LLVM: lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp File Reference
AMDGPUAsmParser.cpp File Reference
#include "AMDGPU.h"
#include "AMDKernelCodeT.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "MCTargetDesc/AMDGPUTargetStreamer.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUAsmUtils.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "Utils/AMDKernelCodeTUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/AMDGPUMetadata.h"
#include "llvm/Support/AMDHSAKernelDescriptor.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <iterator>
#include <map>
#include <memory>
#include <string>
#include "AMDGPUGenAsmMatcher.inc"
Macros
#define PARSE_BITS_ENTRY(FIELD, ENTRY, VALUE, RANGE)
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Functions
static const fltSemantics * getFltSemantics (unsigned Size)
static const fltSemantics * getFltSemantics (MVT VT)
static const fltSemantics * getOpFltSemantics (uint8_t OperandType)
static bool canLosslesslyConvertToFPType (APFloat &FPLiteral, MVT VT)
static bool isSafeTruncation (int64_t Val, unsigned Size)
static bool isInlineValue (unsigned Reg)
static int getRegClass (RegisterKind Is, unsigned RegWidth)
static unsigned getSpecialRegForName (StringRef RegName)
static bool IsRevOpcode (const unsigned Opcode)
static std::string AMDGPUMnemonicSpellCheck (StringRef S, const FeatureBitset &FBS, unsigned VariantID=0)
static void addOptionalImmOperand (MCInst &Inst, const OperandVector &Operands, AMDGPUAsmParser::OptionalImmIndexMap &OptionalIdx, AMDGPUOperand::ImmTy ImmT, int64_t Default=0)
static bool encodeCnt (const AMDGPU::IsaVersion ISA, int64_t &IntVal, int64_t CntVal, bool Saturate, unsigned(*encode)(const IsaVersion &Version, unsigned, unsigned), unsigned(*decode)(const IsaVersion &Version, unsigned))
static LLVM_READNONE unsigned encodeBitmaskPerm (const unsigned AndMask, const unsigned OrMask, const unsigned XorMask)
static bool ConvertOmodMul (int64_t &Mul)
static bool ConvertOmodDiv (int64_t &Div)
static bool ConvertBoundCtrl (int64_t &BoundCtrl)
static bool isRegOrImmWithInputMods (const MCInstrDesc &Desc, unsigned OpNum)
void LLVMInitializeAMDGPUAsmParser ()
Force static initialization.
Variables
static const StringRef Registers []
static const OptionalOperand AMDGPUOptionalOperandTable []
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 1002 of file AMDGPUAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 6806 of file AMDGPUAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 6807 of file AMDGPUAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 6805 of file AMDGPUAsmParser.cpp.
PARSE_BITS_ENTRY
#define PARSE_BITS_ENTRY (FIELD, ENTRY, VALUE, RANGE)
Value:
  if (!isUInt<ENTRY##_WIDTH>(VALUE))                                           \
    return OutOfRangeError(RANGE);                                             \
  AMDHSA_BITS_SET(FIELD, ENTRY, VALUE);
Function Documentation
addOptionalImmOperand()
static void addOptionalImmOperand (MCInst & Inst, const OperandVector & Operands, AMDGPUAsmParser::OptionalImmIndexMap & OptionalIdx, AMDGPUOperand::ImmTy ImmT, int64_t Default = 0) static
Definition at line 4521 of file AMDGPUAsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Default, and Idx.
AMDGPUMnemonicSpellCheck()
static std::string AMDGPUMnemonicSpellCheck (StringRef S, const FeatureBitset & FBS, unsigned VariantID = 0) static
canLosslesslyConvertToFPType()
static bool canLosslesslyConvertToFPType (APFloat & FPLiteral, MVT VT) static
Definition at line 1477 of file AMDGPUAsmParser.cpp.
ConvertBoundCtrl()
static bool ConvertBoundCtrl (int64_t & BoundCtrl) static
Definition at line 5882 of file AMDGPUAsmParser.cpp.
ConvertOmodDiv()
static bool ConvertOmodDiv (int64_t & Div) static
Definition at line 5868 of file AMDGPUAsmParser.cpp.
ConvertOmodMul()
static bool ConvertOmodMul (int64_t & Mul) static
Definition at line 5860 of file AMDGPUAsmParser.cpp.
encodeBitmaskPerm()
static LLVM_READNONE unsigned encodeBitmaskPerm (const unsigned AndMask, const unsigned OrMask, const unsigned XorMask) static
Definition at line 5283 of file AMDGPUAsmParser.cpp.
encodeCnt()
static bool encodeCnt (const AMDGPU::IsaVersion ISA, int64_t & IntVal, int64_t CntVal, bool Saturate, unsigned(*)(const IsaVersion &Version, unsigned, unsigned) encode, unsigned(*)(const IsaVersion &Version, unsigned) decode) static
Definition at line 4736 of file AMDGPUAsmParser.cpp.
References decode(), and llvm::Failed().
getFltSemantics() [1/2]
static const fltSemantics * getFltSemantics (MVT VT) static
Definition at line 1437 of file AMDGPUAsmParser.cpp.
getFltSemantics() [2/2]
static const fltSemantics * getFltSemantics (unsigned Size) static
Definition at line 1424 of file AMDGPUAsmParser.cpp.
getOpFltSemantics()
static const fltSemantics * getOpFltSemantics (uint8_t OperandType) static
Definition at line 1441 of file AMDGPUAsmParser.cpp.
getRegClass()
static int getRegClass (RegisterKind Is, unsigned RegWidth) static
Definition at line 1865 of file AMDGPUAsmParser.cpp.
Referenced by llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::AVRRegisterInfo::shouldCoalesce(), and llvm::X86InstrInfo::unfoldMemoryOperand().
getSpecialRegForName()
static unsigned getSpecialRegForName (StringRef RegName) static
Definition at line 1907 of file AMDGPUAsmParser.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
isInlineValue()
static bool isInlineValue (unsigned Reg) static
Definition at line 1840 of file AMDGPUAsmParser.cpp.
isRegOrImmWithInputMods()
static bool isRegOrImmWithInputMods (const MCInstrDesc & Desc, unsigned OpNum) static
Definition at line 6049 of file AMDGPUAsmParser.cpp.
References llvm::MCInstrDesc::getOperandConstraint(), llvm::MCInstrDesc::NumOperands, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, and llvm::MCOperandInfo::RegClass.
IsRevOpcode()
static bool IsRevOpcode (const unsigned Opcode) static
Definition at line 2989 of file AMDGPUAsmParser.cpp.
isSafeTruncation()
static bool isSafeTruncation (int64_t Val, unsigned Size) static
Definition at line 1495 of file AMDGPUAsmParser.cpp.
LLVMInitializeAMDGPUAsmParser()
void LLVMInitializeAMDGPUAsmParser ()
Force static initialization.
Definition at line 6800 of file AMDGPUAsmParser.cpp.
References A, B, llvm::getTheAMDGPUTarget(), and llvm::getTheGCNTarget().
Variable Documentation
AMDGPUOptionalOperandTable
const OptionalOperand AMDGPUOptionalOperandTable[] static
Definition at line 5897 of file AMDGPUAsmParser.cpp.
Registers
const StringRef Registers[] static
Initial value:
= {
  { "v" },
  { "s" },
  { "ttmp" },
  { "acc" },
  { "a" },
}
Definition at line 2011 of file AMDGPUAsmParser.cpp.
Referenced by ConsecutiveRegisters().