LLVM: lib/Target/AMDGPU/AMDGPURegisterBankInfo.cpp File Reference
AMDGPURegisterBankInfo.cpp File Reference
This file implements the targeting of the RegisterBankInfo class for AMDGPU.
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
#include "llvm/CodeGen/GlobalISel/RegisterBankInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Constants.h"
#include "AMDGPUGenRegisterBank.inc"
#include "AMDGPUGenRegisterBankInfo.def"
Macros
#define GET_TARGET_REGBANK_IMPL
Functions
static bool isInstrUniform (const MachineInstr &MI)
static void setRegsToType (MachineRegisterInfo &MRI, ArrayRef< Register > Regs, LLT NewTy)
Replace the current type each register in Regs has with NewTy.
static LLT getHalfSizedType (LLT Ty)
static MachineInstr * getOtherVRegDef (const MachineRegisterInfo &MRI, Register Reg, const MachineInstr &MI)
static void substituteSimpleCopyRegs (const AMDGPURegisterBankInfo::OperandsMapper &OpdMapper, unsigned OpIdx)
Detailed Description
This file implements the targeting of the RegisterBankInfo class for AMDGPU.
Todo:
This should be generated by TableGen.
Definition in file AMDGPURegisterBankInfo.cpp.
Macro Definition Documentation
GET_TARGET_REGBANK_IMPL
#define GET_TARGET_REGBANK_IMPL
Definition at line 29 of file AMDGPURegisterBankInfo.cpp.
Function Documentation
getHalfSizedType()
static LLT getHalfSizedType (LLT Ty) static
Definition at line 595 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::scalarOrVector().
getOtherVRegDef()
static MachineInstr * getOtherVRegDef (const MachineRegisterInfo & MRI, Register Reg, const MachineInstr & MI) static
Definition at line 936 of file AMDGPURegisterBankInfo.cpp.
References MI, MRI, and Other.
isInstrUniform()
static bool isInstrUniform (const MachineInstr & MI) static
Definition at line 322 of file AMDGPURegisterBankInfo.cpp.
References llvm::AMDGPUInstrInfo::isUniformMMO(), and MI.
Referenced by llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings().
setRegsToType()
static void setRegsToType (MachineRegisterInfo & MRI, ArrayRef< Register > Regs, LLT NewTy) static
Replace the current type each register in Regs has with NewTy.
Definition at line 587 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getSizeInBits(), and MRI.
substituteSimpleCopyRegs()
static void substituteSimpleCopyRegs (const AMDGPURegisterBankInfo::OperandsMapper & OpdMapper, unsigned OpIdx) static
Definition at line 1018 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::SmallVectorBase::empty(), llvm::RegisterBankInfo::OperandsMapper::getMI(), llvm::MachineInstr::getOperand(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::MachineOperand::setReg(), and llvm::SmallVectorBase::size().