LLVM: lib/Target/AMDGPU/AMDGPULibFunc.cpp File Reference
AMDGPULibFunc.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPULibFunc.h"
#include <llvm/ADT/SmallString.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringSwitch.h>
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include <llvm/Support/raw_ostream.h>
#include <string>
Functions
static int parseVecSize (StringRef &mangledName)
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef &mangledName)
static const char * getItaniumTypeName (AMDGPULibFunc::EType T)
static Type * getIntrinsicParamType (LLVMContext &C, const AMDGPULibFunc::Param &P, bool useAddrSpace)
Function Documentation
getIntrinsicParamType()
static Type * getIntrinsicParamType (LLVMContext & C, const AMDGPULibFunc::Param & P, bool useAddrSpace) static
Definition at line 872 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::ADDR_SPACE, llvm::AMDGPULibFuncBase::BYVALUE, C, llvm::LiveRangeEdit::create(), llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getDoubleTy(), llvm::IRBuilderBase::getFloatTy(), llvm::IRBuilderBase::getHalfTy(), llvm::IRBuilderBase::getInt16Ty(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilderBase::getInt8Ty(), llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, P, llvm::AMDGPULibFuncBase::SAMPLER, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
Referenced by llvm::AMDGPUMangledLibFunc::getFunctionType().
getItaniumTypeName()
static const char * getItaniumTypeName (AMDGPULibFunc::EType T) static
Definition at line 727 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, llvm::AMDGPULibFuncBase::SAMPLER, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
parseNamePrefix()
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef & mangledName) static
Definition at line 540 of file AMDGPULibFunc.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::AMDGPULibFuncBase::HALF, llvm::AMDGPULibFuncBase::NATIVE, llvm::AMDGPULibFuncBase::NOPFX, P, and llvm::StringRef::split().
Referenced by llvm::AMDGPUMangledLibFunc::parseFuncName().
parseVecSize()
static int parseVecSize (StringRef & mangledName) static
Definition at line 529 of file AMDGPULibFunc.cpp.