LLVM: lib/Target/AMDGPU/Utils/AMDKernelCodeTUtils.cpp File Reference
AMDKernelCodeTUtils.cpp File Reference
#include "AMDKernelCodeTUtils.h"
#include "SIDefines.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <utility>
#include "AMDKernelCodeTInfo.h"
Macros
#define RECORD(name, altName, print, parse) #name
#define RECORD(name, altName, print, parse) #altName
#define RECORD(name, altName, print, parse) print
#define RECORD(name, altName, print, parse) parse
Typedefs
using PrintFx = void(*)(StringRef, const amd_kernel_code_t &, raw_ostream &)
using ParseFx = bool(*)(amd_kernel_code_t &, MCAsmParser &MCParser, raw_ostream &Err)
Functions
static ArrayRef< StringRef > get_amd_kernel_code_t_FldNames ()
static ArrayRef< StringRef > get_amd_kernel_code_t_FldAltNames ()
static StringMap< int > createIndexMap (const ArrayRef< StringRef > &names, const ArrayRef< StringRef > &altNames)
static int get_amd_kernel_code_t_FieldIndex (StringRef name)
static StringRef get_amd_kernel_code_t_FieldName (int index)
static raw_ostream & printName (raw_ostream &OS, StringRef Name)
template<typename T , T amd_kernel_code_t::* ptr>
static void printField (StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS)
template<typename T , T amd_kernel_code_t::* ptr, int shift, int width = 1>
static void printBitField (StringRef Name, const amd_kernel_code_t &c, raw_ostream &OS)
static ArrayRef< PrintFx > getPrinterTable ()
static bool expectAbsExpression (MCAsmParser &MCParser, int64_t &Value, raw_ostream &Err)
template<typename T , T amd_kernel_code_t::* ptr>
static bool parseField (amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err)
template<typename T , T amd_kernel_code_t::* ptr, int shift, int width = 1>
static bool parseBitField (amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err)
static ArrayRef< ParseFx > getParserTable ()
Macro Definition Documentation
RECORD [1/4]
#define RECORD (name, altName, print, parse) #name
RECORD [2/4]
#define RECORD (name, altName, print, parse) #altName
RECORD [3/4]
#define RECORD (name, altName, print, parse) print
RECORD [4/4]
#define RECORD (name, altName, print, parse) parse
Typedef Documentation
ParseFx
using ParseFx = bool(*)(amd_kernel_code_t &, MCAsmParser &MCParser, raw_ostream &Err)
Definition at line 156 of file AMDKernelCodeTUtils.cpp.
PrintFx
using PrintFx = void(*)(StringRef, const amd_kernel_code_t &, raw_ostream &)
Definition at line 87 of file AMDKernelCodeTUtils.cpp.
Function Documentation
createIndexMap()
static StringMap< int > createIndexMap (const ArrayRef< StringRef > & names, const ArrayRef< StringRef > & altNames) static
Definition at line 47 of file AMDKernelCodeTUtils.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), and llvm::ArrayRef< T >::size().
Referenced by get_amd_kernel_code_t_FieldIndex().
expectAbsExpression()
static bool expectAbsExpression (MCAsmParser & MCParser, int64_t & Value, raw_ostream & Err) static
Definition at line 119 of file AMDKernelCodeTUtils.cpp.
References llvm::AsmToken::Equal, llvm::MCAsmParser::getLexer(), llvm::MCAsmLexer::isNot(), llvm::MCAsmLexer::Lex(), and llvm::MCAsmParser::parseAbsoluteExpression().
Referenced by parseBitField(), and parseField().
get_amd_kernel_code_t_FieldIndex()
static int get_amd_kernel_code_t_FieldIndex (StringRef name) static
Definition at line 58 of file AMDKernelCodeTUtils.cpp.
References createIndexMap(), get_amd_kernel_code_t_FldAltNames(), get_amd_kernel_code_t_FldNames(), and name.
Referenced by llvm::parseAmdKernelCodeField().
get_amd_kernel_code_t_FieldName()
static StringRef get_amd_kernel_code_t_FieldName (int index) static
Definition at line 64 of file AMDKernelCodeTUtils.cpp.
References get_amd_kernel_code_t_FldNames().
Referenced by llvm::printAmdKernelCodeField().
get_amd_kernel_code_t_FldAltNames()
static ArrayRef< StringRef > get_amd_kernel_code_t_FldAltNames () static
Definition at line 37 of file AMDKernelCodeTUtils.cpp.
References llvm::makeArrayRef().
Referenced by get_amd_kernel_code_t_FieldIndex().
get_amd_kernel_code_t_FldNames()
static ArrayRef< StringRef > get_amd_kernel_code_t_FldNames () static
Definition at line 27 of file AMDKernelCodeTUtils.cpp.
References llvm::makeArrayRef().
Referenced by get_amd_kernel_code_t_FieldIndex(), and get_amd_kernel_code_t_FieldName().
getParserTable()
static ArrayRef< ParseFx > getParserTable () static
Definition at line 159 of file AMDKernelCodeTUtils.cpp.
References llvm::makeArrayRef().
Referenced by llvm::parseAmdKernelCodeField().
getPrinterTable()
static ArrayRef< PrintFx > getPrinterTable () static
Definition at line 89 of file AMDKernelCodeTUtils.cpp.
References llvm::makeArrayRef().
Referenced by llvm::dumpAmdKernelCode(), and llvm::printAmdKernelCodeField().
parseBitField()
template<typename T , T amd_kernel_code_t::* ptr, int shift, int width = 1> static bool parseBitField (amd_kernel_code_t & C, MCAsmParser & MCParser, raw_ostream & Err) static
Definition at line 145 of file AMDKernelCodeTUtils.cpp.
References C, and expectAbsExpression().
parseField()
template<typename T , T amd_kernel_code_t::* ptr> static bool parseField (amd_kernel_code_t & C, MCAsmParser & MCParser, raw_ostream & Err) static
Definition at line 135 of file AMDKernelCodeTUtils.cpp.
References C, and expectAbsExpression().
printBitField()
template<typename T , T amd_kernel_code_t::* ptr, int shift, int width = 1> static void printBitField (StringRef Name, const amd_kernel_code_t & c, raw_ostream & OS) static
Definition at line 81 of file AMDKernelCodeTUtils.cpp.
References Name, and printName().
printField()
template<typename T , T amd_kernel_code_t::* ptr> static void printField (StringRef Name, const amd_kernel_code_t & C, raw_ostream & OS) static
Definition at line 75 of file AMDKernelCodeTUtils.cpp.
References C, Name, and printName().
printName()
static raw_ostream & printName (raw_ostream & OS, StringRef Name) static
Definition at line 70 of file AMDKernelCodeTUtils.cpp.
References Name.
Referenced by printBitField(), and printField().