LLVM: lib/CodeGen/AsmPrinter/AsmPrinter.cpp File Reference
AsmPrinter.cpp File Reference
#include "llvm/CodeGen/AsmPrinter.h"
#include "CodeViewDebug.h"
#include "DwarfDebug.h"
#include "DwarfException.h"
#include "WasmException.h"
#include "WinCFGuard.h"
#include "WinException.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalIndirectSymbol.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/RemarkStreamer.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodePadder.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Pass.h"
#include "llvm/Remarks/Remark.h"
#include "llvm/Remarks/RemarkFormat.h"
#include "llvm/Remarks/RemarkStringTable.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <iterator>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "asm-printer"
Typedefs
using gcp_map_type = DenseMap< GCStrategy *, std::unique_ptr< GCMetadataPrinter > >
Functions
STATISTIC (EmittedInsts, "Number of machine instrs printed")
static gcp_map_type & getGCMap (void *&P)
static unsigned getGVAlignmentLog2 (const GlobalValue *GV, const DataLayout &DL, unsigned InBits=0)
getGVAlignmentLog2 - Return the alignment to use for the specified global value in log2 form.
static bool canBeHidden (const GlobalValue *GV, const MCAsmInfo &MAI)
static void emitComments (const MachineInstr &MI, raw_ostream &CommentOS)
emitComments - Pretty-print comments for instructions.
static void emitKill (const MachineInstr *MI, AsmPrinter &AP)
static bool emitDebugValueComment (const MachineInstr *MI, AsmPrinter &AP)
emitDebugValueComment - This method handles the target-independent form of DBG_VALUE, returning true if it was able to do so.
static bool emitDebugLabelComment (const MachineInstr *MI, AsmPrinter &AP)
This method handles the target-independent form of DBG_LABEL, returning true if it was able to do so.
static bool needFuncLabelsForEHOrDebugInfo (const MachineFunction &MF, MachineModuleInfo *MMI)
static unsigned getNumGlobalVariableUses (const Constant *C)
Compute the number of Global Variables that uses a Constant.
static bool isGOTEquivalentCandidate (const GlobalVariable *GV, unsigned &NumGOTEquivUsers)
Only consider global GOT equivalents if at least one user is a cstexpr inside an initializer of another global variables.
static void emitGlobalConstantImpl (const DataLayout &DL, const Constant *C, AsmPrinter &AP, const Constant *BaseCV=nullptr, uint64_t Offset=0)
static void emitGlobalConstantFP (const ConstantFP *CFP, AsmPrinter &AP)
static void emitGlobalConstantFP (APFloat APF, Type *ET, AsmPrinter &AP)
static int isRepeatedByteSequence (const ConstantDataSequential *V)
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
static int isRepeatedByteSequence (const Value *V, const DataLayout &DL)
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
static void emitGlobalConstantDataSequential (const DataLayout &DL, const ConstantDataSequential *CDS, AsmPrinter &AP)
static void emitGlobalConstantArray (const DataLayout &DL, const ConstantArray *CA, AsmPrinter &AP, const Constant *BaseCV, uint64_t Offset)
static void emitGlobalConstantVector (const DataLayout &DL, const ConstantVector *CV, AsmPrinter &AP)
static void emitGlobalConstantStruct (const DataLayout &DL, const ConstantStruct *CS, AsmPrinter &AP, const Constant *BaseCV, uint64_t Offset)
static void emitGlobalConstantLargeInt (const ConstantInt *CI, AsmPrinter &AP)
static void handleIndirectSymViaGOTPCRel (AsmPrinter &AP, const MCExpr **ME, const Constant *BaseCst, uint64_t Offset)
Transform a not absolute MCExpr containing a reference to a GOT equivalent global, by a target specific GOT pc relative access to the final symbol.
static void PrintParentLoopComment (raw_ostream &OS, const MachineLoop *Loop, unsigned FunctionNumber)
PrintParentLoopComment - Print comments about parent loops of this one.
static void PrintChildLoopComment (raw_ostream &OS, const MachineLoop *Loop, unsigned FunctionNumber)
PrintChildLoopComment - Print comments about child loops within the loop for this basic block, with nesting.
static void emitBasicBlockLoopComments (const MachineBasicBlock &MBB, const MachineLoopInfo *LI, const AsmPrinter &AP)
emitBasicBlockLoopComments - Pretty-print comments for basic blocks.
Variables
static const char *const DWARFGroupName = "dwarf"
static const char *const DWARFGroupDescription = "DWARF Emission"
static const char *const DbgTimerName = "emit"
static const char *const DbgTimerDescription = "Debug Info Emission"
static const char *const EHTimerName = "write_exception"
static const char *const EHTimerDescription = "DWARF Exception Writer"
static const char *const CFGuardName = "Control Flow Guard"
static const char *const CFGuardDescription = "Control Flow Guard Tables"
static const char *const CodeViewLineTablesGroupName = "linetables"
static const char *const CodeViewLineTablesGroupDescription
static cl::opt< bool > EnableRemarksSection ("remarks-section", cl::desc("Emit a section containing remark diagnostics metadata"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 131 of file AsmPrinter.cpp.
Typedef Documentation
gcp_map_type
using gcp_map_type = DenseMap<GCStrategy *, std::unique_ptr<GCMetadataPrinter> >
Definition at line 154 of file AsmPrinter.cpp.
Function Documentation
canBeHidden()
static bool canBeHidden (const GlobalValue * GV, const MCAsmInfo & MAI) static
Definition at line 390 of file AsmPrinter.cpp.
References llvm::GlobalValue::canBeOmittedFromSymbolTable(), and llvm::MCAsmInfo::hasWeakDefCanBeHiddenDirective().
Referenced by llvm::AsmPrinter::EmitLinkage().
emitBasicBlockLoopComments()
static void emitBasicBlockLoopComments (const MachineBasicBlock & MBB, const MachineLoopInfo * LI, const AsmPrinter & AP) static
emitBasicBlockLoopComments - Pretty-print comments for basic blocks.
Definition at line 2880 of file AsmPrinter.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::empty(), llvm::AsmPrinter::getFunctionNumber(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::MachineLoopInfo::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::raw_ostream::indent(), llvm::AsmPrinter::OutStreamer, PrintChildLoopComment(), and PrintParentLoopComment().
Referenced by llvm::AsmPrinter::EmitBasicBlockStart().
emitComments()
static void emitComments (const MachineInstr & MI, raw_ostream & CommentOS) static
emitComments - Pretty-print comments for instructions.
Definition at line 757 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), MI, llvm::MachineInstr::ReloadReuse, Size, and TII.
Referenced by llvm::AsmPrinter::EmitFunctionBody().
emitDebugLabelComment()
static bool emitDebugLabelComment (const MachineInstr * MI, AsmPrinter & AP) static
This method handles the target-independent form of DBG_LABEL, returning true if it was able to do so.
A false return means the target will need to handle MI in EmitInstruction.
Definition at line 904 of file AsmPrinter.cpp.
References llvm::DILabel::getName(), llvm::DILabel::getScope(), MI, Name, llvm::AsmPrinter::OutStreamer, and llvm::raw_svector_ostream::str().
Referenced by llvm::AsmPrinter::EmitFunctionBody().
emitDebugValueComment()
static bool emitDebugValueComment (const MachineInstr * MI, AsmPrinter & AP) static
emitDebugValueComment - This method handles the target-independent form of DBG_VALUE, returning true if it was able to do so.
A false return means the target will need to handle MI in EmitInstruction.
Definition at line 814 of file AsmPrinter.cpp.
References assert(), llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::DIExpression::expr_ops(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::DIVariable::getName(), llvm::DIExpression::getNumElements(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::DILocalVariable::getScope(), llvm::MachineFunction::getSubtarget(), I, llvm::APFloatBase::IEEEdouble(), ignored(), llvm::AsmPrinter::MF, MI, Name, llvm::dwarf::OperationEncodingString(), llvm::AsmPrinter::OutStreamer, llvm::Pass::print(), llvm::printReg(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::raw_svector_ostream::str().
Referenced by llvm::AsmPrinter::EmitFunctionBody().
emitGlobalConstantArray()
static void emitGlobalConstantArray (const DataLayout & DL, const ConstantArray * CA, AsmPrinter & AP, const Constant * BaseCV, uint64_t Offset) static
Definition at line 2424 of file AsmPrinter.cpp.
References emitGlobalConstantImpl(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::ConstantArray::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), isRepeatedByteSequence(), and llvm::AsmPrinter::OutStreamer.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantDataSequential()
static void emitGlobalConstantDataSequential (const DataLayout & DL, const ConstantDataSequential * CDS, AsmPrinter & AP) static
Definition at line 2384 of file AsmPrinter.cpp.
References assert(), E, emitGlobalConstantFP(), llvm::format(), llvm::ConstantDataSequential::getAsString(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::ConstantDataSequential::getElementByteSize(), llvm::ConstantDataSequential::getElementType(), llvm::SequentialType::getElementType(), llvm::ConstantDataSequential::getNumElements(), llvm::ConstantDataSequential::getType(), llvm::DataLayout::getTypeAllocSize(), I, isRepeatedByteSequence(), llvm::ConstantDataSequential::isString(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantFP() [1/2]
static void emitGlobalConstantFP (APFloat APF, Type * ET, AsmPrinter & AP) static
Definition at line 2483 of file AsmPrinter.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getNumWords(), llvm::APInt::getRawData(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeStoreSize(), llvm::DataLayout::isBigEndian(), llvm::Type::isPPC_FP128Ty(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, llvm::Type::print(), and llvm::APFloat::toString().
emitGlobalConstantFP() [2/2]
static void emitGlobalConstantFP (const ConstantFP * CFP, AsmPrinter & AP) static
Definition at line 2530 of file AsmPrinter.cpp.
References emitGlobalConstantFP(), llvm::Value::getType(), and llvm::ConstantFP::getValueAPF().
Referenced by emitGlobalConstantDataSequential(), emitGlobalConstantFP(), and emitGlobalConstantImpl().
emitGlobalConstantImpl()
static void emitGlobalConstantImpl (const DataLayout & DL, const Constant * C, AsmPrinter & AP, const Constant * BaseCV = nullptr, uint64_t Offset = 0) static
Definition at line 2681 of file AsmPrinter.cpp.
References llvm::ConstantFoldConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::format(), llvm::AsmPrinter::getObjFileLowering(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), handleIndirectSymViaGOTPCRel(), llvm::Value::hasOneUse(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::lowerConstant(), llvm::AsmPrinter::OutStreamer, Size, llvm::TargetLoweringObjectFile::supportIndirectSymViaGOTPCRel(), and llvm::Value::user_back().
Referenced by llvm::AsmPrinter::EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantImpl(), emitGlobalConstantStruct(), and emitGlobalConstantVector().
emitGlobalConstantLargeInt()
static void emitGlobalConstantLargeInt (const ConstantInt * CI, AsmPrinter & AP) static
Definition at line 2534 of file AsmPrinter.cpp.
References assert(), llvm::ConstantInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getRawData(), llvm::ConstantInt::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ConstantInt::getValue(), llvm::DataLayout::isBigEndian(), llvm::APInt::lshrInPlace(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantStruct()
static void emitGlobalConstantStruct (const DataLayout & DL, const ConstantStruct * CS, AsmPrinter & AP, const Constant * BaseCV, uint64_t Offset) static
Definition at line 2455 of file AsmPrinter.cpp.
References assert(), emitGlobalConstantImpl(), llvm::StructLayout::getElementOffset(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::ConstantStruct::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantVector()
static void emitGlobalConstantVector (const DataLayout & DL, const ConstantVector * CV, AsmPrinter & AP) static
Definition at line 2443 of file AsmPrinter.cpp.
References emitGlobalConstantImpl(), llvm::SequentialType::getElementType(), llvm::SequentialType::getNumElements(), llvm::User::getOperand(), llvm::ConstantVector::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitKill()
static void emitKill (const MachineInstr * MI, AsmPrinter & AP) static
Definition at line 797 of file AsmPrinter.cpp.
References assert(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutStreamer, llvm::printReg(), and llvm::raw_string_ostream::str().
Referenced by llvm::AsmPrinter::EmitFunctionBody().
getGCMap()
static gcp_map_type & getGCMap (void *& P) static
Definition at line 156 of file AsmPrinter.cpp.
References P.
Referenced by llvm::AsmPrinter::~AsmPrinter().
getGVAlignmentLog2()
static unsigned getGVAlignmentLog2 (const GlobalValue * GV, const DataLayout & DL, unsigned InBits = 0) static
getGVAlignmentLog2 - Return the alignment to use for the specified global value in log2 form.
This rounds up to the preferred alignment if possible and legal.
Definition at line 165 of file AsmPrinter.cpp.
References llvm::GlobalValue::getAlignment(), llvm::DataLayout::getPreferredAlignmentLog(), llvm::GlobalValue::hasSection(), and llvm::Log2_32().
Referenced by llvm::AsmPrinter::EmitAlignment(), and llvm::AsmPrinter::EmitGlobalVariable().
getNumGlobalVariableUses()
static unsigned getNumGlobalVariableUses (const Constant * C) static
Compute the number of Global Variables that uses a Constant.
Definition at line 1215 of file AsmPrinter.cpp.
References C, and getNumGlobalVariableUses().
Referenced by getNumGlobalVariableUses(), and isGOTEquivalentCandidate().
handleIndirectSymViaGOTPCRel()
static void handleIndirectSymViaGOTPCRel (AsmPrinter & AP, const MCExpr ** ME, const Constant * BaseCst, uint64_t Offset) static
Transform a not absolute MCExpr containing a reference to a GOT equivalent global, by a target specific GOT pc relative access to the final symbol.
Definition at line 2593 of file AsmPrinter.cpp.
References llvm::MCValue::getConstant(), llvm::TargetLoweringObjectFile::getIndirectSymViaGOTPCRel(), llvm::AsmPrinter::getObjFileLowering(), llvm::User::getOperand(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::GlobalGOTEquivs, llvm::MCValue::isAbsolute(), llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, and llvm::TargetLoweringObjectFile::supportGOTPCRelWithOffset().
Referenced by emitGlobalConstantImpl().
isGOTEquivalentCandidate()
static bool isGOTEquivalentCandidate (const GlobalVariable * GV, unsigned & NumGOTEquivUsers) static
Only consider global GOT equivalents if at least one user is a cstexpr inside an initializer of another global variables.
Also, don't handle cstexpr inside instructions. During global variable emission, candidates are skipped and are emitted later in case at least one cstexpr isn't replaced by a PC relative GOT entry access.
Definition at line 1234 of file AsmPrinter.cpp.
References getNumGlobalVariableUses(), llvm::User::getOperand(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDiscardableIfUnused(), and llvm::Value::users().
Referenced by llvm::AsmPrinter::computeGlobalGOTEquivs().
isRepeatedByteSequence() [1/2]
static int isRepeatedByteSequence (const ConstantDataSequential * V) static
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
If it is not a repeated sequence, return -1.
Definition at line 2338 of file AsmPrinter.cpp.
References assert(), C, llvm::Data, and llvm::ConstantDataSequential::getRawDataValues().
Referenced by emitGlobalConstantArray(), emitGlobalConstantDataSequential(), and isRepeatedByteSequence().
isRepeatedByteSequence() [2/2]
static int isRepeatedByteSequence (const Value * V, const DataLayout & DL) static
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
If it is not a repeated sequence, return -1.
Definition at line 2350 of file AsmPrinter.cpp.
References assert(), llvm::User::getOperand(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSizeInBits(), isRepeatedByteSequence(), and Size.
needFuncLabelsForEHOrDebugInfo()
static bool needFuncLabelsForEHOrDebugInfo (const MachineFunction & MF, MachineModuleInfo * MMI) static
Definition at line 1000 of file AsmPrinter.cpp.
References llvm::classifyEHPersonality(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getLandingPads(), llvm::Function::getPersonalityFn(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::MachineFunction::hasEHFunclets(), llvm::Function::hasPersonalityFn(), and llvm::isNoOpWithoutInvoke().
Referenced by llvm::AsmPrinter::EmitFunctionBody(), and llvm::AsmPrinter::SetupMachineFunction().
PrintChildLoopComment()
static void PrintChildLoopComment (raw_ostream & OS, const MachineLoop * Loop, unsigned FunctionNumber) static
PrintChildLoopComment - Print comments about child loops within the loop for this basic block, with nesting.
Definition at line 2867 of file AsmPrinter.cpp.
References llvm::raw_ostream::indent(), and PrintChildLoopComment().
Referenced by emitBasicBlockLoopComments(), and PrintChildLoopComment().
PrintParentLoopComment()
static void PrintParentLoopComment (raw_ostream & OS, const MachineLoop * Loop, unsigned FunctionNumber) static
PrintParentLoopComment - Print comments about parent loops of this one.
Definition at line 2855 of file AsmPrinter.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::raw_ostream::indent(), and PrintParentLoopComment().
Referenced by emitBasicBlockLoopComments(), and PrintParentLoopComment().
STATISTIC()
STATISTIC (EmittedInsts , "Number of machine instrs printed")
Variable Documentation
CFGuardDescription
const char* const CFGuardDescription = "Control Flow Guard Tables" static
Definition at line 140 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
CFGuardName
const char* const CFGuardName = "Control Flow Guard" static
Definition at line 139 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
CodeViewLineTablesGroupDescription
const char* const CodeViewLineTablesGroupDescription static
Initial value:
=
  "CodeView Line Tables"
Definition at line 142 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
CodeViewLineTablesGroupName
const char* const CodeViewLineTablesGroupName = "linetables" static
Definition at line 141 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
DbgTimerDescription
const char* const DbgTimerDescription = "Debug Info Emission" static
Definition at line 136 of file AsmPrinter.cpp.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::AsmPrinter::doInitialization().
DbgTimerName
const char* const DbgTimerName = "emit" static
Definition at line 135 of file AsmPrinter.cpp.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::AsmPrinter::doInitialization().
DWARFGroupDescription
const char* const DWARFGroupDescription = "DWARF Emission" static
Definition at line 134 of file AsmPrinter.cpp.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::AsmPrinter::doInitialization().
DWARFGroupName
const char* const DWARFGroupName = "dwarf" static
Definition at line 133 of file AsmPrinter.cpp.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::AsmPrinter::doInitialization().
EHTimerDescription
const char* const EHTimerDescription = "DWARF Exception Writer" static
Definition at line 138 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
EHTimerName
const char* const EHTimerName = "write_exception" static
Definition at line 137 of file AsmPrinter.cpp.
Referenced by llvm::AsmPrinter::doInitialization().
EnableRemarksSection
cl::opt< bool > EnableRemarksSection("remarks-section", cl::desc("Emit a section containing remark diagnostics metadata"), cl::init(false)) ("remarks-section" , cl::desc("Emit a section containing remark diagnostics metadata") , cl::init(false)) static
Referenced by llvm::AsmPrinter::doFinalization().