LLVM: lib/Analysis/BlockFrequencyInfo.cpp File Reference
BlockFrequencyInfo.cpp File Reference
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/iterator.h"
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <string>
Classes
struct llvm::GraphTraits< BlockFrequencyInfo * >
struct llvm::DOTGraphTraits< BlockFrequencyInfo * >
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "block-freq"
Typedefs
using llvm::BFIDOTGTraitsBase = BFIDOTGraphTraitsBase< BlockFrequencyInfo, BranchProbabilityInfo >
Functions
static GVDAGType llvm::getGVDT ()
INITIALIZE_PASS_BEGIN (BlockFrequencyInfoWrapperPass, "block-freq", "Block Frequency Analysis", true, true) INITIALIZE_PASS_END(BlockFrequencyInfoWrapperPass
Variables
static cl::opt< GVDAGType > ViewBlockFreqPropagationDAG ("view-block-freq-propagation-dags", cl::Hidden, cl::desc("Pop up a window to show a dag displaying how block " "frequencies propagation through the CFG."), cl::values(clEnumValN(GVDT_None, "none", "do not display graphs."), clEnumValN(GVDT_Fraction, "fraction", "display a graph using the " "fractional block frequency representation."), clEnumValN(GVDT_Integer, "integer", "display a graph using the raw " "integer fractional block frequency representation."), clEnumValN(GVDT_Count, "count", "display a graph using the real " "profile count if available.")))
cl::opt< std::string > ViewBlockFreqFuncName ("view-bfi-func-name", cl::Hidden, cl::desc("The option to specify " "the name of the function " "whose CFG will be displayed."))
cl::opt< unsigned > ViewHotFreqPercent ("view-hot-freq-percent", cl::init(10), cl::Hidden, cl::desc("An integer in percent used to specify " "the hot blocks/edges to be displayed " "in red: a block or edge whose frequency " "is no less than the max frequency of the " "function multiplied by this percent."))
cl::opt< PGOViewCountsType > PGOViewCounts ("pgo-view-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text with " "block profile counts and branch probabilities " "right after PGO profile annotation step. The " "profile counts are computed using branch " "probabilities from the runtime profile data and " "block frequency propagation algorithm. To view " "the raw counts from the profile, use option " "-pgo-view-raw-counts instead. To limit graph " "display to only one function, use filtering option " "-view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text.")))
static cl::opt< bool > PrintBlockFreq ("print-bfi", cl::init(false), cl::Hidden, cl::desc("Print the block frequency info."))
cl::opt< std::string > PrintBlockFreqFuncName ("print-bfi-func-name", cl::Hidden, cl::desc("The option to specify the name of the function " "whose block frequency info is printed."))
block freq
block Block Frequency Analysis
block Block Frequency true
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "block-freq"
Definition at line 33 of file BlockFrequencyInfo.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (BlockFrequencyInfoWrapperPass , "block-freq" , "Block Frequency Analysis" , true , true)
Variable Documentation
Analysis
block Block Frequency Analysis
Definition at line 294 of file BlockFrequencyInfo.cpp.
Referenced by llvm::yaml::MappingTraits< remarks::Remark * >::mapping(), llvm::PassInstrumentation::runAfterAnalysis(), llvm::PassInstrumentation::runBeforeAnalysis(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), and llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction().
freq
block freq
Definition at line 293 of file BlockFrequencyInfo.cpp.
Referenced by llvm::SpillPlacement::Node::addBias().
PGOViewCounts
cl::opt< PGOViewCountsType > PGOViewCounts("pgo-view-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text with " "block profile counts and branch probabilities " "right after PGO profile annotation step. The " "profile counts are computed using branch " "probabilities from the runtime profile data and " "block frequency propagation algorithm. To view " "the raw counts from the profile, use option " "-pgo-view-raw-counts instead. To limit graph " "display to only one function, use filtering option " "-view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text."))) ("pgo-view-counts" , cl::Hidden , cl::desc("A boolean option to show CFG dag or text with " "block profile counts and branch probabilities " "right after PGO profile annotation step. The " "profile counts are computed using branch " "probabilities from the runtime profile data and " "block frequency propagation algorithm. To view " "the raw counts from the profile, use option " "-pgo-view-raw-counts instead. To limit graph " "display to only one function, use filtering option " "-view-bfi-func-name.") , cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text.")))
Referenced by annotateAllFunctions(), and llvm::getGVDT().
PrintBlockFreq
cl::opt< bool > PrintBlockFreq("print-bfi", cl::init(false), cl::Hidden, cl::desc("Print the block frequency info.")) ("print-bfi" , cl::init(false) , cl::Hidden , cl::desc("Print the block frequency info.")) static
Referenced by llvm::BlockFrequencyInfo::calculate().
PrintBlockFreqFuncName
cl::opt< std::string > PrintBlockFreqFuncName("print-bfi-func-name", cl::Hidden, cl::desc("The option to specify the name of the function " "whose block frequency info is printed.")) ("print-bfi-func-name" , cl::Hidden , cl::desc("The option to specify the name of the function " "whose block frequency info is printed."))
Referenced by llvm::BlockFrequencyInfo::calculate(), and llvm::MachineBlockFrequencyInfo::calculate().
true
dot regions Print regions of function to dot true view regions View regions of true
Examples
/home/tommy/workspace/llvm/9.0.1/llvm-9.0.1.src/include/llvm/ADT/ilist_node.h.
Definition at line 294 of file BlockFrequencyInfo.cpp.
Referenced by llvm::DWARFUnitHeader::extract(), hasBZHI(), llvm::X86CallLowering::lowerCall(), matchIntrinsicType(), and llvm::ScopedHandle< HandleTraits >::operator bool().
ViewBlockFreqFuncName
cl::opt< std::string > ViewBlockFreqFuncName("view-bfi-func-name", cl::Hidden, cl::desc("The option to specify " "the name of the function " "whose CFG will be displayed.")) ("view-bfi-func-name" , cl::Hidden , cl::desc("The option to specify " "the name of the function " "whose CFG will be displayed."))
Referenced by annotateAllFunctions(), llvm::BlockFrequencyInfo::calculate(), and llvm::MachineBlockFrequencyInfo::calculate().
ViewBlockFreqPropagationDAG
cl::opt< GVDAGType > ViewBlockFreqPropagationDAG("view-block-freq-propagation-dags", cl::Hidden, cl::desc("Pop up a window to show a dag displaying how block " "frequencies propagation through the CFG."), cl::values(clEnumValN(GVDT_None, "none", "do not display graphs."), clEnumValN(GVDT_Fraction, "fraction", "display a graph using the " "fractional block frequency representation."), clEnumValN(GVDT_Integer, "integer", "display a graph using the raw " "integer fractional block frequency representation."), clEnumValN(GVDT_Count, "count", "display a graph using the real " "profile count if available."))) ("view-block-freq-propagation-dags" , cl::Hidden , cl::desc("Pop up a window to show a dag displaying how block " "frequencies propagation through the CFG.") , cl::values(clEnumValN(GVDT_None, "none", "do not display graphs."), clEnumValN(GVDT_Fraction, "fraction", "display a graph using the " "fractional block frequency representation."), clEnumValN(GVDT_Integer, "integer", "display a graph using the raw " "integer fractional block frequency representation."), clEnumValN(GVDT_Count, "count", "display a graph using the real " "profile count if available."))) static
Referenced by llvm::BlockFrequencyInfo::calculate(), and llvm::getGVDT().
ViewHotFreqPercent
cl::opt< unsigned > ViewHotFreqPercent("view-hot-freq-percent", cl::init(10), cl::Hidden, cl::desc("An integer in percent used to specify " "the hot blocks/edges to be displayed " "in red: a block or edge whose frequency " "is no less than the max frequency of the " "function multiplied by this percent.")) ("view-hot-freq-percent" , cl::init(10) , cl::Hidden , cl::desc("An integer in percent used to specify " "the hot blocks/edges to be displayed " "in red: a block or edge whose frequency " "is no less than the max frequency of the " "function multiplied by this percent."))
Referenced by llvm::DOTGraphTraits< BlockFrequencyInfo * >::getEdgeAttributes(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getEdgeAttributes(), llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeAttributes(), and llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeAttributes().