LLVM: lib/Target/BPF/BPFTargetMachine.cpp File Reference
BPFTargetMachine.cpp File Reference
#include "BPFTargetMachine.h"
#include "BPF.h"
#include "MCTargetDesc/BPFMCAsmInfo.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
Functions
void LLVMInitializeBPFTarget ()
static std::string computeDataLayout (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
Variables
static cl::opt< bool > DisableMIPeephole ("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF"))
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 42 of file BPFTargetMachine.cpp.
References llvm::Triple::bpfeb, and TT.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 49 of file BPFTargetMachine.cpp.
References llvm::Reloc::PIC_.
LLVMInitializeBPFTarget()
void LLVMInitializeBPFTarget ()
Definition at line 30 of file BPFTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), llvm::initializeBPFAbstractMemberAccessPass(), llvm::initializeBPFMIPeepholePass(), X, Y, and llvm::Z.
Variable Documentation
DisableMIPeephole
cl::opt< bool > DisableMIPeephole("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF")) ("disable-bpf-peephole" , cl::Hidden , cl::desc("Disable machine peepholes for BPF")) static