LLVM: lib/Analysis/CFG.cpp File Reference
CFG.cpp File Reference
#include "llvm/Analysis/CFG.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/Dominators.h"
Functions
static const Loop * getOutermostLoop (const LoopInfo *LI, const BasicBlock *BB)
Function Documentation
getOutermostLoop()
static const Loop * getOutermostLoop (const LoopInfo * LI, const BasicBlock * BB) static
Definition at line 114 of file CFG.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), and llvm::LoopBase< BlockT, LoopT >::getParentLoop().
Referenced by llvm::isPotentiallyReachableFromMany().