LLVM: llvm::SIScheduleBlockScheduler Class Reference
llvm::SIScheduleBlockScheduler Class Reference
#include "Target/AMDGPU/SIMachineScheduler.h"
Public Member Functions
SIScheduleBlockScheduler (SIScheduleDAGMI *DAG, SISchedulerBlockSchedulerVariant Variant, SIScheduleBlocks BlocksStruct)
~SIScheduleBlockScheduler ()=default
std::vector< SIScheduleBlock * > getBlocks ()
unsigned getVGPRUsage ()
unsigned getSGPRUsage ()
Detailed Description
Definition at line 322 of file SIMachineScheduler.h.
Constructor & Destructor Documentation
SIScheduleBlockScheduler()
SIScheduleBlockScheduler::SIScheduleBlockScheduler (SIScheduleDAGMI * DAG, SISchedulerBlockSchedulerVariant Variant, SIScheduleBlocks BlocksStruct)
Definition at line 1448 of file SIMachineScheduler.cpp.
References assert(), llvm::dbgs(), llvm::SIScheduleDAGMI::getInRegs(), llvm::SIScheduleDAGMI::getOutRegs(), LLVM_DEBUG, llvm::SIScheduleBlocks::TopDownBlock2Index, and llvm::SIScheduleBlocks::TopDownIndex2Block.
~SIScheduleBlockScheduler()
llvm::SIScheduleBlockScheduler::~SIScheduleBlockScheduler () default
Member Function Documentation
getBlocks()
std::vector< SIScheduleBlock * > llvm::SIScheduleBlockScheduler::getBlocks () inline
Definition at line 355 of file SIMachineScheduler.h.
getSGPRUsage()
unsigned llvm::SIScheduleBlockScheduler::getSGPRUsage () inline
Definition at line 358 of file SIMachineScheduler.h.
getVGPRUsage()
unsigned llvm::SIScheduleBlockScheduler::getVGPRUsage () inline
Definition at line 357 of file SIMachineScheduler.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIMachineScheduler.h
lib/Target/AMDGPU/SIMachineScheduler.cpp