LLVM: TypedVReg Class Reference
TypedVReg Class Reference
Public Member Functions
TypedVReg (unsigned reg)
TypedVReg (VRType type)
bool isReg () const
bool isFrameIndex () const
bool isCandidate () const
VRType getType () const
unsigned getReg () const
Detailed Description
Definition at line 75 of file MIRCanonicalizerPass.cpp.
Constructor & Destructor Documentation
TypedVReg() [1/2]
TypedVReg::TypedVReg (unsigned reg) inline
Definition at line 80 of file MIRCanonicalizerPass.cpp.
TypedVReg() [2/2]
TypedVReg::TypedVReg (VRType type) inline
Definition at line 81 of file MIRCanonicalizerPass.cpp.
References assert(), and RSE_Reg.
Member Function Documentation
getReg()
unsigned TypedVReg::getReg () const inline
Definition at line 90 of file MIRCanonicalizerPass.cpp.
References assert(), and isReg().
Referenced by doCandidateWalk().
getType()
VRType TypedVReg::getType () const inline
Definition at line 89 of file MIRCanonicalizerPass.cpp.
isCandidate()
bool TypedVReg::isCandidate () const inline
Definition at line 87 of file MIRCanonicalizerPass.cpp.
References RSE_NewCandidate.
isFrameIndex()
bool TypedVReg::isFrameIndex () const inline
Definition at line 86 of file MIRCanonicalizerPass.cpp.
References RSE_FrameIndex.
isReg()
bool TypedVReg::isReg () const inline
Definition at line 85 of file MIRCanonicalizerPass.cpp.
References RSE_Reg.
Referenced by doCandidateWalk(), and getReg().
The documentation for this class was generated from the following file:
lib/CodeGen/MIRCanonicalizerPass.cpp