LLVM: llvm::DominatorTreePrinterPass Class Reference
llvm::DominatorTreePrinterPass Class Reference
Printer pass for the DominatorTree.
#include "llvm/IR/Dominators.h"
Public Member Functions
DominatorTreePrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DominatorTreePrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the DominatorTree.
Definition at line 243 of file Dominators.h.
Constructor & Destructor Documentation
DominatorTreePrinterPass()
DominatorTreePrinterPass::DominatorTreePrinterPass (raw_ostream & OS) explicit
Definition at line 332 of file Dominators.cpp.
Member Function Documentation
run()
PreservedAnalyses DominatorTreePrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 334 of file Dominators.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and print().
The documentation for this class was generated from the following files:
include/llvm/IR/Dominators.h
lib/IR/Dominators.cpp