LLVM: llvm::StackSafetyGlobalPrinterPass Class Reference
llvm::StackSafetyGlobalPrinterPass Class Reference
Printer pass for the StackSafetyGlobalAnalysis results.
#include "llvm/Analysis/StackSafetyAnalysis.h"
Public Member Functions
StackSafetyGlobalPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< StackSafetyGlobalPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the StackSafetyGlobalAnalysis results.
Definition at line 90 of file StackSafetyAnalysis.h.
Constructor & Destructor Documentation
StackSafetyGlobalPrinterPass()
llvm::StackSafetyGlobalPrinterPass::StackSafetyGlobalPrinterPass (raw_ostream & OS) inline explicit
Definition at line 95 of file StackSafetyAnalysis.h.
Member Function Documentation
run()
PreservedAnalyses StackSafetyGlobalPrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 629 of file StackSafetyAnalysis.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/StackSafetyAnalysis.h
lib/Analysis/StackSafetyAnalysis.cpp