LLVM: llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > > Class Template Reference
llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/RPCSerialization.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const std::set< T2 > &S)
Serialize a std::set<T> from std::set<T2>.
static Error deserialize (ChannelT &C, std::set< T2 > &S)
Deserialize a std::set<T> to a std::set<T>.
Detailed Description
template<typename ChannelT, typename T, typename T2>
class llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >
Definition at line 614 of file RPCSerialization.h.
Member Function Documentation
deserialize()
template<typename ChannelT , typename T , typename T2 > static Error llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::deserialize (ChannelT & C, std::set< T2 > & S) inline static
Deserialize a std::set<T> to a std::set<T>.
Definition at line 629 of file RPCSerialization.h.
References assert(), C, llvm::orc::rpc::deserializeSeq(), llvm::orc::orcError(), llvm::Error::success(), and llvm::orc::UnknownORCError.
serialize()
template<typename ChannelT , typename T , typename T2 > static Error llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::serialize (ChannelT & C, const std::set< T2 > & S) inline static
Serialize a std::set<T> from std::set<T2>.
Definition at line 617 of file RPCSerialization.h.
References C, E, llvm::orc::rpc::serializeSeq(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCSerialization.h