LLVM: llvm::LanaiInstrInfo Class Reference
llvm::LanaiInstrInfo Class Reference
#include "Target/Lanai/LanaiInstrInfo.h"
Public Member Functions
LanaiInstrInfo ()
virtual const LanaiRegisterInfo & getRegisterInfo () const
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb, AliasAnalysis *AA) const override
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isLoadFromStackSlotPostFE (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, const DebugLoc &DL, unsigned DestinationRegister, unsigned SourceRegister, bool KillSource) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, unsigned SourceRegister, bool IsKill, int FrameIndex, const TargetRegisterClass *RegisterClass, const TargetRegisterInfo *RegisterInfo) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator Position, unsigned DestinationRegister, int FrameIndex, const TargetRegisterClass *RegisterClass, const TargetRegisterInfo *RegisterInfo) const override
bool expandPostRAPseudo (MachineInstr &MI) const override
bool getMemOperandWithOffset (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, const TargetRegisterInfo *TRI) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TrueBlock, MachineBasicBlock *&FalseBlock, SmallVectorImpl< MachineOperand > &Condition, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool analyzeCompare (const MachineInstr &MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const override
bool optimizeCompareInstr (MachineInstr &CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const override
bool analyzeSelect (const MachineInstr &MI, SmallVectorImpl< MachineOperand > &Cond, unsigned &TrueOp, unsigned &FalseOp, bool &Optimizable) const override
MachineInstr * optimizeSelect (MachineInstr &MI, SmallPtrSetImpl< MachineInstr * > &SeenMIs, bool PreferFalse) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Condition) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TrueBlock, MachineBasicBlock *FalseBlock, ArrayRef< MachineOperand > Condition, const DebugLoc &DL, int *BytesAdded=nullptr) const override
Detailed Description
Definition at line 25 of file LanaiInstrInfo.h.
Constructor & Destructor Documentation
LanaiInstrInfo()
LanaiInstrInfo::LanaiInstrInfo ()
Definition at line 30 of file LanaiInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool LanaiInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TrueBlock, MachineBasicBlock *& FalseBlock, SmallVectorImpl< MachineOperand > & Condition, bool AllowModify) const override
Definition at line 563 of file LanaiInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::MachineBasicBlock::isLayoutSuccessor(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
analyzeCompare()
bool LanaiInstrInfo::analyzeCompare (const MachineInstr & MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const override
Definition at line 178 of file LanaiInstrInfo.cpp.
References MI.
analyzeSelect()
bool LanaiInstrInfo::analyzeSelect (const MachineInstr & MI, SmallVectorImpl< MachineOperand > & Cond, unsigned & TrueOp, unsigned & FalseOp, bool & Optimizable) const override
Definition at line 439 of file LanaiInstrInfo.cpp.
References assert(), and MI.
areMemAccessesTriviallyDisjoint()
bool LanaiInstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb, AliasAnalysis * AA) const override
Definition at line 88 of file LanaiInstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineInstr::mayLoadOrStore(), and TRI.
copyPhysReg()
void LanaiInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, const DebugLoc & DL, unsigned DestinationRegister, unsigned SourceRegister, bool KillSource) const override
Definition at line 34 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), and llvm_unreachable.
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > LanaiInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 164 of file LanaiInstrInfo.cpp.
expandPostRAPseudo()
bool LanaiInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 120 of file LanaiInstrInfo.cpp.
getMemOperandWithOffset()
bool LanaiInstrInfo::getMemOperandWithOffset (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, const TargetRegisterInfo * TRI) const override
Definition at line 797 of file LanaiInstrInfo.cpp.
References getMemOperandWithOffsetWidth(), llvm::MachineInstr::getOpcode(), and TRI.
getMemOperandWithOffsetWidth()
bool LanaiInstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Definition at line 758 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, assert(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by areMemAccessesTriviallyDisjoint(), and getMemOperandWithOffset().
getRegisterInfo()
virtual const LanaiRegisterInfo & llvm::LanaiInstrInfo::getRegisterInfo () const inline virtual
Definition at line 34 of file LanaiInstrInfo.h.
Referenced by areMemAccessesTriviallyDisjoint(), llvm::LanaiSubtarget::getRegisterInfo(), and optimizeCompareInstr().
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > LanaiInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 169 of file LanaiInstrInfo.cpp.
References llvm::makeArrayRef().
insertBranch()
unsigned LanaiInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TrueBlock, MachineBasicBlock * FalseBlock, ArrayRef< MachineOperand > Condition, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 661 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::size().
isLoadFromStackSlot()
unsigned LanaiInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 718 of file LanaiInstrInfo.cpp.
References MI.
Referenced by isLoadFromStackSlotPostFE().
isLoadFromStackSlotPostFE()
unsigned LanaiInstrInfo::isLoadFromStackSlotPostFE (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 729 of file LanaiInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::front(), isLoadFromStackSlot(), and MI.
isStoreToStackSlot()
unsigned LanaiInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 747 of file LanaiInstrInfo.cpp.
References MI.
loadRegFromStackSlot()
void LanaiInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, unsigned DestinationRegister, int FrameIndex, const TargetRegisterClass * RegisterClass, const TargetRegisterInfo * RegisterInfo) const override
Definition at line 69 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), and llvm_unreachable.
optimizeCompareInstr()
bool LanaiInstrInfo::optimizeCompareInstr (MachineInstr & CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const override
Definition at line 284 of file LanaiInstrInfo.cpp.
References B, llvm::MachineBasicBlock::begin(), llvm::MachineOperand::clobbersPhysReg(), E, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), flagSettingOpcodeVariant(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), I, llvm::LPCC::ICC_CC, llvm::LPCC::ICC_CS, llvm::LPCC::ICC_EQ, llvm::LPCC::ICC_F, llvm::LPCC::ICC_GE, llvm::LPCC::ICC_GT, llvm::LPCC::ICC_HI, llvm::LPCC::ICC_LE, llvm::LPCC::ICC_LS, llvm::LPCC::ICC_LT, llvm::LPCC::ICC_MI, llvm::LPCC::ICC_NE, llvm::LPCC::ICC_PL, llvm::LPCC::ICC_T, llvm::LPCC::ICC_VC, llvm::LPCC::ICC_VS, llvm::MachineOperand::isDef(), isRedundantFlagInstr(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), MI, llvm::MachineInstr::modifiesRegister(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstr::readsRegister(), SI, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), TRI, and llvm::LPCC::UNKNOWN.
optimizeSelect()
MachineInstr * LanaiInstrInfo::optimizeSelect (MachineInstr & MI, SmallPtrSetImpl< MachineInstr * > & SeenMIs, bool PreferFalse) const override
Definition at line 494 of file LanaiInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), canFoldIntoSelect(), llvm::MachineInstr::clearKillInfo(), llvm::MachineInstrBuilder::copyImplicitOps(), DefMI, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDesc(), llvm::MachineInstr::getNumOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MCOperandInfo::isPredicate(), MI, MRI, llvm::MCInstrDesc::OpInfo, llvm::MachineOperand::setImplicit(), and llvm::MachineInstr::tieOperands().
removeBranch()
unsigned LanaiInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 693 of file LanaiInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::Instruction::eraseFromParent(), and llvm::Instruction::getOpcode().
reverseBranchCondition()
bool LanaiInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Condition) const override
Definition at line 647 of file LanaiInstrInfo.cpp.
References assert(), getOppositeCondition(), and llvm::SmallVectorBase::size().
storeRegToStackSlot()
void LanaiInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator Position, unsigned SourceRegister, bool IsKill, int FrameIndex, const TargetRegisterClass * RegisterClass, const TargetRegisterInfo * RegisterInfo) const override
Definition at line 49 of file LanaiInstrInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), and llvm_unreachable.
The documentation for this class was generated from the following files:
lib/Target/Lanai/LanaiInstrInfo.h
lib/Target/Lanai/LanaiInstrInfo.cpp