LLVM: llvm::BitMaskClassIterator Class Reference
llvm::BitMaskClassIterator Class Reference
This class encapuslates the logic to iterate over bitmask returned by the various RegClass related APIs.
#include "llvm/CodeGen/TargetRegisterInfo.h"
Public Member Functions
BitMaskClassIterator (const uint32_t *Mask, const TargetRegisterInfo &TRI)
Create a BitMaskClassIterator that visits all the register classes represented by Mask.
bool isValid () const
Returns true if this iterator is still pointing at a valid entry.
unsigned getID () const
Returns the current register class ID.
void operator++ ()
Advance iterator to the next entry.
Detailed Description
This class encapuslates the logic to iterate over bitmask returned by the various RegClass related APIs.
E.g., this class can be used to iterate over the subclasses provided by TargetRegisterClass::getSubClassMask or SuperRegClassIterator::getMask.
Definition at line 1072 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
BitMaskClassIterator()
llvm::BitMaskClassIterator::BitMaskClassIterator (const uint32_t * Mask, const TargetRegisterInfo & TRI) inline
Create a BitMaskClassIterator that visits all the register classes represented by Mask.
Precondition
Mask != nullptr
Definition at line 1136 of file TargetRegisterInfo.h.
Member Function Documentation
getID()
unsigned llvm::BitMaskClassIterator::getID () const inline
Returns the current register class ID.
Definition at line 1146 of file TargetRegisterInfo.h.
Referenced by isValid().
isValid()
bool llvm::BitMaskClassIterator::isValid () const inline
Returns true if this iterator is still pointing at a valid entry.
Definition at line 1143 of file TargetRegisterInfo.h.
References getID().
Referenced by llvm::TargetRegisterInfo::getAllocatableClass(), and operator++().
operator++()
void llvm::BitMaskClassIterator::operator++ () inline
Advance iterator to the next entry.
Definition at line 1149 of file TargetRegisterInfo.h.
References assert(), and isValid().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/TargetRegisterInfo.h