LLVM: llvm::MCInst Class Reference
llvm::MCInst Class Reference
Instances of this class represent a single low-level machine instruction.
#include "llvm/MC/MCInst.h"
Public Types
using iterator = SmallVectorImpl< MCOperand >::iterator
using const_iterator = SmallVectorImpl< MCOperand >::const_iterator
Public Member Functions
MCInst ()=default
void setOpcode (unsigned Op)
unsigned getOpcode () const
void setFlags (unsigned F)
unsigned getFlags () const
void setLoc (SMLoc loc)
SMLoc getLoc () const
const MCOperand & getOperand (unsigned i) const
MCOperand & getOperand (unsigned i)
unsigned getNumOperands () const
void addOperand (const MCOperand &Op)
void clear ()
void erase (iterator I)
void erase (iterator First, iterator Last)
size_t size () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator insert (iterator I, const MCOperand &Op)
void print (raw_ostream &OS) const
void dump () const
void dump_pretty (raw_ostream &OS, const MCInstPrinter *Printer=nullptr, StringRef Separator=" ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given.
void dump_pretty (raw_ostream &OS, StringRef Name, StringRef Separator=" ") const
Detailed Description
Instances of this class represent a single low-level machine instruction.
Definition at line 158 of file MCInst.h.
Member Typedef Documentation
const_iterator
using llvm::MCInst::const_iterator = SmallVectorImpl<MCOperand>::const_iterator
Definition at line 186 of file MCInst.h.
iterator
using llvm::MCInst::iterator = SmallVectorImpl<MCOperand>::iterator
Definition at line 185 of file MCInst.h.
Constructor & Destructor Documentation
MCInst()
llvm::MCInst::MCInst () default
Member Function Documentation
addOperand()
void llvm::MCInst::addOperand (const MCOperand & Op) inline
Definition at line 183 of file MCInst.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::X86Operand::addAbsMemOperands(), llvm::HexagonMCInstrInfo::addConstExtender(), llvm::X86Operand::addDstIdxOperands(), llvm::MCInstBuilder::addExpr(), llvm::X86Operand::addExpr(), llvm::MCInstBuilder::addFPImm(), llvm::X86Operand::addGR32orGR64Operands(), llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addInst(), llvm::X86Operand::addMaskPairOperands(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), addNegOperand(), llvm::MCInstBuilder::addOperand(), addOperand(), addOps(), addOptionalImmOperand(), llvm::MCInstBuilder::addReg(), llvm::X86Operand::addRegOperands(), llvm::X86Operand::addSrcIdxOperands(), llvm::HexagonMCShuffler::copyTo(), Decode2RImmInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), DecodeACC64DSPRegisterClass(), DecodeAddiur2Simm7(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrModeImm12Operand(), DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAFGR64RegisterClass(), DecodeANDI16Imm(), DecodeArmMOVTWInstruction(), DecodeASRRegsRegisterClass(), DecodeBankedReg(), decodeBDAddr12Operand(), decodeBDAddr20Operand(), decodeBDLAddr12Len4Operand(), decodeBDLAddr12Len8Operand(), decodeBDRAddr12Operand(), decodeBDVAddr12Operand(), decodeBDXAddr12Operand(), decodeBDXAddr20Operand(), DecodeBFAfterTargetOperand(), DecodeBFLabelOperand(), DecodeBitfieldMaskOperand(), DecodeBitpOperand(), DecodeBranchImmInstruction(), DecodeBranchTarget(), DecodeBranchTarget10MM(), DecodeBranchTarget1SImm16(), DecodeBranchTarget21(), DecodeBranchTarget21MM(), DecodeBranchTarget26(), DecodeBranchTarget26MM(), DecodeBranchTarget7MM(), DecodeBranchTargetMM(), DecodeCacheeOp_CacheOpR6(), DecodeCacheOp(), DecodeCacheOpMM(), DecodeCCOutOperand(), DecodeCCRRegisterClass(), DecodeCLRMGPRRegisterClass(), decodeCLUIImmOperand(), DecodeCOP0RegisterClass(), DecodeCOP2RegisterClass(), DecodeCopMemInstruction(), DecodeCoprocessor(), DecodeCPPairRegisterClass(), DecodeCPRegsRegisterClass(), DecodeCPSInstruction(), decodeCRBitMOperand(), DecodeCtrRegs64RegisterClass(), DecodeCtrRegsRegisterClass(), DecodeDDDDRegisterClass(), DecodeDDDRegisterClass(), DecodeDDRegisterClass(), DecodeDFPRegsRegisterClass(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeExpandedImmOperand(), DecodeFCCRegisterClass(), DecodeFCCRegsRegisterClass(), DecodeFGR32RegisterClass(), DecodeFGR64RegisterClass(), DecodeFGRCCRegisterClass(), DecodeFixedPointScaleImm32(), DecodeFixedPointScaleImm64(), DecodeFMem(), DecodeFMem2(), DecodeFMem3(), DecodeFMemCop2MMR6(), DecodeFMemCop2R6(), DecodeFMemMMR2(), DecodeFMOVLaneInstruction(), DecodeForVMRSandVMSR(), DecodeFPR128RegisterClass(), DecodeFPR16RegisterClass(), DecodeFPR32CRegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64CRegisterClass(), DecodeFPR64RegisterClass(), DecodeFPR8RegisterClass(), DecodeFPRegsRegisterClass(), decodeFRMArg(), DecodeFromCyclicRange(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64commonRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), DecodeGPRCRegisterClass(), DecodeGPRMM16MovePRegisterClass(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRSeqPairsClassRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeGRRegsRegisterClass(), DecodeGuestRegs64RegisterClass(), DecodeGuestRegsRegisterClass(), DecodeHI32DSPRegisterClass(), DecodeHINTInstruction(), DecodeHWRegsRegisterClass(), DecodeI64RegsRegisterClass(), DecodeImm8OptLsl(), DecodeInsSize(), DecodeInstSyncBarrierOption(), DecodeIntPairRegisterClass(), DecodeIntRegsRegisterClass(), DecodeIT(), DecodeJumpTarget(), DecodeJumpTargetMM(), DecodeL2RUSInstruction(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeLi16Imm(), DecodeLO32DSPRegisterClass(), DecodeLoadByte15(), DecodeLogicalImmInstruction(), DecodeLOLoop(), DecodeLongShiftOperand(), DecodeMem(), DecodeMemBarrierOption(), DecodeMemEVA(), DecodeMemExtend(), DecodeMemMMGPImm7Lsl2(), DecodeMemMMImm12(), DecodeMemMMImm16(), DecodeMemMMImm4(), DecodeMemMMImm9(), DecodeMemMMReglistImm4Lsl2(), DecodeMemMMSPImm5Lsl2(), DecodeMemMultipleWritebackInstruction(), decodeMemoryOpValue(), decodeMemRIOperands(), decodeMemRIX16Operands(), decodeMemRIXOperands(), DecodeMEMrs9(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodeModRegsRegisterClass(), DecodeMoveHRegInstruction(), DecodeMoveImmInstruction(), DecodeMovePRegPair(), DecodeMQPRRegisterClass(), DecodeMRSSystemRegister(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128Mem(), DecodeMSA128WRegisterClass(), DecodeMSACtrlRegisterClass(), DecodeMSRMask(), DecodeMSRSystemRegister(), DecodeMveAddrModeQ(), DecodeMVEModImmInstruction(), DecodeMVEPairVectorIndexOperand(), DecodeMVEVADCInstruction(), DecodeMVEVCMP(), DecodeMveVCTP(), DecodeNegImmOperand(), DecodeNEONComplexLane64Instruction(), DecodeNEONModImmInstruction(), DecodePairLdStInstruction(), decodePCDBLOperand(), DecodePCRel24BranchTarget(), DecodePCRelLabel19(), DecodePOOL16BEncodedField(), DecodePostIdxReg(), DecodePowerTwoOperand(), DecodePPRRegisterClass(), DecodePredicateOperand(), decodePredicateOperand(), DecodePredNoALOperand(), DecodePrefeOpMM(), DecodePRRegsRegisterClass(), DecodeQFPRegsRegisterClass(), DecodeQPRRegisterClass(), DecodeQQPRRegisterClass(), DecodeQQQQPRRegisterClass(), DecodeQQQQRegisterClass(), DecodeQQQRegisterClass(), DecodeQQRegisterClass(), decodeRegisterClass(), DecodeRegisterClass(), DecodeRegListOperand(), DecodeRegListOperand16(), DecodeRestrictedFPPredicateOperand(), DecodeRestrictedIPredicateOperand(), DecodeRestrictedSPredicateOperand(), DecodeRestrictedUPredicateOperand(), DecodeRFEInstruction(), DecoderForMRRC2AndMCRR2(), decodeRiMemoryValue(), DecodeRRegsRegisterClass(), decodeRrMemoryValue(), DecodeRUSInstruction(), DecodeSETPANInstruction(), decodeShiftImm(), DecodeShiftRight16Imm(), DecodeShiftRight32Imm(), DecodeShiftRight64Imm(), DecodeShiftRight8Imm(), DecodeSignedLdStInstruction(), DecodeSignedOperand(), DecodeSImm(), DecodeSimm18Lsl3(), DecodeSimm19Lsl2(), DecodeSimm23Lsl2(), DecodeSimm9SP(), decodeSImmOperand(), decodeSImmOperandAndLsl1(), DecodeSImmWithOffsetAndScale(), DecodeSORegImmOperand(), DecodeSORegMemOperand(), DecodeSORegRegOperand(), decodeSPE2Operands(), decodeSPE4Operands(), decodeSPE8Operands(), DecodeSpecial3LlSc(), decodeSplsValue(), DecodeSPRRegisterClass(), DecodeStLImmInstruction(), DecodeSVEIncDecImm(), DecodeSVELogicalImmInstruction(), DecodeSymbolicOperandOff(), DecodeSyncI(), DecodeSyncI_MM(), DecodeSynciR6(), DecodeSystemPStateInstruction(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm12(), DecodeT2AddrModeSOReg(), DecodeT2Adr(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2CPSInstruction(), DecodeT2Imm7(), DecodeT2Imm7S4(), DecodeT2Imm8(), DecodeT2Imm8S4(), DecodeT2LoadLabel(), DecodeT2MOVTWInstruction(), DecodeT2ShifterImmOperand(), DecodeT2SOImm(), DecodetcGPRRegisterClass(), DecodeTestAndBranch(), DecodetGPREvenRegisterClass(), DecodetGPROddRegisterClass(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddrModeIS(), DecodeThumbAddrModePC(), DecodeThumbAddrModeSP(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPImm(), DecodeThumbAddSPReg(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBLXOffset(), DecodeThumbBROperand(), DecodeThumbCmpBROperand(), DecodeThumbCPS(), decodeUImmOperand(), DecodeUImmWithOffsetAndScale(), DecodeUnconditionalBranch(), DecodeUnsignedLdStInstruction(), DecodeVCVTD(), DecodeVCVTImmOperand(), DecodeVCVTQ(), DecodeVecShiftLImm(), DecodeVecShiftRImm(), DecodeVectorRegisterClass(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVPTMaskOperand(), DecodeVSCCLRM(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), DecodeZPR2RegisterClass(), DecodeZPR3RegisterClass(), DecodeZPR4RegisterClass(), DecodeZPRRegisterClass(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), EmitBinary(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetStreamer::emitII(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), getCompoundInsn(), llvm::AArch64InstrInfo::getNoop(), llvm::ARMInstrInfo::getNoop(), llvm::Thumb1InstrInfo::getNoop(), llvm::Thumb2InstrInfo::getNoop(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::BTFDebug::InstLower(), llvm::AArch64MCInstLower::Lower(), llvm::ARCMCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::XCoreMCInstLower::Lower(), lowerAlignmentHint(), llvm::LowerARMMachineInstrToMCInst(), llvm::AVRMCInstLower::lowerInstruction(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerRISCVMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), makeCombineInst(), llvm::HexagonMCInstrInfo::padEndloop(), PostOperandDecodeAdjust(), llvm::ARMInstPrinter::printInst(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), SimplifyShortImmForm(), SimplifyShortMoveForm(), translateDstIndex(), translateFPRegister(), translateImmediate(), translateMaskRegister(), translateOperand(), translateRegister(), translateRMMemory(), translateSrcIndex(), and llvm::AMDGPUSymbolizer::tryAddingSymbolicOperand().
begin() [1/2]
iterator llvm::MCInst::begin () inline
Definition at line 192 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::HexagonMCInstrInfo::bundleInstructions(), decodeMemRIOperands(), decodeMemRIXOperands(), lookForCompound(), llvm::Hexagon::PacketIterator::operator++(), and llvm::HexagonMCInstrInfo::replaceDuplex().
begin() [2/2]
const_iterator llvm::MCInst::begin () const inline
Definition at line 193 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
clear()
void llvm::MCInst::clear () inline
Definition at line 188 of file MCInst.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::HexagonMCShuffler::copyTo(), DecodeL5RInstructionFail(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), and translateInstruction().
dump()
LLVM_DUMP_METHOD void MCInst::dump () const
Definition at line 94 of file MCInst.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::HexagonMCShuffler::reshuffleTo().
dump_pretty() [1/2]
void MCInst::dump_pretty (raw_ostream & OS, const MCInstPrinter * Printer = nullptr, StringRef Separator = " ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given.
Operators are separated by the Separator string.
Definition at line 72 of file MCInst.cpp.
References dump_pretty(), getOpcode(), and Printer.
Referenced by dump_pretty(), and llvm::ARMAsmBackend::relaxInstruction().
dump_pretty() [2/2]
void MCInst::dump_pretty (raw_ostream & OS, StringRef Name, StringRef Separator = " ") const
Definition at line 78 of file MCInst.cpp.
References getNumOperands(), getOpcode(), getOperand(), Name, and llvm::MCOperand::print().
end() [1/2]
iterator llvm::MCInst::end () inline
Definition at line 194 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::HexagonMCInstrInfo::bundleInstructions(), DecodeRegListOperand(), lookForCompound(), and llvm::Hexagon::PacketIterator::operator++().
end() [2/2]
const_iterator llvm::MCInst::end () const inline
Definition at line 195 of file MCInst.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
erase() [1/2]
void llvm::MCInst::erase (iterator First, iterator Last) inline
Definition at line 190 of file MCInst.h.
References llvm::SmallVectorImpl< T >::erase().
erase() [2/2]
void llvm::MCInst::erase (iterator I) inline
Definition at line 189 of file MCInst.h.
References llvm::SmallVectorImpl< T >::erase(), and I.
Referenced by lookForCompound(), removeRegisterOperands(), and llvm::HexagonMCInstrInfo::replaceDuplex().
getFlags()
unsigned llvm::MCInst::getFlags () const inline
Definition at line 174 of file MCInst.h.
getLoc()
SMLoc llvm::MCInst::getLoc () const inline
Definition at line 177 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), llvm::HexagonMCChecker::reportError(), llvm::HexagonMCChecker::reportWarning(), llvm::HexagonShuffler::restrictNoSlot1Store(), and llvm::HexagonShuffler::restrictSlot1AOK().
getNumOperands()
unsigned llvm::MCInst::getNumOperands () const inline
Definition at line 181 of file MCInst.h.
References llvm::SmallVectorBase::size().
Referenced by checkLowRegisterList(), dump_pretty(), llvm::MCStreamer::EmitInstruction(), llvm::MipsELFStreamer::EmitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getItineraryLatency(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), listContainsReg(), LowerLargeShift(), print(), removeRegisterOperands(), ScaleVectorOffset(), SimplifyShortImmForm(), SimplifyShortMoveForm(), and llvm::mca::verifyOperands().
getOpcode()
unsigned llvm::MCInst::getOpcode () const inline
Definition at line 171 of file MCInst.h.
Referenced by addImplySP(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::TargetSchedModel::computeInstrLatency(), llvm::MCSchedModel::computeInstrLatency(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddSubERegInstruction(), DecodeArmMOVTWInstruction(), DecodeCopMemInstruction(), DecodeExclusiveLdStInstruction(), DecodeForVMRSandVMSR(), DecodeLogicalImmInstruction(), DecodeLOLoop(), DecodeMem(), DecodeMemEVA(), DecodeMemMMImm12(), DecodeMemMMImm4(), DecodeMemMMImm9(), DecodeMemMMReglistImm4Lsl2(), DecodeMemMultipleWritebackInstruction(), decodeMemRIOperands(), decodeMemRIXOperands(), DecodeModImmInstruction(), DecodeMoveImmInstruction(), DecodeMSA128Mem(), DecodeMSRMask(), DecodeMVEModImmInstruction(), DecodeMVEOverlappingLongShift(), DecodeNEONModImmInstruction(), DecodePairLdStInstruction(), DecodePCRelLabel19(), DecodePredicateOperand(), DecodeRegListOperand(), DecodeRegListOperand16(), DecoderForMRRC2AndMCRR2(), DecodeSignedLdStInstruction(), DecodeSpecial3LlSc(), DecodeSVELogicalImmInstruction(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm8(), DecodeT2AddrModeSOReg(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeTBLInstruction(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPReg(), DecodeUnsignedLdStInstruction(), DecodeVCVTImmOperand(), DecodeVLD1DupInstruction(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), DecodeVSCCLRM(), DecodeVSTInstruction(), DecodeVSTRVLDR_SYSREG(), llvm::HexagonMCInstrInfo::deriveSubInst(), dump_pretty(), llvm::AsmPrinter::EmitFunctionBody(), llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::MipsMCCodeEmitter::encodeInstruction(), llvm::MCInstrAnalysis::evaluateBranch(), getCompoundInsn(), getCompoundOp(), llvm::HexagonMCInstrInfo::getDesc(), llvm::HexagonMCInstrInfo::getDuplexCandidateGroup(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getItineraryLatency(), getLatency(), llvm::HexagonMCInstrInfo::getName(), llvm::MCSchedModel::getReciprocalThroughput(), getRegisterForMxtrDSP(), getRelaxedOpcode(), getRelaxedOpcodeArith(), getRelaxedOpcodeBranch(), llvm::HexagonMCInstrInfo::getType(), hasShortDelaySlot(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), instIsBreakpoint(), llvm::MCInstrAnalysis::isBranch(), llvm::HexagonMCInstrInfo::isBundle(), llvm::MCInstrAnalysis::isCall(), llvm::MCInstrAnalysis::isConditionalBranch(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::HexagonMCInstrInfo::isImmext(), llvm::MCInstrAnalysis::isIndirectBranch(), isOrderedCompoundPair(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::MCInstrAnalysis::isReturn(), llvm::HexagonMCInstrInfo::isSolo(), llvm::HexagonMCInstrInfo::isSubInstruction(), llvm::MCInstrAnalysis::isTerminator(), llvm::MCInstrAnalysis::isUnconditionalBranch(), lookForCompound(), llvm::AArch64MCInstLower::Lower(), LowerLargeShift(), llvm::ARMAsmBackend::mayNeedRelaxation(), llvm::RISCVAsmBackend::mayNeedRelaxation(), PostOperandDecodeAdjust(), print(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), ScaleVectorOffset(), SimplifyMOVSX(), llvm::HexagonMCInstrInfo::subInstWouldBeExtended(), and translateInstruction().
getOperand() [1/2]
MCOperand & llvm::MCInst::getOperand (unsigned i) inline
Definition at line 180 of file MCInst.h.
getOperand() [2/2]
const MCOperand & llvm::MCInst::getOperand (unsigned i) const inline
Definition at line 179 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), addOps(), llvm::adjustPqBits(), checkLowRegisterList(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::mca::InstrBuilder::createInstruction(), DecodeBFAfterTargetOperand(), DecodeInsSize(), DecodeMoveImmInstruction(), DecodeRegListOperand(), llvm::HexagonMCInstrInfo::deriveSubInst(), dump_pretty(), llvm::MCStreamer::EmitInstruction(), llvm::MipsELFStreamer::EmitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::HexagonMCInstrInfo::extenderForIndex(), getCompoundInsn(), getCompoundOp(), llvm::HexagonMCInstrInfo::getDuplexCandidateGroup(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), llvm::HexagonMCInstrInfo::getExtendableOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand2(), getRegisterForMxtrC0(), getRegisterForMxtrDSP(), getRegisterForMxtrFP(), hasShortDelaySlot(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::HexagonMCInstrInfo::instruction(), llvm::HexagonMCInstrInfo::isBundle(), llvm::HexagonMCInstrInfo::isInnerLoop(), llvm::HexagonMCInstrInfo::isMemReorderDisabled(), isOrderedCompoundPair(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::HexagonMCInstrInfo::isOuterLoop(), listContainsReg(), LowerLargeShift(), llvm::HexagonMCInstrInfo::minConstant(), PostOperandDecodeAdjust(), llvm::HexagonMCInstrInfo::predicateInfo(), print(), llvm::HexagonInstPrinter::printInst(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), llvm::HexagonMCInstrInfo::replaceDuplex(), ScaleVectorOffset(), llvm::HexagonMCInstrInfo::setInnerLoop(), llvm::HexagonMCInstrInfo::setMemReorderDisabled(), llvm::HexagonMCInstrInfo::setOuterLoop(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), llvm::HexagonMCInstrInfo::subInstWouldBeExtended(), and llvm::mca::verifyOperands().
insert()
iterator llvm::MCInst::insert (iterator I, const MCOperand & Op) inline
Definition at line 197 of file MCInst.h.
References I, and llvm::SmallVectorImpl< T >::insert().
Referenced by decodeMemRIOperands(), and decodeMemRIXOperands().
print()
void MCInst::print (raw_ostream & OS) const
Definition at line 63 of file MCInst.cpp.
References getNumOperands(), getOpcode(), getOperand(), and llvm::MCOperand::print().
Referenced by dump().
setFlags()
void llvm::MCInst::setFlags (unsigned F) inline
Definition at line 173 of file MCInst.h.
References F.
setLoc()
void llvm::MCInst::setLoc (SMLoc loc) inline
Definition at line 176 of file MCInst.h.
Referenced by llvm::HexagonMCInstrInfo::addConstExtender(), llvm::HexagonMCShuffler::copyTo(), llvm::MipsTargetStreamer::emitII(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRX(), and llvm::MipsTargetStreamer::emitRX().
setOpcode()
void llvm::MCInst::setOpcode (unsigned Op) inline
Definition at line 170 of file MCInst.h.
Referenced by Decode2OpInstructionFail(), DecodeBranchImmInstruction(), DecodeCPSInstruction(), DecodeL2OpInstructionFail(), DecodeL5RInstructionFail(), DecodeLOLoop(), DecodeMemMultipleWritebackInstruction(), DecodeMVEOverlappingLongShift(), DecodeSETPANInstruction(), DecodeT2CPSInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeThumb2BCCInstruction(), DecodeVCVTD(), DecodeVCVTQ(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), EmitBinary(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpreturn(), llvm::MipsTargetStreamer::emitII(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), llvm::MipsMCCodeEmitter::encodeInstruction(), getCompoundInsn(), llvm::AArch64InstrInfo::getNoop(), llvm::ARMInstrInfo::getNoop(), llvm::Thumb1InstrInfo::getNoop(), llvm::Thumb2InstrInfo::getNoop(), llvm::PPCInstrInfo::getNoop(), llvm::X86InstrInfo::getNoop(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::BTFDebug::InstLower(), llvm::AArch64MCInstLower::Lower(), llvm::ARCMCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::XCoreMCInstLower::Lower(), lowerAlignmentHint(), llvm::LowerARMMachineInstrToMCInst(), llvm::AVRMCInstLower::lowerInstruction(), LowerLargeShift(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerRISCVMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), makeCombineInst(), llvm::MCInstBuilder::MCInstBuilder(), llvm::HexagonMCInstrInfo::padEndloop(), llvm::ARMInstPrinter::printInst(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), removeRegisterOperands(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), and translateInstruction().
size()
size_t llvm::MCInst::size () const inline
Definition at line 191 of file MCInst.h.
References llvm::SmallVectorBase::size().
Referenced by llvm::HexagonMCInstrInfo::bundleSize(), llvm::MCCodePadder::handleInstructionEnd(), llvm::HexagonMCInstrInfo::isBundle(), llvm::HexagonMCInstrInfo::minConstant(), llvm::HexagonMCInstrInfo::replaceDuplex(), and llvm::HexagonMCInstrInfo::tryCompound().
The documentation for this class was generated from the following files:
include/llvm/MC/MCInst.h
lib/MC/MCInst.cpp