LLVM: llvm::CombinerHelper Class Reference
llvm::CombinerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
Public Member Functions
CombinerHelper (GISelChangeObserver &Observer, MachineIRBuilder &B)
void replaceRegWith (MachineRegisterInfo &MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
void replaceRegOpWith (MachineRegisterInfo &MRI, MachineOperand &FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
bool tryCombineCopy (MachineInstr &MI)
If MI is COPY, try to combine it.
bool matchCombineCopy (MachineInstr &MI)
void applyCombineCopy (MachineInstr &MI)
bool tryCombineExtendingLoads (MachineInstr &MI)
If MI is extend that consumes the result of a load, try to combine it.
bool matchCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
void applyCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
bool matchCombineBr (MachineInstr &MI)
bool tryCombineBr (MachineInstr &MI)
bool tryCombine (MachineInstr &MI)
Try to transform MI by using all of the above combine functions.
Detailed Description
Definition at line 37 of file CombinerHelper.h.
Constructor & Destructor Documentation
CombinerHelper()
CombinerHelper::CombinerHelper (GISelChangeObserver & Observer, MachineIRBuilder & B)
Definition at line 21 of file CombinerHelper.cpp.
Member Function Documentation
applyCombineCopy()
void CombinerHelper::applyCombineCopy (MachineInstr & MI)
Definition at line 68 of file CombinerHelper.cpp.
References MI, and replaceRegWith().
Referenced by tryCombineCopy().
applyCombineExtendingLoads()
void CombinerHelper::applyCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
rewrites to:
rewrites to:
Definition at line 235 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildTrunc(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::GISelChangeObserver::erasingInstr(), llvm::PreferredTuple::ExtendOpcode, llvm::MCInstrInfo::get(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::PreferredTuple::MI, MI, replaceRegOpWith(), replaceRegWith(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineOperand::setReg(), llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_operands(), UseMI, and Uses.
Referenced by tryCombineExtendingLoads().
matchCombineBr()
bool CombinerHelper::matchCombineBr (MachineInstr & MI)
Definition at line 345 of file CombinerHelper.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), llvm::MachineBasicBlock::isLayoutSuccessor(), and MI.
Referenced by tryCombineBr().
matchCombineCopy()
bool CombinerHelper::matchCombineCopy (MachineInstr & MI)
Definition at line 55 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), llvm::LLT::isValid(), and MI.
Referenced by tryCombineCopy().
matchCombineExtendingLoads()
bool CombinerHelper::matchCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
Definition at line 169 of file CombinerHelper.cpp.
References assert(), llvm::dbgs(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::isPowerOf2_32(), llvm::LLT::isScalar(), LLVM_DEBUG, llvm::PreferredTuple::MI, MI, llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_instructions(), and UseMI.
Referenced by tryCombineExtendingLoads().
replaceRegOpWith()
void CombinerHelper::replaceRegOpWith (MachineRegisterInfo & MRI, MachineOperand & FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
Definition at line 37 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineOperand::getParent(), and llvm::MachineOperand::setReg().
Referenced by applyCombineExtendingLoads().
replaceRegWith()
void CombinerHelper::replaceRegWith (MachineRegisterInfo & MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
Definition at line 25 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), llvm::GISelChangeObserver::changingAllUsesOfReg(), llvm::GISelChangeObserver::finishedChangingAllUsesOfReg(), and MRI.
Referenced by applyCombineCopy(), and applyCombineExtendingLoads().
tryCombine()
bool CombinerHelper::tryCombine (MachineInstr & MI)
Try to transform MI by using all of the above combine functions.
Returns true if changed.
Definition at line 407 of file CombinerHelper.cpp.
References MI, tryCombineCopy(), and tryCombineExtendingLoads().
tryCombineBr()
bool CombinerHelper::tryCombineBr (MachineInstr & MI)
Definition at line 383 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::CmpInst::getInversePredicate(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), matchCombineBr(), MI, llvm::MachineOperand::setMBB(), and llvm::MachineOperand::setPredicate().
tryCombineCopy()
bool CombinerHelper::tryCombineCopy (MachineInstr & MI)
If MI is COPY, try to combine it.
Returns true if MI changed.
Definition at line 48 of file CombinerHelper.cpp.
References applyCombineCopy(), matchCombineCopy(), and MI.
Referenced by tryCombine().
tryCombineExtendingLoads()
bool CombinerHelper::tryCombineExtendingLoads (MachineInstr & MI)
If MI is extend that consumes the result of a load, try to combine it.
Returns true if MI changed.
Definition at line 160 of file CombinerHelper.cpp.
References applyCombineExtendingLoads(), matchCombineExtendingLoads(), and MI.
Referenced by tryCombine().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CombinerHelper.h
lib/CodeGen/GlobalISel/CombinerHelper.cpp