LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference final
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV3 ()=default
~MetadataStreamerV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()
virtual bool emitTo (AMDGPUTargetStreamer &TargetStreamer)=0
virtual void begin (const Module &Mod)=0
virtual void end ()=0
virtual void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo)=0
Detailed Description
Definition at line 52 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::MetadataStreamerV3 () default
~MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::~MetadataStreamerV3 () default
References begin().
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::begin (const Module & Mod) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 913 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::Mod.
Referenced by ~MetadataStreamerV3().
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 930 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, assert(), llvm::msgpack::DocNode::getArray(), llvm::msgpack::DocNode::getDocument(), llvm::MachineFunction::getFunction(), llvm::msgpack::Document::getNode(), and llvm::CallingConv::SPIR_KERNEL.
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 909 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 919 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::DumpHSAMetadata, llvm::raw_string_ostream::str(), verify, and llvm::VerifyHSAMetadata.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp