LLVM: llvm::MCPaddingFragment Class Reference
llvm::MCPaddingFragment Class Reference
Fragment for adding required padding.
#include "llvm/MC/MCFragment.h"
Public Types
enum MCPaddingFragmentKind { FirstTargetPerfNopFragmentKind = 8 , MaxTargetPerfNopFragmentKind = 63 }
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB , FT_Padding , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_Dummy
}
Public Member Functions
MCPaddingFragment (MCSection *Sec=nullptr)
bool isInsertionPoint () const
void setAsInsertionPoint ()
uint64_t getPaddingPoliciesMask () const
void setPaddingPoliciesMask (uint64_t Value)
bool hasPaddingPolicy (uint64_t PolicyMask) const
const MCInst & getInst () const
size_t getInstSize () const
void setInstAndInstSize (const MCInst &Inst, size_t InstSize)
void setInstAndInstFragment (const MCInst &Inst, MCRelaxableFragment *InstFragment)
uint64_t getSize () const
void setSize (uint64_t Value)
bool isInstructionInitialized () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
bool isDummy () const
Return true if given frgment has FT_Dummy type.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Attributes
static const uint64_t PFK_None = UINT64_C(0)
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
~MCFragment ()
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Detailed Description
Fragment for adding required padding.
This fragment is always inserted before an instruction, and holds that instruction as context information (as well as a mask of kinds) for determining the padding size.
Definition at line 340 of file MCFragment.h.
Member Enumeration Documentation
MCPaddingFragmentKind
enum llvm::MCPaddingFragment::MCPaddingFragmentKind
Enumerator
FirstTargetPerfNopFragmentKind
MaxTargetPerfNopFragmentKind
Limit range of target MCPerfNopFragment kinds to fit in uint64_t.
Definition at line 370 of file MCFragment.h.
Constructor & Destructor Documentation
MCPaddingFragment()
llvm::MCPaddingFragment::MCPaddingFragment (MCSection * Sec = nullptr) inline
Definition at line 379 of file MCFragment.h.
Member Function Documentation
classof()
static bool llvm::MCPaddingFragment::classof (const MCFragment * F) inline static
Definition at line 422 of file MCFragment.h.
References F, and llvm::MCFragment::FT_Padding.
getInst()
const MCInst & llvm::MCPaddingFragment::getInst () const inline
Definition at line 393 of file MCFragment.h.
References assert(), and isInstructionInitialized().
getInstSize()
size_t llvm::MCPaddingFragment::getInstSize () const inline
Definition at line 397 of file MCFragment.h.
References assert(), and isInstructionInitialized().
Referenced by llvm::MCCodePaddingPolicy::getFragmentInstByte().
getPaddingPoliciesMask()
uint64_t llvm::MCPaddingFragment::getPaddingPoliciesMask () const inline
Definition at line 386 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleBasicBlockStart(), llvm::MCCodePadder::handleInstructionBegin(), and hasPaddingPolicy().
getSize()
uint64_t llvm::MCPaddingFragment::getSize () const inline
Definition at line 418 of file MCFragment.h.
Referenced by llvm::MCCodePadder::relaxFragment().
hasPaddingPolicy()
bool llvm::MCPaddingFragment::hasPaddingPolicy (uint64_t PolicyMask) const inline
Definition at line 388 of file MCFragment.h.
References assert(), getPaddingPoliciesMask(), llvm::isPowerOf2_64(), and PFK_None.
Referenced by llvm::MCCodePaddingPolicy::computeFirstWindowPenaltyWeight(), and llvm::MCCodePaddingPolicy::computeRangePenaltyWeight().
isInsertionPoint()
bool llvm::MCPaddingFragment::isInsertionPoint () const inline
Definition at line 384 of file MCFragment.h.
Referenced by llvm::MCCodePadder::relaxFragment().
isInstructionInitialized()
bool llvm::MCPaddingFragment::isInstructionInitialized () const inline
Definition at line 420 of file MCFragment.h.
Referenced by getInst(), and getInstSize().
setAsInsertionPoint()
void llvm::MCPaddingFragment::setAsInsertionPoint () inline
Definition at line 385 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleBasicBlockStart(), and llvm::MCCodePadder::handleInstructionBegin().
setInstAndInstFragment()
void llvm::MCPaddingFragment::setInstAndInstFragment (const MCInst & Inst, MCRelaxableFragment * InstFragment) inline
Definition at line 411 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleInstructionEnd().
setInstAndInstSize()
void llvm::MCPaddingFragment::setInstAndInstSize (const MCInst & Inst, size_t InstSize) inline
Definition at line 405 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleInstructionEnd().
setPaddingPoliciesMask()
void llvm::MCPaddingFragment::setPaddingPoliciesMask (uint64_t Value) inline
Definition at line 387 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleBasicBlockStart(), and llvm::MCCodePadder::handleInstructionBegin().
setSize()
void llvm::MCPaddingFragment::setSize (uint64_t Value) inline
Definition at line 419 of file MCFragment.h.
Referenced by llvm::MCCodePadder::relaxFragment().
Member Data Documentation
PFK_None
const uint64_t llvm::MCPaddingFragment::PFK_None = UINT64_C(0) static
Definition at line 368 of file MCFragment.h.
Referenced by llvm::MCCodePadder::handleBasicBlockStart(), llvm::MCCodePadder::handleInstructionBegin(), and hasPaddingPolicy().
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h