LLVM: llvm::ListInit Class Reference
llvm::ListInit Class Reference final
[AL, AH, CL] - Represent a list of defs
#include "llvm/TableGen/Record.h"
Public Types
using const_iterator = Init *const *
Public Member Functions
ListInit (const ListInit &)=delete
ListInit & operator= (const ListInit &)=delete
void operator delete (void *p)
void Profile (FoldingSetNodeID &ID) const
Init * getElement (unsigned i) const
RecTy * getElementType () const
Record * getElementAsRecord (unsigned i) const
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time they expression is formed.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
ArrayRef< Init * > getValues () const
const_iterator begin () const
const_iterator end () const
size_t size () const
bool empty () const
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< ListInit, Init * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
Static Public Member Functions
static bool classof (const Init *I)
static ListInit * get (ArrayRef< Init * > Range, RecTy *EltTy)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< ListInit, Init * >
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
[AL, AH, CL] - Represent a list of defs
Definition at line 661 of file Record.h.
Member Typedef Documentation
const_iterator
using llvm::ListInit::const_iterator = Init *const *
Definition at line 666 of file Record.h.
Constructor & Destructor Documentation
ListInit()
llvm::ListInit::ListInit (const ListInit &) delete
Member Function Documentation
begin()
const_iterator llvm::ListInit::begin () const inline
Definition at line 714 of file Record.h.
Referenced by ConcatListInits(), end(), and llvm::BinOpInit::Fold().
classof()
static bool llvm::ListInit::classof (const Init * I) inline static
Definition at line 679 of file Record.h.
References I, and llvm::Init::IK_ListInit.
convertInitializerTo()
Init * ListInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Reimplemented from llvm::TypedInit.
Definition at line 598 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::TypedInit::getType(), getValues(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
convertInitListSlice()
Init * ListInit::convertInitListSlice (ArrayRef< unsigned > Elements) const override virtual
This method is used to implement the list slice selection operator.
Given an initializer, it selects the specified list elements, returning them as a new init of list type. If it is not legal to take a slice of this, return null.
Reimplemented from llvm::TypedInit.
Definition at line 626 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), getElement(), getElementType(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::ArrayRef< T >::size(), and size().
empty()
bool llvm::ListInit::empty () const inline
Definition at line 718 of file Record.h.
end()
const_iterator llvm::ListInit::end () const inline
Definition at line 715 of file Record.h.
References begin().
Referenced by ConcatListInits(), and llvm::BinOpInit::Fold().
get()
ListInit * ListInit::get (ArrayRef< Init * > Range, RecTy * EltTy) static
Definition at line 570 of file Record.cpp.
References Allocator, assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), I, llvm::FoldingSetImpl< T >::InsertNode(), ProfileListInit(), and llvm::ArrayRef< T >::size().
getAsString()
std::string ListInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 669 of file Record.cpp.
References llvm::Init::getAsString().
getBit()
Init * llvm::ListInit::getBit (unsigned Bit) const inline override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 720 of file Record.h.
References llvm_unreachable.
getElement()
Init * llvm::ListInit::getElement (unsigned i) const inline
Definition at line 686 of file Record.h.
References assert().
Referenced by convertInitListSlice(), llvm::TernOpInit::Fold(), and getElementAsRecord().
getElementAsRecord()
Record * ListInit::getElementAsRecord (unsigned i) const
Definition at line 637 of file Record.cpp.
References assert(), llvm::DefInit::getDef(), getElement(), and llvm::PrintFatalError().
getElementType()
RecTy * llvm::ListInit::getElementType () const inline
Definition at line 690 of file Record.h.
References llvm::TypedInit::getType().
Referenced by ConcatListInits(), convertInitListSlice(), llvm::BinOpInit::Fold(), and resolveReferences().
getValues()
ArrayRef< Init * > llvm::ListInit::getValues () const inline
Definition at line 710 of file Record.h.
References llvm::makeArrayRef().
Referenced by convertInitializerTo(), Profile(), and resolveReferences().
isConcrete()
bool ListInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 661 of file Record.cpp.
References llvm::Init::isConcrete().
operator delete()
void llvm::ListInit::operator delete (void * p) inline
Definition at line 677 of file Record.h.
operator=()
ListInit & llvm::ListInit::operator= (const ListInit &) delete
Profile()
void ListInit::Profile (FoldingSetNodeID & ID) const
Definition at line 592 of file Record.cpp.
References llvm::TypedInit::getType(), getValues(), and ProfileListInit().
resolveReferences()
Init * ListInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time they expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 645 of file Record.cpp.
References E, llvm::IntervalMapImpl::NodeRef::get(), getElementType(), getValues(), and size().
size()
size_t llvm::ListInit::size () const inline
Definition at line 717 of file Record.h.
Referenced by convertInitListSlice(), llvm::TernOpInit::Fold(), and resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp