LLVM: llvm::FileCheck Class Reference
llvm::FileCheck Class Reference
FileCheck class takes the request and exposes various methods that use information from the request.
#include "llvm/Support/FileCheck.h"
Public Member Functions
FileCheck (FileCheckRequest Req)
Regex buildCheckPrefixRegex ()
bool ReadCheckFile (SourceMgr &SM, StringRef Buffer, Regex &PrefixRE, std::vector< FileCheckString > &CheckStrings)
Reads the check file from Buffer and records the expected strings it contains in the CheckStrings vector.
bool ValidateCheckPrefixes ()
StringRef CanonicalizeFile (MemoryBuffer &MB, SmallVectorImpl< char > &OutputBuffer)
Canonicalizes whitespaces in the file.
bool CheckInput (SourceMgr &SM, StringRef Buffer, ArrayRef< FileCheckString > CheckStrings, std::vector< FileCheckDiag > *Diags=nullptr)
Checks the input to FileCheck provided in the Buffer against the CheckStrings read from the check file and record diagnostics emitted in Diags.
Detailed Description
FileCheck class takes the request and exposes various methods that use information from the request.
Definition at line 711 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheck()
llvm::FileCheck::FileCheck (FileCheckRequest Req) inline
Definition at line 716 of file FileCheck.h.
Member Function Documentation
buildCheckPrefixRegex()
Regex FileCheck::buildCheckPrefixRegex ()
Definition at line 1729 of file FileCheck.cpp.
References llvm::SmallString< InternalLen >::append(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
CanonicalizeFile()
StringRef FileCheck::CanonicalizeFile (MemoryBuffer & MB, SmallVectorImpl< char > & OutputBuffer)
Canonicalizes whitespaces in the file.
Line endings are replaced with UNIX-style '
'.
Definition at line 885 of file FileCheck.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::FileCheckRequest::NoCanonicalizeWhiteSpace, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorBase::size().
CheckInput()
bool FileCheck::CheckInput (SourceMgr & SM, StringRef Buffer, ArrayRef< FileCheckString > CheckStrings, std::vector< FileCheckDiag > * Diags = nullptr)
Checks the input to FileCheck provided in the Buffer against the CheckStrings read from the check file and record diagnostics emitted in Diags.
Errors are recorded against SM.
Returns
false if the input fails to satisfy the checks.
Definition at line 1890 of file FileCheck.cpp.
References llvm::FileCheckString::Check(), llvm::Check::CheckLabel, llvm::FileCheckPattern::getCheckTy(), llvm::StringRef::npos, llvm::FileCheckString::Pat, llvm::ArrayRef< T >::size(), and llvm::StringRef::substr().
ReadCheckFile()
bool FileCheck::ReadCheckFile (SourceMgr & SM, StringRef Buffer, Regex & PrefixRE, std::vector< FileCheckString > & CheckStrings)
Reads the check file from Buffer and records the expected strings it contains in the CheckStrings vector.
Errors are reported against SM.
Only expected strings whose prefix is one of those listed in PrefixRE are recorded.
Returns
true in case of an error, false otherwise.
Definition at line 1111 of file FileCheck.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), assert(), llvm::Check::CheckBadCount, llvm::Check::CheckBadNot, llvm::Check::CheckDAG, llvm::Check::CheckEmpty, llvm::Check::CheckEOF, llvm::Check::CheckLabel, llvm::Check::CheckNext, llvm::Check::CheckNot, llvm::Check::CheckSame, llvm::StringRef::data(), llvm::SourceMgr::DK_Error, llvm::StringRef::drop_front(), E, llvm::StringRef::empty(), llvm::errs(), llvm::StringRef::find_first_not_of(), llvm::StringRef::find_first_of(), FindFirstMatchingPrefix(), llvm::SMLoc::getFromPointer(), llvm::MemoryBuffer::getMemBufferCopy(), I, llvm::logAllUnhandledErrors(), P, llvm::SourceMgr::PrintMessage(), llvm::StringRef::size(), llvm::StringRef::substr(), and std::swap().
ValidateCheckPrefixes()
bool FileCheck::ValidateCheckPrefixes ()
Definition at line 1711 of file FileCheck.cpp.
References llvm::StringSet< AllocatorTy >::insert(), and ValidateCheckPrefix().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp