LLVM: llvm::StackMapParser< Endianness >::RecordAccessor Class Reference
llvm::StackMapParser< Endianness >::RecordAccessor Class Reference
Accessor for stackmap records.
#include "llvm/Object/StackMapParser.h"
Public Types
using location_iterator = AccessorIterator< LocationAccessor >
using liveout_iterator = AccessorIterator< LiveOutAccessor >
Public Member Functions
uint64_t getID () const
Get the patchpoint/stackmap ID for this record.
uint32_t getInstructionOffset () const
Get the instruction offset (from the start of the containing function) for this record.
uint16_t getNumLocations () const
Get the number of locations contained in this record.
LocationAccessor getLocation (unsigned LocationIndex) const
Get the location with the given index.
location_iterator location_begin () const
Begin iterator for locations.
location_iterator location_end () const
End iterator for locations.
iterator_range< location_iterator > locations () const
Iterator range for locations.
uint16_t getNumLiveOuts () const
Get the number of liveouts contained in this record.
LiveOutAccessor getLiveOut (unsigned LiveOutIndex) const
Get the live-out with the given index.
liveout_iterator liveouts_begin () const
Begin iterator for live-outs.
liveout_iterator liveouts_end () const
End iterator for live-outs.
iterator_range< liveout_iterator > liveouts () const
Iterator range for live-outs.
Friends
class StackMapParser
Detailed Description
template<support::endianness Endianness>
class llvm::StackMapParser< Endianness >::RecordAccessor
Accessor for stackmap records.
Definition at line 198 of file StackMapParser.h.
Member Typedef Documentation
liveout_iterator
template<support::endianness Endianness> using llvm::StackMapParser< Endianness >::RecordAccessor::liveout_iterator = AccessorIterator<LiveOutAccessor>
Definition at line 203 of file StackMapParser.h.
location_iterator
template<support::endianness Endianness> using llvm::StackMapParser< Endianness >::RecordAccessor::location_iterator = AccessorIterator<LocationAccessor>
Definition at line 202 of file StackMapParser.h.
Member Function Documentation
getID()
template<support::endianness Endianness> uint64_t llvm::StackMapParser< Endianness >::RecordAccessor::getID () const inline
Get the patchpoint/stackmap ID for this record.
Definition at line 206 of file StackMapParser.h.
References P.
getInstructionOffset()
template<support::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::RecordAccessor::getInstructionOffset () const inline
Get the instruction offset (from the start of the containing function) for this record.
Definition at line 212 of file StackMapParser.h.
References P.
getLiveOut()
template<support::endianness Endianness> LiveOutAccessor llvm::StackMapParser< Endianness >::RecordAccessor::getLiveOut (unsigned LiveOutIndex) const inline
Get the live-out with the given index.
Definition at line 249 of file StackMapParser.h.
References P.
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_begin(), and llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_end().
getLocation()
template<support::endianness Endianness> LocationAccessor llvm::StackMapParser< Endianness >::RecordAccessor::getLocation (unsigned LocationIndex) const inline
Get the location with the given index.
Definition at line 222 of file StackMapParser.h.
References P.
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::location_begin(), and llvm::StackMapParser< Endianness >::RecordAccessor::location_end().
getNumLiveOuts()
template<support::endianness Endianness> uint16_t llvm::StackMapParser< Endianness >::RecordAccessor::getNumLiveOuts () const inline
Get the number of liveouts contained in this record.
Definition at line 244 of file StackMapParser.h.
References P.
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_end().
getNumLocations()
template<support::endianness Endianness> uint16_t llvm::StackMapParser< Endianness >::RecordAccessor::getNumLocations () const inline
Get the number of locations contained in this record.
Definition at line 217 of file StackMapParser.h.
References P.
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::location_end().
liveouts()
template<support::endianness Endianness> iterator_range< liveout_iterator > llvm::StackMapParser< Endianness >::RecordAccessor::liveouts () const inline
Iterator range for live-outs.
Definition at line 266 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_begin(), llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_end(), and llvm::make_range().
liveouts_begin()
template<support::endianness Endianness> liveout_iterator llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_begin () const inline
Begin iterator for live-outs.
Definition at line 256 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::getLiveOut().
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::liveouts().
liveouts_end()
template<support::endianness Endianness> liveout_iterator llvm::StackMapParser< Endianness >::RecordAccessor::liveouts_end () const inline
End iterator for live-outs.
Definition at line 261 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::getLiveOut(), and llvm::StackMapParser< Endianness >::RecordAccessor::getNumLiveOuts().
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::liveouts().
location_begin()
template<support::endianness Endianness> location_iterator llvm::StackMapParser< Endianness >::RecordAccessor::location_begin () const inline
Begin iterator for locations.
Definition at line 229 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::getLocation().
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::locations().
location_end()
template<support::endianness Endianness> location_iterator llvm::StackMapParser< Endianness >::RecordAccessor::location_end () const inline
End iterator for locations.
Definition at line 234 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::getLocation(), and llvm::StackMapParser< Endianness >::RecordAccessor::getNumLocations().
Referenced by llvm::StackMapParser< Endianness >::RecordAccessor::locations().
locations()
template<support::endianness Endianness> iterator_range< location_iterator > llvm::StackMapParser< Endianness >::RecordAccessor::locations () const inline
Iterator range for locations.
Definition at line 239 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::RecordAccessor::location_begin(), llvm::StackMapParser< Endianness >::RecordAccessor::location_end(), and llvm::make_range().
Friends And Related Function Documentation
StackMapParser
template<support::endianness Endianness> friend class StackMapParser friend
Definition at line 199 of file StackMapParser.h.
The documentation for this class was generated from the following file:
include/llvm/Object/StackMapParser.h