LLVM: llvm::sys::OwningMemoryBlock Class Reference
llvm::sys::OwningMemoryBlock Class Reference
Owning version of MemoryBlock.
#include "llvm/Support/Memory.h"
Public Member Functions
OwningMemoryBlock ()=default
OwningMemoryBlock (MemoryBlock M)
OwningMemoryBlock (OwningMemoryBlock &&Other)
OwningMemoryBlock & operator= (OwningMemoryBlock &&Other)
~OwningMemoryBlock ()
void * base () const
size_t allocatedSize () const
The size as it was allocated.
MemoryBlock getMemoryBlock () const
Detailed Description
Owning version of MemoryBlock.
Definition at line 128 of file Memory.h.
Constructor & Destructor Documentation
OwningMemoryBlock() [1/3]
llvm::sys::OwningMemoryBlock::OwningMemoryBlock () default
OwningMemoryBlock() [2/3]
llvm::sys::OwningMemoryBlock::OwningMemoryBlock (MemoryBlock M) inline explicit
Definition at line 131 of file Memory.h.
OwningMemoryBlock() [3/3]
llvm::sys::OwningMemoryBlock::OwningMemoryBlock (OwningMemoryBlock && Other) inline
Definition at line 132 of file Memory.h.
References Other.
~OwningMemoryBlock()
llvm::sys::OwningMemoryBlock::~OwningMemoryBlock () inline
Definition at line 141 of file Memory.h.
References llvm::sys::Memory::releaseMappedMemory().
Member Function Documentation
allocatedSize()
size_t llvm::sys::OwningMemoryBlock::allocatedSize () const inline
The size as it was allocated.
This is always greater or equal to the size that was originally requested.
Definition at line 147 of file Memory.h.
References llvm::sys::MemoryBlock::allocatedSize().
base()
void * llvm::sys::OwningMemoryBlock::base () const inline
Definition at line 144 of file Memory.h.
References llvm::sys::MemoryBlock::base().
Referenced by llvm::orc::GenericIndirectStubsInfo< StubSizeVal >::getPtr(), and llvm::orc::GenericIndirectStubsInfo< StubSizeVal >::getStub().
getMemoryBlock()
MemoryBlock llvm::sys::OwningMemoryBlock::getMemoryBlock () const inline
Definition at line 148 of file Memory.h.
operator=()
OwningMemoryBlock & llvm::sys::OwningMemoryBlock::operator= (OwningMemoryBlock && Other) inline
Definition at line 136 of file Memory.h.
References Other.
The documentation for this class was generated from the following file:
include/llvm/Support/Memory.h