LLVM: llvm::AMDGPUTargetAsmStreamer Class Reference
llvm::AMDGPUTargetAsmStreamer Class Reference final
#include "Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h"
Public Member Functions
AMDGPUTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void finish () override
void EmitDirectiveAMDGCNTarget (StringRef Target) override
void EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override
void EmitDirectiveHSACodeObjectISA (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override
void EmitAMDKernelCodeT (const amd_kernel_code_t &Header) override
void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override
void emitAMDGPULDS (MCSymbol *Sym, unsigned Size, unsigned Align) override
bool EmitISAVersion (StringRef IsaVersionString) override
bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict) override
bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata) override
bool EmitCodeEnd () override
void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const amdhsa::kernel_descriptor_t &KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, bool ReserveXNACK) override
Public Member Functions inherited from llvm::AMDGPUTargetStreamer
AMDGPUTargetStreamer (MCStreamer &S)
AMDGPUPALMetadata * getPALMetadata ()
virtual void EmitDirectiveAMDGCNTarget (StringRef Target)=0
virtual void EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor)=0
virtual void EmitDirectiveHSACodeObjectISA (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName)=0
virtual void EmitAMDKernelCodeT (const amd_kernel_code_t &Header)=0
virtual void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type)=0
virtual void emitAMDGPULDS (MCSymbol *Symbol, unsigned Size, unsigned Align)=0
virtual bool EmitISAVersion (StringRef IsaVersionString)=0
virtual bool EmitHSAMetadataV2 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadataV3 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict)=0
Emit HSA Metadata.
virtual bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata)=0
virtual bool EmitCodeEnd ()=0
virtual void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const amdhsa::kernel_descriptor_t &KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, bool ReserveXNACK)=0
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, raw_ostream &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUTargetStreamer
static StringRef getArchNameFromElfMach (unsigned ElfMach)
static unsigned getElfMach (StringRef GPU)
Protected Member Functions inherited from llvm::AMDGPUTargetStreamer
MCContext & getContext () const
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 93 of file AMDGPUTargetStreamer.h.
Constructor & Destructor Documentation
AMDGPUTargetAsmStreamer()
AMDGPUTargetAsmStreamer::AMDGPUTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 160 of file AMDGPUTargetStreamer.cpp.
Member Function Documentation
emitAMDGPULDS()
void AMDGPUTargetAsmStreamer::emitAMDGPULDS (MCSymbol * Sym, unsigned Size, unsigned Align) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 211 of file AMDGPUTargetStreamer.cpp.
References Size.
EmitAMDGPUSymbolType()
void AMDGPUTargetAsmStreamer::EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 201 of file AMDGPUTargetStreamer.cpp.
References llvm_unreachable, and llvm::ELF::STT_AMDGPU_HSA_KERNEL.
EmitAmdhsaKernelDescriptor()
void AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor (const MCSubtargetInfo & STI, StringRef KernelName, const amdhsa::kernel_descriptor_t & KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, bool ReserveXNACK) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 257 of file AMDGPUTargetStreamer.cpp.
References llvm::MCSubtargetInfo::getCPU(), llvm::AMDGPU::getIsaVersion(), llvm::amdhsa::kernel_descriptor_t::group_segment_fixed_size, llvm::AMDGPU::hasXNACK(), llvm::AMDGPU::IsaVersion::Major, PRINT_FIELD, and llvm::amdhsa::kernel_descriptor_t::private_segment_fixed_size.
EmitAMDKernelCodeT()
void AMDGPUTargetAsmStreamer::EmitAMDKernelCodeT (const amd_kernel_code_t & Header) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 195 of file AMDGPUTargetStreamer.cpp.
References llvm::dumpAmdKernelCode().
EmitCodeEnd()
bool AMDGPUTargetAsmStreamer::EmitCodeEnd () override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 250 of file AMDGPUTargetStreamer.cpp.
EmitDirectiveAMDGCNTarget()
void AMDGPUTargetAsmStreamer::EmitDirectiveAMDGCNTarget (StringRef Target) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 172 of file AMDGPUTargetStreamer.cpp.
EmitDirectiveHSACodeObjectISA()
void AMDGPUTargetAsmStreamer::EmitDirectiveHSACodeObjectISA (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 183 of file AMDGPUTargetStreamer.cpp.
EmitDirectiveHSACodeObjectVersion()
void AMDGPUTargetAsmStreamer::EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 176 of file AMDGPUTargetStreamer.cpp.
EmitHSAMetadata() [1/2]
bool AMDGPUTargetAsmStreamer::EmitHSAMetadata (const AMDGPU::HSAMD::Metadata & HSAMetadata) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 222 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::AssemblerDirectiveBegin, llvm::AMDGPU::HSAMD::AssemblerDirectiveEnd, and llvm::AMDGPU::HSAMD::toString().
EmitHSAMetadata() [2/2]
bool AMDGPUTargetAsmStreamer::EmitHSAMetadata (msgpack::Document & HSAMetadata, bool Strict) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 234 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::V3::AssemblerDirectiveBegin, llvm::AMDGPU::HSAMD::V3::AssemblerDirectiveEnd, llvm::msgpack::Document::getRoot(), llvm::raw_string_ostream::str(), llvm::msgpack::Document::toYAML(), and Verifier.
EmitISAVersion()
bool AMDGPUTargetAsmStreamer::EmitISAVersion (StringRef IsaVersionString) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 217 of file AMDGPUTargetStreamer.cpp.
finish()
void AMDGPUTargetAsmStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 166 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPUTargetStreamer::getPALMetadata(), and llvm::AMDGPUPALMetadata::toString().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp