LLVM: llvm::VPWidenMemoryInstructionRecipe Class Reference
llvm::VPWidenMemoryInstructionRecipe Class Reference
A Recipe for widening load/store operations.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenMemoryInstructionRecipe (Instruction &Instr, VPValue *Mask)
void execute (VPTransformState &State) override
Generate the wide load/store.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Detailed Description
A Recipe for widening load/store operations.
TODO: We currently execute only per-part unless a specific instance is provided.
Definition at line 955 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenMemoryInstructionRecipe()
llvm::VPWidenMemoryInstructionRecipe::VPWidenMemoryInstructionRecipe (Instruction & Instr, VPValue * Mask) inline
Definition at line 961 of file VPlan.h.
Member Function Documentation
classof()
static bool llvm::VPWidenMemoryInstructionRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 968 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPWidenMemoryInstructionRecipe::execute (VPTransformState & State) override virtual
Generate the wide load/store.
Implements llvm::VPRecipeBase.
Definition at line 7190 of file LoopVectorize.cpp.
References llvm::VPTransformState::get(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::VPTransformState::ILV, llvm::VPTransformState::UF, and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
print()
void VPWidenMemoryInstructionRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 689 of file VPlan.cpp.
References llvm::User::getOperand(), and llvm::Value::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp