LLVM: llvm::RegisterPassParser< RegistryClass > Class Template Reference
llvm::RegisterPassParser< RegistryClass > Class Template Reference
RegisterPassParser class - Handle the addition of new machine passes.
#include "llvm/CodeGen/MachinePassRegistry.h"
Public Member Functions
RegisterPassParser (cl::Option &O)
~RegisterPassParser () override
void initialize ()
void NotifyAdd (StringRef N, typename RegistryClass::FunctionPassCtor C, StringRef D) override
void NotifyRemove (StringRef N) override
Public Member Functions inherited from llvm::MachinePassRegistryListener< RegistryClass::FunctionPassCtor >
MachinePassRegistryListener ()=default
virtual ~MachinePassRegistryListener ()=default
virtual void NotifyAdd (StringRef N, RegistryClass::FunctionPassCtor C, StringRef D)=0
virtual void NotifyRemove (StringRef N)=0
Public Member Functions inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
parser (Option &O)
unsigned getNumOptions () const override
StringRef getOption (unsigned N) const override
StringRef getDescription (unsigned N) const override
const GenericOptionValue & getOptionValue (unsigned N) const override
bool parse (Option &O, StringRef ArgName, StringRef Arg, RegistryClass::FunctionPassCtor &V)
void addLiteralOption (StringRef Name, const DT &V, StringRef HelpStr)
addLiteralOption - Add an entry to the mapping table.
void removeLiteralOption (StringRef Name)
removeLiteralOption - Remove the specified option.
Public Member Functions inherited from llvm::cl::generic_parser_base
generic_parser_base (Option &O)
virtual ~generic_parser_base ()=default
virtual unsigned getNumOptions () const =0
virtual StringRef getOption (unsigned N) const =0
virtual StringRef getDescription (unsigned N) const =0
virtual size_t getOptionWidth (const Option &O) const
virtual const GenericOptionValue & getOptionValue (unsigned N) const =0
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue >
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize ()
void getExtraOptionNames (SmallVectorImpl< StringRef > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (StringRef Name)
Additional Inherited Members
Public Types inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
using parser_data_type = RegistryClass::FunctionPassCtor
Protected Attributes inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
SmallVector< OptionInfo, 8 > Values
Protected Attributes inherited from llvm::cl::generic_parser_base
Option & Owner
Detailed Description
template<class RegistryClass>
class llvm::RegisterPassParser< RegistryClass >
RegisterPassParser class - Handle the addition of new machine passes.
Definition at line 135 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
RegisterPassParser()
template<class RegistryClass > llvm::RegisterPassParser< RegistryClass >::RegisterPassParser (cl::Option & O) inline
Definition at line 140 of file MachinePassRegistry.h.
~RegisterPassParser()
template<class RegistryClass > llvm::RegisterPassParser< RegistryClass >::~RegisterPassParser () inline override
Definition at line 142 of file MachinePassRegistry.h.
Member Function Documentation
initialize()
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::initialize () inline
Definition at line 144 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption(), and llvm::RegisterPassParser< RegistryClass >::initialize().
Referenced by llvm::RegisterPassParser< RegistryClass >::initialize(), llvm::PassNameParser::initialize(), llvm::GCNMaxOccupancySchedStrategy::initialize(), llvm::PPCPostRASchedStrategy::initialize(), llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator()(), and llvm::VarStreamArrayExtractor< pdb::DbiModuleDescriptor >::operator()().
NotifyAdd()
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::NotifyAdd (StringRef N, typename RegistryClass::FunctionPassCtor C, StringRef D) inline override virtual
Implements llvm::MachinePassRegistryListener< RegistryClass::FunctionPassCtor >.
Definition at line 160 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption(), C, and D.
NotifyRemove()
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::NotifyRemove (StringRef N) inline override virtual
Implements llvm::MachinePassRegistryListener< RegistryClass::FunctionPassCtor >.
Definition at line 164 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::removeLiteralOption().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachinePassRegistry.h