LLVM: llvm::MemCpyOptPass Class Reference
llvm::MemCpyOptPass Class Reference
#include "llvm/Transforms/Scalar/MemCpyOptimizer.h"
Public Member Functions
MemCpyOptPass ()=default
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, MemoryDependenceResults *MD_, TargetLibraryInfo *TLI_, std::function< AliasAnalysis &()> LookupAliasAnalysis_, std::function< AssumptionCache &()> LookupAssumptionCache_, std::function< DominatorTree &()> LookupDomTree_)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MemCpyOptPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 39 of file MemCpyOptimizer.h.
Constructor & Destructor Documentation
MemCpyOptPass()
llvm::MemCpyOptPass::MemCpyOptPass () default
Member Function Documentation
run()
PreservedAnalyses MemCpyOptPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1463 of file MemCpyOptimizer.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool MemCpyOptPass::runImpl (Function & F, MemoryDependenceResults * MD_, TargetLibraryInfo * TLI_, std::function< AliasAnalysis &()> LookupAliasAnalysis_, std::function< AssumptionCache &()> LookupAssumptionCache_, std::function< DominatorTree &()> LookupDomTree_)
Definition at line 1489 of file MemCpyOptimizer.cpp.
References F, and llvm::TargetLibraryInfo::has().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/MemCpyOptimizer.h
lib/Transforms/Scalar/MemCpyOptimizer.cpp