LLVM: llvm::pdb::PDBSymbolData Class Reference
llvm::pdb::PDBSymbolData Class Reference
#include "llvm/DebugInfo/PDB/PDBSymbolData.h"
Public Member Functions
void dump (PDBSymDumper &Dumper) const override
Dumps the contents of a symbol a raw_ostream.
std::unique_ptr< IPDBEnumLineNumbers > getLineNumbers () const
uint32_t getCompilandId () const
Public Member Functions inherited from llvm::pdb::PDBSymbol
virtual ~PDBSymbol ()
virtual void dump (PDBSymDumper &Dumper) const =0
Dumps the contents of a symbol a raw_ostream.
virtual void dumpRight (PDBSymDumper &Dumper) const
For certain PDBSymbolTypes, dumps additional information for the type that normally goes on the right side of the symbol.
void defaultDump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowFlags, PdbSymbolIdField RecurseFlags) const
void dumpProperties () const
void dumpChildStats () const
PDB_SymType getSymTag () const
uint32_t getSymIndexId () const
template<typename T >
std::unique_ptr< T > findOneChild () const
template<typename T >
std::unique_ptr< ConcreteSymbolEnumerator< T > > findAllChildren () const
std::unique_ptr< IPDBEnumSymbols > findAllChildren (PDB_SymType Type) const
std::unique_ptr< IPDBEnumSymbols > findAllChildren () const
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const
const IPDBRawSymbol & getRawSymbol () const
IPDBRawSymbol & getRawSymbol ()
const IPDBSession & getSession () const
std::unique_ptr< IPDBEnumSymbols > getChildStats (TagStats &Stats) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::pdb::PDBSymbol
static std::unique_ptr< PDBSymbol > create (const IPDBSession &PDBSession, std::unique_ptr< IPDBRawSymbol > RawSymbol)
static std::unique_ptr< PDBSymbol > create (const IPDBSession &PDBSession, IPDBRawSymbol &RawSymbol)
template<typename ConcreteT >
static std::unique_ptr< ConcreteT > createAs (const IPDBSession &PDBSession, std::unique_ptr< IPDBRawSymbol > RawSymbol)
template<typename ConcreteT >
static std::unique_ptr< ConcreteT > createAs (const IPDBSession &PDBSession, IPDBRawSymbol &RawSymbol)
Protected Member Functions inherited from llvm::pdb::PDBSymbol
PDBSymbol (const IPDBSession &PDBSession)
PDBSymbol (PDBSymbol &&Other)
std::unique_ptr< PDBSymbol > getSymbolByIdHelper (uint32_t Id) const
template<typename ConcreteType >
std::unique_ptr< ConcreteType > getConcreteSymbolByIdHelper (uint32_t Id) const
Protected Attributes inherited from llvm::pdb::PDBSymbol
const IPDBSession & Session
std::unique_ptr< IPDBRawSymbol > OwnedRawSymbol
IPDBRawSymbol * RawSymbol = nullptr
Detailed Description
Definition at line 22 of file PDBSymbolData.h.
Member Function Documentation
dump()
void PDBSymbolData::dump (PDBSymDumper & Dumper) const override virtual
Dumps the contents of a symbol a raw_ostream.
By default this will just call dump() on the underlying RawSymbol, which allows us to discover unknown properties, but individual implementations of PDBSymbol may override the behavior to only dump known fields.
Implements llvm::pdb::PDBSymbol.
Definition at line 19 of file PDBSymbolData.cpp.
References llvm::pdb::PDBSymDumper::dump().
getCompilandId()
uint32_t PDBSymbolData::getCompilandId () const
Definition at line 34 of file PDBSymbolData.cpp.
References llvm::pdb::IPDBSession::addressForRVA(), llvm::pdb::Compiland, llvm::pdb::Exe, llvm::pdb::IPDBRawSymbol::getAddressOffset(), llvm::pdb::IPDBRawSymbol::getAddressSection(), llvm::pdb::IPDBRawSymbol::getLexicalParentId(), getLineNumbers(), llvm::pdb::IPDBRawSymbol::getRelativeVirtualAddress(), llvm::pdb::IPDBSession::getSectionContribs(), llvm::pdb::IPDBSession::getSymbolById(), llvm::pdb::PDBSymbol::RawSymbol, and llvm::pdb::PDBSymbol::Session.
getLineNumbers()
std::unique_ptr< IPDBEnumLineNumbers > PDBSymbolData::getLineNumbers () const
Definition at line 21 of file PDBSymbolData.cpp.
References llvm::pdb::IPDBSession::findLineNumbersByRVA(), llvm::pdb::IPDBSession::findLineNumbersBySectOffset(), llvm::pdb::IPDBRawSymbol::getAddressOffset(), llvm::pdb::IPDBRawSymbol::getAddressSection(), llvm::pdb::IPDBRawSymbol::getLength(), llvm::pdb::IPDBRawSymbol::getRelativeVirtualAddress(), llvm::pdb::PDBSymbol::RawSymbol, and llvm::pdb::PDBSymbol::Session.
Referenced by getCompilandId().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/PDBSymbolData.h
lib/DebugInfo/PDB/PDBSymbolData.cpp