LLVM: llvm::FeatureBitArray Class Reference
llvm::FeatureBitArray Class Reference
Class used to store the subtarget bits in the tables created by tablegen.
#include "llvm/MC/SubtargetFeature.h"
Public Member Functions
constexpr FeatureBitArray (const std::array< uint64_t, MAX_SUBTARGET_WORDS > &B)
FeatureBitset getAsBitset () const
Detailed Description
Class used to store the subtarget bits in the tables created by tablegen.
The std::initializer_list constructor of FeatureBitset can't be done at compile time and requires a static constructor to run at startup.
Definition at line 63 of file SubtargetFeature.h.
Constructor & Destructor Documentation
FeatureBitArray()
constexpr llvm::FeatureBitArray::FeatureBitArray (const std::array< uint64_t, MAX_SUBTARGET_WORDS > & B) inline constexpr
Definition at line 67 of file SubtargetFeature.h.
Member Function Documentation
getAsBitset()
FeatureBitset llvm::FeatureBitArray::getAsBitset () const inline
Definition at line 70 of file SubtargetFeature.h.
Referenced by ApplyFeatureFlag(), getFeatures(), and llvm::MCSubtargetInfo::ToggleFeature().
The documentation for this class was generated from the following file:
include/llvm/MC/SubtargetFeature.h