LLVM: llvm::IRBuilder< T, Inserter > Class Template Reference
llvm::IRBuilder< T, Inserter > Class Template Reference
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
#include "llvm/IR/IRBuilder.h"
Public Member Functions
IRBuilder (LLVMContext &C, const T &F, Inserter I=Inserter(), MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (LLVMContext &C, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, const T &F, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (Instruction *IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, const T &F, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
const T & getFolder ()
Get the constant folder being used.
template<typename InstTy >
InstTy * Insert (InstTy *I, const Twine &Name="") const
Insert and return the specified instruction.
Constant * Insert (Constant *C, const Twine &="") const
No-op overload to handle constants.
ReturnInst * CreateRetVoid ()
Create a 'ret void' instruction.
ReturnInst * CreateRet (Value *V)
Create a 'ret <val>' instruction.
ReturnInst * CreateAggregateRet (Value *const *retVals, unsigned N)
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
BranchInst * CreateBr (BasicBlock *Dest)
Create an unconditional 'br label X' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, Instruction *MDSrc)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
SwitchInst * CreateSwitch (Value *V, BasicBlock *Dest, unsigned NumCases=10, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
IndirectBrInst * CreateIndirectBr (Value *Addr, unsigned NumDests=10)
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
Create an invoke instruction.
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args=None, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args=None, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args=None, const Twine &Name="")
Create a callbr instruction.
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
ResumeInst * CreateResume (Value *Exn)
CleanupReturnInst * CreateCleanupRet (CleanupPadInst *CleanupPad, BasicBlock *UnwindBB=nullptr)
CatchSwitchInst * CreateCatchSwitch (Value *ParentPad, BasicBlock *UnwindBB, unsigned NumHandlers, const Twine &Name="")
CatchPadInst * CreateCatchPad (Value *ParentPad, ArrayRef< Value * > Args, const Twine &Name="")
CleanupPadInst * CreateCleanupPad (Value *ParentPad, ArrayRef< Value * > Args=None, const Twine &Name="")
CatchReturnInst * CreateCatchRet (CatchPadInst *CatchPad, BasicBlock *BB)
UnreachableInst * CreateUnreachable ()
Value * CreateAdd (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSub (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateMul (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateUDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactUDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactSDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateURem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSRem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateShl (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, const APInt &RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, uint64_t RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateLShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAnd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateAnd (ArrayRef< Value * > Ops)
Value * CreateOr (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateOr (ArrayRef< Value * > Ops)
Value * CreateXor (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateFAdd (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFAddFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFSub (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFSubFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFMul (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFMulFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFDiv (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFDivFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFRem (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFRemFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPBinOp (Intrinsic::ID ID, Value *L, Value *R, Instruction *FMFSource=nullptr, const Twine &Name="", MDNode *FPMathTag=nullptr, Optional< ConstrainedFPIntrinsic::RoundingMode > Rounding=None, Optional< ConstrainedFPIntrinsic::ExceptionBehavior > Except=None)
Value * CreateNeg (Value *V, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWNeg (Value *V, const Twine &Name="")
Value * CreateNUWNeg (Value *V, const Twine &Name="")
Value * CreateFNeg (Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFNegFMF (Value *V, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateNot (Value *V, const Twine &Name="")
Value * CreateUnOp (Instruction::UnaryOps Opc, Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateNAryOp (unsigned Opc, ArrayRef< Value * > Ops, const Twine &Name="", MDNode *FPMathTag=nullptr)
Create either a UnaryOperator or BinaryOperator depending on Opc.
AllocaInst * CreateAlloca (Type *Ty, unsigned AddrSpace, Value *ArraySize=nullptr, const Twine &Name="")
AllocaInst * CreateAlloca (Type *Ty, Value *ArraySize=nullptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const char *Name)
Provided to resolve 'CreateLoad(Ty, Ptr, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, bool isVolatile, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, const char *Name)
LoadInst * CreateLoad (Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, bool isVolatile, const Twine &Name="")
StoreInst * CreateStore (Value *Val, Value *Ptr, bool isVolatile=false)
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, const char *Name)
Provided to resolve 'CreateAlignedLoad(Ptr, Align, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const char *Name)
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name="")
StoreInst * CreateAlignedStore (Value *Val, Value *Ptr, unsigned Align, bool isVolatile=false)
FenceInst * CreateFence (AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System, const Twine &Name="")
AtomicCmpXchgInst * CreateAtomicCmpXchg (Value *Ptr, Value *Cmp, Value *New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SyncScope::ID SSID=SyncScope::System)
AtomicRMWInst * CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value *Ptr, Value *Val, AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System)
Value * CreateGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateGEP (Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateConstGEP1_32 (Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateStructGEP (Type *Ty, Value *Ptr, unsigned Idx, const Twine &Name="")
Value * CreateStructGEP (Value *Ptr, unsigned Idx, const Twine &Name="")
Constant * CreateGlobalStringPtr (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Value * CreateTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a ZExt or Trunc from the integer value V to DestTy.
Value * CreateSExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a SExt or Trunc from the integer value V to DestTy.
Value * CreateFPToUI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPToSI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateUIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePtrToInt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntToPtr (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateTruncOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateCast (Instruction::CastOps Op, Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerBitCastOrAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntCast (Value *V, Type *DestTy, bool isSigned, const Twine &Name="")
Value * CreateBitOrPointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntCast (Value *, Type *, const char *)=delete
Value * CreateICmpEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpNE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpONE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpORD (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNO (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateICmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
PHINode * CreatePHI (Type *Ty, unsigned NumReservedValues, const Twine &Name="")
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value * > Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (Value *Callee, ArrayRef< Value * > Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (Value *Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateSelect (Value *C, Value *True, Value *False, const Twine &Name="", Instruction *MDFrom=nullptr)
VAArgInst * CreateVAArg (Value *List, Type *Ty, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, Value *Idx, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, uint64_t Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, Value *Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, uint64_t Idx, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, Value *Mask, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, ArrayRef< uint32_t > IntMask, const Twine &Name="")
Value * CreateExtractValue (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &Name="")
Value * CreateInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &Name="")
LandingPadInst * CreateLandingPad (Type *Ty, unsigned NumClauses, const Twine &Name="")
Value * CreateIsNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is null.
Value * CreateIsNotNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is not null.
Value * CreatePtrDiff (Value *LHS, Value *RHS, const Twine &Name="")
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
Value * CreateLaunderInvariantGroup (Value *Ptr)
Create a launder.invariant.group intrinsic call.
Value * CreateStripInvariantGroup (Value *Ptr)
Create a strip.invariant.group intrinsic call.
Value * CreateVectorSplat (unsigned NumElts, Value *V, const Twine &Name="")
Return a vector value that contains.
Value * CreateExtractInteger (const DataLayout &DL, Value *From, IntegerType *ExtractedTy, uint64_t Offset, const Twine &Name)
Return a value that has been extracted from a larger integer type.
Value * CreatePreserveArrayAccessIndex (Value *Base, unsigned Dimension, unsigned LastIndex)
Value * CreatePreserveUnionAccessIndex (Value *Base, unsigned FieldIndex, MDNode *DbgInfo)
Value * CreatePreserveStructAccessIndex (Value *Base, unsigned Index, unsigned FieldIndex, MDNode *DbgInfo)
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, unsigned Alignment, Value *OffsetValue=nullptr, Value **TheCheck=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, Value *Alignment, Value *OffsetValue=nullptr, Value **TheCheck=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
Public Member Functions inherited from llvm::IRBuilderBase
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
const DebugLoc & getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void setDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void setFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
void setIsFPConstrained (bool IsCon)
Enable/Disable use of constrained floating point math.
bool getIsFPConstrained ()
Query for the use of constrained floating point math.
void setDefaultConstrainedExcept (ConstrainedFPIntrinsic::ExceptionBehavior NewExcept)
Set the exception handling to be used with constrained floating point.
void setDefaultConstrainedRounding (ConstrainedFPIntrinsic::RoundingMode NewRounding)
Set the rounding mode handling to be used with constrained floating point.
ConstrainedFPIntrinsic::ExceptionBehavior getDefaultConstrainedExcept ()
Get the exception handling used with constrained floating point.
ConstrainedFPIntrinsic::RoundingMode getDefaultConstrainedRounding ()
Get the rounding mode handling used with constrained floating point.
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memcpy between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memmove between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateFAddReduce (Value *Acc, Value *Src)
Create a vector fadd reduction intrinsic of the source vector.
CallInst * CreateFMulReduce (Value *Acc, Value *Src)
Create a vector fmul reduction intrinsic of the source vector.
CallInst * CreateAddReduce (Value *Src)
Create a vector int add reduction intrinsic of the source vector.
CallInst * CreateMulReduce (Value *Src)
Create a vector int mul reduction intrinsic of the source vector.
CallInst * CreateAndReduce (Value *Src)
Create a vector int AND reduction intrinsic of the source vector.
CallInst * CreateOrReduce (Value *Src)
Create a vector int OR reduction intrinsic of the source vector.
CallInst * CreateXorReduce (Value *Src)
Create a vector int XOR reduction intrinsic of the source vector.
CallInst * CreateIntMaxReduce (Value *Src, bool IsSigned=false)
Create a vector integer max reduction intrinsic of the source vector.
CallInst * CreateIntMinReduce (Value *Src, bool IsSigned=false)
Create a vector integer min reduction intrinsic of the source vector.
CallInst * CreateFPMaxReduce (Value *Src, bool NoNaN=false)
Create a vector float max reduction intrinsic of the source vector.
CallInst * CreateFPMinReduce (Value *Src, bool NoNaN=false)
Create a vector float min reduction intrinsic of the source vector.
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateInvariantStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a call to invariant.start intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateMaskedGather (Value *Ptrs, unsigned Align, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Gather intrinsic.
CallInst * CreateMaskedScatter (Value *Val, Value *Ptrs, unsigned Align, Value *Mask=nullptr)
Create a call to Masked Scatter intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
CallInst * CreateUnaryIntrinsic (Intrinsic::ID ID, Value *V, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
CallInst * CreateBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
CallInst * CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type * > Types, ArrayRef< Value * > Args, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with args, mangled using Types.
CallInst * CreateMinNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minnum intrinsic.
CallInst * CreateMaxNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maxnum intrinsic.
CallInst * CreateMinimum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minimum intrinsic.
CallInst * CreateMaximum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maximum intrinsic.
Additional Inherited Members
Protected Member Functions inherited from llvm::IRBuilderDefaultInserter
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Protected Attributes inherited from llvm::IRBuilderBase
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
bool IsFPConstrained
ConstrainedFPIntrinsic::ExceptionBehavior DefaultConstrainedExcept
ConstrainedFPIntrinsic::RoundingMode DefaultConstrainedRounding
ArrayRef< OperandBundleDef > DefaultOperandBundles
Detailed Description
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter>
class llvm::IRBuilder< T, Inserter >
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
Note that the builder does not expose the full generality of LLVM instructions. For access to extra instruction properties, use the mutators (e.g. setVolatile) on the instructions after they have been created. Convenience state exists to specify fast-math flags and fp-math tags.
The first template argument specifies a class to use for creating constants. This defaults to creating minimally folded constants. The second template argument allows clients to specify custom insertion hooks that are called on every newly created insertion.
Definition at line 779 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilder() [1/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (LLVMContext & C, const T & F, Inserter I = Inserter(), MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 783 of file IRBuilder.h.
IRBuilder() [2/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (LLVMContext & C, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 789 of file IRBuilder.h.
IRBuilder() [3/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, const T & F, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 793 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [4/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 799 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [5/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (Instruction * IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 805 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [6/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, const T & F, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 811 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [7/7]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> llvm::IRBuilder< T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 818 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
Member Function Documentation
CreateAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAdd (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1118 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::InstCombiner::commonIDivTransforms(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::IRBuilder< T, Inserter >::CreateNSWAdd(), llvm::IRBuilder< T, Inserter >::CreateNUWAdd(), evaluateGEPOffsetExpression(), foldAndOrOfEqualityCmpsWithConstants(), foldICmpWithTruncSignExtendedVal(), foldUDivShl(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getStepVector(), LowerAtomicRMWInst(), LowerCTPOP(), performAtomicOp(), TurnSwitchRangeIntoICmp(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitAdd(), llvm::ObjectSizeOffsetEvaluator::visitGEPOperator(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitURem(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreateAddrSpaceCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1956 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by simplifyInvariantGroupIntrinsic().
CreateAggregateRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst * llvm::IRBuilder< T, Inserter >::CreateAggregateRet (Value *const * retVals, unsigned N) inline
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
This is a convenience function for code that uses aggregate return values as a vehicle for having multiple return values.
Definition at line 876 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::ReturnInst::Create(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::IRBuilder< T, Inserter >::Insert(), and N.
CreateAlignedLoad() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 1624 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), isVolatile(), Name, and llvm::LoadInst::setAlignment().
CreateAlignedLoad() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, const char * Name) inline
Provided to resolve 'CreateAlignedLoad(Ptr, Align, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
Definition at line 1612 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), Name, and llvm::LoadInst::setAlignment().
Referenced by combineLoadToNewType(), llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), simplifyNeonVld1(), unpackLoadToAggregate(), llvm::UpgradeIntrinsicCall(), UpgradeMaskedLoad(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateAlignedLoad() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Type * Ty, Value * Ptr, unsigned Align, const Twine & Name = "") inline
Definition at line 1618 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), Name, and llvm::LoadInst::setAlignment().
CreateAlignedLoad() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 1643 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), isVolatile(), and Name.
CreateAlignedLoad() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const char * Name) inline
Definition at line 1632 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), and Name.
CreateAlignedLoad() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const Twine & Name = "") inline
Definition at line 1637 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), and Name.
CreateAlignedStore()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> StoreInst * llvm::IRBuilder< T, Inserter >::CreateAlignedStore (Value * Val, Value * Ptr, unsigned Align, bool isVolatile = false) inline
Definition at line 1649 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateStore(), isVolatile(), and SI.
Referenced by combineStoreToNewValue(), scalarizeMaskedCompressStore(), scalarizeMaskedScatter(), scalarizeMaskedStore(), splitMergedValStore(), unpackStoreToAggregate(), llvm::UpgradeIntrinsicCall(), UpgradeMaskedStore(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateAlignmentAssumption() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption (const DataLayout & DL, Value * PtrValue, unsigned Alignment, Value * OffsetValue = nullptr, Value ** TheCheck = nullptr) inline
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
An optional offset can be provided, and if it is provided, the offset must be subtracted from the provided pointer to get the pointer with the specified alignment.
It may be sometimes useful to do some other logic based on this alignment check, thus it can be stored into 'TheCheck'.
Definition at line 2567 of file IRBuilder.h.
References assert(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getIntPtrTy(), and llvm::Value::getType().
Referenced by AddAlignmentAssumptions().
CreateAlignmentAssumption() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption (const DataLayout & DL, Value * PtrValue, Value * Alignment, Value * OffsetValue = nullptr, Value ** TheCheck = nullptr) inline
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
An optional offset can be provided, and if it is provided, the offset must be subtracted from the provided pointer to get the pointer with the specified alignment.
It may be sometimes useful to do some other logic based on this alignment check, thus it can be stored into 'TheCheck'.
This overload handles the condition where the Alignment is dependent on an existing value rather than a static value.
Definition at line 2594 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getIntPtrTy(), and llvm::Value::getType().
CreateAlloca() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AllocaInst * llvm::IRBuilder< T, Inserter >::CreateAlloca (Type * Ty, unsigned AddrSpace, Value * ArraySize = nullptr, const Twine & Name = "") inline
Definition at line 1563 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by handleNoSuspendCoroutine(), and simplifyAllocaArraySize().
CreateAlloca() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AllocaInst * llvm::IRBuilder< T, Inserter >::CreateAlloca (Type * Ty, Value * ArraySize = nullptr, const Twine & Name = "") inline
Definition at line 1568 of file IRBuilder.h.
References llvm::IRBuilderBase::BB, llvm::DataLayout::getAllocaAddrSpace(), llvm::BasicBlock::getParent(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateAnd() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAnd (ArrayRef< Value * > Ops) inline
Definition at line 1286 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::size().
CreateAnd() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1278 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateAnd() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1282 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateAnd() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAnd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1268 of file IRBuilder.h.
References llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), ApplyX86MaskOn1BitsVec(), buildPartialUnswitchConditionalBranch(), checkForNegativeOperand(), llvm::InstCombiner::commonShiftTransforms(), llvm::IRBuilder< T, Inserter >::CreateAnd(), createMaskInstrs(), foldAnyOrAllBitsSet(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), performAtomicOp(), performMaskedAtomicOp(), processUMulZExtIdiom(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), upgradePMULDQ(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), visitMaskedMerge(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
CreateAShr() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1258 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateAShr() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1263 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateAShr() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateAShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1248 of file IRBuilder.h.
References llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAShr(), foldSelectICmpLshrAshr(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), simplifyX86immShift(), simplifyX86varShift(), upgradePMULDQ(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitTrunc().
CreateAtomicCmpXchg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AtomicCmpXchgInst * llvm::IRBuilder< T, Inserter >::CreateAtomicCmpXchg (Value * Ptr, Value * Cmp, Value * New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SyncScope::ID SSID = SyncScope::System) inline
Definition at line 1663 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert().
Referenced by createCmpXchgInstFun().
CreateAtomicRMW()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> AtomicRMWInst * llvm::IRBuilder< T, Inserter >::CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value * Ptr, Value * Val, AtomicOrdering Ordering, SyncScope::ID SSID = SyncScope::System) inline
Definition at line 1671 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert().
Referenced by llvm::UpgradeIntrinsicCall().
CreateBinOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1458 of file IRBuilder.h.
References llvm::BinaryOperator::Create(), llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::InstCombiner::commonShiftTransforms(), llvm::IRBuilder< T, Inserter >::CreateNAryOp(), createReplacementInstr(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::fixReduction(), llvm::FoldBranchToCommonDest(), foldLogicCastConstant(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), llvm::InstCombiner::FoldShiftByConstant(), llvm::getOrderedReduction(), llvm::getShuffleReduction(), llvm::InnerLoopVectorizer::getStepVector(), matchDeMorgansLaws(), narrowUDivURem(), SimplifyBSwap(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombiner::visitAnd(), and llvm::InstCombiner::visitMul().
CreateBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1951 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), ApplyX86MaskOn1BitsVec(), canonicalizeBitCastExtElt(), combineLoadToNewType(), combineStoreToNewValue(), llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), createCast(), createClone(), createCmpXchgInstFun(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), EmitX86ScalarSelect(), foldBitCastBitwiseLogic(), foldBitcastExtElt(), foldBitCastSelect(), foldICmpBitCast(), foldVecTruncToExtElt(), llvm::SCEVExpander::generateOverflowCheck(), llvm::VNCoercion::getLoadValueForLoad(), getX86MaskVec(), handleNoSuspendCoroutine(), llvm::InlineFunction(), insertRelocationStores(), insertSpills(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerSubFn(), optimizeVectorResize(), scalarizeMaskedLoad(), scalarizeMaskedStore(), simplifyInvariantGroupIntrinsic(), simplifyNeonVld1(), simplifyRelocatesOffABase(), simplifyX86extrq(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), splitMergedValStore(), tryPromoteAllocaToVector(), llvm::UpgradeIntrinsicCall(), UpgradeMaskedLoad(), UpgradeMaskedStore(), upgradePMULDQ(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), UpgradeX86VPERMT2Intrinsics(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), versionCallSite(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitShuffleVectorInst().
CreateBitOrPointerCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2029 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPtrOrPtrVectorTy(), and Name.
Referenced by llvm::InnerLoopVectorizer::createBitOrPointerCast(), rewriteGEPAsOffset(), and llvm::InstCombiner::visitLoadInst().
CreateBr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst * llvm::IRBuilder< T, Inserter >::CreateBr (BasicBlock * Dest) inline
Create an unconditional 'br label X' instruction.
Definition at line 884 of file IRBuilder.h.
References llvm::BranchInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by CloneLoopBlocks(), llvm::ConstantFoldTerminator(), llvm::deleteDeadLoop(), FoldTwoEntryPHINode(), generateUnsignedDivisionCode(), optimizeSQRT(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), SimplifyTerminatorOnSelect(), SwitchToLookupTable(), and versionCallSite().
CreateCall() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2217 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateCall() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2211 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateCall() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (FunctionType * FTy, Value * Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2202 of file IRBuilder.h.
References Callee, llvm::CallInst::Create(), llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateCall() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (FunctionType * FTy, Value * Callee, ArrayRef< Value * > Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2193 of file IRBuilder.h.
References Callee, llvm::CallInst::Create(), llvm::IRBuilderBase::DefaultOperandBundles, llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by callIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateCall(), createFFSIntrinsic(), CreateGCRelocates(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), createPopcntIntrinsic(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex(), llvm::createSanitizerCtorAndInitFunctions(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), foldGuardedRotateToFunnelShift(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::InlineFunction(), instrumentOneFunc(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerObjCCall(), llvm::ARMTargetLowering::makeDMB(), llvm::orc::makeStub(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), ReplaceCallWith(), SimplifyBSwap(), simplifyX86extrq(), simplifyX86insertq(), upgradeAVX512MaskToSelect(), llvm::UpgradeIntrinsicCall(), UpgradeX86AddSubSatIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), UpgradeX86VPERMT2Intrinsics(), UseTlsOffset(), llvm::InstCombiner::visitCallInst(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateCall() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (Value * Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2233 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), and Name.
CreateCall() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateCall (Value * Callee, ArrayRef< Value * > Args = None, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2225 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCall(), and Name.
CreateCallBr() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst * llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionCallee Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 1010 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCallBr(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateCallBr() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst * llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionCallee Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Definition at line 1003 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateCallBr(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateCallBr() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst * llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionType * Ty, Value * Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 992 of file IRBuilder.h.
References Callee, llvm::CallBrInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateCallBr() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallBrInst * llvm::IRBuilder< T, Inserter >::CreateCallBr (FunctionType * Ty, Value * Callee, BasicBlock * DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Create a callbr instruction.
Definition at line 984 of file IRBuilder.h.
References Callee, llvm::CallBrInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateCallBr().
CreateCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateCast (Instruction::CastOps Op, Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1988 of file IRBuilder.h.
References llvm::CastInst::Create(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAddrSpaceCast(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateFPExt(), llvm::IRBuilder< T, Inserter >::CreateFPToSI(), llvm::IRBuilder< T, Inserter >::CreateFPToUI(), llvm::IRBuilder< T, Inserter >::CreateFPTrunc(), llvm::IRBuilder< T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), createReplacementInstr(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::IRBuilder< T, Inserter >::CreateSIToFP(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateUIToFP(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::IRBuilder< T, Inserter >::CreateZExt(), foldOperationIntoSelectOperand(), shrinkInsertElt(), llvm::InnerLoopVectorizer::widenInstruction(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
CreateCatchPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchPadInst * llvm::IRBuilder< T, Inserter >::CreateCatchPad (Value * ParentPad, ArrayRef< Value * > Args, const Twine & Name = "") inline
Definition at line 1035 of file IRBuilder.h.
References llvm::CatchPadInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateCatchRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchReturnInst * llvm::IRBuilder< T, Inserter >::CreateCatchRet (CatchPadInst * CatchPad, BasicBlock * BB) inline
Definition at line 1046 of file IRBuilder.h.
References llvm::IRBuilderBase::BB, llvm::CatchReturnInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
CreateCatchSwitch()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CatchSwitchInst * llvm::IRBuilder< T, Inserter >::CreateCatchSwitch (Value * ParentPad, BasicBlock * UnwindBB, unsigned NumHandlers, const Twine & Name = "") inline
Definition at line 1028 of file IRBuilder.h.
References llvm::CatchSwitchInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateCleanupPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CleanupPadInst * llvm::IRBuilder< T, Inserter >::CreateCleanupPad (Value * ParentPad, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Definition at line 1040 of file IRBuilder.h.
References llvm::CleanupPadInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateCleanupRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CleanupReturnInst * llvm::IRBuilder< T, Inserter >::CreateCleanupRet (CleanupPadInst * CleanupPad, BasicBlock * UnwindBB = nullptr) inline
Definition at line 1023 of file IRBuilder.h.
References llvm::CleanupReturnInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
CreateCondBr() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst * llvm::IRBuilder< T, Inserter >::CreateCondBr (Value * Cond, BasicBlock * True, BasicBlock * False, Instruction * MDSrc) inline
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
Copy branch meta data if available.
Definition at line 899 of file IRBuilder.h.
References llvm::Instruction::copyMetadata(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), llvm::makeArrayRef(), llvm::LLVMContext::MD_dbg, llvm::LLVMContext::MD_make_implicit, llvm::LLVMContext::MD_prof, and llvm::LLVMContext::MD_unpredictable.
CreateCondBr() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> BranchInst * llvm::IRBuilder< T, Inserter >::CreateCondBr (Value * Cond, BasicBlock * True, BasicBlock * False, MDNode * BranchWeights = nullptr, MDNode * Unpredictable = nullptr) inline
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
Definition at line 890 of file IRBuilder.h.
References llvm::BranchInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by buildPartialUnswitchConditionalBranch(), CloneLoopBlocks(), llvm::ConstantFoldTerminator(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::deleteDeadLoop(), despeculateCountZeros(), generateUnsignedDivisionCode(), handleFinalSuspend(), optimizeSQRT(), SimplifyBranchOnICmpChain(), SimplifyTerminatorOnSelect(), SwitchToLookupTable(), and TurnSwitchRangeIntoICmp().
CreateConstGEP1_32() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32 (Type * Ty, Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1739 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::Create(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateConstGEP1_32() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32 (Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1735 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), and UseTlsOffset().
CreateConstGEP1_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64 (Type * Ty, Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1785 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::Create(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt64Ty(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64().
CreateConstGEP1_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1795 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), and Name.
CreateConstGEP2_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32 (Type * Ty, Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1759 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::Create(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateConstGEP2_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64 (Type * Ty, Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1814 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::Create(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64().
CreateConstGEP2_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1827 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), and Name.
CreateConstInBoundsGEP1_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32 (Type * Ty, Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1749 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::CreateInBounds(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedLoad(), and scalarizeMaskedStore().
CreateConstInBoundsGEP1_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64 (Type * Ty, Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1799 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::CreateInBounds(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt64Ty(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64().
CreateConstInBoundsGEP1_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1809 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), and Name.
CreateConstInBoundsGEP2_32()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32 (Type * Ty, Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1772 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::CreateInBounds(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by createResumeEntryBlock(), llvm::IRBuilder< T, Inserter >::CreateStructGEP(), handleFinalSuspend(), insertSpills(), lowerSubFn(), and updateCoroFrame().
CreateConstInBoundsGEP2_64() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64 (Type * Ty, Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1832 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::GetElementPtrInst::CreateInBounds(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64().
CreateConstInBoundsGEP2_64() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1845 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), and Name.
CreateConstrainedFPBinOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> CallInst * llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp (Intrinsic::ID ID, Value * L, Value * R, Instruction * FMFSource = nullptr, const Twine & Name = "", MDNode * FPMathTag = nullptr, Optional< ConstrainedFPIntrinsic::RoundingMode > Rounding = None, Optional< ConstrainedFPIntrinsic::ExceptionBehavior > Except = None) inline
Definition at line 1468 of file IRBuilder.h.
References C, llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::FMF, llvm::Value::getType(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAddFMF(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDivFMF(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), llvm::IRBuilder< T, Inserter >::CreateFRem(), llvm::IRBuilder< T, Inserter >::CreateFRemFMF(), llvm::IRBuilder< T, Inserter >::CreateFSub(), and llvm::IRBuilder< T, Inserter >::CreateFSubFMF().
CreateExactSDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExactSDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1193 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateSDiv(), and Name.
Referenced by llvm::NoFolder::CreateExactSDiv(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), llvm::NoFolder::CreateSDiv(), and llvm::IRBuilder< T, Inserter >::CreateSDiv().
CreateExactUDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExactUDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1179 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateUDiv(), and Name.
Referenced by llvm::NoFolder::CreateExactUDiv(), llvm::NoFolder::CreateUDiv(), and llvm::IRBuilder< T, Inserter >::CreateUDiv().
CreateExtractElement() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExtractElement (Value * Vec, uint64_t Idx, const Twine & Name = "") inline
Definition at line 2271 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilderBase::getInt64(), Idx, and Name.
CreateExtractElement() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExtractElement (Value * Vec, Value * Idx, const Twine & Name = "") inline
Definition at line 2263 of file IRBuilder.h.
References llvm::ExtractElementInst::Create(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateExtractElement(), EmitX86ScalarSelect(), llvm::VPBasicBlock::execute(), llvm::VPBranchOnMaskRecipe::execute(), extractValues(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), foldICmpBitCast(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::getOrderedReduction(), llvm::getShuffleReduction(), instrumentMaskedLoadOrStore(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), tryPromoteAllocaToVector(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), and llvm::InstCombiner::visitShuffleVectorInst().
CreateExtractInteger()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExtractInteger (const DataLayout & DL, Value * From, IntegerType * ExtractedTy, uint64_t Offset, const Twine & Name) inline
Return a value that has been extracted from a larger integer type.
Definition at line 2433 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), From, llvm::IntegerType::getBitWidth(), llvm::DataLayout::getTypeStoreSize(), llvm::DataLayout::isBigEndian(), and Name.
CreateExtractValue()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateExtractValue (Value * Agg, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 2305 of file IRBuilder.h.
References llvm::ExtractValueInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by createCast(), createCmpXchgInstFun(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::SCEVExpander::generateOverflowCheck(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), simplifyX86addcarry(), unpackStoreToAggregate(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitExtractValueInst().
CreateFAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFAdd (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1333 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFAdd(), llvm::AtomicRMWInst::FAdd, llvm::IRBuilderBase::FMF, I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by LowerAtomicRMWInst(), performAtomicOp(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
CreateFAddFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFAddFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1346 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFAdd(), llvm::AtomicRMWInst::FAdd, llvm::Instruction::getFastMathFlags(), I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by factorizeFAddFSub(), and llvm::InstCombiner::visitFMul().
CreateFCmp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2176 of file IRBuilder.h.
References llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), Name, and P.
Referenced by llvm::IRBuilder< T, Inserter >::CreateFCmpOEQ(), llvm::IRBuilder< T, Inserter >::CreateFCmpOGE(), llvm::IRBuilder< T, Inserter >::CreateFCmpOGT(), llvm::IRBuilder< T, Inserter >::CreateFCmpOLE(), llvm::IRBuilder< T, Inserter >::CreateFCmpOLT(), llvm::IRBuilder< T, Inserter >::CreateFCmpONE(), llvm::IRBuilder< T, Inserter >::CreateFCmpORD(), llvm::IRBuilder< T, Inserter >::CreateFCmpUEQ(), llvm::IRBuilder< T, Inserter >::CreateFCmpUGE(), llvm::IRBuilder< T, Inserter >::CreateFCmpUGT(), llvm::IRBuilder< T, Inserter >::CreateFCmpULE(), llvm::IRBuilder< T, Inserter >::CreateFCmpULT(), llvm::IRBuilder< T, Inserter >::CreateFCmpUNE(), llvm::IRBuilder< T, Inserter >::CreateFCmpUNO(), llvm::createMinMaxOp(), foldVectorCmp(), getFCmpValue(), reassociateFCmps(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateFCmpOEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpOEQ (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2098 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_OEQ, and Name.
Referenced by llvm::InstCombiner::visitCallInst().
CreateFCmpOGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpOGE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2108 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_OGE, and Name.
Referenced by optimizeSQRT().
CreateFCmpOGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpOGT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2103 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_OGT, and Name.
CreateFCmpOLE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpOLE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2118 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_OLE, and Name.
CreateFCmpOLT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpOLT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2113 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_OLT, and Name.
CreateFCmpONE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpONE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2123 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_ONE, and Name.
CreateFCmpORD()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpORD (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2128 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_ORD, and Name.
Referenced by optimizeSQRT().
CreateFCmpUEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpUEQ (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2138 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_UEQ, and Name.
CreateFCmpUGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpUGE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2148 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_UGE, and Name.
CreateFCmpUGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpUGT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2143 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_UGT, and Name.
CreateFCmpULE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpULE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2158 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_ULE, and Name.
CreateFCmpULT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpULT (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2153 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_ULT, and Name.
CreateFCmpUNE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpUNE (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2163 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_UNE, and Name.
CreateFCmpUNO()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFCmpUNO (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 2133 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::CmpInst::FCMP_UNO, and Name.
Referenced by llvm::InstCombiner::visitCallInst().
CreateFDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFDiv (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1408 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFDiv(), llvm::IRBuilderBase::FMF, I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
CreateFDivFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFDivFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1421 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFDiv(), llvm::Instruction::getFastMathFlags(), I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
CreateFence()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> FenceInst * llvm::IRBuilder< T, Inserter >::CreateFence (AtomicOrdering Ordering, SyncScope::ID SSID = SyncScope::System, const Twine & Name = "") inline
Definition at line 1656 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::TargetLoweringBase::emitLeadingFence(), llvm::RISCVTargetLowering::emitLeadingFence(), llvm::TargetLoweringBase::emitTrailingFence(), and llvm::RISCVTargetLowering::emitTrailingFence().
CreateFMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFMul (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1383 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFMul(), llvm::IRBuilderBase::FMF, I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by buildMultiplyTree(), llvm::InnerLoopVectorizer::getStepVector(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
CreateFMulFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFMulFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1396 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFMul(), llvm::Instruction::getFastMathFlags(), I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by llvm::InstCombiner::visitFDiv(), and llvm::InstCombiner::visitFMul().
CreateFNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFNeg (Value * V, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1503 of file IRBuilder.h.
References llvm::BinaryOperator::CreateFNeg(), llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::UpgradeIntrinsicCall().
CreateFNegFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFNegFMF (Value * V, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1513 of file IRBuilder.h.
References llvm::BinaryOperator::CreateFNeg(), llvm::Instruction::getFastMathFlags(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateFPCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFPCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2041 of file IRBuilder.h.
References llvm::CastInst::CreateFPCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateFPExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFPExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1937 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::CCValAssign::FPExt, and Name.
Referenced by llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFSub().
CreateFPToSI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFPToSI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1920 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
CreateFPToUI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFPToUI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1916 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
CreateFPTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFPTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1932 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFPTrunc(), and llvm::InstCombiner::visitFSub().
CreateFRem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFRem (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1433 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFRem(), llvm::IRBuilderBase::FMF, I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
CreateFRemFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFRemFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1446 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFRem(), llvm::Instruction::getFastMathFlags(), I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by llvm::InstCombiner::visitFPTrunc().
CreateFSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFSub (Value * L, Value * R, const Twine & Name = "", MDNode * FPMD = nullptr) inline
Definition at line 1358 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFSub(), llvm::IRBuilderBase::FMF, llvm::AtomicRMWInst::FSub, I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by LowerAtomicRMWInst(), performAtomicOp(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
CreateFSubFMF()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateFSubFMF (Value * L, Value * R, Instruction * FMFSource, const Twine & Name = "") inline
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Definition at line 1371 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::TargetFolder::CreateFSub(), llvm::AtomicRMWInst::FSub, llvm::Instruction::getFastMathFlags(), I, llvm::IRBuilder< T, Inserter >::Insert(), llvm::IRBuilderBase::IsFPConstrained, and Name.
Referenced by factorizeFAddFSub(), and llvm::InstCombiner::visitFSub().
CreateGEP() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1682 of file IRBuilder.h.
References llvm::GetElementPtrInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), Name, and llvm::ArrayRef< T >::size().
CreateGEP() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateGEP (Type * Ty, Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1720 of file IRBuilder.h.
References llvm::GetElementPtrInst::Create(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateGEP() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateGEP (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1677 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateGEP(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateGEP(), doPromotion(), instrumentMaskedLoadOrStore(), simplifyRelocatesOffABase(), splitMergedValStore(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateGEP() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateGEP (Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1716 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateGEP(), Idx, and Name.
CreateGlobalStringPtr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Constant * llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr (StringRef Str, const Twine & Name = "", unsigned AddressSpace = 0) inline
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Definition at line 1861 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::IRBuilderBase::CreateGlobalString(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::IRBuilderBase::getInt32Ty(), llvm::GlobalValue::getValueType(), and Name.
CreateICmp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2168 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), Name, and P.
Referenced by llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::IRBuilder< T, Inserter >::CreateICmpSGE(), llvm::IRBuilder< T, Inserter >::CreateICmpSGT(), llvm::IRBuilder< T, Inserter >::CreateICmpSLE(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::IRBuilder< T, Inserter >::CreateICmpUGE(), llvm::IRBuilder< T, Inserter >::CreateICmpUGT(), llvm::IRBuilder< T, Inserter >::CreateICmpULE(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), createMinMax(), llvm::createMinMaxOp(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), foldAndOrOfEqualityCmpsWithConstants(), foldICmpWithLowBitMaskedVal(), foldICmpWithTruncSignExtendedVal(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldVectorCmp(), llvm::SCEVExpander::generateOverflowCheck(), getNewICmpValue(), llvm::InstCombiner::simplifyRangeCheck(), upgradeAbs(), upgradeIntMinMax(), llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), upgradeX86vpcom(), llvm::InstCombiner::visitXor(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateICmpEQ()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpEQ (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2058 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_EQ, and Name.
Referenced by llvm::InstCombiner::commonIDivTransforms(), llvm::ConstantFoldTerminator(), ConvertTwoCaseSwitch(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::IRBuilder< T, Inserter >::CreateIsNull(), createMemMoveLoop(), createMemSetLoop(), despeculateCountZeros(), llvm::HexagonTargetLowering::emitStoreConditional(), foldAnyOrAllBitsSet(), foldIsPowerOf2(), generateUnsignedDivisionCode(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), handleFinalSuspend(), LowerAtomicCmpXchgInst(), llvm::UpgradeIntrinsicCall(), versionCallSite(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitUDiv(), and llvm::InstCombiner::visitURem().
CreateICmpNE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpNE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2062 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_NE, and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateIsNotNull(), llvm::createMemCpyLoopUnknownSize(), llvm::SCEVExpander::expandEqualPredicate(), foldIsPowerOf2(), and llvm::InstCombiner::visitURem().
CreateICmpSGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpSGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2086 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_SGE, and Name.
Referenced by llvm::UpgradeIntrinsicCall().
CreateICmpSGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpSGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2082 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_SGT, and Name.
Referenced by performAtomicOp(), and simplifyX86pack().
CreateICmpSLE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpSLE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2094 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_SLE, and Name.
Referenced by performAtomicOp(), and llvm::UpgradeIntrinsicCall().
CreateICmpSLT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpSLT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2090 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_SLT, and Name.
Referenced by getBoundsCheckCond(), LowerAtomicRMWInst(), simplifyX86movmsk(), simplifyX86pack(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateICmpUGE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpUGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2070 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_UGE, and Name.
Referenced by llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitUDiv().
CreateICmpUGT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpUGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2066 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_UGT, and Name.
Referenced by generateUnsignedDivisionCode(), and performAtomicOp().
CreateICmpULE()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpULE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2078 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_ULE, and Name.
Referenced by performAtomicOp(), and llvm::UpgradeIntrinsicCall().
CreateICmpULT()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateICmpULT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 2074 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::ICMP_ULT, and Name.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), llvm::InstCombiner::commonIDivTransforms(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), foldSignedTruncationCheck(), getBoundsCheckCond(), LowerAtomicRMWInst(), llvm::lowerObjectSizeCall(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), and llvm::InstCombiner::visitURem().
CreateInBoundsGEP() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1701 of file IRBuilder.h.
References llvm::GetElementPtrInst::CreateInBounds(), llvm::IRBuilder< T, Inserter >::Insert(), Name, and llvm::ArrayRef< T >::size().
CreateInBoundsGEP() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Type * Ty, Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1727 of file IRBuilder.h.
References llvm::GetElementPtrInst::CreateInBounds(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateInBoundsGEP() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1696 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createReplacementInstr(), insertSpills(), rewriteGEPAsOffset(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateIndirectBr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> IndirectBrInst * llvm::IRBuilder< T, Inserter >::CreateIndirectBr (Value * Addr, unsigned NumDests = 10) inline
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
Definition at line 923 of file IRBuilder.h.
References llvm::IndirectBrInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
CreateInsertElement() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInsertElement (Value * Vec, Value * NewElt, uint64_t Idx, const Twine & Name = "") inline
Definition at line 2285 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilderBase::getInt64(), Idx, and Name.
CreateInsertElement() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInsertElement (Value * Vec, Value * NewElt, Value * Idx, const Twine & Name = "") inline
Definition at line 2276 of file IRBuilder.h.
References llvm::InsertElementInst::Create(), Idx, llvm::IRBuilder< T, Inserter >::Insert(), Name, and NC.
Referenced by canonicalizeInsertSplat(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), hoistInsEltConst(), insertValues(), optimizeIntegerToVectorInsertions(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), tryPromoteAllocaToVector(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitInsertElementInst().
CreateInsertValue()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 2313 of file IRBuilder.h.
References llvm::InsertValueInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAggregateRet(), createCast(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), LowerAtomicCmpXchgInst(), simplifyX86addcarry(), and unpackLoadToAggregate().
CreateIntCast() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateIntCast (Value * , Type * , const char *) delete
CreateIntCast() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateIntCast (Value * V, Type * DestTy, bool isSigned, const Twine & Name = "") inline
Definition at line 2020 of file IRBuilder.h.
References llvm::CastInst::CreateIntegerCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption(), evaluateGEPOffsetExpression(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::InstCombiner::OptimizePointerDifference(), simplifyAllocaArraySize(), upgradeX86ConcatShift(), upgradeX86Rotate(), and llvm::InstCombiner::visitGetElementPtrInst().
CreateIntToPtr()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateIntToPtr (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1946 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), createCast(), createMaskInstrs(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), and llvm::ARMTargetLowering::lowerInterleavedLoad().
CreateInvoke() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionCallee Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 945 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateInvoke(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateInvoke() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionCallee Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Definition at line 953 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateInvoke(), llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and Name.
CreateInvoke() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionType * Ty, Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Create an invoke instruction.
Definition at line 928 of file IRBuilder.h.
References Callee, llvm::InvokeInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateInvoke().
CreateInvoke() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (FunctionType * Ty, Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Definition at line 937 of file IRBuilder.h.
References Callee, llvm::InvokeInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateInvoke() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine & Name = "") inline
Definition at line 962 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateInvoke(), and Name.
CreateInvoke() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> InvokeInst * llvm::IRBuilder< T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args = None, const Twine & Name = "") inline
Definition at line 973 of file IRBuilder.h.
References Callee, llvm::IRBuilder< T, Inserter >::CreateInvoke(), and Name.
CreateIsNotNull()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateIsNotNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is not null.
Definition at line 2338 of file IRBuilder.h.
References Arg, llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::Constant::getNullValue(), and Name.
Referenced by CloneLoopBlocks(), foldAnyOrAllBitsSet(), foldSelectICmpAndAnd(), llvm::UnrollRuntimeLoopRemainder(), and upgradeMaskedMove().
CreateIsNull()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateIsNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is null.
Definition at line 2332 of file IRBuilder.h.
References Arg, llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::Constant::getNullValue(), and Name.
Referenced by llvm::UnrollRuntimeLoopRemainder().
CreateLandingPad()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LandingPadInst * llvm::IRBuilder< T, Inserter >::CreateLandingPad (Type * Ty, unsigned NumClauses, const Twine & Name = "") inline
Definition at line 2322 of file IRBuilder.h.
References llvm::LandingPadInst::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateLaunderInvariantGroup()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup (Value * Ptr) inline
Create a launder.invariant.group intrinsic call.
If Ptr type is different from pointer to i8, it's casted to pointer to i8 in the same address space before call and casted back to Ptr type after call.
Definition at line 2364 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::BB, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::Function::getReturnType(), and llvm::Value::getType().
Referenced by simplifyInvariantGroupIntrinsic().
CreateLoad() [1/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, bool isVolatile, const Twine & Name = "") inline
Definition at line 1584 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), isVolatile(), and Name.
CreateLoad() [2/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, const char * Name) inline
Provided to resolve 'CreateLoad(Ty, Ptr, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
Definition at line 1576 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createResumeEntryBlock(), doPromotion(), llvm::VNCoercion::getLoadValueForLoad(), handleFinalSuspend(), insertSpills(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), lowerSubFn(), llvm::orc::makeStub(), tryPromoteAllocaToVector(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractValueInst(), and llvm::InstCombiner::visitLoadInst().
CreateLoad() [3/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Type * Ty, Value * Ptr, const Twine & Name = "") inline
Definition at line 1580 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateLoad() [4/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, bool isVolatile, const Twine & Name = "") inline
Definition at line 1600 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), isVolatile(), and Name.
CreateLoad() [5/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, const char * Name) inline
Definition at line 1590 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), and Name.
CreateLoad() [6/6]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> LoadInst * llvm::IRBuilder< T, Inserter >::CreateLoad (Value * Ptr, const Twine & Name = "") inline
Definition at line 1595 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::Type::getPointerElementType(), llvm::Value::getType(), and Name.
CreateLShr() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1238 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateLShr() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1243 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateLShr() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateLShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1228 of file IRBuilder.h.
References llvm::TargetFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateExtractInteger(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), foldBitcastExtElt(), foldICmpWithHighBitMask(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), generateUnsignedDivisionCode(), llvm::VNCoercion::getLoadValueForLoad(), getMul64(), getShiftedValue(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), performMaskedAtomicOp(), ReduceSwitchRange(), simplifyX86immShift(), simplifyX86varShift(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SwitchToLookupTable(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitXor().
CreateMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateMul (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1152 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), llvm::MCBinaryExpr::Mul, and Name.
Referenced by buildMultiplyTree(), llvm::IRBuilder< T, Inserter >::CreateNSWMul(), llvm::IRBuilder< T, Inserter >::CreateNUWMul(), generatedUnsignedRemainderCode(), getMul64(), llvm::InnerLoopVectorizer::getStepVector(), llvm::UpgradeIntrinsicCall(), upgradePMULDQ(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitCallSite(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitSub().
CreateNAryOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNAryOp (unsigned Opc, ArrayRef< Value * > Ops, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Create either a UnaryOperator or BinaryOperator depending on Opc.
Correct number of operands must be passed accordingly.
Definition at line 1543 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateUnOp(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isUnaryOp(), llvm_unreachable, Name, and llvm::ArrayRef< T >::size().
Referenced by llvm::InnerLoopVectorizer::widenInstruction().
CreateNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNeg (Value * V, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1485 of file IRBuilder.h.
References llvm::BinaryOperator::CreateNeg(), llvm::IRBuilder< T, Inserter >::Insert(), Name, llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
Referenced by canonicalizeSaturatedSubtract(), llvm::IRBuilder< T, Inserter >::CreateNSWNeg(), llvm::IRBuilder< T, Inserter >::CreateNUWNeg(), llvm::InstCombiner::OptimizePointerDifference(), upgradeAbs(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateNot()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNot (Value * V, const Twine & Name = "") inline
Definition at line 1524 of file IRBuilder.h.
References llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by canonicalizeICmpBool(), createMaskInstrs(), llvm::FoldBranchToCommonDest(), LowerAtomicRMWInst(), LowerCTLZ(), llvm::IntrinsicLowering::LowerIntrinsicCall(), mergeConditionalStoreToAddress(), performAtomicOp(), SimplifyCondBranchToCondBranch(), sinkNotIntoXor(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), visitMaskedMerge(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateNSWAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNSWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1127 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAdd(), and Name.
Referenced by llvm::NoFolder::CreateNSWAdd(), rewriteGEPAsOffset(), and llvm::InstCombiner::visitFAdd().
CreateNSWMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNSWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1161 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateMul(), and Name.
Referenced by llvm::NoFolder::CreateNSWMul().
CreateNSWNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNSWNeg (Value * V, const Twine & Name = "") inline
Definition at line 1495 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateNeg(), and Name.
CreateNSWSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNSWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1144 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateSub(), and Name.
Referenced by llvm::BinaryOperator::CreateNSWNeg(), and llvm::NoFolder::CreateNSWSub().
CreateNUWAdd()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNUWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1131 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateAdd(), and Name.
Referenced by llvm::NoFolder::CreateNUWAdd(), and foldNoWrapAdd().
CreateNUWMul()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNUWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1165 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateMul(), and Name.
Referenced by llvm::NoFolder::CreateNUWMul().
CreateNUWNeg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNUWNeg (Value * V, const Twine & Name = "") inline
Definition at line 1499 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateNeg(), and Name.
CreateNUWSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateNUWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1148 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateSub(), and Name.
Referenced by llvm::BinaryOperator::CreateNUWNeg(), and llvm::NoFolder::CreateNUWSub().
CreateOr() [1/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateOr (ArrayRef< Value * > Ops) inline
Definition at line 1312 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::ArrayRef< T >::empty(), and llvm::ArrayRef< T >::size().
CreateOr() [2/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1304 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateOr() [3/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1308 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateOr() [4/4]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateOr (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1294 of file IRBuilder.h.
References llvm::TargetFolder::CreateOr(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), buildPartialUnswitchConditionalBranch(), checkForNegativeOperand(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::SCEVExpander::expandUnionPredicate(), llvm::SCEVExpander::expandWrapPredicate(), foldAndOrOfEqualityCmpsWithConstants(), foldLogOpOfMaskedICmps(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), getBoundsCheckCond(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTLZ(), mergeConditionalStoreToAddress(), performAtomicOp(), performMaskedAtomicOp(), ReduceSwitchRange(), SimplifyCondBranchToCondBranch(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitXor().
CreatePHI()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> PHINode * llvm::IRBuilder< T, Inserter >::CreatePHI (Type * Ty, unsigned NumReservedValues, const Twine & Name = "") inline
Definition at line 2188 of file IRBuilder.h.
References llvm::PHINode::Create(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::InnerLoopVectorizer::createInductionVariable(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createRetPHINode(), despeculateCountZeros(), llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), generateUnsignedDivisionCode(), optimizeSQRT(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), speculatePHIs(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreatePointerBitCastOrAddrSpaceCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePointerBitCastOrAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 2006 of file IRBuilder.h.
References llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreatePointerCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1997 of file IRBuilder.h.
References llvm::CastInst::CreatePointerCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by rewriteGEPAsOffset(), llvm::UpgradeIntrinsicCall(), and UseTlsOffset().
CreatePreserveArrayAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex (Value * Base, unsigned Dimension, unsigned LastIndex) inline
Definition at line 2456 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::BB, llvm::IRBuilderBase::Context, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Intrinsic::getDeclaration(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::BasicBlock::getParent(), llvm::Value::getType(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
CreatePreserveStructAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex (Value * Base, unsigned Index, unsigned FieldIndex, MDNode * DbgInfo) inline
Definition at line 2501 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::BB, llvm::IRBuilderBase::Context, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Intrinsic::getDeclaration(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_preserve_access_index, and llvm::Instruction::setMetadata().
CreatePreserveUnionAccessIndex()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex (Value * Base, unsigned FieldIndex, MDNode * DbgInfo) inline
Definition at line 2483 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::BB, llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt32(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_preserve_access_index, and llvm::Instruction::setMetadata().
CreatePtrDiff()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePtrDiff (Value * LHS, Value * RHS, const Twine & Name = "") inline
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
This is intended to implement C-style pointer subtraction. As such, the pointers must be appropriately aligned for their element types and pointing into the same object.
Definition at line 2349 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::Context, llvm::IRBuilder< T, Inserter >::CreateExactSDiv(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilderBase::getInt64Ty(), llvm::object::ArchiveMemberHeader::getSizeOf(), llvm::Value::getType(), and Name.
CreatePtrToInt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreatePtrToInt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1941 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), Name, and llvm::PtrToIntOperator::PtrToInt.
Referenced by llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), createCast(), createMaskInstrs(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), instrumentOneFunc(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), SimplifyBranchOnICmpChain(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitPtrToInt().
CreateResume()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ResumeInst * llvm::IRBuilder< T, Inserter >::CreateResume (Value * Exn) inline
Definition at line 1019 of file IRBuilder.h.
References llvm::ResumeInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
CreateRet()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst * llvm::IRBuilder< T, Inserter >::CreateRet (Value * V) inline
Create a 'ret <val>' instruction.
Definition at line 865 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::ReturnInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by llvm::InlineFunction(), llvm::orc::makeStub(), SimplifyCondBranchToTwoReturns(), and SwitchToLookupTable().
CreateRetVoid()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> ReturnInst * llvm::IRBuilder< T, Inserter >::CreateRetVoid () inline
Create a 'ret void' instruction.
Definition at line 860 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::ReturnInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by llvm::InlineFunction(), llvm::orc::makeStub(), and SimplifyCondBranchToTwoReturns().
CreateSDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1183 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactSDiv(), llvm::TargetFolder::CreateSDiv(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateExactSDiv(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), and llvm::InstCombiner::visitSDiv().
CreateSelect()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSelect (Value * C, Value * True, Value * False, const Twine & Name = "", Instruction * MDFrom = nullptr) inline
Definition at line 2241 of file IRBuilder.h.
References C, llvm::SelectInst::Create(), llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), llvm::LLVMContext::MD_prof, llvm::LLVMContext::MD_unpredictable, and Name.
Referenced by ConvertTwoCaseSwitch(), createMinMax(), llvm::createMinMaxOp(), EmitX86ScalarSelect(), EmitX86Select(), llvm::VPBlendRecipe::execute(), FoldTwoEntryPHINode(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), HoistThenElseCodeToIf(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::lowerObjectSizeCall(), performAtomicOp(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), simplifyX86pack(), SpeculativelyExecuteBB(), updateCoroFrame(), upgradeAbs(), upgradeIntMinMax(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), llvm::InstCombiner::visitCallInst(), llvm::ObjectSizeOffsetEvaluator::visitSelectInst(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateSExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1882 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), Name, and llvm::CCValAssign::SExt.
Referenced by llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldNoWrapAdd(), llvm::UpgradeIntrinsicCall(), UpgradeMaskToInt(), upgradeX86vpcom(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), and llvm::InstCombiner::visitCallInst().
CreateSExtOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1970 of file IRBuilder.h.
References llvm::CastInst::CreateSExtOrBitCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
CreateSExtOrTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a SExt or Trunc from the integer value V to DestTy.
Return the value untouched if the type of V is already DestTy.
Definition at line 1903 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), and Name.
Referenced by rewriteGEPAsOffset(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreateShl() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, const APInt & RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1216 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateShl() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, uint64_t RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1222 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateShl() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateShl (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1207 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), Name, and llvm::MCBinaryExpr::Shl.
Referenced by canonicalizeLowbitMask(), createMaskInstrs(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), generateUnsignedDivisionCode(), getShiftedValue(), LowerBSWAP(), performMaskedAtomicOp(), ReduceSwitchRange(), simplifyValueKnownNonZero(), simplifyX86immShift(), simplifyX86varShift(), upgradePMULDQ(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitSExt(), and llvm::InstCombiner::visitShl().
CreateShuffleVector() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateShuffleVector (Value * V1, Value * V2, ArrayRef< uint32_t > IntMask, const Twine & Name = "") inline
Definition at line 2299 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IntervalMapImpl::NodeRef::get(), and Name.
CreateShuffleVector() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateShuffleVector (Value * V1, Value * V2, Value * Mask, const Twine & Name = "") inline
Definition at line 2290 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by ApplyX86MaskOn1BitsVec(), concatenateTwoVectors(), concatSubVector(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), foldSelectShuffle(), llvm::getShuffleReduction(), getX86MaskVec(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), narrowVectorSelect(), reorderSubVector(), llvm::InnerLoopVectorizer::reverseVector(), simplifyNeonTbl1(), simplifyX86extrq(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), llvm::UpgradeIntrinsicCall(), UpgradeX86ALIGNIntrinsics(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitShuffleVectorInst().
CreateSIToFP()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1928 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::UpgradeIntrinsicCall().
CreateSRem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSRem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1202 of file IRBuilder.h.
References llvm::TargetFolder::CreateSRem(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), and llvm::InstCombiner::visitSRem().
CreateStore()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> StoreInst * llvm::IRBuilder< T, Inserter >::CreateStore (Value * Val, Value * Ptr, bool isVolatile = false) inline
Definition at line 1605 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), and isVolatile().
Referenced by llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createResumeEntryBlock(), insertSpills(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), mergeConditionalStoreToAddress(), tryPromoteAllocaToVector(), and updateCoroFrame().
CreateStripInvariantGroup()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup (Value * Ptr) inline
Create a strip.invariant.group intrinsic call.
If Ptr type is different from pointer to i8, it's casted to pointer to i8 in the same address space before call and casted back to Ptr type after call.
Definition at line 2391 of file IRBuilder.h.
References assert(), llvm::IRBuilderBase::BB, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::Function::getReturnType(), and llvm::Value::getType().
Referenced by simplifyInvariantGroupIntrinsic().
CreateStructGEP() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateStructGEP (Type * Ty, Value * Ptr, unsigned Idx, const Twine & Name = "") inline
Definition at line 1850 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), Idx, and Name.
CreateStructGEP() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateStructGEP (Value * Ptr, unsigned Idx, const Twine & Name = "") inline
Definition at line 1855 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), Idx, and Name.
CreateSub()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateSub (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 1135 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), Name, and llvm::AtomicRMWInst::Sub.
Referenced by checkForNegativeOperand(), CloneLoopBlocks(), llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), llvm::IRBuilder< T, Inserter >::CreateNSWSub(), llvm::IRBuilder< T, Inserter >::CreateNUWSub(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), llvm::VPlan::execute(), generatedUnsignedRemainderCode(), llvm::SCEVExpander::generateOverflowCheck(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), getBoundsCheckCond(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), LowerAtomicRMWInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::lowerObjectSizeCall(), llvm::InstCombiner::OptimizePointerDifference(), performAtomicOp(), ReduceSwitchRange(), simplifyValueKnownNonZero(), SwitchToLookupTable(), llvm::UnrollRuntimeLoopRemainder(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitURem().
CreateSwitch()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> SwitchInst * llvm::IRBuilder< T, Inserter >::CreateSwitch (Value * V, BasicBlock * Dest, unsigned NumCases = 10, MDNode * BranchWeights = nullptr, MDNode * Unpredictable = nullptr) inline
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
Definition at line 913 of file IRBuilder.h.
References llvm::SwitchInst::Create(), and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by createResumeEntryBlock(), and SimplifyBranchOnICmpChain().
CreateTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1874 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateExtractInteger(), createMaskInstrs(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), evaluateGEPOffsetExpression(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldBitcastExtElt(), llvm::VNCoercion::getLoadValueForLoad(), getMul64(), performMaskedAtomicOp(), processUGT_ADDCST_ADD(), shrinkSplatShuffle(), simplifyX86pack(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SwitchToLookupTable(), truncateIVUse(), llvm::UpgradeIntrinsicCall(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitZExt(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
CreateTruncOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateTruncOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1979 of file IRBuilder.h.
References llvm::CastInst::CreateTruncOrBitCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::ARMTargetLowering::emitLoadLinked(), and llvm::SCEVExpander::replaceCongruentIVs().
CreateUDiv()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateUDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 1169 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactUDiv(), llvm::TargetFolder::CreateUDiv(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateExactUDiv(), llvm::createMemCpyLoopUnknownSize(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), generatedUnsignedRemainderCode(), and generateSignedDivisionCode().
CreateUIToFP()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateUIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1924 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), and Name.
Referenced by llvm::UpgradeIntrinsicCall().
CreateUnOp()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateUnOp (Instruction::UnaryOps Opc, Value * V, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 1530 of file IRBuilder.h.
References llvm::UnaryOperator::Create(), llvm::IRBuilderBase::FMF, llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateNAryOp().
CreateUnreachable()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> UnreachableInst * llvm::IRBuilder< T, Inserter >::CreateUnreachable () inline
Definition at line 1050 of file IRBuilder.h.
References llvm::IRBuilderBase::Context, and llvm::IRBuilder< T, Inserter >::Insert().
Referenced by createResumeEntryBlock(), llvm::VPlan::execute(), llvm::VPBasicBlock::execute(), removeUndefIntroducingPredecessor(), and TryToMergeLandingPad().
CreateURem()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateURem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1197 of file IRBuilder.h.
References llvm::TargetFolder::CreateURem(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::createMemCpyLoopUnknownSize(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), generateSignedRemainderCode(), and llvm::InnerLoopVectorizer::getOrCreateVectorTripCount().
CreateVAArg()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> VAArgInst * llvm::IRBuilder< T, Inserter >::CreateVAArg (Value * List, Type * Ty, const Twine & Name = "") inline
Definition at line 2259 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::Insert(), List, and Name.
CreateVectorSplat()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateVectorSplat (unsigned NumElts, Value * V, const Twine & Name = "") inline
Return a vector value that contains.
V broadcasted to NumElts elements.
Definition at line 2418 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), llvm::Value::getType(), and Name.
Referenced by llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::InnerLoopVectorizer::getStepVector(), simplifyX86immShift(), llvm::UpgradeIntrinsicCall(), upgradeX86ConcatShift(), upgradeX86Rotate(), and llvm::InnerLoopVectorizer::widenInstruction().
CreateXor() [1/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 1325 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateXor() [2/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 1329 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), and Name.
CreateXor() [3/3]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateXor (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1320 of file IRBuilder.h.
References llvm::TargetFolder::CreateXor(), llvm::IRBuilder< T, Inserter >::Insert(), Name, and llvm::AtomicRMWInst::Xor.
Referenced by canonicalizeICmpBool(), createMaskInstrs(), llvm::IRBuilder< T, Inserter >::CreateXor(), foldAndToXor(), foldOrToXor(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldXorToXor(), generateSignedDivisionCode(), generateSignedRemainderCode(), LowerAtomicRMWInst(), performAtomicOp(), and llvm::UpgradeIntrinsicCall().
CreateZExt()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateZExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1878 of file IRBuilder.h.
References llvm::IRBuilder< T, Inserter >::CreateCast(), Name, and llvm::CCValAssign::ZExt.
Referenced by llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InnerLoopVectorizer::fixReduction(), foldAnyOrAllBitsSet(), foldNoWrapAdd(), foldUDivShl(), getMul64(), performMaskedAtomicOp(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), simplifyX86addcarry(), llvm::UpgradeIntrinsicCall(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitCallInst(), llvm::ObjectSizeOffsetEvaluator::visitCallSite(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitZExt().
CreateZExtOrBitCast()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateZExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1961 of file IRBuilder.h.
References llvm::CastInst::CreateZExtOrBitCast(), llvm::Value::getType(), llvm::IRBuilder< T, Inserter >::Insert(), and Name.
Referenced by llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), and splitMergedValStore().
CreateZExtOrTrunc()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Value * llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a ZExt or Trunc from the integer value V to DestTy.
Return the value untouched if the type of V is already DestTy.
Definition at line 1888 of file IRBuilder.h.
References assert(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), and Name.
Referenced by foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::SCEVExpander::generateOverflowCheck(), simplifyX86movmsk(), SwitchToLookupTable(), and llvm::InstCombiner::visitIntToPtr().
getFolder()
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> const T & llvm::IRBuilder< T, Inserter >::getFolder () inline
Get the constant folder being used.
Definition at line 826 of file IRBuilder.h.
Insert() [1/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> Constant * llvm::IRBuilder< T, Inserter >::Insert (Constant * C, const Twine & = "") const inline
No-op overload to handle constants.
Definition at line 837 of file IRBuilder.h.
References C.
Insert() [2/2]
template<typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter> template<typename InstTy > InstTy * llvm::IRBuilder< T, Inserter >::Insert (InstTy * I, const Twine & Name = "") const inline
Insert and return the specified instruction.
Definition at line 830 of file IRBuilder.h.
References llvm::IRBuilderBase::BB, I, llvm::IRBuilderDefaultInserter::InsertHelper(), llvm::IRBuilderBase::InsertPt, Name, and llvm::IRBuilderBase::SetInstDebugLocation().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAggregateRet(), llvm::IRBuilder< T, Inserter >::CreateAlloca(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateAtomicCmpXchg(), llvm::IRBuilder< T, Inserter >::CreateAtomicRMW(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateBr(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateCallBr(), llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::IRBuilder< T, Inserter >::CreateCatchPad(), llvm::IRBuilder< T, Inserter >::CreateCatchRet(), llvm::IRBuilder< T, Inserter >::CreateCatchSwitch(), llvm::IRBuilder< T, Inserter >::CreateCleanupPad(), llvm::IRBuilder< T, Inserter >::CreateCleanupRet(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAddFMF(), llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDivFMF(), llvm::IRBuilder< T, Inserter >::CreateFence(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), llvm::IRBuilder< T, Inserter >::CreateFNeg(), llvm::IRBuilder< T, Inserter >::CreateFNegFMF(), llvm::IRBuilder< T, Inserter >::CreateFPCast(), llvm::IRBuilder< T, Inserter >::CreateFRem(), llvm::IRBuilder< T, Inserter >::CreateFRemFMF(), llvm::IRBuilder< T, Inserter >::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateFSubFMF(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateIndirectBr(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateInvoke(), llvm::IRBuilder< T, Inserter >::CreateLandingPad(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreatePointerBitCastOrAddrSpaceCast(), llvm::IRBuilder< T, Inserter >::CreatePointerCast(), llvm::IRBuilder< T, Inserter >::CreateResume(), llvm::IRBuilder< T, Inserter >::CreateRet(), llvm::IRBuilder< T, Inserter >::CreateRetVoid(), llvm::IRBuilder< T, Inserter >::CreateSDiv(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExtOrBitCast(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilder< T, Inserter >::CreateSRem(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateSwitch(), llvm::IRBuilder< T, Inserter >::CreateTruncOrBitCast(), llvm::IRBuilder< T, Inserter >::CreateUDiv(), llvm::IRBuilder< T, Inserter >::CreateUnOp(), llvm::IRBuilder< T, Inserter >::CreateUnreachable(), llvm::IRBuilder< T, Inserter >::CreateURem(), llvm::IRBuilder< T, Inserter >::CreateVAArg(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateZExtOrBitCast(), optimizeSQRT(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InnerLoopVectorizer::widenInstruction().
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h