LLVM: llvm::MMIAddrLabelMap Class Reference
llvm::MMIAddrLabelMap Class Reference
Public Member Functions
MMIAddrLabelMap (MCContext &context)
~MMIAddrLabelMap ()
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (BasicBlock *BB)
void takeDeletedSymbolsForFunction (Function *F, std::vector< MCSymbol * > &Result)
If we have any deleted symbols for F, return them.
void UpdateForDeletedBlock (BasicBlock *BB)
void UpdateForRAUWBlock (BasicBlock *Old, BasicBlock *New)
Detailed Description
Definition at line 66 of file MachineModuleInfo.cpp.
Constructor & Destructor Documentation
MMIAddrLabelMap()
llvm::MMIAddrLabelMap::MMIAddrLabelMap (MCContext & context) inline
Definition at line 89 of file MachineModuleInfo.cpp.
References Context.
~MMIAddrLabelMap()
llvm::MMIAddrLabelMap::~MMIAddrLabelMap () inline
Definition at line 91 of file MachineModuleInfo.cpp.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Member Function Documentation
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > MMIAddrLabelMap::getAddrLabelSymbolToEmit (BasicBlock * BB)
Definition at line 107 of file MachineModuleInfo.cpp.
References assert(), llvm::MCContext::createTempSymbol(), llvm::BasicBlock::getParent(), and llvm::BasicBlock::hasAddressTaken().
Referenced by llvm::MachineModuleInfo::getAddrLabelSymbolToEmit().
takeDeletedSymbolsForFunction()
void MMIAddrLabelMap::takeDeletedSymbolsForFunction (Function * F, std::vector< MCSymbol * > & Result)
If we have any deleted symbols for F, return them.
Definition at line 129 of file MachineModuleInfo.cpp.
References F, I, and std::swap().
UpdateForDeletedBlock()
void MMIAddrLabelMap::UpdateForDeletedBlock (BasicBlock * BB)
Definition at line 142 of file MachineModuleInfo.cpp.
References assert(), llvm::BasicBlock::getParent(), and llvm::MCSymbol::isDefined().
Referenced by llvm::MMIAddrLabelMapCallbackPtr::deleted().
UpdateForRAUWBlock()
void MMIAddrLabelMap::UpdateForRAUWBlock (BasicBlock * Old, BasicBlock * New)
Definition at line 166 of file MachineModuleInfo.cpp.
References assert().
Referenced by llvm::MMIAddrLabelMapCallbackPtr::allUsesReplacedWith().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineModuleInfo.cpp