LLVM: llvm::orc::LocalCXXRuntimeOverrides Class Reference
llvm::orc::LocalCXXRuntimeOverrides Class Reference
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Member Functions
Error enable (JITDylib &JD, MangleAndInterner &Mangler)
Public Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
void runDestructors ()
Run any destructors recorded by the overriden __cxa_atexit function (CXAAtExitOverride).
Additional Inherited Members
Protected Types inherited from llvm::orc::LocalCXXRuntimeOverridesBase
using DestructorPtr = void(*)(void *)
using CXXDestructorDataPair = std::pair< DestructorPtr, void * >
using CXXDestructorDataPairList = std::vector< CXXDestructorDataPair >
Protected Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
template<typename PtrTy >
JITTargetAddress toTargetAddress (PtrTy *P)
Static Protected Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
static int CXAAtExitOverride (DestructorPtr Destructor, void *Arg, void *DSOHandle)
Protected Attributes inherited from llvm::orc::LocalCXXRuntimeOverridesBase
CXXDestructorDataPairList DSOHandleOverride
Detailed Description
Definition at line 230 of file ExecutionUtils.h.
Member Function Documentation
enable()
Error llvm::orc::LocalCXXRuntimeOverrides::enable (JITDylib & JD, MangleAndInterner & Mangler)
Definition at line 163 of file ExecutionUtils.cpp.
References llvm::orc::absoluteSymbols(), llvm::orc::LocalCXXRuntimeOverridesBase::CXAAtExitOverride(), llvm::orc::JITDylib::define(), llvm::orc::LocalCXXRuntimeOverridesBase::DSOHandleOverride, llvm::JITSymbolFlags::Exported, and llvm::orc::LocalCXXRuntimeOverridesBase::toTargetAddress().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp