LLVM: llvm::LegacyJITSymbolResolver Class Reference
llvm::LegacyJITSymbolResolver Class Reference abstract
Legacy symbol resolution interface.
#include "llvm/ExecutionEngine/JITSymbol.h"
Public Member Functions
void lookup (const LookupSet &Symbols, OnResolvedFunction OnResolved) final
Performs lookup by, for each symbol, first calling findSymbolInLogicalDylib and if that fails calling findSymbol.
Expected< LookupSet > getResponsibilitySet (const LookupSet &Symbols) final
Performs flags lookup by calling findSymbolInLogicalDylib and returning the flags value for that symbol.
virtual JITSymbol findSymbolInLogicalDylib (const std::string &Name)=0
This method returns the address of the specified symbol if it exists within the logical dynamic library represented by this JITSymbolResolver.
virtual JITSymbol findSymbol (const std::string &Name)=0
This method returns the address of the specified function or variable.
Public Member Functions inherited from llvm::JITSymbolResolver
virtual ~JITSymbolResolver ()=default
virtual void lookup (const LookupSet &Symbols, OnResolvedFunction OnResolved)=0
Returns the fully resolved address and flags for each of the given symbols.
virtual Expected< LookupSet > getResponsibilitySet (const LookupSet &Symbols)=0
Returns the subset of the given symbols that should be materialized by the caller.
Additional Inherited Members
Public Types inherited from llvm::JITSymbolResolver
using LookupSet = std::set< StringRef >
using LookupResult = std::map< StringRef, JITEvaluatedSymbol >
using OnResolvedFunction = std::function< void(Expected< LookupResult >)>
Detailed Description
Legacy symbol resolution interface.
Definition at line 351 of file JITSymbol.h.
Member Function Documentation
findSymbol()
virtual JITSymbol llvm::LegacyJITSymbolResolver::findSymbol (const std::string & Name) pure virtual
This method returns the address of the specified function or variable.
It is used to resolve symbols during module linking.
If the returned symbol's address is equal to ~0ULL then RuntimeDyld will skip all relocations for that symbol, and the client will be responsible for handling them manually.
Implemented in llvm::orc::LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT >, llvm::orc::NullLegacyResolver, llvm::RTDyldMemoryManager, and llvm::LinkingSymbolResolver.
Referenced by lookup().
findSymbolInLogicalDylib()
virtual JITSymbol llvm::LegacyJITSymbolResolver::findSymbolInLogicalDylib (const std::string & Name) pure virtual
This method returns the address of the specified symbol if it exists within the logical dynamic library represented by this JITSymbolResolver.
Unlike findSymbol, queries through this interface should return addresses for hidden symbols.
This is of particular importance for the Orc JIT APIs, which support lazy compilation by breaking up modules: Each of those broken out modules must be able to resolve hidden symbols provided by the others. Clients writing memory managers for MCJIT can usually ignore this method.
This method will be queried by RuntimeDyld when checking for previous definitions of common symbols.
Implemented in llvm::orc::LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT >, llvm::orc::NullLegacyResolver, llvm::RTDyldMemoryManager, and llvm::LinkingSymbolResolver.
Referenced by getResponsibilitySet(), and lookup().
getResponsibilitySet()
Expected< JITSymbolResolver::LookupSet > LegacyJITSymbolResolver::getResponsibilitySet (const LookupSet & Symbols) final virtual
Performs flags lookup by calling findSymbolInLogicalDylib and returning the flags value for that symbol.
Implements llvm::JITSymbolResolver.
Definition at line 111 of file JITSymbol.cpp.
References findSymbolInLogicalDylib().
lookup()
void LegacyJITSymbolResolver::lookup (const LookupSet & Symbols, OnResolvedFunction OnResolved) final virtual
Performs lookup by, for each symbol, first calling findSymbolInLogicalDylib and if that fails calling findSymbol.
Implements llvm::JITSymbolResolver.
Definition at line 70 of file JITSymbol.cpp.
References findSymbol(), findSymbolInLogicalDylib(), and llvm::inconvertibleErrorCode().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITSymbol.h
lib/ExecutionEngine/RuntimeDyld/JITSymbol.cpp
lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp