LLVM: llvm::FileCheckErrorDiagnostic Class Reference
llvm::FileCheckErrorDiagnostic Class Reference
Class to represent an error holding a diagnostic with location information used when printing it.
#include "llvm/Support/FileCheck.h"
Public Member Functions
FileCheckErrorDiagnostic (SMDiagnostic &&Diag)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print diagnostic associated with this error when printing the error.
Public Member Functions inherited from llvm::ErrorInfo< FileCheckErrorDiagnostic >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Member Functions
static Error get (const SourceMgr &SM, SMLoc Loc, const Twine &ErrMsg)
static Error get (const SourceMgr &SM, StringRef Buffer, const Twine &ErrMsg)
Static Public Member Functions inherited from llvm::ErrorInfo< FileCheckErrorDiagnostic >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Static Public Attributes
static char ID = 0
Detailed Description
Class to represent an error holding a diagnostic with location information used when printing it.
Definition at line 376 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheckErrorDiagnostic()
llvm::FileCheckErrorDiagnostic::FileCheckErrorDiagnostic (SMDiagnostic && Diag) inline
Definition at line 383 of file FileCheck.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::FileCheckErrorDiagnostic::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 385 of file FileCheck.h.
References llvm::inconvertibleErrorCode().
get() [1/2]
static Error llvm::FileCheckErrorDiagnostic::get (const SourceMgr & SM, SMLoc Loc, const Twine & ErrMsg) inline static
Definition at line 392 of file FileCheck.h.
References llvm::SourceMgr::DK_Error, and llvm::SourceMgr::GetMessage().
Referenced by get().
get() [2/2]
static Error llvm::FileCheckErrorDiagnostic::get (const SourceMgr & SM, StringRef Buffer, const Twine & ErrMsg) inline static
Definition at line 397 of file FileCheck.h.
References llvm::StringRef::data(), get(), and llvm::SMLoc::getFromPointer().
log()
void llvm::FileCheckErrorDiagnostic::log (raw_ostream & OS) const inline override virtual
Print diagnostic associated with this error when printing the error.
Implements llvm::ErrorInfoBase.
Definition at line 390 of file FileCheck.h.
References llvm::SMDiagnostic::print().
Member Data Documentation
ID
char FileCheckErrorDiagnostic::ID = 0 static
Definition at line 381 of file FileCheck.h.
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp