LLVM: llvm::mca::Context Class Reference
llvm::mca::Context Class Reference
#include "llvm/MCA/Context.h"
Public Member Functions
Context (const MCRegisterInfo &R, const MCSubtargetInfo &S)
Context (const Context &C)=delete
Context & operator= (const Context &C)=delete
void addHardwareUnit (std::unique_ptr< HardwareUnit > H)
std::unique_ptr< Pipeline > createDefaultPipeline (const PipelineOptions &Opts, InstrBuilder &IB, SourceMgr &SrcMgr)
Construct a basic pipeline for simulating an out-of-order pipeline.
Detailed Description
Definition at line 51 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
llvm::mca::Context::Context (const MCRegisterInfo & R, const MCSubtargetInfo & S) inline
Definition at line 57 of file Context.h.
References MRI.
Context() [2/2]
llvm::mca::Context::Context (const Context & C) delete
Member Function Documentation
addHardwareUnit()
void llvm::mca::Context::addHardwareUnit (std::unique_ptr< HardwareUnit > H) inline
Definition at line 61 of file Context.h.
References H, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by createDefaultPipeline().
createDefaultPipeline()
std::unique_ptr< Pipeline > llvm::mca::Context::createDefaultPipeline (const PipelineOptions & Opts, InstrBuilder & IB, SourceMgr & SrcMgr)
Construct a basic pipeline for simulating an out-of-order pipeline.
This pipeline consists of Fetch, Dispatch, Execute, and Retire stages.
Definition at line 31 of file Context.cpp.
References addHardwareUnit(), llvm::mca::PipelineOptions::AssumeNoAlias, llvm::mca::PipelineOptions::DecodersThroughput, llvm::mca::PipelineOptions::DispatchWidth, llvm::mca::PipelineOptions::EnableBottleneckAnalysis, Execute(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::PipelineOptions::LoadQueueSize, llvm::mca::PipelineOptions::MicroOpQueueSize, llvm::mca::PipelineOptions::RegisterFileSize, llvm::SrcMgr, and llvm::mca::PipelineOptions::StoreQueueSize.
operator=()
Context & llvm::mca::Context::operator= (const Context & C) delete
The documentation for this class was generated from the following files:
include/llvm/MCA/Context.h
lib/MCA/Context.cpp