LLVM: llvm::MetadataLoader::MetadataLoaderImpl Class Reference
llvm::MetadataLoader::MetadataLoaderImpl Class Reference
Public Member Functions
MetadataLoaderImpl (BitstreamCursor &Stream, Module &TheModule, BitcodeReaderValueList &ValueList, std::function< Type *(unsigned)> getTypeByID, bool IsImporting)
Error parseMetadata (bool ModuleLevel)
Parse a METADATA_BLOCK.
bool hasFwdRefs () const
Metadata * getMetadataFwdRefOrLoad (unsigned ID)
DISubprogram * lookupSubprogramForFunction (Function *F)
bool hasSeenOldLoopTags ()
Error parseMetadataAttachment (Function &F, const SmallVectorImpl< Instruction * > &InstructionList)
Parse metadata attachments.
Error parseMetadataKinds ()
Parse the metadata kinds out of the METADATA_KIND_BLOCK.
void setStripTBAA (bool Value)
bool isStrippingTBAA ()
unsigned size () const
void shrinkTo (unsigned N)
void upgradeDebugIntrinsics (Function &F)
Detailed Description
Definition at line 421 of file MetadataLoader.cpp.
Constructor & Destructor Documentation
MetadataLoaderImpl()
llvm::MetadataLoader::MetadataLoaderImpl::MetadataLoaderImpl (BitstreamCursor & Stream, Module & TheModule, BitcodeReaderValueList & ValueList, std::function< Type *(unsigned)> getTypeByID, bool IsImporting) inline
Definition at line 635 of file MetadataLoader.cpp.
References Context.
Member Function Documentation
getMetadataFwdRefOrLoad()
Metadata * llvm::MetadataLoader::MetadataLoaderImpl::getMetadataFwdRefOrLoad (unsigned ID) inline
Definition at line 648 of file MetadataLoader.cpp.
hasFwdRefs()
bool llvm::MetadataLoader::MetadataLoaderImpl::hasFwdRefs () const inline
Definition at line 646 of file MetadataLoader.cpp.
hasSeenOldLoopTags()
bool llvm::MetadataLoader::MetadataLoaderImpl::hasSeenOldLoopTags () inline
Definition at line 668 of file MetadataLoader.cpp.
isStrippingTBAA()
bool llvm::MetadataLoader::MetadataLoaderImpl::isStrippingTBAA () inline
Definition at line 676 of file MetadataLoader.cpp.
lookupSubprogramForFunction()
DISubprogram * llvm::MetadataLoader::MetadataLoaderImpl::lookupSubprogramForFunction (Function * F) inline
Definition at line 664 of file MetadataLoader.cpp.
References F, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
parseMetadata()
Error llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata (bool ModuleLevel)
Parse a METADATA_BLOCK.
If ModuleLevel is true then we are parsing module level metadata.
Definition at line 892 of file MetadataLoader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), llvm::consumeError(), DisableLazyLoading, llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::BitstreamCursor::GetCurrentBitNo(), llvm::bitc::METADATA_BLOCK_ID, llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::BitstreamCursor::ReadBlockEnd(), llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamEntry::SubBlock, llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata().
parseMetadataAttachment()
Error llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment (Function & F, const SmallVectorImpl< Instruction * > & InstructionList)
Parse metadata attachments.
Definition at line 1977 of file MetadataLoader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Expected< T >::get(), I, Idx, llvm::MDNode::isTemporary(), llvm::LLVMContext::MD_loop, llvm::LLVMContext::MD_tbaa, llvm::bitc::METADATA_ATTACHMENT, llvm::bitc::METADATA_ATTACHMENT_ID, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::Instruction::setMetadata(), llvm::BitstreamEntry::SubBlock, llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::upgradeInstructionLoopAttachment(), and llvm::UpgradeTBAANode().
parseMetadataKinds()
Error llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds ()
Parse the metadata kinds out of the METADATA_KIND_BLOCK.
Definition at line 2082 of file MetadataLoader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::bitc::METADATA_KIND, llvm::bitc::METADATA_KIND_BLOCK_ID, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, llvm::Error::success(), and llvm::Expected< T >::takeError().
setStripTBAA()
void llvm::MetadataLoader::MetadataLoaderImpl::setStripTBAA (bool Value) inline
Definition at line 675 of file MetadataLoader.cpp.
shrinkTo()
void llvm::MetadataLoader::MetadataLoaderImpl::shrinkTo (unsigned N) inline
Definition at line 679 of file MetadataLoader.cpp.
References N.
size()
unsigned llvm::MetadataLoader::MetadataLoaderImpl::size () const inline
Definition at line 678 of file MetadataLoader.cpp.
upgradeDebugIntrinsics()
void llvm::MetadataLoader::MetadataLoaderImpl::upgradeDebugIntrinsics (Function & F) inline
Definition at line 680 of file MetadataLoader.cpp.
References F.
The documentation for this class was generated from the following file:
lib/Bitcode/Reader/MetadataLoader.cpp