LLVM: llvm::optional_detail::OptionalStorage< T, true > Class Template Reference
llvm::optional_detail::OptionalStorage< T, true > Class Template Reference
#include "llvm/ADT/Optional.h"
Public Member Functions
~OptionalStorage ()=default
OptionalStorage () noexcept
OptionalStorage (OptionalStorage const &other)=default
OptionalStorage (OptionalStorage &&other)=default
OptionalStorage & operator= (OptionalStorage const &other)=default
OptionalStorage & operator= (OptionalStorage &&other)=default
template<class... Args>
OptionalStorage (in_place_t, Args &&... args)
void reset () noexcept
bool hasValue () const noexcept
T & getValue () LLVM_LVALUE_FUNCTION noexcept
T const & getValue () const LLVM_LVALUE_FUNCTION noexcept
template<class... Args>
void emplace (Args &&... args)
OptionalStorage & operator= (T const &y)
OptionalStorage & operator= (T &&y)
Detailed Description
template<typename T>
class llvm::optional_detail::OptionalStorage< T, true >
Definition at line 141 of file Optional.h.
Constructor & Destructor Documentation
~OptionalStorage()
template<typename T > llvm::optional_detail::OptionalStorage< T, true >::~OptionalStorage () default
OptionalStorage() [1/4]
template<typename T > llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage () inline noexcept
Definition at line 151 of file Optional.h.
OptionalStorage() [2/4]
template<typename T > llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (OptionalStorage< T, true > const & other) default
OptionalStorage() [3/4]
template<typename T > llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (OptionalStorage< T, true > && other) default
OptionalStorage() [4/4]
template<typename T > template<class... Args> llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (in_place_t , Args &&... args) inline explicit
Definition at line 160 of file Optional.h.
Member Function Documentation
emplace()
template<typename T > template<class... Args> void llvm::optional_detail::OptionalStorage< T, true >::emplace (Args &&... args) inline
Definition at line 187 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::reset(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
getValue() [1/2]
template<typename T > T const & llvm::optional_detail::OptionalStorage< T, true >::getValue () const inline noexcept
Definition at line 176 of file Optional.h.
References assert(), and llvm::optional_detail::OptionalStorage< T, bool >::value.
getValue() [2/2]
template<typename T > T & llvm::optional_detail::OptionalStorage< T, true >::getValue () inline noexcept
Definition at line 172 of file Optional.h.
References assert(), and llvm::optional_detail::OptionalStorage< T, bool >::value.
hasValue()
template<typename T > bool llvm::optional_detail::OptionalStorage< T, true >::hasValue () const inline noexcept
Definition at line 170 of file Optional.h.
operator=() [1/4]
template<typename T > OptionalStorage & llvm::optional_detail::OptionalStorage< T, true >::operator= (OptionalStorage< T, true > && other) default
operator=() [2/4]
template<typename T > OptionalStorage & llvm::optional_detail::OptionalStorage< T, true >::operator= (OptionalStorage< T, true > const & other) default
operator=() [3/4]
template<typename T > OptionalStorage & llvm::optional_detail::OptionalStorage< T, true >::operator= (T && y) inline
Definition at line 202 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
operator=() [4/4]
template<typename T > OptionalStorage & llvm::optional_detail::OptionalStorage< T, true >::operator= (T const & y) inline
Definition at line 193 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
reset()
template<typename T > void llvm::optional_detail::OptionalStorage< T, true >::reset () inline noexcept
Definition at line 163 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::value.
Member Data Documentation
empty
template<typename T > char llvm::optional_detail::OptionalStorage< T, true >::empty
Definition at line 143 of file Optional.h.
value
template<typename T > T llvm::optional_detail::OptionalStorage< T, true >::value
Definition at line 144 of file Optional.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/Optional.h