LLVM: llvm::NearMissInfo Class Reference
llvm::NearMissInfo Class Reference
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
Public Types
enum NearMissKind {
NoNearMiss , NearMissOperand , NearMissFeature , NearMissPredicate ,
NearMissTooFewOperands
}
Public Member Functions
operator bool () const
NearMissKind getKind () const
const FeatureBitset & getFeatures () const
unsigned getPredicateError () const
unsigned getOperandClass () const
unsigned getOpcode () const
unsigned getOperandError () const
unsigned getOperandIndex () const
Static Public Member Functions
static NearMissInfo getSuccess ()
static NearMissInfo getMissedFeature (const FeatureBitset &MissingFeatures)
static NearMissInfo getMissedPredicate (unsigned FailureCode)
static NearMissInfo getMissedOperand (unsigned OperandError, unsigned OperandClass, unsigned Opcode, unsigned OperandIndex)
static NearMissInfo getTooFewOperands (unsigned OperandClass, unsigned Opcode)
Detailed Description
Definition at line 189 of file MCTargetAsmParser.h.
Member Enumeration Documentation
NearMissKind
enum llvm::NearMissInfo::NearMissKind
Enumerator
NoNearMiss
NearMissOperand
NearMissFeature
NearMissPredicate
NearMissTooFewOperands
Definition at line 191 of file MCTargetAsmParser.h.
Member Function Documentation
getFeatures()
const FeatureBitset & llvm::NearMissInfo::getFeatures () const inline
Definition at line 258 of file MCTargetAsmParser.h.
References assert(), Features, and NearMissFeature.
getKind()
NearMissKind llvm::NearMissInfo::getKind () const inline
Definition at line 254 of file MCTargetAsmParser.h.
getMissedFeature()
static NearMissInfo llvm::NearMissInfo::getMissedFeature (const FeatureBitset & MissingFeatures) inline static
Definition at line 206 of file MCTargetAsmParser.h.
References NearMissFeature.
getMissedOperand()
static NearMissInfo llvm::NearMissInfo::getMissedOperand (unsigned OperandError, unsigned OperandClass, unsigned Opcode, unsigned OperandIndex) inline static
Definition at line 228 of file MCTargetAsmParser.h.
References NearMissOperand.
getMissedPredicate()
static NearMissInfo llvm::NearMissInfo::getMissedPredicate (unsigned FailureCode) inline static
Definition at line 216 of file MCTargetAsmParser.h.
References NearMissPredicate.
getOpcode()
unsigned llvm::NearMissInfo::getOpcode () const inline
Definition at line 274 of file MCTargetAsmParser.h.
References assert(), MissedOperand, NearMissOperand, and NearMissTooFewOperands.
getOperandClass()
unsigned llvm::NearMissInfo::getOperandClass () const inline
Definition at line 269 of file MCTargetAsmParser.h.
References assert(), MissedOperand, NearMissOperand, and NearMissTooFewOperands.
getOperandError()
unsigned llvm::NearMissInfo::getOperandError () const inline
Definition at line 279 of file MCTargetAsmParser.h.
References assert(), MissedOperand, and NearMissOperand.
getOperandIndex()
unsigned llvm::NearMissInfo::getOperandIndex () const inline
Definition at line 285 of file MCTargetAsmParser.h.
References assert(), MissedOperand, and NearMissOperand.
getPredicateError()
unsigned llvm::NearMissInfo::getPredicateError () const inline
Definition at line 264 of file MCTargetAsmParser.h.
References assert(), NearMissPredicate, and PredicateError.
getSuccess()
static NearMissInfo llvm::NearMissInfo::getSuccess () inline static
Definition at line 201 of file MCTargetAsmParser.h.
getTooFewOperands()
static NearMissInfo llvm::NearMissInfo::getTooFewOperands (unsigned OperandClass, unsigned Opcode) inline static
Definition at line 243 of file MCTargetAsmParser.h.
References NearMissTooFewOperands.
operator bool()
llvm::NearMissInfo::operator bool () const inline
Definition at line 252 of file MCTargetAsmParser.h.
References NoNearMiss.
Member Data Documentation
Features
FeatureBitset llvm::NearMissInfo::Features
Definition at line 308 of file MCTargetAsmParser.h.
Referenced by getFeatures().
MissedOperand
MissedOpInfo llvm::NearMissInfo::MissedOperand
Definition at line 310 of file MCTargetAsmParser.h.
Referenced by getOpcode(), getOperandClass(), getOperandError(), and getOperandIndex().
PredicateError
unsigned llvm::NearMissInfo::PredicateError
Definition at line 309 of file MCTargetAsmParser.h.
Referenced by getPredicateError().
TooFewOperands
TooFewOperandsInfo llvm::NearMissInfo::TooFewOperands
Definition at line 311 of file MCTargetAsmParser.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCParser/MCTargetAsmParser.h