LLVM: llvm::orc::ObjectLinkingLayer Class Reference
llvm::orc::ObjectLinkingLayer Class Reference
An ObjectLayer implementation built on JITLink.
#include "llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h"
Classes
class Plugin
Plugin instances can be added to the ObjectLinkingLayer to receive callbacks when code is loaded or emitted, and when JITLink is being configured.
Public Member Functions
ObjectLinkingLayer (ExecutionSession &ES, jitlink::JITLinkMemoryManager &MemMgr)
Construct an ObjectLinkingLayer with the given NotifyLoaded, and NotifyEmitted functors.
~ObjectLinkingLayer ()
Destruct an ObjectLinkingLayer.
ObjectLinkingLayer & addPlugin (std::unique_ptr< Plugin > P)
Add a pass-config modifier.
void emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override
Emit the object.
ObjectLinkingLayer & setOverrideObjectFlagsWithResponsibilityFlags (bool OverrideObjectFlags)
Instructs this ObjectLinkingLayer instance to override the symbol flags found in the AtomGraph with the flags supplied by the MaterializationResponsibility instance.
ObjectLinkingLayer & setAutoClaimResponsibilityForObjectSymbols (bool AutoClaimObjectSymbols)
If set, this ObjectLinkingLayer instance will claim responsibility for any symbols provided by a given object file that were not already in the MaterializationResponsibility instance.
Public Member Functions inherited from llvm::orc::ObjectLayer
ObjectLayer (ExecutionSession &ES)
virtual ~ObjectLayer ()
ExecutionSession & getExecutionSession ()
Returns the execution session for this layer.
virtual Error add (JITDylib &JD, std::unique_ptr< MemoryBuffer > O, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
virtual void emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O)=0
Emit should materialize the given IR.
Friends
class ObjectLinkingLayerJITLinkContext
Detailed Description
An ObjectLayer implementation built on JITLink.
Clients can use this class to add relocatable object files to an ExecutionSession, and it typically serves as the base layer (underneath a compiling layer like IRCompileLayer) for the rest of the JIT.
Definition at line 53 of file ObjectLinkingLayer.h.
Constructor & Destructor Documentation
ObjectLinkingLayer()
llvm::orc::ObjectLinkingLayer::ObjectLinkingLayer (ExecutionSession & ES, jitlink::JITLinkMemoryManager & MemMgr)
Construct an ObjectLinkingLayer with the given NotifyLoaded, and NotifyEmitted functors.
Definition at line 321 of file ObjectLinkingLayer.cpp.
~ObjectLinkingLayer()
llvm::orc::ObjectLinkingLayer::~ObjectLinkingLayer ()
Destruct an ObjectLinkingLayer.
Definition at line 325 of file ObjectLinkingLayer.cpp.
References llvm::orc::ObjectLayer::getExecutionSession(), and llvm::orc::ExecutionSession::reportError().
Member Function Documentation
addPlugin()
ObjectLinkingLayer & llvm::orc::ObjectLinkingLayer::addPlugin (std::unique_ptr< Plugin > P) inline
Add a pass-config modifier.
Definition at line 85 of file ObjectLinkingLayer.h.
References llvm::Lock, and P.
emit()
void llvm::orc::ObjectLinkingLayer::emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) override virtual
Emit the object.
Implements llvm::orc::ObjectLayer.
Definition at line 330 of file ObjectLinkingLayer.cpp.
References assert(), and llvm::jitlink::jitLink().
setAutoClaimResponsibilityForObjectSymbols()
ObjectLinkingLayer & llvm::orc::ObjectLinkingLayer::setAutoClaimResponsibilityForObjectSymbols (bool AutoClaimObjectSymbols) inline
If set, this ObjectLinkingLayer instance will claim responsibility for any symbols provided by a given object file that were not already in the MaterializationResponsibility instance.
Setting this flag allows higher-level program representations (e.g. LLVM IR) to be added based on only a subset of the symbols they provide, without having to write intervening layers to scan and add the additional symbols. This trades diagnostic quality for convenience however: If all symbols are enumerated up-front then clashes can be detected and reported early (and usually deterministically). If this option is set, clashes for the additional symbols may not be detected until late, and detection may depend on the flow of control through JIT'd code. Use with care.
Definition at line 121 of file ObjectLinkingLayer.h.
setOverrideObjectFlagsWithResponsibilityFlags()
ObjectLinkingLayer & llvm::orc::ObjectLinkingLayer::setOverrideObjectFlagsWithResponsibilityFlags (bool OverrideObjectFlags) inline
Instructs this ObjectLinkingLayer instance to override the symbol flags found in the AtomGraph with the flags supplied by the MaterializationResponsibility instance.
This is a workaround to support symbol visibility in COFF, which does not use the libObject's SF_Exported flag. Use only when generating / adding COFF object files.
FIXME: We should be able to remove this if/when COFF properly tracks exported symbols.
Definition at line 104 of file ObjectLinkingLayer.h.
Friends And Related Function Documentation
ObjectLinkingLayerJITLinkContext
friend class ObjectLinkingLayerJITLinkContext friend
Definition at line 54 of file ObjectLinkingLayer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h
lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp