LLVM: llvm::Statistic Class Reference
llvm::Statistic Class Reference
#include "llvm/ADT/Statistic.h"
Public Member Functions
unsigned getValue () const
const char * getDebugType () const
const char * getName () const
const char * getDesc () const
void construct (const char *debugtype, const char *name, const char *desc)
construct - This should only be called for non-global statistics.
operator unsigned () const
const Statistic & operator= (unsigned Val)
const Statistic & operator++ ()
unsigned operator++ (int)
const Statistic & operator-- ()
unsigned operator-- (int)
const Statistic & operator+= (unsigned V)
const Statistic & operator-= (unsigned V)
void updateMax (unsigned V)
Public Attributes
const char * DebugType
const char * Name
const char * Desc
std::atomic< unsigned > Value
std::atomic< bool > Initialized
Protected Member Functions
Statistic & init ()
void RegisterStatistic ()
RegisterStatistic - The first time a statistic is bumped, this method is called.
Detailed Description
Definition at line 47 of file Statistic.h.
Member Function Documentation
construct()
void llvm::Statistic::construct (const char * debugtype, const char * name, const char * desc) inline
construct - This should only be called for non-global statistics.
Definition at line 61 of file Statistic.h.
References DebugType, Desc, Initialized, Name, and name.
getDebugType()
const char * llvm::Statistic::getDebugType () const inline
Definition at line 56 of file Statistic.h.
References DebugType.
Referenced by llvm::PrintStatisticsJSON().
getDesc()
const char * llvm::Statistic::getDesc () const inline
Definition at line 58 of file Statistic.h.
References Desc.
getName()
const char * llvm::Statistic::getName () const inline
Definition at line 57 of file Statistic.h.
References Name.
Referenced by llvm::orc::rpc::RPCTypeName< std::vector< T > >::getName(), llvm::orc::rpc::RPCTypeName< std::set< T > >::getName(), llvm::orc::rpc::Function< DerivedFunc, RetT(ArgTs...)>::getPrototype(), and llvm::PrintStatisticsJSON().
getValue()
unsigned llvm::Statistic::getValue () const inline
Definition at line 55 of file Statistic.h.
Referenced by operator unsigned(), and llvm::PrintStatisticsJSON().
init()
Statistic & llvm::Statistic::init () inline protected
Definition at line 157 of file Statistic.h.
References Initialized, and RegisterStatistic().
Referenced by operator++(), operator+=(), operator--(), operator-=(), operator=(), and updateMax().
operator unsigned()
llvm::Statistic::operator unsigned () const inline
Definition at line 70 of file Statistic.h.
References getValue().
operator++() [1/2]
const Statistic & llvm::Statistic::operator++ () inline
Definition at line 78 of file Statistic.h.
References init().
operator++() [2/2]
unsigned llvm::Statistic::operator++ (int) inline
Definition at line 83 of file Statistic.h.
References init().
operator+=()
const Statistic & llvm::Statistic::operator+= (unsigned V) inline
Definition at line 98 of file Statistic.h.
References init().
operator--() [1/2]
const Statistic & llvm::Statistic::operator-- () inline
Definition at line 88 of file Statistic.h.
References init().
operator--() [2/2]
unsigned llvm::Statistic::operator-- (int) inline
Definition at line 93 of file Statistic.h.
References init().
operator-=()
const Statistic & llvm::Statistic::operator-= (unsigned V) inline
Definition at line 105 of file Statistic.h.
References init().
operator=()
const Statistic & llvm::Statistic::operator= (unsigned Val) inline
Definition at line 73 of file Statistic.h.
References init().
RegisterStatistic()
void Statistic::RegisterStatistic () protected
RegisterStatistic - The first time a statistic is bumped, this method is called.
Definition at line 93 of file Statistic.cpp.
References Enabled, Initialized, llvm::Lock, SI, StatInfo, StatLock, and Stats.
Referenced by init().
updateMax()
void llvm::Statistic::updateMax (unsigned V) inline
Definition at line 112 of file Statistic.h.
References init().
Member Data Documentation
DebugType
const char* llvm::Statistic::DebugType
Definition at line 49 of file Statistic.h.
Referenced by construct(), and getDebugType().
Desc
const char* llvm::Statistic::Desc
Definition at line 51 of file Statistic.h.
Referenced by construct(), and getDesc().
Initialized
std::atomic<bool> llvm::Statistic::Initialized
Definition at line 53 of file Statistic.h.
Referenced by construct(), init(), and RegisterStatistic().
Name
const char* llvm::Statistic::Name
Definition at line 50 of file Statistic.h.
Referenced by construct(), and getName().
Value
std::atomic<unsigned> llvm::Statistic::Value
Definition at line 52 of file Statistic.h.
The documentation for this class was generated from the following files:
include/llvm/ADT/Statistic.h
lib/Support/Statistic.cpp