LLVM: llvm::PooledStringPtr Class Reference
llvm::PooledStringPtr Class Reference
PooledStringPtr - A pointer to an interned string.
#include "llvm/Support/StringPool.h"
Public Member Functions
PooledStringPtr ()=default
PooledStringPtr (entry_t *E)
PooledStringPtr (const PooledStringPtr &That)
PooledStringPtr & operator= (const PooledStringPtr &That)
void clear ()
~PooledStringPtr ()
const char * begin () const
const char * end () const
unsigned size () const
const char * operator* () const
operator bool () const
bool operator== (const PooledStringPtr &That) const
bool operator!= (const PooledStringPtr &That) const
Detailed Description
PooledStringPtr - A pointer to an interned string.
Use operator bool to test whether the pointer is valid, and operator * to get the string if so. This is a lightweight value class with storage requirements equivalent to a single pointer, but it does have reference-counting overhead when copied.
Definition at line 78 of file StringPool.h.
Constructor & Destructor Documentation
PooledStringPtr() [1/3]
llvm::PooledStringPtr::PooledStringPtr () default
PooledStringPtr() [2/3]
llvm::PooledStringPtr::PooledStringPtr (entry_t * E) inline explicit
Definition at line 86 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::getValue().
PooledStringPtr() [3/3]
llvm::PooledStringPtr::PooledStringPtr (const PooledStringPtr & That) inline
Definition at line 90 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::getValue().
~PooledStringPtr()
llvm::PooledStringPtr::~PooledStringPtr () inline
Definition at line 113 of file StringPool.h.
References clear().
Member Function Documentation
begin()
const char * llvm::PooledStringPtr::begin () const inline
Definition at line 115 of file StringPool.h.
References assert(), and llvm::StringMapEntry< ValueTy >::getKeyData().
Referenced by operator*().
clear()
void llvm::PooledStringPtr::clear () inline
Definition at line 103 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::Destroy(), and llvm::StringMapEntry< ValueTy >::getValue().
Referenced by operator=(), and ~PooledStringPtr().
end()
const char * llvm::PooledStringPtr::end () const inline
Definition at line 120 of file StringPool.h.
References assert(), llvm::StringMapEntry< ValueTy >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
operator bool()
llvm::PooledStringPtr::operator bool () const inline explicit
Definition at line 131 of file StringPool.h.
operator!=()
bool llvm::PooledStringPtr::operator!= (const PooledStringPtr & That) const inline
Definition at line 134 of file StringPool.h.
operator*()
const char * llvm::PooledStringPtr::operator* () const inline
Definition at line 130 of file StringPool.h.
References begin().
operator=()
PooledStringPtr & llvm::PooledStringPtr::operator= (const PooledStringPtr & That) inline
Definition at line 94 of file StringPool.h.
References clear(), and llvm::StringMapEntry< ValueTy >::getValue().
operator==()
bool llvm::PooledStringPtr::operator== (const PooledStringPtr & That) const inline
Definition at line 133 of file StringPool.h.
size()
unsigned llvm::PooledStringPtr::size () const inline
Definition at line 125 of file StringPool.h.
References assert(), and llvm::StringMapEntryBase::getKeyLength().
The documentation for this class was generated from the following file:
include/llvm/Support/StringPool.h