LLVM: llvm::remarks::YAMLParseError Class Reference
llvm::remarks::YAMLParseError Class Reference
#include "Remarks/YAMLRemarkParser.h"
Public Member Functions
YAMLParseError (StringRef Message, SourceMgr &SM, yaml::Stream &Stream, yaml::Node &Node)
YAMLParseError (StringRef Message)
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfo< YAMLParseError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< YAMLParseError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Definition at line 30 of file YAMLRemarkParser.h.
Constructor & Destructor Documentation
YAMLParseError() [1/2]
YAMLParseError::YAMLParseError (StringRef Message, SourceMgr & SM, yaml::Stream & Stream, yaml::Node & Node)
Definition at line 34 of file YAMLRemarkParser.cpp.
References llvm::SourceMgr::getDiagContext(), llvm::SourceMgr::getDiagHandler(), handleDiagnostic(), llvm::yaml::Stream::printError(), and llvm::SourceMgr::setDiagHandler().
YAMLParseError() [2/2]
llvm::remarks::YAMLParseError::YAMLParseError (StringRef Message) inline
Definition at line 37 of file YAMLRemarkParser.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::remarks::YAMLParseError::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 40 of file YAMLRemarkParser.h.
References llvm::inconvertibleErrorCode().
log()
void llvm::remarks::YAMLParseError::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 39 of file YAMLRemarkParser.h.
Member Data Documentation
ID
char YAMLParseError::ID = 0 static
Definition at line 32 of file YAMLRemarkParser.h.
The documentation for this class was generated from the following files:
lib/Remarks/YAMLRemarkParser.h
lib/Remarks/YAMLRemarkParser.cpp