LLVM: llvm::ilist_sentinel< OptionsT > Class Template Reference
llvm::ilist_sentinel< OptionsT > Class Template Reference
#include "llvm/ADT/ilist_node.h"
Public Member Functions
ilist_sentinel ()
void reset ()
bool empty () const
Public Member Functions inherited from llvm::ilist_node_impl< OptionsT >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< OptionsT >
using self_iterator = ilist_iterator< OptionsT, false, false >
using const_self_iterator = ilist_iterator< OptionsT, false, true >
using reverse_self_iterator = ilist_iterator< OptionsT, true, false >
using const_reverse_self_iterator = ilist_iterator< OptionsT, true, true >
Protected Member Functions inherited from llvm::ilist_node_impl< OptionsT >
ilist_node_impl ()=default
Detailed Description
template<class OptionsT>
class llvm::ilist_sentinel< OptionsT >
Definition at line 236 of file ilist_node.h.
Constructor & Destructor Documentation
ilist_sentinel()
template<class OptionsT > llvm::ilist_sentinel< OptionsT >::ilist_sentinel () inline
Examples
/home/tommy/workspace/llvm/9.0.1/llvm-9.0.1.src/include/llvm/ADT/ilist_node.h.
Definition at line 238 of file ilist_node.h.
References llvm::ilist_sentinel< OptionsT >::reset().
Member Function Documentation
empty()
template<class OptionsT > bool llvm::ilist_sentinel< OptionsT >::empty () const inline
Examples
/home/tommy/workspace/llvm/9.0.1/llvm-9.0.1.src/include/llvm/ADT/ilist_node.h.
Definition at line 248 of file ilist_node.h.
Referenced by llvm::simple_ilist< T, Options >::empty().
reset()
template<class OptionsT > void llvm::ilist_sentinel< OptionsT >::reset () inline
Examples
/home/tommy/workspace/llvm/9.0.1/llvm-9.0.1.src/include/llvm/ADT/ilist_node.h.
Definition at line 243 of file ilist_node.h.
Referenced by llvm::simple_ilist< T, Options >::clear(), and llvm::ilist_sentinel< OptionsT >::ilist_sentinel().
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_node.h