LLVM: llvm::VarListElementInit Class Reference
llvm::VarListElementInit Class Reference
List[4] - Represent access to one element of a var or field.
#include "llvm/TableGen/Record.h"
Public Member Functions
VarListElementInit (const VarListElementInit &)=delete
VarListElementInit & operator= (const VarListElementInit &)=delete
TypedInit * getVariable () const
unsigned getElementNum () const
std::string getAsString () const override
Convert this value to a string form.
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
static VarListElementInit * get (TypedInit *T, unsigned E)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
List[4] - Represent access to one element of a var or field.
Definition at line 1142 of file Record.h.
Constructor & Destructor Documentation
VarListElementInit()
llvm::VarListElementInit::VarListElementInit (const VarListElementInit &) delete
Member Function Documentation
classof()
static bool llvm::VarListElementInit::classof (const Init * I) inline static
Definition at line 1158 of file Record.h.
References I, and llvm::Init::IK_VarListElementInit.
get()
VarListElementInit * VarListElementInit::get (TypedInit * T, unsigned E) static
Definition at line 1524 of file Record.cpp.
References Allocator, E, and I.
getAsString()
std::string VarListElementInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1536 of file Record.cpp.
References llvm::Init::getAsString(), and llvm::utostr().
getBit()
Init * VarListElementInit::getBit (unsigned Bit) const override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1553 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::IntervalMapImpl::NodeRef::get(), and llvm::TypedInit::getType().
getElementNum()
unsigned llvm::VarListElementInit::getElementNum () const inline
Definition at line 1165 of file Record.h.
Referenced by resolveReferences().
getVariable()
TypedInit * llvm::VarListElementInit::getVariable () const inline
Definition at line 1164 of file Record.h.
operator=()
VarListElementInit & llvm::VarListElementInit::operator= (const VarListElementInit &) delete
resolveReferences()
Init * VarListElementInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1540 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), getElementNum(), List, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp