LLVM: llvm::SlotIndexes Class Reference
llvm::SlotIndexes Class Reference
SlotIndexes pass.
#include "llvm/CodeGen/SlotIndexes.h"
Public Types
using MBBIndexIterator = SmallVectorImpl< IdxMBBPair >::const_iterator
Iterator over the idx2MBBMap (sorted pairs of slot index of basic block begin and basic block)
Public Member Functions
SlotIndexes ()
~SlotIndexes () override
void getAnalysisUsage (AnalysisUsage &au) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
bool runOnMachineFunction (MachineFunction &fn) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void dump () const
Dump the indexes.
void repairIndexesInRange (MachineBasicBlock *MBB, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End)
Repair indexes after adding and removing instructions.
SlotIndex getZeroIndex ()
Returns the zero index for this analysis.
SlotIndex getLastIndex ()
Returns the base index of the last slot in this analysis.
bool hasIndex (const MachineInstr &instr) const
Returns true if the given machine instr is mapped to an index, otherwise returns false.
SlotIndex getInstructionIndex (const MachineInstr &MI) const
Returns the base index for the given instruction.
MachineInstr * getInstructionFromIndex (SlotIndex index) const
Returns the instruction for the given index, or null if the given index has no instruction associated with it.
SlotIndex getNextNonNullIndex (SlotIndex Index)
Returns the next non-null index, if one exists.
SlotIndex getIndexBefore (const MachineInstr &MI) const
getIndexBefore - Returns the index of the last indexed instruction before MI, or the start index of its basic block.
SlotIndex getIndexAfter (const MachineInstr &MI) const
getIndexAfter - Returns the index of the first indexed instruction after MI, or the end index of its basic block.
const std::pair< SlotIndex, SlotIndex > & getMBBRange (unsigned Num) const
Return the (start,end) range of the given basic block number.
const std::pair< SlotIndex, SlotIndex > & getMBBRange (const MachineBasicBlock *MBB) const
Return the (start,end) range of the given basic block.
SlotIndex getMBBStartIdx (unsigned Num) const
Returns the first index in the given basic block number.
SlotIndex getMBBStartIdx (const MachineBasicBlock *mbb) const
Returns the first index in the given basic block.
SlotIndex getMBBEndIdx (unsigned Num) const
Returns the last index in the given basic block number.
SlotIndex getMBBEndIdx (const MachineBasicBlock *mbb) const
Returns the last index in the given basic block.
MBBIndexIterator advanceMBBIndex (MBBIndexIterator I, SlotIndex To) const
Move iterator to the next IdxMBBPair where the SlotIndex is greater or equal to To.
MBBIndexIterator findMBBIndex (SlotIndex Idx) const
Get an iterator pointing to the IdxMBBPair with the biggest SlotIndex that is greater or equal to Idx.
MBBIndexIterator MBBIndexBegin () const
Returns an iterator for the begin of the idx2MBBMap.
MBBIndexIterator MBBIndexEnd () const
Return an iterator for the end of the idx2MBBMap.
MachineBasicBlock * getMBBFromIndex (SlotIndex index) const
Returns the basic block which the given index falls in.
SlotIndex insertMachineInstrInMaps (MachineInstr &MI, bool Late=false)
Insert the given machine instruction into the mapping.
void removeMachineInstrFromMaps (MachineInstr &MI)
Removes machine instruction (bundle) MI from the mapping.
void removeSingleMachineInstrFromMaps (MachineInstr &MI)
Removes a single machine instruction MI from the mapping.
SlotIndex replaceMachineInstrInMaps (MachineInstr &MI, MachineInstr &NewMI)
ReplaceMachineInstrInMaps - Replacing a machine instr with a new one in maps used by register allocator.
void insertMBBInMaps (MachineBasicBlock *mbb)
Add the given MachineBasicBlock into the maps.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
SlotIndexes pass.
This pass assigns indexes to each instruction.
Definition at line 314 of file SlotIndexes.h.
Member Typedef Documentation
MBBIndexIterator
using llvm::SlotIndexes::MBBIndexIterator = SmallVectorImpl<IdxMBBPair>::const_iterator
Iterator over the idx2MBBMap (sorted pairs of slot index of basic block begin and basic block)
Definition at line 490 of file SlotIndexes.h.
Constructor & Destructor Documentation
SlotIndexes()
llvm::SlotIndexes::SlotIndexes () inline
Definition at line 350 of file SlotIndexes.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeSlotIndexesPass().
~SlotIndexes()
llvm::SlotIndexes::~SlotIndexes () inline override
Definition at line 354 of file SlotIndexes.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::clearAndLeakNodesUnsafely().
Member Function Documentation
advanceMBBIndex()
MBBIndexIterator llvm::SlotIndexes::advanceMBBIndex (MBBIndexIterator I, SlotIndex To) const inline
Move iterator to the next IdxMBBPair where the SlotIndex is greater or equal to To.
Definition at line 494 of file SlotIndexes.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and I.
Referenced by findMBBIndex().
dump()
LLVM_DUMP_METHOD void SlotIndexes::dump () const
Dump the indexes.
Definition at line 238 of file SlotIndexes.cpp.
References llvm::dbgs().
findMBBIndex()
MBBIndexIterator llvm::SlotIndexes::findMBBIndex (SlotIndex Idx) const inline
Get an iterator pointing to the IdxMBBPair with the biggest SlotIndex that is greater or equal to Idx.
Definition at line 502 of file SlotIndexes.h.
References advanceMBBIndex(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and Idx.
Referenced by getMBBFromIndex().
getAnalysisUsage()
void SlotIndexes::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 26 of file SlotIndexes.cpp.
References llvm::MachineFunctionPass::getAnalysisUsage().
getIndexAfter()
SlotIndex llvm::SlotIndexes::getIndexAfter (const MachineInstr & MI) const inline
getIndexAfter - Returns the index of the first indexed instruction after MI, or the end index of its basic block.
MI is not required to have an index.
Definition at line 442 of file SlotIndexes.h.
References assert(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getMBBEndIdx(), I, and MI.
Referenced by insertMachineInstrInMaps().
getIndexBefore()
SlotIndex llvm::SlotIndexes::getIndexBefore (const MachineInstr & MI) const inline
getIndexBefore - Returns the index of the last indexed instruction before MI, or the start index of its basic block.
MI is not required to have an index.
Definition at line 425 of file SlotIndexes.h.
References assert(), B, llvm::MachineBasicBlock::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getMBBStartIdx(), I, and MI.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), and insertMachineInstrInMaps().
getInstructionFromIndex()
MachineInstr * llvm::SlotIndexes::getInstructionFromIndex (SlotIndex index) const inline
Returns the instruction for the given index, or null if the given index has no instruction associated with it.
Definition at line 406 of file SlotIndexes.h.
References llvm::IndexListEntry::getInstr(), and llvm::SlotIndex::isValid().
Referenced by llvm::LiveIntervals::getInstructionFromIndex(), getMBBFromIndex(), llvm::LiveRange::overlaps(), llvm::HexagonRegisterInfo::shouldCoalesce(), and stripValuesNotDefiningMask().
getInstructionIndex()
SlotIndex llvm::SlotIndexes::getInstructionIndex (const MachineInstr & MI) const inline
Returns the base index for the given instruction.
Definition at line 390 of file SlotIndexes.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::getBundleEnd(), llvm::getBundleStart(), llvm::MachineInstr::isDebugInstr(), MI, and llvm::skipDebugInstructionsForward().
Referenced by llvm::LiveInterval::computeSubRangeUndefs(), createDeadDef(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::handleMove(), llvm::LiveIntervals::handleMoveIntoBundle(), llvm::MachineBasicBlock::print(), and repairIndexesInRange().
getLastIndex()
SlotIndex llvm::SlotIndexes::getLastIndex () inline
Returns the base index of the last slot in this analysis.
Definition at line 379 of file SlotIndexes.h.
Referenced by getNextNonNullIndex().
getMBBEndIdx() [1/2]
SlotIndex llvm::SlotIndexes::getMBBEndIdx (const MachineBasicBlock * mbb) const inline
Returns the last index in the given basic block.
Definition at line 484 of file SlotIndexes.h.
References getMBBRange().
getMBBEndIdx() [2/2]
SlotIndex llvm::SlotIndexes::getMBBEndIdx (unsigned Num) const inline
Returns the last index in the given basic block number.
Definition at line 479 of file SlotIndexes.h.
References getMBBRange().
Referenced by getIndexAfter(), llvm::LiveIntervals::getMBBEndIdx(), getMBBFromIndex(), llvm::LiveIntervals::hasPHIKill(), llvm::LiveIntervals::pruneValue(), and repairIndexesInRange().
getMBBFromIndex()
MachineBasicBlock * llvm::SlotIndexes::getMBBFromIndex (SlotIndex index) const inline
Returns the basic block which the given index falls in.
Definition at line 517 of file SlotIndexes.h.
References assert(), llvm::SmallVectorBase::empty(), findMBBIndex(), getInstructionFromIndex(), getMBBEndIdx(), I, MBBIndexEnd(), and MI.
Referenced by llvm::LiveRangeCalc::extend(), llvm::LiveIntervals::getMBBFromIndex(), llvm::LiveIntervals::intervalIsInOneMBB(), llvm::LiveRangeCalc::isJointlyDominated(), and llvm::LiveIntervals::pruneValue().
getMBBRange() [1/2]
const std::pair< SlotIndex, SlotIndex > & llvm::SlotIndexes::getMBBRange (const MachineBasicBlock * MBB) const inline
Return the (start,end) range of the given basic block.
Definition at line 464 of file SlotIndexes.h.
References getMBBRange(), and llvm::MachineBasicBlock::getNumber().
getMBBRange() [2/2]
const std::pair< SlotIndex, SlotIndex > & llvm::SlotIndexes::getMBBRange (unsigned Num) const inline
Return the (start,end) range of the given basic block number.
Definition at line 458 of file SlotIndexes.h.
Referenced by getMBBEndIdx(), getMBBRange(), getMBBStartIdx(), llvm::LiveIntervals::pruneValue(), llvm::SplitEditor::splitLiveThroughBlock(), llvm::SplitEditor::splitRegInBlock(), and llvm::SplitEditor::splitRegOutBlock().
getMBBStartIdx() [1/2]
SlotIndex llvm::SlotIndexes::getMBBStartIdx (const MachineBasicBlock * mbb) const inline
Returns the first index in the given basic block.
Definition at line 474 of file SlotIndexes.h.
References getMBBRange().
getMBBStartIdx() [2/2]
SlotIndex llvm::SlotIndexes::getMBBStartIdx (unsigned Num) const inline
Returns the first index in the given basic block number.
Definition at line 469 of file SlotIndexes.h.
References getMBBRange().
Referenced by llvm::LiveRangeCalc::extend(), getIndexBefore(), llvm::LiveIntervals::getMBBStartIdx(), insertMBBInMaps(), llvm::MachineBasicBlock::print(), and repairIndexesInRange().
getNextNonNullIndex()
SlotIndex llvm::SlotIndexes::getNextNonNullIndex (SlotIndex Index) inline
Returns the next non-null index, if one exists.
Otherwise returns getLastIndex().
Definition at line 412 of file SlotIndexes.h.
References E, getLastIndex(), and I.
Referenced by llvm::LiveRange::isZeroLength().
getZeroIndex()
SlotIndex llvm::SlotIndexes::getZeroIndex () inline
Returns the zero index for this analysis.
Definition at line 373 of file SlotIndexes.h.
References assert().
hasIndex()
bool llvm::SlotIndexes::hasIndex (const MachineInstr & instr) const inline
Returns true if the given machine instr is mapped to an index, otherwise returns false.
Definition at line 385 of file SlotIndexes.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count().
Referenced by llvm::LiveIntervals::isNotInMIMap(), llvm::MachineBasicBlock::print(), repairIndexesInRange(), and llvm::LiveIntervals::repairIntervalsInRange().
insertMachineInstrInMaps()
SlotIndex llvm::SlotIndexes::insertMachineInstrInMaps (MachineInstr & MI, bool Late = false) inline
Insert the given machine instruction into the mapping.
Returns the assigned index. If Late is set and there are null indexes between mi's neighboring instructions, create the new index after the null indexes instead of before them.
Definition at line 538 of file SlotIndexes.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getIndexAfter(), getIndexBefore(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), and MI.
Referenced by llvm::LiveIntervals::handleMove(), llvm::LiveIntervals::InsertMachineInstrInMaps(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), llvm::LiveRangeEdit::rematerializeAt(), and repairIndexesInRange().
insertMBBInMaps()
void llvm::SlotIndexes::insertMBBInMaps (MachineBasicBlock * mbb) inline
Add the given MachineBasicBlock into the maps.
Definition at line 606 of file SlotIndexes.h.
References assert(), llvm::MachineFunction::end(), llvm::ilist_node_impl< OptionsT >::getIterator(), getMBBStartIdx(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insertAfter(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and llvm::sort().
Referenced by llvm::LiveIntervals::insertMBBInMaps().
MBBIndexBegin()
MBBIndexIterator llvm::SlotIndexes::MBBIndexBegin () const inline
Returns an iterator for the begin of the idx2MBBMap.
Definition at line 507 of file SlotIndexes.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
MBBIndexEnd()
MBBIndexIterator llvm::SlotIndexes::MBBIndexEnd () const inline
Return an iterator for the end of the idx2MBBMap.
Definition at line 512 of file SlotIndexes.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by getMBBFromIndex().
releaseMemory()
void SlotIndexes::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 31 of file SlotIndexes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), llvm::SmallVectorImpl< T >::clear(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
removeMachineInstrFromMaps()
void SlotIndexes::removeMachineInstrFromMaps (MachineInstr & MI)
Removes machine instruction (bundle) MI from the mapping.
This should be called before MachineInstr::eraseFromParent() is used to remove a whole bundle or an unbundled instruction.
Definition at line 104 of file SlotIndexes.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::IndexListEntry::getInstr(), MI, and llvm::IndexListEntry::setInstr().
Referenced by llvm::LiveIntervals::handleMove(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), and repairIndexesInRange().
removeSingleMachineInstrFromMaps()
void SlotIndexes::removeSingleMachineInstrFromMaps (MachineInstr & MI)
Removes a single machine instruction MI from the mapping.
This should be called before MachineInstr::eraseFromBundle() is used to remove a single instruction (out of a bundle).
Definition at line 119 of file SlotIndexes.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::IndexListEntry::getInstr(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), MI, and llvm::IndexListEntry::setInstr().
repairIndexesInRange()
void SlotIndexes::repairIndexesInRange (MachineBasicBlock * MBB, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End)
Repair indexes after adding and removing instructions.
Definition at line 167 of file SlotIndexes.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getInstructionIndex(), llvm::ilist_node_impl< OptionsT >::getIterator(), getMBBEndIdx(), getMBBStartIdx(), hasIndex(), I, insertMachineInstrInMaps(), MI, and removeMachineInstrFromMaps().
Referenced by llvm::LiveIntervals::repairIntervalsInRange().
replaceMachineInstrInMaps()
SlotIndex llvm::SlotIndexes::replaceMachineInstrInMaps (MachineInstr & MI, MachineInstr & NewMI) inline
ReplaceMachineInstrInMaps - Replacing a machine instr with a new one in maps used by register allocator.
Returns
the index where the new instruction was inserted.
Definition at line 591 of file SlotIndexes.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::IndexListEntry::getInstr(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), MI, and llvm::IndexListEntry::setInstr().
Referenced by llvm::LiveIntervals::ReplaceMachineInstrInMaps().
runOnMachineFunction()
bool SlotIndexes::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 39 of file SlotIndexes.cpp.
References assert(), llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::SmallVectorBase::empty(), llvm::MachineFunction::getNumBlockIDs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SlotIndex::InstrDist, LLVM_DEBUG, MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::MachineFunction::size(), and llvm::sort().
Member Data Documentation
ID
char SlotIndexes::ID = 0 static
Definition at line 348 of file SlotIndexes.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SlotIndexes.h
lib/CodeGen/SlotIndexes.cpp