LLVM: llvm::coverage::RawCoverageFilenamesReader Class Reference
llvm::coverage::RawCoverageFilenamesReader Class Reference
Reader for the raw coverage filenames.
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
Public Member Functions
RawCoverageFilenamesReader (StringRef Data, std::vector< StringRef > &Filenames)
RawCoverageFilenamesReader (const RawCoverageFilenamesReader &)=delete
RawCoverageFilenamesReader & operator= (const RawCoverageFilenamesReader &)=delete
Error read ()
Additional Inherited Members
Protected Member Functions inherited from llvm::coverage::RawCoverageReader
RawCoverageReader (StringRef Data)
Error readULEB128 (uint64_t &Result)
Error readIntMax (uint64_t &Result, uint64_t MaxPlus1)
Error readSize (uint64_t &Result)
Error readString (StringRef &Result)
Protected Attributes inherited from llvm::coverage::RawCoverageReader
StringRef Data
Detailed Description
Reader for the raw coverage filenames.
Definition at line 117 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageFilenamesReader() [1/2]
llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader (StringRef Data, std::vector< StringRef > & Filenames) inline
Definition at line 121 of file CoverageMappingReader.h.
RawCoverageFilenamesReader() [2/2]
llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader (const RawCoverageFilenamesReader &) delete
Member Function Documentation
operator=()
RawCoverageFilenamesReader & llvm::coverage::RawCoverageFilenamesReader::operator= (const RawCoverageFilenamesReader &) delete
read()
Error RawCoverageFilenamesReader::read ()
Definition at line 95 of file CoverageMappingReader.cpp.
References I, llvm::coverage::RawCoverageReader::readSize(), llvm::coverage::RawCoverageReader::readString(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingReader.h
lib/ProfileData/Coverage/CoverageMappingReader.cpp