LLVM: llvm::jitlink::AtomGraph Class Reference
llvm::jitlink::AtomGraph Class Reference
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Classes
class defined_atom_iterator_impl
Public Types
using external_atom_iterator = ExternalAtomSet::iterator
using section_iterator = pointee_iterator< SectionList::iterator >
using const_section_iterator = pointee_iterator< SectionList::const_iterator >
using defined_atom_iterator = defined_atom_iterator_impl< section_iterator, Section::atom_iterator, DefinedAtom * >
using const_defined_atom_iterator = defined_atom_iterator_impl< const_section_iterator, Section::const_atom_iterator, const DefinedAtom * >
Public Member Functions
AtomGraph (std::string Name, unsigned PointerSize, support::endianness Endianness)
const std::string & getName ()
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
unsigned getPointerSize () const
Returns the pointer size for use in this graph.
support::endianness getEndianness () const
Returns the endianness of atom-content in this graph.
Section & createSection (StringRef Name, uint32_t Alignment, sys::Memory::ProtectionFlags Prot, bool IsZeroFill)
Create a section with the given name, protection flags, and alignment.
Atom & addExternalAtom (StringRef Name)
Add an external atom representing an undefined symbol in this graph.
Atom & addAbsoluteAtom (StringRef Name, JITTargetAddress Addr)
Add an external atom representing an absolute symbol.
DefinedAtom & addAnonymousAtom (Section &Parent, JITTargetAddress Address, uint32_t Alignment)
Add an anonymous defined atom to the graph.
DefinedAtom & addDefinedAtom (Section &Parent, StringRef Name, JITTargetAddress Address, uint32_t Alignment)
Add a defined atom to the graph.
DefinedAtom & addCommonAtom (Section &Parent, StringRef Name, JITTargetAddress Address, uint32_t Alignment, uint64_t Size)
Add a common symbol atom to the graph.
iterator_range< section_iterator > sections ()
Section * findSectionByName (StringRef Name)
Returns the section with the given name if it exists, otherwise returns null.
iterator_range< external_atom_iterator > external_atoms ()
iterator_range< external_atom_iterator > absolute_atoms ()
iterator_range< defined_atom_iterator > defined_atoms ()
iterator_range< const_defined_atom_iterator > defined_atoms () const
Atom & getAtomByName (StringRef Name)
Returns the atom with the given name, which must exist in this graph.
DefinedAtom & getDefinedAtomByName (StringRef Name)
Returns the atom with the given name, which must exist in this graph and be a DefinedAtom.
Expected< Atom & > findAtomByName (StringRef Name)
Search for the given atom by name.
Expected< DefinedAtom & > findDefinedAtomByName (StringRef Name)
Search for the given defined atom by name.
DefinedAtom * getAtomByAddress (JITTargetAddress Address)
Returns the atom covering the given address, or an error if no such atom exists.
Expected< DefinedAtom & > findAtomByAddress (JITTargetAddress Address)
Like getAtomByAddress, but returns an Error if the given address is not covered by an atom, rather than a null pointer.
void removeExternalAtom (Atom &A)
void removeAbsoluteAtom (Atom &A)
Remove the given absolute atom from the graph.
void removeDefinedAtom (DefinedAtom &DA)
Remove the given defined atom from the graph.
void invalidateAddrToAtomMap ()
Invalidate the atom-to-address map.
void dump (raw_ostream &OS, std::function< StringRef(Edge::Kind)> EdegKindToName=std::function< StringRef(Edge::Kind)>())
Dump the graph.
Detailed Description
Definition at line 469 of file JITLink.h.
Member Typedef Documentation
const_defined_atom_iterator
using llvm::jitlink::AtomGraph::const_defined_atom_iterator = defined_atom_iterator_impl<const_section_iterator, Section::const_atom_iterator, const DefinedAtom *>
Definition at line 530 of file JITLink.h.
const_section_iterator
using llvm::jitlink::AtomGraph::const_section_iterator = pointee_iterator<SectionList::const_iterator>
Definition at line 480 of file JITLink.h.
defined_atom_iterator
using llvm::jitlink::AtomGraph::defined_atom_iterator = defined_atom_iterator_impl<section_iterator, Section::atom_iterator, DefinedAtom *>
Definition at line 526 of file JITLink.h.
external_atom_iterator
using llvm::jitlink::AtomGraph::external_atom_iterator = ExternalAtomSet::iterator
Definition at line 477 of file JITLink.h.
section_iterator
using llvm::jitlink::AtomGraph::section_iterator = pointee_iterator<SectionList::iterator>
Definition at line 479 of file JITLink.h.
Constructor & Destructor Documentation
AtomGraph()
llvm::jitlink::AtomGraph::AtomGraph (std::string Name, unsigned PointerSize, support::endianness Endianness) inline
Definition at line 535 of file JITLink.h.
Member Function Documentation
absolute_atoms()
iterator_range< external_atom_iterator > llvm::jitlink::AtomGraph::absolute_atoms () inline
Definition at line 645 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
Referenced by dump().
addAbsoluteAtom()
Atom & llvm::jitlink::AtomGraph::addAbsoluteAtom (StringRef Name, JITTargetAddress Addr) inline
Add an external atom representing an absolute symbol.
Definition at line 571 of file JITLink.h.
References A, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
addAnonymousAtom()
DefinedAtom & llvm::jitlink::AtomGraph::addAnonymousAtom (Section & Parent, JITTargetAddress Address, uint32_t Alignment) inline
Add an anonymous defined atom to the graph.
Anonymous atoms have content but no name. They must have an address.
Definition at line 584 of file JITLink.h.
References A, llvm::Address, and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate().
Referenced by llvm::jitlink::EHFrameParser::atomize().
addCommonAtom()
DefinedAtom & llvm::jitlink::AtomGraph::addCommonAtom (Section & Parent, StringRef Name, JITTargetAddress Address, uint32_t Alignment, uint64_t Size) inline
Add a common symbol atom to the graph.
Adds a common-symbol atom to the graph with the given parent, name, address, alignment and size.
Definition at line 614 of file JITLink.h.
References A, llvm::Address, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and Size.
addDefinedAtom()
DefinedAtom & llvm::jitlink::AtomGraph::addDefinedAtom (Section & Parent, StringRef Name, JITTargetAddress Address, uint32_t Alignment) inline
Add a defined atom to the graph.
Allocates and constructs a DefinedAtom instance with the given parent, name, address, and alignment.
Definition at line 598 of file JITLink.h.
References A, llvm::Address, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count().
addExternalAtom()
Atom & llvm::jitlink::AtomGraph::addExternalAtom (StringRef Name) inline
Add an external atom representing an undefined symbol in this graph.
Definition at line 560 of file JITLink.h.
References A, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
createSection()
Section & llvm::jitlink::AtomGraph::createSection (StringRef Name, uint32_t Alignment, sys::Memory::ProtectionFlags Prot, bool IsZeroFill) inline
Create a section with the given name, protection flags, and alignment.
Definition at line 551 of file JITLink.h.
defined_atoms() [1/2]
iterator_range< defined_atom_iterator > llvm::jitlink::AtomGraph::defined_atoms () inline
Definition at line 649 of file JITLink.h.
References llvm::make_range().
Referenced by dump(), and llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
defined_atoms() [2/2]
iterator_range< const_defined_atom_iterator > llvm::jitlink::AtomGraph::defined_atoms () const inline
Definition at line 654 of file JITLink.h.
References llvm::make_range().
dump()
void llvm::jitlink::AtomGraph::dump (raw_ostream & OS, std::function< StringRef(Edge::Kind)> EdegKindToName = std::function<StringRef(Edge::Kind)>())
Dump the graph.
If supplied, the EdgeKindToName function will be used to name edge kinds in the debug output. Otherwise raw edge kind numbers will be displayed.
Definition at line 104 of file JITLink.cpp.
References A, absolute_atoms(), defined_atoms(), E, llvm::StringRef::empty(), external_atoms(), llvm::format(), llvm::jitlink::getGenericEdgeKindName(), and llvm::jitlink::printEdge().
external_atoms()
iterator_range< external_atom_iterator > llvm::jitlink::AtomGraph::external_atoms () inline
Definition at line 641 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
Referenced by dump().
findAtomByAddress()
Expected< DefinedAtom & > llvm::jitlink::AtomGraph::findAtomByAddress (JITTargetAddress Address) inline
Like getAtomByAddress, but returns an Error if the given address is not covered by an atom, rather than a null pointer.
Definition at line 730 of file JITLink.h.
References llvm::Address, llvm::formatv(), and getAtomByAddress().
findAtomByName()
Expected< Atom & > llvm::jitlink::AtomGraph::findAtomByName (StringRef Name) inline
Search for the given atom by name.
Returns the atom (if found) or an error (if no atom with this name exists).
Definition at line 678 of file JITLink.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
findDefinedAtomByName()
Expected< DefinedAtom & > llvm::jitlink::AtomGraph::findDefinedAtomByName (StringRef Name) inline
Search for the given defined atom by name.
Returns the defined atom (if found) or an error (if no atom with this name exists, or if one exists but is not a defined atom).
Definition at line 688 of file JITLink.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
findSectionByName()
Section * llvm::jitlink::AtomGraph::findSectionByName (StringRef Name) inline
Returns the section with the given name if it exists, otherwise returns null.
Definition at line 634 of file JITLink.h.
References sections().
getAtomByAddress()
DefinedAtom * llvm::jitlink::AtomGraph::getAtomByAddress (JITTargetAddress Address) inline
Returns the atom covering the given address, or an error if no such atom exists.
Returns null if no atom exists at the given address.
Definition at line 703 of file JITLink.h.
References llvm::Address, assert(), and I.
Referenced by findAtomByAddress().
getAtomByName()
Atom & llvm::jitlink::AtomGraph::getAtomByName (StringRef Name) inline
Returns the atom with the given name, which must exist in this graph.
Definition at line 661 of file JITLink.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by getDefinedAtomByName().
getDefinedAtomByName()
DefinedAtom & llvm::jitlink::AtomGraph::getDefinedAtomByName (StringRef Name) inline
Returns the atom with the given name, which must exist in this graph and be a DefinedAtom.
Definition at line 669 of file JITLink.h.
References A, assert(), and getAtomByName().
getEndianness()
support::endianness llvm::jitlink::AtomGraph::getEndianness () const inline
Returns the endianness of atom-content in this graph.
Definition at line 548 of file JITLink.h.
getName()
const std::string & llvm::jitlink::AtomGraph::getName () inline
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
Definition at line 542 of file JITLink.h.
getPointerSize()
unsigned llvm::jitlink::AtomGraph::getPointerSize () const inline
Returns the pointer size for use in this graph.
Definition at line 545 of file JITLink.h.
Referenced by llvm::jitlink::EHFrameParser::atomize().
invalidateAddrToAtomMap()
void llvm::jitlink::AtomGraph::invalidateAddrToAtomMap () inline
Invalidate the atom-to-address map.
Definition at line 769 of file JITLink.h.
References llvm::None.
removeAbsoluteAtom()
void llvm::jitlink::AtomGraph::removeAbsoluteAtom (Atom & A) inline
Remove the given absolute atom from the graph.
Definition at line 746 of file JITLink.h.
References A, assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase().
removeDefinedAtom()
void llvm::jitlink::AtomGraph::removeDefinedAtom (DefinedAtom & DA) inline
Remove the given defined atom from the graph.
Definition at line 754 of file JITLink.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::jitlink::Atom::getAddress(), llvm::jitlink::Atom::getName(), llvm::jitlink::DefinedAtom::getSection(), and llvm::jitlink::Atom::hasName().
removeExternalAtom()
void llvm::jitlink::AtomGraph::removeExternalAtom (Atom & A) inline
Definition at line 738 of file JITLink.h.
References A, assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase().
sections()
iterator_range< section_iterator > llvm::jitlink::AtomGraph::sections () inline
Definition at line 627 of file JITLink.h.
References llvm::make_range().
Referenced by findSectionByName().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp