LLVM: llvm::LiveIntervals::HMEditor Class Reference
llvm::LiveIntervals::HMEditor Class Reference
Toolkit used by handleMove to trim or extend live intervals.
Public Member Functions
HMEditor (LiveIntervals &LIS, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, SlotIndex OldIdx, SlotIndex NewIdx, bool UpdateFlags)
LiveRange * getRegUnitLI (unsigned Unit)
void updateAllRanges (MachineInstr *MI)
Update all live ranges touched by MI, assuming a move from OldIdx to NewIdx.
Detailed Description
Toolkit used by handleMove to trim or extend live intervals.
Definition at line 943 of file LiveIntervals.cpp.
Constructor & Destructor Documentation
HMEditor()
llvm::LiveIntervals::HMEditor::HMEditor (LiveIntervals & LIS, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI, SlotIndex OldIdx, SlotIndex NewIdx, bool UpdateFlags) inline
Definition at line 954 of file LiveIntervals.cpp.
References MRI, and TRI.
Member Function Documentation
getRegUnitLI()
LiveRange * llvm::LiveIntervals::HMEditor::getRegUnitLI (unsigned Unit) inline
Definition at line 964 of file LiveIntervals.cpp.
References llvm::LiveIntervals::getCachedRegUnit(), llvm::LiveIntervals::getRegUnit(), and MRI.
Referenced by llvm::LiveIntervals::HMEditor::updateAllRanges().
updateAllRanges()
void llvm::LiveIntervals::HMEditor::updateAllRanges (MachineInstr * MI) inline
Update all live ranges touched by MI, assuming a move from OldIdx to NewIdx.
Definition at line 972 of file LiveIntervals.cpp.
References llvm::dbgs(), llvm::LiveIntervals::getInterval(), llvm::LaneBitmask::getNone(), llvm::LiveIntervals::HMEditor::getRegUnitLI(), llvm::LiveInterval::hasSubRanges(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MI, MRI, llvm::LiveInterval::subranges(), SubReg, and TRI.
Referenced by llvm::LiveIntervals::handleMove(), and llvm::LiveIntervals::handleMoveIntoBundle().
The documentation for this class was generated from the following file:
lib/CodeGen/LiveIntervals.cpp