LLVM: llvm::DebugEpochBase::HandleBase Class Reference
llvm::DebugEpochBase::HandleBase Class Reference
#include "llvm/ADT/EpochTracker.h"
Public Member Functions
HandleBase ()=default
HandleBase (const DebugEpochBase *)
bool isHandleInSync () const
const void * getEpochAddress () const
Detailed Description
Definition at line 85 of file EpochTracker.h.
Constructor & Destructor Documentation
HandleBase() [1/2]
llvm::DebugEpochBase::HandleBase::HandleBase () default
HandleBase() [2/2]
llvm::DebugEpochBase::HandleBase::HandleBase (const DebugEpochBase *) inline explicit
Definition at line 88 of file EpochTracker.h.
Member Function Documentation
getEpochAddress()
const void * llvm::DebugEpochBase::HandleBase::getEpochAddress () const inline
Definition at line 90 of file EpochTracker.h.
Referenced by llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!=(), and llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator==().
isHandleInSync()
bool llvm::DebugEpochBase::HandleBase::isHandleInSync () const inline
Definition at line 89 of file EpochTracker.h.
Referenced by llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!=(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator*(), llvm::SmallPtrSetIterator< PtrTy >::operator*(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++(), llvm::SmallPtrSetIterator< PtrTy >::operator++(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator->(), and llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator==().
The documentation for this class was generated from the following file:
include/llvm/ADT/EpochTracker.h