LLVM: llvm::LegalizeRuleSet Class Reference
llvm::LegalizeRuleSet Class Reference
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
Public Member Functions
LegalizeRuleSet ()
bool isAliasedByAnother ()
void setIsAliasedByAnother ()
void aliasTo (unsigned Opcode)
unsigned getAlias () const
LegalizeRuleSet & legalIf (LegalityPredicate Predicate)
The instruction is legal if predicate is true.
LegalizeRuleSet & legalFor (std::initializer_list< LLT > Types)
The instruction is legal when type index 0 is any type in the given list.
LegalizeRuleSet & legalFor (std::initializer_list< std::pair< LLT, LLT > > Types)
The instruction is legal when type indexes 0 and 1 is any type pair in the given list.
LegalizeRuleSet & legalForTypesWithMemDesc (std::initializer_list< LegalityPredicates::TypePairAndMemDesc > TypesAndMemDesc)
The instruction is legal when type indexes 0 and 1 along with the memory size and minimum alignment is any type and size tuple in the given list.
LegalizeRuleSet & legalForCartesianProduct (std::initializer_list< LLT > Types)
The instruction is legal when type indexes 0 and 1 are both in the given list.
LegalizeRuleSet & legalForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1)
The instruction is legal when type indexes 0 and 1 are both their respective lists.
LegalizeRuleSet & legalForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1, std::initializer_list< LLT > Types2)
The instruction is legal when type indexes 0, 1, and 2 are both their respective lists.
LegalizeRuleSet & alwaysLegal ()
LegalizeRuleSet & lower ()
The instruction is lowered.
LegalizeRuleSet & lowerIf (LegalityPredicate Predicate)
The instruction is lowered if predicate is true.
LegalizeRuleSet & lowerIf (LegalityPredicate Predicate, LegalizeMutation Mutation)
The instruction is lowered if predicate is true.
LegalizeRuleSet & lowerFor (std::initializer_list< LLT > Types)
The instruction is lowered when type index 0 is any type in the given list.
LegalizeRuleSet & lowerFor (std::initializer_list< LLT > Types, LegalizeMutation Mutation)
The instruction is lowered when type index 0 is any type in the given list.
LegalizeRuleSet & lowerFor (std::initializer_list< std::pair< LLT, LLT > > Types)
The instruction is lowered when type indexes 0 and 1 is any type pair in the given list.
LegalizeRuleSet & lowerFor (std::initializer_list< std::pair< LLT, LLT > > Types, LegalizeMutation Mutation)
The instruction is lowered when type indexes 0 and 1 is any type pair in the given list.
LegalizeRuleSet & lowerForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1)
The instruction is lowered when type indexes 0 and 1 are both in their respective lists.
LegalizeRuleSet & lowerForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1, std::initializer_list< LLT > Types2)
The instruction is lowered when when type indexes 0, 1, and 2 are all in their respective lists.
LegalizeRuleSet & libcallIf (LegalityPredicate Predicate)
Like legalIf, but for the Libcall action.
LegalizeRuleSet & libcallFor (std::initializer_list< LLT > Types)
LegalizeRuleSet & libcallFor (std::initializer_list< std::pair< LLT, LLT > > Types)
LegalizeRuleSet & libcallForCartesianProduct (std::initializer_list< LLT > Types)
LegalizeRuleSet & libcallForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1)
LegalizeRuleSet & widenScalarIf (LegalityPredicate Predicate, LegalizeMutation Mutation)
Widen the scalar to the one selected by the mutation if the predicate is true.
LegalizeRuleSet & narrowScalarIf (LegalityPredicate Predicate, LegalizeMutation Mutation)
Narrow the scalar to the one selected by the mutation if the predicate is true.
LegalizeRuleSet & moreElementsIf (LegalityPredicate Predicate, LegalizeMutation Mutation)
Add more elements to reach the type selected by the mutation if the predicate is true.
LegalizeRuleSet & fewerElementsIf (LegalityPredicate Predicate, LegalizeMutation Mutation)
Remove elements to reach the type selected by the mutation if the predicate is true.
LegalizeRuleSet & unsupported ()
The instruction is unsupported.
LegalizeRuleSet & unsupportedIf (LegalityPredicate Predicate)
LegalizeRuleSet & unsupportedIfMemSizeNotPow2 ()
LegalizeRuleSet & customIf (LegalityPredicate Predicate)
LegalizeRuleSet & customFor (std::initializer_list< LLT > Types)
LegalizeRuleSet & customFor (std::initializer_list< std::pair< LLT, LLT > > Types)
The instruction is custom when type indexes 0 and 1 is any type pair in the given list.
LegalizeRuleSet & customForCartesianProduct (std::initializer_list< LLT > Types)
LegalizeRuleSet & customForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1)
LegalizeRuleSet & custom ()
Unconditionally custom lower.
LegalizeRuleSet & widenScalarToNextPow2 (unsigned TypeIdx, unsigned MinSize=0)
Widen the scalar to the next power of two that is at least MinSize.
LegalizeRuleSet & widenScalarOrEltToNextPow2 (unsigned TypeIdx, unsigned MinSize=0)
Widen the scalar or vector element type to the next power of two that is at least MinSize.
LegalizeRuleSet & narrowScalar (unsigned TypeIdx, LegalizeMutation Mutation)
LegalizeRuleSet & scalarize (unsigned TypeIdx)
LegalizeRuleSet & minScalarOrElt (unsigned TypeIdx, const LLT &Ty)
Ensure the scalar or element is at least as wide as Ty.
LegalizeRuleSet & minScalarOrEltIf (LegalityPredicate Predicate, unsigned TypeIdx, const LLT &Ty)
Ensure the scalar or element is at least as wide as Ty.
LegalizeRuleSet & minScalar (unsigned TypeIdx, const LLT &Ty)
Ensure the scalar is at least as wide as Ty.
LegalizeRuleSet & maxScalarOrElt (unsigned TypeIdx, const LLT &Ty)
Ensure the scalar is at most as wide as Ty.
LegalizeRuleSet & maxScalar (unsigned TypeIdx, const LLT &Ty)
Ensure the scalar is at most as wide as Ty.
LegalizeRuleSet & maxScalarIf (LegalityPredicate Predicate, unsigned TypeIdx, const LLT &Ty)
Conditionally limit the maximum size of the scalar.
LegalizeRuleSet & clampScalar (unsigned TypeIdx, const LLT &MinTy, const LLT &MaxTy)
Limit the range of scalar sizes to MinTy and MaxTy.
LegalizeRuleSet & clampScalarOrElt (unsigned TypeIdx, const LLT &MinTy, const LLT &MaxTy)
Limit the range of scalar sizes to MinTy and MaxTy.
LegalizeRuleSet & minScalarSameAs (unsigned TypeIdx, unsigned LargeTypeIdx)
Widen the scalar to match the size of another.
LegalizeRuleSet & minScalarEltSameAsIf (LegalityPredicate Predicate, unsigned TypeIdx, unsigned LargeTypeIdx)
Conditionally widen the scalar or elt to match the size of another.
LegalizeRuleSet & moreElementsToNextPow2 (unsigned TypeIdx)
Add more elements to the vector to reach the next power of two.
LegalizeRuleSet & clampMinNumElements (unsigned TypeIdx, const LLT &EltTy, unsigned MinElements)
Limit the number of elements in EltTy vectors to at least MinElements.
LegalizeRuleSet & clampMaxNumElements (unsigned TypeIdx, const LLT &EltTy, unsigned MaxElements)
Limit the number of elements in EltTy vectors to at most MaxElements.
LegalizeRuleSet & clampNumElements (unsigned TypeIdx, const LLT &MinTy, const LLT &MaxTy)
Limit the number of elements for the given vectors to at least MinTy's number of elements and at most MaxTy's number of elements.
LegalizeRuleSet & fallback ()
Fallback on the previous implementation.
bool verifyTypeIdxsCoverage (unsigned NumTypeIdxs) const
Check if there is no type index which is obviously not handled by the LegalizeRuleSet in any way at all.
LegalizeActionStep apply (const LegalityQuery &Query) const
Apply the ruleset to the given LegalityQuery.
Detailed Description
Definition at line 317 of file LegalizerInfo.h.
Constructor & Destructor Documentation
LegalizeRuleSet()
llvm::LegalizeRuleSet::LegalizeRuleSet () inline
Definition at line 441 of file LegalizerInfo.h.
Member Function Documentation
aliasTo()
void llvm::LegalizeRuleSet::aliasTo (unsigned Opcode) inline
Definition at line 445 of file LegalizerInfo.h.
References assert(), and llvm::SmallVectorBase::empty().
Referenced by llvm::LegalizerInfo::aliasActionDefinitions().
alwaysLegal()
LegalizeRuleSet & llvm::LegalizeRuleSet::alwaysLegal () inline
Definition at line 498 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo().
apply()
LegalizeActionStep LegalizeRuleSet::apply (const LegalityQuery & Query) const
Apply the ruleset to the given LegalityQuery.
Definition at line 180 of file LegalizerInfo.cpp.
References assert(), llvm::dbgs(), hasNoSimpleLoops(), LLVM_DEBUG, Mutation, mutationIsSane(), llvm::LegalityQuery::print(), llvm::LegalizeActions::Unsupported, and llvm::LegalizeActions::UseLegacyRules.
Referenced by llvm::LegalizerInfo::getAction(), and llvm::handleErrorImpl().
clampMaxNumElements()
LegalizeRuleSet & llvm::LegalizeRuleSet::clampMaxNumElements (unsigned TypeIdx, const LLT & EltTy, unsigned MaxElements) inline
Limit the number of elements in EltTy vectors to at most MaxElements.
Definition at line 841 of file LegalizerInfo.h.
References llvm::LegalizeActions::FewerElements, llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::isVector(), llvm::LLT::scalarOrVector(), and llvm::LegalityQuery::Types.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and clampNumElements().
clampMinNumElements()
LegalizeRuleSet & llvm::LegalizeRuleSet::clampMinNumElements (unsigned TypeIdx, const LLT & EltTy, unsigned MinElements) inline
Limit the number of elements in EltTy vectors to at least MinElements.
Definition at line 823 of file LegalizerInfo.h.
References llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::isVector(), llvm::LegalizeActions::MoreElements, and llvm::LegalityQuery::Types.
Referenced by clampNumElements().
clampNumElements()
LegalizeRuleSet & llvm::LegalizeRuleSet::clampNumElements (unsigned TypeIdx, const LLT & MinTy, const LLT & MaxTy) inline
Limit the number of elements for the given vectors to at least MinTy's number of elements and at most MaxTy's number of elements.
No effect if the type is not a vector or does not have the same element type as the constraints. The element type of MinTy and MaxTy must match.
Definition at line 864 of file LegalizerInfo.h.
References assert(), clampMaxNumElements(), clampMinNumElements(), llvm::LLT::getElementType(), and llvm::LLT::getNumElements().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
clampScalar()
LegalizeRuleSet & llvm::LegalizeRuleSet::clampScalar (unsigned TypeIdx, const LLT & MinTy, const LLT & MaxTy) inline
Limit the range of scalar sizes to MinTy and MaxTy.
Definition at line 769 of file LegalizerInfo.h.
References assert(), llvm::LLT::isScalar(), maxScalar(), and minScalar().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and llvm::ARMLegalizerInfo::ARMLegalizerInfo().
clampScalarOrElt()
LegalizeRuleSet & llvm::LegalizeRuleSet::clampScalarOrElt (unsigned TypeIdx, const LLT & MinTy, const LLT & MaxTy) inline
Limit the range of scalar sizes to MinTy and MaxTy.
Definition at line 776 of file LegalizerInfo.h.
References maxScalarOrElt(), and minScalarOrElt().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
custom()
LegalizeRuleSet & llvm::LegalizeRuleSet::custom () inline
Unconditionally custom lower.
Definition at line 670 of file LegalizerInfo.h.
References customIf().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
customFor() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::customFor (std::initializer_list< LLT > Types) inline
Definition at line 650 of file LegalizerInfo.h.
References llvm::LegalizeActions::Custom.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and llvm::ARMLegalizerInfo::ARMLegalizerInfo().
customFor() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::customFor (std::initializer_list< std::pair< LLT, LLT > > Types) inline
The instruction is custom when type indexes 0 and 1 is any type pair in the given list.
Definition at line 656 of file LegalizerInfo.h.
References llvm::LegalizeActions::Custom.
customForCartesianProduct() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::customForCartesianProduct (std::initializer_list< LLT > Types) inline
Definition at line 660 of file LegalizerInfo.h.
References llvm::LegalizeActions::Custom.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::ARMLegalizerInfo::ARMLegalizerInfo().
customForCartesianProduct() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::customForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1) inline
Definition at line 664 of file LegalizerInfo.h.
References llvm::LegalizeActions::Custom.
customIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::customIf (LegalityPredicate Predicate) inline
Definition at line 644 of file LegalizerInfo.h.
References llvm::LegalizeActions::Custom.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and custom().
fallback()
LegalizeRuleSet & llvm::LegalizeRuleSet::fallback () inline
Fallback on the previous implementation.
This should only be used while porting a rule.
Definition at line 876 of file LegalizerInfo.h.
References llvm::LegalizeActions::UseLegacyRules.
fewerElementsIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::fewerElementsIf (LegalityPredicate Predicate, LegalizeMutation Mutation) inline
Remove elements to reach the type selected by the mutation if the predicate is true.
Definition at line 624 of file LegalizerInfo.h.
References llvm::LegalizeActions::FewerElements, and Mutation.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
getAlias()
unsigned llvm::LegalizeRuleSet::getAlias () const inline
Definition at line 451 of file LegalizerInfo.h.
isAliasedByAnother()
bool llvm::LegalizeRuleSet::isAliasedByAnother () inline
Definition at line 443 of file LegalizerInfo.h.
legalFor() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::legalFor (std::initializer_list< LLT > Types) inline
The instruction is legal when type index 0 is any type in the given list.
Definition at line 461 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), and llvm::MipsLegalizerInfo::MipsLegalizerInfo().
legalFor() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::legalFor (std::initializer_list< std::pair< LLT, LLT > > Types) inline
The instruction is legal when type indexes 0 and 1 is any type pair in the given list.
Definition at line 466 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
legalForCartesianProduct() [1/3]
LegalizeRuleSet & llvm::LegalizeRuleSet::legalForCartesianProduct (std::initializer_list< LLT > Types) inline
The instruction is legal when type indexes 0 and 1 are both in the given list.
That is, the type pair is in the cartesian product of the list.
Definition at line 480 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), and llvm::MipsLegalizerInfo::MipsLegalizerInfo().
legalForCartesianProduct() [2/3]
LegalizeRuleSet & llvm::LegalizeRuleSet::legalForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1) inline
The instruction is legal when type indexes 0 and 1 are both their respective lists.
Definition at line 485 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
legalForCartesianProduct() [3/3]
LegalizeRuleSet & llvm::LegalizeRuleSet::legalForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1, std::initializer_list< LLT > Types2) inline
The instruction is legal when type indexes 0, 1, and 2 are both their respective lists.
Definition at line 491 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
legalForTypesWithMemDesc()
LegalizeRuleSet & llvm::LegalizeRuleSet::legalForTypesWithMemDesc (std::initializer_list< LegalityPredicates::TypePairAndMemDesc > TypesAndMemDesc) inline
The instruction is legal when type indexes 0 and 1 along with the memory size and minimum alignment is any type and size tuple in the given list.
Definition at line 471 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal, and llvm::LegalityPredicates::typePairAndMemDescInSet().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and llvm::ARMLegalizerInfo::ARMLegalizerInfo().
legalIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::legalIf (LegalityPredicate Predicate) inline
The instruction is legal if predicate is true.
Definition at line 454 of file LegalizerInfo.h.
References llvm::LegalizeActions::Legal.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
libcallFor() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::libcallFor (std::initializer_list< LLT > Types) inline
Definition at line 577 of file LegalizerInfo.h.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), and llvm::MipsLegalizerInfo::MipsLegalizerInfo().
libcallFor() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::libcallFor (std::initializer_list< std::pair< LLT, LLT > > Types) inline
Definition at line 581 of file LegalizerInfo.h.
libcallForCartesianProduct() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::libcallForCartesianProduct (std::initializer_list< LLT > Types) inline
Definition at line 585 of file LegalizerInfo.h.
Referenced by llvm::MipsLegalizerInfo::MipsLegalizerInfo().
libcallForCartesianProduct() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::libcallForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1) inline
Definition at line 589 of file LegalizerInfo.h.
libcallIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::libcallIf (LegalityPredicate Predicate) inline
Like legalIf, but for the Libcall action.
Definition at line 571 of file LegalizerInfo.h.
lower()
LegalizeRuleSet & llvm::LegalizeRuleSet::lower () inline
The instruction is lowered.
Definition at line 505 of file LegalizerInfo.h.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
lowerFor() [1/4]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerFor (std::initializer_list< LLT > Types) inline
The instruction is lowered when type index 0 is any type in the given list.
Keep type index 0 as the same type.
Definition at line 531 of file LegalizerInfo.h.
References llvm::LegalizeMutations::changeTo().
Referenced by llvm::ARMLegalizerInfo::ARMLegalizerInfo().
lowerFor() [2/4]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerFor (std::initializer_list< LLT > Types, LegalizeMutation Mutation) inline
The instruction is lowered when type index 0 is any type in the given list.
Definition at line 537 of file LegalizerInfo.h.
References Mutation.
lowerFor() [3/4]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerFor (std::initializer_list< std::pair< LLT, LLT > > Types) inline
The instruction is lowered when type indexes 0 and 1 is any type pair in the given list.
Keep type index 0 as the same type.
Definition at line 543 of file LegalizerInfo.h.
References llvm::LegalizeMutations::changeTo().
lowerFor() [4/4]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerFor (std::initializer_list< std::pair< LLT, LLT > > Types, LegalizeMutation Mutation) inline
The instruction is lowered when type indexes 0 and 1 is any type pair in the given list.
Definition at line 549 of file LegalizerInfo.h.
References Mutation.
lowerForCartesianProduct() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1) inline
The instruction is lowered when type indexes 0 and 1 are both in their respective lists.
Definition at line 555 of file LegalizerInfo.h.
lowerForCartesianProduct() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerForCartesianProduct (std::initializer_list< LLT > Types0, std::initializer_list< LLT > Types1, std::initializer_list< LLT > Types2) inline
The instruction is lowered when when type indexes 0, 1, and 2 are all in their respective lists.
Definition at line 562 of file LegalizerInfo.h.
lowerIf() [1/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerIf (LegalityPredicate Predicate) inline
The instruction is lowered if predicate is true.
Keep type index 0 as the same type.
Definition at line 514 of file LegalizerInfo.h.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo().
lowerIf() [2/2]
LegalizeRuleSet & llvm::LegalizeRuleSet::lowerIf (LegalityPredicate Predicate, LegalizeMutation Mutation) inline
The instruction is lowered if predicate is true.
Definition at line 522 of file LegalizerInfo.h.
References Mutation.
maxScalar()
LegalizeRuleSet & llvm::LegalizeRuleSet::maxScalar (unsigned TypeIdx, const LLT & Ty) inline
Ensure the scalar is at most as wide as Ty.
Definition at line 745 of file LegalizerInfo.h.
References llvm::LLT::getSizeInBits(), and llvm::LegalizeActions::NarrowScalar.
Referenced by llvm::ARMLegalizerInfo::ARMLegalizerInfo(), and clampScalar().
maxScalarIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::maxScalarIf (LegalityPredicate Predicate, unsigned TypeIdx, const LLT & Ty) inline
Conditionally limit the maximum size of the scalar.
For example, when the maximum size of one type depends on the size of another such as extracting N bits from an M bit container.
Definition at line 756 of file LegalizerInfo.h.
References llvm::LLT::getSizeInBits(), and llvm::LegalizeActions::NarrowScalar.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo().
maxScalarOrElt()
LegalizeRuleSet & llvm::LegalizeRuleSet::maxScalarOrElt (unsigned TypeIdx, const LLT & Ty) inline
Ensure the scalar is at most as wide as Ty.
Definition at line 736 of file LegalizerInfo.h.
References llvm::LLT::getScalarSizeInBits(), and llvm::LegalizeActions::NarrowScalar.
Referenced by clampScalarOrElt().
minScalar()
LegalizeRuleSet & llvm::LegalizeRuleSet::minScalar (unsigned TypeIdx, const LLT & Ty) inline
Ensure the scalar is at least as wide as Ty.
Definition at line 727 of file LegalizerInfo.h.
References llvm::LLT::getSizeInBits(), and llvm::LegalizeActions::WidenScalar.
Referenced by clampScalar(), and llvm::MipsLegalizerInfo::MipsLegalizerInfo().
minScalarEltSameAsIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::minScalarEltSameAsIf (LegalityPredicate Predicate, unsigned TypeIdx, unsigned LargeTypeIdx) inline
Conditionally widen the scalar or elt to match the size of another.
Definition at line 797 of file LegalizerInfo.h.
References llvm::LegalityQuery::Types, and widenScalarIf().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo().
minScalarOrElt()
LegalizeRuleSet & llvm::LegalizeRuleSet::minScalarOrElt (unsigned TypeIdx, const LLT & Ty) inline
Ensure the scalar or element is at least as wide as Ty.
Definition at line 707 of file LegalizerInfo.h.
References llvm::LLT::getScalarSizeInBits(), and llvm::LegalizeActions::WidenScalar.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), and clampScalarOrElt().
minScalarOrEltIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::minScalarOrEltIf (LegalityPredicate Predicate, unsigned TypeIdx, const LLT & Ty) inline
Ensure the scalar or element is at least as wide as Ty.
Definition at line 716 of file LegalizerInfo.h.
References llvm::LLT::getScalarSizeInBits(), and llvm::LegalizeActions::WidenScalar.
minScalarSameAs()
LegalizeRuleSet & llvm::LegalizeRuleSet::minScalarSameAs (unsigned TypeIdx, unsigned LargeTypeIdx) inline
Widen the scalar to match the size of another.
Definition at line 782 of file LegalizerInfo.h.
References llvm::LegalityQuery::Types, and widenScalarIf().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
moreElementsIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::moreElementsIf (LegalityPredicate Predicate, LegalizeMutation Mutation) inline
Add more elements to reach the type selected by the mutation if the predicate is true.
Definition at line 615 of file LegalizerInfo.h.
References llvm::LegalizeActions::MoreElements, and Mutation.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
moreElementsToNextPow2()
LegalizeRuleSet & llvm::LegalizeRuleSet::moreElementsToNextPow2 (unsigned TypeIdx) inline
Add more elements to the vector to reach the next power of two.
No effect if the type is not a vector or the element count is a power of two.
Definition at line 815 of file LegalizerInfo.h.
References llvm::LegalizeActions::MoreElements, and llvm::LegalizeMutations::moreElementsToNextPow2().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo().
narrowScalar()
LegalizeRuleSet & llvm::LegalizeRuleSet::narrowScalar (unsigned TypeIdx, LegalizeMutation Mutation) inline
Definition at line 694 of file LegalizerInfo.h.
References Mutation, and llvm::LegalizeActions::NarrowScalar.
narrowScalarIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::narrowScalarIf (LegalityPredicate Predicate, LegalizeMutation Mutation) inline
Narrow the scalar to the one selected by the mutation if the predicate is true.
Definition at line 605 of file LegalizerInfo.h.
References Mutation, and llvm::LegalizeActions::NarrowScalar.
scalarize()
LegalizeRuleSet & llvm::LegalizeRuleSet::scalarize (unsigned TypeIdx) inline
Definition at line 700 of file LegalizerInfo.h.
References llvm::LegalizeActions::FewerElements, and llvm::LegalizeMutations::scalarize().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
setIsAliasedByAnother()
void llvm::LegalizeRuleSet::setIsAliasedByAnother () inline
Definition at line 444 of file LegalizerInfo.h.
unsupported()
LegalizeRuleSet & llvm::LegalizeRuleSet::unsupported () inline
The instruction is unsupported.
Definition at line 633 of file LegalizerInfo.h.
References llvm::LegalizeActions::Unsupported.
unsupportedIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::unsupportedIf (LegalityPredicate Predicate) inline
Definition at line 636 of file LegalizerInfo.h.
References llvm::LegalizeActions::Unsupported.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
unsupportedIfMemSizeNotPow2()
LegalizeRuleSet & llvm::LegalizeRuleSet::unsupportedIfMemSizeNotPow2 () inline
Definition at line 639 of file LegalizerInfo.h.
References llvm::LegalityPredicates::memSizeInBytesNotPow2(), and llvm::LegalizeActions::Unsupported.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
verifyTypeIdxsCoverage()
bool LegalizeRuleSet::verifyTypeIdxsCoverage (unsigned NumTypeIdxs) const
Check if there is no type index which is obviously not handled by the LegalizeRuleSet in any way at all.
Precondition
Type indices of the opcode form a dense [0, NumTypeIdxs) set.
Definition at line 204 of file LegalizerInfo.cpp.
References llvm::dbgs(), llvm::SmallBitVector::find_first_unset(), and LLVM_DEBUG.
Referenced by llvm::LegalizerInfo::verify().
widenScalarIf()
LegalizeRuleSet & llvm::LegalizeRuleSet::widenScalarIf (LegalityPredicate Predicate, LegalizeMutation Mutation) inline
Widen the scalar to the one selected by the mutation if the predicate is true.
Definition at line 596 of file LegalizerInfo.h.
References Mutation, and llvm::LegalizeActions::WidenScalar.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), minScalarEltSameAsIf(), and minScalarSameAs().
widenScalarOrEltToNextPow2()
LegalizeRuleSet & llvm::LegalizeRuleSet::widenScalarOrEltToNextPow2 (unsigned TypeIdx, unsigned MinSize = 0) inline
Widen the scalar or vector element type to the next power of two that is at least MinSize.
No effect if the scalar size is a power of two.
Definition at line 686 of file LegalizerInfo.h.
References llvm::LegalizeActions::WidenScalar, and llvm::LegalizeMutations::widenScalarOrEltToNextPow2().
widenScalarToNextPow2()
LegalizeRuleSet & llvm::LegalizeRuleSet::widenScalarToNextPow2 (unsigned TypeIdx, unsigned MinSize = 0) inline
Widen the scalar to the next power of two that is at least MinSize.
No effect if the type is not a scalar or is a power of two.
Definition at line 676 of file LegalizerInfo.h.
References llvm::LegalizeActions::WidenScalar, and llvm::LegalizeMutations::widenScalarOrEltToNextPow2().
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), and llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/LegalizerInfo.h
lib/CodeGen/GlobalISel/LegalizerInfo.cpp