LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Constant * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFSub (Constant *LHS, Constant *RHS) const
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFMul (Constant *LHS, Constant *RHS) const
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const
Constant * CreateURem (Constant *LHS, Constant *RHS) const
Constant * CreateSRem (Constant *LHS, Constant *RHS) const
Constant * CreateFRem (Constant *LHS, Constant *RHS) const
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAnd (Constant *LHS, Constant *RHS) const
Constant * CreateOr (Constant *LHS, Constant *RHS) const
Constant * CreateXor (Constant *LHS, Constant *RHS) const
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFNeg (Constant *C) const
Constant * CreateNot (Constant *C) const
Constant * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const
Constant * CreatePointerCast (Constant *C, Type *DestTy) const
Constant * CreateFPCast (Constant *C, Type *DestTy) const
Constant * CreateBitCast (Constant *C, Type *DestTy) const
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const
Constant * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateSelect (Constant *C, Constant *True, Constant *False) const
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const
Constant * CreateShuffleVector (Constant *V1, Constant *V2, Constant *Mask) const
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 31 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 42 of file TargetFolder.h.
Member Function Documentation
CreateAdd()
Constant * llvm::TargetFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 48 of file TargetFolder.h.
References llvm::ConstantExpr::getAdd().
Referenced by llvm::NoFolder::CreateAdd(), CreateAdd(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateAnd()
Constant * llvm::TargetFolder::CreateAnd (Constant * LHS, Constant * RHS) const inline
Definition at line 97 of file TargetFolder.h.
References llvm::ConstantExpr::getAnd().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), canonicalizeICmpBool(), llvm::NoFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), createAndInstr(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitURem(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
CreateAShr()
Constant * llvm::TargetFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 94 of file TargetFolder.h.
References llvm::ConstantExpr::getAShr().
Referenced by llvm::NoFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitXor().
CreateBinOp()
Constant * llvm::TargetFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline
Definition at line 107 of file TargetFolder.h.
References llvm::IntervalMapImpl::NodeRef::get().
CreateBitCast()
Constant * llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const inline
Definition at line 192 of file TargetFolder.h.
References C, and CreateCast().
CreateCast()
Constant * llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline
Definition at line 170 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Constant * llvm::TargetFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline
Definition at line 245 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement(), and Idx.
CreateExtractValue()
Constant * llvm::TargetFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline
Definition at line 259 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractValue().
CreateFAdd()
Constant * llvm::TargetFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline
Definition at line 52 of file TargetFolder.h.
References llvm::ConstantExpr::getFAdd().
Referenced by CreateAdd(), llvm::NoFolder::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAddFMF(), and llvm::InstCombiner::visitCallInst().
CreateFCmp()
Constant * llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 232 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
CreateFDiv()
Constant * llvm::TargetFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline
Definition at line 75 of file TargetFolder.h.
References llvm::ConstantExpr::getFDiv().
Referenced by llvm::NoFolder::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDivFMF(), llvm::hoistRegion(), and llvm::InstCombiner::visitCallInst().
CreateFMul()
Constant * llvm::TargetFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline
Definition at line 66 of file TargetFolder.h.
References llvm::ConstantExpr::getFMul().
Referenced by llvm::NoFolder::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), CreateMul(), llvm::hoistRegion(), and llvm::InstCombiner::visitCallInst().
CreateFNeg()
Constant * llvm::TargetFolder::CreateFNeg (Constant * C) const inline
Definition at line 120 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFNeg().
CreateFPCast()
Constant * llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const inline
Definition at line 187 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFPCast().
CreateFRem()
Constant * llvm::TargetFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline
Definition at line 84 of file TargetFolder.h.
References llvm::ConstantExpr::getFRem().
Referenced by llvm::NoFolder::CreateFRem(), llvm::IRBuilder< T, Inserter >::CreateFRem(), and llvm::IRBuilder< T, Inserter >::CreateFRemFMF().
CreateFSub()
Constant * llvm::TargetFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline
Definition at line 59 of file TargetFolder.h.
References llvm::ConstantExpr::getFSub().
Referenced by llvm::NoFolder::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateFSub(), and llvm::IRBuilder< T, Inserter >::CreateFSubFMF().
CreateGetElementPtr() [1/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline
Definition at line 135 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [2/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline
Definition at line 145 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [3/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 139 of file TargetFolder.h.
References C, llvm::ConstantExpr::getGetElementPtr(), and Idx.
CreateICmp()
Constant * llvm::TargetFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 228 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
CreateInBoundsGetElementPtr() [1/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline
Definition at line 150 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [2/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline
Definition at line 161 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [3/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 154 of file TargetFolder.h.
References C, llvm::ConstantExpr::getInBoundsGetElementPtr(), and Idx.
CreateInsertElement()
Constant * llvm::TargetFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline
Definition at line 249 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement(), and Idx.
CreateInsertValue()
Constant * llvm::TargetFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline
Definition at line 264 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertValue().
CreateIntCast()
Constant * llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline
Definition at line 176 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getIntegerCast().
CreateIntToPtr()
Constant * llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline
Definition at line 195 of file TargetFolder.h.
References C, and CreateCast().
CreateLShr()
Constant * llvm::TargetFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 91 of file TargetFolder.h.
References llvm::ConstantExpr::getLShr().
Referenced by llvm::NoFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), foldUDivPow2Cst(), foldUDivShl(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateMul()
Constant * llvm::TargetFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 62 of file TargetFolder.h.
References llvm::ConstantExpr::getMul().
Referenced by ConvertShiftToMul(), createMalloc(), llvm::NoFolder::CreateMul(), CreateMul(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitShl().
CreateNeg()
Constant * llvm::TargetFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 116 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNeg().
CreateNot()
Constant * llvm::TargetFolder::CreateNot (Constant * C) const inline
Definition at line 123 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNot().
CreateOr()
Constant * llvm::TargetFolder::CreateOr (Constant * LHS, Constant * RHS) const inline
Definition at line 100 of file TargetFolder.h.
References llvm::ConstantExpr::getOr().
Referenced by canonicalizeICmpBool(), llvm::NoFolder::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), visitMaskedMerge(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitXor().
CreatePointerBitCastOrAddrSpaceCast()
Constant * llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline
Definition at line 217 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant * llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline
Definition at line 182 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant * llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline
Definition at line 198 of file TargetFolder.h.
References C, CreateCast(), and llvm::PtrToIntOperator::PtrToInt.
CreateSDiv()
Constant * llvm::TargetFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 72 of file TargetFolder.h.
References llvm::ConstantExpr::getSDiv().
Referenced by llvm::NoFolder::CreateSDiv(), llvm::IRBuilder< T, Inserter >::CreateSDiv(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitSub().
CreateSelect()
Constant * llvm::TargetFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const inline
Definition at line 241 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getSelect().
CreateSExtOrBitCast()
Constant * llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 206 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getSExtOrBitCast().
CreateShl()
Constant * llvm::TargetFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 87 of file TargetFolder.h.
References llvm::ConstantExpr::getShl().
Referenced by llvm::NoFolder::CreateShl(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitSub().
CreateShuffleVector()
Constant * llvm::TargetFolder::CreateShuffleVector (Constant * V1, Constant * V2, Constant * Mask) const inline
Definition at line 254 of file TargetFolder.h.
References llvm::ConstantExpr::getShuffleVector().
CreateSRem()
Constant * llvm::TargetFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline
Definition at line 81 of file TargetFolder.h.
References llvm::ConstantExpr::getSRem().
Referenced by llvm::NoFolder::CreateSRem(), and llvm::IRBuilder< T, Inserter >::CreateSRem().
CreateSub()
Constant * llvm::TargetFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 55 of file TargetFolder.h.
References llvm::ConstantExpr::getSub().
Referenced by llvm::NoFolder::CreateSub(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
CreateTruncOrBitCast()
Constant * llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 211 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getTruncOrBitCast().
CreateUDiv()
Constant * llvm::TargetFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 69 of file TargetFolder.h.
References llvm::ConstantExpr::getUDiv().
Referenced by llvm::NoFolder::CreateUDiv(), llvm::IRBuilder< T, Inserter >::CreateUDiv(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitUDiv().
CreateUnOp()
Constant * llvm::TargetFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline
Definition at line 127 of file TargetFolder.h.
References C, and llvm::IntervalMapImpl::NodeRef::get().
CreateURem()
Constant * llvm::TargetFolder::CreateURem (Constant * LHS, Constant * RHS) const inline
Definition at line 78 of file TargetFolder.h.
References llvm::ConstantExpr::getURem().
Referenced by llvm::NoFolder::CreateURem(), llvm::IRBuilder< T, Inserter >::CreateURem(), and llvm::InstCombiner::visitSRem().
CreateXor()
Constant * llvm::TargetFolder::CreateXor (Constant * LHS, Constant * RHS) const inline
Definition at line 103 of file TargetFolder.h.
References llvm::ConstantExpr::getXor().
Referenced by canonicalizeICmpBool(), llvm::NoFolder::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateXor(), foldAndToXor(), foldOrToXor(), sinkNotIntoXor(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), visitMaskedMerge(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
CreateZExtOrBitCast()
Constant * llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 201 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getZExtOrBitCast().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetFolder.h