LLVM: llvm::optional_detail::OptionalStorage< T, bool > Class Template Reference
llvm::optional_detail::OptionalStorage< T, bool > Class Template Reference
Storage for any type.
#include "llvm/ADT/Optional.h"
Public Member Functions
~OptionalStorage ()
OptionalStorage () noexcept
OptionalStorage (OptionalStorage const &other)
OptionalStorage (OptionalStorage &&other)
template<class... Args>
OptionalStorage (in_place_t, Args &&... args)
void reset () noexcept
bool hasValue () const noexcept
T & getValue () LLVM_LVALUE_FUNCTION noexcept
T const & getValue () const LLVM_LVALUE_FUNCTION noexcept
template<class... Args>
void emplace (Args &&... args)
OptionalStorage & operator= (T const &y)
OptionalStorage & operator= (T &&y)
OptionalStorage & operator= (OptionalStorage const &other)
OptionalStorage & operator= (OptionalStorage &&other)
Detailed Description
template<typename T, bool = is_trivially_copyable<T>::value>
class llvm::optional_detail::OptionalStorage< T, bool >
Storage for any type.
Definition at line 36 of file Optional.h.
Constructor & Destructor Documentation
~OptionalStorage()
template<typename T , bool = is_trivially_copyable<T>::value> llvm::optional_detail::OptionalStorage< T, bool >::~OptionalStorage () inline
Definition at line 44 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::reset().
OptionalStorage() [1/4]
template<typename T , bool = is_trivially_copyable<T>::value> llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage () inline noexcept
Definition at line 46 of file Optional.h.
OptionalStorage() [2/4]
template<typename T , bool = is_trivially_copyable<T>::value> llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (OptionalStorage< T, bool > const & other) inline
Definition at line 48 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::emplace(), llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), and llvm::optional_detail::OptionalStorage< T, bool >::value.
OptionalStorage() [3/4]
template<typename T , bool = is_trivially_copyable<T>::value> llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (OptionalStorage< T, bool > && other) inline
Definition at line 53 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::emplace().
OptionalStorage() [4/4]
template<typename T , bool = is_trivially_copyable<T>::value> template<class... Args> llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (in_place_t , Args &&... args) inline explicit
Definition at line 60 of file Optional.h.
Member Function Documentation
emplace()
template<typename T , bool = is_trivially_copyable<T>::value> template<class... Args> void llvm::optional_detail::OptionalStorage< T, bool >::emplace (Args &&... args) inline
Definition at line 87 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::reset(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
Referenced by llvm::Optional< T >::emplace(), and llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage().
getValue() [1/2]
template<typename T , bool = is_trivially_copyable<T>::value> T const & llvm::optional_detail::OptionalStorage< T, bool >::getValue () const inline noexcept
Definition at line 76 of file Optional.h.
References assert(), and llvm::optional_detail::OptionalStorage< T, bool >::value.
getValue() [2/2]
template<typename T , bool = is_trivially_copyable<T>::value> T & llvm::optional_detail::OptionalStorage< T, bool >::getValue () inline noexcept
Definition at line 72 of file Optional.h.
References assert(), and llvm::optional_detail::OptionalStorage< T, bool >::value.
Referenced by llvm::Optional< T >::getPointer(), and llvm::Optional< T >::getValue().
hasValue()
template<typename T , bool = is_trivially_copyable<T>::value> bool llvm::optional_detail::OptionalStorage< T, bool >::hasValue () const inline noexcept
Definition at line 70 of file Optional.h.
Referenced by llvm::Optional< T >::hasValue(), llvm::optional_detail::OptionalStorage< T, bool >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), and llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage().
operator=() [1/4]
template<typename T , bool = is_trivially_copyable<T>::value> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (OptionalStorage< T, bool > && other) inline
Definition at line 126 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), llvm::optional_detail::OptionalStorage< T, bool >::reset(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
operator=() [2/4]
template<typename T , bool = is_trivially_copyable<T>::value> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (OptionalStorage< T, bool > const & other) inline
Definition at line 112 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), llvm::optional_detail::OptionalStorage< T, bool >::reset(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
operator=() [3/4]
template<typename T , bool = is_trivially_copyable<T>::value> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (T && y) inline
Definition at line 102 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
operator=() [4/4]
template<typename T , bool = is_trivially_copyable<T>::value> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (T const & y) inline
Definition at line 93 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue(), T, and llvm::optional_detail::OptionalStorage< T, bool >::value.
reset()
template<typename T , bool = is_trivially_copyable<T>::value> void llvm::optional_detail::OptionalStorage< T, bool >::reset () inline noexcept
Definition at line 63 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::value.
Referenced by llvm::optional_detail::OptionalStorage< T, bool >::emplace(), llvm::optional_detail::OptionalStorage< T, true >::emplace(), llvm::optional_detail::OptionalStorage< T, bool >::operator=(), llvm::Optional< T >::reset(), and llvm::optional_detail::OptionalStorage< T, bool >::~OptionalStorage().
Member Data Documentation
empty
template<typename T , bool = is_trivially_copyable<T>::value> char llvm::optional_detail::OptionalStorage< T, bool >::empty
Definition at line 38 of file Optional.h.
value
template<typename T , bool = is_trivially_copyable<T>::value> T llvm::optional_detail::OptionalStorage< T, bool >::value
Definition at line 39 of file Optional.h.
Referenced by llvm::optional_detail::OptionalStorage< T, bool >::emplace(), llvm::optional_detail::OptionalStorage< T, true >::emplace(), llvm::optional_detail::OptionalStorage< T, bool >::getValue(), llvm::optional_detail::OptionalStorage< T, true >::getValue(), llvm::optional_detail::OptionalStorage< T, bool >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage(), llvm::optional_detail::OptionalStorage< T, bool >::reset(), and llvm::optional_detail::OptionalStorage< T, true >::reset().
The documentation for this class was generated from the following file:
include/llvm/ADT/Optional.h