LLVM: llvm::DWARFUnitIndex Class Reference
llvm::DWARFUnitIndex Class Reference
#include "llvm/DebugInfo/DWARF/DWARFUnitIndex.h"
Classes
class Entry
Public Member Functions
DWARFUnitIndex (DWARFSectionKind InfoColumnKind)
operator bool () const
bool parse (DataExtractor IndexData)
void dump (raw_ostream &OS) const
const Entry * getFromOffset (uint32_t Offset) const
const Entry * getFromHash (uint64_t Offset) const
ArrayRef< DWARFSectionKind > getColumnKinds () const
ArrayRef< Entry > getRows () const
Detailed Description
Definition at line 33 of file DWARFUnitIndex.h.
Constructor & Destructor Documentation
DWARFUnitIndex()
llvm::DWARFUnitIndex::DWARFUnitIndex (DWARFSectionKind InfoColumnKind) inline
Definition at line 83 of file DWARFUnitIndex.h.
Member Function Documentation
dump()
void DWARFUnitIndex::dump (raw_ostream & OS) const
Definition at line 124 of file DWARFUnitIndex.cpp.
References llvm::format(), and llvm::left_justify().
Referenced by llvm::DWARFContext::dump().
getColumnKinds()
ArrayRef< DWARFSectionKind > llvm::DWARFUnitIndex::getColumnKinds () const inline
Definition at line 94 of file DWARFUnitIndex.h.
References llvm::makeArrayRef().
getFromHash()
const DWARFUnitIndex::Entry * DWARFUnitIndex::getFromHash (uint64_t Offset) const
Definition at line 188 of file DWARFUnitIndex.cpp.
References getSignature(), and H.
getFromOffset()
const DWARFUnitIndex::Entry * DWARFUnitIndex::getFromOffset (uint32_t Offset) const
Definition at line 165 of file DWARFUnitIndex.cpp.
References E, I, llvm::partition_point(), and llvm::sort().
getRows()
ArrayRef< Entry > llvm::DWARFUnitIndex::getRows () const inline
Definition at line 98 of file DWARFUnitIndex.h.
References llvm::makeArrayRef().
operator bool()
llvm::DWARFUnitIndex::operator bool () const inline explicit
Definition at line 86 of file DWARFUnitIndex.h.
parse()
bool DWARFUnitIndex::parse (DataExtractor IndexData)
Definition at line 35 of file DWARFUnitIndex.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnitIndex.h
lib/DebugInfo/DWARF/DWARFUnitIndex.cpp