LLVM: llvm::CondOpInit Class Reference
llvm::CondOpInit Class Reference final
!cond(condition_1: value1, ... , condition_n: value) Selects the first value for which condition is true.
#include "llvm/TableGen/Record.h"
Public Types
using const_case_iterator = SmallVectorImpl< Init * >::const_iterator
using const_val_iterator = SmallVectorImpl< Init * >::const_iterator
Public Member Functions
CondOpInit (const CondOpInit &)=delete
CondOpInit & operator= (const CondOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
RecTy * getValType () const
unsigned getNumConds () const
Init * getCond (unsigned Num) const
Init * getVal (unsigned Num) const
ArrayRef< Init * > getConds () const
ArrayRef< Init * > getVals () const
Init * Fold (Record *CurRec) const
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
bool isComplete () const override
This virtual method should be overridden by values that may not be completely specified yet.
std::string getAsString () const override
Convert this value to a string form.
const_case_iterator arg_begin () const
const_case_iterator arg_end () const
size_t case_size () const
bool case_empty () const
const_val_iterator name_begin () const
const_val_iterator name_end () const
size_t val_size () const
bool val_empty () const
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< CondOpInit, Init * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
Static Public Member Functions
static bool classof (const Init *I)
static CondOpInit * get (ArrayRef< Init * > C, ArrayRef< Init * > V, RecTy *Type)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< CondOpInit, Init * >
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!cond(condition_1: value1, ... , condition_n: value) Selects the first value for which condition is true.
Otherwise reports an error.
Definition at line 923 of file Record.h.
Member Typedef Documentation
const_case_iterator
using llvm::CondOpInit::const_case_iterator = SmallVectorImpl<Init*>::const_iterator
Definition at line 979 of file Record.h.
const_val_iterator
using llvm::CondOpInit::const_val_iterator = SmallVectorImpl<Init*>::const_iterator
Definition at line 980 of file Record.h.
Constructor & Destructor Documentation
CondOpInit()
llvm::CondOpInit::CondOpInit (const CondOpInit &) delete
Member Function Documentation
arg_begin()
const_case_iterator llvm::CondOpInit::arg_begin () const inline
Definition at line 982 of file Record.h.
References getConds().
arg_end()
const_case_iterator llvm::CondOpInit::arg_end () const inline
Definition at line 983 of file Record.h.
References getConds().
case_empty()
bool llvm::CondOpInit::case_empty () const inline
Definition at line 986 of file Record.h.
case_size()
size_t llvm::CondOpInit::case_size () const inline
Definition at line 985 of file Record.h.
classof()
static bool llvm::CondOpInit::classof (const Init * I) inline static
Definition at line 940 of file Record.h.
References I, and llvm::Init::IK_CondOpInit.
Fold()
Init * CondOpInit::Fold (Record * CurRec) const
Definition at line 1818 of file Record.cpp.
References llvm::Init::convertInitializerTo(), llvm::IntRecTy::get(), getCond(), llvm::Record::getLoc(), llvm::Record::getName(), getVal(), getValType(), and llvm::PrintFatalError().
get()
CondOpInit * CondOpInit::get (ArrayRef< Init * > C, ArrayRef< Init * > V, RecTy * Type) static
Definition at line 1770 of file Record.cpp.
References Allocator, assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), I, llvm::FoldingSetImpl< T >::InsertNode(), ProfileCondOpInit(), and llvm::ArrayRef< T >::size().
getAsString()
std::string CondOpInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1862 of file Record.cpp.
References llvm::Init::getAsString(), getCond(), getNumConds(), and getVal().
getBit()
Init * CondOpInit::getBit (unsigned Bit) const override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1873 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get().
getCond()
Init * llvm::CondOpInit::getCond (unsigned Num) const inline
Definition at line 953 of file Record.h.
References assert().
Referenced by Fold(), and getAsString().
getConds()
ArrayRef< Init * > llvm::CondOpInit::getConds () const inline
Definition at line 963 of file Record.h.
References llvm::makeArrayRef().
Referenced by arg_begin(), arg_end(), isComplete(), isConcrete(), and resolveReferences().
getNumConds()
unsigned llvm::CondOpInit::getNumConds () const inline
Definition at line 951 of file Record.h.
Referenced by getAsString().
getVal()
Init * llvm::CondOpInit::getVal (unsigned Num) const inline
Definition at line 958 of file Record.h.
References assert().
Referenced by Fold(), and getAsString().
getVals()
ArrayRef< Init * > llvm::CondOpInit::getVals () const inline
Definition at line 967 of file Record.h.
References llvm::makeArrayRef().
Referenced by isComplete(), isConcrete(), name_begin(), name_end(), and resolveReferences().
getValType()
RecTy * llvm::CondOpInit::getValType () const inline
Definition at line 949 of file Record.h.
Referenced by Fold(), and resolveReferences().
isComplete()
bool CondOpInit::isComplete () const override virtual
This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented from llvm::Init.
Definition at line 1850 of file Record.cpp.
References getConds(), and getVals().
isConcrete()
bool CondOpInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 1838 of file Record.cpp.
References getConds(), and getVals().
name_begin()
const_val_iterator llvm::CondOpInit::name_begin () const inline
Definition at line 988 of file Record.h.
References getVals().
name_end()
const_val_iterator llvm::CondOpInit::name_end () const inline
Definition at line 989 of file Record.h.
References getVals().
operator=()
CondOpInit & llvm::CondOpInit::operator= (const CondOpInit &) delete
Profile()
void CondOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1762 of file Record.cpp.
References llvm::makeArrayRef(), and ProfileCondOpInit().
resolveReferences()
Init * CondOpInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1795 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), getConds(), getVals(), getValType(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Init::resolveReferences().
val_empty()
bool llvm::CondOpInit::val_empty () const inline
Definition at line 992 of file Record.h.
val_size()
size_t llvm::CondOpInit::val_size () const inline
Definition at line 991 of file Record.h.
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp