LLVM: llvm::InstCombiner Class Reference
llvm::InstCombiner Class Reference
The core instruction combiner logic.
#include "Transforms/InstCombine/InstCombineInternal.h"
Public Types
using BuilderTy = IRBuilder< TargetFolder, IRBuilderCallbackInserter >
An IRBuilder that automatically inserts new instructions into the worklist.
Public Member Functions
InstCombiner (InstCombineWorklist &Worklist, BuilderTy &Builder, bool MinimizeSize, bool ExpensiveCombines, AliasAnalysis *AA, AssumptionCache &AC, TargetLibraryInfo &TLI, DominatorTree &DT, OptimizationRemarkEmitter &ORE, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, const DataLayout &DL, LoopInfo *LI)
bool run ()
Run the combiner over the entire worklist until it is empty.
AssumptionCache & getAssumptionCache () const
const DataLayout & getDataLayout () const
DominatorTree & getDominatorTree () const
LoopInfo * getLoopInfo () const
TargetLibraryInfo & getTargetLibraryInfo () const
Instruction * visitFNeg (UnaryOperator &I)
Instruction * visitAdd (BinaryOperator &I)
Instruction * visitFAdd (BinaryOperator &I)
Value * OptimizePointerDifference (Value *LHS, Value *RHS, Type *Ty)
Optimize pointer differences into the same array into a size.
Instruction * visitSub (BinaryOperator &I)
Instruction * visitFSub (BinaryOperator &I)
Instruction * visitMul (BinaryOperator &I)
Instruction * visitFMul (BinaryOperator &I)
Instruction * visitURem (BinaryOperator &I)
Instruction * visitSRem (BinaryOperator &I)
Instruction * visitFRem (BinaryOperator &I)
bool simplifyDivRemOfSelectWithZeroOp (BinaryOperator &I)
Fold a divide or remainder with a select instruction divisor when one of the select operands is zero.
Instruction * commonRemTransforms (BinaryOperator &I)
Instruction * commonIRemTransforms (BinaryOperator &I)
This function implements the transforms common to both integer remainder instructions (urem and srem).
Instruction * commonDivTransforms (BinaryOperator &I)
Instruction * commonIDivTransforms (BinaryOperator &I)
This function implements the transforms common to both integer division instructions (udiv and sdiv).
Instruction * visitUDiv (BinaryOperator &I)
Instruction * visitSDiv (BinaryOperator &I)
Instruction * visitFDiv (BinaryOperator &I)
Value * simplifyRangeCheck (ICmpInst *Cmp0, ICmpInst *Cmp1, bool Inverted)
Try to fold a signed range checked with lower bound 0 to an unsigned icmp.
Instruction * visitAnd (BinaryOperator &I)
Instruction * visitOr (BinaryOperator &I)
Instruction * visitXor (BinaryOperator &I)
Instruction * visitShl (BinaryOperator &I)
Instruction * visitAShr (BinaryOperator &I)
Instruction * visitLShr (BinaryOperator &I)
Instruction * commonShiftTransforms (BinaryOperator &I)
Instruction * visitFCmpInst (FCmpInst &I)
Instruction * visitICmpInst (ICmpInst &I)
Instruction * FoldShiftByConstant (Value *Op0, Constant *Op1, BinaryOperator &I)
Instruction * commonCastTransforms (CastInst &CI)
Implement the transforms common to all CastInst visitors.
Instruction * commonPointerCastTransforms (CastInst &CI)
Implement the transforms for cast of pointer (bitcast/ptrtoint)
Instruction * visitTrunc (TruncInst &CI)
Instruction * visitZExt (ZExtInst &CI)
Instruction * visitSExt (SExtInst &CI)
Instruction * visitFPTrunc (FPTruncInst &CI)
Instruction * visitFPExt (CastInst &CI)
Instruction * visitFPToUI (FPToUIInst &FI)
Instruction * visitFPToSI (FPToSIInst &FI)
Instruction * visitUIToFP (CastInst &CI)
Instruction * visitSIToFP (CastInst &CI)
Instruction * visitPtrToInt (PtrToIntInst &CI)
Instruction * visitIntToPtr (IntToPtrInst &CI)
Instruction * visitBitCast (BitCastInst &CI)
Instruction * visitAddrSpaceCast (AddrSpaceCastInst &CI)
Instruction * FoldItoFPtoI (Instruction &FI)
Instruction * visitSelectInst (SelectInst &SI)
Instruction * visitCallInst (CallInst &CI)
CallInst simplification.
Instruction * visitInvokeInst (InvokeInst &II)
Instruction * visitCallBrInst (CallBrInst &CBI)
Instruction * SliceUpIllegalIntegerPHI (PHINode &PN)
This is an integer PHI and we know that it has an illegal type: see if it is only used by trunc or trunc(lshr) operations.
Instruction * visitPHINode (PHINode &PN)
Instruction * visitGetElementPtrInst (GetElementPtrInst &GEP)
Instruction * visitAllocaInst (AllocaInst &AI)
Instruction * visitAllocSite (Instruction &FI)
Instruction * visitFree (CallInst &FI)
Instruction * visitLoadInst (LoadInst &LI)
Instruction * visitStoreInst (StoreInst &SI)
Instruction * visitAtomicRMWInst (AtomicRMWInst &SI)
Instruction * visitBranchInst (BranchInst &BI)
Instruction * visitFenceInst (FenceInst &FI)
Instruction * visitSwitchInst (SwitchInst &SI)
Instruction * visitReturnInst (ReturnInst &RI)
Instruction * visitInsertValueInst (InsertValueInst &IV)
Try to find redundant insertvalue instructions, like the following ones: %0 = insertvalue { i8, i32 } undef, i8 x, 0 %1 = insertvalue { i8, i32 } %0, i8 y, 0 Here the second instruction inserts values at the same indices, as the first one, making the first one redundant.
Instruction * visitInsertElementInst (InsertElementInst &IE)
Instruction * visitExtractElementInst (ExtractElementInst &EI)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &SVI)
Instruction * visitExtractValueInst (ExtractValueInst &EV)
Instruction * visitLandingPadInst (LandingPadInst &LI)
Instruction * visitVAStartInst (VAStartInst &I)
Instruction * visitVACopyInst (VACopyInst &I)
Instruction * visitInstruction (Instruction &I)
Specify what to return for unhandled instructions.
bool dominatesAllUses (const Instruction *DI, const Instruction *UI, const BasicBlock *DB) const
True when DB dominates all uses of DI except UI.
bool replacedSelectWithOperand (SelectInst *SI, const ICmpInst *Icmp, const unsigned SIOpd)
Try to replace select with select operand SIOpd in SI-ICmp sequence.
bool replacePointer (Instruction &I, Value *V)
Try to replace instruction I with value V which are pointers in different address space.
Instruction * InsertNewInstBefore (Instruction *New, Instruction &Old)
Inserts an instruction New before instruction Old.
Instruction * InsertNewInstWith (Instruction *New, Instruction &Old)
Same as InsertNewInstBefore, but also sets the debug loc.
Instruction * replaceInstUsesWith (Instruction &I, Value *V)
A combiner-aware RAUW-like routine.
Instruction * CreateOverflowTuple (IntrinsicInst *II, Value *Result, Constant *Overflow)
Creates a result tuple for an overflow intrinsic II with a given Result and a constant Overflow value.
void CreateNonTerminatorUnreachable (Instruction *InsertAt)
Create and insert the idiom we use to indicate a block is unreachable without having to rewrite the CFG from within InstCombine.
Instruction * eraseInstFromFunction (Instruction &I)
Combiner aware instruction erasure.
void computeKnownBits (const Value *V, KnownBits &Known, unsigned Depth, const Instruction *CxtI) const
KnownBits computeKnownBits (const Value *V, unsigned Depth, const Instruction *CxtI) const
bool isKnownToBeAPowerOfTwo (const Value *V, bool OrZero=false, unsigned Depth=0, const Instruction *CxtI=nullptr)
bool MaskedValueIsZero (const Value *V, const APInt &Mask, unsigned Depth=0, const Instruction *CxtI=nullptr) const
unsigned ComputeNumSignBits (const Value *Op, unsigned Depth=0, const Instruction *CxtI=nullptr) const
OverflowResult computeOverflowForUnsignedMul (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForSignedMul (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForUnsignedAdd (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForSignedAdd (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForUnsignedSub (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForSignedSub (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflow (Instruction::BinaryOps BinaryOp, bool IsSigned, Value *LHS, Value *RHS, Instruction *CxtI) const
Public Member Functions inherited from llvm::InstVisitor< InstCombiner, Instruction * >
void visit (Iterator Start, Iterator End)
void visit (Module &M)
void visit (Function &F)
void visit (BasicBlock &BB)
void visit (Module *M)
void visit (Function *F)
void visit (BasicBlock *BB)
Instruction * visit (Instruction *I)
Instruction * visit (Instruction &I)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
Instruction * visitICmpInst (ICmpInst &I)
Instruction * visitFCmpInst (FCmpInst &I)
Instruction * visitAllocaInst (AllocaInst &I)
Instruction * visitLoadInst (LoadInst &I)
Instruction * visitStoreInst (StoreInst &I)
Instruction * visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
Instruction * visitAtomicRMWInst (AtomicRMWInst &I)
Instruction * visitFenceInst (FenceInst &I)
Instruction * visitGetElementPtrInst (GetElementPtrInst &I)
Instruction * visitPHINode (PHINode &I)
Instruction * visitTruncInst (TruncInst &I)
Instruction * visitZExtInst (ZExtInst &I)
Instruction * visitSExtInst (SExtInst &I)
Instruction * visitFPTruncInst (FPTruncInst &I)
Instruction * visitFPExtInst (FPExtInst &I)
Instruction * visitFPToUIInst (FPToUIInst &I)
Instruction * visitFPToSIInst (FPToSIInst &I)
Instruction * visitUIToFPInst (UIToFPInst &I)
Instruction * visitSIToFPInst (SIToFPInst &I)
Instruction * visitPtrToIntInst (PtrToIntInst &I)
Instruction * visitIntToPtrInst (IntToPtrInst &I)
Instruction * visitBitCastInst (BitCastInst &I)
Instruction * visitAddrSpaceCastInst (AddrSpaceCastInst &I)
Instruction * visitSelectInst (SelectInst &I)
Instruction * visitVAArgInst (VAArgInst &I)
Instruction * visitExtractElementInst (ExtractElementInst &I)
Instruction * visitInsertElementInst (InsertElementInst &I)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &I)
Instruction * visitExtractValueInst (ExtractValueInst &I)
Instruction * visitInsertValueInst (InsertValueInst &I)
Instruction * visitLandingPadInst (LandingPadInst &I)
Instruction * visitFuncletPadInst (FuncletPadInst &I)
Instruction * visitCleanupPadInst (CleanupPadInst &I)
Instruction * visitCatchPadInst (CatchPadInst &I)
Instruction * visitDbgDeclareInst (DbgDeclareInst &I)
Instruction * visitDbgValueInst (DbgValueInst &I)
Instruction * visitDbgVariableIntrinsic (DbgVariableIntrinsic &I)
Instruction * visitDbgLabelInst (DbgLabelInst &I)
Instruction * visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
Instruction * visitMemSetInst (MemSetInst &I)
Instruction * visitMemCpyInst (MemCpyInst &I)
Instruction * visitMemMoveInst (MemMoveInst &I)
Instruction * visitMemTransferInst (MemTransferInst &I)
Instruction * visitMemIntrinsic (MemIntrinsic &I)
Instruction * visitVAStartInst (VAStartInst &I)
Instruction * visitVAEndInst (VAEndInst &I)
Instruction * visitVACopyInst (VACopyInst &I)
Instruction * visitIntrinsicInst (IntrinsicInst &I)
Instruction * visitCallInst (CallInst &I)
Instruction * visitInvokeInst (InvokeInst &I)
Instruction * visitCallBrInst (CallBrInst &I)
Instruction * visitReturnInst (ReturnInst &I)
Instruction * visitBranchInst (BranchInst &I)
Instruction * visitSwitchInst (SwitchInst &I)
Instruction * visitIndirectBrInst (IndirectBrInst &I)
Instruction * visitResumeInst (ResumeInst &I)
Instruction * visitUnreachableInst (UnreachableInst &I)
Instruction * visitCleanupReturnInst (CleanupReturnInst &I)
Instruction * visitCatchReturnInst (CatchReturnInst &I)
Instruction * visitCatchSwitchInst (CatchSwitchInst &I)
Instruction * visitTerminator (Instruction &I)
Instruction * visitCastInst (CastInst &I)
Instruction * visitUnaryOperator (UnaryOperator &I)
Instruction * visitBinaryOperator (BinaryOperator &I)
Instruction * visitCmpInst (CmpInst &I)
Instruction * visitUnaryInstruction (UnaryInstruction &I)
Instruction * visitCallBase (CallBase &I)
Instruction * visitCallSite (CallSite CS)
void visitInstruction (Instruction &I)
Public Attributes
InstCombineWorklist & Worklist
A worklist of the instructions that need to be simplified.
BuilderTy & Builder
uint64_t MaxArraySizeForCombine
Maximum size of array considered when transforming.
Detailed Description
The core instruction combiner logic.
This class provides both the logic to recursively visit instructions and combine them.
Definition at line 247 of file InstCombineInternal.h.
Member Typedef Documentation
BuilderTy
using llvm::InstCombiner::BuilderTy = IRBuilder<TargetFolder, IRBuilderCallbackInserter>
An IRBuilder that automatically inserts new instructions into the worklist.
Definition at line 256 of file InstCombineInternal.h.
Constructor & Destructor Documentation
InstCombiner()
llvm::InstCombiner::InstCombiner (InstCombineWorklist & Worklist, BuilderTy & Builder, bool MinimizeSize, bool ExpensiveCombines, AliasAnalysis * AA, AssumptionCache & AC, TargetLibraryInfo & TLI, DominatorTree & DT, OptimizationRemarkEmitter & ORE, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, const DataLayout & DL, LoopInfo * LI) inline
Definition at line 285 of file InstCombineInternal.h.
Member Function Documentation
commonCastTransforms()
Instruction * InstCombiner::commonCastTransforms (CastInst & CI)
Implement the transforms common to all CastInst visitors.
Definition at line 260 of file InstCombineCasts.cpp.
References llvm::CastInst::Create(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::replaceAllDbgUsesWith().
Referenced by commonPointerCastTransforms(), visitBitCast(), visitFPExt(), visitFPToSI(), visitFPToUI(), visitFPTrunc(), visitIntToPtr(), visitSExt(), visitSIToFP(), visitTrunc(), visitUIToFP(), and visitZExt().
commonDivTransforms()
Instruction * llvm::InstCombiner::commonDivTransforms (BinaryOperator & I)
commonIDivTransforms()
Instruction * InstCombiner::commonIDivTransforms (BinaryOperator & I)
This function implements the transforms common to both integer division instructions (udiv and sdiv).
It is called by the visitors to those integer division instructions. Common integer divide transforms
Definition at line 640 of file InstCombineMulDivRem.cpp.
References assert(), Builder, llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getBitWidth(), llvm::APInt::getLimitedValue(), llvm::APInt::getOneBitSet(), I, llvm::Type::isIntOrIntVectorTy(), isMultiple(), llvm::APInt::isNullValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::MCBinaryExpr::Mul, multiplyOverflows(), simplifyDivRemOfSelectWithZeroOp(), simplifyValueKnownNonZero(), X, Y, and llvm::Z.
Referenced by visitSDiv(), and visitUDiv().
commonIRemTransforms()
Instruction * InstCombiner::commonIRemTransforms (BinaryOperator & I)
This function implements the transforms common to both integer remainder instructions (urem and srem).
It is called by the visitors to those integer remainder instructions. Common integer remainder transforms
Definition at line 1254 of file InstCombineMulDivRem.cpp.
References I, llvm::APInt::isMinSignedValue(), llvm::APInt::isMinValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), SI, simplifyDivRemOfSelectWithZeroOp(), and simplifyValueKnownNonZero().
Referenced by visitSRem(), and visitURem().
commonPointerCastTransforms()
Instruction * InstCombiner::commonPointerCastTransforms (CastInst & CI)
Implement the transforms for cast of pointer (bitcast/ptrtoint)
Definition at line 1779 of file InstCombineCasts.cpp.
References llvm::InstCombineWorklist::Add(), commonCastTransforms(), GEP, llvm::User::getOperand(), llvm::User::setOperand(), and Worklist.
Referenced by visitAddrSpaceCast(), visitBitCast(), and visitPtrToInt().
commonRemTransforms()
Instruction * llvm::InstCombiner::commonRemTransforms (BinaryOperator & I)
commonShiftTransforms()
Instruction * InstCombiner::commonShiftTransforms (BinaryOperator & I)
Definition at line 68 of file InstCombineShifts.cpp.
References A, assert(), B, Builder, C, llvm::BinaryOperator::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), FoldShiftByConstant(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getType(), I, llvm::isKnownNonNegative(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), reassociateShiftAmtsOfTwoSameDirectionShifts(), and SI.
Referenced by visitAShr(), visitLShr(), and visitShl().
computeKnownBits() [1/2]
void llvm::InstCombiner::computeKnownBits (const Value * V, KnownBits & Known, unsigned Depth, const Instruction * CxtI) const inline
Definition at line 662 of file InstCombineInternal.h.
References llvm::computeKnownBits(), and llvm::Depth.
Referenced by canReplaceGEPIdxWithZero(), foldCtpop(), foldCttzCtlz(), run(), simplifyRangeCheck(), visitAdd(), visitCallInst(), visitReturnInst(), visitSExt(), visitSub(), and visitSwitchInst().
computeKnownBits() [2/2]
KnownBits llvm::InstCombiner::computeKnownBits (const Value * V, unsigned Depth, const Instruction * CxtI) const inline
Definition at line 667 of file InstCombineInternal.h.
References llvm::computeKnownBits(), and llvm::Depth.
ComputeNumSignBits()
unsigned llvm::InstCombiner::ComputeNumSignBits (const Value * Op, unsigned Depth = 0, const Instruction * CxtI = nullptr) const inline
Definition at line 683 of file InstCombineInternal.h.
References llvm::ComputeNumSignBits(), and llvm::Depth.
Referenced by canEvaluateTruncated(), processUGT_ADDCST_ADD(), visitSExt(), and visitShl().
computeOverflow()
OverflowResult InstCombiner::computeOverflow (Instruction::BinaryOps BinaryOp, bool IsSigned, Value * LHS, Value * RHS, Instruction * CxtI) const
Definition at line 4098 of file InstCombineCompares.cpp.
References computeOverflowForSignedAdd(), computeOverflowForSignedMul(), computeOverflowForSignedSub(), computeOverflowForUnsignedAdd(), computeOverflowForUnsignedMul(), computeOverflowForUnsignedSub(), llvm_unreachable, llvm::MCBinaryExpr::Mul, and llvm::AtomicRMWInst::Sub.
Referenced by visitCallInst().
computeOverflowForSignedAdd()
OverflowResult llvm::InstCombiner::computeOverflowForSignedAdd (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 706 of file InstCombineInternal.h.
References llvm::computeOverflowForSignedAdd().
Referenced by computeOverflow().
computeOverflowForSignedMul()
OverflowResult llvm::InstCombiner::computeOverflowForSignedMul (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 694 of file InstCombineInternal.h.
References llvm::computeOverflowForSignedMul().
Referenced by computeOverflow().
computeOverflowForSignedSub()
OverflowResult llvm::InstCombiner::computeOverflowForSignedSub (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 718 of file InstCombineInternal.h.
References llvm::computeOverflowForSignedSub().
Referenced by computeOverflow().
computeOverflowForUnsignedAdd()
OverflowResult llvm::InstCombiner::computeOverflowForUnsignedAdd (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 700 of file InstCombineInternal.h.
References llvm::computeOverflowForUnsignedAdd().
Referenced by computeOverflow().
computeOverflowForUnsignedMul()
OverflowResult llvm::InstCombiner::computeOverflowForUnsignedMul (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 688 of file InstCombineInternal.h.
References llvm::computeOverflowForUnsignedMul().
Referenced by computeOverflow().
computeOverflowForUnsignedSub()
OverflowResult llvm::InstCombiner::computeOverflowForUnsignedSub (const Value * LHS, const Value * RHS, const Instruction * CxtI) const inline
Definition at line 712 of file InstCombineInternal.h.
References llvm::computeOverflowForUnsignedSub().
Referenced by computeOverflow().
CreateNonTerminatorUnreachable()
void llvm::InstCombiner::CreateNonTerminatorUnreachable (Instruction * InsertAt) inline
Create and insert the idiom we use to indicate a block is unreachable without having to rewrite the CFG from within InstCombine.
Definition at line 631 of file InstCombineInternal.h.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getContext(), llvm::Type::getInt1PtrTy(), and llvm::IRBuilderBase::getTrue().
Referenced by visitFree().
CreateOverflowTuple()
Instruction * llvm::InstCombiner::CreateOverflowTuple (IntrinsicInst * II, Value * Result, Constant * Overflow) inline
Creates a result tuple for an overflow intrinsic II with a given Result and a constant Overflow value.
Definition at line 621 of file InstCombineInternal.h.
References llvm::InsertValueInst::Create(), llvm::IntervalMapImpl::NodeRef::get(), and llvm::Value::getType().
dominatesAllUses()
bool InstCombiner::dominatesAllUses (const Instruction * DI, const Instruction * UI, const BasicBlock * DB) const
True when DB dominates all uses of DI except UI.
Check that one use is in the same block as the definition and all other uses are in blocks dominated by a given block.
UI must be in the same block as DI. The routine checks that the DI parent and DB are different.
Parameters
DI Definition
UI Use
DB Block that must dominate all uses of DI outside the parent block
Returns
true when UI is the only use of DI in the parent block and all other uses of DI are in blocks dominated by DB.
Definition at line 4474 of file InstCombineCompares.cpp.
References assert(), llvm::DominatorTree::dominates(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), and llvm::Value::users().
Referenced by replacedSelectWithOperand().
eraseInstFromFunction()
Instruction * llvm::InstCombiner::eraseInstFromFunction (Instruction & I) inline
Combiner aware instruction erasure.
When dealing with an instruction that has side effects or produces a void value, we can't rely on DCE to delete the instruction. Instead, visit methods should return the value returned by this function.
Definition at line 644 of file InstCombineInternal.h.
References llvm::InstCombineWorklist::Add(), assert(), llvm::dbgs(), I, LLVM_DEBUG, llvm::InstCombineWorklist::Remove(), and llvm::salvageDebugInfo().
Referenced by combineLoadToOperationType(), removeBitcastsFromLoadStoreOnMinMax(), removeTriviallyEmptyRange(), run(), simplifyX86MaskedStore(), visitAllocaInst(), visitAllocSite(), visitAtomicRMWInst(), visitCallInst(), visitExtractValueInst(), visitFenceInst(), visitFree(), and visitStoreInst().
FoldItoFPtoI()
Instruction * InstCombiner::FoldItoFPtoI (Instruction & FI)
Definition at line 1687 of file InstCombineCasts.cpp.
References llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and replaceInstUsesWith().
Referenced by visitFPToSI(), and visitFPToUI().
FoldShiftByConstant()
Instruction * InstCombiner::FoldShiftByConstant (Value * Op0, Constant * Op1, BinaryOperator & I)
Definition at line 377 of file InstCombineShifts.cpp.
References llvm::MCBinaryExpr::AShr, assert(), Builder, C, canEvaluateShifted(), canShiftBinOpWithConstantRHS(), llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::TargetFolder::CreateSub(), llvm::dbgs(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), getShiftedValue(), llvm::ConstantExpr::getShl(), llvm::ConstantVector::getSplat(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), llvm::APInt::getZExtValue(), llvm::Value::hasOneUse(), I, llvm::Instruction::isShift(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm::MCBinaryExpr::LShr, llvm::APInt::lshrInPlace(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::MCBinaryExpr::Shl, llvm::AtomicRMWInst::Sub, llvm::Value::takeName(), llvm::APInt::uge(), X, and llvm::AtomicRMWInst::Xor.
Referenced by commonShiftTransforms().
getAssumptionCache()
AssumptionCache & llvm::InstCombiner::getAssumptionCache () const inline
Definition at line 299 of file InstCombineInternal.h.
Referenced by foldCttzCtlz().
getDataLayout()
const DataLayout & llvm::InstCombiner::getDataLayout () const inline
Definition at line 301 of file InstCombineInternal.h.
Referenced by canReplaceGEPIdxWithZero(), combineLoadToNewType(), combineLoadToOperationType(), foldCttzCtlz(), foldVecTruncToExtElt(), likeBitCastFromVector(), optimizeIntegerToVectorInsertions(), simplifyAllocaArraySize(), unpackLoadToAggregate(), and unpackStoreToAggregate().
getDominatorTree()
DominatorTree & llvm::InstCombiner::getDominatorTree () const inline
Definition at line 303 of file InstCombineInternal.h.
Referenced by foldCttzCtlz().
getLoopInfo()
LoopInfo * llvm::InstCombiner::getLoopInfo () const inline
Definition at line 305 of file InstCombineInternal.h.
getTargetLibraryInfo()
TargetLibraryInfo & llvm::InstCombiner::getTargetLibraryInfo () const inline
Definition at line 307 of file InstCombineInternal.h.
Referenced by getShiftedValue().
InsertNewInstBefore()
Instruction * llvm::InstCombiner::InsertNewInstBefore (Instruction * New, Instruction & Old) inline
Inserts an instruction New before instruction Old.
Also adds the new instruction to the worklist and returns New so that it is suitable for use as the return from the visitation patterns.
Definition at line 579 of file InstCombineInternal.h.
References llvm::InstCombineWorklist::Add(), assert(), llvm::BasicBlock::getInstList(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by simplifyAllocaArraySize().
InsertNewInstWith()
Instruction * llvm::InstCombiner::InsertNewInstWith (Instruction * New, Instruction & Old) inline
Same as InsertNewInstBefore, but also sets the debug loc.
Definition at line 589 of file InstCombineInternal.h.
References llvm::Instruction::getDebugLoc().
Referenced by replaceExtractElements().
isKnownToBeAPowerOfTwo()
bool llvm::InstCombiner::isKnownToBeAPowerOfTwo (const Value * V, bool OrZero = false, unsigned Depth = 0, const Instruction * CxtI = nullptr) inline
Definition at line 672 of file InstCombineInternal.h.
References llvm::Depth, and llvm::isKnownToBeAPowerOfTwo().
Referenced by simplifyValueKnownNonZero(), visitICmpInst(), visitSDiv(), and visitURem().
MaskedValueIsZero()
bool llvm::InstCombiner::MaskedValueIsZero (const Value * V, const APInt & Mask, unsigned Depth = 0, const Instruction * CxtI = nullptr) const inline
Definition at line 678 of file InstCombineInternal.h.
References llvm::Depth, and llvm::MaskedValueIsZero().
Referenced by canEvaluateShiftedShift(), canEvaluateTruncated(), canEvaluateZExtd(), visitAdd(), visitAnd(), visitAShr(), visitLShr(), visitOr(), visitSDiv(), visitShl(), visitSRem(), visitXor(), and visitZExt().
OptimizePointerDifference()
Value * InstCombiner::OptimizePointerDifference (Value * LHS, Value * RHS, Type * Ty)
Optimize pointer differences into the same array into a size.
Consider: &A[10] - &A[0]: we should compile this to "10". LHS/RHS are the pointer operands to the ptrtoint instructions for the LHS/RHS of the subtract.
Definition at line 1449 of file InstCombineAddSub.cpp.
References Builder, llvm::GEPOperator::countNonConstantIndices(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateSub(), and llvm::Value::hasOneUse().
Referenced by visitSub().
replacedSelectWithOperand()
bool InstCombiner::replacedSelectWithOperand (SelectInst * SI, const ICmpInst * Icmp, const unsigned SIOpd)
Try to replace select with select operand SIOpd in SI-ICmp sequence.
True when a select result is replaced by one of its operands in select-icmp sequence.
This will eventually result in the elimination of the select.
Parameters
SI Select instruction
Icmp Compare instruction
SIOpd Operand that replaces the select
Notes:
The replacement is global and requires dominator information
The caller is responsible for the actual replacement
Example:
entry: %4 = select i1 %3, C* %0, C* null %5 = icmp eq C* %4, null br i1 %5, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %4, i64 0, i32 0 ...
can be transformed to
%5 = icmp eq C* %0, null %6 = select i1 %3, i1 %5, i1 true br i1 %6, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %0, i64 0, i32 0 // replace by %0!
Similar when the first operand of the select is a constant or/and the compare is for not equal rather than equal.
NOTE: The function is only called when the select and compare constants are equal, the optimization can work only for EQ predicates. This is not a major restriction since a NE compare should be 'normalized' to an equal compare, which usually happens in the combiner and test case select-cmp-br.ll checks for it.
Definition at line 4549 of file InstCombineCompares.cpp.
References assert(), dominatesAllUses(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getSinglePredecessor(), llvm::CmpInst::ICMP_EQ, isChainSelectCmpBranch(), and SI.
replaceInstUsesWith()
Instruction * llvm::InstCombiner::replaceInstUsesWith (Instruction & I, Value * V) inline
A combiner-aware RAUW-like routine.
This method is to be used when an instruction is found to be dead, replaceable with another preexisting expression. Here we add all uses of I to the worklist, replace all uses of I with the new value, then return I, so that the inst combiner will know that I was modified.
Definition at line 600 of file InstCombineInternal.h.
References llvm::InstCombineWorklist::AddUsersToWorkList(), llvm::dbgs(), llvm::IntervalMapImpl::NodeRef::get(), I, and LLVM_DEBUG.
Referenced by foldCttzCtlz(), FoldItoFPtoI(), FoldShiftByConstant(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), removeBitcastsFromLoadStoreOnMinMax(), replaceExtractElements(), run(), simplifyAllocaArraySize(), simplifyX86MaskedLoad(), SliceUpIllegalIntegerPHI(), unpackLoadToAggregate(), visitAdd(), visitAllocaInst(), visitAllocSite(), visitAnd(), visitAShr(), visitBitCast(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFAdd(), visitFCmpInst(), visitFDiv(), visitFMul(), visitFNeg(), visitFRem(), visitFSub(), visitGetElementPtrInst(), visitICmpInst(), visitInsertElementInst(), visitInsertValueInst(), visitLoadInst(), visitLShr(), visitMul(), visitOr(), visitPHINode(), visitSDiv(), visitSExt(), visitShl(), visitShuffleVectorInst(), visitSRem(), visitSub(), visitTrunc(), visitUDiv(), visitURem(), visitXor(), and visitZExt().
replacePointer()
bool llvm::InstCombiner::replacePointer (Instruction & I, Value * V)
Try to replace instruction I with value V which are pointers in different address space.
Returns
true if successful.
run()
bool InstCombiner::run ()
Run the combiner over the entire worklist until it is empty.
Returns
true if the IR is changed.
Definition at line 3185 of file InstructionCombining.cpp.
References llvm::InstCombineWorklist::Add(), llvm::InstCombineWorklist::AddUsersToWorkList(), Builder, C, computeKnownBits(), llvm::ConstantFoldInstruction(), llvm::dbgs(), E, EnableCodeSinking, eraseInstFromFunction(), llvm::IntervalMapImpl::NodeRef::get(), llvm::KnownBits::getConstant(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getInstList(), llvm::Instruction::getParent(), llvm::BasicBlock::getUniquePredecessor(), I, llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::KnownBits::isConstant(), llvm::InstCombineWorklist::isEmpty(), llvm::isInstructionTriviallyDead(), llvm::Type::isIntOrIntVectorTy(), LLVM_DEBUG, llvm::InstCombineWorklist::RemoveOne(), replaceInstUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), llvm::DebugCounter::shouldExecute(), SI, llvm::succ_begin(), llvm::succ_end(), TryToSinkInstruction(), llvm::InstVisitor< InstCombiner, Instruction * >::visit(), Worklist, and llvm::InstCombineWorklist::Zap().
Referenced by combineInstructionsOverFunction().
simplifyDivRemOfSelectWithZeroOp()
bool InstCombiner::simplifyDivRemOfSelectWithZeroOp (BinaryOperator & I)
Fold a divide or remainder with a select instruction divisor when one of the select operands is zero.
In that case, we can use the other select operand because div/rem by zero is undefined.
Definition at line 539 of file InstCombineMulDivRem.cpp.
References llvm::InstCombineWorklist::Add(), E, llvm::IRBuilderBase::getFalse(), llvm::IRBuilderBase::getTrue(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), SI, and Worklist.
Referenced by commonIDivTransforms(), and commonIRemTransforms().
simplifyRangeCheck()
Value * InstCombiner::simplifyRangeCheck (ICmpInst * Cmp0, ICmpInst * Cmp1, bool Inverted)
Try to fold a signed range checked with lower bound 0 to an unsigned icmp.
Example: (icmp sge x, 0) & (icmp slt x, n) --> icmp ult x, n If Inverted is true then the check is for the inverted range, e.g. (icmp slt x, 0) | (icmp sgt x, n) --> icmp ugt x, n
Definition at line 754 of file InstCombineAndOrXor.cpp.
References Builder, computeKnownBits(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantInt::isMinusOne(), llvm::KnownBits::isNonNegative(), and llvm::ConstantInt::isZero().
SliceUpIllegalIntegerPHI()
Instruction * InstCombiner::SliceUpIllegalIntegerPHI (PHINode & FirstPhi)
This is an integer PHI and we know that it has an illegal type: see if it is only used by trunc or trunc(lshr) operations.
If so, we split the PHI into the various pieces being extracted. This sort of thing is introduced when SROA promotes an aggregate to large integer values.
TODO: The user of the trunc may be an bitcast to float/double/vector or an inttoptr. We should produce new PHIs in the right type.
Definition at line 951 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::array_pod_sort(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), Builder, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::PHINode::Create(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::dbgs(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Type::getScalarSizeInBits(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::MCBinaryExpr::LShr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceInstUsesWith(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SmallVectorBase::size(), llvm::Instruction::user_back(), and llvm::Value::users().
Referenced by visitPHINode().
visitAdd()
Instruction * InstCombiner::visitAdd (BinaryOperator & I)
Definition at line 1100 of file InstCombineAddSub.cpp.
References A, B, Builder, canonicalizeLowbitMask(), checkForNegativeOperand(), computeKnownBits(), llvm::SelectInst::Create(), llvm::TargetFolder::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::TargetFolder::CreateAnd(), llvm::TargetFolder::CreateAShr(), llvm::BinaryOperator::CreateNeg(), llvm::TargetFolder::CreateOr(), llvm::TargetFolder::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::TargetFolder::CreateSub(), llvm::TargetFolder::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateZExt(), foldNoWrapAdd(), foldToUnsignedSaturatedAdd(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getAdd(), llvm::APInt::getHighBitsSet(), llvm::Value::getName(), llvm::Type::getScalarSizeInBits(), llvm::ConstantInt::getValue(), llvm::SimplifyQuery::getWithInstruction(), llvm::ConstantExpr::getXor(), llvm::Value::hasOneUse(), llvm::haveNoCommonBitsSet(), I, llvm::Type::isIntOrIntVectorTy(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignMask(), llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), MaskedValueIsZero(), llvm::PatternMatch::match(), N, replaceInstUsesWith(), SI, llvm::SimplifyAddInst(), X, and llvm::KnownBits::Zero.
visitAddrSpaceCast()
Instruction * InstCombiner::visitAddrSpaceCast (AddrSpaceCastInst & CI)
Definition at line 2437 of file InstCombineCasts.cpp.
References Builder, commonPointerCastTransforms(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerType::getAddressSpace(), llvm::PointerType::getElementType(), llvm::User::getOperand(), llvm::Type::getScalarType(), and llvm::Value::getType().
visitAllocaInst()
Instruction * InstCombiner::visitAllocaInst (AllocaInst & AI)
Definition at line 341 of file InstCombineLoadStoreAlloca.cpp.
References llvm::dbgs(), eraseInstFromFunction(), llvm::IntervalMapImpl::NodeRef::get(), llvm::AllocaInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::BasicBlock::getFirstNonPHIOrDbg(), llvm::getOrEnforceKnownAlignment(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Type::getPointerAddressSpace(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::Type::getPointerElementType(), llvm::DataLayout::getPrefTypeAlignment(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), I, llvm::AllocaInst::isArrayAllocation(), isDereferenceableForAllocaSize(), isOnlyCopiedFromConstantGlobal(), llvm::Type::isSized(), LLVM_DEBUG, llvm::Instruction::moveBefore(), replaceInstUsesWith(), llvm::AllocaInst::setAlignment(), llvm::User::setOperand(), simplifyAllocaArraySize(), llvm::SmallVectorBase::size(), and visitAllocSite().
visitAllocSite()
Instruction * InstCombiner::visitAllocSite (Instruction & FI)
Definition at line 2345 of file InstructionCombining.cpp.
References C, llvm::ConvertDebugDeclareToDebugValue(), llvm::InvokeInst::Create(), eraseInstFromFunction(), F, llvm::FindDbgAddrUses(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt1Ty(), I, isAllocSiteRemovable(), llvm::lowerObjectSizeCall(), MI, llvm::None, replaceInstUsesWith(), SI, and Users.
Referenced by visitAllocaInst().
visitAnd()
Instruction * InstCombiner::visitAnd (BinaryOperator & I)
Definition at line 1608 of file InstCombineAndOrXor.cpp.
References A, B, Builder, C, llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::TargetFolder::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::TargetFolder::CreateXor(), foldAndToXor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getAnd(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getTrunc(), llvm::ConstantInt::getValue(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), I, llvm::IsFreeToInvert(), llvm::APInt::isIntN(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZExt(), MaskedValueIsZero(), llvm::PatternMatch::match(), matchDeMorgansLaws(), llvm::MCBinaryExpr::Mul, reassociateFCmps(), replaceInstUsesWith(), llvm::SimplifyAndInst(), SimplifyBSwap(), llvm::AtomicRMWInst::Sub, X, llvm::AtomicRMWInst::Xor, Y, and llvm::Z.
visitAShr()
Instruction * InstCombiner::visitAShr (BinaryOperator & I)
Definition at line 862 of file InstCombineShifts.cpp.
References Builder, commonShiftTransforms(), llvm::BinaryOperator::Create(), llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::TargetFolder::CreateLShr(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getLowBitsSet(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::SimplifyQuery::getWithInstruction(), llvm::APInt::getZExtValue(), I, llvm::Type::isVectorTy(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), MaskedValueIsZero(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::MCBinaryExpr::Shl, llvm::SimplifyAShrInst(), llvm::APInt::ult(), and X.
visitAtomicRMWInst()
Instruction * InstCombiner::visitAtomicRMWInst (AtomicRMWInst & SI)
Definition at line 96 of file InstCombineAtomicRMW.cpp.
References llvm::Acquire, assert(), eraseInstFromFunction(), llvm::AtomicRMWInst::FAdd, llvm::IntervalMapImpl::NodeRef::get(), llvm::DataLayout::getABITypeAlignment(), llvm::ConstantFP::getNegativeZero(), llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getOrdering(), llvm::AtomicRMWInst::getPointerOperand(), llvm::AtomicRMWInst::getSyncScopeID(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::AtomicRMWInst::isVolatile(), llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::User::setOperand(), llvm::AtomicRMWInst::setOperation(), SI, llvm::Unordered, llvm::Value::use_empty(), and llvm::AtomicRMWInst::Xchg.
visitBitCast()
Instruction * InstCombiner::visitBitCast (BitCastInst & CI)
Definition at line 2289 of file InstCombineCasts.cpp.
References Builder, canonicalizeBitCastExtElt(), commonCastTransforms(), commonPointerCastTransforms(), llvm::CastInst::Create(), llvm::InsertElementInst::Create(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::GetElementPtrInst::CreateInBounds(), foldBitCastBitwiseLogic(), foldBitCastSelect(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerType::getAddressSpace(), llvm::Value::getContext(), llvm::PointerType::getElementType(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::Constant::getNullValue(), llvm::Type::getNumContainedTypes(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), I, llvm::Type::isPointerTy(), llvm::Type::isSized(), llvm::Type::isVectorTy(), optimizeIntegerToVectorInsertions(), optimizeVectorResize(), and replaceInstUsesWith().
Referenced by visitGetElementPtrInst().
visitBranchInst()
Instruction * InstCombiner::visitBranchInst (BranchInst & BI)
Definition at line 2549 of file InstructionCombining.cpp.
References llvm::InstCombineWorklist::Add(), llvm::BranchInst::getCondition(), llvm::IRBuilderBase::getFalse(), llvm::CmpInst::getInversePredicate(), llvm::BranchInst::getSuccessor(), llvm::Value::getType(), llvm::isCanonicalPredicate(), llvm::BranchInst::isConditional(), llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::BranchInst::setCondition(), llvm::BranchInst::swapSuccessors(), Worklist, and X.
visitCallBrInst()
Instruction * InstCombiner::visitCallBrInst (CallBrInst & CBI)
Definition at line 4046 of file InstCombineCalls.cpp.
visitCallInst()
Instruction * InstCombiner::visitCallInst (CallInst & CI)
CallInst simplification.
This mostly only handles folding of intrinsic instructions. For normal calls, it allows visitCallBase to do the heavy lifting.
Definition at line 1782 of file InstCombineCalls.cpp.
References A, llvm::CallBase::addAttribute(), llvm::AlwaysOverflowsHigh, llvm::AlwaysOverflowsLow, Arg, assert(), B, Builder, C, canonicalizeConstantArg0ToArg1(), computeKnownBits(), computeOverflow(), llvm::Constant::containsConstantExpression(), llvm::MCID::Convergent, llvm::APFloat::convert(), llvm::Instruction::copyFastMathFlags(), llvm::Instruction::copyIRFlags(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::TargetFolder::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFCmpOEQ(), llvm::IRBuilder< T, Inserter >::CreateFCmpUNO(), llvm::TargetFolder::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::TargetFolder::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::BinaryOperator::CreateFNeg(), llvm::IRBuilder< T, Inserter >::CreateFPExt(), llvm::IRBuilder< T, Inserter >::CreateFPTrunc(), llvm::IRBuilder< T, Inserter >::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::TargetFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilderBase::CreateMaxNum(), llvm::IRBuilderBase::CreateMinNum(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::BinaryOperator::CreateNSW(), llvm::BinaryOperator::CreateNUW(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::TargetFolder::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::Data, llvm::APFloat::divide(), llvm::CallBase::doesNotThrow(), eraseInstFromFunction(), llvm::CmpInst::FIRST_FCMP_PREDICATE, llvm::CmpInst::FIRST_ICMP_PREDICATE, fmed3AMDGCN(), foldCtpop(), foldCttzCtlz(), llvm::frexp(), llvm::AttributeList::FunctionIndex, llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::IntegerType::getBitWidth(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCalledValue(), llvm::ConstantExpr::getCompare(), llvm::IRBuilderBase::getContext(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getFastMathFlags(), llvm::IRBuilderBase::getFloatTy(), llvm::Type::getFltSemantics(), llvm::Instruction::getFunction(), llvm::CallBase::getFunctionType(), llvm::IRBuilderBase::getHalfTy(), llvm::ConstantExpr::getICmp(), llvm::IRBuilderBase::getInt1Ty(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::Type::getIntegerBitWidth(), llvm::ConstantExpr::getIntegerCast(), llvm::IRBuilderBase::getIntNTy(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CmpInst::getInversePredicate(), llvm::getKnownAlignment(), llvm::APInt::getLowBitsSet(), llvm::APSInt::getMaxValue(), llvm::APSInt::getMinValue(), llvm::Instruction::getModule(), llvm::ConstantExpr::getMul(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), getNegativeIsTrueBoolVec(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getNextNonDebugInstruction(), llvm::APInt::getNullValue(), llvm::CallBase::getNumArgOperands(), llvm::Instruction::getOpcode(), llvm::getOrEnforceKnownAlignment(), llvm::Instruction::getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::APFloat::getSemantics(), llvm::ConstantExpr::getSExt(), llvm::APInt::getSplat(), llvm::ConstantExpr::getSub(), llvm::CmpInst::getSwappedPredicate(), llvm::BasicBlock::getTerminator(), llvm::IRBuilderBase::getTrue(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::ConstantExpr::getURem(), llvm::ConstantInt::getValue(), llvm::ConstantFP::getValueAPF(), llvm::Type::getVectorNumElements(), llvm::SimplifyQuery::getWithInstruction(), llvm::ConstantInt::getZExtValue(), GuardWideningWindow, llvm::Value::hasOneUse(), llvm::CallBase::hasRetAttr(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, Idx, llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::KnownBits::isAllOnes(), llvm::APFloat::isDenormal(), llvm::Type::isDoubleTy(), llvm::Instruction::isFast(), llvm::Type::isFloatTy(), llvm::CmpInst::isFPPredicate(), llvm::isFreeCall(), llvm::Type::isHalfTy(), llvm::APFloat::isInfinity(), llvm::Type::isIntegerTy(), llvm::isKnownNeverNaN(), llvm::isKnownNonZero(), llvm::DataLayout::isLittleEndian(), llvm::APFloat::isNaN(), llvm::APFloat::isNegative(), llvm::APInt::isNonNegative(), llvm::APFloat::isNormal(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::isPowerOf2_32(), llvm::isSafeToSpeculativelyExecute(), llvm::APFloat::isSignaling(), llvm::CmpInst::isSigned(), llvm::APInt::isSubsetOf(), llvm::isValidAssumeForContext(), llvm::Type::isVectorTy(), llvm::APFloat::isZero(), llvm::CmpInst::LAST_FCMP_PREDICATE, llvm::CmpInst::LAST_ICMP_PREDICATE, LLVM_FALLTHROUGH, llvm_unreachable, llvm::Log2_32_Ceil(), llvm::lowerObjectSizeCall(), llvm::APInt::lshr(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_NaN(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_NUWAdd(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::CmpInst::makeCmpResultType(), llvm::PatternMatch::match(), llvm::maximum(), llvm::maxnum(), llvm::MayOverflow, llvm::LLVMContext::MD_nonnull, MI, llvm::minimum(), llvm::minnum(), llvm::Mod, llvm::NeverOverflows, llvm::None, llvm::APFloatBase::opOK, OR, Other, llvm::peekThroughBitcast(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), removeTriviallyEmptyRange(), replaceInstUsesWith(), llvm::AttributeList::ReturnIndex, llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardZero, llvm::APInt::sadd_ov(), llvm::CallBase::setArgOperand(), llvm::CallBase::setCalledFunction(), llvm::CallBase::setDoesNotThrow(), llvm::IRBuilderBase::setFastMathFlags(), llvm::Instruction::setMetadata(), llvm::User::setOperand(), SI, Signed, llvm::SimplifyCall(), simplifyInvariantGroupIntrinsic(), simplifyNeonTbl1(), simplifyNeonVld1(), SimplifyNVVMIntrinsic(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), std::swap(), llvm::Value::takeName(), llvm::APInt::uadd_ov(), llvm::APInt::uadd_sat(), llvm::AssumptionCache::updateAffectedValues(), llvm::Value::use_empty(), visitFree(), X, Y, and llvm::APInt::zextOrTrunc().
visitExtractElementInst()
Instruction * InstCombiner::visitExtractElementInst (ExtractElementInst & EI)
Definition at line 256 of file InstCombineVectorOps.cpp.
References llvm::InstCombineWorklist::AddValue(), Builder, cheapToScalarize(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::ExtractElementInst::Create(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::BinaryOperator::CreateWithCopiedFlags(), foldBitcastExtElt(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getContext(), llvm::ExtractElementInst::getIndexOperand(), llvm::IRBuilderBase::getInt32Ty(), llvm::SequentialType::getNumElements(), llvm::BinaryOperator::getOpcode(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ExtractElementInst::getVectorOperand(), llvm::ExtractElementInst::getVectorOperandType(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), I, Int32Ty, llvm::DataLayout::isBigEndian(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::APInt::setBit(), llvm::User::setOperand(), llvm::SimplifyExtractElementInst(), Worklist, X, and Y.
visitExtractValueInst()
Instruction * InstCombiner::visitExtractValueInst (ExtractValueInst & EV)
Definition at line 2638 of file InstructionCombining.cpp.
References Builder, llvm::BinaryOperator::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateLoad(), E, eraseInstFromFunction(), GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::ExtractValueInst::getAggregateOperand(), llvm::ExtractValueInst::getIndices(), llvm::IRBuilderBase::getInt32(), llvm::ConstantExpr::getNot(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::ExtractValueInst::hasIndices(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_UGT, llvm::ExtractValueInst::idx_begin(), llvm::ExtractValueInst::idx_end(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceInstUsesWith(), llvm::Instruction::setAAMetadata(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::SimplifyExtractValueInst().
visitFAdd()
Instruction * InstCombiner::visitFAdd (BinaryOperator & I)
Definition at line 1350 of file InstCombineAddSub.cpp.
References Builder, llvm::BinaryOperator::CreateFSubFMF(), llvm::IRBuilder< T, Inserter >::CreateNSWAdd(), F, factorizeFAddFSub(), llvm::Type::getFltSemantics(), llvm::ConstantExpr::getFPToSI(), llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::ConstantExpr::getSIToFP(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::APFloatBase::semanticsPrecision(), simplify, llvm::SimplifyFAddInst(), and X.
visitFCmpInst()
Instruction * InstCombiner::visitFCmpInst (FCmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 5592 of file InstCombineCompares.cpp.
References A, assert(), B, Builder, C, llvm::APFloat::clearSign(), llvm::APFloatBase::cmpLessThan, llvm::APFloat::compare(), llvm::APFloat::convert(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::SelectPatternResult::Flavor, foldFabsWithFcmpZero(), foldFCmpReciprocalAndZero(), foldVectorCmp(), GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::getComplexity(), llvm::ConstantExpr::getFNeg(), llvm::Constant::getNullValue(), llvm::APInt::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::APFloat::getSmallestNormalized(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::GlobalVariable::hasDefinitiveInitializer(), I, llvm::GlobalVariable::isConstant(), llvm::isKnownNeverNaN(), llvm::APFloat::isZero(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), replaceInstUsesWith(), llvm::APFloatBase::rmNearestTiesToEven, SI, llvm::SimplifyFCmpInst(), llvm::SPF_UNKNOWN, X, and Y.
visitFDiv()
Instruction * InstCombiner::visitFDiv (BinaryOperator & I)
Definition at line 1162 of file InstCombineMulDivRem.cpp.
References B, Builder, llvm::BinaryOperator::CreateFDivFMF(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), llvm::emitUnaryFloatFnCall(), foldFDivConstantDividend(), foldFDivConstantDivisor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), llvm::hasUnaryFloatFn(), I, llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), SI, llvm::SimplifyFDivInst(), X, and Y.
visitFenceInst()
Instruction * InstCombiner::visitFenceInst (FenceInst & FI)
Definition at line 4031 of file InstCombineCalls.cpp.
References eraseInstFromFunction(), llvm::Instruction::getNextNonDebugInstruction(), and llvm::Instruction::isIdenticalTo().
visitFMul()
Instruction * InstCombiner::visitFMul (BinaryOperator & I)
Definition at line 346 of file InstCombineMulDivRem.cpp.
References Builder, C, llvm::IRBuilder< T, Inserter >::CreateFAddFMF(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFDivFMF(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::BinaryOperator::CreateFNegFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::ConstantExpr::getFDiv(), llvm::ConstantExpr::getFMul(), llvm::ConstantExpr::getFNeg(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasNUses(), llvm::Value::hasOneUse(), I, llvm::Constant::isNormalFP(), llvm::Log2(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::SimplifyFMulInst(), X, Y, and llvm::Z.
visitFNeg()
Instruction * InstCombiner::visitFNeg (UnaryOperator & I)
Definition at line 1868 of file InstCombineAddSub.cpp.
References llvm::BinaryOperator::CreateFSubFMF(), foldFNegIntoConstant(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::SimplifyFNegInst(), X, and Y.
visitFPExt()
Instruction * InstCombiner::visitFPExt (CastInst & CI)
Definition at line 1679 of file InstCombineCasts.cpp.
References commonCastTransforms().
visitFPToSI()
Instruction * InstCombiner::visitFPToSI (FPToSIInst & FI)
Definition at line 1738 of file InstCombineCasts.cpp.
References commonCastTransforms(), FoldItoFPtoI(), llvm::User::getOperand(), and I.
visitFPToUI()
Instruction * InstCombiner::visitFPToUI (FPToUIInst & FI)
Definition at line 1727 of file InstCombineCasts.cpp.
References commonCastTransforms(), FoldItoFPtoI(), llvm::User::getOperand(), and I.
visitFPTrunc()
Instruction * InstCombiner::visitFPTrunc (FPTruncInst & CI)
Definition at line 1522 of file InstCombineCasts.cpp.
References Builder, commonCastTransforms(), llvm::Instruction::copyFastMathFlags(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::UnaryOperator::CreateFNegFMF(), llvm::BinaryOperator::CreateFNegFMF(), llvm::CastInst::CreateFPCast(), llvm::IRBuilder< T, Inserter >::CreateFPTrunc(), llvm::IRBuilder< T, Inserter >::CreateFRemFMF(), llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::Intrinsic::getDeclaration(), llvm::Type::getFPMantissaWidth(), getMinimumFPType(), llvm::Instruction::getModule(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CastInst::getSrcTy(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), shrinkInsertElt(), and X.
visitFree()
Instruction * InstCombiner::visitFree (CallInst & FI)
Definition at line 2503 of file InstructionCombining.cpp.
References CreateNonTerminatorUnreachable(), eraseInstFromFunction(), llvm::CallBase::getArgOperand(), I, and tryToMoveFreeBeforeNullTest().
Referenced by visitCallInst().
visitFRem()
Instruction * InstCombiner::visitFRem (BinaryOperator & I)
Definition at line 1419 of file InstCombineMulDivRem.cpp.
References llvm::SimplifyQuery::getWithInstruction(), I, replaceInstUsesWith(), llvm::SimplifyFRemInst(), and X.
visitFSub()
Instruction * InstCombiner::visitFSub (BinaryOperator & I)
Definition at line 1888 of file InstCombineAddSub.cpp.
References Builder, C, llvm::CannotBeNegativeZero(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::BinaryOperator::CreateFNegFMF(), llvm::IRBuilder< T, Inserter >::CreateFPExt(), llvm::IRBuilder< T, Inserter >::CreateFPTrunc(), llvm::IRBuilder< T, Inserter >::CreateFSubFMF(), F, factorizeFAddFSub(), foldFNegIntoConstant(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getFNeg(), llvm::ConstantExpr::getFSub(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FPTrunc(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), SI, simplify, llvm::SimplifyFSubInst(), llvm::SimplifyQuery::TLI, X, and Y.
visitGetElementPtrInst()
Instruction * InstCombiner::visitGetElementPtrInst (GetElementPtrInst & GEP)
Definition at line 1610 of file InstructionCombining.cpp.
References llvm::PHINode::addIncoming(), llvm::SmallVectorImpl< T >::append(), assert(), Builder, C, llvm::Instruction::clone(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::GetElementPtrInst::CreateInBounds(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::IRBuilder< T, Inserter >::CreateSub(), E, llvm::SmallVectorBase::empty(), F, GEP, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerType::getAddressSpace(), llvm::APInt::getAllOnesValue(), llvm::Type::getArrayElementType(), llvm::Type::getArrayNumElements(), llvm::PointerType::getElementType(), llvm::PHINode::getIncomingBlock(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::DataLayout::getIndexSizeInBits(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), I, Idx, llvm::IRBuilder< T, Inserter >::Insert(), llvm::isAllocationFn(), llvm::Type::isArrayTy(), llvm::Type::isSized(), llvm::generic_gep_type_iterator< ItTy >::isStruct(), llvm::Type::isStructTy(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::User::op_begin(), llvm::User::op_end(), llvm::User::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceInstUsesWith(), llvm::IRBuilderBase::SetInsertPoint(), llvm::GetElementPtrInst::setIsInBounds(), shouldMergeGEPs(), llvm::SimplifyAddInst(), llvm::SimplifyGEPInst(), llvm::Value::stripPointerCasts(), llvm::Value::takeName(), visitBitCast(), and Y.
visitICmpInst()
Instruction * InstCombiner::visitICmpInst (ICmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 5012 of file InstCombineCompares.cpp.
References A, assert(), B, Builder, C, canonicalizeCmpWithConstant(), canonicalizeICmpBool(), llvm::CmpInst::Create(), llvm::ExtractValueInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::SelectPatternResult::Flavor, foldICmpBitCast(), foldICmpWithHighBitMask(), foldICmpWithMinMax(), foldVectorCmp(), GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getAllOnesValue(), llvm::getComplexity(), llvm::Constant::getNullValue(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::GetUnderlyingObject(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::Type::isIntOrIntVectorTy(), isKnownToBeAPowerOfTwo(), llvm::Type::isPointerTy(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_UAddWithOverflow(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), processUMulZExtIdiom(), replaceInstUsesWith(), SI, llvm::SimplifyICmpInst(), llvm::SPF_UNKNOWN, std::swap(), swapMayExposeCSEOpportunities(), and X.
visitInsertElementInst()
Instruction * InstCombiner::visitInsertElementInst (InsertElementInst & IE)
Definition at line 898 of file InstCombineVectorOps.cpp.
References Builder, collectShuffleElements(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), foldConstantInsEltIntoShuffle(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getAllOnesValue(), llvm::Value::getType(), getType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), hoistInsEltConst(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ExtractElement(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), and llvm::SimplifyInsertElementInst().
visitInsertValueInst()
Instruction * InstCombiner::visitInsertValueInst (InsertValueInst & I)
Try to find redundant insertvalue instructions, like the following ones: %0 = insertvalue { i8, i32 } undef, i8 x, 0 %1 = insertvalue { i8, i32 } %0, i8 y, 0 Here the second instruction inserts values at the same indices, as the first one, making the first one redundant.
It should be transformed to: %0 = insertvalue { i8, i32 } undef, i8 y, 0
Definition at line 618 of file InstCombineVectorOps.cpp.
References llvm::Depth, llvm::User::getOperand(), llvm::Value::hasOneUse(), I, replaceInstUsesWith(), and llvm::Value::user_back().
visitInstruction()
Instruction * llvm::InstCombiner::visitInstruction (Instruction & I) inline
Specify what to return for unhandled instructions.
Definition at line 391 of file InstCombineInternal.h.
visitIntToPtr()
Instruction * InstCombiner::visitIntToPtr (IntToPtrInst & CI)
Definition at line 1757 of file InstCombineCasts.cpp.
References Builder, commonCastTransforms(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IntToPtrInst::getAddressSpace(), llvm::Value::getContext(), llvm::DataLayout::getIntPtrType(), llvm::User::getOperand(), llvm::DataLayout::getPointerSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), I, llvm::Type::isVectorTy(), and P.
visitInvokeInst()
Instruction * InstCombiner::visitInvokeInst (InvokeInst & II)
Definition at line 4041 of file InstCombineCalls.cpp.
visitLandingPadInst()
Instruction * InstCombiner::visitLandingPadInst (LandingPadInst & LI)
Definition at line 2799 of file InstructionCombining.cpp.
References llvm::LandingPadInst::addClause(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::classifyEHPersonality(), llvm::LandingPadInst::Create(), llvm::SmallVectorBase::empty(), llvm::SmallVectorImpl< T >::erase(), llvm::Filter, llvm::IntervalMapImpl::NodeRef::get(), llvm::LandingPadInst::getClause(), llvm::SequentialType::getElementType(), llvm::Constant::getNullValue(), llvm::LandingPadInst::getNumClauses(), llvm::SequentialType::getNumElements(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LandingPadInst::isCatch(), isCatchAll(), llvm::LandingPadInst::isCleanup(), llvm::LandingPadInst::isFilter(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::LandingPadInst::setCleanup(), shorter_filter(), llvm::SmallVectorBase::size(), llvm::Constant::stripPointerCasts(), and llvm::Value::stripPointerCasts().
visitLoadInst()
Instruction * InstCombiner::visitLoadInst (LoadInst & LI)
Definition at line 992 of file InstCombineLoadStoreAlloca.cpp.
References llvm::InstCombineWorklist::Add(), assert(), Builder, canSimplifyNullLoadOrGEP(), combineLoadToOperationType(), llvm::combineMetadataForCSE(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateBitOrPointerCast(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::DefMaxInstsToScan, llvm::FindAvailableLoadedValue(), llvm::IntervalMapImpl::NodeRef::get(), llvm::DataLayout::getABITypeAlignment(), llvm::LoadInst::getAlignment(), llvm::Instruction::getDebugLoc(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::getOrEnforceKnownAlignment(), llvm::Instruction::getParent(), llvm::LoadInst::getPointerAddressSpace(), llvm::DataLayout::getPrefTypeAlignment(), llvm::LoadInst::getSyncScopeID(), llvm::Value::getType(), llvm::isSafeToLoadUnconditionally(), llvm::LoadInst::isUnordered(), llvm::NullPointerIsDefined(), replaceGEPIdxWithZero(), replaceInstUsesWith(), llvm::LoadInst::setAlignment(), llvm::LoadInst::setAtomic(), llvm::User::setOperand(), SI, unpackLoadToAggregate(), and Worklist.
visitLShr()
Instruction * InstCombiner::visitLShr (BinaryOperator & I)
Definition at line 733 of file InstCombineShifts.cpp.
References assert(), Builder, commonShiftTransforms(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::TargetFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::TargetFolder::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APFloat::getAllOnesValue(), llvm::APInt::getLowBitsSet(), llvm::Type::getScalarSizeInBits(), getScalarSizeInBits(), llvm::ConstantInt::getSigned(), getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::APInt::getZExtValue(), hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::Type::isIntegerTy(), llvm::isPowerOf2_32(), llvm::Log2_32(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), MaskedValueIsZero(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::SimplifyLShrInst(), llvm::APInt::ugt(), llvm::APInt::ult(), and X.
visitMul()
Instruction * InstCombiner::visitMul (BinaryOperator & I)
i1 mul -> i1 and.
Definition at line 127 of file InstCombineMulDivRem.cpp.
References llvm::APInt::abs(), Builder, C, llvm::SelectInst::Create(), llvm::TargetFolder::CreateAdd(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::TargetFolder::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::BinaryOperator::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::TargetFolder::CreateShl(), llvm::TargetFolder::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getBitWidth(), getLogBase2(), llvm::ConstantExpr::getNeg(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getShl(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::Instruction::isExact(), llvm::APInt::isNegative(), llvm::Constant::isNotMinSignedValue(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::SimplifyMulInst(), X, and Y.
visitOr()
Instruction * InstCombiner::visitOr (BinaryOperator & I)
Definition at line 2290 of file InstCombineAndOrXor.cpp.
References A, B, Builder, C, llvm::SelectInst::Create(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::TargetFolder::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::TargetFolder::CreateXor(), D, foldOrToXor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt(), llvm::Value::getName(), llvm::ConstantExpr::getOr(), llvm::ConstantInt::getSigned(), llvm::ConstantInt::getValue(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), I, llvm::APInt::isAllOnesValue(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), matchDeMorgansLaws(), matchRotate(), reassociateFCmps(), replaceInstUsesWith(), SimplifyBSwap(), llvm::SimplifyOrInst(), std::swap(), llvm::Value::takeName(), X, llvm::AtomicRMWInst::Xor, and Y.
visitPHINode()
Instruction * InstCombiner::visitPHINode (PHINode & PN)
Definition at line 1127 of file InstCombinePHI.cpp.
References llvm::BasicBlock::begin(), DeadPHICycle(), llvm::IntervalMapImpl::NodeRef::get(), GetAnyNonZeroConstInt(), llvm::PHINode::getBasicBlockIndex(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CmpInst::isEquality(), llvm::Type::isIntegerTy(), llvm::isKnownNonZero(), llvm::DataLayout::isLegalInteger(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), PHIsEqualValue(), replaceInstUsesWith(), llvm::PHINode::setIncomingBlock(), llvm::PHINode::setIncomingValue(), llvm::SimplifyInstruction(), SliceUpIllegalIntegerPHI(), and llvm::Instruction::user_back().
visitPtrToInt()
Instruction * InstCombiner::visitPtrToInt (PtrToIntInst & CI)
Definition at line 1803 of file InstCombineCasts.cpp.
References Builder, commonPointerCastTransforms(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getContext(), llvm::DataLayout::getIndexSizeInBits(), llvm::DataLayout::getIntPtrType(), llvm::User::getOperand(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), and P.
visitReturnInst()
Instruction * InstCombiner::visitReturnInst (ReturnInst & RI)
Definition at line 2531 of file InstructionCombining.cpp.
References computeKnownBits(), llvm::KnownBits::getConstant(), llvm::Constant::getIntegerValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::KnownBits::isConstant(), llvm::Type::isIntegerTy(), and llvm::User::setOperand().
visitSDiv()
Instruction * InstCombiner::visitSDiv (BinaryOperator & I)
Definition at line 1008 of file InstCombineMulDivRem.cpp.
References Builder, commonIDivTransforms(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::TargetFolder::CreateSDiv(), llvm::IRBuilder< T, Inserter >::CreateSDiv(), llvm::TargetFolder::CreateUDiv(), llvm::APInt::exactLogBase2(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getMinSignedBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), I, isKnownToBeAPowerOfTwo(), llvm::APInt::isMinSignedValue(), llvm::APInt::isNonNegative(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), MaskedValueIsZero(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::Instruction::setIsExact(), llvm::SimplifySDivInst(), X, and Y.
visitSelectInst()
Instruction * llvm::InstCombiner::visitSelectInst (SelectInst & SI)
visitSExt()
Instruction * InstCombiner::visitSExt (SExtInst & CI)
Definition at line 1360 of file InstCombineCasts.cpp.
References A, assert(), Builder, canEvaluateSExtd(), commonCastTransforms(), computeKnownBits(), ComputeNumSignBits(), llvm::CastInst::Create(), llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::dbgs(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::KnownBits::isNonNegative(), LLVM_DEBUG, llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::Instruction::user_back(), X, and llvm::CCValAssign::ZExt.
visitShl()
Instruction * InstCombiner::visitShl (BinaryOperator & I)
Definition at line 620 of file InstCombineShifts.cpp.
References Builder, commonShiftTransforms(), ComputeNumSignBits(), llvm::BinaryOperator::Create(), llvm::TargetFolder::CreateAnd(), llvm::TargetFolder::CreateLShr(), llvm::TargetFolder::CreateMul(), llvm::TargetFolder::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APFloat::getAllOnesValue(), llvm::APInt::getHighBitsSet(), getOpcode(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getShl(), llvm::APInt::getSignMask(), llvm::SimplifyQuery::getWithInstruction(), llvm::APInt::getZExtValue(), I, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), MaskedValueIsZero(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::SimplifyShlInst(), and X.
visitShuffleVectorInst()
Instruction * InstCombiner::visitShuffleVectorInst (ShuffleVectorInst & SVI)
Definition at line 1752 of file InstCombineVectorOps.cpp.
References assert(), Builder, canEvaluateShuffled(), canonicalizeInsertSplat(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), evaluateInDifferentElementOrder(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldSelectShuffle(), foldShuffleWithInsert(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getAllOnesValue(), llvm::VectorType::getBitWidth(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::IRBuilderBase::getInt32Ty(), llvm::ShuffleVectorInst::getMask(), llvm::Value::getName(), llvm::SequentialType::getNumElements(), llvm::User::getOperand(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ShuffleVectorInst::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::Type::getVectorNumElements(), llvm::SimplifyQuery::getWithInstruction(), I, Idx, Int32Ty, isShuffleExtractingFromLHS(), isSplat(), llvm::VectorType::isValidElementType(), narrowVectorSelect(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), recognizeIdentityMask(), replaceInstUsesWith(), llvm::User::setOperand(), llvm::SimplifyShuffleVectorInst(), llvm::SmallVectorBase::size(), and llvm::Value::users().
visitSIToFP()
Instruction * InstCombiner::visitSIToFP (CastInst & CI)
Definition at line 1753 of file InstCombineCasts.cpp.
References commonCastTransforms().
visitSRem()
Instruction * InstCombiner::visitSRem (BinaryOperator & I)
Definition at line 1341 of file InstCombineMulDivRem.cpp.
References llvm::InstCombineWorklist::AddValue(), Builder, C, commonIRemTransforms(), llvm::BinaryOperator::CreateNSWNeg(), llvm::IRBuilder< T, Inserter >::CreateSRem(), llvm::TargetFolder::CreateURem(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getNeg(), llvm::APInt::getSignMask(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), MaskedValueIsZero(), llvm::PatternMatch::match(), replaceInstUsesWith(), llvm::SimplifySRemInst(), Worklist, X, and Y.
visitStoreInst()
Instruction * InstCombiner::visitStoreInst (StoreInst & SI)
Definition at line 1393 of file InstCombineLoadStoreAlloca.cpp.
References llvm::InstCombineWorklist::Add(), assert(), canSimplifyNullStoreOrGEP(), combineStoreToValueType(), equivalentAddressValues(), eraseInstFromFunction(), GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::DataLayout::getABITypeAlignment(), llvm::getOrEnforceKnownAlignment(), llvm::DataLayout::getPrefTypeAlignment(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::AAResults::pointsToConstantMemory(), removeBitcastsFromLoadStoreOnMinMax(), replaceGEPIdxWithZero(), SI, unpackStoreToAggregate(), and Worklist.
visitSub()
Instruction * InstCombiner::visitSub (BinaryOperator & I)
Definition at line 1532 of file InstCombineAddSub.cpp.
References A, llvm::AddOne(), assert(), B, Builder, C, computeKnownBits(), llvm::SelectInst::Create(), llvm::TargetFolder::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::TargetFolder::CreateAnd(), llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::TargetFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::BinaryOperator::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::TargetFolder::CreateSDiv(), llvm::CastInst::CreateSExtOrBitCast(), llvm::TargetFolder::CreateShl(), llvm::TargetFolder::CreateSub(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::TargetFolder::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::CastInst::CreateZExtOrBitCast(), llvm::SelectPatternResult::Flavor, llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getNeg(), llvm::APInt::getNullValue(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getSub(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasNUsesOrMore(), I, llvm::IsFreeToInvert(), llvm::APInt::isMask(), llvm::SelectPatternResult::isMinOrMax(), llvm::APInt::isMinSignedValue(), llvm::APInt::isNullValue(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), OptimizePointerDifference(), replaceInstUsesWith(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setIsExact(), SI, llvm::SimplifySubInst(), llvm::SPF_ABS, llvm::SPF_NABS, llvm::AtomicRMWInst::Sub, llvm::SubOne(), std::swap(), X, Y, llvm::Z, and llvm::KnownBits::Zero.
visitSwitchInst()
Instruction * InstCombiner::visitSwitchInst (SwitchInst & SI)
Definition at line 2586 of file InstructionCombining.cpp.
References assert(), Builder, C, computeKnownBits(), llvm::KnownBits::countMinLeadingOnes(), llvm::KnownBits::countMinLeadingZeros(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::IntervalMapImpl::NodeRef::get(), llvm::KnownBits::getBitWidth(), llvm::ConstantExpr::getSub(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::IRBuilderBase::SetInsertPoint(), SI, and llvm::APInt::trunc().
visitTrunc()
Instruction * InstCombiner::visitTrunc (TruncInst & CI)
Definition at line 684 of file InstCombineCasts.cpp.
References A, assert(), Builder, C, canEvaluateTruncated(), commonCastTransforms(), llvm::BinaryOperator::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::dbgs(), foldVecTruncToExtElt(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_NE, llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), LLVM_DEBUG, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), replaceInstUsesWith(), llvm::APInt::shl(), llvm::MCBinaryExpr::Shl, shrinkInsertElt(), shrinkSplatShuffle(), SI, llvm::SPF_UNKNOWN, llvm::Value::takeName(), llvm::APInt::trunc(), llvm::APInt::ult(), and X.
visitUDiv()
Instruction * InstCombiner::visitUDiv (BinaryOperator & I)
Definition at line 914 of file InstCombineMulDivRem.cpp.
References A, B, Builder, commonIDivTransforms(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpUGE(), llvm::TargetFolder::CreateUDiv(), llvm::CastInst::CreateZExtOrBitCast(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APFloat::getAllOnesValue(), llvm::SimplifyQuery::getWithInstruction(), I, llvm::Instruction::insertBefore(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowUDivURem(), replaceInstUsesWith(), llvm::Instruction::setIsExact(), llvm::SimplifyUDivInst(), llvm::SmallVectorBase::size(), llvm::APInt::ushl_ov(), visitUDivOperand(), and X.
visitUIToFP()
Instruction * InstCombiner::visitUIToFP (CastInst & CI)
Definition at line 1749 of file InstCombineCasts.cpp.
References commonCastTransforms().
visitURem()
Instruction * InstCombiner::visitURem (BinaryOperator & I)
Definition at line 1294 of file InstCombineMulDivRem.cpp.
References Builder, commonIRemTransforms(), llvm::SelectInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::CastInst::CreateZExtOrBitCast(), llvm::Constant::getAllOnesValue(), llvm::APFloat::getAllOnesValue(), llvm::APInt::getNullValue(), llvm::SimplifyQuery::getWithInstruction(), I, isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowUDivURem(), replaceInstUsesWith(), llvm::SimplifyURemInst(), and X.
visitVACopyInst()
Instruction * InstCombiner::visitVACopyInst (VACopyInst & I)
Definition at line 1753 of file InstCombineCalls.cpp.
References I, and removeTriviallyEmptyRange().
visitVAStartInst()
Instruction * InstCombiner::visitVAStartInst (VAStartInst & I)
Definition at line 1748 of file InstCombineCalls.cpp.
References I, and removeTriviallyEmptyRange().
visitXor()
Instruction * InstCombiner::visitXor (BinaryOperator & I)
Definition at line 2764 of file InstCombineAndOrXor.cpp.
References A, llvm::InstCombineWorklist::Add(), llvm::AddOne(), B, Builder, C, llvm::SelectInst::Create(), llvm::TargetFolder::CreateAdd(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::TargetFolder::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::TargetFolder::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilder< T, Inserter >::CreateNot(), llvm::TargetFolder::CreateOr(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::TargetFolder::CreateSub(), llvm::TargetFolder::CreateXor(), llvm::SelectPatternResult::Flavor, foldXorToXor(), llvm::IntervalMapImpl::NodeRef::get(), llvm::getInverseMinMaxPred(), llvm::CmpInst::getInversePredicate(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getNot(), llvm::APInt::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasNUses(), llvm::Value::hasNUsesOrMore(), llvm::Value::hasOneUse(), I, llvm::IsFreeToInvert(), llvm::SelectPatternResult::isMinOrMax(), llvm::APInt::isSignMask(), llvm::APInt::lshr(), llvm::MCBinaryExpr::LShr, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), replaceInstUsesWith(), SimplifyBSwap(), llvm::SimplifyXorInst(), sinkNotIntoXor(), std::swap(), llvm::Value::takeName(), visitMaskedMerge(), Worklist, X, llvm::AtomicRMWInst::Xor, and Y.
visitZExt()
Instruction * InstCombiner::visitZExt (ZExtInst & CI)
Definition at line 1088 of file InstCombineCasts.cpp.
References A, assert(), Builder, C, canEvaluateZExtd(), commonCastTransforms(), llvm::BinaryOperator::Create(), llvm::TargetFolder::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::TargetFolder::CreateXor(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::dbgs(), llvm::IntervalMapImpl::NodeRef::get(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), getScalarSizeInBits(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), llvm::Value::hasOneUse(), LLVM_DEBUG, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::replaceAllDbgUsesWith(), replaceInstUsesWith(), llvm::Instruction::user_back(), and X.
Member Data Documentation
Builder
BuilderTy& llvm::InstCombiner::Builder
Definition at line 257 of file InstCombineInternal.h.
Referenced by canonicalizeBitCastExtElt(), combineLoadToNewType(), combineLoadToOperationType(), combineStoreToNewValue(), commonIDivTransforms(), commonShiftTransforms(), evaluateGEPOffsetExpression(), foldCttzCtlz(), FoldShiftByConstant(), foldUDivShl(), foldVecTruncToExtElt(), getShiftedValue(), optimizeIntegerToVectorInsertions(), OptimizePointerDifference(), optimizeVectorResize(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), removeBitcastsFromLoadStoreOnMinMax(), run(), simplifyAllocaArraySize(), simplifyInvariantGroupIntrinsic(), simplifyRangeCheck(), simplifyValueKnownNonZero(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), SliceUpIllegalIntegerPHI(), unpackLoadToAggregate(), unpackStoreToAggregate(), visitAdd(), visitAddrSpaceCast(), visitAnd(), visitAShr(), visitBitCast(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFAdd(), visitFCmpInst(), visitFDiv(), visitFMul(), visitFPTrunc(), visitFSub(), visitGetElementPtrInst(), visitICmpInst(), visitInsertElementInst(), visitIntToPtr(), visitLoadInst(), visitLShr(), visitMul(), visitOr(), visitPtrToInt(), visitSDiv(), visitSExt(), visitShl(), visitShuffleVectorInst(), visitSRem(), visitSub(), visitSwitchInst(), visitTrunc(), visitUDiv(), visitURem(), visitXor(), and visitZExt().
MaxArraySizeForCombine
uint64_t llvm::InstCombiner::MaxArraySizeForCombine
Maximum size of array considered when transforming.
Definition at line 728 of file InstCombineInternal.h.
Referenced by combineInstructionsOverFunction(), unpackLoadToAggregate(), and unpackStoreToAggregate().
Worklist
InstCombineWorklist& llvm::InstCombiner::Worklist
A worklist of the instructions that need to be simplified.
Definition at line 252 of file InstCombineInternal.h.
Referenced by commonPointerCastTransforms(), getShiftedValue(), processUMulZExtIdiom(), run(), simplifyDivRemOfSelectWithZeroOp(), visitBranchInst(), visitExtractElementInst(), visitLoadInst(), visitSRem(), visitStoreInst(), and visitXor().
The documentation for this class was generated from the following files:
lib/Transforms/InstCombine/InstCombineInternal.h
lib/Transforms/InstCombine/InstCombineAddSub.cpp
lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
lib/Transforms/InstCombine/InstCombineAtomicRMW.cpp
lib/Transforms/InstCombine/InstCombineCalls.cpp
lib/Transforms/InstCombine/InstCombineCasts.cpp
lib/Transforms/InstCombine/InstCombineCompares.cpp
lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp
lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
lib/Transforms/InstCombine/InstCombinePHI.cpp
lib/Transforms/InstCombine/InstCombineSelect.cpp
lib/Transforms/InstCombine/InstCombineShifts.cpp
lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp
lib/Transforms/InstCombine/InstCombineVectorOps.cpp
lib/Transforms/InstCombine/InstructionCombining.cpp