LLVM: llvm::MachineLoop Class Reference
llvm::MachineLoop Class Reference
#include "llvm/CodeGen/MachineLoopInfo.h"
Public Member Functions
MachineBasicBlock * getTopBlock ()
Return the "top" block in the loop, which is the first block in the linear layout, ignoring any parts of the loop not contiguous with the part that contains the header.
MachineBasicBlock * getBottomBlock ()
Return the "bottom" block in the loop, which is the last block in the linear layout, ignoring any parts of the loop not contiguous with the part that contains the header.
MachineBasicBlock * findLoopControlBlock ()
Find the block that contains the loop control variable and the loop test.
DebugLoc getStartLoc () const
Return the debug location of the start of this loop.
void dump () const
Public Member Functions inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
unsigned getLoopDepth () const
Return the nesting level of this loop.
MachineBasicBlock * getHeader () const
MachineLoop * getParentLoop () const
void setParentLoop (MachineLoop *L)
This is a raw interface for bypassing addChildLoop.
bool contains (const MachineLoop *L) const
Return true if the specified loop is contained within in this loop.
bool contains (const MachineBasicBlock *BB) const
Return true if the specified basic block is in this loop.
bool contains (const InstT *Inst) const
Return true if the specified instruction is in this loop.
const std::vector< MachineLoop * > & getSubLoops () const
Return the loops contained entirely within this loop.
std::vector< MachineLoop * > & getSubLoopsVector ()
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
ArrayRef< MachineBasicBlock * > getBlocks () const
Get a list of the basic blocks which make up this loop.
block_iterator block_begin () const
block_iterator block_end () const
iterator_range< block_iterator > blocks () const
unsigned getNumBlocks () const
Get the number of blocks in this loop in constant time.
std::vector< MachineBasicBlock * > & getBlocksVector ()
Return a direct, mutable handle to the blocks vector so that we can mutate it efficiently with techniques like std::remove.
SmallPtrSetImpl< const MachineBasicBlock * > & getBlocksSet ()
Return a direct, mutable handle to the blocks set so that we can mutate it efficiently.
const SmallPtrSetImpl< const MachineBasicBlock * > & getBlocksSet () const
Return a direct, immutable handle to the blocks set.
bool isInvalid () const
Return true if this loop is no longer valid.
bool isLoopExiting (const MachineBasicBlock *BB) const
True if terminator in the block can branch to another block that is outside of the current loop.
bool isLoopLatch (const MachineBasicBlock *BB) const
unsigned getNumBackEdges () const
Calculate the number of back edges to the loop header.
void getExitingBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitingBlocks) const
Return all blocks inside the loop that have successors outside of the loop.
MachineBasicBlock * getExitingBlock () const
If getExitingBlocks would return exactly one block, return that block.
void getExitBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitBlocks) const
Return all of the successor blocks of this loop.
MachineBasicBlock * getExitBlock () const
If getExitBlocks would return exactly one block, return that block.
bool hasDedicatedExits () const
Return true if no exit block for the loop has a predecessor that is outside the loop.
void getUniqueExitBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitBlocks) const
Return all unique successor blocks of this loop.
void getUniqueNonLatchExitBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitBlocks) const
Return all unique successor blocks of this loop except successors from Latch block are not considered.
MachineBasicBlock * getUniqueExitBlock () const
If getUniqueExitBlocks would return exactly one block, return that block.
void getExitEdges (SmallVectorImpl< Edge > &ExitEdges) const
Return all pairs of (inside_block,outside_block).
MachineBasicBlock * getLoopPreheader () const
If there is a preheader for this loop, return it.
MachineBasicBlock * getLoopPredecessor () const
If the given loop's header has exactly one unique predecessor outside the loop, return it.
MachineBasicBlock * getLoopLatch () const
If there is a single latch block for this loop, return it.
void getLoopLatches (SmallVectorImpl< MachineBasicBlock * > &LoopLatches) const
Return all loop latch blocks of this loop.
SmallVector< const MachineLoop *, 4 > getLoopsInPreorder () const
Return all loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
SmallVector< MachineLoop *, 4 > getLoopsInPreorder ()
void addBasicBlockToLoop (MachineBasicBlock *NewBB, LoopInfoBase< MachineBasicBlock, MachineLoop > &LI)
This method is used by other analyses to update loop information.
void replaceChildLoopWith (MachineLoop *OldChild, MachineLoop *NewChild)
This is used when splitting loops up.
void addChildLoop (MachineLoop *NewChild)
Add the specified loop to be a child of this loop.
MachineLoop * removeChildLoop (iterator I)
This removes the specified child from being a subloop of this loop.
MachineLoop * removeChildLoop (MachineLoop *Child)
This removes the specified child from being a subloop of this loop.
void addBlockEntry (MachineBasicBlock *BB)
This adds a basic block directly to the basic block list.
void reverseBlock (unsigned from)
interface to reverse Blocks[from, end of loop] in this loop
void reserveBlocks (unsigned size)
interface to do reserve() for Blocks
void moveToHeader (MachineBasicBlock *BB)
This method is used to move BB (which must be part of this loop) to be the loop header of the loop (the block that dominates all others).
void removeBlockFromLoop (MachineBasicBlock *BB)
This removes the specified basic block from the current loop, updating the Blocks as appropriate.
void verifyLoop () const
Verify loop structure.
void verifyLoopNest (DenseSet< const MachineLoop * > *Loops) const
Verify loop structure of this loop and all nested loops.
bool isAnnotatedParallel () const
Returns true if the loop is annotated parallel.
void print (raw_ostream &OS, unsigned Depth=0, bool Verbose=false) const
Print loop with all the BBs inside it.
Friends
class LoopInfoBase< MachineBasicBlock, MachineLoop >
Additional Inherited Members
Public Types inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
typedef std::vector< MachineLoop * >::const_iterator iterator
typedef std::vector< MachineLoop * >::const_reverse_iterator reverse_iterator
typedef ArrayRef< MachineBasicBlock * >::const_iterator block_iterator
typedef std::pair< MachineBasicBlock *, MachineBasicBlock * > Edge
Edge type.
Static Public Member Functions inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
static void getInnerLoopsInPreorder (const MachineLoop &L, SmallVectorImpl< Type > &PreOrderLoops)
Return all inner loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
Protected Member Functions inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
LoopBase ()
This creates an empty loop.
LoopBase (MachineBasicBlock *BB)
~LoopBase ()
Detailed Description
Definition at line 44 of file MachineLoopInfo.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MachineLoop::dump () const
Definition at line 142 of file MachineLoopInfo.cpp.
References llvm::dbgs(), and llvm::LoopBase< MachineBasicBlock, MachineLoop >::print().
findLoopControlBlock()
MachineBasicBlock * MachineLoop::findLoopControlBlock ()
Find the block that contains the loop control variable and the loop test.
This will return the latch block if it's one of the exiting blocks. Otherwise, return the exiting block. Return 'null' when multiple exiting blocks are present.
Definition at line 80 of file MachineLoopInfo.cpp.
References llvm::LoopBase< MachineBasicBlock, MachineLoop >::getExitingBlock(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::getLoopLatch(), and llvm::LoopBase< MachineBasicBlock, MachineLoop >::isLoopExiting().
getBottomBlock()
MachineBasicBlock * MachineLoop::getBottomBlock ()
Return the "bottom" block in the loop, which is the last block in the linear layout, ignoring any parts of the loop not contiguous with the part that contains the header.
Definition at line 65 of file MachineLoopInfo.cpp.
References llvm::LoopBase< MachineBasicBlock, MachineLoop >::contains(), llvm::MachineFunction::end(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::getHeader(), llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::MachineBasicBlock::getParent().
Referenced by llvm::HexagonInstrInfo::analyzeLoop(), and llvm::PPCInstrInfo::analyzeLoop().
getStartLoc()
DebugLoc MachineLoop::getStartLoc () const
Return the debug location of the start of this loop.
This looks for a BB terminating instruction with a known debug location by looking at the preheader and header blocks. If it cannot find a terminating instruction with location information, it returns an unknown location.
Definition at line 90 of file MachineLoopInfo.cpp.
References llvm::LoopBase< MachineBasicBlock, MachineLoop >::getHeader(), and llvm::LoopBase< MachineBasicBlock, MachineLoop >::getLoopPreheader().
getTopBlock()
MachineBasicBlock * MachineLoop::getTopBlock ()
Return the "top" block in the loop, which is the first block in the linear layout, ignoring any parts of the loop not contiguous with the part that contains the header.
Definition at line 50 of file MachineLoopInfo.cpp.
References llvm::MachineFunction::begin(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::contains(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::getHeader(), llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::MachineBasicBlock::getParent().
Friends And Related Function Documentation
LoopInfoBase< MachineBasicBlock, MachineLoop >
friend class LoopInfoBase< MachineBasicBlock, MachineLoop > friend
Definition at line 69 of file MachineLoopInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineLoopInfo.h
lib/CodeGen/MachineLoopInfo.cpp