LLVM: llvm::WebAssemblyExceptionInfo Class Reference
llvm::WebAssemblyExceptionInfo Class Reference final
#include "Target/WebAssembly/WebAssemblyExceptionInfo.h"
Public Member Functions
WebAssemblyExceptionInfo ()
~WebAssemblyExceptionInfo () override
WebAssemblyExceptionInfo (const WebAssemblyExceptionInfo &)=delete
WebAssemblyExceptionInfo & operator= (const WebAssemblyExceptionInfo &)=delete
bool runOnMachineFunction (MachineFunction &) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void recalculate (MachineDominatorTree &MDT, const MachineDominanceFrontier &MDF)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
bool empty () const
WebAssemblyException * getExceptionFor (const MachineBasicBlock *MBB) const
void changeExceptionFor (MachineBasicBlock *MBB, WebAssemblyException *WE)
void addTopLevelException (WebAssemblyException *WE)
void print (raw_ostream &OS, const Module *M=nullptr) const override
print - Print out the internal state of the pass.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 117 of file WebAssemblyExceptionInfo.h.
Constructor & Destructor Documentation
WebAssemblyExceptionInfo() [1/2]
llvm::WebAssemblyExceptionInfo::WebAssemblyExceptionInfo () inline
Definition at line 129 of file WebAssemblyExceptionInfo.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeWebAssemblyExceptionInfoPass().
~WebAssemblyExceptionInfo()
llvm::WebAssemblyExceptionInfo::~WebAssemblyExceptionInfo () inline override
Definition at line 132 of file WebAssemblyExceptionInfo.h.
References releaseMemory().
WebAssemblyExceptionInfo() [2/2]
llvm::WebAssemblyExceptionInfo::WebAssemblyExceptionInfo (const WebAssemblyExceptionInfo &) delete
Member Function Documentation
addTopLevelException()
void llvm::WebAssemblyExceptionInfo::addTopLevelException (WebAssemblyException * WE) inline
Definition at line 159 of file WebAssemblyExceptionInfo.h.
References assert(), and llvm::WebAssemblyException::getParentException().
Referenced by recalculate().
changeExceptionFor()
void llvm::WebAssemblyExceptionInfo::changeExceptionFor (MachineBasicBlock * MBB, WebAssemblyException * WE) inline
Definition at line 151 of file WebAssemblyExceptionInfo.h.
empty()
bool llvm::WebAssemblyExceptionInfo::empty () const inline
Definition at line 143 of file WebAssemblyExceptionInfo.h.
getAnalysisUsage()
void WebAssemblyExceptionInfo::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 88 of file WebAssemblyExceptionInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getExceptionFor()
WebAssemblyException * llvm::WebAssemblyExceptionInfo::getExceptionFor (const MachineBasicBlock * MBB) const inline
Definition at line 147 of file WebAssemblyExceptionInfo.h.
Referenced by recalculate().
operator=()
WebAssemblyExceptionInfo & llvm::WebAssemblyExceptionInfo::operator= (const WebAssemblyExceptionInfo &) delete
print()
void WebAssemblyExceptionInfo::print (raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 182 of file WebAssemblyExceptionInfo.cpp.
References llvm::WebAssemblyException::print().
recalculate()
void WebAssemblyExceptionInfo::recalculate (MachineDominatorTree & MDT, const MachineDominanceFrontier & MDF)
Definition at line 45 of file WebAssemblyExceptionInfo.cpp.
References llvm::WebAssemblyException::addBlock(), addTopLevelException(), getExceptionFor(), llvm::WebAssemblyException::getParentException(), llvm::MachineBasicBlock::isEHPad(), llvm::post_order(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
releaseMemory()
void WebAssemblyExceptionInfo::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 82 of file WebAssemblyExceptionInfo.cpp.
References llvm::DeleteContainerPointers().
Referenced by ~WebAssemblyExceptionInfo().
runOnMachineFunction()
WebAssembly Exception true bool WebAssemblyExceptionInfo::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 34 of file WebAssemblyExceptionInfo.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Member Data Documentation
ID
char WebAssemblyExceptionInfo::ID = 0 static
Definition at line 128 of file WebAssemblyExceptionInfo.h.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyExceptionInfo.h
lib/Target/WebAssembly/WebAssemblyExceptionInfo.cpp