LLVM: llvm::PostDominatorTreePrinterPass Class Reference
llvm::PostDominatorTreePrinterPass Class Reference
Printer pass for the PostDominatorTree.
#include "llvm/Analysis/PostDominators.h"
Public Member Functions
PostDominatorTreePrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PostDominatorTreePrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the PostDominatorTree.
Definition at line 56 of file PostDominators.h.
Constructor & Destructor Documentation
PostDominatorTreePrinterPass()
PostDominatorTreePrinterPass::PostDominatorTreePrinterPass (raw_ostream & OS) explicit
Definition at line 75 of file PostDominators.cpp.
Member Function Documentation
run()
PreservedAnalyses PostDominatorTreePrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 79 of file PostDominators.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/PostDominators.h
lib/Analysis/PostDominators.cpp