LLVM: llvm::InjectorIRStrategy Class Reference
llvm::InjectorIRStrategy Class Reference
Strategy that injects operations into the function.
#include "llvm/FuzzMutate/IRMutator.h"
Public Member Functions
InjectorIRStrategy (std::vector< fuzzerop::OpDescriptor > &&Operations)
uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override
Provide a weight to bias towards choosing this strategy for a mutation.
void mutate (Function &F, RandomIRBuilder &IB) override
void mutate (BasicBlock &BB, RandomIRBuilder &IB) override
virtual void mutate (Module &M, RandomIRBuilder &IB)
virtual void mutate (Function &F, RandomIRBuilder &IB)
virtual void mutate (BasicBlock &BB, RandomIRBuilder &IB)
virtual void mutate (Instruction &I, RandomIRBuilder &IB)
Public Member Functions inherited from llvm::IRMutationStrategy
virtual ~IRMutationStrategy ()=default
virtual uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight)=0
Provide a weight to bias towards choosing this strategy for a mutation.
Static Public Member Functions
static std::vector< fuzzerop::OpDescriptor > getDefaultOps ()
Detailed Description
Strategy that injects operations into the function.
Definition at line 74 of file IRMutator.h.
Constructor & Destructor Documentation
InjectorIRStrategy()
llvm::InjectorIRStrategy::InjectorIRStrategy (std::vector< fuzzerop::OpDescriptor > && Operations) inline
Definition at line 81 of file IRMutator.h.
Member Function Documentation
getDefaultOps()
std::vector< fuzzerop::OpDescriptor > InjectorIRStrategy::getDefaultOps () static
Definition at line 84 of file IRMutator.cpp.
References llvm::describeFuzzerAggregateOps(), llvm::describeFuzzerControlFlowOps(), llvm::describeFuzzerFloatOps(), llvm::describeFuzzerIntOps(), llvm::describeFuzzerPointerOps(), and llvm::describeFuzzerVectorOps().
getWeight()
uint64_t llvm::InjectorIRStrategy::getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) inline override virtual
Provide a weight to bias towards choosing this strategy for a mutation.
The value of the weight is arbitrary, but a good default is "the number of distinct ways in which this strategy can mutate a unit". This can also be used to prefer strategies that shrink the overall size of the result when we start getting close to MaxSize.
Implements llvm::IRMutationStrategy.
Definition at line 85 of file IRMutator.h.
mutate() [1/6]
void IRMutationStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 50 of file IRMutator.cpp.
mutate() [2/6]
void InjectorIRStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 106 of file IRMutator.cpp.
References llvm::RandomIRBuilder::connectToSink(), E, llvm::BasicBlock::end(), llvm::RandomIRBuilder::findOrCreateSource(), llvm::BasicBlock::getFirstInsertionPt(), I, llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::RandomIRBuilder::Rand, and llvm::SmallVectorBase::size().
mutate() [3/6]
void IRMutationStrategy::mutate (Function & F, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 49 of file IRMutator.cpp.
mutate() [4/6]
void InjectorIRStrategy::mutate (Function & F, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 79 of file IRMutator.cpp.
References eliminateDeadCode(), F, and llvm::IRMutationStrategy::mutate().
mutate() [5/6]
virtual void llvm::IRMutationStrategy::mutate (Instruction & I, RandomIRBuilder & IB) inline virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 51 of file IRMutator.h.
mutate() [6/6]
void IRMutationStrategy::mutate (Module & M, RandomIRBuilder & IB) virtual
Mutators for each IR unit. By default these forward to a contained instance of the next smaller unit.
Reimplemented from llvm::IRMutationStrategy.
Definition at line 48 of file IRMutator.cpp.
The documentation for this class was generated from the following files:
include/llvm/FuzzMutate/IRMutator.h
lib/FuzzMutate/IRMutator.cpp