LLVM: llvm::TargetLoweringObjectFile Class Reference
llvm::TargetLoweringObjectFile Class Reference abstract
#include "llvm/Target/TargetLoweringObjectFile.h"
Public Member Functions
TargetLoweringObjectFile ()=default
TargetLoweringObjectFile (const TargetLoweringObjectFile &)=delete
TargetLoweringObjectFile & operator= (const TargetLoweringObjectFile &)=delete
virtual ~TargetLoweringObjectFile ()
MCContext & getContext () const
Mangler & getMangler () const
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
This method must be called before any actual lowering is done.
virtual void emitPersonalityValue (MCStreamer &Streamer, const DataLayout &TM, const MCSymbol *Sym) const
virtual void emitModuleMetadata (MCStreamer &Streamer, Module &M) const
Emit the module-level metadata that the platform cares about.
virtual void getModuleMetadata (Module &M)
Get the module-level metadata that the platform cares about.
virtual MCSection * getSectionForConstant (const DataLayout &DL, SectionKind Kind, const Constant *C, unsigned &Align) const
Given a constant with the SectionKind, return a section that it should be placed in.
MCSection * SectionForGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
MCSection * SectionForGlobal (const GlobalObject *GO, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
virtual void getNameWithPrefix (SmallVectorImpl< char > &OutName, const GlobalValue *GV, const TargetMachine &TM) const
virtual MCSection * getSectionForJumpTable (const Function &F, const TargetMachine &TM) const
virtual bool shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function &F) const
virtual MCSection * getExplicitSectionGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const =0
Targets should implement this method to assign a section to globals with an explicit section specfied.
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, const TargetMachine &TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, const TargetMachine &TM, MachineModuleInfo *MMI) const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getTTypeEncoding () const
unsigned getCallSiteEncoding () const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
virtual const MCExpr * lowerRelativeReference (const GlobalValue *LHS, const GlobalValue *RHS, const TargetMachine &TM) const
bool supportIndirectSymViaGOTPCRel () const
Target supports replacing a data "PC"-relative access to a symbol through another symbol, by accessing the later via a GOT entry instead?
bool supportGOTPCRelWithOffset () const
Target GOT "PC"-relative relocation supports encoding an additional binary expression with an offset?
bool supportDebugThreadLocalLocation () const
Target supports TLS offset relocation in debug section?
virtual const MCExpr * getIndirectSymViaGOTPCRel (const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Get the target specific PC relative GOT entry relocation.
virtual void emitLinkerFlagsForGlobal (raw_ostream &OS, const GlobalValue *GV) const
virtual void emitLinkerFlagsForUsed (raw_ostream &OS, const GlobalValue *GV) const
virtual MCSection * getSectionForCommandLines () const
If supported, return the section to use for the llvm.commandline metadata.
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (const Triple &TT, bool PIC, MCContext &ctx, bool LargeCodeModel=false)
bool getSupportsWeakOmittedEHFrame () const
bool getSupportsCompactUnwindWithoutEHFrame () const
bool getOmitDwarfIfHaveCompactUnwind () const
bool getCommDirectiveSupportsAlignment () const
unsigned getFDEEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
MCSection * getTextSection () const
MCSection * getDataSection () const
MCSection * getBSSSection () const
MCSection * getReadOnlySection () const
MCSection * getLSDASection () const
MCSection * getCompactUnwindSection () const
MCSection * getDwarfAbbrevSection () const
MCSection * getDwarfInfoSection () const
MCSection * getDwarfInfoSection (uint64_t Hash) const
MCSection * getDwarfLineSection () const
MCSection * getDwarfLineStrSection () const
MCSection * getDwarfFrameSection () const
MCSection * getDwarfPubNamesSection () const
MCSection * getDwarfPubTypesSection () const
MCSection * getDwarfGnuPubNamesSection () const
MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
MCSection * getDwarfStrSection () const
MCSection * getDwarfLocSection () const
MCSection * getDwarfARangesSection () const
MCSection * getDwarfRangesSection () const
MCSection * getDwarfRnglistsSection () const
MCSection * getDwarfLoclistsSection () const
MCSection * getDwarfMacinfoSection () const
MCSection * getDwarfDebugNamesSection () const
MCSection * getDwarfAccelNamesSection () const
MCSection * getDwarfAccelObjCSection () const
MCSection * getDwarfAccelNamespaceSection () const
MCSection * getDwarfAccelTypesSection () const
MCSection * getDwarfInfoDWOSection () const
MCSection * getDwarfTypesSection (uint64_t Hash) const
MCSection * getDwarfTypesDWOSection () const
MCSection * getDwarfAbbrevDWOSection () const
MCSection * getDwarfStrDWOSection () const
MCSection * getDwarfLineDWOSection () const
MCSection * getDwarfLocDWOSection () const
MCSection * getDwarfStrOffDWOSection () const
MCSection * getDwarfStrOffSection () const
MCSection * getDwarfAddrSection () const
MCSection * getDwarfRnglistsDWOSection () const
MCSection * getDwarfCUIndexSection () const
MCSection * getDwarfTUIndexSection () const
MCSection * getDwarfSwiftASTSection () const
MCSection * getCOFFDebugSymbolsSection () const
MCSection * getCOFFDebugTypesSection () const
MCSection * getCOFFGlobalTypeHashesSection () const
MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
MCSection * getTLSBSSSection () const
MCSection * getStackMapSection () const
MCSection * getFaultMapSection () const
MCSection * getRemarksSection () const
MCSection * getStackSizesSection (const MCSection &TextSec) const
MCSection * getDataRelROSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getMergeableConst32Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getConstDataCoalSection () const
const MCSection * getDataCommonSection () const
MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
MCSection * getLazySymbolPointerSection () const
MCSection * getNonLazySymbolPointerSection () const
MCSection * getThreadLocalPointerSection () const
MCSection * getDrectveSection () const
MCSection * getPDataSection () const
MCSection * getXDataSection () const
MCSection * getSXDataSection () const
MCSection * getGFIDsSection () const
MCSection * getEHFrameSection ()
Environment getObjectFileType () const
bool isPositionIndependent () const
const Triple & getTargetTriple () const
void setSDKVersion (const VersionTuple &TheSDKVersion)
const VersionTuple & getSDKVersion () const
Static Public Member Functions
static SectionKind getKindForGlobal (const GlobalObject *GO, const TargetMachine &TM)
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
Protected Member Functions
virtual MCSection * SelectSectionForGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const =0
Protected Attributes
bool SupportIndirectSymViaGOTPCRel = false
bool SupportGOTPCRelWithOffset = true
bool SupportDebugThreadLocalLocation = true
unsigned PersonalityEncoding = 0
PersonalityEncoding, LSDAEncoding, TTypeEncoding - Some encoding values for EH.
unsigned LSDAEncoding = 0
unsigned TTypeEncoding = 0
unsigned CallSiteEncoding = 0
MCSection * StaticCtorSection = nullptr
This section contains the static constructor pointer list.
MCSection * StaticDtorSection = nullptr
This section contains the static destructor pointer list.
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment
True if .comm supports alignment.
bool SupportsWeakOmittedEHFrame
True if target object file supports a weak_definition of constant 0 for an omitted EH frame.
bool SupportsCompactUnwindWithoutEHFrame
True if the target object file supports emitting a compact unwind section without an associated EH frame section.
bool OmitDwarfIfHaveCompactUnwind
OmitDwarfIfHaveCompactUnwind - True if the target object file supports having some functions with compact unwind and other with dwarf unwind.
unsigned FDECFIEncoding = 0
FDE CFI encoding.
unsigned CompactUnwindDwarfEHFrameOnly
Compact unwind encoding indicating that we should emit only an EH frame.
MCSection * TextSection
Section directive for standard text.
MCSection * DataSection
Section directive for standard data.
MCSection * BSSSection
Section that is default initialized to zero.
MCSection * ReadOnlySection
Section that is readonly and can contain arbitrary initialized data.
MCSection * LSDASection
If exception handling is supported by the target, this is the section the Language Specific Data Area information is emitted to.
MCSection * CompactUnwindSection
If exception handling is supported by the target and the target can support a compact representation of the CIE and FDE, this is the section to emit them into.
MCSection * DwarfAbbrevSection
MCSection * DwarfInfoSection
MCSection * DwarfLineSection
MCSection * DwarfLineStrSection
MCSection * DwarfFrameSection
MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
MCSection * DwarfStrSection
MCSection * DwarfLocSection
MCSection * DwarfARangesSection
MCSection * DwarfRangesSection
MCSection * DwarfMacinfoSection
MCSection * DwarfPubNamesSection
MCSection * DwarfDebugNamesSection
Accelerator table sections.
MCSection * DwarfAccelNamesSection
MCSection * DwarfAccelObjCSection
MCSection * DwarfAccelNamespaceSection
MCSection * DwarfAccelTypesSection
MCSection * DwarfInfoDWOSection
MCSection * DwarfTypesDWOSection
MCSection * DwarfAbbrevDWOSection
MCSection * DwarfStrDWOSection
MCSection * DwarfLineDWOSection
MCSection * DwarfLocDWOSection
MCSection * DwarfStrOffDWOSection
MCSection * DwarfStrOffSection
The DWARF v5 string offset and address table sections.
MCSection * DwarfAddrSection
MCSection * DwarfRnglistsSection
The DWARF v5 range list section.
MCSection * DwarfLoclistsSection
The DWARF v5 locations list section.
MCSection * DwarfRnglistsDWOSection
The DWARF v5 range list section for fission.
MCSection * DwarfCUIndexSection
MCSection * DwarfTUIndexSection
MCSection * DwarfGnuPubNamesSection
Section for newer gnu pubnames.
MCSection * DwarfGnuPubTypesSection
Section for newer gnu pubtypes.
MCSection * DwarfSwiftASTSection
MCSection * COFFDebugSymbolsSection
MCSection * COFFDebugTypesSection
MCSection * COFFGlobalTypeHashesSection
MCSection * TLSExtraDataSection
Extra TLS Variable Data section.
MCSection * TLSDataSection
Section directive for Thread Local data. ELF, MachO, COFF, and Wasm.
MCSection * TLSBSSSection
Section directive for Thread Local uninitialized data.
MCSection * StackMapSection
StackMap section.
MCSection * FaultMapSection
FaultMap section.
MCSection * RemarksSection
Remarks section.
MCSection * EHFrameSection
EH frame section.
MCSection * StackSizesSection
Section containing metadata on function stack sizes.
DenseMap< const MCSymbol *, unsigned > StackSizesUniquing
MCSection * DataRelROSection
MCSection * MergeableConst4Section
MCSection * MergeableConst8Section
MCSection * MergeableConst16Section
MCSection * MergeableConst32Section
MCSection * TLSTLVSection
Section for thread local structure information.
const MCSection * TLSThreadInitSection
Section for thread local data initialization functions.
MCSection * CStringSection
MCSection * UStringSection
MCSection * TextCoalSection
MCSection * ConstTextCoalSection
MCSection * ConstDataSection
MCSection * DataCoalSection
MCSection * ConstDataCoalSection
MCSection * DataCommonSection
MCSection * DataBSSSection
MCSection * FourByteConstantSection
MCSection * EightByteConstantSection
MCSection * SixteenByteConstantSection
MCSection * LazySymbolPointerSection
MCSection * NonLazySymbolPointerSection
MCSection * ThreadLocalPointerSection
MCSection * DrectveSection
COFF specific sections.
MCSection * PDataSection
MCSection * XDataSection
MCSection * SXDataSection
MCSection * GFIDsSection
Additional Inherited Members
Public Types inherited from llvm::MCObjectFileInfo
enum Environment {
IsMachO , IsELF , IsCOFF , IsWasm ,
IsXCOFF
}
Detailed Description
Definition at line 38 of file TargetLoweringObjectFile.h.
Constructor & Destructor Documentation
TargetLoweringObjectFile() [1/2]
llvm::TargetLoweringObjectFile::TargetLoweringObjectFile () default
TargetLoweringObjectFile() [2/2]
llvm::TargetLoweringObjectFile::TargetLoweringObjectFile (const TargetLoweringObjectFile &) delete
~TargetLoweringObjectFile()
TargetLoweringObjectFile::~TargetLoweringObjectFile () virtual
Definition at line 53 of file TargetLoweringObjectFile.cpp.
Member Function Documentation
emitLinkerFlagsForGlobal()
virtual void llvm::TargetLoweringObjectFile::emitLinkerFlagsForGlobal (raw_ostream & OS, const GlobalValue * GV) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileCOFF.
Definition at line 202 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization().
emitLinkerFlagsForUsed()
virtual void llvm::TargetLoweringObjectFile::emitLinkerFlagsForUsed (raw_ostream & OS, const GlobalValue * GV) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileCOFF.
Definition at line 205 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization().
emitModuleMetadata()
virtual void llvm::TargetLoweringObjectFile::emitModuleMetadata (MCStreamer & Streamer, Module & M) const inline virtual
Emit the module-level metadata that the platform cares about.
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::TargetLoweringObjectFileCOFF.
Definition at line 81 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization().
emitPersonalityValue()
void TargetLoweringObjectFile::emitPersonalityValue (MCStreamer & Streamer, const DataLayout & TM, const MCSymbol * Sym) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 133 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::endModule().
getCallSiteEncoding()
unsigned llvm::TargetLoweringObjectFile::getCallSiteEncoding () const inline
Definition at line 151 of file TargetLoweringObjectFile.h.
References CallSiteEncoding.
Referenced by llvm::EHStreamer::emitExceptionTable().
getCFIPersonalitySymbol()
MCSymbol * TargetLoweringObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, const TargetMachine & TM, MachineModuleInfo * MMI) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 127 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::beginFragment(), and llvm::WinException::beginFunclet().
getContext()
MCContext & llvm::TargetLoweringObjectFile::getContext () const inline
Definition at line 69 of file TargetLoweringObjectFile.h.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::MipsTargetObjectFile::getDebugThreadLocalSymbol(), llvm::X86ELFTargetObjectFile::getDebugThreadLocalSymbol(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileELF::getSectionForCommandLines(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), llvm::TargetLoweringObjectFileWasm::getStaticCtorSection(), llvm::TargetLoweringObjectFileELF::getStaticDtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection(), llvm::TargetMachine::getSymbol(), getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), getTTypeReference(), llvm::HexagonTargetObjectFile::Initialize(), llvm::LanaiTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::RISCVELFTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::TargetLoweringObjectFileWasm::InitializeWasm(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal().
getDebugThreadLocalSymbol()
const MCExpr * TargetLoweringObjectFile::getDebugThreadLocalSymbol (const MCSymbol * Sym) const virtual
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Reimplemented in llvm::ARMElfTargetObjectFile, llvm::MipsTargetObjectFile, and llvm::X86ELFTargetObjectFile.
Definition at line 336 of file TargetLoweringObjectFile.cpp.
References llvm::LiveRangeEdit::create().
Referenced by llvm::DwarfCompileUnit::addLocationAttribute().
getExplicitSectionGlobal()
virtual MCSection * llvm::TargetLoweringObjectFile::getExplicitSectionGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) const pure virtual
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GO->hasSection() is true.
Implemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileWasm, llvm::AMDGPUTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::HexagonTargetObjectFile, llvm::NVPTXTargetObjectFile, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
getIndirectSymViaGOTPCRel()
virtual const MCExpr * llvm::TargetLoweringObjectFile::getIndirectSymViaGOTPCRel (const MCSymbol * Sym, const MCValue & MV, int64_t Offset, MachineModuleInfo * MMI, MCStreamer & Streamer) const inline virtual
Get the target specific PC relative GOT entry relocation.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 194 of file TargetLoweringObjectFile.h.
Referenced by handleIndirectSymViaGOTPCRel().
getKindForGlobal()
SectionKind TargetLoweringObjectFile::getKindForGlobal (const GlobalObject * GO, const TargetMachine & TM) static
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
getKindForGlobal - This is a top-level target-independent classifier for a global object.
Given a global variable and information from the TM, this function classifies the global in a target independent manner. This function may be overridden by the target implementation.
Definition at line 143 of file TargetLoweringObjectFile.cpp.
References assert(), C, llvm::SectionKind::getBSS(), llvm::SectionKind::getBSSExtern(), llvm::SectionKind::getBSSLocal(), llvm::SectionKind::getCommon(), llvm::SectionKind::getData(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeable4ByteCString(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst32(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::isDeclaration(), IsNullTerminatedString(), isSuitableForBSS(), llvm::Reloc::ROPI, llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, and llvm::Reloc::Static.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), llvm::LanaiTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), and SectionForGlobal().
getLSDAEncoding()
unsigned llvm::TargetLoweringObjectFile::getLSDAEncoding () const inline
Definition at line 149 of file TargetLoweringObjectFile.h.
References LSDAEncoding.
Referenced by llvm::DwarfCFIException::beginFragment(), llvm::DwarfCFIException::beginFunction(), and llvm::WinException::beginFunction().
getMangler()
Mangler & llvm::TargetLoweringObjectFile::getMangler () const inline
Definition at line 70 of file TargetLoweringObjectFile.h.
Referenced by llvm::TargetLoweringObjectFileCOFF::emitLinkerFlagsForGlobal(), llvm::TargetLoweringObjectFileCOFF::emitLinkerFlagsForUsed(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), llvm::TargetLoweringObjectFileCOFF::getNameWithPrefix(), llvm::AArch64_MachoTargetObjectFile::getNameWithPrefix(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal().
getModuleMetadata()
virtual void llvm::TargetLoweringObjectFile::getModuleMetadata (Module & M) inline virtual
Get the module-level metadata that the platform cares about.
Reimplemented in llvm::RISCVELFTargetObjectFile.
Definition at line 84 of file TargetLoweringObjectFile.h.
getNameWithPrefix()
void TargetLoweringObjectFile::getNameWithPrefix (SmallVectorImpl< char > & OutName, const GlobalValue * GV, const TargetMachine & TM) const virtual
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileCOFF, and llvm::AArch64_MachoTargetObjectFile.
Definition at line 342 of file TargetLoweringObjectFile.cpp.
References llvm::Mangler::getNameWithPrefix().
Referenced by llvm::TargetMachine::getNameWithPrefix().
getPersonalityEncoding()
unsigned llvm::TargetLoweringObjectFile::getPersonalityEncoding () const inline
Definition at line 148 of file TargetLoweringObjectFile.h.
References PersonalityEncoding.
Referenced by llvm::DwarfCFIException::beginFragment(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::DwarfCFIException::endModule(), and llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol().
getSectionForCommandLines()
virtual MCSection * llvm::TargetLoweringObjectFile::getSectionForCommandLines () const inline virtual
If supported, return the section to use for the llvm.commandline metadata.
Otherwise, return nullptr.
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 210 of file TargetLoweringObjectFile.h.
getSectionForConstant()
MCSection * TargetLoweringObjectFile::getSectionForConstant (const DataLayout & DL, SectionKind Kind, const Constant * C, unsigned & Align) const virtual
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileCOFF, llvm::LanaiTargetObjectFile, llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, llvm::RISCVELFTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 295 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::DataSection, and llvm::MCObjectFileInfo::ReadOnlySection.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::EmitConstantPool(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), and getSectionForJumpTable().
getSectionForJumpTable()
MCSection * TargetLoweringObjectFile::getSectionForJumpTable (const Function & F, const TargetMachine & TM) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, and llvm::TargetLoweringObjectFileCOFF.
Definition at line 270 of file TargetLoweringObjectFile.cpp.
References F, llvm::SectionKind::getReadOnly(), and getSectionForConstant().
Referenced by llvm::AsmPrinter::EmitJumpTableInfo().
getStaticCtorSection()
virtual MCSection * llvm::TargetLoweringObjectFile::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileWasm.
Definition at line 156 of file TargetLoweringObjectFile.h.
References StaticCtorSection.
getStaticDtorSection()
virtual MCSection * llvm::TargetLoweringObjectFile::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileWasm.
Definition at line 161 of file TargetLoweringObjectFile.h.
References StaticDtorSection.
getSymbolWithGlobalValueBase()
MCSymbol * TargetLoweringObjectFile::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix, const TargetMachine & TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 116 of file TargetLoweringObjectFile.cpp.
References llvm::SmallString< InternalLen >::append(), assert(), llvm::StringRef::begin(), llvm::StringRef::empty(), llvm::StringRef::end(), llvm::MCContext::getOrCreateSymbol(), and llvm::GlobalValue::getParent().
Referenced by llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::AsmPrinter::getSymbolWithGlobalValueBase(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and llvm::SparcELFTargetObjectFile::getTTypeGlobalReference().
getTTypeEncoding()
unsigned llvm::TargetLoweringObjectFile::getTTypeEncoding () const inline
Definition at line 150 of file TargetLoweringObjectFile.h.
References TTypeEncoding.
Referenced by llvm::EHStreamer::emitExceptionTable().
getTTypeGlobalReference()
const MCExpr * TargetLoweringObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const virtual
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
getTTypeGlobalReference - Return an MCExpr to use for a reference to the specified global variable from exception handling information.
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::AArch64_MachoTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::SparcELFTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 307 of file TargetLoweringObjectFile.cpp.
References llvm::LiveRangeEdit::create(), getContext(), getTTypeReference(), and llvm::Ref.
Referenced by llvm::AsmPrinter::EmitTTypeReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
getTTypeReference()
const MCExpr * TargetLoweringObjectFile::getTTypeReference (const MCSymbolRefExpr * Sym, unsigned Encoding, MCStreamer & Streamer) const
Definition at line 316 of file TargetLoweringObjectFile.cpp.
References llvm::LiveRangeEdit::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), getContext(), and llvm::report_fatal_error().
Referenced by getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
Initialize()
void TargetLoweringObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) virtual
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileCOFF, llvm::ARMElfTargetObjectFile, llvm::AVRTargetObjectFile, llvm::HexagonTargetObjectFile, llvm::LanaiTargetObjectFile, llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, llvm::RISCVELFTargetObjectFile, llvm::SparcELFTargetObjectFile, llvm::WebAssemblyTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 39 of file TargetLoweringObjectFile.cpp.
References CallSiteEncoding, llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_uleb128, llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::CodeModel::Large, LSDAEncoding, PersonalityEncoding, and TTypeEncoding.
Referenced by llvm::TargetLoweringObjectFileELF::Initialize(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringObjectFileCOFF::Initialize(), and llvm::NVPTXTargetObjectFile::Initialize().
lowerRelativeReference()
virtual const MCExpr * llvm::TargetLoweringObjectFile::lowerRelativeReference (const GlobalValue * LHS, const GlobalValue * RHS, const TargetMachine & TM) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileWasm.
Definition at line 170 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::lowerConstant().
operator=()
TargetLoweringObjectFile & llvm::TargetLoweringObjectFile::operator= (const TargetLoweringObjectFile &) delete
SectionForGlobal() [1/2]
MCSection * llvm::TargetLoweringObjectFile::SectionForGlobal (const GlobalObject * GO, const TargetMachine & TM) const inline
This method computes the appropriate section to emit the specified global variable or function definition.
This should not be passed external (or available externally) globals.
Definition at line 107 of file TargetLoweringObjectFile.h.
References getKindForGlobal(), and SectionForGlobal().
SectionForGlobal() [2/2]
MCSection * TargetLoweringObjectFile::SectionForGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
This should not be passed external (or available externally) globals.
Definition at line 246 of file TargetLoweringObjectFile.cpp.
References F, getExplicitSectionGlobal(), llvm::GlobalObject::hasSection(), and SelectSectionForGlobal().
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), and SectionForGlobal().
SelectSectionForGlobal()
virtual MCSection * llvm::TargetLoweringObjectFile::SelectSectionForGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) const protected pure virtual
Implemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileWasm, llvm::AMDGPUTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::AVRTargetObjectFile, llvm::HexagonTargetObjectFile, llvm::LanaiTargetObjectFile, llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, llvm::RISCVELFTargetObjectFile, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
shouldPutJumpTableInFunctionSection()
bool TargetLoweringObjectFile::shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function & F) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileWasm, and llvm::HexagonTargetObjectFile.
Definition at line 278 of file TargetLoweringObjectFile.cpp.
References F.
Referenced by llvm::AsmPrinter::EmitJumpTableInfo().
supportDebugThreadLocalLocation()
bool llvm::TargetLoweringObjectFile::supportDebugThreadLocalLocation () const inline
Target supports TLS offset relocation in debug section?
Definition at line 189 of file TargetLoweringObjectFile.h.
References SupportDebugThreadLocalLocation.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute().
supportGOTPCRelWithOffset()
bool llvm::TargetLoweringObjectFile::supportGOTPCRelWithOffset () const inline
Target GOT "PC"-relative relocation supports encoding an additional binary expression with an offset?
Definition at line 184 of file TargetLoweringObjectFile.h.
References SupportGOTPCRelWithOffset.
Referenced by handleIndirectSymViaGOTPCRel().
supportIndirectSymViaGOTPCRel()
bool llvm::TargetLoweringObjectFile::supportIndirectSymViaGOTPCRel () const inline
Target supports replacing a data "PC"-relative access to a symbol through another symbol, by accessing the later via a GOT entry instead?
Definition at line 178 of file TargetLoweringObjectFile.h.
References SupportIndirectSymViaGOTPCRel.
Referenced by emitGlobalConstantImpl().
Member Data Documentation
CallSiteEncoding
unsigned llvm::TargetLoweringObjectFile::CallSiteEncoding = 0 protected
Definition at line 54 of file TargetLoweringObjectFile.h.
Referenced by getCallSiteEncoding(), Initialize(), and llvm::TargetLoweringObjectFileELF::Initialize().
LSDAEncoding
unsigned llvm::TargetLoweringObjectFile::LSDAEncoding = 0 protected
Definition at line 52 of file TargetLoweringObjectFile.h.
Referenced by getLSDAEncoding(), Initialize(), llvm::TargetLoweringObjectFileELF::Initialize(), and llvm::TargetLoweringObjectFileMachO::Initialize().
PersonalityEncoding
unsigned llvm::TargetLoweringObjectFile::PersonalityEncoding = 0 protected
PersonalityEncoding, LSDAEncoding, TTypeEncoding - Some encoding values for EH.
Definition at line 51 of file TargetLoweringObjectFile.h.
Referenced by getPersonalityEncoding(), Initialize(), llvm::TargetLoweringObjectFileELF::Initialize(), and llvm::TargetLoweringObjectFileMachO::Initialize().
StaticCtorSection
MCSection* llvm::TargetLoweringObjectFile::StaticCtorSection = nullptr protected
This section contains the static constructor pointer list.
Definition at line 57 of file TargetLoweringObjectFile.h.
Referenced by getStaticCtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), llvm::TargetLoweringObjectFileWasm::getStaticCtorSection(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringObjectFileCOFF::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), and llvm::TargetLoweringObjectFileWasm::InitializeWasm().
StaticDtorSection
MCSection* llvm::TargetLoweringObjectFile::StaticDtorSection = nullptr protected
This section contains the static destructor pointer list.
Definition at line 60 of file TargetLoweringObjectFile.h.
Referenced by getStaticDtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringObjectFileCOFF::Initialize(), and llvm::TargetLoweringObjectFileELF::InitializeELF().
SupportDebugThreadLocalLocation
bool llvm::TargetLoweringObjectFile::SupportDebugThreadLocalLocation = true protected
Definition at line 47 of file TargetLoweringObjectFile.h.
Referenced by supportDebugThreadLocalLocation().
SupportGOTPCRelWithOffset
bool llvm::TargetLoweringObjectFile::SupportGOTPCRelWithOffset = true protected
Definition at line 46 of file TargetLoweringObjectFile.h.
Referenced by llvm::AArch64_MachoTargetObjectFile::AArch64_MachoTargetObjectFile(), and supportGOTPCRelWithOffset().
SupportIndirectSymViaGOTPCRel
bool llvm::TargetLoweringObjectFile::SupportIndirectSymViaGOTPCRel = false protected
Definition at line 45 of file TargetLoweringObjectFile.h.
Referenced by supportIndirectSymViaGOTPCRel(), and llvm::TargetLoweringObjectFileMachO::TargetLoweringObjectFileMachO().
TTypeEncoding
unsigned llvm::TargetLoweringObjectFile::TTypeEncoding = 0 protected
Definition at line 53 of file TargetLoweringObjectFile.h.
Referenced by getTTypeEncoding(), Initialize(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::TargetLoweringObjectFileMachO::Initialize(), and llvm::TargetLoweringObjectFileWasm::InitializeWasm().
The documentation for this class was generated from the following files:
include/llvm/Target/TargetLoweringObjectFile.h
lib/Target/TargetLoweringObjectFile.cpp