LLVM: llvm::sampleprof::SampleRecord Class Reference
llvm::sampleprof::SampleRecord Class Reference
Representation of a single sample record.
#include "llvm/ProfileData/SampleProf.h"
Public Types
using CallTargetMap = StringMap< uint64_t >
Public Member Functions
SampleRecord ()=default
sampleprof_error addSamples (uint64_t S, uint64_t Weight=1)
Increment the number of samples for this record by S.
sampleprof_error addCalledTarget (StringRef F, uint64_t S, uint64_t Weight=1)
Add called function F with samples S.
bool hasCalls () const
Return true if this sample record contains function calls.
uint64_t getSamples () const
const CallTargetMap & getCallTargets () const
sampleprof_error merge (const SampleRecord &Other, uint64_t Weight=1)
Merge the samples in Other into this record.
void print (raw_ostream &OS, unsigned Indent) const
Print the sample record to the stream OS indented by Indent.
void dump () const
Detailed Description
Representation of a single sample record.
A sample record is represented by a positive integer value, which indicates how frequently was the associated line location executed.
Additionally, if the associated location contains a function call, the record will hold a list of all the possible called targets. For direct calls, this will be the exact function being invoked. For indirect calls (function pointers, virtual table dispatch), this will be a list of one or more functions.
Definition at line 144 of file SampleProf.h.
Member Typedef Documentation
CallTargetMap
using llvm::sampleprof::SampleRecord::CallTargetMap = StringMap<uint64_t>
Definition at line 146 of file SampleProf.h.
Constructor & Destructor Documentation
SampleRecord()
llvm::sampleprof::SampleRecord::SampleRecord () default
Member Function Documentation
addCalledTarget()
sampleprof_error llvm::sampleprof::SampleRecord::addCalledTarget (StringRef F, uint64_t S, uint64_t Weight = 1) inline
Add called function F with samples S.
Optionally scale sample count S by Weight.
Sample counts accumulate using saturating arithmetic, to avoid wrapping around unsigned integers.
Definition at line 167 of file SampleProf.h.
References llvm::counter_overflow, F, llvm::SaturatingMultiplyAdd(), and llvm::success.
Referenced by merge().
addSamples()
sampleprof_error llvm::sampleprof::SampleRecord::addSamples (uint64_t S, uint64_t Weight = 1) inline
Increment the number of samples for this record by S.
Optionally scale sample count S by Weight.
Sample counts accumulate using saturating arithmetic, to avoid wrapping around unsigned integers.
Definition at line 155 of file SampleProf.h.
References llvm::counter_overflow, llvm::SaturatingMultiplyAdd(), and llvm::success.
Referenced by merge().
dump()
LLVM_DUMP_METHOD void SampleRecord::dump () const
Definition at line 112 of file SampleProf.cpp.
References llvm::dbgs(), and print().
getCallTargets()
const CallTargetMap & llvm::sampleprof::SampleRecord::getCallTargets () const inline
Definition at line 181 of file SampleProf.h.
Referenced by print(), llvm::sampleprof::SampleProfileWriterText::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
getSamples()
uint64_t llvm::sampleprof::SampleRecord::getSamples () const inline
Definition at line 180 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterText::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
hasCalls()
bool llvm::sampleprof::SampleRecord::hasCalls () const inline
Return true if this sample record contains function calls.
Definition at line 178 of file SampleProf.h.
References llvm::StringMapImpl::empty().
Referenced by print().
merge()
sampleprof_error llvm::sampleprof::SampleRecord::merge (const SampleRecord & Other, uint64_t Weight = 1) inline
Merge the samples in Other into this record.
Optionally scale sample counts by Weight.
Definition at line 185 of file SampleProf.h.
References addCalledTarget(), addSamples(), I, llvm::MergeResult(), and Other.
print()
void SampleRecord::print (raw_ostream & OS, unsigned Indent) const
Print the sample record to the stream OS indented by Indent.
Definition at line 101 of file SampleProf.cpp.
References getCallTargets(), hasCalls(), and I.
Referenced by dump(), and llvm::sampleprof::operator<<().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp