LLVM: llvm::MSP430Subtarget Class Reference
llvm::MSP430Subtarget Class Reference
#include "Target/MSP430/MSP430Subtarget.h"
Public Types
enum HWMultEnum { NoHWMult , HWMult16 , HWMult32 , HWMultF5 }
Public Member Functions
MSP430Subtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
MSP430Subtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
bool hasHWMult16 () const
bool hasHWMult32 () const
bool hasHWMultF5 () const
const TargetFrameLowering * getFrameLowering () const override
const MSP430InstrInfo * getInstrInfo () const override
const TargetRegisterInfo * getRegisterInfo () const override
const MSP430TargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
Detailed Description
Definition at line 31 of file MSP430Subtarget.h.
Member Enumeration Documentation
HWMultEnum
enum llvm::MSP430Subtarget::HWMultEnum
Enumerator
NoHWMult
HWMult16
HWMult32
HWMultF5
Definition at line 33 of file MSP430Subtarget.h.
Constructor & Destructor Documentation
MSP430Subtarget()
MSP430Subtarget::MSP430Subtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 58 of file MSP430Subtarget.cpp.
Member Function Documentation
getFrameLowering()
const TargetFrameLowering * llvm::MSP430Subtarget::getFrameLowering () const inline override
Definition at line 63 of file MSP430Subtarget.h.
getInstrInfo()
const MSP430InstrInfo * llvm::MSP430Subtarget::getInstrInfo () const inline override
Definition at line 66 of file MSP430Subtarget.h.
getRegisterInfo()
const TargetRegisterInfo * llvm::MSP430Subtarget::getRegisterInfo () const inline override
Definition at line 67 of file MSP430Subtarget.h.
References llvm::MSP430InstrInfo::getRegisterInfo().
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::MSP430Subtarget::getSelectionDAGInfo () const inline override
Definition at line 73 of file MSP430Subtarget.h.
getTargetLowering()
const MSP430TargetLowering * llvm::MSP430Subtarget::getTargetLowering () const inline override
Definition at line 70 of file MSP430Subtarget.h.
hasHWMult16()
bool llvm::MSP430Subtarget::hasHWMult16 () const inline
Definition at line 59 of file MSP430Subtarget.h.
References HWMult16.
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering().
hasHWMult32()
bool llvm::MSP430Subtarget::hasHWMult32 () const inline
Definition at line 60 of file MSP430Subtarget.h.
References HWMult32.
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering().
hasHWMultF5()
bool llvm::MSP430Subtarget::hasHWMultF5 () const inline
Definition at line 61 of file MSP430Subtarget.h.
References HWMultF5.
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering().
initializeSubtargetDependencies()
MSP430Subtarget & MSP430Subtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 42 of file MSP430Subtarget.cpp.
References HWMultModeOption, NoHWMult, and ParseSubtargetFeatures().
ParseSubtargetFeatures()
void llvm::MSP430Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
lib/Target/MSP430/MSP430Subtarget.h
lib/Target/MSP430/MSP430Subtarget.cpp