LLVM: llvm::IntervalMapImpl::NodeRef Class Reference
llvm::IntervalMapImpl::NodeRef Class Reference
#include "llvm/ADT/IntervalMap.h"
Public Member Functions
NodeRef ()=default
NodeRef - Create a null ref.
operator bool () const
operator bool - Detect a null ref.
template<typename NodeT >
NodeRef (NodeT *p, unsigned n)
NodeRef - Create a reference to the node p with n elements.
unsigned size () const
size - Return the number of elements in the referenced node.
void setSize (unsigned n)
setSize - Update the node size.
NodeRef & subtree (unsigned i) const
subtree - Access the i'th subtree reference in a branch node.
template<typename NodeT >
NodeT & get () const
get - Dereference as a NodeT reference.
bool operator== (const NodeRef &RHS) const
bool operator!= (const NodeRef &RHS) const
Detailed Description
Definition at line 490 of file IntervalMap.h.
Constructor & Destructor Documentation
NodeRef() [1/2]
llvm::IntervalMapImpl::NodeRef::NodeRef () default
NodeRef - Create a null ref.
NodeRef() [2/2]
template<typename NodeT > llvm::IntervalMapImpl::NodeRef::NodeRef (NodeT * p, unsigned n) inline
NodeRef - Create a reference to the node p with n elements.
Definition at line 507 of file IntervalMap.h.
References assert().
Member Function Documentation
get()
template<typename NodeT > NodeT & llvm::IntervalMapImpl::NodeRef::get () const inline
get - Dereference as a NodeT reference.
Definition at line 526 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by llvm::AliasSetTracker::add(), llvm::AttributeSet::addAttribute(), llvm::AttributeList::addAttributes(), llvm::Function::addFnAttr(), llvm::Module::addModuleFlag(), llvm::AddOne(), llvm::AttributeList::addParamAttribute(), AddRuntimeUnrollDisableMetaData(), llvm::GlobalObject::addTypeMetadata(), llvm::GVNExpression::BasicExpression::allocateOperands(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::annotateValueSite(), llvm::fuzzerop::anyPtrType(), llvm::DIExpression::append(), appendToGlobalArray(), appendToUsedList(), arrayTypeToVecType(), BinomialCoefficient(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFConstant(), buildFrameType(), llvm::coro::Shape::buildFrom(), buildNew(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canonicalizeBitCastExtElt(), canonicalizeCmpWithConstant(), canonicalizeInsertSplat(), canonicalizeMetadataForValue(), canonicalizeSaturatedAdd(), CanShareConstantPoolEntry(), llvm::canSinkOrHoistInst(), llvm::CoroIdInst::clearPromise(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), llvm::CloneFunction(), llvm::DILocation::cloneWithDiscriminator(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), collectInsertionElements(), collectShuffleElements(), collectSingleShuffleElements(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::ObjectSizeOffsetEvaluator::compute(), computeUnlikelySuccessors(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConcatListInits(), ConcatStringInits(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLabelDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), convert_i1_to_i8(), llvm::TypedInit::convertInitializerBitRange(), llvm::BitsInit::convertInitializerBitRange(), llvm::IntInit::convertInitializerBitRange(), llvm::TypedInit::convertInitializerTo(), llvm::BitInit::convertInitializerTo(), llvm::BitsInit::convertInitializerTo(), llvm::IntInit::convertInitializerTo(), llvm::StringInit::convertInitializerTo(), llvm::CodeInit::convertInitializerTo(), llvm::ListInit::convertInitializerTo(), llvm::TypedInit::convertInitListSlice(), llvm::ListInit::convertInitListSlice(), ConvertShiftToMul(), llvm::GlobalObject::copyMetadata(), llvm::SanitizerStatReport::create(), createAccessTag(), llvm::IRBuilder< T, Inserter >::CreateAggregateRet(), llvm::MDBuilder::createAliasScope(), llvm::MDBuilder::createAliasScopeDomain(), llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::DwarfUnit::createAndAddDIE(), createAndInstr(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createArrayType(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), llvm::DIBuilder::createBasicType(), llvm::TargetFolder::CreateBinOp(), llvm::ConstantFolder::CreateBinOp(), llvm::DIBuilder::createBitFieldMemberType(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCommonBlock(), llvm::MDBuilder::createConstant(), llvm::DIBuilder::createConstantValueExpression(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), createDevirtTriggerFunc(), createDummyFunction(), createEmptyFunction(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createExpression(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), llvm::DIBuilder::createFriend(), llvm::MDBuilder::createFunctionEntryCount(), llvm::MDBuilder::createFunctionSectionPrefix(), CreateGCRelocates(), llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr(), llvm::DIBuilder::createGlobalVariableExpression(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), llvm::DIBuilder::createLabel(), llvm::DIBuilder::createLexicalBlockFile(), createLocalVariable(), createLoweredType(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::DIBuilder::createMacro(), createMalloc(), createMaskedBitTest(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::InstCombiner::CreateNonTerminatorUnreachable(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::InstCombiner::CreateOverflowTuple(), llvm::createPGOFuncNameMetadata(), llvm::DIBuilder::createPointerType(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), createPrivateGlobalForSourceLoc(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), createRdxShuffleMask(), llvm::DIBuilder::createReferenceType(), llvm::createSanitizerCtorAndInitFunctions(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DIBuilder::createStaticMemberType(), llvm::MDBuilder::createString(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::DIBuilder::createTemplateTemplateParameter(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::TargetFolder::CreateUnOp(), llvm::ConstantFolder::CreateUnOp(), llvm::MDBuilder::createUnpredictable(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantPart(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::DIBuilder::createVectorType(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::GVNExpression::BasicExpression::deallocateOperands(), llvm::declareSanitizerInitFunction(), DecodeFixedType(), decomposeBitTestICmp(), llvm::FileCheckPatternContext::defineCmdlineVariables(), deleteDeadInstruction(), llvm::DependenceInfo::depends(), doPromotion(), llvm::EmitGEPOffset(), EmitInlineAsm(), emitLibCall(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), EmitX86ScalarSelect(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::Evaluator::EvaluateBlock(), evaluateGEPOffsetExpression(), evaluateInDifferentElementOrder(), llvm::VPlan::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::SCEVExpander::expandUnionPredicate(), llvm::DIExpression::extractAddressClass(), extractVector(), FactorOutConstant(), llvm::FastISel::fastEmit_ri_(), llvm::DIBuilder::finalize(), findBaseDefiningValue(), findBaseDefiningValueOfVector(), findBasePointer(), llvm::RandomIRBuilder::findPointer(), llvm::SanitizerStatReport::finish(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::IsAOpInit::Fold(), llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::UnOpInit::Fold(), foldAndOrOfEqualityCmpsWithConstants(), foldConstantInsEltIntoShuffle(), foldCtpop(), foldCttzCtlz(), foldFDivConstantDivisor(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithTruncSignExtendedVal(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), foldIsPowerOf2(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), foldVectorCmp(), foldVecTruncToExtElt(), forceIndeterminateEdge(), ForeachDagApply(), ForeachHelper(), llvm::SCEVExpander::generateOverflowCheck(), llvm::ConstantVector::get(), llvm::gvn::AvailableValueInBlock::get(), llvm::DagInit::get(), llvm::AttributeList::get(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::MDNode::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataArray::get(), llvm::ConstantInt::get(), llvm::VarInit::get(), llvm::ConstantStruct::get(), llvm::VectorType::get(), llvm::StructType::get(), llvm::DebugLoc::get(), getAccessType(), llvm::ConstantExpr::getAddrSpaceCast(), getAISize(), llvm::ConstantExpr::getAlignOf(), llvm::Constant::getAllOnesValue(), getAlternateBinop(), GetAnyNonZeroConstInt(), llvm::BasicTTIImplBase< T >::getArithmeticReductionCost(), getAsConstantIndexedAddress(), llvm::GlobalVariable::getAttributesAsList(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), llvm::IntInit::getBit(), llvm::OpInit::getBit(), llvm::CondOpInit::getBit(), llvm::FoldOpInit::getBit(), llvm::IsAOpInit::getBit(), llvm::VarInit::getBit(), llvm::VarListElementInit::getBit(), llvm::FieldInit::getBit(), llvm::DINode::getCanonicalMDString(), llvm::DIMacroNode::getCanonicalMDString(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::TypedInit::getCastTo(), getCmpOpsType(), llvm::ValueLatticeElement::getCompare(), llvm::ScalarEvolution::getConstant(), llvm::SelectionDAG::getConstant(), llvm::LazyValueInfo::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::LazyValueInfo::getConstantOnEdge(), getConstantOrNull(), llvm::ExecutionEngine::getConstantValue(), getConstantVector(), getDbgIntrinsicValueImpl(), llvm::AbstractAttribute::getDeducedAttributes(), getDefaultPersonalityFn(), llvm::VectorType::getDoubleElementsVectorType(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::SelectionDAG::getEVTAlignment(), llvm::VectorType::getExtendedElementVectorType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), getFoldedAlignOf(), getFoldedSizeOf(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::AMDGPUMangledLibFunc::getFunctionType(), llvm::ScalarEvolution::getGEPExpr(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::VectorType::getHalfElementsVectorType(), GetHeapSROAValue(), llvm::ConstantExpr::getICmp(), llvm::ConstantDataSequential::getImpl(), llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), llvm::DataLayout::getIndexType(), llvm::getInlineCost(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt1(), llvm::IRBuilderBase::getInt16(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::VectorType::getInteger(), llvm::Constant::getIntegerValue(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::IRBuilderBase::getIntN(), llvm::DataLayout::getIntPtrType(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), getIntrinsicParamType(), llvm::BinOpInit::getListConcat(), llvm::BinOpInit::getListSplat(), llvm::VNCoercion::getLoadValueForLoad(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::ProfileSummary::getMD(), getMemCmpLoad(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getMemSetPatternValue(), llvm::DILocation::getMergedLocation(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::BasicTTIImplBase< T >::getMinMaxReductionCost(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::RecordKeeper::getNewAnonymousName(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::Constant::getNullValue(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::DIBuilder::getOrCreateArray(), llvm::DIBuilder::getOrCreateMacroArray(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), getOrInsertValueProfilingCall(), getOrSelfReference(), getPreStartForExtend(), llvm::ConstantDataArray::getRaw(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), getReducedType(), getReturnAttrs(), llvm::getSafeVectorConstantForBinop(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::UndefValue::getSequentialElement(), llvm::X86TTIImpl::getShuffleCost(), llvm::ConstantExpr::getShuffleVector(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::ConstantExpr::getSizeOf(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::DependenceInfo::getSplitIteration(), llvm::InstrProfIncrementInst::getStep(), llvm::InnerLoopVectorizer::getStepVector(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::BinOpInit::getStrConcat(), llvm::UndefValue::getStructElement(), getSubprogram(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::ConstantInt::getTrue(), llvm::VectorType::getTruncatedElementVectorType(), llvm::Record::getType(), llvm::Intrinsic::getType(), llvm::ConstantStruct::getTypeForElements(), llvm::EVT::getTypeForEVT(), getTypePartition(), llvm::ScalarEvolution::getUDivExpr(), llvm::SSAUpdaterTraits< SSAUpdater >::GetUndefVal(), llvm::PointerType::getUnqual(), llvm::ScalarEvolution::getURemExpr(), llvm::Record::getValue(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::ConstantExpr::getWithOperands(), getX86MaskVec(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ValueAsMetadata::handleRAUW(), hasAddressTakenAndUsed(), llvm::PHINode::hasConstantValue(), hasIrregularType(), llvm::hoistRegion(), llvm::FunctionImporter::importFunctions(), INITIALIZE_PASS(), insertCall(), InsertSafepointPoll(), insertSinCosCall(), insertUseHolderAfter(), insertVector(), instrumentMaskedLoadOrStore(), llvm::ScaledNumber< DigitsT >::invert(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), IsIncrementNSW(), IsIncrementNUW(), isLoadInvariantInLoop(), isVectorPromotionViableForSlice(), legalizeCallAttributes(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LinearizeExprTree(), LLVMAddTargetDependentFunctionAttr(), LLVMArrayType(), LLVMConstArray(), LLVMCreateEnumAttribute(), LLVMCreateStringAttribute(), LLVMDIBuilderCreateDebugLocation(), LLVMFunctionType(), LLVMPointerType(), LLVMVectorType(), llvm::XCoreInstrInfo::loadImmediate(), lookThroughAnd(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), LowerFPToInt(), LowerFSINCOS(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), LowerUINT_TO_FP_i64(), llvm::CmpInst::makeCmpResultType(), makeStatepointExplicitImpl(), llvm::coro::LowererBase::makeSubFnCall(), llvm::FileCheckPattern::match(), MatchBinaryOp(), matchIntrinsicType(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::MDBuilder::mergeCallbackEncodings(), narrowVectorSelect(), llvm::RandomIRBuilder::newSink(), llvm::EscapeEnumerator::Next(), OptimizeGlobalAddressOfMalloc(), optimizeMemCmpConstantSize(), optimizeVectorResize(), llvm::TargetLowering::ParseConstraints(), llvm::LLParser::ParseMDField(), llvm::FileCheckPattern::parseNumericSubstitutionBlock(), llvm::FileCheckPattern::parseNumericVariableDefinition(), llvm::FileCheckPattern::parseVariable(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind(), PerformHeapAllocSRoA(), prepareForSplit(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prependOpcodes(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), processUGT_ADDCST_ADD(), promoteToConstantPool(), relocationViaAlloca(), removeBitcastsFromLoadStoreOnMinMax(), removeGlobalCtors(), llvm::PHINode::removeIncomingValue(), RemoveNonValidAttrAtIndex(), llvm::BasicBlock::removePredecessor(), llvm::Record::removeValue(), ReplaceCallWith(), llvm::coro::replaceCoroFree(), replaceExtractElements(), replaceGEPIdxWithZero(), llvm::InstCombiner::replaceInstUsesWith(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), resolveRecordTypes(), llvm::BitsInit::resolveReferences(), llvm::ListInit::resolveReferences(), llvm::UnOpInit::resolveReferences(), llvm::BinOpInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), llvm::CondOpInit::resolveReferences(), llvm::VarListElementInit::resolveReferences(), llvm::VarDefInit::resolveReferences(), llvm::FieldInit::resolveReferences(), llvm::DagInit::resolveReferences(), llvm::InnerLoopVectorizer::reverseVector(), rewriteGEPAsOffset(), llvm::InstCombiner::run(), llvm::LoadAndStorePromoter::run(), llvm::runIPSCCP(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), llvm::SanitizerStatReport::SanitizerStatReport(), SegmentOffset(), llvm::FastISel::selectIntrinsicCall(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setCoroInfo(), setInlineRemark(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Module::setSDKVersion(), setUsedInitializer(), llvm::RecordVal::setValue(), llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign(), shrinkFPConstantVector(), shrinkInsertElt(), shrinkSplatShuffle(), simplifyAllocaArraySize(), simplifyAssocCastAssoc(), SimplifyGEPInst(), simplifyNeonTbl1(), simplifyNeonVld1(), SimplifyNVVMIntrinsic(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), sink(), llvm::fuzzerop::sizedPtrType(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::fuzzerop::SourcePred::SourcePred(), stripDebugLocFromLoopID(), stripNonValidDataFromBody(), llvm::SubOne(), llvm::Instruction::swapProfMetadata(), ToVectorTy(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryMergeRange(), TryToSinkInstruction(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::CallInst::updateProfWeight(), llvm::UpgradeGlobalVariable(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), upgradeMaskedCompare(), UpgradePTESTIntrinsic(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), validShuffleVectorIndex(), valueHasFloatPrecision(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::InnerLoopVectorizer::widenPHIInstruction(), llvm::LegalizerHelper::widenScalar(), and llvm::BasicBlock::~BasicBlock().
operator bool()
llvm::IntervalMapImpl::NodeRef::operator bool () const inline explicit
operator bool - Detect a null ref.
Definition at line 503 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getOpaqueValue().
operator!=()
bool llvm::IntervalMapImpl::NodeRef::operator!= (const NodeRef & RHS) const inline
Definition at line 537 of file IntervalMap.h.
References operator==().
operator==()
bool llvm::IntervalMapImpl::NodeRef::operator== (const NodeRef & RHS) const inline
Definition at line 530 of file IntervalMap.h.
References assert(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by operator!=().
setSize()
void llvm::IntervalMapImpl::NodeRef::setSize (unsigned n) inline
setSize - Update the node size.
Definition at line 515 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt().
Referenced by llvm::IntervalMapImpl::Path::setSize().
size()
unsigned llvm::IntervalMapImpl::NodeRef::size () const inline
size - Return the number of elements in the referenced node.
Definition at line 512 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt().
Referenced by llvm::IntervalMapImpl::Path::getLeftSibling(), and llvm::IntervalMapImpl::Path::moveLeft().
subtree()
NodeRef & llvm::IntervalMapImpl::NodeRef::subtree (unsigned i) const inline
subtree - Access the i'th subtree reference in a branch node.
This depends on branch nodes storing the NodeRef array as their first member.
Definition at line 520 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by llvm::IntervalMapImpl::Path::getLeftSibling(), llvm::IntervalMapImpl::Path::getRightSibling(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::IntervalMapImpl::Path::moveRight(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind().
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalMap.h