LLVM: llvm::Target Class Reference
llvm::Target Class Reference
Target - Wrapper for Target specific information.
#include "llvm/Support/TargetRegistry.h"
Public Types
using ArchMatchFnTy = bool(*)(Triple::ArchType Arch)
using MCAsmInfoCtorFnTy = MCAsmInfo *(*)(const MCRegisterInfo &MRI, const Triple &TT)
using MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
using MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
using MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
using MCSubtargetInfoCtorFnTy = MCSubtargetInfo *(*)(const Triple &TT, StringRef CPU, StringRef Features)
using TargetMachineCtorTy = TargetMachine *(*)(const Target &T, const Triple &TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
using AsmPrinterCtorTy = AsmPrinter *(*)(TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer)
using MCAsmBackendCtorTy = MCAsmBackend *(*)(const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options)
using MCAsmParserCtorTy = MCTargetAsmParser *(*)(const MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
using MCDisassemblerCtorTy = MCDisassembler *(*)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
using MCInstPrinterCtorTy = MCInstPrinter *(*)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
using MCCodeEmitterCtorTy = MCCodeEmitter *(*)(const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx)
using ELFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using MachOStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
using COFFStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool IncrementalLinkerCompatible)
using WasmStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
using AsmTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
using ObjectTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, const MCSubtargetInfo &STI)
using MCRelocationInfoCtorTy = MCRelocationInfo *(*)(const Triple &TT, MCContext &Ctx)
using MCSymbolizerCtorTy = MCSymbolizer *(*)(const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
Public Member Functions
Target ()=default
Target Information
const Target * getNext () const
const char * getName () const
getName - Get the target name.
const char * getShortDescription () const
getShortDescription - Get a short description of the target.
const char * getBackendName () const
getBackendName - Get the backend name.
Feature Predicates
bool hasJIT () const
hasJIT - Check if this targets supports the just-in-time compilation.
bool hasTargetMachine () const
hasTargetMachine - Check if this target supports code generation.
bool hasMCAsmBackend () const
hasMCAsmBackend - Check if this target supports .o generation.
bool hasMCAsmParser () const
hasMCAsmParser - Check if this target supports assembly parsing.
Feature Constructors
MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &MRI, StringRef TheTriple) const
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
MCInstrInfo * createMCInstrInfo () const
createMCInstrInfo - Create a MCInstrInfo implementation.
MCInstrAnalysis * createMCInstrAnalysis (const MCInstrInfo *Info) const
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
MCRegisterInfo * createMCRegInfo (StringRef TT) const
createMCRegInfo - Create a MCRegisterInfo implementation.
MCSubtargetInfo * createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
TargetMachine * createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM=None, CodeGenOpt::Level OL=CodeGenOpt::Default, bool JIT=false) const
createTargetMachine - Create a target specific machine implementation for the specified Triple.
MCAsmBackend * createMCAsmBackend (const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options) const
createMCAsmBackend - Create a target specific assembly parser.
MCTargetAsmParser * createMCAsmParser (const MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options) const
createMCAsmParser - Create a target specific assembly parser.
AsmPrinter * createAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer) const
createAsmPrinter - Create a target specific assembly printer pass.
MCDisassembler * createMCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx) const
MCInstPrinter * createMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI) const
MCCodeEmitter * createMCCodeEmitter (const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx) const
createMCCodeEmitter - Create a target specific code emitter.
MCStreamer * createMCObjectStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, const MCSubtargetInfo &STI, bool RelaxAll, bool IncrementalLinkerCompatible, bool DWARFMustBeAtTheEnd) const
Create a target specific MCStreamer.
MCStreamer * createAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter *InstPrint, std::unique_ptr< MCCodeEmitter > &&CE, std::unique_ptr< MCAsmBackend > &&TAB, bool ShowInst) const
MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm) const
MCStreamer * createNullStreamer (MCContext &Ctx) const
MCTargetStreamer * createNullTargetStreamer (MCStreamer &S) const
MCRelocationInfo * createMCRelocationInfo (StringRef TT, MCContext &Ctx) const
createMCRelocationInfo - Create a target specific MCRelocationInfo.
MCSymbolizer * createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo) const
createMCSymbolizer - Create a target specific MCSymbolizer.
Friends
struct TargetRegistry
Detailed Description
Target - Wrapper for Target specific information.
For registration purposes, this is a POD type so that targets can be registered without the use of static constructors.
Targets should implement a single global instance of this class (which will be zero initialized), and pass that instance to the TargetRegistry as part of their initialization.
Definition at line 124 of file TargetRegistry.h.
Member Typedef Documentation
ArchMatchFnTy
using llvm::Target::ArchMatchFnTy = bool (*)(Triple::ArchType Arch)
Definition at line 128 of file TargetRegistry.h.
AsmPrinterCtorTy
using llvm::Target::AsmPrinterCtorTy = AsmPrinter *(*)(TargetMachine &TM, std::unique_ptr<MCStreamer> &&Streamer)
Definition at line 145 of file TargetRegistry.h.
AsmTargetStreamerCtorTy
using llvm::Target::AsmTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
Definition at line 186 of file TargetRegistry.h.
COFFStreamerCtorTy
using llvm::Target::COFFStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll, bool IncrementalLinkerCompatible)
Definition at line 175 of file TargetRegistry.h.
ELFStreamerCtorTy
using llvm::Target::ELFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 165 of file TargetRegistry.h.
MachOStreamerCtorTy
using llvm::Target::MachOStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
Definition at line 170 of file TargetRegistry.h.
MCAsmBackendCtorTy
using llvm::Target::MCAsmBackendCtorTy = MCAsmBackend *(*)(const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options)
Definition at line 147 of file TargetRegistry.h.
MCAsmInfoCtorFnTy
using llvm::Target::MCAsmInfoCtorFnTy = MCAsmInfo *(*)(const MCRegisterInfo &MRI, const Triple &TT)
Definition at line 130 of file TargetRegistry.h.
MCAsmParserCtorTy
using llvm::Target::MCAsmParserCtorTy = MCTargetAsmParser *(*)(const MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
Definition at line 151 of file TargetRegistry.h.
MCCodeEmitterCtorTy
using llvm::Target::MCCodeEmitterCtorTy = MCCodeEmitter *(*)(const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx)
Definition at line 162 of file TargetRegistry.h.
MCDisassemblerCtorTy
using llvm::Target::MCDisassemblerCtorTy = MCDisassembler *(*)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
Definition at line 154 of file TargetRegistry.h.
MCInstPrinterCtorTy
using llvm::Target::MCInstPrinterCtorTy = MCInstPrinter *(*)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
Definition at line 157 of file TargetRegistry.h.
MCInstrAnalysisCtorFnTy
using llvm::Target::MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
Definition at line 133 of file TargetRegistry.h.
MCInstrInfoCtorFnTy
using llvm::Target::MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
Definition at line 132 of file TargetRegistry.h.
MCRegInfoCtorFnTy
using llvm::Target::MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
Definition at line 134 of file TargetRegistry.h.
MCRelocationInfoCtorTy
using llvm::Target::MCRelocationInfoCtorTy = MCRelocationInfo *(*)(const Triple &TT, MCContext &Ctx)
Definition at line 191 of file TargetRegistry.h.
MCSubtargetInfoCtorFnTy
using llvm::Target::MCSubtargetInfoCtorFnTy = MCSubtargetInfo *(*)(const Triple &TT, StringRef CPU, StringRef Features)
Definition at line 135 of file TargetRegistry.h.
MCSymbolizerCtorTy
using llvm::Target::MCSymbolizerCtorTy = MCSymbolizer *(*)(const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr<MCRelocationInfo> &&RelInfo)
Definition at line 193 of file TargetRegistry.h.
NullTargetStreamerCtorTy
using llvm::Target::NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
Definition at line 185 of file TargetRegistry.h.
ObjectTargetStreamerCtorTy
using llvm::Target::ObjectTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, const MCSubtargetInfo &STI)
Definition at line 189 of file TargetRegistry.h.
TargetMachineCtorTy
using llvm::Target::TargetMachineCtorTy = TargetMachine *(*)(const Target &T, const Triple &TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Optional<Reloc::Model> RM, Optional<CodeModel::Model> CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 138 of file TargetRegistry.h.
WasmStreamerCtorTy
using llvm::Target::WasmStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 180 of file TargetRegistry.h.
Constructor & Destructor Documentation
Target()
llvm::Target::Target () default
Member Function Documentation
createAsmPrinter()
AsmPrinter * llvm::Target::createAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > && Streamer) const inline
createAsmPrinter - Create a target specific assembly printer pass.
This takes ownership of the MCStreamer object.
Definition at line 429 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
createAsmStreamer()
MCStreamer * llvm::Target::createAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter * InstPrint, std::unique_ptr< MCCodeEmitter > && CE, std::unique_ptr< MCAsmBackend > && TAB, bool ShowInst) const inline
Definition at line 522 of file TargetRegistry.h.
References llvm::createAsmStreamer(), and createAsmTargetStreamer().
Referenced by llvm::LLVMTargetMachine::addAsmPrinter().
createAsmTargetStreamer()
MCTargetStreamer * llvm::Target::createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool IsVerboseAsm) const inline
Definition at line 537 of file TargetRegistry.h.
Referenced by createAsmStreamer().
createMCAsmBackend()
MCAsmBackend * llvm::Target::createMCAsmBackend (const MCSubtargetInfo & STI, const MCRegisterInfo & MRI, const MCTargetOptions & Options) const inline
createMCAsmBackend - Create a target specific assembly parser.
Definition at line 406 of file TargetRegistry.h.
References MRI.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
createMCAsmInfo()
MCAsmInfo * llvm::Target::createMCAsmInfo (const MCRegisterInfo & MRI, StringRef TheTriple) const inline
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 338 of file TargetRegistry.h.
References MRI.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), and LLVMCreateDisasmCPUFeatures().
createMCAsmParser()
MCTargetAsmParser * llvm::Target::createMCAsmParser (const MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) const inline
createMCAsmParser - Create a target specific assembly parser.
Parameters
Parser The target independent parser implementation to use for parsing and lexing.
Definition at line 418 of file TargetRegistry.h.
createMCCodeEmitter()
MCCodeEmitter * llvm::Target::createMCCodeEmitter (const MCInstrInfo & II, const MCRegisterInfo & MRI, MCContext & Ctx) const inline
createMCCodeEmitter - Create a target specific code emitter.
Definition at line 453 of file TargetRegistry.h.
References MRI.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), llvm::LLVMTargetMachine::addPassesToEmitMC(), and llvm::X86AsmPrinter::runOnMachineFunction().
createMCDisassembler()
MCDisassembler * llvm::Target::createMCDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) const inline
Definition at line 436 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCInstPrinter()
MCInstPrinter * llvm::Target::createMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) const inline
Definition at line 443 of file TargetRegistry.h.
References MRI.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), and LLVMCreateDisasmCPUFeatures().
createMCInstrAnalysis()
MCInstrAnalysis * llvm::Target::createMCInstrAnalysis (const MCInstrInfo * Info) const inline
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
Definition at line 355 of file TargetRegistry.h.
References Info.
createMCInstrInfo()
MCInstrInfo * llvm::Target::createMCInstrInfo () const inline
createMCInstrInfo - Create a MCInstrInfo implementation.
Definition at line 347 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), and LLVMCreateDisasmCPUFeatures().
createMCObjectStreamer()
MCStreamer * llvm::Target::createMCObjectStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, const MCSubtargetInfo & STI, bool RelaxAll, bool IncrementalLinkerCompatible, bool DWARFMustBeAtTheEnd) const inline
Create a target specific MCStreamer.
Parameters
T The target triple.
Ctx The target context.
TAB The target assembler backend object. Takes ownership.
OW The stream object.
Emitter The target independent assembler object.Takes ownership.
RelaxAll Relax all fixups?
Definition at line 469 of file TargetRegistry.h.
References assert(), llvm::Triple::COFF, llvm::createELFStreamer(), llvm::createMachOStreamer(), llvm::createWasmStreamer(), llvm::createXCOFFStreamer(), llvm::Triple::ELF, llvm_unreachable, llvm::Triple::MachO, llvm::Triple::UnknownObjectFormat, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
createMCRegInfo()
MCRegisterInfo * llvm::Target::createMCRegInfo (StringRef TT) const inline
createMCRegInfo - Create a MCRegisterInfo implementation.
Definition at line 363 of file TargetRegistry.h.
References TT.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::DWARFContext::loadRegisterInfo().
createMCRelocationInfo()
MCRelocationInfo * llvm::Target::createMCRelocationInfo (StringRef TT, MCContext & Ctx) const inline
createMCRelocationInfo - Create a target specific MCRelocationInfo.
Parameters
TT The target triple.
Ctx The target context.
Definition at line 562 of file TargetRegistry.h.
References llvm::createMCRelocationInfo(), and TT.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCSubtargetInfo()
MCSubtargetInfo * llvm::Target::createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const inline
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
CPU This specifies the name of the target CPU.
Features This specifies the string representation of the additional target features.
Definition at line 378 of file TargetRegistry.h.
Referenced by llvm::AsmPrinter::doInitialization(), llvm::LLVMTargetMachine::initAsmInfo(), and LLVMCreateDisasmCPUFeatures().
createMCSymbolizer()
MCSymbolizer * llvm::Target::createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) const inline
createMCSymbolizer - Create a target specific MCSymbolizer.
Parameters
TT The target triple.
GetOpInfo The function to get the symbolic information for operands.
SymbolLookUp The function to lookup a symbol name.
DisInfo The pointer to the block of symbolic information for above call back.
Ctx The target context.
RelInfo The relocation information for this target. Takes ownership.
Definition at line 582 of file TargetRegistry.h.
References llvm::createMCSymbolizer(), and TT.
Referenced by LLVMCreateDisasmCPUFeatures().
createNullStreamer()
MCStreamer * llvm::Target::createNullStreamer (MCContext & Ctx) const inline
Definition at line 546 of file TargetRegistry.h.
References llvm::createNullStreamer(), and createNullTargetStreamer().
createNullTargetStreamer()
MCTargetStreamer * llvm::Target::createNullTargetStreamer (MCStreamer & S) const inline
Definition at line 552 of file TargetRegistry.h.
Referenced by createNullStreamer().
createTargetMachine()
TargetMachine * llvm::Target::createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions & Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM = None, CodeGenOpt::Level OL = CodeGenOpt::Default, bool JIT = false) const inline
createTargetMachine - Create a target specific machine implementation for the specified Triple.
Parameters
TT This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 392 of file TargetRegistry.h.
References TT.
Referenced by llvm::TargetMachineBuilder::create(), and llvm::EngineBuilder::selectTarget().
getBackendName()
const char * llvm::Target::getBackendName () const inline
getBackendName - Get the backend name.
Definition at line 309 of file TargetRegistry.h.
Referenced by llvm::InstructionSelect::runOnMachineFunction().
getName()
const char * llvm::Target::getName () const inline
getName - Get the target name.
Definition at line 303 of file TargetRegistry.h.
References Name.
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getGOTEntryAtom(), llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getStubAtom(), and llvm::MachObjectWriter::getSymbolAddress().
getNext()
const Target * llvm::Target::getNext () const inline
Definition at line 300 of file TargetRegistry.h.
Referenced by llvm::TargetRegistry::iterator::operator++().
getShortDescription()
const char * llvm::Target::getShortDescription () const inline
getShortDescription - Get a short description of the target.
Definition at line 306 of file TargetRegistry.h.
hasJIT()
bool llvm::Target::hasJIT () const inline
hasJIT - Check if this targets supports the just-in-time compilation.
Definition at line 316 of file TargetRegistry.h.
hasMCAsmBackend()
bool llvm::Target::hasMCAsmBackend () const inline
hasMCAsmBackend - Check if this target supports .o generation.
Definition at line 322 of file TargetRegistry.h.
hasMCAsmParser()
bool llvm::Target::hasMCAsmParser () const inline
hasMCAsmParser - Check if this target supports assembly parsing.
Definition at line 325 of file TargetRegistry.h.
hasTargetMachine()
bool llvm::Target::hasTargetMachine () const inline
hasTargetMachine - Check if this target supports code generation.
Definition at line 319 of file TargetRegistry.h.
Friends And Related Function Documentation
TargetRegistry
friend struct TargetRegistry friend
Definition at line 126 of file TargetRegistry.h.
The documentation for this class was generated from the following file:
include/llvm/Support/TargetRegistry.h