LLVM: llvm::object::ELFRelocationRef Class Reference
llvm::object::ELFRelocationRef Class Reference
#include "llvm/Object/ELFObjectFile.h"
Public Member Functions
ELFRelocationRef (const RelocationRef &B)
const ELFObjectFileBase * getObject () const
Expected< int64_t > getAddend () const
Public Member Functions inherited from llvm::object::RelocationRef
RelocationRef ()=default
RelocationRef (DataRefImpl RelocationP, const ObjectFile *Owner)
RelocationRef.
bool operator== (const RelocationRef &Other) const
void moveNext ()
uint64_t getOffset () const
symbol_iterator getSymbol () const
uint64_t getType () const
void getTypeName (SmallVectorImpl< char > &Result) const
Get a string that represents the type of this relocation.
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObject () const
Detailed Description
Definition at line 188 of file ELFObjectFile.h.
Constructor & Destructor Documentation
ELFRelocationRef()
llvm::object::ELFRelocationRef::ELFRelocationRef (const RelocationRef & B) inline
Definition at line 190 of file ELFObjectFile.h.
References assert(), and llvm::object::RelocationRef::getObject().
Member Function Documentation
getAddend()
Expected< int64_t > llvm::object::ELFRelocationRef::getAddend () const inline
Definition at line 198 of file ELFObjectFile.h.
References getObject(), llvm::object::RelocationRef::getRawDataRefImpl(), and llvm::object::ELFObjectFileBase::getRelocationAddend().
Referenced by llvm::object::getELFAddend(), loadObj(), and llvm::RuntimeDyldELF::processRelocationRef().
getObject()
const ELFObjectFileBase * llvm::object::ELFRelocationRef::getObject () const inline
Definition at line 194 of file ELFObjectFile.h.
References llvm::object::RelocationRef::getObject().
Referenced by getAddend().
The documentation for this class was generated from the following file:
include/llvm/Object/ELFObjectFile.h