LLVM: llvm::orc::JITSymbolResolverAdapter Class Reference
llvm::orc::JITSymbolResolverAdapter Class Reference
Legacy adapter. Remove once we kill off the old ORC layers.
#include "llvm/ExecutionEngine/Orc/Legacy.h"
Public Member Functions
JITSymbolResolverAdapter (ExecutionSession &ES, SymbolResolver &R, MaterializationResponsibility *MR)
Expected< LookupSet > getResponsibilitySet (const LookupSet &Symbols) override
Returns the subset of the given symbols that should be materialized by the caller.
void lookup (const LookupSet &Symbols, OnResolvedFunction OnResolved) override
Returns the fully resolved address and flags for each of the given symbols.
Public Member Functions inherited from llvm::JITSymbolResolver
virtual ~JITSymbolResolver ()=default
virtual void lookup (const LookupSet &Symbols, OnResolvedFunction OnResolved)=0
Returns the fully resolved address and flags for each of the given symbols.
virtual Expected< LookupSet > getResponsibilitySet (const LookupSet &Symbols)=0
Returns the subset of the given symbols that should be materialized by the caller.
Additional Inherited Members
Public Types inherited from llvm::JITSymbolResolver
using LookupSet = std::set< StringRef >
using LookupResult = std::map< StringRef, JITEvaluatedSymbol >
using OnResolvedFunction = std::function< void(Expected< LookupResult >)>
Detailed Description
Legacy adapter. Remove once we kill off the old ORC layers.
Definition at line 93 of file Legacy.h.
Constructor & Destructor Documentation
JITSymbolResolverAdapter()
llvm::orc::JITSymbolResolverAdapter::JITSymbolResolverAdapter (ExecutionSession & ES, SymbolResolver & R, MaterializationResponsibility * MR)
Definition at line 16 of file Legacy.cpp.
Member Function Documentation
getResponsibilitySet()
Expected< JITSymbolResolverAdapter::LookupSet > llvm::orc::JITSymbolResolverAdapter::getResponsibilitySet (const LookupSet & Symbols) override virtual
Returns the subset of the given symbols that should be materialized by the caller.
Only weak/common symbols should be looked up, as strong definitions are implicitly always part of the caller's responsibility.
Implements llvm::JITSymbolResolver.
Definition at line 50 of file Legacy.cpp.
References llvm::orc::SymbolResolver::getResponsibilitySet(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and llvm::orc::ExecutionSession::intern().
lookup()
void llvm::orc::JITSymbolResolverAdapter::lookup (const LookupSet & Symbols, OnResolvedFunction OnResolved) override virtual
Returns the fully resolved address and flags for each of the given symbols.
This method will return an error if any of the given symbols can not be resolved, or if the resolution process itself triggers an error.
Implements llvm::JITSymbolResolver.
Definition at line 20 of file Legacy.cpp.
References llvm::orc::MaterializationResponsibility::addDependenciesForAll(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::orc::ExecutionSession::intern(), llvm::orc::ExecutionSession::legacyFailQuery(), llvm::orc::SymbolResolver::lookup(), and llvm::orc::Resolved.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Legacy.h
lib/ExecutionEngine/Orc/Legacy.cpp