LLVM: llvm::RegBankSelect::MBBInsertPoint Class Reference
llvm::RegBankSelect::MBBInsertPoint Class Reference
Insertion point at the beginning or end of a basic block.
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
Public Member Functions
MBBInsertPoint (MachineBasicBlock &MBB, bool Beginning=true)
bool isSplit () const override
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
uint64_t frequency (const Pass &P) const override
Frequency of the insertion point.
bool canMaterialize () const override
Check whether this insertion point can be materialized.
Public Member Functions inherited from llvm::RegBankSelect::InsertPoint
virtual ~InsertPoint ()=default
MachineBasicBlock::iterator getPoint ()
The first call to this method will cause the splitting to happen if need be, then sub sequent calls just return the iterator to that point.
MachineBasicBlock & getInsertMBB ()
The first call to this method will cause the splitting to happen if need be, then sub sequent calls just return the basic block that contains the insertion point.
MachineBasicBlock::iterator insert (MachineInstr &MI)
Insert MI in the just before getPoint()
virtual bool isSplit () const
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
virtual uint64_t frequency (const Pass &P) const
Frequency of the insertion point.
virtual bool canMaterialize () const
Check whether this insertion point can be materialized.
Additional Inherited Members
virtual void materialize ()=0
Materialize the insertion point.
virtual MachineBasicBlock & getInsertMBBImpl ()=0
Return the materialized insertion basic block.
virtual MachineBasicBlock::iterator getPointImpl ()=0
Return the materialized insertion point.
Protected Attributes inherited from llvm::RegBankSelect::InsertPoint
bool WasMaterialized = false
Tell if the insert point has already been materialized.
Detailed Description
Insertion point at the beginning or end of a basic block.
Definition at line 236 of file RegBankSelect.h.
Constructor & Destructor Documentation
MBBInsertPoint()
llvm::RegBankSelect::MBBInsertPoint::MBBInsertPoint (MachineBasicBlock & MBB, bool Beginning = true) inline
Definition at line 254 of file RegBankSelect.h.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstNonPHI(), and llvm::MachineBasicBlock::getFirstTerminator().
Member Function Documentation
canMaterialize()
bool llvm::RegBankSelect::MBBInsertPoint::canMaterialize () const inline override virtual
Check whether this insertion point can be materialized.
As soon as getPoint is called and thus, the point materialized calling this method does not make sense.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 268 of file RegBankSelect.h.
frequency()
uint64_t RegBankSelect::MBBInsertPoint::frequency (const Pass & P) const override virtual
Frequency of the insertion point.
P is used to access the various analysis that will help to get that information, like MachineBlockFrequencyInfo. If P does not contain enough enough to return the actual frequency, this returns 1.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 889 of file RegBankSelect.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::BlockFrequency::getFrequency(), and P.
isSplit()
bool llvm::RegBankSelect::MBBInsertPoint::isSplit () const inline override virtual
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 266 of file RegBankSelect.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegBankSelect.h
lib/CodeGen/GlobalISel/RegBankSelect.cpp