LLVM: llvm::LegalizationArtifactCombiner Class Reference
llvm::LegalizationArtifactCombiner Class Reference
#include "llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h"
Public Member Functions
LegalizationArtifactCombiner (MachineIRBuilder &B, MachineRegisterInfo &MRI, const LegalizerInfo &LI)
bool tryCombineAnyExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
bool tryCombineZExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
bool tryCombineSExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
bool tryFoldImplicitDef (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
bool tryCombineMerges (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
bool tryCombineExtract (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts)
bool tryCombineInstruction (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, GISelObserverWrapper &WrapperObserver)
Try to combine away MI.
Static Public Member Functions
static unsigned getMergeOpcode (LLT OpTy, LLT DestTy)
static bool isMergeLikeOpcode (unsigned Opc)
Detailed Description
Definition at line 26 of file LegalizationArtifactCombiner.h.
Constructor & Destructor Documentation
LegalizationArtifactCombiner()
llvm::LegalizationArtifactCombiner::LegalizationArtifactCombiner (MachineIRBuilder & B, MachineRegisterInfo & MRI, const LegalizerInfo & LI) inline
Definition at line 44 of file LegalizationArtifactCombiner.h.
References MRI.
Member Function Documentation
getMergeOpcode()
static unsigned llvm::LegalizationArtifactCombiner::getMergeOpcode (LLT OpTy, LLT DestTy) inline static
Definition at line 206 of file LegalizationArtifactCombiner.h.
References llvm::LLT::isVector().
Referenced by tryCombineMerges().
isMergeLikeOpcode()
static bool llvm::LegalizationArtifactCombiner::isMergeLikeOpcode (unsigned Opc) inline static
Definition at line 320 of file LegalizationArtifactCombiner.h.
Referenced by tryCombineExtract().
tryCombineAnyExt()
bool llvm::LegalizationArtifactCombiner::tryCombineAnyExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Definition at line 48 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::MachineInstr::getOpcode(), llvm::LLT::getSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::MachineIRBuilder::setInstr(), and tryFoldImplicitDef().
Referenced by tryCombineInstruction().
tryCombineExtract()
bool llvm::LegalizationArtifactCombiner::tryCombineExtract (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Definition at line 331 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), isMergeLikeOpcode(), MI, MRI, and llvm::MachineIRBuilder::setInstr().
Referenced by tryCombineInstruction().
tryCombineInstruction()
bool llvm::LegalizationArtifactCombiner::tryCombineInstruction (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, GISelObserverWrapper & WrapperObserver) inline
Try to combine away MI.
Returns true if it combined away the MI. Adds instructions that are dead as a result of the combine into DeadInsts, which can include MI.
Definition at line 383 of file LegalizationArtifactCombiner.h.
References llvm::SmallVectorBase::empty(), MI, MRI, tryCombineAnyExt(), tryCombineExtract(), tryCombineInstruction(), tryCombineMerges(), tryCombineSExt(), and tryCombineZExt().
Referenced by llvm::Legalizer::runOnMachineFunction(), and tryCombineInstruction().
tryCombineMerges()
bool llvm::LegalizationArtifactCombiner::tryCombineMerges (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Definition at line 216 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::getDefIgnoringCopies(), getMergeOpcode(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), Idx, MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::MachineIRBuilder::setInstr().
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl(), and tryCombineInstruction().
tryCombineSExt()
bool llvm::LegalizationArtifactCombiner::tryCombineSExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Definition at line 137 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::LLT::getScalarSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::MachineIRBuilder::setInstr(), and tryFoldImplicitDef().
Referenced by tryCombineInstruction().
tryCombineZExt()
bool llvm::LegalizationArtifactCombiner::tryCombineZExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Definition at line 94 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildAnyExtOrTrunc(), llvm::MachineIRBuilder::buildConstant(), llvm::dbgs(), llvm::APInt::getAllOnesValue(), llvm::LLT::getSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::MachineIRBuilder::setInstr(), and tryFoldImplicitDef().
Referenced by tryCombineInstruction().
tryFoldImplicitDef()
bool llvm::LegalizationArtifactCombiner::tryFoldImplicitDef (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts) inline
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
Definition at line 172 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), DefMI, llvm::getOpcodeDef(), LLVM_DEBUG, MI, MRI, and llvm::MachineIRBuilder::setInstr().
Referenced by tryCombineAnyExt(), tryCombineSExt(), and tryCombineZExt().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h