LLVM: llvm::jitlink::MachOAtomGraphBuilder::MachOSection Class Reference
llvm::jitlink::MachOAtomGraphBuilder::MachOSection Class Reference
#include "ExecutionEngine/JITLink/MachOAtomGraphBuilder.h"
Public Member Functions
MachOSection ()=default
MachOSection (Section &GenericSection, JITTargetAddress Address, unsigned Alignment)
Create a MachO section with the given address and alignment.
MachOSection (Section &GenericSection)
Create a section without address, content or size (used for common symbol sections).
Section & getGenericSection () const
StringRef getName () const
MachOSection & setContent (StringRef Content)
MachOSection & setZeroFill (uint64_t Size)
bool isZeroFill () const
bool empty () const
size_t getSize () const
StringRef getContent () const
JITTargetAddress getAddress () const
unsigned getAlignment () const
MachOSection & setNoDeadStrip (bool NoDeadStrip)
bool isNoDeadStrip () const
Detailed Description
Definition at line 33 of file MachOAtomGraphBuilder.h.
Constructor & Destructor Documentation
MachOSection() [1/3]
llvm::jitlink::MachOAtomGraphBuilder::MachOSection::MachOSection () default
MachOSection() [2/3]
llvm::jitlink::MachOAtomGraphBuilder::MachOSection::MachOSection (Section & GenericSection, JITTargetAddress Address, unsigned Alignment) inline
Create a MachO section with the given address and alignment.
Definition at line 38 of file MachOAtomGraphBuilder.h.
References llvm::Address.
MachOSection() [3/3]
llvm::jitlink::MachOAtomGraphBuilder::MachOSection::MachOSection (Section & GenericSection) inline
Create a section without address, content or size (used for common symbol sections).
Definition at line 45 of file MachOAtomGraphBuilder.h.
Member Function Documentation
empty()
bool llvm::jitlink::MachOAtomGraphBuilder::MachOSection::empty () const inline
Definition at line 72 of file MachOAtomGraphBuilder.h.
References getSize().
getAddress()
JITTargetAddress llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getAddress () const inline
Definition at line 81 of file MachOAtomGraphBuilder.h.
getAlignment()
unsigned llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getAlignment () const inline
Definition at line 83 of file MachOAtomGraphBuilder.h.
getContent()
StringRef llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getContent () const inline
Definition at line 76 of file MachOAtomGraphBuilder.h.
References assert().
getGenericSection()
Section & llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getGenericSection () const inline
Definition at line 47 of file MachOAtomGraphBuilder.h.
References assert().
getName()
StringRef llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getName () const inline
Definition at line 52 of file MachOAtomGraphBuilder.h.
References assert(), and llvm::jitlink::Section::getName().
getSize()
size_t llvm::jitlink::MachOAtomGraphBuilder::MachOSection::getSize () const inline
Definition at line 74 of file MachOAtomGraphBuilder.h.
Referenced by empty().
isNoDeadStrip()
bool llvm::jitlink::MachOAtomGraphBuilder::MachOSection::isNoDeadStrip () const inline
Definition at line 90 of file MachOAtomGraphBuilder.h.
isZeroFill()
bool llvm::jitlink::MachOAtomGraphBuilder::MachOSection::isZeroFill () const inline
Definition at line 70 of file MachOAtomGraphBuilder.h.
setContent()
MachOSection & llvm::jitlink::MachOAtomGraphBuilder::MachOSection::setContent (StringRef Content) inline
Definition at line 57 of file MachOAtomGraphBuilder.h.
References assert(), llvm::StringRef::data(), and llvm::StringRef::size().
setNoDeadStrip()
MachOSection & llvm::jitlink::MachOAtomGraphBuilder::MachOSection::setNoDeadStrip (bool NoDeadStrip) inline
Definition at line 85 of file MachOAtomGraphBuilder.h.
setZeroFill()
MachOSection & llvm::jitlink::MachOAtomGraphBuilder::MachOSection::setZeroFill (uint64_t Size) inline
Definition at line 64 of file MachOAtomGraphBuilder.h.
References assert().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/MachOAtomGraphBuilder.h