LLVM: llvm::raw_sha1_ostream Class Reference
llvm::raw_sha1_ostream Class Reference
A raw_ostream that hash the content using the sha1 algorithm.
#include "llvm/Support/raw_sha1_ostream.h"
Public Member Functions
StringRef sha1 ()
Return the current SHA1 hash for the content of the stream.
void resetHash ()
Reset the internal state to start over from scratch.
uint64_t current_pos () const override
Return the current position within the stream, not counting the bytes currently in the buffer.
Public Member Functions inherited from llvm::raw_ostream
raw_ostream (bool unbuffered=false)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '\t', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the foreground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
Additional Inherited Members
Public Types inherited from llvm::raw_ostream
enum Colors {
BLACK = 0 , RED , GREEN , YELLOW ,
BLUE , MAGENTA , CYAN , WHITE ,
SAVEDCOLOR
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Protected Member Functions inherited from llvm::raw_ostream
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
A raw_ostream that hash the content using the sha1 algorithm.
Definition at line 23 of file raw_sha1_ostream.h.
Member Function Documentation
current_pos()
uint64_t llvm::raw_sha1_ostream::current_pos () const inline override virtual
Return the current position within the stream, not counting the bytes currently in the buffer.
Implements llvm::raw_ostream.
Definition at line 41 of file raw_sha1_ostream.h.
resetHash()
void llvm::raw_sha1_ostream::resetHash () inline
Reset the internal state to start over from scratch.
Definition at line 39 of file raw_sha1_ostream.h.
References llvm::SHA1::init().
sha1()
StringRef llvm::raw_sha1_ostream::sha1 () inline
Return the current SHA1 hash for the content of the stream.
Definition at line 33 of file raw_sha1_ostream.h.
References llvm::raw_ostream::flush(), and llvm::SHA1::result().
The documentation for this class was generated from the following file:
include/llvm/Support/raw_sha1_ostream.h