LLVM: llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
#include "llvm/ADT/EquivalenceClasses.h"
Public Types
using size_type = size_t
using pointer = typename super::pointer
using reference = typename super::reference
Public Member Functions
member_iterator ()=default
member_iterator (const ECValue *N)
reference operator* () const
pointer operator-> () const
member_iterator & operator++ ()
member_iterator operator++ (int)
bool operator== (const member_iterator &RHS) const
bool operator!= (const member_iterator &RHS) const
Friends
class EquivalenceClasses
Detailed Description
template<class ElemTy>
class llvm::EquivalenceClasses< ElemTy >::member_iterator
Definition at line 251 of file EquivalenceClasses.h.
Member Typedef Documentation
pointer
template<class ElemTy > using llvm::EquivalenceClasses< ElemTy >::member_iterator::pointer = typename super::pointer
Definition at line 262 of file EquivalenceClasses.h.
reference
template<class ElemTy > using llvm::EquivalenceClasses< ElemTy >::member_iterator::reference = typename super::reference
Definition at line 263 of file EquivalenceClasses.h.
size_type
template<class ElemTy > using llvm::EquivalenceClasses< ElemTy >::member_iterator::size_type = size_t
Definition at line 261 of file EquivalenceClasses.h.
Constructor & Destructor Documentation
member_iterator() [1/2]
template<class ElemTy > llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator () explicit default
member_iterator() [2/2]
template<class ElemTy > llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator (const ECValue * N) inline explicit
Definition at line 266 of file EquivalenceClasses.h.
Member Function Documentation
operator!=()
template<class ElemTy > bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator!= (const member_iterator & RHS) const inline
Definition at line 289 of file EquivalenceClasses.h.
operator*()
template<class ElemTy > reference llvm::EquivalenceClasses< ElemTy >::member_iterator::operator* () const inline
Definition at line 268 of file EquivalenceClasses.h.
References assert().
Referenced by llvm::EquivalenceClasses< ElemTy >::member_iterator::operator->().
operator++() [1/2]
template<class ElemTy > member_iterator & llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ () inline
Definition at line 274 of file EquivalenceClasses.h.
References assert().
operator++() [2/2]
template<class ElemTy > member_iterator llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ (int) inline
Definition at line 280 of file EquivalenceClasses.h.
operator->()
template<class ElemTy > pointer llvm::EquivalenceClasses< ElemTy >::member_iterator::operator-> () const inline
Definition at line 272 of file EquivalenceClasses.h.
References llvm::EquivalenceClasses< ElemTy >::member_iterator::operator*().
operator==()
template<class ElemTy > bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator== (const member_iterator & RHS) const inline
Definition at line 286 of file EquivalenceClasses.h.
Friends And Related Function Documentation
EquivalenceClasses
template<class ElemTy > friend class EquivalenceClasses friend
Definition at line 253 of file EquivalenceClasses.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/EquivalenceClasses.h