LLVM: llvm::APByteStreamer Class Reference
llvm::APByteStreamer Class Reference final
#include "CodeGen/AsmPrinter/ByteStreamer.h"
Public Member Functions
APByteStreamer (AsmPrinter &Asm)
void EmitInt8 (uint8_t Byte, const Twine &Comment) override
void EmitSLEB128 (uint64_t DWord, const Twine &Comment) override
void EmitULEB128 (uint64_t DWord, const Twine &Comment, unsigned PadTo) override
virtual void EmitInt8 (uint8_t Byte, const Twine &Comment="")=0
virtual void EmitSLEB128 (uint64_t DWord, const Twine &Comment="")=0
virtual void EmitULEB128 (uint64_t DWord, const Twine &Comment="", unsigned PadTo=0)=0
Additional Inherited Members
Protected Member Functions inherited from llvm::ByteStreamer
~ByteStreamer ()=default
ByteStreamer (const ByteStreamer &)=default
ByteStreamer ()=default
Detailed Description
Definition at line 37 of file ByteStreamer.h.
Constructor & Destructor Documentation
APByteStreamer()
llvm::APByteStreamer::APByteStreamer (AsmPrinter & Asm) inline
Definition at line 42 of file ByteStreamer.h.
Member Function Documentation
EmitInt8()
void llvm::APByteStreamer::EmitInt8 (uint8_t Byte, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 43 of file ByteStreamer.h.
References llvm::AsmPrinter::emitInt8(), and llvm::AsmPrinter::OutStreamer.
EmitSLEB128()
void llvm::APByteStreamer::EmitSLEB128 (uint64_t DWord, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 47 of file ByteStreamer.h.
References llvm::AsmPrinter::EmitSLEB128(), and llvm::AsmPrinter::OutStreamer.
EmitULEB128()
void llvm::APByteStreamer::EmitULEB128 (uint64_t DWord, const Twine & Comment, unsigned PadTo) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 51 of file ByteStreamer.h.
References llvm::AsmPrinter::EmitULEB128(), and llvm::AsmPrinter::OutStreamer.
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/ByteStreamer.h