LLVM: llvm::orc::ObjectLayer Class Reference
llvm::orc::ObjectLayer Class Reference abstract
Interface for Layers that accept object files.
#include "llvm/ExecutionEngine/Orc/Layer.h"
Public Member Functions
ObjectLayer (ExecutionSession &ES)
virtual ~ObjectLayer ()
ExecutionSession & getExecutionSession ()
Returns the execution session for this layer.
virtual Error add (JITDylib &JD, std::unique_ptr< MemoryBuffer > O, VModuleKey K=VModuleKey())
Adds a MaterializationUnit representing the given IR to the given JITDylib.
virtual void emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O)=0
Emit should materialize the given IR.
Detailed Description
Interface for Layers that accept object files.
Definition at line 113 of file Layer.h.
Constructor & Destructor Documentation
ObjectLayer()
llvm::orc::ObjectLayer::ObjectLayer (ExecutionSession & ES)
Definition at line 102 of file Layer.cpp.
~ObjectLayer()
llvm::orc::ObjectLayer::~ObjectLayer () virtual
Definition at line 104 of file Layer.cpp.
Member Function Documentation
add()
Error llvm::orc::ObjectLayer::add (JITDylib & JD, std::unique_ptr< MemoryBuffer > O, VModuleKey K = VModuleKey()) virtual
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Definition at line 106 of file Layer.cpp.
References llvm::orc::BasicObjectLayerMaterializationUnit::Create(), and llvm::orc::JITDylib::define().
emit()
virtual void llvm::orc::ObjectLayer::emit (MaterializationResponsibility R, std::unique_ptr< MemoryBuffer > O) pure virtual
Emit should materialize the given IR.
Implemented in llvm::orc::ObjectLinkingLayer, llvm::orc::ObjectTransformLayer, and llvm::orc::RTDyldObjectLinkingLayer.
Referenced by llvm::orc::ObjectTransformLayer::emit(), and llvm::orc::IRCompileLayer::emit().
getExecutionSession()
ExecutionSession & llvm::orc::ObjectLayer::getExecutionSession () inline
Returns the execution session for this layer.
Definition at line 119 of file Layer.h.
Referenced by llvm::orc::BasicObjectLayerMaterializationUnit::Create(), llvm::orc::ObjectTransformLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::orc::ObjectLinkingLayerJITLinkContext::lookup(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFailed(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), and llvm::orc::ObjectLinkingLayer::~ObjectLinkingLayer().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Layer.h
lib/ExecutionEngine/Orc/Layer.cpp