LLVM: llvm::object::MachOUniversalBinary Class Reference
llvm::object::MachOUniversalBinary Class Reference
#include "llvm/Object/MachOUniversal.h"
Classes
class object_iterator
class ObjectForArch
Public Member Functions
MachOUniversalBinary (MemoryBufferRef Souce, Error &Err)
object_iterator begin_objects () const
object_iterator end_objects () const
iterator_range< object_iterator > objects () const
uint32_t getMagic () const
uint32_t getNumberOfObjects () const
Expected< std::unique_ptr< MachOObjectFile > > getObjectForArch (StringRef ArchName) const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< std::unique_ptr< MachOUniversalBinary > > create (MemoryBufferRef Source)
static bool classof (Binary const *V)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 28 of file MachOUniversal.h.
Constructor & Destructor Documentation
MachOUniversalBinary()
MachOUniversalBinary::MachOUniversalBinary (MemoryBufferRef Souce, Error & Err)
Definition at line 112 of file MachOUniversal.cpp.
References A, B, llvm::StringRef::begin(), llvm::MachO::CPU_SUBTYPE_MASK, llvm::object::Binary::Data, llvm::MachO::FAT_MAGIC, llvm::MachO::FAT_MAGIC_64, llvm::MemoryBufferRef::getBufferSize(), llvm::object::Binary::getData(), H, llvm::object::invalid_file_type, malformedError(), MAXSECTALIGN, llvm::StringRef::size(), and llvm::Error::success().
Member Function Documentation
begin_objects()
object_iterator llvm::object::MachOUniversalBinary::begin_objects () const inline
Definition at line 141 of file MachOUniversal.h.
Referenced by objects().
classof()
static bool llvm::object::MachOUniversalBinary::classof (Binary const * V) inline static
Definition at line 156 of file MachOUniversal.h.
References llvm::object::Binary::isMachOUniversalBinary().
create()
Expected< std::unique_ptr< MachOUniversalBinary > > MachOUniversalBinary::create (MemoryBufferRef Source) static
Definition at line 103 of file MachOUniversal.cpp.
References llvm::Error::success().
end_objects()
object_iterator llvm::object::MachOUniversalBinary::end_objects () const inline
Definition at line 144 of file MachOUniversal.h.
Referenced by objects().
getMagic()
uint32_t llvm::object::MachOUniversalBinary::getMagic () const inline
Definition at line 152 of file MachOUniversal.h.
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::getAlign(), llvm::object::MachOUniversalBinary::ObjectForArch::getArchFlagName(), llvm::object::MachOUniversalBinary::ObjectForArch::getCPUSubType(), llvm::object::MachOUniversalBinary::ObjectForArch::getCPUType(), llvm::object::MachOUniversalBinary::ObjectForArch::getOffset(), llvm::object::MachOUniversalBinary::ObjectForArch::getReserved(), llvm::object::MachOUniversalBinary::ObjectForArch::getSize(), and llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch().
getNumberOfObjects()
uint32_t llvm::object::MachOUniversalBinary::getNumberOfObjects () const inline
Definition at line 153 of file MachOUniversal.h.
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch().
getObjectForArch()
Expected< std::unique_ptr< MachOObjectFile > > MachOUniversalBinary::getObjectForArch (StringRef ArchName) const
Definition at line 213 of file MachOUniversal.cpp.
References llvm::object::arch_not_found, objects(), and llvm::Triple::UnknownArch.
objects()
iterator_range< object_iterator > llvm::object::MachOUniversalBinary::objects () const inline
Definition at line 148 of file MachOUniversal.h.
References begin_objects(), end_objects(), and llvm::make_range().
Referenced by getObjectForArch().
The documentation for this class was generated from the following files:
include/llvm/Object/MachOUniversal.h
lib/Object/MachOUniversal.cpp