LLVM: llvm::orc::LLJIT Class Reference
llvm::orc::LLJIT Class Reference
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
~LLJIT ()
Destruct this instance.
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this instance.
const DataLayout & getDataLayout () const
Returns a reference to the DataLayout for this instance.
JITDylib & getMainJITDylib ()
Returns a reference to the JITDylib representing the JIT'd main program.
JITDylib * getJITDylibByName (StringRef Name)
Returns the JITDylib with the given name, or nullptr if no JITDylib with that name exists.
JITDylib & createJITDylib (std::string Name)
Create a new JITDylib with the given name and return a reference to it.
Error defineAbsolute (StringRef Name, JITEvaluatedSymbol Address)
Convenience method for defining an absolute symbol.
Error addIRModule (JITDylib &JD, ThreadSafeModule TSM)
Adds an IR module to the given JITDylib.
Error addIRModule (ThreadSafeModule TSM)
Adds an IR module to the Main JITDylib.
Error addObjectFile (JITDylib &JD, std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Error addObjectFile (std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Expected< JITEvaluatedSymbol > lookupLinkerMangled (JITDylib &JD, StringRef Name)
Look up a symbol in JITDylib JD by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Expected< JITEvaluatedSymbol > lookupLinkerMangled (StringRef Name)
Look up a symbol in the main JITDylib by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Expected< JITEvaluatedSymbol > lookup (JITDylib &JD, StringRef UnmangledName)
Look up a symbol in JITDylib JD based on its IR symbol name.
Expected< JITEvaluatedSymbol > lookup (StringRef UnmangledName)
Look up a symbol in the main JITDylib based on its IR symbol name.
Error runConstructors ()
Runs all not-yet-run static constructors.
Error runDestructors ()
Runs all not-yet-run static destructors.
ObjectLayer & getObjLinkingLayer ()
Returns a reference to the ObjLinkingLayer.
Static Public Member Functions
static Expected< std::unique_ptr< LLJIT > > Create (LLJITBuilderState &S)
Protected Member Functions
LLJIT (LLJITBuilderState &S, Error &Err)
Create an LLJIT instance with a single compile thread.
std::string mangle (StringRef UnmangledName)
Error applyDataLayout (Module &M)
void recordCtorDtors (Module &M)
Static Protected Member Functions
static std::unique_ptr< ObjectLayer > createObjectLinkingLayer (LLJITBuilderState &S, ExecutionSession &ES)
static Expected< IRCompileLayer::CompileFunction > createCompileFunction (LLJITBuilderState &S, JITTargetMachineBuilder JTMB)
Protected Attributes
std::unique_ptr< ExecutionSession > ES
JITDylib & Main
DataLayout DL
std::unique_ptr< ThreadPool > CompileThreads
std::unique_ptr< ObjectLayer > ObjLinkingLayer
std::unique_ptr< IRCompileLayer > CompileLayer
CtorDtorRunner CtorRunner
CtorDtorRunner DtorRunner
Friends
template<typename , typename , typename >
class LLJITBuilderSetters
Detailed Description
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
Create instances using LLJITBuilder.
Definition at line 35 of file LLJIT.h.
Constructor & Destructor Documentation
~LLJIT()
llvm::orc::LLJIT::~LLJIT ()
Destruct this instance.
If a multi-threaded instance, waits for all compile threads to complete.
Definition at line 30 of file LLJIT.cpp.
References CompileThreads.
LLJIT()
llvm::orc::LLJIT::LLJIT (LLJITBuilderState & S, Error & Err) protected
Create an LLJIT instance with a single compile thread.
Definition at line 94 of file LLJIT.cpp.
References _, CompileLayer, CompileThreads, createCompileFunction(), createObjectLinkingLayer(), DL, ES, llvm::orc::LLJITBuilderState::JTMB, llvm::orc::LLJITBuilderState::NumCompileThreads, and ObjLinkingLayer.
Member Function Documentation
addIRModule() [1/2]
Error llvm::orc::LLJIT::addIRModule (JITDylib & JD, ThreadSafeModule TSM)
Adds an IR module to the given JITDylib.
Definition at line 41 of file LLJIT.cpp.
References applyDataLayout(), assert(), CompileLayer, ES, and llvm::orc::ThreadSafeModule::getModule().
Referenced by addIRModule().
addIRModule() [2/2]
Error llvm::orc::LLJIT::addIRModule (ThreadSafeModule TSM) inline
Adds an IR module to the Main JITDylib.
Definition at line 77 of file LLJIT.h.
References addIRModule(), and Main.
addObjectFile() [1/2]
Error llvm::orc::LLJIT::addObjectFile (JITDylib & JD, std::unique_ptr< MemoryBuffer > Obj)
Adds an object file to the given JITDylib.
Definition at line 50 of file LLJIT.cpp.
References assert(), ES, and ObjLinkingLayer.
Referenced by addObjectFile().
addObjectFile() [2/2]
Error llvm::orc::LLJIT::addObjectFile (std::unique_ptr< MemoryBuffer > Obj) inline
Adds an object file to the given JITDylib.
Definition at line 85 of file LLJIT.h.
References addObjectFile(), and Main.
applyDataLayout()
Error llvm::orc::LLJIT::applyDataLayout (Module & M) protected
Definition at line 142 of file LLJIT.cpp.
References DL, llvm::inconvertibleErrorCode(), and llvm::Error::success().
Referenced by addIRModule(), and llvm::orc::LLLazyJIT::addLazyIRModule().
Create()
static Expected< std::unique_ptr< LLJIT > > llvm::orc::LLJIT::Create (LLJITBuilderState & S) static
createCompileFunction()
Expected< IRCompileLayer::CompileFunction > llvm::orc::LLJIT::createCompileFunction (LLJITBuilderState & S, JITTargetMachineBuilder JTMB) static protected
If there is a custom compile function creator set then use it.
Definition at line 75 of file LLJIT.cpp.
References llvm::orc::LLJITBuilderState::CreateCompileFunction, llvm::orc::JITTargetMachineBuilder::createTargetMachine(), and llvm::orc::LLJITBuilderState::NumCompileThreads.
Referenced by LLJIT().
createJITDylib()
JITDylib & llvm::orc::LLJIT::createJITDylib (std::string Name) inline
Create a new JITDylib with the given name and return a reference to it.
JITDylib names must be unique. If the given name is derived from user input or elsewhere in the environment then the client should check (e.g. by calling getJITDylibByName) that the given name is not already in use.
Definition at line 66 of file LLJIT.h.
References ES, and Name.
createObjectLinkingLayer()
std::unique_ptr< ObjectLayer > llvm::orc::LLJIT::createObjectLinkingLayer (LLJITBuilderState & S, ExecutionSession & ES) static protected
Definition at line 62 of file LLJIT.cpp.
References llvm::orc::LLJITBuilderState::CreateObjectLinkingLayer, and ES.
Referenced by LLJIT().
defineAbsolute()
Error llvm::orc::LLJIT::defineAbsolute (StringRef Name, JITEvaluatedSymbol Address)
Convenience method for defining an absolute symbol.
Definition at line 35 of file LLJIT.cpp.
References llvm::orc::absoluteSymbols(), llvm::orc::JITDylib::define(), ES, Main, and Name.
getDataLayout()
const DataLayout & llvm::orc::LLJIT::getDataLayout () const inline
Returns a reference to the DataLayout for this instance.
Definition at line 49 of file LLJIT.h.
References DL.
getExecutionSession()
ExecutionSession & llvm::orc::LLJIT::getExecutionSession () inline
Returns the ExecutionSession for this instance.
Definition at line 46 of file LLJIT.h.
References ES.
getJITDylibByName()
JITDylib * llvm::orc::LLJIT::getJITDylibByName (StringRef Name) inline
Returns the JITDylib with the given name, or nullptr if no JITDylib with that name exists.
Definition at line 56 of file LLJIT.h.
References ES, and Name.
getMainJITDylib()
JITDylib & llvm::orc::LLJIT::getMainJITDylib () inline
Returns a reference to the JITDylib representing the JIT'd main program.
Definition at line 52 of file LLJIT.h.
References Main.
getObjLinkingLayer()
ObjectLayer & llvm::orc::LLJIT::getObjLinkingLayer () inline
Returns a reference to the ObjLinkingLayer.
Definition at line 118 of file LLJIT.h.
References ObjLinkingLayer.
lookup() [1/2]
Expected< JITEvaluatedSymbol > llvm::orc::LLJIT::lookup (JITDylib & JD, StringRef UnmangledName) inline
Look up a symbol in JITDylib JD based on its IR symbol name.
Definition at line 102 of file LLJIT.h.
References lookupLinkerMangled(), and mangle().
Referenced by lookup().
lookup() [2/2]
Expected< JITEvaluatedSymbol > llvm::orc::LLJIT::lookup (StringRef UnmangledName) inline
Look up a symbol in the main JITDylib based on its IR symbol name.
Definition at line 107 of file LLJIT.h.
References lookup(), and Main.
lookupLinkerMangled() [1/2]
Expected< JITEvaluatedSymbol > llvm::orc::LLJIT::lookupLinkerMangled (JITDylib & JD, StringRef Name)
Look up a symbol in JITDylib JD by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Definition at line 56 of file LLJIT.cpp.
References ES, and Name.
Referenced by lookup(), and lookupLinkerMangled().
lookupLinkerMangled() [2/2]
Expected< JITEvaluatedSymbol > llvm::orc::LLJIT::lookupLinkerMangled (StringRef Name) inline
Look up a symbol in the main JITDylib by the symbol's linker-mangled name (to look up symbols based on their IR name use the lookup function instead).
Definition at line 97 of file LLJIT.h.
References lookupLinkerMangled(), Main, and Name.
mangle()
std::string llvm::orc::LLJIT::mangle (StringRef UnmangledName) protected
Definition at line 133 of file LLJIT.cpp.
References DL, and llvm::Mangler::getNameWithPrefix().
Referenced by lookup().
recordCtorDtors()
void llvm::orc::LLJIT::recordCtorDtors (Module & M) protected
Definition at line 154 of file LLJIT.cpp.
References llvm::orc::CtorDtorRunner::add(), CtorRunner, DtorRunner, llvm::orc::getConstructors(), and llvm::orc::getDestructors().
Referenced by llvm::orc::LLLazyJIT::addLazyIRModule().
runConstructors()
Error llvm::orc::LLJIT::runConstructors () inline
Runs all not-yet-run static constructors.
Definition at line 112 of file LLJIT.h.
References CtorRunner, and llvm::orc::CtorDtorRunner::run().
runDestructors()
Error llvm::orc::LLJIT::runDestructors () inline
Runs all not-yet-run static destructors.
Definition at line 115 of file LLJIT.h.
References DtorRunner, and llvm::orc::CtorDtorRunner::run().
Friends And Related Function Documentation
LLJITBuilderSetters
template<typename , typename , typename > friend class LLJITBuilderSetters friend
Definition at line 36 of file LLJIT.h.
Member Data Documentation
CompileLayer
std::unique_ptr<IRCompileLayer> llvm::orc::LLJIT::CompileLayer protected
Definition at line 143 of file LLJIT.h.
Referenced by addIRModule(), and LLJIT().
CompileThreads
std::unique_ptr<ThreadPool> llvm::orc::LLJIT::CompileThreads protected
Definition at line 140 of file LLJIT.h.
Referenced by LLJIT(), and ~LLJIT().
CtorRunner
CtorDtorRunner llvm::orc::LLJIT::CtorRunner protected
Definition at line 145 of file LLJIT.h.
Referenced by recordCtorDtors(), and runConstructors().
DL
DataLayout llvm::orc::LLJIT::DL protected
Definition at line 139 of file LLJIT.h.
Referenced by applyDataLayout(), getDataLayout(), LLJIT(), and mangle().
DtorRunner
CtorDtorRunner llvm::orc::LLJIT::DtorRunner protected
Definition at line 145 of file LLJIT.h.
Referenced by recordCtorDtors(), and runDestructors().
ES
std::unique_ptr<ExecutionSession> llvm::orc::LLJIT::ES protected
Definition at line 136 of file LLJIT.h.
Referenced by addIRModule(), llvm::orc::LLLazyJIT::addLazyIRModule(), addObjectFile(), createJITDylib(), createObjectLinkingLayer(), defineAbsolute(), getExecutionSession(), getJITDylibByName(), LLJIT(), and lookupLinkerMangled().
Main
JITDylib& llvm::orc::LLJIT::Main protected
Definition at line 137 of file LLJIT.h.
Referenced by addIRModule(), llvm::orc::LLLazyJIT::addLazyIRModule(), addObjectFile(), defineAbsolute(), getMainJITDylib(), lookup(), and lookupLinkerMangled().
ObjLinkingLayer
std::unique_ptr<ObjectLayer> llvm::orc::LLJIT::ObjLinkingLayer protected
Definition at line 142 of file LLJIT.h.
Referenced by addObjectFile(), getObjLinkingLayer(), and LLJIT().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp