LLVM: llvm::SectionEntry Class Reference
llvm::SectionEntry Class Reference
SectionEntry - represents a section emitted into memory by the dynamic linker.
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h"
Public Member Functions
SectionEntry (StringRef name, uint8_t *address, size_t size, size_t allocationSize, uintptr_t objAddress)
StringRef getName () const
uint8_t * getAddress () const
uint8_t * getAddressWithOffset (unsigned OffsetBytes) const
Return the address of this section with an offset.
size_t getSize () const
uint64_t getLoadAddress () const
void setLoadAddress (uint64_t LA)
uint64_t getLoadAddressWithOffset (unsigned OffsetBytes) const
Return the load address of this section with an offset.
uintptr_t getStubOffset () const
void advanceStubOffset (unsigned StubSize)
uintptr_t getObjAddress () const
Detailed Description
SectionEntry - represents a section emitted into memory by the dynamic linker.
Definition at line 46 of file RuntimeDyldImpl.h.
Constructor & Destructor Documentation
SectionEntry()
llvm::SectionEntry::SectionEntry (StringRef name, uint8_t * address, size_t size, size_t allocationSize, uintptr_t objAddress) inline
Definition at line 75 of file RuntimeDyldImpl.h.
References llvm::Address, and llvm::size().
Member Function Documentation
advanceStubOffset()
void llvm::SectionEntry::advanceStubOffset (unsigned StubSize) inline
Definition at line 108 of file RuntimeDyldImpl.h.
References assert().
getAddress()
uint8_t * llvm::SectionEntry::getAddress () const inline
Definition at line 87 of file RuntimeDyldImpl.h.
References llvm::Address.
Referenced by llvm::dumpSectionMemory(), and llvm::RuntimeDyldMachOCRTPBase< Impl >::registerEHFrames().
getAddressWithOffset()
uint8_t * llvm::SectionEntry::getAddressWithOffset (unsigned OffsetBytes) const inline
Return the address of this section with an offset.
Definition at line 90 of file RuntimeDyldImpl.h.
References llvm::Address, and assert().
getLoadAddress()
uint64_t llvm::SectionEntry::getLoadAddress () const inline
Definition at line 97 of file RuntimeDyldImpl.h.
Referenced by llvm::dumpSectionMemory(), and llvm::RuntimeDyldMachOCRTPBase< Impl >::registerEHFrames().
getLoadAddressWithOffset()
uint64_t llvm::SectionEntry::getLoadAddressWithOffset (unsigned OffsetBytes) const inline
Return the load address of this section with an offset.
Definition at line 101 of file RuntimeDyldImpl.h.
References assert().
getName()
StringRef llvm::SectionEntry::getName () const inline
Definition at line 85 of file RuntimeDyldImpl.h.
Referenced by llvm::dumpSectionMemory().
getObjAddress()
uintptr_t llvm::SectionEntry::getObjAddress () const inline
Definition at line 113 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldCOFFI386::processRelocationRef(), and llvm::RuntimeDyldCOFFThumb::processRelocationRef().
getSize()
size_t llvm::SectionEntry::getSize () const inline
Definition at line 95 of file RuntimeDyldImpl.h.
Referenced by llvm::dumpSectionMemory(), and llvm::RuntimeDyldMachOCRTPBase< Impl >::registerEHFrames().
getStubOffset()
uintptr_t llvm::SectionEntry::getStubOffset () const inline
Definition at line 106 of file RuntimeDyldImpl.h.
setLoadAddress()
void llvm::SectionEntry::setLoadAddress (uint64_t LA) inline
Definition at line 98 of file RuntimeDyldImpl.h.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h