LLVM: llvm::FunctionImporter Class Reference
llvm::FunctionImporter Class Reference
The function importer is automatically importing function from other modules based on the provided summary informations.
#include "llvm/Transforms/IPO/FunctionImport.h"
Classes
struct ImportFailureInfo
Information optionally tracked for candidates the importer decided not to import.
Public Types
enum ImportFailureReason {
None , GlobalVar , NotLive , TooLarge ,
InterposableLinkage , LocalLinkageNotInModule , NotEligible , NoInline
}
The different reasons selectCallee will chose not to import a candidate.
using FunctionsToImportTy = std::unordered_set< GlobalValue::GUID >
Set of functions to import from a source module.
using ImportThresholdsTy = DenseMap< GlobalValue::GUID, std::tuple< unsigned, const GlobalValueSummary *, std::unique_ptr< ImportFailureInfo > > >
Map of callee GUID considered for import into a given module to a pair consisting of the largest threshold applied when deciding whether to import it and, if we decided to import, a pointer to the summary instance imported.
using ImportMapTy = StringMap< FunctionsToImportTy >
The map contains an entry for every module to import from, the key being the module identifier to pass to the ModuleLoader.
using ExportSetTy = std::unordered_set< GlobalValue::GUID >
The set contains an entry for every global value the module exports.
using ModuleLoaderTy = std::function< Expected< std::unique_ptr< Module > >(StringRef Identifier)>
A function of this type is used to load modules referenced by the index.
Public Member Functions
FunctionImporter (const ModuleSummaryIndex &Index, ModuleLoaderTy ModuleLoader)
Create a Function Importer.
Expected< bool > importFunctions (Module &M, const ImportMapTy &ImportList)
Import functions in Module M based on the supplied import list.
Detailed Description
The function importer is automatically importing function from other modules based on the provided summary informations.
Definition at line 33 of file FunctionImport.h.
Member Typedef Documentation
ExportSetTy
using llvm::FunctionImporter::ExportSetTy = std::unordered_set<GlobalValue::GUID>
The set contains an entry for every global value the module exports.
Definition at line 101 of file FunctionImport.h.
FunctionsToImportTy
using llvm::FunctionImporter::FunctionsToImportTy = std::unordered_set<GlobalValue::GUID>
Set of functions to import from a source module.
Each entry is a set containing all the GUIDs of all functions to import for a source module.
Definition at line 37 of file FunctionImport.h.
ImportMapTy
using llvm::FunctionImporter::ImportMapTy = StringMap<FunctionsToImportTy>
The map contains an entry for every module to import from, the key being the module identifier to pass to the ModuleLoader.
The value is the set of functions to import.
Definition at line 98 of file FunctionImport.h.
ImportThresholdsTy
using llvm::FunctionImporter::ImportThresholdsTy = DenseMap<GlobalValue::GUID, std::tuple<unsigned, const GlobalValueSummary *, std::unique_ptr<ImportFailureInfo> >>
Map of callee GUID considered for import into a given module to a pair consisting of the largest threshold applied when deciding whether to import it and, if we decided to import, a pointer to the summary instance imported.
If we decided not to import, the summary will be nullptr.
Definition at line 90 of file FunctionImport.h.
ModuleLoaderTy
using llvm::FunctionImporter::ModuleLoaderTy = std::function<Expected<std::unique_ptr<Module> >(StringRef Identifier)>
A function of this type is used to load modules referenced by the index.
Definition at line 104 of file FunctionImport.h.
Member Enumeration Documentation
ImportFailureReason
enum llvm::FunctionImporter::ImportFailureReason
The different reasons selectCallee will chose not to import a candidate.
Enumerator
None
GlobalVar
NotLive
TooLarge
InterposableLinkage
LocalLinkageNotInModule
NotEligible
NoInline
Definition at line 41 of file FunctionImport.h.
Constructor & Destructor Documentation
FunctionImporter()
llvm::FunctionImporter::FunctionImporter (const ModuleSummaryIndex & Index, ModuleLoaderTy ModuleLoader) inline
Create a Function Importer.
Definition at line 108 of file FunctionImport.h.
Member Function Documentation
importFunctions()
Expected< bool > FunctionImporter::importFunctions (Module & M, const ImportMapTy & ImportList)
Import functions in Module M based on the supplied import list.
Definition at line 1081 of file FunctionImport.cpp.
References assert(), llvm::dbgs(), EnableImportMetadata, llvm::StringMap< ValueTy, AllocatorTy >::end(), F, llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::IntervalMapImpl::NodeRef::get(), llvm::SetVector< T, Vector, Set >::getArrayRef(), llvm::GlobalValue::getBaseObject(), llvm::Module::getContext(), llvm::GlobalValue::getGUID(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::Module::getSourceFileName(), llvm::Import, llvm::SetVector< T, Vector, Set >::insert(), internalizeGVsAfterImport(), LLVM_DEBUG, llvm::GlobalValue::materialize(), llvm::IRMover::move(), Name, PrintImports, llvm::renameModuleForThinLTO(), replaceAliasWithAliasee(), llvm::report_fatal_error(), llvm::SetVector< T, Vector, Set >::size(), llvm::Expected< T >::takeError(), and llvm::UpgradeDebugInfo().
Referenced by doImportingForModule(), and llvm::lto::thinBackend().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/FunctionImport.h
lib/Transforms/IPO/FunctionImport.cpp