LLVM: llvm::SystemZTTIImpl Class Reference
llvm::SystemZTTIImpl Class Reference
#include "Target/SystemZ/SystemZTargetTransformInfo.h"
Public Member Functions
SystemZTTIImpl (const SystemZTargetMachine *TM, const Function &F)
Scalar TTI Implementations
unsigned getInliningThresholdMultiplier ()
int getIntImmCost (const APInt &Imm, Type *Ty)
int getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
int getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isLSRCostLess (TargetTransformInfo::LSRCost &C1, TargetTransformInfo::LSRCost &C2)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getCacheLineSize ()
unsigned getPrefetchDistance ()
unsigned getMinPrefetchStride ()
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool prefersVectorizedAddressing ()
bool LSRWithInstrQueries ()
bool supportsEfficientVectorElementLoadStore ()
bool enableInterleavedAccessVectorization ()
int getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >())
int getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getVectorTruncCost (Type *SrcTy, Type *DstTy)
unsigned getVectorBitmaskConversionCost (Type *SrcTy, Type *DstTy)
unsigned getBoolVecToIntConversionCost (unsigned Opcode, Type *Dst, const Instruction *I)
int getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
int getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I=nullptr)
int getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
bool isFoldableLoad (const LoadInst *Ld, const Instruction *&FoldedValue)
int getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
int getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
int getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
int getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=UINT_MAX)
Public Member Functions inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
int getInstructionLatency (const Instruction *I)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getScalarizationOverhead (Type *VecTy, ArrayRef< const Value * > Args)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >())
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
Get intrinsic cost based on arguments.
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=std::numeric_limits< unsigned >::max())
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwise, bool)
Try to calculate op costs for min/max reduction operations.
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
unsigned getCallCost (const Function *F, int NumArgs, const User *U)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getUserCost (const User *U, ArrayRef< const Value * > Operands)
int getInstructionLatency (const Instruction *I)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType)
bool isLegalMaskedLoad (Type *DataType)
bool isLegalNTStore (Type *DataType, unsigned Alignment)
bool isLegalNTLoad (Type *DataType, unsigned Alignment)
bool isLegalMaskedScatter (Type *DataType)
bool isLegalMaskedGather (Type *DataType)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize ()
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level)
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level)
unsigned getPrefetchDistance ()
unsigned getMinPrefetchStride ()
unsigned getMaxPrefetchIterationsAhead ()
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value * > Args)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument * > &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 18 of file SystemZTargetTransformInfo.h.
Constructor & Destructor Documentation
SystemZTTIImpl()
llvm::SystemZTTIImpl::SystemZTTIImpl (const SystemZTargetMachine * TM, const Function & F) inline explicit
Definition at line 32 of file SystemZTargetTransformInfo.h.
Member Function Documentation
enableInterleavedAccessVectorization()
bool llvm::SystemZTTIImpl::enableInterleavedAccessVectorization () inline
Definition at line 70 of file SystemZTargetTransformInfo.h.
getArithmeticInstrCost()
int SystemZTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value * > Args = ArrayRef<const Value *>())
Definition at line 349 of file SystemZTargetTransformInfo.cpp.
References A, llvm::MCBinaryExpr::AShr, assert(), C, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::BasicTTIImplBase< SystemZTTIImpl >::getArithmeticInstrCost(), getArithmeticInstrCost(), getNumVectorRegs(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::ConstantInt::getValue(), llvm::Type::getVectorNumElements(), llvm::SystemZSubtarget::hasLoadStoreOnCond2(), llvm::SystemZSubtarget::hasMiscellaneousExtensions3(), llvm::SystemZSubtarget::hasVector(), llvm::SystemZSubtarget::hasVectorEnhancements1(), I, llvm::APInt::isPowerOf2(), llvm::Type::isVectorTy(), llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::Shl, and llvm::AtomicRMWInst::Xor.
Referenced by getArithmeticInstrCost().
getBoolVecToIntConversionCost()
unsigned SystemZTTIImpl::getBoolVecToIntConversionCost (unsigned Opcode, Type * Dst, const Instruction * I)
Definition at line 653 of file SystemZTargetTransformInfo.cpp.
References assert(), getCmpOpsType(), getNumVectorRegs(), getVectorBitmaskConversionCost(), llvm::Type::getVectorNumElements(), I, llvm::Type::isVectorTy(), and llvm::CCValAssign::ZExt.
Referenced by getCastInstrCost().
getCacheLineSize()
unsigned llvm::SystemZTTIImpl::getCacheLineSize () inline
Definition at line 62 of file SystemZTargetTransformInfo.h.
getCastInstrCost()
int SystemZTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * I = nullptr)
Definition at line 670 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::CCValAssign::FPExt, getBoolVecToIntConversionCost(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getCastInstrCost(), getCastInstrCost(), getCmpOpsType(), getElSizeLog2Diff(), getNumVectorRegs(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::Type::getVectorNumElements(), getVectorTruncCost(), llvm::SystemZSubtarget::hasLoadStoreOnCond2(), llvm::SystemZSubtarget::hasVector(), llvm::SystemZSubtarget::hasVectorEnhancements2(), I, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
Referenced by getCastInstrCost().
getCmpSelInstrCost()
int SystemZTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, const Instruction * I = nullptr)
Definition at line 807 of file SystemZTargetTransformInfo.cpp.
References assert(), C, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNO, getCmpOpsType(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getCmpSelInstrCost(), getNumVectorRegs(), getOperandsExtensionCost(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), getVectorBitmaskConversionCost(), llvm::Type::getVectorNumElements(), llvm::SystemZSubtarget::hasVector(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, llvm::Type::isFloatingPointTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), and llvm::MCID::Select.
getInliningThresholdMultiplier()
unsigned llvm::SystemZTTIImpl::getInliningThresholdMultiplier () inline
Definition at line 39 of file SystemZTargetTransformInfo.h.
getInterleavedMemoryOpCost()
int SystemZTTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 1061 of file SystemZTargetTransformInfo.cpp.
References A, assert(), B, llvm::BitVector::count(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getInterleavedMemoryOpCost(), getNumVectorRegs(), getScalarSizeInBits(), llvm::Type::getVectorNumElements(), and llvm::BitVector::set().
getIntImmCost() [1/3]
int SystemZTTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Definition at line 33 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost().
getIntImmCost() [2/3]
int SystemZTTIImpl::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Definition at line 183 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), Idx, llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), and llvm::TargetTransformInfo::TCC_Free.
getIntImmCost() [3/3]
int SystemZTTIImpl::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Definition at line 65 of file SystemZTargetTransformInfo.cpp.
References llvm::MCBinaryExpr::AShr, assert(), llvm::LazyCallGraph::Edge::Call, llvm::APInt::getBitWidth(), llvm::SystemZSubtarget::getInstrInfo(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), Idx, llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::Mul, llvm::PtrToIntOperator::PtrToInt, llvm::MCID::Select, llvm::CCValAssign::SExt, llvm::MCBinaryExpr::Shl, llvm::AtomicRMWInst::Sub, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, TII, llvm::AtomicRMWInst::Xor, and llvm::CCValAssign::ZExt.
getIntrinsicInstrCost() [1/2]
int SystemZTTIImpl::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed = UINT_MAX)
Definition at line 1137 of file SystemZTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::getIntrinsicInstrCost(), getVectorIntrinsicInstrCost(), and RetTy.
getIntrinsicInstrCost() [2/2]
int SystemZTTIImpl::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF = 1)
Definition at line 1128 of file SystemZTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::getIntrinsicInstrCost(), getVectorIntrinsicInstrCost(), and RetTy.
getMemoryOpCost()
int SystemZTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace, const Instruction * I = nullptr)
Definition at line 996 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getNumberOfParts(), llvm::User::getNumOperands(), getNumVectorRegs(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::hasOneUse(), llvm::SystemZSubtarget::hasVectorEnhancements2(), I, isBswapIntrinsicCall(), isFoldableLoad(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), SI, and llvm::Value::user_begin().
Referenced by getUnrollingPreferences().
getMinPrefetchStride()
unsigned llvm::SystemZTTIImpl::getMinPrefetchStride () inline
Definition at line 64 of file SystemZTargetTransformInfo.h.
getNumberOfRegisters()
unsigned SystemZTTIImpl::getNumberOfRegisters (bool Vector)
Definition at line 307 of file SystemZTargetTransformInfo.cpp.
References llvm::SystemZSubtarget::hasVector().
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind SystemZTTIImpl::getPopcntSupport (unsigned TyWidth)
Definition at line 233 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::SystemZSubtarget::hasPopulationCount(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
getPrefetchDistance()
unsigned llvm::SystemZTTIImpl::getPrefetchDistance () inline
Definition at line 63 of file SystemZTargetTransformInfo.h.
getRegisterBitWidth()
unsigned SystemZTTIImpl::getRegisterBitWidth (bool Vector) const
Definition at line 317 of file SystemZTargetTransformInfo.cpp.
References llvm::SystemZSubtarget::hasVector().
getShuffleCost()
int SystemZTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Definition at line 513 of file SystemZTargetTransformInfo.cpp.
References assert(), getNumVectorRegs(), llvm::Type::getScalarType(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getShuffleCost(), llvm::SystemZSubtarget::hasVector(), llvm::Type::isFP128Ty(), llvm::Type::isVectorTy(), llvm::TargetTransformInfo::SK_Broadcast, and llvm::TargetTransformInfo::SK_ExtractSubvector.
getUnrollingPreferences()
void SystemZTTIImpl::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP)
Definition at line 240 of file SystemZTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::UnrollingPreferences::AllowExpensiveTripCount, llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::TargetTransformInfo::UnrollingPreferences::DefaultUnrollRuntimeCount, F, llvm::TargetTransformInfo::UnrollingPreferences::Force, llvm::TargetTransformInfo::UnrollingPreferences::FullUnrollMaxCount, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), getMemoryOpCost(), I, llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::TargetTransformInfo::UnrollingPreferences::MaxCount, llvm::TargetTransformInfo::UnrollingPreferences::Partial, llvm::TargetTransformInfo::UnrollingPreferences::PartialThreshold, and llvm::TargetTransformInfo::UnrollingPreferences::Runtime.
getVectorBitmaskConversionCost()
unsigned SystemZTTIImpl::getVectorBitmaskConversionCost (Type * SrcTy, Type * DstTy)
Definition at line 602 of file SystemZTargetTransformInfo.cpp.
References assert(), getElSizeLog2Diff(), getNumVectorRegs(), llvm::Type::getScalarSizeInBits(), getVectorTruncCost(), and llvm::Type::isVectorTy().
Referenced by getBoolVecToIntConversionCost(), and getCmpSelInstrCost().
getVectorInstrCost()
int SystemZTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Definition at line 887 of file SystemZTargetTransformInfo.cpp.
References getScalarSizeInBits(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getVectorInstrCost(), and llvm::Type::isIntOrIntVectorTy().
getVectorTruncCost()
unsigned SystemZTTIImpl::getVectorTruncCost (Type * SrcTy, Type * DstTy)
Definition at line 562 of file SystemZTargetTransformInfo.cpp.
References assert(), getElSizeLog2Diff(), getNumVectorRegs(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), and P.
Referenced by getCastInstrCost(), and getVectorBitmaskConversionCost().
hasDivRemOp()
bool SystemZTTIImpl::hasDivRemOp (Type * DataType, bool IsSigned)
Definition at line 325 of file SystemZTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::DL, llvm::TargetLoweringBase::getValueType(), llvm::EVT::isScalarInteger(), and llvm::TargetLoweringBase::isTypeLegal().
isFoldableLoad()
bool SystemZTTIImpl::isFoldableLoad (const LoadInst * Ld, const Instruction *& FoldedValue)
Definition at line 908 of file SystemZTargetTransformInfo.cpp.
References llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), getScalarSizeInBits(), llvm::Value::getType(), llvm::SystemZSubtarget::hasMiscellaneousExtensions2(), llvm::Value::hasOneUse(), llvm::isUInt< 16 >(), LLVM_FALLTHROUGH, llvm::MCBinaryExpr::Mul, llvm::AtomicRMWInst::Sub, llvm::Value::user_begin(), and llvm::AtomicRMWInst::Xor.
Referenced by getMemoryOpCost().
isLSRCostLess()
bool SystemZTTIImpl::isLSRCostLess (TargetTransformInfo::LSRCost & C1, TargetTransformInfo::LSRCost & C2)
Definition at line 295 of file SystemZTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::Insns, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
LSRWithInstrQueries()
bool llvm::SystemZTTIImpl::LSRWithInstrQueries () inline
Definition at line 68 of file SystemZTargetTransformInfo.h.
prefersVectorizedAddressing()
bool llvm::SystemZTTIImpl::prefersVectorizedAddressing () inline
Definition at line 67 of file SystemZTargetTransformInfo.h.
supportsEfficientVectorElementLoadStore()
bool llvm::SystemZTTIImpl::supportsEfficientVectorElementLoadStore () inline
Definition at line 69 of file SystemZTargetTransformInfo.h.
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZTargetTransformInfo.h
lib/Target/SystemZ/SystemZTargetTransformInfo.cpp