LLVM: llvm::mca::EntryStage Class Reference
llvm::mca::EntryStage Class Reference final
#include "llvm/MCA/Stages/EntryStage.h"
Public Member Functions
EntryStage (SourceMgr &SM)
bool isAvailable (const InstRef &IR) const override
Returns true if it can execute IR during this cycle.
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
Error cycleStart () override
Called once at the start of each cycle.
Error cycleEnd () override
Called once at the end of each cycle.
Public Member Functions inherited from llvm::mca::Stage
Stage ()
virtual ~Stage ()
virtual bool isAvailable (const InstRef &IR) const
Returns true if it can execute IR during this cycle.
virtual bool hasWorkToComplete () const =0
Returns true if some instructions are still executing this stage.
virtual Error cycleStart ()
Called once at the start of each cycle.
virtual Error cycleEnd ()
Called once at the end of each cycle.
virtual Error execute (InstRef &IR)=0
The primary action that this stage performs on instruction IR.
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 26 of file EntryStage.h.
Constructor & Destructor Documentation
EntryStage()
llvm::mca::EntryStage::EntryStage (SourceMgr & SM) inline
Definition at line 39 of file EntryStage.h.
Member Function Documentation
cycleEnd()
llvm::Error llvm::mca::EntryStage::cycleEnd () override virtual
Called once at the end of each cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 59 of file EntryStage.cpp.
References llvm::find_if(), I, and llvm::make_range().
cycleStart()
llvm::Error llvm::mca::EntryStage::cycleStart () override virtual
Called once at the start of each cycle.
This can be used as a setup phase to prepare for the executions during the cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 53 of file EntryStage.cpp.
execute()
llvm::Error llvm::mca::EntryStage::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 42 of file EntryStage.cpp.
References assert(), llvm::mca::InstRef::invalidate(), and llvm::mca::Stage::moveToTheNextStage().
hasWorkToComplete()
bool llvm::mca::EntryStage::hasWorkToComplete () const override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 21 of file EntryStage.cpp.
isAvailable()
bool llvm::mca::EntryStage::isAvailable (const InstRef & IR) const override virtual
Returns true if it can execute IR during this cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 25 of file EntryStage.cpp.
References llvm::mca::Stage::checkNextStage().
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/EntryStage.h
lib/MCA/Stages/EntryStage.cpp