LLVM: llvm::RegionInfoBase< Tr > Class Template Reference
llvm::RegionInfoBase< Tr > Class Template Reference abstract
Analysis that detects all canonical Regions.
#include "llvm/Analysis/RegionInfo.h"
Public Member Functions
RegionInfoBase (const RegionInfoBase &)=delete
RegionInfoBase & operator= (const RegionInfoBase &)=delete
void print (raw_ostream &OS) const
void dump () const
void releaseMemory ()
RegionT * getRegionFor (BlockT *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BlockT *BB, RegionT *R)
Set the smallest region that surrounds a basic block.
RegionT * operator[] (BlockT *BB) const
A shortcut for getRegionFor().
BlockT * getMaxRegionExit (BlockT *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
RegionT * getCommonRegion (RegionT *A, RegionT *B) const
Find the smallest region that contains two regions.
RegionT * getCommonRegion (BlockT *A, BlockT *B) const
Find the smallest region that contains two basic blocks.
RegionT * getCommonRegion (SmallVectorImpl< RegionT * > &Regions) const
Find the smallest region that contains a set of regions.
RegionT * getCommonRegion (SmallVectorImpl< BlockT * > &BBs) const
Find the smallest region that contains a set of basic blocks.
RegionT * getTopLevelRegion () const
void clearNodeCache ()
Clear the Node Cache for all Regions.
void verifyAnalysis () const
Static Public Attributes
static bool VerifyRegionInfo = false
static RegionT::PrintStyle printStyle
Protected Member Functions
template<typename TheRegionT >
void updateRegionTree (RegionInfoT &RI, TheRegionT *R)
Update refences to a RegionInfoT held by the RegionT managed here.
Friends
class RegionInfo
class MachineRegionInfo
Detailed Description
template<class Tr>
class llvm::RegionInfoBase< Tr >
Analysis that detects all canonical Regions.
The RegionInfo pass detects all canonical regions in a function. The Regions are connected using the parent relation. This builds a Program Structure Tree.
Definition at line 676 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionInfoBase()
template<class Tr > llvm::RegionInfoBase< Tr >::RegionInfoBase (const RegionInfoBase< Tr > &) delete
Member Function Documentation
clearNodeCache()
template<class Tr > void llvm::RegionInfoBase< Tr >::clearNodeCache () inline
Clear the Node Cache for all Regions.
See also
Region::clearNodeCache()
Definition at line 873 of file RegionInfo.h.
Referenced by llvm::RGPassManager::runOnFunction().
dump()
template<class Tr > void llvm::RegionInfoBase< Tr >::dump
Definition at line 794 of file RegionInfoImpl.h.
References llvm::dbgs(), and print().
Referenced by llvm::RegionInfoPass::dump(), llvm::MachineRegionInfoPass::dump(), llvm::RGPassManager::runOnFunction(), and llvm::MachineRegionInfoPass::runOnMachineFunction().
getCommonRegion() [1/4]
template<class Tr > RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (BlockT * A, BlockT * B) const inline
Find the smallest region that contains two basic blocks.
Parameters
A The first basic block.
B The second basic block.
Returns
The smallest region that contains A and B.
Definition at line 852 of file RegionInfo.h.
References A, B, llvm::RegionInfoBase< Tr >::getCommonRegion(), and llvm::RegionInfoBase< Tr >::getRegionFor().
getCommonRegion() [2/4]
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (RegionT * A, RegionT * B) const
Find the smallest region that contains two regions.
Parameters
A The first region.
B The second region.
Returns
The smallest region containing A and B.
Definition at line 876 of file RegionInfoImpl.h.
Referenced by llvm::RegionInfoBase< Tr >::getCommonRegion().
getCommonRegion() [3/4]
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (SmallVectorImpl< BlockT * > & BBs) const
Find the smallest region that contains a set of basic blocks.
Parameters
BBs A vector of basic blocks.
Returns
The smallest region that contains all basic blocks in BBS.
Definition at line 903 of file RegionInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
getCommonRegion() [4/4]
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (SmallVectorImpl< RegionT * > & Regions) const
Find the smallest region that contains a set of regions.
Parameters
Regions A vector of regions.
Returns
The smallest region that contains all regions in Regions.
Definition at line 891 of file RegionInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
getMaxRegionExit()
template<class Tr > RegionInfoBase< Tr >::BlockT * llvm::RegionInfoBase< Tr >::getMaxRegionExit (BlockT * BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
Parameters
BB The BasicBlock the refined region starts.
Definition at line 836 of file RegionInfoImpl.h.
getRegionFor()
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getRegionFor (BlockT * BB) const
Get the smallest region that contains a BasicBlock.
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 819 of file RegionInfoImpl.h.
References I.
Referenced by llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), and sortBlocks().
getTopLevelRegion()
template<class Tr > RegionT * llvm::RegionInfoBase< Tr >::getTopLevelRegion () const inline
Definition at line 868 of file RegionInfo.h.
Referenced by llvm::GraphTraits< MachineRegionInfo * >::getEntryNode(), llvm::GraphTraits< RegionInfo * >::getEntryNode(), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), llvm::RGPassManager::runOnFunction(), and viewRegionInfo().
operator=()
template<class Tr > RegionInfoBase & llvm::RegionInfoBase< Tr >::operator= (const RegionInfoBase< Tr > &) delete
operator[]()
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::operator[] (BlockT * BB) const
A shortcut for getRegionFor().
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 830 of file RegionInfoImpl.h.
print()
template<class Tr > void llvm::RegionInfoBase< Tr >::print (raw_ostream & OS) const
Definition at line 786 of file RegionInfoImpl.h.
Referenced by llvm::RegionInfoPass::print(), and llvm::MachineRegionInfoPass::print().
releaseMemory()
template<class Tr > void llvm::RegionInfoBase< Tr >::releaseMemory
Definition at line 798 of file RegionInfoImpl.h.
Referenced by llvm::RegionInfoPass::releaseMemory(), and llvm::MachineRegionInfoPass::releaseMemory().
setRegionFor()
template<class Tr > void llvm::RegionInfoBase< Tr >::setRegionFor (BlockT * BB, RegionT * R)
Set the smallest region that surrounds a basic block.
Parameters
BB The basic block surrounded by a region.
R The smallest region that surrounds BB.
Definition at line 825 of file RegionInfoImpl.h.
updateRegionTree()
template<class Tr > template<typename TheRegionT > void llvm::RegionInfoBase< Tr >::updateRegionTree (RegionInfoT & RI, TheRegionT * R) inline protected
Update refences to a RegionInfoT held by the RegionT managed here.
This is a post-move helper. Regions hold references to the owning RegionInfo object. After a move these need to be fixed.
Definition at line 733 of file RegionInfo.h.
References llvm::RegionInfoBase< Tr >::updateRegionTree().
Referenced by llvm::RegionInfoBase< Tr >::updateRegionTree().
verifyAnalysis()
template<class Tr > void llvm::RegionInfoBase< Tr >::verifyAnalysis
Definition at line 806 of file RegionInfoImpl.h.
Referenced by llvm::RegionInfoPass::verifyAnalysis(), and llvm::MachineRegionInfoPass::verifyAnalysis().
Friends And Related Function Documentation
MachineRegionInfo
template<class Tr > friend class MachineRegionInfo friend
Definition at line 678 of file RegionInfo.h.
RegionInfo
template<class Tr > friend class RegionInfo friend
Definition at line 677 of file RegionInfo.h.
Member Data Documentation
printStyle
template<class Tr > Tr::RegionT::PrintStyle llvm::RegionInfoBase< Tr >::printStyle static
Initial value:
=
    RegionBase<Tr>::PrintNone
Definition at line 805 of file RegionInfo.h.
VerifyRegionInfo
template<class Tr > bool llvm::RegionInfoBase< Tr >::VerifyRegionInfo = false static
Definition at line 804 of file RegionInfo.h.
Referenced by llvm::MachineRegionInfoPass::verifyAnalysis().
The documentation for this class was generated from the following files:
include/llvm/Analysis/RegionInfo.h
include/llvm/Analysis/RegionInfoImpl.h