LLVM: llvm::PostGenericScheduler Class Reference
llvm::PostGenericScheduler Class Reference
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
#include "llvm/CodeGen/MachineScheduler.h"
Public Member Functions
PostGenericScheduler (const MachineSchedContext *C)
~PostGenericScheduler () override=default
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Optionally override the per-region scheduling policy.
bool shouldTrackPressure () const override
PostRA scheduling does not track pressure.
void initialize (ScheduleDAGMI *Dag) override
Initialize the strategy after building the DAG for a new region.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
SUnit * pickNode (bool &IsTopNode) override
Pick the next node to schedule.
void scheduleTree (unsigned SubtreeID) override
Scheduler callback to notify that a new subtree is scheduled.
void schedNode (SUnit *SU, bool IsTopNode) override
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual SUnit * pickNode (bool &IsTopNode)=0
Pick the next node to schedule, or return NULL.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
virtual void releaseTopNode (SUnit *SU)=0
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
virtual void releaseBottomNode (SUnit *SU)=0
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Protected Member Functions
void tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand)
Apply a set of heuristics to a new candidate for PostRA scheduling.
void pickNodeFromQueue (SchedCandidate &Cand)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
ScheduleDAGMI * DAG
SchedBoundary Top
SmallVector< SUnit *, 8 > BotRoots
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
SchedRemainder Rem
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NextDefUse ,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Detailed Description
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
Callbacks from ScheduleDAGMI: initPolicy -> initialize(DAG) -> registerRoots -> pickNode ...
Definition at line 1009 of file MachineScheduler.h.
Constructor & Destructor Documentation
PostGenericScheduler()
llvm::PostGenericScheduler::PostGenericScheduler (const MachineSchedContext * C) inline
Definition at line 1016 of file MachineScheduler.h.
~PostGenericScheduler()
llvm::PostGenericScheduler::~PostGenericScheduler () override default
Member Function Documentation
initialize()
void PostGenericScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 3323 of file MachineScheduler.cpp.
References BotRoots, llvm::TargetInstrInfo::CreateTargetMIHazardRecognizer(), DAG, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSchedModel::getInstrItineraries(), llvm::ScheduleDAGInstrs::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::SchedBoundary::HazardRec, llvm::SchedRemainder::init(), llvm::SchedBoundary::init(), llvm::ScheduleDAG::MF, llvm::GenericSchedulerBase::Rem, llvm::GenericSchedulerBase::SchedModel, Top, llvm::GenericSchedulerBase::TRI, and llvm::ScheduleDAG::TRI.
initPolicy()
void llvm::PostGenericScheduler::initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) inline override virtual
Optionally override the per-region scheduling policy.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1021 of file MachineScheduler.h.
pickNode()
SUnit * PostGenericScheduler::pickNode (bool & IsTopNode) override virtual
Pick the next node to schedule.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 3414 of file MachineScheduler.cpp.
References assert(), llvm::SchedBoundary::Available, llvm::ScheduleDAGMI::bottom(), DAG, llvm::dbgs(), llvm::ReadyQueue::empty(), llvm::SUnit::getInstr(), llvm::SUnit::isScheduled, LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::Only1, llvm::SchedBoundary::Pending, pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::SchedBoundary::removeReady(), llvm::GenericSchedulerBase::setPolicy(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::ScheduleDAGMI::top(), Top, and tracePick().
pickNodeFromQueue()
void PostGenericScheduler::pickNodeFromQueue (SchedCandidate & Cand) protected
Definition at line 3398 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::SchedBoundary::Available, DAG, llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::SchedCandidate::SU, Top, llvm::GenericSchedulerBase::traceCandidate(), and tryCandidate().
Referenced by pickNode().
registerRoots()
void PostGenericScheduler::registerRoots () override virtual
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 3342 of file MachineScheduler.cpp.
References BotRoots, llvm::SchedRemainder::CriticalPath, DAG, llvm::dbgs(), llvm::DumpCriticalPathLength, llvm::errs(), llvm::ScheduleDAG::ExitSU, llvm::SUnit::getDepth(), LLVM_DEBUG, and llvm::GenericSchedulerBase::Rem.
releaseBottomNode()
void llvm::PostGenericScheduler::releaseBottomNode (SUnit * SU) inline override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1049 of file MachineScheduler.h.
References BotRoots.
releaseTopNode()
void llvm::PostGenericScheduler::releaseTopNode (SUnit * SU) inline override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1042 of file MachineScheduler.h.
References llvm::SUnit::isScheduled, llvm::SchedBoundary::releaseNode(), Top, and llvm::SUnit::TopReadyCycle.
schedNode()
void PostGenericScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 3447 of file MachineScheduler.cpp.
References llvm::SchedBoundary::bumpNode(), llvm::SchedBoundary::getCurrCycle(), Top, and llvm::SUnit::TopReadyCycle.
scheduleTree()
void llvm::PostGenericScheduler::scheduleTree (unsigned SubtreeID) inline override virtual
Scheduler callback to notify that a new subtree is scheduled.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1036 of file MachineScheduler.h.
References llvm_unreachable.
shouldTrackPressure()
bool llvm::PostGenericScheduler::shouldTrackPressure () const inline override virtual
PostRA scheduling does not track pressure.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1028 of file MachineScheduler.h.
tryCandidate()
void PostGenericScheduler::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand) protected
Apply a set of heuristics to a new candidate for PostRA scheduling.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Definition at line 3360 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::Cluster, llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, DAG, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::SchedBoundary::getLatencyStallCycles(), llvm::ScheduleDAGMI::getNextClusterSucc(), llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, Top, llvm::tryGreater(), llvm::tryLatency(), and llvm::tryLess().
Referenced by pickNodeFromQueue().
Member Data Documentation
BotRoots
SmallVector<SUnit*, 8> llvm::PostGenericScheduler::BotRoots protected
Definition at line 1013 of file MachineScheduler.h.
Referenced by initialize(), registerRoots(), and releaseBottomNode().
DAG
ScheduleDAGMI* llvm::PostGenericScheduler::DAG protected
Definition at line 1011 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeFromQueue(), registerRoots(), and tryCandidate().
Top
SchedBoundary llvm::PostGenericScheduler::Top protected
Definition at line 1012 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeFromQueue(), releaseTopNode(), schedNode(), and tryCandidate().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp