LLVM: llvm::BitstreamCursor Class Reference
llvm::BitstreamCursor Class Reference
This represents a position within a bitcode file, implemented on top of a SimpleBitstreamCursor.
#include "llvm/Bitstream/BitstreamReader.h"
Public Types
enum { AF_DontPopBlockAtEnd = 1 , AF_DontAutoprocessAbbrevs = 2 }
Flags that modify the behavior of advance().
Public Member Functions
BitstreamCursor ()=default
BitstreamCursor (ArrayRef< uint8_t > BitcodeBytes)
BitstreamCursor (StringRef BitcodeBytes)
BitstreamCursor (MemoryBufferRef BitcodeBytes)
unsigned getAbbrevIDWidth () const
Return the number of bits used to encode an abbrev #.
Expected< BitstreamEntry > advance (unsigned Flags=0)
Advance the current bitstream, returning the next entry in the stream.
Expected< BitstreamEntry > advanceSkippingSubblocks (unsigned Flags=0)
This is a convenience function for clients that don't expect any subblocks.
Expected< unsigned > ReadCode ()
Expected< unsigned > ReadSubBlockID ()
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
Error SkipBlock ()
Having read the ENTER_SUBBLOCK abbrevid and a BlockID, skip over the body of this block.
Error EnterSubBlock (unsigned BlockID, unsigned *NumWordsP=nullptr)
Having read the ENTER_SUBBLOCK abbrevid, and enter the block.
bool ReadBlockEnd ()
const BitCodeAbbrev * getAbbrev (unsigned AbbrevID)
Return the abbreviation for the specified AbbrevId.
Expected< unsigned > skipRecord (unsigned AbbrevID)
Read the current record and discard it, returning the code for the record.
Expected< unsigned > readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > &Vals, StringRef *Blob=nullptr)
Error ReadAbbrevRecord ()
Expected< Optional< BitstreamBlockInfo > > ReadBlockInfoBlock (bool ReadBlockInfoNames=false)
Read and return a block info block from the bitstream.
void setBlockInfo (BitstreamBlockInfo *BI)
Set the block info to be used by this BitstreamCursor to interpret abbreviated records.
bool AtEndOfStream ()
bool canSkipToPos (size_t pos) const
Error fillCurWord ()
ArrayRef< uint8_t > getBitcodeBytes () const
uint64_t GetCurrentBitNo () const
Return the bit # of the bit we are reading.
uint64_t getCurrentByteNo () const
const uint8_t * getPointerToByte (uint64_t ByteNo, uint64_t NumBytes)
Get a pointer into the bitstream at the specified byte offset.
Error JumpToBit (uint64_t BitNo)
Reset the stream to the specified bit number.
Expected< word_t > Read (unsigned NumBits)
Expected< uint32_t > ReadVBR (unsigned NumBits)
Expected< uint64_t > ReadVBR64 (unsigned NumBits)
size_t SizeInBytes () const
Return the size of the stream in bytes.
Static Public Attributes
static const size_t MaxChunkSize = sizeof(word_t) * 8
Detailed Description
This represents a position within a bitcode file, implemented on top of a SimpleBitstreamCursor.
Unlike iterators, BitstreamCursors are heavy-weight objects that should not be passed by value.
Definition at line 339 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Flags that modify the behavior of advance().
Enumerator
AF_DontPopBlockAtEnd
If this flag is used, the advance() method does not automatically pop the block scope when the end of a block is reached.
AF_DontAutoprocessAbbrevs
If this flag is used, abbrev entries are returned just like normal records.
Definition at line 387 of file BitstreamReader.h.
Constructor & Destructor Documentation
BitstreamCursor() [1/4]
llvm::BitstreamCursor::BitstreamCursor () default
BitstreamCursor() [2/4]
llvm::BitstreamCursor::BitstreamCursor (ArrayRef< uint8_t > BitcodeBytes) inline explicit
Definition at line 363 of file BitstreamReader.h.
BitstreamCursor() [3/4]
llvm::BitstreamCursor::BitstreamCursor (StringRef BitcodeBytes) inline explicit
Definition at line 365 of file BitstreamReader.h.
BitstreamCursor() [4/4]
llvm::BitstreamCursor::BitstreamCursor (MemoryBufferRef BitcodeBytes) inline explicit
Definition at line 367 of file BitstreamReader.h.
Member Function Documentation
advance()
Expected< BitstreamEntry > llvm::BitstreamCursor::advance (unsigned Flags = 0) inline
Advance the current bitstream, returning the next entry in the stream.
Definition at line 398 of file BitstreamReader.h.
References AF_DontAutoprocessAbbrevs, AF_DontPopBlockAtEnd, AtEndOfStream(), llvm::bitc::DEFINE_ABBREV, llvm::bitc::END_BLOCK, llvm::bitc::ENTER_SUBBLOCK, llvm::Expected< T >::get(), llvm::BitstreamEntry::getEndBlock(), llvm::BitstreamEntry::getError(), llvm::pdb::TagRecordHash::getRecord(), llvm::BitstreamEntry::getSubBlock(), ReadAbbrevRecord(), ReadBlockEnd(), ReadCode(), ReadSubBlockID(), and llvm::Expected< T >::takeError().
Referenced by advanceSkippingSubblocks(), llvm::getBitcodeFileContents(), llvm::BitcodeModule::getLTOInfo(), hasObjCCategory(), jumpToValueSymbolTable(), readBlobInRecord(), readIdentificationBlock(), readIdentificationCode(), and readTriple().
advanceSkippingSubblocks()
Expected< BitstreamEntry > llvm::BitstreamCursor::advanceSkippingSubblocks (unsigned Flags = 0) inline
This is a convenience function for clients that don't expect any subblocks.
This just skips over them automatically.
Definition at line 437 of file BitstreamReader.h.
References advance(), llvm::Expected< T >::get(), SkipBlock(), and llvm::BitstreamEntry::SubBlock.
Referenced by getEnableSplitLTOUnitFlag(), hasObjCCategoryInModule(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), ReadBlockInfoBlock(), and readModuleTriple().
AtEndOfStream()
bool llvm::SimpleBitstreamCursor::AtEndOfStream () inline
Definition at line 115 of file BitstreamReader.h.
Referenced by advance(), llvm::BitcodeAnalyzer::analyze(), EnterSubBlock(), readIdentificationCode(), and SkipBlock().
canSkipToPos()
bool llvm::SimpleBitstreamCursor::canSkipToPos (size_t pos) const inline
Definition at line 110 of file BitstreamReader.h.
Referenced by hasInvalidBitcodeHeader(), readRecord(), SkipBlock(), and skipRecord().
EnterSubBlock()
Error BitstreamCursor::EnterSubBlock (unsigned BlockID, unsigned * NumWordsP = nullptr)
Having read the ENTER_SUBBLOCK abbrevid, and enter the block.
Having read the ENTER_SUBBLOCK abbrevid, enter the block.
Definition at line 21 of file BitstreamReader.cpp.
References AtEndOfStream(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::bitc::BlockSizeWidth, llvm::bitc::CodeLenWidth, llvm::createStringError(), llvm::Expected< T >::get(), llvm::BitstreamBlockInfo::getBlockInfo(), Info, MaxChunkSize, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Read(), ReadVBR(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by getEnableSplitLTOUnitFlag(), llvm::BitcodeModule::getLTOInfo(), hasObjCCategoryInModule(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), readBlobInRecord(), ReadBlockInfoBlock(), readIdentificationBlock(), and readModuleTriple().
fillCurWord()
Error llvm::SimpleBitstreamCursor::fillCurWord () inline
Definition at line 163 of file BitstreamReader.h.
getAbbrev()
const BitCodeAbbrev * llvm::BitstreamCursor::getAbbrev (unsigned AbbrevID) inline
Return the abbreviation for the specified AbbrevId.
Definition at line 523 of file BitstreamReader.h.
References llvm::bitc::FIRST_APPLICATION_ABBREV, and llvm::report_fatal_error().
Referenced by readRecord(), and skipRecord().
getAbbrevIDWidth()
unsigned llvm::BitstreamCursor::getAbbrevIDWidth () const inline
Return the number of bits used to encode an abbrev #.
Definition at line 384 of file BitstreamReader.h.
getBitcodeBytes()
ArrayRef< uint8_t > llvm::SimpleBitstreamCursor::getBitcodeBytes () const inline
Definition at line 127 of file BitstreamReader.h.
Referenced by analyzeHeader(), llvm::getBitcodeFileContents(), and llvm::BitcodeAnalyzer::printStats().
GetCurrentBitNo()
uint64_t llvm::SimpleBitstreamCursor::GetCurrentBitNo () const inline
Return the bit # of the bit we are reading.
Definition at line 120 of file BitstreamReader.h.
Referenced by llvm::getBitcodeFileContents(), jumpToValueSymbolTable(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), readRecord(), SkipBlock(), and skipRecord().
getCurrentByteNo()
uint64_t llvm::SimpleBitstreamCursor::getCurrentByteNo () const inline
Definition at line 125 of file BitstreamReader.h.
Referenced by llvm::getBitcodeFileContents().
getPointerToByte()
const uint8_t * llvm::SimpleBitstreamCursor::getPointerToByte (uint64_t ByteNo, uint64_t NumBytes) inline
Get a pointer into the bitstream at the specified byte offset.
Definition at line 151 of file BitstreamReader.h.
JumpToBit()
Error llvm::SimpleBitstreamCursor::JumpToBit (uint64_t BitNo) inline
Reset the stream to the specified bit number.
Definition at line 130 of file BitstreamReader.h.
Referenced by llvm::BitcodeModule::getLTOInfo(), llvm::BitcodeModule::getSummary(), jumpToValueSymbolTable(), readRecord(), llvm::BitcodeModule::readSummary(), SkipBlock(), and skipRecord().
Read()
Expected< word_t > llvm::SimpleBitstreamCursor::Read (unsigned NumBits) inline
Definition at line 189 of file BitstreamReader.h.
Referenced by EnterSubBlock(), hasInvalidBitcodeHeader(), readAbbreviatedField(), ReadAbbrevRecord(), ReadCode(), readRecord(), ReadSignature(), skipAbbreviatedField(), and SkipBlock().
ReadAbbrevRecord()
Error BitstreamCursor::ReadAbbrevRecord ()
Definition at line 375 of file BitstreamReader.cpp.
References llvm::Data, E, llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), llvm::BitCodeAbbrevOp::hasEncodingData(), MaxChunkSize, Read(), ReadVBR(), ReadVBR64(), llvm::report_fatal_error(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::BitCodeAbbrevOp::VBR.
Referenced by advance(), and ReadBlockInfoBlock().
ReadBlockEnd()
bool llvm::BitstreamCursor::ReadBlockEnd () inline
Definition at line 498 of file BitstreamReader.h.
References llvm::SmallVectorBase::empty(), and llvm::SimpleBitstreamCursor::SkipToFourByteBoundary().
Referenced by advance(), and llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata().
ReadBlockInfoBlock()
Expected< Optional< BitstreamBlockInfo > > BitstreamCursor::ReadBlockInfoBlock (bool ReadBlockInfoNames = false)
Read and return a block info block from the bitstream.
If an error was encountered, return None.
Parameters
ReadBlockInfoNames Whether to read block/record name information in the BlockInfo block. Only llvm-bcanalyzer uses this.
Definition at line 432 of file BitstreamReader.cpp.
References llvm::BitstreamBlockInfo::BlockInfo::Abbrevs, advanceSkippingSubblocks(), AF_DontAutoprocessAbbrevs, llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::bitc::BLOCKINFO_CODE_BLOCKNAME, llvm::bitc::BLOCKINFO_CODE_SETBID, llvm::bitc::BLOCKINFO_CODE_SETRECORDNAME, llvm::bitc::DEFINE_ABBREV, llvm::BitstreamEntry::EndBlock, EnterSubBlock(), llvm::BitstreamEntry::Error, llvm::Expected< T >::get(), llvm::BitstreamBlockInfo::getOrCreateBlockInfo(), llvm::BitstreamBlockInfo::BlockInfo::Name, Name, llvm::None, ReadAbbrevRecord(), readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamBlockInfo::BlockInfo::RecordNames, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::BitcodeAnalyzer::analyze().
ReadCode()
Expected< unsigned > llvm::BitstreamCursor::ReadCode () inline
Definition at line 454 of file BitstreamReader.h.
References Read().
Referenced by advance(), and llvm::BitcodeAnalyzer::analyze().
readRecord()
Expected< unsigned > BitstreamCursor::readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > & Vals, StringRef * Blob = nullptr)
Definition at line 235 of file BitstreamReader.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::BitCodeAbbrevOp::Blob, canSkipToPos(), llvm::BitCodeAbbrevOp::Char6, llvm::BitCodeAbbrevOp::DecodeChar6(), llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), getAbbrev(), GetCurrentBitNo(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::SimpleBitstreamCursor::getPointerToBit(), llvm::BitCodeAbbrevOp::isEncoding(), llvm::BitCodeAbbrevOp::isLiteral(), JumpToBit(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Read(), readAbbreviatedField(), ReadVBR(), ReadVBR64(), llvm::report_fatal_error(), llvm::SimpleBitstreamCursor::skipToEnd(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Expected< T >::takeError(), llvm::bitc::UNABBREV_RECORD, and llvm::BitCodeAbbrevOp::VBR.
Referenced by getEnableSplitLTOUnitFlag(), hasObjCCategoryInModule(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), readBlobInRecord(), ReadBlockInfoBlock(), readIdentificationBlock(), and readModuleTriple().
ReadSubBlockID()
Expected< unsigned > llvm::BitstreamCursor::ReadSubBlockID () inline
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
Definition at line 460 of file BitstreamReader.h.
References llvm::bitc::BlockIDWidth, and ReadVBR().
Referenced by advance(), and llvm::BitcodeAnalyzer::analyze().
ReadVBR()
Expected< uint32_t > llvm::SimpleBitstreamCursor::ReadVBR (unsigned NumBits) inline
Definition at line 232 of file BitstreamReader.h.
Referenced by EnterSubBlock(), ReadAbbrevRecord(), readRecord(), ReadSubBlockID(), SkipBlock(), and skipRecord().
ReadVBR64()
Expected< uint64_t > llvm::SimpleBitstreamCursor::ReadVBR64 (unsigned NumBits) inline
Definition at line 259 of file BitstreamReader.h.
Referenced by readAbbreviatedField(), ReadAbbrevRecord(), readRecord(), skipAbbreviatedField(), and skipRecord().
setBlockInfo()
void llvm::BitstreamCursor::setBlockInfo (BitstreamBlockInfo * BI) inline
Set the block info to be used by this BitstreamCursor to interpret abbreviated records.
Definition at line 552 of file BitstreamReader.h.
Referenced by llvm::BitcodeAnalyzer::analyze().
SizeInBytes()
size_t llvm::SimpleBitstreamCursor::SizeInBytes () const inline
Return the size of the stream in bytes.
Definition at line 298 of file BitstreamReader.h.
SkipBlock()
Error llvm::BitstreamCursor::SkipBlock () inline
Having read the ENTER_SUBBLOCK abbrevid and a BlockID, skip over the body of this block.
Definition at line 464 of file BitstreamReader.h.
References AtEndOfStream(), llvm::bitc::BlockSizeWidth, canSkipToPos(), llvm::bitc::CodeLenWidth, llvm::createStringError(), llvm::Expected< T >::get(), GetCurrentBitNo(), JumpToBit(), Read(), ReadVBR(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by advanceSkippingSubblocks(), llvm::BitcodeAnalyzer::analyze(), llvm::getBitcodeFileContents(), llvm::BitcodeModule::getLTOInfo(), hasObjCCategory(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), readBlobInRecord(), readIdentificationCode(), and readTriple().
skipRecord()
Expected< unsigned > BitstreamCursor::skipRecord (unsigned AbbrevID)
Read the current record and discard it, returning the code for the record.
skipRecord - Read the current record and discard it.
Definition at line 123 of file BitstreamReader.cpp.
References assert(), llvm::BitCodeAbbrevOp::Blob, canSkipToPos(), llvm::BitCodeAbbrevOp::Char6, llvm::createStringError(), llvm::BitCodeAbbrevOp::Fixed, llvm::Expected< T >::get(), getAbbrev(), GetCurrentBitNo(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::BitCodeAbbrevOp::isLiteral(), JumpToBit(), MaxChunkSize, readAbbreviatedField(), ReadVBR(), ReadVBR64(), llvm::report_fatal_error(), skipAbbreviatedField(), llvm::SimpleBitstreamCursor::skipToEnd(), llvm::SimpleBitstreamCursor::SkipToFourByteBoundary(), llvm::Expected< T >::takeError(), llvm::bitc::UNABBREV_RECORD, and llvm::BitCodeAbbrevOp::VBR.
Referenced by llvm::getBitcodeFileContents(), llvm::BitcodeModule::getLTOInfo(), hasObjCCategory(), readIdentificationCode(), and readTriple().
Member Data Documentation
MaxChunkSize
const size_t llvm::BitstreamCursor::MaxChunkSize = sizeof(word_t) * 8 static
Definition at line 360 of file BitstreamReader.h.
Referenced by EnterSubBlock(), readAbbreviatedField(), ReadAbbrevRecord(), skipAbbreviatedField(), and skipRecord().
The documentation for this class was generated from the following files:
include/llvm/Bitstream/BitstreamReader.h
lib/Bitstream/Reader/BitstreamReader.cpp