LLVM: llvm::DWARFObject Class Reference
llvm::DWARFObject Class Reference abstract
#include "llvm/DebugInfo/DWARF/DWARFObject.h"
Public Member Functions
virtual ~DWARFObject ()=default
virtual StringRef getFileName () const
virtual const object::ObjectFile * getFile () const
virtual ArrayRef< SectionName > getSectionNames () const
virtual bool isLittleEndian () const =0
virtual uint8_t getAddressSize () const
virtual void forEachInfoSections (function_ref< void(const DWARFSection &)> F) const
virtual void forEachTypesSections (function_ref< void(const DWARFSection &)> F) const
virtual StringRef getAbbrevSection () const
virtual const DWARFSection & getLocSection () const
virtual const DWARFSection & getLoclistsSection () const
virtual StringRef getARangeSection () const
virtual StringRef getDebugFrameSection () const
virtual StringRef getEHFrameSection () const
virtual const DWARFSection & getLineSection () const
virtual StringRef getLineStringSection () const
virtual StringRef getStringSection () const
virtual const DWARFSection & getRangeSection () const
virtual const DWARFSection & getRnglistsSection () const
virtual StringRef getMacinfoSection () const
virtual const DWARFSection & getPubNamesSection () const
virtual const DWARFSection & getPubTypesSection () const
virtual const DWARFSection & getGnuPubNamesSection () const
virtual const DWARFSection & getGnuPubTypesSection () const
virtual const DWARFSection & getStringOffsetSection () const
virtual void forEachInfoDWOSections (function_ref< void(const DWARFSection &)> F) const
virtual void forEachTypesDWOSections (function_ref< void(const DWARFSection &)> F) const
virtual StringRef getAbbrevDWOSection () const
virtual const DWARFSection & getLineDWOSection () const
virtual const DWARFSection & getLocDWOSection () const
virtual StringRef getStringDWOSection () const
virtual const DWARFSection & getStringOffsetDWOSection () const
virtual const DWARFSection & getRangeDWOSection () const
virtual const DWARFSection & getRnglistsDWOSection () const
virtual const DWARFSection & getAddrSection () const
virtual const DWARFSection & getAppleNamesSection () const
virtual const DWARFSection & getAppleTypesSection () const
virtual const DWARFSection & getAppleNamespacesSection () const
virtual const DWARFSection & getDebugNamesSection () const
virtual const DWARFSection & getAppleObjCSection () const
virtual StringRef getCUIndexSection () const
virtual StringRef getGdbIndexSection () const
virtual StringRef getTUIndexSection () const
virtual Optional< RelocAddrEntry > find (const DWARFSection &Sec, uint64_t Pos) const =0
Detailed Description
Definition at line 25 of file DWARFObject.h.
Constructor & Destructor Documentation
~DWARFObject()
virtual llvm::DWARFObject::~DWARFObject () virtual default
Member Function Documentation
find()
virtual Optional< RelocAddrEntry > llvm::DWARFObject::find (const DWARFSection & Sec, uint64_t Pos) const pure virtual
Referenced by llvm::DWARFDataExtractor::getRelocatedValue().
forEachInfoDWOSections()
virtual void llvm::DWARFObject::forEachInfoDWOSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 57 of file DWARFObject.h.
forEachInfoSections()
virtual void llvm::DWARFObject::forEachInfoSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 36 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
forEachTypesDWOSections()
virtual void llvm::DWARFObject::forEachTypesDWOSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 59 of file DWARFObject.h.
forEachTypesSections()
virtual void llvm::DWARFObject::forEachTypesSections (function_ref< void(const DWARFSection &)> F) const inline virtual
Definition at line 38 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
getAbbrevDWOSection()
virtual StringRef llvm::DWARFObject::getAbbrevDWOSection () const inline virtual
Definition at line 60 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugAbbrev().
getAbbrevSection()
virtual StringRef llvm::DWARFObject::getAbbrevSection () const inline virtual
Definition at line 39 of file DWARFObject.h.
Referenced by llvm::DWARFVerifier::handleDebugAbbrev().
getAddressSize()
virtual uint8_t llvm::DWARFObject::getAddressSize () const inline virtual
Definition at line 34 of file DWARFObject.h.
References llvm_unreachable.
Referenced by dumpLocation().
getAddrSection()
virtual const DWARFSection & llvm::DWARFObject::getAddrSection () const inline virtual
Definition at line 69 of file DWARFObject.h.
getAppleNamespacesSection()
virtual const DWARFSection & llvm::DWARFObject::getAppleNamespacesSection () const inline virtual
Definition at line 72 of file DWARFObject.h.
getAppleNamesSection()
virtual const DWARFSection & llvm::DWARFObject::getAppleNamesSection () const inline virtual
Definition at line 70 of file DWARFObject.h.
getAppleObjCSection()
virtual const DWARFSection & llvm::DWARFObject::getAppleObjCSection () const inline virtual
Definition at line 76 of file DWARFObject.h.
getAppleTypesSection()
virtual const DWARFSection & llvm::DWARFObject::getAppleTypesSection () const inline virtual
Definition at line 71 of file DWARFObject.h.
getARangeSection()
virtual StringRef llvm::DWARFObject::getARangeSection () const inline virtual
Definition at line 42 of file DWARFObject.h.
Referenced by llvm::DWARFDebugAranges::generate().
getCUIndexSection()
virtual StringRef llvm::DWARFObject::getCUIndexSection () const inline virtual
Definition at line 77 of file DWARFObject.h.
getDebugFrameSection()
virtual StringRef llvm::DWARFObject::getDebugFrameSection () const inline virtual
Definition at line 43 of file DWARFObject.h.
getDebugNamesSection()
virtual const DWARFSection & llvm::DWARFObject::getDebugNamesSection () const inline virtual
Definition at line 75 of file DWARFObject.h.
getEHFrameSection()
virtual StringRef llvm::DWARFObject::getEHFrameSection () const inline virtual
Definition at line 44 of file DWARFObject.h.
getFile()
virtual const object::ObjectFile * llvm::DWARFObject::getFile () const inline virtual
Definition at line 31 of file DWARFObject.h.
Referenced by llvm::SourceMgr::AddIncludeFile(), llvm::LTOCodeGenerator::compileOptimized(), llvm::LTOModule::createFromFile(), llvm::SpecialCaseList::createInternal(), llvm::object::ObjectFile::createObjectFile(), llvm::DWARFVerifier::DWARFVerifier(), ExpandResponseFile(), llvm::DWARFContext::getArch(), llvm::object::Archive::Child::getBuffer(), llvm::LTOModule::isBitcodeFile(), and llvm::SymbolRewriter::RewriteMapParser::parse().
getFileName()
virtual StringRef llvm::DWARFObject::getFileName () const inline virtual
Definition at line 30 of file DWARFObject.h.
References llvm_unreachable.
getGdbIndexSection()
virtual StringRef llvm::DWARFObject::getGdbIndexSection () const inline virtual
Definition at line 78 of file DWARFObject.h.
getGnuPubNamesSection()
virtual const DWARFSection & llvm::DWARFObject::getGnuPubNamesSection () const inline virtual
Definition at line 53 of file DWARFObject.h.
getGnuPubTypesSection()
virtual const DWARFSection & llvm::DWARFObject::getGnuPubTypesSection () const inline virtual
Definition at line 54 of file DWARFObject.h.
getLineDWOSection()
virtual const DWARFSection & llvm::DWARFObject::getLineDWOSection () const inline virtual
Definition at line 61 of file DWARFObject.h.
getLineSection()
virtual const DWARFSection & llvm::DWARFObject::getLineSection () const inline virtual
Definition at line 45 of file DWARFObject.h.
getLineStringSection()
virtual StringRef llvm::DWARFObject::getLineStringSection () const inline virtual
Definition at line 46 of file DWARFObject.h.
getLocDWOSection()
virtual const DWARFSection & llvm::DWARFObject::getLocDWOSection () const inline virtual
Definition at line 62 of file DWARFObject.h.
getLoclistsSection()
virtual const DWARFSection & llvm::DWARFObject::getLoclistsSection () const inline virtual
Definition at line 41 of file DWARFObject.h.
Referenced by dumpLocation().
getLocSection()
virtual const DWARFSection & llvm::DWARFObject::getLocSection () const inline virtual
Definition at line 40 of file DWARFObject.h.
getMacinfoSection()
virtual StringRef llvm::DWARFObject::getMacinfoSection () const inline virtual
Definition at line 50 of file DWARFObject.h.
getPubNamesSection()
virtual const DWARFSection & llvm::DWARFObject::getPubNamesSection () const inline virtual
Definition at line 51 of file DWARFObject.h.
getPubTypesSection()
virtual const DWARFSection & llvm::DWARFObject::getPubTypesSection () const inline virtual
Definition at line 52 of file DWARFObject.h.
getRangeDWOSection()
virtual const DWARFSection & llvm::DWARFObject::getRangeDWOSection () const inline virtual
Definition at line 67 of file DWARFObject.h.
getRangeSection()
virtual const DWARFSection & llvm::DWARFObject::getRangeSection () const inline virtual
Definition at line 48 of file DWARFObject.h.
getRnglistsDWOSection()
virtual const DWARFSection & llvm::DWARFObject::getRnglistsDWOSection () const inline virtual
Definition at line 68 of file DWARFObject.h.
getRnglistsSection()
virtual const DWARFSection & llvm::DWARFObject::getRnglistsSection () const inline virtual
Definition at line 49 of file DWARFObject.h.
getSectionNames()
virtual ArrayRef< SectionName > llvm::DWARFObject::getSectionNames () const inline virtual
Definition at line 32 of file DWARFObject.h.
Referenced by llvm::DWARFFormValue::dumpAddressSection(), and dumpRanges().
getStringDWOSection()
virtual StringRef llvm::DWARFObject::getStringDWOSection () const inline virtual
Definition at line 63 of file DWARFObject.h.
getStringOffsetDWOSection()
virtual const DWARFSection & llvm::DWARFObject::getStringOffsetDWOSection () const inline virtual
Definition at line 64 of file DWARFObject.h.
getStringOffsetSection()
virtual const DWARFSection & llvm::DWARFObject::getStringOffsetSection () const inline virtual
Definition at line 55 of file DWARFObject.h.
getStringSection()
virtual StringRef llvm::DWARFObject::getStringSection () const inline virtual
Definition at line 47 of file DWARFObject.h.
getTUIndexSection()
virtual StringRef llvm::DWARFObject::getTUIndexSection () const inline virtual
Definition at line 79 of file DWARFObject.h.
isLittleEndian()
virtual bool llvm::DWARFObject::isLittleEndian () const pure virtual
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFObject.h