LLVM: llvm::orc::rpc::detail::ResponseHandler< ChannelT > Class Template Reference
llvm::orc::rpc::detail::ResponseHandler< ChannelT > Class Template Reference abstract
#include "llvm/ExecutionEngine/Orc/RPCUtils.h"
Public Member Functions
virtual ~ResponseHandler ()
virtual Error handleResponse (ChannelT &C)=0
virtual void abandon ()=0
Static Public Member Functions
static Error createAbandonedResponseError ()
Detailed Description
template<typename ChannelT>
class llvm::orc::rpc::detail::ResponseHandler< ChannelT >
Definition at line 619 of file RPCUtils.h.
Constructor & Destructor Documentation
~ResponseHandler()
template<typename ChannelT > virtual llvm::orc::rpc::detail::ResponseHandler< ChannelT >::~ResponseHandler () inline virtual
Definition at line 621 of file RPCUtils.h.
Member Function Documentation
abandon()
template<typename ChannelT > virtual void llvm::orc::rpc::detail::ResponseHandler< ChannelT >::abandon () pure virtual
Implemented in llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, FuncRetT, HandlerT >, llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >, llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Expected< FuncRetT >, HandlerT >, and llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >.
createAbandonedResponseError()
template<typename ChannelT > static Error llvm::orc::rpc::detail::ResponseHandler< ChannelT >::createAbandonedResponseError () inline static
Definition at line 633 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, FuncRetT, HandlerT >::abandon(), llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >::abandon(), llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Expected< FuncRetT >, HandlerT >::abandon(), and llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >::abandon().
handleResponse()
template<typename ChannelT > virtual Error llvm::orc::rpc::detail::ResponseHandler< ChannelT >::handleResponse (ChannelT & C) pure virtual
Implemented in llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, FuncRetT, HandlerT >, llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >, llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Expected< FuncRetT >, HandlerT >, and llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCUtils.h