LLVM: llvm::DWARF5AccelTableData Class Reference
llvm::DWARF5AccelTableData Class Reference
The Data class implementation for DWARF v5 accelerator table.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
DWARF5AccelTableData (const DIE &Die)
void print (raw_ostream &OS) const override
const DIE & getDie () const
uint64_t getDieOffset () const
unsigned getDieTag () const
Public Member Functions inherited from llvm::AccelTableData
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
virtual void print (raw_ostream &OS) const =0
Static Public Member Functions
static uint32_t hash (StringRef Name)
Protected Member Functions
uint64_t order () const override
virtual uint64_t order () const =0
Protected Attributes
const DIE & Die
Detailed Description
The Data class implementation for DWARF v5 accelerator table.
Unlike the Apple Data classes, this class is just a DIE wrapper, and does not know to serialize itself. The complete serialization logic is in the emitDWARF5AccelTable function.
Definition at line 252 of file AccelTable.h.
Constructor & Destructor Documentation
DWARF5AccelTableData()
llvm::DWARF5AccelTableData::DWARF5AccelTableData (const DIE & Die) inline
Definition at line 256 of file AccelTable.h.
Member Function Documentation
getDie()
const DIE & llvm::DWARF5AccelTableData::getDie () const inline
Definition at line 262 of file AccelTable.h.
References Die.
getDieOffset()
uint64_t llvm::DWARF5AccelTableData::getDieOffset () const inline
Definition at line 263 of file AccelTable.h.
References Die, and llvm::DIE::getOffset().
Referenced by print().
getDieTag()
unsigned llvm::DWARF5AccelTableData::getDieTag () const inline
Definition at line 264 of file AccelTable.h.
References Die, and llvm::DIE::getTag().
Referenced by print().
hash()
static uint32_t llvm::DWARF5AccelTableData::hash (StringRef Name) inline static
Definition at line 254 of file AccelTable.h.
References llvm::caseFoldingDjbHash(), and Name.
order()
uint64_t llvm::DWARF5AccelTableData::order () const inline override protected virtual
Implements llvm::AccelTableData.
Definition at line 269 of file AccelTable.h.
References Die, and llvm::DIE::getOffset().
print()
void DWARF5AccelTableData::print (raw_ostream & OS) const override virtual
Implements llvm::AccelTableData.
Definition at line 681 of file AccelTable.cpp.
References getDieOffset(), getDieTag(), and llvm::dwarf::TagString().
Member Data Documentation
Die
const DIE& llvm::DWARF5AccelTableData::Die protected
Definition at line 267 of file AccelTable.h.
Referenced by getDie(), getDieOffset(), getDieTag(), and order().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp