LLVM: llvm::AVRELFStreamer Class Reference
llvm::AVRELFStreamer Class Reference
A target streamer for an AVR ELF object file.
#include "Target/AVR/MCTargetDesc/AVRELFStreamer.h"
Public Member Functions
AVRELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
MCELFStreamer & getStreamer ()
Public Member Functions inherited from llvm::AVRTargetStreamer
AVRTargetStreamer (MCStreamer &S)
void finish () override
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, raw_ostream &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
A target streamer for an AVR ELF object file.
Definition at line 17 of file AVRELFStreamer.h.
Constructor & Destructor Documentation
AVRELFStreamer()
llvm::AVRELFStreamer::AVRELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 56 of file AVRELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::getEFlagsForFeatureSet(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
Member Function Documentation
getStreamer()
MCELFStreamer & llvm::AVRELFStreamer::getStreamer () inline
Definition at line 21 of file AVRELFStreamer.h.
References llvm::MCTargetStreamer::Streamer.
Referenced by AVRELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/AVR/MCTargetDesc/AVRELFStreamer.h
lib/Target/AVR/MCTargetDesc/AVRELFStreamer.cpp