LLVM: llvm::MCRegisterInfo::DiffListIterator Class Reference
llvm::MCRegisterInfo::DiffListIterator Class Reference
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
bool isValid () const
isValid - returns true if this iterator is not yet at the end.
unsigned operator* () const
Dereference the iterator to get the value at the current position.
void operator++ ()
Pre-increment to move to the next position.
Protected Member Functions
DiffListIterator ()=default
Create an invalid iterator. Call init() to point to something useful.
void init (MCPhysReg InitVal, const MCPhysReg *DiffList)
init - Point the iterator to InitVal, decoding subsequent values from DiffList.
unsigned advance ()
advance - Move to the next list position, return the applied differential.
Detailed Description
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
Don't use this class directly, use one of the specialized sub-classes defined below.
Definition at line 186 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
DiffListIterator()
llvm::MCRegisterInfo::DiffListIterator::DiffListIterator () protected default
Create an invalid iterator. Call init() to point to something useful.
Member Function Documentation
advance()
unsigned llvm::MCRegisterInfo::DiffListIterator::advance () inline protected
advance - Move to the next list position, return the applied differential.
This function does not detect the end of the list, that is the caller's responsibility (by checking for a 0 return value).
Definition at line 205 of file MCRegisterInfo.h.
References assert(), D, and isValid().
Referenced by llvm::MCRegUnitIterator::MCRegUnitIterator(), and operator++().
init()
void llvm::MCRegisterInfo::DiffListIterator::init (MCPhysReg InitVal, const MCPhysReg * DiffList) inline protected
init - Point the iterator to InitVal, decoding subsequent values from DiffList.
The iterator will initially point to InitVal, sub-classes are responsible for skipping the seed value if it is not part of the list.
Definition at line 197 of file MCRegisterInfo.h.
Referenced by llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCSubRegIterator::MCSubRegIterator(), and llvm::MCSuperRegIterator::MCSuperRegIterator().
isValid()
bool llvm::MCRegisterInfo::DiffListIterator::isValid () const inline
isValid - returns true if this iterator is not yet at the end.
Definition at line 214 of file MCRegisterInfo.h.
Referenced by llvm::addLiveIns(), llvm::DwarfExpression::addMachineReg(), llvm::LivePhysRegs::addReg(), llvm::LiveRegUnits::addReg(), addRegUnits(), advance(), llvm::MCRegAliasIterator::advance(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::LiveRegUnits::available(), llvm::TargetRegisterInfo::checkAllSuperRegsMarked(), llvm::LiveRegMatrix::checkInterference(), computeLiveOuts(), llvm::finalizeBundle(), findHoistingInsertPosAndDeps(), llvm::SIRegisterInfo::findReachingDef(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foreachUnit(), llvm::RegScavenger::forward(), getDwarfRegNum(), llvm::MCRegisterInfo::getMatchingSuperReg(), getMax32BitSubRegister(), llvm::HexagonInstrInfo::getOperandLatency(), getPairedGPR(), llvm::MachineFrameInfo::getPristineRegs(), llvm::ReachingDefAnalysis::getReachingDef(), llvm::MCRegisterInfo::getSubReg(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::TargetRegisterInfo::hasRegUnit(), INITIALIZE_PASS(), llvm::HexagonInstrInfo::isDependent(), llvm::LiveRegMatrix::isPhysRegUsed(), llvm::MachineRegisterInfo::isReservedRegUnit(), llvm::MCSubRegIndexIterator::isValid(), llvm::MCRegUnitMaskIterator::isValid(), llvm::MCRegAliasIterator::isValid(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::TargetRegisterInfo::markSuperRegs(), llvm::MCRegAliasIterator::MCRegAliasIterator(), needsStackFrame(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::TargetRegisterInfo::regsOverlap(), llvm::LiveIntervals::removeAllRegUnitsForPhysReg(), llvm::LiveRegUnits::removeReg(), llvm::rdf::Liveness::resetKills(), llvm::MipsRegInfoRecord::SetPhysRegUsed(), TrackDefUses(), llvm::LiveIntervals::HMEditor::updateAllRanges(), updateLiveIn(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), and UpdatePredRedefs().
operator*()
unsigned llvm::MCRegisterInfo::DiffListIterator::operator* () const inline
Dereference the iterator to get the value at the current position.
Definition at line 217 of file MCRegisterInfo.h.
operator++()
void llvm::MCRegisterInfo::DiffListIterator::operator++ () inline
Pre-increment to move to the next position.
Definition at line 220 of file MCRegisterInfo.h.
References advance().
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h