LLVM: llvm::ImmutableMap< KeyT, ValT, ValInfo > Class Template Reference
llvm::ImmutableMap< KeyT, ValT, ValInfo > Class Template Reference
#include "llvm/ADT/ImmutableMap.h"
Classes
class Factory
class iterator
Public Types
using value_type = typename ValInfo::value_type
using value_type_ref = typename ValInfo::value_type_ref
using key_type = typename ValInfo::key_type
using key_type_ref = typename ValInfo::key_type_ref
using data_type = typename ValInfo::data_type
using data_type_ref = typename ValInfo::data_type_ref
using TreeTy = ImutAVLTree< ValInfo >
Public Member Functions
ImmutableMap (const TreeTy *R)
Constructs a map from a pointer to a tree root.
ImmutableMap (const ImmutableMap &X)
~ImmutableMap ()
ImmutableMap & operator= (const ImmutableMap &X)
bool contains (key_type_ref K) const
bool operator== (const ImmutableMap &RHS) const
bool operator!= (const ImmutableMap &RHS) const
TreeTy * getRoot () const
TreeTy * getRootWithoutRetain () const
void manualRetain ()
void manualRelease ()
bool isEmpty () const
template<typename Callback >
void foreach (Callback &C)
template<typename Callback >
void foreach ()
void verify () const
iterator begin () const
iterator end () const
data_type * lookup (key_type_ref K) const
value_type * getMaxElement () const
getMaxElement - Returns the <key,value> pair in the ImmutableMap for which key is the highest in the ordering of keys in the map.
unsigned getHeight () const
void Profile (FoldingSetNodeID &ID) const
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, const ImmutableMap &M)
Protected Attributes
TreeTy * Root
Detailed Description
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>>
class llvm::ImmutableMap< KeyT, ValT, ValInfo >
Definition at line 62 of file ImmutableMap.h.
Member Typedef Documentation
data_type
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::data_type = typename ValInfo::data_type
Definition at line 68 of file ImmutableMap.h.
data_type_ref
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::data_type_ref = typename ValInfo::data_type_ref
Definition at line 69 of file ImmutableMap.h.
key_type
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::key_type = typename ValInfo::key_type
Definition at line 66 of file ImmutableMap.h.
key_type_ref
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::key_type_ref = typename ValInfo::key_type_ref
Definition at line 67 of file ImmutableMap.h.
TreeTy
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::TreeTy = ImutAVLTree<ValInfo>
Definition at line 70 of file ImmutableMap.h.
value_type
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::value_type = typename ValInfo::value_type
Definition at line 64 of file ImmutableMap.h.
value_type_ref
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> using llvm::ImmutableMap< KeyT, ValT, ValInfo >::value_type_ref = typename ValInfo::value_type_ref
Definition at line 65 of file ImmutableMap.h.
Constructor & Destructor Documentation
ImmutableMap() [1/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap (const TreeTy * R) inline explicit
Constructs a map from a pointer to a tree root.
In general one should use a Factory object to create maps instead of directly invoking the constructor, but there are cases where make this constructor public is useful.
Definition at line 80 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
ImmutableMap() [2/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap (const ImmutableMap< KeyT, ValT, ValInfo > & X) inline
Definition at line 84 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
~ImmutableMap()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::~ImmutableMap () inline
Definition at line 88 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::release(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
Member Function Documentation
begin()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMap< KeyT, ValT, ValInfo >::begin () const inline
Definition at line 220 of file ImmutableMap.h.
References llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
contains()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::contains (key_type_ref K) const inline
Definition at line 132 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::contains(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
end()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMap< KeyT, ValT, ValInfo >::end () const inline
Definition at line 221 of file ImmutableMap.h.
foreach() [1/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> template<typename Callback > void llvm::ImmutableMap< KeyT, ValT, ValInfo >::foreach () inline
Definition at line 192 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::foreach(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
foreach() [2/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> template<typename Callback > void llvm::ImmutableMap< KeyT, ValT, ValInfo >::foreach (Callback & C) inline
Definition at line 184 of file ImmutableMap.h.
References C, llvm::ImutAVLTree< ImutInfo >::foreach(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
getHeight()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> unsigned llvm::ImmutableMap< KeyT, ValT, ValInfo >::getHeight () const inline
Definition at line 243 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getHeight(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
getMaxElement()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> value_type * llvm::ImmutableMap< KeyT, ValT, ValInfo >::getMaxElement () const inline
getMaxElement - Returns the <key,value> pair in the ImmutableMap for which key is the highest in the ordering of keys in the map.
This method returns NULL if the map is empty.
Definition at line 235 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getMaxElement(), llvm::ImutAVLTree< ImutInfo >::getValue(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
getRoot()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> TreeTy * llvm::ImmutableMap< KeyT, ValT, ValInfo >::getRoot () const inline
Definition at line 144 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
getRootWithoutRetain()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> TreeTy * llvm::ImmutableMap< KeyT, ValT, ValInfo >::getRootWithoutRetain () const inline
Definition at line 149 of file ImmutableMap.h.
References llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
isEmpty()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::isEmpty () const inline
Definition at line 159 of file ImmutableMap.h.
References llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
lookup()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> data_type * llvm::ImmutableMap< KeyT, ValT, ValInfo >::lookup (key_type_ref K) const inline
Definition at line 223 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::find(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
manualRelease()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMap< KeyT, ValT, ValInfo >::manualRelease () inline
Definition at line 155 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::release(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
manualRetain()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMap< KeyT, ValT, ValInfo >::manualRetain () inline
Definition at line 151 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
operator!=()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator!= (const ImmutableMap< KeyT, ValT, ValInfo > & RHS) const inline
Definition at line 140 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::isNotEqual(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
operator=()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMap & llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator= (const ImmutableMap< KeyT, ValT, ValInfo > & X) inline
Definition at line 92 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::release(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root, and X.
operator==()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator== (const ImmutableMap< KeyT, ValT, ValInfo > & RHS) const inline
Definition at line 136 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::isEqual(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
Profile() [1/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMap< KeyT, ValT, ValInfo >::Profile (FoldingSetNodeID & ID) const inline
Definition at line 249 of file ImmutableMap.h.
References llvm::ImmutableMap< KeyT, ValT, ValInfo >::Profile().
Profile() [2/2]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> static void llvm::ImmutableMap< KeyT, ValT, ValInfo >::Profile (FoldingSetNodeID & ID, const ImmutableMap< KeyT, ValT, ValInfo > & M) inline static
Definition at line 245 of file ImmutableMap.h.
Referenced by llvm::ImmutableMap< KeyT, ValT, ValInfo >::Profile().
verify()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMap< KeyT, ValT, ValInfo >::verify () const inline
Definition at line 203 of file ImmutableMap.h.
References llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
Member Data Documentation
Root
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> TreeTy* llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root protected
Definition at line 73 of file ImmutableMap.h.
Referenced by llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::add(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::begin(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::contains(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::foreach(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::getHeight(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::getMaxElement(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::getRoot(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::getRootWithoutRetain(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::isEmpty(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::lookup(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::manualRelease(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::manualRetain(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator!=(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator=(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator==(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::remove(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::verify(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::~ImmutableMap().
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableMap.h