LLVM: llvm::MCCVInlineLineTableFragment Class Reference
llvm::MCCVInlineLineTableFragment Class Reference
Fragment representing the binary annotations produced by the .cv_inline_linetable directive.
#include "llvm/MC/MCFragment.h"
Public Member Functions
MCCVInlineLineTableFragment (unsigned SiteFuncId, unsigned StartFileId, unsigned StartLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym, MCSection *Sec=nullptr)
Accessors
const MCSymbol * getFnStartSym () const
const MCSymbol * getFnEndSym () const
SmallString< 8 > & getContents ()
const SmallString< 8 > & getContents () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
bool isDummy () const
Return true if given frgment has FT_Dummy type.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Friends
class CodeViewContext
CodeViewContext has the real knowledge about this format, so let it access our members.
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB , FT_Padding , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_Dummy
}
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
~MCFragment ()
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Detailed Description
Fragment representing the binary annotations produced by the .cv_inline_linetable directive.
Definition at line 597 of file MCFragment.h.
Constructor & Destructor Documentation
MCCVInlineLineTableFragment()
llvm::MCCVInlineLineTableFragment::MCCVInlineLineTableFragment (unsigned SiteFuncId, unsigned StartFileId, unsigned StartLineNum, const MCSymbol * FnStartSym, const MCSymbol * FnEndSym, MCSection * Sec = nullptr) inline
Definition at line 610 of file MCFragment.h.
Member Function Documentation
classof()
static bool llvm::MCCVInlineLineTableFragment::classof (const MCFragment * F) inline static
Definition at line 629 of file MCFragment.h.
References F, and llvm::MCFragment::FT_CVInlineLines.
getContents() [1/2]
SmallString< 8 > & llvm::MCCVInlineLineTableFragment::getContents () inline
Definition at line 624 of file MCFragment.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
getContents() [2/2]
const SmallString< 8 > & llvm::MCCVInlineLineTableFragment::getContents () const inline
Definition at line 625 of file MCFragment.h.
getFnEndSym()
const MCSymbol * llvm::MCCVInlineLineTableFragment::getFnEndSym () const inline
Definition at line 622 of file MCFragment.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
getFnStartSym()
const MCSymbol * llvm::MCCVInlineLineTableFragment::getFnStartSym () const inline
Definition at line 621 of file MCFragment.h.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().
Friends And Related Function Documentation
CodeViewContext
friend class CodeViewContext friend
CodeViewContext has the real knowledge about this format, so let it access our members.
Definition at line 607 of file MCFragment.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h