LLVM: llvm::object::Archive Class Reference
llvm::object::Archive Class Reference
#include "llvm/Object/Archive.h"
Classes
class Child
class ChildFallibleIterator
class Symbol
class symbol_iterator
Public Types
enum Kind {
K_GNU , K_GNU64 , K_BSD , K_DARWIN ,
K_DARWIN64 , K_COFF
}
using child_iterator = fallible_iterator< ChildFallibleIterator >
Public Member Functions
Archive (MemoryBufferRef Source, Error &Err)
Kind kind () const
bool isThin () const
child_iterator child_begin (Error &Err, bool SkipInternal=true) const
child_iterator child_end () const
iterator_range< child_iterator > children (Error &Err, bool SkipInternal=true) const
symbol_iterator symbol_begin () const
symbol_iterator symbol_end () const
iterator_range< symbol_iterator > symbols () const
Expected< Optional< Child > > findSym (StringRef name) const
bool isEmpty () const
bool hasSymbolTable () const
StringRef getSymbolTable () const
StringRef getStringTable () const
uint32_t getNumberOfSymbols () const
std::vector< std::unique_ptr< MemoryBuffer > > takeThinBuffers ()
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< std::unique_ptr< Archive > > create (MemoryBufferRef Source)
static bool classof (Binary const *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 84 of file Archive.h.
Member Typedef Documentation
child_iterator
using llvm::object::Archive::child_iterator = fallible_iterator<ChildFallibleIterator>
Definition at line 176 of file Archive.h.
Member Enumeration Documentation
Kind
enum llvm::object::Archive::Kind
Enumerator
K_GNU
K_GNU64
K_BSD
K_DARWIN
K_DARWIN64
K_COFF
Definition at line 224 of file Archive.h.
Constructor & Destructor Documentation
Archive()
Archive::Archive (MemoryBufferRef Source, Error & Err)
Definition at line 543 of file Archive.cpp.
References C, child_begin(), child_end(), llvm::object::Binary::Data, E, llvm::errorCodeToError(), llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBuffer(), I, llvm::object::invalid_file_type, K_BSD, K_COFF, K_DARWIN64, K_GNU, K_GNU64, Magic, Name, llvm::object::parse_failed, llvm::StringRef::startswith(), llvm::Error::success(), llvm::Expected< T >::takeError(), and ThinMagic.
Member Function Documentation
child_begin()
Archive::child_iterator Archive::child_begin (Error & Err, bool SkipInternal = true) const
Definition at line 775 of file Archive.cpp.
References C, child_end(), llvm::object::Binary::Data, llvm::MemoryBufferRef::getBufferStart(), isEmpty(), llvm::fallible_iterator< Underlying >::itr(), and Magic.
Referenced by Archive(), and children().
child_end()
Archive::child_iterator Archive::child_end () const
Definition at line 791 of file Archive.cpp.
Referenced by Archive(), child_begin(), children(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator++(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::RNSuccIterator(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::RNSuccIterator(), and llvm::GraphWriter< GraphType >::writeNode().
children()
iterator_range< child_iterator > llvm::object::Archive::children (Error & Err, bool SkipInternal = true) const inline
Definition at line 238 of file Archive.h.
References child_begin(), child_end(), and llvm::make_range().
Referenced by doList().
classof()
static bool llvm::object::Archive::classof (Binary const * v) inline static
Definition at line 250 of file Archive.h.
References llvm::object::Binary::isArchive().
create()
Expected< std::unique_ptr< Archive > > Archive::create (MemoryBufferRef Source) static
Definition at line 530 of file Archive.cpp.
References llvm::Error::success().
findSym()
Expected< Optional< Archive::Child > > Archive::findSym (StringRef name) const
Definition at line 976 of file Archive.cpp.
References llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::Symbol::getName(), name, symbol_begin(), and symbol_end().
getNumberOfSymbols()
uint32_t Archive::getNumberOfSymbols () const
Definition at line 958 of file Archive.cpp.
References llvm::StringRef::begin(), getSymbolTable(), hasSymbolTable(), K_BSD, K_DARWIN64, K_GNU, K_GNU64, kind(), llvm::support::endian::read32be(), llvm::support::endian::read32le(), llvm::support::endian::read64be(), and llvm::support::endian::read64le().
Referenced by symbol_end().
getStringTable()
StringRef llvm::object::Archive::getStringTable () const inline
Definition at line 260 of file Archive.h.
Referenced by llvm::object::ArchiveMemberHeader::getName().
getSymbolTable()
StringRef llvm::object::Archive::getSymbolTable () const inline
Definition at line 259 of file Archive.h.
Referenced by llvm::object::Archive::Symbol::getName(), getNumberOfSymbols(), and symbol_begin().
hasSymbolTable()
bool Archive::hasSymbolTable () const
Definition at line 995 of file Archive.cpp.
References llvm::StringRef::empty().
Referenced by getNumberOfSymbols(), and symbol_begin().
isEmpty()
bool Archive::isEmpty () const
Definition at line 993 of file Archive.cpp.
References llvm::object::Binary::Data, and llvm::MemoryBufferRef::getBufferSize().
Referenced by child_begin().
isThin()
bool llvm::object::Archive::isThin () const inline
Definition at line 234 of file Archive.h.
Referenced by llvm::object::Archive::Child::Child(), llvm::object::Archive::Child::getBuffer(), and llvm::object::Archive::Child::getFullName().
kind()
Kind llvm::object::Archive::kind () const inline
Definition at line 233 of file Archive.h.
Referenced by llvm::object::ArchiveMemberHeader::getName(), getNumberOfSymbols(), llvm::object::ArchiveMemberHeader::getRawName(), and symbol_begin().
symbol_begin()
Archive::symbol_iterator Archive::symbol_begin () const
Definition at line 898 of file Archive.cpp.
References llvm::StringRef::begin(), getSymbolTable(), hasSymbolTable(), K_BSD, K_DARWIN64, K_GNU, K_GNU64, kind(), llvm::support::endian::read32be(), llvm::support::endian::read32le(), llvm::support::endian::read64be(), and llvm::support::endian::read64le().
Referenced by findSym(), and symbols().
symbol_end()
Archive::symbol_iterator Archive::symbol_end () const
Definition at line 954 of file Archive.cpp.
References getNumberOfSymbols().
Referenced by findSym(), and symbols().
symbols()
iterator_range< symbol_iterator > llvm::object::Archive::symbols () const inline
Definition at line 245 of file Archive.h.
References llvm::make_range(), symbol_begin(), and symbol_end().
takeThinBuffers()
std::vector< std::unique_ptr< MemoryBuffer > > llvm::object::Archive::takeThinBuffers () inline
Definition at line 263 of file Archive.h.
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp