LLVM: llvm::TGParser Class Reference
llvm::TGParser Class Reference
#include "TableGen/TGParser.h"
Public Member Functions
TGParser (SourceMgr &SrcMgr, ArrayRef< std::string > Macros, RecordKeeper &records)
bool ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
bool Error (SMLoc L, const Twine &Msg) const
bool TokError (const Twine &Msg) const
const TGLexer::DependenciesMapTy & getDependencies () const
Detailed Description
Definition at line 87 of file TGParser.h.
Constructor & Destructor Documentation
TGParser()
llvm::TGParser::TGParser (SourceMgr & SrcMgr, ArrayRef< std::string > Macros, RecordKeeper & records) inline
Definition at line 117 of file TGParser.h.
Member Function Documentation
Error()
bool llvm::TGParser::Error (SMLoc L, const Twine & Msg) const inline
Definition at line 125 of file TGParser.h.
References llvm::PrintError().
getDependencies()
const TGLexer::DependenciesMapTy & llvm::TGParser::getDependencies () const inline
Definition at line 132 of file TGParser.h.
References llvm::TGLexer::getDependencies().
Referenced by createDependencyFile().
ParseFile()
bool TGParser::ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
These parser routines return true on error, or false on success.
Definition at line 3206 of file TGParser.cpp.
References llvm::tgtok::Eof, llvm::TGLexer::getCode(), llvm::TGLexer::Lex(), and TokError().
Referenced by llvm::TableGenMain().
TokError()
bool llvm::TGParser::TokError (const Twine & Msg) const inline
Definition at line 129 of file TGParser.h.
References llvm::TGLexer::getLoc().
Referenced by ParseFile().
The documentation for this class was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp