LLVM: llvm::BinOpInit Class Reference
llvm::BinOpInit Class Reference
!op (X, Y) - Combine two inits.
#include "llvm/TableGen/Record.h"
Public Types
enum BinaryOp : uint8_t {
ADD , MUL , AND , OR ,
SHL , SRA , SRL , LISTCONCAT ,
LISTSPLAT , STRCONCAT , CONCAT , EQ ,
NE , LE , LT , GE ,
GT
}
Public Member Functions
BinOpInit (const BinOpInit &)=delete
BinOpInit & operator= (const BinOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
OpInit * clone (ArrayRef< Init * > Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
BinaryOp getOpcode () const
Init * getLHS () const
Init * getRHS () const
Init * Fold (Record *CurRec) const
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a string form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
virtual OpInit * clone (ArrayRef< Init * > Operands) const =0
virtual unsigned getNumOperands () const =0
virtual Init * getOperand (unsigned i) const =0
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static BinOpInit * get (BinaryOp opc, Init *lhs, Init *rhs, RecTy *Type)
static Init * getStrConcat (Init *lhs, Init *rhs)
static Init * getListConcat (TypedInit *lhs, Init *rhs)
static Init * getListSplat (TypedInit *lhs, Init *rhs)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X, Y) - Combine two inits.
Definition at line 801 of file Record.h.
Member Enumeration Documentation
BinaryOp
enum llvm::BinOpInit::BinaryOp : uint8_t
Enumerator
ADD
MUL
AND
OR
SHL
SRA
SRL
LISTCONCAT
LISTSPLAT
STRCONCAT
CONCAT
EQ
NE
LE
LT
GE
GT
Definition at line 803 of file Record.h.
Constructor & Destructor Documentation
BinOpInit()
llvm::BinOpInit::BinOpInit (const BinOpInit &) delete
Member Function Documentation
classof()
static bool llvm::BinOpInit::classof (const Init * I) inline static
Definition at line 817 of file Record.h.
References I, and llvm::Init::IK_BinOpInit.
clone()
OpInit * llvm::BinOpInit::clone (ArrayRef< Init * > Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 830 of file Record.h.
References assert(), llvm::IntervalMapImpl::NodeRef::get(), getOpcode(), llvm::TypedInit::getType(), and llvm::ArrayRef< T >::size().
Fold()
Init * BinOpInit::Fold (Record * CurRec) const
Definition at line 882 of file Record.cpp.
References ADD, AND, llvm::ListInit::begin(), CONCAT, ConcatStringInits(), llvm::Init::convertInitializerTo(), llvm::ListInit::end(), EQ, GE, llvm::IntRecTy::get(), llvm::IntervalMapImpl::NodeRef::get(), llvm::DagInit::getArg(), llvm::DagInit::getArgName(), llvm::DagInit::getAsString(), llvm::DefInit::getDef(), llvm::ListInit::getElementType(), llvm::DagInit::getNumArgs(), getOpcode(), llvm::DagInit::getOperator(), llvm::Value::getType(), llvm::IntInit::getValue(), llvm::StringInit::getValue(), GT, LE, LISTCONCAT, LISTSPLAT, llvm_unreachable, LT, MUL, NE, OR, llvm::PrintFatalError(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), SHL, Size, SRA, SRL, and STRCONCAT.
get()
BinOpInit * BinOpInit::get (BinaryOp opc, Init * lhs, Init * rhs, RecTy * Type) static
Definition at line 825 of file Record.cpp.
References Allocator, llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), I, llvm::FoldingSetImpl< T >::InsertNode(), llvm::Init::Opc, and ProfileBinOpInit().
getAsString()
std::string BinOpInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1020 of file Record.cpp.
References ADD, AND, CONCAT, EQ, GE, llvm::Init::getAsString(), getOpcode(), GT, LE, LISTCONCAT, LISTSPLAT, LT, MUL, NE, OR, SHL, SRA, SRL, and STRCONCAT.
getLHS()
Init * llvm::BinOpInit::getLHS () const inline
Definition at line 846 of file Record.h.
Referenced by getOperand(), and Profile().
getListConcat()
Init * BinOpInit::getListConcat (TypedInit * lhs, Init * rhs) static
Definition at line 868 of file Record.cpp.
References assert(), ConcatListInits(), llvm::IntervalMapImpl::NodeRef::get(), llvm::TypedInit::getType(), and LISTCONCAT.
getListSplat()
Init * BinOpInit::getListSplat (TypedInit * lhs, Init * rhs) static
Definition at line 878 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::TypedInit::getType(), and LISTSPLAT.
getNumOperands()
unsigned llvm::BinOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 836 of file Record.h.
getOpcode()
BinaryOp llvm::BinOpInit::getOpcode () const inline
Definition at line 845 of file Record.h.
References llvm::Init::Opc.
Referenced by clone(), Fold(), getAsString(), Profile(), and resolveReferences().
getOperand()
Init * llvm::BinOpInit::getOperand (unsigned i) const inline override virtual
Implements llvm::OpInit.
Definition at line 837 of file Record.h.
References getLHS(), getRHS(), and llvm_unreachable.
getRHS()
Init * llvm::BinOpInit::getRHS () const inline
Definition at line 847 of file Record.h.
Referenced by getOperand(), and Profile().
getStrConcat()
Init * BinOpInit::getStrConcat (Init * lhs, Init * rhs) static
Definition at line 852 of file Record.cpp.
References ConcatStringInits(), llvm::StringRecTy::get(), llvm::IntervalMapImpl::NodeRef::get(), and STRCONCAT.
Referenced by QualifyName().
operator=()
BinOpInit & llvm::BinOpInit::operator= (const BinOpInit &) delete
Profile()
void BinOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 841 of file Record.cpp.
References getLHS(), getOpcode(), getRHS(), llvm::TypedInit::getType(), and ProfileBinOpInit().
resolveReferences()
Init * BinOpInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1010 of file Record.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), getOpcode(), llvm::TypedInit::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp