LLVM: llvm::SuperRegClassIterator Class Reference
llvm::SuperRegClassIterator Class Reference
#include "llvm/CodeGen/TargetRegisterInfo.h"
Public Member Functions
SuperRegClassIterator (const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, bool IncludeSelf=false)
Create a SuperRegClassIterator that visits all the super-register classes of RC.
bool isValid () const
Returns true if this iterator is still pointing at a valid entry.
unsigned getSubReg () const
Returns the current sub-register index.
const uint32_t * getMask () const
Returns the bit mask of register classes that getSubReg() projects into RC.
void operator++ ()
Advance iterator to the next entry.
Detailed Description
Definition at line 1026 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
SuperRegClassIterator()
llvm::SuperRegClassIterator::SuperRegClassIterator (const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, bool IncludeSelf = false) inline
Create a SuperRegClassIterator that visits all the super-register classes of RC.
When IncludeSelf is set, also include the (0, sub-classes) entry.
Definition at line 1035 of file TargetRegisterInfo.h.
References Idx.
Member Function Documentation
getMask()
const uint32_t * llvm::SuperRegClassIterator::getMask () const inline
Returns the bit mask of register classes that getSubReg() projects into RC.
See TargetRegisterClass::getSubClassMask() for how to use it.
Definition at line 1053 of file TargetRegisterInfo.h.
getSubReg()
unsigned llvm::SuperRegClassIterator::getSubReg () const inline
Returns the current sub-register index.
Definition at line 1048 of file TargetRegisterInfo.h.
References SubReg.
isValid()
bool llvm::SuperRegClassIterator::isValid () const inline
Returns true if this iterator is still pointing at a valid entry.
Definition at line 1045 of file TargetRegisterInfo.h.
References Idx.
Referenced by llvm::TargetLoweringBase::findRepresentativeClass(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), and operator++().
operator++()
void llvm::SuperRegClassIterator::operator++ () inline
Advance iterator to the next entry.
Definition at line 1056 of file TargetRegisterInfo.h.
References assert(), Idx, isValid(), and SubReg.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/TargetRegisterInfo.h