LLVM: llvm::SelectionDAGISel Class Reference
llvm::SelectionDAGISel Class Reference abstract
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
#include "llvm/CodeGen/SelectionDAGISel.h"
Public Types
enum BuiltinOpcodes {
OPC_Scope , OPC_RecordNode , OPC_RecordChild0 , OPC_RecordChild1 ,
OPC_RecordChild2 , OPC_RecordChild3 , OPC_RecordChild4 , OPC_RecordChild5 ,
OPC_RecordChild6 , OPC_RecordChild7 , OPC_RecordMemRef , OPC_CaptureGlueInput ,
OPC_MoveChild , OPC_MoveChild0 , OPC_MoveChild1 , OPC_MoveChild2 ,
OPC_MoveChild3 , OPC_MoveChild4 , OPC_MoveChild5 , OPC_MoveChild6 ,
OPC_MoveChild7 , OPC_MoveParent , OPC_CheckSame , OPC_CheckChild0Same ,
OPC_CheckChild1Same , OPC_CheckChild2Same , OPC_CheckChild3Same , OPC_CheckPatternPredicate ,
OPC_CheckPredicate , OPC_CheckPredicateWithOperands , OPC_CheckOpcode , OPC_SwitchOpcode ,
OPC_CheckType , OPC_CheckTypeRes , OPC_SwitchType , OPC_CheckChild0Type ,
OPC_CheckChild1Type , OPC_CheckChild2Type , OPC_CheckChild3Type , OPC_CheckChild4Type ,
OPC_CheckChild5Type , OPC_CheckChild6Type , OPC_CheckChild7Type , OPC_CheckInteger ,
OPC_CheckChild0Integer , OPC_CheckChild1Integer , OPC_CheckChild2Integer , OPC_CheckChild3Integer ,
OPC_CheckChild4Integer , OPC_CheckCondCode , OPC_CheckChild2CondCode , OPC_CheckValueType ,
OPC_CheckComplexPat , OPC_CheckAndImm , OPC_CheckOrImm , OPC_CheckImmAllOnesV ,
OPC_CheckImmAllZerosV , OPC_CheckFoldableChainNode , OPC_EmitInteger , OPC_EmitRegister ,
OPC_EmitRegister2 , OPC_EmitConvertToTarget , OPC_EmitMergeInputChains , OPC_EmitMergeInputChains1_0 ,
OPC_EmitMergeInputChains1_1 , OPC_EmitMergeInputChains1_2 , OPC_EmitCopyToReg , OPC_EmitNodeXForm ,
OPC_EmitNode , OPC_EmitNode0 , OPC_EmitNode1 , OPC_EmitNode2 ,
OPC_MorphNodeTo , OPC_MorphNodeTo0 , OPC_MorphNodeTo1 , OPC_MorphNodeTo2 ,
OPC_CompleteMatch , OPC_Coverage
}
enum {
OPFL_None = 0 , OPFL_Chain = 1 , OPFL_GlueInput = 2 , OPFL_GlueOutput = 4 ,
OPFL_MemRefs = 8 , OPFL_Variadic0 = 1<<4 , OPFL_Variadic1 = 2<<4 , OPFL_Variadic2 = 3<<4 ,
OPFL_Variadic3 = 4<<4 , OPFL_Variadic4 = 5<<4 , OPFL_Variadic5 = 6<<4 , OPFL_Variadic6 = 7<<4 ,
OPFL_VariadicInfo = OPFL_Variadic6
}
Public Member Functions
SelectionDAGISel (TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
~SelectionDAGISel () override
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
virtual void EmitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
virtual void PostprocessISelDAG ()
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
virtual void Select (SDNode *N)=0
Main hook for targets to transform nodes into machine nodes.
virtual bool SelectInlineAsmMemoryOperand (const SDValue &Op, unsigned ConstraintID, std::vector< SDValue > &OutOps)
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
virtual bool CheckPatternPredicate (unsigned PredNo) const
CheckPatternPredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
CheckNodePredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicateWithOperands (SDNode *N, unsigned PredNo, const SmallVectorImpl< SDValue > &Operands) const
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
void SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
bool isOrEquivalentToAdd (const SDNode *N) const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
static void InvalidateNodeId (SDNode *N)
static int getUninvalidatedNodeId (SDNode *N)
static void EnforceNodeIdInvariant (SDNode *N)
static int getNumFixedFromVariadicInfo (unsigned Flags)
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes
TargetMachine & TM
const TargetLibraryInfo * LibInfo
FunctionLoweringInfo * FuncInfo
SwiftErrorValueTracking * SwiftError
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
SelectionDAGBuilder * SDB
AliasAnalysis * AA
GCFunctionInfo * GFI
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
bool FastISelFailed
SmallPtrSet< const Instruction *, 4 > ElidedArgCopyInstrs
std::unique_ptr< OptimizationRemarkEmitter > ORE
Current optimization remark emitter.
Static Public Attributes
static char ID = 0
Protected Member Functions
void ReplaceUses (SDValue F, SDValue T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
void ReplaceUses (SDNode *F, SDNode *T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceNode (SDNode *F, SDNode *T)
Replace all uses of F with T, then remove F from the DAG.
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops, const SDLoc &DL)
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
virtual StringRef getPatternForIndex (unsigned index)
getPatternForIndex - Patterns selected by tablegen during ISEL
virtual StringRef getIncludePathForIndex (unsigned index)
getIncludePathForIndex - get the td source location of pattern instantiation
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
unsigned DAGSize
DAGSize - Size of DAG being instruction selected.
Detailed Description
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
Definition at line 44 of file SelectionDAGISel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPFL_None
OPFL_Chain
OPFL_GlueInput
OPFL_GlueOutput
OPFL_MemRefs
OPFL_Variadic0
OPFL_Variadic1
OPFL_Variadic2
OPFL_Variadic3
OPFL_Variadic4
OPFL_Variadic5
OPFL_Variadic6
OPFL_VariadicInfo
Definition at line 177 of file SelectionDAGISel.h.
BuiltinOpcodes
enum llvm::SelectionDAGISel::BuiltinOpcodes
Enumerator
OPC_Scope
OPC_RecordNode
OPC_RecordChild0
OPC_RecordChild1
OPC_RecordChild2
OPC_RecordChild3
OPC_RecordChild4
OPC_RecordChild5
OPC_RecordChild6
OPC_RecordChild7
OPC_RecordMemRef
OPC_CaptureGlueInput
OPC_MoveChild
OPC_MoveChild0
OPC_MoveChild1
OPC_MoveChild2
OPC_MoveChild3
OPC_MoveChild4
OPC_MoveChild5
OPC_MoveChild6
OPC_MoveChild7
OPC_MoveParent
OPC_CheckSame
OPC_CheckChild0Same
OPC_CheckChild1Same
OPC_CheckChild2Same
OPC_CheckChild3Same
OPC_CheckPatternPredicate
OPC_CheckPredicate
OPC_CheckPredicateWithOperands
OPC_CheckOpcode
OPC_SwitchOpcode
OPC_CheckType
OPC_CheckTypeRes
OPC_SwitchType
OPC_CheckChild0Type
OPC_CheckChild1Type
OPC_CheckChild2Type
OPC_CheckChild3Type
OPC_CheckChild4Type
OPC_CheckChild5Type
OPC_CheckChild6Type
OPC_CheckChild7Type
OPC_CheckInteger
OPC_CheckChild0Integer
OPC_CheckChild1Integer
OPC_CheckChild2Integer
OPC_CheckChild3Integer
OPC_CheckChild4Integer
OPC_CheckCondCode
OPC_CheckChild2CondCode
OPC_CheckValueType
OPC_CheckComplexPat
OPC_CheckAndImm
OPC_CheckOrImm
OPC_CheckImmAllOnesV
OPC_CheckImmAllZerosV
OPC_CheckFoldableChainNode
OPC_EmitInteger
OPC_EmitRegister
OPC_EmitRegister2
OPC_EmitConvertToTarget
OPC_EmitMergeInputChains
OPC_EmitMergeInputChains1_0
OPC_EmitMergeInputChains1_1
OPC_EmitMergeInputChains1_2
OPC_EmitCopyToReg
OPC_EmitNodeXForm
OPC_EmitNode
OPC_EmitNode0
OPC_EmitNode1
OPC_EmitNode2
OPC_MorphNodeTo
OPC_MorphNodeTo0
OPC_MorphNodeTo1
OPC_MorphNodeTo2
OPC_CompleteMatch
OPC_Coverage
Definition at line 120 of file SelectionDAGISel.h.
Constructor & Destructor Documentation
SelectionDAGISel()
SelectionDAGISel::SelectionDAGISel (TargetMachine & tm, CodeGenOpt::Level OL = CodeGenOpt::Default) explicit
Definition at line 307 of file SelectionDAGISel.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::initializeAAResultsWrapperPassPass(), llvm::initializeBranchProbabilityInfoWrapperPassPass(), llvm::initializeGCModuleInfoPass(), and llvm::initializeTargetLibraryInfoWrapperPassPass().
~SelectionDAGISel()
SelectionDAGISel::~SelectionDAGISel () override
Definition at line 325 of file SelectionDAGISel.cpp.
References CurDAG, FuncInfo, SDB, and SwiftError.
Member Function Documentation
CheckAndMask()
bool SelectionDAGISel::CheckAndMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an AND, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 1973 of file SelectionDAGISel.cpp.
References CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), llvm::APInt::isSubsetOf(), and llvm::SelectionDAG::MaskedValueIsZero().
Referenced by CheckAndImm().
CheckComplexPattern()
virtual bool llvm::SelectionDAGISel::CheckComplexPattern (SDNode * Root, SDNode * Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > & Result) inline virtual
Definition at line 285 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
CheckNodePredicate()
virtual bool llvm::SelectionDAGISel::CheckNodePredicate (SDNode * N, unsigned PredNo) const inline virtual
CheckNodePredicate - This function is generated by tblgen in the target.
It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 270 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckNodePredicate(), and SelectCodeCommon().
CheckNodePredicateWithOperands()
virtual bool llvm::SelectionDAGISel::CheckNodePredicateWithOperands (SDNode * N, unsigned PredNo, const SmallVectorImpl< SDValue > & Operands) const inline virtual
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 279 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
CheckOrMask()
bool SelectionDAGISel::CheckOrMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an OR, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 2002 of file SelectionDAGISel.cpp.
References llvm::SelectionDAG::computeKnownBits(), CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), llvm::APInt::isSubsetOf(), and llvm::KnownBits::One.
Referenced by CheckOrImm().
CheckPatternPredicate()
virtual bool llvm::SelectionDAGISel::CheckPatternPredicate (unsigned PredNo) const inline virtual
CheckPatternPredicate - This function is generated by tblgen in the target.
It runs the specified pattern predicate and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 262 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckPatternPredicate(), and SelectCodeCommon().
ComplexPatternFuncMutatesDAG()
virtual bool llvm::SelectionDAGISel::ComplexPatternFuncMutatesDAG () const inline virtual
Return true if complex patterns for this target can mutate the DAG.
Reimplemented in llvm::HexagonDAGToDAGISel.
Definition at line 300 of file SelectionDAGISel.h.
Referenced by SelectCodeCommon().
EmitFunctionEntryCode()
virtual void llvm::SelectionDAGISel::EmitFunctionEntryCode () inline virtual
Reimplemented in llvm::HexagonDAGToDAGISel.
Definition at line 78 of file SelectionDAGISel.h.
EnforceNodeIdInvariant()
void SelectionDAGISel::EnforceNodeIdInvariant (SDNode * N) static
Definition at line 1063 of file SelectionDAGISel.cpp.
References llvm::SmallVectorBase::empty(), InvalidateNodeId(), N, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by ReplaceNode(), and ReplaceUses().
getAnalysisUsage()
void SelectionDAGISel::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Reimplemented in llvm::MipsDAGToDAGISel.
Definition at line 332 of file SelectionDAGISel.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::CodeGenOpt::None, OptLevel, and UseMBPI.
Referenced by llvm::MipsDAGToDAGISel::getAnalysisUsage().
getIncludePathForIndex()
virtual StringRef llvm::SelectionDAGISel::getIncludePathForIndex (unsigned index) inline protected virtual
getIncludePathForIndex - get the td source location of pattern instantiation
Definition at line 247 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
getNumFixedFromVariadicInfo()
static int llvm::SelectionDAGISel::getNumFixedFromVariadicInfo (unsigned Flags) inline static
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Definition at line 197 of file SelectionDAGISel.h.
References OPFL_VariadicInfo.
Referenced by SelectCodeCommon().
getPatternForIndex()
virtual StringRef llvm::SelectionDAGISel::getPatternForIndex (unsigned index) inline protected virtual
getPatternForIndex - Patterns selected by tablegen during ISEL
Definition at line 242 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
getTargetLowering()
const TargetLowering * llvm::SelectionDAGISel::getTargetLowering () const inline
Definition at line 72 of file SelectionDAGISel.h.
References TLI.
Referenced by llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::AVRDAGToDAGISel::SelectAddr(), and llvm::AVRDAGToDAGISel::selectIndexedLoad().
getUninvalidatedNodeId()
int SelectionDAGISel::getUninvalidatedNodeId (SDNode * N) static
Definition at line 1088 of file SelectionDAGISel.cpp.
References N.
Referenced by insertDAGNode().
InvalidateNodeId()
void SelectionDAGISel::InvalidateNodeId (SDNode * N) static
Definition at line 1082 of file SelectionDAGISel.cpp.
References N.
Referenced by EnforceNodeIdInvariant(), and insertDAGNode().
IsLegalToFold()
bool SelectionDAGISel::IsLegalToFold (SDValue N, SDNode * U, SDNode * Root, CodeGenOpt::Level OptLevel, bool IgnoreChains = false) static
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
FIXME: This is a static member function because the MSP430/X86 targets, which uses it during isel. This could become a proper member.
Definition at line 2153 of file SelectionDAGISel.cpp.
References findGlueUse(), findNonImmUse(), llvm::SDNode::getNumValues(), llvm::SDNode::getValueType(), llvm::MVT::Glue, N, llvm::CodeGenOpt::None, and OptLevel.
Referenced by SelectCodeCommon().
isOrEquivalentToAdd()
bool SelectionDAGISel::isOrEquivalentToAdd (const SDNode * N) const
Definition at line 3621 of file SelectionDAGISel.cpp.
References A, assert(), C, llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::isPowerOf2_32(), MF, N, and llvm::ISD::OR.
IsProfitableToFold()
bool SelectionDAGISel::IsProfitableToFold (SDValue N, SDNode * U, SDNode * Root) const virtual
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
Definition at line 2145 of file SelectionDAGISel.cpp.
References N, llvm::CodeGenOpt::None, and OptLevel.
Referenced by SelectCodeCommon().
PostprocessISelDAG()
virtual void llvm::SelectionDAGISel::PostprocessISelDAG () inline virtual
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
Definition at line 86 of file SelectionDAGISel.h.
PreprocessISelDAG()
virtual void llvm::SelectionDAGISel::PreprocessISelDAG () inline virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Reimplemented in llvm::HexagonDAGToDAGISel.
Definition at line 82 of file SelectionDAGISel.h.
ReplaceNode()
void llvm::SelectionDAGISel::ReplaceNode (SDNode * F, SDNode * T) inline protected
Replace all uses of F with T, then remove F from the DAG.
Definition at line 230 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, llvm::SelectionDAG::RemoveDeadNode(), and llvm::SelectionDAG::ReplaceAllUsesWith().
Referenced by llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HvxSelector::selectShuffle(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), and llvm::HexagonDAGToDAGISel::SelectVAlignAddr().
ReplaceUses() [1/3]
void llvm::SelectionDAGISel::ReplaceUses (const SDValue * F, const SDValue * T, unsigned Num) inline protected
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
Definition at line 216 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and llvm::SelectionDAG::ReplaceAllUsesOfValuesWith().
ReplaceUses() [2/3]
void llvm::SelectionDAGISel::ReplaceUses (SDNode * F, SDNode * T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 224 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and llvm::SelectionDAG::ReplaceAllUsesWith().
ReplaceUses() [3/3]
void llvm::SelectionDAGISel::ReplaceUses (SDValue F, SDValue T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 209 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and llvm::SelectionDAG::ReplaceAllUsesOfValueWith().
Referenced by llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), and llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic().
runOnMachineFunction()
bool SelectionDAGISel::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::AVRDAGToDAGISel, llvm::HexagonDAGToDAGISel, llvm::MipsDAGToDAGISel, and llvm::NVPTXDAGToDAGISel.
Definition at line 410 of file SelectionDAGISel.cpp.
References AA, llvm::FunctionLoweringInfo::ArgDbgValues, assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::MachineBasicBlock::begin(), llvm::FunctionLoweringInfo::BPI, llvm::BuildMI(), llvm::Function::callsFunctionThatReturnsTwice(), llvm::FunctionLoweringInfo::clear(), computeUsesMSVCFloatingPoint(), CurDAG, llvm::dbgs(), llvm::LLVMContext::diagnose(), E, llvm::MachineRegisterInfo::EmitLiveInCopies(), llvm::TargetOptions::EnableFastISel, EnableFastISelAbort, EnableFastISelFallbackReport, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), FastISelFailed, llvm::TargetLoweringBase::finalizeLowering(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), From, llvm::MachineFunction::front(), FuncInfo, llvm::MCInstrInfo::get(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::Value::getName(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getProperties(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::TargetMachine::getTargetTriple(), llvm::MachineRegisterInfo::getVRegDef(), GFI, llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasGC(), llvm::MachineFunction::hasInlineAsm(), llvm::MachineFunctionProperties::hasProperty(), I, llvm::SelectionDAGBuilder::init(), llvm::SelectionDAG::init(), llvm::TargetLowering::initializeSplitCSR(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::TargetLowering::insertCopiesSplitCSR(), llvm::MCInstrDesc::isCall(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MCInstrDesc::isReturn(), llvm::TargetRegisterInfo::isVirtualRegister(), LibInfo, llvm::MachineRegisterInfo::liveins(), LLVM_DEBUG, MF, MI, MRI, llvm::CodeGenOpt::None, llvm::TargetMachine::Options, OptLevel, ORE, llvm::MachineFunction::print(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::FunctionLoweringInfo::RegFixups, RegInfo, llvm::TargetMachine::resetTargetOptions(), SDB, llvm::MachineFunctionProperties::Selected, llvm::FunctionLoweringInfo::set(), llvm::MachineFunction::setExposesReturnsTwice(), llvm::SwiftErrorValueTracking::setFunction(), llvm::MachineFrameInfo::setHasCalls(), llvm::MachineFunction::setHasInlineAsm(), llvm::FunctionPass::skipFunction(), SplitCriticalSideEffectEdges(), llvm::FunctionLoweringInfo::SplitCSR, llvm::succ_empty(), llvm::TargetLowering::supportSplitCSR(), SwiftError, TII, TLI, TM, TRI, llvm::MachineRegisterInfo::use_instr_begin(), llvm::MachineRegisterInfo::use_instr_end(), UseMBPI, UseMI, and llvm::TargetRegisterInfo::virtReg2Index().
Referenced by llvm::AVRDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), and llvm::NVPTXDAGToDAGISel::runOnMachineFunction().
RunSDNodeXForm()
virtual SDValue llvm::SelectionDAGISel::RunSDNodeXForm (SDValue V, unsigned XFormNo) inline virtual
Definition at line 291 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
Select()
virtual void llvm::SelectionDAGISel::Select (SDNode * N) pure virtual
Main hook for targets to transform nodes into machine nodes.
Implemented in llvm::HexagonDAGToDAGISel.
SelectCodeCommon()
void SelectionDAGISel::SelectCodeCommon (SDNode * NodeToMatch, const unsigned char * MatcherTable, unsigned TableSize)
Definition at line 2750 of file SelectionDAGISel.cpp.
References llvm::ISD::ANNOTATION_LABEL, llvm::SmallVectorImpl< T >::append(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::ISD::BasicBlock, llvm::SmallVectorTemplateCommon< T, typename >::begin(), CheckAndImm(), CheckChild2CondCode(), CheckChildInteger(), CheckChildSame(), CheckChildType(), CheckComplexPattern(), CheckCondCode(), CheckInteger(), CheckNodePredicate(), CheckNodePredicateWithOperands(), CheckOpcode(), CheckOrImm(), CheckPatternPredicate(), CheckSame(), CheckType(), CheckValueType(), llvm::SmallVectorImpl< T >::clear(), ComplexPatternFuncMutatesDAG(), llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, CurDAG, llvm::dbgs(), llvm::ISD::DELETED_NODE, llvm::SDNode::dump(), E, llvm::ISD::EH_LABEL, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::EntryToken, first, llvm::MCInstrInfo::get(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), getIncludePathForIndex(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), getNumFixedFromVariadicInfo(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), getPatternForIndex(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetConstantFP(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), GetVBR(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, HandleMergeInputChains(), llvm::ISD::HANDLENODE, hasOneUse(), Idx, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::MVT::iPTR, llvm::is_contained(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), IsLegalToFold(), llvm::SDNode::isMachineOpcode(), IsPredicateKnownToFail(), IsProfitableToFold(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, LLVM_DEBUG, llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), llvm::ISD::MCSymbol, llvm::ISD::MDNODE_SDNODE, llvm::MachineSDNode::memoperands_empty(), N, OPC_CaptureGlueInput, OPC_CheckAndImm, OPC_CheckChild0Integer, OPC_CheckChild0Same, OPC_CheckChild0Type, OPC_CheckChild1Integer, OPC_CheckChild1Same, OPC_CheckChild1Type, OPC_CheckChild2CondCode, OPC_CheckChild2Integer, OPC_CheckChild2Same, OPC_CheckChild2Type, OPC_CheckChild3Integer, OPC_CheckChild3Same, OPC_CheckChild3Type, OPC_CheckChild4Integer, OPC_CheckChild4Type, OPC_CheckChild5Type, OPC_CheckChild6Type, OPC_CheckChild7Type, OPC_CheckComplexPat, OPC_CheckCondCode, OPC_CheckFoldableChainNode, OPC_CheckImmAllOnesV, OPC_CheckImmAllZerosV, OPC_CheckInteger, OPC_CheckOpcode, OPC_CheckOrImm, OPC_CheckPatternPredicate, OPC_CheckPredicate, OPC_CheckPredicateWithOperands, OPC_CheckSame, OPC_CheckType, OPC_CheckTypeRes, OPC_CheckValueType, OPC_CompleteMatch, OPC_Coverage, OPC_EmitConvertToTarget, OPC_EmitCopyToReg, OPC_EmitInteger, OPC_EmitMergeInputChains, OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitMergeInputChains1_2, OPC_EmitNode, OPC_EmitNode0, OPC_EmitNode1, OPC_EmitNode2, OPC_EmitNodeXForm, OPC_EmitRegister, OPC_EmitRegister2, OPC_MorphNodeTo, OPC_MorphNodeTo0, OPC_MorphNodeTo1, OPC_MorphNodeTo2, OPC_MoveChild, OPC_MoveChild0, OPC_MoveChild1, OPC_MoveChild2, OPC_MoveChild3, OPC_MoveChild4, OPC_MoveChild5, OPC_MoveChild6, OPC_MoveChild7, OPC_MoveParent, OPC_RecordChild0, OPC_RecordChild1, OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5, OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_RecordNode, OPC_Scope, OPC_SwitchOpcode, OPC_SwitchType, OPFL_Chain, OPFL_GlueInput, OPFL_GlueOutput, OPFL_MemRefs, OPFL_VariadicInfo, OptLevel, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::READ_REGISTER, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::SelectionDAG::RemoveDeadNode(), ReplaceUses(), llvm::SmallVectorImpl< T >::resize(), RunSDNodeXForm(), llvm::SelectionDAG::salvageDebugInfo(), second, llvm::SDNode::setNodeId(), llvm::SelectionDAG::setNodeMemRefs(), llvm::SmallVectorBase::size(), llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, TII, TLI, llvm::ISD::TokenFactor, llvm::ISD::UNDEF, llvm::SDNode::use_empty(), and llvm::ISD::WRITE_REGISTER.
SelectInlineAsmMemoryOperand()
virtual bool llvm::SelectionDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, unsigned ConstraintID, std::vector< SDValue > & OutOps) inline virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Reimplemented in llvm::AVRDAGToDAGISel, llvm::HexagonDAGToDAGISel, and llvm::NVPTXDAGToDAGISel.
Definition at line 96 of file SelectionDAGISel.h.
Referenced by SelectInlineAsmMemoryOperands().
SelectInlineAsmMemoryOperands()
void SelectionDAGISel::SelectInlineAsmMemoryOperands (std::vector< SDValue > & Ops, const SDLoc & DL) protected
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
Others should not call it.
Definition at line 2032 of file SelectionDAGISel.cpp.
References assert(), CurDAG, llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMem(), llvm::InlineAsm::getMemoryConstraintID(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::Glue, llvm::MVT::i32, llvm::InlineAsm::isMemKind(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Op_AsmString, llvm::InlineAsm::Op_ExtraInfo, llvm::InlineAsm::Op_FirstOperand, llvm::InlineAsm::Op_InputChain, llvm::InlineAsm::Op_MDNode, llvm::report_fatal_error(), SelectInlineAsmMemoryOperand(), and std::swap().
Member Data Documentation
AA
AliasAnalysis* llvm::SelectionDAGISel::AA
Definition at line 54 of file SelectionDAGISel.h.
Referenced by llvm::createVLIWDAGScheduler(), runOnMachineFunction(), and llvm::HexagonDAGToDAGISel::SelectVAlignAddr().
CurDAG
SelectionDAG* llvm::SelectionDAGISel::CurDAG
Definition at line 52 of file SelectionDAGISel.h.
Referenced by CheckAndMask(), CheckOrMask(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), IsPredicateKnownToFail(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::HexagonDAGToDAGISel::PreprocessISelDAG(), ReplaceNode(), ReplaceUses(), runOnMachineFunction(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectAnyImmediate(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectGlobalAddress(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), SelectInlineAsmMemoryOperands(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), and ~SelectionDAGISel().
DAGSize
unsigned llvm::SelectionDAGISel::DAGSize protected
DAGSize - Size of DAG being instruction selected.
Definition at line 205 of file SelectionDAGISel.h.
ElidedArgCopyInstrs
SmallPtrSet<const Instruction *, 4> llvm::SelectionDAGISel::ElidedArgCopyInstrs
Definition at line 60 of file SelectionDAGISel.h.
FastISelFailed
bool llvm::SelectionDAGISel::FastISelFailed
Definition at line 59 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
FuncInfo
FunctionLoweringInfo* llvm::SelectionDAGISel::FuncInfo
Definition at line 48 of file SelectionDAGISel.h.
Referenced by llvm::HexagonDAGToDAGISel::EmitFunctionEntryCode(), runOnMachineFunction(), and ~SelectionDAGISel().
GFI
GCFunctionInfo* llvm::SelectionDAGISel::GFI
Definition at line 55 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
ID
char SelectionDAGISel::ID = 0 static
Definition at line 66 of file SelectionDAGISel.h.
LibInfo
const TargetLibraryInfo* llvm::SelectionDAGISel::LibInfo
Definition at line 47 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
MF
MachineFunction* llvm::SelectionDAGISel::MF
Definition at line 50 of file SelectionDAGISel.h.
Referenced by llvm::createBURRListDAGScheduler(), llvm::createDAGLinearizer(), llvm::createDefaultScheduler(), llvm::createFastDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::createVLIWDAGScheduler(), llvm::HexagonDAGToDAGISel::EmitFunctionEntryCode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), isOrEquivalentToAdd(), llvm::OptLevelChanger::OptLevelChanger(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), llvm::AVRDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), and llvm::OptLevelChanger::~OptLevelChanger().
OptLevel
CodeGenOpt::Level llvm::SelectionDAGISel::OptLevel
Definition at line 56 of file SelectionDAGISel.h.
Referenced by getAnalysisUsage(), IsLegalToFold(), IsProfitableToFold(), llvm::NVPTXDAGToDAGISel::NVPTXDAGToDAGISel(), llvm::OptLevelChanger::OptLevelChanger(), runOnMachineFunction(), SelectCodeCommon(), and llvm::OptLevelChanger::~OptLevelChanger().
ORE
std::unique_ptr<OptimizationRemarkEmitter> llvm::SelectionDAGISel::ORE
Current optimization remark emitter.
Used to report things like combines and FastISel failures.
Definition at line 64 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
RegInfo
MachineRegisterInfo* llvm::SelectionDAGISel::RegInfo
Definition at line 51 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
SDB
SelectionDAGBuilder* llvm::SelectionDAGISel::SDB
Definition at line 53 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and ~SelectionDAGISel().
SwiftError
SwiftErrorValueTracking* llvm::SelectionDAGISel::SwiftError
Definition at line 49 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and ~SelectionDAGISel().
TII
const TargetInstrInfo* llvm::SelectionDAGISel::TII
Definition at line 57 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and SelectCodeCommon().
TLI
const TargetLowering* llvm::SelectionDAGISel::TLI
Definition at line 58 of file SelectionDAGISel.h.
Referenced by llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), getTargetLowering(), IsPredicateKnownToFail(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), and SelectCodeCommon().
TM
TargetMachine& llvm::SelectionDAGISel::TM
Definition at line 46 of file SelectionDAGISel.h.
Referenced by llvm::OptLevelChanger::OptLevelChanger(), runOnMachineFunction(), and llvm::OptLevelChanger::~OptLevelChanger().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGISel.h
lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp