LLVM: llvm::SmallVectorBase Class Reference
llvm::SmallVectorBase Class Reference
This is all the non-templated stuff common to all SmallVectors.
#include "llvm/ADT/SmallVector.h"
Inherited by llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >, llvm::SmallVectorTemplateCommon< BasicBlock * >, llvm::SmallVectorTemplateCommon< BlockT * >, llvm::SmallVectorTemplateCommon< BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateCommon< llvm::MCFixup >, llvm::SmallVectorTemplateCommon< char >, llvm::SmallVectorTemplateCommon< llvm::cl::parser::OptionInfo >, llvm::SmallVectorTemplateCommon< std::pair< KeyT, ValueT > >, llvm::SmallVectorTemplateCommon< ScheduleData * >, llvm::SmallVectorTemplateCommon< Instruction * >, llvm::SmallVectorTemplateCommon< llvm::SUnit * >, llvm::SmallVectorTemplateCommon< LoopVector >, llvm::SmallVectorTemplateCommon< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorTemplateCommon< AllocaInfo >, llvm::SmallVectorTemplateCommon< ParamInfo >, llvm::SmallVectorTemplateCommon< CallInst * >, llvm::SmallVectorTemplateCommon< unsigned >, llvm::SmallVectorTemplateCommon< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults) >, llvm::SmallVectorTemplateCommon< llvm::ForwardedRegister >, llvm::SmallVectorTemplateCommon< MILOHDirective >, llvm::SmallVectorTemplateCommon< const llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorTemplateCommon< llvm::BasicBlockInfo >, llvm::SmallVectorTemplateCommon< FCmpLibcallsList >, llvm::SmallVectorTemplateCommon< int >, llvm::SmallVectorTemplateCommon< MCPhysReg >, llvm::SmallVectorTemplateCommon< AnalysisID >, llvm::SmallVectorTemplateCommon< std::pair< AtomType, Form > >, llvm::SmallVectorTemplateCommon< FreeList * >, llvm::SmallVectorTemplateCommon< llvm::AsmPrinter::HandlerInfo >, llvm::SmallVectorTemplateCommon< llvm::AsmPrinter::XRayFunctionEntry >, llvm::SmallVectorTemplateCommon< llvm::WeakTrackingVH >, llvm::SmallVectorTemplateCommon< AbstractAttribute * >, llvm::SmallVectorTemplateCommon< VariableGEPIndex >, llvm::SmallVectorTemplateCommon< llvm::BitCodeAbbrevOp >, llvm::SmallVectorTemplateCommon< BitValue >, llvm::SmallVectorTemplateCommon< Block >, llvm::SmallVectorTemplateCommon< Weight >, llvm::SmallVectorTemplateCommon< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorTemplateCommon< BlockNode >, llvm::SmallVectorTemplateCommon< BlockMass >, llvm::SmallVectorTemplateCommon< std::string >, llvm::SmallVectorTemplateCommon< void * >, llvm::SmallVectorTemplateCommon< std::pair< void *, size_t > >, llvm::SmallVectorTemplateCommon< llvm::CCValAssign >, llvm::SmallVectorTemplateCommon< uint32_t >, llvm::SmallVectorTemplateCommon< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorTemplateCommon< ByValInfo >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::RefSCC * >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorTemplateCommon< llvm::Register >, llvm::SmallVectorTemplateCommon< FileInfo >, llvm::SmallVectorTemplateCommon< CVGlobalVariable >, llvm::SmallVectorTemplateCommon< const llvm::DISubprogram * >, llvm::SmallVectorTemplateCommon< const llvm::DICompositeType * >, llvm::SmallVectorTemplateCommon< const llvm::DILocation * >, llvm::SmallVectorTemplateCommon< LocalVariable >, llvm::SmallVectorTemplateCommon< LexicalBlock * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * > >, llvm::SmallVectorTemplateCommon< LocalVarDefRange >, llvm::SmallVectorTemplateCommon< consthoist::ConstantInfo >, llvm::SmallVectorTemplateCommon< ConstantPoolEntry >, llvm::SmallVectorTemplateCommon< llvm::SDNode * >, llvm::SmallVectorTemplateCommon< llvm::Metadata * >, llvm::SmallVectorTemplateCommon< llvm::TypedTrackingMDRef >, llvm::SmallVectorTemplateCommon< llvm::DIEAbbrevData >, llvm::SmallVectorTemplateCommon< llvm::DILineInfo >, llvm::SmallVectorTemplateCommon< AttributeSpec >, llvm::SmallVectorTemplateCommon< llvm::DWARFFormValue >, llvm::SmallVectorTemplateCommon< LocationList >, llvm::SmallVectorTemplateCommon< llvm::DWARFDebugLoc::Entry >, llvm::SmallVectorTemplateCommon< llvm::DWARFDebugLoclists::Entry >, llvm::SmallVectorTemplateCommon< Entry >, llvm::SmallVectorTemplateCommon< llvm::DWARFDebugNames::NameIndex >, llvm::SmallVectorTemplateCommon< CompUnitEntry >, llvm::SmallVectorTemplateCommon< TypeUnitEntry >, llvm::SmallVectorTemplateCommon< AddressEntry >, llvm::SmallVectorTemplateCommon< SymTableEntry >, llvm::SmallVectorTemplateCommon< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > > >, llvm::SmallVectorTemplateCommon< unsigned char >, llvm::SmallVectorTemplateCommon< LayoutAlignElem >, llvm::SmallVectorTemplateCommon< PointerAlignElem >, llvm::SmallVectorTemplateCommon< FrameIndexExpr >, llvm::SmallVectorTemplateCommon< int64_t >, llvm::SmallVectorTemplateCommon< llvm::DICompileUnit * >, llvm::SmallVectorTemplateCommon< llvm::DISubprogram * >, llvm::SmallVectorTemplateCommon< llvm::DIGlobalVariableExpression * >, llvm::SmallVectorTemplateCommon< llvm::DIType * >, llvm::SmallVectorTemplateCommon< llvm::DIScope * >, llvm::SmallVectorTemplateCommon< llvm::DbgValueLoc >, llvm::SmallVectorTemplateCommon< llvm::DebugLocStream::List >, llvm::SmallVectorTemplateCommon< llvm::DebugLocStream::Entry >, llvm::SmallVectorTemplateCommon< llvm::Init * >, llvm::SmallVectorTemplateCommon< llvm::DiagnosticInfoOptimizationBase::Argument >, llvm::SmallVectorTemplateCommon< UpdateT >, llvm::SmallVectorTemplateCommon< NodePtr >, llvm::SmallVectorTemplateCommon< llvm::DomTreeNodeBase >, llvm::SmallVectorTemplateCommon< llvm::cfg::Update >, llvm::SmallVectorTemplateCommon< llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< NodeT * >, llvm::SmallVectorTemplateCommon< llvm::RangeSpan >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DbgEntity > >, llvm::SmallVectorTemplateCommon< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * > >, llvm::SmallVectorTemplateCommon< llvm::DwarfExpression::Register >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DwarfCompileUnit > >, llvm::SmallVectorTemplateCommon< llvm::RangeSpanList >, llvm::SmallVectorTemplateCommon< llvm::DbgVariable * >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorTemplateCommon< llvm::Function * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GlobalVariable > >, llvm::SmallVectorTemplateCommon< llvm::DomainValue * >, llvm::SmallVectorTemplateCommon< LiveRegsDVInfo >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::Module > >, llvm::SmallVectorTemplateCommon< llvm::Value * >, llvm::SmallVectorTemplateCommon< llvm::ISD::InputArg >, llvm::SmallVectorTemplateCommon< std::pair< std::string, GCOVCoverage > >, llvm::SmallVectorTemplateCommon< T * >, llvm::SmallVectorTemplateCommon< llvm::FunctionLoweringInfo::LiveOutInfo >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCStrategy > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator > >, llvm::SmallVectorTemplateCommon< llvm::DenseMap >, llvm::SmallVectorTemplateCommon< llvm::GCNRegPressure >, llvm::SmallVectorTemplateCommon< llvm::GCOVEdge * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVEdge > >, llvm::SmallVectorTemplateCommon< llvm::GISelChangeObserver * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Value *, llvm::Constant * > >, llvm::SmallVectorTemplateCommon< llvm::Instruction * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, unsigned > >, llvm::SmallVectorTemplateCommon< llvm::BasicBlock * >, llvm::SmallVectorTemplateCommon< MCOperand >, llvm::SmallVectorTemplateCommon< HexagonInstr >, llvm::SmallVectorTemplateCommon< NodeTy * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > > >, llvm::SmallVectorTemplateCommon< InlineGraphNode * >, llvm::SmallVectorTemplateCommon< uintptr_t >, llvm::SmallVectorTemplateCommon< const char * >, llvm::SmallVectorTemplateCommon< llvm::AllocaInst * >, llvm::SmallVectorTemplateCommon< llvm::CallSite >, llvm::SmallVectorTemplateCommon< llvm::PHINode * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorTemplateCommon< MachineInstr * >, llvm::SmallVectorTemplateCommon< RegUnitInfo >, llvm::SmallVectorTemplateCommon< BlockInterference >, llvm::SmallVectorTemplateCommon< llvm::AssertingVH< const llvm::BasicBlock > >, llvm::SmallVectorTemplateCommon< llvm::Loop * >, llvm::SmallVectorTemplateCommon< llvm::MCSymbol * >, llvm::SmallVectorTemplateCommon< llvm::SEHHandler >, llvm::SmallVectorTemplateCommon< Edge >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::Node * >, llvm::SmallVectorTemplateCommon< llvm::LegalizeRule >, llvm::SmallVectorTemplateCommon< SizeChangeStrategy >, llvm::SmallVectorTemplateCommon< SizeAndActionsVec >, llvm::SmallVectorTemplateCommon< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorTemplateCommon< llvm::LexicalScope * >, llvm::SmallVectorTemplateCommon< InsnRange >, llvm::SmallVectorTemplateCommon< llvm::LiveInterval * >, llvm::SmallVectorTemplateCommon< llvm::SlotIndex >, llvm::SmallVectorTemplateCommon< const uint32_t * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, unsigned > >, llvm::SmallVectorTemplateCommon< llvm::LiveRange * >, llvm::SmallVectorTemplateCommon< Segment >, llvm::SmallVectorTemplateCommon< VNInfo * >, llvm::SmallVectorTemplateCommon< LiveOutPair >, llvm::SmallVectorTemplateCommon< LiveInBlock >, llvm::SmallVectorTemplateCommon< llvm::LiveRange::Segment >, llvm::SmallVectorTemplateCommon< IndexMaskPair >, llvm::SmallVectorTemplateCommon< llvm::LiveVariables::VarInfo >, llvm::SmallVectorTemplateCommon< MBBInfo >, llvm::SmallVectorTemplateCommon< VPlanPtr >, llvm::SmallVectorTemplateCommon< RuntimePointerChecking::PointerCheck >, llvm::SmallVectorTemplateCommon< llvm::MCSection * >, llvm::SmallVectorTemplateCommon< llvm::AsmToken >, llvm::SmallVectorTemplateCommon< llvm::MCAsmParser::MCPendingError >, llvm::SmallVectorTemplateCommon< llvm::MCDwarfFile >, llvm::SmallVectorTemplateCommon< llvm::MCDataFragment * >, llvm::SmallVectorTemplateCommon< llvm::MCOperand >, llvm::SmallVectorTemplateCommon< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorTemplateCommon< llvm::MCLOHDirective >, llvm::SmallVectorTemplateCommon< PendingMCFixup >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorTemplateCommon< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::TypedTrackingMDRef > >, llvm::SmallVectorTemplateCommon< Attachment >, llvm::SmallVectorTemplateCommon< llvm::StringRef >, llvm::SmallVectorTemplateCommon< llvm::MachineBasicBlock * >, llvm::SmallVectorTemplateCommon< CriticalEdge >, llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >, llvm::SmallVectorTemplateCommon< VariableDbgInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineOperand >, llvm::SmallVectorTemplateCommon< std::pair< llvm::PointerUnion, llvm::MachineOperand * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::SmallVector< unsigned, 4 > > >, llvm::SmallVectorTemplateCommon< LLT >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorTemplateCommon< std::string * >, llvm::SmallVectorTemplateCommon< llvm::MemoryDepChecker::Dependence >, llvm::SmallVectorTemplateCommon< DefPath >, llvm::SmallVectorTemplateCommon< llvm::WeakVH >, llvm::SmallVectorTemplateCommon< llvm::AssertingVH< llvm::MemoryPhi > >, llvm::SmallVectorTemplateCommon< Inst >, llvm::SmallVectorTemplateCommon< bool >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorTemplateCommon< const llvm::Value * >, llvm::SmallVectorTemplateCommon< llvm::Pass * >, llvm::SmallVectorTemplateCommon< llvm::PMDataManager * >, llvm::SmallVectorTemplateCommon< llvm::ImmutablePass * >, llvm::SmallVectorTemplateCommon< llvm::AsmRewrite >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::PassManager &, OptimizationLevel)> >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::PassManager &)> >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::AnalysisManager &)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >, bool VerifyEachPass, bool DebugLogging)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)> >, llvm::SmallVectorTemplateCommon< InsertedPass >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforePassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterPassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterPassInvalidatedFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforeAnalysisFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterAnalysisFunc > >, llvm::SmallVectorTemplateCommon< ValueInfo >, llvm::SmallVectorTemplateCommon< llvm::AssertingVH< llvm::Function > >, llvm::SmallVectorTemplateCommon< llvm::PredicateBase * >, llvm::SmallVectorTemplateCommon< PrintModuleDesc >, llvm::SmallVectorTemplateCommon< llvm::Type * >, llvm::SmallVectorTemplateCommon< LiveRegsDefInfo >, llvm::SmallVectorTemplateCommon< MBBDefsInfo >, llvm::SmallVectorTemplateCommon< llvm::SMLoc >, llvm::SmallVectorTemplateCommon< llvm::RecordVal >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Record *, llvm::SMRange > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< InsertPoint > >, llvm::SmallVectorTemplateCommon< ScavengedInfo >, llvm::SmallVectorTemplateCommon< llvm::RegisterMaskPair >, llvm::SmallVectorTemplateCommon< llvm::EVT >, llvm::SmallVectorTemplateCommon< llvm::MVT >, llvm::SmallVectorTemplateCommon< uint64_t >, llvm::SmallVectorTemplateCommon< SID >, llvm::SmallVectorTemplateCommon< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >, llvm::SmallVectorTemplateCommon< SectionEntry >, llvm::SmallVectorTemplateCommon< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorTemplateCommon< llvm::RuntimePointerChecking::PointerInfo >, llvm::SmallVectorTemplateCommon< llvm::RuntimePointerChecking::CheckingPtrGroup >, llvm::SmallVectorTemplateCommon< PointerCheck >, llvm::SmallVectorTemplateCommon< SCEVInsertPointGuard * >, llvm::SmallVectorTemplateCommon< const llvm::SCEV * >, llvm::SmallVectorTemplateCommon< const llvm::SCEVPredicate * >, llvm::SmallVectorTemplateCommon< llvm::SDDbgValue * >, llvm::SmallVectorTemplateCommon< llvm::SDDbgLabel * >, llvm::SmallVectorTemplateCommon< llvm::SIMachineFunctionInfo::SGPRSpillVGPRCSR >, llvm::SmallVectorTemplateCommon< llvm::SMFixIt >, llvm::SmallVectorTemplateCommon< llvm::SelectInst * >, llvm::SmallVectorTemplateCommon< RewriteInfo >, llvm::SmallVectorTemplateCommon< llvm::Use * >, llvm::SmallVectorTemplateCommon< PhiT * >, llvm::SmallVectorTemplateCommon< llvm::SDep >, llvm::SmallVectorTemplateCommon< ExitNotTakenInfo >, llvm::SmallVectorTemplateCommon< RootData >, llvm::SmallVectorTemplateCommon< TreeData >, llvm::SmallVectorTemplateCommon< SMSNode >, llvm::SmallVectorTemplateCommon< std::pair< llvm::SUnit *, llvm::SUnit * > >, llvm::SmallVectorTemplateCommon< llvm::sys::MemoryBlock >, llvm::SmallVectorTemplateCommon< FreeMemBlock >, llvm::SmallVectorTemplateCommon< llvm::SDValue >, llvm::SmallVectorTemplateCommon< const llvm::GCRelocateInst * >, llvm::SmallVectorTemplateCommon< IdxMBBPair >, llvm::SmallVectorTemplateCommon< ValueT >, llvm::SmallVectorTemplateCommon< llvm::BlockFrequency >, llvm::SmallVectorTemplateCommon< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorTemplateCommon< Location >, llvm::SmallVectorTemplateCommon< LiveOutReg >, llvm::SmallVectorTemplateCommon< const llvm::CallInst * >, llvm::SmallVectorTemplateCommon< const Value * >, llvm::SmallVectorTemplateCommon< llvm::SmallPtrSet< llvm::SUnit *, 4 > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< int, 4 > >, llvm::SmallVectorTemplateCommon< BitTestCase >, llvm::SmallVectorTemplateCommon< llvm::DefsetRecord * >, llvm::SmallVectorTemplateCommon< llvm::ISD::OutputArg >, llvm::SmallVectorTemplateCommon< llvm::Timer * >, llvm::SmallVectorTemplateCommon< llvm::Entry >, llvm::SmallVectorTemplateCommon< llvm::TruncInst * >, llvm::SmallVectorTemplateCommon< uint8_t >, llvm::SmallVectorTemplateCommon< llvm::VPBlockBase * >, llvm::SmallVectorTemplateCommon< llvm::VPBasicBlock * >, llvm::SmallVectorTemplateCommon< llvm::VPValue * >, llvm::SmallVectorTemplateCommon< llvm::VPUser * >, llvm::SmallVectorTemplateCommon< VPBlockBase * >, llvm::SmallVectorTemplateCommon< MultiNodeOpTy >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, bool > >, llvm::SmallVectorTemplateCommon< llvm::CxxUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::WinEHTryBlockMapEntry >, llvm::SmallVectorTemplateCommon< llvm::SEHUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::ClrEHUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::WinEHHandlerType >, llvm::SmallVectorTemplateCommon< llvm::cflaa::ExternalRelation >, llvm::SmallVectorTemplateCommon< llvm::cflaa::ExternalAttribute >, llvm::SmallVectorTemplateCommon< llvm::cl::OptionCategory * >, llvm::SmallVectorTemplateCommon< llvm::cl::Option * >, llvm::SmallVectorTemplateCommon< llvm::cl::OptionEnumValue >, llvm::SmallVectorTemplateCommon< llvm::ArrayRef< uint8_t > >, llvm::SmallVectorTemplateCommon< llvm::codeview::TypeIndex >, llvm::SmallVectorTemplateCommon< RecordLimit >, llvm::SmallVectorTemplateCommon< llvm::codeview::GloballyHashedType >, llvm::SmallVectorTemplateCommon< std::pair< uint32_t, llvm::codeview::TypeIndex > >, llvm::SmallVectorTemplateCommon< ConstantUser >, llvm::SmallVectorTemplateCommon< RebasedConstantInfo >, llvm::SmallVectorTemplateCommon< llvm::CoroEndInst * >, llvm::SmallVectorTemplateCommon< llvm::CoroSizeInst * >, llvm::SmallVectorTemplateCommon< llvm::CoroSuspendInst * >, llvm::SmallVectorTemplateCommon< const llvm::coverage::CoverageSegment * >, llvm::SmallVectorTemplateCommon< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorTemplateCommon< llvm::fuzzerop::SourcePred >, llvm::SmallVectorTemplateCommon< State >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::HardwareUnit > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::Instruction > >, llvm::SmallVectorTemplateCommon< llvm::mca::WriteDescriptor >, llvm::SmallVectorTemplateCommon< llvm::mca::ReadDescriptor >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, llvm::mca::ResourceUsage > >, llvm::SmallVectorTemplateCommon< llvm::mca::WriteState >, llvm::SmallVectorTemplateCommon< llvm::mca::ReadState >, llvm::SmallVectorTemplateCommon< std::pair< ResourceRef, llvm::mca::ResourceCycles > >, llvm::SmallVectorTemplateCommon< llvm::mca::MemoryGroup * >, llvm::SmallVectorTemplateCommon< llvm::mca::InstRef >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::Stage > >, llvm::SmallVectorTemplateCommon< RegisterMappingTracker >, llvm::SmallVectorTemplateCommon< std::pair< llvm::mca::ReadState *, int > >, llvm::SmallVectorTemplateCommon< SectionInfo >, llvm::SmallVectorTemplateCommon< NodeState >, llvm::SmallVectorTemplateCommon< LoadCommandInfo >, llvm::SmallVectorTemplateCommon< StringRef >, llvm::SmallVectorTemplateCommon< Arg * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorTemplateCommon< InjectedSourceDescriptor >, llvm::SmallVectorTemplateCommon< size_t >, llvm::SmallVectorTemplateCommon< llvm::remarks::Argument >, llvm::SmallVectorTemplateCommon< llvm::safestack::StackColoring::LiveRange >, llvm::SmallVectorTemplateCommon< StackRegion >, llvm::SmallVectorTemplateCommon< StackObject >, llvm::SmallVectorTemplateCommon< const SamplesWithLoc * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< TreeEntry > >, llvm::SmallVectorTemplateCommon< unique_value >, llvm::SmallVectorTemplateCommon< ExternalUser >, llvm::SmallVectorTemplateCommon< Value * >, llvm::SmallVectorTemplateCommon< llvm::slpvectorizer::BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateCommon< SmallVector< Value *, 8 > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector >, llvm::SmallVectorTemplateCommon< Slice >, llvm::SmallVectorTemplateCommon< Slice * >, llvm::SmallVectorTemplateCommon< IntrusiveRefCntPtr< FileSystem > >, llvm::SmallVectorTemplateCommon< ValType >, llvm::SmallVectorTemplateCommon< TrieNode * >, llvm::SmallVectorTemplateCommon< SimpleKey >, and llvm::SmallVectorTemplateCommon< T, typename >.
Public Member Functions
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Protected Member Functions
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void grow_pod (void *FirstEl, size_t MinCapacity, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Protected Attributes
void * BeginX
unsigned Size = 0
unsigned Capacity
Detailed Description
This is all the non-templated stuff common to all SmallVectors.
Definition at line 38 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorBase() [1/2]
llvm::SmallVectorBase::SmallVectorBase () protected delete
SmallVectorBase() [2/2]
llvm::SmallVectorBase::SmallVectorBase (void * FirstEl, size_t TotalCapacity) inline protected
Definition at line 44 of file SmallVector.h.
Member Function Documentation
capacity()
size_t llvm::SmallVectorBase::capacity () const inline
Definition at line 53 of file SmallVector.h.
References Capacity.
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorTemplateCommon< T, typename >::capacity_in_bytes(), llvm::SmallVectorImpl< T >::emplace_back(), grow_pod(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), set_size(), and llvm::SmallVectorImpl< T >::swap().
empty()
LLVM_NODISCARD bool llvm::SmallVectorBase::empty () const inline
Definition at line 55 of file SmallVector.h.
References Size.
Referenced by llvm::PMDataManager::add(), AddAliasScopeMetadata(), addAllGlobalValueUsers(), addBlockAndPredsToSet(), addBoundsChecking(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::DbgVariable::addMMIEntry(), addRange(), AddReachableCodeToWorklist(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), advanceToNextLeafType(), llvm::LegalizeRuleSet::aliasTo(), llvm::AllocationOrder::AllocationOrder(), allUsersAreInFunction(), llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::LanaiInstrInfo::analyzeBranch(), analyzeLoopUnrollCost(), llvm::Annotations::Annotations(), llvm::LiveRange::append(), llvm::sys::path::append(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::A57ChainingConstraint::apply(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::MemorySSAUpdater::applyUpdates(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atEnd(), llvm::SmallVectorTemplateCommon< T, typename >::back(), BatchCommitValueTo(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), llvm::coro::buildCoroutineFrame(), buildGEP(), buildMultiplyTree(), CalcNodeSethiUllmanNumber(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), canonicalizePHIOperands(), canPaddingBeAccessed(), llvm::canPeel(), canRewriteGEPAsOffset(), llvm::TailDuplicator::canTailDuplicate(), canUseReferenceType(), CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), checkClobberSanity(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), CleanupConstantGlobalUsers(), llvm::ArrayRecycler< T, Align >::clear(), clearAssumptionsOfUsers(), cloneLoopNest(), collectCastsToIgnore(), collectConcatOps(), collectEHScopeMembers(), collectHomogenousInstGraphLoopInvariants(), collectTransitivePredecessors(), llvm::colorEHFunclets(), combineRedundantDWordShuffle(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::FunctionComparator::compare(), llvm::ScalarEvolution::computeAccessFunctions(), computeBlocksDominatingExits(), llvm::computeDeadSymbols(), llvm::MCCodePaddingPolicy::computeFirstWindowPenaltyWeight(), ComputeImportForModule(), ComputeLiveInBlocks(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), ComputePostOrders(), llvm::MCCodePaddingPolicy::computeRangePenaltyWeight(), computeUnlikelySuccessors(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), computeVariableSummary(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::ConstantFoldGetElementPtr(), ConstHasGlobalValuePredicate(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), llvm::convertUTF8ToUTF16String(), CrashHandler(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), deleteDeadBlocksFromLoop(), deleteDeadInstruction(), DeleteTriviallyDeadInstructions(), llvm::ScalarEvolution::delinearize(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), llvm::dwarf::CIE::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::SMSchedule::earliestCycleInChain(), llvm::LiveRangeEdit::eliminateDeadDefs(), eliminateDeadSwitchCases(), llvm::EmitAnyX86InstComments(), llvm::ConstantPool::emitEntries(), llvm::PPCFrameLowering::emitEpilogue(), llvm::CodeViewContext::emitFileChecksums(), EmitGenDwarfInfo(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::PPCFrameLowering::emitPrologue(), llvm::AsmPrinter::emitRemarksSection(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::ConstantPool::empty(), llvm::PriorityWorklist< T, VectorT, MapT >::empty(), llvm::SmallSet< T, N, C >::empty(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::empty(), llvm::LiveRange::empty(), llvm::SDDbgInfo::empty(), llvm::DWARFDebugMacro::empty(), llvm::MDAttachmentMap::empty(), llvm::MDGlobalAttachmentMap::empty(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), eraseDeadBBsAndChildren(), llvm::VPBasicBlock::execute(), llvm::InstructionSelector::executeMatchTable(), explicifyGuards(), llvm::DIBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::CodeExtractor::findAllocas(), llvm::ScalarEvolution::findArrayDimensions(), findBasePointer(), llvm::rdf::FuncNode::findBlock(), llvm::objcarc::FindDependencies(), llvm::findDevirtualizableCallsForTypeTest(), llvm::FindFunctionBackedges(), FindMostPopularDest(), findProfitablePHIs(), findRefEdges(), findSRegBaseAndIndex(), firstRealType(), llvm::LiveRange::flushSegmentSet(), foldReturnAndProcessPred(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::FunctionComparator::functionHash(), llvm::RuntimePointerChecking::generateChecks(), genericValueTraversal(), llvm::ScalarEvolution::getAddExpr(), getBaseType(), getCastsForInductionPHI(), llvm::getConstantVRegValWithLookThrough(), getCoroBeginPredBlocks(), llvm::MCStreamer::getCurrentSection(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), llvm::DWARFContext::getDWOContext(), llvm::getEHScopeMembership(), llvm::safestack::StackLayout::getFrameSize(), getFunctionNameAndStartLineForAddress(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::getLibcallSignature(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), getMatchingEHPad(), llvm::SlotIndexes::getMBBFromIndex(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), getNotRelocatableInstructions(), llvm::MCStreamer::getPreviousSection(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), llvm::Intrinsic::getType(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::GetUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), handleFree(), HandleMergeInputChains(), llvm::VPRecipeBuilder::handleReplication(), llvm::LiveRange::hasAtLeastOneValue(), hasCallsInBlocksBetween(), llvm::DbgVariable::hasComplexAddress(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), llvm::DbgVariable::hasFrameIndexExprs(), llvm::SDNode::hasPredecessorHelper(), llvm::DebugHandlerBase::identifyScopeMarkers(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), inlineCallsImpl(), llvm::InlineFunction(), llvm::SmallSet< T, N, C >::insert(), llvm::VPBlockUtils::insertBlockAfter(), llvm::MemorySSAUpdater::insertDef(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), insertParsePoints(), insertPHI(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), llvm::AbstractCallSite::isCallbackCall(), llvm::AbstractCallSite::isCallee(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::InstCombineWorklist::isEmpty(), isEphemeralValueOf(), isHorizontalBinOp(), isKnownNonNullFromDominatingCondition(), isLeakCheckerRoot(), llvm::DwarfDebug::isLexicalScopeDIENull(), isNonEscapingGlobalNoAliasWithLoad(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantGlobal(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isSafeToMove(), isSafeToPromoteArgument(), isSafeToSpeculatePHIUsers(), isSimpleIf(), IsStoredObjCPointer(), isSuccOrder(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), llvm::SMSchedule::latestCycleInChain(), llvm::MCAsmLexer::Lex(), LinearizeExprTree(), llvm::vfs::lookupInMemoryNode(), llvm::vfs::RedirectingFileSystem::lookupPath(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::X86CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::LowerDbgDeclare(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerGuardIntrinsic(), llvm::SITargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), lowerWidenableCondition(), markAliveBlocks(), markTails(), llvm::FileCheckPattern::match(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), memoryIsNotModifiedBetween(), llvm::object::ExportEntry::moveNext(), mustExecuteUBIfPoisonOnPathTo(), llvm::sys::path::native(), llvm::EscapeEnumerator::Next(), nextRealType(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), AllocaSlices::partition_iterator::operator==(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::X86FrameLowering::orderFrameObjects(), llvm::PointerMayBeCaptured(), llvm::BasicAAResult::pointsToConstantMemory(), llvm::PriorityWorklist< T, VectorT, MapT >::pop_back(), llvm::SwiftErrorValueTracking::preassignVRegs(), PrepareTailCall(), llvm::DIExpression::prependOpcodes(), llvm::GCOVBlock::print(), llvm::WebAssemblyInstPrinter::printInst(), llvm::printLoop(), printSyncScope(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), processHeaderPhiOperands(), llvm::JumpThreadingPass::ProcessThreadableEdges(), promoteArguments(), llvm::promoteLoopAccessesToScalars(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::BitstreamCursor::ReadBlockEnd(), rebuildLoopAfterUnswitch(), recomputeLoopBlockSet(), llvm::InnerLoopVectorizer::recordVectorLoopValueForInductionCast(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), relocationViaAlloca(), llvm::sys::path::remove_dots(), llvm::LegacyInlinerBase::removeDeadFunctions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PMDataManager::removeDeadPasses(), llvm::MemoryDependenceResults::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), replaceConstantExprOp(), llvm::coro::replaceCoroFree(), llvm::replaceDbgUsesWithUndef(), replaceDevirtTrigger(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), rewriteNonInstructionUses(), llvm::TruncInstCombine::run(), llvm::LoopUnrollPass::run(), llvm::SpeculateAroundPHIsPass::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::AlwaysInlinerPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::LoopVectorizePass::runImpl(), llvm::ConstantHoistingPass::runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::salvageDebugInfo(), llvm::SpillPlacement::scanActiveBundles(), searchPredecessors(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::EngineBuilder::selectTarget(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory(), llvm::SUnit::setDepthDirty(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExit(), llvm::MCContext::setGenDwarfRootFile(), llvm::SUnit::setHeightDirty(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), llvm::VPBlockBase::setOneSuccessor(), llvm::VPBlockBase::setPredecessors(), llvm::VPBlockBase::setTwoSuccessors(), SimplifyAddOperands(), simplifyCommonValuePhi(), llvm::simplifyLoop(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SmallVector< T, N >::SmallVector(), sortBlocks(), sortLocalVars(), SplitAddRecs(), llvm::SplitCriticalEdge(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitLandingPadPredecessors(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::MCStreamer::SubSection(), substituteSimpleCopyRegs(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::JumpThreadingPass::ThreadEdge(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::detail::IEEEFloat::toString(), llvm::LoopTraversal::traverse(), tryBuildVectorShuffle(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), tryToSpeculatePHIs(), TurnSwitchRangeIntoICmp(), unswitchBestCondition(), unswitchTrivialSwitch(), updateLiveness(), llvm::IntervalMapImpl::Path::valid(), llvm::PHITransAddr::Verify(), llvm::ScalarEvolution::verify(), verifyCTRBranch(), llvm::SCEVTraversal< SV >::visitAll(), visitDomSubTree(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitLandingPadInst(), visitPHIUsersAndDepsInPostOrder(), llvm::LazyCallGraph::visitReferences(), llvm::VPRegionBlock::VPRegionBlock(), llvm::writeArchive(), llvm::ArrayRecycler< T, Align >::~ArrayRecycler(), llvm::PrintIRInstrumentation::~PrintIRInstrumentation(), and llvm::SCEVExpander::~SCEVExpander().
grow_pod()
void SmallVectorBase::grow_pod (void * FirstEl, size_t MinCapacity, size_t TSize) protected
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
grow_pod - This is an implementation of the grow() method which only works on POD-like datatypes and is out of line to reduce code duplication.
Definition at line 42 of file SmallVector.cpp.
References BeginX, Capacity, capacity(), llvm::report_bad_alloc_error(), llvm::safe_malloc(), llvm::safe_realloc(), and size().
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::grow_pod().
set_size()
void llvm::SmallVectorBase::set_size (size_t N) inline
Set the array size to N, which the current array must have enough capacity for.
This does not construct or destroy any elements in the vector.
Clients can use this in conjunction with capacity() to write past the end of the buffer when they know that more elements are available, and only update the size later. This avoids the cost of value initializing elements which will only be overwritten.
Definition at line 66 of file SmallVector.h.
References assert(), capacity(), N, and Size.
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::assign(), llvm::zlib::compress(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorImpl< T >::erase(), getMemoryBufferForStream(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, true >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::sys::path::remove_filename(), llvm::sys::path::replace_extension(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorImpl< T >::swap().
size()
size_t llvm::SmallVectorBase::size () const inline
Definition at line 52 of file SmallVector.h.
References Size.
Referenced by llvm::InstCombineWorklist::Add(), AddAliasScopeMetadata(), llvm::AttributeList::addAttributes(), llvm::SSAUpdaterBulk::AddAvailableValue(), addData(), llvm::CodeViewContext::addFile(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::DbgVariable::addMMIEntry(), llvm::AttributeList::addParamAttribute(), llvm::mca::RegisterFile::addRegisterRead(), llvm::CodeViewContext::addToStringTable(), llvm::SSAUpdaterBulk::AddUse(), llvm::DebugLocEntry::addValues(), llvm::SSAUpdaterBulk::AddVariable(), adjustCostForPairing(), llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::AllocationOrder::AllocationOrder(), llvm::ForwardDominanceFrontierBase< BlockT >::analyze(), AnalyzeArguments(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::CCState::AnalyzeCallOperands(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::CCState::AnalyzeReturn(), llvm::opt::ArgList::append(), llvm::RegsForValue::append(), llvm::SmallVectorImpl< T >::append(), llvm::sys::path::append(), appendToGlobalArray(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), llvm::IntervalMapImpl::Path::atBegin(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning(), llvm::IntervalMapImpl::Path::atLastEntry(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), BatchCommitValueTo(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildFrameType(), buildFromShuffleMostly(), buildGEP(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildMerge(), buildMultiplyTree(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::DomTreeBuilder::CalculateWithUpdates(), llvm::X86InstrInfo::canMakeTailCallConditional(), CanMergeParamLoadStoresStartingAt(), canonicalizeBitSelect(), llvm::FileCheck::CanonicalizeFile(), canProfitablyUnrollMultiExitLoop(), canSplitCallSite(), canUseSiblingCall(), canWidenShuffleElements(), CasesAreContiguous(), CC_AArch64_Custom_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_RISCV(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), chainLoadsAndStoresForMemcpy(), llvm::HexagonShuffler::check(), checkHVXPipes(), llvm::CCState::CheckReturn(), llvm::object::MachOObjectFile::checkSymbolTable(), llvm::ArrayRecycler< T, Align >::clear(), clobbersFlagRegisters(), llvm::CloneAndPruneIntoFromInst(), llvm::collectChildrenInLoop(), collectInsertionElements(), collectMultiplyFactors(), llvm::collectPGOFuncNameStrings(), combineAnd(), CombineBaseUpdate(), combineExtractVectorElt(), combineOrCmpEqZeroToCtlzSrl(), combineToConsecutiveLoads(), combineVectorShiftImm(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), completeEphemeralValues(), llvm::IntEqClasses::compress(), llvm::ScalarEvolution::computeAccessFunctions(), llvm::EHStreamer::computeActionsTable(), llvm::ComputeASanStackFrameDescription(), llvm::ComputeASanStackFrameLayout(), llvm::EHStreamer::computeCallSiteTable(), llvm::WasmException::computeCallSiteTable(), llvm::FoldingSetNodeID::ComputeHash(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::safestack::StackLayout::computeLayout(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::EHStreamer::computePadMap(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputePTXValueVTs(), llvm::concatenateVectors(), ConstructSSAForLoadSet(), llvm::LiveRange::containsOneValue(), llvm::convertUTF8ToUTF16String(), createMMXBuildVector(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::sys::fs::createUniquePath(), llvm::LiveRange::createValueCopy(), llvm::mca::ExecuteStage::cycleEnd(), llvm::DeleteDeadPHIs(), llvm::DependenceInfo::depends(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::MCFragment::dump(), dumpScopes(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), EmitAddTreeOfValues(), llvm::EmitAnyX86InstComments(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::AsmPrinter::EmitConstantPool(), emitDarwinBCHeaderAndTrailer(), llvm::MCObjectStreamer::EmitDTPRel32Value(), llvm::MCObjectStreamer::EmitDTPRel64Value(), llvm::PPCFrameLowering::emitEpilogue(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::MCObjectStreamer::emitFill(), EmitGenDwarfInfo(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::PPCFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::MCObjectStreamer::EmitRelocDirective(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::MCObjectStreamer::EmitTPRel32Value(), llvm::MCObjectStreamer::EmitTPRel64Value(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::CodeViewContext::encodeDefRange(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::codeview::ContinuationRecordBuilder::end(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::InstructionSelector::executeMatchTable(), llvm::LoopVectorizationPlanner::executePlan(), ExpandBVWithShuffles(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), ExpandResponseFile(), llvm::cl::ExpandResponseFiles(), ExtendUsesToFormExtLoad(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::GISelWorkList< N >::finalize(), llvm::DebugLocEntry::finalize(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::finalizeBundle(), llvm::CodeExtractor::findAllocas(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), llvm::DWARFAbbreviationDeclaration::findAttributeIndex(), findBestInsertionSet(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::findIndex(), FindInOperandList(), llvm::FindInsertedValue(), llvm::MachineInstr::findTiedOperandIdx(), llvm::SplitEditor::finish(), llvm::DWARFUnitVector::finishedInfoUnits(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), fixupVariableFloatArgs(), llvm::FoldBranchToCommonDest(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::FmtAlign::format(), llvm::formLCSSAForInstructions(), ForwardSwitchConditionToPHI(), llvm::MemoryDepChecker::generateInstructionOrderMap(), llvm::RecordRecTy::get(), llvm::AttributeSetNode::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::DWARFAbbreviationDeclaration::getAttrByIndex(), GetBranchWeights(), llvm::AbstractCallSite::getCallArgOperandNoForCallee(), llvm::SCEVUnionPredicate::getComplexity(), llvm::RegsForValue::getCopyToRegs(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), getFauxShuffleMask(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::DIInliningInfo::getFrame(), llvm::DbgVariable::getFrameIndexExprs(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::CCState::getInRegsParamInfo(), llvm::CCState::getInRegsParamsCount(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::RISCVMatInt::getIntMatCost(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::RegisterClassInfo::getLastCalleeSavedAlias(), llvm::object::MachOObjectFile::getLibraryCount(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemoryBufferForStream(), getMemsetStores(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::DIInliningInfo::getMutableFrame(), llvm::LiveRange::getNextValue(), getNoopInput(), llvm::AbstractCallSite::getNumArgOperands(), llvm::DWARFAbbreviationDeclaration::getNumAttributes(), llvm::RuntimePointerChecking::getNumberOfChecks(), llvm::DIInliningInfo::getNumberOfFrames(), llvm::ExtractValueInst::getNumIndices(), llvm::InsertValueInst::getNumIndices(), llvm::DWARFUnitVector::getNumInfoUnits(), llvm::RegBankSelect::RepairingPlacement::getNumInsertPoints(), llvm::DebugLocStream::getNumLists(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::MCInst::getNumOperands(), llvm::VPUser::getNumOperands(), llvm::VPBlockBase::getNumPredecessors(), llvm::mca::RegisterFile::getNumRegisterFiles(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::GetNumSlabs(), llvm::mca::MemoryGroup::getNumSuccessors(), llvm::VPBlockBase::getNumSuccessors(), llvm::DWARFUnitVector::getNumTypesUnits(), llvm::DWARFUnitVector::getNumUnits(), llvm::LiveRange::getNumValNums(), llvm::opt::Arg::getNumValues(), getOpEnabled(), llvm::VPUser::getOperand(), getOpRefinementSteps(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), getPreStartForExtend(), llvm::MachineTraceMetrics::getProcResourceCycles(), llvm::NVPTXTargetLowering::getPrototype(), llvm::ReachingDefAnalysis::getReachingDef(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::GetReturnInfo(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::getRoot(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRoot(), llvm::object::MachOObjectFile::getSection(), llvm::GetShadowBytes(), getShuffleComment(), getShuffleInput(), llvm::DbgVariable::getSingleExpression(), llvm::VPBlockBase::getSinglePredecessor(), llvm::VPBlockBase::getSingleSuccessor(), llvm::DependenceInfo::getSplitIteration(), llvm::object::MachOObjectFile::getSymbolSection(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), llvm::slpvectorizer::BoUpSLP::getTreeSize(), getTwoPredecessors(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlock(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::SSAUpdaterImpl< UpdaterT >::GetValue(), llvm::yaml::ScalarNode::getValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), GroupByComplexity(), llvm::IndexedMap< T, ToIndexT >::grow(), llvm::IntEqClasses::grow(), grow_pod(), llvm::CallLowering::handleAssignments(), HandleMergeInputChains(), llvm::DbgVariable::hasComplexAddress(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::TargetInstrInfo::hasStoreToStackSlot(), llvm::SSAUpdaterBulk::HasValueForBlock(), llvm::mca::MicroOpQueueStage::hasWorkToComplete(), llvm::IntervalMapImpl::Path::height(), llvm::HexagonMCShuffle(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::identifyObject(), llvm::IndexedMap< T, ToIndexT >::inBounds(), llvm::ValueEnumerator::incorporateFunction(), INITIALIZE_PASS(), InitializeUniqueCases(), llvm::InitLLVM::InitLLVM(), inlineCallsImpl(), llvm::InlineFunction(), llvm::sroa::AllocaSlices::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::GISelWorkList< N >::insert(), llvm::insertDebugValuesForPHIs(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), insertParsePoints(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), insertValues(), llvm::FoldingSetNodeID::Intern(), llvm::intersectAccessGroups(), isBigEndian(), isConstantSplat(), isFNEG(), llvm::AArch64TargetLowering::isFPImmLegal(), isHorizontalBinOp(), llvm::DwarfDebug::isLexicalScopeDIENull(), llvm::ARMBaseInstrInfo::isLoadFromStackSlotPostFE(), IsMemoryAssignmentError(), isPointerValueDeadOnEntryToFunction(), isSlicingProfitable(), llvm::ARMBaseInstrInfo::isStoreToStackSlotPostFE(), llvm::CodeViewContext::isValidFileNumber(), isVECTOR_SHUFFLE_SPLATI(), iterativelySimplifyCFG(), llvm::LiveRange::join(), LinearizeExprTree(), llvm_getMetadata(), LLVMCopyModuleFlagsMetadata(), LLVMDisasmInstruction(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetRelocationTypeName(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::X86InstrInfo::loadRegFromAddr(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), LowerBUILD_VECTORvXi1(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::MipsCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleWithUndefHalf(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), LowerVectorAllZeroTest(), llvm::sys::fs::make_absolute(), llvm::makeFollowupLoopID(), llvm::opt::InputArgList::MakeIndex(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::FileCheckPattern::match(), matchBinaryPermuteShuffle(), matchBitOpReduction(), llvm::Intrinsic::matchIntrinsicSignature(), matchIntrinsicType(), matchShuffleAsByteRotate(), MaybePredicatedInst(), llvm::BitTracker::RegisterCell::meet(), mergeConstants(), llvm::InjectorIRStrategy::mutate(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::sys::path::native(), llvm::PHITransAddr::NeedsPHITranslationFromBlock(), needsReferenceType(), llvm::EscapeEnumerator::Next(), llvm::CCState::nextInRegsParam(), llvm::Triple::normalize(), llvm::FoldingSetNodeID::operator<(), llvm::raw_ostream::operator<<(), llvm::SmallVectorImpl< T >::operator=(), llvm::object::ExportEntry::operator==(), llvm::FoldingSetNodeID::operator==(), AllocaSlices::partition_iterator::operator==(), llvm::BitTracker::RegisterCell::operator==(), llvm::SmallVectorImpl< T >::operator==(), llvm::IndexedMap< T, ToIndexT >::operator[](), llvm::remarks::ParsedStringTable::operator[](), llvm::SmallVectorTemplateCommon< T, typename >::operator[](), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeIntegerToVectorInsertions(), llvm::CallLowering::packRegs(), llvm::TargetLowering::parametersInCSRMatch(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), llvm::cl::ParseCommandLineOptions(), llvm::cl::ParseEnvironmentOptions(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::PHITransAddr::PHITranslateWithInsertion(), placeSplitBlockCarefully(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, true >::pop_back(), llvm::MCStreamer::PopSection(), previousEqual(), llvm::opt::Arg::print(), llvm::safestack::StackLayout::print(), llvm::WebAssemblyInstPrinter::printInst(), PrintLoopInfo(), PrintOps(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::PrintStats(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::JumpThreadingPass::ProcessThreadableEdges(), PropagateConstantReturn(), PropagateConstantsIntoArguments(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::coverage::RawCoverageMappingReader::read(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::SymbolRemappingReader::read(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::readPGOFuncNameStrings(), llvm::AArch64TargetLowering::ReconstructShuffle(), redirectValuesFromPredecessorsToPhi(), llvm::LegalizerHelper::reduceLoadStoreWidth(), RefineErrorLoc(), llvm::RuntimeDyldELF::registerEHFrames(), relocationViaAlloca(), rematerializeLiveValues(), llvm::sys::path::remove_dots(), llvm::sys::path::remove_filename(), llvm::AttributeList::removeAttribute(), llvm::AttributeList::removeAttributes(), removeDuplicateGCPtrs(), removeGlobalCtors(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), removeRedundantBlockingStores(), llvm::Record::removeValue(), llvm::LiveRange::RenumberValues(), llvm::sys::path::replace_extension(), llvm::sys::path::replace_path_prefix(), llvm::X86InstrInfo::replaceBranchWithTailCall(), llvm::SmallVectorImpl< T >::resize(), llvm::RuntimeDyldImpl::resolveRelocationList(), resolveTargetShuffleInputsAndMask(), RestoreSpillList(), llvm::CCState::resultsCompatible(), llvm::LanaiInstrInfo::reverseBranchCondition(), llvm::Attributor::run(), llvm::LoopVectorizePass::runImpl(), llvm::runIPSCCP(), llvm::object::MachOObjectFile::section_end(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectPatchpoint(), llvm::EngineBuilder::selectTarget(), llvm::LoopVectorizationPlanner::setBestPlan(), llvm::mca::ResourceManager::setCustomStrategy(), setLocInfo(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), llvm::IntervalMapImpl::Path::setSize(), setUsedInitializer(), SimplifyAddOperands(), SimplifyBranchOnICmpChain(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::simplifyLoop(), simplifyOneLoop(), SimplifyShuffleVectorInst(), SimplifySwitchOnSelect(), SimplifyWithOpReplaced(), SinkCommonCodeFromPredecessors(), sinkLastInstruction(), llvm::IndexedMap< T, ToIndexT >::size(), llvm::SmallSet< T, N, C >::size(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::size(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::size(), llvm::LazyCallGraph::SCC::size(), llvm::LazyCallGraph::RefSCC::size(), llvm::LiveRange::size(), llvm::LiveRangeEdit::size(), llvm::MCInst::size(), llvm::MDAttachmentMap::size(), llvm::HexagonShuffler::size(), LoopDepthTree::size(), llvm::IntervalMapImpl::Path::size(), llvm::SmallVectorTemplateCommon< T, typename >::size_in_bytes(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHIs(), SplitAddRecs(), splitCallSite(), llvm::DbgValueHistoryMap::startClobber(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::X86InstrInfo::storeRegToAddr(), llvm::PPCInstrInfo::storeRegToStackSlot(), StoreTailCallArgumentsToStackSlot(), llvm::raw_svector_ostream::str(), llvm::SmallString< InternalLen >::str(), llvm::Regex::sub(), substituteSimpleCopyRegs(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::JumpThreadingPass::ThreadEdge(), llvm::CodeViewYAML::toDebugH(), llvm::Twine::toNullTerminatedStringRef(), llvm::detail::IEEEFloat::toString(), llvm::APInt::toString(), llvm::Twine::toStringRef(), llvm::LoopTraversal::traverse(), llvm::Triple::Triple(), tryBuildVectorShuffle(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryMergeRange(), TurnSwitchRangeIntoICmp(), llvm::IntEqClasses::uncompress(), llvm::CallLowering::unpackRegs(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchTrivialSwitch(), updatePhysDepsUpwards(), llvm::UpgradeModuleFlags(), llvm::UpgradeRetainReleaseMarker(), VectorizePTXValueVTs(), llvm::LiveRange::verify(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::MemorySSA::verifyOrdering(), VerifyVectorTypes(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitUDiv(), visitUDivOperand(), llvm::WriteBitcodeToFile(), llvm::WriteIndexToFile(), llvm::MCAssembler::writeSectionData(), llvm::BitcodeWriter::writeSymtab(), llvm::WriteThinLinkBitcodeToFile(), llvm::opt::Arg::~Arg(), and llvm::json::OStream::~OStream().
Member Data Documentation
BeginX
void* llvm::SmallVectorBase::BeginX protected
Definition at line 40 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::begin(), grow_pod(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), and llvm::SmallVectorImpl< T >::swap().
Capacity
unsigned llvm::SmallVectorBase::Capacity protected
Definition at line 41 of file SmallVector.h.
Referenced by capacity(), grow_pod(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), and llvm::SmallVectorImpl< T >::swap().
Size
unsigned llvm::SmallVectorBase::Size = 0 protected
Definition at line 41 of file SmallVector.h.
Referenced by llvm::ARMBasicBlockUtils::adjustBBSize(), llvm::SmallVectorImpl< T >::clear(), llvm::ComputeASanStackFrameLayout(), empty(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), set_size(), size(), and llvm::SmallVectorImpl< T >::swap().
The documentation for this class was generated from the following files:
include/llvm/ADT/SmallVector.h
lib/Support/SmallVector.cpp