LLVM: llvm::GISelObserverWrapper Class Reference
llvm::GISelObserverWrapper Class Reference
Simple wrapper observer that takes several observers, and calls each one for each event.
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
Public Member Functions
GISelObserverWrapper ()=default
GISelObserverWrapper (ArrayRef< GISelChangeObserver * > Obs)
void addObserver (GISelChangeObserver *O)
void removeObserver (GISelChangeObserver *O)
void erasingInstr (MachineInstr &MI) override
An instruction is about to be erased.
void createdInstr (MachineInstr &MI) override
An instruction has been created and inserted into the function.
void changingInstr (MachineInstr &MI) override
This instruction is about to be mutated in some way.
void changedInstr (MachineInstr &MI) override
This instruction was mutated in some way.
void MF_HandleInsertion (MachineInstr &MI) override
Callback after an insertion. This should not modify the MI directly.
void MF_HandleRemoval (MachineInstr &MI) override
Callback before a removal. This should not modify the MI directly.
Public Member Functions inherited from llvm::MachineFunction::Delegate
virtual ~Delegate ()=default
virtual void MF_HandleInsertion (MachineInstr &MI)=0
Callback after an insertion. This should not modify the MI directly.
virtual void MF_HandleRemoval (MachineInstr &MI)=0
Callback before a removal. This should not modify the MI directly.
Public Member Functions inherited from llvm::GISelChangeObserver
virtual ~GISelChangeObserver ()
virtual void erasingInstr (MachineInstr &MI)=0
An instruction is about to be erased.
virtual void createdInstr (MachineInstr &MI)=0
An instruction has been created and inserted into the function.
virtual void changingInstr (MachineInstr &MI)=0
This instruction is about to be mutated in some way.
virtual void changedInstr (MachineInstr &MI)=0
This instruction was mutated in some way.
void changingAllUsesOfReg (const MachineRegisterInfo &MRI, unsigned Reg)
All the instructions using the given register are being changed.
void finishedChangingAllUsesOfReg ()
All instructions reported as changing by changingAllUsesOfReg() have finished being changed.
Detailed Description
Simple wrapper observer that takes several observers, and calls each one for each event.
If there are multiple observers (say CSE, Legalizer, Combiner), it's sufficient to register this to the machine function as the delegate.
Definition at line 65 of file GISelChangeObserver.h.
Constructor & Destructor Documentation
GISelObserverWrapper() [1/2]
llvm::GISelObserverWrapper::GISelObserverWrapper () default
GISelObserverWrapper() [2/2]
llvm::GISelObserverWrapper::GISelObserverWrapper (ArrayRef< GISelChangeObserver * > Obs) inline
Definition at line 71 of file GISelChangeObserver.h.
Member Function Documentation
addObserver()
void llvm::GISelObserverWrapper::addObserver (GISelChangeObserver * O) inline
Definition at line 74 of file GISelChangeObserver.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::Combiner::combineMachineInstrs(), llvm::IRTranslator::runOnMachineFunction(), and llvm::Legalizer::runOnMachineFunction().
changedInstr()
void llvm::GISelObserverWrapper::changedInstr (MachineInstr & MI) inline override virtual
This instruction was mutated in some way.
Implements llvm::GISelChangeObserver.
Definition at line 95 of file GISelChangeObserver.h.
References MI.
changingInstr()
void llvm::GISelObserverWrapper::changingInstr (MachineInstr & MI) inline override virtual
This instruction is about to be mutated in some way.
Implements llvm::GISelChangeObserver.
Definition at line 91 of file GISelChangeObserver.h.
References MI.
createdInstr()
void llvm::GISelObserverWrapper::createdInstr (MachineInstr & MI) inline override virtual
An instruction has been created and inserted into the function.
Note that the instruction might not be a fully fledged instruction at this point and won't be if the MachineFunction::Delegate is calling it. This is because the delegate only sees the construction of the MachineInstr before operands have been added.
Implements llvm::GISelChangeObserver.
Definition at line 87 of file GISelChangeObserver.h.
References MI.
Referenced by MF_HandleInsertion().
erasingInstr()
void llvm::GISelObserverWrapper::erasingInstr (MachineInstr & MI) inline override virtual
An instruction is about to be erased.
Implements llvm::GISelChangeObserver.
Definition at line 83 of file GISelChangeObserver.h.
References MI.
Referenced by MF_HandleRemoval(), and llvm::Legalizer::runOnMachineFunction().
MF_HandleInsertion()
void llvm::GISelObserverWrapper::MF_HandleInsertion (MachineInstr & MI) inline override virtual
Callback after an insertion. This should not modify the MI directly.
Implements llvm::MachineFunction::Delegate.
Definition at line 100 of file GISelChangeObserver.h.
References createdInstr(), and MI.
MF_HandleRemoval()
void llvm::GISelObserverWrapper::MF_HandleRemoval (MachineInstr & MI) inline override virtual
Callback before a removal. This should not modify the MI directly.
Implements llvm::MachineFunction::Delegate.
Definition at line 101 of file GISelChangeObserver.h.
References erasingInstr(), and MI.
removeObserver()
void llvm::GISelObserverWrapper::removeObserver (GISelChangeObserver * O) inline
Definition at line 77 of file GISelChangeObserver.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorImpl< T >::erase().
Referenced by llvm::IRTranslator::runOnMachineFunction().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/GISelChangeObserver.h