LLVM: llvm::ARMAsmBackendDarwin Class Reference
llvm::ARMAsmBackendDarwin Class Reference
#include "Target/ARM/MCTargetDesc/ARMAsmBackendDarwin.h"
Public Member Functions
ARMAsmBackendDarwin (const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, MachO::CPUSubTypeARM st)
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction > Instrs) const override
Generate compact unwind encoding for the function based on the CFI instructions.
Public Member Functions inherited from llvm::ARMAsmBackend
ARMAsmBackend (const Target &T, const MCSubtargetInfo &STI, support::endianness Endian)
unsigned getNumFixupKinds () const override
Get the number of target specific fixup kinds.
bool hasNOP () const
Optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target) override
Hook to check if a relocation is needed for some target specific reason.
unsigned adjustFixupValue (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, uint64_t Value, bool IsResolved, MCContext &Ctx, const MCSubtargetInfo *STI) const
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
unsigned getRelaxedOpcode (unsigned Op, const MCSubtargetInfo &STI) const
bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const override
Check whether the given instruction may need relaxation.
const char * reasonForFixupRelaxation (const MCFixup &Fixup, uint64_t Value) const
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
void relaxInstruction (const MCInst &Inst, const MCSubtargetInfo &STI, MCInst &Res) const override
Relax the instruction in the given fragment to the next wider instruction.
bool writeNopData (raw_ostream &OS, uint64_t Count) const override
Write an (optimal) nop sequence of Count bytes to the given output.
void handleAssemblerFlag (MCAssemblerFlag Flag) override
Handle any target-specific assembler flags. By default, do nothing.
unsigned getPointerSize () const
bool isThumb () const
void setIsThumb (bool it)
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
void handleCodePaddingBasicBlockStart (MCObjectStreamer *OS, const MCCodePaddingContext &Context)
Handles all target related code padding when starting to write a new basic block to an object file.
void handleCodePaddingBasicBlockEnd (const MCCodePaddingContext &Context)
Handles all target related code padding after writing a block to an object file.
void handleCodePaddingInstructionBegin (const MCInst &Inst)
Handles all target related code padding before writing a new instruction to an object file.
void handleCodePaddingInstructionEnd (const MCInst &Inst)
Handles all target related code padding after writing an instruction to an object file.
bool relaxFragment (MCPaddingFragment *PF, MCAsmLayout &Layout)
Relaxes a fragment (changes the size of the padding) according to target requirements.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool requiresDiffExpressionRelocations () const
Check whether the given target requires emitting differences of two symbols as a set of relocations.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Public Attributes
const MachO::CPUSubTypeARM Subtype
Public Attributes inherited from llvm::MCAsmBackend
const support::endianness Endian
Additional Inherited Members
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (support::endianness Endian)
Detailed Description
Definition at line 17 of file ARMAsmBackendDarwin.h.
Constructor & Destructor Documentation
ARMAsmBackendDarwin()
llvm::ARMAsmBackendDarwin::ARMAsmBackendDarwin (const Target & T, const MCSubtargetInfo & STI, const MCRegisterInfo & MRI, MachO::CPUSubTypeARM st) inline
Definition at line 21 of file ARMAsmBackendDarwin.h.
References MRI.
Member Function Documentation
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > llvm::ARMAsmBackendDarwin::createObjectTargetWriter () const inline override virtual
Implements llvm::MCAsmBackend.
Definition at line 26 of file ARMAsmBackendDarwin.h.
References llvm::MachO::CPU_TYPE_ARM, llvm::createARMMachObjectWriter(), and Subtype.
generateCompactUnwindEncoding()
uint32_t ARMAsmBackendDarwin::generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction > Instrs) const override virtual
Generate compact unwind encoding for the function based on the CFI instructions.
If the CFI instructions describe a frame that cannot be encoded in compact unwind, the method returns UNWIND_ARM_MODE_DWARF which tells the runtime to fallback and unwind using dwarf.
Reimplemented from llvm::MCAsmBackend.
Definition at line 1098 of file ARMAsmBackend.cpp.
References contains(), llvm::MachO::CPU_SUBTYPE_ARM_V7K, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::ArrayRef< T >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MCRegisterInfo::getLLVMRegNum(), llvm::MCRegisterInfo::getName(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), Idx, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRelOffset, llvm::ArrayRef< T >::size(), Subtype, CU::UNWIND_ARM_FRAME_FIRST_PUSH_R4, CU::UNWIND_ARM_FRAME_FIRST_PUSH_R5, CU::UNWIND_ARM_FRAME_FIRST_PUSH_R6, CU::UNWIND_ARM_FRAME_SECOND_PUSH_R10, CU::UNWIND_ARM_FRAME_SECOND_PUSH_R11, CU::UNWIND_ARM_FRAME_SECOND_PUSH_R12, CU::UNWIND_ARM_FRAME_SECOND_PUSH_R8, CU::UNWIND_ARM_FRAME_SECOND_PUSH_R9, CU::UNWIND_ARM_MODE_DWARF, CU::UNWIND_ARM_MODE_FRAME, and CU::UNWIND_ARM_MODE_FRAME_D.
Member Data Documentation
Subtype
const MachO::CPUSubTypeARM llvm::ARMAsmBackendDarwin::Subtype
Definition at line 20 of file ARMAsmBackendDarwin.h.
Referenced by createObjectTargetWriter(), and generateCompactUnwindEncoding().
The documentation for this class was generated from the following files:
lib/Target/ARM/MCTargetDesc/ARMAsmBackendDarwin.h
lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp