LLVM: llvm::ContextAndReplaceableUses Class Reference
llvm::ContextAndReplaceableUses Class Reference
Pointer to the context, with optional RAUW support.
#include "llvm/IR/Metadata.h"
Public Member Functions
ContextAndReplaceableUses (LLVMContext &Context)
ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
ContextAndReplaceableUses ()=delete
ContextAndReplaceableUses (ContextAndReplaceableUses &&)=delete
ContextAndReplaceableUses (const ContextAndReplaceableUses &)=delete
ContextAndReplaceableUses & operator= (ContextAndReplaceableUses &&)=delete
ContextAndReplaceableUses & operator= (const ContextAndReplaceableUses &)=delete
~ContextAndReplaceableUses ()
operator LLVMContext & ()
bool hasReplaceableUses () const
Whether this contains RAUW support.
LLVMContext & getContext () const
ReplaceableMetadataImpl * getReplaceableUses () const
ReplaceableMetadataImpl * getOrCreateReplaceableUses ()
Ensure that this has RAUW support, and then return it.
void makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
Assign RAUW support to this.
std::unique_ptr< ReplaceableMetadataImpl > takeReplaceableUses ()
Drop RAUW support.
Detailed Description
Pointer to the context, with optional RAUW support.
Either a raw (non-null) pointer to the LLVMContext, or an owned pointer to ReplaceableMetadataImpl (which has a reference to LLVMContext).
Definition at line 769 of file Metadata.h.
Constructor & Destructor Documentation
ContextAndReplaceableUses() [1/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (LLVMContext & Context) inline
Definition at line 773 of file Metadata.h.
ContextAndReplaceableUses() [2/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) inline
Definition at line 774 of file Metadata.h.
References assert(), and getReplaceableUses().
ContextAndReplaceableUses() [3/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses () delete
ContextAndReplaceableUses() [4/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (ContextAndReplaceableUses &&) delete
ContextAndReplaceableUses() [5/5]
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (const ContextAndReplaceableUses &) delete
~ContextAndReplaceableUses()
llvm::ContextAndReplaceableUses::~ContextAndReplaceableUses () inline
Definition at line 785 of file Metadata.h.
References getReplaceableUses().
Member Function Documentation
getContext()
LLVMContext & llvm::ContextAndReplaceableUses::getContext () const inline
Definition at line 794 of file Metadata.h.
References llvm::PointerUnion< PTs >::get(), llvm::ReplaceableMetadataImpl::getContext(), getReplaceableUses(), and hasReplaceableUses().
Referenced by getOrCreateReplaceableUses(), makeReplaceable(), and operator LLVMContext &().
getOrCreateReplaceableUses()
ReplaceableMetadataImpl * llvm::ContextAndReplaceableUses::getOrCreateReplaceableUses () inline
Ensure that this has RAUW support, and then return it.
Definition at line 807 of file Metadata.h.
References getContext(), getReplaceableUses(), hasReplaceableUses(), and makeReplaceable().
getReplaceableUses()
ReplaceableMetadataImpl * llvm::ContextAndReplaceableUses::getReplaceableUses () const inline
Definition at line 800 of file Metadata.h.
References llvm::PointerUnion< PTs >::get(), and hasReplaceableUses().
Referenced by ContextAndReplaceableUses(), getContext(), getOrCreateReplaceableUses(), makeReplaceable(), takeReplaceableUses(), and ~ContextAndReplaceableUses().
hasReplaceableUses()
bool llvm::ContextAndReplaceableUses::hasReplaceableUses () const inline
Whether this contains RAUW support.
Definition at line 790 of file Metadata.h.
References llvm::PointerUnion< PTs >::is().
Referenced by getContext(), getOrCreateReplaceableUses(), getReplaceableUses(), and takeReplaceableUses().
makeReplaceable()
void llvm::ContextAndReplaceableUses::makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) inline
Assign RAUW support to this.
Make this replaceable, taking ownership of ReplaceableUses (which must not be null).
Definition at line 818 of file Metadata.h.
References assert(), getContext(), and getReplaceableUses().
Referenced by getOrCreateReplaceableUses().
operator LLVMContext &()
llvm::ContextAndReplaceableUses::operator LLVMContext & () inline
Definition at line 787 of file Metadata.h.
References getContext().
operator=() [1/2]
ContextAndReplaceableUses & llvm::ContextAndReplaceableUses::operator= (const ContextAndReplaceableUses &) delete
operator=() [2/2]
ContextAndReplaceableUses & llvm::ContextAndReplaceableUses::operator= (ContextAndReplaceableUses &&) delete
takeReplaceableUses()
std::unique_ptr< ReplaceableMetadataImpl > llvm::ContextAndReplaceableUses::takeReplaceableUses () inline
Drop RAUW support.
Cede ownership of RAUW support, returning it.
Definition at line 829 of file Metadata.h.
References assert(), getReplaceableUses(), and hasReplaceableUses().
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h