LLVM: llvm::codeview::DebugInlineeLinesSubsection Class Reference
llvm::codeview::DebugInlineeLinesSubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h"
Classes
struct Entry
Public Member Functions
DebugInlineeLinesSubsection (DebugChecksumsSubsection &Checksums, bool HasExtraFiles=false)
Error commit (BinaryStreamWriter &Writer) const override
uint32_t calculateSerializedSize () const override
void addInlineSite (TypeIndex FuncId, StringRef FileName, uint32_t SourceLine)
void addExtraFile (StringRef FileName)
bool hasExtraFiles () const
void setHasExtraFiles (bool Has)
std::vector< Entry >::const_iterator begin () const
std::vector< Entry >::const_iterator end () const
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
virtual Error commit (BinaryStreamWriter &Writer) const =0
virtual uint32_t calculateSerializedSize () const =0
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 88 of file DebugInlineeLinesSubsection.h.
Constructor & Destructor Documentation
DebugInlineeLinesSubsection()
DebugInlineeLinesSubsection::DebugInlineeLinesSubsection (DebugChecksumsSubsection & Checksums, bool HasExtraFiles = false)
Definition at line 61 of file DebugInlineeLinesSubsection.cpp.
Member Function Documentation
addExtraFile()
void DebugInlineeLinesSubsection::addExtraFile (StringRef FileName)
Definition at line 107 of file DebugInlineeLinesSubsection.cpp.
References llvm::codeview::DebugInlineeLinesSubsection::Entry::ExtraFiles, and llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset().
addInlineSite()
void DebugInlineeLinesSubsection::addInlineSite (TypeIndex FuncId, StringRef FileName, uint32_t SourceLine)
Definition at line 115 of file DebugInlineeLinesSubsection.cpp.
References llvm::codeview::InlineeSourceLineHeader::FileID, FuncId, llvm::codeview::DebugInlineeLinesSubsection::Entry::Header, llvm::codeview::InlineeSourceLineHeader::Inlinee, llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), and llvm::codeview::InlineeSourceLineHeader::SourceLineNum.
begin()
std::vector< Entry >::const_iterator llvm::codeview::DebugInlineeLinesSubsection::begin () const inline
Definition at line 111 of file DebugInlineeLinesSubsection.h.
calculateSerializedSize()
uint32_t DebugInlineeLinesSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 66 of file DebugInlineeLinesSubsection.cpp.
References assert(), and Size.
classof()
static bool llvm::codeview::DebugInlineeLinesSubsection::classof (const DebugSubsection * S) inline static
Definition at line 98 of file DebugInlineeLinesSubsection.h.
References llvm::codeview::InlineeLines, and llvm::codeview::DebugSubsection::kind().
commit()
Error DebugInlineeLinesSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 83 of file DebugInlineeLinesSubsection.cpp.
References E, llvm::codeview::EC, llvm::codeview::ExtraFiles, llvm::makeArrayRef(), llvm::codeview::Normal, llvm::Error::success(), llvm::BinaryStreamWriter::writeArray(), llvm::BinaryStreamWriter::writeEnum(), llvm::BinaryStreamWriter::writeInteger(), and llvm::BinaryStreamWriter::writeObject().
end()
std::vector< Entry >::const_iterator llvm::codeview::DebugInlineeLinesSubsection::end () const inline
Definition at line 112 of file DebugInlineeLinesSubsection.h.
hasExtraFiles()
bool llvm::codeview::DebugInlineeLinesSubsection::hasExtraFiles () const inline
Definition at line 108 of file DebugInlineeLinesSubsection.h.
setHasExtraFiles()
void llvm::codeview::DebugInlineeLinesSubsection::setHasExtraFiles (bool Has) inline
Definition at line 109 of file DebugInlineeLinesSubsection.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h
lib/DebugInfo/CodeView/DebugInlineeLinesSubsection.cpp