LLVM: llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT > Class Template Reference
llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT > Class Template Reference
Compile-on-demand layer.
#include "llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h"
Public Types
using PartitioningFtor = std::function< std::set< Function * >(Function &)>
Module partitioning functor.
using IndirectStubsManagerBuilderT = std::function< std::unique_ptr< IndirectStubsMgrT >()>
Builder for IndirectStubsManagers.
using SymbolResolverGetter = std::function< std::shared_ptr< SymbolResolver >(VModuleKey K)>
using SymbolResolverSetter = std::function< void(VModuleKey K, std::shared_ptr< SymbolResolver > R)>
Public Member Functions
LLVM_ATTRIBUTE_DEPRECATED (LegacyCompileOnDemandLayer(ExecutionSession &ES, BaseLayerT &BaseLayer, SymbolResolverGetter GetSymbolResolver, SymbolResolverSetter SetSymbolResolver, PartitioningFtor Partition, CompileCallbackMgrT &CallbackMgr, IndirectStubsManagerBuilderT CreateIndirectStubsManager, bool CloneStubsIntoPartitions=true), "ORCv1 layers (layers with the 'Legacy' prefix) are deprecated. Please " "use " "the ORCv2 LegacyCompileOnDemandLayer instead")
Construct a compile-on-demand layer instance.
LegacyCompileOnDemandLayer (ORCv1DeprecationAcknowledgement, ExecutionSession &ES, BaseLayerT &BaseLayer, SymbolResolverGetter GetSymbolResolver, SymbolResolverSetter SetSymbolResolver, PartitioningFtor Partition, CompileCallbackMgrT &CallbackMgr, IndirectStubsManagerBuilderT CreateIndirectStubsManager, bool CloneStubsIntoPartitions=true)
Legacy layer constructor with deprecation acknowledgement.
~LegacyCompileOnDemandLayer ()
Error addModule (VModuleKey K, std::unique_ptr< Module > M)
Add a module to the compile-on-demand layer.
Error addExtraModule (VModuleKey K, std::unique_ptr< Module > M)
Add extra modules to an existing logical module.
Error removeModule (VModuleKey K)
Remove the module represented by the given key.
JITSymbol findSymbol (StringRef Name, bool ExportedSymbolsOnly)
Search for the given named symbol.
JITSymbol findSymbolIn (VModuleKey K, const std::string &Name, bool ExportedSymbolsOnly)
Get the address of a symbol provided by this layer, or some layer below this one.
Error updatePointer (std::string FuncName, JITTargetAddress FnBodyAddr)
Update the stub for the given function to point at FnBodyAddr.
Detailed Description
template<typename BaseLayerT, typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager>
class llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >
Compile-on-demand layer.
When a module is added to this layer a stub is created for each of its function definitions. The stubs and other global values are immediately added to the layer below. When a stub is called it triggers the extraction of the function body from the original module. The extracted body is then compiled and executed.
Definition at line 143 of file CompileOnDemandLayer.h.
Member Typedef Documentation
IndirectStubsManagerBuilderT
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> using llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::IndirectStubsManagerBuilderT = std::function<std::unique_ptr<IndirectStubsMgrT>()>
Builder for IndirectStubsManagers.
Definition at line 257 of file CompileOnDemandLayer.h.
PartitioningFtor
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> using llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::PartitioningFtor = std::function<std::set<Function*>(Function&)>
Module partitioning functor.
Definition at line 254 of file CompileOnDemandLayer.h.
SymbolResolverGetter
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> using llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::SymbolResolverGetter = std::function<std::shared_ptr<SymbolResolver>(VModuleKey K)>
Definition at line 260 of file CompileOnDemandLayer.h.
SymbolResolverSetter
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> using llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::SymbolResolverSetter = std::function<void(VModuleKey K, std::shared_ptr<SymbolResolver> R)>
Definition at line 263 of file CompileOnDemandLayer.h.
Constructor & Destructor Documentation
LegacyCompileOnDemandLayer()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::LegacyCompileOnDemandLayer (ORCv1DeprecationAcknowledgement , ExecutionSession & ES, BaseLayerT & BaseLayer, SymbolResolverGetter GetSymbolResolver, SymbolResolverSetter SetSymbolResolver, PartitioningFtor Partition, CompileCallbackMgrT & CallbackMgr, IndirectStubsManagerBuilderT CreateIndirectStubsManager, bool CloneStubsIntoPartitions = true) inline
Legacy layer constructor with deprecation acknowledgement.
Definition at line 280 of file CompileOnDemandLayer.h.
~LegacyCompileOnDemandLayer()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::~LegacyCompileOnDemandLayer () inline
Definition at line 294 of file CompileOnDemandLayer.h.
References llvm::consumeError(), and llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::removeModule().
Member Function Documentation
addExtraModule()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> Error llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::addExtraModule (VModuleKey K, std::unique_ptr< Module > M) inline
Add extra modules to an existing logical module.
Definition at line 313 of file CompileOnDemandLayer.h.
addModule()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> Error llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::addModule (VModuleKey K, std::unique_ptr< Module > M) inline
Add a module to the compile-on-demand layer.
Definition at line 301 of file CompileOnDemandLayer.h.
References assert(), and I.
findSymbol()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> JITSymbol llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::findSymbol (StringRef Name, bool ExportedSymbolsOnly) inline
Search for the given named symbol.
Parameters
Name The name of the symbol to search for.
ExportedSymbolsOnly If true, search only for exported symbols.
Returns
A handle for the given named symbol, if it exists.
Definition at line 333 of file CompileOnDemandLayer.h.
References llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::findSymbolIn(), and Name.
findSymbolIn()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> JITSymbol llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::findSymbolIn (VModuleKey K, const std::string & Name, bool ExportedSymbolsOnly) inline
Get the address of a symbol provided by this layer, or some layer below this one.
Definition at line 347 of file CompileOnDemandLayer.h.
References assert(), and Name.
Referenced by llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::findSymbol().
LLVM_ATTRIBUTE_DEPRECATED()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::LLVM_ATTRIBUTE_DEPRECATED (LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >(ExecutionSession &ES, BaseLayerT &BaseLayer, SymbolResolverGetter GetSymbolResolver, SymbolResolverSetter SetSymbolResolver, PartitioningFtor Partition, CompileCallbackMgrT &CallbackMgr, IndirectStubsManagerBuilderT CreateIndirectStubsManager, bool CloneStubsIntoPartitions=true) , "ORCv1 layers (layers with the 'Legacy' prefix) are deprecated. Please " "use " "the ORCv2 LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT > instead")
Construct a compile-on-demand layer instance.
removeModule()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> Error llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::removeModule (VModuleKey K) inline
Remove the module represented by the given key.
This will remove all modules in the layers below that were derived from the module represented by K.
Definition at line 321 of file CompileOnDemandLayer.h.
References assert(), and I.
Referenced by llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::~LegacyCompileOnDemandLayer().
updatePointer()
template<typename BaseLayerT , typename CompileCallbackMgrT = JITCompileCallbackManager, typename IndirectStubsMgrT = IndirectStubsManager> Error llvm::orc::LegacyCompileOnDemandLayer< BaseLayerT, CompileCallbackMgrT, IndirectStubsMgrT >::updatePointer (std::string FuncName, JITTargetAddress FnBodyAddr) inline
Update the stub for the given function to point at FnBodyAddr.
This can be used to support re-optimization.
Returns
true if the function exists and the stub is updated, false otherwise.
Definition at line 361 of file CompileOnDemandLayer.h.
References llvm::Module::getDataLayout(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h