LLVM: llvm::DagInit Class Reference
llvm::DagInit Class Reference final
(v a, b) - Represent a DAG tree value.
#include "llvm/TableGen/Record.h"
Public Types
using const_arg_iterator = SmallVectorImpl< Init * >::const_iterator
using const_name_iterator = SmallVectorImpl< StringInit * >::const_iterator
Public Member Functions
DagInit (const DagInit &)=delete
DagInit & operator= (const DagInit &)=delete
void Profile (FoldingSetNodeID &ID) const
Init * getOperator () const
StringInit * getName () const
StringRef getNameStr () const
unsigned getNumArgs () const
Init * getArg (unsigned Num) const
StringInit * getArgName (unsigned Num) const
StringRef getArgNameStr (unsigned Num) const
ArrayRef< Init * > getArgs () const
ArrayRef< StringInit * > getArgNames () const
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
size_t arg_size () const
bool arg_empty () const
const_name_iterator name_begin () const
const_name_iterator name_end () const
size_t name_size () const
bool name_empty () const
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< DagInit, Init *, StringInit * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
Static Public Member Functions
static bool classof (const Init *I)
static DagInit * get (Init *V, StringInit *VN, ArrayRef< Init * > ArgRange, ArrayRef< StringInit * > NameRange)
static DagInit * get (Init *V, StringInit *VN, ArrayRef< std::pair< Init *, StringInit * > > Args)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< DagInit, Init *, StringInit * >
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if< std::is_same< Foo< TrailingTys... >, Foo< Tys... > >::value, size_t >::type totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
(v a, b) - Represent a DAG tree value.
DAG inits are required to have at least one value then a (possibly empty) list of arguments. Each argument can have a name associated with it.
Definition at line 1295 of file Record.h.
Member Typedef Documentation
const_arg_iterator
using llvm::DagInit::const_arg_iterator = SmallVectorImpl<Init*>::const_iterator
Definition at line 1363 of file Record.h.
const_name_iterator
using llvm::DagInit::const_name_iterator = SmallVectorImpl<StringInit*>::const_iterator
Definition at line 1364 of file Record.h.
Constructor & Destructor Documentation
DagInit()
llvm::DagInit::DagInit (const DagInit &) delete
Member Function Documentation
arg_begin()
const_arg_iterator llvm::DagInit::arg_begin () const inline
Definition at line 1366 of file Record.h.
References getArgs().
arg_empty()
bool llvm::DagInit::arg_empty () const inline
Definition at line 1370 of file Record.h.
Referenced by getAsString().
arg_end()
const_arg_iterator llvm::DagInit::arg_end () const inline
Definition at line 1367 of file Record.h.
References getArgs().
arg_size()
size_t llvm::DagInit::arg_size () const inline
Definition at line 1369 of file Record.h.
Referenced by resolveReferences().
classof()
static bool llvm::DagInit::classof (const Init * I) inline static
Definition at line 1314 of file Record.h.
References I, and llvm::Init::IK_DagInit.
get() [1/2]
DagInit * DagInit::get (Init * V, StringInit * VN, ArrayRef< Init * > ArgRange, ArrayRef< StringInit * > NameRange) static
Definition at line 1894 of file Record.cpp.
References Allocator, llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), I, llvm::FoldingSetImpl< T >::InsertNode(), ProfileDagInit(), and llvm::ArrayRef< T >::size().
get() [2/2]
DagInit * DagInit::get (Init * V, StringInit * VN, ArrayRef< std::pair< Init *, StringInit * > > Args) static
Definition at line 1916 of file Record.cpp.
References Arg, llvm::IntervalMapImpl::NodeRef::get(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getArg()
Init * llvm::DagInit::getArg (unsigned Num) const inline
Definition at line 1335 of file Record.h.
References assert().
Referenced by llvm::BinOpInit::Fold(), ForeachDagApply(), and getAsString().
getArgName()
StringInit * llvm::DagInit::getArgName (unsigned Num) const inline
Definition at line 1340 of file Record.h.
References assert().
Referenced by llvm::BinOpInit::Fold(), ForeachDagApply(), getArgNameStr(), and getAsString().
getArgNames()
ArrayRef< StringInit * > llvm::DagInit::getArgNames () const inline
Definition at line 1354 of file Record.h.
References llvm::makeArrayRef().
Referenced by name_begin(), name_end(), and resolveReferences().
getArgNameStr()
StringRef llvm::DagInit::getArgNameStr (unsigned Num) const inline
Definition at line 1345 of file Record.h.
References getArgName().
getArgs()
ArrayRef< Init * > llvm::DagInit::getArgs () const inline
Definition at line 1350 of file Record.h.
References llvm::makeArrayRef().
Referenced by arg_begin(), arg_end(), isConcrete(), and resolveReferences().
getAsString()
std::string DagInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1960 of file Record.cpp.
References arg_empty(), getArg(), getArgName(), llvm::Init::getAsString(), llvm::StringInit::getAsUnquotedString(), and getNumArgs().
Referenced by llvm::BinOpInit::Fold().
getBit()
Init * llvm::DagInit::getBit (unsigned Bit) const inline override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1378 of file Record.h.
References llvm_unreachable.
getName()
StringInit * llvm::DagInit::getName () const inline
Definition at line 1327 of file Record.h.
getNameStr()
StringRef llvm::DagInit::getNameStr () const inline
Definition at line 1329 of file Record.h.
References llvm::StringInit::getValue().
getNumArgs()
unsigned llvm::DagInit::getNumArgs () const inline
Definition at line 1333 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), ForeachDagApply(), and getAsString().
getOperator()
Init * llvm::DagInit::getOperator () const inline
Definition at line 1325 of file Record.h.
Referenced by llvm::SetTheory::evaluate(), llvm::BinOpInit::Fold(), and ForeachDagApply().
isConcrete()
bool DagInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 1950 of file Record.cpp.
References getArgs(), and llvm::Init::isConcrete().
name_begin()
const_name_iterator llvm::DagInit::name_begin () const inline
Definition at line 1372 of file Record.h.
References getArgNames().
name_empty()
bool llvm::DagInit::name_empty () const inline
Definition at line 1376 of file Record.h.
name_end()
const_name_iterator llvm::DagInit::name_end () const inline
Definition at line 1373 of file Record.h.
References getArgNames().
name_size()
size_t llvm::DagInit::name_size () const inline
Definition at line 1375 of file Record.h.
operator=()
DagInit & llvm::DagInit::operator= (const DagInit &) delete
Profile()
void DagInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1929 of file Record.cpp.
References llvm::makeArrayRef(), and ProfileDagInit().
resolveReferences()
Init * DagInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1933 of file Record.cpp.
References Arg, arg_size(), llvm::IntervalMapImpl::NodeRef::get(), getArgNames(), getArgs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp