LLVM: llvm::object::ELFObjectFileBase Class Reference
llvm::object::ELFObjectFileBase Class Reference abstract
#include "llvm/Object/ELFObjectFile.h"
Public Types
using elf_symbol_iterator_range = iterator_range< elf_symbol_iterator >
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Public Member Functions
virtual elf_symbol_iterator_range getDynamicSymbolIterators () const =0
virtual unsigned getPlatformFlags () const =0
Returns platform-specific object flags, if any.
elf_symbol_iterator_range symbols () const
SubtargetFeatures getFeatures () const override
SubtargetFeatures getMIPSFeatures () const
SubtargetFeatures getARMFeatures () const
SubtargetFeatures getRISCVFeatures () const
void setARMSubArch (Triple &TheTriple) const override
virtual uint16_t getEType () const =0
virtual uint16_t getEMachine () const =0
std::vector< std::pair< DataRefImpl, uint64_t > > getPltAddresses () const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual SubtargetFeatures getFeatures () const =0
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Member Functions
ELFObjectFileBase (unsigned int Type, MemoryBufferRef Source)
virtual uint64_t getSymbolSize (DataRefImpl Symb) const =0
virtual uint8_t getSymbolBinding (DataRefImpl Symb) const =0
virtual uint8_t getSymbolOther (DataRefImpl Symb) const =0
virtual uint8_t getSymbolELFType (DataRefImpl Symb) const =0
virtual uint32_t getSectionType (DataRefImpl Sec) const =0
virtual uint64_t getSectionFlags (DataRefImpl Sec) const =0
virtual uint64_t getSectionOffset (DataRefImpl Sec) const =0
virtual Expected< int64_t > getRelocationAddend (DataRefImpl Rel) const =0
virtual Error getBuildAttributes (ARMAttributeParser &Attributes) const =0
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
uint64_t getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class ELFRelocationRef
class ELFSectionRef
class ELFSymbolRef
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 49 of file ELFObjectFile.h.
Member Typedef Documentation
elf_symbol_iterator_range
using llvm::object::ELFObjectFileBase::elf_symbol_iterator_range = iterator_range<elf_symbol_iterator>
Definition at line 70 of file ELFObjectFile.h.
Constructor & Destructor Documentation
ELFObjectFileBase()
ELFObjectFileBase::ELFObjectFileBase (unsigned int Type, MemoryBufferRef Source) protected
Definition at line 48 of file ELFObjectFile.cpp.
Member Function Documentation
classof()
static bool llvm::object::ELFObjectFileBase::classof (const Binary * v) inline static
Definition at line 79 of file ELFObjectFile.h.
References llvm::object::Binary::isELF().
getARMFeatures()
SubtargetFeatures ELFObjectFileBase::getARMFeatures () const
Definition at line 148 of file ELFObjectFile.cpp.
References llvm::SubtargetFeatures::AddFeature(), llvm::ARMBuildAttrs::Advanced_SIMD_arch, llvm::ARMBuildAttrs::AllowDIVExt, llvm::ARMBuildAttrs::AllowFPv2, llvm::ARMBuildAttrs::AllowFPv3A, llvm::ARMBuildAttrs::AllowFPv3B, llvm::ARMBuildAttrs::AllowFPv4A, llvm::ARMBuildAttrs::AllowFPv4B, llvm::ARMBuildAttrs::AllowMVEInteger, llvm::ARMBuildAttrs::AllowMVEIntegerAndFloat, llvm::ARMBuildAttrs::AllowNeon, llvm::ARMBuildAttrs::AllowNeon2, llvm::ARMBuildAttrs::AllowThumb32, llvm::ARMBuildAttrs::ApplicationProfile, llvm::ARMBuildAttrs::CPU_arch, llvm::ARMBuildAttrs::CPU_arch_profile, llvm::ARMBuildAttrs::DisallowDIV, llvm::ARMBuildAttrs::DIV_use, E, llvm::ARMBuildAttrs::FP_arch, llvm::ARMAttributeParser::getAttributeValue(), getBuildAttributes(), llvm::ARMAttributeParser::hasAttribute(), llvm::ARMBuildAttrs::MicroControllerProfile, llvm::ARMBuildAttrs::MVE_arch, llvm::ARMBuildAttrs::Not_Allowed, llvm::ARMBuildAttrs::RealTimeProfile, llvm::ARMBuildAttrs::THUMB_ISA_use, and llvm::ARMBuildAttrs::v7.
Referenced by getFeatures().
getBuildAttributes()
virtual Error llvm::object::ELFObjectFileBase::getBuildAttributes (ARMAttributeParser & Attributes) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by getARMFeatures(), and setARMSubArch().
getDynamicSymbolIterators()
virtual elf_symbol_iterator_range llvm::object::ELFObjectFileBase::getDynamicSymbolIterators () const pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
getEMachine()
virtual uint16_t llvm::object::ELFObjectFileBase::getEMachine () const pure virtual
Referenced by getFeatures().
getEType()
virtual uint16_t llvm::object::ELFObjectFileBase::getEType () const pure virtual
getFeatures()
SubtargetFeatures ELFObjectFileBase::getFeatures () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 280 of file ELFObjectFile.cpp.
References llvm::ELF::EM_ARM, llvm::ELF::EM_MIPS, llvm::ELF::EM_RISCV, getARMFeatures(), getEMachine(), getMIPSFeatures(), and getRISCVFeatures().
getMIPSFeatures()
SubtargetFeatures ELFObjectFileBase::getMIPSFeatures () const
Definition at line 88 of file ELFObjectFile.cpp.
References llvm::SubtargetFeatures::AddFeature(), llvm::ELF::EF_MIPS_ARCH, llvm::ELF::EF_MIPS_ARCH_1, llvm::ELF::EF_MIPS_ARCH_2, llvm::ELF::EF_MIPS_ARCH_3, llvm::ELF::EF_MIPS_ARCH_32, llvm::ELF::EF_MIPS_ARCH_32R2, llvm::ELF::EF_MIPS_ARCH_32R6, llvm::ELF::EF_MIPS_ARCH_4, llvm::ELF::EF_MIPS_ARCH_5, llvm::ELF::EF_MIPS_ARCH_64, llvm::ELF::EF_MIPS_ARCH_64R2, llvm::ELF::EF_MIPS_ARCH_64R6, llvm::ELF::EF_MIPS_ARCH_ASE_M16, llvm::ELF::EF_MIPS_MACH, llvm::ELF::EF_MIPS_MACH_NONE, llvm::ELF::EF_MIPS_MACH_OCTEON, llvm::ELF::EF_MIPS_MICROMIPS, getPlatformFlags(), and llvm_unreachable.
Referenced by getFeatures().
getPlatformFlags()
virtual unsigned llvm::object::ELFObjectFileBase::getPlatformFlags () const pure virtual
Returns platform-specific object flags, if any.
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by getMIPSFeatures(), getRISCVFeatures(), and llvm::RuntimeDyldELF::processRelocationRef().
getPltAddresses()
std::vector< std::pair< DataRefImpl, uint64_t > > ELFObjectFileBase::getPltAddresses () const
Definition at line 359 of file ELFObjectFile.cpp.
References llvm::Triple::aarch64, llvm::arrayRefFromStringRef(), llvm::consumeError(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Triple::getArch(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::TargetRegistry::lookupTarget(), llvm::object::ObjectFile::makeTriple(), Name, llvm::None, llvm::object::ObjectFile::sections(), llvm::Triple::str(), llvm::Expected< T >::takeError(), llvm::Triple::x86, and llvm::Triple::x86_64.
getRelocationAddend()
virtual Expected< int64_t > llvm::object::ELFObjectFileBase::getRelocationAddend (DataRefImpl Rel) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFRelocationRef::getAddend().
getRISCVFeatures()
SubtargetFeatures ELFObjectFileBase::getRISCVFeatures () const
Definition at line 269 of file ELFObjectFile.cpp.
References llvm::SubtargetFeatures::AddFeature(), llvm::ELF::EF_RISCV_RVC, and getPlatformFlags().
Referenced by getFeatures().
getSectionFlags()
virtual uint64_t llvm::object::ELFObjectFileBase::getSectionFlags (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSectionRef::getFlags().
getSectionOffset()
virtual uint64_t llvm::object::ELFObjectFileBase::getSectionOffset (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSectionRef::getOffset().
getSectionType()
virtual uint32_t llvm::object::ELFObjectFileBase::getSectionType (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSectionRef::getType().
getSymbolBinding()
virtual uint8_t llvm::object::ELFObjectFileBase::getSymbolBinding (DataRefImpl Symb) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSymbolRef::getBinding().
getSymbolELFType()
virtual uint8_t llvm::object::ELFObjectFileBase::getSymbolELFType (DataRefImpl Symb) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSymbolRef::getELFType().
getSymbolOther()
virtual uint8_t llvm::object::ELFObjectFileBase::getSymbolOther (DataRefImpl Symb) const protected pure virtual
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::ELFSymbolRef::getOther().
getSymbolSize()
virtual uint64_t llvm::object::ELFObjectFileBase::getSymbolSize (DataRefImpl Symb) const protected pure virtual
Referenced by llvm::object::ELFSymbolRef::getSize().
setARMSubArch()
void ELFObjectFileBase::setARMSubArch (Triple & TheTriple) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 294 of file ELFObjectFile.cpp.
References llvm::ARMBuildAttrs::CPU_arch, E, llvm::ARMAttributeParser::getAttributeValue(), getBuildAttributes(), llvm::Triple::getSubArch(), llvm::ARMAttributeParser::hasAttribute(), llvm::object::Binary::isLittleEndian(), llvm::Triple::isThumb(), llvm::Triple::NoSubArch, llvm::Triple::setArchName(), llvm::ARMBuildAttrs::v4, llvm::ARMBuildAttrs::v4T, llvm::ARMBuildAttrs::v5T, llvm::ARMBuildAttrs::v5TE, llvm::ARMBuildAttrs::v5TEJ, llvm::ARMBuildAttrs::v6, llvm::ARMBuildAttrs::v6_M, llvm::ARMBuildAttrs::v6K, llvm::ARMBuildAttrs::v6KZ, llvm::ARMBuildAttrs::v6S_M, llvm::ARMBuildAttrs::v6T2, llvm::ARMBuildAttrs::v7, and llvm::ARMBuildAttrs::v7E_M.
symbols()
ELFObjectFileBase::elf_symbol_iterator_range llvm::object::ELFObjectFileBase::symbols () const inline
Definition at line 221 of file ELFObjectFile.h.
References llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
Friends And Related Function Documentation
ELFRelocationRef
friend class ELFRelocationRef friend
Definition at line 50 of file ELFObjectFile.h.
ELFSectionRef
friend class ELFSectionRef friend
Definition at line 51 of file ELFObjectFile.h.
ELFSymbolRef
friend class ELFSymbolRef friend
Definition at line 52 of file ELFObjectFile.h.
The documentation for this class was generated from the following files:
include/llvm/Object/ELFObjectFile.h
lib/Object/ELFObjectFile.cpp