LLVM: llvm::DILocalVariable Class Reference
llvm::DILocalVariable Class Reference
Local variable.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DILocalVariable,(DILocalScope *Scope, StringRef Name, DIFile *File, unsigned Line, DIType *Type, unsigned Arg, DIFlags Flags, uint32_t AlignInBits),(Scope, Name, File, Line, Type, Arg, Flags, AlignInBits)) DEFINE_MDNODE_GET(DILocalVariable
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t AlignInBits TempDILocalVariable clone () const
DILocalScope * getScope () const
Get the local scope for this variable.
bool isParameter () const
unsigned getArg () const
DIFlags getFlags () const
bool isArtificial () const
bool isObjectPointer () const
bool isNotModified () const
Check that an argument is unmodified.
void setIsNotModified ()
Set the flag if an argument is unmodified.
bool isValidLocationForIntrinsic (const DILocation *DL) const
Check that a location is valid for this variable.
Public Member Functions inherited from llvm::DIVariable
unsigned getLine () const
DIScope * getScope () const
StringRef getName () const
DIFile * getFile () const
DIType * getType () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
Optional< uint64_t > getSizeInBits () const
Determines the size of the variable's type.
Optional< DIBasicType::Signedness > getSignedness () const
Return the signedness of this variable's type, or None if this type is neither signed nor unsigned.
StringRef getFilename () const
StringRef getDirectory () const
Optional< StringRef > getSource () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawFile () const
Metadata * getRawType () const
Public Member Functions inherited from llvm::DINode
unsigned getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIVariable
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString Metadata * File
Metadata MDString Metadata unsigned Line
Metadata MDString Metadata unsigned Metadata * Type
Metadata MDString Metadata unsigned Metadata unsigned Arg
Metadata MDString Metadata unsigned Metadata unsigned DIFlags Flags
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t AlignInBits
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Scope
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Name
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t File
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Line
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Type
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Arg
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Flags
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIVariable
DIVariable (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Line, ArrayRef< Metadata * > Ops, uint32_t AlignInBits=0)
~DIVariable ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Local variable.
TODO: Split up flags.
Definition at line 2748 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DILocalVariable::classof (const Metadata * MD) inline static
Definition at line 2826 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t AlignInBits TempDILocalVariable llvm::DILocalVariable::clone () const inline
Definition at line 2796 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DILocalVariable::DEFINE_MDNODE_GET (DILocalVariable , (DILocalScope *Scope, StringRef Name, DIFile *File, unsigned Line, DIType *Type, unsigned Arg, DIFlags Flags, uint32_t AlignInBits) , (Scope, Name, File, Line, Type, Arg, Flags, AlignInBits))
getArg()
unsigned llvm::DILocalVariable::getArg () const inline
Definition at line 2806 of file DebugInfoMetadata.h.
References Arg.
Referenced by llvm::DwarfFile::addScopeVariable(), and llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf().
getFlags()
DIFlags llvm::DILocalVariable::getFlags () const inline
Definition at line 2807 of file DebugInfoMetadata.h.
Referenced by isArtificial(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), isNotModified(), and isObjectPointer().
getScope()
DILocalScope * llvm::DILocalVariable::getScope () const inline
Get the local scope for this variable.
Variables must be defined in a local scope.
Definition at line 2801 of file DebugInfoMetadata.h.
References llvm::DIVariable::getScope().
Referenced by llvm::DebugHandlerBase::beginFunction(), emitDebugValueComment(), and isValidLocationForIntrinsic().
isArtificial()
bool llvm::DILocalVariable::isArtificial () const inline
Definition at line 2809 of file DebugInfoMetadata.h.
References getFlags().
isNotModified()
bool llvm::DILocalVariable::isNotModified () const inline
Check that an argument is unmodified.
Definition at line 2813 of file DebugInfoMetadata.h.
References getFlags().
isObjectPointer()
bool llvm::DILocalVariable::isObjectPointer () const inline
Definition at line 2810 of file DebugInfoMetadata.h.
References getFlags().
isParameter()
bool llvm::DILocalVariable::isParameter () const inline
Definition at line 2805 of file DebugInfoMetadata.h.
References Arg.
Referenced by llvm::DebugHandlerBase::beginFunction(), and llvm::SelectionDAGBuilder::handleDebugValue().
isValidLocationForIntrinsic()
bool llvm::DILocalVariable::isValidLocationForIntrinsic (const DILocation * DL) const inline
Check that a location is valid for this variable.
Check that DL exists, is in the same subprogram, and has the same inlined-at location as this. (Otherwise, it's not a valid attachment to a DbgInfoIntrinsic.)
Definition at line 2822 of file DebugInfoMetadata.h.
References getScope(), and llvm::DILocalScope::getSubprogram().
Referenced by llvm::calculateDbgEntityHistory(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
setIsNotModified()
void llvm::DILocalVariable::setIsNotModified () inline
Set the flag if an argument is unmodified.
Definition at line 2815 of file DebugInfoMetadata.h.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 2749 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 2750 of file DebugInfoMetadata.h.
Member Data Documentation
AlignInBits
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::AlignInBits
Definition at line 2793 of file DebugInfoMetadata.h.
Arg [1/2]
Metadata MDString Metadata unsigned Metadata unsigned llvm::DILocalVariable::Arg
Definition at line 2792 of file DebugInfoMetadata.h.
Arg [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Arg
Definition at line 2794 of file DebugInfoMetadata.h.
File [1/2]
Metadata MDString Metadata* llvm::DILocalVariable::File
Definition at line 2791 of file DebugInfoMetadata.h.
File [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::File
Definition at line 2794 of file DebugInfoMetadata.h.
Flags [1/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags llvm::DILocalVariable::Flags
Definition at line 2793 of file DebugInfoMetadata.h.
Flags [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Flags
Definition at line 2794 of file DebugInfoMetadata.h.
Line [1/2]
Metadata MDString Metadata unsigned llvm::DILocalVariable::Line
Definition at line 2792 of file DebugInfoMetadata.h.
Line [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Line
Definition at line 2794 of file DebugInfoMetadata.h.
Name [1/2]
Metadata MDString* llvm::DILocalVariable::Name
Definition at line 2791 of file DebugInfoMetadata.h.
Name [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Name
Definition at line 2794 of file DebugInfoMetadata.h.
Scope [1/2]
Metadata* llvm::DILocalVariable::Scope
Definition at line 2791 of file DebugInfoMetadata.h.
Scope [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Scope
Definition at line 2794 of file DebugInfoMetadata.h.
Type [1/2]
Metadata MDString Metadata unsigned Metadata* llvm::DILocalVariable::Type
Definition at line 2792 of file DebugInfoMetadata.h.
Type [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::Type
Definition at line 2794 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp