LLVM: llvm::JITSymbol Class Reference
llvm::JITSymbol Class Reference
Represents a symbol in the JIT.
#include "llvm/ExecutionEngine/JITSymbol.h"
Public Types
using GetAddressFtor = std::function< Expected< JITTargetAddress >()>
Public Member Functions
JITSymbol (std::nullptr_t)
Create a 'null' symbol, used to represent a "symbol not found" result from a successful (non-erroneous) lookup.
JITSymbol (Error Err)
Create a JITSymbol representing an error in the symbol lookup process (e.g.
JITSymbol (JITTargetAddress Addr, JITSymbolFlags Flags)
Create a symbol for a definition with a known address.
JITSymbol (JITEvaluatedSymbol Sym)
Construct a JITSymbol from a JITEvaluatedSymbol.
JITSymbol (GetAddressFtor GetAddress, JITSymbolFlags Flags)
Create a symbol for a definition that doesn't have a known address yet.
JITSymbol (const JITSymbol &)=delete
JITSymbol & operator= (const JITSymbol &)=delete
JITSymbol (JITSymbol &&Other)
JITSymbol & operator= (JITSymbol &&Other)
~JITSymbol ()
operator bool () const
Returns true if the symbol exists, false otherwise.
Error takeError ()
Move the error field value out of this JITSymbol.
Expected< JITTargetAddress > getAddress ()
Get the address of the symbol in the target address space.
JITSymbolFlags getFlags () const
Detailed Description
Represents a symbol in the JIT.
Definition at line 218 of file JITSymbol.h.
Member Typedef Documentation
GetAddressFtor
using llvm::JITSymbol::GetAddressFtor = std::function<Expected<JITTargetAddress>()>
Definition at line 220 of file JITSymbol.h.
Constructor & Destructor Documentation
JITSymbol() [1/7]
llvm::JITSymbol::JITSymbol (std::nullptr_t) inline
Create a 'null' symbol, used to represent a "symbol not found" result from a successful (non-erroneous) lookup.
Definition at line 224 of file JITSymbol.h.
JITSymbol() [2/7]
llvm::JITSymbol::JITSymbol (Error Err) inline
Create a JITSymbol representing an error in the symbol lookup process (e.g.
a network failure during a remote lookup).
Definition at line 229 of file JITSymbol.h.
JITSymbol() [3/7]
llvm::JITSymbol::JITSymbol (JITTargetAddress Addr, JITSymbolFlags Flags) inline
Create a symbol for a definition with a known address.
Definition at line 233 of file JITSymbol.h.
JITSymbol() [4/7]
llvm::JITSymbol::JITSymbol (JITEvaluatedSymbol Sym) inline
Construct a JITSymbol from a JITEvaluatedSymbol.
Definition at line 237 of file JITSymbol.h.
JITSymbol() [5/7]
llvm::JITSymbol::JITSymbol (GetAddressFtor GetAddress, JITSymbolFlags Flags) inline
Create a symbol for a definition that doesn't have a known address yet.
Parameters
GetAddress A functor to materialize a definition (fixing the address) on demand.
This constructor allows a JIT layer to provide a reference to a symbol definition without actually materializing the definition up front. The user can materialize the definition at any time by calling the getAddress method.
Definition at line 249 of file JITSymbol.h.
JITSymbol() [6/7]
llvm::JITSymbol::JITSymbol (const JITSymbol &) delete
JITSymbol() [7/7]
llvm::JITSymbol::JITSymbol (JITSymbol && Other) inline
Definition at line 255 of file JITSymbol.h.
References CachedAddr, Err, llvm::JITSymbolFlags::hasError(), and Other.
~JITSymbol()
llvm::JITSymbol::~JITSymbol () inline
Definition at line 273 of file JITSymbol.h.
References CachedAddr, Err, llvm::JITSymbolFlags::hasError(), and llvm::Error::~Error().
Member Function Documentation
getAddress()
Expected< JITTargetAddress > llvm::JITSymbol::getAddress () inline
Get the address of the symbol in the target address space.
Returns '0' if the symbol does not exist.
Definition at line 294 of file JITSymbol.h.
References assert(), CachedAddr, and llvm::JITSymbolFlags::hasError().
getFlags()
JITSymbolFlags llvm::JITSymbol::getFlags () const inline
Definition at line 307 of file JITSymbol.h.
Referenced by llvm::orc::RemoteObjectLayer< RPCEndpoint >::jitSymbolToRemote().
operator bool()
llvm::JITSymbol::operator bool () const inline explicit
Returns true if the symbol exists, false otherwise.
Definition at line 281 of file JITSymbol.h.
References CachedAddr, and llvm::JITSymbolFlags::hasError().
operator=() [1/2]
JITSymbol & llvm::JITSymbol::operator= (const JITSymbol &) delete
operator=() [2/2]
JITSymbol & llvm::JITSymbol::operator= (JITSymbol && Other) inline
Definition at line 263 of file JITSymbol.h.
References CachedAddr, Err, llvm::JITSymbolFlags::hasError(), and Other.
takeError()
Error llvm::JITSymbol::takeError () inline
Move the error field value out of this JITSymbol.
Definition at line 286 of file JITSymbol.h.
References Err, llvm::JITSymbolFlags::hasError(), and llvm::Error::success().
Referenced by llvm::orc::RemoteObjectLayer< RPCEndpoint >::jitSymbolToRemote().
Member Data Documentation
CachedAddr
JITTargetAddress llvm::JITSymbol::CachedAddr
Definition at line 312 of file JITSymbol.h.
Referenced by getAddress(), JITSymbol(), operator bool(), operator=(), and ~JITSymbol().
Err
Error llvm::JITSymbol::Err
Definition at line 313 of file JITSymbol.h.
Referenced by JITSymbol(), operator=(), takeError(), and ~JITSymbol().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITSymbol.h