LLVM: llvm::cl::opt_storage< DataType, ExternalStorage, isClass > Class Template Reference
llvm::cl::opt_storage< DataType, ExternalStorage, isClass > Class Template Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
opt_storage ()=default
bool setLocation (Option &O, DataType &L)
template<class T >
void setValue (const T &V, bool initial=false)
DataType & getValue ()
const DataType & getValue () const
operator DataType () const
const OptionValue< DataType > & getDefault () const
Detailed Description
template<class DataType, bool ExternalStorage, bool isClass>
class llvm::cl::opt_storage< DataType, ExternalStorage, isClass >
Definition at line 1234 of file CommandLine.h.
Constructor & Destructor Documentation
opt_storage()
template<class DataType , bool ExternalStorage, bool isClass> llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::opt_storage () default
Member Function Documentation
getDefault()
template<class DataType , bool ExternalStorage, bool isClass> const OptionValue< DataType > & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getDefault () const inline
Definition at line 1273 of file CommandLine.h.
getValue() [1/2]
template<class DataType , bool ExternalStorage, bool isClass> DataType & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getValue () inline
Definition at line 1262 of file CommandLine.h.
Referenced by llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::operator DataType(), llvm::cl::opt_storage< DataType, false, false >::operator DataType(), and llvm::cl::opt< DataType, ExternalStorage, ParserClass >::operator=().
getValue() [2/2]
template<class DataType , bool ExternalStorage, bool isClass> const DataType & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getValue () const inline
Definition at line 1266 of file CommandLine.h.
operator DataType()
template<class DataType , bool ExternalStorage, bool isClass> llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::operator DataType () const inline
Definition at line 1271 of file CommandLine.h.
References llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getValue().
setLocation()
template<class DataType , bool ExternalStorage, bool isClass> bool llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::setLocation (Option & O, DataType & L) inline
Definition at line 1247 of file CommandLine.h.
setValue()
template<class DataType , bool ExternalStorage, bool isClass> template<class T > void llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::setValue (const T & V, bool initial = false) inline
Definition at line 1255 of file CommandLine.h.
Referenced by llvm::cl::opt< DataType, ExternalStorage, ParserClass >::operator=(), and llvm::cl::opt< DataType, ExternalStorage, ParserClass >::setInitialValue().
The documentation for this class was generated from the following file:
include/llvm/Support/CommandLine.h