LLVM: llvm::ImmutableList< T >::iterator Class Reference
llvm::ImmutableList< T >::iterator Class Reference
#include "llvm/ADT/ImmutableList.h"
Public Member Functions
iterator ()=default
iterator (ImmutableList l)
iterator & operator++ ()
bool operator== (const iterator &I) const
bool operator!= (const iterator &I) const
const value_type & operator* () const
const std::remove_reference< value_type >::type * operator-> () const
ImmutableList getList () const
Detailed Description
template<typename T>
class llvm::ImmutableList< T >::iterator
Definition at line 85 of file ImmutableList.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T > llvm::ImmutableList< T >::iterator::iterator () default
iterator() [2/2]
template<typename T > llvm::ImmutableList< T >::iterator::iterator (ImmutableList l) inline
Definition at line 90 of file ImmutableList.h.
Member Function Documentation
getList()
template<typename T > ImmutableList llvm::ImmutableList< T >::iterator::getList () const inline
Definition at line 100 of file ImmutableList.h.
operator!=()
template<typename T > bool llvm::ImmutableList< T >::iterator::operator!= (const iterator & I) const inline
Definition at line 94 of file ImmutableList.h.
References I.
operator*()
template<typename T > const value_type & llvm::ImmutableList< T >::iterator::operator* () const inline
Definition at line 95 of file ImmutableList.h.
References llvm::ImmutableListImpl< T >::getHead().
operator++()
template<typename T > iterator & llvm::ImmutableList< T >::iterator::operator++ () inline
Definition at line 92 of file ImmutableList.h.
References llvm::ImmutableListImpl< T >::getTail().
operator->()
template<typename T > const std::remove_reference< value_type >::type * llvm::ImmutableList< T >::iterator::operator-> () const inline
Definition at line 96 of file ImmutableList.h.
References llvm::ImmutableListImpl< T >::getHead().
operator==()
template<typename T > bool llvm::ImmutableList< T >::iterator::operator== (const iterator & I) const inline
Definition at line 93 of file ImmutableList.h.
References I.
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableList.h