LLVM: llvm::NVPTXFloatMCExpr Class Reference
llvm::NVPTXFloatMCExpr Class Reference
#include "Target/NVPTX/NVPTXMCExpr.h"
Public Types
enum VariantKind { VK_NVPTX_None , VK_NVPTX_HALF_PREC_FLOAT , VK_NVPTX_SINGLE_PREC_FLOAT , VK_NVPTX_DOUBLE_PREC_FLOAT }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
APFloat getAPFloat () const
getSubExpr - Get the child of this expression.
Public Member Functions inherited from llvm::MCTargetExpr
virtual void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const =0
virtual bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const =0
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
virtual void visitUsedExpr (MCStreamer &Streamer) const =0
virtual MCFragment * findAssociatedFragment () const =0
virtual void fixELFSymbolsInTLSFixups (MCAssembler &) const =0
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const NVPTXFloatMCExpr * create (VariantKind Kind, const APFloat &Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * createConstantFPHalf (const APFloat &Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * createConstantFPSingle (const APFloat &Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * createConstantFPDouble (const APFloat &Flt, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Definition at line 20 of file NVPTXMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::NVPTXFloatMCExpr::VariantKind
Enumerator
VK_NVPTX_None
VK_NVPTX_HALF_PREC_FLOAT
VK_NVPTX_SINGLE_PREC_FLOAT
VK_NVPTX_DOUBLE_PREC_FLOAT
Definition at line 22 of file NVPTXMCExpr.h.
Member Function Documentation
classof()
static bool llvm::NVPTXFloatMCExpr::classof (const MCExpr * E) inline static
Definition at line 82 of file NVPTXMCExpr.h.
References E, and llvm::MCExpr::Target.
create()
const NVPTXFloatMCExpr * NVPTXFloatMCExpr::create (VariantKind Kind, const APFloat & Flt, MCContext & Ctx) static
Definition at line 19 of file NVPTXMCExpr.cpp.
Referenced by createConstantFPDouble(), createConstantFPHalf(), and createConstantFPSingle().
createConstantFPDouble()
static const NVPTXFloatMCExpr * llvm::NVPTXFloatMCExpr::createConstantFPDouble (const APFloat & Flt, MCContext & Ctx) inline static
Definition at line 53 of file NVPTXMCExpr.h.
References create(), and VK_NVPTX_DOUBLE_PREC_FLOAT.
createConstantFPHalf()
static const NVPTXFloatMCExpr * llvm::NVPTXFloatMCExpr::createConstantFPHalf (const APFloat & Flt, MCContext & Ctx) inline static
Definition at line 43 of file NVPTXMCExpr.h.
References create(), and VK_NVPTX_HALF_PREC_FLOAT.
createConstantFPSingle()
static const NVPTXFloatMCExpr * llvm::NVPTXFloatMCExpr::createConstantFPSingle (const APFloat & Flt, MCContext & Ctx) inline static
Definition at line 48 of file NVPTXMCExpr.h.
References create(), and VK_NVPTX_SINGLE_PREC_FLOAT.
evaluateAsRelocatableImpl()
bool llvm::NVPTXFloatMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 71 of file NVPTXMCExpr.h.
findAssociatedFragment()
MCFragment * llvm::NVPTXFloatMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 77 of file NVPTXMCExpr.h.
fixELFSymbolsInTLSFixups()
void llvm::NVPTXFloatMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 80 of file NVPTXMCExpr.h.
getAPFloat()
APFloat llvm::NVPTXFloatMCExpr::getAPFloat () const inline
getSubExpr - Get the child of this expression.
Definition at line 66 of file NVPTXMCExpr.h.
Referenced by printImpl().
getKind()
VariantKind llvm::NVPTXFloatMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 63 of file NVPTXMCExpr.h.
printImpl()
void NVPTXFloatMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 23 of file NVPTXMCExpr.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convert(), llvm::format_hex_no_prefix(), getAPFloat(), llvm::APInt::getZExtValue(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, llvm::APFloatBase::rmNearestTiesToEven, VK_NVPTX_DOUBLE_PREC_FLOAT, VK_NVPTX_HALF_PREC_FLOAT, and VK_NVPTX_SINGLE_PREC_FLOAT.
visitUsedExpr()
void llvm::NVPTXFloatMCExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 76 of file NVPTXMCExpr.h.
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXMCExpr.h
lib/Target/NVPTX/NVPTXMCExpr.cpp