LLVM: QualType Class Reference
QualType Class Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
QualType (const Node *Child_, Qualifiers Quals_)
template<typename Fn >
void match (Fn F) const
bool hasRHSComponentSlow (OutputStream &S) const override
bool hasArraySlow (OutputStream &S) const override
bool hasFunctionSlow (OutputStream &S) const override
void printLeft (OutputStream &S) const override
void printRight (OutputStream &S) const override
Public Member Functions inherited from Node
Node (Kind K_, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputStream &S) const
bool hasArray (OutputStream &S) const
bool hasFunction (OutputStream &S) const
Kind getKind () const
virtual bool hasRHSComponentSlow (OutputStream &) const
virtual bool hasArraySlow (OutputStream &) const
virtual bool hasFunctionSlow (OutputStream &) const
virtual const Node * getSyntaxNode (OutputStream &) const
void print (OutputStream &S) const
virtual void printLeft (OutputStream &) const =0
virtual void printRight (OutputStream &) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Protected Member Functions
void printQuals (OutputStream &S) const
Protected Attributes
const Qualifiers Quals
const Node * Child
Additional Inherited Members
Public Types inherited from Node
enum Kind : unsigned char
enum class Cache : unsigned char { Yes , No , Unknown }
Three-way bool to track a cached value.
Public Attributes inherited from Node
Cache RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache
Track if this node is a (possibly qualified) array type.
Cache FunctionCache
Track if this node is a (possibly qualified) function type.
Detailed Description
Definition at line 306 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
QualType()
QualType::QualType (const Node * Child_, Qualifiers Quals_) inline
Definition at line 321 of file ItaniumDemangle.h.
Member Function Documentation
hasArraySlow()
bool QualType::hasArraySlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 331 of file ItaniumDemangle.h.
References Child, and Node::hasArray().
hasFunctionSlow()
bool QualType::hasFunctionSlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 334 of file ItaniumDemangle.h.
References Child, and Node::hasFunction().
hasRHSComponentSlow()
bool QualType::hasRHSComponentSlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 328 of file ItaniumDemangle.h.
References Child, and Node::hasRHSComponent().
match()
template<typename Fn > void QualType::match (Fn F) const inline
Definition at line 326 of file ItaniumDemangle.h.
References Child, F, and Quals.
printLeft()
void QualType::printLeft (OutputStream & S) const inline override virtual
Implements Node.
Definition at line 338 of file ItaniumDemangle.h.
References Child, Node::printLeft(), and printQuals().
printQuals()
void QualType::printQuals (OutputStream & S) const inline protected
Definition at line 311 of file ItaniumDemangle.h.
References QualConst, QualRestrict, Quals, and QualVolatile.
Referenced by printLeft().
printRight()
void QualType::printRight (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 343 of file ItaniumDemangle.h.
References Child, and Node::printRight().
Member Data Documentation
Child
const Node* QualType::Child protected
Definition at line 309 of file ItaniumDemangle.h.
Referenced by hasArraySlow(), hasFunctionSlow(), hasRHSComponentSlow(), match(), printLeft(), and printRight().
Quals
const Qualifiers QualType::Quals protected
Definition at line 308 of file ItaniumDemangle.h.
Referenced by match(), and printQuals().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h