LLVM: llvm::VPRecipeBase Class Reference
llvm::VPRecipeBase Class Reference abstract
VPRecipeBase is a base class modeling a sequence of one or more output IR instructions.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Member Functions
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Detailed Description
VPRecipeBase is a base class modeling a sequence of one or more output IR instructions.
Definition at line 568 of file VPlan.h.
Member Typedef Documentation
VPRecipeTy
using llvm::VPRecipeBase::VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Values of this enumeration are kept in the SubclassID field of the VPRecipeBase objects. They are used for concrete type identification.
Definition at line 582 of file VPlan.h.
Constructor & Destructor Documentation
VPRecipeBase()
llvm::VPRecipeBase::VPRecipeBase (const unsigned char SC) inline
Definition at line 595 of file VPlan.h.
~VPRecipeBase()
virtual llvm::VPRecipeBase::~VPRecipeBase () virtual default
Member Function Documentation
eraseFromParent()
iplist< VPRecipeBase >::iterator VPRecipeBase::eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Returns
an iterator pointing to the element after the erased one
Definition at line 282 of file VPlan.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::getIterator(), getParent(), and llvm::VPBasicBlock::getRecipeList().
Referenced by llvm::VPlanHCFGTransforms::VPInstructionsToVPRecipes().
execute()
virtual void llvm::VPRecipeBase::execute (struct VPTransformState & State) pure virtual
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
Implemented in llvm::VPInstruction, llvm::VPWidenRecipe, llvm::VPWidenIntOrFpInductionRecipe, llvm::VPWidenPHIRecipe, llvm::VPBlendRecipe, llvm::VPInterleaveRecipe, llvm::VPReplicateRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPPredInstPHIRecipe, and llvm::VPWidenMemoryInstructionRecipe.
getParent() [1/2]
VPBasicBlock * llvm::VPRecipeBase::getParent () inline
Returns
the VPBasicBlock which this VPRecipe belongs to.
Definition at line 604 of file VPlan.h.
Referenced by eraseFromParent(), and insertBefore().
getParent() [2/2]
const VPBasicBlock * llvm::VPRecipeBase::getParent () const inline
Definition at line 605 of file VPlan.h.
getVPRecipeID()
unsigned llvm::VPRecipeBase::getVPRecipeID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 601 of file VPlan.h.
Referenced by llvm::VPWidenRecipe::classof(), llvm::VPWidenIntOrFpInductionRecipe::classof(), llvm::VPWidenPHIRecipe::classof(), llvm::VPBlendRecipe::classof(), llvm::VPInterleaveRecipe::classof(), llvm::VPReplicateRecipe::classof(), llvm::VPBranchOnMaskRecipe::classof(), llvm::VPPredInstPHIRecipe::classof(), and llvm::VPWidenMemoryInstructionRecipe::classof().
insertBefore()
void VPRecipeBase::insertBefore (VPRecipeBase * InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
Definition at line 277 of file VPlan.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), llvm::VPBasicBlock::getRecipeList(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by llvm::VPlanHCFGTransforms::VPInstructionsToVPRecipes().
print()
virtual void llvm::VPRecipeBase::print (raw_ostream & O, const Twine & Indent) const pure virtual
Each recipe prints itself.
Implemented in llvm::VPInstruction, llvm::VPWidenRecipe, llvm::VPWidenIntOrFpInductionRecipe, llvm::VPWidenPHIRecipe, llvm::VPBlendRecipe, llvm::VPInterleaveRecipe, llvm::VPReplicateRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPPredInstPHIRecipe, and llvm::VPWidenMemoryInstructionRecipe.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp