LLVM: llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type > Class Template Reference
llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type > Class Template Reference
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const remote::DirectBufferWriter &DBW)
static Error deserialize (ChannelT &C, remote::DirectBufferWriter &DBW)
Detailed Description
template<typename ChannelT>
class llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
Definition at line 109 of file OrcRemoteTargetRPCAPI.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::deserialize (ChannelT & C, remote::DirectBufferWriter & DBW) inline static
Definition at line 122 of file OrcRemoteTargetRPCAPI.h.
References C, llvm::orc::rpc::deserializeSeq(), and Size.
serialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize (ChannelT & C, const remote::DirectBufferWriter & DBW) inline static
Definition at line 114 of file OrcRemoteTargetRPCAPI.h.
References C, llvm::orc::remote::DirectBufferWriter::getDst(), llvm::orc::remote::DirectBufferWriter::getSize(), llvm::orc::remote::DirectBufferWriter::getSrc(), and llvm::orc::rpc::serializeSeq().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h