LLVM: llvm::XCoreSubtarget Class Reference
llvm::XCoreSubtarget Class Reference
#include "Target/XCore/XCoreSubtarget.h"
Public Member Functions
XCoreSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
const XCoreInstrInfo * getInstrInfo () const override
const XCoreFrameLowering * getFrameLowering () const override
const XCoreTargetLowering * getTargetLowering () const override
const XCoreSelectionDAGInfo * getSelectionDAGInfo () const override
const TargetRegisterInfo * getRegisterInfo () const override
Detailed Description
Definition at line 31 of file XCoreSubtarget.h.
Constructor & Destructor Documentation
XCoreSubtarget()
XCoreSubtarget::XCoreSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 27 of file XCoreSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const XCoreFrameLowering * llvm::XCoreSubtarget::getFrameLowering () const inline override
Definition at line 50 of file XCoreSubtarget.h.
getInstrInfo()
const XCoreInstrInfo * llvm::XCoreSubtarget::getInstrInfo () const inline override
Definition at line 49 of file XCoreSubtarget.h.
Referenced by llvm::XCoreTargetLowering::EmitInstrWithCustomInserter().
getRegisterInfo()
const TargetRegisterInfo * llvm::XCoreSubtarget::getRegisterInfo () const inline override
Definition at line 59 of file XCoreSubtarget.h.
References llvm::XCoreInstrInfo::getRegisterInfo().
Referenced by llvm::XCoreTargetLowering::XCoreTargetLowering().
getSelectionDAGInfo()
const XCoreSelectionDAGInfo * llvm::XCoreSubtarget::getSelectionDAGInfo () const inline override
Definition at line 56 of file XCoreSubtarget.h.
getTargetLowering()
const XCoreTargetLowering * llvm::XCoreSubtarget::getTargetLowering () const inline override
Definition at line 53 of file XCoreSubtarget.h.
ParseSubtargetFeatures()
void llvm::XCoreSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
The documentation for this class was generated from the following files:
lib/Target/XCore/XCoreSubtarget.h
lib/Target/XCore/XCoreSubtarget.cpp