LLVM: llvm::GVN Class Reference
llvm::GVN Class Reference
The core GVN pass object.
#include "llvm/Transforms/Scalar/GVN.h"
Classes
struct Expression
class ValueTable
This class holds the mapping between values and value numbers.
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Run the pass over the function.
void markInstructionForDeletion (Instruction *I)
This removes the specified instruction from our various maps and marks it for deletion.
DominatorTree & getDominatorTree () const
AliasAnalysis * getAliasAnalysis () const
MemoryDependenceResults & getMemDep () const
Friends
class gvn::GVNLegacyPass
struct DenseMapInfo< Expression >
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GVN >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The core GVN pass object.
FIXME: We should have a good summary of the GVN algorithm implemented by this particular pass here.
Definition at line 68 of file GVN.h.
Member Function Documentation
getAliasAnalysis()
AliasAnalysis * llvm::GVN::getAliasAnalysis () const inline
Definition at line 83 of file GVN.h.
References llvm::GVN::ValueTable::getAliasAnalysis().
getDominatorTree()
DominatorTree & llvm::GVN::getDominatorTree () const inline
Definition at line 82 of file GVN.h.
Referenced by ConstructSSAForLoadSet().
getMemDep()
MemoryDependenceResults & llvm::GVN::getMemDep () const inline
Definition at line 84 of file GVN.h.
Referenced by llvm::gvn::AvailableValue::MaterializeAdjustedValue().
markInstructionForDeletion()
void llvm::GVN::markInstructionForDeletion (Instruction * I) inline
This removes the specified instruction from our various maps and marks it for deletion.
Definition at line 77 of file GVN.h.
References llvm::GVN::ValueTable::erase(), and I.
run()
PreservedAnalyses GVN::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
Definition at line 610 of file GVN.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserve().
Friends And Related Function Documentation
DenseMapInfo< Expression >
friend struct DenseMapInfo< Expression > friend
Definition at line 154 of file GVN.h.
gvn::GVNLegacyPass
friend class gvn::GVNLegacyPass friend
Definition at line 154 of file GVN.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVN.h
lib/Transforms/Scalar/GVN.cpp