LLVM: llvm::DWARFDebugLoc Class Reference
llvm::DWARFDebugLoc Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
Classes
struct Entry
A single location within a location list.
struct LocationList
A list of locations that contain one variable.
Public Member Functions
void dump (raw_ostream &OS, const MCRegisterInfo *RegInfo, Optional< uint64_t > Offset) const
Print the location lists found within the debug_loc section.
void parse (const DWARFDataExtractor &data)
Parse the debug_loc section accessible via the 'data' parameter using the address size also given in 'data' to interpret the address ranges.
LocationList const * getLocationListAtOffset (uint64_t Offset) const
Return the location list at the given offset or nullptr.
Optional< LocationList > parseOneLocationList (DWARFDataExtractor Data, uint32_t *Offset)
Detailed Description
Definition at line 23 of file DWARFDebugLoc.h.
Member Function Documentation
dump()
void DWARFDebugLoc::dump (raw_ostream & OS, const MCRegisterInfo * RegInfo, Optional< uint64_t > Offset) const
Print the location lists found within the debug_loc section.
Definition at line 67 of file DWARFDebugLoc.cpp.
References llvm::format(), getLocationListAtOffset(), and MRI.
Referenced by llvm::DWARFContext::dump().
getLocationListAtOffset()
DWARFDebugLoc::LocationList const * DWARFDebugLoc::getLocationListAtOffset (uint64_t Offset) const
Return the location list at the given offset or nullptr.
Definition at line 59 of file DWARFDebugLoc.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DWARFDebugLoc::LocationList::Offset, and llvm::partition_point().
Referenced by dump().
parse()
void DWARFDebugLoc::parse (const DWARFDataExtractor & data)
Parse the debug_loc section accessible via the 'data' parameter using the address size also given in 'data' to interpret the address ranges.
Definition at line 131 of file DWARFDebugLoc.cpp.
References llvm::WithColor::error(), llvm::DataExtractor::getAddressSize(), llvm::DataExtractor::isLittleEndian(), llvm::DataExtractor::isValidOffset(), parseOneLocationList(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
parseOneLocationList()
Optional< DWARFDebugLoc::LocationList > DWARFDebugLoc::parseOneLocationList (DWARFDataExtractor Data, uint32_t * Offset)
Definition at line 87 of file DWARFDebugLoc.cpp.
References llvm::copy(), llvm::Data, E, llvm::DWARFDebugLoc::LocationList::Entries, llvm::WithColor::error(), llvm::None, llvm::DWARFDebugLoc::LocationList::Offset, and llvm::StringRef::size().
Referenced by parse().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
lib/DebugInfo/DWARF/DWARFDebugLoc.cpp