LLVM: llvm::memoryaccess_def_iterator_base< T > Class Template Reference
llvm::memoryaccess_def_iterator_base< T > Class Template Reference
Iterator base class used to implement const and non-const iterators over the defining accesses of a MemoryAccess.
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
memoryaccess_def_iterator_base (T *Start)
memoryaccess_def_iterator_base ()=default
bool operator== (const memoryaccess_def_iterator_base &Other) const
BasicBlock * getPhiArgBlock () const
BaseT::iterator::pointer operator* () const
memoryaccess_def_iterator_base & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< memoryaccess_def_iterator_base< T >, std::forward_iterator_tag, T, ptrdiff_t, T *, T * >
memoryaccess_def_iterator_base< T > operator+ (ptrdiff_t n) const
memoryaccess_def_iterator_base< T > operator- (ptrdiff_t n) const
memoryaccess_def_iterator_base< T > & operator++ ()
memoryaccess_def_iterator_base< T > operator++ (int)
memoryaccess_def_iterator_base< T > & operator-- ()
memoryaccess_def_iterator_base< T > operator-- (int)
bool operator!= (const memoryaccess_def_iterator_base< T > &RHS) const
bool operator> (const memoryaccess_def_iterator_base< T > &RHS) const
bool operator<= (const memoryaccess_def_iterator_base< T > &RHS) const
bool operator>= (const memoryaccess_def_iterator_base< T > &RHS) const
T * operator-> ()
T * operator-> () const
ReferenceProxy operator[] (ptrdiff_t n)
ReferenceProxy operator[] (ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< memoryaccess_def_iterator_base< T >, std::forward_iterator_tag, T, ptrdiff_t, T *, T * >
enum
Detailed Description
template<class T>
class llvm::memoryaccess_def_iterator_base< T >
Iterator base class used to implement const and non-const iterators over the defining accesses of a MemoryAccess.
Definition at line 1079 of file MemorySSA.h.
Constructor & Destructor Documentation
memoryaccess_def_iterator_base() [1/2]
template<class T > llvm::memoryaccess_def_iterator_base< T >::memoryaccess_def_iterator_base (T * Start) inline
Definition at line 1086 of file MemorySSA.h.
memoryaccess_def_iterator_base() [2/2]
template<class T > llvm::memoryaccess_def_iterator_base< T >::memoryaccess_def_iterator_base () default
Member Function Documentation
getPhiArgBlock()
template<class T > BasicBlock * llvm::memoryaccess_def_iterator_base< T >::getPhiArgBlock () const inline
Definition at line 1099 of file MemorySSA.h.
References assert(), and llvm::MemoryPhi::getIncomingBlock().
Referenced by llvm::upward_defs_iterator::getPhiArgBlock().
operator*()
template<class T > BaseT::iterator::pointer llvm::memoryaccess_def_iterator_base< T >::operator* () const inline
Definition at line 1105 of file MemorySSA.h.
References assert().
operator++()
template<class T > memoryaccess_def_iterator_base & llvm::memoryaccess_def_iterator_base< T >::operator++ () inline
Definition at line 1115 of file MemorySSA.h.
References assert().
operator==()
template<class T > bool llvm::memoryaccess_def_iterator_base< T >::operator== (const memoryaccess_def_iterator_base< T > & Other) const inline
Definition at line 1089 of file MemorySSA.h.
References Other.
The documentation for this class was generated from the following file:
include/llvm/Analysis/MemorySSA.h