LLVM: llvm::LanaiSubtarget Class Reference
llvm::LanaiSubtarget Class Reference
#include "Target/Lanai/LanaiSubtarget.h"
Public Member Functions
LanaiSubtarget (const Triple &TargetTriple, StringRef Cpu, StringRef FeatureString, const TargetMachine &TM, const TargetOptions &Options, CodeModel::Model CodeModel, CodeGenOpt::Level OptLevel)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
LanaiSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void initSubtargetFeatures (StringRef CPU, StringRef FS)
bool enableMachineScheduler () const override
const LanaiInstrInfo * getInstrInfo () const override
const TargetFrameLowering * getFrameLowering () const override
const LanaiRegisterInfo * getRegisterInfo () const override
const LanaiTargetLowering * getTargetLowering () const override
const LanaiSelectionDAGInfo * getSelectionDAGInfo () const override
Detailed Description
Definition at line 30 of file LanaiSubtarget.h.
Constructor & Destructor Documentation
LanaiSubtarget()
LanaiSubtarget::LanaiSubtarget (const Triple & TargetTriple, StringRef Cpu, StringRef FeatureString, const TargetMachine & TM, const TargetOptions & Options, CodeModel::Model CodeModel, CodeGenOpt::Level OptLevel)
Definition at line 39 of file LanaiSubtarget.cpp.
Member Function Documentation
enableMachineScheduler()
bool llvm::LanaiSubtarget::enableMachineScheduler () const inline override
Definition at line 47 of file LanaiSubtarget.h.
getFrameLowering()
const TargetFrameLowering * llvm::LanaiSubtarget::getFrameLowering () const inline override
Definition at line 51 of file LanaiSubtarget.h.
getInstrInfo()
const LanaiInstrInfo * llvm::LanaiSubtarget::getInstrInfo () const inline override
Definition at line 49 of file LanaiSubtarget.h.
Referenced by llvm::LanaiFrameLowering::emitEpilogue(), and llvm::LanaiFrameLowering::emitPrologue().
getRegisterInfo()
const LanaiRegisterInfo * llvm::LanaiSubtarget::getRegisterInfo () const inline override
Definition at line 55 of file LanaiSubtarget.h.
References llvm::LanaiInstrInfo::getRegisterInfo().
Referenced by llvm::LanaiFrameLowering::determineCalleeSaves(), and llvm::LanaiTargetLowering::LanaiTargetLowering().
getSelectionDAGInfo()
const LanaiSelectionDAGInfo * llvm::LanaiSubtarget::getSelectionDAGInfo () const inline override
Definition at line 63 of file LanaiSubtarget.h.
getTargetLowering()
const LanaiTargetLowering * llvm::LanaiSubtarget::getTargetLowering () const inline override
Definition at line 59 of file LanaiSubtarget.h.
initializeSubtargetDependencies()
LanaiSubtarget & LanaiSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 33 of file LanaiSubtarget.cpp.
References initSubtargetFeatures().
initSubtargetFeatures()
void LanaiSubtarget::initSubtargetFeatures (StringRef CPU, StringRef FS)
Definition at line 25 of file LanaiSubtarget.cpp.
References ParseSubtargetFeatures().
Referenced by initializeSubtargetDependencies().
ParseSubtargetFeatures()
void llvm::LanaiSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by initSubtargetFeatures().
The documentation for this class was generated from the following files:
lib/Target/Lanai/LanaiSubtarget.h
lib/Target/Lanai/LanaiSubtarget.cpp