LLVM: llvm::LiveRangeEdit Class Reference
llvm::LiveRangeEdit Class Reference
#include "llvm/CodeGen/LiveRangeEdit.h"
Classes
class Delegate
Callback methods for LiveRangeEdit owners.
struct Remat
Remat - Information needed to rematerialize at a specific location.
Public Types
using iterator = SmallVectorImpl< unsigned >::const_iterator
Iterator for accessing the new registers added by this edit.
Public Member Functions
LiveRangeEdit (LiveInterval *parent, SmallVectorImpl< unsigned > &newRegs, MachineFunction &MF, LiveIntervals &lis, VirtRegMap *vrm, Delegate *delegate=nullptr, SmallPtrSet< MachineInstr *, 32 > *deadRemats=nullptr)
Create a LiveRangeEdit for breaking down parent into smaller pieces.
~LiveRangeEdit () override
LiveInterval & getParent () const
unsigned getReg () const
iterator begin () const
iterator end () const
unsigned size () const
bool empty () const
unsigned get (unsigned idx) const
void pop_back ()
pop_back - It allows LiveRangeEdit users to drop new registers.
ArrayRef< unsigned > regs () const
unsigned createFrom (unsigned OldReg)
createFrom - Create a new virtual register based on OldReg.
LiveInterval & createEmptyInterval ()
create - Create a new register with the same class and original slot as parent.
unsigned create ()
bool anyRematerializable (AliasAnalysis *)
anyRematerializable - Return true if any parent values may be rematerializable.
bool checkRematerializable (VNInfo *VNI, const MachineInstr *DefMI, AliasAnalysis *)
checkRematerializable - Manually add VNI to the list of rematerializable values if DefMI may be rematerializable.
bool canRematerializeAt (Remat &RM, VNInfo *OrigVNI, SlotIndex UseIdx, bool cheapAsAMove)
canRematerializeAt - Determine if ParentVNI can be rematerialized at UseIdx.
SlotIndex rematerializeAt (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, const Remat &RM, const TargetRegisterInfo &, bool Late=false)
rematerializeAt - Rematerialize RM.ParentVNI into DestReg by inserting an instruction into MBB before MI.
void markRematerialized (const VNInfo *ParentVNI)
markRematerialized - explicitly mark a value as rematerialized after doing it manually.
bool didRematerialize (const VNInfo *ParentVNI) const
didRematerialize - Return true if ParentVNI was rematerialized anywhere.
void eraseVirtReg (unsigned Reg)
eraseVirtReg - Notify the delegate that Reg is no longer in use, and try to erase it from LIS.
void eliminateDeadDefs (SmallVectorImpl< MachineInstr * > &Dead, ArrayRef< unsigned > RegsBeingSpilled=None, AliasAnalysis *AA=nullptr)
eliminateDeadDefs - Try to delete machine instructions that are now dead (allDefsAreDead returns true).
void calculateRegClassAndHint (MachineFunction &, const MachineLoopInfo &, const MachineBlockFrequencyInfo &)
calculateRegClassAndHint - Recompute register class and hint for each new register.
Detailed Description
Definition at line 45 of file LiveRangeEdit.h.
Member Typedef Documentation
iterator
using llvm::LiveRangeEdit::iterator = SmallVectorImpl<unsigned>::const_iterator
Iterator for accessing the new registers added by this edit.
Definition at line 158 of file LiveRangeEdit.h.
Constructor & Destructor Documentation
LiveRangeEdit()
llvm::LiveRangeEdit::LiveRangeEdit (LiveInterval * parent, SmallVectorImpl< unsigned > & newRegs, MachineFunction & MF, LiveIntervals & lis, VirtRegMap * vrm, Delegate * delegate = nullptr, SmallPtrSet< MachineInstr *, 32 > * deadRemats = nullptr) inline
Create a LiveRangeEdit for breaking down parent into smaller pieces.
Parameters
parent The register being spilled or split.
newRegs List to receive any new registers created. This needn't be empty initially, any existing registers are ignored.
MF The MachineFunction the live range edit is taking place in.
lis The collection of all live intervals in this function.
vrm Map of virtual registers to physical registers for this function. If NULL, no virtual register map updates will be done. This could be the case if called before Regalloc.
deadRemats The collection of all the instructions defining an original reg and are dead after remat.
Definition at line 138 of file LiveRangeEdit.h.
References MRI, and TII.
~LiveRangeEdit()
llvm::LiveRangeEdit::~LiveRangeEdit () inline override
Definition at line 148 of file LiveRangeEdit.h.
References MRI.
Member Function Documentation
anyRematerializable()
bool LiveRangeEdit::anyRematerializable (AliasAnalysis * aa)
anyRematerializable - Return true if any parent values may be rematerializable.
This function must be called before any rematerialization is attempted.
Definition at line 98 of file LiveRangeEdit.cpp.
References aa.
Referenced by llvm::SplitEditor::reset().
begin()
iterator llvm::LiveRangeEdit::begin () const inline
Definition at line 159 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
calculateRegClassAndHint()
void LiveRangeEdit::calculateRegClassAndHint (MachineFunction & MF, const MachineLoopInfo & Loops, const MachineBlockFrequencyInfo & MBFI)
calculateRegClassAndHint - Recompute register class and hint for each new register.
Definition at line 462 of file LiveRangeEdit.cpp.
References llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::dbgs(), get(), llvm::LiveIntervals::getInterval(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getSubtarget(), I, LLVM_DEBUG, Loops, llvm::printReg(), llvm::MachineRegisterInfo::recomputeRegClass(), llvm::LiveInterval::reg, size(), Size, and TRI.
canRematerializeAt()
bool LiveRangeEdit::canRematerializeAt (Remat & RM, VNInfo * OrigVNI, SlotIndex UseIdx, bool cheapAsAMove)
canRematerializeAt - Determine if ParentVNI can be rematerialized at UseIdx.
It is assumed that parent_.getVNINfoAt(UseIdx) == ParentVNI. When cheapAsAMove is set, only cheap remats are allowed.
Definition at line 140 of file LiveRangeEdit.cpp.
References assert(), llvm::LiveIntervals::getInstructionIndex(), and llvm::TargetInstrInfo::isAsCheapAsAMove().
checkRematerializable()
bool LiveRangeEdit::checkRematerializable (VNInfo * VNI, const MachineInstr * DefMI, AliasAnalysis * aa)
checkRematerializable - Manually add VNI to the list of rematerializable values if DefMI may be rematerializable.
Definition at line 70 of file LiveRangeEdit.cpp.
References aa, assert(), DefMI, and llvm::TargetInstrInfo::isTriviallyReMaterializable().
create()
unsigned llvm::LiveRangeEdit::create () inline
Definition at line 188 of file LiveRangeEdit.h.
References createFrom(), and getReg().
Referenced by llvm::OverlapStats::accumuateCounts(), llvm::HexagonMCInstrInfo::addConstant(), llvm::ConstantPool::addEntry(), llvm::ThinLTOCodeGenerator::addModule(), annotateAllFunctions(), ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), buildSymbolDiff(), llvm::orc::cloneGlobalAliasDecl(), llvm::msf::MSFBuilder::commit(), computeLabelDiff(), llvm::MIRPrinter::convertStackObjects(), llvm::MCSymbolRefExpr::create(), llvm::MinidumpYAML::Object::create(), llvm::InstrProfReader::create(), llvm::IndexedInstrProfReader::create(), llvm::object::ELFObjectFile< ELFT >::create(), llvm::coverage::BinaryCoverageReader::create(), llvm::object::createBinary(), llvm::LTOModule::createInputFile(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::MachineFunction::createMIExtraInfo(), llvm::MachineFunction::createMIExtraInfoWithMarker(), createPtr(), llvm::createRuntimeDyldCOFF(), llvm::createRuntimeDyldELF(), llvm::createRuntimeDyldMachO(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::ObjectFile::createXCOFFObjectFile(), llvm::AsmPrinter::doFinalization(), llvm::AddressPool::emit(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISA(), llvm::AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectVersion(), emitDirectiveRelocJalr(), llvm::MCObjectStreamer::EmitDTPRel32Value(), llvm::MCObjectStreamer::EmitDTPRel64Value(), llvm::WebAssemblyAsmPrinter::EmitEndOfAsmFile(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::CodeViewContext::emitFileChecksums(), llvm::MCStreamer::emitFill(), llvm::AsmPrinter::emitFrameAlloc(), llvm::AsmPrinter::EmitFunctionBody(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::ARMAsmPrinter::EmitJumpTableAddrs(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::ARMAsmPrinter::EmitJumpTableInsts(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), emitNonLazySymbolPointer(), EmitNop(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MCObjectStreamer::EmitRelocDirective(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCObjectStreamer::EmitTPRel32Value(), llvm::MCObjectStreamer::EmitTPRel64Value(), llvm::AVRMCELFStreamer::EmitValueForModiferKind(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MCELFStreamer::EmitWeakReference(), llvm::MCWasmStreamer::EmitWeakReference(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::CodeViewContext::encodeDefRange(), llvm::WasmException::endFunction(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::pdb::DIASession::findSymbolByAddress(), llvm::pdb::DIASession::findSymbolByRVA(), llvm::pdb::DIASession::findSymbolBySectOffset(), llvm::AMDGPUTargetELFStreamer::finish(), llvm::RecordStreamer::flushSymverDirectives(), forceExpAbs(), llvm::PPCMCCodeEmitter::getAbsCondBrEncoding(), GetAbsDifference(), llvm::PPCMCCodeEmitter::getAbsDirectBrEncoding(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsArchive(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget7OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue1SImm16(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueLsl2MMR6(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMPC10(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMR6(), llvm::pdb::DIAEnumSymbols::getChildAtIndex(), llvm::PPCMCCodeEmitter::getCondBrEncoding(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::MipsTargetObjectFile::getDebugThreadLocalSymbol(), llvm::X86ELFTargetObjectFile::getDebugThreadLocalSymbol(), llvm::PPCMCCodeEmitter::getDirectBrEncoding(), llvm::DWARFContext::getDWOContext(), llvm::SystemZMCInstLower::getExpr(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::MipsMCCodeEmitter::getExprOpValue(), llvm::DebugHandlerBase::getFunctionLocalOffsetAfterInsn(), llvm::pdb::DIASession::getGlobalScope(), llvm::PPCMCCodeEmitter::getImm16Encoding(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), getIntrinsicParamType(), llvm::MipsMCCodeEmitter::getJumpTargetOpValue(), llvm::MipsMCCodeEmitter::getJumpTargetOpValueMM(), llvm::PPCMCCodeEmitter::getMemRIEncoding(), llvm::PPCMCCodeEmitter::getMemRIX16Encoding(), llvm::PPCMCCodeEmitter::getMemRIXEncoding(), llvm::pdb::DIAEnumSymbols::getNext(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::MipsMCCodeEmitter::getSimm18Lsl3Encoding(), llvm::MipsMCCodeEmitter::getSimm19Lsl2Encoding(), llvm::pdb::SymbolCache::getSymbolById(), llvm::pdb::DIASession::getSymbolById(), llvm::PPCMCCodeEmitter::getTLSCallEncoding(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::coverage::CoverageMapping::load(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), lowerAddrSpaceCast(), llvm::AsmPrinter::lowerConstant(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::AVRMCInstLower::lowerInstruction(), llvm::ARMAsmPrinter::lowerOperand(), llvm::AArch64MCInstLower::lowerOperand(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::AVRMCInstLower::lowerSymbolOperand(), llvm::BPFMCInstLower::LowerSymbolOperand(), llvm::LanaiMCInstLower::LowerSymbolOperand(), llvm::MSP430MCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandCOFF(), llvm::AArch64MCInstLower::lowerSymbolOperandDarwin(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), MakeStartMinusEndExpr(), makeStartPlusIntExpr(), llvm::FaultMaps::recordFaultingOp(), ScaleVectorOffset(), llvm::MCContext::setSymbolValue(), llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign(), llvm::symbolize::LLVMSymbolizer::symbolizeCode(), llvm::AMDGPUSymbolizer::tryAddingSymbolicOperand(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::writeArchive().
createEmptyInterval()
LiveInterval & llvm::LiveRangeEdit::createEmptyInterval () inline
create - Create a new register with the same class and original slot as parent.
Definition at line 184 of file LiveRangeEdit.h.
References getReg().
Referenced by llvm::SplitEditor::openIntv().
createFrom()
unsigned LiveRangeEdit::createFrom (unsigned OldReg)
createFrom - Create a new virtual register based on OldReg.
Definition at line 54 of file LiveRangeEdit.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getOriginal(), llvm::MachineRegisterInfo::getRegClass(), llvm::LiveInterval::isSpillable(), llvm::LiveInterval::markNotSpillable(), and llvm::VirtRegMap::setIsSplitFromReg().
Referenced by create().
didRematerialize()
bool llvm::LiveRangeEdit::didRematerialize (const VNInfo * ParentVNI) const inline
didRematerialize - Return true if ParentVNI was rematerialized anywhere.
Definition at line 231 of file LiveRangeEdit.h.
References llvm::SmallPtrSetImpl< PtrType >::count().
eliminateDeadDefs()
void LiveRangeEdit::eliminateDeadDefs (SmallVectorImpl< MachineInstr * > & Dead, ArrayRef< unsigned > RegsBeingSpilled = None, AliasAnalysis * AA = nullptr)
eliminateDeadDefs - Try to delete machine instructions that are now dead (allDefsAreDead returns true).
This may cause live intervals to be trimmed and further dead efs to be eliminated. RegsBeingSpilled lists registers currently being spilled by the register allocator. These registers should not be split into new intervals as currently those new intervals are not guaranteed to spill.
Definition at line 392 of file LiveRangeEdit.cpp.
References llvm::SetVector< T, Vector, Set >::back(), llvm::SetVector< T, Vector, Set >::empty(), llvm::SmallVectorBase::empty(), llvm::VirtRegMap::getOriginal(), llvm::LiveRangeEdit::Delegate::LRE_DidCloneVirtReg(), llvm::LiveRangeEdit::Delegate::LRE_WillShrinkVirtReg(), llvm::SetVector< T, Vector, Set >::pop_back(), llvm::LiveInterval::reg, llvm::LiveRange::RenumberValues(), llvm::VirtRegMap::setIsSplitFromReg(), llvm::LiveIntervals::shrinkToUses(), llvm::ArrayRef< T >::size(), and llvm::LiveIntervals::splitSeparateComponents().
empty()
bool llvm::LiveRangeEdit::empty () const inline
Definition at line 162 of file LiveRangeEdit.h.
References size().
Referenced by llvm::SplitEditor::openIntv().
end()
iterator llvm::LiveRangeEdit::end () const inline
Definition at line 160 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
eraseVirtReg()
void LiveRangeEdit::eraseVirtReg (unsigned Reg)
eraseVirtReg - Notify the delegate that Reg is no longer in use, and try to erase it from LIS.
Definition at line 180 of file LiveRangeEdit.cpp.
References llvm::LiveRangeEdit::Delegate::LRE_CanEraseVirtReg(), and llvm::LiveIntervals::removeInterval().
get()
unsigned llvm::LiveRangeEdit::get (unsigned idx) const inline
Definition at line 163 of file LiveRangeEdit.h.
Referenced by calculateRegClassAndHint().
getParent()
LiveInterval & llvm::LiveRangeEdit::getParent () const inline
Definition at line 150 of file LiveRangeEdit.h.
References assert().
Referenced by llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), getReg(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), and llvm::SplitEditor::overlapIntv().
getReg()
unsigned llvm::LiveRangeEdit::getReg () const inline
Definition at line 155 of file LiveRangeEdit.h.
References getParent(), and llvm::LiveInterval::reg.
Referenced by create(), createEmptyInterval(), and llvm::SplitEditor::leaveIntvAfter().
markRematerialized()
void llvm::LiveRangeEdit::markRematerialized (const VNInfo * ParentVNI) inline
markRematerialized - explicitly mark a value as rematerialized after doing it manually.
Definition at line 226 of file LiveRangeEdit.h.
References llvm::SmallPtrSetImpl< PtrType >::insert().
pop_back()
void llvm::LiveRangeEdit::pop_back () inline
pop_back - It allows LiveRangeEdit users to drop new registers.
The context is when an original def instruction of a register is dead after rematerialization, we still want to keep it for following rematerializations. We save the def instruction in DeadRemats, and replace the original dst register with a new dummy register so the live range of original dst register can be shrinked normally. We don't want to allocate phys register for the dummy register, so we want to drop it from the NewRegs set.
Definition at line 173 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateBase< T, bool >::pop_back().
regs()
ArrayRef< unsigned > llvm::LiveRangeEdit::regs () const inline
Definition at line 175 of file LiveRangeEdit.h.
References llvm::makeArrayRef().
rematerializeAt()
SlotIndex LiveRangeEdit::rematerializeAt (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, const Remat & RM, const TargetRegisterInfo & tri, bool Late = false)
rematerializeAt - Rematerialize RM.ParentVNI into DestReg by inserting an instruction into MBB before MI.
The new instruction is mapped, but liveness is not updated. Return the SlotIndex of the new instruction.
Definition at line 164 of file LiveRangeEdit.cpp.
References assert(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), llvm::SlotIndexes::insertMachineInstrInMaps(), MI, and llvm::TargetInstrInfo::reMaterialize().
size()
unsigned llvm::LiveRangeEdit::size () const inline
Definition at line 161 of file LiveRangeEdit.h.
References llvm::SmallVectorBase::size().
Referenced by calculateRegClassAndHint(), empty(), and llvm::SplitEditor::openIntv().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveRangeEdit.h
lib/CodeGen/LiveRangeEdit.cpp