LLVM: llvm::MCCodePadder Class Reference
llvm::MCCodePadder Class Reference
Target-independent base class incharge of all code padding decisions for a target.
#include "llvm/MC/MCCodePadder.h"
Public Member Functions
MCCodePadder ()
virtual ~MCCodePadder ()
void handleBasicBlockStart (MCObjectStreamer *OS, const MCCodePaddingContext &Context)
Handles all target related code padding when starting to write a new basic block to an object file.
void handleBasicBlockEnd (const MCCodePaddingContext &Context)
Handles all target related code padding when done writing a block to an object file.
void handleInstructionBegin (const MCInst &Inst)
Handles all target related code padding before writing a new instruction to an object file.
void handleInstructionEnd (const MCInst &Inst)
Handles all target related code padding after writing an instruction to an object file.
bool relaxFragment (MCPaddingFragment *Fragment, MCAsmLayout &Layout)
Relaxes a fragment (changes the size of the padding) according to target requirements.
Protected Member Functions
bool addPolicy (MCCodePaddingPolicy *Policy)
virtual bool basicBlockRequiresInsertionPoint (const MCCodePaddingContext &Context)
virtual bool instructionRequiresInsertionPoint (const MCInst &Inst)
virtual bool usePoliciesForBasicBlock (const MCCodePaddingContext &Context)
Protected Attributes
MCObjectStreamer * OS
The current streamer, used to stream code padding.
Detailed Description
Target-independent base class incharge of all code padding decisions for a target.
During encoding it determines if and where MCPaddingFragments will be located, as later on, when layout information is available, it determines their sizes.
Definition at line 38 of file MCCodePadder.h.
Constructor & Destructor Documentation
MCCodePadder()
llvm::MCCodePadder::MCCodePadder () inline
Definition at line 84 of file MCCodePadder.h.
~MCCodePadder()
MCCodePadder::~MCCodePadder () virtual
Definition at line 22 of file MCCodePadder.cpp.
Member Function Documentation
addPolicy()
bool MCCodePadder::addPolicy (MCCodePaddingPolicy * Policy) protected
Definition at line 27 of file MCCodePadder.cpp.
References assert().
basicBlockRequiresInsertionPoint()
virtual bool llvm::MCCodePadder::basicBlockRequiresInsertionPoint (const MCCodePaddingContext & Context) inline protected virtual
Definition at line 71 of file MCCodePadder.h.
Referenced by handleBasicBlockStart().
handleBasicBlockEnd()
void MCCodePadder::handleBasicBlockEnd (const MCCodePaddingContext & Context)
Handles all target related code padding when done writing a block to an object file.
Parameters
Context the context of the padding, Embeds the basic block's parameters.
Definition at line 68 of file MCCodePadder.cpp.
References assert(), and OS.
handleBasicBlockStart()
void MCCodePadder::handleBasicBlockStart (MCObjectStreamer * OS, const MCCodePaddingContext & Context)
Handles all target related code padding when starting to write a new basic block to an object file.
Parameters
OS The streamer used for writing the padding data and function.
Context the context of the padding, Embeds the basic block's parameters.
Definition at line 32 of file MCCodePadder.cpp.
References assert(), basicBlockRequiresInsertionPoint(), Context, llvm::MCFragment::FT_Align, llvm::MCObjectStreamer::getCurrentFragment(), llvm::MCFragment::getKind(), llvm::MCObjectStreamer::getOrCreatePaddingFragment(), llvm::MCPaddingFragment::getPaddingPoliciesMask(), OS, llvm::MCPaddingFragment::PFK_None, llvm::MCPaddingFragment::setAsInsertionPoint(), llvm::MCPaddingFragment::setPaddingPoliciesMask(), and usePoliciesForBasicBlock().
handleInstructionBegin()
void MCCodePadder::handleInstructionBegin (const MCInst & Inst)
Handles all target related code padding before writing a new instruction to an object file.
Parameters
Inst the instruction.
Definition at line 73 of file MCCodePadder.cpp.
References assert(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Padding, llvm::MCObjectStreamer::getCurrentFragment(), llvm::MCFragment::getKind(), llvm::MCObjectStreamer::getOrCreatePaddingFragment(), llvm::MCPaddingFragment::getPaddingPoliciesMask(), instructionRequiresInsertionPoint(), OS, llvm::MCPaddingFragment::PFK_None, llvm::MCPaddingFragment::setAsInsertionPoint(), and llvm::MCPaddingFragment::setPaddingPoliciesMask().
handleInstructionEnd()
void MCCodePadder::handleInstructionEnd (const MCInst & Inst)
Handles all target related code padding after writing an instruction to an object file.
Parameters
Inst the instruction.
Definition at line 117 of file MCCodePadder.cpp.
References llvm::MCObjectStreamer::getCurrentFragment(), llvm_unreachable, OS, llvm::MCPaddingFragment::setInstAndInstFragment(), llvm::MCPaddingFragment::setInstAndInstSize(), and llvm::MCInst::size().
instructionRequiresInsertionPoint()
virtual bool llvm::MCCodePadder::instructionRequiresInsertionPoint (const MCInst & Inst) inline protected virtual
Definition at line 75 of file MCCodePadder.h.
Referenced by handleInstructionBegin().
relaxFragment()
bool MCCodePadder::relaxFragment (MCPaddingFragment * Fragment, MCAsmLayout & Layout)
Relaxes a fragment (changes the size of the padding) according to target requirements.
The new size computation is done w.r.t a layout.
Parameters
Fragment The fragment to relax.
Layout Code layout information.
Returns
true iff any relaxation occurred.
Definition at line 207 of file MCCodePadder.cpp.
References assert(), llvm::MCSection::getAlignment(), llvm::MCFragment::getParent(), llvm::MCPaddingFragment::getSize(), llvm::MCAsmLayout::invalidateFragmentsFrom(), llvm::MCPaddingFragment::isInsertionPoint(), llvm::isPowerOf2_64(), llvm::MCPaddingFragment::setSize(), and Size.
usePoliciesForBasicBlock()
virtual bool llvm::MCCodePadder::usePoliciesForBasicBlock (const MCCodePaddingContext & Context) inline protected virtual
Definition at line 79 of file MCCodePadder.h.
References Context.
Referenced by handleBasicBlockStart().
Member Data Documentation
OS
MCObjectStreamer* llvm::MCCodePadder::OS protected
The current streamer, used to stream code padding.
Definition at line 66 of file MCCodePadder.h.
Referenced by handleBasicBlockEnd(), handleBasicBlockStart(), handleInstructionBegin(), and handleInstructionEnd().
The documentation for this class was generated from the following files:
include/llvm/MC/MCCodePadder.h
lib/MC/MCCodePadder.cpp