LLVM: llvm::RegScavenger Class Reference
llvm::RegScavenger Class Reference
#include "llvm/CodeGen/RegisterScavenging.h"
Public Member Functions
RegScavenger ()=default
void enterBasicBlock (MachineBasicBlock &MBB)
Start tracking liveness from the begin of basic block MBB.
void enterBasicBlockEnd (MachineBasicBlock &MBB)
Start tracking liveness from the end of basic block MBB.
void forward ()
Move the internal MBB iterator and update register states.
void forward (MachineBasicBlock::iterator I)
Move the internal MBB iterator and update register states until it has processed the specific iterator.
void unprocess ()
Invert the behavior of forward() on the current instruction (undo the changes to the available registers made by forward()).
void unprocess (MachineBasicBlock::iterator I)
Unprocess instructions until you reach the provided iterator.
void backward ()
Update internal register state and move MBB iterator backwards.
void backward (MachineBasicBlock::iterator I)
Call backward() as long as the internal iterator does not point to I.
void skipTo (MachineBasicBlock::iterator I)
Move the internal MBB iterator but do not update register states.
MachineBasicBlock::iterator getCurrentPosition () const
bool isRegUsed (unsigned Reg, bool includeReserved=true) const
Return if a specific register is currently used.
BitVector getRegsAvailable (const TargetRegisterClass *RC)
Return all available registers in the register class in Mask.
unsigned FindUnusedReg (const TargetRegisterClass *RC) const
Find an unused register of the specified register class.
void addScavengingFrameIndex (int FI)
Add a scavenging frame index.
bool isScavengingFrameIndex (int FI) const
Query whether a frame index is a scavenging frame index.
void getScavengingFrameIndices (SmallVectorImpl< int > &A) const
Get an array of scavenging frame indices.
unsigned scavengeRegister (const TargetRegisterClass *RC, MachineBasicBlock::iterator I, int SPAdj, bool AllowSpill=true)
Make a register of the specific register class available and do the appropriate bookkeeping.
unsigned scavengeRegister (const TargetRegisterClass *RegClass, int SPAdj, bool AllowSpill=true)
unsigned scavengeRegisterBackwards (const TargetRegisterClass &RC, MachineBasicBlock::iterator To, bool RestoreAfter, int SPAdj, bool AllowSpill=true)
Make a register of the specific register class available from the current position backwards to the place before To.
void setRegUsed (unsigned Reg, LaneBitmask LaneMask=LaneBitmask::getAll())
Tell the scavenger a register is used.
Detailed Description
Definition at line 34 of file RegisterScavenging.h.
Constructor & Destructor Documentation
RegScavenger()
llvm::RegScavenger::RegScavenger () default
Member Function Documentation
addScavengingFrameIndex()
void llvm::RegScavenger::addScavengingFrameIndex (int FI) inline
Add a scavenging frame index.
Definition at line 132 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized().
backward() [1/2]
void RegScavenger::backward ()
Update internal register state and move MBB iterator backwards.
Contrary to unprocess() this method gives precise results even in the absence of kill flags.
Definition at line 260 of file RegisterScavenging.cpp.
References assert(), llvm::MachineBasicBlock::begin(), I, MI, and llvm::LiveRegUnits::stepBackward().
Referenced by backward(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and scavengeFrameVirtualRegsInBlock().
backward() [2/2]
void llvm::RegScavenger::backward (MachineBasicBlock::iterator I) inline
Call backward() as long as the internal iterator does not point to I.
Definition at line 107 of file RegisterScavenging.h.
References backward(), and I.
enterBasicBlock()
void RegScavenger::enterBasicBlock (MachineBasicBlock & MBB)
Start tracking liveness from the begin of basic block MBB.
Definition at line 83 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addLiveIns().
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SIInstrInfo::copyPhysReg(), and llvm::Mips16InstrInfo::loadImmediate().
enterBasicBlockEnd()
void RegScavenger::enterBasicBlockEnd (MachineBasicBlock & MBB)
Start tracking liveness from the end of basic block MBB.
Use backward() to move towards the beginning of the block. This is preferred to enterBasicBlock() and forward() because it does not depend on the presence of kill flags.
Definition at line 88 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addLiveOuts(), llvm::MachineBasicBlock::begin(), and llvm::MachineBasicBlock::end().
Referenced by llvm::SIInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and scavengeFrameVirtualRegsInBlock().
FindUnusedReg()
unsigned RegScavenger::FindUnusedReg (const TargetRegisterClass * RC) const
Find an unused register of the specified register class.
Return 0 if none is found.
Definition at line 287 of file RegisterScavenging.cpp.
References llvm::dbgs(), isRegUsed(), LLVM_DEBUG, and llvm::printReg().
Referenced by llvm::SIInstrInfo::copyPhysReg(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and ReplaceFrameIndex().
forward() [1/2]
void RegScavenger::forward ()
Move the internal MBB iterator and update register states.
Definition at line 175 of file RegisterScavenging.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), I, llvm::TargetRegisterInfo::isPhysicalRegister(), isRegUsed(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm_unreachable, MI, and llvm::MachineFunction::verify().
Referenced by llvm::SIInstrInfo::copyPhysReg(), forward(), and llvm::Mips16InstrInfo::loadImmediate().
forward() [2/2]
void llvm::RegScavenger::forward (MachineBasicBlock::iterator I) inline
Move the internal MBB iterator and update register states until it has processed the specific iterator.
Definition at line 87 of file RegisterScavenging.h.
References llvm::MachineBasicBlock::begin(), forward(), and I.
getCurrentPosition()
MachineBasicBlock::iterator llvm::RegScavenger::getCurrentPosition () const inline
Definition at line 119 of file RegisterScavenging.h.
getRegsAvailable()
BitVector RegScavenger::getRegsAvailable (const TargetRegisterClass * RC)
Return all available registers in the register class in Mask.
Definition at line 298 of file RegisterScavenging.cpp.
References llvm::MCRegisterInfo::getNumRegs(), and isRegUsed().
Referenced by llvm::Mips16InstrInfo::loadImmediate(), and scavengeRegister().
getScavengingFrameIndices()
void llvm::RegScavenger::getScavengingFrameIndices (SmallVectorImpl< int > & A) const inline
Get an array of scavenging frame indices.
Definition at line 147 of file RegisterScavenging.h.
References A, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and I.
isRegUsed()
bool RegScavenger::isRegUsed (unsigned Reg, bool includeReserved = true) const
Return if a specific register is currently used.
Definition at line 281 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::available().
Referenced by FindUnusedReg(), forward(), getRegsAvailable(), llvm::SIRegisterInfo::restoreSGPR(), scavengeRegister(), and llvm::SIRegisterInfo::spillSGPR().
isScavengingFrameIndex()
bool llvm::RegScavenger::isScavengingFrameIndex (int FI) const inline
Query whether a frame index is a scavenging frame index.
Definition at line 137 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and I.
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), and llvm::ThumbRegisterInfo::eliminateFrameIndex().
scavengeRegister() [1/2]
unsigned RegScavenger::scavengeRegister (const TargetRegisterClass * RC, MachineBasicBlock::iterator I, int SPAdj, bool AllowSpill = true)
Make a register of the specific register class available and do the appropriate bookkeeping.
SPAdj is the stack adjustment due to call frame, it's passed along to eliminateFrameIndex(). Returns the scavenged register. This is deprecated as it depends on the quality of the kill flags being present; Use scavengeRegisterBackwards() instead!
If AllowSpill is false, fail if a spill is required to make the register available, and return NoRegister.
Definition at line 534 of file RegisterScavenging.cpp.
References llvm::BitVector::any(), llvm::dbgs(), llvm::TargetRegisterInfo::getAllocatableSet(), getRegsAvailable(), I, isRegUsed(), llvm::MCRegAliasIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MI, llvm::printReg(), llvm::BitVector::reset(), and UseMI.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SIInstrInfo::copyPhysReg(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), InsertFPConstInst(), InsertSPConstInst(), ReplaceFrameIndex(), and scavengeRegister().
scavengeRegister() [2/2]
unsigned llvm::RegScavenger::scavengeRegister (const TargetRegisterClass * RegClass, int SPAdj, bool AllowSpill = true) inline
Definition at line 166 of file RegisterScavenging.h.
References scavengeRegister().
scavengeRegisterBackwards()
unsigned RegScavenger::scavengeRegisterBackwards (const TargetRegisterClass & RC, MachineBasicBlock::iterator To, bool RestoreAfter, int SPAdj, bool AllowSpill = true)
Make a register of the specific register class available from the current position backwards to the place before To.
If RestoreAfter is true this includes the instruction following the current position. SPAdj is the stack adjustment due to call frame, it's passed along to eliminateFrameIndex(). Returns the scavenged register.
If AllowSpill is false, fail if a spill is required to make the register available, and return NoRegister.
Definition at line 579 of file RegisterScavenging.cpp.
References assert(), llvm::dbgs(), llvm::MachineBasicBlock::end(), findSurvivorBackwards(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterClass::getRawAllocationOrder(), LLVM_DEBUG, P, llvm::printReg(), llvm::LiveRegUnits::removeReg(), and UseMI.
Referenced by llvm::SIInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), and scavengeVReg().
setRegUsed()
void RegScavenger::setRegUsed (unsigned Reg, LaneBitmask LaneMask = LaneBitmask::getAll())
Tell the scavenger a register is used.
Definition at line 52 of file RegisterScavenging.cpp.
References llvm::LiveRegUnits::addRegMasked().
Referenced by llvm::SIInstrInfo::copyPhysReg(), InsertFPConstInst(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), InsertSPConstInst(), ReplaceFrameIndex(), and scavengeFrameVirtualRegsInBlock().
skipTo()
void llvm::RegScavenger::skipTo (MachineBasicBlock::iterator I) inline
Move the internal MBB iterator but do not update register states.
Definition at line 113 of file RegisterScavenging.h.
References I.
unprocess() [1/2]
void RegScavenger::unprocess ()
Invert the behavior of forward() on the current instruction (undo the changes to the available registers made by forward()).
Definition at line 156 of file RegisterScavenging.cpp.
References assert(), llvm::MachineBasicBlock::begin(), and MI.
Referenced by unprocess().
unprocess() [2/2]
void llvm::RegScavenger::unprocess (MachineBasicBlock::iterator I) inline
Unprocess instructions until you reach the provided iterator.
Definition at line 97 of file RegisterScavenging.h.
References I, and unprocess().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterScavenging.h
lib/CodeGen/RegisterScavenging.cpp