LLVM: llvm::MCSubtargetInfo Class Reference
llvm::MCSubtargetInfo Class Reference
Generic base class for all target subtargets.
#include "llvm/MC/MCSubtargetInfo.h"
Public Member Functions
MCSubtargetInfo (const MCSubtargetInfo &)=default
MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetSubTypeKV > PD, const MCWriteProcResEntry *WPR, const MCWriteLatencyEntry *WL, const MCReadAdvanceEntry *RA, const InstrStage *IS, const unsigned *OC, const unsigned *FP)
MCSubtargetInfo ()=delete
MCSubtargetInfo & operator= (const MCSubtargetInfo &)=delete
MCSubtargetInfo & operator= (MCSubtargetInfo &&)=delete
virtual ~MCSubtargetInfo ()=default
const Triple & getTargetTriple () const
StringRef getCPU () const
const FeatureBitset & getFeatureBits () const
void setFeatureBits (const FeatureBitset &FeatureBits_)
bool hasFeature (unsigned Feature) const
void setDefaultFeatures (StringRef CPU, StringRef FS)
Set the features to the default for the given CPU with an appended feature string.
FeatureBitset ToggleFeature (uint64_t FB)
Toggle a feature and return the re-computed feature bits.
FeatureBitset ToggleFeature (const FeatureBitset &FB)
Toggle a feature and return the re-computed feature bits.
FeatureBitset ToggleFeature (StringRef FS)
Toggle a set of features and return the re-computed feature bits.
FeatureBitset ApplyFeatureFlag (StringRef FS)
Apply a feature flag and return the re-computed feature bits, including all feature bits implied by the flag.
FeatureBitset SetFeatureBitsTransitively (const FeatureBitset &FB)
Set/clear additional feature bits, including all other bits they imply.
FeatureBitset ClearFeatureBitsTransitively (const FeatureBitset &FB)
bool checkFeatures (StringRef FS) const
Check whether the subtarget features are enabled/disabled as per the provided string, ignoring all other features.
const MCSchedModel & getSchedModelForCPU (StringRef CPU) const
Get the machine model of a CPU.
const MCSchedModel & getSchedModel () const
Get the machine model for this subtarget's CPU.
const MCWriteProcResEntry * getWriteProcResBegin (const MCSchedClassDesc *SC) const
Return an iterator at the first process resource consumed by the given scheduling class.
const MCWriteProcResEntry * getWriteProcResEnd (const MCSchedClassDesc *SC) const
const MCWriteLatencyEntry * getWriteLatencyEntry (const MCSchedClassDesc *SC, unsigned DefIdx) const
int getReadAdvanceCycles (const MCSchedClassDesc *SC, unsigned UseIdx, unsigned WriteResID) const
ArrayRef< MCReadAdvanceEntry > getReadAdvanceEntries (const MCSchedClassDesc &SC) const
Return the set of ReadAdvance entries declared by the scheduling class descriptor in input.
InstrItineraryData getInstrItineraryForCPU (StringRef CPU) const
Get scheduling itinerary of a CPU.
void initInstrItins (InstrItineraryData &InstrItins) const
Initialize an InstrItineraryData instance.
virtual unsigned resolveVariantSchedClass (unsigned SchedClass, const MCInst *MI, unsigned CPUID) const
Resolve a variant scheduling class for the given MCInst and CPU.
bool isCPUStringValid (StringRef CPU) const
Check whether the CPU string is valid.
Protected Member Functions
void InitMCProcessorInfo (StringRef CPU, StringRef FS)
Initialize the scheduling model and feature bits.
Detailed Description
Generic base class for all target subtargets.
Definition at line 74 of file MCSubtargetInfo.h.
Constructor & Destructor Documentation
MCSubtargetInfo() [1/3]
llvm::MCSubtargetInfo::MCSubtargetInfo (const MCSubtargetInfo &) default
MCSubtargetInfo() [2/3]
MCSubtargetInfo::MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetSubTypeKV > PD, const MCWriteProcResEntry * WPR, const MCWriteLatencyEntry * WL, const MCReadAdvanceEntry * RA, const InstrStage * IS, const unsigned * OC, const unsigned * FP)
Definition at line 209 of file MCSubtargetInfo.cpp.
References InitMCProcessorInfo().
MCSubtargetInfo() [3/3]
llvm::MCSubtargetInfo::MCSubtargetInfo () delete
~MCSubtargetInfo()
virtual llvm::MCSubtargetInfo::~MCSubtargetInfo () virtual default
Member Function Documentation
ApplyFeatureFlag()
FeatureBitset MCSubtargetInfo::ApplyFeatureFlag (StringRef FS)
Apply a feature flag and return the re-computed feature bits, including all feature bits implied by the flag.
Definition at line 273 of file MCSubtargetInfo.cpp.
References ApplyFeatureFlag().
Referenced by ApplyFeatureFlag(), and checkFeatures().
checkFeatures()
bool MCSubtargetInfo::checkFeatures (StringRef FS) const
Check whether the subtarget features are enabled/disabled as per the provided string, ignoring all other features.
Definition at line 278 of file MCSubtargetInfo.cpp.
References ApplyFeatureFlag(), and F.
ClearFeatureBitsTransitively()
FeatureBitset MCSubtargetInfo::ClearFeatureBitsTransitively (const FeatureBitset & FB)
Definition at line 237 of file MCSubtargetInfo.cpp.
References ClearImpliedBits(), E, and I.
getCPU()
StringRef llvm::MCSubtargetInfo::getCPU () const inline
Definition at line 105 of file MCSubtargetInfo.h.
Referenced by llvm::AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer(), llvm::createHexagonAsmBackend(), llvm::createMipsAsmBackend(), llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::ARMTargetStreamer::emitTargetAttributes(), llvm::AMDGPU::IsaInfo::getAddressableNumSGPRs(), getArchForCPU(), llvm::AMDGPU::getDefaultAmdhsaKernelDescriptor(), llvm::Hexagon_MC::GetELFFlags(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), llvm::AMDGPU::IsaInfo::getSGPRAllocGranule(), llvm::AMDGPU::IsaInfo::getTotalNumSGPRs(), llvm::HexagonShuffler::HexagonShuffler(), llvm::AMDGPU::initDefaultAMDKernelCodeT(), llvm::HexagonMCInstrInfo::isOrderedDuplexPair(), llvm::AMDGPUInstPrinter::printWaitFlag(), and llvm::AMDGPU::IsaInfo::streamIsaVersion().
getFeatureBits()
const FeatureBitset & llvm::MCSubtargetInfo::getFeatureBits () const inline
Definition at line 107 of file MCSubtargetInfo.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), llvm::AMDGPUDisassembler::AMDGPUDisassembler(), llvm::AVRELFStreamer::AVRELFStreamer(), llvm::HexagonMCInstrInfo::canonicalizePacket(), checkFeature(), clearFeature(), llvm::AMDGPUDisassembler::convertMIMGInst(), llvm::AMDGPUDisassembler::convertSDWAInst(), llvm::AMDGPUDisassembler::decodeBoolReg(), DecodeHINTInstruction(), llvm::AMDGPUDisassembler::decodeSDWASrc(), llvm::AMDGPUDisassembler::decodeSDWAVopcDst(), DecodeSETPANInstruction(), DecodeSystemPStateInstruction(), llvm::MipsTargetStreamer::emitNop(), llvm::PPCMCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::MipsTargetELFStreamer::finish(), llvm::AMDGPU::IsaInfo::getAddressableNumSGPRs(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), llvm::AMDGPU::getDefaultAmdhsaKernelDescriptor(), llvm::MCInstrDesc::getDeprecatedInfo(), llvm::AMDGPUDisassembler::getInstruction(), getITDeprecationInfo(), getLit16Encoding(), getLit32Encoding(), getLit64Encoding(), llvm::AMDGPU::IsaInfo::getLocalMemorySize(), llvm::AMDGPUMCAsmInfo::getMaxInstLength(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), getMCRDeprecationInfo(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), llvm::ARMAsmBackend::getRelaxedOpcode(), llvm::AMDGPU::IsaInfo::getVGPRAllocGranule(), llvm::AMDGPU::IsaInfo::getWavefrontSize(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), llvm::AMDGPU::hasMIMG_R128(), llvm::ARMAsmBackend::hasNOP(), llvm::AMDGPU::hasPackedD16(), llvm::AMDGPU::hasSRAMECC(), llvm::AMDGPU::hasXNACK(), llvm::AMDGPU::initDefaultAMDKernelCodeT(), llvm::AMDGPU::isCI(), llvm::AMDGPU::isGCN3Encoding(), llvm::AMDGPUDisassembler::isGFX10(), llvm::AMDGPU::isGFX10(), llvm::AMDGPUDisassembler::isGFX9(), llvm::AMDGPU::isGFX9(), llvm::AMDGPU::isSI(), isThumb(), llvm::SparcInstPrinter::isV9(), llvm::AMDGPUDisassembler::isVI(), llvm::AMDGPU::isVI(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::RISCVInstPrinter::printCSRSystemRegister(), llvm::AArch64InstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::X86ATTInstPrinter::printInst(), llvm::X86IntelInstPrinter::printInst(), llvm::ARMInstPrinter::printMemBOption(), llvm::AArch64InstPrinter::printMRSSystemRegister(), llvm::ARMInstPrinter::printMSRMaskOperand(), llvm::AArch64InstPrinter::printMSRSystemRegister(), llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSystemPStateField(), llvm::RISCVAsmBackend::RISCVAsmBackend(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), llvm::RISCVAsmBackend::shouldForceRelocation(), llvm::RISCVAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign(), llvm::RISCVAsmBackend::willForceRelocations(), and llvm::RISCVAsmBackend::writeNopData().
getInstrItineraryForCPU()
InstrItineraryData MCSubtargetInfo::getInstrItineraryForCPU (StringRef CPU) const
Get scheduling itinerary of a CPU.
Definition at line 309 of file MCSubtargetInfo.cpp.
References getSchedModelForCPU().
Referenced by getItineraryLatency().
getReadAdvanceCycles()
int llvm::MCSubtargetInfo::getReadAdvanceCycles (const MCSchedClassDesc * SC, unsigned UseIdx, unsigned WriteResID) const inline
Definition at line 177 of file MCSubtargetInfo.h.
References E, and I.
Referenced by llvm::mca::RegisterFile::addRegisterRead(), and llvm::TargetSchedModel::computeOperandLatency().
getReadAdvanceEntries()
ArrayRef< MCReadAdvanceEntry > llvm::MCSubtargetInfo::getReadAdvanceEntries (const MCSchedClassDesc & SC) const inline
Return the set of ReadAdvance entries declared by the scheduling class descriptor in input.
Definition at line 199 of file MCSubtargetInfo.h.
getSchedModel()
const MCSchedModel & llvm::MCSubtargetInfo::getSchedModel () const inline
Get the machine model for this subtarget's CPU.
Definition at line 156 of file MCSubtargetInfo.h.
Referenced by llvm::mca::RegisterFile::addRegisterRead(), llvm::mca::Context::createDefaultPipeline(), llvm::mca::InstrBuilder::createInstruction(), llvm::mca::DispatchStage::DispatchStage(), llvm::TargetSubtargetInfo::enablePostRAScheduler(), llvm::BasicTTIImplBase< T >::getInstructionLatency(), getLatency(), llvm::HexagonMCInstrInfo::getOtherReservedSlots(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::HexagonMCInstrInfo::getUnits(), llvm::TargetSchedModel::init(), llvm::mca::initializeUsedResources(), initInstrItins(), and llvm::mca::InstrBuilder::InstrBuilder().
getSchedModelForCPU()
const MCSchedModel & MCSubtargetInfo::getSchedModelForCPU (StringRef CPU) const
Get the machine model of a CPU.
Definition at line 290 of file MCSubtargetInfo.cpp.
References assert(), llvm::errs(), Find(), llvm::MCSchedModel::GetDefaultSchedModel(), and llvm::SubtargetSubTypeKV::SchedModel.
Referenced by getInstrItineraryForCPU(), and InitMCProcessorInfo().
getTargetTriple()
const Triple & llvm::MCSubtargetInfo::getTargetTriple () const inline
Definition at line 104 of file MCSubtargetInfo.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), llvm::createAArch64ObjectTargetStreamer(), llvm::createAMDGPUAsmBackend(), createARMAsmBackend(), llvm::createARMObjectTargetStreamer(), createAsmBackend(), llvm::createAVRAsmBackend(), llvm::createHexagonAsmBackend(), llvm::createLanaiAsmBackend(), llvm::createMipsAsmBackend(), llvm::createMSP430ObjectTargetStreamer(), createObjectTargetStreamer(), llvm::createPPCAsmBackend(), llvm::createRISCVAsmBackend(), createRISCVObjectTargetStreamer(), llvm::createSparcAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::createX86ObjectTargetStreamer(), llvm::AMDGPUAsmPrinter::doFinalization(), llvm::AsmPrinter::emitXRayTable(), llvm::ARMAsmBackend::getFixupKind(), llvm::AMDGPUMCAsmInfo::getMaxInstLength(), llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU(), llvm::AMDGPU::getMCReg(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::AMDGPU::IsaInfo::hasCodeObjectV3(), lowerMSASplatZExt(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::RISCVAsmBackend::RISCVAsmBackend(), llvm::AMDGPU::IsaInfo::streamIsaVersion(), and truncateVecElts().
getWriteLatencyEntry()
const MCWriteLatencyEntry * llvm::MCSubtargetInfo::getWriteLatencyEntry (const MCSchedClassDesc * SC, unsigned DefIdx) const inline
Definition at line 169 of file MCSubtargetInfo.h.
References assert().
Referenced by llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeOperandLatency(), and getLatency().
getWriteProcResBegin()
const MCWriteProcResEntry * llvm::MCSubtargetInfo::getWriteProcResBegin (const MCSchedClassDesc * SC) const inline
Return an iterator at the first process resource consumed by the given scheduling class.
Definition at line 160 of file MCSubtargetInfo.h.
Referenced by llvm::ResourceManager::canReserveResources(), llvm::TargetSchedModel::computeOutputLatency(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::TargetSchedModel::getWriteProcResBegin(), getWriteProcResEnd(), llvm::mca::initializeUsedResources(), and llvm::ResourceManager::reserveResources().
getWriteProcResEnd()
const MCWriteProcResEntry * llvm::MCSubtargetInfo::getWriteProcResEnd (const MCSchedClassDesc * SC) const inline
Definition at line 164 of file MCSubtargetInfo.h.
References getWriteProcResBegin().
Referenced by llvm::ResourceManager::canReserveResources(), llvm::TargetSchedModel::computeOutputLatency(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::TargetSchedModel::getWriteProcResEnd(), and llvm::ResourceManager::reserveResources().
hasFeature()
bool llvm::MCSubtargetInfo::hasFeature (unsigned Feature) const inline
Definition at line 112 of file MCSubtargetInfo.h.
Referenced by llvm::ARMTargetStreamer::emitTargetAttributes(), getArchForCPU(), llvm::ARMElfTargetObjectFile::Initialize(), and isV8M().
initInstrItins()
void MCSubtargetInfo::initInstrItins (InstrItineraryData & InstrItins) const
Initialize an InstrItineraryData instance.
Definition at line 314 of file MCSubtargetInfo.cpp.
References getSchedModel().
Referenced by llvm::TargetSchedModel::init().
InitMCProcessorInfo()
void MCSubtargetInfo::InitMCProcessorInfo (StringRef CPU, StringRef FS) protected
Initialize the scheduling model and feature bits.
FIXME: Find a way to stick this in the constructor, since it should only be called during initialization.
Definition at line 197 of file MCSubtargetInfo.cpp.
References llvm::StringRef::empty(), llvm::MCSchedModel::GetDefaultSchedModel(), getFeatures(), and getSchedModelForCPU().
Referenced by MCSubtargetInfo().
isCPUStringValid()
bool llvm::MCSubtargetInfo::isCPUStringValid (StringRef CPU) const inline
Check whether the CPU string is valid.
Definition at line 220 of file MCSubtargetInfo.h.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
operator=() [1/2]
MCSubtargetInfo & llvm::MCSubtargetInfo::operator= (const MCSubtargetInfo &) delete
operator=() [2/2]
MCSubtargetInfo & llvm::MCSubtargetInfo::operator= (MCSubtargetInfo &&) delete
resolveVariantSchedClass()
virtual unsigned llvm::MCSubtargetInfo::resolveVariantSchedClass (unsigned SchedClass, const MCInst * MI, unsigned CPUID) const inline virtual
Resolve a variant scheduling class for the given MCInst and CPU.
Definition at line 214 of file MCSubtargetInfo.h.
Referenced by llvm::MCSchedModel::computeInstrLatency(), and llvm::MCSchedModel::getReciprocalThroughput().
setDefaultFeatures()
void MCSubtargetInfo::setDefaultFeatures (StringRef CPU, StringRef FS)
Set the features to the default for the given CPU with an appended feature string.
Definition at line 205 of file MCSubtargetInfo.cpp.
References getFeatures().
setFeatureBits()
void llvm::MCSubtargetInfo::setFeatureBits (const FeatureBitset & FeatureBits_) inline
Definition at line 108 of file MCSubtargetInfo.h.
SetFeatureBitsTransitively()
FeatureBitset MCSubtargetInfo::SetFeatureBitsTransitively (const FeatureBitset & FB)
Set/clear additional feature bits, including all other bits they imply.
Definition at line 231 of file MCSubtargetInfo.cpp.
References SetImpliedBits().
ToggleFeature() [1/3]
FeatureBitset MCSubtargetInfo::ToggleFeature (const FeatureBitset & FB)
Toggle a feature and return the re-computed feature bits.
This version does not change the implied bits.
Definition at line 226 of file MCSubtargetInfo.cpp.
ToggleFeature() [2/3]
FeatureBitset MCSubtargetInfo::ToggleFeature (StringRef FS)
Toggle a set of features and return the re-computed feature bits.
This version will also change all implied bits.
Definition at line 248 of file MCSubtargetInfo.cpp.
References ClearImpliedBits(), llvm::errs(), Find(), llvm::FeatureBitArray::getAsBitset(), llvm::SubtargetFeatureKV::Implies, SetImpliedBits(), llvm::SubtargetFeatures::StripFlag(), and llvm::SubtargetFeatureKV::Value.
ToggleFeature() [3/3]
FeatureBitset MCSubtargetInfo::ToggleFeature (uint64_t FB)
Toggle a feature and return the re-computed feature bits.
This version does not change the implied bits.
Definition at line 221 of file MCSubtargetInfo.cpp.
Referenced by clearFeature().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSubtargetInfo.h
lib/MC/MCSubtargetInfo.cpp