LLVM: llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
SetterImpl & setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB)
Set the JITTargetMachineBuilder for this instance.
Optional< JITTargetMachineBuilder > & getJITTargetMachineBuilder ()
Return a reference to the JITTargetMachineBuilder.
SetterImpl & setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer)
Set an ObjectLinkingLayer creation function.
SetterImpl & setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction)
Set a CompileFunctionCreator.
SetterImpl & setNumCompileThreads (unsigned NumCompileThreads)
Set the number of compile threads to use.
Expected< std::unique_ptr< JITType > > create ()
Create an instance of the JIT.
Protected Member Functions
SetterImpl & impl ()
Detailed Description
template<typename JITType, typename SetterImpl, typename State>
class llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
Definition at line 205 of file LLJIT.h.
Member Function Documentation
create()
template<typename JITType , typename SetterImpl , typename State > Expected< std::unique_ptr< JITType > > llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::create () inline
Create an instance of the JIT.
Definition at line 258 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl(), and llvm::Error::success().
getJITTargetMachineBuilder()
template<typename JITType , typename SetterImpl , typename State > Optional< JITTargetMachineBuilder > & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::getJITTargetMachineBuilder () inline
Return a reference to the JITTargetMachineBuilder.
Definition at line 218 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
impl()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl () inline protected
Definition at line 270 of file LLJIT.h.
Referenced by llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::create(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::getJITTargetMachineBuilder(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setCompileFunctionCreator(), llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setIndirectStubsManagerBuilder(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setJITTargetMachineBuilder(), llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCallthroughManager(), llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCompileFailureAddr(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setNumCompileThreads(), and llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setObjectLinkingLayerCreator().
setCompileFunctionCreator()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction) inline
Set a CompileFunctionCreator.
If this method is not called, a default creation function wil be used that will construct a basic IR compile function that is compatible with the selected number of threads (SimpleCompiler for '0' compile threads, ConcurrentIRCompiler otherwise).
Definition at line 238 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setJITTargetMachineBuilder()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB) inline
Set the JITTargetMachineBuilder for this instance.
If this method is not called, JITTargetMachineBuilder::detectHost will be used to construct a default target machine builder for the host platform.
Definition at line 211 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setNumCompileThreads()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setNumCompileThreads (unsigned NumCompileThreads) inline
Set the number of compile threads to use.
If set to zero, compilation will be performed on the execution thread when JITing in-process. If set to any other number N, a thread pool of N threads will be created for compilation.
If this method is not called, behavior will be as if it were called with a zero argument.
Definition at line 252 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setObjectLinkingLayerCreator()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer) inline
Set an ObjectLinkingLayer creation function.
If this method is not called, a default creation function will be used that will construct an RTDyldObjectLinkingLayer.
Definition at line 226 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/LLJIT.h