LLVM: llvm::jitlink::MachOAtomGraphBuilder Class Reference
llvm::jitlink::MachOAtomGraphBuilder Class Reference abstract
#include "ExecutionEngine/JITLink/MachOAtomGraphBuilder.h"
Classes
class MachOSection
Public Member Functions
virtual ~MachOAtomGraphBuilder ()
Expected< std::unique_ptr< AtomGraph > > buildGraph ()
Protected Types
using OffsetToAtomMap = std::map< JITTargetAddress, DefinedAtom * >
using CustomAtomizeFunction = std::function< Error(MachOSection &S)>
Protected Member Functions
MachOAtomGraphBuilder (const object::MachOObjectFile &Obj)
AtomGraph & getGraph () const
const object::MachOObjectFile & getObject () const
void addCustomAtomizer (StringRef SectionName, CustomAtomizeFunction Atomizer)
virtual Error addRelocations ()=0
bool areLayoutLocked (const Atom &A, const Atom &B)
Returns true if Atom A and Atom B are at a fixed offset from one another (i.e.
Detailed Description
Definition at line 25 of file MachOAtomGraphBuilder.h.
Member Typedef Documentation
CustomAtomizeFunction
using llvm::jitlink::MachOAtomGraphBuilder::CustomAtomizeFunction = std::function<Error(MachOSection &S)> protected
Definition at line 101 of file MachOAtomGraphBuilder.h.
OffsetToAtomMap
using llvm::jitlink::MachOAtomGraphBuilder::OffsetToAtomMap = std::map<JITTargetAddress, DefinedAtom *> protected
Definition at line 31 of file MachOAtomGraphBuilder.h.
Constructor & Destructor Documentation
~MachOAtomGraphBuilder()
llvm::jitlink::MachOAtomGraphBuilder::~MachOAtomGraphBuilder () virtual
Definition at line 20 of file MachOAtomGraphBuilder.cpp.
MachOAtomGraphBuilder()
llvm::jitlink::MachOAtomGraphBuilder::MachOAtomGraphBuilder (const object::MachOObjectFile & Obj) protected
Definition at line 35 of file MachOAtomGraphBuilder.cpp.
Member Function Documentation
addCustomAtomizer()
void llvm::jitlink::MachOAtomGraphBuilder::addCustomAtomizer (StringRef SectionName, CustomAtomizeFunction Atomizer) protected
Definition at line 40 of file MachOAtomGraphBuilder.cpp.
References assert(), and llvm::StringMap< ValueTy, AllocatorTy >::count().
addRelocations()
virtual Error llvm::jitlink::MachOAtomGraphBuilder::addRelocations () protected pure virtual
Referenced by buildGraph().
areLayoutLocked()
bool llvm::jitlink::MachOAtomGraphBuilder::areLayoutLocked (const Atom & A, const Atom & B) protected
Returns true if Atom A and Atom B are at a fixed offset from one another (i.e.
if they're part of the same alt-entry chain).
Definition at line 47 of file MachOAtomGraphBuilder.cpp.
References A, and B.
buildGraph()
Expected< std::unique_ptr< AtomGraph > > llvm::jitlink::MachOAtomGraphBuilder::buildGraph ()
Definition at line 22 of file MachOAtomGraphBuilder.cpp.
References addRelocations().
getGraph()
AtomGraph & llvm::jitlink::MachOAtomGraphBuilder::getGraph () const inline protected
Definition at line 105 of file MachOAtomGraphBuilder.h.
getObject()
const object::MachOObjectFile & llvm::jitlink::MachOAtomGraphBuilder::getObject () const inline protected
Definition at line 107 of file MachOAtomGraphBuilder.h.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/MachOAtomGraphBuilder.h
lib/ExecutionEngine/JITLink/MachOAtomGraphBuilder.cpp