LLVM: llvm::MCExpr Class Reference
llvm::MCExpr Class Reference
Base class for the full range of assembler expressions which are needed for parsing.
#include "llvm/MC/MCExpr.h"
Public Types
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
Accessors
ExprKind getKind () const
SMLoc getLoc () const
Utility Methods
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
Expression Evaluation
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Protected Member Functions
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Base class for the full range of assembler expressions which are needed for parsing.
Definition at line 35 of file MCExpr.h.
Member Enumeration Documentation
ExprKind
enum llvm::MCExpr::ExprKind
Enumerator
Binary
Binary expressions.
Constant
Constant expressions.
SymbolRef
References to labels and assigned expressions.
Unary
Unary expressions.
Target
Target specific expression.
Definition at line 37 of file MCExpr.h.
Constructor & Destructor Documentation
MCExpr() [1/2]
llvm::MCExpr::MCExpr (ExprKind Kind, SMLoc Loc) inline explicit protected
Definition at line 58 of file MCExpr.h.
MCExpr() [2/2]
llvm::MCExpr::MCExpr (const MCExpr &) delete
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MCExpr::dump () const
Definition at line 150 of file MCExpr.cpp.
evaluateAsAbsolute() [1/5]
bool MCExpr::evaluateAsAbsolute (int64_t & Res) const
Definition at line 455 of file MCExpr.cpp.
evaluateAsAbsolute() [2/5]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAsmLayout & Layout) const
Definition at line 459 of file MCExpr.cpp.
evaluateAsAbsolute() [3/5]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAsmLayout & Layout, const SectionAddrMap & Addrs) const
Try to evaluate the expression to an absolute value.
Parameters
Res - The absolute value, if evaluation succeeds.
Layout - The assembler layout object to use for evaluating symbol values. If not given, then only non-symbolic expressions will be evaluated.
Returns
- True on success.
Definition at line 464 of file MCExpr.cpp.
Referenced by llvm::AArch64InstPrinter::printAlignedLabel(), and llvm::X86InstPrinterCommon::printPCRelImm().
evaluateAsAbsolute() [4/5]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAssembler & Asm) const
Definition at line 470 of file MCExpr.cpp.
evaluateAsAbsolute() [5/5]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAssembler * Asm) const
Definition at line 474 of file MCExpr.cpp.
evaluateAsRelocatable()
bool MCExpr::evaluateAsRelocatable (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
an expression of the fixed form (a - b + constant).
Parameters
Res - The relocatable value, if evaluation succeeds.
Layout - The assembler layout object to use for evaluating values.
Fixup - The Fixup object if available.
Returns
- True on success.
Definition at line 655 of file MCExpr.cpp.
References evaluateAsRelocatableImpl(), Fixup, and llvm::MCAsmLayout::getAssembler().
Referenced by llvm::CodeViewContext::encodeDefRange(), llvm::PPCMCExpr::evaluateAsConstant(), llvm::RISCVMCExpr::evaluateAsConstant(), llvm::AVRMCExpr::evaluateAsConstant(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::HexagonMCExpr::evaluateAsRelocatableImpl(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVMCExpr::evaluateAsRelocatableImpl(), llvm::SparcMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVMCExpr::getPCRelHiFixup(), llvm::MachObjectWriter::getSymbolAddress(), and llvm::MCAssembler::isThumbFunc().
evaluateAsRelocatableImpl()
bool MCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm, const MCAsmLayout * Layout, const MCFixup * Fixup, const SectionAddrMap * Addrs, bool InSet) const protected
-(a - b + const) ==> (b - a - const)
Definition at line 682 of file MCExpr.cpp.
References A, llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, llvm::MCBinaryExpr::AShr, B, Binary, canExpand(), Constant, llvm::MCBinaryExpr::Div, llvm::MCBinaryExpr::EQ, evaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), Fixup, llvm::IntervalMapImpl::NodeRef::get(), llvm::MCValue::getConstant(), getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCUnaryExpr::getOpcode(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isVariable(), llvm::MCBinaryExpr::LAnd, llvm_unreachable, llvm::MCUnaryExpr::LNot, llvm::MCBinaryExpr::LOr, llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, llvm::MCUnaryExpr::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCUnaryExpr::Not, llvm::MCBinaryExpr::Or, llvm::MCUnaryExpr::Plus, llvm::MCBinaryExpr::Shl, llvm::MCBinaryExpr::Sub, SymbolRef, Target, Unary, llvm::MCSymbolRefExpr::VK_None, and llvm::MCBinaryExpr::Xor.
Referenced by evaluateAsRelocatable(), evaluateAsRelocatableImpl(), and evaluateAsValue().
evaluateAsValue()
bool MCExpr::evaluateAsValue (MCValue & Res, const MCAsmLayout & Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
This is a more aggressive variant of evaluateAsRelocatable. The intended use is for when relocations are not available, like the .size directive.
Definition at line 663 of file MCExpr.cpp.
References evaluateAsRelocatableImpl(), and llvm::MCAsmLayout::getAssembler().
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::MCAsmLayout::getBaseSymbol(), and getSymbolOffsetImpl().
evaluateKnownAbsolute()
bool MCExpr::evaluateKnownAbsolute (int64_t & Res, const MCAsmLayout & Layout) const
Definition at line 478 of file MCExpr.cpp.
Referenced by computeLabelDiff().
findAssociatedFragment()
MCFragment * MCExpr::findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Definition at line 875 of file MCExpr.cpp.
References llvm::MCSymbol::AbsolutePseudoFragment, Binary, Constant, findAssociatedFragment(), llvm::MCSymbol::getFragment(), getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCBinaryExpr::Sub, SymbolRef, Target, and Unary.
Referenced by findAssociatedFragment(), llvm::ARMMCExpr::findAssociatedFragment(), llvm::AVRMCExpr::findAssociatedFragment(), llvm::LanaiMCExpr::findAssociatedFragment(), llvm::MipsMCExpr::findAssociatedFragment(), llvm::PPCMCExpr::findAssociatedFragment(), llvm::RISCVMCExpr::findAssociatedFragment(), llvm::SparcMCExpr::findAssociatedFragment(), and llvm::MCSymbol::getFragment().
getKind()
ExprKind llvm::MCExpr::getKind () const inline
Definition at line 72 of file MCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), fixELFSymbolsInTLSFixupsImpl(), getAccessVariant(), llvm::MipsMCCodeEmitter::getExprOpValue(), hasGOTReference(), HasSecRelSymbolRef(), llvm::MCOperand::isBareSymbolRef(), needsPCRel(), llvm::X86Operand::print(), print(), llvm::ARMMCExpr::printImpl(), llvm::ARMInstPrinter::printOperand(), StartsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
getLoc()
SMLoc llvm::MCExpr::getLoc () const inline
Definition at line 73 of file MCExpr.h.
Referenced by llvm::MCAsmLayout::getBaseSymbol().
operator=()
MCExpr & llvm::MCExpr::operator= (const MCExpr &) delete
print()
void MCExpr::print (raw_ostream & OS, const MCAsmInfo * MAI, bool InParens = false) const
Definition at line 42 of file MCExpr.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, llvm::MCBinaryExpr::AShr, Binary, Constant, llvm::MCBinaryExpr::Div, llvm::StringRef::empty(), llvm::MCBinaryExpr::EQ, getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCUnaryExpr::getOpcode(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCBinaryExpr::GT, llvm::MCUnaryExpr::LNot, llvm::MCUnaryExpr::Minus, llvm::MCUnaryExpr::Not, llvm::MCUnaryExpr::Plus, llvm::MCSymbol::print(), print(), llvm::MCSymbolRefExpr::printVariantKind(), SymbolRef, Target, Unary, llvm::Twine::utohexstr(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction(), print(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::ARMInstPrinter::printAdrLabelOperand(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::AArch64MCExpr::printImpl(), llvm::ARMMCExpr::printImpl(), llvm::AVRMCExpr::printImpl(), llvm::HexagonMCExpr::printImpl(), llvm::LanaiMCExpr::printImpl(), llvm::MipsMCExpr::printImpl(), llvm::NVPTXGenericMCSymbolRefExpr::printImpl(), llvm::PPCMCExpr::printImpl(), llvm::RISCVMCExpr::printImpl(), llvm::SparcMCExpr::printImpl(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::X86ATTInstPrinter::printMemOffset(), printMemoryImmediateOffset(), llvm::X86IntelInstPrinter::printMemReference(), llvm::X86ATTInstPrinter::printMemReference(), llvm::SparcInstPrinter::printOperand(), llvm::ARMInstPrinter::printOperand(), llvm::RISCVInstPrinter::printOperand(), llvm::SystemZInstPrinter::printOperand(), llvm::MCSectionELF::PrintSwitchToSection(), llvm::MCSectionWasm::PrintSwitchToSection(), llvm::ARMInstPrinter::printThumbLdrLabelOperand(), and llvm::AArch64InstPrinter::printUImm12Offset().
The documentation for this class was generated from the following files:
include/llvm/MC/MCExpr.h
lib/MC/MCExpr.cpp