LLVM: llvm::MCRegAliasIterator Class Reference
llvm::MCRegAliasIterator Class Reference
MCRegAliasIterator enumerates all registers aliasing Reg.
#include "llvm/MC/MCRegisterInfo.h"
Public Member Functions
MCRegAliasIterator (unsigned Reg, const MCRegisterInfo *MCRI, bool IncludeSelf)
bool isValid () const
unsigned operator* () const
void advance ()
void operator++ ()
Detailed Description
MCRegAliasIterator enumerates all registers aliasing Reg.
If IncludeSelf is set, Reg itself is included in the list. This iterator does not guarantee any ordering or that entries are unique.
Definition at line 668 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCRegAliasIterator()
llvm::MCRegAliasIterator::MCRegAliasIterator (unsigned Reg, const MCRegisterInfo * MCRI, bool IncludeSelf) inline
Definition at line 679 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), and SI.
Member Function Documentation
advance()
void llvm::MCRegAliasIterator::advance () inline
Definition at line 700 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), and SI.
Referenced by operator++().
isValid()
bool llvm::MCRegAliasIterator::isValid () const inline
Definition at line 693 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), addRegAndItsAliases(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), AnyAliasLiveIn(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::calculateDbgEntityHistory(), CheckForLiveRegDef(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), findDeadCallerSavedReg(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::MachineRegisterInfo::isPhysRegModified(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::CCState::IsShadowAllocatedReg(), needToReserveScavengingSpillSlots(), operator++(), llvm::rdf::Liveness::resetKills(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::RegScavenger::scavengeRegister(), setAliasRegs(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::AggressiveAntiDepBreaker::StartBlock(), and llvm::CriticalAntiDepBreaker::StartBlock().
operator*()
unsigned llvm::MCRegAliasIterator::operator* () const inline
Definition at line 695 of file MCRegisterInfo.h.
References assert(), and SI.
operator++()
void llvm::MCRegAliasIterator::operator++ () inline
Definition at line 718 of file MCRegisterInfo.h.
References advance(), assert(), isValid(), and SI.
The documentation for this class was generated from the following file:
include/llvm/MC/MCRegisterInfo.h