LLVM: llvm::CallGraphWrapperPass Class Reference
llvm::CallGraphWrapperPass Class Reference
The ModulePass which wraps up a CallGraph and the logic to build it.
#include "llvm/Analysis/CallGraph.h"
Public Types
using iterator = CallGraph::iterator
using const_iterator = CallGraph::const_iterator
Public Member Functions
CallGraphWrapperPass ()
~CallGraphWrapperPass () override
const CallGraph & getCallGraph () const
The internal CallGraph around which the rest of this interface is wrapped.
CallGraph & getCallGraph ()
Module & getModule () const
Returns the module the call graph corresponds to.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const CallGraphNode * operator[] (const Function *F) const
Returns the call graph node for the provided function.
CallGraphNode * operator[] (const Function *F)
Returns the call graph node for the provided function.
CallGraphNode * getExternalCallingNode () const
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
CallGraphNode * getCallsExternalNode () const
Function * removeFunctionFromModule (CallGraphNode *CGN)
Unlink the function from this module, returning it.
CallGraphNode * getOrInsertFunction (const Function *F)
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnModule (Module &M) override
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void print (raw_ostream &o, const Module *) const override
print - Print out the internal state of the pass.
void dump () const
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
The ModulePass which wraps up a CallGraph and the logic to build it.
This class exposes both the interface to the call graph container and the module pass which runs over a module of IR and produces the call graph. The call graph interface is entirelly a wrapper around a CallGraph object which is stored internally for each module.
Definition at line 324 of file CallGraph.h.
Member Typedef Documentation
const_iterator
using llvm::CallGraphWrapperPass::const_iterator = CallGraph::const_iterator
Definition at line 339 of file CallGraph.h.
iterator
using llvm::CallGraphWrapperPass::iterator = CallGraph::iterator
Definition at line 338 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraphWrapperPass()
CallGraphWrapperPass::CallGraphWrapperPass ()
Definition at line 260 of file CallGraph.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeCallGraphWrapperPassPass().
~CallGraphWrapperPass()
CallGraphWrapperPass::~CallGraphWrapperPass () override default
Member Function Documentation
begin() [1/2]
iterator llvm::CallGraphWrapperPass::begin () inline
Definition at line 344 of file CallGraph.h.
References G.
begin() [2/2]
const_iterator llvm::CallGraphWrapperPass::begin () const inline
Definition at line 346 of file CallGraph.h.
References G.
dump()
LLVM_DUMP_METHOD void CallGraphWrapperPass::dump () const
Definition at line 295 of file CallGraph.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::CallGraphWrapperPass::end () inline
Definition at line 345 of file CallGraph.h.
References G.
end() [2/2]
const_iterator llvm::CallGraphWrapperPass::end () const inline
Definition at line 347 of file CallGraph.h.
References G.
getAnalysisUsage()
void CallGraphWrapperPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 266 of file CallGraph.cpp.
References llvm::AnalysisUsage::setPreservesAll().
getCallGraph() [1/2]
CallGraph & llvm::CallGraphWrapperPass::getCallGraph () inline
Definition at line 336 of file CallGraph.h.
References G.
getCallGraph() [2/2]
const CallGraph & llvm::CallGraphWrapperPass::getCallGraph () const inline
The internal CallGraph around which the rest of this interface is wrapped.
Definition at line 335 of file CallGraph.h.
References G.
getCallsExternalNode()
CallGraphNode * llvm::CallGraphWrapperPass::getCallsExternalNode () const inline
Definition at line 363 of file CallGraph.h.
References G.
getExternalCallingNode()
CallGraphNode * llvm::CallGraphWrapperPass::getExternalCallingNode () const inline
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
Definition at line 359 of file CallGraph.h.
References G.
getModule()
Module & llvm::CallGraphWrapperPass::getModule () const inline
Returns the module the call graph corresponds to.
Definition at line 342 of file CallGraph.h.
References G.
getOrInsertFunction()
CallGraphNode * llvm::CallGraphWrapperPass::getOrInsertFunction (const Function * F) inline
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
Definition at line 384 of file CallGraph.h.
References F, and G.
operator[]() [1/2]
CallGraphNode * llvm::CallGraphWrapperPass::operator[] (const Function * F) inline
Returns the call graph node for the provided function.
Definition at line 355 of file CallGraph.h.
References F, and G.
operator[]() [2/2]
const CallGraphNode * llvm::CallGraphWrapperPass::operator[] (const Function * F) const inline
Returns the call graph node for the provided function.
Definition at line 350 of file CallGraph.h.
References F, and G.
print()
void CallGraphWrapperPass::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 283 of file CallGraph.cpp.
Referenced by dump().
releaseMemory()
void llvm::CallGraphWrapperPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
removeFunctionFromModule()
Function * llvm::CallGraphWrapperPass::removeFunctionFromModule (CallGraphNode * CGN) inline
Unlink the function from this module, returning it.
Because this removes the function from the module, the call graph node is destroyed. This is only valid if the function does not call any other functions (ie, there are no edges in it's CGN). The easiest way to do this is to dropAllReferences before calling this.
Definition at line 378 of file CallGraph.h.
References G.
runOnModule()
bool CallGraphWrapperPass::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 270 of file CallGraph.cpp.
Member Data Documentation
ID
char llvm::CallGraphWrapperPass::ID static
Definition at line 328 of file CallGraph.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CallGraph.h
lib/Analysis/CallGraph.cpp