LLVM: llvm::object::XCOFFObjectFile Class Reference
llvm::object::XCOFFObjectFile Class Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
SubtargetFeatures getFeatures () const override
Expected< uint64_t > getStartAddress () const override
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool is64Bit () const
const XCOFFSymbolEntry * getPointerToSymbolTable () const
Expected< StringRef > getSymbolSectionName (const XCOFFSymbolEntry *SymEntPtr) const
const XCOFFSymbolEntry * toSymbolEntry (DataRefImpl Ref) const
uint16_t getMagic () const
uint16_t getNumberOfSections () const
int32_t getTimeStamp () const
uint32_t getSymbolTableOffset32 () const
uint64_t getSymbolTableOffset64 () const
int32_t getRawNumberOfSymbolTableEntries32 () const
uint32_t getLogicalNumberOfSymbolTableEntries32 () const
uint32_t getNumberOfSymbolTableEntries64 () const
uint16_t getOptionalHeaderSize () const
uint16_t getFlags () const
ArrayRef< XCOFFSectionHeader32 > sections32 () const
ArrayRef< XCOFFSectionHeader64 > sections64 () const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual SubtargetFeatures getFeatures () const =0
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Friends
Expected< std::unique_ptr< ObjectFile > > ObjectFile::createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
uint64_t getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 130 of file XCOFFObjectFile.h.
Member Function Documentation
getArch()
Triple::ArchType llvm::object::XCOFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 333 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::Triple::ppc, and llvm::Triple::ppc64.
getBytesInAddress()
uint8_t llvm::object::XCOFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 327 of file XCOFFObjectFile.cpp.
References is64Bit().
getCommonSymbolSizeImpl()
uint64_t llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 155 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getFeatures()
SubtargetFeatures llvm::object::XCOFFObjectFile::getFeatures () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 337 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getFileFormatName()
StringRef llvm::object::XCOFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 329 of file XCOFFObjectFile.cpp.
References is64Bit().
getFlags()
uint16_t llvm::object::XCOFFObjectFile::getFlags () const
Definition at line 445 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader32::Flags, llvm::object::XCOFFFileHeader64::Flags, and is64Bit().
getLogicalNumberOfSymbolTableEntries32()
uint32_t llvm::object::XCOFFObjectFile::getLogicalNumberOfSymbolTableEntries32 () const
Definition at line 431 of file XCOFFObjectFile.cpp.
Referenced by symbol_end().
getMagic()
uint16_t llvm::object::XCOFFObjectFile::getMagic () const
Definition at line 367 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::object::XCOFFFileHeader32::Magic, and llvm::object::XCOFFFileHeader64::Magic.
getNumberOfSections()
uint16_t llvm::object::XCOFFObjectFile::getNumberOfSections () const
Definition at line 406 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::object::XCOFFFileHeader32::NumberOfSections, and llvm::object::XCOFFFileHeader64::NumberOfSections.
Referenced by section_end(), sections32(), and sections64().
getNumberOfSymbolTableEntries64()
uint32_t llvm::object::XCOFFObjectFile::getNumberOfSymbolTableEntries64 () const
Definition at line 441 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader64::NumberOfSymTableEntries.
getOptionalHeaderSize()
uint16_t llvm::object::XCOFFObjectFile::getOptionalHeaderSize () const
Definition at line 415 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader32::AuxHeaderSize, llvm::object::XCOFFFileHeader64::AuxHeaderSize, and is64Bit().
getPointerToSymbolTable()
const XCOFFSymbolEntry * llvm::object::XCOFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 228 of file XCOFFObjectFile.h.
References assert(), and is64Bit().
getRawNumberOfSymbolTableEntries32()
int32_t llvm::object::XCOFFObjectFile::getRawNumberOfSymbolTableEntries32 () const
Definition at line 424 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader32::NumberOfSymTableEntries.
getRelocationOffset()
uint64_t llvm::object::XCOFFObjectFile::getRelocationOffset (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 270 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getRelocationSymbol()
symbol_iterator llvm::object::XCOFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 276 of file XCOFFObjectFile.cpp.
References llvm_unreachable, and llvm::object::ObjectFile::SymbolRef.
getRelocationType()
uint64_t llvm::object::XCOFFObjectFile::getRelocationType (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 281 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getRelocationTypeName()
void llvm::object::XCOFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 287 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getSectionAddress()
uint64_t llvm::object::XCOFFObjectFile::getSectionAddress (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 191 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::object::XCOFFSectionHeader32::VirtualAddress, and llvm::object::XCOFFSectionHeader64::VirtualAddress.
getSectionAlignment()
uint64_t llvm::object::XCOFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 223 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getSectionContents()
Expected< ArrayRef< uint8_t > > llvm::object::XCOFFObjectFile::getSectionContents (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 219 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getSectionIndex()
uint64_t llvm::object::XCOFFObjectFile::getSectionIndex (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 200 of file XCOFFObjectFile.cpp.
References is64Bit().
getSectionName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSectionName (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 187 of file XCOFFObjectFile.cpp.
References llvm::object::generateStringRef(), and llvm::XCOFF::SectionNameSize.
getSectionSize()
uint64_t llvm::object::XCOFFObjectFile::getSectionSize (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 209 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::object::XCOFFSectionHeader32::SectionSize, and llvm::object::XCOFFSectionHeader64::SectionSize.
getStartAddress()
Expected< uint64_t > llvm::object::XCOFFObjectFile::getStartAddress () const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 348 of file XCOFFObjectFile.cpp.
getSymbolAddress()
Expected< uint64_t > llvm::object::XCOFFObjectFile::getSymbolAddress (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 145 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getSymbolFlags()
uint32_t llvm::object::XCOFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 293 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
getSymbolName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSymbolName (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 118 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFStringTable::Data, llvm::object::generateStringRef(), llvm::object::XCOFFSymbolEntry::NameInStrTblType::Magic, llvm::object::XCOFFSymbolEntry::NAME_IN_STR_TBL_MAGIC, llvm::object::XCOFFSymbolEntry::NameInStrTbl, llvm::object::XCOFFSymbolEntry::NameInStrTblType::Offset, llvm::object::parse_failed, llvm::object::XCOFFStringTable::Size, llvm::object::XCOFFSymbolEntry::StorageClass, llvm::object::XCOFFSymbolEntry::SymbolName, llvm::XCOFF::SymbolNameSize, and toSymbolEntry().
getSymbolSection()
Expected< section_iterator > llvm::object::XCOFFObjectFile::getSymbolSection (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 168 of file XCOFFObjectFile.cpp.
References llvm::Expected< T >::get(), section_end(), llvm::object::XCOFFSymbolEntry::SectionNumber, llvm::object::ObjectFile::SectionRef, llvm::Expected< T >::takeError(), and toSymbolEntry().
getSymbolSectionName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSymbolSectionName (const XCOFFSymbolEntry * SymEntPtr) const
Definition at line 382 of file XCOFFObjectFile.cpp.
References assert(), llvm::object::generateStringRef(), llvm::Expected< T >::get(), is64Bit(), llvm::XCOFF::N_ABS, llvm::XCOFF::N_DEBUG, llvm::XCOFF::N_UNDEF, llvm::XCOFF::SectionNameSize, llvm::object::XCOFFSymbolEntry::SectionNumber, and llvm::Expected< T >::takeError().
getSymbolTableOffset32()
uint32_t llvm::object::XCOFFObjectFile::getSymbolTableOffset32 () const
Definition at line 420 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader32::SymbolTableOffset.
getSymbolTableOffset64()
uint64_t llvm::object::XCOFFObjectFile::getSymbolTableOffset64 () const
Definition at line 437 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFFileHeader64::SymbolTableOffset.
getSymbolType()
Expected< SymbolRef::Type > llvm::object::XCOFFObjectFile::getSymbolType (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 162 of file XCOFFObjectFile.cpp.
References llvm_unreachable, and llvm::object::SymbolRef::ST_Other.
getSymbolValueImpl()
uint64_t llvm::object::XCOFFObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 151 of file XCOFFObjectFile.cpp.
References toSymbolEntry(), and llvm::object::XCOFFSymbolEntry::Value.
getTimeStamp()
int32_t llvm::object::XCOFFObjectFile::getTimeStamp () const
Definition at line 411 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::object::XCOFFFileHeader32::TimeStamp, and llvm::object::XCOFFFileHeader64::TimeStamp.
is64Bit()
bool llvm::object::XCOFFObjectFile::is64Bit () const
Definition at line 363 of file XCOFFObjectFile.cpp.
References llvm::object::Binary::getType(), and llvm::object::Binary::ID_XCOFF64.
Referenced by getArch(), getBytesInAddress(), getFileFormatName(), getFlags(), getMagic(), getNumberOfSections(), getOptionalHeaderSize(), getPointerToSymbolTable(), getSectionAddress(), getSectionIndex(), getSectionSize(), getSymbolSectionName(), getTimeStamp(), sections32(), sections64(), symbol_begin(), symbol_end(), and toSymbolEntry().
isRelocatableObject()
bool llvm::object::XCOFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 342 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
isSectionBSS()
bool llvm::object::XCOFFObjectFile::isSectionBSS (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 244 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::STYP_BSS, and llvm::XCOFF::STYP_TBSS.
isSectionCompressed()
bool llvm::object::XCOFFObjectFile::isSectionCompressed (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 229 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
isSectionData()
bool llvm::object::XCOFFObjectFile::isSectionData (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 239 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::STYP_DATA, and llvm::XCOFF::STYP_TDATA.
isSectionText()
bool llvm::object::XCOFFObjectFile::isSectionText (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 235 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::STYP_TEXT.
isSectionVirtual()
bool llvm::object::XCOFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 249 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
moveRelocationNext()
void llvm::object::XCOFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 265 of file XCOFFObjectFile.cpp.
References llvm_unreachable.
moveSectionNext()
void llvm::object::XCOFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 182 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
moveSymbolNext()
void llvm::object::XCOFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 112 of file XCOFFObjectFile.cpp.
References llvm::object::XCOFFSymbolEntry::NumberOfAuxEntries, llvm::object::DataRefImpl::p, and toSymbolEntry().
section_begin()
section_iterator llvm::object::XCOFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 314 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, and llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator llvm::object::XCOFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 320 of file XCOFFObjectFile.cpp.
References getNumberOfSections(), llvm::object::getWithOffset(), llvm::object::DataRefImpl::p, and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection().
section_rel_begin()
relocation_iterator llvm::object::XCOFFObjectFile::section_rel_begin (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 255 of file XCOFFObjectFile.cpp.
References llvm_unreachable, and llvm::object::ObjectFile::RelocationRef.
section_rel_end()
relocation_iterator llvm::object::XCOFFObjectFile::section_rel_end (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 260 of file XCOFFObjectFile.cpp.
References llvm_unreachable, and llvm::object::ObjectFile::RelocationRef.
sections32()
ArrayRef< XCOFFSectionHeader32 > llvm::object::XCOFFObjectFile::sections32 () const
Definition at line 473 of file XCOFFObjectFile.cpp.
References assert(), getNumberOfSections(), and is64Bit().
sections64()
ArrayRef< XCOFFSectionHeader64 > llvm::object::XCOFFObjectFile::sections64 () const
Definition at line 466 of file XCOFFObjectFile.cpp.
References assert(), getNumberOfSections(), and is64Bit().
symbol_begin()
basic_symbol_iterator llvm::object::XCOFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 299 of file XCOFFObjectFile.cpp.
References assert(), is64Bit(), llvm::object::DataRefImpl::p, and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator llvm::object::XCOFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 306 of file XCOFFObjectFile.cpp.
References assert(), getLogicalNumberOfSymbolTableEntries32(), is64Bit(), llvm::object::DataRefImpl::p, and llvm::object::ObjectFile::SymbolRef.
toSymbolEntry()
const XCOFFSymbolEntry * llvm::object::XCOFFObjectFile::toSymbolEntry (DataRefImpl Ref) const
Definition at line 83 of file XCOFFObjectFile.cpp.
References assert(), is64Bit(), and llvm::Ref.
Referenced by getSymbolName(), getSymbolSection(), getSymbolValueImpl(), and moveSymbolNext().
Friends And Related Function Documentation
ObjectFile::createXCOFFObjectFile
Expected< std::unique_ptr< ObjectFile > > ObjectFile::createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType) friend
The documentation for this class was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp