LLVM: llvm::MachineLoopInfo Class Reference
llvm::MachineLoopInfo Class Reference
#include "llvm/CodeGen/MachineLoopInfo.h"
Public Types
using iterator = LoopInfoBase< MachineBasicBlock, MachineLoop >::iterator
The iterator interface to the top-level loops in the current function.
Public Member Functions
MachineLoopInfo ()
MachineLoopInfo (const MachineLoopInfo &)=delete
MachineLoopInfo & operator= (const MachineLoopInfo &)=delete
LoopInfoBase< MachineBasicBlock, MachineLoop > & getBase ()
MachineBasicBlock * findLoopPreheader (MachineLoop *L, bool SpeculativePreheader=false) const
Find the block that either is the loop preheader, or could speculatively be used as the preheader.
iterator begin () const
iterator end () const
bool empty () const
MachineLoop * getLoopFor (const MachineBasicBlock *BB) const
Return the innermost loop that BB lives in.
const MachineLoop * operator[] (const MachineBasicBlock *BB) const
Same as getLoopFor.
unsigned getLoopDepth (const MachineBasicBlock *BB) const
Return the loop nesting level of the specified block.
bool isLoopHeader (const MachineBasicBlock *BB) const
True if the block is a loop header node.
bool runOnMachineFunction (MachineFunction &F) override
Calculate the natural loop information.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
MachineLoop * removeLoop (iterator I)
This removes the specified top-level loop from this loop info object.
void changeLoopFor (MachineBasicBlock *BB, MachineLoop *L)
Change the top-level loop that contains BB to the specified loop.
void changeTopLevelLoop (MachineLoop *OldLoop, MachineLoop *NewLoop)
Replace the specified loop in the top-level loops list with the indicated loop.
void addTopLevelLoop (MachineLoop *New)
This adds the specified loop to the collection of top-level loops.
void removeBlock (MachineBasicBlock *BB)
This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from MachineBasicBlocks to loops.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Friends
class LoopBase< MachineBasicBlock, MachineLoop >
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 83 of file MachineLoopInfo.h.
Member Typedef Documentation
iterator
using llvm::MachineLoopInfo::iterator = LoopInfoBase<MachineBasicBlock, MachineLoop>::iterator
The iterator interface to the top-level loops in the current function.
Definition at line 108 of file MachineLoopInfo.h.
Constructor & Destructor Documentation
MachineLoopInfo() [1/2]
llvm::MachineLoopInfo::MachineLoopInfo () inline
Definition at line 91 of file MachineLoopInfo.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineLoopInfoPass().
MachineLoopInfo() [2/2]
llvm::MachineLoopInfo::MachineLoopInfo (const MachineLoopInfo &) delete
Member Function Documentation
addTopLevelLoop()
void llvm::MachineLoopInfo::addTopLevelLoop (MachineLoop * New) inline
This adds the specified loop to the collection of top-level loops.
Definition at line 159 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop().
begin()
iterator llvm::MachineLoopInfo::begin () const inline
Definition at line 109 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::begin().
changeLoopFor()
void llvm::MachineLoopInfo::changeLoopFor (MachineBasicBlock * BB, MachineLoop * L) inline
Change the top-level loop that contains BB to the specified loop.
This should be used by transformations that restructure the loop hierarchy tree.
Definition at line 148 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor().
changeTopLevelLoop()
void llvm::MachineLoopInfo::changeTopLevelLoop (MachineLoop * OldLoop, MachineLoop * NewLoop) inline
Replace the specified loop in the top-level loops list with the indicated loop.
Definition at line 154 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeTopLevelLoop().
empty()
bool llvm::MachineLoopInfo::empty () const inline
Definition at line 111 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::empty().
end()
iterator llvm::MachineLoopInfo::end () const inline
Definition at line 110 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::end().
findLoopPreheader()
MachineBasicBlock * MachineLoopInfo::findLoopPreheader (MachineLoop * L, bool SpeculativePreheader = false) const
Find the block that either is the loop preheader, or could speculatively be used as the preheader.
This is e.g. useful to place loop setup code. Code that cannot be speculated should not be placed here. SpeculativePreheader is controlling whether it also tries to find the speculative preheader if the regular preheader is not present.
Definition at line 107 of file MachineLoopInfo.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::MachineBasicBlock::hasAddressTaken(), P, llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::predecessors(), and llvm::MachineBasicBlock::successors().
getAnalysisUsage()
void MachineLoopInfo::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 44 of file MachineLoopInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getBase()
LoopInfoBase< MachineBasicBlock, MachineLoop > & llvm::MachineLoopInfo::getBase () inline
Definition at line 97 of file MachineLoopInfo.h.
getLoopDepth()
unsigned llvm::MachineLoopInfo::getLoopDepth (const MachineBasicBlock * BB) const inline
Return the loop nesting level of the specified block.
Definition at line 125 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopDepth().
Referenced by llvm::VLIWMachineScheduler::schedule().
getLoopFor()
MachineLoop * llvm::MachineLoopInfo::getLoopFor (const MachineBasicBlock * BB) const inline
Return the innermost loop that BB lives in.
If a basic block is in no loop (for example the entry node), null is returned.
Definition at line 115 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
Referenced by emitBasicBlockLoopComments(), llvm::SystemZPostRASchedStrategy::enterMBB(), findLoopPreheader(), llvm::HexagonPacketizerList::producesStall(), sortBlocks(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isLoopHeader()
bool llvm::MachineLoopInfo::isLoopHeader (const MachineBasicBlock * BB) const inline
True if the block is a loop header node.
Definition at line 130 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::isLoopHeader().
operator=()
MachineLoopInfo & llvm::MachineLoopInfo::operator= (const MachineLoopInfo &) delete
operator[]()
const MachineLoop * llvm::MachineLoopInfo::operator[] (const MachineBasicBlock * BB) const inline
Same as getLoopFor.
Definition at line 120 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
releaseMemory()
void llvm::MachineLoopInfo::releaseMemory () inline override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 137 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory().
removeBlock()
void llvm::MachineLoopInfo::removeBlock (MachineBasicBlock * BB) inline
This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from MachineBasicBlocks to loops.
Definition at line 166 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::removeBlock().
removeLoop()
MachineLoop * llvm::MachineLoopInfo::removeLoop (iterator I) inline
This removes the specified top-level loop from this loop info object.
The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 143 of file MachineLoopInfo.h.
References I, and llvm::LoopInfoBase< BlockT, LoopT >::removeLoop().
runOnMachineFunction()
bool MachineLoopInfo::runOnMachineFunction (MachineFunction & F) override virtual
Calculate the natural loop information.
Implements llvm::MachineFunctionPass.
Definition at line 38 of file MachineLoopInfo.cpp.
Friends And Related Function Documentation
LoopBase< MachineBasicBlock, MachineLoop >
friend class LoopBase< MachineBasicBlock, MachineLoop > friend
Definition at line 77 of file MachineLoopInfo.h.
Member Data Documentation
ID
char MachineLoopInfo::ID = 0 static
Definition at line 89 of file MachineLoopInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineLoopInfo.h
lib/CodeGen/MachineLoopInfo.cpp