LLVM: llvm::AArch64FrameLowering Class Reference
llvm::AArch64FrameLowering Class Reference
#include "Target/AArch64/AArch64FrameLowering.h"
Public Member Functions
AArch64FrameLowering ()
void emitCalleeSavedFrameMoves (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool canUseAsPrologue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a prologue for the target.
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
int resolveFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg, bool PreferFP, bool ForSimm) const
int resolveFrameOffsetReference (const MachineFunction &MF, int ObjectOffset, bool isFixed, unsigned &FrameReg, bool PreferFP, bool ForSimm) const
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool canUseRedZone (const MachineFunction &MF) const
Can this function use the red zone for local allocations.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
bool enableShrinkWrapping (const MachineFunction &MF) const override
Returns true if the target will correctly handle shrink wrapping.
bool enableStackSlotScavenging (const MachineFunction &MF) const override
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const override
The parent frame offset (aka dispFrame) is only used on X86_64 to retrieve the parent's frame pointer.
unsigned getWinEHFuncletFrameSize (const MachineFunction &MF) const
Funclets only need to account for space for the callee saved registers, as the locals are accounted for in the parent's stack frame.
int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const override
For Win64 AArch64 EH, the offset to the Unwind object is from the SP before the update.
int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const override
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
int getSEHFrameIndexOffset (const MachineFunction &MF, int FI) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
virtual void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasFP (const MachineFunction &MF) const =0
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual int getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, unsigned &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual int getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual unsigned getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 20 of file AArch64FrameLowering.h.
Constructor & Destructor Documentation
AArch64FrameLowering()
llvm::AArch64FrameLowering::AArch64FrameLowering () inline explicit
Definition at line 22 of file AArch64FrameLowering.h.
Member Function Documentation
canUseAsPrologue()
bool AArch64FrameLowering::canUseAsPrologue (const MachineBasicBlock & MBB) const override virtual
Check whether or not the given MBB can be used as a prologue for the target.
The prologue will be inserted first in this basic block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 380 of file AArch64FrameLowering.cpp.
References findScratchNonCalleeSaveRegister(), llvm::MachineBasicBlock::getParent(), llvm::AArch64Subtarget::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
canUseRedZone()
bool AArch64FrameLowering::canUseRedZone (const MachineFunction & MF) const
Can this function use the red zone for local allocations.
Definition at line 186 of file AArch64FrameLowering.cpp.
References EnableRedZone, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::MachineFrameInfo::hasCalls(), hasFP(), and llvm::GCOVOptions::NoRedZone.
Referenced by emitEpilogue(), emitPrologue(), and resolveFrameOffsetReference().
determineCalleeSaves()
void AArch64FrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2044 of file AArch64FrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::alignTo(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), contains(), llvm::BitVector::count(), llvm::MachineFrameInfo::CreateStackObject(), llvm::dbgs(), llvm::TargetFrameLowering::determineCalleeSaves(), estimateRSStackSizeLimit(), llvm::MachineFrameInfo::estimateStackSize(), llvm::AArch64RegisterInfo::getBaseRegister(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm::AArch64RegisterInfo::hasBasePointer(), hasFP(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::AArch64RegisterInfo::isReservedReg(), LLVM_DEBUG, MRI, llvm::printReg(), produceCompactUnwindFrame(), llvm::BitVector::set(), llvm::BitVector::set_bits(), llvm::AArch64FunctionInfo::setCalleeSavedStackSize(), llvm::AArch64FunctionInfo::setCalleeSaveStackHasFreeSpace(), llvm::AArch64FunctionInfo::setHasStackFrame(), Size, llvm::BitVector::test(), TRI, and windowsRequiresStackProbe().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator AArch64FrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 243 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), assert(), llvm::emitFrameOffset(), llvm::MachineBasicBlock::erase(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), hasReservedCallFrame(), I, and TII.
emitCalleeSavedFrameMoves()
void AArch64FrameLowering::emitCalleeSavedFrameMoves (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI) const
Definition at line 313 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::createOffset(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstr::FrameSetup, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), Info, MRI, llvm::MachineInstrBuilder::setMIFlags(), and TII.
Referenced by emitPrologue().
emitEpilogue()
void AArch64FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 1264 of file AArch64FrameLowering.cpp.
References adaptForLdStOpt(), llvm::alignTo(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), canUseRedZone(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::emitFrameOffset(), llvm::MachineBasicBlock::end(), fixupCalleeSaveRestoreStackOffset(), llvm::MachineInstr::FrameDestroy, llvm::AArch64FunctionInfo::getArgumentStackToRestore(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::AArch64Subtarget::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getVarArgsGPRSize(), getWinEHFuncletFrameSize(), llvm::CallingConv::GHC, llvm::MachineFunction::hasEHFunclets(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFunction::hasWinCFI(), InsertReturnAddressAuth(), llvm::AArch64Subtarget::isCallingConvWin64(), isFuncletReturnInstr(), llvm::AArch64InstrInfo::isSEHInstruction(), llvm::AArch64FunctionInfo::isStackRealigned(), llvm::make_scope_exit(), needsWinCFI(), llvm::MachineFunction::setHasWinCFI(), llvm::AArch64FunctionInfo::setLocalStackSize(), llvm::MachineInstrBuilder::setMIFlag(), and TII.
emitPrologue()
void AArch64FrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 794 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::alignTo(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), canUseRedZone(), llvm::classifyEHPersonality(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::countTrailingZeros(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createNegateRAState(), llvm::MCContext::createTempSymbol(), llvm::RegState::Dead, llvm::RegState::Define, emitCalleeSavedFrameMoves(), llvm::emitFrameOffset(), llvm::MachineBasicBlock::end(), F, findScratchNonCalleeSaveRegister(), fixupCalleeSaveRestoreStackOffset(), FramePtr, llvm::MachineInstr::FrameSetup, llvm::AArch64_AM::getArithExtendImm(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::TargetMachine::getCodeModel(), llvm::MachineModuleInfo::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64Subtarget::getInstrInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getMMI(), llvm::DataLayout::getPointerSize(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::AArch64_AM::getShifterImm(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::AArch64FunctionInfo::getVarArgsGPRSize(), getWinEHFuncletFrameSize(), llvm::CallingConv::GHC, llvm::MachineModuleInfo::hasDebugInfo(), hasFP(), llvm::AArch64FunctionInfo::hasStackFrame(), llvm::RegState::Implicit, llvm::isAsynchronousEHPersonality(), llvm::AArch64Subtarget::isCallingConvWin64(), llvm::MachineBasicBlock::isEHFuncletEntry(), llvm::CodeModel::Kernel, llvm::RegState::Kill, llvm::CodeModel::Large, llvm::AArch64_AM::LSL, llvm::make_scope_exit(), llvm::CodeModel::Medium, needsWinCFI(), llvm::report_fatal_error(), llvm::AArch64FunctionInfo::setHasRedZone(), llvm::MachineFunction::setHasWinCFI(), llvm::AArch64FunctionInfo::setLocalStackSize(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineInstrBuilder::setMIFlags(), llvm::AArch64FunctionInfo::setStackRealigned(), llvm::AArch64FunctionInfo::setTaggedBasePointerOffset(), ShouldSignReturnAddress(), ShouldSignWithAKey(), llvm::CodeModel::Small, TII, llvm::CodeModel::Tiny, llvm::MCAsmInfo::usesWindowsCFI(), llvm::AArch64_AM::UXTX, and windowsRequiresStackProbe().
enableShrinkWrapping()
bool llvm::AArch64FrameLowering::enableShrinkWrapping (const MachineFunction & MF) const inline override virtual
Returns true if the target will correctly handle shrink wrapping.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 68 of file AArch64FrameLowering.h.
enableStackSlotScavenging()
bool AArch64FrameLowering::enableStackSlotScavenging (const MachineFunction & MF) const override virtual
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2178 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), and llvm::AArch64FunctionInfo::hasCalleeSaveStackFreeSpace().
getFrameIndexReference()
int AArch64FrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
It's the same as what we use for resolving the code-gen references for now. FIXME: This can go wrong when references are SP-relative and simple call frames aren't used.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1500 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFunction(), and resolveFrameIndexReference().
getFrameIndexReferencePreferSP()
int AArch64FrameLowering::getFrameIndexReferencePreferSP (const MachineFunction & MF, int FI, unsigned & FrameReg, bool IgnoreSPUpdates) const override virtual
For Win64 AArch64 EH, the offset to the Unwind object is from the SP before the update.
This is easily retrieved as it is exactly the offset that is set in processFunctionBeforeFrameFinalized.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2220 of file AArch64FrameLowering.cpp.
References llvm::dbgs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), and LLVM_DEBUG.
getNonLocalFrameIndexReference()
int AArch64FrameLowering::getNonLocalFrameIndexReference (const MachineFunction & MF, int FI) const override virtual
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
The offset can be from either FP/BP/SP based on which base register is returned by llvm.localaddress.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1510 of file AArch64FrameLowering.cpp.
References getSEHFrameIndexOffset().
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex().
getSEHFrameIndexOffset()
int AArch64FrameLowering::getSEHFrameIndexOffset (const MachineFunction & MF, int FI) const
Definition at line 1529 of file AArch64FrameLowering.cpp.
References getFPOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), getStackOffset(), and llvm::MachineFunction::getSubtarget().
Referenced by getNonLocalFrameIndexReference().
getWinEHFuncletFrameSize()
unsigned AArch64FrameLowering::getWinEHFuncletFrameSize (const MachineFunction & MF) const
Funclets only need to account for space for the callee saved registers, as the locals are accounted for in the parent's stack frame.
Definition at line 2239 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), and llvm::TargetFrameLowering::getStackAlignment().
Referenced by emitEpilogue(), and emitPrologue().
getWinEHParentFrameOffset()
unsigned AArch64FrameLowering::getWinEHParentFrameOffset (const MachineFunction & MF) const override virtual
The parent frame offset (aka dispFrame) is only used on X86_64 to retrieve the parent's frame pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2232 of file AArch64FrameLowering.cpp.
hasFP()
bool AArch64FrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
Implements llvm::TargetFrameLowering.
Definition at line 203 of file AArch64FrameLowering.cpp.
References DefaultSafeSPDisplacement, llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineFunction::hasEHFunclets(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::MachineFrameInfo::isMaxCallFrameSizeComputed(), llvm::TargetRegisterInfo::needsStackRealignment(), and llvm::TargetMachine::Options.
Referenced by canUseRedZone(), determineCalleeSaves(), emitEpilogue(), emitPrologue(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), resolveFrameOffsetReference(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
hasReservedCallFrame()
bool AArch64FrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 239 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr().
processFunctionBeforeFrameFinalized()
void AArch64FrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2184 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::RegScavenger::backward(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineBasicBlock::end(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::RegScavenger::FindUnusedReg(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::front(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::getKillRegState(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getWinEHFuncInfo(), llvm::MachineFunction::hasEHFunclets(), TII, and llvm::WinEHFuncInfo::UnwindHelpFrameIdx.
resolveFrameIndexReference()
int AArch64FrameLowering::resolveFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg, bool PreferFP, bool ForSimm) const
Definition at line 1539 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), and resolveFrameOffsetReference().
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex(), and getFrameIndexReference().
resolveFrameOffsetReference()
int AArch64FrameLowering::resolveFrameOffsetReference (const MachineFunction & MF, int ObjectOffset, bool isFixed, unsigned & FrameReg, bool PreferFP, bool ForSimm) const
Definition at line 1550 of file AArch64FrameLowering.cpp.
References assert(), canUseRedZone(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), getFPOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), getStackOffset(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::hasEHFunclets(), hasFP(), and llvm::AArch64FunctionInfo::hasStackFrame().
Referenced by resolveFrameIndexReference().
restoreCalleeSavedRegisters()
bool AArch64FrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1943 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), computeCalleeSaveRegisterPairs(), llvm::dbgs(), llvm::RegState::Define, llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameDestroy, llvm::getDefRegState(), llvm::MachinePointerInfo::getFixedStack(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), InsertSEH(), LLVM_DEBUG, MI, llvm::MachineMemOperand::MOLoad, needsWinCFI(), llvm::printReg(), llvm::reverse(), ReverseCSRRestoreSeq, llvm::MachineInstrBuilder::setMIFlag(), Size, std::swap(), TII, and TRI.
spillCalleeSavedRegisters()
bool AArch64FrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1816 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), computeCalleeSaveRegisterPairs(), llvm::MCCFIInstruction::createEscape(), llvm::dbgs(), llvm::RegState::Define, llvm::MachineInstr::FrameSetup, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), getPrologueDeath(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), InsertSEH(), LLVM_DEBUG, MI, llvm::MachineMemOperand::MOStore, MRI, needsWinCFI(), llvm::printReg(), llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), llvm::SmallVectorTemplateCommon< T, typename >::rend(), llvm::MachineInstrBuilder::setMIFlag(), Size, std::swap(), TII, and TRI.
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64FrameLowering.h
lib/Target/AArch64/AArch64FrameLowering.cpp