LLVM: lib/Transforms/Coroutines/CoroFrame.cpp File Reference
CoroFrame.cpp File Reference
#include "CoroInternal.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/circular_raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "coro-suspend-crossing"
#define DEBUG_TYPE "coro-frame"
Typedefs
using SpillInfo = SmallVector< Spill, 8 >
Enumerations
enum { SmallVectorThreshold = 32 }
Functions
static void dump (StringRef Title, SpillInfo const &Spills)
static StructType * buildFrameType (Function &F, coro::Shape &Shape, SpillInfo &Spills)
static Instruction * splitBeforeCatchSwitch (CatchSwitchInst *CatchSwitch)
static Instruction * insertSpills (SpillInfo &Spills, coro::Shape &Shape)
static void setUnwindEdgeTo (Instruction *TI, BasicBlock *Succ)
static void updatePhiNodes (BasicBlock *DestBB, BasicBlock *OldPred, BasicBlock *NewPred, PHINode *LandingPadReplacement)
static BasicBlock * ehAwareSplitEdge (BasicBlock *BB, BasicBlock *Succ, LandingPadInst *OriginalPad, PHINode *LandingPadReplacement)
static void rewritePHIs (BasicBlock &BB)
static void rewritePHIs (Function &F)
static bool materializable (Instruction &V)
static bool isCoroutineStructureIntrinsic (Instruction &I)
static void rewriteMaterializableInstructions (IRBuilder<> &IRB, SpillInfo const &Spills)
static void moveSpillUsesAfterCoroBegin (Function &F, SpillInfo const &Spills, CoroBeginInst *CoroBegin)
static BasicBlock * splitBlockIfNotFirst (Instruction *I, const Twine &Name)
static void splitAround (Instruction *I, const Twine &Name)
Macro Definition Documentation
DEBUG_TYPE [1/2]
#define DEBUG_TYPE "coro-suspend-crossing"
Definition at line 259 of file CoroFrame.cpp.
DEBUG_TYPE [2/2]
#define DEBUG_TYPE "coro-frame"
Definition at line 259 of file CoroFrame.cpp.
Typedef Documentation
SpillInfo
using SpillInfo = SmallVector<Spill, 8>
Definition at line 295 of file CoroFrame.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SmallVectorThreshold
Definition at line 38 of file CoroFrame.cpp.
Function Documentation
buildFrameType()
static StructType * buildFrameType (Function & F, coro::Shape & Shape, SpillInfo & Spills) static
Definition at line 371 of file CoroFrame.cpp.
References C, llvm::coro::Shape::CoroSuspends, llvm::StructType::create(), F, llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerType::getElementType(), llvm::Type::getInt1Ty(), llvm::Type::getIntNTy(), llvm::Type::getPointerTo(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::Type::getVoidTy(), llvm::Log2_64_Ceil(), Name, llvm::coro::Shape::PromiseAlloca, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::StructType::setBody(), and llvm::SmallVectorBase::size().
Referenced by llvm::coro::buildCoroutineFrame().
dump()
static void dump (StringRef Title, SpillInfo const & Spills) static
Definition at line 298 of file CoroFrame.cpp.
References llvm::dbgs(), llvm::Value::dump(), and E.
Referenced by llvm::coro::buildCoroutineFrame().
ehAwareSplitEdge()
static BasicBlock * ehAwareSplitEdge (BasicBlock * BB, BasicBlock * Succ, LandingPadInst * OriginalPad, PHINode * LandingPadReplacement) static
Definition at line 676 of file CoroFrame.cpp.
References llvm::PHINode::addIncoming(), llvm::Instruction::clone(), llvm::BranchInst::Create(), llvm::BasicBlock::Create(), llvm::CleanupReturnInst::Create(), llvm::CleanupPadInst::Create(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getFirstNonPHI(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Instruction::isEHPad(), llvm_unreachable, setUnwindEdgeTo(), llvm::SplitEdge(), and updatePhiNodes().
Referenced by rewritePHIs().
insertSpills()
static Instruction * insertSpills (SpillInfo & Spills, coro::Shape & Shape) static
Definition at line 479 of file CoroFrame.cpp.
References llvm::coro::Shape::AllocaSpillBlock, assert(), C, llvm::coro::Shape::CoroBegin, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateStore(), E, llvm::SmallVectorImpl< T >::emplace_back(), FramePtr, llvm::coro::Shape::FrameTy, llvm::BasicBlock::front(), G, llvm::ConstantInt::get(), llvm::StructType::getElementType(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Type::getInt32Ty(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::Type::getPointerTo(), llvm::BasicBlock::getTerminator(), P, llvm::coro::Shape::PromiseAlloca, llvm::coro::Shape::PromiseField, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::IRBuilderBase::SetInsertPoint(), llvm::BasicBlock::splitBasicBlock(), splitBeforeCatchSwitch(), and llvm::SplitEdge().
Referenced by llvm::coro::buildCoroutineFrame().
isCoroutineStructureIntrinsic()
static bool isCoroutineStructureIntrinsic (Instruction & I) static
Definition at line 788 of file CoroFrame.cpp.
References I.
Referenced by llvm::coro::buildCoroutineFrame().
materializable()
static bool materializable (Instruction & V) static
Definition at line 781 of file CoroFrame.cpp.
Referenced by llvm::coro::buildCoroutineFrame().
moveSpillUsesAfterCoroBegin()
static void moveSpillUsesAfterCoroBegin (Function & F, SpillInfo const & Spills, CoroBeginInst * CoroBegin) static
Definition at line 841 of file CoroFrame.cpp.
References llvm::dbgs(), llvm::DominatorTree::dominates(), E, F, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), I, LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), and llvm::Value::users().
Referenced by llvm::coro::buildCoroutineFrame().
rewriteMaterializableInstructions()
static void rewriteMaterializableInstructions (IRBuilder<> & IRB, SpillInfo const & Spills) static
Definition at line 795 of file CoroFrame.cpp.
References assert(), llvm::Instruction::clone(), E, llvm::BasicBlock::getFirstInsertionPt(), llvm::Value::getName(), llvm::Instruction::insertBefore(), and llvm::Value::setName().
Referenced by llvm::coro::buildCoroutineFrame().
rewritePHIs() [1/2]
static void rewritePHIs (BasicBlock & BB) static
Definition at line 707 of file CoroFrame.cpp.
References llvm::PHINode::addIncoming(), llvm::PHINode::Create(), ehAwareSplitEdge(), llvm::Instruction::eraseFromParent(), llvm::StringRef::front(), llvm::BasicBlock::front(), llvm::BasicBlock::getFirstNonPHI(), llvm::Value::getName(), llvm::Value::getType(), llvm::pred_begin(), llvm::pred_end(), llvm::Value::replaceAllUsesWith(), and llvm::Value::takeName().
Referenced by llvm::coro::buildCoroutineFrame(), and rewritePHIs().
rewritePHIs() [2/2]
static void rewritePHIs (Function & F) static
Definition at line 767 of file CoroFrame.cpp.
References F, llvm::BasicBlock::front(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and rewritePHIs().
setUnwindEdgeTo()
static void setUnwindEdgeTo (Instruction * TI, BasicBlock * Succ) static
Definition at line 636 of file CoroFrame.cpp.
References llvm_unreachable.
Referenced by ehAwareSplitEdge().
splitAround()
static void splitAround (Instruction * I, const Twine & Name) static
Definition at line 893 of file CoroFrame.cpp.
References I, Name, and splitBlockIfNotFirst().
Referenced by llvm::coro::buildCoroutineFrame().
splitBeforeCatchSwitch()
static Instruction * splitBeforeCatchSwitch (CatchSwitchInst * CatchSwitch) static
Definition at line 445 of file CoroFrame.cpp.
References llvm::CleanupReturnInst::Create(), llvm::CleanupPadInst::Create(), llvm::Instruction::eraseFromParent(), llvm::Instruction::getParent(), llvm::CatchSwitchInst::getParentPad(), llvm::BasicBlock::getTerminator(), and llvm::BasicBlock::splitBasicBlock().
Referenced by insertSpills().
splitBlockIfNotFirst()
static BasicBlock * splitBlockIfNotFirst (Instruction * I, const Twine & Name) static
Definition at line 880 of file CoroFrame.cpp.
References llvm::BasicBlock::front(), llvm::BasicBlock::getSinglePredecessor(), I, Name, llvm::Value::setName(), and llvm::BasicBlock::splitBasicBlock().
Referenced by splitAround().
updatePhiNodes()
static void updatePhiNodes (BasicBlock * DestBB, BasicBlock * OldPred, BasicBlock * NewPred, PHINode * LandingPadReplacement) static
Definition at line 649 of file CoroFrame.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::PHINode::getBasicBlockIndex(), llvm::PHINode::getIncomingBlock(), I, and llvm::PHINode::setIncomingBlock().
Referenced by ehAwareSplitEdge().