LLVM: lib/Transforms/Coroutines/CoroSplit.cpp File Reference
CoroSplit.cpp File Reference
#include "CoroInstr.h"
#include "CoroInternal.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iterator>
Macros
#define DEBUG_TYPE "coro-split"
Functions
static BasicBlock * createResumeEntryBlock (Function &F, coro::Shape &Shape)
static void replaceFallthroughCoroEnd (IntrinsicInst *End, ValueToValueMapTy &VMap)
static void replaceUnwindCoroEnds (coro::Shape &Shape, ValueToValueMapTy &VMap)
static void handleFinalSuspend (IRBuilder<> &Builder, Value *FramePtr, coro::Shape &Shape, SwitchInst *Switch, bool IsDestroy)
static Function * createClone (Function &F, Twine Suffix, coro::Shape &Shape, BasicBlock *ResumeEntry, int8_t FnIndex)
static void removeCoroEnds (coro::Shape &Shape)
static void replaceFrameSize (coro::Shape &Shape)
static void setCoroInfo (Function &F, CoroBeginInst *CoroBegin, std::initializer_list< Function * > Fns)
static void updateCoroFrame (coro::Shape &Shape, Function *ResumeFn, Function *DestroyFn, Function *CleanupFn)
static void postSplitCleanup (Function &F)
static void scanPHIsAndUpdateValueMap (Instruction *Prev, BasicBlock *NewBlock, DenseMap< Value *, Value * > &ResolvedValues)
static bool simplifyTerminatorLeadingToRet (Instruction *InitialInst)
static void addMustTailToCoroResumes (Function &F)
static void handleNoSuspendCoroutine (CoroBeginInst *CoroBegin, Type *FrameTy)
static bool hasCallsInBlockBetween (Instruction *From, Instruction *To)
static bool hasCallsInBlocksBetween (BasicBlock *SaveBB, BasicBlock *ResDesBB)
static bool hasCallsBetween (Instruction *Save, Instruction *ResumeOrDestroy)
static bool simplifySuspendPoint (CoroSuspendInst *Suspend, CoroBeginInst *CoroBegin)
static void simplifySuspendPoints (coro::Shape &Shape)
static SmallPtrSet< BasicBlock *, 4 > getCoroBeginPredBlocks (CoroBeginInst *CB)
static SmallPtrSet< Instruction *, 8 > getNotRelocatableInstructions (CoroBeginInst *CoroBegin, SmallPtrSetImpl< BasicBlock * > &RelocBlocks)
static void relocateInstructionBefore (CoroBeginInst *CoroBegin, Function &F)
static void splitCoroutine (Function &F, CallGraph &CG, CallGraphSCC &SCC)
static void prepareForSplit (Function &F, CallGraph &CG)
static void createDevirtTriggerFunc (CallGraph &CG, CallGraphSCC &SCC)
INITIALIZE_PASS_BEGIN (CoroSplit, "coro-split", "Split coroutine into a set of functions driving its state machine", false, false) INITIALIZE_PASS_END(CoroSplit
Variables
coro split
coro Split coroutine into a set of functions driving its state machine
coro Split coroutine into a set of functions driving its state false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-split"
Definition at line 71 of file CoroSplit.cpp.
Function Documentation
addMustTailToCoroResumes()
static void addMustTailToCoroResumes (Function & F) static
Definition at line 497 of file CoroSplit.cpp.
References F, I, instructions, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::removeUnreachableBlocks(), simplifyTerminatorLeadingToRet(), and llvm::CallInst::TCK_MustTail.
Referenced by splitCoroutine().
createClone()
static Function * createClone (Function & F, Twine Suffix, coro::Shape & Shape, BasicBlock * ResumeEntry, int8_t FnIndex) static
Definition at line 245 of file CoroSplit.cpp.
References A, llvm::Function::addParamAttr(), llvm::coro::Shape::AllocaSpillBlock, llvm::Function::arg_begin(), llvm::changeToUnreachable(), llvm::CloneFunctionInto(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, llvm::BranchInst::Create(), llvm::Function::Create(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), F, llvm::RegBankSelect::Fast, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::BasicBlock::front(), llvm::UndefValue::get(), llvm::IRBuilderBase::getContext(), llvm::Function::getEntryBlock(), llvm::CoroBeginInst::getId(), llvm::IRBuilderBase::getInt8(), llvm::Type::getInt8PtrTy(), llvm::Function::getReturnType(), handleFinalSuspend(), llvm::coro::Shape::HasFinalSuspend, llvm::NoAlias, llvm::Function::removeAttributes(), llvm::Value::replaceAllUsesWith(), llvm::coro::replaceCoroFree(), replaceFallthroughCoroEnd(), replaceUnwindCoroEnds(), llvm::coro::Shape::ResumeSwitch, llvm::AttributeList::ReturnIndex, llvm::Function::setCallingConv(), llvm::GlobalValue::setLinkage(), llvm::Value::takeName(), and llvm::AttributeFuncs::typeIncompatible().
Referenced by splitCoroutine().
createDevirtTriggerFunc()
static void createDevirtTriggerFunc (CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 862 of file CoroSplit.cpp.
References llvm::Function::addFnAttr(), llvm::CallGraphSCC::begin(), C, CORO_DEVIRT_TRIGGER_FN, llvm::Function::Create(), llvm::ReturnInst::Create(), llvm::BasicBlock::Create(), llvm::CallGraphSCC::end(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getInt8PtrTy(), llvm::CallGraph::getModule(), llvm::CallGraph::getOrInsertFunction(), llvm::Type::getVoidTy(), llvm::CallGraphSCC::initialize(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
createResumeEntryBlock()
static BasicBlock * createResumeEntryBlock (Function & F, coro::Shape & Shape) static
Definition at line 75 of file CoroSplit.cpp.
References C, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), llvm::PHINode::Create(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateSwitch(), llvm::IRBuilder< T, Inserter >::CreateUnreachable(), F, FramePtr, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantTokenNone::get(), llvm::ConstantPointerNull::get(), llvm::CoroSuspendInst::getCoroSave(), llvm::coro::Shape::getIndex(), llvm::coro::Shape::getIndexType(), llvm::IRBuilderBase::getInt8(), llvm::IRBuilderBase::getInt8Ty(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), llvm::coro::Shape::IndexField, llvm::CoroSuspendInst::isFinal(), llvm::Value::replaceAllUsesWith(), llvm::coro::Shape::ResumeSwitch, llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
Referenced by splitCoroutine().
getCoroBeginPredBlocks()
static SmallPtrSet< BasicBlock *, 4 > getCoroBeginPredBlocks (CoroBeginInst * CB) static
Definition at line 690 of file CoroSplit.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase::empty(), llvm::Instruction::getParent(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by relocateInstructionBefore().
getNotRelocatableInstructions()
static SmallPtrSet< Instruction *, 8 > getNotRelocatableInstructions (CoroBeginInst * CoroBegin, SmallPtrSetImpl< BasicBlock * > & RelocBlocks) static
Definition at line 708 of file CoroSplit.cpp.
References A, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::SmallVectorBase::empty(), llvm::Instruction::getParent(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and SI.
Referenced by relocateInstructionBefore().
handleFinalSuspend()
static void handleFinalSuspend (IRBuilder<> & Builder, Value * FramePtr, coro::Shape & Shape, SwitchInst * Switch, bool IsDestroy) static
Definition at line 219 of file CoroSplit.cpp.
References assert(), llvm::SwitchInst::case_end(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::Instruction::eraseFromParent(), FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantPointerNull::get(), llvm::StructType::getElementType(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::coro::Shape::HasFinalSuspend, llvm::SwitchInst::removeCase(), llvm::coro::Shape::ResumeField, llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
Referenced by createClone().
handleNoSuspendCoroutine()
static void handleNoSuspendCoroutine (CoroBeginInst * CoroBegin, Type * FrameTy) static
Definition at line 523 of file CoroSplit.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAlloca(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::Instruction::eraseFromParent(), llvm::CoroIdInst::getCoroAlloc(), llvm::IRBuilderBase::getFalse(), llvm::CoroBeginInst::getId(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::CoroBeginInst::getMem(), llvm::Value::replaceAllUsesWith(), and llvm::coro::replaceCoroFree().
Referenced by splitCoroutine().
hasCallsBetween()
static bool hasCallsBetween (Instruction * Save, Instruction * ResumeOrDestroy) static
Definition at line 585 of file CoroSplit.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), hasCallsInBlockBetween(), and hasCallsInBlocksBetween().
Referenced by simplifySuspendPoint().
hasCallsInBlockBetween()
static bool hasCallsInBlockBetween (Instruction * From, Instruction * To) static
Definition at line 544 of file CoroSplit.cpp.
References From, and I.
Referenced by hasCallsBetween(), and hasCallsInBlocksBetween().
hasCallsInBlocksBetween()
static bool hasCallsInBlocksBetween (BasicBlock * SaveBB, BasicBlock * ResDesBB) static
Definition at line 556 of file CoroSplit.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl< PtrType >::erase(), hasCallsInBlockBetween(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by hasCallsBetween().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (CoroSplit , "coro-split" , "Split coroutine into a set of functions driving its state machine" , false , false)
postSplitCleanup()
static void postSplitCleanup (Function & F) static
Definition at line 423 of file CoroSplit.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::createCFGSimplificationPass(), llvm::createEarlyCSEPass(), llvm::createSCCPPass(), llvm::createVerifierPass(), llvm::legacy::FunctionPassManager::doFinalization(), llvm::legacy::FunctionPassManager::doInitialization(), F, llvm::removeUnreachableBlocks(), and llvm::legacy::FunctionPassManager::run().
Referenced by splitCoroutine().
prepareForSplit()
static void prepareForSplit (Function & F, CallGraph & CG) static
Definition at line 831 of file CoroSplit.cpp.
References assert(), Context, CORO_DEVIRT_TRIGGER_FN, CORO_PRESPLIT_ATTR, llvm::CallInst::Create(), F, llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantPointerNull::get(), llvm::CallGraph::getCallsExternalNode(), llvm::Type::getInt8PtrTy(), llvm::Type::getVoidTy(), llvm::coro::LowererBase::makeSubFnCall(), PREPARED_FOR_SPLIT, and llvm::CoroSubFnInst::RestartTrigger.
relocateInstructionBefore()
static void relocateInstructionBefore (CoroBeginInst * CoroBegin, Function & F) static
Definition at line 756 of file CoroSplit.cpp.
References B, llvm::BasicBlock::begin(), E, llvm::BasicBlock::end(), F, getCoroBeginPredBlocks(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), getNotRelocatableInstructions(), and I.
Referenced by splitCoroutine().
removeCoroEnds()
static void removeCoroEnds (coro::Shape & Shape) static
Definition at line 339 of file CoroSplit.cpp.
References Context, llvm::coro::Shape::CoroEnds, and llvm::ConstantInt::getFalse().
Referenced by splitCoroutine().
replaceFallthroughCoroEnd()
static void replaceFallthroughCoroEnd (IntrinsicInst * End, ValueToValueMapTy & VMap) static
Definition at line 172 of file CoroSplit.cpp.
References llvm::ReturnInst::Create().
Referenced by createClone().
replaceFrameSize()
static void replaceFrameSize (coro::Shape & Shape) static
Definition at line 352 of file CoroSplit.cpp.
References llvm::coro::Shape::CoroSizes, llvm::Instruction::eraseFromParent(), llvm::coro::Shape::FrameTy, llvm::ConstantInt::get(), llvm::DataLayout::getTypeAllocSize(), llvm::Value::replaceAllUsesWith(), and Size.
Referenced by splitCoroutine().
replaceUnwindCoroEnds()
static void replaceUnwindCoroEnds (coro::Shape & Shape, ValueToValueMapTy & VMap) static
Definition at line 185 of file CoroSplit.cpp.
References Context, llvm::coro::Shape::CoroEnds, llvm::CleanupReturnInst::Create(), llvm::ConstantInt::getTrue(), and llvm::LLVMContext::OB_funclet.
Referenced by createClone().
scanPHIsAndUpdateValueMap()
static void scanPHIsAndUpdateValueMap (Instruction * Prev, BasicBlock * NewBlock, DenseMap< Value *, Value * > & ResolvedValues) static
Definition at line 441 of file CoroSplit.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Instruction::getParent(), llvm::BasicBlock::phis(), and VI.
Referenced by simplifyTerminatorLeadingToRet().
setCoroInfo()
static void setCoroInfo (Function & F, CoroBeginInst * CoroBegin, std::initializer_list< Function * > Fns) static
Definition at line 380 of file CoroSplit.cpp.
References assert(), llvm::Function::begin(), C, F, llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantArray::get(), llvm::CoroBeginInst::getId(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPointerCast(), llvm::GlobalValue::getType(), and llvm::CoroIdInst::setInfo().
Referenced by splitCoroutine().
simplifySuspendPoint()
static bool simplifySuspendPoint (CoroSuspendInst * Suspend, CoroBeginInst * CoroBegin) static
Definition at line 610 of file CoroSplit.cpp.
References Callee, llvm::BranchInst::Create(), llvm::Instruction::eraseFromParent(), llvm::CoroSuspendInst::getCoroSave(), llvm::Instruction::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::BasicBlock::getSinglePredecessor(), hasCallsBetween(), I, and llvm::Value::replaceAllUsesWith().
Referenced by simplifySuspendPoints().
simplifySuspendPoints()
static void simplifySuspendPoints (coro::Shape & Shape) static
Definition at line 672 of file CoroSplit.cpp.
References llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, I, N, simplifySuspendPoint(), and std::swap().
Referenced by splitCoroutine().
simplifyTerminatorLeadingToRet()
static bool simplifyTerminatorLeadingToRet (Instruction * InitialInst) static
Definition at line 458 of file CoroSplit.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime(), I, llvm::ReplaceInstWithInst(), scanPHIsAndUpdateValueMap(), and SI.
Referenced by addMustTailToCoroResumes().
splitCoroutine()
static void splitCoroutine (Function & F, CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 779 of file CoroSplit.cpp.
References addMustTailToCoroResumes(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, createClone(), createResumeEntryBlock(), llvm::EliminateUnreachableBlocks(), F, llvm::coro::Shape::FrameTy, handleNoSuspendCoroutine(), postSplitCleanup(), relocateInstructionBefore(), removeCoroEnds(), replaceFrameSize(), setCoroInfo(), simplifySuspendPoints(), llvm::coro::updateCallGraph(), and updateCoroFrame().
updateCoroFrame()
static void updateCoroFrame (coro::Shape & Shape, Function * ResumeFn, Function * DestroyFn, Function * CleanupFn) static
Definition at line 400 of file CoroSplit.cpp.
References llvm::coro::Shape::CoroBegin, llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::coro::Shape::DestroyField, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::CoroIdInst::getCoroAlloc(), llvm::CoroBeginInst::getId(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::coro::Shape::ResumeField.
Referenced by splitCoroutine().
Variable Documentation
false
coro Split coroutine into a set of functions driving its state false
Definition at line 956 of file CoroSplit.cpp.
machine
coro Split coroutine into a set of functions driving its state machine
Definition at line 956 of file CoroSplit.cpp.
split
coro split
Definition at line 955 of file CoroSplit.cpp.
Referenced by llvm::StringRef::split().