LLVM: lib/Transforms/Utils/CtorUtils.cpp File Reference
CtorUtils.cpp File Reference
#include "llvm/Transforms/Utils/CtorUtils.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "ctor_utils"
Functions
static void removeGlobalCtors (GlobalVariable *GCL, const BitVector &CtorsToRemove)
Given a specified llvm.global_ctors list, remove the listed elements.
static std::vector< Function * > parseGlobalCtors (GlobalVariable *GV)
Given a llvm.global_ctors list that we can understand, return a list of the functions and null terminator as a vector.
static GlobalVariable * findGlobalCtors (Module &M)
Find the llvm.global_ctors list, verifying that all initializers have an init priority of 65535.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ctor_utils"
Definition at line 22 of file CtorUtils.cpp.
Function Documentation
findGlobalCtors()
static GlobalVariable * findGlobalCtors (Module & M) static
Find the llvm.global_ctors list, verifying that all initializers have an init priority of 65535.
Definition at line 80 of file CtorUtils.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getOperand(), llvm::ConstantInt::getZExtValue(), llvm::GlobalVariable::hasUniqueInitializer(), and llvm::User::operands().
Referenced by llvm::optimizeGlobalCtorsList().
parseGlobalCtors()
static std::vector< Function * > parseGlobalCtors (GlobalVariable * GV) static
Given a llvm.global_ctors list that we can understand, return a list of the functions and null terminator as a vector.
Definition at line 65 of file CtorUtils.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Constant::isNullValue(), and llvm::User::operands().
Referenced by llvm::optimizeGlobalCtorsList().
removeGlobalCtors()
static void removeGlobalCtors (GlobalVariable * GCL, const BitVector & CtorsToRemove) static
Given a specified llvm.global_ctors list, remove the listed elements.
Definition at line 27 of file CtorUtils.cpp.
References E, llvm::GlobalVariable::eraseFromParent(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantArray::get(), llvm::ConstantExpr::getBitCast(), llvm::SequentialType::getElementType(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::GlobalValue::getLinkage(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getThreadLocalMode(), llvm::ConstantArray::getType(), llvm::GlobalValue::getType(), llvm::Value::getType(), I, llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::GlobalVariable::isConstant(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::GlobalVariable::setInitializer(), llvm::SmallVectorBase::size(), llvm::Value::takeName(), llvm::BitVector::test(), and llvm::Value::use_empty().
Referenced by llvm::optimizeGlobalCtorsList().