LLVM: lib/Transforms/Instrumentation/GCOVProfiling.cpp File Reference
GCOVProfiling.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Instrumentation/GCOVProfiler.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <memory>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "insert-gcov-profiling"
Functions
INITIALIZE_PASS_BEGIN (GCOVProfilerLegacyPass, "insert-gcov-profiling", "Insert instrumentation for GCOV profiling", false, false) INITIALIZE_PASS_END(GCOVProfilerLegacyPass
static StringRef getFunctionName (const DISubprogram *SP)
static SmallString< 128 > getFilename (const DISubprogram *SP)
Extract a filename for a DISubprogram.
static bool functionHasLines (Function &F)
static bool isUsingScopeBasedEH (Function &F)
static bool shouldKeepInEntry (BasicBlock::iterator It)
Variables
static cl::opt< std::string > DefaultGCOVVersion ("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired)
static cl::opt< bool > DefaultExitBlockBeforeBody ("gcov-exit-block-before-body", cl::init(false), cl::Hidden)
insert gcov profiling
insert gcov Insert instrumentation for GCOV false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "insert-gcov-profiling"
Definition at line 49 of file GCOVProfiling.cpp.
Function Documentation
functionHasLines()
static bool functionHasLines (Function & F) static
Definition at line 585 of file GCOVProfiling.cpp.
References F, llvm::DebugLoc::getLine(), and I.
getFilename()
static SmallString< 128 > getFilename (const DISubprogram * SP) static
Extract a filename for a DISubprogram.
Prefer relative paths in the coverage notes. Clang also may split up absolute paths into a directory and filename component. When the relative path doesn't exist, reconstruct the absolute path.
Definition at line 187 of file GCOVProfiling.cpp.
References llvm::sys::path::append(), llvm::sys::fs::exists(), llvm::DIScope::getDirectory(), and llvm::DIScope::getFilename().
getFunctionName()
static StringRef getFunctionName (const DISubprogram * SP) static
Definition at line 176 of file GCOVProfiling.cpp.
References llvm::DIScope::getName().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (GCOVProfilerLegacyPass , "insert-gcov-profiling" , "Insert instrumentation for GCOV profiling" , false , false)
isUsingScopeBasedEH()
static bool isUsingScopeBasedEH (Function & F) static
Definition at line 607 of file GCOVProfiling.cpp.
References llvm::classifyEHPersonality(), F, and llvm::isScopedEHPersonality().
shouldKeepInEntry()
static bool shouldKeepInEntry (BasicBlock::iterator It) static
Definition at line 614 of file GCOVProfiling.cpp.
Variable Documentation
DefaultExitBlockBeforeBody
cl::opt< bool > DefaultExitBlockBeforeBody("gcov-exit-block-before-body", cl::init(false), cl::Hidden) ("gcov-exit-block-before-body" , cl::init(false) , cl::Hidden) static
Referenced by llvm::GCOVOptions::getDefault().
DefaultGCOVVersion
cl::opt< std::string > DefaultGCOVVersion("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired) ("default-gcov-version" , cl::init("402*") , cl::Hidden , cl::ValueRequired) static
Referenced by llvm::GCOVOptions::getDefault().
false
insert gcov Insert instrumentation for GCOV false
Definition at line 170 of file GCOVProfiling.cpp.
profiling
insert gcov Insert instrumentation for GCOV profiling
Definition at line 169 of file GCOVProfiling.cpp.