LLVM: General APIs
General APIs
LLVM-C: C interface to LLVM » Core » Values
Functions in this section work on all LLVMValueRef instances, regardless of their sub-type.
Macros
#define LLVM_DECLARE_VALUE_CAST(name) LLVMValueRef LLVMIsA##name(LLVMValueRef Val);
Convert value instances between types.
Functions
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
Obtain the type of a value.
LLVMValueKind LLVMGetValueKind (LLVMValueRef Val)
Obtain the enumerated type of a Value instance.
const char * LLVMGetValueName2 (LLVMValueRef Val, size_t *Length)
Obtain the string name of a value.
void LLVMSetValueName2 (LLVMValueRef Val, const char *Name, size_t NameLen)
Set the string name of a value.
void LLVMDumpValue (LLVMValueRef Val)
Dump a representation of a value to stderr.
char * LLVMPrintValueToString (LLVMValueRef Val)
Return a string representation of the value.
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
Replace all uses of a value with another one.
LLVMBool LLVMIsConstant (LLVMValueRef Val)
Determine whether the specified value instance is constant.
LLVMBool LLVMIsUndef (LLVMValueRef Val)
Determine whether a value instance is undefined.
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
const char * LLVMGetValueName (LLVMValueRef Val)
Deprecated: Use LLVMGetValueName2 instead.
void LLVMSetValueName (LLVMValueRef Val, const char *Name)
Deprecated: Use LLVMSetValueName2 instead.
Detailed Description
Functions in this section work on all LLVMValueRef instances, regardless of their sub-type.
They correspond to functions available on llvm::Value.
Macro Definition Documentation
LLVM_DECLARE_VALUE_CAST
#define LLVM_DECLARE_VALUE_CAST (name) LLVMValueRef LLVMIsA##name(LLVMValueRef Val);
Convert value instances between types.
Internally, an LLVMValueRef is "pinned" to a specific type. This series of functions allows you to cast an instance to a specific type.
If the cast is not valid for the specified type, NULL is returned.
See also
llvm::dyn_cast_or_null<>
Definition at line 1678 of file Core.h.
Function Documentation
LLVMDumpValue()
void LLVMDumpValue (LLVMValueRef Val)
Dump a representation of a value to stderr.
See also
llvm::Value::dump()
Definition at line 837 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMGetValueKind()
LLVMValueKind LLVMGetValueKind (LLVMValueRef Val)
Obtain the enumerated type of a Value instance.
See also
llvm::Value::getValueID()
Definition at line 808 of file Core.cpp.
References LLVMInstructionValueKind, and llvm::unwrap().
LLVMGetValueName()
const char * LLVMGetValueName (LLVMValueRef Val)
Deprecated: Use LLVMGetValueName2 instead.
Definition at line 829 of file Core.cpp.
References llvm::unwrap().
LLVMGetValueName2()
const char * LLVMGetValueName2 (LLVMValueRef Val, size_t * Length)
Obtain the string name of a value.
See also
llvm::Value::getName()
Definition at line 819 of file Core.cpp.
References llvm::unwrap().
LLVMIsAMDNode()
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
Definition at line 932 of file Core.cpp.
References llvm::unwrap().
LLVMIsAMDString()
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
Definition at line 940 of file Core.cpp.
References llvm::unwrap().
LLVMIsConstant()
LLVMBool LLVMIsConstant (LLVMValueRef Val)
Determine whether the specified value instance is constant.
Definition at line 1028 of file Core.cpp.
References llvm::unwrap().
LLVMIsUndef()
LLVMBool LLVMIsUndef (LLVMValueRef Val)
Determine whether a value instance is undefined.
Definition at line 1038 of file Core.cpp.
References llvm::unwrap().
LLVMPrintValueToString()
char * LLVMPrintValueToString (LLVMValueRef Val)
Return a string representation of the value.
Use LLVMDisposeMessage to free the string.
See also
llvm::Value::print()
Definition at line 841 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMReplaceAllUsesWith()
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
Replace all uses of a value with another one.
See also
llvm::Value::replaceAllUsesWith()
Definition at line 855 of file Core.cpp.
References llvm::unwrap().
LLVMSetValueName()
void LLVMSetValueName (LLVMValueRef Val, const char * Name)
Deprecated: Use LLVMSetValueName2 instead.
Definition at line 833 of file Core.cpp.
References Name, and llvm::unwrap().
LLVMSetValueName2()
void LLVMSetValueName2 (LLVMValueRef Val, const char * Name, size_t NameLen)
Set the string name of a value.
See also
llvm::Value::setName()
Definition at line 825 of file Core.cpp.
References Name, and llvm::unwrap().
LLVMTypeOf()
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
Obtain the type of a value.
See also
llvm::Value::getType()
Definition at line 804 of file Core.cpp.
References getType(), llvm::unwrap(), and llvm::wrap().