LLVM: Pass manager builder
Pass manager builder
LLVM-C: C interface to LLVM » Transforms
Functions
LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate (void)
See llvm::PassManagerBuilder.
void LLVMPassManagerBuilderDispose (LLVMPassManagerBuilderRef PMB)
void LLVMPassManagerBuilderSetOptLevel (LLVMPassManagerBuilderRef PMB, unsigned OptLevel)
See llvm::PassManagerBuilder::OptLevel.
void LLVMPassManagerBuilderSetSizeLevel (LLVMPassManagerBuilderRef PMB, unsigned SizeLevel)
See llvm::PassManagerBuilder::SizeLevel.
void LLVMPassManagerBuilderSetDisableUnitAtATime (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnitAtATime.
void LLVMPassManagerBuilderSetDisableUnrollLoops (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnrollLoops.
void LLVMPassManagerBuilderSetDisableSimplifyLibCalls (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableSimplifyLibCalls.
void LLVMPassManagerBuilderUseInlinerWithThreshold (LLVMPassManagerBuilderRef PMB, unsigned Threshold)
See llvm::PassManagerBuilder::Inliner.
void LLVMPassManagerBuilderPopulateFunctionPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateFunctionPassManager.
void LLVMPassManagerBuilderPopulateModulePassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateModulePassManager.
void LLVMPassManagerBuilderPopulateLTOPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM, LLVMBool Internalize, LLVMBool RunInliner)
See llvm::PassManagerBuilder::populateLTOPassManager.
Detailed Description
Function Documentation
LLVMPassManagerBuilderCreate()
LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate (void)
See llvm::PassManagerBuilder.
Definition at line 1056 of file PassManagerBuilder.cpp.
References llvm::wrap().
LLVMPassManagerBuilderDispose()
void LLVMPassManagerBuilderDispose (LLVMPassManagerBuilderRef PMB)
Definition at line 1061 of file PassManagerBuilder.cpp.
References llvm::unwrap().
LLVMPassManagerBuilderPopulateFunctionPassManager()
void LLVMPassManagerBuilderPopulateFunctionPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateFunctionPassManager.
Definition at line 1107 of file PassManagerBuilder.cpp.
References llvm::PassManagerBuilder::populateFunctionPassManager(), and llvm::unwrap().
LLVMPassManagerBuilderPopulateLTOPassManager()
void LLVMPassManagerBuilderPopulateLTOPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM, LLVMBool Internalize, LLVMBool RunInliner)
See llvm::PassManagerBuilder::populateLTOPassManager.
Definition at line 1122 of file PassManagerBuilder.cpp.
References llvm::createFunctionInliningPass(), llvm::PassManagerBuilder::Inliner, llvm::PassManagerBuilder::populateLTOPassManager(), and llvm::unwrap().
LLVMPassManagerBuilderPopulateModulePassManager()
void LLVMPassManagerBuilderPopulateModulePassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateModulePassManager.
Definition at line 1115 of file PassManagerBuilder.cpp.
References llvm::PassManagerBuilder::populateModulePassManager(), and llvm::unwrap().
LLVMPassManagerBuilderSetDisableSimplifyLibCalls()
void LLVMPassManagerBuilderSetDisableSimplifyLibCalls (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableSimplifyLibCalls.
Definition at line 1094 of file PassManagerBuilder.cpp.
LLVMPassManagerBuilderSetDisableUnitAtATime()
void LLVMPassManagerBuilderSetDisableUnitAtATime (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnitAtATime.
Definition at line 1081 of file PassManagerBuilder.cpp.
LLVMPassManagerBuilderSetDisableUnrollLoops()
void LLVMPassManagerBuilderSetDisableUnrollLoops (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnrollLoops.
Definition at line 1087 of file PassManagerBuilder.cpp.
References llvm::PassManagerBuilder::DisableUnrollLoops, and llvm::unwrap().
LLVMPassManagerBuilderSetOptLevel()
void LLVMPassManagerBuilderSetOptLevel (LLVMPassManagerBuilderRef PMB, unsigned OptLevel)
See llvm::PassManagerBuilder::OptLevel.
Definition at line 1067 of file PassManagerBuilder.cpp.
References llvm::PassManagerBuilder::OptLevel, and llvm::unwrap().
LLVMPassManagerBuilderSetSizeLevel()
void LLVMPassManagerBuilderSetSizeLevel (LLVMPassManagerBuilderRef PMB, unsigned SizeLevel)
See llvm::PassManagerBuilder::SizeLevel.
Definition at line 1074 of file PassManagerBuilder.cpp.
References llvm::PassManagerBuilder::SizeLevel, and llvm::unwrap().
LLVMPassManagerBuilderUseInlinerWithThreshold()
void LLVMPassManagerBuilderUseInlinerWithThreshold (LLVMPassManagerBuilderRef PMB, unsigned Threshold)
See llvm::PassManagerBuilder::Inliner.
Definition at line 1100 of file PassManagerBuilder.cpp.
References llvm::createFunctionInliningPass(), llvm::PassManagerBuilder::Inliner, Threshold, and llvm::unwrap().