LLVM: Metadata
Metadata
LLVM-C: C interface to LLVM » Core
Functions
LLVMMetadataRef LLVMMDStringInContext2 (LLVMContextRef C, const char *Str, size_t SLen)
Create an MDString value from a given string value.
LLVMMetadataRef LLVMMDNodeInContext2 (LLVMContextRef C, LLVMMetadataRef *MDs, size_t Count)
Create an MDNode value with the given array of operands.
LLVMValueRef LLVMMetadataAsValue (LLVMContextRef C, LLVMMetadataRef MD)
Obtain a Metadata as a Value.
LLVMMetadataRef LLVMValueAsMetadata (LLVMValueRef Val)
Obtain a Value as a Metadata.
const char * LLVMGetMDString (LLVMValueRef V, unsigned *Length)
Obtain the underlying string from a MDString value.
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Obtain the number of operands from an MDNode value.
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef *Dest)
Obtain the given MDNode's operands.
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char *Str, unsigned SLen)
Deprecated: Use LLVMMDStringInContext2 instead.
LLVMValueRef LLVMMDString (const char *Str, unsigned SLen)
Deprecated: Use LLVMMDStringInContext2 instead.
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef *Vals, unsigned Count)
Deprecated: Use LLVMMDNodeInContext2 instead.
LLVMValueRef LLVMMDNode (LLVMValueRef *Vals, unsigned Count)
Deprecated: Use LLVMMDNodeInContext2 instead.
Detailed Description
Function Documentation
LLVMGetMDNodeNumOperands()
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Obtain the number of operands from an MDNode value.
Parameters
V MDNode to get number of operands from.
Returns
Number of operands of the MDNode.
Definition at line 1123 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetNumOperands().
LLVMGetMDNodeOperands()
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef * Dest)
Obtain the given MDNode's operands.
The passed LLVMValueRef pointer should point to enough memory to hold all of the operands of the given MDNode (see LLVMGetMDNodeNumOperands) as LLVMValueRefs. This memory will be populated with the LLVMValueRefs of the MDNode's operands.
Parameters
V MDNode to get the operands from.
Dest Destination array for operands.
Definition at line 1178 of file Core.cpp.
References Context, getMDNodeOperandImpl(), N, llvm::unwrap(), and llvm::wrap().
LLVMGetMDString()
const char * LLVMGetMDString (LLVMValueRef V, unsigned * Length)
Obtain the underlying string from a MDString value.
Parameters
V Instance to obtain string from.
Length Memory address which will hold length of returned string.
Returns
String data in MDString.
Definition at line 1113 of file Core.cpp.
References llvm::unwrap().
LLVMMDNode()
LLVMValueRef LLVMMDNode (LLVMValueRef * Vals, unsigned Count)
Deprecated: Use LLVMMDNodeInContext2 instead.
Definition at line 1096 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDNodeInContext().
LLVMMDNodeInContext()
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef * Vals, unsigned Count)
Deprecated: Use LLVMMDNodeInContext2 instead.
Definition at line 1069 of file Core.cpp.
References assert(), C, Context, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MetadataAsValue::get(), llvm::LocalAsMetadata::get(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDNode().
LLVMMDNodeInContext2()
LLVMMetadataRef LLVMMDNodeInContext2 (LLVMContextRef C, LLVMMetadataRef * MDs, size_t Count)
Create an MDNode value with the given array of operands.
See also
llvm::MDNode::get()
Definition at line 1053 of file Core.cpp.
References C, llvm::MDNode::get(), llvm::unwrap(), and llvm::wrap().
LLVMMDString()
LLVMValueRef LLVMMDString (const char * Str, unsigned SLen)
Deprecated: Use LLVMMDStringInContext2 instead.
Definition at line 1065 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDStringInContext().
LLVMMDStringInContext()
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char * Str, unsigned SLen)
Deprecated: Use LLVMMDStringInContext2 instead.
Definition at line 1058 of file Core.cpp.
References C, Context, llvm::MetadataAsValue::get(), llvm::MDString::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDString().
LLVMMDStringInContext2()
LLVMMetadataRef LLVMMDStringInContext2 (LLVMContextRef C, const char * Str, size_t SLen)
Create an MDString value from a given string value.
The MDString value does not take ownership of the given string, it remains the responsibility of the caller to free it.
See also
llvm::MDString::get()
Definition at line 1048 of file Core.cpp.
References C, llvm::MDString::get(), llvm::unwrap(), and llvm::wrap().
LLVMMetadataAsValue()
LLVMValueRef LLVMMetadataAsValue (LLVMContextRef C, LLVMMetadataRef MD)
Obtain a Metadata as a Value.
Definition at line 1100 of file Core.cpp.
References C, llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMValueAsMetadata()
LLVMMetadataRef LLVMValueAsMetadata (LLVMValueRef Val)
Obtain a Value as a Metadata.
Definition at line 1104 of file Core.cpp.
References C, llvm::ConstantAsMetadata::get(), llvm::ValueAsMetadata::get(), llvm::unwrap(), and llvm::wrap().