LLVM: Composite Constants
Composite Constants
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions in this group operate on composite constants.
Functions
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char *Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential and initialize it with a string.
LLVMValueRef LLVMConstString (const char *Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential with string content in the global context.
LLVMBool LLVMIsConstantString (LLVMValueRef c)
Returns true if the specified constant is an array of i8.
const char * LLVMGetAsString (LLVMValueRef c, size_t *Length)
Get the given constant data sequential as a string.
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
Create an anonymous ConstantStruct with the specified values.
LLVMValueRef LLVMConstStruct (LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
Create a ConstantStruct in the global Context.
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef *ConstantVals, unsigned Length)
Create a ConstantArray from values.
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef *ConstantVals, unsigned Count)
Create a non-anonymous ConstantStruct from values.
LLVMValueRef LLVMGetElementAsConstant (LLVMValueRef C, unsigned idx)
Get an element at specified index as a constant.
LLVMValueRef LLVMConstVector (LLVMValueRef *ScalarConstantVals, unsigned Size)
Create a ConstantVector from values.
Detailed Description
Functions in this group operate on composite constants.
Function Documentation
LLVMConstArray()
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef * ConstantVals, unsigned Length)
Create a ConstantArray from values.
See also
llvm::ConstantArray::get()
Definition at line 1397 of file Core.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantArray::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstNamedStruct()
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef * ConstantVals, unsigned Count)
Create a non-anonymous ConstantStruct from values.
See also
llvm::ConstantStruct::get()
Definition at line 1417 of file Core.cpp.
References llvm::ConstantStruct::get(), llvm::makeArrayRef(), llvm::unwrap(), and llvm::wrap().
LLVMConstString()
LLVMValueRef LLVMConstString (const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential with string content in the global context.
This is the same as LLVMConstStringInContext except it operates on the global context.
See also
LLVMConstStringInContext()
llvm::ConstantDataArray::getString()
Definition at line 1377 of file Core.cpp.
References LLVMConstStringInContext(), and LLVMGetGlobalContext().
LLVMConstStringInContext()
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential and initialize it with a string.
See also
llvm::ConstantDataArray::getString()
Definition at line 1368 of file Core.cpp.
References C, llvm::ConstantDataArray::getString(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstString().
LLVMConstStruct()
LLVMValueRef LLVMConstStruct (LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Create a ConstantStruct in the global Context.
This is the same as LLVMConstStructInContext except it operates on the global Context.
See also
LLVMConstStructInContext()
Definition at line 1411 of file Core.cpp.
References LLVMConstStructInContext(), and LLVMGetGlobalContext().
LLVMConstStructInContext()
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Create an anonymous ConstantStruct with the specified values.
See also
llvm::ConstantStruct::getAnon()
Definition at line 1403 of file Core.cpp.
References C, llvm::ConstantStruct::getAnon(), llvm::makeArrayRef(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstStruct().
LLVMConstVector()
LLVMValueRef LLVMConstVector (LLVMValueRef * ScalarConstantVals, unsigned Size)
Create a ConstantVector from values.
See also
llvm::ConstantVector::get()
Definition at line 1426 of file Core.cpp.
References llvm::ConstantVector::get(), llvm::makeArrayRef(), Size, and llvm::wrap().
LLVMGetAsString()
const char * LLVMGetAsString (LLVMValueRef c, size_t * Length)
Get the given constant data sequential as a string.
See also
ConstantDataSequential::getAsString()
Definition at line 1391 of file Core.cpp.
References C, llvm::StringRef::data(), and llvm::StringRef::size().
LLVMGetElementAsConstant()
LLVMValueRef LLVMGetElementAsConstant (LLVMValueRef C, unsigned idx)
Get an element at specified index as a constant.
See also
ConstantDataSequential::getElementAsConstant()
Definition at line 1383 of file Core.cpp.
References C, and llvm::wrap().
LLVMIsConstantString()
LLVMBool LLVMIsConstantString (LLVMValueRef c)
Returns true if the specified constant is an array of i8.
See also
ConstantDataSequential::getAsString()
Definition at line 1387 of file Core.cpp.
References C.