LLVM: Bit Reader
Bit Reader
LLVM-C: C interface to LLVM
Functions
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMParseBitcode2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule)
LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMParseBitcodeInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule)
LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVMBool LLVMGetBitcodeModuleInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
LLVMBool LLVMGetBitcodeModule2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM)
Detailed Description
Function Documentation
LLVMGetBitcodeModule()
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Definition at line 124 of file BitReader.cpp.
References LLVMGetBitcodeModuleInContext(), and LLVMGetGlobalContext().
LLVMGetBitcodeModule2()
LLVMBool LLVMGetBitcodeModule2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM)
Definition at line 130 of file BitReader.cpp.
References LLVMGetBitcodeModuleInContext2(), and LLVMGetGlobalContext().
LLVMGetBitcodeModuleInContext()
LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
Returns 0 on success. Optionally returns a human-readable error message via OutMessage. This is deprecated. Use LLVMGetBitcodeModuleInContext2.
Definition at line 78 of file BitReader.cpp.
References llvm::Expected< T >::get(), llvm::getOwningLazyBitcodeModule(), llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), llvm::Expected< T >::takeError(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule().
LLVMGetBitcodeModuleInContext2()
LLVMBool LLVMGetBitcodeModuleInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
Returns 0 on success.
Definition at line 105 of file BitReader.cpp.
References llvm::expectedToErrorOrAndEmitErrors(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::getOwningLazyBitcodeModule(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule2().
LLVMParseBitcode()
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 24 of file BitReader.cpp.
References LLVMGetGlobalContext(), and LLVMParseBitcodeInContext().
LLVMParseBitcode2()
LLVMBool LLVMParseBitcode2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule)
Definition at line 30 of file BitReader.cpp.
References LLVMGetGlobalContext(), and LLVMParseBitcodeInContext2().
LLVMParseBitcodeInContext()
LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 35 of file BitReader.cpp.
References llvm::Expected< T >::get(), llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), llvm::parseBitcodeFile(), llvm::Expected< T >::takeError(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMParseBitcode().
LLVMParseBitcodeInContext2()
LLVMBool LLVMParseBitcodeInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule)
Definition at line 58 of file BitReader.cpp.
References llvm::expectedToErrorOrAndEmitErrors(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::parseBitcodeFile(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMParseBitcode2().