LLVM: lib/Transforms/Scalar/GuardWidening.cpp File Reference
GuardWidening.cpp File Reference
#include "llvm/Transforms/Scalar/GuardWidening.h"
#include <functional>
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/GuardUtils.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "guard-widening"
Functions
STATISTIC (GuardsEliminated, "Number of eliminated guards")
STATISTIC (CondBranchEliminated, "Number of eliminated conditional branches")
static bool isSupportedGuardInstruction (const Instruction *Insn)
INITIALIZE_PASS_BEGIN (GuardWideningLegacyPass, "guard-widening", "Widen guards", false, false) if(WidenFrequentBranches) INITIALIZE_PASS_END(GuardWideningLegacyPass
guard Widen false INITIALIZE_PASS_BEGIN (LoopGuardWideningLegacyPass, "loop-guard-widening", "Widen guards (within a single loop, as a loop pass)", false, false) if(WidenFrequentBranches) INITIALIZE_PASS_END(LoopGuardWideningLegacyPass
guard Widen false loop guard Widen guards (within a single loop, as a loop pass)"
Variables
static cl::opt< bool > WidenFrequentBranches ("guard-widening-widen-frequent-branches", cl::Hidden, cl::desc("Widen conditions of explicit branches into dominating guards in " "case if their taken frequency exceeds threshold set by " "guard-widening-frequent-branch-threshold option"), cl::init(false))
static cl::opt< unsigned > FrequentBranchThreshold ("guard-widening-frequent-branch-threshold", cl::Hidden, cl::desc("When WidenFrequentBranches is set to true, this option is used " "to determine which branches are frequently taken. The criteria " "that a branch is taken more often than " "((FrequentBranchThreshold - 1) / FrequentBranchThreshold), then " "it is considered frequently taken"), cl::init(1000))
static cl::opt< bool > WidenBranchGuards ("guard-widening-widen-branch-guards", cl::Hidden, cl::desc("Whether or not we should widen guards " "expressed as branches by widenable conditions"), cl::init(true))
guard widening
guard Widen guards
guard Widen false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "guard-widening"
Definition at line 64 of file GuardWidening.cpp.
Function Documentation
guards()
guard Widen false loop guard Widen guards (within a single loop, as a loop pass)
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (GuardWideningLegacyPass , "guard-widening" , "Widen guards" , false , false)
INITIALIZE_PASS_BEGIN() [2/2]
guard Widen false INITIALIZE_PASS_BEGIN (LoopGuardWideningLegacyPass , "loop-guard-widening" , "Widen guards (within a single loop, as a loop pass)" , false , false)
isSupportedGuardInstruction()
static bool isSupportedGuardInstruction (const Instruction * Insn) static
Definition at line 301 of file GuardWidening.cpp.
References llvm::isGuard(), llvm::isGuardAsWidenableBranch(), and WidenBranchGuards.
STATISTIC() [1/2]
STATISTIC (CondBranchEliminated , "Number of eliminated conditional branches")
STATISTIC() [2/2]
STATISTIC (GuardsEliminated , "Number of eliminated guards")
Variable Documentation
false
guard Widen false loop guard Widen false
Definition at line 926 of file GuardWidening.cpp.
FrequentBranchThreshold
cl::opt< unsigned > FrequentBranchThreshold("guard-widening-frequent-branch-threshold", cl::Hidden, cl::desc("When WidenFrequentBranches is set to true, this option is used " "to determine which branches are frequently taken. The criteria " "that a branch is taken more often than " "((FrequentBranchThreshold - 1) / FrequentBranchThreshold), then " "it is considered frequently taken"), cl::init(1000)) ("guard-widening-frequent-branch-threshold" , cl::Hidden , cl::desc("When WidenFrequentBranches is set to true, this option is used " "to determine which branches are frequently taken. The criteria " "that a branch is taken more often than " "((FrequentBranchThreshold - 1) / FrequentBranchThreshold), then " "it is considered frequently taken") , cl::init(1000)) static
guards
guard Widen guards
Definition at line 925 of file GuardWidening.cpp.
WidenBranchGuards
cl::opt< bool > WidenBranchGuards("guard-widening-widen-branch-guards", cl::Hidden, cl::desc("Whether or not we should widen guards " "expressed as branches by widenable conditions"), cl::init(true)) ("guard-widening-widen-branch-guards" , cl::Hidden , cl::desc("Whether or not we should widen guards " "expressed as branches by widenable conditions") , cl::init(true)) static
Referenced by isSupportedGuardInstruction().
WidenFrequentBranches
cl::opt< bool > WidenFrequentBranches("guard-widening-widen-frequent-branches", cl::Hidden, cl::desc("Widen conditions of explicit branches into dominating guards in " "case if their taken frequency exceeds threshold set by " "guard-widening-frequent-branch-threshold option"), cl::init(false)) ("guard-widening-widen-frequent-branches" , cl::Hidden , cl::desc("Widen conditions of explicit branches into dominating guards in " "case if their taken frequency exceeds threshold set by " "guard-widening-frequent-branch-threshold option") , cl::init(false)) static
Referenced by llvm::GuardWideningPass::run().
widening
guard Widen false loop guard widening
Definition at line 925 of file GuardWidening.cpp.