LLVM: lib/Target/Hexagon/HexagonPeephole.cpp File Reference
HexagonPeephole.cpp File Reference
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/PassSupport.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "hexagon-peephole"
Functions
FunctionPass * llvm::createHexagonPeephole ()
void llvm::initializeHexagonPeepholePass (PassRegistry &)
INITIALIZE_PASS (HexagonPeephole, "hexagon-peephole", "Hexagon Peephole", false, false) bool HexagonPeephole
Variables
static cl::opt< bool > DisableHexagonPeephole ("disable-hexagon-peephole", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Peephole Optimization"))
static cl::opt< bool > DisablePNotP ("disable-hexagon-pnotp", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of PNotP"))
static cl::opt< bool > DisableOptSZExt ("disable-hexagon-optszext", cl::Hidden, cl::ZeroOrMore, cl::init(true), cl::desc("Disable Optimization of Sign/Zero Extends"))
static cl::opt< bool > DisableOptExtTo64 ("disable-hexagon-opt-ext-to-64", cl::Hidden, cl::ZeroOrMore, cl::init(true), cl::desc("Disable Optimization of extensions to i64."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-peephole"
Definition at line 57 of file HexagonPeephole.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (HexagonPeephole , "hexagon-peephole" , "Hexagon Peephole" , false , false)
Definition at line 106 of file HexagonPeephole.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::MachineOperand::CreateReg(), DisableHexagonPeephole, DisableOptExtTo64, DisableOptSZExt, DisablePNotP, E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::TargetRegisterClass::getID(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), I, llvm::TargetRegisterInfo::isVirtualRegister(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), MI, and MRI.
Variable Documentation
DisableHexagonPeephole
cl::opt< bool > DisableHexagonPeephole("disable-hexagon-peephole", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Peephole Optimization")) ("disable-hexagon-peephole" , cl::Hidden , cl::ZeroOrMore , cl::init(false) , cl::desc("Disable Peephole Optimization")) static
Referenced by INITIALIZE_PASS().
DisableOptExtTo64
cl::opt< bool > DisableOptExtTo64("disable-hexagon-opt-ext-to-64", cl::Hidden, cl::ZeroOrMore, cl::init(true), cl::desc("Disable Optimization of extensions to i64.")) ("disable-hexagon-opt-ext-to-64" , cl::Hidden , cl::ZeroOrMore , cl::init(true) , cl::desc("Disable Optimization of extensions to i64.")) static
Referenced by INITIALIZE_PASS().
DisableOptSZExt
cl::opt< bool > DisableOptSZExt("disable-hexagon-optszext", cl::Hidden, cl::ZeroOrMore, cl::init(true), cl::desc("Disable Optimization of Sign/Zero Extends")) ("disable-hexagon-optszext" , cl::Hidden , cl::ZeroOrMore , cl::init(true) , cl::desc("Disable Optimization of Sign/Zero Extends")) static
Referenced by INITIALIZE_PASS().
DisablePNotP
cl::opt< bool > DisablePNotP("disable-hexagon-pnotp", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of PNotP")) ("disable-hexagon-pnotp" , cl::Hidden , cl::ZeroOrMore , cl::init(false) , cl::desc("Disable Optimization of PNotP")) static
Referenced by INITIALIZE_PASS().