LLVM: lib/Target/Hexagon/HexagonMachineScheduler.cpp File Reference
HexagonMachineScheduler.cpp File Reference
#include "HexagonMachineScheduler.h"
#include "HexagonInstrInfo.h"
#include "HexagonSubtarget.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/DFAPacketizer.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/RegisterPressure.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <iomanip>
#include <limits>
#include <memory>
#include <sstream>
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
static bool hasDependence (const SUnit *SUd, const SUnit *SUu, const HexagonInstrInfo &QII)
Return true if there is a dependence between SUd and SUu.
static bool isSingleUnscheduledPred (SUnit *SU, SUnit *SU2)
isSingleUnscheduledPred - If SU2 is the only unscheduled predecessor of SU, return true (we may have duplicates)
static bool isSingleUnscheduledSucc (SUnit *SU, SUnit *SU2)
isSingleUnscheduledSucc - If SU2 is the only unscheduled successor of SU, return true (we may have duplicates)
Variables
static cl::opt< bool > IgnoreBBRegPressure ("ignore-bb-reg-pressure", cl::Hidden, cl::ZeroOrMore, cl::init(false))
static cl::opt< bool > UseNewerCandidate ("use-newer-candidate", cl::Hidden, cl::ZeroOrMore, cl::init(true))
static cl::opt< unsigned > SchedDebugVerboseLevel ("misched-verbose-level", cl::Hidden, cl::ZeroOrMore, cl::init(1))
static cl::opt< bool > CheckEarlyAvail ("check-early-avail", cl::Hidden, cl::ZeroOrMore, cl::init(true))
static cl::opt< float > RPThreshold ("hexagon-reg-pressure", cl::Hidden, cl::init(0.75f), cl::desc("High register pressure threhold."))
static const unsigned PriorityOne = 200
static const unsigned PriorityTwo = 50
static const unsigned PriorityThree = 75
static const unsigned ScaleTwo = 10
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 45 of file HexagonMachineScheduler.cpp.
Function Documentation
hasDependence()
static bool hasDependence (const SUnit * SUd, const SUnit * SUu, const HexagonInstrInfo & QII) static
Return true if there is a dependence between SUd and SUu.
Definition at line 68 of file HexagonMachineScheduler.cpp.
References llvm::HexagonInstrInfo::canExecuteInBundle(), llvm::SUnit::getInstr(), llvm::HexagonInstrInfo::mayBeCurLoad(), and llvm::SUnit::Succs.
Referenced by llvm::VLIWResourceModel::isResourceAvailable().
isSingleUnscheduledPred()
static bool isSingleUnscheduledPred (SUnit * SU, SUnit * SU2) inline static
isSingleUnscheduledPred - If SU2 is the only unscheduled predecessor of SU, return true (we may have duplicates)
Definition at line 521 of file HexagonMachineScheduler.cpp.
References llvm::SUnit::NumPredsLeft, and llvm::SUnit::Preds.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost().
isSingleUnscheduledSucc()
static bool isSingleUnscheduledSucc (SUnit * SU, SUnit * SU2) inline static
isSingleUnscheduledSucc - If SU2 is the only unscheduled successor of SU, return true (we may have duplicates)
Definition at line 536 of file HexagonMachineScheduler.cpp.
References llvm::SUnit::NumSuccsLeft, and llvm::SUnit::Succs.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost().
Variable Documentation
CheckEarlyAvail
cl::opt< bool > CheckEarlyAvail("check-early-avail", cl::Hidden, cl::ZeroOrMore, cl::init(true)) ("check-early-avail" , cl::Hidden , cl::ZeroOrMore , cl::init(true)) static
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost().
IgnoreBBRegPressure
cl::opt< bool > IgnoreBBRegPressure("ignore-bb-reg-pressure", cl::Hidden, cl::ZeroOrMore, cl::init(false)) ("ignore-bb-reg-pressure" , cl::Hidden , cl::ZeroOrMore , cl::init(false)) static
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost().
PriorityOne
const unsigned PriorityOne = 200 static
Definition at line 569 of file HexagonMachineScheduler.cpp.
PriorityThree
const unsigned PriorityThree = 75 static
Definition at line 571 of file HexagonMachineScheduler.cpp.
PriorityTwo
const unsigned PriorityTwo = 50 static
Definition at line 570 of file HexagonMachineScheduler.cpp.
RPThreshold
cl::opt< float > RPThreshold("hexagon-reg-pressure", cl::Hidden, cl::init(0.75f), cl::desc("High register pressure threhold.")) ("hexagon-reg-pressure" , cl::Hidden , cl::init(0.75f) , cl::desc("High register pressure threhold.")) static
Referenced by llvm::ConvergingVLIWScheduler::initialize().
ScaleTwo
const unsigned ScaleTwo = 10 static
Definition at line 572 of file HexagonMachineScheduler.cpp.
SchedDebugVerboseLevel
cl::opt< unsigned > SchedDebugVerboseLevel("misched-verbose-level", cl::Hidden, cl::ZeroOrMore, cl::init(1)) ("misched-verbose-level" , cl::Hidden , cl::ZeroOrMore , cl::init(1)) static
Referenced by llvm::ConvergingVLIWScheduler::pickNodeFromQueue().
UseNewerCandidate
cl::opt< bool > UseNewerCandidate("use-newer-candidate", cl::Hidden, cl::ZeroOrMore, cl::init(true)) ("use-newer-candidate" , cl::Hidden , cl::ZeroOrMore , cl::init(true)) static
Referenced by llvm::ConvergingVLIWScheduler::pickNodeFromQueue().