LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCTargetDesc.cpp File Reference
HexagonMCTargetDesc.cpp File Reference
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "HexagonDepArch.h"
#include "HexagonTargetStreamer.h"
#include "MCTargetDesc/HexagonInstPrinter.h"
#include "MCTargetDesc/HexagonMCAsmInfo.h"
#include "MCTargetDesc/HexagonMCELFStreamer.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "TargetInfo/HexagonTargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <new>
#include <string>
#include "HexagonGenInstrInfo.inc"
#include "HexagonGenSubtargetInfo.inc"
#include "HexagonGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static StringRef HexagonGetArchVariant ()
static MCRegisterInfo * createHexagonMCRegisterInfo (const Triple &TT)
static MCAsmInfo * createHexagonMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT)
static MCInstPrinter * createHexagonMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createMCAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *IP, bool IsVerboseAsm)
static MCStreamer * createMCStreamer (Triple const &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createHexagonObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static void LLVM_ATTRIBUTE_UNUSED clearFeature (MCSubtargetInfo *STI, uint64_t F)
static bool LLVM_ATTRIBUTE_UNUSED checkFeature (MCSubtargetInfo *STI, uint64_t F)
static bool isCPUValid (std::string CPU)
static MCInstrAnalysis * createHexagonMCInstrAnalysis (const MCInstrInfo *Info)
void LLVMInitializeHexagonTargetMC ()
Variables
cl::opt< Hexagon::ArchEnum > EnableHVX ("mhvx", cl::desc("Enable Hexagon Vector eXtensions"), cl::values(clEnumValN(Hexagon::ArchEnum::V60, "v60", "Build for HVX v60"), clEnumValN(Hexagon::ArchEnum::V62, "v62", "Build for HVX v62"), clEnumValN(Hexagon::ArchEnum::V65, "v65", "Build for HVX v65"), clEnumValN(Hexagon::ArchEnum::V66, "v66", "Build for HVX v66"), clEnumValN(Hexagon::ArchEnum::Generic, "", "")), cl::init(Hexagon::ArchEnum::NoArch), cl::ValueOptional)
static cl::opt< bool > DisableHVX ("mno-hvx", cl::Hidden, cl::desc("Disable Hexagon Vector eXtensions"))
static StringRef DefaultArch = "hexagonv60"
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 45 of file HexagonMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 51 of file HexagonMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 48 of file HexagonMCTargetDesc.cpp.
Function Documentation
checkFeature()
static bool LLVM_ATTRIBUTE_UNUSED checkFeature (MCSubtargetInfo * STI, uint64_t F) static
Definition at line 272 of file HexagonMCTargetDesc.cpp.
References F, and llvm::MCSubtargetInfo::getFeatureBits().
clearFeature()
static void LLVM_ATTRIBUTE_UNUSED clearFeature (MCSubtargetInfo * STI, uint64_t F) static
Definition at line 266 of file HexagonMCTargetDesc.cpp.
References F, llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCSubtargetInfo::ToggleFeature().
createHexagonMCAsmInfo()
static MCAsmInfo * createHexagonMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT) static
Definition at line 221 of file HexagonMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), MRI, and TT.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCInstPrinter()
static MCInstPrinter * createHexagonMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 234 of file HexagonMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCInstrAnalysis()
static MCInstrAnalysis * createHexagonMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 454 of file HexagonMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCRegisterInfo()
static MCRegisterInfo * createHexagonMCRegisterInfo (const Triple & TT) static
Definition at line 215 of file HexagonMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonObjectTargetStreamer()
static MCTargetStreamer * createHexagonObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 262 of file HexagonMCTargetDesc.cpp.
Referenced by LLVMInitializeHexagonTargetMC().
createMCAsmTargetStreamer()
static MCTargetStreamer * createMCAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * IP, bool IsVerboseAsm) static
Definition at line 247 of file HexagonMCTargetDesc.cpp.
Referenced by LLVMInitializeHexagonTargetMC().
createMCStreamer()
static MCStreamer * createMCStreamer (Triple const & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 252 of file HexagonMCTargetDesc.cpp.
References Context, and llvm::createHexagonELFStreamer().
Referenced by LLVMInitializeHexagonTargetMC().
HexagonGetArchVariant()
static StringRef HexagonGetArchVariant () static
Definition at line 97 of file HexagonMCTargetDesc.cpp.
Referenced by llvm::Hexagon_MC::selectHexagonCPU().
isCPUValid()
static bool isCPUValid (std::string CPU) static
Definition at line 315 of file HexagonMCTargetDesc.cpp.
Referenced by llvm::Hexagon_MC::createHexagonMCSubtargetInfo().
LLVMInitializeHexagonTargetMC()
void LLVMInitializeHexagonTargetMC ()
Definition at line 459 of file HexagonMCTargetDesc.cpp.
References llvm::createHexagonAsmBackend(), createHexagonMCAsmInfo(), llvm::createHexagonMCCodeEmitter(), createHexagonMCInstPrinter(), createHexagonMCInstrAnalysis(), llvm::createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createHexagonObjectTargetStreamer(), createMCAsmTargetStreamer(), createMCStreamer(), llvm::getTheHexagonTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.
Variable Documentation
DefaultArch
StringRef DefaultArch = "hexagonv60" static
Definition at line 95 of file HexagonMCTargetDesc.cpp.
Referenced by llvm::Hexagon_MC::selectHexagonCPU().
DisableHVX
cl::opt< bool > DisableHVX("mno-hvx", cl::Hidden, cl::desc("Disable Hexagon Vector eXtensions")) ("mno-hvx" , cl::Hidden , cl::desc("Disable Hexagon Vector eXtensions")) static
EnableHVX
cl::opt< Hexagon::ArchEnum > EnableHVX("mhvx", cl::desc("Enable Hexagon Vector eXtensions"), cl::values(clEnumValN(Hexagon::ArchEnum::V60, "v60", "Build for HVX v60"), clEnumValN(Hexagon::ArchEnum::V62, "v62", "Build for HVX v62"), clEnumValN(Hexagon::ArchEnum::V65, "v65", "Build for HVX v65"), clEnumValN(Hexagon::ArchEnum::V66, "v66", "Build for HVX v66"), clEnumValN(Hexagon::ArchEnum::Generic, "", "")), cl::init(Hexagon::ArchEnum::NoArch), cl::ValueOptional) ("mhvx" , cl::desc("Enable Hexagon Vector eXtensions") , cl::values(clEnumValN(Hexagon::ArchEnum::V60, "v60", "Build for HVX v60"), clEnumValN(Hexagon::ArchEnum::V62, "v62", "Build for HVX v62"), clEnumValN(Hexagon::ArchEnum::V65, "v65", "Build for HVX v65"), clEnumValN(Hexagon::ArchEnum::V66, "v66", "Build for HVX v66"), clEnumValN(Hexagon::ArchEnum::Generic, "", "")) , cl::init(Hexagon::ArchEnum::NoArch) , cl::ValueOptional)