LLVM: lib/AsmParser/LLLexer.cpp File Reference
LLLexer.cpp File Reference
#include "LLLexer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SourceMgr.h"
#include <cassert>
#include <cctype>
#include <cstdio>
Macros
#define KEYWORD(STR)
#define TYPEKEYWORD(STR, LLVMTY)
#define INSTKEYWORD(STR, Enum)
#define DWKEYWORD(TYPE, TOKEN)
Functions
static void UnEscapeLexed (std::string &Str)
static bool isLabelChar (char C)
isLabelChar - Return true for [-a-zA-Z$._0-9].
static const char * isLabelTail (const char *CurPtr)
isLabelTail - Return true if this pointer points to a valid end of a label.
Macro Definition Documentation
DWKEYWORD
#define DWKEYWORD (TYPE, TOKEN)
Value:
  do {                                                                         \
    if (Keyword.startswith("DW_" #TYPE "_")) {                                 \
      StrVal.assign(Keyword.begin(), Keyword.end());                           \
      return lltok::TOKEN;                                                     \
    }                                                                          \
  } while (false)
INSTKEYWORD
#define INSTKEYWORD (STR, Enum)
Value:
  do {                                                                         \
    if (Keyword == #STR) {                                                     \
      UIntVal = Instruction::Enum;                                             \
      return lltok::kw_##STR;                                                  \
    }                                                                          \
  } while (false)
KEYWORD
#define KEYWORD (STR)
Value:
  do {                                                                         \
    if (Keyword == #STR)                                                       \
      return lltok::kw_##STR;                                                  \
  } while (false)
TYPEKEYWORD
#define TYPEKEYWORD (STR, LLVMTY)
Value:
  do {                                                                         \
    if (Keyword == STR) {                                                      \
      TyVal = LLVMTY;                                                          \
      return lltok::Type;                                                      \
    }                                                                          \
  } while (false)
Function Documentation
isLabelChar()
static bool isLabelChar (char C) static
isLabelChar - Return true for [-a-zA-Z$._0-9].
Definition at line 141 of file LLLexer.cpp.
References C.
Referenced by isLabelTail().
isLabelTail()
static const char * isLabelTail (const char * CurPtr) static
isLabelTail - Return true if this pointer points to a valid end of a label.
Definition at line 147 of file LLLexer.cpp.
References isLabelChar().
UnEscapeLexed()
static void UnEscapeLexed (std::string & Str) static
Definition at line 114 of file LLLexer.cpp.
References llvm::hexDigitValue().