LLVM: lib/Transforms/Scalar/LoopVersioningLICM.cpp File Reference
LoopVersioningLICM.cpp File Reference
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AliasSetTracker.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/LoopAccessAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/LoopVersioning.h"
#include <cassert>
#include <memory>
Macros
#define DEBUG_TYPE "loop-versioning-licm"
Functions
static MDNode * createStringMetadata (Loop *TheLoop, StringRef Name, unsigned V)
Create MDNode for input string.
INITIALIZE_PASS_BEGIN (LoopVersioningLICM, "loop-versioning-licm", "Loop Versioning For LICM", false, false) INITIALIZE_PASS_END(LoopVersioningLICM
Variables
static const char * LICMVersioningMetaData = "llvm.loop.licm_versioning.disable"
static cl::opt< float > LVInvarThreshold ("licm-versioning-invariant-threshold", cl::desc("LoopVersioningLICM's minimum allowed percentage" "of possible invariant instructions per loop"), cl::init(25), cl::Hidden)
Threshold minimum allowed percentage for possible invariant instructions in a loop.
static cl::opt< unsigned > LVLoopDepthThreshold ("licm-versioning-max-depth-threshold", cl::desc("LoopVersioningLICM's threshold for maximum allowed loop nest/depth"), cl::init(2), cl::Hidden)
Threshold for maximum allowed loop nest/depth.
loop versioning licm
loop versioning Loop Versioning For LICM
loop versioning Loop Versioning For false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-versioning-licm"
Definition at line 96 of file LoopVersioningLICM.cpp.
Function Documentation
createStringMetadata()
static MDNode * createStringMetadata (Loop * TheLoop, StringRef Name, unsigned V) static
Create MDNode for input string.
Definition at line 116 of file LoopVersioningLICM.cpp.
References Context, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ConstantInt::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Type::getInt32Ty(), and Name.
Referenced by llvm::addStringMetadataToLoop().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopVersioningLICM , "loop-versioning-licm" , "Loop Versioning For LICM" , false , false)
Variable Documentation
false
loop versioning Loop Versioning For false
Definition at line 669 of file LoopVersioningLICM.cpp.
licm
loop versioning licm
Definition at line 668 of file LoopVersioningLICM.cpp.
LICM
loop versioning Loop Versioning For LICM
Definition at line 669 of file LoopVersioningLICM.cpp.
Referenced by llvm::LICMPass::run().
LICMVersioningMetaData
const char* LICMVersioningMetaData = "llvm.loop.licm_versioning.disable" static
Definition at line 98 of file LoopVersioningLICM.cpp.
LVInvarThreshold
cl::opt< float > LVInvarThreshold("licm-versioning-invariant-threshold", cl::desc("LoopVersioningLICM's minimum allowed percentage" "of possible invariant instructions per loop"), cl::init(25), cl::Hidden) ("licm-versioning-invariant-threshold" , cl::desc("LoopVersioningLICM's minimum allowed percentage" "of possible invariant instructions per loop") , cl::init(25) , cl::Hidden) static
Threshold minimum allowed percentage for possible invariant instructions in a loop.
LVLoopDepthThreshold
cl::opt< unsigned > LVLoopDepthThreshold("licm-versioning-max-depth-threshold", cl::desc("LoopVersioningLICM's threshold for maximum allowed loop nest/depth"), cl::init(2), cl::Hidden) ("licm-versioning-max-depth-threshold" , cl::desc("LoopVersioningLICM's threshold for maximum allowed loop nest/depth") , cl::init(2) , cl::Hidden) static
Threshold for maximum allowed loop nest/depth.