LLVM: lib/Transforms/Utils/LowerMemIntrinsics.cpp File Reference
LowerMemIntrinsics.cpp File Reference
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Functions
static unsigned getLoopOperandSizeInBytes (Type *Type)
static void createMemMoveLoop (Instruction *InsertBefore, Value *SrcAddr, Value *DstAddr, Value *CopyLen, unsigned SrcAlign, unsigned DestAlign, bool SrcIsVolatile, bool DstIsVolatile)
static void createMemSetLoop (Instruction *InsertBefore, Value *DstAddr, Value *CopyLen, Value *SetValue, unsigned Align, bool IsVolatile)
Function Documentation
createMemMoveLoop()
static void createMemMoveLoop (Instruction * InsertBefore, Value * SrcAddr, Value * DstAddr, Value * CopyLen, unsigned SrcAlign, unsigned DestAlign, bool SrcIsVolatile, bool DstIsVolatile) static
Definition at line 287 of file LowerMemIntrinsics.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::BasicBlock::Create(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateSub(), llvm::Instruction::eraseFromParent(), F, llvm::ConstantInt::get(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::setName(), and llvm::SplitBlockAndInsertIfThenElse().
Referenced by llvm::expandMemMoveAsLoop().
createMemSetLoop()
static void createMemSetLoop (Instruction * InsertBefore, Value * DstAddr, Value * CopyLen, Value * SetValue, unsigned Align, bool IsVolatile) static
Definition at line 368 of file LowerMemIntrinsics.cpp.
References llvm::PHINode::addIncoming(), llvm::BasicBlock::Create(), llvm::IRBuilder< T, Inserter >::CreateAdd(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpULT(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::Instruction::eraseFromParent(), F, llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantInt::get(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), SetValue(), and llvm::BasicBlock::splitBasicBlock().
Referenced by llvm::expandMemSetAsLoop().
getLoopOperandSizeInBytes()
static unsigned getLoopOperandSizeInBytes (Type * Type) static
Definition at line 17 of file LowerMemIntrinsics.cpp.
References llvm::Type::getPrimitiveSizeInBits().
Referenced by llvm::createMemCpyLoopKnownSize(), and llvm::createMemCpyLoopUnknownSize().