LLVM: lib/Transforms/Instrumentation/MemorySanitizer.cpp File Reference
MemorySanitizer.cpp File Reference
This file is a part of MemorySanitizer, a detector of uninitialized reads.
#include "llvm/Transforms/Instrumentation/MemorySanitizer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueMap.h"
#include "llvm/Pass.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <tuple>
Macros
#define DEBUG_TYPE "msan"
Functions
INITIALIZE_PASS_BEGIN (MemorySanitizerLegacyPass, "msan", "MemorySanitizer: detects uninitialized reads.", false, false) INITIALIZE_PASS_END(MemorySanitizerLegacyPass
static GlobalVariable * createPrivateNonConstGlobalForString (Module &M, StringRef Str)
Create a non-const global initialized with the given string.
static Constant * getOrInsertGlobal (Module &M, StringRef Name, Type *Ty)
static VarArgHelper * CreateVarArgHelper (Function &Func, MemorySanitizer &Msan, MemorySanitizerVisitor &Visitor)
static unsigned TypeSizeToSizeIndex (unsigned TypeSize)
Variables
static const unsigned kOriginSize = 4
static const unsigned kMinOriginAlignment = 4
static const unsigned kShadowTLSAlignment = 8
static const unsigned kParamTLSSize = 800
static const unsigned kRetvalTLSSize = 800
static const size_t kNumberOfAccessSizes = 4
static cl::opt< int > ClTrackOrigins ("msan-track-origins", cl::desc("Track origins (allocation sites) of poisoned memory"), cl::Hidden, cl::init(0))
Track origins of uninitialized values.
static cl::opt< bool > ClKeepGoing ("msan-keep-going", cl::desc("keep going after reporting a UMR"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClPoisonStack ("msan-poison-stack", cl::desc("poison uninitialized stack variables"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClPoisonStackWithCall ("msan-poison-stack-with-call", cl::desc("poison uninitialized stack variables with a call"), cl::Hidden, cl::init(false))
static cl::opt< int > ClPoisonStackPattern ("msan-poison-stack-pattern", cl::desc("poison uninitialized stack variables with the given pattern"), cl::Hidden, cl::init(0xff))
static cl::opt< bool > ClPoisonUndef ("msan-poison-undef", cl::desc("poison undef temps"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClHandleICmp ("msan-handle-icmp", cl::desc("propagate shadow through ICmpEQ and ICmpNE"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClHandleICmpExact ("msan-handle-icmp-exact", cl::desc("exact handling of relational integer ICmp"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClHandleLifetimeIntrinsics ("msan-handle-lifetime-intrinsics", cl::desc("when possible, poison scoped variables at the beginning of the scope " "(slower, but more precise)"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClHandleAsmConservative ("msan-handle-asm-conservative", cl::desc("conservative handling of inline assembly"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClCheckAccessAddress ("msan-check-access-address", cl::desc("report accesses through a pointer which has poisoned shadow"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClDumpStrictInstructions ("msan-dump-strict-instructions", cl::desc("print out instructions with default strict semantics"), cl::Hidden, cl::init(false))
static cl::opt< int > ClInstrumentationWithCallThreshold ("msan-instrumentation-with-call-threshold", cl::desc("If the function being instrumented requires more than " "this number of checks and origin stores, use callbacks instead of " "inline checks (-1 means never use callbacks)."), cl::Hidden, cl::init(3500))
static cl::opt< bool > ClEnableKmsan ("msan-kernel", cl::desc("Enable KernelMemorySanitizer instrumentation"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClCheckConstantShadow ("msan-check-constant-shadow", cl::desc("Insert checks for constant shadow values"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClWithComdat ("msan-with-comdat", cl::desc("Place MSan constructors in comdat sections"), cl::Hidden, cl::init(false))
static cl::opt< uint64_t > ClAndMask ("msan-and-mask", cl::desc("Define custom MSan AndMask"), cl::Hidden, cl::init(0))
static cl::opt< uint64_t > ClXorMask ("msan-xor-mask", cl::desc("Define custom MSan XorMask"), cl::Hidden, cl::init(0))
static cl::opt< uint64_t > ClShadowBase ("msan-shadow-base", cl::desc("Define custom MSan ShadowBase"), cl::Hidden, cl::init(0))
static cl::opt< uint64_t > ClOriginBase ("msan-origin-base", cl::desc("Define custom MSan OriginBase"), cl::Hidden, cl::init(0))
static const char *const kMsanModuleCtorName = "msan.module_ctor"
static const char *const kMsanInitName = "__msan_init"
static const MemoryMapParams Linux_I386_MemoryMapParams
static const MemoryMapParams Linux_X86_64_MemoryMapParams
static const MemoryMapParams Linux_MIPS64_MemoryMapParams
static const MemoryMapParams Linux_PowerPC64_MemoryMapParams
static const MemoryMapParams Linux_AArch64_MemoryMapParams
static const MemoryMapParams FreeBSD_I386_MemoryMapParams
static const MemoryMapParams FreeBSD_X86_64_MemoryMapParams
static const MemoryMapParams NetBSD_X86_64_MemoryMapParams
static const PlatformMemoryMapParams Linux_X86_MemoryMapParams
static const PlatformMemoryMapParams Linux_MIPS_MemoryMapParams
static const PlatformMemoryMapParams Linux_PowerPC_MemoryMapParams
static const PlatformMemoryMapParams Linux_ARM_MemoryMapParams
static const PlatformMemoryMapParams FreeBSD_X86_MemoryMapParams
static const PlatformMemoryMapParams NetBSD_X86_MemoryMapParams
msan
MemorySanitizer __pad0__
MemorySanitizer false
Detailed Description
This file is a part of MemorySanitizer, a detector of uninitialized reads.
The algorithm of the tool is similar to Memcheck (http://goo.gl/QKbem). We associate a few shadow bits with every byte of the application memory, poison the shadow of the malloc-ed or alloca-ed memory, load the shadow bits on every memory read, propagate the shadow bits through some of the arithmetic instruction (including MOV), store the shadow bits on every memory write, report a bug on some other instructions (e.g. JMP) if the associated shadow is poisoned.
But there are differences too. The first and the major one: compiler instrumentation instead of binary instrumentation. This gives us much better register allocation, possible compiler optimizations and a fast start-up. But this brings the major issue as well: msan needs to see all program events, including system calls and reads/writes in system libraries, so we either need to compile everything with msan or use a binary translation component (e.g. DynamoRIO) to instrument pre-built libraries. Another difference from Memcheck is that we use 8 shadow bits per byte of application memory and use a direct shadow mapping. This greatly simplifies the instrumentation code and avoids races on shadow updates (Memcheck is single-threaded so races are not a concern there. Memcheck uses 2 shadow bits per byte with a slow path storage that uses 8 bits per byte).
The default value of shadow is 0, which means "clean" (not poisoned).
Every module initializer should call __msan_init to ensure that the shadow memory is ready. On error, __msan_warning is called. Since parameters and return values may be passed via registers, we have a specialized thread-local shadow for return values (__msan_retval_tls) and parameters (__msan_param_tls).
                      Origin tracking.
MemorySanitizer can track origins (allocation points) of all uninitialized values. This behavior is controlled with a flag (msan-track-origins) and is disabled by default.
Origins are 4-byte values created and interpreted by the runtime library. They are stored in a second shadow mapping, one 4-byte value for 4 bytes of application memory. Propagation of origins is basically a bunch of "select" instructions that pick the origin of a dirty argument, if an instruction has one.
Every 4 aligned, consecutive bytes of application memory have one origin value associated with them. If these bytes contain uninitialized data coming from 2 different allocations, the last store wins. Because of this, MemorySanitizer reports can show unrelated origins, but this is unlikely in practice.
Origins are meaningless for fully initialized values, so MemorySanitizer avoids storing origin to memory when a fully initialized value is stored. This way it avoids needless overwritting origin of the 4-byte region on a short (i.e. 1 byte) clean store, and it is also good for performance.
                       Atomic handling.
Ideally, every atomic store of application value should update the corresponding shadow location in an atomic way. Unfortunately, atomic store of two disjoint locations can not be done without severe slowdown.
Therefore, we implement an approximation that may err on the safe side. In this implementation, every atomically accessed location in the program may only change from (partially) uninitialized to fully initialized, but not the other way around. We load the shadow after the application load, and we store the shadow before the app store. Also, we always store clean shadow (if the application store is atomic). This way, if the store-load pair constitutes a happens-before arc, shadow store and load are correctly ordered such that the load will get either the value that was stored, or some later value (which is always clean).
This does not work very well with Compare-And-Swap (CAS) and Read-Modify-Write (RMW) operations. To follow the above logic, CAS and RMW must store the new shadow before the app operation, and load the shadow after the app operation. Computers don't work this way. Current implementation ignores the load aspect of CAS/RMW, always returning a clean value. It implements the store part as a simple atomic store by storing a clean shadow.
                 Instrumenting inline assembly.
For inline assembly code LLVM has little idea about which memory locations become initialized depending on the arguments. It can be possible to figure out which arguments are meant to point to inputs and outputs, but the actual semantics can be only visible at runtime. In the Linux kernel it's also possible that the arguments only indicate the offset for a base taken from a segment register, so it's dangerous to treat any asm() arguments as pointers. We take a conservative approach generating calls to __msan_instrument_asm_store(ptr, size) , which defer the memory unpoisoning to the runtime library. The latter can perform more complex address checks to figure out whether it's safe to touch the shadow memory. Like with atomic operations, we call __msan_instrument_asm_store() before the assembly call, so that changes to the shadow memory will be seen by other threads together with main memory initialization.
             KernelMemorySanitizer (KMSAN) implementation.
The major differences between KMSAN and MSan instrumentation are:
KMSAN always tracks the origins and implies msan-keep-going=true;
KMSAN allocates shadow and origin memory for each page separately, so there are no explicit accesses to shadow and origin in the instrumentation. Shadow and origin values for a particular X-byte memory location (X=1,2,4,8) are accessed through pointers obtained via the __msan_metadata_ptr_for_load_X(ptr) __msan_metadata_ptr_for_store_X(ptr) functions. The corresponding functions check that the X-byte accesses are possible and returns the pointers to shadow and origin memory. Arbitrary sized accesses are handled with: __msan_metadata_ptr_for_load_n(ptr, size) __msan_metadata_ptr_for_store_n(ptr, size);
TLS variables are stored in a single per-task struct. A call to a function __msan_get_context_state() returning a pointer to that struct is inserted into every instrumented function before the entry block;
__msan_warning() takes a 32-bit origin parameter;
local variables are poisoned with __msan_poison_alloca() upon function entry and unpoisoned with __msan_unpoison_alloca() before leaving the function;
the pass doesn't declare any global variables or add global constructors to the translation unit.
Also, KMSAN currently ignores uninitialized memory passed into inline asm calls, making sure we're on the safe side wrt. possible false positives.
KernelMemorySanitizer only supports X86_64 at the moment.
Definition in file MemorySanitizer.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "msan"
Definition at line 202 of file MemorySanitizer.cpp.
Function Documentation
createPrivateNonConstGlobalForString()
static GlobalVariable * createPrivateNonConstGlobalForString (Module & M, StringRef Str) static
Create a non-const global initialized with the given string.
Creates a writable global for Str so that we can pass it to the run-time lib. Runtime uses first 4 bytes of the string to store the frame ID, so the string needs to be mutable.
Definition at line 656 of file MemorySanitizer.cpp.
References llvm::msgpack::DocNode::getString(), llvm::Value::getType(), and llvm::GlobalValue::PrivateLinkage.
CreateVarArgHelper()
static VarArgHelper * CreateVarArgHelper (Function & Func, MemorySanitizer & Msan, MemorySanitizerVisitor & Visitor) static
Definition at line 4551 of file MemorySanitizer.cpp.
References llvm::Triple::aarch64, llvm::Triple::getArch(), llvm::Triple::isMIPS64(), llvm::Triple::ppc64, llvm::Triple::ppc64le, and llvm::Triple::x86_64.
getOrInsertGlobal()
static Constant * getOrInsertGlobal (Module & M, StringRef Name, Type * Ty) static
Definition at line 722 of file MemorySanitizer.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::InitialExecTLSModel, and Name.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (MemorySanitizerLegacyPass , "msan" , "MemorySanitizer: detects uninitialized reads." , false , false)
TypeSizeToSizeIndex()
static unsigned TypeSizeToSizeIndex (unsigned TypeSize) static
Definition at line 995 of file MemorySanitizer.cpp.
References llvm::Log2_32_Ceil().
Variable Documentation
__pad0__
MemorySanitizer __pad0__
Definition at line 643 of file MemorySanitizer.cpp.
ClAndMask
cl::opt< uint64_t > ClAndMask("msan-and-mask", cl::desc("Define custom MSan AndMask"), cl::Hidden, cl::init(0)) ("msan-and-mask" , cl::desc("Define custom MSan AndMask") , cl::Hidden , cl::init(0)) static
ClCheckAccessAddress
cl::opt< bool > ClCheckAccessAddress("msan-check-access-address", cl::desc("report accesses through a pointer which has poisoned shadow"), cl::Hidden, cl::init(true)) ("msan-check-access-address" , cl::desc("report accesses through a pointer which has poisoned shadow") , cl::Hidden , cl::init(true)) static
ClCheckConstantShadow
cl::opt< bool > ClCheckConstantShadow("msan-check-constant-shadow", cl::desc("Insert checks for constant shadow values"), cl::Hidden, cl::init(false)) ("msan-check-constant-shadow" , cl::desc("Insert checks for constant shadow values") , cl::Hidden , cl::init(false)) static
ClDumpStrictInstructions
cl::opt< bool > ClDumpStrictInstructions("msan-dump-strict-instructions", cl::desc("print out instructions with default strict semantics"), cl::Hidden, cl::init(false)) ("msan-dump-strict-instructions" , cl::desc("print out instructions with default strict semantics") , cl::Hidden , cl::init(false)) static
ClEnableKmsan
cl::opt< bool > ClEnableKmsan("msan-kernel", cl::desc("Enable KernelMemorySanitizer instrumentation"), cl::Hidden, cl::init(false)) ("msan-kernel" , cl::desc("Enable KernelMemorySanitizer instrumentation") , cl::Hidden , cl::init(false)) static
ClHandleAsmConservative
cl::opt< bool > ClHandleAsmConservative("msan-handle-asm-conservative", cl::desc("conservative handling of inline assembly"), cl::Hidden, cl::init(true)) ("msan-handle-asm-conservative" , cl::desc("conservative handling of inline assembly") , cl::Hidden , cl::init(true)) static
ClHandleICmp
cl::opt< bool > ClHandleICmp("msan-handle-icmp", cl::desc("propagate shadow through ICmpEQ and ICmpNE"), cl::Hidden, cl::init(true)) ("msan-handle-icmp" , cl::desc("propagate shadow through ICmpEQ and ICmpNE") , cl::Hidden , cl::init(true)) static
ClHandleICmpExact
cl::opt< bool > ClHandleICmpExact("msan-handle-icmp-exact", cl::desc("exact handling of relational integer ICmp"), cl::Hidden, cl::init(false)) ("msan-handle-icmp-exact" , cl::desc("exact handling of relational integer ICmp") , cl::Hidden , cl::init(false)) static
ClHandleLifetimeIntrinsics
cl::opt< bool > ClHandleLifetimeIntrinsics("msan-handle-lifetime-intrinsics", cl::desc("when possible, poison scoped variables at the beginning of the scope " "(slower, but more precise)"), cl::Hidden, cl::init(true)) ("msan-handle-lifetime-intrinsics" , cl::desc("when possible, poison scoped variables at the beginning of the scope " "(slower, but more precise)") , cl::Hidden , cl::init(true)) static
ClInstrumentationWithCallThreshold
cl::opt< int > ClInstrumentationWithCallThreshold("msan-instrumentation-with-call-threshold", cl::desc("If the function being instrumented requires more than " "this number of checks and origin stores, use callbacks instead of " "inline checks (-1 means never use callbacks)."), cl::Hidden, cl::init(3500)) ("msan-instrumentation-with-call-threshold" , cl::desc("If the function being instrumented requires more than " "this number of checks and origin stores, use callbacks instead of " "inline checks (-1 means never use callbacks).") , cl::Hidden , cl::init(3500)) static
ClKeepGoing
cl::opt< bool > ClKeepGoing("msan-keep-going", cl::desc("keep going after reporting a UMR"), cl::Hidden, cl::init(false)) ("msan-keep-going" , cl::desc("keep going after reporting a UMR") , cl::Hidden , cl::init(false)) static
ClOriginBase
cl::opt< uint64_t > ClOriginBase("msan-origin-base", cl::desc("Define custom MSan OriginBase"), cl::Hidden, cl::init(0)) ("msan-origin-base" , cl::desc("Define custom MSan OriginBase") , cl::Hidden , cl::init(0)) static
ClPoisonStack
cl::opt< bool > ClPoisonStack("msan-poison-stack", cl::desc("poison uninitialized stack variables"), cl::Hidden, cl::init(true)) ("msan-poison-stack" , cl::desc("poison uninitialized stack variables") , cl::Hidden , cl::init(true)) static
ClPoisonStackPattern
cl::opt< int > ClPoisonStackPattern("msan-poison-stack-pattern", cl::desc("poison uninitialized stack variables with the given pattern"), cl::Hidden, cl::init(0xff)) ("msan-poison-stack-pattern" , cl::desc("poison uninitialized stack variables with the given pattern") , cl::Hidden , cl::init(0xff)) static
ClPoisonStackWithCall
cl::opt< bool > ClPoisonStackWithCall("msan-poison-stack-with-call", cl::desc("poison uninitialized stack variables with a call"), cl::Hidden, cl::init(false)) ("msan-poison-stack-with-call" , cl::desc("poison uninitialized stack variables with a call") , cl::Hidden , cl::init(false)) static
ClPoisonUndef
cl::opt< bool > ClPoisonUndef("msan-poison-undef", cl::desc("poison undef temps"), cl::Hidden, cl::init(true)) ("msan-poison-undef" , cl::desc("poison undef temps") , cl::Hidden , cl::init(true)) static
ClShadowBase
cl::opt< uint64_t > ClShadowBase("msan-shadow-base", cl::desc("Define custom MSan ShadowBase"), cl::Hidden, cl::init(0)) ("msan-shadow-base" , cl::desc("Define custom MSan ShadowBase") , cl::Hidden , cl::init(0)) static
ClTrackOrigins
cl::opt< int > ClTrackOrigins("msan-track-origins", cl::desc("Track origins (allocation sites) of poisoned memory"), cl::Hidden, cl::init(0)) ("msan-track-origins" , cl::desc("Track origins (allocation sites) of poisoned memory") , cl::Hidden , cl::init(0)) static
Track origins of uninitialized values.
Adds a section to MemorySanitizer report that points to the allocation (stack or heap) the uninitialized bits came from originally.
ClWithComdat
cl::opt< bool > ClWithComdat("msan-with-comdat", cl::desc("Place MSan constructors in comdat sections"), cl::Hidden, cl::init(false)) ("msan-with-comdat" , cl::desc("Place MSan constructors in comdat sections") , cl::Hidden , cl::init(false)) static
ClXorMask
cl::opt< uint64_t > ClXorMask("msan-xor-mask", cl::desc("Define custom MSan XorMask"), cl::Hidden, cl::init(0)) ("msan-xor-mask" , cl::desc("Define custom MSan XorMask") , cl::Hidden , cl::init(0)) static
false
MemorySanitizer false
Definition at line 643 of file MemorySanitizer.cpp.
FreeBSD_I386_MemoryMapParams
const MemoryMapParams FreeBSD_I386_MemoryMapParams static
Initial value:
= {
  0x000180000000,
  0x000040000000,
  0x000020000000,
  0x000700000000,
}
Definition at line 402 of file MemorySanitizer.cpp.
FreeBSD_X86_64_MemoryMapParams
const MemoryMapParams FreeBSD_X86_64_MemoryMapParams static
Initial value:
= {
  0xc00000000000,
  0x200000000000,
  0x100000000000,
  0x380000000000,
}
Definition at line 410 of file MemorySanitizer.cpp.
FreeBSD_X86_MemoryMapParams
const PlatformMemoryMapParams FreeBSD_X86_MemoryMapParams static
Initial value:
= {
  &FreeBSD_I386_MemoryMapParams,
  &FreeBSD_X86_64_MemoryMapParams,
}
Definition at line 445 of file MemorySanitizer.cpp.
kMinOriginAlignment
const unsigned kMinOriginAlignment = 4 static
Definition at line 205 of file MemorySanitizer.cpp.
kMsanInitName
const char* const kMsanInitName = "__msan_init" static
Definition at line 332 of file MemorySanitizer.cpp.
kMsanModuleCtorName
const char* const kMsanModuleCtorName = "msan.module_ctor" static
Definition at line 331 of file MemorySanitizer.cpp.
kNumberOfAccessSizes
const size_t kNumberOfAccessSizes = 4 static
Definition at line 213 of file MemorySanitizer.cpp.
kOriginSize
const unsigned kOriginSize = 4 static
Definition at line 204 of file MemorySanitizer.cpp.
kParamTLSSize
const unsigned kParamTLSSize = 800 static
Definition at line 209 of file MemorySanitizer.cpp.
kRetvalTLSSize
const unsigned kRetvalTLSSize = 800 static
Definition at line 210 of file MemorySanitizer.cpp.
kShadowTLSAlignment
const unsigned kShadowTLSAlignment = 8 static
Definition at line 206 of file MemorySanitizer.cpp.
Linux_AArch64_MemoryMapParams
const MemoryMapParams Linux_AArch64_MemoryMapParams static
Initial value:
= {
  0,
  0x06000000000,
  0,
  0x01000000000,
}
Definition at line 394 of file MemorySanitizer.cpp.
Linux_ARM_MemoryMapParams
const PlatformMemoryMapParams Linux_ARM_MemoryMapParams static
Initial value:
= {
  nullptr,
  &Linux_AArch64_MemoryMapParams,
}
Definition at line 440 of file MemorySanitizer.cpp.
Linux_I386_MemoryMapParams
const MemoryMapParams Linux_I386_MemoryMapParams static
Initial value:
= {
  0x000080000000,
  0,
  0,
  0x000040000000,
}
Definition at line 355 of file MemorySanitizer.cpp.
Linux_MIPS64_MemoryMapParams
const MemoryMapParams Linux_MIPS64_MemoryMapParams static
Initial value:
= {
  0,
  0x008000000000,
  0,
  0x002000000000,
}
Definition at line 378 of file MemorySanitizer.cpp.
Linux_MIPS_MemoryMapParams
const PlatformMemoryMapParams Linux_MIPS_MemoryMapParams static
Initial value:
= {
  nullptr,
  &Linux_MIPS64_MemoryMapParams,
}
Definition at line 430 of file MemorySanitizer.cpp.
Linux_PowerPC64_MemoryMapParams
const MemoryMapParams Linux_PowerPC64_MemoryMapParams static
Initial value:
= {
  0xE00000000000,
  0x100000000000,
  0x080000000000,
  0x1C0000000000,
}
Definition at line 386 of file MemorySanitizer.cpp.
Linux_PowerPC_MemoryMapParams
const PlatformMemoryMapParams Linux_PowerPC_MemoryMapParams static
Initial value:
= {
  nullptr,
  &Linux_PowerPC64_MemoryMapParams,
}
Definition at line 435 of file MemorySanitizer.cpp.
Linux_X86_64_MemoryMapParams
const MemoryMapParams Linux_X86_64_MemoryMapParams static
Initial value:
= {
  0,
  0x500000000000,
  0,
  0x100000000000,
}
Definition at line 363 of file MemorySanitizer.cpp.
Linux_X86_MemoryMapParams
const PlatformMemoryMapParams Linux_X86_MemoryMapParams static
Initial value:
= {
  &Linux_I386_MemoryMapParams,
  &Linux_X86_64_MemoryMapParams,
}
Definition at line 425 of file MemorySanitizer.cpp.
msan
msan
Definition at line 642 of file MemorySanitizer.cpp.
NetBSD_X86_64_MemoryMapParams
const MemoryMapParams NetBSD_X86_64_MemoryMapParams static
Initial value:
= {
  0,
  0x500000000000,
  0,
  0x100000000000,
}
Definition at line 418 of file MemorySanitizer.cpp.
NetBSD_X86_MemoryMapParams
const PlatformMemoryMapParams NetBSD_X86_MemoryMapParams static
Initial value:
= {
  nullptr,
  &NetBSD_X86_64_MemoryMapParams,
}
Definition at line 450 of file MemorySanitizer.cpp.