LLVM: lib/DebugInfo/CodeView/MergingTypeTableBuilder.cpp File Reference
MergingTypeTableBuilder.cpp File Reference
#include "llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
Functions
static ArrayRef< uint8_t > stabilize (BumpPtrAllocator &Alloc, ArrayRef< uint8_t > Data)
Function Documentation
stabilize()
static ArrayRef< uint8_t > stabilize (BumpPtrAllocator & Alloc, ArrayRef< uint8_t > Data) inline static
Definition at line 83 of file MergingTypeTableBuilder.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::Data, and llvm::makeArrayRef().
Referenced by llvm::codeview::MergingTypeTableBuilder::insertRecordAs().