LLVM: llvm::RISCVFPRndMode Namespace Reference
llvm::RISCVFPRndMode Namespace Reference
Enumerations
enum RoundingMode {
RNE = 0 , RTZ = 1 , RDN = 2 , RUP = 3 ,
RMM = 4 , DYN = 7 , Invalid
}
Functions
static StringRef roundingModeToString (RoundingMode RndMode)
static RoundingMode stringToRoundingMode (StringRef Str)
static bool isValidRoundingMode (unsigned Mode)
Enumeration Type Documentation
RoundingMode
enum llvm::RISCVFPRndMode::RoundingMode
Enumerator
RNE
RTZ
RDN
RUP
RMM
DYN
Invalid
Definition at line 78 of file RISCVBaseInfo.h.
Function Documentation
isValidRoundingMode()
static bool llvm::RISCVFPRndMode::isValidRoundingMode (unsigned Mode) inline static
Definition at line 118 of file RISCVBaseInfo.h.
References DYN, Mode, RDN, RMM, RNE, RTZ, and RUP.
Referenced by decodeFRMArg().
roundingModeToString()
static StringRef llvm::RISCVFPRndMode::roundingModeToString (RoundingMode RndMode) inline static
Definition at line 88 of file RISCVBaseInfo.h.
References DYN, llvm_unreachable, RDN, RMM, RNE, RTZ, and RUP.
Referenced by llvm::RISCVInstPrinter::printFRMArg().
stringToRoundingMode()
static RoundingMode llvm::RISCVFPRndMode::stringToRoundingMode (StringRef Str) inline static
Definition at line 107 of file RISCVBaseInfo.h.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), DYN, Invalid, RDN, RMM, RNE, RTZ, and RUP.