LLVM: llvm::APIntOps Namespace Reference
llvm::APIntOps Namespace Reference
Functions
const APInt & smin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be signed.
const APInt & smax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be signed.
const APInt & umin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be signed.
const APInt & umax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be unsigned.
APInt GreatestCommonDivisor (APInt A, APInt B)
Compute GCD of two unsigned APInt values.
double RoundAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
double RoundSignedAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
float RoundAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float vlalue.
float RoundSignedAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float value.
APInt RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
APInt RoundFloatToAPInt (float Float, unsigned width)
Converts a float value into a APInt.
APInt RoundingUDiv (const APInt &A, const APInt &B, APInt::Rounding RM)
Return A unsign-divided by B, rounded by the given rounding mode.
APInt RoundingSDiv (const APInt &A, const APInt &B, APInt::Rounding RM)
Return A sign-divided by B, rounded by the given rounding mode.
Optional< APInt > SolveQuadraticEquationWrap (APInt A, APInt B, APInt C, unsigned RangeWidth)
Let q(n) = An^2 + Bn + C, and BW = bit width of the value range (e.g.
Function Documentation
GreatestCommonDivisor()
APInt llvm::APIntOps::GreatestCommonDivisor (APInt A, APInt B)
Compute GCD of two unsigned APInt values.
This function returns the greatest common divisor of the two APInt values using Stein's algorithm.
Returns
the greatest common divisor of A and B.
Definition at line 674 of file APInt.cpp.
References A, and B.
Referenced by gcd().
RoundAPIntToDouble()
double llvm::APIntOps::RoundAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as an unsigned value for conversion purposes.
Definition at line 2134 of file APInt.h.
References llvm::APInt::roundToDouble().
Referenced by RoundAPIntToFloat().
RoundAPIntToFloat()
float llvm::APIntOps::RoundAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float vlalue.
Definition at line 2146 of file APInt.h.
References RoundAPIntToDouble().
RoundDoubleToAPInt()
APInt llvm::APIntOps::RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
This function convert a double value to an APInt value.
Definition at line 717 of file APInt.cpp.
References I.
Referenced by llvm::ExecutionEngine::getConstantValue(), and RoundFloatToAPInt().
RoundFloatToAPInt()
APInt llvm::APIntOps::RoundFloatToAPInt (float Float, unsigned width) inline
Converts a float value into a APInt.
Converts a float value into an APInt value.
Definition at line 2165 of file APInt.h.
References RoundDoubleToAPInt().
Referenced by llvm::ExecutionEngine::getConstantValue().
RoundingSDiv()
APInt llvm::APIntOps::RoundingSDiv (const APInt & A, const APInt & B, APInt::Rounding RM)
Return A sign-divided by B, rounded by the given rounding mode.
Definition at line 2718 of file APInt.cpp.
References A, B, llvm::APInt::DOWN, llvm::APInt::isNegative(), llvm_unreachable, llvm::APInt::sdivrem(), llvm::APInt::TOWARD_ZERO, and llvm::APInt::UP.
Referenced by makeExactMulNSWRegion().
RoundingUDiv()
APInt llvm::APIntOps::RoundingUDiv (const APInt & A, const APInt & B, APInt::Rounding RM)
Return A unsign-divided by B, rounded by the given rounding mode.
Definition at line 2700 of file APInt.cpp.
References A, B, llvm::APInt::DOWN, llvm_unreachable, llvm::APInt::TOWARD_ZERO, llvm::APInt::udivrem(), and llvm::APInt::UP.
Referenced by makeExactMulNUWRegion().
RoundSignedAPIntToDouble()
double llvm::APIntOps::RoundSignedAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as a signed value for conversion purposes.
Definition at line 2141 of file APInt.h.
References llvm::APInt::signedRoundToDouble().
RoundSignedAPIntToFloat()
float llvm::APIntOps::RoundSignedAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float value.
Treast the APInt as a signed value for conversion purposes.
Definition at line 2153 of file APInt.h.
References llvm::APInt::signedRoundToDouble().
smax()
const APInt & llvm::APIntOps::smax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be signed.
Definition at line 2109 of file APInt.h.
References A, and B.
Referenced by llvm::ScalarEvolution::getMinMaxExpr(), and llvm::ConstantRange::smax().
smin()
const APInt & llvm::APIntOps::smin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be signed.
Definition at line 2104 of file APInt.h.
References A, and B.
Referenced by llvm::ScalarEvolution::getMinMaxExpr(), and llvm::ConstantRange::smin().
SolveQuadraticEquationWrap()
Optional< APInt > llvm::APIntOps::SolveQuadraticEquationWrap (APInt A, APInt B, APInt C, unsigned RangeWidth)
Let q(n) = An^2 + Bn + C, and BW = bit width of the value range (e.g.
32 for i32). This function finds the smallest number n, such that (a) n >= 0 and q(n) = 0, or (b) n >= 1 and q(n-1) and q(n), when evaluated in the set of all integers, belong to two different intervals [Rk, Rk+R), where R = 2^BW, and k is an integer. The idea here is to find when q(n) "overflows" 2^BW, while at the same time "allowing" subtraction. In unsigned modulo arithmetic a subtraction (treated as addition of negated numbers) would always count as an overflow, but here we want to allow values to decrease and increase as long as they are within the same interval. Specifically, adding of two negative numbers should not cause an overflow (as long as the magnitude does not exceed the bith width). On the other hand, given a positive number, adding a negative number to it can give a negative result, which would cause the value to go from [-2^BW, 0) to [0, 2^BW). In that sense, zero is treated as a special case of an overflow.
This function returns None if after finding k that minimizes the positive solution to q(n) = kR, both solutions are contained between two consecutive integers.
There are cases where q(n) > T, and q(n+1) < T (assuming evaluation in arithmetic modulo 2^BW, and treating the values as signed) by the virtue of signed overflow. This function will not find such an n, however it may find a value of n satisfying the inequalities due to an unsigned overflow (if the values are treated as unsigned). To find a solution for a signed overflow, treat it as a problem of finding an unsigned overflow with a range with of BW-1.
The returned value may have a different bit width from the input coefficients.
Definition at line 2749 of file APInt.cpp.
References A, llvm::APInt::abs(), assert(), B, C, D, llvm::dbgs(), llvm::APInt::getOneBitSet(), llvm::APInt::isNegative(), llvm::APInt::isNullValue(), LLVM_DEBUG, llvm::None, llvm::APInt::sdivrem(), llvm::APInt::sgt(), T, llvm::APInt::udiv(), llvm::APInt::urem(), and X.
Referenced by SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
umax()
const APInt & llvm::APIntOps::umax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be unsigned.
Definition at line 2119 of file APInt.h.
References A, and B.
Referenced by llvm::ConstantRange::abs(), llvm::ConstantRange::binaryOr(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ConstantRange::srem(), and llvm::ConstantRange::umax().
umin()
const APInt & llvm::APIntOps::umin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be signed.
Definition at line 2114 of file APInt.h.
References A, and B.
Referenced by llvm::ConstantRange::abs(), llvm::ConstantRange::binaryAnd(), foldSignedTruncationCheck(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ConstantRange::srem(), llvm::ConstantRange::umin(), and llvm::ConstantRange::urem().