LLVM: llvm::parallel::detail Namespace Reference
llvm::parallel::detail Namespace Reference
Classes
class Latch
class TaskGroup
Typedefs
template<typename Iter >
using DefComparator = std::less< typename std::iterator_traits< Iter >::value_type >
Functions
template<class RandomAccessIterator , class Comparator >
RandomAccessIterator medianOf3 (RandomAccessIterator Start, RandomAccessIterator End, const Comparator &Comp)
Inclusive median.
template<class RandomAccessIterator , class Comparator >
void parallel_quick_sort (RandomAccessIterator Start, RandomAccessIterator End, const Comparator &Comp, TaskGroup &TG, size_t Depth)
template<class RandomAccessIterator , class Comparator >
void parallel_sort (RandomAccessIterator Start, RandomAccessIterator End, const Comparator &Comp)
template<class IterTy , class FuncTy >
void parallel_for_each (IterTy Begin, IterTy End, FuncTy Fn)
template<class IndexTy , class FuncTy >
void parallel_for_each_n (IndexTy Begin, IndexTy End, FuncTy Fn)
Variables
const ptrdiff_t MinParallelSize = 1024
static std::atomic< int > TaskGroupInstances
Typedef Documentation
DefComparator
template<typename Iter > using llvm::parallel::detail::DefComparator = typedef std::less<typename std::iterator_traits<Iter>::value_type>
Definition at line 194 of file Parallel.h.
Function Documentation
medianOf3()
template<class RandomAccessIterator , class Comparator > RandomAccessIterator llvm::parallel::detail::medianOf3 (RandomAccessIterator Start, RandomAccessIterator End, const Comparator & Comp)
Inclusive median.
Definition at line 108 of file Parallel.h.
Referenced by parallel_quick_sort().
parallel_for_each()
template<class IterTy , class FuncTy > void llvm::parallel::detail::parallel_for_each (IterTy Begin, IterTy End, FuncTy Fn)
Definition at line 154 of file Parallel.h.
References llvm::parallel::detail::TaskGroup::spawn().
Referenced by llvm::parallel::for_each().
parallel_for_each_n()
template<class IndexTy , class FuncTy > void llvm::parallel::detail::parallel_for_each_n (IndexTy Begin, IndexTy End, FuncTy Fn)
Definition at line 172 of file Parallel.h.
References E, I, and llvm::parallel::detail::TaskGroup::spawn().
Referenced by llvm::parallel::for_each_n().
parallel_quick_sort()
template<class RandomAccessIterator , class Comparator > void llvm::parallel::detail::parallel_quick_sort (RandomAccessIterator Start, RandomAccessIterator End, const Comparator & Comp, TaskGroup & TG, size_t Depth)
Definition at line 120 of file Parallel.h.
References llvm::Depth, medianOf3(), MinParallelSize, parallel_quick_sort(), llvm::sort(), llvm::parallel::detail::TaskGroup::spawn(), and std::swap().
Referenced by parallel_quick_sort(), and parallel_sort().
parallel_sort()
template<class RandomAccessIterator , class Comparator > void llvm::parallel::detail::parallel_sort (RandomAccessIterator Start, RandomAccessIterator End, const Comparator & Comp)
Definition at line 146 of file Parallel.h.
References llvm::Log2_64(), and parallel_quick_sort().
Referenced by llvm::parallel::sort().
Variable Documentation
MinParallelSize
const ptrdiff_t llvm::parallel::detail::MinParallelSize = 1024
Definition at line 104 of file Parallel.h.
Referenced by parallel_quick_sort().
TaskGroupInstances
std::atomic<int> llvm::parallel::detail::TaskGroupInstances static
Definition at line 123 of file Parallel.cpp.
Referenced by llvm::parallel::detail::TaskGroup::~TaskGroup().