LLVM: llvm::orc Namespace Reference
llvm::orc Namespace Reference
Namespaces
namespace remote
namespace rpc
Classes
class AbsoluteSymbolsMaterializationUnit
A MaterializationUnit implementation for pre-existing absolute symbols.
class AsynchronousSymbolQuery
A symbol query that returns results via a callback when results are ready.
class BasicIRLayerMaterializationUnit
MaterializationUnit that materializes modules by calling the 'emit' method on the given IRLayer.
class BasicObjectLayerMaterializationUnit
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
class CompileOnDemandLayer
class ConcurrentIRCompiler
A thread-safe version of SimpleCompiler.
class CtorDtorIterator
This iterator provides a convenient way to iterate over the elements of an llvm.global_ctors/llvm.global_dtors instance.
class CtorDtorRunner
class DuplicateDefinition
class DynamicLibrarySearchGenerator
A utility class to expose symbols found via dlsym to the JIT.
class EHFrameRegistrationPlugin
class ExecutionSession
An ExecutionSession represents a running JIT program.
class FailedToMaterialize
Used to notify a JITDylib that the given set of symbols failed to materialize.
class GenericIndirectStubsInfo
Provide information about stub blocks generated by the makeIndirectStubsBlock function.
class GlobalMappingLayer
Global mapping layer.
class IndirectStubsManager
Base class for managing collections of named indirect stubs.
class IRCompileLayer
class IRLayer
Interface for layers that accept LLVM IR.
class IRMaterializationUnit
IRMaterializationUnit is a convenient base class for MaterializationUnits wrapping LLVM IR.
class IRTransformLayer
class JITCompileCallbackManager
Target-independent base class for compile callback management.
class JITDylib
A symbol table that supports asynchoronous symbol queries.
class JITSymbolNotFound
class JITSymbolResolverAdapter
Legacy adapter. Remove once we kill off the old ORC layers.
class JITTargetMachineBuilder
A utility class for building TargetMachines for JITs.
class LambdaResolver
class LambdaSymbolResolver
Implements SymbolResolver with a pair of supplied function objects for convenience.
class LazyCallThroughManager
Manages a set of 'lazy call-through' trampolines.
class LazyEmittingLayer
Lazy-emitting IR layer.
class LazyReexportsMaterializationUnit
A materialization unit that builds lazy re-exports.
class LegacyCompileOnDemandLayer
Compile-on-demand layer.
class LegacyCtorDtorRunner
Convenience class for recording constructor/destructor names for later execution.
class LegacyIRCompileLayer
Eager IR compiling layer.
class LegacyIRTransformLayer
IR mutating layer.
class LegacyLocalCXXRuntimeOverrides
class LegacyLookupFnResolver
An ORC SymbolResolver implementation that uses a legacy findSymbol-like function to perform lookup;.
class LegacyObjectTransformLayer
Object mutating layer.
class LegacyRTDyldObjectLinkingLayer
Bare bones object linking layer.
class LegacyRTDyldObjectLinkingLayerBase
class LLJIT
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
class LLJITBuilder
Constructs LLJIT instances.
class LLJITBuilderSetters
class LLJITBuilderState
class LLLazyJIT
An extended version of LLJIT that supports lazy function-at-a-time compilation of LLVM IR.
class LLLazyJITBuilder
Constructs LLLazyJIT instances.
class LLLazyJITBuilderSetters
class LLLazyJITBuilderState
class LocalCXXRuntimeOverrides
class LocalCXXRuntimeOverridesBase
Support class for static dtor execution.
class LocalIndirectStubsManager
IndirectStubsManager implementation for the host architecture, e.g.
class LocalJITCompileCallbackManager
Manage compile callbacks for in-process JITs.
class LocalLazyCallThroughManager
A lazy call-through manager that builds trampolines in the current process.
class LocalTrampolinePool
A trampoline pool for trampolines within the current process.
class MangleAndInterner
Mangles symbol names then uniques them in the context of an ExecutionSession.
class MaterializationResponsibility
Tracks responsibility for materialization, and mediates interactions between MaterializationUnits and JDs.
class MaterializationUnit
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
class NullLegacyResolver
SymbolResolver impliementation that rejects all resolution requests.
class NullResolver
class ObjectLayer
Interface for Layers that accept object files.
class ObjectLinkingLayer
An ObjectLayer implementation built on JITLink.
class ObjectLinkingLayerJITLinkContext
class ObjectTransformLayer
class OrcAArch64
class OrcGenericABI
Generic ORC ABI support.
class OrcI386
I386 support.
class OrcMCJITReplacement
class OrcMips32_Base
class OrcMips32Be
class OrcMips32Le
class OrcMips64
class OrcX86_64_Base
X86_64 code that's common to all ABIs.
class OrcX86_64_SysV
X86_64 support for SysV ABI (Linux, MacOSX).
class OrcX86_64_Win32
X86_64 support for Win32.
class PartitioningIRMaterializationUnit
class ReexportsGenerator
ReexportsGenerator can be used with JITDylib::setGenerator to automatically re-export a subset of the source JITDylib's symbols in the target.
class ReExportsMaterializationUnit
A materialization unit for symbol aliases.
class RemoteObjectClientLayer
RemoteObjectClientLayer forwards the ORC Object Layer API over an RPC connection.
class RemoteObjectLayer
Base class containing common utilities for RemoteObjectClientLayer and RemoteObjectServerLayer.
class RemoteObjectLayerAPI
RPC API needed by RemoteObjectClientLayer and RemoteObjectServerLayer.
class RemoteObjectServerLayer
RemoteObjectServerLayer acts as a server and handling RPC calls for the object layer API from the given RPC connection.
class RTDyldObjectLinkingLayer
class SimpleCompiler
Simple compile functor: Takes a single IR module and returns an ObjectFile.
struct SymbolAliasMapEntry
class SymbolLinkagePromoter
Promotes private symbols to global hidden, and renames to prevent clashes with other promoted symbols.
class SymbolResolver
SymbolResolver is a composable interface for looking up symbol flags and addresses using the AsynchronousSymbolQuery type.
class SymbolsCouldNotBeRemoved
Used to notify clients that a set of symbols could not be removed.
class SymbolsNotFound
Used to notify clients when symbols can not be found during a lookup.
class SymbolStringPool
String pool for symbol names used by the JIT.
class SymbolStringPtr
Pointer to a pooled string representing a symbol name.
class ThreadSafeContext
An LLVMContext together with an associated mutex that can be used to lock the context to prevent concurrent access by other threads.
class ThreadSafeModule
An LLVM Module together with a shared ThreadSafeContext.
class TMOwningSimpleCompiler
A SimpleCompiler that owns its TargetMachine.
class TrampolinePool
Base class for pools of compiler re-entry trampolines.
Typedefs
using VModuleKey = uint64_t
VModuleKey provides a unique identifier (allocated and managed by ExecutionSessions) for a module added to the JIT.
using SymbolNameSet = DenseSet< SymbolStringPtr >
A set of symbol names (represented by SymbolStringPtrs for.
using SymbolMap = DenseMap< SymbolStringPtr, JITEvaluatedSymbol >
A map from symbol names (as SymbolStringPtrs) to JITSymbols (address/flags pairs).
using SymbolFlagsMap = DenseMap< SymbolStringPtr, JITSymbolFlags >
A map from symbol names (as SymbolStringPtrs) to JITSymbolFlags.
using SymbolDependenceMap = DenseMap< JITDylib *, SymbolNameSet >
A base class for materialization failures that allows the failing symbols to be obtained for logging.
using JITDylibSearchList = std::vector< std::pair< JITDylib *, bool > >
A list of (JITDylib*, bool) pairs.
using SymbolAliasMap = DenseMap< SymbolStringPtr, SymbolAliasMapEntry >
A map of Symbols to (Symbol, Flags) pairs.
using SymbolsResolvedCallback = std::function< void(Expected< SymbolMap >)>
Callback to notify client that symbols have been resolved.
using RegisterDependenciesFunction = std::function< void(const SymbolDependenceMap &)>
Callback to register the dependencies for a given query.
using MaterializationUnitList = std::vector< std::unique_ptr< MaterializationUnit > >
using GVPredicate = std::function< bool(const GlobalValue &)>
using GVModifier = std::function< void(GlobalValue &)>
Enumerations
enum class SymbolState : uint8_t {
Invalid , NeverSearched , Materializing , Resolved ,
Ready = 0x3f
}
Represents the state that a symbol has reached during materialization.
enum class OrcErrorCode : int {
UnknownORCError = 1 , DuplicateDefinition , JITSymbolNotFound , RemoteAllocatorDoesNotExist ,
RemoteAllocatorIdAlreadyInUse , RemoteMProtectAddrUnrecognized , RemoteIndirectStubsOwnerDoesNotExist , RemoteIndirectStubsOwnerIdAlreadyInUse ,
RPCConnectionClosed , RPCCouldNotNegotiateFunction , RPCResponseAbandoned , UnexpectedRPCCall ,
UnexpectedRPCResponse , UnknownErrorCodeFromRemote , UnknownResourceHandle
}
Functions
raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPtr &Sym)
Render a SymbolStringPtr.
raw_ostream & operator<< (raw_ostream &OS, const SymbolNameSet &Symbols)
Render a SymbolNameSet.
raw_ostream & operator<< (raw_ostream &OS, const SymbolFlagsMap::value_type &KV)
Render a SymbolFlagsMap entry.
raw_ostream & operator<< (raw_ostream &OS, const SymbolFlagsMap &SymbolFlags)
Render a SymbolFlagsMap.
raw_ostream & operator<< (raw_ostream &OS, const SymbolMap &Symbols)
Render a SymbolMap.
raw_ostream & operator<< (raw_ostream &OS, const MaterializationUnit &MU)
Render a MaterializationUnit.
raw_ostream & operator<< (raw_ostream &OS, const JITDylibSearchList &JDs)
Render a JITDylibSearchList.
raw_ostream & operator<< (raw_ostream &OS, const SymbolAliasMap &Aliases)
Render a SymbolAliasMap.
raw_ostream & operator<< (raw_ostream &OS, const SymbolState &S)
Render a SymbolState.
std::unique_ptr< AbsoluteSymbolsMaterializationUnit > absoluteSymbols (SymbolMap Symbols, VModuleKey K=VModuleKey())
Create an AbsoluteSymbolsMaterializationUnit with the given symbols.
std::unique_ptr< ReExportsMaterializationUnit > symbolAliases (SymbolAliasMap Aliases, VModuleKey K=VModuleKey())
Create a ReExportsMaterializationUnit with the given aliases.
std::unique_ptr< ReExportsMaterializationUnit > reexports (JITDylib &SourceJD, SymbolAliasMap Aliases, bool MatchNonExported=false, VModuleKey K=VModuleKey())
Create a materialization unit for re-exporting symbols from another JITDylib with alternative names/flags.
Expected< SymbolAliasMap > buildSimpleReexportsAliasMap (JITDylib &SourceJD, const SymbolNameSet &Symbols)
Build a SymbolAliasMap for the common case where you want to re-export symbols from another JITDylib with the same linkage/flags.
iterator_range< CtorDtorIterator > getConstructors (const Module &M)
Create an iterator range over the entries of the llvm.global_ctors array.
iterator_range< CtorDtorIterator > getDestructors (const Module &M)
Create an iterator range over the entries of the llvm.global_ctors array.
Expected< std::unique_ptr< JITCompileCallbackManager > > createLocalCompileCallbackManager (const Triple &T, ExecutionSession &ES, JITTargetAddress ErrorHandlerAddress)
Create a local compile callback manager.
std::function< std::unique_ptr< IndirectStubsManager >()> createLocalIndirectStubsManagerBuilder (const Triple &T)
Create a local indriect stubs manager builder.
Constant * createIRTypedAddress (FunctionType &FT, JITTargetAddress Addr)
Build a function pointer of FunctionType with the given constant address.
GlobalVariable * createImplPointer (PointerType &PT, Module &M, const Twine &Name, Constant *Initializer)
Create a function pointer with the given type, name, and initializer in the given Module.
void makeStub (Function &F, Value &ImplPointer)
Turn a function declaration into a stub function that makes an indirect call using the given function pointer.
Function * cloneFunctionDecl (Module &Dst, const Function &F, ValueToValueMapTy *VMap=nullptr)
Clone a function declaration into a new module.
void moveFunctionBody (Function &OrigF, ValueToValueMapTy &VMap, ValueMaterializer *Materializer=nullptr, Function *NewF=nullptr)
Move the body of function 'F' to a cloned function declaration in a different module (See related cloneFunctionDecl).
GlobalVariable * cloneGlobalVariableDecl (Module &Dst, const GlobalVariable &GV, ValueToValueMapTy *VMap=nullptr)
Clone a global variable declaration into a new module.
void moveGlobalVariableInitializer (GlobalVariable &OrigGV, ValueToValueMapTy &VMap, ValueMaterializer *Materializer=nullptr, GlobalVariable *NewGV=nullptr)
Move global variable GV from its parent module to cloned global declaration in a different module.
GlobalAlias * cloneGlobalAliasDecl (Module &Dst, const GlobalAlias &OrigA, ValueToValueMapTy &VMap)
Clone a global alias declaration into a new module.
void cloneModuleFlagsMetadata (Module &Dst, const Module &Src, ValueToValueMapTy &VMap)
Clone module flags metadata into the destination module.
template<typename DylibLookupFtorT , typename ExternalLookupFtorT >
std::shared_ptr< LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT > > createLambdaResolver (DylibLookupFtorT DylibLookupFtor, ExternalLookupFtorT ExternalLookupFtor)
template<typename DylibLookupFtorT , typename ExternalLookupFtorT >
std::shared_ptr< LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT > > createLambdaResolver (ORCv1DeprecationAcknowledgement, DylibLookupFtorT DylibLookupFtor, ExternalLookupFtorT ExternalLookupFtor)
Expected< SymbolFlagsMap > getObjectSymbolFlags (ExecutionSession &ES, MemoryBufferRef ObjBuffer)
Returns a SymbolFlagsMap for the object file represented by the given buffer, or an error if the buffer does not contain a valid object file.
Expected< std::unique_ptr< LazyCallThroughManager > > createLocalLazyCallThroughManager (const Triple &T, ExecutionSession &ES, JITTargetAddress ErrorHandlerAddr)
Create a LocalLazyCallThroughManager from the given triple and execution session.
std::unique_ptr< LazyReexportsMaterializationUnit > lazyReexports (LazyCallThroughManager &LCTManager, IndirectStubsManager &ISManager, JITDylib &SourceJD, SymbolAliasMap CallableAliases, VModuleKey K=VModuleKey())
Define lazy-reexports based on the given SymbolAliasMap.
template<typename GetResponsibilitySetFn , typename LookupFn >
std::unique_ptr< LambdaSymbolResolver< typename std::remove_cv< typename std::remove_reference< GetResponsibilitySetFn >::type >::type, typename std::remove_cv< typename std::remove_reference< LookupFn >::type >::type > > createSymbolResolver (GetResponsibilitySetFn &&GetResponsibilitySet, LookupFn &&Lookup)
Creates a SymbolResolver implementation from the pair of supplied function objects.
template<typename FindSymbolFn >
Expected< SymbolNameSet > getResponsibilitySetWithLegacyFn (const SymbolNameSet &Symbols, FindSymbolFn FindSymbol)
Use the given legacy-style FindSymbol function (i.e.
template<typename FindSymbolFn >
SymbolNameSet lookupWithLegacyFn (ExecutionSession &ES, AsynchronousSymbolQuery &Query, const SymbolNameSet &Symbols, FindSymbolFn FindSymbol)
Use the given legacy-style FindSymbol function (i.e.
template<typename LegacyLookupFn >
std::shared_ptr< LegacyLookupFnResolver< LegacyLookupFn > > createLegacyLookupResolver (ExecutionSession &ES, LegacyLookupFn LegacyLookup, std::function< void(Error)> ErrorReporter)
std::error_code orcError (OrcErrorCode ErrCode)
ThreadSafeModule cloneToNewContext (ThreadSafeModule &TSMW, GVPredicate ShouldCloneDef=GVPredicate(), GVModifier UpdateClonedDefSource=GVModifier())
Clones the given module on to a new context.
raw_ostream & operator<< (raw_ostream &OS, const JITSymbolFlags &Flags)
raw_ostream & operator<< (raw_ostream &OS, const JITEvaluatedSymbol &Sym)
Variables
RegisterDependenciesFunction NoDependenciesToRegister
This can be used as the value for a RegisterDependenciesFunction if there are no dependants to register with.
Typedef Documentation
GVModifier
using llvm::orc::GVModifier = typedef std::function<void(GlobalValue &)>
Definition at line 151 of file ThreadSafeModule.h.
GVPredicate
using llvm::orc::GVPredicate = typedef std::function<bool(const GlobalValue &)>
Definition at line 150 of file ThreadSafeModule.h.
JITDylibSearchList
using llvm::orc::JITDylibSearchList = typedef std::vector<std::pair<JITDylib *, bool> >
A list of (JITDylib*, bool) pairs.
Definition at line 59 of file Core.h.
MaterializationUnitList
using llvm::orc::MaterializationUnitList = typedef std::vector<std::unique_ptr<MaterializationUnit> >
Definition at line 316 of file Core.h.
RegisterDependenciesFunction
using llvm::orc::RegisterDependenciesFunction = typedef std::function<void(const SymbolDependenceMap &)>
Callback to register the dependencies for a given query.
Definition at line 114 of file Core.h.
SymbolAliasMap
using llvm::orc::SymbolAliasMap = typedef DenseMap<SymbolStringPtr, SymbolAliasMapEntry>
A map of Symbols to (Symbol, Flags) pairs.
Definition at line 71 of file Core.h.
SymbolDependenceMap
using llvm::orc::SymbolDependenceMap = typedef DenseMap<JITDylib *, SymbolNameSet>
A base class for materialization failures that allows the failing symbols to be obtained for logging.
Definition at line 56 of file Core.h.
SymbolFlagsMap
using llvm::orc::SymbolFlagsMap = typedef DenseMap<SymbolStringPtr, JITSymbolFlags>
A map from symbol names (as SymbolStringPtrs) to JITSymbolFlags.
Definition at line 52 of file Core.h.
SymbolMap
using llvm::orc::SymbolMap = typedef DenseMap<SymbolStringPtr, JITEvaluatedSymbol>
A map from symbol names (as SymbolStringPtrs) to JITSymbols (address/flags pairs).
Definition at line 49 of file Core.h.
SymbolNameSet
using llvm::orc::SymbolNameSet = typedef DenseSet<SymbolStringPtr>
A set of symbol names (represented by SymbolStringPtrs for.
Definition at line 45 of file Core.h.
SymbolsResolvedCallback
using llvm::orc::SymbolsResolvedCallback = typedef std::function<void(Expected<SymbolMap>)>
Callback to notify client that symbols have been resolved.
Definition at line 111 of file Core.h.
VModuleKey
using llvm::orc::VModuleKey = typedef uint64_t
VModuleKey provides a unique identifier (allocated and managed by ExecutionSessions) for a module added to the JIT.
Definition at line 41 of file Core.h.
Enumeration Type Documentation
OrcErrorCode
enum class llvm::orc::OrcErrorCode : int strong
Enumerator
UnknownORCError
DuplicateDefinition
JITSymbolNotFound
RemoteAllocatorDoesNotExist
RemoteAllocatorIdAlreadyInUse
RemoteMProtectAddrUnrecognized
RemoteIndirectStubsOwnerDoesNotExist
RemoteIndirectStubsOwnerIdAlreadyInUse
RPCConnectionClosed
RPCCouldNotNegotiateFunction
RPCResponseAbandoned
UnexpectedRPCCall
UnexpectedRPCResponse
UnknownErrorCodeFromRemote
UnknownResourceHandle
Definition at line 22 of file OrcError.h.
SymbolState
enum class llvm::orc::SymbolState : uint8_t strong
Represents the state that a symbol has reached during materialization.
Enumerator
Invalid
NeverSearched
No symbol should be in this state.
Materializing
Added to the symbol table, never queried.
Resolved
Queried, materialization begun.
Ready
Assigned address, still materializing.
Definition at line 435 of file Core.h.
Function Documentation
absoluteSymbols()
std::unique_ptr< AbsoluteSymbolsMaterializationUnit > llvm::orc::absoluteSymbols (SymbolMap Symbols, VModuleKey K = VModuleKey()) inline
Create an AbsoluteSymbolsMaterializationUnit with the given symbols.
Useful for inserting absolute symbols into a JITDylib. E.g.:
JITDylib &JD = ...;
SymbolStringPtr Foo = ...;
JITEvaluatedSymbol FooSym = ...;
if (auto Err = JD.define(absoluteSymbols({{Foo, FooSym}})))
  return Err;
Definition at line 348 of file Core.h.
Referenced by llvm::orc::LLJIT::defineAbsolute(), llvm::orc::LocalCXXRuntimeOverrides::enable(), and llvm::orc::DynamicLibrarySearchGenerator::operator()().
buildSimpleReexportsAliasMap()
Expected< SymbolAliasMap > llvm::orc::buildSimpleReexportsAliasMap (JITDylib & SourceJD, const SymbolNameSet & Symbols)
Build a SymbolAliasMap for the common case where you want to re-export symbols from another JITDylib with the same linkage/flags.
Definition at line 668 of file Core.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::orc::JITDylib::lookupFlags(), and Name.
cloneFunctionDecl()
Function * llvm::orc::cloneFunctionDecl (Module & Dst, const Function & F, ValueToValueMapTy * VMap = nullptr)
Clone a function declaration into a new module.
This function can be used as the first step towards creating a callback stub (see makeStub), or moving a function body (see moveFunctionBody).
If the VMap argument is non-null, a mapping will be added between F and the new declaration, and between each of F's arguments and the new declaration's arguments. This map can then be passed in to moveFunction to move the function body if required. Note: When moving functions between modules with these utilities, all decls should be cloned (and added to a single VMap) before any bodies are moved. This will ensure that references between functions all refer to the versions in the new module.
Definition at line 283 of file IndirectionUtils.cpp.
References llvm::Function::arg_begin(), llvm::Function::copyAttributesFrom(), llvm::Function::Create(), and F.
Referenced by extractSubModule().
cloneGlobalAliasDecl()
GlobalAlias * llvm::orc::cloneGlobalAliasDecl (Module & Dst, const GlobalAlias & OrigA, ValueToValueMapTy & VMap)
Clone a global alias declaration into a new module.
Definition at line 350 of file IndirectionUtils.cpp.
References assert(), llvm::LiveRangeEdit::create(), llvm::GlobalAlias::getAliasee(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::Type::getPointerAddressSpace(), llvm::GlobalValue::getType(), and llvm::GlobalValue::getValueType().
cloneGlobalVariableDecl()
GlobalVariable * llvm::orc::cloneGlobalVariableDecl (Module & Dst, const GlobalVariable & GV, ValueToValueMapTy * VMap = nullptr)
Clone a global variable declaration into a new module.
Definition at line 320 of file IndirectionUtils.cpp.
References llvm::GlobalVariable::copyAttributesFrom(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), and llvm::GlobalVariable::isConstant().
Referenced by extractSubModule().
cloneModuleFlagsMetadata()
void llvm::orc::cloneModuleFlagsMetadata (Module & Dst, const Module & Src, ValueToValueMapTy & VMap)
Clone module flags metadata into the destination module.
Definition at line 361 of file IndirectionUtils.cpp.
References llvm::Module::addModuleFlag(), llvm::Module::getModuleFlagsMetadata(), and llvm::MapMetadata().
cloneToNewContext()
ThreadSafeModule llvm::orc::cloneToNewContext (ThreadSafeModule & TSMW, GVPredicate ShouldCloneDef = GVPredicate(), GVModifier UpdateClonedDefSource = GVModifier())
Clones the given module on to a new context.
Definition at line 18 of file ThreadSafeModule.cpp.
References assert(), llvm::CloneModule(), llvm::orc::ThreadSafeModule::getContextLock(), llvm::orc::ThreadSafeModule::getModule(), llvm::Lock, llvm::BitcodeWriter::writeModule(), llvm::BitcodeWriter::writeStrtab(), and llvm::BitcodeWriter::writeSymtab().
Referenced by extractSubModule().
createImplPointer()
GlobalVariable * llvm::orc::createImplPointer (PointerType & PT, Module & M, const Twine & Name, Constant * Initializer)
Create a function pointer with the given type, name, and initializer in the given Module.
Definition at line 225 of file IndirectionUtils.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::HiddenVisibility, Name, and llvm::GlobalValue::NotThreadLocal.
createIRTypedAddress()
Constant * llvm::orc::createIRTypedAddress (FunctionType & FT, JITTargetAddress Addr)
Build a function pointer of FunctionType with the given constant address.
Usage example: Turn a trampoline address into a function pointer constant for use in a stub.
Definition at line 216 of file IndirectionUtils.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getCast(), llvm::Type::getContext(), and llvm::IRBuilderBase::getInt64Ty().
createLambdaResolver() [1/2]
template<typename DylibLookupFtorT , typename ExternalLookupFtorT > std::shared_ptr< LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT > > llvm::orc::createLambdaResolver (DylibLookupFtorT DylibLookupFtor, ExternalLookupFtorT ExternalLookupFtor)
Definition at line 63 of file LambdaResolver.h.
createLambdaResolver() [2/2]
template<typename DylibLookupFtorT , typename ExternalLookupFtorT > std::shared_ptr< LambdaResolver< DylibLookupFtorT, ExternalLookupFtorT > > llvm::orc::createLambdaResolver (ORCv1DeprecationAcknowledgement , DylibLookupFtorT DylibLookupFtor, ExternalLookupFtorT ExternalLookupFtor)
Definition at line 72 of file LambdaResolver.h.
References llvm::AcknowledgeORCv1Deprecation.
createLegacyLookupResolver()
template<typename LegacyLookupFn > std::shared_ptr< LegacyLookupFnResolver< LegacyLookupFn > > llvm::orc::createLegacyLookupResolver (ExecutionSession & ES, LegacyLookupFn LegacyLookup, std::function< void(Error)> ErrorReporter)
Definition at line 206 of file Legacy.h.
createLocalCompileCallbackManager()
Expected< std::unique_ptr< JITCompileCallbackManager > > llvm::orc::createLocalCompileCallbackManager (const Triple & T, ExecutionSession & ES, JITTargetAddress ErrorHandlerAddress)
Create a local compile callback manager.
The given target triple will determine the ABI, and the given ErrorHandlerAddress will be used by the resulting compile callback manager if a compile callback fails.
Definition at line 115 of file IndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::inconvertibleErrorCode(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
createLocalIndirectStubsManagerBuilder()
std::function< std::unique_ptr< IndirectStubsManager >()> llvm::orc::createLocalIndirectStubsManagerBuilder (const Triple & T)
Create a local indriect stubs manager builder.
The given target triple will determine the ABI.
Definition at line 161 of file IndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::make_unique(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by LLVMOrcCreateInstance().
createLocalLazyCallThroughManager()
Expected< std::unique_ptr< LazyCallThroughManager > > llvm::orc::createLocalLazyCallThroughManager (const Triple & T, ExecutionSession & ES, JITTargetAddress ErrorHandlerAddr)
Create a LocalLazyCallThroughManager from the given triple and execution session.
Definition at line 85 of file LazyReexports.cpp.
References llvm::Triple::aarch64, llvm::inconvertibleErrorCode(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
createSymbolResolver()
template<typename GetResponsibilitySetFn , typename LookupFn > std::unique_ptr< LambdaSymbolResolver< typename std::remove_cv< typename std::remove_reference< GetResponsibilitySetFn >::type >::type, typename std::remove_cv< typename std::remove_reference< LookupFn >::type >::type > > llvm::orc::createSymbolResolver (GetResponsibilitySetFn && GetResponsibilitySet, LookupFn && Lookup)
Creates a SymbolResolver implementation from the pair of supplied function objects.
Definition at line 80 of file Legacy.h.
References Lookup().
getConstructors()
iterator_range< CtorDtorIterator > llvm::orc::getConstructors (const Module & M)
Create an iterator range over the entries of the llvm.global_ctors array.
Definition at line 77 of file ExecutionUtils.cpp.
References llvm::make_range().
Referenced by llvm::OrcCBindingsStack::addIRModule(), llvm::orc::OrcMCJITReplacement::addModule(), and llvm::orc::LLJIT::recordCtorDtors().
getDestructors()
iterator_range< CtorDtorIterator > llvm::orc::getDestructors (const Module & M)
Create an iterator range over the entries of the llvm.global_ctors array.
Definition at line 83 of file ExecutionUtils.cpp.
References llvm::make_range().
Referenced by llvm::OrcCBindingsStack::addIRModule(), llvm::orc::OrcMCJITReplacement::addModule(), and llvm::orc::LLJIT::recordCtorDtors().
getObjectSymbolFlags()
Expected< SymbolFlagsMap > llvm::orc::getObjectSymbolFlags (ExecutionSession & ES, MemoryBufferRef ObjBuffer)
Returns a SymbolFlagsMap for the object file represented by the given buffer, or an error if the buffer does not contain a valid object file.
Definition at line 152 of file Layer.cpp.
References llvm::object::ObjectFile::createObjectFile(), llvm::JITSymbolFlags::fromObjectSymbol(), llvm::orc::ExecutionSession::intern(), Name, llvm::object::BasicSymbolRef::SF_Global, and llvm::object::BasicSymbolRef::SF_Undefined.
Referenced by llvm::orc::BasicObjectLayerMaterializationUnit::Create().
getResponsibilitySetWithLegacyFn()
template<typename FindSymbolFn > Expected< SymbolNameSet > llvm::orc::getResponsibilitySetWithLegacyFn (const SymbolNameSet & Symbols, FindSymbolFn FindSymbol)
Use the given legacy-style FindSymbol function (i.e.
a function that takes a const std::string& or StringRef and returns a JITSymbol) to get the subset of symbols that the caller is responsible for materializing. If any JITSymbol returned by FindSymbol is in an error state the function returns immediately with that error.
Useful for implementing getResponsibilitySet bodies that query legacy resolvers.
Definition at line 117 of file Legacy.h.
Referenced by llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::getResponsibilitySet().
lazyReexports()
std::unique_ptr< LazyReexportsMaterializationUnit > llvm::orc::lazyReexports (LazyCallThroughManager & LCTManager, IndirectStubsManager & ISManager, JITDylib & SourceJD, SymbolAliasMap CallableAliases, VModuleKey K = VModuleKey()) inline
Define lazy-reexports based on the given SymbolAliasMap.
Each lazy re-export is a callable symbol that will look up and dispatch to the given aliasee on first call. All subsequent calls will go directly to the aliasee.
Definition at line 183 of file LazyReexports.h.
Referenced by llvm::orc::CompileOnDemandLayer::emit().
lookupWithLegacyFn()
template<typename FindSymbolFn > SymbolNameSet llvm::orc::lookupWithLegacyFn (ExecutionSession & ES, AsynchronousSymbolQuery & Query, const SymbolNameSet & Symbols, FindSymbolFn FindSymbol)
Use the given legacy-style FindSymbol function (i.e.
a function that takes a const std::string& or StringRef and returns a JITSymbol) to find the address and flags for each symbol in Symbols and store the result in Query. If any JITSymbol returned by FindSymbol is in an error then Query.notifyFailed(...) is called with that error and the function returns immediately. On success, returns the set of symbols not found.
Useful for implementing lookup bodies that query legacy resolvers.
Definition at line 143 of file Legacy.h.
References llvm::orc::AsynchronousSymbolQuery::handleComplete(), llvm::orc::AsynchronousSymbolQuery::isComplete(), llvm::orc::ExecutionSession::legacyFailQuery(), and llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState().
Referenced by llvm::orc::LegacyLookupFnResolver< LegacyLookupFn >::lookup().
makeStub()
void llvm::orc::makeStub (Function & F, Value & ImplPointer)
Turn a function declaration into a stub function that makes an indirect call using the given function pointer.
Definition at line 234 of file IndirectionUtils.cpp.
References A, assert(), llvm::BasicBlock::Create(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::IRBuilder< T, Inserter >::CreateRet(), llvm::IRBuilder< T, Inserter >::CreateRetVoid(), and F.
moveFunctionBody()
void llvm::orc::moveFunctionBody (Function & OrigF, ValueToValueMapTy & VMap, ValueMaterializer * Materializer = nullptr, Function * NewF = nullptr)
Move the body of function 'F' to a cloned function declaration in a different module (See related cloneFunctionDecl).
If the target function declaration is not supplied via the NewF parameter then it will be looked up via the VMap.
This will delete the body of function 'F' from its original parent module, but leave its declaration.
Definition at line 301 of file IndirectionUtils.cpp.
References assert(), llvm::CloneFunctionInto(), llvm::Function::deleteBody(), llvm::GlobalValue::getParent(), and llvm::GlobalValue::isDeclaration().
moveGlobalVariableInitializer()
void llvm::orc::moveGlobalVariableInitializer (GlobalVariable & OrigGV, ValueToValueMapTy & VMap, ValueMaterializer * Materializer = nullptr, GlobalVariable * NewGV = nullptr)
Move global variable GV from its parent module to cloned global declaration in a different module.
If the target global declaration is not supplied via the NewGV parameter then it will be looked up via the VMap.
This will delete the initializer of GV from its original parent module, but leave its declaration.
Definition at line 332 of file IndirectionUtils.cpp.
References assert(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getParent(), llvm::GlobalVariable::hasInitializer(), llvm::MapValue(), llvm::RF_None, and llvm::GlobalVariable::setInitializer().
operator<<() [1/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITDylibSearchList & JDs)
Render a JITDylibSearchList.
Definition at line 206 of file Core.cpp.
References assert(), and llvm::make_range().
operator<<() [2/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITEvaluatedSymbol & Sym)
Definition at line 169 of file Core.cpp.
References llvm::format(), llvm::JITEvaluatedSymbol::getAddress(), and llvm::JITEvaluatedSymbol::getFlags().
operator<<() [3/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITSymbolFlags & Flags)
Definition at line 153 of file Core.cpp.
References llvm::JITSymbolFlags::isCallable(), llvm::JITSymbolFlags::isCommon(), llvm::JITSymbolFlags::isExported(), and llvm::JITSymbolFlags::isWeak().
operator<<() [4/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const MaterializationUnit & MU)
Render a MaterializationUnit.
Definition at line 199 of file Core.cpp.
References llvm::orc::MaterializationUnit::getName(), and llvm::orc::MaterializationUnit::getSymbols().
operator<<() [5/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolAliasMap & Aliases)
Render a SymbolAliasMap.
Definition at line 222 of file Core.cpp.
operator<<() [6/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolFlagsMap & SymbolFlags)
Render a SymbolFlagsMap.
Definition at line 182 of file Core.cpp.
operator<<() [7/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolFlagsMap::value_type & KV)
Render a SymbolFlagsMap entry.
Render a SymbolDependenceMap entry.
Render a SymbolMap entry.
Definition at line 174 of file Core.cpp.
operator<<() [8/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolMap & Symbols)
Render a SymbolMap.
Render a SymbolDependendeMap.
Definition at line 186 of file Core.cpp.
operator<<() [9/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolNameSet & Symbols)
Render a SymbolNameSet.
Definition at line 149 of file Core.cpp.
operator<<() [10/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolState & S)
Render a SymbolState.
Definition at line 231 of file Core.cpp.
References Invalid, llvm_unreachable, Materializing, NeverSearched, Ready, and Resolved.
operator<<() [11/11]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolStringPtr & Sym)
Render a SymbolStringPtr.
Definition at line 145 of file Core.cpp.
orcError()
std::error_code llvm::orc::orcError (OrcErrorCode ErrCode)
Definition at line 76 of file OrcError.cpp.
Referenced by llvm::orc::FailedToMaterialize::convertToErrorCode(), llvm::orc::SymbolsNotFound::convertToErrorCode(), llvm::orc::SymbolsCouldNotBeRemoved::convertToErrorCode(), llvm::orc::DuplicateDefinition::convertToErrorCode(), llvm::orc::remote::ResourceNotFound< ResourceIdT >::convertToErrorCode(), llvm::orc::rpc::ConnectionClosed::convertToErrorCode(), llvm::orc::rpc::BadFunctionCall< FnIdT, SeqNoT >::convertToErrorCode(), llvm::orc::rpc::InvalidSequenceNumberForResponse< SeqNoT >::convertToErrorCode(), llvm::orc::rpc::ResponseAbandoned::convertToErrorCode(), llvm::orc::rpc::CouldNotNegotiate::convertToErrorCode(), llvm::orc::rpc::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::deserialize(), and llvm::orc::rpc::registerStringError().
reexports()
std::unique_ptr< ReExportsMaterializationUnit > llvm::orc::reexports (JITDylib & SourceJD, SymbolAliasMap Aliases, bool MatchNonExported = false, VModuleKey K = VModuleKey()) inline
Create a materialization unit for re-exporting symbols from another JITDylib with alternative names/flags.
If MatchNonExported is true then non-exported symbols from SourceJD can be re-exported. If it is false, attempts to re-export a non-exported symbol will result in a "symbol not found" error.
Definition at line 403 of file Core.h.
Referenced by llvm::orc::CompileOnDemandLayer::emit(), and llvm::orc::ReexportsGenerator::operator()().
symbolAliases()
std::unique_ptr< ReExportsMaterializationUnit > llvm::orc::symbolAliases (SymbolAliasMap Aliases, VModuleKey K = VModuleKey()) inline
Create a ReExportsMaterializationUnit with the given aliases.
Useful for defining symbol aliases.: E.g., given a JITDylib JD containing symbols "foo" and "bar", we can define aliases "baz" (for "foo") and "qux" (for "bar") with:
SymbolStringPtr Baz = ...;
SymbolStringPtr Qux = ...;
if (auto Err = JD.define(symbolAliases({
    {Baz, { Foo, JITSymbolFlags::Exported }},
    {Qux, { Bar, JITSymbolFlags::Weak }}}))
  return Err;
Definition at line 392 of file Core.h.
Variable Documentation
NoDependenciesToRegister
RegisterDependenciesFunction llvm::orc::NoDependenciesToRegister
Initial value:
=
    RegisterDependenciesFunction()
This can be used as the value for a RegisterDependenciesFunction if there are no dependants to register with.
Definition at line 140 of file Core.cpp.
Referenced by llvm::orc::ExecutionSession::lookup().