LLVM: lib/Target/PowerPC/TargetInfo/PowerPCTargetInfo.cpp File Reference
PowerPCTargetInfo.cpp File Reference
#include "TargetInfo/PowerPCTargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
Functions
void LLVMInitializePowerPCTargetInfo ()
Function Documentation
LLVMInitializePowerPCTargetInfo()
void LLVMInitializePowerPCTargetInfo ()
Definition at line 26 of file PowerPCTargetInfo.cpp.
References llvm::getThePPC32Target(), llvm::getThePPC64LETarget(), llvm::getThePPC64Target(), llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, X, Y, and llvm::Z.