LLVM: lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp File Reference
ResourcePriorityQueue.cpp File Reference
#include "llvm/CodeGen/ResourcePriorityQueue.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "scheduler"
Functions
static unsigned numberCtrlDepsInSU (SUnit *SU)
static unsigned numberCtrlPredInSU (SUnit *SU)
Variables
static cl::opt< bool > DisableDFASched ("disable-dfa-sched", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable use of DFA during scheduling"))
static cl::opt< int > RegPressureThreshold ("dfa-sched-reg-pressure-threshold", cl::Hidden, cl::ZeroOrMore, cl::init(5), cl::desc("Track reg pressure and switch priority to in-depth"))
static const unsigned PriorityOne = 200
static const unsigned PriorityTwo = 50
static const unsigned PriorityThree = 15
static const unsigned PriorityFour = 5
static const unsigned ScaleOne = 20
static const unsigned ScaleTwo = 10
static const unsigned ScaleThree = 5
static const unsigned FactorOne = 2
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "scheduler"
Definition at line 33 of file ResourcePriorityQueue.cpp.
Function Documentation
numberCtrlDepsInSU()
static unsigned numberCtrlDepsInSU (SUnit * SU) static
Definition at line 142 of file ResourcePriorityQueue.cpp.
References llvm::SDep::isCtrl(), and llvm::SUnit::Succs.
Referenced by llvm::ResourcePriorityQueue::scheduledNode().
numberCtrlPredInSU()
static unsigned numberCtrlPredInSU (SUnit * SU) static
Definition at line 151 of file ResourcePriorityQueue.cpp.
References llvm::SDep::isCtrl(), and llvm::SUnit::Preds.
Referenced by llvm::ResourcePriorityQueue::scheduledNode().
Variable Documentation
DisableDFASched
cl::opt< bool > DisableDFASched("disable-dfa-sched", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable use of DFA during scheduling")) ("disable-dfa-sched" , cl::Hidden , cl::ZeroOrMore , cl::init(false) , cl::desc("Disable use of DFA during scheduling")) static
Referenced by llvm::ResourcePriorityQueue::pop().
FactorOne
const unsigned FactorOne = 2 static
Definition at line 385 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ResourcePriorityQueue::SUSchedulingCost().
PriorityFour
const unsigned PriorityFour = 5 static
Definition at line 381 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ResourcePriorityQueue::SUSchedulingCost().
PriorityOne
const unsigned PriorityOne = 200 static
Definition at line 378 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost(), and llvm::ResourcePriorityQueue::SUSchedulingCost().
PriorityThree
const unsigned PriorityThree = 15 static
Definition at line 380 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost(), and llvm::ResourcePriorityQueue::SUSchedulingCost().
PriorityTwo
const unsigned PriorityTwo = 50 static
Definition at line 379 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost(), and llvm::ResourcePriorityQueue::SUSchedulingCost().
RegPressureThreshold
cl::opt< int > RegPressureThreshold("dfa-sched-reg-pressure-threshold", cl::Hidden, cl::ZeroOrMore, cl::init(5), cl::desc("Track reg pressure and switch priority to in-depth")) ("dfa-sched-reg-pressure-threshold" , cl::Hidden , cl::ZeroOrMore , cl::init(5) , cl::desc("Track reg pressure and switch priority to in-depth")) static
Referenced by llvm::ResourcePriorityQueue::SUSchedulingCost().
ScaleOne
const unsigned ScaleOne = 20 static
Definition at line 382 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ResourcePriorityQueue::SUSchedulingCost().
ScaleThree
const unsigned ScaleThree = 5 static
Definition at line 384 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ResourcePriorityQueue::SUSchedulingCost().
ScaleTwo
const unsigned ScaleTwo = 10 static
Definition at line 383 of file ResourcePriorityQueue.cpp.
Referenced by llvm::ConvergingVLIWScheduler::SchedulingCost(), and llvm::ResourcePriorityQueue::SUSchedulingCost().