LLVM: lib/Target/RISCV/RISCVInstrInfo.cpp File Reference
RISCVInstrInfo.cpp File Reference
#include "RISCVInstrInfo.h"
#include "RISCV.h"
#include "RISCVSubtarget.h"
#include "RISCVTargetMachine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "RISCVGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
Functions
static void parseCondBranch (MachineInstr &LastInst, MachineBasicBlock *&Target, SmallVectorImpl< MachineOperand > &Cond)
static unsigned getOppositeBranchOpcode (int Opc)
Macro Definition Documentation
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 26 of file RISCVInstrInfo.cpp.
Function Documentation
getOppositeBranchOpcode()
static unsigned getOppositeBranchOpcode (int Opc) static
Definition at line 193 of file RISCVInstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::RISCVInstrInfo::reverseBranchCondition().
parseCondBranch()
static void parseCondBranch (MachineInstr & LastInst, MachineBasicBlock *& Target, SmallVectorImpl< MachineOperand > & Cond) static
Definition at line 182 of file RISCVInstrInfo.cpp.
References assert(), llvm::MachineOperand::CreateImm(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MCInstrDesc::isConditionalBranch().