LLVM: lib/CodeGen/SelectionDAG/SelectionDAG.cpp File Reference
SelectionDAG.cpp File Reference
#include "llvm/CodeGen/SelectionDAG.h"
#include "SDNodeDbgValue.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/SelectionDAGAddressAnalysis.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <set>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "selectiondag"
Functions
static SDVTList makeVTList (const EVT *VTs, unsigned NumVTs)
makeVTList - Return an instance of the SDVTList struct initialized with the specified members.
static void NewSDValueDbgMsg (SDValue V, StringRef Msg, SelectionDAG *G)
static int isSignedOp (ISD::CondCode Opcode)
For an integer comparison, return 1 if the comparison is a signed operation and 2 if the result is an unsigned comparison.
static void AddNodeIDOpcode (FoldingSetNodeID &ID, unsigned OpC)
AddNodeIDOpcode - Add the node opcode to the NodeID data.
static void AddNodeIDValueTypes (FoldingSetNodeID &ID, SDVTList VTList)
AddNodeIDValueTypes - Value type lists are intern'd so we can represent them solely with their pointer.
static void AddNodeIDOperands (FoldingSetNodeID &ID, ArrayRef< SDValue > Ops)
AddNodeIDOperands - Various routines for adding operands to the NodeID data.
static void AddNodeIDOperands (FoldingSetNodeID &ID, ArrayRef< SDUse > Ops)
AddNodeIDOperands - Various routines for adding operands to the NodeID data.
static void AddNodeIDNode (FoldingSetNodeID &ID, unsigned short OpC, SDVTList VTList, ArrayRef< SDValue > OpList)
static void AddNodeIDCustom (FoldingSetNodeID &ID, const SDNode *N)
If this is an SDNode with special info, add this info to the NodeID data.
static void AddNodeIDNode (FoldingSetNodeID &ID, const SDNode *N)
AddNodeIDNode - Generic routine for adding a nodes info to the NodeID data.
static bool doNotCSE (SDNode *N)
doNotCSE - Return true if CSE should not be performed for this node.
static void VerifySDNode (SDNode *N)
VerifySDNode - Sanity check the given SDNode. Aborts if it is invalid.
static void commuteShuffle (SDValue &N1, SDValue &N2, MutableArrayRef< int > M)
Swaps the values of N1 and N2.
static const APInt * getValidShiftAmountConstant (SDValue V)
If a SHL/SRA/SRL node has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
static SDValue FoldBUILD_VECTOR (const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, SelectionDAG &DAG)
static SDValue foldCONCAT_VECTORS (const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, SelectionDAG &DAG)
Try to simplify vector concatenation to an input value, undef, or build vector.
static std::pair< APInt, bool > FoldValue (unsigned Opcode, const APInt &C1, const APInt &C2)
static SDValue getMemsetValue (SDValue Value, EVT VT, SelectionDAG &DAG, const SDLoc &dl)
getMemsetValue - Vectorized representation of the memset value operand.
static SDValue getMemsetStringVal (EVT VT, const SDLoc &dl, SelectionDAG &DAG, const TargetLowering &TLI, const ConstantDataArraySlice &Slice)
getMemsetStringVal - Similar to getMemsetValue.
static bool isMemSrcFromConstant (SDValue Src, ConstantDataArraySlice &Slice)
Returns true if memcpy source is constant data.
static bool shouldLowerMemFuncForSize (const MachineFunction &MF)
static void chainLoadsAndStoresForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SmallVector< SDValue, 32 > &OutChains, unsigned From, unsigned To, SmallVector< SDValue, 16 > &OutLoadChains, SmallVector< SDValue, 16 > &OutStoreChains)
static SDValue getMemcpyLoadsAndStores (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
static SDValue getMemmoveLoadsAndStores (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
static SDValue getMemsetStores (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, MachinePointerInfo DstPtrInfo)
Lower the call to 'memset' intrinsic function into a series of store operations.
static void checkAddrSpaceIsValidForLibcall (const TargetLowering *TLI, unsigned AS)
static MachinePointerInfo InferPointerInfo (const MachinePointerInfo &Info, SelectionDAG &DAG, SDValue Ptr, int64_t Offset=0)
InferPointerInfo - If the specified ptr/offset is a frame index, infer a MachinePointerInfo record from it.
static MachinePointerInfo InferPointerInfo (const MachinePointerInfo &Info, SelectionDAG &DAG, SDValue Ptr, SDValue OffsetOp)
InferPointerInfo - If the specified ptr/offset is a frame index, infer a MachinePointerInfo record from it.
static void checkForCyclesHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallPtrSetImpl< const SDNode * > &Checked, const llvm::SelectionDAG *DAG)
Variables
static cl::opt< bool > EnableMemCpyDAGOpt ("enable-memcpy-dag-opt", cl::Hidden, cl::init(true), cl::desc("Gang up loads and stores generated by inlining of memcpy"))
static cl::opt< int > MaxLdStGlue ("ldstmemcpy-glue-max", cl::desc("Number limit for gluing ld/st of memcpy."), cl::Hidden, cl::init(0))
static ManagedStatic< std::set< EVT, EVT::compareRawBits > > EVTs
static ManagedStatic< EVTArray > SimpleVTArray
static ManagedStatic< sys::SmartMutex< true > > VTMutex
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "selectiondag"
Definition at line 92 of file SelectionDAG.cpp.
Function Documentation
AddNodeIDCustom()
static void AddNodeIDCustom (FoldingSetNodeID & ID, const SDNode * N) static
If this is an SDNode with special info, add this info to the NodeID data.
Definition at line 472 of file SelectionDAG.cpp.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BasicBlock, llvm::ISD::BlockAddress, C, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::ISD::ExternalSymbol, llvm::ISD::FrameIndex, llvm::MachinePointerInfo::getAddrSpace(), getAddrSpace(), llvm::BlockAddressSDNode::getBlockAddress(), llvm::GlobalAddressSDNode::getGlobal(), llvm::TargetIndexSDNode::getIndex(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::MemSDNode::getMemoryVT(), llvm::GlobalAddressSDNode::getOffset(), llvm::TargetIndexSDNode::getOffset(), llvm::BlockAddressSDNode::getOffset(), llvm::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getRawBits(), llvm::MemSDNode::getRawSubclassData(), getReg(), llvm::GlobalAddressSDNode::getTargetFlags(), llvm::TargetIndexSDNode::getTargetFlags(), llvm::BlockAddressSDNode::getTargetFlags(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::JumpTable, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MCSymbol, llvm::ISD::MGATHER, llvm::ISD::MLOAD, llvm::ISD::MSCATTER, llvm::ISD::MSTORE, N, llvm::ISD::PREFETCH, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::ISD::SRCVALUE, llvm::ISD::STORE, llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetIndex, llvm::ISD::TargetJumpTable, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by AddNodeIDNode().
AddNodeIDNode() [1/2]
static void AddNodeIDNode (FoldingSetNodeID & ID, const SDNode * N) static
AddNodeIDNode - Generic routine for adding a nodes info to the NodeID data.
Definition at line 640 of file SelectionDAG.cpp.
References AddNodeIDCustom(), AddNodeIDOpcode(), AddNodeIDOperands(), AddNodeIDValueTypes(), and N.
AddNodeIDNode() [2/2]
static void AddNodeIDNode (FoldingSetNodeID & ID, unsigned short OpC, SDVTList VTList, ArrayRef< SDValue > OpList) static
Definition at line 464 of file SelectionDAG.cpp.
References AddNodeIDOpcode(), AddNodeIDOperands(), and AddNodeIDValueTypes().
Referenced by llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getBlockAddress(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getFrameIndex(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getJumpTable(), llvm::SelectionDAG::getLabelNode(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMDNode(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNodeIfExists(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getRegisterMask(), llvm::SelectionDAG::getSrcValue(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetIndex(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::MorphNodeTo(), and llvm::SDNode::Profile().
AddNodeIDOpcode()
static void AddNodeIDOpcode (FoldingSetNodeID & ID, unsigned OpC) static
AddNodeIDOpcode - Add the node opcode to the NodeID data.
Definition at line 436 of file SelectionDAG.cpp.
Referenced by AddNodeIDNode().
AddNodeIDOperands() [1/2]
static void AddNodeIDOperands (FoldingSetNodeID & ID, ArrayRef< SDUse > Ops) static
AddNodeIDOperands - Various routines for adding operands to the NodeID data.
Definition at line 456 of file SelectionDAG.cpp.
AddNodeIDOperands() [2/2]
static void AddNodeIDOperands (FoldingSetNodeID & ID, ArrayRef< SDValue > Ops) static
AddNodeIDOperands - Various routines for adding operands to the NodeID data.
Definition at line 447 of file SelectionDAG.cpp.
Referenced by AddNodeIDNode().
AddNodeIDValueTypes()
static void AddNodeIDValueTypes (FoldingSetNodeID & ID, SDVTList VTList) static
AddNodeIDValueTypes - Value type lists are intern'd so we can represent them solely with their pointer.
Definition at line 442 of file SelectionDAG.cpp.
References llvm::SDVTList::VTs.
Referenced by AddNodeIDNode().
chainLoadsAndStoresForMemcpy()
static void chainLoadsAndStoresForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SmallVector< SDValue, 32 > & OutChains, unsigned From, unsigned To, SmallVector< SDValue, 16 > & OutLoadChains, SmallVector< SDValue, 16 > & OutStoreChains) static
Definition at line 5747 of file SelectionDAG.cpp.
References assert(), From, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTruncStore(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and llvm::ISD::TokenFactor.
Referenced by getMemcpyLoadsAndStores().
checkAddrSpaceIsValidForLibcall()
static void checkAddrSpaceIsValidForLibcall (const TargetLowering * TLI, unsigned AS) static
Definition at line 6153 of file SelectionDAG.cpp.
References llvm::TargetLoweringBase::isNoopAddrSpaceCast(), and llvm::report_fatal_error().
Referenced by llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), and llvm::SelectionDAG::getMemset().
checkForCyclesHelper()
static void checkForCyclesHelper (const SDNode * N, SmallPtrSetImpl< const SDNode * > & Visited, SmallPtrSetImpl< const SDNode * > & Checked, const llvm::SelectionDAG * DAG) static
Definition at line 9551 of file SelectionDAG.cpp.
References checkForCyclesHelper(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::errs(), llvm::SmallPtrSetImpl< PtrType >::insert(), and N.
Referenced by llvm::checkForCycles(), and checkForCyclesHelper().
commuteShuffle()
static void commuteShuffle (SDValue & N1, SDValue & N2, MutableArrayRef< int > M) static
Swaps the values of N1 and N2.
Swaps all indices in the shuffle mask M that point at N1 to point at N2 and indices that point at N2 to point at N1.
Definition at line 1564 of file SelectionDAG.cpp.
References llvm::ShuffleVectorSDNode::commuteMask(), and std::swap().
Referenced by llvm::SelectionDAG::getVectorShuffle().
doNotCSE()
static bool doNotCSE (SDNode * N) static
doNotCSE - Return true if CSE should not be performed for this node.
Definition at line 656 of file SelectionDAG.cpp.
References llvm::ISD::EH_LABEL, llvm::MVT::Glue, llvm::ISD::HANDLENODE, and N.
FoldBUILD_VECTOR()
static SDValue FoldBUILD_VECTOR (const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, SelectionDAG & DAG) static
Definition at line 4146 of file SelectionDAG.cpp.
References llvm::all_of(), assert(), llvm::ISD::EXTRACT_VECTOR_ELT, getOpcode(), llvm::SelectionDAG::getUNDEF(), llvm::EVT::getVectorNumElements(), and llvm::ArrayRef< T >::size().
Referenced by llvm::SelectionDAG::getNode().
foldCONCAT_VECTORS()
static SDValue foldCONCAT_VECTORS (const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, SelectionDAG & DAG) static
Try to simplify vector concatenation to an input value, undef, or build vector.
Definition at line 4180 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::SmallVectorImpl< T >::append(), assert(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::ArrayRef< T >::empty(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBuildVector(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLoweringBase::isZExtFree(), NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::SelectionDAG::getNode().
FoldValue()
static std::pair< APInt, bool > FoldValue (unsigned Opcode, const APInt & C1, const APInt & C2) static
Definition at line 4689 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::APInt::ashr(), llvm::APInt::lshr(), llvm::ISD::MUL, llvm::ISD::OR, llvm::APInt::rotl(), llvm::ISD::ROTL, llvm::APInt::rotr(), llvm::ISD::ROTR, llvm::APInt::sadd_sat(), llvm::ISD::SADDSAT, llvm::APInt::sdiv(), llvm::ISD::SDIV, llvm::APInt::sge(), llvm::ISD::SHL, llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRA, llvm::APInt::srem(), llvm::ISD::SREM, llvm::ISD::SRL, llvm::APInt::ssub_sat(), llvm::ISD::SSUBSAT, llvm::ISD::SUB, llvm::APInt::uadd_sat(), llvm::ISD::UADDSAT, llvm::APInt::udiv(), llvm::ISD::UDIV, llvm::APInt::uge(), llvm::APInt::ule(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::APInt::urem(), llvm::ISD::UREM, llvm::APInt::usub_sat(), llvm::ISD::USUBSAT, and llvm::ISD::XOR.
Referenced by llvm::SelectionDAG::FoldConstantArithmetic().
getMemcpyLoadsAndStores()
static SDValue getMemcpyLoadsAndStores (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) static
Definition at line 5772 of file SelectionDAG.cpp.
References llvm::ConstantDataArraySlice::Array, assert(), llvm::EVT::bitsGE(), C, chainLoadsAndStoresForMemcpy(), EnableMemCpyDAGOpt, llvm::DataLayout::exceedsNaturalStackAlignment(), llvm::ISD::EXTLOAD, llvm::TargetLowering::findOptimalMemOpLowering(), llvm::DataLayout::getABITypeAlignment(), llvm::MachinePointerInfo::getAddrSpace(), llvm::Function::getAttributes(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getExtLoad(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::FrameIndexSDNode::getIndex(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getMaxGluedStoresPerMemcpy(), llvm::TargetLoweringBase::getMaxStoresPerMemcpy(), llvm::SelectionDAG::getMemBasePlusOffset(), getMemsetStringVal(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::MachinePointerInfo::getWithOffset(), llvm::SelectionDAG::InferPtrAlignment(), llvm::MachinePointerInfo::isDereferenceable(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::EVT::isInteger(), isMemSrcFromConstant(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::ConstantDataArraySlice::Length, MaxLdStGlue, llvm::MinAlign(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MONone, llvm::ConstantDataArraySlice::move(), llvm::MachineMemOperand::MOVolatile, llvm::ConstantDataArraySlice::Offset, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineFrameInfo::setObjectAlignment(), shouldLowerMemFuncForSize(), llvm::SmallVectorBase::size(), Size, llvm::ISD::TokenFactor, and TRI.
Referenced by llvm::SelectionDAG::getMemcpy().
getMemmoveLoadsAndStores()
static SDValue getMemmoveLoadsAndStores (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) static
Definition at line 5958 of file SelectionDAG.cpp.
References C, llvm::SmallVectorImpl< T >::clear(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::DataLayout::getABITypeAlignment(), llvm::MachinePointerInfo::getAddrSpace(), llvm::Function::getAttributes(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::FrameIndexSDNode::getIndex(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getMaxStoresPerMemmove(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MachinePointerInfo::getWithOffset(), llvm::SelectionDAG::InferPtrAlignment(), llvm::MachinePointerInfo::isDereferenceable(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::SDValue::isUndef(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineFrameInfo::setObjectAlignment(), shouldLowerMemFuncForSize(), llvm::SmallVectorBase::size(), Size, and llvm::ISD::TokenFactor.
Referenced by llvm::SelectionDAG::getMemmove().
getMemsetStores()
static SDValue getMemsetStores (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, unsigned Align, bool isVol, MachinePointerInfo DstPtrInfo) static
Lower the call to 'memset' intrinsic function into a series of store operations.
Parameters
DAG Selection DAG where lowered code is placed.
dl Link to corresponding IR location.
Chain Control flow dependency.
Dst Pointer to destination memory location.
Src Value of byte to write into the memory.
Size Number of bytes to write.
Align Alignment of the destination in bytes.
isVol True if destination is volatile.
DstPtrInfo IR information on the memory pointer.
Returns
New head in the control flow, if lowering was successful, empty SDValue otherwise.
The function tries to replace 'llvm.memset' intrinsic with several store operations and value calculation code. This is usually profitable for small memory size.
Definition at line 6068 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsLT(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::DataLayout::getABITypeAlignment(), llvm::MachinePointerInfo::getAddrSpace(), llvm::Function::getAttributes(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::FrameIndexSDNode::getIndex(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getMaxStoresPerMemset(), llvm::SelectionDAG::getMemBasePlusOffset(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MachinePointerInfo::getWithOffset(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::TargetLoweringBase::isTruncateFree(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineFrameInfo::setObjectAlignment(), shouldLowerMemFuncForSize(), llvm::SmallVectorBase::size(), Size, llvm::ISD::TokenFactor, and llvm::ISD::TRUNCATE.
Referenced by llvm::SelectionDAG::getMemset().
getMemsetStringVal()
static SDValue getMemsetStringVal (EVT VT, const SDLoc & dl, SelectionDAG & DAG, const TargetLowering & TLI, const ConstantDataArraySlice & Slice) static
getMemsetStringVal - Similar to getMemsetValue.
Except this is only used when a memcpy is turned into a memset when the source is a constant string ptr.
Definition at line 5672 of file SelectionDAG.cpp.
References llvm::ConstantDataArraySlice::Array, assert(), llvm::ISD::BITCAST, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::EVT::getTypeForEVT(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::EVT::isVector(), llvm::ConstantDataArraySlice::Length, llvm_unreachable, and llvm::TargetLoweringBase::shouldConvertConstantLoadToIntImm().
Referenced by getMemcpyLoadsAndStores().
getMemsetValue()
static SDValue getMemsetValue (SDValue Value, EVT VT, SelectionDAG & DAG, const SDLoc & dl) static
getMemsetValue - Vectorized representation of the memset value operand.
Definition at line 5630 of file SelectionDAG.cpp.
References assert(), C, llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::APInt::getSplat(), llvm::SelectionDAG::getSplatBuildVector(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::i8, llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLegalStoreImmediate(), Magic, llvm::ISD::MUL, and llvm::ISD::ZERO_EXTEND.
Referenced by getMemsetStores().
getValidShiftAmountConstant()
static const APInt * getValidShiftAmountConstant (SDValue V) static
If a SHL/SRA/SRL node has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
Definition at line 2398 of file SelectionDAG.cpp.
References llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::isConstOrConstSplat(), and llvm::APInt::ult().
Referenced by llvm::SelectionDAG::computeKnownBits().
InferPointerInfo() [1/2]
static MachinePointerInfo InferPointerInfo (const MachinePointerInfo & Info, SelectionDAG & DAG, SDValue Ptr, int64_t Offset = 0) static
InferPointerInfo - If the specified ptr/offset is a frame index, infer a MachinePointerInfo record from it.
This is particularly useful because the code generator has many cases where it doesn't bother passing in a MachinePointerInfo to getLoad or getStore when it has "FI+Cst".
Definition at line 6660 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and Info.
Referenced by llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), and InferPointerInfo().
InferPointerInfo() [2/2]
static MachinePointerInfo InferPointerInfo (const MachinePointerInfo & Info, SelectionDAG & DAG, SDValue Ptr, SDValue OffsetOp) static
InferPointerInfo - If the specified ptr/offset is a frame index, infer a MachinePointerInfo record from it.
This is particularly useful because the code generator has many cases where it doesn't bother passing in a MachinePointerInfo to getLoad or getStore when it has "FI+Cst".
Definition at line 6684 of file SelectionDAG.cpp.
References InferPointerInfo(), Info, and llvm::SDValue::isUndef().
isMemSrcFromConstant()
static bool isMemSrcFromConstant (SDValue Src, ConstantDataArraySlice & Slice) static
Returns true if memcpy source is constant data.
Definition at line 5721 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::Constant, G, llvm::getConstantDataArrayInfo(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::GlobalAddress.
Referenced by getMemcpyLoadsAndStores().
isSignedOp()
static int isSignedOp (ISD::CondCode Opcode) static
For an integer comparison, return 1 if the comparison is a signed operation and 2 if the result is an unsigned comparison.
Return zero if the operation does not depend on the sign of the input (setne and seteq).
Definition at line 371 of file SelectionDAG.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
Referenced by llvm::ISD::getSetCCAndOperation(), and llvm::ISD::getSetCCOrOperation().
makeVTList()
static SDVTList makeVTList (const EVT * VTs, unsigned NumVTs) static
makeVTList - Return an instance of the SDVTList struct initialized with the specified members.
Definition at line 80 of file SelectionDAG.cpp.
Referenced by llvm::SelectionDAG::getVTList().
NewSDValueDbgMsg()
static void NewSDValueDbgMsg (SDValue V, StringRef Msg, SelectionDAG * G) static
Definition at line 102 of file SelectionDAG.cpp.
References llvm::dbgs(), llvm::SelectionDAG::dump(), G, llvm::SDValue::getNode(), and LLVM_DEBUG.
Referenced by foldCONCAT_VECTORS(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVectorShuffle().
shouldLowerMemFuncForSize()
static bool shouldLowerMemFuncForSize (const MachineFunction & MF) static
Definition at line 5739 of file SelectionDAG.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::Function::hasMinSize(), llvm::Function::hasOptSize(), and llvm::Triple::isOSDarwin().
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and getMemsetStores().
VerifySDNode()
static void VerifySDNode (SDNode * N) static
VerifySDNode - Sanity check the given SDNode. Aborts if it is invalid.
Definition at line 791 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, E, llvm::EVT::getSizeInBits(), I, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isVector(), and N.
Variable Documentation
EnableMemCpyDAGOpt
cl::opt< bool > EnableMemCpyDAGOpt("enable-memcpy-dag-opt", cl::Hidden, cl::init(true), cl::desc("Gang up loads and stores generated by inlining of memcpy")) ("enable-memcpy-dag-opt" , cl::Hidden , cl::init(true) , cl::desc("Gang up loads and stores generated by inlining of memcpy")) static
Referenced by getMemcpyLoadsAndStores().
EVTs
ManagedStatic<std::set<EVT, EVT::compareRawBits> > EVTs static
Definition at line 8861 of file SelectionDAG.cpp.
MaxLdStGlue
cl::opt< int > MaxLdStGlue("ldstmemcpy-glue-max", cl::desc("Number limit for gluing ld/st of memcpy."), cl::Hidden, cl::init(0)) ("ldstmemcpy-glue-max" , cl::desc("Number limit for gluing ld/st of memcpy.") , cl::Hidden , cl::init(0)) static
Referenced by getMemcpyLoadsAndStores().
SimpleVTArray
ManagedStatic<EVTArray> SimpleVTArray static
Definition at line 8862 of file SelectionDAG.cpp.
VTMutex
ManagedStatic<sys::SmartMutex<true> > VTMutex static
Definition at line 8863 of file SelectionDAG.cpp.