LLVM: llvm::rdf::IndexedSet< T, N > Struct Template Reference
llvm::rdf::IndexedSet< T, N > Struct Template Reference
#include "Target/Hexagon/RDFRegisters.h"
Public Types
using const_iterator = typename std::vector< T >::const_iterator
Public Member Functions
IndexedSet ()
T get (uint32_t Idx) const
uint32_t insert (T Val)
uint32_t find (T Val) const
uint32_t size () const
const_iterator begin () const
const_iterator end () const
Detailed Description
template<typename T, unsigned N = 32>
struct llvm::rdf::IndexedSet< T, N >
Definition at line 36 of file RDFRegisters.h.
Member Typedef Documentation
const_iterator
template<typename T , unsigned N = 32> using llvm::rdf::IndexedSet< T, N >::const_iterator = typename std::vector<T>::const_iterator
Definition at line 62 of file RDFRegisters.h.
Constructor & Destructor Documentation
IndexedSet()
template<typename T , unsigned N = 32> llvm::rdf::IndexedSet< T, N >::IndexedSet () inline
Definition at line 37 of file RDFRegisters.h.
References N.
Member Function Documentation
begin()
template<typename T , unsigned N = 32> const_iterator llvm::rdf::IndexedSet< T, N >::begin () const inline
Definition at line 64 of file RDFRegisters.h.
end()
template<typename T , unsigned N = 32> const_iterator llvm::rdf::IndexedSet< T, N >::end () const inline
Definition at line 65 of file RDFRegisters.h.
find()
template<typename T , unsigned N = 32> uint32_t llvm::rdf::IndexedSet< T, N >::find (T Val) const inline
Definition at line 54 of file RDFRegisters.h.
References assert(), F, and llvm::find().
Referenced by llvm::rdf::PhysicalRegisterInfo::getRegMaskId().
get()
template<typename T , unsigned N = 32> T llvm::rdf::IndexedSet< T, N >::get (uint32_t Idx) const inline
Definition at line 39 of file RDFRegisters.h.
References assert(), and Idx.
Referenced by llvm::rdf::PhysicalRegisterInfo::getRegMaskBits(), and llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo().
insert()
template<typename T , unsigned N = 32> uint32_t llvm::rdf::IndexedSet< T, N >::insert (T Val) inline
Definition at line 45 of file RDFRegisters.h.
References F, and llvm::find().
Referenced by llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo().
size()
template<typename T , unsigned N = 32> uint32_t llvm::rdf::IndexedSet< T, N >::size () const inline
Definition at line 60 of file RDFRegisters.h.
Referenced by llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/RDFRegisters.h