LLVM: llvm::rdf::LaneMaskIndex Struct Reference
llvm::rdf::LaneMaskIndex Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Public Member Functions
LaneMaskIndex ()=default
LaneBitmask getLaneMaskForIndex (uint32_t K) const
uint32_t getIndexForLaneMask (LaneBitmask LM)
uint32_t getIndexForLaneMask (LaneBitmask LM) const
Detailed Description
Definition at line 431 of file RDFGraph.h.
Constructor & Destructor Documentation
LaneMaskIndex()
llvm::rdf::LaneMaskIndex::LaneMaskIndex () default
Member Function Documentation
getIndexForLaneMask() [1/2]
uint32_t llvm::rdf::LaneMaskIndex::getIndexForLaneMask (LaneBitmask LM) inline
Definition at line 438 of file RDFGraph.h.
References llvm::LaneBitmask::all(), llvm::LaneBitmask::any(), assert(), and llvm::rdf::IndexedSet< LaneBitmask >::insert().
Referenced by llvm::rdf::DataFlowGraph::pack().
getIndexForLaneMask() [2/2]
uint32_t llvm::rdf::LaneMaskIndex::getIndexForLaneMask (LaneBitmask LM) const inline
Definition at line 443 of file RDFGraph.h.
References llvm::LaneBitmask::all(), llvm::LaneBitmask::any(), assert(), and llvm::rdf::IndexedSet< LaneBitmask >::find().
getLaneMaskForIndex()
LaneBitmask llvm::rdf::LaneMaskIndex::getLaneMaskForIndex (uint32_t K) const inline
Definition at line 434 of file RDFGraph.h.
References llvm::rdf::IndexedSet< LaneBitmask >::get(), and llvm::LaneBitmask::getAll().
Referenced by llvm::rdf::DataFlowGraph::unpack().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/RDFGraph.h