LLVM: FusionCandidateCompare Struct Reference
FusionCandidateCompare Struct Reference
Public Member Functions
bool operator() (const FusionCandidate &LHS, const FusionCandidate &RHS) const
Comparison functor to sort two Control Flow Equivalent fusion candidates into dominance order.
Detailed Description
Definition at line 254 of file LoopFuse.cpp.
Member Function Documentation
operator()()
bool FusionCandidateCompare::operator() (const FusionCandidate & LHS, const FusionCandidate & RHS) const inline
Comparison functor to sort two Control Flow Equivalent fusion candidates into dominance order.
If LHS dominates RHS and RHS post-dominates LHS, return true; IF RHS dominates LHS and LHS post-dominates RHS, return false;
Definition at line 259 of file LoopFuse.cpp.
References assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTree::dominates(), FusionCandidate::DT, llvm_unreachable, FusionCandidate::PDT, and FusionCandidate::Preheader.
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopFuse.cpp