LLVM: AbstractManglingParser< Derived, Alloc > Struct Template Reference
AbstractManglingParser< Derived, Alloc > Struct Template Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Classes
struct NameState
Holds some extra information about a <name> that is being parsed.
Public Member Functions
AbstractManglingParser (const char *First_, const char *Last_)
Derived & getDerived ()
void reset (const char *First_, const char *Last_)
template<class T , class... Args>
Node * make (Args &&... args)
template<class It >
NodeArray makeNodeArray (It begin, It end)
NodeArray popTrailingNodeArray (size_t FromPosition)
bool consumeIf (StringView S)
bool consumeIf (char C)
char consume ()
char look (unsigned Lookahead=0)
size_t numLeft () const
StringView parseNumber (bool AllowNegative=false)
Qualifiers parseCVQualifiers ()
bool parsePositiveInteger (size_t *Out)
StringView parseBareSourceName ()
bool parseSeqId (size_t *Out)
Node * parseSubstitution ()
Node * parseTemplateParam ()
Node * parseTemplateArgs (bool TagTemplates=false)
Node * parseTemplateArg ()
Node * parseExpr ()
Parse the <expr> production.
Node * parsePrefixExpr (StringView Kind)
Node * parseBinaryExpr (StringView Kind)
Node * parseIntegerLiteral (StringView Lit)
Node * parseExprPrimary ()
template<class Float >
Node * parseFloatingLiteral ()
Node * parseFunctionParam ()
Node * parseNewExpr ()
Node * parseConversionExpr ()
Node * parseBracedExpr ()
Node * parseFoldExpr ()
Node * parseType ()
Parse the <type> production.
Node * parseFunctionType ()
Node * parseVectorType ()
Node * parseDecltype ()
Node * parseArrayType ()
Node * parsePointerToMemberType ()
Node * parseClassEnumType ()
Node * parseQualifiedType ()
Node * parseEncoding ()
bool parseCallOffset ()
Node * parseSpecialName ()
bool resolveForwardTemplateRefs (NameState &State)
Node * parseName (NameState *State=nullptr)
Parse the <name> production>
Node * parseLocalName (NameState *State)
Node * parseOperatorName (NameState *State)
Node * parseUnqualifiedName (NameState *State)
Node * parseUnnamedTypeName (NameState *State)
Node * parseSourceName (NameState *State)
Node * parseUnscopedName (NameState *State)
Node * parseNestedName (NameState *State)
Node * parseCtorDtorName (Node *&SoFar, NameState *State)
Node * parseAbiTags (Node *N)
Node * parseUnresolvedName ()
Parse the <unresolved-name> production.
Node * parseSimpleId ()
Node * parseBaseUnresolvedName ()
Node * parseUnresolvedType ()
Node * parseDestructorName ()
Node * parse ()
Top-level entry point into the parser.
Public Attributes
const char * First
const char * Last
PODSmallVector< Node *, 32 > Names
PODSmallVector< Node *, 32 > Subs
PODSmallVector< Node *, 8 > TemplateParams
PODSmallVector< ForwardTemplateReference *, 4 > ForwardTemplateRefs
bool TryToParseTemplateArgs = true
bool PermitForwardTemplateReferences = false
bool ParsingLambdaParams = false
Alloc ASTAllocator
Detailed Description
template<typename Derived, typename Alloc>
struct AbstractManglingParser< Derived, Alloc >
Definition at line 2156 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
AbstractManglingParser()
template<typename Derived , typename Alloc > AbstractManglingParser< Derived, Alloc >::AbstractManglingParser (const char * First_, const char * Last_) inline
Definition at line 2185 of file ItaniumDemangle.h.
Member Function Documentation
consume()
template<typename Derived , typename Alloc > char AbstractManglingParser< Derived, Alloc >::consume () inline
Definition at line 2238 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
consumeIf() [1/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::consumeIf (char C) inline
Definition at line 2230 of file ItaniumDemangle.h.
References C, AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
consumeIf() [2/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::consumeIf (StringView S) inline
Definition at line 2222 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, AbstractManglingParser< Derived, Alloc >::Last, and StringView::size().
getDerived()
template<typename Derived , typename Alloc > Derived & AbstractManglingParser< Derived, Alloc >::getDerived () inline
Definition at line 2188 of file ItaniumDemangle.h.
look()
template<typename Derived , typename Alloc > char AbstractManglingParser< Derived, Alloc >::look (unsigned Lookahead = 0) inline
Definition at line 2240 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
make()
template<typename Derived , typename Alloc > template<class T , class... Args> Node * AbstractManglingParser< Derived, Alloc >::make (Args &&... args) inline
Definition at line 2202 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator.
makeNodeArray()
template<typename Derived , typename Alloc > template<class It > NodeArray AbstractManglingParser< Derived, Alloc >::makeNodeArray (It begin, It end) inline
Definition at line 2206 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator.
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray().
numLeft()
template<typename Derived , typename Alloc > size_t AbstractManglingParser< Derived, Alloc >::numLeft () const inline
Definition at line 2246 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
parse()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parse
Top-level entry point into the parser.
Definition at line 5192 of file ItaniumDemangle.h.
parseAbiTags()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseAbiTags (Node * N)
Definition at line 3171 of file ItaniumDemangle.h.
References StringView::empty(), and N.
parseArrayType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseArrayType
Definition at line 3350 of file ItaniumDemangle.h.
parseBareSourceName()
template<typename Alloc , typename Derived > StringView AbstractManglingParser< Alloc, Derived >::parseBareSourceName
Definition at line 3211 of file ItaniumDemangle.h.
parseBaseUnresolvedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBaseUnresolvedName
Definition at line 3048 of file ItaniumDemangle.h.
parseBinaryExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBinaryExpr (StringView Kind)
Definition at line 3819 of file ItaniumDemangle.h.
parseBracedExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBracedExpr
Definition at line 4050 of file ItaniumDemangle.h.
parseCallOffset()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parseCallOffset
Definition at line 4699 of file ItaniumDemangle.h.
parseClassEnumType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseClassEnumType
Definition at line 3394 of file ItaniumDemangle.h.
References StringView::empty(), and Name.
parseConversionExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseConversionExpr
Definition at line 3918 of file ItaniumDemangle.h.
References E.
parseCtorDtorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseCtorDtorName (Node *& SoFar, NameState * State)
Definition at line 2822 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion, Node::getKind(), iostream, istream, ostream, and string.
parseCVQualifiers()
template<typename Alloc , typename Derived > Qualifiers AbstractManglingParser< Alloc, Derived >::parseCVQualifiers
Definition at line 3840 of file ItaniumDemangle.h.
References QualConst, QualNone, QualRestrict, and QualVolatile.
parseDecltype()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseDecltype
Definition at line 3334 of file ItaniumDemangle.h.
References E.
parseDestructorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseDestructorName
Definition at line 3007 of file ItaniumDemangle.h.
parseEncoding()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseEncoding
Definition at line 4853 of file ItaniumDemangle.h.
References Arg, AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion, AbstractManglingParser< Derived, Alloc >::NameState::CVQualifiers, AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, Name, and AbstractManglingParser< Derived, Alloc >::NameState::ReferenceQualifier.
parseExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseExpr
Parse the <expr> production.
Definition at line 4207 of file ItaniumDemangle.h.
References Arg, Callee, E, and T.
parseExprPrimary()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseExprPrimary
Definition at line 3955 of file ItaniumDemangle.h.
References N, and T.
parseFloatingLiteral()
template<typename Alloc , typename Derived > template<class Float > Node * AbstractManglingParser< Alloc, Derived >::parseFloatingLiteral
Definition at line 4951 of file ItaniumDemangle.h.
References C, and N.
parseFoldExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFoldExpr
Definition at line 4097 of file ItaniumDemangle.h.
References std::swap().
parseFunctionParam()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFunctionParam
Definition at line 3856 of file ItaniumDemangle.h.
parseFunctionType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFunctionType
Definition at line 3229 of file ItaniumDemangle.h.
References E, FrefQualLValue, FrefQualNone, and FrefQualRValue.
parseIntegerLiteral()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseIntegerLiteral (StringView Lit)
Definition at line 3831 of file ItaniumDemangle.h.
References StringView::empty().
parseLocalName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseLocalName (NameState * State)
Definition at line 2388 of file ItaniumDemangle.h.
References N, and parse_discriminator().
parseName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseName (NameState * State = nullptr)
Parse the <name> production>
Definition at line 2346 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, and N.
parseNestedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseNestedName (NameState * State)
Definition at line 2885 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CVQualifiers, AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, FrefQualLValue, FrefQualNone, FrefQualRValue, and AbstractManglingParser< Derived, Alloc >::NameState::ReferenceQualifier.
parseNewExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseNewExpr
Definition at line 3884 of file ItaniumDemangle.h.
parseNumber()
template<typename Alloc , typename Derived > StringView AbstractManglingParser< Alloc, Derived >::parseNumber (bool AllowNegative = false)
Definition at line 3186 of file ItaniumDemangle.h.
parseOperatorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseOperatorName (NameState * State)
Definition at line 2575 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion.
parsePointerToMemberType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parsePointerToMemberType
Definition at line 3377 of file ItaniumDemangle.h.
parsePositiveInteger()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parsePositiveInteger (size_t * Out)
Definition at line 3199 of file ItaniumDemangle.h.
parsePrefixExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parsePrefixExpr (StringView Kind)
Definition at line 3811 of file ItaniumDemangle.h.
References E.
parseQualifiedType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseQualifiedType
Definition at line 3417 of file ItaniumDemangle.h.
References StringView::begin(), StringView::dropFront(), StringView::empty(), StringView::end(), QualNone, and StringView::startsWith().
parseSeqId()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parseSeqId (size_t * Out)
Definition at line 4967 of file ItaniumDemangle.h.
parseSimpleId()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSimpleId
Definition at line 2991 of file ItaniumDemangle.h.
parseSourceName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSourceName (NameState * State)
Definition at line 2509 of file ItaniumDemangle.h.
References Name.
parseSpecialName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSpecialName
Definition at line 4729 of file ItaniumDemangle.h.
References Name.
parseSubstitution()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSubstitution
Definition at line 4999 of file ItaniumDemangle.h.
References allocator, basic_string, iostream, istream, ostream, and string.
parseTemplateArg()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArg
Definition at line 5108 of file ItaniumDemangle.h.
References Arg.
parseTemplateArgs()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArgs (bool TagTemplates = false)
Definition at line 5150 of file ItaniumDemangle.h.
References Arg.
parseTemplateParam()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateParam
Definition at line 5066 of file ItaniumDemangle.h.
References assert(), and Node::getKind().
parseType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseType
Parse the <type> production.
Definition at line 3478 of file ItaniumDemangle.h.
References DEMANGLE_FALLTHROUGH, StringView::empty(), LValue, P, and RValue.
parseUnnamedTypeName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName (NameState * State)
Definition at line 2473 of file ItaniumDemangle.h.
References P.
parseUnqualifiedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnqualifiedName (NameState * State)
Definition at line 2442 of file ItaniumDemangle.h.
parseUnresolvedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedName
Parse the <unresolved-name> production.
Definition at line 3081 of file ItaniumDemangle.h.
References assert().
parseUnresolvedType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedType
Definition at line 3022 of file ItaniumDemangle.h.
parseUnscopedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnscopedName (NameState * State)
Definition at line 2425 of file ItaniumDemangle.h.
parseVectorType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseVectorType
Definition at line 3299 of file ItaniumDemangle.h.
popTrailingNodeArray()
template<typename Derived , typename Alloc > NodeArray AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray (size_t FromPosition) inline
Definition at line 2214 of file ItaniumDemangle.h.
References assert(), PODSmallVector< T, N >::begin(), PODSmallVector< T, N >::dropBack(), PODSmallVector< T, N >::end(), AbstractManglingParser< Derived, Alloc >::makeNodeArray(), AbstractManglingParser< Derived, Alloc >::Names, and PODSmallVector< T, N >::size().
reset()
template<typename Derived , typename Alloc > void AbstractManglingParser< Derived, Alloc >::reset (const char * First_, const char * Last_) inline
Definition at line 2190 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator, PODSmallVector< T, N >::clear(), AbstractManglingParser< Derived, Alloc >::First, AbstractManglingParser< Derived, Alloc >::Last, AbstractManglingParser< Derived, Alloc >::Names, AbstractManglingParser< Derived, Alloc >::ParsingLambdaParams, AbstractManglingParser< Derived, Alloc >::PermitForwardTemplateReferences, AbstractManglingParser< Derived, Alloc >::Subs, AbstractManglingParser< Derived, Alloc >::TemplateParams, and AbstractManglingParser< Derived, Alloc >::TryToParseTemplateArgs.
resolveForwardTemplateRefs()
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs (NameState & State) inline
Definition at line 2299 of file ItaniumDemangle.h.
References PODSmallVector< T, N >::dropBack(), E, AbstractManglingParser< Derived, Alloc >::ForwardTemplateRefs, AbstractManglingParser< Derived, Alloc >::NameState::ForwardTemplateRefsBegin, I, Idx, PODSmallVector< T, N >::size(), and AbstractManglingParser< Derived, Alloc >::TemplateParams.
Member Data Documentation
ASTAllocator
template<typename Derived , typename Alloc > Alloc AbstractManglingParser< Derived, Alloc >::ASTAllocator
Definition at line 2183 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::make(), AbstractManglingParser< Derived, Alloc >::makeNodeArray(), and AbstractManglingParser< Derived, Alloc >::reset().
First
template<typename Derived , typename Alloc > const char* AbstractManglingParser< Derived, Alloc >::First
Definition at line 2157 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::consume(), AbstractManglingParser< Derived, Alloc >::consumeIf(), AbstractManglingParser< Derived, Alloc >::look(), AbstractManglingParser< Derived, Alloc >::numLeft(), and AbstractManglingParser< Derived, Alloc >::reset().
ForwardTemplateRefs
template<typename Derived , typename Alloc > PODSmallVector<ForwardTemplateReference *, 4> AbstractManglingParser< Derived, Alloc >::ForwardTemplateRefs
Definition at line 2177 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs().
Last
template<typename Derived , typename Alloc > const char* AbstractManglingParser< Derived, Alloc >::Last
Definition at line 2158 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::consume(), AbstractManglingParser< Derived, Alloc >::consumeIf(), AbstractManglingParser< Derived, Alloc >::look(), AbstractManglingParser< Derived, Alloc >::numLeft(), and AbstractManglingParser< Derived, Alloc >::reset().
Names
template<typename Derived , typename Alloc > PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Names
Definition at line 2163 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray(), and AbstractManglingParser< Derived, Alloc >::reset().
ParsingLambdaParams
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::ParsingLambdaParams = false
Definition at line 2181 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
PermitForwardTemplateReferences
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::PermitForwardTemplateReferences = false
Definition at line 2180 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
Subs
template<typename Derived , typename Alloc > PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Subs
Definition at line 2168 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
TemplateParams
template<typename Derived , typename Alloc > PODSmallVector<Node *, 8> AbstractManglingParser< Derived, Alloc >::TemplateParams
Definition at line 2173 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset(), and AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs().
TryToParseTemplateArgs
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::TryToParseTemplateArgs = true
Definition at line 2179 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h