LLVM: llvm::FunctionTypeKeyInfo Struct Reference
llvm::FunctionTypeKeyInfo Struct Reference
#include "IR/LLVMContextImpl.h"
Classes
struct KeyTy
Static Public Member Functions
static FunctionType * getEmptyKey ()
static FunctionType * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const FunctionType *FT)
static bool isEqual (const KeyTy &LHS, const FunctionType *RHS)
static bool isEqual (const FunctionType *LHS, const FunctionType *RHS)
Detailed Description
Definition at line 149 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
static FunctionType * llvm::FunctionTypeKeyInfo::getEmptyKey () inline static
Definition at line 175 of file LLVMContextImpl.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getEmptyKey().
Referenced by isEqual().
getHashValue() [1/2]
static unsigned llvm::FunctionTypeKeyInfo::getHashValue (const FunctionType * FT) inline static
Definition at line 190 of file LLVMContextImpl.h.
References getHashValue().
getHashValue() [2/2]
static unsigned llvm::FunctionTypeKeyInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 183 of file LLVMContextImpl.h.
References llvm::hash_combine(), and llvm::hash_combine_range().
Referenced by getHashValue().
getTombstoneKey()
static FunctionType * llvm::FunctionTypeKeyInfo::getTombstoneKey () inline static
Definition at line 179 of file LLVMContextImpl.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getTombstoneKey().
Referenced by isEqual().
isEqual() [1/2]
static bool llvm::FunctionTypeKeyInfo::isEqual (const FunctionType * LHS, const FunctionType * RHS) inline static
Definition at line 200 of file LLVMContextImpl.h.
isEqual() [2/2]
static bool llvm::FunctionTypeKeyInfo::isEqual (const KeyTy & LHS, const FunctionType * RHS) inline static
Definition at line 194 of file LLVMContextImpl.h.
References getEmptyKey(), and getTombstoneKey().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h