LLVM: llvm::rdf::DataFlowGraph Struct Reference
llvm::rdf::DataFlowGraph Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Classes
struct DefStack
Public Types
using DefStackMap = std::unordered_map< RegisterId, DefStack >
Public Member Functions
DataFlowGraph (MachineFunction &mf, const TargetInstrInfo &tii, const TargetRegisterInfo &tri, const MachineDominatorTree &mdt, const MachineDominanceFrontier &mdf, const TargetOperandInfo &toi)
NodeBase * ptr (NodeId N) const
template<typename T >
T ptr (NodeId N) const
NodeId id (const NodeBase *P) const
template<typename T >
NodeAddr< T > addr (NodeId N) const
NodeAddr< FuncNode * > getFunc () const
MachineFunction & getMF () const
const TargetInstrInfo & getTII () const
const TargetRegisterInfo & getTRI () const
const PhysicalRegisterInfo & getPRI () const
const MachineDominatorTree & getDT () const
const MachineDominanceFrontier & getDF () const
const RegisterAggr & getLiveIns () const
void build (unsigned Options=BuildOptions::None)
void pushAllDefs (NodeAddr< InstrNode * > IA, DefStackMap &DM)
void markBlock (NodeId B, DefStackMap &DefM)
void releaseBlock (NodeId B, DefStackMap &DefM)
PackedRegisterRef pack (RegisterRef RR)
PackedRegisterRef pack (RegisterRef RR) const
RegisterRef unpack (PackedRegisterRef PR) const
RegisterRef makeRegRef (unsigned Reg, unsigned Sub) const
RegisterRef makeRegRef (const MachineOperand &Op) const
RegisterRef restrictRef (RegisterRef AR, RegisterRef BR) const
NodeAddr< RefNode * > getNextRelated (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeAddr< RefNode * > getNextImp (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
NodeAddr< RefNode * > getNextImp (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeAddr< RefNode * > getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
NodeAddr< RefNode * > getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeList getRelatedRefs (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeAddr< BlockNode * > findBlock (MachineBasicBlock *BB) const
void unlinkUse (NodeAddr< UseNode * > UA, bool RemoveFromOwner)
void unlinkDef (NodeAddr< DefNode * > DA, bool RemoveFromOwner)
Static Public Member Functions
template<uint16_t Kind>
static bool IsRef (const NodeAddr< NodeBase * > BA)
template<uint16_t Kind>
static bool IsCode (const NodeAddr< NodeBase * > BA)
static bool IsDef (const NodeAddr< NodeBase * > BA)
static bool IsUse (const NodeAddr< NodeBase * > BA)
static bool IsPhi (const NodeAddr< NodeBase * > BA)
static bool IsPreservingDef (const NodeAddr< DefNode * > DA)
Detailed Description
Definition at line 644 of file RDFGraph.h.
Member Typedef Documentation
DefStackMap
using llvm::rdf::DataFlowGraph::DefStackMap = std::unordered_map<RegisterId, DefStack>
Definition at line 733 of file RDFGraph.h.
Constructor & Destructor Documentation
DataFlowGraph()
DataFlowGraph::DataFlowGraph (MachineFunction & mf, const TargetInstrInfo & tii, const TargetRegisterInfo & tri, const MachineDominatorTree & mdt, const MachineDominanceFrontier & mdf, const TargetOperandInfo & toi)
Definition at line 651 of file RDFGraph.cpp.
Member Function Documentation
addr()
template<typename T > NodeAddr< T > llvm::rdf::DataFlowGraph::addr (NodeId N) const inline
Definition at line 656 of file RDFGraph.h.
References N.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
build()
void DataFlowGraph::build (unsigned Options = BuildOptions::None)
Definition at line 866 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), B, E, llvm::MachineFunction::empty(), findBlock(), I, llvm::rdf::RegisterAggr::insert(), llvm::rdf::BuildOptions::KeepDeadPhis, llvm::MachineBasicBlock::liveins(), MRI, P, llvm::rdf::NodeAttrs::PhiRef, llvm::MachineBasicBlock::pred_empty(), llvm::rdf::NodeAttrs::Preserving, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::rdf::RegisterAggr::rr_begin(), and llvm::rdf::RegisterAggr::rr_end().
findBlock()
NodeAddr< BlockNode * > llvm::rdf::DataFlowGraph::findBlock (MachineBasicBlock * BB) const inline
Definition at line 768 of file RDFGraph.h.
Referenced by build(), and llvm::rdf::Liveness::getNearestAliasedRef().
getDF()
const MachineDominanceFrontier & llvm::rdf::DataFlowGraph::getDF () const inline
Definition at line 666 of file RDFGraph.h.
getDT()
const MachineDominatorTree & llvm::rdf::DataFlowGraph::getDT () const inline
Definition at line 665 of file RDFGraph.h.
getFunc()
NodeAddr< FuncNode * > llvm::rdf::DataFlowGraph::getFunc () const inline
Definition at line 660 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
getLiveIns()
const RegisterAggr & llvm::rdf::DataFlowGraph::getLiveIns () const inline
Definition at line 667 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns().
getMF()
MachineFunction & llvm::rdf::DataFlowGraph::getMF () const inline
Definition at line 661 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::resetKills(), and llvm::rdf::Liveness::resetLiveIns().
getNextImp() [1/2]
NodeAddr< RefNode * > llvm::rdf::DataFlowGraph::getNextImp (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
getNextImp() [2/2]
NodeAddr< RefNode * > llvm::rdf::DataFlowGraph::getNextImp (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
getNextRelated()
NodeAddr< RefNode * > DataFlowGraph::getNextRelated (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1154 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), llvm::rdf::NodeAddr< T >::Id, RA, llvm::rdf::NodeAttrs::Stmt, and llvm::rdf::NodeAttrs::Use.
Referenced by getRelatedRefs().
getNextShadow() [1/2]
NodeAddr< RefNode * > DataFlowGraph::getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1236 of file RDFGraph.cpp.
References assert(), llvm::rdf::NodeAddr< T >::Id, RA, and llvm::rdf::NodeAttrs::Shadow.
getNextShadow() [2/2]
NodeAddr< RefNode * > DataFlowGraph::getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
Definition at line 1215 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), llvm::rdf::NodeAddr< T >::Id, RA, and llvm::rdf::NodeAttrs::Shadow.
getPRI()
const PhysicalRegisterInfo & llvm::rdf::DataFlowGraph::getPRI () const inline
Definition at line 664 of file RDFGraph.h.
getRelatedRefs()
NodeList DataFlowGraph::getRelatedRefs (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1128 of file RDFGraph.cpp.
References assert(), getNextRelated(), llvm::rdf::NodeAddr< T >::Id, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and RA.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getAllReachingDefs().
getTII()
const TargetInstrInfo & llvm::rdf::DataFlowGraph::getTII () const inline
Definition at line 662 of file RDFGraph.h.
getTRI()
const TargetRegisterInfo & llvm::rdf::DataFlowGraph::getTRI () const inline
Definition at line 663 of file RDFGraph.h.
id()
NodeId DataFlowGraph::id (const NodeBase * P) const
Definition at line 771 of file RDFGraph.cpp.
References P.
IsCode()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsCode (const NodeAddr< NodeBase * > BA) inline static
Definition at line 792 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Code.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getAllReachingDefs().
IsDef()
static bool llvm::rdf::DataFlowGraph::IsDef (const NodeAddr< NodeBase * > BA) inline static
Definition at line 797 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Def, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::getNearestAliasedRef().
IsPhi()
static bool llvm::rdf::DataFlowGraph::IsPhi (const NodeAddr< NodeBase * > BA) inline static
Definition at line 807 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Code, and llvm::rdf::NodeAttrs::Phi.
IsPreservingDef()
static bool llvm::rdf::DataFlowGraph::IsPreservingDef (const NodeAddr< DefNode * > DA) inline static
Definition at line 812 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Preserving, and llvm::rdf::NodeAttrs::Undef.
Referenced by llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
IsRef()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsRef (const NodeAddr< NodeBase * > BA) inline static
Definition at line 786 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
IsUse()
static bool llvm::rdf::DataFlowGraph::IsUse (const NodeAddr< NodeBase * > BA) inline static
Definition at line 802 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::Use.
makeRegRef() [1/2]
RegisterRef DataFlowGraph::makeRegRef (const MachineOperand & Op) const
Definition at line 973 of file RDFGraph.cpp.
References assert(), llvm::LaneBitmask::getAll(), llvm::rdf::PhysicalRegisterInfo::getRegMaskId(), and makeRegRef().
makeRegRef() [2/2]
RegisterRef DataFlowGraph::makeRegRef (unsigned Reg, unsigned Sub) const
Definition at line 964 of file RDFGraph.cpp.
References assert(), llvm::MCRegisterInfo::getSubReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::rdf::PhysicalRegisterInfo::isRegMaskId().
Referenced by makeRegRef().
markBlock()
void DataFlowGraph::markBlock (NodeId B, DefStackMap & DefM)
Definition at line 998 of file RDFGraph.cpp.
References B, E, and I.
pack() [1/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) inline
Definition at line 740 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
pack() [2/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) const inline
Definition at line 743 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
ptr() [1/2]
NodeBase * DataFlowGraph::ptr (NodeId N) const
Definition at line 764 of file RDFGraph.cpp.
References N.
Referenced by ptr().
ptr() [2/2]
template<typename T > T llvm::rdf::DataFlowGraph::ptr (NodeId N) const inline
Definition at line 650 of file RDFGraph.h.
References N, and ptr().
pushAllDefs()
void DataFlowGraph::pushAllDefs (NodeAddr< InstrNode * > IA, DefStackMap & DM)
Definition at line 1023 of file RDFGraph.cpp.
releaseBlock()
void DataFlowGraph::releaseBlock (NodeId B, DefStackMap & DefM)
Definition at line 1005 of file RDFGraph.cpp.
References B, E, and I.
restrictRef()
RegisterRef DataFlowGraph::restrictRef (RegisterRef AR, RegisterRef BR) const
Definition at line 980 of file RDFGraph.cpp.
References llvm::rdf::PhysicalRegisterInfo::alias(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
unlinkDef()
void llvm::rdf::DataFlowGraph::unlinkDef (NodeAddr< DefNode * > DA, bool RemoveFromOwner) inline
Definition at line 778 of file RDFGraph.h.
unlinkUse()
void llvm::rdf::DataFlowGraph::unlinkUse (NodeAddr< UseNode * > UA, bool RemoveFromOwner) inline
Definition at line 772 of file RDFGraph.h.
unpack()
RegisterRef llvm::rdf::DataFlowGraph::unpack (PackedRegisterRef PR) const inline
Definition at line 746 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getLaneMaskForIndex(), llvm::rdf::PackedRegisterRef::MaskId, and llvm::rdf::PackedRegisterRef::Reg.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFGraph.h
lib/Target/Hexagon/RDFGraph.cpp