LLVM: ForwardTemplateReference Struct Reference
ForwardTemplateReference Struct Reference
A forward-reference to a template argument that was not known at the point where the template parameter name was parsed in a mangling.
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
ForwardTemplateReference (size_t Index_)
template<typename Fn >
void match (Fn F) const =delete
bool hasRHSComponentSlow (OutputStream &S) const override
bool hasArraySlow (OutputStream &S) const override
bool hasFunctionSlow (OutputStream &S) const override
const Node * getSyntaxNode (OutputStream &S) const override
void printLeft (OutputStream &S) const override
void printRight (OutputStream &S) const override
Public Member Functions inherited from Node
Node (Kind K_, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputStream &S) const
bool hasArray (OutputStream &S) const
bool hasFunction (OutputStream &S) const
Kind getKind () const
virtual bool hasRHSComponentSlow (OutputStream &) const
virtual bool hasArraySlow (OutputStream &) const
virtual bool hasFunctionSlow (OutputStream &) const
virtual const Node * getSyntaxNode (OutputStream &) const
void print (OutputStream &S) const
virtual void printLeft (OutputStream &) const =0
virtual void printRight (OutputStream &) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Public Attributes
size_t Index
Node * Ref = nullptr
bool Printing = false
Public Attributes inherited from Node
Cache RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache
Track if this node is a (possibly qualified) array type.
Cache FunctionCache
Track if this node is a (possibly qualified) function type.
Additional Inherited Members
Public Types inherited from Node
enum Kind : unsigned char
enum class Cache : unsigned char { Yes , No , Unknown }
Three-way bool to track a cached value.
Detailed Description
A forward-reference to a template argument that was not known at the point where the template parameter name was parsed in a mangling.
This is created when demangling the name of a specialization of a conversion function template:
struct A {
  template<typename T> operator T*();
};
When demangling a specialization of the conversion function template, we encounter the name of the template (including the T) before we reach the template argument list, so we cannot substitute the parameter name for the corresponding argument while parsing. Instead, we create a ForwardTemplateReference node that is resolved after we parse the template arguments.
Definition at line 1143 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
ForwardTemplateReference()
ForwardTemplateReference::ForwardTemplateReference (size_t Index_) inline
Definition at line 1153 of file ItaniumDemangle.h.
Member Function Documentation
getSyntaxNode()
const Node * ForwardTemplateReference::getSyntaxNode (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 1181 of file ItaniumDemangle.h.
References Node::getSyntaxNode(), Printing, and Ref.
hasArraySlow()
bool ForwardTemplateReference::hasArraySlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 1169 of file ItaniumDemangle.h.
References Node::hasArray(), Printing, and Ref.
hasFunctionSlow()
bool ForwardTemplateReference::hasFunctionSlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 1175 of file ItaniumDemangle.h.
References Node::hasFunction(), Printing, and Ref.
hasRHSComponentSlow()
bool ForwardTemplateReference::hasRHSComponentSlow (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 1163 of file ItaniumDemangle.h.
References Node::hasRHSComponent(), Printing, and Ref.
match()
template<typename Fn > void ForwardTemplateReference::match (Fn F) const delete
printLeft()
void ForwardTemplateReference::printLeft (OutputStream & S) const inline override virtual
Implements Node.
Definition at line 1188 of file ItaniumDemangle.h.
References Printing, Node::printLeft(), and Ref.
printRight()
void ForwardTemplateReference::printRight (OutputStream & S) const inline override virtual
Reimplemented from Node.
Definition at line 1194 of file ItaniumDemangle.h.
References Printing, Node::printRight(), and Ref.
Member Data Documentation
Index
size_t ForwardTemplateReference::Index
Definition at line 1144 of file ItaniumDemangle.h.
Printing
bool ForwardTemplateReference::Printing = false mutable
Definition at line 1151 of file ItaniumDemangle.h.
Referenced by getSyntaxNode(), hasArraySlow(), hasFunctionSlow(), hasRHSComponentSlow(), printLeft(), and printRight().
Ref
Node* ForwardTemplateReference::Ref = nullptr
Definition at line 1145 of file ItaniumDemangle.h.
Referenced by getSyntaxNode(), hasArraySlow(), hasFunctionSlow(), hasRHSComponentSlow(), printLeft(), and printRight().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h