LLVM: llvm::DenseMapInfo< gsym::FileEntry > Struct Reference
llvm::DenseMapInfo< gsym::FileEntry > Struct Reference
#include "llvm/DebugInfo/GSYM/FileEntry.h"
Static Public Member Functions
static gsym::FileEntry getEmptyKey ()
static gsym::FileEntry getTombstoneKey ()
static unsigned getHashValue (const gsym::FileEntry &Val)
static bool isEqual (const gsym::FileEntry &LHS, const gsym::FileEntry &RHS)
Detailed Description
Definition at line 49 of file FileEntry.h.
Member Function Documentation
getEmptyKey()
static gsym::FileEntry llvm::DenseMapInfo< gsym::FileEntry >::getEmptyKey () inline static
Definition at line 50 of file FileEntry.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getEmptyKey().
getHashValue()
static unsigned llvm::DenseMapInfo< gsym::FileEntry >::getHashValue (const gsym::FileEntry & Val) inline static
Definition at line 58 of file FileEntry.h.
References llvm::gsym::FileEntry::Base, llvm::gsym::FileEntry::Dir, and llvm::hash_combine().
getTombstoneKey()
static gsym::FileEntry llvm::DenseMapInfo< gsym::FileEntry >::getTombstoneKey () inline static
Definition at line 54 of file FileEntry.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getTombstoneKey().
isEqual()
static bool llvm::DenseMapInfo< gsym::FileEntry >::isEqual (const gsym::FileEntry & LHS, const gsym::FileEntry & RHS) inline static
Definition at line 62 of file FileEntry.h.
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/GSYM/FileEntry.h