LLVM: llvm::MultiClass Struct Reference
llvm::MultiClass Struct Reference
#include "TableGen/TGParser.h"
Public Member Functions
void dump () const
MultiClass (StringRef Name, SMLoc Loc, RecordKeeper &Records)
Public Attributes
Record Rec
std::vector< RecordsEntry > Entries
Detailed Description
Definition at line 77 of file TGParser.h.
Constructor & Destructor Documentation
MultiClass()
llvm::MultiClass::MultiClass (StringRef Name, SMLoc Loc, RecordKeeper & Records) inline
Definition at line 83 of file TGParser.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MultiClass::dump () const
Definition at line 3235 of file TGParser.cpp.
References llvm::Record::dump(), E, Entries, llvm::errs(), and Rec.
Referenced by llvm::SubMultiClassReference::dump().
Member Data Documentation
Entries
std::vector<RecordsEntry> llvm::MultiClass::Entries
Definition at line 79 of file TGParser.h.
Referenced by dump().
Rec
Record llvm::MultiClass::Rec
Definition at line 78 of file TGParser.h.
Referenced by dump(), QualifiedNameOfImplicitName(), and QualifyName().
The documentation for this struct was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp