LLVM: llvm::remarks::StringTable Struct Reference
llvm::remarks::StringTable Struct Reference
The string table used for serializing remarks.
#include "llvm/Remarks/RemarkStringTable.h"
Public Member Functions
StringTable ()
std::pair< unsigned, StringRef > add (StringRef Str)
Add a string to the table. It returns an unique ID of the string.
void serialize (raw_ostream &OS) const
Serialize the string table to a stream.
std::vector< StringRef > serialize () const
Serialize the string table to a vector.
Public Attributes
BumpPtrAllocator Allocator
Allocator holding all the memory used by the map.
StringMap< unsigned, BumpPtrAllocator & > StrTab
The string table containing all the unique strings used in the output.
size_t SerializedSize = 0
Total size of the string table when serialized.
Detailed Description
The string table used for serializing remarks.
This table can be for example serialized in a section to be consumed after the compilation.
Definition at line 33 of file RemarkStringTable.h.
Constructor & Destructor Documentation
StringTable()
llvm::remarks::StringTable::StringTable () inline
Definition at line 42 of file RemarkStringTable.h.
Member Function Documentation
add()
std::pair< unsigned, StringRef > StringTable::add (StringRef Str)
Add a string to the table. It returns an unique ID of the string.
Definition at line 21 of file RemarkStringTable.cpp.
References SerializedSize, and StrTab.
serialize() [1/2]
std::vector< StringRef > StringTable::serialize () const
Serialize the string table to a vector.
This allows users to do the actual writing to file/memory/other. The string with the ID == N should be the N-th element in the vector.
Definition at line 43 of file RemarkStringTable.cpp.
References StrTab.
Referenced by llvm::orc::rpc::SequenceSerialization< ChannelT, ArgT, ArgTs... >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::serialize(), serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::string, T, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, const char * >::value||std::is_same< T, char * >::value)>::type >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::string, std::string, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize(), and llvm::orc::rpc::detail::HandlerTraits< RetT(ArgTs...)>::serializeArgs().
serialize() [2/2]
void StringTable::serialize (raw_ostream & OS) const
Serialize the string table to a stream.
It is serialized as a little endian uint64 (the size of the table in bytes) followed by a sequence of NULL-terminated strings, where the N-th string is the string with the ID N in the StrTab map.
Definition at line 31 of file RemarkStringTable.cpp.
References llvm::support::little, serialize(), SerializedSize, llvm::raw_ostream::write(), and llvm::support::endian::write().
Member Data Documentation
Allocator
BumpPtrAllocator llvm::remarks::StringTable::Allocator
Allocator holding all the memory used by the map.
Definition at line 35 of file RemarkStringTable.h.
SerializedSize
size_t llvm::remarks::StringTable::SerializedSize = 0
Total size of the string table when serialized.
Definition at line 40 of file RemarkStringTable.h.
Referenced by add(), and serialize().
StrTab
StringMap<unsigned, BumpPtrAllocator &> llvm::remarks::StringTable::StrTab
The string table containing all the unique strings used in the output.
It maps a string to an unique ID.
Definition at line 38 of file RemarkStringTable.h.
Referenced by add(), and serialize().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/RemarkStringTable.h
lib/Remarks/RemarkStringTable.cpp