LLVM: llvm::GraphTraits< const CallGraph * > Struct Reference
llvm::GraphTraits< const CallGraph * > Struct Reference
#include "llvm/Analysis/CallGraph.h"
Public Types
using PairTy = std::pair< const Function *const, std::unique_ptr< CallGraphNode > >
using nodes_iterator = mapped_iterator< CallGraph::const_iterator, decltype(&CGGetValuePtr)>
Public Types inherited from llvm::GraphTraits< const CallGraphNode * >
using NodeRef = const CallGraphNode *
using CGNPairTy = CallGraphNode::CallRecord
using EdgeRef = const CallGraphNode::CallRecord &
using ChildIteratorType = mapped_iterator< CallGraphNode::const_iterator, decltype(&CGNGetValue)>
using ChildEdgeIteratorType = CallGraphNode::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (const CallGraph *CGN)
static const CallGraphNode * CGGetValuePtr (const PairTy &P)
static nodes_iterator nodes_begin (const CallGraph *CG)
static nodes_iterator nodes_end (const CallGraph *CG)
Static Public Member Functions inherited from llvm::GraphTraits< const CallGraphNode * >
static NodeRef getEntryNode (const CallGraphNode *CGN)
static const CallGraphNode * CGNGetValue (CGNPairTy P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
static NodeRef edge_dest (EdgeRef E)
Detailed Description
Definition at line 481 of file CallGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< const CallGraph * >::nodes_iterator = mapped_iterator<CallGraph::const_iterator, decltype(&CGGetValuePtr)>
Definition at line 495 of file CallGraph.h.
PairTy
using llvm::GraphTraits< const CallGraph * >::PairTy = std::pair<const Function *const, std::unique_ptr<CallGraphNode> >
Definition at line 483 of file CallGraph.h.
Member Function Documentation
CGGetValuePtr()
static const CallGraphNode * llvm::GraphTraits< const CallGraph * >::CGGetValuePtr (const PairTy & P) inline static
Definition at line 490 of file CallGraph.h.
References P.
getEntryNode()
static NodeRef llvm::GraphTraits< const CallGraph * >::getEntryNode (const CallGraph * CGN) inline static
Definition at line 486 of file CallGraph.h.
References llvm::CallGraph::getExternalCallingNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_begin (const CallGraph * CG) inline static
Definition at line 498 of file CallGraph.h.
References llvm::CallGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_end (const CallGraph * CG) inline static
Definition at line 502 of file CallGraph.h.
References llvm::CallGraph::end().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CallGraph.h