LLVM: llvm::DWARFDebugLoclists::LocationList Struct Reference
llvm::DWARFDebugLoclists::LocationList Struct Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
Public Member Functions
void dump (raw_ostream &OS, uint64_t BaseAddr, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo *RegInfo, DWARFUnit *U, unsigned Indent) const
Public Attributes
unsigned Offset
SmallVector< Entry, 2 > Entries
Detailed Description
Definition at line 84 of file DWARFDebugLoc.h.
Member Function Documentation
dump()
void DWARFDebugLoclists::LocationList::dump (raw_ostream & OS, uint64_t BaseAddr, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo * RegInfo, DWARFUnit * U, unsigned Indent) const
Definition at line 222 of file DWARFDebugLoc.cpp.
References dumpExpression(), llvm::dwarf::DW_LLE_base_address, llvm::dwarf::DW_LLE_offset_pair, llvm::dwarf::DW_LLE_start_length, llvm::dwarf::DW_LLE_startx_length, E, Entries, llvm::format(), llvm::raw_ostream::indent(), llvm_unreachable, and MRI.
Member Data Documentation
Entries
SmallVector<Entry, 2> llvm::DWARFDebugLoclists::LocationList::Entries
Definition at line 86 of file DWARFDebugLoc.h.
Referenced by dump(), and llvm::DWARFDebugLoclists::parseOneLocationList().
Offset
unsigned llvm::DWARFDebugLoclists::LocationList::Offset
Definition at line 85 of file DWARFDebugLoc.h.
Referenced by llvm::DWARFDebugLoclists::getLocationListAtOffset(), and llvm::DWARFDebugLoclists::parseOneLocationList().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
lib/DebugInfo/DWARF/DWARFDebugLoc.cpp