LLVM: llvm::object::import_lookup_table_entry< IntTy > Struct Template Reference
llvm::object::import_lookup_table_entry< IntTy > Struct Template Reference
#include "llvm/Object/COFF.h"
Public Member Functions
bool isOrdinal () const
uint16_t getOrdinal () const
uint32_t getHintNameRVA () const
Public Attributes
IntTy Data
Detailed Description
template<typename IntTy>
struct llvm::object::import_lookup_table_entry< IntTy >
Definition at line 189 of file COFF.h.
Member Function Documentation
getHintNameRVA()
template<typename IntTy > uint32_t llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA () const inline
Definition at line 199 of file COFF.h.
References assert(), llvm::object::import_lookup_table_entry< IntTy >::Data, and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
Referenced by llvm::object::ImportedSymbolRef::getHintNameRVA(), llvm::object::ImportedSymbolRef::getOrdinal(), and llvm::object::ImportedSymbolRef::getSymbolName().
getOrdinal()
template<typename IntTy > uint16_t llvm::object::import_lookup_table_entry< IntTy >::getOrdinal () const inline
Definition at line 194 of file COFF.h.
References assert(), llvm::object::import_lookup_table_entry< IntTy >::Data, and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
Referenced by llvm::object::ImportedSymbolRef::getOrdinal().
isOrdinal()
template<typename IntTy > bool llvm::object::import_lookup_table_entry< IntTy >::isOrdinal () const inline
Definition at line 192 of file COFF.h.
References llvm::object::import_lookup_table_entry< IntTy >::Data.
Referenced by llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), and llvm::object::ImportedSymbolRef::isOrdinal().
Member Data Documentation
Data
template<typename IntTy > IntTy llvm::object::import_lookup_table_entry< IntTy >::Data
Definition at line 190 of file COFF.h.
Referenced by llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
The documentation for this struct was generated from the following file:
include/llvm/Object/COFF.h