LLVM: llvm::AsmPrinter::XRayFunctionEntry Struct Reference
llvm::AsmPrinter::XRayFunctionEntry Struct Reference
#include "llvm/CodeGen/AsmPrinter.h"
Public Member Functions
void emit (int, MCStreamer *, const MCSymbol *) const
Public Attributes
const MCSymbol * Sled
const MCSymbol * Function
SledKind Kind
bool AlwaysInstrument
const class Function * Fn
uint8_t Version
Detailed Description
Definition at line 255 of file AsmPrinter.h.
Member Function Documentation
emit()
void AsmPrinter::XRayFunctionEntry::emit (int Bytes, MCStreamer * Out, const MCSymbol * CurrentFnSym) const
Definition at line 3118 of file AsmPrinter.cpp.
References AlwaysInstrument, assert(), llvm::AsmPrinter::CurrentFnSym, llvm::MCStreamer::EmitBinaryData(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitZeros(), Kind, Sled, and Version.
Member Data Documentation
AlwaysInstrument
bool llvm::AsmPrinter::XRayFunctionEntry::AlwaysInstrument
Definition at line 259 of file AsmPrinter.h.
Referenced by emit().
Fn
const class Function* llvm::AsmPrinter::XRayFunctionEntry::Fn
Definition at line 260 of file AsmPrinter.h.
Function
const MCSymbol* llvm::AsmPrinter::XRayFunctionEntry::Function
Definition at line 257 of file AsmPrinter.h.
Kind
SledKind llvm::AsmPrinter::XRayFunctionEntry::Kind
Definition at line 258 of file AsmPrinter.h.
Referenced by emit().
Sled
const MCSymbol* llvm::AsmPrinter::XRayFunctionEntry::Sled
Definition at line 256 of file AsmPrinter.h.
Referenced by emit().
Version
uint8_t llvm::AsmPrinter::XRayFunctionEntry::Version
Definition at line 261 of file AsmPrinter.h.
Referenced by emit().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/AsmPrinter.h
lib/CodeGen/AsmPrinter/AsmPrinter.cpp