LLVM: llvm::ilist_callback_traits< MachineBasicBlock > Struct Reference
llvm::ilist_callback_traits< MachineBasicBlock > Struct Reference
#include "llvm/CodeGen/MachineFunction.h"
Public Member Functions
void addNodeToList (MachineBasicBlock *N)
When an MBB is added to an MF, we need to update the parent pointer of the MBB, the MBB numbering, and any instructions in the MBB to be on the right operand list for registers.
void removeNodeFromList (MachineBasicBlock *N)
template<class Iterator >
void transferNodesFromList (ilist_callback_traits &OldList, Iterator, Iterator)
Detailed Description
Definition at line 79 of file MachineFunction.h.
Member Function Documentation
addNodeToList()
void llvm::ilist_callback_traits< MachineBasicBlock >::addNodeToList (MachineBasicBlock * N)
When an MBB is added to an MF, we need to update the parent pointer of the MBB, the MBB numbering, and any instructions in the MBB to be on the right operand list for registers.
MBBs start out as #-1. When a MBB is added to a MachineFunction, it gets the next available unique MBB number. If it is removed from a MachineFunction, it goes back to being #-1.
Definition at line 84 of file MachineBasicBlock.cpp.
References llvm::MachineFunction::addToMBBNumbering(), E, llvm::MachineFunction::getRegInfo(), I, and N.
removeNodeFromList()
void llvm::ilist_callback_traits< MachineBasicBlock >::removeNodeFromList (MachineBasicBlock * N)
Definition at line 96 of file MachineBasicBlock.cpp.
References N.
transferNodesFromList()
template<class Iterator > void llvm::ilist_callback_traits< MachineBasicBlock >::transferNodesFromList (ilist_callback_traits< MachineBasicBlock > & OldList, Iterator , Iterator) inline
Definition at line 84 of file MachineFunction.h.
References assert().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineBasicBlock.cpp