LLVM: llvm::codeview::serialize_conditional_impl< T, U > Struct Template Reference
llvm::codeview::serialize_conditional_impl< T, U > Struct Template Reference
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
Public Member Functions
serialize_conditional_impl (T &Item, U Func)
Error deserialize (BinaryStreamReader &Reader) const
Public Attributes
T & Item
U Func
Detailed Description
template<typename T, typename U>
struct llvm::codeview::serialize_conditional_impl< T, U >
Definition at line 73 of file RecordSerialization.h.
Constructor & Destructor Documentation
serialize_conditional_impl()
template<typename T , typename U > llvm::codeview::serialize_conditional_impl< T, U >::serialize_conditional_impl (T & Item, U Func) inline
Definition at line 74 of file RecordSerialization.h.
Member Function Documentation
deserialize()
template<typename T , typename U > Error llvm::codeview::serialize_conditional_impl< T, U >::deserialize (BinaryStreamReader & Reader) const inline
Definition at line 76 of file RecordSerialization.h.
References llvm::consume, llvm::codeview::serialize_conditional_impl< T, U >::Func, llvm::codeview::serialize_conditional_impl< T, U >::Item, and llvm::Error::success().
Referenced by llvm::codeview::consume(), llvm::orc::rpc::SequenceSerialization< ChannelT, ArgT >::deserialize(), llvm::orc::rpc::SequenceSerialization< ChannelT, ArgT, ArgTs... >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >::deserialize(), and llvm::orc::rpc::deserializeSeq().
Member Data Documentation
Func
template<typename T , typename U > U llvm::codeview::serialize_conditional_impl< T, U >::Func
Definition at line 83 of file RecordSerialization.h.
Referenced by llvm::codeview::serialize_conditional_impl< T, U >::deserialize().
Item
template<typename T , typename U > T& llvm::codeview::serialize_conditional_impl< T, U >::Item
Definition at line 82 of file RecordSerialization.h.
Referenced by llvm::codeview::serialize_conditional_impl< T, U >::deserialize().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/RecordSerialization.h