LLVM: llvm::yaml::SequenceTraits< ArrayRef< T > > Struct Template Reference
llvm::yaml::SequenceTraits< ArrayRef< T > > Struct Template Reference
ArrayRef is not really compatible with the YAMLTraits.
Static Public Member Functions
static size_t size (IO &io, ArrayRef< T > &seq)
static Argument & element (IO &io, ArrayRef< T > &seq, size_t index)
Detailed Description
template<typename T>
struct llvm::yaml::SequenceTraits< ArrayRef< T > >
ArrayRef is not really compatible with the YAMLTraits.
Everything should be immutable in an ArrayRef, while the SequenceTraits expect a mutable version for inputting, but we're only using the outputting capabilities here. This is a hack, but still nicer than having to manually call the YAMLIO internal methods. Keep this in this file so that it doesn't get misused from YAMLTraits.h.
Definition at line 123 of file YAMLRemarkSerializer.cpp.
Member Function Documentation
element()
template<typename T > static Argument & llvm::yaml::SequenceTraits< ArrayRef< T > >::element (IO & io, ArrayRef< T > & seq, size_t index) inline static
Definition at line 125 of file YAMLRemarkSerializer.cpp.
References assert(), and llvm::seq().
size()
template<typename T > static size_t llvm::yaml::SequenceTraits< ArrayRef< T > >::size (IO & io, ArrayRef< T > & seq) inline static
Definition at line 124 of file YAMLRemarkSerializer.cpp.
References llvm::seq().
The documentation for this struct was generated from the following file:
lib/Remarks/YAMLRemarkSerializer.cpp