LLVM: llvm::ms_demangle::SymbolNode Struct Reference
llvm::ms_demangle::SymbolNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
SymbolNode (NodeKind K)
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputStream &OS, OutputFlags Flags) const =0
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
QualifiedNameNode * Name = nullptr
Detailed Description
Definition at line 574 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
SymbolNode()
llvm::ms_demangle::SymbolNode::SymbolNode (NodeKind K) inline explicit
Definition at line 575 of file MicrosoftDemangleNodes.h.
Member Function Documentation
output()
void SymbolNode::output (OutputStream & OS, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Reimplemented in llvm::ms_demangle::SpecialTableSymbolNode, llvm::ms_demangle::LocalStaticGuardVariableNode, llvm::ms_demangle::EncodedStringLiteralNode, llvm::ms_demangle::VariableSymbolNode, and llvm::ms_demangle::FunctionSymbolNode.
Definition at line 573 of file MicrosoftDemangleNodes.cpp.
References Name, and llvm::ms_demangle::QualifiedNameNode::output().
Referenced by llvm::microsoftDemangle(), and llvm::ms_demangle::TemplateParameterReferenceNode::output().
Member Data Documentation
Name
QualifiedNameNode* llvm::ms_demangle::SymbolNode::Name = nullptr
Definition at line 577 of file MicrosoftDemangleNodes.h.
Referenced by output(), llvm::ms_demangle::SpecialTableSymbolNode::output(), llvm::ms_demangle::LocalStaticGuardVariableNode::output(), llvm::ms_demangle::VariableSymbolNode::output(), llvm::ms_demangle::FunctionSymbolNode::output(), and synthesizeVariable().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp