LLVM: llvm::ForceFunctionAttrsPass Struct Reference
llvm::ForceFunctionAttrsPass Struct Reference
Pass which forces specific function attributes into the IR, primarily as a debugging tool.
#include "llvm/Transforms/IPO/ForceFunctionAttrs.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ForceFunctionAttrsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass which forces specific function attributes into the IR, primarily as a debugging tool.
Definition at line 23 of file ForceFunctionAttrs.h.
Member Function Documentation
run()
PreservedAnalyses ForceFunctionAttrsPass::run (Module & M, ModuleAnalysisManager &)
Definition at line 89 of file ForceFunctionAttrs.cpp.
References addForcedAttributes(), llvm::PreservedAnalyses::all(), F, ForceAttributes, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/ForceFunctionAttrs.h
lib/Transforms/IPO/ForceFunctionAttrs.cpp