LLVM: llvm::HexagonSubtarget::UsrOverflowMutation Struct Reference
llvm::HexagonSubtarget::UsrOverflowMutation Struct Reference
#include "Target/Hexagon/HexagonSubtarget.h"
Public Member Functions
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
virtual void apply (ScheduleDAGInstrs *DAG)=0
Detailed Description
Definition at line 69 of file HexagonSubtarget.h.
Member Function Documentation
apply()
void HexagonSubtarget::UsrOverflowMutation::apply (ScheduleDAGInstrs * DAG) override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 128 of file HexagonSubtarget.cpp.
References D, E, llvm::SUnit::isInstr(), llvm::SDep::Output, llvm::SUnit::Preds, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SUnit::removePred(), and llvm::ScheduleDAG::SUnits.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonSubtarget.h
lib/Target/Hexagon/HexagonSubtarget.cpp