LLVM: llvm::X86Operand Struct Reference
llvm::X86Operand Struct Reference final
X86Operand - Instances of this class represent a parsed X86 machine instruction.
#include "Target/X86/AsmParser/X86Operand.h"
Classes
struct ImmOp
struct MemOp
struct PrefOp
struct RegOp
struct TokOp
Public Types
enum KindTy {
Token , Register , Immediate , Memory ,
Prefix , DXRegister
}
Public Member Functions
X86Operand (KindTy K, SMLoc Start, SMLoc End)
StringRef getSymName () override
void * getOpDecl () override
SMLoc getStartLoc () const override
getStartLoc - Get the location of the first token of this operand.
SMLoc getEndLoc () const override
getEndLoc - Get the location of the last token of this operand.
SMRange getLocRange () const
getLocRange - Get the range between the first and last token of this operand.
SMLoc getOffsetOfLoc () const override
getOffsetOfLoc - Get the location of the offset operator.
void print (raw_ostream &OS) const override
print - Print a debug representation of the operand to the given stream.
StringRef getToken () const
void setTokenValue (StringRef Value)
unsigned getReg () const override
unsigned getPrefix () const
const MCExpr * getImm () const
const MCExpr * getMemDisp () const
unsigned getMemSegReg () const
unsigned getMemBaseReg () const
unsigned getMemIndexReg () const
unsigned getMemScale () const
unsigned getMemModeSize () const
unsigned getMemFrontendSize () const
bool isToken () const override
isToken - Is this a token operand?
bool isImm () const override
isImm - Is this an immediate operand?
bool isImmSExti16i8 () const
bool isImmSExti32i8 () const
bool isImmSExti64i8 () const
bool isImmSExti64i32 () const
bool isImmUnsignedi8 () const
bool isOffsetOf () const override
isOffsetOf - Do we need to emit code to get the offset of the variable, rather then the value of the variable? Only valid when parsing MS-style inline assembly.
bool needAddressOf () const override
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
bool isMem () const override
isMem - Is this a memory operand?
bool isMemUnsized () const
bool isMem8 () const
bool isMem16 () const
bool isMem32 () const
bool isMem64 () const
bool isMem80 () const
bool isMem128 () const
bool isMem256 () const
bool isMem512 () const
bool isMemIndexReg (unsigned LowR, unsigned HighR) const
bool isMem64_RC128 () const
bool isMem128_RC128 () const
bool isMem128_RC256 () const
bool isMem256_RC128 () const
bool isMem256_RC256 () const
bool isMem64_RC128X () const
bool isMem128_RC128X () const
bool isMem128_RC256X () const
bool isMem256_RC128X () const
bool isMem256_RC256X () const
bool isMem256_RC512 () const
bool isMem512_RC256X () const
bool isMem512_RC512 () const
bool isAbsMem () const
bool isAVX512RC () const
bool isAbsMem16 () const
bool isSrcIdx () const
bool isSrcIdx8 () const
bool isSrcIdx16 () const
bool isSrcIdx32 () const
bool isSrcIdx64 () const
bool isDstIdx () const
bool isDstIdx8 () const
bool isDstIdx16 () const
bool isDstIdx32 () const
bool isDstIdx64 () const
bool isMemOffs () const
bool isMemOffs16_8 () const
bool isMemOffs16_16 () const
bool isMemOffs16_32 () const
bool isMemOffs32_8 () const
bool isMemOffs32_16 () const
bool isMemOffs32_32 () const
bool isMemOffs32_64 () const
bool isMemOffs64_8 () const
bool isMemOffs64_16 () const
bool isMemOffs64_32 () const
bool isMemOffs64_64 () const
bool isPrefix () const
bool isReg () const override
isReg - Is this a register operand?
bool isDXReg () const
bool isGR32orGR64 () const
bool isVK1Pair () const
bool isVK2Pair () const
bool isVK4Pair () const
bool isVK8Pair () const
bool isVK16Pair () const
void addExpr (MCInst &Inst, const MCExpr *Expr) const
void addRegOperands (MCInst &Inst, unsigned N) const
void addGR32orGR64Operands (MCInst &Inst, unsigned N) const
void addAVX512RCOperands (MCInst &Inst, unsigned N) const
void addImmOperands (MCInst &Inst, unsigned N) const
void addMaskPairOperands (MCInst &Inst, unsigned N) const
void addMemOperands (MCInst &Inst, unsigned N) const
void addAbsMemOperands (MCInst &Inst, unsigned N) const
void addSrcIdxOperands (MCInst &Inst, unsigned N) const
void addDstIdxOperands (MCInst &Inst, unsigned N) const
void addMemOffsOperands (MCInst &Inst, unsigned N) const
Public Member Functions inherited from llvm::MCParsedAsmOperand
virtual ~MCParsedAsmOperand ()=default
void setConstraint (StringRef C)
StringRef getConstraint ()
void setMCOperandNum (unsigned OpNum)
unsigned getMCOperandNum ()
virtual StringRef getSymName ()
virtual void * getOpDecl ()
virtual bool isToken () const =0
isToken - Is this a token operand?
virtual bool isImm () const =0
isImm - Is this an immediate operand?
virtual bool isReg () const =0
isReg - Is this a register operand?
virtual unsigned getReg () const =0
virtual bool isMem () const =0
isMem - Is this a memory operand?
virtual SMLoc getStartLoc () const =0
getStartLoc - Get the location of the first token of this operand.
virtual SMLoc getEndLoc () const =0
getEndLoc - Get the location of the last token of this operand.
virtual bool needAddressOf () const
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
virtual bool isOffsetOf () const
isOffsetOf - Do we need to emit code to get the offset of the variable, rather then the value of the variable? Only valid when parsing MS-style inline assembly.
virtual SMLoc getOffsetOfLoc () const
getOffsetOfLoc - Get the location of the offset operator.
virtual void print (raw_ostream &OS) const =0
print - Print a debug representation of the operand to the given stream.
virtual void dump () const
dump - Print to the debug stream.
Static Public Member Functions
static std::unique_ptr< X86Operand > CreateToken (StringRef Str, SMLoc Loc)
static std::unique_ptr< X86Operand > CreateReg (unsigned RegNo, SMLoc StartLoc, SMLoc EndLoc, bool AddressOf=false, SMLoc OffsetOfLoc=SMLoc(), StringRef SymName=StringRef(), void *OpDecl=nullptr)
static std::unique_ptr< X86Operand > CreateDXReg (SMLoc StartLoc, SMLoc EndLoc)
static std::unique_ptr< X86Operand > CreatePrefix (unsigned Prefixes, SMLoc StartLoc, SMLoc EndLoc)
static std::unique_ptr< X86Operand > CreateImm (const MCExpr *Val, SMLoc StartLoc, SMLoc EndLoc)
static std::unique_ptr< X86Operand > CreateMem (unsigned ModeSize, const MCExpr *Disp, SMLoc StartLoc, SMLoc EndLoc, unsigned Size=0, StringRef SymName=StringRef(), void *OpDecl=nullptr, unsigned FrontendSize=0)
Create an absolute memory operand.
static std::unique_ptr< X86Operand > CreateMem (unsigned ModeSize, unsigned SegReg, const MCExpr *Disp, unsigned BaseReg, unsigned IndexReg, unsigned Scale, SMLoc StartLoc, SMLoc EndLoc, unsigned Size=0, StringRef SymName=StringRef(), void *OpDecl=nullptr, unsigned FrontendSize=0)
Create a generalized memory operand.
Public Attributes
enum llvm::X86Operand::KindTy Kind
SMLoc StartLoc
SMLoc EndLoc
SMLoc OffsetOfLoc
StringRef SymName
void * OpDecl
bool AddressOf
union {
struct TokOp Tok
struct RegOp Reg
struct ImmOp Imm
struct MemOp Mem
struct PrefOp Pref
};
Additional Inherited Members
Protected Member Functions inherited from llvm::MCParsedAsmOperand
MCParsedAsmOperand ()=default
MCParsedAsmOperand (const MCParsedAsmOperand &RHS)=default
MCParsedAsmOperand & operator= (const MCParsedAsmOperand &)=default
Detailed Description
X86Operand - Instances of this class represent a parsed X86 machine instruction.
Definition at line 31 of file X86Operand.h.
Member Enumeration Documentation
KindTy
enum llvm::X86Operand::KindTy
Enumerator
Token
Register
Immediate
Memory
Prefix
DXRegister
Definition at line 32 of file X86Operand.h.
Constructor & Destructor Documentation
X86Operand()
llvm::X86Operand::X86Operand (KindTy K, SMLoc Start, SMLoc End) inline
Definition at line 79 of file X86Operand.h.
Member Function Documentation
addAbsMemOperands()
void llvm::X86Operand::addAbsMemOperands (MCInst & Inst, unsigned N) const inline
Definition at line 543 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), getMemDisp(), and N.
addAVX512RCOperands()
void llvm::X86Operand::addAVX512RCOperands (MCInst & Inst, unsigned N) const inline
Definition at line 500 of file X86Operand.h.
References addExpr(), assert(), getImm(), and N.
addDstIdxOperands()
void llvm::X86Operand::addDstIdxOperands (MCInst & Inst, unsigned N) const inline
Definition at line 558 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), getMemBaseReg(), and N.
addExpr()
void llvm::X86Operand::addExpr (MCInst & Inst, const MCExpr * Expr) const inline
Definition at line 479 of file X86Operand.h.
References llvm::MCInst::addOperand(), llvm::MCOperand::createExpr(), and llvm::MCOperand::createImm().
Referenced by addAVX512RCOperands(), addImmOperands(), and addMemOperands().
addGR32orGR64Operands()
void llvm::X86Operand::addGR32orGR64Operands (MCInst & Inst, unsigned N) const inline
Definition at line 492 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), contains(), llvm::MCOperand::createReg(), getReg(), llvm::getX86SubSuperRegister(), and N.
addImmOperands()
void llvm::X86Operand::addImmOperands (MCInst & Inst, unsigned N) const inline
Definition at line 505 of file X86Operand.h.
References addExpr(), assert(), getImm(), and N.
addMaskPairOperands()
void llvm::X86Operand::addMaskPairOperands (MCInst & Inst, unsigned N) const inline
Definition at line 510 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), getReg(), N, and Reg.
addMemOffsOperands()
void llvm::X86Operand::addMemOffsOperands (MCInst & Inst, unsigned N) const inline
Definition at line 563 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getMemDisp(), getMemSegReg(), and N.
addMemOperands()
void llvm::X86Operand::addMemOperands (MCInst & Inst, unsigned N) const inline
Definition at line 534 of file X86Operand.h.
References addExpr(), llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getMemBaseReg(), getMemDisp(), getMemIndexReg(), getMemScale(), getMemSegReg(), and N.
addRegOperands()
void llvm::X86Operand::addRegOperands (MCInst & Inst, unsigned N) const inline
Definition at line 487 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), getReg(), and N.
addSrcIdxOperands()
void llvm::X86Operand::addSrcIdxOperands (MCInst & Inst, unsigned N) const inline
Definition at line 552 of file X86Operand.h.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), getMemBaseReg(), getMemSegReg(), and N.
CreateDXReg()
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateDXReg (SMLoc StartLoc, SMLoc EndLoc) inline static
Definition at line 595 of file X86Operand.h.
References DXRegister, EndLoc, and StartLoc.
CreateImm()
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateImm (const MCExpr * Val, SMLoc StartLoc, SMLoc EndLoc) inline static
Definition at line 606 of file X86Operand.h.
References EndLoc, Immediate, and StartLoc.
CreateMem() [1/2]
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateMem (unsigned ModeSize, const MCExpr * Disp, SMLoc StartLoc, SMLoc EndLoc, unsigned Size = 0, StringRef SymName = StringRef(), void * OpDecl = nullptr, unsigned FrontendSize = 0) inline static
Create an absolute memory operand.
Definition at line 615 of file X86Operand.h.
References EndLoc, OpDecl, Size, StartLoc, and SymName.
CreateMem() [2/2]
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateMem (unsigned ModeSize, unsigned SegReg, const MCExpr * Disp, unsigned BaseReg, unsigned IndexReg, unsigned Scale, SMLoc StartLoc, SMLoc EndLoc, unsigned Size = 0, StringRef SymName = StringRef(), void * OpDecl = nullptr, unsigned FrontendSize = 0) inline static
Create a generalized memory operand.
Definition at line 635 of file X86Operand.h.
References assert(), EndLoc, OpDecl, Size, StartLoc, and SymName.
CreatePrefix()
static std::unique_ptr< X86Operand > llvm::X86Operand::CreatePrefix (unsigned Prefixes, SMLoc StartLoc, SMLoc EndLoc) inline static
Definition at line 600 of file X86Operand.h.
References EndLoc, Prefix, and StartLoc.
CreateReg()
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateReg (unsigned RegNo, SMLoc StartLoc, SMLoc EndLoc, bool AddressOf = false, SMLoc OffsetOfLoc = SMLoc(), StringRef SymName = StringRef(), void * OpDecl = nullptr) inline static
Definition at line 582 of file X86Operand.h.
References AddressOf, EndLoc, OffsetOfLoc, OpDecl, StartLoc, and SymName.
CreateToken()
static std::unique_ptr< X86Operand > llvm::X86Operand::CreateToken (StringRef Str, SMLoc Loc) inline static
Definition at line 573 of file X86Operand.h.
References llvm::StringRef::data(), EndLoc, llvm::SMLoc::getFromPointer(), llvm::SMLoc::getPointer(), llvm::StringRef::size(), and Token.
getEndLoc()
SMLoc llvm::X86Operand::getEndLoc () const inline override virtual
getEndLoc - Get the location of the last token of this operand.
Implements llvm::MCParsedAsmOperand.
Definition at line 89 of file X86Operand.h.
References EndLoc.
getImm()
const MCExpr * llvm::X86Operand::getImm () const inline
Definition at line 168 of file X86Operand.h.
References assert(), Imm, Immediate, Kind, and llvm::X86Operand::ImmOp::Val.
Referenced by addAVX512RCOperands(), addImmOperands(), isImmSExti16i8(), isImmSExti32i8(), isImmSExti64i32(), isImmSExti64i8(), and isImmUnsignedi8().
getLocRange()
SMRange llvm::X86Operand::getLocRange () const inline
getLocRange - Get the range between the first and last token of this operand.
Definition at line 93 of file X86Operand.h.
References EndLoc, and StartLoc.
getMemBaseReg()
unsigned llvm::X86Operand::getMemBaseReg () const inline
Definition at line 181 of file X86Operand.h.
References assert(), llvm::X86Operand::MemOp::BaseReg, Kind, and Mem.
Referenced by addDstIdxOperands(), addMemOperands(), addSrcIdxOperands(), isAbsMem(), isDstIdx(), isMemOffs(), and isSrcIdx().
getMemDisp()
const MCExpr * llvm::X86Operand::getMemDisp () const inline
Definition at line 173 of file X86Operand.h.
References assert(), llvm::X86Operand::MemOp::Disp, Kind, and Mem.
Referenced by addAbsMemOperands(), addMemOffsOperands(), addMemOperands(), isDstIdx(), and isSrcIdx().
getMemFrontendSize()
unsigned llvm::X86Operand::getMemFrontendSize () const inline
Definition at line 197 of file X86Operand.h.
References assert(), llvm::X86Operand::MemOp::FrontendSize, Kind, and Mem.
getMemIndexReg()
unsigned llvm::X86Operand::getMemIndexReg () const inline
Definition at line 185 of file X86Operand.h.
References assert(), llvm::X86Operand::MemOp::IndexReg, Kind, and Mem.
Referenced by addMemOperands(), isAbsMem(), isDstIdx(), isMemOffs(), and isSrcIdx().
getMemModeSize()
unsigned llvm::X86Operand::getMemModeSize () const inline
Definition at line 193 of file X86Operand.h.
References assert(), Kind, Mem, and llvm::X86Operand::MemOp::ModeSize.
getMemScale()
unsigned llvm::X86Operand::getMemScale () const inline
Definition at line 189 of file X86Operand.h.
References assert(), Kind, Mem, and llvm::X86Operand::MemOp::Scale.
Referenced by addMemOperands(), isAbsMem(), isDstIdx(), isMemOffs(), and isSrcIdx().
getMemSegReg()
unsigned llvm::X86Operand::getMemSegReg () const inline
Definition at line 177 of file X86Operand.h.
References assert(), Kind, Mem, and llvm::X86Operand::MemOp::SegReg.
Referenced by addMemOffsOperands(), addMemOperands(), addSrcIdxOperands(), isAbsMem(), and isDstIdx().
getOffsetOfLoc()
SMLoc llvm::X86Operand::getOffsetOfLoc () const inline override virtual
getOffsetOfLoc - Get the location of the offset operator.
Reimplemented from llvm::MCParsedAsmOperand.
Definition at line 96 of file X86Operand.h.
References OffsetOfLoc.
getOpDecl()
void * llvm::X86Operand::getOpDecl () inline override virtual
Reimplemented from llvm::MCParsedAsmOperand.
Definition at line 83 of file X86Operand.h.
References OpDecl.
getPrefix()
unsigned llvm::X86Operand::getPrefix () const inline
Definition at line 163 of file X86Operand.h.
References assert(), Kind, Pref, Prefix, and llvm::X86Operand::PrefOp::Prefixes.
getReg()
unsigned llvm::X86Operand::getReg () const inline override virtual
Implements llvm::MCParsedAsmOperand.
Definition at line 158 of file X86Operand.h.
References assert(), Kind, Reg, and llvm::X86Operand::RegOp::RegNo.
Referenced by addGR32orGR64Operands(), addMaskPairOperands(), addRegOperands(), isGR32orGR64(), isVK16Pair(), isVK1Pair(), isVK2Pair(), isVK4Pair(), and isVK8Pair().
getStartLoc()
SMLoc llvm::X86Operand::getStartLoc () const inline override virtual
getStartLoc - Get the location of the first token of this operand.
Implements llvm::MCParsedAsmOperand.
Definition at line 86 of file X86Operand.h.
References StartLoc.
getSymName()
StringRef llvm::X86Operand::getSymName () inline override virtual
Reimplemented from llvm::MCParsedAsmOperand.
Definition at line 82 of file X86Operand.h.
References SymName.
getToken()
StringRef llvm::X86Operand::getToken () const inline
Definition at line 148 of file X86Operand.h.
References assert(), llvm::X86Operand::TokOp::Data, Kind, llvm::X86Operand::TokOp::Length, Tok, and Token.
isAbsMem()
bool llvm::X86Operand::isAbsMem () const inline
Definition at line 354 of file X86Operand.h.
References getMemBaseReg(), getMemIndexReg(), getMemScale(), getMemSegReg(), and Kind.
Referenced by isAbsMem16().
isAbsMem16()
bool llvm::X86Operand::isAbsMem16 () const inline
Definition at line 362 of file X86Operand.h.
References isAbsMem(), Mem, and llvm::X86Operand::MemOp::ModeSize.
isAVX512RC()
bool llvm::X86Operand::isAVX512RC () const inline
Definition at line 358 of file X86Operand.h.
References isImm().
isDstIdx()
bool llvm::X86Operand::isDstIdx () const inline
Definition at line 385 of file X86Operand.h.
References getMemBaseReg(), getMemDisp(), getMemIndexReg(), getMemScale(), and getMemSegReg().
Referenced by isDstIdx16(), isDstIdx32(), isDstIdx64(), and isDstIdx8().
isDstIdx16()
bool llvm::X86Operand::isDstIdx16 () const inline
Definition at line 395 of file X86Operand.h.
References isDstIdx(), and isMem16().
isDstIdx32()
bool llvm::X86Operand::isDstIdx32 () const inline
Definition at line 398 of file X86Operand.h.
References isDstIdx(), and isMem32().
isDstIdx64()
bool llvm::X86Operand::isDstIdx64 () const inline
Definition at line 401 of file X86Operand.h.
References isDstIdx(), and isMem64().
isDstIdx8()
bool llvm::X86Operand::isDstIdx8 () const inline
Definition at line 392 of file X86Operand.h.
References isDstIdx(), and isMem8().
isDXReg()
bool llvm::X86Operand::isDXReg () const inline
Definition at line 446 of file X86Operand.h.
References DXRegister, and Kind.
isGR32orGR64()
bool llvm::X86Operand::isGR32orGR64 () const inline
Definition at line 448 of file X86Operand.h.
References getReg(), and Kind.
isImm()
bool llvm::X86Operand::isImm () const inline override virtual
isImm - Is this an immediate operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 204 of file X86Operand.h.
References Immediate, and Kind.
Referenced by isAVX512RC(), isImmSExti16i8(), isImmSExti32i8(), isImmSExti64i32(), isImmSExti64i8(), and isImmUnsignedi8().
isImmSExti16i8()
bool llvm::X86Operand::isImmSExti16i8 () const inline
Definition at line 206 of file X86Operand.h.
References getImm(), isImm(), and llvm::isImmSExti16i8Value().
isImmSExti32i8()
bool llvm::X86Operand::isImmSExti32i8 () const inline
Definition at line 220 of file X86Operand.h.
References getImm(), isImm(), and llvm::isImmSExti32i8Value().
isImmSExti64i32()
bool llvm::X86Operand::isImmSExti64i32 () const inline
Definition at line 248 of file X86Operand.h.
References getImm(), isImm(), and llvm::isImmSExti64i32Value().
isImmSExti64i8()
bool llvm::X86Operand::isImmSExti64i8 () const inline
Definition at line 234 of file X86Operand.h.
References getImm(), isImm(), and llvm::isImmSExti64i8Value().
isImmUnsignedi8()
bool llvm::X86Operand::isImmUnsignedi8 () const inline
Definition at line 263 of file X86Operand.h.
References getImm(), isImm(), and llvm::isImmUnsignedi8Value().
isMem()
bool llvm::X86Operand::isMem () const inline override virtual
isMem - Is this a memory operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 280 of file X86Operand.h.
References Kind, and Memory.
isMem128()
bool llvm::X86Operand::isMem128 () const inline
Definition at line 299 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isMem128_RC128(), isMem128_RC128X(), isMem128_RC256(), and isMem128_RC256X().
isMem128_RC128()
bool llvm::X86Operand::isMem128_RC128 () const inline
Definition at line 316 of file X86Operand.h.
References isMem128(), and isMemIndexReg().
isMem128_RC128X()
bool llvm::X86Operand::isMem128_RC128X () const inline
Definition at line 332 of file X86Operand.h.
References isMem128(), and isMemIndexReg().
isMem128_RC256()
bool llvm::X86Operand::isMem128_RC256 () const inline
Definition at line 319 of file X86Operand.h.
References isMem128(), and isMemIndexReg().
isMem128_RC256X()
bool llvm::X86Operand::isMem128_RC256X () const inline
Definition at line 335 of file X86Operand.h.
References isMem128(), and isMemIndexReg().
isMem16()
bool llvm::X86Operand::isMem16 () const inline
Definition at line 287 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isDstIdx16(), and isSrcIdx16().
isMem256()
bool llvm::X86Operand::isMem256 () const inline
Definition at line 302 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isMem256_RC128(), isMem256_RC128X(), isMem256_RC256(), isMem256_RC256X(), and isMem256_RC512().
isMem256_RC128()
bool llvm::X86Operand::isMem256_RC128 () const inline
Definition at line 322 of file X86Operand.h.
References isMem256(), and isMemIndexReg().
isMem256_RC128X()
bool llvm::X86Operand::isMem256_RC128X () const inline
Definition at line 338 of file X86Operand.h.
References isMem256(), and isMemIndexReg().
isMem256_RC256()
bool llvm::X86Operand::isMem256_RC256 () const inline
Definition at line 325 of file X86Operand.h.
References isMem256(), and isMemIndexReg().
isMem256_RC256X()
bool llvm::X86Operand::isMem256_RC256X () const inline
Definition at line 341 of file X86Operand.h.
References isMem256(), and isMemIndexReg().
isMem256_RC512()
bool llvm::X86Operand::isMem256_RC512 () const inline
Definition at line 344 of file X86Operand.h.
References isMem256(), and isMemIndexReg().
isMem32()
bool llvm::X86Operand::isMem32 () const inline
Definition at line 290 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isDstIdx32(), and isSrcIdx32().
isMem512()
bool llvm::X86Operand::isMem512 () const inline
Definition at line 305 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isMem512_RC256X(), and isMem512_RC512().
isMem512_RC256X()
bool llvm::X86Operand::isMem512_RC256X () const inline
Definition at line 347 of file X86Operand.h.
References isMem512(), and isMemIndexReg().
isMem512_RC512()
bool llvm::X86Operand::isMem512_RC512 () const inline
Definition at line 350 of file X86Operand.h.
References isMem512(), and isMemIndexReg().
isMem64()
bool llvm::X86Operand::isMem64 () const inline
Definition at line 293 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isDstIdx64(), isMem64_RC128(), isMem64_RC128X(), and isSrcIdx64().
isMem64_RC128()
bool llvm::X86Operand::isMem64_RC128 () const inline
Definition at line 313 of file X86Operand.h.
References isMem64(), and isMemIndexReg().
isMem64_RC128X()
bool llvm::X86Operand::isMem64_RC128X () const inline
Definition at line 329 of file X86Operand.h.
References isMem64(), and isMemIndexReg().
isMem8()
bool llvm::X86Operand::isMem8 () const inline
Definition at line 284 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
Referenced by isDstIdx8(), and isSrcIdx8().
isMem80()
bool llvm::X86Operand::isMem80 () const inline
Definition at line 296 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
isMemIndexReg()
bool llvm::X86Operand::isMemIndexReg (unsigned LowR, unsigned HighR) const inline
Definition at line 308 of file X86Operand.h.
References assert(), llvm::X86Operand::MemOp::IndexReg, Kind, and Mem.
Referenced by isMem128_RC128(), isMem128_RC128X(), isMem128_RC256(), isMem128_RC256X(), isMem256_RC128(), isMem256_RC128X(), isMem256_RC256(), isMem256_RC256X(), isMem256_RC512(), isMem512_RC256X(), isMem512_RC512(), isMem64_RC128(), and isMem64_RC128X().
isMemOffs()
bool llvm::X86Operand::isMemOffs () const inline
Definition at line 405 of file X86Operand.h.
References getMemBaseReg(), getMemIndexReg(), getMemScale(), and Kind.
Referenced by isMemOffs16_16(), isMemOffs16_32(), isMemOffs16_8(), isMemOffs32_16(), isMemOffs32_32(), isMemOffs32_64(), isMemOffs32_8(), isMemOffs64_16(), isMemOffs64_32(), isMemOffs64_64(), and isMemOffs64_8().
isMemOffs16_16()
bool llvm::X86Operand::isMemOffs16_16 () const inline
Definition at line 413 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs16_32()
bool llvm::X86Operand::isMemOffs16_32 () const inline
Definition at line 416 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs16_8()
bool llvm::X86Operand::isMemOffs16_8 () const inline
Definition at line 410 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs32_16()
bool llvm::X86Operand::isMemOffs32_16 () const inline
Definition at line 422 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs32_32()
bool llvm::X86Operand::isMemOffs32_32 () const inline
Definition at line 425 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs32_64()
bool llvm::X86Operand::isMemOffs32_64 () const inline
Definition at line 428 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs32_8()
bool llvm::X86Operand::isMemOffs32_8 () const inline
Definition at line 419 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs64_16()
bool llvm::X86Operand::isMemOffs64_16 () const inline
Definition at line 434 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs64_32()
bool llvm::X86Operand::isMemOffs64_32 () const inline
Definition at line 437 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs64_64()
bool llvm::X86Operand::isMemOffs64_64 () const inline
Definition at line 440 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemOffs64_8()
bool llvm::X86Operand::isMemOffs64_8 () const inline
Definition at line 431 of file X86Operand.h.
References isMemOffs(), Mem, llvm::X86Operand::MemOp::ModeSize, and llvm::X86Operand::MemOp::Size.
isMemUnsized()
bool llvm::X86Operand::isMemUnsized () const inline
Definition at line 281 of file X86Operand.h.
References Kind, Mem, and llvm::X86Operand::MemOp::Size.
isOffsetOf()
bool llvm::X86Operand::isOffsetOf () const inline override virtual
isOffsetOf - Do we need to emit code to get the offset of the variable, rather then the value of the variable? Only valid when parsing MS-style inline assembly.
Reimplemented from llvm::MCParsedAsmOperand.
Definition at line 272 of file X86Operand.h.
References llvm::SMLoc::getPointer(), and OffsetOfLoc.
isPrefix()
bool llvm::X86Operand::isPrefix () const inline
Definition at line 444 of file X86Operand.h.
References Kind, and Prefix.
isReg()
bool llvm::X86Operand::isReg () const inline override virtual
isReg - Is this a register operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 445 of file X86Operand.h.
References Kind, and Register.
isSrcIdx()
bool llvm::X86Operand::isSrcIdx () const inline
Definition at line 366 of file X86Operand.h.
References getMemBaseReg(), getMemDisp(), getMemIndexReg(), and getMemScale().
Referenced by isSrcIdx16(), isSrcIdx32(), isSrcIdx64(), and isSrcIdx8().
isSrcIdx16()
bool llvm::X86Operand::isSrcIdx16 () const inline
Definition at line 375 of file X86Operand.h.
References isMem16(), and isSrcIdx().
isSrcIdx32()
bool llvm::X86Operand::isSrcIdx32 () const inline
Definition at line 378 of file X86Operand.h.
References isMem32(), and isSrcIdx().
isSrcIdx64()
bool llvm::X86Operand::isSrcIdx64 () const inline
Definition at line 381 of file X86Operand.h.
References isMem64(), and isSrcIdx().
isSrcIdx8()
bool llvm::X86Operand::isSrcIdx8 () const inline
Definition at line 372 of file X86Operand.h.
References isMem8(), and isSrcIdx().
isToken()
bool llvm::X86Operand::isToken () const inline override virtual
isToken - Is this a token operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 202 of file X86Operand.h.
References Kind, and Token.
isVK16Pair()
bool llvm::X86Operand::isVK16Pair () const inline
Definition at line 474 of file X86Operand.h.
References getReg(), and Kind.
isVK1Pair()
bool llvm::X86Operand::isVK1Pair () const inline
Definition at line 454 of file X86Operand.h.
References getReg(), and Kind.
isVK2Pair()
bool llvm::X86Operand::isVK2Pair () const inline
Definition at line 459 of file X86Operand.h.
References getReg(), and Kind.
isVK4Pair()
bool llvm::X86Operand::isVK4Pair () const inline
Definition at line 464 of file X86Operand.h.
References getReg(), and Kind.
isVK8Pair()
bool llvm::X86Operand::isVK8Pair () const inline
Definition at line 469 of file X86Operand.h.
References getReg(), and Kind.
needAddressOf()
bool llvm::X86Operand::needAddressOf () const inline override virtual
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
Reimplemented from llvm::MCParsedAsmOperand.
Definition at line 276 of file X86Operand.h.
References AddressOf.
print()
void llvm::X86Operand::print (raw_ostream & OS) const inline override virtual
print - Print a debug representation of the operand to the given stream.
Implements llvm::MCParsedAsmOperand.
Definition at line 98 of file X86Operand.h.
References llvm::X86Operand::MemOp::BaseReg, llvm::MCExpr::Constant, llvm::StringRef::data(), llvm::X86Operand::TokOp::Data, llvm::X86Operand::MemOp::Disp, DXRegister, llvm::MCExpr::getKind(), llvm::MCSymbol::getName(), llvm::X86IntelInstPrinter::getRegisterName(), Imm, Immediate, llvm::X86Operand::MemOp::IndexReg, Kind, Mem, Memory, llvm::X86Operand::MemOp::ModeSize, Pref, Prefix, llvm::X86Operand::PrefOp::Prefixes, Reg, Register, llvm::X86Operand::RegOp::RegNo, llvm::X86Operand::MemOp::Scale, llvm::X86Operand::MemOp::SegReg, llvm::X86Operand::MemOp::Size, llvm::MCExpr::SymbolRef, SymName, Tok, Token, and llvm::X86Operand::ImmOp::Val.
setTokenValue()
void llvm::X86Operand::setTokenValue (StringRef Value) inline
Definition at line 152 of file X86Operand.h.
References assert(), llvm::X86Operand::TokOp::Data, Kind, llvm::X86Operand::TokOp::Length, Tok, and Token.
Member Data Documentation
union { ... } llvm::X86Operand::@505
AddressOf
bool llvm::X86Operand::AddressOf
Definition at line 38 of file X86Operand.h.
Referenced by CreateReg(), and needAddressOf().
EndLoc
SMLoc llvm::X86Operand::EndLoc
Definition at line 34 of file X86Operand.h.
Referenced by CreateDXReg(), CreateImm(), CreateMem(), CreatePrefix(), CreateReg(), CreateToken(), getEndLoc(), and getLocRange().
Imm
struct ImmOp llvm::X86Operand::Imm
Definition at line 74 of file X86Operand.h.
Referenced by getImm(), and print().
Kind
enum llvm::X86Operand::KindTy llvm::X86Operand::Kind
Referenced by getImm(), getMemBaseReg(), getMemDisp(), getMemFrontendSize(), getMemIndexReg(), getMemModeSize(), getMemScale(), getMemSegReg(), getPrefix(), getReg(), getToken(), isAbsMem(), isDXReg(), isGR32orGR64(), isImm(), isMem(), isMem128(), isMem16(), isMem256(), isMem32(), isMem512(), isMem64(), isMem8(), isMem80(), isMemIndexReg(), isMemOffs(), isMemUnsized(), isPrefix(), isReg(), isToken(), isVK16Pair(), isVK1Pair(), isVK2Pair(), isVK4Pair(), isVK8Pair(), print(), and setTokenValue().
Mem
struct MemOp llvm::X86Operand::Mem
Definition at line 75 of file X86Operand.h.
Referenced by getMemBaseReg(), getMemDisp(), getMemFrontendSize(), getMemIndexReg(), getMemModeSize(), getMemScale(), getMemSegReg(), isAbsMem16(), isMem128(), isMem16(), isMem256(), isMem32(), isMem512(), isMem64(), isMem8(), isMem80(), isMemIndexReg(), isMemOffs16_16(), isMemOffs16_32(), isMemOffs16_8(), isMemOffs32_16(), isMemOffs32_32(), isMemOffs32_64(), isMemOffs32_8(), isMemOffs64_16(), isMemOffs64_32(), isMemOffs64_64(), isMemOffs64_8(), isMemUnsized(), and print().
OffsetOfLoc
SMLoc llvm::X86Operand::OffsetOfLoc
Definition at line 35 of file X86Operand.h.
Referenced by CreateReg(), getOffsetOfLoc(), and isOffsetOf().
OpDecl
void* llvm::X86Operand::OpDecl
Definition at line 37 of file X86Operand.h.
Referenced by CreateMem(), CreateReg(), and getOpDecl().
Pref
struct PrefOp llvm::X86Operand::Pref
Definition at line 76 of file X86Operand.h.
Referenced by getPrefix(), and print().
Reg
struct RegOp llvm::X86Operand::Reg
Definition at line 73 of file X86Operand.h.
Referenced by addMaskPairOperands(), getReg(), and print().
StartLoc
SMLoc llvm::X86Operand::StartLoc
Definition at line 34 of file X86Operand.h.
Referenced by CreateDXReg(), CreateImm(), CreateMem(), CreatePrefix(), CreateReg(), getLocRange(), and getStartLoc().
SymName
StringRef llvm::X86Operand::SymName
Definition at line 36 of file X86Operand.h.
Referenced by CreateMem(), CreateReg(), getSymName(), and print().
Tok
struct TokOp llvm::X86Operand::Tok
Definition at line 72 of file X86Operand.h.
Referenced by getToken(), print(), and setTokenValue().
The documentation for this struct was generated from the following file:
lib/Target/X86/AsmParser/X86Operand.h