LLVM: INITIALIZE_PASS::InsertedPass Struct Reference
INITIALIZE_PASS::InsertedPass Struct Reference
Public Member Functions
InsertedPass (AnalysisID TargetPassID, IdentifyingPassPtr InsertedPassID, bool VerifyAfter, bool PrintAfter)
Pass * getInsertedPass () const
Public Attributes
AnalysisID TargetPassID
IdentifyingPassPtr InsertedPassID
bool VerifyAfter
bool PrintAfter
Detailed Description
Definition at line 283 of file TargetPassConfig.cpp.
Constructor & Destructor Documentation
InsertedPass()
INITIALIZE_PASS::InsertedPass::InsertedPass (AnalysisID TargetPassID, IdentifyingPassPtr InsertedPassID, bool VerifyAfter, bool PrintAfter) inline
Definition at line 289 of file TargetPassConfig.cpp.
Member Function Documentation
getInsertedPass()
Pass * INITIALIZE_PASS::InsertedPass::getInsertedPass () const inline
Definition at line 294 of file TargetPassConfig.cpp.
References assert(), llvm::Pass::createPass(), llvm::IdentifyingPassPtr::getID(), llvm::IdentifyingPassPtr::getInstance(), llvm::IdentifyingPassPtr::isInstance(), and llvm::IdentifyingPassPtr::isValid().
Member Data Documentation
InsertedPassID
IdentifyingPassPtr INITIALIZE_PASS::InsertedPass::InsertedPassID
Definition at line 285 of file TargetPassConfig.cpp.
PrintAfter
bool INITIALIZE_PASS::InsertedPass::PrintAfter
Definition at line 287 of file TargetPassConfig.cpp.
TargetPassID
AnalysisID INITIALIZE_PASS::InsertedPass::TargetPassID
Definition at line 284 of file TargetPassConfig.cpp.
VerifyAfter
bool INITIALIZE_PASS::InsertedPass::VerifyAfter
Definition at line 286 of file TargetPassConfig.cpp.
The documentation for this struct was generated from the following file:
lib/CodeGen/TargetPassConfig.cpp