LLVM: LoopFuser Struct Reference
LoopFuser Struct Reference
Public Member Functions
LoopFuser (LoopInfo &LI, DominatorTree &DT, DependenceInfo &DI, ScalarEvolution &SE, PostDominatorTree &PDT, OptimizationRemarkEmitter &ORE, const DataLayout &DL)
bool fuseLoops (Function &F)
This is the main entry point for loop fusion.
Detailed Description
Definition at line 404 of file LoopFuse.cpp.
Constructor & Destructor Documentation
LoopFuser()
LoopFuser::LoopFuser (LoopInfo & LI, DominatorTree & DT, DependenceInfo & DI, ScalarEvolution & SE, PostDominatorTree & PDT, OptimizationRemarkEmitter & ORE, const DataLayout & DL) inline
Definition at line 420 of file LoopFuse.cpp.
Member Function Documentation
fuseLoops()
bool LoopFuser::fuseLoops (Function & F) inline
This is the main entry point for loop fusion.
It will traverse the specified function and collect candidate loops to fuse, starting at the outermost nesting level and working inwards.
Definition at line 429 of file LoopFuse.cpp.
References assert(), llvm::dbgs(), LoopDepthTree::empty(), F, LoopDepthTree::getDepth(), LLVM_DEBUG, llvm::LoopInfoBase< BlockT, LoopT >::print(), printLoopVector(), LoopDepthTree::size(), VerboseFusionDebugging, llvm::ScalarEvolution::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::verify().
Referenced by llvm::LoopFusePass::run(), and LoopFuseLegacy::runOnFunction().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopFuse.cpp