LLVM: lib/Target/TargetMachineC.cpp File Reference
TargetMachineC.cpp File Reference
#include "llvm-c/Core.h"
#include "llvm-c/Target.h"
#include "llvm-c/TargetMachine.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/CodeGenCWrappers.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdlib>
#include <cstring>
Functions
static TargetMachine * unwrap (LLVMTargetMachineRef P)
static Target * unwrap (LLVMTargetRef P)
static LLVMTargetMachineRef wrap (const TargetMachine *P)
static LLVMTargetRef wrap (const Target *P)
LLVMTargetRef LLVMGetFirstTarget ()
Returns the first llvm::Target in the registered targets list.
LLVMTargetRef LLVMGetNextTarget (LLVMTargetRef T)
Returns the next llvm::Target given a previous one (or null if there's none)
LLVMTargetRef LLVMGetTargetFromName (const char *Name)
Finds the target corresponding to the given name and stores it in T.
LLVMBool LLVMGetTargetFromTriple (const char *TripleStr, LLVMTargetRef *T, char **ErrorMessage)
Finds the target corresponding to the given triple and stores it in T.
const char * LLVMGetTargetName (LLVMTargetRef T)
Returns the name of a target.
const char * LLVMGetTargetDescription (LLVMTargetRef T)
Returns the description of a target.
LLVMBool LLVMTargetHasJIT (LLVMTargetRef T)
Returns if the target has a JIT.
LLVMBool LLVMTargetHasTargetMachine (LLVMTargetRef T)
Returns if the target has a TargetMachine associated.
LLVMBool LLVMTargetHasAsmBackend (LLVMTargetRef T)
Returns if the target as an ASM backend (required for emitting output)
LLVMTargetMachineRef LLVMCreateTargetMachine (LLVMTargetRef T, const char *Triple, const char *CPU, const char *Features, LLVMCodeGenOptLevel Level, LLVMRelocMode Reloc, LLVMCodeModel CodeModel)
Creates a new llvm::TargetMachine.
void LLVMDisposeTargetMachine (LLVMTargetMachineRef T)
Dispose the LLVMTargetMachineRef instance generated by LLVMCreateTargetMachine.
LLVMTargetRef LLVMGetTargetMachineTarget (LLVMTargetMachineRef T)
Returns the Target used in a TargetMachine.
char * LLVMGetTargetMachineTriple (LLVMTargetMachineRef T)
Returns the triple used creating this target machine.
char * LLVMGetTargetMachineCPU (LLVMTargetMachineRef T)
Returns the cpu used creating this target machine.
char * LLVMGetTargetMachineFeatureString (LLVMTargetMachineRef T)
Returns the feature string used creating this target machine.
void LLVMSetTargetMachineAsmVerbosity (LLVMTargetMachineRef T, LLVMBool VerboseAsm)
Set the target machine's ASM verbosity.
LLVMTargetDataRef LLVMCreateTargetDataLayout (LLVMTargetMachineRef T)
Create a DataLayout based on the targetMachine.
static LLVMBool LLVMTargetMachineEmit (LLVMTargetMachineRef T, LLVMModuleRef M, raw_pwrite_stream &OS, LLVMCodeGenFileType codegen, char **ErrorMessage)
LLVMBool LLVMTargetMachineEmitToFile (LLVMTargetMachineRef T, LLVMModuleRef M, char *Filename, LLVMCodeGenFileType codegen, char **ErrorMessage)
Emits an asm or object file for the given module to the filename.
LLVMBool LLVMTargetMachineEmitToMemoryBuffer (LLVMTargetMachineRef T, LLVMModuleRef M, LLVMCodeGenFileType codegen, char **ErrorMessage, LLVMMemoryBufferRef *OutMemBuf)
Compile the LLVM IR stored in M and store the result in OutMemBuf.
char * LLVMGetDefaultTargetTriple (void)
Get a triple for the host machine as a string.
char * LLVMNormalizeTargetTriple (const char *triple)
Normalize a target triple.
char * LLVMGetHostCPUName (void)
Get the host CPU as a string.
char * LLVMGetHostCPUFeatures (void)
Get the host CPU's features as a string.
void LLVMAddAnalysisPasses (LLVMTargetMachineRef T, LLVMPassManagerRef PM)
Adds the target-specific analysis passes to the pass manager.
Function Documentation
LLVMAddAnalysisPasses()
void LLVMAddAnalysisPasses (LLVMTargetMachineRef T, LLVMPassManagerRef PM)
Adds the target-specific analysis passes to the pass manager.
Definition at line 268 of file TargetMachineC.cpp.
References llvm::createTargetTransformInfoWrapperPass(), and unwrap().
LLVMCreateTargetDataLayout()
LLVMTargetDataRef LLVMCreateTargetDataLayout (LLVMTargetMachineRef T)
Create a DataLayout based on the targetMachine.
Definition at line 181 of file TargetMachineC.cpp.
References unwrap(), and wrap().
LLVMCreateTargetMachine()
LLVMTargetMachineRef LLVMCreateTargetMachine (LLVMTargetRef T, const char * Triple, const char * CPU, const char * Features, LLVMCodeGenOptLevel Level, LLVMRelocMode Reloc, LLVMCodeModel CodeModel)
Creates a new llvm::TargetMachine.
See llvm::Target::createTargetMachine
Definition at line 102 of file TargetMachineC.cpp.
References llvm::CodeGenOpt::Aggressive, llvm::CodeGenOpt::Default, llvm::Reloc::DynamicNoPIC, llvm::CodeGenOpt::Less, LLVMCodeGenLevelAggressive, LLVMCodeGenLevelLess, LLVMCodeGenLevelNone, LLVMRelocDynamicNoPic, LLVMRelocPIC, LLVMRelocROPI, LLVMRelocROPI_RWPI, LLVMRelocRWPI, LLVMRelocStatic, llvm::CodeGenOpt::None, opt, llvm::Reloc::PIC_, llvm::Reloc::ROPI, llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, llvm::Reloc::Static, unwrap(), and wrap().
LLVMDisposeTargetMachine()
void LLVMDisposeTargetMachine (LLVMTargetMachineRef T)
Dispose the LLVMTargetMachineRef instance generated by LLVMCreateTargetMachine.
Definition at line 154 of file TargetMachineC.cpp.
References unwrap().
LLVMGetDefaultTargetTriple()
char * LLVMGetDefaultTargetTriple (void)
Get a triple for the host machine as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 245 of file TargetMachineC.cpp.
References llvm::c_str(), and llvm::sys::getDefaultTargetTriple().
LLVMGetFirstTarget()
LLVMTargetRef LLVMGetFirstTarget (void)
Returns the first llvm::Target in the registered targets list.
Definition at line 47 of file TargetMachineC.cpp.
References llvm::TargetRegistry::targets(), and wrap().
LLVMGetHostCPUFeatures()
char * LLVMGetHostCPUFeatures (void)
Get the host CPU's features as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 257 of file TargetMachineC.cpp.
References llvm::SubtargetFeatures::AddFeature(), F, llvm::sys::getHostCPUFeatures(), and llvm::SubtargetFeatures::getString().
LLVMGetHostCPUName()
char * LLVMGetHostCPUName (void)
Get the host CPU as a string.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 253 of file TargetMachineC.cpp.
References llvm::sys::getHostCPUName().
LLVMGetNextTarget()
LLVMTargetRef LLVMGetNextTarget (LLVMTargetRef T)
Returns the next llvm::Target given a previous one (or null if there's none)
Definition at line 55 of file TargetMachineC.cpp.
References unwrap(), and wrap().
LLVMGetTargetDescription()
const char * LLVMGetTargetDescription (LLVMTargetRef T)
Returns the description of a target.
See llvm::Target::getDescription
Definition at line 86 of file TargetMachineC.cpp.
References unwrap().
LLVMGetTargetFromName()
LLVMTargetRef LLVMGetTargetFromName (const char * Name)
Finds the target corresponding to the given name and stores it in T.
Returns 0 on success.
Definition at line 59 of file TargetMachineC.cpp.
References llvm::find_if(), I, Name, llvm::TargetRegistry::targets(), and wrap().
LLVMGetTargetFromTriple()
LLVMBool LLVMGetTargetFromTriple (const char * Triple, LLVMTargetRef * T, char ** ErrorMessage)
Finds the target corresponding to the given triple and stores it in T.
Returns 0 on success. Optionally returns any error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
Definition at line 66 of file TargetMachineC.cpp.
References llvm::TargetRegistry::lookupTarget(), and wrap().
LLVMGetTargetMachineCPU()
char * LLVMGetTargetMachineCPU (LLVMTargetMachineRef T)
Returns the cpu used creating this target machine.
See llvm::TargetMachine::getCPU. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 166 of file TargetMachineC.cpp.
References llvm::TargetMachine::getTargetCPU(), and unwrap().
LLVMGetTargetMachineFeatureString()
char * LLVMGetTargetMachineFeatureString (LLVMTargetMachineRef T)
Returns the feature string used creating this target machine.
See llvm::TargetMachine::getFeatureString. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 171 of file TargetMachineC.cpp.
References llvm::TargetMachine::getTargetFeatureString(), and unwrap().
LLVMGetTargetMachineTarget()
LLVMTargetRef LLVMGetTargetMachineTarget (LLVMTargetMachineRef T)
Returns the Target used in a TargetMachine.
Definition at line 156 of file TargetMachineC.cpp.
References llvm::TargetMachine::getTarget(), unwrap(), and wrap().
LLVMGetTargetMachineTriple()
char * LLVMGetTargetMachineTriple (LLVMTargetMachineRef T)
Returns the triple used creating this target machine.
See llvm::TargetMachine::getTriple. The result needs to be disposed with LLVMDisposeMessage.
Definition at line 161 of file TargetMachineC.cpp.
References llvm::TargetMachine::getTargetTriple(), llvm::Triple::str(), and unwrap().
LLVMGetTargetName()
const char * LLVMGetTargetName (LLVMTargetRef T)
Returns the name of a target.
See llvm::Target::getName
Definition at line 82 of file TargetMachineC.cpp.
References unwrap().
LLVMNormalizeTargetTriple()
char * LLVMNormalizeTargetTriple (const char * triple)
Normalize a target triple.
The result needs to be disposed with LLVMDisposeMessage.
Definition at line 249 of file TargetMachineC.cpp.
References llvm::c_str(), and llvm::Triple::normalize().
LLVMSetTargetMachineAsmVerbosity()
void LLVMSetTargetMachineAsmVerbosity (LLVMTargetMachineRef T, LLVMBool VerboseAsm)
Set the target machine's ASM verbosity.
Definition at line 176 of file TargetMachineC.cpp.
References llvm::MCTargetOptions::AsmVerbose, llvm::TargetOptions::MCOptions, llvm::TargetMachine::Options, and unwrap().
LLVMTargetHasAsmBackend()
LLVMBool LLVMTargetHasAsmBackend (LLVMTargetRef T)
Returns if the target as an ASM backend (required for emitting output)
Definition at line 98 of file TargetMachineC.cpp.
References unwrap().
LLVMTargetHasJIT()
LLVMBool LLVMTargetHasJIT (LLVMTargetRef T)
Returns if the target has a JIT.
Definition at line 90 of file TargetMachineC.cpp.
References unwrap().
LLVMTargetHasTargetMachine()
LLVMBool LLVMTargetHasTargetMachine (LLVMTargetRef T)
Returns if the target has a TargetMachine associated.
Definition at line 94 of file TargetMachineC.cpp.
References unwrap().
LLVMTargetMachineEmit()
static LLVMBool LLVMTargetMachineEmit (LLVMTargetMachineRef T, LLVMModuleRef M, raw_pwrite_stream & OS, LLVMCodeGenFileType codegen, char ** ErrorMessage) static
Definition at line 185 of file TargetMachineC.cpp.
References llvm::TargetMachine::CGFT_AssemblyFile, llvm::TargetMachine::CGFT_ObjectFile, codegen(), error, llvm::raw_ostream::flush(), LLVMAssemblyFile, llvm::Mod, pass, and unwrap().
Referenced by LLVMTargetMachineEmitToFile(), and LLVMTargetMachineEmitToMemoryBuffer().
LLVMTargetMachineEmitToFile()
LLVMBool LLVMTargetMachineEmitToFile (LLVMTargetMachineRef T, LLVMModuleRef M, char * Filename, LLVMCodeGenFileType codegen, char ** ErrorMessage)
Emits an asm or object file for the given module to the filename.
This wraps several c++ only classes (among them a file stream). Returns any error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
Definition at line 219 of file TargetMachineC.cpp.
References codegen(), llvm::sys::fs::F_None, llvm::raw_ostream::flush(), and LLVMTargetMachineEmit().
LLVMTargetMachineEmitToMemoryBuffer()
LLVMBool LLVMTargetMachineEmitToMemoryBuffer (LLVMTargetMachineRef T, LLVMModuleRef M, LLVMCodeGenFileType codegen, char ** ErrorMessage, LLVMMemoryBufferRef * OutMemBuf)
Compile the LLVM IR stored in M and store the result in OutMemBuf.
Definition at line 232 of file TargetMachineC.cpp.
References codegen(), llvm::Data, LLVMCreateMemoryBufferWithMemoryRangeCopy(), LLVMTargetMachineEmit(), and llvm::raw_svector_ostream::str().
unwrap() [1/2]
static TargetMachine * unwrap (LLVMTargetMachineRef P) static
Definition at line 34 of file TargetMachineC.cpp.
References P.
Referenced by LLVMAddAnalysisPasses(), LLVMCreateTargetDataLayout(), LLVMCreateTargetMachine(), LLVMDisposeTargetMachine(), LLVMGetNextTarget(), LLVMGetTargetDescription(), LLVMGetTargetMachineCPU(), LLVMGetTargetMachineFeatureString(), LLVMGetTargetMachineTarget(), LLVMGetTargetMachineTriple(), LLVMGetTargetName(), LLVMSetTargetMachineAsmVerbosity(), LLVMTargetHasAsmBackend(), LLVMTargetHasJIT(), LLVMTargetHasTargetMachine(), and LLVMTargetMachineEmit().
unwrap() [2/2]
static Target * unwrap (LLVMTargetRef P) static
Definition at line 37 of file TargetMachineC.cpp.
References P.
wrap() [1/2]
static LLVMTargetRef wrap (const Target * P) static
Definition at line 43 of file TargetMachineC.cpp.
References P.
wrap() [2/2]
static LLVMTargetMachineRef wrap (const TargetMachine * P) static
Definition at line 40 of file TargetMachineC.cpp.
References P.
Referenced by LLVMCreateTargetDataLayout(), LLVMCreateTargetMachine(), LLVMGetFirstTarget(), LLVMGetNextTarget(), LLVMGetTargetFromName(), LLVMGetTargetFromTriple(), and LLVMGetTargetMachineTarget().