LLVM: lib/DebugInfo/CodeView/TypeRecordMapping.cpp File Reference
TypeRecordMapping.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeRecordMapping.h"
Macros
#define error(X)
Functions
static Error mapNameAndUniqueName (CodeViewRecordIO &IO, StringRef &Name, StringRef &UniqueName, bool HasUniqueName)
Macro Definition Documentation
error
#define error (X)
Value:
  if (auto EC = X)                                                             \
    return EC;
Definition at line 14 of file TypeRecordMapping.cpp.
Function Documentation
mapNameAndUniqueName()
static Error mapNameAndUniqueName (CodeViewRecordIO & IO, StringRef & Name, StringRef & UniqueName, bool HasUniqueName) static
Definition at line 46 of file TypeRecordMapping.cpp.
References llvm::StringRef::drop_back(), error, llvm::codeview::HasUniqueName, llvm::codeview::CodeViewRecordIO::isWriting(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), N, Name, llvm::StringRef::size(), llvm::Error::success(), and llvm::StringRef::take_front().