LLVM: lib/Analysis/TypeMetadataUtils.cpp File Reference
TypeMetadataUtils.cpp File Reference
#include "llvm/Analysis/TypeMetadataUtils.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
Functions
static void findCallsAtConstantOffset (SmallVectorImpl< DevirtCallSite > &DevirtCalls, bool *HasNonCallUses, Value *FPtr, uint64_t Offset, const CallInst *CI, DominatorTree &DT)
static void findLoadCallsAtConstantOffset (const Module *M, SmallVectorImpl< DevirtCallSite > &DevirtCalls, Value *VPtr, int64_t Offset, const CallInst *CI, DominatorTree &DT)
Function Documentation
findCallsAtConstantOffset()
static void findCallsAtConstantOffset (SmallVectorImpl< DevirtCallSite > & DevirtCalls, bool * HasNonCallUses, Value * FPtr, uint64_t Offset, const CallInst * CI, DominatorTree & DT) static
Definition at line 24 of file TypeMetadataUtils.cpp.
References llvm::DominatorTree::dominates(), findCallsAtConstantOffset(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::uses().
Referenced by findCallsAtConstantOffset(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), and findLoadCallsAtConstantOffset().
findLoadCallsAtConstantOffset()
static void findLoadCallsAtConstantOffset (const Module * M, SmallVectorImpl< DevirtCallSite > & DevirtCalls, Value * VPtr, int64_t Offset, const CallInst * CI, DominatorTree & DT) static
Definition at line 51 of file TypeMetadataUtils.cpp.
References findCallsAtConstantOffset(), findLoadCallsAtConstantOffset(), GEP, and llvm::Value::uses().
Referenced by llvm::findDevirtualizableCallsForTypeTest(), and findLoadCallsAtConstantOffset().