LLVM: lib/MC/WasmObjectWriter.cpp File Reference
WasmObjectWriter.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWasmObjectWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/StringSaver.h"
#include <vector>
Macros
#define DEBUG_TYPE "mc"
Functions
static const MCSymbolWasm * resolveSymbol (const MCSymbolWasm &Symbol)
static void addData (SmallVectorImpl< char > &DataBytes, MCSectionWasm &DataSection)
static bool isInSymtab (const MCSymbolWasm &Sym)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mc"
Definition at line 37 of file WasmObjectWriter.cpp.
Function Documentation
addData()
static void addData (SmallVectorImpl< char > & DataBytes, MCSectionWasm & DataSection) static
Definition at line 615 of file WasmObjectWriter.cpp.
References llvm::alignTo(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::errs(), llvm::MCSection::getAlignment(), llvm::MCSectionWasm::getSectionName(), llvm::SmallVectorImpl< T >::insert(), LLVM_DEBUG, llvm_unreachable, llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorBase::size(), and Size.
isInSymtab()
static bool isInSymtab (const MCSymbolWasm & Sym) static
Definition at line 1115 of file WasmObjectWriter.cpp.
References llvm::StringRef::empty(), llvm::MCSymbol::getName(), llvm::MCSymbolWasm::getSize(), llvm::MCSymbolWasm::isComdat(), llvm::MCSymbolWasm::isData(), llvm::MCSymbol::isDefined(), llvm::MCSymbolWasm::isSection(), llvm::MCSymbol::isTemporary(), and llvm::MCSymbol::isUsedInReloc().
resolveSymbol()
static const MCSymbolWasm * resolveSymbol (const MCSymbolWasm & Symbol) static
Definition at line 551 of file WasmObjectWriter.cpp.