LLVM: lib/Target/WebAssembly/WebAssemblyMCInstLower.cpp File Reference
WebAssemblyMCInstLower.cpp File Reference
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
#include "WebAssemblyMCInstLower.h"
#include "WebAssemblyAsmPrinter.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyRuntimeLibcallSignatures.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Constants.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "WebAssemblyGenInstrInfo.inc"
Macros
#define GET_INSTRMAP_INFO 1
Functions
static void removeRegisterOperands (const MachineInstr *MI, MCInst &OutMI)
static wasm::ValType getType (const TargetRegisterClass *RC)
Variables
cl::opt< bool > WasmKeepRegisters ("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false))
Detailed Description
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
Definition in file WebAssemblyMCInstLower.cpp.
Macro Definition Documentation
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO 1
Definition at line 34 of file WebAssemblyMCInstLower.cpp.
Function Documentation
getType()
static wasm::ValType getType (const TargetRegisterClass * RC) static
Definition at line 167 of file WebAssemblyMCInstLower.cpp.
References llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::I32, llvm::wasm::I64, llvm_unreachable, and llvm::wasm::V128.
Referenced by allSameType(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBoolExt(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildSequence(), cloneConstantExprWithNewAddressSpace(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), ComputeNumSignBitsImpl(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantExprKeyType::create(), foldIdentityExtractShuffle(), llvm::fuzzerop::gepDescriptor(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::getActualReturnType(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::getCopyDeclaration(), llvm::Intrinsic::getDeclaration(), llvm::CastInst::getDestTy(), llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::MemTransferBase< BaseCL >::getSourceAddressSpace(), llvm::ConstantExpr::getWithOperands(), llvm::LandingPadInst::isCatch(), llvm::object::Elf_Sym_Impl< ELFT >::isCommon(), llvm::HexagonMCInstrInfo::isCompound(), llvm::LandingPadInst::isFilter(), llvm::HexagonMCInstrInfo::isHVX(), llvm::MachineInstr::isOperandSubregIdx(), isPointerValueDeadOnEntryToFunction(), llvm::HexagonMCInstrInfo::isVector(), LLVMBinaryGetType(), LLVMTypeOf(), llvm::WebAssemblyMCInstLower::lower(), llvm::fuzzerop::matchFirstType(), matchScalarInAggregate(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::MachineIRBuilder::materializeGEP(), PerformHeapAllocSRoA(), llvm::object::Elf_Sym_Impl< ELFT >::setBinding(), llvm::PHINode::setIncomingValue(), llvm::MemTransferBase< BaseCL >::setSource(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbol(), llvm::MemSetBase< BaseCL >::setValue(), SimplifyGEPInst(), speculatePHIs(), splitGlobal(), llvm::UpgradeIntrinsicCall(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitLandingPadInst(), and llvm::InstCombiner::visitLShr().
removeRegisterOperands()
static void removeRegisterOperands (const MachineInstr * MI, MCInst & OutMI) static
Definition at line 282 of file WebAssemblyMCInstLower.cpp.
References assert(), llvm::MCInst::erase(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), I, llvm::MachineOperand::isReg(), MI, and llvm::MCInst::setOpcode().
Referenced by llvm::WebAssemblyMCInstLower::lower().
Variable Documentation
WasmKeepRegisters
cl::opt< bool > WasmKeepRegisters("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false)) ("wasm-keep-registers" , cl::Hidden , cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only.") , cl::init(false))