LLVM: lib/Target/WebAssembly/Disassembler/WebAssemblyDisassembler.cpp File Reference
WebAssemblyDisassembler.cpp File Reference
This file is part of the WebAssembly Disassembler.
#include "MCTargetDesc/WebAssemblyInstPrinter.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/TargetRegistry.h"
#include "WebAssemblyGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "wasm-disassembler"
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
static MCDisassembler * createWebAssemblyDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
void LLVMInitializeWebAssemblyDisassembler ()
static int nextByte (ArrayRef< uint8_t > Bytes, uint64_t &Size)
static bool nextLEB (int64_t &Val, ArrayRef< uint8_t > Bytes, uint64_t &Size, bool Signed)
static bool parseLEBImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes, bool Signed)
template<typename T >
bool parseImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes)
Detailed Description
This file is part of the WebAssembly Disassembler.
It contains code to translate the data produced by the decoder into MCInsts.
Definition in file WebAssemblyDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-disassembler"
Definition at line 33 of file WebAssemblyDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 35 of file WebAssemblyDisassembler.cpp.
Function Documentation
createWebAssemblyDisassembler()
static MCDisassembler * createWebAssemblyDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 61 of file WebAssemblyDisassembler.cpp.
Referenced by LLVMInitializeWebAssemblyDisassembler().
LLVMInitializeWebAssemblyDisassembler()
void LLVMInitializeWebAssemblyDisassembler ()
Definition at line 68 of file WebAssemblyDisassembler.cpp.
References createWebAssemblyDisassembler(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), and llvm::TargetRegistry::RegisterMCDisassembler().
nextByte()
static int nextByte (ArrayRef< uint8_t > Bytes, uint64_t & Size) static
Definition at line 76 of file WebAssemblyDisassembler.cpp.
References llvm::ArrayRef< T >::size(), and Size.
Referenced by readPrefixes(), and setPrefixPresent().
nextLEB()
static bool nextLEB (int64_t & Val, ArrayRef< uint8_t > Bytes, uint64_t & Size, bool Signed) static
Definition at line 84 of file WebAssemblyDisassembler.cpp.
References llvm::ArrayRef< T >::data(), llvm::decodeSLEB128(), llvm::decodeULEB128(), N, Signed, llvm::ArrayRef< T >::size(), and Size.
Referenced by parseLEBImmediate().
parseImmediate()
template<typename T > bool parseImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes)
Definition at line 109 of file WebAssemblyDisassembler.cpp.
References llvm::MCOperand::createFPImm(), llvm::MCOperand::createImm(), llvm::ArrayRef< T >::data(), MI, llvm::ArrayRef< T >::size(), and Size.
parseLEBImmediate()
static bool parseLEBImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes, bool Signed) static
Definition at line 99 of file WebAssemblyDisassembler.cpp.
References llvm::MCOperand::createImm(), MI, nextLEB(), Signed, and Size.