LLVM: lib/MC/WinCOFFObjectWriter.cpp File Reference
WinCOFFObjectWriter.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolCOFF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWinCOFFObjectWriter.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/JamCRC.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <memory>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "WinCOFFObjectWriter"
Enumerations
enum : unsigned { Max7DecimalOffset = 9999999U }
enum : uint64_t { MaxBase64Offset = 0xFFFFFFFFFULL }
Functions
static uint32_t getAlignment (const MCSectionCOFF &Sec)
static uint64_t getSymbolValue (const MCSymbol &Symbol, const MCAsmLayout &Layout)
static void encodeBase64StringEntry (char *Buffer, uint64_t Value)
static std::time_t getTime ()
static bool isAssociative (const COFFSection &Section)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "WinCOFFObjectWriter"
Definition at line 54 of file WinCOFFObjectWriter.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
Max7DecimalOffset
Definition at line 420 of file WinCOFFObjectWriter.cpp.
anonymous enum
anonymous enum : uint64_t
Enumerator
MaxBase64Offset
Definition at line 421 of file WinCOFFObjectWriter.cpp.
Function Documentation
encodeBase64StringEntry()
static void encodeBase64StringEntry (char * Buffer, uint64_t Value) static
Definition at line 426 of file WinCOFFObjectWriter.cpp.
References assert(), Max7DecimalOffset, and MaxBase64Offset.
getAlignment()
static uint32_t getAlignment (const MCSectionCOFF & Sec) static
Definition at line 258 of file WinCOFFObjectWriter.cpp.
References llvm::MCSection::getAlignment(), llvm::COFF::IMAGE_SCN_ALIGN_1024BYTES, llvm::COFF::IMAGE_SCN_ALIGN_128BYTES, llvm::COFF::IMAGE_SCN_ALIGN_16BYTES, llvm::COFF::IMAGE_SCN_ALIGN_1BYTES, llvm::COFF::IMAGE_SCN_ALIGN_2048BYTES, llvm::COFF::IMAGE_SCN_ALIGN_256BYTES, llvm::COFF::IMAGE_SCN_ALIGN_2BYTES, llvm::COFF::IMAGE_SCN_ALIGN_32BYTES, llvm::COFF::IMAGE_SCN_ALIGN_4096BYTES, llvm::COFF::IMAGE_SCN_ALIGN_4BYTES, llvm::COFF::IMAGE_SCN_ALIGN_512BYTES, llvm::COFF::IMAGE_SCN_ALIGN_64BYTES, llvm::COFF::IMAGE_SCN_ALIGN_8192BYTES, llvm::COFF::IMAGE_SCN_ALIGN_8BYTES, and llvm_unreachable.
Referenced by llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::SystemZConstantPoolValue::getExistingMachineCPValue(), llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getOperandLatency(), and llvm::AMDGPUTargetLowering::shouldReduceLoadWidth().
getSymbolValue()
static uint64_t getSymbolValue (const MCSymbol & Symbol, const MCAsmLayout & Layout) static
Definition at line 326 of file WinCOFFObjectWriter.cpp.
References llvm::MCAsmLayout::getSymbolOffset().
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbolAddress().
getTime()
static std::time_t getTime () static
Definition at line 828 of file WinCOFFObjectWriter.cpp.
References llvm::isUInt< 32 >().
isAssociative()
static bool isAssociative (const COFFSection & Section) static
Definition at line 866 of file WinCOFFObjectWriter.cpp.
References llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE.