LLVM: lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp File Reference
X86AsmBackend.cpp File Reference
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86FixupKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
namespace CU
Functions
static unsigned getFixupKindSize (unsigned Kind)
static unsigned getRelaxedOpcodeBranch (const MCInst &Inst, bool is16BitMode)
static unsigned getRelaxedOpcodeArith (const MCInst &Inst)
static unsigned getRelaxedOpcode (const MCInst &Inst, bool is16BitMode)
Function Documentation
getFixupKindSize()
static unsigned getFixupKindSize (unsigned Kind) static
Definition at line 29 of file X86AsmBackend.cpp.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_NONE, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm::FK_PCRel_8, llvm::FK_SecRel_1, llvm::FK_SecRel_2, llvm::FK_SecRel_4, llvm::FK_SecRel_8, llvm_unreachable, llvm::X86::reloc_branch_4byte_pcrel, llvm::X86::reloc_global_offset_table, llvm::X86::reloc_global_offset_table8, llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_riprel_4byte_relax, llvm::X86::reloc_riprel_4byte_relax_rex, llvm::X86::reloc_signed_4byte, and llvm::X86::reloc_signed_4byte_relax.
getRelaxedOpcode()
static unsigned getRelaxedOpcode (const MCInst & Inst, bool is16BitMode) static
Definition at line 239 of file X86AsmBackend.cpp.
References llvm::MCInst::getOpcode(), getRelaxedOpcodeArith(), and getRelaxedOpcodeBranch().
getRelaxedOpcodeArith()
static unsigned getRelaxedOpcodeArith (const MCInst & Inst) static
Definition at line 154 of file X86AsmBackend.cpp.
References llvm::MCInst::getOpcode().
Referenced by getRelaxedOpcode().
getRelaxedOpcodeBranch()
static unsigned getRelaxedOpcodeBranch (const MCInst & Inst, bool is16BitMode) static
Definition at line 142 of file X86AsmBackend.cpp.
References llvm::MCInst::getOpcode().
Referenced by getRelaxedOpcode().