LLVM: lib/Target/AMDGPU/AMDGPUCallLowering.cpp File Reference
AMDGPUCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "AMDGPUCallLowering.h"
#include "AMDGPU.h"
#include "AMDGPUISelLowering.h"
#include "AMDGPUSubtarget.h"
#include "SIISelLowering.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/Support/LowLevelTypeImpl.h"
Functions
static Register findFirstFreeSGPR (CCState &CCInfo)
static void allocateSpecialEntryInputVGPRs (CCState &CCInfo, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static void allocateHSAUserSGPRs (CCState &CCInfo, MachineIRBuilder &MIRBuilder, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static void allocateSystemSGPRs (CCState &CCInfo, MachineFunction &MF, SIMachineFunctionInfo &Info, CallingConv::ID CallConv, bool IsShader)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file AMDGPUCallLowering.cpp.
Function Documentation
allocateHSAUserSGPRs()
static void allocateHSAUserSGPRs (CCState & CCInfo, MachineIRBuilder & MIRBuilder, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 202 of file AMDGPUCallLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), llvm::MachineIRBuilder::buildCopy(), AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineIRBuilder::getMBB(), llvm::MachineFunction::getRegInfo(), Info, MRI, and TRI.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
allocateSpecialEntryInputVGPRs()
static void allocateSpecialEntryInputVGPRs (CCState & CCInfo, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 169 of file AMDGPUCallLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), llvm::ArgDescriptor::createRegister(), llvm::MachineFunction::getRegInfo(), Info, MRI, and llvm::LLT::scalar().
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
allocateSystemSGPRs()
static void allocateSystemSGPRs (CCState & CCInfo, MachineFunction & MF, SIMachineFunctionInfo & Info, CallingConv::ID CallConv, bool IsShader) static
Definition at line 253 of file AMDGPUCallLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), findFirstFreeSGPR(), llvm::MachineFunction::getRegInfo(), Info, MRI, and llvm::LLT::scalar().
Referenced by llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
findFirstFreeSGPR()
static Register findFirstFreeSGPR (CCState & CCInfo) static
Definition at line 159 of file AMDGPUCallLowering.cpp.
References llvm::CCState::isAllocated(), and llvm_unreachable.
Referenced by allocateSystemSGPRs().