LLVM: lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp File Reference
AMDGPUInstructionSelector.cpp File Reference
This file implements the targeting of the InstructionSelector class for AMDGPU.
#include "AMDGPUInstructionSelector.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPURegisterInfo.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelectorImpl.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "AMDGPUGenGlobalISel.inc"
Macros
#define DEBUG_TYPE "amdgpu-isel"
#define GET_GLOBALISEL_IMPL
#define AMDGPUSubtarget GCNSubtarget
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Functions
static bool isSCC (Register Reg, const MachineRegisterInfo &MRI)
static int64_t getConstant (const MachineInstr *MI)
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64)
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size)
static MachineInstr * buildEXP (const TargetInstrInfo &TII, MachineInstr *Insert, unsigned Tgt, unsigned Reg0, unsigned Reg1, unsigned Reg2, unsigned Reg3, unsigned VM, bool Compr, unsigned Enabled, bool Done)
static int sizeToSubRegIndex (unsigned Size)
static bool shouldUseAndMask (unsigned Size, unsigned &Mask)
static bool isConstant (const MachineInstr &MI)
static bool signBitIsZero (const MachineOperand &Op, const MachineRegisterInfo &MRI)
static bool isStackPtrRelative (const MachinePointerInfo &PtrInfo)
Detailed Description
This file implements the targeting of the InstructionSelector class for AMDGPU.
Todo:
This should be generated by TableGen.
Definition in file AMDGPUInstructionSelector.cpp.
Macro Definition Documentation
AMDGPUSubtarget
#define AMDGPUSubtarget GCNSubtarget
Definition at line 41 of file AMDGPUInstructionSelector.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-isel"
Definition at line 35 of file AMDGPUInstructionSelector.cpp.
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 40 of file AMDGPUInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Function Documentation
buildEXP()
static MachineInstr * buildEXP (const TargetInstrInfo & TII, MachineInstr * Insert, unsigned Tgt, unsigned Reg0, unsigned Reg1, unsigned Reg2, unsigned Reg3, unsigned VM, bool Compr, unsigned Enabled, bool Done) static
Definition at line 722 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), Enabled, and TII.
getConstant()
static int64_t getConstant (const MachineInstr * MI) static
Definition at line 247 of file AMDGPUInstructionSelector.cpp.
References MI.
getLogicalBitOpcode()
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64) static
Definition at line 251 of file AMDGPUInstructionSelector.cpp.
References llvm_unreachable.
getV_CMPOpcode()
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size) static
Definition at line 604 of file AMDGPUInstructionSelector.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, P, and Size.
isConstant()
static bool isConstant (const MachineInstr & MI) static
Definition at line 1175 of file AMDGPUInstructionSelector.cpp.
References MI.
Referenced by llvm::MDBuilder::createTBAANode(), and llvm::HexagonInstrInfo::expandPostRAPseudo().
isSCC()
static bool isSCC (Register Reg, const MachineRegisterInfo & MRI) static
Definition at line 64 of file AMDGPUInstructionSelector.cpp.
References llvm::RegisterBank::getID(), llvm::TargetRegisterClass::getID(), llvm::LLT::getSizeInBits(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::LLT::isValid(), and MRI.
isStackPtrRelative()
static bool isStackPtrRelative (const MachinePointerInfo & PtrInfo) static
Definition at line 1606 of file AMDGPUInstructionSelector.cpp.
References llvm::PointerUnion< PTs >::dyn_cast(), llvm::PseudoSourceValue::isStack(), and llvm::MachinePointerInfo::V.
shouldUseAndMask()
static bool shouldUseAndMask (unsigned Size, unsigned & Mask) static
Returns
true if a bitmask for Size bits will be an inline immediate.
Definition at line 967 of file AMDGPUInstructionSelector.cpp.
References Size.
signBitIsZero()
static bool signBitIsZero (const MachineOperand & Op, const MachineRegisterInfo & MRI) static
Definition at line 1601 of file AMDGPUInstructionSelector.cpp.
sizeToSubRegIndex()
static int sizeToSubRegIndex (unsigned Size) static
Definition at line 896 of file AMDGPUInstructionSelector.cpp.
References llvm::PowerOf2Ceil(), Size, and sizeToSubRegIndex().
Referenced by sizeToSubRegIndex().