LLVM: lib/Analysis/Analysis.cpp File Reference
Analysis.cpp File Reference
#include "llvm-c/Analysis.h"
#include "llvm-c/Initialization.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/PassRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <cstring>
Functions
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
void LLVMInitializeIPA (LLVMPassRegistryRef R)
LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char **OutMessages)
LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
void LLVMViewFunctionCFG (LLVMValueRef Fn)
void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Function Documentation
LLVMInitializeAnalysis()
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
Definition at line 89 of file Analysis.cpp.
References unwrap().
LLVMInitializeIPA()
void LLVMInitializeIPA (LLVMPassRegistryRef R)
Definition at line 93 of file Analysis.cpp.
References unwrap().
LLVMVerifyFunction()
LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
Definition at line 118 of file Analysis.cpp.
References llvm::report_fatal_error().
LLVMVerifyModule()
LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char ** OutMessages)
Definition at line 97 of file Analysis.cpp.
References llvm::report_fatal_error(), and unwrap().
LLVMViewFunctionCFG()
void LLVMViewFunctionCFG (LLVMValueRef Fn)
Definition at line 129 of file Analysis.cpp.
References F.
LLVMViewFunctionCFGOnly()
void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Definition at line 134 of file Analysis.cpp.
References F.