LLVM: lib/Transforms/IPO/ArgumentPromotion.cpp File Reference
ArgumentPromotion.cpp File Reference
#include "llvm/Transforms/IPO/ArgumentPromotion.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <functional>
#include <iterator>
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "argpromotion"
Typedefs
using IndicesVector = std::vector< uint64_t >
A vector used to hold the indices of a single GEP instruction.
Functions
STATISTIC (NumArgumentsPromoted, "Number of pointer arguments promoted")
STATISTIC (NumAggregatesPromoted, "Number of aggregate arguments promoted")
STATISTIC (NumByValArgsPromoted, "Number of byval arguments promoted")
STATISTIC (NumArgumentsDead, "Number of dead pointer args eliminated")
static Function * doPromotion (Function *F, SmallPtrSetImpl< Argument * > &ArgsToPromote, SmallPtrSetImpl< Argument * > &ByValArgsToTransform, Optional< function_ref< void(CallSite OldCS, CallSite NewCS)> > ReplaceCallSite)
DoPromotion - This method actually performs the promotion of the specified arguments, and returns the new function.
static bool allCallersPassValidPointerForArgument (Argument *Arg, Type *Ty)
Return true if we can prove that all callees pass in a valid pointer for the specified function argument.
static bool isPrefix (const IndicesVector &Prefix, const IndicesVector &Longer)
Returns true if Prefix is a prefix of longer.
static bool prefixIn (const IndicesVector &Indices, std::set< IndicesVector > &Set)
Checks if Indices, or a prefix of Indices, is in Set.
static void markIndicesSafe (const IndicesVector &ToMark, std::set< IndicesVector > &Safe)
Mark the given indices (ToMark) as safe in the given set of indices (Safe).
static bool isSafeToPromoteArgument (Argument *Arg, Type *ByValTy, AAResults &AAR, unsigned MaxElements)
isSafeToPromoteArgument - As you might guess from the name of this method, it checks to see if it is both safe and useful to promote the argument.
static bool isDenselyPacked (Type *type, const DataLayout &DL)
Checks if a type could have padding bytes.
static bool canPaddingBeAccessed (Argument *arg)
Checks if the padding bytes of an argument could be accessed.
static bool areFunctionArgsABICompatible (const Function &F, const TargetTransformInfo &TTI, SmallPtrSetImpl< Argument * > &ArgsToPromote, SmallPtrSetImpl< Argument * > &ByValArgsToTransform)
static Function * promoteArguments (Function *F, function_ref< AAResults &(Function &F)> AARGetter, unsigned MaxElements, Optional< function_ref< void(CallSite OldCS, CallSite NewCS)> > ReplaceCallSite, const TargetTransformInfo &TTI)
PromoteArguments - This method checks the specified function to see if there are any promotable arguments and if it is safe to promote the function (for example, all callers are direct).
INITIALIZE_PASS_BEGIN (ArgPromotion, "argpromotion", "Promote 'by reference' arguments to scalars", false, false) INITIALIZE_PASS_END(ArgPromotion
Variables
argpromotion
Promote by reference arguments to scalars
Promote by reference arguments to false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "argpromotion"
Definition at line 91 of file ArgumentPromotion.cpp.
Typedef Documentation
IndicesVector
using IndicesVector = std::vector<uint64_t>
A vector used to hold the indices of a single GEP instruction.
Definition at line 99 of file ArgumentPromotion.cpp.
Function Documentation
allCallersPassValidPointerForArgument()
static bool allCallersPassValidPointerForArgument (Argument * Arg, Type * Ty) static
Return true if we can prove that all callees pass in a valid pointer for the specified function argument.
Definition at line 484 of file ArgumentPromotion.cpp.
References assert(), llvm::Argument::getArgNo(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgument(), llvm::Argument::getParent(), and llvm::isDereferenceablePointer().
Referenced by isSafeToPromoteArgument().
areFunctionArgsABICompatible()
static bool areFunctionArgsABICompatible (const Function & F, const TargetTransformInfo & TTI, SmallPtrSetImpl< Argument * > & ArgsToPromote, SmallPtrSetImpl< Argument * > & ByValArgsToTransform) static
Definition at line 845 of file ArgumentPromotion.cpp.
References llvm::TargetTransformInfo::areFunctionArgsABICompatible(), F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), and llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCaller().
Referenced by promoteArguments().
canPaddingBeAccessed()
static bool canPaddingBeAccessed (Argument * arg) static
Checks if the padding bytes of an argument could be accessed.
Definition at line 810 of file ArgumentPromotion.cpp.
References assert(), llvm::Argument::hasByValAttr(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by promoteArguments().
doPromotion()
static Function * doPromotion (Function * F, SmallPtrSetImpl< Argument * > & ArgsToPromote, SmallPtrSetImpl< Argument * > & ByValArgsToTransform, Optional< function_ref< void(CallSite OldCS, CallSite NewCS)> > ReplaceCallSite) static
DoPromotion - This method actually performs the promotion of the specified arguments, and returns the new function.
At this point, we know that it's safe to do so.
Definition at line 105 of file ArgumentPromotion.cpp.
References llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_end(), assert(), llvm::Function::begin(), llvm::Function::copyAttributesFrom(), llvm::Function::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::GetElementPtrInst::Create(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::dbgs(), llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::Instruction::eraseFromParent(), F, llvm::AttributeList::get(), llvm::FunctionType::get(), llvm::UndefValue::get(), llvm::ConstantInt::get(), llvm::Instruction::getAAMetadata(), llvm::LoadInst::getAlignment(), llvm::DataLayout::getAllocaAddrSpace(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getAttributes(), llvm::Function::getBasicBlockList(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCallingConv(), llvm::StructType::getElementType(), llvm::AttributeList::getFnAttributes(), llvm::GetElementPtrInst::getIndexedType(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::Value::getName(), llvm::StructType::getNumElements(), llvm::GetElementPtrInst::getNumIndices(), llvm::User::getNumOperands(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getOperandBundlesAsDefs(), llvm::AttributeList::getParamAttributes(), llvm::AttributeList::getRetAttributes(), llvm::FunctionType::getReturnType(), llvm::Value::getType(), I, Idx, llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_end(), llvm::Type::isStructTy(), llvm::FunctionType::isVarArg(), LLVM_DEBUG, llvm::User::op_begin(), llvm::User::op_end(), llvm::Value::replaceAllUsesWith(), RetTy, llvm::Instruction::setAAMetadata(), llvm::LoadInst::setAlignment(), llvm::Function::setAttributes(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setAttributes(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCallingConv(), llvm::Value::setName(), llvm::Function::setSubprogram(), llvm::Value::takeName(), llvm::Value::use_empty(), llvm::Instruction::user_back(), and llvm::Value::users().
Referenced by promoteArguments().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ArgPromotion , "argpromotion" , "Promote 'by reference' arguments to scalars" , false , false)
isDenselyPacked()
static bool isDenselyPacked (Type * type, const DataLayout & DL) static
Checks if a type could have padding bytes.
Definition at line 776 of file ArgumentPromotion.cpp.
References llvm::StructLayout::getElementOffsetInBits(), llvm::StructType::getElementType(), llvm::StructType::getNumElements(), llvm::DataLayout::getStructLayout(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), isDenselyPacked(), and llvm::Type::isSized().
Referenced by isDenselyPacked(), and promoteArguments().
isPrefix()
static bool isPrefix (const IndicesVector & Prefix, const IndicesVector & Longer) static
Returns true if Prefix is a prefix of longer.
That means, Longer has a size that is greater than or equal to the size of prefix, and each of the elements in Prefix is the same as the corresponding elements in Longer.
This means it also returns true when Prefix and Longer are equal!
Definition at line 507 of file ArgumentPromotion.cpp.
Referenced by markIndicesSafe(), and prefixIn().
isSafeToPromoteArgument()
static bool isSafeToPromoteArgument (Argument * Arg, Type * ByValTy, AAResults & AAR, unsigned MaxElements) static
isSafeToPromoteArgument - As you might guess from the name of this method, it checks to see if it is both safe and useful to promote the argument.
This method limits promotion of aggregates to only promote up to three elements of the aggregate in order to avoid exploding the number of arguments passed in.
Definition at line 569 of file ArgumentPromotion.cpp.
References allCallersPassValidPointerForArgument(), assert(), llvm::AAResults::canBasicBlockModify(), llvm::AAResults::canInstructionRangeModRef(), llvm::dbgs(), llvm::BasicBlock::front(), llvm::Function::front(), llvm::MemoryLocation::get(), llvm::Value::getName(), llvm::Argument::getParent(), llvm::BasicBlock::getParent(), I, isSafeToPromoteArgument(), LLVM_DEBUG, markIndicesSafe(), P, llvm::predecessors(), prefixIn(), llvm::Value::use_empty(), llvm::Value::users(), and llvm::Value::uses().
Referenced by isSafeToPromoteArgument(), and promoteArguments().
markIndicesSafe()
static void markIndicesSafe (const IndicesVector & ToMark, std::set< IndicesVector > & Safe) static
Mark the given indices (ToMark) as safe in the given set of indices (Safe).
Marking safe usually means adding ToMark to Safe. However, if there is already a prefix of Indices in Safe, Indices are implicitely marked safe already. Furthermore, any indices that Indices is itself a prefix of, are removed from Safe (since they are implicitely safe because of Indices now).
Definition at line 533 of file ArgumentPromotion.cpp.
References isPrefix().
Referenced by isSafeToPromoteArgument().
prefixIn()
static bool prefixIn (const IndicesVector & Indices, std::set< IndicesVector > & Set) static
Checks if Indices, or a prefix of Indices, is in Set.
Definition at line 514 of file ArgumentPromotion.cpp.
References isPrefix().
Referenced by isSafeToPromoteArgument().
promoteArguments()
static Function * promoteArguments (Function * F, function_ref< AAResults &(Function &F)> AARGetter, unsigned MaxElements, Optional< function_ref< void(CallSite OldCS, CallSite NewCS)> > ReplaceCallSite, const TargetTransformInfo & TTI) static
PromoteArguments - This method checks the specified function to see if there are any promotable arguments and if it is safe to promote the function (for example, all callers are direct).
If safe to promote some arguments, it calls the DoPromotion method.
Definition at line 865 of file ArgumentPromotion.cpp.
References llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::addParamAttr(), areFunctionArgsABICompatible(), canPaddingBeAccessed(), llvm::dbgs(), doPromotion(), F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), I, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isCallee(), isDenselyPacked(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isMustTailCall(), isSafeToPromoteArgument(), LLVM_DEBUG, llvm::codeview::Naked, llvm::NoAlias, and llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::removeParamAttr().
Referenced by llvm::ArgumentPromotionPass::run().
STATISTIC() [1/4]
STATISTIC (NumAggregatesPromoted , "Number of aggregate arguments promoted")
STATISTIC() [2/4]
STATISTIC (NumArgumentsDead , "Number of dead pointer args eliminated")
STATISTIC() [3/4]
STATISTIC (NumArgumentsPromoted , "Number of pointer arguments promoted")
STATISTIC() [4/4]
STATISTIC (NumByValArgsPromoted , "Number of byval arguments promoted")
Variable Documentation
argpromotion
argpromotion
Definition at line 1108 of file ArgumentPromotion.cpp.
false
Promote by reference arguments to false
Definition at line 1109 of file ArgumentPromotion.cpp.
scalars
Promote by reference arguments to scalars
Definition at line 1109 of file ArgumentPromotion.cpp.