LLVM: lib/IR/AutoUpgrade.cpp File Reference
AutoUpgrade.cpp File Reference
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Regex.h"
#include <cstring>
Functions
static void rename (GlobalValue *GV)
static bool UpgradePTESTIntrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeX86IntrinsicsWith8BitMask (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool ShouldUpgradeX86Intrinsic (Function *F, StringRef Name)
static bool UpgradeX86IntrinsicFunction (Function *F, StringRef Name, Function *&NewFn)
static bool UpgradeIntrinsicFunction1 (Function *F, Function *&NewFn)
static Value * UpgradeX86PSLLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * UpgradeX86PSRLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * getX86MaskVec (IRBuilder<> &Builder, Value *Mask, unsigned NumElts)
static Value * EmitX86Select (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * EmitX86ScalarSelect (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * UpgradeX86ALIGNIntrinsics (IRBuilder<> &Builder, Value *Op0, Value *Op1, Value *Shift, Value *Passthru, Value *Mask, bool IsVALIGN)
static Value * UpgradeX86VPERMT2Intrinsics (IRBuilder<> &Builder, CallInst &CI, bool ZeroMask, bool IndexForm)
static Value * UpgradeX86AddSubSatIntrinsics (IRBuilder<> &Builder, CallInst &CI, bool IsSigned, bool IsAddition)
static Value * upgradeX86Rotate (IRBuilder<> &Builder, CallInst &CI, bool IsRotateRight)
static Value * upgradeX86vpcom (IRBuilder<> &Builder, CallInst &CI, unsigned Imm, bool IsSigned)
static Value * upgradeX86ConcatShift (IRBuilder<> &Builder, CallInst &CI, bool IsShiftRight, bool ZeroMask)
static Value * UpgradeMaskedStore (IRBuilder<> &Builder, Value *Ptr, Value *Data, Value *Mask, bool Aligned)
static Value * UpgradeMaskedLoad (IRBuilder<> &Builder, Value *Ptr, Value *Passthru, Value *Mask, bool Aligned)
static Value * upgradeAbs (IRBuilder<> &Builder, CallInst &CI)
static Value * upgradeIntMinMax (IRBuilder<> &Builder, CallInst &CI, ICmpInst::Predicate Pred)
static Value * upgradePMULDQ (IRBuilder<> &Builder, CallInst &CI, bool IsSigned)
static Value * ApplyX86MaskOn1BitsVec (IRBuilder<> &Builder, Value *Vec, Value *Mask)
static Value * upgradeMaskedCompare (IRBuilder<> &Builder, CallInst &CI, unsigned CC, bool Signed)
static Value * UpgradeX86MaskedShift (IRBuilder<> &Builder, CallInst &CI, Intrinsic::ID IID)
static Value * upgradeMaskedMove (IRBuilder<> &Builder, CallInst &CI)
static Value * UpgradeMaskToInt (IRBuilder<> &Builder, CallInst &CI)
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> &Builder, CallInst &CI, Value *&Rep)
static bool isOldLoopArgument (Metadata *MD)
static MDString * upgradeLoopTag (LLVMContext &C, StringRef OldTag)
static Metadata * upgradeLoopArgument (Metadata *MD)
Function Documentation
ApplyX86MaskOn1BitsVec()
static Value * ApplyX86MaskOn1BitsVec (IRBuilder<> & Builder, Value * Vec, Value * Mask) static
Definition at line 1302 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilderBase::getIntNTy(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
Referenced by llvm::UpgradeIntrinsicCall(), and upgradeMaskedCompare().
EmitX86ScalarSelect()
static Value * EmitX86ScalarSelect (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 960 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::DITypeRefArray::get(), llvm::IRBuilderBase::getInt1Ty(), llvm::Type::getIntegerBitWidth(), and llvm::Value::getType().
Referenced by llvm::UpgradeIntrinsicCall().
EmitX86Select()
static Value * EmitX86Select (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 949 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
Referenced by upgradeAbs(), upgradeAVX512MaskToSelect(), upgradeIntMinMax(), llvm::UpgradeIntrinsicCall(), upgradePMULDQ(), UpgradeX86AddSubSatIntrinsics(), UpgradeX86ALIGNIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), and UpgradeX86VPERMT2Intrinsics().
getX86MaskVec()
static Value * getX86MaskVec (IRBuilder<> & Builder, Value * Mask, unsigned NumElts) static
Definition at line 929 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::IntegerType::getBitWidth(), llvm::IRBuilderBase::getInt1Ty(), and llvm::Value::getType().
Referenced by ApplyX86MaskOn1BitsVec(), EmitX86Select(), llvm::UpgradeIntrinsicCall(), UpgradeMaskedLoad(), UpgradeMaskedStore(), and UpgradeMaskToInt().
isOldLoopArgument()
static bool isOldLoopArgument (Metadata * MD) static
Definition at line 3954 of file AutoUpgrade.cpp.
Referenced by llvm::upgradeInstructionLoopAttachment().
rename()
static void rename (GlobalValue * GV) static
Definition at line 33 of file AutoUpgrade.cpp.
References llvm::Value::getName(), and llvm::Value::setName().
Referenced by UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicFunction(), and UpgradeX86IntrinsicsWith8BitMask().
ShouldUpgradeX86Intrinsic()
static bool ShouldUpgradeX86Intrinsic (Function * F, StringRef Name) static
Definition at line 67 of file AutoUpgrade.cpp.
Referenced by UpgradeX86IntrinsicFunction().
upgradeAbs()
static Value * upgradeAbs (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1245 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateNeg(), llvm::IRBuilder< T, Inserter >::CreateSelect(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::CallBase::getNumArgOperands(), and llvm::Value::getType().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeAVX512MaskToSelect()
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> & Builder, CallInst & CI, Value *& Rep) static
Definition at line 1386 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_operands(), llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), and llvm_unreachable.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeIntMinMax()
static Value * upgradeIntMinMax (IRBuilder<> & Builder, CallInst & CI, ICmpInst::Predicate Pred) static
Definition at line 1259 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateSelect(), EmitX86Select(), llvm::CallBase::getArgOperand(), and llvm::CallBase::getNumArgOperands().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeIntrinsicFunction1()
static bool UpgradeIntrinsicFunction1 (Function * F, Function *& NewFn) static
Definition at line 490 of file AutoUpgrade.cpp.
References assert(), llvm::Function::Create(), F, llvm::FunctionType::get(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::IRBuilderBase::getInt1Ty(), llvm::Intrinsic::getName(), llvm::Type::isFloatingPointTy(), llvm::Regex::match(), llvm::None, llvm::Intrinsic::not_intrinsic, llvm::Intrinsic::remangleIntrinsicFunction(), rename(), and UpgradeX86IntrinsicFunction().
Referenced by llvm::UpgradeIntrinsicFunction().
upgradeLoopArgument()
static Metadata * upgradeLoopArgument (Metadata * MD) static
Definition at line 3978 of file AutoUpgrade.cpp.
References llvm::MDTuple::get(), I, and upgradeLoopTag().
Referenced by llvm::upgradeInstructionLoopAttachment().
upgradeLoopTag()
static MDString * upgradeLoopTag (LLVMContext & C, StringRef OldTag) static
Definition at line 3966 of file AutoUpgrade.cpp.
References assert(), and llvm::MDString::get().
Referenced by upgradeLoopArgument().
upgradeMaskedCompare()
static Value * upgradeMaskedCompare (IRBuilder<> & Builder, CallInst & CI, unsigned CC, bool Signed) static
Definition at line 1324 of file AutoUpgrade.cpp.
References ApplyX86MaskOn1BitsVec(), llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::DITypeRefArray::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::IRBuilderBase::getInt1Ty(), llvm::Constant::getNullValue(), llvm::CallBase::getNumArgOperands(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and llvm_unreachable.
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeMaskedLoad()
static Value * UpgradeMaskedLoad (IRBuilder<> & Builder, Value * Ptr, Value * Passthru, Value * Mask, bool Aligned) static
Definition at line 1225 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeMaskedMove()
static Value * upgradeMaskedMove (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1362 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateIsNotNull(), llvm::IRBuilder< T, Inserter >::CreateSelect(), and llvm::CallBase::getArgOperand().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeMaskedStore()
static Value * UpgradeMaskedStore (IRBuilder<> & Builder, Value * Ptr, Value * Data, Value * Mask, bool Aligned) static
Definition at line 1205 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::PointerType::getUnqual(), and getX86MaskVec().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeMaskToInt()
static Value * UpgradeMaskToInt (IRBuilder<> & Builder, CallInst & CI) static
Definition at line 1377 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and getX86MaskVec().
Referenced by llvm::UpgradeIntrinsicCall().
upgradePMULDQ()
static Value * upgradePMULDQ (IRBuilder<> & Builder, CallInst & CI, bool IsSigned) static
Definition at line 1272 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateMul(), llvm::IRBuilder< T, Inserter >::CreateShl(), EmitX86Select(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getNumArgOperands(), and llvm::Value::getType().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradePTESTIntrinsic()
static bool UpgradePTESTIntrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 37 of file AutoUpgrade.cpp.
References F, llvm::VectorType::get(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getFloatTy(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeX86AddSubSatIntrinsics()
static Value * UpgradeX86AddSubSatIntrinsics (IRBuilder<> & Builder, CallInst & CI, bool IsSigned, bool IsAddition) static
Definition at line 1085 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), and llvm::Value::getType().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeX86ALIGNIntrinsics()
static Value * UpgradeX86ALIGNIntrinsics (IRBuilder<> & Builder, Value * Op0, Value * Op1, Value * Shift, Value * Passthru, Value * Mask, bool IsVALIGN) static
Definition at line 978 of file AutoUpgrade.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), EmitX86Select(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), Idx, and llvm::isPowerOf2_32().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeX86ConcatShift()
static Value * upgradeX86ConcatShift (IRBuilder<> & Builder, CallInst & CI, bool IsShiftRight, bool ZeroMask) static
Definition at line 1171 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::Type::getVectorNumElements().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeX86IntrinsicFunction()
static bool UpgradeX86IntrinsicFunction (Function * F, StringRef Name, Function *& NewFn) static
Definition at line 394 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getDeclaration(), Idx, rename(), ShouldUpgradeX86Intrinsic(), UpgradePTESTIntrinsic(), and UpgradeX86IntrinsicsWith8BitMask().
Referenced by UpgradeIntrinsicFunction1().
UpgradeX86IntrinsicsWith8BitMask()
static bool UpgradeX86IntrinsicsWith8BitMask (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 53 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getDeclaration(), llvm::Type::isIntegerTy(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeX86MaskedShift()
static Value * UpgradeX86MaskedShift (IRBuilder<> & Builder, CallInst & CI, Intrinsic::ID IID) static
Definition at line 1354 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), and llvm::Instruction::getModule().
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeX86PSLLDQIntrinsics()
static Value * UpgradeX86PSLLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 863 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and Idx.
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeX86PSRLDQIntrinsics()
static Value * UpgradeX86PSRLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 897 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::VectorType::get(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and Idx.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeX86Rotate()
static Value * upgradeX86Rotate (IRBuilder<> & Builder, CallInst & CI, bool IsRotateRight) static
Definition at line 1105 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateIntCast(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::CallBase::getNumArgOperands(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::Type::getVectorNumElements().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeX86vpcom()
static Value * upgradeX86vpcom (IRBuilder<> & Builder, CallInst & CI, unsigned Imm, bool IsSigned) static
Definition at line 1132 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateICmp(), llvm::IRBuilder< T, Inserter >::CreateSExt(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), and llvm_unreachable.
Referenced by llvm::UpgradeIntrinsicCall().
UpgradeX86VPERMT2Intrinsics()
static Value * UpgradeX86VPERMT2Intrinsics (IRBuilder<> & Builder, CallInst & CI, bool ZeroMask, bool IndexForm) static
Definition at line 1024 of file AutoUpgrade.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), and llvm_unreachable.
Referenced by llvm::UpgradeIntrinsicCall().