LLVM: lib/Bitcode/Reader/BitcodeReader.cpp File Reference
BitcodeReader.cpp File Reference
#include "llvm/Bitcode/BitcodeReader.h"
#include "MetadataLoader.h"
#include "ValueList.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Bitstream/BitstreamReader.h"
#include "llvm/Bitcode/LLVMBitCodes.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GVMaterializer.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalIndirectSymbol.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <system_error>
#include <tuple>
#include <utility>
#include <vector>
Functions
static Error error (const Twine &Message)
static Error hasInvalidBitcodeHeader (BitstreamCursor &Stream)
static Expected< BitstreamCursor > initStream (MemoryBufferRef Buffer)
template<typename StrTy >
static bool convertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy &Result)
Convert a string from a record into an std::string, return true on failure.
static void stripTBAA (Module *M)
static Expected< std::string > readIdentificationBlock (BitstreamCursor &Stream)
Read the "IDENTIFICATION_BLOCK_ID" block, do some basic enforcement on the "epoch" encoded in the bitcode, and return the producer name if any.
static Expected< std::string > readIdentificationCode (BitstreamCursor &Stream)
static Expected< bool > hasObjCCategoryInModule (BitstreamCursor &Stream)
static Expected< bool > hasObjCCategory (BitstreamCursor &Stream)
static Expected< std::string > readModuleTriple (BitstreamCursor &Stream)
static Expected< std::string > readTriple (BitstreamCursor &Stream)
static bool hasImplicitComdat (size_t Val)
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val)
static FunctionSummary::FFlags getDecodedFFlags (uint64_t RawFlags)
static GlobalValueSummary::GVFlags getDecodedGVSummaryFlags (uint64_t RawFlags, uint64_t Version)
Decode the flags for GlobalValue in the summary.
static GlobalVarSummary::GVarFlags getDecodedGVarFlags (uint64_t RawFlags)
static GlobalValue::VisibilityTypes getDecodedVisibility (unsigned Val)
static GlobalValue::DLLStorageClassTypes getDecodedDLLStorageClass (unsigned Val)
static bool getDecodedDSOLocal (unsigned Val)
static GlobalVariable::ThreadLocalMode getDecodedThreadLocalMode (unsigned Val)
static GlobalVariable::UnnamedAddr getDecodedUnnamedAddrType (unsigned Val)
static int getDecodedCastOpcode (unsigned Val)
static int getDecodedUnaryOpcode (unsigned Val, Type *Ty)
static int getDecodedBinaryOpcode (unsigned Val, Type *Ty)
static AtomicRMWInst::BinOp getDecodedRMWOperation (unsigned Val)
static AtomicOrdering getDecodedOrdering (unsigned Val)
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val)
static FastMathFlags getDecodedFastMathFlags (unsigned Val)
static void upgradeDLLImportExportLinkage (GlobalValue *GV, unsigned Val)
static uint64_t getRawAttributeMask (Attribute::AttrKind Val)
static void addRawAttributeValue (AttrBuilder &B, uint64_t Val)
static void decodeLLVMAttributesForBitcode (AttrBuilder &B, uint64_t EncodedAttrs)
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer.
static Attribute::AttrKind getAttrFromCode (uint64_t Code)
static Expected< uint64_t > jumpToValueSymbolTable (uint64_t Offset, BitstreamCursor &Stream)
Helper to note and return the current location, and jump to the given offset.
static APInt readWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits)
static void inferDSOLocal (GlobalValue *GV)
static void parseWholeProgramDevirtResolutionByArg (ArrayRef< uint64_t > Record, size_t &Slot, WholeProgramDevirtResolution &Wpd)
static void parseWholeProgramDevirtResolution (ArrayRef< uint64_t > Record, StringRef Strtab, size_t &Slot, TypeIdSummary &TypeId)
static void parseTypeIdSummaryRecord (ArrayRef< uint64_t > Record, StringRef Strtab, ModuleSummaryIndex &TheIndex)
static void setSpecialRefs (std::vector< ValueInfo > &Refs, unsigned ROCnt, unsigned WOCnt)
static Expected< StringRef > readBlobInRecord (BitstreamCursor &Stream, unsigned Block, unsigned RecordID)
static Expected< bool > getEnableSplitLTOUnitFlag (BitstreamCursor &Stream, unsigned ID)
static Expected< BitcodeModule > getSingleModule (MemoryBufferRef Buffer)
Variables
static cl::opt< bool > PrintSummaryGUIDs ("print-summary-global-ids", cl::init(false), cl::Hidden, cl::desc("Print the global id for each value when reading the module summary"))
static ManagedStatic< BitcodeErrorCategoryType > ErrorCategory
Function Documentation
addRawAttributeValue()
static void addRawAttributeValue (AttrBuilder & B, uint64_t Val) static
Definition at line 1306 of file BitcodeReader.cpp.
References A, llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::Alignment, B, llvm::Attribute::EndAttrKinds, getRawAttributeMask(), I, and llvm::None.
Referenced by decodeLLVMAttributesForBitcode().
convertToString()
template<typename StrTy > static bool convertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy & Result) static
Convert a string from a record into an std::string, return true on failure.
Definition at line 151 of file BitcodeReader.cpp.
References Idx.
Referenced by hasObjCCategoryInModule(), readIdentificationBlock(), and readModuleTriple().
decodeLLVMAttributesForBitcode()
static void decodeLLVMAttributesForBitcode (AttrBuilder & B, uint64_t EncodedAttrs) static
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer.
This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
Definition at line 1332 of file BitcodeReader.cpp.
References addRawAttributeValue(), assert(), B, and llvm::isPowerOf2_32().
error()
static Error error (const Twine & Message) static
Definition at line 103 of file BitcodeReader.cpp.
References llvm::make_error_code().
getAttrFromCode()
static Attribute::AttrKind getAttrFromCode (uint64_t Code) static
Definition at line 1411 of file BitcodeReader.cpp.
References llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::Alignment, llvm::bitc::ATTR_KIND_ALIGNMENT, llvm::bitc::ATTR_KIND_ALLOC_SIZE, llvm::bitc::ATTR_KIND_ALWAYS_INLINE, llvm::bitc::ATTR_KIND_ARGMEMONLY, llvm::bitc::ATTR_KIND_BUILTIN, llvm::bitc::ATTR_KIND_BY_VAL, llvm::bitc::ATTR_KIND_COLD, llvm::bitc::ATTR_KIND_CONVERGENT, llvm::bitc::ATTR_KIND_DEREFERENCEABLE, llvm::bitc::ATTR_KIND_DEREFERENCEABLE_OR_NULL, llvm::bitc::ATTR_KIND_IMMARG, llvm::bitc::ATTR_KIND_IN_ALLOCA, llvm::bitc::ATTR_KIND_IN_REG, llvm::bitc::ATTR_KIND_INACCESSIBLEMEM_ONLY, llvm::bitc::ATTR_KIND_INACCESSIBLEMEM_OR_ARGMEMONLY, llvm::bitc::ATTR_KIND_INLINE_HINT, llvm::bitc::ATTR_KIND_JUMP_TABLE, llvm::bitc::ATTR_KIND_MIN_SIZE, llvm::bitc::ATTR_KIND_NAKED, llvm::bitc::ATTR_KIND_NEST, llvm::bitc::ATTR_KIND_NO_ALIAS, llvm::bitc::ATTR_KIND_NO_BUILTIN, llvm::bitc::ATTR_KIND_NO_CAPTURE, llvm::bitc::ATTR_KIND_NO_DUPLICATE, llvm::bitc::ATTR_KIND_NO_IMPLICIT_FLOAT, llvm::bitc::ATTR_KIND_NO_INLINE, llvm::bitc::ATTR_KIND_NO_RECURSE, llvm::bitc::ATTR_KIND_NO_RED_ZONE, llvm::bitc::ATTR_KIND_NO_RETURN, llvm::bitc::ATTR_KIND_NO_UNWIND, llvm::bitc::ATTR_KIND_NOCF_CHECK, llvm::bitc::ATTR_KIND_NOFREE, llvm::bitc::ATTR_KIND_NON_LAZY_BIND, llvm::bitc::ATTR_KIND_NON_NULL, llvm::bitc::ATTR_KIND_NOSYNC, llvm::bitc::ATTR_KIND_OPT_FOR_FUZZING, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_SIZE, llvm::bitc::ATTR_KIND_OPTIMIZE_NONE, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_RETURNED, llvm::bitc::ATTR_KIND_RETURNS_TWICE, llvm::bitc::ATTR_KIND_S_EXT, llvm::bitc::ATTR_KIND_SAFESTACK, llvm::bitc::ATTR_KIND_SANITIZE_ADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_HWADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_MEMORY, llvm::bitc::ATTR_KIND_SANITIZE_MEMTAG, llvm::bitc::ATTR_KIND_SANITIZE_THREAD, llvm::bitc::ATTR_KIND_SHADOWCALLSTACK, llvm::bitc::ATTR_KIND_SPECULATABLE, llvm::bitc::ATTR_KIND_SPECULATIVE_LOAD_HARDENING, llvm::bitc::ATTR_KIND_STACK_ALIGNMENT, llvm::bitc::ATTR_KIND_STACK_PROTECT, llvm::bitc::ATTR_KIND_STACK_PROTECT_REQ, llvm::bitc::ATTR_KIND_STACK_PROTECT_STRONG, llvm::bitc::ATTR_KIND_STRICT_FP, llvm::bitc::ATTR_KIND_STRUCT_RET, llvm::bitc::ATTR_KIND_SWIFT_ERROR, llvm::bitc::ATTR_KIND_SWIFT_SELF, llvm::bitc::ATTR_KIND_UW_TABLE, llvm::bitc::ATTR_KIND_WILLRETURN, llvm::bitc::ATTR_KIND_WRITEONLY, llvm::bitc::ATTR_KIND_Z_EXT, llvm::CallingConv::Cold, llvm::MCID::Convergent, llvm::codeview::Naked, llvm::NoAlias, llvm::FunctionSummary::FFlags::NoInline, llvm::None, llvm::FunctionSummary::FFlags::NoRecurse, llvm::GCOVOptions::NoRedZone, llvm::FunctionSummary::FFlags::ReadNone, llvm::ValueInfo::ReadOnly, llvm::CCValAssign::SExt, llvm::ValueInfo::WriteOnly, and llvm::CCValAssign::ZExt.
getDecodedBinaryOpcode()
static int getDecodedBinaryOpcode (unsigned Val, Type * Ty) static
Definition at line 1071 of file BitcodeReader.cpp.
References llvm::bitc::BINOP_ADD, llvm::bitc::BINOP_AND, llvm::bitc::BINOP_ASHR, llvm::bitc::BINOP_LSHR, llvm::bitc::BINOP_MUL, llvm::bitc::BINOP_OR, llvm::bitc::BINOP_SDIV, llvm::bitc::BINOP_SHL, llvm::bitc::BINOP_SREM, llvm::bitc::BINOP_SUB, llvm::bitc::BINOP_UDIV, llvm::bitc::BINOP_UREM, llvm::bitc::BINOP_XOR, llvm::Type::isFPOrFPVectorTy(), and llvm::Type::isIntOrIntVectorTy().
getDecodedCastOpcode()
static int getDecodedCastOpcode (unsigned Val) static
Definition at line 1038 of file BitcodeReader.cpp.
References llvm::bitc::CAST_ADDRSPACECAST, llvm::bitc::CAST_BITCAST, llvm::bitc::CAST_FPEXT, llvm::bitc::CAST_FPTOSI, llvm::bitc::CAST_FPTOUI, llvm::bitc::CAST_FPTRUNC, llvm::bitc::CAST_INTTOPTR, llvm::bitc::CAST_PTRTOINT, llvm::bitc::CAST_SEXT, llvm::bitc::CAST_SITOFP, llvm::bitc::CAST_TRUNC, llvm::bitc::CAST_UITOFP, and llvm::bitc::CAST_ZEXT.
getDecodedComdatSelectionKind()
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val) static
Definition at line 1141 of file BitcodeReader.cpp.
References llvm::Comdat::Any, llvm::bitc::COMDAT_SELECTION_KIND_ANY, llvm::bitc::COMDAT_SELECTION_KIND_EXACT_MATCH, llvm::bitc::COMDAT_SELECTION_KIND_LARGEST, llvm::bitc::COMDAT_SELECTION_KIND_NO_DUPLICATES, llvm::bitc::COMDAT_SELECTION_KIND_SAME_SIZE, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, llvm::Comdat::NoDuplicates, and llvm::Comdat::SameSize.
getDecodedDLLStorageClass()
static GlobalValue::DLLStorageClassTypes getDecodedDLLStorageClass (unsigned Val) static
Definition at line 1001 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DLLExportStorageClass, and llvm::GlobalValue::DLLImportStorageClass.
getDecodedDSOLocal()
static bool getDecodedDSOLocal (unsigned Val) static
Definition at line 1010 of file BitcodeReader.cpp.
getDecodedFastMathFlags()
static FastMathFlags getDecodedFastMathFlags (unsigned Val) static
Definition at line 1157 of file BitcodeReader.cpp.
References llvm::bitc::AllowContract, llvm::bitc::AllowReassoc, llvm::bitc::AllowReciprocal, llvm::bitc::ApproxFunc, llvm::bitc::NoInfs, llvm::bitc::NoNaNs, llvm::bitc::NoSignedZeros, llvm::FastMathFlags::setAllowContract(), llvm::FastMathFlags::setAllowReassoc(), llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setApproxFunc(), llvm::FastMathFlags::setFast(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::FastMathFlags::setNoSignedZeros(), and llvm::bitc::UnsafeAlgebra.
getDecodedFFlags()
static FunctionSummary::FFlags getDecodedFFlags (uint64_t RawFlags) static
Definition at line 956 of file BitcodeReader.cpp.
References llvm::FunctionSummary::FFlags::NoInline, llvm::FunctionSummary::FFlags::NoRecurse, llvm::FunctionSummary::FFlags::ReadNone, llvm::FunctionSummary::FFlags::ReadOnly, and llvm::FunctionSummary::FFlags::ReturnDoesNotAlias.
getDecodedGVarFlags()
static GlobalVarSummary::GVarFlags getDecodedGVarFlags (uint64_t RawFlags) static
Definition at line 986 of file BitcodeReader.cpp.
getDecodedGVSummaryFlags()
static GlobalValueSummary::GVFlags getDecodedGVSummaryFlags (uint64_t RawFlags, uint64_t Version) static
Decode the flags for GlobalValue in the summary.
Definition at line 967 of file BitcodeReader.cpp.
References Live.
getDecodedLinkage()
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val) static
Definition at line 914 of file BitcodeReader.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
getDecodedOrdering()
static AtomicOrdering getDecodedOrdering (unsigned Val) static
Definition at line 1128 of file BitcodeReader.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::Monotonic, llvm::NotAtomic, llvm::bitc::ORDERING_ACQREL, llvm::bitc::ORDERING_ACQUIRE, llvm::bitc::ORDERING_MONOTONIC, llvm::bitc::ORDERING_NOTATOMIC, llvm::bitc::ORDERING_RELEASE, llvm::bitc::ORDERING_SEQCST, llvm::bitc::ORDERING_UNORDERED, llvm::SequentiallyConsistent, and llvm::Unordered.
getDecodedRMWOperation()
static AtomicRMWInst::BinOp getDecodedRMWOperation (unsigned Val) static
Definition at line 1109 of file BitcodeReader.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::BAD_BINOP, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::bitc::RMW_ADD, llvm::bitc::RMW_AND, llvm::bitc::RMW_FADD, llvm::bitc::RMW_FSUB, llvm::bitc::RMW_MAX, llvm::bitc::RMW_MIN, llvm::bitc::RMW_NAND, llvm::bitc::RMW_OR, llvm::bitc::RMW_SUB, llvm::bitc::RMW_UMAX, llvm::bitc::RMW_UMIN, llvm::bitc::RMW_XCHG, llvm::bitc::RMW_XOR, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
getDecodedThreadLocalMode()
static GlobalVariable::ThreadLocalMode getDecodedThreadLocalMode (unsigned Val) static
Definition at line 1018 of file BitcodeReader.cpp.
getDecodedUnaryOpcode()
static int getDecodedUnaryOpcode (unsigned Val, Type * Ty) static
Definition at line 1057 of file BitcodeReader.cpp.
References llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), and llvm::bitc::UNOP_NEG.
getDecodedUnnamedAddrType()
static GlobalVariable::UnnamedAddr getDecodedUnnamedAddrType (unsigned Val) static
Definition at line 1029 of file BitcodeReader.cpp.
getDecodedVisibility()
static GlobalValue::VisibilityTypes getDecodedVisibility (unsigned Val) static
Definition at line 991 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::ProtectedVisibility.
getEnableSplitLTOUnitFlag()
static Expected< bool > getEnableSplitLTOUnitFlag (BitstreamCursor & Stream, unsigned ID) static
Definition at line 6498 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), assert(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::bitc::FS_FLAGS, llvm::Expected< T >::get(), llvm_unreachable, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::BitcodeModule::getLTOInfo().
getRawAttributeMask()
static uint64_t getRawAttributeMask (Attribute::AttrKind Val) static
Definition at line 1215 of file BitcodeReader.cpp.
References llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::Alignment, llvm::CallingConv::Cold, llvm::MCID::Convergent, llvm::Attribute::EndAttrKinds, llvm_unreachable, llvm::codeview::Naked, llvm::NoAlias, llvm::FunctionSummary::FFlags::NoInline, llvm::None, llvm::FunctionSummary::FFlags::NoRecurse, llvm::GCOVOptions::NoRedZone, llvm::FunctionSummary::FFlags::ReadNone, llvm::ValueInfo::ReadOnly, llvm::CCValAssign::SExt, llvm::ValueInfo::WriteOnly, and llvm::CCValAssign::ZExt.
Referenced by addRawAttributeValue().
getSingleModule()
static Expected< BitcodeModule > getSingleModule (MemoryBufferRef Buffer) static
Definition at line 6598 of file BitcodeReader.cpp.
References error, llvm::getBitcodeModuleList(), and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeLTOInfo(), llvm::getLazyBitcodeModule(), llvm::getModuleSummaryIndex(), llvm::parseBitcodeFile(), and llvm::readModuleSummaryIndex().
hasImplicitComdat()
static bool hasImplicitComdat (size_t Val) static
Definition at line 902 of file BitcodeReader.cpp.
hasInvalidBitcodeHeader()
static Error hasInvalidBitcodeHeader (BitstreamCursor & Stream) static
Definition at line 108 of file BitcodeReader.cpp.
References C, llvm::BitstreamCursor::canSkipToPos(), llvm::createStringError(), llvm::BitstreamCursor::Read(), and llvm::Error::success().
Referenced by initStream().
hasObjCCategory()
static Expected< bool > hasObjCCategory (BitstreamCursor & Stream) static
Definition at line 305 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, hasObjCCategoryInModule(), llvm::bitc::MODULE_BLOCK_ID, llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), and llvm::BitstreamEntry::SubBlock.
Referenced by getObjCClassCategory(), and llvm::isBitcodeContainingObjCCategory().
hasObjCCategoryInModule()
static Expected< bool > hasObjCCategoryInModule (BitstreamCursor & Stream) static
Definition at line 258 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm_unreachable, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_SECTIONNAME, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by hasObjCCategory().
inferDSOLocal()
static void inferDSOLocal (GlobalValue * GV) static
Definition at line 3077 of file BitcodeReader.cpp.
References llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasLocalLinkage(), and llvm::GlobalValue::setDSOLocal().
initStream()
static Expected< BitstreamCursor > initStream (MemoryBufferRef Buffer) static
Definition at line 129 of file BitcodeReader.cpp.
References error, llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBufferRef::getBufferStart(), hasInvalidBitcodeHeader(), llvm::isBitcodeWrapper(), and llvm::SkipBitcodeWrapperHeader().
Referenced by llvm::getBitcodeFileContents(), llvm::getBitcodeProducerString(), llvm::getBitcodeTargetTriple(), and llvm::isBitcodeContainingObjCCategory().
jumpToValueSymbolTable()
static Expected< uint64_t > jumpToValueSymbolTable (uint64_t Offset, BitstreamCursor & Stream) static
Helper to note and return the current location, and jump to the given offset.
Definition at line 2037 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), assert(), llvm::Expected< T >::get(), llvm::BitstreamCursor::GetCurrentBitNo(), llvm::BitstreamCursor::JumpToBit(), llvm::BitstreamEntry::SubBlock, llvm::Expected< T >::takeError(), and llvm::bitc::VALUE_SYMTAB_BLOCK_ID.
parseTypeIdSummaryRecord()
static void parseTypeIdSummaryRecord (ArrayRef< uint64_t > Record, StringRef Strtab, ModuleSummaryIndex & TheIndex) static
Definition at line 5667 of file BitcodeReader.cpp.
References llvm::TypeTestResolution::AlignLog2, llvm::TypeTestResolution::BitMask, llvm::StringRef::data(), llvm::ModuleSummaryIndex::getOrInsertTypeIdSummary(), llvm::TypeTestResolution::InlineBits, parseWholeProgramDevirtResolution(), llvm::TypeTestResolution::SizeM1, llvm::TypeTestResolution::SizeM1BitWidth, llvm::TypeTestResolution::TheKind, and llvm::TypeIdSummary::TTRes.
parseWholeProgramDevirtResolution()
static void parseWholeProgramDevirtResolution (ArrayRef< uint64_t > Record, StringRef Strtab, size_t & Slot, TypeIdSummary & TypeId) static
Definition at line 5651 of file BitcodeReader.cpp.
References llvm::StringRef::data(), I, parseWholeProgramDevirtResolutionByArg(), llvm::WholeProgramDevirtResolution::SingleImplName, llvm::WholeProgramDevirtResolution::TheKind, and llvm::TypeIdSummary::WPDRes.
Referenced by parseTypeIdSummaryRecord().
parseWholeProgramDevirtResolutionByArg()
static void parseWholeProgramDevirtResolutionByArg (ArrayRef< uint64_t > Record, size_t & Slot, WholeProgramDevirtResolution & Wpd) static
Definition at line 5637 of file BitcodeReader.cpp.
References B, and llvm::WholeProgramDevirtResolution::ResByArg.
Referenced by parseWholeProgramDevirtResolution().
readBlobInRecord()
static Expected< StringRef > readBlobInRecord (BitstreamCursor & Stream, unsigned Block, unsigned RecordID) static
Definition at line 6250 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeFileContents().
readIdentificationBlock()
static Expected< std::string > readIdentificationBlock (BitstreamCursor & Stream) static
Read the "IDENTIFICATION_BLOCK_ID" block, do some basic enforcement on the "epoch" encoded in the bitcode, and return the producer name if any.
Definition at line 173 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::bitc::BITCODE_CURRENT_EPOCH, convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::bitc::IDENTIFICATION_BLOCK_ID, llvm::bitc::IDENTIFICATION_CODE_EPOCH, llvm::bitc::IDENTIFICATION_CODE_STRING, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, and llvm::Expected< T >::takeError().
Referenced by readIdentificationCode().
readIdentificationCode()
static Expected< std::string > readIdentificationCode (BitstreamCursor & Stream) static
Definition at line 223 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamCursor::AtEndOfStream(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, llvm::bitc::IDENTIFICATION_BLOCK_ID, readIdentificationBlock(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), and llvm::BitstreamEntry::SubBlock.
Referenced by llvm::getBitcodeProducerString().
readModuleTriple()
static Expected< std::string > readModuleTriple (BitstreamCursor & Stream) static
Definition at line 339 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm_unreachable, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_TRIPLE, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by readTriple().
readTriple()
static Expected< std::string > readTriple (BitstreamCursor & Stream) static
Definition at line 384 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::bitc::MODULE_BLOCK_ID, readModuleTriple(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeTargetTriple().
readWideAPInt()
static APInt readWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits) static
Definition at line 2315 of file BitcodeReader.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::size(), and llvm::transform().
setSpecialRefs()
static void setSpecialRefs (std::vector< ValueInfo > & Refs, unsigned ROCnt, unsigned WOCnt) static
Definition at line 5707 of file BitcodeReader.cpp.
References assert().
stripTBAA()
static void stripTBAA (Module * M) static
Definition at line 162 of file BitcodeReader.cpp.
References F, I, instructions, and llvm::LLVMContext::MD_tbaa.
upgradeDLLImportExportLinkage()
static void upgradeDLLImportExportLinkage (GlobalValue * GV, unsigned Val) static
Definition at line 1178 of file BitcodeReader.cpp.
References llvm::GlobalValue::DLLExportStorageClass, llvm::GlobalValue::DLLImportStorageClass, and llvm::GlobalValue::setDLLStorageClass().
Variable Documentation
ErrorCategory
ManagedStatic<BitcodeErrorCategoryType> ErrorCategory static
Definition at line 6244 of file BitcodeReader.cpp.
Referenced by llvm::BitcodeErrorCategory(), and llvm::coverage::coveragemap_category().
PrintSummaryGUIDs
cl::opt< bool > PrintSummaryGUIDs("print-summary-global-ids", cl::init(false), cl::Hidden, cl::desc("Print the global id for each value when reading the module summary")) ("print-summary-global-ids" , cl::init(false) , cl::Hidden , cl::desc("Print the global id for each value when reading the module summary")) static