LLVM: llvm::DWARFDebugInfoEntry Class Reference
llvm::DWARFDebugInfoEntry Class Reference
DWARFDebugInfoEntry - A DIE with only the minimum required data.
#include "llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h"
Public Member Functions
DWARFDebugInfoEntry ()=default
bool extractFast (const DWARFUnit &U, uint32_t *OffsetPtr)
Extracts a debug info entry, which is a child of a given unit, starting at a given offset.
bool extractFast (const DWARFUnit &U, uint32_t *OffsetPtr, const DWARFDataExtractor &DebugInfoData, uint32_t UEndOffset, uint32_t Depth)
High performance extraction should use this call.
uint32_t getOffset () const
uint32_t getDepth () const
dwarf::Tag getTag () const
bool hasChildren () const
const DWARFAbbreviationDeclaration * getAbbreviationDeclarationPtr () const
Detailed Description
DWARFDebugInfoEntry - A DIE with only the minimum required data.
Definition at line 23 of file DWARFDebugInfoEntry.h.
Constructor & Destructor Documentation
DWARFDebugInfoEntry()
llvm::DWARFDebugInfoEntry::DWARFDebugInfoEntry () default
Member Function Documentation
extractFast() [1/2]
bool DWARFDebugInfoEntry::extractFast (const DWARFUnit & U, uint32_t * OffsetPtr)
Extracts a debug info entry, which is a child of a given unit, starting at a given offset.
If DIE can't be extracted, returns false and doesn't change OffsetPtr.
Definition at line 21 of file DWARFDebugInfoEntry.cpp.
References extractFast(), llvm::DWARFUnit::getDebugInfoExtractor(), and llvm::DWARFUnit::getNextUnitOffset().
Referenced by extractFast().
extractFast() [2/2]
bool DWARFDebugInfoEntry::extractFast (const DWARFUnit & U, uint32_t * OffsetPtr, const DWARFDataExtractor & DebugInfoData, uint32_t UEndOffset, uint32_t Depth)
High performance extraction should use this call.
Definition at line 28 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFAbbreviationDeclaration::attributes(), llvm::DWARFAbbreviationDeclarationSet::getAbbreviationDeclaration(), llvm::DWARFUnit::getAbbreviations(), llvm::DWARFAbbreviationDeclaration::getFixedAttributesByteSize(), llvm::DWARFUnit::getFormParams(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::isValidOffset(), and llvm::DWARFFormValue::skipValue().
getAbbreviationDeclarationPtr()
const DWARFAbbreviationDeclaration * llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr () const inline
Definition at line 55 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFDie::getAbbreviationDeclarationPtr(), llvm::DWARFUnit::getSibling(), and llvm::DWARFDie::attribute_iterator::operator++().
getDepth()
uint32_t llvm::DWARFDebugInfoEntry::getDepth () const inline
Definition at line 47 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFUnit::getLastChild(), llvm::DWARFUnit::getParent(), llvm::DWARFUnit::getPreviousSibling(), and llvm::DWARFUnit::getSibling().
getOffset()
uint32_t llvm::DWARFDebugInfoEntry::getOffset () const inline
Definition at line 46 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFUnit::getDIEForOffset(), and llvm::DWARFDie::getOffset().
getTag()
dwarf::Tag llvm::DWARFDebugInfoEntry::getTag () const inline
Definition at line 49 of file DWARFDebugInfoEntry.h.
References llvm::DWARFAbbreviationDeclaration::getTag().
hasChildren()
bool llvm::DWARFDebugInfoEntry::hasChildren () const inline
Definition at line 53 of file DWARFDebugInfoEntry.h.
References llvm::DWARFAbbreviationDeclaration::hasChildren().
Referenced by llvm::DWARFUnit::getFirstChild(), llvm::DWARFUnit::getLastChild(), and llvm::DWARFDie::hasChildren().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h
lib/DebugInfo/DWARF/DWARFDebugInfoEntry.cpp