LLVM: llvm::orc::DynamicLibrarySearchGenerator Class Reference
llvm::orc::DynamicLibrarySearchGenerator Class Reference
A utility class to expose symbols found via dlsym to the JIT.
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Types
using SymbolPredicate = std::function< bool(SymbolStringPtr)>
Public Member Functions
DynamicLibrarySearchGenerator (sys::DynamicLibrary Dylib, char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Create a DynamicLibrarySearchGenerator that searches for symbols in the given sys::DynamicLibrary.
Expected< SymbolNameSet > operator() (JITDylib &JD, const SymbolNameSet &Names)
Static Public Member Functions
static Expected< DynamicLibrarySearchGenerator > Load (const char *FileName, char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Permanently loads the library at the given path and, on success, returns a DynamicLibrarySearchGenerator that will search it for symbol definitions in the library.
static Expected< DynamicLibrarySearchGenerator > GetForCurrentProcess (char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Creates a DynamicLibrarySearchGenerator that searches for symbols in the current process.
Detailed Description
A utility class to expose symbols found via dlsym to the JIT.
If an instance of this class is attached to a JITDylib as a fallback definition generator, then any symbol found in the given DynamicLibrary that passes the 'Allow' predicate will be added to the JITDylib.
Definition at line 240 of file ExecutionUtils.h.
Member Typedef Documentation
SymbolPredicate
using llvm::orc::DynamicLibrarySearchGenerator::SymbolPredicate = std::function<bool(SymbolStringPtr)>
Definition at line 242 of file ExecutionUtils.h.
Constructor & Destructor Documentation
DynamicLibrarySearchGenerator()
llvm::orc::DynamicLibrarySearchGenerator::DynamicLibrarySearchGenerator (sys::DynamicLibrary Dylib, char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate())
Create a DynamicLibrarySearchGenerator that searches for symbols in the given sys::DynamicLibrary.
If the Allow predicate is given then only symbols matching the predicate will be searched for. If the predicate is not given then all symbols will be searched for.
Definition at line 176 of file ExecutionUtils.cpp.
Member Function Documentation
GetForCurrentProcess()
static Expected< DynamicLibrarySearchGenerator > llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess (char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate()) inline static
Creates a DynamicLibrarySearchGenerator that searches for symbols in the current process.
Definition at line 263 of file ExecutionUtils.h.
References GlobalPrefix, and Load().
Load()
Expected< DynamicLibrarySearchGenerator > llvm::orc::DynamicLibrarySearchGenerator::Load (const char * FileName, char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate()) static
Permanently loads the library at the given path and, on success, returns a DynamicLibrarySearchGenerator that will search it for symbol definitions in the library.
On failure returns the reason the library failed to load.
Definition at line 182 of file ExecutionUtils.cpp.
References llvm::sys::DynamicLibrary::getPermanentLibrary(), GlobalPrefix, and llvm::inconvertibleErrorCode().
Referenced by GetForCurrentProcess().
operator()()
Expected< SymbolNameSet > llvm::orc::DynamicLibrarySearchGenerator::operator() (JITDylib & JD, const SymbolNameSet & Names)
Definition at line 193 of file ExecutionUtils.cpp.
References llvm::orc::absoluteSymbols(), llvm::cantFail(), llvm::orc::JITDylib::define(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::JITSymbolFlags::Exported, llvm::sys::DynamicLibrary::getAddressOfSymbol(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and Name.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp