LLVM: llvm::AttributeSetNode Class Reference
llvm::AttributeSetNode Class Reference final
#include "IR/AttributeImpl.h"
Public Types
using iterator = const Attribute *
Public Member Functions
AttributeSetNode (const AttributeSetNode &)=delete
AttributeSetNode & operator= (const AttributeSetNode &)=delete
void operator delete (void *p)
unsigned getNumAttributes () const
Return the number of attributes this AttributeList contains.
bool hasAttribute (Attribute::AttrKind Kind) const
bool hasAttribute (StringRef Kind) const
bool hasAttributes () const
Attribute getAttribute (Attribute::AttrKind Kind) const
Attribute getAttribute (StringRef Kind) const
unsigned getAlignment () const
unsigned getStackAlignment () const
uint64_t getDereferenceableBytes () const
uint64_t getDereferenceableOrNullBytes () const
std::pair< unsigned, Optional< unsigned > > getAllocSizeArgs () const
std::string getAsString (bool InAttrGrp) const
Type * getByValType () const
iterator begin () const
iterator end () const
void Profile (FoldingSetNodeID &ID) const
Static Public Member Functions
static AttributeSetNode * get (LLVMContext &C, const AttrBuilder &B)
static AttributeSetNode * get (LLVMContext &C, ArrayRef< Attribute > Attrs)
static void Profile (FoldingSetNodeID &ID, ArrayRef< Attribute > AttrList)
Detailed Description
Definition at line 177 of file AttributeImpl.h.
Member Typedef Documentation
iterator
using llvm::AttributeSetNode::iterator = const Attribute *
Definition at line 219 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeSetNode()
llvm::AttributeSetNode::AttributeSetNode (const AttributeSetNode &) delete
Member Function Documentation
begin()
iterator llvm::AttributeSetNode::begin () const inline
Definition at line 221 of file AttributeImpl.h.
Referenced by end(), getAsString(), and Profile().
end()
iterator llvm::AttributeSetNode::end () const inline
Definition at line 222 of file AttributeImpl.h.
References begin().
Referenced by getAsString(), and Profile().
get() [1/2]
AttributeSetNode * AttributeSetNode::get (LLVMContext & C, ArrayRef< Attribute > Attrs) static
Definition at line 739 of file Attributes.cpp.
References llvm::LLVMContextImpl::AttrsSetNodes.
get() [2/2]
AttributeSetNode * AttributeSetNode::get (LLVMContext & C, const AttrBuilder & B) static
Definition at line 771 of file Attributes.cpp.
References get().
Referenced by get().
getAlignment()
unsigned AttributeSetNode::getAlignment () const
Definition at line 839 of file Attributes.cpp.
References I.
getAllocSizeArgs()
std::pair< unsigned, Optional< unsigned > > AttributeSetNode::getAllocSizeArgs () const
Definition at line 875 of file Attributes.cpp.
References I.
getAsString()
std::string AttributeSetNode::getAsString (bool InAttrGrp) const
Definition at line 882 of file Attributes.cpp.
References begin(), end(), and I.
getAttribute() [1/2]
Attribute AttributeSetNode::getAttribute (Attribute::AttrKind Kind) const
Definition at line 823 of file Attributes.cpp.
References hasAttribute(), and I.
getAttribute() [2/2]
Attribute AttributeSetNode::getAttribute (StringRef Kind) const
Definition at line 832 of file Attributes.cpp.
References I.
getByValType()
Type * AttributeSetNode::getByValType () const
Definition at line 853 of file Attributes.cpp.
References I.
getDereferenceableBytes()
uint64_t AttributeSetNode::getDereferenceableBytes () const
Definition at line 860 of file Attributes.cpp.
References I.
getDereferenceableOrNullBytes()
uint64_t AttributeSetNode::getDereferenceableOrNullBytes () const
Definition at line 867 of file Attributes.cpp.
References I.
getNumAttributes()
unsigned llvm::AttributeSetNode::getNumAttributes () const inline
Return the number of attributes this AttributeList contains.
Definition at line 200 of file AttributeImpl.h.
getStackAlignment()
unsigned AttributeSetNode::getStackAlignment () const
Definition at line 846 of file Attributes.cpp.
References I.
hasAttribute() [1/2]
bool llvm::AttributeSetNode::hasAttribute (Attribute::AttrKind Kind) const inline
Definition at line 202 of file AttributeImpl.h.
Referenced by getAttribute().
hasAttribute() [2/2]
bool AttributeSetNode::hasAttribute (StringRef Kind) const
Definition at line 816 of file Attributes.cpp.
References I.
hasAttributes()
bool llvm::AttributeSetNode::hasAttributes () const inline
Definition at line 206 of file AttributeImpl.h.
operator delete()
void llvm::AttributeSetNode::operator delete (void * p) inline
Definition at line 193 of file AttributeImpl.h.
operator=()
AttributeSetNode & llvm::AttributeSetNode::operator= (const AttributeSetNode &) delete
Profile() [1/2]
void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID) const inline
Definition at line 224 of file AttributeImpl.h.
References begin(), end(), and Profile().
Referenced by Profile().
Profile() [2/2]
static void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID, ArrayRef< Attribute > AttrList) inline static
Definition at line 228 of file AttributeImpl.h.
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp