LLVM: llvm::TargetLibraryInfo Class Reference
llvm::TargetLibraryInfo Class Reference
Provides information about what library functions are available for the current target.
#include "llvm/Analysis/TargetLibraryInfo.h"
Public Member Functions
TargetLibraryInfo (const TargetLibraryInfoImpl &Impl)
TargetLibraryInfo (const TargetLibraryInfo &TLI)
TargetLibraryInfo (TargetLibraryInfo &&TLI)
TargetLibraryInfo & operator= (const TargetLibraryInfo &TLI)
TargetLibraryInfo & operator= (TargetLibraryInfo &&TLI)
bool getLibFunc (StringRef funcName, LibFunc &F) const
Searches for a particular function name.
bool getLibFunc (const Function &FDecl, LibFunc &F) const
bool getLibFunc (ImmutableCallSite CS, LibFunc &F) const
If a callsite does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
bool has (LibFunc F) const
Tests whether a library function is available.
bool isFunctionVectorizable (StringRef F, unsigned VF) const
bool isFunctionVectorizable (StringRef F) const
StringRef getVectorizedFunction (StringRef F, unsigned VF) const
bool hasOptimizedCodeGen (LibFunc F) const
Tests if the function is both available and a candidate for optimized code generation.
StringRef getName (LibFunc F) const
Attribute::AttrKind getExtAttrForI32Param (bool Signed=true) const
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
Attribute::AttrKind getExtAttrForI32Return (bool Signed=true) const
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
unsigned getWCharSize (const Module &M) const
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Handle invalidation from the pass manager.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Friends
class TargetLibraryAnalysis
class TargetLibraryInfoWrapperPass
Detailed Description
Provides information about what library functions are available for the current target.
This both allows optimizations to handle them specially and frontends to disable such optimizations through -fno-builtin etc.
Definition at line 206 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfo() [1/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfoImpl & Impl) inline explicit
Definition at line 213 of file TargetLibraryInfo.h.
TargetLibraryInfo() [2/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfo & TLI) inline
Definition at line 216 of file TargetLibraryInfo.h.
TargetLibraryInfo() [3/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (TargetLibraryInfo && TLI) inline
Definition at line 217 of file TargetLibraryInfo.h.
Member Function Documentation
getExtAttrForI32Param()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Param (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 305 of file TargetLibraryInfo.h.
References llvm::Attribute::None, llvm::CCValAssign::SExt, Signed, and llvm::CCValAssign::ZExt.
Referenced by getOrInsertValueProfilingCall().
getExtAttrForI32Return()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Return (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 316 of file TargetLibraryInfo.h.
References llvm::Attribute::None, llvm::CCValAssign::SExt, Signed, and llvm::CCValAssign::ZExt.
getLibFunc() [1/3]
bool llvm::TargetLibraryInfo::getLibFunc (const Function & FDecl, LibFunc & F) const inline
Definition at line 235 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getLibFunc().
getLibFunc() [2/3]
bool llvm::TargetLibraryInfo::getLibFunc (ImmutableCallSite CS, LibFunc & F) const inline
If a callsite does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
Definition at line 241 of file TargetLibraryInfo.h.
References F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), getLibFunc(), and llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isNoBuiltin().
getLibFunc() [3/3]
bool llvm::TargetLibraryInfo::getLibFunc (StringRef funcName, LibFunc & F) const inline
Searches for a particular function name.
If it is one of the known library functions, return true and set F to the corresponding value.
Definition at line 231 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getLibFunc().
Referenced by llvm::callsGCLeafFunction(), FindCXAAtExit(), getAllocationDataForFunction(), llvm::MemoryLocation::getForArgument(), llvm::getIntrinsicForCallSite(), getLibFunc(), llvm::inferLibFuncAttributes(), llvm::isFreeCall(), isKnownLibFunction(), isLocallyOpenedFile(), llvm::isMathLibCallNoop(), isWriteOnlyParam(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), optimizeCall(), runPartiallyInlineLibCalls(), and llvm::FastISel::selectInstruction().
getName()
StringRef llvm::TargetLibraryInfo::getName (LibFunc F) const inline
Definition at line 292 of file TargetLibraryInfo.h.
References assert(), F, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitPutChar(), llvm::emitPutS(), FindCXAAtExit(), llvm::getUnaryFloatFn(), and hasAnalyzableMemoryWrite().
getVectorizedFunction()
StringRef llvm::TargetLibraryInfo::getVectorizedFunction (StringRef F, unsigned VF) const inline
Definition at line 256 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getVectorizedFunction().
Referenced by llvm::InnerLoopVectorizer::widenInstruction().
getWCharSize()
unsigned llvm::TargetLibraryInfo::getWCharSize (const Module & M) const inline
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
This queries the 'wchar_size' metadata.
Definition at line 323 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getWCharSize().
has()
bool llvm::TargetLibraryInfo::has (LibFunc F) const inline
Tests whether a library function is available.
Definition at line 247 of file TargetLibraryInfo.h.
References F.
Referenced by llvm::callsGCLeafFunction(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), FindCXAAtExit(), getAllocationDataForFunction(), llvm::MemoryLocation::getForArgument(), hasAnalyzableMemoryWrite(), llvm::hasUnaryFloatFn(), llvm::inferLibFuncAttributes(), llvm::isFreeCall(), isLocallyOpenedFile(), isWriteOnlyParam(), llvm::LibCallSimplifier::optimizeCall(), llvm::MemCpyOptPass::runImpl(), and runPartiallyInlineLibCalls().
hasOptimizedCodeGen()
bool llvm::TargetLibraryInfo::hasOptimizedCodeGen (LibFunc F) const inline
Tests if the function is both available and a candidate for optimized code generation.
Definition at line 262 of file TargetLibraryInfo.h.
References F.
Referenced by llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), and llvm::FastISel::selectInstruction().
invalidate() [1/2]
bool llvm::TargetLibraryInfo::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Definition at line 335 of file TargetLibraryInfo.h.
invalidate() [2/2]
bool llvm::TargetLibraryInfo::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Handle invalidation from the pass manager.
If we try to invalidate this info, just return false. It cannot become invalid even if the module or function changes.
Definition at line 331 of file TargetLibraryInfo.h.
isFunctionVectorizable() [1/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F) const inline
Definition at line 253 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
isFunctionVectorizable() [2/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F, unsigned VF) const inline
Definition at line 250 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
Referenced by llvm::LoopVectorizationCostModel::getVectorCallCost(), and isKnownLibFunction().
operator=() [1/2]
TargetLibraryInfo & llvm::TargetLibraryInfo::operator= (const TargetLibraryInfo & TLI) inline
Definition at line 218 of file TargetLibraryInfo.h.
operator=() [2/2]
TargetLibraryInfo & llvm::TargetLibraryInfo::operator= (TargetLibraryInfo && TLI) inline
Definition at line 222 of file TargetLibraryInfo.h.
Friends And Related Function Documentation
TargetLibraryAnalysis
friend class TargetLibraryAnalysis friend
Definition at line 207 of file TargetLibraryInfo.h.
TargetLibraryInfoWrapperPass
friend class TargetLibraryInfoWrapperPass friend
Definition at line 208 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetLibraryInfo.h