LLVM: llvm::DIELabel Class Reference
llvm::DIELabel Class Reference
A label DIE.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIELabel (const MCSymbol *L)
const MCSymbol * getValue () const
Get MCSymbol.
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit label value.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of label value in bytes.
void print (raw_ostream &O) const
Detailed Description
A label DIE.
Definition at line 218 of file DIE.h.
Constructor & Destructor Documentation
DIELabel()
llvm::DIELabel::DIELabel (const MCSymbol * L) inline explicit
Definition at line 222 of file DIE.h.
Member Function Documentation
EmitValue()
void DIELabel::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit label value.
Definition at line 488 of file DIE.cpp.
References llvm::AsmPrinter::EmitLabelReference(), and SizeOf().
Referenced by llvm::DIEString::EmitValue().
getValue()
const MCSymbol * llvm::DIELabel::getValue () const inline
Get MCSymbol.
Definition at line 225 of file DIE.h.
print()
LLVM_DUMP_METHOD void DIELabel::print (raw_ostream & O) const
Definition at line 506 of file DIE.cpp.
References llvm::MCSymbol::getName().
SizeOf()
unsigned DIELabel::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of label value in bytes.
Definition at line 498 of file DIE.cpp.
References llvm::MCAsmInfo::getCodePointerSize(), and llvm::AsmPrinter::MAI.
Referenced by EmitValue(), and llvm::DIEString::SizeOf().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp