LLVM: llvm::StringMapEntry< ValueTy > Class Template Reference
llvm::StringMapEntry< ValueTy > Class Template Reference
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
#include "llvm/ADT/StringMap.h"
Public Member Functions
StringMapEntry (size_t strLen)
template<typename... InitTy>
StringMapEntry (size_t strLen, InitTy &&... InitVals)
StringMapEntry (StringMapEntry &E)=delete
StringRef getKey () const
const ValueTy & getValue () const
ValueTy & getValue ()
void setValue (const ValueTy &V)
const char * getKeyData () const
getKeyData - Return the start of the string data that is the key for this value.
StringRef first () const
template<typename AllocatorTy >
void Destroy (AllocatorTy &Allocator)
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
void Destroy ()
Destroy this object, releasing memory back to the malloc allocator.
Public Member Functions inherited from llvm::StringMapEntryBase
StringMapEntryBase (size_t Len)
size_t getKeyLength () const
Static Public Member Functions
template<typename AllocatorTy , typename... InitTy>
static StringMapEntry * Create (StringRef Key, AllocatorTy &Allocator, InitTy &&... InitVals)
Create a StringMapEntry for the specified key construct the value using InitiVals.
template<typename... InitType>
static StringMapEntry * Create (StringRef Key, InitType &&... InitVal)
Create - Create a StringMapEntry with normal malloc/free.
static StringMapEntry * Create (StringRef Key)
static StringMapEntry & GetStringMapEntryFromKeyData (const char *KeyData)
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Public Attributes
ValueTy second
Detailed Description
template<typename ValueTy>
class llvm::StringMapEntry< ValueTy >
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
It contains the Value itself and the key: the string length and data.
Definition at line 125 of file StringMap.h.
Constructor & Destructor Documentation
StringMapEntry() [1/3]
template<typename ValueTy > llvm::StringMapEntry< ValueTy >::StringMapEntry (size_t strLen) inline explicit
Definition at line 129 of file StringMap.h.
StringMapEntry() [2/3]
template<typename ValueTy > template<typename... InitTy> llvm::StringMapEntry< ValueTy >::StringMapEntry (size_t strLen, InitTy &&... InitVals) inline
Definition at line 132 of file StringMap.h.
StringMapEntry() [3/3]
template<typename ValueTy > llvm::StringMapEntry< ValueTy >::StringMapEntry (StringMapEntry< ValueTy > & E) delete
Member Function Documentation
Create() [1/3]
template<typename ValueTy > static StringMapEntry * llvm::StringMapEntry< ValueTy >::Create (StringRef Key) inline static
Definition at line 186 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::Create().
Create() [2/3]
template<typename ValueTy > template<typename AllocatorTy , typename... InitTy> static StringMapEntry * llvm::StringMapEntry< ValueTy >::Create (StringRef Key, AllocatorTy & Allocator, InitTy &&... InitVals) inline static
Create a StringMapEntry for the specified key construct the value using InitiVals.
Definition at line 155 of file StringMap.h.
References Allocator, assert(), and llvm::StringMapEntry< ValueTy >::getKeyData().
Referenced by llvm::StringMapEntry< ValueTy >::Create(), llvm::StringPool::intern(), llvm::StringMap< ValueTy, AllocatorTy >::StringMap(), and llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
Create() [3/3]
template<typename ValueTy > template<typename... InitType> static StringMapEntry * llvm::StringMapEntry< ValueTy >::Create (StringRef Key, InitType &&... InitVal) inline static
Create - Create a StringMapEntry with normal malloc/free.
Definition at line 181 of file StringMap.h.
References A, and llvm::StringMapEntry< ValueTy >::Create().
Destroy() [1/2]
template<typename ValueTy > void llvm::StringMapEntry< ValueTy >::Destroy () inline
Destroy this object, releasing memory back to the malloc allocator.
Definition at line 208 of file StringMap.h.
References A, and llvm::StringMapEntry< ValueTy >::Destroy().
Referenced by llvm::StringMapEntry< ValueTy >::Destroy().
Destroy() [2/2]
template<typename ValueTy > template<typename AllocatorTy > void llvm::StringMapEntry< ValueTy >::Destroy (AllocatorTy & Allocator) inline
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
Definition at line 200 of file StringMap.h.
References Allocator, and llvm::StringMapEntryBase::getKeyLength().
Referenced by llvm::PooledStringPtr::clear(), and llvm::StringMap< ValueTy, AllocatorTy >::erase().
first()
template<typename ValueTy > StringRef llvm::StringMapEntry< ValueTy >::first () const inline
Definition at line 150 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
Referenced by llvm::orc::SymbolStringPtr::operator*().
getKey()
template<typename ValueTy > StringRef llvm::StringMapEntry< ValueTy >::getKey () const inline
Definition at line 136 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
Referenced by llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::Value::getName(), llvm::StringSet< AllocatorTy >::insert(), and llvm::StringMap< ValueTy, AllocatorTy >::insert().
getKeyData()
template<typename ValueTy > const char * llvm::StringMapEntry< ValueTy >::getKeyData () const inline
getKeyData - Return the start of the string data that is the key for this value.
The string data is always stored immediately after the StringMapEntry object.
Definition at line 148 of file StringMap.h.
Referenced by llvm::PooledStringPtr::begin(), llvm::StringMapEntry< ValueTy >::Create(), llvm::PooledStringPtr::end(), llvm::StringMapEntry< ValueTy >::first(), llvm::TargetIntrinsicInfo::getIntrinsicID(), and llvm::StringMapEntry< ValueTy >::getKey().
GetStringMapEntryFromKeyData()
template<typename ValueTy > static StringMapEntry & llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromKeyData (const char * KeyData) inline static
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Definition at line 192 of file StringMap.h.
getValue() [1/2]
template<typename ValueTy > ValueTy & llvm::StringMapEntry< ValueTy >::getValue () inline
Definition at line 141 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::second.
getValue() [2/2]
template<typename ValueTy > const ValueTy & llvm::StringMapEntry< ValueTy >::getValue () const inline
Definition at line 140 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::second.
Referenced by llvm::PooledStringPtr::clear(), llvm::StringPool::intern(), llvm::PooledStringPtr::operator=(), llvm::orc::SymbolStringPtr::operator=(), llvm::PooledStringPtr::PooledStringPtr(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), and llvm::orc::SymbolStringPtr::~SymbolStringPtr().
setValue()
template<typename ValueTy > void llvm::StringMapEntry< ValueTy >::setValue (const ValueTy & V) inline
Definition at line 143 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::second.
Referenced by llvm::Value::takeName().
Member Data Documentation
second
template<typename ValueTy > ValueTy llvm::StringMapEntry< ValueTy >::second
Definition at line 127 of file StringMap.h.
Referenced by llvm::StringMapEntry< ValueTy >::getValue(), and llvm::StringMapEntry< ValueTy >::setValue().
The documentation for this class was generated from the following file:
include/llvm/ADT/StringMap.h