LLVM: llvm::InstrOrderFilePass Class Reference
llvm::InstrOrderFilePass Class Reference
The instrumentation pass for recording function order.
#include "llvm/Transforms/Instrumentation/InstrOrderFile.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InstrOrderFilePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The instrumentation pass for recording function order.
Definition at line 21 of file InstrOrderFile.h.
Member Function Documentation
run()
PreservedAnalyses InstrOrderFilePass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 196 of file InstrOrderFile.cpp.
References llvm::PreservedAnalyses::all(), llvm::PreservedAnalyses::none(), and run().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/InstrOrderFile.h
lib/Transforms/Instrumentation/InstrOrderFile.cpp