LLVM: llvm::CallLowering Class Reference
llvm::CallLowering Class Reference
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
Classes
struct ArgInfo
struct ValueHandler
Argument handling is mostly uniform between the four places that make these decisions: function formal arguments, call instruction args, call instruction returns and function returns.
Public Member Functions
CallLowering (const TargetLowering *TLI)
virtual ~CallLowering ()=default
virtual bool supportSwiftError () const
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs) const
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
virtual bool lowerFormalArguments (MachineIRBuilder &MIRBuilder, const Function &F, ArrayRef< ArrayRef< Register > > VRegs) const
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs) const
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
bool lowerCall (MachineIRBuilder &MIRBuilder, ImmutableCallSite CS, ArrayRef< Register > ResRegs, ArrayRef< ArrayRef< Register > > ArgRegs, Register SwiftErrorVReg, std::function< unsigned()> GetCalleeReg) const
Lower the given call instruction, including argument and return value marshalling.
Protected Member Functions
const TargetLowering * getTLI () const
Getter for generic TargetLowering class.
template<class XXXTargetLowering >
const XXXTargetLowering * getTLI () const
Getter for target specific TargetLowering class.
template<typename FuncInfoTy >
void setArgFlags (ArgInfo &Arg, unsigned OpIdx, const DataLayout &DL, const FuncInfoTy &FuncInfo) const
Register packRegs (ArrayRef< Register > SrcRegs, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for packing SrcRegs into one big register corresponding to the aggregate type PackedTy.
void unpackRegs (ArrayRef< Register > DstRegs, Register SrcReg, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for unpacking SrcReg into the DstRegs corresponding to the aggregate type PackedTy.
bool handleAssignments (MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Invoke Handler::assignArg on each of the given Args and then use Callback to move them to the assigned locations.
bool handleAssignments (CCState &CCState, SmallVectorImpl< CCValAssign > &ArgLocs, MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Detailed Description
Definition at line 41 of file CallLowering.h.
Constructor & Destructor Documentation
CallLowering()
llvm::CallLowering::CallLowering (const TargetLowering * TLI) inline
Definition at line 172 of file CallLowering.h.
~CallLowering()
virtual llvm::CallLowering::~CallLowering () virtual default
Member Function Documentation
getTLI() [1/2]
const TargetLowering * llvm::CallLowering::getTLI () const inline protected
Getter for generic TargetLowering class.
Definition at line 129 of file CallLowering.h.
Referenced by setArgFlags().
getTLI() [2/2]
template<class XXXTargetLowering > const XXXTargetLowering * llvm::CallLowering::getTLI () const inline protected
Getter for target specific TargetLowering class.
Definition at line 135 of file CallLowering.h.
handleAssignments() [1/2]
bool CallLowering::handleAssignments (CCState & CCState, SmallVectorImpl< CCValAssign > & ArgLocs, MachineIRBuilder & MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler & Handler) const protected
Definition at line 171 of file CallLowering.cpp.
References llvm::alignTo(), assert(), llvm::CallLowering::ValueHandler::assignArg(), llvm::CallLowering::ValueHandler::assignCustomValue(), llvm::CallLowering::ValueHandler::assignValueToAddress(), llvm::CallLowering::ValueHandler::assignValueToReg(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::dbgs(), F, llvm::CCValAssign::Full, llvm::MachineFunction::getFunction(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::LLT::getNumElements(), llvm::DataLayout::getPointerSize(), getReg(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::MVT::getSizeInBits(), llvm::CallLowering::ValueHandler::getStackAddress(), llvm::CCValAssign::getValNo(), llvm::CCValAssign::getValVT(), llvm::MVT::getVectorNumElements(), llvm::VTSDNode::getVT(), llvm::MVT::iPTR, llvm::CallLowering::ValueHandler::isArgumentHandler(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::MVT::isValid(), llvm::LLT::isVector(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::CCValAssign::needsCustom(), llvm::SmallVectorBase::size(), and Size.
handleAssignments() [2/2]
bool CallLowering::handleAssignments (MachineIRBuilder & MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler & Handler) const protected
Invoke Handler::assignArg on each of the given Args and then use Callback to move them to the assigned locations.
Returns
True if everything has succeeded, false otherwise.
Definition at line 161 of file CallLowering.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), and handleAssignments().
Referenced by handleAssignments(), llvm::ARMCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), and llvm::AArch64CallLowering::lowerReturn().
lowerCall() [1/3]
virtual bool llvm::CallLowering::lowerCall (MachineIRBuilder & MIRBuilder, CallingConv::ID CallConv, const MachineOperand & Callee, const ArgInfo & OrigRet, ArrayRef< ArgInfo > OrigArgs) const inline virtual
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
Reimplemented in llvm::AArch64CallLowering, llvm::ARMCallLowering, llvm::MipsCallLowering, and llvm::X86CallLowering.
Definition at line 254 of file CallLowering.h.
lowerCall() [2/3]
virtual bool llvm::CallLowering::lowerCall (MachineIRBuilder & MIRBuilder, CallingConv::ID CallConv, const MachineOperand & Callee, const ArgInfo & OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const inline virtual
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
CallConv is the calling convention to be used for the call.
Callee is the destination of the call. It should be either a register, globaladdress, or externalsymbol.
OrigRet is a descriptor for the return type of the function.
OrigArgs is a list of descriptors of the arguments passed to the function.
SwiftErrorVReg is non-zero if the call has a swifterror inout parameter, and contains the vreg that the swifterror should be copied into after the call.
Returns
true if the lowering succeeded, false otherwise.
Reimplemented in llvm::AArch64CallLowering.
Definition at line 241 of file CallLowering.h.
References assert(), Callee, lowerCall(), and supportSwiftError().
Referenced by lowerCall().
lowerCall() [3/3]
bool CallLowering::lowerCall (MachineIRBuilder & MIRBuilder, ImmutableCallSite CS, ArrayRef< Register > ResRegs, ArrayRef< ArrayRef< Register > > ArgRegs, Register SwiftErrorVReg, std::function< unsigned()> GetCalleeReg) const
Lower the given call instruction, including argument and return value marshalling.
CI is the call/invoke instruction.
ResRegs are the registers where the call's return value should be stored (or 0 if there is no return value). There will be one register for each non-aggregate type, as returned by computeValueLLTs.
ArgRegs is a list of lists of virtual registers containing each argument that needs to be passed (argument i should be placed in ArgRegs[i]). For each argument, there will be one register for each non-aggregate type, as returned by computeValueLLTs.
SwiftErrorVReg is non-zero if the call has a swifterror inout parameter, and contains the vreg that the swifterror should be copied into after the call.
GetCalleeReg is a callback to materialize a register for the callee if the target determines it cannot jump to the destination based purely on CI. This might be because CI is indirect, or because of the limited range of an immediate jump.
Returns
true if the lowering succeeded, false otherwise.
Definition at line 30 of file CallLowering.cpp.
References Arg, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::args(), Callee, llvm::MachineOperand::CreateGA(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), F, llvm::AttributeList::FirstArgIndex, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCallingConv(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getParent(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getType(), lowerCall(), NumFixedArgs, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AttributeList::ReturnIndex, and setArgFlags().
lowerFormalArguments()
virtual bool llvm::CallLowering::lowerFormalArguments (MachineIRBuilder & MIRBuilder, const Function & F, ArrayRef< ArrayRef< Register > > VRegs) const inline virtual
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
Each argument must end up in the related virtual registers described by VRegs. In other words, the first argument should end up in VRegs[0], the second in VRegs[1], and so on. For each argument, there will be one register for each non-aggregate type, as returned by computeValueLLTs. MIRBuilder is set to the proper insertion for the argument lowering.
Returns
True if the lowering succeeded, false otherwise.
Reimplemented in llvm::AArch64CallLowering, llvm::AMDGPUCallLowering, llvm::ARMCallLowering, llvm::MipsCallLowering, and llvm::X86CallLowering.
Definition at line 217 of file CallLowering.h.
Referenced by llvm::IRTranslator::runOnMachineFunction().
lowerReturn() [1/2]
virtual bool llvm::CallLowering::lowerReturn (MachineIRBuilder & MIRBuilder, const Value * Val, ArrayRef< Register > VRegs) const inline virtual
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
Reimplemented in llvm::AMDGPUCallLowering, llvm::ARMCallLowering, llvm::MipsCallLowering, and llvm::X86CallLowering.
Definition at line 202 of file CallLowering.h.
lowerReturn() [2/2]
virtual bool llvm::CallLowering::lowerReturn (MachineIRBuilder & MIRBuilder, const Value * Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const inline virtual
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
This hook is used by GlobalISel.
SwiftErrorVReg is non-zero if the function has a swifterror parameter that needs to be implicitly returned.
Returns
True if the lowering succeeds, false otherwise.
Reimplemented in llvm::AArch64CallLowering.
Definition at line 190 of file CallLowering.h.
References assert(), lowerReturn(), and supportSwiftError().
Referenced by lowerReturn().
packRegs()
Register CallLowering::packRegs (ArrayRef< Register > SrcRegs, Type * PackedTy, MachineIRBuilder & MIRBuilder) const protected
Generate instructions for packing SrcRegs into one big register corresponding to the aggregate type PackedTy.
Parameters
SrcRegs should contain one virtual register for each base type in PackedTy, as returned by computeValueLLTs.
Returns
The packed register.
Definition at line 120 of file CallLowering.cpp.
References assert(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildUndef(), llvm::computeValueLLTs(), llvm::MachineFunction::getDataLayout(), llvm::getLLTForType(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), MRI, llvm::ArrayRef< T >::size(), and llvm::SmallVectorBase::size().
setArgFlags()
template<typename FuncInfoTy > template void CallLowering::setArgFlags< CallInst > (ArgInfo & Arg, unsigned OpIdx, const DataLayout & DL, const FuncInfoTy & FuncInfo) const protected
Definition at line 69 of file CallLowering.cpp.
References Arg, llvm::DataLayout::getABITypeAlignment(), llvm::TargetLoweringBase::getByValTypeAlignment(), getTLI(), llvm::DataLayout::getTypeAllocSize(), llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
Referenced by lowerCall(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), and llvm::AArch64CallLowering::lowerReturn().
supportSwiftError()
virtual bool llvm::CallLowering::supportSwiftError () const inline virtual
Returns
true if the target is capable of handling swifterror values that have been promoted to a specified register. The extended versions of lowerReturn and lowerCall should be implemented.
Reimplemented in llvm::AArch64CallLowering.
Definition at line 178 of file CallLowering.h.
Referenced by lowerCall(), and lowerReturn().
unpackRegs()
void CallLowering::unpackRegs (ArrayRef< Register > DstRegs, Register SrcReg, Type * PackedTy, MachineIRBuilder & MIRBuilder) const protected
Generate instructions for unpacking SrcReg into the DstRegs corresponding to the aggregate type PackedTy.
Parameters
DstRegs should contain one virtual register for each base type in PackedTy, as returned by computeValueLLTs.
Definition at line 145 of file CallLowering.cpp.
References assert(), llvm::MachineIRBuilder::buildExtract(), llvm::computeValueLLTs(), llvm::MachineFunction::getDataLayout(), llvm::MachineIRBuilder::getMF(), llvm::ArrayRef< T >::size(), and llvm::SmallVectorBase::size().
Referenced by llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CallLowering.h
lib/CodeGen/GlobalISel/CallLowering.cpp