LLVM: llvm::MipsCallLowering Class Reference
llvm::MipsCallLowering Class Reference
#include "Target/Mips/MipsCallLowering.h"
Classes
class MipsHandler
Public Member Functions
MipsCallLowering (const MipsTargetLowering &TLI)
bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs) const override
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
bool lowerFormalArguments (MachineIRBuilder &MIRBuilder, const Function &F, ArrayRef< ArrayRef< Register > > VRegs) const override
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs) const override
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
Public Member Functions inherited from llvm::CallLowering
CallLowering (const TargetLowering *TLI)
virtual ~CallLowering ()=default
virtual bool supportSwiftError () const
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs) const
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
virtual bool lowerFormalArguments (MachineIRBuilder &MIRBuilder, const Function &F, ArrayRef< ArrayRef< Register > > VRegs) const
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs) const
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
bool lowerCall (MachineIRBuilder &MIRBuilder, ImmutableCallSite CS, ArrayRef< Register > ResRegs, ArrayRef< ArrayRef< Register > > ArgRegs, Register SwiftErrorVReg, std::function< unsigned()> GetCalleeReg) const
Lower the given call instruction, including argument and return value marshalling.
Additional Inherited Members
Protected Member Functions inherited from llvm::CallLowering
const TargetLowering * getTLI () const
Getter for generic TargetLowering class.
template<class XXXTargetLowering >
const XXXTargetLowering * getTLI () const
Getter for target specific TargetLowering class.
template<typename FuncInfoTy >
void setArgFlags (ArgInfo &Arg, unsigned OpIdx, const DataLayout &DL, const FuncInfoTy &FuncInfo) const
Register packRegs (ArrayRef< Register > SrcRegs, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for packing SrcRegs into one big register corresponding to the aggregate type PackedTy.
void unpackRegs (ArrayRef< Register > DstRegs, Register SrcReg, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for unpacking SrcReg into the DstRegs corresponding to the aggregate type PackedTy.
bool handleAssignments (MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Invoke Handler::assignArg on each of the given Args and then use Callback to move them to the assigned locations.
bool handleAssignments (CCState &CCState, SmallVectorImpl< CCValAssign > &ArgLocs, MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Detailed Description
Definition at line 23 of file MipsCallLowering.h.
Constructor & Destructor Documentation
MipsCallLowering()
MipsCallLowering::MipsCallLowering (const MipsTargetLowering & TLI)
Definition at line 24 of file MipsCallLowering.cpp.
Member Function Documentation
lowerCall()
bool MipsCallLowering::lowerCall (MachineIRBuilder & MIRBuilder, CallingConv::ID CallConv, const MachineOperand & Callee, const ArgInfo & OrigRet, ArrayRef< ArgInfo > OrigArgs) const override virtual
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
Reimplemented from llvm::CallLowering.
Definition at line 501 of file MipsCallLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineInstrBuilder::addUse(), llvm::alignTo(), llvm::CCState::AllocateStack(), llvm::MipsCCState::AnalyzeCallOperands(), llvm::MipsCCState::AnalyzeCallResult(), Arg, llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::CallingConv::C, Callee, llvm::MipsTargetLowering::CCAssignFnForCall(), llvm::MipsTargetLowering::CCAssignFnForReturn(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineInstrBuilder::constrainAllUses(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), F, llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MipsFunctionInfo::getGlobalBaseRegForGlobalISel(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMF(), llvm::CCState::getNextStackOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MipsSubtarget::getRegBankInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MipsSubtarget::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineIRBuilder::getTII(), llvm::RegState::Implicit, llvm::MachineIRBuilder::insertInstr(), isSupportedType(), llvm::MipsII::MO_GOT_CALL, llvm::CallLowering::ArgInfo::Regs, setLocInfo(), llvm::MachineOperand::setTargetFlags(), llvm::ArrayRef< T >::size(), TRI, and llvm::CallLowering::ArgInfo::Ty.
lowerFormalArguments()
bool MipsCallLowering::lowerFormalArguments (MachineIRBuilder & MIRBuilder, const Function & F, ArrayRef< ArrayRef< Register > > VRegs) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
Each argument must end up in the related virtual registers described by VRegs. In other words, the first argument should end up in VRegs[0], the second in VRegs[1], and so on. For each argument, there will be one register for each non-aggregate type, as returned by computeValueLLTs. MIRBuilder is set to the proper insertion for the argument lowering.
Returns
True if the lowering succeeded, false otherwise.
Reimplemented from llvm::CallLowering.
Definition at line 448 of file MipsCallLowering.cpp.
References llvm::CCState::AllocateStack(), llvm::MipsCCState::AnalyzeFormalArguments(), Arg, llvm::MipsTargetLowering::CCAssignFnForCall(), F, llvm::AttributeList::FirstArgIndex, llvm::MachineFunction::getDataLayout(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), isSupportedType(), llvm::CallLowering::setArgFlags(), and setLocInfo().
lowerReturn()
bool MipsCallLowering::lowerReturn (MachineIRBuilder & MIRBuilder, const Value * Val, ArrayRef< Register > VRegs) const override virtual
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
Reimplemented from llvm::CallLowering.
Definition at line 400 of file MipsCallLowering.cpp.
References llvm::MipsCCState::AnalyzeReturn(), assert(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::MipsTargetLowering::CCAssignFnForReturn(), llvm::ComputeValueVTs(), llvm::ArrayRef< T >::empty(), F, llvm::Type::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getRegInfo(), llvm::Value::getType(), llvm::MachineIRBuilder::insertInstr(), isSupportedType(), llvm::AttributeList::ReturnIndex, llvm::CallLowering::setArgFlags(), setLocInfo(), llvm::ArrayRef< T >::size(), and llvm::SmallVectorBase::size().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsCallLowering.h
lib/Target/Mips/MipsCallLowering.cpp