LLVM: llvm::parallel::detail::Latch Class Reference
llvm::parallel::detail::Latch Class Reference
#include "llvm/Support/Parallel.h"
Public Member Functions
Latch (uint32_t Count=0)
~Latch ()
void inc ()
void dec ()
void sync () const
Detailed Description
Definition at line 48 of file Parallel.h.
Constructor & Destructor Documentation
Latch()
llvm::parallel::detail::Latch::Latch (uint32_t Count = 0) inline explicit
Definition at line 54 of file Parallel.h.
~Latch()
llvm::parallel::detail::Latch::~Latch () inline
Definition at line 55 of file Parallel.h.
References sync().
Member Function Documentation
dec()
void llvm::parallel::detail::Latch::dec () inline
Definition at line 62 of file Parallel.h.
Referenced by llvm::parallel::detail::TaskGroup::spawn().
inc()
void llvm::parallel::detail::Latch::inc () inline
Definition at line 57 of file Parallel.h.
Referenced by llvm::parallel::detail::TaskGroup::spawn().
sync()
void llvm::parallel::detail::Latch::sync () const inline
Definition at line 68 of file Parallel.h.
Referenced by llvm::parallel::detail::TaskGroup::sync(), and ~Latch().
The documentation for this class was generated from the following file:
include/llvm/Support/Parallel.h