LLVM: llvm::sampleprof::SampleProfileWriterRawBinary Class Reference
llvm::sampleprof::SampleProfileWriterRawBinary Class Reference
#include "llvm/ProfileData/SampleProfWriter.h"
Protected Member Functions
virtual std::error_code writeNameTable () override
virtual std::error_code writeMagicIdent () override
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code writeNameTable ()=0
virtual std::error_code writeMagicIdent ()=0
virtual std::error_code writeHeader (const StringMap< FunctionSamples > &ProfileMap) override
Write a file header for the profile file.
std::error_code writeSummary ()
std::error_code writeNameIdx (StringRef FName)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (std::set< StringRef > &V)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeHeader (const StringMap< FunctionSamples > &ProfileMap)=0
Write a file header for the profile file.
void computeSummary (const StringMap< FunctionSamples > &ProfileMap)
Compute summary for this profile.
Additional Inherited Members
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code write (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
virtual std::error_code write (const FunctionSamples &S)=0
Write sample profiles in S.
virtual std::error_code write (const StringMap< FunctionSamples > &ProfileMap)
Write all the sample profiles in the given map of samples.
raw_ostream & getOutputStream ()
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterBinary
MapVector< StringRef, uint32_t > NameTable
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
Detailed Description
Definition at line 130 of file SampleProfWriter.h.
Member Function Documentation
writeMagicIdent()
std::error_code SampleProfileWriterRawBinary::writeMagicIdent () override protected virtual
Implements llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 217 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SPMagic(), llvm::sampleprof::SPVersion(), and llvm::success.
writeNameTable()
std::error_code SampleProfileWriterRawBinary::writeNameTable () override protected virtual
Implements llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 166 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), N, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SampleProfileWriterBinary::stablizeNameTable(), and llvm::success.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp