LLVM: llvm::GEPOperator Class Reference
llvm::GEPOperator Class Reference
#include "llvm/IR/Operator.h"
Public Member Functions
bool isInBounds () const
Test whether this is an inbounds GEP, as defined by LangRef.html.
Optional< unsigned > getInRangeIndex () const
Returns the offset of the index with an inrange attachment, or None if none.
op_iterator idx_begin ()
const_op_iterator idx_begin () const
op_iterator idx_end ()
const_op_iterator idx_end () const
Value * getPointerOperand ()
const Value * getPointerOperand () const
Type * getPointerOperandType () const
Method to return the pointer operand as a PointerType.
Type * getSourceElementType () const
Type * getResultElementType () const
unsigned getPointerAddressSpace () const
Method to return the address space of the pointer operand.
unsigned getNumIndices () const
bool hasIndices () const
bool hasAllZeroIndices () const
Return true if all of the indices of this GEP are zeros.
bool hasAllConstantIndices () const
Return true if all of the indices of this GEP are constant integers.
unsigned countNonConstantIndices () const
bool accumulateConstantOffset (const DataLayout &DL, APInt &Offset) const
Accumulate the constant address offset of this GEP if possible.
Public Member Functions inherited from llvm::Operator
Operator ()=delete
~Operator ()=delete
void * operator new (size_t s)=delete
unsigned getOpcode () const
Return the opcode for this Instruction or ConstantExpr.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, bool)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCasts ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs, aliases and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripPointerCastsNoFollowAliases () const
Strip off pointer casts and all-zero GEPs.
Value * stripPointerCastsNoFollowAliases ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
unsigned getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static unsigned getPointerOperandIndex ()
Static Public Member Functions inherited from llvm::ConcreteOperator< Operator, Instruction::GetElementPtr >
static bool classof (const Instruction *I)
static bool classof (const ConstantExpr *CE)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Operator
static unsigned getOpcode (const Value *V)
If V is an Instruction or ConstantExpr, return its opcode.
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class GetElementPtrInst
class ConstantExpr
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 440 of file Operator.h.
Member Function Documentation
accumulateConstantOffset()
bool llvm::GEPOperator::accumulateConstantOffset (const DataLayout & DL, APInt & Offset) const
Accumulate the constant address offset of this GEP if possible.
This routine accepts an APInt into which it will accumulate the constant offset of this GEP if the GEP is in fact constant. If the GEP is not all-constant, it returns false and the value of the offset APInt is undefined (it is not preserved!). The APInt passed into this routine must be at exactly as wide as the IntPtr type for the address space of the base GEP pointer.
Definition at line 34 of file Operator.cpp.
References assert(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::StructLayout::getElementOffset(), llvm::DataLayout::getIndexSizeInBits(), getPointerAddressSpace(), llvm::DataLayout::getStructLayout(), llvm::DataLayout::getTypeAllocSize(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), and llvm::ConstantInt::isZero().
Referenced by llvm::ObjectSizeOffsetVisitor::visitGEPOperator().
countNonConstantIndices()
unsigned llvm::GEPOperator::countNonConstantIndices () const inline
Definition at line 528 of file Operator.h.
References idx_begin(), idx_end(), and use.
Referenced by llvm::InstCombiner::OptimizePointerDifference().
getInRangeIndex()
Optional< unsigned > llvm::GEPOperator::getInRangeIndex () const inline
Returns the offset of the index with an inrange attachment, or None if none.
Definition at line 463 of file Operator.h.
References llvm::None, and llvm::Value::SubclassOptionalData.
getNumIndices()
unsigned llvm::GEPOperator::getNumIndices () const inline
Definition at line 496 of file Operator.h.
References llvm::User::getNumOperands().
Referenced by aliasSameBasePointerGEPs().
getPointerAddressSpace()
unsigned llvm::GEPOperator::getPointerAddressSpace () const inline
Method to return the address space of the pointer operand.
Definition at line 492 of file Operator.h.
References llvm::Type::getPointerAddressSpace(), and getPointerOperandType().
Referenced by accumulateConstantOffset(), and isGEPKnownNonNull().
getPointerOperand() [1/2]
Value * llvm::GEPOperator::getPointerOperand () inline
Definition at line 473 of file Operator.h.
References llvm::User::getOperand().
Referenced by aliasSameBasePointerGEPs(), llvm::ScalarEvolution::getGEPExpr(), getPointerOperandType(), isGEPKnownNonNull(), llvm::ObjectSizeOffsetVisitor::visitGEPOperator(), and llvm::ObjectSizeOffsetEvaluator::visitGEPOperator().
getPointerOperand() [2/2]
const Value * llvm::GEPOperator::getPointerOperand () const inline
Definition at line 476 of file Operator.h.
References llvm::User::getOperand().
getPointerOperandIndex()
static unsigned llvm::GEPOperator::getPointerOperandIndex () inline static
Definition at line 479 of file Operator.h.
getPointerOperandType()
Type * llvm::GEPOperator::getPointerOperandType () const inline
Method to return the pointer operand as a PointerType.
Definition at line 484 of file Operator.h.
References getPointerOperand(), and llvm::Value::getType().
Referenced by aliasSameBasePointerGEPs(), and getPointerAddressSpace().
getResultElementType()
Type * llvm::GEPOperator::getResultElementType () const
Definition at line 28 of file Operator.cpp.
References I.
getSourceElementType()
Type * llvm::GEPOperator::getSourceElementType () const
Definition at line 22 of file Operator.cpp.
References I.
Referenced by aliasSameBasePointerGEPs(), llvm::ConstantFoldCastInstruction(), llvm::ScalarEvolution::getGEPExpr(), and llvm::isGEPBasedOnPointerToString().
hasAllConstantIndices()
bool llvm::GEPOperator::hasAllConstantIndices () const inline
Return true if all of the indices of this GEP are constant integers.
If so, the result pointer and the first operand have a constant offset between them.
Definition at line 520 of file Operator.h.
References I, idx_begin(), and idx_end().
Referenced by transformToIndexedCompare().
hasAllZeroIndices()
bool llvm::GEPOperator::hasAllZeroIndices () const inline
Return true if all of the indices of this GEP are zeros.
If so, the result pointer and the first operand have the same value, just potentially different types.
Definition at line 507 of file Operator.h.
References I, idx_begin(), and idx_end().
Referenced by evaluateICmpRelation(), and shouldMergeGEPs().
hasIndices()
bool llvm::GEPOperator::hasIndices () const inline
Definition at line 500 of file Operator.h.
References llvm::User::getNumOperands().
idx_begin() [1/2]
op_iterator llvm::GEPOperator::idx_begin () inline
Definition at line 468 of file Operator.h.
References llvm::User::op_begin().
Referenced by countNonConstantIndices(), hasAllConstantIndices(), and hasAllZeroIndices().
idx_begin() [2/2]
const_op_iterator llvm::GEPOperator::idx_begin () const inline
Definition at line 469 of file Operator.h.
References llvm::User::op_begin().
idx_end() [1/2]
op_iterator llvm::GEPOperator::idx_end () inline
Definition at line 470 of file Operator.h.
References llvm::User::op_end().
Referenced by countNonConstantIndices(), hasAllConstantIndices(), and hasAllZeroIndices().
idx_end() [2/2]
const_op_iterator llvm::GEPOperator::idx_end () const inline
Definition at line 471 of file Operator.h.
References llvm::User::op_end().
isInBounds()
bool llvm::GEPOperator::isInBounds () const inline
Test whether this is an inbounds GEP, as defined by LangRef.html.
Definition at line 457 of file Operator.h.
References llvm::Value::SubclassOptionalData.
Referenced by llvm::EmitGEPOffset(), llvm::ScalarEvolution::getGEPExpr(), and isGEPKnownNonNull().
Friends And Related Function Documentation
ConstantExpr
friend class ConstantExpr friend
Definition at line 443 of file Operator.h.
GetElementPtrInst
friend class GetElementPtrInst friend
Definition at line 442 of file Operator.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Operator.h
lib/IR/Operator.cpp