LLVM: llvm::CoroSubFnInst Class Reference
llvm::CoroSubFnInst Class Reference
This class represents the llvm.coro.subfn.addr instruction.
#include "Transforms/Coroutines/CoroInstr.h"
Public Types
enum ResumeKind {
RestartTrigger = -1 , ResumeIndex , DestroyIndex , CleanupIndex ,
IndexLast , IndexFirst = RestartTrigger
}
Public Member Functions
Value * getFrame () const
ResumeKind getIndex () const
ConstantInt * getRawIndex () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Detailed Description
This class represents the llvm.coro.subfn.addr instruction.
Definition at line 34 of file CoroInstr.h.
Member Enumeration Documentation
ResumeKind
enum llvm::CoroSubFnInst::ResumeKind
Enumerator
RestartTrigger
ResumeIndex
DestroyIndex
CleanupIndex
IndexLast
IndexFirst
Definition at line 38 of file CoroInstr.h.
Member Function Documentation
classof() [1/2]
static bool llvm::CoroSubFnInst::classof (const IntrinsicInst * I) inline static
Definition at line 60 of file CoroInstr.h.
References I.
classof() [2/2]
static bool llvm::CoroSubFnInst::classof (const Value * V) inline static
Definition at line 63 of file CoroInstr.h.
getFrame()
Value * llvm::CoroSubFnInst::getFrame () const inline
Definition at line 47 of file CoroInstr.h.
Referenced by lowerSubFn().
getIndex()
ResumeKind llvm::CoroSubFnInst::getIndex () const inline
Definition at line 48 of file CoroInstr.h.
References assert().
Referenced by lowerSubFn().
getRawIndex()
ConstantInt * llvm::CoroSubFnInst::getRawIndex () const inline
Definition at line 55 of file CoroInstr.h.
The documentation for this class was generated from the following file:
lib/Transforms/Coroutines/CoroInstr.h