LLVM: llvm::orc::JITCompileCallbackManager Class Reference
llvm::orc::JITCompileCallbackManager Class Reference
Target-independent base class for compile callback management.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Types
using CompileFunction = std::function< JITTargetAddress()>
Public Member Functions
virtual ~JITCompileCallbackManager ()=default
Expected< JITTargetAddress > getCompileCallback (CompileFunction Compile)
Reserve a compile callback.
JITTargetAddress executeCompileCallback (JITTargetAddress TrampolineAddr)
Execute the callback for the given trampoline id.
Protected Member Functions
JITCompileCallbackManager (std::unique_ptr< TrampolinePool > TP, ExecutionSession &ES, JITTargetAddress ErrorHandlerAddress)
Construct a JITCompileCallbackManager.
void setTrampolinePool (std::unique_ptr< TrampolinePool > TP)
Detailed Description
Target-independent base class for compile callback management.
Definition at line 185 of file IndirectionUtils.h.
Member Typedef Documentation
CompileFunction
using llvm::orc::JITCompileCallbackManager::CompileFunction = std::function<JITTargetAddress()>
Definition at line 187 of file IndirectionUtils.h.
Constructor & Destructor Documentation
~JITCompileCallbackManager()
virtual llvm::orc::JITCompileCallbackManager::~JITCompileCallbackManager () virtual default
JITCompileCallbackManager()
llvm::orc::JITCompileCallbackManager::JITCompileCallbackManager (std::unique_ptr< TrampolinePool > TP, ExecutionSession & ES, JITTargetAddress ErrorHandlerAddress) inline protected
Construct a JITCompileCallbackManager.
Definition at line 200 of file IndirectionUtils.h.
Member Function Documentation
executeCompileCallback()
JITTargetAddress llvm::orc::JITCompileCallbackManager::executeCompileCallback (JITTargetAddress TrampolineAddr)
Execute the callback for the given trampoline id.
Called by the JIT to compile functions on demand.
Definition at line 77 of file IndirectionUtils.cpp.
References llvm::dbgs(), llvm::format(), I, llvm::inconvertibleErrorCode(), llvm::Lock, llvm::orc::ExecutionSession::lookup(), Name, llvm::orc::ExecutionSession::reportError(), and llvm::sys::SmartMutex< mt_only >::unlock().
getCompileCallback()
Expected< JITTargetAddress > llvm::orc::JITCompileCallbackManager::getCompileCallback (CompileFunction Compile)
Reserve a compile callback.
Definition at line 61 of file IndirectionUtils.cpp.
References llvm::orc::ExecutionSession::allocateVModule(), llvm::cantFail(), llvm::orc::JITDylib::define(), llvm::orc::ExecutionSession::intern(), and llvm::Lock.
setTrampolinePool()
void llvm::orc::JITCompileCallbackManager::setTrampolinePool (std::unique_ptr< TrampolinePool > TP) inline protected
Definition at line 207 of file IndirectionUtils.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h
lib/ExecutionEngine/Orc/IndirectionUtils.cpp