LLVM: llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor > Class Template Reference
llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor > Class Template Reference
Eager IR compiling layer.
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
Public Types
using NotifyCompiledCallback = std::function< void(VModuleKey K, std::unique_ptr< Module >)>
Callback type for notifications when modules are compiled.
Public Member Functions
LLVM_ATTRIBUTE_DEPRECATED (LegacyIRCompileLayer(BaseLayerT &BaseLayer, CompileFtor Compile, NotifyCompiledCallback NotifyCompiled=NotifyCompiledCallback()), "ORCv1 layers (layers with the 'Legacy' prefix) are deprecated. Please " "use " "the ORCv2 IRCompileLayer instead")
Construct an LegacyIRCompileLayer with the given BaseLayer, which must implement the ObjectLayer concept.
LegacyIRCompileLayer (ORCv1DeprecationAcknowledgement, BaseLayerT &BaseLayer, CompileFtor Compile, NotifyCompiledCallback NotifyCompiled=NotifyCompiledCallback())
Legacy layer constructor with deprecation acknowledgement.
CompileFtor & getCompiler ()
Get a reference to the compiler functor.
void setNotifyCompiled (NotifyCompiledCallback NotifyCompiled)
(Re)set the NotifyCompiled callback.
Error addModule (VModuleKey K, std::unique_ptr< Module > M)
Compile the module, and add the resulting object to the base layer along with the given memory manager and symbol resolver.
Error removeModule (VModuleKey K)
Remove the module associated with the VModuleKey K.
JITSymbol findSymbol (const std::string &Name, bool ExportedSymbolsOnly)
Search for the given named symbol.
JITSymbol findSymbolIn (VModuleKey K, const std::string &Name, bool ExportedSymbolsOnly)
Get the address of the given symbol in compiled module represented by the handle H.
Error emitAndFinalize (VModuleKey K)
Immediately emit and finalize the module represented by the given handle.
Detailed Description
template<typename BaseLayerT, typename CompileFtor>
class llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >
Eager IR compiling layer.
This layer immediately compiles each IR module added via addModule to an object file and adds this module file to the layer below, which must implement the object layer concept.
Definition at line 58 of file IRCompileLayer.h.
Member Typedef Documentation
NotifyCompiledCallback
template<typename BaseLayerT , typename CompileFtor > using llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::NotifyCompiledCallback = std::function<void(VModuleKey K, std::unique_ptr<Module>)>
Callback type for notifications when modules are compiled.
Definition at line 61 of file IRCompileLayer.h.
Constructor & Destructor Documentation
LegacyIRCompileLayer()
template<typename BaseLayerT , typename CompileFtor > llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::LegacyIRCompileLayer (ORCv1DeprecationAcknowledgement , BaseLayerT & BaseLayer, CompileFtor Compile, NotifyCompiledCallback NotifyCompiled = NotifyCompiledCallback()) inline
Legacy layer constructor with deprecation acknowledgement.
Definition at line 75 of file IRCompileLayer.h.
Member Function Documentation
addModule()
template<typename BaseLayerT , typename CompileFtor > Error llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::addModule (VModuleKey K, std::unique_ptr< Module > M) inline
Compile the module, and add the resulting object to the base layer along with the given memory manager and symbol resolver.
Definition at line 92 of file IRCompileLayer.h.
References llvm::Error::success().
emitAndFinalize()
template<typename BaseLayerT , typename CompileFtor > Error llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::emitAndFinalize (VModuleKey K) inline
Immediately emit and finalize the module represented by the given handle.
Parameters
K The VModuleKey for the module to emit/finalize.
Definition at line 127 of file IRCompileLayer.h.
findSymbol()
template<typename BaseLayerT , typename CompileFtor > JITSymbol llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::findSymbol (const std::string & Name, bool ExportedSymbolsOnly) inline
Search for the given named symbol.
Parameters
Name The name of the symbol to search for.
ExportedSymbolsOnly If true, search only for exported symbols.
Returns
A handle for the given named symbol, if it exists.
Definition at line 107 of file IRCompileLayer.h.
References Name.
Referenced by llvm::OrcCBindingsStack::findSymbol().
findSymbolIn()
template<typename BaseLayerT , typename CompileFtor > JITSymbol llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::findSymbolIn (VModuleKey K, const std::string & Name, bool ExportedSymbolsOnly) inline
Get the address of the given symbol in compiled module represented by the handle H.
This call is forwarded to the base layer's implementation.
Parameters
K The VModuleKey for the module to search in.
Name The name of the symbol to search for.
ExportedSymbolsOnly If true, search only for exported symbols.
Returns
A handle for the given named symbol, if it is found in the given module.
Definition at line 119 of file IRCompileLayer.h.
References Name.
getCompiler()
template<typename BaseLayerT , typename CompileFtor > CompileFtor & llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::getCompiler () inline
Get a reference to the compiler functor.
Definition at line 83 of file IRCompileLayer.h.
Referenced by llvm::orc::OrcMCJITReplacement::setObjectCache().
LLVM_ATTRIBUTE_DEPRECATED()
template<typename BaseLayerT , typename CompileFtor > llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::LLVM_ATTRIBUTE_DEPRECATED (LegacyIRCompileLayer< BaseLayerT, CompileFtor >(BaseLayerT &BaseLayer, CompileFtor Compile, NotifyCompiledCallback NotifyCompiled=NotifyCompiledCallback()) , "ORCv1 layers (layers with the 'Legacy' prefix) are deprecated. Please " "use " "the ORCv2 IRCompileLayer instead")
Construct an LegacyIRCompileLayer with the given BaseLayer, which must implement the ObjectLayer concept.
removeModule()
template<typename BaseLayerT , typename CompileFtor > Error llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::removeModule (VModuleKey K) inline
Remove the module associated with the VModuleKey K.
Definition at line 101 of file IRCompileLayer.h.
setNotifyCompiled()
template<typename BaseLayerT , typename CompileFtor > void llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::setNotifyCompiled (NotifyCompiledCallback NotifyCompiled) inline
(Re)set the NotifyCompiled callback.
Definition at line 86 of file IRCompileLayer.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/IRCompileLayer.h