LLVM: llvm::DIObjCProperty Class Reference
llvm::DIObjCProperty Class Reference
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIObjCProperty,(StringRef Name, DIFile *File, unsigned Line, StringRef GetterName, StringRef SetterName, unsigned Attributes, DIType *Type),(Name, File, Line, GetterName, SetterName, Attributes, Type)) DEFINE_MDNODE_GET(DIObjCProperty
MDString Metadata unsigned MDString MDString unsigned Metadata Type TempDIObjCProperty clone () const
unsigned getLine () const
unsigned getAttributes () const
StringRef getName () const
DIFile * getFile () const
StringRef getGetterName () const
StringRef getSetterName () const
DIType * getType () const
StringRef getFilename () const
StringRef getDirectory () const
Optional< StringRef > getSource () const
MDString * getRawName () const
Metadata * getRawFile () const
MDString * getRawGetterName () const
MDString * getRawSetterName () const
Metadata * getRawType () const
Public Member Functions inherited from llvm::DINode
unsigned getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
MDString * Name
MDString Metadata * File
MDString Metadata unsigned Line
MDString Metadata unsigned MDString * GetterName
MDString Metadata unsigned MDString MDString * SetterName
MDString Metadata unsigned MDString MDString unsigned Attributes
MDString Metadata unsigned MDString MDString unsigned Metadata * Type
MDString Metadata unsigned MDString MDString unsigned Metadata Name
MDString Metadata unsigned MDString MDString unsigned Metadata File
MDString Metadata unsigned MDString MDString unsigned Metadata Line
MDString Metadata unsigned MDString MDString unsigned Metadata GetterName
MDString Metadata unsigned MDString MDString unsigned Metadata SetterName
MDString Metadata unsigned MDString MDString unsigned Metadata Attributes
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Definition at line 2901 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DIObjCProperty::classof (const Metadata * MD) inline static
Definition at line 2984 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
MDString Metadata unsigned MDString MDString unsigned Metadata Type TempDIObjCProperty llvm::DIObjCProperty::clone () const inline
Definition at line 2950 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DIObjCProperty::DEFINE_MDNODE_GET (DIObjCProperty , (StringRef Name, DIFile *File, unsigned Line, StringRef GetterName, StringRef SetterName, unsigned Attributes, DIType *Type) , (Name, File, Line, GetterName, SetterName, Attributes, Type))
getAttributes()
unsigned llvm::DIObjCProperty::getAttributes () const inline
Definition at line 2953 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getDirectory()
StringRef llvm::DIObjCProperty::getDirectory () const inline
Definition at line 2966 of file DebugInfoMetadata.h.
References F, and getFile().
getFile()
DIFile * llvm::DIObjCProperty::getFile () const inline
Definition at line 2955 of file DebugInfoMetadata.h.
References getRawFile().
Referenced by getDirectory(), getFilename(), and getSource().
getFilename()
StringRef llvm::DIObjCProperty::getFilename () const inline
Definition at line 2960 of file DebugInfoMetadata.h.
References F, and getFile().
getGetterName()
StringRef llvm::DIObjCProperty::getGetterName () const inline
Definition at line 2956 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getLine()
unsigned llvm::DIObjCProperty::getLine () const inline
Definition at line 2952 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getName()
StringRef llvm::DIObjCProperty::getName () const inline
Definition at line 2954 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getRawFile()
Metadata * llvm::DIObjCProperty::getRawFile () const inline
Definition at line 2979 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getFile(), and llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getRawGetterName()
MDString * llvm::DIObjCProperty::getRawGetterName () const inline
Definition at line 2980 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getRawName()
MDString * llvm::DIObjCProperty::getRawName () const inline
Definition at line 2978 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getRawSetterName()
MDString * llvm::DIObjCProperty::getRawSetterName () const inline
Definition at line 2981 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getRawType()
Metadata * llvm::DIObjCProperty::getRawType () const inline
Definition at line 2982 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getType(), and llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf().
getSetterName()
StringRef llvm::DIObjCProperty::getSetterName () const inline
Definition at line 2957 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getSource()
Optional< StringRef > llvm::DIObjCProperty::getSource () const inline
Definition at line 2972 of file DebugInfoMetadata.h.
References F, getFile(), and llvm::None.
getType()
DIType * llvm::DIObjCProperty::getType () const inline
Definition at line 2958 of file DebugInfoMetadata.h.
References getRawType().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 2902 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 2903 of file DebugInfoMetadata.h.
Member Data Documentation
Attributes [1/2]
MDString Metadata unsigned MDString MDString unsigned llvm::DIObjCProperty::Attributes
Definition at line 2946 of file DebugInfoMetadata.h.
Attributes [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::Attributes
Definition at line 2947 of file DebugInfoMetadata.h.
File [1/2]
MDString Metadata* llvm::DIObjCProperty::File
Definition at line 2944 of file DebugInfoMetadata.h.
File [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::File
Definition at line 2947 of file DebugInfoMetadata.h.
GetterName [1/2]
MDString Metadata unsigned MDString* llvm::DIObjCProperty::GetterName
Definition at line 2945 of file DebugInfoMetadata.h.
GetterName [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::GetterName
Definition at line 2947 of file DebugInfoMetadata.h.
Line [1/2]
MDString Metadata unsigned llvm::DIObjCProperty::Line
Definition at line 2944 of file DebugInfoMetadata.h.
Line [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::Line
Definition at line 2947 of file DebugInfoMetadata.h.
Name [1/2]
MDString* llvm::DIObjCProperty::Name
Definition at line 2944 of file DebugInfoMetadata.h.
Name [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::Name
Definition at line 2947 of file DebugInfoMetadata.h.
SetterName [1/2]
MDString Metadata unsigned MDString MDString* llvm::DIObjCProperty::SetterName
Definition at line 2945 of file DebugInfoMetadata.h.
SetterName [2/2]
MDString Metadata unsigned MDString MDString unsigned Metadata llvm::DIObjCProperty::SetterName
Definition at line 2947 of file DebugInfoMetadata.h.
Type
MDString Metadata unsigned MDString MDString unsigned Metadata* llvm::DIObjCProperty::Type
Definition at line 2946 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp