LLVM: llvm::ConstantExpr Class Reference
llvm::ConstantExpr Class Reference
A constant value that is initialized with an expression using other constant values.
#include "llvm/IR/Constants.h"
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
bool isCast () const
Return true if this is a convert constant expression.
bool isCompare () const
Return true if this is a compare constant expression.
bool hasIndices () const
Return true if this is an insertvalue or extractvalue expression, and the getIndices() method may be used.
bool isGEPWithNoNotionalOverIndexing () const
Return true if this is a getelementptr expression and all the index operands are compile-time known integers within the corresponding notional static array extents.
unsigned getOpcode () const
Return the opcode at the root of this constant expression.
unsigned getPredicate () const
Return the ICMP or FCMP predicate value.
ArrayRef< unsigned > getIndices () const
Assert that this is an insertvalue or exactvalue expression and return the list of indices.
const char * getOpcodeName () const
Return a string representation for an opcode.
Constant * getWithOperandReplaced (unsigned OpNo, Constant *Op) const
Return a constant expression identical to this one, but with the specified operand set to the specified value.
Constant * getWithOperands (ArrayRef< Constant * > Ops) const
This returns the current constant expression with the operands replaced with the specified values.
Constant * getWithOperands (ArrayRef< Constant * > Ops, Type *Ty, bool OnlyIfReduced=false, Type *SrcTy=nullptr) const
Get the current expression with the operands replaced.
Instruction * getAsInstruction ()
Returns an Instruction which implements the same operation as this ConstantExpr.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool containsUndefElement () const
Return true if this is a vector constant that includes any undefined elements.
bool containsConstantExpression () const
Return true if this is a vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry.
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
If this is a splat vector constant, meaning that all of the elements have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, bool)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCasts ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs, aliases and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripPointerCastsNoFollowAliases () const
Strip off pointer casts and all-zero GEPs.
Value * stripPointerCastsNoFollowAliases ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
unsigned getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static Constant * getAlignOf (Type *Ty)
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
static Constant * getSizeOf (Type *Ty)
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (StructType *STy, unsigned FieldNo)
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (Type *Ty, Constant *FieldNo)
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
static Constant * getNeg (Constant *C, bool HasNUW=false, bool HasNSW=false)
static Constant * getFNeg (Constant *C)
static Constant * getNot (Constant *C)
static Constant * getAdd (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFAdd (Constant *C1, Constant *C2)
static Constant * getSub (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFSub (Constant *C1, Constant *C2)
static Constant * getMul (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFMul (Constant *C1, Constant *C2)
static Constant * getUDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getSDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getFDiv (Constant *C1, Constant *C2)
static Constant * getURem (Constant *C1, Constant *C2)
static Constant * getSRem (Constant *C1, Constant *C2)
static Constant * getFRem (Constant *C1, Constant *C2)
static Constant * getAnd (Constant *C1, Constant *C2)
static Constant * getOr (Constant *C1, Constant *C2)
static Constant * getXor (Constant *C1, Constant *C2)
static Constant * getShl (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getLShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getAShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getZExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPExtend (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getUIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToUI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToSI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getPtrToInt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getIntToPtr (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getBitCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getAddrSpaceCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getNSWNeg (Constant *C)
static Constant * getNUWNeg (Constant *C)
static Constant * getNSWAdd (Constant *C1, Constant *C2)
static Constant * getNUWAdd (Constant *C1, Constant *C2)
static Constant * getNSWSub (Constant *C1, Constant *C2)
static Constant * getNUWSub (Constant *C1, Constant *C2)
static Constant * getNSWMul (Constant *C1, Constant *C2)
static Constant * getNUWMul (Constant *C1, Constant *C2)
static Constant * getNSWShl (Constant *C1, Constant *C2)
static Constant * getNUWShl (Constant *C1, Constant *C2)
static Constant * getExactSDiv (Constant *C1, Constant *C2)
static Constant * getExactUDiv (Constant *C1, Constant *C2)
static Constant * getExactAShr (Constant *C1, Constant *C2)
static Constant * getExactLShr (Constant *C1, Constant *C2)
static Constant * getBinOpIdentity (unsigned Opcode, Type *Ty, bool AllowRHSConstant=false)
Return the identity constant for a binary opcode.
static Constant * getBinOpAbsorber (unsigned Opcode, Type *Ty)
Return the absorbing element for the given binary operation, i.e.
static Constant * getCast (unsigned ops, Constant *C, Type *Ty, bool OnlyIfReduced=false)
Convenience function for getting a Cast operation.
static Constant * getZExtOrBitCast (Constant *C, Type *Ty)
static Constant * getSExtOrBitCast (Constant *C, Type *Ty)
static Constant * getTruncOrBitCast (Constant *C, Type *Ty)
static Constant * getPointerCast (Constant *C, Type *Ty)
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
static Constant * getPointerBitCastOrAddrSpaceCast (Constant *C, Type *Ty)
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
static Constant * getIntegerCast (Constant *C, Type *Ty, bool isSigned)
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
static Constant * getFPCast (Constant *C, Type *Ty)
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
static Constant * getSelect (Constant *C, Constant *V1, Constant *V2, Type *OnlyIfReducedTy=nullptr)
Select constant expr.
static Constant * get (unsigned Opcode, Constant *C1, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
get - Return a unary operator constant expression, folding if possible.
static Constant * get (unsigned Opcode, Constant *C1, Constant *C2, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
get - Return a binary or shift operator constant expression, folding if possible.
static Constant * getCompare (unsigned short pred, Constant *C1, Constant *C2, bool OnlyIfReduced=false)
Return an ICmp or FCmp comparison operator constant expression.
static Constant * getICmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
static Constant * getFCmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
Getelementptr form.
static Constant * getGetElementPtr (Type *Ty, Constant *C, Constant *Idx, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList)
Create an "inbounds" getelementptr.
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList)
static Constant * getExtractElement (Constant *Vec, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertElement (Constant *Vec, Constant *Elt, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getShuffleVector (Constant *V1, Constant *V2, Constant *Mask, Type *OnlyIfReducedTy=nullptr)
static Constant * getExtractValue (Constant *Agg, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
ConstantExpr (Type *ty, unsigned Opcode, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Friends
struct ConstantExprKeyType
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
A constant value that is initialized with an expression using other constant values.
This class uses the standard Instruction opcodes to define the various constant expressions. The Opcode field for the ConstantExpr class is maintained in the Value::SubclassData field.
Definition at line 888 of file Constants.h.
Constructor & Destructor Documentation
ConstantExpr()
llvm::ConstantExpr::ConstantExpr (Type * ty, unsigned Opcode, Use * Ops, unsigned NumOps) inline protected
Definition at line 896 of file Constants.h.
Member Function Documentation
classof()
static bool llvm::ConstantExpr::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1256 of file Constants.h.
References llvm::Value::getValueID().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::ConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
get() [1/2]
Constant * ConstantExpr::get (unsigned Opcode, Constant * C1, Constant * C2, unsigned Flags = 0, Type * OnlyIfReducedTy = nullptr) static
get - Return a binary or shift operator constant expression, folding if possible.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1846 of file Constants.cpp.
References llvm::MCBinaryExpr::AShr, assert(), llvm::ConstantFoldBinaryInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::Value::getContext(), llvm::Value::getType(), llvm::Instruction::isBinaryOp(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::Mul, llvm::LLVMContext::pImpl, llvm::MCBinaryExpr::Shl, llvm::AtomicRMWInst::Sub, and llvm::AtomicRMWInst::Xor.
get() [2/2]
Constant * ConstantExpr::get (unsigned Opcode, Constant * C1, unsigned Flags = 0, Type * OnlyIfReducedTy = nullptr) static
get - Return a unary operator constant expression, folding if possible.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1815 of file Constants.cpp.
References assert(), C, llvm::ConstantFoldUnaryInstruction(), llvm::LLVMContextImpl::ExprConstants, and llvm::Instruction::isUnaryOp().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), getAdd(), getAnd(), getAShr(), getFAdd(), getFDiv(), getFMul(), getFNeg(), getFRem(), getFSub(), getLShr(), getMul(), getNot(), getOr(), getSDiv(), getShl(), getSRem(), getSub(), getUDiv(), getURem(), and getXor().
getAdd()
Constant * ConstantExpr::getAdd (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2228 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::AddOne(), BuildConstantFromSCEV(), canonicalizeCmpWithConstant(), computePointerICmp(), llvm::ConstantFoldGetElementPtr(), llvm::copyNonnullMetadata(), llvm::TargetFolder::CreateAdd(), llvm::ConstantFolder::CreateAdd(), foldNoWrapAdd(), getAsConstantIndexedAddress(), LLVMConstAdd(), and llvm::InstCombiner::visitAdd().
getAddrSpaceCast()
Constant * ConstantExpr::getAddrSpaceCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1794 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), llvm::IntervalMapImpl::NodeRef::get(), llvm::PointerType::getAddressSpace(), getBitCast(), llvm::PointerType::getElementType(), getFoldedCast(), and llvm::Type::getScalarType().
Referenced by cloneConstantExprWithNewAddressSpace(), getCast(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), LLVMConstAddrSpaceCast(), and operandWithNewAddressSpaceOrCreateUndef().
getAlignOf()
Constant * ConstantExpr::getAlignOf (Type * Ty) static
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
Definition at line 1915 of file Constants.cpp.
References GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::IRBuilderBase::getInt1Ty(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::Constant::getNullValue(), llvm::Type::getPointerTo(), and getPtrToInt().
Referenced by getFoldedAlignOf(), and LLVMAlignOf().
getAnd()
Constant * ConstantExpr::getAnd (Constant * C1, Constant * C2) static
Definition at line 2287 of file Constants.cpp.
References get().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastOperand(), llvm::TargetFolder::CreateAnd(), llvm::ConstantFolder::CreateAnd(), ExtractConstantBytes(), getMaskedICmpType(), LLVMConstAnd(), and llvm::InstCombiner::visitAnd().
getAShr()
Constant * ConstantExpr::getAShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2311 of file Constants.cpp.
References llvm::MCBinaryExpr::AShr, get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by llvm::TargetFolder::CreateAShr(), llvm::ConstantFolder::CreateAShr(), and LLVMConstAShr().
getAsInstruction()
Instruction * ConstantExpr::getAsInstruction ()
Returns an Instruction which implements the same operation as this ConstantExpr.
The instruction is not linked to any basic block.
A better approach to this could be to have a constructor for Instruction which would take a ConstantExpr parameter, but that would have spread implementation details of ConstantExpr outside of Constants.cpp, which would make it harder to remove ConstantExprs altogether.
Definition at line 2963 of file Constants.cpp.
References assert(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::GetElementPtrInst::Create(), llvm::UnaryOperator::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::SelectInst::Create(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), llvm::CCValAssign::FPExt, getIndices(), llvm::User::getNumOperands(), getOpcode(), getPredicate(), llvm::Value::getType(), llvm::PossiblyExactOperator::IsExact, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::User::op_begin(), llvm::User::op_end(), llvm::PtrToIntOperator::PtrToInt, llvm::MCID::Select, llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), llvm::CCValAssign::SExt, llvm::ArrayRef< T >::slice(), llvm::Value::SubclassOptionalData, and llvm::CCValAssign::ZExt.
getBinOpAbsorber()
Constant * ConstantExpr::getBinOpAbsorber (unsigned Opcode, Type * Ty) static
Return the absorbing element for the given binary operation, i.e.
a constant C such that X op C = C and C op X = C for every X. For example, this returns zero for integer multiplication. It returns null if the operator doesn't have an absorbing element.
Definition at line 2362 of file Constants.cpp.
References llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), and llvm::MCBinaryExpr::Mul.
getBinOpIdentity()
Constant * ConstantExpr::getBinOpIdentity (unsigned Opcode, Type * Ty, bool AllowRHSConstant = false) static
Return the identity constant for a binary opcode.
The identity constant C is defined as X op C = X and C op X = X for every X when the binary operation is commutative. If the binop is not commutative, callers can acquire the operand 1 identity constant by setting AllowRHSConstant to true. For example, any shift has a zero identity constant for operand 1: X shift 0 = X. Return nullptr if the operator does not have an identity constant.
Definition at line 2316 of file Constants.cpp.
References llvm::MCBinaryExpr::AShr, assert(), llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantFP::getNegativeZero(), llvm::Constant::getNullValue(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isCommutative(), llvm_unreachable, llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::Shl, llvm::AtomicRMWInst::Sub, and llvm::AtomicRMWInst::Xor.
Referenced by foldSelectBinOpIdentity(), foldSelectShuffleWith1Binop(), getIdentityValue(), llvm::getSafeVectorConstantForBinop(), and LinearizeExprTree().
getBitCast()
Constant * ConstantExpr::getBitCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1782 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), and getFoldedCast().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), appendToUsedList(), BitCastConstantVector(), BuildConstantFromSCEV(), cloneConstantExprWithNewAddressSpace(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::SanitizerStatReport::create(), llvm::SanitizerStatReport::finish(), FoldBitCast(), foldBitCastBitwiseLogic(), getAddrSpaceCast(), getCast(), getMemCmpLoad(), llvm::VNCoercion::getMemInstValueForLoadHelper(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), getSExtOrBitCast(), getTruncOrBitCast(), getZExtOrBitCast(), insertCall(), instrumentOneFunc(), llvm::isBytewiseValue(), LLVMConstBitCast(), OptimizeGlobalAddressOfMalloc(), OptimizeGlobalAliases(), optimizeMemCmpConstantSize(), optimizeOnceStoredGlobal(), removeGlobalCtors(), replaceAliasWithAliasee(), replaceWithConstant(), llvm::CoroIdInst::setCoroutineSelf(), and SimplifyRelativeLoad().
getCast()
Constant * ConstantExpr::getCast (unsigned ops, Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Convenience function for getting a Cast operation.
Parameters
ops The opcode for the conversion
C The constant to be converted
Ty The type to which the constant is converted
OnlyIfReduced see getWithOperands() docs.
Definition at line 1539 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), llvm::CCValAssign::FPExt, getAddrSpaceCast(), getBitCast(), getFPExtend(), getFPToSI(), getFPToUI(), getFPTrunc(), getIntToPtr(), getPtrToInt(), getSExt(), getSIToFP(), getTrunc(), getUIToFP(), getZExt(), llvm::Instruction::isCast(), llvm_unreachable, llvm::PtrToIntOperator::PtrToInt, llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::TargetFolder::CreateCast(), llvm::ConstantFolder::CreateCast(), llvm::orc::createIRTypedAddress(), llvm::Evaluator::EvaluateBlock(), getFoldedAlignOf(), getFoldedOffsetOf(), getFoldedSizeOf(), getFPCast(), getIntegerCast(), getWithOperands(), lookThroughCast(), OptimizeAwayTrappingUsesOfValue(), simplifyAndOrOfCmps(), simplifyAssocCastAssoc(), and SimplifyICmpInst().
getCompare()
Constant * ConstantExpr::getCompare (unsigned short pred, Constant * C1, Constant * C2, bool OnlyIfReduced = false) static
Return an ICmp or FCmp comparison operator constant expression.
Parameters
OnlyIfReduced see getWithOperands() docs.
Definition at line 1946 of file Constants.cpp.
References assert(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, getFCmp(), getICmp(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by computeUnlikelySuccessors(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateFCmp(), llvm::ConstantFolder::CreateFCmp(), llvm::TargetFolder::CreateICmp(), llvm::ConstantFolder::CreateICmp(), llvm::Evaluator::EvaluateBlock(), llvm::ValueLatticeElement::getCompare(), getWithOperands(), and llvm::InstCombiner::visitCallInst().
getExactAShr()
static Constant * llvm::ConstantExpr::getExactAShr (Constant * C1, Constant * C2) inline static
Definition at line 1016 of file Constants.h.
getExactLShr()
static Constant * llvm::ConstantExpr::getExactLShr (Constant * C1, Constant * C2) inline static
Definition at line 1020 of file Constants.h.
getExactSDiv()
static Constant * llvm::ConstantExpr::getExactSDiv (Constant * C1, Constant * C2) inline static
Definition at line 1008 of file Constants.h.
Referenced by LLVMConstExactSDiv().
getExactUDiv()
static Constant * llvm::ConstantExpr::getExactUDiv (Constant * C1, Constant * C2) inline static
Definition at line 1012 of file Constants.h.
Referenced by LLVMConstExactUDiv().
getExtractElement()
Constant * ConstantExpr::getExtractElement (Constant * Vec, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2093 of file Constants.cpp.
References assert(), llvm::ConstantFoldExtractElementInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::Value::getType(), llvm::Type::getVectorElementType(), Idx, llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by BitCastConstantVector(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), llvm::TargetFolder::CreateExtractElement(), llvm::ConstantFolder::CreateExtractElement(), getWithOperands(), and LLVMConstExtractElement().
getExtractValue()
Constant * ConstantExpr::getExtractValue (Constant * Agg, ArrayRef< unsigned > Idxs, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2185 of file Constants.cpp.
References assert(), llvm::ConstantFoldExtractValueInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Value::getType(), llvm::Type::isFirstClassType(), and llvm::LLVMContext::pImpl.
Referenced by llvm::ConstantFoldInstruction(), llvm::TargetFolder::CreateExtractValue(), llvm::ConstantFolder::CreateExtractValue(), llvm::Evaluator::EvaluateBlock(), getWithOperands(), and LLVMConstExtractValue().
getFAdd()
Constant * ConstantExpr::getFAdd (Constant * C1, Constant * C2) static
Definition at line 2235 of file Constants.cpp.
References llvm::AtomicRMWInst::FAdd, and get().
Referenced by llvm::TargetFolder::CreateFAdd(), llvm::ConstantFolder::CreateFAdd(), and LLVMConstFAdd().
getFCmp()
Constant * ConstantExpr::getFCmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
Definition at line 2068 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::IRBuilderBase::getInt1Ty(), llvm::Value::getType(), llvm::CmpInst::isFPPredicate(), llvm::LLVMContext::pImpl, and pred.
Referenced by evaluateFCmpRelation(), getCompare(), and LLVMConstFCmp().
getFDiv()
Constant * ConstantExpr::getFDiv (Constant * C1, Constant * C2) static
Definition at line 2271 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFDiv(), llvm::ConstantFolder::CreateFDiv(), foldFDivConstantDividend(), foldFDivConstantDivisor(), LLVMConstFDiv(), and llvm::InstCombiner::visitFMul().
getFMul()
Constant * ConstantExpr::getFMul (Constant * C1, Constant * C2) static
Definition at line 2257 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFMul(), llvm::ConstantFolder::CreateFMul(), foldFDivConstantDividend(), LLVMConstFMul(), and llvm::InstCombiner::visitFMul().
getFNeg()
Constant * ConstantExpr::getFNeg (Constant * C) static
Definition at line 2216 of file Constants.cpp.
References assert(), C, and get().
Referenced by llvm::TargetFolder::CreateFNeg(), llvm::ConstantFolder::CreateFNeg(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldFNegIntoConstant(), LLVMConstFNeg(), NegateValue(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFSub().
getFPCast()
Constant * ConstantExpr::getFPCast (Constant * C, Type * Ty) static
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
Definition at line 1634 of file Constants.cpp.
References assert(), C, llvm::CCValAssign::FPExt, getCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::TargetFolder::CreateFPCast(), llvm::ConstantFolder::CreateFPCast(), and LLVMConstFPCast().
getFPExtend()
Constant * ConstantExpr::getFPExtend (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1700 of file Constants.cpp.
References assert(), C, llvm::CCValAssign::FPExt, getFoldedCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isFPOrFPVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstFPExt(), and lookThroughCast().
getFPToSI()
Constant * ConstantExpr::getFPToSI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1745 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getTypeID(), llvm::Type::isIntOrIntVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstFPToSI(), lookThroughCast(), and llvm::InstCombiner::visitFAdd().
getFPToUI()
Constant * ConstantExpr::getFPToUI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1734 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getTypeID(), llvm::Type::isIntOrIntVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstFPToUI(), and lookThroughCast().
getFPTrunc()
Constant * ConstantExpr::getFPTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1688 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isFPOrFPVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstFPTrunc(), and lookThroughCast().
getFRem()
Constant * ConstantExpr::getFRem (Constant * C1, Constant * C2) static
Definition at line 2283 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFRem(), llvm::ConstantFolder::CreateFRem(), and LLVMConstFRem().
getFSub()
Constant * ConstantExpr::getFSub (Constant * C1, Constant * C2) static
Definition at line 2246 of file Constants.cpp.
References llvm::AtomicRMWInst::FSub, and get().
Referenced by llvm::TargetFolder::CreateFSub(), llvm::ConstantFolder::CreateFSub(), LLVMConstFSub(), and llvm::InstCombiner::visitFSub().
getGetElementPtr() [1/3]
static Constant * llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) inline static
Getelementptr form.
Value* is only accepted for convenience; all elements must be Constants.
Parameters
InRangeIndex the inrange index if present or None.
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1153 of file Constants.h.
References C, llvm::ArrayRef< T >::data(), llvm::makeArrayRef(), and llvm::ArrayRef< T >::size().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), llvm::SanitizerStatReport::create(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), evaluateBitcastFromPtr(), llvm::Evaluator::EvaluateBlock(), getAlignOf(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getOffsetOf(), getSizeOf(), getWithOperands(), LLVMConstGEP(), OptimizeAwayTrappingUsesOfValue(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyRelativeLoad(), splitGlobal(), and SRAGlobal().
getGetElementPtr() [2/3]
Constant * ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) static
Definition at line 1985 of file Constants.cpp.
References assert(), C, llvm::ConstantFoldGetElementPtr(), llvm::LLVMContextImpl::ExprConstants, llvm::IntervalMapImpl::NodeRef::get(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Type::getPointerTo(), llvm::ConstantVector::getSplat(), llvm::Value::getType(), Idx, llvm::None, and llvm::ArrayRef< T >::size().
getGetElementPtr() [3/3]
static Constant * llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, Constant * Idx, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) inline static
Definition at line 1162 of file Constants.h.
References C, and Idx.
getICmp()
Constant * ConstantExpr::getICmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
Definition at line 2043 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::IRBuilderBase::getInt1Ty(), llvm::Value::getType(), llvm::CmpInst::isIntPredicate(), llvm::LLVMContext::pImpl, and pred.
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstruction(), evaluateICmpRelation(), getCompare(), LLVMConstICmp(), reuseTableCompare(), SimplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), and llvm::InstCombiner::visitCallInst().
getInBoundsGetElementPtr() [1/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) inline static
Create an "inbounds" getelementptr.
See the documentation for the "inbounds" flag in LangRef.html for details.
Definition at line 1180 of file Constants.h.
References C.
Referenced by llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), FoldBitCast(), and LLVMConstInBoundsGEP().
getInBoundsGetElementPtr() [2/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) inline static
Definition at line 1191 of file Constants.h.
References C.
getInBoundsGetElementPtr() [3/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) inline static
Definition at line 1184 of file Constants.h.
References C, and Idx.
getIndices()
ArrayRef< unsigned > ConstantExpr::getIndices () const
Assert that this is an insertvalue or exactvalue expression and return the list of indices.
Definition at line 1189 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getInsertElement()
Constant * ConstantExpr::getInsertElement (Constant * Vec, Constant * Elt, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2115 of file Constants.cpp.
References assert(), llvm::ConstantFoldInsertElementInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::Value::getType(), llvm::Type::getVectorElementType(), Idx, llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by llvm::TargetFolder::CreateInsertElement(), llvm::ConstantFolder::CreateInsertElement(), getWithOperands(), and LLVMConstInsertElement().
getInsertValue()
Constant * ConstantExpr::getInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > Idxs, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2161 of file Constants.cpp.
References assert(), llvm::ConstantFoldInsertValueInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Value::getType(), llvm::Type::isFirstClassType(), and llvm::LLVMContext::pImpl.
Referenced by llvm::ConstantFoldInstruction(), llvm::TargetFolder::CreateInsertValue(), llvm::ConstantFolder::CreateInsertValue(), llvm::Evaluator::EvaluateBlock(), getWithOperands(), and LLVMConstInsertValue().
getIntegerCast()
Constant * ConstantExpr::getIntegerCast (Constant * C, Type * Ty, bool isSigned) static
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
isSigned Whether C should be treated as signed or not
Definition at line 1622 of file Constants.cpp.
References assert(), C, getCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::isIntOrIntVectorTy(), llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::TargetFolder::CreateIntCast(), llvm::ConstantFolder::CreateIntCast(), createMalloc(), llvm::EmitGEPOffset(), GetConstantInt(), llvm::isBytewiseValue(), LLVMConstIntCast(), lookThroughCast(), llvm::AsmPrinter::lowerConstant(), SimplifySubInst(), and llvm::InstCombiner::visitCallInst().
getIntToPtr()
Constant * ConstantExpr::getIntToPtr (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1769 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getVectorNumElements(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::SanitizerStatReport::create(), getCast(), llvm::Constant::getIntegerValue(), LLVMConstIntToPtr(), llvm::MergeBasicBlockIntoOnlyPred(), SegmentOffset(), SimplifyGEPInst(), SimplifyICmpInst(), llvm::UpgradeBitCastExpr(), and llvm::BasicBlock::~BasicBlock().
getLShr()
Constant * ConstantExpr::getLShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2306 of file Constants.cpp.
References get(), llvm::PossiblyExactOperator::IsExact, and llvm::MCBinaryExpr::LShr.
Referenced by collectInsertionElements(), llvm::ConstantFoldBinaryInstruction(), llvm::TargetFolder::CreateLShr(), llvm::ConstantFolder::CreateLShr(), ExtractConstantBytes(), and LLVMConstLShr().
getMul()
Constant * ConstantExpr::getMul (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2250 of file Constants.cpp.
References get(), llvm::MCBinaryExpr::Mul, llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by BuildConstantFromSCEV(), llvm::ComputeMultiple(), llvm::ConstantFoldCastInstruction(), createMalloc(), llvm::TargetFolder::CreateMul(), llvm::ConstantFolder::CreateMul(), llvm::EmitGEPOffset(), LLVMConstMul(), and llvm::InstCombiner::visitCallInst().
getNeg()
Constant * ConstantExpr::getNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2209 of file Constants.cpp.
References assert(), C, getSub(), and llvm::ConstantFP::getZeroValueForNegation().
Referenced by llvm::TargetFolder::CreateNeg(), llvm::ConstantFolder::CreateNeg(), llvm::ScalarEvolution::getNegativeSCEV(), LLVMConstNeg(), NegateValue(), TurnSwitchRangeIntoICmp(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
getNot()
Constant * ConstantExpr::getNot (Constant * C) static
Definition at line 2222 of file Constants.cpp.
References assert(), C, get(), llvm::Constant::getAllOnesValue(), and llvm::AtomicRMWInst::Xor.
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateNot(), llvm::ConstantFolder::CreateNot(), llvm::ScalarEvolution::getNotSCEV(), LLVMConstNot(), llvm::InstCombiner::visitExtractValueInst(), and llvm::InstCombiner::visitXor().
getNSWAdd()
static Constant * llvm::ConstantExpr::getNSWAdd (Constant * C1, Constant * C2) inline static
Definition at line 976 of file Constants.h.
Referenced by LLVMConstNSWAdd().
getNSWMul()
static Constant * llvm::ConstantExpr::getNSWMul (Constant * C1, Constant * C2) inline static
Definition at line 992 of file Constants.h.
Referenced by LLVMConstNSWMul().
getNSWNeg()
static Constant * llvm::ConstantExpr::getNSWNeg (Constant * C) inline static
Definition at line 973 of file Constants.h.
References C.
Referenced by LLVMConstNSWNeg().
getNSWShl()
static Constant * llvm::ConstantExpr::getNSWShl (Constant * C1, Constant * C2) inline static
Definition at line 1000 of file Constants.h.
getNSWSub()
static Constant * llvm::ConstantExpr::getNSWSub (Constant * C1, Constant * C2) inline static
Definition at line 984 of file Constants.h.
Referenced by LLVMConstNSWSub().
getNUWAdd()
static Constant * llvm::ConstantExpr::getNUWAdd (Constant * C1, Constant * C2) inline static
Definition at line 980 of file Constants.h.
Referenced by LLVMConstNUWAdd().
getNUWMul()
static Constant * llvm::ConstantExpr::getNUWMul (Constant * C1, Constant * C2) inline static
Definition at line 996 of file Constants.h.
Referenced by getFoldedOffsetOf(), getFoldedSizeOf(), and LLVMConstNUWMul().
getNUWNeg()
static Constant * llvm::ConstantExpr::getNUWNeg (Constant * C) inline static
Definition at line 974 of file Constants.h.
References C.
Referenced by LLVMConstNUWNeg().
getNUWShl()
static Constant * llvm::ConstantExpr::getNUWShl (Constant * C1, Constant * C2) inline static
Definition at line 1004 of file Constants.h.
getNUWSub()
static Constant * llvm::ConstantExpr::getNUWSub (Constant * C1, Constant * C2) inline static
Definition at line 988 of file Constants.h.
Referenced by LLVMConstNUWSub().
getOffsetOf() [1/2]
Constant * ConstantExpr::getOffsetOf (StructType * STy, unsigned FieldNo) static
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
Definition at line 1928 of file Constants.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), llvm::IRBuilderBase::getInt32Ty(), and getOffsetOf().
Referenced by getFoldedOffsetOf(), and getOffsetOf().
getOffsetOf() [2/2]
Constant * ConstantExpr::getOffsetOf (Type * Ty, Constant * FieldNo) static
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
Definition at line 1933 of file Constants.cpp.
References GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::IRBuilderBase::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
getOpcode()
unsigned llvm::ConstantExpr::getOpcode () const inline
Return the opcode at the root of this constant expression.
Definition at line 1209 of file Constants.h.
Referenced by evaluateFCmpRelation(), evaluateICmpRelation(), getAsInstruction(), getOpcodeName(), getWithOperands(), hasIndices(), isCast(), isCompare(), isGEPWithNoNotionalOverIndexing(), and llvm::Constant::needsRelocation().
getOpcodeName()
const char * ConstantExpr::getOpcodeName () const
Return a string representation for an opcode.
Definition at line 2382 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::getOpcodeName().
getOr()
Constant * ConstantExpr::getOr (Constant * C1, Constant * C2) static
Definition at line 2291 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateOr(), llvm::ConstantFolder::CreateOr(), ExtractConstantBytes(), foldLogOpOfMaskedICmps(), LLVMConstOr(), and llvm::InstCombiner::visitOr().
getPointerBitCastOrAddrSpaceCast()
Constant * ConstantExpr::getPointerBitCastOrAddrSpaceCast (Constant * C, Type * Ty) static
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
Parameters
C The constant to addrspacecast or bitcast
Ty The type to bitcast or addrspacecast C to
Definition at line 1611 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast(), setUsedInitializer(), and llvm::InstCombiner::visitAllocaInst().
getPointerCast()
Constant * ConstantExpr::getPointerCast (Constant * C, Type * Ty) static
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
Parameters
C The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Definition at line 1596 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), getPtrToInt(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by appendToGlobalArray(), llvm::ConstantFoldCastInstruction(), llvm::TargetFolder::CreatePointerCast(), llvm::ConstantFolder::CreatePointerCast(), INITIALIZE_PASS(), LLVMConstPointerCast(), and setCoroInfo().
getPredicate()
unsigned ConstantExpr::getPredicate () const
Return the ICMP or FCMP predicate value.
Assert if this is not an ICMP or FCMP constant expression.
Definition at line 1197 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getPtrToInt()
Constant * ConstantExpr::getPtrToInt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1756 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getVectorNumElements(), llvm::Type::isIntOrIntVectorTy(), and llvm::PtrToIntOperator::PtrToInt.
Referenced by llvm::copyNonnullMetadata(), getAlignOf(), getCast(), getOffsetOf(), getPointerCast(), getSizeOf(), LLVMConstPtrToInt(), and llvm::UpgradeBitCastExpr().
getSDiv()
Constant * ConstantExpr::getSDiv (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2266 of file Constants.cpp.
References get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::TargetFolder::CreateSDiv(), llvm::ConstantFolder::CreateSDiv(), and LLVMConstSDiv().
getSelect()
Constant * ConstantExpr::getSelect (Constant * C, Constant * V1, Constant * V2, Type * OnlyIfReducedTy = nullptr) static
Select constant expr.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1968 of file Constants.cpp.
References llvm::SelectInst::areInvalidOperands(), assert(), C, llvm::ConstantFoldSelectInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getType(), and llvm::MCID::Select.
Referenced by cloneConstantExprWithNewAddressSpace(), llvm::ConstantFoldSelectInstruction(), llvm::TargetFolder::CreateSelect(), llvm::ConstantFolder::CreateSelect(), llvm::Evaluator::EvaluateBlock(), getWithOperands(), and LLVMConstSelect().
getSExt()
Constant * ConstantExpr::getSExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1660 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isIntOrIntVectorTy(), llvm::CCValAssign::SExt, and llvm::Type::VectorTyID.
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), foldLogicCastConstant(), foldNoWrapAdd(), getCast(), getSExtOrBitCast(), llvm::ScalarEvolution::getSignExtendExpr(), LLVMConstSExt(), and llvm::InstCombiner::visitCallInst().
getSExtOrBitCast()
Constant * ConstantExpr::getSExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to sext or bitcast
Ty The type to sext or bitcast C to
Definition at line 1584 of file Constants.cpp.
References C, getBitCast(), llvm::Type::getScalarSizeInBits(), and getSExt().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::TargetFolder::CreateSExtOrBitCast(), llvm::ConstantFolder::CreateSExtOrBitCast(), getAsConstantIndexedAddress(), and LLVMConstSExtOrBitCast().
getShl()
Constant * ConstantExpr::getShl (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2299 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and llvm::MCBinaryExpr::Shl.
Referenced by ConvertShiftToMul(), llvm::TargetFolder::CreateShl(), llvm::ConstantFolder::CreateShl(), llvm::InstCombiner::FoldShiftByConstant(), getAlternateBinop(), getBinOpsForFactorization(), LLVMConstShl(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitShl().
getShuffleVector()
Constant * ConstantExpr::getShuffleVector (Constant * V1, Constant * V2, Constant * Mask, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2138 of file Constants.cpp.
References assert(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), llvm::Value::getType(), llvm::Type::getVectorElementType(), llvm::ShuffleVectorInst::isValidOperands(), and llvm::LLVMContext::pImpl.
Referenced by llvm::TargetFolder::CreateShuffleVector(), llvm::ConstantFolder::CreateShuffleVector(), evaluateInDifferentElementOrder(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), getWithOperands(), and LLVMConstShuffleVector().
getSIToFP()
Constant * ConstantExpr::getSIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1723 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getTypeID(), llvm::Type::isFPOrFPVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstSIToFP(), lookThroughCast(), and llvm::InstCombiner::visitFAdd().
getSizeOf()
Constant * ConstantExpr::getSizeOf (Type * Ty) static
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
Definition at line 1905 of file Constants.cpp.
References GEP, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
Referenced by getFoldedSizeOf(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMSizeOf().
getSRem()
Constant * ConstantExpr::getSRem (Constant * C1, Constant * C2) static
Definition at line 2279 of file Constants.cpp.
References get().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::TargetFolder::CreateSRem(), llvm::ConstantFolder::CreateSRem(), and LLVMConstSRem().
getSub()
Constant * ConstantExpr::getSub (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2239 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and llvm::AtomicRMWInst::Sub.
Referenced by computePointerDifference(), llvm::TargetFolder::CreateSub(), llvm::ConstantFolder::CreateSub(), getNeg(), LLVMConstSub(), llvm::SubOne(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitSwitchInst().
getTrunc()
Constant * ConstantExpr::getTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1646 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isIntOrIntVectorTy(), and llvm::Type::VectorTyID.
Referenced by BuildConstantFromSCEV(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), ExtractConstantBytes(), foldLogicCastConstant(), getCast(), llvm::ScalarEvolution::getTruncateExpr(), getTruncOrBitCast(), LLVMConstTrunc(), lookThroughCast(), narrowUDivURem(), SimplifyICmpInst(), llvm::InstCombiner::visitAnd(), and llvm::InstCombiner::visitSDiv().
getTruncOrBitCast()
Constant * ConstantExpr::getTruncOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to trunc or bitcast
Ty The type to trunc or bitcast C to
Definition at line 1590 of file Constants.cpp.
References C, getBitCast(), llvm::Type::getScalarSizeInBits(), and getTrunc().
Referenced by llvm::TargetFolder::CreateTruncOrBitCast(), llvm::ConstantFolder::CreateTruncOrBitCast(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMConstTruncOrBitCast().
getUDiv()
Constant * ConstantExpr::getUDiv (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2261 of file Constants.cpp.
References get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by BuildConstantFromSCEV(), llvm::TargetFolder::CreateUDiv(), llvm::ConstantFolder::CreateUDiv(), llvm::ScalarEvolution::getUDivExpr(), and LLVMConstUDiv().
getUIToFP()
Constant * ConstantExpr::getUIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1712 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getTypeID(), llvm::Type::isFPOrFPVectorTy(), and llvm::Type::VectorTyID.
Referenced by getCast(), LLVMConstUIToFP(), and lookThroughCast().
getURem()
Constant * ConstantExpr::getURem (Constant * C1, Constant * C2) static
Definition at line 2275 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateURem(), llvm::ConstantFolder::CreateURem(), LLVMConstURem(), and llvm::InstCombiner::visitCallInst().
getWithOperandReplaced()
Constant * ConstantExpr::getWithOperandReplaced (unsigned OpNo, Constant * Op) const
Return a constant expression identical to this one, but with the specified operand set to the specified value.
Definition at line 1202 of file Constants.cpp.
References assert(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), getWithOperands(), llvm::User::Op(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getWithOperands() [1/2]
Constant * llvm::ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops) const inline
This returns the current constant expression with the operands replaced with the specified values.
The specified array must have the same number of operands as our current one.
Definition at line 1229 of file Constants.h.
References getType().
Referenced by getWithOperandReplaced().
getWithOperands() [2/2]
Constant * ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops, Type * Ty, bool OnlyIfReduced = false, Type * SrcTy = nullptr) const
Get the current expression with the operands replaced.
Return the current constant expression with the operands replaced with Ops and the type with Ty. The new operands must have the same number as the current ones.
If OnlyIfReduced is true, nullptr will be returned unless something gets constant-folded, the type changes, or the expression is otherwise canonicalized. This parameter should almost always be false.
Definition at line 1215 of file Constants.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::CCValAssign::FPExt, llvm::IntervalMapImpl::NodeRef::get(), getCast(), getCompare(), getExtractElement(), getExtractValue(), getGetElementPtr(), getIndices(), getInsertElement(), getInsertValue(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), getPredicate(), getSelect(), getShuffleVector(), llvm::Value::getType(), llvm::User::op_begin(), llvm::PtrToIntOperator::PtrToInt, llvm::MCID::Select, llvm::CCValAssign::SExt, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), llvm::Value::SubclassOptionalData, and llvm::CCValAssign::ZExt.
getXor()
Constant * ConstantExpr::getXor (Constant * C1, Constant * C2) static
Definition at line 2295 of file Constants.cpp.
References get(), and llvm::AtomicRMWInst::Xor.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateXor(), llvm::ConstantFolder::CreateXor(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), LLVMConstXor(), and llvm::InstCombiner::visitAdd().
getZExt()
Constant * ConstantExpr::getZExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 1674 of file Constants.cpp.
References assert(), C, getFoldedCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::VectorTyID, and llvm::CCValAssign::ZExt.
Referenced by BuildConstantFromSCEV(), llvm::ComputeMultiple(), foldLogicCastConstant(), foldNoWrapAdd(), llvm::InstCombiner::FoldShiftByConstant(), getCast(), llvm::ScalarEvolution::getZeroExtendExpr(), getZExtOrBitCast(), LLVMConstZExt(), narrowUDivURem(), and llvm::InstCombiner::visitZExt().
getZExtOrBitCast()
Constant * ConstantExpr::getZExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to zext or bitcast
Ty The type to zext or bitcast C to
Definition at line 1578 of file Constants.cpp.
References C, getBitCast(), llvm::Type::getScalarSizeInBits(), and getZExt().
Referenced by llvm::TargetFolder::CreateZExtOrBitCast(), llvm::ConstantFolder::CreateZExtOrBitCast(), and LLVMConstZExtOrBitCast().
hasIndices()
bool ConstantExpr::hasIndices () const
Return true if this is an insertvalue or extractvalue expression, and the getIndices() method may be used.
Definition at line 1184 of file Constants.cpp.
References getOpcode().
isCast()
bool ConstantExpr::isCast () const
Return true if this is a convert constant expression.
Definition at line 1154 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::isCast().
isCompare()
bool ConstantExpr::isCompare () const
Return true if this is a compare constant expression.
Definition at line 1158 of file Constants.cpp.
References getOpcode().
isGEPWithNoNotionalOverIndexing()
bool ConstantExpr::isGEPWithNoNotionalOverIndexing () const
Return true if this is a getelementptr expression and all the index operands are compile-time known integers within the corresponding notional static array extents.
Note that this is not equivalant to, a subset of, or a superset of the "inbounds" property.
Definition at line 1162 of file Constants.cpp.
References E, llvm::gep_type_begin(), llvm::gep_type_end(), getOpcode(), llvm::generic_gep_type_iterator< ItTy >::getSequentialNumElements(), llvm::generic_gep_type_iterator< ItTy >::isBoundedSequential(), and llvm::User::op_begin().
Referenced by evaluateICmpRelation().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 890 of file Constants.h.
ConstantExprKeyType
friend struct ConstantExprKeyType friend
Definition at line 889 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp