LLVM: llvm::orc::ObjectLinkingLayerJITLinkContext Class Reference
llvm::orc::ObjectLinkingLayerJITLinkContext Class Reference final
Public Member Functions
ObjectLinkingLayerJITLinkContext (ObjectLinkingLayer &Layer, MaterializationResponsibility MR, std::unique_ptr< MemoryBuffer > ObjBuffer)
JITLinkMemoryManager & getMemoryManager () override
Return the MemoryManager to be used for this link.
MemoryBufferRef getObjectBuffer () const override
Returns a StringRef for the object buffer.
void notifyFailed (Error Err) override
Notify this context that linking failed.
void lookup (const DenseSet< StringRef > &Symbols, JITLinkAsyncLookupContinuation LookupContinuation) override
Called by JITLink to resolve external symbols.
void notifyResolved (AtomGraph &G) override
Called by JITLink once all defined atoms in the graph have been assigned their final memory locations in the target process.
void notifyFinalized (std::unique_ptr< JITLinkMemoryManager::Allocation > A) override
Called by JITLink to notify the context that the object has been finalized (i.e.
AtomGraphPassFunction getMarkLivePass (const Triple &TT) const override
Returns the mark-live pass to be used for this link.
Error modifyPassConfig (const Triple &TT, PassConfiguration &Config) override
Called by JITLink to modify the pass pipeline prior to linking.
Public Member Functions inherited from llvm::jitlink::JITLinkContext
virtual ~JITLinkContext ()
Destroy a JITLinkContext.
virtual JITLinkMemoryManager & getMemoryManager ()=0
Return the MemoryManager to be used for this link.
virtual MemoryBufferRef getObjectBuffer () const =0
Returns a StringRef for the object buffer.
virtual void notifyFailed (Error Err)=0
Notify this context that linking failed.
virtual void lookup (const DenseSet< StringRef > &Symbols, JITLinkAsyncLookupContinuation LookupContinuation)=0
Called by JITLink to resolve external symbols.
virtual void notifyResolved (AtomGraph &G)=0
Called by JITLink once all defined atoms in the graph have been assigned their final memory locations in the target process.
virtual void notifyFinalized (std::unique_ptr< JITLinkMemoryManager::Allocation > A)=0
Called by JITLink to notify the context that the object has been finalized (i.e.
virtual bool shouldAddDefaultTargetPasses (const Triple &TT) const
Called by JITLink prior to linking to determine whether default passes for the target should be added.
virtual AtomGraphPassFunction getMarkLivePass (const Triple &TT) const
Returns the mark-live pass to be used for this link.
virtual Error modifyPassConfig (const Triple &TT, PassConfiguration &Config)
Called by JITLink to modify the pass pipeline prior to linking.
Detailed Description
Definition at line 25 of file ObjectLinkingLayer.cpp.
Constructor & Destructor Documentation
ObjectLinkingLayerJITLinkContext()
llvm::orc::ObjectLinkingLayerJITLinkContext::ObjectLinkingLayerJITLinkContext (ObjectLinkingLayer & Layer, MaterializationResponsibility MR, std::unique_ptr< MemoryBuffer > ObjBuffer) inline
Definition at line 27 of file ObjectLinkingLayer.cpp.
Member Function Documentation
getMarkLivePass()
AtomGraphPassFunction llvm::orc::ObjectLinkingLayerJITLinkContext::getMarkLivePass (const Triple & TT) const inline override virtual
Returns the mark-live pass to be used for this link.
If no pass is returned (the default) then the target-specific linker implementation will choose a conservative default (usually marking all atoms live). This function is only called if shouldAddDefaultTargetPasses returns true, otherwise the JITContext is responsible for adding a mark-live pass in modifyPassConfig.
Reimplemented from llvm::jitlink::JITLinkContext.
Definition at line 147 of file ObjectLinkingLayer.cpp.
References G.
getMemoryManager()
JITLinkMemoryManager & llvm::orc::ObjectLinkingLayerJITLinkContext::getMemoryManager () inline override virtual
Return the MemoryManager to be used for this link.
Implements llvm::jitlink::JITLinkContext.
Definition at line 32 of file ObjectLinkingLayer.cpp.
getObjectBuffer()
MemoryBufferRef llvm::orc::ObjectLinkingLayerJITLinkContext::getObjectBuffer () const inline override virtual
Returns a StringRef for the object buffer.
This method can not be called once takeObjectBuffer has been called.
Implements llvm::jitlink::JITLinkContext.
Definition at line 34 of file ObjectLinkingLayer.cpp.
lookup()
void llvm::orc::ObjectLinkingLayerJITLinkContext::lookup (const DenseSet< StringRef > & Symbols, JITLinkAsyncLookupContinuation LookupContinuation) inline override virtual
Called by JITLink to resolve external symbols.
This method is passed a lookup continutation which it must call with a result to continue the linking process.
Implements llvm::jitlink::JITLinkContext.
Definition at line 43 of file ObjectLinkingLayer.cpp.
References llvm::orc::ObjectLayer::getExecutionSession(), llvm::orc::MaterializationResponsibility::getTargetJITDylib(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::orc::Resolved, and llvm::orc::JITDylib::withSearchOrderDo().
modifyPassConfig()
Error llvm::orc::ObjectLinkingLayerJITLinkContext::modifyPassConfig (const Triple & TT, PassConfiguration & Config) inline override virtual
Called by JITLink to modify the pass pipeline prior to linking.
The default version performs no modification.
Reimplemented from llvm::jitlink::JITLinkContext.
Definition at line 151 of file ObjectLinkingLayer.cpp.
References G, llvm::jitlink::PassConfiguration::PostPrunePasses, llvm::jitlink::PassConfiguration::PrePrunePasses, llvm::Error::success(), and TT.
notifyFailed()
void llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFailed (Error Err) inline override virtual
Notify this context that linking failed.
Called by JITLink if linking cannot be completed.
Implements llvm::jitlink::JITLinkContext.
Definition at line 38 of file ObjectLinkingLayer.cpp.
References llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::ObjectLayer::getExecutionSession(), and llvm::orc::ExecutionSession::reportError().
Referenced by notifyResolved().
notifyFinalized()
void llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized (std::unique_ptr< JITLinkMemoryManager::Allocation > A) inline override virtual
Called by JITLink to notify the context that the object has been finalized (i.e.
emitted to memory and memory permissions set). If all of this objects dependencies have also been finalized then the code is ready to run.
Implements llvm::jitlink::JITLinkContext.
Definition at line 135 of file ObjectLinkingLayer.cpp.
References A, llvm::orc::MaterializationResponsibility::failMaterialization(), llvm::orc::ObjectLayer::getExecutionSession(), llvm::orc::MaterializationResponsibility::notifyEmitted(), and llvm::orc::ExecutionSession::reportError().
notifyResolved()
void llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved (AtomGraph & G) inline override virtual
Called by JITLink once all defined atoms in the graph have been assigned their final memory locations in the target process.
At this point he atom graph can be, inspected to build a symbol table however the atom content will not generally have been copied to the target location yet.
Implements llvm::jitlink::JITLinkContext.
Definition at line 78 of file ObjectLinkingLayer.cpp.
References A, llvm::JITSymbolFlags::Absolute, assert(), llvm::JITSymbolFlags::Callable, llvm::JITSymbolFlags::Common, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::orc::MaterializationResponsibility::defineMaterializing(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::JITSymbolFlags::Exported, G, llvm::orc::ObjectLayer::getExecutionSession(), llvm::orc::MaterializationResponsibility::getSymbols(), notifyFailed(), llvm::orc::MaterializationResponsibility::notifyResolved(), and llvm::JITSymbolFlags::Weak.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp