LLVM: llvm::MDTupleTypedArrayWrapper< T > Class Template Reference
llvm::MDTupleTypedArrayWrapper< T > Class Template Reference
Typed, array-like tuple of metadata.
#include "llvm/IR/Metadata.h"
Public Types
using iterator = TypedMDOperandIterator< T >
Public Member Functions
MDTupleTypedArrayWrapper ()=default
MDTupleTypedArrayWrapper (const MDTuple *N)
template<class U >
MDTupleTypedArrayWrapper (const MDTupleTypedArrayWrapper< U > &Other, typename std::enable_if< std::is_convertible< U *, T * >::value >::type *=nullptr)
template<class U >
MDTupleTypedArrayWrapper (const MDTupleTypedArrayWrapper< U > &Other, typename std::enable_if<!std::is_convertible< U *, T * >::value >::type *=nullptr)
operator bool () const
operator MDTuple * () const
MDTuple * get () const
MDTuple * operator-> () const
MDTuple & operator* () const
unsigned size () const
bool empty () const
T * operator[] (unsigned I) const
iterator begin () const
iterator end () const
Detailed Description
template<class T>
class llvm::MDTupleTypedArrayWrapper< T >
Typed, array-like tuple of metadata.
This is a wrapper for MDTuple that makes it act like an array holding a particular type of metadata.
Definition at line 1221 of file Metadata.h.
Member Typedef Documentation
iterator
template<class T > using llvm::MDTupleTypedArrayWrapper< T >::iterator = TypedMDOperandIterator<T>
Definition at line 1255 of file Metadata.h.
Constructor & Destructor Documentation
MDTupleTypedArrayWrapper() [1/4]
template<class T > llvm::MDTupleTypedArrayWrapper< T >::MDTupleTypedArrayWrapper () default
MDTupleTypedArrayWrapper() [2/4]
template<class T > llvm::MDTupleTypedArrayWrapper< T >::MDTupleTypedArrayWrapper (const MDTuple * N) inline
Definition at line 1226 of file Metadata.h.
References N.
MDTupleTypedArrayWrapper() [3/4]
template<class T > template<class U > llvm::MDTupleTypedArrayWrapper< T >::MDTupleTypedArrayWrapper (const MDTupleTypedArrayWrapper< U > & Other, typename std::enable_if< std::is_convertible< U *, T * >::value >::type * = nullptr) inline
Definition at line 1229 of file Metadata.h.
References N.
MDTupleTypedArrayWrapper() [4/4]
template<class T > template<class U > llvm::MDTupleTypedArrayWrapper< T >::MDTupleTypedArrayWrapper (const MDTupleTypedArrayWrapper< U > & Other, typename std::enable_if<!std::is_convertible< U *, T * >::value >::type * = nullptr) inline explicit
Definition at line 1236 of file Metadata.h.
References N.
Member Function Documentation
begin()
template<class T > iterator llvm::MDTupleTypedArrayWrapper< T >::begin () const inline
Definition at line 1257 of file Metadata.h.
References N.
empty()
template<class T > bool llvm::MDTupleTypedArrayWrapper< T >::empty () const inline
Definition at line 1251 of file Metadata.h.
References N.
end()
template<class T > iterator llvm::MDTupleTypedArrayWrapper< T >::end () const inline
Definition at line 1258 of file Metadata.h.
References N.
get()
template<class T > MDTuple * llvm::MDTupleTypedArrayWrapper< T >::get () const inline
Definition at line 1245 of file Metadata.h.
References N.
Referenced by llvm::MDTupleTypedArrayWrapper< T >::operator bool(), llvm::MDTupleTypedArrayWrapper< T >::operator MDTuple *(), llvm::MDTupleTypedArrayWrapper< T >::operator*(), and llvm::MDTupleTypedArrayWrapper< T >::operator->().
operator bool()
template<class T > llvm::MDTupleTypedArrayWrapper< T >::operator bool () const inline explicit
Definition at line 1242 of file Metadata.h.
References llvm::MDTupleTypedArrayWrapper< T >::get().
operator MDTuple *()
template<class T > llvm::MDTupleTypedArrayWrapper< T >::operator MDTuple * () const inline explicit
Definition at line 1243 of file Metadata.h.
References llvm::MDTupleTypedArrayWrapper< T >::get().
operator*()
template<class T > MDTuple & llvm::MDTupleTypedArrayWrapper< T >::operator* () const inline
Definition at line 1247 of file Metadata.h.
References llvm::MDTupleTypedArrayWrapper< T >::get().
operator->()
template<class T > MDTuple * llvm::MDTupleTypedArrayWrapper< T >::operator-> () const inline
Definition at line 1246 of file Metadata.h.
References llvm::MDTupleTypedArrayWrapper< T >::get().
operator[]()
template<class T > T * llvm::MDTupleTypedArrayWrapper< T >::operator[] (unsigned I) const inline
Definition at line 1252 of file Metadata.h.
References I, and N.
size()
template<class T > unsigned llvm::MDTupleTypedArrayWrapper< T >::size () const inline
Definition at line 1250 of file Metadata.h.
References N.
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h