LLVM: llvm::legacy::FunctionPassManager Class Reference
llvm::legacy::FunctionPassManager Class Reference
FunctionPassManager manages FunctionPasses and BasicBlockPassManagers.
#include "llvm/IR/LegacyPassManager.h"
Public Member Functions
FunctionPassManager (Module *M)
FunctionPassManager ctor - This initializes the pass manager.
~FunctionPassManager () override
void add (Pass *P) override
Add a pass to the queue of passes to run.
bool run (Function &F)
run - Execute all of the passes scheduled for execution.
bool doInitialization ()
doInitialization - Run all of the initializers for the function passes.
bool doFinalization ()
doFinalization - Run all of the finalizers for the function passes.
Public Member Functions inherited from llvm::legacy::PassManagerBase
virtual ~PassManagerBase ()
virtual void add (Pass *P)=0
Add a pass to the queue of passes to run.
Detailed Description
FunctionPassManager manages FunctionPasses and BasicBlockPassManagers.
Definition at line 67 of file LegacyPassManager.h.
Constructor & Destructor Documentation
FunctionPassManager()
FunctionPassManager::FunctionPassManager (Module * M) explicit
FunctionPassManager ctor - This initializes the pass manager.
Create new Function pass manager.
It needs, but does not take ownership of, the specified Module.
Definition at line 1485 of file LegacyPassManager.cpp.
References llvm::PMDataManager::setTopLevelManager().
~FunctionPassManager()
FunctionPassManager::~FunctionPassManager () override
Definition at line 1494 of file LegacyPassManager.cpp.
Member Function Documentation
add()
void FunctionPassManager::add (Pass * P) override virtual
Add a pass to the queue of passes to run.
This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Implements llvm::legacy::PassManagerBase.
Definition at line 1498 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::add(), and P.
Referenced by invokeFunctionPass(), llvm::lintFunction(), llvm::PassManagerBuilder::populateFunctionPassManager(), postSplitCleanup(), and simplifyCFG().
doFinalization()
bool FunctionPassManager::doFinalization ()
doFinalization - Run all of the finalizers for the function passes.
Definition at line 1522 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::doFinalization().
Referenced by invokeFunctionPass(), postSplitCleanup(), and simplifyCFG().
doInitialization()
bool FunctionPassManager::doInitialization ()
doInitialization - Run all of the initializers for the function passes.
Definition at line 1516 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::doInitialization().
Referenced by invokeFunctionPass(), postSplitCleanup(), and simplifyCFG().
run()
bool FunctionPassManager::run (Function & F)
run - Execute all of the passes scheduled for execution.
Keep track of whether any of the passes modifies the function, and if so, return true.
Definition at line 1506 of file LegacyPassManager.cpp.
References F, llvm::handleAllErrors(), and llvm::legacy::FunctionPassManagerImpl::run().
Referenced by invokeFunctionPass(), llvm::lintFunction(), postSplitCleanup(), llvm::FunctionToLoopPassAdaptor< LoopPassT >::run(), and simplifyCFG().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManager.h
lib/IR/LegacyPassManager.cpp