LLVM: llvm::CodeExtractor Class Reference
llvm::CodeExtractor Class Reference
Utility class for extracting code into a new function.
#include "llvm/Transforms/Utils/CodeExtractor.h"
Public Member Functions
CodeExtractor (ArrayRef< BasicBlock * > BBs, DominatorTree *DT=nullptr, bool AggregateArgs=false, BlockFrequencyInfo *BFI=nullptr, BranchProbabilityInfo *BPI=nullptr, AssumptionCache *AC=nullptr, bool AllowVarArgs=false, bool AllowAlloca=false, std::string Suffix="")
Create a code extractor for a sequence of blocks.
CodeExtractor (DominatorTree &DT, Loop &L, bool AggregateArgs=false, BlockFrequencyInfo *BFI=nullptr, BranchProbabilityInfo *BPI=nullptr, AssumptionCache *AC=nullptr, std::string Suffix="")
Create a code extractor for a loop body.
Function * extractCodeRegion ()
Perform the extraction, returning the new function.
bool isEligible () const
Test whether this code extractor is eligible.
void findInputsOutputs (ValueSet &Inputs, ValueSet &Outputs, const ValueSet &Allocas) const
Compute the set of input values and output values for the code.
bool isLegalToShrinkwrapLifetimeMarkers (Instruction *AllocaAddr) const
Check if life time marker nodes can be hoisted/sunk into the outline region.
void findAllocas (ValueSet &SinkCands, ValueSet &HoistCands, BasicBlock *&ExitBlock) const
Find the set of allocas whose life ranges are contained within the outlined region.
BasicBlock * findOrCreateBlockForHoisting (BasicBlock *CommonExitBlock)
Find or create a block within the outline region for placing hoisted code.
Detailed Description
Utility class for extracting code into a new function.
This utility provides a simple interface for extracting some sequence of code into its own function, replacing it with a call to that function. It also provides various methods to query about the nature and result of such a transformation.
The rough algorithm used is: 1) Find both the inputs and outputs for the extracted region. 2) Pass the inputs as arguments, remapping them within the extracted function to arguments. 3) Add allocas for any scalar outputs, adding all of the outputs' allocas as arguments, and inserting stores to the arguments for any scalars.
Definition at line 52 of file CodeExtractor.h.
Constructor & Destructor Documentation
CodeExtractor() [1/2]
CodeExtractor::CodeExtractor (ArrayRef< BasicBlock * > BBs, DominatorTree * DT = nullptr, bool AggregateArgs = false, BlockFrequencyInfo * BFI = nullptr, BranchProbabilityInfo * BPI = nullptr, AssumptionCache * AC = nullptr, bool AllowVarArgs = false, bool AllowAlloca = false, std::string Suffix = "")
Create a code extractor for a sequence of blocks.
Given a sequence of basic blocks where the first block in the sequence dominates the rest, prepare a code extractor object for pulling this sequence out into its new function. When a DominatorTree is also given, extra checking and transformations are enabled. If AllowVarArgs is true, vararg functions can be extracted. This is safe, if all vararg handling code is extracted, including vastart. If AllowAlloca is true, then extraction of blocks containing alloca instructions would be possible, however code extractor won't validate whether extraction is legal.
Definition at line 244 of file CodeExtractor.cpp.
CodeExtractor() [2/2]
CodeExtractor::CodeExtractor (DominatorTree & DT, Loop & L, bool AggregateArgs = false, BlockFrequencyInfo * BFI = nullptr, BranchProbabilityInfo * BPI = nullptr, AssumptionCache * AC = nullptr, std::string Suffix = "")
Create a code extractor for a loop body.
Behaves just like the generic code sequence constructor, but uses the block sequence of the loop.
Definition at line 254 of file CodeExtractor.cpp.
Member Function Documentation
extractCodeRegion()
Function * CodeExtractor::extractCodeRegion ()
Perform the extraction, returning the new function.
Returns zero when called on a CodeExtractor instance where isEligible returns false.
Definition at line 1335 of file CodeExtractor.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::BranchInst::Create(), llvm::BasicBlock::Create(), llvm::Value::dump(), llvm::Instruction::eraseFromParent(), eraseLifetimeMarkersOnInputs(), llvm::errs(), F, findAllocas(), llvm::findDbgUsers(), findInputsOutputs(), findOrCreateBlockForHoisting(), llvm::BlockFrequencyInfo::getBlockFreq(), llvm::BasicBlock::getContext(), llvm::BranchProbabilityInfo::getEdgeProbability(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BlockFrequency::getFrequency(), llvm::Function::getFunctionType(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::BasicBlock::getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Function::getPersonalityFn(), llvm::BlockFrequencyInfo::getProfileCountFromFreq(), llvm::Function::getSubprogram(), llvm::BasicBlock::getTerminator(), llvm::Function::hasPersonalityFn(), I, insertLifetimeMarkersSurroundingCall(), isEligible(), llvm::FunctionType::isVarArg(), LLVM_DEBUG, llvm::Instruction::moveBefore(), llvm::Function::PCT_Real, llvm::predecessors(), llvm::report_fatal_error(), llvm::BlockFrequencyInfo::setBlockFreq(), llvm::Function::setDoesNotReturn(), llvm::Function::setEntryCount(), llvm::PHINode::setIncomingBlock(), llvm::Function::setPersonalityFn(), llvm::succ_begin(), llvm::succ_end(), and llvm::verifyFunction().
findAllocas()
void CodeExtractor::findAllocas (ValueSet & SinkCands, ValueSet & HoistCands, BasicBlock *& ExitBlock) const
Find the set of allocas whose life ranges are contained within the outlined region.
Allocas which have life_time markers contained in the outlined region should be pushed to the outlined function. The address bitcasts that are used by the lifetime markers are also candidates for shrink- wrapping. The instructions that need to be sunk are collected in 'Allocas'.
Definition at line 460 of file CodeExtractor.cpp.
References assert(), llvm::dbgs(), definedInRegion(), getCommonExitBlock(), getParent(), I, LLVM_DEBUG, and llvm::Value::users().
Referenced by extractCodeRegion().
findInputsOutputs()
void CodeExtractor::findInputsOutputs (ValueSet & Inputs, ValueSet & Outputs, const ValueSet & Allocas) const
Compute the set of input values and output values for the code.
These can be used either when performing the extraction or to evaluate the expected size of a call to the extracted function. Note that this work cannot be cached between the two as once we decide to extract a code sequence, that sequence is modified, including changing these sets, before extraction occurs. These modifications won't have any significant impact on the cost however.
Definition at line 540 of file CodeExtractor.cpp.
References definedInCaller(), definedInRegion(), and llvm::Value::users().
Referenced by extractCodeRegion().
findOrCreateBlockForHoisting()
BasicBlock * CodeExtractor::findOrCreateBlockForHoisting (BasicBlock * CommonExitBlock)
Find or create a block within the outline region for placing hoisted code.
CommonExitBlock is block outside the outline region. It is the common successor of blocks inside the region. If there exists a single block inside the region that is the predecessor of CommonExitBlock, that block will be returned. Otherwise CommonExitBlock will be split and the original block will be added to the outline region.
Definition at line 360 of file CodeExtractor.cpp.
References assert(), llvm::BasicBlock::getFirstNonPHI(), llvm::BasicBlock::getTerminator(), I, llvm::pred_begin(), llvm::pred_end(), llvm::predecessors(), and llvm::BasicBlock::splitBasicBlock().
Referenced by extractCodeRegion().
isEligible()
bool llvm::CodeExtractor::isEligible () const inline
Test whether this code extractor is eligible.
Based on the blocks used when constructing the code extractor, determine whether it is eligible for extraction.
Definition at line 113 of file CodeExtractor.h.
Referenced by extractCodeRegion().
isLegalToShrinkwrapLifetimeMarkers()
bool CodeExtractor::isLegalToShrinkwrapLifetimeMarkers (Instruction * AllocaAddr) const
Check if life time marker nodes can be hoisted/sunk into the outline region.
Returns true if it is safe to do the code motion.
Definition at line 310 of file CodeExtractor.cpp.
References getParent(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::Instruction::isLifetimeStartOrEnd(), and llvm::Value::stripInBoundsConstantOffsets().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/CodeExtractor.h
lib/Transforms/Utils/CodeExtractor.cpp