LLVM: llvm::MachineOperandIteratorBase Class Reference
llvm::MachineOperandIteratorBase Class Reference
MachineOperandIteratorBase - Iterator that can visit all operands on a MachineInstr, or all operands on a bundle of MachineInstrs.
#include "llvm/CodeGen/MachineInstrBundle.h"
Classes
struct PhysRegInfo
Information about how a physical register Reg is used by a set of operands.
struct VirtRegInfo
VirtRegInfo - Information about a virtual register used by a set of operands.
Public Member Functions
bool isValid () const
isValid - Returns true until all the operands have been visited.
void operator++ ()
Preincrement. Move to the next operand.
unsigned getOperandNo () const
getOperandNo - Returns the number of the current operand relative to its instruction.
VirtRegInfo analyzeVirtReg (unsigned Reg, SmallVectorImpl< std::pair< MachineInstr *, unsigned > > *Ops=nullptr)
analyzeVirtReg - Analyze how the current instruction or bundle uses a virtual register.
PhysRegInfo analyzePhysReg (unsigned Reg, const TargetRegisterInfo *TRI)
analyzePhysReg - Analyze how the current instruction or bundle uses a physical register.
Protected Member Functions
MachineOperandIteratorBase (MachineInstr &MI, bool WholeBundle)
MachineOperandIteratorBase - Create an iterator that visits all operands on MI, or all operands on every instruction in the bundle containing MI.
MachineOperand & deref () const
Detailed Description
MachineOperandIteratorBase - Iterator that can visit all operands on a MachineInstr, or all operands on a bundle of MachineInstrs.
This class is not intended to be used directly, use one of the sub-classes instead.
Intended use:
for (MIBundleOperands MIO(MI); MIO.isValid(); ++MIO) { if (!MIO->isReg()) continue; ... }
Definition at line 93 of file MachineInstrBundle.h.
Constructor & Destructor Documentation
MachineOperandIteratorBase()
llvm::MachineOperandIteratorBase::MachineOperandIteratorBase (MachineInstr & MI, bool WholeBundle) inline explicit protected
MachineOperandIteratorBase - Create an iterator that visits all operands on MI, or all operands on every instruction in the bundle containing MI.
Parameters
MI The instruction to examine.
WholeBundle When true, visit all operands on the entire bundle.
Definition at line 116 of file MachineInstrBundle.h.
References llvm::getBundleStart(), and MI.
Member Function Documentation
analyzePhysReg()
MachineOperandIteratorBase::PhysRegInfo MachineOperandIteratorBase::analyzePhysReg (unsigned Reg, const TargetRegisterInfo * TRI)
analyzePhysReg - Analyze how the current instruction or bundle uses a physical register.
This function should not be called after operator++(), it expects a fresh iterator.
Parameters
Reg The physical register to analyze.
Returns
A filled-in PhysRegInfo struct.
Definition at line 314 of file MachineInstrBundle.cpp.
References assert(), llvm::MachineOperandIteratorBase::PhysRegInfo::Clobbered, llvm::MachineOperand::clobbersPhysReg(), llvm::MachineOperandIteratorBase::PhysRegInfo::DeadDef, llvm::MachineOperandIteratorBase::PhysRegInfo::Defined, deref(), llvm::MachineOperandIteratorBase::PhysRegInfo::FullyDefined, llvm::MachineOperandIteratorBase::PhysRegInfo::FullyRead, llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), isValid(), llvm::MachineOperandIteratorBase::PhysRegInfo::Killed, llvm::MachineOperandIteratorBase::PhysRegInfo::PartialDeadDef, llvm::MachineOperandIteratorBase::PhysRegInfo::Read, llvm::MachineOperand::readsReg(), and TRI.
Referenced by llvm::MachineBasicBlock::computeRegisterLiveness().
analyzeVirtReg()
MachineOperandIteratorBase::VirtRegInfo MachineOperandIteratorBase::analyzeVirtReg (unsigned Reg, SmallVectorImpl< std::pair< MachineInstr *, unsigned > > * Ops = nullptr)
analyzeVirtReg - Analyze how the current instruction or bundle uses a virtual register.
This function should not be called after operator++(), it expects a fresh iterator.
Parameters
Reg The virtual register to analyze.
Ops When set, this vector will receive an (MI, OpNum) entry for each operand referring to Reg.
Returns
A filled-in RegInfo struct.
Definition at line 285 of file MachineInstrBundle.cpp.
References deref(), getOperandNo(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), isValid(), llvm::MachineOperandIteratorBase::VirtRegInfo::Reads, llvm::MachineOperand::readsReg(), llvm::MachineOperandIteratorBase::VirtRegInfo::Tied, and llvm::MachineOperandIteratorBase::VirtRegInfo::Writes.
deref()
MachineOperand & llvm::MachineOperandIteratorBase::deref () const inline protected
Definition at line 130 of file MachineInstrBundle.h.
Referenced by analyzePhysReg(), analyzeVirtReg(), llvm::MIOperands::operator*(), llvm::ConstMIOperands::operator*(), llvm::MIBundleOperands::operator*(), llvm::ConstMIBundleOperands::operator*(), llvm::MIOperands::operator->(), llvm::ConstMIOperands::operator->(), llvm::MIBundleOperands::operator->(), and llvm::ConstMIBundleOperands::operator->().
getOperandNo()
unsigned llvm::MachineOperandIteratorBase::getOperandNo () const inline
getOperandNo - Returns the number of the current operand relative to its instruction.
Definition at line 146 of file MachineInstrBundle.h.
Referenced by analyzeVirtReg().
isValid()
bool llvm::MachineOperandIteratorBase::isValid () const inline
isValid - Returns true until all the operands have been visited.
Definition at line 134 of file MachineInstrBundle.h.
Referenced by analyzePhysReg(), analyzeVirtReg(), llvm::MachineInstr::getRegClassConstraintEffectForVReg(), operator++(), llvm::recomputeLivenessFlags(), and stripValuesNotDefiningMask().
operator++()
void llvm::MachineOperandIteratorBase::operator++ () inline
Preincrement. Move to the next operand.
Definition at line 137 of file MachineInstrBundle.h.
References assert(), and isValid().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineInstrBundle.h
lib/CodeGen/MachineInstrBundle.cpp