LLVM: llvm::TargetLoweringBase Class Reference
llvm::TargetLoweringBase Class Reference
This base class for TargetLowering contains the SelectionDAG-independent parts that can be used from the rest of CodeGen.
#include "llvm/CodeGen/TargetLowering.h"
Classes
struct AddrMode
This represents an addressing mode of: BaseGV + BaseOffs + BaseReg + Scale*ScaleReg If BaseGV is null, there is no BaseGV.
class ArgListEntry
struct IntrinsicInfo
class ValueTypeActionImpl
Public Types
enum LegalizeAction : uint8_t {
Legal , Promote , Expand , LibCall ,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector ,
TypePromoteFloat
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum class AtomicExpansionKind {
None , LLSC , LLOnly , CmpXChg ,
MaskedIntrinsic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum class MulExpansionKind { Always , OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum ReciprocalEstimate : int { Unspecified = -1 , Disabled = 0 , Enabled = 1 }
Reciprocal estimate status values used by the functions below.
using LegalizeKind = std::pair< LegalizeTypeAction, EVT >
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector< ArgListEntry >
Public Member Functions
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
const TargetMachine & getTargetMachine () const
virtual bool useSoftFloat () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
virtual MVT getFenceOperandTy (const DataLayout &DL) const
Return the type for operands of fence.
virtual MVT getScalarShiftAmountTy (const DataLayout &, EVT) const
EVT is not used in-tree, but is used by out-of-tree target.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL, bool LegalTypes=true) const
virtual MVT getVectorIdxTy (const DataLayout &DL) const
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
virtual bool isSelectSupported (SelectSupportKind) const
virtual bool reduceSelectOfFPConstantLoads (bool IsFPSetCC) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
virtual bool isFsqrtCheap (SDValue X, SelectionDAG &DAG) const
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual BranchProbability getPredictableBranchThreshold () const
If a branch or a select condition is skewed in one direction by more than this factor, it is very likely to be predicted correctly.
virtual bool isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AddrSpace) const
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
virtual bool mergeStoresAfterLegalization (EVT MemVT) const
Allow store merging for the specified type after legalization in addition to before legalization.
virtual bool canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG &DAG) const
Returns if it's reasonable to merge stores to MemVT size.
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
virtual bool isCtlzFast () const
Return true if ctlz instruction is fast.
virtual bool hasBitPreservingFPLogic (EVT VT) const
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool isMaskAndCmp0FoldingBeneficial (const Instruction &AndI) const
Return if the target supports combining a chain like:
virtual bool convertSetCCLogicToBitwiseLogic (EVT VT) const
Use bitwise logic to make pairs of compares more efficient.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNotCompare (SDValue Y) const
Return true if the target should transform: (X & Y) == Y —> (~X & Y) == 0 (X & Y) != Y —> (~X & Y) != 0.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool preferIncOfAddToSubOfNot (EVT VT) const
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual bool enableAggressiveFMAFusion (EVT VT) const
Return true if target always beneficiates from combining into FMA for a given value type.
virtual EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const
Return the ValueType of the result of SETCC operations.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
Some scheduler, e.g.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent=false) const
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *) const
Allows target to decide about the register class of the specific value that is live outside the defining block.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual bool shouldExpandShift (SelectionDAG &DAG, SDNode *N) const
Return true if SHIFT instructions should be expanded to SHIFT_PARTS instructions, and false if a library call is preferred (e.g for code-size reasons).
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, MachineFunction &, unsigned) const
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
virtual bool isFPImmLegal (const APFloat &, EVT, bool ForCodeSize=false) const
Returns true if the target can instruction select the specified FP immediate natively.
virtual bool isShuffleMaskLegal (ArrayRef< int >, EVT) const
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty, const DataLayout &DL) const
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
Return the number of registers that this ValueType will eventually require.
virtual MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
virtual unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain targets require unusual breakdowns of certain types.
virtual unsigned getABIAlignmentForCallingConv (Type *ArgTy, DataLayout DL) const
Certain targets have context senstive alignment requirements, where one type has the alignment requirement of another type.
virtual bool ShouldShrinkFPConstant (EVT) const
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
Return true if it is profitable to reduce a load to a smaller type.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, unsigned Align=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, unsigned Alignment=1, MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
virtual EVT getOptimalMemOpType (uint64_t, unsigned, unsigned, bool, bool, bool, const AttributeList &) const
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
virtual bool isJumpTableRelative () const
unsigned getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual unsigned getExceptionPointerRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
virtual unsigned getExceptionSelectorRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
virtual bool needsFixedCatchObjects () const
unsigned getJumpBufSize () const
Returns the target's jmp_buf size in bytes (if never set, the default is 200)
unsigned getJumpBufAlignment () const
Returns the target's jmp_buf alignment in bytes (if never set, the default is 0)
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilder<> &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual void insertSSPDeclarations (Module &M) const
Inserts necessary declarations for SSP (stack protection) purpose.
virtual Value * getSDagStackGuard (const Module &M) const
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual Value * getSafeStackPointerLocation (IRBuilder<> &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual StringRef getStackProbeSymbolName (MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, unsigned &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilder<> &Builder) const
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *RMW) const
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool convertSelectOfConstantsToMath (EVT VT) const
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
virtual bool decomposeMulByConstant (EVT VT, SDValue C) const
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
virtual bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
virtual bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AddrSpace, Instruction *I=nullptr) const
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
virtual int getScalingFactorCost (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS=0) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
virtual bool isLegalAddImmediate (int64_t) const
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool isTruncateFree (Type *FromTy, Type *ToTy) const
Return true if it's free to truncate a value of type FromTy to type ToTy.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isTruncateFree (EVT FromVT, EVT ToVT) const
virtual bool isProfitableToHoist (Instruction *I) const
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isZExtFree (Type *FromTy, Type *ToTy) const
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
virtual bool isZExtFree (EVT FromTy, EVT ToTy) const
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool hasPairedLoad (EVT, unsigned &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst * > Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool isZExtFree (SDValue Val, EVT VT2) const
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
virtual bool isFPExtFree (EVT DestVT, EVT SrcVT) const
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
virtual bool isFPExtFoldable (unsigned Opcode, EVT DestVT, EVT SrcVT) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFNegFree (EVT VT) const
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFAbsFree (EVT VT) const
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isNarrowingProfitable (EVT, EVT) const
Return true if it's profitable to narrow operations of type VT1 to VT2.
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool aggressivelyPreferBuildVectorSources (EVT VecVT) const
virtual bool shouldConsiderGEPOffsetSplit () const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
virtual void finalizeLowering (MachineFunction &MF) const
Execute target specific actions to finalize target lowering.
Helpers for TargetTransformInfo implementations
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< int, MVT > getTypeLegalizationCost (const DataLayout &DL, Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
Helpers for atomic expansion.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual bool shouldInsertFencesForAtomic (const Instruction *I) const
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Perform a store-conditional operation to Addr.
virtual Value * emitMaskedAtomicRMWIntrinsic (IRBuilder<> &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const
Perform a masked atomicrmw using a target-specific intrinsic.
virtual Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilder<> &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const
Perform a masked cmpxchg using a target-specific intrinsic.
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Inserts in the IR a target-specific intrinsic specifying a fence.
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, Instruction *Inst, AtomicOrdering Ord) const
Static Public Member Functions
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilder<> &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
Indicate whether this target prefers to use _setjmp to implement llvm.setjmp or the version without _.
void setUseUnderscoreLongJmp (bool Val)
Indicate whether this target prefers to use _longjmp to implement llvm.longjmp or the version without _.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (unsigned R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setTargetDAGCombine (ISD::NodeType NT)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
Set the target's required jmp_buf buffer alignment (in bytes); default is 0.
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
Set the target's preferred function alignment.
void setPrefLoopAlignment (unsigned Align)
Set the target's preferred loop alignment.
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
MachineBasicBlock * emitXRayCustomEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay custom event operands with target-dependent details.
MachineBasicBlock * emitXRayTypedEvent (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify the XRay typed event operands with target-dependent details.
Protected Attributes
ValueTypeActionImpl ValueTypeActions
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Maximum number of stores operations that may be substituted for the call to memset, used for functions with OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxStoresPerMemcpyOptSize
Maximum number of store operations that may be substituted for a call to memcpy, used for functions with OptSize attribute.
unsigned MaxLoadsPerMemcmp
unsigned MaxLoadsPerMemcmpOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Maximum number of store instructions that may be substituted for a call to memmove, used for functions with OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
Detailed Description
This base class for TargetLowering contains the SelectionDAG-independent parts that can be used from the rest of CodeGen.
Definition at line 107 of file TargetLowering.h.
Member Typedef Documentation
ArgListTy
using llvm::TargetLoweringBase::ArgListTy = std::vector<ArgListEntry>
Definition at line 204 of file TargetLowering.h.
LegalizeKind
using llvm::TargetLoweringBase::LegalizeKind = std::pair<LegalizeTypeAction, EVT>
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
Definition at line 136 of file TargetLowering.h.
Member Enumeration Documentation
AtomicExpansionKind
enum class llvm::TargetLoweringBase::AtomicExpansionKind strong
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
Exists because different targets have different levels of support for these atomic instructions, and also have different options w.r.t. what they should expand to.
Enumerator
None
LLSC
LLOnly
CmpXChg
MaskedIntrinsic
Definition at line 158 of file TargetLowering.h.
BooleanContent
enum llvm::TargetLoweringBase::BooleanContent
Enum that describes how the target represents true/false values.
Enumerator
UndefinedBooleanContent
ZeroOrOneBooleanContent
ZeroOrNegativeOneBooleanContent
Definition at line 139 of file TargetLowering.h.
LegalizeAction
enum llvm::TargetLoweringBase::LegalizeAction : uint8_t
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
Enumerator
Legal
Promote
Expand
LibCall
Custom
Definition at line 111 of file TargetLowering.h.
LegalizeTypeAction
enum llvm::TargetLoweringBase::LegalizeTypeAction : uint8_t
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
Enumerator
TypeLegal
TypePromoteInteger
TypeExpandInteger
TypeSoftenFloat
TypeExpandFloat
TypeScalarizeVector
TypeSplitVector
TypeWidenVector
TypePromoteFloat
Definition at line 121 of file TargetLowering.h.
MulExpansionKind
enum class llvm::TargetLoweringBase::MulExpansionKind strong
Enum that specifies when a multiplication should be expanded.
Enumerator
Always
OnlyLegalOrCustom
Definition at line 169 of file TargetLowering.h.
ReciprocalEstimate
enum llvm::TargetLoweringBase::ReciprocalEstimate : int
Reciprocal estimate status values used by the functions below.
Enumerator
Unspecified
Disabled
Enabled
Definition at line 345 of file TargetLowering.h.
SelectSupportKind
enum llvm::TargetLoweringBase::SelectSupportKind
Enum that describes what type of support for selects the target has.
Enumerator
ScalarValSelect
ScalarCondVectorVal
VectorMaskSelect
Definition at line 146 of file TargetLowering.h.
Constructor & Destructor Documentation
TargetLoweringBase() [1/2]
TargetLoweringBase::TargetLoweringBase (const TargetMachine & TM) explicit
NOTE: The TargetMachine owns TLOF.
Definition at line 560 of file TargetLoweringBase.cpp.
References EnableExtLdPromotion, GatherAllAliasesMaxDepth, llvm::TargetMachine::getTargetTriple(), llvm::Sched::ILP, initActions(), InitCmpLibcallCCs(), JumpIsExpensiveOverride, MaxGluedStoresPerMemcpy, MaxLoadsPerMemcmp, MaxLoadsPerMemcmpOptSize, MaxStoresPerMemcpy, MaxStoresPerMemcpyOptSize, MaxStoresPerMemmove, MaxStoresPerMemmoveOptSize, MaxStoresPerMemset, MaxStoresPerMemsetOptSize, PredictableSelectIsExpensive, and UndefinedBooleanContent.
TargetLoweringBase() [2/2]
llvm::TargetLoweringBase::TargetLoweringBase (const TargetLoweringBase &) delete
~TargetLoweringBase()
virtual llvm::TargetLoweringBase::~TargetLoweringBase () virtual default
Member Function Documentation
addBypassSlowDiv()
void llvm::TargetLoweringBase::addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth) inline protected
Tells the code generator which bitwidths to bypass.
Definition at line 1943 of file TargetLowering.h.
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
AddPromotedToType()
void llvm::TargetLoweringBase::AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT) inline protected
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
If that default is insufficient, this method can be used by the target to override the default.
Definition at line 2040 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), setOperationPromotedToType(), and llvm::SITargetLowering::SITargetLowering().
addRegisterClass()
void llvm::TargetLoweringBase::addRegisterClass (MVT VT, const TargetRegisterClass * RC) inline protected
Add the specified register class as an available regclass for the specified value type.
This indicates the selector can handle values of that class natively.
Definition at line 1950 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
aggressivelyPreferBuildVectorSources()
virtual bool llvm::TargetLoweringBase::aggressivelyPreferBuildVectorSources (EVT VecVT) const inline virtual
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 2549 of file TargetLowering.h.
alignLoopsWithOptSize()
virtual bool llvm::TargetLoweringBase::alignLoopsWithOptSize () const inline virtual
Should loops be aligned even when the function is marked OptSize (but not MinSize).
Reimplemented in llvm::ARMTargetLowering.
Definition at line 1559 of file TargetLowering.h.
allowsMemoryAccess() [1/2]
bool TargetLoweringBase::allowsMemoryAccess (LLVMContext & Context, const DataLayout & DL, EVT VT, const MachineMemOperand & MMO, bool * Fast = nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
If the access is allowed, the optional final parameter returns if the access is also fast (as defined by the target).
Definition at line 1514 of file TargetLoweringBase.cpp.
References allowsMemoryAccess(), Context, llvm::MachineMemOperand::getAddrSpace(), llvm::MachineMemOperand::getAlignment(), and llvm::MachineMemOperand::getFlags().
allowsMemoryAccess() [2/2]
bool TargetLoweringBase::allowsMemoryAccess (LLVMContext & Context, const DataLayout & DL, EVT VT, unsigned AddrSpace = 0, unsigned Alignment = 1, MachineMemOperand::Flags Flags = MachineMemOperand::MONone, bool * Fast = nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
If the access is allowed, the optional final parameter returns if the access is also fast (as defined by the target).
Definition at line 1491 of file TargetLoweringBase.cpp.
References allowsMisalignedMemoryAccesses(), Context, llvm::DataLayout::getABITypeAlignment(), and llvm::EVT::getTypeForEVT().
Referenced by allowsMemoryAccess(), combineConcatVectorOps(), combineLoad(), combineStore(), isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), and llvm::HexagonTargetLowering::LowerUnalignedLoad().
allowsMisalignedMemoryAccesses()
virtual bool llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace = 0, unsigned Align = 1, MachineMemOperand::Flags Flags = MachineMemOperand::MONone, bool * = nullptr) const inline virtual
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented in llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::Mips16TargetLowering, llvm::PPCTargetLowering, llvm::AArch64TargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, and llvm::MipsSETargetLowering.
Definition at line 1422 of file TargetLowering.h.
Referenced by allowsMemoryAccess(), llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::AMDGPUTargetLowering::performLoadCombine(), and llvm::AMDGPUTargetLowering::performStoreCombine().
allowTruncateForTailCall()
virtual bool llvm::TargetLoweringBase::allowTruncateForTailCall (Type * FromTy, Type * ToTy) const inline virtual
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call. Targets must return false when FromTy <= ToTy.
Reimplemented in llvm::SystemZTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, and llvm::X86TargetLowering.
Definition at line 2276 of file TargetLowering.h.
Referenced by getNoopInput().
areJTsAllowed()
virtual bool llvm::TargetLoweringBase::areJTsAllowed (const Function * Fn) const inline virtual
Return true if lowering to a jump table is allowed.
Reimplemented in llvm::X86TargetLowering.
Definition at line 971 of file TargetLowering.h.
References llvm::ISD::BR_JT, llvm::ISD::BRIND, llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), isOperationLegalOrCustom(), and llvm::MVT::Other.
Referenced by llvm::X86TargetLowering::areJTsAllowed(), llvm::SwitchCG::SwitchLowering::findJumpTables(), and llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters().
canCombineStoreAndExtract()
virtual bool llvm::TargetLoweringBase::canCombineStoreAndExtract (Type * VectorTy, Value * Idx, unsigned & Cost) const inline virtual
Return true if the target can combine store(extractelement VectorTy, Idx).
Cost[out] gives the cost of that transformation when this is true.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 592 of file TargetLowering.h.
canMergeStoresTo()
virtual bool llvm::TargetLoweringBase::canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG & DAG) const inline virtual
Returns if it's reasonable to merge stores to MemVT size.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::X86TargetLowering, llvm::R600TargetLowering, and llvm::SITargetLowering.
Definition at line 451 of file TargetLowering.h.
canOpTrap()
bool TargetLoweringBase::canOpTrap (unsigned Op, EVT VT) const virtual
Returns true if the operation can trap for the value type.
VT must be a legal type. By default, we optimistically assume most operations don't trap except for integer divide and remainder.
Definition at line 798 of file TargetLoweringBase.cpp.
References assert(), isTypeLegal(), llvm::ISD::SDIV, llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
computeRegisterProperties()
void TargetLoweringBase::computeRegisterProperties (const TargetRegisterInfo * TRI) protected
Once all of the register classes are added, this allows us to compute derived properties we expose.
computeRegisterProperties - Once all of the register classes are added, this allows us to compute derived properties we expose.
Definition at line 1154 of file TargetLoweringBase.cpp.
References assert(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, findRepresentativeClass(), llvm::MVT::FIRST_VECTOR_VALUETYPE, llvm::MVT::getPow2VectorType(), getPreferredVectorAction(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), getVectorTypeBreakdownMVT(), llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, isTypeLegal(), llvm::MVT::isVoid, llvm::MVT::LAST_INTEGER_VALUETYPE, llvm::MVT::LAST_INTEGER_VECTOR_VALUETYPE, llvm::MVT::LAST_VALUETYPE, llvm::MVT::LAST_VECTOR_VALUETYPE, LLVM_FALLTHROUGH, llvm_unreachable, llvm::MVT::MAX_ALLOWED_VALUETYPE, llvm::MVT::Other, llvm::MVT::ppcf128, llvm::TargetLoweringBase::ValueTypeActionImpl::setTypeAction(), TRI, TypeExpandFloat, TypeExpandInteger, TypePromoteFloat, TypePromoteInteger, TypeScalarizeVector, TypeSoftenFloat, TypeSplitVector, TypeWidenVector, and ValueTypeActions.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
convertSelectOfConstantsToMath()
virtual bool llvm::TargetLoweringBase::convertSelectOfConstantsToMath (EVT VT) const inline virtual
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
For example: select Cond, C1, C1-1 --> add (zext Cond), C1-1
Reimplemented in llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1842 of file TargetLowering.h.
convertSetCCLogicToBitwiseLogic()
virtual bool llvm::TargetLoweringBase::convertSetCCLogicToBitwiseLogic (EVT VT) const inline virtual
Use bitwise logic to make pairs of compares more efficient.
For example: and (seteq A, B), (seteq C, D) --> seteq (or (xor A, B), (xor C, D)), 0 This should be true when it takes more than one instruction to lower setcc (cmp+set on x86 scalar), when bitwise ops are faster than logic on condition bits (crand on PowerPC), and/or when reducing cmp+br is a win.
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, and llvm::X86TargetLowering.
Definition at line 504 of file TargetLowering.h.
decomposeMulByConstant()
virtual bool llvm::TargetLoweringBase::decomposeMulByConstant (EVT VT, SDValue C) const inline virtual
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
This may be true if the target does not directly support the multiplication operation for the specified type or the sequence of simpler ops is faster than the multiply.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1851 of file TargetLowering.h.
emitAtomicCmpXchgNoStoreLLBalance()
virtual void llvm::TargetLoweringBase::emitAtomicCmpXchgNoStoreLLBalance (IRBuilder<> & Builder) const inline virtual
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 1762 of file TargetLowering.h.
emitLeadingFence()
virtual Instruction * llvm::TargetLoweringBase::emitLeadingFence (IRBuilder<> & Builder, Instruction * Inst, AtomicOrdering Ord) const inline virtual
Inserts in the IR a target-specific intrinsic specifying a fence.
It is called by AtomicExpandPass before expanding an AtomicRMW/AtomicCmpXchg/AtomicStore/AtomicLoad if shouldInsertFencesForAtomic returns true.
Inst is the original atomic instruction, prior to other expansions that may be performed.
This function should either return a nullptr, or a pointer to an IR-level Instruction*. Even complex fence sequences can be represented by a single Instruction* through an intrinsic to be lowered later. Backends should override this method to produce target-specific intrinsic for their fences. FIXME: Please note that the default implementation here in terms of IR-level fences exists for historical/compatibility reasons and is unsound ! Fences cannot, in general, be used to restore sequential consistency. For example, consider the following example: atomic<int> x = y = 0; int r1, r2, r3, r4; Thread 0: x.store(1); Thread 1: y.store(1); Thread 2: r1 = x.load(); r2 = y.load(); Thread 3: r3 = y.load(); r4 = x.load(); r1 = r3 = 1 and r2 = r4 = 0 is impossible as long as the accesses are all seq_cst. But if they are lowered to monotonic accesses, no amount of IR-level fences can prevent it.
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::RISCVTargetLowering.
Definition at line 1738 of file TargetLowering.h.
References llvm::IRBuilder< T, Inserter >::CreateFence(), llvm::Instruction::hasAtomicStore(), and llvm::isReleaseOrStronger().
emitLoadLinked()
virtual Value * llvm::TargetLoweringBase::emitLoadLinked (IRBuilder<> & Builder, Value * Addr, AtomicOrdering Ord) const inline virtual
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
This may entail some non-trivial operations to truncate or reconstruct types that will be illegal in the backend. See ARMISelLowering for an example implementation.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 1673 of file TargetLowering.h.
References llvm_unreachable.
emitMaskedAtomicCmpXchgIntrinsic()
virtual Value * llvm::TargetLoweringBase::emitMaskedAtomicCmpXchgIntrinsic (IRBuilder<> & Builder, AtomicCmpXchgInst * CI, Value * AlignedAddr, Value * CmpVal, Value * NewVal, Value * Mask, AtomicOrdering Ord) const inline virtual
Perform a masked cmpxchg using a target-specific intrinsic.
This represents the core LL/SC loop which will be lowered at a late stage by the backend.
Definition at line 1699 of file TargetLowering.h.
References llvm_unreachable.
emitMaskedAtomicRMWIntrinsic()
virtual Value * llvm::TargetLoweringBase::emitMaskedAtomicRMWIntrinsic (IRBuilder<> & Builder, AtomicRMWInst * AI, Value * AlignedAddr, Value * Incr, Value * Mask, Value * ShiftAmt, AtomicOrdering Ord) const inline virtual
Perform a masked atomicrmw using a target-specific intrinsic.
This represents the core LL/SC loop which will be lowered at a late stage by the backend.
Definition at line 1688 of file TargetLowering.h.
References llvm_unreachable.
emitPatchPoint()
MachineBasicBlock * TargetLoweringBase::emitPatchPoint (MachineInstr & MI, MachineBasicBlock * MBB) const protected
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
Definition at line 1010 of file TargetLoweringBase.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addMemOperand(), assert(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::MachineFunction::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::DataLayout::getPointerSize(), llvm::MachineBasicBlock::insert(), llvm::MachineOperand::isFI(), llvm::MachineFrameInfo::isStatepointSpillSlotObjectIndex(), llvm::MachineInstr::mayLoad(), MI, and llvm::MachineMemOperand::MOLoad.
Referenced by llvm::SystemZTargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), and llvm::X86TargetLowering::EmitInstrWithCustomInserter().
emitStoreConditional()
virtual Value * llvm::TargetLoweringBase::emitStoreConditional (IRBuilder<> & Builder, Value * Val, Value * Addr, AtomicOrdering Ord) const inline virtual
Perform a store-conditional operation to Addr.
Return the status of the store. This should be 0 if the store succeeded, non-zero otherwise.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 1680 of file TargetLowering.h.
References llvm_unreachable.
emitTrailingFence()
virtual Instruction * llvm::TargetLoweringBase::emitTrailingFence (IRBuilder<> & Builder, Instruction * Inst, AtomicOrdering Ord) const inline virtual
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::RISCVTargetLowering.
Definition at line 1746 of file TargetLowering.h.
References llvm::IRBuilder< T, Inserter >::CreateFence(), and llvm::isAcquireOrStronger().
emitXRayCustomEvent()
MachineBasicBlock * TargetLoweringBase::emitXRayCustomEvent (MachineInstr & MI, MachineBasicBlock * MBB) const protected
Replace/modify the XRay custom event operands with target-dependent details.
Definition at line 1091 of file TargetLoweringBase.cpp.
References assert(), llvm::BuildMI(), llvm::MachineBasicBlock::insert(), and MI.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
emitXRayTypedEvent()
MachineBasicBlock * TargetLoweringBase::emitXRayTypedEvent (MachineInstr & MI, MachineBasicBlock * MBB) const protected
Replace/modify the XRay typed event operands with target-dependent details.
Definition at line 1106 of file TargetLoweringBase.cpp.
References assert(), llvm::BuildMI(), llvm::MachineBasicBlock::insert(), and MI.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
enableAggressiveFMAFusion()
virtual bool llvm::TargetLoweringBase::enableAggressiveFMAFusion (EVT VT) const inline virtual
Return true if target always beneficiates from combining into FMA for a given value type.
This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::NVPTXTargetLowering, and llvm::PPCTargetLowering.
Definition at line 606 of file TargetLowering.h.
enableExtLdPromotion()
bool llvm::TargetLoweringBase::enableExtLdPromotion () const inline
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
Definition at line 587 of file TargetLowering.h.
References EnableExtLdPromotion.
finalizeLowering()
void TargetLoweringBase::finalizeLowering (MachineFunction & MF) const virtual
Execute target specific actions to finalize target lowering.
This is used to set extra flags in MachineFrameInformation and freezing the set of reserved registers. The default implementation just freezes the set of reserved registers.
Reimplemented in llvm::SITargetLowering, and llvm::ARMTargetLowering.
Definition at line 1960 of file TargetLoweringBase.cpp.
References llvm::MachineRegisterInfo::freezeReservedRegs(), and llvm::MachineFunction::getRegInfo().
Referenced by llvm::SITargetLowering::finalizeLowering(), llvm::ARMTargetLowering::finalizeLowering(), INITIALIZE_PASS(), llvm::InstructionSelect::runOnMachineFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
findRepresentativeClass()
std::pair< const TargetRegisterClass *, uint8_t > TargetLoweringBase::findRepresentativeClass (const TargetRegisterInfo * TRI, MVT VT) const protected virtual
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
findRepresentativeClass - Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
Reimplemented in llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 1127 of file TargetLoweringBase.cpp.
References isLegalRC(), llvm::SuperRegClassIterator::isValid(), llvm::BitVector::set_bits(), llvm::BitVector::setBitsInMask(), llvm::MVT::SimpleTy, and TRI.
Referenced by computeRegisterProperties(), llvm::ARMTargetLowering::findRepresentativeClass(), and llvm::X86TargetLowering::findRepresentativeClass().
getABIAlignmentForCallingConv()
virtual unsigned llvm::TargetLoweringBase::getABIAlignmentForCallingConv (Type * ArgTy, DataLayout DL) const inline virtual
Certain targets have context senstive alignment requirements, where one type has the alignment requirement of another type.
Reimplemented in llvm::ARMTargetLowering, and llvm::MipsTargetLowering.
Definition at line 1319 of file TargetLowering.h.
References llvm::DataLayout::getABITypeAlignment().
Referenced by llvm::TargetLowering::LowerCallTo().
getAddrModeArguments()
virtual bool llvm::TargetLoweringBase::getAddrModeArguments (IntrinsicInst * , SmallVectorImpl< Value * > & , Type *&) const inline virtual
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
This allows as much computation as possible to be done in the address mode for that operand. This hook lets targets also pass back when this should be done on intrinsics which load/store.
Reimplemented in llvm::SITargetLowering.
Definition at line 2123 of file TargetLowering.h.
getBooleanContents() [1/2]
BooleanContent llvm::TargetLoweringBase::getBooleanContents (bool isVec, bool isFloat) const inline
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
"Boolean values" are special true/false values produced by nodes like SETCC and consumed (as the condition) by nodes like SELECT and BRCOND. Not to be confused with general values promoted from i1. Some cpus distinguish between vectors of boolean and scalars; the isVec parameter selects between the two kinds. For example on X86 a scalar boolean should be zero extended from i1, while the elements of a vector of booleans should be sign extended from i1.
Some cpus also treat floating point types the same way as they treat vectors instead of the way they treat scalars.
Definition at line 633 of file TargetLowering.h.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::TargetLowering::expandAddSubSat(), extractBooleanFlip(), flipBoolean(), getAsCarry(), llvm::SelectionDAG::getBoolConstant(), getBooleanContents(), llvm::SelectionDAG::getBoolExtOrTrunc(), llvm::TargetLowering::isConstFalseVal(), llvm::TargetLowering::isConstTrueVal(), llvm::TargetLowering::isExtendedTrueVal(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getBooleanContents() [2/2]
BooleanContent llvm::TargetLoweringBase::getBooleanContents (EVT Type) const inline
Definition at line 639 of file TargetLowering.h.
References getBooleanContents().
getBypassSlowDivWidths()
const DenseMap< unsigned int, unsigned int > & llvm::TargetLoweringBase::getBypassSlowDivWidths () const inline
Returns map of slow types for division or remainder with corresponding fast types.
Definition at line 380 of file TargetLowering.h.
getByValTypeAlignment()
unsigned TargetLoweringBase::getByValTypeAlignment (Type * Ty, const DataLayout & DL) const virtual
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
This is the actual alignment, not its logarithm.
Reimplemented in llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1486 of file TargetLoweringBase.cpp.
References llvm::DataLayout::getABITypeAlignment().
Referenced by llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), and llvm::CallLowering::setArgFlags().
getCmpLibcallCC()
ISD::CondCode llvm::TargetLoweringBase::getCmpLibcallCC (RTLIB::Libcall Call) const inline
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
Definition at line 2580 of file TargetLowering.h.
Referenced by llvm::TargetLowering::softenSetCCOperands().
getCmpLibcallReturnType()
MVT::SimpleValueType TargetLoweringBase::getCmpLibcallReturnType () const virtual
Return the ValueType for comparison libcalls.
Comparions libcalls include floating point comparion calls, and Ordered/Unordered check calls on floating point numbers.
Reimplemented in llvm::AVRTargetLowering.
Definition at line 1353 of file TargetLoweringBase.cpp.
References llvm::MVT::i32.
Referenced by llvm::TargetLowering::softenSetCCOperands().
getCondCodeAction()
LegalizeAction llvm::TargetLoweringBase::getCondCodeAction (ISD::CondCode CC, MVT VT) const inline
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 1142 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), Promote, and llvm::MVT::SimpleTy.
Referenced by isCondCodeLegal(), and isCondCodeLegalOrCustom().
getDefaultSafeStackPointerLocation()
Value * TargetLoweringBase::getDefaultSafeStackPointerLocation (IRBuilder<> & IRB, bool UseTLS) const protected
Definition at line 1636 of file TargetLoweringBase.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::IRBuilderBase::GetInsertBlock(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::GlobalValue::InitialExecTLSModel, llvm::GlobalValue::NotThreadLocal, and llvm::report_fatal_error().
Referenced by getSafeStackPointerLocation(), and llvm::X86TargetLowering::getSafeStackPointerLocation().
getDivRefinementSteps()
int TargetLoweringBase::getDivRefinementSteps (EVT VT, MachineFunction & MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
If the operation is not overridden by the function's attributes, "Unspecified" is returned and target defaults are expected to be used for instruction selection.
Definition at line 1955 of file TargetLoweringBase.cpp.
References getOpRefinementSteps(), and getRecipEstimateForFunc().
getExceptionPointerRegister()
virtual unsigned llvm::TargetLoweringBase::getExceptionPointerRegister (const Constant * PersonalityFn) const inline virtual
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 1508 of file TargetLowering.h.
Referenced by GetEHSpillList().
getExceptionSelectorRegister()
virtual unsigned llvm::TargetLoweringBase::getExceptionSelectorRegister (const Constant * PersonalityFn) const inline virtual
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 1516 of file TargetLowering.h.
Referenced by GetEHSpillList().
getExtendForAtomicOps()
virtual ISD::NodeType llvm::TargetLoweringBase::getExtendForAtomicOps () const inline virtual
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
Reimplemented in llvm::MipsTargetLowering, llvm::RISCVTargetLowering, and llvm::SystemZTargetLowering.
Definition at line 1813 of file TargetLowering.h.
References llvm::ISD::ZERO_EXTEND.
getExtendForContent()
static ISD::NodeType llvm::TargetLoweringBase::getExtendForContent (BooleanContent Content) inline static
Definition at line 209 of file TargetLowering.h.
References llvm::ISD::ANY_EXTEND, llvm_unreachable, llvm::ISD::SIGN_EXTEND, UndefinedBooleanContent, llvm::ISD::ZERO_EXTEND, ZeroOrNegativeOneBooleanContent, and ZeroOrOneBooleanContent.
Referenced by llvm::SelectionDAG::getBoolExtOrTrunc(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and llvm::TargetLowering::SimplifySetCC().
getFenceOperandTy()
virtual MVT llvm::TargetLoweringBase::getFenceOperandTy (const DataLayout & DL) const inline virtual
Return the type for operands of fence.
TODO: Let fence operands be of i32 type and remove this.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 261 of file TargetLowering.h.
References getPointerTy().
getFixedPointOperationAction()
LegalizeAction llvm::TargetLoweringBase::getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const inline
Some fixed point operations may be natively supported by the target but only for specific scales.
This method allows for checking if the width is supported by the target for a given operation that may depend on scale.
Definition at line 872 of file TargetLowering.h.
References Expand, getOperationAction(), isSupportedFixedPointOperation(), Legal, llvm_unreachable, llvm::ISD::SMULFIX, llvm::ISD::SMULFIXSAT, and llvm::ISD::UMULFIX.
getFrameIndexTy()
MVT llvm::TargetLoweringBase::getFrameIndexTy (const DataLayout & DL) const inline
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
Definition at line 255 of file TargetLowering.h.
References llvm::DataLayout::getAllocaAddrSpace(), and getPointerTy().
Referenced by addStackMapLiveVars(), llvm::SelectionDAG::CreateStackTemporary(), getAddressForMemoryInput(), llvm::SelectionDAGBuilder::getFrameIndexTy(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::TargetLowering::LowerCallTo().
getGatherAllAliasesMaxDepth()
unsigned llvm::TargetLoweringBase::getGatherAllAliasesMaxDepth () const inline
Definition at line 1355 of file TargetLowering.h.
References GatherAllAliasesMaxDepth.
getIndexedLoadAction()
LegalizeAction llvm::TargetLoweringBase::getIndexedLoadAction (unsigned IdxMode, MVT VT) const inline
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 1106 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by isIndexedLoadLegal().
getIndexedStoreAction()
LegalizeAction llvm::TargetLoweringBase::getIndexedStoreAction (unsigned IdxMode, MVT VT) const inline
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 1124 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by isIndexedStoreLegal().
getIRStackGuard()
Value * TargetLoweringBase::getIRStackGuard (IRBuilder<> & IRB) const virtual
If the target has a standard location for the stack protector guard, returns the address of that location.
Otherwise, returns nullptr. DEPRECATED: please override useLoadStackGuardNode and customize LOAD_STACK_GUARD, or customize @llvm.stackguard().
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 1728 of file TargetLoweringBase.cpp.
References llvm::IRBuilderBase::GetInsertBlock(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getParent(), and getTargetMachine().
Referenced by llvm::AArch64TargetLowering::getIRStackGuard(), llvm::X86TargetLowering::getIRStackGuard(), and getStackGuard().
getJumpBufAlignment()
unsigned llvm::TargetLoweringBase::getJumpBufAlignment () const inline
Returns the target's jmp_buf alignment in bytes (if never set, the default is 0)
Definition at line 1533 of file TargetLowering.h.
Referenced by llvm::BasicTTIImplBase< T >::getJumpBufAlignment().
getJumpBufSize()
unsigned llvm::TargetLoweringBase::getJumpBufSize () const inline
Returns the target's jmp_buf size in bytes (if never set, the default is 200)
Definition at line 1527 of file TargetLowering.h.
Referenced by llvm::BasicTTIImplBase< T >::getJumpBufSize().
getLibcallCallingConv()
CallingConv::ID llvm::TargetLoweringBase::getLibcallCallingConv (RTLIB::Libcall Call) const inline
Get the CallingConv that should be used for the specified libcall.
Definition at line 2590 of file TargetLowering.h.
Referenced by llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), and llvm::TargetLowering::makeLibCall().
getLibcallName()
const char * llvm::TargetLoweringBase::getLibcallName (RTLIB::Libcall Call) const inline
Get the libcall routine name for the specified libcall.
Definition at line 2568 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), isDivRemLibcallAvailable(), isSinCosLibcallAvailable(), LowerF128_FPEXTEND(), LowerF128_FPROUND(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerFSINCOS(), llvm::SparcTargetLowering::LowerOperation(), LowerSINT_TO_FP(), LowerUINT_TO_FP(), llvm::TargetLowering::makeLibCall(), optimizeCall(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::returnTypeIsEligibleForTailCall(), and llvm::X86TargetLowering::X86TargetLowering().
getLoadExtAction()
LegalizeAction llvm::TargetLoweringBase::getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const inline
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 1053 of file TargetLowering.h.
References assert(), Expand, llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::ISD::LAST_LOADEXT_TYPE, llvm::MVT::LAST_VALUETYPE, and llvm::MVT::SimpleTy.
Referenced by llvm::BasicTTIImplBase< T >::getMemoryOpCost(), isLoadExtLegal(), and isLoadExtLegalOrCustom().
getMaxAtomicSizeInBitsSupported()
unsigned llvm::TargetLoweringBase::getMaxAtomicSizeInBitsSupported () const inline
Returns the maximum atomic operation size (in bits) supported by the backend.
Atomic operations greater than this size (as well as ones that are not naturally aligned), will be expanded by AtomicExpandPass into an __atomic_* library call.
Definition at line 1646 of file TargetLowering.h.
Referenced by atomicSizeSupported().
getMaxExpandSizeMemcmp()
unsigned llvm::TargetLoweringBase::getMaxExpandSizeMemcmp (bool OptSize) const inline
Get maximum # of load operations permitted for memcmp.
This function returns the maximum number of load operations permitted to replace a call to memcmp. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 1399 of file TargetLowering.h.
References MaxLoadsPerMemcmp, and MaxLoadsPerMemcmpOptSize.
Referenced by llvm::AArch64TTIImpl::enableMemCmpExpansion(), llvm::PPCTTIImpl::enableMemCmpExpansion(), and llvm::X86TTIImpl::enableMemCmpExpansion().
getMaxGluedStoresPerMemcpy()
virtual unsigned llvm::TargetLoweringBase::getMaxGluedStoresPerMemcpy () const inline virtual
Get maximum # of store operations to be glued together.
This function returns the maximum number of store operations permitted to glue together during lowering of llvm.memcpy. The value is set by
Definition at line 1389 of file TargetLowering.h.
References MaxGluedStoresPerMemcpy.
Referenced by getMemcpyLoadsAndStores().
getMaximumJumpTableSize()
unsigned TargetLoweringBase::getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
Zero if no limit.
Definition at line 1768 of file TargetLoweringBase.cpp.
References MaximumJumpTableSize.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and isSuitableForJumpTable().
getMaxStoresPerMemcpy()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemcpy (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memcpy.
This function returns the maximum number of store operations permitted to replace a call to llvm.memcpy. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 1380 of file TargetLowering.h.
References MaxStoresPerMemcpy, and MaxStoresPerMemcpyOptSize.
Referenced by getMemcpyLoadsAndStores().
getMaxStoresPerMemmove()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemmove (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memmove.
This function returns the maximum number of store operations permitted to replace a call to llvm.memmove. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 1409 of file TargetLowering.h.
References MaxStoresPerMemmove, and MaxStoresPerMemmoveOptSize.
Referenced by llvm::ARMTTIImpl::getMemcpyCost(), and getMemmoveLoadsAndStores().
getMaxStoresPerMemset()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemset (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memset.
This function returns the maximum number of store operations permitted to replace a call to llvm.memset. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 1370 of file TargetLowering.h.
References MaxStoresPerMemset, and MaxStoresPerMemsetOptSize.
Referenced by getMemsetStores().
getMaxSupportedInterleaveFactor()
virtual unsigned llvm::TargetLoweringBase::getMaxSupportedInterleaveFactor () const inline virtual
Get the maximum supported factor for interleaved memory accesses.
Default to be the minimum interleave factor: 2.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2408 of file TargetLowering.h.
getMemValueType()
EVT llvm::TargetLoweringBase::getMemValueType (const DataLayout & DL, Type * Ty, bool AllowUnknown = false) const inline
Definition at line 1215 of file TargetLowering.h.
References llvm::Type::getContext(), llvm::EVT::getEVT(), getPointerMemTy(), getValueType(), and llvm::EVT::getVectorVT().
Referenced by llvm::ComputeValueVTs(), getAddressForMemoryInput(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getMinCmpXchgSizeInBits()
unsigned llvm::TargetLoweringBase::getMinCmpXchgSizeInBits () const inline
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
Any smaller operations are widened in AtomicExpandPass.
Note that unlike operations above the maximum size, atomic ops are still natively supported below the minimum; they just require a more complex expansion.
Definition at line 1657 of file TargetLowering.h.
getMinFunctionAlignment()
unsigned llvm::TargetLoweringBase::getMinFunctionAlignment () const inline
Return the minimum function alignment.
Definition at line 1543 of file TargetLowering.h.
getMinimumJumpTableDensity()
unsigned TargetLoweringBase::getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
Definition at line 1764 of file TargetLoweringBase.cpp.
References JumpTableDensity, and OptsizeJumpTableDensity.
Referenced by isSuitableForJumpTable().
getMinimumJumpTableEntries()
unsigned TargetLoweringBase::getMinimumJumpTableEntries () const virtual
Return lower limit for number of blocks in a jump table.
Definition at line 1756 of file TargetLoweringBase.cpp.
References MinimumJumpTableEntries.
Referenced by llvm::SwitchCG::SwitchLowering::findJumpTables().
getMinStackArgumentAlignment()
unsigned llvm::TargetLoweringBase::getMinStackArgumentAlignment () const inline
Return the minimum stack alignment of an argument.
Definition at line 1538 of file TargetLowering.h.
Referenced by llvm::SelectionDAG::expandVAArg().
getNumRegisters()
unsigned llvm::TargetLoweringBase::getNumRegisters (LLVMContext & Context, EVT VT) const inline
Return the number of registers that this ValueType will eventually require.
This is one for any types promoted to live in larger registers, but may be more than one for types (like i64) that are split into pieces. For types like i140, which are first promoted then expanded, it is the number of registers needed to hold all the bits of the original type. For an i140 on a 32 bit machine this means 5 registers.
Definition at line 1280 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), Context, getRegisterType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), getVectorTypeBreakdown(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm_unreachable, and llvm::MVT::SimpleTy.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::computeLegalValueVTs(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::FunctionLoweringInfo::CreateRegs(), getNumRegistersForCallingConv(), llvm::MipsTargetLowering::getNumRegistersForCallingConv(), GetRegistersForValue(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RegsForValue::RegsForValue(), llvm::FastISel::selectExtractValue(), and llvm::FunctionLoweringInfo::set().
getNumRegistersForCallingConv()
virtual unsigned llvm::TargetLoweringBase::getNumRegistersForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT) const inline virtual
Certain targets require unusual breakdowns of certain types.
For MIPS, this occurs when a vector type is used, as vector are passed through the integer register set.
Reimplemented in llvm::SITargetLowering, llvm::MipsTargetLowering, and llvm::X86TargetLowering.
Definition at line 1311 of file TargetLowering.h.
References Context, and getNumRegisters().
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::SITargetLowering::getNumRegistersForCallingConv(), llvm::X86TargetLowering::getNumRegistersForCallingConv(), llvm::GetReturnInfo(), llvm::TargetLowering::LowerCallTo(), llvm::AArch64CallLowering::lowerReturn(), and llvm::RegsForValue::RegsForValue().
getOperationAction()
LegalizeAction llvm::TargetLoweringBase::getOperationAction (unsigned Op, EVT VT) const inline
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 852 of file TargetLowering.h.
References llvm::array_lengthof(), Custom, Expand, llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), and llvm::MVT::SimpleTy.
Referenced by getFixedPointOperationAction(), getStrictFPOperationAction(), getTypeToPromoteTo(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), isLoadBitCastBeneficial(), isOperationCustom(), isOperationExpand(), isOperationLegal(), isOperationLegalOrCustom(), isOperationLegalOrCustomOrPromote(), isOperationLegalOrPromote(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
getOptimalMemOpType()
virtual EVT llvm::TargetLoweringBase::getOptimalMemOpType (uint64_t , unsigned , unsigned , bool , bool , bool , const AttributeList &) const inline virtual
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1459 of file TargetLowering.h.
References llvm::MVT::Other.
Referenced by llvm::TargetLowering::findOptimalMemOpLowering().
getPointerMemTy()
MVT llvm::TargetLoweringBase::getPointerMemTy (const DataLayout & DL, uint32_t AS = 0) const inline
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
FIXME: The default needs to be removed once all the code is updated.
Definition at line 249 of file TargetLowering.h.
References llvm::MVT::getIntegerVT(), and llvm::DataLayout::getPointerSizeInBits().
Referenced by getLoadStackGuard(), getMemValueType(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getPointerTy()
virtual MVT llvm::TargetLoweringBase::getPointerTy (const DataLayout & DL, uint32_t AS = 0) const inline virtual
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
FIXME: The default needs to be removed once all the code is updated.
Definition at line 242 of file TargetLowering.h.
References llvm::MVT::getIntegerVT(), and llvm::DataLayout::getPointerSizeInBits().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::X86TargetLowering::BuildFILD(), CheckType(), CheckValueType(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandMULO(), llvm::SelectionDAG::expandVAArg(), llvm::SelectionDAG::expandVACopy(), getAddressForMemoryInput(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), getCopyFromParts(), GetExponent(), getFenceOperandTy(), getFrameIndexTy(), llvm::SelectionDAG::getIntPtrConstant(), getLimitedPrecisionExp2(), getLoadStackGuard(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SwiftErrorValueTracking::getOrCreateVReg(), llvm::SwiftErrorValueTracking::getOrCreateVRegDefAt(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::NVPTXTargetLowering::getPrototype(), llvm::FastISel::getRegForGEPIndex(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getSetCCResultType(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::RISCVTargetLowering::getSetCCResultType(), getShiftAmountTy(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), getUniformBase(), getVaListSizeInBits(), llvm::AArch64TargetLowering::getVaListSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), getValueType(), getVectorIdxTy(), isBLACompatibleAddress(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCTPOP(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFPOWI(), LowerFSINCOS(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLoad(), LowerMemOpCallTo(), llvm::R600TargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformSTORECombine(), PrepareCall(), llvm::SwiftErrorValueTracking::propagateVRegs(), recoverFramePointer(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectGetElementPtr(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getPredictableBranchThreshold()
BranchProbability TargetLoweringBase::getPredictableBranchThreshold () const virtual
If a branch or a select condition is skewed in one direction by more than this factor, it is very likely to be predicted correctly.
Definition at line 1522 of file TargetLoweringBase.cpp.
References MinPercentageForPredictableBranch.
Referenced by isFormingBranchFromSelectProfitable().
getPreferredVectorAction()
virtual TargetLoweringBase::LegalizeTypeAction llvm::TargetLoweringBase::getPreferredVectorAction (MVT VT) const inline virtual
Return the preferred vector type legalization action.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 301 of file TargetLowering.h.
References llvm::MVT::getVectorNumElements(), llvm::MVT::isPow2VectorType(), TypePromoteInteger, TypeScalarizeVector, and TypeWidenVector.
Referenced by computeRegisterProperties(), llvm::AArch64TargetLowering::getPreferredVectorAction(), llvm::SITargetLowering::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), llvm::PPCTargetLowering::getPreferredVectorAction(), llvm::SystemZTargetLowering::getPreferredVectorAction(), and llvm::X86TargetLowering::getPreferredVectorAction().
getPrefFunctionAlignment()
unsigned llvm::TargetLoweringBase::getPrefFunctionAlignment () const inline
Return the preferred function alignment.
Definition at line 1548 of file TargetLowering.h.
getPrefLoopAlignment()
virtual unsigned llvm::TargetLoweringBase::getPrefLoopAlignment (MachineLoop * ML = nullptr) const inline virtual
Return the preferred loop alignment.
Reimplemented in llvm::SITargetLowering, and llvm::PPCTargetLowering.
Definition at line 1553 of file TargetLowering.h.
getRecipEstimateDivEnabled()
int TargetLoweringBase::getRecipEstimateDivEnabled (EVT VT, MachineFunction & MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
If the operation is not overridden by the function's attributes, "Unspecified" is returned and target defaults are expected to be used for instruction selection.
Definition at line 1945 of file TargetLoweringBase.cpp.
References getOpEnabled(), and getRecipEstimateForFunc().
getRecipEstimateSqrtEnabled()
int TargetLoweringBase::getRecipEstimateSqrtEnabled (EVT VT, MachineFunction & MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
If the operation is not overridden by the function's attributes, "Unspecified" is returned and target defaults are expected to be used for instruction selection.
Definition at line 1940 of file TargetLoweringBase.cpp.
References getOpEnabled(), and getRecipEstimateForFunc().
getRegClassFor()
virtual const TargetRegisterClass * llvm::TargetLoweringBase::getRegClassFor (MVT VT, bool isDivergent = false) const inline virtual
Return the register class that should be used for the specified value type.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 657 of file TargetLowering.h.
References assert(), and llvm::MVT::SimpleTy.
Referenced by llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::FunctionLoweringInfo::CreateReg(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::SwiftErrorValueTracking::getOrCreateVReg(), llvm::SwiftErrorValueTracking::getOrCreateVRegDefAt(), llvm::ARMTargetLowering::getRegClassFor(), llvm::GenericScheduler::initPolicy(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::SITargetLowering::PostISelFolding(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectPatchpoint(), and llvm::X86TargetLowering::X86TargetLowering().
getRegisterType() [1/2]
MVT llvm::TargetLoweringBase::getRegisterType (LLVMContext & Context, EVT VT) const inline
Return the type of registers that this ValueType will eventually require.
Definition at line 1252 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), Context, getRegisterType(), llvm::EVT::getSimpleVT(), getTypeToTransformTo(), getVectorTypeBreakdown(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm_unreachable, and llvm::MVT::SimpleTy.
getRegisterType() [2/2]
MVT llvm::TargetLoweringBase::getRegisterType (MVT VT) const inline
Return the type of registers that this ValueType will eventually require.
Definition at line 1246 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), and llvm::MVT::SimpleTy.
Referenced by llvm::computeLegalValueVTs(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getNumRegisters(), getRegisterType(), getRegisterTypeForCallingConv(), llvm::GetReturnInfo(), llvm::TargetLowering::getTypeForExtReturn(), llvm::MipsTargetLowering::getTypeForExtReturn(), getVectorTypeBreakdown(), getVectorTypeBreakdownMVT(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::RegsForValue::RegsForValue(), and shouldTransformMulToShiftsAddsSubs().
getRegisterTypeForCallingConv()
virtual MVT llvm::TargetLoweringBase::getRegisterTypeForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT) const inline virtual
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
For MIPS all vector types must be passed through the integer register set.
Reimplemented in llvm::SITargetLowering, llvm::MipsTargetLowering, and llvm::X86TargetLowering.
Definition at line 1303 of file TargetLowering.h.
References Context, and getRegisterType().
Referenced by llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::RegsForValue::getCopyFromRegs(), llvm::RegsForValue::getCopyToRegs(), llvm::SITargetLowering::getRegisterTypeForCallingConv(), llvm::X86TargetLowering::getRegisterTypeForCallingConv(), llvm::GetReturnInfo(), llvm::CallLowering::handleAssignments(), llvm::TargetLowering::LowerCallTo(), llvm::AArch64CallLowering::lowerReturn(), and llvm::RegsForValue::RegsForValue().
getRepRegClassCostFor()
virtual uint8_t llvm::TargetLoweringBase::getRepRegClassCostFor (MVT VT) const inline virtual
Return the cost of the 'representative' register class for the specified value type.
Definition at line 686 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by GetCostForDef().
getRepRegClassFor()
virtual const TargetRegisterClass * llvm::TargetLoweringBase::getRepRegClassFor (MVT VT) const inline virtual
Return the 'representative' register class for the specified value type.
The 'representative' register class is the largest legal super-reg register class for the register class of the value type. For example, on i386 the rep register class for i8, i16, and i32 are GR32; while the rep register class is GR64 on x86_64.
Reimplemented in llvm::MipsSETargetLowering.
Definition at line 679 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by GetCostForDef(), and llvm::MipsSETargetLowering::getRepRegClassFor().
getSafeStackPointerLocation()
Value * TargetLoweringBase::getSafeStackPointerLocation (IRBuilder<> & IRB) const virtual
Returns the target-specific address of the unsafe stack pointer.
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 1668 of file TargetLoweringBase.cpp.
References llvm::IRBuilder< T, Inserter >::CreateCall(), getDefaultSafeStackPointerLocation(), llvm::IRBuilderBase::GetInsertBlock(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::Type::getPointerTo(), llvm::TargetMachine::getTargetTriple(), and llvm::Triple::isAndroid().
Referenced by llvm::AArch64TargetLowering::getSafeStackPointerLocation(), and llvm::X86TargetLowering::getSafeStackPointerLocation().
getScalarShiftAmountTy()
MVT TargetLoweringBase::getScalarShiftAmountTy (const DataLayout & DL, EVT) const virtual
EVT is not used in-tree, but is used by out-of-tree target.
A documentation for this function would be nice...
Reimplemented in llvm::AVRTargetLowering, llvm::X86TargetLowering, llvm::SITargetLowering, llvm::BPFTargetLowering, llvm::MipsTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::AArch64TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 784 of file TargetLoweringBase.cpp.
References llvm::MVT::getIntegerVT(), and llvm::DataLayout::getPointerSizeInBits().
Referenced by getShiftAmountTy().
getScalingFactorCost()
virtual int llvm::TargetLoweringBase::getScalingFactorCost (const DataLayout & DL, const AddrMode & AM, Type * Ty, unsigned AS = 0) const inline virtual
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
If the AM is supported, the return value must be >= 0. If the AM is not supported, it returns a negative value. TODO: Handle pre/postinc as well. TODO: Remove default argument
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2165 of file TargetLowering.h.
References isLegalAddressingMode().
Referenced by llvm::BasicTTIImplBase< T >::getScalingFactorCost().
getSchedulingPreference() [1/2]
Sched::Preference llvm::TargetLoweringBase::getSchedulingPreference () const inline
Return target scheduling preference.
Definition at line 644 of file TargetLowering.h.
Referenced by llvm::createDefaultScheduler(), llvm::PPCTargetLowering::getSchedulingPreference(), and llvm::ScheduleDAGSDNodes::newSUnit().
getSchedulingPreference() [2/2]
virtual Sched::Preference llvm::TargetLoweringBase::getSchedulingPreference (SDNode *) const inline virtual
Some scheduler, e.g.
hybrid, can switch to different scheduling heuristics for different nodes. This function returns the preference (or none) for the given node.
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 651 of file TargetLowering.h.
References llvm::Sched::None.
getSDagStackGuard()
Value * TargetLoweringBase::getSDagStackGuard (const Module & M) const virtual
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
Should be used only when getIRStackGuard returns nullptr.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 1748 of file TargetLoweringBase.cpp.
Referenced by getLoadStackGuard(), llvm::AArch64TargetLowering::getSDagStackGuard(), llvm::ARMTargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSDagStackGuard(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getSetCCResultType()
EVT TargetLoweringBase::getSetCCResultType (const DataLayout & DL, LLVMContext & Context, EVT VT) const virtual
Return the ValueType of the result of SETCC operations.
Reimplemented in llvm::HexagonTargetLowering, llvm::R600TargetLowering, llvm::SystemZTargetLowering, llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::ARMTargetLowering, llvm::AVRTargetLowering, llvm::BPFTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SparcTargetLowering, llvm::X86TargetLowering, and llvm::NVPTXTargetLowering.
Definition at line 1347 of file TargetLoweringBase.cpp.
References assert(), getPointerTy(), llvm::EVT::isVector(), and llvm::MVT::SimpleTy.
Referenced by combineFMinNumFMaxNum(), combineHorizontalPredicateResult(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), foldXorTruncShiftIntoCmp(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::TargetLowering::SimplifySetCC(), llvm::TargetLowering::softenSetCCOperands(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getShiftAmountTy()
EVT TargetLoweringBase::getShiftAmountTy (EVT LHSTy, const DataLayout & DL, bool LegalTypes = true) const
Definition at line 789 of file TargetLoweringBase.cpp.
References assert(), getPointerTy(), getScalarShiftAmountTy(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::SelectionDAG::getShiftAmountOperand(), getShiftAmountTyForConstant(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getSimpleValueType()
MVT llvm::TargetLoweringBase::getSimpleValueType (const DataLayout & DL, Type * Ty, bool AllowUnknown = false) const inline
Return the MVT corresponding to this LLVM type. See getValueType.
Definition at line 1235 of file TargetLowering.h.
References llvm::EVT::getSimpleVT(), and getValueType().
Referenced by llvm::TargetLowering::ParseConstraints().
getSqrtRefinementSteps()
int TargetLoweringBase::getSqrtRefinementSteps (EVT VT, MachineFunction & MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
If the operation is not overridden by the function's attributes, "Unspecified" is returned and target defaults are expected to be used for instruction selection.
Definition at line 1950 of file TargetLoweringBase.cpp.
References getOpRefinementSteps(), and getRecipEstimateForFunc().
getSSPStackGuardCheck()
Function * TargetLoweringBase::getSSPStackGuardCheck (const Module & M) const virtual
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
Otherwise, returns nullptr. Must be previously inserted by insertSSPDeclarations. Should be used only when getIRStackGuard returns nullptr.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 1752 of file TargetLoweringBase.cpp.
Referenced by llvm::AArch64TargetLowering::getSSPStackGuardCheck(), llvm::ARMTargetLowering::getSSPStackGuardCheck(), llvm::X86TargetLowering::getSSPStackGuardCheck(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getStackPointerRegisterToSaveRestore()
unsigned llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore () const inline
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
Definition at line 1501 of file TargetLowering.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::calculateDbgEntityHistory(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), and llvm::FunctionLoweringInfo::set().
getStackProbeSymbolName()
virtual StringRef llvm::TargetLoweringBase::getStackProbeSymbolName (MachineFunction & MF) const inline virtual
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1600 of file TargetLowering.h.
getStrictFPOperationAction()
LegalizeAction llvm::TargetLoweringBase::getStrictFPOperationAction (unsigned Op, EVT VT) const inline
Definition at line 894 of file TargetLowering.h.
References Expand, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getOperationAction(), Legal, llvm_unreachable, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FCOS, llvm::ISD::STRICT_FDIV, llvm::ISD::STRICT_FEXP, llvm::ISD::STRICT_FEXP2, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FLOG, llvm::ISD::STRICT_FLOG10, llvm::ISD::STRICT_FLOG2, llvm::ISD::STRICT_FMA, llvm::ISD::STRICT_FMAXNUM, llvm::ISD::STRICT_FMINNUM, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FPOW, llvm::ISD::STRICT_FPOWI, llvm::ISD::STRICT_FREM, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FROUND, llvm::ISD::STRICT_FSIN, llvm::ISD::STRICT_FSQRT, llvm::ISD::STRICT_FSUB, and llvm::ISD::STRICT_FTRUNC.
getTargetMachine()
const TargetMachine & llvm::TargetLoweringBase::getTargetMachine () const inline
Definition at line 235 of file TargetLowering.h.
Referenced by llvm::X86TTIImpl::areFunctionArgsABICompatible(), llvm::AArch64TTIImpl::areInlineCompatible(), llvm::GCNTTIImpl::areInlineCompatible(), llvm::ARMTTIImpl::areInlineCompatible(), llvm::X86TTIImpl::areInlineCompatible(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::finalizeLowering(), llvm::NVPTXTargetLowering::getDivF32Level(), llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), getIRStackGuard(), llvm::TargetLowering::getJumpTableEncoding(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::MipsTargetLowering::isJumpTableRelative(), llvm::X86TargetLowering::isLegalAddressingMode(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::SystemZSubtarget::isPC32DBLSymbol(), llvm::TargetLowering::isPositionIndependent(), llvm::AArch64TargetLowering::isProfitableToHoist(), IsSmallObject(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::SparcTargetLowering::makeAddress(), llvm::AMDGPUTargetLowering::mayIgnoreSignedZero(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::InstructionSelect::runOnMachineFunction(), llvm::AArch64TargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::ARMTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::HexagonTargetLowering::shouldReduceLoadWidth(), llvm::NVPTXTargetLowering::usePrecSqrtF32(), and llvm::AArch64Subtarget::useSmallAddressing().
getTgtMemIntrinsic()
virtual bool llvm::TargetLoweringBase::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , MachineFunction & , unsigned) const inline virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented in llvm::SITargetLowering, llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, and llvm::X86TargetLowering.
Definition at line 813 of file TargetLowering.h.
getTruncStoreAction()
LegalizeAction llvm::TargetLoweringBase::getTruncStoreAction (EVT ValVT, EVT MemVT) const inline
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 1079 of file TargetLowering.h.
References assert(), Expand, llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::MVT::LAST_VALUETYPE, and llvm::MVT::SimpleTy.
Referenced by llvm::BasicTTIImplBase< T >::getMemoryOpCost(), isTruncStoreLegal(), and isTruncStoreLegalOrCustom().
getTypeAction() [1/2]
LegalizeTypeAction llvm::TargetLoweringBase::getTypeAction (LLVMContext & Context, EVT VT) const inline
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
'Custom' is not an option.
Definition at line 734 of file TargetLowering.h.
References Context.
Referenced by FindMemType(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::SelectionDAG::getConstant(), llvm::X86TargetLowering::getSetCCResultType(), getTypeToExpandTo(), getVectorTypeBreakdown(), LowerStore(), OptimizeNoopCopyExpression(), llvm::X86TargetLowering::ReplaceNodeResults(), and shouldNormalizeToSelectSequence().
getTypeAction() [2/2]
LegalizeTypeAction llvm::TargetLoweringBase::getTypeAction (MVT VT) const inline
Definition at line 737 of file TargetLowering.h.
References llvm::TargetLoweringBase::ValueTypeActionImpl::getTypeAction(), and ValueTypeActions.
getTypeLegalizationCost()
std::pair< int, MVT > TargetLoweringBase::getTypeLegalizationCost (const DataLayout & DL, Type * Ty) const
Estimate the cost of type-legalization and the legalized type.
Definition at line 1609 of file TargetLoweringBase.cpp.
References C, llvm::Type::getContext(), llvm::EVT::getSimpleVT(), getValueType(), TypeExpandInteger, TypeLegal, and TypeSplitVector.
Referenced by llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::NVPTXTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::PPCTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::HexagonTTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::GCNTTIImpl::getMinMaxReductionCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< T >::getNumberOfParts(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::PPCTTIImpl::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::PPCTTIImpl::getUserCost(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), llvm::AArch64TTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), and llvm::PPCTTIImpl::vectorCostAdjustment().
getTypeToExpandTo()
EVT llvm::TargetLoweringBase::getTypeToExpandTo (LLVMContext & Context, EVT VT) const inline
For types supported by the target, this is an identity function.
For types that must be expanded (i.e. integer types that are larger than the largest integer register or illegal floating point types), this returns the largest legal type it will be expanded to.
Definition at line 755 of file TargetLowering.h.
References assert(), Context, getTypeAction(), getTypeToTransformTo(), llvm::EVT::isVector(), llvm_unreachable, TypeExpandInteger, and TypeLegal.
getTypeToPromoteTo()
MVT llvm::TargetLoweringBase::getTypeToPromoteTo (unsigned Op, MVT VT) const inline
If the action for this operation is to promote, this method returns the ValueType to promote to.
Definition at line 1168 of file TargetLowering.h.
References assert(), getOperationAction(), llvm::MVT::isFloatingPoint(), llvm::MVT::isInteger(), isTypeLegal(), llvm::MVT::isVoid, Promote, and llvm::MVT::SimpleTy.
Referenced by isLoadBitCastBeneficial().
getTypeToTransformTo()
EVT llvm::TargetLoweringBase::getTypeToTransformTo (LLVMContext & Context, EVT VT) const inline
For types supported by the target, this is an identity function.
For types that must be promoted to larger types, this returns the larger type to promote to. For integer types that are larger than the largest integer register, this contains one step in the expansion to get to the smaller register. For illegal floating point types, this returns the integer type to transform to.
Definition at line 747 of file TargetLowering.h.
References Context.
Referenced by combineMinNumMaxNum(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), llvm::SelectionDAG::getConstant(), getMemcpyLoadsAndStores(), llvm::FastISel::getRegForValue(), getRegisterType(), llvm::X86TargetLowering::getSetCCResultType(), llvm::SelectionDAG::GetSplitDestVTs(), getTypeToExpandTo(), getVectorTypeBreakdown(), OptimizeNoopCopyExpression(), llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::FastISel::selectBinaryOp().
getVaListSizeInBits()
virtual unsigned llvm::TargetLoweringBase::getVaListSizeInBits (const DataLayout & DL) const inline virtual
Returns the size of the platform's va_list object.
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 1360 of file TargetLowering.h.
References getPointerTy(), and llvm::MVT::getSizeInBits().
getValueType()
EVT llvm::TargetLoweringBase::getValueType (const DataLayout & DL, Type * Ty, bool AllowUnknown = false) const inline
Return the EVT corresponding to this LLVM type.
This is fixed by the LLVM operations except for the pointer size. If AllowUnknown is true, this will return MVT::Other for types with no EVT counterpart (e.g. structs), otherwise it will assert.
Definition at line 1195 of file TargetLowering.h.
References llvm::Type::getContext(), llvm::EVT::getEVT(), getPointerTy(), and llvm::EVT::getVectorVT().
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::ComputeValueVTs(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::BasicTTIImplBase< T >::getFPOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), getMemValueType(), llvm::GCNTTIImpl::getMinMaxReductionCost(), llvm::NVPTXTargetLowering::getPrototype(), llvm::FastISel::getRegForValue(), getSimpleValueType(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), getTypeLegalizationCost(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::SystemZTTIImpl::hasDivRemOp(), llvm::X86TTIImpl::hasDivRemOp(), llvm::BasicTTIImplBase< T >::haveFastSqrt(), isExtLoad(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::BasicTTIImplBase< T >::isIndexedLoadLegal(), llvm::BasicTTIImplBase< T >::isIndexedStoreLegal(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedInstructionLegal(), isSupportedType(), llvm::BasicTTIImplBase< T >::isTypeLegal(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), makeBitReverse(), OptimizeExtractBits(), OptimizeNoopCopyExpression(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectFNeg(), llvm::FastISel::selectOperator(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and SinkShiftAndTruncate().
getValueTypeActions()
const ValueTypeActionImpl & llvm::TargetLoweringBase::getValueTypeActions () const inline
Definition at line 726 of file TargetLowering.h.
References ValueTypeActions.
getVectorIdxTy()
virtual MVT llvm::TargetLoweringBase::getVectorIdxTy (const DataLayout & DL) const inline virtual
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::SystemZTargetLowering.
Definition at line 275 of file TargetLowering.h.
References getPointerTy().
Referenced by BuildVectorFromScalar(), CollectOpsToWiden(), llvm::SelectionDAG::ExtractVectorElements(), getCopyFromPartsVector(), getCopyToPartsVector(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerReturn_32(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorStore(), llvm::SelectionDAG::SplitVector(), llvm::SelectionDAG::UnrollVectorOp(), and llvm::SelectionDAG::WidenVector().
getVectorTypeBreakdown()
unsigned TargetLoweringBase::getVectorTypeBreakdown (LLVMContext & Context, EVT VT, EVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT) const
Vector types are broken down into some number of legal first class types.
getVectorTypeBreakdown - Vector types are broken down into some number of legal first class types.
For example, EVT::v8f32 maps to 2 EVT::v4f32 with Altivec or SSE1, or 8 promoted EVT::f64 values with the X86 FP stack. Similarly, EVT::v2i64 turns into 4 EVT::i32 values with both PPC and X86.
This method returns the number of registers needed, and the VT for each register. It also returns the VT and quantity of the intermediate values before they are promoted/expanded.
For example, MVT::v8f32 maps to 2 MVT::v4f32 with Altivec or SSE1, or 8 promoted MVT::f64 values with the X86 FP stack. Similarly, MVT::v2i64 turns into 4 MVT::i32 values with both PPC and X86.
This method returns the number of registers needed, and the VT for each register. It also returns the VT and quantity of the intermediate values before they are promoted/expanded.
Definition at line 1365 of file TargetLoweringBase.cpp.
References Context, getRegisterType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), getTypeAction(), getTypeToTransformTo(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::isPowerOf2_32(), isTypeLegal(), llvm::NextPowerOf2(), TypePromoteInteger, and TypeWidenVector.
Referenced by getCopyFromPartsVector(), getCopyToPartsVector(), getNumRegisters(), getRegisterType(), and getVectorTypeBreakdownForCallingConv().
getVectorTypeBreakdownForCallingConv()
virtual unsigned llvm::TargetLoweringBase::getVectorTypeBreakdownForCallingConv (LLVMContext & Context, CallingConv::ID CC, EVT VT, EVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT) const inline virtual
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
This occurs even if the vector type is legal.
Reimplemented in llvm::SITargetLowering, and llvm::MipsTargetLowering.
Definition at line 786 of file TargetLowering.h.
References Context, and getVectorTypeBreakdown().
Referenced by getCopyFromPartsVector(), getCopyToPartsVector(), and llvm::SITargetLowering::getVectorTypeBreakdownForCallingConv().
hasAndNot()
virtual bool llvm::TargetLoweringBase::hasAndNot (SDValue X) const inline virtual
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 536 of file TargetLowering.h.
References hasAndNotCompare(), and X.
hasAndNotCompare()
virtual bool llvm::TargetLoweringBase::hasAndNotCompare (SDValue Y) const inline virtual
Return true if the target should transform: (X & Y) == Y —> (~X & Y) == 0 (X & Y) != Y —> (~X & Y) != 0.
This may be profitable if the target has a bitwise and-not operation that sets comparison flags. A target may want to limit the transformation based on the type of Y or if Y is a constant.
Note that the transform will not occur if Y is known to be a power-of-2 because a mask and compare of a single bit can be handled by inverting the predicate, for example: (X & 8) == 8 —> (X & 8) != 0
Reimplemented in llvm::AArch64TargetLowering, llvm::X86TargetLowering, and llvm::PPCTargetLowering.
Definition at line 529 of file TargetLowering.h.
Referenced by hasAndNot().
hasBigEndianPartOrdering()
bool llvm::TargetLoweringBase::hasBigEndianPartOrdering (EVT VT, const DataLayout & DL) const inline
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
Definition at line 1344 of file TargetLowering.h.
References llvm::DataLayout::isBigEndian(), and llvm::MVT::ppcf128.
Referenced by getCopyFromParts().
hasBitPreservingFPLogic()
virtual bool llvm::TargetLoweringBase::hasBitPreservingFPLogic (EVT VT) const inline virtual
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
This should be set to true if the target has IEEE-754-compliant fabs/fneg operations for the input type.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::RISCVTargetLowering, and llvm::X86TargetLowering.
Definition at line 475 of file TargetLowering.h.
Referenced by foldBitcastedFPLogic().
hasExtractBitsInsn()
bool llvm::TargetLoweringBase::hasExtractBitsInsn () const inline
Return true if the target has BitExtract instructions.
Definition at line 297 of file TargetLowering.h.
hasFastEqualityCompare()
virtual MVT llvm::TargetLoweringBase::hasFastEqualityCompare (unsigned NumBits) const inline virtual
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
Assume that any legal integer type can be compared efficiently. Targets may override this to allow illegal wide types to return a vector type if there is support to compare that type.
Reimplemented in llvm::X86TargetLowering.
Definition at line 512 of file TargetLowering.h.
References llvm::MVT::getIntegerVT(), llvm::MVT::INVALID_SIMPLE_VALUE_TYPE, and isTypeLegal().
hasMultipleConditionRegisters()
bool llvm::TargetLoweringBase::hasMultipleConditionRegisters () const inline
Return true if multiple condition registers are available.
Definition at line 292 of file TargetLowering.h.
Referenced by shouldNormalizeToSelectSequence(), and sinkCmpExpression().
hasPairedLoad()
virtual bool llvm::TargetLoweringBase::hasPairedLoad (EVT , unsigned &) const inline virtual
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
RequiredAlignment gives the minimal alignment constraints that must be met to be able to select this paired load.
This information is not used to generate actual paired loads, but it is used to generate a sequence of loads that is easier to combine into a paired load. For instance, something like this: a = load i64* addr b = trunc i64 a to i32 c = lshr i64 a, 32 d = trunc i64 c to i32 will be optimized into: b = load i32* addr1 d = load i32* addr2 Where addr1 = addr2 +/- sizeof(i32).
In other words, unless the target performs a post-isel load combining, this information should not be provided because it will generate more loads.
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 2398 of file TargetLowering.h.
hasStandaloneRem()
virtual bool llvm::TargetLoweringBase::hasStandaloneRem (EVT VT) const inline virtual
Return true if the target can handle a standalone remainder operation.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 334 of file TargetLowering.h.
hasTargetDAGCombine()
bool llvm::TargetLoweringBase::hasTargetDAGCombine (ISD::NodeType NT) const inline
If true, the target has custom DAG combine transformations that it can perform for the specified node.
Definition at line 1350 of file TargetLowering.h.
References llvm::array_lengthof(), and assert().
hasVectorBlend()
virtual bool llvm::TargetLoweringBase::hasVectorBlend () const inline virtual
Return true if the target has a vector blend instruction.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2404 of file TargetLowering.h.
Referenced by llvm::SelectionDAG::getVectorShuffle().
initActions()
void TargetLoweringBase::initActions () protected
Initialize all of the actions to default values.
Definition at line 601 of file TargetLoweringBase.cpp.
References llvm::ISD::ABS, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, AddPromotedToType(), llvm::MVT::all_valuetypes(), llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITREVERSE, llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantFP, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DEBUGTRAP, Expand, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FCBRT, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FGETSIGN, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FNEARBYINT, llvm::MVT::fp_valuetypes(), llvm::ISD::FPOWI, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::FTRUNC, llvm::ISD::GET_DYNAMIC_AREA_OFFSET, llvm::MVT::getIntegerVT(), llvm::MVT::i64, llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, llvm::ISD::LLRINT, llvm::ISD::LLROUND, llvm::ISD::LRINT, llvm::ISD::LROUND, llvm::MVT::Other, llvm::ISD::PRE_INC, llvm::ISD::PREFETCH, Promote, llvm::ISD::READCYCLECOUNTER, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SETCCCARRY, setIndexedLoadAction(), setIndexedStoreAction(), setOperationAction(), llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULFIX, llvm::ISD::SMULFIXSAT, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::ISD::SSUBSAT, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FCOS, llvm::ISD::STRICT_FDIV, llvm::ISD::STRICT_FEXP, llvm::ISD::STRICT_FEXP2, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FLOG, llvm::ISD::STRICT_FLOG10, llvm::ISD::STRICT_FLOG2, llvm::ISD::STRICT_FMA, llvm::ISD::STRICT_FMAXNUM, llvm::ISD::STRICT_FMINNUM, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FPOW, llvm::ISD::STRICT_FPOWI, llvm::ISD::STRICT_FREM, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FROUND, llvm::ISD::STRICT_FSIN, llvm::ISD::STRICT_FSQRT, llvm::ISD::STRICT_FSUB, llvm::ISD::STRICT_FTRUNC, llvm::ISD::SUBC, llvm::ISD::SUBCARRY, llvm::ISD::SUBE, llvm::ISD::TRAP, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULFIX, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::USUBSAT, llvm::ISD::VECREDUCE_ADD, llvm::ISD::VECREDUCE_AND, llvm::ISD::VECREDUCE_FADD, llvm::ISD::VECREDUCE_FMAX, llvm::ISD::VECREDUCE_FMIN, llvm::ISD::VECREDUCE_FMUL, llvm::ISD::VECREDUCE_MUL, llvm::ISD::VECREDUCE_OR, llvm::ISD::VECREDUCE_SMAX, llvm::ISD::VECREDUCE_SMIN, llvm::ISD::VECREDUCE_UMAX, llvm::ISD::VECREDUCE_UMIN, llvm::ISD::VECREDUCE_XOR, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by TargetLoweringBase().
insertSSPDeclarations()
void TargetLoweringBase::insertSSPDeclarations (Module & M) const virtual
Inserts necessary declarations for SSP (stack protection) purpose.
Should be used only when getIRStackGuard returns nullptr.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1739 of file TargetLoweringBase.cpp.
References llvm::GlobalValue::ExternalLinkage, and llvm::Type::getInt8PtrTy().
Referenced by getStackGuard(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::PPCTargetLowering::insertSSPDeclarations(), llvm::SparcTargetLowering::insertSSPDeclarations(), and llvm::X86TargetLowering::insertSSPDeclarations().
InstructionOpcodeToISD()
int TargetLoweringBase::InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
Definition at line 1530 of file TargetLoweringBase.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDRSPACECAST, llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREM, llvm::ISD::FSUB, llvm::ISD::INSERT_VECTOR_ELT, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::LanaiTTIImpl::getArithmeticInstrCost(), llvm::NVPTXTTIImpl::getArithmeticInstrCost(), llvm::PPCTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::PPCTTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), isPromotedInstructionLegal(), SinkShiftAndTruncate(), and llvm::PPCTTIImpl::vectorCostAdjustment().
isBinOp()
virtual bool llvm::TargetLoweringBase::isBinOp (unsigned Opcode) const inline virtual
Return true if the node is a math/logic binary operator.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2240 of file TargetLowering.h.
References llvm::ISD::FDIV, llvm::ISD::FREM, llvm::ISD::FSUB, isCommutativeBinOp(), llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::UDIV, and llvm::ISD::UREM.
Referenced by getKnownUndefForVectorBinop(), llvm::X86TargetLowering::isBinOp(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), and scalarizeExtractedBinop().
isCheapToSpeculateCtlz()
virtual bool llvm::TargetLoweringBase::isCheapToSpeculateCtlz () const inline virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 462 of file TargetLowering.h.
Referenced by despeculateCountZeros().
isCheapToSpeculateCttz()
virtual bool llvm::TargetLoweringBase::isCheapToSpeculateCttz () const inline virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 457 of file TargetLowering.h.
Referenced by despeculateCountZeros().
isCommutativeBinOp()
virtual bool llvm::TargetLoweringBase::isCommutativeBinOp (unsigned Opcode) const inline virtual
Returns true if the opcode is a commutative binary operation.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2204 of file TargetLowering.h.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::FADD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, and llvm::ISD::XOR.
Referenced by llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::getNode(), isBinOp(), llvm::X86TargetLowering::isCommutativeBinOp(), and llvm::TargetLowering::SimplifySetCC().
isCondCodeLegal()
bool llvm::TargetLoweringBase::isCondCodeLegal (ISD::CondCode CC, MVT VT) const inline
Return true if the specified condition code is legal on this target.
Definition at line 1155 of file TargetLowering.h.
References getCondCodeAction(), and Legal.
Referenced by llvm::SelectionDAG::FoldSetCC(), llvm::R600TargetLowering::PerformDAGCombine(), and llvm::TargetLowering::SimplifySetCC().
isCondCodeLegalOrCustom()
bool llvm::TargetLoweringBase::isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const inline
Return true if the specified condition code is legal or custom on this target.
Definition at line 1161 of file TargetLowering.h.
References Custom, getCondCodeAction(), and Legal.
isCtlzFast()
virtual bool llvm::TargetLoweringBase::isCtlzFast () const inline virtual
Return true if ctlz instruction is fast.
Reimplemented in llvm::HexagonTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 467 of file TargetLowering.h.
Referenced by llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl().
isExtFree()
bool llvm::TargetLoweringBase::isExtFree (const Instruction * I) const inline
Return true if the extension represented by I is free.
Unlikely the is[Z|FP]ExtFree family which is based on types, this method can use the context provided by I to decide whether or not I is free. This method extends the behavior of the is[Z|FP]ExtFree family. In other words, if is[Z|FP]Free returns true, then this method returns true as well. The converse is not true. The target can perform the adequate checks by overriding isExtFreeImpl.
Precondition
I must be a sign, zero, or fp extension.
Definition at line 2295 of file TargetLowering.h.
References llvm::CCValAssign::FPExt, llvm::EVT::getEVT(), I, isExtFreeImpl(), isFPExtFree(), isZExtFree(), llvm_unreachable, llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
isExtFreeImpl()
virtual bool llvm::TargetLoweringBase::isExtFreeImpl (const Instruction * I) const inline protected virtual
Return true if the extension represented by I is free.
Precondition
I is a sign, zero, or fp extension and is[Z|FP]ExtFree of the related types is not true.
Definition at line 2785 of file TargetLowering.h.
Referenced by isExtFree().
isExtLoad()
bool llvm::TargetLoweringBase::isExtLoad (const LoadInst * Load, const Instruction * Ext, const DataLayout & DL) const inline
Return true if Load and Ext can form an ExtLoad.
For example, in AArch64 L = load i8, i8* ptr E = zext i8 L to i32 can be lowered into one load instruction ldrb w0, [x0]
Definition at line 2320 of file TargetLowering.h.
References assert(), getValueType(), isLoadExtLegal(), isTruncateFree(), isTypeLegal(), llvm::ISD::SEXTLOAD, and llvm::ISD::ZEXTLOAD.
isExtractSubvectorCheap()
virtual bool llvm::TargetLoweringBase::isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const inline virtual
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
This is needed because EXTRACT_SUBVECTOR usually has custom lowering that depends on the index of the first element, and only the target knows which lowering is cheap.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2511 of file TargetLowering.h.
Referenced by narrowExtractedVectorBinOp().
isExtractVecEltCheap()
virtual bool llvm::TargetLoweringBase::isExtractVecEltCheap (EVT VT, unsigned Index) const inline virtual
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
For example, if scalar operations occur on the same register file as vector operations, then an extract element may be a sub-register rename rather than an actual instruction.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2526 of file TargetLowering.h.
Referenced by scalarizeBinOpOfSplats().
isFAbsFree()
virtual bool llvm::TargetLoweringBase::isFAbsFree (EVT VT) const inline virtual
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 2473 of file TargetLowering.h.
References assert(), and llvm::EVT::isFloatingPoint().
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost().
isFMAFasterThanFMulAndFAdd()
virtual bool llvm::TargetLoweringBase::isFMAFasterThanFMulAndFAdd (EVT) const inline virtual
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
NOTE: This may be called before legalization on types for which FMAs are not legal, but should return true if those types will eventually legalize to types that support FMAs. After legalization, it will only be called on types that support FMAs (via Legal or Custom actions)
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, llvm::HexagonTargetLowering, and llvm::NVPTXTargetLowering.
Definition at line 2486 of file TargetLowering.h.
isFNegFree()
virtual bool llvm::TargetLoweringBase::isFNegFree (EVT VT) const inline virtual
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::ARMTargetLowering.
Definition at line 2466 of file TargetLowering.h.
References assert(), and llvm::EVT::isFloatingPoint().
isFPExtFoldable()
virtual bool llvm::TargetLoweringBase::isFPExtFoldable (unsigned Opcode, EVT DestVT, EVT SrcVT) const inline virtual
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
Reimplemented in llvm::SITargetLowering.
Definition at line 2454 of file TargetLowering.h.
References assert(), llvm::EVT::isFloatingPoint(), and isFPExtFree().
isFPExtFree()
virtual bool llvm::TargetLoweringBase::isFPExtFree (EVT DestVT, EVT SrcVT) const inline virtual
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
Reimplemented in llvm::PPCTargetLowering.
Definition at line 2445 of file TargetLowering.h.
References assert(), and llvm::EVT::isFloatingPoint().
Referenced by isExtFree(), isFPExtFoldable(), and isNegatibleForFree().
isFPImmLegal()
virtual bool llvm::TargetLoweringBase::isFPImmLegal (const APFloat & , EVT , bool ForCodeSize = false) const inline virtual
Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::HexagonTargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::ARMTargetLowering.
Definition at line 822 of file TargetLowering.h.
Referenced by isNegatibleForFree().
isFreeAddrSpaceCast()
virtual bool llvm::TargetLoweringBase::isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline virtual
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
we are happy to sink it into basic blocks. A cast may be free, but not necessarily a no-op. e.g. a free truncate from a 64-bit to 32-bit pointer.
Reimplemented in llvm::SITargetLowering.
Definition at line 1612 of file TargetLowering.h.
References isNoopAddrSpaceCast().
Referenced by llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getOperationCost(), and OptimizeNoopCopyExpression().
isFsqrtCheap()
virtual bool llvm::TargetLoweringBase::isFsqrtCheap (SDValue X, SelectionDAG & DAG) const inline virtual
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 339 of file TargetLowering.h.
isIndexedLoadLegal()
bool llvm::TargetLoweringBase::isIndexedLoadLegal (unsigned IdxMode, EVT VT) const inline
Return true if the specified indexed load is legal on this target.
Definition at line 1114 of file TargetLowering.h.
References Custom, getIndexedLoadAction(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and Legal.
Referenced by llvm::BasicTTIImplBase< T >::isIndexedLoadLegal().
isIndexedStoreLegal()
bool llvm::TargetLoweringBase::isIndexedStoreLegal (unsigned IdxMode, EVT VT) const inline
Return true if the specified indexed load is legal on this target.
Definition at line 1132 of file TargetLowering.h.
References Custom, getIndexedStoreAction(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and Legal.
Referenced by llvm::BasicTTIImplBase< T >::isIndexedStoreLegal().
isIntDivCheap()
virtual bool llvm::TargetLoweringBase::isIntDivCheap (EVT VT, AttributeList Attr) const inline virtual
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
The definition of "cheaper" may depend on whether we're optimizing for speed or for size.
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 331 of file TargetLowering.h.
Referenced by llvm::TargetLowering::BuildSDIVPow2(), and llvm::TargetLowering::SimplifySetCC().
isJumpExpensive()
bool llvm::TargetLoweringBase::isJumpExpensive () const inline
Return true if Flow Control is an expensive operation that should be avoided.
Definition at line 386 of file TargetLowering.h.
isJumpTableRelative()
virtual bool llvm::TargetLoweringBase::isJumpTableRelative () const inline virtual
Reimplemented in llvm::MipsTargetLowering, and llvm::PPCTargetLowering.
Definition at line 1495 of file TargetLowering.h.
References llvm::TargetMachine::isPositionIndependent().
Referenced by llvm::PPCTargetLowering::isJumpTableRelative().
isLegalAddImmediate()
virtual bool llvm::TargetLoweringBase::isLegalAddImmediate (int64_t) const inline virtual
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::AArch64TargetLowering.
Definition at line 2183 of file TargetLowering.h.
Referenced by llvm::BasicTTIImplBase< T >::isLegalAddImmediate().
isLegalAddressingMode()
bool TargetLoweringBase::isLegalAddressingMode (const DataLayout & DL, const AddrMode & AM, Type * Ty, unsigned AddrSpace, Instruction * I = nullptr) const virtual
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
If the address space cannot be determined, it will be -1.
TODO: Remove default argument
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::ARCTargetLowering, llvm::ARMTargetLowering, llvm::AVRTargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 1687 of file TargetLoweringBase.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
Referenced by canFoldInAddressingMode(), getScalingFactorCost(), and llvm::BasicTTIImplBase< T >::isLegalAddressingMode().
isLegalICmpImmediate()
virtual bool llvm::TargetLoweringBase::isLegalICmpImmediate (int64_t) const inline virtual
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented in llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::AArch64TargetLowering.
Definition at line 2176 of file TargetLowering.h.
Referenced by llvm::BasicTTIImplBase< T >::isLegalICmpImmediate(), and llvm::TargetLowering::SimplifySetCC().
isLegalRC()
bool TargetLoweringBase::isLegalRC (const TargetRegisterInfo & TRI, const TargetRegisterClass & RC) const protected
Return true if the value types that can be represented by the specified register class are all legal.
isLegalRC - Return true if the value types that can be represented by the specified register class are all legal.
Definition at line 999 of file TargetLoweringBase.cpp.
References I, isTypeLegal(), llvm::MVT::Other, and TRI.
Referenced by findRepresentativeClass(), and llvm::TargetLowering::getRegForInlineAsmConstraint().
isLegalStoreImmediate()
virtual bool llvm::TargetLoweringBase::isLegalStoreImmediate (int64_t Value) const inline virtual
Return true if the specified immediate is legal for the value input of a store instruction.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2189 of file TargetLowering.h.
Referenced by getMemsetValue().
isLoadBitCastBeneficial()
virtual bool llvm::TargetLoweringBase::isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG & DAG, const MachineMemOperand & MMO) const inline virtual
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
Reimplemented in llvm::X86TargetLowering, and llvm::AMDGPUTargetLowering.
Definition at line 404 of file TargetLowering.h.
References allowsMemoryAccess(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), getOperationAction(), llvm::EVT::getSimpleVT(), getTypeToPromoteTo(), llvm::EVT::isSimple(), llvm::ISD::LOAD, and Promote.
Referenced by llvm::X86TargetLowering::isLoadBitCastBeneficial(), and isStoreBitCastBeneficial().
isLoadExtLegal()
bool llvm::TargetLoweringBase::isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const inline
Return true if the specified load with extension is legal on this target.
Definition at line 1065 of file TargetLowering.h.
References getLoadExtAction(), and Legal.
Referenced by combineExtInVec(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), isExtLoad(), tryToFoldExtOfExtload(), and tryToFoldExtOfLoad().
isLoadExtLegalOrCustom()
bool llvm::TargetLoweringBase::isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const inline
Return true if the specified load with extension is legal or custom on this target.
Definition at line 1071 of file TargetLowering.h.
References Custom, getLoadExtAction(), and Legal.
isMaskAndCmp0FoldingBeneficial()
virtual bool llvm::TargetLoweringBase::isMaskAndCmp0FoldingBeneficial (const Instruction & AndI) const inline virtual
Return if the target supports combining a chain like:
%andResult = and %val1, #mask
%icmpResult = icmp %andResult, 0
into a single machine instruction of a form like:
cc = test %register, #mask
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 495 of file TargetLowering.h.
Referenced by sinkAndCmp0Expression().
isMultiStoresCheaperThanBitsMerge()
virtual bool llvm::TargetLoweringBase::isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const inline virtual
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
Reimplemented in llvm::X86TargetLowering.
Definition at line 481 of file TargetLowering.h.
Referenced by splitMergedValStore().
isNarrowingProfitable()
virtual bool llvm::TargetLoweringBase::isNarrowingProfitable (EVT , EVT) const inline virtual
Return true if it's profitable to narrow operations of type VT1 to VT2.
e.g. on x86, it's profitable to narrow from i32 to i8 but not from i32 to i16.
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::X86TargetLowering.
Definition at line 2493 of file TargetLowering.h.
isNoopAddrSpaceCast()
virtual bool llvm::TargetLoweringBase::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::ARMTargetLowering, llvm::MipsTargetLowering, and llvm::X86TargetLowering.
Definition at line 1605 of file TargetLowering.h.
Referenced by checkAddrSpaceIsValidForLibcall(), and isFreeAddrSpaceCast().
isOperationCustom()
bool llvm::TargetLoweringBase::isOperationCustom (unsigned Op, EVT VT) const inline
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
Definition at line 966 of file TargetLowering.h.
References Custom, and getOperationAction().
Referenced by llvm::PPCTargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::X86TargetLowering().
isOperationExpand()
bool llvm::TargetLoweringBase::isOperationExpand (unsigned Op, EVT VT) const inline
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
This is used to help guide high-level lowering decisions.
Definition at line 1040 of file TargetLowering.h.
References Expand, getOperationAction(), and isTypeLegal().
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), shouldFormOverflowOp(), llvm::X86TargetLowering::shouldFormOverflowOp(), llvm::PPCTTIImpl::vectorCostAdjustment(), and llvm::X86TargetLowering::X86TargetLowering().
isOperationLegal()
bool llvm::TargetLoweringBase::isOperationLegal (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target.
Definition at line 1045 of file TargetLowering.h.
References getOperationAction(), isTypeLegal(), Legal, and llvm::MVT::Other.
Referenced by llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineLogicBlendIntoConditionalNegate(), combineParity(), combineShuffle(), combineTruncatedArithmetic(), llvm::X86TargetLowering::decomposeMulByConstant(), EltsFromConsecutiveLoads(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandROT(), foldFPToIntToFP(), llvm::X86TTIImpl::hasDivRemOp(), isNegatibleForFree(), LowerADDSAT_SUBSAT(), LowerVSETCC(), PerformABSCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), stripModuloOnShift(), and tryFoldToZero().
isOperationLegalOrCustom()
bool llvm::TargetLoweringBase::isOperationLegalOrCustom (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
This is used to help guide high-level lowering decisions.
Definition at line 939 of file TargetLowering.h.
References Custom, getOperationAction(), isTypeLegal(), Legal, and llvm::MVT::Other.
Referenced by areJTsAllowed(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineExtractSubvector(), combineMinNumMaxNum(), combineShuffleToVectorExtend(), combineVSelectToBLENDV(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVecReduce(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), getAsCarry(), llvm::BasicTTIImplBase< T >::haveFastSqrt(), llvm::AArch64TargetLowering::isExtractSubvectorCheap(), llvm::ARMTargetLowering::isExtractSubvectorCheap(), llvm::X86TargetLowering::isExtractSubvectorCheap(), llvm::HexagonTargetLowering::isFMAFasterThanFMulAndFAdd(), isNegatibleForFree(), llvm::AArch64TargetLowering::isProfitableToHoist(), isPromotedInstructionLegal(), makeBitReverse(), narrowInsertExtractVectorBinOp(), scalarizeBinOpOfSplats(), llvm::BasicTTIImplBase< T >::shouldBuildLookupTables(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SinkShiftAndTruncate(), and XFormVExtractWithShuffleIntoLoad().
isOperationLegalOrCustomOrPromote()
bool llvm::TargetLoweringBase::isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
This is used to help guide high-level lowering decisions.
Definition at line 957 of file TargetLowering.h.
References Custom, getOperationAction(), isTypeLegal(), Legal, llvm::MVT::Other, and Promote.
Referenced by llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::BasicTTIImplBase< T >::getFPOpCost(), narrowExtractedVectorBinOp(), and llvm::X86TargetLowering::shouldScalarizeBinop().
isOperationLegalOrPromote()
bool llvm::TargetLoweringBase::isOperationLegalOrPromote (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target or can be made legal using promotion.
This is used to help guide high-level lowering decisions.
Definition at line 948 of file TargetLowering.h.
References getOperationAction(), isTypeLegal(), Legal, llvm::MVT::Other, and Promote.
Referenced by combineTruncatedArithmetic(), llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), lowerBuildVectorToBitOp(), and PromoteMaskArithmetic().
isPredictableSelectExpensive()
bool llvm::TargetLoweringBase::isPredictableSelectExpensive () const inline
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
Definition at line 390 of file TargetLowering.h.
References PredictableSelectIsExpensive.
Referenced by isFormingBranchFromSelectProfitable().
isProfitableToCombineMinNumMaxNum()
virtual bool llvm::TargetLoweringBase::isProfitableToCombineMinNumMaxNum (EVT VT) const inline virtual
Definition at line 1837 of file TargetLowering.h.
Referenced by isLegalToCombineMinNumMaxNum().
isProfitableToHoist()
virtual bool llvm::TargetLoweringBase::isProfitableToHoist (Instruction * I) const inline virtual
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 2284 of file TargetLowering.h.
Referenced by llvm::BasicTTIImplBase< T >::isProfitableToHoist().
isSafeMemOpType()
virtual bool llvm::TargetLoweringBase::isSafeMemOpType (MVT) const inline virtual
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
This is mostly true for all types except for some special cases. For example, on X86 targets without SSE2 f64 load / store are done with fldl / fstpl which also does type conversion. Note the specified type doesn't have to be legal as the hook is used before type legalization.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1473 of file TargetLowering.h.
Referenced by llvm::TargetLowering::findOptimalMemOpLowering().
isSelectSupported()
virtual bool llvm::TargetLoweringBase::isSelectSupported (SelectSupportKind) const inline virtual
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::AMDGPUTargetLowering.
Definition at line 279 of file TargetLowering.h.
isSExtCheaperThanZExt()
virtual bool llvm::TargetLoweringBase::isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const inline virtual
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
Reimplemented in llvm::RISCVTargetLowering.
Definition at line 2363 of file TargetLowering.h.
isShuffleMaskLegal()
virtual bool llvm::TargetLoweringBase::isShuffleMaskLegal (ArrayRef< int > , EVT) const inline virtual
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsSETargetLowering, llvm::X86TargetLowering, and llvm::SITargetLowering.
Definition at line 831 of file TargetLowering.h.
Referenced by combineConcatVectorOfExtracts(), ExpandBVWithShuffles(), foldShuffleOfConcatUndefs(), reduceBuildVecToShuffleWithZero(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
isSlowDivBypassed()
bool llvm::TargetLoweringBase::isSlowDivBypassed () const inline
Returns true if target has indicated at least one type should be bypassed.
Definition at line 376 of file TargetLowering.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
isStoreBitCastBeneficial()
virtual bool llvm::TargetLoweringBase::isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG & DAG, const MachineMemOperand & MMO) const inline virtual
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
Definition at line 427 of file TargetLowering.h.
References isLoadBitCastBeneficial().
isSuitableForBitTests()
bool llvm::TargetLoweringBase::isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt & Low, const APInt & High, const DataLayout & DL) const inline
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
Check if the number of destinations, comparison metric, and range are all suitable.
Definition at line 1015 of file TargetLowering.h.
References High, and rangeFitsInWord().
Referenced by llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters().
isSuitableForJumpTable()
virtual bool llvm::TargetLoweringBase::isSuitableForJumpTable (const SwitchInst * SI, uint64_t NumCases, uint64_t Range) const inline virtual
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
Definition at line 990 of file TargetLowering.h.
References getMaximumJumpTableSize(), getMinimumJumpTableDensity(), and SI.
Referenced by llvm::SwitchCG::SwitchLowering::findJumpTables(), and llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters().
isSupportedFixedPointOperation()
virtual bool llvm::TargetLoweringBase::isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const inline virtual
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
If not, the operation is illegal.
Definition at line 863 of file TargetLowering.h.
Referenced by getFixedPointOperationAction().
isTruncateFree() [1/2]
virtual bool llvm::TargetLoweringBase::isTruncateFree (EVT FromVT, EVT ToVT) const inline virtual
Reimplemented in llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::RISCVTargetLowering, llvm::AArch64TargetLowering, llvm::HexagonTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::X86TargetLowering, and llvm::SystemZTargetLowering.
Definition at line 2280 of file TargetLowering.h.
isTruncateFree() [2/2]
virtual bool llvm::TargetLoweringBase::isTruncateFree (Type * FromTy, Type * ToTy) const inline virtual
Return true if it's free to truncate a value of type FromTy to type ToTy.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX. Targets must return false when FromTy <= ToTy.
Reimplemented in llvm::SystemZTargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::NVPTXTargetLowering, llvm::RISCVTargetLowering, llvm::AArch64TargetLowering, llvm::HexagonTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 2267 of file TargetLowering.h.
Referenced by ExtendUsesToFormExtLoad(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), getMemsetStores(), llvm::BasicTTIImplBase< T >::getOperationCost(), isExtLoad(), llvm::BasicTTIImplBase< T >::isTruncateFree(), and llvm::TargetLowering::ShrinkDemandedOp().
isTruncStoreLegal()
bool llvm::TargetLoweringBase::isTruncStoreLegal (EVT ValVT, EVT MemVT) const inline
Return true if the specified store with truncation is legal on this target.
Definition at line 1090 of file TargetLowering.h.
References getTruncStoreAction(), isTypeLegal(), and Legal.
Referenced by combineMaskedStore().
isTruncStoreLegalOrCustom()
bool llvm::TargetLoweringBase::isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const inline
Return true if the specified store with truncation has solution on this target.
Definition at line 1096 of file TargetLowering.h.
References Custom, getTruncStoreAction(), isTypeLegal(), and Legal.
Referenced by combineStore().
isTypeLegal()
bool llvm::TargetLoweringBase::isTypeLegal (EVT VT) const inline
Return true if the target has native support for the specified value type.
This means that it has a register that directly holds it without promotions or expansions.
Definition at line 700 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and llvm::MVT::SimpleTy.
Referenced by llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canOpTrap(), CollectOpsToWiden(), combineConcatVectorOfScalars(), combineConcatVectors(), combineExtInVec(), combineExtractSubvector(), combineFMA(), combineFMinNumFMaxNum(), combineFneg(), combineHorizontalPredicateResult(), combineLoad(), combineMaskedLoad(), combineMaskedStore(), combineMulToPMADDWD(), combineParity(), combineSelect(), combineSelectOfTwoConstants(), combineShuffle(), combineShuffleToFMAddSub(), combineShuffleToVectorExtend(), combineStore(), combineToExtendVectorInReg(), combineTruncateWithSat(), combineVSelectWithAllOnesOrZeros(), combineX86ShuffleChain(), computeRegisterProperties(), detectAVX512SSatPattern(), detectAVX512USatPattern(), EltsFromConsecutiveLoads(), ExpandBITCAST(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::findOptimalMemOpLowering(), getConstVector(), getCopyFromPartsVector(), getCopyToParts(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), getPromotedVectorElementType(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::FastISel::getRegForValue(), getTypeToPromoteTo(), getVectorTypeBreakdown(), getVectorTypeBreakdownMVT(), llvm::SITargetLowering::hasBitPreservingFPLogic(), llvm::SystemZTTIImpl::hasDivRemOp(), hasFastEqualityCompare(), llvm::X86TargetLowering::hasFastEqualityCompare(), llvm::BasicTTIImplBase< T >::haveFastSqrt(), llvm::GenericScheduler::initPolicy(), isAddSubOrSubAdd(), isExtLoad(), isLegalRC(), llvm::X86TargetLowering::isLoadBitCastBeneficial(), isNoopBitcast(), isOperationExpand(), isOperationLegal(), isOperationLegalOrCustom(), isOperationLegalOrCustomOrPromote(), isOperationLegalOrPromote(), llvm::X86TargetLowering::isShuffleMaskLegal(), isTruncStoreLegal(), isTruncStoreLegalOrCustom(), llvm::X86TargetLowering::isTypeDesirableForOp(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::BasicTTIImplBase< T >::isTypeLegal(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSUBCARRY(), LowerATOMIC_STORE(), LowerBITCAST(), lowerFCMPIntrinsic(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), lowerICMPIntrinsic(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), LowerLoad(), lowerShuffleAsElementInsertion(), lowerShuffleAsShift(), LowerSINT_TO_FP(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP(), lowerVectorShuffle(), LowerXALUO(), LowerXOR(), OptimizeExtractBits(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), PerformExtendCombine(), performExtendCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformLOADCombine(), performORCombine(), PerformORCombine(), performSelectCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), PerformXORCombine(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectFNeg(), llvm::AMDGPUTargetLowering::shouldCombineMemoryType(), llvm::X86TargetLowering::shouldSplatInsEltVarIndex(), llvm::TargetLowering::SimplifySetCC(), llvm::SystemZTargetLowering::SystemZTargetLowering(), tryToFoldExtendOfConstant(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and llvm::X86TargetLowering::X86TargetLowering().
isVectorClearMaskLegal()
virtual bool llvm::TargetLoweringBase::isVectorClearMaskLegal (ArrayRef< int > , EVT) const inline virtual
Similar to isShuffleMaskLegal.
Targets can use this to indicate if there is a suitable VECTOR_SHUFFLE that can be used to replace a VAND with a constant pool entry.
Reimplemented in llvm::X86TargetLowering.
Definition at line 844 of file TargetLowering.h.
isVectorLoadExtDesirable()
virtual bool llvm::TargetLoweringBase::isVectorLoadExtDesirable (SDValue ExtVal) const inline virtual
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
Reimplemented in llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2462 of file TargetLowering.h.
Referenced by tryToFoldExtOfLoad().
isVectorShiftByScalarCheap()
virtual bool llvm::TargetLoweringBase::isVectorShiftByScalarCheap (Type * Ty) const inline virtual
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
On x86, for example, there is a "psllw" instruction for the former case, but no simple instruction for a general "a << b" operation on vectors.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2199 of file TargetLowering.h.
isZExtFree() [1/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (EVT FromTy, EVT ToTy) const inline virtual
Reimplemented in llvm::AMDGPUTargetLowering, llvm::AArch64TargetLowering, llvm::MSP430TargetLowering, and llvm::X86TargetLowering.
Definition at line 2357 of file TargetLowering.h.
isZExtFree() [2/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (SDValue Val, EVT VT2) const inline virtual
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 2438 of file TargetLowering.h.
References llvm::SDValue::getValueType(), and isZExtFree().
isZExtFree() [3/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (Type * FromTy, Type * ToTy) const inline virtual
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
The function should return true when it is likely that the truncate can be freely folded with an instruction defining a value of FromTy. If the defining instruction is unknown (because you're looking at a function argument, PHI, etc.) then the target may require an explicit truncate, which is not necessarily free, but this function does not deal with those cases. Targets must return false when FromTy >= ToTy.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::AArch64TargetLowering, llvm::MSP430TargetLowering, and llvm::X86TargetLowering.
Definition at line 2353 of file TargetLowering.h.
Referenced by combineShuffleOfScalars(), foldCONCAT_VECTORS(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::RegsForValue::getCopyToRegs(), llvm::BasicTTIImplBase< T >::getOperationCost(), hasSameExtUse(), isExtFree(), isZExtFree(), llvm::PPCTargetLowering::isZExtFree(), llvm::RISCVTargetLowering::isZExtFree(), llvm::TargetLowering::ShrinkDemandedOp(), and tryToFoldExtendOfConstant().
lowerIdempotentRMWIntoFencedLoad()
virtual LoadInst * llvm::TargetLoweringBase::lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst * RMWI) const inline virtual
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
This may sound useless, but it makes it possible for the processor to keep the cacheline shared, dramatically improving performance. And such idempotent RMWs are useful for implementing some kinds of locks, see for example (justification + benchmarks): http://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf This method tries doing that transformation, returning the atomic load if it succeeds, and nullptr otherwise. If shouldExpandAtomicLoadInIR returns true on that load, it will undergo another round of expansion.
Definition at line 1807 of file TargetLowering.h.
lowerInterleavedLoad()
virtual bool llvm::TargetLoweringBase::lowerInterleavedLoad (LoadInst * LI, ArrayRef< ShuffleVectorInst * > Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const inline virtual
Lower an interleaved load to target specific intrinsics.
Return true on success.
LI is the vector load instruction. Shuffles is the shufflevector list to DE-interleave the loaded vector. Indices is the corresponding indices for each shufflevector. Factor is the interleave factor.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2417 of file TargetLowering.h.
lowerInterleavedStore()
virtual bool llvm::TargetLoweringBase::lowerInterleavedStore (StoreInst * SI, ShuffleVectorInst * SVI, unsigned Factor) const inline virtual
Lower an interleaved store to target specific intrinsics.
Return true on success.
SI is the vector store instruction. SVI is the shufflevector to RE-interleave the stored vector. Factor is the interleave factor.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2430 of file TargetLowering.h.
markLibCallAttributes()
virtual void llvm::TargetLoweringBase::markLibCallAttributes (MachineFunction * MF, unsigned CC, ArgListTy & Args) const inline virtual
Reimplemented in llvm::X86TargetLowering.
Definition at line 206 of file TargetLowering.h.
Referenced by llvm::FastISel::lowerCallTo(), and llvm::TargetLowering::CallLoweringInfo::setLibCallee().
mergeStoresAfterLegalization()
virtual bool llvm::TargetLoweringBase::mergeStoresAfterLegalization (EVT MemVT) const inline virtual
Allow store merging for the specified type after legalization in addition to before legalization.
This may transform stores that do not exist earlier (for example, stores created from intrinsics).
Reimplemented in llvm::X86TargetLowering, and llvm::AMDGPUTargetLowering.
Definition at line 446 of file TargetLowering.h.
needsFixedCatchObjects()
virtual bool llvm::TargetLoweringBase::needsFixedCatchObjects () const inline virtual
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 1521 of file TargetLowering.h.
References llvm::report_fatal_error().
Referenced by llvm::FunctionLoweringInfo::set().
operator=()
TargetLoweringBase & llvm::TargetLoweringBase::operator= (const TargetLoweringBase &) delete
preferIncOfAddToSubOfNot()
virtual bool llvm::TargetLoweringBase::preferIncOfAddToSubOfNot (EVT VT) const inline virtual
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
Some targets may prefer one to the other.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 579 of file TargetLowering.h.
rangeFitsInWord()
bool llvm::TargetLoweringBase::rangeFitsInWord (const APInt & Low, const APInt & High, const DataLayout & DL) const inline
Check whether the range [Low,High] fits in a machine word.
Definition at line 980 of file TargetLowering.h.
References llvm::DataLayout::getIndexSizeInBits(), High, and UINT64_MAX.
Referenced by isSuitableForBitTests().
reduceSelectOfFPConstantLoads()
virtual bool llvm::TargetLoweringBase::reduceSelectOfFPConstantLoads (bool IsFPSetCC) const inline virtual
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
The parameter may be used to differentiate a select with FP compare from integer compare.
Reimplemented in llvm::X86TargetLowering.
Definition at line 287 of file TargetLowering.h.
requiresUniformRegister()
virtual bool llvm::TargetLoweringBase::requiresUniformRegister (MachineFunction & MF, const Value *) const inline virtual
Allows target to decide about the register class of the specific value that is live outside the defining block.
Returns true if the value needs uniform register class.
Definition at line 667 of file TargetLowering.h.
Referenced by llvm::FunctionLoweringInfo::CreateRegs().
setBooleanContents() [1/2]
void llvm::TargetLoweringBase::setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy) inline protected
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
See getBooleanContents.
Definition at line 1879 of file TargetLowering.h.
setBooleanContents() [2/2]
void llvm::TargetLoweringBase::setBooleanContents (BooleanContent Ty) inline protected
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
See getBooleanContents.
Definition at line 1872 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setBooleanVectorContents()
void llvm::TargetLoweringBase::setBooleanVectorContents (BooleanContent Ty) inline protected
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
See getBooleanContents.
Definition at line 1886 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setCmpLibcallCC()
void llvm::TargetLoweringBase::setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC) inline
Override the default CondCode to be used to test the result of the comparison libcall against zero.
Definition at line 2574 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::MSP430TargetLowering::MSP430TargetLowering().
setCondCodeAction()
void llvm::TargetLoweringBase::setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
The lower 3 bits of the SimpleTy index into Nth 4bit set from the 32-bit value and the upper 29 bits index into the second dimension of the array to select what 32-bit value to use.
Definition at line 2023 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), llvm::MVT::isValid(), and llvm::MVT::SimpleTy.
Referenced by llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setHasExtractBitsInsn()
void llvm::TargetLoweringBase::setHasExtractBitsInsn (bool hasExtractInsn = true) inline protected
Tells the code generator that the target has BitExtract instructions.
The code generator will aggressively sink "shift"s into the blocks of their users if the users will generate "and" instructions which can be combined with "shift" to BitExtract instructions.
Definition at line 1933 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), and llvm::SITargetLowering::SITargetLowering().
setHasMultipleConditionRegisters()
void llvm::TargetLoweringBase::setHasMultipleConditionRegisters (bool hasManyRegs = true) inline protected
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
With multiple condition registers, the code generator will not aggressively sink comparisons into the blocks of their users.
Definition at line 1925 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setIndexedLoadAction()
void llvm::TargetLoweringBase::setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
NOTE: All indexed mode loads are initialized to Expand in TargetLowering.cpp
Definition at line 1998 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), llvm::MSP430TargetLowering::MSP430TargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setIndexedStoreAction()
void llvm::TargetLoweringBase::setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
NOTE: All indexed mode stores are initialized to Expand in TargetLowering.cpp
Definition at line 2012 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), and llvm::PPCTargetLowering::PPCTargetLowering().
setJumpBufAlignment()
void llvm::TargetLoweringBase::setJumpBufAlignment (unsigned Align) inline protected
Set the target's required jmp_buf buffer alignment (in bytes); default is 0.
Definition at line 2066 of file TargetLowering.h.
setJumpBufSize()
void llvm::TargetLoweringBase::setJumpBufSize (unsigned Size) inline protected
Set the target's required jmp_buf buffer size (in bytes); default is 200.
Definition at line 2060 of file TargetLowering.h.
References Size.
setJumpIsExpensive()
void TargetLoweringBase::setJumpIsExpensive (bool isExpensive = true) protected
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
Definition at line 811 of file TargetLoweringBase.cpp.
References JumpIsExpensiveOverride.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setLibcallCallingConv()
void llvm::TargetLoweringBase::setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC) inline
Set the CallingConv that should be used for the specified libcall.
Definition at line 2585 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setLibcallName()
void llvm::TargetLoweringBase::setLibcallName (RTLIB::Libcall Call, const char * Name) inline
Rename the default libcall routine name for the specified libcall.
Definition at line 2563 of file TargetLowering.h.
References Name.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setLoadExtAction()
void llvm::TargetLoweringBase::setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action) inline protected
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
Definition at line 1975 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), llvm::ISD::LAST_LOADEXT_TYPE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setMaxAtomicSizeInBitsSupported()
void llvm::TargetLoweringBase::setMaxAtomicSizeInBitsSupported (unsigned SizeInBits) inline protected
Set the maximum atomic operation size supported by the backend.
Atomic operations greater than this size (as well as ones that are not naturally aligned), will be expanded by AtomicExpandPass into an __atomic_* library call.
Definition at line 2099 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setMaximumJumpTableSize()
void TargetLoweringBase::setMaximumJumpTableSize (unsigned Val) protected
Indicate the maximum number of entries in jump tables.
Set to zero to generate unlimited jump tables.
Definition at line 1772 of file TargetLoweringBase.cpp.
References MaximumJumpTableSize.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
setMinCmpXchgSizeInBits()
void llvm::TargetLoweringBase::setMinCmpXchgSizeInBits (unsigned SizeInBits) inline protected
Sets the minimum cmpxchg or ll/sc size supported by the backend.
Definition at line 2104 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and llvm::SparcTargetLowering::SparcTargetLowering().
setMinFunctionAlignment()
void llvm::TargetLoweringBase::setMinFunctionAlignment (unsigned Align) inline protected
Set the target's minimum function alignment (in log2(bytes))
Definition at line 2071 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setMinimumJumpTableEntries()
void TargetLoweringBase::setMinimumJumpTableEntries (unsigned Val) protected
Indicate the minimum number of blocks to generate jump tables.
Definition at line 1760 of file TargetLoweringBase.cpp.
References MinimumJumpTableEntries.
Referenced by llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
setMinStackArgumentAlignment()
void llvm::TargetLoweringBase::setMinStackArgumentAlignment (unsigned Align) inline protected
Set the minimum stack alignment of an argument (in log2(bytes)).
Definition at line 2091 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setOperationAction()
void llvm::TargetLoweringBase::setOperationAction (unsigned Op, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
Note that VT may refer to either the type of a result or that of an operand of Op.
Definition at line 1967 of file TargetLowering.h.
References llvm::array_lengthof(), assert(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), setOperationPromotedToType(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setOperationPromotedToType()
void llvm::TargetLoweringBase::setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT) inline protected
Convenience method to set an operation to Promote and specify the type in a single call.
Definition at line 2046 of file TargetLowering.h.
References AddPromotedToType(), Promote, and setOperationAction().
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setPrefFunctionAlignment()
void llvm::TargetLoweringBase::setPrefFunctionAlignment (unsigned Align) inline protected
Set the target's preferred function alignment.
This should be set if there is a performance benefit to higher-than-minimum alignment (in log2(bytes))
Definition at line 2078 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setPrefLoopAlignment()
void llvm::TargetLoweringBase::setPrefLoopAlignment (unsigned Align) inline protected
Set the target's preferred loop alignment.
Default alignment is zero, it means the target does not care about loop alignment. The alignment is specified in log2(bytes). The target may also override getPrefLoopAlignment to provide per-loop values.
Definition at line 2086 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setSchedulingPreference()
void llvm::TargetLoweringBase::setSchedulingPreference (Sched::Preference Pref) inline protected
Specify the target scheduling preference.
Definition at line 1891 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::SITargetLowering::SITargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setStackPointerRegisterToSaveRestore()
void llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore (unsigned R) inline protected
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
Definition at line 1916 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARCTargetLowering::ARCTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setSupportsUnalignedAtomics()
void llvm::TargetLoweringBase::setSupportsUnalignedAtomics (bool UnalignedSupported) inline protected
Sets whether unaligned atomic operations are supported.
Definition at line 2109 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), and llvm::AVRTargetLowering::AVRTargetLowering().
setTargetDAGCombine()
void llvm::TargetLoweringBase::setTargetDAGCombine (ISD::NodeType NT) inline protected
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
Definition at line 2054 of file TargetLowering.h.
References llvm::array_lengthof(), and assert().
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setTruncStoreAction()
void llvm::TargetLoweringBase::setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action) inline protected
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
Definition at line 1987 of file TargetLowering.h.
References assert(), llvm::MVT::isValid(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::AVRTargetLowering::AVRTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setUseUnderscoreLongJmp()
void llvm::TargetLoweringBase::setUseUnderscoreLongJmp (bool Val) inline protected
Indicate whether this target prefers to use _longjmp to implement llvm.longjmp or the version without _.
Defaults to false.
Definition at line 1903 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
setUseUnderscoreSetJmp()
void llvm::TargetLoweringBase::setUseUnderscoreSetJmp (bool Val) inline protected
Indicate whether this target prefers to use _setjmp to implement llvm.setjmp or the version without _.
Defaults to false.
Definition at line 1897 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::X86TargetLowering().
shouldAlignPointerArgs()
virtual bool llvm::TargetLoweringBase::shouldAlignPointerArgs (CallInst * , unsigned & , unsigned &) const inline virtual
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
If so then MinSize is set to the minimum size the object must be to be aligned and PrefAlign is set to the preferred alignment.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 1620 of file TargetLowering.h.
shouldConsiderGEPOffsetSplit()
virtual bool llvm::TargetLoweringBase::shouldConsiderGEPOffsetSplit () const inline virtual
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 2556 of file TargetLowering.h.
shouldConvertConstantLoadToIntImm()
virtual bool llvm::TargetLoweringBase::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const inline virtual
Return true if it is beneficial to convert a load of a constant to just the constant itself.
On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
Reimplemented in llvm::AArch64TargetLowering, llvm::SITargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 2502 of file TargetLowering.h.
Referenced by getMemsetStringVal().
shouldExpandAtomicCmpXchgInIR()
virtual AtomicExpansionKind llvm::TargetLoweringBase::shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst * AI) const inline virtual
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 1784 of file TargetLowering.h.
References None.
shouldExpandAtomicLoadInIR()
virtual AtomicExpansionKind llvm::TargetLoweringBase::shouldExpandAtomicLoadInIR (LoadInst * LI) const inline virtual
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 1777 of file TargetLowering.h.
References None.
shouldExpandAtomicRMWInIR()
virtual AtomicExpansionKind llvm::TargetLoweringBase::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const inline virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::SITargetLowering, llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, and llvm::SparcTargetLowering.
Definition at line 1790 of file TargetLowering.h.
References CmpXChg, llvm::AtomicRMWInst::isFloatingPointOperation(), and None.
shouldExpandAtomicStoreInIR()
virtual bool llvm::TargetLoweringBase::shouldExpandAtomicStoreInIR (StoreInst * SI) const inline virtual
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 1766 of file TargetLowering.h.
shouldExpandBuildVectorWithShuffles()
virtual bool llvm::TargetLoweringBase::shouldExpandBuildVectorWithShuffles (EVT , unsigned DefinedValues) const inline virtual
Reimplemented in llvm::HexagonTargetLowering, and llvm::PPCTargetLowering.
Definition at line 322 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::shouldExpandBuildVectorWithShuffles().
shouldExpandShift()
virtual bool llvm::TargetLoweringBase::shouldExpandShift (SelectionDAG & DAG, SDNode * N) const inline virtual
Return true if SHIFT instructions should be expanded to SHIFT_PARTS instructions, and false if a library call is preferred (e.g for code-size reasons).
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::RISCVTargetLowering, and llvm::X86TargetLowering.
Definition at line 693 of file TargetLowering.h.
shouldFoldConstantShiftPairToMask()
virtual bool llvm::TargetLoweringBase::shouldFoldConstantShiftPairToMask (const SDNode * N, CombineLevel Level) const inline virtual
Return true if it is profitable to fold a pair of shifts into a mask.
This is usually true on most targets. But some targets, like Thumb1, have immediate shift instructions, but no immediate "and" instruction; this makes the fold unprofitable.
Reimplemented in llvm::ARMTargetLowering, llvm::MipsTargetLowering, and llvm::X86TargetLowering.
Definition at line 556 of file TargetLowering.h.
Referenced by llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask().
shouldFoldMaskToVariableShiftPair()
virtual bool llvm::TargetLoweringBase::shouldFoldMaskToVariableShiftPair (SDValue X) const inline virtual
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
Return false if there is no preference.
Reimplemented in llvm::X86TargetLowering.
Definition at line 547 of file TargetLowering.h.
shouldFormOverflowOp()
virtual bool llvm::TargetLoweringBase::shouldFormOverflowOp (unsigned Opcode, EVT VT) const inline virtual
Try to convert math with an overflow comparison into the corresponding DAG node operation.
Targets may want to override this independently of whether the operation is legal/custom for the given type because it may obscure matching of other patterns.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2534 of file TargetLowering.h.
References isOperationExpand(), llvm::EVT::isSimple(), llvm::EVT::isVector(), and llvm::ISD::UADDO.
shouldInsertFencesForAtomic()
virtual bool llvm::TargetLoweringBase::shouldInsertFencesForAtomic (const Instruction * I) const inline virtual
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
This should be true for most architectures with weak memory ordering. Defaults to false.
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::RISCVTargetLowering, and llvm::SparcTargetLowering.
Definition at line 1665 of file TargetLowering.h.
shouldNormalizeToSelectSequence()
virtual bool llvm::TargetLoweringBase::shouldNormalizeToSelectSequence (LLVMContext & Context, EVT VT) const inline virtual
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
Targets that are able to perform and/or on flags should return false here.
Definition at line 1824 of file TargetLowering.h.
References Context, getTypeAction(), hasMultipleConditionRegisters(), TypeExpandFloat, TypeExpandInteger, and TypeSplitVector.
shouldReduceLoadWidth()
virtual bool llvm::TargetLoweringBase::shouldReduceLoadWidth (SDNode * Load, ISD::LoadExtType ExtTy, EVT NewVT) const inline virtual
Return true if it is profitable to reduce a load to a smaller type.
Example: (i16 (trunc (i32 (load x))) -> i16 load x
Reimplemented in llvm::AArch64TargetLowering, llvm::HexagonTargetLowering, llvm::X86TargetLowering, and llvm::AMDGPUTargetLowering.
Definition at line 1331 of file TargetLowering.h.
References llvm::EVT::isVector().
Referenced by narrowExtractedVectorLoad(), llvm::AArch64TargetLowering::shouldReduceLoadWidth(), llvm::HexagonTargetLowering::shouldReduceLoadWidth(), llvm::AMDGPUTargetLowering::shouldReduceLoadWidth(), and llvm::TargetLowering::SimplifySetCC().
shouldScalarizeBinop()
virtual bool llvm::TargetLoweringBase::shouldScalarizeBinop (SDValue VecOp) const inline virtual
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2518 of file TargetLowering.h.
Referenced by scalarizeExtractedBinop().
ShouldShrinkFPConstant()
virtual bool llvm::TargetLoweringBase::ShouldShrinkFPConstant (EVT) const inline virtual
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::SparcTargetLowering, and llvm::X86TargetLowering.
Definition at line 1327 of file TargetLowering.h.
shouldSignExtendTypeInLibCall()
virtual bool llvm::TargetLoweringBase::shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const inline virtual
Returns true if arguments should be sign-extended in lib calls.
Definition at line 1771 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall().
shouldSinkOperands()
virtual bool llvm::TargetLoweringBase::shouldSinkOperands (Instruction * I, SmallVectorImpl< Use * > & Ops) const inline virtual
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
because the operands can be folded into a target instruction during instruction selection. After calling the function Ops contains the Uses to sink ordered by dominance (dominating users come first).
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 2372 of file TargetLowering.h.
shouldSplatInsEltVarIndex()
virtual bool llvm::TargetLoweringBase::shouldSplatInsEltVarIndex (EVT) const inline virtual
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
Reimplemented in llvm::X86TargetLowering.
Definition at line 599 of file TargetLowering.h.
shouldTransformSignedTruncationCheck()
virtual bool llvm::TargetLoweringBase::shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const inline virtual
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
Return false if there is no preference.
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 568 of file TargetLowering.h.
shouldUseStrictFP_TO_INT()
virtual bool llvm::TargetLoweringBase::shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const inline virtual
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
This may be true if the target throws exceptions for out of bounds conversions or has fast FP CMOV.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1860 of file TargetLowering.h.
Referenced by llvm::TargetLowering::expandFP_TO_UINT().
storeOfVectorConstantIsCheap()
virtual bool llvm::TargetLoweringBase::storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AddrSpace) const inline virtual
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
Reimplemented in llvm::X86TargetLowering, and llvm::AMDGPUTargetLowering.
Definition at line 437 of file TargetLowering.h.
supportsUnalignedAtomics()
bool llvm::TargetLoweringBase::supportsUnalignedAtomics () const inline
Whether the target supports unaligned atomic operations.
Definition at line 1660 of file TargetLowering.h.
useSoftFloat()
virtual bool llvm::TargetLoweringBase::useSoftFloat () const inline virtual
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, and llvm::X86TargetLowering.
Definition at line 237 of file TargetLowering.h.
Referenced by sinkCmpExpression().
useStackGuardXorFP()
virtual bool llvm::TargetLoweringBase::useStackGuardXorFP () const inline virtual
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
getIRStackGuard must return nullptr if this returns true.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1582 of file TargetLowering.h.
Referenced by llvm::SelectionDAGBuilder::visitSPDescriptorParent().
usesUnderscoreLongJmp()
bool llvm::TargetLoweringBase::usesUnderscoreLongJmp () const inline
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
Definition at line 1481 of file TargetLowering.h.
usesUnderscoreSetJmp()
bool llvm::TargetLoweringBase::usesUnderscoreSetJmp () const inline
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
Definition at line 1476 of file TargetLowering.h.
Member Data Documentation
EnableExtLdPromotion
bool llvm::TargetLoweringBase::EnableExtLdPromotion protected
See also
enableExtLdPromotion.
Definition at line 2857 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), enableExtLdPromotion(), TargetLoweringBase(), and llvm::X86TargetLowering::X86TargetLowering().
GatherAllAliasesMaxDepth
unsigned llvm::TargetLoweringBase::GatherAllAliasesMaxDepth protected
Depth that GatherAllAliases should should continue looking for chain dependencies when trying to find a more preferable chain.
As an approximation, this should be more than the number of consecutive stores expected to be merged.
Definition at line 2791 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), getGatherAllAliasesMaxDepth(), and TargetLoweringBase().
MaxGluedStoresPerMemcpy
unsigned llvm::TargetLoweringBase::MaxGluedStoresPerMemcpy = 0 protected
Specify max number of store instructions to glue in inlined memcpy.
When memcpy is inlined based on MaxStoresPerMemcpy, specify maximum number of store instructions to keep together. This helps in pairing and
Definition at line 2828 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), getMaxGluedStoresPerMemcpy(), and TargetLoweringBase().
MaxLoadsPerMemcmp
unsigned llvm::TargetLoweringBase::MaxLoadsPerMemcmp protected
Definition at line 2833 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), getMaxExpandSizeMemcmp(), llvm::PPCTargetLowering::PPCTargetLowering(), TargetLoweringBase(), and llvm::X86TargetLowering::X86TargetLowering().
MaxLoadsPerMemcmpOptSize
unsigned llvm::TargetLoweringBase::MaxLoadsPerMemcmpOptSize protected
Definition at line 2834 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), getMaxExpandSizeMemcmp(), llvm::PPCTargetLowering::PPCTargetLowering(), TargetLoweringBase(), and llvm::X86TargetLowering::X86TargetLowering().
MaxStoresPerMemcpy
unsigned llvm::TargetLoweringBase::MaxStoresPerMemcpy protected
Specify maximum bytes of store instructions per memcpy call.
When lowering @llvm.memcpy this field specifies the maximum number of store operations that may be substituted for a call to memcpy. Targets must set this value based on the cost threshold for that target. Targets should assume that the memcpy will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, storing 7 bytes on a 32-bit machine with 32-bit alignment would result in one 4-byte store, a one 2-byte store and one 1-byte store. This only applies to copying a constant array of constant size.
Definition at line 2820 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemcpy(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemcpyOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize protected
Maximum number of store operations that may be substituted for a call to memcpy, used for functions with OptSize attribute.
Definition at line 2832 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemcpy(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemmove
unsigned llvm::TargetLoweringBase::MaxStoresPerMemmove protected
Specify maximum bytes of store instructions per memmove call.
When lowering @llvm.memmove this field specifies the maximum number of store instructions that may be substituted for a call to memmove. Targets must set this value based on the cost threshold for that target. Targets should assume that the memmove will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, moving 9 bytes on a 32-bit machine with 8-bit alignment would result in nine 1-byte stores. This only applies to copying a constant array of constant size.
Definition at line 2846 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemmove(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemmoveOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize protected
Maximum number of store instructions that may be substituted for a call to memmove, used for functions with OptSize attribute.
Definition at line 2850 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemmove(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemset
unsigned llvm::TargetLoweringBase::MaxStoresPerMemset protected
Specify maximum number of store instructions per memset call.
When lowering @llvm.memset this field specifies the maximum number of store operations that may be substituted for the call to memset. Targets must set this value based on the cost threshold for that target. Targets should assume that the memset will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, storing 9 bytes on a 32-bit machine with 16-bit alignment would result in four 2-byte stores and one 1-byte store. This only applies to setting a constant array of a constant size.
Definition at line 2803 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemset(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemsetOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize protected
Maximum number of stores operations that may be substituted for the call to memset, used for functions with OptSize attribute.
Definition at line 2807 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::BPFTargetLowering::BPFTargetLowering(), getMaxStoresPerMemset(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::LanaiTargetLowering::LanaiTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
PredictableSelectIsExpensive
bool llvm::TargetLoweringBase::PredictableSelectIsExpensive protected
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
Definition at line 2854 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), isPredictableSelectExpensive(), TargetLoweringBase(), and llvm::X86TargetLowering::X86TargetLowering().
ValueTypeActions
ValueTypeActionImpl llvm::TargetLoweringBase::ValueTypeActions protected
Definition at line 2748 of file TargetLowering.h.
Referenced by computeRegisterProperties(), getTypeAction(), getValueTypeActions(), and llvm::X86TargetLowering::X86TargetLowering().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetLowering.h
lib/CodeGen/TargetLoweringBase.cpp