LLVM: llvm::TargetLibraryInfoWrapperPass Class Reference
llvm::TargetLibraryInfoWrapperPass Class Reference
#include "llvm/Analysis/TargetLibraryInfo.h"
Public Member Functions
TargetLibraryInfoWrapperPass ()
TargetLibraryInfoWrapperPass (const Triple &T)
TargetLibraryInfoWrapperPass (const TargetLibraryInfoImpl &TLI)
TargetLibraryInfo & getTLI ()
const TargetLibraryInfo & getTLI () const
Static Public Attributes
static char ID
Detailed Description
Definition at line 376 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfoWrapperPass() [1/3]
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass ()
Definition at line 1635 of file TargetLibraryInfo.cpp.
TargetLibraryInfoWrapperPass() [2/3]
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass (const Triple & T) explicit
Definition at line 1640 of file TargetLibraryInfo.cpp.
TargetLibraryInfoWrapperPass() [3/3]
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass (const TargetLibraryInfoImpl & TLI) explicit
Definition at line 1645 of file TargetLibraryInfo.cpp.
Member Function Documentation
getTLI() [1/2]
TargetLibraryInfo & llvm::TargetLibraryInfoWrapperPass::getTLI () inline
Definition at line 388 of file TargetLibraryInfo.h.
Referenced by llvm::createLegacyPMAAResults(), llvm::createLegacyPMBasicAAResult(), and llvm::getBestSimplifyQuery().
getTLI() [2/2]
const TargetLibraryInfo & llvm::TargetLibraryInfoWrapperPass::getTLI () const inline
Definition at line 389 of file TargetLibraryInfo.h.
Member Data Documentation
ID
char llvm::TargetLibraryInfoWrapperPass::ID static
Definition at line 383 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetLibraryInfo.h
lib/Analysis/TargetLibraryInfo.cpp