LLVM: llvm::BasicBlockEdge Class Reference
llvm::BasicBlockEdge Class Reference
#include "llvm/IR/Dominators.h"
Public Member Functions
BasicBlockEdge (const BasicBlock *Start_, const BasicBlock *End_)
BasicBlockEdge (const std::pair< BasicBlock *, BasicBlock * > &Pair)
BasicBlockEdge (const std::pair< const BasicBlock *, const BasicBlock * > &Pair)
const BasicBlock * getStart () const
const BasicBlock * getEnd () const
bool isSingleEdge () const
Check if this is the only edge between Start and End.
Detailed Description
Definition at line 76 of file Dominators.h.
Constructor & Destructor Documentation
BasicBlockEdge() [1/3]
llvm::BasicBlockEdge::BasicBlockEdge (const BasicBlock * Start_, const BasicBlock * End_) inline
Definition at line 81 of file Dominators.h.
BasicBlockEdge() [2/3]
llvm::BasicBlockEdge::BasicBlockEdge (const std::pair< BasicBlock *, BasicBlock * > & Pair) inline
Definition at line 84 of file Dominators.h.
BasicBlockEdge() [3/3]
llvm::BasicBlockEdge::BasicBlockEdge (const std::pair< const BasicBlock *, const BasicBlock * > & Pair) inline
Definition at line 87 of file Dominators.h.
Member Function Documentation
getEnd()
const BasicBlock * llvm::BasicBlockEdge::getEnd () const inline
Definition at line 94 of file Dominators.h.
Referenced by llvm::DominatorTree::dominates(), llvm::DenseMapInfo< BasicBlockEdge >::getHashValue(), and llvm::DenseMapInfo< BasicBlockEdge >::isEqual().
getStart()
const BasicBlock * llvm::BasicBlockEdge::getStart () const inline
Definition at line 90 of file Dominators.h.
Referenced by llvm::DominatorTree::dominates(), llvm::DenseMapInfo< BasicBlockEdge >::getHashValue(), and llvm::DenseMapInfo< BasicBlockEdge >::isEqual().
isSingleEdge()
bool BasicBlockEdge::isSingleEdge () const
Check if this is the only edge between Start and End.
Definition at line 42 of file Dominators.cpp.
References assert(), llvm::Instruction::getNumSuccessors(), llvm::Instruction::getSuccessor(), and llvm::BasicBlock::getTerminator().
Referenced by BrPHIToSelect(), isKnownNonNullFromDominatingCondition(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), and llvm::isOverflowIntrinsicNoWrap().
The documentation for this class was generated from the following files:
include/llvm/IR/Dominators.h
lib/IR/Dominators.cpp