LLVM: llvm::AddressSanitizerPass Class Reference
llvm::AddressSanitizerPass Class Reference
Public interface to the address sanitizer pass for instrumenting code to check for various memory errors at runtime.
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
Public Member Functions
AddressSanitizerPass (bool CompileKernel=false, bool Recover=false, bool UseAfterScope=false)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AddressSanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Public interface to the address sanitizer pass for instrumenting code to check for various memory errors at runtime.
The sanitizer itself is a function pass that works by inserting various calls to the ASan runtime library functions. The runtime library essentially replaces malloc() and free() with custom implementations that allow regions surrounding requested memory to be checked for invalid accesses.
Definition at line 99 of file AddressSanitizer.h.
Constructor & Destructor Documentation
AddressSanitizerPass()
AddressSanitizerPass::AddressSanitizerPass (bool CompileKernel = false, bool Recover = false, bool UseAfterScope = false) explicit
Definition at line 1147 of file AddressSanitizer.cpp.
Member Function Documentation
run()
PreservedAnalyses AddressSanitizerPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1152 of file AddressSanitizer.cpp.
References AddressSanitizer, llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::none(), and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/AddressSanitizer.h
lib/Transforms/Instrumentation/AddressSanitizer.cpp