LLVM: llvm::VPlanHCFGTransforms Class Reference
llvm::VPlanHCFGTransforms Class Reference
#include "Transforms/Vectorize/VPlanHCFGTransforms.h"
Static Public Member Functions
static void VPInstructionsToVPRecipes (VPlanPtr &Plan, LoopVectorizationLegality::InductionList *Inductions, SmallPtrSetImpl< Instruction * > &DeadInstructions)
Replaces the VPInstructions in Plan with corresponding widen recipes.
Detailed Description
Definition at line 22 of file VPlanHCFGTransforms.h.
Member Function Documentation
VPInstructionsToVPRecipes()
void VPlanHCFGTransforms::VPInstructionsToVPRecipes (VPlanPtr & Plan, LoopVectorizationLegality::InductionList * Inductions, SmallPtrSetImpl< Instruction * > & DeadInstructions) static
Replaces the VPInstructions in Plan with corresponding widen recipes.
Definition at line 19 of file VPlanHCFGTransforms.cpp.
References llvm::VPBasicBlock::begin(), llvm::VPBasicBlock::end(), llvm::VPRecipeBase::eraseFromParent(), llvm::VPBlockBase::getCondBit(), llvm::VPRegionBlock::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::InductionDescriptor::getKind(), llvm::VPValue::getUnderlyingValue(), I, llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::VPRecipeBase::insertBefore(), and llvm::VPBlockBase::setCondBit().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanHCFGTransforms.h
lib/Transforms/Vectorize/VPlanHCFGTransforms.cpp