LLVM: llvm::PBQP::ValuePool< ValueT > Class Template Reference
llvm::PBQP::ValuePool< ValueT > Class Template Reference
#include "llvm/CodeGen/PBQP/CostAllocator.h"
Public Types
using PoolRef = std::shared_ptr< const ValueT >
Public Member Functions
template<typename ValueKeyT >
PoolRef getValue (ValueKeyT ValueKey)
Detailed Description
template<typename ValueT>
class llvm::PBQP::ValuePool< ValueT >
Definition at line 28 of file CostAllocator.h.
Member Typedef Documentation
PoolRef
template<typename ValueT > using llvm::PBQP::ValuePool< ValueT >::PoolRef = std::shared_ptr<const ValueT>
Definition at line 30 of file CostAllocator.h.
Member Function Documentation
getValue()
template<typename ValueT > template<typename ValueKeyT > PoolRef llvm::PBQP::ValuePool< ValueT >::getValue (ValueKeyT ValueKey) inline
Definition at line 95 of file CostAllocator.h.
References I, and P.
Referenced by llvm::PBQP::RegAlloc::GraphMetadata::getAllowedRegs(), llvm::PBQP::PoolCostAllocator< VectorT, MatrixT >::getMatrix(), and llvm::PBQP::PoolCostAllocator< VectorT, MatrixT >::getVector().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/PBQP/CostAllocator.h