LLVM: llvm::raw_ostream Class Reference
llvm::raw_ostream Class Reference abstract
This class implements an extremely fast bulk output stream that can only output to a stream.
#include "llvm/Support/raw_ostream.h"
Public Types
enum Colors {
BLACK = 0 , RED , GREEN , YELLOW ,
BLUE , MAGENTA , CYAN , WHITE ,
SAVEDCOLOR
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Public Member Functions
raw_ostream (bool unbuffered=false)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '\t', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the foreground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
Protected Member Functions
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
This class implements an extremely fast bulk output stream that can only output to a stream.
It does not support seeking, reopening, rewinding, line buffered disciplines etc. It is a simple buffer that outputs a chunk at a time.
Definition at line 45 of file raw_ostream.h.
Member Typedef Documentation
uuid_t
using llvm::raw_ostream::uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Definition at line 218 of file raw_ostream.h.
Member Enumeration Documentation
Colors
enum llvm::raw_ostream::Colors
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
SAVEDCOLOR
Definition at line 75 of file raw_ostream.h.
Constructor & Destructor Documentation
raw_ostream() [1/2]
llvm::raw_ostream::raw_ostream (bool unbuffered = false) inline explicit
Definition at line 87 of file raw_ostream.h.
raw_ostream() [2/2]
llvm::raw_ostream::raw_ostream (const raw_ostream &) delete
~raw_ostream()
raw_ostream::~raw_ostream () virtual
Definition at line 68 of file raw_ostream.cpp.
References assert().
Member Function Documentation
changeColor()
virtual raw_ostream & llvm::raw_ostream::changeColor (enum Colors Color, bool Bold = false, bool BG = false) inline virtual
Changes the foreground color of text that will be output from this point forward.
Parameters
Color ANSI color to use, the special SAVEDCOLOR can be used to change only the bold attribute, and keep colors untouched
Bold bold/brighter text, default false
BG if true change the background, default: change foreground
Returns
itself so it can be used within << invocations
Reimplemented in llvm::formatted_raw_ostream, and llvm::raw_fd_ostream.
Definition at line 256 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::changeColor(), llvm::WithColor::changeColor(), and llvm::WithColor::WithColor().
flush()
void llvm::raw_ostream::flush () inline
Definition at line 141 of file raw_ostream.h.
Referenced by llvm::TarWriter::append(), llvm::raw_fd_ostream::changeColor(), llvm::raw_fd_ostream::close(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::ImportedFunctionsInliningStatistics::dump(), llvm::pdb::PDBSymbol::dumpChildStats(), llvm::pdb::PDBSymbol::dumpProperties(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::json::OStream::flush(), llvm::ScopedPrinter::flush(), llvm::Attribute::getAsString(), getBranchCondString(), getDebugLocString(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::LazyCallGraph::SCC::getName(), llvm::LazyCallGraph::RefSCC::getName(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree(), LLVMGetDiagInfoDescription(), LLVMParseIRInContext(), LLVMPrintModuleToString(), LLVMPrintTypeToString(), LLVMPrintValueToString(), llvm::DiagnosticInfoUnsupported::print(), PrintCurStackTrace(), llvm::opt::OptTable::PrintHelp(), ReportError(), reportOpenError(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::raw_fd_ostream::seek(), SetBufferSize(), llvm::setProfMetadata(), SetUnbuffered(), llvm::raw_sha1_ostream::sha1(), llvm::raw_string_ostream::str(), llvm::formatv_object_base::str(), llvm::sys::StrError(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty(), writeToResolutionFile(), llvm::circular_raw_ostream::~circular_raw_ostream(), llvm::formatted_raw_ostream::~formatted_raw_ostream(), llvm::raw_fd_ostream::~raw_fd_ostream(), llvm::raw_null_ostream::~raw_null_ostream(), llvm::raw_os_ostream::~raw_os_ostream(), and llvm::raw_string_ostream::~raw_string_ostream().
GetBufferSize()
size_t llvm::raw_ostream::GetBufferSize () const inline
Definition at line 115 of file raw_ostream.h.
References preferred_buffer_size().
getBufferStart()
const char * llvm::raw_ostream::getBufferStart () const inline protected
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Definition at line 317 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::PadToColumn().
GetNumBytesInBuffer()
size_t llvm::raw_ostream::GetNumBytesInBuffer () const inline
Definition at line 133 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::PadToColumn(), and tell().
has_colors()
virtual bool llvm::raw_ostream::has_colors () const inline virtual
This function determines if this stream is displayed and supports colors.
Reimplemented in llvm::raw_fd_ostream.
Definition at line 278 of file raw_ostream.h.
References is_displayed().
Referenced by llvm::WithColor::colorsEnabled().
indent()
raw_ostream & raw_ostream::indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
Definition at line 477 of file raw_ostream.cpp.
Referenced by llvm::DWARFDebugLoc::LocationList::dump(), llvm::dwarf::CFIProgram::dump(), llvm::pdb::IPDBSourceFile::dump(), llvm::DWARFDebugLoclists::LocationList::dump(), llvm::DWARFDie::dump(), dumpAttribute(), llvm::LPPassManager::dumpPassStructure(), llvm::RGPassManager::dumpPassStructure(), llvm::FPPassManager::dumpPassStructure(), dumpRanges(), llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), llvm::detail::PadAdapter< T >::format(), operator<<(), llvm::formatted_raw_ostream::PadToColumn(), llvm::DWARFDebugLine::LineTable::parse(), llvm::slpvectorizer::BoUpSLP::VLOperands::print(), llvm::RegionBase< Tr >::print(), llvm::LoopAccessLegacyAnalysis::print(), llvm::PredicatedScalarEvolution::print(), llvm::MemoryDepChecker::Dependence::print(), llvm::RuntimePointerChecking::print(), llvm::LoopAccessInfo::print(), llvm::SCEVEqualPredicate::print(), llvm::SCEVWrapPredicate::print(), llvm::LoopBase< BlockT, LoopT >::print(), llvm::RuntimePointerChecking::printChecks(), llvm::PrintDomTree(), llvm::cl::generic_parser_base::printGenericOptionDiff(), PrintHelpOptionList(), llvm::cl::Option::printHelpStr(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::cl::basic_parser_impl::printOptionName(), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), llvm::TargetRegistry::printRegisteredTargetsForVersion(), and llvm::LoopAccessInfoPrinterPass::run().
is_displayed()
virtual bool llvm::raw_ostream::is_displayed () const inline virtual
This function determines if this stream is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Reimplemented in llvm::formatted_raw_ostream, and llvm::raw_fd_ostream.
Definition at line 275 of file raw_ostream.h.
Referenced by llvm::CheckBitcodeOutputToConsole(), has_colors(), and llvm::formatted_raw_ostream::is_displayed().
operator<<() [1/20]
raw_ostream & llvm::raw_ostream::operator<< (char C) inline
Definition at line 146 of file raw_ostream.h.
References write().
Referenced by operator<<().
operator<<() [2/20]
raw_ostream & llvm::raw_ostream::operator<< (const char * Str) inline
Definition at line 182 of file raw_ostream.h.
References operator<<().
operator<<() [3/20]
raw_ostream & raw_ostream::operator<< (const format_object_base & Fmt)
Definition at line 286 of file raw_ostream.cpp.
References assert(), llvm::format_object_base::print(), and write().
operator<<() [4/20]
raw_ostream & raw_ostream::operator<< (const FormattedBytes & FB)
Definition at line 383 of file raw_ostream.cpp.
References llvm::alignTo(), assert(), I, indent(), llvm::Log2_64_Ceil(), llvm::Lower, llvm::Upper, and llvm::write_hex().
operator<<() [5/20]
raw_ostream & raw_ostream::operator<< (const FormattedNumber & FN)
Definition at line 360 of file raw_ostream.cpp.
References indent(), llvm::Integer, llvm::Lower, llvm::PrefixLower, llvm::PrefixUpper, llvm::Upper, llvm::write_hex(), and llvm::write_integer().
operator<<() [6/20]
raw_ostream & raw_ostream::operator<< (const FormattedString & FS)
Definition at line 332 of file raw_ostream.cpp.
References indent(), llvm::FormattedString::JustifyCenter, llvm::FormattedString::JustifyLeft, llvm::FormattedString::JustifyNone, llvm::FormattedString::JustifyRight, llvm_unreachable, and operator<<().
operator<<() [7/20]
raw_ostream & raw_ostream::operator<< (const formatv_object_base & Obj)
Definition at line 326 of file raw_ostream.cpp.
References llvm::formatv_object_base::format().
operator<<() [8/20]
raw_ostream & llvm::raw_ostream::operator<< (const SmallVectorImpl< char > & Str) inline
Definition at line 194 of file raw_ostream.h.
References write().
operator<<() [9/20]
raw_ostream & llvm::raw_ostream::operator<< (const std::string & Str) inline
Definition at line 189 of file raw_ostream.h.
References write().
operator<<() [10/20]
raw_ostream & raw_ostream::operator<< (const void * P)
Definition at line 186 of file raw_ostream.cpp.
References P, llvm::PrefixLower, and llvm::write_hex().
operator<<() [11/20]
raw_ostream & raw_ostream::operator<< (double N)
Definition at line 191 of file raw_ostream.cpp.
References llvm::Exponent, N, and llvm::write_double().
operator<<() [12/20]
raw_ostream & llvm::raw_ostream::operator<< (int N) inline
Definition at line 208 of file raw_ostream.h.
References N.
operator<<() [13/20]
raw_ostream & raw_ostream::operator<< (long long N)
Definition at line 126 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [14/20]
raw_ostream & raw_ostream::operator<< (long N)
Definition at line 116 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [15/20]
raw_ostream & llvm::raw_ostream::operator<< (signed char C) inline
Definition at line 160 of file raw_ostream.h.
References write().
operator<<() [16/20]
raw_ostream & llvm::raw_ostream::operator<< (StringRef Str) inline
Definition at line 167 of file raw_ostream.h.
References write().
operator<<() [17/20]
raw_ostream & llvm::raw_ostream::operator<< (unsigned char C) inline
Definition at line 153 of file raw_ostream.h.
References write().
operator<<() [18/20]
raw_ostream & llvm::raw_ostream::operator<< (unsigned int N) inline
Definition at line 204 of file raw_ostream.h.
References N.
operator<<() [19/20]
raw_ostream & raw_ostream::operator<< (unsigned long long N)
Definition at line 121 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [20/20]
raw_ostream & raw_ostream::operator<< (unsigned long N)
Definition at line 111 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator=()
void llvm::raw_ostream::operator= (const raw_ostream &) delete
preferred_buffer_size()
size_t raw_ostream::preferred_buffer_size () const protected virtual
Return an efficient buffer size for the underlying output mechanism.
Definition at line 78 of file raw_ostream.cpp.
Referenced by GetBufferSize(), and SetBuffered().
resetColor()
virtual raw_ostream & llvm::raw_ostream::resetColor () inline virtual
Resets the colors to terminal defaults.
Call this when you are done outputting colored text, or before program exit.
Reimplemented in llvm::formatted_raw_ostream, and llvm::raw_fd_ostream.
Definition at line 267 of file raw_ostream.h.
Referenced by llvm::WithColor::resetColor(), and llvm::formatted_raw_ostream::resetColor().
reverseColor()
virtual raw_ostream & llvm::raw_ostream::reverseColor () inline virtual
Reverses the foreground and background colors.
Reimplemented in llvm::formatted_raw_ostream, and llvm::raw_fd_ostream.
Definition at line 270 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::reverseColor().
SetBuffer()
void llvm::raw_ostream::SetBuffer (char * BufferStart, size_t Size) inline protected
Use the provided buffer as the raw_ostream buffer.
This is intended for use only by subclasses which can arrange for the output to go directly into the desired output buffer, instead of being copied on each flush.
Definition at line 308 of file raw_ostream.h.
SetBuffered()
void raw_ostream::SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
Definition at line 83 of file raw_ostream.cpp.
References preferred_buffer_size(), SetBufferSize(), and SetUnbuffered().
Referenced by write().
SetBufferSize()
void llvm::raw_ostream::SetBufferSize (size_t Size) inline
Set the stream to be buffered, using the specified buffer size.
Definition at line 110 of file raw_ostream.h.
References flush().
Referenced by SetBuffered().
SetUnbuffered()
void llvm::raw_ostream::SetUnbuffered () inline
Set the stream to be unbuffered.
When unbuffered, the stream will flush after every write. This routine will also flush the buffer immediately when the stream is being set to unbuffered.
Definition at line 128 of file raw_ostream.h.
References flush().
Referenced by llvm::raw_svector_ostream::raw_svector_ostream(), and SetBuffered().
tell()
uint64_t llvm::raw_ostream::tell () const inline
tell - Return the current offset with the file.
Definition at line 99 of file raw_ostream.h.
References GetNumBytesInBuffer().
Referenced by llvm::TarWriter::append(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), pad(), and llvm::raw_pwrite_stream::pwrite().
write() [1/2]
raw_ostream & raw_ostream::write (const char * Ptr, size_t Size)
Definition at line 223 of file raw_ostream.cpp.
References assert(), LLVM_UNLIKELY, SetBuffered(), and write().
write() [2/2]
raw_ostream & raw_ostream::write (unsigned char C)
Definition at line 203 of file raw_ostream.cpp.
References LLVM_UNLIKELY, SetBuffered(), and write().
Referenced by llvm::raw_fd_ostream::changeColor(), llvm::circular_raw_ostream::flushBufferWithBanner(), operator<<(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::support::endian::write(), write(), llvm::write_hex(), write_padding(), write_unsigned_impl(), and writeWithCommas().
write_escaped()
raw_ostream & raw_ostream::write_escaped (StringRef Str, bool UseHexEscapes = false)
Output Str, turning '\', '\t', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
Definition at line 146 of file raw_ostream.cpp.
Referenced by llvm::DWARFContext::dump(), llvm::DWARFFormValue::dump(), and llvm::FileCheckUndefVarError::log().
write_hex()
raw_ostream & raw_ostream::write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
Definition at line 131 of file raw_ostream.cpp.
References llvm::Lower, N, and llvm::write_hex().
Referenced by dumpDataAux().
write_uuid()
raw_ostream & raw_ostream::write_uuid (const uuid_t UUID)
Definition at line 136 of file raw_ostream.cpp.
References llvm::format(), and Idx.
Referenced by dumpUUID().
write_zeros()
raw_ostream & raw_ostream::write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
Definition at line 482 of file raw_ostream.cpp.
The documentation for this class was generated from the following files:
include/llvm/Support/raw_ostream.h
lib/Support/raw_ostream.cpp