LLVM: llvm::AMDGPUSymbolizer Class Reference
llvm::AMDGPUSymbolizer Class Reference
#include "Target/AMDGPU/Disassembler/AMDGPUDisassembler.h"
Public Member Functions
AMDGPUSymbolizer (MCContext &Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo, void *disInfo)
bool tryAddingSymbolicOperand (MCInst &Inst, raw_ostream &cStream, int64_t Value, uint64_t Address, bool IsBranch, uint64_t Offset, uint64_t InstSize) override
Try to add a symbolic operand instead of Value to the MCInst.
void tryAddingPcLoadReferenceComment (raw_ostream &cStream, int64_t Value, uint64_t Address) override
Try to add a comment on the PC-relative load.
Public Member Functions inherited from llvm::MCSymbolizer
MCSymbolizer (MCContext &Ctx, std::unique_ptr< MCRelocationInfo > RelInfo)
Construct an MCSymbolizer, taking ownership of RelInfo.
MCSymbolizer (const MCSymbolizer &)=delete
MCSymbolizer & operator= (const MCSymbolizer &)=delete
virtual ~MCSymbolizer ()
virtual bool tryAddingSymbolicOperand (MCInst &Inst, raw_ostream &cStream, int64_t Value, uint64_t Address, bool IsBranch, uint64_t Offset, uint64_t InstSize)=0
Try to add a symbolic operand instead of Value to the MCInst.
virtual void tryAddingPcLoadReferenceComment (raw_ostream &cStream, int64_t Value, uint64_t Address)=0
Try to add a comment on the PC-relative load.
Additional Inherited Members
Protected Attributes inherited from llvm::MCSymbolizer
MCContext & Ctx
std::unique_ptr< MCRelocationInfo > RelInfo
Detailed Description
Definition at line 150 of file AMDGPUDisassembler.h.
Constructor & Destructor Documentation
AMDGPUSymbolizer()
llvm::AMDGPUSymbolizer::AMDGPUSymbolizer (MCContext & Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo, void * disInfo) inline
Definition at line 155 of file AMDGPUDisassembler.h.
Member Function Documentation
tryAddingPcLoadReferenceComment()
void AMDGPUSymbolizer::tryAddingPcLoadReferenceComment (raw_ostream & cStream, int64_t Value, uint64_t Address) override virtual
Try to add a comment on the PC-relative load.
For instance, in Mach-O, this is used to add annotations to instructions that use C string literals, as found in __cstring.
Implements llvm::MCSymbolizer.
Definition at line 1238 of file AMDGPUDisassembler.cpp.
References llvm_unreachable.
tryAddingSymbolicOperand()
bool AMDGPUSymbolizer::tryAddingSymbolicOperand (MCInst & Inst, raw_ostream & cStream, int64_t Value, uint64_t Address, bool IsBranch, uint64_t Offset, uint64_t InstSize) override virtual
Try to add a symbolic operand instead of Value to the MCInst.
Instead of having a difficult to read immediate, a symbolic operand would represent this immediate in a more understandable way, for instance as a symbol or an offset from a symbol. Relocations can also be used to enrich the symbolic expression.
Parameters
Inst - The MCInst where to insert the symbolic operand.
cStream - Stream to print comments and annotations on.
Value - Operand value, pc-adjusted by the caller if necessary.
Address - Load address of the instruction.
IsBranch - Is the instruction a branch?
Offset - Byte offset of the operand inside the inst.
InstSize - Size of the instruction in bytes.
Returns
Whether a symbolic operand was added.
Implements llvm::MCSymbolizer.
Definition at line 1209 of file AMDGPUDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::LiveRangeEdit::create(), llvm::MCOperand::createExpr(), llvm::MCSymbolizer::Ctx, and llvm::MCContext::getOrCreateSymbol().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.h
lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp