LLVM: llvm::PredicateInfoPrinterLegacyPass Class Reference
llvm::PredicateInfoPrinterLegacyPass Class Reference
#include "llvm/Transforms/Utils/PredicateInfo.h"
Public Member Functions
PredicateInfoPrinterLegacyPass ()
bool runOnFunction (Function &) override
void getAnalysisUsage (AnalysisUsage &AU) const override
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 272 of file PredicateInfo.h.
Constructor & Destructor Documentation
PredicateInfoPrinterLegacyPass()
llvm::PredicateInfoPrinterLegacyPass::PredicateInfoPrinterLegacyPass ()
Definition at line 746 of file PredicateInfo.cpp.
Member Function Documentation
getAnalysisUsage()
void llvm::PredicateInfoPrinterLegacyPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 752 of file PredicateInfo.cpp.
runOnFunction()
bool llvm::PredicateInfoPrinterLegacyPass::runOnFunction (Function & F) override
Definition at line 772 of file PredicateInfo.cpp.
References llvm::dbgs(), F, llvm::replaceCreatedSSACopys(), and VerifyPredicateInfo().
Member Data Documentation
ID
char llvm::PredicateInfoPrinterLegacyPass::ID = 0 static
Definition at line 276 of file PredicateInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/PredicateInfo.h
lib/Transforms/Utils/PredicateInfo.cpp