LLVM: llvm::VPRecipeBuilder Class Reference
llvm::VPRecipeBuilder Class Reference
Helper class to create VPRecipies from IR instructions.
#include "Transforms/Vectorize/VPRecipeBuilder.h"
Public Member Functions
VPValue * createBlockInMask (BasicBlock *BB, VPlanPtr &Plan)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True.
VPValue * createEdgeMask (BasicBlock *Src, BasicBlock *Dst, VPlanPtr &Plan)
A helper function that computes the predicate of the edge between SRC and DST.
VPInterleaveRecipe * tryToInterleaveMemory (Instruction *I, VFRange &Range, VPlanPtr &Plan)
Check if \I belongs to an Interleave Group within the given VF Range,.
VPWidenMemoryInstructionRecipe * tryToWidenMemory (Instruction *I, VFRange &Range, VPlanPtr &Plan)
Check if \I is a memory instruction to be widened for Range.Start and potentially masked.
VPWidenIntOrFpInductionRecipe * tryToOptimizeInduction (Instruction *I, VFRange &Range)
Check if an induction recipe should be constructed for \I within the given VF Range.
VPBlendRecipe * tryToBlend (Instruction *I, VPlanPtr &Plan)
Handle non-loop phi nodes.
bool tryToWiden (Instruction *I, VPBasicBlock *VPBB, VFRange &Range)
Check if I can be widened within the given VF Range.
VPRegionBlock * createReplicateRegion (Instruction *I, VPRecipeBase *PredRecipe, VPlanPtr &Plan)
Create a replicating region for instruction I that requires predication.
VPRecipeBuilder (Loop *OrigLoop, const TargetLibraryInfo *TLI, LoopVectorizationLegality *Legal, LoopVectorizationCostModel &CM, VPBuilder &Builder)
bool tryToCreateRecipe (Instruction *Instr, VFRange &Range, VPlanPtr &Plan, VPBasicBlock *VPBB)
Check if a recipe can be create for I withing the given VF Range.
VPBasicBlock * handleReplication (Instruction *I, VFRange &Range, VPBasicBlock *VPBB, DenseMap< Instruction *, VPReplicateRecipe * > &PredInst2Recipe, VPlanPtr &Plan)
Build a VPReplicationRecipe for I and enclose it within a Region if it is predicated.
Detailed Description
Helper class to create VPRecipies from IR instructions.
Definition at line 25 of file VPRecipeBuilder.h.
Constructor & Destructor Documentation
VPRecipeBuilder()
llvm::VPRecipeBuilder::VPRecipeBuilder (Loop * OrigLoop, const TargetLibraryInfo * TLI, LoopVectorizationLegality * Legal, LoopVectorizationCostModel & CM, VPBuilder & Builder) inline
Definition at line 103 of file VPRecipeBuilder.h.
Member Function Documentation
createBlockInMask()
VPValue * VPRecipeBuilder::createBlockInMask (BasicBlock * BB, VPlanPtr & Plan)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True.
It returns the entry mask for the block BB.
Definition at line 6452 of file LoopVectorize.cpp.
References assert(), llvm::LoopVectorizationCostModel::blockNeedsPredication(), llvm::LoopBase< BlockT, LoopT >::contains(), createEdgeMask(), llvm::VPBuilder::createNaryOp(), llvm::VPBuilder::createOr(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getPrimaryInduction(), llvm::VPInstruction::ICmpULE, and llvm::predecessors().
Referenced by createEdgeMask(), createReplicateRegion(), tryToInterleaveMemory(), and tryToWidenMemory().
createEdgeMask()
VPValue * VPRecipeBuilder::createEdgeMask (BasicBlock * Src, BasicBlock * Dst, VPlanPtr & Plan)
A helper function that computes the predicate of the edge between SRC and DST.
Definition at line 6421 of file LoopVectorize.cpp.
References assert(), llvm::VPBuilder::createAnd(), createBlockInMask(), llvm::VPBuilder::createNot(), llvm::BranchInst::getCondition(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::BranchInst::isConditional(), and llvm::predecessors().
Referenced by createBlockInMask(), and tryToBlend().
createReplicateRegion()
VPRegionBlock * VPRecipeBuilder::createReplicateRegion (Instruction * I, VPRecipeBase * PredRecipe, VPlanPtr & Plan)
Create a replicating region for instruction I that requires predication.
PredRecipe is a VPReplicateRecipe holding I.
Definition at line 6757 of file LoopVectorize.cpp.
References assert(), llvm::VPBlockUtils::connectBlocks(), createBlockInMask(), llvm::Instruction::getOpcodeName(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::VPBlockUtils::insertTwoBlocksAfter(), and llvm::Type::isVoidTy().
Referenced by handleReplication().
handleReplication()
VPBasicBlock * VPRecipeBuilder::handleReplication (Instruction * I, VFRange & Range, VPBasicBlock * VPBB, DenseMap< Instruction *, VPReplicateRecipe * > & PredInst2Recipe, VPlanPtr & Plan)
Build a VPReplicationRecipe for I and enclose it within a Region if it is predicated.
Returns
VPBB augmented with this new recipe if I is not predicated, otherwise
a new VPBasicBlock that succeeds the new Region. Update the packing decision of predicated instructions if they feed I. Range.End may be decreased to ensure same recipe behavior from Range.Start to Range.End.
Definition at line 6718 of file LoopVectorize.cpp.
References llvm::VPBasicBlock::appendRecipe(), assert(), createReplicateRegion(), llvm::dbgs(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::VPBlockBase::getSuccessors(), I, llvm::VPBlockUtils::insertBlockAfter(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), and LLVM_DEBUG.
tryToBlend()
VPBlendRecipe * VPRecipeBuilder::tryToBlend (Instruction * I, VPlanPtr & Plan)
Handle non-loop phi nodes.
Currently all such phi nodes are turned into a sequence of select instructions as the vectorizer currently performs full if-conversion.
Definition at line 6588 of file LoopVectorize.cpp.
References assert(), createEdgeMask(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), and I.
Referenced by tryToCreateRecipe().
tryToCreateRecipe()
bool VPRecipeBuilder::tryToCreateRecipe (Instruction * Instr, VFRange & Range, VPlanPtr & Plan, VPBasicBlock * VPBB)
Check if a recipe can be create for I withing the given VF Range.
If a recipe can be created, it adds it to VPBB.
Definition at line 6785 of file LoopVectorize.cpp.
References llvm::VPBasicBlock::appendRecipe(), tryToBlend(), tryToInterleaveMemory(), tryToOptimizeInduction(), tryToWiden(), and tryToWidenMemory().
tryToInterleaveMemory()
VPInterleaveRecipe * VPRecipeBuilder::tryToInterleaveMemory (Instruction * I, VFRange & Range, VPlanPtr & Plan)
Check if \I belongs to an Interleave Group within the given VF Range,.
Returns
true in the first returned value if so and false otherwise. Build a new VPInterleaveGroup Recipe if \I is the primary member of an IG for Range.Start, and provide it as the second returned value. Note that if \I is an adjunct member of an IG for Range.Start, the
value is <true, nullptr>, as it is handled by another recipe. Range.End may be decreased to ensure same decision from Range.Start to Range.End.
Definition at line 6493 of file LoopVectorize.cpp.
References assert(), llvm::LoopVectorizationCostModel::CM_Interleave, createBlockInMask(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::LoopVectorizationCostModel::getInterleavedAccessGroup(), llvm::LoopVectorizationCostModel::getWideningDecision(), I, and llvm::LoopVectorizationLegality::isMaskRequired().
Referenced by tryToCreateRecipe().
tryToOptimizeInduction()
VPWidenIntOrFpInductionRecipe * VPRecipeBuilder::tryToOptimizeInduction (Instruction * I, VFRange & Range)
Check if an induction recipe should be constructed for \I within the given VF Range.
If so build and return it. If not, return null. Range.End may be decreased to ensure same decision from Range.Start to Range.End.
Definition at line 6556 of file LoopVectorize.cpp.
References llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::InductionDescriptor::getKind(), I, llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, and llvm::LoopVectorizationCostModel::isOptimizableIVTruncate().
Referenced by tryToCreateRecipe().
tryToWiden()
bool VPRecipeBuilder::tryToWiden (Instruction * I, VPBasicBlock * VPBB, VFRange & Range)
Check if I can be widened within the given VF Range.
If I can be widened for Range.Start, check if the last recipe of VPBB can be extended to include I or else build a new VPWidenRecipe for it and append it to VPBB. Return true if I can be widened for Range.Start, false otherwise. Range.End may be decreased to ensure same decision from Range.Start to Range.End.
Definition at line 6612 of file LoopVectorize.cpp.
References llvm::AtomicRMWInst::And, llvm::VPWidenRecipe::appendInstruction(), llvm::VPBasicBlock::appendRecipe(), assert(), llvm::VPBasicBlock::back(), llvm::LazyCallGraph::Edge::Call, llvm::LoopVectorizationCostModel::CM_Scalarize, llvm::VPBasicBlock::empty(), llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::getVectorIntrinsicIDForCall(), llvm::LoopVectorizationCostModel::getWideningDecision(), I, llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), llvm::AtomicRMWInst::Or, llvm::PtrToIntOperator::PtrToInt, llvm::AtomicRMWInst::Sub, and llvm::AtomicRMWInst::Xor.
Referenced by tryToCreateRecipe().
tryToWidenMemory()
VPWidenMemoryInstructionRecipe * VPRecipeBuilder::tryToWidenMemory (Instruction * I, VFRange & Range, VPlanPtr & Plan)
Check if \I is a memory instruction to be widened for Range.Start and potentially masked.
Such instructions are handled by a recipe that takes an additional VPInstruction for the mask.
Definition at line 6525 of file LoopVectorize.cpp.
References assert(), llvm::LoopVectorizationCostModel::CM_Interleave, llvm::LoopVectorizationCostModel::CM_Scalarize, llvm::LoopVectorizationCostModel::CM_Unknown, createBlockInMask(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::LoopVectorizationCostModel::getWideningDecision(), I, llvm::LoopVectorizationLegality::isMaskRequired(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), and llvm::LoopVectorizationCostModel::isScalarAfterVectorization().
Referenced by tryToCreateRecipe().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPRecipeBuilder.h
lib/Transforms/Vectorize/LoopVectorize.cpp