LLVM: llvm::SCEVAddExpr Class Reference
llvm::SCEVAddExpr Class Reference
This node represents an addition of some number of SCEVs.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
Type * getType () const
Public Member Functions inherited from llvm::SCEVCommutativeExpr
void setNoWrapFlags (NoWrapFlags Flags)
Set flags for a non-recurrence without clearing previously set flags.
Public Member Functions inherited from llvm::SCEVNAryExpr
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
Type * getType () const
NoWrapFlags getNoWrapFlags (NoWrapFlags Mask=NoWrapMask) const
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
bool hasNoSelfWrap () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy, unsigned short ExpressionSize)
SCEV (const SCEV &)=delete
SCEV & operator= (const SCEV &)=delete
unsigned getSCEVType () const
Type * getType () const
Return the LLVM type of this SCEV expression.
bool isZero () const
Return true if the expression is a constant zero.
bool isOne () const
Return true if the expression is a constant one.
bool isAllOnesValue () const
Return true if the expression is a constant all-ones value.
bool isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
unsigned short getExpressionSize () const
void print (raw_ostream &OS) const
Print out the internal representation of this scalar to the specified stream.
void dump () const
This method is used for debugging.
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::SCEVCommutativeExpr
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::SCEVNAryExpr
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Public Types inherited from llvm::SCEVNAryExpr
using op_iterator = const SCEV *const *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) - 1
}
NoWrapFlags are bitfield indices into SubclassData.
Protected Member Functions inherited from llvm::SCEVCommutativeExpr
SCEVCommutativeExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Member Functions inherited from llvm::SCEVNAryExpr
SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Attributes inherited from llvm::SCEVNAryExpr
const SCEV *const * Operands
size_t NumOperands
Protected Attributes inherited from llvm::SCEV
const unsigned short ExpressionSize
unsigned short SubclassData = 0
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Detailed Description
This node represents an addition of some number of SCEVs.
Definition at line 222 of file ScalarEvolutionExpressions.h.
Member Function Documentation
classof()
static bool llvm::SCEVAddExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 238 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scAddExpr.
getType()
Type * llvm::SCEVAddExpr::getType () const inline
Definition at line 230 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), and llvm::SCEV::getType().
Friends And Related Function Documentation
ScalarEvolution
friend class ScalarEvolution friend
Definition at line 223 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h