LLVM: llvm::TypedTrackingMDRef< T > Class Template Reference
llvm::TypedTrackingMDRef< T > Class Template Reference
Typed tracking ref.
#include "llvm/IR/TrackingMDRef.h"
Public Member Functions
TypedTrackingMDRef ()=default
TypedTrackingMDRef (T *MD)
TypedTrackingMDRef (TypedTrackingMDRef &&X)
TypedTrackingMDRef (const TypedTrackingMDRef &X)
TypedTrackingMDRef & operator= (TypedTrackingMDRef &&X)
TypedTrackingMDRef & operator= (const TypedTrackingMDRef &X)
T * get () const
operator T* () const
T * operator-> () const
T & operator* () const
bool operator== (const TypedTrackingMDRef &X) const
bool operator!= (const TypedTrackingMDRef &X) const
void reset ()
void reset (T *MD)
bool hasTrivialDestructor () const
Check whether this has a trivial destructor.
Detailed Description
template<class T>
class llvm::TypedTrackingMDRef< T >
Typed tracking ref.
Track refererences of a particular type. It's useful to use this for MDNode and ValueAsMetadata.
Definition at line 106 of file TrackingMDRef.h.
Constructor & Destructor Documentation
TypedTrackingMDRef() [1/4]
template<class T > llvm::TypedTrackingMDRef< T >::TypedTrackingMDRef () default
TypedTrackingMDRef() [2/4]
template<class T > llvm::TypedTrackingMDRef< T >::TypedTrackingMDRef (T * MD) inline explicit
Definition at line 111 of file TrackingMDRef.h.
References llvm::Ref.
TypedTrackingMDRef() [3/4]
template<class T > llvm::TypedTrackingMDRef< T >::TypedTrackingMDRef (TypedTrackingMDRef< T > && X) inline
Definition at line 113 of file TrackingMDRef.h.
References llvm::Ref.
TypedTrackingMDRef() [4/4]
template<class T > llvm::TypedTrackingMDRef< T >::TypedTrackingMDRef (const TypedTrackingMDRef< T > & X) inline
Definition at line 114 of file TrackingMDRef.h.
References llvm::Ref.
Member Function Documentation
get()
template<class T > T * llvm::TypedTrackingMDRef< T >::get () const inline
Definition at line 126 of file TrackingMDRef.h.
References llvm::Ref.
Referenced by llvm::DebugLoc::get(), llvm::simplify_type< const TypedTrackingMDRef< T > >::getSimplifiedValue(), llvm::simplify_type< TypedTrackingMDRef< T > >::getSimplifiedValue(), llvm::TypedTrackingMDRef< MDNode >::operator MDNode *(), llvm::TypedTrackingMDRef< T >::operator*(), and llvm::TypedTrackingMDRef< T >::operator->().
hasTrivialDestructor()
template<class T > bool llvm::TypedTrackingMDRef< T >::hasTrivialDestructor () const inline
Check whether this has a trivial destructor.
Definition at line 138 of file TrackingMDRef.h.
References llvm::Ref.
Referenced by llvm::DebugLoc::hasTrivialDestructor().
operator T*()
template<class T > llvm::TypedTrackingMDRef< T >::operator T* () const inline
Definition at line 127 of file TrackingMDRef.h.
operator!=()
template<class T > bool llvm::TypedTrackingMDRef< T >::operator!= (const TypedTrackingMDRef< T > & X) const inline
Definition at line 132 of file TrackingMDRef.h.
References llvm::Ref, and X().
operator*()
template<class T > T & llvm::TypedTrackingMDRef< T >::operator* () const inline
Definition at line 129 of file TrackingMDRef.h.
References llvm::TypedTrackingMDRef< T >::get().
operator->()
template<class T > T * llvm::TypedTrackingMDRef< T >::operator-> () const inline
Definition at line 128 of file TrackingMDRef.h.
References llvm::TypedTrackingMDRef< T >::get().
operator=() [1/2]
template<class T > TypedTrackingMDRef & llvm::TypedTrackingMDRef< T >::operator= (const TypedTrackingMDRef< T > & X) inline
Definition at line 121 of file TrackingMDRef.h.
References llvm::Ref, and X().
operator=() [2/2]
template<class T > TypedTrackingMDRef & llvm::TypedTrackingMDRef< T >::operator= (TypedTrackingMDRef< T > && X) inline
Definition at line 116 of file TrackingMDRef.h.
References llvm::Ref, and X().
operator==()
template<class T > bool llvm::TypedTrackingMDRef< T >::operator== (const TypedTrackingMDRef< T > & X) const inline
Definition at line 131 of file TrackingMDRef.h.
References llvm::Ref, and X().
reset() [1/2]
template<class T > void llvm::TypedTrackingMDRef< T >::reset () inline
Definition at line 134 of file TrackingMDRef.h.
References llvm::Ref.
reset() [2/2]
template<class T > void llvm::TypedTrackingMDRef< T >::reset (T * MD) inline
Definition at line 135 of file TrackingMDRef.h.
References llvm::Ref.
The documentation for this class was generated from the following file:
include/llvm/IR/TrackingMDRef.h