LLVM: llvm::Init Class Reference
llvm::Init Class Reference abstract
#include "llvm/TableGen/Record.h"
Public Member Functions
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Protected Types
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions
Init (InitKind K, uint8_t Opc=0)
Protected Attributes
uint8_t Opc
Detailed Description
Definition at line 287 of file Record.h.
Member Enumeration Documentation
InitKind
enum llvm::Init::InitKind : uint8_t protected
Discriminator enum (for isa<>, dyn_cast<>, et al.)
This enum is laid out by a preorder traversal of the inheritance hierarchy, and does not contain an entry for abstract classes, as per the recommendation in docs/HowToSetUpLLVMStyleRTTI.rst.
We also explicitly include "first" and "last" values for each interior node of the inheritance tree, to make it easier to read the corresponding classof().
We could pack these a bit tighter by not having the IK_FirstXXXInit and IK_LastXXXInit be their own values, but that would degrade readability for really no benefit.
Enumerator
IK_First
IK_FirstTypedInit
IK_BitInit
IK_BitsInit
IK_CodeInit
IK_DagInit
IK_DefInit
IK_FieldInit
IK_IntInit
IK_ListInit
IK_FirstOpInit
IK_BinOpInit
IK_TernOpInit
IK_UnOpInit
IK_LastOpInit
IK_CondOpInit
IK_FoldOpInit
IK_IsAOpInit
IK_StringInit
IK_VarInit
IK_VarListElementInit
IK_VarBitInit
IK_VarDefInit
IK_LastTypedInit
IK_UnsetInit
Definition at line 302 of file Record.h.
Constructor & Destructor Documentation
Init() [1/2]
llvm::Init::Init (InitKind K, uint8_t Opc = 0) inline explicit protected
Definition at line 343 of file Record.h.
Init() [2/2]
llvm::Init::Init (const Init &) delete
~Init()
virtual llvm::Init::~Init () virtual default
Member Function Documentation
convertInitializerBitRange()
virtual Init * llvm::Init::convertInitializerBitRange (ArrayRef< unsigned > Bits) const inline virtual
This method is used to implement the bitrange selection operator.
Given an initializer, it selects the specified bits out, returning them as a new init of bits type. If it is not legal to use the bit subscript operator on this initializer, return null.
Reimplemented in llvm::TypedInit, llvm::BitsInit, and llvm::IntInit.
Definition at line 387 of file Record.h.
convertInitializerTo()
virtual Init * llvm::Init::convertInitializerTo (RecTy * Ty) const pure virtual
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Implemented in llvm::TypedInit, llvm::UnsetInit, llvm::BitInit, llvm::BitsInit, llvm::IntInit, llvm::StringInit, llvm::CodeInit, llvm::ListInit, and llvm::DefInit.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::CondOpInit::Fold(), llvm::UnOpInit::Fold(), and llvm::TernOpInit::resolveReferences().
convertInitListSlice()
virtual Init * llvm::Init::convertInitListSlice (ArrayRef< unsigned > Elements) const inline virtual
This method is used to implement the list slice selection operator.
Given an initializer, it selects the specified list elements, returning them as a new init of list type. If it is not legal to take a slice of this, return null.
Reimplemented in llvm::TypedInit, and llvm::ListInit.
Definition at line 395 of file Record.h.
dump()
LLVM_DUMP_METHOD void Init::dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
Definition at line 295 of file Record.cpp.
References llvm::errs(), and print().
Referenced by llvm::ExecutionEngine::InitializeMemory().
getAsString()
virtual std::string llvm::Init::getAsString () const pure virtual
Convert this value to a string form.
Implemented in llvm::UnsetInit, llvm::BitInit, llvm::BitsInit, llvm::IntInit, llvm::StringInit, llvm::CodeInit, llvm::ListInit, llvm::UnOpInit, llvm::BinOpInit, llvm::TernOpInit, llvm::CondOpInit, llvm::FoldOpInit, llvm::IsAOpInit, llvm::VarInit, llvm::VarBitInit, llvm::VarListElementInit, llvm::DefInit, llvm::VarDefInit, llvm::FieldInit, and llvm::DagInit.
Referenced by llvm::ForeachLoop::dump(), llvm::SetTheory::evaluate(), llvm::FieldInit::Fold(), llvm::ListInit::getAsString(), llvm::UnOpInit::getAsString(), llvm::BinOpInit::getAsString(), llvm::TernOpInit::getAsString(), llvm::CondOpInit::getAsString(), llvm::FoldOpInit::getAsString(), llvm::IsAOpInit::getAsString(), llvm::VarBitInit::getAsString(), llvm::VarListElementInit::getAsString(), llvm::FieldInit::getAsString(), llvm::DagInit::getAsString(), getAsUnquotedString(), and print().
getAsUnquotedString()
virtual std::string llvm::Init::getAsUnquotedString () const inline virtual
Convert this value to a string form, without adding quote markers.
This primaruly affects StringInits where we will not surround the string value with quotes.
Reimplemented in llvm::StringInit, and llvm::CodeInit.
Definition at line 367 of file Record.h.
References getAsString().
Referenced by llvm::TernOpInit::getAsString(), llvm::FoldOpInit::getAsString(), llvm::VarInit::getNameInitAsString(), llvm::RecordVal::getNameInitAsString(), llvm::Record::getNameInitAsString(), and llvm::Record::resolveReferences().
getBit()
virtual Init * llvm::Init::getBit (unsigned Bit) const pure virtual
This method is used to return the initializer for the specified bit.
Implemented in llvm::VarBitInit, llvm::UnsetInit, llvm::BitInit, llvm::BitsInit, llvm::IntInit, llvm::StringInit, llvm::CodeInit, llvm::ListInit, llvm::OpInit, llvm::CondOpInit, llvm::FoldOpInit, llvm::IsAOpInit, llvm::VarInit, llvm::VarListElementInit, llvm::DefInit, llvm::VarDefInit, llvm::FieldInit, and llvm::DagInit.
Referenced by llvm::BitsInit::resolveReferences().
getCastTo()
virtual Init * llvm::Init::getCastTo (RecTy * Ty) const pure virtual
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Otherwise, return nullptr.
Implemented in llvm::TypedInit, and llvm::UnsetInit.
Referenced by llvm::RecordVal::setValue().
getFieldType()
virtual RecTy * llvm::Init::getFieldType (StringInit * FieldName) const inline virtual
This method is used to implement the FieldInit class.
Implementors of this method should return the type of the named field if they are of record type.
Reimplemented in llvm::TypedInit, and llvm::DefInit.
Definition at line 402 of file Record.h.
getKind()
InitKind llvm::Init::getKind () const inline
Definition at line 340 of file Record.h.
isComplete()
virtual bool llvm::Init::isComplete () const inline virtual
This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented in llvm::UnsetInit, llvm::BitsInit, llvm::TernOpInit, llvm::CondOpInit, llvm::FoldOpInit, and llvm::IsAOpInit.
Definition at line 352 of file Record.h.
Referenced by llvm::BitsInit::allInComplete(), llvm::FieldInit::Fold(), llvm::BitsInit::isComplete(), and llvm::TernOpInit::isComplete().
isConcrete()
virtual bool llvm::Init::isConcrete () const inline virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented in llvm::UnsetInit, llvm::BitInit, llvm::BitsInit, llvm::IntInit, llvm::StringInit, llvm::CodeInit, llvm::ListInit, llvm::CondOpInit, llvm::DefInit, and llvm::DagInit.
Definition at line 356 of file Record.h.
Referenced by llvm::ListInit::isConcrete(), and llvm::DagInit::isConcrete().
operator=()
Init & llvm::Init::operator= (const Init &) delete
print()
void llvm::Init::print (raw_ostream & OS) const inline
Print out this value.
Definition at line 359 of file Record.h.
References getAsString().
Referenced by dump().
resolveReferences()
virtual Init * llvm::Init::resolveReferences (Resolver & R) const inline virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented in llvm::BitsInit, llvm::ListInit, llvm::UnOpInit, llvm::BinOpInit, llvm::TernOpInit, llvm::CondOpInit, llvm::FoldOpInit, llvm::IsAOpInit, llvm::VarInit, llvm::VarBitInit, llvm::VarListElementInit, llvm::VarDefInit, llvm::FieldInit, and llvm::DagInit.
Definition at line 410 of file Record.h.
Referenced by llvm::FoldOpInit::Fold(), ForeachApply(), llvm::RecordResolver::resolve(), llvm::BitsInit::resolveReferences(), llvm::UnOpInit::resolveReferences(), llvm::BinOpInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), llvm::CondOpInit::resolveReferences(), llvm::FoldOpInit::resolveReferences(), llvm::IsAOpInit::resolveReferences(), llvm::VarBitInit::resolveReferences(), llvm::VarListElementInit::resolveReferences(), llvm::FieldInit::resolveReferences(), llvm::DagInit::resolveReferences(), and llvm::Record::resolveReferences().
Member Data Documentation
Opc
uint8_t llvm::Init::Opc protected
Definition at line 334 of file Record.h.
Referenced by llvm::BinOpInit::get(), llvm::TernOpInit::get(), llvm::UnOpInit::get(), llvm::UnOpInit::getOpcode(), llvm::BinOpInit::getOpcode(), and llvm::TernOpInit::getOpcode().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp