LLVM: llvm::DWARFContext Class Reference
llvm::DWARFContext Class Reference
DWARFContext This data structure is the top level entity that deals with dwarf debug information parsing.
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
Classes
struct DIEsForAddress
Wraps the returned DIEs for a given address.
Public Types
using unit_iterator_range = DWARFUnitVector::iterator_range
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF , CK_PDB }
Public Member Functions
DWARFContext (std::unique_ptr< const DWARFObject > DObj, std::string DWPName="")
~DWARFContext ()
DWARFContext (DWARFContext &)=delete
DWARFContext & operator= (DWARFContext &)=delete
const DWARFObject & getDWARFObj () const
void dump (raw_ostream &OS, DIDumpOptions DumpOpts, std::array< Optional< uint64_t >, DIDT_ID_Count > DumpOffsets)
Dump a textual representation to OS.
void dump (raw_ostream &OS, DIDumpOptions DumpOpts) override
bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={}) override
unit_iterator_range info_section_units ()
Get units from .debug_info in this context.
unit_iterator_range types_section_units ()
Get units from .debug_types in this context.
unit_iterator_range compile_units ()
Get compile units in this context.
unit_iterator_range type_units ()
Get type units in this context.
unit_iterator_range normal_units ()
Get all normal compile/type units in this context.
unit_iterator_range dwo_info_section_units ()
Get units from .debug_info..dwo in the DWO context.
unit_iterator_range dwo_types_section_units ()
Get units from .debug_types.dwo in the DWO context.
unit_iterator_range dwo_compile_units ()
Get compile units in the DWO context.
unit_iterator_range dwo_type_units ()
Get type units in the DWO context.
unit_iterator_range dwo_units ()
Get all units in the DWO context.
unsigned getNumCompileUnits ()
Get the number of compile units in this context.
unsigned getNumTypeUnits ()
Get the number of type units in this context.
unsigned getNumDWOCompileUnits ()
Get the number of compile units in the DWO context.
unsigned getNumDWOTypeUnits ()
Get the number of type units in the DWO context.
DWARFUnit * getUnitAtIndex (unsigned index)
Get the unit at the specified index.
DWARFUnit * getDWOUnitAtIndex (unsigned index)
Get the unit at the specified index for the DWO units.
DWARFCompileUnit * getDWOCompileUnitForHash (uint64_t Hash)
DWARFCompileUnit * getCompileUnitForOffset (uint32_t Offset)
Return the compile unit that includes an offset (relative to .debug_info).
DWARFDie getDIEForOffset (uint32_t Offset)
Get a DIE given an exact offset.
unsigned getMaxVersion ()
unsigned getMaxDWOVersion ()
void setMaxVersionIfGreater (unsigned Version)
const DWARFUnitIndex & getCUIndex ()
DWARFGdbIndex & getGdbIndex ()
const DWARFUnitIndex & getTUIndex ()
const DWARFDebugAbbrev * getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
const DWARFDebugLoc * getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAbbrev * getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
const DWARFDebugLoclists * getDebugLocDWO ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAranges * getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
const DWARFDebugFrame * getDebugFrame ()
Get a pointer to the parsed frame information object.
const DWARFDebugFrame * getEHFrame ()
Get a pointer to the parsed eh frame information object.
const DWARFDebugMacro * getDebugMacro ()
Get a pointer to the parsed DebugMacro object.
const DWARFDebugNames & getDebugNames ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleNames ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleTypes ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleNamespaces ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleObjC ()
Get a reference to the parsed accelerator table object.
const DWARFDebugLine::LineTable * getLineTableForUnit (DWARFUnit *U)
Get a pointer to a parsed line table corresponding to a compile unit.
Expected< const DWARFDebugLine::LineTable * > getLineTableForUnit (DWARFUnit *U, std::function< void(Error)> RecoverableErrorCallback)
Get a pointer to a parsed line table corresponding to a compile unit.
DataExtractor getStringExtractor () const
DataExtractor getLineStringExtractor () const
DIEsForAddress getDIEsForAddress (uint64_t Address)
Get the compilation unit, the function DIE and lexical block DIE for the given address where applicable.
DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address) override
bool isLittleEndian () const
std::shared_ptr< DWARFContext > getDWOContext (StringRef AbsolutePath)
const MCRegisterInfo * getRegisterInfo () const
Error loadRegisterInfo (const object::ObjectFile &Obj)
Loads register info for the architecture of the provided object file.
uint8_t getCUAddrSize ()
Get address size from CUs.
Triple::ArchType getArch () const
Public Member Functions inherited from llvm::DIContext
DIContext (DIContextKind K)
virtual ~DIContext ()=default
DIContextKind getKind () const
virtual void dump (raw_ostream &OS, DIDumpOptions DumpOpts)=0
virtual bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={})
virtual DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address)=0
Static Public Member Functions
static bool classof (const DIContext *DICtx)
static bool isSupportedVersion (unsigned version)
static ErrorPolicy defaultErrorHandler (Error E)
Function used to handle default error reporting policy.
static std::unique_ptr< DWARFContext > create (const object::ObjectFile &Obj, const LoadedObjectInfo *L=nullptr, function_ref< ErrorPolicy(Error)> HandleError=defaultErrorHandler, std::string DWPName="")
static std::unique_ptr< DWARFContext > create (const StringMap< std::unique_ptr< MemoryBuffer > > &Sections, uint8_t AddrSize, bool isLittleEndian=sys::IsLittleEndianHost)
static void dumpWarning (Error Warning)
Dump Error as warning message to stderr.
Detailed Description
DWARFContext This data structure is the top level entity that deals with dwarf debug information parsing.
The actual data is supplied through DWARFObj.
Definition at line 58 of file DWARFContext.h.
Member Typedef Documentation
unit_iterator_range
using llvm::DWARFContext::unit_iterator_range = DWARFUnitVector::iterator_range
Definition at line 134 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContext() [1/2]
DWARFContext::DWARFContext (std::unique_ptr< const DWARFObject > DObj, std::string DWPName = "")
Definition at line 68 of file DWARFContext.cpp.
~DWARFContext()
DWARFContext::~DWARFContext () default
DWARFContext() [2/2]
llvm::DWARFContext::DWARFContext (DWARFContext &) delete
Member Function Documentation
classof()
static bool llvm::DWARFContext::classof (const DIContext * DICtx) inline static
Definition at line 118 of file DWARFContext.h.
References llvm::DIContext::CK_DWARF, and llvm::DIContext::getKind().
compile_units()
unit_iterator_range llvm::DWARFContext::compile_units () inline
Get compile units in this context.
Definition at line 152 of file DWARFContext.h.
References info_section_units().
Referenced by dump(), llvm::DWARFDebugAranges::generate(), and getCUAddrSize().
create() [1/2]
std::unique_ptr< DWARFContext > DWARFContext::create (const object::ObjectFile & Obj, const LoadedObjectInfo * L = nullptr, function_ref< ErrorPolicy(Error)> HandleError = defaultErrorHandler, std::string DWPName = "") static
Definition at line 1799 of file DWARFContext.cpp.
create() [2/2]
std::unique_ptr< DWARFContext > DWARFContext::create (const StringMap< std::unique_ptr< MemoryBuffer > > & Sections, uint8_t AddrSize, bool isLittleEndian = sys::IsLittleEndianHost) static
Definition at line 1807 of file DWARFContext.cpp.
References isLittleEndian().
defaultErrorHandler()
ErrorPolicy DWARFContext::defaultErrorHandler (Error E) static
Function used to handle default error reporting policy.
Prints a error message and returns Continue, so DWARF context ignores the error.
Definition at line 1356 of file DWARFContext.cpp.
References llvm::Continue, llvm::WithColor::error(), and llvm::toString().
Referenced by llvm::symbolize::LLVMSymbolizer::symbolizeCode().
dump() [1/2]
void llvm::DWARFContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts) inline override virtual
Implements llvm::DIContext.
Definition at line 127 of file DWARFContext.h.
References llvm::DIDT_ID_Count, and dump().
dump() [2/2]
void DWARFContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts, std::array< Optional< uint64_t >, DIDT_ID_Count > DumpOffsets)
Dump a textual representation to OS.
If any DumpOffsets are present, dump only the record at the specified offset.
Definition at line 317 of file DWARFContext.cpp.
References compile_units(), llvm::DIDT_All, llvm::DIDT_UUID, llvm::DWARFDebugLine::SectionParser::done(), llvm::DWARFGdbIndex::dump(), llvm::DWARFDebugAbbrev::dump(), llvm::DWARFDebugArangeSet::dump(), llvm::DWARFDebugMacro::dump(), llvm::DWARFDebugPubTable::dump(), llvm::DWARFDebugRangeList::dump(), llvm::DWARFUnitIndex::dump(), llvm::AppleAcceleratorTable::dump(), llvm::DWARFDebugNames::dump(), llvm::DWARFDebugFrame::dump(), llvm::DWARFDebugLoc::dump(), llvm::DWARFDebugLine::LineTable::dump(), dump(), llvm::DWARFDebugLoclists::dump(), dumpAddrSection(), dumpLoclistsSection(), dumpRnglistsSection(), dumpStringOffsetsSection(), llvm::DIDumpOptions::DumpType, dumpUUID(), dumpWarning(), dwo_compile_units(), dwo_info_section_units(), dwo_type_units(), dwo_types_section_units(), dwo_units(), llvm::WithColor::error(), llvm::sys::path::extension(), llvm::DWARFDebugRangeList::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::format(), getAppleNames(), getAppleNamespaces(), getAppleObjC(), getAppleTypes(), llvm::DataExtractor::getCStr(), getCUAddrSize(), getCUIndex(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugLocDWO(), getDebugMacro(), getDebugNames(), getEHFrame(), getGdbIndex(), getMaxDWOVersion(), getMaxVersion(), getNumCompileUnits(), getNumDWOCompileUnits(), getNumDWOTypeUnits(), getNumTypeUnits(), llvm::DWARFDebugLine::SectionParser::getOffset(), getRegisterInfo(), getTUIndex(), I, info_section_units(), isLittleEndian(), llvm::DataExtractor::isValidOffset(), llvm::DIDumpOptions::noImplicitRecursion(), llvm::None, normal_units(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::DWARFDebugLine::SectionParser::skip(), llvm::toString(), type_units(), types_section_units(), llvm::DIDumpOptions::Verbose, and llvm::raw_ostream::write_escaped().
Referenced by dump().
dumpWarning()
void DWARFContext::dumpWarning (Error Warning) static
Dump Error as warning message to stderr.
Definition at line 1845 of file DWARFContext.cpp.
References llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), llvm::Warning, and llvm::WithColor::warning().
Referenced by dump(), dumpAddrSection(), and getLineTableForUnit().
dwo_compile_units()
unit_iterator_range llvm::DWARFContext::dwo_compile_units () inline
Get compile units in the DWO context.
Definition at line 178 of file DWARFContext.h.
References dwo_info_section_units().
Referenced by dump(), and getDWOCompileUnitForHash().
dwo_info_section_units()
unit_iterator_range llvm::DWARFContext::dwo_info_section_units () inline
Get units from .debug_info..dwo in the DWO context.
Definition at line 164 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), dwo_compile_units(), and getMaxDWOVersion().
dwo_type_units()
unit_iterator_range llvm::DWARFContext::dwo_type_units () inline
Get type units in the DWO context.
Definition at line 181 of file DWARFContext.h.
References dwo_types_section_units().
Referenced by dump().
dwo_types_section_units()
unit_iterator_range llvm::DWARFContext::dwo_types_section_units () inline
Get units from .debug_types.dwo in the DWO context.
Definition at line 171 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), and dwo_type_units().
dwo_units()
unit_iterator_range llvm::DWARFContext::dwo_units () inline
Get all units in the DWO context.
Definition at line 184 of file DWARFContext.h.
Referenced by dump().
getAppleNames()
const AppleAcceleratorTable & DWARFContext::getAppleNames ()
Get a reference to the parsed accelerator table object.
Definition at line 816 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleNamespaces()
const AppleAcceleratorTable & DWARFContext::getAppleNamespaces ()
Get a reference to the parsed accelerator table object.
Definition at line 826 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleObjC()
const AppleAcceleratorTable & DWARFContext::getAppleObjC ()
Get a reference to the parsed accelerator table object.
Definition at line 832 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleTypes()
const AppleAcceleratorTable & DWARFContext::getAppleTypes ()
Get a reference to the parsed accelerator table object.
Definition at line 821 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getArch()
Triple::ArchType llvm::DWARFContext::getArch () const inline
Definition at line 370 of file DWARFContext.h.
References getDWARFObj(), and llvm::DWARFObject::getFile().
Referenced by getDebugFrame(), and getEHFrame().
getCompileUnitForOffset()
DWARFCompileUnit * DWARFContext::getCompileUnitForOffset (uint32_t Offset)
Return the compile unit that includes an offset (relative to .debug_info).
Definition at line 901 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::getUnitForOffset().
getCUAddrSize()
uint8_t DWARFContext::getCUAddrSize ()
Get address size from CUs.
TODO: refactor compile_units() to make this const.
Definition at line 1831 of file DWARFContext.cpp.
References compile_units(), and llvm::DWARFUnit::getAddressByteSize().
Referenced by dump().
getCUIndex()
const DWARFUnitIndex & DWARFContext::getCUIndex ()
Definition at line 664 of file DWARFContext.cpp.
References llvm::DW_SECT_INFO, and isLittleEndian().
Referenced by dump(), llvm::getDWARFUnitIndex(), and getDWOCompileUnitForHash().
getDebugAbbrev()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
Definition at line 696 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump(), and llvm::DWARFVerifier::handleDebugAbbrev().
getDebugAbbrevDWO()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
Definition at line 707 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump(), and llvm::DWARFVerifier::handleDebugAbbrev().
getDebugAranges()
const DWARFDebugAranges * DWARFContext::getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
Definition at line 747 of file DWARFContext.cpp.
getDebugFrame()
const DWARFDebugFrame * DWARFContext::getDebugFrame ()
Get a pointer to the parsed frame information object.
Definition at line 756 of file DWARFContext.cpp.
References getArch(), and isLittleEndian().
Referenced by dump().
getDebugLoc()
const DWARFDebugLoc * DWARFContext::getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
Definition at line 717 of file DWARFContext.cpp.
References getNumCompileUnits(), getUnitAtIndex(), and isLittleEndian().
Referenced by dump(), and isVariableIndexable().
getDebugLocDWO()
const DWARFDebugLoclists * DWARFContext::getDebugLocDWO ()
Get a pointer to the parsed DebugLoc object.
Definition at line 731 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump().
getDebugMacro()
const DWARFDebugMacro * DWARFContext::getDebugMacro ()
Get a pointer to the parsed DebugMacro object.
Definition at line 787 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump().
getDebugNames()
const DWARFDebugNames & DWARFContext::getDebugNames ()
Get a reference to the parsed accelerator table object.
Definition at line 811 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getDIEForOffset()
DWARFDie DWARFContext::getDIEForOffset (uint32_t Offset)
Get a DIE given an exact offset.
Definition at line 644 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::getUnitForOffset().
getDIEsForAddress()
DWARFContext::DIEsForAddress DWARFContext::getDIEsForAddress (uint64_t Address)
Get the compilation unit, the function DIE and lexical block DIE for the given address where applicable.
TODO: change input parameter from "uint64_t Address" into "SectionedAddress Address"
Definition at line 914 of file DWARFContext.cpp.
References llvm::Address, llvm::DWARFDie::addressRangeContainsAddress(), llvm::DWARFContext::DIEsForAddress::BlockDIE, llvm::DWARFContext::DIEsForAddress::CompileUnit, llvm::DWARFContext::DIEsForAddress::FunctionDIE, llvm::DWARFUnit::getSubroutineForAddress(), llvm::DWARFDie::getTag(), and llvm::DWARFDie::isValid().
getDWARFObj()
const DWARFObject & llvm::DWARFContext::getDWARFObj () const inline
Definition at line 116 of file DWARFContext.h.
Referenced by dumpAttribute(), dumpLocation(), llvm::DWARFFormValue::dumpSectionedAddress(), llvm::DWARFVerifier::DWARFVerifier(), llvm::DWARFUnit::extractRangeList(), llvm::DWARFUnit::findRnglistFromOffset(), llvm::DWARFDebugAranges::generate(), llvm::DWARFUnit::getAddrOffsetSectionItem(), getArch(), llvm::DWARFUnit::getDebugInfoExtractor(), llvm::DWARFUnit::getStringOffsetSectionItem(), llvm::DWARFVerifier::handleAccelTables(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getDWOCompileUnitForHash()
DWARFCompileUnit * DWARFContext::getDWOCompileUnitForHash (uint64_t Hash)
Definition at line 614 of file DWARFContext.cpp.
References dwo_compile_units(), getCUIndex(), llvm::DWARFUnitVector::getUnitForIndexEntry(), and llvm::dwarf::toUnsigned().
getDWOContext()
std::shared_ptr< DWARFContext > DWARFContext::getDWOContext (StringRef AbsolutePath)
Definition at line 1228 of file DWARFContext.cpp.
References llvm::consumeError(), llvm::TargetMachineBuilder::create(), llvm::Expected< T >::get(), and llvm::Expected< T >::takeError().
getDWOUnitAtIndex()
DWARFUnit * llvm::DWARFContext::getDWOUnitAtIndex (unsigned index) inline
Get the unit at the specified index for the DWO units.
Definition at line 220 of file DWARFContext.h.
getEHFrame()
const DWARFDebugFrame * DWARFContext::getEHFrame ()
Get a pointer to the parsed eh frame information object.
Definition at line 776 of file DWARFContext.cpp.
References getArch(), and isLittleEndian().
Referenced by dump().
getGdbIndex()
DWARFGdbIndex & DWARFContext::getGdbIndex ()
Definition at line 686 of file DWARFContext.cpp.
Referenced by dump().
getInliningInfoForAddress()
DIInliningInfo DWARFContext::getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1162 of file DWARFContext.cpp.
References llvm::DIInliningInfo::addFrame(), llvm::Address, llvm::DILineInfo::Column, llvm::DILineInfo::Discriminator, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFDie::getCallerFrame(), llvm::DWARFUnit::getCompilationDir(), llvm::DWARFDie::getDeclLine(), llvm::DWARFDebugLine::LineTable::getFileLineInfoForAddress(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), llvm::DWARFUnit::getInlinedChainForAddress(), getLineTableForUnit(), llvm::DWARFDie::getSubroutineName(), llvm::DILineInfo::Line, and llvm::DILineInfo::StartLine.
getLineInfoForAddress()
DILineInfo DWARFContext::getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1094 of file DWARFContext.cpp.
References llvm::Address, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFUnit::getCompilationDir(), getFunctionNameAndStartLineForAddress(), getLineTableForUnit(), and llvm::DILineInfo::StartLine.
getLineInfoForAddressRange()
DILineInfoTable DWARFContext::getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1114 of file DWARFContext.cpp.
References llvm::DWARFDebugLine::Row::Address, llvm::Address, llvm::DILineInfo::Column, llvm::DWARFDebugLine::Row::Column, llvm::DWARFDebugLine::Row::File, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFUnit::getCompilationDir(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getFunctionNameAndStartLineForAddress(), getLineTableForUnit(), llvm::DILineInfo::Line, llvm::DWARFDebugLine::Row::Line, llvm::DWARFDebugLine::LineTable::lookupAddressRange(), llvm::DWARFDebugLine::LineTable::Rows, and llvm::DILineInfo::StartLine.
getLineStringExtractor()
DataExtractor llvm::DWARFContext::getLineStringExtractor () const inline
Definition at line 306 of file DWARFContext.h.
Referenced by llvm::DWARFFormValue::getAsCString().
getLineTableForUnit() [1/2]
const DWARFDebugLine::LineTable * DWARFContext::getLineTableForUnit (DWARFUnit * U)
Get a pointer to a parsed line table corresponding to a compile unit.
Report any parsing issues as warnings on stderr.
Definition at line 838 of file DWARFContext.cpp.
References dumpWarning(), getLineTableForUnit(), and llvm::Expected< T >::takeError().
Referenced by dumpAttribute(), getInliningInfoForAddress(), getLineInfoForAddress(), getLineInfoForAddressRange(), and getLineTableForUnit().
getLineTableForUnit() [2/2]
Expected< const DWARFDebugLine::LineTable * > DWARFContext::getLineTableForUnit (DWARFUnit * U, std::function< void(Error)> RecoverableErrorCallback)
Get a pointer to a parsed line table corresponding to a compile unit.
Report any recoverable parsing problems using the callback.
Definition at line 848 of file DWARFContext.cpp.
References llvm::DWARFSection::Data, llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFUnit::getLineSection(), llvm::DWARFUnit::getLineTableOffset(), llvm::DWARFUnit::getUnitDIE(), isLittleEndian(), and llvm::dwarf::toSectionOffset().
getLocalsForAddress()
std::vector< DILocal > DWARFContext::getLocalsForAddress (object::SectionedAddress Address) override virtual
Implements llvm::DIContext.
Definition at line 1082 of file DWARFContext.cpp.
References llvm::Address, llvm::DWARFUnit::getSubroutineForAddress(), and llvm::DWARFDie::isValid().
getMaxDWOVersion()
unsigned llvm::DWARFContext::getMaxDWOVersion () inline
Definition at line 239 of file DWARFContext.h.
References dwo_info_section_units().
Referenced by dump().
getMaxVersion()
unsigned llvm::DWARFContext::getMaxVersion () inline
Definition at line 233 of file DWARFContext.h.
References info_section_units().
Referenced by dump().
getNumCompileUnits()
unsigned llvm::DWARFContext::getNumCompileUnits () inline
Get the number of compile units in this context.
Definition at line 190 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), and getDebugLoc().
getNumDWOCompileUnits()
unsigned llvm::DWARFContext::getNumDWOCompileUnits () inline
Get the number of compile units in the DWO context.
Definition at line 202 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump().
getNumDWOTypeUnits()
unsigned llvm::DWARFContext::getNumDWOTypeUnits () inline
Get the number of type units in the DWO context.
Definition at line 208 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumTypesUnits().
Referenced by dump().
getNumTypeUnits()
unsigned llvm::DWARFContext::getNumTypeUnits () inline
Get the number of type units in this context.
Definition at line 196 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumTypesUnits().
Referenced by dump().
getRegisterInfo()
const MCRegisterInfo * llvm::DWARFContext::getRegisterInfo () const inline
Definition at line 344 of file DWARFContext.h.
Referenced by dump(), and dumpLocation().
getStringExtractor()
DataExtractor llvm::DWARFContext::getStringExtractor () const inline
Definition at line 303 of file DWARFContext.h.
Referenced by llvm::DWARFFormValue::getAsCString().
getTUIndex()
const DWARFUnitIndex & DWARFContext::getTUIndex ()
Definition at line 675 of file DWARFContext.cpp.
References llvm::DW_SECT_TYPES, and isLittleEndian().
Referenced by dump(), and llvm::getDWARFUnitIndex().
getUnitAtIndex()
DWARFUnit * llvm::DWARFContext::getUnitAtIndex (unsigned index) inline
Get the unit at the specified index.
Definition at line 214 of file DWARFContext.h.
Referenced by getDebugLoc().
info_section_units()
unit_iterator_range llvm::DWARFContext::info_section_units () inline
Get units from .debug_info in this context.
Definition at line 137 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by compile_units(), dump(), llvm::DWARFUnit::getAddrOffsetSectionItem(), and getMaxVersion().
isLittleEndian()
bool llvm::DWARFContext::isLittleEndian () const inline
Definition at line 337 of file DWARFContext.h.
Referenced by create(), dump(), dumpLocation(), llvm::DWARFDebugAranges::generate(), getAppleNames(), getAppleNamespaces(), getAppleObjC(), getAppleTypes(), getCUIndex(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugLocDWO(), getDebugMacro(), getDebugNames(), getEHFrame(), getLineTableForUnit(), getTUIndex(), llvm::DWARFVerifier::handleAccelTables(), and isVariableIndexable().
isSupportedVersion()
static bool llvm::DWARFContext::isSupportedVersion (unsigned version) inline static
Definition at line 338 of file DWARFContext.h.
Referenced by llvm::DWARFUnitHeader::extract().
loadRegisterInfo()
Error DWARFContext::loadRegisterInfo (const object::ObjectFile & Obj)
Loads register info for the architecture of the provided object file.
Improves readability of dumped DWARF expressions. Requires the caller to have initialized the relevant target descriptions.
Definition at line 1814 of file DWARFContext.cpp.
References llvm::Target::createMCRegInfo(), llvm::createStringError(), llvm::invalid_argument, llvm::TargetRegistry::lookupTarget(), and llvm::Error::success().
normal_units()
unit_iterator_range llvm::DWARFContext::normal_units () inline
Get all normal compile/type units in this context.
Definition at line 158 of file DWARFContext.h.
Referenced by dump().
operator=()
DWARFContext & llvm::DWARFContext::operator= (DWARFContext &) delete
setMaxVersionIfGreater()
void llvm::DWARFContext::setMaxVersionIfGreater (unsigned Version) inline
Definition at line 245 of file DWARFContext.h.
Referenced by llvm::DWARFUnitHeader::extract().
type_units()
unit_iterator_range llvm::DWARFContext::type_units () inline
Get type units in this context.
Definition at line 155 of file DWARFContext.h.
References types_section_units().
Referenced by dump().
types_section_units()
unit_iterator_range llvm::DWARFContext::types_section_units () inline
Get units from .debug_types in this context.
Definition at line 145 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), and type_units().
verify()
bool DWARFContext::verify (raw_ostream & OS, DIDumpOptions DumpOpts = {}) override virtual
Reimplemented from llvm::DIContext.
Definition at line 651 of file DWARFContext.cpp.
References llvm::DIDumpOptions::DumpType, llvm::DWARFVerifier::handleAccelTables(), llvm::DWARFVerifier::handleDebugAbbrev(), llvm::DWARFVerifier::handleDebugInfo(), and llvm::DWARFVerifier::handleDebugLine().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFContext.h
lib/DebugInfo/DWARF/DWARFContext.cpp