LLVM: llvm::ModuleSummaryIndex Class Reference
llvm::ModuleSummaryIndex Class Reference
Class to hold module path string table and global value map, and encapsulate methods for operating on them.
#include "llvm/IR/ModuleSummaryIndex.h"
Public Types
typedef ModulePathStringTableTy::value_type ModuleInfo
Public Member Functions
ModuleSummaryIndex (bool HaveGVs, bool EnableSplitLTOUnit=false)
bool haveGVs () const
gvsummary_iterator begin ()
const_gvsummary_iterator begin () const
gvsummary_iterator end ()
const_gvsummary_iterator end () const
size_t size () const
FunctionSummary calculateCallGraphRoot ()
bool withGlobalValueDeadStripping () const
void setWithGlobalValueDeadStripping ()
bool hasSyntheticEntryCounts () const
void setHasSyntheticEntryCounts ()
bool skipModuleByDistributedBackend () const
void setSkipModuleByDistributedBackend ()
bool enableSplitLTOUnit () const
void setEnableSplitLTOUnit ()
bool partiallySplitLTOUnits () const
void setPartiallySplitLTOUnits ()
bool isGlobalValueLive (const GlobalValueSummary *GVS) const
bool isGUIDLive (GlobalValue::GUID GUID) const
ValueInfo getValueInfo (const GlobalValueSummaryMapTy::value_type &R) const
Return a ValueInfo for the index value_type (convenient when iterating index).
ValueInfo getValueInfo (GlobalValue::GUID GUID) const
Return a ValueInfo for GUID if it exists, otherwise return ValueInfo().
ValueInfo getOrInsertValueInfo (GlobalValue::GUID GUID)
Return a ValueInfo for GUID.
StringRef saveString (StringRef String)
ValueInfo getOrInsertValueInfo (GlobalValue::GUID GUID, StringRef Name)
Return a ValueInfo for GUID setting value Name.
ValueInfo getOrInsertValueInfo (const GlobalValue *GV)
Return a ValueInfo for GV and mark it as belonging to GV.
GlobalValue::GUID getGUIDFromOriginalID (GlobalValue::GUID OriginalID) const
Return the GUID for OriginalId in the OidGuidMap.
std::set< std::string > & cfiFunctionDefs ()
const std::set< std::string > & cfiFunctionDefs () const
std::set< std::string > & cfiFunctionDecls ()
const std::set< std::string > & cfiFunctionDecls () const
void addGlobalValueSummary (const GlobalValue &GV, std::unique_ptr< GlobalValueSummary > Summary)
Add a global value summary for a value.
void addGlobalValueSummary (StringRef ValueName, std::unique_ptr< GlobalValueSummary > Summary)
Add a global value summary for a value of the given name.
void addGlobalValueSummary (ValueInfo VI, std::unique_ptr< GlobalValueSummary > Summary)
Add a global value summary for the given ValueInfo.
void addOriginalName (GlobalValue::GUID ValueGUID, GlobalValue::GUID OrigGUID)
Add an original name for the value of the given GUID.
GlobalValueSummary * findSummaryInModule (ValueInfo VI, StringRef ModuleId) const
Find the summary for ValueInfo VI in module ModuleId, or nullptr if not found.
GlobalValueSummary * findSummaryInModule (GlobalValue::GUID ValueGUID, StringRef ModuleId) const
Find the summary for global GUID in module ModuleId, or nullptr if not found.
GlobalValueSummary * getGlobalValueSummary (const GlobalValue &GV, bool PerModuleIndex=true) const
Returns the first GlobalValueSummary for GV, asserting that there is only one if PerModuleIndex.
GlobalValueSummary * getGlobalValueSummary (GlobalValue::GUID ValueGUID, bool PerModuleIndex=true) const
Returns the first GlobalValueSummary for ValueGUID, asserting that there is only one if PerModuleIndex.
const StringMap< std::pair< uint64_t, ModuleHash > > & modulePaths () const
Table of modules, containing module hash and id.
StringMap< std::pair< uint64_t, ModuleHash > > & modulePaths ()
Table of modules, containing hash and id.
uint64_t getModuleId (const StringRef ModPath) const
Get the module ID recorded for the given module path.
const ModuleHash & getModuleHash (const StringRef ModPath) const
Get the module SHA1 hash recorded for the given module path.
ModuleInfo * addModule (StringRef ModPath, uint64_t ModId, ModuleHash Hash=ModuleHash{{0}})
Add a new module with the given Hash, mapped to the given ModID, and return a reference to the module.
ModuleInfo * getModule (StringRef ModPath)
Return module entry for module with the given ModPath.
bool hasExportedFunctions (const Module &M) const
Check if the given Module has any functions available for exporting in the index.
const TypeIdSummaryMapTy & typeIds () const
TypeIdSummary & getOrInsertTypeIdSummary (StringRef TypeId)
Return an existing or new TypeIdSummary entry for TypeId.
const TypeIdSummary * getTypeIdSummary (StringRef TypeId) const
This returns either a pointer to the type id summary (if present in the summary map) or null (if not present).
const std::map< std::string, TypeIdCompatibleVtableInfo > & typeIdCompatibleVtableMap () const
TypeIdCompatibleVtableInfo & getOrInsertTypeIdCompatibleVtableSummary (StringRef TypeId)
Return an existing or new TypeIdCompatibleVtableMap entry for TypeId.
Optional< TypeIdCompatibleVtableInfo > getTypeIdCompatibleVtableSummary (StringRef TypeId) const
For the given TypeId, this returns the TypeIdCompatibleVtableMap entry if present in the summary map.
void collectDefinedFunctionsForModule (StringRef ModulePath, GVSummaryMapTy &GVSummaryMap) const
Collect for the given module the list of functions it defines (GUID -> Summary).
template<class Map >
void collectDefinedGVSummariesPerModule (Map &ModuleToDefinedGVSummaries) const
Collect for each module the list of Summaries it defines (GUID -> Summary).
void print (raw_ostream &OS, bool IsForDebug=false) const
Print to an output stream.
void dump () const
Dump to stderr (for debugging).
void exportToDot (raw_ostream &OS) const
Export summary to dot file for GraphViz.
void dumpSCCs (raw_ostream &OS)
Print out strongly connected components for debugging.
void propagateAttributes (const DenseSet< GlobalValue::GUID > &PreservedSymbols)
Analyze index and detect unmodified globals.
Static Public Member Functions
static void discoverNodes (ValueInfo V, std::map< ValueInfo, bool > &FunctionHasParent)
Convenience function for doing a DFS on a ValueInfo.
static std::string getGlobalNameForLocal (StringRef Name, ModuleHash ModHash)
Convenience method for creating a promoted global name for the given value name of a local, and its original module's ID.
static StringRef getOriginalNameBeforePromote (StringRef Name)
Helper to obtain the unpromoted name for a global value (or the original name if not promoted).
Detailed Description
Class to hold module path string table and global value map, and encapsulate methods for operating on them.
Definition at line 914 of file ModuleSummaryIndex.h.
Member Typedef Documentation
ModuleInfo
typedef ModulePathStringTableTy::value_type llvm::ModuleSummaryIndex::ModuleInfo
Definition at line 1248 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
ModuleSummaryIndex()
llvm::ModuleSummaryIndex::ModuleSummaryIndex (bool HaveGVs, bool EnableSplitLTOUnit = false) inline
Definition at line 984 of file ModuleSummaryIndex.h.
Member Function Documentation
addGlobalValueSummary() [1/3]
void llvm::ModuleSummaryIndex::addGlobalValueSummary (const GlobalValue & GV, std::unique_ptr< GlobalValueSummary > Summary) inline
Add a global value summary for a value.
Definition at line 1138 of file ModuleSummaryIndex.h.
References addGlobalValueSummary(), and getOrInsertValueInfo().
Referenced by addGlobalValueSummary(), llvm::buildModuleSummaryIndex(), computeAliasSummary(), computeFunctionSummary(), and computeVariableSummary().
addGlobalValueSummary() [2/3]
void llvm::ModuleSummaryIndex::addGlobalValueSummary (StringRef ValueName, std::unique_ptr< GlobalValueSummary > Summary) inline
Add a global value summary for a value of the given name.
Definition at line 1144 of file ModuleSummaryIndex.h.
References addGlobalValueSummary(), llvm::GlobalValue::getGUID(), and getOrInsertValueInfo().
addGlobalValueSummary() [3/3]
void llvm::ModuleSummaryIndex::addGlobalValueSummary (ValueInfo VI, std::unique_ptr< GlobalValueSummary > Summary) inline
Add a global value summary for the given ValueInfo.
Definition at line 1151 of file ModuleSummaryIndex.h.
References addOriginalName(), llvm::ValueInfo::getGUID(), and llvm::ValueInfo::getRef().
addModule()
ModuleInfo * llvm::ModuleSummaryIndex::addModule (StringRef ModPath, uint64_t ModId, ModuleHash Hash = ModuleHash{{0}}) inline
Add a new module with the given Hash, mapped to the given ModID, and return a reference to the module.
Definition at line 1252 of file ModuleSummaryIndex.h.
addOriginalName()
void llvm::ModuleSummaryIndex::addOriginalName (GlobalValue::GUID ValueGUID, GlobalValue::GUID OrigGUID) inline
Add an original name for the value of the given GUID.
Definition at line 1161 of file ModuleSummaryIndex.h.
Referenced by addGlobalValueSummary().
begin() [1/2]
gvsummary_iterator llvm::ModuleSummaryIndex::begin () inline
Definition at line 990 of file ModuleSummaryIndex.h.
begin() [2/2]
const_gvsummary_iterator llvm::ModuleSummaryIndex::begin () const inline
Definition at line 991 of file ModuleSummaryIndex.h.
calculateCallGraphRoot()
FunctionSummary llvm::ModuleSummaryIndex::calculateCallGraphRoot () inline
Definition at line 1030 of file ModuleSummaryIndex.h.
References discoverNodes(), llvm::FunctionSummary::makeDummyFunctionSummary(), and P.
Referenced by initializeCounts().
cfiFunctionDecls() [1/2]
std::set< std::string > & llvm::ModuleSummaryIndex::cfiFunctionDecls () inline
Definition at line 1134 of file ModuleSummaryIndex.h.
cfiFunctionDecls() [2/2]
const std::set< std::string > & llvm::ModuleSummaryIndex::cfiFunctionDecls () const inline
Definition at line 1135 of file ModuleSummaryIndex.h.
cfiFunctionDefs() [1/2]
std::set< std::string > & llvm::ModuleSummaryIndex::cfiFunctionDefs () inline
Definition at line 1131 of file ModuleSummaryIndex.h.
cfiFunctionDefs() [2/2]
const std::set< std::string > & llvm::ModuleSummaryIndex::cfiFunctionDefs () const inline
Definition at line 1132 of file ModuleSummaryIndex.h.
collectDefinedFunctionsForModule()
void ModuleSummaryIndex::collectDefinedFunctionsForModule (StringRef ModulePath, GVSummaryMapTy & GVSummaryMap) const
Collect for the given module the list of functions it defines (GUID -> Summary).
Definition at line 66 of file ModuleSummaryIndex.cpp.
Referenced by llvm::ComputeCrossModuleImportForModule().
collectDefinedGVSummariesPerModule()
template<class Map > void llvm::ModuleSummaryIndex::collectDefinedGVSummariesPerModule (Map & ModuleToDefinedGVSummaries) const inline
Collect for each module the list of Summaries it defines (GUID -> Summary).
Definition at line 1328 of file ModuleSummaryIndex.h.
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), exportToDot(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
discoverNodes()
static void llvm::ModuleSummaryIndex::discoverNodes (ValueInfo V, std::map< ValueInfo, bool > & FunctionHasParent) inline static
Convenience function for doing a DFS on a ValueInfo.
Marks the function in the FunctionHasParent map.
Definition at line 998 of file ModuleSummaryIndex.h.
References assert(), discoverNodes(), F, and llvm::ValueInfo::getSummaryList().
Referenced by calculateCallGraphRoot(), and discoverNodes().
dump()
LLVM_DUMP_METHOD void ModuleSummaryIndex::dump () const
Dump to stderr (for debugging).
Definition at line 4456 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
dumpSCCs()
LLVM_DUMP_METHOD void ModuleSummaryIndex::dumpSCCs (raw_ostream & OS)
Print out strongly connected components for debugging.
Definition at line 199 of file ModuleSummaryIndex.cpp.
References F, and I.
enableSplitLTOUnit()
bool llvm::ModuleSummaryIndex::enableSplitLTOUnit () const inline
Definition at line 1076 of file ModuleSummaryIndex.h.
Referenced by computeVariableSummary().
end() [1/2]
gvsummary_iterator llvm::ModuleSummaryIndex::end () inline
Definition at line 992 of file ModuleSummaryIndex.h.
end() [2/2]
const_gvsummary_iterator llvm::ModuleSummaryIndex::end () const inline
Definition at line 993 of file ModuleSummaryIndex.h.
exportToDot()
void ModuleSummaryIndex::exportToDot (raw_ostream & OS) const
Export summary to dot file for GraphViz.
Definition at line 366 of file ModuleSummaryIndex.cpp.
References assert(), collectDefinedGVSummariesPerModule(), defineExternalNode(), llvm::sys::path::filename(), getModuleId(), getNodeLabel(), getValueInfo(), hasReadOnlyFlag(), and hasWriteOnlyFlag().
Referenced by llvm::buildModuleSummaryIndex().
findSummaryInModule() [1/2]
GlobalValueSummary * llvm::ModuleSummaryIndex::findSummaryInModule (GlobalValue::GUID ValueGUID, StringRef ModuleId) const inline
Find the summary for global GUID in module ModuleId, or nullptr if not found.
Definition at line 1187 of file ModuleSummaryIndex.h.
References findSummaryInModule(), and getValueInfo().
findSummaryInModule() [2/2]
GlobalValueSummary * llvm::ModuleSummaryIndex::findSummaryInModule (ValueInfo VI, StringRef ModuleId) const inline
Find the summary for ValueInfo VI in module ModuleId, or nullptr if not found.
Definition at line 1173 of file ModuleSummaryIndex.h.
References llvm::ValueInfo::getSummaryList().
Referenced by llvm::computeLTOCacheKey(), and findSummaryInModule().
getGlobalNameForLocal()
static std::string llvm::ModuleSummaryIndex::getGlobalNameForLocal (StringRef Name, ModuleHash ModHash) inline static
Convenience method for creating a promoted global name for the given value name of a local, and its original module's ID.
Definition at line 1233 of file ModuleSummaryIndex.h.
getGlobalValueSummary() [1/2]
GlobalValueSummary * llvm::ModuleSummaryIndex::getGlobalValueSummary (const GlobalValue & GV, bool PerModuleIndex = true) const inline
Returns the first GlobalValueSummary for GV, asserting that there is only one if PerModuleIndex.
Definition at line 1197 of file ModuleSummaryIndex.h.
References assert(), getGlobalValueSummary(), llvm::GlobalValue::getGUID(), and llvm::Value::hasName().
Referenced by llvm::buildModuleSummaryIndex(), and getGlobalValueSummary().
getGlobalValueSummary() [2/2]
GlobalValueSummary * ModuleSummaryIndex::getGlobalValueSummary (GlobalValue::GUID ValueGUID, bool PerModuleIndex = true) const
Returns the first GlobalValueSummary for ValueGUID, asserting that there is only one if PerModuleIndex.
Definition at line 84 of file ModuleSummaryIndex.cpp.
References assert(), and getValueInfo().
getGUIDFromOriginalID()
GlobalValue::GUID llvm::ModuleSummaryIndex::getGUIDFromOriginalID (GlobalValue::GUID OriginalID) const inline
Return the GUID for OriginalId in the OidGuidMap.
Definition at line 1126 of file ModuleSummaryIndex.h.
References I.
Referenced by updateValueInfoForIndirectCalls().
getModule()
ModuleInfo * llvm::ModuleSummaryIndex::getModule (StringRef ModPath) inline
Return module entry for module with the given ModPath.
Definition at line 1258 of file ModuleSummaryIndex.h.
References assert().
getModuleHash()
const ModuleHash & llvm::ModuleSummaryIndex::getModuleHash (const StringRef ModPath) const inline
Get the module SHA1 hash recorded for the given module path.
Definition at line 1225 of file ModuleSummaryIndex.h.
References assert().
Referenced by llvm::computeLTOCacheKey().
getModuleId()
uint64_t llvm::ModuleSummaryIndex::getModuleId (const StringRef ModPath) const inline
Get the module ID recorded for the given module path.
Definition at line 1220 of file ModuleSummaryIndex.h.
Referenced by exportToDot().
getOriginalNameBeforePromote()
static StringRef llvm::ModuleSummaryIndex::getOriginalNameBeforePromote (StringRef Name) inline static
Helper to obtain the unpromoted name for a global value (or the original name if not promoted).
Definition at line 1243 of file ModuleSummaryIndex.h.
Referenced by llvm::thinLTOInternalizeModule().
getOrInsertTypeIdCompatibleVtableSummary()
TypeIdCompatibleVtableInfo & llvm::ModuleSummaryIndex::getOrInsertTypeIdCompatibleVtableSummary (StringRef TypeId) inline
Return an existing or new TypeIdCompatibleVtableMap entry for TypeId.
This accessor can mutate the map and therefore should not be used in the ThinLTO backends.
Definition at line 1305 of file ModuleSummaryIndex.h.
Referenced by recordTypeIdCompatibleVtableReferences().
getOrInsertTypeIdSummary()
TypeIdSummary & llvm::ModuleSummaryIndex::getOrInsertTypeIdSummary (StringRef TypeId) inline
Return an existing or new TypeIdSummary entry for TypeId.
This accessor can mutate the map and therefore should not be used in the ThinLTO backends.
Definition at line 1276 of file ModuleSummaryIndex.h.
References llvm::GlobalValue::getGUID().
getOrInsertValueInfo() [1/3]
ValueInfo llvm::ModuleSummaryIndex::getOrInsertValueInfo (const GlobalValue * GV) inline
Return a ValueInfo for GV and mark it as belonging to GV.
Definition at line 1118 of file ModuleSummaryIndex.h.
References assert(), and llvm::GlobalValue::getGUID().
getOrInsertValueInfo() [2/3]
ValueInfo llvm::ModuleSummaryIndex::getOrInsertValueInfo (GlobalValue::GUID GUID) inline
Return a ValueInfo for GUID.
Definition at line 1100 of file ModuleSummaryIndex.h.
Referenced by addGlobalValueSummary(), computeFunctionSummary(), findFuncPointers(), findRefEdges(), and recordTypeIdCompatibleVtableReferences().
getOrInsertValueInfo() [3/3]
ValueInfo llvm::ModuleSummaryIndex::getOrInsertValueInfo (GlobalValue::GUID GUID, StringRef Name) inline
Return a ValueInfo for GUID setting value Name.
Definition at line 1110 of file ModuleSummaryIndex.h.
References assert().
getTypeIdCompatibleVtableSummary()
Optional< TypeIdCompatibleVtableInfo > llvm::ModuleSummaryIndex::getTypeIdCompatibleVtableSummary (StringRef TypeId) const inline
For the given TypeId, this returns the TypeIdCompatibleVtableMap entry if present in the summary map.
This may be used when importing.
Definition at line 1312 of file ModuleSummaryIndex.h.
References I, and llvm::None.
getTypeIdSummary()
const TypeIdSummary * llvm::ModuleSummaryIndex::getTypeIdSummary (StringRef TypeId) const inline
This returns either a pointer to the type id summary (if present in the summary map) or null (if not present).
This may be used when importing.
Definition at line 1288 of file ModuleSummaryIndex.h.
References llvm::GlobalValue::getGUID().
getValueInfo() [1/2]
ValueInfo llvm::ModuleSummaryIndex::getValueInfo (const GlobalValueSummaryMapTy::value_type & R) const inline
Return a ValueInfo for the index value_type (convenient when iterating index).
Definition at line 1089 of file ModuleSummaryIndex.h.
Referenced by computeAliasSummary(), llvm::computeDeadSymbols(), ComputeImportForModule(), exportToDot(), findSummaryInModule(), getGlobalValueSummary(), isGlobalVarSummary(), isGUIDLive(), setLiveRoot(), and updateValueInfoForIndirectCalls().
getValueInfo() [2/2]
ValueInfo llvm::ModuleSummaryIndex::getValueInfo (GlobalValue::GUID GUID) const inline
Return a ValueInfo for GUID if it exists, otherwise return ValueInfo().
Definition at line 1094 of file ModuleSummaryIndex.h.
References I.
hasExportedFunctions()
bool llvm::ModuleSummaryIndex::hasExportedFunctions (const Module & M) const inline
Check if the given Module has any functions available for exporting in the index.
We consider any module present in the ModulePathStringTable to have exported functions.
Definition at line 1267 of file ModuleSummaryIndex.h.
Referenced by llvm::FunctionImportGlobalProcessing::FunctionImportGlobalProcessing().
hasSyntheticEntryCounts()
bool llvm::ModuleSummaryIndex::hasSyntheticEntryCounts () const inline
Definition at line 1066 of file ModuleSummaryIndex.h.
haveGVs()
bool llvm::ModuleSummaryIndex::haveGVs () const inline
Definition at line 988 of file ModuleSummaryIndex.h.
isGlobalValueLive()
bool llvm::ModuleSummaryIndex::isGlobalValueLive (const GlobalValueSummary * GVS) const inline
Definition at line 1082 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::isLive().
Referenced by ComputeImportForModule(), dropDeadSymbols(), isGUIDLive(), propagateAttributes(), and selectCallee().
isGUIDLive()
bool ModuleSummaryIndex::isGUIDLive (GlobalValue::GUID GUID) const
Definition at line 94 of file ModuleSummaryIndex.cpp.
References getValueInfo(), I, and isGlobalValueLive().
modulePaths() [1/2]
StringMap< std::pair< uint64_t, ModuleHash > > & llvm::ModuleSummaryIndex::modulePaths () inline
Table of modules, containing hash and id.
Definition at line 1215 of file ModuleSummaryIndex.h.
modulePaths() [2/2]
const StringMap< std::pair< uint64_t, ModuleHash > > & llvm::ModuleSummaryIndex::modulePaths () const inline
Table of modules, containing module hash and id.
Definition at line 1210 of file ModuleSummaryIndex.h.
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), and llvm::ThinLTOCodeGenerator::promote().
partiallySplitLTOUnits()
bool llvm::ModuleSummaryIndex::partiallySplitLTOUnits () const inline
Definition at line 1079 of file ModuleSummaryIndex.h.
print()
void ModuleSummaryIndex::print (raw_ostream & OS, bool IsForDebug = false) const
Print to an output stream.
Definition at line 4414 of file AsmWriter.cpp.
Referenced by dump().
propagateAttributes()
void ModuleSummaryIndex::propagateAttributes (const DenseSet< GlobalValue::GUID > & PreservedSymbols)
Analyze index and detect unmodified globals.
Definition at line 156 of file ModuleSummaryIndex.cpp.
References llvm::canImportGlobalVar(), isGlobalValueLive(), P, and propagateAttributesToRefs().
Referenced by llvm::computeDeadSymbolsWithConstProp().
saveString()
StringRef llvm::ModuleSummaryIndex::saveString (StringRef String) inline
Definition at line 1107 of file ModuleSummaryIndex.h.
References llvm::StringSaver::save(), and llvm::String.
setEnableSplitLTOUnit()
void llvm::ModuleSummaryIndex::setEnableSplitLTOUnit () inline
Definition at line 1077 of file ModuleSummaryIndex.h.
setHasSyntheticEntryCounts()
void llvm::ModuleSummaryIndex::setHasSyntheticEntryCounts () inline
Definition at line 1067 of file ModuleSummaryIndex.h.
Referenced by llvm::computeSyntheticCounts().
setPartiallySplitLTOUnits()
void llvm::ModuleSummaryIndex::setPartiallySplitLTOUnits () inline
Definition at line 1080 of file ModuleSummaryIndex.h.
setSkipModuleByDistributedBackend()
void llvm::ModuleSummaryIndex::setSkipModuleByDistributedBackend () inline
Definition at line 1072 of file ModuleSummaryIndex.h.
setWithGlobalValueDeadStripping()
void llvm::ModuleSummaryIndex::setWithGlobalValueDeadStripping () inline
Definition at line 1062 of file ModuleSummaryIndex.h.
size()
size_t llvm::ModuleSummaryIndex::size () const inline
Definition at line 994 of file ModuleSummaryIndex.h.
skipModuleByDistributedBackend()
bool llvm::ModuleSummaryIndex::skipModuleByDistributedBackend () const inline
Definition at line 1069 of file ModuleSummaryIndex.h.
typeIdCompatibleVtableMap()
const std::map< std::string, TypeIdCompatibleVtableInfo > & llvm::ModuleSummaryIndex::typeIdCompatibleVtableMap () const inline
Definition at line 1297 of file ModuleSummaryIndex.h.
typeIds()
const TypeIdSummaryMapTy & llvm::ModuleSummaryIndex::typeIds () const inline
Definition at line 1271 of file ModuleSummaryIndex.h.
Referenced by llvm::computeLTOCacheKey().
withGlobalValueDeadStripping()
bool llvm::ModuleSummaryIndex::withGlobalValueDeadStripping () const inline
Definition at line 1059 of file ModuleSummaryIndex.h.
Referenced by llvm::computeDeadSymbols().
The documentation for this class was generated from the following files:
include/llvm/IR/ModuleSummaryIndex.h
lib/IR/AsmWriter.cpp
lib/IR/ModuleSummaryIndex.cpp