LLVM: llvm::AppleAccelTableTypeData Class Reference
llvm::AppleAccelTableTypeData Class Reference
Accelerator table data implementation for Apple type accelerator tables.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
AppleAccelTableTypeData (const DIE &D)
void emit (AsmPrinter *Asm) const override
void print (raw_ostream &OS) const override
Public Member Functions inherited from llvm::AppleAccelTableOffsetData
AppleAccelTableOffsetData (const DIE &D)
void emit (AsmPrinter *Asm) const override
void print (raw_ostream &OS) const override
virtual void emit (AsmPrinter *Asm) const =0
Public Member Functions inherited from llvm::AccelTableData
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
virtual void print (raw_ostream &OS) const =0
Static Public Attributes
static constexpr Atom Atoms []
Static Public Attributes inherited from llvm::AppleAccelTableOffsetData
static constexpr Atom Atoms []
Additional Inherited Members
Static Public Member Functions inherited from llvm::AppleAccelTableData
static uint32_t hash (StringRef Buffer)
Protected Member Functions inherited from llvm::AppleAccelTableOffsetData
uint64_t order () const override
virtual uint64_t order () const =0
Protected Attributes inherited from llvm::AppleAccelTableOffsetData
const DIE & Die
Detailed Description
Accelerator table data implementation for Apple type accelerator tables.
Definition at line 342 of file AccelTable.h.
Constructor & Destructor Documentation
AppleAccelTableTypeData()
llvm::AppleAccelTableTypeData::AppleAccelTableTypeData (const DIE & D) inline
Definition at line 344 of file AccelTable.h.
Member Function Documentation
emit()
void AppleAccelTableTypeData::emit (AsmPrinter * Asm) const override virtual
Reimplemented from llvm::AppleAccelTableOffsetData.
Definition at line 599 of file AccelTable.cpp.
References llvm::AppleAccelTableOffsetData::Die, llvm::DIE::getDebugSectionOffset(), and llvm::DIE::getTag().
print()
void AppleAccelTableTypeData::print (raw_ostream & OS) const override virtual
Reimplemented from llvm::AppleAccelTableOffsetData.
Definition at line 695 of file AccelTable.cpp.
References llvm::AppleAccelTableOffsetData::Die, llvm::DIE::getOffset(), llvm::DIE::getTag(), and llvm::dwarf::TagString().
Member Data Documentation
Atoms
constexpr AppleAccelTableData::Atom AppleAccelTableTypeData::Atoms static constexpr
Initial value:
= {
      Atom(dwarf::DW_ATOM_die_offset, dwarf::DW_FORM_data4),
      Atom(dwarf::DW_ATOM_die_tag, dwarf::DW_FORM_data2),
      Atom(dwarf::DW_ATOM_type_flags, dwarf::DW_FORM_data1)}
Definition at line 348 of file AccelTable.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp