LLVM: llvm::Function::ProfileCount Class Reference
llvm::Function::ProfileCount Class Reference
Class to represent profile counts.
#include "llvm/IR/Function.h"
Public Member Functions
ProfileCount ()
ProfileCount (uint64_t Count, ProfileCountType PCT)
bool hasValue () const
uint64_t getCount () const
ProfileCountType getType () const
bool isSynthetic () const
operator bool ()
bool operator! () const
ProfileCount & setCount (uint64_t C)
Static Public Member Functions
static ProfileCount getInvalid ()
Detailed Description
Class to represent profile counts.
This class represents both real and synthetic profile counts.
Definition at line 260 of file Function.h.
Constructor & Destructor Documentation
ProfileCount() [1/2]
llvm::Function::ProfileCount::ProfileCount () inline
Definition at line 267 of file Function.h.
Referenced by getInvalid().
ProfileCount() [2/2]
llvm::Function::ProfileCount::ProfileCount (uint64_t Count, ProfileCountType PCT) inline
Definition at line 268 of file Function.h.
Member Function Documentation
getCount()
uint64_t llvm::Function::ProfileCount::getCount () const inline
Definition at line 271 of file Function.h.
Referenced by llvm::Function::setEntryCount(), and updateCallProfile().
getInvalid()
static ProfileCount llvm::Function::ProfileCount::getInvalid () inline static
Definition at line 281 of file Function.h.
References llvm::Function::PCT_Invalid, and ProfileCount().
Referenced by llvm::Function::getEntryCount().
getType()
ProfileCountType llvm::Function::ProfileCount::getType () const inline
Definition at line 272 of file Function.h.
Referenced by llvm::Function::setEntryCount().
hasValue()
bool llvm::Function::ProfileCount::hasValue () const inline
Definition at line 270 of file Function.h.
References llvm::Function::PCT_Invalid.
Referenced by llvm::Function::hasProfileData(), operator bool(), operator!(), llvm::Function::setEntryCount(), and updateCallProfile().
isSynthetic()
bool llvm::Function::ProfileCount::isSynthetic () const inline
Definition at line 273 of file Function.h.
References llvm::Function::PCT_Synthetic.
Referenced by llvm::Function::setEntryCount(), and updateCallProfile().
operator bool()
llvm::Function::ProfileCount::operator bool () inline explicit
Definition at line 274 of file Function.h.
References hasValue().
operator!()
bool llvm::Function::ProfileCount::operator! () const inline
Definition at line 275 of file Function.h.
References hasValue().
setCount()
ProfileCount & llvm::Function::ProfileCount::setCount (uint64_t C) inline
Definition at line 277 of file Function.h.
The documentation for this class was generated from the following file:
include/llvm/IR/Function.h