LLVM: llvm::MCContext Class Reference
llvm::MCContext Class Reference
Context object for machine code objects.
#include "llvm/MC/MCContext.h"
Public Types
using SymbolTable = StringMap< MCSymbol *, BumpPtrAllocator & >
Public Member Functions
MCContext (const MCAsmInfo *MAI, const MCRegisterInfo *MRI, const MCObjectFileInfo *MOFI, const SourceMgr *Mgr=nullptr, bool DoAutoReset=true)
MCContext (const MCContext &)=delete
MCContext & operator= (const MCContext &)=delete
~MCContext ()
const SourceMgr * getSourceManager () const
void setInlineSourceManager (SourceMgr *SM)
const MCAsmInfo * getAsmInfo () const
const MCRegisterInfo * getRegisterInfo () const
const MCObjectFileInfo * getObjectFileInfo () const
CodeViewContext & getCVContext ()
void setAllowTemporaryLabels (bool Value)
void setUseNamesOnTempLabels (bool Value)
char * getSecureLogFile ()
raw_fd_ostream * getSecureLog ()
void setSecureLog (std::unique_ptr< raw_fd_ostream > Value)
bool getSecureLogUsed ()
void setSecureLogUsed (bool Value)
void * allocate (unsigned Size, unsigned Align=8)
void deallocate (void *Ptr)
bool hadError ()
void reportError (SMLoc L, const Twine &Msg)
LLVM_ATTRIBUTE_NORETURN void reportFatalError (SMLoc L, const Twine &Msg)
const MCAsmMacro * lookupMacro (StringRef Name)
void defineMacro (StringRef Name, MCAsmMacro Macro)
void undefineMacro (StringRef Name)
Module Lifetime Management
void reset ()
reset - return object to right after construction state to prepare to process a new module
Symbol Management
MCSymbol * createLinkerPrivateTempSymbol ()
Create and return a new linker temporary symbol with a unique but unspecified name.
MCSymbol * createTempSymbol (bool CanBeUnnamed=true)
Create and return a new assembler temporary symbol with a unique but unspecified name.
MCSymbol * createTempSymbol (const Twine &Name, bool AlwaysAddSuffix, bool CanBeUnnamed=true)
MCSymbol * createDirectionalLocalSymbol (unsigned LocalLabelVal)
Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
MCSymbol * getDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
MCSymbol * getOrCreateSymbol (const Twine &Name)
Lookup the symbol inside with the specified Name.
MCSymbol * getOrCreateFrameAllocSymbol (StringRef FuncName, unsigned Idx)
Gets a symbol that will be defined to the final stack offset of a local variable after codegen.
MCSymbol * getOrCreateParentFrameOffsetSymbol (StringRef FuncName)
MCSymbol * getOrCreateLSDASymbol (StringRef FuncName)
MCSymbol * lookupSymbol (const Twine &Name) const
Get the symbol for Name, or null.
void setSymbolValue (MCStreamer &Streamer, StringRef Sym, uint64_t Val)
Set value for a symbol.
const SymbolTable & getSymbols () const
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols.
MCSymbol * getInlineAsmLabel (StringRef Name) const
isInlineAsmLabel - Return true if the name is a label referenced in inline assembly.
void registerInlineAsmLabel (MCSymbol *Sym)
registerInlineAsmLabel - Records that the name is a label referenced in inline assembly.
Dwarf Management
StringRef getCompilationDir () const
Get the compilation directory for DW_AT_comp_dir The compilation directory should be set with setCompilationDir before calling this function.
void setCompilationDir (StringRef S)
Set the compilation directory for DW_AT_comp_dir.
void addDebugPrefixMapEntry (const std::string &From, const std::string &To)
Add an entry to the debug prefix map.
void RemapDebugPaths ()
const std::string & getMainFileName () const
Get the main file name for use in error messages and debug info.
void setMainFileName (StringRef S)
Set the main file name and override the default.
Expected< unsigned > getDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID)
Creates an entry in the dwarf file and directory tables.
bool isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID=0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
const std::map< unsigned, MCDwarfLineTable > & getMCDwarfLineTables () const
MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID)
const MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID) const
const SmallVectorImpl< MCDwarfFile > & getMCDwarfFiles (unsigned CUID=0)
const SmallVectorImpl< std::string > & getMCDwarfDirs (unsigned CUID=0)
unsigned getDwarfCompileUnitID ()
void setDwarfCompileUnitID (unsigned CUIndex)
void setMCLineTableRootFile (unsigned CUID, StringRef CompilationDir, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source)
Specifies the "root" file and directory of the compilation unit.
bool isDwarfMD5UsageConsistent (unsigned CUID) const
Reports whether MD5 checksum usage is consistent (all-or-none).
void setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator)
Saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen.
void clearDwarfLocSeen ()
bool getDwarfLocSeen ()
const MCDwarfLoc & getCurrentDwarfLoc ()
bool getGenDwarfForAssembly ()
void setGenDwarfForAssembly (bool Value)
unsigned getGenDwarfFileNumber ()
void setGenDwarfFileNumber (unsigned FileNumber)
void setGenDwarfRootFile (StringRef FileName, StringRef Buffer)
Specifies information about the "root file" for assembler clients (e.g., llvm-mc).
const SetVector< MCSection * > & getGenDwarfSectionSyms ()
bool addGenDwarfSection (MCSection *Sec)
void finalizeDwarfSections (MCStreamer &MCOS)
Remove empty sections from SectionsForRanges, to avoid generating useless debug info for them.
const std::vector< MCGenDwarfLabelEntry > & getMCGenDwarfLabelEntries () const
void addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry &E)
void setDwarfDebugFlags (StringRef S)
StringRef getDwarfDebugFlags ()
void setDwarfDebugProducer (StringRef S)
StringRef getDwarfDebugProducer ()
dwarf::DwarfFormat getDwarfFormat () const
void setDwarfVersion (uint16_t v)
uint16_t getDwarfVersion () const
Section Management
enum : unsigned { GenericSectionID = ~0U }
MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K, const char *BeginSymName=nullptr)
Return the MCSection for the specified mach-o section.
MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K, const char *BeginSymName=nullptr)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine &Group)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine &Group, unsigned UniqueID)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine &Group, unsigned UniqueID, const MCSymbolELF *Associated)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF *Group, unsigned UniqueID, const MCSymbolELF *Associated)
MCSectionELF * getELFNamedSection (const Twine &Prefix, const Twine &Suffix, unsigned Type, unsigned Flags, unsigned EntrySize=0)
Get a section with the provided group identifier.
MCSectionELF * createELFRelSection (const Twine &Name, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF *Group, const MCSectionELF *RelInfoSection)
void renameELFSection (MCSectionELF *Section, StringRef Name)
MCSectionELF * createELFGroupSection (const MCSymbolELF *Group)
MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, unsigned UniqueID=GenericSectionID, const char *BeginSymName=nullptr)
MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, const char *BeginSymName=nullptr)
MCSectionCOFF * getAssociativeCOFFSection (MCSectionCOFF *Sec, const MCSymbol *KeySym, unsigned UniqueID=GenericSectionID)
Gets or creates a section equivalent to Sec that is associated with the section containing KeySym.
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, const char *BeginSymName)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, const Twine &Group, unsigned UniqueID)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, const Twine &Group, unsigned UniqueID, const char *BeginSymName)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, const MCSymbolWasm *Group, unsigned UniqueID, const char *BeginSymName)
MCSectionXCOFF * getXCOFFSection (StringRef Section, XCOFF::StorageMappingClass MappingClass, SectionKind K, const char *BeginSymName=nullptr)
MCSubtargetInfo & getSubtargetCopy (const MCSubtargetInfo &STI)
Detailed Description
Context object for machine code objects.
This class owns all of the sections that it creates.
Definition at line 64 of file MCContext.h.
Member Typedef Documentation
SymbolTable
using llvm::MCContext::SymbolTable = StringMap<MCSymbol *, BumpPtrAllocator &>
Definition at line 66 of file MCContext.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
GenericSectionID
Pass this value as the UniqueID during section creation to get the generic section with the given name and characteristics.
The usual sections such as .text use this ID.
Definition at line 398 of file MCContext.h.
Constructor & Destructor Documentation
MCContext() [1/2]
MCContext::MCContext (const MCAsmInfo * MAI, const MCRegisterInfo * MRI, const MCObjectFileInfo * MOFI, const SourceMgr * Mgr = nullptr, bool DoAutoReset = true) explicit
Definition at line 59 of file MCContext.cpp.
References Allocator, and AsSecureLogFileName().
MCContext() [2/2]
llvm::MCContext::MCContext (const MCContext &) delete
~MCContext()
MCContext::~MCContext ()
Definition at line 74 of file MCContext.cpp.
References reset().
Member Function Documentation
addDebugPrefixMapEntry()
void MCContext::addDebugPrefixMapEntry (const std::string & From, const std::string & To)
Add an entry to the debug prefix map.
Definition at line 574 of file MCContext.cpp.
References From.
addGenDwarfSection()
bool llvm::MCContext::addGenDwarfSection (MCSection * Sec) inline
Definition at line 627 of file MCContext.h.
References llvm::SetVector< T, Vector, Set >::insert().
addMCGenDwarfLabelEntry()
void llvm::MCContext::addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry & E) inline
Definition at line 637 of file MCContext.h.
References E.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
allocate()
void * llvm::MCContext::allocate (unsigned Size, unsigned Align = 8) inline
Definition at line 667 of file MCContext.h.
References Allocator, and Size.
clearDwarfLocSeen()
void llvm::MCContext::clearDwarfLocSeen () inline
Definition at line 606 of file MCContext.h.
Referenced by llvm::MCObjectStreamer::changeSectionImpl(), and llvm::MCDwarfLineEntry::Make().
createDirectionalLocalSymbol()
MCSymbol * MCContext::createDirectionalLocalSymbol (unsigned LocalLabelVal)
Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
Definition at line 251 of file MCContext.cpp.
createELFGroupSection()
MCSectionELF * MCContext::createELFGroupSection (const MCSymbolELF * Group)
Definition at line 428 of file MCContext.cpp.
References llvm::SectionKind::getReadOnly(), and llvm::ELF::SHT_GROUP.
createELFRelSection()
MCSectionELF * MCContext::createELFRelSection (const Twine & Name, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF * Group, const MCSectionELF * RelInfoSection)
Definition at line 364 of file MCContext.cpp.
References llvm::MCSection::getBeginSymbol(), llvm::SectionKind::getReadOnly(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and Name.
createLinkerPrivateTempSymbol()
MCSymbol * MCContext::createLinkerPrivateTempSymbol ()
Create and return a new linker temporary symbol with a unique but unspecified name.
Definition at line 219 of file MCContext.cpp.
References llvm::MCAsmInfo::getLinkerPrivateGlobalPrefix().
createTempSymbol() [1/2]
MCSymbol * MCContext::createTempSymbol (bool CanBeUnnamed = true)
Create and return a new assembler temporary symbol with a unique but unspecified name.
Definition at line 225 of file MCContext.cpp.
References createTempSymbol().
Referenced by llvm::MachineFunction::addCodeViewHeapAllocSite(), llvm::CodeViewContext::addFile(), llvm::MachineFunction::addLandingPad(), ARM64EmitUnwindInfo(), llvm::DebugHandlerBase::beginInstruction(), llvm::BTFDebug::beginInstruction(), createTempSymbol(), llvm::AsmPrinter::createTempSymbol(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MipsELFStreamer::EmitCFIEndProcImpl(), llvm::MipsELFStreamer::EmitCFILabel(), llvm::MipsELFStreamer::EmitCFIStartProcImpl(), llvm::MCObjectStreamer::EmitCVLocDirective(), emitDirectiveRelocJalr(), llvm::CodeViewContext::emitFileChecksums(), EmitGenDwarfInfo(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitNop(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CodeViewContext::emitStringTable(), EmitUnwindInfo(), llvm::AsmPrinter::emitXRayTable(), llvm::DebugHandlerBase::endInstruction(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), getCOFFSection(), llvm::MCSection::getEndSymbol(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), getMachOSection(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), getXCOFFSection(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::MCDwarfLineEntry::Make(), llvm::MCGenDwarfLabelEntry::Make(), and llvm::FaultMaps::recordFaultingOp().
createTempSymbol() [2/2]
MCSymbol * MCContext::createTempSymbol (const Twine & Name, bool AlwaysAddSuffix, bool CanBeUnnamed = true)
Definition at line 212 of file MCContext.cpp.
References llvm::MCAsmInfo::getPrivateGlobalPrefix(), and Name.
deallocate()
void llvm::MCContext::deallocate (void * Ptr) inline
Definition at line 671 of file MCContext.h.
defineMacro()
void llvm::MCContext::defineMacro (StringRef Name, MCAsmMacro Macro) inline
Definition at line 686 of file MCContext.h.
References llvm::Macro, and Name.
finalizeDwarfSections()
void MCContext::finalizeDwarfSections (MCStreamer & MCOS)
Remove empty sections from SectionsForRanges, to avoid generating useless debug info for them.
Definition at line 670 of file MCContext.cpp.
References llvm::MCStreamer::mayHaveInstructions().
Referenced by llvm::MCGenDwarfInfo::Emit().
getAsmInfo()
const MCAsmInfo * llvm::MCContext::getAsmInfo () const inline
Definition at line 313 of file MCContext.h.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::MCTargetStreamer::changeSection(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::EmitCFIStartProc(), EmitDwarfLineTable(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::ARMTargetStreamer::emitInst(), llvm::MCStreamer::EmitIntValue(), EmitPersonality(), llvm::MCTargetStreamer::emitRawBytes(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitValue(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::MCStreamer::EnsureValidWinFrameInfo(), getDataAlignmentFactor(), llvm::MCStreamer::getDwarfLineTableSymbol(), getRelocType32(), getRelocType64(), getSizeForEncoding(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::MCELFStreamer::InitSections(), and llvm::MCDwarfLineStr::MCDwarfLineStr().
getAssociativeCOFFSection()
MCSectionCOFF * MCContext::getAssociativeCOFFSection (MCSectionCOFF * Sec, const MCSymbol * KeySym, unsigned UniqueID = GenericSectionID)
Gets or creates a section equivalent to Sec that is associated with the section containing KeySym.
For example, to create a debug info section associated with an inline function, pass the normal debug info section as Sec and the function symbol as KeySym.
Definition at line 474 of file MCContext.cpp.
References Characteristics, GenericSectionID, llvm::MCSectionCOFF::getCharacteristics(), getCOFFSection(), llvm::MCSection::getKind(), llvm::MCSymbol::getName(), llvm::MCSectionCOFF::getSectionName(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
Referenced by getCOFFStaticStructorSection().
getCOFFSection() [1/2]
MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, const char * BeginSymName = nullptr)
Definition at line 466 of file MCContext.cpp.
References Characteristics, GenericSectionID, and getCOFFSection().
Referenced by getCOFFSection().
getCOFFSection() [2/2]
MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, unsigned UniqueID = GenericSectionID, const char * BeginSymName = nullptr)
Definition at line 434 of file MCContext.cpp.
References Characteristics, createTempSymbol(), llvm::StringRef::empty(), llvm::MCSymbol::getName(), getOrCreateSymbol(), and Selection.
Referenced by llvm::AsmPrinter::doFinalization(), getAssociativeCOFFSection(), getCOFFStaticStructorSection(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::Initialize(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCompilationDir()
StringRef llvm::MCContext::getCompilationDir () const inline
Get the compilation directory for DW_AT_comp_dir The compilation directory should be set with setCompilationDir before calling this function.
If it is unset, an empty string will be returned.
Definition at line 520 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), and setGenDwarfRootFile().
getCurrentDwarfLoc()
const MCDwarfLoc & llvm::MCContext::getCurrentDwarfLoc () inline
Definition at line 609 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::Make().
getCVContext()
CodeViewContext & MCContext::getCVContext ()
Definition at line 675 of file MCContext.cpp.
Referenced by llvm::MCStreamer::checkCVLocSection(), llvm::MCObjectStreamer::EmitCVDefRangeDirective(), llvm::MCObjectStreamer::EmitCVFileChecksumOffsetDirective(), llvm::MCObjectStreamer::EmitCVFileChecksumsDirective(), llvm::MCStreamer::EmitCVFileDirective(), llvm::MCStreamer::EmitCVFuncIdDirective(), llvm::MCObjectStreamer::EmitCVInlineLinetableDirective(), llvm::MCStreamer::EmitCVInlineSiteIdDirective(), llvm::MCObjectStreamer::EmitCVLinetableDirective(), llvm::MCObjectStreamer::EmitCVLocDirective(), and llvm::MCObjectStreamer::EmitCVStringTableDirective().
getDirectionalLocalSymbol()
MCSymbol * MCContext::getDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
Definition at line 256 of file MCContext.cpp.
getDwarfCompileUnitID()
unsigned llvm::MCContext::getDwarfCompileUnitID () inline
Definition at line 569 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::Make().
getDwarfDebugFlags()
StringRef llvm::MCContext::getDwarfDebugFlags () inline
Definition at line 642 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), and EmitGenDwarfInfo().
getDwarfDebugProducer()
StringRef llvm::MCContext::getDwarfDebugProducer () inline
Definition at line 645 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
getDwarfFile()
Expected< unsigned > MCContext::getDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID)
Creates an entry in the dwarf file and directory tables.
getDwarfFile - takes a file name and number to place in the dwarf file and directory tables.
If the file number has already been allocated it is an error and zero is returned and the client reports the error, else the allocated file number is returned. The file numbers may be in any order.
Definition at line 645 of file MCContext.cpp.
References llvm::MCDwarfLineTable::tryGetFile().
Referenced by llvm::MCStreamer::tryEmitDwarfFileDirective().
getDwarfFormat()
dwarf::DwarfFormat llvm::MCContext::getDwarfFormat () const inline
Definition at line 647 of file MCContext.h.
References llvm::dwarf::DWARF32.
getDwarfLocSeen()
bool llvm::MCContext::getDwarfLocSeen () inline
Definition at line 608 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::Make().
getDwarfVersion()
uint16_t llvm::MCContext::getDwarfVersion () const inline
Definition at line 653 of file MCContext.h.
Referenced by llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfLineTableHeader::Emit(), EmitDwarfLineTable(), EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), isValidDwarfFileNumber(), and setGenDwarfRootFile().
getELFNamedSection()
MCSectionELF * MCContext::getELFNamedSection (const Twine & Prefix, const Twine & Suffix, unsigned Type, unsigned Flags, unsigned EntrySize = 0)
Get a section with the provided group identifier.
This section is named by concatenating Prefix with '.' then Suffix. The Type describes the type of the section and Flags are used to further configure this named section.
Definition at line 378 of file MCContext.cpp.
References getELFSection().
Referenced by llvm::TargetLoweringObjectFileELF::emitPersonalityValue().
getELFSection() [1/5]
MCSectionELF * llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags) inline
Definition at line 419 of file MCContext.h.
References getELFSection().
Referenced by llvm::AsmPrinter::doFinalization(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitIdent(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::AsmPrinter::emitXRayTable(), getELFNamedSection(), getELFSection(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getSectionForCommandLines(), llvm::MCObjectFileInfo::getStackSizesSection(), getStaticStructorSection(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::AVRTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::LanaiTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::RISCVELFTargetObjectFile::Initialize(), llvm::XCoreTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), selectELFSectionForGlobal(), and smallData().
getELFSection() [2/5]
MCSectionELF * MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF * Group, unsigned UniqueID, const MCSymbolELF * Associated)
Definition at line 397 of file MCContext.cpp.
References llvm::SectionKind::getExecuteOnly(), llvm::MCSymbol::getName(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getText(), llvm::ELF::SHF_ARM_PURECODE, and llvm::ELF::SHF_EXECINSTR.
getELFSection() [3/5]
MCSectionELF * llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine & Group) inline
Definition at line 424 of file MCContext.h.
References getELFSection().
getELFSection() [4/5]
MCSectionELF * llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine & Group, unsigned UniqueID) inline
Definition at line 430 of file MCContext.h.
References getELFSection().
getELFSection() [5/5]
MCSectionELF * MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine & Group, unsigned UniqueID, const MCSymbolELF * Associated)
Definition at line 385 of file MCContext.cpp.
References getELFSection(), getOrCreateSymbol(), llvm::Twine::isTriviallyEmpty(), and llvm::Twine::str().
getGenDwarfFileNumber()
unsigned llvm::MCContext::getGenDwarfFileNumber () inline
Definition at line 613 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
getGenDwarfForAssembly()
bool llvm::MCContext::getGenDwarfForAssembly () inline
Definition at line 611 of file MCContext.h.
getGenDwarfSectionSyms()
const SetVector< MCSection * > & llvm::MCContext::getGenDwarfSectionSyms () inline
Definition at line 623 of file MCContext.h.
Referenced by llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), and llvm::MCGenDwarfLabelEntry::Make().
getInlineAsmLabel()
MCSymbol * llvm::MCContext::getInlineAsmLabel (StringRef Name) const inline
isInlineAsmLabel - Return true if the name is a label referenced in inline assembly.
Definition at line 385 of file MCContext.h.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup(), and Name.
getMachOSection() [1/2]
MCSectionMachO * llvm::MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K, const char * BeginSymName = nullptr) inline
Definition at line 412 of file MCContext.h.
References getMachOSection().
getMachOSection() [2/2]
MCSectionMachO * MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K, const char * BeginSymName = nullptr)
Return the MCSection for the specified mach-o section.
This requires the operands to be valid.
Definition at line 285 of file MCContext.cpp.
References createTempSymbol(), and Name.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), emitNonLazyStubs(), llvm::AsmPrinter::emitXRayTable(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), getMachOSection(), and llvm::TargetLoweringObjectFileMachO::Initialize().
getMainFileName()
const std::string & llvm::MCContext::getMainFileName () const inline
Get the main file name for use in error messages and debug info.
This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
Definition at line 534 of file MCContext.h.
Referenced by setGenDwarfRootFile().
getMCDwarfDirs()
const SmallVectorImpl< std::string > & llvm::MCContext::getMCDwarfDirs (unsigned CUID = 0) inline
Definition at line 565 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfDirs(), and getMCDwarfLineTable().
Referenced by EmitGenDwarfInfo().
getMCDwarfFiles()
const SmallVectorImpl< MCDwarfFile > & llvm::MCContext::getMCDwarfFiles (unsigned CUID = 0) inline
Definition at line 561 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfFiles(), and getMCDwarfLineTable().
Referenced by EmitGenDwarfInfo().
getMCDwarfLineTable() [1/2]
MCDwarfLineTable & llvm::MCContext::getMCDwarfLineTable (unsigned CUID) inline
Definition at line 551 of file MCContext.h.
Referenced by EmitGenDwarfInfo(), llvm::MCStreamer::getDwarfLineTableSymbol(), getMCDwarfDirs(), getMCDwarfFiles(), isDwarfMD5UsageConsistent(), isValidDwarfFileNumber(), llvm::MCDwarfLineEntry::Make(), and setMCLineTableRootFile().
getMCDwarfLineTable() [2/2]
const MCDwarfLineTable & llvm::MCContext::getMCDwarfLineTable (unsigned CUID) const inline
Definition at line 555 of file MCContext.h.
References assert(), and I.
getMCDwarfLineTables()
const std::map< unsigned, MCDwarfLineTable > & llvm::MCContext::getMCDwarfLineTables () const inline
Definition at line 547 of file MCContext.h.
Referenced by llvm::MCDwarfLineTable::Emit().
getMCGenDwarfLabelEntries()
const std::vector< MCGenDwarfLabelEntry > & llvm::MCContext::getMCGenDwarfLabelEntries () const inline
Definition at line 633 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
getObjectFileInfo()
const MCObjectFileInfo * llvm::MCContext::getObjectFileInfo () const inline
Definition at line 317 of file MCContext.h.
Referenced by llvm::MCTargetStreamer::changeSection(), llvm::NVPTXTargetStreamer::changeSection(), llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), EmitDwarfLineTable(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::AsmPrinter::emitRemarksSection(), llvm::MCDwarfLineStr::emitSection(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::WinCFGuard::endModule(), llvm::MipsTargetELFStreamer::finish(), llvm::MCELFStreamer::InitSections(), llvm::MCDwarfLineStr::MCDwarfLineStr(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::FaultMaps::serializeToFaultMapSection(), and llvm::StackMaps::serializeToStackMapSection().
getOrCreateFrameAllocSymbol()
MCSymbol * MCContext::getOrCreateFrameAllocSymbol (StringRef FuncName, unsigned Idx)
Gets a symbol that will be defined to the final stack offset of a local variable after codegen.
Parameters
Idx - The index of a local variable passed to @llvm.localescape.
Definition at line 142 of file MCContext.cpp.
References getOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), and Idx.
getOrCreateLSDASymbol()
MCSymbol * MCContext::getOrCreateLSDASymbol (StringRef FuncName)
Definition at line 153 of file MCContext.cpp.
References getOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
getOrCreateParentFrameOffsetSymbol()
MCSymbol * MCContext::getOrCreateParentFrameOffsetSymbol (StringRef FuncName)
Definition at line 148 of file MCContext.cpp.
References getOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
Referenced by recoverFramePointer().
getOrCreateSymbol()
MCSymbol * MCContext::getOrCreateSymbol (const Twine & Name)
Lookup the symbol inside with the specified Name.
If it exists, return it. If not, create a forward reference and return it.
Parameters
Name - The symbol name, which must be unique across all symbols.
Definition at line 129 of file MCContext.cpp.
References assert(), llvm::StringRef::empty(), and Name.
Referenced by llvm::MipsTargetLowering::AdjustInstrPostInstrSelection(), llvm::AsmPrinter::doFinalization(), EmitCamlGlobal(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::RecordStreamer::flushSymverDirectives(), getBFLabel(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), getCOFFSection(), llvm::LanaiMCInstLower::GetConstantPoolIndexSymbol(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::ARMAsmPrinter::GetCPISymbol(), llvm::MCStreamer::getDwarfLineTableSymbol(), getELFSection(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::PPCFunctionInfo::getGlobalEPSymbol(), llvm::MachineFunction::getJTISymbol(), llvm::AsmPrinter::GetJTSetSymbol(), llvm::LanaiMCInstLower::GetJumpTableSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::PPCFunctionInfo::getLocalEPSymbol(), getMCSymbolForMBB(), getOrCreateFrameAllocSymbol(), getOrCreateLSDASymbol(), getOrCreateParentFrameOffsetSymbol(), llvm::MachineFunction::getPICBaseSymbol(), getPICLabel(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetMachine::getSymbol(), GetSymbolFromOperand(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::PPCFunctionInfo::getTOCOffsetSymbol(), getWasmSection(), llvm::FastISel::lowerCallTo(), llvm::MCParserUtils::parseAssignmentExpression(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), llvm::FastISel::CallLoweringInfo::setCallee(), setSymbolValue(), smallData(), llvm::AMDGPUSymbolizer::tryAddingSymbolicOperand(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
getRegisterInfo()
const MCRegisterInfo * llvm::MCContext::getRegisterInfo () const inline
Definition at line 315 of file MCContext.h.
References MRI.
Referenced by llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::MipsMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::AMDGPUDisassembler::getRegClassName(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
getSecureLog()
raw_fd_ostream * llvm::MCContext::getSecureLog () inline
Definition at line 658 of file MCContext.h.
getSecureLogFile()
char * llvm::MCContext::getSecureLogFile () inline
Definition at line 657 of file MCContext.h.
getSecureLogUsed()
bool llvm::MCContext::getSecureLogUsed () inline
Definition at line 664 of file MCContext.h.
getSourceManager()
const SourceMgr * llvm::MCContext::getSourceManager () const inline
Definition at line 309 of file MCContext.h.
References llvm::SrcMgr.
Referenced by llvm::MCObjectStreamer::emitFill(), llvm::HexagonShuffler::reportError(), llvm::HexagonMCChecker::reportNote(), and llvm::HexagonMCChecker::reportWarning().
getSubtargetCopy()
MCSubtargetInfo & MCContext::getSubtargetCopy (const MCSubtargetInfo & STI)
Definition at line 570 of file MCContext.cpp.
Referenced by llvm::MCTargetAsmParser::copySTI(), and llvm::AsmPrinter::doInitialization().
getSymbols()
const SymbolTable & llvm::MCContext::getSymbols () const inline
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols.
'const' because we still want any modifications to the table itself to use the MCContext APIs.
Definition at line 381 of file MCContext.h.
Referenced by llvm::WebAssemblyAsmPrinter::EmitEndOfAsmFile().
getWasmSection() [1/5]
MCSectionWasm * llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K) inline
Definition at line 482 of file MCContext.h.
References getWasmSection().
Referenced by llvm::WebAssemblyAsmPrinter::EmitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getStaticCtorSection(), getWasmSection(), llvm::TargetLoweringObjectFileWasm::InitializeWasm(), and selectWasmSectionForGlobal().
getWasmSection() [2/5]
MCSectionWasm * llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K, const char * BeginSymName) inline
Definition at line 486 of file MCContext.h.
References getWasmSection().
getWasmSection() [3/5]
MCSectionWasm * MCContext::getWasmSection (const Twine & Section, SectionKind K, const MCSymbolWasm * Group, unsigned UniqueID, const char * BeginSymName)
Definition at line 507 of file MCContext.cpp.
References F, llvm::MCSymbol::getName(), llvm::MCSymbol::setFragment(), and llvm::wasm::WASM_SYMBOL_TYPE_SECTION.
getWasmSection() [4/5]
MCSectionWasm * llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K, const Twine & Group, unsigned UniqueID) inline
Definition at line 491 of file MCContext.h.
References getWasmSection().
getWasmSection() [5/5]
MCSectionWasm * MCContext::getWasmSection (const Twine & Section, SectionKind K, const Twine & Group, unsigned UniqueID, const char * BeginSymName)
Definition at line 495 of file MCContext.cpp.
References getOrCreateSymbol(), getWasmSection(), llvm::Twine::isTriviallyEmpty(), llvm::MCSymbolWasm::setComdat(), and llvm::Twine::str().
getXCOFFSection()
MCSectionXCOFF * MCContext::getXCOFFSection (StringRef Section, XCOFF::StorageMappingClass MappingClass, SectionKind K, const char * BeginSymName = nullptr)
Definition at line 538 of file MCContext.cpp.
References createTempSymbol(), F, and llvm::MCSymbol::setFragment().
hadError()
bool llvm::MCContext::hadError () inline
Definition at line 673 of file MCContext.h.
Referenced by llvm::MCAssembler::layout().
isDwarfMD5UsageConsistent()
bool llvm::MCContext::isDwarfMD5UsageConsistent (unsigned CUID) const inline
Reports whether MD5 checksum usage is consistent (all-or-none).
Definition at line 586 of file MCContext.h.
References getMCDwarfLineTable(), and llvm::MCDwarfLineTable::isMD5UsageConsistent().
isValidDwarfFileNumber()
bool MCContext::isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID = 0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
Definition at line 658 of file MCContext.cpp.
References getDwarfVersion(), llvm::MCDwarfLineTable::getMCDwarfFiles(), and getMCDwarfLineTable().
lookupMacro()
const MCAsmMacro * llvm::MCContext::lookupMacro (StringRef Name) inline
Definition at line 681 of file MCContext.h.
References I, and Name.
lookupSymbol()
MCSymbol * MCContext::lookupSymbol (const Twine & Name) const
Get the symbol for Name, or null.
Definition at line 264 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup(), and Name.
Referenced by llvm::WasmException::endModule(), and llvm::MCParserUtils::parseAssignmentExpression().
operator=()
MCContext & llvm::MCContext::operator= (const MCContext &) delete
registerInlineAsmLabel()
void MCContext::registerInlineAsmLabel (MCSymbol * Sym)
registerInlineAsmLabel - Records that the name is a label referenced in inline assembly.
Definition at line 277 of file MCContext.cpp.
References llvm::MCSymbol::getName().
Referenced by EmitGCCInlineAsmStr().
RemapDebugPaths()
void MCContext::RemapDebugPaths ()
Definition at line 579 of file MCContext.cpp.
References llvm::StringRef::startswith(), and llvm::SmallString< InternalLen >::str().
Referenced by llvm::MCObjectStreamer::FinishImpl().
renameELFSection()
void MCContext::renameELFSection (MCSectionELF * Section, StringRef Name)
Definition at line 313 of file MCContext.cpp.
References I, and Name.
reportError()
void MCContext::reportError (SMLoc L, const Twine & Msg)
Definition at line 685 of file MCContext.cpp.
References llvm::SourceMgr::DK_Error, and llvm::report_fatal_error().
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), adjustFixupValue(), llvm::MCStreamer::checkCVLocSection(), checkIs32(), llvm::MCAssembler::computeFragmentSize(), llvm::MCStreamer::EmitCFIStartProc(), llvm::MCStreamer::EmitCVInlineSiteIdDirective(), llvm::AMDGPUAsmPrinter::EmitGlobalVariable(), llvm::MCStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MCStreamer::EmitWinCFIAllocStack(), llvm::MCStreamer::EmitWinCFIEndChained(), llvm::MCStreamer::EmitWinCFIEndProc(), llvm::MCStreamer::EmitWinCFIFuncletOrFuncEnd(), llvm::MCStreamer::EmitWinCFIPushFrame(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), llvm::MCStreamer::EmitWinCFISetFrame(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::MCStreamer::EmitWinEHHandler(), llvm::MCStreamer::EnsureValidWinFrameInfo(), llvm::MCStreamer::Finish(), llvm::MCAsmLayout::getBaseSymbol(), isNonILP32reloc(), llvm::HexagonMCChecker::reportError(), llvm::HexagonShuffler::reportError(), and reportFatalError().
reportFatalError()
void MCContext::reportFatalError (SMLoc L, const Twine & Msg)
Definition at line 699 of file MCContext.cpp.
References reportError(), and llvm::sys::RunInterruptHandlers().
Referenced by adjustFixupValue().
reset()
void MCContext::reset ()
reset - return object to right after construction state to prepare to process a new module
Definition at line 86 of file MCContext.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), DWARF2_FLAG_IS_STMT, and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
Referenced by llvm::MachineModuleInfo::doFinalization(), and ~MCContext().
setAllowTemporaryLabels()
void llvm::MCContext::setAllowTemporaryLabels (bool Value) inline
Definition at line 321 of file MCContext.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC().
setCompilationDir()
void llvm::MCContext::setCompilationDir (StringRef S) inline
Set the compilation directory for DW_AT_comp_dir.
Definition at line 523 of file MCContext.h.
References llvm::StringRef::str().
setCurrentDwarfLoc()
void llvm::MCContext::setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator) inline
Saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen.
When the next instruction is assembled an entry in the line number table with this information and the address of the instruction will be created.
Definition at line 594 of file MCContext.h.
References llvm::MCDwarfLoc::setColumn(), llvm::MCDwarfLoc::setDiscriminator(), llvm::MCDwarfLoc::setFileNum(), llvm::MCDwarfLoc::setFlags(), llvm::MCDwarfLoc::setIsa(), and llvm::MCDwarfLoc::setLine().
Referenced by llvm::MCStreamer::EmitDwarfLocDirective().
setDwarfCompileUnitID()
void llvm::MCContext::setDwarfCompileUnitID (unsigned CUIndex) inline
Definition at line 571 of file MCContext.h.
setDwarfDebugFlags()
void llvm::MCContext::setDwarfDebugFlags (StringRef S) inline
Definition at line 641 of file MCContext.h.
setDwarfDebugProducer()
void llvm::MCContext::setDwarfDebugProducer (StringRef S) inline
Definition at line 644 of file MCContext.h.
setDwarfVersion()
void llvm::MCContext::setDwarfVersion (uint16_t v) inline
Definition at line 652 of file MCContext.h.
setGenDwarfFileNumber()
void llvm::MCContext::setGenDwarfFileNumber (unsigned FileNumber) inline
Definition at line 615 of file MCContext.h.
setGenDwarfForAssembly()
void llvm::MCContext::setGenDwarfForAssembly (bool Value) inline
Definition at line 612 of file MCContext.h.
setGenDwarfRootFile()
void MCContext::setGenDwarfRootFile (StringRef FileName, StringRef Buffer)
Specifies information about the "root file" for assembler clients (e.g., llvm-mc).
Assumes compilation dir etc. have been set up.
Definition at line 605 of file MCContext.cpp.
References llvm::sys::path::append(), assert(), llvm::StringRef::consume_front(), llvm::StringRef::drop_front(), llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::empty(), llvm::MD5::final(), llvm::StringRef::front(), getCompilationDir(), getDwarfVersion(), getMainFileName(), llvm::sys::path::is_separator(), llvm::None, llvm::sys::path::remove_filename(), setMCLineTableRootFile(), and llvm::MD5::update().
setInlineSourceManager()
void llvm::MCContext::setInlineSourceManager (SourceMgr * SM) inline
Definition at line 311 of file MCContext.h.
setMainFileName()
void llvm::MCContext::setMainFileName (StringRef S) inline
Set the main file name and override the default.
Definition at line 537 of file MCContext.h.
setMCLineTableRootFile()
void llvm::MCContext::setMCLineTableRootFile (unsigned CUID, StringRef CompilationDir, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source) inline
Specifies the "root" file and directory of the compilation unit.
These are "file 0" and "directory 0" in DWARF v5.
Definition at line 577 of file MCContext.h.
References getMCDwarfLineTable(), and llvm::MCDwarfLineTable::setRootFile().
Referenced by llvm::MCStreamer::emitDwarfFile0Directive(), and setGenDwarfRootFile().
setSecureLog()
void llvm::MCContext::setSecureLog (std::unique_ptr< raw_fd_ostream > Value) inline
Definition at line 660 of file MCContext.h.
setSecureLogUsed()
void llvm::MCContext::setSecureLogUsed (bool Value) inline
Definition at line 665 of file MCContext.h.
setSymbolValue()
void MCContext::setSymbolValue (MCStreamer & Streamer, StringRef Sym, uint64_t Val)
Set value for a symbol.
Definition at line 270 of file MCContext.cpp.
References llvm::LiveRangeEdit::create(), llvm::MCStreamer::EmitAssignment(), and getOrCreateSymbol().
setUseNamesOnTempLabels()
void llvm::MCContext::setUseNamesOnTempLabels (bool Value) inline
Definition at line 322 of file MCContext.h.
undefineMacro()
void llvm::MCContext::undefineMacro (StringRef Name) inline
Definition at line 690 of file MCContext.h.
References Name.
The documentation for this class was generated from the following files:
include/llvm/MC/MCContext.h
lib/MC/MCContext.cpp