LLVM: llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator Class Reference
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator Class Reference
Iterator for PHI operands.
Public Member Functions
PHI_iterator (MachineInstr *P)
PHI_iterator (MachineInstr *P, bool)
PHI_iterator & operator++ ()
bool operator== (const PHI_iterator &x) const
bool operator!= (const PHI_iterator &x) const
unsigned getIncomingValue ()
MachineBasicBlock * getIncomingBlock ()
Detailed Description
Iterator for PHI operands.
Definition at line 252 of file MachineSSAUpdater.cpp.
Constructor & Destructor Documentation
PHI_iterator() [1/2]
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::PHI_iterator (MachineInstr * P) inline explicit
Definition at line 258 of file MachineSSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
PHI_iterator() [2/2]
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::PHI_iterator (MachineInstr * P, bool) inline
Definition at line 260 of file MachineSSAUpdater.cpp.
Member Function Documentation
getIncomingBlock()
MachineBasicBlock * llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingBlock () inline
Definition at line 269 of file MachineSSAUpdater.cpp.
References llvm::MachineOperand::getMBB(), and llvm::MachineInstr::getOperand().
getIncomingValue()
unsigned llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingValue () inline
Definition at line 267 of file MachineSSAUpdater.cpp.
References llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
operator!=()
bool llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator!= (const PHI_iterator & x) const inline
Definition at line 265 of file MachineSSAUpdater.cpp.
References operator==().
operator++()
PHI_iterator & llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator++ () inline
Definition at line 263 of file MachineSSAUpdater.cpp.
operator==()
bool llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator== (const PHI_iterator & x) const inline
Definition at line 264 of file MachineSSAUpdater.cpp.
Referenced by operator!=(), and llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator!=().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineSSAUpdater.cpp