LLVM: llvm::ReadyQueue Class Reference
llvm::ReadyQueue Class Reference
Helpers for implementing custom MachineSchedStrategy classes.
#include "llvm/CodeGen/MachineScheduler.h"
Public Types
using iterator = std::vector< SUnit * >::iterator
Public Member Functions
ReadyQueue (unsigned id, const Twine &name)
unsigned getID () const
StringRef getName () const
bool isInQueue (SUnit *SU) const
bool empty () const
void clear ()
unsigned size () const
iterator begin ()
iterator end ()
ArrayRef< SUnit * > elements ()
iterator find (SUnit *SU)
void push (SUnit *SU)
iterator remove (iterator I)
void dump () const
Detailed Description
Helpers for implementing custom MachineSchedStrategy classes.
These take care of the book-keeping associated with list scheduling heuristics. ReadyQueue encapsulates vector of "ready" SUnits with basic convenience methods for pushing and removing nodes. ReadyQueue's are uniquely identified by an ID. SUnit::NodeQueueId is a mask of the ReadyQueues the SUnit is in.
This is a convenience class that may be used by implementations of MachineSchedStrategy.
Definition at line 526 of file MachineScheduler.h.
Member Typedef Documentation
iterator
using llvm::ReadyQueue::iterator = std::vector<SUnit*>::iterator
Definition at line 547 of file MachineScheduler.h.
Constructor & Destructor Documentation
ReadyQueue()
llvm::ReadyQueue::ReadyQueue (unsigned id, const Twine & name) inline
Definition at line 532 of file MachineScheduler.h.
Member Function Documentation
begin()
iterator llvm::ReadyQueue::begin () inline
Definition at line 549 of file MachineScheduler.h.
Referenced by llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::ConvergingVLIWScheduler::readyQueueVerboseDump(), and llvm::SchedBoundary::releasePending().
clear()
void llvm::ReadyQueue::clear () inline
Definition at line 543 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::reset().
dump()
LLVM_DUMP_METHOD void ReadyQueue::dump () const
Definition at line 594 of file MachineScheduler.cpp.
References llvm::dbgs().
Referenced by llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), and llvm::SchedBoundary::pickOnlyChoice().
elements()
ArrayRef< SUnit * > llvm::ReadyQueue::elements () inline
Definition at line 553 of file MachineScheduler.h.
Referenced by computeRemLatency().
empty()
bool llvm::ReadyQueue::empty () const inline
Definition at line 541 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::pickNode(), llvm::PostGenericScheduler::pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), llvm::SchedBoundary::pickOnlyChoice(), and llvm::SchedBoundary::releasePending().
end()
iterator llvm::ReadyQueue::end () inline
Definition at line 551 of file MachineScheduler.h.
Referenced by llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), and llvm::ConvergingVLIWScheduler::readyQueueVerboseDump().
find()
iterator llvm::ReadyQueue::find (SUnit * SU) inline
Definition at line 555 of file MachineScheduler.h.
References llvm::find().
Referenced by llvm::SchedBoundary::removeReady().
getID()
unsigned llvm::ReadyQueue::getID () const inline
Definition at line 534 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::isTop(), llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), and llvm::ConvergingVLIWScheduler::SchedulingCost().
getName()
StringRef llvm::ReadyQueue::getName () const inline
Definition at line 536 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::bumpCycle(), llvm::SchedBoundary::bumpNode(), llvm::SchedBoundary::dumpScheduledState(), llvm::SchedBoundary::findMaxLatency(), llvm::SchedBoundary::getOtherResourceCount(), llvm::ConvergingVLIWScheduler::readyQueueVerboseDump(), llvm::GenericSchedulerBase::setPolicy(), and llvm::ConvergingVLIWScheduler::traceCandidate().
isInQueue()
bool llvm::ReadyQueue::isInQueue (SUnit * SU) const inline
Definition at line 539 of file MachineScheduler.h.
References llvm::SUnit::NodeQueueId.
Referenced by llvm::SchedBoundary::removeReady().
push()
void llvm::ReadyQueue::push (SUnit * SU) inline
Definition at line 557 of file MachineScheduler.h.
References llvm::SUnit::NodeQueueId.
Referenced by llvm::SchedBoundary::pickOnlyChoice(), llvm::SchedBoundary::releaseNode(), and llvm::SchedBoundary::releasePending().
remove()
iterator llvm::ReadyQueue::remove (iterator I) inline
Definition at line 562 of file MachineScheduler.h.
References I.
Referenced by llvm::SchedBoundary::pickOnlyChoice(), llvm::SchedBoundary::releasePending(), and llvm::SchedBoundary::removeReady().
size()
unsigned llvm::ReadyQueue::size () const inline
Definition at line 545 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::pickOnlyChoice(), llvm::SchedBoundary::releaseNode(), and llvm::SchedBoundary::releasePending().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp