LLVM: llvm::orc::LegacyLocalCXXRuntimeOverrides Class Reference
llvm::orc::LegacyLocalCXXRuntimeOverrides Class Reference
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Member Functions
template<typename MangleFtorT >
LLVM_ATTRIBUTE_DEPRECATED (LegacyLocalCXXRuntimeOverrides(const MangleFtorT &Mangle), "ORCv1 utilities (utilities with the 'Legacy' prefix) are deprecated. " "Please use the ORCv2 LocalCXXRuntimeOverrides utility instead")
Create a runtime-overrides class.
template<typename MangleFtorT >
LegacyLocalCXXRuntimeOverrides (ORCv1DeprecationAcknowledgement, const MangleFtorT &Mangle)
JITEvaluatedSymbol searchOverrides (const std::string &Name)
Search overrided symbols.
template<typename MangleFtorT >
LegacyLocalCXXRuntimeOverrides (const MangleFtorT &Mangle)
Public Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
void runDestructors ()
Run any destructors recorded by the overriden __cxa_atexit function (CXAAtExitOverride).
Additional Inherited Members
Protected Types inherited from llvm::orc::LocalCXXRuntimeOverridesBase
using DestructorPtr = void(*)(void *)
using CXXDestructorDataPair = std::pair< DestructorPtr, void * >
using CXXDestructorDataPairList = std::vector< CXXDestructorDataPair >
Protected Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
template<typename PtrTy >
JITTargetAddress toTargetAddress (PtrTy *P)
Static Protected Member Functions inherited from llvm::orc::LocalCXXRuntimeOverridesBase
static int CXAAtExitOverride (DestructorPtr Destructor, void *Arg, void *DSOHandle)
Protected Attributes inherited from llvm::orc::LocalCXXRuntimeOverridesBase
CXXDestructorDataPairList DSOHandleOverride
Detailed Description
Definition at line 191 of file ExecutionUtils.h.
Constructor & Destructor Documentation
LegacyLocalCXXRuntimeOverrides() [1/2]
template<typename MangleFtorT > llvm::orc::LegacyLocalCXXRuntimeOverrides::LegacyLocalCXXRuntimeOverrides (ORCv1DeprecationAcknowledgement , const MangleFtorT & Mangle) inline
Definition at line 201 of file ExecutionUtils.h.
References llvm::orc::LocalCXXRuntimeOverridesBase::CXAAtExitOverride(), llvm::orc::LocalCXXRuntimeOverridesBase::DSOHandleOverride, and llvm::orc::LocalCXXRuntimeOverridesBase::toTargetAddress().
LegacyLocalCXXRuntimeOverrides() [2/2]
template<typename MangleFtorT > llvm::orc::LegacyLocalCXXRuntimeOverrides::LegacyLocalCXXRuntimeOverrides (const MangleFtorT & Mangle)
Definition at line 224 of file ExecutionUtils.h.
References llvm::orc::LocalCXXRuntimeOverridesBase::CXAAtExitOverride(), llvm::orc::LocalCXXRuntimeOverridesBase::DSOHandleOverride, and llvm::orc::LocalCXXRuntimeOverridesBase::toTargetAddress().
Member Function Documentation
LLVM_ATTRIBUTE_DEPRECATED()
template<typename MangleFtorT > llvm::orc::LegacyLocalCXXRuntimeOverrides::LLVM_ATTRIBUTE_DEPRECATED (LegacyLocalCXXRuntimeOverrides(const MangleFtorT &Mangle) , "ORCv1 utilities (utilities with the 'Legacy' prefix) are deprecated. " "Please use the ORCv2 LocalCXXRuntimeOverrides utility instead")
Create a runtime-overrides class.
searchOverrides()
JITEvaluatedSymbol llvm::orc::LegacyLocalCXXRuntimeOverrides::searchOverrides (const std::string & Name) inline
Search overrided symbols.
Definition at line 208 of file ExecutionUtils.h.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::JITSymbolFlags::Exported, llvm::StringMap< ValueTy, AllocatorTy >::find(), I, and Name.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h