LLVM: llvm::ConnectedVNInfoEqClasses Class Reference
llvm::ConnectedVNInfoEqClasses Class Reference
ConnectedVNInfoEqClasses - Helper class that can divide VNInfos in a LiveInterval into equivalence clases of connected components.
#include "llvm/CodeGen/LiveInterval.h"
Public Member Functions
ConnectedVNInfoEqClasses (LiveIntervals &lis)
unsigned Classify (const LiveRange &LR)
Classify the values in LR into connected components.
unsigned getEqClass (const VNInfo *VNI) const
getEqClass - Classify creates equivalence classes numbered 0..N.
void Distribute (LiveInterval &LI, LiveInterval *LIV[], MachineRegisterInfo &MRI)
Distribute values in LI into a separate LiveIntervals for each connected component.
Detailed Description
ConnectedVNInfoEqClasses - Helper class that can divide VNInfos in a LiveInterval into equivalence clases of connected components.
A LiveInterval that has multiple connected components can be broken into multiple LiveIntervals.
Given a LiveInterval that may have multiple connected components, run:
unsigned numComps = ConEQ.Classify(LI); if (numComps > 1) { // allocate numComps-1 new LiveIntervals into LIS[1..] ConEQ.Distribute(LIS); }
Definition at line 962 of file LiveInterval.h.
Constructor & Destructor Documentation
ConnectedVNInfoEqClasses()
llvm::ConnectedVNInfoEqClasses::ConnectedVNInfoEqClasses (LiveIntervals & lis) inline explicit
Definition at line 967 of file LiveInterval.h.
Member Function Documentation
Classify()
unsigned ConnectedVNInfoEqClasses::Classify (const LiveRange & LR)
Classify the values in LR into connected components.
Returns the number of connected components.
Definition at line 1308 of file LiveInterval.cpp.
References assert(), llvm::IntEqClasses::clear(), llvm::IntEqClasses::compress(), llvm::VNInfo::def, llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveIntervals::getMBBFromIndex(), llvm::IntEqClasses::getNumClasses(), llvm::LiveRange::getNumValNums(), llvm::LiveRange::getVNInfoBefore(), llvm::IntEqClasses::grow(), llvm::VNInfo::id, llvm::VNInfo::isPHIDef(), llvm::VNInfo::isUnused(), llvm::IntEqClasses::join(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), and llvm::LiveRange::valnos.
Referenced by llvm::LiveIntervals::splitSeparateComponents().
Distribute()
void ConnectedVNInfoEqClasses::Distribute (LiveInterval & LI, LiveInterval * LIV[], MachineRegisterInfo & MRI)
Distribute values in LI into a separate LiveIntervals for each connected component.
LIV must have an empty LiveInterval for each additional connected component. The first connected component is left in LI.
Definition at line 1351 of file LiveInterval.cpp.
References Allocator, assert(), llvm::SmallVectorImpl< T >::clear(), llvm::LiveInterval::createSubRange(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::VNInfo::def, llvm::DistributeRange(), getEqClass(), llvm::SlotIndexes::getIndexBefore(), llvm::LiveIntervals::getInstructionIndex(), llvm::IntEqClasses::getNumClasses(), llvm::LiveIntervals::getSlotIndexes(), llvm::LiveIntervals::getVNInfoAllocator(), llvm::LiveRange::getVNInfoAt(), llvm::LiveInterval::hasSubRanges(), I, Idx, llvm::VNInfo::isUnused(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveRange::Query(), llvm::MachineOperand::readsReg(), llvm::LiveInterval::reg, llvm::LiveInterval::removeEmptySubRanges(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), llvm::MachineOperand::setReg(), llvm::LiveInterval::subranges(), llvm::LiveQueryResult::valueDefined(), llvm::LiveQueryResult::valueIn(), and llvm::LiveQueryResult::valueOut().
Referenced by llvm::LiveIntervals::splitSeparateComponents().
getEqClass()
unsigned llvm::ConnectedVNInfoEqClasses::getEqClass (const VNInfo * VNI) const inline
getEqClass - Classify creates equivalence classes numbered 0..N.
Return the equivalence class assigned the VNI.
Definition at line 975 of file LiveInterval.h.
References llvm::VNInfo::id.
Referenced by Distribute().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveInterval.h
lib/CodeGen/LiveInterval.cpp