LLVM: llvm::Legalizer Class Reference
llvm::Legalizer Class Reference
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
Public Member Functions
Legalizer ()
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getSetProperties () const override
MachineFunctionProperties getClearedProperties () const override
bool combineExtracts (MachineInstr &MI, MachineRegisterInfo &MRI, const TargetInstrInfo &TII)
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 30 of file Legalizer.h.
Constructor & Destructor Documentation
Legalizer()
Legalize the Machine IR a function s Machine false Legalizer::Legalizer ()
Definition at line 53 of file Legalizer.cpp.
Member Function Documentation
combineExtracts()
bool llvm::Legalizer::combineExtracts (MachineInstr & MI, MachineRegisterInfo & MRI, const TargetInstrInfo & TII)
getAnalysisUsage()
void Legalizer::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 55 of file Legalizer.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::getSelectionDAGFallbackAnalysisUsage().
getClearedProperties()
MachineFunctionProperties llvm::Legalizer::getClearedProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 57 of file Legalizer.h.
References llvm::MachineFunctionProperties::NoPHIs, and llvm::MachineFunctionProperties::set().
getPassName()
StringRef llvm::Legalizer::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 43 of file Legalizer.h.
getRequiredProperties()
MachineFunctionProperties llvm::Legalizer::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 47 of file Legalizer.h.
References llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::set().
getSetProperties()
MachineFunctionProperties llvm::Legalizer::getSetProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 52 of file Legalizer.h.
References llvm::MachineFunctionProperties::Legalized, and llvm::MachineFunctionProperties::set().
runOnMachineFunction()
bool Legalizer::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 142 of file Legalizer.cpp.
References llvm::GISelObserverWrapper::addObserver(), assert(), llvm::dbgs(), llvm::GISelWorkList< N >::deferred_insert(), llvm::GISelWorkList< N >::empty(), EnableCSEInLegalizer, llvm::GISelObserverWrapper::erasingInstr(), llvm::MachineFunctionProperties::FailedISel, llvm::GISelWorkList< N >::finalize(), llvm::TargetPassConfig::getCSEConfig(), llvm::MachineFunction::getFunction(), llvm::LegalizerHelper::getLegalizerInfo(), llvm::MachineFunction::getName(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunctionProperties::hasProperty(), llvm::GISelWorkList< N >::insert(), isArtifact(), llvm::TargetPassConfig::isGISelCSEEnabled(), llvm::isPreISelGenericOpcode(), llvm::isTriviallyDead(), llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::legalizeInstrStep(), LLVM_DEBUG, MI, llvm::LegalizerHelper::MIRBuilder, MORE, MRI, llvm::GISelWorkList< N >::pop_back_val(), llvm::reportGISelFailure(), llvm::MachineFunction::size(), llvm::MachineIRBuilder::stopObservingChanges(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::LegalizerHelper::UnableToLegalize, and Wrapper.
Member Data Documentation
ID
char Legalizer::ID = 0 static
Definition at line 32 of file Legalizer.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/Legalizer.h
lib/CodeGen/GlobalISel/Legalizer.cpp