LLVM: llvm::MCCFIInstruction Class Reference
llvm::MCCFIInstruction Class Reference
#include "llvm/MC/MCDwarf.h"
Public Types
enum OpType {
OpSameValue , OpRememberState , OpRestoreState , OpOffset ,
OpDefCfaRegister , OpDefCfaOffset , OpDefCfa , OpRelOffset ,
OpAdjustCfaOffset , OpEscape , OpRestore , OpUndefined ,
OpRegister , OpWindowSave , OpNegateRAState , OpGnuArgsSize
}
Public Member Functions
OpType getOperation () const
MCSymbol * getLabel () const
unsigned getRegister () const
unsigned getRegister2 () const
int getOffset () const
StringRef getValues () const
Static Public Member Functions
static MCCFIInstruction createDefCfa (MCSymbol *L, unsigned Register, int Offset)
.cfi_def_cfa defines a rule for computing CFA as: take address from Register and add Offset to it.
static MCCFIInstruction createDefCfaRegister (MCSymbol *L, unsigned Register)
.cfi_def_cfa_register modifies a rule for computing CFA.
static MCCFIInstruction createDefCfaOffset (MCSymbol *L, int Offset)
.cfi_def_cfa_offset modifies a rule for computing CFA.
static MCCFIInstruction createAdjustCfaOffset (MCSymbol *L, int Adjustment)
.cfi_adjust_cfa_offset Same as .cfi_def_cfa_offset, but Offset is a relative value that is added/subtracted from the previous offset.
static MCCFIInstruction createOffset (MCSymbol *L, unsigned Register, int Offset)
.cfi_offset Previous value of Register is saved at offset Offset from CFA.
static MCCFIInstruction createRelOffset (MCSymbol *L, unsigned Register, int Offset)
.cfi_rel_offset Previous value of Register is saved at offset Offset from the current CFA register.
static MCCFIInstruction createRegister (MCSymbol *L, unsigned Register1, unsigned Register2)
.cfi_register Previous value of Register1 is saved in register Register2.
static MCCFIInstruction createWindowSave (MCSymbol *L)
.cfi_window_save SPARC register window is saved.
static MCCFIInstruction createNegateRAState (MCSymbol *L)
.cfi_negate_ra_state AArch64 negate RA state.
static MCCFIInstruction createRestore (MCSymbol *L, unsigned Register)
.cfi_restore says that the rule for Register is now the same as it was at the beginning of the function, after all initial instructions added by .cfi_startproc were executed.
static MCCFIInstruction createUndefined (MCSymbol *L, unsigned Register)
.cfi_undefined From now on the previous value of Register can't be restored anymore.
static MCCFIInstruction createSameValue (MCSymbol *L, unsigned Register)
.cfi_same_value Current value of Register is the same as in the previous frame.
static MCCFIInstruction createRememberState (MCSymbol *L)
.cfi_remember_state Save all current rules for all registers.
static MCCFIInstruction createRestoreState (MCSymbol *L)
.cfi_restore_state Restore the previously saved state.
static MCCFIInstruction createEscape (MCSymbol *L, StringRef Vals)
.cfi_escape Allows the user to add arbitrary bytes to the unwind info.
static MCCFIInstruction createGnuArgsSize (MCSymbol *L, int Size)
A special wrapper for .cfi_escape that indicates GNU_ARGS_SIZE.
Detailed Description
Definition at line 435 of file MCDwarf.h.
Member Enumeration Documentation
OpType
enum llvm::MCCFIInstruction::OpType
Enumerator
OpSameValue
OpRememberState
OpRestoreState
OpOffset
OpDefCfaRegister
OpDefCfaOffset
OpDefCfa
OpRelOffset
OpAdjustCfaOffset
OpEscape
OpRestore
OpUndefined
OpRegister
OpWindowSave
OpNegateRAState
OpGnuArgsSize
Definition at line 437 of file MCDwarf.h.
Member Function Documentation
createAdjustCfaOffset()
static MCCFIInstruction llvm::MCCFIInstruction::createAdjustCfaOffset (MCSymbol * L, int Adjustment) inline static
.cfi_adjust_cfa_offset Same as .cfi_def_cfa_offset, but Offset is a relative value that is added/subtracted from the previous offset.
Definition at line 501 of file MCDwarf.h.
References OpAdjustCfaOffset.
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::MCStreamer::EmitCFIAdjustCfaOffset(), and ExpandMOVImmSExti8().
createDefCfa()
static MCCFIInstruction llvm::MCCFIInstruction::createDefCfa (MCSymbol * L, unsigned Register, int Offset) inline static
.cfi_def_cfa defines a rule for computing CFA as: take address from Register and add Offset to it.
Definition at line 480 of file MCDwarf.h.
References Offset, and OpDefCfa.
Referenced by createAArch64MCAsmInfo(), createARCMCAsmInfo(), createARMMCAsmInfo(), createHexagonMCAsmInfo(), createPPCMCAsmInfo(), createRISCVMCAsmInfo(), createSparcMCAsmInfo(), createSparcV9MCAsmInfo(), createSystemZMCAsmInfo(), createX86MCAsmInfo(), createXCoreMCAsmInfo(), llvm::MCStreamer::EmitCFIDefCfa(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::RISCVFrameLowering::emitPrologue().
createDefCfaOffset()
static MCCFIInstruction llvm::MCCFIInstruction::createDefCfaOffset (MCSymbol * L, int Offset) inline static
.cfi_def_cfa_offset modifies a rule for computing CFA.
Register remains the same, but offset is new. Note that it is the absolute offset that will be added to a defined register to the compute CFA address.
Definition at line 494 of file MCDwarf.h.
References Offset, and OpDefCfaOffset.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::MCStreamer::EmitCFIDefCfaOffset(), EmitDefCfaOffset(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
createDefCfaRegister()
static MCCFIInstruction llvm::MCCFIInstruction::createDefCfaRegister (MCSymbol * L, unsigned Register) inline static
.cfi_def_cfa_register modifies a rule for computing CFA.
From now on Register will be used instead of the old one. Offset remains the same.
Definition at line 487 of file MCDwarf.h.
References OpDefCfaRegister.
Referenced by createMipsMCAsmInfo(), llvm::MCStreamer::EmitCFIDefCfaRegister(), EmitDefCfaRegister(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
createEscape()
static MCCFIInstruction llvm::MCCFIInstruction::createEscape (MCSymbol * L, StringRef Vals) inline static
.cfi_escape Allows the user to add arbitrary bytes to the unwind info.
Definition at line 568 of file MCDwarf.h.
References OpEscape.
Referenced by llvm::MCStreamer::EmitCFIEscape(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
createGnuArgsSize()
static MCCFIInstruction llvm::MCCFIInstruction::createGnuArgsSize (MCSymbol * L, int Size) inline static
A special wrapper for .cfi_escape that indicates GNU_ARGS_SIZE.
Definition at line 573 of file MCDwarf.h.
References OpGnuArgsSize, and Size.
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), and llvm::MCStreamer::EmitCFIGnuArgsSize().
createNegateRAState()
static MCCFIInstruction llvm::MCCFIInstruction::createNegateRAState (MCSymbol * L) inline static
.cfi_negate_ra_state AArch64 negate RA state.
Definition at line 533 of file MCDwarf.h.
References OpNegateRAState.
Referenced by llvm::MCStreamer::EmitCFINegateRAState(), and llvm::AArch64FrameLowering::emitPrologue().
createOffset()
static MCCFIInstruction llvm::MCCFIInstruction::createOffset (MCSymbol * L, unsigned Register, int Offset) inline static
.cfi_offset Previous value of Register is saved at offset Offset from CFA.
Definition at line 507 of file MCDwarf.h.
References Offset, and OpOffset.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64InstrInfo::buildOutlinedFrame(), createX86MCAsmInfo(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::MCStreamer::EmitCFIOffset(), EmitCfiOffset(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
createRegister()
static MCCFIInstruction llvm::MCCFIInstruction::createRegister (MCSymbol * L, unsigned Register1, unsigned Register2) inline static
.cfi_register Previous value of Register1 is saved in register Register2.
Definition at line 522 of file MCDwarf.h.
References OpRegister, and Register2.
Referenced by llvm::MCStreamer::EmitCFIRegister(), llvm::PPCFrameLowering::emitPrologue(), and llvm::SparcFrameLowering::emitPrologue().
createRelOffset()
static MCCFIInstruction llvm::MCCFIInstruction::createRelOffset (MCSymbol * L, unsigned Register, int Offset) inline static
.cfi_rel_offset Previous value of Register is saved at offset Offset from the current CFA register.
This is transformed to .cfi_offset using the known displacement of the CFA register from the CFA.
Definition at line 515 of file MCDwarf.h.
References Offset, and OpRelOffset.
Referenced by llvm::MCStreamer::EmitCFIRelOffset().
createRememberState()
static MCCFIInstruction llvm::MCCFIInstruction::createRememberState (MCSymbol * L) inline static
.cfi_remember_state Save all current rules for all registers.
Definition at line 557 of file MCDwarf.h.
References OpRememberState.
Referenced by llvm::MCStreamer::EmitCFIRememberState().
createRestore()
static MCCFIInstruction llvm::MCCFIInstruction::createRestore (MCSymbol * L, unsigned Register) inline static
.cfi_restore says that the rule for Register is now the same as it was at the beginning of the function, after all initial instructions added by .cfi_startproc were executed.
Definition at line 540 of file MCDwarf.h.
References OpRestore.
Referenced by llvm::MCStreamer::EmitCFIRestore(), and llvm::RISCVFrameLowering::emitEpilogue().
createRestoreState()
static MCCFIInstruction llvm::MCCFIInstruction::createRestoreState (MCSymbol * L) inline static
.cfi_restore_state Restore the previously saved state.
Definition at line 562 of file MCDwarf.h.
References OpRestoreState.
Referenced by llvm::MCStreamer::EmitCFIRestoreState().
createSameValue()
static MCCFIInstruction llvm::MCCFIInstruction::createSameValue (MCSymbol * L, unsigned Register) inline static
.cfi_same_value Current value of Register is the same as in the previous frame.
I.e., no restoration is needed.
Definition at line 552 of file MCDwarf.h.
References OpSameValue.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::MCStreamer::EmitCFISameValue().
createUndefined()
static MCCFIInstruction llvm::MCCFIInstruction::createUndefined (MCSymbol * L, unsigned Register) inline static
.cfi_undefined From now on the previous value of Register can't be restored anymore.
Definition at line 546 of file MCDwarf.h.
References OpUndefined.
Referenced by llvm::MCStreamer::EmitCFIUndefined().
createWindowSave()
static MCCFIInstruction llvm::MCCFIInstruction::createWindowSave (MCSymbol * L) inline static
.cfi_window_save SPARC register window is saved.
Definition at line 528 of file MCDwarf.h.
References OpWindowSave.
Referenced by llvm::MCStreamer::EmitCFIWindowSave(), and llvm::SparcFrameLowering::emitPrologue().
getLabel()
MCSymbol * llvm::MCCFIInstruction::getLabel () const inline
Definition at line 578 of file MCDwarf.h.
Referenced by printCFI().
getOffset()
int llvm::MCCFIInstruction::getOffset () const inline
Definition at line 593 of file MCDwarf.h.
References assert(), Offset, OpAdjustCfaOffset, OpDefCfa, OpDefCfaOffset, Operation, OpGnuArgsSize, OpOffset, and OpRelOffset.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), and printCFI().
getOperation()
OpType llvm::MCCFIInstruction::getOperation () const inline
Definition at line 577 of file MCDwarf.h.
References Operation.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), and printCFI().
getRegister()
unsigned llvm::MCCFIInstruction::getRegister () const inline
Definition at line 580 of file MCDwarf.h.
References assert(), OpDefCfa, OpDefCfaRegister, Operation, OpOffset, OpRegister, OpRelOffset, OpRestore, OpSameValue, and OpUndefined.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), and printCFI().
getRegister2()
unsigned llvm::MCCFIInstruction::getRegister2 () const inline
Definition at line 588 of file MCDwarf.h.
References assert(), Operation, OpRegister, and Register2.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), and printCFI().
getValues()
StringRef llvm::MCCFIInstruction::getValues () const inline
Definition at line 600 of file MCDwarf.h.
References assert(), Operation, and OpEscape.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), and printCFI().
Member Data Documentation
Offset
int llvm::MCCFIInstruction::Offset
Definition at line 461 of file MCDwarf.h.
Referenced by createDefCfa(), createDefCfaOffset(), createOffset(), createRelOffset(), and getOffset().
Register2
unsigned llvm::MCCFIInstruction::Register2
Definition at line 462 of file MCDwarf.h.
Referenced by createRegister(), and getRegister2().
The documentation for this class was generated from the following file:
include/llvm/MC/MCDwarf.h