LLVM: llvm::SDDbgInfo Class Reference
llvm::SDDbgInfo Class Reference
Keeps track of dbg_value information through SDISel.
#include "llvm/CodeGen/SelectionDAG.h"
Public Types
using DbgIterator = SmallVectorImpl< SDDbgValue * >::iterator
using DbgLabelIterator = SmallVectorImpl< SDDbgLabel * >::iterator
Public Member Functions
SDDbgInfo ()=default
SDDbgInfo (const SDDbgInfo &)=delete
SDDbgInfo & operator= (const SDDbgInfo &)=delete
void add (SDDbgValue *V, const SDNode *Node, bool isParameter)
void add (SDDbgLabel *L)
void erase (const SDNode *Node)
Invalidate all DbgValues attached to the node and remove it from the Node-to-DbgValues map.
void clear ()
BumpPtrAllocator & getAlloc ()
bool empty () const
ArrayRef< SDDbgValue * > getSDDbgValues (const SDNode *Node) const
DbgIterator DbgBegin ()
DbgIterator DbgEnd ()
DbgIterator ByvalParmDbgBegin ()
DbgIterator ByvalParmDbgEnd ()
DbgLabelIterator DbgLabelBegin ()
DbgLabelIterator DbgLabelEnd ()
Detailed Description
Keeps track of dbg_value information through SDISel.
We do not build SDNodes for these so as not to perturb the generated code; instead the info is kept off to the side in this structure. Each SDNode may have one or more associated dbg_value entries. This information is kept in DbgValMap. Byval parameters are handled separately because they don't use alloca's, which busts the normal mechanism. There is good reason for handling all parameters separately: they may not have code generated for them, they should always go at the beginning of the function regardless of other code motion, and debug info for them is potentially useful even if the parameter is unused. Right now only byval parameters are handled separately.
Definition at line 147 of file SelectionDAG.h.
Member Typedef Documentation
DbgIterator
using llvm::SDDbgInfo::DbgIterator = SmallVectorImpl<SDDbgValue*>::iterator
Definition at line 197 of file SelectionDAG.h.
DbgLabelIterator
using llvm::SDDbgInfo::DbgLabelIterator = SmallVectorImpl<SDDbgLabel*>::iterator
Definition at line 198 of file SelectionDAG.h.
Constructor & Destructor Documentation
SDDbgInfo() [1/2]
llvm::SDDbgInfo::SDDbgInfo () default
SDDbgInfo() [2/2]
llvm::SDDbgInfo::SDDbgInfo (const SDDbgInfo &) delete
Member Function Documentation
add() [1/2]
void llvm::SDDbgInfo::add (SDDbgLabel * L) inline
Definition at line 168 of file SelectionDAG.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
add() [2/2]
void llvm::SDDbgInfo::add (SDDbgValue * V, const SDNode * Node, bool isParameter) inline
Definition at line 160 of file SelectionDAG.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::SelectionDAG::AddDbgLabel(), and llvm::SelectionDAG::AddDbgValue().
ByvalParmDbgBegin()
DbgIterator llvm::SDDbgInfo::ByvalParmDbgBegin () inline
Definition at line 202 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SelectionDAG::ByvalParmDbgBegin().
ByvalParmDbgEnd()
DbgIterator llvm::SDDbgInfo::ByvalParmDbgEnd () inline
Definition at line 203 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SelectionDAG::ByvalParmDbgEnd().
clear()
void llvm::SDDbgInfo::clear () inline
Definition at line 176 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
Referenced by llvm::SelectionDAG::clear().
DbgBegin()
DbgIterator llvm::SDDbgInfo::DbgBegin () inline
Definition at line 200 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SelectionDAG::DbgBegin().
DbgEnd()
DbgIterator llvm::SDDbgInfo::DbgEnd () inline
Definition at line 201 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SelectionDAG::DbgEnd().
DbgLabelBegin()
DbgLabelIterator llvm::SDDbgInfo::DbgLabelBegin () inline
Definition at line 204 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SelectionDAG::DbgLabelBegin().
DbgLabelEnd()
DbgLabelIterator llvm::SDDbgInfo::DbgLabelEnd () inline
Definition at line 205 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SelectionDAG::DbgLabelEnd().
empty()
bool llvm::SDDbgInfo::empty () const inline
Definition at line 186 of file SelectionDAG.h.
References llvm::SmallVectorBase::empty().
Referenced by llvm::SelectionDAG::hasDebugValues().
erase()
void SDDbgInfo::erase (const SDNode * Node)
Invalidate all DbgValues attached to the node and remove it from the Node-to-DbgValues map.
Definition at line 762 of file SelectionDAG.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
getAlloc()
BumpPtrAllocator & llvm::SDDbgInfo::getAlloc () inline
Definition at line 184 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::getConstantDbgValue(), llvm::SelectionDAG::getDbgLabel(), llvm::SelectionDAG::getDbgValue(), llvm::SelectionDAG::getFrameIndexDbgValue(), and llvm::SelectionDAG::getVRegDbgValue().
getSDDbgValues()
ArrayRef< SDDbgValue * > llvm::SDDbgInfo::getSDDbgValues (const SDNode * Node) const inline
Definition at line 190 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::SelectionDAG::AddDbgValue(), and llvm::SelectionDAG::GetDbgValues().
operator=()
SDDbgInfo & llvm::SDDbgInfo::operator= (const SDDbgInfo &) delete
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/SelectionDAG.cpp