LLVM: llvm::SMLoc Class Reference
llvm::SMLoc Class Reference
Represents a location in source code.
#include "llvm/Support/SMLoc.h"
Public Member Functions
SMLoc ()=default
bool isValid () const
bool operator== (const SMLoc &RHS) const
bool operator!= (const SMLoc &RHS) const
const char * getPointer () const
Static Public Member Functions
static SMLoc getFromPointer (const char *Ptr)
Detailed Description
Represents a location in source code.
Definition at line 23 of file SMLoc.h.
Constructor & Destructor Documentation
SMLoc()
llvm::SMLoc::SMLoc () default
Member Function Documentation
getFromPointer()
static SMLoc llvm::SMLoc::getFromPointer (const char * Ptr) inline static
Definition at line 36 of file SMLoc.h.
Referenced by llvm::yaml::BlockScalarNode::BlockScalarNode(), llvm::FileCheckString::CheckDag(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckSame(), llvm::X86Operand::CreateToken(), llvm::FileCheckErrorDiagnostic::get(), llvm::AsmToken::getEndLoc(), llvm::AsmToken::getLoc(), llvm::MCAsmLexer::getLoc(), llvm::LLLexer::getLoc(), llvm::TGLexer::getLoc(), llvm::SourceMgr::GetMessage(), incrementLoc(), isAltmacroString(), llvm::FileCheckPattern::parsePattern(), llvm::parseType(), llvm::PrintError(), llvm::FileCheckPattern::printSubstitutions(), llvm::PrintWarning(), ProcessMatchResult(), llvm::FileCheck::ReadCheckFile(), llvm::yaml::ScalarNode::ScalarNode(), and llvm::yaml::Scanner::setError().
getPointer()
const char * llvm::SMLoc::getPointer () const inline
Definition at line 34 of file SMLoc.h.
Referenced by llvm::X86Operand::CreateToken(), llvm::SourceMgr::FindBufferContainingLoc(), llvm::SourceMgr::getLineAndColumn(), llvm::SourceMgr::GetMessage(), incrementLoc(), isAltmacroString(), llvm::X86Operand::isOffsetOf(), llvm::SMFixIt::operator<(), llvm::SMDiagnostic::print(), and rewritesSort().
isValid()
bool llvm::SMLoc::isValid () const inline
Definition at line 29 of file SMLoc.h.
Referenced by llvm::SourceMgr::GetMessage(), llvm::SMRange::isValid(), llvm::SourceMgr::PrintMessage(), llvm::SMFixIt::SMFixIt(), and llvm::SMRange::SMRange().
operator!=()
bool llvm::SMLoc::operator!= (const SMLoc & RHS) const inline
Definition at line 32 of file SMLoc.h.
operator==()
bool llvm::SMLoc::operator== (const SMLoc & RHS) const inline
Definition at line 31 of file SMLoc.h.
The documentation for this class was generated from the following file:
include/llvm/Support/SMLoc.h