LLVM: llvm::GPUDivergenceAnalysis Class Reference
llvm::GPUDivergenceAnalysis Class Reference
Divergence analysis frontend for GPU kernels.
#include "llvm/Analysis/DivergenceAnalysis.h"
Public Member Functions
GPUDivergenceAnalysis (Function &F, const DominatorTree &DT, const PostDominatorTree &PDT, const LoopInfo &LI, const TargetTransformInfo &TTI)
Runs the divergence analysis on @F, a GPU kernel.
bool hasDivergence () const
Whether any divergence was detected.
const Function & getFunction () const
The GPU kernel this analysis result is for.
bool isDivergent (const Value &V) const
Whether V is divergent.
bool isUniform (const Value &V) const
Whether V is uniform/non-divergent.
void print (raw_ostream &OS, const Module *) const
Print all divergent values in the kernel.
Detailed Description
Divergence analysis frontend for GPU kernels.
Definition at line 176 of file DivergenceAnalysis.h.
Constructor & Destructor Documentation
GPUDivergenceAnalysis()
GPUDivergenceAnalysis::GPUDivergenceAnalysis (Function & F, const DominatorTree & DT, const PostDominatorTree & PDT, const LoopInfo & LI, const TargetTransformInfo & TTI)
Runs the divergence analysis on @F, a GPU kernel.
Definition at line 426 of file DivergenceAnalysis.cpp.
References llvm::DivergenceAnalysis::addUniformOverride(), llvm::DivergenceAnalysis::compute(), F, I, instructions, llvm::TargetTransformInfo::isAlwaysUniform(), llvm::TargetTransformInfo::isSourceOfDivergence(), and llvm::DivergenceAnalysis::markDivergent().
Member Function Documentation
getFunction()
const Function & llvm::GPUDivergenceAnalysis::getFunction () const inline
The GPU kernel this analysis result is for.
Definition at line 190 of file DivergenceAnalysis.h.
References llvm::DivergenceAnalysis::getFunction().
hasDivergence()
bool llvm::GPUDivergenceAnalysis::hasDivergence () const inline
Whether any divergence was detected.
Definition at line 187 of file DivergenceAnalysis.h.
References llvm::DivergenceAnalysis::hasDetectedDivergence().
isDivergent()
bool GPUDivergenceAnalysis::isDivergent (const Value & V) const
Whether V is divergent.
Definition at line 448 of file DivergenceAnalysis.cpp.
References llvm::DivergenceAnalysis::isDivergent().
Referenced by isUniform().
isUniform()
bool llvm::GPUDivergenceAnalysis::isUniform (const Value & V) const inline
Whether V is uniform/non-divergent.
Definition at line 196 of file DivergenceAnalysis.h.
References isDivergent().
print()
void GPUDivergenceAnalysis::print (raw_ostream & OS, const Module * mod) const
Print all divergent values in the kernel.
Definition at line 452 of file DivergenceAnalysis.cpp.
References llvm::DivergenceAnalysis::getFunction(), llvm::Value::getName(), and llvm::DivergenceAnalysis::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DivergenceAnalysis.h
lib/Analysis/DivergenceAnalysis.cpp