LLVM: llvm::upward_defs_iterator Class Reference
llvm::upward_defs_iterator Class Reference
Provide an iterator that walks defs, giving both the memory access, and the current pointer location, updating the pointer location as it changes due to phi node translation.
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
upward_defs_iterator (const MemoryAccessPair &Info)
upward_defs_iterator ()
bool operator== (const upward_defs_iterator &Other) const
BaseT::iterator::reference operator* () const
upward_defs_iterator & operator++ ()
BasicBlock * getPhiArgBlock () const
DerivedT & operator++ ()
DerivedT operator++ (int)
Public Member Functions inherited from llvm::iterator_facade_base< upward_defs_iterator, std::forward_iterator_tag, const MemoryAccessPair >
upward_defs_iterator operator+ (std::ptrdiff_t n) const
upward_defs_iterator operator- (std::ptrdiff_t n) const
upward_defs_iterator & operator++ ()
upward_defs_iterator operator++ (int)
upward_defs_iterator & operator-- ()
upward_defs_iterator operator-- (int)
bool operator!= (const upward_defs_iterator &RHS) const
bool operator> (const upward_defs_iterator &RHS) const
bool operator<= (const upward_defs_iterator &RHS) const
bool operator>= (const upward_defs_iterator &RHS) const
const MemoryAccessPair * operator-> ()
const MemoryAccessPair * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< upward_defs_iterator, std::forward_iterator_tag, const MemoryAccessPair >
enum
Detailed Description
Provide an iterator that walks defs, giving both the memory access, and the current pointer location, updating the pointer location as it changes due to phi node translation.
This iterator, while somewhat specialized, is what most clients actually want when walking upwards through MemorySSA def chains. It takes a pair of <MemoryAccess,MemoryLocation>, and walks defs, properly translating the memory location through phi nodes for the user.
Definition at line 1177 of file MemorySSA.h.
Constructor & Destructor Documentation
upward_defs_iterator() [1/2]
llvm::upward_defs_iterator::upward_defs_iterator (const MemoryAccessPair & Info) inline
Definition at line 1184 of file MemorySSA.h.
References Info.
upward_defs_iterator() [2/2]
llvm::upward_defs_iterator::upward_defs_iterator () inline
Definition at line 1193 of file MemorySSA.h.
Member Function Documentation
getPhiArgBlock()
BasicBlock * llvm::upward_defs_iterator::getPhiArgBlock () const inline
Definition at line 1215 of file MemorySSA.h.
References llvm::memoryaccess_def_iterator_base< T >::getPhiArgBlock().
operator*()
BaseT::iterator::reference llvm::upward_defs_iterator::operator* () const inline
Definition at line 1199 of file MemorySSA.h.
References assert(), and llvm::MemoryAccess::defs_end().
operator++() [1/3]
DerivedT & llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ () inline
Definition at line 120 of file iterator.h.
operator++() [2/3]
upward_defs_iterator & llvm::upward_defs_iterator::operator++ () inline
Definition at line 1206 of file MemorySSA.h.
References assert(), and llvm::MemoryAccess::defs_end().
operator++() [3/3]
DerivedT llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
Definition at line 125 of file iterator.h.
operator==()
bool llvm::upward_defs_iterator::operator== (const upward_defs_iterator & Other) const inline
Definition at line 1195 of file MemorySSA.h.
References Other.
The documentation for this class was generated from the following file:
include/llvm/Analysis/MemorySSA.h