LLVM: llvm::codeview::DebugChecksumsSubsectionRef Class Reference
llvm::codeview::DebugChecksumsSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h"
Public Member Functions
DebugChecksumsSubsectionRef ()
bool valid () const
Error initialize (BinaryStreamReader Reader)
Error initialize (BinaryStreamRef Stream)
Iterator begin () const
Iterator end () const
const FileChecksumArray & getArray () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 49 of file DebugChecksumsSubsection.h.
Constructor & Destructor Documentation
DebugChecksumsSubsectionRef()
llvm::codeview::DebugChecksumsSubsectionRef::DebugChecksumsSubsectionRef () inline
Definition at line 54 of file DebugChecksumsSubsection.h.
Member Function Documentation
begin()
Iterator llvm::codeview::DebugChecksumsSubsectionRef::begin () const inline
Definition at line 66 of file DebugChecksumsSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::begin().
classof()
static bool llvm::codeview::DebugChecksumsSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 57 of file DebugChecksumsSubsection.h.
References llvm::codeview::FileChecksums, and llvm::codeview::DebugSubsectionRef::kind().
end()
Iterator llvm::codeview::DebugChecksumsSubsectionRef::end () const inline
Definition at line 67 of file DebugChecksumsSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::end().
getArray()
const FileChecksumArray & llvm::codeview::DebugChecksumsSubsectionRef::getArray () const inline
Definition at line 69 of file DebugChecksumsSubsection.h.
initialize() [1/2]
Error DebugChecksumsSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 51 of file DebugChecksumsSubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, llvm::BinaryStreamReader::readArray(), and llvm::Error::success().
Referenced by llvm::pdb::ModuleDebugStreamRef::findChecksumsSubsection(), initialize(), and llvm::codeview::visitDebugSubsection().
initialize() [2/2]
Error DebugChecksumsSubsectionRef::initialize (BinaryStreamRef Stream)
Definition at line 58 of file DebugChecksumsSubsection.cpp.
References initialize().
valid()
bool llvm::codeview::DebugChecksumsSubsectionRef::valid () const inline
Definition at line 61 of file DebugChecksumsSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::valid().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h
lib/DebugInfo/CodeView/DebugChecksumsSubsection.cpp