LLVM: llvm::DataExtractor Class Reference
llvm::DataExtractor Class Reference
#include "llvm/Support/DataExtractor.h"
Public Member Functions
DataExtractor (StringRef Data, bool IsLittleEndian, uint8_t AddressSize)
Construct with a buffer that is owned by the caller.
StringRef getData () const
Get the data pointed to by this extractor.
bool isLittleEndian () const
Get the endianness for this extractor.
uint8_t getAddressSize () const
Get the address size for this extractor.
void setAddressSize (uint8_t Size)
Set the address size for this extractor.
const char * getCStr (uint32_t *offset_ptr) const
Extract a C string from *offset_ptr.
StringRef getCStrRef (uint32_t *OffsetPtr) const
Extract a C string from *OffsetPtr.
uint64_t getUnsigned (uint32_t *offset_ptr, uint32_t byte_size) const
Extract an unsigned integer of size byte_size from *offset_ptr.
int64_t getSigned (uint32_t *offset_ptr, uint32_t size) const
Extract an signed integer of size byte_size from *offset_ptr.
uint64_t getAddress (uint32_t *offset_ptr) const
Extract an pointer from *offset_ptr.
uint8_t getU8 (uint32_t *offset_ptr) const
Extract a uint8_t value from *offset_ptr.
uint8_t * getU8 (uint32_t *offset_ptr, uint8_t *dst, uint32_t count) const
Extract count uint8_t values from *offset_ptr.
uint16_t getU16 (uint32_t *offset_ptr) const
Extract a uint16_t value from *offset_ptr.
uint16_t * getU16 (uint32_t *offset_ptr, uint16_t *dst, uint32_t count) const
Extract count uint16_t values from *offset_ptr.
uint32_t getU24 (uint32_t *offset_ptr) const
Extract a 24-bit unsigned value from *offset_ptr and return it in a uint32_t.
uint32_t getU32 (uint32_t *offset_ptr) const
Extract a uint32_t value from *offset_ptr.
uint32_t * getU32 (uint32_t *offset_ptr, uint32_t *dst, uint32_t count) const
Extract count uint32_t values from *offset_ptr.
uint64_t getU64 (uint32_t *offset_ptr) const
Extract a uint64_t value from *offset_ptr.
uint64_t * getU64 (uint32_t *offset_ptr, uint64_t *dst, uint32_t count) const
Extract count uint64_t values from *offset_ptr.
int64_t getSLEB128 (uint32_t *offset_ptr) const
Extract a signed LEB128 value from *offset_ptr.
uint64_t getULEB128 (uint32_t *offset_ptr) const
Extract a unsigned LEB128 value from *offset_ptr.
bool isValidOffset (uint32_t offset) const
Test the validity of offset.
bool isValidOffsetForDataOfSize (uint32_t offset, uint32_t length) const
Test the availability of length bytes of data from offset.
bool isValidOffsetForAddress (uint32_t offset) const
Test the availability of enough bytes of data for a pointer from offset.
Detailed Description
Definition at line 40 of file DataExtractor.h.
Constructor & Destructor Documentation
DataExtractor()
llvm::DataExtractor::DataExtractor (StringRef Data, bool IsLittleEndian, uint8_t AddressSize) inline
Construct with a buffer that is owned by the caller.
This constructor allows us to use data that is owned by the caller. The data must stay around as long as this object is valid.
Definition at line 50 of file DataExtractor.h.
Member Function Documentation
getAddress()
uint64_t llvm::DataExtractor::getAddress (uint32_t * offset_ptr) const inline
Extract an pointer from *offset_ptr.
Extract a single pointer from the data and update the offset pointed to by offset_ptr. The size of the extracted pointer is getAddressSize(), so the address size has to be set correctly prior to extracting any pointer values.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted pointer value as a 64 integer.
Definition at line 174 of file DataExtractor.h.
References getUnsigned().
getAddressSize()
uint8_t llvm::DataExtractor::getAddressSize () const inline
Get the address size for this extractor.
Definition at line 58 of file DataExtractor.h.
Referenced by llvm::DWARFDebugRangeList::extract(), llvm::DWARFDataExtractor::getEncodedPointer(), llvm::DWARFDataExtractor::getRelocatedAddress(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DWARFDebugLoclists::parse(), and llvm::DWARFDebugLine::LineTable::parse().
getCStr()
const char * DataExtractor::getCStr (uint32_t * offset_ptr) const
Extract a C string from *offset_ptr.
Returns a pointer to a C String from the data at the offset pointed to by offset_ptr. A variable length NULL terminated C string will be extracted and the offset_ptr will be updated with the offset of the byte that follows the NULL terminator byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
A pointer to the C string value in the data. If the offset pointed to by offset_ptr is out of bounds, or if the offset plus the length of the C string is out of bounds, NULL will be returned.
Definition at line 128 of file DataExtractor.cpp.
Referenced by llvm::DWARFContext::dump(), dumpDWARFv5StringOffsetsSection(), dumpStringOffsetsSection(), llvm::AppleAcceleratorTable::equal_range(), llvm::DWARFFormValue::getAsCString(), llvm::DWARFDebugNames::NameTableEntry::getString(), llvm::DWARFDebugMacro::parse(), llvm::DWARFDebugLine::LineTable::parse(), and llvm::DWARFFormValue::skipValue().
getCStrRef()
StringRef DataExtractor::getCStrRef (uint32_t * OffsetPtr) const
Extract a C string from *OffsetPtr.
Returns a StringRef for the C String from the data at the offset pointed to by OffsetPtr. A variable length NULL terminated C string will be extracted and the OffsetPtr will be updated with the offset of the byte that follows the NULL terminator byte.
Parameters
[in,out] OffsetPtr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
A StringRef for the C string value in the data. If the offset pointed to by OffsetPtr is out of bounds, or if the offset plus the length of the C string is out of bounds, a default-initialized StringRef will be returned.
Definition at line 138 of file DataExtractor.cpp.
Referenced by llvm::DWARFDebugPubTable::DWARFDebugPubTable(), and parseV2DirFileTables().
getData()
StringRef llvm::DataExtractor::getData () const inline
Get the data pointed to by this extractor.
Definition at line 54 of file DataExtractor.h.
Referenced by llvm::DWARFUnit::determineStringOffsetsTableContribution(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), llvm::DWARFExpression::end(), llvm::DWARFExpression::iterator::operator++(), and llvm::DWARFExpression::print().
getSigned()
int64_t DataExtractor::getSigned (uint32_t * offset_ptr, uint32_t size) const
Extract an signed integer of size byte_size from *offset_ptr.
Extract a single signed integer value (sign extending if required) and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size should have a value greater than or equal to one and less than or equal to eight since the return value is 64 bits wide. Any byte_size values less than 1 or greater than 8 will result in nothing being extracted, and zero being returned.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] size The size in bytes of the integer to extract.
Returns
The sign extended signed integer value that was extracted, or zero on failure.
Definition at line 114 of file DataExtractor.cpp.
References getU16(), getU32(), getU64(), getU8(), and llvm_unreachable.
Referenced by llvm::DWARFDataExtractor::getEncodedPointer().
getSLEB128()
int64_t DataExtractor::getSLEB128 (uint32_t * offset_ptr) const
Extract a signed LEB128 value from *offset_ptr.
Extracts an signed LEB128 number from this object's data starting at the offset pointed to by offset_ptr. The offset pointed to by offset_ptr will be updated with the offset of the byte following the last extracted byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted signed integer value.
Definition at line 162 of file DataExtractor.cpp.
References assert(), llvm::decodeSLEB128(), and error.
Referenced by llvm::DWARFDataExtractor::getEncodedPointer(), llvm::DWARFDebugLine::LineTable::parse(), and llvm::DWARFFormValue::skipValue().
getU16() [1/2]
uint16_t DataExtractor::getU16 (uint32_t * offset_ptr) const
Extract a uint16_t value from *offset_ptr.
Extract a single uint16_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint16_t value.
Definition at line 61 of file DataExtractor.cpp.
Referenced by llvm::DWARFDebugPubTable::DWARFDebugPubTable(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFUnitHeader::extract(), getSigned(), getUnsigned(), llvm::DWARFDebugLine::Prologue::parse(), parseDWARF32StringOffsetsTableHeader(), parseDWARF64StringOffsetsTableHeader(), and llvm::DWARFFormValue::skipValue().
getU16() [2/2]
uint16_t * DataExtractor::getU16 (uint32_t * offset_ptr, uint16_t * dst, uint32_t count) const
Extract count uint16_t values from *offset_ptr.
Extract count uint16_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint16_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint16_t values to extract.
Returns
dst if all values were properly extracted and copied, NULL otherise.
Definition at line 65 of file DataExtractor.cpp.
getU24()
uint32_t DataExtractor::getU24 (uint32_t * offset_ptr) const
Extract a 24-bit unsigned value from *offset_ptr and return it in a uint32_t.
Extract 3 bytes from the binary data at the offset pointed to by offset_ptr, construct a uint32_t from them and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the 3 bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted 24-bit value represented in a uint32_t.
Definition at line 71 of file DataExtractor.cpp.
References llvm::Uint24::getAsUint32(), and llvm::sys::IsLittleEndianHost.
getU32() [1/2]
uint32_t DataExtractor::getU32 (uint32_t * offset_ptr) const
Extract a uint32_t value from *offset_ptr.
Extract a single uint32_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint32_t value.
Definition at line 78 of file DataExtractor.cpp.
Referenced by llvm::AppleAcceleratorTable::dump(), dumpStringOffsetsSection(), llvm::DWARFDebugPubTable::DWARFDebugPubTable(), llvm::AppleAcceleratorTable::equal_range(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFUnitHeader::extract(), getSigned(), getUnsigned(), parseDWARF32StringOffsetsTableHeader(), parseDWARF64StringOffsetsTableHeader(), llvm::DWARFFormValue::skipValue(), and llvm::AppleAcceleratorTable::ValueIterator::ValueIterator().
getU32() [2/2]
uint32_t * DataExtractor::getU32 (uint32_t * offset_ptr, uint32_t * dst, uint32_t count) const
Extract count uint32_t values from *offset_ptr.
Extract count uint32_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint32_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint32_t values to extract.
Returns
dst if all values were properly extracted and copied, NULL otherise.
Definition at line 82 of file DataExtractor.cpp.
getU64() [1/2]
uint64_t DataExtractor::getU64 (uint32_t * offset_ptr) const
Extract a uint64_t value from *offset_ptr.
Extract a single uint64_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint64_t value.
Definition at line 88 of file DataExtractor.cpp.
Referenced by llvm::DWARFUnitHeader::extract(), getSigned(), getUnsigned(), llvm::DWARFDebugLine::Prologue::parse(), and parseDWARF64StringOffsetsTableHeader().
getU64() [2/2]
uint64_t * DataExtractor::getU64 (uint32_t * offset_ptr, uint64_t * dst, uint32_t count) const
Extract count uint64_t values from *offset_ptr.
Extract count uint64_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint64_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint64_t values to extract.
Returns
dst if all values were properly extracted and copied, NULL otherise.
Definition at line 92 of file DataExtractor.cpp.
getU8() [1/2]
uint8_t DataExtractor::getU8 (uint32_t * offset_ptr) const
Extract a uint8_t value from *offset_ptr.
Extract a single uint8_t from the binary data at the offset pointed to by offset_ptr, and advance the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint8_t value.
Definition at line 50 of file DataExtractor.cpp.
Referenced by llvm::DWARFDebugPubTable::DWARFDebugPubTable(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFUnitHeader::extract(), getSigned(), getUnsigned(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DWARFDebugLine::LineTable::parse(), parseV5DirFileTables(), parseV5EntryFormat(), llvm::DWARFExpression::Operation::print(), llvm::DWARFExpression::print(), and llvm::DWARFFormValue::skipValue().
getU8() [2/2]
uint8_t * DataExtractor::getU8 (uint32_t * offset_ptr, uint8_t * dst, uint32_t count) const
Extract count uint8_t values from *offset_ptr.
Extract count uint8_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint8_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint8_t values to extract.
Returns
dst if all values were properly extracted and copied, NULL otherise.
Definition at line 55 of file DataExtractor.cpp.
getULEB128()
uint64_t DataExtractor::getULEB128 (uint32_t * offset_ptr) const
Extract a unsigned LEB128 value from *offset_ptr.
Extracts an unsigned LEB128 number from this object's data starting at the offset pointed to by offset_ptr. The offset pointed to by offset_ptr will be updated with the offset of the byte following the last extracted byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted unsigned integer value.
Definition at line 148 of file DataExtractor.cpp.
References assert(), llvm::decodeULEB128(), and error.
Referenced by llvm::DWARFDie::dump(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::DWARFDataExtractor::getEncodedPointer(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::DWARFDebugMacro::parse(), llvm::DWARFDebugLine::LineTable::parse(), parseV2DirFileTables(), parseV5EntryFormat(), and llvm::DWARFFormValue::skipValue().
getUnsigned()
uint64_t DataExtractor::getUnsigned (uint32_t * offset_ptr, uint32_t byte_size) const
Extract an unsigned integer of size byte_size from *offset_ptr.
Extract a single unsigned integer value and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size should have a value greater than or equal to one and less than or equal to eight since the return value is 64 bits wide. Any byte_size values less than 1 or greater than 8 will result in nothing being extracted, and zero being returned.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] byte_size The size in byte of the integer to extract.
Returns
The unsigned integer value that was extracted, or zero on failure.
Definition at line 99 of file DataExtractor.cpp.
References getU16(), getU32(), getU64(), getU8(), and llvm_unreachable.
Referenced by llvm::DWARFDebugArangeSet::extract(), getAddress(), llvm::DWARFDataExtractor::getEncodedPointer(), and llvm::DWARFDataExtractor::getRelocatedValue().
isLittleEndian()
bool llvm::DataExtractor::isLittleEndian () const inline
Get the endianness for this extractor.
Definition at line 56 of file DataExtractor.h.
Referenced by llvm::DWARFDebugLoc::parse(), and llvm::DWARFDebugLoclists::parse().
isValidOffset()
bool llvm::DataExtractor::isValidOffset (uint32_t offset) const inline
Test the validity of offset.
Returns
true if offset is a valid offset into the data in this object, false otherwise.
Definition at line 402 of file DataExtractor.h.
Referenced by llvm::AppleAcceleratorTable::dump(), llvm::DWARFContext::dump(), llvm::DWARFDie::dump(), dumpAddrSection(), dumpRnglistsSection(), llvm::DWARFDebugPubTable::DWARFDebugPubTable(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFDebugNames::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugRangeList::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFUnitHeader::extract(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::DWARFDebugLine::getOrParseLineTable(), isValidOffsetForDataOfSize(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugMacro::parse(), llvm::DWARFDebugLoclists::parse(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::DWARFDebugLine::SectionParser::SectionParser(), and llvm::DWARFDebugLine::SectionParser::skip().
isValidOffsetForAddress()
bool llvm::DataExtractor::isValidOffsetForAddress (uint32_t offset) const inline
Test the availability of enough bytes of data for a pointer from offset.
The size of a pointer is getAddressSize().
Returns
true if offset is a valid offset and there are enough bytes for a pointer available at that offset, false otherwise.
Definition at line 420 of file DataExtractor.h.
References isValidOffsetForDataOfSize().
isValidOffsetForDataOfSize()
bool llvm::DataExtractor::isValidOffsetForDataOfSize (uint32_t offset, uint32_t length) const inline
Test the availability of length bytes of data from offset.
Returns
true if offset is a valid offset and there are length bytes available at that offset, false otherwise.
Definition at line 409 of file DataExtractor.h.
References isValidOffset().
Referenced by llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugArangeSet::extract(), getU(), getUs(), isValidOffsetForAddress(), parseDWARF32StringOffsetsTableHeader(), parseDWARF64StringOffsetsTableHeader(), llvm::StrOffsetsContributionDescriptor::validateContributionSize(), and llvm::AppleAcceleratorTable::ValueIterator::ValueIterator().
setAddressSize()
void llvm::DataExtractor::setAddressSize (uint8_t Size) inline
Set the address size for this extractor.
Definition at line 60 of file DataExtractor.h.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
The documentation for this class was generated from the following files:
include/llvm/Support/DataExtractor.h
lib/Support/DataExtractor.cpp