LLVM: llvm::VPBlendRecipe Class Reference
llvm::VPBlendRecipe Class Reference
A recipe for vectorizing a phi-node as a sequence of mask-based select instructions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPBlendRecipe (PHINode *Phi, ArrayRef< VPValue * > Masks)
void execute (VPTransformState &State) override
Generate the phi/select nodes.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Detailed Description
A recipe for vectorizing a phi-node as a sequence of mask-based select instructions.
Definition at line 787 of file VPlan.h.
Constructor & Destructor Documentation
VPBlendRecipe()
llvm::VPBlendRecipe::VPBlendRecipe (PHINode * Phi, ArrayRef< VPValue * > Masks) inline
Definition at line 795 of file VPlan.h.
References assert(), llvm::ArrayRef< T >::empty(), llvm::PHINode::getNumIncomingValues(), and llvm::ArrayRef< T >::size().
Member Function Documentation
classof()
static bool llvm::VPBlendRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 805 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPBlendRecipe::execute (VPTransformState & State) override virtual
Generate the phi/select nodes.
Implements llvm::VPRecipeBase.
Definition at line 7055 of file LoopVectorize.cpp.
References assert(), llvm::VPTransformState::Builder, llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::VPTransformState::get(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::VPTransformState::ILV, llvm::InnerLoopVectorizer::setDebugLocFromInst(), llvm::VectorizerValueMap::setVectorValue(), llvm::VPTransformState::UF, and llvm::VPTransformState::ValueMap.
print()
void VPBlendRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 654 of file VPlan.cpp.
References E, llvm::PHINode::getIncomingValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, and llvm::Value::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp