LLVM: llvm::GraphDiff< NodePtr, InverseGraph > Class Template Reference
llvm::GraphDiff< NodePtr, InverseGraph > Class Template Reference
#include "llvm/IR/CFGDiff.h"
Public Member Functions
GraphDiff ()
GraphDiff (ArrayRef< cfg::Update< NodePtr > > Updates)
bool ignoreChild (const NodePtr BB, NodePtr EdgeEnd, bool InverseEdge) const
iterator_range< typename SmallVectorImpl< NodePtr >::const_iterator > getAddedChildren (const NodePtr BB, bool InverseEdge) const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
template<typename NodePtr, bool InverseGraph = false>
class llvm::GraphDiff< NodePtr, InverseGraph >
Definition at line 80 of file CFGDiff.h.
Constructor & Destructor Documentation
GraphDiff() [1/2]
template<typename NodePtr , bool InverseGraph = false> llvm::GraphDiff< NodePtr, InverseGraph >::GraphDiff () inline
Definition at line 103 of file CFGDiff.h.
GraphDiff() [2/2]
template<typename NodePtr , bool InverseGraph = false> llvm::GraphDiff< NodePtr, InverseGraph >::GraphDiff (ArrayRef< cfg::Update< NodePtr > > Updates) inline
Definition at line 104 of file CFGDiff.h.
References llvm::cfg::Insert.
Member Function Documentation
dump()
template<typename NodePtr , bool InverseGraph = false> LLVM_DUMP_METHOD void llvm::GraphDiff< NodePtr, InverseGraph >::dump () const inline
Definition at line 154 of file CFGDiff.h.
References llvm::dbgs(), and llvm::GraphDiff< NodePtr, InverseGraph >::print().
getAddedChildren()
template<typename NodePtr , bool InverseGraph = false> iterator_range< typename SmallVectorImpl< NodePtr >::const_iterator > llvm::GraphDiff< NodePtr, InverseGraph >::getAddedChildren (const NodePtr BB, bool InverseEdge) const inline
Definition at line 129 of file CFGDiff.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::make_range().
ignoreChild()
template<typename NodePtr , bool InverseGraph = false> bool llvm::GraphDiff< NodePtr, InverseGraph >::ignoreChild (const NodePtr BB, NodePtr EdgeEnd, bool InverseEdge) const inline
Definition at line 118 of file CFGDiff.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::find().
print()
template<typename NodePtr , bool InverseGraph = false> void llvm::GraphDiff< NodePtr, InverseGraph >::print (raw_ostream & OS) const inline
Definition at line 138 of file CFGDiff.h.
Referenced by llvm::GraphDiff< NodePtr, InverseGraph >::dump().
The documentation for this class was generated from the following file:
include/llvm/IR/CFGDiff.h