LLVM: llvm::MCSection Class Reference
llvm::MCSection Class Reference abstract
Instances of this class represent a uniqued identifier for a section in the current translation unit.
#include "llvm/MC/MCSection.h"
Public Types
enum SectionVariant {
SV_COFF = 0 , SV_ELF , SV_MachO , SV_Wasm ,
SV_XCOFF
}
enum BundleLockStateType { NotBundleLocked , BundleLocked , BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Public Member Functions
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
unsigned getAlignment () const
void setAlignment (unsigned Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool hasData () const
void setHasData (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
virtual void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const =0
virtual bool UseCodeAlign () const =0
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
virtual bool isVirtualSection () const =0
Check whether this section is "virtual", that is has no actual object file contents.
Static Public Member Functions
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Protected Member Functions
MCSection (SectionVariant V, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes
SectionVariant Variant
SectionKind Kind
Detailed Description
Instances of this class represent a uniqued identifier for a section in the current translation unit.
The MCContext class uniques and creates these.
Definition at line 38 of file MCSection.h.
Member Typedef Documentation
const_iterator
using llvm::MCSection::const_iterator = FragmentListType::const_iterator
Definition at line 51 of file MCSection.h.
const_reverse_iterator
using llvm::MCSection::const_reverse_iterator = FragmentListType::const_reverse_iterator
Definition at line 54 of file MCSection.h.
FragmentListType
using llvm::MCSection::FragmentListType = iplist<MCFragment>
Definition at line 49 of file MCSection.h.
iterator
using llvm::MCSection::iterator = FragmentListType::iterator
Definition at line 52 of file MCSection.h.
reverse_iterator
using llvm::MCSection::reverse_iterator = FragmentListType::reverse_iterator
Definition at line 55 of file MCSection.h.
Member Enumeration Documentation
BundleLockStateType
enum llvm::MCSection::BundleLockStateType
Express the state of bundle locked groups while emitting code.
Enumerator
NotBundleLocked
BundleLocked
BundleLockedAlignToEnd
Definition at line 43 of file MCSection.h.
SectionVariant
enum llvm::MCSection::SectionVariant
Enumerator
SV_COFF
SV_ELF
SV_MachO
SV_Wasm
SV_XCOFF
Definition at line 40 of file MCSection.h.
Constructor & Destructor Documentation
MCSection() [1/2]
MCSection::MCSection (SectionVariant V, SectionKind K, MCSymbol * Begin) protected
Definition at line 23 of file MCSection.cpp.
~MCSection()
MCSection::~MCSection () protected default
MCSection() [2/2]
llvm::MCSection::MCSection (const MCSection &) delete
Member Function Documentation
begin() [1/2]
iterator llvm::MCSection::begin () inline
Definition at line 162 of file MCSection.h.
Referenced by dump().
begin() [2/2]
const_iterator llvm::MCSection::begin () const inline
Definition at line 163 of file MCSection.h.
dump()
LLVM_DUMP_METHOD void MCSection::dump () const
Definition at line 90 of file MCSection.cpp.
References begin(), end(), and llvm::errs().
end() [1/2]
iterator llvm::MCSection::end () inline
Definition at line 165 of file MCSection.h.
Referenced by dump(), and getSubsectionInsertionPoint().
end() [2/2]
const_iterator llvm::MCSection::end () const inline
Definition at line 166 of file MCSection.h.
getAlignment()
unsigned llvm::MCSection::getAlignment () const inline
Definition at line 120 of file MCSection.h.
Referenced by addData(), llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::MCObjectStreamer::EmitValueToAlignment(), llvm::MipsTargetELFStreamer::finish(), getAlignment(), llvm::MachObjectWriter::getPaddingSize(), and llvm::MCCodePadder::relaxFragment().
getBeginSymbol() [1/2]
MCSymbol * llvm::MCSection::getBeginSymbol () inline
Definition at line 109 of file MCSection.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfUnit::addLoclistsBase(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfUnit::addStringOffsetsStart(), llvm::MCContext::createELFRelSection(), llvm::DwarfUnit::emitCommonHeader(), getBeginSymbol(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::DwarfCompileUnit::initStmtList(), and llvm::MCDwarfLineStr::MCDwarfLineStr().
getBeginSymbol() [2/2]
const MCSymbol * llvm::MCSection::getBeginSymbol () const inline
Definition at line 110 of file MCSection.h.
References getBeginSymbol().
getBundleLockState()
BundleLockStateType llvm::MCSection::getBundleLockState () const inline
Definition at line 129 of file MCSection.h.
Referenced by llvm::MCELFStreamer::EmitBundleUnlock().
getDummyFragment() [1/2]
MCDummyFragment & llvm::MCSection::getDummyFragment () inline
Definition at line 160 of file MCSection.h.
getDummyFragment() [2/2]
const MCDummyFragment & llvm::MCSection::getDummyFragment () const inline
Definition at line 159 of file MCSection.h.
getEndSymbol()
MCSymbol * MCSection::getEndSymbol (MCContext & Ctx)
Definition at line 28 of file MCSection.cpp.
References llvm::MCContext::createTempSymbol().
getFragmentList() [1/2]
MCSection::FragmentListType & llvm::MCSection::getFragmentList () inline
Definition at line 149 of file MCSection.h.
Referenced by llvm::MCObjectStreamer::flushPendingLabels(), getFragmentList(), llvm::MCAsmLayout::getSectionAddressSize(), getSubsectionInsertionPoint(), llvm::MCObjectStreamer::insert(), llvm::MCAssembler::layout(), and llvm::MCFragment::MCFragment().
getFragmentList() [2/2]
const MCSection::FragmentListType & llvm::MCSection::getFragmentList () const inline
Definition at line 150 of file MCSection.h.
References getFragmentList().
getKind()
SectionKind llvm::MCSection::getKind () const inline
Definition at line 105 of file MCSection.h.
References Kind.
Referenced by llvm::MCContext::getAssociativeCOFFSection(), llvm::MCSectionXCOFF::isVirtualSection(), llvm::MCSectionXCOFF::PrintSwitchToSection(), llvm::MCSectionCOFF::UseCodeAlign(), and llvm::MCSectionXCOFF::UseCodeAlign().
getLayoutOrder()
unsigned llvm::MCSection::getLayoutOrder () const inline
Definition at line 126 of file MCSection.h.
Referenced by llvm::MachObjectWriter::getPaddingSize().
getOrdinal()
unsigned llvm::MCSection::getOrdinal () const inline
Definition at line 123 of file MCSection.h.
getSublistAccess()
static FragmentListType MCSection::* llvm::MCSection::getSublistAccess (MCFragment *) inline static
Support for MCFragment::getNextNode().
Definition at line 155 of file MCSection.h.
getSubsectionInsertionPoint()
MCSection::iterator MCSection::getSubsectionInsertionPoint (unsigned Subsection)
Definition at line 58 of file MCSection.cpp.
References end(), F, getFragmentList(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), and MI.
getVariant()
SectionVariant llvm::MCSection::getVariant () const inline
Definition at line 107 of file MCSection.h.
References Variant.
Referenced by llvm::MCSectionCOFF::classof(), llvm::MCSectionELF::classof(), llvm::MCSectionMachO::classof(), llvm::MCSectionWasm::classof(), and llvm::MCSectionXCOFF::classof().
hasData()
bool llvm::MCSection::hasData () const inline
Definition at line 143 of file MCSection.h.
hasEnded()
bool MCSection::hasEnded () const
Definition at line 34 of file MCSection.cpp.
References llvm::MCSymbol::isInSection().
hasInstructions()
bool llvm::MCSection::hasInstructions () const inline
Definition at line 140 of file MCSection.h.
Referenced by llvm::MCObjectStreamer::mayHaveInstructions().
isBundleGroupBeforeFirstInst()
bool llvm::MCSection::isBundleGroupBeforeFirstInst () const inline
Definition at line 133 of file MCSection.h.
Referenced by llvm::MCELFStreamer::EmitBundleUnlock().
isBundleLocked()
bool llvm::MCSection::isBundleLocked () const inline
Definition at line 131 of file MCSection.h.
References NotBundleLocked.
isRegistered()
bool llvm::MCSection::isRegistered () const inline
Definition at line 146 of file MCSection.h.
isVirtualSection()
virtual bool llvm::MCSection::isVirtualSection () const pure virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implemented in llvm::MCSectionCOFF, llvm::MCSectionELF, llvm::MCSectionMachO, llvm::MCSectionWasm, and llvm::MCSectionXCOFF.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::MachObjectWriter::getPaddingSize(), llvm::MCAsmLayout::getSectionFileSize(), and llvm::MCAssembler::writeSectionData().
operator=()
MCSection & llvm::MCSection::operator= (const MCSection &) delete
PrintSwitchToSection()
virtual void llvm::MCSection::PrintSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const pure virtual
Implemented in llvm::MCSectionCOFF, llvm::MCSectionELF, llvm::MCSectionMachO, llvm::MCSectionWasm, and llvm::MCSectionXCOFF.
rbegin() [1/2]
reverse_iterator llvm::MCSection::rbegin () inline
Definition at line 168 of file MCSection.h.
rbegin() [2/2]
const_reverse_iterator llvm::MCSection::rbegin () const inline
Definition at line 169 of file MCSection.h.
rend() [1/2]
reverse_iterator llvm::MCSection::rend () inline
Definition at line 171 of file MCSection.h.
rend() [2/2]
const_reverse_iterator llvm::MCSection::rend () const inline
Definition at line 172 of file MCSection.h.
setAlignment()
void llvm::MCSection::setAlignment (unsigned Value) inline
Definition at line 121 of file MCSection.h.
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolIndex(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MCObjectStreamer::EmitValueToAlignment(), and llvm::MipsTargetELFStreamer::finish().
setBeginSymbol()
void llvm::MCSection::setBeginSymbol (MCSymbol * Sym) inline
Definition at line 113 of file MCSection.h.
References assert().
setBundleGroupBeforeFirstInst()
void llvm::MCSection::setBundleGroupBeforeFirstInst (bool IsFirst) inline
Definition at line 136 of file MCSection.h.
Referenced by llvm::MCELFStreamer::EmitBundleLock().
setBundleLockState()
void MCSection::setBundleLockState (BundleLockStateType NewState)
Definition at line 38 of file MCSection.cpp.
References BundleLockedAlignToEnd, NotBundleLocked, and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::EmitBundleLock(), and llvm::MCELFStreamer::EmitBundleUnlock().
setHasData()
void llvm::MCSection::setHasData (bool Value) inline
Definition at line 144 of file MCSection.h.
Referenced by llvm::MCObjectStreamer::EmitBytes().
setHasInstructions()
void llvm::MCSection::setHasInstructions (bool Value) inline
Definition at line 141 of file MCSection.h.
setIsRegistered()
void llvm::MCSection::setIsRegistered (bool Value) inline
Definition at line 147 of file MCSection.h.
setLayoutOrder()
void llvm::MCSection::setLayoutOrder (unsigned Value) inline
Definition at line 127 of file MCSection.h.
Referenced by llvm::MCAssembler::layout().
setOrdinal()
void llvm::MCSection::setOrdinal (unsigned Value) inline
Definition at line 124 of file MCSection.h.
Referenced by llvm::MCAssembler::layout().
UseCodeAlign()
virtual bool llvm::MCSection::UseCodeAlign () const pure virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implemented in llvm::MCSectionCOFF, llvm::MCSectionELF, llvm::MCSectionMachO, llvm::MCSectionWasm, and llvm::MCSectionXCOFF.
Referenced by llvm::MCAssembler::computeFragmentSize().
Member Data Documentation
Kind
SectionKind llvm::MCSection::Kind protected
Definition at line 96 of file MCSection.h.
Referenced by getKind(), and llvm::MCSectionWasm::isWasmData().
Variant
SectionVariant llvm::MCSection::Variant protected
Definition at line 95 of file MCSection.h.
Referenced by getVariant().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSection.h
lib/MC/MCSection.cpp