LLVM: llvm::IRBuilderBase Class Reference
llvm::IRBuilderBase Class Reference
Common base class shared among various IRBuilders.
#include "llvm/IR/IRBuilder.h"
Classes
class FastMathFlagGuard
class InsertPoint
InsertPoint - A saved insertion point.
class InsertPointGuard
Public Member Functions
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
const DebugLoc & getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void setDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void setFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
void setIsFPConstrained (bool IsCon)
Enable/Disable use of constrained floating point math.
bool getIsFPConstrained ()
Query for the use of constrained floating point math.
void setDefaultConstrainedExcept (ConstrainedFPIntrinsic::ExceptionBehavior NewExcept)
Set the exception handling to be used with constrained floating point.
void setDefaultConstrainedRounding (ConstrainedFPIntrinsic::RoundingMode NewRounding)
Set the rounding mode handling to be used with constrained floating point.
ConstrainedFPIntrinsic::ExceptionBehavior getDefaultConstrainedExcept ()
Get the exception handling used with constrained floating point.
ConstrainedFPIntrinsic::RoundingMode getDefaultConstrainedRounding ()
Get the rounding mode handling used with constrained floating point.
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memcpy between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memmove between the specified pointers.
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateFAddReduce (Value *Acc, Value *Src)
Create a vector fadd reduction intrinsic of the source vector.
CallInst * CreateFMulReduce (Value *Acc, Value *Src)
Create a vector fmul reduction intrinsic of the source vector.
CallInst * CreateAddReduce (Value *Src)
Create a vector int add reduction intrinsic of the source vector.
CallInst * CreateMulReduce (Value *Src)
Create a vector int mul reduction intrinsic of the source vector.
CallInst * CreateAndReduce (Value *Src)
Create a vector int AND reduction intrinsic of the source vector.
CallInst * CreateOrReduce (Value *Src)
Create a vector int OR reduction intrinsic of the source vector.
CallInst * CreateXorReduce (Value *Src)
Create a vector int XOR reduction intrinsic of the source vector.
CallInst * CreateIntMaxReduce (Value *Src, bool IsSigned=false)
Create a vector integer max reduction intrinsic of the source vector.
CallInst * CreateIntMinReduce (Value *Src, bool IsSigned=false)
Create a vector integer min reduction intrinsic of the source vector.
CallInst * CreateFPMaxReduce (Value *Src, bool NoNaN=false)
Create a vector float max reduction intrinsic of the source vector.
CallInst * CreateFPMinReduce (Value *Src, bool NoNaN=false)
Create a vector float min reduction intrinsic of the source vector.
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateInvariantStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a call to invariant.start intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateMaskedGather (Value *Ptrs, unsigned Align, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Gather intrinsic.
CallInst * CreateMaskedScatter (Value *Val, Value *Ptrs, unsigned Align, Value *Mask=nullptr)
Create a call to Masked Scatter intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
CallInst * CreateUnaryIntrinsic (Intrinsic::ID ID, Value *V, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
CallInst * CreateBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
CallInst * CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type * > Types, ArrayRef< Value * > Args, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with args, mangled using Types.
CallInst * CreateMinNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minnum intrinsic.
CallInst * CreateMaxNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maxnum intrinsic.
CallInst * CreateMinimum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minimum intrinsic.
CallInst * CreateMaximum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maximum intrinsic.
Protected Attributes
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
bool IsFPConstrained
ConstrainedFPIntrinsic::ExceptionBehavior DefaultConstrainedExcept
ConstrainedFPIntrinsic::RoundingMode DefaultConstrainedRounding
ArrayRef< OperandBundleDef > DefaultOperandBundles
Detailed Description
Common base class shared among various IRBuilders.
Definition at line 88 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilderBase()
llvm::IRBuilderBase::IRBuilderBase (LLVMContext & context, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 106 of file IRBuilder.h.
References ClearInsertionPoint().
Member Function Documentation
clearFastMathFlags()
void llvm::IRBuilderBase::clearFastMathFlags () inline
Clear the fast-math flags.
Definition at line 219 of file IRBuilder.h.
References llvm::FastMathFlags::clear(), and FMF.
ClearInsertionPoint()
void llvm::IRBuilderBase::ClearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 121 of file IRBuilder.h.
References BB, and InsertPt.
Referenced by llvm::SCEVExpander::clearInsertPoint(), IRBuilderBase(), restoreIP(), saveAndClearIP(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
CreateAddReduce()
CallInst * IRBuilderBase::CreateAddReduce (Value * Src)
Create a vector int add reduction intrinsic of the source vector.
Definition at line 339 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateAndReduce()
CallInst * IRBuilderBase::CreateAndReduce (Value * Src)
Create a vector int AND reduction intrinsic of the source vector.
Definition at line 349 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateAssumption()
CallInst * IRBuilderBase::CreateAssumption (Value * Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
Definition at line 450 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1Ty(), and llvm::BasicBlock::getParent().
CreateBinaryIntrinsic()
CallInst * IRBuilderBase::CreateBinaryIntrinsic (Intrinsic::ID ID, Value * LHS, Value * RHS, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
Definition at line 739 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getModule(), llvm::Value::getType(), and Name.
Referenced by canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), CreateMaximum(), CreateMaxNum(), CreateMinimum(), CreateMinNum(), and llvm::InstCombiner::visitCallInst().
CreateElementUnorderedAtomicMemCpy() [1/2]
CallInst * llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert an element unordered-atomic memcpy between the specified pointers.
DstAlign/SrcAlign are the alignments of the Dst/Src pointers, respectively.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 508 of file IRBuilder.h.
References CreateElementUnorderedAtomicMemCpy(), getInt64(), and Size.
Referenced by CreateElementUnorderedAtomicMemCpy().
CreateElementUnorderedAtomicMemCpy() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 196 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, llvm::Instruction::setMetadata(), and Size.
CreateElementUnorderedAtomicMemMove() [1/2]
CallInst * llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert an element unordered-atomic memmove between the specified pointers.
DstAlign/SrcAlign are the alignments of the Dst/Src pointers, respectively.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 552 of file IRBuilder.h.
References CreateElementUnorderedAtomicMemMove(), getInt64(), and Size.
Referenced by CreateElementUnorderedAtomicMemMove().
CreateElementUnorderedAtomicMemMove() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 272 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), assert(), BB, createCallHelper(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::Attribute::getWithAlignment(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, llvm::Instruction::setMetadata(), and Size.
CreateElementUnorderedAtomicMemSet() [1/2]
CallInst * llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet (Value * Ptr, Value * Val, uint64_t Size, unsigned Align, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 459 of file IRBuilder.h.
References CreateElementUnorderedAtomicMemSet(), getInt64(), and Size.
Referenced by CreateElementUnorderedAtomicMemSet().
CreateElementUnorderedAtomicMemSet() [2/2]
CallInst * IRBuilderBase::CreateElementUnorderedAtomicMemSet (Value * Ptr, Value * Val, Value * Size, unsigned Align, uint32_t ElementSize, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 127 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::Instruction::setMetadata(), and Size.
CreateFAddReduce()
CallInst * IRBuilderBase::CreateFAddReduce (Value * Acc, Value * Src)
Create a vector fadd reduction intrinsic of the source vector.
The first parameter is a scalar accumulator value for ordered reductions.
Definition at line 321 of file IRBuilder.cpp.
References createCallHelper(), llvm::Intrinsic::getDeclaration(), GetInsertBlock(), llvm::BasicBlock::getParent(), and llvm::Value::getType().
Referenced by llvm::createSimpleTargetReduction().
CreateFMulReduce()
CallInst * IRBuilderBase::CreateFMulReduce (Value * Acc, Value * Src)
Create a vector fmul reduction intrinsic of the source vector.
The first parameter is a scalar accumulator value for ordered reductions.
Definition at line 330 of file IRBuilder.cpp.
References createCallHelper(), llvm::Intrinsic::getDeclaration(), GetInsertBlock(), llvm::BasicBlock::getParent(), and llvm::Value::getType().
Referenced by llvm::createSimpleTargetReduction().
CreateFPMaxReduce()
CallInst * IRBuilderBase::CreateFPMaxReduce (Value * Src, bool NoNaN = false)
Create a vector float max reduction intrinsic of the source vector.
Definition at line 376 of file IRBuilder.cpp.
References FMF, getReductionIntrinsic(), and llvm::FastMathFlags::setNoNaNs().
Referenced by llvm::createSimpleTargetReduction().
CreateFPMinReduce()
CallInst * IRBuilderBase::CreateFPMinReduce (Value * Src, bool NoNaN = false)
Create a vector float min reduction intrinsic of the source vector.
Definition at line 387 of file IRBuilder.cpp.
References FMF, getReductionIntrinsic(), and llvm::FastMathFlags::setNoNaNs().
Referenced by llvm::createSimpleTargetReduction().
CreateGCRelocate()
CallInst * IRBuilderBase::CreateGCRelocate (Instruction * Statepoint, int BaseOffset, int DerivedOffset, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Definition at line 715 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), and Name.
CreateGCResult()
CallInst * IRBuilderBase::CreateGCResult (Instruction * Statepoint, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
Definition at line 703 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getParent(), and Name.
Referenced by makeStatepointExplicitImpl().
CreateGCStatepointCall() [1/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
Definition at line 640 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGCStatepointCall() [2/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 622 of file IRBuilder.cpp.
References Name, and llvm::None.
Referenced by makeStatepointExplicitImpl().
CreateGCStatepointCall() [3/3]
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< Use > CallArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 631 of file IRBuilder.cpp.
References Name.
CreateGCStatepointInvoke() [1/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Definition at line 693 of file IRBuilder.cpp.
References Name, and llvm::None.
CreateGCStatepointInvoke() [2/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 672 of file IRBuilder.cpp.
References Name, and llvm::None.
Referenced by makeStatepointExplicitImpl().
CreateGCStatepointInvoke() [3/3]
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, uint32_t Flags, ArrayRef< Use > InvokeArgs, ArrayRef< Use > TransitionArgs, ArrayRef< Use > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 683 of file IRBuilder.cpp.
References Name.
CreateGlobalString()
GlobalVariable * IRBuilderBase::CreateGlobalString (StringRef Str, const Twine & Name = "", unsigned AddressSpace = 0)
Make a new global variable with initializer type i8*.
CreateGlobalString - Make a new global variable with an initializer that has array of i8 type filled in with the nul terminated string value specified.
Make a new global variable with an initializer that has array of i8 type filled in with the null terminated string value specified. The new global variable will be marked mergable with any others of the same contents. If Name is specified, it is the name of the global variable created.
If Name is specified, it is the name of the global variable created.
Definition at line 42 of file IRBuilder.cpp.
References BB, Context, llvm::BasicBlock::getParent(), llvm::msgpack::DocNode::getString(), llvm::Value::getType(), llvm::GlobalValue::Global, Name, llvm::GlobalValue::NotThreadLocal, and llvm::GlobalValue::PrivateLinkage.
Referenced by llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr().
CreateIntMaxReduce()
CallInst * IRBuilderBase::CreateIntMaxReduce (Value * Src, bool IsSigned = false)
Create a vector integer max reduction intrinsic of the source vector.
Definition at line 364 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateIntMinReduce()
CallInst * IRBuilderBase::CreateIntMinReduce (Value * Src, bool IsSigned = false)
Create a vector integer min reduction intrinsic of the source vector.
Definition at line 370 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateIntrinsic()
CallInst * IRBuilderBase::CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type * > Types, ArrayRef< Value * > Args, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with args, mangled using Types.
If FMFSource is provided, copy fast-math-flags from that instruction to the intrinsic.
Definition at line 748 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getModule(), and Name.
Referenced by llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), and simplifyX86addcarry().
CreateInvariantStart()
CallInst * IRBuilderBase::CreateInvariantStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a call to invariant.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 430 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::Value::getType(), and Size.
CreateLifetimeEnd()
CallInst * IRBuilderBase::CreateLifetimeEnd (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.end intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 414 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::Value::getType(), and Size.
Referenced by llvm::InlineFunction().
CreateLifetimeStart()
CallInst * IRBuilderBase::CreateLifetimeStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 398 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::Value::getType(), and Size.
Referenced by llvm::InlineFunction().
CreateMaskedGather()
CallInst * IRBuilderBase::CreateMaskedGather (Value * Ptrs, unsigned Align, Value * Mask = nullptr, Value * PassThru = nullptr, const Twine & Name = "")
Create a call to Masked Gather intrinsic.
Create a call to a Masked Gather intrinsic.
Ptrs - vector of pointers for loading Align - alignment for one element Mask - vector of booleans which indicates what vector lanes should be accessed in memory PassThru - pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 520 of file IRBuilder.cpp.
References Context, llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getAllOnesValue(), getInt1Ty(), getInt32(), llvm::Value::getType(), and Name.
Referenced by llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedLoad()
CallInst * IRBuilderBase::CreateMaskedLoad (Value * Ptr, unsigned Align, Value * Mask, Value * PassThru = nullptr, const Twine & Name = "")
Create a call to Masked Load intrinsic.
Create a call to a Masked Load intrinsic.
Ptr - base pointer for the load Align - alignment of the source location Mask - vector of booleans which indicates what vector lanes should be accessed in memory PassThru - pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 468 of file IRBuilder.cpp.
References assert(), llvm::IntervalMapImpl::NodeRef::get(), getInt32(), llvm::Value::getType(), llvm::Type::isVectorTy(), and Name.
Referenced by simplifyX86MaskedLoad(), UpgradeMaskedLoad(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedScatter()
CallInst * IRBuilderBase::CreateMaskedScatter (Value * Data, Value * Ptrs, unsigned Align, Value * Mask = nullptr)
Create a call to Masked Scatter intrinsic.
Create a call to a Masked Scatter intrinsic.
Data - data to be stored, Ptrs - the vector of pointers, where the Data elements should be stored Align - alignment for one element Mask - vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 551 of file IRBuilder.cpp.
References assert(), Context, llvm::Data, llvm::IntervalMapImpl::NodeRef::get(), llvm::Constant::getAllOnesValue(), getInt1Ty(), getInt32(), and llvm::Value::getType().
Referenced by llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaskedStore()
CallInst * IRBuilderBase::CreateMaskedStore (Value * Val, Value * Ptr, unsigned Align, Value * Mask)
Create a call to Masked Store intrinsic.
Create a call to a Masked Store intrinsic.
Val - data to be stored, Ptr - base pointer for the store Align - alignment of the destination location Mask - vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 489 of file IRBuilder.cpp.
References assert(), getInt32(), llvm::Value::getType(), and llvm::Type::isVectorTy().
Referenced by simplifyX86MaskedStore(), UpgradeMaskedStore(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), and llvm::InnerLoopVectorizer::vectorizeMemoryInstruction().
CreateMaximum()
CallInst * llvm::IRBuilderBase::CreateMaximum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the maximum intrinsic.
Definition at line 750 of file IRBuilder.h.
References CreateBinaryIntrinsic(), and Name.
CreateMaxNum()
CallInst * llvm::IRBuilderBase::CreateMaxNum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the maxnum intrinsic.
Definition at line 740 of file IRBuilder.h.
References CreateBinaryIntrinsic(), and Name.
Referenced by llvm::InstCombiner::visitCallInst().
CreateMemCpy() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memcpy between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 482 of file IRBuilder.h.
References CreateMemCpy(), getInt64(), isVolatile(), and Size.
Referenced by CreateMemCpy(), and HandleByValArgumentInit().
CreateMemCpy() [2/2]
CallInst * IRBuilderBase::CreateMemCpy (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 157 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::isPowerOf2_32(), isVolatile(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, llvm::Instruction::setMetadata(), and Size.
CreateMemMove() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, uint64_t Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memmove between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 530 of file IRBuilder.h.
References CreateMemMove(), getInt64(), isVolatile(), and Size.
Referenced by CreateMemMove().
CreateMemMove() [2/2]
CallInst * IRBuilderBase::CreateMemMove (Value * Dst, unsigned DstAlign, Value * Src, unsigned SrcAlign, Value * Size, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 237 of file IRBuilder.cpp.
References assert(), BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::Value::getType(), llvm::isPowerOf2_32(), isVolatile(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::Instruction::setMetadata(), and Size.
CreateMemSet() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memset to the specified pointer and the specified value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 440 of file IRBuilder.h.
References CreateMemSet(), getInt64(), isVolatile(), and Size.
Referenced by CreateMemSet().
CreateMemSet() [2/2]
CallInst * IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 99 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), llvm::BasicBlock::getParent(), llvm::Value::getType(), isVolatile(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::Instruction::setMetadata(), and Size.
CreateMinimum()
CallInst * llvm::IRBuilderBase::CreateMinimum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the minimum intrinsic.
Definition at line 745 of file IRBuilder.h.
References CreateBinaryIntrinsic(), and Name.
CreateMinNum()
CallInst * llvm::IRBuilderBase::CreateMinNum (Value * LHS, Value * RHS, const Twine & Name = "") inline
Create call to the minnum intrinsic.
Definition at line 735 of file IRBuilder.h.
References CreateBinaryIntrinsic(), and Name.
Referenced by llvm::InstCombiner::visitCallInst().
CreateMulReduce()
CallInst * IRBuilderBase::CreateMulReduce (Value * Src)
Create a vector int mul reduction intrinsic of the source vector.
Definition at line 344 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateOrReduce()
CallInst * IRBuilderBase::CreateOrReduce (Value * Src)
Create a vector int OR reduction intrinsic of the source vector.
Definition at line 354 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
CreateUnaryIntrinsic()
CallInst * IRBuilderBase::CreateUnaryIntrinsic (Intrinsic::ID ID, Value * V, Instruction * FMFSource = nullptr, const Twine & Name = "")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
Definition at line 731 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getModule(), llvm::Value::getType(), and Name.
Referenced by llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFMul().
CreateXorReduce()
CallInst * IRBuilderBase::CreateXorReduce (Value * Src)
Create a vector int XOR reduction intrinsic of the source vector.
Definition at line 359 of file IRBuilder.cpp.
References getReductionIntrinsic().
Referenced by llvm::createSimpleTargetReduction().
getContext()
LLVMContext & llvm::IRBuilderBase::getContext () const inline
Definition at line 128 of file IRBuilder.h.
References Context.
Referenced by createClone(), generateUnsignedDivisionCode(), SegmentOffset(), and llvm::InstCombiner::visitCallInst().
getCurrentDebugLocation()
const DebugLoc & llvm::IRBuilderBase::getCurrentDebugLocation () const inline
Get location information used by debugging information.
Definition at line 159 of file IRBuilder.h.
getCurrentFunctionReturnType()
Type * IRBuilderBase::getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
Definition at line 56 of file IRBuilder.cpp.
References assert(), BB, and llvm::BasicBlock::getParent().
Referenced by llvm::IRBuilder< T, Inserter >::CreateAggregateRet().
getDefaultConstrainedExcept()
ConstrainedFPIntrinsic::ExceptionBehavior llvm::IRBuilderBase::getDefaultConstrainedExcept () inline
Get the exception handling used with constrained floating point.
Definition at line 249 of file IRBuilder.h.
References DefaultConstrainedExcept.
getDefaultConstrainedRounding()
ConstrainedFPIntrinsic::RoundingMode llvm::IRBuilderBase::getDefaultConstrainedRounding () inline
Get the rounding mode handling used with constrained floating point.
Definition at line 254 of file IRBuilder.h.
References DefaultConstrainedRounding.
getDefaultFPMathTag()
MDNode * llvm::IRBuilderBase::getDefaultFPMathTag () const inline
Get the floating point math metadata being used.
Definition at line 213 of file IRBuilder.h.
References DefaultFPMathTag.
getDoubleTy()
Type * llvm::IRBuilderBase::getDoubleTy () inline
Fetch the type representing a 64-bit floating point value.
Definition at line 411 of file IRBuilder.h.
References Context, and getDoubleTy().
Referenced by DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantDataVector::get(), llvm::ConstantFP::get(), getDoubleTy(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getIntrinsicParamType(), llvm::Type::getScalarTy(), llvm::EVT::getTypeForEVT(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), llvm::LegalizerHelper::lower(), LowerFPToInt(), and shrinkFPConstant().
getFalse()
ConstantInt * llvm::IRBuilderBase::getFalse () inline
Get the constant value for i1 false.
Definition at line 328 of file IRBuilder.h.
References Context, and getFalse().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), createFFSIntrinsic(), llvm::deleteDeadLoop(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::SCEVExpander::expandWrapPredicate(), forceIndeterminateEdge(), llvm::ValueLatticeElement::getCompare(), getFalse(), llvm::ConstantInt::getFalse(), handleNoSuspendCoroutine(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), llvm::ScalarEvolution::SimplifyICmpOperands(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitBranchInst(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getFastMathFlags()
FastMathFlags llvm::IRBuilderBase::getFastMathFlags () const inline
Get the flags to be applied to created floating point ops.
Definition at line 216 of file IRBuilder.h.
References FMF.
getFloatTy()
Type * llvm::IRBuilderBase::getFloatTy () inline
Fetch the type representing a 32-bit floating point value.
Definition at line 406 of file IRBuilder.h.
References Context, and getFloatTy().
Referenced by llvm::MDBuilder::createFPMath(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantDataVector::get(), llvm::ConstantFP::get(), getFloatTy(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getIntrinsicParamType(), llvm::Type::getScalarTy(), llvm::EVT::getTypeForEVT(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), llvm::LegalizerHelper::lower(), LowerFPToInt(), shrinkFPConstant(), and llvm::InstCombiner::visitCallInst().
getHalfTy()
Type * llvm::IRBuilderBase::getHalfTy () inline
Fetch the type representing a 16-bit floating point value.
Definition at line 401 of file IRBuilder.h.
References Context, and getHalfTy().
Referenced by DecodeFixedType(), llvm::ConstantFP::get(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getHalfTy(), getIntrinsicParamType(), llvm::EVT::getTypeForEVT(), llvm::LegalizerHelper::lower(), shrinkFPConstant(), and llvm::InstCombiner::visitCallInst().
GetInsertBlock()
BasicBlock * llvm::IRBuilderBase::GetInsertBlock () const inline
Definition at line 126 of file IRBuilder.h.
References BB.
Referenced by callIntrinsic(), createCallHelper(), CreateFAddReduce(), createFFSIntrinsic(), CreateFMulReduce(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), createInvokeHelper(), createPopcntIntrinsic(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), generateUnsignedDivisionCode(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), llvm::TargetLoweringBase::getIRStackGuard(), getReductionIntrinsic(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::ARMTargetLowering::makeDMB(), saveAndClearIP(), saveIP(), and UseTlsOffset().
GetInsertPoint()
BasicBlock::iterator llvm::IRBuilderBase::GetInsertPoint () const inline
Definition at line 127 of file IRBuilder.h.
References InsertPt.
Referenced by createCallHelper(), createInvokeHelper(), llvm::expandDivision(), llvm::expandRemainder(), generateUnsignedDivisionCode(), insertBoundsCheck(), instrumentOneFunc(), mergeConditionalStoreToAddress(), saveAndClearIP(), and saveIP().
getInt()
ConstantInt * llvm::IRBuilderBase::getInt (const APInt & AI) inline
Get a constant integer value.
Definition at line 359 of file IRBuilder.h.
References Context, and llvm::IntervalMapImpl::NodeRef::get().
Referenced by despeculateCountZeros(), and llvm::InstCombiner::visitOr().
getInt1()
ConstantInt * llvm::IRBuilderBase::getInt1 (bool V) inline
Get a constant value representing either true or false.
Definition at line 318 of file IRBuilder.h.
References llvm::IntervalMapImpl::NodeRef::get(), and getInt1Ty().
Referenced by llvm::createBitMaskForGaps(), CreateMemCpy(), CreateMemMove(), and CreateMemSet().
getInt128Ty()
IntegerType * llvm::IRBuilderBase::getInt128Ty () inline
Fetch the type representing a 128-bit integer.
Definition at line 393 of file IRBuilder.h.
References Context, and getInt128Ty().
Referenced by llvm::IntegerType::get(), getInt128Ty(), and llvm::EVT::getTypeForEVT().
getInt16()
ConstantInt * llvm::IRBuilderBase::getInt16 (uint16_t C) inline
Get a constant 16-bit value.
Definition at line 338 of file IRBuilder.h.
References C, llvm::IntervalMapImpl::NodeRef::get(), and getInt16Ty().
getInt16Ty()
IntegerType * llvm::IRBuilderBase::getInt16Ty () inline
Fetch the type representing a 16-bit integer.
Definition at line 378 of file IRBuilder.h.
References Context, and getInt16Ty().
Referenced by llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getInt16(), getInt16Ty(), getIntrinsicParamType(), llvm::EVT::getTypeForEVT(), and llvm::UpgradeIntrinsicCall().
getInt1Ty()
IntegerType * llvm::IRBuilderBase::getInt1Ty () inline
Fetch the type representing a single bit.
Definition at line 368 of file IRBuilder.h.
References Context, and getInt1Ty().
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), CreateAssumption(), llvm::MDBuilder::createCallbackEncoding(), CreateMaskedGather(), CreateMaskedScatter(), EmitX86ScalarSelect(), llvm::IntegerType::get(), llvm::ConstantExpr::getAlignOf(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::ConstantExpr::getICmp(), getInt1(), getInt1Ty(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::ConstantInt::getTrue(), llvm::EVT::getTypeForEVT(), getX86MaskVec(), llvm::CmpInst::makeCmpResultType(), upgradeMaskedCompare(), llvm::InstCombiner::visitAllocSite(), and llvm::InstCombiner::visitCallInst().
getInt32()
ConstantInt * llvm::IRBuilderBase::getInt32 (uint32_t C) inline
Get a constant 32-bit value.
Definition at line 343 of file IRBuilder.h.
References C, llvm::IntervalMapImpl::NodeRef::get(), and getInt32Ty().
Referenced by appendToGlobalArray(), canonicalizeInsertSplat(), CreateElementUnorderedAtomicMemCpy(), CreateElementUnorderedAtomicMemMove(), CreateElementUnorderedAtomicMemSet(), CreateGCRelocate(), CreateGCRelocates(), llvm::createInterleaveMask(), CreateMaskedGather(), CreateMaskedLoad(), CreateMaskedScatter(), CreateMaskedStore(), createOrdering(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex(), createRdxShuffleMask(), llvm::createReplicatedMask(), llvm::createSequentialMask(), llvm::createStrideMask(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::VPBasicBlock::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), foldVecTruncToExtElt(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::getOrderedReduction(), llvm::getShuffleReduction(), instrumentOneFunc(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::makeDMB(), optimizeIntegerToVectorInsertions(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::InnerLoopVectorizer::reverseVector(), simplifyAllocaArraySize(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitExtractValueInst().
getInt32Ty()
IntegerType * llvm::IRBuilderBase::getInt32Ty () inline
Fetch the type representing a 32-bit integer.
Definition at line 383 of file IRBuilder.h.
References Context, and getInt32Ty().
Referenced by llvm::Module::addModuleFlag(), llvm::annotateValueSite(), appendToGlobalArray(), BuildConstantFromSCEV(), collectShuffleElements(), collectSingleShuffleElements(), llvm::ShuffleVectorInst::commute(), llvm::convertPointerToIntegerType(), llvm::ARMConstantPoolConstant::Create(), llvm::MDBuilder::createBranchWeights(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), createPrivateGlobalForSourceLoc(), createRdxShuffleMask(), llvm::createSequentialMask(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::deleteDeadLoop(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), evaluateInDifferentElementOrder(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), llvm::SanitizerStatReport::finish(), foldConstantInsEltIntoShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getAISize(), llvm::ConstantExpr::getAlignOf(), getGlobalVariableI32(), getInt32(), getInt32Ty(), getIntrinsicParamType(), getMul64(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), llvm::getShuffleReduction(), llvm::ConstantExpr::getSizeOf(), llvm::EVT::getTypeForEVT(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), llvm::XCoreInstrInfo::loadImmediate(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::EscapeEnumerator::Next(), replaceExtractElements(), SegmentOffset(), simplifyX86extrq(), simplifyX86insertq(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitShuffleVectorInst(), and llvm::BasicBlock::~BasicBlock().
getInt64()
ConstantInt * llvm::IRBuilderBase::getInt64 (uint64_t C) inline
Get a constant 64-bit value.
Definition at line 348 of file IRBuilder.h.
References C, llvm::IntervalMapImpl::NodeRef::get(), and getInt64Ty().
Referenced by CreateElementUnorderedAtomicMemCpy(), CreateElementUnorderedAtomicMemMove(), CreateElementUnorderedAtomicMemSet(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), CreateInvariantStart(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), getMul64(), HandleByValArgumentInit(), and instrumentOneFunc().
getInt64Ty()
IntegerType * llvm::IRBuilderBase::getInt64Ty () inline
Fetch the type representing a 64-bit integer.
Definition at line 388 of file IRBuilder.h.
References Context, and getInt64Ty().
Referenced by llvm::GlobalObject::addTypeMetadata(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::annotateValueSite(), llvm::MDBuilder::createCallbackEncoding(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), llvm::MDBuilder::createFunctionEntryCount(), CreateInvariantStart(), llvm::createIRLevelProfileFlagVar(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), CreateLifetimeEnd(), CreateLifetimeStart(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo64Bits(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), llvm::ConstantExpr::getAlignOf(), getInt64(), getInt64Ty(), getIntrinsicParamType(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getMul64(), llvm::ConstantExpr::getOffsetOf(), llvm::ConstantExpr::getSizeOf(), llvm::InstrProfIncrementInst::getStep(), llvm::EVT::getTypeForEVT(), insertLifetimeMarkersSurroundingCall(), instrumentOneFunc(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::LegalizerHelper::libcall(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), simplifyX86extrq(), simplifyX86insertq(), unpackLoadToAggregate(), unpackStoreToAggregate(), and llvm::CallInst::updateProfWeight().
getInt8()
ConstantInt * llvm::IRBuilderBase::getInt8 (uint8_t C) inline
Get a constant 8-bit value.
Definition at line 333 of file IRBuilder.h.
References C, llvm::IntervalMapImpl::NodeRef::get(), and getInt8Ty().
Referenced by convert_i1_to_i8(), createClone(), createResumeEntryBlock(), and llvm::UpgradeIntrinsicCall().
getInt8PtrTy()
PointerType * llvm::IRBuilderBase::getInt8PtrTy (unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an 8-bit integer value.
Definition at line 421 of file IRBuilder.h.
References Context, and llvm::Type::getInt8PtrTy().
Referenced by appendToGlobalArray(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), handleNoSuspendCoroutine(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::UpgradeGlobalVariable(), and UseTlsOffset().
getInt8Ty()
IntegerType * llvm::IRBuilderBase::getInt8Ty () inline
Fetch the type representing an 8-bit integer.
Definition at line 373 of file IRBuilder.h.
References Context, and getInt8Ty().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), createResumeEntryBlock(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getEVTAlignment(), getInt8(), getInt8Ty(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), getIntrinsicParamType(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), llvm::VNCoercion::getMemInstValueForLoadHelper(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::EVT::getTypeForEVT(), isLoadInvariantInLoop(), llvm::coro::LowererBase::makeSubFnCall(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86insertq(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), and UseTlsOffset().
getIntN()
ConstantInt * llvm::IRBuilderBase::getIntN (unsigned N, uint64_t C) inline
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
Definition at line 354 of file IRBuilder.h.
References C, llvm::IntervalMapImpl::NodeRef::get(), getIntNTy(), and N.
getIntNTy()
IntegerType * llvm::IRBuilderBase::getIntNTy (unsigned N) inline
Fetch the type representing an N-bit integer.
Definition at line 396 of file IRBuilder.h.
References Context, llvm::Type::getIntNTy(), and N.
Referenced by ApplyX86MaskOn1BitsVec(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCmpXchgInstFun(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), foldBitcastExtElt(), getIntN(), simplifyX86movmsk(), and llvm::InstCombiner::visitCallInst().
getIntPtrTy()
IntegerType * llvm::IRBuilderBase::getIntPtrTy (const DataLayout & DL, unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an integer value.
Definition at line 426 of file IRBuilder.h.
References Context, and llvm::DataLayout::getIntPtrType().
Referenced by llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption().
getIsFPConstrained()
bool llvm::IRBuilderBase::getIsFPConstrained () inline
Query for the use of constrained floating point math.
Definition at line 234 of file IRBuilder.h.
References IsFPConstrained.
getTrue()
ConstantInt * llvm::IRBuilderBase::getTrue () inline
Get the constant value for i1 true.
Definition at line 323 of file IRBuilder.h.
References Context, and getTrue().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), createFFSIntrinsic(), llvm::InstCombiner::CreateNonTerminatorUnreachable(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), despeculateCountZeros(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::VPBranchOnMaskRecipe::execute(), foldCttzCtlz(), generateUnsignedDivisionCode(), llvm::ValueLatticeElement::getCompare(), getTrue(), llvm::ConstantInt::getTrue(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::InstCombiner::simplifyDivRemOfSelectWithZeroOp(), llvm::InstCombiner::visitCallInst(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getVoidTy()
Type * llvm::IRBuilderBase::getVoidTy () inline
Fetch the type representing void.
Definition at line 416 of file IRBuilder.h.
References Context, and getVoidTy().
Referenced by appendToGlobalArray(), createDummyFunction(), createFree(), llvm::createSanitizerCtorAndInitFunctions(), DecodeFixedType(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SanitizerStatReport::finish(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), getOrInsertValueProfilingCall(), llvm::EVT::getTypeForEVT(), getVoidTy(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), insertUseHolderAfter(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Op(), llvm::IntrinsicLowering::LowerIntrinsicCall(), makeStatepointExplicitImpl(), and llvm::Interpreter::visitReturnInst().
restoreIP()
void llvm::IRBuilderBase::restoreIP (InsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 205 of file IRBuilder.h.
References ClearInsertionPoint(), llvm::IRBuilderBase::InsertPoint::getBlock(), llvm::IRBuilderBase::InsertPoint::getPoint(), llvm::IRBuilderBase::InsertPoint::isSet(), and SetInsertPoint().
Referenced by llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
saveAndClearIP()
InsertPoint llvm::IRBuilderBase::saveAndClearIP () inline
Returns the current insert point, clearing it in the process.
Definition at line 198 of file IRBuilder.h.
References ClearInsertionPoint(), GetInsertBlock(), and GetInsertPoint().
saveIP()
InsertPoint llvm::IRBuilderBase::saveIP () const inline
Returns the current insert point.
Definition at line 193 of file IRBuilder.h.
References GetInsertBlock(), and GetInsertPoint().
Referenced by llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), and llvm::InnerLoopVectorizer::getOrCreateVectorValue().
SetCurrentDebugLocation()
void llvm::IRBuilderBase::SetCurrentDebugLocation (DebugLoc L) inline
Set location information used by debugging information.
Definition at line 156 of file IRBuilder.h.
Referenced by despeculateCountZeros(), llvm::VNCoercion::getLoadValueForLoad(), makeStatepointExplicitImpl(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::InstCombiner::run(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), SetInsertPoint(), simplifyRelocatesOffABase(), SimplifyTerminatorOnSelect(), and llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
setDefaultConstrainedExcept()
void llvm::IRBuilderBase::setDefaultConstrainedExcept (ConstrainedFPIntrinsic::ExceptionBehavior NewExcept) inline
Set the exception handling to be used with constrained floating point.
Definition at line 237 of file IRBuilder.h.
References DefaultConstrainedExcept.
setDefaultConstrainedRounding()
void llvm::IRBuilderBase::setDefaultConstrainedRounding (ConstrainedFPIntrinsic::RoundingMode NewRounding) inline
Set the rounding mode handling to be used with constrained floating point.
Definition at line 243 of file IRBuilder.h.
References DefaultConstrainedRounding.
setDefaultFPMathTag()
void llvm::IRBuilderBase::setDefaultFPMathTag (MDNode * FPMathTag) inline
Set the floating point math metadata to be used.
Definition at line 222 of file IRBuilder.h.
References DefaultFPMathTag.
setFastMathFlags()
void llvm::IRBuilderBase::setFastMathFlags (FastMathFlags NewFMF) inline
Set the fast-math flags to be used with generated fp-math operators.
Definition at line 225 of file IRBuilder.h.
References FMF.
Referenced by llvm::createMinMaxOp(), llvm::InstCombiner::visitCallInst(), and llvm::InnerLoopVectorizer::widenInstruction().
SetInsertPoint() [1/3]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB) inline
This specifies that created instructions should be appended to the end of the specified block.
Definition at line 132 of file IRBuilder.h.
References BB, llvm::BasicBlock::end(), and InsertPt.
Referenced by combineLoadToOperationType(), llvm::InnerLoopVectorizer::createInductionVariable(), createResumeEntryBlock(), createRetPHINode(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::deleteDeadLoop(), despeculateCountZeros(), llvm::VPlan::execute(), llvm::VPBasicBlock::execute(), llvm::SCEVExpander::expandEqualPredicate(), llvm::SCEVExpander::expandUnionPredicate(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::InnerLoopVectorizer::fixReduction(), FoldTwoEntryPHINode(), generatedUnsignedRemainderCode(), llvm::SCEVExpander::generateOverflowCheck(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), handleFinalSuspend(), insertSpills(), llvm::IRBuilder< T, Inserter >::IRBuilder(), llvm::lowerObjectSizeCall(), lowerSubFn(), makeStatepointExplicitImpl(), mergeConditionalStoreToAddress(), llvm::EscapeEnumerator::Next(), optimizeSQRT(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), ReduceSwitchRange(), removeBitcastsFromLoadStoreOnMinMax(), restoreIP(), llvm::InstCombiner::run(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), setInsertionPoint(), llvm::SCEVExpander::setInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), splitMergedValStore(), SwitchToLookupTable(), switchToSelect(), llvm::UnrollRuntimeLoopRemainder(), llvm::UpgradeIntrinsicCall(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), versionCallSite(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InstCombiner::visitSwitchInst().
SetInsertPoint() [2/3]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB, BasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 148 of file IRBuilder.h.
References BB, llvm::BasicBlock::end(), InsertPt, and SetCurrentDebugLocation().
SetInsertPoint() [3/3]
void llvm::IRBuilderBase::SetInsertPoint (Instruction * I) inline
This specifies that created instructions should be inserted before the specified instruction.
Definition at line 139 of file IRBuilder.h.
References assert(), BB, llvm::BasicBlock::end(), I, InsertPt, and SetCurrentDebugLocation().
SetInstDebugLocation()
void llvm::IRBuilderBase::SetInstDebugLocation (Instruction * I) const inline
If this builder has a current debug location, set it on the specified instruction.
Definition at line 163 of file IRBuilder.h.
References I.
Referenced by createCallHelper(), createInvokeHelper(), and llvm::IRBuilder< T, Inserter >::Insert().
setIsFPConstrained()
void llvm::IRBuilderBase::setIsFPConstrained (bool IsCon) inline
Enable/Disable use of constrained floating point math.
When enabled the CreateF<op>() calls instead create constrained floating point intrinsic calls. Fast math flags are unaffected by this setting.
Definition at line 231 of file IRBuilder.h.
References IsFPConstrained.
Member Data Documentation
BB
BasicBlock* llvm::IRBuilderBase::BB protected
Definition at line 92 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), llvm::IRBuilder< T, Inserter >::CreateAlloca(), CreateAssumption(), CreateBinaryIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateCatchRet(), CreateElementUnorderedAtomicMemCpy(), CreateElementUnorderedAtomicMemMove(), CreateElementUnorderedAtomicMemSet(), CreateGCRelocate(), CreateGCResult(), CreateGlobalString(), CreateIntrinsic(), CreateInvariantStart(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), CreateUnaryIntrinsic(), getCurrentFunctionReturnType(), GetInsertBlock(), llvm::IRBuilder< T, Inserter >::Insert(), and SetInsertPoint().
Context
LLVMContext& llvm::IRBuilderBase::Context protected
Definition at line 94 of file IRBuilder.h.
Referenced by llvm::IRBuilder< T, Inserter >::CreateAggregateRet(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateFence(), CreateGlobalString(), llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr(), CreateMaskedGather(), CreateMaskedScatter(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), llvm::IRBuilder< T, Inserter >::CreateRet(), llvm::IRBuilder< T, Inserter >::CreateRetVoid(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilder< T, Inserter >::CreateUnreachable(), getContext(), getDoubleTy(), getFalse(), getFloatTy(), getHalfTy(), getInt(), getInt128Ty(), getInt16Ty(), getInt1Ty(), getInt32Ty(), getInt64Ty(), getInt8PtrTy(), getInt8Ty(), getIntNTy(), getIntPtrTy(), getTrue(), and getVoidTy().
DefaultConstrainedExcept
ConstrainedFPIntrinsic::ExceptionBehavior llvm::IRBuilderBase::DefaultConstrainedExcept protected
Definition at line 100 of file IRBuilder.h.
Referenced by getDefaultConstrainedExcept(), and setDefaultConstrainedExcept().
DefaultConstrainedRounding
ConstrainedFPIntrinsic::RoundingMode llvm::IRBuilderBase::DefaultConstrainedRounding protected
Definition at line 101 of file IRBuilder.h.
Referenced by getDefaultConstrainedRounding(), and setDefaultConstrainedRounding().
DefaultFPMathTag
MDNode* llvm::IRBuilderBase::DefaultFPMathTag protected
Definition at line 96 of file IRBuilder.h.
Referenced by getDefaultFPMathTag(), setDefaultFPMathTag(), and llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
DefaultOperandBundles
ArrayRef<OperandBundleDef> llvm::IRBuilderBase::DefaultOperandBundles protected
Definition at line 103 of file IRBuilder.h.
Referenced by llvm::IRBuilder< T, Inserter >::CreateCall().
FMF
FastMathFlags llvm::IRBuilderBase::FMF protected
Definition at line 97 of file IRBuilder.h.
Referenced by clearFastMathFlags(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateConstrainedFPBinOp(), llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFCmp(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFNeg(), CreateFPMaxReduce(), CreateFPMinReduce(), llvm::IRBuilder< T, Inserter >::CreateFRem(), llvm::IRBuilder< T, Inserter >::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateUnOp(), getFastMathFlags(), setFastMathFlags(), and llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
InsertPt
BasicBlock::iterator llvm::IRBuilderBase::InsertPt protected
Definition at line 93 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), GetInsertPoint(), llvm::IRBuilder< T, Inserter >::Insert(), and SetInsertPoint().
IsFPConstrained
bool llvm::IRBuilderBase::IsFPConstrained protected
Definition at line 99 of file IRBuilder.h.
Referenced by llvm::IRBuilder< T, Inserter >::CreateFAdd(), llvm::IRBuilder< T, Inserter >::CreateFAddFMF(), llvm::IRBuilder< T, Inserter >::CreateFDiv(), llvm::IRBuilder< T, Inserter >::CreateFDivFMF(), llvm::IRBuilder< T, Inserter >::CreateFMul(), llvm::IRBuilder< T, Inserter >::CreateFMulFMF(), llvm::IRBuilder< T, Inserter >::CreateFRem(), llvm::IRBuilder< T, Inserter >::CreateFRemFMF(), llvm::IRBuilder< T, Inserter >::CreateFSub(), llvm::IRBuilder< T, Inserter >::CreateFSubFMF(), getIsFPConstrained(), and setIsFPConstrained().
The documentation for this class was generated from the following files:
include/llvm/IR/IRBuilder.h
lib/IR/IRBuilder.cpp