LLVM: llvm::DWARFListType< ListEntryType > Class Template Reference
llvm::DWARFListType< ListEntryType > Class Template Reference
A base class for lists of entries that are extracted from a particular section, such as range lists or location lists.
#include "llvm/DebugInfo/DWARF/DWARFListTable.h"
Public Member Functions
const ListEntries & getEntries () const
bool empty () const
void clear ()
Error extract (DWARFDataExtractor Data, uint32_t HeaderOffset, uint32_t End, uint32_t *OffsetPtr, StringRef SectionName, StringRef ListStringName)
Protected Attributes
ListEntries Entries
Detailed Description
template<typename ListEntryType>
class llvm::DWARFListType< ListEntryType >
A base class for lists of entries that are extracted from a particular section, such as range lists or location lists.
Definition at line 38 of file DWARFListTable.h.
Member Function Documentation
clear()
template<typename ListEntryType > void llvm::DWARFListType< ListEntryType >::clear () inline
Definition at line 48 of file DWARFListTable.h.
References llvm::DWARFListType< ListEntryType >::Entries.
empty()
template<typename ListEntryType > bool llvm::DWARFListType< ListEntryType >::empty () const inline
Definition at line 47 of file DWARFListTable.h.
References llvm::DWARFListType< ListEntryType >::Entries.
extract()
template<typename ListEntryType > Error llvm::DWARFListType< ListEntryType >::extract (DWARFDataExtractor Data, uint32_t HeaderOffset, uint32_t End, uint32_t * OffsetPtr, StringRef SectionName, StringRef ListStringName)
Definition at line 210 of file DWARFListTable.h.
References llvm::createStringError(), llvm::illegal_byte_sequence, llvm::invalid_argument, and llvm::Error::success().
Referenced by llvm::DWARFListTableBase< DWARFListType >::extract(), and llvm::DWARFListTableBase< DWARFListType >::findList().
getEntries()
template<typename ListEntryType > const ListEntries & llvm::DWARFListType< ListEntryType >::getEntries () const inline
Definition at line 46 of file DWARFListTable.h.
References llvm::DWARFListType< ListEntryType >::Entries.
Member Data Documentation
Entries
template<typename ListEntryType > ListEntries llvm::DWARFListType< ListEntryType >::Entries protected
Definition at line 43 of file DWARFListTable.h.
Referenced by llvm::DWARFListType< ListEntryType >::clear(), llvm::DWARFListType< ListEntryType >::empty(), and llvm::DWARFListType< ListEntryType >::getEntries().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFListTable.h