LLVM: llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy > Class Template Reference
llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy > Class Template Reference
#include "llvm/ADT/ScopedHashTable.h"
Public Member Functions
ScopedHashTableScope (ScopedHashTable< K, V, KInfo, AllocatorTy > &HT)
ScopedHashTableScope (ScopedHashTableScope &)=delete
ScopedHashTableScope & operator= (ScopedHashTableScope &)=delete
~ScopedHashTableScope ()
ScopedHashTableScope * getParentScope ()
const ScopedHashTableScope * getParentScope () const
Friends
class ScopedHashTable< K, V, KInfo, AllocatorTy >
Detailed Description
template<typename K, typename V, typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator>
class llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >
Definition at line 85 of file ScopedHashTable.h.
Constructor & Destructor Documentation
ScopedHashTableScope() [1/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::ScopedHashTableScope (ScopedHashTable< K, V, KInfo, AllocatorTy > & HT)
ScopedHashTableScope() [2/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::ScopedHashTableScope (ScopedHashTableScope< K, V, KInfo, AllocatorTy > &) delete
~ScopedHashTableScope()
template<typename K , typename V , typename KInfo , typename Allocator > llvm::ScopedHashTableScope< K, V, KInfo, Allocator >::~ScopedHashTableScope
Definition at line 236 of file ScopedHashTable.h.
References assert(), llvm::ScopedHashTableVal< K, V >::Destroy(), llvm::ScopedHashTableVal< K, V >::getNextForKey(), and llvm::ScopedHashTableVal< K, V >::getNextInScope().
Member Function Documentation
getParentScope() [1/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> ScopedHashTableScope * llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::getParentScope () inline
Definition at line 102 of file ScopedHashTable.h.
getParentScope() [2/2]
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> const ScopedHashTableScope * llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::getParentScope () const inline
Definition at line 103 of file ScopedHashTable.h.
operator=()
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> ScopedHashTableScope & llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::operator= (ScopedHashTableScope< K, V, KInfo, AllocatorTy > &) delete
Friends And Related Function Documentation
ScopedHashTable< K, V, KInfo, AllocatorTy >
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> friend class ScopedHashTable< K, V, KInfo, AllocatorTy > friend
Definition at line 103 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ScopedHashTable.h