LLVM: llvm::BlockFrequencyInfoWrapperPass Class Reference
llvm::BlockFrequencyInfoWrapperPass Class Reference
Legacy analysis pass which computes BlockFrequencyInfo.
#include "llvm/Analysis/BlockFrequencyInfo.h"
Public Member Functions
BlockFrequencyInfoWrapperPass ()
~BlockFrequencyInfoWrapperPass () override
BlockFrequencyInfo & getBFI ()
const BlockFrequencyInfo & getBFI () const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
void releaseMemory () override
void print (raw_ostream &OS, const Module *M) const override
Static Public Attributes
static char ID = 0
Detailed Description
Legacy analysis pass which computes BlockFrequencyInfo.
Definition at line 135 of file BlockFrequencyInfo.h.
Constructor & Destructor Documentation
BlockFrequencyInfoWrapperPass()
BlockFrequencyInfoWrapperPass::BlockFrequencyInfoWrapperPass ()
Definition at line 298 of file BlockFrequencyInfo.cpp.
~BlockFrequencyInfoWrapperPass()
BlockFrequencyInfoWrapperPass::~BlockFrequencyInfoWrapperPass () override default
Member Function Documentation
getAnalysisUsage()
void BlockFrequencyInfoWrapperPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 310 of file BlockFrequencyInfo.cpp.
getBFI() [1/2]
BlockFrequencyInfo & llvm::BlockFrequencyInfoWrapperPass::getBFI () inline
Definition at line 144 of file BlockFrequencyInfo.h.
getBFI() [2/2]
const BlockFrequencyInfo & llvm::BlockFrequencyInfoWrapperPass::getBFI () const inline
Definition at line 145 of file BlockFrequencyInfo.h.
print()
void BlockFrequencyInfoWrapperPass::print (raw_ostream & OS, const Module * M) const override
Definition at line 305 of file BlockFrequencyInfo.cpp.
References llvm::BlockFrequencyInfo::print().
releaseMemory()
void BlockFrequencyInfoWrapperPass::releaseMemory () override
Definition at line 316 of file BlockFrequencyInfo.cpp.
References llvm::BlockFrequencyInfo::releaseMemory().
runOnFunction()
bool BlockFrequencyInfoWrapperPass::runOnFunction (Function & F) override
Definition at line 318 of file BlockFrequencyInfo.cpp.
References llvm::BlockFrequencyInfo::calculate(), and F.
Member Data Documentation
ID
block Block Frequency true char BlockFrequencyInfoWrapperPass::ID = 0 static
Definition at line 139 of file BlockFrequencyInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/BlockFrequencyInfo.h
lib/Analysis/BlockFrequencyInfo.cpp