LLVM: llvm::ListRecTy Class Reference
llvm::ListRecTy Class Reference
'list<Ty>' - Represent a list of values, all of which must be of the specified type.
#include "llvm/TableGen/Record.h"
Public Member Functions
RecTy * getElementType () const
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Return true if all values of 'this' type can be converted to the specified type.
bool typeIsA (const RecTy *RHS) const override
Return true if 'this' type is equal to or a subtype of RHS.
Public Member Functions inherited from llvm::RecTy
RecTy (RecTyKind K)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
virtual std::string getAsString () const =0
void print (raw_ostream &OS) const
void dump () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
Return true if all values of 'this' type can be converted to the specified type.
virtual bool typeIsA (const RecTy *RHS) const
Return true if 'this' type is equal to or a subtype of RHS.
ListRecTy * getListTy ()
Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static ListRecTy * get (RecTy *T)
Friends
ListRecTy * RecTy::getListTy ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , CodeRecTyKind , IntRecTyKind ,
StringRecTyKind , ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
'list<Ty>' - Represent a list of values, all of which must be of the specified type.
Definition at line 195 of file Record.h.
Member Function Documentation
classof()
static bool llvm::ListRecTy::classof (const RecTy * RT) inline static
Definition at line 203 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::ListRecTyKind.
get()
static ListRecTy * llvm::ListRecTy::get (RecTy * T) inline static
Definition at line 207 of file Record.h.
getAsString()
std::string ListRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 130 of file Record.cpp.
References llvm::RecTy::getAsString().
getElementType()
RecTy * llvm::ListRecTy::getElementType () const inline
Definition at line 208 of file Record.h.
Referenced by typeIsA().
typeIsA()
bool ListRecTy::typeIsA (const RecTy * RHS) const override virtual
Return true if 'this' type is equal to or a subtype of RHS.
For example, a bit set is not an int, but they are convertible.
Reimplemented from llvm::RecTy.
Definition at line 140 of file Record.cpp.
References getElementType(), and llvm::RecTy::typeIsA().
typeIsConvertibleTo()
bool ListRecTy::typeIsConvertibleTo (const RecTy * RHS) const override virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 134 of file Record.cpp.
References llvm::RecTy::typeIsConvertibleTo().
Friends And Related Function Documentation
RecTy::getListTy
ListRecTy * RecTy::getListTy () friend
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp