LLVM: llvm::TernOpInit Class Reference
llvm::TernOpInit Class Reference
!op (X, Y, Z) - Combine two inits.
#include "llvm/TableGen/Record.h"
Public Types
enum TernaryOp : uint8_t { SUBST , FOREACH , IF , DAG }
Public Member Functions
TernOpInit (const TernOpInit &)=delete
TernOpInit & operator= (const TernOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
OpInit * clone (ArrayRef< Init * > Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
TernaryOp getOpcode () const
Init * getLHS () const
Init * getMHS () const
Init * getRHS () const
Init * Fold (Record *CurRec) const
bool isComplete () const override
This virtual method should be overridden by values that may not be completely specified yet.
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a string form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
virtual OpInit * clone (ArrayRef< Init * > Operands) const =0
virtual unsigned getNumOperands () const =0
virtual Init * getOperand (unsigned i) const =0
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsString () const =0
Convert this value to a string form.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This method is used to implement the bitrange selection operator.
virtual Init * convertInitListSlice (ArrayRef< unsigned > Elements) const
This method is used to implement the list slice selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This method is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
This method is used to return the initializer for the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static TernOpInit * get (TernaryOp opc, Init *lhs, Init *mhs, Init *rhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X, Y, Z) - Combine two inits.
Definition at line 859 of file Record.h.
Member Enumeration Documentation
TernaryOp
enum llvm::TernOpInit::TernaryOp : uint8_t
Enumerator
SUBST
FOREACH
IF
DAG
Definition at line 861 of file Record.h.
Constructor & Destructor Documentation
TernOpInit()
llvm::TernOpInit::TernOpInit (const TernOpInit &) delete
Member Function Documentation
classof()
static bool llvm::TernOpInit::classof (const Init * I) inline static
Definition at line 874 of file Record.h.
References I, and llvm::Init::IK_TernOpInit.
clone()
OpInit * llvm::TernOpInit::clone (ArrayRef< Init * > Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 885 of file Record.h.
References assert(), llvm::IntervalMapImpl::NodeRef::get(), getOpcode(), llvm::TypedInit::getType(), and llvm::ArrayRef< T >::size().
Fold()
Init * TernOpInit::Fold (Record * CurRec) const
Definition at line 1128 of file Record.cpp.
References llvm::Init::convertInitializerTo(), DAG, llvm::SmallVectorImpl< T >::emplace_back(), llvm::StringRef::find(), FOREACH, ForeachHelper(), llvm::IntRecTy::get(), llvm::UnsetInit::get(), llvm::IntervalMapImpl::NodeRef::get(), llvm::VarInit::getAsString(), llvm::DefInit::getAsString(), llvm::DefInit::getDef(), llvm::ListInit::getElement(), llvm::VarInit::getName(), getOpcode(), llvm::TypedInit::getType(), llvm::StringInit::getValue(), IF, Name, llvm::FoldingSetBase::Node::Node(), llvm::StringRef::size(), llvm::ListInit::size(), Size, and SUBST.
get()
TernOpInit * TernOpInit::get (TernaryOp opc, Init * lhs, Init * mhs, Init * rhs, RecTy * Type) static
Definition at line 1054 of file Record.cpp.
References Allocator, llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), I, llvm::FoldingSetImpl< T >::InsertNode(), llvm::Init::Opc, and ProfileTernOpInit().
getAsString()
std::string TernOpInit::getAsString () const override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1247 of file Record.cpp.
References DAG, FOREACH, llvm::Init::getAsString(), llvm::Init::getAsUnquotedString(), getOpcode(), IF, and SUBST.
getLHS()
Init * llvm::TernOpInit::getLHS () const inline
Definition at line 903 of file Record.h.
Referenced by getOperand(), and Profile().
getMHS()
Init * llvm::TernOpInit::getMHS () const inline
Definition at line 904 of file Record.h.
Referenced by getOperand(), and Profile().
getNumOperands()
unsigned llvm::TernOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 892 of file Record.h.
getOpcode()
TernaryOp llvm::TernOpInit::getOpcode () const inline
Definition at line 902 of file Record.h.
References llvm::Init::Opc.
Referenced by clone(), Fold(), getAsString(), Profile(), and resolveReferences().
getOperand()
Init * llvm::TernOpInit::getOperand (unsigned i) const inline override virtual
Implements llvm::OpInit.
Definition at line 893 of file Record.h.
References getLHS(), getMHS(), getRHS(), and llvm_unreachable.
getRHS()
Init * llvm::TernOpInit::getRHS () const inline
Definition at line 905 of file Record.h.
Referenced by getOperand(), and Profile().
isComplete()
bool llvm::TernOpInit::isComplete () const inline override virtual
This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented from llvm::Init.
Definition at line 911 of file Record.h.
References llvm::Init::isComplete().
operator=()
TernOpInit & llvm::TernOpInit::operator= (const TernOpInit &) delete
Profile()
void TernOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1070 of file Record.cpp.
References getLHS(), getMHS(), getOpcode(), getRHS(), llvm::TypedInit::getType(), and ProfileTernOpInit().
resolveReferences()
Init * TernOpInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1217 of file Record.cpp.
References llvm::ShadowResolver::addShadow(), llvm::Init::convertInitializerTo(), FOREACH, llvm::IntRecTy::get(), llvm::IntervalMapImpl::NodeRef::get(), getOpcode(), llvm::TypedInit::getType(), IF, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp