LLVM: llvm::FunctionImportGlobalProcessing Class Reference
llvm::FunctionImportGlobalProcessing Class Reference
Class to handle necessary GlobalValue changes required by ThinLTO function importing, including linkage changes and any necessary renaming.
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
Public Member Functions
FunctionImportGlobalProcessing (Module &M, const ModuleSummaryIndex &Index, SetVector< GlobalValue * > *GlobalsToImport=nullptr)
bool run ()
Static Public Member Functions
static bool doImportAsDefinition (const GlobalValue *SGV, SetVector< GlobalValue * > *GlobalsToImport)
Checks if we should import SGV as a definition, otherwise import as a declaration.
Detailed Description
Class to handle necessary GlobalValue changes required by ThinLTO function importing, including linkage changes and any necessary renaming.
Definition at line 25 of file FunctionImportUtils.h.
Constructor & Destructor Documentation
FunctionImportGlobalProcessing()
llvm::FunctionImportGlobalProcessing::FunctionImportGlobalProcessing (Module & M, const ModuleSummaryIndex & Index, SetVector< GlobalValue * > * GlobalsToImport = nullptr) inline
Definition at line 90 of file FunctionImportUtils.h.
References llvm::collectUsedGlobalVariables(), and llvm::ModuleSummaryIndex::hasExportedFunctions().
Member Function Documentation
doImportAsDefinition()
bool FunctionImportGlobalProcessing::doImportAsDefinition (const GlobalValue * SGV, SetVector< GlobalValue * > * GlobalsToImport) static
Checks if we should import SGV as a definition, otherwise import as a declaration.
Definition at line 20 of file FunctionImportUtils.cpp.
References assert().
run()
bool FunctionImportGlobalProcessing::run ()
Definition at line 304 of file FunctionImportUtils.cpp.
Referenced by llvm::renameModuleForThinLTO().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/FunctionImportUtils.h
lib/Transforms/Utils/FunctionImportUtils.cpp