LLVM: llvm::InstructionCombiningPass Class Reference
llvm::InstructionCombiningPass Class Reference
The legacy pass manager's instcombine pass.
#include "llvm/Transforms/InstCombine/InstCombine.h"
Public Member Functions
InstructionCombiningPass (bool ExpensiveCombines=true)
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
Static Public Attributes
static char ID = 0
Detailed Description
The legacy pass manager's instcombine pass.
This is a basic whole-function wrapper around the instcombine utility. It will try to combine all instructions in the function.
Definition at line 42 of file InstCombine.h.
Constructor & Destructor Documentation
InstructionCombiningPass()
llvm::InstructionCombiningPass::InstructionCombiningPass (bool ExpensiveCombines = true) inline
Definition at line 49 of file InstCombine.h.
Member Function Documentation
getAnalysisUsage()
void InstructionCombiningPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 3561 of file InstructionCombining.cpp.
References llvm::LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage().
runOnFunction()
bool InstructionCombiningPass::runOnFunction (Function & F) override
Definition at line 3576 of file InstructionCombining.cpp.
References combineInstructionsOverFunction(), F, and llvm::ProfileSummaryInfo::hasProfileSummary().
Member Data Documentation
ID
char InstructionCombiningPass::ID = 0 static
Definition at line 47 of file InstCombine.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/InstCombine/InstCombine.h
lib/Transforms/InstCombine/InstructionCombining.cpp