LLVM: llvm::jitlink::EHFrameParser Class Reference
llvm::jitlink::EHFrameParser Class Reference
A generic parser for eh-frame sections.
#include "ExecutionEngine/JITLink/EHFrameSupportImpl.h"
Public Member Functions
EHFrameParser (AtomGraph &G, Section &EHFrameSection, StringRef EHFrameContent, JITTargetAddress EHFrameAddress, Edge::Kind FDEToCIERelocKind, Edge::Kind FDEToTargetRelocKind)
Error atomize ()
Detailed Description
A generic parser for eh-frame sections.
Adds atoms representing CIE and FDE entries, using the given FDE-to-CIE and FDEToTarget relocation kinds.
Definition at line 28 of file EHFrameSupportImpl.h.
Constructor & Destructor Documentation
EHFrameParser()
llvm::jitlink::EHFrameParser::EHFrameParser (AtomGraph & G, Section & EHFrameSection, StringRef EHFrameContent, JITTargetAddress EHFrameAddress, Edge::Kind FDEToCIERelocKind, Edge::Kind FDEToTargetRelocKind)
Definition at line 20 of file EHFrameSupport.cpp.
Member Function Documentation
atomize()
Error llvm::jitlink::EHFrameParser::atomize ()
Definition at line 31 of file EHFrameSupport.cpp.
References llvm::jitlink::AtomGraph::addAnonymousAtom(), llvm::BinaryStreamReader::bytesRemaining(), llvm::dbgs(), llvm::BinaryStreamReader::empty(), llvm::format(), llvm::BinaryStreamReader::getOffset(), llvm::jitlink::AtomGraph::getPointerSize(), LLVM_DEBUG, llvm::BinaryStreamReader::readInteger(), llvm::jitlink::DefinedAtom::setContent(), llvm::BinaryStreamReader::setOffset(), llvm::StringRef::substr(), and llvm::Error::success().
Referenced by llvm::jitlink::addEHFrame().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/EHFrameSupportImpl.h
lib/ExecutionEngine/JITLink/EHFrameSupport.cpp