LLVM: llvm::VPBranchOnMaskRecipe Class Reference
llvm::VPBranchOnMaskRecipe Class Reference
A recipe for generating conditional branches on the bits of a mask.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPBranchOnMaskRecipe (VPValue *BlockInMask)
void execute (VPTransformState &State) override
Generate the extraction of the appropriate bit from the block mask and the conditional branch.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Detailed Description
A recipe for generating conditional branches on the bits of a mask.
Definition at line 894 of file VPlan.h.
Constructor & Destructor Documentation
VPBranchOnMaskRecipe()
llvm::VPBranchOnMaskRecipe::VPBranchOnMaskRecipe (VPValue * BlockInMask) inline
Definition at line 899 of file VPlan.h.
Member Function Documentation
classof()
static bool llvm::VPBranchOnMaskRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 905 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPBranchOnMaskRecipe::execute (VPTransformState & State) override virtual
Generate the extraction of the appropriate bit from the block mask and the conditional branch.
Implements llvm::VPRecipeBase.
Definition at line 7132 of file LoopVectorize.cpp.
References assert(), llvm::VPTransformState::Builder, llvm::VPTransformState::CFG, llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::VPTransformState::get(), llvm::IRBuilderBase::getInt32(), llvm::User::getOperand(), llvm::BasicBlock::getTerminator(), llvm::IRBuilderBase::getTrue(), llvm::Value::getType(), llvm::VPTransformState::Instance, llvm::Type::isVectorTy(), llvm::VPTransformState::CFGState::PrevBB, and llvm::ReplaceInstWithInst().
print()
void llvm::VPBranchOnMaskRecipe::print (raw_ostream & O, const Twine & Indent) const inline override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 914 of file VPlan.h.
References llvm::User::getOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp