LLVM: llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... > Class Template Reference
llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... > Class Template Reference
#include "llvm/Support/TrailingObjects.h"
Static Protected Member Functions
static const NextTy * getTrailingObjectsImpl (const BaseTy *Obj, TrailingObjectsBase::OverloadToken< NextTy >)
static NextTy * getTrailingObjectsImpl (BaseTy *Obj, TrailingObjectsBase::OverloadToken< NextTy >)
static constexpr size_t additionalSizeToAllocImpl (size_t SizeSoFar, size_t Count1, typename ExtractSecondType< MoreTys, size_t >::type... MoreCounts)
Detailed Description
template<int Align, typename BaseTy, typename TopTrailingObj, typename PrevTy, typename NextTy, typename... MoreTys>
class llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... >
Definition at line 136 of file TrailingObjects.h.
Member Function Documentation
additionalSizeToAllocImpl()
template<int Align, typename BaseTy , typename TopTrailingObj , typename PrevTy , typename NextTy , typename... MoreTys> static constexpr size_t llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... >::additionalSizeToAllocImpl (size_t SizeSoFar, size_t Count1, typename ExtractSecondType< MoreTys, size_t >::type... MoreCounts) inline static constexpr protected
Definition at line 197 of file TrailingObjects.h.
References llvm::alignTo().
Referenced by llvm::TrailingObjects< BaseTy, TrailingTys >::additionalSizeToAlloc(), and llvm::TrailingObjects< BaseTy, TrailingTys >::totalSizeToAlloc().
getTrailingObjectsImpl() [1/2]
template<int Align, typename BaseTy , typename TopTrailingObj , typename PrevTy , typename NextTy , typename... MoreTys> static NextTy * llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... >::getTrailingObjectsImpl (BaseTy * Obj, TrailingObjectsBase::OverloadToken< NextTy >) inline static protected
Definition at line 181 of file TrailingObjects.h.
References llvm::alignAddr().
getTrailingObjectsImpl() [2/2]
template<int Align, typename BaseTy , typename TopTrailingObj , typename PrevTy , typename NextTy , typename... MoreTys> static const NextTy * llvm::trailing_objects_internal::TrailingObjectsImpl< Align, BaseTy, TopTrailingObj, PrevTy, NextTy, MoreTys... >::getTrailingObjectsImpl (const BaseTy * Obj, TrailingObjectsBase::OverloadToken< NextTy >) inline static protected
Definition at line 166 of file TrailingObjects.h.
References llvm::alignAddr().
The documentation for this class was generated from the following file:
include/llvm/Support/TrailingObjects.h