LLVM: llvm::RegBankSelect::InstrInsertPoint Class Reference
llvm::RegBankSelect::InstrInsertPoint Class Reference
Insertion point before or after an instruction.
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
Public Member Functions
InstrInsertPoint (MachineInstr &Instr, bool Before=true)
Create an insertion point before (Before=true) or after Instr.
bool isSplit () const override
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
uint64_t frequency (const Pass &P) const override
Frequency of the insertion point.
bool canMaterialize () const override
Check whether this insertion point can be materialized.
Public Member Functions inherited from llvm::RegBankSelect::InsertPoint
virtual ~InsertPoint ()=default
MachineBasicBlock::iterator getPoint ()
The first call to this method will cause the splitting to happen if need be, then sub sequent calls just return the iterator to that point.
MachineBasicBlock & getInsertMBB ()
The first call to this method will cause the splitting to happen if need be, then sub sequent calls just return the basic block that contains the insertion point.
MachineBasicBlock::iterator insert (MachineInstr &MI)
Insert MI in the just before getPoint()
virtual bool isSplit () const
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
virtual uint64_t frequency (const Pass &P) const
Frequency of the insertion point.
virtual bool canMaterialize () const
Check whether this insertion point can be materialized.
Additional Inherited Members
virtual void materialize ()=0
Materialize the insertion point.
virtual MachineBasicBlock & getInsertMBBImpl ()=0
Return the materialized insertion basic block.
virtual MachineBasicBlock::iterator getPointImpl ()=0
Return the materialized insertion point.
Protected Attributes inherited from llvm::RegBankSelect::InsertPoint
bool WasMaterialized = false
Tell if the insert point has already been materialized.
Detailed Description
Insertion point before or after an instruction.
Definition at line 203 of file RegBankSelect.h.
Constructor & Destructor Documentation
InstrInsertPoint()
RegBankSelect::InstrInsertPoint::InstrInsertPoint (MachineInstr & Instr, bool Before = true)
Create an insertion point before (Before=true) or after Instr.
Definition at line 837 of file RegBankSelect.cpp.
References assert(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::MachineInstr::isPHI().
Member Function Documentation
canMaterialize()
bool llvm::RegBankSelect::InstrInsertPoint::canMaterialize () const inline override virtual
Check whether this insertion point can be materialized.
As soon as getPoint is called and thus, the point materialized calling this method does not make sense.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 232 of file RegBankSelect.h.
frequency()
uint64_t RegBankSelect::InstrInsertPoint::frequency (const Pass & P) const override virtual
Frequency of the insertion point.
P is used to access the various analysis that will help to get that information, like MachineBlockFrequencyInfo. If P does not contain enough enough to return the actual frequency, this returns 1.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 879 of file RegBankSelect.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockFreq(), and P.
isSplit()
bool RegBankSelect::InstrInsertPoint::isSplit () const override virtual
Does this point involve splitting an edge or block? As soon as getPoint is called and thus, the point materialized, the point will not require splitting anymore, i.e., this will return false.
Reimplemented from llvm::RegBankSelect::InsertPoint.
Definition at line 870 of file RegBankSelect.cpp.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegBankSelect.h
lib/CodeGen/GlobalISel/RegBankSelect.cpp