LLVM: llvm::AssumptionCacheTracker Class Reference
llvm::AssumptionCacheTracker Class Reference
An immutable pass that tracks lazily created AssumptionCache objects.
#include "llvm/Analysis/AssumptionCache.h"
Public Member Functions
AssumptionCache & getAssumptionCache (Function &F)
Get the cached assumptions for a function.
AssumptionCache * lookupAssumptionCache (Function &F)
Return the cached assumptions for a function if it has already been scanned.
AssumptionCacheTracker ()
~AssumptionCacheTracker () override
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void verifyAnalysis () const override
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
bool doFinalization (Module &) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
An immutable pass that tracks lazily created AssumptionCache objects.
This is essentially a workaround for the legacy pass manager's weaknesses which associates each assumption cache with Function and clears it if the function is deleted. The nature of the AssumptionCache is that it is not invalidated by any changes to the function body and so this is sufficient to be conservatively correct.
Definition at line 185 of file AssumptionCache.h.
Constructor & Destructor Documentation
AssumptionCacheTracker()
AssumptionCacheTracker::AssumptionCacheTracker ()
Definition at line 289 of file AssumptionCache.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeAssumptionCacheTrackerPass().
~AssumptionCacheTracker()
AssumptionCacheTracker::~AssumptionCacheTracker () override default
Member Function Documentation
doFinalization()
bool llvm::AssumptionCacheTracker::doFinalization (Module &) inline override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 229 of file AssumptionCache.h.
References verifyAnalysis().
getAssumptionCache()
AssumptionCache & AssumptionCacheTracker::getAssumptionCache (Function & F)
Get the cached assumptions for a function.
If no assumptions are cached, this will scan the function. Otherwise, the existing cache will be returned.
Definition at line 243 of file AssumptionCache.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by llvm::createLegacyPMBasicAAResult(), llvm::getBestSimplifyQuery(), and llvm::LegacyInlinerBase::inlineCalls().
lookupAssumptionCache()
AssumptionCache * AssumptionCacheTracker::lookupAssumptionCache (Function & F)
Return the cached assumptions for a function if it has already been scanned.
Otherwise return nullptr.
Definition at line 260 of file AssumptionCache.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), and I.
releaseMemory()
void llvm::AssumptionCacheTracker::releaseMemory () inline override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 222 of file AssumptionCache.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear(), and verifyAnalysis().
verifyAnalysis()
void AssumptionCacheTracker::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 267 of file AssumptionCache.cpp.
References B, llvm::SmallPtrSetImpl< PtrType >::count(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::PatternMatch::match(), llvm::report_fatal_error(), and VerifyAssumptionCache.
Referenced by doFinalization(), and releaseMemory().
Member Data Documentation
ID
char AssumptionCacheTracker::ID = 0 static
Definition at line 234 of file AssumptionCache.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/AssumptionCache.h
lib/Analysis/AssumptionCache.cpp