LLVM: llvm::vfs::recursive_directory_iterator Class Reference
llvm::vfs::recursive_directory_iterator Class Reference
An input iterator over the recursive contents of a virtual path, similar to llvm::sys::fs::recursive_directory_iterator.
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
recursive_directory_iterator (FileSystem &FS, const Twine &Path, std::error_code &EC)
recursive_directory_iterator ()=default
Construct an 'end' iterator.
recursive_directory_iterator & increment (std::error_code &EC)
Equivalent to operator++, with an error code.
const directory_entry & operator* () const
const directory_entry * operator-> () const
bool operator== (const recursive_directory_iterator &Other) const
bool operator!= (const recursive_directory_iterator &RHS) const
int level () const
Gets the current level. Starting path is at level 0.
void no_push ()
Detailed Description
An input iterator over the recursive contents of a virtual path, similar to llvm::sys::fs::recursive_directory_iterator.
Definition at line 208 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
recursive_directory_iterator() [1/2]
vfs::recursive_directory_iterator::recursive_directory_iterator (FileSystem & FS, const Twine & Path, std::error_code & EC)
Definition at line 2080 of file VirtualFileSystem.cpp.
References llvm::vfs::FileSystem::dir_begin(), and I.
recursive_directory_iterator() [2/2]
llvm::vfs::recursive_directory_iterator::recursive_directory_iterator () default
Construct an 'end' iterator.
Member Function Documentation
increment()
vfs::recursive_directory_iterator & recursive_directory_iterator::increment (std::error_code & EC)
Equivalent to operator++, with an error code.
Definition at line 2091 of file VirtualFileSystem.cpp.
References assert(), llvm::vfs::FileSystem::dir_begin(), llvm::sys::fs::directory_file, and I.
level()
int llvm::vfs::recursive_directory_iterator::level () const inline
Gets the current level. Starting path is at level 0.
Definition at line 234 of file VirtualFileSystem.h.
References assert().
no_push()
void llvm::vfs::recursive_directory_iterator::no_push () inline
Definition at line 240 of file VirtualFileSystem.h.
operator!=()
bool llvm::vfs::recursive_directory_iterator::operator!= (const recursive_directory_iterator & RHS) const inline
Definition at line 229 of file VirtualFileSystem.h.
operator*()
const directory_entry & llvm::vfs::recursive_directory_iterator::operator* () const inline
Definition at line 223 of file VirtualFileSystem.h.
operator->()
const directory_entry * llvm::vfs::recursive_directory_iterator::operator-> () const inline
Definition at line 224 of file VirtualFileSystem.h.
operator==()
bool llvm::vfs::recursive_directory_iterator::operator== (const recursive_directory_iterator & Other) const inline
Definition at line 226 of file VirtualFileSystem.h.
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp