LLVM: llvm::xray::RecordInitializer Class Reference
llvm::xray::RecordInitializer Class Reference
#include "llvm/XRay/FDRRecords.h"
Public Member Functions
RecordInitializer (DataExtractor &DE, uint32_t &OP, uint16_t V)
RecordInitializer (DataExtractor &DE, uint32_t &OP)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
virtual Error visit (BufferExtents &)=0
virtual Error visit (WallclockRecord &)=0
virtual Error visit (NewCPUIDRecord &)=0
virtual Error visit (TSCWrapRecord &)=0
virtual Error visit (CustomEventRecord &)=0
virtual Error visit (CallArgRecord &)=0
virtual Error visit (PIDRecord &)=0
virtual Error visit (NewBufferRecord &)=0
virtual Error visit (EndBufferRecord &)=0
virtual Error visit (FunctionRecord &)=0
virtual Error visit (CustomEventRecordV5 &)=0
virtual Error visit (TypedEventRecord &)=0
Static Public Attributes
static constexpr uint16_t DefaultVersion = 5u
Detailed Description
Definition at line 418 of file FDRRecords.h.
Constructor & Destructor Documentation
RecordInitializer() [1/2]
llvm::xray::RecordInitializer::RecordInitializer (DataExtractor & DE, uint32_t & OP, uint16_t V) inline explicit
Definition at line 426 of file FDRRecords.h.
RecordInitializer() [2/2]
llvm::xray::RecordInitializer::RecordInitializer (DataExtractor & DE, uint32_t & OP) inline explicit
Definition at line 429 of file FDRRecords.h.
Member Function Documentation
visit() [1/12]
Error llvm::xray::RecordInitializer::visit (BufferExtents & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 13 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getU64(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [2/12]
Error llvm::xray::RecordInitializer::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 300 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getU64(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [3/12]
Error llvm::xray::RecordInitializer::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 98 of file RecordInitializer.cpp.
References assert(), llvm::createStringError(), llvm::DataExtractor::getSigned(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [4/12]
Error llvm::xray::RecordInitializer::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 169 of file RecordInitializer.cpp.
References assert(), llvm::createStringError(), llvm::DataExtractor::getSigned(), llvm::DataExtractor::getU8(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [5/12]
Error llvm::xray::RecordInitializer::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 354 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [6/12]
Error llvm::xray::RecordInitializer::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 365 of file RecordInitializer.cpp.
References assert(), llvm::createStringError(), llvm::xray::ENTER, llvm::xray::ENTER_ARG, llvm::xray::EXIT, llvm::DataExtractor::getU32(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::Error::success(), and llvm::xray::TAIL_EXIT.
visit() [7/12]
Error llvm::xray::RecordInitializer::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 336 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getSigned(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [8/12]
Error llvm::xray::RecordInitializer::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 57 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU64(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [9/12]
Error llvm::xray::RecordInitializer::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 318 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getSigned(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [10/12]
Error llvm::xray::RecordInitializer::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 80 of file RecordInitializer.cpp.
References llvm::createStringError(), llvm::DataExtractor::getU64(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [11/12]
Error llvm::xray::RecordInitializer::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 231 of file RecordInitializer.cpp.
References assert(), llvm::createStringError(), llvm::DataExtractor::getSigned(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU8(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
visit() [12/12]
Error llvm::xray::RecordInitializer::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 30 of file RecordInitializer.cpp.
References assert(), llvm::createStringError(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::xray::MetadataRecord::kMetadataBodySize, and llvm::Error::success().
Member Data Documentation
DefaultVersion
constexpr uint16_t llvm::xray::RecordInitializer::DefaultVersion = 5u static constexpr
Definition at line 424 of file FDRRecords.h.
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/RecordInitializer.cpp