LLVM: llvm::xray::FileBasedRecordProducer Class Reference
llvm::xray::FileBasedRecordProducer Class Reference
#include "llvm/XRay/FDRRecordProducer.h"
Public Member Functions
FileBasedRecordProducer (const XRayFileHeader &FH, DataExtractor &DE, uint32_t &OP)
Expected< std::unique_ptr< Record > > produce () override
This producer encapsulates the logic for loading a File-backed RecordProducer hidden behind a DataExtractor.
Public Member Functions inherited from llvm::xray::RecordProducer
virtual Expected< std::unique_ptr< Record > > produce ()=0
All producer implementations must yield either an Error or a non-nullptr unique_ptr<Record>.
virtual ~RecordProducer ()=default
Detailed Description
Definition at line 27 of file FDRRecordProducer.h.
Constructor & Destructor Documentation
FileBasedRecordProducer()
llvm::xray::FileBasedRecordProducer::FileBasedRecordProducer (const XRayFileHeader & FH, DataExtractor & DE, uint32_t & OP) inline
Definition at line 38 of file FDRRecordProducer.h.
Member Function Documentation
produce()
Expected< std::unique_ptr< Record > > llvm::xray::FileBasedRecordProducer::produce () override virtual
This producer encapsulates the logic for loading a File-backed RecordProducer hidden behind a DataExtractor.
Implements llvm::xray::RecordProducer.
Definition at line 112 of file FDRRecordProducer.cpp.
References assert(), llvm::createStringError(), llvm::StringRef::data(), llvm::DataExtractor::getU8(), llvm::joinErrors(), and llvm::xray::Record::kindToString().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecordProducer.h
lib/XRay/FDRRecordProducer.cpp