LLVM: llvm::ShadowResolver Class Reference
llvm::ShadowResolver Class Reference final
Delegate resolving to a sub-resolver, but shadow some variable names.
#include "llvm/TableGen/Record.h"
Public Member Functions
ShadowResolver (Resolver &R)
void addShadow (Init *Key)
Init * resolve (Init *VarName) override
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Public Member Functions inherited from llvm::Resolver
Resolver (Record *CurRec)
virtual ~Resolver ()
Record * getCurrentRecord () const
virtual Init * resolve (Init *VarName)=0
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
Delegate resolving to a sub-resolver, but shadow some variable names.
Definition at line 1936 of file Record.h.
Constructor & Destructor Documentation
ShadowResolver()
llvm::ShadowResolver::ShadowResolver (Resolver & R) inline explicit
Definition at line 1941 of file Record.h.
References llvm::Resolver::setFinal().
Member Function Documentation
addShadow()
void llvm::ShadowResolver::addShadow (Init * Key) inline
Definition at line 1946 of file Record.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by llvm::TernOpInit::resolveReferences(), and llvm::FoldOpInit::resolveReferences().
resolve()
Init * llvm::ShadowResolver::resolve (Init * VarName) inline override virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implements llvm::Resolver.
Definition at line 1948 of file Record.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count().
The documentation for this class was generated from the following file:
include/llvm/TableGen/Record.h