LLVM: llvm::pdb::DIARawSymbol Class Reference
llvm::pdb::DIARawSymbol Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIARawSymbol.h"
Public Member Functions
DIARawSymbol (const DIASession &PDBSession, CComPtr< IDiaSymbol > DiaSymbol)
void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override
CComPtr< IDiaSymbol > getDiaSymbol () const
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override
void getDataBytes (llvm::SmallVector< uint8_t, 32 > &bytes) const override
void getFrontEndVersion (VersionInfo &Version) const override
void getBackEndVersion (VersionInfo &Version) const override
PDB_MemberAccess getAccess () const override
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getAge () const override
SymIndexId getArrayIndexTypeId () const override
uint32_t getBaseDataOffset () const override
uint32_t getBaseDataSlot () const override
SymIndexId getBaseSymbolId () const override
PDB_BuiltinType getBuiltinType () const override
uint32_t getBitPosition () const override
PDB_CallingConv getCallingConvention () const override
SymIndexId getClassParentId () const override
std::string getCompilerName () const override
uint32_t getCount () const override
uint32_t getCountLiveRanges () const override
PDB_Lang getLanguage () const override
SymIndexId getLexicalParentId () const override
std::string getLibraryName () const override
uint32_t getLiveRangeStartAddressOffset () const override
uint32_t getLiveRangeStartAddressSection () const override
uint32_t getLiveRangeStartRelativeVirtualAddress () const override
codeview::RegisterId getLocalBasePointerRegisterId () const override
SymIndexId getLowerBoundId () const override
uint32_t getMemorySpaceKind () const override
std::string getName () const override
uint32_t getNumberOfAcceleratorPointerTags () const override
uint32_t getNumberOfColumns () const override
uint32_t getNumberOfModifiers () const override
uint32_t getNumberOfRegisterIndices () const override
uint32_t getNumberOfRows () const override
std::string getObjectFileName () const override
uint32_t getOemId () const override
SymIndexId getOemSymbolId () const override
uint32_t getOffsetInUdt () const override
PDB_Cpu getPlatform () const override
uint32_t getRank () const override
codeview::RegisterId getRegisterId () const override
uint32_t getRegisterType () const override
uint32_t getRelativeVirtualAddress () const override
uint32_t getSamplerSlot () const override
uint32_t getSignature () const override
uint32_t getSizeInUdt () const override
uint32_t getSlot () const override
std::string getSourceFileName () const override
std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const override
uint32_t getStride () const override
SymIndexId getSubTypeId () const override
std::string getSymbolsFileName () const override
SymIndexId getSymIndexId () const override
uint32_t getTargetOffset () const override
uint32_t getTargetRelativeVirtualAddress () const override
uint64_t getTargetVirtualAddress () const override
uint32_t getTargetSection () const override
uint32_t getTextureSlot () const override
uint32_t getTimeStamp () const override
uint32_t getToken () const override
SymIndexId getTypeId () const override
uint32_t getUavSlot () const override
std::string getUndecoratedName () const override
std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const override
SymIndexId getUnmodifiedTypeId () const override
SymIndexId getUpperBoundId () const override
Variant getValue () const override
uint32_t getVirtualBaseDispIndex () const override
uint32_t getVirtualBaseOffset () const override
SymIndexId getVirtualTableShapeId () const override
std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const override
PDB_DataKind getDataKind () const override
PDB_SymType getSymTag () const override
codeview::GUID getGuid () const override
int32_t getOffset () const override
int32_t getThisAdjust () const override
int32_t getVirtualBasePointerOffset () const override
PDB_LocType getLocationType () const override
PDB_Machine getMachineType () const override
codeview::ThunkOrdinal getThunkOrdinal () const override
uint64_t getLength () const override
uint64_t getLiveRangeLength () const override
uint64_t getVirtualAddress () const override
PDB_UdtType getUdtKind () const override
bool hasConstructor () const override
bool hasCustomCallingConvention () const override
bool hasFarReturn () const override
bool isCode () const override
bool isCompilerGenerated () const override
bool isConstType () const override
bool isEditAndContinueEnabled () const override
bool isFunction () const override
bool getAddressTaken () const override
bool getNoStackOrdering () const override
bool hasAlloca () const override
bool hasAssignmentOperator () const override
bool hasCTypes () const override
bool hasCastOperator () const override
bool hasDebugInfo () const override
bool hasEH () const override
bool hasEHa () const override
bool hasInlAsm () const override
bool hasInlineAttribute () const override
bool hasInterruptReturn () const override
bool hasFramePointer () const override
bool hasLongJump () const override
bool hasManagedCode () const override
bool hasNestedTypes () const override
bool hasNoInlineAttribute () const override
bool hasNoReturnAttribute () const override
bool hasOptimizedCodeDebugInfo () const override
bool hasOverloadedOperator () const override
bool hasSEH () const override
bool hasSecurityChecks () const override
bool hasSetJump () const override
bool hasStrictGSCheck () const override
bool isAcceleratorGroupSharedLocal () const override
bool isAcceleratorPointerTagLiveRange () const override
bool isAcceleratorStubFunction () const override
bool isAggregated () const override
bool isIntroVirtualFunction () const override
bool isCVTCIL () const override
bool isConstructorVirtualBase () const override
bool isCxxReturnUdt () const override
bool isDataAligned () const override
bool isHLSLData () const override
bool isHotpatchable () const override
bool isIndirectVirtualBaseClass () const override
bool isInterfaceUdt () const override
bool isIntrinsic () const override
bool isLTCG () const override
bool isLocationControlFlowDependent () const override
bool isMSILNetmodule () const override
bool isMatrixRowMajor () const override
bool isManagedCode () const override
bool isMSILCode () const override
bool isMultipleInheritance () const override
bool isNaked () const override
bool isNested () const override
bool isOptimizedAway () const override
bool isPacked () const override
bool isPointerBasedOnSymbolValue () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
bool isPureVirtual () const override
bool isRValueReference () const override
bool isRefUdt () const override
bool isReference () const override
bool isRestrictedType () const override
bool isReturnValue () const override
bool isSafeBuffers () const override
bool isScoped () const override
bool isSdl () const override
bool isSingleInheritance () const override
bool isSplitted () const override
bool isStatic () const override
bool hasPrivateSymbols () const override
bool isUnalignedType () const override
bool isUnreached () const override
bool isValueUdt () const override
bool isVirtual () const override
bool isVirtualBaseClass () const override
bool isVirtualInheritance () const override
bool isVolatileType () const override
bool wasInlined () const override
std::string getUnused () const override
Public Member Functions inherited from llvm::pdb::IPDBRawSymbol
virtual ~IPDBRawSymbol ()
virtual void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const =0
virtual void getDataBytes (llvm::SmallVector< uint8_t, 32 > &bytes) const =0
virtual void getBackEndVersion (VersionInfo &Version) const =0
virtual PDB_MemberAccess getAccess () const =0
virtual uint32_t getAddressOffset () const =0
virtual uint32_t getAddressSection () const =0
virtual uint32_t getAge () const =0
virtual SymIndexId getArrayIndexTypeId () const =0
virtual uint32_t getBaseDataOffset () const =0
virtual uint32_t getBaseDataSlot () const =0
virtual SymIndexId getBaseSymbolId () const =0
virtual PDB_BuiltinType getBuiltinType () const =0
virtual uint32_t getBitPosition () const =0
virtual PDB_CallingConv getCallingConvention () const =0
virtual SymIndexId getClassParentId () const =0
virtual std::string getCompilerName () const =0
virtual uint32_t getCount () const =0
virtual uint32_t getCountLiveRanges () const =0
virtual void getFrontEndVersion (VersionInfo &Version) const =0
virtual PDB_Lang getLanguage () const =0
virtual SymIndexId getLexicalParentId () const =0
virtual std::string getLibraryName () const =0
virtual uint32_t getLiveRangeStartAddressOffset () const =0
virtual uint32_t getLiveRangeStartAddressSection () const =0
virtual uint32_t getLiveRangeStartRelativeVirtualAddress () const =0
virtual codeview::RegisterId getLocalBasePointerRegisterId () const =0
virtual SymIndexId getLowerBoundId () const =0
virtual uint32_t getMemorySpaceKind () const =0
virtual std::string getName () const =0
virtual uint32_t getNumberOfAcceleratorPointerTags () const =0
virtual uint32_t getNumberOfColumns () const =0
virtual uint32_t getNumberOfModifiers () const =0
virtual uint32_t getNumberOfRegisterIndices () const =0
virtual uint32_t getNumberOfRows () const =0
virtual std::string getObjectFileName () const =0
virtual uint32_t getOemId () const =0
virtual SymIndexId getOemSymbolId () const =0
virtual uint32_t getOffsetInUdt () const =0
virtual PDB_Cpu getPlatform () const =0
virtual uint32_t getRank () const =0
virtual codeview::RegisterId getRegisterId () const =0
virtual uint32_t getRegisterType () const =0
virtual uint32_t getRelativeVirtualAddress () const =0
virtual uint32_t getSamplerSlot () const =0
virtual uint32_t getSignature () const =0
virtual uint32_t getSizeInUdt () const =0
virtual uint32_t getSlot () const =0
virtual std::string getSourceFileName () const =0
virtual std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const =0
virtual uint32_t getStride () const =0
virtual SymIndexId getSubTypeId () const =0
virtual std::string getSymbolsFileName () const =0
virtual SymIndexId getSymIndexId () const =0
virtual uint32_t getTargetOffset () const =0
virtual uint32_t getTargetRelativeVirtualAddress () const =0
virtual uint64_t getTargetVirtualAddress () const =0
virtual uint32_t getTargetSection () const =0
virtual uint32_t getTextureSlot () const =0
virtual uint32_t getTimeStamp () const =0
virtual uint32_t getToken () const =0
virtual SymIndexId getTypeId () const =0
virtual uint32_t getUavSlot () const =0
virtual std::string getUndecoratedName () const =0
virtual std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const =0
virtual SymIndexId getUnmodifiedTypeId () const =0
virtual SymIndexId getUpperBoundId () const =0
virtual Variant getValue () const =0
virtual uint32_t getVirtualBaseDispIndex () const =0
virtual uint32_t getVirtualBaseOffset () const =0
virtual std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const =0
virtual SymIndexId getVirtualTableShapeId () const =0
virtual PDB_DataKind getDataKind () const =0
virtual PDB_SymType getSymTag () const =0
virtual codeview::GUID getGuid () const =0
virtual int32_t getOffset () const =0
virtual int32_t getThisAdjust () const =0
virtual int32_t getVirtualBasePointerOffset () const =0
virtual PDB_LocType getLocationType () const =0
virtual PDB_Machine getMachineType () const =0
virtual codeview::ThunkOrdinal getThunkOrdinal () const =0
virtual uint64_t getLength () const =0
virtual uint64_t getLiveRangeLength () const =0
virtual uint64_t getVirtualAddress () const =0
virtual PDB_UdtType getUdtKind () const =0
virtual bool hasConstructor () const =0
virtual bool hasCustomCallingConvention () const =0
virtual bool hasFarReturn () const =0
virtual bool isCode () const =0
virtual bool isCompilerGenerated () const =0
virtual bool isConstType () const =0
virtual bool isEditAndContinueEnabled () const =0
virtual bool isFunction () const =0
virtual bool getAddressTaken () const =0
virtual bool getNoStackOrdering () const =0
virtual bool hasAlloca () const =0
virtual bool hasAssignmentOperator () const =0
virtual bool hasCTypes () const =0
virtual bool hasCastOperator () const =0
virtual bool hasDebugInfo () const =0
virtual bool hasEH () const =0
virtual bool hasEHa () const =0
virtual bool hasFramePointer () const =0
virtual bool hasInlAsm () const =0
virtual bool hasInlineAttribute () const =0
virtual bool hasInterruptReturn () const =0
virtual bool hasLongJump () const =0
virtual bool hasManagedCode () const =0
virtual bool hasNestedTypes () const =0
virtual bool hasNoInlineAttribute () const =0
virtual bool hasNoReturnAttribute () const =0
virtual bool hasOptimizedCodeDebugInfo () const =0
virtual bool hasOverloadedOperator () const =0
virtual bool hasSEH () const =0
virtual bool hasSecurityChecks () const =0
virtual bool hasSetJump () const =0
virtual bool hasStrictGSCheck () const =0
virtual bool isAcceleratorGroupSharedLocal () const =0
virtual bool isAcceleratorPointerTagLiveRange () const =0
virtual bool isAcceleratorStubFunction () const =0
virtual bool isAggregated () const =0
virtual bool isIntroVirtualFunction () const =0
virtual bool isCVTCIL () const =0
virtual bool isConstructorVirtualBase () const =0
virtual bool isCxxReturnUdt () const =0
virtual bool isDataAligned () const =0
virtual bool isHLSLData () const =0
virtual bool isHotpatchable () const =0
virtual bool isIndirectVirtualBaseClass () const =0
virtual bool isInterfaceUdt () const =0
virtual bool isIntrinsic () const =0
virtual bool isLTCG () const =0
virtual bool isLocationControlFlowDependent () const =0
virtual bool isMSILNetmodule () const =0
virtual bool isMatrixRowMajor () const =0
virtual bool isManagedCode () const =0
virtual bool isMSILCode () const =0
virtual bool isMultipleInheritance () const =0
virtual bool isNaked () const =0
virtual bool isNested () const =0
virtual bool isOptimizedAway () const =0
virtual bool isPacked () const =0
virtual bool isPointerBasedOnSymbolValue () const =0
virtual bool isPointerToDataMember () const =0
virtual bool isPointerToMemberFunction () const =0
virtual bool isPureVirtual () const =0
virtual bool isRValueReference () const =0
virtual bool isRefUdt () const =0
virtual bool isReference () const =0
virtual bool isRestrictedType () const =0
virtual bool isReturnValue () const =0
virtual bool isSafeBuffers () const =0
virtual bool isScoped () const =0
virtual bool isSdl () const =0
virtual bool isSingleInheritance () const =0
virtual bool isSplitted () const =0
virtual bool isStatic () const =0
virtual bool hasPrivateSymbols () const =0
virtual bool isUnalignedType () const =0
virtual bool isUnreached () const =0
virtual bool isValueUdt () const =0
virtual bool isVirtual () const =0
virtual bool isVirtualBaseClass () const =0
virtual bool isVirtualInheritance () const =0
virtual bool isVolatileType () const =0
virtual bool wasInlined () const =0
virtual std::string getUnused () const =0
Detailed Description
Definition at line 18 of file DIARawSymbol.h.
Constructor & Destructor Documentation
DIARawSymbol()
DIARawSymbol::DIARawSymbol (const DIASession & PDBSession, CComPtr< IDiaSymbol > DiaSymbol)
Definition at line 200 of file DIARawSymbol.cpp.
Member Function Documentation
dump()
void DIARawSymbol::dump (raw_ostream & OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 218 of file DIARawSymbol.cpp.
References llvm::pdb::ClassParent, llvm::count(), function, hasAlloca(), hasAssignmentOperator(), hasCastOperator(), hasDebugInfo(), hasEH(), hasEHa(), hasInlAsm(), hasLongJump(), hasManagedCode(), hasNestedTypes(), hasSecurityChecks(), hasSEH(), hasSetJump(), isAcceleratorGroupSharedLocal(), isAcceleratorPointerTagLiveRange(), isAcceleratorStubFunction(), isAggregated(), isConstructorVirtualBase(), isCVTCIL(), isCxxReturnUdt(), isDataAligned(), isHLSLData(), isHotpatchable(), isInterfaceUdt(), isLocationControlFlowDependent(), isLTCG(), isMatrixRowMajor(), isMSILNetmodule(), isMultipleInheritance(), isNaked(), isOptimizedAway(), isPointerBasedOnSymbolValue(), isPointerToDataMember(), isPointerToMemberFunction(), isRefUdt(), isReturnValue(), isSafeBuffers(), isSdl(), isSingleInheritance(), isSplitted(), isStatic(), isValueUdt(), isVirtualInheritance(), llvm::pdb::LexicalParent, name, RAW_ID_METHOD_DUMP, RAW_METHOD_DUMP, RAW_METHOD_DUMP_AS, llvm::pdb::SymIndexId, llvm::pdb::Type, llvm::pdb::UnmodifiedType, value, and wasInlined().
findChildren() [1/2]
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildren (PDB_SymType Type) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 398 of file DIARawSymbol.cpp.
References llvm::pdb::Type.
findChildren() [2/2]
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 412 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T, typename >::data(), Name, and llvm::pdb::Type.
findChildrenByAddr()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 430 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T, typename >::data(), Name, and llvm::pdb::Type.
findChildrenByRVA()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 469 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T, typename >::data(), Name, and llvm::pdb::Type.
findChildrenByVA()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 450 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T, typename >::data(), Name, and llvm::pdb::Type.
findInlineeLines()
std::unique_ptr< IPDBEnumLineNumbers > DIARawSymbol::findInlineeLines () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 513 of file DIARawSymbol.cpp.
findInlineeLinesByAddr()
std::unique_ptr< IPDBEnumLineNumbers > DIARawSymbol::findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 522 of file DIARawSymbol.cpp.
findInlineeLinesByRVA()
std::unique_ptr< IPDBEnumLineNumbers > DIARawSymbol::findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 533 of file DIARawSymbol.cpp.
findInlineeLinesByVA()
std::unique_ptr< IPDBEnumLineNumbers > DIARawSymbol::findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 542 of file DIARawSymbol.cpp.
findInlineFramesByAddr()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 487 of file DIARawSymbol.cpp.
findInlineFramesByRVA()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findInlineFramesByRVA (uint32_t RVA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 496 of file DIARawSymbol.cpp.
findInlineFramesByVA()
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findInlineFramesByVA (uint64_t VA) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 505 of file DIARawSymbol.cpp.
getAccess()
PDB_MemberAccess DIARawSymbol::getAccess () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 575 of file DIARawSymbol.cpp.
getAddressOffset()
uint32_t DIARawSymbol::getAddressOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 580 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getAddressSection()
uint32_t DIARawSymbol::getAddressSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 584 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getAddressTaken()
bool DIARawSymbol::getAddressTaken () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 970 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getAge()
uint32_t DIARawSymbol::getAge () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 588 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getArrayIndexTypeId()
SymIndexId DIARawSymbol::getArrayIndexTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 592 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBackEndVersion()
void DIARawSymbol::getBackEndVersion (VersionInfo & Version) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 596 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBaseDataOffset()
uint32_t DIARawSymbol::getBaseDataOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 603 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBaseDataSlot()
uint32_t DIARawSymbol::getBaseDataSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 607 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBaseSymbolId()
SymIndexId DIARawSymbol::getBaseSymbolId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 611 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBitPosition()
uint32_t DIARawSymbol::getBitPosition () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 620 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getBuiltinType()
PDB_BuiltinType DIARawSymbol::getBuiltinType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 615 of file DIARawSymbol.cpp.
getCallingConvention()
PDB_CallingConv DIARawSymbol::getCallingConvention () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 624 of file DIARawSymbol.cpp.
getClassParentId()
SymIndexId DIARawSymbol::getClassParentId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 629 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getCompilerName()
std::string DIARawSymbol::getCompilerName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 633 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getCount()
uint32_t DIARawSymbol::getCount () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 637 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getCountLiveRanges()
uint32_t DIARawSymbol::getCountLiveRanges () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 641 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getDataBytes()
void DIARawSymbol::getDataBytes (llvm::SmallVector< uint8_t, 32 > & bytes) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 550 of file DIARawSymbol.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::data(), and llvm::SmallVectorImpl< T >::resize().
getDataKind()
PDB_DataKind DIARawSymbol::getDataKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 880 of file DIARawSymbol.cpp.
getDiaSymbol()
CComPtr< IDiaSymbol > llvm::pdb::DIARawSymbol::getDiaSymbol () const inline
Definition at line 25 of file DIARawSymbol.h.
Referenced by llvm::pdb::DIASession::findLineNumbers(), and llvm::pdb::DIASession::getSourceFilesForCompiland().
getFrontEndVersion()
void DIARawSymbol::getFrontEndVersion (VersionInfo & Version) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 645 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getGuid()
codeview::GUID DIARawSymbol::getGuid () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 890 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLanguage()
PDB_Lang DIARawSymbol::getLanguage () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 652 of file DIARawSymbol.cpp.
getLength()
uint64_t DIARawSymbol::getLength () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 921 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLexicalParentId()
SymIndexId DIARawSymbol::getLexicalParentId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 656 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLibraryName()
std::string DIARawSymbol::getLibraryName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 660 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLiveRangeLength()
uint64_t DIARawSymbol::getLiveRangeLength () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 925 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLiveRangeStartAddressOffset()
uint32_t DIARawSymbol::getLiveRangeStartAddressOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 664 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLiveRangeStartAddressSection()
uint32_t DIARawSymbol::getLiveRangeStartAddressSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 669 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLiveRangeStartRelativeVirtualAddress()
uint32_t DIARawSymbol::getLiveRangeStartRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 674 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getLocalBasePointerRegisterId()
codeview::RegisterId DIARawSymbol::getLocalBasePointerRegisterId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 679 of file DIARawSymbol.cpp.
getLocationType()
PDB_LocType DIARawSymbol::getLocationType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 906 of file DIARawSymbol.cpp.
getLowerBoundId()
SymIndexId DIARawSymbol::getLowerBoundId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 684 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getMachineType()
PDB_Machine DIARawSymbol::getMachineType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 911 of file DIARawSymbol.cpp.
getMemorySpaceKind()
uint32_t DIARawSymbol::getMemorySpaceKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 688 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getName()
std::string DIARawSymbol::getName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 692 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNoStackOrdering()
bool DIARawSymbol::getNoStackOrdering () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 974 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNumberOfAcceleratorPointerTags()
uint32_t DIARawSymbol::getNumberOfAcceleratorPointerTags () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 696 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNumberOfColumns()
uint32_t DIARawSymbol::getNumberOfColumns () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 701 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNumberOfModifiers()
uint32_t DIARawSymbol::getNumberOfModifiers () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 705 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNumberOfRegisterIndices()
uint32_t DIARawSymbol::getNumberOfRegisterIndices () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 709 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getNumberOfRows()
uint32_t DIARawSymbol::getNumberOfRows () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 713 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getObjectFileName()
std::string DIARawSymbol::getObjectFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 717 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getOemId()
uint32_t DIARawSymbol::getOemId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 721 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getOemSymbolId()
SymIndexId DIARawSymbol::getOemSymbolId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 725 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getOffset()
int32_t DIARawSymbol::getOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 894 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getOffsetInUdt()
uint32_t DIARawSymbol::getOffsetInUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 729 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getPlatform()
PDB_Cpu DIARawSymbol::getPlatform () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 733 of file DIARawSymbol.cpp.
getRank()
uint32_t DIARawSymbol::getRank () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 737 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getRegisterId()
codeview::RegisterId DIARawSymbol::getRegisterId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 741 of file DIARawSymbol.cpp.
getRegisterType()
uint32_t DIARawSymbol::getRegisterType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 746 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by llvm::MipsTargetLowering::getRegisterTypeForCallingConv().
getRelativeVirtualAddress()
uint32_t DIARawSymbol::getRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 750 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSamplerSlot()
uint32_t DIARawSymbol::getSamplerSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 754 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSignature()
uint32_t DIARawSymbol::getSignature () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 758 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSizeInUdt()
uint32_t DIARawSymbol::getSizeInUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 762 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSlot()
uint32_t DIARawSymbol::getSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 766 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSourceFileName()
std::string DIARawSymbol::getSourceFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 770 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSrcLineOnTypeDefn()
std::unique_ptr< IPDBLineNumber > DIARawSymbol::getSrcLineOnTypeDefn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 774 of file DIARawSymbol.cpp.
getStride()
uint32_t DIARawSymbol::getStride () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 782 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSubTypeId()
SymIndexId DIARawSymbol::getSubTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 786 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSymbolsFileName()
std::string DIARawSymbol::getSymbolsFileName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 790 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSymIndexId()
SymIndexId DIARawSymbol::getSymIndexId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 794 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getSymTag()
PDB_SymType DIARawSymbol::getSymTag () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 885 of file DIARawSymbol.cpp.
getTargetOffset()
uint32_t DIARawSymbol::getTargetOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 798 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getTargetRelativeVirtualAddress()
uint32_t DIARawSymbol::getTargetRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 802 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getTargetSection()
uint32_t DIARawSymbol::getTargetSection () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 811 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getTargetVirtualAddress()
uint64_t DIARawSymbol::getTargetVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 807 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getTextureSlot()
uint32_t DIARawSymbol::getTextureSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 815 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getThisAdjust()
int32_t DIARawSymbol::getThisAdjust () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 898 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getThunkOrdinal()
codeview::ThunkOrdinal DIARawSymbol::getThunkOrdinal () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 916 of file DIARawSymbol.cpp.
getTimeStamp()
uint32_t DIARawSymbol::getTimeStamp () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 819 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getToken()
uint32_t DIARawSymbol::getToken () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 823 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getTypeId()
SymIndexId DIARawSymbol::getTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 827 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getUavSlot()
uint32_t DIARawSymbol::getUavSlot () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 831 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getUdtKind()
PDB_UdtType DIARawSymbol::getUdtKind () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 933 of file DIARawSymbol.cpp.
getUndecoratedName()
std::string DIARawSymbol::getUndecoratedName () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 835 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getUndecoratedNameEx()
std::string DIARawSymbol::getUndecoratedNameEx (PDB_UndnameFlags Flags) const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 562 of file DIARawSymbol.cpp.
References llvm::convertUTF16ToUTF8String().
getUnmodifiedTypeId()
SymIndexId DIARawSymbol::getUnmodifiedTypeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 839 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getUnused()
std::string DIARawSymbol::getUnused () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1268 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getUpperBoundId()
SymIndexId DIARawSymbol::getUpperBoundId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 843 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getValue()
Variant DIARawSymbol::getValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 847 of file DIARawSymbol.cpp.
getVirtualAddress()
uint64_t DIARawSymbol::getVirtualAddress () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 929 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getVirtualBaseDispIndex()
uint32_t DIARawSymbol::getVirtualBaseDispIndex () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 856 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getVirtualBaseOffset()
uint32_t DIARawSymbol::getVirtualBaseOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 860 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getVirtualBasePointerOffset()
int32_t DIARawSymbol::getVirtualBasePointerOffset () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 902 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
getVirtualBaseTableType()
std::unique_ptr< PDBSymbolTypeBuiltin > DIARawSymbol::getVirtualBaseTableType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 869 of file DIARawSymbol.cpp.
getVirtualTableShapeId()
SymIndexId DIARawSymbol::getVirtualTableShapeId () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 864 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasAlloca()
bool DIARawSymbol::hasAlloca () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 978 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasAssignmentOperator()
bool DIARawSymbol::hasAssignmentOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 982 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasCastOperator()
bool DIARawSymbol::hasCastOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 990 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasConstructor()
bool DIARawSymbol::hasConstructor () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 938 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasCTypes()
bool DIARawSymbol::hasCTypes () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 986 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasCustomCallingConvention()
bool DIARawSymbol::hasCustomCallingConvention () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 942 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasDebugInfo()
bool DIARawSymbol::hasDebugInfo () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 994 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasEH()
bool DIARawSymbol::hasEH () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 998 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasEHa()
bool DIARawSymbol::hasEHa () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1002 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasFarReturn()
bool DIARawSymbol::hasFarReturn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 946 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasFramePointer()
bool DIARawSymbol::hasFramePointer () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1018 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasInlAsm()
bool DIARawSymbol::hasInlAsm () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1006 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasInlineAttribute()
bool DIARawSymbol::hasInlineAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1010 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasInterruptReturn()
bool DIARawSymbol::hasInterruptReturn () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1014 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasLongJump()
bool DIARawSymbol::hasLongJump () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1022 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasManagedCode()
bool DIARawSymbol::hasManagedCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1026 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasNestedTypes()
bool DIARawSymbol::hasNestedTypes () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1030 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasNoInlineAttribute()
bool DIARawSymbol::hasNoInlineAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1034 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasNoReturnAttribute()
bool DIARawSymbol::hasNoReturnAttribute () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1038 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasOptimizedCodeDebugInfo()
bool DIARawSymbol::hasOptimizedCodeDebugInfo () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1042 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasOverloadedOperator()
bool DIARawSymbol::hasOverloadedOperator () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1046 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasPrivateSymbols()
bool DIARawSymbol::hasPrivateSymbols () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1230 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
hasSecurityChecks()
bool DIARawSymbol::hasSecurityChecks () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1054 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasSEH()
bool DIARawSymbol::hasSEH () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1050 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasSetJump()
bool DIARawSymbol::hasSetJump () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1058 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
hasStrictGSCheck()
bool DIARawSymbol::hasStrictGSCheck () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1062 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isAcceleratorGroupSharedLocal()
bool DIARawSymbol::isAcceleratorGroupSharedLocal () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1066 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isAcceleratorPointerTagLiveRange()
bool DIARawSymbol::isAcceleratorPointerTagLiveRange () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1071 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isAcceleratorStubFunction()
bool DIARawSymbol::isAcceleratorStubFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1076 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isAggregated()
bool DIARawSymbol::isAggregated () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1080 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isCode()
bool DIARawSymbol::isCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 950 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isCompilerGenerated()
bool DIARawSymbol::isCompilerGenerated () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 954 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isConstructorVirtualBase()
bool DIARawSymbol::isConstructorVirtualBase () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1092 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isConstType()
bool DIARawSymbol::isConstType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 958 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isCVTCIL()
bool DIARawSymbol::isCVTCIL () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1088 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isCxxReturnUdt()
bool DIARawSymbol::isCxxReturnUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1096 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isDataAligned()
bool DIARawSymbol::isDataAligned () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1100 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isEditAndContinueEnabled()
bool DIARawSymbol::isEditAndContinueEnabled () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 962 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isFunction()
bool DIARawSymbol::isFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 966 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isHLSLData()
bool DIARawSymbol::isHLSLData () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1104 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isHotpatchable()
bool DIARawSymbol::isHotpatchable () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1108 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isIndirectVirtualBaseClass()
bool DIARawSymbol::isIndirectVirtualBaseClass () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1112 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isInterfaceUdt()
bool DIARawSymbol::isInterfaceUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1116 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isIntrinsic()
bool DIARawSymbol::isIntrinsic () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1120 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isIntroVirtualFunction()
bool DIARawSymbol::isIntroVirtualFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1084 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isLocationControlFlowDependent()
bool DIARawSymbol::isLocationControlFlowDependent () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1128 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isLTCG()
bool DIARawSymbol::isLTCG () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1124 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isManagedCode()
bool DIARawSymbol::isManagedCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1141 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isMatrixRowMajor()
bool DIARawSymbol::isMatrixRowMajor () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1137 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isMSILCode()
bool DIARawSymbol::isMSILCode () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1145 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isMSILNetmodule()
bool DIARawSymbol::isMSILNetmodule () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1133 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isMultipleInheritance()
bool DIARawSymbol::isMultipleInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1149 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isNaked()
bool DIARawSymbol::isNaked () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1153 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isNested()
bool DIARawSymbol::isNested () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1157 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isOptimizedAway()
bool DIARawSymbol::isOptimizedAway () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1161 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isPacked()
bool DIARawSymbol::isPacked () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1165 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isPointerBasedOnSymbolValue()
bool DIARawSymbol::isPointerBasedOnSymbolValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1169 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isPointerToDataMember()
bool DIARawSymbol::isPointerToDataMember () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1174 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isPointerToMemberFunction()
bool DIARawSymbol::isPointerToMemberFunction () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1178 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isPureVirtual()
bool DIARawSymbol::isPureVirtual () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1182 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isReference()
bool DIARawSymbol::isReference () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1194 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isRefUdt()
bool DIARawSymbol::isRefUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1190 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isRestrictedType()
bool DIARawSymbol::isRestrictedType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1198 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isReturnValue()
bool DIARawSymbol::isReturnValue () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1202 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isRValueReference()
bool DIARawSymbol::isRValueReference () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1186 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isSafeBuffers()
bool DIARawSymbol::isSafeBuffers () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1206 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isScoped()
bool DIARawSymbol::isScoped () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1210 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isSdl()
bool DIARawSymbol::isSdl () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1214 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isSingleInheritance()
bool DIARawSymbol::isSingleInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1218 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isSplitted()
bool DIARawSymbol::isSplitted () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1222 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isStatic()
bool DIARawSymbol::isStatic () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1226 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isUnalignedType()
bool DIARawSymbol::isUnalignedType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1236 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isUnreached()
bool DIARawSymbol::isUnreached () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1240 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isValueUdt()
bool DIARawSymbol::isValueUdt () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1244 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isVirtual()
bool DIARawSymbol::isVirtual () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1248 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isVirtualBaseClass()
bool DIARawSymbol::isVirtualBaseClass () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1252 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
isVirtualInheritance()
bool DIARawSymbol::isVirtualInheritance () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1256 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
isVolatileType()
bool DIARawSymbol::isVolatileType () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1260 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
wasInlined()
bool DIARawSymbol::wasInlined () const override virtual
Implements llvm::pdb::IPDBRawSymbol.
Definition at line 1264 of file DIARawSymbol.cpp.
References PrivateGetDIAValue().
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIARawSymbol.h
lib/DebugInfo/PDB/DIA/DIARawSymbol.cpp