LLVM: llvm::TargetRegisterInfo Class Reference
llvm::TargetRegisterInfo Class Reference abstract
TargetRegisterInfo base class - We assume that the target defines a static array of TargetRegisterDesc objects that represent all of the machine registers that the target has.
#include "llvm/CodeGen/TargetRegisterInfo.h"
Classes
struct RegClassInfo
Public Types
using regclass_iterator = const TargetRegisterClass *const *
using vt_iterator = const MVT::SimpleValueType *
Public Types inherited from llvm::MCRegisterInfo
using regclass_iterator = const MCRegisterClass *
Public Member Functions
unsigned getRegSizeInBits (const TargetRegisterClass &RC) const
Return the size in bits of a register from class RC.
unsigned getSpillSize (const TargetRegisterClass &RC) const
Return the size in bytes of the stack slot allocated to hold a spilled copy of a register from class RC.
unsigned getSpillAlignment (const TargetRegisterClass &RC) const
Return the minimum required alignment in bytes for a spill slot for a register of this class.
bool isTypeLegalForClass (const TargetRegisterClass &RC, MVT T) const
Return true if the given TargetRegisterClass has the ValueType T.
vt_iterator legalclasstypes_begin (const TargetRegisterClass &RC) const
Loop over all of the value types that can be represented by values in the given register class.
vt_iterator legalclasstypes_end (const TargetRegisterClass &RC) const
const TargetRegisterClass * getMinimalPhysRegClass (unsigned Reg, MVT VT=MVT::Other) const
Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
const TargetRegisterClass * getAllocatableClass (const TargetRegisterClass *RC) const
Return the maximal subclass of the given register class that is allocatable or NULL.
BitVector getAllocatableSet (const MachineFunction &MF, const TargetRegisterClass *RC=nullptr) const
Returns a bitset indexed by register number indicating if a register is allocatable or not.
unsigned getCostPerUse (unsigned RegNo) const
Return the additional cost of using this register instead of other registers in its class.
bool isInAllocatableClass (unsigned RegNo) const
Return true if the register is in the allocation of any register class.
const char * getSubRegIndexName (unsigned SubIdx) const
Return the human-readable symbolic target-specific name for the specified SubRegIndex.
LaneBitmask getSubRegIndexLaneMask (unsigned SubIdx) const
Return a bitmask representing the parts of a register that are covered by SubIdx.
LaneBitmask getCoveringLanes () const
The lane masks returned by getSubRegIndexLaneMask() above can only be used to determine if sub-registers overlap - they can't be used to determine if a set of sub-registers completely cover another sub-register.
bool regsOverlap (unsigned regA, unsigned regB) const
Returns true if the two registers are equal or alias each other.
bool hasRegUnit (unsigned Reg, unsigned RegUnit) const
Returns true if Reg contains RegUnit.
virtual unsigned lookThruCopyLike (unsigned SrcReg, const MachineRegisterInfo *MRI) const
Returns the original SrcReg unless it is the target of a copy-like operation, in which case we chain backwards through all such operations to the ultimate source register.
virtual const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const =0
Return a null-terminated list of all of the callee-saved registers on this target.
virtual const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const
Return a mask of call-preserved registers for the given calling convention on the current function.
virtual const uint32_t * getNoPreservedMask () const
Return a register mask that clobbers everything.
bool regmaskSubsetEqual (const uint32_t *mask0, const uint32_t *mask1) const
Return true if all bits that are set in mask mask0 are also set in mask1.
virtual ArrayRef< const uint32_t * > getRegMasks () const =0
Return all the call-preserved register masks defined for this target.
virtual ArrayRef< const char * > getRegMaskNames () const =0
virtual BitVector getReservedRegs (const MachineFunction &MF) const =0
Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
virtual bool isAsmClobberable (const MachineFunction &MF, unsigned PhysReg) const
Returns false if we can't guarantee that Physreg, specified as an IR asm clobber constraint, will be preserved across the statement.
virtual bool isConstantPhysReg (unsigned PhysReg) const
Returns true if PhysReg is unallocatable and constant throughout the function.
virtual bool isDivergentRegClass (const TargetRegisterClass *RC) const
Returns true if the register class is considered divergent.
virtual bool isCallerPreservedPhysReg (unsigned PhysReg, const MachineFunction &MF) const
Physical registers that may be modified within a function but are guaranteed to be restored before any uses.
virtual void adjustStackMapLiveOutMask (uint32_t *Mask) const
Prior to adding the live-out mask to a stackmap or patchpoint instruction, provide the target the opportunity to adjust it (mainly to remove pseudo-registers that should be ignored).
unsigned getMatchingSuperReg (unsigned Reg, unsigned SubIdx, const TargetRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
virtual const TargetRegisterClass * getMatchingSuperRegClass (const TargetRegisterClass *A, const TargetRegisterClass *B, unsigned Idx) const
Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
virtual bool shouldRewriteCopySrc (const TargetRegisterClass *DefRC, unsigned DefSubReg, const TargetRegisterClass *SrcRC, unsigned SrcSubReg) const
virtual const TargetRegisterClass * getSubClassWithSubReg (const TargetRegisterClass *RC, unsigned Idx) const
Returns the largest legal sub-class of RC that supports the sub-register index Idx.
unsigned composeSubRegIndices (unsigned a, unsigned b) const
Return the subregister index you get from composing two subregister indices.
LaneBitmask composeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask Mask) const
Transforms a LaneMask computed for one subregister to the lanemask that would have been computed when composing the subsubregisters with IdxA first.
LaneBitmask reverseComposeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask LaneMask) const
Transform a lanemask given for a virtual register to the corresponding lanemask before using subregister with index IdxA.
const TargetRegisterClass * getCommonSuperRegClass (const TargetRegisterClass *RCA, unsigned SubA, const TargetRegisterClass *RCB, unsigned SubB, unsigned &PreA, unsigned &PreB) const
Find a common super-register class if it exists.
regclass_iterator regclass_begin () const
Register class iterators.
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const TargetRegisterClass * getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const TargetRegisterClass *Class) const
Returns the name of the register class.
const TargetRegisterClass * getCommonSubClass (const TargetRegisterClass *A, const TargetRegisterClass *B, const MVT::SimpleValueType SVT=MVT::SimpleValueType::Any) const
Find the largest common subclass of A and B.
virtual const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const
Returns a TargetRegisterClass used for pointer values.
virtual const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const
Returns a legal register class to copy a register in the specified class to or from.
virtual const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &) const
Returns the largest super class of RC that is legal to use in the current sub-target and has the same spill size.
virtual unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const
Return the register pressure "high water mark" for the specific register class.
virtual unsigned getRegPressureSetScore (const MachineFunction &MF, unsigned PSetID) const
Return a heuristic for the machine scheduler to compare the profitability of increasing one register pressure set versus another.
virtual const RegClassWeight & getRegClassWeight (const TargetRegisterClass *RC) const =0
Get the weight in units of pressure for this register class.
unsigned getRegSizeInBits (unsigned Reg, const MachineRegisterInfo &MRI) const
Returns size in bits of a phys/virtual/generic register.
virtual unsigned getRegUnitWeight (unsigned RegUnit) const =0
Get the weight in units of pressure for this register unit.
virtual unsigned getNumRegPressureSets () const =0
Get the number of dimensions of register pressure.
virtual const char * getRegPressureSetName (unsigned Idx) const =0
Get the name of this register unit pressure set.
virtual unsigned getRegPressureSetLimit (const MachineFunction &MF, unsigned Idx) const =0
Get the register unit pressure limit for this dimension.
virtual const int * getRegClassPressureSets (const TargetRegisterClass *RC) const =0
Get the dimensions of register pressure impacted by this register class.
virtual const int * getRegUnitPressureSets (unsigned RegUnit) const =0
Get the dimensions of register pressure impacted by this register unit.
virtual bool getRegAllocationHints (unsigned VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM=nullptr, const LiveRegMatrix *Matrix=nullptr) const
Get a list of 'hint' registers that the register allocator should try first when allocating a physical register for the virtual register VirtReg.
virtual void updateRegAllocHint (unsigned Reg, unsigned NewReg, MachineFunction &MF) const
A callback to allow target a chance to update register allocation hints when a register is "changed" (e.g.
virtual bool reverseLocalAssignment () const
Allow the target to reverse allocation order of local live ranges.
virtual unsigned getCSRFirstUseCost () const
Allow the target to override the cost of using a callee-saved register for the first time.
virtual bool requiresRegisterScavenging (const MachineFunction &MF) const
Returns true if the target requires (and can make use of) the register scavenger.
virtual bool useFPForScavengingIndex (const MachineFunction &MF) const
Returns true if the target wants to use frame pointer based accesses to spill to the scavenger emergency spill slot.
virtual bool requiresFrameIndexScavenging (const MachineFunction &MF) const
Returns true if the target requires post PEI scavenging of registers for materializing frame index constants.
virtual bool requiresFrameIndexReplacementScavenging (const MachineFunction &MF) const
Returns true if the target requires using the RegScavenger directly for frame elimination despite using requiresFrameIndexScavenging.
virtual bool requiresVirtualBaseRegisters (const MachineFunction &MF) const
Returns true if the target wants the LocalStackAllocation pass to be run and virtual base registers used for more efficient stack access.
virtual bool hasReservedSpillSlot (const MachineFunction &MF, unsigned Reg, int &FrameIdx) const
Return true if target has reserved a spill slot in the stack frame of the given function for the specified register.
virtual bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const
Returns true if the live-ins should be tracked after register allocation.
virtual bool canRealignStack (const MachineFunction &MF) const
True if the stack can be realigned for the target.
bool needsStackRealignment (const MachineFunction &MF) const
True if storage within the function requires the stack pointer to be aligned more than the normal calling convention calls for.
virtual int64_t getFrameIndexInstrOffset (const MachineInstr *MI, int Idx) const
Get the offset from the referenced frame index in the instruction, if there is one.
virtual bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
virtual void materializeFrameBaseRegister (MachineBasicBlock *MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx before insertion point I.
virtual void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const
Resolve a frame index operand of an instruction to reference the indicated base register plus offset instead.
virtual bool isFrameOffsetLegal (const MachineInstr *MI, unsigned BaseReg, int64_t Offset) const
Determine whether a given base register plus offset immediate is encodable to resolve a frame index.
virtual bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, unsigned Reg) const
Spill the register so it can be used by the register scavenger.
virtual void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const =0
This method must be overriden to eliminate abstract frame indices from instructions which may use them.
virtual StringRef getRegAsmName (unsigned Reg) const
Return the assembly name for Reg.
virtual bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const
Subtarget Hooks.
virtual Register getFrameRegister (const MachineFunction &MF) const =0
Debug information queries.
void markSuperRegs (BitVector &RegisterSet, unsigned Reg) const
Mark a register and all its aliases as reserved in the given set.
bool checkAllSuperRegsMarked (const BitVector &RegisterSet, ArrayRef< MCPhysReg > Exceptions=ArrayRef< MCPhysReg >()) const
Returns true if for every register in the set all super registers are part of the set as well.
virtual const TargetRegisterClass * getConstrainedRegClassForOperand (const MachineOperand &MO, const MachineRegisterInfo &MRI) const
Public Member Functions inherited from llvm::MCRegisterInfo
void InitMCRegisterInfo (const MCRegisterDesc *D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass *C, unsigned NC, const MCPhysReg(*RURoots)[2], unsigned NRU, const MCPhysReg *DL, const LaneBitmask *RUMS, const char *Strings, const char *ClassStrings, const uint16_t *SubIndices, unsigned NumIndices, const SubRegCoveredBits *SubIdxRanges, const uint16_t *RET)
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
void mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize LLVM register to Dwarf register number mapping.
void mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize Dwarf register to LLVM register number mapping.
void mapLLVMRegToSEHReg (unsigned LLVMReg, int SEHReg)
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
void mapLLVMRegToCVReg (unsigned LLVMReg, int CVReg)
unsigned getRARegister () const
This method should return the register where the return address can be found.
unsigned getProgramCounter () const
Return the register which is the program counter.
const MCRegisterDesc & operator[] (unsigned RegNo) const
const MCRegisterDesc & get (unsigned RegNo) const
Provide a get method, equivalent to [], but more useful with a pointer to this object.
unsigned getSubReg (unsigned Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
unsigned getMatchingSuperReg (unsigned Reg, unsigned SubIdx, const MCRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
unsigned getSubRegIndex (unsigned RegNo, unsigned SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
unsigned getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
unsigned getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
const char * getName (unsigned RegNo) const
Return the human-readable symbolic target-specific name for the specified physical register.
unsigned getNumRegs () const
Return the number of registers this target has (useful for sizing arrays holding per register information)
unsigned getNumSubRegIndices () const
Return the number of sub-register indices understood by the target.
unsigned getNumRegUnits () const
Return the number of (native) register units in the target.
int getDwarfRegNum (unsigned RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
int getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
int getLLVMRegNumFromEH (unsigned RegNum) const
Map a DWARF EH register back to a target register (same as getLLVMRegNum(RegNum, true)) but return -1 if there is no mapping, rather than asserting that there must be one.
int getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
int getSEHRegNum (unsigned RegNum) const
Map a target register to an equivalent SEH register number.
int getCodeViewRegNum (unsigned RegNum) const
Map a target register to an equivalent CodeView register number.
regclass_iterator regclass_begin () const
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const MCRegisterClass & getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const MCRegisterClass *Class) const
uint16_t getEncodingValue (unsigned RegNo) const
Returns the encoding for RegNo.
bool isSubRegister (unsigned RegA, unsigned RegB) const
Returns true if RegB is a sub-register of RegA.
bool isSuperRegister (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register of RegA.
bool isSubRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
bool isSuperRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register of RegA or if RegB == RegA.
bool isSuperOrSubRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
Static Public Member Functions
static bool isStackSlot (unsigned Reg)
isStackSlot - Sometimes it is useful the be able to store a non-negative frame index in a variable that normally holds a register.
static int stackSlot2Index (unsigned Reg)
Compute the frame index from a register value representing a stack slot.
static unsigned index2StackSlot (int FI)
Convert a non-negative frame index to a stack slot register value.
static bool isPhysicalRegister (unsigned Reg)
Return true if the specified register number is in the physical register namespace.
static bool isVirtualRegister (unsigned Reg)
Return true if the specified register number is in the virtual register namespace.
static unsigned virtReg2Index (unsigned Reg)
Convert a virtual register number to a 0-based index.
static unsigned index2VirtReg (unsigned Index)
Convert a 0-based index to a virtual register number.
static void dumpReg (unsigned Reg, unsigned SubRegIndex=0, const TargetRegisterInfo *TRI=nullptr)
Debugging helper: dump register in human readable form to dbgs() stream.
Protected Member Functions
TargetRegisterInfo (const TargetRegisterInfoDesc *ID, regclass_iterator RCB, regclass_iterator RCE, const char *const *SRINames, const LaneBitmask *SRILaneMasks, LaneBitmask CoveringLanes, const RegClassInfo *const RCIs, unsigned Mode=0)
virtual ~TargetRegisterInfo ()
virtual unsigned composeSubRegIndicesImpl (unsigned, unsigned) const
Overridden by TableGen in targets that have sub-registers.
virtual LaneBitmask composeSubRegIndexLaneMaskImpl (unsigned, LaneBitmask) const
Overridden by TableGen in targets that have sub-registers.
virtual LaneBitmask reverseComposeSubRegIndexLaneMaskImpl (unsigned, LaneBitmask) const
const RegClassInfo & getRegClassInfo (const TargetRegisterClass &RC) const
Detailed Description
TargetRegisterInfo base class - We assume that the target defines a static array of TargetRegisterDesc objects that represent all of the machine registers that the target has.
As such, we simply have to track a pointer to this array so that we can turn register number into a register descriptor.
Definition at line 219 of file TargetRegisterInfo.h.
Member Typedef Documentation
regclass_iterator
using llvm::TargetRegisterInfo::regclass_iterator = const TargetRegisterClass * const *
Definition at line 221 of file TargetRegisterInfo.h.
vt_iterator
using llvm::TargetRegisterInfo::vt_iterator = const MVT::SimpleValueType *
Definition at line 222 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
TargetRegisterInfo()
TargetRegisterInfo::TargetRegisterInfo (const TargetRegisterInfoDesc * ID, regclass_iterator RCB, regclass_iterator RCE, const char *const * SRINames, const LaneBitmask * SRILaneMasks, LaneBitmask CoveringLanes, const RegClassInfo *const RCIs, unsigned Mode = 0) protected
Definition at line 42 of file TargetRegisterInfo.cpp.
References Mode.
~TargetRegisterInfo()
TargetRegisterInfo::~TargetRegisterInfo () protected virtual default
Member Function Documentation
adjustStackMapLiveOutMask()
virtual void llvm::TargetRegisterInfo::adjustStackMapLiveOutMask (uint32_t * Mask) const inline virtual
Prior to adding the live-out mask to a stackmap or patchpoint instruction, provide the target the opportunity to adjust it (mainly to remove pseudo-registers that should be ignored).
Definition at line 541 of file TargetRegisterInfo.h.
canRealignStack()
bool TargetRegisterInfo::canRealignStack (const MachineFunction & MF) const virtual
True if the stack can be realigned for the target.
Definition at line 436 of file TargetRegisterInfo.cpp.
References llvm::MachineFunction::getFunction().
Referenced by llvm::SIRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::MipsRegisterInfo::canRealignStack(), llvm::SparcRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), and needsStackRealignment().
checkAllSuperRegsMarked()
bool TargetRegisterInfo::checkAllSuperRegsMarked (const BitVector & RegisterSet, ArrayRef< MCPhysReg > Exceptions = ArrayRef<MCPhysReg>()) const
Returns true if for every register in the set all super registers are part of the set as well.
Definition at line 64 of file TargetRegisterInfo.cpp.
References llvm::dbgs(), llvm::MCRegisterInfo::getNumRegs(), llvm::is_contained(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::printReg(), and llvm::BitVector::set().
composeSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::composeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask Mask) const inline
Transforms a LaneMask computed for one subregister to the lanemask that would have been computed when composing the subsubregisters with IdxA first.
See also
composeSubRegIndices()
Definition at line 608 of file TargetRegisterInfo.h.
References composeSubRegIndexLaneMaskImpl().
Referenced by llvm::rdf::PhysicalRegisterInfo::mapTo().
composeSubRegIndexLaneMaskImpl()
virtual LaneBitmask llvm::TargetRegisterInfo::composeSubRegIndexLaneMaskImpl (unsigned , LaneBitmask) const inline protected virtual
Overridden by TableGen in targets that have sub-registers.
Definition at line 641 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by composeSubRegIndexLaneMask().
composeSubRegIndices()
unsigned llvm::TargetRegisterInfo::composeSubRegIndices (unsigned a, unsigned b) const inline
Return the subregister index you get from composing two subregister indices.
The special null sub-register index composes as the identity.
If R:a:b is the same register as R:c, then composeSubRegIndices(a, b) returns c. Note that composeSubRegIndices does not tell you about illegal compositions. If R does not have a subreg a, or R:a does not have a subreg b, composeSubRegIndices doesn't tell you.
The ARM register Q0 has two D subregs dsub_0:D0 and dsub_1:D1. It also has ssub_0:S0 - ssub_3:S3 subregs. If you compose subreg indices dsub_1, ssub_0 you get ssub_2.
Definition at line 599 of file TargetRegisterInfo.h.
References composeSubRegIndicesImpl().
Referenced by getCommonSuperRegClass().
composeSubRegIndicesImpl()
virtual unsigned llvm::TargetRegisterInfo::composeSubRegIndicesImpl (unsigned , unsigned) const inline protected virtual
Overridden by TableGen in targets that have sub-registers.
Definition at line 635 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by composeSubRegIndices().
dumpReg()
LLVM_DUMP_METHOD void TargetRegisterInfo::dumpReg (unsigned Reg, unsigned SubRegIndex = 0, const TargetRegisterInfo * TRI = nullptr) static
Debugging helper: dump register in human readable form to dbgs() stream.
Definition at line 513 of file TargetRegisterInfo.cpp.
References llvm::dbgs(), llvm::printReg(), and TRI.
eliminateFrameIndex()
virtual void llvm::TargetRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const pure virtual
This method must be overriden to eliminate abstract frame indices from instructions which may use them.
The instruction referenced by the iterator contains an MO_FrameIndex operand which must be eliminated by this method. This method may modify or replace the specified instruction, as long as it keeps the iterator pointing at the finished product. SPAdj is the SP adjustment due to call frame setup instruction. FIOperandNum is the FI operand number.
getAllocatableClass()
const TargetRegisterClass * TargetRegisterInfo::getAllocatableClass (const TargetRegisterClass * RC) const
Return the maximal subclass of the given register class that is allocatable or NULL.
getAllocatableClass - Return the maximal subclass of the given register class that is alloctable, or NULL.
Definition at line 174 of file TargetRegisterInfo.cpp.
References getRegClass(), llvm::TargetRegisterClass::getSubClassMask(), llvm::TargetRegisterClass::isAllocatable(), and llvm::BitMaskClassIterator::isValid().
Referenced by getAllocatableSet().
getAllocatableSet()
BitVector TargetRegisterInfo::getAllocatableSet (const MachineFunction & MF, const TargetRegisterClass * RC = nullptr) const
Returns a bitset indexed by register number indicating if a register is allocatable or not.
If a register class is specified, returns the subset for the class.
Definition at line 217 of file TargetRegisterInfo.cpp.
References C, llvm::BitVector::flip(), getAllocatableClass(), getAllocatableSetForRC(), llvm::MCRegisterInfo::getNumRegs(), getReservedRegs(), and regclasses().
Referenced by addLiveInRegs(), llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker(), and llvm::RegScavenger::scavengeRegister().
getCalleeSavedRegs()
virtual const MCPhysReg * llvm::TargetRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const pure virtual
Return a null-terminated list of all of the callee-saved registers on this target.
The register should be in the order of desired callee-save stack frame offset. The first register is closest to the incoming stack pointer if stack grows down, and vice versa. Notice: This function does not take into account disabled CSRs. In most cases you will want to use instead the function getCalleeSavedRegs that is implemented in MachineRegisterInfo.
Referenced by llvm::MachineRegisterInfo::getCalleeSavedRegs().
getCallPreservedMask()
virtual const uint32_t * llvm::TargetRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const inline virtual
Return a mask of call-preserved registers for the given calling convention on the current function.
The mask should include all call-preserved aliases. This is used by the register allocator to determine which registers can be live across a call.
The mask is an array containing (TRI::getNumRegs()+31)/32 entries. A set bit indicates that all bits of the corresponding register are preserved across the function call. The bit mask is expected to be sub-register complete, i.e. if A is preserved, so are all its sub-registers.
Bits are numbered from the LSB, so the bit for physical register Reg can be found as (Mask[Reg / 32] >> Reg % 32) & 1.
A NULL pointer means that no register mask will be used, and call instructions should use implicit-def operands to indicate call clobbered registers.
Definition at line 481 of file TargetRegisterInfo.h.
Referenced by llvm::FastISel::selectPatchpoint().
getCommonSubClass()
const TargetRegisterClass * TargetRegisterInfo::getCommonSubClass (const TargetRegisterClass * A, const TargetRegisterClass * B, const MVT::SimpleValueType SVT = MVT::SimpleValueType::Any) const
Find the largest common subclass of A and B.
Return NULL if there is no common subclass. The common subclass should contain simple value type SVT if it is not the Any type.
Definition at line 256 of file TargetRegisterInfo.cpp.
References A, B, and firstCommonClass().
Referenced by llvm::LiveStacks::getOrCreateInterval().
getCommonSuperRegClass()
const TargetRegisterClass * TargetRegisterInfo::getCommonSuperRegClass (const TargetRegisterClass * RCA, unsigned SubA, const TargetRegisterClass * RCB, unsigned SubB, unsigned & PreA, unsigned & PreB) const
Find a common super-register class if it exists.
Find a register class, SuperRC and two sub-register indices, PreA and PreB, such that:
PreA + SubA == PreB + SubB (using composeSubRegIndices()), and
For all Reg in SuperRC: Reg:PreA in RCA and Reg:PreB in RCB, and
SuperRC->getSize() >= max(RCA->getSize(), RCB->getSize()).
SuperRC will be chosen such that no super-class of SuperRC satisfies the requirements, and there is no register class with a smaller spill size that satisfies the requirements.
SubA and SubB must not be 0. Use getMatchingSuperRegClass() instead.
Either of the PreA and PreB sub-register indices may be returned as 0. In that case, the returned register class will be a sub-class of the corresponding argument register class.
The function returns NULL if no register class can be found.
Definition at line 286 of file TargetRegisterInfo.cpp.
References assert(), composeSubRegIndices(), firstCommonClass(), getRegSizeInBits(), llvm::SuperRegClassIterator::isValid(), and std::swap().
getConstrainedRegClassForOperand()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getConstrainedRegClassForOperand (const MachineOperand & MO, const MachineRegisterInfo & MRI) const inline virtual
Definition at line 1004 of file TargetRegisterInfo.h.
getCostPerUse()
unsigned llvm::TargetRegisterInfo::getCostPerUse (unsigned RegNo) const inline
Return the additional cost of using this register instead of other registers in its class.
Definition at line 369 of file TargetRegisterInfo.h.
References llvm::TargetRegisterInfoDesc::CostPerUse.
getCoveringLanes()
LaneBitmask llvm::TargetRegisterInfo::getCoveringLanes () const inline
The lane masks returned by getSubRegIndexLaneMask() above can only be used to determine if sub-registers overlap - they can't be used to determine if a set of sub-registers completely cover another sub-register.
The X86 general purpose registers have two lanes corresponding to the sub_8bit and sub_8bit_hi sub-registers. Both sub_32bit and sub_16bit have lane masks '3', but the sub_16bit sub-register doesn't fully cover the sub_32bit sub-register.
On the other hand, the ARM NEON lanes fully cover their registers: The dsub_0 sub-register is completely covered by the ssub_0 and ssub_1 lanes. This is related to the CoveredBySubRegs property on register definitions.
This function returns a bit mask of lanes that completely cover their sub-registers. More precisely, given:
Covering = getCoveringLanes(); MaskA = getSubRegIndexLaneMask(SubA); MaskB = getSubRegIndexLaneMask(SubB);
If (MaskA & ~(MaskB & Covering)) == 0, then SubA is completely covered by SubB.
Definition at line 418 of file TargetRegisterInfo.h.
getCrossCopyRegClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const inline virtual
Returns a legal register class to copy a register in the specified class to or from.
If it is possible to copy the register directly without using a cross register class copy, return the specified RC. Returns NULL if it is not possible to copy between two registers of the specified class.
Definition at line 733 of file TargetRegisterInfo.h.
getCSRFirstUseCost()
virtual unsigned llvm::TargetRegisterInfo::getCSRFirstUseCost () const inline virtual
Allow the target to override the cost of using a callee-saved register for the first time.
Default value of 0 means we will use a callee-saved register if it is available.
Definition at line 845 of file TargetRegisterInfo.h.
getFrameIndexInstrOffset()
virtual int64_t llvm::TargetRegisterInfo::getFrameIndexInstrOffset (const MachineInstr * MI, int Idx) const inline virtual
Get the offset from the referenced frame index in the instruction, if there is one.
Definition at line 905 of file TargetRegisterInfo.h.
getFrameRegister()
virtual Register llvm::TargetRegisterInfo::getFrameRegister (const MachineFunction & MF) const pure virtual
Debug information queries.
getFrameRegister - This method should return the register used as a base for values allocated in the current stack frame.
Referenced by llvm::MipsAsmPrinter::emitFrameDirective(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
getLargestLegalSuperClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction &) const inline virtual
Returns the largest super class of RC that is legal to use in the current sub-target and has the same spill size.
The returned register class can be used to create virtual registers which means that all its registers can be copied and spilled.
The default implementation is very conservative and doesn't allow the register allocator to inflate register classes.
Definition at line 742 of file TargetRegisterInfo.h.
Referenced by llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::MachineRegisterInfo::recomputeRegClass().
getMatchingSuperReg()
unsigned llvm::TargetRegisterInfo::getMatchingSuperReg (unsigned Reg, unsigned SubIdx, const TargetRegisterClass * RC) const inline
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
Definition at line 545 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getMatchingSuperReg(), llvm::TargetRegisterClass::MC, and Reg.
Referenced by copyHint().
getMatchingSuperRegClass()
const TargetRegisterClass * TargetRegisterInfo::getMatchingSuperRegClass (const TargetRegisterClass * A, const TargetRegisterClass * B, unsigned Idx) const virtual
Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
TableGen will synthesize missing A sub-classes.
Definition at line 271 of file TargetRegisterInfo.cpp.
References A, assert(), B, firstCommonClass(), Idx, and llvm::SuperRegClassIterator::isValid().
getMinimalPhysRegClass()
const TargetRegisterClass * TargetRegisterInfo::getMinimalPhysRegClass (unsigned Reg, MVT VT = MVT::Other) const
Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
getMinimalPhysRegClass - Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
Definition at line 191 of file TargetRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::hasSubClass(), isPhysicalRegister(), isTypeLegalForClass(), llvm::MVT::Other, and regclasses().
Referenced by assignCalleeSavedSpillSlots(), llvm::BitTracker::MachineEvaluator::getPhysRegBitWidth(), llvm::HexagonEvaluator::getPhysRegBitWidth(), and getRegSizeInBits().
getNoPreservedMask()
virtual const uint32_t * llvm::TargetRegisterInfo::getNoPreservedMask () const inline virtual
Return a register mask that clobbers everything.
Definition at line 488 of file TargetRegisterInfo.h.
References llvm_unreachable.
getNumRegClasses()
unsigned llvm::TargetRegisterInfo::getNumRegClasses () const inline
Definition at line 694 of file TargetRegisterInfo.h.
References regclass_begin(), and regclass_end().
Referenced by getRegClass(), getRegClassInfo(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), and llvm::RegisterClassInfo::runOnMachineFunction().
getNumRegPressureSets()
virtual unsigned llvm::TargetRegisterInfo::getNumRegPressureSets () const pure virtual
Get the number of dimensions of register pressure.
Referenced by llvm::RegPressureTracker::init(), llvm::RegPressureTracker::initLiveThru(), and llvm::RegisterClassInfo::runOnMachineFunction().
getPointerRegClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline virtual
Returns a TargetRegisterClass used for pointer values.
If a target supports multiple different pointer register classes, kind specifies which one is indicated.
Definition at line 724 of file TargetRegisterInfo.h.
References llvm_unreachable.
getRegAllocationHints()
bool TargetRegisterInfo::getRegAllocationHints (unsigned VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const MachineFunction & MF, const VirtRegMap * VRM = nullptr, const LiveRegMatrix * Matrix = nullptr) const virtual
Get a list of 'hint' registers that the register allocator should try first when allocating a physical register for the virtual register VirtReg.
These registers are effectively moved to the front of the allocation order. If true is returned, regalloc will try to only use hints to the greatest extent possible even if it means spilling.
The Order argument is the allocation order for VirtReg's register class as returned from RegisterClassInfo::getOrder(). The hint registers must come from Order, and they must not be reserved.
The default implementation of this function will only add target independent register allocation hints. Targets that override this function should typically call this default implementation as well and expect to see generic copy hints added.
Definition at line 391 of file TargetRegisterInfo.cpp.
References llvm::VirtRegMap::getPhys(), llvm::MachineFunction::getRegInfo(), llvm::SmallSet< T, N, C >::insert(), llvm::is_contained(), isPhysicalRegister(), isVirtualRegister(), MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::ARMBaseRegisterInfo::getRegAllocationHints(), and llvm::SystemZRegisterInfo::getRegAllocationHints().
getRegAsmName()
virtual StringRef llvm::TargetRegisterInfo::getRegAsmName (unsigned Reg) const inline virtual
Return the assembly name for Reg.
Definition at line 965 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getName(), and Reg.
Referenced by llvm::TargetLowering::getRegForInlineAsmConstraint().
getRegClass()
const TargetRegisterClass * llvm::TargetRegisterInfo::getRegClass (unsigned i) const inline
Returns the register class associated with the enumeration value.
See class MCOperandInfo.
Definition at line 700 of file TargetRegisterInfo.h.
References assert(), and getNumRegClasses().
Referenced by getAllocatableClass().
getRegClassInfo()
const RegClassInfo & llvm::TargetRegisterInfo::getRegClassInfo (const TargetRegisterClass & RC) const inline protected
Definition at line 682 of file TargetRegisterInfo.h.
References llvm::TargetRegisterClass::getID(), and getNumRegClasses().
Referenced by getRegSizeInBits(), getSpillAlignment(), getSpillSize(), and legalclasstypes_begin().
getRegClassName()
const char * llvm::TargetRegisterInfo::getRegClassName (const TargetRegisterClass * Class) const inline
Returns the name of the register class.
Definition at line 706 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getRegClassName().
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::HexagonEvaluator::mask(), llvm::LiveStacks::print(), llvm::VirtRegMap::print(), and llvm::ExecutionDomainFix::runOnMachineFunction().
getRegClassPressureSets()
virtual const int * llvm::TargetRegisterInfo::getRegClassPressureSets (const TargetRegisterClass * RC) const pure virtual
Get the dimensions of register pressure impacted by this register class.
Returns a -1 terminated array of pressure set IDs.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegClassWeight()
virtual const RegClassWeight & llvm::TargetRegisterInfo::getRegClassWeight (const TargetRegisterClass * RC) const pure virtual
Get the weight in units of pressure for this register class.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegMaskNames()
virtual ArrayRef< const char * > llvm::TargetRegisterInfo::getRegMaskNames () const pure virtual
getRegMasks()
virtual ArrayRef< const uint32_t * > llvm::TargetRegisterInfo::getRegMasks () const pure virtual
Return all the call-preserved register masks defined for this target.
Referenced by llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo().
getRegPressureLimit()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const inline virtual
Return the register pressure "high water mark" for the specific register class.
The scheduler is in high register pressure mode (for the specific register class) if it goes over the limit.
Note: this is the old register pressure model that relies on a manually specified representative register class per value type.
Definition at line 755 of file TargetRegisterInfo.h.
Referenced by llvm::SIRegisterInfo::getRegPressureLimit(), and llvm::ResourcePriorityQueue::ResourcePriorityQueue().
getRegPressureSetLimit()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureSetLimit (const MachineFunction & MF, unsigned Idx) const pure virtual
Get the register unit pressure limit for this dimension.
This limit must be adjusted dynamically for reserved registers.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegPressureSetName()
virtual const char * llvm::TargetRegisterInfo::getRegPressureSetName (unsigned Idx) const pure virtual
Get the name of this register unit pressure set.
Referenced by llvm::GenericScheduler::initCandidate(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::ConvergingVLIWScheduler::traceCandidate(), llvm::GenericSchedulerBase::traceCandidate(), and llvm::ScheduleDAGMILive::updateScheduledPressure().
getRegPressureSetScore()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureSetScore (const MachineFunction & MF, unsigned PSetID) const inline virtual
Return a heuristic for the machine scheduler to compare the profitability of increasing one register pressure set versus another.
The scheduler will prefer increasing the register pressure of the set which returns the largest value for this function.
Definition at line 764 of file TargetRegisterInfo.h.
getRegSizeInBits() [1/2]
unsigned llvm::TargetRegisterInfo::getRegSizeInBits (const TargetRegisterClass & RC) const inline
Return the size in bits of a register from class RC.
Definition at line 313 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::RegSize.
Referenced by getCommonSuperRegClass(), llvm::BitTracker::MachineEvaluator::getPhysRegBitWidth(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), and getRegSizeInBits().
getRegSizeInBits() [2/2]
unsigned TargetRegisterInfo::getRegSizeInBits (unsigned Reg, const MachineRegisterInfo & MRI) const
Returns size in bits of a phys/virtual/generic register.
Definition at line 466 of file TargetRegisterInfo.cpp.
References assert(), getMinimalPhysRegClass(), getRegSizeInBits(), llvm::LLT::getSizeInBits(), isPhysicalRegister(), llvm::LLT::isValid(), and MRI.
getRegUnitPressureSets()
virtual const int * llvm::TargetRegisterInfo::getRegUnitPressureSets (unsigned RegUnit) const pure virtual
Get the dimensions of register pressure impacted by this register unit.
Returns a -1 terminated array of pressure set IDs.
Referenced by llvm::SIRegisterInfo::getRegUnitPressureSets().
getRegUnitWeight()
virtual unsigned llvm::TargetRegisterInfo::getRegUnitWeight (unsigned RegUnit) const pure virtual
Get the weight in units of pressure for this register unit.
getReservedRegs()
virtual BitVector llvm::TargetRegisterInfo::getReservedRegs (const MachineFunction & MF) const pure virtual
Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
stack pointer, return address. A reserved register:
is not allocatable
is considered always live
is ignored by liveness tracking It is often necessary to reserve the super registers of a reserved register as well, to avoid them getting allocated indirectly. You may use markSuperRegs() and checkAllSuperRegsMarked() in this case.
Referenced by llvm::MachineRegisterInfo::freezeReservedRegs(), and getAllocatableSet().
getSpillAlignment()
unsigned llvm::TargetRegisterInfo::getSpillAlignment (const TargetRegisterClass & RC) const inline
Return the minimum required alignment in bytes for a spill slot for a register of this class.
Definition at line 325 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::SpillAlignment.
Referenced by assignCalleeSavedSpillSlots(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
getSpillSize()
unsigned llvm::TargetRegisterInfo::getSpillSize (const TargetRegisterClass & RC) const inline
Return the size in bytes of the stack slot allocated to hold a spilled copy of a register from class RC.
Definition at line 319 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::SpillSize.
Referenced by assignCalleeSavedSpillSlots(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
getSubClassWithSubReg()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getSubClassWithSubReg (const TargetRegisterClass * RC, unsigned Idx) const inline virtual
Returns the largest legal sub-class of RC that supports the sub-register index Idx.
If no such sub-class exists, return NULL. If all registers in RC already have an Idx sub-register, return RC.
TableGen generates a version of this function that is good enough in most cases. Targets can override if they have constraints that TableGen doesn't understand. For example, the x86 sub_8bit sub-register index is supported by the full GR32 register class in 64-bit mode, but only by the GR32_ABCD regiister class in 32-bit mode.
TableGen will synthesize missing RC sub-classes.
Definition at line 581 of file TargetRegisterInfo.h.
References assert(), and Idx.
Referenced by llvm::FastISel::fastEmitInst_extractsubreg().
getSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::getSubRegIndexLaneMask (unsigned SubIdx) const inline
Return a bitmask representing the parts of a register that are covered by SubIdx.
See also
LaneBitmask.
SubIdx == 0 is allowed, it has the lane mask ~0u.
Definition at line 390 of file TargetRegisterInfo.h.
References assert(), and llvm::MCRegisterInfo::getNumSubRegIndices().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::ScheduleDAGInstrs::getLaneMaskForMO(), llvm::rdf::Liveness::resetKills(), and llvm::LiveIntervals::shrinkToUses().
getSubRegIndexName()
const char * llvm::TargetRegisterInfo::getSubRegIndexName (unsigned SubIdx) const inline
Return the human-readable symbolic target-specific name for the specified SubRegIndex.
Definition at line 380 of file TargetRegisterInfo.h.
References assert(), and llvm::MCRegisterInfo::getNumSubRegIndices().
hasRegUnit()
bool llvm::TargetRegisterInfo::hasRegUnit (unsigned Reg, unsigned RegUnit) const inline
Returns true if Reg contains RegUnit.
Definition at line 439 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), and Reg.
hasReservedSpillSlot()
virtual bool llvm::TargetRegisterInfo::hasReservedSpillSlot (const MachineFunction & MF, unsigned Reg, int & FrameIdx) const inline virtual
Return true if target has reserved a spill slot in the stack frame of the given function for the specified register.
e.g. On x86, if the frame register is required, the first fixed stack object is reserved as its spill slot. This tells PEI not to create a new stack frame object for the given register. It should be called only after determineCalleeSaves().
Definition at line 884 of file TargetRegisterInfo.h.
Referenced by assignCalleeSavedSpillSlots().
index2StackSlot()
static unsigned llvm::TargetRegisterInfo::index2StackSlot (int FI) inline static
Convert a non-negative frame index to a stack slot register value.
Definition at line 280 of file TargetRegisterInfo.h.
References assert().
Referenced by llvm::LiveStacks::getOrCreateInterval(), and llvm::rdf::PhysicalRegisterInfo::getRegMaskId().
index2VirtReg()
static unsigned llvm::TargetRegisterInfo::index2VirtReg (unsigned Index) inline static
Convert a 0-based index to a virtual register number.
This is the inverse operation of VirtReg2IndexFunctor below.
Definition at line 308 of file TargetRegisterInfo.h.
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveVariables::addNewBlock(), llvm::calculateSpillWeightsAndHints(), llvm::MachineRegisterInfo::clearVirtRegs(), llvm::MIRPrinter::convert(), llvm::MachineRegisterInfo::createIncompleteVirtualRegister(), llvm::getLiveRegMap(), llvm::getLiveRegs(), isSSA(), llvm::LiveIntervals::print(), llvm::VirtRegMap::print(), llvm::GCNRPTracker::printLiveRegs(), llvm::printLivesAt(), llvm::LiveIntervals::releaseMemory(), llvm::InstructionSelect::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), and llvm::MachineRegisterInfo::verifyUseLists().
isAsmClobberable()
virtual bool llvm::TargetRegisterInfo::isAsmClobberable (const MachineFunction & MF, unsigned PhysReg) const inline virtual
Returns false if we can't guarantee that Physreg, specified as an IR asm clobber constraint, will be preserved across the statement.
Definition at line 514 of file TargetRegisterInfo.h.
isCallerPreservedPhysReg()
virtual bool llvm::TargetRegisterInfo::isCallerPreservedPhysReg (unsigned PhysReg, const MachineFunction & MF) const inline virtual
Physical registers that may be modified within a function but are guaranteed to be restored before any uses.
This is useful for targets that have call sequences where a GOT register may be updated by the caller prior to a call and is guaranteed to be restored (also by the caller) after the call.
Definition at line 533 of file TargetRegisterInfo.h.
isConstantPhysReg()
virtual bool llvm::TargetRegisterInfo::isConstantPhysReg (unsigned PhysReg) const inline virtual
Returns true if PhysReg is unallocatable and constant throughout the function.
Used by MachineRegisterInfo::isConstantPhysReg().
Definition at line 521 of file TargetRegisterInfo.h.
isDivergentRegClass()
virtual bool llvm::TargetRegisterInfo::isDivergentRegClass (const TargetRegisterClass * RC) const inline virtual
Returns true if the register class is considered divergent.
Definition at line 524 of file TargetRegisterInfo.h.
isFrameOffsetLegal()
virtual bool llvm::TargetRegisterInfo::isFrameOffsetLegal (const MachineInstr * MI, unsigned BaseReg, int64_t Offset) const inline virtual
Determine whether a given base register plus offset immediate is encodable to resolve a frame index.
Definition at line 936 of file TargetRegisterInfo.h.
References llvm_unreachable.
isInAllocatableClass()
bool llvm::TargetRegisterInfo::isInAllocatableClass (unsigned RegNo) const inline
Return true if the register is in the allocation of any register class.
Definition at line 374 of file TargetRegisterInfo.h.
References llvm::TargetRegisterInfoDesc::inAllocatableClass.
Referenced by llvm::MachineRegisterInfo::isAllocatable().
isPhysicalRegister()
static bool llvm::TargetRegisterInfo::isPhysicalRegister (unsigned Reg) inline static
Return true if the specified register number is in the physical register namespace.
Definition at line 287 of file TargetRegisterInfo.h.
References assert(), isStackSlot(), and Reg.
Referenced by llvm::LiveRegUnits::accumulate(), llvm::LiveRegUnits::accumulateUsedDefed(), addDefsUsesToList(), llvm::ARMBaseInstrInfo::AddDReg(), llvm::MachineBasicBlock::addLiveIn(), addRegAndItsAliases(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterDefined(), llvm::MachineInstr::addRegisterKilled(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), AddSubReg(), addToListsIfDependent(), llvm::LivePhysRegs::addUses(), llvm::MachineOperandIteratorBase::analyzePhysReg(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::VirtRegMap::assignVirt2Phys(), llvm::biasPhysReg(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::ScheduleDAGInstrs::buildSchedGraph(), canCompareBeNewValueJump(), canFoldCopy(), canFoldIntoSelect(), llvm::X86InstrInfo::classifyLEAReg(), llvm::MachineInstr::clearRegisterKills(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), countOperands(), definesFullReg(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), llvm::HexagonBlockRanges::expandToSubRegs(), llvm::finalizeBundle(), findHoistingInsertPosAndDeps(), findOnlyInterestingUse(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::CoalescerPair::flip(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), llvm::RegScavenger::forward(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::getConstantVRegValWithLookThrough(), getDataDeps(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::RegisterClassInfo::getLastCalleeSavedAlias(), getMappedReg(), llvm::RegisterBankInfo::getMinimalPhysRegClass(), getMinimalPhysRegClass(), getMopState(), llvm::BitTracker::MachineEvaluator::getPhysRegBitWidth(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), getRegAllocationHints(), llvm::RegisterBankInfo::getRegBank(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), getRegClassFromGRPhysReg(), getRegisterName(), getRegSizeInBits(), llvm::RegisterBankInfo::getSizeInBits(), getSubRegForIndex(), llvm::X86InstrInfo::getUndefRegClearance(), llvm::VirtRegMap::hasKnownPreference(), INITIALIZE_PASS(), instAccessReg(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::CoalescerPair::isCoalescable(), llvm::MachineRegisterInfo::isConstantPhysReg(), isCopyToReg(), llvm::HexagonInstrInfo::isDependent(), isEvenReg(), isIdenticalOp(), isImplicitlyDef(), isKilled(), isLocalCopy(), llvm::MachineOperand::isRenamable(), isSafeToMove(), isSCC(), isSubRegOf(), llvm::isTriviallyDead(), isValidCopy(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::rdf::DataFlowGraph::makeRegRef(), MIIsInTerminatorSequence(), llvm::SIInstrInfo::moveToVALU(), llvm::MachineOperand::print(), llvm::ARMAsmPrinter::printOperand(), llvm::recomputeLivenessFlags(), llvm::LivePhysRegs::removeDefs(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::GenericScheduler::reschedulePhysReg(), llvm::rdf::Liveness::resetKills(), llvm::SelectionDAGISel::runOnMachineFunction(), selectCopy(), selectSubregisterCopy(), llvm::MachineOperand::setIsRenamable(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::CoalescerPair::setRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::LiveRegUnits::stepBackward(), llvm::LivePhysRegs::stepForward(), storeRegPairToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::MachineInstr::substituteRegister(), llvm::MachineOperand::substPhysReg(), UpdateOperandRegClass(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), llvm::SIInstrInfo::verifyInstruction(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isStackSlot()
static bool llvm::TargetRegisterInfo::isStackSlot (unsigned Reg) inline static
isStackSlot - Sometimes it is useful the be able to store a non-negative frame index in a variable that normally holds a register.
isStackSlot() returns true if Reg is in the range used for stack slots.
Note that isVirtualRegister() and isPhysicalRegister() cannot handle stack slots, so if a variable may contains a stack slot, always check isStackSlot() first.
Definition at line 269 of file TargetRegisterInfo.h.
References Reg.
Referenced by isPhysicalRegister(), llvm::rdf::PhysicalRegisterInfo::isRegMaskId(), isVirtualRegister(), llvm::printReg(), and stackSlot2Index().
isTypeLegalForClass()
bool llvm::TargetRegisterInfo::isTypeLegalForClass (const TargetRegisterClass & RC, MVT T) const inline
Return true if the given TargetRegisterClass has the ValueType T.
Definition at line 330 of file TargetRegisterInfo.h.
References I, legalclasstypes_begin(), and llvm::MVT::Other.
Referenced by getMinimalPhysRegClass(), and llvm::TargetLowering::getRegForInlineAsmConstraint().
isVirtualRegister()
static bool llvm::TargetRegisterInfo::isVirtualRegister (unsigned Reg) inline static
Return true if the specified register number is in the virtual register namespace.
Definition at line 294 of file TargetRegisterInfo.h.
References assert(), isStackSlot(), and Reg.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::LiveVariables::addNewBlock(), llvm::MachineRegisterInfo::addRegAllocationHint(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::RegisterOperands::adjustLaneLiveness(), llvm::GCNDownwardRPTracker::advanceToNext(), llvm::RegAllocBase::allocatePhysRegs(), llvm::VirtRegMap::assignVirt2Phys(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::ScheduleDAGInstrs::buildSchedGraph(), canCombine(), canFoldCopy(), canFoldIntoCSel(), canFoldIntoSelect(), CheckForPhysRegDependency(), llvm::X86InstrInfo::classifyLEAReg(), llvm::VirtRegMap::clearVirt(), collectVirtualRegUses(), llvm::ScheduleDAGMILive::collectVRegUses(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::HexagonBlockRanges::computeDeadMap(), computeLiveOuts(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::LiveInterval::computeSubRangeUndefs(), llvm::constrainOperandRegClass(), llvm::FastISel::constrainOperandRegClass(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), copyHint(), llvm::WebAssemblyInstrInfo::copyPhysReg(), doCandidateWalk(), dominatesAllUsesOf(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::HexagonBlockRanges::expandToSubRegs(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::SIScheduleDAGMI::fillVgprSgprCost(), llvm::SIRegisterInfo::findReachingDef(), findSinkableLocalRegDef(), findSRegBaseAndIndex(), findSurvivorBackwards(), foldImmediates(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), genFusedMultiply(), genMaddR(), getCallTargetRegOpnd(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::RegsForValue::getCopyFromRegs(), getCopyRegClasses(), getDefRegMask(), llvm::MachineInstrExpressionTrait::getHashValue(), getImmOrMaterializedImm(), llvm::R600InstrInfo::getIndirectIndexBegin(), getLanesWithProperty(), getLiveRange(), getMappedReg(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::PPCInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::X86InstrInfo::getPartialRegUpdateClearance(), llvm::SIRegisterInfo::getPhysRegClass(), llvm::MachineRegisterInfo::getRegAllocationHint(), getRegAllocationHints(), llvm::MachineRegisterInfo::getRegAllocationHints(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::SIRegisterInfo::getRegClassForReg(), llvm::MachineRegisterInfo::getSimpleHint(), llvm::VirtRegMap::getStackSlot(), llvm::MachineRegisterInfo::getType(), getUsedRegMask(), llvm::LiveVariables::getVarInfo(), GetVRegRenameMap(), llvm::getVRegSubRegDef(), llvm::VirtRegMap::hasKnownPreference(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), llvm::VirtRegMap::hasPreferredPhys(), llvm::TargetInstrInfo::hasReassociableOperands(), hasVectorOperands(), INITIALIZE_PASS(), llvm::RegPressureTracker::initLiveThru(), instAccessReg(), llvm::WebAssembly::isChild(), isCopyFeedingInvariantStore(), isCVTAToLocalCombinationCandidate(), isFPR64(), llvm::MachineInstr::isIdenticalTo(), isInvariantStore(), llvm::SIInstrInfo::isLegalRegOperand(), llvm::R600InstrInfo::isLegalToSplitMBBAt(), isPhysicalRegCopy(), llvm::R600RegisterInfo::isPhysRegLiveAcrossClauses(), isPlainlyKilled(), isRematerializable(), llvm::SIRegisterInfo::isSGPRReg(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isVirtualRegisterOperand(), llvm::SIInstrInfo::legalizeOperands(), llvm::Mips16InstrInfo::loadImmediate(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), lookThruCopyLike(), MatchingStackOffset(), llvm::BitTracker::RegisterCell::meet(), llvm::SIInstrInfo::moveToVALU(), needsStackFrame(), oneUseDominatesOtherUses(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), optimizeVcndVcmpPair(), llvm::SMSchedule::orderDependence(), populateCandidates(), llvm::MachineOperand::print(), llvm::printReg(), llvm::ARMBaseInstrInfo::produceSameValue(), propagateLocalCopies(), llvm::PSetIterator::PSetIterator(), llvm::BitTracker::MachineEvaluator::putCell(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::TargetInstrInfo::reassociateOps(), llvm::GCNUpwardRPTracker::recede(), llvm::RegPressureTracker::recede(), regIsPICBase(), regsOverlap(), llvm::WebAssemblyAsmPrinter::regToString(), removeCopies(), llvm::LiveVariables::removeVirtualRegistersKilled(), llvm::LiveIntervals::repairIntervalsInRange(), rescheduleCanonically(), runOnBasicBlock(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), scavengeFrameVirtualRegsInBlock(), llvm::RegScavenger::scavengeRegister(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::MachineRegisterInfo::setRegAllocationHint(), llvm::CoalescerPair::setRegisters(), llvm::SIInstrInfo::shouldClusterMemOps(), llvm::MachineRegisterInfo::shouldTrackSubRegLiveness(), shrinkScalarLogicOp(), llvm::LiveIntervals::shrinkToUses(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), stripValuesNotDefiningMask(), llvm::MachineOperand::substVirtReg(), tryChangeVGPRtoSGPRinCopy(), tryToFoldACImm(), unsupportedBinOp(), llvm::LiveIntervals::HMEditor::updateAllRanges(), llvm::ScheduleDAGMILive::updatePressureDiffs(), llvm::ARMBaseRegisterInfo::updateRegAllocHint(), llvm::SIInstrInfo::usesConstantBus(), llvm::SIInstrInfo::verifyInstruction(), virtReg2Index(), and llvm::VirtRegAuxInfo::weightCalcHelper().
legalclasstypes_begin()
vt_iterator llvm::TargetRegisterInfo::legalclasstypes_begin (const TargetRegisterClass & RC) const inline
Loop over all of the value types that can be represented by values in the given register class.
Definition at line 339 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::VTList.
Referenced by isTypeLegalForClass(), and legalclasstypes_end().
legalclasstypes_end()
vt_iterator llvm::TargetRegisterInfo::legalclasstypes_end (const TargetRegisterClass & RC) const inline
Definition at line 343 of file TargetRegisterInfo.h.
References I, legalclasstypes_begin(), and llvm::MVT::Other.
lookThruCopyLike()
unsigned TargetRegisterInfo::lookThruCopyLike (unsigned SrcReg, const MachineRegisterInfo * MRI) const virtual
Returns the original SrcReg unless it is the target of a copy-like operation, in which case we chain backwards through all such operations to the ultimate source register.
If a physical register is encountered, we stop the search.
Definition at line 489 of file TargetRegisterInfo.cpp.
References assert(), isVirtualRegister(), MI, and MRI.
markSuperRegs()
void TargetRegisterInfo::markSuperRegs (BitVector & RegisterSet, unsigned Reg) const
Mark a register and all its aliases as reserved in the given set.
Definition at line 58 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
materializeFrameBaseRegister()
virtual void llvm::TargetRegisterInfo::materializeFrameBaseRegister (MachineBasicBlock * MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const inline virtual
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx before insertion point I.
Definition at line 920 of file TargetRegisterInfo.h.
References llvm_unreachable.
needsFrameBaseReg()
virtual bool llvm::TargetRegisterInfo::needsFrameBaseReg (MachineInstr * MI, int64_t Offset) const inline virtual
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
Used by LocalStackFrameAllocation to determine which frame index references it should create new base registers for.
Definition at line 914 of file TargetRegisterInfo.h.
needsStackRealignment()
bool TargetRegisterInfo::needsStackRealignment (const MachineFunction & MF) const
True if storage within the function requires the stack pointer to be aligned more than the normal calling convention calls for.
This cannot be overriden by the target, but canRealignStack can be overridden.
Definition at line 440 of file TargetRegisterInfo.cpp.
References canRealignStack(), llvm::dbgs(), F, llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), and LLVM_DEBUG.
Referenced by llvm::MachineFrameInfo::estimateStackSize(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), and llvm::SparcFrameLowering::hasFP().
regclass_begin()
regclass_iterator llvm::TargetRegisterInfo::regclass_begin () const inline
Register class iterators.
Definition at line 688 of file TargetRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclass_end()
regclass_iterator llvm::TargetRegisterInfo::regclass_end () const inline
Definition at line 689 of file TargetRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclasses()
iterator_range< regclass_iterator > llvm::TargetRegisterInfo::regclasses () const inline
Definition at line 690 of file TargetRegisterInfo.h.
References llvm::make_range(), regclass_begin(), and regclass_end().
Referenced by llvm::RegisterClassInfo::computePSetLimit(), getAllocatableSet(), getMinimalPhysRegClass(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::HexagonBlockRanges::HexagonBlockRanges(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::ResourcePriorityQueue::regPressureDelta(), and llvm::ResourcePriorityQueue::ResourcePriorityQueue().
regmaskSubsetEqual()
bool TargetRegisterInfo::regmaskSubsetEqual (const uint32_t * mask0, const uint32_t * mask1) const
Return true if all bits that are set in mask mask0 are also set in mask1.
Definition at line 457 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::getNumRegs(), I, and N.
regsOverlap()
bool llvm::TargetRegisterInfo::regsOverlap (unsigned regA, unsigned regB) const inline
Returns true if the two registers are equal or alias each other.
The registers may be virtual registers.
Definition at line 422 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), and isVirtualRegister().
Referenced by llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), and llvm::MachineInstr::clearRegisterKills().
requiresFrameIndexReplacementScavenging()
virtual bool llvm::TargetRegisterInfo::requiresFrameIndexReplacementScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires using the RegScavenger directly for frame elimination despite using requiresFrameIndexScavenging.
Definition at line 867 of file TargetRegisterInfo.h.
requiresFrameIndexScavenging()
virtual bool llvm::TargetRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires post PEI scavenging of registers for materializing frame index constants.
Definition at line 861 of file TargetRegisterInfo.h.
requiresRegisterScavenging()
virtual bool llvm::TargetRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires (and can make use of) the register scavenger.
Definition at line 849 of file TargetRegisterInfo.h.
requiresVirtualBaseRegisters()
virtual bool llvm::TargetRegisterInfo::requiresVirtualBaseRegisters (const MachineFunction & MF) const inline virtual
Returns true if the target wants the LocalStackAllocation pass to be run and virtual base registers used for more efficient stack access.
Definition at line 874 of file TargetRegisterInfo.h.
resolveFrameIndex()
virtual void llvm::TargetRegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const inline virtual
Resolve a frame index operand of an instruction to reference the indicated base register plus offset instead.
Definition at line 929 of file TargetRegisterInfo.h.
References llvm_unreachable.
reverseComposeSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask LaneMask) const inline
Transform a lanemask given for a virtual register to the corresponding lanemask before using subregister with index IdxA.
This is the reverse of composeSubRegIndexLaneMask(), assuming Mask is a valie lane mask (no invalid bits set) the following holds: X0 = composeSubRegIndexLaneMask(Idx, Mask) X1 = reverseComposeSubRegIndexLaneMask(Idx, X0) => X1 == Mask
Definition at line 622 of file TargetRegisterInfo.h.
References reverseComposeSubRegIndexLaneMaskImpl().
Referenced by llvm::rdf::PhysicalRegisterInfo::mapTo().
reverseComposeSubRegIndexLaneMaskImpl()
virtual LaneBitmask llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMaskImpl (unsigned , LaneBitmask) const inline protected virtual
Definition at line 645 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by reverseComposeSubRegIndexLaneMask().
reverseLocalAssignment()
virtual bool llvm::TargetRegisterInfo::reverseLocalAssignment () const inline virtual
Allow the target to reverse allocation order of local live ranges.
This will generally allocate shorter local live ranges first. For targets with many registers, this could reduce regalloc compile time by a large factor. It is disabled by default for three reasons: (1) Top-down allocation is simpler and easier to debug for targets that don't benefit from reversing the order. (2) Bottom-up allocation could result in poor evicition decisions on some targets affecting the performance of compiled code. (3) Bottom-up allocation is no longer guaranteed to optimally color.
Definition at line 840 of file TargetRegisterInfo.h.
saveScavengerRegister()
virtual bool llvm::TargetRegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, unsigned Reg) const inline virtual
Spill the register so it can be used by the register scavenger.
Return true if the register was spilled, false otherwise. If this function does not spill the register, the scavenger will instead spill it to the emergency spill slot.
Definition at line 945 of file TargetRegisterInfo.h.
shouldCoalesce()
virtual bool llvm::TargetRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const inline virtual
Subtarget Hooks.
SrcRC and DstRC will be morphed into NewRC if this returns true.
Definition at line 979 of file TargetRegisterInfo.h.
Referenced by llvm::AVRRegisterInfo::shouldCoalesce().
shouldRewriteCopySrc()
bool TargetRegisterInfo::shouldRewriteCopySrc (const TargetRegisterClass * DefRC, unsigned DefSubReg, const TargetRegisterClass * SrcRC, unsigned SrcSubReg) const virtual
Definition at line 381 of file TargetRegisterInfo.cpp.
References shareSameRegisterFile().
Referenced by llvm::X86RegisterInfo::shouldRewriteCopySrc().
stackSlot2Index()
static int llvm::TargetRegisterInfo::stackSlot2Index (unsigned Reg) inline static
Compute the frame index from a register value representing a stack slot.
Definition at line 274 of file TargetRegisterInfo.h.
References assert(), isStackSlot(), and Reg.
Referenced by llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getRegMaskBits(), and llvm::printReg().
trackLivenessAfterRegAlloc()
virtual bool llvm::TargetRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline virtual
Returns true if the live-ins should be tracked after register allocation.
Definition at line 890 of file TargetRegisterInfo.h.
Referenced by llvm::BranchFolder::OptimizeFunction().
updateRegAllocHint()
virtual void llvm::TargetRegisterInfo::updateRegAllocHint (unsigned Reg, unsigned NewReg, MachineFunction & MF) const inline virtual
A callback to allow target a chance to update register allocation hints when a register is "changed" (e.g.
coalesced) to another register. e.g. On ARM, some virtual registers should target register pairs, if one of pair is coalesced to another register, the allocation hint of the other half of the pair should be changed to point to the new register.
Definition at line 826 of file TargetRegisterInfo.h.
useFPForScavengingIndex()
virtual bool llvm::TargetRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const inline virtual
Returns true if the target wants to use frame pointer based accesses to spill to the scavenger emergency spill slot.
Definition at line 855 of file TargetRegisterInfo.h.
virtReg2Index()
static unsigned llvm::TargetRegisterInfo::virtReg2Index (unsigned Reg) inline static
Convert a virtual register number to a 0-based index.
The first virtual register in a function will get the index 0.
Definition at line 301 of file TargetRegisterInfo.h.
References assert(), isVirtualRegister(), and Reg.
Referenced by llvm::VReg2SUnit::getSparseSetIndex(), llvm::WebAssemblyFunctionInfo::getWAReg(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), llvm::VirtReg2IndexFunctor::operator()(), llvm::printReg(), llvm::SelectionDAGISel::runOnMachineFunction(), scavengeFrameVirtualRegsInBlock(), llvm::WebAssemblyFunctionInfo::setWAReg(), and llvm::WebAssemblyFunctionInfo::stackifyVReg().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetRegisterInfo.h
lib/CodeGen/TargetRegisterInfo.cpp