LLVM: llvm::AArch64InstrInfo Class Reference
llvm::AArch64InstrInfo Class Reference final
#include "Target/AArch64/AArch64InstrInfo.h"
Public Member Functions
AArch64InstrInfo (const AArch64Subtarget &STI)
const AArch64RegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
bool isAsCheapAsAMove (const MachineInstr &MI) const override
bool isCoalescableExtInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DstReg, unsigned &SubIdx) const override
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb, AliasAnalysis *AA=nullptr) const override
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
bool isCandidateToMergeOrPair (const MachineInstr &MI) const
Return true if this is a load/store that can be potentially paired/merged.
bool getMemOperandWithOffset (const MachineInstr &MI, const MachineOperand *&BaseOp, int64_t &Offset, const TargetRegisterInfo *TRI) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &MI, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
MachineOperand & getMemOpBaseRegImmOfsOffsetOperand (MachineInstr &LdSt) const
Return the immediate offset of the base register in a load/store LdSt.
bool shouldClusterMemOps (const MachineOperand &BaseOp1, const MachineOperand &BaseOp2, unsigned NumLoads) const override
Detect opportunities for ldp/stp formation.
void copyPhysRegTuple (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, llvm::ArrayRef< unsigned > Indices) const
void copyGPRRegTuple (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, unsigned ZeroReg, llvm::ArrayRef< unsigned > Indices) const
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
bool isSubregFoldable () const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals *LIS=nullptr, VirtRegMap *VRM=nullptr) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool canInsertSelect (const MachineBasicBlock &, ArrayRef< MachineOperand > Cond, unsigned, unsigned, int &, int &, int &) const override
void insertSelect (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const override
void getNoop (MCInst &NopInst) const override
bool isSchedulingBoundary (const MachineInstr &MI, const MachineBasicBlock *MBB, const MachineFunction &MF) const override
bool analyzeCompare (const MachineInstr &MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const override
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2, and the value it compares against in CmpValue.
bool optimizeCompareInstr (MachineInstr &CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const override
optimizeCompareInstr - Convert the instruction supplying the argument to the comparison into one that sets the zero bit in the flags register.
bool optimizeCondBranch (MachineInstr &MI) const override
Replace csincr-branch sequence by simple conditional branch.
bool isThroughputPattern (MachineCombinerPattern Pattern) const override
Return true when a code sequence can improve throughput.
bool getMachineCombinerPatterns (MachineInstr &Root, SmallVectorImpl< MachineCombinerPattern > &Patterns) const override
Return true when there is potentially a faster code sequence for an instruction chain ending in Root.
bool isAssociativeAndCommutative (const MachineInstr &Inst) const override
Return true when Inst is associative and commutative so that it can be reassociated.
void genAlternativeCodeSequence (MachineInstr &Root, MachineCombinerPattern Pattern, SmallVectorImpl< MachineInstr * > &InsInstrs, SmallVectorImpl< MachineInstr * > &DelInstrs, DenseMap< unsigned, unsigned > &InstrIdxForVirtReg) const override
When getMachineCombinerPatterns() finds patterns, this function generates the instructions that could replace the original code sequence.
bool useMachineCombiner () const override
AArch64 supports MachineCombiner.
bool expandPostRAPseudo (MachineInstr &MI) const override
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableBitmaskMachineOperandTargetFlags () const override
ArrayRef< std::pair< MachineMemOperand::Flags, const char * > > getSerializableMachineMemOperandTargetFlags () const override
bool isFunctionSafeToOutlineFrom (MachineFunction &MF, bool OutlineFromLinkOnceODRs) const override
outliner::OutlinedFunction getOutliningCandidateInfo (std::vector< outliner::Candidate > &RepeatedSequenceLocs) const override
outliner::InstrType getOutliningType (MachineBasicBlock::iterator &MIT, unsigned Flags) const override
bool isMBBSafeToOutlineFrom (MachineBasicBlock &MBB, unsigned &Flags) const override
void buildOutlinedFrame (MachineBasicBlock &MBB, MachineFunction &MF, const outliner::OutlinedFunction &OF) const override
MachineBasicBlock::iterator insertOutlinedCall (Module &M, MachineBasicBlock &MBB, MachineBasicBlock::iterator &It, MachineFunction &MF, const outliner::Candidate &C) const override
bool shouldOutlineFromFunctionByDefault (MachineFunction &MF) const override
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals *LIS=nullptr, VirtRegMap *VRM=nullptr) const
Target-dependent implementation for foldMemoryOperand.
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, MachineInstr &LoadMI, LiveIntervals *LIS=nullptr) const
Target-dependent implementation for foldMemoryOperand.
Static Public Member Functions
static bool isGPRZero (const MachineInstr &MI)
Does this instruction set its full destination register to zero?
static bool isGPRCopy (const MachineInstr &MI)
Does this instruction rename a GPR without modifying bits?
static bool isFPRCopy (const MachineInstr &MI)
Does this instruction rename an FPR without modifying bits?
static bool isLdStPairSuppressed (const MachineInstr &MI)
Return true if pairing the given load or store is hinted to be unprofitable.
static bool isStridedAccess (const MachineInstr &MI)
Return true if the given load or store is a strided memory access.
static bool isUnscaledLdSt (unsigned Opc)
Return true if this is an unscaled load/store.
static bool isUnscaledLdSt (MachineInstr &MI)
static Optional< unsigned > getUnscaledLdSt (unsigned Opc)
Returns the unscaled load/store for the scaled load/store opcode, if there is a corresponding unscaled variant available.
static unsigned getLoadStoreImmIdx (unsigned Opc)
Returns the index for the immediate for a given instruction.
static bool isPairableLdStInst (const MachineInstr &MI)
Return true if pairing the given load or store may be paired with another.
static unsigned convertToFlagSettingOpc (unsigned Opc, bool &Is64Bit)
Return the opcode that set flags when possible.
static void suppressLdStPair (MachineInstr &MI)
Hint that pairing the given load or store is unprofitable.
static bool getMemOpInfo (unsigned Opcode, unsigned &Scale, unsigned &Width, int64_t &MinOffset, int64_t &MaxOffset)
Returns true if opcode Opc is a memory operation.
static bool isFalkorShiftExtFast (const MachineInstr &MI)
Returns true if the instruction has a shift by immediate that can be executed in one cycle less.
static bool isSEHInstruction (const MachineInstr &MI)
Return true if the instructions is a SEH instruciton used for unwinding on Windows.
Protected Member Functions
bool isCopyInstrImpl (const MachineInstr &MI, const MachineOperand *&Source, const MachineOperand *&Destination) const override
If the specific machine instruction is a instruction that moves/copies value from one register to another register return true along with @Source machine operand and @Destination machine operand.
Detailed Description
Definition at line 37 of file AArch64InstrInfo.h.
Constructor & Destructor Documentation
AArch64InstrInfo()
AArch64InstrInfo::AArch64InstrInfo (const AArch64Subtarget & STI) explicit
Definition at line 68 of file AArch64InstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool AArch64InstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 210 of file AArch64InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::isCondBranchOpcode(), llvm::isIndirectBranchOpcode(), llvm::isUncondBranchOpcode(), and parseCondBranch().
analyzeCompare()
bool AArch64InstrInfo::analyzeCompare (const MachineInstr & MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const override
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2, and the value it compares against in CmpValue.
Return true if the comparison instruction can be analyzed.
Definition at line 988 of file AArch64InstrInfo.cpp.
References assert(), llvm::AArch64_AM::decodeLogicalImmediate(), and MI.
areMemAccessesTriviallyDisjoint()
bool AArch64InstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb, AliasAnalysis * AA = nullptr) const override
Definition at line 933 of file AArch64InstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineInstr::mayLoadOrStore(), and TRI.
buildOutlinedFrame()
void AArch64InstrInfo::buildOutlinedFrame (MachineBasicBlock & MBB, MachineFunction & MF, const outliner::OutlinedFunction & OF) const override
Definition at line 5373 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createOffset(), llvm::RegState::Define, llvm::MachineBasicBlock::end(), llvm::outliner::OutlinedFunction::FrameConstructionID, llvm::MachineInstr::FrameSetup, llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), MachineOutlinerDefault, MachineOutlinerTailCall, MachineOutlinerThunk, MI, MRI, llvm::MachineInstrBuilder::setMIFlags(), and llvm::RegState::Undef.
canInsertSelect()
bool AArch64InstrInfo::canInsertSelect (const MachineBasicBlock & MBB, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg, int & CondCycles, int & TrueCycles, int & FalseCycles) const override
Definition at line 498 of file AArch64InstrInfo.cpp.
References canFoldIntoCSel(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), and MRI.
convertToFlagSettingOpc()
unsigned AArch64InstrInfo::convertToFlagSettingOpc (unsigned Opc, bool & Is64Bit) static
Return the opcode that set flags when possible.
The caller is responsible for ensuring the opc has a flag setting equivalent.
Definition at line 1816 of file AArch64InstrInfo.cpp.
References llvm_unreachable.
copyGPRRegTuple()
void AArch64InstrInfo::copyGPRRegTuple (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, unsigned ZeroReg, llvm::ArrayRef< unsigned > Indices) const
Definition at line 2404 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), AddSubReg(), assert(), llvm::BuildMI(), llvm::RegState::Define, llvm::getKillRegState(), getRegisterInfo(), I, llvm::ArrayRef< T >::size(), SubReg, and TRI.
Referenced by copyPhysReg().
copyPhysReg()
void AArch64InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 2429 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), copyGPRRegTuple(), copyPhysRegTuple(), llvm::RegState::Define, llvm::getKillRegState(), getRegisterInfo(), llvm::AArch64_AM::getShifterImm(), llvm::AArch64Subtarget::hasNEON(), llvm::AArch64Subtarget::hasZeroCycleRegMove(), llvm::AArch64Subtarget::hasZeroCycleZeroingGP(), I, llvm::RegState::Implicit, llvm_unreachable, llvm::AArch64_AM::LSL, TRI, and llvm::RegState::Undef.
copyPhysRegTuple()
void AArch64InstrInfo::copyPhysRegTuple (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, llvm::ArrayRef< unsigned > Indices) const
Definition at line 2377 of file AArch64InstrInfo.cpp.
References AddSubReg(), assert(), llvm::BuildMI(), llvm::RegState::Define, forwardCopyWillClobberTuple(), llvm::getKillRegState(), getRegisterInfo(), llvm::AArch64Subtarget::hasNEON(), I, llvm::ArrayRef< T >::size(), SubReg, and TRI.
Referenced by copyPhysReg().
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > AArch64InstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 4729 of file AArch64InstrInfo.cpp.
References llvm::AArch64II::MO_FRAGMENT.
expandPostRAPseudo()
bool AArch64InstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 1470 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::RegState::Define, llvm::MachineBasicBlock::erase(), llvm::MachineInstr::FrameDestroy, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::RegState::Kill, llvm::CodeModel::Large, MI, llvm::AArch64II::MO_G0, llvm::AArch64II::MO_G1, llvm::AArch64II::MO_G2, llvm::AArch64II::MO_G3, llvm::AArch64II::MO_GOT, llvm::AArch64II::MO_NC, llvm::AArch64II::MO_PAGE, llvm::AArch64II::MO_PAGEOFF, TII, and llvm::CodeModel::Tiny.
foldMemoryOperandImpl() [1/3]
virtual MachineInstr * llvm::TargetInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr & MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals * LIS = nullptr, VirtRegMap * VRM = nullptr) const inline
Target-dependent implementation for foldMemoryOperand.
Target-independent code in foldMemoryOperand will take care of adding a MachineMemOperand to the newly created instruction. The instruction and any auxiliary instructions necessary will be inserted at InsertPt.
Definition at line 1030 of file TargetInstrInfo.h.
foldMemoryOperandImpl() [2/3]
MachineInstr * AArch64InstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr & MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals * LIS = nullptr, VirtRegMap * VRM = nullptr) const override
Definition at line 3076 of file AArch64InstrInfo.cpp.
References assert(), llvm::MachineRegisterInfo::constrainRegClass(), contains(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isKill(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isUndef(), llvm::TargetRegisterInfo::isVirtualRegister(), loadRegFromStackSlot(), MI, MRI, llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setSubReg(), llvm::ArrayRef< T >::size(), storeRegToStackSlot(), and TRI.
foldMemoryOperandImpl() [3/3]
virtual MachineInstr * llvm::TargetInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr & MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, MachineInstr & LoadMI, LiveIntervals * LIS = nullptr) const inline
Target-dependent implementation for foldMemoryOperand.
Target-independent code in foldMemoryOperand will take care of adding a MachineMemOperand to the newly created instruction. The instruction and any auxiliary instructions necessary will be inserted at InsertPt.
Definition at line 1043 of file TargetInstrInfo.h.
genAlternativeCodeSequence()
void AArch64InstrInfo::genAlternativeCodeSequence (MachineInstr & Root, MachineCombinerPattern Pattern, SmallVectorImpl< MachineInstr * > & InsInstrs, SmallVectorImpl< MachineInstr * > & DelInstrs, DenseMap< unsigned, unsigned > & InstrIdxForVirtReg) const override
When getMachineCombinerPatterns() finds patterns, this function generates the instructions that could replace the original code sequence.
When getMachineCombinerPatterns() finds potential patterns, this function generates the instructions that could replace the original code sequence.
Definition at line 4058 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::FMLAv1i32_indexed_OP1, llvm::FMLAv1i32_indexed_OP2, llvm::FMLAv1i64_indexed_OP1, llvm::FMLAv1i64_indexed_OP2, llvm::FMLAv2f32_OP1, llvm::FMLAv2f32_OP2, llvm::FMLAv2f64_OP1, llvm::FMLAv2f64_OP2, llvm::FMLAv2i32_indexed_OP1, llvm::FMLAv2i32_indexed_OP2, llvm::FMLAv2i64_indexed_OP1, llvm::FMLAv2i64_indexed_OP2, llvm::FMLAv4f32_OP1, llvm::FMLAv4f32_OP2, llvm::FMLAv4i32_indexed_OP1, llvm::FMLAv4i32_indexed_OP2, llvm::FMLSv1i32_indexed_OP2, llvm::FMLSv1i64_indexed_OP2, llvm::FMLSv2f32_OP1, llvm::FMLSv2f32_OP2, llvm::FMLSv2f64_OP1, llvm::FMLSv2f64_OP2, llvm::FMLSv2i32_indexed_OP1, llvm::FMLSv2i32_indexed_OP2, llvm::FMLSv2i64_indexed_OP1, llvm::FMLSv2i64_indexed_OP2, llvm::FMLSv4f32_OP1, llvm::FMLSv4f32_OP2, llvm::FMLSv4i32_indexed_OP1, llvm::FMLSv4i32_indexed_OP2, llvm::FMULADDD_OP1, llvm::FMULADDD_OP2, llvm::FMULADDS_OP1, llvm::FMULADDS_OP2, llvm::FMULSUBD_OP1, llvm::FMULSUBD_OP2, llvm::FMULSUBS_OP1, llvm::FMULSUBS_OP2, llvm::FNMULSUBD_OP1, llvm::FNMULSUBS_OP1, llvm::TargetInstrInfo::genAlternativeCodeSequence(), genFusedMultiply(), genMaddR(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineOperand::isImm(), MRI, llvm::MULADDW_OP1, llvm::MULADDW_OP2, llvm::MULADDWI_OP1, llvm::MULADDX_OP1, llvm::MULADDX_OP2, llvm::MULADDXI_OP1, llvm::MULSUBW_OP1, llvm::MULSUBW_OP2, llvm::MULSUBWI_OP1, llvm::MULSUBX_OP1, llvm::MULSUBX_OP2, llvm::MULSUBXI_OP1, llvm::AArch64_AM::processLogicalImmediate(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SignExtend64(), and TII.
getBranchDestBlock()
MachineBasicBlock * AArch64InstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 189 of file AArch64InstrInfo.cpp.
References llvm_unreachable, and MI.
getInstSizeInBytes()
unsigned AArch64InstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
This returns the maximum number of bytes.
Definition at line 75 of file AArch64InstrInfo.cpp.
References assert(), llvm::TargetMachine::getMCAsmInfo(), llvm::StackMapOpers::getNumPatchBytes(), llvm::PatchPointOpers::getNumPatchBytes(), llvm::MCInstrDesc::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), and MI.
getLoadStoreImmIdx()
unsigned AArch64InstrInfo::getLoadStoreImmIdx (unsigned Opc) static
Returns the index for the immediate for a given instruction.
Definition at line 1751 of file AArch64InstrInfo.cpp.
Referenced by llvm::isAArch64FrameOffsetLegal().
getMachineCombinerPatterns()
bool AArch64InstrInfo::getMachineCombinerPatterns (MachineInstr & Root, SmallVectorImpl< MachineCombinerPattern > & Patterns) const override
Return true when there is potentially a faster code sequence for an instruction chain ending in Root.
Return true when there is potentially a faster code sequence for an instruction chain ending in Root.
All potential patterns are listed in the Patterns array.
All potential patterns are listed in the Pattern vector. Pattern should be sorted in priority order since the pattern evaluator stops checking as soon as it finds a faster sequence.
Definition at line 3909 of file AArch64InstrInfo.cpp.
References getFMAPatterns(), llvm::TargetInstrInfo::getMachineCombinerPatterns(), and getMaddPatterns().
getMemOpBaseRegImmOfsOffsetOperand()
MachineOperand & AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand (MachineInstr & LdSt) const
Return the immediate offset of the base register in a load/store LdSt.
Definition at line 2015 of file AArch64InstrInfo.cpp.
References assert(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and llvm::MachineInstr::mayLoadOrStore().
getMemOperandWithOffset()
bool AArch64InstrInfo::getMemOperandWithOffset (const MachineInstr & MI, const MachineOperand *& BaseOp, int64_t & Offset, const TargetRegisterInfo * TRI) const override
Definition at line 1959 of file AArch64InstrInfo.cpp.
References getMemOperandWithOffsetWidth(), and TRI.
Referenced by getOutliningCandidateInfo().
getMemOperandWithOffsetWidth()
bool AArch64InstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & MI, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Definition at line 1967 of file AArch64InstrInfo.cpp.
References assert(), llvm::MachineOperand::getImm(), getMemOpInfo(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), and llvm::MachineInstr::mayLoadOrStore().
Referenced by areMemAccessesTriviallyDisjoint(), and getMemOperandWithOffset().
getMemOpInfo()
bool AArch64InstrInfo::getMemOpInfo (unsigned Opcode, unsigned & Scale, unsigned & Width, int64_t & MinOffset, int64_t & MaxOffset) static
Returns true if opcode Opc is a memory operation.
If it is, set Scale, Width, MinOffset, and MaxOffset accordingly.
For unscaled instructions, Scale is set to 1.
Definition at line 2022 of file AArch64InstrInfo.cpp.
Referenced by getMemOperandWithOffsetWidth(), getOutliningCandidateInfo(), and llvm::isAArch64FrameOffsetLegal().
getNoop()
void AArch64InstrInfo::getNoop (MCInst & NopInst) const override
Definition at line 3373 of file AArch64InstrInfo.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCInst::setOpcode().
getOutliningCandidateInfo()
outliner::OutlinedFunction AArch64InstrInfo::getOutliningCandidateInfo (std::vector< outliner::Candidate > & RepeatedSequenceLocs) const override
Definition at line 4883 of file AArch64InstrInfo.cpp.
References llvm::any_of(), llvm::LiveRegUnits::available(), llvm::outliner::Candidate::back(), C, llvm::outliner::Candidate::front(), getFunction(), getMemOperandWithOffset(), getMemOpInfo(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineOperand::isReg(), MachineOutlinerDefault, MachineOutlinerNoLRSave, MachineOutlinerRegSave, MachineOutlinerTailCall, MachineOutlinerThunk, MI, TRI, and UnsafeRegsDead.
getOutliningType()
outliner::InstrType AArch64InstrInfo::getOutliningType (MachineBasicBlock::iterator & MIT, unsigned Flags) const override
Definition at line 5214 of file AArch64InstrInfo.cpp.
References Callee, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLOHRelated(), llvm::MachineModuleInfo::getMachineFunction(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getNumObjects(), llvm::MachineBasicBlock::getParent(), getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::outliner::Illegal, llvm::outliner::Invisible, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::outliner::Legal, llvm::outliner::LegalTerminator, and MI.
getRegisterInfo()
const AArch64RegisterInfo & llvm::AArch64InstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 47 of file AArch64InstrInfo.h.
Referenced by areMemAccessesTriviallyDisjoint(), copyGPRRegTuple(), copyPhysReg(), copyPhysRegTuple(), getOutliningCandidateInfo(), getOutliningType(), llvm::AArch64Subtarget::getRegisterInfo(), isCandidateToMergeOrPair(), isMBBSafeToOutlineFrom(), loadRegFromStackSlot(), optimizeCondBranch(), and storeRegToStackSlot().
getSerializableBitmaskMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > AArch64InstrInfo::getSerializableBitmaskMachineOperandTargetFlags () const override
Definition at line 4747 of file AArch64InstrInfo.cpp.
References llvm::makeArrayRef().
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > AArch64InstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 4735 of file AArch64InstrInfo.cpp.
References llvm::makeArrayRef().
getSerializableMachineMemOperandTargetFlags()
ArrayRef< std::pair< MachineMemOperand::Flags, const char * > > AArch64InstrInfo::getSerializableMachineMemOperandTargetFlags () const override
Definition at line 4759 of file AArch64InstrInfo.cpp.
References llvm::makeArrayRef(), llvm::MOStridedAccess, and llvm::MOSuppressPair.
getUnscaledLdSt()
Optional< unsigned > AArch64InstrInfo::getUnscaledLdSt (unsigned Opc) static
Returns the unscaled load/store for the scaled load/store opcode, if there is a corresponding unscaled variant available.
Definition at line 1721 of file AArch64InstrInfo.cpp.
Referenced by llvm::isAArch64FrameOffsetLegal().
insertBranch()
unsigned AArch64InstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 390 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), assert(), and llvm::BuildMI().
insertOutlinedCall()
MachineBasicBlock::iterator AArch64InstrInfo::insertOutlinedCall (Module & M, MachineBasicBlock & MBB, MachineBasicBlock::iterator & It, MachineFunction & MF, const outliner::Candidate & C) const override
Definition at line 5470 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), C, llvm::RegState::Define, llvm::MachineFunction::getName(), llvm::MachineBasicBlock::insert(), MachineOutlinerNoLRSave, MachineOutlinerRegSave, MachineOutlinerTailCall, and MachineOutlinerThunk.
insertSelect()
void AArch64InstrInfo::insertSelect (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const override
Definition at line 540 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), canFoldIntoCSel(), llvm::AArch64_AM::encodeLogicalImmediate(), llvm::AArch64CC::EQ, llvm::AArch64CC::getInvertedCondCode(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::MachineFunction::getRegInfo(), I, llvm_unreachable, MRI, and llvm::AArch64CC::NE.
isAsCheapAsAMove()
bool AArch64InstrInfo::isAsCheapAsAMove (const MachineInstr & MI) const override
Definition at line 686 of file AArch64InstrInfo.cpp.
References canBeExpandedToORR(), llvm::AArch64Subtarget::hasCustomCheapAsMoveHandling(), llvm::AArch64Subtarget::hasExynosCheapAsMoveHandling(), llvm::AArch64Subtarget::hasZeroCycleZeroingFP(), llvm::AArch64Subtarget::hasZeroCycleZeroingGP(), llvm_unreachable, and MI.
isAssociativeAndCommutative()
bool AArch64InstrInfo::isAssociativeAndCommutative (const MachineInstr & Inst) const override
Return true when Inst is associative and commutative so that it can be reassociated.
Definition at line 3513 of file AArch64InstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
isBranchOffsetInRange()
bool AArch64InstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Returns
true if a branch from an instruction with opcode BranchOpc bytes is capable of jumping to a position BrOffset bytes away.
Definition at line 180 of file AArch64InstrInfo.cpp.
References assert(), getBranchDisplacementBits(), and llvm::isIntN().
isCandidateToMergeOrPair()
bool AArch64InstrInfo::isCandidateToMergeOrPair (const MachineInstr & MI) const
Return true if this is a load/store that can be potentially paired/merged.
Definition at line 1906 of file AArch64InstrInfo.cpp.
References assert(), llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, getRegisterInfo(), isLdStPairSuppressed(), llvm::AArch64Subtarget::isPaired128Slow(), MI, TRI, and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by shouldClusterMemOps().
isCoalescableExtInstr()
bool AArch64InstrInfo::isCoalescableExtInstr (const MachineInstr & MI, unsigned & SrcReg, unsigned & DstReg, unsigned & SubIdx) const override
Definition at line 913 of file AArch64InstrInfo.cpp.
References MI.
isCopyInstrImpl()
bool AArch64InstrInfo::isCopyInstrImpl (const MachineInstr & MI, const MachineOperand *& Source, const MachineOperand *& Destination) const override protected
If the specific machine instruction is a instruction that moves/copies value from one register to another register return true along with @Source machine operand and @Destination machine operand.
Definition at line 5547 of file AArch64InstrInfo.cpp.
References MI.
isFalkorShiftExtFast()
bool AArch64InstrInfo::isFalkorShiftExtFast (const MachineInstr & MI) static
Returns true if the instruction has a shift by immediate that can be executed in one cycle less.
Definition at line 765 of file AArch64InstrInfo.cpp.
References llvm::AArch64_AM::ASR, llvm::AArch64_AM::getArithExtendType(), llvm::AArch64_AM::getArithShiftValue(), llvm::AArch64_AM::getShiftType(), llvm::AArch64_AM::getShiftValue(), llvm::AArch64_AM::LSL, MI, llvm::AArch64_AM::UXTB, llvm::AArch64_AM::UXTH, llvm::AArch64_AM::UXTW, and llvm::AArch64_AM::UXTX.
isFPRCopy()
bool AArch64InstrInfo::isFPRCopy (const MachineInstr & MI) static
Does this instruction rename an FPR without modifying bits?
Definition at line 1609 of file AArch64InstrInfo.cpp.
References assert(), contains(), and MI.
isFunctionSafeToOutlineFrom()
bool AArch64InstrInfo::isFunctionSafeToOutlineFrom (MachineFunction & MF, bool OutlineFromLinkOnceODRs) const override
Definition at line 5121 of file AArch64InstrInfo.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::Optional< T >::getValueOr(), and llvm::AArch64FunctionInfo::hasRedZone().
isGPRCopy()
bool AArch64InstrInfo::isGPRCopy (const MachineInstr & MI) static
Does this instruction rename a GPR without modifying bits?
Definition at line 1579 of file AArch64InstrInfo.cpp.
References assert(), contains(), and MI.
isGPRZero()
bool AArch64InstrInfo::isGPRZero (const MachineInstr & MI) static
Does this instruction set its full destination register to zero?
Definition at line 1555 of file AArch64InstrInfo.cpp.
References assert(), and MI.
isLdStPairSuppressed()
bool AArch64InstrInfo::isLdStPairSuppressed (const MachineInstr & MI) static
Return true if pairing the given load or store is hinted to be unprofitable.
Check all MachineMemOperands for a hint to suppress pairing.
Definition at line 1676 of file AArch64InstrInfo.cpp.
References llvm::any_of(), and MI.
Referenced by isCandidateToMergeOrPair().
isLoadFromStackSlot()
unsigned AArch64InstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 1630 of file AArch64InstrInfo.cpp.
References MI.
isMBBSafeToOutlineFrom()
bool AArch64InstrInfo::isMBBSafeToOutlineFrom (MachineBasicBlock & MBB, unsigned & Flags) const override
Definition at line 5147 of file AArch64InstrInfo.cpp.
References llvm::LiveRegUnits::addLiveOuts(), llvm::any_of(), assert(), llvm::LiveRegUnits::available(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64RegisterInfo::isReservedReg(), MI, llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), and llvm::MachineRegisterInfo::tracksLiveness().
isPairableLdStInst()
bool AArch64InstrInfo::isPairableLdStInst (const MachineInstr & MI) static
Return true if pairing the given load or store may be paired with another.
Definition at line 1784 of file AArch64InstrInfo.cpp.
References MI.
Referenced by shouldClusterMemOps().
isSchedulingBoundary()
bool AArch64InstrInfo::isSchedulingBoundary (const MachineInstr & MI, const MachineBasicBlock * MBB, const MachineFunction & MF) const override
Definition at line 965 of file AArch64InstrInfo.cpp.
References llvm::TargetInstrInfo::isSchedulingBoundary(), isSEHInstruction(), and MI.
isSEHInstruction()
bool AArch64InstrInfo::isSEHInstruction (const MachineInstr & MI) static
Return true if the instructions is a SEH instruciton used for unwinding on Windows.
Definition at line 887 of file AArch64InstrInfo.cpp.
References MI.
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::AArch64FrameLowering::emitEpilogue(), fixupCalleeSaveRestoreStackOffset(), and isSchedulingBoundary().
isStoreToStackSlot()
unsigned AArch64InstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 1653 of file AArch64InstrInfo.cpp.
References MI.
isStridedAccess()
bool AArch64InstrInfo::isStridedAccess (const MachineInstr & MI) static
Return true if the given load or store is a strided memory access.
Check all MachineMemOperands for a hint that the load/store is strided.
Definition at line 1690 of file AArch64InstrInfo.cpp.
References llvm::any_of(), and MI.
isSubregFoldable()
bool llvm::AArch64InstrInfo::isSubregFoldable () const inline override
Definition at line 158 of file AArch64InstrInfo.h.
isThroughputPattern()
bool AArch64InstrInfo::isThroughputPattern (MachineCombinerPattern Pattern) const override
Return true when a code sequence can improve throughput.
It should be called only for instructions in loops.
Parameters
Pattern - combiner pattern
Definition at line 3861 of file AArch64InstrInfo.cpp.
References llvm::FMLAv1i32_indexed_OP1, llvm::FMLAv1i32_indexed_OP2, llvm::FMLAv1i64_indexed_OP1, llvm::FMLAv1i64_indexed_OP2, llvm::FMLAv2f32_OP1, llvm::FMLAv2f32_OP2, llvm::FMLAv2f64_OP1, llvm::FMLAv2f64_OP2, llvm::FMLAv2i32_indexed_OP1, llvm::FMLAv2i32_indexed_OP2, llvm::FMLAv2i64_indexed_OP1, llvm::FMLAv2i64_indexed_OP2, llvm::FMLAv4f32_OP1, llvm::FMLAv4f32_OP2, llvm::FMLAv4i32_indexed_OP1, llvm::FMLAv4i32_indexed_OP2, llvm::FMLSv1i32_indexed_OP2, llvm::FMLSv1i64_indexed_OP2, llvm::FMLSv2f32_OP2, llvm::FMLSv2f64_OP2, llvm::FMLSv2i32_indexed_OP2, llvm::FMLSv2i64_indexed_OP2, llvm::FMLSv4f32_OP2, llvm::FMLSv4i32_indexed_OP2, llvm::FMULADDD_OP1, llvm::FMULADDD_OP2, llvm::FMULADDS_OP1, llvm::FMULADDS_OP2, llvm::FMULSUBD_OP1, llvm::FMULSUBD_OP2, llvm::FMULSUBS_OP1, llvm::FMULSUBS_OP2, llvm::FNMULSUBD_OP1, and llvm::FNMULSUBS_OP1.
isUnscaledLdSt() [1/2]
static bool llvm::AArch64InstrInfo::isUnscaledLdSt (MachineInstr & MI) inline static
Definition at line 84 of file AArch64InstrInfo.h.
References isUnscaledLdSt(), and MI.
isUnscaledLdSt() [2/2]
bool AArch64InstrInfo::isUnscaledLdSt (unsigned Opc) static
Return true if this is an unscaled load/store.
Definition at line 1696 of file AArch64InstrInfo.cpp.
Referenced by isUnscaledLdSt(), and shouldClusterMemOps().
loadRegFromStackSlot()
void AArch64InstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 2882 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::getDefRegState(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::AArch64Subtarget::hasNEON(), llvm::TargetRegisterInfo::isVirtualRegister(), loadRegPairFromStackSlot(), MI, llvm::MachineMemOperand::MOLoad, and TRI.
Referenced by foldMemoryOperandImpl().
optimizeCompareInstr()
bool AArch64InstrInfo::optimizeCompareInstr (MachineInstr & CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const override
optimizeCompareInstr - Convert the instruction supplying the argument to the comparison into one that sets the zero bit in the flags register.
Try to optimize a compare instruction.
A compare instruction is an instruction which produces AArch64::NZCV. It can be truly compare instruction when there are no uses of its destination register.
The following steps are tried in order:
Convert CmpInstr into an unconditional version.
Remove CmpInstr if above there is an instruction producing a needed condition code or an instruction which can be converted into such an instruction. Only comparison with zero is supported.
Definition at line 1183 of file AArch64InstrInfo.cpp.
References assert(), convertToNonFlagSettingOpc(), llvm::MachineInstr::definesRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), MRI, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), and UpdateOperandRegClass().
optimizeCondBranch()
bool AArch64InstrInfo::optimizeCondBranch (MachineInstr & MI) const override
Replace csincr-branch sequence by simple conditional branch.
Examples:
csinc  w9, wzr, wzr, <condition code>
tbnz   w9, #0, 0x44
to
b.<inverted condition code>
csinc w9, wzr, wzr, <condition code>
tbz   w9, #0, 0x44
to
b.<condition code>
Replace compare and branch sequence by TBZ/TBNZ instruction when the compare's constant operand is power of 2.
Examples:
and  w8, w8, #0x400
cbnz w8, L1
to
tbnz w8, #10, L1
Parameters
MI Conditional Branch
Returns
True when the simple conditional branch is generated
Definition at line 4591 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), AK_Write, areCFlagsAccessedBetweenInstrs(), assert(), llvm::BuildMI(), llvm::AArch64_AM::decodeLogicalImmediate(), DefMI, llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::MachineOperand::getImm(), llvm::AArch64CC::getInvertedCondCode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::MachineInstr::isCopy(), llvm::isPowerOf2_64(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm_unreachable, llvm::Log2_64(), MI, MRI, llvm::MachineOperand::setIsKill(), and llvm::MachineOperand::setSubReg().
removeBranch()
unsigned AArch64InstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 338 of file AArch64InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), I, llvm::isCondBranchOpcode(), and llvm::isUncondBranchOpcode().
reverseBranchCondition()
bool AArch64InstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 297 of file AArch64InstrInfo.cpp.
References llvm::AArch64CC::getInvertedCondCode(), and llvm_unreachable.
shouldClusterMemOps()
bool AArch64InstrInfo::shouldClusterMemOps (const MachineOperand & BaseOp1, const MachineOperand & BaseOp2, unsigned NumLoads) const override
Detect opportunities for ldp/stp formation.
Only called for LdSt for which getMemOperandWithOffset returns true.
Definition at line 2293 of file AArch64InstrInfo.cpp.
References assert(), canPairLdStOpc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), isCandidateToMergeOrPair(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isIdenticalTo(), isPairableLdStInst(), llvm::MachineOperand::isReg(), isUnscaledLdSt(), scaleOffset(), and shouldClusterFI().
shouldOutlineFromFunctionByDefault()
bool AArch64InstrInfo::shouldOutlineFromFunctionByDefault (MachineFunction & MF) const override
Definition at line 5542 of file AArch64InstrInfo.cpp.
References llvm::MachineFunction::getFunction().
storeRegToStackSlot()
void AArch64InstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 2751 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::AArch64Subtarget::hasNEON(), llvm::TargetRegisterInfo::isVirtualRegister(), MI, llvm::MachineMemOperand::MOStore, storeRegPairToStackSlot(), and TRI.
Referenced by foldMemoryOperandImpl().
suppressLdStPair()
void AArch64InstrInfo::suppressLdStPair (MachineInstr & MI) static
Hint that pairing the given load or store is unprofitable.
Set a flag on the first MachineMemOperand to suppress pairing.
Definition at line 1683 of file AArch64InstrInfo.cpp.
References MI, and llvm::MOSuppressPair.
useMachineCombiner()
bool AArch64InstrInfo::useMachineCombiner () const override
AArch64 supports MachineCombiner.
Definition at line 3379 of file AArch64InstrInfo.cpp.
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64InstrInfo.h
lib/Target/AArch64/AArch64InstrInfo.cpp