LLVM: llvm::sys::SmartMutex< mt_only > Class Template Reference
llvm::sys::SmartMutex< mt_only > Class Template Reference
SmartMutex - A mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
#include "llvm/Support/Mutex.h"
Public Member Functions
SmartMutex (bool rec=true)
bool lock ()
bool unlock ()
bool try_lock ()
Detailed Description
template<bool mt_only>
class llvm::sys::SmartMutex< mt_only >
SmartMutex - A mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
Definition at line 91 of file Mutex.h.
Constructor & Destructor Documentation
SmartMutex()
template<bool mt_only> llvm::sys::SmartMutex< mt_only >::SmartMutex (bool rec = true) inline explicit
Definition at line 96 of file Mutex.h.
References impl.
Member Function Documentation
lock()
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::lock () inline
Definition at line 99 of file Mutex.h.
References assert(), impl, and llvm::llvm_is_multithreaded().
Referenced by llvm::sys::SmartScopedLock< mt_only >::SmartScopedLock().
try_lock()
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::try_lock () inline
Definition at line 126 of file Mutex.h.
References impl, and llvm::llvm_is_multithreaded().
unlock()
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::unlock () inline
Definition at line 112 of file Mutex.h.
References assert(), impl, and llvm::llvm_is_multithreaded().
Referenced by llvm::orc::JITCompileCallbackManager::executeCompileCallback(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse(), and llvm::sys::SmartScopedLock< mt_only >::~SmartScopedLock().
The documentation for this class was generated from the following file:
include/llvm/Support/Mutex.h