LLVM: llvm::orc::remote::OrcRemoteTargetClient Class Reference
llvm::orc::remote::OrcRemoteTargetClient Class Reference
This class provides utilities (including memory manager, indirect stubs manager, and compile callback manager types) that support remote JITing in ORC.
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h"
Classes
class RemoteCompileCallbackManager
Remote compile callback manager.
class RemoteIndirectStubsManager
Remote indirect stubs manager.
class RemoteRTDyldMemoryManager
Remote-mapped RuntimeDyld-compatible memory manager.
class RemoteTrampolinePool
Public Member Functions
Expected< int > callIntVoid (JITTargetAddress Addr)
Call the int(void) function at the given address in the target and return its result.
Expected< int > callMain (JITTargetAddress Addr, const std::vector< std::string > &Args)
Call the int(int, char*[]) function at the given address in the target and return its result.
Error callVoidVoid (JITTargetAddress Addr)
Call the void() function at the given address in the target and wait for it to finish.
Expected< std::unique_ptr< RemoteRTDyldMemoryManager > > createRemoteMemoryManager ()
Create an RCMemoryManager which will allocate its memory on the remote target.
Expected< std::unique_ptr< RemoteIndirectStubsManager > > createIndirectStubsManager ()
Create an RCIndirectStubsManager that will allocate stubs on the remote target.
Expected< RemoteCompileCallbackManager & > enableCompileCallbacks (JITTargetAddress ErrorHandlerAddress)
Expected< JITTargetAddress > getSymbolAddress (StringRef Name)
Search for symbols in the remote process.
const std::string & getTargetTriple () const
Get the triple for the remote target.
Error terminateSession ()
Public Member Functions inherited from llvm::orc::rpc::SingleThreadedRPCEndpoint< rpc::RawByteChannel >
SingleThreadedRPCEndpoint (rpc::RawByteChannel &C, bool LazyAutoNegotiation)
void addHandler (HandlerT Handler)
void addHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
void addAsyncHandler (HandlerT Handler)
void addAsyncHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
Add a class-method as a handler.
detail::ResultTraits< AltRetT >::ErrorReturnType callB (const ArgTs &... Args)
Public Member Functions inherited from llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
RPCEndpointBase (ChannelT &C, bool LazyAutoNegotiation)
Construct an RPC instance on a channel.
template<typename Func >
Error negotiateFunction (bool Retry=false)
Negotiate a function id for Func with the other end of the channel.
template<typename Func , typename HandlerT , typename... ArgTs>
Error appendCallAsync (HandlerT Handler, const ArgTs &... Args)
Append a call Func, does not call send on the channel.
Error sendAppendedCalls ()
template<typename Func , typename HandlerT , typename... ArgTs>
Error callAsync (HandlerT Handler, const ArgTs &... Args)
Error handleOne ()
Handle one incoming call.
void abandonPendingResponses ()
Abandon all outstanding result handlers.
template<typename Func >
void removeHandler ()
Remove the handler for the given function.
void clearHandlers ()
Clear all handlers.
Static Public Member Functions
static Expected< std::unique_ptr< OrcRemoteTargetClient > > Create (rpc::RawByteChannel &Channel, ExecutionSession &ES)
Create an OrcRemoteTargetClient.
Static Public Member Functions inherited from llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
template<typename... ArgTs>
static detail::ReadArgs< ArgTs... > readArgs (ArgTs &... Args)
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args... to values deserialized from the channel.
Additional Inherited Members
Protected Types inherited from llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
using WrappedHandlerFn = std::function< Error(ChannelT &, SequenceNumberT)>
Protected Member Functions inherited from llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
FunctionIdT getInvalidFunctionId () const
template<typename Func , typename HandlerT >
void addHandlerImpl (HandlerT Handler)
Add the given handler to the handler map and make it available for autonegotiation and execution.
template<typename Func , typename HandlerT >
void addAsyncHandlerImpl (HandlerT Handler)
Error handleResponse (SequenceNumberT SeqNo)
FunctionIdT handleNegotiate (const std::string &Name)
template<typename Func >
Expected< FunctionIdT > getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid)
template<typename Func , typename HandlerT >
WrappedHandlerFn wrapHandler (HandlerT Handler)
template<typename Func , typename HandlerT >
WrappedHandlerFn wrapAsyncHandler (HandlerT Handler)
Protected Attributes inherited from llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
ChannelT & C
bool LazyAutoNegotiation
RPCFunctionIdAllocator< FunctionIdT > FnIdAllocator
FunctionIdT ResponseId
std::map< std::string, FunctionIdT > LocalFunctionIds
std::map< const char *, FunctionIdT > RemoteFunctionIds
std::map< FunctionIdT, WrappedHandlerFn > Handlers
std::mutex ResponsesMutex
detail::SequenceNumberManager< SequenceNumberT > SequenceNumberMgr
std::map< SequenceNumberT, std::unique_ptr< detail::ResponseHandler< ChannelT > > > PendingResponses
Detailed Description
This class provides utilities (including memory manager, indirect stubs manager, and compile callback manager types) that support remote JITing in ORC.
Each of the utility classes talks to a JIT server (an instance of the OrcRemoteTargetServer class) via an RPC system (see RPCUtils.h) to carry out its actions.
Definition at line 55 of file OrcRemoteTargetClient.h.
Member Function Documentation
callIntVoid()
Expected< int > llvm::orc::remote::OrcRemoteTargetClient::callIntVoid (JITTargetAddress Addr) inline
Call the int(void) function at the given address in the target and return its result.
Definition at line 515 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
callMain()
Expected< int > llvm::orc::remote::OrcRemoteTargetClient::callMain (JITTargetAddress Addr, const std::vector< std::string > & Args) inline
Call the int(int, char*[]) function at the given address in the target and return its result.
Definition at line 523 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
callVoidVoid()
Error llvm::orc::remote::OrcRemoteTargetClient::callVoidVoid (JITTargetAddress Addr) inline
Call the void() function at the given address in the target and wait for it to finish.
Definition at line 532 of file OrcRemoteTargetClient.h.
References llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
Create()
static Expected< std::unique_ptr< OrcRemoteTargetClient > > llvm::orc::remote::OrcRemoteTargetClient::Create (rpc::RawByteChannel & Channel, ExecutionSession & ES) inline static
Create an OrcRemoteTargetClient.
Channel is the ChannelT instance to communicate on. It is assumed that the channel is ready to be read from and written to.
Definition at line 504 of file OrcRemoteTargetClient.h.
References llvm::Error::success().
createIndirectStubsManager()
Expected< std::unique_ptr< RemoteIndirectStubsManager > > llvm::orc::remote::OrcRemoteTargetClient::createIndirectStubsManager () inline
Create an RCIndirectStubsManager that will allocate stubs on the remote target.
Definition at line 552 of file OrcRemoteTargetClient.h.
References llvm::orc::remote::ResourceIdMgr::getNext().
createRemoteMemoryManager()
Expected< std::unique_ptr< RemoteRTDyldMemoryManager > > llvm::orc::remote::OrcRemoteTargetClient::createRemoteMemoryManager () inline
Create an RCMemoryManager which will allocate its memory on the remote target.
Definition at line 541 of file OrcRemoteTargetClient.h.
References llvm::orc::remote::ResourceIdMgr::getNext().
enableCompileCallbacks()
Expected< RemoteCompileCallbackManager & > llvm::orc::remote::OrcRemoteTargetClient::enableCompileCallbacks (JITTargetAddress ErrorHandlerAddress) inline
Definition at line 560 of file OrcRemoteTargetClient.h.
References assert().
getSymbolAddress()
Expected< JITTargetAddress > llvm::orc::remote::OrcRemoteTargetClient::getSymbolAddress (StringRef Name) inline
Search for symbols in the remote process.
Note: This should be used by symbol resolvers after they've searched the local symbol table in the JIT stack.
Definition at line 576 of file OrcRemoteTargetClient.h.
References Name.
getTargetTriple()
const std::string & llvm::orc::remote::OrcRemoteTargetClient::getTargetTriple () const inline
Get the triple for the remote target.
Definition at line 581 of file OrcRemoteTargetClient.h.
terminateSession()
Error llvm::orc::remote::OrcRemoteTargetClient::terminateSession () inline
Definition at line 583 of file OrcRemoteTargetClient.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h