LLVM: llvm::VPlan Class Reference
llvm::VPlan Class Reference
VPlan models a candidate for vectorization, encoding various decisions take to produce efficient output IR, including which branches, basic-blocks and output IR instructions to generate, and their cost.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPlan (VPBlockBase *Entry=nullptr)
~VPlan ()
void execute (struct VPTransformState *State)
Generate the IR code for this VPlan.
VPBlockBase * getEntry ()
const VPBlockBase * getEntry () const
VPBlockBase * setEntry (VPBlockBase *Block)
VPValue * getOrCreateBackedgeTakenCount ()
The backedge taken count of the original loop.
void addVF (unsigned VF)
bool hasVF (unsigned VF)
const std::string & getName () const
void setName (const Twine &newName)
void addExternalDef (VPValue *VPVal)
Add VPVal to the pool of external definitions if it's not already in the pool.
void addCBV (VPValue *CBV)
Add CBV to the vector of condition bit values.
void addVPValue (Value *V)
VPValue * getVPValue (Value *V)
VPLoopInfo & getVPLoopInfo ()
Return the VPLoopInfo analysis for this VPlan.
const VPLoopInfo & getVPLoopInfo () const
Friends
class VPlanPrinter
Detailed Description
VPlan models a candidate for vectorization, encoding various decisions take to produce efficient output IR, including which branches, basic-blocks and output IR instructions to generate, and their cost.
VPlan holds a Hierarchical-CFG of VPBasicBlocks and VPRegionBlocks rooted at an Entry VPBlock.
Definition at line 1147 of file VPlan.h.
Constructor & Destructor Documentation
VPlan()
llvm::VPlan::VPlan (VPBlockBase * Entry = nullptr) inline
Definition at line 1182 of file VPlan.h.
~VPlan()
llvm::VPlan::~VPlan () inline
Definition at line 1184 of file VPlan.h.
References llvm::VPBlockBase::deleteCFG().
Member Function Documentation
addCBV()
void llvm::VPlan::addCBV (VPValue * CBV) inline
Add CBV to the vector of condition bit values.
Definition at line 1228 of file VPlan.h.
addExternalDef()
void llvm::VPlan::addExternalDef (VPValue * VPVal) inline
Add VPVal to the pool of external definitions if it's not already in the pool.
Definition at line 1223 of file VPlan.h.
addVF()
void llvm::VPlan::addVF (unsigned VF) inline
Definition at line 1213 of file VPlan.h.
addVPValue()
void llvm::VPlan::addVPValue (Value * V) inline
Definition at line 1232 of file VPlan.h.
References assert().
execute()
void VPlan::execute (struct VPTransformState * State)
Generate the IR code for this VPlan.
Generate the code inside the body of the vectorized loop.
Assumes a single LoopVectorBody basic-block was created for this. Introduce additional basic-blocks as needed, and fill them all.
Definition at line 359 of file VPlan.cpp.
References assert(), llvm::VPTransformState::Builder, llvm::VPTransformState::CFG, llvm::VPTransformState::DT, EnableVPlanNativePath, llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBlockBase::getHierarchicalSuccessors(), llvm::VPValue::getNumUsers(), Idx, llvm::VPTransformState::CFGState::LastBB, llvm::VPTransformState::LI, llvm::VPTransformState::CFGState::PrevBB, llvm::VPTransformState::CFGState::PrevVPBB, llvm::VPTransformState::TripCount, llvm::VPTransformState::CFGState::VPBB2IRBB, llvm::VPTransformState::CFGState::VPBBsToFix, and llvm::VPTransformState::VPValue2Value.
getEntry() [1/2]
VPBlockBase * llvm::VPlan::getEntry () inline
Definition at line 1201 of file VPlan.h.
Referenced by llvm::VPlanPredicator::predicate(), llvm::VPInterleavedAccessInfo::VPInterleavedAccessInfo(), and llvm::VPlanPredicator::VPlanPredicator().
getEntry() [2/2]
const VPBlockBase * llvm::VPlan::getEntry () const inline
Definition at line 1202 of file VPlan.h.
getName()
const std::string & llvm::VPlan::getName () const inline
Definition at line 1217 of file VPlan.h.
getOrCreateBackedgeTakenCount()
VPValue * llvm::VPlan::getOrCreateBackedgeTakenCount () inline
The backedge taken count of the original loop.
Definition at line 1207 of file VPlan.h.
getVPLoopInfo() [1/2]
VPLoopInfo & llvm::VPlan::getVPLoopInfo () inline
Return the VPLoopInfo analysis for this VPlan.
Definition at line 1245 of file VPlan.h.
Referenced by llvm::VPlanHCFGBuilder::buildHierarchicalCFG().
getVPLoopInfo() [2/2]
const VPLoopInfo & llvm::VPlan::getVPLoopInfo () const inline
Definition at line 1246 of file VPlan.h.
getVPValue()
VPValue * llvm::VPlan::getVPValue (Value * V) inline
Definition at line 1238 of file VPlan.h.
References assert().
hasVF()
bool llvm::VPlan::hasVF (unsigned VF) inline
Definition at line 1215 of file VPlan.h.
setEntry()
VPBlockBase * llvm::VPlan::setEntry (VPBlockBase * Block) inline
Definition at line 1204 of file VPlan.h.
Referenced by llvm::VPlanHCFGBuilder::buildHierarchicalCFG().
setName()
void llvm::VPlan::setName (const Twine & newName) inline
Definition at line 1219 of file VPlan.h.
Referenced by llvm::VPlanHCFGBuilder::buildHierarchicalCFG().
Friends And Related Function Documentation
VPlanPrinter
friend class VPlanPrinter friend
Definition at line 1148 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp