LLVM: llvm::SCEVParameterRewriter Class Reference
llvm::SCEVParameterRewriter Class Reference
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> Value).
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVParameterRewriter (ScalarEvolution &SE, ValueToValueMap &M, bool C)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
Public Member Functions inherited from llvm::SCEVRewriteVisitor< SCEVParameterRewriter >
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SC, RetVal >
RetVal visit (const SCEV *S)
RetVal visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, ScalarEvolution &SE, ValueToValueMap &Map, bool InterpretConsts=false)
Additional Inherited Members
Protected Attributes inherited from llvm::SCEVRewriteVisitor< SCEVParameterRewriter >
ScalarEvolution & SE
DenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> Value).
Definition at line 789 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVParameterRewriter()
llvm::SCEVParameterRewriter::SCEVParameterRewriter (ScalarEvolution & SE, ValueToValueMap & M, bool C) inline
Definition at line 798 of file ScalarEvolutionExpressions.h.
Member Function Documentation
rewrite()
static const SCEV * llvm::SCEVParameterRewriter::rewrite (const SCEV * Scev, ScalarEvolution & SE, ValueToValueMap & Map, bool InterpretConsts = false) inline static
Definition at line 791 of file ScalarEvolutionExpressions.h.
References llvm::SCEVRewriteVisitor< SCEVParameterRewriter >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
Referenced by llvm::ScalarEvolution::convertSCEVToAddRecWithPredicates(), llvm::ScalarEvolution::rewriteUsingPredicate(), and llvm::ScalarEvolution::SplitIntoInitAndPostInc().
visitUnknown()
const SCEV * llvm::SCEVParameterRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 801 of file ScalarEvolutionExpressions.h.
References llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getUnknown(), llvm::SCEVUnknown::getValue(), and llvm::SCEVRewriteVisitor< SCEVParameterRewriter >::SE.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h