LLVM: llvm::sampleprof::SampleProfileReaderRawBinary Class Reference
llvm::sampleprof::SampleProfileReaderRawBinary Class Reference
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReaderRawBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C)
Public Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual std::error_code readHeader () override
Read and validate the file header.
std::error_code read () override
Read sample profiles from the associated file.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
virtual std::error_code readHeader ()=0
Read and validate the file header.
virtual std::error_code read ()=0
Read sample profiles from the associated file.
void dumpFunctionProfile (StringRef FName, raw_ostream &OS=dbgs())
Print the profile for FName on stream OS.
virtual void collectFuncsToUse (const Module &M)
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
StringMap< FunctionSamples > & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, Twine Msg) const
Report a parse error message.
ProfileSummary & getSummary ()
Return the profile summary.
SampleProfileFormat getFormat ()
Return the profile format.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &Buffer)
Return true if Buffer is in the format supported by this class.
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const Twine &Filename, LLVMContext &C)
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C)
Create a sample profile reader from the supplied memory buffer.
Additional Inherited Members
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
template<typename T >
ErrorOr< T > readNumber ()
Read a numeric value of type T from the profile.
template<typename T >
ErrorOr< T > readUnencodedNumber ()
Read a numeric value of type T from the profile.
ErrorOr< StringRef > readString ()
Read a string from the profile.
template<typename T >
ErrorOr< uint32_t > readStringIndex (T &Table)
Read the string index and check whether it overflows the table.
bool at_eof () const
Return true if we've reached the end of file.
std::error_code readFuncProfile ()
Read the next function profile instance.
std::error_code readProfile (FunctionSamples &FProfile)
Read the contents of the given profile instance.
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
void computeSummary ()
Compute summary for this profile.
Static Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReaderBinary
const uint8_t * Data = nullptr
Points to the current location in the buffer.
const uint8_t * End = nullptr
Points to the end of the buffer.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
StringMap< FunctionSamples > Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
SampleProfileFormat Format = SPF_None
The format of sample.
Detailed Description
Definition at line 439 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderRawBinary()
llvm::sampleprof::SampleProfileReaderRawBinary::SampleProfileReaderRawBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext & C) inline
Definition at line 449 of file SampleProfReader.h.
Member Function Documentation
hasFormat()
bool SampleProfileReaderRawBinary::hasFormat (const MemoryBuffer & Buffer) static
Return true if Buffer is in the format supported by this class.
Definition at line 657 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, llvm::sampleprof::SampleProfileReaderBinary::Data, llvm::decodeULEB128(), Magic, and llvm::sampleprof::SPMagic().
Referenced by llvm::sampleprof::SampleProfileReader::create().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp