LLVM: llvm::SCEVUnionPredicate Class Reference
llvm::SCEVUnionPredicate Class Reference final
This class represents a composition of other SCEV predicates, and is the class that most clients will interact with.
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
SCEVUnionPredicate ()
Union predicates don't get cached so create a dummy set ID for it.
const SmallVectorImpl< const SCEVPredicate * > & getPredicates () const
void add (const SCEVPredicate *N)
Adds a predicate to this union.
ArrayRef< const SCEVPredicate * > getPredicatesForExpr (const SCEV *Expr)
Returns a reference to a vector containing all predicates which apply to Expr.
bool isAlwaysTrue () const override
Implementation of the SCEVPredicate interface.
bool implies (const SCEVPredicate *N) const override
Returns true if this predicate implies N.
void print (raw_ostream &OS, unsigned Depth) const override
Prints a textual representation of this predicate with an indentation of Depth.
const SCEV * getExpr () const override
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
unsigned getComplexity () const override
We estimate the complexity of a union predicate as the size number of predicates in the union.
Public Member Functions inherited from llvm::SCEVPredicate
SCEVPredicate (const FoldingSetNodeIDRef ID, SCEVPredicateKind Kind)
SCEV predicates.
SCEVPredicateKind getKind () const
virtual unsigned getComplexity () const
Returns the estimated complexity of this predicate.
virtual bool isAlwaysTrue () const =0
Returns true if the predicate is always true.
virtual bool implies (const SCEVPredicate *N) const =0
Returns true if this predicate implies N.
virtual void print (raw_ostream &OS, unsigned Depth=0) const =0
Prints a textual representation of this predicate with an indentation of Depth.
virtual const SCEV * getExpr () const =0
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Static Public Member Functions
static bool classof (const SCEVPredicate *P)
Methods for support type inquiry through isa, cast, and dyn_cast:
Additional Inherited Members
Public Types inherited from llvm::SCEVPredicate
enum SCEVPredicateKind { P_Union , P_Equal , P_Wrap }
Protected Member Functions inherited from llvm::SCEVPredicate
~SCEVPredicate ()=default
SCEVPredicate (const SCEVPredicate &)=default
SCEVPredicate & operator= (const SCEVPredicate &)=default
Protected Attributes inherited from llvm::SCEVPredicate
SCEVPredicateKind Kind
Detailed Description
This class represents a composition of other SCEV predicates, and is the class that most clients will interact with.
This is equivalent to a logical "AND" of all the predicates in the union.
NB! Unlike other SCEVPredicate sub-classes this class does not live in the ScalarEvolution::Preds folding set. This is why the add function is sound.
Definition at line 397 of file ScalarEvolution.h.
Constructor & Destructor Documentation
SCEVUnionPredicate()
SCEVUnionPredicate::SCEVUnionPredicate ()
Union predicates don't get cached so create a dummy set ID for it.
Definition at line 12248 of file ScalarEvolution.cpp.
Member Function Documentation
add()
void SCEVUnionPredicate::add (const SCEVPredicate * N)
Adds a predicate to this union.
Definition at line 12285 of file ScalarEvolution.cpp.
References add(), assert(), implies(), and N.
Referenced by add(), llvm::PredicatedScalarEvolution::addPredicate(), and llvm::PredicatedScalarEvolution::getAsAddRec().
classof()
static bool llvm::SCEVUnionPredicate::classof (const SCEVPredicate * P) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 433 of file ScalarEvolution.h.
References P, and llvm::SCEVPredicate::P_Union.
getComplexity()
unsigned llvm::SCEVUnionPredicate::getComplexity () const inline override virtual
We estimate the complexity of a union predicate as the size number of predicates in the union.
Reimplemented from llvm::SCEVPredicate.
Definition at line 430 of file ScalarEvolution.h.
Referenced by llvm::LoopVectorizationLegality::canVectorize().
getExpr()
const SCEV * SCEVUnionPredicate::getExpr () const override virtual
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Implements llvm::SCEVPredicate.
Definition at line 12278 of file ScalarEvolution.cpp.
getPredicates()
const SmallVectorImpl< const SCEVPredicate * > & llvm::SCEVUnionPredicate::getPredicates () const inline
Definition at line 411 of file ScalarEvolution.h.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF().
getPredicatesForExpr()
ArrayRef< const SCEVPredicate * > SCEVUnionPredicate::getPredicatesForExpr (const SCEV * Expr)
Returns a reference to a vector containing all predicates which apply to Expr.
Definition at line 12257 of file ScalarEvolution.cpp.
References I.
implies()
bool SCEVUnionPredicate::implies (const SCEVPredicate * N) const override virtual
Returns true if this predicate implies N.
Implements llvm::SCEVPredicate.
Definition at line 12264 of file ScalarEvolution.cpp.
References I, and N.
Referenced by add(), llvm::PredicatedScalarEvolution::addPredicate(), and llvm::PredicatedScalarEvolution::areAddRecsEqualWithPreds().
isAlwaysTrue()
bool SCEVUnionPredicate::isAlwaysTrue () const override virtual
Implementation of the SCEVPredicate interface.
Implements llvm::SCEVPredicate.
Definition at line 12251 of file ScalarEvolution.cpp.
References I.
print()
void SCEVUnionPredicate::print (raw_ostream & OS, unsigned Depth) const override virtual
Prints a textual representation of this predicate with an indentation of Depth.
Implements llvm::SCEVPredicate.
Definition at line 12280 of file ScalarEvolution.cpp.
References print().
Referenced by print(), and PrintLoopInfo().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp