LLVM: llvm::FileCheckASTBinop Class Reference
llvm::FileCheckASTBinop Class Reference
Class representing a single binary operation in the AST of an expression.
#include "llvm/Support/FileCheck.h"
Public Member Functions
FileCheckASTBinop (binop_eval_t EvalBinop, std::unique_ptr< FileCheckExpressionAST > LeftOp, std::unique_ptr< FileCheckExpressionAST > RightOp)
Expected< uint64_t > eval () const
Evaluates the value of the binary operation represented by this AST, using EvalBinop on the result of recursively evaluating the operands.
Public Member Functions inherited from llvm::FileCheckExpressionAST
virtual ~FileCheckExpressionAST ()=default
virtual Expected< uint64_t > eval () const =0
Evaluates and.
Detailed Description
Class representing a single binary operation in the AST of an expression.
Definition at line 154 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheckASTBinop()
llvm::FileCheckASTBinop::FileCheckASTBinop (binop_eval_t EvalBinop, std::unique_ptr< FileCheckExpressionAST > LeftOp, std::unique_ptr< FileCheckExpressionAST > RightOp) inline
Definition at line 166 of file FileCheck.h.
Member Function Documentation
eval()
Expected< uint64_t > FileCheckASTBinop::eval () const virtual
Evaluates the value of the binary operation represented by this AST, using EvalBinop on the result of recursively evaluating the operands.
Returns
the expression value or an error if an undefined numeric variable is used in one of the operands.
Implements llvm::FileCheckExpressionAST.
Definition at line 45 of file FileCheck.cpp.
References llvm::joinErrors(), llvm::Error::success(), and llvm::Expected< T >::takeError().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp