LLVM: llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
SetterImpl & setLazyCompileFailureAddr (JITTargetAddress Addr)
Set the address in the target address to call if a lazy compile fails.
SetterImpl & setLazyCallthroughManager (std::unique_ptr< LazyCallThroughManager > LCTMgr)
Set the lazy-callthrough manager.
SetterImpl & setIndirectStubsManagerBuilder (LLLazyJITBuilderState::IndirectStubsManagerBuilderFunction ISMBuilder)
Set the IndirectStubsManager builder function.
Public Member Functions inherited from llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
SetterImpl & setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB)
Set the JITTargetMachineBuilder for this instance.
Optional< JITTargetMachineBuilder > & getJITTargetMachineBuilder ()
Return a reference to the JITTargetMachineBuilder.
SetterImpl & setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer)
Set an ObjectLinkingLayer creation function.
SetterImpl & setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction)
Set a CompileFunctionCreator.
SetterImpl & setNumCompileThreads (unsigned NumCompileThreads)
Set the number of compile threads to use.
Expected< std::unique_ptr< JITType > > create ()
Create an instance of the JIT.
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
SetterImpl & impl ()
Detailed Description
template<typename JITType, typename SetterImpl, typename State>
class llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >
Definition at line 294 of file LLJIT.h.
Member Function Documentation
setIndirectStubsManagerBuilder()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setIndirectStubsManagerBuilder (LLLazyJITBuilderState::IndirectStubsManagerBuilderFunction ISMBuilder) inline
Set the IndirectStubsManager builder function.
If this method is not called then a default, in-process IndirectStubsManager builder for the host platform will be used.
Definition at line 319 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setLazyCallthroughManager()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCallthroughManager (std::unique_ptr< LazyCallThroughManager > LCTMgr) inline
Set the lazy-callthrough manager.
If this method is not called then a default, in-process lazy callthrough manager for the host platform will be used.
Definition at line 310 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setLazyCompileFailureAddr()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCompileFailureAddr (JITTargetAddress Addr) inline
Set the address in the target address to call if a lazy compile fails.
If this method is not called then the value will default to 0.
Definition at line 300 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/LLJIT.h