LLVM: llvm::orc::SimpleCompiler Class Reference
llvm::orc::SimpleCompiler Class Reference
Simple compile functor: Takes a single IR module and returns an ObjectFile.
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
Public Types
using CompileResult = std::unique_ptr< MemoryBuffer >
Public Member Functions
SimpleCompiler (TargetMachine &TM, ObjectCache *ObjCache=nullptr)
Construct a simple compile functor with the given target.
void setObjectCache (ObjectCache *NewCache)
Set an ObjectCache to query before compiling.
CompileResult operator() (Module &M)
Compile a Module to an ObjectFile.
Detailed Description
Simple compile functor: Takes a single IR module and returns an ObjectFile.
This compiler supports a single compilation thread and LLVMContext only. For multithreaded compilation, use ConcurrentIRCompiler below.
Definition at line 34 of file CompileUtils.h.
Member Typedef Documentation
CompileResult
using llvm::orc::SimpleCompiler::CompileResult = std::unique_ptr<MemoryBuffer>
Definition at line 36 of file CompileUtils.h.
Constructor & Destructor Documentation
SimpleCompiler()
llvm::orc::SimpleCompiler::SimpleCompiler (TargetMachine & TM, ObjectCache * ObjCache = nullptr) inline
Construct a simple compile functor with the given target.
Definition at line 39 of file CompileUtils.h.
Member Function Documentation
operator()()
SimpleCompiler::CompileResult llvm::orc::SimpleCompiler::operator() (Module & M)
Compile a Module to an ObjectFile.
Definition at line 28 of file CompileUtils.cpp.
References llvm::TargetMachine::addPassesToEmitMC(), llvm::consumeError(), llvm::object::ObjectFile::createObjectFile(), llvm_unreachable, and llvm::legacy::PassManager::run().
setObjectCache()
void llvm::orc::SimpleCompiler::setObjectCache (ObjectCache * NewCache) inline
Set an ObjectCache to query before compiling.
Definition at line 43 of file CompileUtils.h.
Referenced by llvm::orc::OrcMCJITReplacement::setObjectCache().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/CompileUtils.h
lib/ExecutionEngine/Orc/CompileUtils.cpp