LLVM: llvm::object::IRObjectFile Class Reference
llvm::object::IRObjectFile Class Reference
#include "llvm/Object/IRObjectFile.h"
Public Types
using module_iterator = pointee_iterator< std::vector< std::unique_ptr< Module > >::const_iterator, const Module >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Public Member Functions
~IRObjectFile () override
void moveSymbolNext (DataRefImpl &Symb) const override
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
StringRef getTargetTriple () const
module_iterator module_begin () const
module_iterator module_end () const
iterator_range< module_iterator > modules () const
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
static Expected< MemoryBufferRef > findBitcodeInObject (const ObjectFile &Obj)
Finds and returns bitcode embedded in the given object file, or an error code if not found.
static Expected< MemoryBufferRef > findBitcodeInMemBuffer (MemoryBufferRef Object)
Finds and returns bitcode in the given memory buffer (which may be either a bitcode file or a native object file with embedded bitcode), or an error code if not found.
static Expected< std::unique_ptr< IRObjectFile > > create (MemoryBufferRef Object, LLVMContext &Context)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 31 of file IRObjectFile.h.
Member Typedef Documentation
module_iterator
using llvm::object::IRObjectFile::module_iterator = pointee_iterator<std::vector<std::unique_ptr<Module> >::const_iterator, const Module>
Definition at line 51 of file IRObjectFile.h.
Constructor & Destructor Documentation
~IRObjectFile()
IRObjectFile::~IRObjectFile () override
Definition at line 35 of file IRObjectFile.cpp.
Member Function Documentation
classof()
static bool llvm::object::IRObjectFile::classof (const Binary * v) inline static
Definition at line 47 of file IRObjectFile.h.
References llvm::object::Binary::isIR().
create()
Expected< std::unique_ptr< IRObjectFile > > IRObjectFile::create (MemoryBufferRef Object, LLVMContext & Context) static
Definition at line 110 of file IRObjectFile.cpp.
References Context, findBitcodeInMemBuffer(), llvm::getBitcodeModuleList(), and llvm::Expected< T >::takeError().
findBitcodeInMemBuffer()
Expected< MemoryBufferRef > IRObjectFile::findBitcodeInMemBuffer (MemoryBufferRef Object) static
Finds and returns bitcode in the given memory buffer (which may be either a bitcode file or a native object file with embedded bitcode), or an error code if not found.
Definition at line 90 of file IRObjectFile.cpp.
References llvm::file_magic::bitcode, llvm::file_magic::coff_object, llvm::object::ObjectFile::createObjectFile(), llvm::file_magic::elf_relocatable, llvm::errorCodeToError(), findBitcodeInObject(), llvm::identify_magic(), llvm::object::invalid_file_type, llvm::file_magic::macho_object, and llvm::Expected< T >::takeError().
Referenced by create(), llvm::LTOModule::getProducerString(), llvm::LTOModule::isBitcodeFile(), llvm::LTOModule::isBitcodeForTarget(), parseBitcodeFileImpl(), and llvm::object::readIRSymtab().
findBitcodeInObject()
Expected< MemoryBufferRef > IRObjectFile::findBitcodeInObject (const ObjectFile & Obj) static
Finds and returns bitcode embedded in the given object file, or an error code if not found.
Definition at line 74 of file IRObjectFile.cpp.
References llvm::object::bitcode_section_not_found, llvm::errorCodeToError(), llvm::object::Binary::getFileName(), llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
Referenced by llvm::object::SymbolicFile::createSymbolicFile(), and findBitcodeInMemBuffer().
getSymbolFlags()
uint32_t IRObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 50 of file IRObjectFile.cpp.
References getSym(), and llvm::ModuleSymbolTable::getSymbolFlags().
getTargetTriple()
StringRef IRObjectFile::getTargetTriple () const
Definition at line 67 of file IRObjectFile.cpp.
module_begin()
module_iterator llvm::object::IRObjectFile::module_begin () const inline
Definition at line 55 of file IRObjectFile.h.
Referenced by modules().
module_end()
module_iterator llvm::object::IRObjectFile::module_end () const inline
Definition at line 56 of file IRObjectFile.h.
Referenced by modules().
modules()
iterator_range< module_iterator > llvm::object::IRObjectFile::modules () const inline
Definition at line 58 of file IRObjectFile.h.
References llvm::make_range(), module_begin(), and module_end().
moveSymbolNext()
void IRObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 41 of file IRObjectFile.cpp.
References llvm::object::DataRefImpl::p.
printSymbolName()
Error IRObjectFile::printSymbolName (raw_ostream & OS, DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 45 of file IRObjectFile.cpp.
References getSym(), llvm::ModuleSymbolTable::printSymbolName(), and llvm::Error::success().
symbol_begin()
basic_symbol_iterator IRObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 54 of file IRObjectFile.cpp.
References llvm::ModuleSymbolTable::symbols().
symbol_end()
basic_symbol_iterator IRObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 60 of file IRObjectFile.cpp.
References llvm::ModuleSymbolTable::symbols().
The documentation for this class was generated from the following files:
include/llvm/Object/IRObjectFile.h
lib/Object/IRObjectFile.cpp