LLVM: llvm::JITEvaluatedSymbol Class Reference
llvm::JITEvaluatedSymbol Class Reference
Represents a symbol that has been evaluated to an address already.
#include "llvm/ExecutionEngine/JITSymbol.h"
Public Member Functions
JITEvaluatedSymbol ()=default
JITEvaluatedSymbol (std::nullptr_t)
Create a 'null' symbol.
JITEvaluatedSymbol (JITTargetAddress Address, JITSymbolFlags Flags)
Create a symbol for the given address and flags.
operator bool () const
An evaluated symbol converts to 'true' if its address is non-zero.
JITTargetAddress getAddress () const
Return the address of this symbol.
JITSymbolFlags getFlags () const
Return the flags for this symbol.
void setFlags (JITSymbolFlags Flags)
Set the flags for this symbol.
Detailed Description
Represents a symbol that has been evaluated to an address already.
Definition at line 189 of file JITSymbol.h.
Constructor & Destructor Documentation
JITEvaluatedSymbol() [1/3]
llvm::JITEvaluatedSymbol::JITEvaluatedSymbol () default
JITEvaluatedSymbol() [2/3]
llvm::JITEvaluatedSymbol::JITEvaluatedSymbol (std::nullptr_t) inline
Create a 'null' symbol.
Definition at line 194 of file JITSymbol.h.
JITEvaluatedSymbol() [3/3]
llvm::JITEvaluatedSymbol::JITEvaluatedSymbol (JITTargetAddress Address, JITSymbolFlags Flags) inline
Create a symbol for the given address and flags.
Definition at line 197 of file JITSymbol.h.
References llvm::Address.
Member Function Documentation
getAddress()
JITTargetAddress llvm::JITEvaluatedSymbol::getAddress () const inline
Return the address of this symbol.
Definition at line 204 of file JITSymbol.h.
Referenced by llvm::MCJIT::getPointerToFunction(), and llvm::orc::operator<<().
getFlags()
JITSymbolFlags llvm::JITEvaluatedSymbol::getFlags () const inline
Return the flags for this symbol.
Definition at line 207 of file JITSymbol.h.
Referenced by llvm::orc::operator<<().
operator bool()
llvm::JITEvaluatedSymbol::operator bool () const inline explicit
An evaluated symbol converts to 'true' if its address is non-zero.
Definition at line 201 of file JITSymbol.h.
setFlags()
void llvm::JITEvaluatedSymbol::setFlags (JITSymbolFlags Flags) inline
Set the flags for this symbol.
Definition at line 210 of file JITSymbol.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITSymbol.h