LLVM: llvm::SmallVectorTemplateBase< T, bool > Class Template Reference
llvm::SmallVectorTemplateBase< T, bool > Class Template Reference
SmallVectorTemplateBase<TriviallyCopyable = false> - This is where we put method implementations that are designed to work with non-POD-like T's.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorTemplateCommon< T, typename >.
Inherited by llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >, llvm::SmallVectorImpl< BasicBlock * >, llvm::SmallVectorImpl< BlockT * >, llvm::SmallVectorImpl< BoUpSLP::EdgeInfo >, llvm::SmallVectorImpl< llvm::MCFixup >, llvm::SmallVectorImpl< char >, llvm::SmallVectorImpl< llvm::cl::parser::OptionInfo >, llvm::SmallVectorImpl< std::pair< KeyT, ValueT > >, llvm::SmallVectorImpl< ScheduleData * >, llvm::SmallVectorImpl< Instruction * >, llvm::SmallVectorImpl< llvm::SUnit * >, llvm::SmallVectorImpl< LoopVector >, llvm::SmallVectorImpl< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorImpl< AllocaInfo >, llvm::SmallVectorImpl< ParamInfo >, llvm::SmallVectorImpl< CallInst * >, llvm::SmallVectorImpl< unsigned >, llvm::SmallVectorImpl< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults) >, llvm::SmallVectorImpl< llvm::ForwardedRegister >, llvm::SmallVectorImpl< MILOHDirective >, llvm::SmallVectorImpl< const llvm::MachineInstr * >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorImpl< llvm::BasicBlockInfo >, llvm::SmallVectorImpl< FCmpLibcallsList >, llvm::SmallVectorImpl< int >, llvm::SmallVectorImpl< MCPhysReg >, llvm::SmallVectorImpl< AnalysisID >, llvm::SmallVectorImpl< std::pair< AtomType, Form > >, llvm::SmallVectorImpl< FreeList * >, llvm::SmallVectorImpl< llvm::AsmPrinter::HandlerInfo >, llvm::SmallVectorImpl< llvm::AsmPrinter::XRayFunctionEntry >, llvm::SmallVectorImpl< llvm::WeakTrackingVH >, llvm::SmallVectorImpl< AbstractAttribute * >, llvm::SmallVectorImpl< VariableGEPIndex >, llvm::SmallVectorImpl< llvm::BitCodeAbbrevOp >, llvm::SmallVectorImpl< BitValue >, llvm::SmallVectorImpl< Block >, llvm::SmallVectorImpl< Weight >, llvm::SmallVectorImpl< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorImpl< BlockNode >, llvm::SmallVectorImpl< BlockMass >, llvm::SmallVectorImpl< std::string >, llvm::SmallVectorImpl< void * >, llvm::SmallVectorImpl< std::pair< void *, size_t > >, llvm::SmallVectorImpl< llvm::CCValAssign >, llvm::SmallVectorImpl< uint32_t >, llvm::SmallVectorImpl< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorImpl< ByValInfo >, llvm::SmallVectorImpl< llvm::LazyCallGraph::RefSCC * >, llvm::SmallVectorImpl< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorImpl< llvm::Register >, llvm::SmallVectorImpl< FileInfo >, llvm::SmallVectorImpl< CVGlobalVariable >, llvm::SmallVectorImpl< const llvm::DISubprogram * >, llvm::SmallVectorImpl< const llvm::DICompositeType * >, llvm::SmallVectorImpl< const llvm::DILocation * >, llvm::SmallVectorImpl< LocalVariable >, llvm::SmallVectorImpl< LexicalBlock * >, llvm::SmallVectorImpl< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * > >, llvm::SmallVectorImpl< LocalVarDefRange >, llvm::SmallVectorImpl< consthoist::ConstantInfo >, llvm::SmallVectorImpl< ConstantPoolEntry >, llvm::SmallVectorImpl< llvm::SDNode * >, llvm::SmallVectorImpl< llvm::Metadata * >, llvm::SmallVectorImpl< llvm::TypedTrackingMDRef >, llvm::SmallVectorImpl< llvm::DIEAbbrevData >, llvm::SmallVectorImpl< llvm::DILineInfo >, llvm::SmallVectorImpl< AttributeSpec >, llvm::SmallVectorImpl< llvm::DWARFFormValue >, llvm::SmallVectorImpl< LocationList >, llvm::SmallVectorImpl< llvm::DWARFDebugLoc::Entry >, llvm::SmallVectorImpl< llvm::DWARFDebugLoclists::Entry >, llvm::SmallVectorImpl< Entry >, llvm::SmallVectorImpl< llvm::DWARFDebugNames::NameIndex >, llvm::SmallVectorImpl< CompUnitEntry >, llvm::SmallVectorImpl< TypeUnitEntry >, llvm::SmallVectorImpl< AddressEntry >, llvm::SmallVectorImpl< SymTableEntry >, llvm::SmallVectorImpl< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > > >, llvm::SmallVectorImpl< unsigned char >, llvm::SmallVectorImpl< LayoutAlignElem >, llvm::SmallVectorImpl< PointerAlignElem >, llvm::SmallVectorImpl< FrameIndexExpr >, llvm::SmallVectorImpl< int64_t >, llvm::SmallVectorImpl< llvm::DICompileUnit * >, llvm::SmallVectorImpl< llvm::DISubprogram * >, llvm::SmallVectorImpl< llvm::DIGlobalVariableExpression * >, llvm::SmallVectorImpl< llvm::DIType * >, llvm::SmallVectorImpl< llvm::DIScope * >, llvm::SmallVectorImpl< llvm::DbgValueLoc >, llvm::SmallVectorImpl< llvm::DebugLocStream::List >, llvm::SmallVectorImpl< llvm::DebugLocStream::Entry >, llvm::SmallVectorImpl< llvm::Init * >, llvm::SmallVectorImpl< llvm::DiagnosticInfoOptimizationBase::Argument >, llvm::SmallVectorImpl< UpdateT >, llvm::SmallVectorImpl< NodePtr >, llvm::SmallVectorImpl< llvm::DomTreeNodeBase >, llvm::SmallVectorImpl< llvm::cfg::Update >, llvm::SmallVectorImpl< llvm::MachineInstr * >, llvm::SmallVectorImpl< NodeT * >, llvm::SmallVectorImpl< llvm::RangeSpan >, llvm::SmallVectorImpl< std::unique_ptr< llvm::DbgEntity > >, llvm::SmallVectorImpl< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * > >, llvm::SmallVectorImpl< llvm::DwarfExpression::Register >, llvm::SmallVectorImpl< std::unique_ptr< llvm::DwarfCompileUnit > >, llvm::SmallVectorImpl< llvm::RangeSpanList >, llvm::SmallVectorImpl< llvm::DbgVariable * >, llvm::SmallVectorImpl< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorImpl< llvm::Function * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GlobalVariable > >, llvm::SmallVectorImpl< llvm::DomainValue * >, llvm::SmallVectorImpl< LiveRegsDVInfo >, llvm::SmallVectorImpl< std::unique_ptr< llvm::Module > >, llvm::SmallVectorImpl< llvm::Value * >, llvm::SmallVectorImpl< llvm::ISD::InputArg >, llvm::SmallVectorImpl< std::pair< std::string, GCOVCoverage > >, llvm::SmallVectorImpl< T * >, llvm::SmallVectorImpl< llvm::FunctionLoweringInfo::LiveOutInfo >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCStrategy > >, llvm::SmallVectorImpl< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator > >, llvm::SmallVectorImpl< llvm::DenseMap >, llvm::SmallVectorImpl< llvm::GCNRegPressure >, llvm::SmallVectorImpl< llvm::GCOVEdge * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVEdge > >, llvm::SmallVectorImpl< llvm::GISelChangeObserver * >, llvm::SmallVectorImpl< std::pair< llvm::Value *, llvm::Constant * > >, llvm::SmallVectorImpl< llvm::Instruction * >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, unsigned > >, llvm::SmallVectorImpl< llvm::BasicBlock * >, llvm::SmallVectorImpl< MCOperand >, llvm::SmallVectorImpl< HexagonInstr >, llvm::SmallVectorImpl< NodeTy * >, llvm::SmallVectorImpl< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > > >, llvm::SmallVectorImpl< InlineGraphNode * >, llvm::SmallVectorImpl< uintptr_t >, llvm::SmallVectorImpl< const char * >, llvm::SmallVectorImpl< llvm::AllocaInst * >, llvm::SmallVectorImpl< llvm::CallSite >, llvm::SmallVectorImpl< llvm::PHINode * >, llvm::SmallVectorImpl< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorImpl< MachineInstr * >, llvm::SmallVectorImpl< RegUnitInfo >, llvm::SmallVectorImpl< BlockInterference >, llvm::SmallVectorImpl< llvm::AssertingVH< const llvm::BasicBlock > >, llvm::SmallVectorImpl< llvm::Loop * >, llvm::SmallVectorImpl< llvm::MCSymbol * >, llvm::SmallVectorImpl< llvm::SEHHandler >, llvm::SmallVectorImpl< Edge >, llvm::SmallVectorImpl< llvm::LazyCallGraph::Node * >, llvm::SmallVectorImpl< llvm::LegalizeRule >, llvm::SmallVectorImpl< SizeChangeStrategy >, llvm::SmallVectorImpl< SizeAndActionsVec >, llvm::SmallVectorImpl< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorImpl< llvm::LexicalScope * >, llvm::SmallVectorImpl< InsnRange >, llvm::SmallVectorImpl< llvm::LiveInterval * >, llvm::SmallVectorImpl< llvm::SlotIndex >, llvm::SmallVectorImpl< const uint32_t * >, llvm::SmallVectorImpl< std::pair< unsigned, unsigned > >, llvm::SmallVectorImpl< llvm::LiveRange * >, llvm::SmallVectorImpl< Segment >, llvm::SmallVectorImpl< VNInfo * >, llvm::SmallVectorImpl< LiveOutPair >, llvm::SmallVectorImpl< LiveInBlock >, llvm::SmallVectorImpl< llvm::LiveRange::Segment >, llvm::SmallVectorImpl< IndexMaskPair >, llvm::SmallVectorImpl< llvm::LiveVariables::VarInfo >, llvm::SmallVectorImpl< MBBInfo >, llvm::SmallVectorImpl< VPlanPtr >, llvm::SmallVectorImpl< RuntimePointerChecking::PointerCheck >, llvm::SmallVectorImpl< llvm::MCSection * >, llvm::SmallVectorImpl< llvm::AsmToken >, llvm::SmallVectorImpl< llvm::MCAsmParser::MCPendingError >, llvm::SmallVectorImpl< llvm::MCDwarfFile >, llvm::SmallVectorImpl< llvm::MCDataFragment * >, llvm::SmallVectorImpl< llvm::MCOperand >, llvm::SmallVectorImpl< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorImpl< llvm::MCLOHDirective >, llvm::SmallVectorImpl< PendingMCFixup >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorImpl< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::TypedTrackingMDRef > >, llvm::SmallVectorImpl< Attachment >, llvm::SmallVectorImpl< llvm::StringRef >, llvm::SmallVectorImpl< llvm::MachineBasicBlock * >, llvm::SmallVectorImpl< CriticalEdge >, llvm::SmallVectorImpl< std::pair< int, int64_t > >, llvm::SmallVectorImpl< VariableDbgInfo >, llvm::SmallVectorImpl< llvm::MachineOperand >, llvm::SmallVectorImpl< std::pair< llvm::PointerUnion, llvm::MachineOperand * > >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::SmallVector< unsigned, 4 > > >, llvm::SmallVectorImpl< LLT >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorImpl< std::string * >, llvm::SmallVectorImpl< llvm::MemoryDepChecker::Dependence >, llvm::SmallVectorImpl< DefPath >, llvm::SmallVectorImpl< llvm::WeakVH >, llvm::SmallVectorImpl< llvm::AssertingVH< llvm::MemoryPhi > >, llvm::SmallVectorImpl< Inst >, llvm::SmallVectorImpl< bool >, llvm::SmallVectorImpl< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorImpl< const llvm::Value * >, llvm::SmallVectorImpl< llvm::Pass * >, llvm::SmallVectorImpl< llvm::PMDataManager * >, llvm::SmallVectorImpl< llvm::ImmutablePass * >, llvm::SmallVectorImpl< llvm::AsmRewrite >, llvm::SmallVectorImpl< std::function< void(llvm::PassManager &, OptimizationLevel)> >, llvm::SmallVectorImpl< std::function< void(llvm::PassManager &)> >, llvm::SmallVectorImpl< std::function< void(llvm::AnalysisManager &)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorImpl< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >, bool VerifyEachPass, bool DebugLogging)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)> >, llvm::SmallVectorImpl< InsertedPass >, llvm::SmallVectorImpl< llvm::unique_function< BeforePassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterPassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterPassInvalidatedFunc > >, llvm::SmallVectorImpl< llvm::unique_function< BeforeAnalysisFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterAnalysisFunc > >, llvm::SmallVectorImpl< ValueInfo >, llvm::SmallVectorImpl< llvm::AssertingVH< llvm::Function > >, llvm::SmallVectorImpl< llvm::PredicateBase * >, llvm::SmallVectorImpl< PrintModuleDesc >, llvm::SmallVectorImpl< llvm::Type * >, llvm::SmallVectorImpl< LiveRegsDefInfo >, llvm::SmallVectorImpl< MBBDefsInfo >, llvm::SmallVectorImpl< llvm::SMLoc >, llvm::SmallVectorImpl< llvm::RecordVal >, llvm::SmallVectorImpl< std::pair< llvm::Record *, llvm::SMRange > >, llvm::SmallVectorImpl< std::unique_ptr< InsertPoint > >, llvm::SmallVectorImpl< ScavengedInfo >, llvm::SmallVectorImpl< llvm::RegisterMaskPair >, llvm::SmallVectorImpl< llvm::EVT >, llvm::SmallVectorImpl< llvm::MVT >, llvm::SmallVectorImpl< uint64_t >, llvm::SmallVectorImpl< SID >, llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >, llvm::SmallVectorImpl< SectionEntry >, llvm::SmallVectorImpl< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorImpl< llvm::RuntimePointerChecking::PointerInfo >, llvm::SmallVectorImpl< llvm::RuntimePointerChecking::CheckingPtrGroup >, llvm::SmallVectorImpl< PointerCheck >, llvm::SmallVectorImpl< SCEVInsertPointGuard * >, llvm::SmallVectorImpl< const llvm::SCEV * >, llvm::SmallVectorImpl< const llvm::SCEVPredicate * >, llvm::SmallVectorImpl< llvm::SDDbgValue * >, llvm::SmallVectorImpl< llvm::SDDbgLabel * >, llvm::SmallVectorImpl< llvm::SIMachineFunctionInfo::SGPRSpillVGPRCSR >, llvm::SmallVectorImpl< llvm::SMFixIt >, llvm::SmallVectorImpl< llvm::SelectInst * >, llvm::SmallVectorImpl< RewriteInfo >, llvm::SmallVectorImpl< llvm::Use * >, llvm::SmallVectorImpl< PhiT * >, llvm::SmallVectorImpl< llvm::SDep >, llvm::SmallVectorImpl< ExitNotTakenInfo >, llvm::SmallVectorImpl< RootData >, llvm::SmallVectorImpl< TreeData >, llvm::SmallVectorImpl< SMSNode >, llvm::SmallVectorImpl< std::pair< llvm::SUnit *, llvm::SUnit * > >, llvm::SmallVectorImpl< llvm::sys::MemoryBlock >, llvm::SmallVectorImpl< FreeMemBlock >, llvm::SmallVectorImpl< llvm::SDValue >, llvm::SmallVectorImpl< const llvm::GCRelocateInst * >, llvm::SmallVectorImpl< IdxMBBPair >, llvm::SmallVectorImpl< ValueT >, llvm::SmallVectorImpl< llvm::BlockFrequency >, llvm::SmallVectorImpl< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorImpl< Location >, llvm::SmallVectorImpl< LiveOutReg >, llvm::SmallVectorImpl< const llvm::CallInst * >, llvm::SmallVectorImpl< const Value * >, llvm::SmallVectorImpl< llvm::SmallPtrSet< llvm::SUnit *, 4 > >, llvm::SmallVectorImpl< llvm::SmallVector< int, 4 > >, llvm::SmallVectorImpl< BitTestCase >, llvm::SmallVectorImpl< llvm::DefsetRecord * >, llvm::SmallVectorImpl< llvm::ISD::OutputArg >, llvm::SmallVectorImpl< llvm::Timer * >, llvm::SmallVectorImpl< llvm::Entry >, llvm::SmallVectorImpl< llvm::TruncInst * >, llvm::SmallVectorImpl< uint8_t >, llvm::SmallVectorImpl< llvm::VPBlockBase * >, llvm::SmallVectorImpl< llvm::VPBasicBlock * >, llvm::SmallVectorImpl< llvm::VPValue * >, llvm::SmallVectorImpl< llvm::VPUser * >, llvm::SmallVectorImpl< VPBlockBase * >, llvm::SmallVectorImpl< MultiNodeOpTy >, llvm::SmallVectorImpl< std::pair< uint64_t, bool > >, llvm::SmallVectorImpl< llvm::CxxUnwindMapEntry >, llvm::SmallVectorImpl< llvm::WinEHTryBlockMapEntry >, llvm::SmallVectorImpl< llvm::SEHUnwindMapEntry >, llvm::SmallVectorImpl< llvm::ClrEHUnwindMapEntry >, llvm::SmallVectorImpl< llvm::WinEHHandlerType >, llvm::SmallVectorImpl< llvm::cflaa::ExternalRelation >, llvm::SmallVectorImpl< llvm::cflaa::ExternalAttribute >, llvm::SmallVectorImpl< llvm::cl::OptionCategory * >, llvm::SmallVectorImpl< llvm::cl::Option * >, llvm::SmallVectorImpl< llvm::cl::OptionEnumValue >, llvm::SmallVectorImpl< llvm::ArrayRef< uint8_t > >, llvm::SmallVectorImpl< llvm::codeview::TypeIndex >, llvm::SmallVectorImpl< RecordLimit >, llvm::SmallVectorImpl< llvm::codeview::GloballyHashedType >, llvm::SmallVectorImpl< std::pair< uint32_t, llvm::codeview::TypeIndex > >, llvm::SmallVectorImpl< ConstantUser >, llvm::SmallVectorImpl< RebasedConstantInfo >, llvm::SmallVectorImpl< llvm::CoroEndInst * >, llvm::SmallVectorImpl< llvm::CoroSizeInst * >, llvm::SmallVectorImpl< llvm::CoroSuspendInst * >, llvm::SmallVectorImpl< const llvm::coverage::CoverageSegment * >, llvm::SmallVectorImpl< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorImpl< llvm::fuzzerop::SourcePred >, llvm::SmallVectorImpl< State >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::HardwareUnit > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::Instruction > >, llvm::SmallVectorImpl< llvm::mca::WriteDescriptor >, llvm::SmallVectorImpl< llvm::mca::ReadDescriptor >, llvm::SmallVectorImpl< std::pair< uint64_t, llvm::mca::ResourceUsage > >, llvm::SmallVectorImpl< llvm::mca::WriteState >, llvm::SmallVectorImpl< llvm::mca::ReadState >, llvm::SmallVectorImpl< std::pair< ResourceRef, llvm::mca::ResourceCycles > >, llvm::SmallVectorImpl< llvm::mca::MemoryGroup * >, llvm::SmallVectorImpl< llvm::mca::InstRef >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::Stage > >, llvm::SmallVectorImpl< RegisterMappingTracker >, llvm::SmallVectorImpl< std::pair< llvm::mca::ReadState *, int > >, llvm::SmallVectorImpl< SectionInfo >, llvm::SmallVectorImpl< NodeState >, llvm::SmallVectorImpl< LoadCommandInfo >, llvm::SmallVectorImpl< StringRef >, llvm::SmallVectorImpl< Arg * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorImpl< InjectedSourceDescriptor >, llvm::SmallVectorImpl< size_t >, llvm::SmallVectorImpl< llvm::remarks::Argument >, llvm::SmallVectorImpl< llvm::safestack::StackColoring::LiveRange >, llvm::SmallVectorImpl< StackRegion >, llvm::SmallVectorImpl< StackObject >, llvm::SmallVectorImpl< const SamplesWithLoc * >, llvm::SmallVectorImpl< std::unique_ptr< TreeEntry > >, llvm::SmallVectorImpl< unique_value >, llvm::SmallVectorImpl< ExternalUser >, llvm::SmallVectorImpl< Value * >, llvm::SmallVectorImpl< llvm::slpvectorizer::BoUpSLP::EdgeInfo >, llvm::SmallVectorImpl< SmallVector< Value *, 8 > >, llvm::SmallVectorImpl< llvm::SmallVector >, llvm::SmallVectorImpl< Slice >, llvm::SmallVectorImpl< Slice * >, llvm::SmallVectorImpl< IntrusiveRefCntPtr< FileSystem > >, llvm::SmallVectorImpl< ValType >, llvm::SmallVectorImpl< TrieNode * >, llvm::SmallVectorImpl< SimpleKey >, and llvm::SmallVectorImpl< T >.
Public Member Functions
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinCapacity, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
Protected Member Functions inherited from llvm::SmallVectorBase
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void grow_pod (void *FirstEl, size_t MinCapacity, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Static Protected Member Functions
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Additional Inherited Members
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from llvm::SmallVectorBase
void * BeginX
unsigned Size = 0
unsigned Capacity
Detailed Description
template<typename T, bool = is_trivially_copyable<T>::value>
class llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase<TriviallyCopyable = false> - This is where we put method implementations that are designed to work with non-POD-like T's.
Definition at line 179 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T , bool = is_trivially_copyable<T>::value> llvm::SmallVectorTemplateBase< T, bool >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 181 of file SmallVector.h.
Member Function Documentation
destroy_range()
template<typename T , bool = is_trivially_copyable<T>::value> static void llvm::SmallVectorTemplateBase< T, bool >::destroy_range (T * S, T * E) inline static protected
Definition at line 183 of file SmallVector.h.
References E.
Referenced by llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorImpl< T >::erase(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVector< T, N >::~SmallVector().
grow()
template<typename T , bool TriviallyCopyable> void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::grow (size_t MinSize = 0) protected
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 233 of file SmallVector.h.
References llvm::NextPowerOf2(), llvm::report_bad_alloc_error(), and llvm::safe_malloc().
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorImpl< T >::swap().
pop_back()
template<typename T , bool = is_trivially_copyable<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::pop_back () inline
Definition at line 225 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorBase::set_size(), and llvm::SmallVectorBase::size().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::MipsInstrInfo::analyzeBranch(), llvm::Annotations::Annotations(), llvm::A57ChainingConstraint::apply(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), BuildSubAggregate(), llvm::SmallString< InternalLen >::c_str(), llvm::c_str(), CalcNodeSethiUllmanNumber(), canPaddingBeAccessed(), canRewriteGEPAsOffset(), llvm::ArrayRecycler< T, Align >::clear(), ComputePostOrders(), computeUnlikelySuccessors(), llvm::ConstantFoldTerminator(), llvm::convertUTF8ToUTF16String(), llvm::sys::fs::createUniquePath(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ScheduleDAGSDNodes::dumpNode(), EmitAddTreeOfValues(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::SmallVectorImpl< T >::erase(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::cl::ExpandResponseFiles(), llvm::ScalarEvolution::getAddRecExpr(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), getPrefixes(), llvm::Intrinsic::getType(), getVFSEntries(), inlineCallsImpl(), llvm::SmallSet< T, N, C >::insert(), llvm::GCOVBlock::lookForCircuit(), llvm::WebAssemblyMCInstLower::lower(), llvm::object::ExportEntry::moveNext(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::IntervalMapImpl::Path::pop(), llvm::PriorityWorklist< T, VectorT, MapT >::pop_back(), llvm::LiveRangeEdit::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MCStreamer::PopSection(), llvm::WebAssemblyInstPrinter::printInst(), processHeaderPhiOperands(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::sys::path::remove_dots(), llvm::MemoryDependenceResults::removeInstruction(), removeRedundantBlockingStores(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), sortLocalVars(), swapMIOperands(), llvm::Twine::toNullTerminatedStringRef(), and llvm::LoopTraversal::traverse().
push_back() [1/2]
template<typename T , bool = is_trivially_copyable<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::push_back (const T & Elt) inline
Definition at line 211 of file SmallVector.h.
References llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), LLVM_UNLIKELY, llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::opt::Option::accept(), llvm::BitCodeAbbrev::Add(), llvm::InstCombineWorklist::Add(), llvm::LiveRangeUpdater::add(), llvm::PMDataManager::add(), llvm::SDDbgInfo::add(), llvm::MemoryDepChecker::addAccess(), AddAliasScopeMetadata(), llvm::opt::ArgList::AddAllArgsTranslated(), addAllGlobalValueUsers(), addBlockAndPredsToSet(), addBoundsChecking(), llvm::VPlan::addCBV(), AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::SchedDFSImpl::addConnection(), llvm::MCLOHContainer::addDirective(), llvm::ConstantPool::addEntry(), llvm::SMDiagnostic::addFixIt(), llvm::DIInliningInfo::addFrame(), AddGlue(), llvm::mca::Context::addHardwareUnit(), addHints(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::pdb::PDBFileBuilder::addInjectedSource(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::CCState::addInRegsParamInfo(), llvm::FoldingSetNodeID::AddInteger(), llvm::LiveIntervals::addKillFlags(), llvm::MachineFunction::addLandingPad(), llvm::GCOVBlock::addLine(), llvm::SpillPlacement::Node::addLink(), llvm::LiveRangeCalc::addLiveInBlock(), llvm::CCState::addLoc(), addLocIfNotPresent(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::MachineInstr::addMemOperand(), llvm::InterleaveGroup< llvm::Instruction >::addMetadata(), llvm::DbgVariable::addMMIEntry(), llvm::PPCFunctionInfo::addMustSaveCR(), addMustTailToCoroResumes(), llvm::safestack::StackLayout::addObject(), llvm::GISelObserverWrapper::addObserver(), llvm::lowertypetests::BitSetBuilder::addOffset(), llvm::MCInst::addOperand(), llvm::VPUser::addOperand(), llvm::RuntimePointerChecking::CheckingPtrGroup::addPointer(), llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), addRange(), AddReachableCodeToWorklist(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), addRegLanes(), llvm::AnalysisUsage::addRequiredID(), llvm::AnalysisUsage::addRequiredTransitiveID(), llvm::DominatorTreeBase< NodeT, IsPostDom >::addRoot(), AddRuntimeUnrollDisableMetaData(), llvm::RegScavenger::addScavengingFrameIndex(), llvm::DwarfFile::addScopeLabel(), addStackMapLiveVars(), llvm::FoldingSetNodeID::AddString(), llvm::addStringMetadataToLoop(), llvm::Record::addSuperClass(), llvm::AMDGPUTargetLowering::addTokenForArgument(), addToListsIfDependent(), llvm::SSAUpdaterBulk::AddUse(), llvm::AnalysisUsage::addUsedIfAvailable(), llvm::AnalysisUsage::addUsedIfAvailableID(), llvm::consthoist::ConstantCandidate::addUser(), llvm::Record::addValue(), llvm::SSAUpdaterBulk::AddVariable(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), advanceToNextLeafType(), aliasSameBasePointerGEPs(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::StatepointLoweringState::allocateStackSlot(), allUsersAreInFunction(), llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::MipsInstrInfo::analyzeBranch(), llvm::LanaiInstrInfo::analyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::SystemZCCState::AnalyzeFormalArguments(), analyzeLoopUnrollCost(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::annotateValueSite(), llvm::opt::ArgList::append(), llvm::LiveRange::append(), llvm::RegsForValue::append(), llvm::HexagonShuffler::append(), llvm::sys::path::append(), llvm::DebugLoc::appendInlinedAt(), llvm::Record::appendLoc(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::DIExpression::appendOffset(), appendSpeculatableOperands(), appendToGlobalArray(), llvm::DIExpression::appendToStack(), llvm::A57ChainingConstraint::apply(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::MemorySSAUpdater::applyUpdates(), llvm::DomTreeUpdater::applyUpdatesPermissive(), llvm::opt::Arg::Arg(), llvm::LiveRange::assign(), llvm::AVRDAGToDAGISel::select< AVRISD::CALL >(), BatchCommitValueTo(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::codeview::CodeViewRecordIO::beginRecord(), llvm::object::BindRebaseSegInfo::BindRebaseSegInfo(), bitTrackingDCE(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::rdf::DataFlowGraph::build(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::FileCheck::buildCheckPrefixRegex(), buildClonedLoopBlocks(), buildClonedLoops(), BuildExactSDIV(), buildFrameType(), llvm::coro::Shape::buildFrom(), buildFromShuffleMostly(), llvm::VPlanSlp::buildGraph(), llvm::LazyCallGraph::buildRefSCCs(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), BuildSubAggregate(), llvm::TargetLowering::BuildUDIV(), llvm::MachineIRBuilder::buildUnmerge(), llvm::LoopVectorizationPlanner::buildVPlans(), llvm::SmallString< InternalLen >::c_str(), llvm::c_str(), CalcNodeSethiUllmanNumber(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), calculateCXXStateNumbers(), llvm::calculateDbgEntityHistory(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), CalculateTailCallArgDest(), llvm::FileCheck::CanonicalizeFile(), canonicalizePHIOperands(), canPaddingBeAccessed(), canRewriteGEPAsOffset(), CC_AArch64_Custom_Block(), CC_AArch64_Custom_Stack_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), chainLoadsAndStoresForMemcpy(), llvm::MemorySSAUpdater::changeCondBranchToUnconditionalTo(), llvm::MemorySSAUpdater::changeToUnreachable(), llvm::HexagonShuffler::check(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), llvm::RuntimePointerChecking::CheckingPtrGroup::CheckingPtrGroup(), clearAssumptionsOfUsers(), llvm::FileCheckPatternContext::clearLocalVars(), clobberRegEntries(), CloneAliasScopeMetadata(), llvm::CloneAndPruneIntoFromInst(), cloneConstantExprWithNewAddressSpace(), llvm::CloneFunctionInto(), cloneInstructionWithNewAddressSpace(), cloneLoopBlocks(), cloneLoopNest(), llvm::cloneLoopWithPreheader(), CloneNodeWithValues(), llvm::LexicalScope::closeInsnRange(), CollectAddOperandsWithScales(), collectCastsToIgnore(), llvm::collectChildrenInLoop(), llvm::collectCmpOps(), collectConcatOps(), llvm::MachineInstr::collectDebugValues(), collectEHScopeMembers(), collectHomogenousInstGraphLoopInvariants(), llvm::PMTopLevelManager::collectLastUses(), collectMultiplyFactors(), collectPHIs(), llvm::PMDataManager::collectRequiredAndUsedAnalyses(), CollectSubexprs(), collectSupportedLoops(), collectTransitivePredecessors(), collectValuesToDemote(), collectVirtualRegUses(), llvm::colorEHFunclets(), CombineBaseUpdate(), combineBVOfConsecutiveLoads(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineExtractVectorElt(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), combineShuffleOfScalars(), combineShuffleOfSplatVal(), combineStore(), combineToConsecutiveLoads(), combineToExtendVectorInReg(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::FunctionComparator::compare(), compressAnnotation(), llvm::ScalarEvolution::computeAccessFunctions(), llvm::EHStreamer::computeActionsTable(), computeBlocksDominatingExits(), computeCalleeSaveRegisterPairs(), llvm::EHStreamer::computeCallSiteTable(), llvm::computeDeadSymbols(), llvm::MCCodePaddingPolicy::computeFirstWindowPenaltyWeight(), computeFreeStackSlots(), llvm::computeLegalValueVTs(), ComputeLiveInBlocks(), computeLiveOuts(), ComputePostOrders(), ComputePTXValueVTs(), llvm::MCCodePaddingPolicy::computeRangePenaltyWeight(), llvm::computeSignatureVTs(), llvm::LiveInterval::computeSubRangeUndefs(), computeUnlikelySuccessors(), llvm::computeValueLLTs(), llvm::ComputeValueVTs(), llvm::concatenateVectors(), ConnectProlog(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldTerminator(), ConstHasGlobalValuePredicate(), constructRetValue(), llvm::DwarfCompileUnit::constructScopeDIE(), convert_i1_to_i8(), llvm::TypedInit::convertInitializerBitRange(), llvm::ListInit::convertInitializerTo(), llvm::TypedInit::convertInitListSlice(), llvm::ListInit::convertInitListSlice(), convertShiftLeftToScale(), llvm::convertUTF8ToUTF16String(), createBSWAPShuffleMask(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), createDevirtTriggerFunc(), llvm::DIExpression::createFragmentExpression(), llvm::MDBuilder::createFunctionEntryCount(), createMMXBuildVector(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::createReplicatedMask(), createRetBitCast(), createRetPHINode(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), llvm::sys::fs::createUniquePath(), llvm::LiveRange::createValueCopy(), llvm::mca::ResourceManager::cycleEvent(), llvm::DecodeBLENDMask(), llvm::DecodeEXTRQIMask(), DecodeFixedType(), DecodeIITType(), llvm::DecodeInsertElementMask(), llvm::DecodeINSERTPSMask(), llvm::DecodeINSERTQIMask(), llvm::DecodeMOVDDUPMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), DecodePALIGNRMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodePSLLDQMask(), llvm::DecodePSRLDQMask(), llvm::DecodePSWAPMask(), llvm::DecodeSHUFPMask(), llvm::DecodeSubVectorBroadcast(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVALIGNMask(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::decodeVSHUF64x2FamilyMask(), llvm::DecodeZeroMoveLowMask(), deduceFunctionAttributeInRPO(), llvm::GISelWorkList< N >::deferred_insert(), llvm::VPBlockBase::deleteCFG(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), deleteDeadInstruction(), llvm::deleteDeadLoop(), llvm::DeleteDeadPHIs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DependenceInfo::depends(), llvm::DetatchDeadBlocks(), llvm::ARMFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), llvm::RegPressureTracker::discoverLiveInOrOut(), discoverTypeIndices(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::AsmPrinter::doFinalization(), DoInitialMatch(), doPromotion(), llvm::AppleAcceleratorTable::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::SMSchedule::earliestCycleInChain(), eliminateDeadSwitchCases(), eliminateLoadsAcrossLoops(), eliminateRecursiveTailCall(), llvm::DwarfStringPool::emit(), llvm::AsmPrinter::EmitConstantPool(), emitDarwinBCHeaderAndTrailer(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::emitGlobalGOTEquivs(), llvm::BufferByteStreamer::EmitInt8(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), emitNullTerminatedSymbolName(), llvm::SystemZFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), emitSignedInt64(), llvm::BufferByteStreamer::EmitSLEB128(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::BufferByteStreamer::EmitULEB128(), EmitUnrolledSetTag(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::CodeViewContext::encodeDefRange(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), llvm::BitstreamCursor::EnterSubBlock(), llvm::rdf::DeadCodeElimination::erase(), llvm::Evaluator::EvaluateBlock(), evaluateInDifferentElementOrder(), EvaluateStoreInto(), llvm::InstructionSelector::executeMatchTable(), ExpandBVWithShuffles(), ExpandCryptoAEK(), llvm::AArch64_IMM::expandMOVImm(), llvm::AArch64_IMM::expandMOVImmSimple(), llvm::cl::ExpandResponseFiles(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), explicifyGuards(), ExtendToType(), ExtendUsesToFormExtLoad(), llvm::DWARFAbbreviationDeclaration::extract(), llvm::DbgVariableLocation::extractFromMachineInstruction(), extractLoadMMOs(), extractStoreMMOs(), extractValues(), llvm::LegalizerHelper::fewerElementsVectorBasic(), llvm::LegalizerHelper::fewerElementsVectorCasts(), llvm::LegalizerHelper::fewerElementsVectorCmp(), llvm::LegalizerHelper::fewerElementsVectorImplicitDef(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorSelect(), llvm::AMDGPU::fillValidArchListAMDGCN(), llvm::AMDGPU::fillValidArchListR600(), llvm::AArch64::fillValidCPUArchList(), llvm::ARM::fillValidCPUArchList(), llvm::DIBuilder::finalize(), llvm::finalizeBundle(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::MCJIT::finalizeObject(), findAffectedValues(), llvm::CodeExtractor::findAllocas(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), findBasePointer(), findBestInsertionSet(), findBuildAggregate(), findBuildVector(), findCallsAtConstantOffset(), llvm::findDbgUsers(), llvm::findDbgValues(), llvm::findDefsUsedOutsideOfLoop(), llvm::objcarc::FindDependencies(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::FindFunctionBackedges(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), findIBRPredecessor(), FindMostPopularDest(), findNonImmUse(), findPartitions(), findPotentialBlockers(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::FindPredecessorBlocks(), findProfitablePHIs(), findRefEdges(), findRematerializableChainToBasePointer(), findReturnsToZap(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), FindSingleUseMultiplyFactors(), findSRegBaseAndIndex(), llvm::MachineInstr::findTiedOperandIdx(), findUnconditionalPreds(), llvm::SplitEditor::finish(), firstRealType(), fixPhis(), llvm::BinOpInit::Fold(), FoldBitCast(), llvm::FoldBranchToCommonDest(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldReturnAndProcessPred(), ForeachDagApply(), llvm::ScalarEvolution::forgetValue(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), llvm::FunctionComparator::functionHash(), FusionCandidate::FusionCandidate(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::RISCVMatInt::generateInstSeq(), generatePoisonChecks(), generatePoisonChecksForBinOp(), GenerateTBL(), genericValueTraversal(), genFusedMultiply(), genMaddR(), genShuffleBland(), llvm::DagInit::get(), llvm::AttributeList::get(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get(), llvm::LegalizerInfo::getAction(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::SITargetLowering::getAddrModeArguments(), llvm::ScalarEvolution::getAnyExtendExpr(), getArrayElements(), getBaseType(), llvm::HexagonInstrInfo::getBranchingInstrs(), GetBranchWeights(), llvm::SelectionDAG::getCALLSEQ_END(), getCastsForInductionPHI(), llvm::SelectionDAG::getConstant(), getConstantVector(), llvm::getConstantVRegValWithLookThrough(), getConstVector(), getCoroBeginPredBlocks(), getDataDeps(), llvm::GlobalVariable::getDebugInfo(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), llvm::Record::getDirectSuperClasses(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), llvm::getEHScopeMembership(), GetEHSpillList(), getExactSDiv(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::RegionBase< Tr >::getExitingBlocks(), llvm::cl::generic_parser_base::getExtraOptionNames(), getFauxShuffleMask(), getFMAPatterns(), llvm::Evaluator::getFormalParams(), getFPSequenceIfElementsMatch(), llvm::X86AddressMode::getFullAddress(), getGEPSmallConstantIntOffsetV(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), llvm::CallBrInst::getIndirectDests(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::RegisterBankInfo::getInstrPossibleMappings(), getIntOperandFromRegisterString(), llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), getIntSequenceIfElementsMatch(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::getLibcallSignature(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::pdb::PDBContext::getLineInfoForAddressRange(), getLoadsAndStores(), getLogBase2(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::TargetInstrInfo::getMachineCombinerPatterns(), getMaddPatterns(), llvm::ManagedStringPool::getManagedString(), getMatchingEHPad(), getMemcpyLoadsAndStores(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::SelectionDAG::getMergeValues(), llvm::SourceMgr::GetMessage(), llvm::Module::getModuleFlagsMetadata(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), getNaturalGEPWithType(), GetNegatedExpression(), getNegativeIsTrueBoolVec(), getNewSource(), llvm::LiveRange::getNextValue(), llvm::SelectionDAG::getNode(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), getNotRelocatableInstructions(), llvm::ScalarEvolution::getNotSCEV(), getOffsetFromIndices(), getOperands(), llvm::MipsTargetLowering::getOpndList(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::DwarfUnit::getParentContextString(), getPHIDeps(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPreStartForExtend(), getQualifiedNameComponents(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), GetRegistersForValue(), llvm::RegsForValue::getRegsAndSizes(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::rdf::DataFlowGraph::getRelatedRefs(), getRelevantOperands(), llvm::CCState::getRemainingRegParmsForType(), llvm::GetReturnInfo(), getSchedRegions(), llvm::GetShadowBytes(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), GetSpillList(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::InnerLoopVectorizer::getStepVector(), llvm::ConstantDataArray::getString(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), getTargetShuffleMaskIndices(), getTargetVShiftByConstNode(), llvm::ScalarEvolution::getTruncateExpr(), llvm::Intrinsic::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnderlyingObjectsForInstr(), llvm::getUniqueExitBlocksHelper(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::yaml::ScalarNode::getValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), getVFSEntries(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ScalarEvolution::getZeroExtendExpr(), group2Shuffle(), llvm::IntEqClasses::grow(), llvm::MipsCallLowering::MipsHandler::handle(), handleBaseClass(), handleDataMember(), handleFree(), HandleInlinedEHPad(), handleListContinuation(), HandleMergeInputChains(), handleMethodOverloadList(), handleNestedType(), handleNewDebugValue(), handleOneMethod(), handleOverloadedMethod(), handlePhiDef(), handlePointer(), handleStaticDataMember(), handleVFPtr(), handleVirtualBaseClass(), hasCallsInBlocksBetween(), hashValueMapping(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::SDNode::hasPredecessor(), llvm::SDNode::hasPredecessorHelper(), hasRegisterDependency(), llvm::TargetInstrInfo::hasStoreToStackSlot(), hoistAndMergeSGPRInits(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator(), incDecVectorConstant(), llvm::ValueEnumerator::incorporateFunction(), llvm::SwitchInstProfUpdateWrapper::init(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), llvm::InitLLVM::InitLLVM(), inlineCallsImpl(), llvm::InlineFunction(), inlineLoopID(), llvm::SmallSet< T, N, C >::insert(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::GISelWorkList< N >::insert(), llvm::slpvectorizer::BoUpSLP::BlockScheduling::ReadyList::insert(), llvm::MDGlobalAttachmentMap::insert(), llvm::MemorySSAUpdater::insertDef(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), insertParsePoints(), llvm::InsertPreheaderForLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), llvm::SIInstrInfo::insertSelect(), insertSpills(), insertTrivialPHIs(), insertUseHolderAfter(), llvm::xray::Profile::internPath(), llvm::intersectAccessGroups(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::OuterAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::invalidate(), llvm::PhiValues::invalidateValue(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), isEphemeralValueOf(), isFusableLoadOpStorePattern(), isGEPFoldable(), isHorizontalBinOp(), isKnownNonNullFromDominatingCondition(), isLeakCheckerRoot(), isNonEscapingGlobalNoAliasWithLoad(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantGlobal(), llvm::isOverflowIntrinsicNoWrap(), isPointerValueDeadOnEntryToFunction(), llvm::isPotentiallyReachable(), isProfitableToFoldUnconditional(), isSafeToMove(), isSafeToPromoteArgument(), isSafeToSpeculatePHIUsers(), IsStoredObjCPointer(), isSuccOrder(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), isVectorPromotionViable(), llvm::SpillPlacement::iterate(), llvm::LiveRange::join(), llvm::SMSchedule::latestCycleInChain(), llvm::LazyCallGraph::LazyCallGraph(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LinearizeExprTree(), LLVMMDNodeInContext(), llvm::coverage::CoverageMapping::load(), llvm::X86InstrInfo::loadRegFromAddr(), llvm::GCOVBlock::lookForCircuit(), LookupNearestOption(), llvm::WebAssemblyMCInstLower::lower(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), lowerBuildVectorToBitOp(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCTPOP(), llvm::LowerDbgDeclare(), lowerDSPIntr(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerGuardIntrinsic(), lowerIncomingStatepointValue(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), LowerLoad(), LowerMemOpCallTo(), LowerMUL(), LowerMULH(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerShift(), lowerShuffleAsBlend(), lowerStatepointMetaArgs(), LowerUINT_TO_FP_i64(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), lowerWidenableCondition(), makeAllConstantUsesInstructions(), llvm::makeFollowupLoopID(), llvm::opt::InputArgList::MakeIndex(), llvm::makePostTransformationMetadata(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::AbstractAttribute::manifest(), markAliveBlocks(), markTails(), llvm::Regex::match(), matchBitOpReduction(), matchIntrinsicType(), llvm::MCDwarfCallFrameFragment::MCDwarfCallFrameFragment(), llvm::MCLEBFragment::MCLEBFragment(), llvm::MCStreamer::MCStreamer(), llvm::rdf::CodeNode::members_if(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeConstants(), llvm::SelectionDAG::MorphNodeTo(), moveBelowOrigChain(), moveLCSSAPhis(), moveSpillUsesAfterCoroBegin(), moveUp(), mustExecuteUBIfPoisonOnPathTo(), llvm::InjectorIRStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::SelectionDAG::mutateStrictFPToFP(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::EscapeEnumerator::Next(), llvm::Triple::normalize(), NormalizeBuildVector(), operandWithNewAddressSpaceOrCreateUndef(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::SmallString< InternalLen >::operator+=(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::MemorySSA::OptimizeUses::optimizeUses(), optimizeVectorResize(), llvm::vfs::OverlayFileSystem::OverlayFileSystem(), packCmovGroup(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugMacro::parse(), llvm::DWARFDebugLoclists::parse(), parseBackslash(), llvm::cl::ParseCommandLineOptions(), llvm::remarks::ParsedStringTable::ParsedStringTable(), llvm::cl::ParseEnvironmentOptions(), llvm::parseExternFuncCallArgs(), ParseFunctionArgs(), llvm::parseFunctionArgs(), parseOperands(), llvm::MIRParserImpl::parseRegisterInfo(), parseSegmentLoadCommand(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), PerformBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), llvm::PHITransAddr::PHITransAddr(), llvm::PointerMayBeCaptured(), llvm::BasicAAResult::pointsToConstantMemory(), populateDependencyMatrix(), populateExternalAttributes(), populateExternalRelations(), llvm::SITargetLowering::PostISelFolding(), llvm::PPCCCState::PreAnalyzeCallOperands(), llvm::PPCCCState::PreAnalyzeFormalArguments(), PrepareCall(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prepend(), llvm::DIExpression::prependOpcodes(), llvm::CallGraph::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::FileInfo::print(), llvm::FileInfo::printBranchInfo(), llvm::WebAssemblyInstPrinter::printInst(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), processHeaderPhiOperands(), processShaderInputArgs(), llvm::JumpThreadingPass::ProcessThreadableEdges(), promoteArguments(), llvm::promoteCall(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), promoteToConstantPool(), PropagateConstantReturn(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::LiveIntervals::pruneValue(), llvm::IntervalMapImpl::Path::push(), PushDefUseChildren(), PushLoopPHIs(), llvm::vfs::OverlayFileSystem::pushOverlay(), llvm::MCStreamer::PushSection(), pushStackMapConstant(), llvm::coverage::RawCoverageMappingReader::read(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::BitstreamCursor::readRecord(), llvm::BinaryStreamReader::readSLEB128(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::BinaryStreamReader::readULEB128(), llvm::object::MachOObjectFile::ReadULEB128s(), llvm::TargetInstrInfo::reassociateOps(), rebuildLoopAfterUnswitch(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::recognizeBSwapOrBitReverseIdiom(), recomputeLoopBlockSet(), recordCondition(), llvm::MachineDominatorTree::recordSplitCriticalEdge(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::HexagonInstrInfo::reduceLoopCount(), ReduceSwitchRange(), llvm::Attributor::registerAA(), llvm::RuntimeDyldCOFFX86_64::registerEHFrames(), llvm::RegsForValue::RegsForValue(), relocationViaAlloca(), rematerializeLiveValues(), llvm::sys::path::remove_dots(), removeConstantFactors(), llvm::LegacyInlinerBase::removeDeadFunctions(), llvm::SelectionDAG::RemoveDeadNodes(), removeDuplicateGCPtrs(), removeGlobalCtors(), llvm::MemoryDependenceResults::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), removeRedundantBlockingStores(), llvm::opt::Arg::render(), llvm::LiveRange::RenumberValues(), llvm::sys::path::replace_extension(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::coro::replaceCoroFree(), replaceDevirtTrigger(), replaceDominatedUses(), replaceExtractElements(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), replaceOneDbgValueForAlloca(), llvm::MCStreamer::reset(), llvm::UnwindOpcodeAssembler::Reset(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), resolveRecordTypes(), llvm::CondOpInit::resolveReferences(), llvm::VarDefInit::resolveReferences(), llvm::DagInit::resolveReferences(), resolveTargetShuffleInputsAndMask(), llvm::InnerLoopVectorizer::reverseVector(), rewrite(), llvm::SSAUpdaterBulk::RewriteAllUses(), RewriteHeapSROALoadUser(), rewriteNonInstructionUses(), rewritePHIs(), llvm::LoadAndStorePromoter::run(), llvm::TruncInstCombine::run(), llvm::SpeculateAroundPHIsPass::run(), llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::InlinerPass::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::AlwaysInlinerPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), runImpl(), llvm::runIPSCCP(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::SelectionDAG::salvageDebugInfo(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), scalarizeExtEltFP(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), separateNestedLoop(), llvm::MachineRegisterInfo::setCalleeSavedRegs(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::SwiftErrorValueTracking::setFunction(), setGroupSize(), llvm::SUnit::setHeightDirty(), llvm::PMTopLevelManager::setLastUser(), llvm::StructType::setName(), llvm::setProfMetadata(), llvm::Instruction::setProfWeight(), setRegZero(), llvm::IntervalMapImpl::Path::setRoot(), llvm::Module::setSDKVersion(), setUsedInitializer(), llvm::AArch64TargetLowering::shouldSinkOperands(), llvm::ARMTargetLowering::shouldSinkOperands(), shouldSplitOnPredicatedArgument(), llvm::LiveIntervals::shrinkToUses(), SimplifyAddOperands(), llvm::SimplifyCall(), simplifyCommonValuePhi(), llvm::simplifyLoop(), simplifyLoopInst(), simplifyOneLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), SimplifyWithOpReplaced(), simplifyX86extrq(), simplifyX86insertq(), simplifyX86pack(), simplifyX86varShift(), SinkCommonCodeFromPredecessors(), sinkLastInstruction(), sinkLoopInvariantInstructions(), llvm::InnerLoopVectorizer::sinkScalarOperands(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), sortBlocks(), sortLocalVars(), speculatePHIs(), SpeculativelyExecuteBB(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), SplitAddRecs(), splitAndLowerShuffle(), llvm::SplitCriticalEdge(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::DINode::splitFlags(), splitGlobal(), llvm::SplitLandingPadPredecessors(), SplitOpsAndApply(), llvm::LiveIntervals::splitSeparateComponents(), llvm::SplitString(), SRAGlobal(), stashEntryDbgValues(), llvm::X86InstrInfo::storeRegToAddr(), StoreTailCallArgumentsToStackSlot(), llvm::stripNonLineTableDebugInfo(), stripNonValidDataFromBody(), stripValuesNotDefiningMask(), swapAntiDependences(), swapMIOperands(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), llvm::JumpThreadingPass::ThreadGuard(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::Twine::toNullTerminatedStringRef(), llvm::toString(), llvm::detail::IEEEFloat::toString(), llvm::APInt::toString(), llvm::SelectionDAG::transferDbgValues(), llvm::LoopTraversal::traverse(), tryAddToFoldList(), tryBuildVectorShuffle(), llvm::LegalizationArtifactCombiner::tryCombineMerges(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::MCDwarfLineTableHeader::tryGetFile(), llvm::AArch64_IMM::trySequenceOfOnes(), llvm::VPRecipeBuilder::tryToBlend(), tryToElideArgumentCopy(), tryToFoldACImm(), tryToFoldExtendOfConstant(), llvm::AArch64_IMM::tryToreplicateChunks(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), turnGuardIntoBranch(), TurnSwitchRangeIntoICmp(), llvm::IntEqClasses::uncompress(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), unswitchBestCondition(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::UnwindOpcodeAssembler::UnwindOpcodeAssembler(), llvm::coro::updateCallGraph(), llvm::updateCGAndAnalysisManagerForFunctionPass(), llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs(), updateLiveness(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), updatePredecessorProfileMetadata(), llvm::CallInst::updateProfWeight(), llvm::upgradeInstructionLoopAttachment(), llvm::UpgradeIntrinsicCall(), upgradeLoopArgument(), llvm::valTypesFromMVTs(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), verifyCTRBranch(), llvm::SIInstrInfo::verifyInstruction(), llvm::MemorySSA::verifyOrdering(), llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), llvm::SCEVLoopAddRecRewriter::visitAddRecExpr(), llvm::InstCombiner::visitCallInst(), visitDomSubTree(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::InstCombiner::visitLandingPadInst(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), visitPHIUsersAndDepsInPostOrder(), llvm::LazyCallGraph::visitReferences(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMinExpr(), visitUDivOperand(), llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMinExpr(), llvm::InnerLoopVectorizer::widenInstruction(), widenVectorToPartType(), writeStringRecord(), llvm::InstrProfWriter::writeText(), writeTypeIdCompatibleVtableSummaryRecord(), writeTypeIdSummaryRecord(), writeWholeProgramDevirtResolution(), writeWholeProgramDevirtResolutionByArg(), and llvm::LLVMContextImpl::~LLVMContextImpl().
push_back() [2/2]
template<typename T , bool = is_trivially_copyable<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::push_back (T && Elt) inline
Definition at line 218 of file SmallVector.h.
References llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), LLVM_UNLIKELY, llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
uninitialized_copy()
template<typename T , bool = is_trivially_copyable<T>::value> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 201 of file SmallVector.h.
References E, and I.
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::insert(), and llvm::SmallVectorTemplateBase< T, true >::uninitialized_move().
uninitialized_move()
template<typename T , bool = is_trivially_copyable<T>::value> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 193 of file SmallVector.h.
References E, and I.
Referenced by llvm::SmallVectorImpl< T >::insert().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h