LLVM: llvm::RecurrenceDescriptor Class Reference
llvm::RecurrenceDescriptor Class Reference
The RecurrenceDescriptor is used to identify recurrences variables in a loop.
#include "llvm/Analysis/IVDescriptors.h"
Classes
class InstDesc
This POD struct holds information about a potential recurrence operation.
Public Types
enum RecurrenceKind {
RK_NoRecurrence , RK_IntegerAdd , RK_IntegerMult , RK_IntegerOr ,
RK_IntegerAnd , RK_IntegerXor , RK_IntegerMinMax , RK_FloatAdd ,
RK_FloatMult , RK_FloatMinMax
}
This enum represents the kinds of recurrences that we support.
enum MinMaxRecurrenceKind {
MRK_Invalid , MRK_UIntMin , MRK_UIntMax , MRK_SIntMin ,
MRK_SIntMax , MRK_FloatMin , MRK_FloatMax
}
Public Member Functions
RecurrenceDescriptor ()=default
RecurrenceDescriptor (Value *Start, Instruction *Exit, RecurrenceKind K, FastMathFlags FMF, MinMaxRecurrenceKind MK, Instruction *UAI, Type *RT, bool Signed, SmallPtrSetImpl< Instruction * > &CI)
RecurrenceKind getRecurrenceKind ()
MinMaxRecurrenceKind getMinMaxRecurrenceKind ()
FastMathFlags getFastMathFlags ()
TrackingVH< Value > getRecurrenceStartValue ()
Instruction * getLoopExitInstr ()
bool hasUnsafeAlgebra ()
Returns true if the recurrence has unsafe algebra which requires a relaxed floating-point model.
Instruction * getUnsafeAlgebraInst ()
Returns first unsafe algebra instruction in the PHI node's use-chain.
Type * getRecurrenceType ()
Returns the type of the recurrence.
SmallPtrSet< Instruction *, 8 > & getCastInsts ()
Returns a reference to the instructions used for type-promoting the recurrence.
bool isSigned ()
Returns true if all source operands of the recurrence are SExtInsts.
Static Public Member Functions
static InstDesc isRecurrenceInstr (Instruction *I, RecurrenceKind Kind, InstDesc &Prev, bool HasFunNoNaNAttr)
Returns a struct describing if the instruction 'I' can be a recurrence variable of type 'Kind'.
static bool hasMultipleUsesOf (Instruction *I, SmallPtrSetImpl< Instruction * > &Insts, unsigned MaxNumUses)
Returns true if instruction I has multiple uses in Insts.
static bool areAllUsesIn (Instruction *I, SmallPtrSetImpl< Instruction * > &Set)
Returns true if all uses of the instruction I is within the Set.
static InstDesc isMinMaxSelectCmpPattern (Instruction *I, InstDesc &Prev)
Returns a struct describing if the instruction if the instruction is a Select(ICmp(X, Y), X, Y) instruction pattern corresponding to a min(X, Y) or max(X, Y).
static InstDesc isConditionalRdxPattern (RecurrenceKind Kind, Instruction *I)
Returns a struct describing if the instruction is a Select(FCmp(X, Y), (Z = X op PHINode), PHINode) instruction pattern.
static Constant * getRecurrenceIdentity (RecurrenceKind K, Type *Tp)
Returns identity corresponding to the RecurrenceKind.
static unsigned getRecurrenceBinOp (RecurrenceKind Kind)
Returns the opcode of binary operation corresponding to the RecurrenceKind.
static bool AddReductionVar (PHINode *Phi, RecurrenceKind Kind, Loop *TheLoop, bool HasFunNoNaNAttr, RecurrenceDescriptor &RedDes, DemandedBits *DB=nullptr, AssumptionCache *AC=nullptr, DominatorTree *DT=nullptr)
Returns true if Phi is a reduction of type Kind and adds it to the RecurrenceDescriptor.
static bool isReductionPHI (PHINode *Phi, Loop *TheLoop, RecurrenceDescriptor &RedDes, DemandedBits *DB=nullptr, AssumptionCache *AC=nullptr, DominatorTree *DT=nullptr)
Returns true if Phi is a reduction in TheLoop.
static bool isFirstOrderRecurrence (PHINode *Phi, Loop *TheLoop, DenseMap< Instruction *, Instruction * > &SinkAfter, DominatorTree *DT)
Returns true if Phi is a first-order recurrence.
static bool isIntegerRecurrenceKind (RecurrenceKind Kind)
Returns true if the recurrence kind is an integer kind.
static bool isFloatingPointRecurrenceKind (RecurrenceKind Kind)
Returns true if the recurrence kind is a floating point kind.
static bool isArithmeticRecurrenceKind (RecurrenceKind Kind)
Returns true if the recurrence kind is an arithmetic kind.
Detailed Description
The RecurrenceDescriptor is used to identify recurrences variables in a loop.
Reduction is a special case of recurrence that has uses of the recurrence variable outside the loop. The method isReductionPHI identifies reductions that are basic recurrences.
Basic recurrences are defined as the summation, product, OR, AND, XOR, min, or max of a set of terms. For example: for(i=0; i<n; i++) { total += array[i]; } is a summation of array elements. Basic recurrences are a special case of chains of recurrences (CR). See ScalarEvolution for CR references. This struct holds information about recurrence variables.
Definition at line 62 of file IVDescriptors.h.
Member Enumeration Documentation
MinMaxRecurrenceKind
enum llvm::RecurrenceDescriptor::MinMaxRecurrenceKind
Enumerator
MRK_Invalid
MRK_UIntMin
MRK_UIntMax
MRK_SIntMin
MRK_SIntMax
MRK_FloatMin
MRK_FloatMax
Definition at line 79 of file IVDescriptors.h.
RecurrenceKind
enum llvm::RecurrenceDescriptor::RecurrenceKind
This enum represents the kinds of recurrences that we support.
Enumerator
RK_NoRecurrence
Not a recurrence.
RK_IntegerAdd
Sum of integers.
RK_IntegerMult
Product of integers.
RK_IntegerOr
Bitwise or logical OR of numbers.
RK_IntegerAnd
Bitwise or logical AND of numbers.
RK_IntegerXor
Bitwise or logical XOR of numbers.
RK_IntegerMinMax
Min/max implemented in terms of select(cmp()).
RK_FloatAdd
Sum of floats.
RK_FloatMult
Product of floats.
RK_FloatMinMax
Min/max implemented in terms of select(cmp()).
Definition at line 65 of file IVDescriptors.h.
Constructor & Destructor Documentation
RecurrenceDescriptor() [1/2]
llvm::RecurrenceDescriptor::RecurrenceDescriptor () default
RecurrenceDescriptor() [2/2]
llvm::RecurrenceDescriptor::RecurrenceDescriptor (Value * Start, Instruction * Exit, RecurrenceKind K, FastMathFlags FMF, MinMaxRecurrenceKind MK, Instruction * UAI, Type * RT, bool Signed, SmallPtrSetImpl< Instruction * > & CI) inline
Definition at line 91 of file IVDescriptors.h.
Member Function Documentation
AddReductionVar()
bool RecurrenceDescriptor::AddReductionVar (PHINode * Phi, RecurrenceKind Kind, Loop * TheLoop, bool HasFunNoNaNAttr, RecurrenceDescriptor & RedDes, DemandedBits * DB = nullptr, AssumptionCache * AC = nullptr, DominatorTree * DT = nullptr) static
Returns true if Phi is a reduction of type Kind and adds it to the RecurrenceDescriptor.
If either DB is non-null or AC and DT are non-null, the minimal bit width needed to compute the reduction will be computed.
Definition at line 190 of file IVDescriptors.cpp.
References areAllUsesIn(), collectCastsToIgnore(), computeRecurrenceType(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::FastMathFlags::getFast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::RecurrenceDescriptor::InstDesc::getMinMaxKind(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::RecurrenceDescriptor::InstDesc::getPatternInst(), llvm::Value::getType(), llvm::RecurrenceDescriptor::InstDesc::getUnsafeAlgebraInst(), hasMultipleUsesOf(), isArithmeticRecurrenceKind(), llvm::Instruction::isCommutative(), isConditionalRdxPattern(), isFloatingPointRecurrenceKind(), llvm::Type::isFloatingPointTy(), isIntegerRecurrenceKind(), isMinMaxSelectCmpPattern(), llvm::RecurrenceDescriptor::InstDesc::isRecurrence(), isRecurrenceInstr(), lookThroughAnd(), llvm::User::operands(), RK_FloatAdd, RK_FloatMinMax, RK_FloatMult, RK_IntegerMinMax, llvm::Value::use_empty(), and llvm::Value::users().
Referenced by isReductionPHI().
areAllUsesIn()
bool RecurrenceDescriptor::areAllUsesIn (Instruction * I, SmallPtrSetImpl< Instruction * > & Set) static
Returns true if all uses of the instruction I is within the Set.
Definition at line 43 of file IVDescriptors.cpp.
References I.
Referenced by AddReductionVar().
getCastInsts()
SmallPtrSet< Instruction *, 8 > & llvm::RecurrenceDescriptor::getCastInsts () inline
Returns a reference to the instructions used for type-promoting the recurrence.
Definition at line 231 of file IVDescriptors.h.
Referenced by llvm::LoopVectorizationCostModel::collectValuesToIgnore().
getFastMathFlags()
FastMathFlags llvm::RecurrenceDescriptor::getFastMathFlags () inline
Definition at line 203 of file IVDescriptors.h.
Referenced by llvm::createTargetReduction(), and llvm::InnerLoopVectorizer::fixReduction().
getLoopExitInstr()
Instruction * llvm::RecurrenceDescriptor::getLoopExitInstr () inline
Definition at line 207 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::fixReduction().
getMinMaxRecurrenceKind()
MinMaxRecurrenceKind llvm::RecurrenceDescriptor::getMinMaxRecurrenceKind () inline
Definition at line 201 of file IVDescriptors.h.
Referenced by llvm::createTargetReduction(), and llvm::InnerLoopVectorizer::fixReduction().
getRecurrenceBinOp()
unsigned RecurrenceDescriptor::getRecurrenceBinOp (RecurrenceKind Kind) static
Returns the opcode of binary operation corresponding to the RecurrenceKind.
This function translates the recurrence kind to an LLVM binary operator.
Definition at line 750 of file IVDescriptors.cpp.
References llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::FAdd, llvm_unreachable, llvm::AtomicRMWInst::Or, RK_FloatAdd, RK_FloatMinMax, RK_FloatMult, RK_IntegerAdd, RK_IntegerAnd, RK_IntegerMinMax, RK_IntegerMult, RK_IntegerOr, RK_IntegerXor, and llvm::AtomicRMWInst::Xor.
Referenced by llvm::InnerLoopVectorizer::fixReduction().
getRecurrenceIdentity()
Constant * RecurrenceDescriptor::getRecurrenceIdentity (RecurrenceKind K, Type * Tp) static
Returns identity corresponding to the RecurrenceKind.
This function returns the identity element (or neutral element) for the operation K.
Definition at line 724 of file IVDescriptors.cpp.
References llvm::DITypeRefArray::get(), llvm_unreachable, RK_FloatAdd, RK_FloatMult, RK_IntegerAdd, RK_IntegerAnd, RK_IntegerMult, RK_IntegerOr, and RK_IntegerXor.
Referenced by llvm::InnerLoopVectorizer::fixReduction().
getRecurrenceKind()
RecurrenceKind llvm::RecurrenceDescriptor::getRecurrenceKind () inline
Definition at line 199 of file IVDescriptors.h.
Referenced by llvm::createTargetReduction(), and llvm::InnerLoopVectorizer::fixReduction().
getRecurrenceStartValue()
TrackingVH< Value > llvm::RecurrenceDescriptor::getRecurrenceStartValue () inline
Definition at line 205 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::fixReduction().
getRecurrenceType()
Type * llvm::RecurrenceDescriptor::getRecurrenceType () inline
Returns the type of the recurrence.
This type can be narrower than the actual type of the Phi if the recurrence has been type-promoted.
Definition at line 227 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::fixReduction(), and llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes().
getUnsafeAlgebraInst()
Instruction * llvm::RecurrenceDescriptor::getUnsafeAlgebraInst () inline
Returns first unsafe algebra instruction in the PHI node's use-chain.
Definition at line 214 of file IVDescriptors.h.
hasMultipleUsesOf()
bool RecurrenceDescriptor::hasMultipleUsesOf (Instruction * I, SmallPtrSetImpl< Instruction * > & Insts, unsigned MaxNumUses) static
Returns true if instruction I has multiple uses in Insts.
Definition at line 596 of file IVDescriptors.cpp.
References I.
Referenced by AddReductionVar().
hasUnsafeAlgebra()
bool llvm::RecurrenceDescriptor::hasUnsafeAlgebra () inline
Returns true if the recurrence has unsafe algebra which requires a relaxed floating-point model.
Definition at line 211 of file IVDescriptors.h.
isArithmeticRecurrenceKind()
bool RecurrenceDescriptor::isArithmeticRecurrenceKind (RecurrenceKind Kind) static
Returns true if the recurrence kind is an arithmetic kind.
Definition at line 70 of file IVDescriptors.cpp.
References RK_FloatAdd, RK_FloatMult, RK_IntegerAdd, and RK_IntegerMult.
Referenced by AddReductionVar().
isConditionalRdxPattern()
RecurrenceDescriptor::InstDesc RecurrenceDescriptor::isConditionalRdxPattern (RecurrenceKind Kind, Instruction * I) static
Returns a struct describing if the instruction is a Select(FCmp(X, Y), (Z = X op PHINode), PHINode) instruction pattern.
Returns true if the select instruction has users in the compare-and-add reduction pattern below.
The select instruction argument is the last one in the sequence.
sum.1 = phi ... ... cmp = fcmp pred %0, CFP add = fadd %0, sum.1 sum.2 = select cmp, add, sum.1
Definition at line 518 of file IVDescriptors.cpp.
References llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getTrueValue(), llvm::Value::hasOneUse(), I, llvm::Instruction::isBinaryOp(), llvm::Instruction::isFast(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), RK_FloatAdd, and RK_FloatMult.
Referenced by AddReductionVar(), and isRecurrenceInstr().
isFirstOrderRecurrence()
bool RecurrenceDescriptor::isFirstOrderRecurrence (PHINode * Phi, Loop * TheLoop, DenseMap< Instruction *, Instruction * > & SinkAfter, DominatorTree * DT) static
Returns true if Phi is a first-order recurrence.
A first-order recurrence is a non-reduction recurrence relation in which the value of the recurrence in the current loop iteration equals a value defined in the previous iteration. SinkAfter includes pairs of instructions where the first will be rescheduled to appear after the second if/when the loop is vectorized. It may be augmented with additional pairs if needed in order to handle Phi as a first-order recurrence.
Definition at line 670 of file IVDescriptors.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DominatorTree::dominates(), llvm::PHINode::getBasicBlockIndex(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::Value::hasOneUse(), I, llvm::Instruction::user_back(), and llvm::Value::users().
isFloatingPointRecurrenceKind()
bool RecurrenceDescriptor::isFloatingPointRecurrenceKind (RecurrenceKind Kind) static
Returns true if the recurrence kind is a floating point kind.
Definition at line 66 of file IVDescriptors.cpp.
References isIntegerRecurrenceKind(), and RK_NoRecurrence.
Referenced by AddReductionVar().
isIntegerRecurrenceKind()
bool RecurrenceDescriptor::isIntegerRecurrenceKind (RecurrenceKind Kind) static
Returns true if the recurrence kind is an integer kind.
Definition at line 51 of file IVDescriptors.cpp.
References RK_IntegerAdd, RK_IntegerAnd, RK_IntegerMinMax, RK_IntegerMult, RK_IntegerOr, and RK_IntegerXor.
Referenced by AddReductionVar(), and isFloatingPointRecurrenceKind().
isMinMaxSelectCmpPattern()
RecurrenceDescriptor::InstDesc RecurrenceDescriptor::isMinMaxSelectCmpPattern (Instruction * I, InstDesc & Prev) static
Returns a struct describing if the instruction if the instruction is a Select(ICmp(X, Y), X, Y) instruction pattern corresponding to a min(X, Y) or max(X, Y).
Returns true if the instruction is a Select(ICmp(X, Y), X, Y) instruction pattern corresponding to a min(X, Y) or max(X, Y).
Definition at line 460 of file IVDescriptors.cpp.
References assert(), llvm::RecurrenceDescriptor::InstDesc::getMinMaxKind(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), MRK_FloatMax, MRK_FloatMin, MRK_SIntMax, MRK_SIntMin, MRK_UIntMax, and MRK_UIntMin.
Referenced by AddReductionVar(), and isRecurrenceInstr().
isRecurrenceInstr()
RecurrenceDescriptor::InstDesc RecurrenceDescriptor::isRecurrenceInstr (Instruction * I, RecurrenceKind Kind, InstDesc & Prev, bool HasFunNoNaNAttr) static
Returns a struct describing if the instruction 'I' can be a recurrence variable of type 'Kind'.
If the recurrence is a min/max pattern of select(icmp()) this function advances the instruction pointer 'I' from the compare instruction to the select instruction and stores this pointer in 'PatternLastInst' member of the returned struct.
Definition at line 556 of file IVDescriptors.cpp.
References llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::RecurrenceDescriptor::InstDesc::getMinMaxKind(), llvm::RecurrenceDescriptor::InstDesc::getUnsafeAlgebraInst(), I, isConditionalRdxPattern(), isMinMaxSelectCmpPattern(), LLVM_FALLTHROUGH, llvm::AtomicRMWInst::Or, RK_FloatAdd, RK_FloatMinMax, RK_FloatMult, RK_IntegerAdd, RK_IntegerAnd, RK_IntegerMinMax, RK_IntegerMult, RK_IntegerOr, RK_IntegerXor, llvm::AtomicRMWInst::Sub, and llvm::AtomicRMWInst::Xor.
Referenced by AddReductionVar().
isReductionPHI()
bool RecurrenceDescriptor::isReductionPHI (PHINode * Phi, Loop * TheLoop, RecurrenceDescriptor & RedDes, DemandedBits * DB = nullptr, AssumptionCache * AC = nullptr, DominatorTree * DT = nullptr) static
Returns true if Phi is a reduction in TheLoop.
The RecurrenceDescriptor is returned in RedDes. If either DB is non-null or AC and DT are non-null, the minimal bit width needed to compute the reduction will be computed.
Definition at line 610 of file IVDescriptors.cpp.
References AddReductionVar(), llvm::dbgs(), F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), LLVM_DEBUG, RK_FloatAdd, RK_FloatMinMax, RK_FloatMult, RK_IntegerAdd, RK_IntegerAnd, RK_IntegerMinMax, RK_IntegerMult, RK_IntegerOr, and RK_IntegerXor.
Referenced by findInnerReductionPhi().
isSigned()
bool llvm::RecurrenceDescriptor::isSigned () inline
Returns true if all source operands of the recurrence are SExtInsts.
Definition at line 234 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::fixReduction(), and IsKnownPredicateViaAddRecStart().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IVDescriptors.h
lib/Analysis/IVDescriptors.cpp