LLVM: llvm::DstOp Class Reference
llvm::DstOp Class Reference
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
Public Types
enum class DstType { Ty_LLT , Ty_Reg , Ty_RC }
Public Member Functions
DstOp (unsigned R)
DstOp (Register R)
DstOp (const MachineOperand &Op)
DstOp (const LLT &T)
DstOp (const TargetRegisterClass *TRC)
void addDefToMIB (MachineRegisterInfo &MRI, MachineInstrBuilder &MIB) const
LLT getLLTTy (const MachineRegisterInfo &MRI) const
Register getReg () const
const TargetRegisterClass * getRegClass () const
DstType getDstOpKind () const
Detailed Description
Definition at line 59 of file MachineIRBuilder.h.
Member Enumeration Documentation
DstType
enum class llvm::DstOp::DstType strong
Enumerator
Ty_LLT
Ty_Reg
Ty_RC
Definition at line 67 of file MachineIRBuilder.h.
Constructor & Destructor Documentation
DstOp() [1/5]
llvm::DstOp::DstOp (unsigned R) inline
Definition at line 68 of file MachineIRBuilder.h.
DstOp() [2/5]
llvm::DstOp::DstOp (Register R) inline
Definition at line 69 of file MachineIRBuilder.h.
DstOp() [3/5]
llvm::DstOp::DstOp (const MachineOperand & Op) inline
Definition at line 70 of file MachineIRBuilder.h.
DstOp() [4/5]
llvm::DstOp::DstOp (const LLT & T) inline
Definition at line 71 of file MachineIRBuilder.h.
DstOp() [5/5]
llvm::DstOp::DstOp (const TargetRegisterClass * TRC) inline
Definition at line 72 of file MachineIRBuilder.h.
Member Function Documentation
addDefToMIB()
void llvm::DstOp::addDefToMIB (MachineRegisterInfo & MRI, MachineInstrBuilder & MIB) const inline
Definition at line 74 of file MachineIRBuilder.h.
References llvm::MachineInstrBuilder::addDef(), LLTTy, MRI, RC, Reg, Ty_LLT, Ty_RC, and Ty_Reg.
Referenced by llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFrameIndex(), llvm::MachineIRBuilder::buildGEP(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildLoadInstr(), and llvm::MachineIRBuilder::buildPtrMask().
getDstOpKind()
DstType llvm::DstOp::getDstOpKind () const inline
Definition at line 114 of file MachineIRBuilder.h.
getLLTTy()
LLT llvm::DstOp::getLLTTy (const MachineRegisterInfo & MRI) const inline
Definition at line 88 of file MachineIRBuilder.h.
References LLTTy, llvm_unreachable, MRI, Reg, Ty_LLT, Ty_RC, and Ty_Reg.
Referenced by llvm::MachineIRBuilder::buildCast(), llvm::MachineIRBuilder::buildConstant(), llvm::CSEMIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildFConstant(), llvm::CSEMIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFrameIndex(), llvm::MachineIRBuilder::buildGEP(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildNot(), llvm::MachineIRBuilder::buildPtrMask(), and llvm::MachineIRBuilder::buildSplatVector().
getReg()
Register llvm::DstOp::getReg () const inline
Definition at line 100 of file MachineIRBuilder.h.
References assert(), Reg, and Ty_Reg.
Referenced by AnalyzeArguments(), llvm::analyzeStandardArguments(), CC_MipsO32(), CC_RISCV(), CC_RISCVAssign2XLen(), llvm::X86AsmPrinter::EmitInstruction(), fixupVariableFloatArgs(), getShuffleComment(), and setLocInfo().
getRegClass()
const TargetRegisterClass * llvm::DstOp::getRegClass () const inline
Definition at line 105 of file MachineIRBuilder.h.
References llvm_unreachable, RC, and Ty_RC.
Referenced by llvm::SIRegisterInfo::getRegClass().
Member Data Documentation
LLTTy
LLT llvm::DstOp::LLTTy
Definition at line 61 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), and getLLTTy().
RC
const TargetRegisterClass* llvm::DstOp::RC
Definition at line 63 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), and getRegClass().
Reg
Register llvm::DstOp::Reg
Definition at line 62 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), getLLTTy(), and getReg().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h