LLVM: llvm::BinaryByteStream Class Reference
llvm::BinaryByteStream Class Reference
An implementation of BinaryStream which holds its entire data set in a single contiguous buffer.
#include "llvm/Support/BinaryByteStream.h"
Public Member Functions
BinaryByteStream ()=default
BinaryByteStream (ArrayRef< uint8_t > Data, llvm::support::endianness Endian)
BinaryByteStream (StringRef Data, llvm::support::endianness Endian)
llvm::support::endianness getEndian () const override
Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream, read as much as possible without copying any data.
uint32_t getLength () override
Return the number of bytes of data in this stream.
ArrayRef< uint8_t > data () const
StringRef str () const
Public Member Functions inherited from llvm::BinaryStream
virtual ~BinaryStream ()=default
virtual llvm::support::endianness getEndian () const =0
virtual Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
virtual Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream, read as much as possible without copying any data.
virtual uint32_t getLength ()=0
Return the number of bytes of data in this stream.
virtual BinaryStreamFlags getFlags () const
Return the properties of this stream.
Protected Attributes
llvm::support::endianness Endian
ArrayRef< uint8_t > Data
Additional Inherited Members
Protected Member Functions inherited from llvm::BinaryStream
Error checkOffsetForRead (uint32_t Offset, uint32_t DataSize)
Detailed Description
An implementation of BinaryStream which holds its entire data set in a single contiguous buffer.
BinaryByteStream guarantees that no read operation will ever incur a copy. Note that BinaryByteStream does not own the underlying buffer.
Definition at line 31 of file BinaryByteStream.h.
Constructor & Destructor Documentation
BinaryByteStream() [1/3]
llvm::BinaryByteStream::BinaryByteStream () default
BinaryByteStream() [2/3]
llvm::BinaryByteStream::BinaryByteStream (ArrayRef< uint8_t > Data, llvm::support::endianness Endian) inline
Definition at line 34 of file BinaryByteStream.h.
BinaryByteStream() [3/3]
llvm::BinaryByteStream::BinaryByteStream (StringRef Data, llvm::support::endianness Endian) inline
Definition at line 36 of file BinaryByteStream.h.
Member Function Documentation
data()
ArrayRef< uint8_t > llvm::BinaryByteStream::data () const inline
Definition at line 59 of file BinaryByteStream.h.
References Data.
getEndian()
llvm::support::endianness llvm::BinaryByteStream::getEndian () const inline override virtual
Implements llvm::BinaryStream.
Definition at line 39 of file BinaryByteStream.h.
References Endian.
Referenced by llvm::MutableBinaryByteStream::getEndian().
getLength()
uint32_t llvm::BinaryByteStream::getLength () inline override virtual
Return the number of bytes of data in this stream.
Implements llvm::BinaryStream.
Definition at line 57 of file BinaryByteStream.h.
References Data, and llvm::ArrayRef< T >::size().
Referenced by llvm::MutableBinaryByteStream::getLength().
readBytes()
Error llvm::BinaryByteStream::readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > & Buffer) inline override virtual
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Implements llvm::BinaryStream.
Definition at line 41 of file BinaryByteStream.h.
References llvm::BinaryStream::checkOffsetForRead(), Data, Size, llvm::ArrayRef< T >::slice(), and llvm::Error::success().
Referenced by llvm::MutableBinaryByteStream::readBytes().
readLongestContiguousChunk()
Error llvm::BinaryByteStream::readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > & Buffer) inline override virtual
Given an offset into the stream, read as much as possible without copying any data.
Implements llvm::BinaryStream.
Definition at line 49 of file BinaryByteStream.h.
References llvm::BinaryStream::checkOffsetForRead(), Data, llvm::ArrayRef< T >::slice(), and llvm::Error::success().
Referenced by llvm::MutableBinaryByteStream::readLongestContiguousChunk().
str()
StringRef llvm::BinaryByteStream::str () const inline
Definition at line 61 of file BinaryByteStream.h.
References llvm::ArrayRef< T >::data(), Data, and llvm::ArrayRef< T >::size().
Member Data Documentation
Data
ArrayRef<uint8_t> llvm::BinaryByteStream::Data protected
Definition at line 68 of file BinaryByteStream.h.
Referenced by data(), getLength(), readBytes(), readLongestContiguousChunk(), and str().
Endian
llvm::support::endianness llvm::BinaryByteStream::Endian protected
Definition at line 67 of file BinaryByteStream.h.
Referenced by getEndian().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryByteStream.h