LLVM: llvm::LiveStacks Class Reference
llvm::LiveStacks Class Reference
#include "llvm/CodeGen/LiveStacks.h"
Public Types
using iterator = SS2IntervalMap::iterator
using const_iterator = SS2IntervalMap::const_iterator
Public Member Functions
LiveStacks ()
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
unsigned getNumIntervals () const
LiveInterval & getOrCreateInterval (int Slot, const TargetRegisterClass *RC)
LiveInterval & getInterval (int Slot)
const LiveInterval & getInterval (int Slot) const
bool hasInterval (int Slot) const
const TargetRegisterClass * getIntervalRegClass (int Slot) const
VNInfo::Allocator & getVNInfoAllocator ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
bool runOnMachineFunction (MachineFunction &) override
runOnMachineFunction - pass entry point
void print (raw_ostream &O, const Module *=nullptr) const override
print - Implement the dump method.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 30 of file LiveStacks.h.
Member Typedef Documentation
const_iterator
using llvm::LiveStacks::const_iterator = SS2IntervalMap::const_iterator
Definition at line 52 of file LiveStacks.h.
iterator
using llvm::LiveStacks::iterator = SS2IntervalMap::iterator
Definition at line 51 of file LiveStacks.h.
Constructor & Destructor Documentation
LiveStacks()
llvm::LiveStacks::LiveStacks () inline
Definition at line 47 of file LiveStacks.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveStacksPass().
Member Function Documentation
begin() [1/2]
iterator llvm::LiveStacks::begin () inline
Definition at line 56 of file LiveStacks.h.
begin() [2/2]
const_iterator llvm::LiveStacks::begin () const inline
Definition at line 54 of file LiveStacks.h.
Referenced by print().
end() [1/2]
iterator llvm::LiveStacks::end () inline
Definition at line 57 of file LiveStacks.h.
end() [2/2]
const_iterator llvm::LiveStacks::end () const inline
Definition at line 55 of file LiveStacks.h.
Referenced by print().
getAnalysisUsage()
void LiveStacks::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 35 of file LiveStacks.cpp.
References llvm::MachineFunctionPass::getAnalysisUsage().
getInterval() [1/2]
LiveInterval & llvm::LiveStacks::getInterval (int Slot) inline
Definition at line 63 of file LiveStacks.h.
References assert(), and I.
getInterval() [2/2]
const LiveInterval & llvm::LiveStacks::getInterval (int Slot) const inline
Definition at line 70 of file LiveStacks.h.
References assert(), and I.
getIntervalRegClass()
const TargetRegisterClass * llvm::LiveStacks::getIntervalRegClass (int Slot) const inline
Definition at line 79 of file LiveStacks.h.
References assert(), and I.
Referenced by print().
getNumIntervals()
unsigned llvm::LiveStacks::getNumIntervals () const inline
Definition at line 59 of file LiveStacks.h.
getOrCreateInterval()
LiveInterval & LiveStacks::getOrCreateInterval (int Slot, const TargetRegisterClass * RC)
Definition at line 57 of file LiveStacks.cpp.
References assert(), llvm::TargetRegisterInfo::getCommonSubClass(), I, and llvm::TargetRegisterInfo::index2StackSlot().
getVNInfoAllocator()
VNInfo::Allocator & llvm::LiveStacks::getVNInfoAllocator () inline
Definition at line 88 of file LiveStacks.h.
hasInterval()
bool llvm::LiveStacks::hasInterval (int Slot) const inline
Definition at line 77 of file LiveStacks.h.
print()
void LiveStacks::print (raw_ostream & O, const Module * = nullptr) const override virtual
print - Implement the dump method.
Reimplemented from llvm::Pass.
Definition at line 75 of file LiveStacks.cpp.
References begin(), E, end(), getIntervalRegClass(), llvm::TargetRegisterInfo::getRegClassName(), and I.
releaseMemory()
void LiveStacks::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 42 of file LiveStacks.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
runOnMachineFunction()
bool LiveStacks::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - pass entry point
Implements llvm::MachineFunctionPass.
Definition at line 49 of file LiveStacks.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
Member Data Documentation
ID
char LiveStacks::ID = 0 static
Definition at line 45 of file LiveStacks.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveStacks.h
lib/CodeGen/LiveStacks.cpp