LLVM: AAReturnedValuesImpl Class Reference
AAReturnedValuesImpl Class Reference final
------------------— Function Return Values ----------------------------—
Public Member Functions
AAReturnedValuesImpl (Function &F, InformationCache &InfoCache)
See AbstractAttribute::AbstractAttribute(...).
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
AbstractState & getState () override
See AbstractAttribute::getState(...).
const AbstractState & getState () const override
See AbstractAttribute::getState(...).
ManifestPosition getManifestPosition () const override
See AbstractAttribute::getManifestPosition().
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(Attributor &A).
size_t getNumReturnValues () const
Return the number of potential return values, -1 if unknown.
Optional< Value * > getAssumedUniqueReturnValue () const
Return an assumed unique return value if a single candidate is found.
bool checkForallReturnedValues (std::function< bool(Value &)> &Pred) const override
See AbstractState::checkForallReturnedValues(...).
const std::string getAsStr () const override
Pretty print the attribute similar to the IR representation.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint().
bool isValidState () const override
See AbstractState::isValidState().
void indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...).
void indicatePessimisticFixpoint () override
Indicate that the abstract state should converge to the pessimistic state.
Public Member Functions inherited from llvm::AAReturnedValues
AAReturnedValues (Function &F, InformationCache &InfoCache)
See AbstractAttribute::AbstractAttribute(...).
virtual bool checkForallReturnedValues (std::function< bool(Value &)> &Pred) const =0
Check Pred on all returned values.
Attribute::AttrKind getAttrKind () const override
See AbstractAttribute::getAttrKind()
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (Value *AssociatedVal, Value &AnchoredVal, InformationCache &InfoCache)
An abstract attribute associated with AssociatedVal and anchored at AnchoredVal.
AbstractAttribute (Value &V, InformationCache &InfoCache)
An abstract attribute associated with and anchored at V.
virtual ~AbstractAttribute ()
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual const AbstractState & getState () const =0
Return the internal abstract state for inspection.
Value & getAnchoredValue ()
Return the value this abstract attribute is anchored with.
const Value & getAnchoredValue () const
Function & getAnchorScope ()
}
const Function & getAnchorScope () const
virtual Value * getAssociatedValue ()
}
virtual const Value * getAssociatedValue () const
virtual ManifestPosition getManifestPosition () const =0
}
virtual Attribute::AttrKind getAttrKind () const =0
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
virtual void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void dump () const
virtual const std::string getAsStr () const =0
This function should return the "summarized" assumed state as string.
Additional Inherited Members
Public Types inherited from llvm::AbstractAttribute
enum ManifestPosition { MP_ARGUMENT , MP_CALL_SITE_ARGUMENT , MP_FUNCTION , MP_RETURNED }
The positions attributes can be manifested in.
Static Public Attributes inherited from llvm::AAReturnedValues
static constexpr Attribute::AttrKind ID = Attribute::Returned
The identifier used by the Attributor for this class of attributes.
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual AbstractState & getState ()=0
Return the internal abstract state for careful modification.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Attributes inherited from llvm::AbstractAttribute
Value * AssociatedVal
The value this abstract attribute is associated with.
Value & AnchoredVal
The value this abstract attribute is anchored at.
InformationCache & InfoCache
The information cache accessible to this abstract attribute.
Detailed Description
------------------— Function Return Values ----------------------------—
"Attribute" that collects all potential returned values and the return instructions that they arise from.
If there is a unique returned value R, the manifest method will:
mark R with the "returned" attribute, if R is an argument.
Definition at line 437 of file Attributor.cpp.
Constructor & Destructor Documentation
AAReturnedValuesImpl()
AAReturnedValuesImpl::AAReturnedValuesImpl (Function & F, InformationCache & InfoCache) inline
See AbstractAttribute::AbstractAttribute(...).
Definition at line 475 of file Attributor.cpp.
Member Function Documentation
checkForallReturnedValues()
bool AAReturnedValuesImpl::checkForallReturnedValues (std::function< bool(Value &)> & Pred) const override virtual
See AbstractState::checkForallReturnedValues(...).
Implements llvm::AAReturnedValues.
Definition at line 627 of file Attributor.cpp.
getAsStr()
const std::string AAReturnedValuesImpl::getAsStr () const override virtual
Pretty print the attribute similar to the IR representation.
Implements llvm::AbstractAttribute.
Definition at line 591 of file Attributor.cpp.
getAssumedUniqueReturnValue()
Optional< Value * > AAReturnedValuesImpl::getAssumedUniqueReturnValue () const
Return an assumed unique return value if a single candidate is found.
If there cannot be one, return a nullptr. If it is not clear yet, return the Optional::NoneType.
Definition at line 596 of file Attributor.cpp.
getManifestPosition()
ManifestPosition AAReturnedValuesImpl::getManifestPosition () const inline override virtual
See AbstractAttribute::getManifestPosition().
Implements llvm::AbstractAttribute.
Definition at line 527 of file Attributor.cpp.
getNumReturnValues()
size_t AAReturnedValuesImpl::getNumReturnValues () const inline
Return the number of potential return values, -1 if unknown.
Definition at line 533 of file Attributor.cpp.
getState() [1/2]
const AbstractState & AAReturnedValuesImpl::getState () const inline override virtual
See AbstractAttribute::getState(...).
Implements llvm::AbstractAttribute.
Definition at line 524 of file Attributor.cpp.
getState() [2/2]
AbstractState & AAReturnedValuesImpl::getState () inline override virtual
See AbstractAttribute::getState(...).
Implements llvm::AbstractAttribute.
Definition at line 521 of file Attributor.cpp.
indicateOptimisticFixpoint()
void AAReturnedValuesImpl::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint(...).
Implements llvm::AbstractState.
Definition at line 556 of file Attributor.cpp.
indicatePessimisticFixpoint()
void AAReturnedValuesImpl::indicatePessimisticFixpoint () inline override virtual
Indicate that the abstract state should converge to the pessimistic state.
This will usually revert the optimistically assumed state to the known to be true state.
Implements llvm::AbstractState.
Definition at line 560 of file Attributor.cpp.
initialize()
void AAReturnedValuesImpl::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::AbstractAttribute.
Definition at line 482 of file Attributor.cpp.
References F.
isAtFixpoint()
bool AAReturnedValuesImpl::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint().
Implements llvm::AbstractState.
Definition at line 550 of file Attributor.cpp.
isValidState()
bool AAReturnedValuesImpl::isValidState () const inline override virtual
See AbstractState::isValidState().
Implements llvm::AbstractState.
Definition at line 553 of file Attributor.cpp.
manifest()
ChangeStatus AAReturnedValuesImpl::manifest (Attributor & A) override virtual
See AbstractAttribute::manifest(...).
Reimplemented from llvm::AbstractAttribute.
Definition at line 566 of file Attributor.cpp.
References assert(), llvm::AbstractAttribute::manifest(), and llvm::UNCHANGED.
updateImpl()
ChangeStatus AAReturnedValuesImpl::updateImpl (Attributor & A) override virtual
See AbstractAttribute::updateImpl(Attributor &A).
Implements llvm::AbstractAttribute.
Definition at line 648 of file Attributor.cpp.
References assert(), llvm::CHANGED, llvm::dbgs(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgOperand(), LLVM_DEBUG, and llvm::UNCHANGED.
The documentation for this class was generated from the following file:
lib/Transforms/IPO/Attributor.cpp