LLVM: llvm::RemarkStreamer Class Reference
llvm::RemarkStreamer Class Reference
Streamer for remarks.
#include "llvm/IR/RemarkStreamer.h"
Public Member Functions
RemarkStreamer (StringRef Filename, std::unique_ptr< remarks::Serializer > Serializer)
StringRef getFilename () const
Return the filename that the remark diagnostics are emitted to.
raw_ostream & getStream ()
Return stream that the remark diagnostics are emitted to.
remarks::Serializer & getSerializer ()
Return the serializer used for this stream.
Error setFilter (StringRef Filter)
Set a pass filter based on a regex Filter.
void emit (const DiagnosticInfoOptimizationBase &Diag)
Emit a diagnostic through the streamer.
Detailed Description
Streamer for remarks.
Definition at line 27 of file RemarkStreamer.h.
Constructor & Destructor Documentation
RemarkStreamer()
RemarkStreamer::RemarkStreamer (StringRef Filename, std::unique_ptr< remarks::Serializer > Serializer)
Definition at line 22 of file RemarkStreamer.cpp.
References assert().
Member Function Documentation
emit()
void RemarkStreamer::emit (const DiagnosticInfoOptimizationBase & Diag)
Emit a diagnostic through the streamer.
Definition at line 94 of file RemarkStreamer.cpp.
References llvm::DiagnosticInfoOptimizationBase::getPassName().
getFilename()
StringRef llvm::RemarkStreamer::getFilename () const inline
Return the filename that the remark diagnostics are emitted to.
Definition at line 44 of file RemarkStreamer.h.
getSerializer()
remarks::Serializer & llvm::RemarkStreamer::getSerializer () inline
Return the serializer used for this stream.
Definition at line 48 of file RemarkStreamer.h.
getStream()
raw_ostream & llvm::RemarkStreamer::getStream () inline
Return stream that the remark diagnostics are emitted to.
Definition at line 46 of file RemarkStreamer.h.
setFilter()
Error RemarkStreamer::setFilter (StringRef Filter)
Set a pass filter based on a regex Filter.
Returns an error if the regex is invalid.
Definition at line 28 of file RemarkStreamer.cpp.
References llvm::createStringError(), and llvm::Error::success().
Referenced by llvm::setupOptimizationRemarks().
The documentation for this class was generated from the following files:
include/llvm/IR/RemarkStreamer.h
lib/IR/RemarkStreamer.cpp