LLVM: llvm::MCFixup Class Reference
llvm::MCFixup Class Reference
Encode information on a single operation to perform on a byte sequence (e.g., an encoded instruction) which requires assemble- or run- time patching.
#include "llvm/MC/MCFixup.h"
Public Member Functions
MCFixupKind getKind () const
uint32_t getOffset () const
void setOffset (uint32_t Value)
const MCExpr * getValue () const
SMLoc getLoc () const
Static Public Member Functions
static MCFixup create (uint32_t Offset, const MCExpr *Value, MCFixupKind Kind, SMLoc Loc=SMLoc())
static MCFixup createAddFor (const MCFixup &Fixup)
Return a fixup corresponding to the add half of a add/sub fixup pair for the given Fixup.
static MCFixup createSubFor (const MCFixup &Fixup)
Return a fixup corresponding to the sub half of a add/sub fixup pair for the given Fixup.
static MCFixupKind getKindForSize (unsigned Size, bool isPCRel)
Return the generic fixup kind for a value with the given size.
static MCFixupKind getAddKindForKind (unsigned Kind)
Return the generic fixup kind for an addition with a given size.
static MCFixupKind getSubKindForKind (unsigned Kind)
Return the generic fixup kind for an subtraction with a given size.
Detailed Description
Encode information on a single operation to perform on a byte sequence (e.g., an encoded instruction) which requires assemble- or run- time patching.
Fixups are used any time the target instruction encoder needs to represent some value in an instruction which is not yet concrete. The encoder will encode the instruction assuming the value is 0, and emit a fixup which communicates to the assembler backend how it should rewrite the encoded value.
During the process of relaxation, the assembler will apply fixups as symbolic values become concrete. When relaxation is complete, any remaining fixups become relocations in the object file (or errors, if the fixup cannot be encoded on the target).
Definition at line 74 of file MCFixup.h.
Member Function Documentation
create()
static MCFixup llvm::MCFixup::create (uint32_t Offset, const MCExpr * Value, MCFixupKind Kind, SMLoc Loc = SMLoc()) inline static
Definition at line 90 of file MCFixup.h.
References assert(), and llvm::MaxTargetFixupKind.
Referenced by getBranchTargetOpValue().
createAddFor()
static MCFixup llvm::MCFixup::createAddFor (const MCFixup & Fixup) inline static
Return a fixup corresponding to the add half of a add/sub fixup pair for the given Fixup.
Definition at line 103 of file MCFixup.h.
References Fixup, and getAddKindForKind().
createSubFor()
static MCFixup llvm::MCFixup::createSubFor (const MCFixup & Fixup) inline static
Return a fixup corresponding to the sub half of a add/sub fixup pair for the given Fixup.
Definition at line 114 of file MCFixup.h.
References Fixup, and getSubKindForKind().
getAddKindForKind()
static MCFixupKind llvm::MCFixup::getAddKindForKind (unsigned Kind) inline static
Return the generic fixup kind for an addition with a given size.
It is an error to pass an unsupported size.
Definition at line 144 of file MCFixup.h.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_Add_1, llvm::FK_Data_Add_2, llvm::FK_Data_Add_4, llvm::FK_Data_Add_8, and llvm_unreachable.
Referenced by createAddFor().
getKind()
MCFixupKind llvm::MCFixup::getKind () const inline
Definition at line 123 of file MCFixup.h.
Referenced by llvm::operator<<().
getKindForSize()
static MCFixupKind llvm::MCFixup::getKindForSize (unsigned Size, bool isPCRel) inline static
Return the generic fixup kind for a value with the given size.
It is an error to pass an unsupported size.
Definition at line 132 of file MCFixup.h.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm::FK_PCRel_8, isPCRel(), llvm_unreachable, and Size.
Referenced by llvm::MCObjectStreamer::EmitValueImpl(), and getImmFixupKind().
getLoc()
SMLoc llvm::MCFixup::getLoc () const inline
Definition at line 166 of file MCFixup.h.
getOffset()
uint32_t llvm::MCFixup::getOffset () const inline
Definition at line 125 of file MCFixup.h.
Referenced by llvm::operator<<().
getSubKindForKind()
static MCFixupKind llvm::MCFixup::getSubKindForKind (unsigned Kind) inline static
Return the generic fixup kind for an subtraction with a given size.
It is an error to pass an unsupported size.
Definition at line 156 of file MCFixup.h.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_Sub_1, llvm::FK_Data_Sub_2, llvm::FK_Data_Sub_4, llvm::FK_Data_Sub_8, and llvm_unreachable.
Referenced by createSubFor().
getValue()
const MCExpr * llvm::MCFixup::getValue () const inline
Definition at line 128 of file MCFixup.h.
Referenced by llvm::operator<<().
setOffset()
void llvm::MCFixup::setOffset (uint32_t Value) inline
Definition at line 126 of file MCFixup.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCFixup.h