LLVM: llvm::MCRegisterInfo Class Reference
llvm::MCRegisterInfo Class Reference
MCRegisterInfo base class - We assume that the target defines a static array of MCRegisterDesc objects that represent all of the machine registers that the target has.
#include "llvm/MC/MCRegisterInfo.h"
Classes
class DiffListIterator
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
struct DwarfLLVMRegPair
DwarfLLVMRegPair - Emitted by tablegen so Dwarf<->LLVM reg mappings can be performed with a binary search.
struct SubRegCoveredBits
SubRegCoveredBits - Emitted by tablegen: bit range covered by a subreg index, -1 in any being invalid.
Public Types
using regclass_iterator = const MCRegisterClass *
Public Member Functions
void InitMCRegisterInfo (const MCRegisterDesc *D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass *C, unsigned NC, const MCPhysReg(*RURoots)[2], unsigned NRU, const MCPhysReg *DL, const LaneBitmask *RUMS, const char *Strings, const char *ClassStrings, const uint16_t *SubIndices, unsigned NumIndices, const SubRegCoveredBits *SubIdxRanges, const uint16_t *RET)
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
void mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize LLVM register to Dwarf register number mapping.
void mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize Dwarf register to LLVM register number mapping.
void mapLLVMRegToSEHReg (unsigned LLVMReg, int SEHReg)
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
void mapLLVMRegToCVReg (unsigned LLVMReg, int CVReg)
unsigned getRARegister () const
This method should return the register where the return address can be found.
unsigned getProgramCounter () const
Return the register which is the program counter.
const MCRegisterDesc & operator[] (unsigned RegNo) const
const MCRegisterDesc & get (unsigned RegNo) const
Provide a get method, equivalent to [], but more useful with a pointer to this object.
unsigned getSubReg (unsigned Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
unsigned getMatchingSuperReg (unsigned Reg, unsigned SubIdx, const MCRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
unsigned getSubRegIndex (unsigned RegNo, unsigned SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
unsigned getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
unsigned getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
const char * getName (unsigned RegNo) const
Return the human-readable symbolic target-specific name for the specified physical register.
unsigned getNumRegs () const
Return the number of registers this target has (useful for sizing arrays holding per register information)
unsigned getNumSubRegIndices () const
Return the number of sub-register indices understood by the target.
unsigned getNumRegUnits () const
Return the number of (native) register units in the target.
int getDwarfRegNum (unsigned RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
int getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
int getLLVMRegNumFromEH (unsigned RegNum) const
Map a DWARF EH register back to a target register (same as getLLVMRegNum(RegNum, true)) but return -1 if there is no mapping, rather than asserting that there must be one.
int getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
int getSEHRegNum (unsigned RegNum) const
Map a target register to an equivalent SEH register number.
int getCodeViewRegNum (unsigned RegNum) const
Map a target register to an equivalent CodeView register number.
regclass_iterator regclass_begin () const
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const MCRegisterClass & getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const MCRegisterClass *Class) const
uint16_t getEncodingValue (unsigned RegNo) const
Returns the encoding for RegNo.
bool isSubRegister (unsigned RegA, unsigned RegB) const
Returns true if RegB is a sub-register of RegA.
bool isSuperRegister (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register of RegA.
bool isSubRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
bool isSuperRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register of RegA or if RegB == RegA.
bool isSuperOrSubRegisterEq (unsigned RegA, unsigned RegB) const
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
Friends
class MCSubRegIterator
class MCSubRegIndexIterator
class MCSuperRegIterator
class MCRegUnitIterator
class MCRegUnitMaskIterator
class MCRegUnitRootIterator
Detailed Description
MCRegisterInfo base class - We assume that the target defines a static array of MCRegisterDesc objects that represent all of the machine registers that the target has.
As such, we simply have to track a pointer to this array so that we can turn register number into a register descriptor.
Note this class is designed to be a base class of TargetRegisterInfo, which is the interface used by codegen. However, specific targets should never specialize this class. MCRegisterInfo should only contain getters to access TableGen generated physical register data. It must not be extended with virtual methods.
Definition at line 128 of file MCRegisterInfo.h.
Member Typedef Documentation
regclass_iterator
using llvm::MCRegisterInfo::regclass_iterator = const MCRegisterClass *
Definition at line 130 of file MCRegisterInfo.h.
Member Function Documentation
get()
const MCRegisterDesc & llvm::MCRegisterInfo::get (unsigned RegNo) const inline
Provide a get method, equivalent to [], but more useful with a pointer to this object.
Definition at line 339 of file MCRegisterInfo.h.
References operator[]().
Referenced by getName(), llvm::DWARFContext::getRegisterInfo(), getSubReg(), getSubRegIndex(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator(), llvm::MCSubRegIndexIterator::MCSubRegIndexIterator(), llvm::MCSubRegIterator::MCSubRegIterator(), and llvm::MCSuperRegIterator::MCSuperRegIterator().
getCodeViewRegNum()
int MCRegisterInfo::getCodeViewRegNum (unsigned RegNum) const
Map a target register to an equivalent CodeView register number.
Definition at line 125 of file MCRegisterInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getName(), getNumRegs(), I, and llvm::report_fatal_error().
getDwarfRegNum()
int MCRegisterInfo::getDwarfRegNum (unsigned RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
Returns -1 if there is no equivalent value. The second parameter allows targets to use different numberings for EH info and debugging info.
Definition at line 66 of file MCRegisterInfo.cpp.
References I, and Size.
Referenced by getDwarfRegNumFromDwarfEHRegNum().
getDwarfRegNumFromDwarfEHRegNum()
int MCRegisterInfo::getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
Definition at line 104 of file MCRegisterInfo.cpp.
References getDwarfRegNum(), and getLLVMRegNumFromEH().
getEncodingValue()
uint16_t llvm::MCRegisterInfo::getEncodingValue (unsigned RegNo) const inline
Returns the encoding for RegNo.
Definition at line 442 of file MCRegisterInfo.h.
References assert().
Referenced by llvm::MipsTargetELFStreamer::emitFrame(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::MipsMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::PPCInstPrinter::printOperand(), llvm::MipsRegInfoRecord::SetPhysRegUsed(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
getLLVMRegNum()
int MCRegisterInfo::getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
Definition at line 79 of file MCRegisterInfo.cpp.
References assert(), I, and Size.
Referenced by llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding().
getLLVMRegNumFromEH()
int MCRegisterInfo::getLLVMRegNumFromEH (unsigned RegNum) const
Map a DWARF EH register back to a target register (same as getLLVMRegNum(RegNum, true)) but return -1 if there is no mapping, rather than asserting that there must be one.
Definition at line 91 of file MCRegisterInfo.cpp.
References I, and Size.
Referenced by getDwarfRegNumFromDwarfEHRegNum().
getMatchingSuperReg()
unsigned MCRegisterInfo::getMatchingSuperReg (unsigned Reg, unsigned SubIdx, const MCRegisterClass * RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
Definition at line 23 of file MCRegisterInfo.cpp.
References llvm::MCRegisterClass::contains(), getSubReg(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::ARMInstPrinter::printInst(), and llvm::AArch64InstPrinter::printVectorList().
getName()
const char * llvm::MCRegisterInfo::getName (unsigned RegNo) const inline
Return the human-readable symbolic target-specific name for the specified physical register.
Definition at line 370 of file MCRegisterInfo.h.
References get(), and llvm::MCRegisterDesc::Name.
Referenced by llvm::mca::RegisterFile::addRegisterWrite(), llvm::mca::RegisterFile::dump(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), getCodeViewRegNum(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::TargetRegisterInfo::getRegAsmName(), llvm::HexagonMCChecker::reportErrorNewValue(), and llvm::HexagonMCChecker::reportErrorRegisters().
getNumRegClasses()
unsigned llvm::MCRegisterInfo::getNumRegClasses () const inline
Definition at line 426 of file MCRegisterInfo.h.
References regclass_begin(), and regclass_end().
Referenced by getRegClass().
getNumRegs()
unsigned llvm::MCRegisterInfo::getNumRegs () const inline
Return the number of registers this target has (useful for sizing arrays holding per register information)
Definition at line 376 of file MCRegisterInfo.h.
Referenced by llvm::MachineFunction::allocateRegMask(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::CCState::CCState(), llvm::TargetRegisterInfo::checkAllSuperRegsMarked(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::mca::RegisterFile::dump(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::TargetRegisterInfo::getAllocatableSet(), getCodeViewRegNum(), llvm::RegScavenger::getRegsAvailable(), getSubRegIndex(), llvm::MachineRegisterInfo::MachineRegisterInfo(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::CriticalAntiDepBreaker::Observe(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::TargetRegisterInfo::regmaskSubsetEqual(), llvm::InterferenceCache::reinitPhysRegEntries(), llvm::rdf::Liveness::resetKills(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::AggressiveAntiDepBreaker::StartBlock(), and llvm::CriticalAntiDepBreaker::StartBlock().
getNumRegUnits()
unsigned llvm::MCRegisterInfo::getNumRegUnits () const inline
Return the number of (native) register units in the target.
Register units are numbered from 0 to getNumRegUnits() - 1. They can be accessed through MCRegUnitIterator defined below.
Definition at line 390 of file MCRegisterInfo.h.
Referenced by llvm::LiveRegUnits::addRegsInMask(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::LiveRegUnits::removeRegsNotPreserved(), llvm::LiveIntervals::runOnMachineFunction(), and llvm::ReachingDefAnalysis::runOnMachineFunction().
getNumSubRegIndices()
unsigned llvm::MCRegisterInfo::getNumSubRegIndices () const inline
Return the number of sub-register indices understood by the target.
Index 0 is reserved for the no-op sub-register, while 1 to getNumSubRegIndices() - 1 represent real sub-registers.
Definition at line 383 of file MCRegisterInfo.h.
Referenced by llvm::AVRInstPrinter::getPrettyRegisterName(), getSubReg(), getSubRegIdxOffset(), getSubRegIdxSize(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), and llvm::TargetRegisterInfo::getSubRegIndexName().
getProgramCounter()
unsigned llvm::MCRegisterInfo::getProgramCounter () const inline
Return the register which is the program counter.
Definition at line 327 of file MCRegisterInfo.h.
Referenced by llvm::MCInstrDesc::mayAffectControlFlow().
getRARegister()
unsigned llvm::MCRegisterInfo::getRARegister () const inline
This method should return the register where the return address can be found.
Definition at line 322 of file MCRegisterInfo.h.
Referenced by llvm::MipsAsmPrinter::emitFrameDirective().
getRegClass()
const MCRegisterClass & llvm::MCRegisterInfo::getRegClass (unsigned i) const inline
Returns the register class associated with the enumeration value.
See class MCOperandInfo.
Definition at line 432 of file MCRegisterInfo.h.
References assert(), and getNumRegClasses().
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getReg(), llvm::ARMInstPrinter::printInst(), llvm::AMDGPUInstPrinter::printRegOperand(), and llvm::AArch64InstPrinter::printVectorList().
getRegClassName()
const char * llvm::MCRegisterInfo::getRegClassName (const MCRegisterClass * Class) const inline
Definition at line 437 of file MCRegisterInfo.h.
Referenced by llvm::TargetRegisterInfo::getRegClassName().
getSEHRegNum()
int MCRegisterInfo::getSEHRegNum (unsigned RegNum) const
Map a target register to an equivalent SEH register number.
Returns LLVM register number if there is no equivalent value.
Definition at line 119 of file MCRegisterInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
getSubReg()
unsigned MCRegisterInfo::getSubReg (unsigned Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
Return zero if the sub-register does not exist.
Definition at line 31 of file MCRegisterInfo.cpp.
References assert(), get(), getNumSubRegIndices(), Idx, llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegisterDesc::SubRegIndices.
Referenced by addSavedGPR(), llvm::AMDGPUDisassembler::convertMIMGInst(), copyHint(), getMatchingSuperReg(), getPairedGPR(), llvm::AVRInstPrinter::getPrettyRegisterName(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::ARMInstPrinter::printGPRPairOperand(), llvm::AArch64InstPrinter::printGPRSeqPairsClassOperand(), llvm::ARMInstPrinter::printMVEVectorList(), llvm::AArch64InstPrinter::printVectorList(), llvm::ARMInstPrinter::printVectorListTwo(), llvm::ARMInstPrinter::printVectorListTwoAllLanes(), llvm::ARMInstPrinter::printVectorListTwoSpaced(), llvm::ARMInstPrinter::printVectorListTwoSpacedAllLanes(), and llvm::MachineInstr::substituteRegister().
getSubRegIdxOffset()
unsigned MCRegisterInfo::getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
If an Offset doesn't make sense (the index isn't continuous, or is used to access sub-registers at different offsets), return -1.
Definition at line 60 of file MCRegisterInfo.cpp.
References assert(), getNumSubRegIndices(), Idx, and llvm::MCRegisterInfo::SubRegCoveredBits::Offset.
getSubRegIdxSize()
unsigned MCRegisterInfo::getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
If the index isn't continuous, return the sum of the sizes of its parts. If the index is used to access subregisters of different sizes, return -1.
Definition at line 54 of file MCRegisterInfo.cpp.
References assert(), getNumSubRegIndices(), Idx, and llvm::MCRegisterInfo::SubRegCoveredBits::Size.
getSubRegIndex()
unsigned MCRegisterInfo::getSubRegIndex (unsigned RegNo, unsigned SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
Return zero otherwise.
Definition at line 43 of file MCRegisterInfo.cpp.
References assert(), get(), getNumRegs(), llvm::MCRegisterInfo::DiffListIterator::isValid(), SubReg, and llvm::MCRegisterDesc::SubRegIndices.
Referenced by llvm::rdf::PhysicalRegisterInfo::mapTo().
InitMCRegisterInfo()
void llvm::MCRegisterInfo::InitMCRegisterInfo (const MCRegisterDesc * D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass * C, unsigned NC, const MCPhysReg(*) RURoots[2], unsigned NRU, const MCPhysReg * DL, const LaneBitmask * RUMS, const char * Strings, const char * ClassStrings, const uint16_t * SubIndices, unsigned NumIndices, const SubRegCoveredBits * SubIdxRanges, const uint16_t * RET) inline
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
DO NOT USE.
Definition at line 238 of file MCRegisterInfo.h.
References C, D, NC, and RA.
isSubRegister()
bool llvm::MCRegisterInfo::isSubRegister (unsigned RegA, unsigned RegB) const inline
Returns true if RegB is a sub-register of RegA.
Definition at line 449 of file MCRegisterInfo.h.
References isSuperRegister().
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), and llvm::AggressiveAntiDepBreaker::BreakAntiDependencies().
isSubRegisterEq()
bool llvm::MCRegisterInfo::isSubRegisterEq (unsigned RegA, unsigned RegB) const inline
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
Definition at line 457 of file MCRegisterInfo.h.
References isSuperRegisterEq().
Referenced by llvm::MCInstrDesc::hasDefOfPhysReg(), and isSuperOrSubRegisterEq().
isSuperOrSubRegisterEq()
bool llvm::MCRegisterInfo::isSuperOrSubRegisterEq (unsigned RegA, unsigned RegB) const inline
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
Definition at line 469 of file MCRegisterInfo.h.
References isSubRegisterEq(), and isSuperRegister().
isSuperRegister()
bool llvm::MCRegisterInfo::isSuperRegister (unsigned RegA, unsigned RegB) const inline
Returns true if RegB is a super-register of RegA.
Definition at line 545 of file MCRegisterInfo.h.
References I.
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), isSubRegister(), isSuperOrSubRegisterEq(), and isSuperRegisterEq().
isSuperRegisterEq()
bool llvm::MCRegisterInfo::isSuperRegisterEq (unsigned RegA, unsigned RegB) const inline
Returns true if RegB is a super-register of RegA or if RegB == RegA.
Definition at line 463 of file MCRegisterInfo.h.
References isSuperRegister().
Referenced by isSubRegisterEq().
mapDwarfRegsToLLVMRegs()
void llvm::MCRegisterInfo::mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair * Map, unsigned Size, bool isEH) inline
Used to initialize Dwarf register to LLVM register number mapping.
Called by TableGen auto-generated routines. DO NOT USE.
Definition at line 296 of file MCRegisterInfo.h.
References Size.
mapLLVMRegsToDwarfRegs()
void llvm::MCRegisterInfo::mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair * Map, unsigned Size, bool isEH) inline
Used to initialize LLVM register to Dwarf register number mapping.
Called by TableGen auto-generated routines. DO NOT USE.
Definition at line 282 of file MCRegisterInfo.h.
References Size.
mapLLVMRegToCVReg()
void llvm::MCRegisterInfo::mapLLVMRegToCVReg (unsigned LLVMReg, int CVReg) inline
Definition at line 316 of file MCRegisterInfo.h.
mapLLVMRegToSEHReg()
void llvm::MCRegisterInfo::mapLLVMRegToSEHReg (unsigned LLVMReg, int SEHReg) inline
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
By default the SEH register number is just the same as the LLVM register number. FIXME: TableGen these numbers. Currently this requires target specific initialization code.
Definition at line 312 of file MCRegisterInfo.h.
operator[]()
const MCRegisterDesc & llvm::MCRegisterInfo::operator[] (unsigned RegNo) const inline
Definition at line 331 of file MCRegisterInfo.h.
References assert().
Referenced by get().
regclass_begin()
regclass_iterator llvm::MCRegisterInfo::regclass_begin () const inline
Definition at line 420 of file MCRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclass_end()
regclass_iterator llvm::MCRegisterInfo::regclass_end () const inline
Definition at line 421 of file MCRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclasses()
iterator_range< regclass_iterator > llvm::MCRegisterInfo::regclasses () const inline
Definition at line 422 of file MCRegisterInfo.h.
References llvm::make_range(), regclass_begin(), and regclass_end().
Friends And Related Function Documentation
MCRegUnitIterator
friend class MCRegUnitIterator friend
Definition at line 232 of file MCRegisterInfo.h.
MCRegUnitMaskIterator
friend class MCRegUnitMaskIterator friend
Definition at line 233 of file MCRegisterInfo.h.
MCRegUnitRootIterator
friend class MCRegUnitRootIterator friend
Definition at line 234 of file MCRegisterInfo.h.
MCSubRegIndexIterator
friend class MCSubRegIndexIterator friend
Definition at line 230 of file MCRegisterInfo.h.
MCSubRegIterator
friend class MCSubRegIterator friend
Definition at line 229 of file MCRegisterInfo.h.
MCSuperRegIterator
friend class MCSuperRegIterator friend
Definition at line 231 of file MCRegisterInfo.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCRegisterInfo.h
lib/MC/MCRegisterInfo.cpp