LLVM: llvm::Argument Class Reference
llvm::Argument Class Reference final
This class represents an incoming formal argument to a Function.
#include "llvm/IR/Argument.h"
Public Member Functions
Argument (Type *Ty, const Twine &Name="", Function *F=nullptr, unsigned ArgNo=0)
Argument constructor.
const Function * getParent () const
Function * getParent ()
unsigned getArgNo () const
Return the index of this formal argument in its containing function.
bool hasNonNullAttr () const
Return true if this argument has the nonnull attribute.
uint64_t getDereferenceableBytes () const
If this argument has the dereferenceable attribute, return the number of bytes known to be dereferenceable.
uint64_t getDereferenceableOrNullBytes () const
If this argument has the dereferenceable_or_null attribute, return the number of bytes known to be dereferenceable.
bool hasByValAttr () const
Return true if this argument has the byval attribute.
bool hasSwiftSelfAttr () const
Return true if this argument has the swiftself attribute.
bool hasSwiftErrorAttr () const
Return true if this argument has the swifterror attribute.
bool hasByValOrInAllocaAttr () const
Return true if this argument has the byval attribute or inalloca attribute.
unsigned getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
Type * getParamByValType () const
If this is a byval argument, return its type.
bool hasNestAttr () const
Return true if this argument has the nest attribute.
bool hasNoAliasAttr () const
Return true if this argument has the noalias attribute.
bool hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute.
bool hasStructRetAttr () const
Return true if this argument has the sret attribute.
bool hasInRegAttr () const
Return true if this argument has the inreg attribute.
bool hasReturnedAttr () const
Return true if this argument has the returned attribute.
bool onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute.
bool hasInAllocaAttr () const
Return true if this argument has the inalloca attribute.
bool hasZExtAttr () const
Return true if this argument has the zext attribute.
bool hasSExtAttr () const
Return true if this argument has the sext attribute.
void addAttrs (AttrBuilder &B)
Add attributes to an argument.
void addAttr (Attribute::AttrKind Kind)
void addAttr (Attribute Attr)
void removeAttr (Attribute::AttrKind Kind)
Remove attributes from an argument.
bool hasAttribute (Attribute::AttrKind Kind) const
Check if an argument has a given attribute.
Attribute getAttribute (Attribute::AttrKind Kind) const
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCasts ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs, aliases and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripPointerCastsNoFollowAliases () const
Strip off pointer casts and all-zero GEPs.
Value * stripPointerCastsNoFollowAliases ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
unsigned getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Method for support type inquiry through isa, cast, and dyn_cast.
Friends
class Function
Additional Inherited Members
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This class represents an incoming formal argument to a Function.
A formal argument, since it is `‘formal’', does not contain an actual value but instead represents the type, argument number, and attributes of an argument for a specific function. When used in the body of said function, the argument of course represents the value of the actual argument that the function was called with.
Definition at line 29 of file Argument.h.
Constructor & Destructor Documentation
Argument()
Argument::Argument (Type * Ty, const Twine & Name = "", Function * F = nullptr, unsigned ArgNo = 0) explicit
Argument constructor.
Definition at line 66 of file Function.cpp.
References llvm::Value::setName().
Member Function Documentation
addAttr() [1/2]
void Argument::addAttr (Attribute Attr)
Definition at line 185 of file Function.cpp.
References llvm::Function::addParamAttr(), getArgNo(), and getParent().
addAttr() [2/2]
void Argument::addAttr (Attribute::AttrKind Kind)
Definition at line 181 of file Function.cpp.
References llvm::Function::addParamAttr(), getArgNo(), and getParent().
addAttrs()
void Argument::addAttrs (AttrBuilder & B)
Add attributes to an argument.
Definition at line 175 of file Function.cpp.
References llvm::AttributeList::addParamAttributes(), getArgNo(), llvm::Function::getAttributes(), llvm::Function::getContext(), getParent(), and llvm::Function::setAttributes().
classof()
static bool llvm::Argument::classof (const Value * V) inline static
Method for support type inquiry through isa, cast, and dyn_cast.
Definition at line 130 of file Argument.h.
References llvm::Value::getValueID().
getArgNo()
unsigned llvm::Argument::getArgNo () const inline
Return the index of this formal argument in its containing function.
For example in "void foo(int a, float b)" a is 0 and b is 1.
Definition at line 47 of file Argument.h.
References assert().
Referenced by addAttr(), addAttrs(), allCallersPassValidPointerForArgument(), getAttribute(), llvm::AbstractCallSite::getCallArgOperand(), llvm::AbstractCallSite::getCallArgOperandNo(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getParamAlignment(), getParamByValType(), hasAttribute(), hasByValOrInAllocaAttr(), hasNonNullAttr(), hasSwiftErrorAttr(), hasSwiftSelfAttr(), onlyReadsMemory(), removeAttr(), and AANonNullArgument::updateImpl().
getAttribute()
Attribute Argument::getAttribute (Attribute::AttrKind Kind) const
Definition at line 197 of file Function.cpp.
References getArgNo(), llvm::Function::getParamAttribute(), and getParent().
getDereferenceableBytes()
uint64_t Argument::getDereferenceableBytes () const
If this argument has the dereferenceable attribute, return the number of bytes known to be dereferenceable.
Otherwise, zero is returned.
Definition at line 121 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamDereferenceableBytes(), getParent(), and llvm::Value::getType().
Referenced by hasNonNullAttr().
getDereferenceableOrNullBytes()
uint64_t Argument::getDereferenceableOrNullBytes () const
If this argument has the dereferenceable_or_null attribute, return the number of bytes known to be dereferenceable.
Otherwise, zero is returned.
Definition at line 127 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamDereferenceableOrNullBytes(), getParent(), and llvm::Value::getType().
getParamAlignment()
unsigned Argument::getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
Definition at line 111 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamAlignment(), getParent(), and llvm::Value::getType().
getParamByValType()
Type * Argument::getParamByValType () const
If this is a byval argument, return its type.
Definition at line 116 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamByValType(), getParent(), and llvm::Value::getType().
getParent() [1/2]
Function * llvm::Argument::getParent () inline
Definition at line 42 of file Argument.h.
getParent() [2/2]
const Function * llvm::Argument::getParent () const inline
Definition at line 41 of file Argument.h.
Referenced by addAttr(), addAttrs(), allCallersPassValidPointerForArgument(), getAttribute(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getParamAlignment(), getParamByValType(), hasAttribute(), hasByValOrInAllocaAttr(), hasNonNullAttr(), hasSwiftErrorAttr(), hasSwiftSelfAttr(), isSafeToPromoteArgument(), onlyReadsMemory(), and removeAttr().
hasAttribute()
bool Argument::hasAttribute (Attribute::AttrKind Kind) const
Check if an argument has a given attribute.
Definition at line 193 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
Referenced by hasByValAttr(), hasInAllocaAttr(), hasInRegAttr(), hasNestAttr(), hasNoAliasAttr(), hasNoCaptureAttr(), hasReturnedAttr(), hasSExtAttr(), hasStructRetAttr(), and hasZExtAttr().
hasByValAttr()
bool Argument::hasByValAttr () const
Return true if this argument has the byval attribute.
Definition at line 86 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
Referenced by canPaddingBeAccessed(), and PropagateConstantsIntoArguments().
hasByValOrInAllocaAttr()
bool Argument::hasByValOrInAllocaAttr () const
Return true if this argument has the byval attribute or inalloca attribute.
These attributes represent arguments being passed by value.
Definition at line 104 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Value::getType().
hasInAllocaAttr()
bool Argument::hasInAllocaAttr () const
Return true if this argument has the inalloca attribute.
Definition at line 99 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
Referenced by PropagateConstantsIntoArguments().
hasInRegAttr()
bool Argument::hasInRegAttr () const
Return true if this argument has the inreg attribute.
Definition at line 153 of file Function.cpp.
References hasAttribute().
hasNestAttr()
bool Argument::hasNestAttr () const
Return true if this argument has the nest attribute.
Definition at line 133 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNoAliasAttr()
bool Argument::hasNoAliasAttr () const
Return true if this argument has the noalias attribute.
Definition at line 138 of file Function.cpp.
References llvm::Value::getType(), hasAttribute(), and llvm::NoAlias.
hasNoCaptureAttr()
bool Argument::hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute.
Definition at line 143 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNonNullAttr()
bool Argument::hasNonNullAttr () const
Return true if this argument has the nonnull attribute.
Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0).
Definition at line 75 of file Function.cpp.
References getArgNo(), getDereferenceableBytes(), getParent(), llvm::Value::getType(), and llvm::NullPointerIsDefined().
Referenced by AANonNullArgument::initialize().
hasReturnedAttr()
bool Argument::hasReturnedAttr () const
Return true if this argument has the returned attribute.
Definition at line 157 of file Function.cpp.
References hasAttribute().
hasSExtAttr()
bool Argument::hasSExtAttr () const
Return true if this argument has the sext attribute.
Definition at line 165 of file Function.cpp.
References hasAttribute().
hasStructRetAttr()
bool Argument::hasStructRetAttr () const
Return true if this argument has the sret attribute.
Definition at line 148 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasSwiftErrorAttr()
bool Argument::hasSwiftErrorAttr () const
Return true if this argument has the swifterror attribute.
Definition at line 95 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
hasSwiftSelfAttr()
bool Argument::hasSwiftSelfAttr () const
Return true if this argument has the swiftself attribute.
Definition at line 91 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
hasZExtAttr()
bool Argument::hasZExtAttr () const
Return true if this argument has the zext attribute.
Definition at line 161 of file Function.cpp.
References hasAttribute().
onlyReadsMemory()
bool Argument::onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute.
Definition at line 169 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::FunctionSummary::FFlags::ReadNone, and llvm::ValueInfo::ReadOnly.
Referenced by llvm::objcarc::CanAlterRefCount(), llvm::canSinkOrHoistInst(), and checkFunctionMemoryAccess().
removeAttr()
void Argument::removeAttr (Attribute::AttrKind Kind)
Remove attributes from an argument.
Definition at line 189 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::removeParamAttr().
Friends And Related Function Documentation
Function
friend class Function friend
Definition at line 33 of file Argument.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Argument.h
lib/IR/Function.cpp