LLVM: llvm::codeview::DebugChecksumsSubsection Class Reference
llvm::codeview::DebugChecksumsSubsection Class Reference final
#include "llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h"
Public Member Functions
DebugChecksumsSubsection (DebugStringTableSubsection &Strings)
void addChecksum (StringRef FileName, FileChecksumKind Kind, ArrayRef< uint8_t > Bytes)
uint32_t calculateSerializedSize () const override
Error commit (BinaryStreamWriter &Writer) const override
uint32_t mapChecksumOffset (StringRef FileName) const
Public Member Functions inherited from llvm::codeview::DebugSubsection
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
virtual Error commit (BinaryStreamWriter &Writer) const =0
virtual uint32_t calculateSerializedSize () const =0
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsection
static bool classof (const DebugSubsection *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsection
DebugSubsectionKind Kind
Detailed Description
Definition at line 75 of file DebugChecksumsSubsection.h.
Constructor & Destructor Documentation
DebugChecksumsSubsection()
DebugChecksumsSubsection::DebugChecksumsSubsection (DebugStringTableSubsection & Strings) explicit
Definition at line 63 of file DebugChecksumsSubsection.cpp.
Member Function Documentation
addChecksum()
void DebugChecksumsSubsection::addChecksum (StringRef FileName, FileChecksumKind Kind, ArrayRef< uint8_t > Bytes)
Definition at line 67 of file DebugChecksumsSubsection.cpp.
References llvm::alignTo(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::codeview::Copy, llvm::codeview::DebugStringTableSubsection::insert(), and llvm::codeview::DebugSubsection::Kind.
calculateSerializedSize()
uint32_t DebugChecksumsSubsection::calculateSerializedSize () const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 90 of file DebugChecksumsSubsection.cpp.
classof()
static bool llvm::codeview::DebugChecksumsSubsection::classof (const DebugSubsection * S) inline static
Definition at line 79 of file DebugChecksumsSubsection.h.
References llvm::codeview::FileChecksums, and llvm::codeview::DebugSubsection::kind().
commit()
Error DebugChecksumsSubsection::commit (BinaryStreamWriter & Writer) const override virtual
Implements llvm::codeview::DebugSubsection.
Definition at line 94 of file DebugChecksumsSubsection.cpp.
References FileChecksumEntryHeader::ChecksumKind, FileChecksumEntryHeader::ChecksumSize, llvm::codeview::EC, FileChecksumEntryHeader::FileNameOffset, llvm::BinaryStreamWriter::padToAlignment(), llvm::Error::success(), llvm::BinaryStreamWriter::writeArray(), and llvm::BinaryStreamWriter::writeObject().
mapChecksumOffset()
uint32_t DebugChecksumsSubsection::mapChecksumOffset (StringRef FileName) const
Definition at line 110 of file DebugChecksumsSubsection.cpp.
References assert(), and llvm::codeview::DebugStringTableSubsection::getIdForString().
Referenced by llvm::codeview::DebugInlineeLinesSubsection::addExtraFile(), llvm::codeview::DebugInlineeLinesSubsection::addInlineSite(), and llvm::codeview::DebugLinesSubsection::createBlock().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h
lib/DebugInfo/CodeView/DebugChecksumsSubsection.cpp