LLVM: llvm::DominanceFrontierWrapperPass Class Reference
llvm::DominanceFrontierWrapperPass Class Reference
#include "llvm/Analysis/DominanceFrontier.h"
Public Member Functions
DominanceFrontierWrapperPass ()
DominanceFrontier & getDominanceFrontier ()
const DominanceFrontier & getDominanceFrontier () const
void releaseMemory () override
bool runOnFunction (Function &) override
void getAnalysisUsage (AnalysisUsage &AU) const override
void print (raw_ostream &OS, const Module *=nullptr) const override
void dump () const
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 156 of file DominanceFrontier.h.
Constructor & Destructor Documentation
DominanceFrontierWrapperPass()
Dominance Frontier true DominanceFrontierWrapperPass::DominanceFrontierWrapperPass ()
Definition at line 38 of file DominanceFrontier.cpp.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void DominanceFrontierWrapperPass::dump () const
Definition at line 63 of file DominanceFrontier.cpp.
References llvm::dbgs(), and print().
getAnalysisUsage()
void DominanceFrontierWrapperPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 53 of file DominanceFrontier.cpp.
getDominanceFrontier() [1/2]
DominanceFrontier & llvm::DominanceFrontierWrapperPass::getDominanceFrontier () inline
Definition at line 164 of file DominanceFrontier.h.
getDominanceFrontier() [2/2]
const DominanceFrontier & llvm::DominanceFrontierWrapperPass::getDominanceFrontier () const inline
Definition at line 165 of file DominanceFrontier.h.
print()
void DominanceFrontierWrapperPass::print (raw_ostream & OS, const Module * = nullptr) const override
Definition at line 58 of file DominanceFrontier.cpp.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::print().
Referenced by dump().
releaseMemory()
void DominanceFrontierWrapperPass::releaseMemory () override
Definition at line 43 of file DominanceFrontier.cpp.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::releaseMemory().
Referenced by runOnFunction().
runOnFunction()
bool DominanceFrontierWrapperPass::runOnFunction (Function &) override
Definition at line 47 of file DominanceFrontier.cpp.
References llvm::ForwardDominanceFrontierBase< BlockT >::analyze(), and releaseMemory().
Member Data Documentation
ID
char DominanceFrontierWrapperPass::ID = 0 static
Definition at line 160 of file DominanceFrontier.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DominanceFrontier.h
lib/Analysis/DominanceFrontier.cpp