LLVM: llvm::HexagonTTIImpl Class Reference
llvm::HexagonTTIImpl Class Reference
#include "Target/Hexagon/HexagonTargetTransformInfo.h"
Public Member Functions
HexagonTTIImpl (const HexagonTargetMachine *TM, const Function &F)
int getUserCost (const User *U, ArrayRef< const Value * > Operands)
bool shouldBuildLookupTables () const
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool shouldFavorPostInc () const
Bias LSR towards creating post-increment opportunities.
unsigned getPrefetchDistance () const
— Vector TTI end —
unsigned getCacheLineSize () const
Vector TTI Implementations
unsigned getNumberOfRegisters (bool vector) const
— Vector TTI begin —
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth () const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldMaximizeVectorBandwidth (bool OptSize) const
bool supportsEfficientVectorElementLoadStore ()
bool hasBranchDivergence ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
bool prefersVectorizedAddressing ()
bool enableInterleavedAccessVectorization ()
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=UINT_MAX)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *SE, const SCEV *S)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >())
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
Public Member Functions inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
int getInstructionLatency (const Instruction *I)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getScalarizationOverhead (Type *VecTy, ArrayRef< const Value * > Args)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >())
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
Get intrinsic cost based on arguments.
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=std::numeric_limits< unsigned >::max())
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwise, bool)
Try to calculate op costs for min/max reduction operations.
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
unsigned getCallCost (const Function *F, int NumArgs, const User *U)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getUserCost (const User *U, ArrayRef< const Value * > Operands)
int getInstructionLatency (const Instruction *I)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType)
bool isLegalMaskedLoad (Type *DataType)
bool isLegalNTStore (Type *DataType, unsigned Alignment)
bool isLegalNTLoad (Type *DataType, unsigned Alignment)
bool isLegalMaskedScatter (Type *DataType)
bool isLegalMaskedGather (Type *DataType)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize ()
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level)
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level)
unsigned getPrefetchDistance ()
unsigned getMinPrefetchStride ()
unsigned getMaxPrefetchIterationsAhead ()
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value * > Args)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument * > &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 33 of file HexagonTargetTransformInfo.h.
Constructor & Destructor Documentation
HexagonTTIImpl()
llvm::HexagonTTIImpl::HexagonTTIImpl (const HexagonTargetMachine * TM, const Function & F) inline explicit
Definition at line 54 of file HexagonTargetTransformInfo.h.
Member Function Documentation
enableAggressiveInterleaving()
bool llvm::HexagonTTIImpl::enableAggressiveInterleaving (bool LoopHasReductions) inline
Definition at line 94 of file HexagonTargetTransformInfo.h.
enableInterleavedAccessVectorization()
bool llvm::HexagonTTIImpl::enableInterleavedAccessVectorization () inline
Definition at line 100 of file HexagonTargetTransformInfo.h.
getAddressComputationCost()
unsigned HexagonTTIImpl::getAddressComputationCost (Type * Tp, ScalarEvolution * SE, const SCEV * S)
Definition at line 147 of file HexagonTargetTransformInfo.cpp.
getArithmeticInstrCost()
unsigned HexagonTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value * > Args = ArrayRef<const Value *>())
Definition at line 228 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::BasicTTIImplBase< HexagonTTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::Type::isVectorTy().
getCacheLineSize()
unsigned HexagonTTIImpl::getCacheLineSize () const
Definition at line 279 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getL1CacheLineSize().
getCallInstrCost()
unsigned HexagonTTIImpl::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys)
Definition at line 126 of file HexagonTargetTransformInfo.cpp.
References F, llvm::BasicTTIImplBase< HexagonTTIImpl >::getCallInstrCost(), and RetTy.
getCastInstrCost()
unsigned HexagonTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * I = nullptr)
Definition at line 241 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::Type::isFPOrFPVectorTy().
getCFInstrCost()
unsigned llvm::HexagonTTIImpl::getCFInstrCost (unsigned Opcode) inline
Definition at line 139 of file HexagonTargetTransformInfo.h.
getCmpSelInstrCost()
unsigned HexagonTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, const Instruction * I)
Definition at line 218 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::BasicTTIImplBase< HexagonTTIImpl >::getCmpSelInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), I, and llvm::Type::isVectorTy().
getGatherScatterOpCost()
unsigned HexagonTTIImpl::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, Value * Ptr, bool VariableMask, unsigned Alignment)
Definition at line 201 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::getGatherScatterOpCost().
getInterleavedMemoryOpCost()
unsigned HexagonTTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 207 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getInterleavedMemoryOpCost(), getMemoryOpCost(), and llvm::ArrayRef< T >::size().
getIntrinsicInstrCost() [1/2]
unsigned HexagonTTIImpl::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed = UINT_MAX)
Definition at line 136 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, llvm::BasicTTIImplBase< HexagonTTIImpl >::getIntrinsicInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), and RetTy.
getIntrinsicInstrCost() [2/2]
unsigned HexagonTTIImpl::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF)
Definition at line 131 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getIntrinsicInstrCost(), and RetTy.
getMaskedMemoryOpCost()
unsigned HexagonTTIImpl::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Definition at line 191 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::getMaskedMemoryOpCost().
getMaxInterleaveFactor()
unsigned HexagonTTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 100 of file HexagonTargetTransformInfo.cpp.
getMemoryOpCost()
unsigned HexagonTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace, const Instruction * I = nullptr)
Definition at line 152 of file HexagonTargetTransformInfo.cpp.
References llvm::alignTo(), assert(), FloatFactor, llvm::VectorType::getBitWidth(), llvm::SequentialType::getElementType(), llvm::BasicTTIImplBase< HexagonTTIImpl >::getMemoryOpCost(), getRegisterBitWidth(), I, llvm::Type::isFloatingPointTy(), llvm::Type::isVectorTy(), and llvm::Log2_32().
Referenced by getInterleavedMemoryOpCost().
getMinimumVF()
unsigned HexagonTTIImpl::getMinimumVF (unsigned ElemWidth) const
Definition at line 112 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getVectorLength().
getMinVectorRegisterBitWidth()
unsigned HexagonTTIImpl::getMinVectorRegisterBitWidth () const
Definition at line 108 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getVectorLength().
Referenced by getRegisterBitWidth().
getNumberOfRegisters()
unsigned HexagonTTIImpl::getNumberOfRegisters (bool vector) const
— Vector TTI begin —
Definition at line 94 of file HexagonTargetTransformInfo.cpp.
getOperandsScalarizationOverhead()
unsigned HexagonTTIImpl::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Definition at line 121 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getOperandsScalarizationOverhead().
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind HexagonTTIImpl::getPopcntSupport (unsigned IntTyWidthInBit) const
Definition at line 69 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::PSK_FastHardware.
getPrefetchDistance()
unsigned HexagonTTIImpl::getPrefetchDistance () const
— Vector TTI end —
Definition at line 275 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getL1PrefetchDistance().
getRegisterBitWidth()
unsigned HexagonTTIImpl::getRegisterBitWidth (bool Vector) const
Definition at line 104 of file HexagonTargetTransformInfo.cpp.
References getMinVectorRegisterBitWidth().
Referenced by getMemoryOpCost().
getScalarizationOverhead()
unsigned HexagonTTIImpl::getScalarizationOverhead (Type * Ty, bool Insert, bool Extract)
Definition at line 116 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getScalarizationOverhead().
getShuffleCost()
unsigned HexagonTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Definition at line 196 of file HexagonTargetTransformInfo.cpp.
getUnrollingPreferences()
void HexagonTTIImpl::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP)
Definition at line 76 of file HexagonTargetTransformInfo.cpp.
References llvm::canPeel(), llvm::LoopBase< BlockT, LoopT >::empty(), llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::TargetTransformInfo::UnrollingPreferences::Partial, llvm::TargetTransformInfo::UnrollingPreferences::PeelCount, and llvm::TargetTransformInfo::UnrollingPreferences::Runtime.
getUserCost()
int HexagonTTIImpl::getUserCost (const User * U, ArrayRef< const Value * > Operands)
Definition at line 283 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, llvm::TargetTransformInfoImplBase::getDataLayout(), llvm::DataLayout::getTypeSizeInBits(), llvm::TargetTransformInfo::getUserCost(), llvm::Value::hasOneUse(), and llvm::TargetTransformInfo::TCC_Free.
getVectorInstrCost()
unsigned HexagonTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Definition at line 254 of file HexagonTargetTransformInfo.cpp.
References getVectorInstrCost(), llvm::Type::isIntegerTy(), and llvm::Type::isVectorTy().
Referenced by getVectorInstrCost().
hasBranchDivergence()
bool llvm::HexagonTTIImpl::hasBranchDivergence () inline
Definition at line 91 of file HexagonTargetTransformInfo.h.
prefersVectorizedAddressing()
bool llvm::HexagonTTIImpl::prefersVectorizedAddressing () inline
Definition at line 97 of file HexagonTargetTransformInfo.h.
shouldBuildLookupTables()
bool HexagonTTIImpl::shouldBuildLookupTables () const
Definition at line 309 of file HexagonTargetTransformInfo.cpp.
References EmitLookupTables.
shouldFavorPostInc()
bool HexagonTTIImpl::shouldFavorPostInc () const
Bias LSR towards creating post-increment opportunities.
Definition at line 88 of file HexagonTargetTransformInfo.cpp.
shouldMaximizeVectorBandwidth()
bool llvm::HexagonTTIImpl::shouldMaximizeVectorBandwidth (bool OptSize) const inline
Definition at line 85 of file HexagonTargetTransformInfo.h.
supportsEfficientVectorElementLoadStore()
bool llvm::HexagonTTIImpl::supportsEfficientVectorElementLoadStore () inline
Definition at line 88 of file HexagonTargetTransformInfo.h.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonTargetTransformInfo.h
lib/Target/Hexagon/HexagonTargetTransformInfo.cpp