LLVM: llvm::InterleavedAccessInfo Class Reference
llvm::InterleavedAccessInfo Class Reference
Drive the analysis of interleaved memory accesses in the loop.
#include "llvm/Analysis/VectorUtils.h"
Public Member Functions
InterleavedAccessInfo (PredicatedScalarEvolution &PSE, Loop *L, DominatorTree *DT, LoopInfo *LI, const LoopAccessInfo *LAI)
~InterleavedAccessInfo ()
void analyzeInterleaving (bool EnableMaskedInterleavedGroup)
Analyze the interleaved accesses and collect them in interleave groups.
void reset ()
Invalidate groups, e.g., in case all blocks in loop will be predicated contrary to original assumption.
bool isInterleaved (Instruction *Instr) const
Check if Instr belongs to any interleave group.
InterleaveGroup< Instruction > * getInterleaveGroup (const Instruction *Instr) const
Get the interleave group that Instr belongs to.
iterator_range< SmallPtrSetIterator< llvm::InterleaveGroup< Instruction > * > > getInterleaveGroups ()
bool requiresScalarEpilogue () const
Returns true if an interleaved group that may access memory out-of-bounds requires a scalar epilogue iteration for correctness.
void invalidateGroupsRequiringScalarEpilogue ()
Invalidate groups that require a scalar epilogue (due to gaps).
Detailed Description
Drive the analysis of interleaved memory accesses in the loop.
Use this class to analyze interleaved accesses only when we can vectorize a loop. Otherwise it's meaningless to do analysis as the vectorization on interleaved accesses is unsafe.
The analysis collects interleave groups and records the relationships between the member and the group in a map.
Definition at line 417 of file VectorUtils.h.
Constructor & Destructor Documentation
InterleavedAccessInfo()
llvm::InterleavedAccessInfo::InterleavedAccessInfo (PredicatedScalarEvolution & PSE, Loop * L, DominatorTree * DT, LoopInfo * LI, const LoopAccessInfo * LAI) inline
Definition at line 419 of file VectorUtils.h.
~InterleavedAccessInfo()
llvm::InterleavedAccessInfo::~InterleavedAccessInfo () inline
Definition at line 424 of file VectorUtils.h.
References reset().
Member Function Documentation
analyzeInterleaving()
void InterleavedAccessInfo::analyzeInterleaving (bool EnableMaskedInterleavedGroup)
Analyze the interleaved accesses and collect them in interleave groups.
Substitute symbolic strides using Strides. Consider also predicated loads/stores in the analysis if EnableMaskedInterleavedGroup is true.
Definition at line 881 of file VectorUtils.cpp.
References llvm::dbgs(), llvm::SCEVConstant::getAPInt(), llvm::InterleaveGroup< InstTy >::getIndex(), getInterleaveGroup(), llvm::getLoadStoreAddressSpace(), llvm::getLoadStorePointerOperand(), llvm::ScalarEvolution::getMinusSCEV(), llvm::Instruction::getParent(), llvm::getPtrStride(), llvm::PredicatedScalarEvolution::getSE(), llvm::LoopAccessInfo::getSymbolicStrides(), llvm::InterleaveGroup< InstTy >::insertMember(), isInterleaved(), LLVM_DEBUG, llvm::Instruction::mayReadFromMemory(), llvm::Instruction::mayWriteToMemory(), and llvm::InterleaveGroup< InstTy >::setInsertPos().
Referenced by llvm::LoopVectorizePass::processLoop().
getInterleaveGroup()
InterleaveGroup< Instruction > * llvm::InterleavedAccessInfo::getInterleaveGroup (const Instruction * Instr) const inline
Get the interleave group that Instr belongs to.
Returns
nullptr if doesn't have such group.
Definition at line 457 of file VectorUtils.h.
Referenced by analyzeInterleaving(), and llvm::LoopVectorizationCostModel::getInterleavedAccessGroup().
getInterleaveGroups()
iterator_range< SmallPtrSetIterator< llvm::InterleaveGroup< Instruction > * > > llvm::InterleavedAccessInfo::getInterleaveGroups () inline
Definition at line 464 of file VectorUtils.h.
invalidateGroupsRequiringScalarEpilogue()
void InterleavedAccessInfo::invalidateGroupsRequiringScalarEpilogue ()
Invalidate groups that require a scalar epilogue (due to gaps).
This can happen when optimizing for size forbids a scalar epilogue, and the gap cannot be filtered by masking the load/store.
Definition at line 1117 of file VectorUtils.cpp.
References llvm::dbgs(), I, LLVM_DEBUG, llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), and requiresScalarEpilogue().
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF().
isInterleaved()
bool llvm::InterleavedAccessInfo::isInterleaved (Instruction * Instr) const inline
Check if Instr belongs to any interleave group.
Definition at line 449 of file VectorUtils.h.
Referenced by analyzeInterleaving(), and llvm::LoopVectorizationCostModel::isAccessInterleaved().
requiresScalarEpilogue()
bool llvm::InterleavedAccessInfo::requiresScalarEpilogue () const inline
Returns true if an interleaved group that may access memory out-of-bounds requires a scalar epilogue iteration for correctness.
Definition at line 470 of file VectorUtils.h.
Referenced by invalidateGroupsRequiringScalarEpilogue(), and llvm::LoopVectorizationCostModel::requiresScalarEpilogue().
reset()
void llvm::InterleavedAccessInfo::reset () inline
Invalidate groups, e.g., in case all blocks in loop will be predicated contrary to original assumption.
Although we currently prevent group formation for predicated accesses, we may be able to relax this limitation in the future once we handle more complicated blocks.
Definition at line 436 of file VectorUtils.h.
References I.
Referenced by llvm::LoopVectorizationPlanner::plan(), and ~InterleavedAccessInfo().
The documentation for this class was generated from the following files:
include/llvm/Analysis/VectorUtils.h
lib/Analysis/VectorUtils.cpp