LLVM: llvm::LLParser Class Reference
llvm::LLParser Class Reference
#include "AsmParser/LLParser.h"
Public Types
typedef LLLexer::LocTy LocTy
Public Member Functions
LLParser (StringRef F, SourceMgr &SM, SMDiagnostic &Err, Module *M, ModuleSummaryIndex *Index, LLVMContext &Context, SlotMapping *Slots=nullptr, bool UpgradeDebugInfo=true, StringRef DataLayoutString="")
bool Run ()
Run: module ::= toplevelentity*.
bool parseStandaloneConstantValue (Constant *&C, const SlotMapping *Slots)
bool parseTypeAtBeginning (Type *&Ty, unsigned &Read, const SlotMapping *Slots)
LLVMContext & getContext ()
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDUnsignedField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, LineField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, ColumnField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfTagField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfMacinfoTypeField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfVirtualityField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfLangField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfCCField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, EmissionKindField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, NameTableKindField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DwarfAttEncodingField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DIFlagField &Result)
DIFlagField ::= uint32 ::= DIFlagVector ::= DIFlagVector '|' DIFlagFwdDecl '|' uint32 '|' DIFlagPublic.
template<>
bool ParseMDField (LocTy Loc, StringRef Name, DISPFlagField &Result)
DISPFlagField ::= uint32 ::= DISPFlagVector ::= DISPFlagVector '|' DISPFlag* '|' uint32.
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDSignedField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDBoolField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDSignedOrMDField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDSignedOrUnsignedField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDStringField &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, MDFieldList &Result)
template<>
bool ParseMDField (LocTy Loc, StringRef Name, ChecksumKindField &Result)
Detailed Description
Definition at line 87 of file LLParser.h.
Member Typedef Documentation
LocTy
typedef LLLexer::LocTy llvm::LLParser::LocTy
Definition at line 89 of file LLParser.h.
Constructor & Destructor Documentation
LLParser()
llvm::LLParser::LLParser (StringRef F, SourceMgr & SM, SMDiagnostic & Err, Module * M, ModuleSummaryIndex * Index, LLVMContext & Context, SlotMapping * Slots = nullptr, bool UpgradeDebugInfo = true, StringRef DataLayoutString = "") inline
Definition at line 169 of file LLParser.h.
References llvm::UpgradeDebugInfo().
Member Function Documentation
getContext()
LLVMContext & llvm::LLParser::getContext () inline
Definition at line 186 of file LLParser.h.
ParseMDField() [1/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, ChecksumKindField & Result)
Definition at line 4298 of file LLParser.cpp.
References llvm::lltok::ChecksumKind, llvm::DIFile::getChecksumKind(), llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [2/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, ColumnField & Result)
Definition at line 3942 of file LLParser.cpp.
ParseMDField() [3/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DIFlagField & Result)
DIFlagField ::= uint32 ::= DIFlagVector ::= DIFlagVector '|' DIFlagFwdDecl '|' uint32 '|' DIFlagPublic.
Definition at line 4100 of file LLParser.cpp.
References llvm::lltok::APSInt, llvm::lltok::bar, llvm::lltok::DIFlag, llvm::LLLexer::getAPSIntVal(), llvm::DINode::getFlag(), llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [4/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DISPFlagField & Result)
DISPFlagField ::= uint32 ::= DISPFlagVector ::= DISPFlagVector '|' DISPFlag* '|' uint32.
Definition at line 4140 of file LLParser.cpp.
References llvm::lltok::APSInt, llvm::lltok::bar, llvm::lltok::DISPFlag, llvm::LLLexer::getAPSIntVal(), llvm::DISubprogram::getFlag(), llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [5/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfAttEncodingField & Result)
Definition at line 4077 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfAttEncoding, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [6/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfCCField & Result)
Definition at line 4022 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfCC, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [7/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfLangField & Result)
Definition at line 4004 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfLang, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [8/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfMacinfoTypeField & Result)
Definition at line 3965 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfMacinfo, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [9/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfTagField & Result)
Definition at line 3947 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfTag, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), llvm::LLLexer::Lex(), and llvm::Tag.
ParseMDField() [10/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, DwarfVirtualityField & Result)
Definition at line 3985 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfVirtuality, llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [11/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, EmissionKindField & Result)
Definition at line 4040 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::EmissionKind, llvm::DICompileUnit::getEmissionKind(), llvm::LLLexer::getKind(), llvm::LLLexer::getStrVal(), and llvm::LLLexer::Lex().
ParseMDField() [12/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, LineField & Result)
Definition at line 3938 of file LLParser.cpp.
ParseMDField() [13/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDBoolField & Result)
Definition at line 4196 of file LLParser.cpp.
References llvm::LLLexer::getKind(), llvm::lltok::kw_false, llvm::lltok::kw_true, and llvm::LLLexer::Lex().
ParseMDField() [14/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDField & Result)
Definition at line 4212 of file LLParser.cpp.
References llvm::LLLexer::getKind(), llvm::lltok::kw_null, and llvm::LLLexer::Lex().
ParseMDField() [15/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDFieldList & Result)
Definition at line 4288 of file LLParser.cpp.
ParseMDField() [16/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDSignedField & Result)
Definition at line 4176 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::LLLexer::getAPSIntVal(), llvm::LLLexer::getKind(), and llvm::LLLexer::Lex().
ParseMDField() [17/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDSignedOrMDField & Result)
Definition at line 4230 of file LLParser.cpp.
References llvm::lltok::APSInt, and llvm::LLLexer::getKind().
ParseMDField() [18/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDSignedOrUnsignedField & Result)
Definition at line 4253 of file LLParser.cpp.
References llvm::lltok::APSInt, llvm::LLLexer::getAPSIntVal(), and llvm::LLLexer::getKind().
ParseMDField() [19/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDStringField & Result)
Definition at line 4274 of file LLParser.cpp.
References llvm::DITypeRefArray::get(), and llvm::LLLexer::getLoc().
ParseMDField() [20/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, MDUnsignedField & Result)
Definition at line 3922 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::LLLexer::getAPSIntVal(), llvm::LLLexer::getKind(), and llvm::LLLexer::Lex().
ParseMDField() [21/21]
template<> bool llvm::LLParser::ParseMDField (LocTy Loc, StringRef Name, NameTableKindField & Result)
Definition at line 4058 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::LLLexer::getKind(), llvm::DICompileUnit::getNameTableKind(), llvm::LLLexer::getStrVal(), llvm::LLLexer::Lex(), and llvm::lltok::NameTableKind.
parseStandaloneConstantValue()
bool LLParser::parseStandaloneConstantValue (Constant *& C, const SlotMapping * Slots)
Definition at line 77 of file LLParser.cpp.
References llvm::lltok::Eof, llvm::LLLexer::getKind(), llvm::LLLexer::getLoc(), and llvm::LLLexer::Lex().
Referenced by llvm::parseConstantValue().
parseTypeAtBeginning()
bool LLParser::parseTypeAtBeginning (Type *& Ty, unsigned & Read, const SlotMapping * Slots)
Definition at line 90 of file LLParser.cpp.
References llvm::LLLexer::getLoc(), and llvm::LLLexer::Lex().
Referenced by llvm::parseTypeAtBeginning().
Run()
bool LLParser::Run ()
Run: module ::= toplevelentity*.
Definition at line 64 of file LLParser.cpp.
References llvm::LLLexer::getLoc(), llvm::LLLexer::Lex(), and llvm::LLVMContext::shouldDiscardValueNames().
Referenced by llvm::parseAssemblyInto(), and parseSummaryIndexAssemblyInto().
The documentation for this class was generated from the following files:
lib/AsmParser/LLParser.h
lib/AsmParser/LLParser.cpp