LLVM: NodeOrString Class Reference
NodeOrString Class Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
NodeOrString (StringView Str)
NodeOrString (Node *N)
NodeOrString ()
bool isString () const
bool isNode () const
bool isEmpty () const
StringView asString () const
const Node * asNode () const
Detailed Description
Definition at line 603 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
NodeOrString() [1/3]
NodeOrString::NodeOrString (StringView Str) inline
Definition at line 608 of file ItaniumDemangle.h.
References assert(), StringView::begin(), and StringView::end().
NodeOrString() [2/3]
NodeOrString::NodeOrString (Node * N) inline
Definition at line 619 of file ItaniumDemangle.h.
NodeOrString() [3/3]
NodeOrString::NodeOrString () inline
Definition at line 621 of file ItaniumDemangle.h.
Member Function Documentation
asNode()
const Node * NodeOrString::asNode () const inline
Definition at line 633 of file ItaniumDemangle.h.
References assert(), and isNode().
asString()
StringView NodeOrString::asString () const inline
Definition at line 627 of file ItaniumDemangle.h.
References assert(), and isString().
isEmpty()
bool NodeOrString::isEmpty () const inline
Definition at line 625 of file ItaniumDemangle.h.
isNode()
bool NodeOrString::isNode () const inline
Definition at line 624 of file ItaniumDemangle.h.
Referenced by asNode().
isString()
bool NodeOrString::isString () const inline
Definition at line 623 of file ItaniumDemangle.h.
Referenced by asString().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h