LLVM: llvm::orc::ThreadSafeModule Class Reference
llvm::orc::ThreadSafeModule Class Reference
An LLVM Module together with a shared ThreadSafeContext.
#include "llvm/ExecutionEngine/Orc/ThreadSafeModule.h"
Public Member Functions
ThreadSafeModule ()=default
Default construct a ThreadSafeModule.
ThreadSafeModule (ThreadSafeModule &&Other)=default
ThreadSafeModule & operator= (ThreadSafeModule &&Other)
ThreadSafeModule (std::unique_ptr< Module > M, std::unique_ptr< LLVMContext > Ctx)
Construct a ThreadSafeModule from a unique_ptr<Module> and a unique_ptr<LLVMContext>.
ThreadSafeModule (std::unique_ptr< Module > M, ThreadSafeContext TSCtx)
Construct a ThreadSafeModule from a unique_ptr<Module> and an existing ThreadSafeContext.
~ThreadSafeModule ()
Module * getModule ()
Get the module wrapped by this ThreadSafeModule.
const Module * getModule () const
Get the module wrapped by this ThreadSafeModule.
ThreadSafeContext::Lock getContextLock ()
Take out a lock on the ThreadSafeContext for this module.
operator bool ()
Boolean conversion: This ThreadSafeModule will evaluate to true if it wraps a non-null module.
Detailed Description
An LLVM Module together with a shared ThreadSafeContext.
Definition at line 82 of file ThreadSafeModule.h.
Constructor & Destructor Documentation
ThreadSafeModule() [1/4]
llvm::orc::ThreadSafeModule::ThreadSafeModule () default
Default construct a ThreadSafeModule.
This results in a null module and null context.
ThreadSafeModule() [2/4]
llvm::orc::ThreadSafeModule::ThreadSafeModule (ThreadSafeModule && Other) default
ThreadSafeModule() [3/4]
llvm::orc::ThreadSafeModule::ThreadSafeModule (std::unique_ptr< Module > M, std::unique_ptr< LLVMContext > Ctx) inline
Construct a ThreadSafeModule from a unique_ptr<Module> and a unique_ptr<LLVMContext>.
This creates a new ThreadSafeContext from the given context.
Definition at line 109 of file ThreadSafeModule.h.
ThreadSafeModule() [4/4]
llvm::orc::ThreadSafeModule::ThreadSafeModule (std::unique_ptr< Module > M, ThreadSafeContext TSCtx) inline
Construct a ThreadSafeModule from a unique_ptr<Module> and an existing ThreadSafeContext.
Definition at line 114 of file ThreadSafeModule.h.
~ThreadSafeModule()
llvm::orc::ThreadSafeModule::~ThreadSafeModule () inline
Definition at line 117 of file ThreadSafeModule.h.
References getContextLock().
Member Function Documentation
getContextLock()
ThreadSafeContext::Lock llvm::orc::ThreadSafeModule::getContextLock () inline
Take out a lock on the ThreadSafeContext for this module.
Definition at line 132 of file ThreadSafeModule.h.
References llvm::orc::ThreadSafeContext::getLock().
Referenced by llvm::orc::cloneToNewContext(), operator=(), and ~ThreadSafeModule().
getModule() [1/2]
Module * llvm::orc::ThreadSafeModule::getModule () inline
Get the module wrapped by this ThreadSafeModule.
Definition at line 126 of file ThreadSafeModule.h.
Referenced by llvm::orc::LLJIT::addIRModule(), llvm::orc::LLLazyJIT::addLazyIRModule(), llvm::orc::cloneToNewContext(), llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::IRTransformLayer::emit(), llvm::orc::IRMaterializationUnit::getName(), and llvm::orc::IRMaterializationUnit::IRMaterializationUnit().
getModule() [2/2]
const Module * llvm::orc::ThreadSafeModule::getModule () const inline
Get the module wrapped by this ThreadSafeModule.
Definition at line 129 of file ThreadSafeModule.h.
operator bool()
llvm::orc::ThreadSafeModule::operator bool () inline explicit
Boolean conversion: This ThreadSafeModule will evaluate to true if it wraps a non-null module.
Definition at line 136 of file ThreadSafeModule.h.
References assert(), and llvm::orc::ThreadSafeContext::getContext().
operator=()
ThreadSafeModule & llvm::orc::ThreadSafeModule::operator= (ThreadSafeModule && Other) inline
Definition at line 90 of file ThreadSafeModule.h.
References getContextLock(), and Other.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h