LLVM: llvm::DWARFDebugLoclists Class Reference
llvm::DWARFDebugLoclists Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
Classes
struct Entry
struct LocationList
Public Member Functions
void parse (DataExtractor data, unsigned Version)
void dump (raw_ostream &OS, uint64_t BaseAddr, const MCRegisterInfo *RegInfo, Optional< uint64_t > Offset) const
LocationList const * getLocationListAtOffset (uint64_t Offset) const
Return the location list at the given offset or nullptr.
Static Public Member Functions
static Optional< LocationList > parseOneLocationList (DataExtractor Data, unsigned *Offset, unsigned Version)
Detailed Description
Definition at line 75 of file DWARFDebugLoc.h.
Member Function Documentation
dump()
void DWARFDebugLoclists::dump (raw_ostream & OS, uint64_t BaseAddr, const MCRegisterInfo * RegInfo, Optional< uint64_t > Offset) const
Definition at line 260 of file DWARFDebugLoc.cpp.
References llvm::format(), getLocationListAtOffset(), and MRI.
Referenced by llvm::DWARFContext::dump(), and dumpLoclistsSection().
getLocationListAtOffset()
DWARFDebugLoclists::LocationList const * DWARFDebugLoclists::getLocationListAtOffset (uint64_t Offset) const
Return the location list at the given offset or nullptr.
Definition at line 214 of file DWARFDebugLoc.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DWARFDebugLoclists::LocationList::Offset, and llvm::partition_point().
Referenced by dump().
parse()
void DWARFDebugLoclists::parse (DataExtractor data, unsigned Version)
Definition at line 200 of file DWARFDebugLoc.cpp.
References llvm::DataExtractor::getAddressSize(), llvm::DataExtractor::isLittleEndian(), llvm::DataExtractor::isValidOffset(), parseOneLocationList(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by dumpLoclistsSection().
parseOneLocationList()
Optional< DWARFDebugLoclists::LocationList > DWARFDebugLoclists::parseOneLocationList (DataExtractor Data, unsigned * Offset, unsigned Version) static
Definition at line 147 of file DWARFDebugLoc.cpp.
References llvm::copy(), llvm::Data, llvm::dwarf::DW_LLE_base_address, llvm::dwarf::DW_LLE_offset_pair, llvm::dwarf::DW_LLE_start_length, llvm::dwarf::DW_LLE_startx_length, E, llvm::DWARFDebugLoclists::LocationList::Entries, llvm::WithColor::error(), llvm::None, llvm::DWARFDebugLoclists::LocationList::Offset, and llvm::StringRef::size().
Referenced by dumpLocation(), and parse().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
lib/DebugInfo/DWARF/DWARFDebugLoc.cpp