LLVM: llvm::iplist_impl< IntrusiveListT, TraitsT > Class Template Reference
llvm::iplist_impl< IntrusiveListT, TraitsT > Class Template Reference
A wrapper around an intrusive list with callbacks and non-intrusive ownership.
#include "llvm/ADT/ilist.h"
Public Types
typedef base_list_type::pointer pointer
typedef base_list_type::const_pointer const_pointer
typedef base_list_type::reference reference
typedef base_list_type::const_reference const_reference
typedef base_list_type::value_type value_type
typedef base_list_type::size_type size_type
typedef base_list_type::difference_type difference_type
typedef base_list_type::iterator iterator
typedef base_list_type::const_iterator const_iterator
typedef base_list_type::reverse_iterator reverse_iterator
typedef base_list_type::const_reverse_iterator const_reverse_iterator
Public Member Functions
iplist_impl ()=default
iplist_impl (const iplist_impl &)=delete
iplist_impl & operator= (const iplist_impl &)=delete
iplist_impl (iplist_impl &&X)
iplist_impl & operator= (iplist_impl &&X)
~iplist_impl ()
size_type max_size () const
void swap (iplist_impl &RHS)
iterator insert (iterator where, pointer New)
iterator insert (iterator where, const_reference New)
iterator insertAfter (iterator where, pointer New)
template<class Cloner >
void cloneFrom (const iplist_impl &L2, Cloner clone)
Clone another list.
pointer remove (iterator &IT)
pointer remove (const iterator &IT)
pointer remove (pointer IT)
pointer remove (reference IT)
iterator erase (iterator where)
iterator erase (pointer IT)
iterator erase (reference IT)
void clearAndLeakNodesUnsafely ()
Remove all nodes from the list like clear(), but do not call removeNodeFromList() or deleteNode().
iterator erase (iterator first, iterator last)
void clear ()
void push_front (pointer val)
void push_back (pointer val)
void pop_front ()
void pop_back ()
template<class InIt >
void insert (iterator where, InIt first, InIt last)
void splice (iterator where, iplist_impl &L2)
void splice (iterator where, iplist_impl &L2, iterator first)
void splice (iterator where, iplist_impl &L2, iterator first, iterator last)
void splice (iterator where, iplist_impl &L2, reference N)
void splice (iterator where, iplist_impl &L2, pointer N)
template<class Compare >
void merge (iplist_impl &Right, Compare comp)
void merge (iplist_impl &Right)
pointer getPrevNode (reference N) const
Get the previous node, or nullptr for the list head.
const_pointer getPrevNode (const_reference N) const
Get the previous node, or nullptr for the list head.
pointer getNextNode (reference N) const
Get the next node, or nullptr for the list tail.
const_pointer getNextNode (const_reference N) const
Get the next node, or nullptr for the list tail.
Detailed Description
template<class IntrusiveListT, class TraitsT>
class llvm::iplist_impl< IntrusiveListT, TraitsT >
A wrapper around an intrusive list with callbacks and non-intrusive ownership.
This wraps a purely intrusive list (like simple_ilist) with a configurable traits class. The traits can implement callbacks and customize the ownership semantics.
This is a subset of ilist functionality that can safely be used on nodes of polymorphic types, i.e. a heterogeneous list with a common base class that holds the next/prev pointers. The only state of the list itself is an ilist_sentinel, which holds pointers to the first and last nodes in the list.
Definition at line 166 of file ilist.h.
Member Typedef Documentation
const_iterator
template<class IntrusiveListT , class TraitsT > typedef base_list_type::const_iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::const_iterator
Definition at line 178 of file ilist.h.
const_pointer
template<class IntrusiveListT , class TraitsT > typedef base_list_type::const_pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::const_pointer
Definition at line 171 of file ilist.h.
const_reference
template<class IntrusiveListT , class TraitsT > typedef base_list_type::const_reference llvm::iplist_impl< IntrusiveListT, TraitsT >::const_reference
Definition at line 173 of file ilist.h.
const_reverse_iterator
template<class IntrusiveListT , class TraitsT > typedef base_list_type::const_reverse_iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::const_reverse_iterator
Definition at line 181 of file ilist.h.
difference_type
template<class IntrusiveListT , class TraitsT > typedef base_list_type::difference_type llvm::iplist_impl< IntrusiveListT, TraitsT >::difference_type
Definition at line 176 of file ilist.h.
iterator
template<class IntrusiveListT , class TraitsT > typedef base_list_type::iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::iterator
Definition at line 177 of file ilist.h.
pointer
template<class IntrusiveListT , class TraitsT > typedef base_list_type::pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::pointer
Definition at line 170 of file ilist.h.
reference
template<class IntrusiveListT , class TraitsT > typedef base_list_type::reference llvm::iplist_impl< IntrusiveListT, TraitsT >::reference
Definition at line 172 of file ilist.h.
reverse_iterator
template<class IntrusiveListT , class TraitsT > typedef base_list_type::reverse_iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::reverse_iterator
Definition at line 179 of file ilist.h.
size_type
template<class IntrusiveListT , class TraitsT > typedef base_list_type::size_type llvm::iplist_impl< IntrusiveListT, TraitsT >::size_type
Definition at line 175 of file ilist.h.
value_type
template<class IntrusiveListT , class TraitsT > typedef base_list_type::value_type llvm::iplist_impl< IntrusiveListT, TraitsT >::value_type
Definition at line 174 of file ilist.h.
Constructor & Destructor Documentation
iplist_impl() [1/3]
template<class IntrusiveListT , class TraitsT > llvm::iplist_impl< IntrusiveListT, TraitsT >::iplist_impl () default
iplist_impl() [2/3]
template<class IntrusiveListT , class TraitsT > llvm::iplist_impl< IntrusiveListT, TraitsT >::iplist_impl (const iplist_impl< IntrusiveListT, TraitsT > &) delete
iplist_impl() [3/3]
template<class IntrusiveListT , class TraitsT > llvm::iplist_impl< IntrusiveListT, TraitsT >::iplist_impl (iplist_impl< IntrusiveListT, TraitsT > && X) inline
Definition at line 200 of file ilist.h.
~iplist_impl()
template<class IntrusiveListT , class TraitsT > llvm::iplist_impl< IntrusiveListT, TraitsT >::~iplist_impl () inline
Definition at line 208 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::clear().
Member Function Documentation
clear()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::clear () inline
Definition at line 307 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase().
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::cloneFrom(), llvm::SlotIndexes::releaseMemory(), llvm::BasicBlock::~BasicBlock(), llvm::iplist_impl< IntrusiveListT, TraitsT >::~iplist_impl(), llvm::Module::~Module(), and llvm::VPBasicBlock::~VPBasicBlock().
clearAndLeakNodesUnsafely()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::clearAndLeakNodesUnsafely () inline
Remove all nodes from the list like clear(), but do not call removeNodeFromList() or deleteNode().
This should only be used immediately before freeing nodes in bulk to avoid traversing the list and bringing all the nodes into cache.
Definition at line 278 of file ilist.h.
References llvm::AllocatorList< T, AllocatorT >::clear().
Referenced by llvm::SlotIndexes::~SlotIndexes().
cloneFrom()
template<class IntrusiveListT , class TraitsT > template<class Cloner > void llvm::iplist_impl< IntrusiveListT, TraitsT >::cloneFrom (const iplist_impl< IntrusiveListT, TraitsT > & L2, Cloner clone) inline
Clone another list.
Definition at line 243 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
erase() [1/4]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::erase (iterator first, iterator last) inline
Definition at line 301 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), and first.
erase() [2/4]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::erase (iterator where) inline
Definition at line 265 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::changeToUnreachable(), llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), eliminateRecursiveTailCall(), llvm::MachineBasicBlock::erase(), llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::MachineFunction::erase(), llvm::Instruction::eraseFromParent(), llvm::VPRecipeBase::eraseFromParent(), llvm::Module::eraseNamedMetadata(), llvm::InlineFunction(), insertUniqueBackedgeBlock(), llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_front(), llvm::ReplaceInstWithValue(), SRAGlobal(), and llvm::UnrollLoop().
erase() [3/4]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::erase (pointer IT) inline
Definition at line 270 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), and IT.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::erase().
erase() [4/4]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::erase (reference IT) inline
Definition at line 271 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), and IT.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::erase().
getNextNode() [1/2]
template<class IntrusiveListT , class TraitsT > const_pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::getNextNode (const_reference N) const inline
Get the next node, or nullptr for the list tail.
Definition at line 377 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::getNextNode(), and N.
getNextNode() [2/2]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::getNextNode (reference N) const inline
Get the next node, or nullptr for the list tail.
Definition at line 370 of file ilist.h.
References N.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::getNextNode().
getPrevNode() [1/2]
template<class IntrusiveListT , class TraitsT > const_pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::getPrevNode (const_reference N) const inline
Get the previous node, or nullptr for the list head.
Definition at line 365 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::getPrevNode(), and N.
getPrevNode() [2/2]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::getPrevNode (reference N) const inline
Get the previous node, or nullptr for the list head.
Definition at line 358 of file ilist.h.
References I, and N.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::getPrevNode().
insert() [1/3]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::insert (iterator where, const_reference New) inline
Definition at line 231 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
insert() [2/3]
template<class IntrusiveListT , class TraitsT > template<class InIt > void llvm::iplist_impl< IntrusiveListT, TraitsT >::insert (iterator where, InIt first, InIt last) inline
Definition at line 322 of file ilist.h.
References first, and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
insert() [3/3]
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::insert (iterator where, pointer New) inline
Definition at line 226 of file ilist.h.
References llvm::AllocatorList< T, AllocatorT >::insert().
Referenced by CloneInstructionInExitBlock(), createCallHelper(), createInvokeHelper(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::MCObjectStreamer::flushPendingLabels(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::MCSection::getSubsectionInsertionPoint(), HoistThenElseCodeToIf(), llvm::MachineBasicBlock::insert(), llvm::MachineFunction::insert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::MCObjectStreamer::insert(), llvm::VPBasicBlock::insert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insertAfter(), llvm::Instruction::insertBefore(), llvm::VPRecipeBase::insertBefore(), llvm::IRBuilderDefaultInserter::InsertHelper(), llvm::BasicBlock::insertInto(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::InstCombiner::InsertNewInstBefore(), llvm::Instruction::Instruction(), OptimizeGlobalAddressOfMalloc(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::push_front(), removeGlobalCtors(), llvm::ReplaceInstWithInst(), llvm::SelectionDAG::RepositionNode(), llvm::InstCombiner::run(), llvm::SplitLandingPadPredecessors(), TryToShrinkGlobalToBoolean(), and llvm::JumpThreadingPass::UnfoldSelectInstr().
insertAfter()
template<class IntrusiveListT , class TraitsT > iterator llvm::iplist_impl< IntrusiveListT, TraitsT >::insertAfter (iterator where, pointer New) inline
Definition at line 235 of file ilist.h.
References llvm::empty(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by llvm::Instruction::insertAfter(), llvm::SlotIndexes::insertMBBInMaps(), and LLVMInsertExistingBasicBlockAfterInsertBlock().
max_size()
template<class IntrusiveListT , class TraitsT > size_type llvm::iplist_impl< IntrusiveListT, TraitsT >::max_size () const inline
Definition at line 211 of file ilist.h.
merge() [1/2]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::merge (iplist_impl< IntrusiveListT, TraitsT > & Right) inline
Definition at line 353 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::merge(), and llvm::Right.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::merge().
merge() [2/2]
template<class IntrusiveListT , class TraitsT > template<class Compare > void llvm::iplist_impl< IntrusiveListT, TraitsT >::merge (iplist_impl< IntrusiveListT, TraitsT > & Right, Compare comp) inline
Definition at line 347 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::merge(), and llvm::Right.
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::merge().
operator=() [1/2]
template<class IntrusiveListT , class TraitsT > iplist_impl & llvm::iplist_impl< IntrusiveListT, TraitsT >::operator= (const iplist_impl< IntrusiveListT, TraitsT > &) delete
operator=() [2/2]
template<class IntrusiveListT , class TraitsT > iplist_impl & llvm::iplist_impl< IntrusiveListT, TraitsT >::operator= (iplist_impl< IntrusiveListT, TraitsT > && X) inline
Definition at line 202 of file ilist.h.
References X.
pop_back()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_back () inline
Definition at line 316 of file ilist.h.
References assert(), llvm::empty(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::erase().
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), llvm::MergeBlockIntoPredecessor(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
pop_front()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_front () inline
Definition at line 312 of file ilist.h.
References assert(), llvm::empty(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::erase().
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), and llvm::BasicBlock::removePredecessor().
push_back()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back (pointer val) inline
Definition at line 311 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by llvm::CloneAndPruneIntoFromInst(), llvm::CloneBasicBlock(), llvm::iplist_impl< IntrusiveListT, TraitsT >::cloneFrom(), llvm::BinaryOperator::Create(), llvm::UnaryOperator::Create(), createMalloc(), createWrapper(), llvm::CodeExtractor::extractCodeRegion(), llvm::FoldReturnIntoUncondBranch(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertNamedMetadata(), llvm::BasicBlock::insertInto(), llvm::Instruction::Instruction(), llvm::MCFragment::MCFragment(), llvm::MachineFunction::push_back(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::SlotIndexes::runOnMachineFunction(), SRAGlobal(), llvm::JumpThreadingPass::ThreadEdge(), unifyReturnBlockSet(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
push_front()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::push_front (pointer val) inline
Definition at line 310 of file ilist.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by llvm::MachineFunction::push_front().
remove() [1/4]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::remove (const iterator & IT) inline
Definition at line 256 of file ilist.h.
References IT, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
remove() [2/4]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::remove (iterator & IT) inline
Definition at line 249 of file ilist.h.
References IT, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::iplist_impl< IntrusiveListT, TraitsT >::remove(), llvm::MachineFunction::remove(), llvm::MachineBasicBlock::remove_instr(), llvm::Instruction::removeFromParent(), and llvm::SelectionDAG::RepositionNode().
remove() [3/4]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::remove (pointer IT) inline
Definition at line 261 of file ilist.h.
References IT, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
remove() [4/4]
template<class IntrusiveListT , class TraitsT > pointer llvm::iplist_impl< IntrusiveListT, TraitsT >::remove (reference IT) inline
Definition at line 262 of file ilist.h.
References IT, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
splice() [1/5]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::splice (iterator where, iplist_impl< IntrusiveListT, TraitsT > & L2) inline
Definition at line 327 of file ilist.h.
Referenced by doPromotion(), llvm::hoistAllInstructionsInto(), HoistThenElseCodeToIf(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), moveBBContents(), llvm::Instruction::moveBefore(), SpeculativelyExecuteBB(), llvm::MachineFunction::splice(), llvm::iplist_impl< IntrusiveListT, TraitsT >::splice(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and unswitchTrivialBranch().
splice() [2/5]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::splice (iterator where, iplist_impl< IntrusiveListT, TraitsT > & L2, iterator first) inline
Definition at line 331 of file ilist.h.
References first.
splice() [3/5]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::splice (iterator where, iplist_impl< IntrusiveListT, TraitsT > & L2, iterator first, iterator last) inline
Definition at line 336 of file ilist.h.
References first.
splice() [4/5]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::splice (iterator where, iplist_impl< IntrusiveListT, TraitsT > & L2, pointer N) inline
Definition at line 342 of file ilist.h.
References N, and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
splice() [5/5]
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::splice (iterator where, iplist_impl< IntrusiveListT, TraitsT > & L2, reference N) inline
Definition at line 339 of file ilist.h.
References N, and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
swap()
template<class IntrusiveListT , class TraitsT > void llvm::iplist_impl< IntrusiveListT, TraitsT >::swap (iplist_impl< IntrusiveListT, TraitsT > & RHS) inline
Definition at line 221 of file ilist.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist.h