LLVM: llvm::sampleprof::SampleProfileWriterCompactBinary Class Reference
llvm::sampleprof::SampleProfileWriterCompactBinary Class Reference
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
virtual std::error_code write (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
virtual std::error_code write (const StringMap< FunctionSamples > &ProfileMap) override
Write all the sample profiles in the given map of samples.
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code write (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
virtual std::error_code write (const FunctionSamples &S)=0
Write sample profiles in S.
virtual std::error_code write (const StringMap< FunctionSamples > &ProfileMap)
Write all the sample profiles in the given map of samples.
raw_ostream & getOutputStream ()
Protected Member Functions
virtual std::error_code writeNameTable () override
virtual std::error_code writeMagicIdent () override
virtual std::error_code writeHeader (const StringMap< FunctionSamples > &ProfileMap) override
Write a file header for the profile file.
std::error_code writeFuncOffsetTable ()
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code writeNameTable ()=0
virtual std::error_code writeMagicIdent ()=0
virtual std::error_code writeHeader (const StringMap< FunctionSamples > &ProfileMap) override
Write a file header for the profile file.
std::error_code writeSummary ()
std::error_code writeNameIdx (StringRef FName)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (std::set< StringRef > &V)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeHeader (const StringMap< FunctionSamples > &ProfileMap)=0
Write a file header for the profile file.
void computeSummary (const StringMap< FunctionSamples > &ProfileMap)
Compute summary for this profile.
Protected Attributes
MapVector< StringRef, uint64_t > FuncOffsetTable
The table mapping from function name to the offset of its FunctionSample towards profile start.
uint64_t TableOffset
The offset of the slot to be filled with the offset of FuncOffsetTable towards profile start.
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterBinary
MapVector< StringRef, uint32_t > NameTable
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Detailed Description
Definition at line 168 of file SampleProfWriter.h.
Member Function Documentation
write() [1/2]
std::error_code SampleProfileWriterCompactBinary::write (const FunctionSamples & S) override virtual
Write samples of a top-level function to a binary file.
Returns
true if the samples were written successfully, false otherwise.
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 333 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), FuncOffsetTable, llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::sampleprof::FunctionSamples::getName(), Name, llvm::sampleprof::SampleProfileWriter::OutputStream, and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
write() [2/2]
std::error_code SampleProfileWriterCompactBinary::write (const StringMap< FunctionSamples > & ProfileMap) override virtual
Write all the sample profiles in the given map of samples.
Returns
status code of the file update operation.
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 67 of file SampleProfWriter.cpp.
References llvm::success, llvm::sampleprof::SampleProfileWriter::write(), and writeFuncOffsetTable().
writeFuncOffsetTable()
std::error_code SampleProfileWriterCompactBinary::writeFuncOffsetTable () protected
Definition at line 180 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), entry, FuncOffsetTable, llvm::support::little, llvm::ostream_seek_unsupported, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::success, TableOffset, llvm::raw_ostream::tell(), llvm::support::endian::Writer::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeNameIdx().
Referenced by write().
writeHeader()
std::error_code SampleProfileWriterCompactBinary::writeHeader (const StringMap< FunctionSamples > & ProfileMap) override protected virtual
Write a file header for the profile file.
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 251 of file SampleProfWriter.cpp.
References llvm::support::little, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::success, TableOffset, llvm::support::endian::Writer::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeHeader().
writeMagicIdent()
std::error_code SampleProfileWriterCompactBinary::writeMagicIdent () override protected virtual
Implements llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 225 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SPF_Compact_Binary, llvm::sampleprof::SPMagic(), llvm::sampleprof::SPVersion(), and llvm::success.
writeNameTable()
std::error_code SampleProfileWriterCompactBinary::writeNameTable () override protected virtual
Implements llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 204 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::MD5Hash(), N, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SampleProfileWriterBinary::stablizeNameTable(), and llvm::success.
Member Data Documentation
FuncOffsetTable
MapVector<StringRef, uint64_t> llvm::sampleprof::SampleProfileWriterCompactBinary::FuncOffsetTable protected
The table mapping from function name to the offset of its FunctionSample towards profile start.
Definition at line 179 of file SampleProfWriter.h.
Referenced by write(), and writeFuncOffsetTable().
TableOffset
uint64_t llvm::sampleprof::SampleProfileWriterCompactBinary::TableOffset protected
The offset of the slot to be filled with the offset of FuncOffsetTable towards profile start.
Definition at line 182 of file SampleProfWriter.h.
Referenced by writeFuncOffsetTable(), and writeHeader().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp