LLVM: llvm::ImmutableListFactory< T > Class Template Reference
llvm::ImmutableListFactory< T > Class Template Reference
#include "llvm/ADT/ImmutableList.h"
Public Member Functions
ImmutableListFactory ()
ImmutableListFactory (BumpPtrAllocator &Alloc)
~ImmutableListFactory ()
template<typename ElemT >
LLVM_NODISCARD ImmutableList< T > concat (ElemT &&Head, ImmutableList< T > Tail)
template<typename ElemT >
LLVM_NODISCARD ImmutableList< T > add (ElemT &&Data, ImmutableList< T > L)
template<typename ... CtorArgs>
LLVM_NODISCARD ImmutableList< T > emplace (ImmutableList< T > Tail, CtorArgs &&...Args)
ImmutableList< T > getEmptyList () const
template<typename ElemT >
ImmutableList< T > create (ElemT &&Data)
Detailed Description
template<typename T>
class llvm::ImmutableListFactory< T >
Definition at line 149 of file ImmutableList.h.
Constructor & Destructor Documentation
ImmutableListFactory() [1/2]
template<typename T > llvm::ImmutableListFactory< T >::ImmutableListFactory () inline
Definition at line 165 of file ImmutableList.h.
References Allocator.
ImmutableListFactory() [2/2]
template<typename T > llvm::ImmutableListFactory< T >::ImmutableListFactory (BumpPtrAllocator & Alloc) inline
Definition at line 168 of file ImmutableList.h.
References Allocator.
~ImmutableListFactory()
template<typename T > llvm::ImmutableListFactory< T >::~ImmutableListFactory () inline
Definition at line 171 of file ImmutableList.h.
Member Function Documentation
add()
template<typename T > template<typename ElemT > LLVM_NODISCARD ImmutableList< T > llvm::ImmutableListFactory< T >::add (ElemT && Data, ImmutableList< T > L) inline
Definition at line 199 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), and llvm::Data.
concat()
template<typename T > template<typename ElemT > LLVM_NODISCARD ImmutableList< T > llvm::ImmutableListFactory< T >::concat (ElemT && Head, ImmutableList< T > Tail) inline
Definition at line 176 of file ImmutableList.h.
References A, llvm::FoldingSetImpl< T >::FindNodeOrInsertPos(), llvm::ImmutableList< T >::getInternalPointer(), and llvm::FoldingSetImpl< T >::InsertNode().
Referenced by llvm::ImmutableListFactory< T >::add(), llvm::ImmutableListFactory< T >::create(), and llvm::ImmutableListFactory< T >::emplace().
create()
template<typename T > template<typename ElemT > ImmutableList< T > llvm::ImmutableListFactory< T >::create (ElemT && Data) inline
Definition at line 214 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), llvm::Data, and llvm::ImmutableListFactory< T >::getEmptyList().
emplace()
template<typename T > template<typename ... CtorArgs> LLVM_NODISCARD ImmutableList< T > llvm::ImmutableListFactory< T >::emplace (ImmutableList< T > Tail, CtorArgs &&... Args) inline
Definition at line 204 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), and T.
getEmptyList()
template<typename T > ImmutableList< T > llvm::ImmutableListFactory< T >::getEmptyList () const inline
Definition at line 209 of file ImmutableList.h.
Referenced by llvm::ImmutableListFactory< T >::create().
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableList.h