LLVM: llvm::DFAPacketizer Class Reference
llvm::DFAPacketizer Class Reference
#include "llvm/CodeGen/DFAPacketizer.h"
Public Member Functions
DFAPacketizer (const InstrItineraryData *I, const DFAStateInput(*SIT)[2], const unsigned *SET)
void clearResources ()
DFAInput getInsnInput (unsigned InsnClass)
bool canReserveResources (const MCInstrDesc *MID)
void reserveResources (const MCInstrDesc *MID)
bool canReserveResources (MachineInstr &MI)
void reserveResources (MachineInstr &MI)
const InstrItineraryData * getInstrItins () const
Static Public Member Functions
static DFAInput getInsnInput (const std::vector< unsigned > &InsnClass)
Detailed Description
Definition at line 77 of file DFAPacketizer.h.
Constructor & Destructor Documentation
DFAPacketizer()
DFAPacketizer::DFAPacketizer (const InstrItineraryData * I, const DFAStateInput(*) SIT[2], const unsigned * SET)
Definition at line 74 of file DFAPacketizer.cpp.
References DFA_MAX_RESOURCES, and DFA_MAX_RESTERMS.
Member Function Documentation
canReserveResources() [1/2]
bool DFAPacketizer::canReserveResources (const MCInstrDesc * MID)
Definition at line 129 of file DFAPacketizer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), getInsnInput(), and llvm::MCInstrDesc::getSchedClass().
Referenced by llvm::HexagonPacketizerList::addToPacket(), llvm::HexagonPacketizerList::canPromoteToDotNew(), canReserveResources(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::HexagonHazardRecognizer::getHazardType(), llvm::VLIWResourceModel::isResourceAvailable(), llvm::VLIWPacketizerList::PacketizeMIs(), and llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt().
canReserveResources() [2/2]
bool DFAPacketizer::canReserveResources (MachineInstr & MI)
Definition at line 150 of file DFAPacketizer.cpp.
References canReserveResources(), and MI.
clearResources()
void llvm::DFAPacketizer::clearResources () inline
Definition at line 97 of file DFAPacketizer.h.
Referenced by llvm::HexagonHazardRecognizer::AdvanceCycle(), llvm::VLIWPacketizerList::endPacket(), llvm::HexagonPacketizerList::endPacket(), llvm::VLIWResourceModel::reserveResources(), llvm::VLIWResourceModel::reset(), llvm::HexagonHazardRecognizer::Reset(), llvm::VLIWResourceModel::resetDFA(), and llvm::VLIWResourceModel::VLIWResourceModel().
getInsnInput() [1/2]
DFAInput DFAPacketizer::getInsnInput (const std::vector< unsigned > & InsnClass) static
Definition at line 123 of file DFAPacketizer.cpp.
References getDFAInsnInput().
getInsnInput() [2/2]
DFAInput DFAPacketizer::getInsnInput (unsigned InsnClass)
Definition at line 109 of file DFAPacketizer.cpp.
References addDFAFuncUnits(), assert(), llvm::InstrItineraryData::beginStage(), DFA_MAX_RESTERMS, and llvm::InstrItineraryData::endStage().
Referenced by canReserveResources(), and reserveResources().
getInstrItins()
const InstrItineraryData * llvm::DFAPacketizer::getInstrItins () const inline
Definition at line 123 of file DFAPacketizer.h.
Referenced by llvm::HexagonPacketizerList::ignorePseudoInstruction().
reserveResources() [1/2]
void DFAPacketizer::reserveResources (const MCInstrDesc * MID)
Definition at line 139 of file DFAPacketizer.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), getInsnInput(), and llvm::MCInstrDesc::getSchedClass().
Referenced by llvm::VLIWPacketizerList::addToPacket(), llvm::HexagonPacketizerList::addToPacket(), llvm::HexagonHazardRecognizer::EmitInstruction(), reserveResources(), llvm::VLIWResourceModel::reserveResources(), and llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt().
reserveResources() [2/2]
void DFAPacketizer::reserveResources (MachineInstr & MI)
Definition at line 157 of file DFAPacketizer.cpp.
References MI, and reserveResources().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DFAPacketizer.h
lib/CodeGen/DFAPacketizer.cpp