LLVM: llvm::object::WindowsResourceParser Class Reference
llvm::object::WindowsResourceParser Class Reference
#include "llvm/Object/WindowsResource.h"
Classes
class TreeNode
Public Member Functions
WindowsResourceParser ()
Error parse (WindowsResource *WR, std::vector< std::string > &Duplicates)
void printTree (raw_ostream &OS) const
const TreeNode & getTree () const
const ArrayRef< std::vector< uint8_t > > getData () const
const ArrayRef< std::vector< UTF16 > > getStringTable () const
Detailed Description
Definition at line 151 of file WindowsResource.h.
Constructor & Destructor Documentation
WindowsResourceParser()
llvm::object::WindowsResourceParser::WindowsResourceParser ()
Definition at line 131 of file WindowsResource.cpp.
Member Function Documentation
getData()
const ArrayRef< std::vector< uint8_t > > llvm::object::WindowsResourceParser::getData () const inline
Definition at line 158 of file WindowsResource.h.
getStringTable()
const ArrayRef< std::vector< UTF16 > > llvm::object::WindowsResourceParser::getStringTable () const inline
Definition at line 159 of file WindowsResource.h.
getTree()
const TreeNode & llvm::object::WindowsResourceParser::getTree () const inline
Definition at line 157 of file WindowsResource.h.
parse()
Error llvm::object::WindowsResourceParser::parse (WindowsResource * WR, std::vector< std::string > & Duplicates)
Definition at line 203 of file WindowsResource.cpp.
References llvm::consumeError(), E, llvm::object::Binary::getFileName(), llvm::object::WindowsResource::getHeadEntry(), llvm::object::makeDuplicateResourceError(), RETURN_IF_ERROR, and llvm::Error::success().
printTree()
void llvm::object::WindowsResourceParser::printTree (raw_ostream & OS) const
Definition at line 250 of file WindowsResource.cpp.
References llvm::object::WindowsResourceParser::TreeNode::print().
The documentation for this class was generated from the following files:
include/llvm/Object/WindowsResource.h
lib/Object/WindowsResource.cpp