LLVM: llvm::GetElementPtrConstantExpr Class Reference
llvm::GetElementPtrConstantExpr Class Reference
GetElementPtrConstantExpr - This class is private to Constants.cpp, and is used behind the scenes to implement getelementpr constant exprs.
#include "IR/ConstantsContext.h"
Public Member Functions
Type * getSourceElementType () const
Type * getResultElementType () const
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Static Public Member Functions
static GetElementPtrConstantExpr * Create (Type *SrcElementTy, Constant *C, ArrayRef< Constant * > IdxList, Type *DestTy, unsigned Flags)
static bool classof (const ConstantExpr *CE)
static bool classof (const Value *V)
Detailed Description
GetElementPtrConstantExpr - This class is private to Constants.cpp, and is used behind the scenes to implement getelementpr constant exprs.
Definition at line 234 of file ConstantsContext.h.
Member Function Documentation
classof() [1/2]
static bool llvm::GetElementPtrConstantExpr::classof (const ConstantExpr * CE) inline static
Definition at line 257 of file ConstantsContext.h.
Referenced by classof().
classof() [2/2]
static bool llvm::GetElementPtrConstantExpr::classof (const Value * V) inline static
Definition at line 260 of file ConstantsContext.h.
References classof().
Create()
static GetElementPtrConstantExpr * llvm::GetElementPtrConstantExpr::Create (Type * SrcElementTy, Constant * C, ArrayRef< Constant * > IdxList, Type * DestTy, unsigned Flags) inline static
Definition at line 242 of file ConstantsContext.h.
Referenced by llvm::ConstantExprKeyType::create().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::GetElementPtrConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
getResultElementType()
Type * GetElementPtrConstantExpr::getResultElementType () const
Definition at line 2404 of file Constants.cpp.
getSourceElementType()
Type * GetElementPtrConstantExpr::getSourceElementType () const
Definition at line 2400 of file Constants.cpp.
The documentation for this class was generated from the following files:
lib/IR/ConstantsContext.h
lib/IR/Constants.cpp