LLVM: llvm::LazyBlockFrequencyInfoPass Class Reference
llvm::LazyBlockFrequencyInfoPass Class Reference
This is an alternative analysis pass to BlockFrequencyInfoWrapperPass.
#include "llvm/Analysis/LazyBlockFrequencyInfo.h"
Public Member Functions
LazyBlockFrequencyInfoPass ()
BlockFrequencyInfo & getBFI ()
Compute and return the block frequencies.
const BlockFrequencyInfo & getBFI () const
Compute and return the block frequencies.
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
void releaseMemory () override
void print (raw_ostream &OS, const Module *M) const override
Static Public Member Functions
static void getLazyBFIAnalysisUsage (AnalysisUsage &AU)
Helper for client passes to set up the analysis usage on behalf of this pass.
Static Public Attributes
static char ID = 0
Detailed Description
This is an alternative analysis pass to BlockFrequencyInfoWrapperPass.
The difference is that with this pass the block frequencies are not computed when the analysis pass is executed but rather when the BFI result is explicitly requested by the analysis client.
There are some additional requirements for any client pass that wants to use the analysis:
The pass needs to initialize dependent passes with:
INITIALIZE_PASS_DEPENDENCY(LazyBFIPass)
Similarly, getAnalysisUsage should call:
LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage(AU)
The computed BFI should be requested with getAnalysis<LazyBlockFrequencyInfoPass>().getBFI() before either LoopInfo or BPI could be invalidated for example by changing the CFG.
Note that it is expected that we wouldn't need this functionality for the new PM since with the new PM, analyses are executed on demand.
Definition at line 100 of file LazyBlockFrequencyInfo.h.
Constructor & Destructor Documentation
LazyBlockFrequencyInfoPass()
LazyBlockFrequencyInfoPass::LazyBlockFrequencyInfoPass ()
Definition at line 34 of file LazyBlockFrequencyInfo.cpp.
Member Function Documentation
getAnalysisUsage()
void LazyBlockFrequencyInfoPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 42 of file LazyBlockFrequencyInfo.cpp.
References llvm::LazyBranchProbabilityInfoPass::getLazyBPIAnalysisUsage().
getBFI() [1/2]
BlockFrequencyInfo & llvm::LazyBlockFrequencyInfoPass::getBFI () inline
Compute and return the block frequencies.
Definition at line 112 of file LazyBlockFrequencyInfo.h.
getBFI() [2/2]
const BlockFrequencyInfo & llvm::LazyBlockFrequencyInfoPass::getBFI () const inline
Compute and return the block frequencies.
Definition at line 115 of file LazyBlockFrequencyInfo.h.
getLazyBFIAnalysisUsage()
void LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage (AnalysisUsage & AU) static
Helper for client passes to set up the analysis usage on behalf of this pass.
Definition at line 61 of file LazyBlockFrequencyInfo.cpp.
References llvm::LazyBranchProbabilityInfoPass::getLazyBPIAnalysisUsage().
Referenced by llvm::OptimizationRemarkEmitterWrapperPass::getAnalysisUsage(), and llvm::InstructionCombiningPass::getAnalysisUsage().
print()
void LazyBlockFrequencyInfoPass::print (raw_ostream & OS, const Module * M) const override
Definition at line 38 of file LazyBlockFrequencyInfo.cpp.
releaseMemory()
void LazyBlockFrequencyInfoPass::releaseMemory () override
Definition at line 52 of file LazyBlockFrequencyInfo.cpp.
runOnFunction()
bool LazyBlockFrequencyInfoPass::runOnFunction (Function & F) override
Definition at line 54 of file LazyBlockFrequencyInfo.cpp.
References F.
Member Data Documentation
ID
Lazy Block Frequency true char LazyBlockFrequencyInfoPass::ID = 0 static
Definition at line 107 of file LazyBlockFrequencyInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyBlockFrequencyInfo.h
lib/Analysis/LazyBlockFrequencyInfo.cpp