LLVM: llvm::MCSectionWasm Class Reference
llvm::MCSectionWasm Class Reference final
This represents a section on wasm.
#include "llvm/MC/MCSectionWasm.h"
Public Member Functions
bool shouldOmitSectionDirective (StringRef Name, const MCAsmInfo &MAI) const
Decides whether a '.section' directive should be printed before the section name.
StringRef getSectionName () const
const MCSymbolWasm * getGroup () const
void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const override
bool UseCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
bool isVirtualSection () const override
Check whether this section is "virtual", that is has no actual object file contents.
bool isWasmData () const
bool isUnique () const
unsigned getUniqueID () const
uint64_t getSectionOffset () const
void setSectionOffset (uint64_t Offset)
uint32_t getSegmentIndex () const
void setSegmentIndex (uint32_t Index)
bool getPassive () const
void setPassive (bool V=true)
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
unsigned getAlignment () const
void setAlignment (unsigned Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool hasData () const
void setHasData (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
virtual void PrintSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const =0
virtual bool UseCodeAlign () const =0
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
virtual bool isVirtualSection () const =0
Check whether this section is "virtual", that is has no actual object file contents.
Static Public Member Functions
static bool classof (const MCSection *S)
Static Public Member Functions inherited from llvm::MCSection
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0 , SV_ELF , SV_MachO , SV_Wasm ,
SV_XCOFF
}
enum BundleLockStateType { NotBundleLocked , BundleLocked , BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
This represents a section on wasm.
Definition at line 27 of file MCSectionWasm.h.
Member Function Documentation
classof()
static bool llvm::MCSectionWasm::classof (const MCSection * S) inline static
Definition at line 90 of file MCSectionWasm.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_Wasm.
getGroup()
const MCSymbolWasm * llvm::MCSectionWasm::getGroup () const inline
Definition at line 60 of file MCSectionWasm.h.
getPassive()
bool llvm::MCSectionWasm::getPassive () const inline
Definition at line 82 of file MCSectionWasm.h.
References assert(), and isWasmData().
getSectionName()
StringRef llvm::MCSectionWasm::getSectionName () const inline
Definition at line 59 of file MCSectionWasm.h.
Referenced by addData(), and PrintSwitchToSection().
getSectionOffset()
uint64_t llvm::MCSectionWasm::getSectionOffset () const inline
Definition at line 76 of file MCSectionWasm.h.
getSegmentIndex()
uint32_t llvm::MCSectionWasm::getSegmentIndex () const inline
Definition at line 79 of file MCSectionWasm.h.
getUniqueID()
unsigned llvm::MCSectionWasm::getUniqueID () const inline
Definition at line 74 of file MCSectionWasm.h.
isUnique()
bool llvm::MCSectionWasm::isUnique () const inline
Definition at line 73 of file MCSectionWasm.h.
Referenced by PrintSwitchToSection().
isVirtualSection()
bool MCSectionWasm::isVirtualSection () const override virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 94 of file MCSectionWasm.cpp.
isWasmData()
bool llvm::MCSectionWasm::isWasmData () const inline
Definition at line 68 of file MCSectionWasm.h.
References llvm::SectionKind::isGlobalWriteableData(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isThreadLocal(), and llvm::MCSection::Kind.
Referenced by getPassive(), and setPassive().
PrintSwitchToSection()
void MCSectionWasm::PrintSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 47 of file MCSectionWasm.cpp.
References llvm::MCAsmInfo::getCommentString(), getSectionName(), isUnique(), llvm::MCExpr::print(), printName(), and shouldOmitSectionDirective().
setPassive()
void llvm::MCSectionWasm::setPassive (bool V = true) inline
Definition at line 86 of file MCSectionWasm.h.
References assert(), and isWasmData().
setSectionOffset()
void llvm::MCSectionWasm::setSectionOffset (uint64_t Offset) inline
Definition at line 77 of file MCSectionWasm.h.
setSegmentIndex()
void llvm::MCSectionWasm::setSegmentIndex (uint32_t Index) inline
Definition at line 80 of file MCSectionWasm.h.
shouldOmitSectionDirective()
bool MCSectionWasm::shouldOmitSectionDirective (StringRef Name, const MCAsmInfo & MAI) const
Decides whether a '.section' directive should be printed before the section name.
Definition at line 19 of file MCSectionWasm.cpp.
References Name, and llvm::MCAsmInfo::shouldOmitSectionDirective().
Referenced by PrintSwitchToSection().
UseCodeAlign()
bool MCSectionWasm::UseCodeAlign () const override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 92 of file MCSectionWasm.cpp.
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 48 of file MCSectionWasm.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionWasm.h
lib/MC/MCSectionWasm.cpp