LLVM: llvm::LoopAccessLegacyAnalysis Class Reference
llvm::LoopAccessLegacyAnalysis Class Reference
This analysis provides dependence information for the memory accesses of a loop.
#include "llvm/Analysis/LoopAccessAnalysis.h"
Public Member Functions
LoopAccessLegacyAnalysis ()
bool runOnFunction (Function &F) override
void getAnalysisUsage (AnalysisUsage &AU) const override
const LoopAccessInfo & getInfo (Loop *L)
Query the result of the loop access information for the loop L.
void releaseMemory () override
void print (raw_ostream &OS, const Module *M=nullptr) const override
Print the result of the analysis when invoked with -analyze.
Static Public Attributes
static char ID = 0
Detailed Description
This analysis provides dependence information for the memory accesses of a loop.
It runs the analysis for a loop on demand. This can be initiated by querying the loop access info via LAA::getInfo. getInfo return a LoopAccessInfo object. See this class for the specifics of what information is provided.
Definition at line 723 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
LoopAccessLegacyAnalysis()
llvm::LoopAccessLegacyAnalysis::LoopAccessLegacyAnalysis () inline
Definition at line 727 of file LoopAccessAnalysis.h.
Member Function Documentation
getAnalysisUsage()
void LoopAccessLegacyAnalysis::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 2410 of file LoopAccessAnalysis.cpp.
getInfo()
const LoopAccessInfo & LoopAccessLegacyAnalysis::getInfo (Loop * L)
Query the result of the loop access information for the loop L.
If there is no cached result available run the analysis.
Definition at line 2379 of file LoopAccessAnalysis.cpp.
Referenced by print().
print()
void LoopAccessLegacyAnalysis::print (raw_ostream & OS, const Module * M = nullptr) const override
Print the result of the analysis when invoked with -analyze.
Definition at line 2388 of file LoopAccessAnalysis.cpp.
References getInfo(), llvm::raw_ostream::indent(), and llvm::LoopAccessInfo::print().
releaseMemory()
void llvm::LoopAccessLegacyAnalysis::releaseMemory () inline override
Definition at line 740 of file LoopAccessAnalysis.h.
runOnFunction()
bool LoopAccessLegacyAnalysis::runOnFunction (Function & F) override
Definition at line 2399 of file LoopAccessAnalysis.cpp.
Member Data Documentation
ID
char LoopAccessLegacyAnalysis::ID = 0 static
Definition at line 725 of file LoopAccessAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopAccessAnalysis.h
lib/Analysis/LoopAccessAnalysis.cpp