LLVM: llvm::detail::HelperFunctions Class Reference
llvm::detail::HelperFunctions Class Reference
#include "llvm/Support/FormatProviders.h"
Static Protected Member Functions
static Optional< size_t > parseNumericPrecision (StringRef Str)
static bool consumeHexStyle (StringRef &Str, HexPrintStyle &Style)
static size_t consumeNumHexDigits (StringRef &Str, HexPrintStyle Style, size_t Default)
Detailed Description
Definition at line 60 of file FormatProviders.h.
Member Function Documentation
consumeHexStyle()
static bool llvm::detail::HelperFunctions::consumeHexStyle (StringRef & Str, HexPrintStyle & Style) inline static protected
Definition at line 77 of file FormatProviders.h.
References llvm::StringRef::consume_front(), llvm::Lower, llvm::PrefixLower, llvm::PrefixUpper, llvm::StringRef::startswith_lower(), and llvm::Upper.
consumeNumHexDigits()
static size_t llvm::detail::HelperFunctions::consumeNumHexDigits (StringRef & Str, HexPrintStyle Style, size_t Default) inline static protected
Definition at line 92 of file FormatProviders.h.
References llvm::StringRef::consumeInteger(), llvm::Default, and llvm::isPrefixedHexStyle().
parseNumericPrecision()
static Optional< size_t > llvm::detail::HelperFunctions::parseNumericPrecision (StringRef Str) inline static protected
Definition at line 62 of file FormatProviders.h.
References assert(), llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), and llvm::None.
The documentation for this class was generated from the following file:
include/llvm/Support/FormatProviders.h