LLVM: llvm::sys::fs::recursive_directory_iterator Class Reference
llvm::sys::fs::recursive_directory_iterator Class Reference
recursive_directory_iterator - Same as directory_iterator except for it recurses down into child directories.
#include "llvm/Support/FileSystem.h"
Public Member Functions
recursive_directory_iterator ()=default
recursive_directory_iterator (const Twine &path, std::error_code &ec, bool follow_symlinks=true)
recursive_directory_iterator & increment (std::error_code &ec)
const directory_entry & operator* () const
const directory_entry * operator-> () const
int level () const
Gets the current level. Starting path is at level 0.
bool no_push_request () const
Returns true if no_push has been called for this directory_entry.
void pop ()
Goes up one level if Level > 0.
void no_push ()
Does not go down into the current directory_entry.
bool operator== (const recursive_directory_iterator &RHS) const
bool operator!= (const recursive_directory_iterator &RHS) const
Detailed Description
recursive_directory_iterator - Same as directory_iterator except for it recurses down into child directories.
Definition at line 1344 of file FileSystem.h.
Constructor & Destructor Documentation
recursive_directory_iterator() [1/2]
llvm::sys::fs::recursive_directory_iterator::recursive_directory_iterator () default
recursive_directory_iterator() [2/2]
llvm::sys::fs::recursive_directory_iterator::recursive_directory_iterator (const Twine & path, std::error_code & ec, bool follow_symlinks = true) inline explicit
Definition at line 1350 of file FileSystem.h.
Member Function Documentation
increment()
recursive_directory_iterator & llvm::sys::fs::recursive_directory_iterator::increment (std::error_code & ec) inline
Definition at line 1360 of file FileSystem.h.
References llvm::sys::fs::directory_file, llvm::sys::fs::status(), llvm::sys::fs::symlink_file, and llvm::sys::fs::directory_entry::type().
level()
int llvm::sys::fs::recursive_directory_iterator::level () const inline
Gets the current level. Starting path is at level 0.
Definition at line 1402 of file FileSystem.h.
no_push()
void llvm::sys::fs::recursive_directory_iterator::no_push () inline
Does not go down into the current directory_entry.
Definition at line 1429 of file FileSystem.h.
no_push_request()
bool llvm::sys::fs::recursive_directory_iterator::no_push_request () const inline
Returns true if no_push has been called for this directory_entry.
Definition at line 1405 of file FileSystem.h.
operator!=()
bool llvm::sys::fs::recursive_directory_iterator::operator!= (const recursive_directory_iterator & RHS) const inline
Definition at line 1435 of file FileSystem.h.
operator*()
const directory_entry & llvm::sys::fs::recursive_directory_iterator::operator* () const inline
Definition at line 1397 of file FileSystem.h.
operator->()
const directory_entry * llvm::sys::fs::recursive_directory_iterator::operator-> () const inline
Definition at line 1398 of file FileSystem.h.
operator==()
bool llvm::sys::fs::recursive_directory_iterator::operator== (const recursive_directory_iterator & RHS) const inline
Definition at line 1431 of file FileSystem.h.
pop()
void llvm::sys::fs::recursive_directory_iterator::pop () inline
Goes up one level if Level > 0.
Definition at line 1409 of file FileSystem.h.
References assert(), and llvm::report_fatal_error().
The documentation for this class was generated from the following file:
include/llvm/Support/FileSystem.h