LLVM: llvm::TinyPtrVector< EltTy > Class Template Reference
llvm::TinyPtrVector< EltTy > Class Template Reference
TinyPtrVector - This class is specialized for cases where there are normally 0 or 1 element in a vector, but is general enough to go beyond that when required.
#include "llvm/ADT/TinyPtrVector.h"
Public Types
using VecTy = SmallVector< EltTy, 4 >
using value_type = typename VecTy::value_type
using PtrUnion = PointerUnion< EltTy, VecTy * >
using iterator = EltTy *
using const_iterator = const EltTy *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
TinyPtrVector ()=default
~TinyPtrVector ()
TinyPtrVector (const TinyPtrVector &RHS)
TinyPtrVector & operator= (const TinyPtrVector &RHS)
TinyPtrVector (TinyPtrVector &&RHS)
TinyPtrVector & operator= (TinyPtrVector &&RHS)
TinyPtrVector (std::initializer_list< EltTy > IL)
TinyPtrVector (ArrayRef< EltTy > Elts)
Constructor from an ArrayRef.
TinyPtrVector (size_t Count, EltTy Value)
operator ArrayRef< EltTy > () const
operator MutableArrayRef< EltTy > ()
template<typename U , typename std::enable_if< std::is_convertible< ArrayRef< EltTy >, ArrayRef< U > >::value, bool >::type = false>
operator ArrayRef< U > () const
bool empty () const
unsigned size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
EltTy operator[] (unsigned i) const
EltTy front () const
EltTy back () const
void push_back (EltTy NewVal)
void pop_back ()
void clear ()
iterator erase (iterator I)
iterator erase (iterator S, iterator E)
iterator insert (iterator I, const EltTy &Elt)
template<typename ItTy >
iterator insert (iterator I, ItTy From, ItTy To)
Detailed Description
template<typename EltTy>
class llvm::TinyPtrVector< EltTy >
TinyPtrVector - This class is specialized for cases where there are normally 0 or 1 element in a vector, but is general enough to go beyond that when required.
NOTE: This container doesn't allow you to store a null pointer into it.
Definition at line 30 of file TinyPtrVector.h.
Member Typedef Documentation
const_iterator
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::const_iterator = const EltTy *
Definition at line 177 of file TinyPtrVector.h.
const_reverse_iterator
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 179 of file TinyPtrVector.h.
iterator
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::iterator = EltTy *
Definition at line 176 of file TinyPtrVector.h.
PtrUnion
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::PtrUnion = PointerUnion<EltTy, VecTy *>
Definition at line 34 of file TinyPtrVector.h.
reverse_iterator
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 178 of file TinyPtrVector.h.
value_type
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::value_type = typename VecTy::value_type
Definition at line 33 of file TinyPtrVector.h.
VecTy
template<typename EltTy > using llvm::TinyPtrVector< EltTy >::VecTy = SmallVector<EltTy, 4>
Definition at line 32 of file TinyPtrVector.h.
Constructor & Destructor Documentation
TinyPtrVector() [1/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector () default
~TinyPtrVector()
template<typename EltTy > llvm::TinyPtrVector< EltTy >::~TinyPtrVector () inline
Definition at line 42 of file TinyPtrVector.h.
TinyPtrVector() [2/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector (const TinyPtrVector< EltTy > & RHS) inline
Definition at line 47 of file TinyPtrVector.h.
TinyPtrVector() [3/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector (TinyPtrVector< EltTy > && RHS) inline
Definition at line 80 of file TinyPtrVector.h.
TinyPtrVector() [4/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector (std::initializer_list< EltTy > IL) inline
Definition at line 110 of file TinyPtrVector.h.
TinyPtrVector() [5/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector (ArrayRef< EltTy > Elts) inline explicit
Constructor from an ArrayRef.
This also is a constructor for individual array elements due to the single element constructor for ArrayRef.
Definition at line 120 of file TinyPtrVector.h.
TinyPtrVector() [6/6]
template<typename EltTy > llvm::TinyPtrVector< EltTy >::TinyPtrVector (size_t Count, EltTy Value) inline
Definition at line 127 of file TinyPtrVector.h.
Member Function Documentation
back()
template<typename EltTy > EltTy llvm::TinyPtrVector< EltTy >::back () const inline
Definition at line 233 of file TinyPtrVector.h.
References assert(), and llvm::TinyPtrVector< EltTy >::empty().
begin() [1/2]
template<typename EltTy > iterator llvm::TinyPtrVector< EltTy >::begin () inline
Definition at line 181 of file TinyPtrVector.h.
References llvm::PointerUnion< PTs >::getAddrOfPtr1().
Referenced by llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::erase(), llvm::TinyPtrVector< EltTy >::insert(), and llvm::TinyPtrVector< EltTy >::rend().
begin() [2/2]
template<typename EltTy > const_iterator llvm::TinyPtrVector< EltTy >::begin () const inline
Definition at line 195 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin().
clear()
template<typename EltTy > void llvm::TinyPtrVector< EltTy >::clear () inline
Definition at line 267 of file TinyPtrVector.h.
Referenced by llvm::TinyPtrVector< EltTy >::operator=(), and llvm::LoadAndStorePromoter::run().
empty()
template<typename EltTy > bool llvm::TinyPtrVector< EltTy >::empty () const inline
Definition at line 159 of file TinyPtrVector.h.
References llvm::PointerUnion< PTs >::isNull().
Referenced by llvm::TinyPtrVector< EltTy >::back(), llvm::TinyPtrVector< EltTy >::front(), llvm::TinyPtrVector< EltTy >::operator=(), llvm::LoadAndStorePromoter::run(), llvm::TinyPtrVector< EltTy >::size(), unswitchBestCondition(), and unswitchTrivialBranch().
end() [1/2]
template<typename EltTy > iterator llvm::TinyPtrVector< EltTy >::end () inline
Definition at line 188 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin(), and llvm::PointerUnion< PTs >::isNull().
Referenced by llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::erase(), llvm::TinyPtrVector< EltTy >::insert(), and llvm::TinyPtrVector< EltTy >::rbegin().
end() [2/2]
template<typename EltTy > const_iterator llvm::TinyPtrVector< EltTy >::end () const inline
Definition at line 199 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::end().
erase() [1/2]
template<typename EltTy > iterator llvm::TinyPtrVector< EltTy >::erase (iterator I) inline
Definition at line 278 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), and I.
erase() [2/2]
template<typename EltTy > iterator llvm::TinyPtrVector< EltTy >::erase (iterator S, iterator E) inline
Definition at line 294 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), E, and llvm::TinyPtrVector< EltTy >::end().
front()
template<typename EltTy > EltTy llvm::TinyPtrVector< EltTy >::front () const inline
Definition at line 226 of file TinyPtrVector.h.
References assert(), and llvm::TinyPtrVector< EltTy >::empty().
Referenced by CloneInstructionInExitBlock(), createCallInst(), and llvm::TinyPtrVector< EltTy >::operator=().
insert() [1/2]
template<typename EltTy > iterator llvm::TinyPtrVector< EltTy >::insert (iterator I, const EltTy & Elt) inline
Definition at line 308 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), I, llvm::PointerUnion< PTs >::isNull(), and llvm::TinyPtrVector< EltTy >::push_back().
insert() [2/2]
template<typename EltTy > template<typename ItTy > iterator llvm::TinyPtrVector< EltTy >::insert (iterator I, ItTy From, ItTy To) inline
Definition at line 327 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), From, I, and llvm::PointerUnion< PTs >::isNull().
operator ArrayRef< EltTy >()
template<typename EltTy > llvm::TinyPtrVector< EltTy >::operator ArrayRef< EltTy > () const inline
Definition at line 133 of file TinyPtrVector.h.
References llvm::PointerUnion< PTs >::getAddrOfPtr1(), llvm::PointerUnion< PTs >::isNull(), and llvm::None.
operator ArrayRef< U >()
template<typename EltTy > template<typename U , typename std::enable_if< std::is_convertible< ArrayRef< EltTy >, ArrayRef< U > >::value, bool >::type = false> llvm::TinyPtrVector< EltTy >::operator ArrayRef< U > () const inline
Definition at line 155 of file TinyPtrVector.h.
operator MutableArrayRef< EltTy >()
template<typename EltTy > llvm::TinyPtrVector< EltTy >::operator MutableArrayRef< EltTy > () inline
Definition at line 142 of file TinyPtrVector.h.
References llvm::PointerUnion< PTs >::getAddrOfPtr1(), llvm::PointerUnion< PTs >::isNull(), and llvm::None.
operator=() [1/2]
template<typename EltTy > TinyPtrVector & llvm::TinyPtrVector< EltTy >::operator= (const TinyPtrVector< EltTy > & RHS) inline
Definition at line 52 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::clear(), llvm::TinyPtrVector< EltTy >::empty(), llvm::TinyPtrVector< EltTy >::front(), and llvm::TinyPtrVector< EltTy >::size().
operator=() [2/2]
template<typename EltTy > TinyPtrVector & llvm::TinyPtrVector< EltTy >::operator= (TinyPtrVector< EltTy > && RHS) inline
Definition at line 84 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::clear().
operator[]()
template<typename EltTy > EltTy llvm::TinyPtrVector< EltTy >::operator[] (unsigned i) const inline
Definition at line 214 of file TinyPtrVector.h.
References assert(), and llvm::PointerUnion< PTs >::isNull().
pop_back()
template<typename EltTy > void llvm::TinyPtrVector< EltTy >::pop_back () inline
Definition at line 259 of file TinyPtrVector.h.
push_back()
template<typename EltTy > void llvm::TinyPtrVector< EltTy >::push_back (EltTy NewVal) inline
Definition at line 240 of file TinyPtrVector.h.
References assert(), and llvm::PointerUnion< PTs >::isNull().
Referenced by collectHomogenousInstGraphLoopInvariants(), llvm::colorEHFunclets(), llvm::FindDbgAddrUses(), llvm::TinyPtrVector< EltTy >::insert(), and unswitchTrivialBranch().
rbegin() [1/2]
template<typename EltTy > reverse_iterator llvm::TinyPtrVector< EltTy >::rbegin () inline
Definition at line 203 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::end().
rbegin() [2/2]
template<typename EltTy > const_reverse_iterator llvm::TinyPtrVector< EltTy >::rbegin () const inline
Definition at line 206 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::end().
rend() [1/2]
template<typename EltTy > reverse_iterator llvm::TinyPtrVector< EltTy >::rend () inline
Definition at line 204 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin().
rend() [2/2]
template<typename EltTy > const_reverse_iterator llvm::TinyPtrVector< EltTy >::rend () const inline
Definition at line 210 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin().
size()
template<typename EltTy > unsigned llvm::TinyPtrVector< EltTy >::size () const inline
Definition at line 168 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::empty().
Referenced by CloneInstructionInExitBlock(), createCallInst(), llvm::TinyPtrVector< EltTy >::operator=(), and llvm::LoadAndStorePromoter::run().
The documentation for this class was generated from the following file:
include/llvm/ADT/TinyPtrVector.h