LLVM: llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl > Class Template Reference
llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl > Class Template Reference
#include "ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h"
Public Member Functions
BasicGOTAndStubsBuilder (AtomGraph &G)
void run ()
Protected Member Functions
Atom & getGOTEntryAtom (Atom &Target)
Atom & getStubAtom (Atom &Target)
Protected Attributes
AtomGraph & G
Detailed Description
template<typename BuilderImpl>
class llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >
Definition at line 21 of file BasicGOTAndStubsBuilder.h.
Constructor & Destructor Documentation
BasicGOTAndStubsBuilder()
template<typename BuilderImpl > llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::BasicGOTAndStubsBuilder (AtomGraph & G) inline
Definition at line 23 of file BasicGOTAndStubsBuilder.h.
Member Function Documentation
getGOTEntryAtom()
template<typename BuilderImpl > Atom & llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getGOTEntryAtom (Atom & Target) inline protected
Definition at line 40 of file BasicGOTAndStubsBuilder.h.
References assert(), and llvm::Target::getName().
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
getStubAtom()
template<typename BuilderImpl > Atom & llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getStubAtom (Atom & Target) inline protected
Definition at line 56 of file BasicGOTAndStubsBuilder.h.
References assert(), and llvm::Target::getName().
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
run()
template<typename BuilderImpl > void llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run () inline
Definition at line 25 of file BasicGOTAndStubsBuilder.h.
References llvm::jitlink::AtomGraph::defined_atoms(), E, llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::G, llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getGOTEntryAtom(), and llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getStubAtom().
Member Data Documentation
G
template<typename BuilderImpl > AtomGraph& llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::G protected
Definition at line 70 of file BasicGOTAndStubsBuilder.h.
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h