LLVM: llvm::DWARFDie Class Reference
llvm::DWARFDie Class Reference
Utility class that carries the DWARF compile/type unit and the debug info entry in an object.
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
Classes
class attribute_iterator
class iterator
Public Member Functions
DWARFDie ()=default
DWARFDie (DWARFUnit *Unit, const DWARFDebugInfoEntry *D)
bool isValid () const
operator bool () const
const DWARFDebugInfoEntry * getDebugInfoEntry () const
DWARFUnit * getDwarfUnit () const
const DWARFAbbreviationDeclaration * getAbbreviationDeclarationPtr () const
Get the abbreviation declaration for this DIE.
uint32_t getOffset () const
Get the absolute offset into the debug info or types section.
dwarf::Tag getTag () const
bool hasChildren () const
bool isNULL () const
Returns true for a valid DIE that terminates a sibling chain.
bool isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
bool isSubroutineDIE () const
Returns true if DIE represents a subprogram or an inlined subroutine.
DWARFDie getParent () const
Get the parent of this DIE object.
DWARFDie getSibling () const
Get the sibling of this DIE object.
DWARFDie getPreviousSibling () const
Get the previous sibling of this DIE object.
DWARFDie getFirstChild () const
Get the first child of this DIE object.
DWARFDie getLastChild () const
Get the last child of this DIE object.
void dump (raw_ostream &OS, unsigned indent=0, DIDumpOptions DumpOpts=DIDumpOptions()) const
Dump the DIE and all of its attributes to the supplied stream.
LLVM_DUMP_METHOD void dump () const
Convenience zero-argument overload for debugging.
Optional< DWARFFormValue > find (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE.
Optional< DWARFFormValue > find (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE.
Optional< DWARFFormValue > findRecursively (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE and recurse into any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
DWARFDie getAttributeValueAsReferencedDie (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE as the referenced DIE.
DWARFDie getAttributeValueAsReferencedDie (const DWARFFormValue &V) const
Optional< uint64_t > getRangesBaseAttribute () const
Extract the range base attribute from this DIE as absolute section offset.
Optional< uint64_t > getHighPC (uint64_t LowPC) const
Get the DW_AT_high_pc attribute value as an address.
bool getLowAndHighPC (uint64_t &LowPC, uint64_t &HighPC, uint64_t &SectionIndex) const
Retrieves DW_AT_low_pc and DW_AT_high_pc from CU.
Expected< DWARFAddressRangesVector > getAddressRanges () const
Get the address ranges for this DIE.
void collectChildrenAddressRanges (DWARFAddressRangesVector &Ranges) const
Get all address ranges for any DW_TAG_subprogram DIEs in this DIE or any of its children.
bool addressRangeContainsAddress (const uint64_t Address) const
const char * getSubroutineName (DINameKind Kind) const
If a DIE represents a subprogram (or inlined subroutine), returns its mangled name (or short name, if mangled is missing).
const char * getName (DINameKind Kind) const
Return the DIE name resolving DW_AT_sepcification or DW_AT_abstract_origin references if necessary.
uint64_t getDeclLine () const
Returns the declaration line (start line) for a DIE, assuming it specifies a subprogram.
void getCallerFrame (uint32_t &CallFile, uint32_t &CallLine, uint32_t &CallColumn, uint32_t &CallDiscriminator) const
Retrieves values of DW_AT_call_file, DW_AT_call_line and DW_AT_call_column from DIE (or zeroes if they are missing).
iterator_range< attribute_iterator > attributes () const
Get an iterator range to all attributes in the current DIE only.
iterator begin () const
iterator end () const
std::reverse_iterator< iterator > rbegin () const
std::reverse_iterator< iterator > rend () const
iterator_range< iterator > children () const
Detailed Description
Utility class that carries the DWARF compile/type unit and the debug info entry in an object.
When accessing information from a debug info entry we always need to DWARF compile/type unit in order to extract the info correctly as some information is relative to the compile/type unit. Prior to this class the DWARFUnit and the DWARFDebugInfoEntry was passed around separately and there was the possibility for error if the wrong DWARFUnit was used to extract a unit relative offset. This class helps to ensure that this doesn't happen and also simplifies the attribute extraction calls by not having to specify the DWARFUnit for each call.
Definition at line 42 of file DWARFDie.h.
Constructor & Destructor Documentation
DWARFDie() [1/2]
llvm::DWARFDie::DWARFDie () default
Referenced by getAttributeValueAsReferencedDie(), getFirstChild(), getLastChild(), getParent(), getPreviousSibling(), and getSibling().
DWARFDie() [2/2]
llvm::DWARFDie::DWARFDie (DWARFUnit * Unit, const DWARFDebugInfoEntry * D) inline
Definition at line 48 of file DWARFDie.h.
Member Function Documentation
addressRangeContainsAddress()
bool DWARFDie::addressRangeContainsAddress (const uint64_t Address) const
Definition at line 507 of file DWARFDie.cpp.
References llvm::Address, llvm::consumeError(), and getAddressRanges().
Referenced by llvm::DWARFContext::getDIEsForAddress().
attributes()
iterator_range< DWARFDie::attribute_iterator > DWARFDie::attributes () const
Get an iterator range to all attributes in the current DIE only.
Returns
an iterator range for the attributes of the current DIE.
Definition at line 660 of file DWARFDie.cpp.
begin()
DWARFDie::iterator llvm::DWARFDie::begin () const inline
Definition at line 374 of file DWARFDie.h.
References getFirstChild().
Referenced by children(), and rend().
children()
iterator_range< DWARFDie::iterator > llvm::DWARFDie::children () const inline
Definition at line 382 of file DWARFDie.h.
References begin(), and end().
Referenced by collectChildrenAddressRanges().
collectChildrenAddressRanges()
void DWARFDie::collectChildrenAddressRanges (DWARFAddressRangesVector & Ranges) const
Get all address ranges for any DW_TAG_subprogram DIEs in this DIE or any of its children.
Get the hi/low PC range if both attributes are available or exrtracts the non-contiguous address ranges from the DW_AT_ranges attribute for this DIE and all children.
Parameters
Ranges the addres range vector to fill in.
Definition at line 491 of file DWARFDie.cpp.
References children(), llvm::consumeError(), getAddressRanges(), isNULL(), and isSubprogramDIE().
dump() [1/2]
LLVM_DUMP_METHOD void DWARFDie::dump () const
Convenience zero-argument overload for debugging.
Definition at line 628 of file DWARFDie.cpp.
References dump(), and llvm::errs().
Referenced by dump().
dump() [2/2]
void DWARFDie::dump (raw_ostream & OS, unsigned indent = 0, DIDumpOptions DumpOpts = DIDumpOptions()) const
Dump the DIE and all of its attributes to the supplied stream.
Parameters
OS the stream to use for output.
indent the number of characters to indent each line that is output.
Definition at line 566 of file DWARFDie.cpp.
References llvm::Address, llvm::DIDumpOptions::ChildRecurseDepth, dump(), dumpAttribute(), dumpParentChain(), llvm::format(), llvm::formatv(), llvm::WithColor::get(), getAbbreviationDeclarationPtr(), llvm::DWARFUnit::getDebugInfoExtractor(), getFirstChild(), getOffset(), getParent(), getSibling(), getTag(), llvm::DataExtractor::getULEB128(), llvm::raw_ostream::indent(), isValid(), llvm::DataExtractor::isValidOffset(), llvm::DIDumpOptions::ShowAddresses, llvm::DIDumpOptions::ShowChildren, llvm::DIDumpOptions::ShowParents, llvm::Tag, and llvm::DIDumpOptions::Verbose.
Referenced by dump(), and dumpParentChain().
end()
DWARFDie::iterator llvm::DWARFDie::end () const inline
Definition at line 378 of file DWARFDie.h.
References getLastChild().
Referenced by children(), and rbegin().
find() [1/2]
Optional< DWARFFormValue > DWARFDie::find (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE.
Extract the first attribute that matches from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs. The attributes will be searched linearly in the order they are specified within Attrs.
Parameters
Attrs an array of DWARF attribute to look for.
Returns
an optional that has a valid DWARFFormValue for the first matching attribute in Attrs, or None if none of the attributes in Attrs exist in this DIE.
Definition at line 376 of file DWARFDie.cpp.
References getAbbreviationDeclarationPtr(), getOffset(), isValid(), and llvm::None.
find() [2/2]
Optional< DWARFFormValue > DWARFDie::find (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE.
Extract an attribute value from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attr the attribute to extract.
Returns
an optional DWARFFormValue that will have the form value if the attribute was successfully extracted.
Definition at line 366 of file DWARFDie.cpp.
References getAbbreviationDeclarationPtr(), getOffset(), isValid(), and llvm::None.
Referenced by findRecursively(), getAddressRanges(), getAttributeValueAsReferencedDie(), llvm::DWARFUnit::getBaseAddress(), getCallerFrame(), getHighPC(), getLowAndHighPC(), and getRangesBaseAttribute().
findRecursively()
Optional< DWARFFormValue > DWARFDie::findRecursively (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE and recurse into any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attrs an array of DWARF attribute to look for.
Returns
an optional that has a valid DWARFFormValue for the first matching attribute in Attrs, or None if none of the attributes in Attrs exist in this DIE or in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Definition at line 390 of file DWARFDie.cpp.
References find(), getAttributeValueAsReferencedDie(), isValid(), and llvm::None.
Referenced by getDeclLine(), getName(), and isVariableIndexable().
getAbbreviationDeclarationPtr()
const DWARFAbbreviationDeclaration * llvm::DWARFDie::getAbbreviationDeclarationPtr () const inline
Get the abbreviation declaration for this DIE.
Returns
the abbreviation declaration or NULL for null tags.
Definition at line 58 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr(), and isValid().
Referenced by llvm::DWARFDie::attribute_iterator::attribute_iterator(), dump(), find(), getTag(), and isNULL().
getAddressRanges()
Expected< DWARFAddressRangesVector > DWARFDie::getAddressRanges () const
Get the address ranges for this DIE.
Get the hi/low PC range if both attributes are available or exrtracts the non-contiguous address ranges from the DW_AT_ranges attribute.
Extracts the range information from this DIE only. This call doesn't look for the range in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Returns
a address range vector that might be empty if no address range information is available.
Definition at line 474 of file DWARFDie.cpp.
References find(), llvm::DWARFUnit::findRnglistFromIndex(), llvm::DWARFUnit::findRnglistFromOffset(), getLowAndHighPC(), and isNULL().
Referenced by addressRangeContainsAddress(), llvm::DWARFUnit::collectAddressRanges(), collectChildrenAddressRanges(), dumpAttribute(), and llvm::DWARFUnit::updateAddressDieMap().
getAttributeValueAsReferencedDie() [1/2]
DWARFDie DWARFDie::getAttributeValueAsReferencedDie (const DWARFFormValue & V) const
Definition at line 431 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFFormValue::getAsRelativeReference(), llvm::DWARFUnitVector::getUnitForOffset(), and llvm::DWARFUnit::getUnitVector().
getAttributeValueAsReferencedDie() [2/2]
DWARFDie DWARFDie::getAttributeValueAsReferencedDie (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE as the referenced DIE.
Regardless of the reference type, return the correct DWARFDie instance if the attribute exists. The returned DWARFDie object might be from another DWARFUnit, but that is all encapsulated in the new DWARFDie object.
Extract an attribute value from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attr the attribute to extract.
Returns
a valid DWARFDie instance if the attribute exists, or an invalid DWARFDie object if it doesn't.
Definition at line 424 of file DWARFDie.cpp.
References DWARFDie(), F, find(), and getAttributeValueAsReferencedDie().
Referenced by dumpAttribute(), findRecursively(), and getAttributeValueAsReferencedDie().
getCallerFrame()
void DWARFDie::getCallerFrame (uint32_t & CallFile, uint32_t & CallLine, uint32_t & CallColumn, uint32_t & CallDiscriminator) const
Retrieves values of DW_AT_call_file, DW_AT_call_line and DW_AT_call_column from DIE (or zeroes if they are missing).
This function looks for DW_AT_call attributes in this DIE only, it will not resolve the attribute values in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Parameters
CallFile filled in with non-zero if successful, zero if there is no DW_AT_call_file attribute in this DIE.
CallLine filled in with non-zero if successful, zero if there is no DW_AT_call_line attribute in this DIE.
CallColumn filled in with non-zero if successful, zero if there is no DW_AT_call_column attribute in this DIE.
CallDiscriminator filled in with non-zero if successful, zero if there is no DW_AT_GNU_discriminator attribute in this DIE.
Definition at line 545 of file DWARFDie.cpp.
References find(), and llvm::dwarf::toUnsigned().
Referenced by llvm::DWARFContext::getInliningInfoForAddress().
getDebugInfoEntry()
const DWARFDebugInfoEntry * llvm::DWARFDie::getDebugInfoEntry () const inline
Definition at line 52 of file DWARFDie.h.
Referenced by llvm::operator==().
getDeclLine()
uint64_t DWARFDie::getDeclLine () const
Returns the declaration line (start line) for a DIE, assuming it specifies a subprogram.
This may be fetched from specification or abstract origin for this subprogram by resolving DW_AT_sepcification or DW_AT_abstract_origin references if necessary.
Definition at line 541 of file DWARFDie.cpp.
References findRecursively(), and llvm::dwarf::toUnsigned().
Referenced by getFunctionNameAndStartLineForAddress(), and llvm::DWARFContext::getInliningInfoForAddress().
getDwarfUnit()
DWARFUnit * llvm::DWARFDie::getDwarfUnit () const inline
Definition at line 53 of file DWARFDie.h.
Referenced by dumpAttribute(), isVariableIndexable(), and llvm::operator==().
getFirstChild()
DWARFDie DWARFDie::getFirstChild () const
Get the first child of this DIE object.
Returns
a valid DWARFDie instance if this object has children or an invalid DWARFDie instance if it doesn't.
Definition at line 648 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFUnit::getFirstChild(), and isValid().
Referenced by begin(), dump(), and llvm::DWARFUnit::updateAddressDieMap().
getHighPC()
Optional< uint64_t > DWARFDie::getHighPC (uint64_t LowPC) const
Get the DW_AT_high_pc attribute value as an address.
In DWARF version 4 and later the high PC can be encoded as an offset from the DW_AT_low_pc. This function takes care of extracting the value as an address or offset and adds it to the low PC if needed and returns the value as an optional in case the DIE doesn't have a DW_AT_high_pc attribute.
Parameters
LowPC the low PC that might be needed to calculate the high PC.
Returns
an optional address value for the attribute.
Definition at line 445 of file DWARFDie.cpp.
References llvm::Address, find(), and llvm::None.
Referenced by getLowAndHighPC().
getLastChild()
DWARFDie DWARFDie::getLastChild () const
Get the last child of this DIE object.
Returns
a valid null DWARFDie instance if this object has children or an invalid DWARFDie instance if it doesn't.
Definition at line 654 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFUnit::getLastChild(), and isValid().
Referenced by end().
getLowAndHighPC()
bool DWARFDie::getLowAndHighPC (uint64_t & LowPC, uint64_t & HighPC, uint64_t & SectionIndex) const
Retrieves DW_AT_low_pc and DW_AT_high_pc from CU.
Returns true if both attributes are present.
Definition at line 459 of file DWARFDie.cpp.
References F, find(), getHighPC(), and llvm::dwarf::toSectionedAddress().
Referenced by dumpAttribute(), and getAddressRanges().
getName()
const char * DWARFDie::getName (DINameKind Kind) const
Return the DIE name resolving DW_AT_sepcification or DW_AT_abstract_origin references if necessary.
Returns null if no name is found.
Definition at line 526 of file DWARFDie.cpp.
References findRecursively(), isValid(), llvm::LinkageName, llvm::None, and llvm::dwarf::toString().
Referenced by llvm::DWARFTypeUnit::dump(), dumpAttribute(), getNames(), and getSubroutineName().
getOffset()
uint32_t llvm::DWARFDie::getOffset () const inline
Get the absolute offset into the debug info or types section.
Returns
the DIE offset or -1U if invalid.
Definition at line 66 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::getOffset(), and isValid().
Referenced by dump(), find(), and llvm::operator<().
getParent()
DWARFDie DWARFDie::getParent () const
Get the parent of this DIE object.
Returns
a valid DWARFDie instance if this object has a parent or an invalid DWARFDie instance if it doesn't.
Definition at line 630 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFUnit::getParent(), and isValid().
Referenced by dump(), dumpParentChain(), and llvm::DWARFUnit::getInlinedChainForAddress().
getPreviousSibling()
DWARFDie DWARFDie::getPreviousSibling () const
Get the previous sibling of this DIE object.
Returns
a valid DWARFDie instance if this object has a sibling or an invalid DWARFDie instance if it doesn't.
Definition at line 642 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFUnit::getPreviousSibling(), and isValid().
Referenced by std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::DWARFDie::iterator::operator--(), and std::reverse_iterator< llvm::DWARFDie::iterator >::reverse_iterator().
getRangesBaseAttribute()
Optional< uint64_t > DWARFDie::getRangesBaseAttribute () const
Extract the range base attribute from this DIE as absolute section offset.
This is a utility function that checks for either the DW_AT_rnglists_base or DW_AT_GNU_ranges_base attribute.
Returns
anm optional absolute section offset value for the attribute.
Definition at line 441 of file DWARFDie.cpp.
References find(), and llvm::dwarf::toSectionOffset().
getSibling()
DWARFDie DWARFDie::getSibling () const
Get the sibling of this DIE object.
Returns
a valid DWARFDie instance if this object has a sibling or an invalid DWARFDie instance if it doesn't.
Definition at line 636 of file DWARFDie.cpp.
References DWARFDie(), llvm::DWARFUnit::getSibling(), and isValid().
Referenced by std::reverse_iterator< llvm::DWARFDie::iterator >::base(), dump(), llvm::DWARFDie::iterator::operator++(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator--(), and llvm::DWARFUnit::updateAddressDieMap().
getSubroutineName()
const char * DWARFDie::getSubroutineName (DINameKind Kind) const
If a DIE represents a subprogram (or inlined subroutine), returns its mangled name (or short name, if mangled is missing).
This name may be fetched from specification or abstract origin for this subprogram. Returns null if no name is found.
Definition at line 520 of file DWARFDie.cpp.
References getName(), and isSubroutineDIE().
Referenced by getFunctionNameAndStartLineForAddress(), and llvm::DWARFContext::getInliningInfoForAddress().
getTag()
dwarf::Tag llvm::DWARFDie::getTag () const inline
Definition at line 71 of file DWARFDie.h.
References getAbbreviationDeclarationPtr().
Referenced by dump(), llvm::DWARFContext::getDIEsForAddress(), llvm::DWARFUnit::getInlinedChainForAddress(), getNames(), isSubprogramDIE(), and isSubroutineDIE().
hasChildren()
bool llvm::DWARFDie::hasChildren () const inline
Definition at line 78 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::hasChildren(), and isValid().
isNULL()
bool llvm::DWARFDie::isNULL () const inline
Returns true for a valid DIE that terminates a sibling chain.
Definition at line 84 of file DWARFDie.h.
References getAbbreviationDeclarationPtr().
Referenced by collectChildrenAddressRanges(), getAddressRanges(), and std::reverse_iterator< llvm::DWARFDie::iterator >::operator--().
isSubprogramDIE()
bool DWARFDie::isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
Definition at line 359 of file DWARFDie.cpp.
References getTag().
Referenced by collectChildrenAddressRanges(), and llvm::DWARFUnit::getInlinedChainForAddress().
isSubroutineDIE()
bool DWARFDie::isSubroutineDIE () const
Returns true if DIE represents a subprogram or an inlined subroutine.
Definition at line 361 of file DWARFDie.cpp.
References getTag(), and llvm::Tag.
Referenced by getSubroutineName(), and llvm::DWARFUnit::updateAddressDieMap().
isValid()
bool llvm::DWARFDie::isValid () const inline
Definition at line 50 of file DWARFDie.h.
Referenced by dump(), dumpAttribute(), find(), findRecursively(), getAbbreviationDeclarationPtr(), llvm::DWARFContext::getDIEsForAddress(), getFirstChild(), getLastChild(), llvm::DWARFContext::getLocalsForAddress(), getName(), getOffset(), getParent(), getPreviousSibling(), getSibling(), hasChildren(), operator bool(), and std::reverse_iterator< llvm::DWARFDie::iterator >::operator*().
operator bool()
llvm::DWARFDie::operator bool () const inline explicit
Definition at line 51 of file DWARFDie.h.
References isValid().
rbegin()
std::reverse_iterator< DWARFDie::iterator > llvm::DWARFDie::rbegin () const inline
Definition at line 458 of file DWARFDie.h.
References end().
rend()
std::reverse_iterator< DWARFDie::iterator > llvm::DWARFDie::rend () const inline
Definition at line 462 of file DWARFDie.h.
References begin().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDie.h
lib/DebugInfo/DWARF/DWARFDie.cpp