LLVM: llvm::AArch64CallLowering Class Reference
llvm::AArch64CallLowering Class Reference
#include "Target/AArch64/AArch64CallLowering.h"
Public Member Functions
AArch64CallLowering (const AArch64TargetLowering &TLI)
bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const override
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
bool lowerFormalArguments (MachineIRBuilder &MIRBuilder, const Function &F, ArrayRef< ArrayRef< Register > > VRegs) const override
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const override
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs) const override
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
bool supportSwiftError () const override
Public Member Functions inherited from llvm::CallLowering
CallLowering (const TargetLowering *TLI)
virtual ~CallLowering ()=default
virtual bool supportSwiftError () const
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
virtual bool lowerReturn (MachineIRBuilder &MIRBuilder, const Value *Val, ArrayRef< Register > VRegs) const
This hook behaves as the extended lowerReturn function, but for targets that do not support swifterror value promotion.
virtual bool lowerFormalArguments (MachineIRBuilder &MIRBuilder, const Function &F, ArrayRef< ArrayRef< Register > > VRegs) const
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
virtual bool lowerCall (MachineIRBuilder &MIRBuilder, CallingConv::ID CallConv, const MachineOperand &Callee, const ArgInfo &OrigRet, ArrayRef< ArgInfo > OrigArgs) const
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
bool lowerCall (MachineIRBuilder &MIRBuilder, ImmutableCallSite CS, ArrayRef< Register > ResRegs, ArrayRef< ArrayRef< Register > > ArgRegs, Register SwiftErrorVReg, std::function< unsigned()> GetCalleeReg) const
Lower the given call instruction, including argument and return value marshalling.
Additional Inherited Members
Protected Member Functions inherited from llvm::CallLowering
const TargetLowering * getTLI () const
Getter for generic TargetLowering class.
template<class XXXTargetLowering >
const XXXTargetLowering * getTLI () const
Getter for target specific TargetLowering class.
template<typename FuncInfoTy >
void setArgFlags (ArgInfo &Arg, unsigned OpIdx, const DataLayout &DL, const FuncInfoTy &FuncInfo) const
Register packRegs (ArrayRef< Register > SrcRegs, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for packing SrcRegs into one big register corresponding to the aggregate type PackedTy.
void unpackRegs (ArrayRef< Register > DstRegs, Register SrcReg, Type *PackedTy, MachineIRBuilder &MIRBuilder) const
Generate instructions for unpacking SrcReg into the DstRegs corresponding to the aggregate type PackedTy.
bool handleAssignments (MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Invoke Handler::assignArg on each of the given Args and then use Callback to move them to the assigned locations.
bool handleAssignments (CCState &CCState, SmallVectorImpl< CCValAssign > &ArgLocs, MachineIRBuilder &MIRBuilder, ArrayRef< ArgInfo > Args, ValueHandler &Handler) const
Detailed Description
Definition at line 32 of file AArch64CallLowering.h.
Constructor & Destructor Documentation
AArch64CallLowering()
AArch64CallLowering::AArch64CallLowering (const AArch64TargetLowering & TLI)
Definition at line 51 of file AArch64CallLowering.cpp.
Member Function Documentation
lowerCall() [1/2]
bool llvm::AArch64CallLowering::lowerCall (MachineIRBuilder & MIRBuilder, CallingConv::ID CallConv, const MachineOperand & Callee, const ArgInfo & OrigRet, ArrayRef< ArgInfo > OrigArgs) const inline override virtual
This hook behaves as the extended lowerCall function, but for targets that do not support swifterror value promotion.
Reimplemented from llvm::CallLowering.
Definition at line 48 of file AArch64CallLowering.h.
References Callee, and lowerCall().
lowerCall() [2/2]
bool AArch64CallLowering::lowerCall (MachineIRBuilder & MIRBuilder, CallingConv::ID CallConv, const MachineOperand & Callee, const ArgInfo & OrigRet, ArrayRef< ArgInfo > OrigArgs, Register SwiftErrorVReg) const override virtual
This hook must be implemented to lower the given call instruction, including argument and return value marshalling.
CallConv is the calling convention to be used for the call.
Callee is the destination of the call. It should be either a register, globaladdress, or externalsymbol.
OrigRet is a descriptor for the return type of the function.
OrigArgs is a list of descriptors of the arguments passed to the function.
SwiftErrorVReg is non-zero if the call has a swifterror inout parameter, and contains the vreg that the swifterror should be copied into after the call.
Returns
true if the lowering succeeded, false otherwise.
Reimplemented from llvm::CallLowering.
Definition at line 404 of file AArch64CallLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstrNoInsert(), Callee, llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::SmallVectorImpl< T >::clear(), llvm::constrainOperandRegClass(), F, llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::TargetSubtargetInfo::getRegBankInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::CallLowering::handleAssignments(), llvm::AArch64Subtarget::hasCustomCallingConv(), llvm::RegState::Implicit, llvm::MachineIRBuilder::insertInstr(), llvm::Type::isVoidTy(), MRI, llvm::MachineOperand::setReg(), TRI, and llvm::CallLowering::ArgInfo::Ty.
Referenced by lowerCall().
lowerFormalArguments()
bool AArch64CallLowering::lowerFormalArguments (MachineIRBuilder & MIRBuilder, const Function & F, ArrayRef< ArrayRef< Register > > VRegs) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by VRegs, for GlobalISel.
Each argument must end up in the related virtual registers described by VRegs. In other words, the first argument should end up in VRegs[0], the second in VRegs[1], and so on. For each argument, there will be one register for each non-aggregate type, as returned by computeValueLLTs. MIRBuilder is set to the proper insertion for the argument lowering.
Returns
True if the lowering succeeded, false otherwise.
Reimplemented from llvm::CallLowering.
Definition at line 347 of file AArch64CallLowering.cpp.
References llvm::alignTo(), Arg, llvm::MachineBasicBlock::begin(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::MachineBasicBlock::empty(), F, llvm::AttributeList::FirstArgIndex, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineIRBuilder::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getRegInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::DataLayout::getTypeStoreSize(), llvm::CallLowering::handleAssignments(), llvm::AArch64Subtarget::isTargetDarwin(), MRI, llvm::CallLowering::setArgFlags(), llvm::MachineIRBuilder::setInstr(), llvm::MachineIRBuilder::setMBB(), llvm::AArch64FunctionInfo::setVarArgsStackIndex(), and llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs().
lowerReturn()
bool AArch64CallLowering::lowerReturn (MachineIRBuilder & MIRBuilder, const Value * Val, ArrayRef< Register > VRegs, Register SwiftErrorVReg) const override virtual
This hook must be implemented to lower outgoing return values, described by Val, into the specified virtual registers VRegs.
This hook is used by GlobalISel.
SwiftErrorVReg is non-zero if the function has a swifterror parameter that needs to be implicitly returned.
Returns
True if the lowering succeeds, false otherwise.
Reimplemented from llvm::CallLowering.
Definition at line 230 of file AArch64CallLowering.cpp.
References assert(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildUndef(), llvm::MachineIRBuilder::buildZExt(), llvm::AArch64TargetLowering::CCAssignFnForReturn(), llvm::ComputeValueVTs(), llvm::dbgs(), llvm::ArrayRef< T >::empty(), F, llvm::Type::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), llvm::LLT::getNumElements(), llvm::TargetLoweringBase::getNumRegistersForCallingConv(), getReg(), llvm::MachineInstrBuilder::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::Value::getType(), llvm::EVT::getTypeForEVT(), llvm::VTSDNode::getVT(), llvm::CallLowering::handleAssignments(), llvm::RegState::Implicit, llvm::MachineIRBuilder::insertInstr(), llvm::LLT::isVector(), llvm::MVT::isVector(), LLVM_DEBUG, MRI, llvm::CallLowering::ArgInfo::Regs, llvm::AttributeList::ReturnIndex, llvm::LLT::scalar(), llvm::CallLowering::setArgFlags(), llvm::CCValAssign::SExt, llvm::ArrayRef< T >::size(), llvm::SmallVectorBase::size(), Success, llvm::CallLowering::ArgInfo::Ty, and llvm::CCValAssign::ZExt.
supportSwiftError()
bool llvm::AArch64CallLowering::supportSwiftError () const inline override virtual
Returns
true if the target is capable of handling swifterror values that have been promoted to a specified register. The extended versions of lowerReturn and lowerCall should be implemented.
Reimplemented from llvm::CallLowering.
Definition at line 54 of file AArch64CallLowering.h.
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64CallLowering.h
lib/Target/AArch64/AArch64CallLowering.cpp