LLVM: llvm::BranchProbabilityInfoWrapperPass Class Reference
llvm::BranchProbabilityInfoWrapperPass Class Reference
Legacy analysis pass which computes BranchProbabilityInfo.
#include "llvm/Analysis/BranchProbabilityInfo.h"
Public Member Functions
BranchProbabilityInfoWrapperPass ()
BranchProbabilityInfo & getBPI ()
const BranchProbabilityInfo & getBPI () const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
void releaseMemory () override
void print (raw_ostream &OS, const Module *M=nullptr) const override
Static Public Attributes
static char ID = 0
Detailed Description
Legacy analysis pass which computes BranchProbabilityInfo.
Definition at line 230 of file BranchProbabilityInfo.h.
Constructor & Destructor Documentation
BranchProbabilityInfoWrapperPass()
llvm::BranchProbabilityInfoWrapperPass::BranchProbabilityInfoWrapperPass () inline
Definition at line 236 of file BranchProbabilityInfo.h.
Member Function Documentation
getAnalysisUsage()
void BranchProbabilityInfoWrapperPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 1004 of file BranchProbabilityInfo.cpp.
getBPI() [1/2]
BranchProbabilityInfo & llvm::BranchProbabilityInfoWrapperPass::getBPI () inline
Definition at line 241 of file BranchProbabilityInfo.h.
getBPI() [2/2]
const BranchProbabilityInfo & llvm::BranchProbabilityInfoWrapperPass::getBPI () const inline
Definition at line 242 of file BranchProbabilityInfo.h.
print()
void BranchProbabilityInfoWrapperPass::print (raw_ostream & OS, const Module * M = nullptr) const override
Definition at line 1024 of file BranchProbabilityInfo.cpp.
References llvm::BranchProbabilityInfo::print().
releaseMemory()
void BranchProbabilityInfoWrapperPass::releaseMemory () override
Definition at line 1022 of file BranchProbabilityInfo.cpp.
References llvm::BranchProbabilityInfo::releaseMemory().
runOnFunction()
bool BranchProbabilityInfoWrapperPass::runOnFunction (Function & F) override
Definition at line 1015 of file BranchProbabilityInfo.cpp.
References llvm::BranchProbabilityInfo::calculate(), and F.
Member Data Documentation
ID
branch Branch Probability true char BranchProbabilityInfoWrapperPass::ID = 0 static
Definition at line 234 of file BranchProbabilityInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/BranchProbabilityInfo.h
lib/Analysis/BranchProbabilityInfo.cpp