LLVM: llvm::MCAsmBackend Class Reference
llvm::MCAsmBackend Class Reference abstract
Generic interface to target specific assembler backends.
#include "llvm/MC/MCAsmBackend.h"
Public Member Functions
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
void handleCodePaddingBasicBlockStart (MCObjectStreamer *OS, const MCCodePaddingContext &Context)
Handles all target related code padding when starting to write a new basic block to an object file.
void handleCodePaddingBasicBlockEnd (const MCCodePaddingContext &Context)
Handles all target related code padding after writing a block to an object file.
void handleCodePaddingInstructionBegin (const MCInst &Inst)
Handles all target related code padding before writing a new instruction to an object file.
void handleCodePaddingInstructionEnd (const MCInst &Inst)
Handles all target related code padding after writing an instruction to an object file.
bool relaxFragment (MCPaddingFragment *PF, MCAsmLayout &Layout)
Relaxes a fragment (changes the size of the padding) according to target requirements.
Target Fixup Interfaces
virtual unsigned getNumFixupKinds () const =0
Get the number of target specific fixup kinds.
virtual Optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const
Get information on a fixup kind.
virtual bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target)
Hook to check if a relocation is needed for some target specific reason.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const =0
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
virtual bool requiresDiffExpressionRelocations () const
Check whether the given target requires emitting differences of two symbols as a set of relocations.
Target Relaxation Interfaces
virtual bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const =0
Check whether the given instruction may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const =0
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual void relaxInstruction (const MCInst &Inst, const MCSubtargetInfo &STI, MCInst &Res) const =0
Relax the instruction in the given fragment to the next wider instruction.
Public Attributes
const support::endianness Endian
Protected Member Functions
MCAsmBackend (support::endianness Endian)
Detailed Description
Generic interface to target specific assembler backends.
Definition at line 41 of file MCAsmBackend.h.
Constructor & Destructor Documentation
MCAsmBackend() [1/2]
MCAsmBackend::MCAsmBackend (support::endianness Endian) protected
Definition at line 26 of file MCAsmBackend.cpp.
MCAsmBackend() [2/2]
llvm::MCAsmBackend::MCAsmBackend (const MCAsmBackend &) delete
~MCAsmBackend()
MCAsmBackend::~MCAsmBackend () virtual default
Member Function Documentation
applyFixup()
virtual void llvm::MCAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const pure virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Referenced by llvm::MCAssembler::layout().
createDwoObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createDwoObjectWriter (raw_pwrite_stream & OS, raw_pwrite_stream & DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
This function is only supported with ELF targets.
Definition at line 56 of file MCAsmBackend.cpp.
References llvm::createELFDwoObjectWriter(), createObjectTargetWriter(), llvm::Triple::ELF, Endian, llvm::support::little, and llvm::report_fatal_error().
Referenced by llvm::LLVMTargetMachine::addAsmPrinter().
createObjectTargetWriter()
virtual std::unique_ptr< MCObjectTargetWriter > llvm::MCAsmBackend::createObjectTargetWriter () const pure virtual
Implemented in llvm::ARMAsmBackendDarwin, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Referenced by createDwoObjectWriter(), and createObjectWriter().
createObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createObjectWriter (raw_pwrite_stream & OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
Definition at line 32 of file MCAsmBackend.cpp.
References llvm::Triple::COFF, llvm::createELFObjectWriter(), llvm::createMachObjectWriter(), createObjectTargetWriter(), llvm::createWasmObjectWriter(), llvm::createWinCOFFObjectWriter(), llvm::createXCOFFObjectWriter(), llvm::Triple::ELF, Endian, llvm::support::little, llvm_unreachable, llvm::Triple::MachO, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
finishLayout()
virtual void llvm::MCAsmBackend::finishLayout (MCAssembler const & Asm, MCAsmLayout & Layout) const inline virtual
Give backend an opportunity to finish layout after relaxation.
Definition at line 171 of file MCAsmBackend.h.
fixupNeedsRelaxation()
virtual bool llvm::MCAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const pure virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Referenced by fixupNeedsRelaxationAdvanced().
fixupNeedsRelaxationAdvanced()
bool MCAsmBackend::fixupNeedsRelaxationAdvanced (const MCFixup & Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout, const bool WasForced) const virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 105 of file MCAsmBackend.cpp.
References Fixup, and fixupNeedsRelaxation().
generateCompactUnwindEncoding()
virtual uint32_t llvm::MCAsmBackend::generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const inline virtual
Generate the compact unwind encoding for the CFI instructions.
Reimplemented in llvm::ARMAsmBackendDarwin.
Definition at line 179 of file MCAsmBackend.h.
Referenced by llvm::MCStreamer::generateCompactUnwindEncodings().
getFixupKind()
Optional< MCFixupKind > MCAsmBackend::getFixupKind (StringRef Name) const virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented in llvm::ARMAsmBackend, and llvm::MipsAsmBackend.
Definition at line 65 of file MCAsmBackend.cpp.
References llvm::None.
Referenced by llvm::MCObjectStreamer::EmitRelocDirective().
getFixupKindInfo()
const MCFixupKindInfo & MCAsmBackend::getFixupKindInfo (MCFixupKind Kind) const virtual
Get information on a fixup kind.
Reimplemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 69 of file MCAsmBackend.cpp.
References llvm::array_lengthof(), assert(), and llvm::MCFixupKindInfo::FKF_IsPCRel.
Referenced by llvm::ARMAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), and llvm::RISCVAsmBackend::getFixupKindInfo().
getMinimumNopSize()
virtual unsigned llvm::MCAsmBackend::getMinimumNopSize () const inline virtual
Returns the minimum size of a nop in bytes on this target.
The assembler will use this to emit excess padding in situations where the padding required for simple alignment would be less than the minimum nop size.
Definition at line 162 of file MCAsmBackend.h.
getNumFixupKinds()
virtual unsigned llvm::MCAsmBackend::getNumFixupKinds () const pure virtual
Get the number of target specific fixup kinds.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
handleAssemblerFlag()
virtual void llvm::MCAsmBackend::handleAssemblerFlag (MCAssemblerFlag Flag) inline virtual
Handle any target-specific assembler flags. By default, do nothing.
Reimplemented in llvm::ARMAsmBackend.
Definition at line 175 of file MCAsmBackend.h.
Referenced by llvm::MCELFStreamer::EmitAssemblerFlag(), and llvm::MCWasmStreamer::EmitAssemblerFlag().
handleCodePaddingBasicBlockEnd()
void MCAsmBackend::handleCodePaddingBasicBlockEnd (const MCCodePaddingContext & Context)
Handles all target related code padding after writing a block to an object file.
Parameters
Context the context of the padding, Embeds the basic block's parameters.
Definition at line 119 of file MCAsmBackend.cpp.
References Context.
Referenced by llvm::MCObjectStreamer::EmitCodePaddingBasicBlockEnd().
handleCodePaddingBasicBlockStart()
void MCAsmBackend::handleCodePaddingBasicBlockStart (MCObjectStreamer * OS, const MCCodePaddingContext & Context)
Handles all target related code padding when starting to write a new basic block to an object file.
Parameters
OS The streamer used for writing the padding data and function.
Context the context of the padding, Embeds the basic block's parameters.
Definition at line 114 of file MCAsmBackend.cpp.
References Context.
Referenced by llvm::MCObjectStreamer::EmitCodePaddingBasicBlockStart().
handleCodePaddingInstructionBegin()
void MCAsmBackend::handleCodePaddingInstructionBegin (const MCInst & Inst)
Handles all target related code padding before writing a new instruction to an object file.
Parameters
Inst the instruction.
Definition at line 124 of file MCAsmBackend.cpp.
Referenced by llvm::MCObjectStreamer::EmitInstruction().
handleCodePaddingInstructionEnd()
void MCAsmBackend::handleCodePaddingInstructionEnd (const MCInst & Inst)
Handles all target related code padding after writing an instruction to an object file.
Parameters
Inst the instruction.
Definition at line 128 of file MCAsmBackend.cpp.
Referenced by llvm::MCObjectStreamer::EmitInstruction().
isMicroMips()
virtual bool llvm::MCAsmBackend::isMicroMips (const MCSymbol * Sym) const inline virtual
Check whether a given symbol has been flagged with MICROMIPS flag.
Reimplemented in llvm::MipsAsmBackend.
Definition at line 184 of file MCAsmBackend.h.
mayNeedRelaxation()
virtual bool llvm::MCAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const pure virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
operator=()
MCAsmBackend & llvm::MCAsmBackend::operator= (const MCAsmBackend &) delete
relaxFragment()
bool MCAsmBackend::relaxFragment (MCPaddingFragment * PF, MCAsmLayout & Layout)
Relaxes a fragment (changes the size of the padding) according to target requirements.
The new size computation is done w.r.t a layout.
Parameters
PF The fragment to relax.
Layout Code layout information.
Returns
true iff any relaxation occurred.
Definition at line 132 of file MCAsmBackend.cpp.
relaxInstruction()
virtual void llvm::MCAsmBackend::relaxInstruction (const MCInst & Inst, const MCSubtargetInfo & STI, MCInst & Res) const pure virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
Inst The instruction to relax, which may be the same as the output.
STI the subtarget information for the associated instruction.
[out] Res On return, the relaxed instruction.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
requiresDiffExpressionRelocations()
virtual bool llvm::MCAsmBackend::requiresDiffExpressionRelocations () const inline virtual
Check whether the given target requires emitting differences of two symbols as a set of relocations.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 119 of file MCAsmBackend.h.
reset()
virtual void llvm::MCAsmBackend::reset () inline virtual
lifetime management
Definition at line 55 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::reset().
shouldForceRelocation()
virtual bool llvm::MCAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target) inline virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 84 of file MCAsmBackend.h.
shouldInsertExtraNopBytesForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment & AF, unsigned & Size) inline virtual
Hook to check if extra nop bytes must be inserted for alignment directive.
For some targets this may be necessary in order to support linker relaxation. The number of bytes to insert are returned in Size.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 93 of file MCAsmBackend.h.
shouldInsertFixupForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertFixupForCodeAlign (MCAssembler & Asm, const MCAsmLayout & Layout, MCAlignFragment & AF) inline virtual
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 100 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::layout().
writeNopData()
virtual bool llvm::MCAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count) const pure virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Member Data Documentation
Endian
const support::endianness llvm::MCAsmBackend::Endian
Definition at line 52 of file MCAsmBackend.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), llvm::ARMAsmBackend::applyFixup(), llvm::MipsAsmBackend::applyFixup(), createDwoObjectWriter(), createObjectWriter(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), and llvm::ARMAsmBackend::writeNopData().
The documentation for this class was generated from the following files:
include/llvm/MC/MCAsmBackend.h
lib/MC/MCAsmBackend.cpp