LLVM: llvm::ARMConstantPoolConstant Class Reference
llvm::ARMConstantPoolConstant Class Reference
ARMConstantPoolConstant - ARM-specific constant pool values for Constants, Functions, and BlockAddresses.
#include "Target/ARM/ARMConstantPoolValue.h"
Public Types
using promoted_iterator = SmallPtrSet< const GlobalVariable *, 1 >::iterator
Public Member Functions
const GlobalValue * getGV () const
const BlockAddress * getBlockAddress () const
iterator_range< promoted_iterator > promotedGlobals ()
const Constant * getPromotedGlobalInit () const
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
bool hasSameValue (ARMConstantPoolValue *ACPV) override
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const ARMConstantPoolConstant *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
~ARMConstantPoolValue () override
ARMCP::ARMCPModifier getModifier () const
StringRef getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
bool isPromotedGlobal () const
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
getType - get type of this MachineConstantPoolValue.
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment)=0
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)=0
virtual void print (raw_ostream &O) const =0
print - Implement operator<<
Static Public Member Functions
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID)
static ARMConstantPoolConstant * Create (const GlobalValue *GV, ARMCP::ARMCPModifier Modifier)
static ARMConstantPoolConstant * Create (const GlobalVariable *GV, const Constant *Initializer)
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj)
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
static bool classof (const ARMConstantPoolValue *APV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolConstant - ARM-specific constant pool values for Constants, Functions, and BlockAddresses.
Definition at line 143 of file ARMConstantPoolValue.h.
Member Typedef Documentation
promoted_iterator
using llvm::ARMConstantPoolConstant::promoted_iterator = SmallPtrSet<const GlobalVariable *, 1>::iterator
Definition at line 179 of file ARMConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void ARMConstantPoolConstant::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 208 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::ARMConstantPoolConstant::classof (const ARMConstantPoolValue * APV) inline static
Definition at line 200 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isGlobalValue(), llvm::ARMConstantPoolValue::isLSDA(), and llvm::ARMConstantPoolValue::isPromotedGlobal().
Create() [1/5]
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID) static
Definition at line 147 of file ARMConstantPoolValue.cpp.
References C, llvm::ARMCP::CPValue, and llvm::ARMCP::no_modifier.
Referenced by duplicateCPV(), and promoteToConstantPool().
Create() [2/5]
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj) static
Definition at line 167 of file ARMConstantPoolValue.cpp.
References C, and llvm::ARMCP::no_modifier.
Create() [3/5]
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) static
Definition at line 174 of file ARMConstantPoolValue.cpp.
References C.
Create() [4/5]
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const GlobalValue * GV, ARMCP::ARMCPModifier Modifier) static
Definition at line 159 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::CPValue, llvm::Value::getContext(), and llvm::IRBuilderBase::getInt32Ty().
Create() [5/5]
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const GlobalVariable * GV, const Constant * Initializer) static
Definition at line 153 of file ARMConstantPoolValue.cpp.
equals()
bool llvm::ARMConstantPoolConstant::equals (const ARMConstantPoolConstant * A) const inline
Definition at line 205 of file ARMConstantPoolValue.h.
References A, and llvm::ARMConstantPoolValue::equals().
getBlockAddress()
const BlockAddress * ARMConstantPoolConstant::getBlockAddress () const
Definition at line 186 of file ARMConstantPoolValue.cpp.
getExistingMachineCPValue()
int ARMConstantPoolConstant::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 190 of file ARMConstantPoolValue.cpp.
getGV()
const GlobalValue * ARMConstantPoolConstant::getGV () const
Definition at line 182 of file ARMConstantPoolValue.cpp.
getPromotedGlobalInit()
const Constant * llvm::ARMConstantPoolConstant::getPromotedGlobalInit () const inline
Definition at line 185 of file ARMConstantPoolValue.h.
hasSameValue()
bool ARMConstantPoolConstant::hasSameValue (ARMConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 203 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::hasSameValue().
print()
void ARMConstantPoolConstant::print (raw_ostream & O) const override virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 215 of file ARMConstantPoolValue.cpp.
References llvm::Value::getName(), and llvm::GISelCSEInfo::print().
promotedGlobals()
iterator_range< promoted_iterator > llvm::ARMConstantPoolConstant::promotedGlobals () inline
Definition at line 181 of file ARMConstantPoolValue.h.
References llvm::SmallPtrSetImpl< PtrType >::begin(), and llvm::SmallPtrSetImpl< PtrType >::end().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMConstantPoolValue.h
lib/Target/ARM/ARMConstantPoolValue.cpp