LLVM: llvm::MachineDominanceFrontier Class Reference
llvm::MachineDominanceFrontier Class Reference
#include "llvm/CodeGen/MachineDominanceFrontier.h"
Public Types
using DomTreeT = DomTreeBase< MachineBasicBlock >
using DomTreeNodeT = DomTreeNodeBase< MachineBasicBlock >
using DomSetType = DominanceFrontierBase< MachineBasicBlock, false >::DomSetType
using iterator = DominanceFrontierBase< MachineBasicBlock, false >::iterator
using const_iterator = DominanceFrontierBase< MachineBasicBlock, false >::const_iterator
Public Member Functions
MachineDominanceFrontier (const MachineDominanceFrontier &)=delete
MachineDominanceFrontier & operator= (const MachineDominanceFrontier &)=delete
MachineDominanceFrontier ()
ForwardDominanceFrontierBase< MachineBasicBlock > & getBase ()
const SmallVectorImpl< MachineBasicBlock * > & getRoots () const
MachineBasicBlock * getRoot () const
bool isPostDominator () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator find (MachineBasicBlock *B)
const_iterator find (MachineBasicBlock *B) const
iterator addBasicBlock (MachineBasicBlock *BB, const DomSetType &frontier)
void removeBlock (MachineBasicBlock *BB)
void addToFrontier (iterator I, MachineBasicBlock *Node)
void removeFromFrontier (iterator I, MachineBasicBlock *Node)
bool compareDomSet (DomSetType &DS1, const DomSetType &DS2) const
bool compare (DominanceFrontierBase< MachineBasicBlock, false > &Other) const
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 21 of file MachineDominanceFrontier.h.
Member Typedef Documentation
const_iterator
using llvm::MachineDominanceFrontier::const_iterator = DominanceFrontierBase<MachineBasicBlock, false>::const_iterator
Definition at line 29 of file MachineDominanceFrontier.h.
DomSetType
using llvm::MachineDominanceFrontier::DomSetType = DominanceFrontierBase<MachineBasicBlock, false>::DomSetType
Definition at line 27 of file MachineDominanceFrontier.h.
DomTreeNodeT
using llvm::MachineDominanceFrontier::DomTreeNodeT = DomTreeNodeBase<MachineBasicBlock>
Definition at line 26 of file MachineDominanceFrontier.h.
DomTreeT
using llvm::MachineDominanceFrontier::DomTreeT = DomTreeBase<MachineBasicBlock>
Definition at line 25 of file MachineDominanceFrontier.h.
iterator
using llvm::MachineDominanceFrontier::iterator = DominanceFrontierBase<MachineBasicBlock, false>::iterator
Definition at line 28 of file MachineDominanceFrontier.h.
Constructor & Destructor Documentation
MachineDominanceFrontier() [1/2]
llvm::MachineDominanceFrontier::MachineDominanceFrontier (const MachineDominanceFrontier &) delete
MachineDominanceFrontier() [2/2]
machine Machine Dominance Frontier true MachineDominanceFrontier::MachineDominanceFrontier ()
Definition at line 31 of file MachineDominanceFrontier.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineDominanceFrontierPass().
Member Function Documentation
addBasicBlock()
iterator llvm::MachineDominanceFrontier::addBasicBlock (MachineBasicBlock * BB, const DomSetType & frontier) inline
Definition at line 77 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::addBasicBlock().
addToFrontier()
void llvm::MachineDominanceFrontier::addToFrontier (iterator I, MachineBasicBlock * Node) inline
Definition at line 85 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::addToFrontier(), and I.
begin() [1/2]
iterator llvm::MachineDominanceFrontier::begin () inline
Definition at line 53 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::begin().
begin() [2/2]
const_iterator llvm::MachineDominanceFrontier::begin () const inline
Definition at line 57 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::begin().
compare()
bool llvm::MachineDominanceFrontier::compare (DominanceFrontierBase< MachineBasicBlock, false > & Other) const inline
Definition at line 97 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::compare(), and Other.
compareDomSet()
bool llvm::MachineDominanceFrontier::compareDomSet (DomSetType & DS1, const DomSetType & DS2) const inline
Definition at line 93 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::compareDomSet().
end() [1/2]
iterator llvm::MachineDominanceFrontier::end () inline
Definition at line 61 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::end().
Referenced by llvm::rdf::Liveness::computeLiveIns().
end() [2/2]
const_iterator llvm::MachineDominanceFrontier::end () const inline
Definition at line 65 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::end().
find() [1/2]
iterator llvm::MachineDominanceFrontier::find (MachineBasicBlock * B) inline
Definition at line 69 of file MachineDominanceFrontier.h.
References B, and llvm::DominanceFrontierBase< BlockT, IsPostDom >::find().
Referenced by llvm::rdf::Liveness::computeLiveIns().
find() [2/2]
const_iterator llvm::MachineDominanceFrontier::find (MachineBasicBlock * B) const inline
Definition at line 73 of file MachineDominanceFrontier.h.
References B, and llvm::DominanceFrontierBase< BlockT, IsPostDom >::find().
getAnalysisUsage()
void MachineDominanceFrontier::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 49 of file MachineDominanceFrontier.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getBase()
ForwardDominanceFrontierBase< MachineBasicBlock > & llvm::MachineDominanceFrontier::getBase () inline
Definition at line 39 of file MachineDominanceFrontier.h.
Referenced by runOnMachineFunction().
getRoot()
MachineBasicBlock * llvm::MachineDominanceFrontier::getRoot () const inline
Definition at line 45 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::getRoot().
getRoots()
const SmallVectorImpl< MachineBasicBlock * > & llvm::MachineDominanceFrontier::getRoots () const inline
Definition at line 41 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::getRoots().
isPostDominator()
bool llvm::MachineDominanceFrontier::isPostDominator () const inline
Definition at line 49 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::isPostDominator().
operator=()
MachineDominanceFrontier & llvm::MachineDominanceFrontier::operator= (const MachineDominanceFrontier &) delete
releaseMemory()
void MachineDominanceFrontier::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 45 of file MachineDominanceFrontier.cpp.
Referenced by runOnMachineFunction().
removeBlock()
void llvm::MachineDominanceFrontier::removeBlock (MachineBasicBlock * BB) inline
Definition at line 81 of file MachineDominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT, IsPostDom >::removeBlock().
removeFromFrontier()
void llvm::MachineDominanceFrontier::removeFromFrontier (iterator I, MachineBasicBlock * Node) inline
Definition at line 89 of file MachineDominanceFrontier.h.
References I, and llvm::DominanceFrontierBase< BlockT, IsPostDom >::removeFromFrontier().
runOnMachineFunction()
bool MachineDominanceFrontier::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 39 of file MachineDominanceFrontier.cpp.
References getBase(), and releaseMemory().
Member Data Documentation
ID
char MachineDominanceFrontier::ID = 0 static
Definition at line 35 of file MachineDominanceFrontier.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineDominanceFrontier.h
lib/CodeGen/MachineDominanceFrontier.cpp