LLVM: llvm::AMDGPUSubtarget Class Reference
llvm::AMDGPUSubtarget Class Reference abstract
#include "Target/AMDGPU/AMDGPUSubtarget.h"
Public Types
enum Generation {
R600 = 0 , R700 = 1 , EVERGREEN = 2 , NORTHERN_ISLANDS = 3 ,
SOUTHERN_ISLANDS = 4 , SEA_ISLANDS = 5 , VOLCANIC_ISLANDS = 6 , GFX9 = 7 ,
GFX10 = 8
}
Public Member Functions
AMDGPUSubtarget (const Triple &TT)
std::pair< unsigned, unsigned > getDefaultFlatWorkGroupSize (CallingConv::ID CC) const
std::pair< unsigned, unsigned > getFlatWorkGroupSizes (const Function &F) const
std::pair< unsigned, unsigned > getWavesPerEU (const Function &F) const
unsigned getMaxLocalMemSizeWithWaveCount (unsigned WaveCount, const Function &) const
Return the amount of LDS that can be used that will not restrict the occupancy lower than WaveCount.
unsigned getOccupancyWithLocalMemSize (uint32_t Bytes, const Function &) const
Inverse of getMaxLocalMemWithWaveCount.
unsigned getOccupancyWithLocalMemSize (const MachineFunction &MF) const
bool isAmdHsaOS () const
bool isAmdPalOS () const
bool isMesa3DOS () const
bool isMesaKernel (const Function &F) const
bool isAmdHsaOrMesa (const Function &F) const
bool has16BitInsts () const
bool hasMadMixInsts () const
bool hasFP32Denormals () const
bool hasFPExceptions () const
bool hasSDWA () const
bool hasVOP3PInsts () const
bool hasMulI24 () const
bool hasMulU24 () const
bool hasInv2PiInlineImm () const
bool hasFminFmaxLegacy () const
bool hasTrigReducedRange () const
bool isPromoteAllocaEnabled () const
unsigned getWavefrontSize () const
int getLocalMemorySize () const
unsigned getAlignmentForImplicitArgPtr () const
unsigned getExplicitKernelArgOffset (const Function &F) const
Returns the offset in bytes from the start of the input buffer of the first explicit kernel argument.
virtual unsigned getMaxWorkGroupsPerCU (unsigned FlatWorkGroupSize) const =0
virtual unsigned getMinFlatWorkGroupSize () const =0
virtual unsigned getMaxFlatWorkGroupSize () const =0
virtual unsigned getMaxWavesPerEU (unsigned FlatWorkGroupSize) const =0
virtual unsigned getMinWavesPerEU () const =0
unsigned getMaxWavesPerEU () const
bool makeLIDRangeMetadata (Instruction *I) const
Creates value range metadata on an workitemid.* inrinsic call or load.
unsigned getImplicitArgNumBytes (const Function &F) const
uint64_t getExplicitKernArgSize (const Function &F, unsigned &MaxAlign) const
unsigned getKernArgSegmentSize (const Function &F, unsigned &MaxAlign) const
virtual ~AMDGPUSubtarget ()
Static Public Member Functions
static const AMDGPUSubtarget & get (const MachineFunction &MF)
static const AMDGPUSubtarget & get (const TargetMachine &TM, const Function &F)
Protected Attributes
bool Has16BitInsts
bool HasMadMixInsts
bool FP32Denormals
bool FPExceptions
bool HasSDWA
bool HasVOP3PInsts
bool HasMulI24
bool HasMulU24
bool HasInv2PiInlineImm
bool HasFminFmaxLegacy
bool EnablePromoteAlloca
bool HasTrigReducedRange
int LocalMemorySize
unsigned WavefrontSize
Detailed Description
Definition at line 48 of file AMDGPUSubtarget.h.
Member Enumeration Documentation
Generation
enum llvm::AMDGPUSubtarget::Generation
Enumerator
R600
R700
EVERGREEN
NORTHERN_ISLANDS
SOUTHERN_ISLANDS
SEA_ISLANDS
VOLCANIC_ISLANDS
GFX9
GFX10
Definition at line 50 of file AMDGPUSubtarget.h.
Constructor & Destructor Documentation
AMDGPUSubtarget()
AMDGPUSubtarget::AMDGPUSubtarget (const Triple & TT)
Definition at line 164 of file AMDGPUSubtarget.cpp.
~AMDGPUSubtarget()
virtual llvm::AMDGPUSubtarget::~AMDGPUSubtarget () inline virtual
Definition at line 243 of file AMDGPUSubtarget.h.
Member Function Documentation
get() [1/2]
const AMDGPUSubtarget & AMDGPUSubtarget::get (const MachineFunction & MF) static
Definition at line 885 of file AMDGPUSubtarget.cpp.
References llvm::Triple::amdgcn, llvm::Triple::getArch(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), and llvm::TargetMachine::getTargetTriple().
get() [2/2]
const AMDGPUSubtarget & AMDGPUSubtarget::get (const TargetMachine & TM, const Function & F) static
Definition at line 892 of file AMDGPUSubtarget.cpp.
References llvm::Triple::amdgcn, and F.
getAlignmentForImplicitArgPtr()
unsigned llvm::AMDGPUSubtarget::getAlignmentForImplicitArgPtr () const inline
Definition at line 198 of file AMDGPUSubtarget.h.
References isAmdHsaOS().
Referenced by getKernArgSegmentSize().
getDefaultFlatWorkGroupSize()
std::pair< unsigned, unsigned > AMDGPUSubtarget::getDefaultFlatWorkGroupSize (CallingConv::ID CC) const
Returns
Default range flat work group size for a calling convention.
Definition at line 341 of file AMDGPUSubtarget.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, getWavefrontSize(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by getFlatWorkGroupSizes().
getExplicitKernArgSize()
uint64_t AMDGPUSubtarget::getExplicitKernArgSize (const Function & F, unsigned & MaxAlign) const
Definition at line 491 of file AMDGPUSubtarget.cpp.
References llvm::alignTo(), llvm::CallingConv::AMDGPU_KERNEL, Arg, assert(), F, llvm::DataLayout::getABITypeAlignment(), llvm::DataLayout::getTypeAllocSize(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by getKernArgSegmentSize().
getExplicitKernelArgOffset()
unsigned llvm::AMDGPUSubtarget::getExplicitKernelArgOffset (const Function & F) const inline
Returns the offset in bytes from the start of the input buffer of the first explicit kernel argument.
Definition at line 204 of file AMDGPUSubtarget.h.
References F, and isAmdHsaOrMesa().
Referenced by getKernArgSegmentSize(), and llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
getFlatWorkGroupSizes()
std::pair< unsigned, unsigned > AMDGPUSubtarget::getFlatWorkGroupSizes (const Function & F) const
Returns
Subtarget's default pair of minimum/maximum flat work group sizes for function F, or minimum/maximum flat work group sizes explicitly requested using "amdgpu-flat-work-group-size" attribute attached to function F.
Subtarget's default values if explicitly requested values cannot be converted to integer, or violate subtarget's specifications.
Definition at line 360 of file AMDGPUSubtarget.cpp.
References llvm::Default, F, getDefaultFlatWorkGroupSize(), llvm::AMDGPU::getIntegerPairAttribute(), getMaxFlatWorkGroupSize(), and getMinFlatWorkGroupSize().
Referenced by getMaxLocalMemSizeWithWaveCount(), getOccupancyWithLocalMemSize(), getWavesPerEU(), and makeLIDRangeMetadata().
getImplicitArgNumBytes()
unsigned llvm::AMDGPUSubtarget::getImplicitArgNumBytes (const Function & F) const inline
Returns
Number of bytes of arguments that are passed to a shader or kernel in addition to the explicit ones declared for the function.
Definition at line 233 of file AMDGPUSubtarget.h.
References F, llvm::AMDGPU::getIntegerAttribute(), and isMesaKernel().
Referenced by getKernArgSegmentSize().
getKernArgSegmentSize()
unsigned AMDGPUSubtarget::getKernArgSegmentSize (const Function & F, unsigned & MaxAlign) const
Definition at line 512 of file AMDGPUSubtarget.cpp.
References llvm::alignTo(), F, getAlignmentForImplicitArgPtr(), getExplicitKernArgSize(), getExplicitKernelArgOffset(), and getImplicitArgNumBytes().
getLocalMemorySize()
int llvm::AMDGPUSubtarget::getLocalMemorySize () const inline
Definition at line 194 of file AMDGPUSubtarget.h.
References LocalMemorySize.
Referenced by getMaxLocalMemSizeWithWaveCount(), and getOccupancyWithLocalMemSize().
getMaxFlatWorkGroupSize()
virtual unsigned llvm::AMDGPUSubtarget::getMaxFlatWorkGroupSize () const pure virtual
Returns
Maximum flat work group size supported by the subtarget.
Implemented in llvm::GCNSubtarget, and llvm::R600Subtarget.
Referenced by getFlatWorkGroupSizes().
getMaxLocalMemSizeWithWaveCount()
unsigned AMDGPUSubtarget::getMaxLocalMemSizeWithWaveCount (unsigned WaveCount, const Function & F) const
Return the amount of LDS that can be used that will not restrict the occupancy lower than WaveCount.
Definition at line 308 of file AMDGPUSubtarget.cpp.
References F, getFlatWorkGroupSizes(), getLocalMemorySize(), getMaxWavesPerEU(), and getMaxWorkGroupsPerCU().
getMaxWavesPerEU() [1/2]
unsigned llvm::AMDGPUSubtarget::getMaxWavesPerEU () const inline
Definition at line 226 of file AMDGPUSubtarget.h.
Referenced by getMaxLocalMemSizeWithWaveCount(), getOccupancyWithLocalMemSize(), and getWavesPerEU().
getMaxWavesPerEU() [2/2]
virtual unsigned llvm::AMDGPUSubtarget::getMaxWavesPerEU (unsigned FlatWorkGroupSize) const pure virtual
Returns
Maximum number of waves per execution unit supported by the subtarget and limited by given FlatWorkGroupSize.
Implemented in llvm::GCNSubtarget, and llvm::R600Subtarget.
getMaxWorkGroupsPerCU()
virtual unsigned llvm::AMDGPUSubtarget::getMaxWorkGroupsPerCU (unsigned FlatWorkGroupSize) const pure virtual
Returns
Maximum number of work groups per compute unit supported by the subtarget and limited by given FlatWorkGroupSize.
Implemented in llvm::GCNSubtarget, and llvm::R600Subtarget.
Referenced by getMaxLocalMemSizeWithWaveCount(), and getOccupancyWithLocalMemSize().
getMinFlatWorkGroupSize()
virtual unsigned llvm::AMDGPUSubtarget::getMinFlatWorkGroupSize () const pure virtual
Returns
Minimum flat work group size supported by the subtarget.
Implemented in llvm::GCNSubtarget, and llvm::R600Subtarget.
Referenced by getFlatWorkGroupSizes().
getMinWavesPerEU()
virtual unsigned llvm::AMDGPUSubtarget::getMinWavesPerEU () const pure virtual
Returns
Minimum number of waves per execution unit supported by the subtarget.
Implemented in llvm::GCNSubtarget, and llvm::R600Subtarget.
Referenced by getWavesPerEU().
getOccupancyWithLocalMemSize() [1/2]
unsigned AMDGPUSubtarget::getOccupancyWithLocalMemSize (const MachineFunction & MF) const
Definition at line 335 of file AMDGPUSubtarget.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), and getOccupancyWithLocalMemSize().
getOccupancyWithLocalMemSize() [2/2]
unsigned AMDGPUSubtarget::getOccupancyWithLocalMemSize (uint32_t Bytes, const Function & F) const
Inverse of getMaxLocalMemWithWaveCount.
Return the maximum wavecount if the given LDS memory size is the only constraint.
Definition at line 320 of file AMDGPUSubtarget.cpp.
References F, getFlatWorkGroupSizes(), getLocalMemorySize(), getMaxWavesPerEU(), and getMaxWorkGroupsPerCU().
Referenced by getOccupancyWithLocalMemSize().
getWavefrontSize()
unsigned llvm::AMDGPUSubtarget::getWavefrontSize () const inline
Definition at line 190 of file AMDGPUSubtarget.h.
References WavefrontSize.
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter(), getDefaultFlatWorkGroupSize(), llvm::SIInstrInfo::getScratchRsrcWords23(), lowerFCMPIntrinsic(), and lowerICMPIntrinsic().
getWavesPerEU()
std::pair< unsigned, unsigned > AMDGPUSubtarget::getWavesPerEU (const Function & F) const
Returns
Subtarget's default pair of minimum/maximum number of waves per execution unit for function F, or minimum/maximum number of waves per execution unit explicitly requested using "amdgpu-waves-per-eu" attribute attached to function F.
Subtarget's default values if explicitly requested values cannot be converted to integer, violate subtarget's specifications, or are not compatible with minimum/maximum number of waves limited by flat work group size, register usage, and/or lds usage.
Definition at line 384 of file AMDGPUSubtarget.cpp.
References llvm::Default, F, getFlatWorkGroupSizes(), llvm::AMDGPU::getIntegerPairAttribute(), getMaxWavesPerEU(), and getMinWavesPerEU().
has16BitInsts()
bool llvm::AMDGPUSubtarget::has16BitInsts () const inline
Definition at line 142 of file AMDGPUSubtarget.h.
References Has16BitInsts.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::SITargetLowering::getNumRegistersForCallingConv(), llvm::SITargetLowering::getRegisterTypeForCallingConv(), llvm::GCNTTIImpl::getVectorInstrCost(), llvm::SITargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::AMDGPUTargetLowering::isFPImmLegal(), llvm::SIInstrInfo::isInlineConstant(), llvm::AMDGPUTargetLowering::isTruncateFree(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::AMDGPUTargetLowering::isZExtFree(), llvm::AMDGPUTargetLowering::LowerFP_TO_SINT(), llvm::AMDGPUTargetLowering::LowerFP_TO_UINT(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), llvm::AMDGPUTargetLowering::performFAbsCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), and llvm::SITargetLowering::SITargetLowering().
hasFminFmaxLegacy()
bool llvm::AMDGPUSubtarget::hasFminFmaxLegacy () const inline
Definition at line 178 of file AMDGPUSubtarget.h.
References HasFminFmaxLegacy.
Referenced by llvm::AMDGPUTargetLowering::performSelectCombine().
hasFP32Denormals()
bool llvm::AMDGPUSubtarget::hasFP32Denormals () const inline
Definition at line 150 of file AMDGPUSubtarget.h.
References FP32Denormals.
Referenced by llvm::SITargetLowering::denormalsEnabledForType(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SITargetLowering::isFPExtFoldable(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::R600TargetLowering::R600TargetLowering(), and llvm::SITargetLowering::SITargetLowering().
hasFPExceptions()
bool llvm::AMDGPUSubtarget::hasFPExceptions () const inline
Definition at line 154 of file AMDGPUSubtarget.h.
References FPExceptions.
hasInv2PiInlineImm()
bool llvm::AMDGPUSubtarget::hasInv2PiInlineImm () const inline
Definition at line 174 of file AMDGPUSubtarget.h.
References HasInv2PiInlineImm.
Referenced by llvm::AMDGPUTargetLowering::isConstantCostlierToNegate(), and llvm::SIInstrInfo::isInlineConstant().
hasMadMixInsts()
bool llvm::AMDGPUSubtarget::hasMadMixInsts () const inline
Definition at line 146 of file AMDGPUSubtarget.h.
References HasMadMixInsts.
Referenced by llvm::SITargetLowering::isFPExtFoldable().
hasMulI24()
bool llvm::AMDGPUSubtarget::hasMulI24 () const inline
Definition at line 166 of file AMDGPUSubtarget.h.
References HasMulI24.
Referenced by llvm::AMDGPUTargetLowering::performMulCombine(), and llvm::AMDGPUTargetLowering::performMulhsCombine().
hasMulU24()
bool llvm::AMDGPUSubtarget::hasMulU24 () const inline
Definition at line 170 of file AMDGPUSubtarget.h.
References HasMulU24.
Referenced by llvm::AMDGPUTargetLowering::performMulCombine(), and llvm::AMDGPUTargetLowering::performMulhuCombine().
hasSDWA()
bool llvm::AMDGPUSubtarget::hasSDWA () const inline
Definition at line 158 of file AMDGPUSubtarget.h.
References HasSDWA.
Referenced by llvm::AMDGPUTargetLowering::PerformDAGCombine(), and llvm::SIInstrInfo::verifyInstruction().
hasTrigReducedRange()
bool llvm::AMDGPUSubtarget::hasTrigReducedRange () const inline
Definition at line 182 of file AMDGPUSubtarget.h.
References HasTrigReducedRange.
hasVOP3PInsts()
bool llvm::AMDGPUSubtarget::hasVOP3PInsts () const inline
Definition at line 162 of file AMDGPUSubtarget.h.
References HasVOP3PInsts.
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::GCNTTIImpl::getArithmeticReductionCost(), llvm::GCNTTIImpl::getMinMaxReductionCost(), llvm::GCNTTIImpl::getShuffleCost(), llvm::AMDGPUTargetLowering::isFNegFree(), and llvm::SITargetLowering::SITargetLowering().
isAmdHsaOrMesa()
bool llvm::AMDGPUSubtarget::isAmdHsaOrMesa (const Function & F) const inline
Definition at line 138 of file AMDGPUSubtarget.h.
References F, isAmdHsaOS(), and isMesaKernel().
Referenced by llvm::AMDGPUAsmPrinter::EmitFunctionBodyStart(), and getExplicitKernelArgOffset().
isAmdHsaOS()
bool llvm::AMDGPUSubtarget::isAmdHsaOS () const inline
Definition at line 122 of file AMDGPUSubtarget.h.
References llvm::Triple::AMDHSA, and llvm::Triple::getOS().
Referenced by llvm::AMDGPUAsmPrinter::EmitFunctionBodyStart(), getAlignmentForImplicitArgPtr(), llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::GCNSubtarget::getTrapHandlerAbi(), llvm::GCNSubtarget::hasCodeObjectV3(), llvm::GCNSubtarget::initializeSubtargetDependencies(), isAmdHsaOrMesa(), llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
isAmdPalOS()
bool llvm::AMDGPUSubtarget::isAmdPalOS () const inline
Definition at line 126 of file AMDGPUSubtarget.h.
References llvm::Triple::AMDPAL, and llvm::Triple::getOS().
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
isMesa3DOS()
bool llvm::AMDGPUSubtarget::isMesa3DOS () const inline
Definition at line 130 of file AMDGPUSubtarget.h.
References llvm::Triple::getOS(), and llvm::Triple::Mesa3D.
Referenced by llvm::GCNSubtarget::isMesaGfxShader(), and isMesaKernel().
isMesaKernel()
bool llvm::AMDGPUSubtarget::isMesaKernel (const Function & F) const inline
Definition at line 134 of file AMDGPUSubtarget.h.
References F, isMesa3DOS(), and llvm::AMDGPU::isShader().
Referenced by getImplicitArgNumBytes(), and isAmdHsaOrMesa().
isPromoteAllocaEnabled()
bool llvm::AMDGPUSubtarget::isPromoteAllocaEnabled () const inline
Definition at line 186 of file AMDGPUSubtarget.h.
References EnablePromoteAlloca.
makeLIDRangeMetadata()
bool AMDGPUSubtarget::makeLIDRangeMetadata (Instruction * I) const
Creates value range metadata on an workitemid.* inrinsic call or load.
Definition at line 429 of file AMDGPUSubtarget.cpp.
References llvm::MDBuilder::createRange(), F, getFlatWorkGroupSizes(), I, if(), LLVM_FALLTHROUGH, and llvm::LLVMContext::MD_range.
Member Data Documentation
EnablePromoteAlloca
bool llvm::AMDGPUSubtarget::EnablePromoteAlloca protected
Definition at line 76 of file AMDGPUSubtarget.h.
Referenced by isPromoteAllocaEnabled().
FP32Denormals
bool llvm::AMDGPUSubtarget::FP32Denormals protected
Definition at line 68 of file AMDGPUSubtarget.h.
Referenced by hasFP32Denormals(), and llvm::R600Subtarget::initializeSubtargetDependencies().
FPExceptions
bool llvm::AMDGPUSubtarget::FPExceptions protected
Definition at line 69 of file AMDGPUSubtarget.h.
Referenced by hasFPExceptions().
Has16BitInsts
bool llvm::AMDGPUSubtarget::Has16BitInsts protected
Definition at line 66 of file AMDGPUSubtarget.h.
Referenced by has16BitInsts().
HasFminFmaxLegacy
bool llvm::AMDGPUSubtarget::HasFminFmaxLegacy protected
Definition at line 75 of file AMDGPUSubtarget.h.
Referenced by hasFminFmaxLegacy(), and llvm::GCNSubtarget::initializeSubtargetDependencies().
HasInv2PiInlineImm
bool llvm::AMDGPUSubtarget::HasInv2PiInlineImm protected
Definition at line 74 of file AMDGPUSubtarget.h.
Referenced by hasInv2PiInlineImm().
HasMadMixInsts
bool llvm::AMDGPUSubtarget::HasMadMixInsts protected
Definition at line 67 of file AMDGPUSubtarget.h.
Referenced by hasMadMixInsts().
HasMulI24
bool llvm::AMDGPUSubtarget::HasMulI24 protected
Definition at line 72 of file AMDGPUSubtarget.h.
Referenced by hasMulI24(), and llvm::R600Subtarget::initializeSubtargetDependencies().
HasMulU24
bool llvm::AMDGPUSubtarget::HasMulU24 protected
Definition at line 73 of file AMDGPUSubtarget.h.
Referenced by hasMulU24(), and llvm::R600Subtarget::initializeSubtargetDependencies().
HasSDWA
bool llvm::AMDGPUSubtarget::HasSDWA protected
Definition at line 70 of file AMDGPUSubtarget.h.
Referenced by hasSDWA().
HasTrigReducedRange
bool llvm::AMDGPUSubtarget::HasTrigReducedRange protected
Definition at line 77 of file AMDGPUSubtarget.h.
Referenced by hasTrigReducedRange().
HasVOP3PInsts
bool llvm::AMDGPUSubtarget::HasVOP3PInsts protected
Definition at line 71 of file AMDGPUSubtarget.h.
Referenced by hasVOP3PInsts().
LocalMemorySize
int llvm::AMDGPUSubtarget::LocalMemorySize protected
Definition at line 78 of file AMDGPUSubtarget.h.
Referenced by getLocalMemorySize(), and llvm::GCNSubtarget::initializeSubtargetDependencies().
WavefrontSize
unsigned llvm::AMDGPUSubtarget::WavefrontSize protected
Definition at line 79 of file AMDGPUSubtarget.h.
Referenced by getWavefrontSize(), llvm::GCNSubtarget::getWavefrontSizeLog2(), llvm::GCNSubtarget::initializeSubtargetDependencies(), and llvm::GCNSubtarget::isWave32().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUSubtarget.h
lib/Target/AMDGPU/AMDGPUSubtarget.cpp