LLVM: llvm::AMDGPULegalizerInfo Class Reference
llvm::AMDGPULegalizerInfo Class Reference
This class provides the information for the target register banks.
#include "Target/AMDGPU/AMDGPULegalizerInfo.h"
Public Member Functions
AMDGPULegalizerInfo (const GCNSubtarget &ST, const GCNTargetMachine &TM)
bool legalizeCustom (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder, GISelChangeObserver &Observer) const override
Register getSegmentAperture (unsigned AddrSpace, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeAddrSpaceCast (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeFrint (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeFceil (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeIntrinsicTrunc (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeITOFP (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder, bool Signed) const
bool legalizeMinNumMaxNum (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeExtractVectorElt (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
bool legalizeInsertVectorElt (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
Register getLiveInRegister (MachineRegisterInfo &MRI, Register Reg, LLT Ty) const
bool loadInputValue (Register DstReg, MachineIRBuilder &B, const ArgDescriptor *Arg) const
bool legalizePreloadedArgIntrin (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B, AMDGPUFunctionArgInfo::PreloadedValue ArgType) const
bool legalizeImplicitArgPtr (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &B) const
bool legalizeIntrinsic (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const override
Return true if MI is either legal or has been legalized and false if not legal.
Public Member Functions inherited from llvm::LegalizerInfo
LegalizerInfo ()
virtual ~LegalizerInfo ()=default
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void computeTables ()
Compute any ancillary tables needed to quickly decide how an operation should be handled.
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
void setAction (const InstrAspect &Aspect, LegalizeAction Action)
More friendly way to set an action for common types that have an LLT representation.
void setLegalizeScalarToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
The setAction calls record the non-size-changing legalization actions to take on specificly-sized types.
void setLegalizeVectorElementToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
See also setLegalizeScalarToDifferentSizeStrategy.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeCustom (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder, GISelChangeObserver &Observer) const
virtual bool legalizeIntrinsic (MachineInstr &MI, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder) const
Return true if MI is either legal or has been legalized and false if not legal.
Additional Inherited Members
Public Types inherited from llvm::LegalizerInfo
using SizeAndAction = std::pair< uint16_t, LegalizeAction >
using SizeAndActionsVec = std::vector< SizeAndAction >
using SizeChangeStrategy = std::function< SizeAndActionsVec(const SizeAndActionsVec &v)>
Static Public Member Functions inherited from llvm::LegalizerInfo
static bool needsLegalizingToDifferentSize (const LegalizeAction Action)
static SizeAndActionsVec unsupportedForDifferentSizes (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of only supporting a specific set of type sizes.
static SizeAndActionsVec widenToLargerTypesAndNarrowToLargest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of widening the type to a large legal type, unless there is no such type and then instead it should be narrowed to the largest legal type.
static SizeAndActionsVec widenToLargerTypesUnsupportedOtherwise (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndUnsupportedIfTooSmall (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndWidenToSmallest (const SizeAndActionsVec &v)
static SizeAndActionsVec moreToWiderTypesAndLessToWidest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular vector operation consists of having more elements in the vector, to a type that is legal.
static SizeAndActionsVec increaseToLargerTypesAndDecreaseToLargest (const SizeAndActionsVec &v, LegalizeAction IncreaseAction, LegalizeAction DecreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
static SizeAndActionsVec decreaseToSmallerTypesAndIncreaseToSmallest (const SizeAndActionsVec &v, LegalizeAction DecreaseAction, LegalizeAction IncreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
Detailed Description
This class provides the information for the target register banks.
Definition at line 27 of file AMDGPULegalizerInfo.h.
Constructor & Destructor Documentation
AMDGPULegalizerInfo()
AMDGPULegalizerInfo::AMDGPULegalizerInfo (const GCNSubtarget & ST, const GCNTargetMachine & TM)
Definition at line 101 of file AMDGPULegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampNumElements(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizeRuleSet::clampScalarOrElt(), llvm::LegalizerInfo::computeTables(), AMDGPUAS::CONSTANT_ADDRESS, llvm::LegalizeRuleSet::custom(), llvm::LegalizeRuleSet::customFor(), llvm::LegalizeRuleSet::customIf(), llvm::LegalizeRuleSet::fewerElementsIf(), fewerEltsToSize64Vector(), AMDGPUAS::FLAT_ADDRESS, llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LLT::getElementType(), llvm::GCNSubtarget::getGeneration(), llvm::GCNSubtarget::getInstrInfo(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPUSubtarget::has16BitInsts(), llvm::GCNSubtarget::hasDwordx3LoadStores(), llvm::GCNSubtarget::hasFlatAddressSpace(), llvm::AMDGPUSubtarget::hasVOP3PInsts(), isMultiple32(), llvm::LegalityPredicates::isPointer(), llvm::isPowerOf2_32(), isRegisterType(), isSmallOddVector(), llvm::LLT::isVector(), llvm::LegalizeActions::Legal, llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalForTypesWithMemDesc(), llvm::LegalizeRuleSet::legalIf(), AMDGPUAS::LOCAL_ADDRESS, llvm::Log2_32_Ceil(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::minScalarOrElt(), llvm::LegalizeRuleSet::minScalarSameAs(), llvm::LegalityQuery::MMODescrs, llvm::LegalizeRuleSet::moreElementsIf(), numElementsNotEven(), oneMoreElement(), AMDGPUAS::PRIVATE_ADDRESS, llvm::LegalityPredicates::sameSize(), llvm::LLT::scalar(), llvm::LegalizeMutations::scalarize(), llvm::LegalizeRuleSet::scalarize(), llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::LegalizerInfo::setAction(), Size, llvm::LegalityPredicates::typeIs(), llvm::LegalityQuery::Types, llvm::LegalizeRuleSet::unsupportedIf(), llvm::LegalizeRuleSet::unsupportedIfMemSizeNotPow2(), vectorWiderThan(), verify, llvm::LegalizeRuleSet::widenScalarIf(), llvm::LegalizeMutations::widenScalarOrEltToNextPow2(), and llvm::LegalizeRuleSet::widenScalarToNextPow2().
Member Function Documentation
getLiveInRegister()
Register AMDGPULegalizerInfo::getLiveInRegister (MachineRegisterInfo & MRI, Register Reg, LLT Ty) const
Definition at line 1202 of file AMDGPULegalizerInfo.cpp.
References MRI.
Referenced by loadInputValue().
getSegmentAperture()
Register AMDGPULegalizerInfo::getSegmentAperture (unsigned AddrSpace, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 807 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLoad(), AMDGPUAS::CONSTANT_ADDRESS, llvm::IntervalMapImpl::NodeRef::get(), llvm::MachineFunction::getFunction(), llvm::IRBuilderBase::getInt8Ty(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPU::Hwreg::ID_MEM_BASES, llvm::AMDGPU::Hwreg::ID_SHIFT_, AMDGPUAS::LOCAL_ADDRESS, llvm::MachineIRBuilder::materializeGEP(), llvm::MinAlign(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::MachineMemOperand::MOLoad, MRI, llvm::AMDGPU::Hwreg::OFFSET_SHIFT_, llvm::AMDGPU::Hwreg::OFFSET_SRC_PRIVATE_BASE, llvm::AMDGPU::Hwreg::OFFSET_SRC_SHARED_BASE, llvm::LLT::scalar(), llvm::AMDGPU::Hwreg::WIDTH_M1_SHIFT_, llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_PRIVATE_BASE, and llvm::AMDGPU::Hwreg::WIDTH_M1_SRC_SHARED_BASE.
Referenced by legalizeAddrSpaceCast().
legalizeAddrSpaceCast()
bool AMDGPULegalizerInfo::legalizeAddrSpaceCast (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 878 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildExtract(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildSelect(), AMDGPUAS::FLAT_ADDRESS, llvm::MCInstrInfo::get(), llvm::LLT::getAddressSpace(), llvm::MachineIRBuilder::getMF(), getSegmentAperture(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineIRBuilder::getTII(), llvm::CmpInst::ICMP_NE, llvm::LLT::isVector(), AMDGPUAS::LOCAL_ADDRESS, MI, MRI, AMDGPUAS::PRIVATE_ADDRESS, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeCustom()
bool AMDGPULegalizerInfo::legalizeCustom (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder, GISelChangeObserver & Observer) const override virtual
Reimplemented from llvm::LegalizerInfo.
Definition at line 774 of file AMDGPULegalizerInfo.cpp.
References legalizeAddrSpaceCast(), legalizeExtractVectorElt(), legalizeFceil(), legalizeFrint(), legalizeInsertVectorElt(), legalizeIntrinsicTrunc(), legalizeITOFP(), legalizeMinNumMaxNum(), llvm_unreachable, MI, and MRI.
legalizeExtractVectorElt()
bool AMDGPULegalizerInfo::legalizeExtractVectorElt (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 1131 of file AMDGPULegalizerInfo.cpp.
References assert(), B, llvm::getConstantVRegVal(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::Optional< T >::getValue(), MI, and MRI.
Referenced by legalizeCustom().
legalizeFceil()
bool AMDGPULegalizerInfo::legalizeFceil (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 984 of file AMDGPULegalizerInfo.cpp.
References assert(), B, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_ONE, MI, MRI, and llvm::LLT::scalar().
Referenced by legalizeCustom().
legalizeFrint()
bool AMDGPULegalizerInfo::legalizeFrint (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 957 of file AMDGPULegalizerInfo.cpp.
References assert(), llvm::MachineIRBuilder::buildFAbs(), llvm::MachineIRBuilder::buildFAdd(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFCopysign(), llvm::MachineIRBuilder::buildFSub(), llvm::MachineIRBuilder::buildSelect(), llvm::CmpInst::FCMP_OGT, llvm::LLT::getSizeInBits(), llvm::APFloatBase::IEEEdouble(), llvm::LLT::isScalar(), MI, MRI, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstr().
Referenced by legalizeCustom().
legalizeImplicitArgPtr()
bool AMDGPULegalizerInfo::legalizeImplicitArgPtr (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B) const
Definition at line 1275 of file AMDGPULegalizerInfo.cpp.
References Arg, B, llvm::AMDGPUTargetLowering::FIRST_IMPLICIT, llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), llvm::SIMachineFunctionInfo::getPreloadedValue(), llvm::LLT::getSizeInBits(), llvm::GCNSubtarget::getTargetLowering(), llvm::AMDGPUFunctionArgInfo::IMPLICIT_ARG_PTR, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, legalizePreloadedArgIntrin(), loadInputValue(), MI, MRI, and llvm::LLT::scalar().
Referenced by legalizeIntrinsic().
legalizeInsertVectorElt()
bool AMDGPULegalizerInfo::legalizeInsertVectorElt (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 1160 of file AMDGPULegalizerInfo.cpp.
References assert(), B, llvm::getConstantVRegVal(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::Optional< T >::getValue(), MI, and MRI.
Referenced by legalizeCustom().
legalizeIntrinsic()
bool AMDGPULegalizerInfo::legalizeIntrinsic (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const override virtual
Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 1309 of file AMDGPULegalizerInfo.cpp.
References B, llvm::AMDGPUFunctionArgInfo::DISPATCH_ID, llvm::AMDGPUFunctionArgInfo::DISPATCH_PTR, llvm::AMDGPUFunctionArgInfo::IMPLICIT_BUFFER_PTR, llvm::AMDGPUFunctionArgInfo::KERNARG_SEGMENT_PTR, legalizeImplicitArgPtr(), legalizePreloadedArgIntrin(), MI, MRI, llvm::AMDGPUFunctionArgInfo::QUEUE_PTR, TRI, verifyCFIntrinsic(), llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_X, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Y, llvm::AMDGPUFunctionArgInfo::WORKGROUP_ID_Z, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_X, llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Y, and llvm::AMDGPUFunctionArgInfo::WORKITEM_ID_Z.
legalizeIntrinsicTrunc()
bool AMDGPULegalizerInfo::legalizeIntrinsicTrunc (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 1029 of file AMDGPULegalizerInfo.cpp.
References assert(), B, extractF64Exponent(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, MI, MRI, and llvm::LLT::scalar().
Referenced by legalizeCustom().
legalizeITOFP()
bool AMDGPULegalizerInfo::legalizeITOFP (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder, bool Signed) const
Definition at line 1075 of file AMDGPULegalizerInfo.cpp.
References assert(), B, MI, MRI, llvm::LLT::scalar(), and Signed.
Referenced by legalizeCustom().
legalizeMinNumMaxNum()
bool AMDGPULegalizerInfo::legalizeMinNumMaxNum (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder) const
Definition at line 1107 of file AMDGPULegalizerInfo.cpp.
References B, llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getMode(), llvm::AMDGPU::SIModeRegisterDefaults::IEEE, llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::lowerFMinNumMaxNum(), MI, and llvm::MachineIRBuilder::setMBB().
Referenced by legalizeCustom().
legalizePreloadedArgIntrin()
bool AMDGPULegalizerInfo::legalizePreloadedArgIntrin (MachineInstr & MI, MachineRegisterInfo & MRI, MachineIRBuilder & B, AMDGPUFunctionArgInfo::PreloadedValue ArgType) const
Definition at line 1250 of file AMDGPULegalizerInfo.cpp.
References Arg, B, llvm::dbgs(), llvm::SIMachineFunctionInfo::getPreloadedValue(), LLVM_DEBUG, loadInputValue(), and MI.
Referenced by legalizeImplicitArgPtr(), and legalizeIntrinsic().
loadInputValue()
bool AMDGPULegalizerInfo::loadInputValue (Register DstReg, MachineIRBuilder & B, const ArgDescriptor * Arg) const
Definition at line 1213 of file AMDGPULegalizerInfo.cpp.
References llvm::MachineBasicBlock::addLiveIn(), Arg, assert(), B, llvm::MachineBasicBlock::begin(), getLiveInRegister(), MRI, and llvm::LLT::scalar().
Referenced by legalizeImplicitArgPtr(), and legalizePreloadedArgIntrin().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPULegalizerInfo.h
lib/Target/AMDGPU/AMDGPULegalizerInfo.cpp