LLVM: llvm::DbgVariable Class Reference
llvm::DbgVariable Class Reference
This class is used to track local variable information.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Member Functions
DbgVariable (const DILocalVariable *V, const DILocation *IA)
Frame index + expression.
void initializeMMI (const DIExpression *E, int FI)
Initialize from the MMI table.
void initializeDbgValue (DbgValueLoc Value)
void initializeDbgValue (const MachineInstr *DbgValue)
Initialize from a DBG_VALUE instruction.
const DILocalVariable * getVariable () const
const DIExpression * getSingleExpression () const
void setDebugLocListIndex (unsigned O)
unsigned getDebugLocListIndex () const
StringRef getName () const
const DbgValueLoc * getValueLoc () const
ArrayRef< FrameIndexExpr > getFrameIndexExprs () const
Get the FI entries, sorted by fragment offset.
bool hasFrameIndexExprs () const
void addMMIEntry (const DbgVariable &V)
dwarf::Tag getTag () const
bool isArtificial () const
Return true if DbgVariable is artificial.
bool isObjectPointer () const
bool hasComplexAddress () const
bool isBlockByrefVariable () const
const DIType * getType () const
Public Member Functions inherited from llvm::DbgEntity
DbgEntity (const DINode *N, const DILocation *IA, unsigned ID)
virtual ~DbgEntity ()
void setDIE (DIE &D)
const DINode * getEntity () const
Accessors.
const DILocation * getInlinedAt () const
DIE * getDIE () const
unsigned getDbgEntityID () const
Static Public Member Functions
static bool classof (const DbgEntity *N)
Static Public Member Functions inherited from llvm::DbgEntity
static bool classof (const DbgEntity *N)
Additional Inherited Members
Public Types inherited from llvm::DbgEntity
enum DbgEntityKind { DbgVariableKind , DbgLabelKind }
Detailed Description
This class is used to track local variable information.
Variables can be created from allocas, in which case they're generated from the MMI table. Such variables can have multiple expressions and frame indices.
Variables can be created from DBG_VALUE instructions. Those whose location changes over time use DebugLocListIndex, while those with a single location use ValueLoc and (optionally) a single entry of Expr.
Variables that have been optimized out use none of these fields.
Definition at line 118 of file DwarfDebug.h.
Constructor & Destructor Documentation
DbgVariable()
llvm::DbgVariable::DbgVariable (const DILocalVariable * V, const DILocation * IA) inline
Frame index + expression.
Construct a DbgVariable.
Creates a variable without any DW_AT_location. Call initializeMMI() for MMI entries, or initializeDbgValue() for DBG_VALUE instructions.
Definition at line 136 of file DwarfDebug.h.
Member Function Documentation
addMMIEntry()
void DbgVariable::addMMIEntry (const DbgVariable & V)
Definition at line 302 of file DwarfDebug.cpp.
References llvm::all_of(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::DbgEntity::getInlinedAt(), getVariable(), llvm::none_of(), Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfFile::addScopeVariable().
classof()
static bool llvm::DbgVariable::classof (const DbgEntity * N) inline static
Definition at line 222 of file DwarfDebug.h.
References llvm::DbgEntity::DbgVariableKind, and N.
getDebugLocListIndex()
unsigned llvm::DbgVariable::getDebugLocListIndex () const inline
Definition at line 176 of file DwarfDebug.h.
getFrameIndexExprs()
ArrayRef< DbgVariable::FrameIndexExpr > DbgVariable::getFrameIndexExprs () const
Get the FI entries, sorted by fragment offset.
Definition at line 284 of file DwarfDebug.cpp.
References A, llvm::all_of(), assert(), B, llvm::SmallVectorBase::size(), and llvm::sort().
getName()
StringRef llvm::DbgVariable::getName () const inline
Definition at line 177 of file DwarfDebug.h.
References llvm::DIVariable::getName(), and getVariable().
Referenced by llvm::DwarfCompileUnit::applyVariableAttributes(), and getType().
getSingleExpression()
const DIExpression * llvm::DbgVariable::getSingleExpression () const inline
Definition at line 170 of file DwarfDebug.h.
References assert(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfCompileUnit::addComplexAddress().
getTag()
dwarf::Tag llvm::DbgVariable::getTag () const inline
Definition at line 185 of file DwarfDebug.h.
References getVariable().
getType()
const DIType * DbgVariable::getType () const
Definition at line 202 of file DwarfDebug.cpp.
References getName(), llvm::DINode::getTag(), llvm::DIVariable::getType(), getVariable(), llvm::DIType::isBlockByrefStruct(), and N.
Referenced by llvm::DwarfCompileUnit::applyVariableAttributes(), dependencies(), isArtificial(), and isObjectPointer().
getValueLoc()
const DbgValueLoc * llvm::DbgVariable::getValueLoc () const inline
Definition at line 178 of file DwarfDebug.h.
getVariable()
const DILocalVariable * llvm::DbgVariable::getVariable () const inline
Definition at line 166 of file DwarfDebug.h.
References llvm::DbgEntity::getEntity().
Referenced by addMMIEntry(), llvm::DwarfFile::addScopeVariable(), llvm::DwarfCompileUnit::applyVariableAttributes(), getName(), getTag(), getType(), initializeDbgValue(), isArtificial(), isBlockByrefVariable(), and isObjectPointer().
hasComplexAddress()
bool llvm::DbgVariable::hasComplexAddress () const inline
Definition at line 210 of file DwarfDebug.h.
References assert(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorBase::size().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
hasFrameIndexExprs()
bool llvm::DbgVariable::hasFrameIndexExprs () const inline
Definition at line 181 of file DwarfDebug.h.
References llvm::SmallVectorBase::empty().
initializeDbgValue() [1/2]
void DbgVariable::initializeDbgValue (const MachineInstr * DbgValue)
Initialize from a DBG_VALUE instruction.
Definition at line 270 of file DwarfDebug.cpp.
References assert(), E, llvm::SmallVectorBase::empty(), llvm::MachineInstr::getDebugExpression(), llvm::MachineInstr::getDebugLoc(), getDebugLocValue(), llvm::MachineInstr::getDebugVariable(), llvm::DbgEntity::getInlinedAt(), getVariable(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
initializeDbgValue() [2/2]
void llvm::DbgVariable::initializeDbgValue (DbgValueLoc Value) inline
Definition at line 151 of file DwarfDebug.h.
References assert(), E, llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::DebugLocStream::ListBuilder::~ListBuilder().
initializeMMI()
void llvm::DbgVariable::initializeMMI (const DIExpression * E, int FI) inline
Initialize from the MMI table.
Definition at line 140 of file DwarfDebug.h.
References assert(), E, llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
isArtificial()
bool llvm::DbgVariable::isArtificial () const inline
Return true if DbgVariable is artificial.
Definition at line 194 of file DwarfDebug.h.
References getType(), getVariable(), and isArtificial().
Referenced by llvm::DwarfCompileUnit::applyVariableAttributes(), and isArtificial().
isBlockByrefVariable()
bool DbgVariable::isBlockByrefVariable () const
Definition at line 197 of file DwarfDebug.cpp.
References assert(), llvm::DIVariable::getType(), getVariable(), and llvm::DIType::isBlockByrefStruct().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
isObjectPointer()
bool llvm::DbgVariable::isObjectPointer () const inline
Definition at line 202 of file DwarfDebug.h.
References getType(), getVariable(), and isObjectPointer().
Referenced by llvm::DwarfCompileUnit::constructVariableDIE(), and isObjectPointer().
setDebugLocListIndex()
void llvm::DbgVariable::setDebugLocListIndex (unsigned O) inline
Definition at line 175 of file DwarfDebug.h.
Referenced by llvm::DebugLocStream::ListBuilder::~ListBuilder().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfDebug.h
lib/CodeGen/AsmPrinter/DwarfDebug.cpp