LLVM: llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT > Class Template Reference
llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT > Class Template Reference
#include "llvm/Analysis/DOTGraphTraitsPass.h"
Public Member Functions
DOTGraphTraitsViewer (StringRef GraphName, char &ID)
virtual bool processFunction (Function &F, AnalysisT &Analysis)
Return true if this function should be processed.
bool runOnFunction (Function &F) override
void getAnalysisUsage (AnalysisUsage &AU) const override
Detailed Description
template<typename AnalysisT, bool IsSimple, typename GraphT = AnalysisT *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<AnalysisT, GraphT>>
class llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >
Definition at line 33 of file DOTGraphTraitsPass.h.
Constructor & Destructor Documentation
DOTGraphTraitsViewer()
template<typename AnalysisT , bool IsSimple, typename GraphT = AnalysisT *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<AnalysisT, GraphT>> llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsViewer (StringRef GraphName, char & ID) inline
Definition at line 35 of file DOTGraphTraitsPass.h.
Member Function Documentation
getAnalysisUsage()
template<typename AnalysisT , bool IsSimple, typename GraphT = AnalysisT *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<AnalysisT, GraphT>> void llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::getAnalysisUsage (AnalysisUsage & AU) const inline override
Definition at line 63 of file DOTGraphTraitsPass.h.
processFunction()
template<typename AnalysisT , bool IsSimple, typename GraphT = AnalysisT *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<AnalysisT, GraphT>> virtual bool llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::processFunction (Function & F, AnalysisT & Analysis) inline virtual
Return true if this function should be processed.
An implementation of this class my override this function to indicate that only certain functions should be viewed.
Parameters
Analysis The current analysis result for this function.
Definition at line 44 of file DOTGraphTraitsPass.h.
Referenced by llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction().
runOnFunction()
template<typename AnalysisT , bool IsSimple, typename GraphT = AnalysisT *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<AnalysisT, GraphT>> bool llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction (Function & F) inline override
Definition at line 48 of file DOTGraphTraitsPass.h.
References Analysis, F, llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getGraphName(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::processFunction(), and ViewGraph().
The documentation for this class was generated from the following file:
include/llvm/Analysis/DOTGraphTraitsPass.h