LLVM: llvm::FileCheckStringSubstitution Class Reference
llvm::FileCheckStringSubstitution Class Reference
#include "llvm/Support/FileCheck.h"
Public Member Functions
FileCheckStringSubstitution (FileCheckPatternContext *Context, StringRef VarName, size_t InsertIdx)
Expected< std::string > getResult () const override
Public Member Functions inherited from llvm::FileCheckSubstitution
FileCheckSubstitution (FileCheckPatternContext *Context, StringRef VarName, size_t InsertIdx)
virtual ~FileCheckSubstitution ()=default
StringRef getFromString () const
size_t getIndex () const
virtual Expected< std::string > getResult () const =0
Additional Inherited Members
Protected Attributes inherited from llvm::FileCheckSubstitution
FileCheckPatternContext * Context
Pointer to a class instance holding, among other things, the table with the values of live string variables at the start of any given CHECK line.
StringRef FromStr
The string that needs to be substituted for something else.
size_t InsertIdx
Detailed Description
Definition at line 219 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheckStringSubstitution()
llvm::FileCheckStringSubstitution::FileCheckStringSubstitution (FileCheckPatternContext * Context, StringRef VarName, size_t InsertIdx) inline
Definition at line 221 of file FileCheck.h.
Member Function Documentation
getResult()
Expected< std::string > FileCheckStringSubstitution::getResult () const override virtual
Returns
the text that the string variable in this substitution matched when defined, or an error if the variable is undefined.
Implements llvm::FileCheckSubstitution.
Definition at line 70 of file FileCheck.cpp.
References llvm::FileCheckSubstitution::Context, llvm::Regex::escape(), llvm::FileCheckSubstitution::FromStr, llvm::FileCheckPatternContext::getPatternVarValue(), and llvm::Expected< T >::takeError().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp