LLVM: llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
#include "llvm/ADT/DenseMap.h"
Inherits llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >.
Public Member Functions
DenseMap (unsigned InitialReserve=0)
Create a DenseMap wth an optional InitialReserve that guarantee that this number of elements can be inserted in the map without grow()
DenseMap (const DenseMap &other)
DenseMap (DenseMap &&other)
template<typename InputIt >
DenseMap (const InputIt &I, const InputIt &E)
DenseMap (std::initializer_list< typename BaseT::value_type > Vals)
~DenseMap ()
void swap (DenseMap &RHS)
DenseMap & operator= (const DenseMap &other)
DenseMap & operator= (DenseMap &&other)
void copyFrom (const DenseMap &other)
void init (unsigned InitNumEntries)
void grow (unsigned AtLeast)
void shrink_and_clear ()
Public Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
LLVM_NODISCARD bool empty () const
unsigned size () const
void reserve (size_type NumEntries)
Grow the densemap so that it can contain at least NumEntries items before resizing again.
void clear ()
size_type count (const_arg_type_t< KeyT > Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const_arg_type_t< KeyT > Val)
const_iterator find (const_arg_type_t< KeyT > Val) const
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
Alternate version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const_arg_type_t< KeyT > Val) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (KeyT &&Key, Ts &&... Args)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (const KeyT &Key, Ts &&... Args)
template<typename LookupKeyT >
std::pair< iterator, bool > insert_as (std::pair< KeyT, ValueT > &&KV, const LookupKeyT &Val)
Alternate version of insert() which allows a different, and possibly less expensive, key type.
template<typename InputIt >
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
value_type & FindAndConstruct (KeyT &&Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
const void * getPointerIntoBucketsArray () const
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
size_t getMemorySize () const
Return the approximate size (in bytes) of the actual map.
Public Member Functions inherited from llvm::DebugEpochBase
void incrementEpoch ()
Friends
class DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >
Additional Inherited Members
Public Types inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
using size_type = unsigned
using key_type = KeyT
using mapped_type = ValueT
using value_type = BucketT
using iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >
using const_iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT, true >
Protected Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
DenseMapBase ()=default
void destroyAll ()
void initEmpty ()
unsigned getMinBucketToReserveForEntries (unsigned NumEntries)
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT >
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > &other)
Static Protected Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT >
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>>
class llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >
Definition at line 710 of file DenseMap.h.
Constructor & Destructor Documentation
DenseMap() [1/5]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap (unsigned InitialReserve = 0) inline explicit
Create a DenseMap wth an optional InitialReserve that guarantee that this number of elements can be inserted in the map without grow()
Definition at line 726 of file DenseMap.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init().
DenseMap() [2/5]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap (const DenseMap< KeyT, ValueT, KeyInfoT, BucketT > & other) inline
Definition at line 728 of file DenseMap.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), and llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init().
DenseMap() [3/5]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap (DenseMap< KeyT, ValueT, KeyInfoT, BucketT > && other) inline
Definition at line 733 of file DenseMap.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init().
DenseMap() [4/5]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> template<typename InputIt > llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap (const InputIt & I, const InputIt & E) inline
Definition at line 739 of file DenseMap.h.
References E, I, llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
DenseMap() [5/5]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap (std::initializer_list< typename BaseT::value_type > Vals) inline
Definition at line 744 of file DenseMap.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
~DenseMap()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::~DenseMap () inline
Definition at line 749 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll().
Member Function Documentation
copyFrom()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::copyFrom (const DenseMap< KeyT, ValueT, KeyInfoT, BucketT > & other) inline
Definition at line 777 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap(), and llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::operator=().
grow()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::grow (unsigned AtLeast) inline
Definition at line 798 of file DenseMap.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), and llvm::NextPowerOf2().
init()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init (unsigned InitNumEntries) inline
Definition at line 788 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::operator=(), and llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear().
operator=() [1/2]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> DenseMap & llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::operator= (const DenseMap< KeyT, ValueT, KeyInfoT, BucketT > & other) inline
Definition at line 763 of file DenseMap.h.
References llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::copyFrom().
operator=() [2/2]
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> DenseMap & llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::operator= (DenseMap< KeyT, ValueT, KeyInfoT, BucketT > && other) inline
Definition at line 769 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), and llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init().
shrink_and_clear()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear () inline
Definition at line 815 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), and llvm::Log2_32_Ceil().
Referenced by llvm::mca::InstrBuilder::clear(), and llvm::AssumptionCacheTracker::releaseMemory().
swap()
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::swap (DenseMap< KeyT, ValueT, KeyInfoT, BucketT > & RHS) inline
Definition at line 754 of file DenseMap.h.
References llvm::DebugEpochBase::incrementEpoch(), and std::swap().
Friends And Related Function Documentation
DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> friend class DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT > friend
Definition at line 668 of file DenseMap.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseMap.h