LLVM: llvm::MCCodePaddingPolicy Class Reference
llvm::MCCodePaddingPolicy Class Reference abstract
The base class for all padding policies, i.e.
#include "llvm/MC/MCCodePadder.h"
Public Member Functions
virtual ~MCCodePaddingPolicy ()
uint64_t getKindMask () const
Returns the kind mask of this policy - A mask holding the kind of this policy, i.e.
uint64_t getWindowSize () const
Returns the instruction window size relevant to this policy.
bool isInstByteLastByte () const
Returns true if the last byte of an instruction determines its instruction window, or false if the first of an instruction determines it.
virtual bool basicBlockRequiresPaddingFragment (const MCCodePaddingContext &Context) const
Returns true iff this policy needs padding for a given basic block.
virtual bool instructionRequiresPaddingFragment (const MCInst &Inst) const
Returns true iff this policy needs padding for a given instruction.
double computeRangePenaltyWeight (const MCPFRange &Range, uint64_t Offset, MCAsmLayout &Layout) const
Computes and returns the penalty caused by a range of instruction windows.
Protected Member Functions
MCCodePaddingPolicy (uint64_t Kind, uint64_t WindowSize, bool InstByteIsLastByte)
uint64_t getFragmentInstByte (const MCPaddingFragment *Fragment, MCAsmLayout &Layout) const
Returns the instruction byte of an instruction pointed by a given MCPaddingFragment.
uint64_t computeWindowEndAddress (const MCPaddingFragment *Fragment, uint64_t Offset, MCAsmLayout &Layout) const
double computeFirstWindowPenaltyWeight (const MCPFRange &Window, uint64_t Offset, MCAsmLayout &Layout) const
Computes and returns the penalty weight of a first instruction window in a range.
virtual double computeWindowPenaltyWeight (const MCPFRange &Window, uint64_t Offset, MCAsmLayout &Layout) const =0
Computes and returns the penalty caused by an instruction window.
Static Protected Member Functions
static uint64_t getNextFragmentOffset (const MCFragment *Fragment, const MCAsmLayout &Layout)
Computes and returns the offset of the consecutive fragment of a given fragment.
Protected Attributes
const uint64_t KindMask
A mask holding the kind of this policy, i.e.
const uint64_t WindowSize
Instruction window size relevant to this policy.
const bool InstByteIsLastByte
A boolean indicating which byte of the instruction determies its instruction window.
Detailed Description
The base class for all padding policies, i.e.
a rule or set of rules to pad the generated code.
Definition at line 126 of file MCCodePadder.h.
Constructor & Destructor Documentation
MCCodePaddingPolicy()
llvm::MCCodePaddingPolicy::MCCodePaddingPolicy (uint64_t Kind, uint64_t WindowSize, bool InstByteIsLastByte) inline protected
Definition at line 142 of file MCCodePadder.h.
~MCCodePaddingPolicy()
virtual llvm::MCCodePaddingPolicy::~MCCodePaddingPolicy () inline virtual
Definition at line 197 of file MCCodePadder.h.
Member Function Documentation
basicBlockRequiresPaddingFragment()
virtual bool llvm::MCCodePaddingPolicy::basicBlockRequiresPaddingFragment (const MCCodePaddingContext & Context) const inline virtual
Returns true iff this policy needs padding for a given basic block.
Parameters
Context the context of the padding, Embeds the basic block's parameters.
Returns
true iff this policy needs padding for the basic block.
Definition at line 215 of file MCCodePadder.h.
computeFirstWindowPenaltyWeight()
double MCCodePaddingPolicy::computeFirstWindowPenaltyWeight (const MCPFRange & Window, uint64_t Offset, MCAsmLayout & Layout) const protected
Computes and returns the penalty weight of a first instruction window in a range.
This requires a special function since the first window does not contain all the padding fragments in that window. It only contains all the padding fragments starting from the relevant insertion point.
Parameters
Window The first window.
Offset The offset of the parent section relative to the beginning of the file, mod the window size.
Layout Code layout information.
Returns
the penalty weight of a first instruction window in a range, Window.
Definition at line 329 of file MCCodePadder.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), computeWindowEndAddress(), computeWindowPenaltyWeight(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getKindMask(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::MCPaddingFragment::hasPaddingPolicy(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by computeRangePenaltyWeight().
computeRangePenaltyWeight()
double MCCodePaddingPolicy::computeRangePenaltyWeight (const MCPFRange & Range, uint64_t Offset, MCAsmLayout & Layout) const
Computes and returns the penalty caused by a range of instruction windows.
The weight is computed for each window separelty and then accumulated.
Parameters
Range The range.
Offset The offset of the parent section relative to the beginning of the file, mod the window size.
Layout Code layout information.
Returns
the penalty caused by Range.
Definition at line 293 of file MCCodePadder.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), computeFirstWindowPenaltyWeight(), computeWindowEndAddress(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getKindMask(), llvm::MCPaddingFragment::hasPaddingPolicy(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
computeWindowEndAddress()
uint64_t MCCodePaddingPolicy::computeWindowEndAddress (const MCPaddingFragment * Fragment, uint64_t Offset, MCAsmLayout & Layout) const protected
Definition at line 286 of file MCCodePadder.cpp.
References llvm::alignTo(), getFragmentInstByte(), and WindowSize.
Referenced by computeFirstWindowPenaltyWeight(), and computeRangePenaltyWeight().
computeWindowPenaltyWeight()
virtual double llvm::MCCodePaddingPolicy::computeWindowPenaltyWeight (const MCPFRange & Window, uint64_t Offset, MCAsmLayout & Layout) const protected pure virtual
Computes and returns the penalty caused by an instruction window.
Parameters
Window The instruction window.
Offset The offset of the parent section relative to the beginning of the file, mod the window size.
Layout Code layout information.
Returns
the penalty caused by Window.
Referenced by computeFirstWindowPenaltyWeight().
getFragmentInstByte()
uint64_t MCCodePaddingPolicy::getFragmentInstByte (const MCPaddingFragment * Fragment, MCAsmLayout & Layout) const protected
Returns the instruction byte of an instruction pointed by a given MCPaddingFragment.
An instruction byte is the address of the byte of an instruction which determines its instruction window.
Parameters
Fragment The fragment pointing to the instruction.
Layout Code layout information.
Returns
the instruction byte of an instruction pointed by Fragment.
Definition at line 277 of file MCCodePadder.cpp.
References llvm::MCPaddingFragment::getInstSize(), getNextFragmentOffset(), and InstByteIsLastByte.
Referenced by computeWindowEndAddress().
getKindMask()
uint64_t llvm::MCCodePaddingPolicy::getKindMask () const inline
Returns the kind mask of this policy - A mask holding the kind of this policy, i.e.
only the i'th bit will be set where i is the kind number.
Definition at line 201 of file MCCodePadder.h.
References KindMask.
Referenced by computeFirstWindowPenaltyWeight(), and computeRangePenaltyWeight().
getNextFragmentOffset()
uint64_t MCCodePaddingPolicy::getNextFragmentOffset (const MCFragment * Fragment, const MCAsmLayout & Layout) static protected
Computes and returns the offset of the consecutive fragment of a given fragment.
Parameters
Fragment The fragment whose consecutive offset will be computed.
Layout Code layout information.
Returns
the offset of the consecutive fragment of Fragment.
Definition at line 267 of file MCCodePadder.cpp.
References assert(), llvm::MCAsmLayout::getFragmentOffset(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MCFragment::getParent(), and llvm::MCAsmLayout::getSectionAddressSize().
Referenced by getFragmentInstByte().
getWindowSize()
uint64_t llvm::MCCodePaddingPolicy::getWindowSize () const inline
Returns the instruction window size relevant to this policy.
Definition at line 203 of file MCCodePadder.h.
References WindowSize.
instructionRequiresPaddingFragment()
virtual bool llvm::MCCodePaddingPolicy::instructionRequiresPaddingFragment (const MCInst & Inst) const inline virtual
Returns true iff this policy needs padding for a given instruction.
Parameters
Inst The given instruction.
Returns
true iff this policy needs padding for Inst.
Definition at line 223 of file MCCodePadder.h.
isInstByteLastByte()
bool llvm::MCCodePaddingPolicy::isInstByteLastByte () const inline
Returns true if the last byte of an instruction determines its instruction window, or false if the first of an instruction determines it.
Definition at line 206 of file MCCodePadder.h.
References InstByteIsLastByte.
Member Data Documentation
InstByteIsLastByte
const bool llvm::MCCodePaddingPolicy::InstByteIsLastByte protected
A boolean indicating which byte of the instruction determies its instruction window.
If true - the last byte of the instructions, o.w. - the first byte of the instruction.
Definition at line 140 of file MCCodePadder.h.
Referenced by getFragmentInstByte(), and isInstByteLastByte().
KindMask
const uint64_t llvm::MCCodePaddingPolicy::KindMask protected
A mask holding the kind of this policy, i.e.
only the i'th bit will be set where i is the kind number.
Definition at line 134 of file MCCodePadder.h.
Referenced by getKindMask().
WindowSize
const uint64_t llvm::MCCodePaddingPolicy::WindowSize protected
Instruction window size relevant to this policy.
Definition at line 136 of file MCCodePadder.h.
Referenced by computeWindowEndAddress(), and getWindowSize().
The documentation for this class was generated from the following files:
include/llvm/MC/MCCodePadder.h
lib/MC/MCCodePadder.cpp