LLVM: llvm::FileCheckPattern Class Reference
llvm::FileCheckPattern Class Reference
#include "llvm/Support/FileCheck.h"
Classes
struct VariableProperties
Parsing information about a variable.
Public Member Functions
FileCheckPattern (Check::FileCheckType Ty, FileCheckPatternContext *Context, Optional< size_t > Line=None)
SMLoc getLoc () const
FileCheckPatternContext * getContext () const
Expected< std::unique_ptr< FileCheckExpressionAST > > parseNumericSubstitutionBlock (StringRef Expr, Optional< FileCheckNumericVariable * > &DefinedNumericVariable, bool IsLegacyLineExpr, const SourceMgr &SM) const
Parses Expr for a numeric substitution block.
bool parsePattern (StringRef PatternStr, StringRef Prefix, SourceMgr &SM, const FileCheckRequest &Req)
Parses the pattern in PatternStr and initializes this FileCheckPattern instance accordingly.
Expected< size_t > match (StringRef Buffer, size_t &MatchLen, const SourceMgr &SM) const
Matches the pattern string against the input buffer Buffer.
void printSubstitutions (const SourceMgr &SM, StringRef Buffer, SMRange MatchRange=None) const
Prints the value of successful substitutions or the name of the undefined string or numeric variables preventing a successful substitution.
void printFuzzyMatch (const SourceMgr &SM, StringRef Buffer, std::vector< FileCheckDiag > *Diags) const
bool hasVariable () const
Check::FileCheckType getCheckTy () const
int getCount () const
Static Public Member Functions
static bool isValidVarNameStart (char C)
static Expected< VariableProperties > parseVariable (StringRef &Str, const SourceMgr &SM)
Parses the string at the start of Str for a variable name.
static Expected< FileCheckNumericVariable * > parseNumericVariableDefinition (StringRef &Expr, FileCheckPatternContext *Context, Optional< size_t > LineNumber, const SourceMgr &SM)
Parses Expr for the name of a numeric variable to be defined at line LineNumber or before input is parsed if LineNumber is None.
Detailed Description
Definition at line 416 of file FileCheck.h.
Constructor & Destructor Documentation
FileCheckPattern()
llvm::FileCheckPattern::FileCheckPattern (Check::FileCheckType Ty, FileCheckPatternContext * Context, Optional< size_t > Line = None) inline
Definition at line 484 of file FileCheck.h.
Member Function Documentation
getCheckTy()
Check::FileCheckType llvm::FileCheckPattern::getCheckTy () const inline
Definition at line 566 of file FileCheck.h.
Referenced by llvm::FileCheckString::CheckDag(), llvm::FileCheck::CheckInput(), printFuzzyMatch(), PrintMatch(), and PrintNoMatch().
getContext()
FileCheckPatternContext * llvm::FileCheckPattern::getContext () const inline
Returns
the pointer to the global state for all patterns in this FileCheck instance.
Definition at line 493 of file FileCheck.h.
getCount()
int llvm::FileCheckPattern::getCount () const inline
Definition at line 568 of file FileCheck.h.
References llvm::Check::FileCheckType::getCount().
Referenced by PrintMatch(), and PrintNoMatch().
getLoc()
SMLoc llvm::FileCheckPattern::getLoc () const inline
Returns
the location in source code.
Definition at line 489 of file FileCheck.h.
Referenced by llvm::FileCheckString::CheckDag(), and printFuzzyMatch().
hasVariable()
bool llvm::FileCheckPattern::hasVariable () const inline
Definition at line 562 of file FileCheck.h.
isValidVarNameStart()
bool FileCheckPattern::isValidVarNameStart (char C) static
Returns
whether C is a valid first character for a variable name.
Definition at line 78 of file FileCheck.cpp.
Referenced by parseVariable().
match()
Expected< size_t > FileCheckPattern::match (StringRef Buffer, size_t & MatchLen, const SourceMgr & SM) const
Matches the pattern string against the input buffer Buffer.
Returns
the position that is matched or an error indicating why matching failed. If there is a match, updates MatchLen with the size of the matched string.
The GlobalVariableTable StringMap in the FileCheckPatternContext class instance provides the current values of FileCheck string variables and is updated if this match defines new values. Likewise, the GlobalNumericVariableTable StringMap in the same class provides the current values of FileCheck numeric variables and is updated if this match defines new numeric values.
Definition at line 599 of file FileCheck.cpp.
References assert(), llvm::Check::CheckEmpty, llvm::Check::CheckEOF, llvm::FileCheckNumericVariable::clearValue(), llvm::DITypeRefArray::get(), match(), llvm::Regex::Newline, and llvm::FileCheckNumericVariable::setValue().
Referenced by llvm::FileCheckString::CheckDag(), and match().
parseNumericSubstitutionBlock()
Expected< std::unique_ptr< FileCheckExpressionAST > > FileCheckPattern::parseNumericSubstitutionBlock (StringRef Expr, Optional< FileCheckNumericVariable * > & DefinedNumericVariable, bool IsLegacyLineExpr, const SourceMgr & SM) const
Parses Expr for a numeric substitution block.
Parameter IsLegacyLineExpr indicates whether Expr should be a legacy @LINE expression.
Returns
a pointer to the class instance representing the AST of the expression whose value must be substituted, or an error holding a diagnostic against SM if parsing fails. If substitution was successful, sets DefinedNumericVariable to point to the class representing the numeric variable being defined in this numeric substitution block, or None if this block does not define any variable.
Definition at line 270 of file FileCheck.cpp.
References llvm::DITypeRefArray::get(), llvm::None, parseNumericVariableDefinition(), SpaceChars, and llvm::Expected< T >::takeError().
Referenced by parsePattern().
parseNumericVariableDefinition()
Expected< FileCheckNumericVariable * > FileCheckPattern::parseNumericVariableDefinition (StringRef & Expr, FileCheckPatternContext * Context, Optional< size_t > LineNumber, const SourceMgr & SM) static
Parses Expr for the name of a numeric variable to be defined at line LineNumber or before input is parsed if LineNumber is None.
Returns
a pointer to the class instance representing that variable, creating it if needed, or an error holding a diagnostic against SM should defining such a variable be invalid.
Definition at line 126 of file FileCheck.cpp.
References llvm::DITypeRefArray::get(), parseVariable(), SpaceChars, and llvm::Expected< T >::takeError().
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables(), and parseNumericSubstitutionBlock().
parsePattern()
bool FileCheckPattern::parsePattern (StringRef PatternStr, StringRef Prefix, SourceMgr & SM, const FileCheckRequest & Req)
Parses the pattern in PatternStr and initializes this FileCheckPattern instance accordingly.
Prefix provides which prefix is being matched, Req describes the global options that influence the parsing such as whitespace canonicalization, SM provides the SourceMgr used for error reports.
Returns
true in case of an error, false otherwise.
Definition at line 319 of file FileCheck.cpp.
References llvm::Check::CheckEmpty, llvm::Check::CheckNot, llvm::SourceMgr::DK_Error, llvm::errs(), llvm::Regex::escape(), llvm::SMLoc::getFromPointer(), llvm::logAllUnhandledErrors(), llvm::FileCheckRequest::MatchFullLines, llvm::FileCheckRequest::NoCanonicalizeWhiteSpace, parseNumericSubstitutionBlock(), parseVariable(), llvm::SourceMgr::PrintMessage(), and llvm::Expected< T >::takeError().
parseVariable()
Expected< FileCheckPattern::VariableProperties > FileCheckPattern::parseVariable (StringRef & Str, const SourceMgr & SM) static
Parses the string at the start of Str for a variable name.
Returns
a VariableProperties structure holding the variable name and whether it is the name of a pseudo variable, or an error holding a diagnostic against SM if parsing fail. If parsing was successful, also strips Str from the variable name.
Definition at line 83 of file FileCheck.cpp.
References llvm::DITypeRefArray::get(), I, and isValidVarNameStart().
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables(), parseNumericVariableDefinition(), and parsePattern().
printFuzzyMatch()
void FileCheckPattern::printFuzzyMatch (const SourceMgr & SM, StringRef Buffer, std::vector< FileCheckDiag > * Diags) const
Definition at line 767 of file FileCheck.cpp.
References llvm::SourceMgr::DK_Note, getCheckTy(), getLoc(), llvm::FileCheckDiag::MatchFuzzy, llvm::SourceMgr::PrintMessage(), ProcessMatchResult(), and llvm::SMRange::Start.
Referenced by PrintNoMatch().
printSubstitutions()
void FileCheckPattern::printSubstitutions (const SourceMgr & SM, StringRef Buffer, SMRange MatchRange = None) const
Prints the value of successful substitutions or the name of the undefined string or numeric variables preventing a successful substitution.
Definition at line 707 of file FileCheck.cpp.
References llvm::SourceMgr::DK_Note, llvm::SMLoc::getFromPointer(), llvm::handleAllErrors(), llvm::SMRange::isValid(), llvm::SourceMgr::PrintMessage(), llvm::SMRange::Start, and llvm::Expected< T >::takeError().
Referenced by PrintMatch(), and PrintNoMatch().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCheck.h
lib/Support/FileCheck.cpp