LLVM: llvm::BasicBlock Class Reference
llvm::BasicBlock Class Reference final
LLVM Basic Block Representation.
#include "llvm/IR/BasicBlock.h"
Classes
class phi_iterator_impl
Iterator to walk just the phi nodes in the basic block.
Public Types
using InstListType = SymbolTableList< Instruction >
using iterator = InstListType::iterator
Instruction iterators...
using const_iterator = InstListType::const_iterator
using reverse_iterator = InstListType::reverse_iterator
using const_reverse_iterator = InstListType::const_reverse_iterator
using phi_iterator = phi_iterator_impl<>
using const_phi_iterator = phi_iterator_impl< const PHINode, BasicBlock::const_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
BasicBlock (const BasicBlock &)=delete
BasicBlock & operator= (const BasicBlock &)=delete
~BasicBlock ()
LLVMContext & getContext () const
Get the context in which this basic block lives.
const Function * getParent () const
Return the enclosing method, or null if none.
Function * getParent ()
const Module * getModule () const
Return the module owning the function this basic block belongs to, or nullptr if the function does not have a module.
Module * getModule ()
const Instruction * getTerminator () const LLVM_READONLY
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
Instruction * getTerminator ()
const CallInst * getTerminatingDeoptimizeCall () const
Returns the call instruction calling @llvm.experimental.deoptimize prior to the terminating return instruction of this basic block, if such a call is present.
CallInst * getTerminatingDeoptimizeCall ()
const CallInst * getTerminatingMustTailCall () const
Returns the call instruction marked 'musttail' prior to the terminating return instruction of this basic block, if such a call is present.
CallInst * getTerminatingMustTailCall ()
const Instruction * getFirstNonPHI () const
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
Instruction * getFirstNonPHI ()
const Instruction * getFirstNonPHIOrDbg () const
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
Instruction * getFirstNonPHIOrDbg ()
const Instruction * getFirstNonPHIOrDbgOrLifetime () const
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
Instruction * getFirstNonPHIOrDbgOrLifetime ()
const_iterator getFirstInsertionPt () const
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
iterator getFirstInsertionPt ()
iterator_range< filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> > > instructionsWithoutDebug () const
Return a const iterator range over the instructions in the block, skipping any debug instructions.
iterator_range< filter_iterator< BasicBlock::iterator, std::function< bool(Instruction &)> > > instructionsWithoutDebug ()
Return an iterator range over the instructions in the block, skipping any debug instructions.
void removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
SymbolTableList< BasicBlock >::iterator eraseFromParent ()
Unlink 'this' from the containing function and delete it.
void moveBefore (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
void moveAfter (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
void insertInto (Function *Parent, BasicBlock *InsertBefore=nullptr)
Insert unlinked basic block into a function.
const BasicBlock * getSinglePredecessor () const
Return the predecessor of this block if it has a single predecessor block.
BasicBlock * getSinglePredecessor ()
const BasicBlock * getUniquePredecessor () const
Return the predecessor of this block if it has a unique predecessor block.
BasicBlock * getUniquePredecessor ()
bool hasNPredecessors (unsigned N) const
Return true if this block has exactly N predecessors.
bool hasNPredecessorsOrMore (unsigned N) const
Return true if this block has N predecessors or more.
const BasicBlock * getSingleSuccessor () const
Return the successor of this block if it has a single successor.
BasicBlock * getSingleSuccessor ()
const BasicBlock * getUniqueSuccessor () const
Return the successor of this block if it has a unique successor.
BasicBlock * getUniqueSuccessor ()
iterator begin ()
Instruction iterator methods.
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
const Instruction & front () const
Instruction & front ()
const Instruction & back () const
Instruction & back ()
iterator_range< const_phi_iterator > phis () const
Returns a range that iterates over the phis in the basic block.
iterator_range< phi_iterator > phis ()
const InstListType & getInstList () const
Return the underlying instruction list container.
InstListType & getInstList ()
ValueSymbolTable * getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
void dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
void removePredecessor (BasicBlock *Pred, bool KeepOneInputPHIs=false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
bool canSplitPredecessors () const
BasicBlock * splitBasicBlock (iterator I, const Twine &BBName="")
Split the basic block into two basic blocks at the specified instruction.
BasicBlock * splitBasicBlock (Instruction *I, const Twine &BBName="")
bool hasAddressTaken () const
Returns true if there are any uses of this basic block other than direct branches, switches, etc.
void replacePhiUsesWith (BasicBlock *Old, BasicBlock *New)
Update all phi nodes in this basic block to refer to basic block New instead of basic block Old.
void replaceSuccessorsPhiUsesWith (BasicBlock *Old, BasicBlock *New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of basic block Old.
void replaceSuccessorsPhiUsesWith (BasicBlock *New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
bool isEHPad () const
Return true if this basic block is an exception handling block.
bool isLandingPad () const
Return true if this basic block is a landing pad.
const LandingPadInst * getLandingPadInst () const
Return the landingpad instruction associated with the landing pad.
LandingPadInst * getLandingPadInst ()
bool isLegalToHoistInto () const
Return true if it is legal to hoist instructions into this block.
Optional< uint64_t > getIrrLoopHeaderWeight () const
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCasts ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs, aliases and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripPointerCastsNoFollowAliases () const
Strip off pointer casts and all-zero GEPs.
Value * stripPointerCastsNoFollowAliases ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
unsigned getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static BasicBlock * Create (LLVMContext &Context, const Twine &Name="", Function *Parent=nullptr, BasicBlock *InsertBefore=nullptr)
Creates a new BasicBlock.
static InstListType BasicBlock::* getSublistAccess (Instruction *)
Returns a pointer to a member of the instruction list.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast.
Friends
class BlockAddress
class SymbolTableListTraits< BasicBlock >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
LLVM Basic Block Representation.
This represents a single basic block in LLVM. A basic block is simply a container of instructions that execute sequentially. Basic blocks are Values because they are referenced by instructions such as branches and switch tables. The type of a BasicBlock is "Type::LabelTy" because the basic block represents a label to which a branch can jump.
A well formed basic block is formed of a list of non-terminating instructions followed by a single terminator instruction. Terminator instructions may not occur in the middle of basic blocks, and must terminate the blocks. The BasicBlock class allows malformed basic blocks to occur because it may be useful in the intermediate stage of constructing or modifying a program. However, the verifier will ensure that basic blocks are "well formed".
Definition at line 57 of file BasicBlock.h.
Member Typedef Documentation
const_iterator
using llvm::BasicBlock::const_iterator = InstListType::const_iterator
Definition at line 90 of file BasicBlock.h.
const_phi_iterator
using llvm::BasicBlock::const_phi_iterator = phi_iterator_impl<const PHINode, BasicBlock::const_iterator>
Definition at line 318 of file BasicBlock.h.
const_reverse_iterator
using llvm::BasicBlock::const_reverse_iterator = InstListType::const_reverse_iterator
Definition at line 92 of file BasicBlock.h.
InstListType
using llvm::BasicBlock::InstListType = SymbolTableList<Instruction>
Definition at line 60 of file BasicBlock.h.
iterator
using llvm::BasicBlock::iterator = InstListType::iterator
Instruction iterators...
Definition at line 89 of file BasicBlock.h.
phi_iterator
using llvm::BasicBlock::phi_iterator = phi_iterator_impl<>
Definition at line 317 of file BasicBlock.h.
reverse_iterator
using llvm::BasicBlock::reverse_iterator = InstListType::reverse_iterator
Definition at line 91 of file BasicBlock.h.
Constructor & Destructor Documentation
BasicBlock()
llvm::BasicBlock::BasicBlock (const BasicBlock &) delete
~BasicBlock()
BasicBlock::~BasicBlock ()
Definition at line 63 of file BasicBlock.cpp.
References assert(), llvm::Constant::destroyConstant(), dropAllReferences(), llvm::DITypeRefArray::get(), getContext(), llvm::IRBuilderBase::getInt32Ty(), llvm::ConstantExpr::getIntToPtr(), getParent(), llvm::Value::getType(), hasAddressTaken(), llvm::Value::replaceAllUsesWith(), llvm::Value::use_empty(), and llvm::Value::user_back().
Member Function Documentation
back() [1/2]
Instruction & llvm::BasicBlock::back () inline
Definition at line 283 of file BasicBlock.h.
back() [2/2]
const Instruction & llvm::BasicBlock::back () const inline
Definition at line 282 of file BasicBlock.h.
Referenced by llvm::AAResults::canBasicBlockModify(), llvm::CloneAndPruneIntoFromInst(), scanInlinedCode(), llvm::SimplifyInstructionsInBlock(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::Solve(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
begin() [1/2]
iterator llvm::BasicBlock::begin () inline
Instruction iterator methods.
Definition at line 268 of file BasicBlock.h.
Referenced by AddReachableCodeToWorklist(), CanPropagatePredecessorsForPHIs(), canSplitCallSite(), llvm::CloneAndPruneIntoFromInst(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::computePeelCount(), cse(), DeleteBasicBlock(), llvm::DominatorTree::dominates(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), eliminateDeadStores(), llvm::EliminateDuplicatePHINodes(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), llvm::OrderedBasicBlock::eraseInstruction(), llvm::Evaluator::EvaluateFunction(), llvm::CodeExtractor::extractCodeRegion(), llvm::FindAvailablePtrLoadStore(), llvm::objcarc::FindDependencies(), findIBRPredecessor(), findInitTrampolineFromBB(), FindLoopCounter(), findPHIToPartitionLoops(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), findRetainForStoreStrongContraction(), findTRECandidate(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), fixPhis(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldSingleEntryPHINodes(), FoldTwoEntryPHINode(), llvm::formLCSSAForInstructions(), llvm::MemoryDependenceResults::getDependency(), llvm::GetIfCondition(), getInductionVariable(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleByValArgumentInit(), HandleCallsInBlockInlinedThroughInvoke(), handleEndBlock(), HandleInlinedEHPad(), llvm::hoistAllInstructionsInto(), llvm::hoistRegion(), HoistThenElseCodeToIf(), llvm::InlineFunction(), InsertSafepointPoll(), insertSinCosCall(), insertUniqueBackedgeBlock(), isBlockValidForExtraction(), llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::isSafeToLoadUnconditionally(), llvm::Value::isUsedInBasicBlock(), llvm::IVUsers::IVUsers(), LLVMGetPreviousInstruction(), makeStatepointExplicitImpl(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), NegateValue(), normalizeForInvokeSafepoint(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeSQRT(), llvm::peelLoop(), phis(), ProcessBlock(), processInternalGlobal(), promoteMemoryToRegister(), relocateInstructionBefore(), removeEmptyCleanup(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), replacePhiUsesWith(), rewritePHINodesForExitAndUnswitchedBlocks(), RewriteUsesOfClonedInstructions(), llvm::InstrProfiling::run(), runOnBasicBlock(), scanInlinedCode(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopIVs(), simplifyOneLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::sinkRegion(), SpeculativelyExecuteBB(), llvm::SplitBlock(), llvm::SplitBlockPredecessors(), splitCallSite(), llvm::SplitCriticalEdge(), llvm::SplitIndirectBrCriticalEdges(), splitPredecessorsOfLoopExit(), llvm::JumpThreadingPass::ThreadEdge(), llvm::JumpThreadingPass::ThreadGuard(), TryToMergeLandingPad(), tryToMoveFreeBeforeNullTest(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::JumpThreadingPass::TryToUnfoldSelectInCurrBB(), TurnSwitchRangeIntoICmp(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), updatePhiNodes(), UpdatePHINodes(), llvm::InstVisitor< SubClass, RetTy >::visit(), and llvm::InstCombiner::visitPHINode().
begin() [2/2]
const_iterator llvm::BasicBlock::begin () const inline
Definition at line 269 of file BasicBlock.h.
References llvm::sys::path::const_iterator::begin.
canSplitPredecessors()
bool BasicBlock::canSplitPredecessors () const
Definition at line 371 of file BasicBlock.cpp.
References getFirstNonPHI(), and llvm::Instruction::isEHPad().
Referenced by canSplitCallSite(), canSplitPredecessors(), and llvm::SplitBlockPredecessors().
classof()
static bool llvm::BasicBlock::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 345 of file BasicBlock.h.
References llvm::Value::getValueID().
Create()
static BasicBlock * llvm::BasicBlock::Create (LLVMContext & Context, const Twine & Name = "", Function * Parent = nullptr, BasicBlock * InsertBefore = nullptr) inline static
Creates a new BasicBlock.
If the Parent parameter is specified, the basic block is automatically inserted at either the end of the function (if InsertBefore is 0), or before the specified basic block.
Definition at line 99 of file BasicBlock.h.
Referenced by addBoundsChecking(), llvm::CloneBasicBlock(), createDevirtTriggerFunc(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createResumeEntryBlock(), llvm::createSanitizerCtorAndInitFunctions(), ehAwareSplitEdge(), eliminateRecursiveTailCall(), llvm::CodeExtractor::extractCodeRegion(), llvm::SanitizerStatReport::finish(), FoldCondBranchOnPHI(), generateUnsignedDivisionCode(), insertUniqueBackedgeBlock(), llvm::StringPool::intern(), LLVMAppendBasicBlockInContext(), LLVMCreateBasicBlockInContext(), LLVMInsertBasicBlockInContext(), matchRotate(), llvm::EscapeEnumerator::Next(), optimizeSQRT(), PerformHeapAllocSRoA(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), and llvm::JumpThreadingPass::UnfoldSelectInstr().
dropAllReferences()
void BasicBlock::dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 226 of file BasicBlock.cpp.
References I.
Referenced by llvm::Function::dropAllReferences(), and ~BasicBlock().
empty()
bool llvm::BasicBlock::empty () const inline
Definition at line 279 of file BasicBlock.h.
Referenced by phis().
end() [1/2]
iterator llvm::BasicBlock::end () inline
Definition at line 270 of file BasicBlock.h.
Referenced by AddReachableCodeToWorklist(), buildClonedLoopBlocks(), llvm::MemorySSAUpdater::changeToUnreachable(), llvm::changeToUnreachable(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::ConvertDebugDeclareToDebugValue(), cse(), DeleteBasicBlock(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateDeadStores(), eliminateRecursiveTailCall(), llvm::OrderedBasicBlock::eraseInstruction(), llvm::objcarc::FindDependencies(), findSafeStoreForStoreStrongContraction(), getFirstInsertionPt(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), HandleCallsInBlockInlinedThroughInvoke(), handleEndBlock(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), llvm::hoistAllInstructionsInto(), llvm::hoistRegion(), llvm::insertDebugValuesForPHIs(), InsertSafepointPoll(), instrumentOneFunc(), isBlockValidForExtraction(), llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::isPotentiallyReachable(), isSafeAndProfitableToSinkLoad(), llvm::Value::isUsedInBasicBlock(), llvm::isValidAssumeForContext(), LLVMGetNextInstruction(), LLVMPositionBuilder(), memoryIsNotModifiedBetween(), llvm::MergeBlockIntoPredecessor(), mergeConditionalStoreToAddress(), llvm::Instruction::moveBefore(), NegateValue(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::OrderedBasicBlock::OrderedBasicBlock(), llvm::PrepareToSplitEntryBlock(), ProcessBlock(), llvm::programUndefinedIfFullPoison(), promoteMemoryToRegister(), relocateInstructionBefore(), llvm::OrderedBasicBlock::replaceInstruction(), replacePhiUsesWith(), RewriteUsesOfClonedInstructions(), llvm::InstrProfiling::run(), runOnBasicBlock(), llvm::IRBuilderBase::SetInsertPoint(), shouldInstrumentBlock(), llvm::SimplifyInstructionsInBlock(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), llvm::sinkRegion(), SpeculativelyExecuteBB(), splitBasicBlock(), tryToMoveFreeBeforeNullTest(), llvm::JumpThreadingPass::UnfoldSelectInstr(), unswitchTrivialBranch(), and llvm::InstVisitor< SubClass, RetTy >::visit().
end() [2/2]
const_iterator llvm::BasicBlock::end () const inline
Definition at line 271 of file BasicBlock.h.
References llvm::sys::path::const_iterator::end.
eraseFromParent()
iplist< BasicBlock >::iterator BasicBlock::eraseFromParent ()
Unlink 'this' from the containing function and delete it.
Definition at line 114 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
Referenced by llvm::CloneAndPruneIntoFromInst(), DeleteBasicBlock(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), removeEmptyCleanup(), simplifyOneLoop(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
front() [1/2]
Instruction & llvm::BasicBlock::front () inline
Definition at line 281 of file BasicBlock.h.
front() [2/2]
const Instruction & llvm::BasicBlock::front () const inline
Definition at line 280 of file BasicBlock.h.
Referenced by llvm::AAResults::canBasicBlockModify(), llvm::CloneAndPruneFunctionInto(), llvm::CloneAndPruneIntoFromInst(), CloneInstructionInExitBlock(), createClone(), llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI(), createPHIsForSplitLoopExit(), createRetBitCast(), createRetPHINode(), eliminateDeadStores(), eliminateDeadSwitchCases(), eliminateRecursiveTailCall(), ensureValueAvailableInSuccessor(), findTRECandidate(), llvm::formLCSSAForInstructions(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::InlineFunction(), insertSpills(), insertTrivialPHIs(), isSafeToPromoteArgument(), llvm::MergeBlockIntoPredecessor(), mergeCleanupPad(), mergeEmptyReturnBlocks(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::removeAllNonTerminatorAndEHPadInstructions(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), rewritePHIs(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyCondBranchToCondBranch(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), sinkLastInstruction(), splitBlockIfNotFirst(), llvm::SplitEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and unswitchTrivialSwitch().
getContext()
LLVMContext & BasicBlock::getContext () const
Get the context in which this basic block lives.
Definition at line 32 of file BasicBlock.cpp.
References llvm::Type::getContext(), and llvm::Value::getType().
Referenced by AddRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), llvm::CloneBasicBlock(), llvm::ConstantFoldTerminator(), createMalloc(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createStringMetadata(), DisableAllLoopOptsOnLoop(), ehAwareSplitEdge(), llvm::emitBCmp(), llvm::emitCalloc(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), llvm::emitMalloc(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitStrLen(), llvm::emitStrNCmp(), llvm::CodeExtractor::extractCodeRegion(), FoldCondBranchOnPHI(), insertCall(), llvm::insertDebugValuesForPHIs(), insertUniqueBackedgeBlock(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), optimizeSQRT(), PerformHeapAllocSRoA(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), llvm::runIPSCCP(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setBranchWeights(), llvm::Loop::setLoopAlreadyUnrolled(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::JumpThreadingPass::UnfoldSelectInstr(), updatePredecessorProfileMetadata(), and ~BasicBlock().
getFirstInsertionPt() [1/2]
iterator llvm::BasicBlock::getFirstInsertionPt () inline
Definition at line 178 of file BasicBlock.h.
References getFirstInsertionPt().
getFirstInsertionPt() [2/2]
BasicBlock::const_iterator BasicBlock::getFirstInsertionPt () const
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
In particular, it skips all PHIs and LandingPad instructions.
Definition at line 216 of file BasicBlock.cpp.
References end(), and getFirstNonPHI().
Referenced by CloneInstructionInExitBlock(), llvm::ConvertDebugDeclareToDebugValue(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::DemoteRegToStack(), llvm::VPlan::execute(), llvm::CodeExtractor::extractCodeRegion(), findInsertPointAfter(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), foldGuardedRotateToFunnelShift(), getFirstInsertionPt(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), llvm::insertDebugValuesForPHIs(), insertSpills(), instrumentOneFunc(), makeStatepointExplicitImpl(), mergeConditionalStoreToAddress(), llvm::SCEVExpander::replaceCongruentIVs(), replaceExtractElements(), rewriteMaterializableInstructions(), llvm::InstCombiner::run(), shouldInstrumentBlock(), SinkInstruction(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadGuard(), TryToSinkInstruction(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getFirstNonPHI() [1/2]
Instruction * llvm::BasicBlock::getFirstNonPHI () inline
Definition at line 152 of file BasicBlock.h.
References getFirstNonPHI().
getFirstNonPHI() [2/2]
const Instruction * BasicBlock::getFirstNonPHI () const
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
When adding instructions to the beginning of the basic block, they should be added before the returned value, not before the first instruction, which might be PHI. Returns 0 is there's no non-PHI instruction.
Definition at line 189 of file BasicBlock.cpp.
References I.
Referenced by canSplitPredecessors(), canSplitPredecessors(), CloneInstructionInExitBlock(), CloneLoopBlocks(), llvm::colorEHFunclets(), ConnectEpilog(), ConnectProlog(), llvm::createMemCpyLoopKnownSize(), createPHIsForSplitLoopExit(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), ehAwareSplitEdge(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), fixPhis(), getFirstInsertionPt(), getFirstNonPHI(), getJumpThreadDuplicationCost(), getLandingPadInst(), getSuccPad(), getUnwindDestTokenHelper(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleInlinedEHPad(), hoist(), llvm::InlineFunction(), llvm::insertDebugValuesForPHIs(), insertUniqueBackedgeBlock(), isEHPad(), isLandingPad(), markAliveBlocks(), moveLCSSAPhis(), llvm::programUndefinedIfFullPoison(), relocationViaAlloca(), removeEmptyCleanup(), rewritePHIs(), llvm::SplitLandingPadPredecessors(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and llvm::UnrollRuntimeLoopRemainder().
getFirstNonPHIOrDbg() [1/2]
Instruction * llvm::BasicBlock::getFirstNonPHIOrDbg () inline
Definition at line 160 of file BasicBlock.h.
References getFirstNonPHIOrDbg().
getFirstNonPHIOrDbg() [2/2]
const Instruction * BasicBlock::getFirstNonPHIOrDbg () const
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
Definition at line 196 of file BasicBlock.cpp.
References I.
Referenced by llvm::ConstantFoldTerminator(), doCallSiteSplitting(), eliminateDeadSwitchCases(), eliminateTailRecursion(), FindPHIForConditionForwarding(), foldReturnAndProcessPred(), getFirstNonPHIOrDbg(), InitializeUniqueCases(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), isPredicatedOnPHI(), SimplifyCondBranchToTwoReturns(), llvm::SplitBlockPredecessors(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), and llvm::InstCombiner::visitAllocaInst().
getFirstNonPHIOrDbgOrLifetime() [1/2]
Instruction * llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime () inline
Definition at line 168 of file BasicBlock.h.
References getFirstNonPHIOrDbgOrLifetime().
getFirstNonPHIOrDbgOrLifetime() [2/2]
const Instruction * BasicBlock::getFirstNonPHIOrDbgOrLifetime () const
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
Definition at line 203 of file BasicBlock.cpp.
References I.
Referenced by getFirstNonPHIOrDbgOrLifetime(), shouldInstrumentBlock(), simplifyTerminatorLeadingToRet(), and llvm::SplitCriticalEdge().
getInstList() [1/2]
InstListType & llvm::BasicBlock::getInstList () inline
Definition at line 334 of file BasicBlock.h.
getInstList() [2/2]
const InstListType & llvm::BasicBlock::getInstList () const inline
Return the underlying instruction list container.
Currently you need to access the underlying instruction list container directly if you want to modify it.
Definition at line 333 of file BasicBlock.h.
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), llvm::changeToUnreachable(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneBasicBlock(), CloneInstructionInExitBlock(), llvm::BinaryOperator::Create(), llvm::UnaryOperator::Create(), createCallHelper(), createInvokeHelper(), createMalloc(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateRecursiveTailCall(), llvm::Instruction::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::hoistAllInstructionsInto(), HoistThenElseCodeToIf(), llvm::InlineFunction(), llvm::Instruction::insertAfter(), llvm::Instruction::insertBefore(), llvm::IRBuilderDefaultInserter::InsertHelper(), llvm::InstCombiner::InsertNewInstBefore(), insertUniqueBackedgeBlock(), llvm::Instruction::Instruction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), moveBBContents(), llvm::Instruction::moveBefore(), llvm::Instruction::removeFromParent(), removePredecessor(), llvm::ReplaceInstWithInst(), llvm::InstCombiner::run(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyFunction(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::SplitLandingPadPredecessors(), llvm::JumpThreadingPass::ThreadEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollLoop(), unswitchTrivialBranch(), and llvm::InstCombiner::visitGetElementPtrInst().
getIrrLoopHeaderWeight()
Optional< uint64_t > BasicBlock::getIrrLoopHeaderWeight () const
Definition at line 472 of file BasicBlock.cpp.
References llvm::Instruction::getMetadata(), llvm::MDString::getString(), getTerminator(), and llvm::LLVMContext::MD_irr_loop.
getLandingPadInst() [1/2]
LandingPadInst * llvm::BasicBlock::getLandingPadInst () inline
Definition at line 416 of file BasicBlock.h.
References getLandingPadInst().
getLandingPadInst() [2/2]
const LandingPadInst * BasicBlock::getLandingPadInst () const
Return the landingpad instruction associated with the landing pad.
Definition at line 468 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by getLandingPadInst(), makeStatepointExplicitImpl(), and llvm::SplitLandingPadPredecessors().
getModule() [1/2]
Module * llvm::BasicBlock::getModule () inline
Definition at line 114 of file BasicBlock.h.
References getModule().
getModule() [2/2]
const Module * BasicBlock::getModule () const
Return the module owning the function this basic block belongs to, or nullptr if the function does not have a module.
Note: this is undefined behavior if the block does not have a parent.
Definition at line 133 of file BasicBlock.cpp.
References llvm::GlobalValue::getParent(), and getParent().
Referenced by llvm::LoopAccessInfo::addRuntimeChecks(), CanProveNotTakenFirstIteration(), CreateAssert(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), eliminateDeadStores(), llvm::emitBinaryFloatFnCall(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), llvm::InnerLoopVectorizer::emitSCEVChecks(), emitUnaryFloatFnCallHelper(), llvm::LazyValueInfo::eraseBlock(), llvm::FindAvailablePtrLoadStore(), FindLoopCounter(), findPHIToPartitionLoops(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getEdgeValueLocal(), getModule(), llvm::Instruction::getModule(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::getPtrStride(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), handleEndBlock(), isObjectDereferencedInBlock(), llvm::printLoop(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessImpliedCondition(), llvm::promoteLoopAccessesToScalars(), ReduceLoopStrength(), llvm::LoopIdiomRecognizePass::run(), llvm::LoopRotatePass::run(), llvm::simplifyCFG(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), simplifyOneLoop(), llvm::LazyValueInfo::threadEdge(), llvm::JumpThreadingPass::ThreadGuard(), llvm::UnrollRuntimeLoopRemainder(), llvm::LoopVersioning::versionLoop(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getParent() [1/2]
Function * llvm::BasicBlock::getParent () inline
Definition at line 107 of file BasicBlock.h.
getParent() [2/2]
const Function * llvm::BasicBlock::getParent () const inline
Return the enclosing method, or null if none.
Definition at line 106 of file BasicBlock.h.
Referenced by addNoRecurseAttrsTopDown(), llvm::CodeMetrics::analyzeBasicBlock(), llvm::changeToUnreachable(), llvm::CloneBasicBlock(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::colorEHFunclets(), CompareValueComplexity(), llvm::LoopSafetyInfo::computeBlockColors(), llvm::computePeelCount(), llvm::computeUnrollCount(), llvm::ConstantFoldTerminator(), copyMustTailReturn(), llvm::SanitizerStatReport::create(), llvm::IRBuilder< T, Inserter >::CreateAlloca(), llvm::IRBuilderBase::CreateAssumption(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), createFFSIntrinsic(), llvm::IRBuilderBase::CreateFMulReduce(), createFree(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), createMalloc(), llvm::IRBuilderBase::CreateMemCpy(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), llvm::IRBuilderBase::CreateMemMove(), createMemMoveLoop(), llvm::IRBuilderBase::CreateMemSet(), createMemSetLoop(), createPopcntIntrinsic(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), DeleteBasicBlock(), llvm::InstCombiner::dominatesAllUses(), ehAwareSplitEdge(), eliminateDeadStores(), eliminateRecursiveTailCall(), eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::findDevirtualizableCallsForTypeTest(), findTRECandidate(), FoldCondBranchOnPHI(), FoldTwoEntryPHINode(), llvm::formLCSSAForInstructions(), llvm::gatherUnrollingPreferences(), generateUnsignedDivisionCode(), llvm::BlockAddress::get(), llvm::CallBase::getCaller(), getCommonReturnValue(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), getDebugLocString(), llvm::MemoryDependenceResults::getDependency(), getDescription(), llvm::Trace::getFunction(), llvm::Instruction::getFunction(), llvm::MemoryDependenceResults::getLoadLoadClobberFullWidthSize(), getModule(), llvm::DOTGraphTraits< DomTreeNode * >::getNodeLabel(), llvm::DOTGraphTraits< RegionNode * >::getNodeLabel(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::getPtrStride(), getReductionIntrinsic(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::GCProjectionInst::getStatepoint(), getValueSymbolTable(), getVarName(), handleEndBlock(), HandleInlinedEHPad(), HandleInlinedLandingPad(), handlePhiDef(), llvm::InlineFunction(), llvm::DivergenceAnalysis::inRegion(), insertCall(), llvm::insertDebugValuesForPHIs(), InsertSafepointPoll(), insertSinCosCall(), insertSpills(), insertUniqueBackedgeBlock(), isDynamicConstant(), isExplicitVecOuterLoop(), isFreeInLoop(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::isPotentiallyReachable(), llvm::RecurrenceDescriptor::isReductionPHI(), isSafeToPromoteArgument(), llvm::AllocaInst::isStaticAlloca(), isValidCandidateForColdCC(), LLVMInsertBasicBlockInContext(), LLVMInsertExistingBasicBlockAfterInsertBlock(), llvm::BlockAddress::lookup(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), moveAfter(), moveBefore(), moveLCSSAPhis(), NegateValue(), optimizeSQRT(), llvm::peelLoop(), PerformHeapAllocSRoA(), placeSplitBlockCarefully(), populateWorklist(), llvm::PrepareToSplitEntryBlock(), llvm::JumpThreadingPass::ProcessBlock(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), promoteArguments(), llvm::AssumptionCache::registerAssumption(), removeFromParent(), replaceExtractElements(), reportLoopFusion(), llvm::SSAUpdaterBulk::RewriteAllUses(), RewriteUsesOfClonedInstructions(), llvm::GuardWideningPass::run(), llvm::IRCEPass::run(), llvm::IndVarSimplifyPass::run(), llvm::LICMPass::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::LoopPredicationPass::run(), llvm::LoopUnrollAndJamPass::run(), llvm::LoopFullUnrollPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::IVUsersWrapperPass::runOnLoop(), scanOneBB(), llvm::setProfMetadata(), SimplifyCondBranchToCondBranch(), sinkLoopInvariantInstructions(), llvm::LoopPass::skipLoop(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), UpdateAnalysisInformation(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitLandingPadInst(), and ~BasicBlock().
getSinglePredecessor() [1/2]
BasicBlock * llvm::BasicBlock::getSinglePredecessor () inline
Definition at line 222 of file BasicBlock.h.
References getSinglePredecessor().
getSinglePredecessor() [2/2]
const BasicBlock * BasicBlock::getSinglePredecessor () const
Return the predecessor of this block if it has a single predecessor block.
If this basic block has a single predecessor block, return the block, otherwise return a null pointer.
Otherwise return a null pointer.
Definition at line 233 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by CanPropagatePredecessorsForPHIs(), CanProveNotTakenFirstIteration(), canSafelyUnrollMultiExitLoop(), llvm::CloneAndPruneIntoFromInst(), llvm::VPPredInstPHIRecipe::execute(), FindPHIForConditionForwarding(), llvm::FoldBranchToCommonDest(), llvm::GetIfCondition(), getSinglePredecessor(), handlePhiDef(), llvm::isImpliedByDomCondition(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::isValidAssumeForContext(), llvm::MergeBasicBlockIntoOnlyPred(), mergeBlocksIntoPredecessors(), mergeCleanupPad(), mergeConditionalStores(), mergeConditionalStoreToAddress(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessGuards(), llvm::JumpThreadingPass::ProcessImpliedCondition(), recordConditions(), llvm::InstCombiner::replacedSelectWithOperand(), shouldInstrumentBlock(), SimplifyCondBranchToCondBranch(), simplifyOneLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifySuspendPoint(), splitBlockIfNotFirst(), llvm::SplitEdge(), tryToMoveFreeBeforeNullTest(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
getSingleSuccessor() [1/2]
BasicBlock * llvm::BasicBlock::getSingleSuccessor () inline
Definition at line 250 of file BasicBlock.h.
References getSingleSuccessor().
getSingleSuccessor() [2/2]
const BasicBlock * BasicBlock::getSingleSuccessor () const
Return the successor of this block if it has a single successor.
Otherwise return a null pointer.
This method is analogous to getSinglePredecessor above.
Definition at line 268 of file BasicBlock.cpp.
References llvm::succ_begin(), and llvm::succ_end().
Referenced by ensureValueAvailableInSuccessor(), llvm::VPlan::execute(), getSingleSuccessor(), mergeBlocksIntoPredecessors(), mergeConditionalStores(), and llvm::programUndefinedIfFullPoison().
getSublistAccess()
static InstListType BasicBlock::* llvm::BasicBlock::getSublistAccess (Instruction *) inline static
Returns a pointer to a member of the instruction list.
Definition at line 337 of file BasicBlock.h.
getTerminatingDeoptimizeCall() [1/2]
CallInst * llvm::BasicBlock::getTerminatingDeoptimizeCall () inline
Definition at line 131 of file BasicBlock.h.
References getTerminatingDeoptimizeCall().
getTerminatingDeoptimizeCall() [2/2]
const CallInst * BasicBlock::getTerminatingDeoptimizeCall () const
Returns the call instruction calling @llvm.experimental.deoptimize prior to the terminating return instruction of this basic block, if such a call is present.
Otherwise, returns null.
Definition at line 174 of file BasicBlock.cpp.
References F.
Referenced by llvm::canPeel(), llvm::getLoopEstimatedTripCount(), getTerminatingDeoptimizeCall(), and llvm::InlineFunction().
getTerminatingMustTailCall() [1/2]
CallInst * llvm::BasicBlock::getTerminatingMustTailCall () inline
Definition at line 140 of file BasicBlock.h.
References getTerminatingMustTailCall().
getTerminatingMustTailCall() [2/2]
const CallInst * BasicBlock::getTerminatingMustTailCall () const
Returns the call instruction marked 'musttail' prior to the terminating return instruction of this basic block, if such a call is present.
Otherwise, returns null.
Definition at line 143 of file BasicBlock.cpp.
References llvm::User::getOperand(), and llvm::ReturnInst::getReturnValue().
Referenced by getTerminatingMustTailCall(), and llvm::InlineFunction().
getTerminator() [1/2]
Instruction * llvm::BasicBlock::getTerminator () inline
Definition at line 122 of file BasicBlock.h.
References getTerminator().
getTerminator() [2/2]
const Instruction * BasicBlock::getTerminator () const
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
Definition at line 137 of file BasicBlock.cpp.
Referenced by AddReachableCodeToWorklist(), llvm::CodeMetrics::analyzeBasicBlock(), analyzeLoopUnrollCost(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::BranchProbabilityInfo::calculate(), llvm::canPeel(), canSinkInstructions(), canSplitPredecessors(), llvm::changeToUnreachable(), checkBasicSSA(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunctionInto(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::colorEHFunclets(), llvm::FunctionComparator::compare(), ComputePostOrders(), computeUnlikelySuccessors(), ConnectEpilog(), ConnectProlog(), llvm::ConstantFoldTerminator(), copyMustTailReturn(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemMoveLoop(), createMemSetLoop(), createPHIsForSplitLoopExit(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), doCallSiteSplitting(), DominatesMergePoint(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), ehAwareSplitEdge(), eliminateDeadStores(), eliminateDeadSwitchCases(), eliminateTailRecursion(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::Evaluator::EvaluateFunction(), llvm::VPlan::execute(), llvm::VPBasicBlock::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::CodeExtractor::extractCodeRegion(), findBasePointer(), findIBRPredecessor(), FindLoopCounter(), FindMostPopularDest(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), FindPHIForConditionForwarding(), findUnconditionalPreds(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), foldGuardedRotateToFunnelShift(), foldReturnAndProcessPred(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), llvm::FunctionComparator::functionHash(), generateUnsignedDivisionCode(), genLoopLimit(), GetBestDestForJumpOnUndef(), getBranchInsertPoint(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::Loop::LoopBounds::getCanonicalPredicate(), getEdgeValueLocal(), llvm::GetIfCondition(), getInsertPointForUses(), getIrrLoopHeaderWeight(), getJumpThreadDuplicationCost(), llvm::getLoopEstimatedTripCount(), llvm::RegionTraits< Function >::getNumSuccessors(), getOnlyLiveSuccessor(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getOutliningBenefit(), getOutliningPenalty(), llvm::GCProjectionInst::getStatepoint(), llvm::GetSuccessorNumber(), getTerminator(), handleFinalSuspend(), handleFree(), handlePhiDef(), hoist(), llvm::hoistAllInstructionsInto(), llvm::hoistRegion(), llvm::InlineFunction(), insertBoundsCheck(), llvm::DIBuilder::insertDeclare(), insertLifetimeMarkersSurroundingCall(), insertSpills(), insertUniqueBackedgeBlock(), IsAcceptableTarget(), isChainSelectCmpBranch(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::isImpliedByDomCondition(), isLegalToHoistInto(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopDead(), isLoopExitTestBasedOn(), isNotUsedOrFreeInLoop(), isSafePHIToSpeculate(), llvm::isSafeToExpandAt(), llvm::BasicBlockEdge::isSingleEdge(), llvm::isUniformLoop(), llvm::Loop::makeLoopInvariant(), llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeConditionalStoreToAddress(), mergeEmptyReturnBlocks(), moveBBContents(), needsLFTR(), llvm::EscapeEnumerator::Next(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeSQRT(), llvm::peelLoop(), PerformHeapAllocSRoA(), ProcessBlock(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnPHI(), llvm::JumpThreadingPass::ProcessImpliedCondition(), llvm::JumpThreadingPass::ProcessThreadableEdges(), llvm::promoteLoopAccessesToScalars(), recordCondition(), relocationViaAlloca(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::MemorySSAUpdater::removeBlocks(), removeEmptyCleanup(), llvm::removeUnwindEdge(), llvm::InstCombiner::replacedSelectWithOperand(), replaceSuccessorsPhiUsesWith(), llvm::runIPSCCP(), separateNestedLoop(), shouldRotateLoopExitingLatch(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), simplifyOneLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), sinkLastInstruction(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SpeculativelyExecuteBB(), splitBasicBlock(), splitBeforeCatchSwitch(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), splitCallSite(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitLandingPadPredecessors(), llvm::succ_begin(), llvm::succ_end(), llvm::JumpThreadingPass::ThreadEdge(), TryToMergeLandingPad(), tryToMoveFreeBeforeNullTest(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSinkInstruction(), llvm::JumpThreadingPass::TryToUnfoldSelect(), llvm::JumpThreadingPass::TryToUnfoldSelectInCurrBB(), turnGuardIntoBranch(), turnToExplicitForm(), llvm::JumpThreadingPass::UnfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchAllTrivialConditions(), unswitchTrivialBranch(), unswitchTrivialSwitch(), updatePredecessorProfileMetadata(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::LoopVersioning::versionLoop(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitPHINode(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
getUniquePredecessor() [1/2]
BasicBlock * llvm::BasicBlock::getUniquePredecessor () inline
Definition at line 234 of file BasicBlock.h.
References getUniquePredecessor().
getUniquePredecessor() [2/2]
const BasicBlock * BasicBlock::getUniquePredecessor () const
Return the predecessor of this block if it has a unique predecessor block.
If this basic block has a unique predecessor block, return the block, otherwise return a null pointer.
Otherwise return a null pointer.
Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Definition at line 246 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by areLoopExitPHIsSupported(), findLocationForEntrySafepoint(), getUniquePredecessor(), IsAcceptableTarget(), isDynamicConstant(), makeStatepointExplicitImpl(), llvm::MergeBlockIntoPredecessor(), normalizeForInvokeSafepoint(), reuseTableCompare(), llvm::InstCombiner::run(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
getUniqueSuccessor() [1/2]
BasicBlock * llvm::BasicBlock::getUniqueSuccessor () inline
Definition at line 260 of file BasicBlock.h.
References getUniqueSuccessor().
getUniqueSuccessor() [2/2]
const BasicBlock * BasicBlock::getUniqueSuccessor () const
Return the successor of this block if it has a unique successor.
Otherwise return a null pointer.
This method is analogous to getUniquePredecessor above.
Definition at line 276 of file BasicBlock.cpp.
References llvm::succ_begin(), and llvm::succ_end().
Referenced by getUniqueSuccessor(), IsBackEdge(), llvm::MergeBlockIntoPredecessor(), and TryToMergeLandingPad().
getValueSymbolTable()
ValueSymbolTable * BasicBlock::getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
Definition at line 26 of file BasicBlock.cpp.
References F, and getParent().
hasAddressTaken()
bool llvm::BasicBlock::hasAddressTaken () const inline
Returns true if there are any uses of this basic block other than direct branches, switches, etc.
to it.
Definition at line 391 of file BasicBlock.h.
References llvm::Value::getSubclassDataFromValue().
Referenced by llvm::CloneFunctionInto(), foldReturnAndProcessPred(), hasAddressTakenAndUsed(), isBlockValidForExtraction(), llvm::isSafeToUnrollAndJam(), llvm::BlockAddress::lookup(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::UnrollLoop(), and ~BasicBlock().
hasNPredecessors()
bool BasicBlock::hasNPredecessors (unsigned N) const
Return true if this block has exactly N predecessors.
Definition at line 260 of file BasicBlock.cpp.
References N, llvm::pred_begin(), and llvm::pred_end().
Referenced by ensureValueAvailableInSuccessor(), llvm::JumpThreadingPass::ProcessThreadableEdges(), and llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor().
hasNPredecessorsOrMore()
bool BasicBlock::hasNPredecessorsOrMore (unsigned N) const
Return true if this block has N predecessors or more.
Definition at line 264 of file BasicBlock.cpp.
References N, llvm::pred_begin(), and llvm::pred_end().
insertInto()
void BasicBlock::insertInto (Function * Parent, BasicBlock * InsertBefore = nullptr)
Insert unlinked basic block into a function.
Inserts an unlinked basic block into Parent. If InsertBefore is provided, inserts before that basic block, otherwise inserts at the end.
Precondition
getParent() is nullptr.
Definition at line 53 of file BasicBlock.cpp.
References assert(), and llvm::Function::getBasicBlockList().
instructionsWithoutDebug() [1/2]
iterator_range< filter_iterator< BasicBlock::iterator, std::function< bool(Instruction &)> > > BasicBlock::instructionsWithoutDebug ()
Return an iterator range over the instructions in the block, skipping any debug instructions.
Definition at line 103 of file BasicBlock.cpp.
References I.
instructionsWithoutDebug() [2/2]
iterator_range< filter_iterator< BasicBlock::const_iterator, std::function< bool(const Instruction &)> > > BasicBlock::instructionsWithoutDebug () const
Return a const iterator range over the instructions in the block, skipping any debug instructions.
Definition at line 94 of file BasicBlock.cpp.
References I.
Referenced by BlockIsSimpleEnoughToThreadThrough(), llvm::FoldBranchToCommonDest(), GetCaseResults(), getOutliningBenefit(), isSafeToSpeculateStore(), mergeConditionalStoreToAddress(), llvm::LegacyDivergenceAnalysis::print(), SimplifyCondBranchToCondBranch(), and simplifyOneLoop().
isEHPad()
bool llvm::BasicBlock::isEHPad () const inline
Return true if this basic block is an exception handling block.
Definition at line 406 of file BasicBlock.h.
References getFirstNonPHI().
Referenced by canSplitCallSite(), insertUniqueBackedgeBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), separateNestedLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), and llvm::SplitCriticalEdge().
isLandingPad()
bool BasicBlock::isLandingPad () const
Return true if this basic block is a landing pad.
Being a `‘landing pad’' means that the basic block is the destination of the 'unwind' edge of an invoke instruction.
I.e., it's the destination of the 'unwind' edge of an invoke instruction.
Definition at line 463 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by createPHIsForSplitLoopExit(), llvm::SplitBlockPredecessors(), and llvm::SplitLandingPadPredecessors().
isLegalToHoistInto()
bool BasicBlock::isLegalToHoistInto () const
Return true if it is legal to hoist instructions into this block.
Definition at line 383 of file BasicBlock.cpp.
References assert(), and getTerminator().
moveAfter()
void BasicBlock::moveAfter (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right after MovePos.
Definition at line 127 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), placeSplitBlockCarefully(), and llvm::JumpThreadingPass::ThreadEdge().
moveBefore()
void BasicBlock::moveBefore (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Definition at line 120 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
Referenced by buildClonedLoopBlocks().
operator=()
BasicBlock & llvm::BasicBlock::operator= (const BasicBlock &) delete
phis() [1/2]
iterator_range< BasicBlock::phi_iterator > BasicBlock::phis ()
Definition at line 290 of file BasicBlock.cpp.
References begin(), empty(), and P.
phis() [2/2]
iterator_range< const_phi_iterator > llvm::BasicBlock::phis () const inline
Returns a range that iterates over the phis in the basic block.
Note that this cannot be used with basic blocks that have no terminator.
Definition at line 324 of file BasicBlock.h.
References phis().
Referenced by AddPHINodeEntriesForMappedBlock(), AddPredecessorToBlock(), areLoopExitPHIsSupported(), llvm::canIfConvertPHINodes(), ConnectEpilog(), createPHIsForSplitLoopExit(), llvm::DeleteDeadPHIs(), deleteLoopIfDead(), FindPHIForConditionForwarding(), llvm::InnerLoopVectorizer::fixCrossIterationPHIs(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixLCSSAPHIs(), llvm::InnerLoopVectorizer::fixReduction(), fixupPHINodeForNormalDest(), fixupPHINodeForUnwindDest(), ForwardSwitchConditionToPHI(), llvm::Loop::getInductionVariable(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HoistThenElseCodeToIf(), isEpilogProfitable(), isExistingPhi(), isLoopDead(), isSafeToHoistInvoke(), llvm::MergeBlockIntoPredecessor(), moveLCSSAPhis(), phis(), processHeaderPhiOperands(), PushLoopPHIs(), removeUndefIntroducingPredecessor(), llvm::SCEVExpander::replaceCongruentIVs(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHINodesForUnswitchedExitBlock(), scanPHIsAndUpdateValueMap(), shouldRotateLoopExitingLatch(), SimplifyCondBranchToCondBranch(), SpeculativelyExecuteBB(), and splitCallSite().
rbegin() [1/2]
reverse_iterator llvm::BasicBlock::rbegin () inline
Definition at line 273 of file BasicBlock.h.
References llvm::sys::path::reverse_iterator::rbegin.
Referenced by findLiveSetAtInst(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), and sinkLoopInvariantInstructions().
rbegin() [2/2]
const_reverse_iterator llvm::BasicBlock::rbegin () const inline
Definition at line 274 of file BasicBlock.h.
removeFromParent()
void BasicBlock::removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
Definition at line 110 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
Referenced by llvm::DomTreeUpdater::callbackDeleteBB(), and llvm::DomTreeUpdater::deleteBB().
removePredecessor()
void BasicBlock::removePredecessor (BasicBlock * Pred, bool KeepOneInputPHIs = false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
This method is used to notify a BasicBlock that the specified Predecessor of the block is no longer able to reach it.
This is actually not used to update the Predecessor list, but is actually used to update the PHI nodes that reside in the block. Note that this should be called while the predecessor still refers to this block.
Definition at line 301 of file BasicBlock.cpp.
References assert(), begin(), llvm::Instruction::eraseFromParent(), front(), llvm::DITypeRefArray::get(), llvm::PHINode::getIncomingBlock(), getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::PHINode::hasConstantValue(), llvm::Value::hasNUsesOrMore(), llvm::pred_begin(), llvm::pred_end(), llvm::PHINode::removeIncomingValue(), and llvm::Value::replaceAllUsesWith().
Referenced by changeToCall(), llvm::ConstantFoldTerminator(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), HandleInlinedEHPad(), HandleInlinedLandingPad(), markAliveBlocks(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessImpliedCondition(), processSwitch(), llvm::RemovePredecessorAndSimplify(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), llvm::removeUnwindEdge(), SimplifyCondBranchToTwoReturns(), simplifyOneLoop(), SimplifyTerminatorOnSelect(), llvm::SplitCriticalEdge(), SwitchToLookupTable(), llvm::JumpThreadingPass::ThreadEdge(), TryToMergeLandingPad(), unswitchNontrivialInvariants(), and unswitchTrivialSwitch().
rend() [1/2]
reverse_iterator llvm::BasicBlock::rend () inline
Definition at line 275 of file BasicBlock.h.
References llvm::sys::path::reverse_iterator::rend.
Referenced by llvm::slpvectorizer::BoUpSLP::getSpillCost(), sinkLoopInvariantInstructions(), and splitCallSite().
rend() [2/2]
const_reverse_iterator llvm::BasicBlock::rend () const inline
Definition at line 276 of file BasicBlock.h.
replacePhiUsesWith()
void BasicBlock::replacePhiUsesWith (BasicBlock * Old, BasicBlock * New)
Update all phi nodes in this basic block to refer to basic block New instead of basic block Old.
Definition at line 434 of file BasicBlock.cpp.
References begin(), end(), and llvm::PHINode::replaceIncomingBlockWith().
Referenced by moveLCSSAPhis(), and replaceSuccessorsPhiUsesWith().
replaceSuccessorsPhiUsesWith() [1/2]
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
Definition at line 457 of file BasicBlock.cpp.
References replaceSuccessorsPhiUsesWith().
replaceSuccessorsPhiUsesWith() [2/2]
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * Old, BasicBlock * New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of basic block Old.
Definition at line 445 of file BasicBlock.cpp.
References getTerminator(), replacePhiUsesWith(), and llvm::successors().
Referenced by replaceSuccessorsPhiUsesWith(), and splitBasicBlock().
size()
size_t llvm::BasicBlock::size () const inline
Definition at line 278 of file BasicBlock.h.
Referenced by tryToMoveFreeBeforeNullTest(), and unswitchTrivialSwitch().
splitBasicBlock() [1/2]
BasicBlock * llvm::BasicBlock::splitBasicBlock (Instruction * I, const Twine & BBName = "") inline
Definition at line 385 of file BasicBlock.h.
References I, and splitBasicBlock().
splitBasicBlock() [2/2]
BasicBlock * BasicBlock::splitBasicBlock (iterator I, const Twine & BBName = "")
Split the basic block into two basic blocks at the specified instruction.
This splits a basic block into two at the specified instruction.
Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the original BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. The newly formed BasicBlock is returned. This function invalidates the specified iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Also note that this doesn't preserve any passes. To split blocks while keeping loop information consistent, use the SplitBlock utility function.
Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the new BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. This invalidates the iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Definition at line 407 of file BasicBlock.cpp.
References assert(), llvm::BranchInst::Create(), Create(), end(), getContext(), getInstList(), getParent(), getTerminator(), I, replaceSuccessorsPhiUsesWith(), and llvm::Instruction::setDebugLoc().
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), createMemSetLoop(), createResumeEntryBlock(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::VPlan::execute(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), generateUnsignedDivisionCode(), handleFinalSuspend(), llvm::InlineFunction(), insertBoundsCheck(), insertSpills(), PerformHeapAllocSRoA(), SimplifyBranchOnICmpChain(), SimplifyFunction(), splitBasicBlock(), splitBeforeCatchSwitch(), llvm::SplitBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), and splitBlockIfNotFirst().
Friends And Related Function Documentation
BlockAddress
friend class BlockAddress friend
Definition at line 63 of file BasicBlock.h.
SymbolTableListTraits< BasicBlock >
friend class SymbolTableListTraits< BasicBlock > friend
Definition at line 63 of file BasicBlock.h.
The documentation for this class was generated from the following files:
include/llvm/IR/BasicBlock.h
lib/IR/BasicBlock.cpp