LLVM: llvm::object::COFFObjectFile Class Reference
llvm::object::COFFObjectFile Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
uintptr_t getSymbolTable () const
uint16_t getMachine () const
uint16_t getSizeOfOptionalHeader () const
uint16_t getCharacteristics () const
uint32_t getTimeDateStamp () const
uint32_t getNumberOfSections () const
uint32_t getPointerToSymbolTable () const
uint32_t getRawNumberOfSymbols () const
uint32_t getNumberOfSymbols () const
const coff_load_configuration32 * getLoadConfig32 () const
const coff_load_configuration64 * getLoadConfig64 () const
StringRef getRelocationTypeName (uint16_t Type) const
COFFObjectFile (MemoryBufferRef Object, std::error_code &EC)
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
section_iterator section_begin () const override
section_iterator section_end () const override
const coff_section * getCOFFSection (const SectionRef &Section) const
COFFSymbolRef getCOFFSymbol (const DataRefImpl &Ref) const
COFFSymbolRef getCOFFSymbol (const SymbolRef &Symbol) const
const coff_relocation * getCOFFRelocation (const RelocationRef &Reloc) const
unsigned getSectionID (SectionRef Sec) const
unsigned getSymbolSectionID (SymbolRef Sym) const
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< uint64_t > getStartAddress () const override
SubtargetFeatures getFeatures () const override
import_directory_iterator import_directory_begin () const
import_directory_iterator import_directory_end () const
delay_import_directory_iterator delay_import_directory_begin () const
delay_import_directory_iterator delay_import_directory_end () const
export_directory_iterator export_directory_begin () const
export_directory_iterator export_directory_end () const
base_reloc_iterator base_reloc_begin () const
base_reloc_iterator base_reloc_end () const
const debug_directory * debug_directory_begin () const
const debug_directory * debug_directory_end () const
iterator_range< import_directory_iterator > import_directories () const
iterator_range< delay_import_directory_iterator > delay_import_directories () const
iterator_range< export_directory_iterator > export_directories () const
iterator_range< base_reloc_iterator > base_relocs () const
iterator_range< const debug_directory * > debug_directories () const
const dos_header * getDOSHeader () const
std::error_code getCOFFHeader (const coff_file_header *&Res) const
std::error_code getCOFFBigObjHeader (const coff_bigobj_file_header *&Res) const
std::error_code getPE32Header (const pe32_header *&Res) const
std::error_code getPE32PlusHeader (const pe32plus_header *&Res) const
std::error_code getDataDirectory (uint32_t index, const data_directory *&Res) const
std::error_code getSection (int32_t index, const coff_section *&Res) const
std::error_code getSection (StringRef SectionName, const coff_section *&Res) const
template<typename coff_symbol_type >
std::error_code getSymbol (uint32_t Index, const coff_symbol_type *&Res) const
Expected< COFFSymbolRef > getSymbol (uint32_t index) const
template<typename T >
std::error_code getAuxSymbol (uint32_t index, const T *&Res) const
std::error_code getSymbolName (COFFSymbolRef Symbol, StringRef &Res) const
std::error_code getSymbolName (const coff_symbol_generic *Symbol, StringRef &Res) const
ArrayRef< uint8_t > getSymbolAuxData (COFFSymbolRef Symbol) const
uint32_t getSymbolIndex (COFFSymbolRef Symbol) const
size_t getSymbolTableEntrySize () const
ArrayRef< coff_relocation > getRelocations (const coff_section *Sec) const
Expected< StringRef > getSectionName (const coff_section *Sec) const
uint64_t getSectionSize (const coff_section *Sec) const
Error getSectionContents (const coff_section *Sec, ArrayRef< uint8_t > &Res) const
uint64_t getImageBase () const
std::error_code getVaPtr (uint64_t VA, uintptr_t &Res) const
std::error_code getRvaPtr (uint32_t Rva, uintptr_t &Res) const
std::error_code getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > &Contents) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
std::error_code getHintName (uint32_t Rva, uint16_t &Hint, StringRef &Name) const
std::error_code getDebugPDBInfo (const debug_directory *DebugDir, const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information out of a codeview debug directory entry.
std::error_code getDebugPDBInfo (const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information from an executable.
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool is64 () const
StringRef mapDebugSectionName (StringRef Name) const override
Maps a debug section name to a standard DWARF section name.
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual SubtargetFeatures getFeatures () const =0
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
uint64_t getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class ImportDirectoryEntryRef
class ExportDirectoryEntryRef
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 762 of file COFF.h.
Constructor & Destructor Documentation
COFFObjectFile()
COFFObjectFile::COFFObjectFile (MemoryBufferRef Object, std::error_code & EC)
Definition at line 664 of file COFFObjectFile.cpp.
References llvm::object::dos_header::AddressOfNewExeHeader, llvm::object::ObjectFile::base(), llvm::COFF::BigObjMagic, checkSize(), llvm::object::Binary::Data, getNumberOfSections(), getNumberOfSymbols(), llvm::object::getObject(), getPointerToSymbolTable(), llvm::COFF::IMAGE_FILE_MACHINE_UNKNOWN, llvm::object::coff_file_header::isImportLibrary(), llvm::object::coff_file_header::Machine, llvm::object::pe32_header::Magic, memcmp, llvm::COFF::BigObjHeader::MinBigObjectVersion, llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, llvm::object::coff_file_header::NumberOfSections, llvm::object::parse_failed, llvm::COFF::PE32Header::PE32, llvm::COFF::PE32Header::PE32_PLUS, llvm::COFF::PEMagic, llvm::object::coff_file_header::SizeOfOptionalHeader, llvm::object::coff_bigobj_file_header::UUID, and llvm::object::coff_bigobj_file_header::Version.
Member Function Documentation
base_reloc_begin()
base_reloc_iterator COFFObjectFile::base_reloc_begin () const
Definition at line 871 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_reloc_end()
base_reloc_iterator COFFObjectFile::base_reloc_end () const
Definition at line 875 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_relocs()
iterator_range< base_reloc_iterator > COFFObjectFile::base_relocs () const
Definition at line 935 of file COFFObjectFile.cpp.
References base_reloc_begin(), base_reloc_end(), and llvm::make_range().
classof()
static bool llvm::object::COFFObjectFile::classof (const Binary * v) inline static
Definition at line 1070 of file COFF.h.
References llvm::object::Binary::isCOFF().
debug_directories()
iterator_range< const debug_directory * > llvm::object::COFFObjectFile::debug_directories () const inline
Definition at line 963 of file COFF.h.
References debug_directory_begin(), debug_directory_end(), and llvm::make_range().
Referenced by getDebugPDBInfo().
debug_directory_begin()
const debug_directory * llvm::object::COFFObjectFile::debug_directory_begin () const inline
Definition at line 951 of file COFF.h.
Referenced by debug_directories().
debug_directory_end()
const debug_directory * llvm::object::COFFObjectFile::debug_directory_end () const inline
Definition at line 954 of file COFF.h.
Referenced by debug_directories().
delay_import_directories()
iterator_range< delay_import_directory_iterator > COFFObjectFile::delay_import_directories () const
Definition at line 925 of file COFFObjectFile.cpp.
References delay_import_directory_begin(), delay_import_directory_end(), and llvm::make_range().
delay_import_directory_begin()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_begin () const
Definition at line 832 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
delay_import_directory_end()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_end () const
Definition at line 838 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
export_directories()
iterator_range< export_directory_iterator > COFFObjectFile::export_directories () const
Definition at line 931 of file COFFObjectFile.cpp.
References export_directory_begin(), export_directory_end(), and llvm::make_range().
export_directory_begin()
export_directory_iterator COFFObjectFile::export_directory_begin () const
Definition at line 844 of file COFFObjectFile.cpp.
References ExportDirectoryEntryRef.
Referenced by export_directories().
export_directory_end()
export_directory_iterator COFFObjectFile::export_directory_end () const
Definition at line 849 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::AddressTableEntries, ExportDirectoryEntryRef, and llvm::Ref.
Referenced by export_directories().
getArch()
Triple::ArchType COFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 898 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::Triple::thumb, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by getBytesInAddress().
getAuxSymbol()
template<typename T > std::error_code llvm::object::COFFObjectFile::getAuxSymbol (uint32_t index, const T *& Res) const inline
Definition at line 1009 of file COFF.h.
References E, llvm::errorToErrorCode(), getSymbol(), and llvm::Expected< T >::takeError().
getBytesInAddress()
uint8_t COFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 879 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getArch(), and llvm::Triple::x86_64.
getCharacteristics()
uint16_t llvm::object::COFFObjectFile::getCharacteristics () const inline
Definition at line 829 of file COFF.h.
References llvm::object::coff_file_header::Characteristics, llvm::object::coff_file_header::isImportLibrary(), and llvm_unreachable.
getCOFFBigObjHeader()
std::error_code COFFObjectFile::getCOFFBigObjHeader (const coff_bigobj_file_header *& Res) const
Definition at line 946 of file COFFObjectFile.cpp.
getCOFFHeader()
std::error_code COFFObjectFile::getCOFFHeader (const coff_file_header *& Res) const
Definition at line 940 of file COFFObjectFile.cpp.
getCOFFRelocation()
const coff_relocation * COFFObjectFile::getCOFFRelocation (const RelocationRef & Reloc) const
Definition at line 1189 of file COFFObjectFile.cpp.
References llvm::object::RelocationRef::getRawDataRefImpl().
getCOFFSection()
const coff_section * COFFObjectFile::getCOFFSection (const SectionRef & Section) const
Definition at line 1172 of file COFFObjectFile.cpp.
Referenced by getRvaAndSizeAsBytes(), getRvaPtr(), and getSection().
getCOFFSymbol() [1/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const DataRefImpl & Ref) const
Definition at line 1176 of file COFFObjectFile.cpp.
References llvm_unreachable, and llvm::Ref.
Referenced by getCOFFSymbol(), getCommonSymbolSizeImpl(), getSymbolAddress(), getSymbolAlignment(), getSymbolFlags(), getSymbolName(), getSymbolSection(), getSymbolSectionID(), getSymbolType(), and getSymbolValueImpl().
getCOFFSymbol() [2/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const SymbolRef & Symbol) const
Definition at line 1184 of file COFFObjectFile.cpp.
References getCOFFSymbol().
getCommonSymbolSizeImpl()
uint64_t COFFObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 243 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), and llvm::Ref.
getDataDirectory()
std::error_code COFFObjectFile::getDataDirectory (uint32_t index, const data_directory *& Res) const
Definition at line 963 of file COFFObjectFile.cpp.
References assert(), llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, and llvm::object::parse_failed.
Referenced by llvm::object::ExportDirectoryEntryRef::isForwarder().
getDebugPDBInfo() [1/2]
std::error_code COFFObjectFile::getDebugPDBInfo (const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information from an executable.
If the information is not present, Info will be set to nullptr and PDBFileName will be empty. An error is returned only on corrupt object files. Convenience accessor that can be used if the debug directory is not already handy.
Definition at line 525 of file COFFObjectFile.cpp.
References D, debug_directories(), getDebugPDBInfo(), and llvm::COFF::IMAGE_DEBUG_TYPE_CODEVIEW.
getDebugPDBInfo() [2/2]
std::error_code COFFObjectFile::getDebugPDBInfo (const debug_directory * DebugDir, const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information out of a codeview debug directory entry.
Definition at line 506 of file COFFObjectFile.cpp.
References llvm::object::debug_directory::AddressOfRawData, llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), getRvaAndSizeAsBytes(), llvm::object::parse_failed, llvm::ArrayRef< T >::size(), llvm::object::debug_directory::SizeOfData, and llvm::StringRef::split().
Referenced by getDebugPDBInfo().
getDOSHeader()
const dos_header * llvm::object::COFFObjectFile::getDOSHeader () const inline
Definition at line 967 of file COFF.h.
References llvm::object::ObjectFile::base().
Referenced by getSectionSize().
getFeatures()
SubtargetFeatures llvm::object::COFFObjectFile::getFeatures () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 941 of file COFF.h.
getFileFormatName()
StringRef COFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 883 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, and llvm::COFF::IMAGE_FILE_MACHINE_I386.
getHintName()
std::error_code COFFObjectFile::getHintName (uint32_t Rva, uint16_t & Hint, StringRef & Name) const
Definition at line 494 of file COFFObjectFile.cpp.
References getRvaPtr(), and Name.
getImageBase()
uint64_t COFFObjectFile::getImageBase () const
Definition at line 439 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::ImageBase, and llvm::object::pe32plus_header::ImageBase.
Referenced by getSectionAddress(), getSymbolAddress(), and getVaPtr().
getLoadConfig32()
const coff_load_configuration32 * llvm::object::COFFObjectFile::getLoadConfig32 () const inline
Definition at line 878 of file COFF.h.
References assert(), and is64().
getLoadConfig64()
const coff_load_configuration64 * llvm::object::COFFObjectFile::getLoadConfig64 () const inline
Definition at line 883 of file COFF.h.
References assert(), and is64().
getMachine()
uint16_t llvm::object::COFFObjectFile::getMachine () const inline
Definition at line 811 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::Machine, and llvm::object::coff_bigobj_file_header::Machine.
Referenced by getArch(), getFileFormatName(), getRelocationTypeName(), and llvm::libDriverMain().
getNumberOfSections()
uint32_t llvm::object::COFFObjectFile::getNumberOfSections () const inline
Definition at line 847 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSections, and llvm::object::coff_bigobj_file_header::NumberOfSections.
Referenced by COFFObjectFile(), getSection(), and section_end().
getNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getNumberOfSymbols () const inline
Definition at line 872 of file COFF.h.
References getRawNumberOfSymbols().
Referenced by COFFObjectFile(), getRelocationSymbol(), getSymbol(), getSymbolAuxData(), and getSymbolIndex().
getPE32Header()
std::error_code COFFObjectFile::getPE32Header (const pe32_header *& Res) const
Definition at line 951 of file COFFObjectFile.cpp.
getPE32PlusHeader()
std::error_code COFFObjectFile::getPE32PlusHeader (const pe32plus_header *& Res) const
Definition at line 957 of file COFFObjectFile.cpp.
getPointerToSymbolTable()
uint32_t llvm::object::COFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 855 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::PointerToSymbolTable, and llvm::object::coff_bigobj_file_header::PointerToSymbolTable.
Referenced by COFFObjectFile(), and getSymbolAuxData().
getRawNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getRawNumberOfSymbols () const inline
Definition at line 864 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSymbols, and llvm::object::coff_bigobj_file_header::NumberOfSymbols.
Referenced by getNumberOfSymbols().
getRelocationOffset()
uint64_t COFFObjectFile::getRelocationOffset (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1147 of file COFFObjectFile.cpp.
getRelocations()
ArrayRef< coff_relocation > COFFObjectFile::getRelocations (const coff_section * Sec) const
Definition at line 1194 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), and getNumberOfRelocations().
getRelocationSymbol()
symbol_iterator COFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1152 of file COFFObjectFile.cpp.
References getNumberOfSymbols(), llvm_unreachable, llvm::Ref, symbol_end(), and llvm::object::ObjectFile::SymbolRef.
getRelocationType()
uint64_t COFFObjectFile::getRelocationType (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1166 of file COFFObjectFile.cpp.
getRelocationTypeName() [1/2]
void COFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1299 of file COFFObjectFile.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), getRelocationTypeName(), and llvm::object::coff_relocation::Type.
getRelocationTypeName() [2/2]
StringRef COFFObjectFile::getRelocationTypeName (uint16_t Type) const
Definition at line 1203 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, and LLVM_COFF_SWITCH_RELOC_TYPE_NAME.
Referenced by getRelocationTypeName().
getRvaAndSizeAsBytes()
std::error_code COFFObjectFile::getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > & Contents) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
Definition at line 472 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), getCOFFSection(), llvm::object::parse_failed, llvm::object::ObjectFile::sections(), and Size.
Referenced by getDebugPDBInfo().
getRvaPtr()
std::error_code COFFObjectFile::getRvaPtr (uint32_t Rva, uintptr_t & Res) const
Definition at line 457 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), getCOFFSection(), llvm::object::parse_failed, and llvm::object::ObjectFile::sections().
Referenced by llvm::object::ExportDirectoryEntryRef::getDllName(), llvm::object::ExportDirectoryEntryRef::getExportRVA(), llvm::object::ExportDirectoryEntryRef::getForwardTo(), getHintName(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::object::ImportedSymbolRef::getOrdinal(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), llvm::object::ImportedSymbolRef::getSymbolName(), and getVaPtr().
getSection() [1/2]
std::error_code COFFObjectFile::getSection (int32_t index, const coff_section *& Res) const
Definition at line 981 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::COFF::isReservedSectionNumber(), and llvm::object::parse_failed.
Referenced by getSymbolAddress(), and getSymbolSection().
getSection() [2/2]
std::error_code COFFObjectFile::getSection (StringRef SectionName, const coff_section *& Res) const
Definition at line 994 of file COFFObjectFile.cpp.
References E, getCOFFSection(), llvm::object::parse_failed, and llvm::object::ObjectFile::sections().
getSectionAddress()
uint64_t COFFObjectFile::getSectionAddress (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 277 of file COFFObjectFile.cpp.
References getImageBase(), llvm::Ref, and llvm::object::coff_section::VirtualAddress.
getSectionAlignment()
uint64_t COFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 304 of file COFFObjectFile.cpp.
References llvm::object::coff_section::getAlignment(), and llvm::Ref.
getSectionContents() [1/2]
Error COFFObjectFile::getSectionContents (const coff_section * Sec, ArrayRef< uint8_t > & Res) const
Definition at line 1121 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::checkOffset(), llvm::object::Binary::Data, getSectionSize(), llvm::makeArrayRef(), llvm::object::coff_section::PointerToRawData, and llvm::Error::success().
getSectionContents() [2/2]
Expected< ArrayRef< uint8_t > > COFFObjectFile::getSectionContents (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 296 of file COFFObjectFile.cpp.
References E, getSectionContents(), and llvm::Ref.
Referenced by getSectionContents().
getSectionID()
unsigned COFFObjectFile::getSectionID (SectionRef Sec) const
Definition at line 331 of file COFFObjectFile.cpp.
References assert(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
getSectionIndex()
uint64_t COFFObjectFile::getSectionIndex (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 287 of file COFFObjectFile.cpp.
getSectionName() [1/2]
Expected< StringRef > COFFObjectFile::getSectionName (const coff_section * Sec) const
Definition at line 1077 of file COFFObjectFile.cpp.
References llvm::createStringError(), decodeBase64StringEntry(), llvm::errorCodeToError(), llvm::object::coff_section::Name, Name, llvm::COFF::NameSize, and llvm::object::parse_failed.
getSectionName() [2/2]
Expected< StringRef > COFFObjectFile::getSectionName (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 272 of file COFFObjectFile.cpp.
References getSectionName(), and llvm::Ref.
Referenced by getSectionName().
getSectionSize() [1/2]
uint64_t COFFObjectFile::getSectionSize (const coff_section * Sec) const
Definition at line 1105 of file COFFObjectFile.cpp.
References getDOSHeader(), llvm::object::coff_section::SizeOfRawData, and llvm::object::coff_section::VirtualSize.
getSectionSize() [2/2]
uint64_t COFFObjectFile::getSectionSize (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 291 of file COFFObjectFile.cpp.
References getSectionSize(), and llvm::Ref.
Referenced by getSectionContents(), and getSectionSize().
getSizeOfOptionalHeader()
uint16_t llvm::object::COFFObjectFile::getSizeOfOptionalHeader () const inline
Definition at line 819 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, and llvm::object::coff_file_header::SizeOfOptionalHeader.
getStartAddress()
Expected< uint64_t > COFFObjectFile::getStartAddress () const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 913 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::AddressOfEntryPoint.
getSymbol() [1/2]
Expected< COFFSymbolRef > llvm::object::COFFObjectFile::getSymbol (uint32_t index) const inline
Definition at line 992 of file COFF.h.
References llvm::errorCodeToError(), getSymbol(), and llvm::object::parse_failed.
getSymbol() [2/2]
template<typename coff_symbol_type > std::error_code llvm::object::COFFObjectFile::getSymbol (uint32_t Index, const coff_symbol_type *& Res) const inline
Definition at line 984 of file COFF.h.
References getNumberOfSymbols(), getSymbolTable(), and llvm::object::parse_failed.
Referenced by getAuxSymbol(), and getSymbol().
getSymbolAddress()
Expected< uint64_t > COFFObjectFile::getSymbolAddress (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 168 of file COFFObjectFile.cpp.
References llvm::errorCodeToError(), getCOFFSymbol(), getImageBase(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::ObjectFile::getSymbolValue(), llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::COFF::isReservedSectionNumber(), and llvm::Ref.
getSymbolAlignment()
uint32_t COFFObjectFile::getSymbolAlignment (DataRefImpl Symb) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 161 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), llvm::PowerOf2Ceil(), and llvm::Ref.
getSymbolAuxData()
ArrayRef< uint8_t > COFFObjectFile::getSymbolAuxData (COFFSymbolRef Symbol) const
Definition at line 1044 of file COFFObjectFile.cpp.
References assert(), llvm::object::ObjectFile::base(), getNumberOfSymbols(), getPointerToSymbolTable(), getSymbolTableEntrySize(), llvm::makeArrayRef(), and llvm::report_fatal_error().
getSymbolFlags()
uint32_t COFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 212 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::COFFSymbolRef::getWeakExternal(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_WEAK_EXTERN_SEARCH_ALIAS, llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isExternal(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::object::COFFSymbolRef::isUndefined(), llvm::object::COFFSymbolRef::isWeakExternal(), llvm::Ref, llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
getSymbolIndex()
uint32_t COFFObjectFile::getSymbolIndex (COFFSymbolRef Symbol) const
Definition at line 1066 of file COFFObjectFile.cpp.
References assert(), getNumberOfSymbols(), getSymbolTable(), and getSymbolTableEntrySize().
getSymbolName() [1/3]
std::error_code COFFObjectFile::getSymbolName (COFFSymbolRef Symbol, StringRef & Res) const
Definition at line 1020 of file COFFObjectFile.cpp.
References getSymbolName().
getSymbolName() [2/3]
std::error_code COFFObjectFile::getSymbolName (const coff_symbol_generic * Symbol, StringRef & Res) const
Definition at line 1025 of file COFFObjectFile.cpp.
References llvm::COFF::NameSize.
getSymbolName() [3/3]
Expected< StringRef > COFFObjectFile::getSymbolName (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 149 of file COFFObjectFile.cpp.
References llvm::errorCodeToError(), getCOFFSymbol(), getSymbolName(), and llvm::Ref.
Referenced by getSymbolName().
getSymbolSection()
Expected< section_iterator > COFFObjectFile::getSymbolSection (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 249 of file COFFObjectFile.cpp.
References llvm::errorCodeToError(), getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::isReservedSectionNumber(), llvm::Ref, section_end(), and llvm::object::ObjectFile::SectionRef.
getSymbolSectionID()
unsigned COFFObjectFile::getSymbolSectionID (SymbolRef Sym) const
Definition at line 261 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::COFFSymbolRef::getSectionNumber().
getSymbolTable()
uintptr_t llvm::object::COFFObjectFile::getSymbolTable () const inline
Definition at line 803 of file COFF.h.
Referenced by getSymbol(), getSymbolIndex(), and symbol_begin().
getSymbolTableEntrySize()
size_t llvm::object::COFFObjectFile::getSymbolTableEntrySize () const inline
Definition at line 1025 of file COFF.h.
References llvm_unreachable.
Referenced by getSymbolAuxData(), and getSymbolIndex().
getSymbolType()
Expected< SymbolRef::Type > COFFObjectFile::getSymbolType (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 189 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getComplexType(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::IMAGE_SYM_DEBUG, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::COFF::isReservedSectionNumber(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::Ref, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, and llvm::object::SymbolRef::ST_Unknown.
getSymbolValueImpl()
uint64_t COFFObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 157 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), and llvm::Ref.
getTimeDateStamp()
uint32_t llvm::object::COFFObjectFile::getTimeDateStamp () const inline
Definition at line 839 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::TimeDateStamp, and llvm::object::coff_bigobj_file_header::TimeDateStamp.
getVaPtr()
std::error_code COFFObjectFile::getVaPtr (uint64_t VA, uintptr_t & Res) const
Definition at line 449 of file COFFObjectFile.cpp.
References assert(), getImageBase(), and getRvaPtr().
import_directories()
iterator_range< import_directory_iterator > COFFObjectFile::import_directories () const
Definition at line 920 of file COFFObjectFile.cpp.
References import_directory_begin(), import_directory_end(), and llvm::make_range().
import_directory_begin()
import_directory_iterator COFFObjectFile::import_directory_begin () const
Definition at line 817 of file COFFObjectFile.cpp.
References import_directory_end(), ImportDirectoryEntryRef, and llvm::object::coff_import_directory_table_entry::isNull().
Referenced by import_directories().
import_directory_end()
import_directory_iterator COFFObjectFile::import_directory_end () const
Definition at line 826 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef.
Referenced by import_directories(), and import_directory_begin().
is64()
bool llvm::object::COFFObjectFile::is64 () const inline
Definition at line 1066 of file COFF.h.
Referenced by llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), getLoadConfig32(), and getLoadConfig64().
isRelocatableObject()
bool COFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1306 of file COFFObjectFile.cpp.
isSectionBSS()
bool COFFObjectFile::isSectionBSS (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 323 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, and llvm::Ref.
isSectionCompressed()
bool COFFObjectFile::isSectionCompressed (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 309 of file COFFObjectFile.cpp.
isSectionData()
bool COFFObjectFile::isSectionData (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 318 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, and llvm::Ref.
isSectionText()
bool COFFObjectFile::isSectionText (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 313 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_CODE, and llvm::Ref.
isSectionVirtual()
bool COFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 338 of file COFFObjectFile.cpp.
References llvm::object::coff_section::PointerToRawData, and llvm::Ref.
mapDebugSectionName()
StringRef COFFObjectFile::mapDebugSectionName (StringRef Name) const override virtual
Maps a debug section name to a standard DWARF section name.
Reimplemented from llvm::object::ObjectFile.
Definition at line 1310 of file COFFObjectFile.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and Name.
moveRelocationNext()
void COFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1142 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
moveSectionNext()
void COFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 266 of file COFFObjectFile.cpp.
References llvm::Ref.
moveSymbolNext()
void COFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 134 of file COFFObjectFile.cpp.
References llvm_unreachable, llvm::object::coff_symbol< SectionNumberType >::NumberOfAuxSymbols, and llvm::Ref.
section_begin()
section_iterator COFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 857 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator COFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 863 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::object::coff_file_header::isImportLibrary(), and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection().
section_rel_begin()
relocation_iterator COFFObjectFile::section_rel_begin (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 380 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), llvm::Ref, llvm::object::ObjectFile::RelocationRef, llvm::report_fatal_error(), and llvm::object::coff_section::VirtualAddress.
section_rel_end()
relocation_iterator COFFObjectFile::section_rel_end (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 390 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), getNumberOfRelocations(), I, llvm::Ref, and llvm::object::ObjectFile::RelocationRef.
symbol_begin()
basic_symbol_iterator COFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 804 of file COFFObjectFile.cpp.
References getSymbolTable(), and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator COFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 810 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::SymbolRef.
Referenced by getRelocationSymbol().
Friends And Related Function Documentation
ExportDirectoryEntryRef
friend class ExportDirectoryEntryRef friend
Definition at line 765 of file COFF.h.
Referenced by export_directory_begin(), and export_directory_end().
ImportDirectoryEntryRef
friend class ImportDirectoryEntryRef friend
Definition at line 764 of file COFF.h.
Referenced by import_directory_begin(), and import_directory_end().
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp