LLVM: llvm::BTFTypeStruct Class Reference
llvm::BTFTypeStruct Class Reference
Handle struct/union type.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeStruct (const DICompositeType *STy, bool IsStruct, bool HasBitField, uint32_t NumMembers)
Represent either a struct or a union.
uint32_t getSize ()
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
std::string getName ()
void getMemberInfo (uint32_t Loc, uint32_t &Offset, uint32_t &MemberType)
uint32_t getStructSize ()
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
virtual uint32_t getSize ()
Get the size of this BTF type entry.
virtual void completeType (BTFDebug &BDebug)
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
virtual void emitType (MCStreamer &OS)
Emit types for this BTF type entry.
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle struct/union type.
Definition at line 122 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeStruct()
BTFTypeStruct::BTFTypeStruct (const DICompositeType * STy, bool IsStruct, bool HasBitField, uint32_t NumMembers)
Represent either a struct or a union.
Definition at line 241 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::DIType::getSizeInBits(), llvm::BTF::CommonType::Info, llvm::BTFTypeBase::Kind, llvm::BTFTypeBase::roundupToBytes(), and llvm::BTF::CommonType::Size.
Member Function Documentation
completeType()
void BTFTypeStruct::completeType (BTFDebug & BDebug) virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 249 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, llvm::DICompositeType::getElements(), llvm::DIType::getName(), llvm::BTFDebug::getTypeId(), llvm::BTFTypeBase::IsCompleted, llvm::BTF::CommonType::NameOff, llvm::BTF::BTFMember::NameOff, llvm::BTF::BTFMember::Offset, stripQualifiers(), and llvm::BTF::BTFMember::Type.
emitType()
void BTFTypeStruct::emitType (MCStreamer & OS) virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 276 of file BTFDebug.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitIntValue(), llvm::BTFTypeBase::emitType(), and llvm::Twine::utohexstr().
getMemberInfo()
void BTFTypeStruct::getMemberInfo (uint32_t Loc, uint32_t & Offset, uint32_t & MemberType)
Definition at line 288 of file BTFDebug.cpp.
getName()
std::string BTFTypeStruct::getName ()
Definition at line 286 of file BTFDebug.cpp.
References llvm::DIType::getName().
getSize()
uint32_t llvm::BTFTypeStruct::getSize () inline virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 131 of file BTFDebug.h.
References llvm::BTF::BTFMemberSize, and llvm::BTFTypeBase::getSize().
getStructSize()
uint32_t BTFTypeStruct::getStructSize ()
Definition at line 295 of file BTFDebug.cpp.
References llvm::DIType::getSizeInBits().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp