LLVM: llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT > Class Template Reference
llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/RPCUtils.h"
Public Member Functions
ResponseHandlerImpl (HandlerT Handler)
Error handleResponse (ChannelT &C) override
void abandon () override
Public Member Functions inherited from llvm::orc::rpc::detail::ResponseHandler< ChannelT >
virtual ~ResponseHandler ()
virtual Error handleResponse (ChannelT &C)=0
virtual void abandon ()=0
Additional Inherited Members
Static Public Member Functions inherited from llvm::orc::rpc::detail::ResponseHandler< ChannelT >
static Error createAbandonedResponseError ()
Detailed Description
template<typename ChannelT, typename HandlerT>
class llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >
Definition at line 674 of file RPCUtils.h.
Constructor & Destructor Documentation
ResponseHandlerImpl()
template<typename ChannelT , typename HandlerT > llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >::ResponseHandlerImpl (HandlerT Handler) inline
Definition at line 677 of file RPCUtils.h.
Member Function Documentation
abandon()
template<typename ChannelT , typename HandlerT > void llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >::abandon () inline override virtual
Implements llvm::orc::rpc::detail::ResponseHandler< ChannelT >.
Definition at line 690 of file RPCUtils.h.
References llvm::orc::rpc::detail::ResponseHandler< ChannelT >::createAbandonedResponseError(), and llvm::report_fatal_error().
handleResponse()
template<typename ChannelT , typename HandlerT > Error llvm::orc::rpc::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >::handleResponse (ChannelT & C) inline override virtual
Implements llvm::orc::rpc::detail::ResponseHandler< ChannelT >.
Definition at line 682 of file RPCUtils.h.
References C, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCUtils.h