LLVM: llvm::ExecutionEngineState Class Reference
llvm::ExecutionEngineState Class Reference
Helper class for helping synchronize access to the global address map table.
#include "llvm/ExecutionEngine/ExecutionEngine.h"
Public Types
using GlobalAddressMapTy = StringMap< uint64_t >
Public Member Functions
GlobalAddressMapTy & getGlobalAddressMap ()
std::map< uint64_t, std::string > & getGlobalAddressReverseMap ()
uint64_t RemoveMapping (StringRef Name)
Erase an entry from the mapping table.
Detailed Description
Helper class for helping synchronize access to the global address map table.
Access to this class should be serialized under a mutex.
Definition at line 65 of file ExecutionEngine.h.
Member Typedef Documentation
GlobalAddressMapTy
using llvm::ExecutionEngineState::GlobalAddressMapTy = StringMap<uint64_t>
Definition at line 67 of file ExecutionEngine.h.
Member Function Documentation
getGlobalAddressMap()
GlobalAddressMapTy & llvm::ExecutionEngineState::getGlobalAddressMap () inline
Definition at line 81 of file ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::ExecutionEngine::getGlobalValueAtAddress(), and llvm::ExecutionEngine::updateGlobalMapping().
getGlobalAddressReverseMap()
std::map< uint64_t, std::string > & llvm::ExecutionEngineState::getGlobalAddressReverseMap () inline
Definition at line 85 of file ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getGlobalValueAtAddress(), and llvm::ExecutionEngine::updateGlobalMapping().
RemoveMapping()
uint64_t ExecutionEngineState::RemoveMapping (StringRef Name)
Erase an entry from the mapping table.
Returns
The address that ToUnmap was happed to.
Definition at line 174 of file ExecutionEngine.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::erase(), llvm::StringMap< ValueTy, AllocatorTy >::find(), I, and Name.
Referenced by llvm::ExecutionEngine::clearGlobalMappingsFromModule(), and llvm::ExecutionEngine::updateGlobalMapping().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/ExecutionEngine.h
lib/ExecutionEngine/ExecutionEngine.cpp