LLVM: llvm::LazyValueInfo Class Reference
llvm::LazyValueInfo Class Reference
This pass computes, caches, and vends lazy value constraint information.
#include "llvm/Analysis/LazyValueInfo.h"
Public Types
enum Tristate { Unknown = -1 , False = 0 , True = 1 }
This is used to return true/false/dunno results.
Public Member Functions
~LazyValueInfo ()
LazyValueInfo ()
LazyValueInfo (AssumptionCache *AC_, const DataLayout *DL_, TargetLibraryInfo *TLI_, DominatorTree *DT_)
LazyValueInfo (LazyValueInfo &&Arg)
LazyValueInfo & operator= (LazyValueInfo &&Arg)
Tristate getPredicateOnEdge (unsigned Pred, Value *V, Constant *C, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Determine whether the specified value comparison with a constant is known to be true or false on the specified CFG edge.
Tristate getPredicateAt (unsigned Pred, Value *V, Constant *C, Instruction *CxtI)
Determine whether the specified value comparison with a constant is known to be true or false at the specified instruction (from an assume intrinsic).
Constant * getConstant (Value *V, BasicBlock *BB, Instruction *CxtI=nullptr)
Determine whether the specified value is known to be a constant at the end of the specified block.
ConstantRange getConstantRange (Value *V, BasicBlock *BB, Instruction *CxtI=nullptr)
Return the ConstantRange constraint that is known to hold for the specified value at the end of the specified block.
Constant * getConstantOnEdge (Value *V, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Determine whether the specified value is known to be a constant on the specified edge.
ConstantRange getConstantRangeOnEdge (Value *V, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Return the ConstantRage constraint that is known to hold for the specified value on the specified edge.
void threadEdge (BasicBlock *PredBB, BasicBlock *OldSucc, BasicBlock *NewSucc)
Inform the analysis cache that we have threaded an edge from PredBB to OldSucc to be from PredBB to NewSucc instead.
void eraseBlock (BasicBlock *BB)
Inform the analysis cache that we have erased a block.
void printLVI (Function &F, DominatorTree &DTree, raw_ostream &OS)
Print the \LazyValueInfo Analysis.
void disableDT ()
Disables use of the DominatorTree within LVI.
void enableDT ()
Enables use of the DominatorTree within LVI.
void releaseMemory ()
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events in the new pass manager.
Friends
class LazyValueInfoWrapperPass
Detailed Description
This pass computes, caches, and vends lazy value constraint information.
Definition at line 31 of file LazyValueInfo.h.
Member Enumeration Documentation
Tristate
enum llvm::LazyValueInfo::Tristate
This is used to return true/false/dunno results.
Enumerator
Unknown
False
True
Definition at line 62 of file LazyValueInfo.h.
Constructor & Destructor Documentation
~LazyValueInfo()
LazyValueInfo::~LazyValueInfo ()
Definition at line 1595 of file LazyValueInfo.cpp.
References releaseMemory().
LazyValueInfo() [1/3]
llvm::LazyValueInfo::LazyValueInfo () inline
Definition at line 42 of file LazyValueInfo.h.
LazyValueInfo() [2/3]
llvm::LazyValueInfo::LazyValueInfo (AssumptionCache * AC_, const DataLayout * DL_, TargetLibraryInfo * TLI_, DominatorTree * DT_) inline
Definition at line 43 of file LazyValueInfo.h.
LazyValueInfo() [3/3]
llvm::LazyValueInfo::LazyValueInfo (LazyValueInfo && Arg) inline
Definition at line 46 of file LazyValueInfo.h.
Member Function Documentation
disableDT()
void LazyValueInfo::disableDT ()
Disables use of the DominatorTree within LVI.
Definition at line 1920 of file LazyValueInfo.cpp.
References getImpl().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ThreadEdge(), and llvm::JumpThreadingPass::TryToUnfoldSelect().
enableDT()
void LazyValueInfo::enableDT ()
Enables use of the DominatorTree within LVI.
Does nothing if the class instance was initialized without a DT pointer.
Definition at line 1925 of file LazyValueInfo.cpp.
References getImpl().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::runImpl(), llvm::JumpThreadingPass::ThreadEdge(), and llvm::JumpThreadingPass::TryToUnfoldSelect().
eraseBlock()
void LazyValueInfo::eraseBlock (BasicBlock * BB)
Inform the analysis cache that we have erased a block.
Definition at line 1906 of file LazyValueInfo.cpp.
References llvm::Module::getDataLayout(), getImpl(), and llvm::BasicBlock::getModule().
Referenced by llvm::JumpThreadingPass::ProcessBlock(), llvm::removeUnreachableBlocks(), and llvm::JumpThreadingPass::runImpl().
getConstant()
Constant * LazyValueInfo::getConstant (Value * V, BasicBlock * BB, Instruction * CxtI = nullptr)
Determine whether the specified value is known to be a constant at the end of the specified block.
Return null if not.
Definition at line 1642 of file LazyValueInfo.cpp.
References llvm::DITypeRefArray::get(), llvm::ValueLatticeElement::getConstant(), llvm::ValueLatticeElement::getConstantRange(), llvm::Value::getContext(), llvm::Module::getDataLayout(), getImpl(), llvm::BasicBlock::getModule(), llvm::ConstantRange::getSingleElement(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), and isKnownNonConstant().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), getConstantAt(), processCallSite(), processMemAccess(), and processSelect().
getConstantOnEdge()
Constant * LazyValueInfo::getConstantOnEdge (Value * V, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value is known to be a constant on the specified edge.
Return null if not.
Definition at line 1682 of file LazyValueInfo.cpp.
References llvm::DITypeRefArray::get(), llvm::ValueLatticeElement::getConstant(), llvm::ValueLatticeElement::getConstantRange(), llvm::Value::getContext(), llvm::Module::getDataLayout(), getImpl(), llvm::BasicBlock::getModule(), llvm::ConstantRange::getSingleElement(), llvm::ValueLatticeElement::isConstant(), and llvm::ValueLatticeElement::isConstantRange().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), processPHI(), and simplifyCommonValuePhi().
getConstantRange()
ConstantRange LazyValueInfo::getConstantRange (Value * V, BasicBlock * BB, Instruction * CxtI = nullptr)
Return the ConstantRange constraint that is known to hold for the specified value at the end of the specified block.
This may only be called on integer-typed Values.
Definition at line 1662 of file LazyValueInfo.cpp.
References assert(), llvm::ValueLatticeElement::getConstant(), llvm::ValueLatticeElement::getConstantRange(), llvm::Module::getDataLayout(), getImpl(), llvm::Type::getIntegerBitWidth(), llvm::BasicBlock::getModule(), llvm::Value::getType(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), llvm::Type::isIntegerTy(), and llvm::ValueLatticeElement::isUndefined().
Referenced by processBinOp(), processUDivOrURem(), and willNotOverflow().
getConstantRangeOnEdge()
ConstantRange LazyValueInfo::getConstantRangeOnEdge (Value * V, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Return the ConstantRage constraint that is known to hold for the specified value on the specified edge.
This may be only be called on integer-typed Values.
Definition at line 1699 of file LazyValueInfo.cpp.
References assert(), llvm::ValueLatticeElement::getConstant(), llvm::ValueLatticeElement::getConstantRange(), llvm::Module::getDataLayout(), getImpl(), llvm::Type::getIntegerBitWidth(), llvm::BasicBlock::getModule(), llvm::Value::getType(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), and llvm::ValueLatticeElement::isUndefined().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl().
getPredicateAt()
LazyValueInfo::Tristate LazyValueInfo::getPredicateAt (unsigned Pred, Value * V, Constant * C, Instruction * CxtI)
Determine whether the specified value comparison with a constant is known to be true or false at the specified instruction (from an assume intrinsic).
Pred is a CmpInst predicate.
Definition at line 1798 of file LazyValueInfo.cpp.
References False, llvm::Module::getDataLayout(), getImpl(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), getPredicateOnEdge(), getPredicateResult(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isKnownNonZero(), llvm::Type::isPointerTy(), llvm::pred_begin(), llvm::pred_end(), llvm::Value::stripPointerCastsSameRepresentation(), True, and Unknown.
Referenced by getConstantAt(), hasPositiveOperands(), processAShr(), llvm::JumpThreadingPass::ProcessBlock(), processCallSite(), and processCmp().
getPredicateOnEdge()
LazyValueInfo::Tristate LazyValueInfo::getPredicateOnEdge (unsigned Pred, Value * V, Constant * C, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value comparison with a constant is known to be true or false on the specified CFG edge.
Pred is a CmpInst predicate.
Definition at line 1787 of file LazyValueInfo.cpp.
References llvm::Module::getDataLayout(), getImpl(), llvm::BasicBlock::getModule(), and getPredicateResult().
Referenced by llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), getPredicateAt(), processPHI(), processSwitch(), and llvm::JumpThreadingPass::TryToUnfoldSelect().
invalidate()
bool LazyValueInfo::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation events in the new pass manager.
Definition at line 1605 of file LazyValueInfo.cpp.
References F, llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
operator=()
LazyValueInfo & llvm::LazyValueInfo::operator= (LazyValueInfo && Arg) inline
Definition at line 50 of file LazyValueInfo.h.
References releaseMemory().
printLVI()
void LazyValueInfo::printLVI (Function & F, DominatorTree & DTree, raw_ostream & OS)
Print the \LazyValueInfo Analysis.
We pass in the DTree that is required for identifying which basic blocks we can solve/print for, in the LVIPrinter. The DT is optional in LVI, so we need to pass it here as an argument.
Definition at line 1914 of file LazyValueInfo.cpp.
References F, and getImpl().
releaseMemory()
void LazyValueInfo::releaseMemory ()
Definition at line 1597 of file LazyValueInfo.cpp.
References getImpl().
Referenced by operator=(), llvm::LazyValueInfoWrapperPass::releaseMemory(), and ~LazyValueInfo().
threadEdge()
void LazyValueInfo::threadEdge (BasicBlock * PredBB, BasicBlock * OldSucc, BasicBlock * NewSucc)
Inform the analysis cache that we have threaded an edge from PredBB to OldSucc to be from PredBB to NewSucc instead.
Definition at line 1898 of file LazyValueInfo.cpp.
References llvm::Module::getDataLayout(), getImpl(), and llvm::BasicBlock::getModule().
Referenced by llvm::JumpThreadingPass::ThreadEdge().
Friends And Related Function Documentation
LazyValueInfoWrapperPass
friend class LazyValueInfoWrapperPass friend
Definition at line 32 of file LazyValueInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyValueInfo.h
lib/Analysis/LazyValueInfo.cpp