LLVM: llvm::DIMacro Class Reference
llvm::DIMacro Class Reference
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIMacro,(unsigned MIType, unsigned Line, StringRef Name, StringRef Value=""),(MIType, Line, Name, Value)) DEFINE_MDNODE_GET(DIMacro
unsigned unsigned MDString MDString Value TempDIMacro clone () const
unsigned getLine () const
StringRef getName () const
StringRef getValue () const
MDString * getRawName () const
MDString * getRawValue () const
Public Member Functions inherited from llvm::DIMacroNode
unsigned getMacinfoType () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIMacroNode
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if< std::is_base_of< MDNode, T >::value, T * >::type replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned MIType
unsigned unsigned Line
unsigned unsigned MDString * Name
unsigned unsigned MDString MDString * Value
unsigned unsigned MDString MDString MIType
unsigned unsigned MDString MDString Line
unsigned unsigned MDString MDString Name
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIMacroNode
DIMacroNode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned MIType, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~DIMacroNode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~MDNode ()=default
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DIMacroNode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char ImplicitCode: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Definition at line 3139 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DIMacro::classof (const Metadata * MD) inline static
Definition at line 3183 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
unsigned unsigned MDString MDString Value TempDIMacro llvm::DIMacro::clone () const inline
Definition at line 3173 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DIMacro::DEFINE_MDNODE_GET (DIMacro , (unsigned MIType, unsigned Line, StringRef Name, StringRef Value="") , (MIType, Line, Name, Value))
getLine()
unsigned llvm::DIMacro::getLine () const inline
Definition at line 3175 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIMacro >::isKeyOf().
getName()
StringRef llvm::DIMacro::getName () const inline
Definition at line 3177 of file DebugInfoMetadata.h.
References llvm::DIMacroNode::getStringOperand().
getRawName()
MDString * llvm::DIMacro::getRawName () const inline
Definition at line 3180 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIMacro >::isKeyOf().
getRawValue()
MDString * llvm::DIMacro::getRawValue () const inline
Definition at line 3181 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIMacro >::isKeyOf().
getValue()
StringRef llvm::DIMacro::getValue () const inline
Definition at line 3178 of file DebugInfoMetadata.h.
References llvm::DIMacroNode::getStringOperand().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 3140 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 3141 of file DebugInfoMetadata.h.
Member Data Documentation
Line [1/2]
unsigned unsigned llvm::DIMacro::Line
Definition at line 3169 of file DebugInfoMetadata.h.
Line [2/2]
unsigned unsigned MDString MDString llvm::DIMacro::Line
Definition at line 3171 of file DebugInfoMetadata.h.
MIType [1/2]
unsigned llvm::DIMacro::MIType
Definition at line 3169 of file DebugInfoMetadata.h.
MIType [2/2]
unsigned unsigned MDString MDString llvm::DIMacro::MIType
Definition at line 3171 of file DebugInfoMetadata.h.
Name [1/2]
unsigned unsigned MDString* llvm::DIMacro::Name
Definition at line 3169 of file DebugInfoMetadata.h.
Name [2/2]
unsigned unsigned MDString MDString llvm::DIMacro::Name
Definition at line 3171 of file DebugInfoMetadata.h.
Value
unsigned unsigned MDString MDString* llvm::DIMacro::Value
Definition at line 3170 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp