LLVM: llvm::SCEVNAryExpr Class Reference
llvm::SCEVNAryExpr Class Reference
This node is a base class providing common functionality for n'ary operators.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Types
using op_iterator = const SCEV *const *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) - 1
}
NoWrapFlags are bitfield indices into SubclassData.
Public Member Functions
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
Type * getType () const
NoWrapFlags getNoWrapFlags (NoWrapFlags Mask=NoWrapMask) const
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
bool hasNoSelfWrap () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy, unsigned short ExpressionSize)
SCEV (const SCEV &)=delete
SCEV & operator= (const SCEV &)=delete
unsigned getSCEVType () const
Type * getType () const
Return the LLVM type of this SCEV expression.
bool isZero () const
Return true if the expression is a constant zero.
bool isOne () const
Return true if the expression is a constant one.
bool isAllOnesValue () const
Return true if the expression is a constant all-ones value.
bool isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
unsigned short getExpressionSize () const
void print (raw_ostream &OS) const
Print out the internal representation of this scalar to the specified stream.
void dump () const
This method is used for debugging.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Attributes
const SCEV *const * Operands
size_t NumOperands
Protected Attributes inherited from llvm::SCEV
const unsigned short ExpressionSize
unsigned short SubclassData = 0
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Detailed Description
This node is a base class providing common functionality for n'ary operators.
Definition at line 142 of file ScalarEvolutionExpressions.h.
Member Typedef Documentation
op_iterator
using llvm::SCEVNAryExpr::op_iterator = const SCEV *const *
Definition at line 164 of file ScalarEvolutionExpressions.h.
op_range
using llvm::SCEVNAryExpr::op_range = iterator_range<op_iterator>
Definition at line 165 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVNAryExpr()
llvm::SCEVNAryExpr::SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const * O, size_t N) inline protected
Definition at line 151 of file ScalarEvolutionExpressions.h.
Member Function Documentation
classof()
static bool llvm::SCEVNAryExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 192 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scMulExpr, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scUMaxExpr, and llvm::scUMinExpr.
getNoWrapFlags()
NoWrapFlags llvm::SCEVNAryExpr::getNoWrapFlags (NoWrapFlags Mask = NoWrapMask) const inline
Definition at line 175 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::SubclassData.
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::SCEVWrapPredicate::getImpliedFlags(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), hasNoSelfWrap(), hasNoSignedWrap(), hasNoUnsignedWrap(), llvm::SCEVWrapPredicate::isAlwaysTrue(), IsKnownPredicateViaAddRecStart(), isNoWrapAddRec(), llvm::SCEV::print(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), and llvm::SCEVLoopAddRecRewriter::visitAddRecExpr().
getNumOperands()
size_t llvm::SCEVNAryExpr::getNumOperands () const inline
Definition at line 157 of file ScalarEvolutionExpressions.h.
References NumOperands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), CompareSCEVComplexity(), llvm::SCEVAddRecExpr::evaluateAtIteration(), extractConstantWithoutWrapping(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPreStartForExtend(), GetQuadraticEquation(), llvm::SCEVAddExpr::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEVAddRecExpr::isAffine(), llvm::SCEVAddRecExpr::isQuadratic(), MatchNotExpr(), and llvm::SCEV::print().
getOperand()
const SCEV * llvm::SCEVNAryExpr::getOperand (unsigned i) const inline
Definition at line 159 of file ScalarEvolutionExpressions.h.
References assert(), NumOperands, and Operands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), CompareSCEVComplexity(), llvm::SCEVAddRecExpr::evaluateAtIteration(), extractConstantWithoutWrapping(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getPostIncExpr(), GetQuadraticEquation(), llvm::SCEVAddRecExpr::getStepRecurrence(), getStoreStride(), getType(), llvm::SCEVAddExpr::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEV::isNonConstantNegative(), MatchNotExpr(), llvm::SCEV::print(), and SolveQuadraticAddRecRange().
getType()
Type * llvm::SCEVNAryExpr::getType () const inline
Definition at line 173 of file ScalarEvolutionExpressions.h.
References getOperand(), and llvm::SCEV::getType().
Referenced by canBeCheaplyTransformed(), CollectSubexprs(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::SCEVExpander::generateOverflowCheck(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), isAddRecSExtable(), isExistingPhi(), IsIncrementNSW(), IsIncrementNUW(), mayUsePostIncMode(), and SolveQuadraticAddRecRange().
hasNoSelfWrap()
bool llvm::SCEVNAryExpr::hasNoSelfWrap () const inline
Definition at line 187 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNW, and getNoWrapFlags().
Referenced by llvm::SCEV::print().
hasNoSignedWrap()
bool llvm::SCEVNAryExpr::hasNoSignedWrap () const inline
Definition at line 183 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, and getNoWrapFlags().
Referenced by llvm::SCEV::print().
hasNoUnsignedWrap()
bool llvm::SCEVNAryExpr::hasNoUnsignedWrap () const inline
Definition at line 179 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNUW, and getNoWrapFlags().
Referenced by llvm::ScalarEvolution::getUDivExactExpr(), and llvm::SCEV::print().
op_begin()
op_iterator llvm::SCEVNAryExpr::op_begin () const inline
Definition at line 167 of file ScalarEvolutionExpressions.h.
References Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::OperandTraits< MemoryUseOrDef >::op_begin(), operands(), llvm::User::OpFrom(), and llvm::SCEV::print().
op_end()
op_iterator llvm::SCEVNAryExpr::op_end () const inline
Definition at line 168 of file ScalarEvolutionExpressions.h.
References NumOperands, and Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::OperandTraits< MemoryUseOrDef >::op_end(), operands(), llvm::User::OpFrom(), and llvm::SCEV::print().
operands()
op_range llvm::SCEVNAryExpr::operands () const inline
Definition at line 169 of file ScalarEvolutionExpressions.h.
References llvm::make_range(), op_begin(), and op_end().
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), llvm::SCEVLoopAddRecRewriter::visitAddRecExpr(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr(), and llvm::SCEVRewriteVisitor< SC >::visitUMinExpr().
Member Data Documentation
NumOperands
size_t llvm::SCEVNAryExpr::NumOperands protected
Definition at line 149 of file ScalarEvolutionExpressions.h.
Referenced by getNumOperands(), getOperand(), and op_end().
Operands
const SCEV* const* llvm::SCEVNAryExpr::Operands protected
Definition at line 148 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOperand(), llvm::SCEVAddRecExpr::getStart(), op_begin(), and op_end().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h