LLVM: llvm::object::WasmObjectFile Class Reference
llvm::object::WasmObjectFile Class Reference
#include "llvm/Object/Wasm.h"
Classes
struct ReadContext
Public Member Functions
WasmObjectFile (MemoryBufferRef Object, Error &Err)
const wasm::WasmObjectHeader & getHeader () const
const WasmSymbol & getWasmSymbol (const DataRefImpl &Symb) const
const WasmSymbol & getWasmSymbol (const SymbolRef &Symbol) const
const WasmSection & getWasmSection (const SectionRef &Section) const
const wasm::WasmRelocation & getWasmRelocation (const RelocationRef &Ref) const
const wasm::WasmDylinkInfo & dylinkInfo () const
const wasm::WasmProducerInfo & getProducerInfo () const
ArrayRef< wasm::WasmFeatureEntry > getTargetFeatures () const
ArrayRef< wasm::WasmSignature > types () const
ArrayRef< uint32_t > functionTypes () const
ArrayRef< wasm::WasmImport > imports () const
ArrayRef< wasm::WasmTable > tables () const
ArrayRef< wasm::WasmLimits > memories () const
ArrayRef< wasm::WasmGlobal > globals () const
ArrayRef< wasm::WasmEvent > events () const
ArrayRef< wasm::WasmExport > exports () const
ArrayRef< WasmSymbol > syms () const
const wasm::WasmLinkingData & linkingData () const
uint32_t getNumberOfSymbols () const
ArrayRef< wasm::WasmElemSegment > elements () const
ArrayRef< WasmSegment > dataSegments () const
ArrayRef< wasm::WasmFunction > functions () const
ArrayRef< wasm::WasmFunctionName > debugNames () const
uint32_t startFunction () const
uint32_t getNumImportedGlobals () const
uint32_t getNumImportedFunctions () const
uint32_t getNumImportedEvents () const
void moveSymbolNext (DataRefImpl &Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint64_t getWasmSymbolValue (const WasmSymbol &Sym) const
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool isSectionBitcode (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
SubtargetFeatures getFeatures () const override
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool isSharedObject () const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual SubtargetFeatures getFeatures () const =0
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static Expected< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static std::error_code checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_Minidump , ID_WinRes , ID_StartObjects , ID_COFF ,
ID_XCOFF32 , ID_XCOFF64 , ID_ELF32L , ID_ELF32B ,
ID_ELF64L , ID_ELF64B , ID_MachO32L , ID_MachO32B ,
ID_MachO64L , ID_MachO64B , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
uint64_t getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 118 of file Wasm.h.
Constructor & Destructor Documentation
WasmObjectFile()
WasmObjectFile::WasmObjectFile (MemoryBufferRef Object, Error & Err)
Definition at line 247 of file WasmObjectFile.cpp.
References llvm::StringRef::bytes_begin(), llvm::object::WasmObjectFile::ReadContext::End, llvm::object::Binary::getData(), llvm::wasm::WasmObjectHeader::Magic, llvm::object::parse_failed, llvm::object::WasmObjectFile::ReadContext::Ptr, readSection(), readUint32(), llvm::StringRef::size(), llvm::object::WasmObjectFile::ReadContext::Start, llvm::StringRef::substr(), llvm::wasm::WasmObjectHeader::Version, and llvm::wasm::WasmVersion.
Member Function Documentation
classof()
static bool llvm::object::WasmObjectFile::classof (const Binary * v) inline static
Definition at line 129 of file Wasm.h.
References llvm::object::Binary::isWasm().
dataSegments()
ArrayRef< WasmSegment > llvm::object::WasmObjectFile::dataSegments () const inline
Definition at line 148 of file Wasm.h.
debugNames()
ArrayRef< wasm::WasmFunctionName > llvm::object::WasmObjectFile::debugNames () const inline
Definition at line 150 of file Wasm.h.
dylinkInfo()
const wasm::WasmDylinkInfo & llvm::object::WasmObjectFile::dylinkInfo () const inline
Definition at line 131 of file Wasm.h.
elements()
ArrayRef< wasm::WasmElemSegment > llvm::object::WasmObjectFile::elements () const inline
Definition at line 147 of file Wasm.h.
events()
ArrayRef< wasm::WasmEvent > llvm::object::WasmObjectFile::events () const inline
Definition at line 142 of file Wasm.h.
exports()
ArrayRef< wasm::WasmExport > llvm::object::WasmObjectFile::exports () const inline
Definition at line 143 of file Wasm.h.
functions()
ArrayRef< wasm::WasmFunction > llvm::object::WasmObjectFile::functions () const inline
Definition at line 149 of file Wasm.h.
functionTypes()
ArrayRef< uint32_t > llvm::object::WasmObjectFile::functionTypes () const inline
Definition at line 137 of file Wasm.h.
getArch()
Triple::ArchType WasmObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1532 of file WasmObjectFile.cpp.
References llvm::Triple::wasm32.
getBytesInAddress()
uint8_t WasmObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 1528 of file WasmObjectFile.cpp.
getCommonSymbolSizeImpl()
uint64_t WasmObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1335 of file WasmObjectFile.cpp.
References llvm_unreachable.
getFeatures()
SubtargetFeatures WasmObjectFile::getFeatures () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1534 of file WasmObjectFile.cpp.
getFileFormatName()
StringRef WasmObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1530 of file WasmObjectFile.cpp.
getHeader()
const wasm::WasmObjectHeader & WasmObjectFile::getHeader () const
Definition at line 1247 of file WasmObjectFile.cpp.
getNumberOfSymbols()
uint32_t llvm::object::WasmObjectFile::getNumberOfSymbols () const inline
Definition at line 146 of file Wasm.h.
getNumImportedEvents()
uint32_t llvm::object::WasmObjectFile::getNumImportedEvents () const inline
Definition at line 154 of file Wasm.h.
getNumImportedFunctions()
uint32_t llvm::object::WasmObjectFile::getNumImportedFunctions () const inline
Definition at line 153 of file Wasm.h.
getNumImportedGlobals()
uint32_t llvm::object::WasmObjectFile::getNumImportedGlobals () const inline
Definition at line 152 of file Wasm.h.
getProducerInfo()
const wasm::WasmProducerInfo & llvm::object::WasmObjectFile::getProducerInfo () const inline
Definition at line 132 of file Wasm.h.
getRelocationOffset()
uint64_t WasmObjectFile::getRelocationOffset (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1477 of file WasmObjectFile.cpp.
References getWasmRelocation(), llvm::wasm::WasmRelocation::Offset, and llvm::Ref.
getRelocationSymbol()
symbol_iterator WasmObjectFile::getRelocationSymbol (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1482 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, getWasmRelocation(), llvm::wasm::WasmRelocation::Index, llvm::Ref, symbol_end(), llvm::object::ObjectFile::SymbolRef, and llvm::wasm::WasmRelocation::Type.
getRelocationType()
uint64_t WasmObjectFile::getRelocationType (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1492 of file WasmObjectFile.cpp.
References getWasmRelocation(), llvm::Ref, and llvm::wasm::WasmRelocation::Type.
getRelocationTypeName()
void WasmObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1497 of file WasmObjectFile.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), getWasmRelocation(), llvm::Ref, and llvm::wasm::WasmRelocation::Type.
getSectionAddress()
uint64_t WasmObjectFile::getSectionAddress (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1419 of file WasmObjectFile.cpp.
getSectionAlignment()
uint64_t WasmObjectFile::getSectionAlignment (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1438 of file WasmObjectFile.cpp.
getSectionContents()
Expected< ArrayRef< uint8_t > > WasmObjectFile::getSectionContents (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1431 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::WasmSection::Content, and llvm::object::DataRefImpl::d.
getSectionIndex()
uint64_t WasmObjectFile::getSectionIndex (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1421 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
getSectionName()
Expected< StringRef > WasmObjectFile::getSectionName (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1392 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::createStringError(), llvm::object::DataRefImpl::d, ECase, llvm::object::invalid_section_index, llvm::object::WasmSection::Name, llvm::object::WasmSection::Type, and llvm::wasm::WASM_SEC_CUSTOM.
getSectionSize()
uint64_t WasmObjectFile::getSectionSize (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1425 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::WasmSection::Content, llvm::object::DataRefImpl::d, and llvm::ArrayRef< T >::size().
getSymbolAddress()
Expected< uint64_t > WasmObjectFile::getSymbolAddress (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1297 of file WasmObjectFile.cpp.
References llvm::wasm::WasmFunction::CodeSectionOffset, llvm::object::ObjectFile::getSymbolValue(), getWasmSymbol(), and llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION.
getSymbolAlignment()
uint32_t WasmObjectFile::getSymbolAlignment (DataRefImpl Symb) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1330 of file WasmObjectFile.cpp.
References llvm_unreachable.
getSymbolFlags()
uint32_t WasmObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1253 of file WasmObjectFile.cpp.
References llvm::dbgs(), getWasmSymbol(), llvm::object::WasmSymbol::isBindingLocal(), llvm::object::WasmSymbol::isBindingWeak(), llvm::object::WasmSymbol::isDefined(), llvm::object::WasmSymbol::isHidden(), llvm::object::WasmSymbol::isTypeFunction(), LLVM_DEBUG, llvm::object::BasicSymbolRef::SF_Executable, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Hidden, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
getSymbolName()
Expected< StringRef > WasmObjectFile::getSymbolName (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1293 of file WasmObjectFile.cpp.
References getWasmSymbol(), llvm::object::WasmSymbol::Info, and llvm::wasm::WasmSymbolInfo::Name.
getSymbolSection()
Expected< section_iterator > WasmObjectFile::getSymbolSection (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1362 of file WasmObjectFile.cpp.
References llvm::wasm::WasmSymbolInfo::ElementIndex, getWasmSymbol(), llvm::object::WasmSymbol::Info, llvm::object::WasmSymbol::isUndefined(), llvm::wasm::WasmSymbolInfo::Kind, llvm_unreachable, llvm::Ref, section_end(), llvm::object::ObjectFile::SectionRef, llvm::wasm::WASM_SYMBOL_TYPE_DATA, llvm::wasm::WASM_SYMBOL_TYPE_EVENT, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL, and llvm::wasm::WASM_SYMBOL_TYPE_SECTION.
getSymbolType()
Expected< SymbolRef::Type > WasmObjectFile::getSymbolType (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1341 of file WasmObjectFile.cpp.
References getWasmSymbol(), llvm::object::WasmSymbol::Info, llvm::wasm::WasmSymbolInfo::Kind, llvm_unreachable, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::wasm::WASM_SYMBOL_TYPE_DATA, llvm::wasm::WASM_SYMBOL_TYPE_EVENT, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL, and llvm::wasm::WASM_SYMBOL_TYPE_SECTION.
getSymbolValueImpl()
uint64_t WasmObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1326 of file WasmObjectFile.cpp.
References getWasmSymbol(), and getWasmSymbolValue().
getTargetFeatures()
ArrayRef< wasm::WasmFeatureEntry > llvm::object::WasmObjectFile::getTargetFeatures () const inline
Definition at line 133 of file Wasm.h.
getWasmRelocation()
const wasm::WasmRelocation & WasmObjectFile::getWasmRelocation (const RelocationRef & Ref) const
Definition at line 1553 of file WasmObjectFile.cpp.
References getWasmRelocation(), and llvm::Ref.
Referenced by getRelocationOffset(), getRelocationSymbol(), getRelocationType(), getRelocationTypeName(), and getWasmRelocation().
getWasmSection()
const WasmSection & WasmObjectFile::getWasmSection (const SectionRef & Section) const
Definition at line 1548 of file WasmObjectFile.cpp.
References getWasmSection().
Referenced by getWasmSection(), isSectionData(), isSectionText(), and section_rel_end().
getWasmSymbol() [1/2]
const WasmSymbol & WasmObjectFile::getWasmSymbol (const DataRefImpl & Symb) const
Definition at line 1285 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
Referenced by getSymbolAddress(), getSymbolFlags(), getSymbolName(), getSymbolSection(), getSymbolType(), getSymbolValueImpl(), and getWasmSymbol().
getWasmSymbol() [2/2]
const WasmSymbol & WasmObjectFile::getWasmSymbol (const SymbolRef & Symbol) const
Definition at line 1289 of file WasmObjectFile.cpp.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and getWasmSymbol().
getWasmSymbolValue()
uint64_t WasmObjectFile::getWasmSymbolValue (const WasmSymbol & Sym) const
Definition at line 1306 of file WasmObjectFile.cpp.
References assert(), llvm::wasm::WasmSymbolInfo::DataRef, llvm::wasm::WasmSymbolInfo::ElementIndex, llvm::object::WasmSymbol::Info, llvm::wasm::WasmInitExpr::Int32, llvm::wasm::WasmSymbolInfo::Kind, llvm_unreachable, llvm::wasm::WasmDataSegment::Offset, llvm::wasm::WasmDataReference::Offset, llvm::wasm::WasmInitExpr::Opcode, llvm::wasm::WasmDataReference::Segment, llvm::wasm::WasmInitExpr::Value, llvm::wasm::WASM_OPCODE_I32_CONST, llvm::wasm::WASM_SYMBOL_TYPE_DATA, llvm::wasm::WASM_SYMBOL_TYPE_EVENT, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL, and llvm::wasm::WASM_SYMBOL_TYPE_SECTION.
Referenced by getSymbolValueImpl().
globals()
ArrayRef< wasm::WasmGlobal > llvm::object::WasmObjectFile::globals () const inline
Definition at line 141 of file Wasm.h.
imports()
ArrayRef< wasm::WasmImport > llvm::object::WasmObjectFile::imports () const inline
Definition at line 138 of file Wasm.h.
isRelocatableObject()
bool WasmObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1538 of file WasmObjectFile.cpp.
isSectionBitcode()
bool WasmObjectFile::isSectionBitcode (DataRefImpl Sec) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1458 of file WasmObjectFile.cpp.
isSectionBSS()
bool WasmObjectFile::isSectionBSS (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1454 of file WasmObjectFile.cpp.
isSectionCompressed()
bool WasmObjectFile::isSectionCompressed (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1442 of file WasmObjectFile.cpp.
isSectionData()
bool WasmObjectFile::isSectionData (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1450 of file WasmObjectFile.cpp.
References getWasmSection(), llvm::object::WasmSection::Type, and llvm::wasm::WASM_SEC_DATA.
isSectionText()
bool WasmObjectFile::isSectionText (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1446 of file WasmObjectFile.cpp.
References getWasmSection(), llvm::object::WasmSection::Type, and llvm::wasm::WASM_SEC_CODE.
isSectionVirtual()
bool WasmObjectFile::isSectionVirtual (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1456 of file WasmObjectFile.cpp.
isSharedObject()
bool WasmObjectFile::isSharedObject () const
Definition at line 1540 of file WasmObjectFile.cpp.
linkingData()
const wasm::WasmLinkingData & llvm::object::WasmObjectFile::linkingData () const inline
Definition at line 145 of file Wasm.h.
memories()
ArrayRef< wasm::WasmLimits > llvm::object::WasmObjectFile::memories () const inline
Definition at line 140 of file Wasm.h.
moveRelocationNext()
void WasmObjectFile::moveRelocationNext (DataRefImpl & Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1475 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
moveSectionNext()
void WasmObjectFile::moveSectionNext (DataRefImpl & Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1390 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
moveSymbolNext()
void WasmObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1251 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
section_begin()
section_iterator WasmObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1516 of file WasmObjectFile.cpp.
References llvm::Ref, and llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator WasmObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1522 of file WasmObjectFile.cpp.
References llvm::Ref, and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection().
section_rel_begin()
relocation_iterator WasmObjectFile::section_rel_begin (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1460 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::Ref, and llvm::object::ObjectFile::RelocationRef.
section_rel_end()
relocation_iterator WasmObjectFile::section_rel_end (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1467 of file WasmObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, getWasmSection(), llvm::Ref, llvm::object::ObjectFile::RelocationRef, and llvm::object::WasmSection::Relocations.
startFunction()
uint32_t llvm::object::WasmObjectFile::startFunction () const inline
Definition at line 151 of file Wasm.h.
symbol_begin()
basic_symbol_iterator WasmObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1271 of file WasmObjectFile.cpp.
References llvm::Ref.
symbol_end()
basic_symbol_iterator WasmObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1278 of file WasmObjectFile.cpp.
References llvm::Ref.
Referenced by getRelocationSymbol().
syms()
ArrayRef< WasmSymbol > llvm::object::WasmObjectFile::syms () const inline
Definition at line 144 of file Wasm.h.
tables()
ArrayRef< wasm::WasmTable > llvm::object::WasmObjectFile::tables () const inline
Definition at line 139 of file Wasm.h.
types()
ArrayRef< wasm::WasmSignature > llvm::object::WasmObjectFile::types () const inline
Definition at line 136 of file Wasm.h.
The documentation for this class was generated from the following files:
include/llvm/Object/Wasm.h
lib/Object/WasmObjectFile.cpp