LLVM: llvm::pdb::InjectedSourceStream Class Reference
llvm::pdb::InjectedSourceStream Class Reference
#include "llvm/DebugInfo/PDB/Native/InjectedSourceStream.h"
Public Types
using const_iterator = HashTable< SrcHeaderBlockEntry >::const_iterator
Public Member Functions
InjectedSourceStream (std::unique_ptr< msf::MappedBlockStream > Stream)
Error reload (const PDBStringTable &Strings)
const_iterator begin () const
const_iterator end () const
uint32_t size () const
Detailed Description
Definition at line 24 of file InjectedSourceStream.h.
Member Typedef Documentation
const_iterator
using llvm::pdb::InjectedSourceStream::const_iterator = HashTable<SrcHeaderBlockEntry>::const_iterator
Definition at line 29 of file InjectedSourceStream.h.
Constructor & Destructor Documentation
InjectedSourceStream()
InjectedSourceStream::InjectedSourceStream (std::unique_ptr< msf::MappedBlockStream > Stream)
Definition at line 24 of file InjectedSourceStream.cpp.
Member Function Documentation
begin()
const_iterator llvm::pdb::InjectedSourceStream::begin () const inline
Definition at line 30 of file InjectedSourceStream.h.
References llvm::pdb::HashTable< ValueT >::begin().
end()
const_iterator llvm::pdb::InjectedSourceStream::end () const inline
Definition at line 31 of file InjectedSourceStream.h.
References llvm::pdb::HashTable< ValueT >::end().
reload()
Error InjectedSourceStream::reload (const PDBStringTable & Strings)
Definition at line 28 of file InjectedSourceStream.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::pdb::corrupt_file, llvm::pdb::PDBStringTable::getStringForID(), llvm::pdb::HashTable< ValueT >::load(), Name, llvm::BinaryStreamReader::readObject(), llvm::pdb::SrcVerOne, llvm::Error::success(), and llvm::pdb::SrcHeaderBlockHeader::Version.
size()
uint32_t llvm::pdb::InjectedSourceStream::size () const inline
Definition at line 33 of file InjectedSourceStream.h.
References llvm::pdb::HashTable< ValueT >::size().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/InjectedSourceStream.h
lib/DebugInfo/PDB/Native/InjectedSourceStream.cpp