LLVM: llvm::DWARFDie::attribute_iterator Class Reference
llvm::DWARFDie::attribute_iterator Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
Public Member Functions
attribute_iterator ()=delete
attribute_iterator (DWARFDie D, bool End)
attribute_iterator & operator++ ()
attribute_iterator & operator-- ()
operator bool () const
const DWARFAttribute & operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< attribute_iterator, std::forward_iterator_tag, const DWARFAttribute >
attribute_iterator operator+ (std::ptrdiff_t n) const
attribute_iterator operator- (std::ptrdiff_t n) const
attribute_iterator & operator++ ()
attribute_iterator operator++ (int)
attribute_iterator & operator-- ()
attribute_iterator operator-- (int)
bool operator!= (const attribute_iterator &RHS) const
bool operator> (const attribute_iterator &RHS) const
bool operator<= (const attribute_iterator &RHS) const
bool operator>= (const attribute_iterator &RHS) const
const DWARFAttribute * operator-> ()
const DWARFAttribute * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Friends
bool operator== (const attribute_iterator &LHS, const attribute_iterator &RHS)
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< attribute_iterator, std::forward_iterator_tag, const DWARFAttribute >
enum
Detailed Description
Definition at line 282 of file DWARFDie.h.
Constructor & Destructor Documentation
attribute_iterator() [1/2]
llvm::DWARFDie::attribute_iterator::attribute_iterator () delete
attribute_iterator() [2/2]
DWARFDie::attribute_iterator::attribute_iterator (DWARFDie D, bool End) explicit
Definition at line 665 of file DWARFDie.cpp.
References assert(), D, llvm::DWARFDie::getAbbreviationDeclarationPtr(), and llvm::DWARFAttribute::Offset.
Member Function Documentation
operator bool()
llvm::DWARFDie::attribute_iterator::operator bool () const inline explicit
Definition at line 308 of file DWARFDie.h.
References llvm::DWARFAttribute::isValid().
operator*()
const DWARFAttribute & llvm::DWARFDie::attribute_iterator::operator* () const inline
Definition at line 309 of file DWARFDie.h.
operator++()
DWARFDie::attribute_iterator & DWARFDie::attribute_iterator::operator++ ()
Definition at line 700 of file DWARFDie.cpp.
References llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr().
operator--()
attribute_iterator & llvm::DWARFDie::attribute_iterator::operator-- ()
Friends And Related Function Documentation
operator==
bool operator== (const attribute_iterator & LHS, const attribute_iterator & RHS) friend
Definition at line 312 of file DWARFDie.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDie.h
lib/DebugInfo/DWARF/DWARFDie.cpp