LLVM: llvm::SCEVEqualPredicate Class Reference
llvm::SCEVEqualPredicate Class Reference final
This class represents an assumption that two SCEV expressions are equal, and this can be checked at run-time.
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
SCEVEqualPredicate (const FoldingSetNodeIDRef ID, const SCEV *LHS, const SCEV *RHS)
bool implies (const SCEVPredicate *N) const override
Implementation of the SCEVPredicate interface.
void print (raw_ostream &OS, unsigned Depth=0) const override
Prints a textual representation of this predicate with an indentation of Depth.
bool isAlwaysTrue () const override
Returns true if the predicate is always true.
const SCEV * getExpr () const override
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
const SCEV * getLHS () const
Returns the left hand side of the equality.
const SCEV * getRHS () const
Returns the right hand side of the equality.
Public Member Functions inherited from llvm::SCEVPredicate
SCEVPredicate (const FoldingSetNodeIDRef ID, SCEVPredicateKind Kind)
SCEV predicates.
SCEVPredicateKind getKind () const
virtual unsigned getComplexity () const
Returns the estimated complexity of this predicate.
virtual bool isAlwaysTrue () const =0
Returns true if the predicate is always true.
virtual bool implies (const SCEVPredicate *N) const =0
Returns true if this predicate implies N.
virtual void print (raw_ostream &OS, unsigned Depth=0) const =0
Prints a textual representation of this predicate with an indentation of Depth.
virtual const SCEV * getExpr () const =0
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Static Public Member Functions
static bool classof (const SCEVPredicate *P)
Methods for support type inquiry through isa, cast, and dyn_cast:
Additional Inherited Members
Public Types inherited from llvm::SCEVPredicate
enum SCEVPredicateKind { P_Union , P_Equal , P_Wrap }
Protected Member Functions inherited from llvm::SCEVPredicate
~SCEVPredicate ()=default
SCEVPredicate (const SCEVPredicate &)=default
SCEVPredicate & operator= (const SCEVPredicate &)=default
Protected Attributes inherited from llvm::SCEVPredicate
SCEVPredicateKind Kind
Detailed Description
This class represents an assumption that two SCEV expressions are equal, and this can be checked at run-time.
Definition at line 265 of file ScalarEvolution.h.
Constructor & Destructor Documentation
SCEVEqualPredicate()
SCEVEqualPredicate::SCEVEqualPredicate (const FoldingSetNodeIDRef ID, const SCEV * LHS, const SCEV * RHS)
Definition at line 12170 of file ScalarEvolution.cpp.
References assert(), and llvm::SCEV::getType().
Member Function Documentation
classof()
static bool llvm::SCEVEqualPredicate::classof (const SCEVPredicate * P) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 287 of file ScalarEvolution.h.
References P, and llvm::SCEVPredicate::P_Equal.
getExpr()
const SCEV * SCEVEqualPredicate::getExpr () const override virtual
Returns the SCEV to which this predicate applies, or nullptr if this is a SCEVUnionPredicate.
Implements llvm::SCEVPredicate.
Definition at line 12188 of file ScalarEvolution.cpp.
getLHS()
const SCEV * llvm::SCEVEqualPredicate::getLHS () const inline
Returns the left hand side of the equality.
Definition at line 281 of file ScalarEvolution.h.
Referenced by llvm::SCEVExpander::expandEqualPredicate().
getRHS()
const SCEV * llvm::SCEVEqualPredicate::getRHS () const inline
Returns the right hand side of the equality.
Definition at line 284 of file ScalarEvolution.h.
Referenced by llvm::SCEVExpander::expandEqualPredicate().
implies()
bool SCEVEqualPredicate::implies (const SCEVPredicate * N) const override virtual
Implementation of the SCEVPredicate interface.
Implements llvm::SCEVPredicate.
Definition at line 12177 of file ScalarEvolution.cpp.
References N.
isAlwaysTrue()
bool SCEVEqualPredicate::isAlwaysTrue () const override virtual
Returns true if the predicate is always true.
This means that no assumptions were made and nothing needs to be checked at run-time.
Implements llvm::SCEVPredicate.
Definition at line 12186 of file ScalarEvolution.cpp.
print()
void SCEVEqualPredicate::print (raw_ostream & OS, unsigned Depth = 0) const override virtual
Prints a textual representation of this predicate with an indentation of Depth.
Implements llvm::SCEVPredicate.
Definition at line 12190 of file ScalarEvolution.cpp.
References llvm::raw_ostream::indent().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp