LLVM: llvm::MachineModuleInfo Class Reference
llvm::MachineModuleInfo Class Reference
This class contains meta information specific to a module.
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Member Functions
MachineModuleInfo (const LLVMTargetMachine *TM=nullptr)
~MachineModuleInfo () override
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
bool doFinalization (Module &) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
const LLVMTargetMachine & getTarget () const
const MCContext & getContext () const
MCContext & getContext ()
const Module * getModule () const
MachineFunction & getOrCreateMachineFunction (const Function &F)
Returns the MachineFunction constructed for the IR function F.
MachineFunction * getMachineFunction (const Function &F) const
\bried Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
void deleteMachineFunctionFor (Function &F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
template<typename Ty >
Ty & getObjFileInfo ()
Keep track of various per-function pieces of information for backends that would like to do so.
template<typename Ty >
const Ty & getObjFileInfo () const
bool hasDebugInfo () const
Returns true if valid debug info is present.
void setDebugInfoAvailability (bool avail)
bool usesMSVCFloatingPoint () const
void setUsesMSVCFloatingPoint (bool b)
bool usesMorestackAddr () const
void setUsesMorestackAddr (bool b)
bool hasSplitStack () const
void setHasSplitStack (bool b)
bool hasNosplitStack () const
void setHasNosplitStack (bool b)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Exception Handling
void setCurrentCallSite (unsigned Site)
Set the call site currently being processed.
unsigned getCurrentCallSite ()
Get the call site currently being processed, if any.
void addPersonality (const Function *Personality)
Provide the personality function for the exception information.
const std::vector< const Function * > & getPersonalities () const
Return array of personality functions ever seen.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
This class contains meta information specific to a module.
Queries can be made by different debugging and exception handling schemes and reformated for specific use.
Definition at line 77 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
MachineModuleInfo()
MachineModuleInfo::MachineModuleInfo (const LLVMTargetMachine * TM = nullptr) explicit
Definition at line 196 of file MachineModuleInfo.cpp.
References Context, llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineModuleInfoPass().
~MachineModuleInfo()
MachineModuleInfo::~MachineModuleInfo () override default
Member Function Documentation
addPersonality()
void MachineModuleInfo::addPersonality (const Function * Personality)
Provide the personality function for the exception information.
Definition at line 252 of file MachineModuleInfo.cpp.
Referenced by llvm::MachineFunction::addLandingPad(), and llvm::DwarfCFIException::beginFragment().
deleteMachineFunctionFor()
void MachineModuleInfo::deleteMachineFunctionFor (Function & F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
Definition at line 292 of file MachineModuleInfo.cpp.
References F.
doFinalization()
bool MachineModuleInfo::doFinalization (Module &) override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 216 of file MachineModuleInfo.cpp.
References llvm::MCContext::reset().
doInitialization()
bool MachineModuleInfo::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 205 of file MachineModuleInfo.cpp.
References llvm::empty().
getAddrLabelSymbol()
MCSymbol * llvm::MachineModuleInfo::getAddrLabelSymbol (const BasicBlock * BB) inline
Return the symbol to be used for the specified basic block when its address is taken.
This cannot be its normal LBB label because the block may be accessed outside its containing function.
Definition at line 221 of file MachineModuleInfo.h.
References getAddrLabelSymbolToEmit().
Referenced by llvm::AsmPrinter::GetBlockAddressSymbol().
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > MachineModuleInfo::getAddrLabelSymbolToEmit (const BasicBlock * BB)
Return the symbol to be used for the specified basic block when its address is taken.
If other blocks were RAUW'd to this one, we may have to emit them as well, return the whole set.
Definition at line 233 of file MachineModuleInfo.cpp.
References llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit().
Referenced by llvm::AsmPrinter::EmitBasicBlockStart(), and getAddrLabelSymbol().
getContext() [1/2]
MCContext & llvm::MachineModuleInfo::getContext () inline
Definition at line 156 of file MachineModuleInfo.h.
References Context.
getContext() [2/2]
const MCContext & llvm::MachineModuleInfo::getContext () const inline
Definition at line 155 of file MachineModuleInfo.h.
References Context.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::DwarfCFIException::beginFunction(), llvm::DebugHandlerBase::beginInstruction(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), EmitGCCInlineAsmStr(), emitNonLazyStubs(), llvm::AArch64FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::DebugHandlerBase::endInstruction(), llvm::SelectionDAGBuilder::lowerInvokable(), and recoverFramePointer().
getCurrentCallSite()
unsigned llvm::MachineModuleInfo::getCurrentCallSite () inline
Get the call site currently being processed, if any.
return zero if none.
Definition at line 245 of file MachineModuleInfo.h.
Referenced by llvm::SelectionDAGBuilder::lowerInvokable().
getMachineFunction()
MachineFunction * MachineModuleInfo::getMachineFunction (const Function & F) const
\bried Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
Definition at line 262 of file MachineModuleInfo.cpp.
References F, and I.
Referenced by llvm::AArch64InstrInfo::getOutliningType(), and llvm::MIRParserImpl::parseMachineFunction().
getModule()
const Module * llvm::MachineModuleInfo::getModule () const inline
Definition at line 158 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::AMDGPUMachineModuleInfo::AMDGPUMachineModuleInfo(), llvm::DwarfDebug::beginModule(), llvm::CodeViewDebug::CodeViewDebug(), llvm::AsmPrinter::doInitialization(), llvm::DwarfDebug::DwarfDebug(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), llvm::X86FrameLowering::emitPrologue(), llvm::WinCFGuard::endModule(), llvm::WinException::endModule(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), and llvm::X86AsmPrinter::runOnMachineFunction().
getObjFileInfo() [1/2]
template<typename Ty > Ty & llvm::MachineModuleInfo::getObjFileInfo () inline
Keep track of various per-function pieces of information for backends that would like to do so.
Definition at line 175 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), emitNonLazyStubs(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getMachOMMI(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and llvm::SparcELFTargetObjectFile::getTTypeGlobalReference().
getObjFileInfo() [2/2]
template<typename Ty > const Ty & llvm::MachineModuleInfo::getObjFileInfo () const inline
Definition at line 182 of file MachineModuleInfo.h.
getOrCreateMachineFunction()
MachineFunction & MachineModuleInfo::getOrCreateMachineFunction (const Function & F)
Returns the MachineFunction constructed for the IR function F.
Creates a new MachineFunction if none exists yet.
Definition at line 268 of file MachineModuleInfo.cpp.
References F, llvm::TargetMachine::getSubtargetImpl(), and I.
Referenced by llvm::MIRParserImpl::parseMachineFunction().
getPersonalities()
const std::vector< const Function * > & llvm::MachineModuleInfo::getPersonalities () const inline
Return array of personality functions ever seen.
Definition at line 251 of file MachineModuleInfo.h.
Referenced by llvm::DwarfCFIException::endModule().
getTarget()
const LLVMTargetMachine & llvm::MachineModuleInfo::getTarget () const inline
Definition at line 153 of file MachineModuleInfo.h.
Referenced by llvm::MIRParserImpl::parseMachineFunction().
hasDebugInfo()
bool llvm::MachineModuleInfo::hasDebugInfo () const inline
Returns true if valid debug info is present.
Definition at line 187 of file MachineModuleInfo.h.
Referenced by llvm::DebugHandlerBase::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitEpilogue(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::DebugHandlerBase::endInstruction(), llvm::CodeViewDebug::endModule(), llvm::DwarfDebug::endModule(), ExpandMOVImmSExti8(), hasDebugInfo(), needFuncLabelsForEHOrDebugInfo(), llvm::AsmPrinter::needsCFIMoves(), llvm::ARCRegisterInfo::needsFrameMoves(), llvm::XCoreRegisterInfo::needsFrameMoves(), and llvm::FastISel::selectIntrinsicCall().
hasNosplitStack()
bool llvm::MachineModuleInfo::hasNosplitStack () const inline
Definition at line 210 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
hasSplitStack()
bool llvm::MachineModuleInfo::hasSplitStack () const inline
Definition at line 202 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
setCurrentCallSite()
void llvm::MachineModuleInfo::setCurrentCallSite (unsigned Site) inline
Set the call site currently being processed.
Definition at line 241 of file MachineModuleInfo.h.
Referenced by llvm::SelectionDAGBuilder::lowerInvokable().
setDebugInfoAvailability()
void llvm::MachineModuleInfo::setDebugInfoAvailability (bool avail) inline
Definition at line 188 of file MachineModuleInfo.h.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::CodeViewDebug::CodeViewDebug().
setHasNosplitStack()
void llvm::MachineModuleInfo::setHasNosplitStack (bool b) inline
Definition at line 214 of file MachineModuleInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
setHasSplitStack()
void llvm::MachineModuleInfo::setHasSplitStack (bool b) inline
Definition at line 206 of file MachineModuleInfo.h.
setUsesMorestackAddr()
void llvm::MachineModuleInfo::setUsesMorestackAddr (bool b) inline
Definition at line 198 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
setUsesMSVCFloatingPoint()
void llvm::MachineModuleInfo::setUsesMSVCFloatingPoint (bool b) inline
Definition at line 192 of file MachineModuleInfo.h.
Referenced by computeUsesMSVCFloatingPoint().
takeDeletedSymbolsForFunction()
void MachineModuleInfo::takeDeletedSymbolsForFunction (const Function * F, std::vector< MCSymbol * > & Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
This prevents emitting a reference to a symbol that has no definition.
Definition at line 240 of file MachineModuleInfo.cpp.
References F, and takeDeletedSymbolsForFunction().
Referenced by takeDeletedSymbolsForFunction().
usesMorestackAddr()
bool llvm::MachineModuleInfo::usesMorestackAddr () const inline
Definition at line 194 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
usesMSVCFloatingPoint()
bool llvm::MachineModuleInfo::usesMSVCFloatingPoint () const inline
Definition at line 190 of file MachineModuleInfo.h.
Referenced by computeUsesMSVCFloatingPoint(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
Member Data Documentation
ID
char llvm::MachineModuleInfo::ID static
Definition at line 144 of file MachineModuleInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp