LLVM: llvm::sampleprof::FunctionSamples Class Reference
llvm::sampleprof::FunctionSamples Class Reference
Representation of the samples collected for a function.
#include "llvm/ProfileData/SampleProf.h"
Classes
class GUIDToFuncNameMapper
Public Member Functions
FunctionSamples ()=default
void print (raw_ostream &OS=dbgs(), unsigned Indent=0) const
Print the samples collected for a function on stream OS.
void dump () const
sampleprof_error addTotalSamples (uint64_t Num, uint64_t Weight=1)
sampleprof_error addHeadSamples (uint64_t Num, uint64_t Weight=1)
sampleprof_error addBodySamples (uint32_t LineOffset, uint32_t Discriminator, uint64_t Num, uint64_t Weight=1)
sampleprof_error addCalledTargetSamples (uint32_t LineOffset, uint32_t Discriminator, StringRef FName, uint64_t Num, uint64_t Weight=1)
ErrorOr< uint64_t > findSamplesAt (uint32_t LineOffset, uint32_t Discriminator) const
Return the number of samples collected at the given location.
ErrorOr< SampleRecord::CallTargetMap > findCallTargetMapAt (uint32_t LineOffset, uint32_t Discriminator) const
Returns the call target map collected at a given location.
FunctionSamplesMap & functionSamplesAt (const LineLocation &Loc)
Return the function samples at the given callsite location.
const FunctionSamplesMap * findFunctionSamplesMapAt (const LineLocation &Loc) const
Returns the FunctionSamplesMap at the given Loc.
const FunctionSamples * findFunctionSamplesAt (const LineLocation &Loc, StringRef CalleeName) const
Returns a pointer to FunctionSamples at the given callsite location Loc with callee CalleeName.
bool empty () const
uint64_t getTotalSamples () const
Return the total number of samples collected inside the function.
uint64_t getHeadSamples () const
Return the total number of branch samples that have the function as the branch target.
uint64_t getEntrySamples () const
Return the sample count of the first instruction of the function.
const BodySampleMap & getBodySamples () const
Return all the samples collected in the body of the function.
const CallsiteSampleMap & getCallsiteSamples () const
Return all the callsite samples collected in the body of the function.
sampleprof_error merge (const FunctionSamples &Other, uint64_t Weight=1)
Merge the samples in Other into this one.
void findInlinedFunctions (DenseSet< GlobalValue::GUID > &S, const Module *M, uint64_t Threshold) const
Recursively traverses all children, if the total sample count of the corresponding function is no less than Threshold, add its corresponding GUID to S.
void setName (StringRef FunctionName)
Set the name of the function.
StringRef getName () const
Return the function name.
StringRef getFuncNameInModule (const Module *M) const
Return the original function name if it exists in Module M.
StringRef getNameInModule (StringRef Name, const Module *M) const
Translate Name into its original name in Module.
const FunctionSamples * findFunctionSamples (const DILocation *DIL) const
Get the FunctionSamples of the inline instance where DIL originates from.
Static Public Member Functions
static StringRef getCanonicalFnName (const Function &F)
Return the canonical name for a function, taking into account suffix elision policy attributes.
static unsigned getOffset (const DILocation *DIL)
Returns the line offset to the start line of the subprogram.
static uint64_t getGUID (StringRef Name)
Static Public Attributes
static SampleProfileFormat Format
static DenseMap< uint64_t, StringRef > GUIDToFuncNameMap
GUIDToFuncNameMap saves the mapping from GUID to the symbol name, for all the function symbols defined or declared in CurrentModule.
static Module * CurrentModule
Detailed Description
Representation of the samples collected for a function.
This data structure contains all the collected samples for the body of a function. Each sample corresponds to a LineLocation instance within the body of the function.
Definition at line 216 of file SampleProf.h.
Constructor & Destructor Documentation
FunctionSamples()
llvm::sampleprof::FunctionSamples::FunctionSamples () default
Member Function Documentation
addBodySamples()
sampleprof_error llvm::sampleprof::FunctionSamples::addBodySamples (uint32_t LineOffset, uint32_t Discriminator, uint64_t Num, uint64_t Weight = 1) inline
Definition at line 239 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderText::read(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), and llvm::sampleprof::SampleProfileReaderBinary::readProfile().
addCalledTargetSamples()
sampleprof_error llvm::sampleprof::FunctionSamples::addCalledTargetSamples (uint32_t LineOffset, uint32_t Discriminator, StringRef FName, uint64_t Num, uint64_t Weight = 1) inline
Definition at line 245 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderText::read(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), and llvm::sampleprof::SampleProfileReaderBinary::readProfile().
addHeadSamples()
sampleprof_error llvm::sampleprof::FunctionSamples::addHeadSamples (uint64_t Num, uint64_t Weight = 1) inline
Definition at line 231 of file SampleProf.h.
References llvm::counter_overflow, llvm::SaturatingMultiplyAdd(), and llvm::success.
Referenced by merge(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::sampleprof::SampleProfileReaderBinary::readFuncProfile(), and llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile().
addTotalSamples()
sampleprof_error llvm::sampleprof::FunctionSamples::addTotalSamples (uint64_t Num, uint64_t Weight = 1) inline
Definition at line 223 of file SampleProf.h.
References llvm::counter_overflow, llvm::SaturatingMultiplyAdd(), and llvm::success.
Referenced by merge(), llvm::sampleprof::SampleProfileReaderText::read(), and llvm::sampleprof::SampleProfileReaderBinary::readProfile().
dump()
LLVM_DUMP_METHOD void FunctionSamples::dump () const
Definition at line 191 of file SampleProf.cpp.
References llvm::dbgs(), and print().
empty()
bool llvm::sampleprof::FunctionSamples::empty () const inline
Definition at line 317 of file SampleProf.h.
findCallTargetMapAt()
ErrorOr< SampleRecord::CallTargetMap > llvm::sampleprof::FunctionSamples::findCallTargetMapAt (uint32_t LineOffset, uint32_t Discriminator) const inline
Returns the call target map collected at a given location.
Each location is specified by LineOffset and Discriminator. If the location is not found in profile, return error.
Definition at line 269 of file SampleProf.h.
findFunctionSamples()
const FunctionSamples * FunctionSamples::findFunctionSamples (const DILocation * DIL) const
Get the FunctionSamples of the inline instance where DIL originates from.
The FunctionSamples of the instruction (Machine or IR) associated to DIL is the inlined instance in which that instruction is coming from. We traverse the inline stack of that instruction, and match it with the tree nodes in the profile.
Returns
the FunctionSamples pointer to the inlined instance.
Definition at line 170 of file SampleProf.cpp.
References assert(), findFunctionSamplesAt(), first, llvm::DILocation::getBaseDiscriminator(), getOffset(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), second, and llvm::SmallVectorBase::size().
findFunctionSamplesAt()
const FunctionSamples * llvm::sampleprof::FunctionSamples::findFunctionSamplesAt (const LineLocation & Loc, StringRef CalleeName) const inline
Returns a pointer to FunctionSamples at the given callsite location Loc with callee CalleeName.
If no callsite can be found, relax the restriction to return the FunctionSamples at callsite location Loc with the maximum total sample count.
Definition at line 294 of file SampleProf.h.
References Format, and llvm::sampleprof::getRepInFormat().
Referenced by findFunctionSamples().
findFunctionSamplesMapAt()
const FunctionSamplesMap * llvm::sampleprof::FunctionSamples::findFunctionSamplesMapAt (const LineLocation & Loc) const inline
Returns the FunctionSamplesMap at the given Loc.
Definition at line 283 of file SampleProf.h.
findInlinedFunctions()
void llvm::sampleprof::FunctionSamples::findInlinedFunctions (DenseSet< GlobalValue::GUID > & S, const Module * M, uint64_t Threshold) const inline
Recursively traverses all children, if the total sample count of the corresponding function is no less than Threshold, add its corresponding GUID to S.
Also traverse the BodySamples to add hot CallTarget's GUID to S.
Definition at line 382 of file SampleProf.h.
References Callee, getGUID(), getNameInModule(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and Threshold.
findSamplesAt()
ErrorOr< uint64_t > llvm::sampleprof::FunctionSamples::findSamplesAt (uint32_t LineOffset, uint32_t Discriminator) const inline
Return the number of samples collected at the given location.
Each location is specified by LineOffset and Discriminator. If the location is not found in profile, return error.
Definition at line 256 of file SampleProf.h.
functionSamplesAt()
FunctionSamplesMap & llvm::sampleprof::FunctionSamples::functionSamplesAt (const LineLocation & Loc) inline
Return the function samples at the given callsite location.
Definition at line 277 of file SampleProf.h.
Referenced by merge(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), and llvm::sampleprof::SampleProfileReaderBinary::readProfile().
getBodySamples()
const BodySampleMap & llvm::sampleprof::FunctionSamples::getBodySamples () const inline
Return all the samples collected in the body of the function.
Definition at line 350 of file SampleProf.h.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), llvm::sampleprof::SampleProfileWriterText::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
getCallsiteSamples()
const CallsiteSampleMap & llvm::sampleprof::FunctionSamples::getCallsiteSamples () const inline
Return all the callsite samples collected in the body of the function.
Definition at line 353 of file SampleProf.h.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), llvm::sampleprof::SampleProfileWriterText::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
getCanonicalFnName()
static StringRef llvm::sampleprof::FunctionSamples::getCanonicalFnName (const Function & F) inline static
Return the canonical name for a function, taking into account suffix elision policy attributes.
Definition at line 415 of file SampleProf.h.
References assert(), F, llvm::StringRef::npos, llvm::StringRef::rfind(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::sampleprof::SampleProfileReaderCompactBinary::collectFuncsToUse(), llvm::sampleprof::SampleProfileReader::getSamplesFor(), and llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::GUIDToFuncNameMapper().
getEntrySamples()
uint64_t llvm::sampleprof::FunctionSamples::getEntrySamples () const inline
Return the sample count of the first instruction of the function.
The function can be either a standalone symbol or an inlined function.
Definition at line 331 of file SampleProf.h.
References T.
getFuncNameInModule()
StringRef llvm::sampleprof::FunctionSamples::getFuncNameInModule (const Module * M) const inline
Return the original function name if it exists in Module M.
Definition at line 409 of file SampleProf.h.
References getNameInModule().
getGUID()
static uint64_t llvm::sampleprof::FunctionSamples::getGUID (StringRef Name) inline static
Definition at line 515 of file SampleProf.h.
References Format, llvm::GlobalValue::getGUID(), and llvm::sampleprof::SPF_Compact_Binary.
Referenced by findInlinedFunctions(), and SortCallTargets().
getHeadSamples()
uint64_t llvm::sampleprof::FunctionSamples::getHeadSamples () const inline
Return the total number of branch samples that have the function as the branch target.
This should be equivalent to the sample of the first instruction of the symbol. But as we directly get this info for raw profile without referring to potentially inaccurate debug info, this gives more accurate profile data and is preferred for standalone symbols.
Definition at line 327 of file SampleProf.h.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), llvm::sampleprof::SampleProfileWriterText::write(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::sampleprof::SampleProfileWriterCompactBinary::write().
getName()
StringRef llvm::sampleprof::FunctionSamples::getName () const inline
Return the function name.
Definition at line 406 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterText::write(), llvm::sampleprof::SampleProfileWriterCompactBinary::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
getNameInModule()
StringRef llvm::sampleprof::FunctionSamples::getNameInModule (StringRef Name, const Module * M) const inline
Translate Name into its original name in Module.
When the Format is not SPF_Compact_Binary, Name needs no translation. When the Format is SPF_Compact_Binary, Name in current FunctionSamples is actually GUID of the original function name. getNameInModule will translate Name in current FunctionSamples into its original name. If the original name doesn't exist in M, return empty StringRef.
Definition at line 447 of file SampleProf.h.
References CurrentModule, Format, GUIDToFuncNameMap, llvm_unreachable, and llvm::sampleprof::SPF_Compact_Binary.
Referenced by findInlinedFunctions(), and getFuncNameInModule().
getOffset()
unsigned FunctionSamples::getOffset (const DILocation * DIL) static
Returns the line offset to the start line of the subprogram.
We assume that a single function will not exceed 65535 LOC.
Definition at line 164 of file SampleProf.cpp.
Referenced by findFunctionSamples().
getTotalSamples()
uint64_t llvm::sampleprof::FunctionSamples::getTotalSamples () const inline
Return the total number of samples collected inside the function.
Definition at line 320 of file SampleProf.h.
Referenced by callsiteIsHot(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::sampleprof::SampleProfileWriterText::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
merge()
sampleprof_error llvm::sampleprof::FunctionSamples::merge (const FunctionSamples & Other, uint64_t Weight = 1) inline
Merge the samples in Other into this one.
Optionally scale samples by Weight.
Definition at line 359 of file SampleProf.h.
References addHeadSamples(), addTotalSamples(), functionSamplesAt(), I, merge(), llvm::MergeResult(), Other, and llvm::success.
Referenced by merge().
print()
void FunctionSamples::print (raw_ostream & OS = dbgs(), unsigned Indent = 0) const
Print the samples collected for a function on stream OS.
Definition at line 122 of file SampleProf.cpp.
References llvm::sampleprof::SampleSorter< LocationT, SampleT >::get(), llvm::raw_ostream::indent(), and SI.
Referenced by dump(), and llvm::sampleprof::operator<<().
setName()
void llvm::sampleprof::FunctionSamples::setName (StringRef FunctionName) inline
Set the name of the function.
Definition at line 403 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderText::read(), llvm::sampleprof::SampleProfileReaderBinary::readFuncProfile(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), and llvm::sampleprof::SampleProfileReaderBinary::readProfile().
Member Data Documentation
CurrentModule
Module * llvm::sampleprof::FunctionSamples::CurrentModule static
Definition at line 478 of file SampleProf.h.
Referenced by getNameInModule(), llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::GUIDToFuncNameMapper(), and llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::~GUIDToFuncNameMapper().
Format
SampleProfileFormat llvm::sampleprof::FunctionSamples::Format static
Definition at line 474 of file SampleProf.h.
Referenced by findFunctionSamplesAt(), getGUID(), getNameInModule(), llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::GUIDToFuncNameMapper(), and llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::~GUIDToFuncNameMapper().
GUIDToFuncNameMap
DenseMap< uint64_t, StringRef > llvm::sampleprof::FunctionSamples::GUIDToFuncNameMap static
GUIDToFuncNameMap saves the mapping from GUID to the symbol name, for all the function symbols defined or declared in CurrentModule.
Definition at line 477 of file SampleProf.h.
Referenced by getNameInModule(), llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::GUIDToFuncNameMapper(), and llvm::sampleprof::FunctionSamples::GUIDToFuncNameMapper::~GUIDToFuncNameMapper().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp