LLVM: llvm::xray::BlockPrinter Class Reference
llvm::xray::BlockPrinter Class Reference
#include "llvm/XRay/BlockPrinter.h"
Public Member Functions
BlockPrinter (raw_ostream &O, RecordPrinter &P)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
void reset ()
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
virtual Error visit (BufferExtents &)=0
virtual Error visit (WallclockRecord &)=0
virtual Error visit (NewCPUIDRecord &)=0
virtual Error visit (TSCWrapRecord &)=0
virtual Error visit (CustomEventRecord &)=0
virtual Error visit (CallArgRecord &)=0
virtual Error visit (PIDRecord &)=0
virtual Error visit (NewBufferRecord &)=0
virtual Error visit (EndBufferRecord &)=0
virtual Error visit (FunctionRecord &)=0
virtual Error visit (CustomEventRecordV5 &)=0
virtual Error visit (TypedEventRecord &)=0
Detailed Description
Definition at line 23 of file BlockPrinter.h.
Constructor & Destructor Documentation
BlockPrinter()
llvm::xray::BlockPrinter::BlockPrinter (raw_ostream & O, RecordPrinter & P) inline explicit
Definition at line 39 of file BlockPrinter.h.
Member Function Documentation
reset()
void llvm::xray::BlockPrinter::reset () inline
Definition at line 55 of file BlockPrinter.h.
visit() [1/12]
Error llvm::xray::BlockPrinter::visit (BufferExtents & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 13 of file BlockPrinter.cpp.
References llvm::xray::RecordPrinter::visit().
visit() [2/12]
Error llvm::xray::BlockPrinter::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 98 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [3/12]
Error llvm::xray::BlockPrinter::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 61 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [4/12]
Error llvm::xray::BlockPrinter::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 70 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [5/12]
Error llvm::xray::BlockPrinter::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 105 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [6/12]
Error llvm::xray::BlockPrinter::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 89 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [7/12]
Error llvm::xray::BlockPrinter::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 20 of file BlockPrinter.cpp.
References llvm::xray::RecordPrinter::visit().
visit() [8/12]
Error llvm::xray::BlockPrinter::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 40 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [9/12]
Error llvm::xray::BlockPrinter::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 34 of file BlockPrinter.cpp.
References llvm::xray::RecordPrinter::visit().
visit() [10/12]
Error llvm::xray::BlockPrinter::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 51 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [11/12]
Error llvm::xray::BlockPrinter::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 79 of file BlockPrinter.cpp.
References E, and llvm::xray::RecordPrinter::visit().
visit() [12/12]
Error llvm::xray::BlockPrinter::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 29 of file BlockPrinter.cpp.
References llvm::xray::RecordPrinter::visit().
The documentation for this class was generated from the following files:
include/llvm/XRay/BlockPrinter.h
lib/XRay/BlockPrinter.cpp