LLVM: llvm::cfg::Update< NodePtr > Class Template Reference
llvm::cfg::Update< NodePtr > Class Template Reference
#include "llvm/Support/CFGUpdate.h"
Public Member Functions
Update (UpdateKind Kind, NodePtr From, NodePtr To)
UpdateKind getKind () const
NodePtr getFrom () const
NodePtr getTo () const
bool operator== (const Update &RHS) const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
template<typename NodePtr>
class llvm::cfg::Update< NodePtr >
Definition at line 28 of file CFGUpdate.h.
Constructor & Destructor Documentation
Update()
template<typename NodePtr > llvm::cfg::Update< NodePtr >::Update (UpdateKind Kind, NodePtr From, NodePtr To) inline
Definition at line 34 of file CFGUpdate.h.
Member Function Documentation
dump()
template<typename NodePtr > LLVM_DUMP_METHOD void llvm::cfg::Update< NodePtr >::dump () const inline
Definition at line 52 of file CFGUpdate.h.
References llvm::dbgs(), and llvm::cfg::Update< NodePtr >::print().
getFrom()
template<typename NodePtr > NodePtr llvm::cfg::Update< NodePtr >::getFrom () const inline
Definition at line 38 of file CFGUpdate.h.
Referenced by llvm::cfg::LegalizeUpdates(), and llvm::cfg::Update< NodePtr >::print().
getKind()
template<typename NodePtr > UpdateKind llvm::cfg::Update< NodePtr >::getKind () const inline
Definition at line 37 of file CFGUpdate.h.
Referenced by llvm::cfg::Update< NodePtr >::print().
getTo()
template<typename NodePtr > NodePtr llvm::cfg::Update< NodePtr >::getTo () const inline
Definition at line 39 of file CFGUpdate.h.
Referenced by llvm::cfg::LegalizeUpdates(), and llvm::cfg::Update< NodePtr >::print().
operator==()
template<typename NodePtr > bool llvm::cfg::Update< NodePtr >::operator== (const Update< NodePtr > & RHS) const inline
Definition at line 40 of file CFGUpdate.h.
print()
template<typename NodePtr > void llvm::cfg::Update< NodePtr >::print (raw_ostream & OS) const inline
Definition at line 44 of file CFGUpdate.h.
References llvm::cfg::Update< NodePtr >::getFrom(), llvm::cfg::Update< NodePtr >::getKind(), llvm::cfg::Update< NodePtr >::getTo(), and llvm::cfg::Insert.
Referenced by llvm::cfg::Update< NodePtr >::dump().
The documentation for this class was generated from the following file:
include/llvm/Support/CFGUpdate.h