LLVM: llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
#include "llvm/ADT/DenseMap.h"
Inherits llvm::DebugEpochBase.
Inherited by llvm::DenseMap< const llvm::SCEV *, const llvm::SCEV * >, llvm::DenseMap< ValueType, unsigned >, llvm::DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, llvm::DenseMap< BasicBlock *, std::unique_ptr< DomTreeNodeBase< BasicBlock > > >, llvm::DenseMap< const BasicBlock *, Loop * >, llvm::DenseMap< BlockT *, RegionT * >, llvm::DenseMap< Value *, SmallPtrSet< ReturnInst *, 2 > >, llvm::DenseMap< const Value *, detail::DenseSetEmpty, DenseMapInfo< const Value * >, detail::DenseSetPair< const Value * > >, llvm::DenseMap< const llvm::Value *, std::vector< OffsetValue > >, llvm::DenseMap< const llvm::Value *, AliasAttrs >, llvm::DenseMap< InstantiatedValue, llvm::cflaa::StratifiedInfo >, llvm::DenseMap< T, detail::DenseSetEmpty, DenseMapInfo< T >, detail::DenseSetPair< T > >, llvm::DenseMap< unsigned, unsigned >, llvm::DenseMap< BasicBlock *, unsigned >, llvm::DenseMap< Value *, detail::DenseSetEmpty, DenseMapInfo< Value * >, detail::DenseSetPair< Value * > >, llvm::DenseMap< Value *, unsigned >, llvm::DenseMap< AssertingVH< Instruction >, unsigned >, llvm::DenseMap< int, std::pair< unsigned, llvm::MCSymbol * > >, llvm::DenseMap< const llvm::Function *, llvm::AMDGPUFunctionArgInfo >, llvm::DenseMap< const llvm::Function *, SIFunctionResourceInfo >, llvm::DenseMap< ValueMapCVH, FuncInfo, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::MachineBasicBlock *, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, AddressPoolEntry >, llvm::DenseMap< ASTCallbackVH, AliasSet::PointerRec *, ASTCallbackVHDenseMapInfo >, llvm::DenseMap< AnalysisKey *, std::unique_ptr< PassConceptT > >, llvm::DenseMap< IRUnitT *, AnalysisResultListT >, llvm::DenseMap< std::pair< AnalysisKey *, IRUnitT * >, typename AnalysisResultListT::iterator >, llvm::DenseMap< const llvm::MCSymbol *, unsigned >, llvm::DenseMap< MCSection *, unsigned >, llvm::DenseMap< AffectedValueCallbackVH, SmallVector< WeakTrackingVH, 1 >, AffectedValueCallbackVH::DMI >, llvm::DenseMap< FunctionCallbackVH, std::unique_ptr< AssumptionCache >, FunctionCallbackVH::DMI >, llvm::DenseMap< std::pair< const llvm::Value *, int >, llvm::DenseMap >, llvm::DenseMap< AbstractAttribute *, SetVector< AbstractAttribute * > >, llvm::DenseMap< unsigned, detail::DenseSetEmpty, DenseMapInfo< unsigned >, detail::DenseSetPair< unsigned > >, llvm::DenseMap< const llvm::MachineInstr *, detail::DenseSetEmpty, DenseMapInfo< const llvm::MachineInstr * >, detail::DenseSetPair< const llvm::MachineInstr * > >, llvm::DenseMap< const llvm::MachineInstr *, unsigned >, llvm::DenseMap< const BlockT *, BlockNode >, llvm::DenseMap< KeyT, size_t >, llvm::DenseMap< const llvm::MachineBasicBlock *, int >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::BlockFrequency >, llvm::DenseMap< BasicBlockCallbackVH, detail::DenseSetEmpty, llvm::DenseMapInfo< llvm::Value * >, detail::DenseSetPair< BasicBlockCallbackVH > >, llvm::DenseMap< Edge, llvm::BranchProbability >, llvm::DenseMap< const BasicBlock *, int >, llvm::DenseMap< const llvm::BasicBlock *, std::unique_ptr< BBInfo > >, llvm::DenseMap< const llvm::Function *, llvm::Optional< CFLAndersAAResult::FunctionInfo > >, llvm::DenseMap< llvm::Function *, llvm::Optional< CFLSteensAAResult::FunctionInfo > >, llvm::DenseMap< VNType, SmallVector< Instruction *, 4 > >, llvm::DenseMap< MDString *, unsigned >, llvm::DenseMap< llvm::BasicBlock *, detail::DenseSetEmpty, DenseMapInfo< llvm::BasicBlock * >, detail::DenseSetPair< llvm::BasicBlock * > >, llvm::DenseMap< const llvm::BasicBlock *, unsigned >, llvm::DenseMap< const llvm::LexicalScope *, llvm::SmallVector< LocalVariable, 1 > >, llvm::DenseMap< const llvm::DIScope *, std::unique_ptr< llvm::SmallVector > >, llvm::DenseMap< llvm::MCSectionCOFF *, detail::DenseSetEmpty, DenseMapInfo< llvm::MCSectionCOFF * >, detail::DenseSetPair< llvm::MCSectionCOFF * > >, llvm::DenseMap< const llvm::Function *, unsigned >, llvm::DenseMap< llvm::StringRef, unsigned >, llvm::DenseMap< std::pair< const llvm::DINode *, const llvm::DIType * >, llvm::codeview::TypeIndex >, llvm::DenseMap< const llvm::DICompositeType *, llvm::codeview::TypeIndex >, llvm::DenseMap< GlobalVariable *, ConstCandVecType >, llvm::DenseMap< GlobalVariable *, ConstInfoVecType >, llvm::DenseMap< ConstantClass *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantClass * > >, llvm::DenseMap< UnsignPair, unsigned >, llvm::DenseMap< llvm::MDNode *, unsigned >, llvm::DenseMap< llvm::MDNode *, llvm::SmallVector< llvm::TypedTrackingMDRef, 1 > >, llvm::DenseMap< const llvm::DIE *, unsigned >, llvm::DenseMap< uint32_t, detail::DenseSetEmpty, DenseMapInfo< uint32_t >, detail::DenseSetPair< uint32_t > >, llvm::DenseMap< uint32_t, const llvm::DWARFDebugNames::NameIndex * >, llvm::DenseMap< llvm::DWARFDebugNames::Abbrev, detail::DenseSetEmpty, AbbrevMapInfo, detail::DenseSetPair< llvm::DWARFDebugNames::Abbrev > >, llvm::DenseMap< InlinedEntity, unsigned >, llvm::DenseMap< unsigned, CounterInfo >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MCSymbol * >, llvm::DenseMap< llvm::Instruction *, llvm::APInt >, llvm::DenseMap< const llvm::Loop *, detail::DenseSetEmpty, DenseMapInfo< const llvm::Loop * >, detail::DenseSetPair< const llvm::Loop * > >, llvm::DenseMap< const llvm::Value *, detail::DenseSetEmpty, DenseMapInfo< const llvm::Value * >, detail::DenseSetPair< const llvm::Value * > >, llvm::DenseMap< const llvm::BasicBlock *, detail::DenseSetEmpty, DenseMapInfo< const llvm::BasicBlock * >, detail::DenseSetPair< const llvm::BasicBlock * > >, llvm::DenseMap< NodePtr, llvm::DomTreeBuilder::SemiNCAInfo::InfoRec >, llvm::DenseMap< NodePtr, llvm::SmallVector< llvm::PointerIntPair, 4 > >, llvm::DenseMap< NodeT *, std::unique_ptr< DomTreeNodeBase< NodeT > > >, llvm::DenseMap< const MDNode *, ImportedEntityList >, llvm::DenseMap< const llvm::MDNode *, llvm::DIE * >, llvm::DenseMap< const llvm::DINode *, std::unique_ptr< llvm::DbgEntity > >, llvm::DenseMap< const llvm::MDNode *, unsigned >, llvm::DenseMap< const llvm::DIE *, llvm::DwarfCompileUnit * >, llvm::DenseMap< const llvm::MCSymbol *, uint64_t >, llvm::DenseMap< const llvm::MDNode *, uint64_t >, llvm::DenseMap< const llvm::MCSection *, const llvm::MCSymbol * >, llvm::DenseMap< llvm::LexicalScope *, ScopeVars >, llvm::DenseMap< llvm::LexicalScope *, llvm::SmallVector >, llvm::DenseMap< llvm::DIE *, const llvm::DINode * >, llvm::DenseMap< llvm::Constant *, llvm::Constant * >, llvm::DenseMap< const llvm::Value *, unsigned >, llvm::DenseMap< llvm::MachineInstr *, unsigned >, llvm::DenseMap< const GCOVFunction *, unsigned >, llvm::DenseMap< uint32_t, BlockVector >, llvm::DenseMap< uint32_t, FunctionVector >, llvm::DenseMap< llvm::Instruction *, unsigned >, llvm::DenseMap< const llvm::Value *, int >, llvm::DenseMap< llvm::GlobalValue *, detail::DenseSetEmpty, DenseMapInfo< llvm::GlobalValue * >, detail::DenseSetPair< llvm::GlobalValue * > >, llvm::DenseMap< const llvm::Comdat *, llvm::Comdat * >, llvm::DenseMap< const llvm::BasicBlock *, llvm::MachineBasicBlock * >, llvm::DenseMap< unsigned, const llvm::Value * >, llvm::DenseMap< const llvm::Instruction *, llvm::FunctionLoweringInfo::StatepointSpillMap >, llvm::DenseMap< const llvm::AllocaInst *, int >, llvm::DenseMap< const llvm::Argument *, int >, llvm::DenseMap< const llvm::Value *, ISD::NodeType >, llvm::DenseMap< const Value *, Optional< int > >, llvm::DenseMap< const llvm::Value *, const llvm::Value * >, llvm::DenseMap< const Function *, GCFunctionInfo * >, llvm::DenseMap< unsigned, LaneBitmask >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::DenseMap >, llvm::DenseMap< llvm::MachineInstr *, llvm::DenseMap >, llvm::DenseMap< const llvm::MachineInstr *, llvm::UniqueMachineInstr * >, llvm::DenseMap< uint32_t, LeaderTableEntry >, llvm::DenseMap< llvm::AssertingVH< llvm::BasicBlock >, uint32_t >, llvm::DenseMap< llvm::Value *, uint32_t >, llvm::DenseMap< llvm::GVN::Expression, uint32_t >, llvm::DenseMap< uint32_t, llvm::PHINode * >, llvm::DenseMap< std::pair< uint32_t, const BasicBlock * >, uint32_t >, llvm::DenseMap< const BasicBlock *, bool >, llvm::DenseMap< llvm::GlobalValue *, llvm::SmallPtrSet< llvm::GlobalValue *, 4 > >, llvm::DenseMap< ValueMapCVH, uint64_t, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::Value *, const llvm::GlobalValue * >, llvm::DenseMap< const llvm::Function *, GlobalsAAResult::FunctionInfo >, llvm::DenseMap< llvm::GlobalVariable *, llvm::GlobalsMetadata::Entry >, llvm::DenseMap< unsigned, ExtType >, llvm::DenseMap< unsigned, PredSet >, llvm::DenseMap< unsigned, UnitsAndLanes >, llvm::DenseMap< NodeTy *, std::unique_ptr< DomTreeNodeBase< NodeTy > > >, llvm::DenseMap< const Metadata *, TrackingMDRef >, llvm::DenseMap< llvm::StructType *, detail::DenseSetEmpty, DenseMapInfo< llvm::StructType * >, detail::DenseSetPair< llvm::StructType * > >, llvm::DenseMap< llvm::StructType *, detail::DenseSetEmpty, StructTypeKeyInfo, detail::DenseSetPair< llvm::StructType * > >, llvm::DenseMap< CFGEdge, llvm::SmallVector< llvm::MachineBasicBlock *, 1 > >, llvm::DenseMap< const llvm::Value *, llvm::SmallVector * >, llvm::DenseMap< const llvm::Type *, llvm::SmallVector * >, llvm::DenseMap< unsigned, TreeTy * >, llvm::DenseMap< Function *, OpcodeInstMapTy >, llvm::DenseMap< Function *, InstructionVectorTy >, llvm::DenseMap< llvm::PHINode *, llvm::Value * >, llvm::DenseMap< SymbolRemappingReader::Key, llvm::StringRef >, llvm::DenseMap< llvm::GlobalVariable *, PerFunctionProfileData >, llvm::DenseMap< const llvm::BasicBlock *, const llvm::Instruction * >, llvm::DenseMap< int32_t, InstTy * >, llvm::DenseMap< llvm::Instruction *, llvm::InterleaveGroup< llvm::Instruction > * >, llvm::DenseMap< llvm::Instruction *, llvm::SmallPtrSet< llvm::Instruction *, 2 > >, llvm::DenseMap< APInt, std::unique_ptr< ConstantInt >, DenseMapAPIntKeyInfo >, llvm::DenseMap< APFloat, std::unique_ptr< ConstantFP >, DenseMapAPFloatKeyInfo >, llvm::DenseMap< llvm::Value *, llvm::ValueAsMetadata * >, llvm::DenseMap< llvm::Metadata *, llvm::MetadataAsValue * >, llvm::DenseMap< const llvm::Value *, llvm::StringMapEntry * >, llvm::DenseMap< const llvm::MDString *, llvm::DICompositeType * >, llvm::DenseMap< llvm::Type *, std::unique_ptr< llvm::ConstantAggregateZero > >, llvm::DenseMap< ConstantArray *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantArray * > >, llvm::DenseMap< ConstantStruct *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantStruct * > >, llvm::DenseMap< ConstantVector *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantVector * > >, llvm::DenseMap< llvm::PointerType *, std::unique_ptr< llvm::ConstantPointerNull > >, llvm::DenseMap< llvm::Type *, std::unique_ptr< llvm::UndefValue > >, llvm::DenseMap< std::pair< const llvm::Function *, const llvm::BasicBlock * >, llvm::BlockAddress * >, llvm::DenseMap< llvm::ConstantExpr *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< llvm::ConstantExpr * > >, llvm::DenseMap< llvm::InlineAsm *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< llvm::InlineAsm * > >, llvm::DenseMap< unsigned, llvm::IntegerType * >, llvm::DenseMap< FunctionType *, detail::DenseSetEmpty, FunctionTypeKeyInfo, detail::DenseSetPair< FunctionType * > >, llvm::DenseMap< StructType *, detail::DenseSetEmpty, AnonStructTypeKeyInfo, detail::DenseSetPair< StructType * > >, llvm::DenseMap< std::pair< llvm::Type *, uint64_t >, llvm::ArrayType * >, llvm::DenseMap< std::pair< llvm::Type *, llvm::ElementCount >, llvm::VectorType * >, llvm::DenseMap< llvm::Type *, llvm::PointerType * >, llvm::DenseMap< std::pair< llvm::Type *, unsigned >, llvm::PointerType * >, llvm::DenseMap< Value *, ValueHandleBase * >, llvm::DenseMap< const llvm::Instruction *, llvm::MDAttachmentMap >, llvm::DenseMap< const llvm::GlobalObject *, llvm::MDGlobalAttachmentMap >, llvm::DenseMap< const llvm::GlobalObject *, llvm::StringRef >, llvm::DenseMap< const llvm::GlobalValue *, llvm::StringRef >, llvm::DenseMap< std::pair< const char *, unsigned >, unsigned >, llvm::DenseMap< const llvm::Function *, std::string >, llvm::DenseMap< const llvm::Function *, llvm::LazyCallGraph::Node * >, llvm::DenseMap< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, llvm::DenseMap< llvm::LazyCallGraph::RefSCC *, int >, llvm::DenseMap< llvm::LazyCallGraph::Node *, int >, llvm::DenseMap< LiveRange *, std::pair< BitVector, BitVector > >, llvm::DenseMap< const Value *, Value * >, llvm::DenseMap< llvm::Loop *, std::unique_ptr< llvm::LoopAccessInfo > >, llvm::DenseMap< llvm::BasicBlock *, unsigned >, llvm::DenseMap< const BlockT *, LoopT * >, llvm::DenseMap< llvm::BasicBlock *, llvm::TinyPtrVector >, llvm::DenseMap< unsigned, llvm::DenseMap >, llvm::DenseMap< unsigned, llvm::SmallPtrSet< llvm::Instruction *, 4 > >, llvm::DenseMap< std::pair< Instruction *, unsigned >, std::pair< InstWidening, unsigned > >, llvm::DenseMap< PHINode *, RecurrenceDescriptor >, llvm::DenseMap< PHINode *, unsigned >, llvm::DenseMap< llvm::Instruction *, llvm::Instruction * >, llvm::DenseMap< ValueMapCVH, WeakTrackingVH, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::Value *, const llvm::RuntimePointerChecking::CheckingPtrGroup * >, llvm::DenseMap< const llvm::RuntimePointerChecking::CheckingPtrGroup *, llvm::MDNode * >, llvm::DenseMap< const llvm::MCSection *, llvm::MCFragment * >, llvm::DenseMap< unsigned, llvm::MCCVFunctionInfo::LineInfo >, llvm::DenseMap< llvm::MCPaddingFragment *, llvm::SmallVector >, llvm::DenseMap< llvm::MCPaddingFragment *, uint64_t >, llvm::DenseMap< std::pair< unsigned, unsigned >, llvm::MCSymbol * >, llvm::DenseMap< unsigned, llvm::MCLabel * >, llvm::DenseMap< llvm::MCSection *, detail::DenseSetEmpty, DenseMapInfo< llvm::MCSection * >, detail::DenseSetPair< llvm::MCSection * > >, llvm::DenseMap< unsigned, int >, llvm::DenseMap< const uint32_t *, unsigned >, llvm::DenseMap< int, FrameIndexOperand >, llvm::DenseMap< llvm::AssertingVH< llvm::BasicBlock >, AddrLabelSymEntry >, llvm::DenseMap< llvm::AssertingVH< llvm::Function >, std::vector< llvm::MCSymbol * > >, llvm::DenseMap< SymbolsMapKey, Symbol * >, llvm::DenseMap< const llvm::MCSection *, std::vector< RelAndSymbol > >, llvm::DenseMap< const llvm::MCSection *, unsigned >, llvm::DenseMap< const MCSection *, uint64_t >, llvm::DenseMap< llvm::MachineConstantPoolValue *, detail::DenseSetEmpty, DenseMapInfo< llvm::MachineConstantPoolValue * >, detail::DenseSetPair< llvm::MachineConstantPoolValue * > >, llvm::DenseMap< llvm::MCSymbol *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::MCSymbol *, unsigned >, llvm::DenseMap< const MachineInstr *, CallSiteInfo >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::MachineLoop * >, llvm::DenseMap< const llvm::Function *, std::unique_ptr< llvm::MachineFunction > >, llvm::DenseMap< llvm::MCSymbol *, StubValueTy >, llvm::DenseMap< llvm::MachineBasicBlock *, std::unique_ptr< DomTreeNodeBase< llvm::MachineBasicBlock > > >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MachineTraceMetrics::InstrCycles >, llvm::DenseMap< const llvm::GlobalValue *, unsigned >, llvm::DenseMap< llvm::Init *, MappedValue >, llvm::DenseMap< KeyT, unsigned >, llvm::DenseMap< PointerIntPair< Value *, 1, bool >, std::vector< unsigned > >, llvm::DenseMap< Instruction *, MemDepResult >, llvm::DenseMap< llvm::AssertingVH< const llvm::Value >, llvm::NonLocalDepResult >, llvm::DenseMap< Instruction *, SmallPtrSet< const Value *, 4 > >, llvm::DenseMap< ValueIsLoadPair, NonLocalPointerInfo >, llvm::DenseMap< Instruction *, SmallPtrSet< ValueIsLoadPair, 4 > >, llvm::DenseMap< Instruction *, PerInstNLInfo >, llvm::DenseMap< Instruction *, SmallPtrSet< Instruction *, 4 > >, llvm::DenseMap< const llvm::Value *, llvm::MemoryAccess * >, llvm::DenseMap< const BasicBlock *, std::unique_ptr< AccessList > >, llvm::DenseMap< const BasicBlock *, std::unique_ptr< DefsList > >, llvm::DenseMap< const llvm::MemoryAccess *, unsigned long >, llvm::DenseMap< ConstMemoryAccessPair, detail::DenseSetEmpty, DenseMapInfo< ConstMemoryAccessPair >, detail::DenseSetPair< ConstMemoryAccessPair > >, llvm::DenseMap< const llvm::MachineInstr *, llvm::SmallVector< const llvm::MachineInstr *, 2 > >, llvm::DenseMap< const llvm::MachineInstr *, InstType >, llvm::DenseMap< const TargetRegisterClass *, VRegMap >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::WeakTrackingVH, 2 > >, llvm::DenseMap< llvm::SUnit *, detail::DenseSetEmpty, DenseMapInfo< llvm::SUnit * >, detail::DenseSetPair< llvm::SUnit * > >, llvm::DenseMap< const Value *, WeakEvalType >, llvm::DenseMap< void *, llvm::cl::Option * >, llvm::DenseMap< const llvm::BasicBlock *, std::unique_ptr< llvm::OrderedBasicBlock > >, llvm::DenseMap< PoolEntry *, detail::DenseSetEmpty, PoolEntryDSInfo, detail::DenseSetPair< PoolEntry * > >, llvm::DenseMap< AnalysisID, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::SmallPtrSet< llvm::Pass *, 8 > >, llvm::DenseMap< llvm::Pass *, llvm::AnalysisUsage * >, llvm::DenseMap< AnalysisID, const llvm::PassInfo * >, llvm::DenseMap< AnalysisID, llvm::IdentifyingPassPtr >, llvm::DenseMap< const void *, const PassInfo * >, llvm::DenseMap< unsigned, llvm::MachineBasicBlock * >, llvm::DenseMap< unsigned, llvm::VRegInfo * >, llvm::DenseMap< const llvm::PHINode *, unsigned int >, llvm::DenseMap< unsigned int, llvm::SmallPtrSet >, llvm::DenseMap< PhiValuesCallbackVH, detail::DenseSetEmpty, llvm::DenseMapInfo< llvm::Value * >, detail::DenseSetPair< PhiValuesCallbackVH > >, llvm::DenseMap< const llvm::Function *, std::vector< uint32_t > >, llvm::DenseMap< llvm::BasicBlock *, llvm::BasicBlock ** >, llvm::DenseMap< const llvm::Value *, const llvm::PredicateBase * >, llvm::DenseMap< llvm::Value *, unsigned int >, llvm::DenseMap< std::pair< llvm::BasicBlock *, llvm::BasicBlock * >, detail::DenseSetEmpty, DenseMapInfo< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > >, detail::DenseSetPair< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > > >, llvm::DenseMap< const llvm::SCEV *, RewriteEntry >, llvm::DenseMap< ValueMapCVH, SCEVWrapPredicate::IncrementWrapFlags, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< T, ptrdiff_t >, llvm::DenseMap< ValueMapCVH, std::unique_ptr< const llvm::GlobalValuePseudoSourceValue >, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< llvm::MachineInstr *, int >, llvm::DenseMap< llvm::AssertingVH< llvm::Value >, unsigned >, llvm::DenseMap< AssertingVH< Instruction >, detail::DenseSetEmpty, DenseMapInfo< AssertingVH< Instruction > >, detail::DenseSetPair< AssertingVH< Instruction > > >, llvm::DenseMap< std::pair< llvm::Value *, llvm::Value * >, llvm::ReassociatePass::PairMapValue >, llvm::DenseMap< llvm::Init *, llvm::Init * >, llvm::DenseMap< const llvm::MCSymbol *, std::vector< llvm::StringRef > >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::PartialMapping > >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::ValueMapping > >, llvm::DenseMap< unsigned, std::unique_ptr< llvm::RegisterBankInfo::ValueMapping[]> >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::InstructionMapping > >, llvm::DenseMap< unsigned, const llvm::TargetRegisterClass * >, llvm::DenseMap< SID, SID >, llvm::DenseMap< std::pair< const llvm::SCEV *, llvm::Instruction * >, llvm::TrackingVH< llvm::Value > >, llvm::DenseMap< llvm::AssertingVH< llvm::Value >, detail::DenseSetEmpty, DenseMapInfo< llvm::AssertingVH< llvm::Value > >, detail::DenseSetPair< llvm::AssertingVH< llvm::Value > > >, llvm::DenseMap< const llvm::SCEV *, const llvm::Loop * >, llvm::DenseMap< llvm::AssertingVH< llvm::PHINode >, detail::DenseSetEmpty, DenseMapInfo< llvm::AssertingVH< llvm::PHINode > >, detail::DenseSetPair< llvm::AssertingVH< llvm::PHINode > > >, llvm::DenseMap< const SCEV *, SmallVector< const SCEVPredicate *, 4 > >, llvm::DenseMap< const SDNode *, SmallVector< SDDbgValue *, 2 > >, llvm::DenseMap< const llvm::Value *, std::unique_ptr< const llvm::AMDGPUBufferPseudoSourceValue > >, llvm::DenseMap< const llvm::Value *, std::unique_ptr< const llvm::AMDGPUImagePseudoSourceValue > >, llvm::DenseMap< int, std::vector< llvm::SIMachineFunctionInfo::SpilledReg > >, llvm::DenseMap< int, llvm::SIMachineFunctionInfo::VGPRSpillToAGPR >, llvm::DenseMap< int, std::deque< llvm::SUnit * > >, llvm::DenseMap< llvm::AllocaInst *, detail::DenseSetEmpty, DenseMapInfo< llvm::AllocaInst * >, detail::DenseSetPair< llvm::AllocaInst * > >, llvm::DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::DenseMap< llvm::PHINode *, detail::DenseSetEmpty, DenseMapInfo< llvm::PHINode * >, detail::DenseSetPair< llvm::PHINode * > >, llvm::DenseMap< llvm::SelectInst *, detail::DenseSetEmpty, DenseMapInfo< llvm::SelectInst * >, detail::DenseSetPair< llvm::SelectInst * > >, llvm::DenseMap< llvm::BasicBlock *, llvm::Value * >, llvm::DenseMap< BlkT *, BBInfo * >, llvm::DenseMap< const SCEV *, bool >, llvm::DenseMap< const SCEV *, SetVector< ValueOffsetPair > >, llvm::DenseMap< SCEVCallbackVH, const SCEV *, DenseMapInfo< Value * > >, llvm::DenseMap< const llvm::SCEV *, uint32_t >, llvm::DenseMap< const llvm::Loop *, BackedgeTakenInfo >, llvm::DenseMap< llvm::PHINode *, llvm::Constant * >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< std::pair< const llvm::Loop *, const llvm::SCEV * >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::PointerIntPair< const llvm::Loop *, 2, LoopDisposition >, 2 > >, llvm::DenseMap< const llvm::Loop *, LoopProperties >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::PointerIntPair< const llvm::BasicBlock *, 2, BlockDisposition >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::ConstantRange >, llvm::DenseMap< const llvm::Loop *, llvm::SmallVector< const llvm::SCEV *, 4 > >, llvm::DenseMap< std::pair< const llvm::SCEVUnknown *, const llvm::Loop * >, std::pair< const llvm::SCEV *, llvm::SmallVector< const llvm::SCEVPredicate *, 3 > > >, llvm::DenseMap< llvm::MachineInstr *, llvm::SUnit * >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, KInfo >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, DenseMapInfo< K > >, llvm::DenseMap< const llvm::SDNode *, CallSiteDbgInfo >, llvm::DenseMap< llvm::MCSymbol *, llvm::SDNode * >, llvm::DenseMap< const llvm::Value *, llvm::SDValue >, llvm::DenseMap< const llvm::Constant *, unsigned >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::Init *, detail::DenseSetEmpty, DenseMapInfo< llvm::Init * >, detail::DenseSetPair< llvm::Init * > >, llvm::DenseMap< const MachineInstr *, SlotIndex >, llvm::DenseMap< const Value *, unsigned >, llvm::DenseMap< llvm::AttributeSet, unsigned >, llvm::DenseMap< GlobalValue::GUID, unsigned >, llvm::DenseMap< LatticeKey, LatticeVal >, llvm::DenseMap< std::pair< unsigned, unsigned >, ValueForcePair >, llvm::DenseMap< uint64_t, unsigned >, llvm::DenseMap< const MCSymbol *, unsigned >, llvm::DenseMap< const AllocaInst *, MachineFrameInfo::SSPLayoutKind >, llvm::DenseMap< llvm::SDValue, llvm::SDValue >, llvm::DenseMap< llvm::CachedHashStringRef, size_t >, llvm::DenseMap< std::pair< const llvm::MachineBasicBlock *, const llvm::Value * >, llvm::Register >, llvm::DenseMap< llvm::PointerIntPair< const llvm::Instruction *, 1, bool >, llvm::Register >, llvm::DenseMap< llvm::SUnit *, std::pair< unsigned, int64_t > >, llvm::DenseMap< const llvm::MDNode *, TBAABaseNodeSummary >, llvm::DenseMap< const llvm::MDNode *, bool >, llvm::DenseMap< unsigned, AvailableValsTy >, llvm::DenseMap< unsigned, std::string >, llvm::DenseMap< unsigned int, unsigned int >, llvm::DenseMap< PassInvocationID, std::unique_ptr< llvm::Timer > >, llvm::DenseMap< const llvm::MDNode *, detail::DenseSetEmpty, DenseMapInfo< const llvm::MDNode * >, detail::DenseSetPair< const llvm::MDNode * > >, llvm::DenseMap< llvm::Type *, detail::DenseSetEmpty, DenseMapInfo< llvm::Type * >, detail::DenseSetPair< llvm::Type * > >, llvm::DenseMap< llvm::StringRef, detail::DenseSetEmpty, DenseMapInfo< llvm::StringRef >, detail::DenseSetPair< llvm::StringRef > >, llvm::DenseMap< llvm::Value *, SimplifiedAddress >, llvm::DenseMap< llvm::Value *, llvm::Constant * >, llvm::DenseMap< int32_t, llvm::Instruction * >, llvm::DenseMap< llvm::VPInstruction *, llvm::InterleaveGroup< llvm::VPInstruction > * >, llvm::DenseMap< std::pair< BasicBlock *, BasicBlock * >, VPValue * >, llvm::DenseMap< BasicBlock *, VPValue * >, llvm::DenseMap< VPValue *, Value * >, llvm::DenseMap< llvm::VPValue *, llvm::SmallVector >, llvm::DenseMap< Value *, VPValue * >, llvm::DenseMap< const VPBlockBase *, VPLoop * >, llvm::DenseMap< VPBlockBase *, std::unique_ptr< DomTreeNodeBase< VPBlockBase > > >, llvm::DenseMap< llvm::SmallVector< llvm::VPValue *, 4 >, llvm::VPInstruction *, BundleDenseMapInfo >, llvm::DenseMap< Type *, unsigned >, llvm::DenseMap< const Metadata *, MDIndex >, llvm::DenseMap< IndexAndAttrSet, unsigned >, llvm::DenseMap< AttributeList, unsigned >, llvm::DenseMap< const Instruction *, unsigned >, llvm::DenseMap< ValueMapCVH, ValueT, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< unsigned, float >, llvm::DenseMap< PointerUnion< const BasicBlock *, MachineBasicBlock * >, PointerUnion< const BasicBlock *, MachineBasicBlock * > >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::WebAssemblyException * >, llvm::DenseMap< const llvm::Instruction *, int >, llvm::DenseMap< const llvm::FuncletPadInst *, int >, llvm::DenseMap< const llvm::InvokeInst *, int >, llvm::DenseMap< llvm::MCSymbol *, std::pair< int, llvm::MCSymbol * > >, llvm::DenseMap< int, unsigned >, llvm::DenseMap< Value *, ValueInfo >, llvm::DenseMap< T, llvm::cflaa::StratifiedInfo >, llvm::DenseMap< uint32_t, uint32_t >, llvm::DenseMap< uint32_t, llvm::StringRef >, llvm::DenseMap< llvm::codeview::GloballyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::codeview::LocallyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::coverage::CounterExpression, unsigned >, llvm::DenseMap< size_t, llvm::DenseSet< size_t > >, llvm::DenseMap< StringRef, Atom * >, llvm::DenseMap< Atom *, detail::DenseSetEmpty, DenseMapInfo< Atom * >, detail::DenseSetPair< Atom * > >, llvm::DenseMap< llvm::StringRef, llvm::jitlink::DefinedAtom * >, llvm::DenseMap< JITTargetAddress, CIEInformation >, llvm::DenseMap< unsigned, SegmentLayout >, llvm::DenseMap< const llvm::jitlink::DefinedAtom *, const llvm::jitlink::DefinedAtom * >, llvm::DenseMap< unsigned, llvm::jitlink::MachOAtomGraphBuilder::MachOSection >, llvm::DenseMap< DefinedAtom *, detail::DenseSetEmpty, DenseMapInfo< DefinedAtom * >, detail::DenseSetPair< DefinedAtom * > >, llvm::DenseMap< ObjectKey, Value, llvm::DenseMapInfo< StringRef > >, llvm::DenseMap< GlobalValue::GUID, llvm::StringRef >, llvm::DenseMap< unsigned short, std::unique_ptr< const llvm::mca::InstrDesc > >, llvm::DenseMap< const llvm::MCInst *, std::unique_ptr< const llvm::mca::InstrDesc > >, llvm::DenseMap< unsigned, std::unique_ptr< llvm::mca::MemoryGroup > >, llvm::DenseMap< uint32_t, std::vector< MutableArrayRef< uint8_t > > >, llvm::DenseMap< ValuePairTy, bool >, llvm::DenseMap< const llvm::Value *, llvm::WeakTrackingVH >, llvm::DenseMap< minidump::StreamType, std::size_t >, llvm::DenseMap< unsigned, OptRange >, llvm::DenseMap< SymbolStringPtr, JITEvaluatedSymbol >, llvm::DenseMap< JITDylib *, SymbolNameSet >, llvm::DenseMap< llvm::orc::MaterializationResponsibility *, JITTargetAddress >, llvm::DenseMap< VModuleKey, JITTargetAddress >, llvm::DenseMap< SymbolStringPtr, detail::DenseSetEmpty, DenseMapInfo< SymbolStringPtr >, detail::DenseSetPair< SymbolStringPtr > >, llvm::DenseMap< SymbolStringPtr, SymbolTableEntry >, llvm::DenseMap< SymbolStringPtr, std::shared_ptr< UnmaterializedInfo > >, llvm::DenseMap< SymbolStringPtr, MaterializingInfo >, llvm::DenseMap< SymbolStringPtr, SymbolAliasMapEntry >, llvm::DenseMap< SymbolStringPtr, JITSymbolFlags >, llvm::DenseMap< VModuleKey, AllocPtr >, llvm::DenseMap< llvm::orc::SymbolStringPtr, llvm::DenseSet >, llvm::DenseMap< CVSymbol, detail::DenseSetEmpty, llvm::pdb::GSIHashStreamBuilder::SymbolDenseMapInfo, detail::DenseSetPair< CVSymbol > >, llvm::DenseMap< uint32_t, std::string >, llvm::DenseMap< llvm::codeview::TypeIndex, uint32_t >, llvm::DenseMap< std::pair< llvm::codeview::TypeIndex, uint32_t >, uint32_t >, llvm::DenseMap< NodeId, MachineBasicBlock * >, llvm::DenseMap< BasicBlock *, BlockLifetimeInfo >, llvm::DenseMap< const llvm::BasicBlock *, std::pair< unsigned, unsigned > >, llvm::DenseMap< llvm::AllocaInst *, unsigned >, llvm::DenseMap< llvm::BasicBlock *, llvm::SmallVector< std::pair< unsigned, Marker >, 4 > >, llvm::DenseMap< uint64_t, llvm::StringRef >, llvm::DenseMap< llvm::StringRef, uint64_t >, llvm::DenseMap< SymbolRemappingReader::Key, llvm::sampleprof::FunctionSamples * >, llvm::DenseMap< NodeRef, unsigned >, llvm::DenseMap< AliasCacheKey, llvm::Optional< bool > >, llvm::DenseMap< SmallVector< unsigned, 4 >, unsigned, OrdersTypeDenseMapInfo >, llvm::DenseMap< llvm::Value *, unsigned >, llvm::DenseMap< llvm::Value *, ScheduleData * >, llvm::DenseMap< llvm::Value *, llvm::SmallDenseMap< llvm::Value *, ScheduleData * > >, llvm::DenseMap< EdgeIdentifier, EdgeAttribute >, llvm::DenseMap< VertexIdentifier, VertexAttribute >, llvm::DenseMap< VertexIdentifier, NeighborSetT >, llvm::DenseMap< unsigned, TrieNode * >, llvm::SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, llvm::SmallDenseMap< KeyT, unsigned, N >, llvm::SmallDenseMap< T, ptrdiff_t >, llvm::SmallDenseMap< T, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< T >, detail::DenseSetPair< T > >, llvm::SmallDenseMap< Instruction *, unsigned >, llvm::SmallDenseMap< Instruction *, uint64_t >, llvm::SmallDenseMap< const GlobalValue *, ModRefInfo, 16 >, llvm::SmallDenseMap< llvm::Function *, llvm::DISubprogram *, 16 >, llvm::SmallDenseMap< unsigned, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< unsigned >, detail::DenseSetPair< unsigned > >, llvm::SmallDenseMap< LocPair, AliasResult, 8 >, llvm::SmallDenseMap< const Value *, bool, 8 >, llvm::SmallDenseMap< const llvm::GlobalValue *, unsigned, 4 >, llvm::SmallDenseMap< llvm::AnalysisKey *, bool, 8 >, llvm::SmallDenseMap< llvm::LazyCallGraph::RefSCC *, ptrdiff_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t >, llvm::SmallDenseMap< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * > >, detail::DenseSetPair< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * > > >, llvm::SmallDenseMap< const llvm::DISubprogram *, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< const llvm::DISubprogram * >, detail::DenseSetPair< const llvm::DISubprogram * > >, llvm::SmallDenseMap< llvm::Instruction *, llvm::Instruction * >, llvm::SmallDenseMap< llvm::SDValue, unsigned, 8 >, llvm::SmallDenseMap< unsigned, llvm::SDValue, 8 >, llvm::SmallDenseMap< unsigned, unsigned, 8 >, llvm::SmallDenseMap< unsigned, std::pair< unsigned, unsigned >, 8 >, llvm::SmallDenseMap< llvm::DomTreeNodeBase, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< llvm::DomTreeNodeBase >, detail::DenseSetPair< llvm::DomTreeNodeBase > >, llvm::SmallDenseMap< llvm::Value *, unsigned, N >, llvm::SmallDenseMap< NodePtr, SmallVector< NodePtr, 2 > >, llvm::SmallDenseMap< llvm::SDNode *, int >, llvm::SmallDenseMap< const llvm::Value *, int >, llvm::SmallDenseMap< llvm::BasicBlock *, SmallVector< llvm::BasicBlock *, 2 > >, llvm::SmallDenseMap< llvm::LLT, unsigned, 64 >, llvm::SmallDenseMap< llvm::Loop *, ptrdiff_t >, llvm::SmallDenseMap< llvm::Function *, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< llvm::Function * >, detail::DenseSetPair< llvm::Function * > >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, int, 4 >, llvm::SmallDenseMap< const llvm::Instruction *, unsigned, 32 >, llvm::SmallDenseMap< llvm::AnalysisKey *, llvm::TinyPtrVector< llvm::AnalysisKey * >, 2 >, llvm::SmallDenseMap< AnalysisID, llvm::ImmutablePass *, 8 >, llvm::SmallDenseMap< void *, std::pair< llvm::PointerUnion, uint64_t >, 4 >, llvm::SmallDenseMap< llvm::PointerIntPair< llvm::Value *, 1 >, ExitLimit >, llvm::SmallDenseMap< llvm::VPBasicBlock *, llvm::BasicBlock * >, llvm::SmallDenseMap< const llvm::VPBlockBase *, unsigned >, llvm::SmallDenseMap< unsigned, MDRange, 1 >, llvm::SmallDenseMap< uint32_t, llvm::bfi_detail::IrreducibleGraph::IrrNode *, 4 >, llvm::SmallDenseMap< ResourceRef, unsigned >, llvm::SmallDenseMap< llvm::Value *, int >, llvm::SmallDenseMap< llvm::PHINode *, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< llvm::PHINode * >, detail::DenseSetPair< llvm::PHINode * > >, llvm::SmallDenseMap< llvm::SelectInst *, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< llvm::SelectInst * >, detail::DenseSetPair< llvm::SelectInst * > >, llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >.
Public Types
using size_type = unsigned
using key_type = KeyT
using mapped_type = ValueT
using value_type = BucketT
using iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >
using const_iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT, true >
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
LLVM_NODISCARD bool empty () const
unsigned size () const
void reserve (size_type NumEntries)
Grow the densemap so that it can contain at least NumEntries items before resizing again.
void clear ()
size_type count (const_arg_type_t< KeyT > Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const_arg_type_t< KeyT > Val)
const_iterator find (const_arg_type_t< KeyT > Val) const
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
Alternate version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const_arg_type_t< KeyT > Val) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (KeyT &&Key, Ts &&... Args)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (const KeyT &Key, Ts &&... Args)
template<typename LookupKeyT >
std::pair< iterator, bool > insert_as (std::pair< KeyT, ValueT > &&KV, const LookupKeyT &Val)
Alternate version of insert() which allows a different, and possibly less expensive, key type.
template<typename InputIt >
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
value_type & FindAndConstruct (KeyT &&Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
const void * getPointerIntoBucketsArray () const
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
size_t getMemorySize () const
Return the approximate size (in bytes) of the actual map.
Public Member Functions inherited from llvm::DebugEpochBase
void incrementEpoch ()
Protected Member Functions
DenseMapBase ()=default
void destroyAll ()
void initEmpty ()
unsigned getMinBucketToReserveForEntries (unsigned NumEntries)
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT >
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > &other)
Static Protected Member Functions
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT >
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT>
class llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
Definition at line 85 of file DenseMap.h.
Member Typedef Documentation
const_iterator
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::const_iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT, true>
Definition at line 96 of file DenseMap.h.
iterator
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 95 of file DenseMap.h.
key_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::key_type = KeyT
Definition at line 91 of file DenseMap.h.
mapped_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::mapped_type = ValueT
Definition at line 92 of file DenseMap.h.
size_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size_type = unsigned
Definition at line 90 of file DenseMap.h.
value_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::value_type = BucketT
Definition at line 93 of file DenseMap.h.
Constructor & Destructor Documentation
DenseMapBase()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::DenseMapBase () protected default
Member Function Documentation
begin() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () inline
Definition at line 99 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::AliasSetTracker::clear(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::MachO::InterfaceFile::exports(), findIrreducibleHeaders(), FindMostPopularDest(), matchBitOpReduction(), PerformHeapAllocSRoA(), llvm::runIPSCCP(), llvm::SelectionDAGISel::runOnMachineFunction(), SpeculativelyExecuteBB(), llvm::MachO::InterfaceFile::symbols(), llvm::MachO::InterfaceFile::undefineds(), and unswitchNontrivialInvariants().
begin() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () const inline
Definition at line 111 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
clear()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear () inline
Definition at line 136 of file DenseMap.h.
References assert(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), llvm::DebugEpochBase::incrementEpoch(), and P.
Referenced by analyzeLoopUnrollCost(), llvm::opt::ArgList::ArgList(), llvm::PriorityWorklist< T, VectorT, MapT >::clear(), llvm::AliasSetTracker::clear(), llvm::AssumptionCache::clear(), llvm::LoopBlocksDFS::clear(), llvm::SCEVExpander::clear(), llvm::FunctionLoweringInfo::clear(), llvm::GCModuleInfo::clear(), llvm::GISelWorkList< N >::clear(), llvm::SDDbgInfo::clear(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::PredIteratorCache::clear(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::clear(), llvm::objcarc::ProvenanceAnalysis::clear(), llvm::rdf::Liveness::computeLiveIns(), llvm::ScalarEvolution::forgetAllLoops(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel(), llvm::SSAUpdater::Initialize(), llvm::MachineSSAUpdater::Initialize(), INITIALIZE_PASS(), mergeConstants(), llvm::orc::MaterializationResponsibility::notifyEmitted(), llvm::SlotTracker::purgeFunction(), llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory(), llvm::GISelCSEInfo::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::SMSchedule::reset(), llvm::MCStreamer::reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), llvm::SplitEditor::reset(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::VirtRegAuxInfo::weightCalcHelper(), llvm::InstCombineWorklist::Zap(), llvm::LLVMContextImpl::~LLVMContextImpl(), and llvm::ScalarEvolution::~ScalarEvolution().
copyFrom()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename OtherBaseT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > & other) inline protected
Definition at line 417 of file DenseMap.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::copyFrom().
count()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > size_type llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count (const_arg_type_t< KeyT > Val) const inline
Return 1 if the specified key is in the map, 0 otherwise.
Definition at line 171 of file DenseMap.h.
Referenced by llvm::jitlink::AtomGraph::addAbsoluteAtom(), llvm::jitlink::AtomGraph::addCommonAtom(), llvm::jitlink::AtomGraph::addDefinedAtom(), llvm::orc::MaterializationResponsibility::addDependencies(), llvm::jitlink::AtomGraph::addExternalAtom(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::VPlan::addVPValue(), llvm::HexagonSubtarget::CallMutation::apply(), buildClonedLoops(), llvm::DFAPacketizer::canReserveResources(), checkHoistValue(), computeImportForFunction(), computeImportForReferencedGlobals(), llvm::EHStreamer::computePadMap(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::count(), llvm::PriorityWorklist< T, VectorT, MapT >::count(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::count(), llvm::GISelCSEInfo::countOpcodeHit(), CreateGCRelocates(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::empty(), findArgumentCopyElisionCandidates(), findIrreducibleHeaders(), findProfitablePHIs(), llvm::LoopBlocksTraversal::finishPostorder(), llvm::formLCSSAForInstructions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::VPInterleavedAccessInfo::getInterleaveGroup(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::VPlan::getVPValue(), HandleInlinedEHPad(), handleNewDebugValue(), llvm::MachineFunction::hasCallSiteBeginLabel(), llvm::SlotIndexes::hasIndex(), llvm::LoopBlocksDFS::hasPreorder(), llvm::SSAUpdater::HasValueForBlock(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::MachineFunction::hasWasmLandingPadIndex(), llvm::HexagonCVIResource::HexagonCVIResource(), insertRelocationStores(), insertRematerializationStores(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::peelLoop(), relocationViaAlloca(), llvm::jitlink::AtomGraph::removeDefinedAtom(), llvm::MemoryDependenceResults::removeInstruction(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::DFAPacketizer::reserveResources(), rewrite(), selectIncomingValueForBlock(), sinkInstruction(), stashEntryDbgValues(), SwitchToLookupTable(), llvm::SCEVLoopAddRecRewriter::visitAddRecExpr(), and llvm::SCEVParameterRewriter::visitUnknown().
destroyAll()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll () inline protected
Definition at line 356 of file DenseMap.h.
References E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and P.
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::operator=(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::operator=(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::shrink_and_clear(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::~DenseMap(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::~SmallDenseMap().
empty()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > LLVM_NODISCARD bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty () const inline
Definition at line 122 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::LoopVectorizationLegality::canFoldTailByMasking(), CompactSwizzlableVector(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::StackProtector::copyToMachineFrameInfo(), createCallInst(), llvm::GISelWorkList< N >::empty(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::empty(), llvm::filterDeadComdatFunctions(), llvm::GISelWorkList< N >::finalize(), FindMostPopularDest(), llvm::MCRegisterInfo::getCodeViewRegNum(), llvm::MachineFunction::hasCallSiteLandingPad(), INITIALIZE_PASS(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::AddressPool::isEmpty(), llvm::TargetLoweringBase::isSlowDivBypassed(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::orc::DynamicLibrarySearchGenerator::operator()(), ProfitableToMerge(), llvm::GISelWorkList< N >::remove(), RemoveFromReverseMap(), ReorganizeVector(), llvm::SlotIndexes::runOnMachineFunction(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::FastISel::startNewBlock(), llvm::lto::thinBackend(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::InstCombineWorklist::Zap(), llvm::orc::MaterializationResponsibility::~MaterializationResponsibility(), llvm::MMIAddrLabelMap::~MMIAddrLabelMap(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), and llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::~ScopedHashTable().
end() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () inline
Definition at line 108 of file DenseMap.h.
Referenced by llvm::BasicAAResult::alias(), AreEquivalentPhiNodes(), llvm::AssumptionCache::assumptionsFor(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::at(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::begin(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), buildClonedLoopBlocks(), calculateIterationsToInvariance(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::cbegin(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::cend(), llvm::AliasSetTracker::clear(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), computeBaseDerivedRelocateMap(), llvm::EHStreamer::computeCallSiteTable(), computeDomSubtreeCost(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::MIRPrinter::convertStackObjects(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::StackProtector::copyToMachineFrameInfo(), llvm::AliasSetTracker::copyValue(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::VPRecipeBuilder::createEdgeMask(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::orc::MaterializationResponsibility::delegate(), llvm::MachineFunction::DeleteMachineInstr(), llvm::AliasSetTracker::deleteValue(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::InstrEmitter::EmitDbgValue(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::end(), llvm::FunctionLoweringInfo::StatepointSpillMap::end(), llvm::SDDbgInfo::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::ScalarEvolution::eraseValueFromMap(), llvm::MachO::InterfaceFile::exports(), llvm::filterDeadComdatFunctions(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), llvm::jitlink::AtomGraph::findAtomByName(), llvm::jitlink::AtomGraph::findDefinedAtomByName(), findIrreducibleHeaders(), FindLIVLoopCondition(), FindMostPopularDest(), findProfitablePHIs(), llvm::SelectionDAGBuilder::findValue(), FoldCondBranchOnPHI(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::OptionRegistry::get(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::jitlink::AtomGraph::getAtomByName(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::MCRegisterInfo::getCodeViewRegNum(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getExistingValueState(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotTracker::getGlobalSlot(), llvm::SlotTracker::getGUIDSlot(), llvm::SelectionDAG::getHeapAllocSite(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SwingSchedulerDAG::getInstrBaseReg(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), getIRBlockFromSlot(), llvm::SlotTracker::getLocalSlot(), getMappedReg(), llvm::InterleaveGroup< InstTy >::getMember(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::SelectionDAGBuilder::getNodeForIRValue(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::PassRegistry::getPassInfo(), llvm::object::ELFObjectFileBase::getPltAddresses(), getPoisonFor(), llvm::LoopBlocksDFS::getPostorder(), llvm::SCEVUnionPredicate::getPredicatesForExpr(), getPredState(), llvm::object::MinidumpFile::getRawStream(), getSCCNum(), llvm::SelectionDAG::getSDCallSiteInfo(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::SIMachineFunctionInfo::getSGPRToVGPRSpills(), getSuccState(), llvm::ValueEnumerator::getTypeID(), getUnwindDestToken(), getUnwindDestTokenHelper(), getValueFromCondition(), llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::VPRecipeBuilder::handleReplication(), llvm::LoopBlocksDFS::hasPostorder(), llvm::SCEVUnionPredicate::implies(), INITIALIZE_PASS(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::InterleaveGroup< InstTy >::insertMember(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::isEqual(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::mca::LSUnitBase::isValidGroupID(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::AssumptionCacheTracker::lookupAssumptionCache(), llvm::AMDGPUArgumentUsageInfo::lookupFuncArgInfo(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::lowerArguments(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), matchBitOpReduction(), mergeConstants(), llvm::orc::EHFrameRegistrationPlugin::notifyRemovingModule(), llvm::orc::MaterializationResponsibility::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), llvm::operator==(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), PerformHeapAllocSRoA(), llvm::MIPrinter::print(), llvm::FileInfo::print(), llvm::PredicatedScalarEvolution::print(), llvm::GCNRPTracker::printLiveRegs(), llvm::MIPrinter::printStackObjectReference(), ProfitableToMerge(), llvm::jitlink::prune(), llvm::GISelWorkList< N >::remove(), llvm::InstCombineWorklist::Remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), removeDuplicateGCPtrs(), RemoveFromReverseMap(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::SlotIndexes::repairIndexesInRange(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), reportMismatch(), rewriteGEPAsOffset(), llvm::lto::LTO::run(), llvm::LoadAndStorePromoter::run(), llvm::runIPSCCP(), llvm::SelectionDAGISel::runOnMachineFunction(), scanPHIsAndUpdateValueMap(), llvm::FastISel::selectExtractValue(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), simplifyTerminatorLeadingToRet(), sinkThroughTriviallyReplaceablePHI(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::size(), speculatePHIs(), SpeculativelyExecuteBB(), llvm::MachO::InterfaceFile::symbols(), llvm::thinLTOInternalizeModule(), llvm::thinLTOResolvePrevailingInModule(), llvm::JumpThreadingPass::ThreadEdge(), tryToElideArgumentCopy(), llvm::MachO::InterfaceFile::undefineds(), llvm::AssumptionCache::unregisterAssumption(), llvm::MachineFunction::updateCallSiteInfo(), useFuncSeen(), and llvm::InstCombiner::visitShuffleVectorInst().
end() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () const inline
Definition at line 118 of file DenseMap.h.
erase() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (const KeyT & Val) inline
Definition at line 298 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey().
Referenced by llvm::HexagonSubtarget::CallMutation::apply(), llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::compareLoops(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::orc::MaterializationResponsibility::delegate(), deleteDeadInstruction(), llvm::AliasSetTracker::deleteValue(), llvm::orc::MaterializationUnit::doDiscard(), llvm::SDDbgInfo::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::opt::ArgList::eraseArg(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::ScalarEvolution::eraseValueFromMap(), llvm::filterDeadComdatFunctions(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::OrderedInstructions::invalidateBlock(), llvm::orc::EHFrameRegistrationPlugin::notifyRemovingModule(), llvm::PriorityWorklist< T, VectorT, MapT >::pop_back(), llvm::GISelWorkList< N >::pop_back_val(), llvm::ValueEnumerator::purgeFunction(), llvm::GISelWorkList< N >::remove(), llvm::InstCombineWorklist::Remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), llvm::jitlink::AtomGraph::removeDefinedAtom(), llvm::MemorySSA::removeFromLists(), RemoveFromReverseMap(), llvm::ValueHandleBase::RemoveFromUseList(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::InstCombineWorklist::RemoveOne(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::orc::MaterializationResponsibility::replace(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::AssumptionCache::unregisterAssumption(), llvm::MachineFunction::updateCallSiteInfo(), and llvm::LoopInfoBase< BlockT, LoopT >::verify().
erase() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (iterator I) inline
Definition at line 309 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and I.
find() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) inline
Definition at line 176 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::BasicAAResult::alias(), AreEquivalentPhiNodes(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::at(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::begin(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), buildClonedLoopBlocks(), calculateIterationsToInvariance(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::cbegin(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::cend(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), computeBaseDerivedRelocateMap(), llvm::EHStreamer::computeCallSiteTable(), computeDomSubtreeCost(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::MIRPrinter::convertStackObjects(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::StackProtector::copyToMachineFrameInfo(), llvm::VPRecipeBuilder::createBlockInMask(), createCallInst(), llvm::VPRecipeBuilder::createEdgeMask(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::orc::MaterializationResponsibility::delegate(), llvm::MachineFunction::DeleteMachineInstr(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::InstrEmitter::EmitDbgValue(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::end(), llvm::SDDbgInfo::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::filterDeadComdatFunctions(), llvm::FunctionLoweringInfo::StatepointSpillMap::find(), llvm::LazyCallGraph::RefSCC::find(), llvm::jitlink::AtomGraph::findAtomByName(), llvm::jitlink::AtomGraph::findDefinedAtomByName(), FindLIVLoopCondition(), findProfitablePHIs(), llvm::SelectionDAGBuilder::findValue(), llvm::SSAUpdater::FindValueForBlock(), FoldCondBranchOnPHI(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::OptionRegistry::get(), llvm::GraphDiff< NodePtr, InverseGraph >::getAddedChildren(), llvm::jitlink::AtomGraph::getAtomByName(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::MCRegisterInfo::getCodeViewRegNum(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getExistingValueState(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotTracker::getGlobalSlot(), llvm::mca::LSUnitBase::getGroup(), llvm::SlotTracker::getGUIDSlot(), llvm::SelectionDAG::getHeapAllocSite(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SwingSchedulerDAG::getInstrBaseReg(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::VPInterleavedAccessInfo::getInterleaveGroup(), getIRBlockFromSlot(), llvm::SlotTracker::getLocalSlot(), getMappedReg(), llvm::InterleaveGroup< InstTy >::getMember(), llvm::TargetLibraryInfo::getName(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::SelectionDAGBuilder::getNodeForIRValue(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::PassRegistry::getPassInfo(), llvm::object::ELFObjectFileBase::getPltAddresses(), getPoisonFor(), llvm::LoopBlocksDFS::getPostorder(), llvm::SCEVUnionPredicate::getPredicatesForExpr(), getPredState(), llvm::object::MinidumpFile::getRawStream(), getSCCNum(), llvm::SelectionDAG::getSDCallSiteInfo(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::SIMachineFunctionInfo::getSGPRToVGPRSpills(), getSuccState(), llvm::ValueEnumerator::getTypeID(), getUnwindDestToken(), getUnwindDestTokenHelper(), getValueFromCondition(), llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::VPRecipeBuilder::handleReplication(), llvm::LoopBlocksDFS::hasPostorder(), llvm::GraphDiff< NodePtr, InverseGraph >::ignoreChild(), llvm::SCEVUnionPredicate::implies(), INITIALIZE_PASS(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::InterleaveGroup< InstTy >::insertMember(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::isEqual(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::mca::LSUnitBase::isValidGroupID(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::AMDGPUArgumentUsageInfo::lookupFuncArgInfo(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::lowerArguments(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), matchBitOpReduction(), mergeConstants(), llvm::orc::EHFrameRegistrationPlugin::notifyRemovingModule(), llvm::orc::MaterializationResponsibility::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), llvm::operator==(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MIPrinter::print(), llvm::FileInfo::print(), llvm::PredicatedScalarEvolution::print(), llvm::GCNRPTracker::printLiveRegs(), llvm::MIPrinter::printStackObjectReference(), ProfitableToMerge(), llvm::jitlink::prune(), llvm::GISelWorkList< N >::remove(), llvm::InstCombineWorklist::Remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), removeDuplicateGCPtrs(), llvm::MemorySSA::removeFromLists(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::SlotIndexes::repairIndexesInRange(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), reportMismatch(), rewriteGEPAsOffset(), llvm::lto::LTO::run(), llvm::LoadAndStorePromoter::run(), llvm::SelectionDAGISel::runOnMachineFunction(), scanPHIsAndUpdateValueMap(), llvm::FastISel::selectExtractValue(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), simplifyTerminatorLeadingToRet(), sinkInstruction(), sinkThroughTriviallyReplaceablePHI(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::InOutEdgeView< isConst, isOut >::size(), speculatePHIs(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::thinLTOInternalizeModule(), llvm::thinLTOResolvePrevailingInModule(), llvm::JumpThreadingPass::ThreadEdge(), tryToElideArgumentCopy(), unswitchNontrivialInvariants(), llvm::MachineFunction::updateCallSiteInfo(), useFuncSeen(), and llvm::InstCombiner::visitShuffleVectorInst().
find() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) const inline
Definition at line 182 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
find_as() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<class LookupKeyT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) inline
Alternate version of find() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 195 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::AssumptionCache::assumptionsFor(), llvm::AliasSetTracker::copyValue(), llvm::AliasSetTracker::deleteValue(), llvm::ScalarEvolution::eraseValueFromMap(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::AssumptionCacheTracker::lookupAssumptionCache(), and llvm::AssumptionCache::unregisterAssumption().
find_as() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<class LookupKeyT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) const inline
Definition at line 202 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
FindAndConstruct() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > value_type & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (const KeyT & Key) inline
Definition at line 317 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[](), and llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::operator[]().
FindAndConstruct() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > value_type & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (KeyT && Key) inline
Definition at line 329 of file DenseMap.h.
getEmptyKey()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey () inline static protected
Definition at line 449 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::grow(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::swap().
getHashValue() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const KeyT & Val) inline static protected
Definition at line 440 of file DenseMap.h.
getHashValue() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename LookupKeyT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const LookupKeyT & Val) inline static protected
Definition at line 445 of file DenseMap.h.
getMemorySize()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > size_t llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMemorySize () const inline
Return the approximate size (in bytes) of the actual map.
This is just the raw memory used by DenseMap. If entries are pointers to objects, the size of the referenced objects are not included.
Definition at line 668 of file DenseMap.h.
getMinBucketToReserveForEntries()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries (unsigned NumEntries) inline protected
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
Definition at line 382 of file DenseMap.h.
References llvm::NextPowerOf2().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve().
getPointerIntoBucketsArray()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const void * llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getPointerIntoBucketsArray () const inline
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
In conjunction with the previous method, this can be used to determine whether an insertion caused the DenseMap to reallocate.
Definition at line 351 of file DenseMap.h.
getTombstoneKey()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey () inline static protected
Definition at line 455 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::grow(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::swap().
initEmpty()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty () inline protected
Definition at line 369 of file DenseMap.h.
References assert(), B, E, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::grow(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::init(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::init(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::shrink_and_clear().
insert() [1/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (const std::pair< KeyT, ValueT > & KV) inline
Definition at line 221 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::InstCombineWorklist::Add(), AddAliasScopeMetadata(), addEdge(), llvm::InstCombineWorklist::AddInitialGroup(), analyzeLoopUnrollCost(), llvm::opt::ArgList::append(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), buildClonedLoops(), collectEHScopeMembers(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), computeBaseDerivedRelocateMap(), computeDomSubtreeCost(), computeImportForFunction(), llvm::rdf::Liveness::computeLiveIns(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::MIRPrinter::convertStackObjects(), llvm::mca::LSUnitBase::createMemoryGroup(), llvm::orc::MaterializationResponsibility::defineMaterializing(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap(), findArgumentCopyElisionCandidates(), findProfitablePHIs(), llvm::xray::BlockIndexer::flush(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), gatherIncomingValuesToPhi(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::Attributor::getAAFor(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::FunctionLoweringInfo::getCatchPadExceptionPointerVReg(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::MemoryDependenceResults::getDependency(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getLocalId(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::object::ELFObjectFileBase::getPltAddresses(), llvm::ScalarEvolution::getSCEV(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::MIRParserImpl::initializeConstantPool(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::MIRParserImpl::initializeJumpTableInfo(), initSlots2BasicBlocks(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::insert(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DwarfFile::insertDIE(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), isNonEscapingLocalObject(), isSafeAndProfitableToSpeculateAroundPHI(), IsValueFullyAvailableInBlock(), loadObj(), mapValueToSlot(), matchBitOpReduction(), llvm::xray::mergeProfilesByThread(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::operator[](), pushDepHeight(), llvm::TargetInstrInfo::reassociateOps(), llvm::ARMFunctionInfo::recordCPEClone(), llvm::PassRegistry::registerPass(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), shouldConvert(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap(), sortLocalVars(), speculatePHIs(), tryToElideArgumentCopy(), llvm::LoopBlocksTraversal::visitPreorder(), and llvm::VirtRegAuxInfo::weightCalcHelper().
insert() [2/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename InputIt > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (InputIt I, InputIt E) inline
insert - Range insertion of pairs.
Definition at line 293 of file DenseMap.h.
References E, I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
insert() [3/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (std::pair< KeyT, ValueT > && KV) inline
Definition at line 228 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
insert_as()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename LookupKeyT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_as (std::pair< KeyT, ValueT > && KV, const LookupKeyT & Val) inline
Alternate version of insert() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 275 of file DenseMap.h.
isPointerIntoBucketsArray()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray (const void * Ptr) const inline
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
either to a key or value in the DenseMap).
Definition at line 344 of file DenseMap.h.
Referenced by llvm::ValueHandleBase::RemoveFromUseList().
lookup()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup (const_arg_type_t< KeyT > Val) const inline
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 211 of file DenseMap.h.
Referenced by llvm::addClonedBlockToLoopInfo(), analyzeLoopUnrollCost(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), llvm::compareLoops(), llvm::MachObjectWriter::computeSymbolTable(), cse(), dropDeadSymbols(), EvaluateExpression(), findIrreducibleHeaders(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::Attributor::getAAFor(), llvm::MachineFunction::getCallSiteBeginLabel(), getConstantEvolvingPHIOperands(), llvm::DebugCounter::getCounterInfo(), llvm::DwarfFile::getDIE(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), getNewSource(), llvm::MachObjectWriter::getSectionAddress(), llvm::MCStreamer::GetSymbolOrder(), llvm::objcarc::GetUnderlyingObjCPtrCached(), llvm::MachineFunction::getWasmLandingPadIndex(), INITIALIZE_PASS(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::orc::ObjectLinkingLayerJITLinkContext::lookup(), llvm::DwarfDebug::lookupCU(), llvm::MetadataLoader::MetadataLoaderImpl::lookupSubprogramForFunction(), llvm::AMDGPUUnmangledLibFunc::parseFuncName(), llvm::GVNHoist::rank(), speculatePHINodeLoads(), llvm::stripDebugInfo(), llvm::MemorySSAUpdater::updateForClonedLoop(), and llvm::LoopInfoBase< BlockT, LoopT >::verify().
moveFromOldBuckets()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets (BucketT * OldBucketsBegin, BucketT * OldBucketsEnd) inline protected
Definition at line 391 of file DenseMap.h.
References assert(), B, E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty().
Referenced by llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::grow(), and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::grow().
operator[]() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (const KeyT & Key) inline
Definition at line 325 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct().
operator[]() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (KeyT && Key) inline
Definition at line 337 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct().
reserve()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve (size_type NumEntries) inline
Grow the densemap so that it can contain at least NumEntries items before resizing again.
Definition at line 129 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries(), and llvm::DebugEpochBase::incrementEpoch().
Referenced by llvm::InstCombineWorklist::AddInitialGroup(), llvm::GISelWorkList< N >::finalize(), findArgumentCopyElisionCandidates(), findBestInsertionSet(), llvm::cfg::LegalizeUpdates(), and llvm::LoopBlocksDFS::LoopBlocksDFS().
size()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size () const inline
Definition at line 125 of file DenseMap.h.
Referenced by llvm::MCStreamer::AssignFragment(), BatchCommitValueTo(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), findArgumentCopyElisionCandidates(), findIrreducibleHeaders(), llvm::InterleaveGroup< InstTy >::getNumMembers(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::isEqual(), IsEquivalentPHI(), llvm::cfg::LegalizeUpdates(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::orc::EHFrameRegistrationPlugin::notifyRemovingAllModules(), llvm::operator==(), llvm::AliasSetTracker::print(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::shrink_and_clear(), llvm::PriorityWorklist< T, VectorT, MapT >::size(), llvm::GISelWorkList< N >::size(), and SwitchToLookupTable().
try_emplace() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (const KeyT & Key, Ts &&... Args) inline
Definition at line 255 of file DenseMap.h.
try_emplace() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (KeyT && Key, Ts &&... Args) inline
Definition at line 236 of file DenseMap.h.
Referenced by llvm::MachO::InterfaceFile::addSymbol(), llvm::object::MinidumpFile::create(), llvm::GISelWorkList< N >::finalize(), llvm::pdb::SymbolCache::getOrCreateFieldListMember(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::GISelWorkList< N >::insert(), and llvm::codeview::GlobalTypeTableBuilder::insertRecordAs().
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseMap.h