LLVM: llvm::SystemZInstPrinter Class Reference
llvm::SystemZInstPrinter Class Reference
#include "Target/SystemZ/MCTargetDesc/SystemZInstPrinter.h"
Public Member Functions
SystemZInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printRegName (raw_ostream &O, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
virtual void printInst (const MCInst *MI, raw_ostream &OS, StringRef Annot, const MCSubtargetInfo &STI)=0
Print the specified MCInst to the specified raw_ostream.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyle () const
void setPrintHexStyle (HexStyle::Style Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static void printAddress (unsigned Base, int64_t Disp, unsigned Index, raw_ostream &O)
static void printOperand (const MCOperand &MO, const MCAsmInfo *MAI, raw_ostream &O)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 23 of file SystemZInstPrinter.h.
Constructor & Destructor Documentation
SystemZInstPrinter()
llvm::SystemZInstPrinter::SystemZInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 25 of file SystemZInstPrinter.h.
Member Function Documentation
getRegisterName()
static const char * llvm::SystemZInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by printAddress(), printOperand(), and printRegName().
printAddress()
void SystemZInstPrinter::printAddress (unsigned Base, int64_t Disp, unsigned Index, raw_ostream & O) static
Definition at line 26 of file SystemZInstPrinter.cpp.
References getRegisterName().
Referenced by llvm::SystemZAsmPrinter::PrintAsmMemoryOperand().
printInst()
void SystemZInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) override virtual
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 54 of file SystemZInstPrinter.cpp.
References MI, llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::SystemZInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
printOperand()
void SystemZInstPrinter::printOperand (const MCOperand & MO, const MCAsmInfo * MAI, raw_ostream & O) static
Definition at line 42 of file SystemZInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by llvm::SystemZAsmPrinter::PrintAsmOperand().
printRegName()
void SystemZInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 61 of file SystemZInstPrinter.cpp.
References getRegisterName().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/MCTargetDesc/SystemZInstPrinter.h
lib/Target/SystemZ/MCTargetDesc/SystemZInstPrinter.cpp