LLVM: llvm::MachineDominatorTree Class Reference
llvm::MachineDominatorTree Class Reference
DominatorTree Class - Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
#include "llvm/CodeGen/MachineDominators.h"
Public Member Functions
MachineDominatorTree ()
DomTreeBase< MachineBasicBlock > & getBase ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
const SmallVectorImpl< MachineBasicBlock * > & getRoots () const
getRoots - Return the root blocks of the current CFG.
MachineBasicBlock * getRoot () const
MachineDomTreeNode * getRootNode () const
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
bool dominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool dominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool dominates (const MachineInstr *A, const MachineInstr *B) const
bool properlyDominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool properlyDominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
MachineBasicBlock * findNearestCommonDominator (MachineBasicBlock *A, MachineBasicBlock *B)
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B.
MachineDomTreeNode * operator[] (MachineBasicBlock *BB) const
MachineDomTreeNode * getNode (MachineBasicBlock *BB) const
getNode - return the (Post)DominatorTree node for the specified basic block.
MachineDomTreeNode * addNewBlock (MachineBasicBlock *BB, MachineBasicBlock *DomBB)
addNewBlock - Add a new node to the dominator tree information.
void changeImmediateDominator (MachineBasicBlock *N, MachineBasicBlock *NewIDom)
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
void changeImmediateDominator (MachineDomTreeNode *N, MachineDomTreeNode *NewIDom)
void eraseNode (MachineBasicBlock *BB)
eraseNode - Removes a node from the dominator tree.
void splitBlock (MachineBasicBlock *NewBB)
splitBlock - BB is split and now it has one successor.
bool isReachableFromEntry (const MachineBasicBlock *A)
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void verifyAnalysis () const override
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
void print (raw_ostream &OS, const Module *) const override
print - Print out the internal state of the pass.
void recordSplitCriticalEdge (MachineBasicBlock *FromBB, MachineBasicBlock *ToBB, MachineBasicBlock *NewBB)
Record that the critical edge (FromBB, ToBB) has been split with NewBB.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
DominatorTree Class - Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
Definition at line 46 of file MachineDominators.h.
Constructor & Destructor Documentation
MachineDominatorTree()
MachineDominatorTree::MachineDominatorTree ()
Definition at line 56 of file MachineDominators.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineDominatorTreePass().
Member Function Documentation
addNewBlock()
MachineDomTreeNode * llvm::MachineDominatorTree::addNewBlock (MachineBasicBlock * BB, MachineBasicBlock * DomBB) inline
addNewBlock - Add a new node to the dominator tree information.
This creates a new node as a child of DomBB dominator node,linking it into the children list of the immediate dominator.
Definition at line 181 of file MachineDominators.h.
Referenced by loadSRsrcFromVGPR().
changeImmediateDominator() [1/2]
void llvm::MachineDominatorTree::changeImmediateDominator (MachineBasicBlock * N, MachineBasicBlock * NewIDom) inline
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
Definition at line 190 of file MachineDominators.h.
References N.
Referenced by loadSRsrcFromVGPR().
changeImmediateDominator() [2/2]
void llvm::MachineDominatorTree::changeImmediateDominator (MachineDomTreeNode * N, MachineDomTreeNode * NewIDom) inline
Definition at line 196 of file MachineDominators.h.
References N.
dominates() [1/3]
bool llvm::MachineDominatorTree::dominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 118 of file MachineDominators.h.
References A, and B.
dominates() [2/3]
bool llvm::MachineDominatorTree::dominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 112 of file MachineDominators.h.
References A, and B.
Referenced by dominatesAllUsesOf(), llvm::rdf::Liveness::getAllReachingDefs(), hoistAndMergeSGPRInits(), isReachable(), loadSRsrcFromVGPR(), oneUseDominatesOtherUses(), replaceDominatedUses(), and sortBlocks().
dominates() [3/3]
bool llvm::MachineDominatorTree::dominates (const MachineInstr * A, const MachineInstr * B) const inline
Definition at line 126 of file MachineDominators.h.
References A, B, llvm::MachineBasicBlock::begin(), and I.
eraseNode()
void llvm::MachineDominatorTree::eraseNode (MachineBasicBlock * BB) inline
eraseNode - Removes a node from the dominator tree.
Block must not dominate any other blocks. Removes node from its immediate dominator's children list. Deletes dominator node associated with basic block BB.
Definition at line 205 of file MachineDominators.h.
findNearestCommonDominator()
MachineBasicBlock * llvm::MachineDominatorTree::findNearestCommonDominator (MachineBasicBlock * A, MachineBasicBlock * B) inline
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B.
If there is no such block then return NULL.
Definition at line 159 of file MachineDominators.h.
References A, and B.
Referenced by hoistAndMergeSGPRInits().
getAnalysisUsage()
void llvm::MachineDominatorTree::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
getBase()
DomTreeBase< MachineBasicBlock > & llvm::MachineDominatorTree::getBase () inline
Definition at line 83 of file MachineDominators.h.
Referenced by llvm::AsmPrinter::EmitFunctionBody().
getNode()
MachineDomTreeNode * llvm::MachineDominatorTree::getNode (MachineBasicBlock * BB) const inline
getNode - return the (Post)DominatorTree node for the specified basic block.
This is the same as using operator[] on this class.
Definition at line 173 of file MachineDominators.h.
Referenced by llvm::rdf::Liveness::getNearestAliasedRef().
getRoot()
MachineBasicBlock * llvm::MachineDominatorTree::getRoot () const inline
Definition at line 100 of file MachineDominators.h.
Referenced by verifyAnalysis().
getRootNode()
MachineDomTreeNode * llvm::MachineDominatorTree::getRootNode () const inline
Definition at line 105 of file MachineDominators.h.
Referenced by llvm::GraphTraits< MachineDominatorTree * >::getEntryNode(), and verifyAnalysis().
getRoots()
const SmallVectorImpl< MachineBasicBlock * > & llvm::MachineDominatorTree::getRoots () const inline
getRoots - Return the root blocks of the current CFG.
This may include multiple blocks if we are computing post dominators. For forward dominators, this will always be a single block (the entry node).
Definition at line 95 of file MachineDominators.h.
isReachableFromEntry()
bool llvm::MachineDominatorTree::isReachableFromEntry (const MachineBasicBlock * A) inline
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 219 of file MachineDominators.h.
References A.
operator[]()
MachineDomTreeNode * llvm::MachineDominatorTree::operator[] (MachineBasicBlock * BB) const inline
Definition at line 165 of file MachineDominators.h.
print()
void MachineDominatorTree::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 84 of file MachineDominators.cpp.
properlyDominates() [1/2]
bool llvm::MachineDominatorTree::properlyDominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 151 of file MachineDominators.h.
References A, and B.
properlyDominates() [2/2]
bool llvm::MachineDominatorTree::properlyDominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 145 of file MachineDominators.h.
References A, and B.
Referenced by hoistAndMergeSGPRInits().
recordSplitCriticalEdge()
void llvm::MachineDominatorTree::recordSplitCriticalEdge (MachineBasicBlock * FromBB, MachineBasicBlock * ToBB, MachineBasicBlock * NewBB) inline
Record that the critical edge (FromBB, ToBB) has been split with NewBB.
This is best to use this method instead of directly update the underlying information, because this helps mitigating the number of time the DT information is invalidated.
Note
Do not use this method with regular edges.
To benefit from the compile time improvement incurred by this method, the users of this method have to limit the queries to the DT interface between two edges splitting. In other words, they have to pack the splitting of critical edges as much as possible.
Definition at line 242 of file MachineDominators.h.
References assert(), llvm::SmallSet< T, N, C >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
releaseMemory()
void MachineDominatorTree::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 61 of file MachineDominators.cpp.
References llvm::SmallVectorImpl< T >::clear().
runOnMachineFunction()
bool MachineDominatorTree::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 48 of file MachineDominators.cpp.
References llvm::SmallVectorImpl< T >::clear(), and F.
splitBlock()
void llvm::MachineDominatorTree::splitBlock (MachineBasicBlock * NewBB) inline
splitBlock - BB is split and now it has one successor.
Update dominator tree to reflect this change.
Definition at line 212 of file MachineDominators.h.
verifyAnalysis()
void MachineDominatorTree::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 66 of file MachineDominators.cpp.
References llvm::errs(), F, llvm::MachineBasicBlock::getParent(), getRoot(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), getRootNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), and VerifyMachineDomInfo.
Member Data Documentation
ID
char MachineDominatorTree::ID = 0 static
Definition at line 79 of file MachineDominators.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineDominators.h
lib/CodeGen/MachineDominators.cpp