LLVM: llvm::InitLLVM Class Reference
llvm::InitLLVM Class Reference
#include "llvm/Support/InitLLVM.h"
Public Member Functions
InitLLVM (int &Argc, const char **&Argv)
InitLLVM (int &Argc, char **&Argv)
~InitLLVM ()
Detailed Description
Definition at line 33 of file InitLLVM.h.
Constructor & Destructor Documentation
InitLLVM() [1/2]
InitLLVM::InitLLVM (int & Argc, const char **& Argv)
Definition at line 24 of file InitLLVM.cpp.
References llvm::errorCodeToError(), llvm::sys::windows::GetCommandLineArguments(), llvm::install_out_of_memory_new_handler(), and llvm::sys::PrintStackTraceOnErrorSignal().
InitLLVM() [2/2]
llvm::InitLLVM::InitLLVM (int & Argc, char **& Argv) inline
Definition at line 36 of file InitLLVM.h.
~InitLLVM()
InitLLVM::~InitLLVM ()
Definition at line 52 of file InitLLVM.cpp.
References llvm::llvm_shutdown().
The documentation for this class was generated from the following files:
include/llvm/Support/InitLLVM.h
lib/Support/InitLLVM.cpp