LLVM: llvm::VPPredInstPHIRecipe Class Reference
llvm::VPPredInstPHIRecipe Class Reference
VPPredInstPHIRecipe is a recipe for generating the phi nodes needed when control converges back from a Branch-on-Mask.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPPredInstPHIRecipe (Instruction *PredInst)
Construct a VPPredInstPHIRecipe given PredInst whose value needs a phi nodes after merging back from a Branch-on-Mask.
~VPPredInstPHIRecipe () override=default
void execute (VPTransformState &State) override
Generates phi nodes for live-outs as needed to retain SSA form.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Detailed Description
VPPredInstPHIRecipe is a recipe for generating the phi nodes needed when control converges back from a Branch-on-Mask.
The phi nodes are needed in order to merge values that are set under such a branch and feed their uses. The phi nodes can be scalar or vector depending on the users of the value. This recipe works in concert with VPBranchOnMaskRecipe.
Definition at line 929 of file VPlan.h.
Constructor & Destructor Documentation
VPPredInstPHIRecipe()
llvm::VPPredInstPHIRecipe::VPPredInstPHIRecipe (Instruction * PredInst) inline
Construct a VPPredInstPHIRecipe given PredInst whose value needs a phi nodes after merging back from a Branch-on-Mask.
Definition at line 936 of file VPlan.h.
~VPPredInstPHIRecipe()
llvm::VPPredInstPHIRecipe::~VPPredInstPHIRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPPredInstPHIRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 941 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPPredInstPHIRecipe::execute (VPTransformState & State) override virtual
Generates phi nodes for live-outs as needed to retain SSA form.
Implements llvm::VPRecipeBase.
Definition at line 7159 of file LoopVectorize.cpp.
References assert(), llvm::VPTransformState::Builder, llvm::VectorizerValueMap::getScalarValue(), llvm::VectorizerValueMap::getVectorValue(), llvm::VectorizerValueMap::hasVectorValue(), llvm::VPTransformState::Instance, llvm::VectorizerValueMap::resetScalarValue(), llvm::VectorizerValueMap::resetVectorValue(), and llvm::VPTransformState::ValueMap.
print()
void VPPredInstPHIRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 683 of file VPlan.cpp.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp