LLVM: llvm::FullDependence Class Reference
llvm::FullDependence Class Reference final
FullDependence - This class represents a dependence between two memory references in a function.
#include "llvm/Analysis/DependenceAnalysis.h"
Public Member Functions
FullDependence (Instruction *Src, Instruction *Dst, bool LoopIndependent, unsigned Levels)
bool isLoopIndependent () const override
isLoopIndependent - Returns true if this is a loop-independent dependence.
bool isConfused () const override
isConfused - Returns true if this dependence is confused (the compiler understands nothing and makes worst-case assumptions).
bool isConsistent () const override
isConsistent - Returns true if this dependence is consistent (occurs every time the source and destination are executed).
unsigned getLevels () const override
getLevels - Returns the number of common loops surrounding the source and destination of the dependence.
unsigned getDirection (unsigned Level) const override
getDirection - Returns the direction associated with a particular level.
const SCEV * getDistance (unsigned Level) const override
getDistance - Returns the distance (or NULL) associated with a particular level.
bool isPeelFirst (unsigned Level) const override
isPeelFirst - Returns true if peeling the first iteration from this loop will break this dependence.
bool isPeelLast (unsigned Level) const override
isPeelLast - Returns true if peeling the last iteration from this loop will break this dependence.
bool isSplitable (unsigned Level) const override
isSplitable - Returns true if splitting the loop will break the dependence.
bool isScalar (unsigned Level) const override
isScalar - Returns true if a particular level is scalar; that is, if no subscript in the source or destination mention the induction variable associated with the loop at this level.
Public Member Functions inherited from llvm::Dependence
Dependence (Instruction *Source, Instruction *Destination)
virtual ~Dependence ()
Instruction * getSrc () const
getSrc - Returns the source instruction for this dependence.
Instruction * getDst () const
getDst - Returns the destination instruction for this dependence.
bool isInput () const
isInput - Returns true if this is an input dependence.
bool isOutput () const
isOutput - Returns true if this is an output dependence.
bool isFlow () const
isFlow - Returns true if this is a flow (aka true) dependence.
bool isAnti () const
isAnti - Returns true if this is an anti dependence.
bool isOrdered () const
isOrdered - Returns true if dependence is Output, Flow, or Anti
bool isUnordered () const
isUnordered - Returns true if dependence is Input
virtual bool isLoopIndependent () const
isLoopIndependent - Returns true if this is a loop-independent dependence.
virtual bool isConfused () const
isConfused - Returns true if this dependence is confused (the compiler understands nothing and makes worst-case assumptions).
virtual bool isConsistent () const
isConsistent - Returns true if this dependence is consistent (occurs every time the source and destination are executed).
virtual unsigned getLevels () const
getLevels - Returns the number of common loops surrounding the source and destination of the dependence.
virtual unsigned getDirection (unsigned Level) const
getDirection - Returns the direction associated with a particular level.
virtual const SCEV * getDistance (unsigned Level) const
getDistance - Returns the distance (or NULL) associated with a particular level.
virtual bool isPeelFirst (unsigned Level) const
isPeelFirst - Returns true if peeling the first iteration from this loop will break this dependence.
virtual bool isPeelLast (unsigned Level) const
isPeelLast - Returns true if peeling the last iteration from this loop will break this dependence.
virtual bool isSplitable (unsigned Level) const
isSplitable - Returns true if splitting this loop will break the dependence.
virtual bool isScalar (unsigned Level) const
isScalar - Returns true if a particular level is scalar; that is, if no subscript in the source or destination mention the induction variable associated with the loop at this level.
const Dependence * getNextPredecessor () const
getNextPredecessor - Returns the value of the NextPredecessor field.
const Dependence * getNextSuccessor () const
getNextSuccessor - Returns the value of the NextSuccessor field.
void setNextPredecessor (const Dependence *pred)
setNextPredecessor - Sets the value of the NextPredecessor field.
void setNextSuccessor (const Dependence *succ)
setNextSuccessor - Sets the value of the NextSuccessor field.
void dump (raw_ostream &OS) const
dump - For debugging purposes, dumps a dependence to OS.
Friends
class DependenceInfo
Additional Inherited Members
Protected Member Functions inherited from llvm::Dependence
Dependence (Dependence &&)=default
Dependence & operator= (Dependence &&)=default
Detailed Description
FullDependence - This class represents a dependence between two memory references in a function.
It contains detailed information about the dependence (direction vectors, etc.) and is used when the compiler is able to accurately analyze the interaction of the references; that is, it is not a confused dependence (see Dependence). In most cases (for output, flow, and anti dependences), the dependence implies an ordering, where the source must precede the destination; in contrast, input dependences are unordered.
Definition at line 214 of file DependenceAnalysis.h.
Constructor & Destructor Documentation
FullDependence()
FullDependence::FullDependence (Instruction * Src, Instruction * Dst, bool LoopIndependent, unsigned Levels)
Definition at line 250 of file DependenceAnalysis.cpp.
Member Function Documentation
getDirection()
unsigned FullDependence::getDirection (unsigned Level) const override virtual
getDirection - Returns the direction associated with a particular level.
Reimplemented from llvm::Dependence.
Definition at line 263 of file DependenceAnalysis.cpp.
References assert().
Referenced by llvm::DependenceInfo::depends().
getDistance()
const SCEV * FullDependence::getDistance (unsigned Level) const override virtual
getDistance - Returns the distance (or NULL) associated with a particular level.
Reimplemented from llvm::Dependence.
Definition at line 270 of file DependenceAnalysis.cpp.
References assert().
getLevels()
unsigned llvm::FullDependence::getLevels () const inline override virtual
getLevels - Returns the number of common loops surrounding the source and destination of the dependence.
Reimplemented from llvm::Dependence.
Definition at line 234 of file DependenceAnalysis.h.
isConfused()
bool llvm::FullDependence::isConfused () const inline override virtual
isConfused - Returns true if this dependence is confused (the compiler understands nothing and makes worst-case assumptions).
Reimplemented from llvm::Dependence.
Definition at line 226 of file DependenceAnalysis.h.
isConsistent()
bool llvm::FullDependence::isConsistent () const inline override virtual
isConsistent - Returns true if this dependence is consistent (occurs every time the source and destination are executed).
Reimplemented from llvm::Dependence.
Definition at line 230 of file DependenceAnalysis.h.
isLoopIndependent()
bool llvm::FullDependence::isLoopIndependent () const inline override virtual
isLoopIndependent - Returns true if this is a loop-independent dependence.
Reimplemented from llvm::Dependence.
Definition at line 221 of file DependenceAnalysis.h.
isPeelFirst()
bool FullDependence::isPeelFirst (unsigned Level) const override virtual
isPeelFirst - Returns true if peeling the first iteration from this loop will break this dependence.
Reimplemented from llvm::Dependence.
Definition at line 287 of file DependenceAnalysis.cpp.
References assert().
isPeelLast()
bool FullDependence::isPeelLast (unsigned Level) const override virtual
isPeelLast - Returns true if peeling the last iteration from this loop will break this dependence.
Reimplemented from llvm::Dependence.
Definition at line 295 of file DependenceAnalysis.cpp.
References assert().
isScalar()
bool FullDependence::isScalar (unsigned Level) const override virtual
isScalar - Returns true if a particular level is scalar; that is, if no subscript in the source or destination mention the induction variable associated with the loop at this level.
Reimplemented from llvm::Dependence.
Definition at line 279 of file DependenceAnalysis.cpp.
References assert().
isSplitable()
bool FullDependence::isSplitable (unsigned Level) const override virtual
isSplitable - Returns true if splitting the loop will break the dependence.
Reimplemented from llvm::Dependence.
Definition at line 302 of file DependenceAnalysis.cpp.
References assert().
Friends And Related Function Documentation
DependenceInfo
friend class DependenceInfo friend
Definition at line 266 of file DependenceAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DependenceAnalysis.h
lib/Analysis/DependenceAnalysis.cpp