LLVM: llvm::NoFolder Class Reference
llvm::NoFolder Class Reference
NoFolder - Create "constants" (actually, instructions) with no folding.
#include "llvm/IR/NoFolder.h"
Public Member Functions
NoFolder ()=default
Instruction * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Instruction * CreateNSWAdd (Constant *LHS, Constant *RHS) const
Instruction * CreateNUWAdd (Constant *LHS, Constant *RHS) const
Instruction * CreateFAdd (Constant *LHS, Constant *RHS) const
Instruction * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Instruction * CreateNSWSub (Constant *LHS, Constant *RHS) const
Instruction * CreateNUWSub (Constant *LHS, Constant *RHS) const
Instruction * CreateFSub (Constant *LHS, Constant *RHS) const
Instruction * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Instruction * CreateNSWMul (Constant *LHS, Constant *RHS) const
Instruction * CreateNUWMul (Constant *LHS, Constant *RHS) const
Instruction * CreateFMul (Constant *LHS, Constant *RHS) const
Instruction * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Instruction * CreateExactUDiv (Constant *LHS, Constant *RHS) const
Instruction * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Instruction * CreateExactSDiv (Constant *LHS, Constant *RHS) const
Instruction * CreateFDiv (Constant *LHS, Constant *RHS) const
Instruction * CreateURem (Constant *LHS, Constant *RHS) const
Instruction * CreateSRem (Constant *LHS, Constant *RHS) const
Instruction * CreateFRem (Constant *LHS, Constant *RHS) const
Instruction * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Instruction * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Instruction * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Instruction * CreateAnd (Constant *LHS, Constant *RHS) const
Instruction * CreateOr (Constant *LHS, Constant *RHS) const
Instruction * CreateXor (Constant *LHS, Constant *RHS) const
Instruction * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const
Instruction * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const
Instruction * CreateNSWNeg (Constant *C) const
Instruction * CreateNUWNeg (Constant *C) const
Instruction * CreateFNeg (Constant *C) const
Instruction * CreateNot (Constant *C) const
Instruction * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Instruction * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Instruction * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Instruction * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const
Instruction * CreatePointerCast (Constant *C, Type *DestTy) const
Instruction * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const
Instruction * CreateFPCast (Constant *C, Type *DestTy) const
Instruction * CreateBitCast (Constant *C, Type *DestTy) const
Instruction * CreateIntToPtr (Constant *C, Type *DestTy) const
Instruction * CreatePtrToInt (Constant *C, Type *DestTy) const
Instruction * CreateZExtOrBitCast (Constant *C, Type *DestTy) const
Instruction * CreateSExtOrBitCast (Constant *C, Type *DestTy) const
Instruction * CreateTruncOrBitCast (Constant *C, Type *DestTy) const
Instruction * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Instruction * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Instruction * CreateSelect (Constant *C, Constant *True, Constant *False) const
Instruction * CreateExtractElement (Constant *Vec, Constant *Idx) const
Instruction * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const
Instruction * CreateShuffleVector (Constant *V1, Constant *V2, Constant *Mask) const
Instruction * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const
Instruction * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const
Detailed Description
NoFolder - Create "constants" (actually, instructions) with no folding.
Definition at line 33 of file NoFolder.h.
Constructor & Destructor Documentation
NoFolder()
llvm::NoFolder::NoFolder () explicit default
Member Function Documentation
CreateAdd()
Instruction * llvm::NoFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 41 of file NoFolder.h.
References llvm::TargetFolder::CreateAdd(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateAnd()
Instruction * llvm::NoFolder::CreateAnd (Constant * LHS, Constant * RHS) const inline
Definition at line 161 of file NoFolder.h.
References llvm::TargetFolder::CreateAnd().
CreateAShr()
Instruction * llvm::NoFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 154 of file NoFolder.h.
References llvm::TargetFolder::CreateAShr().
CreateBinOp()
Instruction * llvm::NoFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline
Definition at line 173 of file NoFolder.h.
References llvm::BinaryOperator::Create().
CreateBitCast()
Instruction * llvm::NoFolder::CreateBitCast (Constant * C, Type * DestTy) const inline
Definition at line 271 of file NoFolder.h.
References C, and CreateCast().
CreateCast()
Instruction * llvm::NoFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline
Definition at line 253 of file NoFolder.h.
References C, and llvm::CastInst::Create().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExactSDiv()
Instruction * llvm::NoFolder::CreateExactSDiv (Constant * LHS, Constant * RHS) const inline
Definition at line 119 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactSDiv().
CreateExactUDiv()
Instruction * llvm::NoFolder::CreateExactUDiv (Constant * LHS, Constant * RHS) const inline
Definition at line 108 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactUDiv().
CreateExtractElement()
Instruction * llvm::NoFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline
Definition at line 318 of file NoFolder.h.
References llvm::ExtractElementInst::Create(), and Idx.
CreateExtractValue()
Instruction * llvm::NoFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline
Definition at line 332 of file NoFolder.h.
References llvm::ExtractValueInst::Create().
CreateFAdd()
Instruction * llvm::NoFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline
Definition at line 57 of file NoFolder.h.
References llvm::TargetFolder::CreateFAdd().
CreateFCmp()
Instruction * llvm::NoFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 304 of file NoFolder.h.
References P.
CreateFDiv()
Instruction * llvm::NoFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline
Definition at line 123 of file NoFolder.h.
References llvm::TargetFolder::CreateFDiv().
CreateFMul()
Instruction * llvm::NoFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline
Definition at line 97 of file NoFolder.h.
References llvm::TargetFolder::CreateFMul().
CreateFNeg()
Instruction * llvm::NoFolder::CreateFNeg (Constant * C) const inline
Definition at line 198 of file NoFolder.h.
References C, and llvm::BinaryOperator::CreateFNeg().
CreateFPCast()
Instruction * llvm::NoFolder::CreateFPCast (Constant * C, Type * DestTy) const inline
Definition at line 267 of file NoFolder.h.
References C, and llvm::CastInst::CreateFPCast().
CreateFRem()
Instruction * llvm::NoFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline
Definition at line 135 of file NoFolder.h.
References llvm::TargetFolder::CreateFRem().
CreateFSub()
Instruction * llvm::NoFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline
Definition at line 77 of file NoFolder.h.
References llvm::TargetFolder::CreateFSub().
CreateGetElementPtr() [1/3]
Constant * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline
Definition at line 214 of file NoFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [2/3]
Instruction * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline
Definition at line 226 of file NoFolder.h.
References C, and llvm::GetElementPtrInst::Create().
CreateGetElementPtr() [3/3]
Constant * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 219 of file NoFolder.h.
References C, llvm::ConstantExpr::getGetElementPtr(), and Idx.
CreateICmp()
Instruction * llvm::NoFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline
Definition at line 299 of file NoFolder.h.
References P.
CreateInBoundsGetElementPtr() [1/3]
Constant * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline
Definition at line 231 of file NoFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [2/3]
Instruction * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline
Definition at line 244 of file NoFolder.h.
References C, and llvm::GetElementPtrInst::CreateInBounds().
CreateInBoundsGetElementPtr() [3/3]
Constant * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline
Definition at line 236 of file NoFolder.h.
References C, llvm::ConstantExpr::getInBoundsGetElementPtr(), and Idx.
CreateInsertElement()
Instruction * llvm::NoFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline
Definition at line 322 of file NoFolder.h.
References llvm::InsertElementInst::Create(), and Idx.
CreateInsertValue()
Instruction * llvm::NoFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline
Definition at line 337 of file NoFolder.h.
References llvm::InsertValueInst::Create().
CreateIntCast()
Instruction * llvm::NoFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline
Definition at line 262 of file NoFolder.h.
References C, and llvm::CastInst::CreateIntegerCast().
CreateIntToPtr()
Instruction * llvm::NoFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline
Definition at line 275 of file NoFolder.h.
References C, and CreateCast().
CreateLShr()
Instruction * llvm::NoFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 147 of file NoFolder.h.
References llvm::TargetFolder::CreateLShr().
CreateMul()
Instruction * llvm::NoFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 81 of file NoFolder.h.
References llvm::TargetFolder::CreateMul(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateNeg()
Instruction * llvm::NoFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 182 of file NoFolder.h.
References C, llvm::BinaryOperator::CreateNeg(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateNot()
Instruction * llvm::NoFolder::CreateNot (Constant * C) const inline
Definition at line 202 of file NoFolder.h.
References C, and llvm::BinaryOperator::CreateNot().
CreateNSWAdd()
Instruction * llvm::NoFolder::CreateNSWAdd (Constant * LHS, Constant * RHS) const inline
Definition at line 49 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNSWAdd().
CreateNSWMul()
Instruction * llvm::NoFolder::CreateNSWMul (Constant * LHS, Constant * RHS) const inline
Definition at line 89 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNSWMul().
CreateNSWNeg()
Instruction * llvm::NoFolder::CreateNSWNeg (Constant * C) const inline
Definition at line 190 of file NoFolder.h.
References C, and llvm::BinaryOperator::CreateNSWNeg().
CreateNSWSub()
Instruction * llvm::NoFolder::CreateNSWSub (Constant * LHS, Constant * RHS) const inline
Definition at line 69 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNSWSub().
CreateNUWAdd()
Instruction * llvm::NoFolder::CreateNUWAdd (Constant * LHS, Constant * RHS) const inline
Definition at line 53 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNUWAdd().
CreateNUWMul()
Instruction * llvm::NoFolder::CreateNUWMul (Constant * LHS, Constant * RHS) const inline
Definition at line 93 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNUWMul().
CreateNUWNeg()
Instruction * llvm::NoFolder::CreateNUWNeg (Constant * C) const inline
Definition at line 194 of file NoFolder.h.
References C, and llvm::BinaryOperator::CreateNUWNeg().
CreateNUWSub()
Instruction * llvm::NoFolder::CreateNUWSub (Constant * LHS, Constant * RHS) const inline
Definition at line 73 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateNUWSub().
CreateOr()
Instruction * llvm::NoFolder::CreateOr (Constant * LHS, Constant * RHS) const inline
Definition at line 165 of file NoFolder.h.
References llvm::TargetFolder::CreateOr().
CreatePointerCast()
Instruction * llvm::NoFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline
Definition at line 258 of file NoFolder.h.
References C, and llvm::CastInst::CreatePointerCast().
CreatePtrToInt()
Instruction * llvm::NoFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline
Definition at line 279 of file NoFolder.h.
References C, CreateCast(), and llvm::PtrToIntOperator::PtrToInt.
CreateSDiv()
Instruction * llvm::NoFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 112 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactSDiv(), and llvm::TargetFolder::CreateSDiv().
CreateSelect()
Instruction * llvm::NoFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const inline
Definition at line 313 of file NoFolder.h.
References C, and llvm::SelectInst::Create().
CreateSExtOrBitCast()
Instruction * llvm::NoFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 287 of file NoFolder.h.
References C, and llvm::CastInst::CreateSExtOrBitCast().
CreateShl()
Instruction * llvm::NoFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 139 of file NoFolder.h.
References llvm::TargetFolder::CreateShl(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateShuffleVector()
Instruction * llvm::NoFolder::CreateShuffleVector (Constant * V1, Constant * V2, Constant * Mask) const inline
Definition at line 327 of file NoFolder.h.
CreateSRem()
Instruction * llvm::NoFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline
Definition at line 131 of file NoFolder.h.
References llvm::TargetFolder::CreateSRem().
CreateSub()
Instruction * llvm::NoFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline
Definition at line 61 of file NoFolder.h.
References llvm::TargetFolder::CreateSub(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateTruncOrBitCast()
Instruction * llvm::NoFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 291 of file NoFolder.h.
References C, and llvm::CastInst::CreateTruncOrBitCast().
CreateUDiv()
Instruction * llvm::NoFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline
Definition at line 101 of file NoFolder.h.
References llvm::IRBuilder< T, Inserter >::CreateExactUDiv(), and llvm::TargetFolder::CreateUDiv().
CreateUnOp()
Instruction * llvm::NoFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline
Definition at line 206 of file NoFolder.h.
References C, and llvm::UnaryOperator::Create().
CreateURem()
Instruction * llvm::NoFolder::CreateURem (Constant * LHS, Constant * RHS) const inline
Definition at line 127 of file NoFolder.h.
References llvm::TargetFolder::CreateURem().
CreateXor()
Instruction * llvm::NoFolder::CreateXor (Constant * LHS, Constant * RHS) const inline
Definition at line 169 of file NoFolder.h.
References llvm::TargetFolder::CreateXor().
CreateZExtOrBitCast()
Instruction * llvm::NoFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline
Definition at line 283 of file NoFolder.h.
References C, and llvm::CastInst::CreateZExtOrBitCast().
The documentation for this class was generated from the following file:
include/llvm/IR/NoFolder.h