LLVM: llvm::DiagnosticLocation Class Reference
llvm::DiagnosticLocation Class Reference
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticLocation ()=default
DiagnosticLocation (const DebugLoc &DL)
DiagnosticLocation (const DISubprogram *SP)
bool isValid () const
std::string getAbsolutePath () const
Return the full path to the file.
StringRef getRelativePath () const
Return the file name relative to the compilation directory.
unsigned getLine () const
unsigned getColumn () const
Detailed Description
Definition at line 343 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticLocation() [1/3]
llvm::DiagnosticLocation::DiagnosticLocation () default
DiagnosticLocation() [2/3]
DiagnosticLocation::DiagnosticLocation (const DebugLoc & DL)
Definition at line 111 of file DiagnosticInfo.cpp.
DiagnosticLocation() [3/3]
DiagnosticLocation::DiagnosticLocation (const DISubprogram * SP)
Definition at line 119 of file DiagnosticInfo.cpp.
References llvm::DIScope::getFile().
Member Function Documentation
getAbsolutePath()
std::string DiagnosticLocation::getAbsolutePath () const
Return the full path to the file.
Definition at line 132 of file DiagnosticInfo.cpp.
References llvm::sys::path::append(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::sys::path::is_absolute(), and llvm::sys::path::remove_leading_dotslash().
Referenced by llvm::DiagnosticInfoWithLocationBase::getAbsolutePath().
getColumn()
unsigned llvm::DiagnosticLocation::getColumn () const inline
Definition at line 359 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoWithLocationBase::getLocation(), and toRemarkLocation().
getLine()
unsigned llvm::DiagnosticLocation::getLine () const inline
Definition at line 358 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), llvm::DiagnosticInfoWithLocationBase::getLocation(), and toRemarkLocation().
getRelativePath()
StringRef DiagnosticLocation::getRelativePath () const
Return the file name relative to the compilation directory.
Definition at line 128 of file DiagnosticInfo.cpp.
References llvm::DIScope::getFilename().
Referenced by llvm::DiagnosticInfoWithLocationBase::getLocation(), and toRemarkLocation().
isValid()
bool llvm::DiagnosticLocation::isValid () const inline
Definition at line 353 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoWithLocationBase::isLocationAvailable(), and toRemarkLocation().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp