LLVM: llvm::Win64EH::ARM64UnwindEmitter Class Reference
llvm::Win64EH::ARM64UnwindEmitter Class Reference
#include "llvm/MC/MCWin64EH.h"
Public Member Functions
void Emit (MCStreamer &Streamer) const override
This emits the unwind info sections (.pdata and .xdata in PE/COFF).
void EmitUnwindInfo (MCStreamer &Streamer, WinEH::FrameInfo *FI) const override
Public Member Functions inherited from llvm::WinEH::UnwindEmitter
virtual ~UnwindEmitter ()
virtual void Emit (MCStreamer &Streamer) const =0
This emits the unwind info sections (.pdata and .xdata in PE/COFF).
virtual void EmitUnwindInfo (MCStreamer &Streamer, FrameInfo *FI) const =0
Detailed Description
Definition at line 59 of file MCWin64EH.h.
Member Function Documentation
Emit()
void llvm::Win64EH::ARM64UnwindEmitter::Emit (MCStreamer & Streamer) const override virtual
This emits the unwind info sections (.pdata and .xdata in PE/COFF).
Implements llvm::WinEH::UnwindEmitter.
Definition at line 657 of file MCWin64EH.cpp.
References ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), llvm::MCStreamer::getAssociatedPDataSection(), llvm::MCStreamer::getAssociatedXDataSection(), llvm::MCStreamer::getWinFrameInfos(), and llvm::MCStreamer::SwitchSection().
EmitUnwindInfo()
void llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo (MCStreamer & Streamer, WinEH::FrameInfo * FI) const override virtual
Implements llvm::WinEH::UnwindEmitter.
Definition at line 673 of file MCWin64EH.cpp.
References ARM64EmitUnwindInfo(), llvm::MCStreamer::getAssociatedXDataSection(), info, and llvm::MCStreamer::SwitchSection().
The documentation for this class was generated from the following files:
include/llvm/MC/MCWin64EH.h
lib/MC/MCWin64EH.cpp