LLVM: llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits > Class Template Reference
llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits > Class Template Reference
#include "llvm/ADT/IntervalMap.h"
Public Member Functions
const KeyT & stop (unsigned i) const
const NodeRef & subtree (unsigned i) const
KeyT & stop (unsigned i)
NodeRef & subtree (unsigned i)
unsigned findFrom (unsigned i, unsigned Size, KeyT x) const
findFrom - Find the first subtree after i that may contain x.
unsigned safeFind (unsigned i, KeyT x) const
safeFind - Find a subtree that is known to exist.
NodeRef safeLookup (KeyT x) const
safeLookup - Get the subtree containing x, Assuming that x is in range.
void insert (unsigned i, unsigned Size, NodeRef Node, KeyT Stop)
insert - Insert a new (subtree, stop) pair.
Public Member Functions inherited from llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >
void copy (const NodeBase< NodeRef, KeyT, M > &Other, unsigned i, unsigned j, unsigned Count)
copy - Copy elements from another node.
void moveLeft (unsigned i, unsigned j, unsigned Count)
moveLeft - Move elements to the left.
void moveRight (unsigned i, unsigned j, unsigned Count)
moveRight - Move elements to the right.
void erase (unsigned i, unsigned j, unsigned Size)
erase - Erase elements [i;j).
void erase (unsigned i, unsigned Size)
erase - Erase element at i.
void shift (unsigned i, unsigned Size)
shift - Shift elements [i;size) 1 position to the right.
void transferToLeftSib (unsigned Size, NodeBase &Sib, unsigned SSize, unsigned Count)
transferToLeftSib - Transfer elements to a left sibling node.
void transferToRightSib (unsigned Size, NodeBase &Sib, unsigned SSize, unsigned Count)
transferToRightSib - Transfer elements to a right sibling node.
int adjustFromLeftSib (unsigned Size, NodeBase &Sib, unsigned SSize, int Add)
adjustFromLeftSib - Adjust the number if elements in this node by moving elements to or from a left sibling node.
Additional Inherited Members
Public Types inherited from llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >
enum
Public Attributes inherited from llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >
NodeRef first [N]
KeyT second [N]
Detailed Description
template<typename KeyT, typename ValT, unsigned N, typename Traits>
class llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >
Definition at line 700 of file IntervalMap.h.
Member Function Documentation
findFrom()
template<typename KeyT , typename ValT , unsigned N, typename Traits > unsigned llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::findFrom (unsigned i, unsigned Size, KeyT x) const inline
findFrom - Find the first subtree after i that may contain x.
Parameters
i Starting index for the search.
Size Number of elements in node.
x Key to search for.
Returns
First index with !stopLess(key[i], x), or size. This is the first subtree that can possibly contain x.
Definition at line 714 of file IntervalMap.h.
References assert(), N, Size, and llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop().
insert()
template<typename KeyT , typename ValT , unsigned N, typename Traits > void llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::insert (unsigned i, unsigned Size, NodeRef Node, KeyT Stop) inline
insert - Insert a new (subtree, stop) pair.
Parameters
i Insert position, following entries will be shifted.
Size Number of elements in node.
Node Subtree to insert.
Stop Last key in subtree.
Definition at line 749 of file IntervalMap.h.
References assert(), N, llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >::shift(), Size, llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop(), and llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::subtree().
safeFind()
template<typename KeyT , typename ValT , unsigned N, typename Traits > unsigned llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeFind (unsigned i, KeyT x) const inline
safeFind - Find a subtree that is known to exist.
This is the same as findFrom except is it assumed that x is in range.
Parameters
i Starting index for the search.
x Key to search for.
Returns
First index with !stopLess(key[i], x), never size. This is the first subtree that can possibly contain x.
Definition at line 728 of file IntervalMap.h.
References assert(), N, and llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop().
Referenced by llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeLookup().
safeLookup()
template<typename KeyT , typename ValT , unsigned N, typename Traits > NodeRef llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeLookup (KeyT x) const inline
safeLookup - Get the subtree containing x, Assuming that x is in range.
Parameters
x Key to search for.
Returns
Subtree containing x
Definition at line 740 of file IntervalMap.h.
References llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeFind(), and llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::subtree().
stop() [1/2]
template<typename KeyT , typename ValT , unsigned N, typename Traits > KeyT & llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop (unsigned i) inline
Definition at line 705 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >::second.
stop() [2/2]
template<typename KeyT , typename ValT , unsigned N, typename Traits > const KeyT & llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop (unsigned i) const inline
Definition at line 702 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >::second.
Referenced by llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::findFrom(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::insert(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeFind(), llvm::IntervalMap< KeyT, ValT, N, Traits >::stop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::treeAdvanceTo().
subtree() [1/2]
template<typename KeyT , typename ValT , unsigned N, typename Traits > NodeRef & llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::subtree (unsigned i) inline
Definition at line 706 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >::first.
subtree() [2/2]
template<typename KeyT , typename ValT , unsigned N, typename Traits > const NodeRef & llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::subtree (unsigned i) const inline
Definition at line 703 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeBase< NodeRef, KeyT, N >::first.
Referenced by llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::insert(), and llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::safeLookup().
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalMap.h