LLVM: llvm::MachineFunctionProperties Class Reference
llvm::MachineFunctionProperties Class Reference
Properties which a MachineFunction may have at a given point in time.
#include "llvm/CodeGen/MachineFunction.h"
Public Types
enum class Property : unsigned {
IsSSA , NoPHIs , TracksLiveness , NoVRegs ,
FailedISel , Legalized , RegBankSelected , Selected ,
LastProperty = Selected
}
Public Member Functions
bool hasProperty (Property P) const
MachineFunctionProperties & set (Property P)
MachineFunctionProperties & reset (Property P)
MachineFunctionProperties & reset ()
Reset all the properties.
MachineFunctionProperties & set (const MachineFunctionProperties &MFP)
MachineFunctionProperties & reset (const MachineFunctionProperties &MFP)
bool verifyRequiredProperties (const MachineFunctionProperties &V) const
void print (raw_ostream &OS) const
Print the MachineFunctionProperties in human-readable form.
Detailed Description
Properties which a MachineFunction may have at a given point in time.
Each of these has checking code in the MachineVerifier, and passes can require that a property be set.
Definition at line 109 of file MachineFunction.h.
Member Enumeration Documentation
Property
enum class llvm::MachineFunctionProperties::Property : unsigned strong
Enumerator
IsSSA
NoPHIs
TracksLiveness
NoVRegs
FailedISel
Legalized
RegBankSelected
Selected
LastProperty
Definition at line 145 of file MachineFunction.h.
Member Function Documentation
hasProperty()
bool llvm::MachineFunctionProperties::hasProperty (Property P) const inline
Definition at line 157 of file MachineFunction.h.
References P.
Referenced by llvm::Combiner::combineMachineInstrs(), llvm::MachineRegisterInfo::isSSA(), llvm::MIRPrinter::print(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::Localizer::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), and llvm::MachineRegisterInfo::tracksLiveness().
print()
void MachineFunctionProperties::print (raw_ostream & OS) const
Print the MachineFunctionProperties in human-readable form.
Definition at line 105 of file MachineFunction.cpp.
References I, and llvm::BitVector::size().
Referenced by llvm::MachineFunction::print().
reset() [1/3]
MachineFunctionProperties & llvm::MachineFunctionProperties::reset () inline
Reset all the properties.
Definition at line 172 of file MachineFunction.h.
References llvm::BitVector::reset().
reset() [2/3]
MachineFunctionProperties & llvm::MachineFunctionProperties::reset (const MachineFunctionProperties & MFP) inline
Definition at line 182 of file MachineFunction.h.
References llvm::BitVector::reset().
reset() [3/3]
MachineFunctionProperties & llvm::MachineFunctionProperties::reset (Property P) inline
Definition at line 166 of file MachineFunction.h.
References P, and llvm::BitVector::reset().
Referenced by createPHIsForSelects(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MachineRegisterInfo::invalidateLiveness(), and llvm::MachineRegisterInfo::leaveSSA().
set() [1/2]
MachineFunctionProperties & llvm::MachineFunctionProperties::set (const MachineFunctionProperties & MFP) inline
Definition at line 177 of file MachineFunction.h.
set() [2/2]
MachineFunctionProperties & llvm::MachineFunctionProperties::set (Property P) inline
Definition at line 161 of file MachineFunction.h.
References P, and llvm::BitVector::set().
Referenced by llvm::Legalizer::getClearedProperties(), llvm::RegBankSelect::getClearedProperties(), llvm::ExecutionDomainFix::getRequiredProperties(), llvm::InstructionSelect::getRequiredProperties(), llvm::Legalizer::getRequiredProperties(), llvm::Localizer::getRequiredProperties(), llvm::RegBankSelect::getRequiredProperties(), llvm::ReachingDefAnalysis::getRequiredProperties(), llvm::BreakFalseDeps::getRequiredProperties(), llvm::InstructionSelect::getSetProperties(), llvm::Legalizer::getSetProperties(), llvm::RegBankSelect::getSetProperties(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::reportGISelFailure(), and llvm::scavengeFrameVirtualRegs().
verifyRequiredProperties()
bool llvm::MachineFunctionProperties::verifyRequiredProperties (const MachineFunctionProperties & V) const inline
Definition at line 189 of file MachineFunction.h.
References llvm::BitVector::test().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineFunction.cpp