LLVM: llvm::object::content_iterator< content_type > Class Template Reference
llvm::object::content_iterator< content_type > Class Template Reference
#include "llvm/Object/SymbolicFile.h"
Public Member Functions
content_iterator (content_type symb)
const content_type * operator-> () const
const content_type & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & operator++ ()
Detailed Description
template<class content_type>
class llvm::object::content_iterator< content_type >
Definition at line 69 of file SymbolicFile.h.
Constructor & Destructor Documentation
content_iterator()
template<class content_type > llvm::object::content_iterator< content_type >::content_iterator (content_type symb) inline
Definition at line 74 of file SymbolicFile.h.
Member Function Documentation
operator!=()
template<class content_type > bool llvm::object::content_iterator< content_type >::operator!= (const content_iterator< content_type > & other) const inline
Definition at line 84 of file SymbolicFile.h.
operator*()
template<class content_type > const content_type & llvm::object::content_iterator< content_type >::operator* () const inline
Definition at line 78 of file SymbolicFile.h.
Referenced by llvm::object::elf_section_iterator::operator*(), llvm::object::elf_relocation_iterator::operator*(), llvm::object::symbol_iterator::operator*(), and llvm::object::symbol_iterator::operator->().
operator++()
template<class content_type > content_iterator & llvm::object::content_iterator< content_type >::operator++ () inline
Definition at line 88 of file SymbolicFile.h.
operator->()
template<class content_type > const content_type * llvm::object::content_iterator< content_type >::operator-> () const inline
Definition at line 76 of file SymbolicFile.h.
Referenced by llvm::object::elf_section_iterator::operator->(), and llvm::object::elf_relocation_iterator::operator->().
operator==()
template<class content_type > bool llvm::object::content_iterator< content_type >::operator== (const content_iterator< content_type > & other) const inline
Definition at line 80 of file SymbolicFile.h.
The documentation for this class was generated from the following file:
include/llvm/Object/SymbolicFile.h