LLVM: llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t > Class Template Reference
llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t > Class Template Reference
#include "llvm/IR/InstIterator.h"
Public Types
using iterator_category = std::bidirectional_iterator_tag
using value_type = IIty
using difference_type = signed
using pointer = IIty *
using reference = IIty &
Public Member Functions
InstIterator ()=default
template<typename A , typename B , typename C , typename D >
InstIterator (const InstIterator< A, B, C, D > &II)
template<typename A , typename B , typename C , typename D >
InstIterator (InstIterator< A, B, C, D > &II)
template<class M >
InstIterator (M &m)
template<class M >
InstIterator (M &m, bool)
BBIty & getBasicBlockIterator ()
BIty & getInstructionIterator ()
reference operator* () const
pointer operator-> () const
bool operator== (const InstIterator &y) const
bool operator!= (const InstIterator &y) const
InstIterator & operator++ ()
InstIterator operator++ (int)
InstIterator & operator-- ()
InstIterator operator-- (int)
bool atEnd () const
Detailed Description
template<class BB_t, class BB_i_t, class BI_t, class II_t>
class llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >
Definition at line 32 of file InstIterator.h.
Member Typedef Documentation
difference_type
template<class BB_t , class BB_i_t , class BI_t , class II_t > using llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::difference_type = signed
Definition at line 44 of file InstIterator.h.
iterator_category
template<class BB_t , class BB_i_t , class BI_t , class II_t > using llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::iterator_category = std::bidirectional_iterator_tag
Definition at line 42 of file InstIterator.h.
pointer
template<class BB_t , class BB_i_t , class BI_t , class II_t > using llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::pointer = IIty *
Definition at line 45 of file InstIterator.h.
reference
template<class BB_t , class BB_i_t , class BI_t , class II_t > using llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::reference = IIty &
Definition at line 46 of file InstIterator.h.
value_type
template<class BB_t , class BB_i_t , class BI_t , class II_t > using llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::value_type = IIty
Definition at line 43 of file InstIterator.h.
Constructor & Destructor Documentation
InstIterator() [1/5]
template<class BB_t , class BB_i_t , class BI_t , class II_t > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator () default
InstIterator() [2/5]
template<class BB_t , class BB_i_t , class BI_t , class II_t > template<typename A , typename B , typename C , typename D > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (const InstIterator< A, B, C, D > & II) inline
Definition at line 53 of file InstIterator.h.
InstIterator() [3/5]
template<class BB_t , class BB_i_t , class BI_t , class II_t > template<typename A , typename B , typename C , typename D > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (InstIterator< A, B, C, D > & II) inline
Definition at line 57 of file InstIterator.h.
InstIterator() [4/5]
template<class BB_t , class BB_i_t , class BI_t , class II_t > template<class M > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (M & m) inline
Definition at line 60 of file InstIterator.h.
InstIterator() [5/5]
template<class BB_t , class BB_i_t , class BI_t , class II_t > template<class M > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (M & m, bool) inline
Definition at line 68 of file InstIterator.h.
Member Function Documentation
atEnd()
template<class BB_t , class BB_i_t , class BI_t , class II_t > bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::atEnd () const inline
Definition at line 107 of file InstIterator.h.
getBasicBlockIterator()
template<class BB_t , class BB_i_t , class BI_t , class II_t > BBIty & llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::getBasicBlockIterator () inline
Definition at line 73 of file InstIterator.h.
getInstructionIterator()
template<class BB_t , class BB_i_t , class BI_t , class II_t > BIty & llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::getInstructionIterator () inline
Definition at line 74 of file InstIterator.h.
operator!=()
template<class BB_t , class BB_i_t , class BI_t , class II_t > bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator!= (const InstIterator< BB_t, BB_i_t, BI_t, II_t > & y) const inline
Definition at line 82 of file InstIterator.h.
References llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator==().
operator*()
template<class BB_t , class BB_i_t , class BI_t , class II_t > reference llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator* () const inline
Definition at line 76 of file InstIterator.h.
Referenced by llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator->().
operator++() [1/2]
template<class BB_t , class BB_i_t , class BI_t , class II_t > InstIterator & llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator++ () inline
Definition at line 86 of file InstIterator.h.
operator++() [2/2]
template<class BB_t , class BB_i_t , class BI_t , class II_t > InstIterator llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator++ (int) inline
Definition at line 91 of file InstIterator.h.
operator--() [1/2]
template<class BB_t , class BB_i_t , class BI_t , class II_t > InstIterator & llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-- () inline
Definition at line 95 of file InstIterator.h.
operator--() [2/2]
template<class BB_t , class BB_i_t , class BI_t , class II_t > InstIterator llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-- (int) inline
Definition at line 103 of file InstIterator.h.
operator->()
template<class BB_t , class BB_i_t , class BI_t , class II_t > pointer llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-> () const inline
Definition at line 77 of file InstIterator.h.
References llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator*().
operator==()
template<class BB_t , class BB_i_t , class BI_t , class II_t > bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator== (const InstIterator< BB_t, BB_i_t, BI_t, II_t > & y) const inline
Definition at line 79 of file InstIterator.h.
Referenced by llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator!=().
The documentation for this class was generated from the following file:
include/llvm/IR/InstIterator.h