LLVM: llvm::sampleprof::SampleProfileReaderItaniumRemapper Class Reference
llvm::sampleprof::SampleProfileReaderItaniumRemapper Class Reference
A profile data reader proxy that remaps the profile data from another sample profile data reader, by applying a provided set of equivalences between components of the symbol names in the profile.
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReaderItaniumRemapper (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, std::unique_ptr< SampleProfileReader > Underlying)
std::error_code readHeader () override
Read and validate the file header.
std::error_code read () override
Read remapping file and apply it to the sample profile.
FunctionSamples * getSamplesFor (StringRef FunctionName) override
Return the samples collected for function F.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
virtual std::error_code readHeader ()=0
Read and validate the file header.
virtual std::error_code read ()=0
Read sample profiles from the associated file.
void dumpFunctionProfile (StringRef FName, raw_ostream &OS=dbgs())
Print the profile for FName on stream OS.
virtual void collectFuncsToUse (const Module &M)
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
StringMap< FunctionSamples > & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, Twine Msg) const
Report a parse error message.
ProfileSummary & getSummary ()
Return the profile summary.
SampleProfileFormat getFormat ()
Return the profile format.
Static Public Member Functions
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const Twine &Filename, LLVMContext &C, std::unique_ptr< SampleProfileReader > Underlying)
Create a remapped sample profile from the given remapping file and underlying samples.
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const Twine &Filename, LLVMContext &C)
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C)
Create a sample profile reader from the supplied memory buffer.
Additional Inherited Members
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
void computeSummary ()
Compute summary for this profile.
Static Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
StringMap< FunctionSamples > Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
SampleProfileFormat Format = SPF_None
The format of sample.
Detailed Description
A profile data reader proxy that remaps the profile data from another sample profile data reader, by applying a provided set of equivalences between components of the symbol names in the profile.
Definition at line 543 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderItaniumRemapper()
llvm::sampleprof::SampleProfileReaderItaniumRemapper::SampleProfileReaderItaniumRemapper (std::unique_ptr< MemoryBuffer > B, LLVMContext & C, std::unique_ptr< SampleProfileReader > Underlying) inline
Definition at line 545 of file SampleProfReader.h.
References llvm::sampleprof::SampleProfileReader::Profiles, llvm::sampleprof::SampleProfileReader::Summary, and llvm::sampleprof::SampleProfileReader::takeSummary().
Member Function Documentation
create()
ErrorOr< std::unique_ptr< SampleProfileReader > > SampleProfileReaderItaniumRemapper::create (const Twine & Filename, LLVMContext & C, std::unique_ptr< SampleProfileReader > Underlying) static
Create a remapped sample profile from the given remapping file and underlying samples.
Create a sample profile remapper from the given input, to remap the function names in the given profile data.
Parameters
Filename The file to open.
C The LLVM context to use to emit diagnostics.
Underlying The underlying profile data reader to remap.
Returns
an error code indicating the status of the created reader.
Definition at line 991 of file SampleProfReader.cpp.
References C, and setupMemoryBuffer().
getSamplesFor() [1/3]
FunctionSamples * llvm::sampleprof::SampleProfileReader::getSamplesFor (const Function & F) inline
Return the samples collected for function F.
Definition at line 288 of file SampleProfReader.h.
getSamplesFor() [2/3]
virtual FunctionSamples * llvm::sampleprof::SampleProfileReader::getSamplesFor (StringRef Fname) inline virtual
Return the samples collected for function F.
Reimplemented from llvm::sampleprof::SampleProfileReader.
Definition at line 297 of file SampleProfReader.h.
getSamplesFor() [3/3]
FunctionSamples * SampleProfileReaderItaniumRemapper::getSamplesFor (StringRef FunctionName) override virtual
Return the samples collected for function F.
Reimplemented from llvm::sampleprof::SampleProfileReader.
Definition at line 942 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::getSamplesFor(), and llvm::SymbolRemappingReader::lookup().
read()
std::error_code SampleProfileReaderItaniumRemapper::read () override virtual
Read remapping file and apply it to the sample profile.
Implements llvm::sampleprof::SampleProfileReader.
Definition at line 914 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, llvm::sampleprof::SampleProfileReader::Ctx, llvm::LLVMContext::diagnose(), llvm::DS_Warning, E, llvm::sampleprof::SampleProfileReader::getFormat(), llvm::SymbolRemappingParseError::getLineNum(), llvm::SymbolRemappingParseError::getMessage(), llvm::sampleprof::SampleProfileReader::getProfiles(), llvm::handleAllErrors(), llvm::SymbolRemappingReader::insert(), llvm::malformed, llvm::SymbolRemappingReader::read(), llvm::sampleprof::SampleProfileReader::reportError(), llvm::sampleprof::SPF_Compact_Binary, and llvm::success.
readHeader()
std::error_code llvm::sampleprof::SampleProfileReaderItaniumRemapper::readHeader () inline override virtual
Read and validate the file header.
Implements llvm::sampleprof::SampleProfileReader.
Definition at line 563 of file SampleProfReader.h.
References llvm::success.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp