LLVM: llvm::BasicTTIImplBase< T > Class Template Reference
llvm::BasicTTIImplBase< T > Class Template Reference
Base class which can be used to help build a TTI implementation.
#include "llvm/CodeGen/BasicTTIImpl.h"
Public Member Functions
Scalar TTI Implementations
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
int getInstructionLatency (const Instruction *I)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getScalarizationOverhead (Type *VecTy, ArrayRef< const Value * > Args)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >())
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF=1)
Get intrinsic cost based on arguments.
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed=std::numeric_limits< unsigned >::max())
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (Type *Ty, Type *CondTy, bool IsPairwise, bool)
Try to calculate op costs for min/max reduction operations.
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
unsigned getCallCost (const Function *F, int NumArgs, const User *U)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys, const User *U)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments, const User *U)
unsigned getUserCost (const User *U, ArrayRef< const Value * > Operands)
int getInstructionLatency (const Instruction *I)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize)
int getExtCost (const Instruction *I, const Value *Src)
unsigned getCallCost (FunctionType *FTy, int NumArgs, const User *U)
unsigned getInliningThresholdMultiplier ()
int getInlinerVectorBonusPercent ()
unsigned getMemcpyCost (const Instruction *I)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool isLoweredToCall (const Function *F)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2)
bool canMacroFuseCmp ()
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo)
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType)
bool isLegalMaskedLoad (Type *DataType)
bool isLegalNTStore (Type *DataType, unsigned Alignment)
bool isLegalNTLoad (Type *DataType, unsigned Alignment)
bool isLegalMaskedScatter (Type *DataType)
bool isLegalMaskedGather (Type *DataType)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalMaskedExpandLoad (Type *DataType)
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace)
bool prefersVectorizedAddressing ()
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool LSRWithInstrQueries ()
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA ()
bool isTypeLegal (Type *Ty)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool shouldBuildLookupTablesForConstant (Constant *C)
bool useColdCCForColdCall (Function &F)
unsigned getScalarizationOverhead (Type *Ty, bool Insert, bool Extract)
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
bool supportsEfficientVectorElementLoadStore ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization ()
bool enableMaskedInterleavedAccessVectorization ()
bool isFPVectorizationPotentiallyUnsafe ()
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth ()
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader)
unsigned getCacheLineSize ()
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level)
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level)
unsigned getPrefetchDistance ()
unsigned getMinPrefetchStride ()
unsigned getMaxPrefetchIterationsAhead ()
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value * > Args)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, const Instruction *I)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, const Instruction *I)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace, const Instruction *I)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, Value *Ptr, bool VariableMask, unsigned Alignment)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned, Type *, bool)
unsigned getMinMaxReductionCost (Type *, Type *, bool, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument * > &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, unsigned Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
Protected Member Functions
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned)
bool isStridedAccess (const SCEV *Ptr)
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr)
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance)
Protected Attributes
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Detailed Description
template<typename T>
class llvm::BasicTTIImplBase< T >
Base class which can be used to help build a TTI implementation.
This class provides as much implementation of the TTI interface as is possible using the target independent parts of the code generator.
In order to subclass it, your class must implement a getST() method to return the subtarget, and a getTLI() method to return the target lowering. We need these methods implemented in the derived class so that this class doesn't have to duplicate storage for them.
Definition at line 77 of file BasicTTIImpl.h.
Constructor & Destructor Documentation
BasicTTIImplBase()
template<typename T > llvm::BasicTTIImplBase< T >::BasicTTIImplBase (const TargetMachine * TM, const DataLayout & DL) inline explicit protected
Definition at line 191 of file BasicTTIImpl.h.
Member Function Documentation
allowsMisalignedMemoryAccesses()
template<typename T > bool llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool * Fast) const inline
Definition at line 199 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), Context, E, llvm::EVT::getIntegerVT(), and llvm::MachineMemOperand::MONone.
getAddressComputationCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getAddressComputationCost (Type * Ty, ScalarEvolution * , const SCEV *) inline
Definition at line 1527 of file BasicTTIImpl.h.
getArithmeticInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value * > Args = ArrayRef<const Value *>()) inline
Definition at line 583 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::DL, llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getVectorNumElements(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Type::isFPOrFPVectorTy(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), and llvm::Type::isVectorTy().
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::WebAssemblyTTIImpl::getArithmeticInstrCost(), and llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost().
getArithmeticReductionCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getArithmeticReductionCost (unsigned Opcode, Type * Ty, bool IsPairwise) inline
Try to calculate arithmetic and shuffle op costs for reduction operations.
We're assuming that reduction operation are performing the following way:
Non-pairwise reduction val1 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 n/2, i32 n/2 + 1, ..., i32 n, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/2 elements n/2 elements red1 = op <n x t> val, <n x t> val1 After this operation we have a vector red1 where only the first n/2 elements are meaningful, the second n/2 elements are undefined and can be dropped. All other operations are actually working with the vector of length n/2, not n, though the real vector length is still n. val2 = shufflevector<n x t> red1, <n x t> undef, <n x i32> <i32 n/4, i32 n/4 + 1, ..., i32 n/2, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/4 elements 3*n/4 elements red2 = op <n x t> red1, <n x t> val2 - working with the vector of length n/2, the resulting vector has length n/4 etc.
Pairwise reduction: Everything is the same except for an additional shuffle operation which is used to produce operands for pairwise kind of reductions. val1 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 0, i32 2, ..., i32 n-2, i32 undef, ..., i32 undef> ----------—v-------—/ -------—v---------—/ n/2 elements n/2 elements val2 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 1, i32 3, ..., i32 n-1, i32 undef, ..., i32 undef> ----------—v-------—/ -------—v---------—/ n/2 elements n/2 elements red1 = op <n x t> val1, <n x t> val2 Again, the operation is performed on <n x t> vector, but the resulting vector red1 is <n/2 x t> vector.
The cost model should take into account that the actual length of the vector is reduced on each iteration.
Definition at line 1567 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::DL, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), llvm::Log2_32(), llvm::TargetTransformInfo::SK_ExtractSubvector, and llvm::TargetTransformInfo::SK_PermuteSingleSrc.
getCallInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys) inline
Compute a cost of the given call instruction.
Compute the cost of calling function F with return type RetTy and argument types Tys. F might be nullptr, in this case the cost of an arbitrary call with the specified signature will be returned. This is used, for instance, when we estimate call of a vector counterpart of the given function.
Parameters
F Called function, might be nullptr.
RetTy Return value types.
Tys Argument types.
Returns
The cost of Call instruction.
Definition at line 1518 of file BasicTTIImpl.h.
getCastInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, const Instruction * I = nullptr) inline
Definition at line 649 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::DL, llvm::IntervalMapImpl::NodeRef::get(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::Type::getContext(), llvm::EVT::getEVT(), llvm::Type::getPointerAddressSpace(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), I, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::TargetLoweringBase::isFreeAddrSpaceCast(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::TargetLoweringBase::isTruncateFree(), llvm::Type::isVectorTy(), llvm::TargetLoweringBase::isZExtFree(), llvm_unreachable, llvm::CCValAssign::SExt, llvm::ISD::SEXTLOAD, llvm::TargetLoweringBase::TypeSplitVector, llvm::CCValAssign::ZExt, and llvm::ISD::ZEXTLOAD.
Referenced by llvm::BasicTTIImplBase< T >::getCastInstrCost(), and llvm::BasicTTIImplBase< T >::getExtractWithExtendCost().
getCFInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCFInstrCost (unsigned Opcode) inline
Definition at line 782 of file BasicTTIImpl.h.
getCmpSelInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, const Instruction * I) inline
Definition at line 787 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::DL, llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getVectorNumElements(), I, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::TargetLoweringBase::isOperationExpand(), llvm::Type::isVectorTy(), llvm::ISD::SELECT, and llvm::ISD::VSELECT.
Referenced by llvm::BasicTTIImplBase< T >::getCmpSelInstrCost().
getEstimatedNumberOfCaseClusters()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JumpTableSize) inline
Try to find the estimated number of clusters. Note that the number of clusters identified in this function could be different from the actural numbers found in lowering. This function ignore switches that are lowered with a mix of jump table / bit test / BTree. This function was initially intended to be used when estimating the cost of switch in inline cost heuristic, but it's a generic cost model to be used in other places (e.g., in loop unrolling).
Definition at line 317 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::areJTsAllowed(), llvm::BasicTTIImplBase< T >::DL, llvm::TargetTransformInfoImplBase::getDataLayout(), llvm::DataLayout::getIndexSizeInBits(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::TargetLoweringBase::isSuitableForBitTests(), llvm::TargetLoweringBase::isSuitableForJumpTable(), N, llvm::APInt::sgt(), SI, llvm::SmallPtrSetImplBase::size(), and llvm::APInt::slt().
getExtCost()
template<typename T > int llvm::BasicTTIImplBase< T >::getExtCost (const Instruction * I, const Value * Src) inline
Definition at line 283 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, I, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
getExtractWithExtendCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index) inline
Definition at line 774 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::SequentialType::getElementType(), and llvm::BasicTTIImplBase< T >::getVectorInstrCost().
getFlatAddressSpace()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getFlatAddressSpace () inline
Definition at line 213 of file BasicTTIImpl.h.
getFPOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getFPOpCost (Type * Ty) inline
Definition at line 395 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::ISD::FADD, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegalOrCustomOrPromote(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Expensive.
getGEPCost()
template<typename T > int llvm::BasicTTIImplBase< T >::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands) inline
Definition at line 278 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost().
getInlinerVectorBonusPercent()
template<typename T > int llvm::BasicTTIImplBase< T >::getInlinerVectorBonusPercent () inline
Definition at line 430 of file BasicTTIImpl.h.
getInliningThresholdMultiplier()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getInliningThresholdMultiplier () inline
Definition at line 428 of file BasicTTIImpl.h.
getInstructionLatency()
template<typename T > int llvm::BasicTTIImplBase< T >::getInstructionLatency (const Instruction * I) inline
Definition at line 504 of file BasicTTIImpl.h.
References llvm::MCSchedModel::DefaultLoadLatency, llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionLatency(), llvm::MCSubtargetInfo::getSchedModel(), and I.
getInterleavedMemoryOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace, bool UseMaskForCond = false, bool UseMaskForGaps = false) inline
Definition at line 865 of file BasicTTIImpl.h.
References A, assert(), B, llvm::BitVector::count(), llvm::BasicTTIImplBase< T >::DL, llvm::IntervalMapImpl::NodeRef::get(), llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::Type::getContext(), llvm::TargetTransformInfoImplBase::getDataLayout(), llvm::SequentialType::getElementType(), llvm::IRBuilderBase::getInt8Ty(), llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::SequentialType::getNumElements(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::DataLayout::getTypeStoreSize(), llvm::BitVector::set(), and llvm::ArrayRef< T >::size().
getIntrinsicCost() [1/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< const Value * > Arguments, const User * U) inline
Definition at line 295 of file BasicTTIImpl.h.
References Arguments, llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), and RetTy.
getIntrinsicCost() [2/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > ParamTys, const User * U) inline
Definition at line 300 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), RetTy, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Expensive.
getIntrinsicInstrCost() [1/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > Tys, FastMathFlags FMF, unsigned ScalarizationCostPassed = std::numeric_limits<unsigned>::max()) inline
Get intrinsic cost based on argument types.
If ScalarizationCostPassed is std::numeric_limits<unsigned>::max(), the cost of scalarizing the arguments and the return value will be computed based on types.
Definition at line 1131 of file BasicTTIImpl.h.
References llvm::MCBinaryExpr::AShr, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LiveRangeEdit::create(), llvm::ISD::CTPOP, llvm::BasicTTIImplBase< T >::DL, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::FABS, llvm::AtomicRMWInst::FAdd, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FNEARBYINT, llvm::ISD::FPOW, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FTRUNC, llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt1Ty(), llvm::Type::getIntNTy(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getVectorNumElements(), llvm::TargetLoweringBase::isFAbsFree(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::Type::isVectorTy(), llvm::MCBinaryExpr::LShr, llvm::CmpInst::makeCmpResultType(), llvm::MCBinaryExpr::Mul, llvm::FastMathFlags::noNaNs(), llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RetTy, llvm::MCID::Select, llvm::CCValAssign::SExt, llvm::MCBinaryExpr::Shl, llvm::ArrayRef< T >::size(), llvm::AtomicRMWInst::Sub, llvm::TargetTransformInfo::TCC_Expensive, llvm::AtomicRMWInst::Xor, and llvm::CCValAssign::ZExt.
getIntrinsicInstrCost() [2/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Value * > Args, FastMathFlags FMF, unsigned VF = 1) inline
Get intrinsic cost based on arguments.
Definition at line 1021 of file BasicTTIImpl.h.
References assert(), llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt1Ty(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::TargetTransformInfo::getOperandInfo(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), getType(), llvm::isPowerOf2_32(), llvm::Type::isVectorTy(), llvm::MCBinaryExpr::LShr, llvm::TargetTransformInfo::OK_NonUniformConstantValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, llvm::TargetTransformInfo::OP_PowerOf2, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RetTy, llvm::MCID::Select, llvm::MCBinaryExpr::Shl, llvm::AtomicRMWInst::Sub, X, Y, and llvm::Z.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost().
getJumpBufAlignment()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getJumpBufAlignment () inline
Definition at line 374 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::getJumpBufAlignment().
getJumpBufSize()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getJumpBufSize () inline
Definition at line 376 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::getJumpBufSize().
getMaxInterleaveFactor()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMaxInterleaveFactor (unsigned VF) inline
Definition at line 581 of file BasicTTIImpl.h.
getMemoryOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace, const Instruction * I = nullptr) inline
Definition at line 834 of file BasicTTIImpl.h.
References assert(), llvm::LegalizeActions::Custom, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::TargetLoweringBase::getLoadExtAction(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), and llvm::LegalizeActions::Legal.
Referenced by llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost().
getMinMaxReductionCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMinMaxReductionCost (Type * Ty, Type * CondTy, bool IsPairwise, bool) inline
Try to calculate op costs for min/max reduction operations.
Parameters
CondTy Conditional type for the Select instruction.
Definition at line 1617 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::DL, llvm::IntervalMapImpl::NodeRef::get(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isVectorTy(), llvm::Log2_32(), llvm::MCID::Select, llvm::TargetTransformInfo::SK_ExtractSubvector, and llvm::TargetTransformInfo::SK_PermuteSingleSrc.
getNumberOfParts()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getNumberOfParts (Type * Tp) inline
Definition at line 1522 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, and llvm::TargetLoweringBase::getTypeLegalizationCost().
getNumberOfRegisters()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getNumberOfRegisters (bool Vector) inline
Definition at line 516 of file BasicTTIImpl.h.
getOperandsScalarizationOverhead()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF) inline
Estimate the overhead of scalarizing an instructions unique non-constant operands.
The types of the arguments are ordinarily scalar, in which case the costs are multiplied with VF.
Definition at line 541 of file BasicTTIImpl.h.
References A, assert(), llvm::IntervalMapImpl::NodeRef::get(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getVectorNumElements(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< T >::getScalarizationOverhead().
getOperationCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getOperationCost (unsigned Opcode, Type * Ty, Type * OpTy) inline
Definition at line 405 of file BasicTTIImpl.h.
References llvm::TargetTransformInfo::getOperationCost(), llvm::Type::getPointerAddressSpace(), llvm::TargetLoweringBase::isFreeAddrSpaceCast(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLoweringBase::isZExtFree(), llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and llvm::CCValAssign::ZExt.
getRegisterBitWidth()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getRegisterBitWidth (bool Vector) const inline
Definition at line 518 of file BasicTTIImpl.h.
getScalarizationOverhead() [1/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getScalarizationOverhead (Type * Ty, bool Insert, bool Extract) inline
Estimate the overhead of scalarizing an instruction.
Insert and Extract are set if the result needs to be inserted and/or extracted from vectors.
Definition at line 522 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), llvm::Type::getVectorNumElements(), and llvm::Type::isVectorTy().
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), and llvm::BasicTTIImplBase< T >::getScalarizationOverhead().
getScalarizationOverhead() [2/2]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getScalarizationOverhead (Type * VecTy, ArrayRef< const Value * > Args) inline
Definition at line 564 of file BasicTTIImpl.h.
References assert(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getVectorNumElements(), and llvm::Type::isVectorTy().
getScalingFactorCost()
template<typename T > int llvm::BasicTTIImplBase< T >::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) inline
Definition at line 253 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getScalingFactorCost(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
getShuffleCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp) inline
Definition at line 630 of file BasicTTIImpl.h.
References llvm_unreachable, llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::TargetTransformInfo::SK_Reverse, llvm::TargetTransformInfo::SK_Select, and llvm::TargetTransformInfo::SK_Transpose.
getUnrollingPreferences()
template<typename T > void llvm::BasicTTIImplBase< T >::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP) inline
Definition at line 432 of file BasicTTIImpl.h.
References llvm::BasicBlock::begin(), llvm::TargetTransformInfo::UnrollingPreferences::BEInsns, llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), E, llvm::BasicBlock::end(), F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), I, llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::TargetTransformInfo::UnrollingPreferences::OptSizeThreshold, llvm::TargetTransformInfo::UnrollingPreferences::Partial, llvm::TargetTransformInfo::UnrollingPreferences::PartialOptSizeThreshold, llvm::TargetTransformInfo::UnrollingPreferences::PartialThreshold, llvm::PartialUnrollingThreshold, llvm::TargetTransformInfo::UnrollingPreferences::Runtime, and llvm::TargetTransformInfo::UnrollingPreferences::UpperBound.
Referenced by llvm::ARMTTIImpl::getUnrollingPreferences().
getVectorInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) inline
Definition at line 827 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::Type::getScalarType(), and llvm::TargetLoweringBase::getTypeLegalizationCost().
Referenced by llvm::BasicTTIImplBase< T >::getExtractWithExtendCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), and llvm::WebAssemblyTTIImpl::getVectorInstrCost().
getVectorSplitCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getVectorSplitCost () inline
Definition at line 1684 of file BasicTTIImpl.h.
hasBranchDivergence()
template<typename T > bool llvm::BasicTTIImplBase< T >::hasBranchDivergence () inline
Definition at line 207 of file BasicTTIImpl.h.
haveFastSqrt()
template<typename T > bool llvm::BasicTTIImplBase< T >::haveFastSqrt (Type * Ty) inline
Definition at line 384 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::ISD::FSQRT, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), and llvm::TargetLoweringBase::isTypeLegal().
isAlwaysUniform()
template<typename T > bool llvm::BasicTTIImplBase< T >::isAlwaysUniform (const Value * V) inline
Definition at line 211 of file BasicTTIImpl.h.
isFCmpOrdCheaperThanFCmpZero()
template<typename T > bool llvm::BasicTTIImplBase< T >::isFCmpOrdCheaperThanFCmpZero (Type * Ty) inline
Definition at line 391 of file BasicTTIImpl.h.
isHardwareLoopProfitable()
template<typename T > bool llvm::BasicTTIImplBase< T >::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) inline
Definition at line 497 of file BasicTTIImpl.h.
References llvm::TargetTransformInfo::isHardwareLoopProfitable().
isIndexedLoadLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isIndexedLoadLegal (TTI::MemIndexedMode M, Type * Ty, const DataLayout & DL) const inline
Definition at line 237 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isIndexedLoadLegal().
isIndexedStoreLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isIndexedStoreLegal (TTI::MemIndexedMode M, Type * Ty, const DataLayout & DL) const inline
Definition at line 243 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isIndexedStoreLegal().
isLegalAddImmediate()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalAddImmediate (int64_t imm) inline
Definition at line 218 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isLegalAddImmediate().
isLegalAddressingMode()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr) inline
Definition at line 226 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::AddrMode::HasBaseReg, I, llvm::TargetLoweringBase::isLegalAddressingMode(), and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalICmpImmediate (int64_t imm) inline
Definition at line 222 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isLegalICmpImmediate().
isLSRCostLess()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2) inline
Definition at line 249 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::isLSRCostLess().
isProfitableToHoist()
template<typename T > bool llvm::BasicTTIImplBase< T >::isProfitableToHoist (Instruction * I) inline
Definition at line 267 of file BasicTTIImpl.h.
References I, and llvm::TargetLoweringBase::isProfitableToHoist().
isSourceOfDivergence()
template<typename T > bool llvm::BasicTTIImplBase< T >::isSourceOfDivergence (const Value * V) inline
Definition at line 209 of file BasicTTIImpl.h.
isTruncateFree()
template<typename T > bool llvm::BasicTTIImplBase< T >::isTruncateFree (Type * Ty1, Type * Ty2) inline
Definition at line 263 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isTruncateFree().
isTypeLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isTypeLegal (Type * Ty) inline
Definition at line 273 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isTypeLegal().
shouldBuildLookupTables()
template<typename T > bool llvm::BasicTTIImplBase< T >::shouldBuildLookupTables () inline
Definition at line 378 of file BasicTTIImpl.h.
References llvm::ISD::BR_JT, llvm::ISD::BRIND, llvm::TargetLoweringBase::isOperationLegalOrCustom(), and llvm::MVT::Other.
useAA()
template<typename T > bool llvm::BasicTTIImplBase< T >::useAA () const inline
Definition at line 271 of file BasicTTIImpl.h.
References llvm::TargetSubtargetInfo::useAA().
Member Data Documentation
DL
template<typename T > const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 35 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< T >::getExtCost(), llvm::BasicTTIImplBase< T >::getFPOpCost(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< T >::getNumberOfParts(), llvm::BasicTTIImplBase< T >::getScalingFactorCost(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), llvm::BasicTTIImplBase< T >::haveFastSqrt(), llvm::BasicTTIImplBase< T >::isIndexedLoadLegal(), llvm::BasicTTIImplBase< T >::isIndexedStoreLegal(), llvm::BasicTTIImplBase< T >::isLegalAddressingMode(), and llvm::BasicTTIImplBase< T >::isTypeLegal().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/BasicTTIImpl.h