LLVM: llvm::DITypeRefArray Class Reference
llvm::DITypeRefArray Class Reference
#include "llvm/IR/DebugInfoMetadata.h"
Classes
class iterator
Public Member Functions
DITypeRefArray ()=default
DITypeRefArray (const MDTuple *N)
operator bool () const
operator MDTuple * () const
MDTuple * get () const
MDTuple * operator-> () const
MDTuple & operator* () const
unsigned size () const
DIType * operator[] (unsigned I) const
iterator begin () const
iterator end () const
Detailed Description
Definition at line 63 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DITypeRefArray() [1/2]
llvm::DITypeRefArray::DITypeRefArray () default
DITypeRefArray() [2/2]
llvm::DITypeRefArray::DITypeRefArray (const MDTuple * N) inline
Definition at line 68 of file DebugInfoMetadata.h.
References N.
Member Function Documentation
begin()
iterator llvm::DITypeRefArray::begin () const inline
Definition at line 109 of file DebugInfoMetadata.h.
References N.
end()
iterator llvm::DITypeRefArray::end () const inline
Definition at line 110 of file DebugInfoMetadata.h.
References N.
get()
MDTuple * llvm::DITypeRefArray::get () const inline
Definition at line 73 of file DebugInfoMetadata.h.
References N.
Referenced by llvm::AliasSetTracker::add(), llvm::AttributeSet::addAttribute(), llvm::AttributeList::addAttributes(), llvm::Function::addFnAttr(), llvm::Module::addModuleFlag(), llvm::AddOne(), llvm::AttributeList::addParamAttribute(), AddRuntimeUnrollDisableMetaData(), llvm::GlobalObject::addTypeMetadata(), llvm::GVNExpression::BasicExpression::allocateOperands(), llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::DIExpression::append(), BinomialCoefficient(), llvm::coro::Shape::buildFrom(), buildNew(), llvm::slpvectorizer::BoUpSLP::canMapToVector(), canonicalizeBitCastExtElt(), canonicalizeCmpWithConstant(), canonicalizeInsertSplat(), canonicalizeMetadataForValue(), canonicalizeSaturatedAdd(), llvm::canSinkOrHoistInst(), llvm::CoroIdInst::clearPromise(), llvm::DILocation::cloneWithDiscriminator(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), collectInsertionElements(), collectShuffleElements(), collectSingleShuffleElements(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::ObjectSizeOffsetEvaluator::compute(), computeUnlikelySuccessors(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), ConvertShiftToMul(), llvm::GlobalObject::copyMetadata(), llvm::SanitizerStatReport::create(), createAccessTag(), llvm::IRBuilder< T, Inserter >::CreateAggregateRet(), llvm::MDBuilder::createAliasScope(), llvm::MDBuilder::createAliasScopeDomain(), llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption(), llvm::IRBuilder< T, Inserter >::CreateAnd(), createAndInstr(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createArrayType(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::DIBuilder::createBasicType(), llvm::TargetFolder::CreateBinOp(), llvm::ConstantFolder::CreateBinOp(), llvm::DIBuilder::createBitFieldMemberType(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCommonBlock(), llvm::MDBuilder::createConstant(), llvm::DIBuilder::createConstantValueExpression(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP2_64(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createExpression(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), llvm::DIBuilder::createFriend(), llvm::MDBuilder::createFunctionEntryCount(), llvm::MDBuilder::createFunctionSectionPrefix(), CreateGCRelocates(), llvm::IRBuilder< T, Inserter >::CreateGlobalStringPtr(), llvm::DIBuilder::createGlobalVariableExpression(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::DIBuilder::createLabel(), llvm::DIBuilder::createLexicalBlockFile(), createLocalVariable(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::DIBuilder::createMacro(), createMalloc(), createMaskedBitTest(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::InstCombiner::CreateNonTerminatorUnreachable(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::InstCombiner::CreateOverflowTuple(), llvm::DIBuilder::createPointerType(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), createPrivateGlobalForSourceLoc(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), createRdxShuffleMask(), llvm::DIBuilder::createReferenceType(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DIBuilder::createStaticMemberType(), llvm::MDBuilder::createString(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::DIBuilder::createTemplateTemplateParameter(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::TargetFolder::CreateUnOp(), llvm::ConstantFolder::CreateUnOp(), llvm::MDBuilder::createUnpredictable(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantPart(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::DIBuilder::createVectorType(), llvm::IRBuilder< T, Inserter >::CreateXor(), llvm::GVNExpression::BasicExpression::deallocateOperands(), DecodeFixedType(), decomposeBitTestICmp(), llvm::FileCheckPatternContext::defineCmdlineVariables(), deleteDeadInstruction(), llvm::DependenceInfo::depends(), llvm::EmitGEPOffset(), llvm::InnerLoopVectorizer::emitMinimumIterationCountCheck(), EmitX86ScalarSelect(), llvm::Evaluator::EvaluateBlock(), evaluateGEPOffsetExpression(), evaluateInDifferentElementOrder(), llvm::VPlan::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::SCEVExpander::expandUnionPredicate(), llvm::DIExpression::extractAddressClass(), extractVector(), FactorOutConstant(), llvm::DIBuilder::finalize(), findBaseDefiningValue(), findBaseDefiningValueOfVector(), findBasePointer(), llvm::SanitizerStatReport::finish(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldAndOrOfEqualityCmpsWithConstants(), foldConstantInsEltIntoShuffle(), foldCtpop(), foldCttzCtlz(), foldFDivConstantDivisor(), foldICmpBitCast(), foldICmpShlOne(), foldICmpWithTruncSignExtendedVal(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), foldIsPowerOf2(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), foldVectorCmp(), foldVecTruncToExtElt(), forceIndeterminateEdge(), llvm::SCEVExpander::generateOverflowCheck(), llvm::ConstantVector::get(), llvm::gvn::AvailableValueInBlock::get(), llvm::AttributeList::get(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::MDNode::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataArray::get(), llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::VectorType::get(), llvm::StructType::get(), llvm::DebugLoc::get(), llvm::ConstantExpr::getAddrSpaceCast(), getAISize(), llvm::ConstantExpr::getAlignOf(), llvm::Constant::getAllOnesValue(), getAlternateBinop(), GetAnyNonZeroConstInt(), getAsConstantIndexedAddress(), llvm::GlobalVariable::getAttributesAsList(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), llvm::DINode::getCanonicalMDString(), llvm::DIMacroNode::getCanonicalMDString(), llvm::ValueLatticeElement::getCompare(), llvm::ScalarEvolution::getConstant(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), getConstantOrNull(), getDbgIntrinsicValueImpl(), llvm::AbstractAttribute::getDeducedAttributes(), llvm::VectorType::getDoubleElementsVectorType(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::VectorType::getExtendedElementVectorType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ScalarEvolution::getGEPExpr(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::VectorType::getHalfElementsVectorType(), llvm::ConstantExpr::getICmp(), llvm::ConstantDataSequential::getImpl(), llvm::DataLayout::getIndexType(), llvm::getInlineCost(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt1(), llvm::IRBuilderBase::getInt16(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::VectorType::getInteger(), llvm::Constant::getIntegerValue(), llvm::IRBuilderBase::getIntN(), llvm::Type::getIntNTy(), llvm::DataLayout::getIntPtrType(), llvm::VNCoercion::getLoadValueForLoad(), llvm::ProfileSummary::getMD(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getMemSetPatternValue(), llvm::DILocation::getMergedLocation(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::Constant::getNullValue(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::ConstantExpr::getOffsetOf(), llvm::DIBuilder::getOrCreateArray(), llvm::DIBuilder::getOrCreateMacroArray(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), getOrInsertValueProfilingCall(), getOrSelfReference(), llvm::Type::getPointerTo(), getPreStartForExtend(), llvm::ConstantDataArray::getRaw(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), getReducedType(), llvm::getSafeVectorConstantForBinop(), llvm::UndefValue::getSequentialElement(), llvm::ConstantExpr::getShuffleVector(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::ConstantExpr::getSizeOf(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::DependenceInfo::getSplitIteration(), llvm::InstrProfIncrementInst::getStep(), llvm::InnerLoopVectorizer::getStepVector(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::UndefValue::getStructElement(), getSubprogram(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::ConstantInt::getTrue(), llvm::VectorType::getTruncatedElementVectorType(), llvm::Intrinsic::getType(), llvm::ConstantStruct::getTypeForElements(), getTypePartition(), llvm::ScalarEvolution::getUDivExpr(), llvm::SSAUpdaterTraits< SSAUpdater >::GetUndefVal(), llvm::PointerType::getUnqual(), llvm::ScalarEvolution::getURemExpr(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::ConstantExpr::getWithOperands(), getX86MaskVec(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ValueAsMetadata::handleRAUW(), hasAddressTakenAndUsed(), llvm::PHINode::hasConstantValue(), llvm::hoistRegion(), llvm::FunctionImporter::importFunctions(), insertSinCosCall(), insertUseHolderAfter(), insertVector(), instrumentMaskedLoadOrStore(), llvm::ScaledNumber< DigitsT >::invert(), IsIncrementNSW(), IsIncrementNUW(), isLoadInvariantInLoop(), isVectorPromotionViableForSlice(), legalizeCallAttributes(), LinearizeExprTree(), LLVMAddTargetDependentFunctionAttr(), LLVMCreateEnumAttribute(), LLVMCreateStringAttribute(), LLVMDIBuilderCreateDebugLocation(), lookThroughAnd(), LowerNegateToMultiply(), llvm::CmpInst::makeCmpResultType(), makeStatepointExplicitImpl(), llvm::coro::LowererBase::makeSubFnCall(), llvm::FileCheckPattern::match(), MatchBinaryOp(), matchIntrinsicType(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::MDBuilder::mergeCallbackEncodings(), narrowVectorSelect(), llvm::EscapeEnumerator::Next(), operator bool(), operator MDTuple *(), operator*(), operator->(), optimizeMemCmpConstantSize(), optimizeVectorResize(), llvm::LLParser::ParseMDField(), llvm::FileCheckPattern::parseNumericSubstitutionBlock(), llvm::FileCheckPattern::parseNumericVariableDefinition(), llvm::FileCheckPattern::parseVariable(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prependOpcodes(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), processUGT_ADDCST_ADD(), relocationViaAlloca(), removeBitcastsFromLoadStoreOnMinMax(), llvm::PHINode::removeIncomingValue(), RemoveNonValidAttrAtIndex(), llvm::BasicBlock::removePredecessor(), llvm::coro::replaceCoroFree(), replaceExtractElements(), replaceGEPIdxWithZero(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InnerLoopVectorizer::reverseVector(), rewriteGEPAsOffset(), llvm::InstCombiner::run(), llvm::LoadAndStorePromoter::run(), llvm::runIPSCCP(), llvm::SanitizerStatReport::SanitizerStatReport(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setInlineRemark(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Module::setSDKVersion(), shrinkFPConstantVector(), shrinkInsertElt(), shrinkSplatShuffle(), simplifyAssocCastAssoc(), simplifyNeonTbl1(), simplifyNeonVld1(), SimplifyNVVMIntrinsic(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), sink(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), stripDebugLocFromLoopID(), stripNonValidDataFromBody(), llvm::SubOne(), llvm::Instruction::swapProfMetadata(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryMergeRange(), TryToSinkInstruction(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::CallInst::updateProfWeight(), upgradeMaskedCompare(), valueHasFloatPrecision(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::InnerLoopVectorizer::widenPHIInstruction(), and llvm::BasicBlock::~BasicBlock().
operator bool()
llvm::DITypeRefArray::operator bool () const inline explicit
Definition at line 70 of file DebugInfoMetadata.h.
References get().
operator MDTuple *()
llvm::DITypeRefArray::operator MDTuple * () const inline explicit
Definition at line 71 of file DebugInfoMetadata.h.
References get().
operator*()
MDTuple & llvm::DITypeRefArray::operator* () const inline
Definition at line 75 of file DebugInfoMetadata.h.
References get().
operator->()
MDTuple * llvm::DITypeRefArray::operator-> () const inline
Definition at line 74 of file DebugInfoMetadata.h.
References get().
operator[]()
DIType * llvm::DITypeRefArray::operator[] (unsigned I) const inline
Definition at line 79 of file DebugInfoMetadata.h.
References I, and N.
size()
unsigned llvm::DITypeRefArray::size () const inline
Definition at line 78 of file DebugInfoMetadata.h.
References N.
The documentation for this class was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h