LLVM: llvm::SSAUpdaterTraits< SSAUpdater > Class Reference
llvm::SSAUpdaterTraits< SSAUpdater > Class Reference
Classes
class PHI_iterator
Public Types
using BlkT = BasicBlock
using ValT = Value *
using PhiT = PHINode
using BlkSucc_iterator = succ_iterator
Static Public Member Functions
static BlkSucc_iterator BlkSucc_begin (BlkT *BB)
static BlkSucc_iterator BlkSucc_end (BlkT *BB)
static PHI_iterator PHI_begin (PhiT *PHI)
static PHI_iterator PHI_end (PhiT *PHI)
static void FindPredecessorBlocks (BasicBlock *BB, SmallVectorImpl< BasicBlock * > *Preds)
FindPredecessorBlocks - Put the predecessors of Info->BB into the Preds vector, set Info->NumPreds, and allocate space in Info->Preds.
static Value * GetUndefVal (BasicBlock *BB, SSAUpdater *Updater)
GetUndefVal - Get an undefined value of the same type as the value being handled.
static Value * CreateEmptyPHI (BasicBlock *BB, unsigned NumPreds, SSAUpdater *Updater)
CreateEmptyPHI - Create a new PHI instruction in the specified block.
static void AddPHIOperand (PHINode *PHI, Value *Val, BasicBlock *Pred)
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
static PHINode * InstrIsPHI (Instruction *I)
InstrIsPHI - Check if an instruction is a PHI.
static PHINode * ValueIsPHI (Value *Val, SSAUpdater *Updater)
ValueIsPHI - Check if a value is a PHI.
static PHINode * ValueIsNewPHI (Value *Val, SSAUpdater *Updater)
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
static Value * GetPHIValue (PHINode *PHI)
GetPHIValue - For the specified PHI instruction, return the value that it defines.
Detailed Description
Definition at line 221 of file SSAUpdater.cpp.
Member Typedef Documentation
BlkSucc_iterator
using llvm::SSAUpdaterTraits< SSAUpdater >::BlkSucc_iterator = succ_iterator
Definition at line 226 of file SSAUpdater.cpp.
BlkT
using llvm::SSAUpdaterTraits< SSAUpdater >::BlkT = BasicBlock
Definition at line 223 of file SSAUpdater.cpp.
PhiT
using llvm::SSAUpdaterTraits< SSAUpdater >::PhiT = PHINode
Definition at line 225 of file SSAUpdater.cpp.
ValT
using llvm::SSAUpdaterTraits< SSAUpdater >::ValT = Value *
Definition at line 224 of file SSAUpdater.cpp.
Member Function Documentation
AddPHIOperand()
static void llvm::SSAUpdaterTraits< SSAUpdater >::AddPHIOperand (PHINode * PHI, Value * Val, BasicBlock * Pred) inline static
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
Definition at line 287 of file SSAUpdater.cpp.
References llvm::PHINode::addIncoming().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
BlkSucc_begin()
static BlkSucc_iterator llvm::SSAUpdaterTraits< SSAUpdater >::BlkSucc_begin (BlkT * BB) inline static
Definition at line 228 of file SSAUpdater.cpp.
References llvm::succ_begin().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
BlkSucc_end()
static BlkSucc_iterator llvm::SSAUpdaterTraits< SSAUpdater >::BlkSucc_end (BlkT * BB) inline static
Definition at line 229 of file SSAUpdater.cpp.
References llvm::succ_end().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
CreateEmptyPHI()
static Value * llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI (BasicBlock * BB, unsigned NumPreds, SSAUpdater * Updater) inline static
CreateEmptyPHI - Create a new PHI instruction in the specified block.
Reserve space for the operands but do not fill them in yet.
Definition at line 278 of file SSAUpdater.cpp.
References llvm::PHINode::Create(), and llvm::BasicBlock::front().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
FindPredecessorBlocks()
static void llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks (BasicBlock * BB, SmallVectorImpl< BasicBlock * > * Preds) inline static
FindPredecessorBlocks - Put the predecessors of Info->BB into the Preds vector, set Info->NumPreds, and allocate space in Info->Preds.
Definition at line 257 of file SSAUpdater.cpp.
References llvm::BasicBlock::begin(), llvm::pred_begin(), and llvm::pred_end().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
GetPHIValue()
static Value * llvm::SSAUpdaterTraits< SSAUpdater >::GetPHIValue (PHINode * PHI) inline static
GetPHIValue - For the specified PHI instruction, return the value that it defines.
Definition at line 313 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs().
GetUndefVal()
static Value * llvm::SSAUpdaterTraits< SSAUpdater >::GetUndefVal (BasicBlock * BB, SSAUpdater * Updater) inline static
GetUndefVal - Get an undefined value of the same type as the value being handled.
Definition at line 272 of file SSAUpdater.cpp.
References llvm::DITypeRefArray::get().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), and llvm::SSAUpdaterImpl< UpdaterT >::GetValue().
InstrIsPHI()
static PHINode * llvm::SSAUpdaterTraits< SSAUpdater >::InstrIsPHI (Instruction * I) inline static
InstrIsPHI - Check if an instruction is a PHI.
Definition at line 293 of file SSAUpdater.cpp.
References I.
PHI_begin()
static PHI_iterator llvm::SSAUpdaterTraits< SSAUpdater >::PHI_begin (PhiT * PHI) inline static
Definition at line 250 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
PHI_end()
static PHI_iterator llvm::SSAUpdaterTraits< SSAUpdater >::PHI_end (PhiT * PHI) inline static
Definition at line 251 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
ValueIsNewPHI()
static PHINode * llvm::SSAUpdaterTraits< SSAUpdater >::ValueIsNewPHI (Value * Val, SSAUpdater * Updater) inline static
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
Definition at line 304 of file SSAUpdater.cpp.
References llvm::PHINode::getNumIncomingValues().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
ValueIsPHI()
static PHINode * llvm::SSAUpdaterTraits< SSAUpdater >::ValueIsPHI (Value * Val, SSAUpdater * Updater) inline static
ValueIsPHI - Check if a value is a PHI.
Definition at line 298 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/SSAUpdater.cpp