LLVM: llvm::VLIWPacketizerList Class Reference
llvm::VLIWPacketizerList Class Reference
#include "llvm/CodeGen/DFAPacketizer.h"
Public Member Functions
VLIWPacketizerList (MachineFunction &MF, MachineLoopInfo &MLI, AliasAnalysis *AA)
virtual ~VLIWPacketizerList ()
void PacketizeMIs (MachineBasicBlock *MBB, MachineBasicBlock::iterator BeginItr, MachineBasicBlock::iterator EndItr)
DFAPacketizer * getResourceTracker ()
virtual MachineBasicBlock::iterator addToPacket (MachineInstr &MI)
virtual void endPacket (MachineBasicBlock *MBB, MachineBasicBlock::iterator MI)
virtual void initPacketizerState ()
virtual bool ignorePseudoInstruction (const MachineInstr &I, const MachineBasicBlock *MBB)
virtual bool isSoloInstruction (const MachineInstr &MI)
virtual bool shouldAddToPacket (const MachineInstr &MI)
virtual bool isLegalToPacketizeTogether (SUnit *SUI, SUnit *SUJ)
virtual bool isLegalToPruneDependencies (SUnit *SUI, SUnit *SUJ)
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
bool alias (const MachineInstr &MI1, const MachineInstr &MI2, bool UseTBAA=true) const
Protected Attributes
MachineFunction & MF
const TargetInstrInfo * TII
AliasAnalysis * AA
DefaultVLIWScheduler * VLIWScheduler
std::vector< MachineInstr * > CurrentPacketMIs
DFAPacketizer * ResourceTracker
std::map< MachineInstr *, SUnit * > MIToSUnit
Detailed Description
Definition at line 133 of file DFAPacketizer.h.
Constructor & Destructor Documentation
VLIWPacketizerList()
VLIWPacketizerList::VLIWPacketizerList (MachineFunction & MF, MachineLoopInfo & MLI, AliasAnalysis * AA)
Definition at line 209 of file DFAPacketizer.cpp.
References AA, llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::MachineFunction::getSubtarget(), MF, ResourceTracker, TII, and VLIWScheduler.
~VLIWPacketizerList()
VLIWPacketizerList::~VLIWPacketizerList () virtual
Definition at line 216 of file DFAPacketizer.cpp.
References ResourceTracker, and VLIWScheduler.
Member Function Documentation
addMutation()
void VLIWPacketizerList::addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
Definition at line 372 of file DFAPacketizer.cpp.
References llvm::DefaultVLIWScheduler::addMutation(), Mutation, and VLIWScheduler.
addToPacket()
virtual MachineBasicBlock::iterator llvm::VLIWPacketizerList::addToPacket (MachineInstr & MI) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 164 of file DFAPacketizer.h.
References CurrentPacketMIs, MI, llvm::DFAPacketizer::reserveResources(), and ResourceTracker.
Referenced by PacketizeMIs().
alias()
bool VLIWPacketizerList::alias (const MachineInstr & MI1, const MachineInstr & MI2, bool UseTBAA = true) const
Definition at line 358 of file DFAPacketizer.cpp.
References alias(), llvm::MachineInstr::memoperands(), llvm::MachineInstr::memoperands_empty(), and UseTBAA.
Referenced by alias(), and llvm::HexagonPacketizerList::isLegalToPacketizeTogether().
endPacket()
void VLIWPacketizerList::endPacket (MachineBasicBlock * MBB, MachineBasicBlock::iterator MI) virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 222 of file DFAPacketizer.cpp.
References llvm::DFAPacketizer::clearResources(), CurrentPacketMIs, llvm::dbgs(), llvm::finalizeBundle(), llvm::ilist_node_impl< OptionsT >::getIterator(), LLVM_DEBUG, MI, and ResourceTracker.
Referenced by PacketizeMIs().
getResourceTracker()
DFAPacketizer * llvm::VLIWPacketizerList::getResourceTracker () inline
Definition at line 161 of file DFAPacketizer.h.
References ResourceTracker.
ignorePseudoInstruction()
virtual bool llvm::VLIWPacketizerList::ignorePseudoInstruction (const MachineInstr & I, const MachineBasicBlock * MBB) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 181 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
initPacketizerState()
virtual void llvm::VLIWPacketizerList::initPacketizerState () inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 178 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
isLegalToPacketizeTogether()
virtual bool llvm::VLIWPacketizerList::isLegalToPacketizeTogether (SUnit * SUI, SUnit * SUJ) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 199 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
isLegalToPruneDependencies()
virtual bool llvm::VLIWPacketizerList::isLegalToPruneDependencies (SUnit * SUI, SUnit * SUJ) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 204 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
isSoloInstruction()
virtual bool llvm::VLIWPacketizerList::isSoloInstruction (const MachineInstr & MI) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 188 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
PacketizeMIs()
void VLIWPacketizerList::PacketizeMIs (MachineBasicBlock * MBB, MachineBasicBlock::iterator BeginItr, MachineBasicBlock::iterator EndItr)
Definition at line 241 of file DFAPacketizer.cpp.
References addToPacket(), assert(), llvm::DFAPacketizer::canReserveResources(), CurrentPacketMIs, llvm::dbgs(), llvm::ScheduleDAGInstrs::dump(), endPacket(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::ScheduleDAGInstrs::exitRegion(), llvm::ScheduleDAGInstrs::finishBlock(), llvm::SUnit::getInstr(), ignorePseudoInstruction(), initPacketizerState(), InstrCount, InstrLimit, isLegalToPacketizeTogether(), isLegalToPruneDependencies(), isSoloInstruction(), LLVM_DEBUG, MI, MIToSUnit, ResourceTracker, llvm::DefaultVLIWScheduler::schedule(), shouldAddToPacket(), llvm::ScheduleDAGInstrs::startBlock(), llvm::ScheduleDAG::SUnits, and VLIWScheduler.
shouldAddToPacket()
virtual bool llvm::VLIWPacketizerList::shouldAddToPacket (const MachineInstr & MI) inline virtual
Reimplemented in llvm::HexagonPacketizerList.
Definition at line 196 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
Member Data Documentation
AA
AliasAnalysis* llvm::VLIWPacketizerList::AA protected
Definition at line 137 of file DFAPacketizer.h.
Referenced by VLIWPacketizerList().
CurrentPacketMIs
std::vector<MachineInstr*> llvm::VLIWPacketizerList::CurrentPacketMIs protected
Definition at line 142 of file DFAPacketizer.h.
Referenced by addToPacket(), llvm::HexagonPacketizerList::addToPacket(), llvm::HexagonPacketizerList::arePredicatesComplements(), llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), llvm::HexagonPacketizerList::cleanUpDotCur(), endPacket(), llvm::HexagonPacketizerList::endPacket(), llvm::HexagonPacketizerList::foundLSInPacket(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), PacketizeMIs(), llvm::HexagonPacketizerList::producesStall(), and llvm::HexagonPacketizerList::restrictingDepExistInPacket().
MF
MachineFunction& llvm::VLIWPacketizerList::MF protected
Definition at line 135 of file DFAPacketizer.h.
Referenced by llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::canPromoteToDotNew(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), llvm::HexagonPacketizerList::useCalleesSP(), llvm::HexagonPacketizerList::useCallersSP(), and VLIWPacketizerList().
MIToSUnit
std::map<MachineInstr*, SUnit*> llvm::VLIWPacketizerList::MIToSUnit protected
Definition at line 146 of file DFAPacketizer.h.
Referenced by llvm::HexagonPacketizerList::arePredicatesComplements(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), PacketizeMIs(), llvm::HexagonPacketizerList::producesStall(), and llvm::HexagonPacketizerList::restrictingDepExistInPacket().
ResourceTracker
DFAPacketizer* llvm::VLIWPacketizerList::ResourceTracker protected
Definition at line 144 of file DFAPacketizer.h.
Referenced by addToPacket(), llvm::HexagonPacketizerList::addToPacket(), llvm::HexagonPacketizerList::canPromoteToDotNew(), endPacket(), llvm::HexagonPacketizerList::endPacket(), getResourceTracker(), llvm::HexagonPacketizerList::ignorePseudoInstruction(), PacketizeMIs(), llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt(), VLIWPacketizerList(), and ~VLIWPacketizerList().
TII
const TargetInstrInfo* llvm::VLIWPacketizerList::TII protected
Definition at line 136 of file DFAPacketizer.h.
Referenced by VLIWPacketizerList().
VLIWScheduler
DefaultVLIWScheduler* llvm::VLIWPacketizerList::VLIWScheduler protected
Definition at line 140 of file DFAPacketizer.h.
Referenced by addMutation(), PacketizeMIs(), VLIWPacketizerList(), and ~VLIWPacketizerList().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DFAPacketizer.h
lib/CodeGen/DFAPacketizer.cpp