LLVM: llvm::ReversePostOrderFunctionAttrsPass Class Reference
llvm::ReversePostOrderFunctionAttrsPass Class Reference
A pass to do RPO deduction and propagation of function attributes.
#include "llvm/Transforms/IPO/FunctionAttrs.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ReversePostOrderFunctionAttrsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass to do RPO deduction and propagation of function attributes.
This pass provides a general RPO or "top down" propagation of function attributes. For a few (rare) cases, we can deduce significantly more about function attributes by working in RPO, so this pass provides the complement to the post-order pass above where the majority of deduction is performed.
Definition at line 69 of file FunctionAttrs.h.
Member Function Documentation
run()
PreservedAnalyses ReversePostOrderFunctionAttrsPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 1612 of file FunctionAttrs.cpp.
References llvm::PreservedAnalyses::all(), deduceFunctionAttributeInRPO(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserve().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/FunctionAttrs.h
lib/Transforms/IPO/FunctionAttrs.cpp