LLVM: llvm::FPPassManager Class Reference
llvm::FPPassManager Class Reference
FPPassManager manages BBPassManagers and FunctionPasses.
#include "llvm/IR/LegacyPassManagers.h"
Public Member Functions
FPPassManager ()
bool runOnFunction (Function &F)
run - Execute all of the passes scheduled for execution.
bool runOnModule (Module &M) override
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void cleanup ()
cleanup - After running all passes, clean up pass manager cache.
bool doInitialization (Module &M) override
doInitialization - Run all of the initializers for the function passes.
bool doFinalization (Module &M) override
doFinalization - Run all of the finalizers for the function passes.
PMDataManager * getAsPMDataManager () override
Pass * getAsPass () override
void getAnalysisUsage (AnalysisUsage &Info) const override
Pass Manager itself does not invalidate any analysis info.
void dumpPassStructure (unsigned Offset) override
Print passes managed by this manager.
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
FunctionPass * getContainedPass (unsigned N)
PassManagerType getPassManagerType () const override
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Member Functions inherited from llvm::PMDataManager
PMDataManager ()
virtual ~PMDataManager ()
virtual Pass * getAsPass ()=0
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
Add pass P into the PassVector.
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
Add RequiredPass into list of lower level passes required by pass P.
virtual Pass * getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAndUsedAnalyses (SmallVectorImpl< Pass * > &UsedPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
Populate UsedPasses with analysis pass that are used or required by pass P and are available.
void initializeAnalysisImpl (Pass *P)
All Required analyses should be available to the pass as it runs! Here we fill in the AnalysisImpls member of the pass so that it can successfully use the getAnalysis() method to retrieve the implementations it needs.
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
Find the pass that implements Analysis AID.
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
void dumpUsedSet (const Pass *P) const
unsigned getNumContainedPasses () const
virtual PassManagerType getPassManagerType () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
unsigned initSizeRemarkInfo (Module &M, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount)
Set the initial size of the module if the user has specified that they want remarks for size.
void emitInstrCountChangedRemark (Pass *P, Module &M, int64_t Delta, unsigned CountBefore, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount, Function *F=nullptr)
Emit a remark signifying that the number of IR instructions in the module changed.
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Protected Member Functions inherited from llvm::PMDataManager
bool isPassDebuggingExecutionsOrMore () const
isPassDebuggingExecutionsOrMore - Return true if -debug-pass=Executions or higher is specified.
Protected Attributes inherited from llvm::PMDataManager
PMTopLevelManager * TPM
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Detailed Description
FPPassManager manages BBPassManagers and FunctionPasses.
It batches all function passes and basic block pass managers together and sequence them to process one function at a time before processing next function.
Definition at line 466 of file LegacyPassManagers.h.
Constructor & Destructor Documentation
FPPassManager()
llvm::FPPassManager::FPPassManager () inline explicit
Definition at line 469 of file LegacyPassManagers.h.
Member Function Documentation
cleanup()
void FPPassManager::cleanup ()
cleanup - After running all passes, clean up pass manager cache.
Definition at line 1557 of file LegacyPassManager.cpp.
References assert(), and llvm::AnalysisResolver::clearAnalysisImpls().
Referenced by llvm::legacy::FunctionPassManagerImpl::run().
doFinalization()
bool FPPassManager::doFinalization (Module & M) override virtual
doFinalization - Run all of the finalizers for the function passes.
Reimplemented from llvm::Pass.
Definition at line 1699 of file LegacyPassManager.cpp.
Referenced by llvm::legacy::FunctionPassManagerImpl::doFinalization().
doInitialization()
bool FPPassManager::doInitialization (Module & M) override virtual
doInitialization - Run all of the initializers for the function passes.
Reimplemented from llvm::Pass.
Definition at line 1690 of file LegacyPassManager.cpp.
Referenced by llvm::legacy::FunctionPassManagerImpl::doInitialization().
dumpPassStructure()
void FPPassManager::dumpPassStructure (unsigned Offset) override virtual
Print passes managed by this manager.
Reimplemented from llvm::Pass.
Definition at line 1601 of file LegacyPassManager.cpp.
References llvm::dbgs(), and llvm::raw_ostream::indent().
getAnalysisUsage()
void llvm::FPPassManager::getAnalysisUsage (AnalysisUsage & Info) const inline override virtual
Pass Manager itself does not invalidate any analysis info.
Reimplemented from llvm::Pass.
Definition at line 502 of file LegacyPassManagers.h.
References Info.
getAsPass()
Pass * llvm::FPPassManager::getAsPass () inline override virtual
Implements llvm::PMDataManager.
Definition at line 499 of file LegacyPassManagers.h.
getAsPMDataManager()
PMDataManager * llvm::FPPassManager::getAsPMDataManager () inline override virtual
Reimplemented from llvm::Pass.
Definition at line 498 of file LegacyPassManagers.h.
getContainedPass()
FunctionPass * llvm::FPPassManager::getContainedPass (unsigned N) inline
Definition at line 511 of file LegacyPassManagers.h.
References assert(), N, and llvm::PMDataManager::PassVector.
Referenced by llvm::legacy::FunctionPassManagerImpl::releaseMemoryOnTheFly().
getPassManagerType()
PassManagerType llvm::FPPassManager::getPassManagerType () const inline override virtual
Reimplemented from llvm::PMDataManager.
Definition at line 517 of file LegacyPassManagers.h.
References llvm::PMT_FunctionPassManager.
getPassName()
StringRef llvm::FPPassManager::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 509 of file LegacyPassManagers.h.
runOnFunction()
bool FPPassManager::runOnFunction (Function & F)
run - Execute all of the passes scheduled for execution.
Execute all of the passes scheduled for execution by invoking runOnFunction method.
Keep track of whether any of the passes modifies the module, and if so, return true.
Keep track of whether any of the passes modifies the function, and if so, return true.
Definition at line 1614 of file LegacyPassManager.cpp.
References llvm::EXECUTION_MSG, F, llvm::getPassTimer(), InstrCount, llvm::MODIFICATION_MSG, llvm::ON_FUNCTION_MSG, and X.
Referenced by llvm::legacy::FunctionPassManagerImpl::run().
runOnModule()
bool FPPassManager::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 1680 of file LegacyPassManager.cpp.
References F, and runOnFunction().
Member Data Documentation
ID
char FPPassManager::ID = 0 static
Definition at line 468 of file LegacyPassManagers.h.
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManagers.h
lib/IR/LegacyPassManager.cpp