LLVM: llvm::pdb::PDBContext Class Reference
llvm::pdb::PDBContext Class Reference
PDBContext This data structure is the top level entity that deals with PDB debug information parsing.
#include "llvm/DebugInfo/PDB/PDBContext.h"
Public Member Functions
PDBContext (const object::COFFObjectFile &Object, std::unique_ptr< IPDBSession > PDBSession)
PDBContext (PDBContext &)=delete
PDBContext & operator= (PDBContext &)=delete
void dump (raw_ostream &OS, DIDumpOptions DIDumpOpts) override
DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address) override
Public Member Functions inherited from llvm::DIContext
DIContext (DIContextKind K)
virtual ~DIContext ()=default
DIContextKind getKind () const
virtual void dump (raw_ostream &OS, DIDumpOptions DumpOpts)=0
virtual bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={})
virtual DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address)=0
Static Public Member Functions
static bool classof (const DIContext *DICtx)
Additional Inherited Members
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF , CK_PDB }
Detailed Description
PDBContext This data structure is the top level entity that deals with PDB debug information parsing.
This data structure exists only when there is a need for a transparent interface to different debug information formats (e.g. PDB and DWARF). More control and power over the debug information access can be had by using the PDB interfaces directly.
Definition at line 32 of file PDBContext.h.
Constructor & Destructor Documentation
PDBContext() [1/2]
llvm::pdb::PDBContext::PDBContext (const object::COFFObjectFile & Object, std::unique_ptr< IPDBSession > PDBSession)
PDBContext() [2/2]
llvm::pdb::PDBContext::PDBContext (PDBContext &) delete
Member Function Documentation
classof()
static bool llvm::pdb::PDBContext::classof (const DIContext * DICtx) inline static
Definition at line 39 of file PDBContext.h.
References llvm::DIContext::CK_PDB, and llvm::DIContext::getKind().
dump()
void PDBContext::dump (raw_ostream & OS, DIDumpOptions DIDumpOpts) override virtual
Implements llvm::DIContext.
Definition at line 31 of file PDBContext.cpp.
getInliningInfoForAddress()
DIInliningInfo PDBContext::getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 86 of file PDBContext.cpp.
References llvm::DIInliningInfo::addFrame(), llvm::Address, and getLineInfoForAddress().
getLineInfoForAddress()
DILineInfo PDBContext::getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 33 of file PDBContext.cpp.
References llvm::Address, assert(), llvm::DILineInfo::Column, llvm::pdb::Data, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DILineInfo::Line, llvm::pdb::LineNumbers, and llvm::pdb::None.
Referenced by getInliningInfoForAddress(), and getLineInfoForAddressRange().
getLineInfoForAddressRange()
DILineInfoTable PDBContext::getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 66 of file PDBContext.cpp.
References llvm::Address, getLineInfoForAddress(), and llvm::pdb::LineNumbers.
getLocalsForAddress()
std::vector< DILocal > PDBContext::getLocalsForAddress (object::SectionedAddress Address) override virtual
Implements llvm::DIContext.
Definition at line 95 of file PDBContext.cpp.
operator=()
PDBContext & llvm::pdb::PDBContext::operator= (PDBContext &) delete
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/PDBContext.h
lib/DebugInfo/PDB/PDBContext.cpp