LLVM: llvm::codeview::TypeTableCollection Class Reference
llvm::codeview::TypeTableCollection Class Reference
#include "llvm/DebugInfo/CodeView/TypeTableCollection.h"
Public Member Functions
TypeTableCollection (ArrayRef< ArrayRef< uint8_t > > Records)
Optional< TypeIndex > getFirst () override
Optional< TypeIndex > getNext (TypeIndex Prev) override
CVType getType (TypeIndex Index) override
StringRef getTypeName (TypeIndex Index) override
bool contains (TypeIndex Index) override
uint32_t size () override
uint32_t capacity () override
Public Member Functions inherited from llvm::codeview::TypeCollection
virtual ~TypeCollection ()=default
bool empty ()
virtual Optional< TypeIndex > getFirst ()=0
virtual Optional< TypeIndex > getNext (TypeIndex Prev)=0
virtual CVType getType (TypeIndex Index)=0
virtual StringRef getTypeName (TypeIndex Index)=0
virtual bool contains (TypeIndex Index)=0
virtual uint32_t size ()=0
virtual uint32_t capacity ()=0
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 20 of file TypeTableCollection.h.
Constructor & Destructor Documentation
TypeTableCollection()
TypeTableCollection::TypeTableCollection (ArrayRef< ArrayRef< uint8_t > > Records) explicit
Definition at line 18 of file TypeTableCollection.cpp.
Member Function Documentation
capacity()
uint32_t TypeTableCollection::capacity () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 60 of file TypeTableCollection.cpp.
contains()
bool TypeTableCollection::contains (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 54 of file TypeTableCollection.cpp.
References size(), and llvm::codeview::TypeIndex::toArrayIndex().
Referenced by getNext().
getFirst()
Optional< TypeIndex > TypeTableCollection::getFirst () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 23 of file TypeTableCollection.cpp.
References llvm::codeview::TypeCollection::empty(), llvm::codeview::TypeIndex::fromArrayIndex(), and llvm::codeview::None.
getNext()
Optional< TypeIndex > TypeTableCollection::getNext (TypeIndex Prev) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 29 of file TypeTableCollection.cpp.
References assert(), contains(), llvm::codeview::None, size(), and llvm::codeview::TypeIndex::toArrayIndex().
getType()
CVType TypeTableCollection::getType (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 37 of file TypeTableCollection.cpp.
References assert(), and llvm::codeview::TypeIndex::toArrayIndex().
getTypeName()
StringRef TypeTableCollection::getTypeName (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 42 of file TypeTableCollection.cpp.
References llvm::codeview::computeTypeName(), I, llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), llvm::StringSaver::save(), llvm::codeview::TypeIndex::simpleTypeName(), and llvm::codeview::TypeIndex::toArrayIndex().
size()
uint32_t TypeTableCollection::size () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 58 of file TypeTableCollection.cpp.
Referenced by contains(), and getNext().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/TypeTableCollection.h
lib/DebugInfo/CodeView/TypeTableCollection.cpp