LLVM: llvm::orc::ExecutionSession Class Reference
llvm::orc::ExecutionSession Class Reference
An ExecutionSession represents a running JIT program.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Types
using ErrorReporter = std::function< void(Error)>
For reporting errors.
using DispatchMaterializationFunction = std::function< void(JITDylib &JD, std::unique_ptr< MaterializationUnit > MU)>
For dispatching MaterializationUnit::materialize calls.
using LegacyAsyncLookupFunction = std::function< SymbolNameSet(std::shared_ptr< AsynchronousSymbolQuery > Q, SymbolNameSet Names)>
Public Member Functions
ExecutionSession (std::shared_ptr< SymbolStringPool > SSP=nullptr)
Construct an ExecutionSession.
SymbolStringPtr intern (StringRef SymName)
Add a symbol name to the SymbolStringPool and return a pointer to it.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Returns a shared_ptr to the SymbolStringPool for this ExecutionSession.
template<typename Func >
auto runSessionLocked (Func &&F) -> decltype(F())
Run the given lambda with the session mutex locked.
JITDylib & getMainJITDylib ()
Get the "main" JITDylib, which is created automatically on construction of the ExecutionSession.
JITDylib * getJITDylibByName (StringRef Name)
Return a pointer to the "name" JITDylib.
JITDylib & createJITDylib (std::string Name, bool AddToMainDylibSearchOrder=true)
Add a new JITDylib to this ExecutionSession.
VModuleKey allocateVModule ()
Allocate a module key for a new module to add to the JIT.
void releaseVModule (VModuleKey Key)
Return a module key to the ExecutionSession so that it can be re-used.
ExecutionSession & setErrorReporter (ErrorReporter ReportError)
Set the error reporter function.
void reportError (Error Err)
Report a error for this execution session.
ExecutionSession & setDispatchMaterialization (DispatchMaterializationFunction DispatchMaterialization)
Set the materialization dispatch function.
void legacyFailQuery (AsynchronousSymbolQuery &Q, Error Err)
Expected< SymbolMap > legacyLookup (LegacyAsyncLookupFunction AsyncLookup, SymbolNameSet Names, SymbolState RequiredState, RegisterDependenciesFunction RegisterDependencies)
A legacy lookup function for JITSymbolResolverAdapter.
void lookup (const JITDylibSearchList &SearchOrder, SymbolNameSet Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete, RegisterDependenciesFunction RegisterDependencies)
Search the given JITDylib list for the given symbols.
Expected< SymbolMap > lookup (const JITDylibSearchList &SearchOrder, const SymbolNameSet &Symbols, SymbolState RequiredState=SymbolState::Ready, RegisterDependenciesFunction RegisterDependencies=NoDependenciesToRegister)
Blocking version of lookup above.
Expected< JITEvaluatedSymbol > lookup (const JITDylibSearchList &SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Expected< JITEvaluatedSymbol > lookup (ArrayRef< JITDylib * > SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Expected< JITEvaluatedSymbol > lookup (ArrayRef< JITDylib * > SearchOrder, StringRef Symbol)
Convenience version of blocking lookup.
void dispatchMaterialization (JITDylib &JD, std::unique_ptr< MaterializationUnit > MU)
Materialize the given unit.
void dump (raw_ostream &OS)
Dump the state of all the JITDylibs in this session.
Friends
class JITDylib
Detailed Description
An ExecutionSession represents a running JIT program.
Definition at line 753 of file Core.h.
Member Typedef Documentation
DispatchMaterializationFunction
using llvm::orc::ExecutionSession::DispatchMaterializationFunction = std::function<void(JITDylib &JD, std::unique_ptr<MaterializationUnit> MU)>
For dispatching MaterializationUnit::materialize calls.
Definition at line 762 of file Core.h.
ErrorReporter
using llvm::orc::ExecutionSession::ErrorReporter = std::function<void(Error)>
For reporting errors.
Definition at line 759 of file Core.h.
LegacyAsyncLookupFunction
using llvm::orc::ExecutionSession::LegacyAsyncLookupFunction = std::function<SymbolNameSet(std::shared_ptr<AsynchronousSymbolQuery> Q, SymbolNameSet Names)>
Definition at line 829 of file Core.h.
Constructor & Destructor Documentation
ExecutionSession()
llvm::orc::ExecutionSession::ExecutionSession (std::shared_ptr< SymbolStringPool > SSP = nullptr)
Construct an ExecutionSession.
SymbolStringPools may be shared between ExecutionSessions.
Definition at line 1589 of file Core.cpp.
References JITDylib.
Member Function Documentation
allocateVModule()
VModuleKey llvm::orc::ExecutionSession::allocateVModule () inline
Allocate a module key for a new module to add to the JIT.
Definition at line 799 of file Core.h.
References runSessionLocked().
Referenced by llvm::OrcCBindingsStack::addIRModule(), llvm::orc::OrcMCJITReplacement::addModule(), llvm::OrcCBindingsStack::addObject(), llvm::orc::OrcMCJITReplacement::addObjectFile(), and llvm::orc::JITCompileCallbackManager::getCompileCallback().
createJITDylib()
JITDylib & llvm::orc::ExecutionSession::createJITDylib (std::string Name, bool AddToMainDylibSearchOrder = true)
Add a new JITDylib to this ExecutionSession.
The JITDylib Name is required to be unique. Clients should verify that names are not being re-used (e.g. by calling getJITDylibByName) if names are based on user input.
Definition at line 1608 of file Core.cpp.
References assert(), getJITDylibByName(), JITDylib, Name, and runSessionLocked().
dispatchMaterialization()
void llvm::orc::ExecutionSession::dispatchMaterialization (JITDylib & JD, std::unique_ptr< MaterializationUnit > MU) inline
Materialize the given unit.
Definition at line 894 of file Core.h.
References llvm::dbgs(), llvm::orc::JITDylib::getName(), LLVM_DEBUG, and runSessionLocked().
dump()
void llvm::orc::ExecutionSession::dump (raw_ostream & OS)
Dump the state of all the JITDylibs in this session.
Definition at line 1879 of file Core.cpp.
References runSessionLocked().
getJITDylibByName()
JITDylib * llvm::orc::ExecutionSession::getJITDylibByName (StringRef Name)
Return a pointer to the "name" JITDylib.
Ownership of JITDylib remains within Execution Session
Definition at line 1599 of file Core.cpp.
References Name, and runSessionLocked().
Referenced by createJITDylib().
getMainJITDylib()
JITDylib & llvm::orc::ExecutionSession::getMainJITDylib ()
Get the "main" JITDylib, which is created automatically on construction of the ExecutionSession.
Definition at line 1595 of file Core.cpp.
References runSessionLocked().
getSymbolStringPool()
std::shared_ptr< SymbolStringPool > llvm::orc::ExecutionSession::getSymbolStringPool () const inline
Returns a shared_ptr to the SymbolStringPool for this ExecutionSession.
Definition at line 774 of file Core.h.
intern()
SymbolStringPtr llvm::orc::ExecutionSession::intern (StringRef SymName) inline
Add a symbol name to the SymbolStringPool and return a pointer to it.
Definition at line 771 of file Core.h.
Referenced by llvm::orc::JITCompileCallbackManager::getCompileCallback(), llvm::orc::getObjectSymbolFlags(), llvm::orc::JITSymbolResolverAdapter::getResponsibilitySet(), lookup(), and llvm::orc::JITSymbolResolverAdapter::lookup().
legacyFailQuery()
void llvm::orc::ExecutionSession::legacyFailQuery (AsynchronousSymbolQuery & Q, Error Err)
Definition at line 1620 of file Core.cpp.
References assert(), reportError(), and runSessionLocked().
Referenced by llvm::orc::JITSymbolResolverAdapter::lookup(), and llvm::orc::lookupWithLegacyFn().
legacyLookup()
Expected< SymbolMap > llvm::orc::ExecutionSession::legacyLookup (LegacyAsyncLookupFunction AsyncLookup, SymbolNameSet Names, SymbolState RequiredState, RegisterDependenciesFunction RegisterDependencies)
A legacy lookup function for JITSymbolResolverAdapter.
Do not use – this will be removed soon.
Definition at line 1635 of file Core.cpp.
References _, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), reportError(), runSessionLocked(), and llvm::Error::success().
lookup() [1/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (ArrayRef< JITDylib * > SearchOrder, StringRef Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol. The search will not find non-exported symbols.
Definition at line 1875 of file Core.cpp.
References intern(), lookup(), and Name.
lookup() [2/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (ArrayRef< JITDylib * > SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol. The search will not find non-exported symbols.
Definition at line 1862 of file Core.cpp.
References lookup(), Name, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::reserve(), and llvm::ArrayRef< T >::size().
lookup() [3/5]
Expected< SymbolMap > llvm::orc::ExecutionSession::lookup (const JITDylibSearchList & SearchOrder, const SymbolNameSet & Symbols, SymbolState RequiredState = SymbolState::Ready, RegisterDependenciesFunction RegisterDependencies = NoDependenciesToRegister)
Blocking version of lookup above.
Returns the resolved symbol map. If WaitUntilReady is true (the default), will not return until all requested symbols are ready (or an error occurs). If WaitUntilReady is false, will return as soon as all requested symbols are resolved, or an error occurs. If WaitUntilReady is false and an error occurs after resolution, the function will return a success value, but the error will be reported via reportErrors.
Definition at line 1794 of file Core.cpp.
References _, lookup(), and llvm::Error::success().
lookup() [4/5]
void llvm::orc::ExecutionSession::lookup (const JITDylibSearchList & SearchOrder, SymbolNameSet Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete, RegisterDependenciesFunction RegisterDependencies)
Search the given JITDylib list for the given symbols.
SearchOrder lists the JITDylibs to search. For each dylib, the associated boolean indicates whether the search should match against non-exported (hidden visibility) symbols in that dylib (true means match against non-exported symbols, false means do not match).
The NotifyComplete callback will be called once all requested symbols reach the required state.
If all symbols are found, the RegisterDependencies function will be called while the session lock is held. This gives clients a chance to register dependencies for on the queried symbols for any symbols they are materializing (if a MaterializationResponsibility instance is present, this can be implemented by calling MaterializationResponsibility::addDependencies). If there are no dependenant symbols for this query (e.g. it is being made by a top level client to get an address to call) then the value NoDependenciesToRegister can be used.
Definition at line 1702 of file Core.cpp.
References assert(), llvm::dbgs(), LLVM_DEBUG, llvm::Lock, runSessionLocked(), and llvm::Error::success().
Referenced by llvm::orc::LazyCallThroughManager::callThroughToSymbol(), llvm::orc::JITCompileCallbackManager::executeCompileCallback(), and lookup().
lookup() [5/5]
Expected< JITEvaluatedSymbol > llvm::orc::ExecutionSession::lookup (const JITDylibSearchList & SearchOrder, SymbolStringPtr Symbol)
Convenience version of blocking lookup.
Searches each of the JITDylibs in the search order in turn for the given symbol.
Definition at line 1848 of file Core.cpp.
References assert(), lookup(), Name, llvm::orc::NoDependenciesToRegister, and llvm::orc::Ready.
releaseVModule()
void llvm::orc::ExecutionSession::releaseVModule (VModuleKey Key) inline
Return a module key to the ExecutionSession so that it can be re-used.
This should only be done once all resources associated with the original key have been released.
Definition at line 806 of file Core.h.
Referenced by llvm::OrcCBindingsStack::removeModule().
reportError()
void llvm::orc::ExecutionSession::reportError (Error Err) inline
Report a error for this execution session.
Unhandled errors can be sent here to log them.
Definition at line 818 of file Core.h.
References ReportError().
Referenced by llvm::orc::LazyCallThroughManager::callThroughToSymbol(), llvm::orc::ObjectTransformLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::IRTransformLayer::emit(), llvm::orc::JITCompileCallbackManager::executeCompileCallback(), legacyFailQuery(), legacyLookup(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFailed(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized(), and llvm::orc::ObjectLinkingLayer::~ObjectLinkingLayer().
runSessionLocked()
template<typename Func > auto llvm::orc::ExecutionSession::runSessionLocked (Func && F) -> decltype(F()) inline
Run the given lambda with the session mutex locked.
Definition at line 777 of file Core.h.
References F, and llvm::Lock.
Referenced by allocateVModule(), createJITDylib(), llvm::orc::JITDylib::define(), dispatchMaterialization(), dump(), getJITDylibByName(), getMainJITDylib(), legacyFailQuery(), legacyLookup(), and lookup().
setDispatchMaterialization()
ExecutionSession & llvm::orc::ExecutionSession::setDispatchMaterialization (DispatchMaterializationFunction DispatchMaterialization) inline
Set the materialization dispatch function.
Definition at line 821 of file Core.h.
setErrorReporter()
ExecutionSession & llvm::orc::ExecutionSession::setErrorReporter (ErrorReporter ReportError) inline
Set the error reporter function.
Definition at line 810 of file Core.h.
References ReportError().
Friends And Related Function Documentation
JITDylib
friend class JITDylib friend
Definition at line 755 of file Core.h.
Referenced by createJITDylib(), and ExecutionSession().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp