LLVM: llvm::SwiftErrorValueTracking Class Reference
llvm::SwiftErrorValueTracking Class Reference
#include "llvm/CodeGen/SwiftErrorValueTracking.h"
Public Member Functions
void setFunction (MachineFunction &MF)
Initialize data structures for specified new function.
const Value * getFunctionArg () const
Get the (unique) function argument that was marked swifterror, or nullptr if this function has no swifterror args.
Register getOrCreateVReg (const MachineBasicBlock *, const Value *)
Get or create the swifterror value virtual register in VRegDefMap for this basic block.
void setCurrentVReg (const MachineBasicBlock *MBB, const Value *, Register)
Set the swifterror virtual register in the VRegDefMap for this basic block.
Register getOrCreateVRegDefAt (const Instruction *, const MachineBasicBlock *, const Value *)
Get or create the swifterror value virtual register for a def of a swifterror by an instruction.
Register getOrCreateVRegUseAt (const Instruction *, const MachineBasicBlock *, const Value *)
Get or create the swifterror value virtual register for a use of a swifterror by an instruction.
bool createEntriesInEntryBlock (DebugLoc DbgLoc)
Create initial definitions of swifterror values in the entry block of the current function.
void propagateVRegs ()
Propagate assigned swifterror vregs through a function, synthesizing PHI nodes when needed to maintain consistency.
void preassignVRegs (MachineBasicBlock *MBB, BasicBlock::const_iterator Begin, BasicBlock::const_iterator End)
Detailed Description
Definition at line 36 of file SwiftErrorValueTracking.h.
Member Function Documentation
createEntriesInEntryBlock()
bool SwiftErrorValueTracking::createEntriesInEntryBlock (DebugLoc DbgLoc)
Create initial definitions of swifterror values in the entry block of the current function.
Definition at line 114 of file SwiftErrorValueTracking.cpp.
References llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorBase::empty(), llvm::MCInstrInfo::get(), llvm::MachineFunction::getDataLayout(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), setCurrentVReg(), and llvm::TargetLowering::supportSwiftError().
Referenced by llvm::IRTranslator::runOnMachineFunction().
getFunctionArg()
const Value * llvm::SwiftErrorValueTracking::getFunctionArg () const inline
Get the (unique) function argument that was marked swifterror, or nullptr if this function has no swifterror args.
Definition at line 74 of file SwiftErrorValueTracking.h.
Referenced by llvm::IRTranslator::runOnMachineFunction().
getOrCreateVReg()
Register SwiftErrorValueTracking::getOrCreateVReg (const MachineBasicBlock * MBB, const Value * Val)
Get or create the swifterror value virtual register in VRegDefMap for this basic block.
Definition at line 25 of file SwiftErrorValueTracking.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineFunction::getDataLayout(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), and llvm::MachineFunction::getRegInfo().
Referenced by getOrCreateVRegUseAt(), and propagateVRegs().
getOrCreateVRegDefAt()
Register SwiftErrorValueTracking::getOrCreateVRegDefAt (const Instruction * I, const MachineBasicBlock * MBB, const Value * Val)
Get or create the swifterror value virtual register for a def of a swifterror by an instruction.
Definition at line 49 of file SwiftErrorValueTracking.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineFunction::getDataLayout(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), I, and setCurrentVReg().
Referenced by llvm::SelectionDAGBuilder::LowerCallTo(), and preassignVRegs().
getOrCreateVRegUseAt()
Register SwiftErrorValueTracking::getOrCreateVRegUseAt (const Instruction * I, const MachineBasicBlock * MBB, const Value * Val)
Get or create the swifterror value virtual register for a use of a swifterror by an instruction.
Definition at line 64 of file SwiftErrorValueTracking.cpp.
References getOrCreateVReg(), and I.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo(), and preassignVRegs().
preassignVRegs()
void SwiftErrorValueTracking::preassignVRegs (MachineBasicBlock * MBB, BasicBlock::const_iterator Begin, BasicBlock::const_iterator End)
Definition at line 258 of file SwiftErrorValueTracking.cpp.
References Arg, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::args(), assert(), llvm::SmallVectorBase::empty(), F, getOrCreateVRegDefAt(), getOrCreateVRegUseAt(), llvm::Value::isSwiftError(), SI, and llvm::TargetLowering::supportSwiftError().
propagateVRegs()
void SwiftErrorValueTracking::propagateVRegs ()
Propagate assigned swifterror vregs through a function, synthesizing PHI nodes when needed to maintain consistency.
Propagate swifterror values through the machine function CFG.
Definition at line 146 of file SwiftErrorValueTracking.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MCInstrInfo::get(), llvm::MachineFunction::getDataLayout(), llvm::TargetSubtargetInfo::getInstrInfo(), getOrCreateVReg(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SmallSet< T, N, C >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), second, setCurrentVReg(), llvm::SmallVectorBase::size(), and llvm::TargetLowering::supportSwiftError().
Referenced by llvm::IRTranslator::runOnMachineFunction().
setCurrentVReg()
void SwiftErrorValueTracking::setCurrentVReg (const MachineBasicBlock * MBB, const Value * Val, Register VReg)
Set the swifterror virtual register in the VRegDefMap for this basic block.
Definition at line 44 of file SwiftErrorValueTracking.cpp.
Referenced by createEntriesInEntryBlock(), getOrCreateVRegDefAt(), propagateVRegs(), and llvm::IRTranslator::runOnMachineFunction().
setFunction()
void SwiftErrorValueTracking::setFunction (MachineFunction & mf)
Initialize data structures for specified new function.
Set up SwiftErrorVals by going through the function.
If the function has swifterror argument, it will be the first entry.
Definition at line 78 of file SwiftErrorValueTracking.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::TargetLowering::supportSwiftError().
Referenced by llvm::IRTranslator::runOnMachineFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SwiftErrorValueTracking.h
lib/CodeGen/SwiftErrorValueTracking.cpp