LLVM: llvm::LPPassManager Class Reference
llvm::LPPassManager Class Reference
#include "llvm/Analysis/LoopPass.h"
Public Member Functions
LPPassManager ()
bool runOnFunction (Function &F) override
run - Execute all of the passes scheduled for execution.
void getAnalysisUsage (AnalysisUsage &Info) const override
Pass Manager itself does not invalidate any analysis info.
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
PMDataManager * getAsPMDataManager () override
Pass * getAsPass () override
void dumpPassStructure (unsigned Offset) override
Print passes managed by this manager.
LoopPass * getContainedPass (unsigned N)
PassManagerType getPassManagerType () const override
void addLoop (Loop &L)
void markLoopAsDeleted (Loop &L)
void cloneBasicBlockSimpleAnalysis (BasicBlock *From, BasicBlock *To, Loop *L)
SimpleAnalysis - Provides simple interface to update analysis info maintained by various passes.
void deleteSimpleAnalysisValue (Value *V, Loop *L)
deleteSimpleAnalysisValue - Invoke deleteAnalysisValue hook for all passes that implement simple analysis interface.
void deleteSimpleAnalysisLoop (Loop *L)
Invoke deleteAnalysisLoop hook for all passes that implement simple analysis interface.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Member Functions inherited from llvm::PMDataManager
PMDataManager ()
virtual ~PMDataManager ()
virtual Pass * getAsPass ()=0
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
Add pass P into the PassVector.
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
Add RequiredPass into list of lower level passes required by pass P.
virtual Pass * getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAndUsedAnalyses (SmallVectorImpl< Pass * > &UsedPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
Populate UsedPasses with analysis pass that are used or required by pass P and are available.
void initializeAnalysisImpl (Pass *P)
All Required analyses should be available to the pass as it runs! Here we fill in the AnalysisImpls member of the pass so that it can successfully use the getAnalysis() method to retrieve the implementations it needs.
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
Find the pass that implements Analysis AID.
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
void dumpUsedSet (const Pass *P) const
unsigned getNumContainedPasses () const
virtual PassManagerType getPassManagerType () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
unsigned initSizeRemarkInfo (Module &M, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount)
Set the initial size of the module if the user has specified that they want remarks for size.
void emitInstrCountChangedRemark (Pass *P, Module &M, int64_t Delta, unsigned CountBefore, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount, Function *F=nullptr)
Emit a remark signifying that the number of IR instructions in the module changed.
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Member Functions inherited from llvm::PMDataManager
bool isPassDebuggingExecutionsOrMore () const
isPassDebuggingExecutionsOrMore - Return true if -debug-pass=Executions or higher is specified.
Protected Attributes inherited from llvm::PMDataManager
PMTopLevelManager * TPM
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Detailed Description
Definition at line 96 of file LoopPass.h.
Constructor & Destructor Documentation
LPPassManager()
LPPassManager::LPPassManager () explicit
Definition at line 70 of file LoopPass.cpp.
Member Function Documentation
addLoop()
void LPPassManager::addLoop (Loop & L)
Definition at line 77 of file LoopPass.cpp.
References E, llvm::LoopBase< BlockT, LoopT >::getParentLoop(), and I.
Referenced by CloneLoop().
cloneBasicBlockSimpleAnalysis()
void LPPassManager::cloneBasicBlockSimpleAnalysis (BasicBlock * From, BasicBlock * To, Loop * L)
SimpleAnalysis - Provides simple interface to update analysis info maintained by various passes.
cloneBasicBlockSimpleAnalysis - Invoke cloneBasicBlockAnalysis hook for all loop passes.
Note, if required this interface can be extracted into a separate abstract class but it would require additional use of multiple inheritance in Pass class hierarchy, something we are trying to avoid. cloneBasicBlockSimpleAnalysis - Invoke cloneBasicBlockAnalysis hook for all passes that implement simple analysis interface.
Definition at line 97 of file LoopPass.cpp.
References llvm::LoopPass::cloneBasicBlockAnalysis(), From, getContainedPass(), and llvm::PMDataManager::getNumContainedPasses().
deleteSimpleAnalysisLoop()
void LPPassManager::deleteSimpleAnalysisLoop (Loop * L)
Invoke deleteAnalysisLoop hook for all passes that implement simple analysis interface.
Invoke deleteAnalysisLoop hook for all passes.
Definition at line 119 of file LoopPass.cpp.
References llvm::LoopPass::deleteAnalysisLoop(), getContainedPass(), and llvm::PMDataManager::getNumContainedPasses().
Referenced by runOnFunction().
deleteSimpleAnalysisValue()
void LPPassManager::deleteSimpleAnalysisValue (Value * V, Loop * L)
deleteSimpleAnalysisValue - Invoke deleteAnalysisValue hook for all passes that implement simple analysis interface.
deleteSimpleAnalysisValue - Invoke deleteAnalysisValue hook for all passes.
Definition at line 106 of file LoopPass.cpp.
References llvm::LoopPass::deleteAnalysisValue(), deleteSimpleAnalysisValue(), getContainedPass(), llvm::PMDataManager::getNumContainedPasses(), and I.
Referenced by deleteSimpleAnalysisValue(), and ReplaceUsesOfWith().
dumpPassStructure()
void LPPassManager::dumpPassStructure (unsigned Offset) override virtual
Print passes managed by this manager.
Reimplemented from llvm::Pass.
Definition at line 314 of file LoopPass.cpp.
References llvm::PMDataManager::dumpLastUses(), llvm::errs(), getContainedPass(), llvm::PMDataManager::getNumContainedPasses(), llvm::raw_ostream::indent(), and P.
getAnalysisUsage()
void LPPassManager::getAnalysisUsage (AnalysisUsage & Info) const override virtual
Pass Manager itself does not invalidate any analysis info.
Reimplemented from llvm::Pass.
Definition at line 135 of file LoopPass.cpp.
References Info.
getAsPass()
Pass * llvm::LPPassManager::getAsPass () inline override virtual
Implements llvm::PMDataManager.
Definition at line 112 of file LoopPass.h.
Referenced by llvm::LoopPass::assignPassManager().
getAsPMDataManager()
PMDataManager * llvm::LPPassManager::getAsPMDataManager () inline override virtual
Reimplemented from llvm::Pass.
Definition at line 111 of file LoopPass.h.
getContainedPass()
LoopPass * llvm::LPPassManager::getContainedPass (unsigned N) inline
Definition at line 117 of file LoopPass.h.
References assert(), N, and llvm::PMDataManager::PassVector.
Referenced by cloneBasicBlockSimpleAnalysis(), deleteSimpleAnalysisLoop(), deleteSimpleAnalysisValue(), dumpPassStructure(), and runOnFunction().
getPassManagerType()
PassManagerType llvm::LPPassManager::getPassManagerType () const inline override virtual
Reimplemented from llvm::PMDataManager.
Definition at line 123 of file LoopPass.h.
References llvm::PMT_LoopPassManager.
getPassName()
StringRef llvm::LPPassManager::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 109 of file LoopPass.h.
markLoopAsDeleted()
void LPPassManager::markLoopAsDeleted (Loop & L)
Definition at line 143 of file LoopPass.cpp.
References assert(), and llvm::LoopBase< BlockT, LoopT >::contains().
runOnFunction()
bool LPPassManager::runOnFunction (Function & F) override virtual
run - Execute all of the passes scheduled for execution.
Keep track of whether any of the passes modifies the module, and if so, return true.
Keep track of whether any of the passes modifies the function, and if so, return true.
Implements llvm::FunctionPass.
Definition at line 161 of file LoopPass.cpp.
References llvm::PMTopLevelManager::activeStack, addLoopIntoQueue(), assert(), deleteSimpleAnalysisLoop(), llvm::PMDataManager::dumpPassInfo(), llvm::PMDataManager::dumpPreservedSet(), llvm::PMDataManager::dumpRequiredSet(), llvm::PMDataManager::emitInstrCountChangedRemark(), llvm::EXECUTION_MSG, F, llvm::PMDataManager::freePass(), getContainedPass(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getName(), llvm::Value::getName(), llvm::PMDataManager::getNumContainedPasses(), llvm::getPassTimer(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::PMDataManager::initSizeRemarkInfo(), InstrCount, llvm::Loop::isRecursivelyLCSSAForm(), llvm::MODIFICATION_MSG, llvm::Pass::mustPreserveAnalysisID(), llvm::ON_LOOP_MSG, P, llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::PMDataManager::removeDeadPasses(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::reverse(), llvm::PMDataManager::TPM, llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::PMDataManager::verifyPreservedAnalysis(), and X.
Member Data Documentation
ID
char LPPassManager::ID = 0 static
Definition at line 98 of file LoopPass.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopPass.h
lib/Analysis/LoopPass.cpp