LLVM: llvm::pdb::PDBStringTable Class Reference
llvm::pdb::PDBStringTable Class Reference
#include "llvm/DebugInfo/PDB/Native/PDBStringTable.h"
Public Member Functions
Error reload (BinaryStreamReader &Reader)
uint32_t getByteSize () const
uint32_t getNameCount () const
uint32_t getHashVersion () const
uint32_t getSignature () const
Expected< StringRef > getStringForID (uint32_t ID) const
Expected< uint32_t > getIDForString (StringRef Str) const
FixedStreamArray< support::ulittle32_t > name_ids () const
const codeview::DebugStringTableSubsectionRef & getStringTable () const
Detailed Description
Definition at line 33 of file PDBStringTable.h.
Member Function Documentation
getByteSize()
uint32_t PDBStringTable::getByteSize () const
Definition at line 22 of file PDBStringTable.cpp.
References llvm::pdb::PDBStringTableHeader::ByteSize.
getHashVersion()
uint32_t PDBStringTable::getHashVersion () const
Definition at line 24 of file PDBStringTable.cpp.
References llvm::pdb::PDBStringTableHeader::HashVersion.
getIDForString()
Expected< uint32_t > PDBStringTable::getIDForString (StringRef Str) const
Definition at line 113 of file PDBStringTable.cpp.
References getStringForID(), llvm::pdb::hashStringV1(), llvm::pdb::hashStringV2(), llvm::pdb::PDBStringTableHeader::HashVersion, I, llvm::pdb::no_entry, and llvm::FixedStreamArray< T >::size().
getNameCount()
uint32_t PDBStringTable::getNameCount () const
Definition at line 23 of file PDBStringTable.cpp.
getSignature()
uint32_t PDBStringTable::getSignature () const
Definition at line 25 of file PDBStringTable.cpp.
References llvm::pdb::PDBStringTableHeader::Signature.
getStringForID()
Expected< StringRef > PDBStringTable::getStringForID (uint32_t ID) const
Definition at line 109 of file PDBStringTable.cpp.
References llvm::codeview::DebugStringTableSubsectionRef::getString().
Referenced by llvm::pdb::DbiStream::getECName(), getIDForString(), and llvm::pdb::InjectedSourceStream::reload().
getStringTable()
const codeview::DebugStringTableSubsectionRef & PDBStringTable::getStringTable () const
Definition at line 58 of file PDBStringTable.cpp.
name_ids()
FixedStreamArray< support::ulittle32_t > PDBStringTable::name_ids () const
Definition at line 138 of file PDBStringTable.cpp.
reload()
Error PDBStringTable::reload (BinaryStreamReader & Reader)
Definition at line 84 of file PDBStringTable.cpp.
References assert(), llvm::pdb::PDBStringTableHeader::ByteSize, llvm::BinaryStreamReader::bytesRemaining(), llvm::BinaryStreamReader::split(), and llvm::Error::success().
Referenced by llvm::pdb::DbiStream::reload().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PDBStringTable.h
lib/DebugInfo/PDB/Native/PDBStringTable.cpp