LLVM: llvm::FunctionCallee Class Reference
llvm::FunctionCallee Class Reference
A handy container for a FunctionType+Callee-pointer pair, which can be passed around as a single entity.
#include "llvm/IR/DerivedTypes.h"
Public Member Functions
template<typename T , typename U = decltype(&T::getFunctionType)>
FunctionCallee (T *Fn)
FunctionCallee (FunctionType *FnTy, Value *Callee)
FunctionCallee (std::nullptr_t)
FunctionCallee ()=default
FunctionType * getFunctionType ()
Value * getCallee ()
operator bool ()
Detailed Description
A handy container for a FunctionType+Callee-pointer pair, which can be passed around as a single entity.
This assists in replacing the use of PointerType::getElementType() to access the function's type, since that's slated for removal as part of the [opaque pointer types] project.
Definition at line 165 of file DerivedTypes.h.
Constructor & Destructor Documentation
FunctionCallee() [1/4]
template<typename T , typename U = decltype(&T::getFunctionType)> llvm::FunctionCallee::FunctionCallee (T * Fn) inline
Definition at line 170 of file DerivedTypes.h.
FunctionCallee() [2/4]
llvm::FunctionCallee::FunctionCallee (FunctionType * FnTy, Value * Callee) inline
Definition at line 173 of file DerivedTypes.h.
References assert(), and Callee.
FunctionCallee() [3/4]
llvm::FunctionCallee::FunctionCallee (std::nullptr_t) inline
Definition at line 178 of file DerivedTypes.h.
FunctionCallee() [4/4]
llvm::FunctionCallee::FunctionCallee () default
Member Function Documentation
getCallee()
Value * llvm::FunctionCallee::getCallee () inline
Definition at line 184 of file DerivedTypes.h.
Referenced by llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateCallBr(), createFree(), llvm::IRBuilder< T, Inserter >::CreateInvoke(), createMalloc(), llvm::emitBinaryFloatFnCall(), llvm::emitCalloc(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitUnaryFloatFnCallHelper(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), lowerObjCCall(), llvm::EscapeEnumerator::Next(), and llvm::CallBase::setCalledFunction().
getFunctionType()
FunctionType * llvm::FunctionCallee::getFunctionType () inline
Definition at line 182 of file DerivedTypes.h.
Referenced by llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateCallBr(), llvm::IRBuilder< T, Inserter >::CreateInvoke(), llvm::Evaluator::EvaluateBlock(), getAllocationDataForFunction(), llvm::isLegalToPromote(), llvm::promoteCall(), and llvm::CallBase::setCalledFunction().
operator bool()
llvm::FunctionCallee::operator bool () inline explicit
Definition at line 186 of file DerivedTypes.h.
The documentation for this class was generated from the following file:
include/llvm/IR/DerivedTypes.h