LLVM: llvm::MCFillFragment Class Reference
llvm::MCFillFragment Class Reference
#include "llvm/MC/MCFragment.h"
Public Member Functions
MCFillFragment (uint64_t Value, uint8_t VSize, const MCExpr &NumValues, SMLoc Loc, MCSection *Sec=nullptr)
uint64_t getValue () const
uint8_t getValueSize () const
const MCExpr & getNumValues () const
SMLoc getLoc () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
bool isDummy () const
Return true if given frgment has FT_Dummy type.
void dump () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB , FT_Padding , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_Dummy
}
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
~MCFragment ()
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions
Detailed Description
Definition at line 427 of file MCFragment.h.
Constructor & Destructor Documentation
MCFillFragment()
llvm::MCFillFragment::MCFillFragment (uint64_t Value, uint8_t VSize, const MCExpr & NumValues, SMLoc Loc, MCSection * Sec = nullptr) inline
Definition at line 438 of file MCFragment.h.
Member Function Documentation
classof()
static bool llvm::MCFillFragment::classof (const MCFragment * F) inline static
Definition at line 449 of file MCFragment.h.
References F, and llvm::MCFragment::FT_Fill.
getLoc()
SMLoc llvm::MCFillFragment::getLoc () const inline
Definition at line 447 of file MCFragment.h.
getNumValues()
const MCExpr & llvm::MCFillFragment::getNumValues () const inline
Definition at line 445 of file MCFragment.h.
Referenced by llvm::MCFragment::dump().
getValue()
uint64_t llvm::MCFillFragment::getValue () const inline
Definition at line 443 of file MCFragment.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
getValueSize()
uint8_t llvm::MCFillFragment::getValueSize () const inline
Definition at line 444 of file MCFragment.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h