LLVM: llvm::WebAssemblyMCInstLower Class Reference
llvm::WebAssemblyMCInstLower Class Reference
This class is used to lower an MachineInstr into an MCInst.
#include "Target/WebAssembly/WebAssemblyMCInstLower.h"
Public Member Functions
WebAssemblyMCInstLower (MCContext &ctx, WebAssemblyAsmPrinter &printer)
void lower (const MachineInstr *MI, MCInst &OutMI) const
Detailed Description
This class is used to lower an MachineInstr into an MCInst.
Definition at line 29 of file WebAssemblyMCInstLower.h.
Constructor & Destructor Documentation
WebAssemblyMCInstLower()
llvm::WebAssemblyMCInstLower::WebAssemblyMCInstLower (MCContext & ctx, WebAssemblyAsmPrinter & printer) inline
Definition at line 38 of file WebAssemblyMCInstLower.h.
References Printer.
Member Function Documentation
lower()
void WebAssemblyMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 181 of file WebAssemblyMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::WebAssemblyAsmPrinter::addSignature(), assert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::LiveRangeEdit::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createFPImm(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::AsmPrinter::createTempSymbol(), E, llvm::errs(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::Value::getType(), getType(), llvm::ConstantFP::getValueAPF(), llvm::WebAssemblyFunctionInfo::getWAReg(), I, Info, llvm::WebAssembly::isCallIndirect(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm_unreachable, MI, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Register, MRI, llvm::MCInstrDesc::NumOperands, llvm::WebAssembly::OPERAND_TYPEINDEX, llvm::MCInstrDesc::OpInfo, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::Pass::print(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), removeRegisterOperands(), llvm::MCInst::setOpcode(), llvm::MCSymbolRefExpr::VK_WASM_TYPEINDEX, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, and WasmKeepRegisters.
Referenced by llvm::WebAssemblyAsmPrinter::EmitInstruction().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyMCInstLower.h
lib/Target/WebAssembly/WebAssemblyMCInstLower.cpp