LLVM: llvm::MachO::InterfaceFile Class Reference
llvm::MachO::InterfaceFile Class Reference
Defines the interface file.
#include "llvm/TextAPI/MachO/InterfaceFile.h"
Classes
struct const_export_iterator
struct const_symbol_iterator
struct const_undefined_iterator
Public Types
using SymbolMapType = DenseMap< SymbolsMapKey, Symbol * >
using const_symbol_range = iterator_range< const_symbol_iterator >
using const_export_range = llvm::iterator_range< const_export_iterator >
using const_undefined_range = llvm::iterator_range< const_undefined_iterator >
Public Member Functions
void setPath (StringRef Path_)
Set the path from which this file was generated (if applicable).
StringRef getPath () const
Get the path from which this file was generated (if applicable).
void setFileType (FileType Kind)
Set the file type.
FileType getFileType () const
Get the file type.
void setPlatform (PlatformKind Platform_)
Set the platform.
PlatformKind getPlatform () const
Get the platform.
void setArchitectures (ArchitectureSet Architectures_)
Specify the set of supported architectures by this file.
void addArchitectures (ArchitectureSet Architectures_)
Add the set of supported architectures by this file.
void addArch (Architecture Arch)
Add supported architecture by this file..
ArchitectureSet getArchitectures () const
Get the set of supported architectures.
void setInstallName (StringRef InstallName_)
Set the install name of the library.
StringRef getInstallName () const
Get the install name of the library.
void setCurrentVersion (PackedVersion Version)
Set the current version of the library.
PackedVersion getCurrentVersion () const
Get the current version of the library.
void setCompatibilityVersion (PackedVersion Version)
Set the compatibility version of the library.
PackedVersion getCompatibilityVersion () const
Get the compatibility version of the library.
void setSwiftABIVersion (uint8_t Version)
Set the Swift ABI version of the library.
uint8_t getSwiftABIVersion () const
Get the Swift ABI version of the library.
void setTwoLevelNamespace (bool V=true)
Specify if the library uses two-level namespace (or flat namespace).
bool isTwoLevelNamespace () const
Check if the library uses two-level namespace.
void setApplicationExtensionSafe (bool V=true)
Specify if the library is application extension safe (or not).
bool isApplicationExtensionSafe () const
Check if the library is application extension safe.
void setObjCConstraint (ObjCConstraintType Constraint)
Set the Objective-C constraint.
ObjCConstraintType getObjCConstraint () const
Get the Objective-C constraint.
void setInstallAPI (bool V=true)
Specify if this file was generated during InstallAPI (or not).
bool isInstallAPI () const
Check if this file was generated during InstallAPI.
void setParentUmbrella (StringRef Parent)
Set the parent umbrella framework.
StringRef getParentUmbrella () const
Get the parent umbrella framework.
void addAllowableClient (StringRef Name, ArchitectureSet Architectures)
Add an allowable client.
const std::vector< InterfaceFileRef > & allowableClients () const
Get the list of allowable clients.
void addReexportedLibrary (StringRef InstallName, ArchitectureSet Architectures)
Add a re-exported library.
const std::vector< InterfaceFileRef > & reexportedLibraries () const
Get the list of re-exported libraries.
void addUUID (Architecture Arch, StringRef UUID)
Add an architecture/UUID pair.
void addUUID (Architecture Arch, uint8_t UUID[16])
Add an architecture/UUID pair.
const std::vector< std::pair< Architecture, std::string > > & uuids () const
Get the list of architecture/UUID pairs.
void addSymbol (SymbolKind Kind, StringRef Name, ArchitectureSet Architectures, SymbolFlags Flags=SymbolFlags::None)
Add a symbol to the symbols list or extend an existing one.
const_symbol_range symbols () const
const_export_range exports () const
const_undefined_range undefineds () const
Detailed Description
Defines the interface file.
Definition at line 148 of file InterfaceFile.h.
Member Typedef Documentation
const_export_range
using llvm::MachO::InterfaceFile::const_export_range = llvm::iterator_range<const_export_iterator>
Definition at line 357 of file InterfaceFile.h.
const_symbol_range
using llvm::MachO::InterfaceFile::const_symbol_range = iterator_range<const_symbol_iterator>
Definition at line 323 of file InterfaceFile.h.
const_undefined_range
using llvm::MachO::InterfaceFile::const_undefined_range = llvm::iterator_range<const_undefined_iterator>
Definition at line 391 of file InterfaceFile.h.
SymbolMapType
using llvm::MachO::InterfaceFile::SymbolMapType = DenseMap<SymbolsMapKey, Symbol *>
Definition at line 308 of file InterfaceFile.h.
Member Function Documentation
addAllowableClient()
void llvm::MachO::InterfaceFile::addAllowableClient (StringRef Name, ArchitectureSet Architectures)
Add an allowable client.
Mach-O Dynamic libraries have the concept of allowable clients that are checked during static link time. The name of the application or library that is being generated needs to match one of the allowable clients or the linker refuses to link this library.
Parameters
Name The name of the client that is allowed to link this library.
Architectures The set of architecture for which this applies.
Definition at line 32 of file InterfaceFile.cpp.
References llvm::MachO::detail::addEntry(), and Name.
addArch()
void llvm::MachO::InterfaceFile::addArch (Architecture Arch) inline
Add supported architecture by this file..
Definition at line 190 of file InterfaceFile.h.
References llvm::MachO::ArchitectureSet::set().
addArchitectures()
void llvm::MachO::InterfaceFile::addArchitectures (ArchitectureSet Architectures_) inline
Add the set of supported architectures by this file.
Definition at line 185 of file InterfaceFile.h.
addReexportedLibrary()
void llvm::MachO::InterfaceFile::addReexportedLibrary (StringRef InstallName, ArchitectureSet Architectures)
Add a re-exported library.
Parameters
InstallName The name of the library to re-export.
Architectures The set of architecture for which this applies.
Definition at line 38 of file InterfaceFile.cpp.
References llvm::MachO::detail::addEntry().
addSymbol()
void llvm::MachO::InterfaceFile::addSymbol (SymbolKind Kind, StringRef Name, ArchitectureSet Architectures, SymbolFlags Flags = SymbolFlags::None)
Add a symbol to the symbols list or extend an existing one.
Definition at line 70 of file InterfaceFile.cpp.
References Name, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
addUUID() [1/2]
void llvm::MachO::InterfaceFile::addUUID (Architecture Arch, StringRef UUID)
Add an architecture/UUID pair.
Parameters
Arch The architecture for which this applies.
UUID The UUID of the library for the specified architecture.
Definition at line 44 of file InterfaceFile.cpp.
References I, and llvm::partition_point().
Referenced by addUUID().
addUUID() [2/2]
void llvm::MachO::InterfaceFile::addUUID (Architecture Arch, uint8_t UUID[16])
Add an architecture/UUID pair.
Parameters
Arch The architecture for which this applies.
UUID The UUID of the library for the specified architecture.
Definition at line 59 of file InterfaceFile.cpp.
References addUUID().
allowableClients()
const std::vector< InterfaceFileRef > & llvm::MachO::InterfaceFile::allowableClients () const inline
Get the list of allowable clients.
Returns
Returns a list of allowable clients.
Definition at line 267 of file InterfaceFile.h.
exports()
const_export_range llvm::MachO::InterfaceFile::exports () const inline
Definition at line 396 of file InterfaceFile.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
getArchitectures()
ArchitectureSet llvm::MachO::InterfaceFile::getArchitectures () const inline
Get the set of supported architectures.
Definition at line 193 of file InterfaceFile.h.
getCompatibilityVersion()
PackedVersion llvm::MachO::InterfaceFile::getCompatibilityVersion () const inline
Get the compatibility version of the library.
Definition at line 213 of file InterfaceFile.h.
getCurrentVersion()
PackedVersion llvm::MachO::InterfaceFile::getCurrentVersion () const inline
Get the current version of the library.
Definition at line 205 of file InterfaceFile.h.
getFileType()
FileType llvm::MachO::InterfaceFile::getFileType () const inline
Get the file type.
Returns
The file type.
Definition at line 171 of file InterfaceFile.h.
getInstallName()
StringRef llvm::MachO::InterfaceFile::getInstallName () const inline
Get the install name of the library.
Definition at line 199 of file InterfaceFile.h.
getObjCConstraint()
ObjCConstraintType llvm::MachO::InterfaceFile::getObjCConstraint () const inline
Get the Objective-C constraint.
Definition at line 239 of file InterfaceFile.h.
getParentUmbrella()
StringRef llvm::MachO::InterfaceFile::getParentUmbrella () const inline
Get the parent umbrella framework.
Definition at line 251 of file InterfaceFile.h.
getPath()
StringRef llvm::MachO::InterfaceFile::getPath () const inline
Get the path from which this file was generated (if applicable).
Returns
The path to the source file or empty.
Definition at line 158 of file InterfaceFile.h.
getPlatform()
PlatformKind llvm::MachO::InterfaceFile::getPlatform () const inline
Get the platform.
Definition at line 177 of file InterfaceFile.h.
getSwiftABIVersion()
uint8_t llvm::MachO::InterfaceFile::getSwiftABIVersion () const inline
Get the Swift ABI version of the library.
Definition at line 219 of file InterfaceFile.h.
isApplicationExtensionSafe()
bool llvm::MachO::InterfaceFile::isApplicationExtensionSafe () const inline
Check if the library is application extension safe.
Definition at line 231 of file InterfaceFile.h.
isInstallAPI()
bool llvm::MachO::InterfaceFile::isInstallAPI () const inline
Check if this file was generated during InstallAPI.
Definition at line 245 of file InterfaceFile.h.
isTwoLevelNamespace()
bool llvm::MachO::InterfaceFile::isTwoLevelNamespace () const inline
Check if the library uses two-level namespace.
Definition at line 225 of file InterfaceFile.h.
reexportedLibraries()
const std::vector< InterfaceFileRef > & llvm::MachO::InterfaceFile::reexportedLibraries () const inline
Get the list of re-exported libraries.
Returns
Returns a list of re-exported libraries.
Definition at line 281 of file InterfaceFile.h.
setApplicationExtensionSafe()
void llvm::MachO::InterfaceFile::setApplicationExtensionSafe (bool V = true) inline
Specify if the library is application extension safe (or not).
Definition at line 228 of file InterfaceFile.h.
setArchitectures()
void llvm::MachO::InterfaceFile::setArchitectures (ArchitectureSet Architectures_) inline
Specify the set of supported architectures by this file.
Definition at line 180 of file InterfaceFile.h.
setCompatibilityVersion()
void llvm::MachO::InterfaceFile::setCompatibilityVersion (PackedVersion Version) inline
Set the compatibility version of the library.
Definition at line 208 of file InterfaceFile.h.
setCurrentVersion()
void llvm::MachO::InterfaceFile::setCurrentVersion (PackedVersion Version) inline
Set the current version of the library.
Definition at line 202 of file InterfaceFile.h.
setFileType()
void llvm::MachO::InterfaceFile::setFileType (FileType Kind) inline
Set the file type.
This is used by the YAML writer to identify the specification it should use for writing the file.
Parameters
Kind The file type.
Definition at line 166 of file InterfaceFile.h.
setInstallAPI()
void llvm::MachO::InterfaceFile::setInstallAPI (bool V = true) inline
Specify if this file was generated during InstallAPI (or not).
Definition at line 242 of file InterfaceFile.h.
setInstallName()
void llvm::MachO::InterfaceFile::setInstallName (StringRef InstallName_) inline
Set the install name of the library.
Definition at line 196 of file InterfaceFile.h.
setObjCConstraint()
void llvm::MachO::InterfaceFile::setObjCConstraint (ObjCConstraintType Constraint) inline
Set the Objective-C constraint.
Definition at line 234 of file InterfaceFile.h.
setParentUmbrella()
void llvm::MachO::InterfaceFile::setParentUmbrella (StringRef Parent) inline
Set the parent umbrella framework.
Definition at line 248 of file InterfaceFile.h.
setPath()
void llvm::MachO::InterfaceFile::setPath (StringRef Path_) inline
Set the path from which this file was generated (if applicable).
Parameters
Path_ The path to the source file.
Definition at line 153 of file InterfaceFile.h.
setPlatform()
void llvm::MachO::InterfaceFile::setPlatform (PlatformKind Platform_) inline
Set the platform.
Definition at line 174 of file InterfaceFile.h.
setSwiftABIVersion()
void llvm::MachO::InterfaceFile::setSwiftABIVersion (uint8_t Version) inline
Set the Swift ABI version of the library.
Definition at line 216 of file InterfaceFile.h.
setTwoLevelNamespace()
void llvm::MachO::InterfaceFile::setTwoLevelNamespace (bool V = true) inline
Specify if the library uses two-level namespace (or flat namespace).
Definition at line 222 of file InterfaceFile.h.
symbols()
const_symbol_range llvm::MachO::InterfaceFile::symbols () const inline
Definition at line 393 of file InterfaceFile.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
undefineds()
const_undefined_range llvm::MachO::InterfaceFile::undefineds () const inline
Definition at line 399 of file InterfaceFile.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
uuids()
const std::vector< std::pair< Architecture, std::string > > & llvm::MachO::InterfaceFile::uuids () const inline
Get the list of architecture/UUID pairs.
Returns
Returns a list of architecture/UUID pairs.
Definition at line 300 of file InterfaceFile.h.
The documentation for this class was generated from the following files:
include/llvm/TextAPI/MachO/InterfaceFile.h
lib/TextAPI/MachO/InterfaceFile.cpp