LLVM: llvm::DWARFDebugNames::Entry Class Reference
llvm::DWARFDebugNames::Entry Class Reference final
DWARF v5-specific implementation of an Accelerator Entry.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
Optional< uint64_t > getCUOffset () const override
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or None if the Compilation Unit offset is not recorded in this Accelerator Entry.
Optional< dwarf::Tag > getTag () const override
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or None if the Tag is not recorded in this Accelerator Entry.
Optional< uint64_t > getCUIndex () const
Returns the Index into the Compilation Unit list of the owning Name Index or None if this Accelerator Entry does not have an associated Compilation Unit.
dwarf::Tag tag () const
.debug_names-specific getter, which always succeeds (DWARF v5 index entries always have a tag).
Optional< uint64_t > getDIEUnitOffset () const
Returns the Offset of the DIE within the containing CU or TU.
const Abbrev & getAbbrev () const
Return the Abbreviation that can be used to interpret the raw values of this Accelerator Entry.
Optional< DWARFFormValue > lookup (dwarf::Index Index) const
Returns the value of the Index Attribute in this Accelerator Entry, if the Entry contains such Attribute.
void dump (ScopedPrinter &W) const
Public Member Functions inherited from llvm::DWARFAcceleratorTable::Entry
virtual Optional< uint64_t > getCUOffset () const =0
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or None if the Compilation Unit offset is not recorded in this Accelerator Entry.
virtual Optional< dwarf::Tag > getTag () const =0
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or None if the Tag is not recorded in this Accelerator Entry.
ArrayRef< DWARFFormValue > getValues () const
Returns the raw values of fields in the Accelerator Entry.
Friends
class NameIndex
class ValueIterator
Additional Inherited Members
Protected Member Functions inherited from llvm::DWARFAcceleratorTable::Entry
Entry ()=default
Entry (const Entry &)=default
Entry (Entry &&)=default
Entry & operator= (const Entry &)=default
Entry & operator= (Entry &&)=default
~Entry ()=default
Protected Attributes inherited from llvm::DWARFAcceleratorTable::Entry
SmallVector< DWARFFormValue, 3 > Values
Detailed Description
DWARF v5-specific implementation of an Accelerator Entry.
Definition at line 280 of file DWARFAcceleratorTable.h.
Member Function Documentation
dump()
void DWARFDebugNames::Entry::dump (ScopedPrinter & W) const
Definition at line 564 of file DWARFAcceleratorTable.cpp.
References assert(), llvm::DWARFDebugNames::Abbrev::Attributes, llvm::DWARFDebugNames::Abbrev::Code, llvm::formatv(), llvm::ScopedPrinter::getOStream(), llvm::ScopedPrinter::printHex(), llvm::ScopedPrinter::startLine(), and llvm::DWARFDebugNames::Abbrev::Tag.
getAbbrev()
const Abbrev & llvm::DWARFDebugNames::Entry::getAbbrev () const inline
Return the Abbreviation that can be used to interpret the raw values of this Accelerator Entry.
Definition at line 309 of file DWARFAcceleratorTable.h.
getCUIndex()
Optional< uint64_t > DWARFDebugNames::Entry::getCUIndex () const
Returns the Index into the Compilation Unit list of the owning Name Index or None if this Accelerator Entry does not have an associated Compilation Unit.
It is up to the user to verify that the returned Index is valid in the owning NameIndex (or use getCUOffset(), which will handle that check itself). Note that entries in NameIndexes which index just a single Compilation Unit are implicitly associated with that unit, so this function will return 0 even without an explicit DW_IDX_compile_unit attribute.
Definition at line 547 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFDebugNames::NameIndex::getCUCount(), and llvm::None.
getCUOffset()
Optional< uint64_t > DWARFDebugNames::Entry::getCUOffset () const override virtual
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or None if the Compilation Unit offset is not recorded in this Accelerator Entry.
Implements llvm::DWARFAcceleratorTable::Entry.
Definition at line 557 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFDebugNames::NameIndex::getCUCount(), llvm::DWARFDebugNames::NameIndex::getCUOffset(), and llvm::None.
getDIEUnitOffset()
Optional< uint64_t > DWARFDebugNames::Entry::getDIEUnitOffset () const
Returns the Offset of the DIE within the containing CU or TU.
Definition at line 541 of file DWARFAcceleratorTable.cpp.
References llvm::None.
getTag()
Optional< dwarf::Tag > llvm::DWARFDebugNames::Entry::getTag () const inline override virtual
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or None if the Tag is not recorded in this Accelerator Entry.
Implements llvm::DWARFAcceleratorTable::Entry.
Definition at line 288 of file DWARFAcceleratorTable.h.
References tag().
lookup()
Optional< DWARFFormValue > DWARFDebugNames::Entry::lookup (dwarf::Index Index) const
Returns the value of the Index Attribute in this Accelerator Entry, if the Entry contains such Attribute.
Definition at line 532 of file DWARFAcceleratorTable.cpp.
References assert(), llvm::DWARFDebugNames::Abbrev::Attributes, and llvm::None.
tag()
dwarf::Tag llvm::DWARFDebugNames::Entry::tag () const inline
.debug_names-specific getter, which always succeeds (DWARF v5 index entries always have a tag).
Definition at line 302 of file DWARFAcceleratorTable.h.
References llvm::DWARFDebugNames::Abbrev::Tag.
Referenced by getTag().
Friends And Related Function Documentation
NameIndex
friend class NameIndex friend
Definition at line 317 of file DWARFAcceleratorTable.h.
ValueIterator
friend class ValueIterator friend
Definition at line 318 of file DWARFAcceleratorTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp