LLVM: llvm::SSAUpdaterTraits< MachineSSAUpdater > Class Reference
llvm::SSAUpdaterTraits< MachineSSAUpdater > Class Reference
Classes
class PHI_iterator
Iterator for PHI operands.
Public Types
using BlkT = MachineBasicBlock
using ValT = unsigned
using PhiT = MachineInstr
using BlkSucc_iterator = MachineBasicBlock::succ_iterator
Static Public Member Functions
static BlkSucc_iterator BlkSucc_begin (BlkT *BB)
static BlkSucc_iterator BlkSucc_end (BlkT *BB)
static PHI_iterator PHI_begin (PhiT *PHI)
static PHI_iterator PHI_end (PhiT *PHI)
static void FindPredecessorBlocks (MachineBasicBlock *BB, SmallVectorImpl< MachineBasicBlock * > *Preds)
FindPredecessorBlocks - Put the predecessors of BB into the Preds vector.
static unsigned GetUndefVal (MachineBasicBlock *BB, MachineSSAUpdater *Updater)
GetUndefVal - Create an IMPLICIT_DEF instruction with a new register.
static unsigned CreateEmptyPHI (MachineBasicBlock *BB, unsigned NumPreds, MachineSSAUpdater *Updater)
CreateEmptyPHI - Create a PHI instruction that defines a new register.
static void AddPHIOperand (MachineInstr *PHI, unsigned Val, MachineBasicBlock *Pred)
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
static MachineInstr * InstrIsPHI (MachineInstr *I)
InstrIsPHI - Check if an instruction is a PHI.
static MachineInstr * ValueIsPHI (unsigned Val, MachineSSAUpdater *Updater)
ValueIsPHI - Check if the instruction that defines the specified register is a PHI instruction.
static MachineInstr * ValueIsNewPHI (unsigned Val, MachineSSAUpdater *Updater)
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
static unsigned GetPHIValue (MachineInstr *PHI)
GetPHIValue - For the specified PHI instruction, return the register that it defines.
Detailed Description
Definition at line 241 of file MachineSSAUpdater.cpp.
Member Typedef Documentation
BlkSucc_iterator
using llvm::SSAUpdaterTraits< MachineSSAUpdater >::BlkSucc_iterator = MachineBasicBlock::succ_iterator
Definition at line 246 of file MachineSSAUpdater.cpp.
BlkT
using llvm::SSAUpdaterTraits< MachineSSAUpdater >::BlkT = MachineBasicBlock
Definition at line 243 of file MachineSSAUpdater.cpp.
PhiT
using llvm::SSAUpdaterTraits< MachineSSAUpdater >::PhiT = MachineInstr
Definition at line 245 of file MachineSSAUpdater.cpp.
ValT
using llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValT = unsigned
Definition at line 244 of file MachineSSAUpdater.cpp.
Member Function Documentation
AddPHIOperand()
static void llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand (MachineInstr * PHI, unsigned Val, MachineBasicBlock * Pred) inline static
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
Definition at line 314 of file MachineSSAUpdater.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), and llvm::MachineBasicBlock::getParent().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
BlkSucc_begin()
static BlkSucc_iterator llvm::SSAUpdaterTraits< MachineSSAUpdater >::BlkSucc_begin (BlkT * BB) inline static
Definition at line 248 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::succ_begin().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
BlkSucc_end()
static BlkSucc_iterator llvm::SSAUpdaterTraits< MachineSSAUpdater >::BlkSucc_end (BlkT * BB) inline static
Definition at line 249 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::succ_end().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
CreateEmptyPHI()
static unsigned llvm::SSAUpdaterTraits< MachineSSAUpdater >::CreateEmptyPHI (MachineBasicBlock * BB, unsigned NumPreds, MachineSSAUpdater * Updater) inline static
CreateEmptyPHI - Create a PHI instruction that defines a new register.
Add it into the specified block and return the register.
Definition at line 303 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and InsertNewDef().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
FindPredecessorBlocks()
static void llvm::SSAUpdaterTraits< MachineSSAUpdater >::FindPredecessorBlocks (MachineBasicBlock * BB, SmallVectorImpl< MachineBasicBlock * > * Preds) inline static
FindPredecessorBlocks - Put the predecessors of BB into the Preds vector.
Definition at line 282 of file MachineSSAUpdater.cpp.
References E, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList().
GetPHIValue()
static unsigned llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetPHIValue (MachineInstr * PHI) inline static
GetPHIValue - For the specified PHI instruction, return the register that it defines.
Definition at line 343 of file MachineSSAUpdater.cpp.
References llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs().
GetUndefVal()
static unsigned llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetUndefVal (MachineBasicBlock * BB, MachineSSAUpdater * Updater) inline static
GetUndefVal - Create an IMPLICIT_DEF instruction with a new register.
Add it into the specified block and return the register.
Definition at line 291 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and InsertNewDef().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), and llvm::SSAUpdaterImpl< UpdaterT >::GetValue().
InstrIsPHI()
static MachineInstr * llvm::SSAUpdaterTraits< MachineSSAUpdater >::InstrIsPHI (MachineInstr * I) inline static
InstrIsPHI - Check if an instruction is a PHI.
Definition at line 320 of file MachineSSAUpdater.cpp.
References I.
PHI_begin()
static PHI_iterator llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_begin (PhiT * PHI) inline static
Definition at line 274 of file MachineSSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
PHI_end()
static PHI_iterator llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_end (PhiT * PHI) inline static
Definition at line 276 of file MachineSSAUpdater.cpp.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
ValueIsNewPHI()
static MachineInstr * llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValueIsNewPHI (unsigned Val, MachineSSAUpdater * Updater) inline static
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
Definition at line 334 of file MachineSSAUpdater.cpp.
References llvm::MachineInstr::getNumOperands().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals().
ValueIsPHI()
static MachineInstr * llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValueIsPHI (unsigned Val, MachineSSAUpdater * Updater) inline static
ValueIsPHI - Check if the instruction that defines the specified register is a PHI instruction.
Definition at line 328 of file MachineSSAUpdater.cpp.
References llvm::MachineRegisterInfo::getVRegDef().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineSSAUpdater.cpp