LLVM: llvm::unique_lock< MutexT > Class Template Reference
llvm::unique_lock< MutexT > Class Template Reference
A pared-down imitation of std::unique_lock from C++11.
#include "llvm/Support/UniqueLock.h"
Public Member Functions
unique_lock ()=default
unique_lock (MutexT &m)
unique_lock (const unique_lock &)=delete
unique_lock & operator= (const unique_lock &)=delete
void operator= (unique_lock &&o)
~unique_lock ()
void lock ()
void unlock ()
bool owns_lock ()
Detailed Description
template<typename MutexT>
class llvm::unique_lock< MutexT >
A pared-down imitation of std::unique_lock from C++11.
Contrary to the name, it's really more of a wrapper for a lock. It may or may not have an associated mutex, which is guaranteed to be locked upon creation and unlocked after destruction. unique_lock can also unlock the mutex and re-lock it freely during its lifetime. Guard a section of code with a mutex.
Definition at line 28 of file UniqueLock.h.
Constructor & Destructor Documentation
unique_lock() [1/3]
template<typename MutexT > llvm::unique_lock< MutexT >::unique_lock () default
unique_lock() [2/3]
template<typename MutexT > llvm::unique_lock< MutexT >::unique_lock (MutexT & m) inline explicit
Definition at line 34 of file UniqueLock.h.
unique_lock() [3/3]
template<typename MutexT > llvm::unique_lock< MutexT >::unique_lock (const unique_lock< MutexT > &) delete
~unique_lock()
template<typename MutexT > llvm::unique_lock< MutexT >::~unique_lock () inline
Definition at line 47 of file UniqueLock.h.
References llvm::unique_lock< MutexT >::owns_lock().
Member Function Documentation
lock()
template<typename MutexT > void llvm::unique_lock< MutexT >::lock () inline
Definition at line 49 of file UniqueLock.h.
References assert().
operator=() [1/2]
template<typename MutexT > unique_lock & llvm::unique_lock< MutexT >::operator= (const unique_lock< MutexT > &) delete
operator=() [2/2]
template<typename MutexT > void llvm::unique_lock< MutexT >::operator= (unique_lock< MutexT > && o) inline
Definition at line 38 of file UniqueLock.h.
References llvm::unique_lock< MutexT >::owns_lock().
owns_lock()
template<typename MutexT > bool llvm::unique_lock< MutexT >::owns_lock () inline
Definition at line 63 of file UniqueLock.h.
Referenced by llvm::unique_lock< MutexT >::operator=(), and llvm::unique_lock< MutexT >::~unique_lock().
unlock()
template<typename MutexT > void llvm::unique_lock< MutexT >::unlock () inline
Definition at line 56 of file UniqueLock.h.
References assert().
Referenced by llvm::Interpreter::callExternalFunction().
The documentation for this class was generated from the following file:
include/llvm/Support/UniqueLock.h