LLVM: llvm::CoroIdInst Class Reference
llvm::CoroIdInst Class Reference
This represents the llvm.coro.alloc instruction.
#include "Transforms/Coroutines/CoroInstr.h"
Classes
struct Info
Public Member Functions
CoroAllocInst * getCoroAlloc ()
IntrinsicInst * getCoroBegin ()
AllocaInst * getPromise () const
void clearPromise ()
Info getInfo () const
Constant * getRawInfo () const
void setInfo (Constant *C)
Function * getCoroutine () const
void setCoroutineSelf ()
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Detailed Description
This represents the llvm.coro.alloc instruction.
Definition at line 81 of file CoroInstr.h.
Member Function Documentation
classof() [1/2]
static bool llvm::CoroIdInst::classof (const IntrinsicInst * I) inline static
Definition at line 177 of file CoroInstr.h.
References I.
classof() [2/2]
static bool llvm::CoroIdInst::classof (const Value * V) inline static
Definition at line 180 of file CoroInstr.h.
clearPromise()
void llvm::CoroIdInst::clearPromise () inline
Definition at line 107 of file CoroInstr.h.
References assert().
Referenced by llvm::coro::buildCoroutineFrame().
getCoroAlloc()
CoroAllocInst * llvm::CoroIdInst::getCoroAlloc () inline
Definition at line 85 of file CoroInstr.h.
References users.
Referenced by handleNoSuspendCoroutine(), and updateCoroFrame().
getCoroBegin()
IntrinsicInst * llvm::CoroIdInst::getCoroBegin () inline
Definition at line 92 of file CoroInstr.h.
References users.
getCoroutine()
Function * llvm::CoroIdInst::getCoroutine () const inline
Definition at line 165 of file CoroInstr.h.
getInfo()
Info llvm::CoroIdInst::getInfo () const inline
Definition at line 145 of file CoroInstr.h.
References assert(), llvm::CoroIdInst::Info::OutlinedParts, and llvm::CoroIdInst::Info::Resumers.
getPromise()
AllocaInst * llvm::CoroIdInst::getPromise () const inline
Definition at line 100 of file CoroInstr.h.
Referenced by llvm::coro::buildCoroutineFrame().
getRawInfo()
Constant * llvm::CoroIdInst::getRawInfo () const inline
Definition at line 159 of file CoroInstr.h.
setCoroutineSelf()
void llvm::CoroIdInst::setCoroutineSelf () inline
Definition at line 168 of file CoroInstr.h.
References assert(), and getFunction().
setInfo()
void llvm::CoroIdInst::setInfo (Constant * C) inline
Definition at line 163 of file CoroInstr.h.
Referenced by setCoroInfo().
The documentation for this class was generated from the following file:
lib/Transforms/Coroutines/CoroInstr.h