LLVM: llvm::jitlink::EHFrameRegistrar Class Reference
llvm::jitlink::EHFrameRegistrar Class Reference abstract
Supports registration/deregistration of EH-frames in a target process.
#include "llvm/ExecutionEngine/JITLink/EHFrameSupport.h"
Public Member Functions
virtual ~EHFrameRegistrar ()
virtual Error registerEHFrames (JITTargetAddress EHFrameSectionAddr)=0
virtual Error deregisterEHFrames (JITTargetAddress EHFrameSectionAddr)=0
Detailed Description
Supports registration/deregistration of EH-frames in a target process.
Definition at line 31 of file EHFrameSupport.h.
Constructor & Destructor Documentation
~EHFrameRegistrar()
llvm::jitlink::EHFrameRegistrar::~EHFrameRegistrar () virtual
Definition at line 511 of file EHFrameSupport.cpp.
Member Function Documentation
deregisterEHFrames()
virtual Error llvm::jitlink::EHFrameRegistrar::deregisterEHFrames (JITTargetAddress EHFrameSectionAddr) pure virtual
Implemented in llvm::jitlink::InProcessEHFrameRegistrar.
Referenced by llvm::orc::EHFrameRegistrationPlugin::notifyRemovingAllModules(), and llvm::orc::EHFrameRegistrationPlugin::notifyRemovingModule().
registerEHFrames()
virtual Error llvm::jitlink::EHFrameRegistrar::registerEHFrames (JITTargetAddress EHFrameSectionAddr) pure virtual
Implemented in llvm::jitlink::InProcessEHFrameRegistrar.
Referenced by llvm::orc::EHFrameRegistrationPlugin::notifyEmitted().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/EHFrameSupport.h
lib/ExecutionEngine/JITLink/EHFrameSupport.cpp