LLVM: llvm::DebugLocEntry Class Reference
llvm::DebugLocEntry Class Reference
This struct describes location entries emitted in the .debug_loc section.
#include "CodeGen/AsmPrinter/DebugLocEntry.h"
Public Member Functions
DebugLocEntry (const MCSymbol *Begin, const MCSymbol *End, ArrayRef< DbgValueLoc > Vals)
Create a location list entry for the range [Begin, End).
bool MergeRanges (const DebugLocEntry &Next)
Attempt to merge this DebugLocEntry with Next and return true if the merge was successful.
const MCSymbol * getBeginSym () const
const MCSymbol * getEndSym () const
ArrayRef< DbgValueLoc > getValues () const
void addValues (ArrayRef< DbgValueLoc > Vals)
void sortUniqueValues ()
void finalize (const AsmPrinter &AP, DebugLocStream::ListBuilder &List, const DIBasicType *BT, DwarfCompileUnit &TheCU)
Lower this entry into a DWARF expression.
Detailed Description
This struct describes location entries emitted in the .debug_loc section.
Definition at line 92 of file DebugLocEntry.h.
Constructor & Destructor Documentation
DebugLocEntry()
llvm::DebugLocEntry::DebugLocEntry (const MCSymbol * Begin, const MCSymbol * End, ArrayRef< DbgValueLoc > Vals) inline
Create a location list entry for the range [Begin, End).
Parameters
Vals One or more values describing (parts of) the variable.
Definition at line 105 of file DebugLocEntry.h.
References addValues().
Member Function Documentation
addValues()
void llvm::DebugLocEntry::addValues (ArrayRef< DbgValueLoc > Vals) inline
Definition at line 127 of file DebugLocEntry.h.
References llvm::all_of(), llvm::SmallVectorImpl< T >::append(), assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::DbgValueLoc::isFragment(), llvm::SmallVectorBase::size(), and sortUniqueValues().
Referenced by DebugLocEntry().
finalize()
void DebugLocEntry::finalize (const AsmPrinter & AP, DebugLocStream::ListBuilder & List, const DIBasicType * BT, DwarfCompileUnit & TheCU)
Lower this entry into a DWARF expression.
Definition at line 2037 of file DwarfDebug.cpp.
References llvm::all_of(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::DwarfDebug::emitDebugLocValue(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DwarfExpression::finalize(), llvm::AsmPrinter::getDwarfVersion(), List, P, and llvm::SmallVectorBase::size().
getBeginSym()
const MCSymbol * llvm::DebugLocEntry::getBeginSym () const inline
Definition at line 124 of file DebugLocEntry.h.
getEndSym()
const MCSymbol * llvm::DebugLocEntry::getEndSym () const inline
Definition at line 125 of file DebugLocEntry.h.
getValues()
ArrayRef< DbgValueLoc > llvm::DebugLocEntry::getValues () const inline
Definition at line 126 of file DebugLocEntry.h.
MergeRanges()
bool llvm::DebugLocEntry::MergeRanges (const DebugLocEntry & Next) inline
Attempt to merge this DebugLocEntry with Next and return true if the merge was successful.
Entries can be merged if they share the same Loc/Constant and if Next immediately follows this Entry.
Definition at line 115 of file DebugLocEntry.h.
sortUniqueValues()
void llvm::DebugLocEntry::sortUniqueValues () inline
Definition at line 137 of file DebugLocEntry.h.
References A, B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), and llvm::sort().
Referenced by addValues().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DebugLocEntry.h
lib/CodeGen/AsmPrinter/DwarfDebug.cpp