LLVM: llvm::jitlink::DefinedAtom Class Reference
llvm::jitlink::DefinedAtom Class Reference
Defined atom class.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Types
using edge_iterator = EdgeVector::iterator
Public Member Functions
Section & getSection () const
uint64_t getSize () const
StringRef getContent () const
void setContent (StringRef Content)
bool isZeroFill () const
void setZeroFill (uint64_t Size)
uint64_t getZeroFillSize () const
uint32_t getAlignment () const
bool hasLayoutNext () const
void setLayoutNext (DefinedAtom &Next)
DefinedAtom & getLayoutNext ()
bool isCommon () const
void addEdge (Edge::Kind K, Edge::OffsetT Offset, Atom &Target, Edge::AddendT Addend)
iterator_range< edge_iterator > edges ()
size_t edges_size () const
bool edges_empty () const
unsigned getOrdinal () const
Public Member Functions inherited from llvm::jitlink::Atom
bool hasName () const
Returns true if this atom has a name.
StringRef getName () const
Returns the name of this atom.
JITTargetAddress getAddress () const
Returns the current target address of this atom.
void setAddress (JITTargetAddress Address)
Set the current target address of this atom.
bool isDefined () const
Returns true if this is a defined atom.
bool isLive () const
Returns true if this atom is marked as live.
void setLive (bool IsLive)
Mark this atom as live.
bool shouldDiscard () const
Returns true if this atom should be discarded during pruning.
void setShouldDiscard (bool ShouldDiscard)
Mark this atom to be discarded.
bool isGlobal () const
Returns true if this definition is global (i.e.
void setGlobal (bool IsGlobal)
Mark this atom as global.
bool isAbsolute () const
Returns true if this atom represents an absolute symbol.
bool isCallable () const
Returns true if this atom is known to be callable.
void setCallable (bool IsCallable)
Mark this atom as callable.
bool isExported () const
Returns true if this atom should appear in the symbol table of a final linked image.
void setExported (bool IsExported)
Mark this atom as exported.
bool isWeak () const
Returns true if this is a weak symbol.
void setWeak (bool IsWeak)
Mark this atom as weak.
Friends
class AtomGraph
Additional Inherited Members
Protected Member Functions inherited from llvm::jitlink::Atom
Atom (StringRef Name)
Create a named (as yet unresolved) atom.
Atom (StringRef Name, JITTargetAddress Address)
Create an absolute symbol atom.
Protected Attributes inherited from llvm::jitlink::Atom
bool HasLayoutNext: 1
bool IsCommon: 1
Detailed Description
Defined atom class.
Suitable for use by defined named and anonymous atoms.
Definition at line 342 of file JITLink.h.
Member Typedef Documentation
edge_iterator
using llvm::jitlink::DefinedAtom::edge_iterator = EdgeVector::iterator
Definition at line 360 of file JITLink.h.
Member Function Documentation
addEdge()
void llvm::jitlink::DefinedAtom::addEdge (Edge::Kind K, Edge::OffsetT Offset, Atom & Target, Edge::AddendT Addend) inline
Definition at line 416 of file JITLink.h.
References assert().
edges()
iterator_range< edge_iterator > llvm::jitlink::DefinedAtom::edges () inline
Definition at line 423 of file JITLink.h.
References llvm::make_range().
Referenced by getLayoutNext(), and llvm::jitlink::prune().
edges_empty()
bool llvm::jitlink::DefinedAtom::edges_empty () const inline
Definition at line 427 of file JITLink.h.
edges_size()
size_t llvm::jitlink::DefinedAtom::edges_size () const inline
Definition at line 426 of file JITLink.h.
getAlignment()
uint32_t llvm::jitlink::DefinedAtom::getAlignment () const inline
Definition at line 392 of file JITLink.h.
getContent()
StringRef llvm::jitlink::DefinedAtom::getContent () const inline
Definition at line 366 of file JITLink.h.
References assert(), llvm::jitlink::Section::isZeroFill(), and Size.
getLayoutNext()
DefinedAtom & llvm::jitlink::DefinedAtom::getLayoutNext () inline
Definition at line 400 of file JITLink.h.
References assert(), E, edges(), and llvm::jitlink::Atom::HasLayoutNext.
getOrdinal()
unsigned llvm::jitlink::DefinedAtom::getOrdinal () const inline
Definition at line 429 of file JITLink.h.
getSection()
Section & llvm::jitlink::DefinedAtom::getSection () const inline
Definition at line 362 of file JITLink.h.
Referenced by llvm::jitlink::AtomGraph::removeDefinedAtom().
getSize()
uint64_t llvm::jitlink::DefinedAtom::getSize () const inline
Definition at line 364 of file JITLink.h.
References Size.
Referenced by llvm::jitlink::SectionRange::getEnd().
getZeroFillSize()
uint64_t llvm::jitlink::DefinedAtom::getZeroFillSize () const inline
Definition at line 386 of file JITLink.h.
References assert(), llvm::jitlink::Section::isZeroFill(), and Size.
hasLayoutNext()
bool llvm::jitlink::DefinedAtom::hasLayoutNext () const inline
Definition at line 394 of file JITLink.h.
References llvm::jitlink::Atom::HasLayoutNext.
isCommon()
bool llvm::jitlink::DefinedAtom::isCommon () const inline
Definition at line 414 of file JITLink.h.
References llvm::jitlink::Atom::IsCommon.
isZeroFill()
bool llvm::jitlink::DefinedAtom::isZeroFill () const inline
Definition at line 378 of file JITLink.h.
References llvm::jitlink::Section::isZeroFill().
setContent()
void llvm::jitlink::DefinedAtom::setContent (StringRef Content) inline
Definition at line 372 of file JITLink.h.
References assert(), llvm::StringRef::data(), llvm::jitlink::Section::isZeroFill(), llvm::StringRef::size(), and Size.
Referenced by llvm::jitlink::EHFrameParser::atomize().
setLayoutNext()
void llvm::jitlink::DefinedAtom::setLayoutNext (DefinedAtom & Next) inline
Definition at line 395 of file JITLink.h.
References assert(), and llvm::jitlink::Atom::HasLayoutNext.
setZeroFill()
void llvm::jitlink::DefinedAtom::setZeroFill (uint64_t Size) inline
Definition at line 380 of file JITLink.h.
References assert(), llvm::jitlink::Section::isZeroFill(), and Size.
Friends And Related Function Documentation
AtomGraph
friend class AtomGraph friend
Definition at line 343 of file JITLink.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h