LLVM: llvm::AMDGPUArgumentUsageInfo Class Reference
llvm::AMDGPUArgumentUsageInfo Class Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
AMDGPUArgumentUsageInfo ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool doInitialization (Module &M) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
bool doFinalization (Module &M) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void print (raw_ostream &OS, const Module *M=nullptr) const override
print - Print out the internal state of the pass.
void setFuncArgInfo (const Function &F, const AMDGPUFunctionArgInfo &ArgInfo)
const AMDGPUFunctionArgInfo & lookupFuncArgInfo (const Function &F) const
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 155 of file AMDGPUArgumentUsageInfo.h.
Constructor & Destructor Documentation
AMDGPUArgumentUsageInfo()
llvm::AMDGPUArgumentUsageInfo::AMDGPUArgumentUsageInfo () inline
Definition at line 163 of file AMDGPUArgumentUsageInfo.h.
Member Function Documentation
doFinalization()
bool AMDGPUArgumentUsageInfo::doFinalization (Module &) override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 50 of file AMDGPUArgumentUsageInfo.cpp.
doInitialization()
bool AMDGPUArgumentUsageInfo::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 46 of file AMDGPUArgumentUsageInfo.cpp.
getAnalysisUsage()
void llvm::AMDGPUArgumentUsageInfo::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 165 of file AMDGPUArgumentUsageInfo.h.
References llvm::AnalysisUsage::setPreservesAll().
lookupFuncArgInfo()
const AMDGPUFunctionArgInfo & llvm::AMDGPUArgumentUsageInfo::lookupFuncArgInfo (const Function & F) const inline
Definition at line 178 of file AMDGPUArgumentUsageInfo.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
print()
void AMDGPUArgumentUsageInfo::print (raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 55 of file AMDGPUArgumentUsageInfo.cpp.
setFuncArgInfo()
void llvm::AMDGPUArgumentUsageInfo::setFuncArgInfo (const Function & F, const AMDGPUFunctionArgInfo & ArgInfo) inline
Definition at line 174 of file AMDGPUArgumentUsageInfo.h.
References F.
Referenced by llvm::SITargetLowering::LowerFormalArguments().
Member Data Documentation
ID
char llvm::AMDGPUArgumentUsageInfo::ID static
Definition at line 161 of file AMDGPUArgumentUsageInfo.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.cpp