LLVM: llvm::pdb::DIASession Class Reference
llvm::pdb::DIASession Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIASession.h"
Public Member Functions
DIASession (CComPtr< IDiaSession > DiaSession)
uint64_t getLoadAddress () const override
bool setLoadAddress (uint64_t Address) override
std::unique_ptr< PDBSymbolExe > getGlobalScope () override
std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const override
bool addressForVA (uint64_t VA, uint32_t &Section, uint32_t &Offset) const override
bool addressForRVA (uint32_t RVA, uint32_t &Section, uint32_t &Offset) const override
std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) const override
std::unique_ptr< PDBSymbol > findSymbolByRVA (uint32_t RVA, PDB_SymType Type) const override
std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Section, uint32_t Offset, PDB_SymType Type) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbers (const PDBSymbolCompiland &Compiland, const IPDBSourceFile &File) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumSourceFiles > findSourceFiles (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBSourceFile > findOneSourceFile (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< PDBSymbolCompiland > findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSourceFiles > getAllSourceFiles () const override
std::unique_ptr< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const override
std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const override
std::unique_ptr< IPDBEnumDataStreams > getDebugStreams () const override
std::unique_ptr< IPDBEnumTables > getEnumTables () const override
std::unique_ptr< IPDBEnumInjectedSources > getInjectedSources () const override
std::unique_ptr< IPDBEnumSectionContribs > getSectionContribs () const override
std::unique_ptr< IPDBEnumFrameData > getFrameData () const override
Public Member Functions inherited from llvm::pdb::IPDBSession
virtual ~IPDBSession ()
virtual uint64_t getLoadAddress () const =0
virtual bool setLoadAddress (uint64_t Address)=0
virtual std::unique_ptr< PDBSymbolExe > getGlobalScope ()=0
virtual std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const =0
virtual bool addressForVA (uint64_t VA, uint32_t &Section, uint32_t &Offset) const =0
virtual bool addressForRVA (uint32_t RVA, uint32_t &Section, uint32_t &Offset) const =0
template<typename T >
std::unique_ptr< T > getConcreteSymbolById (SymIndexId SymbolId) const
virtual std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) const =0
virtual std::unique_ptr< PDBSymbol > findSymbolByRVA (uint32_t RVA, PDB_SymType Type) const =0
virtual std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbers (const PDBSymbolCompiland &Compiland, const IPDBSourceFile &File) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > findSourceFiles (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBSourceFile > findOneSourceFile (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< PDBSymbolCompiland > findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getAllSourceFiles () const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const =0
virtual std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const =0
virtual std::unique_ptr< IPDBEnumDataStreams > getDebugStreams () const =0
virtual std::unique_ptr< IPDBEnumTables > getEnumTables () const =0
virtual std::unique_ptr< IPDBEnumInjectedSources > getInjectedSources () const =0
virtual std::unique_ptr< IPDBEnumSectionContribs > getSectionContribs () const =0
virtual std::unique_ptr< IPDBEnumFrameData > getFrameData () const =0
Static Public Member Functions
static Error createFromPdb (StringRef Path, std::unique_ptr< IPDBSession > &Session)
static Error createFromExe (StringRef Path, std::unique_ptr< IPDBSession > &Session)
Detailed Description
Definition at line 22 of file DIASession.h.
Constructor & Destructor Documentation
DIASession()
DIASession::DIASession (CComPtr< IDiaSession > DiaSession) explicit
Definition at line 93 of file DIASession.cpp.
Member Function Documentation
addressForRVA()
bool DIASession::addressForRVA (uint32_t RVA, uint32_t & Section, uint32_t & Offset) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 179 of file DIASession.cpp.
addressForVA()
bool DIASession::addressForVA (uint64_t VA, uint32_t & Section, uint32_t & Offset) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 168 of file DIASession.cpp.
createFromExe()
Error DIASession::createFromExe (StringRef Path, std::unique_ptr< IPDBSession > & Session) static
Definition at line 121 of file DIASession.cpp.
References llvm::convertUTF8ToUTF16String(), ErrorFromHResult(), llvm::pdb::invalid_utf8_path, LoadDIA(), and llvm::Error::success().
Referenced by llvm::pdb::loadDataForEXE().
createFromPdb()
Error DIASession::createFromPdb (StringRef Path, std::unique_ptr< IPDBSession > & Session) static
Definition at line 95 of file DIASession.cpp.
References llvm::convertUTF8ToUTF16String(), ErrorFromHResult(), llvm::pdb::invalid_utf8_path, LoadDIA(), and llvm::Error::success().
Referenced by llvm::pdb::loadDataForPDB().
findCompilandsForSourceFile()
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > DIASession::findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 323 of file DIASession.cpp.
References findOneSourceFile().
Referenced by findOneCompilandForSourceFile().
findLineNumbers()
std::unique_ptr< IPDBEnumLineNumbers > DIASession::findLineNumbers (const PDBSymbolCompiland & Compiland, const IPDBSourceFile & File) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 243 of file DIASession.cpp.
References llvm::pdb::Compiland, llvm::pdb::DIASourceFile::getDiaFile(), llvm::pdb::DIARawSymbol::getDiaSymbol(), and llvm::pdb::LineNumbers.
findLineNumbersByAddress()
std::unique_ptr< IPDBEnumLineNumbers > DIASession::findLineNumbersByAddress (uint64_t Address, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 258 of file DIASession.cpp.
References llvm::Address, and llvm::pdb::LineNumbers.
findLineNumbersByRVA()
std::unique_ptr< IPDBEnumLineNumbers > DIASession::findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 272 of file DIASession.cpp.
References llvm::pdb::LineNumbers.
findLineNumbersBySectOffset()
std::unique_ptr< IPDBEnumLineNumbers > DIASession::findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 281 of file DIASession.cpp.
References llvm::pdb::LineNumbers.
findOneCompilandForSourceFile()
std::unique_ptr< PDBSymbolCompiland > DIASession::findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 332 of file DIASession.cpp.
References findCompilandsForSourceFile().
findOneSourceFile()
std::unique_ptr< IPDBSourceFile > DIASession::findOneSourceFile (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 313 of file DIASession.cpp.
References llvm::pdb::Compiland, findSourceFiles(), and llvm::pdb::SourceFiles.
Referenced by findCompilandsForSourceFile().
findSourceFiles()
std::unique_ptr< IPDBEnumSourceFiles > DIASession::findSourceFiles (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 291 of file DIASession.cpp.
References llvm::pdb::Compiland, llvm::pdb::NS_FileNameExtMatch, and llvm::pdb::SourceFiles.
Referenced by findOneSourceFile().
findSymbolByAddress()
std::unique_ptr< PDBSymbol > DIASession::findSymbolByAddress (uint64_t Address, PDB_SymType Type) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 201 of file DIASession.cpp.
References llvm::Address, llvm::TargetMachineBuilder::create(), and llvm::pdb::Type.
findSymbolByRVA()
std::unique_ptr< PDBSymbol > DIASession::findSymbolByRVA (uint32_t RVA, PDB_SymType Type) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 217 of file DIASession.cpp.
References llvm::TargetMachineBuilder::create(), and llvm::pdb::Type.
findSymbolBySectOffset()
std::unique_ptr< PDBSymbol > DIASession::findSymbolBySectOffset (uint32_t Section, uint32_t Offset, PDB_SymType Type) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 230 of file DIASession.cpp.
References llvm::TargetMachineBuilder::create(), and llvm::pdb::Type.
getAllSourceFiles()
std::unique_ptr< IPDBEnumSourceFiles > DIASession::getAllSourceFiles () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 340 of file DIASession.cpp.
getDebugStreams()
std::unique_ptr< IPDBEnumDataStreams > DIASession::getDebugStreams () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 370 of file DIASession.cpp.
getEnumTables()
std::unique_ptr< IPDBEnumTables > DIASession::getEnumTables () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 378 of file DIASession.cpp.
getFrameData()
std::unique_ptr< IPDBEnumFrameData > DIASession::getFrameData () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 424 of file DIASession.cpp.
getGlobalScope()
std::unique_ptr< PDBSymbolExe > DIASession::getGlobalScope () override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 156 of file DIASession.cpp.
References llvm::TargetMachineBuilder::create().
getInjectedSources()
std::unique_ptr< IPDBEnumInjectedSources > DIASession::getInjectedSources () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 404 of file DIASession.cpp.
getLoadAddress()
uint64_t DIASession::getLoadAddress () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 146 of file DIASession.cpp.
getSectionContribs()
std::unique_ptr< IPDBEnumSectionContribs > DIASession::getSectionContribs () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 414 of file DIASession.cpp.
getSourceFileById()
std::unique_ptr< IPDBSourceFile > DIASession::getSourceFileById (uint32_t FileId) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 362 of file DIASession.cpp.
getSourceFilesForCompiland()
std::unique_ptr< IPDBEnumSourceFiles > DIASession::getSourceFilesForCompiland (const PDBSymbolCompiland & Compiland) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 348 of file DIASession.cpp.
References llvm::pdb::Compiland, and llvm::pdb::DIARawSymbol::getDiaSymbol().
getSymbolById()
std::unique_ptr< PDBSymbol > DIASession::getSymbolById (SymIndexId SymbolId) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 191 of file DIASession.cpp.
References llvm::TargetMachineBuilder::create().
setLoadAddress()
bool DIASession::setLoadAddress (uint64_t Address) override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 152 of file DIASession.cpp.
References llvm::Address.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIASession.h
lib/DebugInfo/PDB/DIA/DIASession.cpp