LLVM: llvm::SparseBitVector< ElementSize > Class Template Reference
llvm::SparseBitVector< ElementSize > Class Template Reference
#include "llvm/ADT/SparseBitVector.h"
Public Types
using iterator = SparseBitVectorIterator
Public Member Functions
SparseBitVector ()
SparseBitVector (const SparseBitVector &RHS)
SparseBitVector (SparseBitVector &&RHS)
void clear ()
SparseBitVector & operator= (const SparseBitVector &RHS)
SparseBitVector & operator= (SparseBitVector &&RHS)
bool test (unsigned Idx) const
void reset (unsigned Idx)
void set (unsigned Idx)
bool test_and_set (unsigned Idx)
bool operator!= (const SparseBitVector &RHS) const
bool operator== (const SparseBitVector &RHS) const
bool operator|= (const SparseBitVector &RHS)
bool operator&= (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector< ElementSize > *RHS) const
void intersectWithComplement (const SparseBitVector< ElementSize > &RHS1, const SparseBitVector< ElementSize > &RHS2)
void intersectWithComplement (const SparseBitVector< ElementSize > *RHS1, const SparseBitVector< ElementSize > *RHS2)
bool intersects (const SparseBitVector< ElementSize > *RHS) const
bool intersects (const SparseBitVector< ElementSize > &RHS) const
bool contains (const SparseBitVector< ElementSize > &RHS) const
int find_first () const
int find_last () const
bool empty () const
unsigned count () const
iterator begin () const
iterator end () const
Detailed Description
template<unsigned ElementSize = 128>
class llvm::SparseBitVector< ElementSize >
Definition at line 255 of file SparseBitVector.h.
Member Typedef Documentation
iterator
template<unsigned ElementSize = 128> using llvm::SparseBitVector< ElementSize >::iterator = SparseBitVectorIterator
Definition at line 441 of file SparseBitVector.h.
Constructor & Destructor Documentation
SparseBitVector() [1/3]
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::SparseBitVector () inline
Definition at line 443 of file SparseBitVector.h.
SparseBitVector() [2/3]
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::SparseBitVector (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 445 of file SparseBitVector.h.
SparseBitVector() [3/3]
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::SparseBitVector (SparseBitVector< ElementSize > && RHS) inline
Definition at line 447 of file SparseBitVector.h.
Member Function Documentation
begin()
template<unsigned ElementSize = 128> iterator llvm::SparseBitVector< ElementSize >::begin () const inline
Definition at line 809 of file SparseBitVector.h.
Referenced by llvm::dump().
clear()
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::clear () inline
Definition at line 451 of file SparseBitVector.h.
Referenced by llvm::pdb::HashTable< ValueT >::clear(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), and llvm::LiveVariables::runOnMachineFunction().
contains()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::contains (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 772 of file SparseBitVector.h.
count()
template<unsigned ElementSize = 128> unsigned llvm::SparseBitVector< ElementSize >::count () const inline
Definition at line 799 of file SparseBitVector.h.
Referenced by llvm::pdb::HashTable< ValueT >::load(), and llvm::pdb::HashTable< ValueT >::size().
empty()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::empty () const inline
Definition at line 795 of file SparseBitVector.h.
Referenced by llvm::LiveVariables::HandleVirtRegDef(), and llvm::SparseBitVector< ElementSize >::intersectWithComplement().
end()
template<unsigned ElementSize = 128> iterator llvm::SparseBitVector< ElementSize >::end () const inline
Definition at line 813 of file SparseBitVector.h.
Referenced by llvm::dump().
find_first()
template<unsigned ElementSize = 128> int llvm::SparseBitVector< ElementSize >::find_first () const inline
Definition at line 779 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::find_first(), and llvm::SparseBitVectorElement< ElementSize >::index().
find_last()
template<unsigned ElementSize = 128> int llvm::SparseBitVector< ElementSize >::find_last () const inline
Definition at line 787 of file SparseBitVector.h.
Referenced by llvm::pdb::HashTable< ValueT >::calculateSerializedLength(), and llvm::pdb::writeSparseBitVector().
intersects() [1/2]
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersects (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 743 of file SparseBitVector.h.
intersects() [2/2]
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersects (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 738 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersects().
Referenced by llvm::SparseBitVector< ElementSize >::intersects(), and llvm::pdb::HashTable< ValueT >::load().
intersectWithComplement() [1/4]
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 636 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::clear(), and llvm::SparseBitVector< ElementSize >::empty().
Referenced by llvm::SparseBitVector< ElementSize >::intersectWithComplement().
intersectWithComplement() [2/4]
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > & RHS1, const SparseBitVector< ElementSize > & RHS2) inline
Definition at line 687 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersectWithComplement().
intersectWithComplement() [3/4]
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 681 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersectWithComplement().
intersectWithComplement() [4/4]
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS1, const SparseBitVector< ElementSize > * RHS2) inline
Definition at line 733 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersectWithComplement().
operator!=()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator!= (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 540 of file SparseBitVector.h.
operator&=()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator&= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 587 of file SparseBitVector.h.
operator=() [1/2]
template<unsigned ElementSize = 128> SparseBitVector & llvm::SparseBitVector< ElementSize >::operator= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 456 of file SparseBitVector.h.
operator=() [2/2]
template<unsigned ElementSize = 128> SparseBitVector & llvm::SparseBitVector< ElementSize >::operator= (SparseBitVector< ElementSize > && RHS) inline
Definition at line 464 of file SparseBitVector.h.
operator==()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator== (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 544 of file SparseBitVector.h.
operator|=()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator|= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 557 of file SparseBitVector.h.
reset()
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::reset (unsigned Idx) inline
Definition at line 486 of file SparseBitVector.h.
References Idx.
set()
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::set (unsigned Idx) inline
Definition at line 507 of file SparseBitVector.h.
References Idx.
Referenced by llvm::LiveVariables::addNewBlock(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::pdb::readSparseBitVector(), llvm::SIMachineFunctionInfo::ReserveWWMRegister(), llvm::LiveVariables::setPHIJoin(), llvm::SparseBitVector< ElementSize >::test_and_set(), and llvm::LiveIntervalUnion::verify().
test()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::test (unsigned Idx) const inline
Definition at line 471 of file SparseBitVector.h.
References Idx.
Referenced by llvm::LiveVariables::HandleVirtRegUse(), llvm::pdb::HashTable< ValueT >::isDeleted(), llvm::LiveVariables::VarInfo::isLiveIn(), llvm::LiveVariables::isPHIJoin(), llvm::pdb::HashTable< ValueT >::isPresent(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::SparseBitVector< ElementSize >::test_and_set(), and llvm::pdb::writeSparseBitVector().
test_and_set()
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::test_and_set (unsigned Idx) inline
Definition at line 531 of file SparseBitVector.h.
References Idx, llvm::SparseBitVector< ElementSize >::set(), and llvm::SparseBitVector< ElementSize >::test().
The documentation for this class was generated from the following file:
include/llvm/ADT/SparseBitVector.h