LLVM: llvm::VirtRegAuxInfo Class Reference
llvm::VirtRegAuxInfo Class Reference
Calculate auxiliary information for a virtual register such as its spill weight and allocation hint.
#include "llvm/CodeGen/CalcSpillWeights.h"
Public Types
using NormalizingFn = float(*)(float, unsigned, unsigned)
Public Member Functions
VirtRegAuxInfo (MachineFunction &mf, LiveIntervals &lis, VirtRegMap *vrm, const MachineLoopInfo &loops, const MachineBlockFrequencyInfo &mbfi, NormalizingFn norm=normalizeSpillWeight)
void calculateSpillWeightAndHint (LiveInterval &li)
(re)compute li's spill weight and allocation hint.
float futureWeight (LiveInterval &li, SlotIndex start, SlotIndex end)
Compute future expected spill weight of a split artifact of li that will span between start and end slot indexes.
float weightCalcHelper (LiveInterval &li, SlotIndex *start=nullptr, SlotIndex *end=nullptr)
Helper function for weight calculations.
Detailed Description
Calculate auxiliary information for a virtual register such as its spill weight and allocation hint.
Definition at line 46 of file CalcSpillWeights.h.
Member Typedef Documentation
NormalizingFn
using llvm::VirtRegAuxInfo::NormalizingFn = float (*)(float, unsigned, unsigned)
Definition at line 48 of file CalcSpillWeights.h.
Constructor & Destructor Documentation
VirtRegAuxInfo()
llvm::VirtRegAuxInfo::VirtRegAuxInfo (MachineFunction & mf, LiveIntervals & lis, VirtRegMap * vrm, const MachineLoopInfo & loops, const MachineBlockFrequencyInfo & mbfi, NormalizingFn norm = normalizeSpillWeight) inline
Definition at line 60 of file CalcSpillWeights.h.
References Loops.
Member Function Documentation
calculateSpillWeightAndHint()
void VirtRegAuxInfo::calculateSpillWeightAndHint (LiveInterval & li)
(re)compute li's spill weight and allocation hint.
Definition at line 137 of file CalcSpillWeights.cpp.
References llvm::LiveInterval::weight, and weightCalcHelper().
Referenced by llvm::LiveRangeEdit::calculateRegClassAndHint(), and llvm::calculateSpillWeightsAndHints().
futureWeight()
float VirtRegAuxInfo::futureWeight (LiveInterval & li, SlotIndex start, SlotIndex end)
Compute future expected spill weight of a split artifact of li that will span between start and end slot indexes.
Parameters
li The live interval to be split.
start The expected begining of the split artifact. Instructions before start will not affect the weight.
end The expected end of the split artifact. Instructions after end will not affect the weight.
Returns
The expected spill weight of the split artifact. Returns negative weight for unspillable li.
Definition at line 145 of file CalcSpillWeights.cpp.
References weightCalcHelper().
weightCalcHelper()
float VirtRegAuxInfo::weightCalcHelper (LiveInterval & li, SlotIndex * start = nullptr, SlotIndex * end = nullptr)
Helper function for weight calculations.
(Re)compute li's spill weight and allocation hint, or, for non null start and end - compute future expected spill weight of a split artifact of li that will span between start and end slot indexes.
Parameters
li The live interval for which to compute the weight.
start The expected begining of the split artifact. Instructions before start will not affect the weight. Relevant for weight calculation of future split artifact.
end The expected end of the split artifact. Instructions after end will not affect the weight. Relevant for weight calculation of future split artifact.
Returns
The spill weight. Returns negative weight for unspillable li.
Definition at line 150 of file CalcSpillWeights.cpp.
References llvm::MachineRegisterInfo::addRegAllocationHint(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::MachineRegisterInfo::clearSimpleHint(), copyHint(), llvm::SlotIndex::distance(), E, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::LiveIntervals::getInstructionIndex(), llvm::MachineLoopInfo::getLoopFor(), llvm::LiveIntervals::getMBBFromIndex(), llvm::MachineInstr::getParent(), llvm::MachineRegisterInfo::getRegAllocationHint(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::LiveIntervals::getRegMaskSlots(), llvm::LiveInterval::getSize(), llvm::LiveIntervals::getSlotIndexes(), llvm::LiveIntervals::getSpillWeight(), llvm::MachineFunction::getSubtarget(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugInstr(), llvm::MachineInstr::isIdentityCopy(), llvm::MachineInstr::isImplicitDef(), llvm::LiveRange::isLiveAtIndexes(), llvm::LiveIntervals::isLiveOutOfMBB(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::TargetRegisterInfo::isPhysicalRegister(), isRematerializable(), llvm::LiveInterval::isSpillable(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::LiveRange::isZeroLength(), llvm::LiveInterval::markNotSpillable(), llvm::operator<(), P, llvm::MachineInstr::readsWritesVirtualRegister(), llvm::LiveInterval::reg, Reg, llvm::MachineRegisterInfo::reg_instr_begin(), and llvm::MachineRegisterInfo::reg_instr_end().
Referenced by calculateSpillWeightAndHint(), and futureWeight().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/CalcSpillWeights.h
lib/CodeGen/CalcSpillWeights.cpp