LLVM: llvm::orc::rpc::SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type > Class Template Reference
llvm::orc::rpc::SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type > Class Template Reference
#include "llvm/ExecutionEngine/Orc/RawByteChannel.h"
Static Public Member Functions
static Error serialize (RawByteChannel &C, StringRef S)
RPC channel serialization for std::strings.
Detailed Description
template<typename ChannelT>
class llvm::orc::rpc::SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
Definition at line 134 of file RawByteChannel.h.
Member Function Documentation
serialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize (RawByteChannel & C, StringRef S) inline static
RPC channel serialization for std::strings.
Definition at line 139 of file RawByteChannel.h.
References C, llvm::StringRef::data(), llvm::orc::rpc::serializeSeq(), and llvm::StringRef::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RawByteChannel.h