LLVM: OutputStream Class Reference
OutputStream Class Reference
#include "llvm/Demangle/Utility.h"
Public Member Functions
OutputStream (char *StartBuf, size_t Size)
OutputStream ()=default
void reset (char *Buffer_, size_t BufferCapacity_)
OutputStream & operator+= (StringView R)
OutputStream & operator+= (char C)
OutputStream & operator<< (StringView R)
OutputStream & operator<< (char C)
OutputStream & operator<< (long long N)
OutputStream & operator<< (unsigned long long N)
OutputStream & operator<< (long N)
OutputStream & operator<< (unsigned long N)
OutputStream & operator<< (int N)
OutputStream & operator<< (unsigned int N)
size_t getCurrentPosition () const
void setCurrentPosition (size_t NewPos)
char back () const
bool empty () const
char * getBuffer ()
char * getBufferEnd ()
size_t getBufferCapacity ()
Public Attributes
unsigned CurrentPackIndex = std::numeric_limits<unsigned>::max()
If a ParameterPackExpansion (or similar type) is encountered, the offset into the pack that we're currently printing.
unsigned CurrentPackMax = std::numeric_limits<unsigned>::max()
Detailed Description
Definition at line 27 of file Utility.h.
Constructor & Destructor Documentation
OutputStream() [1/2]
OutputStream::OutputStream (char * StartBuf, size_t Size) inline
Definition at line 66 of file Utility.h.
OutputStream() [2/2]
OutputStream::OutputStream () default
Member Function Documentation
back()
char OutputStream::back () const inline
Definition at line 132 of file Utility.h.
Referenced by outputSpaceIfNecessary(), TemplateArgs::printLeft(), and ArrayType::printRight().
empty()
bool OutputStream::empty () const inline
Definition at line 136 of file Utility.h.
Referenced by outputSpaceIfNecessary().
getBuffer()
char * OutputStream::getBuffer () inline
Definition at line 138 of file Utility.h.
Referenced by printNode().
getBufferCapacity()
size_t OutputStream::getBufferCapacity () inline
Definition at line 140 of file Utility.h.
getBufferEnd()
char * OutputStream::getBufferEnd () inline
Definition at line 139 of file Utility.h.
getCurrentPosition()
size_t OutputStream::getCurrentPosition () const inline
Definition at line 129 of file Utility.h.
Referenced by outputQualifiers(), ParameterPackExpansion::printLeft(), printNode(), and NodeArray::printWithComma().
operator+=() [1/2]
OutputStream & OutputStream::operator+= (char C) inline
Definition at line 90 of file Utility.h.
References C.
operator+=() [2/2]
OutputStream & OutputStream::operator+= (StringView R) inline
Definition at line 80 of file Utility.h.
References Size.
operator<<() [1/8]
OutputStream & OutputStream::operator<< (char C) inline
Definition at line 98 of file Utility.h.
References C.
operator<<() [2/8]
OutputStream & OutputStream::operator<< (int N) inline
Definition at line 121 of file Utility.h.
References N.
operator<<() [3/8]
OutputStream & OutputStream::operator<< (long long N) inline
Definition at line 100 of file Utility.h.
References N.
operator<<() [4/8]
OutputStream & OutputStream::operator<< (long N) inline
Definition at line 113 of file Utility.h.
References N.
operator<<() [5/8]
OutputStream & OutputStream::operator<< (StringView R) inline
Definition at line 96 of file Utility.h.
operator<<() [6/8]
OutputStream & OutputStream::operator<< (unsigned int N) inline
Definition at line 125 of file Utility.h.
References N.
operator<<() [7/8]
OutputStream & OutputStream::operator<< (unsigned long long N) inline
Definition at line 108 of file Utility.h.
References N.
operator<<() [8/8]
OutputStream & OutputStream::operator<< (unsigned long N) inline
Definition at line 117 of file Utility.h.
References N.
reset()
void OutputStream::reset (char * Buffer_, size_t BufferCapacity_) inline
Definition at line 69 of file Utility.h.
Referenced by initializeOutputStream().
setCurrentPosition()
void OutputStream::setCurrentPosition (size_t NewPos) inline
Definition at line 130 of file Utility.h.
Referenced by ParameterPackExpansion::printLeft(), and NodeArray::printWithComma().
Member Data Documentation
CurrentPackIndex
unsigned OutputStream::CurrentPackIndex = std::numeric_limits<unsigned>::max()
If a ParameterPackExpansion (or similar type) is encountered, the offset into the pack that we're currently printing.
Definition at line 77 of file Utility.h.
Referenced by ParameterPack::getSyntaxNode(), ParameterPack::hasArraySlow(), ParameterPack::hasFunctionSlow(), ParameterPack::hasRHSComponentSlow(), ParameterPack::printLeft(), ParameterPackExpansion::printLeft(), and ParameterPack::printRight().
CurrentPackMax
unsigned OutputStream::CurrentPackMax = std::numeric_limits<unsigned>::max()
Definition at line 78 of file Utility.h.
Referenced by ParameterPackExpansion::printLeft().
The documentation for this class was generated from the following file:
include/llvm/Demangle/Utility.h