LLVM: llvm::xray::PipelineConsumer Class Reference
llvm::xray::PipelineConsumer Class Reference
#include "llvm/XRay/FDRRecordConsumer.h"
Public Member Functions
PipelineConsumer (std::initializer_list< RecordVisitor * > V)
Error consume (std::unique_ptr< Record > R) override
Public Member Functions inherited from llvm::xray::RecordConsumer
virtual Error consume (std::unique_ptr< Record > R)=0
virtual ~RecordConsumer ()=default
Detailed Description
Definition at line 41 of file FDRRecordConsumer.h.
Constructor & Destructor Documentation
PipelineConsumer()
llvm::xray::PipelineConsumer::PipelineConsumer (std::initializer_list< RecordVisitor * > V) inline
Definition at line 45 of file FDRRecordConsumer.h.
Member Function Documentation
consume()
Error llvm::xray::PipelineConsumer::consume (std::unique_ptr< Record > R) override virtual
Implements llvm::xray::RecordConsumer.
Definition at line 22 of file LogBuilderConsumer.cpp.
References llvm::createStringError(), llvm::joinErrors(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecordConsumer.h
lib/XRay/LogBuilderConsumer.cpp