LLVM: llvm::pdb::NativeTypePointer Class Reference
llvm::pdb::NativeTypePointer Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeTypePointer.h"
Public Member Functions
NativeTypePointer (NativeSession &Session, SymIndexId Id, codeview::TypeIndex TI)
NativeTypePointer (NativeSession &Session, SymIndexId Id, codeview::TypeIndex TI, codeview::PointerRecord PR)
~NativeTypePointer () override
void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override
SymIndexId getClassParentId () const override
bool isConstType () const override
uint64_t getLength () const override
bool isReference () const override
bool isRValueReference () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
SymIndexId getTypeId () const override
bool isRestrictedType () const override
bool isVolatileType () const override
bool isUnalignedType () const override
bool isSingleInheritance () const override
bool isMultipleInheritance () const override
bool isVirtualInheritance () const override
Public Member Functions inherited from llvm::pdb::NativeRawSymbol
NativeRawSymbol (NativeSession &PDBSession, PDB_SymType Tag, SymIndexId SymbolId)
void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const override
void getDataBytes (SmallVector< uint8_t, 32 > &Bytes) const override
void getFrontEndVersion (VersionInfo &Version) const override
void getBackEndVersion (VersionInfo &Version) const override
PDB_MemberAccess getAccess () const override
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getAge () const override
SymIndexId getArrayIndexTypeId () const override
uint32_t getBaseDataOffset () const override
uint32_t getBaseDataSlot () const override
SymIndexId getBaseSymbolId () const override
PDB_BuiltinType getBuiltinType () const override
uint32_t getBitPosition () const override
PDB_CallingConv getCallingConvention () const override
SymIndexId getClassParentId () const override
std::string getCompilerName () const override
uint32_t getCount () const override
uint32_t getCountLiveRanges () const override
PDB_Lang getLanguage () const override
SymIndexId getLexicalParentId () const override
std::string getLibraryName () const override
uint32_t getLiveRangeStartAddressOffset () const override
uint32_t getLiveRangeStartAddressSection () const override
uint32_t getLiveRangeStartRelativeVirtualAddress () const override
codeview::RegisterId getLocalBasePointerRegisterId () const override
SymIndexId getLowerBoundId () const override
uint32_t getMemorySpaceKind () const override
std::string getName () const override
uint32_t getNumberOfAcceleratorPointerTags () const override
uint32_t getNumberOfColumns () const override
uint32_t getNumberOfModifiers () const override
uint32_t getNumberOfRegisterIndices () const override
uint32_t getNumberOfRows () const override
std::string getObjectFileName () const override
uint32_t getOemId () const override
SymIndexId getOemSymbolId () const override
uint32_t getOffsetInUdt () const override
PDB_Cpu getPlatform () const override
uint32_t getRank () const override
codeview::RegisterId getRegisterId () const override
uint32_t getRegisterType () const override
uint32_t getRelativeVirtualAddress () const override
uint32_t getSamplerSlot () const override
uint32_t getSignature () const override
uint32_t getSizeInUdt () const override
uint32_t getSlot () const override
std::string getSourceFileName () const override
std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const override
uint32_t getStride () const override
SymIndexId getSubTypeId () const override
std::string getSymbolsFileName () const override
SymIndexId getSymIndexId () const override
uint32_t getTargetOffset () const override
uint32_t getTargetRelativeVirtualAddress () const override
uint64_t getTargetVirtualAddress () const override
uint32_t getTargetSection () const override
uint32_t getTextureSlot () const override
uint32_t getTimeStamp () const override
uint32_t getToken () const override
SymIndexId getTypeId () const override
uint32_t getUavSlot () const override
std::string getUndecoratedName () const override
std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const override
SymIndexId getUnmodifiedTypeId () const override
SymIndexId getUpperBoundId () const override
Variant getValue () const override
uint32_t getVirtualBaseDispIndex () const override
uint32_t getVirtualBaseOffset () const override
SymIndexId getVirtualTableShapeId () const override
std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const override
PDB_DataKind getDataKind () const override
PDB_SymType getSymTag () const override
codeview::GUID getGuid () const override
int32_t getOffset () const override
int32_t getThisAdjust () const override
int32_t getVirtualBasePointerOffset () const override
PDB_LocType getLocationType () const override
PDB_Machine getMachineType () const override
codeview::ThunkOrdinal getThunkOrdinal () const override
uint64_t getLength () const override
uint64_t getLiveRangeLength () const override
uint64_t getVirtualAddress () const override
PDB_UdtType getUdtKind () const override
bool hasConstructor () const override
bool hasCustomCallingConvention () const override
bool hasFarReturn () const override
bool isCode () const override
bool isCompilerGenerated () const override
bool isConstType () const override
bool isEditAndContinueEnabled () const override
bool isFunction () const override
bool getAddressTaken () const override
bool getNoStackOrdering () const override
bool hasAlloca () const override
bool hasAssignmentOperator () const override
bool hasCTypes () const override
bool hasCastOperator () const override
bool hasDebugInfo () const override
bool hasEH () const override
bool hasEHa () const override
bool hasInlAsm () const override
bool hasInlineAttribute () const override
bool hasInterruptReturn () const override
bool hasFramePointer () const override
bool hasLongJump () const override
bool hasManagedCode () const override
bool hasNestedTypes () const override
bool hasNoInlineAttribute () const override
bool hasNoReturnAttribute () const override
bool hasOptimizedCodeDebugInfo () const override
bool hasOverloadedOperator () const override
bool hasSEH () const override
bool hasSecurityChecks () const override
bool hasSetJump () const override
bool hasStrictGSCheck () const override
bool isAcceleratorGroupSharedLocal () const override
bool isAcceleratorPointerTagLiveRange () const override
bool isAcceleratorStubFunction () const override
bool isAggregated () const override
bool isIntroVirtualFunction () const override
bool isCVTCIL () const override
bool isConstructorVirtualBase () const override
bool isCxxReturnUdt () const override
bool isDataAligned () const override
bool isHLSLData () const override
bool isHotpatchable () const override
bool isIndirectVirtualBaseClass () const override
bool isInterfaceUdt () const override
bool isIntrinsic () const override
bool isLTCG () const override
bool isLocationControlFlowDependent () const override
bool isMSILNetmodule () const override
bool isMatrixRowMajor () const override
bool isManagedCode () const override
bool isMSILCode () const override
bool isMultipleInheritance () const override
bool isNaked () const override
bool isNested () const override
bool isOptimizedAway () const override
bool isPacked () const override
bool isPointerBasedOnSymbolValue () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
bool isPureVirtual () const override
bool isRValueReference () const override
bool isRefUdt () const override
bool isReference () const override
bool isRestrictedType () const override
bool isReturnValue () const override
bool isSafeBuffers () const override
bool isScoped () const override
bool isSdl () const override
bool isSingleInheritance () const override
bool isSplitted () const override
bool isStatic () const override
bool hasPrivateSymbols () const override
bool isUnalignedType () const override
bool isUnreached () const override
bool isValueUdt () const override
bool isVirtual () const override
bool isVirtualBaseClass () const override
bool isVirtualInheritance () const override
bool isVolatileType () const override
bool wasInlined () const override
std::string getUnused () const override
Public Member Functions inherited from llvm::pdb::IPDBRawSymbol
virtual ~IPDBRawSymbol ()
virtual void dump (raw_ostream &OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByAddr (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByAddr (uint32_t Section, uint32_t Offset) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const =0
virtual std::unique_ptr< IPDBEnumSymbols > findInlineFramesByVA (uint64_t VA) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLines () const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByAddr (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findInlineeLinesByVA (uint64_t VA, uint32_t Length) const =0
virtual void getDataBytes (llvm::SmallVector< uint8_t, 32 > &bytes) const =0
virtual void getBackEndVersion (VersionInfo &Version) const =0
virtual PDB_MemberAccess getAccess () const =0
virtual uint32_t getAddressOffset () const =0
virtual uint32_t getAddressSection () const =0
virtual uint32_t getAge () const =0
virtual SymIndexId getArrayIndexTypeId () const =0
virtual uint32_t getBaseDataOffset () const =0
virtual uint32_t getBaseDataSlot () const =0
virtual SymIndexId getBaseSymbolId () const =0
virtual PDB_BuiltinType getBuiltinType () const =0
virtual uint32_t getBitPosition () const =0
virtual PDB_CallingConv getCallingConvention () const =0
virtual SymIndexId getClassParentId () const =0
virtual std::string getCompilerName () const =0
virtual uint32_t getCount () const =0
virtual uint32_t getCountLiveRanges () const =0
virtual void getFrontEndVersion (VersionInfo &Version) const =0
virtual PDB_Lang getLanguage () const =0
virtual SymIndexId getLexicalParentId () const =0
virtual std::string getLibraryName () const =0
virtual uint32_t getLiveRangeStartAddressOffset () const =0
virtual uint32_t getLiveRangeStartAddressSection () const =0
virtual uint32_t getLiveRangeStartRelativeVirtualAddress () const =0
virtual codeview::RegisterId getLocalBasePointerRegisterId () const =0
virtual SymIndexId getLowerBoundId () const =0
virtual uint32_t getMemorySpaceKind () const =0
virtual std::string getName () const =0
virtual uint32_t getNumberOfAcceleratorPointerTags () const =0
virtual uint32_t getNumberOfColumns () const =0
virtual uint32_t getNumberOfModifiers () const =0
virtual uint32_t getNumberOfRegisterIndices () const =0
virtual uint32_t getNumberOfRows () const =0
virtual std::string getObjectFileName () const =0
virtual uint32_t getOemId () const =0
virtual SymIndexId getOemSymbolId () const =0
virtual uint32_t getOffsetInUdt () const =0
virtual PDB_Cpu getPlatform () const =0
virtual uint32_t getRank () const =0
virtual codeview::RegisterId getRegisterId () const =0
virtual uint32_t getRegisterType () const =0
virtual uint32_t getRelativeVirtualAddress () const =0
virtual uint32_t getSamplerSlot () const =0
virtual uint32_t getSignature () const =0
virtual uint32_t getSizeInUdt () const =0
virtual uint32_t getSlot () const =0
virtual std::string getSourceFileName () const =0
virtual std::unique_ptr< IPDBLineNumber > getSrcLineOnTypeDefn () const =0
virtual uint32_t getStride () const =0
virtual SymIndexId getSubTypeId () const =0
virtual std::string getSymbolsFileName () const =0
virtual SymIndexId getSymIndexId () const =0
virtual uint32_t getTargetOffset () const =0
virtual uint32_t getTargetRelativeVirtualAddress () const =0
virtual uint64_t getTargetVirtualAddress () const =0
virtual uint32_t getTargetSection () const =0
virtual uint32_t getTextureSlot () const =0
virtual uint32_t getTimeStamp () const =0
virtual uint32_t getToken () const =0
virtual SymIndexId getTypeId () const =0
virtual uint32_t getUavSlot () const =0
virtual std::string getUndecoratedName () const =0
virtual std::string getUndecoratedNameEx (PDB_UndnameFlags Flags) const =0
virtual SymIndexId getUnmodifiedTypeId () const =0
virtual SymIndexId getUpperBoundId () const =0
virtual Variant getValue () const =0
virtual uint32_t getVirtualBaseDispIndex () const =0
virtual uint32_t getVirtualBaseOffset () const =0
virtual std::unique_ptr< PDBSymbolTypeBuiltin > getVirtualBaseTableType () const =0
virtual SymIndexId getVirtualTableShapeId () const =0
virtual PDB_DataKind getDataKind () const =0
virtual PDB_SymType getSymTag () const =0
virtual codeview::GUID getGuid () const =0
virtual int32_t getOffset () const =0
virtual int32_t getThisAdjust () const =0
virtual int32_t getVirtualBasePointerOffset () const =0
virtual PDB_LocType getLocationType () const =0
virtual PDB_Machine getMachineType () const =0
virtual codeview::ThunkOrdinal getThunkOrdinal () const =0
virtual uint64_t getLength () const =0
virtual uint64_t getLiveRangeLength () const =0
virtual uint64_t getVirtualAddress () const =0
virtual PDB_UdtType getUdtKind () const =0
virtual bool hasConstructor () const =0
virtual bool hasCustomCallingConvention () const =0
virtual bool hasFarReturn () const =0
virtual bool isCode () const =0
virtual bool isCompilerGenerated () const =0
virtual bool isConstType () const =0
virtual bool isEditAndContinueEnabled () const =0
virtual bool isFunction () const =0
virtual bool getAddressTaken () const =0
virtual bool getNoStackOrdering () const =0
virtual bool hasAlloca () const =0
virtual bool hasAssignmentOperator () const =0
virtual bool hasCTypes () const =0
virtual bool hasCastOperator () const =0
virtual bool hasDebugInfo () const =0
virtual bool hasEH () const =0
virtual bool hasEHa () const =0
virtual bool hasFramePointer () const =0
virtual bool hasInlAsm () const =0
virtual bool hasInlineAttribute () const =0
virtual bool hasInterruptReturn () const =0
virtual bool hasLongJump () const =0
virtual bool hasManagedCode () const =0
virtual bool hasNestedTypes () const =0
virtual bool hasNoInlineAttribute () const =0
virtual bool hasNoReturnAttribute () const =0
virtual bool hasOptimizedCodeDebugInfo () const =0
virtual bool hasOverloadedOperator () const =0
virtual bool hasSEH () const =0
virtual bool hasSecurityChecks () const =0
virtual bool hasSetJump () const =0
virtual bool hasStrictGSCheck () const =0
virtual bool isAcceleratorGroupSharedLocal () const =0
virtual bool isAcceleratorPointerTagLiveRange () const =0
virtual bool isAcceleratorStubFunction () const =0
virtual bool isAggregated () const =0
virtual bool isIntroVirtualFunction () const =0
virtual bool isCVTCIL () const =0
virtual bool isConstructorVirtualBase () const =0
virtual bool isCxxReturnUdt () const =0
virtual bool isDataAligned () const =0
virtual bool isHLSLData () const =0
virtual bool isHotpatchable () const =0
virtual bool isIndirectVirtualBaseClass () const =0
virtual bool isInterfaceUdt () const =0
virtual bool isIntrinsic () const =0
virtual bool isLTCG () const =0
virtual bool isLocationControlFlowDependent () const =0
virtual bool isMSILNetmodule () const =0
virtual bool isMatrixRowMajor () const =0
virtual bool isManagedCode () const =0
virtual bool isMSILCode () const =0
virtual bool isMultipleInheritance () const =0
virtual bool isNaked () const =0
virtual bool isNested () const =0
virtual bool isOptimizedAway () const =0
virtual bool isPacked () const =0
virtual bool isPointerBasedOnSymbolValue () const =0
virtual bool isPointerToDataMember () const =0
virtual bool isPointerToMemberFunction () const =0
virtual bool isPureVirtual () const =0
virtual bool isRValueReference () const =0
virtual bool isRefUdt () const =0
virtual bool isReference () const =0
virtual bool isRestrictedType () const =0
virtual bool isReturnValue () const =0
virtual bool isSafeBuffers () const =0
virtual bool isScoped () const =0
virtual bool isSdl () const =0
virtual bool isSingleInheritance () const =0
virtual bool isSplitted () const =0
virtual bool isStatic () const =0
virtual bool hasPrivateSymbols () const =0
virtual bool isUnalignedType () const =0
virtual bool isUnreached () const =0
virtual bool isValueUdt () const =0
virtual bool isVirtual () const =0
virtual bool isVirtualBaseClass () const =0
virtual bool isVirtualInheritance () const =0
virtual bool isVolatileType () const =0
virtual bool wasInlined () const =0
virtual std::string getUnused () const =0
Protected Member Functions
bool isMemberPointer () const
Protected Attributes
codeview::TypeIndex TI
Optional< codeview::PointerRecord > Record
Protected Attributes inherited from llvm::pdb::NativeRawSymbol
NativeSession & Session
PDB_SymType Tag
SymIndexId SymbolId
Detailed Description
Definition at line 21 of file NativeTypePointer.h.
Constructor & Destructor Documentation
NativeTypePointer() [1/2]
NativeTypePointer::NativeTypePointer (NativeSession & Session, SymIndexId Id, codeview::TypeIndex TI)
Definition at line 19 of file NativeTypePointer.cpp.
References assert(), llvm::codeview::TypeIndex::getSimpleMode(), llvm::codeview::TypeIndex::isSimple(), and TI.
NativeTypePointer() [2/2]
NativeTypePointer::NativeTypePointer (NativeSession & Session, SymIndexId Id, codeview::TypeIndex TI, codeview::PointerRecord PR)
Definition at line 26 of file NativeTypePointer.cpp.
~NativeTypePointer()
NativeTypePointer::~NativeTypePointer () override
Definition at line 32 of file NativeTypePointer.cpp.
Member Function Documentation
dump()
void NativeTypePointer::dump (raw_ostream & OS, int Indent, PdbSymbolIdField ShowIdFields, PdbSymbolIdField RecurseIdFields) const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 34 of file NativeTypePointer.cpp.
References llvm::pdb::ClassParent, llvm::AliasSet::dump(), llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), getClassParentId(), getLength(), getTypeId(), isConstType(), isMemberPointer(), isMultipleInheritance(), isPointerToDataMember(), isPointerToMemberFunction(), isReference(), isRestrictedType(), isRValueReference(), isSingleInheritance(), isUnalignedType(), isVirtualInheritance(), isVolatileType(), llvm::pdb::LexicalParent, llvm::pdb::NativeRawSymbol::Session, and llvm::pdb::Type.
getClassParentId()
SymIndexId NativeTypePointer::getClassParentId () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 69 of file NativeTypePointer.cpp.
References assert(), llvm::codeview::MemberPointerInfo::ContainingType, llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::pdb::NativeSession::getSymbolCache(), isMemberPointer(), Record, and llvm::pdb::NativeRawSymbol::Session.
Referenced by dump().
getLength()
uint64_t NativeTypePointer::getLength () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 78 of file NativeTypePointer.cpp.
References assert(), llvm::codeview::TypeIndex::getSimpleMode(), Record, and TI.
Referenced by dump().
getTypeId()
SymIndexId NativeTypePointer::getTypeId () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 100 of file NativeTypePointer.cpp.
References llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::pdb::NativeSession::getSymbolCache(), llvm::codeview::TypeIndex::makeDirect(), Record, llvm::pdb::NativeRawSymbol::Session, and TI.
Referenced by dump().
isConstType()
bool NativeTypePointer::isConstType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 131 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
isMemberPointer()
bool NativeTypePointer::isMemberPointer () const protected
Definition at line 191 of file NativeTypePointer.cpp.
References isPointerToDataMember(), and isPointerToMemberFunction().
Referenced by dump(), getClassParentId(), isMultipleInheritance(), isSingleInheritance(), and isVirtualInheritance().
isMultipleInheritance()
bool NativeTypePointer::isMultipleInheritance () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 173 of file NativeTypePointer.cpp.
References isInheritanceKind(), isMemberPointer(), and Record.
Referenced by dump().
isPointerToDataMember()
bool NativeTypePointer::isPointerToDataMember () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 119 of file NativeTypePointer.cpp.
References Record.
Referenced by dump(), and isMemberPointer().
isPointerToMemberFunction()
bool NativeTypePointer::isPointerToMemberFunction () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 125 of file NativeTypePointer.cpp.
References Record.
Referenced by dump(), and isMemberPointer().
isReference()
bool NativeTypePointer::isReference () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 107 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
isRestrictedType()
bool NativeTypePointer::isRestrictedType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 137 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
isRValueReference()
bool NativeTypePointer::isRValueReference () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 113 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
isSingleInheritance()
bool NativeTypePointer::isSingleInheritance () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 164 of file NativeTypePointer.cpp.
References isInheritanceKind(), isMemberPointer(), and Record.
Referenced by dump().
isUnalignedType()
bool NativeTypePointer::isUnalignedType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 151 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
isVirtualInheritance()
bool NativeTypePointer::isVirtualInheritance () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 182 of file NativeTypePointer.cpp.
References isInheritanceKind(), isMemberPointer(), and Record.
Referenced by dump().
isVolatileType()
bool NativeTypePointer::isVolatileType () const override virtual
Reimplemented from llvm::pdb::NativeRawSymbol.
Definition at line 144 of file NativeTypePointer.cpp.
References Record.
Referenced by dump().
Member Data Documentation
Record
Optional<codeview::PointerRecord> llvm::pdb::NativeTypePointer::Record protected
Definition at line 54 of file NativeTypePointer.h.
Referenced by getClassParentId(), getLength(), getTypeId(), isConstType(), isMultipleInheritance(), isPointerToDataMember(), isPointerToMemberFunction(), isReference(), isRestrictedType(), isRValueReference(), isSingleInheritance(), isUnalignedType(), isVirtualInheritance(), and isVolatileType().
TI
codeview::TypeIndex llvm::pdb::NativeTypePointer::TI protected
Definition at line 53 of file NativeTypePointer.h.
Referenced by getLength(), getTypeId(), and NativeTypePointer().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeTypePointer.h
lib/DebugInfo/PDB/Native/NativeTypePointer.cpp