LLVM: llvm::CoroBeginInst Class Reference
llvm::CoroBeginInst Class Reference
This class represents the llvm.coro.begin instruction.
#include "Transforms/Coroutines/CoroInstr.h"
Public Member Functions
CoroIdInst * getId () const
Value * getMem () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Detailed Description
This class represents the llvm.coro.begin instruction.
Definition at line 214 of file CoroInstr.h.
Member Function Documentation
classof() [1/2]
static bool llvm::CoroBeginInst::classof (const IntrinsicInst * I) inline static
Definition at line 223 of file CoroInstr.h.
References I.
classof() [2/2]
static bool llvm::CoroBeginInst::classof (const Value * V) inline static
Definition at line 226 of file CoroInstr.h.
getId()
CoroIdInst * llvm::CoroBeginInst::getId () const inline
Definition at line 218 of file CoroInstr.h.
Referenced by llvm::coro::buildCoroutineFrame(), createClone(), handleNoSuspendCoroutine(), setCoroInfo(), and updateCoroFrame().
getMem()
Value * llvm::CoroBeginInst::getMem () const inline
Definition at line 220 of file CoroInstr.h.
Referenced by handleNoSuspendCoroutine().
The documentation for this class was generated from the following file:
lib/Transforms/Coroutines/CoroInstr.h