LLVM: llvm::msf::WritableMappedBlockStream Class Reference
llvm::msf::WritableMappedBlockStream Class Reference
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
Public Member Functions
support::endianness getEndian () const override
Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream, read as much as possible without copying any data.
uint32_t getLength () override
Return the number of bytes of data in this stream.
Error writeBytes (uint32_t Offset, ArrayRef< uint8_t > Buffer) override
Attempt to write the given bytes into the stream at the desired offset.
Error commit () override
For buffered streams, commits changes to the backing store.
const MSFStreamLayout & getStreamLayout () const
uint32_t getBlockSize () const
uint32_t getNumBlocks () const
uint32_t getStreamLength () const
Public Member Functions inherited from llvm::WritableBinaryStream
~WritableBinaryStream () override=default
virtual Error writeBytes (uint32_t Offset, ArrayRef< uint8_t > Data)=0
Attempt to write the given bytes into the stream at the desired offset.
virtual Error commit ()=0
For buffered streams, commits changes to the backing store.
BinaryStreamFlags getFlags () const override
Return the properties of this stream.
Public Member Functions inherited from llvm::BinaryStream
virtual ~BinaryStream ()=default
virtual llvm::support::endianness getEndian () const =0
virtual Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
virtual Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream, read as much as possible without copying any data.
virtual uint32_t getLength ()=0
Return the number of bytes of data in this stream.
virtual BinaryStreamFlags getFlags () const
Return the properties of this stream.
Static Public Member Functions
static std::unique_ptr< WritableMappedBlockStream > createStream (uint32_t BlockSize, const MSFStreamLayout &Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
static std::unique_ptr< WritableMappedBlockStream > createIndexedStream (const MSFLayout &Layout, WritableBinaryStreamRef MsfData, uint32_t StreamIndex, BumpPtrAllocator &Allocator)
static std::unique_ptr< WritableMappedBlockStream > createDirectoryStream (const MSFLayout &Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
static std::unique_ptr< WritableMappedBlockStream > createFpmStream (const MSFLayout &Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator &Allocator, bool AltFpm=false)
Protected Member Functions
WritableMappedBlockStream (uint32_t BlockSize, const MSFStreamLayout &StreamLayout, WritableBinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
Protected Member Functions inherited from llvm::WritableBinaryStream
Error checkOffsetForWrite (uint32_t Offset, uint32_t DataSize)
Protected Member Functions inherited from llvm::BinaryStream
Error checkOffsetForRead (uint32_t Offset, uint32_t DataSize)
Detailed Description
Definition at line 107 of file MappedBlockStream.h.
Constructor & Destructor Documentation
WritableMappedBlockStream()
WritableMappedBlockStream::WritableMappedBlockStream (uint32_t BlockSize, const MSFStreamLayout & StreamLayout, WritableBinaryStreamRef MsfData, BumpPtrAllocator & Allocator) protected
Definition at line 310 of file MappedBlockStream.cpp.
Member Function Documentation
commit()
Error WritableMappedBlockStream::commit () override virtual
For buffered streams, commits changes to the backing store.
Implements llvm::WritableBinaryStream.
Definition at line 421 of file MappedBlockStream.cpp.
References llvm::WritableBinaryStreamRef::commit().
createDirectoryStream()
std::unique_ptr< WritableMappedBlockStream > WritableMappedBlockStream::createDirectoryStream (const MSFLayout & Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator & Allocator) static
Definition at line 338 of file MappedBlockStream.cpp.
References llvm::msf::MSFStreamLayout::Blocks, llvm::msf::SuperBlock::BlockSize, createStream(), llvm::msf::MSFLayout::DirectoryBlocks, llvm::msf::MSFStreamLayout::Length, llvm::msf::SuperBlock::NumDirectoryBytes, and llvm::msf::MSFLayout::SB.
Referenced by llvm::msf::MSFBuilder::commit().
createFpmStream()
std::unique_ptr< WritableMappedBlockStream > WritableMappedBlockStream::createFpmStream (const MSFLayout & Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator & Allocator, bool AltFpm = false) static
Definition at line 348 of file MappedBlockStream.cpp.
References llvm::msf::SuperBlock::BlockSize, llvm::BinaryStreamWriter::bytesRemaining(), llvm::cantFail(), createStream(), llvm::msf::getFpmStreamLayout(), llvm::msf::MSFLayout::SB, and llvm::BinaryStreamWriter::writeBytes().
Referenced by commitFpm().
createIndexedStream()
std::unique_ptr< WritableMappedBlockStream > WritableMappedBlockStream::createIndexedStream (const MSFLayout & Layout, WritableBinaryStreamRef MsfData, uint32_t StreamIndex, BumpPtrAllocator & Allocator) static
Definition at line 326 of file MappedBlockStream.cpp.
References assert(), llvm::msf::MSFStreamLayout::Blocks, llvm::msf::SuperBlock::BlockSize, createStream(), llvm::msf::MSFStreamLayout::Length, llvm::msf::MSFLayout::SB, llvm::msf::MSFLayout::StreamMap, and llvm::msf::MSFLayout::StreamSizes.
Referenced by llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::GSIStreamBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), and llvm::pdb::PDBFileBuilder::commit().
createStream()
std::unique_ptr< WritableMappedBlockStream > WritableMappedBlockStream::createStream (uint32_t BlockSize, const MSFStreamLayout & Layout, WritableBinaryStreamRef MsfData, BumpPtrAllocator & Allocator) static
Definition at line 317 of file MappedBlockStream.cpp.
References BlockSize.
Referenced by createDirectoryStream(), createFpmStream(), and createIndexedStream().
getBlockSize()
uint32_t llvm::msf::WritableMappedBlockStream::getBlockSize () const inline
Definition at line 144 of file MappedBlockStream.h.
References llvm::msf::MappedBlockStream::getBlockSize().
Referenced by writeBytes().
getEndian()
support::endianness llvm::msf::WritableMappedBlockStream::getEndian () const inline override virtual
Implements llvm::BinaryStream.
Definition at line 126 of file MappedBlockStream.h.
References llvm::support::little.
getLength()
uint32_t WritableMappedBlockStream::getLength () override virtual
Return the number of bytes of data in this stream.
Implements llvm::BinaryStream.
Definition at line 383 of file MappedBlockStream.cpp.
References llvm::msf::MappedBlockStream::getLength().
getNumBlocks()
uint32_t llvm::msf::WritableMappedBlockStream::getNumBlocks () const inline
Definition at line 145 of file MappedBlockStream.h.
References llvm::msf::MappedBlockStream::getNumBlocks().
getStreamLayout()
const MSFStreamLayout & llvm::msf::WritableMappedBlockStream::getStreamLayout () const inline
Definition at line 140 of file MappedBlockStream.h.
Referenced by writeBytes().
getStreamLength()
uint32_t llvm::msf::WritableMappedBlockStream::getStreamLength () const inline
Definition at line 146 of file MappedBlockStream.h.
References llvm::msf::MappedBlockStream::getStreamLength().
readBytes()
Error WritableMappedBlockStream::readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > & Buffer) override virtual
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Implements llvm::BinaryStream.
Definition at line 373 of file MappedBlockStream.cpp.
References llvm::msf::MappedBlockStream::readBytes().
readLongestContiguousChunk()
Error WritableMappedBlockStream::readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > & Buffer) override virtual
Given an offset into the stream, read as much as possible without copying any data.
Implements llvm::BinaryStream.
Definition at line 378 of file MappedBlockStream.cpp.
References llvm::msf::MappedBlockStream::readLongestContiguousChunk().
writeBytes()
Error WritableMappedBlockStream::writeBytes (uint32_t Offset, ArrayRef< uint8_t > Data) override virtual
Attempt to write the given bytes into the stream at the desired offset.
This will always necessitate a copy. Cannot shrink or grow the stream, only writes into existing allocated space.
Implements llvm::WritableBinaryStream.
Definition at line 387 of file MappedBlockStream.cpp.
References llvm::msf::MSFStreamLayout::Blocks, llvm::msf::blockToOffset(), llvm::WritableBinaryStream::checkOffsetForWrite(), getBlockSize(), getStreamLayout(), llvm::Error::success(), and llvm::WritableBinaryStreamRef::writeBytes().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/MSF/MappedBlockStream.h
lib/DebugInfo/MSF/MappedBlockStream.cpp