LLVM: llvm::CoroSuspendInst Class Reference
llvm::CoroSuspendInst Class Reference
This represents the llvm.coro.suspend instruction.
#include "Transforms/Coroutines/CoroInstr.h"
Public Member Functions
CoroSaveInst * getCoroSave () const
bool isFinal () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Detailed Description
This represents the llvm.coro.suspend instruction.
Definition at line 265 of file CoroInstr.h.
Member Function Documentation
classof() [1/2]
static bool llvm::CoroSuspendInst::classof (const IntrinsicInst * I) inline static
Definition at line 281 of file CoroInstr.h.
References I.
classof() [2/2]
static bool llvm::CoroSuspendInst::classof (const Value * V) inline static
Definition at line 284 of file CoroInstr.h.
getCoroSave()
CoroSaveInst * llvm::CoroSuspendInst::getCoroSave () const inline
Definition at line 269 of file CoroInstr.h.
References assert().
Referenced by llvm::coro::buildCoroutineFrame(), createCoroSave(), createResumeEntryBlock(), and simplifySuspendPoint().
isFinal()
bool llvm::CoroSuspendInst::isFinal () const inline
Definition at line 276 of file CoroInstr.h.
Referenced by createResumeEntryBlock().
The documentation for this class was generated from the following file:
lib/Transforms/Coroutines/CoroInstr.h