LLVM: llvm::VPInterleaveRecipe Class Reference
llvm::VPInterleaveRecipe Class Reference
VPInterleaveRecipe is a recipe for transforming an interleave group of load or stores into one wide load/store and shuffles.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPInterleaveRecipe (const InterleaveGroup< Instruction > *IG, VPValue *Mask)
~VPInterleaveRecipe () override=default
void execute (VPTransformState &State) override
Generate the wide load or store, and shuffles.
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
const InterleaveGroup< Instruction > * getInterleaveGroup ()
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Detailed Description
VPInterleaveRecipe is a recipe for transforming an interleave group of load or stores into one wide load/store and shuffles.
Definition at line 818 of file VPlan.h.
Constructor & Destructor Documentation
VPInterleaveRecipe()
llvm::VPInterleaveRecipe::VPInterleaveRecipe (const InterleaveGroup< Instruction > * IG, VPValue * Mask) inline
Definition at line 824 of file VPlan.h.
~VPInterleaveRecipe()
llvm::VPInterleaveRecipe::~VPInterleaveRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPInterleaveRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 832 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPInterleaveRecipe::execute (VPTransformState & State) override virtual
Generate the wide load or store, and shuffles.
Implements llvm::VPRecipeBase.
Definition at line 7094 of file LoopVectorize.cpp.
References assert(), llvm::VPTransformState::get(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::VPTransformState::ILV, llvm::VPTransformState::Instance, llvm::VPTransformState::UF, and llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
getInterleaveGroup()
const InterleaveGroup< Instruction > * llvm::VPInterleaveRecipe::getInterleaveGroup () inline
Definition at line 842 of file VPlan.h.
print()
void VPInterleaveRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 7026 of file LoopVectorize.cpp.
References llvm::InterleaveGroup< InstTy >::getFactor(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::InterleaveGroup< InstTy >::getMember(), llvm::User::getOperand(), I, and llvm::Value::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp