LLVM: llvm::object::COFFSymbolRef Class Reference
llvm::object::COFFSymbolRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
COFFSymbolRef ()=default
COFFSymbolRef (const coff_symbol16 *CS)
COFFSymbolRef (const coff_symbol32 *CS)
const void * getRawPtr () const
const coff_symbol_generic * getGeneric () const
bool isBigObj () const
const char * getShortName () const
const StringTableOffset & getStringTableOffset () const
uint32_t getValue () const
int32_t getSectionNumber () const
uint16_t getType () const
uint8_t getStorageClass () const
uint8_t getNumberOfAuxSymbols () const
uint8_t getBaseType () const
uint8_t getComplexType () const
template<typename T >
const T * getAux () const
const coff_aux_section_definition * getSectionDefinition () const
const coff_aux_weak_external * getWeakExternal () const
bool isAbsolute () const
bool isExternal () const
bool isCommon () const
bool isUndefined () const
bool isWeakExternal () const
bool isFunctionDefinition () const
bool isFunctionLineInfo () const
bool isAnyUndefined () const
bool isFileRecord () const
bool isSection () const
bool isSectionDefinition () const
bool isCLRToken () const
Friends
bool operator< (COFFSymbolRef A, COFFSymbolRef B)
Detailed Description
Definition at line 280 of file COFF.h.
Constructor & Destructor Documentation
COFFSymbolRef() [1/3]
llvm::object::COFFSymbolRef::COFFSymbolRef () default
COFFSymbolRef() [2/3]
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol16 * CS) inline
Definition at line 283 of file COFF.h.
COFFSymbolRef() [3/3]
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol32 * CS) inline
Definition at line 284 of file COFF.h.
Member Function Documentation
getAux()
template<typename T > const T * llvm::object::COFFSymbolRef::getAux () const inline
Definition at line 351 of file COFF.h.
getBaseType()
uint8_t llvm::object::COFFSymbolRef::getBaseType () const inline
Definition at line 345 of file COFF.h.
References getType().
Referenced by isFunctionDefinition().
getComplexType()
uint8_t llvm::object::COFFSymbolRef::getComplexType () const inline
Definition at line 347 of file COFF.h.
References getType(), and llvm::COFF::SCT_COMPLEX_TYPE_SHIFT.
Referenced by llvm::object::COFFObjectFile::getSymbolType(), and isFunctionDefinition().
getGeneric()
const coff_symbol_generic * llvm::object::COFFSymbolRef::getGeneric () const inline
Definition at line 290 of file COFF.h.
getNumberOfAuxSymbols()
uint8_t llvm::object::COFFSymbolRef::getNumberOfAuxSymbols () const inline
Definition at line 340 of file COFF.h.
References assert(), and llvm::object::coff_symbol< SectionNumberType >::NumberOfAuxSymbols.
Referenced by getSectionDefinition(), getWeakExternal(), and isSectionDefinition().
getRawPtr()
const void * llvm::object::COFFSymbolRef::getRawPtr () const inline
Definition at line 286 of file COFF.h.
getSectionDefinition()
const coff_aux_section_definition * llvm::object::COFFSymbolRef::getSectionDefinition () const inline
Definition at line 356 of file COFF.h.
References getNumberOfAuxSymbols(), getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_STATIC.
getSectionNumber()
int32_t llvm::object::COFFSymbolRef::getSectionNumber () const inline
Definition at line 319 of file COFF.h.
References assert(), llvm::COFF::MaxNumberOfSections16, and llvm::object::coff_symbol< SectionNumberType >::SectionNumber.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), llvm::object::COFFObjectFile::getSymbolSection(), llvm::object::COFFObjectFile::getSymbolSectionID(), llvm::object::COFFObjectFile::getSymbolType(), isAbsolute(), isCommon(), isFunctionDefinition(), isSectionDefinition(), and isUndefined().
getShortName()
const char * llvm::object::COFFSymbolRef::getShortName () const inline
Definition at line 308 of file COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Name, and llvm::object::coff_symbol< SectionNumberType >::ShortName.
getStorageClass()
uint8_t llvm::object::COFFSymbolRef::getStorageClass () const inline
Definition at line 335 of file COFF.h.
References assert(), and llvm::object::coff_symbol< SectionNumberType >::StorageClass.
Referenced by getSectionDefinition(), getWeakExternal(), isCLRToken(), isExternal(), isFileRecord(), isFunctionLineInfo(), isSection(), isSectionDefinition(), and isWeakExternal().
getStringTableOffset()
const StringTableOffset & llvm::object::COFFSymbolRef::getStringTableOffset () const inline
Definition at line 312 of file COFF.h.
References assert(), llvm::object::coff_symbol< SectionNumberType >::Name, and llvm::object::coff_symbol< SectionNumberType >::Offset.
getType()
uint16_t llvm::object::COFFSymbolRef::getType () const inline
Definition at line 330 of file COFF.h.
References assert(), and llvm::object::coff_symbol< SectionNumberType >::Type.
Referenced by getBaseType(), and getComplexType().
getValue()
uint32_t llvm::object::COFFSymbolRef::getValue () const inline
Definition at line 317 of file COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Value.
Referenced by llvm::object::COFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::COFFObjectFile::getSymbolAlignment(), llvm::object::COFFObjectFile::getSymbolValueImpl(), isCommon(), and isUndefined().
getWeakExternal()
const coff_aux_weak_external * llvm::object::COFFSymbolRef::getWeakExternal () const inline
Definition at line 363 of file COFF.h.
References getNumberOfAuxSymbols(), getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags().
isAbsolute()
bool llvm::object::COFFSymbolRef::isAbsolute () const inline
Definition at line 370 of file COFF.h.
References getSectionNumber().
isAnyUndefined()
bool llvm::object::COFFSymbolRef::isAnyUndefined () const inline
Definition at line 402 of file COFF.h.
References isUndefined(), and isWeakExternal().
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), and llvm::object::COFFObjectFile::getSymbolType().
isBigObj()
bool llvm::object::COFFSymbolRef::isBigObj () const inline
Definition at line 300 of file COFF.h.
References llvm_unreachable.
isCLRToken()
bool llvm::object::COFFSymbolRef::isCLRToken () const inline
Definition at line 426 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_CLR_TOKEN.
isCommon()
bool llvm::object::COFFSymbolRef::isCommon () const inline
Definition at line 378 of file COFF.h.
References getSectionNumber(), getValue(), llvm::COFF::IMAGE_SYM_UNDEFINED, and isExternal().
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isExternal()
bool llvm::object::COFFSymbolRef::isExternal () const inline
Definition at line 374 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), isCommon(), isFunctionDefinition(), and isUndefined().
isFileRecord()
bool llvm::object::COFFSymbolRef::isFileRecord () const inline
Definition at line 406 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_FILE.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isFunctionDefinition()
bool llvm::object::COFFSymbolRef::isFunctionDefinition () const inline
Definition at line 392 of file COFF.h.
References getBaseType(), getComplexType(), getSectionNumber(), llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::COFF::IMAGE_SYM_TYPE_NULL, isExternal(), and llvm::COFF::isReservedSectionNumber().
isFunctionLineInfo()
bool llvm::object::COFFSymbolRef::isFunctionLineInfo () const inline
Definition at line 398 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_FUNCTION.
isSection()
bool llvm::object::COFFSymbolRef::isSection () const inline
Definition at line 410 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_SECTION.
isSectionDefinition()
bool llvm::object::COFFSymbolRef::isSectionDefinition () const inline
Definition at line 414 of file COFF.h.
References getNumberOfAuxSymbols(), getSectionNumber(), getStorageClass(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, and llvm::COFF::IMAGE_SYM_CLASS_STATIC.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
isUndefined()
bool llvm::object::COFFSymbolRef::isUndefined () const inline
Definition at line 383 of file COFF.h.
References getSectionNumber(), getValue(), llvm::COFF::IMAGE_SYM_UNDEFINED, and isExternal().
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and isAnyUndefined().
isWeakExternal()
bool llvm::object::COFFSymbolRef::isWeakExternal () const inline
Definition at line 388 of file COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and isAnyUndefined().
Friends And Related Function Documentation
operator<
bool operator< (COFFSymbolRef A, COFFSymbolRef B) friend
Definition at line 296 of file COFF.h.
The documentation for this class was generated from the following file:
include/llvm/Object/COFF.h