LLVM: llvm::ScopedHashTableVal< K, V > Class Template Reference
llvm::ScopedHashTableVal< K, V > Class Template Reference
#include "llvm/ADT/ScopedHashTable.h"
Public Member Functions
const K & getKey () const
const V & getValue () const
V & getValue ()
ScopedHashTableVal * getNextForKey ()
const ScopedHashTableVal * getNextForKey () const
ScopedHashTableVal * getNextInScope ()
template<typename AllocatorTy >
void Destroy (AllocatorTy &Allocator)
Static Public Member Functions
template<typename AllocatorTy >
static ScopedHashTableVal * Create (ScopedHashTableVal *nextInScope, ScopedHashTableVal *nextForKey, const K &key, const V &val, AllocatorTy &Allocator)
Detailed Description
template<typename K, typename V>
class llvm::ScopedHashTableVal< K, V >
Definition at line 46 of file ScopedHashTable.h.
Member Function Documentation
Create()
template<typename K , typename V > template<typename AllocatorTy > static ScopedHashTableVal * llvm::ScopedHashTableVal< K, V >::Create (ScopedHashTableVal< K, V > * nextInScope, ScopedHashTableVal< K, V > * nextForKey, const K & key, const V & val, AllocatorTy & Allocator) inline static
Definition at line 64 of file ScopedHashTable.h.
References Allocator.
Referenced by llvm::ExecutionEngine::getMemoryForGV(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insertIntoScope(), and matchRotate().
Destroy()
template<typename K , typename V > template<typename AllocatorTy > void llvm::ScopedHashTableVal< K, V >::Destroy (AllocatorTy & Allocator) inline
Definition at line 76 of file ScopedHashTable.h.
References Allocator.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
getKey()
template<typename K , typename V > const K & llvm::ScopedHashTableVal< K, V >::getKey () const inline
Definition at line 55 of file ScopedHashTable.h.
getNextForKey() [1/2]
template<typename K , typename V > ScopedHashTableVal * llvm::ScopedHashTableVal< K, V >::getNextForKey () inline
Definition at line 59 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
getNextForKey() [2/2]
template<typename K , typename V > const ScopedHashTableVal * llvm::ScopedHashTableVal< K, V >::getNextForKey () const inline
Definition at line 60 of file ScopedHashTable.h.
getNextInScope()
template<typename K , typename V > ScopedHashTableVal * llvm::ScopedHashTableVal< K, V >::getNextInScope () inline
Definition at line 61 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
getValue() [1/2]
template<typename K , typename V > V & llvm::ScopedHashTableVal< K, V >::getValue () inline
Definition at line 57 of file ScopedHashTable.h.
getValue() [2/2]
template<typename K , typename V > const V & llvm::ScopedHashTableVal< K, V >::getValue () const inline
Definition at line 56 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ScopedHashTable.h