LLVM: llvm::FileBufferByteStream Class Reference
llvm::FileBufferByteStream Class Reference
An implementation of WritableBinaryStream backed by an llvm FileOutputBuffer.
#include "llvm/Support/BinaryByteStream.h"
Public Member Functions
FileBufferByteStream (std::unique_ptr< FileOutputBuffer > Buffer, llvm::support::endianness Endian)
llvm::support::endianness getEndian () const override
Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream, read as much as possible without copying any data.
uint32_t getLength () override
Return the number of bytes of data in this stream.
Error writeBytes (uint32_t Offset, ArrayRef< uint8_t > Data) override
Attempt to write the given bytes into the stream at the desired offset.
Error commit () override
For buffered streams, commits changes to the backing store.
uint8_t * getBufferStart () const
Returns a pointer to the start of the buffer.
uint8_t * getBufferEnd () const
Returns a pointer to the end of the buffer.
Public Member Functions inherited from llvm::WritableBinaryStream
~WritableBinaryStream () override=default
virtual Error writeBytes (uint32_t Offset, ArrayRef< uint8_t > Data)=0
Attempt to write the given bytes into the stream at the desired offset.
virtual Error commit ()=0
For buffered streams, commits changes to the backing store.
BinaryStreamFlags getFlags () const override
Return the properties of this stream.
Public Member Functions inherited from llvm::BinaryStream
virtual ~BinaryStream ()=default
virtual llvm::support::endianness getEndian () const =0
virtual Error readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
virtual Error readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > &Buffer)=0
Given an offset into the stream, read as much as possible without copying any data.
virtual uint32_t getLength ()=0
Return the number of bytes of data in this stream.
virtual BinaryStreamFlags getFlags () const
Return the properties of this stream.
Additional Inherited Members
Protected Member Functions inherited from llvm::WritableBinaryStream
Error checkOffsetForWrite (uint32_t Offset, uint32_t DataSize)
Protected Member Functions inherited from llvm::BinaryStream
Error checkOffsetForRead (uint32_t Offset, uint32_t DataSize)
Detailed Description
An implementation of WritableBinaryStream backed by an llvm FileOutputBuffer.
Definition at line 205 of file BinaryByteStream.h.
Constructor & Destructor Documentation
FileBufferByteStream()
llvm::FileBufferByteStream::FileBufferByteStream (std::unique_ptr< FileOutputBuffer > Buffer, llvm::support::endianness Endian) inline
Definition at line 235 of file BinaryByteStream.h.
Member Function Documentation
commit()
Error llvm::FileBufferByteStream::commit () inline override virtual
For buffered streams, commits changes to the backing store.
Implements llvm::WritableBinaryStream.
Definition at line 259 of file BinaryByteStream.h.
Referenced by llvm::pdb::PDBFileBuilder::commit().
getBufferEnd()
uint8_t * llvm::FileBufferByteStream::getBufferEnd () const inline
Returns a pointer to the end of the buffer.
Definition at line 265 of file BinaryByteStream.h.
Referenced by llvm::pdb::PDBFileBuilder::commit().
getBufferStart()
uint8_t * llvm::FileBufferByteStream::getBufferStart () const inline
Returns a pointer to the start of the buffer.
Definition at line 262 of file BinaryByteStream.h.
Referenced by llvm::pdb::PDBFileBuilder::commit().
getEndian()
llvm::support::endianness llvm::FileBufferByteStream::getEndian () const inline override virtual
Implements llvm::BinaryStream.
Definition at line 239 of file BinaryByteStream.h.
getLength()
uint32_t llvm::FileBufferByteStream::getLength () inline override virtual
Return the number of bytes of data in this stream.
Implements llvm::BinaryStream.
Definition at line 253 of file BinaryByteStream.h.
readBytes()
Error llvm::FileBufferByteStream::readBytes (uint32_t Offset, uint32_t Size, ArrayRef< uint8_t > & Buffer) inline override virtual
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Implements llvm::BinaryStream.
Definition at line 243 of file BinaryByteStream.h.
readLongestContiguousChunk()
Error llvm::FileBufferByteStream::readLongestContiguousChunk (uint32_t Offset, ArrayRef< uint8_t > & Buffer) inline override virtual
Given an offset into the stream, read as much as possible without copying any data.
Implements llvm::BinaryStream.
Definition at line 248 of file BinaryByteStream.h.
writeBytes()
Error llvm::FileBufferByteStream::writeBytes (uint32_t Offset, ArrayRef< uint8_t > Data) inline override virtual
Attempt to write the given bytes into the stream at the desired offset.
This will always necessitate a copy. Cannot shrink or grow the stream, only writes into existing allocated space.
Implements llvm::WritableBinaryStream.
Definition at line 255 of file BinaryByteStream.h.
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryByteStream.h