LLVM: llvm::ScalarEvolution Class Reference
llvm::ScalarEvolution Class Reference
The main scalar evolution driver.
#include "llvm/Analysis/ScalarEvolution.h"
Public Types
enum LoopDisposition { LoopVariant , LoopInvariant , LoopComputable }
An enum describing the relationship between a SCEV and a loop.
enum BlockDisposition { DoesNotDominateBlock , DominatesBlock , ProperlyDominatesBlock }
An enum describing the relationship between a SCEV and a basic block.
Public Member Functions
ScalarEvolution (Function &F, TargetLibraryInfo &TLI, AssumptionCache &AC, DominatorTree &DT, LoopInfo &LI)
ScalarEvolution (ScalarEvolution &&Arg)
~ScalarEvolution ()
LLVMContext & getContext () const
bool isSCEVable (Type *Ty) const
Test if values of the given type are analyzable within the SCEV framework.
uint64_t getTypeSizeInBits (Type *Ty) const
Return the size in bits of the specified type, for which isSCEVable must return true.
Type * getEffectiveSCEVType (Type *Ty) const
Return a type with the same bitwidth as the given type and which represents how SCEV will treat the given type, for which isSCEVable must return true.
Type * getWiderType (Type *Ty1, Type *Ty2) const
bool containsAddRecurrence (const SCEV *S)
Return true if the SCEV is a scAddRecExpr or it contains scAddRecExpr.
void eraseValueFromMap (Value *V)
Erase Value from ValueExprMap and ExprValueMap.
const SCEV * getSCEV (Value *V)
Return a SCEV expression for the full generality of the specified expression.
const SCEV * getConstant (ConstantInt *V)
const SCEV * getConstant (const APInt &Val)
const SCEV * getConstant (Type *Ty, uint64_t V, bool isSigned=false)
const SCEV * getTruncateExpr (const SCEV *Op, Type *Ty, unsigned Depth=0)
const SCEV * getZeroExtendExpr (const SCEV *Op, Type *Ty, unsigned Depth=0)
const SCEV * getSignExtendExpr (const SCEV *Op, Type *Ty, unsigned Depth=0)
const SCEV * getAnyExtendExpr (const SCEV *Op, Type *Ty)
getAnyExtendExpr - Return a SCEV for the given operand extended with unspecified bits out to the given type.
const SCEV * getAddExpr (SmallVectorImpl< const SCEV * > &Ops, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
Get a canonical add expression, or something simpler if possible.
const SCEV * getAddExpr (const SCEV *LHS, const SCEV *RHS, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
const SCEV * getAddExpr (const SCEV *Op0, const SCEV *Op1, const SCEV *Op2, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
const SCEV * getMulExpr (SmallVectorImpl< const SCEV * > &Ops, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
Get a canonical multiply expression, or something simpler if possible.
const SCEV * getMulExpr (const SCEV *LHS, const SCEV *RHS, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
const SCEV * getMulExpr (const SCEV *Op0, const SCEV *Op1, const SCEV *Op2, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
const SCEV * getUDivExpr (const SCEV *LHS, const SCEV *RHS)
Get a canonical unsigned division expression, or something simpler if possible.
const SCEV * getUDivExactExpr (const SCEV *LHS, const SCEV *RHS)
Get a canonical unsigned division expression, or something simpler if possible.
const SCEV * getURemExpr (const SCEV *LHS, const SCEV *RHS)
Represents an unsigned remainder expression based on unsigned division.
const SCEV * getAddRecExpr (const SCEV *Start, const SCEV *Step, const Loop *L, SCEV::NoWrapFlags Flags)
Get an add recurrence expression for the specified loop.
const SCEV * getAddRecExpr (SmallVectorImpl< const SCEV * > &Operands, const Loop *L, SCEV::NoWrapFlags Flags)
Get an add recurrence expression for the specified loop.
const SCEV * getAddRecExpr (const SmallVectorImpl< const SCEV * > &Operands, const Loop *L, SCEV::NoWrapFlags Flags)
Optional< std::pair< const SCEV *, SmallVector< const SCEVPredicate *, 3 > > > createAddRecFromPHIWithCasts (const SCEVUnknown *SymbolicPHI)
Checks if SymbolicPHI can be rewritten as an AddRecExpr under some Predicates.
const SCEV * getGEPExpr (GEPOperator *GEP, const SmallVectorImpl< const SCEV * > &IndexExprs)
Returns an expression for a GEP.
const SCEV * getMinMaxExpr (unsigned Kind, SmallVectorImpl< const SCEV * > &Operands)
const SCEV * getSMaxExpr (const SCEV *LHS, const SCEV *RHS)
const SCEV * getSMaxExpr (SmallVectorImpl< const SCEV * > &Operands)
const SCEV * getUMaxExpr (const SCEV *LHS, const SCEV *RHS)
const SCEV * getUMaxExpr (SmallVectorImpl< const SCEV * > &Operands)
const SCEV * getSMinExpr (const SCEV *LHS, const SCEV *RHS)
const SCEV * getSMinExpr (SmallVectorImpl< const SCEV * > &Operands)
const SCEV * getUMinExpr (const SCEV *LHS, const SCEV *RHS)
const SCEV * getUMinExpr (SmallVectorImpl< const SCEV * > &Operands)
const SCEV * getUnknown (Value *V)
const SCEV * getCouldNotCompute ()
const SCEV * getZero (Type *Ty)
Return a SCEV for the constant 0 of a specific type.
const SCEV * getOne (Type *Ty)
Return a SCEV for the constant 1 of a specific type.
const SCEV * getSizeOfExpr (Type *IntTy, Type *AllocTy)
Return an expression for sizeof AllocTy that is type IntTy.
const SCEV * getOffsetOfExpr (Type *IntTy, StructType *STy, unsigned FieldNo)
Return an expression for offsetof on the given field with type IntTy.
const SCEV * getNegativeSCEV (const SCEV *V, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap)
Return the SCEV object corresponding to -V.
const SCEV * getNotSCEV (const SCEV *V)
Return the SCEV object corresponding to ~V.
const SCEV * getMinusSCEV (const SCEV *LHS, const SCEV *RHS, SCEV::NoWrapFlags Flags=SCEV::FlagAnyWrap, unsigned Depth=0)
Return LHS-RHS. Minus is represented in SCEV as A+B*-1.
const SCEV * getTruncateOrZeroExtend (const SCEV *V, Type *Ty, unsigned Depth=0)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getTruncateOrSignExtend (const SCEV *V, Type *Ty, unsigned Depth=0)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getNoopOrZeroExtend (const SCEV *V, Type *Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getNoopOrSignExtend (const SCEV *V, Type *Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getNoopOrAnyExtend (const SCEV *V, Type *Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getTruncateOrNoop (const SCEV *V, Type *Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
const SCEV * getUMaxFromMismatchedTypes (const SCEV *LHS, const SCEV *RHS)
Promote the operands to the wider of the types using zero-extension, and then perform a umax operation with them.
const SCEV * getUMinFromMismatchedTypes (const SCEV *LHS, const SCEV *RHS)
Promote the operands to the wider of the types using zero-extension, and then perform a umin operation with them.
const SCEV * getUMinFromMismatchedTypes (SmallVectorImpl< const SCEV * > &Ops)
Promote the operands to the wider of the types using zero-extension, and then perform a umin operation with them.
const SCEV * getPointerBase (const SCEV *V)
Transitively follow the chain of pointer-type operands until reaching a SCEV that does not have a single pointer operand.
const SCEV * getSCEVAtScope (const SCEV *S, const Loop *L)
Return a SCEV expression for the specified value at the specified scope in the program.
const SCEV * getSCEVAtScope (Value *V, const Loop *L)
This is a convenience function which does getSCEVAtScope(getSCEV(V), L).
bool isLoopEntryGuardedByCond (const Loop *L, ICmpInst::Predicate Pred, const SCEV *LHS, const SCEV *RHS)
Test whether entry to the loop is protected by a conditional between LHS and RHS.
bool isLoopBackedgeGuardedByCond (const Loop *L, ICmpInst::Predicate Pred, const SCEV *LHS, const SCEV *RHS)
Test whether the backedge of the loop is protected by a conditional between LHS and RHS.
unsigned getSmallConstantTripCount (const Loop *L)
Returns the maximum trip count of the loop if it is a single-exit loop and we can compute a small maximum for that loop.
unsigned getSmallConstantTripCount (const Loop *L, BasicBlock *ExitingBlock)
Returns the maximum trip count of this loop as a normal unsigned value.
unsigned getSmallConstantMaxTripCount (const Loop *L)
Returns the upper bound of the loop trip count as a normal unsigned value.
unsigned getSmallConstantTripMultiple (const Loop *L)
Returns the largest constant divisor of the trip count of the loop if it is a single-exit loop and we can compute a small maximum for that loop.
unsigned getSmallConstantTripMultiple (const Loop *L, BasicBlock *ExitingBlock)
Returns the largest constant divisor of the trip count of this loop as a normal unsigned value, if possible.
const SCEV * getExitCount (const Loop *L, BasicBlock *ExitingBlock)
Return the number of times the backedge executes before the given exit would be taken; if not exactly computable, return SCEVCouldNotCompute.
const SCEV * getBackedgeTakenCount (const Loop *L)
If the specified loop has a predictable backedge-taken count, return it, otherwise return a SCEVCouldNotCompute object.
const SCEV * getPredicatedBackedgeTakenCount (const Loop *L, SCEVUnionPredicate &Predicates)
Similar to getBackedgeTakenCount, except it will add a set of SCEV predicates to Predicates that are required to be true in order for the answer to be correct.
const SCEV * getMaxBackedgeTakenCount (const Loop *L)
When successful, this returns a SCEVConstant that is greater than or equal to (i.e.
bool isBackedgeTakenCountMaxOrZero (const Loop *L)
Return true if the backedge taken count is either the value returned by getMaxBackedgeTakenCount or zero.
bool hasLoopInvariantBackedgeTakenCount (const Loop *L)
Return true if the specified loop has an analyzable loop-invariant backedge-taken count.
void forgetAllLoops ()
void forgetLoop (const Loop *L)
This method should be called by the client when it has changed a loop in a way that may effect ScalarEvolution's ability to compute a trip count, or if the loop is deleted.
void forgetTopmostLoop (const Loop *L)
void forgetValue (Value *V)
This method should be called by the client when it has changed a value in a way that may effect its value, or which may disconnect it from a def-use chain linking it to a loop.
void forgetLoopDispositions (const Loop *L)
Called when the client has changed the disposition of values in this loop.
uint32_t GetMinTrailingZeros (const SCEV *S)
Determine the minimum number of zero bits that S is guaranteed to end in (at every loop iteration).
ConstantRange getUnsignedRange (const SCEV *S)
Determine the unsigned range for a particular SCEV.
APInt getUnsignedRangeMin (const SCEV *S)
Determine the min of the unsigned range for a particular SCEV.
APInt getUnsignedRangeMax (const SCEV *S)
Determine the max of the unsigned range for a particular SCEV.
ConstantRange getSignedRange (const SCEV *S)
Determine the signed range for a particular SCEV.
APInt getSignedRangeMin (const SCEV *S)
Determine the min of the signed range for a particular SCEV.
APInt getSignedRangeMax (const SCEV *S)
Determine the max of the signed range for a particular SCEV.
bool isKnownNegative (const SCEV *S)
Test if the given expression is known to be negative.
bool isKnownPositive (const SCEV *S)
Test if the given expression is known to be positive.
bool isKnownNonNegative (const SCEV *S)
Test if the given expression is known to be non-negative.
bool isKnownNonPositive (const SCEV *S)
Test if the given expression is known to be non-positive.
bool isKnownNonZero (const SCEV *S)
Test if the given expression is known to be non-zero.
std::pair< const SCEV *, const SCEV * > SplitIntoInitAndPostInc (const Loop *L, const SCEV *S)
Splits SCEV expression S into two SCEVs.
bool isKnownViaInduction (ICmpInst::Predicate Pred, const SCEV *LHS, const SCEV *RHS)
We'd like to check the predicate on every iteration of the most dominated loop between loops used in LHS and RHS.
bool isKnownPredicate (ICmpInst::Predicate Pred, const SCEV *LHS, const SCEV *RHS)
Test if the given expression is known to satisfy the condition described by Pred, LHS, and RHS.
bool isKnownOnEveryIteration (ICmpInst::Predicate Pred, const SCEVAddRecExpr *LHS, const SCEV *RHS)
Test if the condition described by Pred, LHS, RHS is known to be true on every iteration of the loop of the recurrency LHS.
bool isMonotonicPredicate (const SCEVAddRecExpr *LHS, ICmpInst::Predicate Pred, bool &Increasing)
Return true if, for all loop invariant X, the predicate "LHS `Pred` X" is monotonically increasing or decreasing.
bool isLoopInvariantPredicate (ICmpInst::Predicate Pred, const SCEV *LHS, const SCEV *RHS, const Loop *L, ICmpInst::Predicate &InvariantPred, const SCEV *&InvariantLHS, const SCEV *&InvariantRHS)
Return true if the result of the predicate LHS Pred RHS is loop invariant with respect to L.
bool SimplifyICmpOperands (ICmpInst::Predicate &Pred, const SCEV *&LHS, const SCEV *&RHS, unsigned Depth=0)
Simplify LHS and RHS in a comparison with predicate Pred.
LoopDisposition getLoopDisposition (const SCEV *S, const Loop *L)
Return the "disposition" of the given SCEV with respect to the given loop.
bool isLoopInvariant (const SCEV *S, const Loop *L)
Return true if the value of the given SCEV is unchanging in the specified loop.
bool isAvailableAtLoopEntry (const SCEV *S, const Loop *L)
Determine if the SCEV can be evaluated at loop's entry.
bool hasComputableLoopEvolution (const SCEV *S, const Loop *L)
Return true if the given SCEV changes value in a known way in the specified loop.
BlockDisposition getBlockDisposition (const SCEV *S, const BasicBlock *BB)
Return the "disposition" of the given SCEV with respect to the given block.
bool dominates (const SCEV *S, const BasicBlock *BB)
Return true if elements that makes up the given SCEV dominate the specified basic block.
bool properlyDominates (const SCEV *S, const BasicBlock *BB)
Return true if elements that makes up the given SCEV properly dominate the specified basic block.
bool hasOperand (const SCEV *S, const SCEV *Op) const
Test whether the given SCEV has Op as a direct or indirect operand.
const SCEV * getElementSize (Instruction *Inst)
Return the size of an element read or written by Inst.
void findArrayDimensions (SmallVectorImpl< const SCEV * > &Terms, SmallVectorImpl< const SCEV * > &Sizes, const SCEV *ElementSize)
Compute the array dimensions Sizes from the set of Terms extracted from the memory access function of this SCEVAddRecExpr (second step of delinearization).
void print (raw_ostream &OS) const
void verify () const
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
void collectParametricTerms (const SCEV *Expr, SmallVectorImpl< const SCEV * > &Terms)
Collect parametric terms occurring in step expressions (first step of delinearization).
void computeAccessFunctions (const SCEV *Expr, SmallVectorImpl< const SCEV * > &Subscripts, SmallVectorImpl< const SCEV * > &Sizes)
Return in Subscripts the access functions for each dimension in Sizes (third step of delinearization).
void delinearize (const SCEV *Expr, SmallVectorImpl< const SCEV * > &Subscripts, SmallVectorImpl< const SCEV * > &Sizes, const SCEV *ElementSize)
Split this SCEVAddRecExpr into two vectors of SCEVs representing the subscripts and sizes of an array access.
const DataLayout & getDataLayout () const
Return the DataLayout associated with the module this SCEV instance is operating on.
const SCEVPredicate * getEqualPredicate (const SCEV *LHS, const SCEV *RHS)
const SCEVPredicate * getWrapPredicate (const SCEVAddRecExpr *AR, SCEVWrapPredicate::IncrementWrapFlags AddedFlags)
const SCEV * rewriteUsingPredicate (const SCEV *S, const Loop *L, SCEVUnionPredicate &A)
Re-writes the SCEV according to the Predicates in A.
const SCEVAddRecExpr * convertSCEVToAddRecWithPredicates (const SCEV *S, const Loop *L, SmallPtrSetImpl< const SCEVPredicate * > &Preds)
Tries to convert the S expression to an AddRec expression, adding additional predicates to Preds as required.
Static Public Member Functions
static LLVM_NODISCARD SCEV::NoWrapFlags maskFlags (SCEV::NoWrapFlags Flags, int Mask)
Convenient NoWrapFlags manipulation that hides enum casts and is visible in the ScalarEvolution name space.
static LLVM_NODISCARD SCEV::NoWrapFlags setFlags (SCEV::NoWrapFlags Flags, SCEV::NoWrapFlags OnFlags)
static LLVM_NODISCARD SCEV::NoWrapFlags clearFlags (SCEV::NoWrapFlags Flags, SCEV::NoWrapFlags OffFlags)
Friends
class SCEVCallbackVH
class SCEVExpander
class SCEVUnknown
Detailed Description
The main scalar evolution driver.
Because client code (intentionally) can't do much with the SCEV objects directly, they must ask this class for services.
Definition at line 470 of file ScalarEvolution.h.
Member Enumeration Documentation
BlockDisposition
enum llvm::ScalarEvolution::BlockDisposition
An enum describing the relationship between a SCEV and a basic block.
Enumerator
DoesNotDominateBlock
The SCEV does not dominate the block.
DominatesBlock
The SCEV dominates the block.
ProperlyDominatesBlock
The SCEV properly dominates the block.
Definition at line 480 of file ScalarEvolution.h.
LoopDisposition
enum llvm::ScalarEvolution::LoopDisposition
An enum describing the relationship between a SCEV and a loop.
Enumerator
LoopVariant
The SCEV is loop-variant (unknown).
LoopInvariant
The SCEV is loop-invariant.
LoopComputable
The SCEV varies predictably with the loop.
Definition at line 473 of file ScalarEvolution.h.
Constructor & Destructor Documentation
ScalarEvolution() [1/2]
ScalarEvolution::ScalarEvolution (Function & F, TargetLibraryInfo & TLI, AssumptionCache & AC, DominatorTree & DT, LoopInfo & LI)
Definition at line 11326 of file ScalarEvolution.cpp.
References F, and llvm::Intrinsic::getName().
ScalarEvolution() [2/2]
ScalarEvolution::ScalarEvolution (ScalarEvolution && Arg)
Definition at line 11347 of file ScalarEvolution.cpp.
~ScalarEvolution()
ScalarEvolution::~ScalarEvolution ()
Definition at line 11375 of file ScalarEvolution.cpp.
References assert().
Member Function Documentation
clearFlags()
static LLVM_NODISCARD SCEV::NoWrapFlags llvm::ScalarEvolution::clearFlags (SCEV::NoWrapFlags Flags, SCEV::NoWrapFlags OffFlags) inline static
Definition at line 497 of file ScalarEvolution.h.
Referenced by getMulExpr().
collectParametricTerms()
void ScalarEvolution::collectParametricTerms (const SCEV * Expr, SmallVectorImpl< const SCEV * > & Terms)
Collect parametric terms occurring in step expressions (first step of delinearization).
Find parametric terms in this SCEVAddRecExpr.
We first for parameters in two places: 1) The strides of AddRec expressions. 2) Unknowns that are multiplied with AddRec expressions.
Definition at line 10952 of file ScalarEvolution.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::visitAll().
Referenced by delinearize().
computeAccessFunctions()
void ScalarEvolution::computeAccessFunctions (const SCEV * Expr, SmallVectorImpl< const SCEV * > & Subscripts, SmallVectorImpl< const SCEV * > & Sizes)
Return in Subscripts the access functions for each dimension in Sizes (third step of delinearization).
Definition at line 11136 of file ScalarEvolution.cpp.
References llvm::dbgs(), llvm::SCEVAddRecExpr::isAffine(), and LLVM_DEBUG.
Referenced by delinearize().
containsAddRecurrence()
bool ScalarEvolution::containsAddRecurrence (const SCEV * S)
Return true if the SCEV is a scAddRecExpr or it contains scAddRecExpr.
The result will be cached in HasRecMap.
Definition at line 3807 of file ScalarEvolution.cpp.
References I, and llvm::SCEVExprContains().
convertSCEVToAddRecWithPredicates()
const SCEVAddRecExpr * ScalarEvolution::convertSCEVToAddRecWithPredicates (const SCEV * S, const Loop * L, SmallPtrSetImpl< const SCEVPredicate * > & Preds)
Tries to convert the S expression to an AddRec expression, adding additional predicates to Preds as required.
Definition at line 12147 of file ScalarEvolution.cpp.
References P, and llvm::SCEVParameterRewriter::rewrite().
Referenced by llvm::PredicatedScalarEvolution::getAsAddRec().
createAddRecFromPHIWithCasts()
Optional< std::pair< const SCEV *, SmallVector< const SCEVPredicate *, 3 > > > ScalarEvolution::createAddRecFromPHIWithCasts (const SCEVUnknown * SymbolicPHI)
Checks if SymbolicPHI can be rewritten as an AddRecExpr under some Predicates.
If successful return these <AddRecExpr, Predicates>; The function is intended to be called from PSCEV (the caller will decide whether to actually add the predicates and carry out the rewrites).
Definition at line 4891 of file ScalarEvolution.cpp.
References assert(), llvm::SCEVUnknown::getValue(), I, isIntegerLoopHeaderPHI(), and llvm::None.
delinearize()
void ScalarEvolution::delinearize (const SCEV * Expr, SmallVectorImpl< const SCEV * > & Subscripts, SmallVectorImpl< const SCEV * > & Sizes, const SCEV * ElementSize)
Split this SCEVAddRecExpr into two vectors of SCEVs representing the subscripts and sizes of an array access.
Splits the SCEV into two vectors of SCEVs representing the subscripts and sizes of an array access.
The delinearization is a 3 step process: the first two steps compute the sizes of each subscript and the third step computes the access functions for the delinearized array:
Find the terms in the step functions
Compute the array size
Compute the access function: divide the SCEV by the array size starting with the innermost dimensions found in step 2. The Quotient is the SCEV to be divided in the next step of the recursion. The Remainder is the subscript of the innermost dimension. Loop over all array dimensions computed in step 2.
To compute a uniform array size for several memory accesses to the same object, one can collect in step 1 all the step terms for all the memory accesses, and compute in step 2 a unique array shape. This guarantees that the array shape will be the same across all memory accesses.
FIXME: We could derive the result of steps 1 and 2 from a description of the array shape given in metadata.
Example:
A[][n][m]
for i for j for k A[j+k][2i][5i] =
The initial SCEV:
A[{{{0,+,2*m+5}_i, +, n*m}_j, +, n*m}_k]
Find the different terms in the step functions: -> [2*m, 5, n*m, n*m]
Compute the array size: sort and unique them -> [n*m, 2*m, 5] find the GCD of all the terms = 1 divide by the GCD and erase constant terms -> [n*m, 2*m] GCD = m divide by GCD -> [n, 2] remove constant terms -> [n] size of the array is A[unknown][n][m]
Compute the access function a. Divide {{{0,+,2*m+5}_i, +, n*m}_j, +, n*m}_k by the innermost size m Quotient: {{{0,+,2}_i, +, n}_j, +, n}_k Remainder: {{{0,+,5}_i, +, 0}_j, +, 0}_k The remainder is the subscript of the innermost array dimension: [5i].
b. Divide Quotient: {{{0,+,2}_i, +, n}_j, +, n}_k by next outer size n Quotient: {{{0,+,0}_i, +, 1}_j, +, 1}_k Remainder: {{{0,+,2}_i, +, 0}_j, +, 0}_k The Remainder is the subscript of the next array dimension: [2i].
The subscript of the outermost dimension is the Quotient: [j+k].
Overall, we have: A[][n][m], and the access function: A[j+k][2i][5i].
Returns the remainder of the delinearization that is the offset start of the array. The SCEV->delinearize algorithm computes the multiples of SCEV coefficients: that is a pattern matching of sub expressions in the stride and base of a SCEV corresponding to the computation of a GCD (greatest common divisor) of base and stride. When SCEV->delinearize fails, it returns the SCEV unchanged.
For example: when analyzing the memory access A[i][j][k] in this loop nest
void foo(long n, long m, long o, double A[n][m][o]) {
for (long i = 0; i < n; i++) for (long j = 0; j < m; j++) for (long k = 0; k < o; k++) A[i][j][k] = 1.0; }
the delinearization input is the following AddRec SCEV:
AddRec: {{{A,+,(8 * m * o)}<for.i>,+,(8 * o)}<for.j>,+,8}<for.k>
From this SCEV, we are able to say that the base offset of the access is A because it appears as an offset that does not divide any of the strides in the loops:
CHECK: Base offset: A
and then SCEV->delinearize determines the size of some of the dimensions of the array as these are the multiples by which the strides are happening:
CHECK: ArrayDecl[UnknownSize][m][o] with elements of sizeof(double) bytes.
Note that the outermost dimension remains of UnknownSize because there are no strides that would help identifying the size of the last dimension: when the array has been statically allocated, one could compute the size of that dimension by dividing the overall size of the array by the size of the known dimensions: m * o * 8.
Finally delinearize provides the access functions for the array reference that does correspond to A[i][j][k] of the above C testcase:
CHECK: ArrayRef[{0,+,1}<for.i>][{0,+,1}<for.j>][{0,+,1}<for.k>]
The testcases are checking the output of a function pass: DelinearizationPass that walks through all loads and stores of a function asking for the SCEV of the memory access with respect to all enclosing loops, calling SCEV->delinearize on that and printing the results.
Definition at line 11242 of file ScalarEvolution.cpp.
References collectParametricTerms(), computeAccessFunctions(), llvm::dbgs(), findArrayDimensions(), and LLVM_DEBUG.
dominates()
bool ScalarEvolution::dominates (const SCEV * S, const BasicBlock * BB)
Return true if elements that makes up the given SCEV dominate the specified basic block.
Definition at line 11761 of file ScalarEvolution.cpp.
References DominatesBlock, and getBlockDisposition().
Referenced by llvm::isSafeToExpandAt().
eraseValueFromMap()
void ScalarEvolution::eraseValueFromMap (Value * V)
Erase Value from ValueExprMap and ExprValueMap.
ValueExprMap.erase(V) cannot be used separately. eraseValueFromMap should be used to remove V from ValueExprMap and ExprValueMap at the same time.
Definition at line 3855 of file ScalarEvolution.cpp.
References I, and splitAddExpr().
Referenced by forgetLoop(), and forgetValue().
findArrayDimensions()
void ScalarEvolution::findArrayDimensions (SmallVectorImpl< const SCEV * > & Terms, SmallVectorImpl< const SCEV * > & Sizes, const SCEV * ElementSize)
Compute the array dimensions Sizes from the set of Terms extracted from the memory access function of this SCEVAddRecExpr (second step of delinearization).
Definition at line 11073 of file ScalarEvolution.cpp.
References containsParameters(), llvm::dbgs(), findArrayDimensionsRec(), llvm::SCEV::isZero(), LLVM_DEBUG, numberOfTerms(), and removeConstantFactors().
Referenced by delinearize().
forgetAllLoops()
void ScalarEvolution::forgetAllLoops ()
Definition at line 6740 of file ScalarEvolution.cpp.
Referenced by llvm::UnrollLoop().
forgetLoop()
void ScalarEvolution::forgetLoop (const Loop * L)
This method should be called by the client when it has changed a loop in a way that may effect ScalarEvolution's ability to compute a trip count, or if the loop is deleted.
This call is potentially expensive for large loop bodies.
Definition at line 6762 of file ScalarEvolution.cpp.
References eraseValueFromMap(), I, PushDefUseChildren(), and PushLoopPHIs().
Referenced by forgetTopmostLoop(), llvm::formLCSSA(), separateNestedLoop(), llvm::UnrollAndJamLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), and llvm::InnerLoopVectorizer::updateAnalysis().
forgetLoopDispositions()
void llvm::ScalarEvolution::forgetLoopDispositions (const Loop * L) inline
Called when the client has changed the disposition of values in this loop.
We don't have a way to invalidate per-loop dispositions. Clear and recompute is simpler.
Definition at line 819 of file ScalarEvolution.h.
Referenced by isLoopDead(), simplifyOneLoop(), and sinkLoopInvariantInstructions().
forgetTopmostLoop()
void ScalarEvolution::forgetTopmostLoop (const Loop * L)
Definition at line 6828 of file ScalarEvolution.cpp.
References forgetLoop(), and llvm::LoopBase< BlockT, LoopT >::getParentLoop().
Referenced by llvm::peelLoop(), simplifyLoopCFG(), simplifyOneLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), and unswitchTrivialSwitch().
forgetValue()
void ScalarEvolution::forgetValue (Value * V)
This method should be called by the client when it has changed a value in a way that may effect its value, or which may disconnect it from a def-use chain linking it to a loop.
Definition at line 6834 of file ScalarEvolution.cpp.
References eraseValueFromMap(), I, and PushDefUseChildren().
Referenced by simplifyOneLoop().
getAddExpr() [1/3]
const SCEV * llvm::ScalarEvolution::getAddExpr (const SCEV * LHS, const SCEV * RHS, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0) inline
Definition at line 547 of file ScalarEvolution.h.
References getAddExpr().
getAddExpr() [2/3]
const SCEV * llvm::ScalarEvolution::getAddExpr (const SCEV * Op0, const SCEV * Op1, const SCEV * Op2, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0) inline
Definition at line 553 of file ScalarEvolution.h.
References getAddExpr().
getAddExpr() [3/3]
const SCEV * ScalarEvolution::getAddExpr (SmallVectorImpl< const SCEV * > & Ops, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0)
Get a canonical add expression, or something simpler if possible.
Definition at line 2402 of file ScalarEvolution.cpp.
References llvm::AddOne(), AddOpsInlineThreshold, assert(), CollectAddOperandsWithScales(), llvm::DominatorTree::dominates(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, getAddExpr(), getAddRecExpr(), getAnyExtendExpr(), getConstant(), getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVAddRecExpr::getLoop(), getMulExpr(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), getOne(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVAddRecExpr::getStart(), getTruncateExpr(), getTypeSizeInBits(), getZero(), GroupByComplexity(), hasHugeExpression(), Idx, isAvailableAtLoopEntry(), MaxArithDepth, llvm::SCEVNAryExpr::op_begin(), llvm::SCEVNAryExpr::op_end(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scMulExpr, setFlags(), and StrengthenNoWrapFlags().
Referenced by canBeCheaplyTransformed(), countToEliminateCompares(), llvm::SCEVAddRecExpr::evaluateAtIteration(), expandBounds(), ExposePointerBase(), ExtractImmediate(), ExtractSymbol(), FactorOutConstant(), genLoopLimit(), getAddExpr(), getExactSDiv(), getExtendAddRecStart(), getGEPExpr(), getMinusSCEV(), getMulExpr(), getNumBytes(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPreStartForExtend(), getSignExtendExpr(), getSmallConstantTripMultiple(), getTruncateExpr(), getUDivExpr(), getZeroExtendExpr(), llvm::RuntimePointerChecking::insert(), llvm::isConsecutiveAccess(), IsIncrementNSW(), IsIncrementNUW(), isSafeDecreasingBound(), isSafeIncreasingBound(), SimplifyAddOperands(), SimplifyICmpOperands(), llvm::UnrollRuntimeLoopRemainder(), llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), and willNotOverflow().
getAddRecExpr() [1/3]
const SCEV * ScalarEvolution::getAddRecExpr (const SCEV * Start, const SCEV * Step, const Loop * L, SCEV::NoWrapFlags Flags)
Get an add recurrence expression for the specified loop.
Simplify the expression as much as possible.
Definition at line 3388 of file ScalarEvolution.cpp.
References llvm::SCEV::FlagNW, getAddRecExpr(), and maskFlags().
Referenced by CollectSubexprs(), DoInitialMatch(), ExposePointerBase(), ExtractImmediate(), ExtractSymbol(), FactorOutConstant(), getAddExpr(), getAddRecExpr(), getAnyExtendExpr(), getExactSDiv(), getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPreStartForExtend(), getSignExtendExpr(), llvm::SCEVAddRecExpr::getStepRecurrence(), getTruncateExpr(), getUDivExpr(), getZeroExtendExpr(), isLoopBackedgeGuardedByCond(), SplitAddRecs(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), and llvm::SCEVLoopAddRecRewriter::visitAddRecExpr().
getAddRecExpr() [2/3]
const SCEV * llvm::ScalarEvolution::getAddRecExpr (const SmallVectorImpl< const SCEV * > & Operands, const Loop * L, SCEV::NoWrapFlags Flags) inline
Definition at line 581 of file ScalarEvolution.h.
References getAddRecExpr().
getAddRecExpr() [3/3]
const SCEV * ScalarEvolution::getAddRecExpr (SmallVectorImpl< const SCEV * > & Operands, const Loop * L, SCEV::NoWrapFlags Flags)
Get an add recurrence expression for the specified loop.
Simplify the expression as much as possible.
Definition at line 3406 of file ScalarEvolution.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DominatorTree::dominates(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNW, getAddRecExpr(), getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), isLoopInvariant(), maskFlags(), llvm::scAddRecExpr, and StrengthenNoWrapFlags().
getAnyExtendExpr()
const SCEV * ScalarEvolution::getAnyExtendExpr (const SCEV * Op, Type * Ty)
getAnyExtendExpr - Return a SCEV for the given operand extended with unspecified bits out to the given type.
Definition at line 2193 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::FlagNW, getAddRecExpr(), getAnyExtendExpr(), getEffectiveSCEVType(), getSignExtendExpr(), getTruncateOrNoop(), llvm::SCEV::getType(), getTypeSizeInBits(), getZeroExtendExpr(), and isSCEVable().
Referenced by getAddExpr(), getAnyExtendExpr(), and getNoopOrAnyExtend().
getBackedgeTakenCount()
const SCEV * ScalarEvolution::getBackedgeTakenCount (const Loop * L)
If the specified loop has a predictable backedge-taken count, return it, otherwise return a SCEVCouldNotCompute object.
The backedge-taken count is the number of times the loop header will be branched to from within the loop, assuming there are no abnormal exists like exception throws. This is one less than the trip count of the loop, since it doesn't count the first iteration, when the header is branched to from outside the loop.
Note that it is not valid to call this method on a loop without a loop-invariant backedge-taken count (see hasLoopInvariantBackedgeTakenCount).
Definition at line 6596 of file ScalarEvolution.cpp.
Referenced by getPreStartForExtend(), hasLoopInvariantBackedgeTakenCount(), llvm::IVUsers::print(), PrintLoopInfo(), llvm::LoopVectorizePass::processLoop(), and verify().
getBlockDisposition()
ScalarEvolution::BlockDisposition ScalarEvolution::getBlockDisposition (const SCEV * S, const BasicBlock * BB)
Return the "disposition" of the given SCEV with respect to the given block.
Definition at line 11677 of file ScalarEvolution.cpp.
References DoesNotDominateBlock.
Referenced by dominates(), and properlyDominates().
getConstant() [1/3]
const SCEV * ScalarEvolution::getConstant (const APInt & Val)
Definition at line 427 of file ScalarEvolution.cpp.
References llvm::DITypeRefArray::get(), getConstant(), and getContext().
getConstant() [2/3]
const SCEV * ScalarEvolution::getConstant (ConstantInt * V)
Definition at line 416 of file ScalarEvolution.cpp.
References llvm::scConstant.
Referenced by BinomialCoefficient(), llvm::cannotBeMaxInLoop(), llvm::cannotBeMinInLoop(), CollectSubexprs(), countToEliminateCompares(), DoInitialMatch(), EvaluateConstantChrecAtConstant(), ExposePointerBase(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), ExtractImmediate(), ExtractSymbol(), FactorOutConstant(), getAddExpr(), getConstant(), getExactSDiv(), getMinMaxExpr(), getMulExpr(), getNegativeSCEV(), getNotSCEV(), getNumBytes(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOffsetOfExpr(), getOne(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), getSignedOverflowLimitForStep(), getSignExtendExpr(), getSizeOfExpr(), getStartForNegStride(), getTruncateExpr(), getUDivExactExpr(), getUDivExpr(), getUnsignedOverflowLimitForStep(), getZero(), getZeroExtendExpr(), llvm::RuntimePointerChecking::insert(), llvm::isConsecutiveAccess(), llvm::InductionDescriptor::isInductionPHI(), isSafeDecreasingBound(), isSafeDependenceDistance(), isSafeIncreasingBound(), SimplifyAddOperands(), SimplifyICmpOperands(), SolveLinEquationWithOverflow(), SplitAddRecs(), llvm::UnrolledInstAnalyzer::UnrolledInstAnalyzer(), llvm::UnrollRuntimeLoopRemainder(), verify(), and llvm::SCEVParameterRewriter::visitUnknown().
getConstant() [3/3]
const SCEV * ScalarEvolution::getConstant (Type * Ty, uint64_t V, bool isSigned = false)
Definition at line 432 of file ScalarEvolution.cpp.
References llvm::DITypeRefArray::get(), getConstant(), and getEffectiveSCEVType().
getContext()
LLVMContext & llvm::ScalarEvolution::getContext () const inline
Definition at line 506 of file ScalarEvolution.h.
References llvm::Function::getContext().
Referenced by BinomialCoefficient(), FactorOutConstant(), getConstant(), llvm::SCEVExpander::getIVIncOperand(), getMinMaxExpr(), getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), getSignExtendExpr(), getUDivExpr(), getURemExpr(), getZeroExtendExpr(), isAddRecSExtable(), isAddSExtable(), isMulSExtable(), SimplifyICmpOperands(), SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
getCouldNotCompute()
const SCEV * ScalarEvolution::getCouldNotCompute ()
Definition at line 3794 of file ScalarEvolution.cpp.
Referenced by BinomialCoefficient(), llvm::SCEVExpander::generateOverflowCheck(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), getSmallConstantTripMultiple(), isKnownViaInduction(), isLoopBackedgeGuardedByCond(), mustBeFiniteCountedLoop(), SolveLinEquationWithOverflow(), SplitIntoInitAndPostInc(), and verify().
getDataLayout()
const DataLayout & llvm::ScalarEvolution::getDataLayout () const inline
Return the DataLayout associated with the module this SCEV instance is operating on.
Definition at line 1083 of file ScalarEvolution.h.
References llvm::Module::getDataLayout(), and llvm::GlobalValue::getParent().
Referenced by getEffectiveSCEVType(), getOffsetOfExpr(), getSizeOfExpr(), getTypeSizeInBits(), and llvm::simplifyLoopIVs().
getEffectiveSCEVType()
Type * ScalarEvolution::getEffectiveSCEVType (Type * Ty) const
Return a type with the same bitwidth as the given type and which represents how SCEV will treat the given type, for which isSCEVable must return true.
For pointer types, this is the pointer-sized integer type.
Definition at line 3779 of file ScalarEvolution.cpp.
References assert(), getDataLayout(), llvm::DataLayout::getIntPtrType(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), and isSCEVable().
Referenced by llvm::SCEVAAResult::alias(), canBeCheaplyTransformed(), DoInitialMatch(), genLoopLimit(), getAddExpr(), getAddRecExpr(), getAnyExtendExpr(), getConstant(), getElementSize(), getGEPExpr(), getMinMaxExpr(), getMulExpr(), getNegativeSCEV(), getNotSCEV(), getSignExtendExpr(), getTruncateExpr(), getUDivExpr(), getURemExpr(), getZeroExtendExpr(), isExistingPhi(), and visitIVCast().
getElementSize()
const SCEV * ScalarEvolution::getElementSize (Instruction * Inst)
Return the size of an element read or written by Inst.
Definition at line 11060 of file ScalarEvolution.cpp.
References getEffectiveSCEVType(), getSizeOfExpr(), and llvm::PointerType::getUnqual().
getEqualPredicate()
const SCEVPredicate * ScalarEvolution::getEqualPredicate (const SCEV * LHS, const SCEV * RHS)
Definition at line 11990 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::getType(), and llvm::SCEVPredicate::P_Equal.
Referenced by llvm::PredicatedScalarEvolution::areAddRecsEqualWithPreds(), and llvm::replaceSymbolicStrideSCEV().
getExitCount()
const SCEV * ScalarEvolution::getExitCount (const Loop * L, BasicBlock * ExitingBlock)
Return the number of times the backedge executes before the given exit would be taken; if not exactly computable, return SCEVCouldNotCompute.
Get the expression for the number of loop iterations for which this loop is guaranteed not to exit via ExitingBlock.
For a single exit loop, this value is equivelent to the result of getBackedgeTakenCount. The loop is guaranteed to exit (via some exit) before the backedge is executed (ExitCount + 1) times. Note that there is no guarantee about which exit is taken on the exiting iteration.
Otherwise return SCEVCouldNotCompute.
Definition at line 6585 of file ScalarEvolution.cpp.
Referenced by getSmallConstantTripCount(), getSmallConstantTripMultiple(), llvm::hasIterationCountInvariantInParent(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), mustBeFiniteCountedLoop(), PrintLoopInfo(), and llvm::UnrollRuntimeLoopRemainder().
getGEPExpr()
const SCEV * ScalarEvolution::getGEPExpr (GEPOperator * GEP, const SmallVectorImpl< const SCEV * > & IndexExprs)
Returns an expression for a GEP.
GEP The GEP. The indices contained in the GEP itself are ignored, instead we use IndexExprs. IndexExprs The expressions for the indices.
Definition at line 3482 of file ScalarEvolution.cpp.
References llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::DITypeRefArray::get(), getAddExpr(), getEffectiveSCEVType(), getMulExpr(), getOffsetOfExpr(), llvm::GEPOperator::getPointerOperand(), getSCEV(), getSizeOfExpr(), llvm::GEPOperator::getSourceElementType(), getTruncateOrSignExtend(), llvm::SCEV::getType(), llvm::ConstantInt::getValue(), getZero(), llvm::ConstantInt::getZExtValue(), and llvm::GEPOperator::isInBounds().
getLoopDisposition()
ScalarEvolution::LoopDisposition ScalarEvolution::getLoopDisposition (const SCEV * S, const Loop * L)
Return the "disposition" of the given SCEV with respect to the given loop.
Definition at line 11570 of file ScalarEvolution.cpp.
References LoopVariant.
Referenced by hasComputableLoopEvolution(), llvm::hasIterationCountInvariantInParent(), isLoopInvariant(), and print().
getMaxBackedgeTakenCount()
const SCEV * ScalarEvolution::getMaxBackedgeTakenCount (const Loop * L)
When successful, this returns a SCEVConstant that is greater than or equal to (i.e.
Similar to getBackedgeTakenCount, except return the least SCEV value that is known never to be less than the actual backedge taken count.
a "conservative over-approximation") of the value returend by getBackedgeTakenCount. If such a value cannot be computed, it returns the SCEVCouldNotCompute object.
Definition at line 6602 of file ScalarEvolution.cpp.
Referenced by deleteLoopIfDead(), getSignExtendExpr(), getSmallConstantMaxTripCount(), getZeroExtendExpr(), mustBeFiniteCountedLoop(), and PrintLoopInfo().
getMinMaxExpr()
const SCEV * ScalarEvolution::getMinMaxExpr (unsigned Kind, SmallVectorImpl< const SCEV * > & Operands)
Definition at line 3545 of file ScalarEvolution.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::DITypeRefArray::get(), getConstant(), getContext(), getEffectiveSCEVType(), getMinMaxExpr(), GroupByComplexity(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, Idx, llvm_unreachable, llvm::SCEVNAryExpr::op_begin(), llvm::SCEVNAryExpr::op_end(), llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scUMaxExpr, and llvm::scUMinExpr.
Referenced by getMinMaxExpr(), getNotSCEV(), getSMaxExpr(), getSMinExpr(), getUMaxExpr(), and getUMinExpr().
GetMinTrailingZeros()
uint32_t ScalarEvolution::GetMinTrailingZeros (const SCEV * S)
Determine the minimum number of zero bits that S is guaranteed to end in (at every loop iteration).
It is, at the same time, the minimum number of times S is divisible by 2. For example, given {4,+,8} it returns 2. If S is guaranteed to be 0, it returns the bitwidth of S.
Definition at line 5509 of file ScalarEvolution.cpp.
References assert(), and I.
Referenced by extractConstantWithoutWrapping(), getSmallConstantTripMultiple(), and SolveLinEquationWithOverflow().
getMinusSCEV()
const SCEV * ScalarEvolution::getMinusSCEV (const SCEV * LHS, const SCEV * RHS, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0)
Return LHS-RHS. Minus is represented in SCEV as A+B*-1.
Definition at line 4000 of file ScalarEvolution.cpp.
References llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, getAddExpr(), getNegativeSCEV(), getSignedRangeMin(), llvm::SCEV::getType(), getZero(), isKnownNonNegative(), and maskFlags().
Referenced by llvm::SCEVAAResult::alias(), llvm::InterleavedAccessInfo::analyzeInterleaving(), BinomialCoefficient(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), getMinFromExprs(), getNewAlignment(), getNewAlignmentDiff(), getNotSCEV(), getStartForNegStride(), getURemExpr(), llvm::isConsecutiveAccess(), isSafeDecreasingBound(), isSafeDependenceDistance(), isSafeIncreasingBound(), llvm::sortPtrAccesses(), verify(), and willNotOverflow().
getMulExpr() [1/3]
const SCEV * llvm::ScalarEvolution::getMulExpr (const SCEV * LHS, const SCEV * RHS, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0) inline
Definition at line 562 of file ScalarEvolution.h.
References getMulExpr().
getMulExpr() [2/3]
const SCEV * llvm::ScalarEvolution::getMulExpr (const SCEV * Op0, const SCEV * Op1, const SCEV * Op2, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0) inline
Definition at line 568 of file ScalarEvolution.h.
References getMulExpr().
getMulExpr() [3/3]
const SCEV * ScalarEvolution::getMulExpr (SmallVectorImpl< const SCEV * > & Ops, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap, unsigned Depth = 0)
Get a canonical multiply expression, or something simpler if possible.
Definition at line 2903 of file ScalarEvolution.cpp.
References assert(), Choose(), clearFlags(), containsConstantInAddMulChain(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, llvm::DITypeRefArray::get(), getAddExpr(), getAddRecExpr(), getConstant(), getContext(), getEffectiveSCEVType(), llvm::SCEVAddRecExpr::getLoop(), getMulExpr(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVNAryExpr::getType(), getTypeSizeInBits(), getZero(), GroupByComplexity(), hasHugeExpression(), Idx, isAvailableAtLoopEntry(), isHugeExpression(), isZero(), maskFlags(), MaxAddRecSize, MaxArithDepth, MulOpsInlineThreshold, llvm::scAddRecExpr, llvm::scMulExpr, StrengthenNoWrapFlags(), and umul_ov().
Referenced by BinomialCoefficient(), CollectAddOperandsWithScales(), CollectSubexprs(), DoInitialMatch(), llvm::SCEVAddRecExpr::evaluateAtIteration(), FactorOutConstant(), findArrayDimensionsRec(), getAddExpr(), getExactSDiv(), getGEPExpr(), getMulExpr(), getNegativeSCEV(), getNewAlignmentDiff(), getNumBytes(), getSignExtendExpr(), getStartForNegStride(), getTruncateExpr(), getUDivExactExpr(), getUDivExpr(), getURemExpr(), getZeroExtendExpr(), isSafeDependenceDistance(), removeConstantFactors(), SolveLinEquationWithOverflow(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), and willNotOverflow().
getNegativeSCEV()
const SCEV * ScalarEvolution::getNegativeSCEV (const SCEV * V, SCEV::NoWrapFlags Flags = SCEV::FlagAnyWrap)
Return the SCEV object corresponding to -V.
Return a SCEV corresponding to -V = -1*V.
Definition at line 3942 of file ScalarEvolution.cpp.
References llvm::Constant::getAllOnesValue(), getConstant(), getEffectiveSCEVType(), getMulExpr(), llvm::ConstantExpr::getNeg(), and llvm::SCEV::getType().
Referenced by canBeCheaplyTransformed(), llvm::SCEVExpander::generateOverflowCheck(), getMinusSCEV(), getNumBytes(), and isSafeDependenceDistance().
getNoopOrAnyExtend()
const SCEV * ScalarEvolution::getNoopOrAnyExtend (const SCEV * V, Type * Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
If the type must be extended, it is extended with unspecified bits. The conversion must not be narrowing.
Definition at line 4088 of file ScalarEvolution.cpp.
References assert(), getAnyExtendExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), and llvm::Type::isIntOrPtrTy().
getNoopOrSignExtend()
const SCEV * ScalarEvolution::getNoopOrSignExtend (const SCEV * V, Type * Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
If the type must be extended, it is sign extended. The conversion must not be narrowing.
Definition at line 4076 of file ScalarEvolution.cpp.
References assert(), getSignExtendExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), and llvm::Type::isIntOrPtrTy().
Referenced by getNewAlignment(), isSafeDependenceDistance(), and NoopOrExtend().
getNoopOrZeroExtend()
const SCEV * ScalarEvolution::getNoopOrZeroExtend (const SCEV * V, Type * Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
If the type must be extended, it is zero extended. The conversion must not be narrowing.
Definition at line 4064 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::getType(), getTypeSizeInBits(), getZeroExtendExpr(), and llvm::Type::isIntOrPtrTy().
Referenced by llvm::InnerLoopVectorizer::getOrCreateTripCount(), getUMaxFromMismatchedTypes(), getUMinFromMismatchedTypes(), and NoopOrExtend().
getNotSCEV()
const SCEV * ScalarEvolution::getNotSCEV (const SCEV * V)
Return the SCEV object corresponding to ~V.
Return a SCEV corresponding to ~V = -1-V.
Definition at line 3970 of file ScalarEvolution.cpp.
References llvm::Constant::getAllOnesValue(), getConstant(), getEffectiveSCEVType(), getMinMaxExpr(), getMinusSCEV(), llvm::ConstantExpr::getNot(), llvm::SCEV::getType(), MatchNotExpr(), and llvm::SCEVMinMaxExpr::negate().
getOffsetOfExpr()
const SCEV * ScalarEvolution::getOffsetOfExpr (Type * IntTy, StructType * STy, unsigned FieldNo)
Return an expression for offsetof on the given field with type IntTy.
Definition at line 3722 of file ScalarEvolution.cpp.
References getConstant(), and getDataLayout().
Referenced by getGEPExpr().
getOne()
const SCEV * llvm::ScalarEvolution::getOne (Type * Ty) inline
Return a SCEV for the constant 1 of a specific type.
Definition at line 618 of file ScalarEvolution.h.
References getConstant().
Referenced by expandBounds(), genLoopLimit(), getAddExpr(), getNumBytes(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), getSmallConstantTripMultiple(), isLoopBackedgeGuardedByCond(), isSafeDecreasingBound(), isSafeIncreasingBound(), and llvm::replaceSymbolicStrideSCEV().
getPointerBase()
const SCEV * ScalarEvolution::getPointerBase (const SCEV * V)
Transitively follow the chain of pointer-type operands until reaching a SCEV that does not have a single pointer operand.
This returns a SCEVUnknown pointer for well-formed pointer-type expressions, but corner cases do exist.
Definition at line 4154 of file ScalarEvolution.cpp.
References getPointerBase(), llvm::SCEV::getType(), and llvm::Type::isPointerTy().
Referenced by getPointerBase().
getPredicatedBackedgeTakenCount()
const SCEV * ScalarEvolution::getPredicatedBackedgeTakenCount (const Loop * L, SCEVUnionPredicate & Predicates)
Similar to getBackedgeTakenCount, except it will add a set of SCEV predicates to Predicates that are required to be true in order for the answer to be correct.
Predicates can be checked with run-time checks and can be used to perform loop versioning.
Definition at line 6591 of file ScalarEvolution.cpp.
Referenced by llvm::SCEVExpander::generateOverflowCheck(), llvm::PredicatedScalarEvolution::getBackedgeTakenCount(), and PrintLoopInfo().
getSCEV()
const SCEV * ScalarEvolution::getSCEV (Value * V)
Return a SCEV expression for the full generality of the specified expression.
Return an existing SCEV if it exists, otherwise analyze the expression and create a new one.
Definition at line 3895 of file ScalarEvolution.cpp.
References assert(), llvm::Value::getType(), isSCEVable(), SCEVCallbackVH, SCEVLostPoisonFlags(), and splitAddExpr().
Referenced by llvm::IVUsers::AddUsersImpl(), llvm::SCEVAAResult::alias(), countToEliminateCompares(), llvm::DependenceInfo::depends(), DoInitialMatch(), expandBounds(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), findIVOperand(), FindLoopCounter(), llvm::SCEVExpander::generateOverflowCheck(), genLoopLimit(), llvm::PredicatedScalarEvolution::getAsAddRec(), llvm::Loop::LoopBounds::getBounds(), getBoundsCheckCond(), getGEPExpr(), getInductionVariable(), getNewAlignment(), llvm::SCEVExpander::getRelatedExistingExpansion(), llvm::IVUsers::getReplacementExpr(), llvm::PredicatedScalarEvolution::getSCEV(), getSCEVAtScope(), llvm::DependenceInfo::getSplitIteration(), llvm::getStrideFromPointer(), llvm::isConsecutiveAccess(), isExistingPhi(), isHighCostExpansion(), llvm::InductionDescriptor::isInductionPHI(), isLoopCounter(), isProfitableChain(), isSimpleIVUser(), llvm::LoopAccessInfo::isUniform(), print(), llvm::PredicatedScalarEvolution::print(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::replaceSymbolicStrideSCEV(), llvm::sortPtrAccesses(), and llvm::stripGetElementPtr().
getSCEVAtScope() [1/2]
const SCEV * ScalarEvolution::getSCEVAtScope (const SCEV * S, const Loop * L)
Return a SCEV expression for the specified value at the specified scope in the program.
The L value specifies a loop nest to evaluate the expression at, where null is the top-level or a specified loop is immediately inside of the loop.
This method can be used to compute the exit value for a variable defined in a loop by querying what the value will hold in the parent loop.
In the case that a relevant loop exit value cannot be computed, the original value V is returned.
Definition at line 7987 of file ScalarEvolution.cpp.
Referenced by computeUnrollAndJamCount(), getSCEVAtScope(), isInteresting(), and print().
getSCEVAtScope() [2/2]
const SCEV * ScalarEvolution::getSCEVAtScope (Value * V, const Loop * L)
This is a convenience function which does getSCEVAtScope(getSCEV(V), L).
Definition at line 8336 of file ScalarEvolution.cpp.
References getSCEV(), and getSCEVAtScope().
getSignedRange()
ConstantRange llvm::ScalarEvolution::getSignedRange (const SCEV * S) inline
Determine the signed range for a particular SCEV.
NOTE: This returns a copy of the reference returned by getRangeRef.
Definition at line 845 of file ScalarEvolution.h.
Referenced by getSignExtendExpr(), print(), and StrengthenNoWrapFlags().
getSignedRangeMax()
APInt llvm::ScalarEvolution::getSignedRangeMax (const SCEV * S) inline
Determine the max of the signed range for a particular SCEV.
Definition at line 855 of file ScalarEvolution.h.
References llvm::ConstantRange::getSignedMax().
Referenced by getSignedOverflowLimitForStep(), isKnownNegative(), isKnownNonPositive(), and SimplifyICmpOperands().
getSignedRangeMin()
APInt llvm::ScalarEvolution::getSignedRangeMin (const SCEV * S) inline
Determine the min of the signed range for a particular SCEV.
Definition at line 850 of file ScalarEvolution.h.
References llvm::ConstantRange::getSignedMin().
Referenced by getMinusSCEV(), getSignedOverflowLimitForStep(), getZeroExtendExpr(), isKnownNonNegative(), isKnownPositive(), and SimplifyICmpOperands().
getSignExtendExpr()
const SCEV * ScalarEvolution::getSignExtendExpr (const SCEV * Op, Type * Ty, unsigned Depth = 0)
Definition at line 1940 of file ScalarEvolution.cpp.
References assert(), llvm::AssumptionCache::assumptions(), llvm::ConstantRange::contains(), extractConstantWithoutWrapping(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, llvm::DITypeRefArray::get(), getAddExpr(), getAddRecExpr(), getConstant(), getContext(), getEffectiveSCEVType(), getMaxBackedgeTakenCount(), getMulExpr(), llvm::ConstantExpr::getSExt(), getSignedOverflowLimitForStep(), getSignedRange(), getSignExtendExpr(), getTruncateOrSignExtend(), getTruncateOrZeroExtend(), llvm::SCEV::getType(), getTypeSizeInBits(), getZeroExtendExpr(), isKnownNonNegative(), isKnownOnEveryIteration(), isLoopBackedgeGuardedByCond(), isSCEVable(), MaxCastDepth, llvm::scSignExtend, llvm::ConstantRange::sextOrTrunc(), llvm::ConstantRange::signExtend(), llvm::ConstantRange::truncate(), and X().
Referenced by llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), getAnyExtendExpr(), getNoopOrSignExtend(), getSignExtendExpr(), getTruncateOrSignExtend(), getZeroExtendExpr(), isAddRecSExtable(), isAddSExtable(), IsIncrementNSW(), isMulSExtable(), llvm::SCEVRewriteVisitor< SC >::visitSignExtendExpr(), and willNotOverflow().
getSizeOfExpr()
const SCEV * ScalarEvolution::getSizeOfExpr (Type * IntTy, Type * AllocTy)
Return an expression for sizeof AllocTy that is type IntTy.
Definition at line 3715 of file ScalarEvolution.cpp.
References getConstant(), and getDataLayout().
Referenced by genLoopLimit(), getElementSize(), and getGEPExpr().
getSmallConstantMaxTripCount()
unsigned ScalarEvolution::getSmallConstantMaxTripCount (const Loop * L)
Returns the upper bound of the loop trip count as a normal unsigned value.
Returns 0 if the trip count is unknown or not constant.
Definition at line 6524 of file ScalarEvolution.cpp.
References getConstantTripCount(), and getMaxBackedgeTakenCount().
Referenced by llvm::LoopVectorizePass::processLoop(), and tryToUnrollLoop().
getSmallConstantTripCount() [1/2]
unsigned ScalarEvolution::getSmallConstantTripCount (const Loop * L)
Returns the maximum trip count of the loop if it is a single-exit loop and we can compute a small maximum for that loop.
Implemented in terms of the getSmallConstantTripCount overload with the single exiting block passed to it. See that routine for details.
Definition at line 6506 of file ScalarEvolution.cpp.
References llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), and getSmallConstantTripCount().
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), getSmallConstantTripCount(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), and llvm::UnrollLoop().
getSmallConstantTripCount() [2/2]
unsigned ScalarEvolution::getSmallConstantTripCount (const Loop * L, BasicBlock * ExitingBlock)
Returns the maximum trip count of this loop as a normal unsigned value.
Returns 0 if the trip count is unknown or not constant. This "trip count" assumes that control exits via ExitingBlock. More precisely, it is the number of times that control may reach ExitingBlock before taking the branch. For loops with multiple exits, it may not be the number times that the loop header executes if the loop exits prematurely via another branch.
Definition at line 6514 of file ScalarEvolution.cpp.
References assert(), getConstantTripCount(), getExitCount(), and llvm::LoopBase< BlockT, LoopT >::isLoopExiting().
getSmallConstantTripMultiple() [1/2]
unsigned ScalarEvolution::getSmallConstantTripMultiple (const Loop * L)
Returns the largest constant divisor of the trip count of the loop if it is a single-exit loop and we can compute a small maximum for that loop.
Implemented in terms of the getSmallConstantTripMultiple overload with the single exiting block passed to it. See that routine for details.
Definition at line 6530 of file ScalarEvolution.cpp.
References llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), and getSmallConstantTripMultiple().
Referenced by getSmallConstantTripMultiple(), PrintLoopInfo(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), and llvm::UnrollLoop().
getSmallConstantTripMultiple() [2/2]
unsigned ScalarEvolution::getSmallConstantTripMultiple (const Loop * L, BasicBlock * ExitingBlock)
Returns the largest constant divisor of the trip count of this loop as a normal unsigned value, if possible.
This means that the actual trip count is always a multiple of the returned value (don't forget the trip count could very well be zero as well!). As explained in the comments for getSmallConstantTripCount, this assumes that control exits the loop via ExitingBlock.
This means that the actual trip count is always a multiple of the returned value (don't forget the trip count could very well be zero as well!).
Returns 1 if the trip count is unknown or not guaranteed to be the multiple of a constant (which is also the case if the trip count is simply constant, use getSmallConstantTripCount for that case), Will also return 1 if the trip count is very large (>= 2^32).
As explained in the comments for getSmallConstantTripCount, this assumes that control exits the loop via ExitingBlock.
Definition at line 6551 of file ScalarEvolution.cpp.
References assert(), getAddExpr(), getCouldNotCompute(), getExitCount(), GetMinTrailingZeros(), getOne(), llvm::SCEV::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), and llvm::LoopBase< BlockT, LoopT >::isLoopExiting().
getSMaxExpr() [1/2]
const SCEV * ScalarEvolution::getSMaxExpr (const SCEV * LHS, const SCEV * RHS)
Definition at line 3677 of file ScalarEvolution.cpp.
References getSMaxExpr().
Referenced by getSMaxExpr(), IntersectSignedRange(), and llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr().
getSMaxExpr() [2/2]
const SCEV * ScalarEvolution::getSMaxExpr (SmallVectorImpl< const SCEV * > & Operands)
Definition at line 3682 of file ScalarEvolution.cpp.
References getMinMaxExpr(), and llvm::scSMaxExpr.
getSMinExpr() [1/2]
const SCEV * ScalarEvolution::getSMinExpr (const SCEV * LHS, const SCEV * RHS)
Definition at line 3695 of file ScalarEvolution.cpp.
References getSMinExpr().
Referenced by getSMinExpr(), IntersectSignedRange(), and llvm::SCEVRewriteVisitor< SC >::visitSMinExpr().
getSMinExpr() [2/2]
const SCEV * ScalarEvolution::getSMinExpr (SmallVectorImpl< const SCEV * > & Operands)
Definition at line 3701 of file ScalarEvolution.cpp.
References getMinMaxExpr(), and llvm::scSMinExpr.
getTruncateExpr()
const SCEV * ScalarEvolution::getTruncateExpr (const SCEV * Op, Type * Ty, unsigned Depth = 0)
Definition at line 1250 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::FlagAnyWrap, getAddExpr(), getAddRecExpr(), getConstant(), getEffectiveSCEVType(), getMulExpr(), llvm::ConstantExpr::getTrunc(), getTruncateExpr(), getTruncateOrSignExtend(), getTruncateOrZeroExtend(), llvm::SCEV::getType(), getTypeSizeInBits(), isSCEVable(), llvm_unreachable, MaxCastDepth, and llvm::scTruncate.
Referenced by generateLoopLatchCheck(), genLoopLimit(), getAddExpr(), getTruncateExpr(), getTruncateOrNoop(), getTruncateOrSignExtend(), getTruncateOrZeroExtend(), getURemExpr(), getZeroExtendExpr(), llvm::SCEVExpander::replaceCongruentIVs(), and llvm::SCEVRewriteVisitor< SC >::visitTruncateExpr().
getTruncateOrNoop()
const SCEV * ScalarEvolution::getTruncateOrNoop (const SCEV * V, Type * Ty)
Return a SCEV corresponding to a conversion of the input value to the specified type.
The conversion must not be widening.
Definition at line 4100 of file ScalarEvolution.cpp.
References assert(), getTruncateExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), and llvm::Type::isIntOrPtrTy().
Referenced by canBeCheaplyTransformed(), getAnyExtendExpr(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), and llvm::SCEVExpander::replaceCongruentIVs().
getTruncateOrSignExtend()
const SCEV * ScalarEvolution::getTruncateOrSignExtend (const SCEV * V, Type * Ty, unsigned Depth = 0)
Return a SCEV corresponding to a conversion of the input value to the specified type.
If the type must be extended, it is sign extended.
Definition at line 4051 of file ScalarEvolution.cpp.
References assert(), getSignExtendExpr(), getTruncateExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), and llvm::Type::isIntOrPtrTy().
Referenced by getGEPExpr(), getSignExtendExpr(), and getTruncateExpr().
getTruncateOrZeroExtend()
const SCEV * ScalarEvolution::getTruncateOrZeroExtend (const SCEV * V, Type * Ty, unsigned Depth = 0)
Return a SCEV corresponding to a conversion of the input value to the specified type.
If the type must be extended, it is zero extended.
Definition at line 4039 of file ScalarEvolution.cpp.
References assert(), getTruncateExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), getZeroExtendExpr(), and llvm::Type::isIntOrPtrTy().
Referenced by BinomialCoefficient(), genLoopLimit(), getNumBytes(), getSignExtendExpr(), getStartForNegStride(), getTruncateExpr(), and getZeroExtendExpr().
getTypeSizeInBits()
uint64_t ScalarEvolution::getTypeSizeInBits (Type * Ty) const
Return the size in bits of the specified type, for which isSCEVable must return true.
Definition at line 3769 of file ScalarEvolution.cpp.
References assert(), getDataLayout(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::Type::isPointerTy(), and isSCEVable().
Referenced by llvm::IVUsers::AddUsersImpl(), llvm::SCEVAAResult::alias(), BinomialCoefficient(), llvm::SCEVExpander::expandCodeFor(), FindLoopCounter(), llvm::SCEVExpander::generateOverflowCheck(), genLoopLimit(), getAddExpr(), getAnyExtendExpr(), getMulExpr(), getNoopOrAnyExtend(), getNoopOrSignExtend(), getNoopOrZeroExtend(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), getSignedOverflowLimitForStep(), getSignExtendExpr(), getTruncateExpr(), getTruncateOrNoop(), getTruncateOrSignExtend(), getTruncateOrZeroExtend(), getUDivExpr(), getUMaxFromMismatchedTypes(), getUnsignedOverflowLimitForStep(), getWiderType(), getZeroExtendExpr(), isAddRecSExtable(), isAddSExtable(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), isMulSExtable(), isSimpleCastedPHI(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecRange(), verify(), and visitIVCast().
getUDivExactExpr()
const SCEV * ScalarEvolution::getUDivExactExpr (const SCEV * LHS, const SCEV * RHS)
Get a canonical unsigned division expression, or something simpler if possible.
There is no representation for an exact udiv in SCEV IR, but we can attempt to remove factors from the LHS and RHS. We can't do this when it's not exact because the udiv may be clearing bits.
Definition at line 3333 of file ScalarEvolution.cpp.
References gcd(), getConstant(), getMulExpr(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), getUDivExactExpr(), getUDivExpr(), llvm::SCEVNAryExpr::hasNoUnsignedWrap(), llvm::SCEVNAryExpr::op_begin(), and llvm::SCEVNAryExpr::op_end().
Referenced by getUDivExactExpr(), and SolveLinEquationWithOverflow().
getUDivExpr()
const SCEV * ScalarEvolution::getUDivExpr (const SCEV * LHS, const SCEV * RHS)
Get a canonical unsigned division expression, or something simpler if possible.
Get a canonical UDivExpr for a recurrence. {X,+,N}/C => {Y,+,N}/C where Y=X-(XN). Safe when CN=0.
Definition at line 3183 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNW, llvm::DITypeRefArray::get(), getAddExpr(), getAddRecExpr(), llvm::SCEVConstant::getAPInt(), getConstant(), getContext(), getEffectiveSCEVType(), getMulExpr(), llvm::SCEV::getType(), getTypeSizeInBits(), llvm::ConstantExpr::getUDiv(), getUDivExpr(), getZeroExtendExpr(), and llvm::scUDivExpr.
Referenced by BinomialCoefficient(), getNewAlignmentDiff(), getUDivExactExpr(), getUDivExpr(), getURemExpr(), getZeroExtendExpr(), and llvm::SCEVRewriteVisitor< SC >::visitUDivExpr().
getUMaxExpr() [1/2]
const SCEV * ScalarEvolution::getUMaxExpr (const SCEV * LHS, const SCEV * RHS)
Definition at line 3686 of file ScalarEvolution.cpp.
References getUMaxExpr().
Referenced by getUMaxExpr(), getUMaxFromMismatchedTypes(), llvm::RuntimePointerChecking::insert(), IntersectUnsignedRange(), and llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr().
getUMaxExpr() [2/2]
const SCEV * ScalarEvolution::getUMaxExpr (SmallVectorImpl< const SCEV * > & Operands)
Definition at line 3691 of file ScalarEvolution.cpp.
References getMinMaxExpr(), and llvm::scUMaxExpr.
getUMaxFromMismatchedTypes()
const SCEV * ScalarEvolution::getUMaxFromMismatchedTypes (const SCEV * LHS, const SCEV * RHS)
Promote the operands to the wider of the types using zero-extension, and then perform a umax operation with them.
Definition at line 4111 of file ScalarEvolution.cpp.
References getNoopOrZeroExtend(), llvm::SCEV::getType(), getTypeSizeInBits(), getUMaxExpr(), and getZeroExtendExpr().
getUMinExpr() [1/2]
const SCEV * ScalarEvolution::getUMinExpr (const SCEV * LHS, const SCEV * RHS)
Definition at line 3705 of file ScalarEvolution.cpp.
References getUMinExpr().
Referenced by getUMinExpr(), getUMinFromMismatchedTypes(), llvm::RuntimePointerChecking::insert(), IntersectUnsignedRange(), and llvm::SCEVRewriteVisitor< SC >::visitUMinExpr().
getUMinExpr() [2/2]
const SCEV * ScalarEvolution::getUMinExpr (SmallVectorImpl< const SCEV * > & Operands)
Definition at line 3711 of file ScalarEvolution.cpp.
References getMinMaxExpr(), and llvm::scUMinExpr.
getUMinFromMismatchedTypes() [1/2]
const SCEV * ScalarEvolution::getUMinFromMismatchedTypes (const SCEV * LHS, const SCEV * RHS)
Promote the operands to the wider of the types using zero-extension, and then perform a umin operation with them.
Definition at line 4124 of file ScalarEvolution.cpp.
References getUMinFromMismatchedTypes().
Referenced by getUMinFromMismatchedTypes().
getUMinFromMismatchedTypes() [2/2]
const SCEV * ScalarEvolution::getUMinFromMismatchedTypes (SmallVectorImpl< const SCEV * > & Ops)
Promote the operands to the wider of the types using zero-extension, and then perform a umin operation with them.
N-ary function.
Definition at line 4130 of file ScalarEvolution.cpp.
References assert(), getNoopOrZeroExtend(), llvm::SCEV::getType(), getUMinExpr(), and getWiderType().
getUnknown()
const SCEV * ScalarEvolution::getUnknown (Value * V)
Definition at line 3732 of file ScalarEvolution.cpp.
References assert(), SCEVUnknown, and llvm::scUnknown.
Referenced by llvm::InductionDescriptor::isFPInductionPHI(), verify(), and llvm::SCEVParameterRewriter::visitUnknown().
getUnsignedRange()
ConstantRange llvm::ScalarEvolution::getUnsignedRange (const SCEV * S) inline
Determine the unsigned range for a particular SCEV.
NOTE: This returns a copy of the reference returned by getRangeRef.
Definition at line 829 of file ScalarEvolution.h.
Referenced by llvm::SCEVAAResult::alias(), getBoundsCheckCond(), getZeroExtendExpr(), mustBeFiniteCountedLoop(), print(), and StrengthenNoWrapFlags().
getUnsignedRangeMax()
APInt llvm::ScalarEvolution::getUnsignedRangeMax (const SCEV * S) inline
Determine the max of the unsigned range for a particular SCEV.
Definition at line 839 of file ScalarEvolution.h.
References llvm::ConstantRange::getUnsignedMax().
Referenced by getUnsignedOverflowLimitForStep(), getZeroExtendExpr(), and SimplifyICmpOperands().
getUnsignedRangeMin()
APInt llvm::ScalarEvolution::getUnsignedRangeMin (const SCEV * S) inline
Determine the min of the unsigned range for a particular SCEV.
Definition at line 834 of file ScalarEvolution.h.
References llvm::ConstantRange::getUnsignedMin().
Referenced by SimplifyICmpOperands().
getURemExpr()
const SCEV * ScalarEvolution::getURemExpr (const SCEV * LHS, const SCEV * RHS)
Represents an unsigned remainder expression based on unsigned division.
Definition at line 3154 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::FlagNUW, llvm::DITypeRefArray::get(), getContext(), getEffectiveSCEVType(), getMinusSCEV(), getMulExpr(), getTruncateExpr(), llvm::SCEV::getType(), getUDivExpr(), getZero(), and getZeroExtendExpr().
Referenced by getZeroExtendExpr().
getWiderType()
Type * ScalarEvolution::getWiderType (Type * Ty1, Type * Ty2) const
Definition at line 3790 of file ScalarEvolution.cpp.
References getTypeSizeInBits().
Referenced by getUMinFromMismatchedTypes().
getWrapPredicate()
const SCEVPredicate * ScalarEvolution::getWrapPredicate (const SCEVAddRecExpr * AR, SCEVWrapPredicate::IncrementWrapFlags AddedFlags)
Definition at line 12008 of file ScalarEvolution.cpp.
References llvm::SCEVPredicate::P_Wrap.
Referenced by llvm::PredicatedScalarEvolution::setNoOverflow().
getZero()
const SCEV * llvm::ScalarEvolution::getZero (Type * Ty) inline
Return a SCEV for the constant 0 of a specific type.
Definition at line 615 of file ScalarEvolution.h.
References getConstant().
Referenced by llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), getAddExpr(), getGEPExpr(), getMinusSCEV(), getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getURemExpr(), llvm::isKnownNegativeInLoop(), llvm::isKnownNonNegativeInLoop(), and isLoopBackedgeGuardedByCond().
getZeroExtendExpr()
const SCEV * ScalarEvolution::getZeroExtendExpr (const SCEV * Op, Type * Ty, unsigned Depth = 0)
Definition at line 1634 of file ScalarEvolution.cpp.
References assert(), llvm::AssumptionCache::assumptions(), llvm::ConstantRange::contains(), extractConstantWithoutWrapping(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, llvm::DITypeRefArray::get(), getAddExpr(), getAddRecExpr(), getConstant(), getContext(), getEffectiveSCEVType(), getMaxBackedgeTakenCount(), getMulExpr(), getSignedRangeMin(), getSignExtendExpr(), getTruncateExpr(), getTruncateOrZeroExtend(), llvm::SCEV::getType(), getTypeSizeInBits(), getUDivExpr(), getUnsignedRange(), getUnsignedRangeMax(), getURemExpr(), getZeroExtendExpr(), llvm::ConstantExpr::getZExt(), llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, isKnownNegative(), isKnownOnEveryIteration(), isKnownPositive(), isLoopBackedgeGuardedByCond(), isSCEVable(), MaxCastDepth, N, llvm::scZeroExtend, llvm::ConstantRange::truncate(), X(), llvm::ConstantRange::zeroExtend(), and llvm::ConstantRange::zextOrTrunc().
Referenced by genLoopLimit(), getAnyExtendExpr(), getNoopOrZeroExtend(), getNumBytes(), getSignExtendExpr(), getTruncateOrZeroExtend(), getUDivExpr(), getUMaxFromMismatchedTypes(), getURemExpr(), getZeroExtendExpr(), IsIncrementNUW(), isSafeDependenceDistance(), verify(), llvm::SCEVRewriteVisitor< SC >::visitZeroExtendExpr(), and willNotOverflow().
hasComputableLoopEvolution()
bool ScalarEvolution::hasComputableLoopEvolution (const SCEV * S, const Loop * L)
Return true if the given SCEV changes value in a known way in the specified loop.
This property being true implies that the value is variant in the loop AND that we can emit an expression to compute the value of the expression at any particular loop iteration.
Definition at line 11672 of file ScalarEvolution.cpp.
References getLoopDisposition(), and LoopComputable.
hasLoopInvariantBackedgeTakenCount()
bool ScalarEvolution::hasLoopInvariantBackedgeTakenCount (const Loop * L)
Return true if the specified loop has an analyzable loop-invariant backedge-taken count.
Definition at line 11403 of file ScalarEvolution.cpp.
References getBackedgeTakenCount().
Referenced by llvm::IVUsers::print(), and PrintLoopInfo().
hasOperand()
bool ScalarEvolution::hasOperand (const SCEV * S, const SCEV * Op) const
Test whether the given SCEV has Op as a direct or indirect operand.
Definition at line 11769 of file ScalarEvolution.cpp.
References llvm::SCEVExprContains().
invalidate()
bool ScalarEvolution::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Definition at line 11917 of file ScalarEvolution.cpp.
References F, llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
isAvailableAtLoopEntry()
bool ScalarEvolution::isAvailableAtLoopEntry (const SCEV * S, const Loop * L)
Determine if the SCEV can be evaluated at loop's entry.
It is true if it doesn't depend on a SCEVUnknown of an instruction which is dominated by the header of loop L.
Definition at line 2397 of file ScalarEvolution.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), isLoopInvariant(), and properlyDominates().
Referenced by llvm::cannotBeMaxInLoop(), llvm::cannotBeMinInLoop(), getAddExpr(), getMulExpr(), llvm::isKnownNegativeInLoop(), llvm::isKnownNonNegativeInLoop(), isKnownViaInduction(), isLoopEntryGuardedByCond(), isSafeDecreasingBound(), and isSafeIncreasingBound().
isBackedgeTakenCountMaxOrZero()
bool ScalarEvolution::isBackedgeTakenCountMaxOrZero (const Loop * L)
Return true if the backedge taken count is either the value returned by getMaxBackedgeTakenCount or zero.
Definition at line 6606 of file ScalarEvolution.cpp.
Referenced by PrintLoopInfo(), and tryToUnrollLoop().
isKnownNegative()
bool ScalarEvolution::isKnownNegative (const SCEV * S)
Test if the given expression is known to be negative.
Definition at line 9054 of file ScalarEvolution.cpp.
References getSignedRangeMax().
Referenced by getSignedOverflowLimitForStep(), getZeroExtendExpr(), isKnownNonZero(), and isSafeDecreasingBound().
isKnownNonNegative()
bool ScalarEvolution::isKnownNonNegative (const SCEV * S)
Test if the given expression is known to be non-negative.
Definition at line 9062 of file ScalarEvolution.cpp.
References getSignedRangeMin().
Referenced by getMinusSCEV(), getSignExtendExpr(), and StrengthenNoWrapFlags().
isKnownNonPositive()
bool ScalarEvolution::isKnownNonPositive (const SCEV * S)
Test if the given expression is known to be non-positive.
Definition at line 9066 of file ScalarEvolution.cpp.
References getSignedRangeMax().
isKnownNonZero()
bool ScalarEvolution::isKnownNonZero (const SCEV * S)
Test if the given expression is known to be non-zero.
Definition at line 9070 of file ScalarEvolution.cpp.
References isKnownNegative(), and isKnownPositive().
isKnownOnEveryIteration()
bool ScalarEvolution::isKnownOnEveryIteration (ICmpInst::Predicate Pred, const SCEVAddRecExpr * LHS, const SCEV * RHS)
Test if the condition described by Pred, LHS, RHS is known to be true on every iteration of the loop of the recurrency LHS.
Definition at line 9150 of file ScalarEvolution.cpp.
References llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVAddRecExpr::getPostIncExpr(), llvm::SCEVAddRecExpr::getStart(), isLoopBackedgeGuardedByCond(), and isLoopEntryGuardedByCond().
Referenced by getSignExtendExpr(), and getZeroExtendExpr().
isKnownPositive()
bool ScalarEvolution::isKnownPositive (const SCEV * S)
Test if the given expression is known to be positive.
Definition at line 9058 of file ScalarEvolution.cpp.
References getSignedRangeMin().
Referenced by getPreStartForExtend(), getSignedOverflowLimitForStep(), getZeroExtendExpr(), isKnownNonZero(), and isSafeDependenceDistance().
isKnownPredicate()
bool ScalarEvolution::isKnownPredicate (ICmpInst::Predicate Pred, const SCEV * LHS, const SCEV * RHS)
Test if the given expression is known to satisfy the condition described by Pred, LHS, and RHS.
Definition at line 9135 of file ScalarEvolution.cpp.
References isKnownViaInduction(), and SimplifyICmpOperands().
Referenced by countToEliminateCompares(), IsKnownPredicateViaAddRecStart(), and normalizePredicate().
isKnownViaInduction()
bool ScalarEvolution::isKnownViaInduction (ICmpInst::Predicate Pred, const SCEV * LHS, const SCEV * RHS)
We'd like to check the predicate on every iteration of the most dominated loop between loops used in LHS and RHS.
To do this we use the following list of steps:
Collect set S all loops on which either LHS or RHS depend.
If S is non-empty a. Let PD be the element of S which is dominated by all other elements. b. Let E(LHS) be value of LHS on entry of PD. To get E(LHS), we should just take LHS and replace all AddRecs that are attached to PD on with their entry values. Define E(RHS) in the same way. c. Let B(LHS) be value of L on backedge of PD. To get B(LHS), we should just take LHS and replace all AddRecs that are attached to PD on with their backedge values. Define B(RHS) in the same way. d. Note that E(LHS) and E(RHS) are automatically available on entry of PD, so we can assert on that. e. Return true if isLoopEntryGuardedByCond(Pred, E(LHS), E(RHS)) && isLoopBackedgeGuardedByCond(Pred, B(LHS), B(RHS))
Definition at line 9086 of file ScalarEvolution.cpp.
References assert(), llvm::DominatorTree::dominates(), getCouldNotCompute(), isAvailableAtLoopEntry(), isLoopBackedgeGuardedByCond(), isLoopEntryGuardedByCond(), and SplitIntoInitAndPostInc().
Referenced by isKnownPredicate().
isLoopBackedgeGuardedByCond()
bool ScalarEvolution::isLoopBackedgeGuardedByCond (const Loop * L, ICmpInst::Predicate Pred, const SCEV * LHS, const SCEV * RHS)
Test whether the backedge of the loop is protected by a conditional between LHS and RHS.
isLoopBackedgeGuardedByCond - Test whether the backedge of the loop is protected by a conditional between LHS and RHS.
This is used to eliminate casts.
This is used to to eliminate casts.
Definition at line 9415 of file ScalarEvolution.cpp.
References assert(), llvm::AssumptionCache::assumptions(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, getAddRecExpr(), llvm::BranchInst::getCondition(), getCouldNotCompute(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), getOne(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), getZero(), llvm::CmpInst::ICMP_ULT, llvm::BranchInst::isConditional(), llvm::DominatorTree::isReachableFromEntry(), llvm::BasicBlockEdge::isSingleEdge(), llvm::verifyFunction(), and VerifyIR.
Referenced by getSignExtendExpr(), getZeroExtendExpr(), isKnownOnEveryIteration(), isKnownViaInduction(), and isLoopInvariantPredicate().
isLoopEntryGuardedByCond()
bool ScalarEvolution::isLoopEntryGuardedByCond (const Loop * L, ICmpInst::Predicate Pred, const SCEV * LHS, const SCEV * RHS)
Test whether entry to the loop is protected by a conditional between LHS and RHS.
This is used to help avoid max expressions in loop trip counts, and to eliminate casts.
Definition at line 9525 of file ScalarEvolution.cpp.
References assert(), llvm::AssumptionCache::assumptions(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::BranchInst::getCondition(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), llvm::CmpInst::getNonStrictPredicate(), llvm::BasicBlock::getParent(), llvm::BranchInst::getSuccessor(), llvm::CmpInst::ICMP_NE, isAvailableAtLoopEntry(), llvm::BranchInst::isUnconditional(), llvm::verifyFunction(), and VerifyIR.
Referenced by llvm::cannotBeMaxInLoop(), llvm::cannotBeMinInLoop(), getNumBytes(), getPreStartForExtend(), llvm::isKnownNegativeInLoop(), llvm::isKnownNonNegativeInLoop(), isKnownOnEveryIteration(), isKnownViaInduction(), isSafeDecreasingBound(), and isSafeIncreasingBound().
isLoopInvariant()
bool ScalarEvolution::isLoopInvariant (const SCEV * S, const Loop * L)
Return true if the value of the given SCEV is unchanging in the specified loop.
Definition at line 11668 of file ScalarEvolution.cpp.
References getLoopDisposition(), and LoopInvariant.
Referenced by computeUnrollAndJamCount(), expandBounds(), genLoopLimit(), getAddRecExpr(), hasComputableBounds(), llvm::RuntimePointerChecking::insert(), llvm::Loop::isAuxiliaryInductionVariable(), isAvailableAtLoopEntry(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::InductionDescriptor::isInductionPHI(), isLoopInvariantPredicate(), isNoWrap(), llvm::LoopAccessInfo::isUniform(), mayUsePostIncMode(), print(), SimplifyICmpOperands(), llvm::stripGetElementPtr(), llvm::InnerLoopVectorizer::widenInstruction(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
isLoopInvariantPredicate()
bool ScalarEvolution::isLoopInvariantPredicate (ICmpInst::Predicate Pred, const SCEV * LHS, const SCEV * RHS, const Loop * L, ICmpInst::Predicate & InvariantPred, const SCEV *& InvariantLHS, const SCEV *& InvariantRHS)
Return true if the result of the predicate LHS Pred RHS is loop invariant with respect to L.
Set InvariantPred, InvariantLHS and InvariantLHS so that InvariantLHS InvariantPred InvariantRHS is the loop invariant form of LHS Pred RHS.
Definition at line 9234 of file ScalarEvolution.cpp.
References llvm::CmpInst::getInversePredicate(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVAddRecExpr::getStart(), llvm::CmpInst::getSwappedPredicate(), isLoopBackedgeGuardedByCond(), isLoopInvariant(), isMonotonicPredicate(), and P.
isMonotonicPredicate()
bool ScalarEvolution::isMonotonicPredicate (const SCEVAddRecExpr * LHS, ICmpInst::Predicate Pred, bool & Increasing)
Return true if, for all loop invariant X, the predicate "LHS `Pred` X" is monotonically increasing or decreasing.
In the former case set Increasing to true and in the latter case set Increasing to false.
A predicate is said to be monotonically increasing if may go from being false to being true as the loop iterates, but never the other way around. A predicate is said to be monotonically decreasing if may go from being true to being false as the loop iterates, but never the other way around.
Definition at line 9158 of file ScalarEvolution.cpp.
References assert(), and llvm::CmpInst::getSwappedPredicate().
Referenced by countToEliminateCompares(), isLoopInvariantPredicate(), and isSafeToTruncateWideIVType().
isSCEVable()
bool ScalarEvolution::isSCEVable (Type * Ty) const
Test if values of the given type are analyzable within the SCEV framework.
This primarily includes integer types, and it can optionally include pointer types if the ScalarEvolution class has access to target-specific information.
Definition at line 3762 of file ScalarEvolution.cpp.
References llvm::Type::isIntOrPtrTy().
Referenced by llvm::IVUsers::AddUsersImpl(), findIVOperand(), getAnyExtendExpr(), getEffectiveSCEVType(), getSCEV(), getSignExtendExpr(), getTruncateExpr(), getTypeSizeInBits(), getZeroExtendExpr(), isExistingPhi(), isHighCostExpansion(), isLoopCounter(), isSimpleIVUser(), llvm::LoopAccessInfo::isUniform(), print(), llvm::PredicatedScalarEvolution::print(), llvm::SCEVExpander::replaceCongruentIVs(), and llvm::InnerLoopVectorizer::widenIntOrFpInduction().
maskFlags()
static LLVM_NODISCARD SCEV::NoWrapFlags llvm::ScalarEvolution::maskFlags (SCEV::NoWrapFlags Flags, int Mask) inline static
Convenient NoWrapFlags manipulation that hides enum casts and is visible in the ScalarEvolution name space.
Definition at line 488 of file ScalarEvolution.h.
Referenced by getAddRecExpr(), getMinusSCEV(), getMulExpr(), getPreStartForExtend(), and StrengthenNoWrapFlags().
print()
void ScalarEvolution::print (raw_ostream & OS) const
Definition at line 11481 of file ScalarEvolution.cpp.
References getLoopDisposition(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), getSCEV(), getSCEVAtScope(), getSignedRange(), getUnsignedRange(), I, instructions, isLoopInvariant(), isSCEVable(), loopDispositionToStr(), llvm::SCEV::print(), llvm::ConstantRange::print(), llvm::Value::printAsOperand(), and PrintLoopInfo().
Referenced by llvm::ScalarEvolutionWrapperPass::print().
properlyDominates()
bool ScalarEvolution::properlyDominates (const SCEV * S, const BasicBlock * BB)
Return true if elements that makes up the given SCEV properly dominate the specified basic block.
Definition at line 11765 of file ScalarEvolution.cpp.
References getBlockDisposition(), and ProperlyDominatesBlock.
Referenced by DoInitialMatch(), isAvailableAtLoopEntry(), llvm::isSafeToExpandAt(), and SimplifyICmpOperands().
rewriteUsingPredicate()
const SCEV * ScalarEvolution::rewriteUsingPredicate (const SCEV * S, const Loop * L, SCEVUnionPredicate & A)
Re-writes the SCEV according to the Predicates in A.
Definition at line 12142 of file ScalarEvolution.cpp.
References llvm::SCEVParameterRewriter::rewrite().
Referenced by llvm::PredicatedScalarEvolution::getSCEV().
setFlags()
static LLVM_NODISCARD SCEV::NoWrapFlags llvm::ScalarEvolution::setFlags (SCEV::NoWrapFlags Flags, SCEV::NoWrapFlags OnFlags) inline static
Definition at line 492 of file ScalarEvolution.h.
Referenced by getAddExpr(), llvm::SCEVWrapPredicate::getImpliedFlags(), llvm::SCEVWrapPredicate::isAlwaysTrue(), llvm::SCEVAddRecExpr::setNoWrapFlags(), and StrengthenNoWrapFlags().
SimplifyICmpOperands()
bool ScalarEvolution::SimplifyICmpOperands (ICmpInst::Predicate & Pred, const SCEV *& LHS, const SCEV *& RHS, unsigned Depth = 0)
Simplify LHS and RHS in a comparison with predicate Pred.
Return true iff any changes were made. If the operands are provably equal or unequal, LHS and RHS are set to the same value and Pred is set to either ICMP_EQ or ICMP_NE.
Definition at line 8857 of file ScalarEvolution.cpp.
References assert(), llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, getAddExpr(), getConstant(), getContext(), llvm::ConstantRange::getEquivalentICmp(), llvm::IRBuilderBase::getFalse(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::ConstantExpr::getICmp(), llvm::SCEVAddRecExpr::getLoop(), getSignedRangeMax(), getSignedRangeMin(), llvm::CmpInst::getSwappedPredicate(), llvm::SCEV::getType(), getUnsignedRangeMax(), getUnsignedRangeMin(), HasSameValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::CmpInst::isFalseWhenEqual(), llvm::ConstantRange::isFullSet(), isLoopInvariant(), llvm::Constant::isNullValue(), llvm::CmpInst::isTrueWhenEqual(), llvm::ConstantRange::makeExactICmpRegion(), properlyDominates(), and SimplifyICmpOperands().
Referenced by isKnownPredicate(), and SimplifyICmpOperands().
SplitIntoInitAndPostInc()
std::pair< const SCEV *, const SCEV * > ScalarEvolution::SplitIntoInitAndPostInc (const Loop * L, const SCEV * S)
Splits SCEV expression S into two SCEVs.
One of them is obtained from S by substitution of all AddRec sub-expression related to loop L with initial value of that SCEV. The second is obtained from S by substitution of all AddRec sub-expressions related to loop L with post increment of this AddRec in the loop L. In both cases all other AddRec sub-expressions (not related to L) remain the same. If the S contains non-invariant unknown SCEV the function returns CouldNotCompute SCEV in both values of std::pair. For example, for SCEV S={0, +, 1}<L1> + {0, +, 1}<L2> and loop L=L1 the function returns pair: first = {0, +, 1}<L2> second = {1, +, 1}<L1> + {0, +, 1}<L2> We can see that for the first AddRec sub-expression it was replaced with 0 (initial value) for the first element and to {1, +, 1}<L1> (post increment value) for the second one. In both cases AddRec expression related to L2 remains the same.
Definition at line 9075 of file ScalarEvolution.cpp.
References assert(), getCouldNotCompute(), and llvm::SCEVParameterRewriter::rewrite().
Referenced by isKnownViaInduction().
verify()
void ScalarEvolution::verify () const
Definition at line 11844 of file ScalarEvolution.cpp.
References llvm::LoopBase< BlockT, LoopT >::begin(), containsUndefs(), llvm::dbgs(), llvm::LoopBase< BlockT, LoopT >::end(), getBackedgeTakenCount(), getConstant(), getCouldNotCompute(), getMinusSCEV(), getTypeSizeInBits(), getUnknown(), llvm::SCEVUnknown::getValue(), and getZeroExtendExpr().
Referenced by LoopFuser::fuseLoops(), and llvm::ScalarEvolutionWrapperPass::verifyAnalysis().
Friends And Related Function Documentation
SCEVCallbackVH
friend class SCEVCallbackVH friend
Definition at line 1115 of file ScalarEvolution.h.
Referenced by getSCEV().
SCEVExpander
friend class SCEVExpander friend
Definition at line 1116 of file ScalarEvolution.h.
SCEVUnknown
friend class SCEVUnknown friend
Definition at line 1117 of file ScalarEvolution.h.
Referenced by getUnknown().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp