LLVM: llvm::orc::FailedToMaterialize Class Reference
llvm::orc::FailedToMaterialize Class Reference
Used to notify a JITDylib that the given set of symbols failed to materialize.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
FailedToMaterialize (SymbolNameSet Symbols)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print an error message to an output stream.
const SymbolNameSet & getSymbols () const
Public Member Functions inherited from llvm::ErrorInfo< FailedToMaterialize >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< FailedToMaterialize >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Used to notify a JITDylib that the given set of symbols failed to materialize.
Definition at line 123 of file Core.h.
Constructor & Destructor Documentation
FailedToMaterialize()
llvm::orc::FailedToMaterialize::FailedToMaterialize (SymbolNameSet Symbols)
Definition at line 247 of file Core.cpp.
References assert(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty().
Member Function Documentation
convertToErrorCode()
std::error_code llvm::orc::FailedToMaterialize::convertToErrorCode () const override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 252 of file Core.cpp.
References llvm::orc::orcError(), and llvm::orc::UnknownORCError.
getSymbols()
const SymbolNameSet & llvm::orc::FailedToMaterialize::getSymbols () const inline
Definition at line 130 of file Core.h.
log()
void llvm::orc::FailedToMaterialize::log (raw_ostream & OS) const override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 256 of file Core.cpp.
Member Data Documentation
ID
char llvm::orc::FailedToMaterialize::ID = 0 static
Definition at line 125 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp