LLVM: llvm::orc::rpc::SerializationTraits< ChannelT, Error > Class Template Reference
llvm::orc::rpc::SerializationTraits< ChannelT, Error > Class Template Reference
#include "llvm/ExecutionEngine/Orc/RPCSerialization.h"
Public Types
using WrappedErrorSerializer = std::function< Error(ChannelT &C, const ErrorInfoBase &)>
using WrappedErrorDeserializer = std::function< Error(ChannelT &C, Error &Err)>
Static Public Member Functions
template<typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor >
static void registerErrorType (std::string Name, SerializeFtor Serialize, DeserializeFtor Deserialize)
static Error serialize (ChannelT &C, Error &&Err)
static Error deserialize (ChannelT &C, Error &Err)
Detailed Description
template<typename ChannelT>
class llvm::orc::rpc::SerializationTraits< ChannelT, Error >
Definition at line 329 of file RPCSerialization.h.
Member Typedef Documentation
WrappedErrorDeserializer
template<typename ChannelT > using llvm::orc::rpc::SerializationTraits< ChannelT, Error >::WrappedErrorDeserializer = std::function<Error(ChannelT &C, Error &Err)>
Definition at line 335 of file RPCSerialization.h.
WrappedErrorSerializer
template<typename ChannelT > using llvm::orc::rpc::SerializationTraits< ChannelT, Error >::WrappedErrorSerializer = std::function<Error(ChannelT &C, const ErrorInfoBase&)>
Definition at line 332 of file RPCSerialization.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, Error >::deserialize (ChannelT & C, Error & Err) inline static
Definition at line 389 of file RPCSerialization.h.
References assert(), C, llvm::orc::rpc::deserializeSeq(), llvm::Lock, and llvm::Error::success().
registerErrorType()
template<typename ChannelT > template<typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor > static void llvm::orc::rpc::SerializationTraits< ChannelT, Error >::registerErrorType (std::string Name, SerializeFtor Serialize, DeserializeFtor Deserialize) inline static
Definition at line 340 of file RPCSerialization.h.
References assert(), C, I, llvm::Lock, Name, and llvm::orc::rpc::serializeSeq().
serialize()
template<typename ChannelT > static Error llvm::orc::rpc::SerializationTraits< ChannelT, Error >::serialize (ChannelT & C, Error && Err) inline static
Definition at line 374 of file RPCSerialization.h.
References C, llvm::ErrorInfoBase::dynamicClassID(), llvm::handleErrors(), if(), llvm::Lock, llvm::orc::rpc::serializeSeq(), and SI.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCSerialization.h