LLVM: llvm::DWARF5AccelTableStaticData Class Reference
llvm::DWARF5AccelTableStaticData Class Reference
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
DWARF5AccelTableStaticData (uint64_t DieOffset, unsigned DieTag, unsigned CUIndex)
void print (raw_ostream &OS) const override
uint64_t getDieOffset () const
unsigned getDieTag () const
unsigned getCUIndex () const
Public Member Functions inherited from llvm::AccelTableData
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
virtual void print (raw_ostream &OS) const =0
Static Public Member Functions
static uint32_t hash (StringRef Name)
Protected Member Functions
uint64_t order () const override
virtual uint64_t order () const =0
Protected Attributes
uint64_t DieOffset
unsigned DieTag
unsigned CUIndex
Detailed Description
Definition at line 272 of file AccelTable.h.
Constructor & Destructor Documentation
DWARF5AccelTableStaticData()
llvm::DWARF5AccelTableStaticData::DWARF5AccelTableStaticData (uint64_t DieOffset, unsigned DieTag, unsigned CUIndex) inline
Definition at line 276 of file AccelTable.h.
Member Function Documentation
getCUIndex()
unsigned llvm::DWARF5AccelTableStaticData::getCUIndex () const inline
Definition at line 286 of file AccelTable.h.
References CUIndex.
getDieOffset()
uint64_t llvm::DWARF5AccelTableStaticData::getDieOffset () const inline
Definition at line 284 of file AccelTable.h.
References DieOffset.
Referenced by print().
getDieTag()
unsigned llvm::DWARF5AccelTableStaticData::getDieTag () const inline
Definition at line 285 of file AccelTable.h.
References DieTag.
Referenced by print().
hash()
static uint32_t llvm::DWARF5AccelTableStaticData::hash (StringRef Name) inline static
Definition at line 274 of file AccelTable.h.
References llvm::caseFoldingDjbHash(), and Name.
order()
uint64_t llvm::DWARF5AccelTableStaticData::order () const inline override protected virtual
Implements llvm::AccelTableData.
Definition at line 293 of file AccelTable.h.
References DieOffset.
print()
void DWARF5AccelTableStaticData::print (raw_ostream & OS) const override virtual
Implements llvm::AccelTableData.
Definition at line 686 of file AccelTable.cpp.
References getDieOffset(), getDieTag(), and llvm::dwarf::TagString().
Member Data Documentation
CUIndex
unsigned llvm::DWARF5AccelTableStaticData::CUIndex protected
Definition at line 291 of file AccelTable.h.
Referenced by getCUIndex().
DieOffset
uint64_t llvm::DWARF5AccelTableStaticData::DieOffset protected
Definition at line 289 of file AccelTable.h.
Referenced by getDieOffset(), and order().
DieTag
unsigned llvm::DWARF5AccelTableStaticData::DieTag protected
Definition at line 290 of file AccelTable.h.
Referenced by getDieTag().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp