LLVM: llvm::iterator_range< IteratorT > Class Template Reference
llvm::iterator_range< IteratorT > Class Template Reference
A range adaptor for a pair of iterators.
#include "llvm/ADT/iterator_range.h"
Public Member Functions
template<typename Container >
iterator_range (Container &&c)
iterator_range (IteratorT begin_iterator, IteratorT end_iterator)
IteratorT begin () const
IteratorT end () const
Detailed Description
template<typename IteratorT>
class llvm::iterator_range< IteratorT >
A range adaptor for a pair of iterators.
This just wraps two iterators into a range-compatible interface. Nothing fancy at all.
Definition at line 31 of file iterator_range.h.
Constructor & Destructor Documentation
iterator_range() [1/2]
template<typename IteratorT > template<typename Container > llvm::iterator_range< IteratorT >::iterator_range (Container && c) inline
Definition at line 38 of file iterator_range.h.
iterator_range() [2/2]
template<typename IteratorT > llvm::iterator_range< IteratorT >::iterator_range (IteratorT begin_iterator, IteratorT end_iterator) inline
Definition at line 41 of file iterator_range.h.
Member Function Documentation
begin()
template<typename IteratorT > IteratorT llvm::iterator_range< IteratorT >::begin () const inline
Definition at line 45 of file iterator_range.h.
Referenced by llvm::orc::CtorDtorRunner::add(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::format_provider< llvm::iterator_range< IterT > >::format(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), and llvm::SmallVector< T, N >::SmallVector().
end()
template<typename IteratorT > IteratorT llvm::iterator_range< IteratorT >::end () const inline
Definition at line 46 of file iterator_range.h.
Referenced by llvm::format_provider< llvm::iterator_range< IterT > >::format(), and llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge().
The documentation for this class was generated from the following file:
include/llvm/ADT/iterator_range.h