LLVM: llvm::ConvergingVLIWScheduler Class Reference
llvm::ConvergingVLIWScheduler Class Reference
ConvergingVLIWScheduler shrinks the unscheduled zone using heuristics to balance the schedule.
#include "Target/Hexagon/HexagonMachineScheduler.h"
Public Types
enum { TopQID = 1 , BotQID = 2 , LogMaxQID = 2 }
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Public Member Functions
ConvergingVLIWScheduler ()
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void schedNode (SUnit *SU, bool IsTopNode) override
Update the scheduler's state after scheduling a node.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
unsigned reportPackets ()
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual SUnit * pickNode (bool &IsTopNode)=0
Pick the next node to schedule, or return NULL.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
virtual void releaseTopNode (SUnit *SU)=0
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
virtual void releaseBottomNode (SUnit *SU)=0
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Protected Member Functions
SUnit * pickNodeBidrectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
int pressureChange (const SUnit *SU, bool isBotUp)
Check if the instruction changes the register pressure of a register in the high pressure set.
int SchedulingCost (ReadyQueue &Q, SUnit *SU, SchedCandidate &Candidate, RegPressureDelta &Delta, bool verbose)
Single point to compute overall scheduling cost.
CandResult pickNodeFromQueue (VLIWSchedBoundary &Zone, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
Pick the best candidate from the top queue.
void traceCandidate (const char *Label, const ReadyQueue &Q, SUnit *SU, int Cost, PressureChange P=PressureChange())
void readyQueueVerboseDump (const RegPressureTracker &RPTracker, SchedCandidate &Candidate, ReadyQueue &Q)
Detailed Description
ConvergingVLIWScheduler shrinks the unscheduled zone using heuristics to balance the schedule.
Definition at line 110 of file HexagonMachineScheduler.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Enumerator
TopQID
BotQID
LogMaxQID
Definition at line 229 of file HexagonMachineScheduler.h.
Constructor & Destructor Documentation
ConvergingVLIWScheduler()
llvm::ConvergingVLIWScheduler::ConvergingVLIWScheduler () inline
Definition at line 235 of file HexagonMachineScheduler.h.
Member Function Documentation
initialize()
void ConvergingVLIWScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 253 of file HexagonMachineScheduler.cpp.
References assert(), llvm::ForceBottomUp, llvm::ForceTopDown, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSchedModel::getInstrItineraries(), llvm::VLIWMachineScheduler::getRegClassInfo(), llvm::ScheduleDAGMILive::getRegPressure(), llvm::RegisterClassInfo::getRegPressureSetLimit(), llvm::ScheduleDAGInstrs::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::RegisterPressure::MaxSetPressure, llvm::ScheduleDAG::MF, RPThreshold, and TII.
pickNode()
SUnit * ConvergingVLIWScheduler::pickNode (bool & IsTopNode) override virtual
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
Implements llvm::MachineSchedStrategy.
Definition at line 945 of file HexagonMachineScheduler.cpp.
References assert(), llvm::ScheduleDAGMI::bottom(), llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::ForceBottomUp, llvm::ForceTopDown, llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isBottomReady(), llvm::SUnit::isTopReady(), LLVM_DEBUG, pickNodeBidrectional(), pickNodeFromQueue(), reportPackets(), and llvm::ScheduleDAGMI::top().
pickNodeBidrectional()
SUnit * ConvergingVLIWScheduler::pickNodeBidrectional (bool & IsTopNode) protected
Pick the best candidate node from either the top or bottom queue.
Definition at line 879 of file HexagonMachineScheduler.cpp.
References assert(), llvm::dbgs(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), LLVM_DEBUG, and pickNodeFromQueue().
Referenced by pickNode().
pickNodeFromQueue()
ConvergingVLIWScheduler::CandResult ConvergingVLIWScheduler::pickNodeFromQueue (VLIWSchedBoundary & Zone, const RegPressureTracker & RPTracker, SchedCandidate & Candidate) protected
Pick the best candidate from the top queue.
TODO: getMaxPressureDelta results can be mostly cached for each SUnit during DAG building. To adjust for the current scheduling location we need to maintain the number of vreg uses remaining to be top-scheduled.
Definition at line 764 of file HexagonMachineScheduler.cpp.
References llvm::ReadyQueue::begin(), BotQID, llvm::ReadyQueue::dump(), E, llvm::ReadyQueue::end(), llvm::ReadyQueue::getID(), llvm::ScheduleDAGMILive::getRegionCriticalPSets(), llvm::ScheduleDAGMILive::getRegPressure(), llvm::getWeakLeft(), I, LLVM_DEBUG, llvm::RegisterPressure::MaxSetPressure, readyQueueVerboseDump(), SchedDebugVerboseLevel, SchedulingCost(), TopQID, traceCandidate(), and UseNewerCandidate.
Referenced by pickNode(), and pickNodeBidrectional().
pressureChange()
int ConvergingVLIWScheduler::pressureChange (const SUnit * SU, bool isBotUp) protected
Check if the instruction changes the register pressure of a register in the high pressure set.
The function returns a negative value if the pressure decreases and a positive value is the pressure increases. If the instruction doesn't use a high pressure register or doesn't change the register pressure, then return 0.
Definition at line 553 of file HexagonMachineScheduler.cpp.
References llvm::ScheduleDAGMILive::getPressureDiff(), and P.
Referenced by SchedulingCost().
readyQueueVerboseDump()
void ConvergingVLIWScheduler::readyQueueVerboseDump (const RegPressureTracker & RPTracker, SchedCandidate & Candidate, ReadyQueue & Q) protected
Definition at line 497 of file HexagonMachineScheduler.cpp.
References llvm::ReadyQueue::begin(), llvm::dbgs(), E, llvm::ReadyQueue::end(), llvm::RegPressureTracker::getMaxPressureDelta(), llvm::ReadyQueue::getName(), llvm::ScheduleDAGMILive::getRegionCriticalPSets(), llvm::ScheduleDAGMILive::getRegPressure(), I, llvm::RegisterPressure::MaxSetPressure, and SchedulingCost().
Referenced by pickNodeFromQueue().
releaseBottomNode()
void ConvergingVLIWScheduler::releaseBottomNode (SUnit * SU) override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 304 of file HexagonMachineScheduler.cpp.
References assert(), llvm::SUnit::BotReadyCycle, E, llvm::SUnit::getInstr(), I, llvm::SUnit::isScheduled, and llvm::SUnit::Succs.
releaseTopNode()
void ConvergingVLIWScheduler::releaseTopNode (SUnit * SU) override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 288 of file HexagonMachineScheduler.cpp.
References llvm::SDep::getLatency(), llvm::SDep::getSUnit(), llvm::SUnit::isScheduled, llvm::SUnit::Preds, and llvm::SUnit::TopReadyCycle.
reportPackets()
unsigned llvm::ConvergingVLIWScheduler::reportPackets () inline
Definition at line 247 of file HexagonMachineScheduler.h.
Referenced by pickNode().
schedNode()
void ConvergingVLIWScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Update the scheduler's state after scheduling a node.
This is the same node that was just returned by pickNode(). However, VLIWMachineScheduler needs to update it's state based on the current cycle before MachineSchedStrategy does.
Implements llvm::MachineSchedStrategy.
Definition at line 994 of file HexagonMachineScheduler.cpp.
References llvm::SUnit::BotReadyCycle, and llvm::SUnit::TopReadyCycle.
SchedulingCost()
int ConvergingVLIWScheduler::SchedulingCost (ReadyQueue & Q, SUnit * SU, SchedCandidate & Candidate, RegPressureDelta & Delta, bool verbose) protected
Single point to compute overall scheduling cost.
TODO: More heuristics will be used soon.
Definition at line 576 of file HexagonMachineScheduler.cpp.
References BotQID, CheckEarlyAvail, llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::dbgs(), llvm::RegPressureDelta::Excess, llvm::SUnit::getDepth(), llvm::SUnit::getHeight(), llvm::ReadyQueue::getID(), llvm::SUnit::getInstr(), llvm::HexagonSubtarget::getInstrInfo(), llvm::SDep::getLatency(), llvm::MachineFunction::getSubtarget(), llvm::SDep::getSUnit(), llvm::PressureChange::getUnitInc(), llvm::getWeakLeft(), IgnoreBBRegPressure, llvm::SDep::isAssignedRegDep(), llvm::SUnit::isInstr(), llvm::MachineInstr::isPseudo(), llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, isSingleUnscheduledPred(), isSingleUnscheduledSucc(), LLVM_DEBUG, llvm::ScheduleDAG::MF, llvm::SUnit::Preds, pressureChange(), PriorityOne, PriorityThree, PriorityTwo, ScaleTwo, SI, llvm::SUnit::Succs, and TopQID.
Referenced by pickNodeFromQueue(), and readyQueueVerboseDump().
traceCandidate()
void ConvergingVLIWScheduler::traceCandidate (const char * Label, const ReadyQueue & Q, SUnit * SU, int Cost, PressureChange P = PressureChange()) protected
Definition at line 484 of file HexagonMachineScheduler.cpp.
References llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::ReadyQueue::getName(), llvm::TargetRegisterInfo::getRegPressureSetName(), P, and llvm::ScheduleDAG::TRI.
Referenced by pickNodeFromQueue().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonMachineScheduler.h
lib/Target/Hexagon/HexagonMachineScheduler.cpp