LLVM: llvm::object::WasmSectionOrderChecker Class Reference
llvm::object::WasmSectionOrderChecker Class Reference
#include "llvm/Object/Wasm.h"
Public Types
enum : int {
WASM_SEC_ORDER_NONE = 0 , WASM_SEC_ORDER_TYPE , WASM_SEC_ORDER_IMPORT , WASM_SEC_ORDER_FUNCTION ,
WASM_SEC_ORDER_TABLE , WASM_SEC_ORDER_MEMORY , WASM_SEC_ORDER_GLOBAL , WASM_SEC_ORDER_EVENT ,
WASM_SEC_ORDER_EXPORT , WASM_SEC_ORDER_START , WASM_SEC_ORDER_ELEM , WASM_SEC_ORDER_DATACOUNT ,
WASM_SEC_ORDER_CODE , WASM_SEC_ORDER_DATA , WASM_SEC_ORDER_DYLINK , WASM_SEC_ORDER_LINKING ,
WASM_SEC_ORDER_RELOC , WASM_SEC_ORDER_NAME , WASM_SEC_ORDER_PRODUCERS , WASM_SEC_ORDER_TARGET_FEATURES ,
WASM_NUM_SEC_ORDERS
}
Public Member Functions
bool isValidSectionOrder (unsigned ID, StringRef CustomSectionName="")
Static Public Attributes
static int DisallowedPredecessors [WASM_NUM_SEC_ORDERS][WASM_NUM_SEC_ORDERS]
Detailed Description
Definition at line 293 of file Wasm.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
WASM_SEC_ORDER_NONE
WASM_SEC_ORDER_TYPE
WASM_SEC_ORDER_IMPORT
WASM_SEC_ORDER_FUNCTION
WASM_SEC_ORDER_TABLE
WASM_SEC_ORDER_MEMORY
WASM_SEC_ORDER_GLOBAL
WASM_SEC_ORDER_EVENT
WASM_SEC_ORDER_EXPORT
WASM_SEC_ORDER_START
WASM_SEC_ORDER_ELEM
WASM_SEC_ORDER_DATACOUNT
WASM_SEC_ORDER_CODE
WASM_SEC_ORDER_DATA
WASM_SEC_ORDER_DYLINK
WASM_SEC_ORDER_LINKING
WASM_SEC_ORDER_RELOC
WASM_SEC_ORDER_NAME
WASM_SEC_ORDER_PRODUCERS
WASM_SEC_ORDER_TARGET_FEATURES
WASM_NUM_SEC_ORDERS
Definition at line 296 of file Wasm.h.
Member Function Documentation
isValidSectionOrder()
bool WasmSectionOrderChecker::isValidSectionOrder (unsigned ID, StringRef CustomSectionName = "")
Definition at line 1636 of file WasmObjectFile.cpp.
References DisallowedPredecessors, llvm::SmallVectorBase::empty(), I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), WASM_NUM_SEC_ORDERS, and WASM_SEC_ORDER_NONE.
Referenced by readSection().
Member Data Documentation
DisallowedPredecessors
int WasmSectionOrderChecker::DisallowedPredecessors static
Initial value:
= {
  {},
  {WASM_SEC_ORDER_TYPE, WASM_SEC_ORDER_IMPORT},
  {WASM_SEC_ORDER_IMPORT, WASM_SEC_ORDER_FUNCTION},
  {WASM_SEC_ORDER_FUNCTION, WASM_SEC_ORDER_TABLE},
  {WASM_SEC_ORDER_TABLE, WASM_SEC_ORDER_MEMORY},
  {WASM_SEC_ORDER_MEMORY, WASM_SEC_ORDER_GLOBAL},
  {WASM_SEC_ORDER_GLOBAL, WASM_SEC_ORDER_EVENT},
  {WASM_SEC_ORDER_EVENT, WASM_SEC_ORDER_EXPORT},
  {WASM_SEC_ORDER_EXPORT, WASM_SEC_ORDER_START},
  {WASM_SEC_ORDER_START, WASM_SEC_ORDER_ELEM},
  {WASM_SEC_ORDER_ELEM, WASM_SEC_ORDER_DATACOUNT},
  {WASM_SEC_ORDER_DATACOUNT, WASM_SEC_ORDER_CODE},
  {WASM_SEC_ORDER_CODE, WASM_SEC_ORDER_DATA},
  {WASM_SEC_ORDER_DATA, WASM_SEC_ORDER_LINKING},
  {WASM_SEC_ORDER_DYLINK, WASM_SEC_ORDER_TYPE},
  {WASM_SEC_ORDER_LINKING, WASM_SEC_ORDER_RELOC, WASM_SEC_ORDER_NAME},
  {},
  {WASM_SEC_ORDER_NAME, WASM_SEC_ORDER_PRODUCERS},
  {WASM_SEC_ORDER_PRODUCERS, WASM_SEC_ORDER_TARGET_FEATURES},
  {WASM_SEC_ORDER_TARGET_FEATURES}
}
Definition at line 336 of file Wasm.h.
Referenced by isValidSectionOrder().
The documentation for this class was generated from the following files:
include/llvm/Object/Wasm.h
lib/Object/WasmObjectFile.cpp