LLVM: llvm::jitlink::Edge Class Reference
llvm::jitlink::Edge Class Reference
Edge class.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Types
using Kind = uint8_t
using GenericEdgeKind = enum :Kind { Invalid, FirstKeepAlive, KeepAlive=FirstKeepAlive, LayoutNext, FirstRelocation }
using OffsetT = uint32_t
using AddendT = int64_t
Public Member Functions
Edge (Kind K, OffsetT Offset, Atom &Target, AddendT Addend)
OffsetT getOffset () const
Kind getKind () const
void setKind (Kind K)
bool isRelocation () const
Kind getRelocation () const
bool isKeepAlive () const
Atom & getTarget () const
void setTarget (Atom &Target)
AddendT getAddend () const
void setAddend (AddendT Addend)
Detailed Description
Edge class.
Represents both object file relocations, as well as layout and keep-alive constraints.
Definition at line 58 of file JITLink.h.
Member Typedef Documentation
AddendT
using llvm::jitlink::Edge::AddendT = int64_t
Definition at line 71 of file JITLink.h.
GenericEdgeKind
using llvm::jitlink::Edge::GenericEdgeKind = enum : Kind { Invalid, FirstKeepAlive, KeepAlive = FirstKeepAlive, LayoutNext, FirstRelocation }
Definition at line 62 of file JITLink.h.
Kind
using llvm::jitlink::Edge::Kind = uint8_t
Definition at line 60 of file JITLink.h.
OffsetT
using llvm::jitlink::Edge::OffsetT = uint32_t
Definition at line 70 of file JITLink.h.
Constructor & Destructor Documentation
Edge()
llvm::jitlink::Edge::Edge (Kind K, OffsetT Offset, Atom & Target, AddendT Addend) inline
Definition at line 73 of file JITLink.h.
Member Function Documentation
getAddend()
AddendT llvm::jitlink::Edge::getAddend () const inline
Definition at line 87 of file JITLink.h.
getKind()
Kind llvm::jitlink::Edge::getKind () const inline
Definition at line 77 of file JITLink.h.
getOffset()
OffsetT llvm::jitlink::Edge::getOffset () const inline
Definition at line 76 of file JITLink.h.
getRelocation()
Kind llvm::jitlink::Edge::getRelocation () const inline
Definition at line 80 of file JITLink.h.
References assert(), and isRelocation().
getTarget()
Atom & llvm::jitlink::Edge::getTarget () const inline
Definition at line 85 of file JITLink.h.
isKeepAlive()
bool llvm::jitlink::Edge::isKeepAlive () const inline
Definition at line 84 of file JITLink.h.
isRelocation()
bool llvm::jitlink::Edge::isRelocation () const inline
Definition at line 79 of file JITLink.h.
Referenced by getRelocation().
setAddend()
void llvm::jitlink::Edge::setAddend (AddendT Addend) inline
Definition at line 88 of file JITLink.h.
setKind()
void llvm::jitlink::Edge::setKind (Kind K) inline
Definition at line 78 of file JITLink.h.
setTarget()
void llvm::jitlink::Edge::setTarget (Atom & Target) inline
Definition at line 86 of file JITLink.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h