LLVM: llvm::SelectionDAG Class Reference
llvm::SelectionDAG Class Reference
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
#include "llvm/CodeGen/SelectionDAG.h"
Classes
struct DAGNodeDeletedListener
struct DAGUpdateListener
Clients of various APIs that cause global effects on the DAG can optionally implement this interface.
Public Types
enum OverflowKind { OFK_Never , OFK_Sometime , OFK_Always }
Used to represent the possible overflow behavior of an operation.
using allnodes_const_iterator = ilist< SDNode >::const_iterator
using allnodes_iterator = ilist< SDNode >::iterator
Public Member Functions
SelectionDAG (const TargetMachine &TM, CodeGenOpt::Level)
SelectionDAG (const SelectionDAG &)=delete
SelectionDAG & operator= (const SelectionDAG &)=delete
~SelectionDAG ()
void init (MachineFunction &NewMF, OptimizationRemarkEmitter &NewORE, Pass *PassPtr, const TargetLibraryInfo *LibraryInfo, LegacyDivergenceAnalysis *Divergence)
Prepare this SelectionDAG to process code in the given MachineFunction.
void setFunctionLoweringInfo (FunctionLoweringInfo *FuncInfo)
void clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
MachineFunction & getMachineFunction () const
const Pass * getPass () const
const DataLayout & getDataLayout () const
const TargetMachine & getTarget () const
const TargetSubtargetInfo & getSubtarget () const
const TargetLowering & getTargetLoweringInfo () const
const TargetLibraryInfo & getLibInfo () const
const SelectionDAGTargetInfo & getSelectionDAGInfo () const
const LegacyDivergenceAnalysis * getDivergenceAnalysis () const
LLVMContext * getContext () const
OptimizationRemarkEmitter & getORE () const
void viewGraph (const std::string &Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
void viewGraph ()
void clearGraphAttrs ()
Clear all previously defined node graph attributes.
void setGraphAttrs (const SDNode *N, const char *Attrs)
Set graph attributes for a node. (eg. "color=red".)
const std::string getGraphAttrs (const SDNode *N) const
Get graph attributes for a node.
void setGraphColor (const SDNode *N, const char *Color)
Convenience for setting node color attribute.
void setSubgraphColor (SDNode *N, const char *Color)
Convenience for setting subgraph color attribute.
allnodes_const_iterator allnodes_begin () const
allnodes_const_iterator allnodes_end () const
allnodes_iterator allnodes_begin ()
allnodes_iterator allnodes_end ()
ilist< SDNode >::size_type allnodes_size () const
iterator_range< allnodes_iterator > allnodes ()
iterator_range< allnodes_const_iterator > allnodes () const
const SDValue & getRoot () const
Return the root tag of the SelectionDAG.
SDValue getEntryNode () const
Return the token chain corresponding to the entry of the function.
const SDValue & setRoot (SDValue N)
Set the current root tag of the SelectionDAG.
void VerifyDAGDiverence ()
void Combine (CombineLevel Level, AliasAnalysis *AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
bool LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
void Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeOp (SDNode *N, SmallSetVector< SDNode *, 16 > &UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
void RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
void DeleteNode (SDNode *N)
Remove the specified node from the system.
SDVTList getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
SDVTList getVTList (EVT VT1, EVT VT2)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
SDVTList getVTList (ArrayRef< EVT > VTs)
SDValue getGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, bool isTargetGA=false, unsigned char TargetFlags=0)
SDValue getTargetGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, unsigned char TargetFlags=0)
SDValue getFrameIndex (int FI, EVT VT, bool isTarget=false)
SDValue getTargetFrameIndex (int FI, EVT VT)
SDValue getJumpTable (int JTI, EVT VT, bool isTarget=false, unsigned char TargetFlags=0)
SDValue getTargetJumpTable (int JTI, EVT VT, unsigned char TargetFlags=0)
SDValue getConstantPool (const Constant *C, EVT VT, unsigned Align=0, int Offs=0, bool isT=false, unsigned char TargetFlags=0)
SDValue getTargetConstantPool (const Constant *C, EVT VT, unsigned Align=0, int Offset=0, unsigned char TargetFlags=0)
SDValue getConstantPool (MachineConstantPoolValue *C, EVT VT, unsigned Align=0, int Offs=0, bool isT=false, unsigned char TargetFlags=0)
SDValue getTargetConstantPool (MachineConstantPoolValue *C, EVT VT, unsigned Align=0, int Offset=0, unsigned char TargetFlags=0)
SDValue getTargetIndex (int Index, EVT VT, int64_t Offset=0, unsigned char TargetFlags=0)
SDValue getBasicBlock (MachineBasicBlock *MBB)
SDValue getBasicBlock (MachineBasicBlock *MBB, SDLoc dl)
SDValue getExternalSymbol (const char *Sym, EVT VT)
SDValue getExternalSymbol (const char *Sym, const SDLoc &dl, EVT VT)
SDValue getTargetExternalSymbol (const char *Sym, EVT VT, unsigned char TargetFlags=0)
SDValue getMCSymbol (MCSymbol *Sym, EVT VT)
SDValue getValueType (EVT)
SDValue getRegister (unsigned Reg, EVT VT)
SDValue getRegisterMask (const uint32_t *RegMask)
SDValue getEHLabel (const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getLabelNode (unsigned Opcode, const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, bool isTarget=false, unsigned char TargetFlags=0)
SDValue getTargetBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, unsigned char TargetFlags=0)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N, SDValue Glue)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, SDValue Reg, SDValue N, SDValue Glue)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT, SDValue Glue)
SDValue getCondCode (ISD::CondCode Cond)
SDValue getVectorShuffle (EVT VT, const SDLoc &dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDValue > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDUse > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getSplatBuildVector (EVT VT, const SDLoc &DL, SDValue Op)
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
SDValue getCommutedVectorShuffle (const ShuffleVectorSDNode &SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
SDValue getFPExtendOrRound (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
SDValue getAnyExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
SDValue getSExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
SDValue getZExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
SDValue getZeroExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
SDValue getPtrExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
SDValue getPtrExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
SDValue getBoolExtOrTrunc (SDValue Op, const SDLoc &SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
SDValue getNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
SDValue getLogicalNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Op, int64_t Offset)
Create an add instruction with appropriate flags when used for addressing some offset of an object.
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Op, SDValue Offset)
SDValue getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc &DL)
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
SDValue getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc &DL)
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
bool isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
SDValue getUNDEF (EVT VT)
Return an UNDEF node. UNDEF does not have a useful SDLoc.
SDValue getGLOBAL_OFFSET_TABLE (EVT VT)
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags=SDNodeFlags())
SDValue getNode (unsigned Opcode, const SDLoc &DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand, const SDNodeFlags Flags=SDNodeFlags())
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags=SDNodeFlags())
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags=SDNodeFlags())
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
SDValue getMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getAtomicMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Value, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getSetCC (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond)
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue getSelect (const SDLoc &DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS)
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
SDValue getSelectCC (const SDLoc &DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond)
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
SDValue simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
SDValue simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
SDValue getVAArg (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
SDValue getAtomicCmpSwap (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand *MMO)
Gets a node for an atomic cmpxchg op.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, unsigned Align=0, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, unsigned Size=0, const AAMDNodes &AAInfo=AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand *MMO)
SDValue getLifetimeNode (bool IsStart, const SDLoc &dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset=-1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
SDValue getMergeValues (ArrayRef< SDValue > Ops, const SDLoc &dl)
Create a MERGE_VALUES node from the given operands.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment=0, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment=0, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
SDValue getIndexedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment=0, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand *MMO)
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment=0, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
Helper function to build ISD::STORE nodes.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachineMemOperand *MMO)
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment=0, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand *MMO)
SDValue getIndexedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMemBasePlusOffset (SDValue Base, unsigned Offset, const SDLoc &DL)
Returns sum of the base pointer and offset.
SDValue getMaskedLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand *MMO, ISD::LoadExtType, bool IsExpanding=false)
SDValue getMaskedStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Mask, EVT MemVT, MachineMemOperand *MMO, bool IsTruncating=false, bool IsCompressing=false)
SDValue getMaskedGather (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO)
SDValue getMaskedScatter (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO)
template<class TargetMemSDNode >
SDValue getTargetMemSDNode (SDVTList VTs, ArrayRef< SDValue > Ops, const SDLoc &dl, EVT MemVT, MachineMemOperand *MMO)
Return (create a new or find existing) a target-specific node.
SDValue getSrcValue (const Value *v)
Construct a node to track a Value* through the backend.
SDValue getMDNode (const MDNode *MD)
Return an MDNodeSDNode which holds an MDNode.
SDValue getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
SDValue getAddrSpaceCast (const SDLoc &dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
SDValue getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
SDValue expandVAArg (SDNode *Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
SDValue expandVACopy (SDNode *Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
SDValue getSymbolFunctionGlobalAddress (SDValue Op, Function **TargetFunction=nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
SDNode * UpdateNodeOperands (SDNode *N, ArrayRef< SDValue > Ops)
SDValue getTokenFactor (const SDLoc &DL, SmallVectorImpl< SDValue > &Vals)
Creates a new TokenFactor containing Vals.
void setNodeMemRefs (MachineSDNode *N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
void updateDivergence (SDNode *N)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned TargetOpc, EVT VT1, EVT VT2, SDValue Op1)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode * MorphNodeTo (SDNode *N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
SDNode * mutateStrictFPToFP (SDNode *Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDValue getTargetExtractSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
SDValue getTargetInsertSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags=SDNodeFlags())
Get the specified node if it's already available, or else return NULL.
SDDbgValue * getDbgValue (DIVariable *Var, DIExpression *Expr, SDNode *N, unsigned R, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a SDDbgValue node.
SDDbgValue * getConstantDbgValue (DIVariable *Var, DIExpression *Expr, const Value *C, const DebugLoc &DL, unsigned O)
Creates a constant SDDbgValue node.
SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
SDDbgValue * getVRegDbgValue (DIVariable *Var, DIExpression *Expr, unsigned VReg, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a VReg SDDbgValue node.
SDDbgLabel * getDbgLabel (DILabel *Label, const DebugLoc &DL, unsigned O)
Creates a SDDbgLabel node.
void transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits=0, unsigned SizeInBits=0, bool InvalidateDbg=true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
void RemoveDeadNode (SDNode *N)
Remove the specified node from the system.
void RemoveDeadNodes (SmallVectorImpl< SDNode * > &DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
void ReplaceAllUsesWith (SDValue From, SDValue To)
Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, SDNode *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, const SDValue *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
void ReplaceAllUsesOfValuesWith (const SDValue *From, const SDValue *To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
SDValue makeEquivalentMemoryOrdering (LoadSDNode *Old, SDValue New)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
unsigned AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
void RepositionNode (allnodes_iterator Position, SDNode *N)
Move node N in the AllNodes list to be immediately before the given iterator Position.
void AddDbgValue (SDDbgValue *DB, SDNode *SD, bool isParameter)
Add a dbg_value SDNode.
void AddDbgLabel (SDDbgLabel *DB)
Add a dbg_label SDNode.
ArrayRef< SDDbgValue * > GetDbgValues (const SDNode *SD) const
Get the debug values which reference the given SDNode.
bool hasDebugValues () const
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
SDDbgInfo::DbgIterator DbgBegin () const
SDDbgInfo::DbgIterator DbgEnd () const
SDDbgInfo::DbgIterator ByvalParmDbgBegin () const
SDDbgInfo::DbgIterator ByvalParmDbgEnd () const
SDDbgInfo::DbgLabelIterator DbgLabelBegin () const
SDDbgInfo::DbgLabelIterator DbgLabelEnd () const
void salvageDebugInfo (SDNode &N)
To be invoked on an SDNode that is slated to be erased.
void dump () const
SDValue CreateStackTemporary (EVT VT, unsigned minAlign=1)
Create a stack temporary, suitable for holding the specified value type.
SDValue CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
SDValue FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode *GA, const SDNode *N2)
SDValue FoldConstantArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, SDNode *N1, SDNode *N2)
SDValue FoldConstantArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, const ConstantSDNode *C1, const ConstantSDNode *C2)
SDValue FoldConstantVectorArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags=SDNodeFlags())
SDValue foldConstantFPMath (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
SDValue FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc &dl)
Constant fold a setcc to true or false.
SDValue GetDemandedBits (SDValue V, const APInt &DemandedBits)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used.
SDValue GetDemandedBits (SDValue V, const APInt &DemandedBits, const APInt &DemandedElts)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used in the elements specified by DemandedElts.
bool SignBitIsZero (SDValue Op, unsigned Depth=0) const
Return true if the sign bit of Op is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
bool MaskedValueIsAllOnes (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if '(Op & Mask) == Mask'.
KnownBits computeKnownBits (SDValue Op, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
KnownBits computeKnownBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
OverflowKind computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
bool isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
unsigned ComputeNumSignBits (SDValue Op, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
unsigned ComputeNumSignBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
bool isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
bool isKnownNeverNaN (SDValue Op, bool SNaN=false, unsigned Depth=0) const
Test whether the given SDValue is known to never be NaN.
bool isKnownNeverSNaN (SDValue Op, unsigned Depth=0) const
bool isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
bool isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
bool isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
bool haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
bool isSplatValue (SDValue V, const APInt &DemandedElts, APInt &UndefElts)
Test whether V has a splatted value for all the demanded elements.
bool isSplatValue (SDValue V, bool AllowUndefs=false)
Test whether V has a splatted value.
SDValue getSplatSourceVector (SDValue V, int &SplatIndex)
If V is a splatted value, return the source vector and its splat index.
SDValue getSplatValue (SDValue V)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
SDValue matchBinOpReduction (SDNode *Extract, ISD::NodeType &BinOp, ArrayRef< ISD::NodeType > CandidateBinOps)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
SDValue UnrollVectorOp (SDNode *N, unsigned ResNE=0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
std::pair< SDValue, SDValue > UnrollVectorOverflowOp (SDNode *N, unsigned ResNE=0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
bool areNonVolatileConsecutiveLoads (LoadSDNode *LD, LoadSDNode *Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
unsigned InferPtrAlignment (SDValue Ptr) const
Infer alignment of a load / store address.
std::pair< EVT, EVT > GetSplitDestVTs (const EVT &VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL)
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
std::pair< SDValue, SDValue > SplitVectorOperand (const SDNode *N, unsigned OpNo)
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
SDValue WidenVector (const SDValue &N, const SDLoc &DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
void ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > &Args, unsigned Start=0, unsigned Count=0)
Append the extracted elements from Start to Count out of the vector Op in Args.
unsigned getEVTAlignment (EVT MemoryVT) const
Compute the default alignment value for the given type.
SDNode * isConstantIntBuildVectorOrConstantInt (SDValue N)
Test whether the given value is a constant int or similar node.
SDNode * isConstantFPBuildVectorOrConstantFP (SDValue N)
Test whether the given value is a constant FP or similar node.
bool isConstantValueOfAnyType (SDValue N)
void addCallSiteInfo (const SDNode *CallNode, CallSiteInfoImpl &&CallInfo)
CallSiteInfo getSDCallSiteInfo (const SDNode *CallNode)
void addHeapAllocSite (const SDNode *Node, MDNode *MD)
MDNode * getHeapAllocSite (const SDNode *Node)
Return the HeapAllocSite type associated with the SDNode, if it exists.
SDValue getConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
Create a ConstantSDNode wrapping a constant value.
SDValue getConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getAllOnesConstant (const SDLoc &DL, EVT VT, bool IsTarget=false, bool IsOpaque=false)
SDValue getConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getIntPtrConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc &DL, bool LegalTypes=true)
SDValue getTargetConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getBoolConstant (bool V, const SDLoc &DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
SDValue getConstantFP (double Val, const SDLoc &DL, EVT VT, bool isTarget=false)
Create a ConstantFPSDNode wrapping a constant value.
SDValue getConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getConstantFP (const ConstantFP &V, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getTargetConstantFP (double Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const ConstantFP &Val, const SDLoc &DL, EVT VT)
Static Public Member Functions
static const fltSemantics & EVTToAPFloatSemantics (EVT VT)
Returns an APFloat semantics tag appropriate for the given type.
Public Attributes
bool NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
std::map< const SDNode *, std::string > NodeGraphAttrs
Friends
struct DAGUpdateListener
DAGUpdateListener is a friend so it can manipulate the listener stack.
Detailed Description
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
This DAG is constructed as the first step of instruction selection in order to allow implementation of machine specific optimizations and code simplifications.
The representation used by the SelectionDAG is a target-independent representation, which has some similarities to the GCC RTL representation, but is significantly more simple, powerful, and is a graph form instead of a linear form.
Definition at line 221 of file SelectionDAG.h.
Member Typedef Documentation
allnodes_const_iterator
using llvm::SelectionDAG::allnodes_const_iterator = ilist<SDNode>::const_iterator
Definition at line 448 of file SelectionDAG.h.
allnodes_iterator
using llvm::SelectionDAG::allnodes_iterator = ilist<SDNode>::iterator
Definition at line 453 of file SelectionDAG.h.
Member Enumeration Documentation
OverflowKind
enum llvm::SelectionDAG::OverflowKind
Used to represent the possible overflow behavior of an operation.
Never: the operation cannot overflow. Always: the operation will always overflow. Sometime: the operation may or may not overflow.
Enumerator
OFK_Never
OFK_Sometime
OFK_Always
Definition at line 1506 of file SelectionDAG.h.
Constructor & Destructor Documentation
SelectionDAG() [1/2]
SelectionDAG::SelectionDAG (const TargetMachine & TM, CodeGenOpt::Level OL) explicit
Definition at line 998 of file SelectionDAG.cpp.
SelectionDAG() [2/2]
llvm::SelectionDAG::SelectionDAG (const SelectionDAG &) delete
~SelectionDAG()
SelectionDAG::~SelectionDAG ()
Definition at line 1020 of file SelectionDAG.cpp.
References assert().
Member Function Documentation
addCallSiteInfo()
void llvm::SelectionDAG::addCallSiteInfo (const SDNode * CallNode, CallSiteInfoImpl && CallInfo) inline
Definition at line 1672 of file SelectionDAG.h.
AddDbgLabel()
void SelectionDAG::AddDbgLabel (SDDbgLabel * DB)
Add a dbg_label SDNode.
Definition at line 8610 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add().
AddDbgValue()
void SelectionDAG::AddDbgValue (SDDbgValue * DB, SDNode * SD, bool isParameter)
Add a dbg_value SDNode.
AddDbgValue - Add a dbg_value SDNode.
If SD is non-null that means the value is produced by SD.
Definition at line 8602 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add(), assert(), llvm::SDNode::getHasDebugValue(), llvm::SDDbgInfo::getSDDbgValues(), and llvm::SDNode::setHasDebugValue().
Referenced by llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), salvageDebugInfo(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), and transferDbgValues().
addHeapAllocSite()
void llvm::SelectionDAG::addHeapAllocSite (const SDNode * Node, MDNode * MD) inline
Definition at line 1683 of file SelectionDAG.h.
allnodes() [1/2]
iterator_range< allnodes_iterator > llvm::SelectionDAG::allnodes () inline
Definition at line 462 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
Referenced by AssignTopologicalOrder(), llvm::HexagonDAGToDAGISel::PreprocessISelDAG(), RemoveDeadNodes(), llvm::DAGTypeLegalizer::run(), and VerifyDAGDiverence().
allnodes() [2/2]
iterator_range< allnodes_const_iterator > llvm::SelectionDAG::allnodes () const inline
Definition at line 465 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
allnodes_begin() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_begin () inline
Definition at line 455 of file SelectionDAG.h.
allnodes_begin() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_begin () const inline
Definition at line 450 of file SelectionDAG.h.
Referenced by allnodes(), AssignTopologicalOrder(), and Legalize().
allnodes_end() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_end () inline
Definition at line 456 of file SelectionDAG.h.
allnodes_end() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_end () const inline
Definition at line 451 of file SelectionDAG.h.
Referenced by allnodes(), AssignTopologicalOrder(), and Legalize().
allnodes_size()
ilist< SDNode >::size_type llvm::SelectionDAG::allnodes_size () const inline
Definition at line 458 of file SelectionDAG.h.
Referenced by AssignTopologicalOrder(), and llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
areNonVolatileConsecutiveLoads()
bool SelectionDAG::areNonVolatileConsecutiveLoads (LoadSDNode * LD, LoadSDNode * Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
Check that both are nonvolatile and if LD is loading 'Bytes' bytes from a location that is 'Dist' units away from the location that the 'Base' load is loading from.
Definition at line 9185 of file SelectionDAG.cpp.
References llvm::MemSDNode::getChain(), llvm::EVT::getSizeInBits(), llvm::LSBaseSDNode::isIndexed(), llvm::MemSDNode::isVolatile(), and llvm::BaseIndexOffset::match().
Referenced by EltsFromConsecutiveLoads().
AssignTopologicalOrder()
unsigned SelectionDAG::AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
AssignTopologicalOrder - Assign a unique node id for each node in the DAG based on their topological order.
Returns the number of nodes.
It returns the maximum id and a vector of the SDNodes* in assigned order by reference.
Definition at line 8513 of file SelectionDAG.cpp.
References allnodes(), allnodes_begin(), allnodes_end(), allnodes_size(), assert(), llvm::checkForCycles(), llvm::dbgs(), llvm::SDNode::dumprFull(), E, llvm::ISD::EntryToken, I, llvm_unreachable, N, and P.
Referenced by Legalize().
ByvalParmDbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgBegin () const inline
Definition at line 1396 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgBegin().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
ByvalParmDbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgEnd () const inline
Definition at line 1399 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgEnd().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
clear()
void SelectionDAG::clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
Definition at line 1077 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::clear(), getEntryNode(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
clearGraphAttrs()
void SelectionDAG::clearGraphAttrs ()
Clear all previously defined node graph attributes.
clearGraphAttrs - Clear all previously defined node graph attributes.
Intended to be used from a debugging tool (eg. gdb).
Definition at line 169 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and NodeGraphAttrs.
Combine()
void SelectionDAG::Combine (CombineLevel Level, AliasAnalysis * AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
This is the entry point for the file.
The Level argument controls whether Combine is allowed to produce nodes and types that are illegal on the target.
This is the main entry point to this class.
Definition at line 20834 of file DAGCombiner.cpp.
computeKnownBits() [1/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements.
Definition at line 2422 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::APInt::ashrInPlace(), assert(), llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::APInt::byteSwap(), C, llvm::APInt::clearAllBits(), llvm::APInt::clearSignBit(), llvm::KnownBits::computeForAddCarry(), llvm::KnownBits::computeForAddSub(), computeKnownBits(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromRangeMetadata(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMaxTrailingZeros(), llvm::KnownBits::countMinLeadingOnes(), llvm::KnownBits::countMinLeadingZeros(), llvm::KnownBits::countMinTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::Depth, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FGETSIGN, llvm::ISD::FrameIndex, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::KnownBits::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), llvm::APInt::getBoolValue(), getDataLayout(), llvm::APInt::getHiBits(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::EVT::getSizeInBits(), llvm::Constant::getSplatValue(), llvm::TargetLowering::getTargetConstantFromLoad(), llvm::Value::getType(), getValidShiftAmountConstant(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZExtValue(), llvm::ConstantSDNode::getZExtValue(), llvm::KnownBits::hasConflict(), Idx, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::APInt::intersects(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::APInt::isNegative(), llvm::ISD::isNON_EXTLoad(), llvm::APInt::isNonNegative(), llvm::KnownBits::isNonNegative(), llvm::KnownBits::isUnknown(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ISD::isZEXTLoad(), LLVM_FALLTHROUGH, llvm::ISD::LOAD, llvm::Log2_32(), llvm::APInt::lshr(), llvm::APInt::lshrInPlace(), llvm::ISD::MUL, llvm::ISD::NON_EXTLOAD, llvm::KnownBits::One, llvm::ISD::OR, RA, llvm::KnownBits::resetAll(), llvm::APInt::reverseBits(), llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::APInt::setAllBits(), llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), llvm::ISD::SETCC, llvm::APInt::setHighBits(), llvm::APInt::setLowBits(), llvm::KnownBits::sext(), llvm::APInt::shl(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SSUBO, llvm::ISD::SUB, llvm::ISD::SUBC, std::swap(), llvm::ISD::TargetFrameIndex, llvm::KnownBits::trunc(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::APInt::ule(), llvm::APInt::ult(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::UREM, llvm::ISD::USUBO, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, llvm::KnownBits::zext(), llvm::APInt::zext(), llvm::APInt::zextOrSelf(), and llvm::APInt::zextOrTrunc().
computeKnownBits() [2/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
For vectors, the known bits are those that are shared by every vector element. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
For vectors, the known bits are those that are shared by every vector element.
Definition at line 2411 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, llvm::APInt::getAllOnesValue(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isVector().
Referenced by adjustForRedundantAnd(), llvm::SelectionDAGISel::CheckOrMask(), combineSubToSubus(), combineVectorSignBitsTruncation(), computeKnownBits(), computeKnownBitsBinOp(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), computeOverflowKind(), foldMaskAndShiftToScale(), GetDemandedBits(), getFauxShuffleMask(), haveNoCommonBitsSet(), isBitfieldPositioningOp(), isKnownToBeAPowerOfTwo(), isTruncateOf(), isWordAligned(), LowerAndToBT(), LowerMUL(), MaskedValueIsAllOnes(), MaskedValueIsZero(), matchRotateSub(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
ComputeNumSignBits() [1/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. The DemandedElts argument allows us to only collect the minimum sign bits of the requested vector elements. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 3417 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::AND, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, C, llvm::APInt::clearBit(), computeKnownBits(), ComputeNumSignBits(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::ISD::CONCAT_VECTORS, llvm::Depth, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), getDataLayout(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::TargetLowering::getTargetConstantFromLoad(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZExtValue(), llvm::ConstantSDNode::getZExtValue(), Idx, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::APInt::lshr(), llvm::ISD::NON_EXTLOAD, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::APInt::setBit(), llvm::ISD::SETCC, llvm::ISD::SEXTLOAD, llvm::APInt::shl(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SSUBO, llvm::ISD::SUB, std::swap(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::APInt::uge(), llvm::APInt::ule(), llvm::APInt::ult(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::ISD::ZEXTLOAD, and llvm::APInt::zextOrSelf().
ComputeNumSignBits() [2/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 3409 of file SelectionDAG.cpp.
References ComputeNumSignBits(), llvm::Depth, llvm::APInt::getAllOnesValue(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isVector().
Referenced by canReduceVMulWidth(), combineAndMaskToShift(), combineHorizontalPredicateResult(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMulToPMULDQ(), combineSIntToFP(), combineVectorPack(), combineVectorSignBitsTruncation(), combineVSelectWithAllOnesOrZeros(), ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetLowering::expandMUL_LOHI(), foldAddSubMasked1(), getFauxShuffleMask(), isS16(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerTruncateVecI1(), matchVectorShuffleWithPACK(), llvm::AMDGPUTargetLowering::numBitsSigned(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
computeOverflowKind()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
Definition at line 3337 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::APInt::getBoolValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::isNullConstant(), OFK_Never, OFK_Sometime, llvm::ISD::UMUL_LOHI, and llvm::KnownBits::Zero.
CreateStackTemporary() [1/2]
SDValue SelectionDAG::CreateStackTemporary (EVT VT, unsigned minAlign = 1)
Create a stack temporary, suitable for holding the specified value type.
If minAlign is specified, the slot size will have at least that alignment.
Definition at line 1946 of file SelectionDAG.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), getContext(), getDataLayout(), getFrameIndex(), llvm::TargetLoweringBase::getFrameIndexTy(), llvm::MachineFunction::getFrameInfo(), getMachineFunction(), llvm::EVT::getStoreSize(), and llvm::EVT::getTypeForEVT().
Referenced by llvm::StatepointLoweringState::allocateStackSlot(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::SystemZTargetLowering::LowerCall(), and llvm::X86TargetLowering::ReplaceNodeResults().
CreateStackTemporary() [2/2]
SDValue SelectionDAG::CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
Definition at line 1957 of file SelectionDAG.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), getContext(), getDataLayout(), getFrameIndex(), llvm::TargetLoweringBase::getFrameIndexTy(), llvm::MachineFunction::getFrameInfo(), getMachineFunction(), llvm::DataLayout::getPrefTypeAlignment(), llvm::EVT::getStoreSize(), and llvm::EVT::getTypeForEVT().
DbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgBegin () const inline
Definition at line 1393 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgBegin().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
DbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgEnd () const inline
Definition at line 1394 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgEnd().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
DbgLabelBegin()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelBegin () const inline
Definition at line 1403 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelBegin().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
DbgLabelEnd()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelEnd () const inline
Definition at line 1406 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelEnd().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
DeleteNode()
void SelectionDAG::DeleteNode (SDNode * N)
Remove the specified node from the system.
This node must have no referrers.
Definition at line 742 of file SelectionDAG.cpp.
References N.
Referenced by Legalize(), and llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
dump()
LLVM_DUMP_METHOD void SelectionDAG::dump () const
Definition at line 808 of file SelectionDAGDumper.cpp.
Referenced by NewSDValueDbgMsg(), and llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
EVTToAPFloatSemantics()
static const fltSemantics & llvm::SelectionDAG::EVTToAPFloatSemantics (EVT VT) inline static
Returns an APFloat semantics tag appropriate for the given type.
If VT is a vector type, the element semantics are returned.
Definition at line 1364 of file SelectionDAG.h.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, llvm::APFloatBase::PPCDoubleDouble(), llvm::MVT::ppcf128, llvm::MVT::SimpleTy, and llvm::APFloatBase::x87DoubleExtended().
Referenced by llvm::TargetLowering::expandFP_TO_UINT(), foldConstantFPMath(), FoldIntToFPToInt(), getConstantFP(), getMemsetValue(), getNode(), llvm::ConstantFPSDNode::isValueValidForType(), LowerFABSorFNEG(), and LowerFCOPYSIGN().
expandVAArg()
SDValue SelectionDAG::expandVAArg (SDNode * Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
Definition at line 1897 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), getConstant(), getContext(), getDataLayout(), getLoad(), llvm::TargetLoweringBase::getMinStackArgumentAlignment(), getNode(), llvm::TargetLoweringBase::getPointerTy(), getStore(), getTargetLoweringInfo(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), and llvm::SDValue::getValueType().
expandVACopy()
SDValue SelectionDAG::expandVACopy (SDNode * Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
Definition at line 1932 of file SelectionDAG.cpp.
References getDataLayout(), getLoad(), llvm::TargetLoweringBase::getPointerTy(), getStore(), getTargetLoweringInfo(), and llvm::SDValue::getValue().
Referenced by LowerVACOPY().
ExtractVectorElements()
void SelectionDAG::ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > & Args, unsigned Start = 0, unsigned Count = 0)
Append the extracted elements from Start to Count out of the vector Op in Args.
If Count is 0, all of the elements will be extracted.
Definition at line 9286 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, getConstant(), getDataLayout(), getNode(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), and llvm::EVT::getVectorNumElements().
Referenced by adjustLoadValueTypeImpl(), constructRetValue(), llvm::TargetLowering::expandVecReduce(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), UnrollVectorOverflowOp(), and widenVectorToPartType().
FoldConstantArithmetic() [1/2]
SDValue SelectionDAG::FoldConstantArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, const ConstantSDNode * C1, const ConstantSDNode * C2)
Definition at line 4731 of file SelectionDAG.cpp.
References FoldValue(), llvm::ConstantSDNode::getAPIntValue(), getConstant(), and llvm::ConstantSDNode::isOpaque().
FoldConstantArithmetic() [2/2]
SDValue SelectionDAG::FoldConstantArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, SDNode * N1, SDNode * N2)
Definition at line 4789 of file SelectionDAG.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILTIN_OP_END, llvm::ISD::Constant, llvm::ISD::ConstantFP, FoldConstantArithmetic(), FoldSymbolOffset(), getBuildVector(), getContext(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getTypeToTransformTo(), getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), I, llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::EVT::isInteger(), llvm::SDValue::isUndef(), llvm::SDNode::isUndef(), isUndef(), llvm::EVT::isVector(), NewNodesMustHaveLegalTypes, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), and llvm::ISD::TRUNCATE.
Referenced by FoldConstantArithmetic(), and getNode().
foldConstantFPMath()
SDValue SelectionDAG::foldConstantFPMath (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
Definition at line 4973 of file SelectionDAG.cpp.
References llvm::APFloat::add(), llvm::APFloat::convert(), llvm::APFloat::copySign(), llvm::APFloat::divide(), EVTToAPFloatSemantics(), llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FP_ROUND, llvm::ISD::FREM, llvm::ISD::FSUB, getConstantFP(), llvm::APFloat::getNaN(), llvm::SDValue::getNode(), getUNDEF(), llvm::SDValue::isUndef(), llvm::APFloat::mod(), llvm::APFloat::multiply(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::APFloat::subtract().
Referenced by getNode().
FoldConstantVectorArithmetic()
SDValue SelectionDAG::FoldConstantVectorArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 4877 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILTIN_OP_END, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, getBuildVector(), getContext(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getTypeToTransformTo(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i1, llvm::BuildVectorSDNode::isConstant(), llvm::EVT::isInteger(), llvm::SDValue::isUndef(), isUndef(), llvm::EVT::isVector(), NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SETCC, llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by getNode().
FoldSetCC()
SDValue SelectionDAG::FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc & dl)
Constant fold a setcc to true or false.
Definition at line 1970 of file SelectionDAG.cpp.
References assert(), llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, llvm::APFloatBase::cmpLessThan, llvm::APFloatBase::cmpUnordered, getBoolConstant(), getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::EVT::getSimpleVT(), getUNDEF(), llvm::ISD::getUnorderedFlavor(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::ISD::isTrueWhenEqual(), llvm::SDValue::isUndef(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::APInt::sge(), llvm::APInt::sgt(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), and llvm::APInt::ult().
Referenced by getNode(), and llvm::TargetLowering::SimplifySetCC().
FoldSymbolOffset()
SDValue SelectionDAG::FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode * GA, const SDNode * N2)
Definition at line 4744 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::GlobalAddressSDNode::getGlobal(), getGlobalAddress(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::ISD::GlobalAddress, llvm::TargetLowering::isOffsetFoldingLegal(), and llvm::ISD::SUB.
Referenced by FoldConstantArithmetic().
getAddrSpaceCast()
SDValue SelectionDAG::getAddrSpaceCast (const SDLoc & dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
Definition at line 1866 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::ADDRSPACECAST, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), and N.
getAllOnesConstant()
SDValue llvm::SelectionDAG::getAllOnesConstant (const SDLoc & DL, EVT VT, bool IsTarget = false, bool IsOpaque = false) inline
Definition at line 579 of file SelectionDAG.h.
References llvm::APInt::getAllOnesValue(), getConstant(), and llvm::EVT::getScalarSizeInBits().
Referenced by combineAndLoadToBZHI(), llvm::TargetLowering::expandAddSubSat(), flipBoolean(), getBoolConstant(), getNode(), LowerADDSAT_SUBSAT(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getAnyExtOrTrunc()
SDValue SelectionDAG::getAnyExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
Definition at line 1105 of file SelectionDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsGT(), getNode(), and llvm::ISD::TRUNCATE.
Referenced by combineBitcast(), combineScalarToVector(), combineToExtendBoolVectorInReg(), createGPRPairNode(), createMMXBuildVector(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), getCopyFromPartsVector(), getCopyToPartsVector(), getNode(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), and LowerMUL().
getAtomic() [1/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
Definition at line 6546 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD, getAtomic(), getVTList(), and llvm::MVT::Other.
getAtomic() [2/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
Definition at line 6518 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_FSUB, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, getAtomic(), llvm::SDValue::getValueType(), getVTList(), and llvm::MVT::Other.
Referenced by combineSetCCAtomicArith(), getAtomic(), getAtomicCmpSwap(), LowerATOMIC_STORE(), and lowerAtomicArith().
getAtomic() [3/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
Definition at line 6484 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), and N.
getAtomicCmpSwap()
SDValue SelectionDAG::getAtomicCmpSwap (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand * MMO)
Gets a node for an atomic cmpxchg op.
There are two valid Opcodes. ISD::ATOMIC_CMO_SWAP produces the value loaded and a chain result. ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS produces the value loaded, a success flag (initially i1), and a chain.
Definition at line 6506 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, getAtomic(), and llvm::SDValue::getValueType().
getAtomicMemcpy()
SDValue SelectionDAG::getAtomicMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6238 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::RTLIB::getMEMCPY_ELEMENT_UNORDERED_ATOMIC(), llvm::TargetLoweringBase::getPointerTy(), llvm::IRBuilderBase::getVoidTy(), llvm::TargetLowering::LowerCallTo(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
getAtomicMemmove()
SDValue SelectionDAG::getAtomicMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6342 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::RTLIB::getMEMMOVE_ELEMENT_UNORDERED_ATOMIC(), llvm::TargetLoweringBase::getPointerTy(), llvm::IRBuilderBase::getVoidTy(), llvm::TargetLowering::LowerCallTo(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
getAtomicMemset()
SDValue SelectionDAG::getAtomicMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Value, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 6444 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::IRBuilderBase::getInt8Ty(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::RTLIB::getMEMSET_ELEMENT_UNORDERED_ATOMIC(), llvm::TargetLoweringBase::getPointerTy(), llvm::IRBuilderBase::getVoidTy(), llvm::TargetLowering::LowerCallTo(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
getBasicBlock() [1/2]
SDValue SelectionDAG::getBasicBlock (MachineBasicBlock * MBB)
Definition at line 1493 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BasicBlock, E, getVTList(), N, llvm::None, and llvm::MVT::Other.
Referenced by llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getBasicBlock() [2/2]
SDValue llvm::SelectionDAG::getBasicBlock (MachineBasicBlock * MBB, SDLoc dl)
getBitcast()
SDValue SelectionDAG::getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
Use getNode to set a custom SDLoc.
Definition at line 1859 of file SelectionDAG.cpp.
References llvm::ISD::BITCAST, getNode(), and llvm::SDValue::getValueType().
Referenced by BuildSplatI(), canonicalizeBitSelect(), combineAnd(), combineAndMaskToShift(), combineAndnp(), combineANDXORWithAllOnesIntoANDNP(), combineBasicSADPattern(), combineBitcast(), combineBitcastvxi1(), combineCastedMaskArithmetic(), combineCompareEqual(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFMA(), combineFneg(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineMulToPMADDWD(), combineOr(), combineRedundantDWordShuffle(), combineScalarToVector(), combineSelect(), combineShuffle(), combineShuffleToVectorExtend(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncationShuffle(), combineVectorCompareAndMaskUnaryOp(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineXor(), convertIntLogicToFPLogic(), convertShiftLeftToScale(), createMMXBuildVector(), EltsFromConsecutiveLoads(), llvm::TargetLowering::expandUINT_TO_FP(), FoldIntToFPToInt(), getBuildDwordsVector(), getConstVector(), getCopyFromPartsVector(), getCopyToPartsVector(), getMaskNode(), getMemsetValue(), getOnesVector(), getScalarMaskingNode(), getScalarValueForVectorElement(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getv64i1Argument(), getVShift(), getZeroVector(), llvm::TargetLowering::IncrementMemoryAddress(), isHorizontalBinOp(), IsNOT(), lower256BitShuffle(), LowerAVXExtend(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCall(), LowerCTPOP(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerHorizontalByteSum(), LowerLoad(), lowerMasksToReg(), LowerMUL(), LowerMULH(), lowerRegToMasks(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndBlend(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), LowerStore(), LowerTruncateVecI1(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVectorAllZeroTest(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), lowerVectorShuffle(), lowerVectorShuffleAsByteShiftMask(), LowerVSETCC(), lowerX86FPLogicOp(), matchVectorShuffleWithPACK(), narrowExtractedVectorBinOp(), narrowExtractedVectorSelect(), Passv64i1ArgInRegs(), reduceBuildVecToShuffleWithZero(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), splitAndLowerShuffle(), truncateVectorWithPACK(), and XFormVExtractWithShuffleIntoLoad().
getBlockAddress()
SDValue SelectionDAG::getBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, bool isTarget = false, unsigned char TargetFlags = 0)
Definition at line 1805 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BlockAddress, E, getVTList(), N, llvm::None, and llvm::ISD::TargetBlockAddress.
Referenced by getTargetBlockAddress(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::LanaiTargetLowering::LowerBlockAddress().
getBoolConstant()
SDValue SelectionDAG::getBoolConstant (bool V, const SDLoc & DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
Definition at line 1169 of file SelectionDAG.cpp.
References getAllOnesConstant(), llvm::TargetLoweringBase::getBooleanContents(), getConstant(), llvm_unreachable, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by FoldSetCC(), getLogicalNOT(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getBoolExtOrTrunc()
SDValue SelectionDAG::getBoolExtOrTrunc (SDValue Op, const SDLoc & SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
Definition at line 1123 of file SelectionDAG.cpp.
References llvm::EVT::bitsLE(), llvm::TargetLoweringBase::getBooleanContents(), llvm::TargetLoweringBase::getExtendForContent(), getNode(), and llvm::ISD::TRUNCATE.
Referenced by llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), and llvm::TargetLowering::SimplifySetCC().
getBuildVector() [1/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDUse > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 759 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, and getNode().
getBuildVector() [2/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDValue > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 750 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, and getNode().
Referenced by adjustLoadValueTypeImpl(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineConcatVectorOfScalars(), combineExtractSubvector(), combineShuffleOfScalars(), combineStore(), combineToExtendBoolVectorInReg(), combineX86ShuffleChain(), CompactSwizzlableVector(), constructRetValue(), convertLocVTToValVT(), convertShiftLeftToScale(), ExtendToType(), extractSubVector(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), GenerateTBL(), getBuildDwordsVector(), getBuildVectorSplat(), getConstant(), getConstVector(), getCopyFromPartsVector(), getGeneralPermuteNode(), GetNegatedExpression(), getNode(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::SelectionDAGBuilder::getValueImpl(), incDecVectorConstant(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), lowerBuildVectorToBitOp(), LowerBuildVectorv4x32(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerMSABinaryBitImmIntr(), lowerMSASplatZExt(), LowerMUL(), LowerMULH(), LowerShift(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerTruncateVectorStore(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), NormalizeBuildVector(), PerformBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), ReorganizeVector(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::SimplifyDemandedVectorElts(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), tryBuildVectorShuffle(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), and widenVectorToPartType().
getCALLSEQ_END()
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc & DL) inline
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
CALLSEQ_END does not have a useful SDLoc.
Definition at line 862 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_END, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, llvm::MVT::Other, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and PrepareTailCall().
getCALLSEQ_START()
SDValue llvm::SelectionDAG::getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc & DL) inline
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
Definition at line 850 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_START, getIntPtrConstant(), getNode(), getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
Referenced by llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::SparcTargetLowering::LowerGlobalTLSAddress().
getCommutedVectorShuffle()
SDValue SelectionDAG::getCommutedVectorShuffle (const ShuffleVectorSDNode & SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
Example: shuffle A, B, <0,5,2,7> -> shuffle B, A, <4,1,6,3>
Definition at line 1742 of file SelectionDAG.cpp.
References llvm::ShuffleVectorSDNode::commuteMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and getVectorShuffle().
Referenced by lowerVectorShuffle().
getCondCode()
SDValue SelectionDAG::getCondCode (ISD::CondCode Cond)
Definition at line 1549 of file SelectionDAG.cpp.
References N.
Referenced by getSelectCC(), getSetCC(), lowerFCMPIntrinsic(), lowerICMPIntrinsic(), LowerVSETCC(), and llvm::TargetLowering::softenSetCCOperands().
getConstant() [1/3]
SDValue SelectionDAG::getConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1193 of file SelectionDAG.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), and getConstant().
getConstant() [2/3]
SDValue SelectionDAG::getConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1198 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ISD::BITCAST, llvm::ISD::Constant, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantInt::getBitWidth(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplatBuildVector(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::ConstantInt::getValue(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), llvm::SmallVectorImpl< T >::insert(), isBigEndian(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::APInt::lshr(), N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::None, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::TargetConstant, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypePromoteInteger, and llvm::APInt::zextOrTrunc().
getConstant() [3/3]
SDValue SelectionDAG::getConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Create a ConstantSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal).
Definition at line 1184 of file SelectionDAG.cpp.
References assert(), getConstant(), llvm::EVT::getScalarType(), and llvm::EVT::getSizeInBits().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmpTruncate(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), bitcastf32Toi32(), BuildExactSDIV(), BuildIntrinsicOp(), llvm::SITargetLowering::buildRSRC(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), BuildSplatI(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), clampDynamicVectorIndex(), CollectOpsToWiden(), combineAcrossLanesIntrinsic(), combineADC(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndLoadToBZHI(), combineAndMaskToShift(), combineAndnp(), CombineANDShift(), CombineBaseUpdate(), combineBEXTR(), combineBitcast(), combineBitcastvxi1(), combineBrCond(), combineCMov(), combineCMP(), combineCompareEqual(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineLoopMAddPattern(), combineLoopSADPattern(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineParity(), combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCAtomicArith(), combineSext(), combineShiftLeft(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineSub(), combineSubToSubus(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineVectorCompare(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combinevXi1ConstantToInteger(), combineX86AddSub(), combineX86ShuffleChain(), combineZext(), constantFoldBFE(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), ConvertI1VectorToInteger(), convertShiftLeftToScale(), convertValVTToLocVT(), CreateCopyOfByValArgument(), createFPCmp(), createGPRPairNode(), createLoadLR(), createMMXBuildVector(), createPSADBW(), createStoreLR(), createVariablePermute(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitCLC(), EmitCMP(), emitCmp(), emitConditionalComparison(), emitConstantSizeRepmov(), EmitKORTEST(), emitMemMem(), emitSETCC(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), EmitTest(), Expand64BitShift(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), ExpandBITCAST(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), ExtendToType(), ExtractBitFromMaskVector(), extractF64Exponent(), extractShiftForRotate(), ExtractVectorElements(), flipBoolean(), foldAddSubBoolOfMaskedVal(), foldAddSubOfSignBit(), FoldConstantArithmetic(), foldExtendedSignBitTest(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldXorTruncShiftIntoCmp(), genConstMult(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesConstant(), getARMIndexedAddressParts(), getBoolConstant(), getBoundedStrlen(), getBuildVectorSplat(), getCCResult(), getConstant(), getConstVector(), getCopyFromParts(), getCopyFromPartsVector(), llvm::RegsForValue::getCopyFromRegs(), getCopyToPartsVector(), GetDemandedBits(), GetExponent(), getGeneralPermuteNode(), llvm::AMDGPUTargetLowering::getHiHalf64(), getIntPtrConstant(), getLimitedPrecisionExp2(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMaskNode(), getMemBasePlusOffset(), getMemsetStringVal(), getMemsetValue(), getNode(), getNOT(), getObjectPtrOffset(), getOnesVector(), getPermuteNode(), getPMOVMSKB(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getReductionSDNode(), getSETCC(), getShiftAmountConstant(), getShuffleScalarElt(), GetSignificand(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getT2IndexedAddressParts(), getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::getVectorElementPointer(), getVShift(), getZeroExtendInReg(), getZeroVector(), incDecVectorConstant(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), IntCondCCodeToICC(), isBLACompatibleAddress(), isConditionalZeroOrAllOnes(), IsSingleInstrConstant(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), LowerAndToBT(), LowerAsSplatVectorLoad(), LowerATOMIC_FENCE(), lowerAtomicArith(), LowerAVXExtend(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::LanaiTargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), LowerBuildVectorv16i8(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), LowerF128Load(), LowerF128Store(), lowerFABS32(), lowerFABS64(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerFGETSIGN(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), LowerHorizontalByteSum(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), LowerLabelRef(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), LowerMemOpCallTo(), LowerMINMAX(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSASplatImm(), lowerMSASplatZExt(), LowerMSCATTER(), LowerMUL(), llvm::LanaiTargetLowering::LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), llvm::R600TargetLowering::LowerOperation(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerPREFETCH(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerRotate(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleToEXPAND(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSSE4A(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4F64Shuffle(), lowerV4X128Shuffle(), lowerV8F64Shuffle(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_SHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), lowerVectorShuffleAsByteShiftMask(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), LowerXALUO(), LowerXOR(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), memsetStore(), narrowExtractedVectorBinOp(), NormalizeBuildVector(), optimizeLogicalImm(), Passv64i1ArgInRegs(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performANDCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBitcastCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performExtendCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), performGlobalAddressCombine(), performIntegerAbsCombine(), PerformIntrinsicCombine(), performMulCombine(), PerformMULCombine(), performORCombine(), PerformORCombineToBFI(), performSetccAddFolding(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), PerformSTORECombine(), performTBZCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), PerformVMOVRRDCombine(), PrepareCall(), promoteExtBeforeAdd(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), ReplaceLongIntrinsic(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), replaceShuffleOfInsert(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedConstant(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyDivRem(), llvm::TargetLowering::SimplifySetCC(), simplifyShift(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), llvm::AMDGPUTargetLowering::split64BitValue(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), splitInt128(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::storeStackInputValue(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), TranslateX86CC(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), tryCombineShiftImm(), tryCombineToEXTR(), tryExtendDUPToExtractHigh(), tryFoldToZero(), tryFormConcatFromShuffle(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), UnpackFromArgumentSlot(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), WidenVector(), WidenVector(), llvm::AMDGPUTargetLowering::WidenVectorLoad(), WinDBZCheckDenominator(), and XFormVExtractWithShuffleIntoLoad().
getConstantDbgValue()
SDDbgValue * SelectionDAG::getConstantDbgValue (DIVariable * Var, DIExpression * Expr, const Value * C, const DebugLoc & DL, unsigned O)
Creates a constant SDDbgValue node.
Constant.
Definition at line 7982 of file SelectionDAG.cpp.
References assert(), C, and llvm::SDDbgInfo::getAlloc().
Referenced by llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue().
getConstantFP() [1/3]
SDValue SelectionDAG::getConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1300 of file SelectionDAG.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), getConstantFP(), and getContext().
getConstantFP() [2/3]
SDValue SelectionDAG::getConstantFP (const ConstantFP & V, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1305 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::ConstantFP, llvm::EVT::getScalarType(), getSplatBuildVector(), getVTList(), llvm::EVT::isFloatingPoint(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::None, and llvm::ISD::TargetConstantFP.
getConstantFP() [3/3]
SDValue SelectionDAG::getConstantFP (double Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Create a ConstantFPSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal). The forms that take a double should only be used for simple constants that can be exactly represented in VT. No checks are made.
Definition at line 1337 of file SelectionDAG.cpp.
References llvm::APFloat::convert(), EVTToAPFloatSemantics(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, getConstantFP(), llvm::EVT::getScalarType(), llvm_unreachable, llvm::MVT::ppcf128, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by combineBitcast(), combineExtractWithShuffle(), combineFneg(), EltsFromConsecutiveLoads(), llvm::TargetLowering::expandFP_TO_UINT(), ExpandPowI(), llvm::TargetLowering::expandUINT_TO_FP(), foldConstantFPMath(), getConstantFP(), getConstVector(), getF32Constant(), getLog2EVal(), getMemsetStringVal(), getMemsetValue(), GetNegatedExpression(), getNode(), getShuffleScalarElt(), getTargetConstantFP(), llvm::SelectionDAGBuilder::getValueImpl(), getZeroVector(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), LowerFCOPYSIGN(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::AMDGPUTargetLowering::LowerFLOG(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), lowerShuffleAsBitMask(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::performRcpCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), visitFMinMax(), and XFormVExtractWithShuffleIntoLoad().
getConstantPool() [1/2]
SDValue SelectionDAG::getConstantPool (const Constant * C, EVT VT, unsigned Align = 0, int Offs = 0, bool isT = false, unsigned char TargetFlags = 0)
Definition at line 1422 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), C, llvm::ISD::ConstantPool, E, llvm::DataLayout::getABITypeAlignment(), getDataLayout(), llvm::MachineFunction::getFunction(), llvm::DataLayout::getPrefTypeAlignment(), getVTList(), N, llvm::None, and llvm::ISD::TargetConstantPool.
Referenced by getAddressForMemoryInput(), getTargetConstantPool(), lowerBuildVectorAsBroadcast(), and LowerUINT_TO_FP_i64().
getConstantPool() [2/2]
SDValue SelectionDAG::getConstantPool (MachineConstantPoolValue * C, EVT VT, unsigned Align = 0, int Offs = 0, bool isT = false, unsigned char TargetFlags = 0)
Definition at line 1450 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), C, llvm::ISD::ConstantPool, E, getDataLayout(), llvm::DataLayout::getPrefTypeAlignment(), getVTList(), N, llvm::None, and llvm::ISD::TargetConstantPool.
getContext()
LLVMContext * llvm::SelectionDAG::getContext () const inline
Definition at line 420 of file SelectionDAG.h.
References Context.
Referenced by AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), BuildVectorFromScalar(), canFoldInAddressingMode(), CollectOpsToWiden(), combineAnd(), combineBitcastvxi1(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineExtInVec(), combineExtractSubvector(), combineExtractVectorElt(), combineFMinNumFMaxNum(), combineGatherScatter(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineLoad(), combineLoopMAddPattern(), combineMaskedLoad(), combineMaskedStore(), combineMinNumMaxNum(), combineReductionToHorizontal(), combineSelect(), combineShuffleToVectorExtend(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToExtendVectorInReg(), combineToFPTruncExtElt(), combineTruncateWithSat(), combineUIntToFP(), CombineVMOVDRRCandidateWithVecOp(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), CreateStackTemporary(), detectPMADDUBSW(), EltsFromConsecutiveLoads(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), errorUnsupported(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), llvm::TargetLowering::expandVecReduce(), extractSubVector(), fail(), FindMemType(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getConstant(), getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), getEVTAlignment(), getFauxShuffleMask(), getMemcpy(), getMemcpyLoadsAndStores(), getMemmove(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), GetRegistersForValue(), GetSplitDestVTs(), llvm::AMDGPUTargetLowering::getSplitDestVTs(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::SelectionDAGBuilder::init(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), LowerADDSAT_SUBSAT(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFPOWI(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerLoad(), LowerMSCATTER(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVECTOR_SHUFFLE(), LowerVSETCC(), llvm::TargetLowering::makeLibCall(), matchPMADDWD(), matchPMADDWD_2(), narrowExtractedVectorBinOp(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtendCombine(), PerformInsertEltCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performSelectCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceVMULWidth(), ReplaceLoadVector(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorStore(), shouldTransformMulToShiftsAddsSubs(), llvm::TargetLowering::ShrinkDemandedOp(), llvm::TargetLowering::SimplifySetCC(), llvm::TargetLowering::softenSetCCOperands(), splitStores(), truncateVectorWithPACK(), tryFormConcatFromShuffle(), UnrollVectorOp(), UnrollVectorOverflowOp(), llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenVec(), WidenVector(), llvm::AMDGPUTargetLowering::WidenVectorLoad(), and XFormVExtractWithShuffleIntoLoad().
getCopyFromReg() [1/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT) inline
Definition at line 721 of file SelectionDAG.h.
References llvm::ISD::CopyFromReg, getNode(), getRegister(), getVTList(), llvm::MVT::Other, and Reg.
Referenced by llvm::AMDGPUTargetLowering::CreateLiveInRegister(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyFromRegs(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), getReadTimeStampCounter(), GetTLSADDR(), getv64i1Argument(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), performDivRemCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), unpackF64OnRV32DSoftABI(), unpackFromRegLoc(), llvm::SelectionDAGBuilder::visitBitTestCase(), and llvm::SelectionDAGBuilder::visitJumpTable().
getCopyFromReg() [2/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT, SDValue Glue) inline
Definition at line 730 of file SelectionDAG.h.
References llvm::ISD::CopyFromReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), llvm::MVT::Other, and Reg.
getCopyToReg() [1/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, SDValue Reg, SDValue N, SDValue Glue) inline
Definition at line 713 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), N, llvm::MVT::Other, and Reg.
getCopyToReg() [2/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N) inline
Definition at line 695 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, getNode(), getRegister(), N, llvm::MVT::Other, and Reg.
Referenced by emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyToRegs(), llvm::MipsTargetLowering::getOpndList(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSLocalDynamicModel(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::SITargetLowering::PostISelFolding(), PrepareCall(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and llvm::SelectionDAGBuilder::visitJumpTableHeader().
getCopyToReg() [3/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N, SDValue Glue) inline
Definition at line 704 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), N, llvm::MVT::Other, and Reg.
getDataLayout()
const DataLayout & llvm::SelectionDAG::getDataLayout () const inline
Definition at line 413 of file SelectionDAG.h.
References llvm::MachineFunction::getDataLayout().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addShuffleForVecExtend(), addStackMapLiveVars(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), canFoldInAddressingMode(), CollectOpsToWiden(), combineBVOfVecSExt(), combineConcatVectorOps(), combineFMinNumFMaxNum(), combineHorizontalPredicateResult(), combineLoad(), combineShuffleToVectorExtend(), combineStore(), combineTruncationShuffle(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), ComputeNumSignBits(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createGPRPairNode(), CreateStackTemporary(), EltsFromConsecutiveLoads(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), ExpandBITCAST(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), ExtractVectorElements(), foldXorTruncShiftIntoCmp(), getAddressForMemoryInput(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getConstant(), getConstantPool(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), getEVTAlignment(), GetExponent(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getGlobalAddress(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getIntPtrConstant(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpy(), getMemcpyLoadsAndStores(), getMemmove(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPPCf128HiElementSelector(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getShiftAmountConstant(), getShiftAmountOperand(), getShiftAmountTyForConstant(), getSymbolFunctionGlobalAddress(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::PPC::getVSPLTImmediate(), llvm::SelectionDAGBuilder::handleDebugValue(), InferPtrAlignment(), llvm::SelectionDAGBuilder::init(), isBLACompatibleAddress(), isExtendedBUILD_VECTOR(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), isNEONModifiedImm(), IsPredicateKnownToFail(), llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFNEGorFABS(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), LowerFPOWI(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLoad(), LowerMemOpCallTo(), llvm::R600TargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::SelectionDAGBuilder::LowerStatepoint(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), narrowExtractedVectorLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), performMULCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformVMOVRRDCombine(), PrepareCall(), promoteToConstantPool(), recoverFramePointer(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceLoadVector(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), unpackFromMemLoc(), UnrollVectorOp(), UnrollVectorOverflowOp(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), WidenVector(), llvm::AMDGPUTargetLowering::WidenVectorLoad(), and XFormVExtractWithShuffleIntoLoad().
getDbgLabel()
SDDbgLabel * SelectionDAG::getDbgLabel (DILabel * Label, const DebugLoc & DL, unsigned O)
Creates a SDDbgLabel node.
Definition at line 8116 of file SelectionDAG.cpp.
References assert(), and llvm::SDDbgInfo::getAlloc().
getDbgValue()
SDDbgValue * SelectionDAG::getDbgValue (DIVariable * Var, DIExpression * Expr, SDNode * N, unsigned R, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a SDDbgValue node.
getDbgValue - Creates a SDDbgValue node.
SDNode
Definition at line 7972 of file SelectionDAG.cpp.
References assert(), llvm::SDDbgInfo::getAlloc(), and N.
Referenced by salvageDebugInfo(), and transferDbgValues().
GetDbgValues()
ArrayRef< SDDbgValue * > llvm::SelectionDAG::GetDbgValues (const SDNode * SD) const inline
Get the debug values which reference the given SDNode.
Definition at line 1384 of file SelectionDAG.h.
References llvm::SDDbgInfo::getSDDbgValues().
Referenced by ProcessSDDbgValues(), salvageDebugInfo(), and transferDbgValues().
GetDemandedBits() [1/2]
SDValue SelectionDAG::GetDemandedBits (SDValue V, const APInt & DemandedBits)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used.
If so, return the simpler operand, otherwise return a null SDValue.
(This exists alongside SimplifyDemandedBits because GetDemandedBits can simplify nodes with multiple uses more aggressively.)
TODO: really we should be making this into the DAG equivalent of SimplifyMultipleUseDemandedBits and not generate any new nodes.
Definition at line 2129 of file SelectionDAG.cpp.
References llvm::APInt::getAllOnesValue(), GetDemandedBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isVector().
Referenced by combineBT(), combinePMULDQ(), GetDemandedBits(), and simplifyI24().
GetDemandedBits() [2/2]
SDValue SelectionDAG::GetDemandedBits (SDValue V, const APInt & DemandedBits, const APInt & DemandedElts)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used in the elements specified by DemandedElts.
If so, return the simpler operand, otherwise return a null SDValue.
(This exists alongside SimplifyDemandedBits because GetDemandedBits can simplify nodes with multiple uses more aggressively.)
TODO: really we should be making this into the DAG equivalent of SimplifyMultipleUseDemandedBits and not generate any new nodes.
Definition at line 2142 of file SelectionDAG.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), computeKnownBits(), llvm::ISD::Constant, getConstant(), GetDemandedBits(), llvm::SDValue::getNode(), getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), llvm::isConstOrConstSplat(), MaskedValueIsZero(), llvm::ISD::OR, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRL, llvm::ISD::XOR, and llvm::KnownBits::Zero.
getDivergenceAnalysis()
const LegacyDivergenceAnalysis * llvm::SelectionDAG::getDivergenceAnalysis () const inline
Definition at line 419 of file SelectionDAG.h.
Referenced by llvm::FunctionLoweringInfo::set().
getEHLabel()
SDValue SelectionDAG::getEHLabel (const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 1781 of file SelectionDAG.cpp.
References llvm::ISD::EH_LABEL, and getLabelNode().
Referenced by llvm::SelectionDAGBuilder::lowerInvokable().
getEntryNode()
SDValue llvm::SelectionDAG::getEntryNode () const inline
Return the token chain corresponding to the entry of the function.
Definition at line 473 of file SelectionDAG.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), clear(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegisterRaw(), llvm::MipsTargetLowering::getAddrLocal(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), llvm::GraphTraits< MachineRegionInfoPass * >::getEntryNode(), llvm::GraphTraits< RegionInfoPass * >::getEntryNode(), getFLUSHW(), getFRAMEADDR(), getMemCmpLoad(), getStackArgumentTokenFactor(), llvm::SelectionDAGBuilder::getValueImpl(), HandleMergeInputChains(), llvm::AMDGPUTargetLowering::loadStackInputValue(), lowerBuildVectorAsBroadcast(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), LowerFPOWI(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), LowerFSINCOS(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), llvm::SelectionDAGBuilder::LowerStatepoint(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::SparcTargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), llvm::ARMTargetLowering::PerformCMOVCombine(), performDivRemCombine(), llvm::SITargetLowering::PostISelFolding(), llvm::MachineRegionInfo::recalculate(), replaceZeroVectorStore(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getEVTAlignment()
unsigned SelectionDAG::getEVTAlignment (EVT MemoryVT) const
Compute the default alignment value for the given type.
Definition at line 989 of file SelectionDAG.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::DataLayout::getABITypeAlignment(), getContext(), getDataLayout(), llvm::IRBuilderBase::getInt8Ty(), llvm::EVT::getTypeForEVT(), and llvm::MVT::iPTR.
Referenced by getLoad(), getLoadStackGuard(), getMemIntrinsicNode(), getStore(), and getTruncStore().
getExternalSymbol() [1/2]
SDValue llvm::SelectionDAG::getExternalSymbol (const char * Sym, const SDLoc & dl, EVT VT)
getExternalSymbol() [2/2]
SDValue SelectionDAG::getExternalSymbol (const char * Sym, EVT VT)
Definition at line 1521 of file SelectionDAG.cpp.
References N.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getMemcpy(), getMemmove(), getMemset(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFPOWI(), LowerFSINCOS(), llvm::TargetLowering::LowerToTLSEmulatedModel(), and llvm::TargetLowering::makeLibCall().
getExtLoad() [1/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 6797 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getExtLoad() [2/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment = 0, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 6786 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
Referenced by adjustSubwordCmp(), combineExtInVec(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getMemcpyLoadsAndStores(), LowerLoad(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), unpackFromMemLoc(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getFPExtendOrRound()
SDValue SelectionDAG::getFPExtendOrRound (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1099 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, getIntPtrConstant(), and getNode().
Referenced by getCopyFromPartsVector(), and LowerUINT_TO_FP_i32().
getFrameIndex()
SDValue SelectionDAG::getFrameIndex (int FI, EVT VT, bool isTarget = false)
Definition at line 1388 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::ISD::FrameIndex, getVTList(), N, llvm::None, and llvm::ISD::TargetFrameIndex.
Referenced by llvm::StatepointLoweringState::allocateStackSlot(), llvm::X86TargetLowering::BuildFILD(), CalculateTailCallArgDest(), CreateStackTemporary(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), getAddressForMemoryInput(), getLifetimeNode(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getTargetFrameIndex(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerStatepointMetaArgs(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getFrameIndexDbgValue()
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex.
Definition at line 7992 of file SelectionDAG.cpp.
References assert(), llvm::SDDbgValue::FRAMEIX, and llvm::SDDbgInfo::getAlloc().
Referenced by llvm::SelectionDAGBuilder::handleDebugValue().
getGLOBAL_OFFSET_TABLE()
SDValue llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE (EVT VT) inline
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
Definition at line 883 of file SelectionDAG.h.
References getNode(), and llvm::ISD::GLOBAL_OFFSET_TABLE.
Referenced by llvm::TargetLowering::getPICJumpTableRelocBase(), and llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
getGlobalAddress()
SDValue SelectionDAG::getGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, bool isTargetGA = false, unsigned char TargetFlags = 0)
Definition at line 1355 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, getDataLayout(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), getVTList(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::GlobalValue::isThreadLocal(), N, llvm::None, llvm::SignExtend64(), llvm::ISD::TargetGlobalAddress, and llvm::ISD::TargetGlobalTLSAddress.
Referenced by FoldSymbolOffset(), getSymbolFunctionGlobalAddress(), getTargetGlobalAddress(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::LowerToTLSEmulatedModel(), and performGlobalAddressCombine().
getGraphAttrs()
const std::string SelectionDAG::getGraphAttrs (const SDNode * N) const
Get graph attributes for a node.
getGraphAttrs - Get graph attributes for a node.
(eg. "color=red".) Used from getNodeAttributes.
Definition at line 193 of file SelectionDAGPrinter.cpp.
References llvm::errs(), I, N, and NodeGraphAttrs.
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getNodeAttributes().
getHeapAllocSite()
MDNode * llvm::SelectionDAG::getHeapAllocSite (const SDNode * Node) inline
Return the HeapAllocSite type associated with the SDNode, if it exists.
Definition at line 1688 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
getIndexedLoad()
SDValue SelectionDAG::getIndexedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 6805 of file SelectionDAG.cpp.
References assert(), getLoad(), llvm::SDValue::getValueType(), llvm::MachineMemOperand::MODereferenceable, and llvm::MachineMemOperand::MOInvariant.
getIndexedStore()
SDValue SelectionDAG::getIndexedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 6938 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), llvm::MVT::Other, and llvm::ISD::STORE.
getIntPtrConstant()
SDValue SelectionDAG::getIntPtrConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1289 of file SelectionDAG.cpp.
References getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getPointerTy().
Referenced by buildFromShuffleMostly(), combineBitcast(), combineCompareEqual(), combineConcatVectorOps(), combineExtractSubvector(), combineExtractWithShuffle(), combineHorizontalMinMaxResult(), combineInsertSubvector(), combineLoopSADPattern(), combineSelect(), combineStore(), combineTargetShuffle(), combineToExtendVectorInReg(), CompactSwizzlableVector(), EltsFromConsecutiveLoads(), emitConstantSizeRepmov(), emitRepmovsB(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), ExtendToType(), ExtractBitFromMaskVector(), extractSubVector(), getCALLSEQ_START(), getCopyToParts(), getFauxShuffleMask(), getFPExtendOrRound(), getFRAMEADDR(), getMaskNode(), getParamsForOneTrueMaskedElt(), getScalarMaskingNode(), getShuffleHalfVectors(), getSplatValue(), insert1BitVector(), insertSubVector(), lower1BitShuffle(), lowerAddSubToHorizontalOp(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerFABSorFNEG(), LowerFCOPYSIGN(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), LowerFSINCOS(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerI128ToGR128(), LowerI64IntToFP_AVX512DQ(), LowerLoad(), lowerMasksToReg(), LowerMGATHER(), LowerMLOAD(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerSDIV(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerToTLSExecModel(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), LowerUMULO_SMULO(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), LowerVAARG(), LowerVACOPY(), LowerVASTART(), LowerVectorINT_TO_FP(), LowerZERO_EXTEND_Mask(), llvm::PPCTargetLowering::PerformDAGCombine(), performMADD_MSUBCombine(), PerformSTORECombine(), PrepareCall(), PrepareTailCall(), reduceVMULWidth(), ReorganizeVector(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), SplitAndExtendv16i1(), splitAndLowerShuffle(), vectorizeExtractedCast(), and widenSubVector().
getJumpTable()
SDValue SelectionDAG::getJumpTable (int JTI, EVT VT, bool isTarget = false, unsigned char TargetFlags = 0)
Definition at line 1403 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, getVTList(), llvm::ISD::JumpTable, N, llvm::None, and llvm::ISD::TargetJumpTable.
Referenced by getTargetJumpTable(), and llvm::SelectionDAGBuilder::visitJumpTable().
getLabelNode()
SDValue SelectionDAG::getLabelNode (unsigned Opcode, const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 1786 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, and llvm::MVT::Other.
Referenced by getEHLabel().
getLibInfo()
const TargetLibraryInfo & llvm::SelectionDAG::getLibInfo () const inline
Definition at line 417 of file SelectionDAG.h.
getLifetimeNode()
SDValue SelectionDAG::getLifetimeNode (bool IsStart, const SDLoc & dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset = -1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
Definition at line 6626 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getDataLayout(), llvm::SDLoc::getDebugLoc(), getFrameIndex(), llvm::SDLoc::getIROrder(), getTargetLoweringInfo(), getVTList(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, N, NewSDValueDbgMsg(), llvm::MVT::Other, and Size.
getLoad() [1/4]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 6779 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
getLoad() [2/4]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment = 0, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
This function will set the MOLoad flag on MMOFlags, but you can set it if you want. The MOStore flag must not be set.
Definition at line 6769 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
Referenced by bitcastf32Toi32(), llvm::X86TargetLowering::BuildFILD(), combineBVOfConsecutiveLoads(), combineLoad(), combineMaskedLoadConstantMask(), combineStore(), EltsFromConsecutiveLoads(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), expandf64Toi32(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrLocal(), getExtLoad(), getFRAMEADDR(), getIndexedLoad(), getLoad(), getMemCmpLoad(), getMemmoveLoadsAndStores(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerF128Load(), llvm::SparcTargetLowering::LowerF128Op(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), LowerLoad(), lowerMSALoadIntr(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVAARG(), llvm::SparcTargetLowering::makeAddress(), narrowExtractedVectorLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformVMOVRRDCombine(), PrepareCall(), reduceMaskedLoadToScalarLoad(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), unpackF64OnRV32DSoftABI(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getLoad() [3/4]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand * MMO)
Definition at line 6720 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), Indexed, llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ISD::LOAD, N, NewSDValueDbgMsg(), llvm::ISD::NON_EXTLOAD, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
getLoad() [4/4]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment = 0, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Definition at line 6695 of file SelectionDAG.cpp.
References assert(), getEVTAlignment(), getLoad(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, and llvm::MachinePointerInfo::V.
getLogicalNOT()
SDValue SelectionDAG::getLogicalNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
Definition at line 1164 of file SelectionDAG.cpp.
References getBoolConstant(), getNode(), and llvm::ISD::XOR.
Referenced by llvm::HexagonTargetLowering::LowerAddSubCarry().
getMachineFunction()
MachineFunction & llvm::SelectionDAG::getMachineFunction () const inline
Definition at line 410 of file SelectionDAG.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIVPow2(), CalculateTailCallSPDiff(), llvm::AArch64TargetLowering::canMergeStoresTo(), llvm::X86TargetLowering::canMergeStoresTo(), combineFMinNumFMaxNum(), combineMul(), combineOr(), combineReductionToHorizontal(), combineStore(), llvm::BaseIndexOffset::computeAliasing(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), CreateStackTemporary(), emitConstantSizeRepmov(), emitLockedStackOp(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::BaseIndexOffset::equalBaseIndex(), errorUnsupported(), llvm::X86TargetLowering::expandIndirectJTBranch(), ExpandPowI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), fail(), llvm::SelectionDAGBuilder::FindMergedConditions(), fixupFuncForFI(), foldFPToIntToFP(), getAddressForMemoryInput(), llvm::MipsTargetLowering::getAddrLocal(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), llvm::MipsTargetLowering::getGlobalReg(), getLoad(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemIntrinsicNode(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::MipsTargetLowering::getOpndList(), llvm::X86TargetLowering::getRegisterByName(), GetRegistersForValue(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStore(), GetTLSADDR(), getTOCEntry(), getTruncStore(), getv64i1Argument(), hasReturnsTwiceAttr(), InferPointerInfo(), InferPtrAlignment(), isConsecutiveLSLoc(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::TargetLowering::isInTailCallPosition(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAndToBT(), LowerAsSplatVectorLoad(), LowerATOMIC_STORE(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFPOWI(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), LowerFunnelShift(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerIncomingStatepointValue(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), LowerINTRINSIC_W_CHAIN(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerStatepointMetaArgs(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), LowerToTLSLocalDynamicModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVACOPY(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), MarkEHGuard(), MarkEHRegistrationNode(), narrowExtractedVectorLoad(), PerformADDCombineWithOperands(), performBRCONDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PostISelFolding(), PrepareCall(), promoteToConstantPool(), recoverFramePointer(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::AMDGPUTargetLowering::SelectFlatOffset(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), setUsesTOCBasePtr(), llvm::AArch64TargetLowering::shouldExpandShift(), llvm::RISCVTargetLowering::shouldExpandShift(), llvm::X86TargetLowering::shouldExpandShift(), shouldUseHorizontalOp(), llvm::TargetLowering::SimplifySetCC(), spillIncomingStatepointValue(), splitStores(), llvm::AMDGPUTargetLowering::storeStackInputValue(), StoreTailCallArgumentsToStackSlot(), llvm::X86InstrInfo::unfoldMemoryOperand(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromRegLoc(), viewGraph(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getMachineNode() [1/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 7898 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [2/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
getMachineNode - These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
Note that getMachineNode returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one.
Definition at line 7817 of file SelectionDAG.cpp.
References getMachineNode(), getVTList(), and llvm::None.
Referenced by llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), llvm::SITargetLowering::copyToM0(), createGPRPairNode(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), emitLockedStackOp(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandIntrinsicWChainHelper(), getLeftShift(), getLoadStackGuard(), getMachineNode(), getPrefetchNode(), getTargetExtractSubreg(), getTargetInsertSubreg(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBITCAST(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFNEGorFABS(), lowerI128ToGR128(), llvm::SystemZTargetLowering::LowerOperationWrapper(), narrowIfNeeded(), optimizeLogicalImm(), performBitcastCombine(), llvm::SITargetLowering::PostISelFolding(), ReplaceBITCASTResults(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), selectI64Imm(), selectI64ImmDirect(), selectImm(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getMachineNode() [3/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 7845 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [4/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1)
Definition at line 7823 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [5/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 7830 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [6/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7837 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [7/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 7867 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [8/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 7891 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [9/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
Definition at line 7874 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [10/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7882 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [11/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 7851 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [12/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7859 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [13/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 7905 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MVT::Glue, N, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
getMaskedGather()
SDValue SelectionDAG::getMaskedGather (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO)
Definition at line 7024 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::ISD::MGATHER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::X86TargetLowering::ReplaceNodeResults().
getMaskedLoad()
SDValue SelectionDAG::getMaskedLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand * MMO, ISD::LoadExtType ExtTy, bool IsExpanding = false)
Definition at line 6966 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), llvm::ISD::MLOAD, N, NewSDValueDbgMsg(), and llvm::MVT::Other.
Referenced by combineMaskedLoad(), combineMaskedLoadConstantMask(), and LowerMLOAD().
getMaskedScatter()
SDValue SelectionDAG::getMaskedScatter (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO)
Definition at line 7064 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::ISD::MSCATTER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by LowerMSCATTER().
getMaskedStore()
SDValue SelectionDAG::getMaskedStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Mask, EVT MemVT, MachineMemOperand * MMO, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 6994 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), llvm::ISD::MSTORE, N, NewSDValueDbgMsg(), and llvm::MVT::Other.
Referenced by combineMaskedStore(), LowerINTRINSIC_W_CHAIN(), and LowerMSTORE().
getMCSymbol()
SDValue SelectionDAG::getMCSymbol (MCSymbol * Sym, EVT VT)
Definition at line 1529 of file SelectionDAG.cpp.
References N.
Referenced by recoverFramePointer().
getMDNode()
SDValue SelectionDAG::getMDNode (const MDNode * MD)
Return an MDNodeSDNode which holds an MDNode.
Definition at line 1844 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::ISD::MDNODE_SDNODE, N, llvm::None, and llvm::MVT::Other.
getMemBasePlusOffset()
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, unsigned Offset, const SDLoc & DL)
Returns sum of the base pointer and offset.
Definition at line 5714 of file SelectionDAG.cpp.
References llvm::ISD::ADD, getConstant(), getNode(), and llvm::SDValue::getValueType().
Referenced by combineLoad(), combineStore(), EmitUnrolledSetTag(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getParamsForOneTrueMaskedElt(), lowerShuffleAsBroadcast(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), narrowExtractedVectorLoad(), scalarizeVectorStore(), and splitVectorStore().
getMemcpy()
SDValue SelectionDAG::getMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6163 of file SelectionDAG.cpp.
References assert(), checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcpy(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), llvm::Type::getInt8PtrTy(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), getMemcpyLoadsAndStores(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
Referenced by CreateCopyOfByValArgument(), emitConstantSizeRepmov(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), and LowerVACOPY().
getMemIntrinsicNode() [1/2]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand * MMO)
Definition at line 6585 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::ISD::FIRST_TARGET_MEMORY_OPCODE, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::MVT::Glue, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, N, llvm::SDVTList::NumVTs, llvm::ISD::PREFETCH, and llvm::SDVTList::VTs.
getMemIntrinsicNode() [2/2]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, unsigned Align = 0, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, unsigned Size = 0, const AAMDNodes & AAInfo = AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
Opcode may be INTRINSIC_VOID, INTRINSIC_W_CHAIN, or a target-specific opcode with a value not less than FIRST_TARGET_MEMORY_OPCODE.
Definition at line 6568 of file SelectionDAG.cpp.
References getEVTAlignment(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), getMemIntrinsicNode(), llvm::EVT::getStoreSize(), and Size.
Referenced by llvm::X86TargetLowering::BuildFILD(), CombineBaseUpdate(), combineCVTP2I_CVTTP2I(), combineShuffle(), CombineVLDDUP(), combineX86INT_TO_FP(), createLoadLR(), createStoreLR(), EltsFromConsecutiveLoads(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), getMemIntrinsicNode(), getTOCEntry(), LowerATOMIC_STORE(), lowerAtomicArithWithLOCK(), llvm::NVPTXTargetLowering::LowerCall(), LowerCMP_SWAP(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::NVPTXTargetLowering::LowerReturn(), LowerStore(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformVDUPCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), and llvm::X86TargetLowering::ReplaceNodeResults().
getMemmove()
SDValue SelectionDAG::getMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6279 of file SelectionDAG.cpp.
References assert(), checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemmove(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), llvm::Type::getInt8PtrTy(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), getMemmoveLoadsAndStores(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
getMemset()
SDValue SelectionDAG::getMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 6383 of file SelectionDAG.cpp.
References assert(), checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemset(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), llvm::Type::getInt8PtrTy(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), getMemsetStores(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::FastISel::CallLoweringInfo::setTailCall(), and Size.
Referenced by llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset().
getMergeValues()
SDValue SelectionDAG::getMergeValues (ArrayRef< SDValue > Ops, const SDLoc & dl)
Create a MERGE_VALUES node from the given operands.
getMergeValues - Create a MERGE_VALUES node from the given operands.
Definition at line 6557 of file SelectionDAG.cpp.
References getNode(), getVTList(), llvm::ISD::MERGE_VALUES, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::ArrayRef< T >::size().
Referenced by combineX86AddSub(), constructRetValue(), getAVX2GatherNode(), getGatherNode(), llvm::SelectionDAGBuilder::getValueImpl(), LowerADDC_ADDE_SUBC_SUBE(), llvm::HexagonTargetLowering::LowerAddSubCarry(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), LowerF128Load(), LowerINTRINSIC_W_CHAIN(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), LowerMGATHER(), LowerMLOAD(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), LowerREADCYCLECOUNTER(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::performLoadCombine(), llvm::AMDGPUTargetLowering::performMulLoHi24Combine(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::WidenVectorLoad().
getNode() [1/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 7267 of file SelectionDAG.cpp.
References getNode(), and getVTList().
getNode() [2/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT)
Gets or creates the specified node.
Definition at line 4257 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, NewSDValueDbgMsg(), and llvm::None.
getNode() [3/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
Definition at line 7186 of file SelectionDAG.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), getNode(), and llvm::ArrayRef< T >::size().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), addShuffleForVecExtend(), llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustLoadValueTypeImpl(), BuildExactSDIV(), buildFromShuffleMostly(), BuildIntrinsicOp(), buildMergeScalars(), buildPCRelGlobalAddress(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), BuildVSLDOI(), canonicalizeBitSelect(), chainLoadsAndStoresForMemcpy(), clampDynamicVectorIndex(), CollectOpsToWiden(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndLoadToBZHI(), combineAndMaskToShift(), combineAndnp(), CombineANDShift(), combineANDXORWithAllOnesIntoANDNP(), CombineBaseUpdate(), combineBasicSADPattern(), combineBEXTR(), combineBitcast(), combineBitcastvxi1(), combineBrCond(), combineBT(), combineCarryThroughADD(), combineCastedMaskArithmetic(), combineCMov(), combineCMP(), combineCompareEqual(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineExtInVec(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddFsub(), combineFAndFNotToFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacy(), combineFMinNumFMaxNum(), combineFneg(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineIncDecVector(), combineInsertSubvector(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLoopMAddPattern(), combineLoopSADPattern(), combineMaskedLoad(), combineMaskedStore(), combineMinNumMaxNum(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineOrCmpEqZeroToCtlzSrl(), combineParity(), combinePMULDQ(), combinePMULH(), combineReductionToHorizontal(), combineRedundantDWordShuffle(), combineSBB(), combineScalarToVector(), combineSelect(), combineSelectAndUse(), combineSelectOfTwoConstants(), combineSetCC(), combineSext(), combineSextInRegCmov(), combineShiftLeft(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleToAddSubOrFMAddSub(), combineShuffleToFMAddSub(), combineShuffleToVectorExtend(), combineSignExtendInReg(), combineSIntToFP(), combineStore(), combineSub(), combineSubToSubus(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToExtendVectorInReg(), combineToFPTruncExtElt(), combineTruncate(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineXor(), combineZext(), CompactSwizzlableVector(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertIntLogicToFPLogic(), convertLocVTToValVT(), ConvertSelectToConcatVector(), convertShiftLeftToScale(), convertValVTToLocVT(), createCMovFP(), createFPCmp(), createGPRPairNode(), createLoadLR(), createMMXBuildVector(), createPSADBW(), createStoreLR(), createVariablePermute(), customLegalizeToWOp(), detectAVGPattern(), detectPMADDUBSW(), detectUSatPattern(), distributeOpThroughSelect(), EltsFromConsecutiveLoads(), emitCLC(), EmitCMP(), emitCmp(), emitComparison(), emitConditionalComparison(), emitConstantSizeRepmov(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), EmitKORTEST(), emitMemMem(), emitRepmovs(), emitSETCC(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), EmitTest(), EmitUnrolledSetTag(), EmitVectorComparison(), Expand64BitShift(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), ExpandBITCAST(), ExpandBVWithShuffles(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandExp(), expandExp2(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), ExpandHorizontalBinOp(), llvm::TargetLowering::expandIndirectJTBranch(), llvm::X86TargetLowering::expandIndirectJTBranch(), expandIntrinsicWChainHelper(), expandLog(), expandLog10(), expandLog2(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), expandPow(), ExpandPowI(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandV4F32ToV2F64(), expandVAArg(), llvm::TargetLowering::expandVecReduce(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendToType(), ExtractBitFromMaskVector(), extractF64Exponent(), extractLOHI(), extractShiftForRotate(), extractSubVector(), ExtractVectorElements(), flipBoolean(), foldAddSubBoolOfMaskedVal(), foldAddSubMasked1(), foldAddSubOfSignBit(), foldBitcastedFPLogic(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), foldExtendedSignBitTest(), foldFPToIntToFP(), foldFreeOpFromSelect(), FoldIntToFPToInt(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldShuffleOfConcatUndefs(), foldShuffleOfHorizOp(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), genConstMult(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrGPRel(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MipsTargetLowering::getAddrNonPIC(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAnyExtOrTrunc(), getBitcast(), getBoolExtOrTrunc(), getBoundedStrlen(), getBuildVector(), getBuildVectorSplat(), getCALLSEQ_END(), getCALLSEQ_START(), getCCResult(), getConstant(), llvm::SelectionDAGBuilder::getControlRoot(), getCopyFromParts(), getCopyFromPartsVector(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), getCopyToReg(), llvm::RegsForValue::getCopyToRegs(), GetDemandedBits(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEstimate(), GetExponent(), getExtendInVec(), getFauxShuffleMask(), getFLUSHW(), getFPBinOp(), getFPExtendOrRound(), getFPTernOp(), getFRAMEADDR(), getGeneralPermuteNode(), getGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::getHiHalf64(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLimitedPrecisionExp2(), getLoadExtOrTrunc(), getLogicalNOT(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMad64_32(), getMaskNode(), getMemBasePlusOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getMergeValues(), getMul24(), GetNegatedExpression(), getNode(), getNOT(), getObjectPtrOffset(), getPermuteNode(), llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPMOVMSKB(), llvm::AMDGPUTargetLowering::getRecipEstimate(), getReductionSDNode(), GetRegistersForValue(), getScalarMaskingNode(), getSelect(), getSelectCC(), getSetCC(), getSETCC(), getSExtOrTrunc(), getShuffleHalfVectors(), GetSignificand(), getSplatBuildVector(), getSplatValue(), llvm::NVPTXTargetLowering::getSqrtEstimate(), llvm::AMDGPUTargetLowering::getSqrtEstimate(), getStackArgumentTokenFactor(), getTargetVShiftByConstNode(), getTargetVShiftNode(), GetTLSADDR(), getTOCEntry(), getTokenFactor(), getUNDEF(), getv64i1Argument(), getVAArg(), llvm::TargetLowering::getVectorElementPointer(), getVectorMaskingNode(), getVectorShuffle(), getVShift(), getX86XALUOOp(), getZeroExtendInReg(), getZeroVector(), getZExtOrTrunc(), HandleMergeInputChains(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), InsertBitToMaskVector(), insertSubVector(), isFNEG(), isFusableLoadOpStorePattern(), IsNOT(), joinDwords(), Legalize(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), Lower256IntVSETCC(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), lowerAddSub(), LowerADDSUBCARRY(), llvm::HexagonTargetLowering::LowerAddSubCarry(), lowerAddSubToHorizontalOp(), LowerAndToBT(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), LowerAsSplatVectorLoad(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::HexagonTargetLowering::LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), LowerATOMIC_STORE(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBR_CC(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTEND_VECTOR_INREG(), llvm::MSP430TargetLowering::LowerExternalSymbol(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), LowerF64Op(), lowerFABS32(), lowerFABS64(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), LowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFLOG(), llvm::AMDGPUTargetLowering::LowerFNEARBYINT(), LowerFNEGorFABS(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), LowerFP_EXTEND(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_SINT(), LowerFP_TO_SINT(), lowerFP_TO_SINT_STORE(), llvm::AMDGPUTargetLowering::LowerFP_TO_UINT(), LowerFPOWI(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerFREM(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerGR128Binary(), lowerGR128ToI128(), LowerHorizontalByteSum(), lowerI128ToGR128(), LowerI64IntToFP_AVX512DQ(), lowerICMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLabelRef(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), lowerMasksToReg(), LowerMemOpCallTo(), LowerMGATHER(), LowerMINMAX(), LowerMLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), LowerMSCATTER(), LowerMUL(), llvm::LanaiTargetLowering::LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerPREFETCH(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), lowerRegToMasks(), llvm::AMDGPUTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftParts(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShuffleToEXPAND(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSHUFPS(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerStore(), LowerSTORE(), lowerToAddSubOrFMAddSub(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), LowerVAARG(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVectorIntUnary(), lowerVectorShuffleAsByteShiftMask(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), lowerX86FPLogicOp(), LowerXALUO(), LowerXOR(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), makeEquivalentMemoryOrdering(), llvm::SparcTargetLowering::makeHiLoPair(), matchPMADDWD(), matchPMADDWD_2(), moveBelowOrigChain(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), narrowVectorSelect(), optimizeLogicalImm(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), performADDCombine(), PerformADDCombineWithOperands(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), performBitcastCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performBRCONDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), PerformExtendCombine(), performExtendCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), performGlobalAddressCombine(), PerformHWLoopCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), PerformIntrinsicCombine(), performIntrinsicCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performMADD_MSUBCombine(), performMulCombine(), PerformMULCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHi24Combine(), performORCombine(), PerformORCombine(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), PerformREMCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), PerformSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), performTBZCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformUMLALCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), performVectorCompareAndMaskUnaryOpCombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSelectCombine(), performVSELECTCombine(), performXORCombine(), PrepareCall(), PrepareTailCall(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), ReorganizeVector(), ReplaceAllUsesWith(), ReplaceBITCASTResults(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), ReplaceReductionResults(), replaceShuffleOfInsert(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::TargetLowering::ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), split256IntArith(), split512IntArith(), llvm::AMDGPUTargetLowering::split64BitValue(), SplitAndExtendv16i1(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::SITargetLowering::splitBinaryVectorOp(), splitInt128(), SplitOpsAndApply(), splitStores(), splitStoreSplat(), llvm::SITargetLowering::splitUnaryVectorOp(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), SplitVSETCC(), stripModuloOnShift(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateVecElts(), truncateVectorWithPACK(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineShiftImm(), tryCombineToBSL(), tryCombineToEXTR(), tryExtendDUPToExtractHigh(), tryFormConcatFromShuffle(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), tryToFoldExtOfLoad(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), vectorizeExtractedCast(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), visitFMinMax(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), visitORCommutative(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), llvm::AMDGPUTargetLowering::WidenVectorLoad(), WinDBZCheckDenominator(), and XFormVExtractWithShuffleIntoLoad().
getNode() [4/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 7202 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BR_CC, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, E, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), getValueType(), getVTList(), llvm::MVT::Glue, N, NewSDValueDbgMsg(), llvm::ISD::SELECT_CC, and llvm::ArrayRef< T >::size().
getNode() [5/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 5031 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddNodeIDNode(), llvm::ISD::AND, llvm::APInt::ashrInPlace(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::EVT::bitsLE(), llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, C, llvm::ISD::CONCAT_VECTORS, E, llvm::ISD::EntryToken, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), foldConstantFPMath(), llvm::ISD::FP_ROUND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FREM, llvm::ISD::FSUB, getAllOnesConstant(), getAnyExtOrTrunc(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::SDValue::getNode(), getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getSExtOrTrunc(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i1, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ConstantSDNode::isAllOnesValue(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::ConstantSDNode::isNullValue(), llvm::EVT::isSimple(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), LLVM_FALLTHROUGH, llvm::Log2_32_Ceil(), llvm::APInt::lshr(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, NewSDValueDbgMsg(), llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDSAT, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, simplifyFPBinop(), simplifyShift(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SSUBSAT, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, llvm::APInt::trunc(), llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::APInt::uge(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UREM, llvm::ISD::USUBSAT, and llvm::ISD::XOR.
getNode() [6/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 5457 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, E, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FMA, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantVectorArithmetic(), FoldSetCC(), llvm::APFloat::fusedMultiplyAdd(), getConstantFP(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, N, NewSDValueDbgMsg(), llvm::APFloatBase::rmNearestTiesToEven, llvm::ISD::SELECT, llvm::ISD::SETCC, simplifySelect(), llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::VSELECT.
getNode() [7/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 5593 of file SelectionDAG.cpp.
References getNode().
getNode() [8/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 5599 of file SelectionDAG.cpp.
References getNode().
getNode() [9/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 4274 of file SelectionDAG.cpp.
References llvm::APInt::abs(), llvm::ISD::ABS, AddNodeIDNode(), llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, assert(), llvm::ISD::BITCAST, llvm::APFloat::bitcastToAPInt(), llvm::ISD::BITREVERSE, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::APInt::byteSwap(), C, llvm::APFloat::changeSign(), llvm::APFloat::clearSign(), llvm::ISD::CONCAT_VECTORS, llvm::APFloat::convert(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertToInteger(), llvm::APInt::countLeadingZeros(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, E, EVTToAPFloatSemantics(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::ISD::FNEG, FoldBUILD_VECTOR(), FoldConstantVectorArithmetic(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::APInt::getBitWidth(), getConstant(), getConstantFP(), llvm::SDValue::getConstantOperandVal(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::SDValue::getNode(), getNode(), llvm::APInt::getNullValue(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getTarget(), getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::APInt::getZExtValue(), llvm::MVT::Glue, llvm::SDNodeFlags::hasNoSignedZeros(), llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), ignored(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::MERGE_VALUES, N, NewSDValueDbgMsg(), llvm::APFloatBase::opInexact, llvm::APFloatBase::opInvalidOp, llvm::APFloatBase::opOK, llvm::APInt::reverseBits(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardNegative, llvm::APFloatBase::rmTowardPositive, llvm::APFloatBase::rmTowardZero, llvm::APFloat::roundToIntegral(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::sextOrTrunc(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::TokenFactor, transferDbgValues(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::UNDEF, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, and llvm::APInt::zextOrTrunc().
getNode() [10/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList)
Definition at line 7322 of file SelectionDAG.cpp.
References getNode(), and llvm::None.
getNode() [11/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops)
Definition at line 7272 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::AND, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::MVT::Glue, llvm::MVT::i1, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, and llvm::SDVTList::VTs.
getNode() [12/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N)
Definition at line 7327 of file SelectionDAG.cpp.
References getNode().
getNode() [13/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2)
Definition at line 7333 of file SelectionDAG.cpp.
References getNode().
getNode() [14/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
Definition at line 7339 of file SelectionDAG.cpp.
References getNode().
getNode() [15/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 7345 of file SelectionDAG.cpp.
References getNode().
getNode() [16/16]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 7351 of file SelectionDAG.cpp.
References getNode().
getNodeIfExists()
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags = SDNodeFlags())
Get the specified node if it's already available, or else return NULL.
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
Definition at line 7954 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MVT::Glue, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by combineX86AddSub(), and llvm::TargetLowering::SimplifySetCC().
getNOT()
SDValue SelectionDAG::getNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
getNOT - Create a bitwise NOT operation as (XOR Val, -1).
Definition at line 1157 of file SelectionDAG.cpp.
References llvm::APInt::getAllOnesValue(), getConstant(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), and llvm::ISD::XOR.
Referenced by combineSelectOfTwoConstants(), combineSetCC(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), foldExtendedSignBitTest(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerFROUND64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerMSABitClear(), LowerVSETCC(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getObjectPtrOffset() [1/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Op, int64_t Offset) inline
Create an add instruction with appropriate flags when used for addressing some offset of an object.
i.e. if a load is split into multiple components, create an add nuw from the base pointer to the offset.
Definition at line 832 of file SelectionDAG.h.
References getConstant(), and getObjectPtrOffset().
Referenced by llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getObjectPtrOffset(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
getObjectPtrOffset() [2/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Op, SDValue Offset) inline
Definition at line 837 of file SelectionDAG.h.
References llvm::ISD::ADD, getNode(), and llvm::SDNodeFlags::setNoUnsignedWrap().
getORE()
OptimizationRemarkEmitter & llvm::SelectionDAG::getORE () const inline
Definition at line 421 of file SelectionDAG.h.
getPass()
const Pass * llvm::SelectionDAG::getPass () const inline
Definition at line 411 of file SelectionDAG.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::passSpecialInputs().
getPtrExtendInReg()
SDValue SelectionDAG::getPtrExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
This may be either a zero extend or a sign extend.
Definition at line 1150 of file SelectionDAG.cpp.
References getZeroExtendInReg().
getPtrExtOrTrunc()
SDValue SelectionDAG::getPtrExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
Definition at line 1144 of file SelectionDAG.cpp.
References getZExtOrTrunc().
Referenced by getLoadStackGuard(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getRegister()
SDValue SelectionDAG::getRegister (unsigned Reg, EVT VT)
Definition at line 1752 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, llvm::None, and llvm::ISD::Register.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), createCMovFP(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), emitLockedStackOp(), EmitUnrolledSetTag(), llvm::MipsTargetLowering::getAddrGPRel(), getCopyFromReg(), getCopyToReg(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), llvm::MipsTargetLowering::getOpndList(), getPrefetchNode(), getTOCEntry(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerEH_RETURN(), lowerFABS32(), lowerFABS64(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), LowerVASTART(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::SITargetLowering::PostISelFolding(), PrepareCall(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), llvm::SelectionDAGISel::SelectCodeCommon(), and selectImm().
getRegisterMask()
SDValue SelectionDAG::getRegisterMask (const uint32_t * RegMask)
Definition at line 1767 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::None, llvm::ISD::RegisterMask, and llvm::MVT::Untyped.
Referenced by llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsTargetLowering::getOpndList(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::SparcTargetLowering::LowerGlobalTLSAddress().
getRoot()
const SDValue & llvm::SelectionDAG::getRoot () const inline
Return the root tag of the SelectionDAG.
Definition at line 470 of file SelectionDAG.h.
Referenced by llvm::checkForCycles(), llvm::SelectionDAGBuilder::getControlRoot(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), getMemCmpLoad(), llvm::SelectionDAGBuilder::getRoot(), Legalize(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), LowerFPOWI(), RemoveDeadNode(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and llvm::DAGTypeLegalizer::run().
getSDCallSiteInfo()
CallSiteInfo llvm::SelectionDAG::getSDCallSiteInfo (const SDNode * CallNode) inline
Definition at line 1676 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
getSelect()
SDValue llvm::SelectionDAG::getSelect (const SDLoc & DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS) inline
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
Definition at line 976 of file SelectionDAG.h.
References assert(), getNode(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), llvm::ISD::SELECT, and llvm::ISD::VSELECT.
Referenced by llvm::TargetLowering::BuildUDIV(), combineFMinNumFMaxNum(), combineLogicBlendIntoPBLENDV(), combineMaskedLoadConstantMask(), combineSelect(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandUINT_TO_FP(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerMINMAX(), LowerRotate(), LowerShift(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBlend(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerZERO_EXTEND_Mask(), narrowExtractedVectorSelect(), performSelectCombine(), tryToFoldExtendOfConstant(), and UnrollVectorOverflowOp().
getSelectCC()
SDValue llvm::SelectionDAG::getSelectCC (const SDLoc & DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond) inline
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 988 of file SelectionDAG.h.
References getCondCode(), getNode(), llvm::SDValue::getValueType(), and llvm::ISD::SELECT_CC.
Referenced by createVariablePermute(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandMUL_LOHI(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), and llvm::R600TargetLowering::PerformDAGCombine().
getSelectionDAGInfo()
const SelectionDAGTargetInfo & llvm::SelectionDAG::getSelectionDAGInfo () const inline
Definition at line 418 of file SelectionDAG.h.
getSetCC()
SDValue llvm::SelectionDAG::getSetCC (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond) inline
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 963 of file SelectionDAG.h.
References assert(), getCondCode(), getNode(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), llvm::ISD::SETCC, and llvm::ISD::SETCC_INVALID.
Referenced by llvm::TargetLowering::BuildUDIV(), combineAnd(), combineExtractVectorElt(), combineExtSetcc(), combineFMinNumFMaxNum(), combineHorizontalPredicateResult(), combineSelect(), combineSetCC(), combineToExtendBoolVectorInReg(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), FoldSetCC(), foldXorTruncShiftIntoCmp(), lower1BitShuffle(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerEXTEND_VECTOR_INREG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND32_16(), llvm::AMDGPUTargetLowering::LowerFROUND64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerIntVSETCC_AVX512(), LowerMINMAX(), LowerMULH(), LowerScalarImmediateShift(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUMULO_SMULO(), LowerVectorCTLZInRegLUT(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), performVSelectCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifySetCC(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getSExtOrTrunc()
SDValue SelectionDAG::getSExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
Definition at line 1111 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), getNode(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by combineGatherScatter(), combineShuffleOfScalars(), combineToExtendBoolVectorInReg(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandFP_TO_SINT(), foldCONCAT_VECTORS(), getNode(), LowerBITCAST(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerLoad(), LowerMULH(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerVSETCC(), llvm::AMDGPUTargetLowering::performMulCombine(), and llvm::AMDGPUTargetLowering::performMulhsCombine().
getShiftAmountConstant()
SDValue SelectionDAG::getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc & DL, bool LegalTypes = true)
Definition at line 1294 of file SelectionDAG.cpp.
References getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getShiftAmountTy().
Referenced by getCopyToParts(), llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::SITargetLowering::passSpecialInputs().
getShiftAmountOperand()
SDValue SelectionDAG::getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
getShiftAmountOperand - Return the specified value casted to the target's desired shift amount type.
Definition at line 1889 of file SelectionDAG.cpp.
References getDataLayout(), llvm::TargetLoweringBase::getShiftAmountTy(), getZExtOrTrunc(), and llvm::EVT::isVector().
Referenced by UnrollVectorOp().
getSplatBuildVector()
SDValue llvm::SelectionDAG::getSplatBuildVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
VT must be a vector type. Op's type must be the same as (or, for integers, a type wider than) VT's element type.
Definition at line 767 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isInteger(), and llvm::ISD::UNDEF.
Referenced by getConstant(), getConstantFP(), getMemsetValue(), getUniformBase(), and getVectorShuffle().
getSplatSourceVector()
SDValue SelectionDAG::getSplatSourceVector (SDValue V, int & SplatIndex)
If V is a splatted value, return the source vector and its splat index.
Definition at line 2350 of file SelectionDAG.cpp.
References llvm::countTrailingOnes(), llvm::APInt::getAllOnesValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), Idx, isSplatValue(), llvm::APInt::isSubsetOf(), llvm::peekThroughExtractSubvectors(), and llvm::ISD::VECTOR_SHUFFLE.
Referenced by getSplatValue(), and scalarizeBinOpOfSplats().
getSplatValue()
SDValue SelectionDAG::getSplatValue (SDValue V)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
Definition at line 2387 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, getIntPtrConstant(), getNode(), and getSplatSourceVector().
Referenced by LowerScalarVariableShift().
GetSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetSplitDestVTs (const EVT & VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
GetSplitDestVTs - Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
Definition at line 9249 of file SelectionDAG.cpp.
References getContext(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::TargetLoweringBase::getTypeToTransformTo(), and llvm::EVT::isVector().
Referenced by llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), SplitVector(), and SplitVSETCC().
getSrcValue()
SDValue SelectionDAG::getSrcValue (const Value * v)
Construct a node to track a Value* through the backend.
Definition at line 1826 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::Value::getType(), getVTList(), llvm::Type::isPointerTy(), N, llvm::None, llvm::MVT::Other, and llvm::ISD::SRCVALUE.
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
getStackArgumentTokenFactor()
SDValue SelectionDAG::getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
getStackArgumentTokenFactor - Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
This is used in tail call lowering to protect stack arguments from being clobbered.
Definition at line 5608 of file SelectionDAG.cpp.
References getEntryNode(), getNode(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ISD::TokenFactor.
getStore() [1/2]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 6841 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getUNDEF(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), llvm::MVT::Other, llvm::ISD::STORE, and llvm::ISD::UNINDEXED.
getStore() [2/2]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment = 0, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Helper function to build ISD::STORE nodes.
This function will set the MOStore flag on MMOFlags, but you can set it if you want. The MOLoad and MOInvariant flags must not be set.
Definition at line 6820 of file SelectionDAG.cpp.
References assert(), getEVTAlignment(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), getStore(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, and llvm::MachinePointerInfo::V.
Referenced by combineStore(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getStore(), getTruncStore(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), LowerF128Store(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerFP_TO_SINT_STORE(), LowerMemOpCallTo(), lowerMSAStoreIntr(), LowerStore(), LowerSTORE(), LowerTruncateVectorStore(), LowerVAARG(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), memsetStore(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), reduceMaskedStoreToScalarStore(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), spillIncomingStatepointValue(), splitStores(), splitStoreSplat(), splitVectorStore(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::AMDGPUTargetLowering::storeStackInputValue(), and StoreTailCallArgumentsToStackSlot().
getSubtarget()
const TargetSubtargetInfo & llvm::SelectionDAG::getSubtarget () const inline
Definition at line 415 of file SelectionDAG.h.
References llvm::MachineFunction::getSubtarget().
Referenced by emitComparison(), emitConditionalComparison(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), init(), llvm::PPC::isVPKUDUMShuffleMask(), lowerMSASplatZExt(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), patchMatchingInput(), recoverFramePointer(), and truncateVecElts().
getSymbolFunctionGlobalAddress()
SDValue SelectionDAG::getSymbolFunctionGlobalAddress (SDValue Op, Function ** TargetFunction = nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
Additionally can provide the matched function. Panics the function doesn't exists.
Definition at line 8633 of file SelectionDAG.cpp.
References assert(), llvm::raw_ostream::flush(), llvm::GlobalValue::getAddressSpace(), getDataLayout(), llvm::MachineFunction::getFunction(), llvm::Module::getFunction(), getGlobalAddress(), llvm::TargetLoweringBase::getPointerTy(), and llvm::report_fatal_error().
Referenced by llvm::NVPTXTargetLowering::LowerCall().
getTarget()
const TargetMachine & llvm::SelectionDAG::getTarget () const inline
Definition at line 414 of file SelectionDAG.h.
Referenced by combineFMinFMax(), combineFMinNumFMaxNum(), combineSelect(), llvm::ScheduleDAGSDNodes::EmitSchedule(), foldFPToIntToFP(), GetNegatedExpression(), getNode(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isFMAddSubOrFMSubAdd(), isKnownNeverNaN(), isLegalToCombineMinNumMaxNum(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerUINT_TO_FP_vXi32(), and PrepareCall().
getTargetBlockAddress()
SDValue llvm::SelectionDAG::getTargetBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, unsigned char TargetFlags = 0) inline
Definition at line 689 of file SelectionDAG.h.
References getBlockAddress().
Referenced by getTargetNode(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), and llvm::SparcTargetLowering::withTargetFlags().
getTargetConstant() [1/3]
SDValue llvm::SelectionDAG::getTargetConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 596 of file SelectionDAG.h.
References getConstant().
getTargetConstant() [2/3]
SDValue llvm::SelectionDAG::getTargetConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 600 of file SelectionDAG.h.
References getConstant().
getTargetConstant() [3/3]
SDValue llvm::SelectionDAG::getTargetConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 592 of file SelectionDAG.h.
References getConstant().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), addStackMapLiveVars(), buildPCRelGlobalAddress(), llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), createGPRPairNode(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::PPC::get_VSPLTI_elt(), getAL(), getAVX2GatherNode(), getCopyFromParts(), getGatherNode(), getIntOperandsFromRegisterString(), getLeftShift(), getPrefetchNode(), getScatterNode(), getTargetExtractSubreg(), getTargetInsertSubreg(), getUniformBase(), getVAArg(), getZeroVector(), isNEONModifiedImm(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::AVRTargetLowering::LowerAsmOperandForConstraint(), llvm::LanaiTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBITCAST(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), LowerCMP_SWAP(), LowerCTTZ(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), lowerVECTOR_SHUFFLE_VSHF(), narrowIfNeeded(), optimizeLogicalImm(), parseCachePolicy(), parseTexFail(), performBitcastCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), pushStackMapConstant(), ReplaceBITCASTResults(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::HexagonDAGToDAGISel::SelectAnyImmediate(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::AMDGPUTargetLowering::SelectFlatOffset(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), selectI64Imm(), selectI64ImmDirect(), selectImm(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getTargetConstantFP() [1/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT) inline
Definition at line 627 of file SelectionDAG.h.
References getConstantFP().
getTargetConstantFP() [2/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const ConstantFP & Val, const SDLoc & DL, EVT VT) inline
Definition at line 630 of file SelectionDAG.h.
References getConstantFP().
getTargetConstantFP() [3/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (double Val, const SDLoc & DL, EVT VT) inline
Definition at line 624 of file SelectionDAG.h.
References getConstantFP().
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
getTargetConstantPool() [1/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (const Constant * C, EVT VT, unsigned Align = 0, int Offset = 0, unsigned char TargetFlags = 0) inline
Definition at line 655 of file SelectionDAG.h.
References C, and getConstantPool().
Referenced by getTargetNode(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), promoteToConstantPool(), and llvm::SparcTargetLowering::withTargetFlags().
getTargetConstantPool() [2/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (MachineConstantPoolValue * C, EVT VT, unsigned Align = 0, int Offset = 0, unsigned char TargetFlags = 0) inline
Definition at line 663 of file SelectionDAG.h.
References C, and getConstantPool().
getTargetExternalSymbol()
SDValue SelectionDAG::getTargetExternalSymbol (const char * Sym, EVT VT, unsigned char TargetFlags = 0)
Definition at line 1538 of file SelectionDAG.cpp.
References N.
Referenced by llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), PrepareCall(), and llvm::SparcTargetLowering::withTargetFlags().
getTargetExtractSubreg()
SDValue SelectionDAG::getTargetExtractSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
getTargetExtractSubreg - A convenience function for creating TargetOpcode::EXTRACT_SUBREG nodes.
Definition at line 7934 of file SelectionDAG.cpp.
References getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by llvm::SITargetLowering::buildRSRC(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerF64Op(), LowerFNEGorFABS(), lowerGR128Binary(), lowerGR128ToI128(), NarrowVector(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), and llvm::HexagonDAGToDAGISel::SelectVAlign().
getTargetFrameIndex()
SDValue llvm::SelectionDAG::getTargetFrameIndex (int FI, EVT VT) inline
Definition at line 644 of file SelectionDAG.h.
References getFrameIndex().
Referenced by addStackMapLiveVars(), EmitUnrolledSetTag(), lowerIncomingStatepointValue(), lowerStatepointMetaArgs(), reservePreviousStackSlotForValue(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), and spillIncomingStatepointValue().
getTargetGlobalAddress()
SDValue llvm::SelectionDAG::getTargetGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, unsigned char TargetFlags = 0) inline
Definition at line 638 of file SelectionDAG.h.
References getGlobalAddress().
Referenced by buildPCRelGlobalAddress(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getTargetNode(), GetTLSADDR(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), PrepareCall(), llvm::HexagonDAGToDAGISel::SelectGlobalAddress(), and llvm::SparcTargetLowering::withTargetFlags().
getTargetIndex()
SDValue SelectionDAG::getTargetIndex (int Index, EVT VT, int64_t Offset = 0, unsigned char TargetFlags = 0)
Definition at line 1476 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::None, and llvm::ISD::TargetIndex.
getTargetInsertSubreg()
SDValue SelectionDAG::getTargetInsertSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
getTargetInsertSubreg - A convenience function for creating TargetOpcode::INSERT_SUBREG nodes.
Definition at line 7944 of file SelectionDAG.cpp.
References getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by LowerF64Op(), and LowerFNEGorFABS().
getTargetJumpTable()
SDValue llvm::SelectionDAG::getTargetJumpTable (int JTI, EVT VT, unsigned char TargetFlags = 0) inline
Definition at line 649 of file SelectionDAG.h.
References getJumpTable().
Referenced by llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), and llvm::MSP430TargetLowering::LowerJumpTable().
getTargetLoweringInfo()
const TargetLowering & llvm::SelectionDAG::getTargetLoweringInfo () const inline
Definition at line 416 of file SelectionDAG.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), addStackMapLiveVars(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIVPow2(), BuildVectorFromScalar(), combineBEXTR(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectors(), combineExtInVec(), combineExtractSubvector(), combineExtractVectorElt(), combineFMA(), combineFMinNumFMaxNum(), combineFneg(), combineGatherScatter(), combineHorizontalPredicateResult(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineMulToPMADDWD(), combineParity(), combinePMULDQ(), combineSelect(), combineSelectOfTwoConstants(), combineShuffle(), combineShuffleToFMAddSub(), combineStore(), combineToExtendVectorInReg(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineVectorInsert(), combineVectorShiftImm(), combineVectorShiftVar(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), EltsFromConsecutiveLoads(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), ExpandBITCAST(), expandVAArg(), expandVACopy(), foldCONCAT_VECTORS(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), getAddressForMemoryInput(), getConstVector(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getKnownUndefForVectorBinop(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetValue(), GetNegatedExpression(), GetRegistersForValue(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::init(), isAddSubOrSubAdd(), isBLACompatibleAddress(), isConsecutiveLSLoc(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), LowerATOMIC_STORE(), LowerBITCAST(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), LowerFPOWI(), LowerFSINCOS(), llvm::SelectionDAGBuilder::lowerInvokable(), LowerLoad(), LowerMemOpCallTo(), lowerShuffleAsElementInsertion(), lowerShuffleAsShift(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerUINT_TO_FP_i64(), LowerVASTART(), lowerVectorShuffle(), LowerVSETCC(), LowerXALUO(), LowerXOR(), matchLSNode(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowInsertExtractVectorBinOp(), llvm::ScheduleDAGSDNodes::newSUnit(), patchMatchingInput(), PerformABSCombine(), PerformADDCombineWithOperands(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PerformExtendCombine(), performExtendCombine(), PerformLOADCombine(), performORCombine(), PerformORCombine(), performSelectCombine(), PerformShiftCombine(), PerformSTORECombine(), performTBISimplification(), PerformVECTOR_SHUFFLECombine(), PerformXORCombine(), PrepareCall(), PromoteMaskArithmetic(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), scalarizeExtractedBinop(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), shouldTransformMulToShiftsAddsSubs(), llvm::TargetLowering::ShrinkDemandedOp(), simplifyI24(), VerifyDAGDiverence(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), and XFormVExtractWithShuffleIntoLoad().
getTargetMemSDNode()
template<class TargetMemSDNode > SDValue llvm::SelectionDAG::getTargetMemSDNode (SDVTList VTs, ArrayRef< SDValue > Ops, const SDLoc & dl, EVT MemVT, MachineMemOperand * MMO)
Return (create a new or find existing) a target-specific node.
TargetMemSDNode should be derived class from MemSDNode.
Compose node ID and try to find an existing node.
Existing node was not found. Create a new one.
Definition at line 1750 of file SelectionDAG.h.
Referenced by EmitMaskedTruncSStore(), EmitTruncSStore(), getAVX2GatherNode(), getGatherNode(), getScatterNode(), LowerMGATHER(), LowerMSCATTER(), and llvm::X86TargetLowering::ReplaceNodeResults().
getTokenFactor()
SDValue SelectionDAG::getTokenFactor (const SDLoc & DL, SmallVectorImpl< SDValue > & Vals)
Creates a new TokenFactor containing Vals.
If Vals contains 64k values or more, move values into new TokenFactors in 64k-1 blocks, until the final TokenFactor has less than 64k operands.
Definition at line 9537 of file SelectionDAG.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SDNode::getMaxNumOperands(), getNode(), llvm::MVT::Other, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::slice(), and llvm::ISD::TokenFactor.
Referenced by llvm::SelectionDAGBuilder::getRoot(), and llvm::SITargetLowering::LowerCall().
getTruncStore() [1/2]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand * MMO)
Definition at line 6893 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStore(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::MVT::Other, llvm::ISD::STORE, and llvm::ISD::UNINDEXED.
getTruncStore() [2/2]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment = 0, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 6871 of file SelectionDAG.cpp.
References assert(), getEVTAlignment(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::EVT::getStoreSize(), getTruncStore(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, and llvm::MachinePointerInfo::V.
Referenced by chainLoadsAndStoresForMemcpy(), combineStore(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getAddressForMemoryInput(), getMemcpyLoadsAndStores(), getTruncStore(), LowerINTRINSIC_W_CHAIN(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic().
getUNDEF()
SDValue llvm::SelectionDAG::getUNDEF (EVT VT) inline
Return an UNDEF node. UNDEF does not have a useful SDLoc.
Definition at line 878 of file SelectionDAG.h.
References getNode(), and llvm::ISD::UNDEF.
Referenced by addShuffleForVecExtend(), buildFromShuffleMostly(), buildMergeScalars(), buildScalarToVector(), CollectOpsToWiden(), combineBasicSADPattern(), combineBitcast(), combineBitcastvxi1(), combineBVOfConsecutiveLoads(), combineConcatVectorOfExtracts(), combineConcatVectorOps(), combineExtractVectorElt(), combineExtractWithShuffle(), combineInsertSubvector(), combineMaskedLoad(), combineMaskedLoadConstantMask(), combineMaskedStore(), combineSelect(), combineSetCCAtomicArith(), combineShuffleOfConcatUndef(), combineShuffleOfScalars(), combineStore(), combineTargetShuffle(), combineToExtendVectorInReg(), combineVectorPack(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CompactSwizzlableVector(), concatSubVectors(), constructRetValue(), convertLocVTToValVT(), convertShiftLeftToScale(), createMMXBuildVector(), EltsFromConsecutiveLoads(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), EmitTruncSStore(), ExpandBVWithShuffles(), ExpandHorizontalBinOp(), expandV4F32ToV2F64(), ExtendToType(), ExtractBitFromMaskVector(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), foldConstantFPMath(), FoldConstantVectorArithmetic(), FoldSetCC(), getBuildDwordsVector(), getConstVector(), getCopyFromPartsVector(), getExtLoad(), getFauxShuffleMask(), getGeneralPermuteNode(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLoad(), getNode(), getShuffleHalfVectors(), getShuffleScalarElt(), getShuffleVectorZeroOrUndef(), getSplatSourceVector(), getStore(), getTargetVShiftNode(), getTruncStore(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorShuffle(), insert1BitVector(), isAddSubOrSubAdd(), isFNEG(), isHopBuildVector(), isHorizontalBinOpPart(), joinDwords(), LowerAsSplatVectorLoad(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorv4x32(), LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), lowerFCMPIntrinsic(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), LowerFP_EXTEND(), lowerICMPIntrinsic(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), LowerMSCATTER(), LowerMUL(), LowerMULH(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndBlend(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithPSHUFB(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerTruncateVectorStore(), lowerUINT_TO_FP_v2i32(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVectorShuffle(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsInsertPS(), matchVectorShuffleWithUNPCK(), NormalizeBuildVector(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), llvm::R600TargetLowering::PerformDAGCombine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceVMULWidth(), ReplaceBITCASTResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), simplifyShift(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryBuildVectorShuffle(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), vectorizeExtractedCast(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), widenVectorToPartType(), and XFormVExtractWithShuffleIntoLoad().
getVAArg()
SDValue SelectionDAG::getVAArg (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
Definition at line 7180 of file SelectionDAG.cpp.
References getNode(), getTargetConstant(), getVTList(), llvm::MVT::i32, llvm::MVT::Other, and llvm::ISD::VAARG.
getValueType()
SDValue SelectionDAG::getValueType (EVT VT)
Definition at line 1507 of file SelectionDAG.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::EVT::isSimple(), N, and llvm::MVT::SimpleTy.
Referenced by combineShiftRightArithmetic(), combineVectorTruncationWithPACKSS(), convertLocVTToValVT(), emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), getAArch64Cmp(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), getNode(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerMSACopyIntr(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::MSP430TargetLowering::LowerShifts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PromoteMaskArithmetic(), llvm::X86TargetLowering::ReplaceNodeResults(), UnpackFromArgumentSlot(), and UnrollVectorOp().
getVectorShuffle()
SDValue SelectionDAG::getVectorShuffle (EVT VT, const SDLoc & dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
The number of elements in VT, which must be a vector type, must match the number of mask elements NumElts. An integer mask element equal to -1 is treated as undefined.
Definition at line 1569 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::all_of(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), assert(), llvm::ISD::BITCAST, C, commuteShuffle(), llvm::copy(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), getSplatBuildVector(), llvm::BuildVectorSDNode::getSplatValue(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::TargetLoweringBase::hasVectorBlend(), llvm::SDValue::isUndef(), N, NewSDValueDbgMsg(), llvm::BitVector::none(), and llvm::ISD::VECTOR_SHUFFLE.
Referenced by addShuffleForVecExtend(), buildFromShuffleMostly(), BuildVSLDOI(), combineBasicSADPattern(), combineBVOfConsecutiveLoads(), combineConcatVectorOfExtracts(), combineHorizontalMinMaxResult(), combineInsertSubvector(), combineMaskedLoad(), combineMaskedStore(), combineSelect(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleOfSplatVal(), combineStore(), combineToExtendBoolVectorInReg(), convertShiftLeftToScale(), createVariablePermute(), EltsFromConsecutiveLoads(), ExpandBVWithShuffles(), expandV4F32ToV2F64(), foldShuffleOfConcatUndefs(), GeneratePerfectShuffle(), getCommutedVectorShuffle(), getMOVL(), getShuffleHalfVectors(), getShuffleVectorZeroOrUndef(), getUnpackh(), getUnpackl(), isFNEG(), lower1BitShuffle(), lower256BitShuffle(), LowerAsSplatVectorLoad(), LowerBuildVectorv4x32(), LowerEXTEND_VECTOR_INREG(), LowerLoad(), LowerMUL(), LowerMULH(), LowerRotate(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndBlend(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleOfExtractsAsVperm(), LowerSIGN_EXTEND(), LowerUINT_TO_FP_i64(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerVectorShuffle(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), partitionShuffleOfConcats(), performConcatVectorsCombine(), performSelectCombine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceBuildVecToShuffleWithZero(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedVectorElts(), splitAndLowerShuffle(), truncateVectorWithPACK(), vectorizeExtractedCast(), and XFormVExtractWithShuffleIntoLoad().
getVRegDbgValue()
SDDbgValue * SelectionDAG::getVRegDbgValue (DIVariable * Var, DIExpression * Expr, unsigned VReg, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a VReg SDDbgValue node.
VReg.
Definition at line 8004 of file SelectionDAG.cpp.
References assert(), llvm::SDDbgInfo::getAlloc(), and llvm::SDDbgValue::VREG.
Referenced by llvm::SelectionDAGBuilder::handleDebugValue().
getVTList() [1/5]
SDVTList SelectionDAG::getVTList (ArrayRef< EVT > VTs)
Definition at line 7422 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::copy(), and llvm::ArrayRef< T >::size().
getVTList() [2/5]
SDVTList SelectionDAG::getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
Definition at line 7358 of file SelectionDAG.cpp.
References makeVTList().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), CloneNodeWithValues(), combineADC(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), CombineBaseUpdate(), combineCMP(), combineCVTP2I_CVTTP2I(), combineParity(), combineSBB(), combineShuffle(), CombineVLDDUP(), combineX86AddSub(), combineX86INT_TO_FP(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), createLoadLR(), createStoreLR(), EltsFromConsecutiveLoads(), emitCLC(), emitComparison(), emitIntrinsicWithCCAndChain(), EmitMaskedTruncSStore(), emitRepmovs(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), EmitTest(), EmitTruncSStore(), EmitUnrolledSetTag(), Expand64BitShift(), llvm::TargetLowering::expandAddSubSat(), ExpandBITCAST(), llvm::TargetLowering::expandFixedPointMul(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), ExpandREAD_REGISTER(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), GeneratePerfectShuffle(), getAArch64XALUOOp(), llvm::MipsTargetLowering::getAddrGPRel(), getAddrSpaceCast(), getAtomic(), getAVX2GatherNode(), getBasicBlock(), getBlockAddress(), getBoundedStrlen(), getCALLSEQ_END(), getCALLSEQ_START(), getConstant(), getConstantFP(), getConstantPool(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToReg(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFPBinOp(), getFPTernOp(), getFrameIndex(), getGatherNode(), getGlobalAddress(), getIndexedStore(), getJumpTable(), getLabelNode(), getLifetimeNode(), getLoad(), getMachineNode(), getMad64_32(), getMaskedLoad(), getMaskedStore(), getMDNode(), getMergeValues(), getMul24(), getNode(), getRegister(), getRegisterMask(), getScatterNode(), getSrcValue(), getStore(), getTargetIndex(), GetTLSADDR(), getTOCEntry(), getTruncStore(), getVAArg(), getVectorShuffle(), getX86XALUOOp(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSUBCARRY(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerATOMIC_STORE(), lowerAtomicArithWithLOCK(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCMP_SWAP(), LowerCTLZ(), LowerCTTZ(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerFSINCOS(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerStore(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerVECTOR_SHUFFLE(), LowerXALUO(), mutateStrictFPToFP(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCONDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performIntegerAbsCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformSETCCCombine(), PerformUMLALCombine(), PerformVDUPCombine(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), SelectNodeTo(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getVTList() [3/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2)
Definition at line 7362 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [4/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3)
Definition at line 7380 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [5/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
Definition at line 7400 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), and llvm::EVT::getRawBits().
getZeroExtendInReg()
SDValue SelectionDAG::getZeroExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
Definition at line 1132 of file SelectionDAG.cpp.
References llvm::ISD::AND, assert(), getConstant(), llvm::APInt::getLowBitsSet(), getNode(), llvm::EVT::getSizeInBits(), and llvm::EVT::isVector().
Referenced by combineExtSetcc(), getPtrExtendInReg(), llvm::MSP430TargetLowering::LowerShifts(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PromoteMaskArithmetic(), and llvm::TargetLowering::SimplifyDemandedBits().
getZExtOrTrunc()
SDValue SelectionDAG::getZExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
Definition at line 1117 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), getNode(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAndLoadToBZHI(), combineBitcast(), combineBitcastvxi1(), combineCompareEqual(), combineExtractWithShuffle(), combineHorizontalPredicateResult(), combineSelect(), combineShuffleOfScalars(), combineSubToSubus(), createVariablePermute(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), llvm::TargetLowering::expandFP_TO_SINT(), foldAddSubBoolOfMaskedVal(), foldCONCAT_VECTORS(), getPtrExtOrTrunc(), getShiftAmountOperand(), llvm::TargetLowering::getVectorElementPointer(), llvm::TargetLowering::IncrementMemoryAddress(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerBITCAST(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), lowerFCMPIntrinsic(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), lowerICMPIntrinsic(), LowerINTRINSIC_W_CHAIN(), LowerMULH(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerShift(), lowerX86CmpEqZeroToCtlzSrl(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and llvm::SelectionDAGBuilder::visitJumpTableHeader().
hasDebugValues()
bool llvm::SelectionDAG::hasDebugValues () const inline
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
Definition at line 1391 of file SelectionDAG.h.
References llvm::SDDbgInfo::empty().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
haveNoCommonBitsSet()
bool SelectionDAG::haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
As an example, this can allow an 'add' to be transformed into an 'or'.
Definition at line 4140 of file SelectionDAG.cpp.
References A, assert(), B, and computeKnownBits().
Referenced by detectAVGPattern().
InferPtrAlignment()
unsigned SelectionDAG::InferPtrAlignment (SDValue Ptr) const
Infer alignment of a load / store address.
InferPtrAlignment - Infer alignment of a load / store address.
Return 0 if it cannot be inferred.
Definition at line 9210 of file SelectionDAG.cpp.
References llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), llvm::SDValue::getConstantOperandVal(), getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::DataLayout::getIndexTypeSizeInBits(), getMachineFunction(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::SDValue::getOperand(), llvm::GlobalValue::getType(), isBaseWithConstantOffset(), llvm::TargetLowering::isGAPlusOffset(), and llvm::MinAlign().
Referenced by llvm::TargetLowering::computeKnownBitsForFrameIndex(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and LowerAsSplatVectorLoad().
init()
void SelectionDAG::init (MachineFunction & NewMF, OptimizationRemarkEmitter & NewORE, Pass * PassPtr, const TargetLibraryInfo * LibraryInfo, LegacyDivergenceAnalysis * Divergence)
Prepare this SelectionDAG to process code in the given MachineFunction.
Definition at line 1006 of file SelectionDAG.cpp.
References llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getSelectionDAGInfo(), getSubtarget(), and llvm::TargetSubtargetInfo::getTargetLowering().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
isBaseWithConstantOffset()
bool SelectionDAG::isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
This handles the equivalence: X|Cst == X+Cst iff X&Cst = 0.
Definition at line 3963 of file SelectionDAG.cpp.
References llvm::ISD::ADD, MaskedValueIsZero(), and llvm::ISD::OR.
Referenced by getBaseWithConstantOffset(), InferPtrAlignment(), LowerAsSplatVectorLoad(), replaceZeroVectorStore(), llvm::AVRDAGToDAGISel::SelectAddr(), and llvm::AMDGPUTargetLowering::SelectFlatOffset().
isConstantFPBuildVectorOrConstantFP()
SDNode * SelectionDAG::isConstantFPBuildVectorOrConstantFP (SDValue N)
Test whether the given value is a constant FP or similar node.
Definition at line 9505 of file SelectionDAG.cpp.
References llvm::ISD::isBuildVectorOfConstantFPSDNodes(), and N.
Referenced by isConstantValueOfAnyType().
isConstantIntBuildVectorOrConstantInt()
SDNode * SelectionDAG::isConstantIntBuildVectorOrConstantInt (SDValue N)
Test whether the given value is a constant int or similar node.
Definition at line 9491 of file SelectionDAG.cpp.
References llvm::ISD::GlobalAddress, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLowering::isOffsetFoldingLegal(), and N.
Referenced by combinePMULDQ(), isConstantValueOfAnyType(), salvageDebugInfo(), and stripConstantMask().
isConstantValueOfAnyType()
bool llvm::SelectionDAG::isConstantValueOfAnyType (SDValue N) inline
Returns
true if N is any kind of constant or build_vector of constants, int or float. If a vector, it may not necessarily be a splat.
Definition at line 1667 of file SelectionDAG.h.
References isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), and N.
Referenced by llvm::AMDGPUTargetLowering::performSelectCombine(), and simplifySelect().
isEqualTo()
bool SelectionDAG::isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
This is true if they are the same value, or if one is negative zero and the other positive zero.
Definition at line 4125 of file SelectionDAG.cpp.
References A, and B.
Referenced by combineSelect().
isKnownNeverNaN()
bool SelectionDAG::isKnownNeverNaN (SDValue Op, bool SNaN = false, unsigned Depth = 0) const
Test whether the given SDValue is known to never be NaN.
If SNaN is true, returns if Op is known to never be a signaling NaN (it may still be a qNaN).
Definition at line 3975 of file SelectionDAG.cpp.
References llvm::ISD::BUILTIN_OP_END, C, llvm::Depth, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getTarget(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isKnownNeverNaN(), llvm::TargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), llvm::ISD::SELECT, llvm::ISD::SINT_TO_FP, and llvm::ISD::UINT_TO_FP.
Referenced by combineFMinNumFMaxNum(), combineSelect(), isKnownNeverNaN(), llvm::AMDGPUTargetLowering::isKnownNeverNaNForTargetNode(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), and isLegalToCombineMinNumMaxNum().
isKnownNeverSNaN()
bool llvm::SelectionDAG::isKnownNeverSNaN (SDValue Op, unsigned Depth = 0) const inline
Returns
true if Op is known to never be a signaling NaN.
Definition at line 1553 of file SelectionDAG.h.
References llvm::Depth, and isKnownNeverNaN().
Referenced by llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::SITargetLowering::isCanonicalized(), and isKnownNeverNaN().
isKnownNeverZero()
bool SelectionDAG::isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
Definition at line 4103 of file SelectionDAG.cpp.
References assert(), C, isKnownNeverZero(), llvm::ISD::matchUnaryPredicate(), and llvm::ISD::OR.
Referenced by isKnownNeverZero(), and LowerShift().
isKnownNeverZeroFloat()
bool SelectionDAG::isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
Definition at line 4092 of file SelectionDAG.cpp.
References assert(), and C.
Referenced by combineSelect().
isKnownToBeAPowerOfTwo()
bool SelectionDAG::isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
This differs from computeKnownBits in that it doesn't necessarily determine which bit is set.
Definition at line 3368 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::ISD::BUILD_VECTOR, C, computeKnownBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMinPopulation(), E, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::isConstOrConstSplat(), llvm::SDNode::ops(), llvm::ISD::SHL, and llvm::ISD::SRL.
isSplatValue() [1/2]
bool SelectionDAG::isSplatValue (SDValue V, bool AllowUndefs = false)
Test whether V has a splatted value.
Helper wrapper to main isSplatValue function.
Definition at line 2339 of file SelectionDAG.cpp.
References assert(), llvm::APInt::getAllOnesValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), isSplatValue(), and llvm::EVT::isVector().
isSplatValue() [2/2]
bool SelectionDAG::isSplatValue (SDValue V, const APInt & DemandedElts, APInt & UndefElts)
Test whether V has a splatted value for all the demanded elements.
isSplatValue - Return true if the vector V has the same value across all DemandedElts.
On success UndefElts will indicate the elements that have UNDEF values instead of the splat value, this is only guaranteed to be correct for DemandedElts.
NOTE: The function will return true for a demanded splat of UNDEF values.
Definition at line 2256 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::extractBits(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ConstantSDNode::getZExtValue(), Idx, isSplatValue(), llvm::EVT::isVector(), llvm::APInt::setBit(), llvm::APInt::shl(), llvm::ISD::SUB, llvm::APInt::ule(), llvm::ISD::VECTOR_SHUFFLE, and llvm::APInt::zextOrSelf().
Referenced by getSplatSourceVector(), isSplatValue(), and LowerRotate().
isUndef()
bool SelectionDAG::isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
Definition at line 4764 of file SelectionDAG.cpp.
References llvm::any_of(), assert(), llvm::SDValue::getNode(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::SDNode::op_values(), llvm::ISD::SDIV, llvm::ArrayRef< T >::size(), llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
Referenced by FoldConstantArithmetic(), FoldConstantVectorArithmetic(), and simplifyDivRem().
Legalize()
void SelectionDAG::Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
This is the entry point for the file.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 4538 of file LegalizeDAG.cpp.
References allnodes_begin(), allnodes_end(), AssignTopologicalOrder(), DeleteNode(), E, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::SDValue::getNode(), getNode(), getRoot(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, and RemoveDeadNodes().
LegalizeOp()
bool SelectionDAG::LegalizeOp (SDNode * N, SmallSetVector< SDNode *, 16 > & UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
Returns
true if N is a valid, legal node after calling this.
This essentially runs a single recursive walk of the Legalize process over the given node (and its operands). This can be used to incrementally legalize the DAG. All of the nodes which are directly replaced, potentially including N, are added to the output parameter UpdatedNodes so that the delta to the DAG can be understood by the caller.
When this returns false, N has been legalized in a way that make the pointer passed in no longer valid. It may have even been deleted from the DAG, and so it shouldn't be used further. When this returns true, the N passed in is a legal node, and can be immediately processed as such. This may still have done some work on the DAG, and will still populate UpdatedNodes with any new nodes replacing those originally in the DAG.
Definition at line 4587 of file LegalizeDAG.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImpl< PtrType >::insert(), and N.
LegalizeTypes()
bool SelectionDAG::LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
Returns "true" if it made any changes.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1114 of file LegalizeTypes.cpp.
References llvm::DAGTypeLegalizer::run().
LegalizeVectors()
bool SelectionDAG::LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
This is necessary as a separate step from Legalize because unrolling a vector operation can introduce illegal types, which requires running LegalizeTypes again.
This returns true if it made any changes; in that case, LegalizeTypes is called again before Legalize.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1418 of file LegalizeVectorOps.cpp.
makeEquivalentMemoryOrdering()
SDValue SelectionDAG::makeEquivalentMemoryOrdering (LoadSDNode * Old, SDValue New)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 8614 of file SelectionDAG.cpp.
References assert(), llvm::SDValue::getNode(), getNode(), llvm::SDNode::hasAnyUseOfValue(), llvm::MVT::Other, ReplaceAllUsesOfValueWith(), llvm::ISD::TokenFactor, and UpdateNodeOperands().
Referenced by combineStore(), EltsFromConsecutiveLoads(), lowerShuffleAsBroadcast(), and narrowExtractedVectorLoad().
MaskedValueIsAllOnes()
bool SelectionDAG::MaskedValueIsAllOnes (SDValue Op, const APInt & Mask, unsigned Depth = 0) const
Return true if '(Op & Mask) == Mask'.
MaskedValueIsAllOnes - Return true if '(Op & Mask) == Mask'.
Op and Mask are known to be the same type.
Definition at line 2249 of file SelectionDAG.cpp.
References computeKnownBits(), and llvm::Depth.
MaskedValueIsZero() [1/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2242 of file SelectionDAG.cpp.
References computeKnownBits(), and llvm::Depth.
MaskedValueIsZero() [2/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2230 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnesValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isVector(), and MaskedValueIsZero().
Referenced by llvm::SelectionDAGISel::CheckAndMask(), combineAnd(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineVectorPack(), combineZext(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMUL_LOHI(), GetDemandedBits(), getFauxShuffleMask(), isBaseWithConstantOffset(), isTruncWithZeroHighBitsInput(), LowerAndToBT(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), MaskedValueIsZero(), matchLSNode(), matchVectorShuffleWithPACK(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformORCombineToBFI(), PerformShiftCombine(), performSRLCombine(), ShrinkLoadReplaceStoreWithStore(), SignBitIsZero(), and llvm::TargetLowering::SimplifySetCC().
matchBinOpReduction()
SDValue SelectionDAG::matchBinOpReduction (SDNode * Extract, ISD::NodeType & BinOp, ArrayRef< ISD::NodeType > CandidateBinOps)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
The reduction must use one of the opcodes listed in /p CandidateBinOps and on success /p BinOp will contain the matching opcode. Returns the vector that is being reduced on, or SDValue() if a reduction was not matched.
Definition at line 9008 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::isNullConstant(), llvm::Log2_32(), and llvm::none_of().
Referenced by combineBasicSADPattern(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), and combineReductionToHorizontal().
MorphNodeTo()
SDNode * SelectionDAG::MorphNodeTo (SDNode * N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
MorphNodeTo - This mutates the specified node to have the specified return type, opcode, and operands.
Note that MorphNodeTo returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one. Note that the SDLoc need not be the same.
Using MorphNodeTo is faster than creating a new node and swapping it in with ReplaceAllUsesWith both because it often avoids allocating a new node, and because it doesn't require CSE recalculation for any of the node's users.
However, note that MorphNodeTo recursively deletes dead nodes from the DAG. As a consequence it isn't appropriate to use from within the DAG combiner or the legalizer which maintain worklists that would need to be updated when deleting things.
Definition at line 7695 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SmallPtrSetImplBase::empty(), llvm::MVT::Glue, I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::SDVTList::NumVTs, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNodes(), llvm::Use::set(), llvm::SDNode::use_empty(), and llvm::SDVTList::VTs.
Referenced by CloneNodeWithValues(), mutateStrictFPToFP(), SelectNodeTo(), and llvm::HexagonDAGToDAGISel::SelectTypecast().
mutateStrictFPToFP()
SDNode * SelectionDAG::mutateStrictFPToFP (SDNode * Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
The node must be a strict FP node.
Definition at line 7748 of file SelectionDAG.cpp.
References assert(), llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getVTList(), llvm_unreachable, MorphNodeTo(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNode(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::SDNode::setNodeId(), llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FCOS, llvm::ISD::STRICT_FDIV, llvm::ISD::STRICT_FEXP, llvm::ISD::STRICT_FEXP2, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FLOG, llvm::ISD::STRICT_FLOG10, llvm::ISD::STRICT_FLOG2, llvm::ISD::STRICT_FMA, llvm::ISD::STRICT_FMAXNUM, llvm::ISD::STRICT_FMINNUM, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FPOW, llvm::ISD::STRICT_FPOWI, llvm::ISD::STRICT_FREM, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FROUND, llvm::ISD::STRICT_FSIN, llvm::ISD::STRICT_FSQRT, llvm::ISD::STRICT_FSUB, and llvm::ISD::STRICT_FTRUNC.
operator=()
SelectionDAG & llvm::SelectionDAG::operator= (const SelectionDAG &) delete
RemoveDeadNode()
void SelectionDAG::RemoveDeadNode (SDNode * N)
Remove the specified node from the system.
If any of its operands then becomes dead, remove them as well. Inform UpdateListener for each node deleted.
Definition at line 731 of file SelectionDAG.cpp.
References getRoot(), N, and RemoveDeadNodes().
Referenced by foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::SITargetLowering::legalizeTargetIndependentNode(), mutateStrictFPToFP(), llvm::SelectionDAGISel::ReplaceNode(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), SelectNodeTo(), llvm::HvxSelector::selectVAlign(), and llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic().
RemoveDeadNodes() [1/2]
void SelectionDAG::RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
RemoveDeadNodes - This method deletes all unreachable nodes in the SelectionDAG.
Definition at line 677 of file SelectionDAG.cpp.
References allnodes(), getRoot(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNodes(), and setRoot().
Referenced by Legalize(), MorphNodeTo(), RemoveDeadNode(), RemoveDeadNodes(), and llvm::DAGTypeLegalizer::run().
RemoveDeadNodes() [2/2]
void SelectionDAG::RemoveDeadNodes (SmallVectorImpl< SDNode * > & DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
RemoveDeadNodes - This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
Definition at line 697 of file SelectionDAG.cpp.
References llvm::ISD::DELETED_NODE, E, llvm::SmallVectorBase::empty(), I, N, llvm::SelectionDAG::DAGUpdateListener::Next, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Use::set(), and llvm::SDNode::use_empty().
ReplaceAllUsesOfValuesWith()
void SelectionDAG::ReplaceAllUsesOfValuesWith (const SDValue * From, const SDValue * To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
ReplaceAllUsesOfValuesWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
This correctly handles the case where there is an overlap between the From values and the To values.
The same value may appear in both the From and To list. The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 8454 of file SelectionDAG.cpp.
References E, From, ReplaceAllUsesOfValueWith(), llvm::Use::set(), llvm::sort(), transferDbgValues(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and Uses.
Referenced by llvm::SelectionDAGISel::ReplaceUses().
ReplaceAllUsesOfValueWith()
void SelectionDAG::ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
ReplaceAllUsesOfValueWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 8307 of file SelectionDAG.cpp.
References From, getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), adjustSubwordCmp(), combineCVTP2I_CVTTP2I(), combineExtInVec(), combineSetCCAtomicArith(), combineShuffle(), combineSIntToFP(), combineVSelectToBLENDV(), combineX86INT_TO_FP(), emitIntrinsicWithCCAndChain(), EmitTest(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), makeEquivalentMemoryOrdering(), mutateStrictFPToFP(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), PerformHWLoopCombine(), performIntToFpCombine(), PerformORCombineToSMULWBT(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformVDUPCombine(), PerformVMOVRRDCombine(), ReplaceAllUsesOfValuesWith(), llvm::SelectionDAGISel::ReplaceUses(), SkipExtensionForVMULL(), tryToFoldExtOfExtload(), and tryToFoldExtOfLoad().
ReplaceAllUsesWith() [1/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, const SDValue * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version can replace From with any result values. To must match the number and types of values returned by From.
Definition at line 8260 of file SelectionDAG.cpp.
References From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [2/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, SDNode * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version assumes that for each value of From, there is a corresponding value in To in the same position with the same type.
Definition at line 8204 of file SelectionDAG.cpp.
References assert(), From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::getValueType(), llvm::SDNode::isDivergent(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [3/3]
void SelectionDAG::ReplaceAllUsesWith (SDValue FromN, SDValue To)
Modify anything using 'From' to use 'To' instead.
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG. Use the first version if 'From' is known to have a single result, use the second if you have two nodes with identical results (or if 'To' has a superset of the results of 'From'), use the third otherwise.
These methods all take an optional UpdateListener, which (if not null) is informed about nodes that are deleted and modified due to recursive changes in the dag.
These functions only replace all existing uses. It's possible that as these replacements are being performed, CSE may cause the From node to be given new uses. These new uses of From are left in place, and not automatically transferred to To.
This can cause recursive merging of nodes in the DAG.
This version assumes From has a single result value.
Definition at line 8153 of file SelectionDAG.cpp.
References assert(), From, llvm::SDValue::getNode(), llvm::SDValue::getResNo(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by ExpandBITCAST(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), mutateStrictFPToFP(), PerformBFICombine(), performCONDCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::SelectionDAGISel::ReplaceNode(), llvm::SelectionDAGISel::ReplaceUses(), and SelectNodeTo().
RepositionNode()
void llvm::SelectionDAG::RepositionNode (allnodes_iterator Position, SDNode * N) inline
Move node N in the AllNodes list to be immediately before the given iterator Position.
This may be used to update the topological ordering when the list of nodes is modified.
Definition at line 1358 of file SelectionDAG.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), N, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by insertDAGNode().
salvageDebugInfo()
void SelectionDAG::salvageDebugInfo (SDNode & N)
To be invoked on an SDNode that is slated to be erased.
This function mirrors llvm::salvageDebugInfo.
Definition at line 8074 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddDbgValue(), llvm::dbgs(), getDbgValue(), GetDbgValues(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), isConstantIntBuildVectorOrConstantInt(), LLVM_DEBUG, N, llvm::DIExpression::prepend(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::DIExpression::StackValue.
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
SelectNodeTo() [1/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SelectNodeTo - These are wrappers around MorphNodeTo that accept a machine opcode.
Note that target opcodes are stored as ~TargetOpcode in the node opcode field. The resultant node is returned.
Definition at line 7588 of file SelectionDAG.cpp.
References getVTList(), N, llvm::None, and SelectNodeTo().
Referenced by SelectNodeTo(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
SelectNodeTo() [2/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 7617 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [3/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1)
Definition at line 7594 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [4/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 7601 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [5/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7609 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [6/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2)
Definition at line 7629 of file SelectionDAG.cpp.
References getVTList(), N, llvm::None, and SelectNodeTo().
SelectNodeTo() [7/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 7623 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [8/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 7635 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [9/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 7642 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [10/11]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 7650 of file SelectionDAG.cpp.
References MorphNodeTo(), N, RemoveDeadNode(), and ReplaceAllUsesWith().
SelectNodeTo() [11/11]
SDNode * llvm::SelectionDAG::SelectNodeTo (SDNode * N, unsigned TargetOpc, EVT VT1, EVT VT2, SDValue Op1)
setFunctionLoweringInfo()
void llvm::SelectionDAG::setFunctionLoweringInfo (FunctionLoweringInfo * FuncInfo) inline
Definition at line 402 of file SelectionDAG.h.
setGraphAttrs()
void SelectionDAG::setGraphAttrs (const SDNode * N, const char * Attrs)
Set graph attributes for a node. (eg. "color=red".)
setGraphAttrs - Set graph attributes for a node.
(eg. "color=red".)
Definition at line 181 of file SelectionDAGPrinter.cpp.
References llvm::errs(), N, and NodeGraphAttrs.
setGraphColor()
void SelectionDAG::setGraphColor (const SDNode * N, const char * Color)
Convenience for setting node color attribute.
setGraphColor - Convenience for setting node color attribute.
Definition at line 211 of file SelectionDAGPrinter.cpp.
References llvm::errs(), N, and NodeGraphAttrs.
setNodeMemRefs()
void SelectionDAG::setNodeMemRefs (MachineSDNode * N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
Definition at line 7564 of file SelectionDAG.cpp.
References llvm::copy(), llvm::ArrayRef< T >::empty(), N, and llvm::ArrayRef< T >::size().
Referenced by CloneNodeWithValues(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), getLoadStackGuard(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setRoot()
const SDValue & llvm::SelectionDAG::setRoot (SDValue N) inline
Set the current root tag of the SelectionDAG.
Definition at line 479 of file SelectionDAG.h.
References assert(), llvm::checkForCycles(), N, and llvm::MVT::Other.
Referenced by llvm::SelectionDAGBuilder::getControlRoot(), llvm::SelectionDAGBuilder::getRoot(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), lowerIncomingStatepointValue(), llvm::SelectionDAGBuilder::lowerInvokable(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and llvm::SelectionDAGBuilder::visitSwitchCase().
setSubgraphColor()
void SelectionDAG::setSubgraphColor (SDNode * N, const char * Color)
Convenience for setting subgraph color attribute.
setSubgraphColor - Convenience for setting subgraph color attribute.
Definition at line 255 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
SignBitIsZero()
bool SelectionDAG::SignBitIsZero (SDValue Op, unsigned Depth = 0) const
Return true if the sign bit of Op is known to be zero.
SignBitIsZero - Return true if the sign bit of Op is known to be zero.
We use this predicate to simplify operations downstream.
Definition at line 2222 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getSignMask(), and MaskedValueIsZero().
Referenced by canReduceVMulWidth(), combineGatherScatter(), combineUIntToFP(), getCmp(), and LowerVSETCC().
simplifyFPBinop()
SDValue SelectionDAG::simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
Definition at line 7156 of file SelectionDAG.cpp.
References llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, llvm::ConstantFPSDNode::getValueAPF(), llvm::isConstOrConstSplatFP(), llvm::APFloat::isExactlyValue(), llvm::APFloat::isNegZero(), llvm::APFloat::isPosZero(), X, and Y.
Referenced by getNode().
simplifySelect()
SDValue SelectionDAG::simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
Definition at line 7101 of file SelectionDAG.cpp.
References F, and isConstantValueOfAnyType().
Referenced by combineSelect(), and getNode().
simplifyShift()
SDValue SelectionDAG::simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
Definition at line 7131 of file SelectionDAG.cpp.
References getConstant(), getUNDEF(), llvm::isNullOrNullSplat(), llvm::ISD::matchUnaryPredicate(), X, and Y.
Referenced by getNode().
SplitVector() [1/2]
std::pair< SDValue, SDValue > llvm::SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL) inline
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 1635 of file SelectionDAG.h.
References GetSplitDestVTs(), N, and SplitVector().
SplitVector() [2/2]
std::pair< SDValue, SDValue > SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
SplitVector - Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 9263 of file SelectionDAG.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, getConstant(), getDataLayout(), getNode(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), and N.
Referenced by combineBitcastvxi1(), combineHorizontalPredicateResult(), llvm::TargetLowering::expandVecReduce(), getPMOVMSKB(), LowerBITCAST(), SplitVector(), and SplitVectorOperand().
SplitVectorOperand()
std::pair< SDValue, SDValue > llvm::SelectionDAG::SplitVectorOperand (const SDNode * N, unsigned OpNo) inline
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 1643 of file SelectionDAG.h.
References N, and SplitVector().
Referenced by llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), and SplitVSETCC().
transferDbgValues()
void SelectionDAG::transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits = 0, unsigned SizeInBits = 0, bool InvalidateDbg = true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
If InvalidateDbg is set, debug values are invalidated after they are transferred.
Definition at line 8014 of file SelectionDAG.cpp.
References AddDbgValue(), assert(), llvm::DIExpression::createFragmentExpression(), From, getDbgValue(), GetDbgValues(), llvm::SDNode::getHasDebugValue(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SDDbgValue::SDNODE.
Referenced by getNode(), ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), and ReplaceAllUsesWith().
UnrollVectorOp()
SDValue SelectionDAG::UnrollVectorOp (SDNode * N, unsigned ResNE = 0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
If the ResNE is 0, fully unroll the vector op. If ResNE is less than the width of the vector op, unroll up to ResNE. If the ResNE is greater than the width of the vector op, unroll the vector op and fill the end of the resulting vector with UNDEFS.
Definition at line 9065 of file SelectionDAG.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FP_ROUND_INREG, getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), getShiftAmountOperand(), getUNDEF(), llvm::SDValue::getValueType(), getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::EVT::isVector(), N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::VSELECT.
Referenced by LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), llvm::X86TargetLowering::ReplaceNodeResults(), and unrollVectorShift().
UnrollVectorOverflowOp()
std::pair< SDValue, SDValue > SelectionDAG::UnrollVectorOverflowOp (SDNode * N, unsigned ResNE = 0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
This is a separate function because those opcodes have two results.
Definition at line 9135 of file SelectionDAG.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), ExtractVectorElements(), getBoolConstant(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), getSelect(), llvm::TargetLoweringBase::getSetCCResultType(), getUNDEF(), llvm::SDValue::getValue(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SADDO, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::ISD::UADDO, llvm::ISD::UMULO, and llvm::ISD::USUBO.
updateDivergence()
void SelectionDAG::updateDivergence (SDNode * N)
Definition at line 8386 of file SelectionDAG.cpp.
References llvm::TargetLowering::isSDNodeAlwaysUniform(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, llvm::MVT::Other, and updateDivergence().
Referenced by ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), updateDivergence(), and UpdateNodeOperands().
UpdateNodeOperands() [1/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, ArrayRef< SDValue > Ops)
Definition at line 7522 of file SelectionDAG.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), N, llvm::ArrayRef< T >::size(), and updateDivergence().
UpdateNodeOperands() [2/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
UpdateNodeOperands - Mutate the specified node in-place to have the specified operands.
If the resultant node already exists in the DAG, this does not modify the specified node, instead it returns the node that already exists. If the resultant node does not exist in the DAG, the input node is returned. As a degenerate case, if you specify the same input operands as the node already has, the input node is returned.
Definition at line 7448 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
Referenced by combineGatherScatter(), llvm::SITargetLowering::legalizeTargetIndependentNode(), makeEquivalentMemoryOrdering(), moveBelowOrigChain(), llvm::PPCTargetLowering::PerformDAGCombine(), and UpdateNodeOperands().
UpdateNodeOperands() [3/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2)
Definition at line 7473 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
UpdateNodeOperands() [4/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7502 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [5/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
Definition at line 7508 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [6/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
Definition at line 7515 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
VerifyDAGDiverence()
void SelectionDAG::VerifyDAGDiverence ()
Definition at line 8423 of file SelectionDAG.cpp.
References allnodes(), assert(), getTargetLoweringInfo(), llvm::TargetLowering::isSDNodeAlwaysUniform(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, and llvm::MVT::Other.
viewGraph() [1/2]
void SelectionDAG::viewGraph ()
Definition at line 163 of file SelectionDAGPrinter.cpp.
References viewGraph().
Referenced by viewGraph().
viewGraph() [2/2]
void SelectionDAG::viewGraph (const std::string & Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
Definition at line 150 of file SelectionDAGPrinter.cpp.
References llvm::errs(), getMachineFunction(), getName(), and ViewGraph().
WidenVector()
SDValue SelectionDAG::WidenVector (const SDValue & N, const SDLoc & DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
Definition at line 9278 of file SelectionDAG.cpp.
References getConstant(), getContext(), getDataLayout(), getNode(), getUNDEF(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ISD::INSERT_SUBVECTOR, N, and llvm::NextPowerOf2().
Friends And Related Function Documentation
DAGUpdateListener
friend struct DAGUpdateListener friend
DAGUpdateListener is a friend so it can manipulate the listener stack.
Definition at line 337 of file SelectionDAG.h.
Member Data Documentation
NewNodesMustHaveLegalTypes
bool llvm::SelectionDAG::NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
This is important after type legalization since any illegally typed nodes generated after this point will not experience type legalization.
Definition at line 333 of file SelectionDAG.h.
Referenced by FoldConstantArithmetic(), FoldConstantVectorArithmetic(), and getConstant().
NodeGraphAttrs
std::map<const SDNode *, std::string> llvm::SelectionDAG::NodeGraphAttrs
Definition at line 428 of file SelectionDAG.h.
Referenced by clearGraphAttrs(), getGraphAttrs(), setGraphAttrs(), and setGraphColor().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/DAGCombiner.cpp
lib/CodeGen/SelectionDAG/LegalizeDAG.cpp
lib/CodeGen/SelectionDAG/LegalizeTypes.cpp
lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp
lib/CodeGen/SelectionDAG/SelectionDAG.cpp
lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp
lib/CodeGen/SelectionDAG/SelectionDAGPrinter.cpp