LLVM: StringView Class Reference
StringView Class Reference
#include "llvm/Demangle/StringView.h"
Public Member Functions
template<size_t N>
StringView (const char(&Str)[N])
StringView (const char *First_, const char *Last_)
StringView (const char *First_, size_t Len)
StringView (const char *Str)
StringView ()
StringView substr (size_t From) const
size_t find (char C, size_t From=0) const
StringView substr (size_t From, size_t To) const
StringView dropFront (size_t N=1) const
StringView dropBack (size_t N=1) const
char front () const
char back () const
char popFront ()
bool consumeFront (char C)
bool consumeFront (StringView S)
bool startsWith (char C) const
bool startsWith (StringView Str) const
const char & operator[] (size_t Idx) const
const char * begin () const
const char * end () const
size_t size () const
bool empty () const
Static Public Attributes
static const size_t npos = ~size_t(0)
Detailed Description
Definition at line 23 of file StringView.h.
Constructor & Destructor Documentation
StringView() [1/5]
template<size_t N> StringView::StringView (const char(&) Str[N]) inline
Definition at line 31 of file StringView.h.
StringView() [2/5]
StringView::StringView (const char * First_, const char * Last_) inline
Definition at line 32 of file StringView.h.
StringView() [3/5]
StringView::StringView (const char * First_, size_t Len) inline
Definition at line 34 of file StringView.h.
StringView() [4/5]
StringView::StringView (const char * Str) inline
Definition at line 36 of file StringView.h.
StringView() [5/5]
StringView::StringView () inline
Definition at line 37 of file StringView.h.
Referenced by dropBack(), dropFront(), and substr().
Member Function Documentation
back()
char StringView::back () const inline
Definition at line 79 of file StringView.h.
References assert(), empty(), and end().
Referenced by startsWithLocalScopePattern().
begin()
const char * StringView::begin () const inline
Definition at line 113 of file StringView.h.
Referenced by llvm::ItaniumManglingCanonicalizer::addEquivalence(), front(), NodeOrString::NodeOrString(), operator==(), operator[](), AbstractManglingParser< Derived, Alloc >::parseQualifiedType(), FloatLiteralImpl< Float >::printLeft(), startsWith(), and substr().
consumeFront() [1/2]
bool StringView::consumeFront (char C) inline
Definition at line 89 of file StringView.h.
References C, dropFront(), and startsWith().
Referenced by consumeSpecialIntrinsicKind(), demangleFunctionRefQualifier(), demanglePointerCVQualifiers(), isMemberPointer(), and startsWithLocalScopePattern().
consumeFront() [2/2]
bool StringView::consumeFront (StringView S) inline
Definition at line 96 of file StringView.h.
References dropFront(), size(), and startsWith().
dropBack()
StringView StringView::dropBack (size_t N = 1) const inline
Definition at line 68 of file StringView.h.
References N, size(), and StringView().
Referenced by startsWithLocalScopePattern().
dropFront()
StringView StringView::dropFront (size_t N = 1) const inline
Definition at line 62 of file StringView.h.
References N, size(), and StringView().
Referenced by consumeFront(), AbstractManglingParser< Derived, Alloc >::parseQualifiedType(), and startsWithLocalScopePattern().
empty()
bool StringView::empty () const inline
Definition at line 116 of file StringView.h.
Referenced by back(), front(), isMemberPointer(), AbstractManglingParser< Derived, Alloc >::parseAbiTags(), AbstractManglingParser< Derived, Alloc >::parseClassEnumType(), AbstractManglingParser< Derived, Alloc >::parseIntegerLiteral(), AbstractManglingParser< Derived, Alloc >::parseQualifiedType(), AbstractManglingParser< Derived, Alloc >::parseType(), popFront(), startsWith(), startsWithDigit(), and startsWithLocalScopePattern().
end()
const char * StringView::end () const inline
Definition at line 114 of file StringView.h.
Referenced by llvm::ItaniumManglingCanonicalizer::addEquivalence(), back(), NodeOrString::NodeOrString(), operator==(), AbstractManglingParser< Derived, Alloc >::parseQualifiedType(), FloatLiteralImpl< Float >::printLeft(), and startsWith().
find()
size_t StringView::find (char C, size_t From = 0) const inline
Definition at line 43 of file StringView.h.
References C, From, npos, P, and size().
Referenced by startsWithLocalScopePattern().
front()
char StringView::front () const inline
Definition at line 74 of file StringView.h.
References assert(), begin(), and empty().
Referenced by isMemberPointer(), isPointerType(), isTagType(), and startsWithDigit().
operator[]()
const char & StringView::operator[] (size_t Idx) const inline
Definition at line 111 of file StringView.h.
References begin(), and Idx.
popFront()
char StringView::popFront () inline
Definition at line 84 of file StringView.h.
References assert(), and empty().
Referenced by demanglePointerCVQualifiers(), and isMemberPointer().
size()
size_t StringView::size () const inline
Definition at line 115 of file StringView.h.
Referenced by llvm::ItaniumManglingCanonicalizer::addEquivalence(), consumeFront(), AbstractManglingParser< Derived, Alloc >::consumeIf(), dropBack(), dropFront(), find(), operator==(), startsWith(), startsWithLocalScopePattern(), and substr().
startsWith() [1/2]
bool StringView::startsWith (char C) const inline
Definition at line 103 of file StringView.h.
References begin(), C, and empty().
Referenced by consumeFront(), isFunctionType(), isPointerType(), and AbstractManglingParser< Derived, Alloc >::parseQualifiedType().
startsWith() [2/2]
bool StringView::startsWith (StringView Str) const inline
Definition at line 105 of file StringView.h.
References begin(), end(), and size().
substr() [1/2]
StringView StringView::substr (size_t From) const inline
Definition at line 39 of file StringView.h.
References begin(), From, size(), and StringView().
Referenced by startsWithLocalScopePattern().
substr() [2/2]
StringView StringView::substr (size_t From, size_t To) const inline
Definition at line 54 of file StringView.h.
References From, size(), and StringView().
Member Data Documentation
npos
const size_t StringView::npos = ~size_t(0) static
Definition at line 28 of file StringView.h.
Referenced by find(), and startsWithLocalScopePattern().
The documentation for this class was generated from the following file:
include/llvm/Demangle/StringView.h