LLVM: llvm::RangeSpan Class Reference
llvm::RangeSpan Class Reference
#include "CodeGen/AsmPrinter/DwarfFile.h"
Public Member Functions
RangeSpan (MCSymbol *S, MCSymbol *E)
const MCSymbol * getStart () const
const MCSymbol * getEnd () const
void setEnd (const MCSymbol *E)
Detailed Description
Definition at line 35 of file DwarfFile.h.
Constructor & Destructor Documentation
RangeSpan()
llvm::RangeSpan::RangeSpan (MCSymbol * S, MCSymbol * E) inline
Definition at line 37 of file DwarfFile.h.
Member Function Documentation
getEnd()
const MCSymbol * llvm::RangeSpan::getEnd () const inline
Definition at line 39 of file DwarfFile.h.
Referenced by llvm::DwarfCompileUnit::addRange(), and llvm::DwarfCompileUnit::attachRangesOrLowHighPC().
getStart()
const MCSymbol * llvm::RangeSpan::getStart () const inline
Definition at line 38 of file DwarfFile.h.
Referenced by llvm::DwarfCompileUnit::addRange(), and llvm::DwarfCompileUnit::attachRangesOrLowHighPC().
setEnd()
void llvm::RangeSpan::setEnd (const MCSymbol * E) inline
Definition at line 40 of file DwarfFile.h.
References E.
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DwarfFile.h