LLVM: llvm::object::ELFFile< ELFT > Class Template Reference
llvm::object::ELFFile< ELFT > Class Template Reference
#include "llvm/Object/ELF.h"
Public Types
using uintX_t = typename ELFT::uint
using Elf_Ehdr = typename ELFT::Ehdr
using Elf_Shdr = typename ELFT::Shdr
using Elf_Sym = typename ELFT::Sym
using Elf_Dyn = typename ELFT::Dyn
using Elf_Phdr = typename ELFT::Phdr
using Elf_Rel = typename ELFT::Rel
using Elf_Rela = typename ELFT::Rela
using Elf_Relr = typename ELFT::Relr
using Elf_Verdef = typename ELFT::Verdef
using Elf_Verdaux = typename ELFT::Verdaux
using Elf_Verneed = typename ELFT::Verneed
using Elf_Vernaux = typename ELFT::Vernaux
using Elf_Versym = typename ELFT::Versym
using Elf_Hash = typename ELFT::Hash
using Elf_GnuHash = typename ELFT::GnuHash
using Elf_Nhdr = typename ELFT::Nhdr
using Elf_Note = typename ELFT::Note
using Elf_Note_Iterator = typename ELFT::NoteIterator
using Elf_Dyn_Range = typename ELFT::DynRange
using Elf_Shdr_Range = typename ELFT::ShdrRange
using Elf_Sym_Range = typename ELFT::SymRange
using Elf_Rel_Range = typename ELFT::RelRange
using Elf_Rela_Range = typename ELFT::RelaRange
using Elf_Relr_Range = typename ELFT::RelrRange
using Elf_Phdr_Range = typename ELFT::PhdrRange
Public Member Functions
const uint8_t * base () const
size_t getBufSize () const
const Elf_Ehdr * getHeader () const
template<typename T >
Expected< const T * > getEntry (uint32_t Section, uint32_t Entry) const
template<typename T >
Expected< const T * > getEntry (const Elf_Shdr *Section, uint32_t Entry) const
Expected< StringRef > getStringTable (const Elf_Shdr *Section) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
StringRef getRelocationTypeName (uint32_t Type) const
void getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > &Result) const
uint32_t getRelativeRelocationType () const
std::string getDynamicTagAsString (unsigned Arch, uint64_t Type) const
std::string getDynamicTagAsString (uint64_t Type) const
Expected< const Elf_Sym * > getRelocationSymbol (const Elf_Rel *Rel, const Elf_Shdr *SymTab) const
Get the symbol for a given relocation.
bool isMipsELF64 () const
bool isMips64EL () const
Expected< Elf_Shdr_Range > sections () const
Expected< Elf_Dyn_Range > dynamicEntries () const
Expected< const uint8_t * > toMappedAddr (uint64_t VAddr) const
Expected< Elf_Sym_Range > symbols (const Elf_Shdr *Sec) const
Expected< Elf_Rela_Range > relas (const Elf_Shdr *Sec) const
Expected< Elf_Rel_Range > rels (const Elf_Shdr *Sec) const
Expected< Elf_Relr_Range > relrs (const Elf_Shdr *Sec) const
Expected< std::vector< Elf_Rela > > decode_relrs (Elf_Relr_Range relrs) const
Expected< std::vector< Elf_Rela > > android_relas (const Elf_Shdr *Sec) const
Expected< Elf_Phdr_Range > program_headers () const
Iterate over program header table.
Elf_Note_Iterator notes_begin (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator over notes in a program header.
Elf_Note_Iterator notes_begin (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator over notes in a section.
Elf_Note_Iterator notes_end () const
Get the end iterator for notes.
iterator_range< Elf_Note_Iterator > notes (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator range over notes of a program header.
iterator_range< Elf_Note_Iterator > notes (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator range over notes of a section.
Expected< StringRef > getSectionStringTable (Elf_Shdr_Range Sections) const
Expected< uint32_t > getSectionIndex (const Elf_Sym *Sym, Elf_Sym_Range Syms, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym *Sym, const Elf_Shdr *SymTab, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym *Sym, Elf_Sym_Range Symtab, ArrayRef< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (uint32_t Index) const
Expected< const Elf_Shdr * > getSection (const StringRef SectionName) const
Expected< const Elf_Sym * > getSymbol (const Elf_Shdr *Sec, uint32_t Index) const
Expected< StringRef > getSectionName (const Elf_Shdr *Section) const
Expected< StringRef > getSectionName (const Elf_Shdr *Section, StringRef DotShstrtab) const
template<typename T >
Expected< ArrayRef< T > > getSectionContentsAsArray (const Elf_Shdr *Sec) const
Expected< ArrayRef< uint8_t > > getSectionContents (const Elf_Shdr *Sec) const
Static Public Member Functions
static Expected< ELFFile > create (StringRef Object)
Detailed Description
template<class ELFT>
class llvm::object::ELFFile< ELFT >
Definition at line 68 of file ELF.h.
Member Typedef Documentation
Elf_Dyn
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Dyn = typename ELFT::Dyn
Definition at line 75 of file ELF.h.
Elf_Dyn_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Dyn_Range = typename ELFT::DynRange
Definition at line 90 of file ELF.h.
Elf_Ehdr
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Ehdr = typename ELFT::Ehdr
Definition at line 72 of file ELF.h.
Elf_GnuHash
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_GnuHash = typename ELFT::GnuHash
Definition at line 86 of file ELF.h.
Elf_Hash
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Hash = typename ELFT::Hash
Definition at line 85 of file ELF.h.
Elf_Nhdr
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Nhdr = typename ELFT::Nhdr
Definition at line 87 of file ELF.h.
Elf_Note
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Note = typename ELFT::Note
Definition at line 88 of file ELF.h.
Elf_Note_Iterator
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Note_Iterator = typename ELFT::NoteIterator
Definition at line 89 of file ELF.h.
Elf_Phdr
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Phdr = typename ELFT::Phdr
Definition at line 76 of file ELF.h.
Elf_Phdr_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Phdr_Range = typename ELFT::PhdrRange
Definition at line 96 of file ELF.h.
Elf_Rel
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Rel = typename ELFT::Rel
Definition at line 77 of file ELF.h.
Elf_Rel_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Rel_Range = typename ELFT::RelRange
Definition at line 93 of file ELF.h.
Elf_Rela
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Rela = typename ELFT::Rela
Definition at line 78 of file ELF.h.
Elf_Rela_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Rela_Range = typename ELFT::RelaRange
Definition at line 94 of file ELF.h.
Elf_Relr
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Relr = typename ELFT::Relr
Definition at line 79 of file ELF.h.
Elf_Relr_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Relr_Range = typename ELFT::RelrRange
Definition at line 95 of file ELF.h.
Elf_Shdr
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Shdr = typename ELFT::Shdr
Definition at line 73 of file ELF.h.
Elf_Shdr_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Shdr_Range = typename ELFT::ShdrRange
Definition at line 91 of file ELF.h.
Elf_Sym
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Sym = typename ELFT::Sym
Definition at line 74 of file ELF.h.
Elf_Sym_Range
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Sym_Range = typename ELFT::SymRange
Definition at line 92 of file ELF.h.
Elf_Verdaux
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Verdaux = typename ELFT::Verdaux
Definition at line 81 of file ELF.h.
Elf_Verdef
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Verdef = typename ELFT::Verdef
Definition at line 80 of file ELF.h.
Elf_Vernaux
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Vernaux = typename ELFT::Vernaux
Definition at line 83 of file ELF.h.
Elf_Verneed
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Verneed = typename ELFT::Verneed
Definition at line 82 of file ELF.h.
Elf_Versym
template<class ELFT > using llvm::object::ELFFile< ELFT >::Elf_Versym = typename ELFT::Versym
Definition at line 84 of file ELF.h.
uintX_t
template<class ELFT > using llvm::object::ELFFile< ELFT >::uintX_t = typename ELFT::uint
Definition at line 71 of file ELF.h.
Member Function Documentation
android_relas()
template<class ELFT > Expected< std::vector< typename ELFT::Rela > > ELFFile::android_relas (const Elf_Shdr * Sec) const
Definition at line 349 of file ELF.cpp.
References llvm::object::createError(), llvm::decodeSLEB128(), I, llvm::ELF::RELOCATION_GROUP_HAS_ADDEND_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_ADDEND_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_INFO_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_OFFSET_DELTA_FLAG, and llvm::Expected< T >::takeError().
base()
template<class ELFT > const uint8_t * llvm::object::ELFFile< ELFT >::base () const inline
Definition at line 98 of file ELF.h.
References llvm::StringRef::bytes_begin().
Referenced by llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::ELFFile< ELFT >::notes_begin(), and llvm::object::ELFFile< ELFT >::program_headers().
create()
template<class ELFT > Expected< ELFFile< ELFT > > llvm::object::ELFFile< ELFT >::create (StringRef Object) static
Definition at line 479 of file ELF.h.
References llvm::object::createError().
decode_relrs()
template<class ELFT > Expected< std::vector< typename ELFT::Rela > > ELFFile::decode_relrs (Elf_Relr_Range relrs) const
Definition at line 270 of file ELF.cpp.
dynamicEntries()
template<class ELFT > Expected< typename ELFT::DynRange > ELFFile::dynamicEntries
Definition at line 498 of file ELF.cpp.
References llvm::ArrayRef< T >::back(), llvm::object::createError(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::empty(), llvm::makeArrayRef(), llvm::ELF::PT_DYNAMIC, llvm::ELF::SHT_DYNAMIC, and llvm::Expected< T >::takeError().
getBufSize()
template<class ELFT > size_t llvm::object::ELFFile< ELFT >::getBufSize () const inline
Definition at line 100 of file ELF.h.
References llvm::StringRef::size().
Referenced by llvm::object::ELFFile< ELFT >::notes_begin(), and llvm::object::ELFFile< ELFT >::program_headers().
getDynamicTagAsString() [1/2]
template<class ELFT > std::string ELFFile::getDynamicTagAsString (uint64_t Type) const
Definition at line 493 of file ELF.cpp.
getDynamicTagAsString() [2/2]
template<class ELFT > std::string ELFFile::getDynamicTagAsString (unsigned Arch, uint64_t Type) const
Definition at line 429 of file ELF.cpp.
References llvm::ELF::EM_AARCH64, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC64, and llvm::utohexstr().
getEntry() [1/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (const Elf_Shdr * Section, uint32_t Entry) const
Definition at line 540 of file ELF.h.
References llvm::object::createError(), llvm::object::getSecIndexForError(), T, and llvm::Twine::utohexstr().
getEntry() [2/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (uint32_t Section, uint32_t Entry) const
Definition at line 530 of file ELF.h.
References llvm::object::getSection().
getHeader()
template<class ELFT > const Elf_Ehdr * llvm::object::ELFFile< ELFT >::getHeader () const inline
Definition at line 108 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL(), llvm::object::ELFFile< ELFT >::isMipsELF64(), and llvm::object::ELFFile< ELFT >::program_headers().
getRelativeRelocationType()
template<class ELFT > uint32_t llvm::object::ELFFile< ELFT >::getRelativeRelocationType
Definition at line 446 of file ELF.h.
References llvm::object::getELFRelativeRelocationType().
getRelocationSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getRelocationSymbol (const Elf_Rel * Rel, const Elf_Shdr * SymTab) const
Get the symbol for a given relocation.
Definition at line 452 of file ELF.h.
getRelocationTypeName() [1/2]
template<class ELFT > StringRef llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type) const
Definition at line 410 of file ELF.h.
References llvm::object::getELFRelocationTypeName().
getRelocationTypeName() [2/2]
template<class ELFT > void llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > & Result) const
Definition at line 415 of file ELF.h.
References Name, Type2, and Type3.
getSection() [1/4]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym * Sym, const Elf_Shdr * SymTab, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 336 of file ELF.h.
References llvm::object::getSection().
getSection() [2/4]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym * Sym, Elf_Sym_Range Symtab, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 346 of file ELF.h.
References llvm::object::getSection().
getSection() [3/4]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const StringRef SectionName) const
Definition at line 565 of file ELF.h.
References llvm::object::createError().
getSection() [4/4]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (uint32_t Index) const
Definition at line 556 of file ELF.h.
getSectionContents()
template<class ELFT > Expected< ArrayRef< uint8_t > > llvm::object::ELFFile< ELFT >::getSectionContents (const Elf_Shdr * Sec) const
Definition at line 405 of file ELF.h.
getSectionContentsAsArray()
template<class ELFT > template<typename T > Expected< ArrayRef< T > > llvm::object::ELFFile< ELFT >::getSectionContentsAsArray (const Elf_Shdr * Sec) const
Definition at line 375 of file ELF.h.
References llvm::object::createError(), llvm::object::getSecIndexForError(), llvm::makeArrayRef(), Size, and llvm::Twine::utohexstr().
getSectionIndex()
template<class ELFT > Expected< uint32_t > llvm::object::ELFFile< ELFT >::getSectionIndex (const Elf_Sym * Sym, Elf_Sym_Range Syms, ArrayRef< Elf_Word > ShndxTable) const
Definition at line 319 of file ELF.h.
References llvm::ELF::SHN_LORESERVE, llvm::ELF::SHN_UNDEF, and llvm::ELF::SHN_XINDEX.
getSectionName() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr * Section) const
Definition at line 665 of file ELF.h.
getSectionName() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr * Section, StringRef DotShstrtab) const
Definition at line 676 of file ELF.h.
References llvm::object::createError(), llvm::StringRef::data(), llvm::object::getSecIndexForError(), llvm::StringRef::size(), and llvm::Twine::utohexstr().
getSectionStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionStringTable (Elf_Shdr_Range Sections) const
Definition at line 462 of file ELF.h.
References llvm::object::createError(), and llvm::ELF::SHN_XINDEX.
getSHNDXTable() [1/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section) const
Definition at line 607 of file ELF.h.
getSHNDXTable() [2/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 616 of file ELF.h.
References assert(), llvm::object::createError(), llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_SYMTAB, llvm::ELF::SHT_SYMTAB_SHNDX, and llvm::ArrayRef< T >::size().
getStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTable (const Elf_Shdr * Section) const
Definition at line 582 of file ELF.h.
References llvm::object::createError(), llvm::Data, llvm::object::getELFSectionTypeName(), llvm::object::getSecIndexForError(), and llvm::ELF::SHT_STRTAB.
getStringTableForSymtab() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section) const
Definition at line 641 of file ELF.h.
getStringTableForSymtab() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 650 of file ELF.h.
References llvm::object::createError(), llvm::ELF::SHT_DYNSYM, and llvm::ELF::SHT_SYMTAB.
getSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getSymbol (const Elf_Shdr * Sec, uint32_t Index) const
Definition at line 359 of file ELF.h.
References llvm::object::createError(), and llvm::object::getSecIndexForError().
isMips64EL()
template<class ELFT > bool llvm::object::ELFFile< ELFT >::isMips64EL () const inline
Definition at line 145 of file ELF.h.
References llvm::ELF::ELFDATA2LSB, llvm::object::ELFFile< ELFT >::getHeader(), and llvm::object::ELFFile< ELFT >::isMipsELF64().
isMipsELF64()
template<class ELFT > bool llvm::object::ELFFile< ELFT >::isMipsELF64 () const inline
Definition at line 140 of file ELF.h.
References llvm::ELF::ELFCLASS64, llvm::ELF::EM_MIPS, and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
notes() [1/2]
template<class ELFT > iterator_range< Elf_Note_Iterator > llvm::object::ELFFile< ELFT >::notes (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator range over notes of a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 247 of file ELF.h.
References llvm::make_range(), llvm::object::ELFFile< ELFT >::notes_begin(), and llvm::object::ELFFile< ELFT >::notes_end().
notes() [2/2]
template<class ELFT > iterator_range< Elf_Note_Iterator > llvm::object::ELFFile< ELFT >::notes (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator range over notes of a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 259 of file ELF.h.
References llvm::make_range(), llvm::object::ELFFile< ELFT >::notes_begin(), and llvm::object::ELFFile< ELFT >::notes_end().
notes_begin() [1/2]
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator over notes in a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 203 of file ELF.h.
References assert(), llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::ELF::PT_NOTE, and llvm::Twine::utohexstr().
Referenced by llvm::object::ELFFile< ELFT >::notes().
notes_begin() [2/2]
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator over notes in a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 222 of file ELF.h.
References assert(), llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::object::getSecIndexForError(), llvm::ELF::SHT_NOTE, and llvm::Twine::utohexstr().
notes_end()
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_end () const inline
Get the end iterator for notes.
Definition at line 236 of file ELF.h.
Referenced by llvm::object::ELFFile< ELFT >::notes().
program_headers()
template<class ELFT > Expected< Elf_Phdr_Range > llvm::object::ELFFile< ELFT >::program_headers () const inline
Iterate over program header table.
Definition at line 179 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::makeArrayRef(), and llvm::Twine::utohexstr().
relas()
template<class ELFT > Expected< Elf_Rela_Range > llvm::object::ELFFile< ELFT >::relas (const Elf_Shdr * Sec) const inline
Definition at line 162 of file ELF.h.
relrs()
template<class ELFT > Expected< Elf_Relr_Range > llvm::object::ELFFile< ELFT >::relrs (const Elf_Shdr * Sec) const inline
Definition at line 170 of file ELF.h.
rels()
template<class ELFT > Expected< Elf_Rel_Range > llvm::object::ELFFile< ELFT >::rels (const Elf_Shdr * Sec) const inline
Definition at line 166 of file ELF.h.
sections()
template<class ELFT > Expected< typename ELFT::ShdrRange > llvm::object::ELFFile< ELFT >::sections
Definition at line 488 of file ELF.h.
References llvm::object::createError(), llvm::makeArrayRef(), UINT64_MAX, and llvm::Twine::utohexstr().
Referenced by llvm::object::getSecIndexForError().
symbols()
template<class ELFT > Expected< Elf_Sym_Range > llvm::object::ELFFile< ELFT >::symbols (const Elf_Shdr * Sec) const inline
Definition at line 156 of file ELF.h.
toMappedAddr()
template<class ELFT > Expected< const uint8_t * > ELFFile::toMappedAddr (uint64_t VAddr) const
Definition at line 555 of file ELF.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::object::createError(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::ELF::PT_LOAD, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Twine::utohexstr().
The documentation for this class was generated from the following files:
include/llvm/Object/ELF.h
lib/Object/ELF.cpp