LLVM: llvm::ImmutableListImpl< T > Class Template Reference
llvm::ImmutableListImpl< T > Class Template Reference
#include "llvm/ADT/ImmutableList.h"
Public Member Functions
ImmutableListImpl (const ImmutableListImpl &)=delete
ImmutableListImpl & operator= (const ImmutableListImpl &)=delete
const T & getHead () const
const ImmutableListImpl * getTail () const
void Profile (FoldingSetNodeID &ID)
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, const T &H, const ImmutableListImpl *L)
Friends
class ImmutableListFactory< T >
Detailed Description
template<typename T>
class llvm::ImmutableListImpl< T >
Definition at line 27 of file ImmutableList.h.
Constructor & Destructor Documentation
ImmutableListImpl()
template<typename T > llvm::ImmutableListImpl< T >::ImmutableListImpl (const ImmutableListImpl< T > &) delete
Member Function Documentation
getHead()
template<typename T > const T & llvm::ImmutableListImpl< T >::getHead () const inline
Definition at line 41 of file ImmutableList.h.
Referenced by llvm::ImmutableList< T >::getHead(), llvm::ImmutableList< T >::iterator::operator*(), and llvm::ImmutableList< T >::iterator::operator->().
getTail()
template<typename T > const ImmutableListImpl * llvm::ImmutableListImpl< T >::getTail () const inline
Definition at line 42 of file ImmutableList.h.
Referenced by llvm::ImmutableList< T >::getTail(), and llvm::ImmutableList< T >::iterator::operator++().
operator=()
template<typename T > ImmutableListImpl & llvm::ImmutableListImpl< T >::operator= (const ImmutableListImpl< T > &) delete
Profile() [1/2]
template<typename T > void llvm::ImmutableListImpl< T >::Profile (FoldingSetNodeID & ID) inline
Definition at line 50 of file ImmutableList.h.
References llvm::ImmutableListImpl< T >::Profile().
Profile() [2/2]
template<typename T > static void llvm::ImmutableListImpl< T >::Profile (FoldingSetNodeID & ID, const T & H, const ImmutableListImpl< T > * L) inline static
Definition at line 44 of file ImmutableList.h.
References H.
Referenced by llvm::ImmutableListImpl< T >::Profile().
Friends And Related Function Documentation
ImmutableListFactory< T >
template<typename T > friend class ImmutableListFactory< T > friend
Definition at line 1 of file ImmutableList.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableList.h