LLVM: llvm::IRMover Class Reference
llvm::IRMover Class Reference
#include "llvm/Linker/IRMover.h"
Classes
class IdentifiedStructTypeSet
Public Types
typedef std::function< void(GlobalValue &)> ValueAdder
Public Member Functions
IRMover (Module &M)
Error move (std::unique_ptr< Module > Src, ArrayRef< GlobalValue * > ValuesToLink, std::function< void(GlobalValue &GV, ValueAdder Add)> AddLazyFor, bool IsPerformingImport)
Move in the provide values in ValuesToLink from Src.
Module & getModule ()
Detailed Description
Definition at line 25 of file IRMover.h.
Member Typedef Documentation
ValueAdder
typedef std::function<void(GlobalValue &)> llvm::IRMover::ValueAdder
Definition at line 64 of file IRMover.h.
Constructor & Destructor Documentation
IRMover()
IRMover::IRMover (Module & M)
Definition at line 1516 of file IRMover.cpp.
References llvm::IRMover::IdentifiedStructTypeSet::addNonOpaque(), llvm::IRMover::IdentifiedStructTypeSet::addOpaque(), llvm::TypeFinder::getVisitedMetadata(), and llvm::TypeFinder::run().
Member Function Documentation
getModule()
Module & llvm::IRMover::getModule () inline
Definition at line 78 of file IRMover.h.
move()
Error IRMover::move (std::unique_ptr< Module > Src, ArrayRef< GlobalValue * > ValuesToLink, std::function< void(GlobalValue &GV, ValueAdder Add)> AddLazyFor, bool IsPerformingImport)
Move in the provide values in ValuesToLink from Src.
AddLazyFor is a call back that the IRMover will call when a global value is referenced by one of the ValuesToLink (transitively) but was not present in ValuesToLink. The GlobalValue and a ValueAdder callback are passed as an argument, and the callback is expected to be called if the GlobalValue needs to be added to the ValuesToLink and linked.
IsPerformingImport is true when this IR link is to perform ThinLTO function importing from Src.
Definition at line 1533 of file IRMover.cpp.
References llvm::Module::dropTriviallyDeadConstantArrays().
Referenced by llvm::FunctionImporter::importFunctions().
The documentation for this class was generated from the following files:
include/llvm/Linker/IRMover.h
lib/Linker/IRMover.cpp