LLVM: llvm::LegacyDivergenceAnalysis Class Reference
llvm::LegacyDivergenceAnalysis Class Reference
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
Public Member Functions
LegacyDivergenceAnalysis ()
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
void print (raw_ostream &OS, const Module *) const override
bool isDivergent (const Value *V) const
bool isUniform (const Value *V) const
void removeValue (const Value *V)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 26 of file LegacyDivergenceAnalysis.h.
Constructor & Destructor Documentation
LegacyDivergenceAnalysis()
llvm::LegacyDivergenceAnalysis::LegacyDivergenceAnalysis () inline
Definition at line 30 of file LegacyDivergenceAnalysis.h.
Member Function Documentation
getAnalysisUsage()
void LegacyDivergenceAnalysis::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 290 of file LegacyDivergenceAnalysis.cpp.
References UseGPUDA.
isDivergent()
bool LegacyDivergenceAnalysis::isDivergent (const Value * V) const
Definition at line 347 of file LegacyDivergenceAnalysis.cpp.
Referenced by isUniform(), and print().
isUniform()
bool llvm::LegacyDivergenceAnalysis::isUniform (const Value * V) const inline
Definition at line 51 of file LegacyDivergenceAnalysis.h.
References isDivergent().
Referenced by hasOnlyUniformBranches().
print()
void LegacyDivergenceAnalysis::print (raw_ostream & OS, const Module *) const override
Definition at line 354 of file LegacyDivergenceAnalysis.cpp.
References F, llvm::Value::getName(), I, llvm::BasicBlock::instructionsWithoutDebug(), isDivergent(), and llvm_unreachable.
Referenced by runOnFunction().
removeValue()
void llvm::LegacyDivergenceAnalysis::removeValue (const Value * V) inline
Definition at line 54 of file LegacyDivergenceAnalysis.h.
runOnFunction()
bool LegacyDivergenceAnalysis::runOnFunction (Function & F) override
Definition at line 311 of file LegacyDivergenceAnalysis.cpp.
References llvm::dbgs(), F, llvm::TargetTransformInfo::hasBranchDivergence(), LLVM_DEBUG, and print().
Member Data Documentation
ID
char LegacyDivergenceAnalysis::ID = 0 static
Definition at line 28 of file LegacyDivergenceAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LegacyDivergenceAnalysis.h
lib/Analysis/LegacyDivergenceAnalysis.cpp