LLVM: llvm::LoopInfo Class Reference
llvm::LoopInfo Class Reference
#include "llvm/Analysis/LoopInfo.h"
Public Member Functions
LoopInfo ()
LoopInfo (const DominatorTreeBase< BasicBlock, false > &DomTree)
LoopInfo (LoopInfo &&Arg)
LoopInfo & operator= (LoopInfo &&RHS)
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
void erase (Loop *L)
Update LoopInfo after removing the last backedge from a loop.
bool replacementPreservesLCSSAForm (Instruction *From, Value *To)
Returns true if replacing From with To everywhere is guaranteed to preserve LCSSA form.
bool movementPreservesLCSSAForm (Instruction *Inst, Instruction *NewLoc)
Checks if moving a specific instruction can break LCSSA in any loop.
Public Member Functions inherited from llvm::LoopInfoBase< BasicBlock, Loop >
LoopInfoBase & operator= (LoopInfoBase &&RHS)
LoopInfoBase ()
LoopInfoBase (LoopInfoBase &&Arg)
~LoopInfoBase ()
void releaseMemory ()
Loop * AllocateLoop (ArgsTy &&... Args)
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
SmallVector< Loop *, 4 > getLoopsInPreorder ()
Return all of the loops in the function in preorder across the loop nests, with siblings in forward program order.
SmallVector< Loop *, 4 > getLoopsInReverseSiblingPreorder ()
Return all of the loops in the function in preorder across the loop nests, with siblings in reverse program order.
Loop * getLoopFor (const BasicBlock *BB) const
Return the inner most loop that BB lives in.
const Loop * operator[] (const BasicBlock *BB) const
Same as getLoopFor.
unsigned getLoopDepth (const BasicBlock *BB) const
Return the loop nesting level of the specified block.
bool isLoopHeader (const BasicBlock *BB) const
Loop * removeLoop (iterator I)
This removes the specified top-level loop from this loop info object.
void changeLoopFor (BasicBlock *BB, Loop *L)
Change the top-level loop that contains BB to the specified loop.
void changeTopLevelLoop (Loop *OldLoop, Loop *NewLoop)
Replace the specified loop in the top-level loops list with the indicated loop.
void addTopLevelLoop (Loop *New)
This adds the specified loop to the collection of top-level loops.
void removeBlock (BasicBlock *BB)
This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from BasicBlocks to loops.
void analyze (const DominatorTreeBase< BasicBlock, false > &DomTree)
Create the loop forest using a stable algorithm.
void print (raw_ostream &OS) const
void verify (const DominatorTreeBase< BasicBlock, false > &DomTree) const
void destroy (Loop *L)
Destroy a loop that has been removed from the LoopInfo nest.
Friends
class LoopBase< BasicBlock, Loop >
Additional Inherited Members
Public Types inherited from llvm::LoopInfoBase< BasicBlock, Loop >
typedef std::vector< Loop * >::const_iterator iterator
iterator/begin/end - The interface to the top-level loops in the current function.
typedef std::vector< Loop * >::const_reverse_iterator reverse_iterator
Static Public Member Functions inherited from llvm::LoopInfoBase< BasicBlock, Loop >
static bool isNotAlreadyContainedIn (const Loop *SubLoop, const Loop *ParentLoop)
Detailed Description
Definition at line 1007 of file LoopInfo.h.
Constructor & Destructor Documentation
LoopInfo() [1/3]
llvm::LoopInfo::LoopInfo () inline
Definition at line 1016 of file LoopInfo.h.
LoopInfo() [2/3]
llvm::LoopInfo::LoopInfo (const DominatorTreeBase< BasicBlock, false > & DomTree) explicit
LoopInfo() [3/3]
llvm::LoopInfo::LoopInfo (LoopInfo && Arg) inline
Definition at line 1019 of file LoopInfo.h.
Member Function Documentation
erase()
void LoopInfo::erase (Loop * L)
Update LoopInfo after removing the last backedge from a loop.
This updates the loop forest and parent loops for each block so that L is no longer referenced, but does not actually delete L immediately. The pointer will remain valid until this LoopInfo's memory is released.
Definition at line 818 of file LoopInfo.cpp.
References llvm::LoopInfoBase< BasicBlock, Loop >::addTopLevelLoop(), assert(), llvm::LoopBase< BlockT, LoopT >::begin(), llvm::LoopInfoBase< BasicBlock, Loop >::begin(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopInfoBase< BasicBlock, Loop >::changeLoopFor(), llvm::LoopInfoBase< BasicBlock, Loop >::destroy(), llvm::LoopBase< BlockT, LoopT >::empty(), llvm::LoopBase< BlockT, LoopT >::end(), llvm::LoopInfoBase< BasicBlock, Loop >::end(), llvm::LoopInfoBase< BasicBlock, Loop >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), I, llvm::LoopBase< BlockT, LoopT >::isInvalid(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), and llvm::LoopInfoBase< BasicBlock, Loop >::removeLoop().
Referenced by llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
invalidate()
bool LoopInfo::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
Definition at line 809 of file LoopInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
movementPreservesLCSSAForm()
bool llvm::LoopInfo::movementPreservesLCSSAForm (Instruction * Inst, Instruction * NewLoc) inline
Checks if moving a specific instruction can break LCSSA in any loop.
Return true if moving Inst to before NewLoc will break LCSSA, assuming that the function containing Inst and NewLoc is currently in LCSSA form.
Definition at line 1065 of file LoopInfo.h.
References assert(), llvm::Instruction::getFunction(), llvm::Instruction::getParent(), llvm::User::operands(), and llvm::Value::uses().
Referenced by llvm::SCEVExpander::hoistIVInc().
operator=()
LoopInfo & llvm::LoopInfo::operator= (LoopInfo && RHS) inline
Definition at line 1020 of file LoopInfo.h.
replacementPreservesLCSSAForm()
bool llvm::LoopInfo::replacementPreservesLCSSAForm (Instruction * From, Value * To) inline
Returns true if replacing From with To everywhere is guaranteed to preserve LCSSA form.
Definition at line 1039 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::Instruction::getParent(), and I.
Referenced by llvm::SCEVExpander::replaceCongruentIVs(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), and simplifyOneLoop().
Friends And Related Function Documentation
LoopBase< BasicBlock, Loop >
friend class LoopBase< BasicBlock, Loop > friend
Definition at line 1008 of file LoopInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopInfo.h
lib/Analysis/LoopInfo.cpp