LLVM: llvm::DiagnosticInfoIgnoringInvalidDebugMetadata Class Reference
llvm::DiagnosticInfoIgnoringInvalidDebugMetadata Class Reference
Diagnostic information for stripping invalid debug metadata.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoIgnoringInvalidDebugMetadata (const Module &M, DiagnosticSeverity Severity=DS_Warning)
The module that is concerned by this debug metadata version diagnostic.
const Module & getModule () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
virtual void print (DiagnosticPrinter &DP) const =0
Print using the given DP a user-friendly message.
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for stripping invalid debug metadata.
Definition at line 258 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoIgnoringInvalidDebugMetadata()
llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::DiagnosticInfoIgnoringInvalidDebugMetadata (const Module & M, DiagnosticSeverity Severity = DS_Warning) inline
The module that is concerned by this debug metadata version diagnostic.
Definition at line 265 of file DiagnosticInfo.h.
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::classof (const DiagnosticInfo * DI) inline static
Definition at line 274 of file DiagnosticInfo.h.
References llvm::DK_DebugMetadataInvalid, and llvm::DiagnosticInfo::getKind().
getModule()
const Module & llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::getModule () const inline
Definition at line 269 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoIgnoringInvalidDebugMetadata::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 85 of file DiagnosticInfo.cpp.
References getModule(), and llvm::Module::getModuleIdentifier().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp