LLVM: llvm::orc::rpc::detail::ResultTraits< RetT > Class Template Reference
llvm::orc::rpc::detail::ResultTraits< RetT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/RPCUtils.h"
Public Types
using ErrorReturnType = Expected< RetT >
using ReturnPromiseType = std::promise< ErrorReturnType >
using ReturnFutureType = std::future< ErrorReturnType >
Static Public Member Functions
static ErrorReturnType createBlankErrorReturnValue ()
static void consumeAbandoned (ErrorReturnType RetOrErr)
Detailed Description
template<typename RetT>
class llvm::orc::rpc::detail::ResultTraits< RetT >
Definition at line 214 of file RPCUtils.h.
Member Typedef Documentation
ErrorReturnType
template<typename RetT > using llvm::orc::rpc::detail::ResultTraits< RetT >::ErrorReturnType = Expected<RetT>
Definition at line 217 of file RPCUtils.h.
ReturnFutureType
template<typename RetT > using llvm::orc::rpc::detail::ResultTraits< RetT >::ReturnFutureType = std::future<ErrorReturnType>
Definition at line 230 of file RPCUtils.h.
ReturnPromiseType
template<typename RetT > using llvm::orc::rpc::detail::ResultTraits< RetT >::ReturnPromiseType = std::promise<ErrorReturnType>
Definition at line 227 of file RPCUtils.h.
Member Function Documentation
consumeAbandoned()
template<typename RetT > static void llvm::orc::rpc::detail::ResultTraits< RetT >::consumeAbandoned (ErrorReturnType RetOrErr) inline static
Definition at line 240 of file RPCUtils.h.
References llvm::consumeError(), and llvm::Expected< T >::takeError().
Referenced by llvm::orc::rpc::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB(), and llvm::orc::rpc::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB().
createBlankErrorReturnValue()
template<typename RetT > static ErrorReturnType llvm::orc::rpc::detail::ResultTraits< RetT >::createBlankErrorReturnValue () inline static
Definition at line 235 of file RPCUtils.h.
Referenced by llvm::orc::rpc::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCUtils.h