LLVM: llvm::GenericScheduler Class Reference
llvm::GenericScheduler Class Reference
GenericScheduler shrinks the unscheduled zone using heuristics to balance the schedule.
#include "llvm/CodeGen/MachineScheduler.h"
Public Member Functions
GenericScheduler (const MachineSchedContext *C)
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Initialize the per-region scheduling policy.
void dumpPolicy () const override
bool shouldTrackPressure () const override
Check if pressure tracking is needed before building the DAG and initializing this strategy.
bool shouldTrackLaneMasks () const override
Returns true if lanemasks should be tracked.
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void schedNode (SUnit *SU, bool IsTopNode) override
Update the scheduler's state after scheduling a node.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual SUnit * pickNode (bool &IsTopNode)=0
Pick the next node to schedule, or return NULL.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
virtual void releaseTopNode (SUnit *SU)=0
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
virtual void releaseBottomNode (SUnit *SU)=0
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Protected Member Functions
void checkAcyclicLatency ()
Set IsAcyclicLatencyLimited if the acyclic path is longer than the cyclic critical path by more cycles than it takes to drain the instruction buffer.
void initCandidate (SchedCandidate &Cand, SUnit *SU, bool AtTop, const RegPressureTracker &RPTracker, RegPressureTracker &TempTracker)
virtual void tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand, SchedBoundary *Zone) const
Apply a set of heuristics to a new candidate.
SUnit * pickNodeBidirectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
void pickNodeFromQueue (SchedBoundary &Zone, const CandPolicy &ZonePolicy, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
Pick the best candidate from the queue.
void reschedulePhysReg (SUnit *SU, bool isTop)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
ScheduleDAGMILive * DAG = nullptr
MachineSchedPolicy RegionPolicy
SchedBoundary Top
SchedBoundary Bot
SchedCandidate TopCand
Candidate last picked from Top boundary.
SchedCandidate BotCand
Candidate last picked from Bot boundary.
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
SchedRemainder Rem
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NextDefUse ,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Detailed Description
GenericScheduler shrinks the unscheduled zone using heuristics to balance the schedule.
Definition at line 927 of file MachineScheduler.h.
Constructor & Destructor Documentation
GenericScheduler()
llvm::GenericScheduler::GenericScheduler (const MachineSchedContext * C) inline
Definition at line 929 of file MachineScheduler.h.
Member Function Documentation
checkAcyclicLatency()
void GenericScheduler::checkAcyclicLatency () protected
Set IsAcyclicLatencyLimited if the acyclic path is longer than the cyclic critical path by more cycles than it takes to drain the instruction buffer.
We estimate an upper bounds on in-flight instructions as:
CyclesPerIteration = max(CyclicPath, Loop-Resource-Height) InFlightIterations = AcyclicPath / CyclesPerIteration InFlightResources = InFlightIterations * LoopResources
TODO: Check execution resources in addition to IssueCount.
Definition at line 2811 of file MachineScheduler.cpp.
References llvm::SchedRemainder::CriticalPath, llvm::SchedRemainder::CyclicCritPath, llvm::dbgs(), llvm::TargetSchedModel::getLatencyFactor(), llvm::TargetSchedModel::getMicroOpBufferSize(), llvm::TargetSchedModel::getMicroOpFactor(), if(), llvm::SchedRemainder::IsAcyclicLatencyLimited, LLVM_DEBUG, llvm::GenericSchedulerBase::Rem, llvm::SchedRemainder::RemIssueCount, and llvm::GenericSchedulerBase::SchedModel.
Referenced by registerRoots().
dumpPolicy()
void GenericScheduler::dumpPolicy () const override virtual
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 2791 of file MachineScheduler.cpp.
References llvm::dbgs(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, RegionPolicy, and llvm::MachineSchedPolicy::ShouldTrackPressure.
initCandidate()
void GenericScheduler::initCandidate (SchedCandidate & Cand, SUnit * SU, bool AtTop, const RegPressureTracker & RPTracker, RegPressureTracker & TempTracker) protected
Definition at line 2948 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, DAG, llvm::dbgs(), llvm::RegPressureDelta::Excess, llvm::SUnit::getInstr(), llvm::RegPressureTracker::getMaxDownwardPressureDelta(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::ScheduleDAGMILive::getPressureDiff(), llvm::PressureChange::getPSet(), llvm::ScheduleDAGMILive::getRegionCriticalPSets(), llvm::ScheduleDAGMILive::getRegPressure(), llvm::TargetRegisterInfo::getRegPressureSetName(), llvm::PressureChange::getUnitInc(), llvm::RegPressureTracker::getUpwardPressureDelta(), llvm::ScheduleDAGMILive::isTrackingPressure(), llvm::PressureChange::isValid(), LLVM_DEBUG, llvm::RegisterPressure::MaxSetPressure, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::SchedCandidate::RPDelta, llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::GenericSchedulerBase::TRI, and VerifyScheduling.
Referenced by pickNodeFromQueue().
initialize()
void GenericScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::GCNMaxOccupancySchedStrategy.
Definition at line 2712 of file MachineScheduler.cpp.
References assert(), Bot, BotCand, llvm::TargetInstrInfo::CreateTargetMIHazardRecognizer(), DAG, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSchedModel::getInstrItineraries(), llvm::ScheduleDAGInstrs::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::ScheduleDAGMI::hasVRegLiveness(), llvm::SchedBoundary::HazardRec, llvm::SchedRemainder::init(), llvm::SchedBoundary::init(), llvm::ScheduleDAG::MF, llvm::GenericSchedulerBase::Rem, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::SU, Top, TopCand, llvm::GenericSchedulerBase::TRI, and llvm::ScheduleDAG::TRI.
initPolicy()
void GenericScheduler::initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override virtual
Initialize the per-region scheduling policy.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 2743 of file MachineScheduler.cpp.
References assert(), llvm::GenericSchedulerBase::Context, EnableRegPressure, llvm::ForceBottomUp, llvm::ForceTopDown, llvm::RegisterClassInfo::getNumAllocatableRegs(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MVT::i1, llvm::MVT::i32, llvm::TargetLoweringBase::isTypeLegal(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::TargetSubtargetInfo::overrideSchedPolicy(), llvm::MachineSchedContext::RegClassInfo, RegionPolicy, llvm::MachineSchedPolicy::ShouldTrackLaneMasks, and llvm::MachineSchedPolicy::ShouldTrackPressure.
pickNode()
SUnit * GenericScheduler::pickNode (bool & IsTopNode) override virtual
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::GCNMaxOccupancySchedStrategy.
Definition at line 3208 of file MachineScheduler.cpp.
References assert(), llvm::SchedBoundary::Available, Bot, BotCand, llvm::ScheduleDAGMI::bottom(), DAG, llvm::dbgs(), llvm::ReadyQueue::empty(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::SUnit::getInstr(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isBottomReady(), llvm::SUnit::isScheduled, llvm::SUnit::isTopReady(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::SchedBoundary::Pending, pickNodeBidirectional(), pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::GenericSchedulerBase::SchedCandidate::Reason, RegionPolicy, llvm::SchedBoundary::removeReady(), llvm::GenericSchedulerBase::SchedCandidate::reset(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::ScheduleDAGMI::top(), Top, TopCand, and tracePick().
pickNodeBidirectional()
SUnit * GenericScheduler::pickNodeBidirectional (bool & IsTopNode) protected
Pick the best candidate node from either the top or bottom queue.
Definition at line 3129 of file MachineScheduler.cpp.
References assert(), llvm::GenericSchedulerBase::SchedCandidate::AtTop, Bot, BotCand, DAG, llvm::dbgs(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isScheduled, llvm::GenericSchedulerBase::SchedCandidate::isValid(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::GenericSchedulerBase::Only1, pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::SchedCandidate::reset(), llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::setPolicy(), llvm::GenericSchedulerBase::SchedCandidate::SU, Top, TopCand, llvm::GenericSchedulerBase::traceCandidate(), tracePick(), tryCandidate(), and VerifyScheduling.
Referenced by pickNode().
pickNodeFromQueue()
void GenericScheduler::pickNodeFromQueue (SchedBoundary & Zone, const CandPolicy & ZonePolicy, const RegPressureTracker & RPTracker, SchedCandidate & Cand) protected
Pick the best candidate from the queue.
TODO: getMaxPressureDelta results can be mostly cached for each SUnit during DAG building. To adjust for the current scheduling location we need to maintain the number of vreg uses remaining to be top-scheduled.
Definition at line 3103 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::SchedBoundary::Available, DAG, initCandidate(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::SchedBoundary::isTop(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::traceCandidate(), and tryCandidate().
Referenced by pickNode(), and pickNodeBidirectional().
registerRoots()
void GenericScheduler::registerRoots () override virtual
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 2839 of file MachineScheduler.cpp.
References llvm::SchedBoundary::Available, Bot, checkAcyclicLatency(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::SchedRemainder::CriticalPath, llvm::SchedRemainder::CyclicCritPath, DAG, llvm::dbgs(), llvm::DumpCriticalPathLength, EnableCyclicPath, llvm::errs(), llvm::ScheduleDAG::ExitSU, llvm::SUnit::getDepth(), llvm::TargetSchedModel::getMicroOpBufferSize(), LLVM_DEBUG, llvm::GenericSchedulerBase::Rem, and llvm::GenericSchedulerBase::SchedModel.
releaseBottomNode()
void llvm::GenericScheduler::releaseBottomNode (SUnit * SU) inline override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 961 of file MachineScheduler.h.
References Bot, BotCand, llvm::SUnit::BotReadyCycle, llvm::SUnit::isScheduled, llvm::SchedBoundary::releaseNode(), and llvm::GenericSchedulerBase::SchedCandidate::SU.
releaseTopNode()
void llvm::GenericScheduler::releaseTopNode (SUnit * SU) inline override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 953 of file MachineScheduler.h.
References llvm::SUnit::isScheduled, llvm::SchedBoundary::releaseNode(), llvm::GenericSchedulerBase::SchedCandidate::SU, Top, TopCand, and llvm::SUnit::TopReadyCycle.
reschedulePhysReg()
void GenericScheduler::reschedulePhysReg (SUnit * SU, bool isTop) protected
Definition at line 3253 of file MachineScheduler.cpp.
References DAG, llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::SUnit::getInstr(), llvm::TargetRegisterInfo::isPhysicalRegister(), LLVM_DEBUG, llvm::ScheduleDAGMI::moveInstruction(), llvm::SUnit::Preds, llvm::SUnit::Succs, and llvm::GenericSchedulerBase::TRI.
Referenced by schedNode().
schedNode()
void GenericScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Update the scheduler's state after scheduling a node.
This is the same node that was just returned by pickNode(). However, ScheduleDAGMILive needs to update it's state based on the current cycle before MachineSchedStrategy does.
FIXME: Eventually, we may bundle physreg copies rather than rescheduling them here. See comments in biasPhysReg.
Implements llvm::MachineSchedStrategy.
Definition at line 3283 of file MachineScheduler.cpp.
References Bot, llvm::SUnit::BotReadyCycle, llvm::SchedBoundary::bumpNode(), llvm::SchedBoundary::getCurrCycle(), llvm::SUnit::hasPhysRegDefs, llvm::SUnit::hasPhysRegUses, reschedulePhysReg(), Top, and llvm::SUnit::TopReadyCycle.
shouldTrackLaneMasks()
bool llvm::GenericScheduler::shouldTrackLaneMasks () const inline override virtual
Returns true if lanemasks should be tracked.
LaneMask tracking is necessary to reorder independent subregister defs for the same vreg. This has to be enabled in combination with shouldTrackPressure().
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 943 of file MachineScheduler.h.
References RegionPolicy, and llvm::MachineSchedPolicy::ShouldTrackLaneMasks.
shouldTrackPressure()
bool llvm::GenericScheduler::shouldTrackPressure () const inline override virtual
Check if pressure tracking is needed before building the DAG and initializing this strategy.
Called after initPolicy.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 939 of file MachineScheduler.h.
References RegionPolicy, and llvm::MachineSchedPolicy::ShouldTrackPressure.
tryCandidate()
void GenericScheduler::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand, SchedBoundary * Zone) const protected virtual
Apply a set of heuristics to a new candidate.
Heuristics are currently hierarchical. This may be more efficient than a graduated cost model because we don't need to evaluate all aspects of the model for each node in the queue. But it's really done to make the heuristics easier to debug and statistically analyze.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Zone describes the scheduled zone that we are extending, or nullptr
Reimplemented in llvm::PPCPreRASchedStrategy.
Definition at line 2995 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::biasPhysReg(), llvm::GenericSchedulerBase::Cluster, llvm::RegPressureDelta::CriticalMax, llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, llvm::RegPressureDelta::CurrentMax, DAG, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::MachineSchedPolicy::DisableLatencyHeuristic, llvm::RegPressureDelta::Excess, llvm::SchedBoundary::getCurrMOps(), llvm::SchedBoundary::getLatencyStallCycles(), llvm::ScheduleDAGMI::getNextClusterPred(), llvm::ScheduleDAGMI::getNextClusterSucc(), llvm::getWeakLeft(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::SchedRemainder::IsAcyclicLatencyLimited, llvm::SchedBoundary::isTop(), llvm::ScheduleDAGMILive::isTrackingPressure(), llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::ScheduleDAG::MF, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::PhysReg, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::RegCritical, llvm::GenericSchedulerBase::RegExcess, RegionPolicy, llvm::GenericSchedulerBase::RegMax, llvm::GenericSchedulerBase::Rem, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::SchedCandidate::RPDelta, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::GenericSchedulerBase::TRI, llvm::tryGreater(), llvm::tryLatency(), llvm::tryLess(), llvm::tryPressure(), and llvm::GenericSchedulerBase::Weak.
Referenced by pickNodeBidirectional(), pickNodeFromQueue(), and llvm::PPCPreRASchedStrategy::tryCandidate().
Member Data Documentation
Bot
SchedBoundary llvm::GenericScheduler::Bot protected
Definition at line 978 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), pickNodeBidirectional(), registerRoots(), releaseBottomNode(), and schedNode().
BotCand
SchedCandidate llvm::GenericScheduler::BotCand protected
Candidate last picked from Bot boundary.
Definition at line 983 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), pickNodeBidirectional(), and releaseBottomNode().
DAG
ScheduleDAGMILive* llvm::GenericScheduler::DAG = nullptr protected
Definition at line 972 of file MachineScheduler.h.
Referenced by initCandidate(), initialize(), llvm::GCNMaxOccupancySchedStrategy::initialize(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), pickNodeBidirectional(), pickNodeFromQueue(), registerRoots(), reschedulePhysReg(), and tryCandidate().
RegionPolicy
MachineSchedPolicy llvm::GenericScheduler::RegionPolicy protected
Definition at line 974 of file MachineScheduler.h.
Referenced by dumpPolicy(), initPolicy(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), shouldTrackLaneMasks(), shouldTrackPressure(), and tryCandidate().
Top
SchedBoundary llvm::GenericScheduler::Top protected
Definition at line 977 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), pickNodeBidirectional(), releaseTopNode(), and schedNode().
TopCand
SchedCandidate llvm::GenericScheduler::TopCand protected
Candidate last picked from Top boundary.
Definition at line 981 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), llvm::GCNMaxOccupancySchedStrategy::pickNode(), pickNodeBidirectional(), and releaseTopNode().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp