LLVM: llvm::SmallPtrSetIterator< PtrTy > Class Template Reference
llvm::SmallPtrSetIterator< PtrTy > Class Template Reference
SmallPtrSetIterator - This implements a const_iterator for SmallPtrSet.
#include "llvm/ADT/SmallPtrSet.h"
Public Types
using value_type = PtrTy
using reference = PtrTy
using pointer = PtrTy
using difference_type = std::ptrdiff_t
using iterator_category = std::forward_iterator_tag
Public Member Functions
SmallPtrSetIterator (const void *const *BP, const void *const *E, const DebugEpochBase &Epoch)
const PtrTy operator* () const
SmallPtrSetIterator & operator++ ()
SmallPtrSetIterator operator++ (int)
Public Member Functions inherited from llvm::SmallPtrSetIteratorImpl
SmallPtrSetIteratorImpl (const void *const *BP, const void *const *E)
bool operator== (const SmallPtrSetIteratorImpl &RHS) const
bool operator!= (const SmallPtrSetIteratorImpl &RHS) const
Additional Inherited Members
Protected Member Functions inherited from llvm::SmallPtrSetIteratorImpl
void AdvanceIfNotValid ()
AdvanceIfNotValid - If the current bucket isn't valid, advance to a bucket that is.
void RetreatIfNotValid ()
Protected Attributes inherited from llvm::SmallPtrSetIteratorImpl
const void *const * Bucket
const void *const * End
Detailed Description
template<typename PtrTy>
class llvm::SmallPtrSetIterator< PtrTy >
SmallPtrSetIterator - This implements a const_iterator for SmallPtrSet.
Definition at line 266 of file SmallPtrSet.h.
Member Typedef Documentation
difference_type
template<typename PtrTy > using llvm::SmallPtrSetIterator< PtrTy >::difference_type = std::ptrdiff_t
Definition at line 274 of file SmallPtrSet.h.
iterator_category
template<typename PtrTy > using llvm::SmallPtrSetIterator< PtrTy >::iterator_category = std::forward_iterator_tag
Definition at line 275 of file SmallPtrSet.h.
pointer
template<typename PtrTy > using llvm::SmallPtrSetIterator< PtrTy >::pointer = PtrTy
Definition at line 273 of file SmallPtrSet.h.
reference
template<typename PtrTy > using llvm::SmallPtrSetIterator< PtrTy >::reference = PtrTy
Definition at line 272 of file SmallPtrSet.h.
value_type
template<typename PtrTy > using llvm::SmallPtrSetIterator< PtrTy >::value_type = PtrTy
Definition at line 271 of file SmallPtrSet.h.
Constructor & Destructor Documentation
SmallPtrSetIterator()
template<typename PtrTy > llvm::SmallPtrSetIterator< PtrTy >::SmallPtrSetIterator (const void *const * BP, const void *const * E, const DebugEpochBase & Epoch) inline explicit
Definition at line 277 of file SmallPtrSet.h.
Member Function Documentation
operator*()
template<typename PtrTy > const PtrTy llvm::SmallPtrSetIterator< PtrTy >::operator* () const inline
Definition at line 283 of file SmallPtrSet.h.
References assert(), llvm::SmallPtrSetIteratorImpl::Bucket, llvm::SmallPtrSetIteratorImpl::End, llvm::DebugEpochBase::HandleBase::isHandleInSync(), and llvm::shouldReverseIterate().
operator++() [1/2]
template<typename PtrTy > SmallPtrSetIterator & llvm::SmallPtrSetIterator< PtrTy >::operator++ () inline
Definition at line 293 of file SmallPtrSet.h.
References llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid(), assert(), llvm::SmallPtrSetIteratorImpl::Bucket, llvm::DebugEpochBase::HandleBase::isHandleInSync(), llvm::SmallPtrSetIteratorImpl::RetreatIfNotValid(), and llvm::shouldReverseIterate().
operator++() [2/2]
template<typename PtrTy > SmallPtrSetIterator llvm::SmallPtrSetIterator< PtrTy >::operator++ (int) inline
Definition at line 305 of file SmallPtrSet.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallPtrSet.h