LLVM: llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
Contains primitive utilities for defining, calling and handling calls to remote procedures.
#include "llvm/ExecutionEngine/Orc/RPCUtils.h"
Classes
class CanDeserializeCheck
class CanSerializeCheck
class OrcRPCInvalid
class OrcRPCNegotiate
class OrcRPCResponse
Public Member Functions
RPCEndpointBase (ChannelT &C, bool LazyAutoNegotiation)
Construct an RPC instance on a channel.
template<typename Func >
Error negotiateFunction (bool Retry=false)
Negotiate a function id for Func with the other end of the channel.
template<typename Func , typename HandlerT , typename... ArgTs>
Error appendCallAsync (HandlerT Handler, const ArgTs &... Args)
Append a call Func, does not call send on the channel.
Error sendAppendedCalls ()
template<typename Func , typename HandlerT , typename... ArgTs>
Error callAsync (HandlerT Handler, const ArgTs &... Args)
Error handleOne ()
Handle one incoming call.
void abandonPendingResponses ()
Abandon all outstanding result handlers.
template<typename Func >
void removeHandler ()
Remove the handler for the given function.
void clearHandlers ()
Clear all handlers.
Static Public Member Functions
template<typename... ArgTs>
static detail::ReadArgs< ArgTs... > readArgs (ArgTs &... Args)
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args... to values deserialized from the channel.
Protected Types
using WrappedHandlerFn = std::function< Error(ChannelT &, SequenceNumberT)>
Protected Member Functions
FunctionIdT getInvalidFunctionId () const
template<typename Func , typename HandlerT >
void addHandlerImpl (HandlerT Handler)
Add the given handler to the handler map and make it available for autonegotiation and execution.
template<typename Func , typename HandlerT >
void addAsyncHandlerImpl (HandlerT Handler)
Error handleResponse (SequenceNumberT SeqNo)
FunctionIdT handleNegotiate (const std::string &Name)
template<typename Func >
Expected< FunctionIdT > getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid)
template<typename Func , typename HandlerT >
WrappedHandlerFn wrapHandler (HandlerT Handler)
template<typename Func , typename HandlerT >
WrappedHandlerFn wrapAsyncHandler (HandlerT Handler)
Protected Attributes
ChannelT & C
bool LazyAutoNegotiation
RPCFunctionIdAllocator< FunctionIdT > FnIdAllocator
FunctionIdT ResponseId
std::map< std::string, FunctionIdT > LocalFunctionIds
std::map< const char *, FunctionIdT > RemoteFunctionIds
std::map< FunctionIdT, WrappedHandlerFn > Handlers
std::mutex ResponsesMutex
detail::SequenceNumberManager< SequenceNumberT > SequenceNumberMgr
std::map< SequenceNumberT, std::unique_ptr< detail::ResponseHandler< ChannelT > > > PendingResponses
Detailed Description
template<typename ImplT, typename ChannelT, typename FunctionIdT, typename SequenceNumberT>
class llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >
Contains primitive utilities for defining, calling and handling calls to remote procedures.
ChannelT is a bidirectional stream conforming to the RPCChannel interface (see RPCChannel.h), FunctionIdT is a procedure identifier type that must be serializable on ChannelT, and SequenceNumberT is an integral type that will be used to number in-flight function calls.
These utilities support the construction of very primitive RPC utilities. Their intent is to ensure correct serialization and deserialization of procedure arguments, and to keep the client and server's view of the API in sync.
Definition at line 931 of file RPCUtils.h.
Member Typedef Documentation
WrappedHandlerFn
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > using llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::WrappedHandlerFn = std::function<Error(ChannelT &, SequenceNumberT)> protected
Definition at line 1251 of file RPCUtils.h.
Constructor & Destructor Documentation
RPCEndpointBase()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase (ChannelT & C, bool LazyAutoNegotiation) inline
Construct an RPC instance on a channel.
Definition at line 976 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::FnIdAllocator, llvm::orc::rpc::Function< DerivedFunc, RetT(ArgTs...)>::getPrototype(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleNegotiate(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers, Name, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RemoteFunctionIds, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponseId.
Member Function Documentation
abandonPendingResponses()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > void llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses () inline
Abandon all outstanding result handlers.
This will call all currently registered result handlers to receive an "abandoned" error as their argument. This is used internally by the RPC in error situations, but can also be called directly by clients who are disconnecting from the remote and don't or can't expect responses to their outstanding calls. (Especially for outstanding blocking calls, calling this function may be necessary to avoid dead threads).
Definition at line 1112 of file RPCUtils.h.
References llvm::Lock, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::PendingResponses, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponsesMutex, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::SequenceNumberMgr.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync(), llvm::orc::rpc::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse().
addAsyncHandlerImpl()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT > void llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandlerImpl (HandlerT Handler) inline protected
Definition at line 1162 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::FnIdAllocator, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LocalFunctionIds.
addHandlerImpl()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT > void llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addHandlerImpl (HandlerT Handler) inline protected
Add the given handler to the handler map and make it available for autonegotiation and execution.
Definition at line 1149 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::FnIdAllocator, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LocalFunctionIds.
appendCallAsync()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT , typename... ArgTs> Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync (HandlerT Handler, const ArgTs &... Args) inline
Append a call Func, does not call send on the channel.
The first argument specifies a user-defined handler to be run when the function returns. The handler should take an Expected<Func::ReturnType>, or an Error (if Func::ReturnType is void). The handler will be called with an error if the return value is abandoned due to a channel error.
Definition at line 1002 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), assert(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C, llvm::cantFail(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LazyAutoNegotiation, llvm::Lock, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::PendingResponses, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponsesMutex, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::SequenceNumberMgr, and llvm::Error::success().
callAsync()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT , typename... ArgTs> Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::callAsync (HandlerT Handler, const ArgTs &... Args) inline
Definition at line 1061 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C.
clearHandlers()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > void llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::clearHandlers () inline
Clear all handlers.
Definition at line 1136 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers.
getInvalidFunctionId()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > FunctionIdT llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getInvalidFunctionId () const inline protected
Definition at line 1142 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::FnIdAllocator.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getRemoteFunctionId(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleNegotiate().
getRemoteFunctionId()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func > Expected< FunctionIdT > llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid) inline protected
Definition at line 1218 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getInvalidFunctionId(), I, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RemoteFunctionIds.
handleNegotiate()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > FunctionIdT llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleNegotiate (const std::string & Name) inline protected
Definition at line 1209 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getInvalidFunctionId(), I, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LocalFunctionIds, and Name.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase().
handleOne()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne () inline
Handle one incoming call.
Definition at line 1068 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers, I, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponseId.
Referenced by llvm::orc::rpc::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB(), and llvm::orc::rpc::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::handlerLoop().
handleResponse()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse (SequenceNumberT SeqNo) inline protected
Definition at line 1176 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), assert(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C, I, llvm::Lock, llvm::make_error(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::PendingResponses, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponsesMutex, llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::SequenceNumberMgr, llvm::Error::success(), and llvm::sys::SmartMutex< mt_only >::unlock().
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne().
negotiateFunction()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func > Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::negotiateFunction (bool Retry = false) inline
Negotiate a function id for Func with the other end of the channel.
Definition at line 992 of file RPCUtils.h.
readArgs()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename... ArgTs> static detail::ReadArgs< ArgTs... > llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::readArgs (ArgTs &... Args) inline static
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args... to values deserialized from the channel.
E.g.
typedef Function<0, bool, int> Func1;
... bool B; int I; if (auto Err = expect<Func1>(Channel, readArgs(B, I))) /* Handle Args *‍/ ;
Definition at line 1100 of file RPCUtils.h.
removeHandler()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func > void llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::removeHandler () inline
Remove the handler for the given function.
A handler must currently be registered for this function.
Definition at line 1125 of file RPCUtils.h.
References assert(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LocalFunctionIds.
sendAppendedCalls()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::sendAppendedCalls () inline
Definition at line 1058 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C.
wrapAsyncHandler()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT > WrappedHandlerFn llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::wrapAsyncHandler (HandlerT Handler) inline protected
Definition at line 1289 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C, and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponseId.
wrapHandler()
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > template<typename Func , typename HandlerT > WrappedHandlerFn llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::wrapHandler (HandlerT Handler) inline protected
Definition at line 1256 of file RPCUtils.h.
References llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponseId.
Member Data Documentation
C
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > ChannelT& llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::C protected
Definition at line 1325 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::callAsync(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::sendAppendedCalls(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::wrapAsyncHandler().
FnIdAllocator
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > RPCFunctionIdAllocator<FunctionIdT> llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::FnIdAllocator protected
Definition at line 1329 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getInvalidFunctionId(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase().
Handlers
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > std::map<FunctionIdT, WrappedHandlerFn> llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::Handlers protected
Definition at line 1335 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::clearHandlers(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::removeHandler(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase().
LazyAutoNegotiation
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > bool llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LazyAutoNegotiation protected
Definition at line 1327 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync().
LocalFunctionIds
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > std::map<std::string, FunctionIdT> llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::LocalFunctionIds protected
Definition at line 1332 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::addHandlerImpl(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleNegotiate(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::removeHandler().
PendingResponses
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > std::map<SequenceNumberT, std::unique_ptr<detail::ResponseHandler<ChannelT> > > llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::PendingResponses protected
Definition at line 1340 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse().
RemoteFunctionIds
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > std::map<const char *, FunctionIdT> llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RemoteFunctionIds protected
Definition at line 1333 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::getRemoteFunctionId(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase().
ResponseId
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > FunctionIdT llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponseId protected
Definition at line 1331 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleOne(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::RPCEndpointBase(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::wrapAsyncHandler(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::wrapHandler().
ResponsesMutex
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > std::mutex llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::ResponsesMutex protected
Definition at line 1337 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse().
SequenceNumberMgr
template<typename ImplT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > detail::SequenceNumberManager<SequenceNumberT> llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::SequenceNumberMgr protected
Definition at line 1338 of file RPCUtils.h.
Referenced by llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::abandonPendingResponses(), llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::appendCallAsync(), and llvm::orc::rpc::detail::RPCEndpointBase< ImplT, ChannelT, FunctionIdT, SequenceNumberT >::handleResponse().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RPCUtils.h