LLVM: llvm::ScopedHashTable< K, V, KInfo, AllocatorTy > Class Template Reference
llvm::ScopedHashTable< K, V, KInfo, AllocatorTy > Class Template Reference
#include "llvm/ADT/ScopedHashTable.h"
Public Types
using ScopeTy = ScopedHashTableScope< K, V, KInfo, AllocatorTy >
ScopeTy - This is a helpful typedef that allows clients to get easy access to the name of the scope for this hash table.
using size_type = unsigned
using iterator = ScopedHashTableIterator< K, V, KInfo >
Public Member Functions
ScopedHashTable ()=default
ScopedHashTable (AllocatorTy A)
ScopedHashTable (const ScopedHashTable &)=delete
ScopedHashTable & operator= (const ScopedHashTable &)=delete
~ScopedHashTable ()
AllocatorTy & getAllocator ()
Access to the allocator.
const AllocatorTy & getAllocator () const
size_type count (const K &Key) const
Return 1 if the specified key is in the table, 0 otherwise.
V lookup (const K &Key) const
void insert (const K &Key, const V &Val)
iterator end ()
iterator begin (const K &Key)
ScopeTy * getCurScope ()
const ScopeTy * getCurScope () const
void insertIntoScope (ScopeTy *S, const K &Key, const V &Val)
insertIntoScope - This inserts the specified key/value at the specified (possibly not the current) scope.
Friends
class ScopedHashTableScope< K, V, KInfo, AllocatorTy >
Detailed Description
template<typename K, typename V, typename KInfo, typename AllocatorTy>
class llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >
Definition at line 150 of file ScopedHashTable.h.
Member Typedef Documentation
iterator
template<typename K , typename V , typename KInfo , typename AllocatorTy > using llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::iterator = ScopedHashTableIterator<K, V, KInfo>
Definition at line 198 of file ScopedHashTable.h.
ScopeTy
template<typename K , typename V , typename KInfo , typename AllocatorTy > using llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::ScopeTy = ScopedHashTableScope<K, V, KInfo, AllocatorTy>
ScopeTy - This is a helpful typedef that allows clients to get easy access to the name of the scope for this hash table.
Definition at line 154 of file ScopedHashTable.h.
size_type
template<typename K , typename V , typename KInfo , typename AllocatorTy > using llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::size_type = unsigned
Definition at line 155 of file ScopedHashTable.h.
Constructor & Destructor Documentation
ScopedHashTable() [1/3]
template<typename K , typename V , typename KInfo , typename AllocatorTy > llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::ScopedHashTable () default
ScopedHashTable() [2/3]
template<typename K , typename V , typename KInfo , typename AllocatorTy > llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::ScopedHashTable (AllocatorTy A) inline
Definition at line 169 of file ScopedHashTable.h.
ScopedHashTable() [3/3]
template<typename K , typename V , typename KInfo , typename AllocatorTy > llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::ScopedHashTable (const ScopedHashTable< K, V, KInfo, AllocatorTy > &) delete
~ScopedHashTable()
template<typename K , typename V , typename KInfo , typename AllocatorTy > llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::~ScopedHashTable () inline
Definition at line 173 of file ScopedHashTable.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Member Function Documentation
begin()
template<typename K , typename V , typename KInfo , typename AllocatorTy > iterator llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin (const K & Key) inline
Definition at line 202 of file ScopedHashTable.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
count()
template<typename K , typename V , typename KInfo , typename AllocatorTy > size_type llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::count (const K & Key) const inline
Return 1 if the specified key is in the table, 0 otherwise.
Definition at line 182 of file ScopedHashTable.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count().
end()
template<typename K , typename V , typename KInfo , typename AllocatorTy > iterator llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::end () inline
Definition at line 200 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin().
getAllocator() [1/2]
template<typename K , typename V , typename KInfo , typename AllocatorTy > AllocatorTy & llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::getAllocator () inline
Access to the allocator.
Definition at line 178 of file ScopedHashTable.h.
References Allocator.
getAllocator() [2/2]
template<typename K , typename V , typename KInfo , typename AllocatorTy > const AllocatorTy & llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::getAllocator () const inline
Definition at line 179 of file ScopedHashTable.h.
References Allocator.
getCurScope() [1/2]
template<typename K , typename V , typename KInfo , typename AllocatorTy > ScopeTy * llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::getCurScope () inline
Definition at line 209 of file ScopedHashTable.h.
getCurScope() [2/2]
template<typename K , typename V , typename KInfo , typename AllocatorTy > const ScopeTy * llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::getCurScope () const inline
Definition at line 210 of file ScopedHashTable.h.
insert()
template<typename K , typename V , typename KInfo , typename AllocatorTy > void llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insert (const K & Key, const V & Val) inline
Definition at line 194 of file ScopedHashTable.h.
References llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insertIntoScope().
insertIntoScope()
template<typename K , typename V , typename KInfo , typename AllocatorTy > void llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insertIntoScope (ScopeTy * S, const K & Key, const V & Val) inline
insertIntoScope - This inserts the specified key/value at the specified (possibly not the current) scope.
While it is ok to insert into a scope that isn't the current one, it isn't ok to insert underneath an existing value of the specified key.
Definition at line 216 of file ScopedHashTable.h.
References Allocator, assert(), and llvm::ScopedHashTableVal< K, V >::Create().
Referenced by llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insert().
lookup()
template<typename K , typename V , typename KInfo , typename AllocatorTy > V llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup (const K & Key) const inline
Definition at line 186 of file ScopedHashTable.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
operator=()
template<typename K , typename V , typename KInfo , typename AllocatorTy > ScopedHashTable & llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::operator= (const ScopedHashTable< K, V, KInfo, AllocatorTy > &) delete
Friends And Related Function Documentation
ScopedHashTableScope< K, V, KInfo, AllocatorTy >
template<typename K , typename V , typename KInfo , typename AllocatorTy > friend class ScopedHashTableScope< K, V, KInfo, AllocatorTy > friend
Definition at line 144 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ScopedHashTable.h