LLVM: llvm::mca::LSUnitBase Class Reference
llvm::mca::LSUnitBase Class Reference abstract
Abstract base interface for LS (load/store) units in llvm-mca.
#include "llvm/MCA/HardwareUnits/LSUnit.h"
Public Types
enum Status { LSU_AVAILABLE = 0 , LSU_LQUEUE_FULL , LSU_SQUEUE_FULL }
Public Member Functions
LSUnitBase (const MCSchedModel &SM, unsigned LoadQueueSize, unsigned StoreQueueSize, bool AssumeNoAlias)
virtual ~LSUnitBase ()
unsigned getLoadQueueSize () const
Returns the total number of entries in the load queue.
unsigned getStoreQueueSize () const
Returns the total number of entries in the store queue.
unsigned getUsedLQEntries () const
unsigned getUsedSQEntries () const
unsigned assignLQSlot ()
unsigned assignSQSlot ()
bool assumeNoAlias () const
virtual Status isAvailable (const InstRef &IR) const =0
This method checks the availability of the load/store buffers.
virtual unsigned dispatch (const InstRef &IR)=0
Allocates LS resources for instruction IR.
bool isSQEmpty () const
bool isLQEmpty () const
bool isSQFull () const
bool isLQFull () const
bool isValidGroupID (unsigned Index) const
bool isReady (const InstRef &IR) const
Check if a peviously dispatched instruction IR is now ready for execution.
bool isPending (const InstRef &IR) const
Check if instruction IR only depends on memory instructions that are currently executing.
bool isWaiting (const InstRef &IR) const
Check if instruction IR is still waiting on memory operations, and the wait time is still unknown.
bool hasDependentUsers (const InstRef &IR) const
const MemoryGroup & getGroup (unsigned Index) const
MemoryGroup & getGroup (unsigned Index)
unsigned createMemoryGroup ()
virtual void onInstructionExecuted (const InstRef &IR)
virtual void onInstructionIssued (const InstRef &IR)
virtual void cycleEvent ()
void dump () const
Public Member Functions inherited from llvm::mca::HardwareUnit
HardwareUnit ()=default
virtual ~HardwareUnit ()
Detailed Description
Abstract base interface for LS (load/store) units in llvm-mca.
Definition at line 167 of file LSUnit.h.
Member Enumeration Documentation
Status
enum llvm::mca::LSUnitBase::Status
Enumerator
LSU_AVAILABLE
LSU_LQUEUE_FULL
LSU_SQUEUE_FULL
Definition at line 217 of file LSUnit.h.
Constructor & Destructor Documentation
LSUnitBase()
llvm::mca::LSUnitBase::LSUnitBase (const MCSchedModel & SM, unsigned LoadQueueSize, unsigned StoreQueueSize, bool AssumeNoAlias)
Definition at line 24 of file LSUnit.cpp.
References llvm::MCProcResourceDesc::BufferSize, llvm::MCSchedModel::getExtraProcessorInfo(), llvm::MCSchedModel::getProcResource(), llvm::MCSchedModel::hasExtraProcessorInfo(), llvm::MCExtraProcessorInfo::LoadQueueID, and llvm::MCExtraProcessorInfo::StoreQueueID.
~LSUnitBase()
llvm::mca::LSUnitBase::~LSUnitBase () virtual
Definition at line 42 of file LSUnit.cpp.
Member Function Documentation
assignLQSlot()
unsigned llvm::mca::LSUnitBase::assignLQSlot () inline
Definition at line 212 of file LSUnit.h.
Referenced by llvm::mca::LSUnit::dispatch().
assignSQSlot()
unsigned llvm::mca::LSUnitBase::assignSQSlot () inline
Definition at line 213 of file LSUnit.h.
Referenced by llvm::mca::LSUnit::dispatch().
assumeNoAlias()
bool llvm::mca::LSUnitBase::assumeNoAlias () const inline
Definition at line 215 of file LSUnit.h.
References llvm::NoAlias.
Referenced by llvm::mca::LSUnit::dispatch().
createMemoryGroup()
unsigned llvm::mca::LSUnitBase::createMemoryGroup () inline
Definition at line 286 of file LSUnit.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by llvm::mca::LSUnit::dispatch().
cycleEvent()
void llvm::mca::LSUnitBase::cycleEvent () virtual
Definition at line 44 of file LSUnit.cpp.
References G.
Referenced by llvm::mca::Scheduler::cycleEvent().
dispatch()
virtual unsigned llvm::mca::LSUnitBase::dispatch (const InstRef & IR) pure virtual
Allocates LS resources for instruction IR.
This method assumes that a previous call to isAvailable(IR) succeeded with a LSUnitBase::Status value of LSU_AVAILABLE. Returns the GroupID associated with this instruction. That value will be used to set the LSUTokenID field in class Instruction.
Implemented in llvm::mca::LSUnit.
dump()
void llvm::mca::LSUnitBase::dump () const
Definition at line 50 of file LSUnit.cpp.
References llvm::dbgs(), getLoadQueueSize(), llvm::mca::MemoryGroup::getNumExecuted(), llvm::mca::MemoryGroup::getNumExecutedPredecessors(), llvm::mca::MemoryGroup::getNumExecuting(), llvm::mca::MemoryGroup::getNumExecutingPredecessors(), llvm::mca::MemoryGroup::getNumInstructions(), llvm::mca::MemoryGroup::getNumPredecessors(), getStoreQueueSize(), getUsedLQEntries(), and getUsedSQEntries().
getGroup() [1/2]
MemoryGroup & llvm::mca::LSUnitBase::getGroup (unsigned Index) inline
Definition at line 281 of file LSUnit.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and isValidGroupID().
getGroup() [2/2]
const MemoryGroup & llvm::mca::LSUnitBase::getGroup (unsigned Index) const inline
Definition at line 276 of file LSUnit.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and isValidGroupID().
Referenced by llvm::mca::LSUnit::dispatch(), hasDependentUsers(), isPending(), isReady(), and isWaiting().
getLoadQueueSize()
unsigned llvm::mca::LSUnitBase::getLoadQueueSize () const inline
Returns the total number of entries in the load queue.
Definition at line 205 of file LSUnit.h.
Referenced by dump().
getStoreQueueSize()
unsigned llvm::mca::LSUnitBase::getStoreQueueSize () const inline
Returns the total number of entries in the store queue.
Definition at line 208 of file LSUnit.h.
Referenced by dump().
getUsedLQEntries()
unsigned llvm::mca::LSUnitBase::getUsedLQEntries () const inline
Definition at line 210 of file LSUnit.h.
Referenced by dump().
getUsedSQEntries()
unsigned llvm::mca::LSUnitBase::getUsedSQEntries () const inline
Definition at line 211 of file LSUnit.h.
Referenced by dump().
hasDependentUsers()
bool llvm::mca::LSUnitBase::hasDependentUsers (const InstRef & IR) const inline
Definition at line 270 of file LSUnit.h.
References getGroup(), llvm::mca::MemoryGroup::getNumSuccessors(), IR, and llvm::mca::MemoryGroup::isExecuted().
Referenced by llvm::mca::Scheduler::issueInstruction().
isAvailable()
virtual Status llvm::mca::LSUnitBase::isAvailable (const InstRef & IR) const pure virtual
This method checks the availability of the load/store buffers.
Returns LSU_AVAILABLE if there are enough load/store queue entries to accomodate instruction IR. By default, LSU_AVAILABLE is returned if IR is not a memory operation.
Implemented in llvm::mca::LSUnit.
isLQEmpty()
bool llvm::mca::LSUnitBase::isLQEmpty () const inline
Definition at line 239 of file LSUnit.h.
isLQFull()
bool llvm::mca::LSUnitBase::isLQFull () const inline
Definition at line 241 of file LSUnit.h.
Referenced by llvm::mca::LSUnit::isAvailable().
isPending()
bool llvm::mca::LSUnitBase::isPending (const InstRef & IR) const inline
Check if instruction IR only depends on memory instructions that are currently executing.
Definition at line 256 of file LSUnit.h.
References getGroup(), IR, and llvm::mca::MemoryGroup::isPending().
Referenced by llvm::mca::Scheduler::analyzeDataDependencies(), and llvm::mca::Scheduler::dispatch().
isReady()
bool llvm::mca::LSUnitBase::isReady (const InstRef & IR) const inline
Check if a peviously dispatched instruction IR is now ready for execution.
Definition at line 248 of file LSUnit.h.
References getGroup(), IR, and llvm::mca::MemoryGroup::isReady().
Referenced by llvm::mca::Scheduler::dispatch().
isSQEmpty()
bool llvm::mca::LSUnitBase::isSQEmpty () const inline
Definition at line 238 of file LSUnit.h.
isSQFull()
bool llvm::mca::LSUnitBase::isSQFull () const inline
Definition at line 240 of file LSUnit.h.
Referenced by llvm::mca::LSUnit::isAvailable().
isValidGroupID()
bool llvm::mca::LSUnitBase::isValidGroupID (unsigned Index) const inline
Definition at line 243 of file LSUnit.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by getGroup(), and llvm::mca::LSUnit::onInstructionExecuted().
isWaiting()
bool llvm::mca::LSUnitBase::isWaiting (const InstRef & IR) const inline
Check if instruction IR is still waiting on memory operations, and the wait time is still unknown.
Definition at line 264 of file LSUnit.h.
References getGroup(), IR, and llvm::mca::MemoryGroup::isWaiting().
Referenced by llvm::mca::Scheduler::dispatch().
onInstructionExecuted()
void llvm::mca::LSUnitBase::onInstructionExecuted (const InstRef & IR) virtual
Reimplemented in llvm::mca::LSUnit.
Definition at line 162 of file LSUnit.cpp.
References assert(), llvm::dbgs(), IR, LLVM_DEBUG, llvm::mca::InstrDesc::MayLoad, and llvm::mca::InstrDesc::MayStore.
onInstructionIssued()
virtual void llvm::mca::LSUnitBase::onInstructionIssued (const InstRef & IR) inline virtual
Definition at line 295 of file LSUnit.h.
References IR.
The documentation for this class was generated from the following files:
include/llvm/MCA/HardwareUnits/LSUnit.h
lib/MCA/HardwareUnits/LSUnit.cpp