LLVM: llvm::SmallVectorImpl< T > Class Template Reference
llvm::SmallVectorImpl< T > Class Template Reference
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorTemplateBase< T, bool >.
Inherited by llvm::SmallVector< std::unique_ptr< DWARFUnit >, 1 >, llvm::SmallVector< BasicBlock *, IsPostDom ? 4 :1 >, llvm::SmallVector< BlockT *, IsPostDom ? 4 :1 >, llvm::SmallVector< BoUpSLP::EdgeInfo, 1 >, llvm::SmallVector< llvm::MCFixup, FixupsSize >, llvm::SmallVector< char, ContentsSize >, llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >, llvm::SmallVector< std::pair< KeyT, ValueT >, N >, llvm::SmallVector< char, InternalLen >, llvm::SmallVector< ScheduleData *, 8 >, llvm::SmallVector< Instruction *, 16 >, llvm::SmallVector< llvm::SUnit *, 8 >, llvm::SmallVector< LoopVector, 4 >, llvm::SmallVector< std::pair< BlockFrequency, unsigned >, 4 >, llvm::SmallVector< AllocaInfo, 4 >, llvm::SmallVector< ParamInfo, 4 >, llvm::SmallVector< CallInst *, 16 >, llvm::SmallVector< unsigned, N >, llvm::SmallVector< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults), 4 >, llvm::SmallVector< llvm::ForwardedRegister, 1 >, llvm::SmallVector< MILOHDirective, 32 >, llvm::SmallVector< const llvm::MachineInstr *, 3 >, llvm::SmallVector< unsigned, 2 >, llvm::SmallVector< std::pair< unsigned, llvm::MCSymbol * >, 4 >, llvm::SmallVector< llvm::BasicBlockInfo, 8 >, llvm::SmallVector< FCmpLibcallsList, 0 >, llvm::SmallVector< int, 0 >, llvm::SmallVector< MCPhysReg, 16 >, llvm::SmallVector< AnalysisID, 8 >, llvm::SmallVector< AnalysisID, 2 >, llvm::SmallVector< AnalysisID, 0 >, llvm::SmallVector< std::pair< AtomType, Form >, 3 >, llvm::SmallVector< FreeList *, 8 >, llvm::SmallVector< llvm::AsmPrinter::HandlerInfo, 1 >, llvm::SmallVector< llvm::AsmPrinter::XRayFunctionEntry, 4 >, llvm::SmallVector< llvm::WeakTrackingVH, 4 >, llvm::SmallVector< AbstractAttribute *, 64 >, llvm::SmallVector< VariableGEPIndex, 4 >, llvm::SmallVector< llvm::BitCodeAbbrevOp, 32 >, llvm::SmallVector< BitValue, DefaultBitN >, llvm::SmallVector< Block, 8 >, llvm::SmallVector< Weight, 4 >, llvm::SmallVector< std::pair< BlockNode, BlockMass >, 4 >, llvm::SmallVector< BlockNode, 4 >, llvm::SmallVector< BlockMass, 1 >, llvm::SmallVector< void *, 4 >, llvm::SmallVector< std::pair< void *, size_t >, 0 >, llvm::SmallVector< uint32_t, 16 >, llvm::SmallVector< llvm::CCValAssign, 4 >, llvm::SmallVector< llvm::ISD::ArgFlagsTy, 4 >, llvm::SmallVector< ByValInfo, 4 >, llvm::SmallVector< llvm::LazyCallGraph::RefSCC *, N >, llvm::SmallVector< llvm::LazyCallGraph::SCC *, N >, llvm::SmallVector< llvm::Register, 4 >, llvm::SmallVector< FileInfo, 4 >, llvm::SmallVector< CVGlobalVariable, 1 >, llvm::SmallVector< const llvm::DISubprogram *, N >, llvm::SmallVector< const llvm::DICompositeType *, 4 >, llvm::SmallVector< const llvm::DILocation *, 1 >, llvm::SmallVector< LocalVariable, 1 >, llvm::SmallVector< LexicalBlock *, 1 >, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 1 >, llvm::SmallVector< LocalVarDefRange, 1 >, llvm::SmallVector< consthoist::ConstantInfo, 8 >, llvm::SmallVector< ConstantPoolEntry, 4 >, llvm::SmallVector< llvm::SDNode *, 128 >, llvm::SmallVector< llvm::Metadata *, 4 >, llvm::SmallVector< llvm::TypedTrackingMDRef, 4 >, llvm::SmallVector< llvm::DIEAbbrevData, 12 >, llvm::SmallVector< llvm::DILineInfo, 4 >, llvm::SmallVector< AttributeSpec, 8 >, llvm::SmallVector< llvm::DWARFFormValue, 3 >, llvm::SmallVector< LocationList, 4 >, llvm::SmallVector< char, 4 >, llvm::SmallVector< llvm::DWARFDebugLoc::Entry, 2 >, llvm::SmallVector< llvm::DWARFDebugLoclists::Entry, 2 >, llvm::SmallVector< Entry, 4 >, llvm::SmallVector< llvm::DWARFDebugNames::NameIndex, 0 >, llvm::SmallVector< CompUnitEntry, 0 >, llvm::SmallVector< TypeUnitEntry, 0 >, llvm::SmallVector< AddressEntry, 0 >, llvm::SmallVector< SymTableEntry, 0 >, llvm::SmallVector< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > >, 0 >, llvm::SmallVector< unsigned char, 8 >, llvm::SmallVector< LayoutAlignElem, 16 >, llvm::SmallVector< PointerAlignElem, 8 >, llvm::SmallVector< unsigned, 8 >, llvm::SmallVector< FrameIndexExpr, 1 >, llvm::SmallVector< int64_t, 1 >, llvm::SmallVector< llvm::DICompileUnit *, 8 >, llvm::SmallVector< llvm::DISubprogram *, 8 >, llvm::SmallVector< llvm::DIGlobalVariableExpression *, 8 >, llvm::SmallVector< llvm::DIType *, 8 >, llvm::SmallVector< llvm::DIScope *, 8 >, llvm::SmallVector< llvm::DbgValueLoc, 1 >, llvm::SmallVector< llvm::DebugLocStream::List, 4 >, llvm::SmallVector< llvm::DebugLocStream::Entry, 32 >, llvm::SmallVector< std::string, 32 >, llvm::SmallVector< llvm::Init *, 16 >, llvm::SmallVector< llvm::DiagnosticInfoOptimizationBase::Argument, 4 >, llvm::SmallVector< UpdateT, 4 >, llvm::SmallVector< NodePtr, 2 >, llvm::SmallVector< llvm::DomTreeNodeBase, 8 >, llvm::SmallVector< llvm::cfg::Update, 16 >, llvm::SmallVector< llvm::MachineInstr *, 8 >, llvm::SmallVector< NodeT *, IsPostDom ? 4 :1 >, llvm::SmallVector< llvm::RangeSpan, 2 >, llvm::SmallVector< std::unique_ptr< llvm::DbgEntity >, 64 >, llvm::SmallVector< const llvm::DISubprogram *, 16 >, llvm::SmallVector< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * >, 1 >, llvm::SmallVector< llvm::DwarfExpression::Register, 2 >, llvm::SmallVector< std::unique_ptr< llvm::DwarfCompileUnit >, 1 >, llvm::SmallVector< llvm::RangeSpanList, 1 >, llvm::SmallVector< llvm::DbgVariable *, 8 >, llvm::SmallVector< llvm::SmallVector< unsigned, 8 >, 4 >, llvm::SmallVector< std::string, 4 >, llvm::SmallVector< llvm::Function *, 4 >, llvm::SmallVector< std::unique_ptr< llvm::GlobalVariable >, 32 >, llvm::SmallVector< llvm::DomainValue *, 16 >, llvm::SmallVector< LiveRegsDVInfo, 4 >, llvm::SmallVector< std::unique_ptr< llvm::Module >, 1 >, llvm::SmallVector< unsigned, 4 >, llvm::SmallVector< llvm::Value *, 16 >, llvm::SmallVector< llvm::ISD::ArgFlagsTy, 16 >, llvm::SmallVector< unsigned, 16 >, llvm::SmallVector< llvm::ISD::InputArg, 4 >, llvm::SmallVector< std::pair< std::string, GCOVCoverage >, 4 >, llvm::SmallVector< unsigned, 32 >, llvm::SmallVector< T *, 8 >, llvm::SmallVector< unsigned, 50 >, llvm::SmallVector< llvm::FunctionLoweringInfo::LiveOutInfo, 0 >, llvm::SmallVector< std::unique_ptr< llvm::GCStrategy >, 1 >, llvm::SmallVector< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator >, 32 >, llvm::SmallVector< llvm::DenseMap, 32 >, llvm::SmallVector< llvm::GCNRegPressure, 32 >, llvm::SmallVector< llvm::GCOVEdge *, 16 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVFunction >, 16 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVBlock >, 16 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVEdge >, 16 >, llvm::SmallVector< llvm::MachineInstr *, N >, llvm::SmallVector< llvm::GISelChangeObserver *, 4 >, llvm::SmallVector< std::pair< llvm::Value *, llvm::Constant * >, N >, llvm::SmallVector< llvm::Instruction *, 8 >, llvm::SmallVector< std::pair< llvm::Instruction *, unsigned >, 4 >, llvm::SmallVector< uint32_t, 4 >, llvm::SmallVector< llvm::BasicBlock *, 32 >, llvm::SmallVector< NodePtr, 1 >, llvm::SmallVector< HexagonInstr, HEXAGON_PRESHUFFLE_PACKET_SIZE >, llvm::SmallVector< NodeTy *, IsPostDom ? 4 :1 >, llvm::SmallVector< llvm::BasicBlock *, 1 >, llvm::SmallVector< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > >, 4 >, llvm::SmallVector< InlineGraphNode *, 8 >, llvm::SmallVector< uintptr_t, 20 >, llvm::SmallVector< T, 0 >, llvm::SmallVector< llvm::Instruction *, 2 >, llvm::SmallVector< const char *, 0 >, llvm::SmallVector< llvm::AllocaInst *, 4 >, llvm::SmallVector< llvm::WeakTrackingVH, 8 >, llvm::SmallVector< llvm::CallSite, 8 >, llvm::SmallVector< llvm::BasicBlock *, 4 >, llvm::SmallVector< llvm::Instruction *, 4 >, llvm::SmallVector< llvm::PHINode *, 8 >, llvm::SmallVector< std::pair< llvm::SlotIndex, llvm::SlotIndex >, 8 >, llvm::SmallVector< llvm::Instruction *, 256 >, llvm::SmallVector< MachineInstr *, 4 >, llvm::SmallVector< RegUnitInfo, 4 >, llvm::SmallVector< BlockInterference, 8 >, llvm::SmallVector< llvm::AssertingVH< const llvm::BasicBlock >, N >, llvm::SmallVector< llvm::Instruction *, 64 >, llvm::SmallVector< llvm::Loop *, N >, llvm::SmallVector< llvm::MCSymbol *, 1 >, llvm::SmallVector< llvm::SEHHandler, 1 >, llvm::SmallVector< llvm::LazyCallGraph::RefSCC *, 16 >, llvm::SmallVector< llvm::Function *, N >, llvm::SmallVector< Edge, 4 >, llvm::SmallVector< llvm::LazyCallGraph::SCC *, 4 >, llvm::SmallVector< llvm::LazyCallGraph::Node *, 1 >, llvm::SmallVector< llvm::LegalizeRule, 2 >, llvm::SmallVector< llvm::DenseMap, 1 >, llvm::SmallVector< SizeChangeStrategy, 1 >, llvm::SmallVector< SizeAndActionsVec, 1 >, llvm::SmallVector< std::pair< bool, llvm::StringRef >, 4 >, llvm::SmallVector< llvm::LexicalScope *, 4 >, llvm::SmallVector< InsnRange, 4 >, llvm::SmallVector< llvm::LiveInterval *, 4 >, llvm::SmallVector< llvm::LiveInterval *, 0 >, llvm::SmallVector< llvm::SlotIndex, 8 >, llvm::SmallVector< const uint32_t *, 8 >, llvm::SmallVector< std::pair< unsigned, unsigned >, 8 >, llvm::SmallVector< llvm::LiveRange *, 0 >, llvm::SmallVector< MCPhysReg, 8 >, llvm::SmallVector< Segment, 2 >, llvm::SmallVector< VNInfo *, 2 >, llvm::SmallVector< LiveOutPair, 0 >, llvm::SmallVector< LiveInBlock, 16 >, llvm::SmallVector< llvm::LiveRange::Segment, 16 >, llvm::SmallVector< IndexMaskPair, 8 >, llvm::SmallVector< llvm::LiveVariables::VarInfo, 0 >, llvm::SmallVector< MBBInfo, 4 >, llvm::SmallVector< VPlanPtr, 4 >, llvm::SmallVector< RuntimePointerChecking::PointerCheck, 4 >, llvm::SmallVector< llvm::MCSection *, 16 >, llvm::SmallVector< llvm::AsmToken, 1 >, llvm::SmallVector< llvm::MCAsmParser::MCPendingError, 0 >, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 2 >, llvm::SmallVector< std::string, 3 >, llvm::SmallVector< llvm::MCDwarfFile, 3 >, llvm::SmallVector< llvm::MCDataFragment *, 4 >, llvm::SmallVector< llvm::MCOperand, 8 >, llvm::SmallVector< llvm::object::OwningBinary< llvm::object::Archive >, 2 >, llvm::SmallVector< std::unique_ptr< llvm::MemoryBuffer >, 2 >, llvm::SmallVector< std::unique_ptr< llvm::object::ObjectFile >, 2 >, llvm::SmallVector< llvm::MCLOHDirective, 32 >, llvm::SmallVector< llvm::MCSymbol *, 3 >, llvm::SmallVector< llvm::MCSymbol *, 2 >, llvm::SmallVector< PendingMCFixup, 2 >, llvm::SmallVector< std::pair< unsigned, llvm::MCFragment * >, 1 >, llvm::SmallVector< std::pair< MCSectionSubPair, MCSectionSubPair >, 4 >, llvm::SmallVector< std::pair< unsigned, llvm::TypedTrackingMDRef >, 2 >, llvm::SmallVector< Attachment, 1 >, llvm::SmallVector< llvm::StringRef, 8 >, llvm::SmallVector< llvm::MachineBasicBlock *, IsPostDom ? 4 :1 >, llvm::SmallVector< CriticalEdge, 32 >, llvm::SmallVector< llvm::MachineBasicBlock *, N >, llvm::SmallVector< std::pair< int, int64_t >, 32 >, llvm::SmallVector< VariableDbgInfo, 4 >, llvm::SmallVector< llvm::MachineOperand, 4 >, llvm::SmallVector< std::pair< llvm::PointerUnion, llvm::MachineOperand * >, 0 >, llvm::SmallVector< std::string, 0 >, llvm::SmallVector< std::pair< unsigned, llvm::SmallVector< unsigned, 4 > >, 0 >, llvm::SmallVector< LLT, 0 >, llvm::SmallVector< llvm::MachineTraceMetrics::FixedBlockInfo, 4 >, llvm::SmallVector< unsigned, 0 >, llvm::SmallVector< llvm::MachineTraceMetrics::TraceBlockInfo, 4 >, llvm::SmallVector< llvm::MachineTraceMetrics::LiveInReg, 4 >, llvm::SmallVector< std::string *, 8 >, llvm::SmallVector< llvm::Instruction *, 16 >, llvm::SmallVector< llvm::MemoryDepChecker::Dependence, 8 >, llvm::SmallVector< DefPath, 32 >, llvm::SmallVector< llvm::WeakVH, 16 >, llvm::SmallVector< llvm::AssertingVH< llvm::MemoryPhi >, N >, llvm::SmallVector< Inst, 7 >, llvm::SmallVector< bool, 4 >, llvm::SmallVector< std::unique_ptr< llvm::MipsOptionRecord >, 8 >, llvm::SmallVector< llvm::MCSymbol *, 4 >, llvm::SmallVector< llvm::MachineInstr *, 2 >, llvm::SmallVector< const llvm::Value *, 4 >, llvm::SmallVector< std::string, 8 >, llvm::SmallVector< llvm::Pass *, 16 >, llvm::SmallVector< llvm::PMDataManager *, 8 >, llvm::SmallVector< llvm::ImmutablePass *, 16 >, llvm::SmallVector< llvm::SUnit *, 7 >, llvm::SmallVector< unsigned, 3 >, llvm::SmallVector< std::function< void(llvm::PassManager &, OptimizationLevel)>, 2 >, llvm::SmallVector< std::function< void(llvm::PassManager &)>, 2 >, llvm::SmallVector< std::function< void(llvm::AnalysisManager &)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)>, 2 >, llvm::SmallVector< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >, bool VerifyEachPass, bool DebugLogging)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)>, 2 >, llvm::SmallVector< InsertedPass, 4 >, llvm::SmallVector< llvm::unique_function< BeforePassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterPassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterPassInvalidatedFunc >, 4 >, llvm::SmallVector< llvm::unique_function< BeforeAnalysisFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterAnalysisFunc >, 4 >, llvm::SmallVector< ValueInfo, 32 >, llvm::SmallVector< llvm::AssertingVH< llvm::Function >, N >, llvm::SmallVector< llvm::PredicateBase *, 4 >, llvm::SmallVector< char, 32 >, llvm::SmallVector< PrintModuleDesc, 2 >, llvm::SmallVector< llvm::Type *, 16 >, llvm::SmallVector< LiveRegsDefInfo, 4 >, llvm::SmallVector< MBBDefsInfo, 4 >, llvm::SmallVector< llvm::SMLoc, 4 >, llvm::SmallVector< llvm::Init *, 0 >, llvm::SmallVector< llvm::RecordVal, 0 >, llvm::SmallVector< std::pair< llvm::Record *, llvm::SMRange >, 0 >, llvm::SmallVector< llvm::Init *, 4 >, llvm::SmallVector< std::unique_ptr< InsertPoint >, 2 >, llvm::SmallVector< ScavengedInfo, 2 >, llvm::SmallVector< int, 8 >, llvm::SmallVector< llvm::Register, 8 >, llvm::SmallVector< MCPhysReg, 4 >, llvm::SmallVector< llvm::RegisterMaskPair, 8 >, llvm::SmallVector< llvm::EVT, 4 >, llvm::SmallVector< llvm::MVT, 4 >, llvm::SmallVector< uint64_t, DefaultProcResSize >, llvm::SmallVector< SID, 2 >, llvm::SmallVector< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry >, 8 >, llvm::SmallVector< SectionEntry, 64 >, llvm::SmallVector< llvm::RuntimeDyldMachO::EHFrameRelatedSections, 2 >, llvm::SmallVector< llvm::RuntimePointerChecking::PointerInfo, 2 >, llvm::SmallVector< llvm::RuntimePointerChecking::CheckingPtrGroup, 2 >, llvm::SmallVector< PointerCheck, 4 >, llvm::SmallVector< SCEVInsertPointGuard *, 8 >, llvm::SmallVector< const llvm::SCEV *, 8 >, llvm::SmallVector< const llvm::SCEVPredicate *, 16 >, llvm::SmallVector< llvm::SDDbgValue *, 32 >, llvm::SmallVector< llvm::SDDbgLabel *, 4 >, llvm::SmallVector< llvm::SIMachineFunctionInfo::SGPRSpillVGPRCSR, 2 >, llvm::SmallVector< MCPhysReg, 32 >, llvm::SmallVector< llvm::SMFixIt, 4 >, llvm::SmallVector< llvm::AllocaInst *, 16 >, llvm::SmallVector< llvm::PHINode *, 2 >, llvm::SmallVector< llvm::SelectInst *, 2 >, llvm::SmallVector< RewriteInfo, 4 >, llvm::SmallVector< llvm::Use *, 4 >, llvm::SmallVector< llvm::SDep, 4 >, llvm::SmallVector< ExitNotTakenInfo, 1 >, llvm::SmallVector< RootData, 8 >, llvm::SmallVector< TreeData, 16 >, llvm::SmallVector< SMSNode, 8 >, llvm::SmallVector< std::pair< llvm::SUnit *, llvm::SUnit * >, 16 >, llvm::SmallVector< llvm::sys::MemoryBlock, 16 >, llvm::SmallVector< FreeMemBlock, 16 >, llvm::SmallVector< llvm::SDValue, 8 >, llvm::SmallVector< const llvm::Value *, 16 >, llvm::SmallVector< const llvm::GCRelocateInst *, 16 >, llvm::SmallVector< IdxMBBPair, 8 >, llvm::SmallVector< char, 0 >, llvm::SmallVector< ValueT, 8 >, llvm::SmallVector< llvm::Value *, 64 >, llvm::SmallVector< llvm::BasicBlock *, 64 >, llvm::SmallVector< llvm::BlockFrequency, 8 >, llvm::SmallVector< llvm::SplitAnalysis::BlockInfo, 8 >, llvm::SmallVector< Location, 8 >, llvm::SmallVector< LiveOutReg, 8 >, llvm::SmallVector< const llvm::CallInst *, 10 >, llvm::SmallVector< const Value *, 1 >, llvm::SmallVector< llvm::SmallPtrSet< llvm::SUnit *, 4 >, 10 >, llvm::SmallVector< llvm::SmallVector< int, 4 >, 16 >, llvm::SmallVector< BitTestCase, 3 >, llvm::SmallVector< uint32_t, 8 >, llvm::SmallVector< llvm::DefsetRecord *, 2 >, llvm::SmallVector< llvm::ISD::OutputArg, 32 >, llvm::SmallVector< llvm::SDValue, 32 >, llvm::SmallVector< llvm::ISD::InputArg, 32 >, llvm::SmallVector< llvm::SDValue, 4 >, llvm::SmallVector< llvm::Timer *, 8 >, llvm::SmallVector< llvm::Entry, 16 >, llvm::SmallVector< llvm::Entry, 128 >, llvm::SmallVector< llvm::TruncInst *, 4 >, llvm::SmallVector< uint8_t, 32 >, llvm::SmallVector< llvm::VPBlockBase *, 1 >, llvm::SmallVector< llvm::VPBasicBlock *, 8 >, llvm::SmallVector< llvm::VPValue *, 2 >, llvm::SmallVector< llvm::VPUser *, 1 >, llvm::SmallVector< llvm::VPValue *, 4 >, llvm::SmallVector< VPBlockBase *, IsPostDom ? 4 :1 >, llvm::SmallVector< MultiNodeOpTy, 4 >, llvm::SmallVector< std::pair< uint64_t, bool >, 4 >, llvm::SmallVector< uint64_t, 4 >, llvm::SmallVector< llvm::CxxUnwindMapEntry, 4 >, llvm::SmallVector< llvm::WinEHTryBlockMapEntry, 4 >, llvm::SmallVector< llvm::SEHUnwindMapEntry, 4 >, llvm::SmallVector< llvm::ClrEHUnwindMapEntry, 4 >, llvm::SmallVector< llvm::WinEHHandlerType, 1 >, llvm::SmallVector< llvm::cflaa::ExternalRelation, 8 >, llvm::SmallVector< llvm::cflaa::ExternalAttribute, 8 >, llvm::SmallVector< llvm::Value *, 4 >, llvm::SmallVector< llvm::cl::OptionCategory *, 1 >, llvm::SmallVector< llvm::cl::Option *, 4 >, llvm::SmallVector< llvm::cl::OptionEnumValue, 4 >, llvm::SmallVector< llvm::ArrayRef< uint8_t >, 2 >, llvm::SmallVector< llvm::codeview::TypeIndex, MaxArgs >, llvm::SmallVector< RecordLimit, 2 >, llvm::SmallVector< llvm::codeview::GloballyHashedType, 2 >, llvm::SmallVector< std::pair< uint32_t, llvm::codeview::TypeIndex >, 8 >, llvm::SmallVector< ConstantUser, 8 >, llvm::SmallVector< RebasedConstantInfo, 4 >, llvm::SmallVector< llvm::CoroEndInst *, 4 >, llvm::SmallVector< llvm::CoroSizeInst *, 2 >, llvm::SmallVector< llvm::CoroSuspendInst *, 4 >, llvm::SmallVector< const llvm::coverage::CoverageSegment *, 4 >, llvm::SmallVector< llvm::detail::PtrUseVisitorBase::UseToVisit, 8 >, llvm::SmallVector< uint64_t, 2 >, llvm::SmallVector< llvm::fuzzerop::SourcePred, 2 >, llvm::SmallVector< State, 16 >, llvm::SmallVector< uint64_t, 16 >, llvm::SmallVector< std::unique_ptr< llvm::mca::HardwareUnit >, 4 >, llvm::SmallVector< std::unique_ptr< llvm::mca::Instruction >, 16 >, llvm::SmallVector< uint64_t, 8 >, llvm::SmallVector< llvm::mca::WriteDescriptor, 4 >, llvm::SmallVector< llvm::mca::ReadDescriptor, 4 >, llvm::SmallVector< std::pair< uint64_t, llvm::mca::ResourceUsage >, 4 >, llvm::SmallVector< llvm::mca::WriteState, 4 >, llvm::SmallVector< llvm::mca::ReadState, 4 >, llvm::SmallVector< std::pair< ResourceRef, llvm::mca::ResourceCycles >, 4 >, llvm::SmallVector< llvm::mca::MemoryGroup *, 4 >, llvm::SmallVector< llvm::mca::InstRef, 8 >, llvm::SmallVector< std::unique_ptr< llvm::mca::Stage >, 8 >, llvm::SmallVector< RegisterMappingTracker, 4 >, llvm::SmallVector< std::pair< llvm::mca::ReadState *, int >, 4 >, llvm::SmallVector< SectionInfo, 32 >, llvm::SmallVector< NodeState, 16 >, llvm::SmallVector< const char *, 1 >, llvm::SmallVector< LoadCommandInfo, 4 >, llvm::SmallVector< StringRef, 1 >, llvm::SmallVector< const char *, 2 >, llvm::SmallVector< Arg *, 16 >, llvm::SmallVector< std::unique_ptr< llvm::opt::Arg >, 16 >, llvm::SmallVector< const char *, 16 >, llvm::SmallVector< InjectedSourceDescriptor, 2 >, llvm::SmallVector< size_t, 8 >, llvm::SmallVector< llvm::remarks::Argument, 5 >, llvm::SmallVector< llvm::safestack::StackColoring::LiveRange, 8 >, llvm::SmallVector< StackRegion, 16 >, llvm::SmallVector< StackObject, 8 >, llvm::SmallVector< const SamplesWithLoc *, 20 >, llvm::SmallVector< std::unique_ptr< TreeEntry >, 8 >, llvm::SmallVector< unique_value, 8 >, llvm::SmallVector< ExternalUser, 16 >, llvm::SmallVector< ScheduleData *, 4 >, llvm::SmallVector< Value *, 8 >, llvm::SmallVector< llvm::slpvectorizer::BoUpSLP::EdgeInfo, 1 >, llvm::SmallVector< SmallVector< Value *, 8 >, 2 >, llvm::SmallVector< llvm::SmallVector, 4 >, llvm::SmallVector< llvm::PHINode *, N >, llvm::SmallVector< llvm::SelectInst *, N >, llvm::SmallVector< Slice, 8 >, llvm::SmallVector< llvm::Use *, 8 >, llvm::SmallVector< Slice *, 4 >, llvm::SmallVector< IntrusiveRefCntPtr< FileSystem >, 1 >, llvm::SmallVector< ValType, 1 >, llvm::SmallVector< ValType, 4 >, llvm::SmallVector< TrieNode *, 4 >, llvm::SmallVector< int, 4 >, llvm::SmallVector< SimpleKey, 4 >, and llvm::SmallVector< T, N >.
Public Types
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
SmallVectorImpl (const SmallVectorImpl &)=delete
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize (size_type N, const T &NV)
void reserve (size_type N)
LLVM_NODISCARD T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename in_iter , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>::type>
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, const T &Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< T > IL)
void assign (size_type NumElts, const T &Elt)
template<typename in_iter , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>::type>
void assign (in_iter in_start, in_iter in_end)
void assign (std::initializer_list< T > IL)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, const T &Elt)
template<typename ItTy , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>::type>
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Protected Member Functions
SmallVectorImpl (unsigned N)
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinCapacity, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
Protected Member Functions inherited from llvm::SmallVectorBase
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void grow_pod (void *FirstEl, size_t MinCapacity, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Additional Inherited Members
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Protected Attributes inherited from llvm::SmallVectorBase
void * BeginX
unsigned Size = 0
unsigned Capacity
Detailed Description
template<typename T>
class llvm::SmallVectorImpl< T >
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
Definition at line 315 of file SmallVector.h.
Member Typedef Documentation
const_iterator
template<typename T > using llvm::SmallVectorImpl< T >::const_iterator = typename SuperClass::const_iterator
Definition at line 320 of file SmallVector.h.
iterator
template<typename T > using llvm::SmallVectorImpl< T >::iterator = typename SuperClass::iterator
Definition at line 319 of file SmallVector.h.
reference
template<typename T > using llvm::SmallVectorImpl< T >::reference = typename SuperClass::reference
Definition at line 321 of file SmallVector.h.
size_type
template<typename T > using llvm::SmallVectorImpl< T >::size_type = typename SuperClass::size_type
Definition at line 322 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorImpl() [1/2]
template<typename T > llvm::SmallVectorImpl< T >::SmallVectorImpl (unsigned N) inline explicit protected
Definition at line 326 of file SmallVector.h.
SmallVectorImpl() [2/2]
template<typename T > llvm::SmallVectorImpl< T >::SmallVectorImpl (const SmallVectorImpl< T > &) delete
~SmallVectorImpl()
template<typename T > llvm::SmallVectorImpl< T >::~SmallVectorImpl () inline
Definition at line 332 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::isSmall().
Member Function Documentation
append() [1/3]
template<typename T > template<typename in_iter , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>::type> void llvm::SmallVectorImpl< T >::append (in_iter in_start, in_iter in_end) inline
Add the specified range to the end of the SmallVector.
Definition at line 387 of file SmallVector.h.
References llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by llvm::opt::ArgList::AddAllArgValues(), addAllGlobalValueUsers(), llvm::MachineInstr::addMemOperand(), llvm::FoldingSetNodeID::AddNodeID(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::FoldingSetNodeID::AddString(), llvm::CodeViewContext::addToStringTable(), llvm::DebugLocEntry::addValues(), analyzeLoopUnrollCost(), llvm::DIExpression::append(), llvm::RegsForValue::append(), llvm::SmallString< InternalLen >::append(), llvm::sys::path::append(), llvm::SmallVectorImpl< T >::append(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::DIExpression::appendToStack(), llvm::DIExpression::ExprOperand::appendToVector(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallString< InternalLen >::assign(), checkClobberSanity(), llvm::MachineInstr::cloneMergedMemRefs(), collectConcatOps(), combineToExtendBoolVectorInReg(), combineX86ShuffleChainWithExtract(), llvm::MCCodePaddingPolicy::computeFirstWindowPenaltyWeight(), llvm::concatenateVectors(), llvm::ConstantFoldGetElementPtr(), createMMXBuildVector(), llvm::DecodeEXTRQIMask(), llvm::DecodeINSERTQIMask(), llvm::DecodeVectorBroadcast(), deleteDeadBlocksFromLoop(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitInstToData(), eraseDeadBBsAndChildren(), llvm::DIBuilder::finalizeSubprogram(), llvm::FindInsertedValue(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::LiveRange::flushSegmentSet(), foldCONCAT_VECTORS(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ScalarEvolution::forgetLoop(), genericValueTraversal(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), getConstVector(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), getHostID(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), getMatchingEHPad(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), getNoopInput(), llvm::ConstantDataArray::getString(), getTargetConstantBitsFromNode(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SDNode::hasPredecessorHelper(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::InlineFunction(), llvm::opt::InputArgList::InputArgList(), llvm::sroa::AllocaSlices::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::MemorySSAUpdater::insertDef(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), isHorizontalBinOp(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isSimpleIf(), IsValueFullyAvailableInBlock(), llvm::TargetLowering::LowerCallTo(), llvm::SITargetLowering::LowerFormalArguments(), lowerShuffleOfExtractsAsVperm(), llvm::makePostTransformationMetadata(), moveBelowOrigChain(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::BitstreamCursor::readRecord(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::sys::path::replace_extension(), ReplaceINTRINSIC_W_CHAIN(), replaceOneDbgValueForAlloca(), resolveTypeIndexReferences(), RewriteHeapSROALoadUser(), llvm::Attributor::run(), llvm::LoopFullUnrollPass::run(), searchPredecessors(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::EngineBuilder::setMAttrs(), SimplifyAddOperands(), llvm::simplifyLoop(), llvm::SmallVector< T, N >::SmallVector(), SplitAddRecs(), llvm::detail::IEEEFloat::toString(), llvm::APInt::toString(), llvm::SelectionDAG::UnrollVectorOverflowOp(), and llvm::InstCombiner::visitGetElementPtrInst().
append() [2/3]
template<typename T > void llvm::SmallVectorImpl< T >::append (size_type NumInputs, const T & Elt) inline
Append NumInputs copies of Elt to the end.
Definition at line 397 of file SmallVector.h.
References llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), llvm::SmallVectorBase::set_size(), and llvm::SmallVectorBase::size().
append() [3/3]
template<typename T > void llvm::SmallVectorImpl< T >::append (std::initializer_list< T > IL) inline
Definition at line 405 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append().
assign() [1/3]
template<typename T > template<typename in_iter , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>::type> void llvm::SmallVectorImpl< T >::assign (in_iter in_start, in_iter in_end) inline
Definition at line 424 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorImpl< T >::clear().
assign() [2/3]
template<typename T > void llvm::SmallVectorImpl< T >::assign (size_type NumElts, const T & Elt) inline
Definition at line 412 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), and llvm::SmallVectorBase::set_size().
Referenced by llvm::SmallString< InternalLen >::assign(), canWidenShuffleElements(), CloneNodeWithValues(), getTargetConstantBitsFromNode(), llvm::SelectionDAGBuilder::getValueImpl(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), llvm::X86CallLowering::lowerCall(), llvm::SmallVector< T, N >::operator=(), llvm::scaleShuffleMask(), llvm::SmallVector< T, N >::SmallVector(), llvm::LoopTraversal::traverse(), and VectorizePTXValueVTs().
assign() [3/3]
template<typename T > void llvm::SmallVectorImpl< T >::assign (std::initializer_list< T > IL) inline
Definition at line 429 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorImpl< T >::clear().
clear()
template<typename T > void llvm::SmallVectorImpl< T >::clear () inline
Definition at line 339 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorBase::Size.
Referenced by llvm::PMDataManager::add(), addHints(), llvm::LiveIntervals::addKillFlags(), llvm::LanaiInstrInfo::analyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::MipsCCState::AnalyzeCallOperands(), llvm::MipsCCState::AnalyzeCallResult(), llvm::MipsCCState::AnalyzeFormalArguments(), llvm::SystemZCCState::AnalyzeFormalArguments(), analyzeLoopUnrollCost(), llvm::MipsCCState::AnalyzeReturn(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::SmallString< InternalLen >::assign(), llvm::SmallVectorImpl< T >::assign(), BatchCommitValueTo(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::coro::buildCoroutineFrame(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), CC_ARM_AAPCS_Custom_Aggregate(), CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), llvm::HexagonShuffler::check(), llvm::MipsCCState::CheckReturn(), llvm::ConstantHoistingPass::cleanup(), llvm::IndexedMap< T, ToIndexT >::clear(), llvm::PriorityWorklist< T, VectorT, MapT >::clear(), llvm::SmallSet< T, N, C >::clear(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::clear(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear(), llvm::AssumptionCache::clear(), llvm::FunctionLoweringInfo::clear(), llvm::GISelWorkList< N >::clear(), llvm::LiveRange::clear(), llvm::SDDbgInfo::clear(), llvm::MCInst::clear(), llvm::ARMBasicBlockUtils::clear(), llvm::ArrayRecycler< T, Align >::clear(), llvm::SpillPlacement::Node::clear(), llvm::CCState::clearByValRegsInfo(), llvm::FastISel::CallLoweringInfo::clearIns(), llvm::FastISel::CallLoweringInfo::clearOuts(), llvm::VPBlockBase::clearPredecessors(), llvm::VPBlockBase::clearSuccessors(), llvm::PPCCCState::clearWasPPCF128(), llvm::ScalarEvolution::computeAccessFunctions(), computeVariableSummary(), llvm::convertUTF8ToUTF16String(), llvm::DecodeVPPERMMask(), llvm::slpvectorizer::BoUpSLP::deleteTree(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::AsmPrinter::doFinalization(), doPromotion(), llvm::CodeViewContext::encodeDefRange(), llvm::CodeViewContext::encodeInlineLineTable(), ExpandBVWithShuffles(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::filterDeadComdatFunctions(), llvm::finalizeBundle(), llvm::CodeExtractor::findAllocas(), llvm::ScalarEvolution::findArrayDimensions(), FindFirstMatchingPrefix(), FindMostPopularDest(), llvm::SplitEditor::finish(), finishStackBlock(), llvm::RecordStreamer::flushSymverDirectives(), llvm::formDedicatedExitBlocks(), llvm::formLCSSAForInstructions(), llvm::ScalarEvolution::getAddExpr(), getAdjustedPtr(), llvm::RegsForValue::getCopyFromRegs(), llvm::TargetSubtargetInfo::getCriticalPathRCs(), llvm::pdb::DIARawSymbol::getDataBytes(), llvm::pdb::NativeRawSymbol::getDataBytes(), getFauxShuffleMask(), getHostID(), llvm::unittest::getInputFileDirectory(), llvm::getLiveRegMap(), getMemmoveLoadsAndStores(), llvm::GetShadowBytes(), llvm::ScalarEvolution::getUDivExpr(), getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnderlyingObjectsForInstr(), llvm::yaml::ScalarNode::getValue(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::MipsCallLowering::MipsHandler::handle(), llvm::InlineFunction(), llvm::MemorySSAUpdater::insertDef(), insertParsePoints(), isVectorPromotionViable(), llvm::SpillPlacement::iterate(), llvm::NVPTXTargetLowering::LowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), llvm::NVPTXTargetLowering::LowerReturn(), makeAllConstantUsesInstructions(), llvm::Regex::match(), mergeConstants(), moveBelowOrigChain(), llvm::sys::path::native(), llvm::SmallString< InternalLen >::operator=(), parseOperands(), llvm::SpillPlacement::prepare(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::HexagonInstrInfo::reduceLoopCount(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::LiveIntervals::releaseMemory(), llvm::MachineDominatorTree::releaseMemory(), llvm::ReachingDefAnalysis::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::LiveRange::RenumberValues(), reorderSubVector(), llvm::RuntimePointerChecking::reset(), llvm::SchedRemainder::reset(), llvm::SchedBoundary::reset(), llvm::MCContext::reset(), llvm::MCLOHContainer::reset(), llvm::MCStreamer::reset(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), llvm::UnwindOpcodeAssembler::Reset(), llvm::HexagonShuffler::reset(), llvm::LiveRangeCalc::reset(), llvm::DataLayout::reset(), llvm::MCDwarfLineTableHeader::resetFileTable(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), resolveTypeIndexReferences(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::MachineDominatorTree::runOnMachineFunction(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::MachineRegisterInfo::setCalleeSavedRegs(), llvm::FileRemover::setFile(), llvm::SwiftErrorValueTracking::setFunction(), llvm::EngineBuilder::setMAttrs(), llvm::IntervalMapImpl::Path::setRoot(), SimplifyAddOperands(), simplifyLoopInst(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::sortPtrAccesses(), llvm::SplitCriticalEdge(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::RegBankSelect::RepairingPlacement::switchTo(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::CodeViewYAML::toDebugH(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::LoopTraversal::traverse(), unswitchNontrivialInvariants(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::ValueEnumerator::ValueEnumerator(), llvm::MemorySSA::verifyOrdering(), and llvm::GCOVBlock::~GCOVBlock().
emplace_back()
template<typename T > template<typename... ArgTypes> reference llvm::SmallVectorImpl< T >::emplace_back (ArgTypes &&... Args) inline
Definition at line 641 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), LLVM_UNLIKELY, llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
Referenced by addEdge(), llvm::mca::MemoryGroup::addSuccessor(), llvm::mca::Scheduler::analyzeDataDependencies(), llvm::Annotations::Annotations(), llvm::coro::buildCoroutineFrame(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), checkClobberSanity(), CloneInstructionInExitBlock(), llvm::sys::commandLineFitsWithinSystemLimits(), computeImportForFunction(), createCallInst(), createImportedModule(), DeleteTriviallyDeadInstructions(), LoopDepthTree::descend(), llvm::NVPTXTargetStreamer::emitDwarfFileDirective(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::TernOpInit::Fold(), llvm::StackSafetyInfo::FunctionInfo::FunctionInfo(), llvm::AttributeList::get(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::CallBase::getOperandBundlesAsDefs(), llvm::ScalarEvolution::getSCEVAtScope(), llvm::SelectionDAG::getTokenFactor(), getWorklist(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::InlineFunction(), llvm::TargetPassConfig::insertPass(), insertSpills(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), isOnlyCopiedFromConstantGlobal(), LinearizeExprTree(), llvm::GCOVBlock::lookForCircuit(), LoopDepthTree::LoopDepthTree(), llvm::SITargetLowering::LowerCall(), matchIntrinsicType(), llvm::json::OStream::OStream(), llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerBeforePassCallback(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::MachineFunction::setVariableDbgInfo(), llvm::sortPtrAccesses(), llvm::DbgValueHistoryMap::startClobber(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::UnrollAndJamLoop(), and unswitchNontrivialInvariants().
erase() [1/2]
template<typename T > iterator llvm::SmallVectorImpl< T >::erase (const_iterator CI) inline
Definition at line 434 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, N, and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by collectMultiplyFactors(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), llvm::SmallSet< T, N, C >::erase(), llvm::MCInst::erase(), llvm::sroa::AllocaSlices::erase(), llvm::MDGlobalAttachmentMap::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase_if(), llvm::cl::ExpandResponseFiles(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), llvm::LiveRangeUpdater::flush(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPWithType(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), inlineCallsImpl(), llvm::InlineFunction(), isVectorPromotionViable(), llvm::LiveRange::join(), llvm::MCAsmLexer::Lex(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::LiveRange::MergeValueNumberInto(), OptimizeAndOrXor(), populateExternalRelations(), llvm::MDAttachmentMap::remove_if(), llvm::LegacyInlinerBase::removeDeadFunctions(), RemoveInstInputs(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::GISelObserverWrapper::removeObserver(), removeRegLanes(), llvm::LiveRange::removeSegment(), llvm::LiveRange::removeValNo(), llvm::Record::removeValue(), replaceConstantExprOp(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), llvm::AlwaysInlinerPass::run(), SimplifyBranchOnICmpChain(), sortGlobalExprs(), llvm::DebugLocEntry::sortUniqueValues(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), tryToSpeculatePHIs(), llvm::GCOVBlock::unblock(), unique_unsorted(), llvm::updateCGAndAnalysisManagerForFunctionPass(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), VerifySubExpr(), and llvm::InstCombiner::visitLandingPadInst().
erase() [2/2]
template<typename T > iterator llvm::SmallVectorImpl< T >::erase (const_iterator CS, const_iterator CE) inline
Definition at line 449 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), I, N, and llvm::SmallVectorBase::set_size().
insert() [1/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, const T & Elt) inline
Definition at line 497 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
insert() [2/5]
template<typename T > template<typename ItTy , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>::type> iterator llvm::SmallVectorImpl< T >::insert (iterator I, ItTy From, ItTy To) inline
Definition at line 581 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), From, I, llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [3/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, size_type NumToInsert, const T & Elt) inline
Definition at line 526 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [4/5]
template<typename T > void llvm::SmallVectorImpl< T >::insert (iterator I, std::initializer_list< T > IL) inline
Definition at line 637 of file SmallVector.h.
References I, and llvm::SmallVectorImpl< T >::insert().
insert() [5/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, T && Elt) inline
Definition at line 467 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
Referenced by addData(), llvm::DWARFUnitVector::addUnit(), llvm::MipsInstrInfo::analyzeBranch(), llvm::mca::Scheduler::analyzeResourcePressure(), canPaddingBeAccessed(), llvm::rdf::Liveness::computePhiInfo(), llvm::DwarfCompileUnit::constructScopeDIE(), doPromotion(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::cl::ExpandResponseFiles(), llvm::LiveRangeUpdater::flush(), llvm::AttributeList::get(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::SelectionDAG::getConstant(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::yaml::ScalarNode::getValue(), llvm::MCInst::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::ARMBasicBlockUtils::insert(), llvm::MCAsmLexer::Lex(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerInterruptReturn(), performSink(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::LiveRange::removeSegment(), llvm::IntervalMapImpl::Path::replaceRoot(), sinkInstruction(), tryToVectorizeHorReductionOrInstOperands(), llvm::MCAsmLexer::UnLex(), llvm::ScalarEvolution::verify(), llvm::WriteBitcodeToFile(), and writeWholeProgramDevirtResolutionByArg().
operator!=()
template<typename T > bool llvm::SmallVectorImpl< T >::operator!= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 657 of file SmallVector.h.
operator<()
template<typename T > bool llvm::SmallVectorImpl< T >::operator< (const SmallVectorImpl< T > & RHS) const inline
Definition at line 661 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
operator=() [1/2]
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (const SmallVectorImpl< T > & RHS)
Definition at line 706 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorBase::size(), and llvm::size().
Referenced by llvm::SmallVector< T, N >::operator=(), and llvm::SmallVector< T, N >::SmallVector().
operator=() [2/2]
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (SmallVectorImpl< T > && RHS)
Definition at line 755 of file SmallVector.h.
References llvm::size(), and Size.
operator==()
template<typename T > bool llvm::SmallVectorImpl< T >::operator== (const SmallVectorImpl< T > & RHS) const inline
Definition at line 653 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorBase::size().
pop_back_val()
template<typename T > LLVM_NODISCARD T llvm::SmallVectorImpl< T >::pop_back_val () inline
Definition at line 374 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by addAllGlobalValueUsers(), addBlockAndPredsToSet(), AddReachableCodeToWorklist(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), allUsersAreInFunction(), analyzeLoopUnrollCost(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), buildMultiplyTree(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), canonicalizePHIOperands(), checkClobberSanity(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), CleanupConstantGlobalUsers(), clearAssumptionsOfUsers(), cloneLoopNest(), collectCastsToIgnore(), collectEHScopeMembers(), collectHomogenousInstGraphLoopInvariants(), collectTransitivePredecessors(), llvm::colorEHFunclets(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), llvm::FunctionComparator::compare(), computeBlocksDominatingExits(), llvm::computeDeadSymbols(), ComputeImportForModule(), ComputeLiveInBlocks(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), ComputePostOrders(), ConstHasGlobalValuePredicate(), deleteDeadBlocksFromLoop(), deleteDeadInstruction(), DeleteTriviallyDeadInstructions(), llvm::ARMFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), llvm::SMSchedule::earliestCycleInChain(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), eraseDeadBBsAndChildren(), llvm::InstructionSelector::executeMatchTable(), findBasePointer(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), findProfitablePHIs(), findRefEdges(), findSRegBaseAndIndex(), foldReturnAndProcessPred(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::formLCSSAForInstructions(), llvm::FunctionComparator::functionHash(), genericValueTraversal(), getBaseType(), llvm::getConstantVRegValWithLookThrough(), getCoroBeginPredBlocks(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), getMatchingEHPad(), getNotRelocatableInstructions(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::GetUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), handleFree(), HandleMergeInputChains(), hasCallsInBlocksBetween(), llvm::SDNode::hasPredecessorHelper(), llvm::HexagonMCShuffle(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), isEphemeralValueOf(), isKnownNonNullFromDominatingCondition(), isLeakCheckerRoot(), isNonEscapingGlobalNoAliasWithLoad(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantGlobal(), llvm::isPotentiallyReachableFromMany(), isSafeToSpeculatePHIUsers(), isSimpleIf(), IsStoredObjCPointer(), isSuccOrder(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), llvm::SMSchedule::latestCycleInChain(), LinearizeExprTree(), markAliveBlocks(), markTails(), memoryIsNotModifiedBetween(), mustExecuteUBIfPoisonOnPathTo(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::PointerMayBeCaptured(), llvm::BasicAAResult::pointsToConstantMemory(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::pop_back_val(), llvm::GISelWorkList< N >::pop_back_val(), llvm::WebAssemblyInstPrinter::printInst(), llvm::AlignmentFromAssumptionsPass::processAssumption(), rebuildLoopAfterUnswitch(), recomputeLoopBlockSet(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::InstCombineWorklist::RemoveOne(), replaceConstantExprOp(), rewriteNonInstructionUses(), llvm::TruncInstCombine::run(), llvm::LoopUnrollPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::LoopVectorizePass::runImpl(), searchPredecessors(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::simplifyLoop(), llvm::simplifyLoopAfterUnroll(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::JumpThreadingPass::ThreadEdge(), updateLiveness(), llvm::ScalarEvolution::verify(), verifyCTRBranch(), llvm::SCEVTraversal< SV >::visitAll(), visitDomSubTree(), visitPHIUsersAndDepsInPostOrder(), and llvm::LazyCallGraph::visitReferences().
reserve()
template<typename T > void llvm::SmallVectorImpl< T >::reserve (size_type N) inline
Definition at line 369 of file SmallVector.h.
References llvm::SmallVectorBase::capacity(), and llvm::SmallVectorTemplateBase< T, bool >::grow().
Referenced by llvm::InstCombineWorklist::AddInitialGroup(), appendToGlobalArray(), BatchCommitValueTo(), buildClonedLoopBlocks(), buildClonedLoops(), llvm::FileCheck::CanonicalizeFile(), llvm::sys::commandLineFitsWithinSystemLimits(), llvm::zlib::compress(), llvm::EHStreamer::computeActionsTable(), llvm::computeDeadSymbols(), llvm::ConstantFoldGetElementPtr(), llvm::TypedInit::convertInitializerBitRange(), llvm::ListInit::convertInitializerTo(), llvm::TypedInit::convertInitListSlice(), llvm::ListInit::convertInitListSlice(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::DwarfStringPool::emit(), llvm::EHStreamer::emitExceptionTable(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), ExpandBVWithShuffles(), llvm::FindInsertedValue(), llvm::RecordStreamer::flushSymverDirectives(), llvm::AttributeList::get(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), getMemoryBufferForStream(), llvm::SelectionDAG::getMergeValues(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::yaml::ScalarNode::getValue(), llvm::IntEqClasses::grow(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::InlineFunction(), llvm::SmallVectorImpl< T >::insert(), insertParsePoints(), makeStatepointExplicit(), OptimizeAwayTrappingUsesOfValue(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::CallGraph::print(), rebuildLoopAfterUnswitch(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), relocationViaAlloca(), llvm::IndexedMap< T, ToIndexT >::reserve(), llvm::VarDefInit::resolveReferences(), llvm::DagInit::resolveReferences(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SimplifyCall(), llvm::sortPtrAccesses(), speculatePHIs(), unswitchNontrivialInvariants(), llvm::upgradeInstructionLoopAttachment(), upgradeLoopArgument(), llvm::InstCombiner::visitLandingPadInst(), llvm::WriteBitcodeToFile(), llvm::WriteIndexToFile(), llvm::WriteThinLinkBitcodeToFile(), and llvm::LLVMContextImpl::~LLVMContextImpl().
resize() [1/2]
template<typename T > void llvm::SmallVectorImpl< T >::resize (size_type N) inline
Definition at line 344 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), I, N, llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::size(), and T.
Referenced by llvm::AttributeList::addAttributes(), addData(), llvm::CodeViewContext::addFile(), llvm::AttributeList::addParamAttribute(), llvm::BitTracker::RegisterCell::cat(), llvm::CCState::CCState(), llvm::ARMBasicBlockUtils::computeAllBlockSizes(), llvm::EHStreamer::computeCallSiteTable(), llvm::WasmException::computeCallSiteTable(), llvm::ConstantFoldGetElementPtr(), llvm::convertUTF8ToUTF16String(), copyBytesForDefRange(), createMMXBuildVector(), llvm::DependenceInfo::depends(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::DwarfStringPool::emit(), llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitDTPRel32Value(), llvm::MCObjectStreamer::EmitDTPRel64Value(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCObjectStreamer::EmitTPRel32Value(), llvm::MCObjectStreamer::EmitTPRel64Value(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MachineTraceMetrics::Ensemble::Ensemble(), llvm::InstructionSelector::executeMatchTable(), llvm::extractConstantMask(), llvm::SplitEditor::finish(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::RegsForValue::getCopyFromRegs(), llvm::pdb::DIARawSymbol::getDataBytes(), llvm::LLVMContext::getMDKindNames(), llvm::MDNode::getMostGenericRange(), getNoopInput(), llvm::LLVMContextImpl::getOperandBundleTags(), llvm::GetShadowBytes(), llvm::DependenceInfo::getSplitIteration(), llvm::LLVMContextImpl::getSyncScopeNames(), getTargetConstantBitsFromNode(), getVPermMask(), llvm::TargetSchedModel::init(), llvm::SchedRemainder::init(), llvm::SchedBoundary::init(), INITIALIZE_PASS(), llvm::ResourceManager::initProcResourceVectors(), llvm::mca::InstrBuilder::InstrBuilder(), llvm::LiveRange::join(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::TargetLowering::LowerCallTo(), lowerV8I16GeneralSingleInputShuffle(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::object::ExportEntry::moveNext(), llvm::LegalizerHelper::narrowScalar(), llvm::Triple::normalize(), llvm::RegisterBankInfo::OperandsMapper::OperandsMapper(), llvm::raw_ostream::operator<<(), parseBuildVersionCommand(), llvm::PredicateInfo::PredicateInfo(), llvm::PrettyStackTraceFormat::PrettyStackTraceFormat(), llvm::JumpThreadingPass::ProcessBranchOnPHI(), PropagateConstantsIntoArguments(), llvm::coverage::RawCoverageMappingReader::read(), llvm::AttributeList::removeAttributes(), llvm::SchedBoundary::reset(), llvm::IndexedMap< T, ToIndexT >::resize(), llvm::DIInliningInfo::resize(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::ReachingDefAnalysis::runOnMachineFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::LegalizerInfo::setLegalizeScalarToDifferentSizeStrategy(), llvm::LegalizerInfo::setLegalizeVectorElementToDifferentSizeStrategy(), llvm::StructType::setName(), llvm::sortPtrAccesses(), and llvm::zlib::uncompress().
resize() [2/2]
template<typename T > void llvm::SmallVectorImpl< T >::resize (size_type N, const T & NV) inline
Definition at line 357 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), N, llvm::SmallVectorBase::set_size(), and llvm::SmallVectorBase::size().
swap()
template<typename T > void llvm::SmallVectorImpl< T >::swap (SmallVectorImpl< T > & RHS)
Definition at line 668 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::BeginX, llvm::SmallVectorBase::Capacity, llvm::SmallVectorBase::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), llvm::SmallVectorBase::set_size(), llvm::SmallVectorBase::Size, llvm::SmallVectorBase::size(), llvm::size(), Size, and std::swap().
Referenced by llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::sys::fs::createUniquePath(), ExpandBVWithShuffles(), llvm::TargetLowering::LowerCallTo(), llvm::sys::fs::make_absolute(), llvm::sys::path::remove_dots(), llvm::sys::path::replace_path_prefix(), llvm::LiveIntervals::shrinkToUses(), std::swap(), and llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef().
The documentation for this class was generated from the following files:
include/llvm/ADT/APFloat.h
include/llvm/ADT/SmallVector.h