LLVM: llvm::X86MCExpr Class Reference
llvm::X86MCExpr Class Reference
#include "Target/X86/MCTargetDesc/X86MCExpr.h"
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
bool inlineAssignedExpr () const override
bool isEqualTo (const MCExpr *X) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
int64_t getRegNo () const
getSubExpr - Get the child of this expression.
virtual void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const =0
virtual bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const =0
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
virtual void visitUsedExpr (MCStreamer &Streamer) const =0
virtual MCFragment * findAssociatedFragment () const =0
virtual void fixELFSymbolsInTLSFixups (MCAssembler &) const =0
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const X86MCExpr * create (int64_t RegNo, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Definition at line 25 of file X86MCExpr.h.
Member Function Documentation
classof()
static bool llvm::X86MCExpr::classof (const MCExpr * E) inline static
Definition at line 72 of file X86MCExpr.h.
References E, and llvm::MCExpr::Target.
create()
static const X86MCExpr * llvm::X86MCExpr::create (int64_t RegNo, MCContext & Ctx) inline static
Definition at line 36 of file X86MCExpr.h.
evaluateAsRelocatableImpl()
bool llvm::X86MCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 55 of file X86MCExpr.h.
findAssociatedFragment()
MCFragment * llvm::X86MCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 67 of file X86MCExpr.h.
fixELFSymbolsInTLSFixups()
void llvm::X86MCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 70 of file X86MCExpr.h.
getRegNo()
int64_t llvm::X86MCExpr::getRegNo () const inline
getSubExpr - Get the child of this expression.
Definition at line 45 of file X86MCExpr.h.
Referenced by isEqualTo().
inlineAssignedExpr()
bool llvm::X86MCExpr::inlineAssignedExpr () const inline override virtual
Reimplemented from llvm::MCTargetExpr.
Definition at line 60 of file X86MCExpr.h.
isEqualTo()
bool llvm::X86MCExpr::isEqualTo (const MCExpr * X) const inline override virtual
Reimplemented from llvm::MCTargetExpr.
Definition at line 61 of file X86MCExpr.h.
References E, getRegNo(), and X.
printImpl()
void llvm::X86MCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 49 of file X86MCExpr.h.
References llvm::MCAsmInfo::getAssemblerDialect(), and llvm::X86ATTInstPrinter::getRegisterName().
visitUsedExpr()
void llvm::X86MCExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 66 of file X86MCExpr.h.
The documentation for this class was generated from the following file:
lib/Target/X86/MCTargetDesc/X86MCExpr.h