LLVM: llvm::PseudoSourceValueManager Class Reference
llvm::PseudoSourceValueManager Class Reference
Manages creation of pseudo source values.
#include "llvm/CodeGen/PseudoSourceValue.h"
Public Member Functions
PseudoSourceValueManager (const TargetInstrInfo &TII)
const PseudoSourceValue * getStack ()
Return a pseudo source value referencing the area below the stack frame of a function, e.g., the argument space.
const PseudoSourceValue * getGOT ()
Return a pseudo source value referencing the global offset table (or something the like).
const PseudoSourceValue * getConstantPool ()
Return a pseudo source value referencing the constant pool.
const PseudoSourceValue * getJumpTable ()
Return a pseudo source value referencing a jump table.
const PseudoSourceValue * getFixedStack (int FI)
Return a pseudo source value referencing a fixed stack frame entry, e.g., a spill slot.
const PseudoSourceValue * getGlobalValueCallEntry (const GlobalValue *GV)
const PseudoSourceValue * getExternalSymbolCallEntry (const char *ES)
Detailed Description
Manages creation of pseudo source values.
Definition at line 155 of file PseudoSourceValue.h.
Constructor & Destructor Documentation
PseudoSourceValueManager()
PseudoSourceValueManager::PseudoSourceValueManager (const TargetInstrInfo & TII)
Definition at line 106 of file PseudoSourceValue.cpp.
Member Function Documentation
getConstantPool()
const PseudoSourceValue * PseudoSourceValueManager::getConstantPool ()
Return a pseudo source value referencing the constant pool.
Since constant pools are constant, this doesn't need to identify a specific constant pool entry.
Definition at line 120 of file PseudoSourceValue.cpp.
Referenced by llvm::MachinePointerInfo::getConstantPool().
getExternalSymbolCallEntry()
const PseudoSourceValue * PseudoSourceValueManager::getExternalSymbolCallEntry (const char * ES)
Definition at line 146 of file PseudoSourceValue.cpp.
References E.
Referenced by llvm::MipsFunctionInfo::callPtrInfo().
getFixedStack()
const PseudoSourceValue * PseudoSourceValueManager::getFixedStack (int FI)
Return a pseudo source value referencing a fixed stack frame entry, e.g., a spill slot.
Definition at line 129 of file PseudoSourceValue.cpp.
Referenced by llvm::MachinePointerInfo::getFixedStack().
getGlobalValueCallEntry()
const PseudoSourceValue * PseudoSourceValueManager::getGlobalValueCallEntry (const GlobalValue * GV)
Definition at line 137 of file PseudoSourceValue.cpp.
References E.
Referenced by llvm::MipsFunctionInfo::callPtrInfo().
getGOT()
const PseudoSourceValue * PseudoSourceValueManager::getGOT ()
Return a pseudo source value referencing the global offset table (or something the like).
Definition at line 118 of file PseudoSourceValue.cpp.
Referenced by expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MachinePointerInfo::getGOT(), getTOCEntry(), LowerToTLSExecModel(), and llvm::SparcTargetLowering::makeAddress().
getJumpTable()
const PseudoSourceValue * PseudoSourceValueManager::getJumpTable ()
Return a pseudo source value referencing a jump table.
Since jump tables are constant, this doesn't need to identify a specific jump table.
Definition at line 124 of file PseudoSourceValue.cpp.
Referenced by llvm::MachinePointerInfo::getJumpTable().
getStack()
const PseudoSourceValue * PseudoSourceValueManager::getStack ()
Return a pseudo source value referencing the area below the stack frame of a function, e.g., the argument space.
Definition at line 114 of file PseudoSourceValue.cpp.
Referenced by llvm::MachinePointerInfo::getStack(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::SITargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), and llvm::AMDGPUTargetLowering::storeStackInputValue().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/PseudoSourceValue.h
lib/CodeGen/PseudoSourceValue.cpp