LLVM: llvm::VPReplicateRecipe Class Reference
llvm::VPReplicateRecipe Class Reference
VPReplicateRecipe replicates a given instruction producing multiple scalar copies of the original scalar type, one per lane, instead of producing a single copy of widened type for all lanes.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPReplicateRecipe (Instruction *I, bool IsUniform, bool IsPredicated=false)
~VPReplicateRecipe () override=default
void execute (VPTransformState &State) override
Generate replicas of the desired Ingredient.
void setAlsoPack (bool Pack)
void print (raw_ostream &O, const Twine &Indent) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (struct VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
virtual void print (raw_ostream &O, const Twine &Indent) const =0
Each recipe prints itself.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Static Public Member Functions
static bool classof (const VPRecipeBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReplicateSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Detailed Description
VPReplicateRecipe replicates a given instruction producing multiple scalar copies of the original scalar type, one per lane, instead of producing a single copy of widened type for all lanes.
If the instruction is known to be uniform only one copy, per lane zero, will be generated.
Definition at line 849 of file VPlan.h.
Constructor & Destructor Documentation
VPReplicateRecipe()
llvm::VPReplicateRecipe::VPReplicateRecipe (Instruction * I, bool IsUniform, bool IsPredicated = false) inline
Definition at line 864 of file VPlan.h.
References I.
~VPReplicateRecipe()
llvm::VPReplicateRecipe::~VPReplicateRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPReplicateRecipe::classof (const VPRecipeBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 878 of file VPlan.h.
References llvm::VPRecipeBase::getVPRecipeID().
execute()
void VPReplicateRecipe::execute (VPTransformState & State) override virtual
Generate replicas of the desired Ingredient.
Replicas will be generated for all parts and lanes unless a specific part and lane are specified in the State.
Implements llvm::VPRecipeBase.
Definition at line 7107 of file LoopVectorize.cpp.
References llvm::DITypeRefArray::get(), llvm::VPTransformState::ILV, llvm::VPTransformState::Instance, llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::VectorizerValueMap::setVectorValue(), llvm::VPTransformState::UF, llvm::VPTransformState::ValueMap, and llvm::VPTransformState::VF.
print()
void VPReplicateRecipe::print (raw_ostream & O, const Twine & Indent) const override virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Definition at line 674 of file VPlan.cpp.
setAlsoPack()
void llvm::VPReplicateRecipe::setAlsoPack (bool Pack) inline
Definition at line 887 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp