LLVM: llvm::LoopUnrollAndJamPass Class Reference
llvm::LoopUnrollAndJamPass Class Reference
A simple loop rotation transformation.
#include "llvm/Transforms/Scalar/LoopUnrollAndJamPass.h"
Public Member Functions
LoopUnrollAndJamPass (int OptLevel=2)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopUnrollAndJamPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A simple loop rotation transformation.
Definition at line 23 of file LoopUnrollAndJamPass.h.
Constructor & Destructor Documentation
LoopUnrollAndJamPass()
llvm::LoopUnrollAndJamPass::LoopUnrollAndJamPass (int OptLevel = 2) inline explicit
Definition at line 27 of file LoopUnrollAndJamPass.h.
Member Function Documentation
run()
PreservedAnalyses LoopUnrollAndJamPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 494 of file LoopUnrollAndJamPass.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), llvm::LoopStandardAnalysisResults::DT, F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::BasicBlock::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::LoopStandardAnalysisResults::LI, llvm::report_fatal_error(), llvm::LoopStandardAnalysisResults::SE, tryToUnrollAndJamLoop(), llvm::LoopStandardAnalysisResults::TTI, and llvm::Unmodified.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopUnrollAndJamPass.h
lib/Transforms/Scalar/LoopUnrollAndJamPass.cpp