LLVM: llvm::ConcreteOperator< SuperClass, Opc > Class Template Reference
llvm::ConcreteOperator< SuperClass, Opc > Class Template Reference
A helper template for defining operators for individual opcodes.
#include "llvm/IR/Operator.h"
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const ConstantExpr *CE)
static bool classof (const Value *V)
Detailed Description
template<typename SuperClass, unsigned Opc>
class llvm::ConcreteOperator< SuperClass, Opc >
A helper template for defining operators for individual opcodes.
Definition at line 398 of file Operator.h.
Member Function Documentation
classof() [1/3]
template<typename SuperClass , unsigned Opc> static bool llvm::ConcreteOperator< SuperClass, Opc >::classof (const ConstantExpr * CE) inline static
Definition at line 403 of file Operator.h.
References llvm::ConstantExpr::getOpcode().
classof() [2/3]
template<typename SuperClass , unsigned Opc> static bool llvm::ConcreteOperator< SuperClass, Opc >::classof (const Instruction * I) inline static
Definition at line 400 of file Operator.h.
References I.
Referenced by llvm::ConcreteOperator< SuperClass, Opc >::classof().
classof() [3/3]
template<typename SuperClass , unsigned Opc> static bool llvm::ConcreteOperator< SuperClass, Opc >::classof (const Value * V) inline static
Definition at line 406 of file Operator.h.
References llvm::ConcreteOperator< SuperClass, Opc >::classof().
The documentation for this class was generated from the following file:
include/llvm/IR/Operator.h