LLVM: llvm::CallBase Class Reference
llvm::CallBase Class Reference
Base class for all callable instructions (InvokeInst and CallInst) Holds everything related to calling a function.
#include "llvm/IR/InstrTypes.h"
Classes
struct BundleOpInfo
Used to keep track of an operand bundle.
Public Member Functions
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *FTy)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
User::op_iterator data_operands_begin ()
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
User::const_op_iterator data_operands_begin () const
User::op_iterator data_operands_end ()
User::const_op_iterator data_operands_end () const
iterator_range< User::op_iterator > data_ops ()
iterator_range< User::const_op_iterator > data_ops () const
bool data_operands_empty () const
unsigned data_operands_size () const
bool isDataOperand (const Use *U) const
bool isDataOperand (Value::const_user_iterator UI) const
unsigned getDataOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the data operand corresponding to it.
unsigned getDataOperandNo (const Use *U) const
Given a use for a data operand, get the data operand number that corresponds to it.
User::op_iterator arg_begin ()
Return the iterator pointing to the beginning of the argument list.
User::const_op_iterator arg_begin () const
User::op_iterator arg_end ()
Return the iterator pointing to the end of the argument list.
User::const_op_iterator arg_end () const
iterator_range< User::op_iterator > args ()
Iteration adapter for range-for loops.
iterator_range< User::const_op_iterator > args () const
bool arg_empty () const
unsigned arg_size () const
iterator_range< User::op_iterator > arg_operands ()
iterator_range< User::const_op_iterator > arg_operands () const
unsigned getNumArgOperands () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a call argument.
Use & getArgOperandUse (unsigned i)
bool isArgOperand (const Use *U) const
bool isArgOperand (Value::const_user_iterator UI) const
bool hasArgument (const Value *V) const
Returns true if this CallSite passes the given Value* as an argument to the called function.
Value * getCalledOperand () const
Value * getCalledValue () const
const Use & getCalledOperandUse () const
Use & getCalledOperandUse ()
Function * getCalledFunction () const
Returns the function called, or null if this is an indirect function invocation.
bool isIndirectCall () const
Return true if the callsite is an indirect call.
bool isCallee (Value::const_user_iterator UI) const
Determine whether the passed iterator points to the callee operand's Use.
bool isCallee (const Use *U) const
Determine whether this Use is the callee operand's Use.
Function * getCaller ()
Helper to get the caller (the parent function).
const Function * getCaller () const
bool isMustTailCall () const
Tests if this call site must be tail call optimized.
bool isTailCall () const
Tests if this call site is marked as a tail call.
Intrinsic::ID getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
void setCalledOperand (Value *V)
void setCalledFunction (Function *Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionCallee Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionType *FTy, Value *Fn)
Sets the function called, including updating to the specified function type.
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
bool isInlineAsm () const
Check if this call is an inline asm statement.
Attribute API
These methods access and modify attributes on this call (including looking through to the attributes on the called function when necessary).
AttributeList getAttributes () const
Return the parameter attributes for this call.
void setAttributes (AttributeList A)
Set the parameter attributes for this call.
bool hasFnAttr (Attribute::AttrKind Kind) const
Determine whether this call has the given attribute.
bool hasFnAttr (StringRef Kind) const
Determine whether this call has the given attribute.
void addAttribute (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
void addAttribute (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
void addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Adds the attribute to the indicated argument.
void addParamAttr (unsigned ArgNo, Attribute Attr)
Adds the attribute to the indicated argument.
void removeAttribute (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeAttribute (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
void removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Removes the attribute from the given argument.
void removeParamAttr (unsigned ArgNo, StringRef Kind)
Removes the attribute from the given argument.
void addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
bool hasRetAttr (Attribute::AttrKind Kind) const
Determine whether the return value has the given attribute.
bool paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
Attribute getAttribute (unsigned i, Attribute::AttrKind Kind) const
Get the attribute of a given kind at a position.
Attribute getAttribute (unsigned i, StringRef Kind) const
Get the attribute of a given kind at a position.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Get the attribute of a given kind from a given arg.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Get the attribute of a given kind from a given arg.
bool dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const
Return true if the data operand at index i has the attribute A.
bool doesNotCapture (unsigned OpNo) const
Determine whether this data operand is not captured.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool isInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed in an alloca.
bool isByValOrInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed by value or in an alloca.
bool hasInAllocaArgument () const
Determine if there are is an inalloca argument.
bool doesNotAccessMemory (unsigned OpNo) const
bool onlyReadsMemory (unsigned OpNo) const
bool doesNotReadMemory (unsigned OpNo) const
unsigned getRetAlignment () const
Extract the alignment of the return value.
unsigned getParamAlignment (unsigned ArgNo) const
Extract the alignment for a call or parameter (0=unknown).
Type * getParamByValType (unsigned ArgNo) const
Extract the byval type for a call or parameter.
uint64_t getDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
bool isReturnNonNull () const
Return true if the return value is known to be not null.
bool returnDoesNotAlias () const
Determine if the return value is marked with NoAlias attribute.
Value * getReturnedArgOperand () const
If one of the arguments has the 'returned' attribute, returns its operand value.
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isStrictFP () const
Determine if the call requires strict floating point semantics.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReadMemory () const
Determine if the call does not access or only writes memory.
void setDoesNotReadMemory ()
bool onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
void setOnlyAccessesArgMemory ()
bool onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
void setOnlyAccessesInaccessibleMemory ()
bool onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
void setOnlyAccessesInaccessibleMemOrArgMem ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNoCfCheck () const
Determine if the call should not perform indirect branch tracking.
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the invoke cannot be duplicated.
void setCannotDuplicate ()
bool isConvergent () const
Determine if the invoke is convergent.
void setConvergent ()
void setNotConvergent ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift ()
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isIndirectTerminator () const
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
Fills the AAMDNodes structure with AA metadata from this instruction.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void setAAMetadata (const AAMDNodes &N)
Sets the metadata on this instruction from the AAMDNodes structure.
bool extractProfMetadata (uint64_t &TrueVal, uint64_t &FalseVal) const
Retrieve the raw weight values of a conditional branch or select.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setProfWeight (uint64_t W)
Sets the branch_weights metadata to W for CallInst.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool isExact () const
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool mayReadFromMemory () const
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const
Return true if this atomic instruction stores to memory.
bool mayThrow () const
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const
Return true if the instruction may have side effects.
bool isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
const Instruction * getNextNonDebugInstruction () const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction ()
const Instruction * getPrevNonDebugInstruction () const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction ()
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, bool)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCasts ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs, aliases and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripPointerCastsNoFollowAliases () const
Strip off pointer casts and all-zero GEPs.
Value * stripPointerCastsNoFollowAliases ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets () const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets ()
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
unsigned getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isIndirectTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator with indirect targets.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
template<class... ArgsTy>
CallBase (AttributeList const &A, FunctionType *FT, ArgsTy &&... Args)
bool hasDescriptor () const
unsigned getNumSubclassExtraOperands () const
unsigned getNumSubclassExtraOperandsDynamic () const
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Instruction (const Instruction &)=delete
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
AttributeList Attrs
parameter attributes for callable
FunctionType * FTy
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes
static constexpr int CalledOperandOpEndIdx = -1
The last operand is the called operand.
Operand Bundle API
This group of methods provides the API to access and manipulate operand bundles on this call.
using bundle_op_iterator = BundleOpInfo *
using const_bundle_op_iterator = const BundleOpInfo *
unsigned getNumOperandBundles () const
Return the number of operand bundles associated with this User.
bool hasOperandBundles () const
Return true if this User has any operand bundles.
unsigned getBundleOperandsStartIndex () const
Return the index of the first bundle operand in the Use array.
unsigned getBundleOperandsEndIndex () const
Return the index of the last bundle operand in the Use array.
bool isBundleOperand (unsigned Idx) const
Return true if the operand at index Idx is a bundle operand.
bool isBundleOperand (const Use *U) const
Returns true if the use is a bundle operand.
bool isBundleOperand (Value::const_user_iterator UI) const
unsigned getNumTotalBundleOperands () const
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
OperandBundleUse getOperandBundleAt (unsigned Index) const
Return the operand bundle at a specific index.
unsigned countOperandBundlesOfType (StringRef Name) const
Return the number of operand bundles with the tag Name attached to this instruction.
unsigned countOperandBundlesOfType (uint32_t ID) const
Return the number of operand bundles with the tag ID attached to this instruction.
Optional< OperandBundleUse > getOperandBundle (StringRef Name) const
Return an operand bundle by name, if present.
Optional< OperandBundleUse > getOperandBundle (uint32_t ID) const
Return an operand bundle by tag ID, if present.
void getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > &Defs) const
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
OperandBundleUse getOperandBundleForOperand (unsigned OpIdx) const
Return the operand bundle for the operand at index OpIdx.
bool hasReadingOperandBundles () const
Return true if this operand bundle user has operand bundles that may read from the heap.
bool hasClobberingOperandBundles () const
Return true if this operand bundle user has operand bundles that may write to the heap.
bool bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const
Return true if the bundle operand at index OpIdx has the attribute A.
bool hasIdenticalOperandBundleSchema (const CallBase &Other) const
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
bool hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
bool isFnAttrDisallowedByOpBundle (StringRef S) const
Is the function attribute S disallowed by some operand bundle on this operand bundle user?
bool isFnAttrDisallowedByOpBundle (Attribute::AttrKind A) const
Is the function attribute A disallowed by some operand bundle on this operand bundle user?
OperandBundleUse operandBundleFromBundleOpInfo (const BundleOpInfo &BOI) const
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
bundle_op_iterator bundle_op_info_begin ()
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_begin () const
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
bundle_op_iterator bundle_op_info_end ()
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_end () const
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
iterator_range< bundle_op_iterator > bundle_op_infos ()
Return the range [bundle_op_info_begin, bundle_op_info_end).
iterator_range< const_bundle_op_iterator > bundle_op_infos () const
Return the range [bundle_op_info_begin, bundle_op_info_end).
op_iterator populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
const BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx) const
Return the BundleOpInfo for the operand at index OpIdx.
static unsigned CountBundleInputs (ArrayRef< OperandBundleDef > Bundles)
Return the total number of values used in Bundles.
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Detailed Description
Base class for all callable instructions (InvokeInst and CallInst) Holds everything related to calling a function.
All call-like instructions are required to use a common operand layout:
Zero or more arguments to the call,
Zero or more operand bundles with zero or more operand inputs each bundle,
Zero or more subclass controlled operands
The called function.
This allows this base class to easily access the called function and the start of the arguments without knowing how many other operands a particular subclass requires. Note that accessing the end of the argument list isn't as cheap as most other operations on the base class.
Definition at line 1100 of file InstrTypes.h.
Member Typedef Documentation
bundle_op_iterator
using llvm::CallBase::bundle_op_iterator = BundleOpInfo *
Definition at line 1974 of file InstrTypes.h.
const_bundle_op_iterator
using llvm::CallBase::const_bundle_op_iterator = const BundleOpInfo *
Definition at line 1975 of file InstrTypes.h.
Constructor & Destructor Documentation
CallBase()
template<class... ArgsTy> llvm::CallBase::CallBase (AttributeList const & A, FunctionType * FT, ArgsTy &&... Args) inline protected
Definition at line 1109 of file InstrTypes.h.
Member Function Documentation
addAttribute() [1/2]
void llvm::CallBase::addAttribute (unsigned i, Attribute Attr) inline
adds the attribute to the list of attributes.
Definition at line 1390 of file InstrTypes.h.
References llvm::AttributeList::addAttribute(), getAttributes(), llvm::Value::getContext(), and setAttributes().
addAttribute() [2/2]
void llvm::CallBase::addAttribute (unsigned i, Attribute::AttrKind Kind) inline
adds the attribute to the list of attributes.
Definition at line 1383 of file InstrTypes.h.
References llvm::AttributeList::addAttribute(), getAttributes(), llvm::Value::getContext(), and setAttributes().
Referenced by llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), setCannotDuplicate(), llvm::CallInst::setCanReturnTwice(), setConvergent(), setDoesNotAccessMemory(), setDoesNotReadMemory(), setDoesNotReturn(), setDoesNotThrow(), setIsNoInline(), setOnlyAccessesArgMemory(), setOnlyAccessesInaccessibleMemOrArgMem(), setOnlyAccessesInaccessibleMemory(), setOnlyReadsMemory(), and llvm::InstCombiner::visitCallInst().
addDereferenceableAttr()
void llvm::CallBase::addDereferenceableAttr (unsigned i, uint64_t Bytes) inline
adds the dereferenceable attribute to the list of attributes.
Definition at line 1443 of file InstrTypes.h.
References llvm::AttributeList::addDereferenceableAttr(), getAttributes(), llvm::Value::getContext(), and setAttributes().
addDereferenceableOrNullAttr()
void llvm::CallBase::addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes) inline
adds the dereferenceable_or_null attribute to the list of attributes.
Definition at line 1451 of file InstrTypes.h.
References llvm::AttributeList::addDereferenceableOrNullAttr(), getAttributes(), llvm::Value::getContext(), and setAttributes().
addParamAttr() [1/2]
void llvm::CallBase::addParamAttr (unsigned ArgNo, Attribute Attr) inline
Adds the attribute to the indicated argument.
Definition at line 1405 of file InstrTypes.h.
References llvm::AttributeList::addParamAttribute(), assert(), getAttributes(), llvm::Value::getContext(), getNumArgOperands(), and setAttributes().
addParamAttr() [2/2]
void llvm::CallBase::addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) inline
Adds the attribute to the indicated argument.
Definition at line 1397 of file InstrTypes.h.
References llvm::AttributeList::addParamAttribute(), assert(), getAttributes(), llvm::Value::getContext(), getNumArgOperands(), and setAttributes().
Referenced by llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), and llvm::MemIntrinsicBase< Derived >::setDestAlignment().
arg_begin() [1/2]
User::op_iterator llvm::CallBase::arg_begin () inline
Return the iterator pointing to the beginning of the argument list.
Definition at line 1206 of file InstrTypes.h.
References llvm::User::op_begin().
Referenced by arg_begin(), arg_empty(), arg_operands(), arg_size(), args(), changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::GCRelocateInst::getBasePtr(), llvm::GCRelocateInst::getDerivedPtr(), llvm::InlineFunction(), isArgOperand(), and llvm::makeGuardControlFlowExplicit().
arg_begin() [2/2]
User::const_op_iterator llvm::CallBase::arg_begin () const inline
Definition at line 1207 of file InstrTypes.h.
References arg_begin().
arg_empty()
bool llvm::CallBase::arg_empty () const inline
Definition at line 1228 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by hasInAllocaArgument().
arg_end() [1/2]
User::op_iterator llvm::CallBase::arg_end () inline
Return the iterator pointing to the end of the argument list.
Definition at line 1212 of file InstrTypes.h.
References data_operands_end(), and getNumTotalBundleOperands().
Referenced by arg_empty(), arg_end(), arg_operands(), arg_size(), args(), changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::InlineFunction(), isArgOperand(), and llvm::makeGuardControlFlowExplicit().
arg_end() [2/2]
User::const_op_iterator llvm::CallBase::arg_end () const inline
Definition at line 1217 of file InstrTypes.h.
References arg_end().
arg_operands() [1/2]
iterator_range< User::op_iterator > llvm::CallBase::arg_operands () inline
Definition at line 1233 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::InlineFunction(), markTails(), SimplifyNVVMIntrinsic(), upgradeAVX512MaskToSelect(), and llvm::UpgradeIntrinsicCall().
arg_operands() [2/2]
iterator_range< User::const_op_iterator > llvm::CallBase::arg_operands () const inline
Definition at line 1236 of file InstrTypes.h.
References arg_begin(), and arg_end().
arg_size()
unsigned llvm::CallBase::arg_size () const inline
Definition at line 1229 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by getNumArgOperands(), and hasInAllocaArgument().
args() [1/2]
iterator_range< User::op_iterator > llvm::CallBase::args () inline
Iteration adapter for range-for loops.
Definition at line 1222 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by hasArgument().
args() [2/2]
iterator_range< User::const_op_iterator > llvm::CallBase::args () const inline
Definition at line 1225 of file InstrTypes.h.
References arg_begin(), and arg_end().
bundle_op_info_begin() [1/2]
bundle_op_iterator llvm::CallBase::bundle_op_info_begin () inline
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
OperandBundleUser uses the descriptor area co-allocated with the host User to store some meta information about which operands are "normal" operands, and which ones belong to some operand bundle.
The layout of an operand bundle user is
     +-----------uint32_t End-------------------------------------+
     |                                                            |
     |  +--------uint32_t Begin--------------------+              |
     |  |                                          |              |
     ^  ^                                          v              v
|---—|---—|-—|-—|-—|-—|-—|------—|-—|------—|-—|--— | BOI0 | BOI1 | .. | DU | U0 | U1 | .. | BOI0_U0 | .. | BOI1_U0 | .. | Un |---—|---—|-—|-—|-—|-—|-—|------—|-—|------—|-—|--— v v ^ ^ | | | | | +-----—uint32_t Begin---------—+ | | | +--------—uint32_t End--------------------------—+
BOI0, BOI1 ... are descriptions of operand bundles in this User's use list. These descriptions are installed and managed by this class, and they're all instances of OperandBundleUser<T>::BundleOpInfo.
DU is an additional descriptor installed by User's 'operator new' to keep track of the 'BOI0 ... BOIN' co-allocation. OperandBundleUser does not access or modify DU in any way, it's an implementation detail private to User.
The regular Use& vector for the User starts at U0. The operand bundle uses are part of the Use& vector, just like normal uses. In the diagram above, the operand bundle uses start at BOI0_U0. Each instance of BundleOpInfo has information about a contiguous set of uses constituting an operand bundle, and the total set of operand bundle uses themselves form a contiguous set of uses (i.e. there are no gaps between uses corresponding to individual operand bundles).
This class does not know the location of the set of operand bundle uses within the use list – that is decided by the User using this class via the BeginIdx argument in populateBundleOperandInfos.
Currently operand bundle users with hung-off operands are not supported.
Definition at line 2023 of file InstrTypes.h.
References llvm::User::getDescriptor(), and hasDescriptor().
Referenced by bundle_op_info_begin(), bundle_op_infos(), getBundleOperandsStartIndex(), getNumOperandBundles(), getOperandBundleAt(), and hasIdenticalOperandBundleSchema().
bundle_op_info_begin() [2/2]
const_bundle_op_iterator llvm::CallBase::bundle_op_info_begin () const inline
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2033 of file InstrTypes.h.
References bundle_op_info_begin().
bundle_op_info_end() [1/2]
bundle_op_iterator llvm::CallBase::bundle_op_info_end () inline
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2040 of file InstrTypes.h.
References llvm::User::getDescriptor(), and hasDescriptor().
Referenced by bundle_op_info_end(), bundle_op_infos(), getBundleOperandsEndIndex(), getNumOperandBundles(), and hasIdenticalOperandBundleSchema().
bundle_op_info_end() [2/2]
const_bundle_op_iterator llvm::CallBase::bundle_op_info_end () const inline
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2050 of file InstrTypes.h.
References bundle_op_info_end().
bundle_op_infos() [1/2]
iterator_range< bundle_op_iterator > llvm::CallBase::bundle_op_infos () inline
Return the range [bundle_op_info_begin, bundle_op_info_end).
Definition at line 2056 of file InstrTypes.h.
References bundle_op_info_begin(), and bundle_op_info_end().
Referenced by getBundleOpInfoForOperand(), hasClobberingOperandBundles(), and populateBundleOperandInfos().
bundle_op_infos() [2/2]
iterator_range< const_bundle_op_iterator > llvm::CallBase::bundle_op_infos () const inline
Return the range [bundle_op_info_begin, bundle_op_info_end).
Definition at line 2061 of file InstrTypes.h.
References bundle_op_info_begin(), and bundle_op_info_end().
bundleOperandHasAttr()
bool llvm::CallBase::bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const inline
Return true if the bundle operand at index OpIdx has the attribute A.
Definition at line 1883 of file InstrTypes.h.
References getBundleOpInfoForOperand(), and operandBundleFromBundleOpInfo().
Referenced by dataOperandHasImpliedAttr().
cannotDuplicate()
bool llvm::CallBase::cannotDuplicate () const inline
Determine if the invoke cannot be duplicated.
Definition at line 1689 of file InstrTypes.h.
References hasFnAttr().
Referenced by FoldCondBranchOnPHI().
classof() [1/2]
static bool llvm::CallBase::classof (const Instruction * I) inline static
Definition at line 1135 of file InstrTypes.h.
References llvm::LazyCallGraph::Edge::Call, and I.
Referenced by classof().
classof() [2/2]
static bool llvm::CallBase::classof (const Value * V) inline static
Definition at line 1140 of file InstrTypes.h.
References classof().
CountBundleInputs()
static unsigned llvm::CallBase::CountBundleInputs (ArrayRef< OperandBundleDef > Bundles) inline static protected
Return the total number of values used in Bundles.
Definition at line 2088 of file InstrTypes.h.
Referenced by llvm::CallInst::Create(), and llvm::CallBrInst::Create().
countOperandBundlesOfType() [1/2]
unsigned llvm::CallBase::countOperandBundlesOfType (StringRef Name) const inline
Return the number of operand bundles with the tag Name attached to this instruction.
Definition at line 1784 of file InstrTypes.h.
References getNumOperandBundles(), and getOperandBundleAt().
Referenced by getOperandBundle().
countOperandBundlesOfType() [2/2]
unsigned llvm::CallBase::countOperandBundlesOfType (uint32_t ID) const inline
Return the number of operand bundles with the tag ID attached to this instruction.
Definition at line 1795 of file InstrTypes.h.
References getNumOperandBundles(), and getOperandBundleAt().
data_operands_begin() [1/2]
User::op_iterator llvm::CallBase::data_operands_begin () inline
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
For invokes, this is the set of instruction operands except the invoke target and the two successor blocks; and for calls this is the set of instruction operands except the call target.
Definition at line 1158 of file InstrTypes.h.
References llvm::User::op_begin().
Referenced by data_operands_begin(), data_operands_empty(), data_operands_size(), data_ops(), getDataOperandNo(), and isDataOperand().
data_operands_begin() [2/2]
User::const_op_iterator llvm::CallBase::data_operands_begin () const inline
Definition at line 1159 of file InstrTypes.h.
References data_operands_begin().
data_operands_empty()
bool llvm::CallBase::data_operands_empty () const inline
Definition at line 1176 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
data_operands_end() [1/2]
User::op_iterator llvm::CallBase::data_operands_end () inline
Definition at line 1162 of file InstrTypes.h.
References getNumSubclassExtraOperands(), and llvm::User::op_end().
Referenced by arg_end(), data_operands_empty(), data_operands_end(), data_operands_size(), data_ops(), and isDataOperand().
data_operands_end() [2/2]
User::const_op_iterator llvm::CallBase::data_operands_end () const inline
Definition at line 1167 of file InstrTypes.h.
References data_operands_end().
data_operands_size()
unsigned llvm::CallBase::data_operands_size () const inline
Definition at line 1179 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
data_ops() [1/2]
iterator_range< User::op_iterator > llvm::CallBase::data_ops () inline
Definition at line 1170 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
data_ops() [2/2]
iterator_range< User::const_op_iterator > llvm::CallBase::data_ops () const inline
Definition at line 1173 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
dataOperandHasImpliedAttr()
bool llvm::CallBase::dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const inline
Return true if the data operand at index i has the attribute A.
Data operands include call arguments and values used in operand bundles, but does not include the callee operand. This routine dispatches to the underlying AttributeList or the OperandBundleUser as appropriate.
The index i is interpreted as
i == Attribute::ReturnIndex -> the return value i in [1, arg_size + 1) -> argument number (i - 1) i in [arg_size + 1, data_operand_size + 1) -> bundle operand at index (i - 1) in the operand list.
Definition at line 1498 of file InstrTypes.h.
References assert(), bundleOperandHasAttr(), getBundleOperandsStartIndex(), getNumArgOperands(), getNumTotalBundleOperands(), hasOperandBundles(), hasRetAttr(), paramHasAttr(), and llvm::AttributeList::ReturnIndex.
Referenced by doesNotAccessMemory(), doesNotCapture(), doesNotReadMemory(), and onlyReadsMemory().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::CallBase::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
doesNoCfCheck()
bool llvm::CallBase::doesNoCfCheck () const inline
Determine if the call should not perform indirect branch tracking.
Definition at line 1680 of file InstrTypes.h.
References hasFnAttr().
doesNotAccessMemory() [1/2]
bool llvm::CallBase::doesNotAccessMemory () const inline
Determine if the call does not access memory.
Definition at line 1625 of file InstrTypes.h.
References hasFnAttr(), and llvm::FunctionSummary::FFlags::ReadNone.
Referenced by doesNotReadMemory(), and onlyReadsMemory().
doesNotAccessMemory() [2/2]
bool llvm::CallBase::doesNotAccessMemory (unsigned OpNo) const inline
Definition at line 1551 of file InstrTypes.h.
References dataOperandHasImpliedAttr(), and llvm::FunctionSummary::FFlags::ReadNone.
Referenced by markTails().
doesNotCapture()
bool llvm::CallBase::doesNotCapture (unsigned OpNo) const inline
Determine whether this data operand is not captured.
Definition at line 1523 of file InstrTypes.h.
References dataOperandHasImpliedAttr().
doesNotReadMemory() [1/2]
bool llvm::CallBase::doesNotReadMemory () const inline
Determine if the call does not access or only writes memory.
Definition at line 1639 of file InstrTypes.h.
References doesNotAccessMemory(), hasFnAttr(), and llvm::ValueInfo::WriteOnly.
doesNotReadMemory() [2/2]
bool llvm::CallBase::doesNotReadMemory (unsigned OpNo) const inline
Definition at line 1564 of file InstrTypes.h.
References dataOperandHasImpliedAttr(), llvm::FunctionSummary::FFlags::ReadNone, and llvm::ValueInfo::WriteOnly.
doesNotReturn()
bool llvm::CallBase::doesNotReturn () const inline
Determine if the call cannot return.
Definition at line 1674 of file InstrTypes.h.
References hasFnAttr().
doesNotThrow()
bool llvm::CallBase::doesNotThrow () const inline
Determine if the call cannot unwind.
Definition at line 1683 of file InstrTypes.h.
References hasFnAttr().
Referenced by HandleCallsInBlockInlinedThroughInvoke(), and llvm::InstCombiner::visitCallInst().
getArgOperand()
Value * llvm::CallBase::getArgOperand (unsigned i) const inline
Definition at line 1241 of file InstrTypes.h.
References assert(), getNumArgOperands(), and llvm::User::getOperand().
Referenced by addIntrinsicToSummary(), computeArraySize(), eliminateRecursiveTailCall(), findAffectedValues(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), foldCtpop(), foldCttzCtlz(), llvm::VAStartInst::getArgList(), llvm::VAEndInst::getArgList(), llvm::GCRelocateInst::getBasePtrIndex(), llvm::GCRelocateInst::getDerivedPtrIndex(), llvm::VACopyInst::getDest(), llvm::ConstrainedFPIntrinsic::getExceptionBehavior(), llvm::InstrProfIncrementInst::getHash(), llvm::InstrProfValueProfileInst::getHash(), llvm::InstrProfIncrementInst::getIndex(), llvm::InstrProfValueProfileInst::getIndex(), llvm::MemIntrinsicBase< Derived >::getLength(), llvm::BinaryOpIntrinsic::getLHS(), llvm::InstrProfIncrementInst::getName(), llvm::InstrProfValueProfileInst::getName(), llvm::InstrProfIncrementInst::getNumCounters(), getParamByValType(), llvm::MemIntrinsicBase< Derived >::getRawDest(), llvm::AtomicMemIntrinsic::getRawElementSizeInBytes(), llvm::DbgVariableIntrinsic::getRawExpression(), llvm::DbgLabelInst::getRawLabel(), llvm::DbgVariableIntrinsic::getRawVariable(), getReturnedArgOperand(), llvm::BinaryOpIntrinsic::getRHS(), llvm::ConstrainedFPIntrinsic::getRoundingMode(), llvm::VACopyInst::getSrc(), llvm::GCProjectionInst::getStatepoint(), llvm::InstrProfIncrementInst::getStep(), llvm::InstrProfValueProfileInst::getTargetValue(), llvm::InstrProfValueProfileInst::getValueKind(), llvm::DbgVariableIntrinsic::getVariableLocation(), llvm::MemIntrinsic::getVolatileCst(), handleBrSelExpect(), handlePhiDef(), handleSwitchExpect(), InTreeUserNeedToExtract(), isDynamicConstant(), isLoadInvariantInLoop(), isReportingError(), llvm::GCProjectionInst::isTiedToInvoke(), lowerExpectIntrinsic(), llvm::lowerObjectSizeCall(), llvm::makeGuardControlFlowExplicit(), optimizeDoubleFP(), OptimizeEmptyGlobalCXXDtors(), PerformHeapAllocSRoA(), replaceUnaryCall(), simplifyInvariantGroupIntrinsic(), simplifyNeonTbl1(), simplifyNeonVld1(), SimplifyNVVMIntrinsic(), simplifyX86addcarry(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), llvm::JumpThreadingPass::ThreadGuard(), tryToMoveFreeBeforeNullTest(), tryToOptimizeStoreOfMallocToGlobal(), turnGuardIntoBranch(), upgradeAbs(), upgradeAVX512MaskToSelect(), upgradeIntMinMax(), llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), upgradeMaskedMove(), UpgradeMaskToInt(), upgradePMULDQ(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), upgradeX86vpcom(), UpgradeX86VPERMT2Intrinsics(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFree().
getArgOperandUse() [1/2]
Use & llvm::CallBase::getArgOperandUse (unsigned i) inline
Definition at line 1256 of file InstrTypes.h.
References assert(), getNumArgOperands(), and llvm::User::getOperandUse().
getArgOperandUse() [2/2]
const Use & llvm::CallBase::getArgOperandUse (unsigned i) const inline
Wrappers for getting the Use of a call argument.
Definition at line 1252 of file InstrTypes.h.
References assert(), getNumArgOperands(), and llvm::User::getOperandUse().
Referenced by llvm::MemIntrinsicBase< Derived >::getLengthUse(), and llvm::MemIntrinsicBase< Derived >::getRawDestUse().
getAttribute() [1/2]
Attribute llvm::CallBase::getAttribute (unsigned i, Attribute::AttrKind Kind) const inline
Get the attribute of a given kind at a position.
Definition at line 1464 of file InstrTypes.h.
References llvm::AttributeList::getAttribute(), and getAttributes().
getAttribute() [2/2]
Attribute llvm::CallBase::getAttribute (unsigned i, StringRef Kind) const inline
Get the attribute of a given kind at a position.
Definition at line 1469 of file InstrTypes.h.
References llvm::AttributeList::getAttribute(), and getAttributes().
getAttributes()
AttributeList llvm::CallBase::getAttributes () const inline
Return the parameter attributes for this call.
Definition at line 1366 of file InstrTypes.h.
References Attrs.
Referenced by addAttribute(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), addParamAttr(), changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), getAttribute(), getParamAttr(), llvm::InlineFunction(), removeAttribute(), and removeParamAttr().
getBundleOperandsEndIndex()
unsigned llvm::CallBase::getBundleOperandsEndIndex () const inline
Return the index of the last bundle operand in the Use array.
Definition at line 1742 of file InstrTypes.h.
References assert(), bundle_op_info_end(), llvm::CallBase::BundleOpInfo::End, and hasOperandBundles().
Referenced by getNumTotalBundleOperands(), and isBundleOperand().
getBundleOperandsStartIndex()
unsigned llvm::CallBase::getBundleOperandsStartIndex () const inline
Return the index of the first bundle operand in the Use array.
Definition at line 1736 of file InstrTypes.h.
References assert(), llvm::CallBase::BundleOpInfo::Begin, bundle_op_info_begin(), and hasOperandBundles().
Referenced by dataOperandHasImpliedAttr(), getNumTotalBundleOperands(), and isBundleOperand().
getBundleOpInfoForOperand()
const BundleOpInfo & llvm::CallBase::getBundleOpInfoForOperand (unsigned OpIdx) const inline
Return the BundleOpInfo for the operand at index OpIdx.
It is an error to call this with an OpIdx that does not correspond to an bundle operand.
Definition at line 2078 of file InstrTypes.h.
References bundle_op_infos(), and llvm_unreachable.
Referenced by bundleOperandHasAttr(), and getOperandBundleForOperand().
getCalledFunction()
Function * llvm::CallBase::getCalledFunction () const inline
Returns the function called, or null if this is an indirect function invocation.
Definition at line 1287 of file InstrTypes.h.
References getCalledOperand().
Referenced by addIntrinsicToSummary(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), findTRECandidate(), llvm::objcarc::GetARCInstKind(), getIntrinsicID(), llvm::IntrinsicInst::getIntrinsicID(), getReturnedArgOperand(), llvm::LoopVectorizationCostModel::getVectorCallCost(), handleBrSelExpect(), HandleCallsInBlockInlinedThroughInvoke(), handleSwitchExpect(), hasRetAttr(), llvm::InlineFunction(), isLocallyOpenedFile(), lowerExpectIntrinsic(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), optimizeDoubleFP(), paramHasAttr(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
getCalledOperand()
Value * llvm::CallBase::getCalledOperand () const inline
Definition at line 1276 of file InstrTypes.h.
Referenced by getCalledFunction(), getCalledValue(), llvm::InlineFunction(), and isInlineAsm().
getCalledOperandUse() [1/2]
Use & llvm::CallBase::getCalledOperandUse () inline
Definition at line 1283 of file InstrTypes.h.
getCalledOperandUse() [2/2]
const Use & llvm::CallBase::getCalledOperandUse () const inline
Definition at line 1282 of file InstrTypes.h.
Referenced by isCallee().
getCalledValue()
Value * llvm::CallBase::getCalledValue () const inline
Definition at line 1280 of file InstrTypes.h.
References getCalledOperand().
Referenced by changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), HandleCallsInBlockInlinedThroughInvoke(), isIndirectCall(), and llvm::InstCombiner::visitCallInst().
getCaller() [1/2]
Function * CallBase::getCaller ()
Helper to get the caller (the parent function).
Definition at line 264 of file Instructions.cpp.
References llvm::BasicBlock::getParent(), and llvm::Instruction::getParent().
Referenced by getCaller(), and isReturnNonNull().
getCaller() [2/2]
const Function * llvm::CallBase::getCaller () const inline
Definition at line 1304 of file InstrTypes.h.
References getCaller().
getCallingConv()
CallingConv::ID llvm::CallBase::getCallingConv () const inline
Definition at line 1344 of file InstrTypes.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::InlineFunction(), isCallingConvCCompatible(), llvm::makeGuardControlFlowExplicit(), and turnToExplicitForm().
getDataOperandNo() [1/2]
unsigned llvm::CallBase::getDataOperandNo (const Use * U) const inline
Given a use for a data operand, get the data operand number that corresponds to it.
Definition at line 1200 of file InstrTypes.h.
References assert(), data_operands_begin(), and isDataOperand().
getDataOperandNo() [2/2]
unsigned llvm::CallBase::getDataOperandNo (Value::const_user_iterator UI) const inline
Given a value use iterator, return the data operand corresponding to it.
Iterator must actually correspond to a data operand.
Definition at line 1194 of file InstrTypes.h.
References getDataOperandNo().
Referenced by getDataOperandNo().
getDereferenceableBytes()
uint64_t llvm::CallBase::getDereferenceableBytes (unsigned i) const inline
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 1585 of file InstrTypes.h.
References Attrs, and llvm::AttributeList::getDereferenceableBytes().
Referenced by isReturnNonNull().
getDereferenceableOrNullBytes()
uint64_t llvm::CallBase::getDereferenceableOrNullBytes (unsigned i) const inline
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
Definition at line 1591 of file InstrTypes.h.
References Attrs, and llvm::AttributeList::getDereferenceableOrNullBytes().
getFunctionType()
FunctionType * llvm::CallBase::getFunctionType () const inline
Definition at line 1144 of file InstrTypes.h.
References FTy.
Referenced by changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::InlineFunction(), isCallingConvCCompatible(), and llvm::InstCombiner::visitCallInst().
getIntrinsicID()
Intrinsic::ID CallBase::getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
Definition at line 296 of file Instructions.cpp.
References F, getCalledFunction(), and llvm::Intrinsic::not_intrinsic.
Referenced by llvm::InlineFunction().
getNumArgOperands()
unsigned llvm::CallBase::getNumArgOperands () const inline
Definition at line 1239 of file InstrTypes.h.
References arg_size().
Referenced by addParamAttr(), dataOperandHasImpliedAttr(), eliminateRecursiveTailCall(), getArgOperand(), getArgOperandUse(), llvm::ConstrainedFPIntrinsic::getExceptionBehavior(), llvm::CallBrInst::getIndirectDestLabel(), llvm::CallBrInst::getIndirectDestLabelUse(), getParamAttr(), llvm::ConstrainedFPIntrinsic::getRoundingMode(), hasStructRetAttr(), InTreeUserNeedToExtract(), isReportingError(), paramHasAttr(), removeParamAttr(), setArgOperand(), upgradeAbs(), upgradeAVX512MaskToSelect(), upgradeIntMinMax(), llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), upgradePMULDQ(), UpgradeX86AddSubSatIntrinsics(), upgradeX86ConcatShift(), upgradeX86Rotate(), and llvm::InstCombiner::visitCallInst().
getNumOperandBundles()
unsigned llvm::CallBase::getNumOperandBundles () const inline
Return the number of operand bundles associated with this User.
Definition at line 1728 of file InstrTypes.h.
References bundle_op_info_begin(), and bundle_op_info_end().
Referenced by llvm::CallInst::cloneImpl(), llvm::InvokeInst::cloneImpl(), llvm::CallBrInst::cloneImpl(), countOperandBundlesOfType(), getOperandBundle(), getOperandBundleAt(), getOperandBundlesAsDefs(), hasIdenticalOperandBundleSchema(), hasOperandBundles(), and hasOperandBundlesOtherThan().
getNumSubclassExtraOperands()
unsigned llvm::CallBase::getNumSubclassExtraOperands () const inline protected
Definition at line 1116 of file InstrTypes.h.
References llvm::LazyCallGraph::Edge::Call, getNumSubclassExtraOperandsDynamic(), llvm::Instruction::getOpcode(), and llvm_unreachable.
Referenced by data_operands_end().
getNumSubclassExtraOperandsDynamic()
unsigned CallBase::getNumSubclassExtraOperandsDynamic () const protected
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Definition at line 266 of file Instructions.cpp.
References assert(), and llvm::Instruction::getOpcode().
Referenced by getNumSubclassExtraOperands().
getNumTotalBundleOperands()
unsigned llvm::CallBase::getNumTotalBundleOperands () const inline
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
Definition at line 1765 of file InstrTypes.h.
References assert(), getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), and hasOperandBundles().
Referenced by arg_end(), dataOperandHasImpliedAttr(), llvm::CallBrInst::getIndirectDestLabel(), and llvm::CallBrInst::getIndirectDestLabelUse().
getOperandBundle() [1/2]
Optional< OperandBundleUse > llvm::CallBase::getOperandBundle (StringRef Name) const inline
Return an operand bundle by name, if present.
It is an error to call this for operand bundle types that may have multiple instances of them on the same instruction.
Definition at line 1808 of file InstrTypes.h.
References assert(), countOperandBundlesOfType(), getNumOperandBundles(), getOperandBundleAt(), llvm::OperandBundleUse::getTagName(), and llvm::None.
Referenced by HandleCallsInBlockInlinedThroughInvoke(), and llvm::makeGuardControlFlowExplicit().
getOperandBundle() [2/2]
Optional< OperandBundleUse > llvm::CallBase::getOperandBundle (uint32_t ID) const inline
Return an operand bundle by tag ID, if present.
It is an error to call this for operand bundle types that may have multiple instances of them on the same instruction.
Definition at line 1824 of file InstrTypes.h.
References assert(), countOperandBundlesOfType(), getNumOperandBundles(), getOperandBundleAt(), llvm::OperandBundleUse::getTagID(), and llvm::None.
getOperandBundleAt()
OperandBundleUse llvm::CallBase::getOperandBundleAt (unsigned Index) const inline
Return the operand bundle at a specific index.
Definition at line 1777 of file InstrTypes.h.
References assert(), bundle_op_info_begin(), getNumOperandBundles(), and operandBundleFromBundleOpInfo().
Referenced by countOperandBundlesOfType(), getOperandBundle(), getOperandBundlesAsDefs(), and hasOperandBundlesOtherThan().
getOperandBundleForOperand()
OperandBundleUse llvm::CallBase::getOperandBundleForOperand (unsigned OpIdx) const inline
Return the operand bundle for the operand at index OpIdx.
It is an error to call this with an OpIdx that does not correspond to an bundle operand.
Definition at line 1852 of file InstrTypes.h.
References getBundleOpInfoForOperand(), and operandBundleFromBundleOpInfo().
getOperandBundlesAsDefs()
void llvm::CallBase::getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > & Defs) const inline
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
This function copies the OperandBundeUse instances associated with this OperandBundleUser to a vector of OperandBundleDefs. Note: OperandBundeUses and OperandBundleDefs are non-trivially different representations of operand bundles (see documentation above).
Definition at line 1843 of file InstrTypes.h.
References getNumOperandBundles(), and getOperandBundleAt().
Referenced by changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::InlineFunction(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), PerformHeapAllocSRoA(), and tryToOptimizeStoreOfMallocToGlobal().
getParamAlignment()
unsigned llvm::CallBase::getParamAlignment (unsigned ArgNo) const inline
Extract the alignment for a call or parameter (0=unknown).
Definition at line 1573 of file InstrTypes.h.
References Attrs, and llvm::AttributeList::getParamAlignment().
Referenced by llvm::MemIntrinsicBase< Derived >::getDestAlignment().
getParamAttr() [1/2]
Attribute llvm::CallBase::getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Get the attribute of a given kind from a given arg.
Definition at line 1474 of file InstrTypes.h.
References assert(), getAttributes(), getNumArgOperands(), and llvm::AttributeList::getParamAttr().
getParamAttr() [2/2]
Attribute llvm::CallBase::getParamAttr (unsigned ArgNo, StringRef Kind) const inline
Get the attribute of a given kind from a given arg.
Definition at line 1480 of file InstrTypes.h.
References assert(), getAttributes(), getNumArgOperands(), and llvm::AttributeList::getParamAttr().
getParamByValType()
Type * llvm::CallBase::getParamByValType (unsigned ArgNo) const inline
Extract the byval type for a call or parameter.
Definition at line 1578 of file InstrTypes.h.
References Attrs, getArgOperand(), llvm::AttributeList::getParamByValType(), llvm::Type::getPointerElementType(), and llvm::Value::getType().
getRetAlignment()
unsigned llvm::CallBase::getRetAlignment () const inline
Extract the alignment of the return value.
Definition at line 1570 of file InstrTypes.h.
References Attrs, and llvm::AttributeList::getRetAlignment().
getReturnedArgOperand()
Value * CallBase::getReturnedArgOperand () const
If one of the arguments has the 'returned' attribute, returns its operand value.
Otherwise, return nullptr.
Definition at line 314 of file Instructions.cpp.
References Attrs, F, llvm::AttributeList::FirstArgIndex, getArgOperand(), getCalledFunction(), and llvm::AttributeList::hasAttrSomewhere().
hasArgument()
bool llvm::CallBase::hasArgument (const Value * V) const inline
Returns true if this CallSite passes the given Value* as an argument to the called function.
Definition at line 1272 of file InstrTypes.h.
References args().
hasByValArgument()
bool llvm::CallBase::hasByValArgument () const inline
Determine if any call argument is an aggregate passed by value.
Definition at line 1714 of file InstrTypes.h.
References Attrs, and llvm::AttributeList::hasAttrSomewhere().
hasClobberingOperandBundles()
bool llvm::CallBase::hasClobberingOperandBundles () const inline
Return true if this operand bundle user has operand bundles that may write to the heap.
Definition at line 1867 of file InstrTypes.h.
References bundle_op_infos(), llvm::LLVMContext::OB_deopt, and llvm::LLVMContext::OB_funclet.
Referenced by isFnAttrDisallowedByOpBundle().
hasDescriptor()
bool llvm::CallBase::hasDescriptor () const inline protected
Definition at line 1114 of file InstrTypes.h.
References llvm::Value::HasDescriptor.
Referenced by bundle_op_info_begin(), and bundle_op_info_end().
hasFnAttr() [1/2]
bool llvm::CallBase::hasFnAttr (Attribute::AttrKind Kind) const inline
Determine whether this call has the given attribute.
Definition at line 1373 of file InstrTypes.h.
References assert().
Referenced by cannotDuplicate(), llvm::CallInst::canReturnTwice(), doesNoCfCheck(), doesNotAccessMemory(), doesNotReadMemory(), doesNotReturn(), doesNotThrow(), isConvergent(), isNoInline(), isStrictFP(), isTrigLibCall(), onlyAccessesArgMemory(), onlyAccessesInaccessibleMemOrArgMem(), onlyAccessesInaccessibleMemory(), and onlyReadsMemory().
hasFnAttr() [2/2]
bool llvm::CallBase::hasFnAttr (StringRef Kind) const inline
Determine whether this call has the given attribute.
Definition at line 1380 of file InstrTypes.h.
hasIdenticalOperandBundleSchema()
bool llvm::CallBase::hasIdenticalOperandBundleSchema (const CallBase & Other) const inline
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
Definition at line 1892 of file InstrTypes.h.
References bundle_op_info_begin(), bundle_op_info_end(), and getNumOperandBundles().
hasInAllocaArgument()
bool llvm::CallBase::hasInAllocaArgument () const inline
Determine if there are is an inalloca argument.
Only the last argument can have the inalloca attribute.
Definition at line 1545 of file InstrTypes.h.
References arg_empty(), arg_size(), and paramHasAttr().
hasOperandBundles()
bool llvm::CallBase::hasOperandBundles () const inline
Return true if this User has any operand bundles.
Definition at line 1733 of file InstrTypes.h.
References getNumOperandBundles().
Referenced by llvm::CallInst::cloneImpl(), llvm::InvokeInst::cloneImpl(), llvm::CallBrInst::cloneImpl(), dataOperandHasImpliedAttr(), getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), getNumTotalBundleOperands(), hasReadingOperandBundles(), isBundleOperand(), and markTails().
hasOperandBundlesOtherThan()
bool llvm::CallBase::hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const inline
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
Definition at line 1902 of file InstrTypes.h.
References getNumOperandBundles(), getOperandBundleAt(), and llvm::OperandBundleUse::getTagID().
hasReadingOperandBundles()
bool llvm::CallBase::hasReadingOperandBundles () const inline
Return true if this operand bundle user has operand bundles that may read from the heap.
Definition at line 1858 of file InstrTypes.h.
References hasOperandBundles().
Referenced by isFnAttrDisallowedByOpBundle().
hasRetAttr()
bool CallBase::hasRetAttr (Attribute::AttrKind Kind) const
Determine whether the return value has the given attribute.
Definition at line 327 of file Instructions.cpp.
References Attrs, F, getCalledFunction(), llvm::AttributeList::hasAttribute(), and llvm::AttributeList::ReturnIndex.
Referenced by dataOperandHasImpliedAttr(), isReturnNonNull(), and llvm::InstCombiner::visitCallInst().
hasStructRetAttr()
bool llvm::CallBase::hasStructRetAttr () const inline
Determine if the call returns a structure through first pointer argument.
Definition at line 1705 of file InstrTypes.h.
References getNumArgOperands(), and paramHasAttr().
Instruction() [1/3]
llvm::Instruction::Instruction (const Instruction &) protected delete
Instruction() [2/3]
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, BasicBlock * InsertAtEnd) protected
Definition at line 765 of file Instruction.cpp.
Instruction() [3/3]
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, Instruction * InsertBefore = nullptr) protected
Definition at line 763 of file Instruction.cpp.
isArgOperand() [1/2]
bool llvm::CallBase::isArgOperand (const Use * U) const inline
Definition at line 1261 of file InstrTypes.h.
References arg_begin(), arg_end(), and assert().
Referenced by isArgOperand().
isArgOperand() [2/2]
bool llvm::CallBase::isArgOperand (Value::const_user_iterator UI) const inline
Definition at line 1266 of file InstrTypes.h.
References isArgOperand().
isBundleOperand() [1/3]
bool llvm::CallBase::isBundleOperand (const Use * U) const inline
Returns true if the use is a bundle operand.
Definition at line 1754 of file InstrTypes.h.
References assert(), hasOperandBundles(), isBundleOperand(), and llvm::User::op_begin().
isBundleOperand() [2/3]
bool llvm::CallBase::isBundleOperand (unsigned Idx) const inline
Return true if the operand at index Idx is a bundle operand.
Definition at line 1748 of file InstrTypes.h.
References getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), hasOperandBundles(), and Idx.
Referenced by isBundleOperand().
isBundleOperand() [3/3]
bool llvm::CallBase::isBundleOperand (Value::const_user_iterator UI) const inline
Definition at line 1759 of file InstrTypes.h.
References isBundleOperand().
isByValArgument()
bool llvm::CallBase::isByValArgument (unsigned ArgNo) const inline
Determine whether this argument is passed by value.
Definition at line 1528 of file InstrTypes.h.
References paramHasAttr().
isByValOrInAllocaArgument()
bool llvm::CallBase::isByValOrInAllocaArgument (unsigned ArgNo) const inline
Determine whether this argument is passed by value or in an alloca.
Definition at line 1538 of file InstrTypes.h.
References paramHasAttr().
isCallee() [1/2]
bool llvm::CallBase::isCallee (const Use * U) const inline
Determine whether this Use is the callee operand's Use.
Definition at line 1300 of file InstrTypes.h.
References getCalledOperandUse().
isCallee() [2/2]
bool llvm::CallBase::isCallee (Value::const_user_iterator UI) const inline
Determine whether the passed iterator points to the callee operand's Use.
Definition at line 1295 of file InstrTypes.h.
References isCallee().
Referenced by isCallee().
isConvergent()
bool llvm::CallBase::isConvergent () const inline
Determine if the invoke is convergent.
Definition at line 1695 of file InstrTypes.h.
References hasFnAttr().
Referenced by FoldCondBranchOnPHI().
isDataOperand() [1/2]
bool llvm::CallBase::isDataOperand (const Use * U) const inline
Definition at line 1183 of file InstrTypes.h.
References assert(), data_operands_begin(), and data_operands_end().
Referenced by getDataOperandNo(), and isDataOperand().
isDataOperand() [2/2]
bool llvm::CallBase::isDataOperand (Value::const_user_iterator UI) const inline
Definition at line 1188 of file InstrTypes.h.
References isDataOperand().
isFnAttrDisallowedByOpBundle() [1/2]
bool llvm::CallBase::isFnAttrDisallowedByOpBundle (Attribute::AttrKind A) const inline
Is the function attribute A disallowed by some operand bundle on this operand bundle user?
Definition at line 1921 of file InstrTypes.h.
References hasClobberingOperandBundles(), hasReadingOperandBundles(), llvm_unreachable, llvm::FunctionSummary::FFlags::ReadNone, and llvm::ValueInfo::ReadOnly.
isFnAttrDisallowedByOpBundle() [2/2]
bool llvm::CallBase::isFnAttrDisallowedByOpBundle (StringRef S) const inline
Is the function attribute S disallowed by some operand bundle on this operand bundle user?
Definition at line 1913 of file InstrTypes.h.
isInAllocaArgument()
bool llvm::CallBase::isInAllocaArgument (unsigned ArgNo) const inline
Determine whether this argument is passed in an alloca.
Definition at line 1533 of file InstrTypes.h.
References paramHasAttr().
isIndirectCall()
bool CallBase::isIndirectCall () const
Return true if the callsite is an indirect call.
Definition at line 271 of file Instructions.cpp.
References getCalledValue().
isInlineAsm()
bool llvm::CallBase::isInlineAsm () const inline
Check if this call is an inline asm statement.
Definition at line 1356 of file InstrTypes.h.
References getCalledOperand().
isMustTailCall()
bool CallBase::isMustTailCall () const
Tests if this call site must be tail call optimized.
Only a CallInst can be tail call optimized.
Definition at line 283 of file Instructions.cpp.
isNoBuiltin()
bool llvm::CallBase::isNoBuiltin () const inline
Return true if the call should not be treated as a call to a builtin.
Definition at line 1611 of file InstrTypes.h.
Referenced by llvm::LoopVectorizationCostModel::getVectorCallCost(), and llvm::LibCallSimplifier::optimizeCall().
isNoInline()
bool llvm::CallBase::isNoInline () const inline
Return true if the call should not be inlined.
Definition at line 1620 of file InstrTypes.h.
References hasFnAttr(), and llvm::FunctionSummary::FFlags::NoInline.
isReturnNonNull()
bool CallBase::isReturnNonNull () const
Return true if the return value is known to be not null.
This may be because it has the nonnull attribute, or because at least one byte is dereferenceable and the pointer is in addrspace(0).
Definition at line 302 of file Instructions.cpp.
References getCaller(), getDereferenceableBytes(), llvm::Value::getType(), hasRetAttr(), llvm::NullPointerIsDefined(), and llvm::AttributeList::ReturnIndex.
isStrictFP()
bool llvm::CallBase::isStrictFP () const inline
Determine if the call requires strict floating point semantics.
Definition at line 1617 of file InstrTypes.h.
References hasFnAttr().
isTailCall()
bool CallBase::isTailCall () const
Tests if this call site is marked as a tail call.
Definition at line 290 of file Instructions.cpp.
mutateFunctionType()
void llvm::CallBase::mutateFunctionType (FunctionType * FTy) inline
Definition at line 1146 of file InstrTypes.h.
References FTy, llvm::FunctionType::getReturnType(), and llvm::Value::mutateType().
onlyAccessesArgMemory()
bool llvm::CallBase::onlyAccessesArgMemory () const inline
Determine if the call can access memmory only using pointers based on its arguments.
Definition at line 1648 of file InstrTypes.h.
References hasFnAttr().
onlyAccessesInaccessibleMemOrArgMem()
bool llvm::CallBase::onlyAccessesInaccessibleMemOrArgMem () const inline
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
Definition at line 1666 of file InstrTypes.h.
References hasFnAttr().
onlyAccessesInaccessibleMemory()
bool llvm::CallBase::onlyAccessesInaccessibleMemory () const inline
Determine if the function may only access memory that is inaccessible from the IR.
Definition at line 1657 of file InstrTypes.h.
References hasFnAttr().
onlyReadsMemory() [1/2]
bool llvm::CallBase::onlyReadsMemory () const inline
Determine if the call does not access or only reads memory.
Definition at line 1631 of file InstrTypes.h.
References doesNotAccessMemory(), hasFnAttr(), and llvm::ValueInfo::ReadOnly.
onlyReadsMemory() [2/2]
bool llvm::CallBase::onlyReadsMemory (unsigned OpNo) const inline
Definition at line 1557 of file InstrTypes.h.
References dataOperandHasImpliedAttr(), llvm::FunctionSummary::FFlags::ReadNone, and llvm::ValueInfo::ReadOnly.
operandBundleFromBundleOpInfo()
OperandBundleUse llvm::CallBase::operandBundleFromBundleOpInfo (const BundleOpInfo & BOI) const inline
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
Definition at line 1968 of file InstrTypes.h.
References llvm::CallBase::BundleOpInfo::Begin, llvm::CallBase::BundleOpInfo::End, llvm::User::op_begin(), and llvm::CallBase::BundleOpInfo::Tag.
Referenced by bundleOperandHasAttr(), getOperandBundleAt(), and getOperandBundleForOperand().
paramHasAttr()
bool CallBase::paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
Definition at line 338 of file Instructions.cpp.
References assert(), Attrs, F, getCalledFunction(), getNumArgOperands(), and llvm::AttributeList::hasParamAttribute().
Referenced by dataOperandHasImpliedAttr(), hasInAllocaArgument(), hasStructRetAttr(), isByValArgument(), isByValOrInAllocaArgument(), and isInAllocaArgument().
populateBundleOperandInfos()
CallBase::op_iterator CallBase::populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
Return the op_iterator pointing to the Use& one past the last last bundle operand use.
Each OperandBundleDef instance is tracked by a OperandBundleInfo instance allocated in this User's descriptor.
Definition at line 361 of file Instructions.cpp.
References assert(), bundle_op_infos(), llvm::Value::getContext(), llvm::User::op_begin(), and llvm::LLVMContext::pImpl.
removeAttribute() [1/2]
void llvm::CallBase::removeAttribute (unsigned i, Attribute::AttrKind Kind) inline
removes the attribute from the list of attributes.
Definition at line 1413 of file InstrTypes.h.
References getAttributes(), llvm::Value::getContext(), llvm::AttributeList::removeAttribute(), and setAttributes().
Referenced by setNotConvergent().
removeAttribute() [2/2]
void llvm::CallBase::removeAttribute (unsigned i, StringRef Kind) inline
removes the attribute from the list of attributes.
Definition at line 1420 of file InstrTypes.h.
References getAttributes(), llvm::Value::getContext(), llvm::AttributeList::removeAttribute(), and setAttributes().
removeParamAttr() [1/2]
void llvm::CallBase::removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) inline
Removes the attribute from the given argument.
Definition at line 1427 of file InstrTypes.h.
References assert(), getAttributes(), llvm::Value::getContext(), getNumArgOperands(), llvm::AttributeList::removeParamAttribute(), and setAttributes().
Referenced by llvm::MemIntrinsicBase< Derived >::setDestAlignment().
removeParamAttr() [2/2]
void llvm::CallBase::removeParamAttr (unsigned ArgNo, StringRef Kind) inline
Removes the attribute from the given argument.
Definition at line 1435 of file InstrTypes.h.
References assert(), getAttributes(), llvm::Value::getContext(), getNumArgOperands(), llvm::AttributeList::removeParamAttribute(), and setAttributes().
returnDoesNotAlias()
bool llvm::CallBase::returnDoesNotAlias () const inline
Determine if the return value is marked with NoAlias attribute.
Definition at line 1601 of file InstrTypes.h.
References Attrs, llvm::AttributeList::hasAttribute(), llvm::NoAlias, and llvm::AttributeList::ReturnIndex.
setArgOperand()
void llvm::CallBase::setArgOperand (unsigned i, Value * v) inline
Definition at line 1246 of file InstrTypes.h.
References assert(), getNumArgOperands(), and llvm::User::setOperand().
Referenced by createCoroSave(), llvm::MemIntrinsicBase< Derived >::setDest(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), llvm::MemIntrinsicBase< Derived >::setLength(), llvm::MemIntrinsic::setVolatile(), turnGuardIntoBranch(), and llvm::InstCombiner::visitCallInst().
setAttributes()
void llvm::CallBase::setAttributes (AttributeList A) inline
Set the parameter attributes for this call.
Definition at line 1370 of file InstrTypes.h.
References Attrs.
Referenced by addAttribute(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), addParamAttr(), changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::emitBinaryFloatFnCall(), emitUnaryFloatFnCallHelper(), INITIALIZE_PASS(), llvm::InlineFunction(), makeStatepointExplicitImpl(), removeAttribute(), and removeParamAttr().
setCalledFunction() [1/3]
void llvm::CallBase::setCalledFunction (Function * Fn) inline
Sets the function called, including updating the function type.
Definition at line 1323 of file InstrTypes.h.
References llvm::Function::getFunctionType(), and setCalledFunction().
Referenced by setCalledFunction(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
setCalledFunction() [2/3]
void llvm::CallBase::setCalledFunction (FunctionCallee Fn) inline
Sets the function called, including updating the function type.
Definition at line 1328 of file InstrTypes.h.
References llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and setCalledFunction().
setCalledFunction() [3/3]
void llvm::CallBase::setCalledFunction (FunctionType * FTy, Value * Fn) inline
Sets the function called, including updating to the specified function type.
Definition at line 1334 of file InstrTypes.h.
References assert(), FTy, llvm::FunctionType::getReturnType(), llvm::Value::getType(), and setCalledOperand().
setCalledOperand()
void llvm::CallBase::setCalledOperand (Value * V) inline
Definition at line 1320 of file InstrTypes.h.
Referenced by setCalledFunction().
setCallingConv()
void llvm::CallBase::setCallingConv (CallingConv::ID CC) inline
Definition at line 1348 of file InstrTypes.h.
References assert(), llvm::Instruction::getSubclassDataFromInstruction(), llvm::CallingConv::MaxID, and llvm::Instruction::setInstructionSubclassData().
Referenced by changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), createFree(), CreateGCRelocates(), createMalloc(), llvm::emitBinaryFloatFnCall(), llvm::emitCalloc(), llvm::emitFGetCUnlocked(), llvm::emitFGetSUnlocked(), llvm::emitFPutC(), llvm::emitFPutCUnlocked(), llvm::emitFPutS(), llvm::emitFPutSUnlocked(), llvm::emitFReadUnlocked(), llvm::emitFWrite(), llvm::emitFWriteUnlocked(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitUnaryFloatFnCallHelper(), INITIALIZE_PASS(), llvm::InlineFunction(), makeStatepointExplicitImpl(), and turnToExplicitForm().
setCannotDuplicate()
void llvm::CallBase::setCannotDuplicate () inline
Definition at line 1690 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
setConvergent()
void llvm::CallBase::setConvergent () inline
Definition at line 1696 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
setDoesNotAccessMemory()
void llvm::CallBase::setDoesNotAccessMemory () inline
Definition at line 1626 of file InstrTypes.h.
References addAttribute(), llvm::AttributeList::FunctionIndex, and llvm::FunctionSummary::FFlags::ReadNone.
setDoesNotReadMemory()
void llvm::CallBase::setDoesNotReadMemory () inline
Definition at line 1642 of file InstrTypes.h.
References addAttribute(), llvm::AttributeList::FunctionIndex, and llvm::ValueInfo::WriteOnly.
setDoesNotReturn()
void llvm::CallBase::setDoesNotReturn () inline
Definition at line 1675 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
Referenced by addBoundsChecking().
setDoesNotThrow()
void llvm::CallBase::setDoesNotThrow () inline
Definition at line 1684 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
Referenced by addBoundsChecking(), llvm::InlineFunction(), and llvm::InstCombiner::visitCallInst().
setIsNoInline()
void llvm::CallBase::setIsNoInline () inline
Definition at line 1621 of file InstrTypes.h.
References addAttribute(), llvm::AttributeList::FunctionIndex, and llvm::FunctionSummary::FFlags::NoInline.
setNotConvergent()
void llvm::CallBase::setNotConvergent () inline
Definition at line 1699 of file InstrTypes.h.
References llvm::AttributeList::FunctionIndex, and removeAttribute().
setOnlyAccessesArgMemory()
void llvm::CallBase::setOnlyAccessesArgMemory () inline
Definition at line 1651 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
setOnlyAccessesInaccessibleMemOrArgMem()
void llvm::CallBase::setOnlyAccessesInaccessibleMemOrArgMem () inline
Definition at line 1669 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
setOnlyAccessesInaccessibleMemory()
void llvm::CallBase::setOnlyAccessesInaccessibleMemory () inline
Definition at line 1660 of file InstrTypes.h.
References addAttribute(), and llvm::AttributeList::FunctionIndex.
setOnlyReadsMemory()
void llvm::CallBase::setOnlyReadsMemory () inline
Definition at line 1634 of file InstrTypes.h.
References addAttribute(), llvm::AttributeList::FunctionIndex, and llvm::ValueInfo::ReadOnly.
Member Data Documentation
Attrs
AttributeList llvm::CallBase::Attrs protected
parameter attributes for callable
Definition at line 1105 of file InstrTypes.h.
Referenced by getAttributes(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getParamAlignment(), getParamByValType(), getRetAlignment(), getReturnedArgOperand(), hasByValArgument(), hasRetAttr(), paramHasAttr(), returnDoesNotAlias(), and setAttributes().
CalledOperandOpEndIdx
constexpr int llvm::CallBase::CalledOperandOpEndIdx = -1 static constexpr protected
The last operand is the called operand.
Definition at line 1103 of file InstrTypes.h.
FTy
FunctionType* llvm::CallBase::FTy protected
Definition at line 1106 of file InstrTypes.h.
Referenced by getFunctionType(), mutateFunctionType(), and setCalledFunction().
The documentation for this class was generated from the following files:
include/llvm/IR/InstrTypes.h
lib/IR/Instructions.cpp