LLVM: llvm::sys::SmartRWMutex< mt_only > Class Template Reference
llvm::sys::SmartRWMutex< mt_only > Class Template Reference
SmartMutex - An R/W mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
#include "llvm/Support/RWMutex.h"
Public Member Functions
SmartRWMutex ()=default
SmartRWMutex (const SmartRWMutex< mt_only > &original)=delete
SmartRWMutex< mt_only > & operator= (const SmartRWMutex< mt_only > &)=delete
bool lock_shared ()
bool unlock_shared ()
bool lock ()
bool unlock ()
Detailed Description
template<bool mt_only>
class llvm::sys::SmartRWMutex< mt_only >
SmartMutex - An R/W mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
Definition at line 87 of file RWMutex.h.
Constructor & Destructor Documentation
SmartRWMutex() [1/2]
template<bool mt_only> llvm::sys::SmartRWMutex< mt_only >::SmartRWMutex () explicit default
SmartRWMutex() [2/2]
template<bool mt_only> llvm::sys::SmartRWMutex< mt_only >::SmartRWMutex (const SmartRWMutex< mt_only > & original) delete
Member Function Documentation
lock()
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::lock () inline
Definition at line 118 of file RWMutex.h.
References assert(), impl, and llvm::llvm_is_multithreaded().
lock_shared()
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::lock_shared () inline
Definition at line 97 of file RWMutex.h.
References impl, and llvm::llvm_is_multithreaded().
operator=()
template<bool mt_only> SmartRWMutex< mt_only > & llvm::sys::SmartRWMutex< mt_only >::operator= (const SmartRWMutex< mt_only > &) delete
unlock()
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::unlock () inline
Definition at line 129 of file RWMutex.h.
References assert(), impl, and llvm::llvm_is_multithreaded().
unlock_shared()
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::unlock_shared () inline
Definition at line 107 of file RWMutex.h.
References assert(), impl, and llvm::llvm_is_multithreaded().
The documentation for this class was generated from the following file:
include/llvm/Support/RWMutex.h