LLVM: llvm::TGLexer Class Reference
llvm::TGLexer Class Reference
TGLexer - TableGen Lexer class.
#include "TableGen/TGLexer.h"
Public Types
typedef std::map< std::string, SMLoc > DependenciesMapTy
Public Member Functions
TGLexer (SourceMgr &SrcMgr, ArrayRef< std::string > Macros)
tgtok::TokKind Lex ()
const DependenciesMapTy & getDependencies () const
tgtok::TokKind getCode () const
const std::string & getCurStrVal () const
int64_t getCurIntVal () const
std::pair< int64_t, unsigned > getCurBinaryIntVal () const
SMLoc getLoc () const
Detailed Description
TGLexer - TableGen Lexer class.
Definition at line 73 of file TGLexer.h.
Member Typedef Documentation
DependenciesMapTy
typedef std::map<std::string, SMLoc> llvm::TGLexer::DependenciesMapTy
Definition at line 90 of file TGLexer.h.
Constructor & Destructor Documentation
TGLexer()
TGLexer::TGLexer (SourceMgr & SrcMgr, ArrayRef< std::string > Macros)
Definition at line 46 of file TGLexer.cpp.
References llvm::ArrayRef< T >::begin(), llvm::StringRef::begin(), llvm::ArrayRef< T >::end(), and llvm::make_unique().
Member Function Documentation
getCode()
tgtok::TokKind llvm::TGLexer::getCode () const inline
Definition at line 106 of file TGLexer.h.
Referenced by llvm::TGParser::ParseFile().
getCurBinaryIntVal()
std::pair< int64_t, unsigned > llvm::TGLexer::getCurBinaryIntVal () const inline
Definition at line 118 of file TGLexer.h.
References assert(), and llvm::tgtok::BinaryIntVal.
getCurIntVal()
int64_t llvm::TGLexer::getCurIntVal () const inline
Definition at line 114 of file TGLexer.h.
References assert(), and llvm::tgtok::IntVal.
getCurStrVal()
const std::string & llvm::TGLexer::getCurStrVal () const inline
Definition at line 108 of file TGLexer.h.
References assert(), llvm::tgtok::CodeFragment, llvm::tgtok::Id, llvm::tgtok::StrVal, and llvm::tgtok::VarName.
getDependencies()
const DependenciesMapTy & llvm::TGLexer::getDependencies () const inline
Definition at line 102 of file TGLexer.h.
Referenced by llvm::TGParser::getDependencies().
getLoc()
SMLoc TGLexer::getLoc () const
Definition at line 63 of file TGLexer.cpp.
References llvm::SMLoc::getFromPointer().
Referenced by llvm::TGParser::TokError().
Lex()
tgtok::TokKind llvm::TGLexer::Lex () inline
Definition at line 98 of file TGLexer.h.
References llvm::StringRef::begin().
Referenced by llvm::TGParser::ParseFile().
The documentation for this class was generated from the following files:
lib/TableGen/TGLexer.h
lib/TableGen/TGLexer.cpp