LLVM: llvm::orc::rpc::RawByteChannel Class Reference
llvm::orc::rpc::RawByteChannel Class Reference abstract
Interface for byte-streams to be used with RPC.
#include "llvm/ExecutionEngine/Orc/RawByteChannel.h"
Public Member Functions
virtual ~RawByteChannel ()=default
virtual Error readBytes (char *Dst, unsigned Size)=0
Read Size bytes from the stream into *Dst.
virtual Error appendBytes (const char *Src, unsigned Size)=0
Read size bytes from *Src and append them to the stream.
virtual Error send ()=0
Flush the stream if possible.
template<typename FunctionIdT , typename SequenceIdT >
Error startSendMessage (const FunctionIdT &FnId, const SequenceIdT &SeqNo)
Notify the channel that we're starting a message send.
Error endSendMessage ()
Notify the channel that we're ending a message send.
template<typename FunctionIdT , typename SequenceNumberT >
Error startReceiveMessage (FunctionIdT &FnId, SequenceNumberT &SeqNo)
Notify the channel that we're starting a message receive.
Error endReceiveMessage ()
Notify the channel that we're ending a message receive.
std::mutex & getReadLock ()
Get the lock for stream reading.
std::mutex & getWriteLock ()
Get the lock for stream writing.
Detailed Description
Interface for byte-streams to be used with RPC.
Definition at line 26 of file RawByteChannel.h.
Constructor & Destructor Documentation
~RawByteChannel()
virtual llvm::orc::rpc::RawByteChannel::~RawByteChannel () virtual default
Member Function Documentation
appendBytes()
virtual Error llvm::orc::rpc::RawByteChannel::appendBytes (const char * Src, unsigned Size) pure virtual
Read size bytes from *Src and append them to the stream.
endReceiveMessage()
Error llvm::orc::rpc::RawByteChannel::endReceiveMessage () inline
Notify the channel that we're ending a message receive.
Unlocks the channel for reading.
Definition at line 72 of file RawByteChannel.h.
References llvm::Error::success().
endSendMessage()
Error llvm::orc::rpc::RawByteChannel::endSendMessage () inline
Notify the channel that we're ending a message send.
Unlocks the channel for writing.
Definition at line 53 of file RawByteChannel.h.
References llvm::Error::success().
getReadLock()
std::mutex & llvm::orc::rpc::RawByteChannel::getReadLock () inline
Get the lock for stream reading.
Definition at line 78 of file RawByteChannel.h.
getWriteLock()
std::mutex & llvm::orc::rpc::RawByteChannel::getWriteLock () inline
Get the lock for stream writing.
Definition at line 81 of file RawByteChannel.h.
readBytes()
virtual Error llvm::orc::rpc::RawByteChannel::readBytes (char * Dst, unsigned Size) pure virtual
Read Size bytes from the stream into *Dst.
send()
virtual Error llvm::orc::rpc::RawByteChannel::send () pure virtual
Flush the stream if possible.
startReceiveMessage()
template<typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::rpc::RawByteChannel::startReceiveMessage (FunctionIdT & FnId, SequenceNumberT & SeqNo) inline
Notify the channel that we're starting a message receive.
Locks the channel for reading.
Definition at line 61 of file RawByteChannel.h.
References llvm::orc::rpc::deserializeSeq(), and llvm::Error::success().
startSendMessage()
template<typename FunctionIdT , typename SequenceIdT > Error llvm::orc::rpc::RawByteChannel::startSendMessage (const FunctionIdT & FnId, const SequenceIdT & SeqNo) inline
Notify the channel that we're starting a message send.
Locks the channel for writing.
Definition at line 42 of file RawByteChannel.h.
References llvm::orc::rpc::serializeSeq(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RawByteChannel.h