LLVM: llvm::SafepointIRVerifierPass Class Reference
llvm::SafepointIRVerifierPass Class Reference
Create an instance of the safepoint verifier pass which can be added to a pass pipeline to check for relocation bugs.
#include "llvm/IR/SafepointIRVerifier.h"
Public Member Functions
SafepointIRVerifierPass ()
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SafepointIRVerifierPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Create an instance of the safepoint verifier pass which can be added to a pass pipeline to check for relocation bugs.
Definition at line 37 of file SafepointIRVerifier.h.
Constructor & Destructor Documentation
SafepointIRVerifierPass()
llvm::SafepointIRVerifierPass::SafepointIRVerifierPass () inline explicit
Definition at line 40 of file SafepointIRVerifier.h.
Member Function Documentation
run()
PreservedAnalyses llvm::SafepointIRVerifierPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 201 of file SafepointIRVerifier.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and Verify().
The documentation for this class was generated from the following files:
include/llvm/IR/SafepointIRVerifier.h
lib/IR/SafepointIRVerifier.cpp