LLVM: lib/Transforms/Utils/CloneModule.cpp File Reference
CloneModule.cpp File Reference
#include "llvm/IR/Constant.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
Functions
static void copyComdat (GlobalObject *Dst, const GlobalObject *Src)
LLVMModuleRef LLVMCloneModule (LLVMModuleRef M)
Function Documentation
copyComdat()
static void copyComdat (GlobalObject * Dst, const GlobalObject * Src) static
Definition at line 21 of file CloneModule.cpp.
References DC, llvm::GlobalObject::getComdat(), llvm::Comdat::getName(), llvm::Module::getOrInsertComdat(), llvm::GlobalValue::getParent(), llvm::Comdat::getSelectionKind(), and llvm::GlobalObject::setComdat().
Referenced by llvm::CloneModule().
LLVMCloneModule()
LLVMModuleRef LLVMCloneModule (LLVMModuleRef M)
Definition at line 198 of file CloneModule.cpp.
References llvm::CloneModule(), llvm::release, llvm::unwrap(), and llvm::wrap().