LLVM: lib/CodeGen/AsmPrinter/CodeViewDebug.cpp File Reference
CodeViewDebug.cpp File Reference
#include "CodeViewDebug.h"
#include "DwarfExpression.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/LexicalScopes.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/CodeViewRecordIO.h"
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
#include "llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h"
#include "llvm/DebugInfo/CodeView/EnumTables.h"
#include "llvm/DebugInfo/CodeView/Line.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/TypeDumpVisitor.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
#include "llvm/DebugInfo/CodeView/TypeTableCollection.h"
#include "llvm/DebugInfo/CodeView/TypeVisitorCallbackPipeline.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <limits>
#include <string>
#include <utility>
#include <vector>
Classes
struct llvm::CodeViewDebug::TypeLoweringScope
struct llvm::ClassInfo
struct llvm::ClassInfo::MemberInfo
Functions
static CPUType mapArchToCVCPUType (Triple::ArchType Type)
static StringRef getPrettyScopeName (const DIScope *Scope)
static const DISubprogram * getQualifiedNameComponents (const DIScope *Scope, SmallVectorImpl< StringRef > &QualifiedNameComponents)
static std::string getQualifiedName (ArrayRef< StringRef > QualifiedNameComponents, StringRef TypeName)
static std::string getFullyQualifiedName (const DIScope *Scope, StringRef Name)
static std::string getFullyQualifiedName (const DIScope *Ty)
static bool isNonTrivial (const DICompositeType *DCTy)
static FunctionOptions getFunctionOptions (const DISubroutineType *Ty, const DICompositeType *ClassTy=nullptr, StringRef SPName=StringRef(""))
static void addLocIfNotPresent (SmallVectorImpl< const DILocation * > &Locs, const DILocation *Loc)
static void emitNullTerminatedSymbolName (MCStreamer &OS, StringRef S, unsigned MaxFixedRecordLength=0xF00)
static StringRef getTypeLeafName (TypeLeafKind TypeKind)
static SourceLanguage MapDWLangToCVLang (unsigned DWLang)
static Version parseVersion (StringRef Name)
static TypeIndex getStringIdTypeIdx (GlobalTypeTableBuilder &TypeTable, StringRef S)
static bool canUseReferenceType (const DbgVariableLocation &Loc)
static bool needsReferenceType (const DbgVariableLocation &Loc)
static bool shouldEmitUdt (const DIType *T)
static PointerToMemberRepresentation translatePtrToMemberRep (unsigned SizeInBytes, bool IsPMF, unsigned Flags)
static CallingConvention dwarfCCToCodeView (unsigned DwarfCC)
Given a DWARF calling convention, get the CodeView equivalent.
static MemberAccess translateAccessFlags (unsigned RecordTag, unsigned Flags)
static MethodOptions translateMethodOptionFlags (const DISubprogram *SP)
static MethodKind translateMethodKindFlags (const DISubprogram *SP, bool Introduced)
static TypeRecordKind getRecordKind (const DICompositeType *Ty)
static ClassOptions getCommonClassOptions (const DICompositeType *Ty)
Return ClassOptions that should be present on both the forward declaration and the defintion of a tag type.
static bool shouldAlwaysEmitCompleteClassType (const DICompositeType *Ty)
template<typename T >
static void copyBytesForDefRange (SmallString< 20 > &BytePrefix, SymbolKind SymKind, const T &DefRangeHeader)
Only call this on endian-specific types like ulittle16_t and little32_t, or structs composed of them.
static StringRef getSymbolName (SymbolKind SymKind)
Function Documentation
addLocIfNotPresent()
static void addLocIfNotPresent (SmallVectorImpl< const DILocation * > & Locs, const DILocation * Loc) static
Definition at line 471 of file CodeViewDebug.cpp.
References B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
canUseReferenceType()
static bool canUseReferenceType (const DbgVariableLocation & Loc) static
Definition at line 1228 of file CodeViewDebug.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), and llvm::DbgVariableLocation::LoadChain.
copyBytesForDefRange()
template<typename T > static void copyBytesForDefRange (SmallString< 20 > & BytePrefix, SymbolKind SymKind, const T & DefRangeHeader) static
Only call this on endian-specific types like ulittle16_t and little32_t, or structs composed of them.
Definition at line 2643 of file CodeViewDebug.cpp.
References llvm::SmallVectorImpl< T >::resize().
dwarfCCToCodeView()
static CallingConvention dwarfCCToCodeView (unsigned DwarfCC) static
Given a DWARF calling convention, get the CodeView equivalent.
If we don't have a translation, use the NearC convention.
Definition at line 1815 of file CodeViewDebug.cpp.
emitNullTerminatedSymbolName()
static void emitNullTerminatedSymbolName (MCStreamer & OS, StringRef S, unsigned MaxFixedRecordLength = 0xF00) static
Definition at line 608 of file CodeViewDebug.cpp.
References llvm::MCStreamer::EmitBytes(), llvm::codeview::MaxRecordLength, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::StringRef::take_front().
getCommonClassOptions()
static ClassOptions getCommonClassOptions (const DICompositeType * Ty) static
Return ClassOptions that should be present on both the forward declaration and the defintion of a tag type.
Definition at line 2022 of file CodeViewDebug.cpp.
References llvm::StringRef::empty(), llvm::DICompositeType::getIdentifier(), llvm::DIType::getScope(), and llvm::DINode::getTag().
getFullyQualifiedName() [1/2]
static std::string getFullyQualifiedName (const DIScope * Scope, StringRef Name) static
Definition at line 315 of file CodeViewDebug.cpp.
References getQualifiedName(), getQualifiedNameComponents(), and Name.
Referenced by getFullyQualifiedName().
getFullyQualifiedName() [2/2]
static std::string getFullyQualifiedName (const DIScope * Ty) static
Definition at line 333 of file CodeViewDebug.cpp.
References getFullyQualifiedName(), getPrettyScopeName(), and llvm::DIScope::getScope().
getFunctionOptions()
static FunctionOptions getFunctionOptions (const DISubroutineType * Ty, const DICompositeType * ClassTy = nullptr, StringRef SPName = StringRef("")) static
Definition at line 394 of file CodeViewDebug.cpp.
References llvm::DISubroutineType::getTypeArray(), and isNonTrivial().
getPrettyScopeName()
static StringRef getPrettyScopeName (const DIScope * Scope) static
Definition at line 271 of file CodeViewDebug.cpp.
References llvm::StringRef::empty(), llvm::DIScope::getName(), and llvm::DINode::getTag().
Referenced by getFullyQualifiedName(), and getQualifiedNameComponents().
getQualifiedName()
static std::string getQualifiedName (ArrayRef< StringRef > QualifiedNameComponents, StringRef TypeName) static
Definition at line 303 of file CodeViewDebug.cpp.
References llvm::reverse().
Referenced by getFullyQualifiedName().
getQualifiedNameComponents()
static const DISubprogram * getQualifiedNameComponents (const DIScope * Scope, SmallVectorImpl< StringRef > & QualifiedNameComponents) static
Definition at line 289 of file CodeViewDebug.cpp.
References llvm::StringRef::empty(), getPrettyScopeName(), llvm::DIScope::getScope(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getFullyQualifiedName().
getRecordKind()
static TypeRecordKind getRecordKind (const DICompositeType * Ty) static
Definition at line 2012 of file CodeViewDebug.cpp.
References llvm::DINode::getTag(), and llvm_unreachable.
getStringIdTypeIdx()
static TypeIndex getStringIdTypeIdx (GlobalTypeTableBuilder & TypeTable, StringRef S) static
Definition at line 835 of file CodeViewDebug.cpp.
References llvm::codeview::GlobalTypeTableBuilder::writeLeafType().
getSymbolName()
static StringRef getSymbolName (SymbolKind SymKind) static
Definition at line 2958 of file CodeViewDebug.cpp.
References llvm::codeview::getSymbolTypeNames().
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbolFlags().
getTypeLeafName()
static StringRef getTypeLeafName (TypeLeafKind TypeKind) static
Definition at line 620 of file CodeViewDebug.cpp.
References llvm::codeview::getTypeLeafNames().
isNonTrivial()
static bool isNonTrivial (const DICompositeType * DCTy) static
Definition at line 389 of file CodeViewDebug.cpp.
References llvm::DIType::getFlags().
Referenced by getFunctionOptions().
mapArchToCVCPUType()
static CPUType mapArchToCVCPUType (Triple::ArchType Type) static
Definition at line 118 of file CodeViewDebug.cpp.
References llvm::codeview::ARM64, llvm::codeview::Pentium3, llvm::report_fatal_error(), llvm::ARMJITSymbolFlags::Thumb, and llvm::codeview::X64.
Referenced by llvm::CodeViewDebug::CodeViewDebug().
MapDWLangToCVLang()
static SourceLanguage MapDWLangToCVLang (unsigned DWLang) static
Definition at line 730 of file CodeViewDebug.cpp.
needsReferenceType()
static bool needsReferenceType (const DbgVariableLocation & Loc) static
Definition at line 1232 of file CodeViewDebug.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::DbgVariableLocation::LoadChain, and llvm::SmallVectorBase::size().
parseVersion()
static Version parseVersion (StringRef Name) static
Definition at line 775 of file CodeViewDebug.cpp.
References llvm::codeview::C, N, and Name.
shouldAlwaysEmitCompleteClassType()
static bool shouldAlwaysEmitCompleteClassType (const DICompositeType * Ty) static
Definition at line 2226 of file CodeViewDebug.cpp.
References llvm::StringRef::empty(), llvm::DICompositeType::getIdentifier(), llvm::DIType::getName(), and llvm::DIType::isForwardDecl().
shouldEmitUdt()
static bool shouldEmitUdt (const DIType * T) static
Definition at line 1463 of file CodeViewDebug.cpp.
translateAccessFlags()
static MemberAccess translateAccessFlags (unsigned RecordTag, unsigned Flags) static
Definition at line 1970 of file CodeViewDebug.cpp.
References llvm::DINode::FlagAccessibility, and llvm_unreachable.
translateMethodKindFlags()
static MethodKind translateMethodKindFlags (const DISubprogram * SP, bool Introduced) static
Definition at line 1992 of file CodeViewDebug.cpp.
References llvm_unreachable.
translateMethodOptionFlags()
static MethodOptions translateMethodOptionFlags (const DISubprogram * SP) static
Definition at line 1983 of file CodeViewDebug.cpp.
translatePtrToMemberRep()
static PointerToMemberRepresentation translatePtrToMemberRep (unsigned SizeInBytes, bool IsPMF, unsigned Flags) static
Definition at line 1762 of file CodeViewDebug.cpp.
References llvm::DINode::FlagPtrToMemberRep, and llvm_unreachable.