LLVM: lib/Support/Compression.cpp File Reference
Compression.cpp File Reference
#include "llvm/Support/Compression.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include <zlib.h>
Functions
static Error createError (StringRef Err)
static StringRef convertZlibCodeToString (int Code)
Function Documentation
convertZlibCodeToString()
static StringRef convertZlibCodeToString (int Code) static
Definition at line 31 of file Compression.cpp.
References llvm_unreachable.
Referenced by llvm::zlib::compress(), and llvm::zlib::uncompress().
createError()
static Error createError (StringRef Err) static
Definition at line 27 of file Compression.cpp.
References llvm::inconvertibleErrorCode().
Referenced by llvm::zlib::compress(), and llvm::zlib::uncompress().