LLVM: lib/IR/Core.cpp File Reference
Core.cpp File Reference
#include "llvm-c/Core.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <system_error>
#include "AttributesCompatFunc.inc"
#include "llvm/IR/Value.def"
#include "llvm/IR/Instruction.def"
Classes
struct LLVMOpaqueModuleFlagEntry
struct LLVMOpaqueValueMetadataEntry
Macros
#define DEBUG_TYPE "ir"
#define GET_ATTR_KIND_FROM_NAME
#define HANDLE_VALUE(Name)
#define LLVM_DEFINE_VALUE_CAST(name)
#define HANDLE_INST(num, opc, clas) case num: return LLVM##opc;
#define HANDLE_INST(num, opc, clas) case LLVM##opc: return num;
Typedefs
using MetadataEntries = SmallVectorImpl< std::pair< unsigned, MDNode * > >
Functions
void LLVMInitializeCore (LLVMPassRegistryRef R)
void LLVMShutdown ()
char * LLVMCreateMessage (const char *Message)
void LLVMDisposeMessage (char *Message)
LLVMContextRef LLVMContextCreate ()
LLVMContextRef LLVMGetGlobalContext ()
void LLVMContextSetDiagnosticHandler (LLVMContextRef C, LLVMDiagnosticHandler Handler, void *DiagnosticContext)
LLVMDiagnosticHandler LLVMContextGetDiagnosticHandler (LLVMContextRef C)
void * LLVMContextGetDiagnosticContext (LLVMContextRef C)
void LLVMContextSetYieldCallback (LLVMContextRef C, LLVMYieldCallback Callback, void *OpaqueHandle)
LLVMBool LLVMContextShouldDiscardValueNames (LLVMContextRef C)
void LLVMContextSetDiscardValueNames (LLVMContextRef C, LLVMBool Discard)
void LLVMContextDispose (LLVMContextRef C)
unsigned LLVMGetMDKindIDInContext (LLVMContextRef C, const char *Name, unsigned SLen)
unsigned LLVMGetMDKindID (const char *Name, unsigned SLen)
unsigned LLVMGetEnumAttributeKindForName (const char *Name, size_t SLen)
unsigned LLVMGetLastEnumAttributeKind (void)
LLVMAttributeRef LLVMCreateEnumAttribute (LLVMContextRef C, unsigned KindID, uint64_t Val)
unsigned LLVMGetEnumAttributeKind (LLVMAttributeRef A)
uint64_t LLVMGetEnumAttributeValue (LLVMAttributeRef A)
LLVMAttributeRef LLVMCreateStringAttribute (LLVMContextRef C, const char *K, unsigned KLength, const char *V, unsigned VLength)
const char * LLVMGetStringAttributeKind (LLVMAttributeRef A, unsigned *Length)
const char * LLVMGetStringAttributeValue (LLVMAttributeRef A, unsigned *Length)
LLVMBool LLVMIsEnumAttribute (LLVMAttributeRef A)
LLVMBool LLVMIsStringAttribute (LLVMAttributeRef A)
char * LLVMGetDiagInfoDescription (LLVMDiagnosticInfoRef DI)
LLVMDiagnosticSeverity LLVMGetDiagInfoSeverity (LLVMDiagnosticInfoRef DI)
LLVMModuleRef LLVMModuleCreateWithName (const char *ModuleID)
LLVMModuleRef LLVMModuleCreateWithNameInContext (const char *ModuleID, LLVMContextRef C)
void LLVMDisposeModule (LLVMModuleRef M)
const char * LLVMGetModuleIdentifier (LLVMModuleRef M, size_t *Len)
void LLVMSetModuleIdentifier (LLVMModuleRef M, const char *Ident, size_t Len)
const char * LLVMGetSourceFileName (LLVMModuleRef M, size_t *Len)
void LLVMSetSourceFileName (LLVMModuleRef M, const char *Name, size_t Len)
const char * LLVMGetDataLayoutStr (LLVMModuleRef M)
const char * LLVMGetDataLayout (LLVMModuleRef M)
void LLVMSetDataLayout (LLVMModuleRef M, const char *DataLayoutStr)
const char * LLVMGetTarget (LLVMModuleRef M)
void LLVMSetTarget (LLVMModuleRef M, const char *Triple)
static Module::ModFlagBehavior map_to_llvmModFlagBehavior (LLVMModuleFlagBehavior Behavior)
static LLVMModuleFlagBehavior map_from_llvmModFlagBehavior (Module::ModFlagBehavior Behavior)
LLVMModuleFlagEntry * LLVMCopyModuleFlagsMetadata (LLVMModuleRef M, size_t *Len)
void LLVMDisposeModuleFlagsMetadata (LLVMModuleFlagEntry *Entries)
LLVMModuleFlagBehavior LLVMModuleFlagEntriesGetFlagBehavior (LLVMModuleFlagEntry *Entries, unsigned Index)
const char * LLVMModuleFlagEntriesGetKey (LLVMModuleFlagEntry *Entries, unsigned Index, size_t *Len)
LLVMMetadataRef LLVMModuleFlagEntriesGetMetadata (LLVMModuleFlagEntry *Entries, unsigned Index)
LLVMMetadataRef LLVMGetModuleFlag (LLVMModuleRef M, const char *Key, size_t KeyLen)
void LLVMAddModuleFlag (LLVMModuleRef M, LLVMModuleFlagBehavior Behavior, const char *Key, size_t KeyLen, LLVMMetadataRef Val)
void LLVMDumpModule (LLVMModuleRef M)
LLVMBool LLVMPrintModuleToFile (LLVMModuleRef M, const char *Filename, char **ErrorMessage)
char * LLVMPrintModuleToString (LLVMModuleRef M)
void LLVMSetModuleInlineAsm2 (LLVMModuleRef M, const char *Asm, size_t Len)
void LLVMSetModuleInlineAsm (LLVMModuleRef M, const char *Asm)
void LLVMAppendModuleInlineAsm (LLVMModuleRef M, const char *Asm, size_t Len)
const char * LLVMGetModuleInlineAsm (LLVMModuleRef M, size_t *Len)
LLVMValueRef LLVMGetInlineAsm (LLVMTypeRef Ty, char *AsmString, size_t AsmStringSize, char *Constraints, size_t ConstraintsSize, LLVMBool HasSideEffects, LLVMBool IsAlignStack, LLVMInlineAsmDialect Dialect)
LLVMContextRef LLVMGetModuleContext (LLVMModuleRef M)
LLVMTypeKind LLVMGetTypeKind (LLVMTypeRef Ty)
LLVMBool LLVMTypeIsSized (LLVMTypeRef Ty)
LLVMContextRef LLVMGetTypeContext (LLVMTypeRef Ty)
void LLVMDumpType (LLVMTypeRef Ty)
char * LLVMPrintTypeToString (LLVMTypeRef Ty)
LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
LLVMTypeRef LLVMInt1Type (void)
LLVMTypeRef LLVMInt8Type (void)
LLVMTypeRef LLVMInt16Type (void)
LLVMTypeRef LLVMInt32Type (void)
LLVMTypeRef LLVMInt64Type (void)
LLVMTypeRef LLVMInt128Type (void)
LLVMTypeRef LLVMIntType (unsigned NumBits)
unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMX86MMXTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMHalfType (void)
LLVMTypeRef LLVMFloatType (void)
LLVMTypeRef LLVMDoubleType (void)
LLVMTypeRef LLVMX86FP80Type (void)
LLVMTypeRef LLVMFP128Type (void)
LLVMTypeRef LLVMPPCFP128Type (void)
LLVMTypeRef LLVMX86MMXType (void)
LLVMTypeRef LLVMFunctionType (LLVMTypeRef ReturnType, LLVMTypeRef *ParamTypes, unsigned ParamCount, LLVMBool IsVarArg)
LLVMBool LLVMIsFunctionVarArg (LLVMTypeRef FunctionTy)
LLVMTypeRef LLVMGetReturnType (LLVMTypeRef FunctionTy)
unsigned LLVMCountParamTypes (LLVMTypeRef FunctionTy)
void LLVMGetParamTypes (LLVMTypeRef FunctionTy, LLVMTypeRef *Dest)
LLVMTypeRef LLVMStructTypeInContext (LLVMContextRef C, LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
LLVMTypeRef LLVMStructType (LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
LLVMTypeRef LLVMStructCreateNamed (LLVMContextRef C, const char *Name)
const char * LLVMGetStructName (LLVMTypeRef Ty)
void LLVMStructSetBody (LLVMTypeRef StructTy, LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
unsigned LLVMCountStructElementTypes (LLVMTypeRef StructTy)
void LLVMGetStructElementTypes (LLVMTypeRef StructTy, LLVMTypeRef *Dest)
LLVMTypeRef LLVMStructGetTypeAtIndex (LLVMTypeRef StructTy, unsigned i)
LLVMBool LLVMIsPackedStruct (LLVMTypeRef StructTy)
LLVMBool LLVMIsOpaqueStruct (LLVMTypeRef StructTy)
LLVMBool LLVMIsLiteralStruct (LLVMTypeRef StructTy)
LLVMTypeRef LLVMGetTypeByName (LLVMModuleRef M, const char *Name)
void LLVMGetSubtypes (LLVMTypeRef Tp, LLVMTypeRef *Arr)
LLVMTypeRef LLVMArrayType (LLVMTypeRef ElementType, unsigned ElementCount)
LLVMTypeRef LLVMPointerType (LLVMTypeRef ElementType, unsigned AddressSpace)
LLVMTypeRef LLVMVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
LLVMTypeRef LLVMGetElementType (LLVMTypeRef WrappedTy)
unsigned LLVMGetNumContainedTypes (LLVMTypeRef Tp)
unsigned LLVMGetArrayLength (LLVMTypeRef ArrayTy)
unsigned LLVMGetPointerAddressSpace (LLVMTypeRef PointerTy)
unsigned LLVMGetVectorSize (LLVMTypeRef VectorTy)
LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMVoidType (void)
LLVMTypeRef LLVMLabelType (void)
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
LLVMValueKind LLVMGetValueKind (LLVMValueRef Val)
const char * LLVMGetValueName2 (LLVMValueRef Val, size_t *Length)
void LLVMSetValueName2 (LLVMValueRef Val, const char *Name, size_t NameLen)
const char * LLVMGetValueName (LLVMValueRef Val)
void LLVMSetValueName (LLVMValueRef Val, const char *Name)
void LLVMDumpValue (LLVMValueRef Val)
char * LLVMPrintValueToString (LLVMValueRef Val)
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
int LLVMHasMetadata (LLVMValueRef Inst)
LLVMValueRef LLVMGetMetadata (LLVMValueRef Inst, unsigned KindID)
static MDNode * extractMDNode (MetadataAsValue *MAV)
void LLVMSetMetadata (LLVMValueRef Inst, unsigned KindID, LLVMValueRef Val)
static LLVMValueMetadataEntry * llvm_getMetadata (size_t *NumEntries, llvm::function_ref< void(MetadataEntries &)> AccessMD)
LLVMValueMetadataEntry * LLVMInstructionGetAllMetadataOtherThanDebugLoc (LLVMValueRef Value, size_t *NumEntries)
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
LLVMUseRef LLVMGetFirstUse (LLVMValueRef Val)
LLVMUseRef LLVMGetNextUse (LLVMUseRef U)
LLVMValueRef LLVMGetUser (LLVMUseRef U)
LLVMValueRef LLVMGetUsedValue (LLVMUseRef U)
static LLVMValueRef getMDNodeOperandImpl (LLVMContext &Context, const MDNode *N, unsigned Index)
LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
void LLVMSetOperand (LLVMValueRef Val, unsigned Index, LLVMValueRef Op)
int LLVMGetNumOperands (LLVMValueRef Val)
LLVMValueRef LLVMConstNull (LLVMTypeRef Ty)
LLVMValueRef LLVMConstAllOnes (LLVMTypeRef Ty)
LLVMValueRef LLVMGetUndef (LLVMTypeRef Ty)
LLVMBool LLVMIsConstant (LLVMValueRef Ty)
LLVMBool LLVMIsNull (LLVMValueRef Val)
LLVMBool LLVMIsUndef (LLVMValueRef Val)
LLVMValueRef LLVMConstPointerNull (LLVMTypeRef Ty)
LLVMMetadataRef LLVMMDStringInContext2 (LLVMContextRef C, const char *Str, size_t SLen)
LLVMMetadataRef LLVMMDNodeInContext2 (LLVMContextRef C, LLVMMetadataRef *MDs, size_t Count)
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char *Str, unsigned SLen)
LLVMValueRef LLVMMDString (const char *Str, unsigned SLen)
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef *Vals, unsigned Count)
LLVMValueRef LLVMMDNode (LLVMValueRef *Vals, unsigned Count)
LLVMValueRef LLVMMetadataAsValue (LLVMContextRef C, LLVMMetadataRef MD)
LLVMMetadataRef LLVMValueAsMetadata (LLVMValueRef Val)
const char * LLVMGetMDString (LLVMValueRef V, unsigned *Length)
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
LLVMNamedMDNodeRef LLVMGetFirstNamedMetadata (LLVMModuleRef M)
LLVMNamedMDNodeRef LLVMGetLastNamedMetadata (LLVMModuleRef M)
LLVMNamedMDNodeRef LLVMGetNextNamedMetadata (LLVMNamedMDNodeRef NMD)
LLVMNamedMDNodeRef LLVMGetPreviousNamedMetadata (LLVMNamedMDNodeRef NMD)
LLVMNamedMDNodeRef LLVMGetNamedMetadata (LLVMModuleRef M, const char *Name, size_t NameLen)
LLVMNamedMDNodeRef LLVMGetOrInsertNamedMetadata (LLVMModuleRef M, const char *Name, size_t NameLen)
const char * LLVMGetNamedMetadataName (LLVMNamedMDNodeRef NMD, size_t *NameLen)
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef *Dest)
unsigned LLVMGetNamedMetadataNumOperands (LLVMModuleRef M, const char *Name)
void LLVMGetNamedMetadataOperands (LLVMModuleRef M, const char *Name, LLVMValueRef *Dest)
void LLVMAddNamedMetadataOperand (LLVMModuleRef M, const char *Name, LLVMValueRef Val)
const char * LLVMGetDebugLocDirectory (LLVMValueRef Val, unsigned *Length)
const char * LLVMGetDebugLocFilename (LLVMValueRef Val, unsigned *Length)
unsigned LLVMGetDebugLocLine (LLVMValueRef Val)
unsigned LLVMGetDebugLocColumn (LLVMValueRef Val)
LLVMValueRef LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)
LLVMValueRef LLVMConstIntOfArbitraryPrecision (LLVMTypeRef IntTy, unsigned NumWords, const uint64_t Words[])
LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char Str[], uint8_t Radix)
LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char Str[], unsigned SLen, uint8_t Radix)
LLVMValueRef LLVMConstReal (LLVMTypeRef RealTy, double N)
LLVMValueRef LLVMConstRealOfString (LLVMTypeRef RealTy, const char *Text)
LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char Str[], unsigned SLen)
unsigned long long LLVMConstIntGetZExtValue (LLVMValueRef ConstantVal)
long long LLVMConstIntGetSExtValue (LLVMValueRef ConstantVal)
double LLVMConstRealGetDouble (LLVMValueRef ConstantVal, LLVMBool *LosesInfo)
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char *Str, unsigned Length, LLVMBool DontNullTerminate)
LLVMValueRef LLVMConstString (const char *Str, unsigned Length, LLVMBool DontNullTerminate)
LLVMValueRef LLVMGetElementAsConstant (LLVMValueRef C, unsigned idx)
LLVMBool LLVMIsConstantString (LLVMValueRef C)
const char * LLVMGetAsString (LLVMValueRef C, size_t *Length)
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef *ConstantVals, unsigned Length)
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
LLVMValueRef LLVMConstStruct (LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef *ConstantVals, unsigned Count)
LLVMValueRef LLVMConstVector (LLVMValueRef *ScalarConstantVals, unsigned Size)
static LLVMOpcode map_to_llvmopcode (int opcode)
static int map_from_llvmopcode (LLVMOpcode code)
LLVMOpcode LLVMGetConstOpcode (LLVMValueRef ConstantVal)
LLVMValueRef LLVMAlignOf (LLVMTypeRef Ty)
LLVMValueRef LLVMSizeOf (LLVMTypeRef Ty)
LLVMValueRef LLVMConstNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNSWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNUWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstFNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNot (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstExactUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstExactSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstURem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAnd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstOr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstXor (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstICmp (LLVMIntPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFCmp (LLVMRealPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstShl (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstLShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstInBoundsGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstUIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToUI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToSI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPtrToInt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntToPtr (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstAddrSpaceCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstTruncOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPointerCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType, LLVMBool isSigned)
LLVMValueRef LLVMConstFPCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSelect (LLVMValueRef ConstantCondition, LLVMValueRef ConstantIfTrue, LLVMValueRef ConstantIfFalse)
LLVMValueRef LLVMConstExtractElement (LLVMValueRef VectorConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstInsertElement (LLVMValueRef VectorConstant, LLVMValueRef ElementValueConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstShuffleVector (LLVMValueRef VectorAConstant, LLVMValueRef VectorBConstant, LLVMValueRef MaskConstant)
LLVMValueRef LLVMConstExtractValue (LLVMValueRef AggConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMConstInsertValue (LLVMValueRef AggConstant, LLVMValueRef ElementValueConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMConstInlineAsm (LLVMTypeRef Ty, const char *AsmString, const char *Constraints, LLVMBool HasSideEffects, LLVMBool IsAlignStack)
LLVMValueRef LLVMBlockAddress (LLVMValueRef F, LLVMBasicBlockRef BB)
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
const char * LLVMGetSection (LLVMValueRef Global)
void LLVMSetSection (LLVMValueRef Global, const char *Section)
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
LLVMUnnamedAddr LLVMGetUnnamedAddress (LLVMValueRef Global)
void LLVMSetUnnamedAddress (LLVMValueRef Global, LLVMUnnamedAddr UnnamedAddr)
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
LLVMTypeRef LLVMGlobalGetValueType (LLVMValueRef Global)
unsigned LLVMGetAlignment (LLVMValueRef V)
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
LLVMValueMetadataEntry * LLVMGlobalCopyAllMetadata (LLVMValueRef Value, size_t *NumEntries)
unsigned LLVMValueMetadataEntriesGetKind (LLVMValueMetadataEntry *Entries, unsigned Index)
LLVMMetadataRef LLVMValueMetadataEntriesGetMetadata (LLVMValueMetadataEntry *Entries, unsigned Index)
void LLVMDisposeValueMetadataEntries (LLVMValueMetadataEntry *Entries)
void LLVMGlobalSetMetadata (LLVMValueRef Global, unsigned Kind, LLVMMetadataRef MD)
void LLVMGlobalEraseMetadata (LLVMValueRef Global, unsigned Kind)
void LLVMGlobalClearMetadata (LLVMValueRef Global)
LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name, unsigned AddressSpace)
LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char *Name)
LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
LLVMValueRef LLVMAddAlias (LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char *Name)
LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char *Name, size_t NameLen)
LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
LLVMValueRef LLVMAddFunction (LLVMModuleRef M, const char *Name, LLVMTypeRef FunctionTy)
LLVMValueRef LLVMGetNamedFunction (LLVMModuleRef M, const char *Name)
LLVMValueRef LLVMGetFirstFunction (LLVMModuleRef M)
LLVMValueRef LLVMGetLastFunction (LLVMModuleRef M)
LLVMValueRef LLVMGetNextFunction (LLVMValueRef Fn)
LLVMValueRef LLVMGetPreviousFunction (LLVMValueRef Fn)
void LLVMDeleteFunction (LLVMValueRef Fn)
LLVMBool LLVMHasPersonalityFn (LLVMValueRef Fn)
LLVMValueRef LLVMGetPersonalityFn (LLVMValueRef Fn)
void LLVMSetPersonalityFn (LLVMValueRef Fn, LLVMValueRef PersonalityFn)
unsigned LLVMGetIntrinsicID (LLVMValueRef Fn)
static Intrinsic::ID llvm_map_to_intrinsic_id (unsigned ID)
LLVMValueRef LLVMGetIntrinsicDeclaration (LLVMModuleRef Mod, unsigned ID, LLVMTypeRef *ParamTypes, size_t ParamCount)
const char * LLVMIntrinsicGetName (unsigned ID, size_t *NameLength)
LLVMTypeRef LLVMIntrinsicGetType (LLVMContextRef Ctx, unsigned ID, LLVMTypeRef *ParamTypes, size_t ParamCount)
const char * LLVMIntrinsicCopyOverloadedName (unsigned ID, LLVMTypeRef *ParamTypes, size_t ParamCount, size_t *NameLength)
unsigned LLVMLookupIntrinsicID (const char *Name, size_t NameLen)
LLVMBool LLVMIntrinsicIsOverloaded (unsigned ID)
unsigned LLVMGetFunctionCallConv (LLVMValueRef Fn)
void LLVMSetFunctionCallConv (LLVMValueRef Fn, unsigned CC)
const char * LLVMGetGC (LLVMValueRef Fn)
void LLVMSetGC (LLVMValueRef Fn, const char *GC)
void LLVMAddAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, LLVMAttributeRef A)
unsigned LLVMGetAttributeCountAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx)
void LLVMGetAttributesAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, LLVMAttributeRef *Attrs)
LLVMAttributeRef LLVMGetEnumAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, unsigned KindID)
LLVMAttributeRef LLVMGetStringAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
void LLVMRemoveEnumAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, unsigned KindID)
void LLVMRemoveStringAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
void LLVMAddTargetDependentFunctionAttr (LLVMValueRef Fn, const char *A, const char *V)
unsigned LLVMCountParams (LLVMValueRef FnRef)
void LLVMGetParams (LLVMValueRef FnRef, LLVMValueRef *ParamRefs)
LLVMValueRef LLVMGetParam (LLVMValueRef FnRef, unsigned index)
LLVMValueRef LLVMGetParamParent (LLVMValueRef V)
LLVMValueRef LLVMGetFirstParam (LLVMValueRef Fn)
LLVMValueRef LLVMGetLastParam (LLVMValueRef Fn)
LLVMValueRef LLVMGetNextParam (LLVMValueRef Arg)
LLVMValueRef LLVMGetPreviousParam (LLVMValueRef Arg)
void LLVMSetParamAlignment (LLVMValueRef Arg, unsigned align)
LLVMValueRef LLVMAddGlobalIFunc (LLVMModuleRef M, const char *Name, size_t NameLen, LLVMTypeRef Ty, unsigned AddrSpace, LLVMValueRef Resolver)
LLVMValueRef LLVMGetNamedGlobalIFunc (LLVMModuleRef M, const char *Name, size_t NameLen)
LLVMValueRef LLVMGetFirstGlobalIFunc (LLVMModuleRef M)
LLVMValueRef LLVMGetLastGlobalIFunc (LLVMModuleRef M)
LLVMValueRef LLVMGetNextGlobalIFunc (LLVMValueRef IFunc)
LLVMValueRef LLVMGetPreviousGlobalIFunc (LLVMValueRef IFunc)
LLVMValueRef LLVMGetGlobalIFuncResolver (LLVMValueRef IFunc)
void LLVMSetGlobalIFuncResolver (LLVMValueRef IFunc, LLVMValueRef Resolver)
void LLVMEraseGlobalIFunc (LLVMValueRef IFunc)
void LLVMRemoveGlobalIFunc (LLVMValueRef IFunc)
LLVMValueRef LLVMBasicBlockAsValue (LLVMBasicBlockRef BB)
LLVMBool LLVMValueIsBasicBlock (LLVMValueRef Val)
LLVMBasicBlockRef LLVMValueAsBasicBlock (LLVMValueRef Val)
const char * LLVMGetBasicBlockName (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetBasicBlockParent (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetBasicBlockTerminator (LLVMBasicBlockRef BB)
unsigned LLVMCountBasicBlocks (LLVMValueRef FnRef)
void LLVMGetBasicBlocks (LLVMValueRef FnRef, LLVMBasicBlockRef *BasicBlocksRefs)
LLVMBasicBlockRef LLVMGetEntryBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetFirstBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetLastBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetNextBasicBlock (LLVMBasicBlockRef BB)
LLVMBasicBlockRef LLVMGetPreviousBasicBlock (LLVMBasicBlockRef BB)
LLVMBasicBlockRef LLVMCreateBasicBlockInContext (LLVMContextRef C, const char *Name)
void LLVMInsertExistingBasicBlockAfterInsertBlock (LLVMBuilderRef Builder, LLVMBasicBlockRef BB)
void LLVMAppendExistingBasicBlock (LLVMValueRef Fn, LLVMBasicBlockRef BB)
LLVMBasicBlockRef LLVMAppendBasicBlockInContext (LLVMContextRef C, LLVMValueRef FnRef, const char *Name)
LLVMBasicBlockRef LLVMAppendBasicBlock (LLVMValueRef FnRef, const char *Name)
LLVMBasicBlockRef LLVMInsertBasicBlockInContext (LLVMContextRef C, LLVMBasicBlockRef BBRef, const char *Name)
LLVMBasicBlockRef LLVMInsertBasicBlock (LLVMBasicBlockRef BBRef, const char *Name)
void LLVMDeleteBasicBlock (LLVMBasicBlockRef BBRef)
void LLVMRemoveBasicBlockFromParent (LLVMBasicBlockRef BBRef)
void LLVMMoveBasicBlockBefore (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
void LLVMMoveBasicBlockAfter (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
LLVMBasicBlockRef LLVMGetInstructionParent (LLVMValueRef Inst)
LLVMValueRef LLVMGetFirstInstruction (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetLastInstruction (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetNextInstruction (LLVMValueRef Inst)
LLVMValueRef LLVMGetPreviousInstruction (LLVMValueRef Inst)
void LLVMInstructionRemoveFromParent (LLVMValueRef Inst)
void LLVMInstructionEraseFromParent (LLVMValueRef Inst)
LLVMIntPredicate LLVMGetICmpPredicate (LLVMValueRef Inst)
LLVMRealPredicate LLVMGetFCmpPredicate (LLVMValueRef Inst)
LLVMOpcode LLVMGetInstructionOpcode (LLVMValueRef Inst)
LLVMValueRef LLVMInstructionClone (LLVMValueRef Inst)
LLVMValueRef LLVMIsATerminatorInst (LLVMValueRef Inst)
unsigned LLVMGetNumArgOperands (LLVMValueRef Instr)
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned align)
void LLVMAddCallSiteAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef A)
unsigned LLVMGetCallSiteAttributeCount (LLVMValueRef C, LLVMAttributeIndex Idx)
void LLVMGetCallSiteAttributes (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef *Attrs)
LLVMAttributeRef LLVMGetCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
LLVMAttributeRef LLVMGetCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
void LLVMRemoveCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
void LLVMRemoveCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
LLVMValueRef LLVMGetCalledValue (LLVMValueRef Instr)
LLVMTypeRef LLVMGetCalledFunctionType (LLVMValueRef Instr)
LLVMBool LLVMIsTailCall (LLVMValueRef Call)
void LLVMSetTailCall (LLVMValueRef Call, LLVMBool isTailCall)
LLVMBasicBlockRef LLVMGetNormalDest (LLVMValueRef Invoke)
LLVMBasicBlockRef LLVMGetUnwindDest (LLVMValueRef Invoke)
void LLVMSetNormalDest (LLVMValueRef Invoke, LLVMBasicBlockRef B)
void LLVMSetUnwindDest (LLVMValueRef Invoke, LLVMBasicBlockRef B)
unsigned LLVMGetNumSuccessors (LLVMValueRef Term)
LLVMBasicBlockRef LLVMGetSuccessor (LLVMValueRef Term, unsigned i)
void LLVMSetSuccessor (LLVMValueRef Term, unsigned i, LLVMBasicBlockRef block)
LLVMBool LLVMIsConditional (LLVMValueRef Branch)
LLVMValueRef LLVMGetCondition (LLVMValueRef Branch)
void LLVMSetCondition (LLVMValueRef Branch, LLVMValueRef Cond)
LLVMBasicBlockRef LLVMGetSwitchDefaultDest (LLVMValueRef Switch)
LLVMTypeRef LLVMGetAllocatedType (LLVMValueRef Alloca)
LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef *IncomingValues, LLVMBasicBlockRef *IncomingBlocks, unsigned Count)
unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
unsigned LLVMGetNumIndices (LLVMValueRef Inst)
const unsigned * LLVMGetIndices (LLVMValueRef Inst)
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
LLVMBuilderRef LLVMCreateBuilder (void)
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char *Name)
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef *RetVals, unsigned N)
LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
LLVMValueRef LLVMBuildInvoke (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char *Name)
LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char *Name)
LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef *Handlers)
LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
LLVMValueRef LLVMBuildLoad (LLVMBuilderRef B, LLVMValueRef PointerVal, const char *Name)
LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char *Name)
LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef PointerVal)
static AtomicOrdering mapFromLLVMOrdering (LLVMAtomicOrdering Ordering)
static LLVMAtomicOrdering mapToLLVMOrdering (AtomicOrdering Ordering)
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering Ordering, LLVMBool isSingleThread, const char *Name)
LLVMValueRef LLVMBuildGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildInBoundsGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildStructGEP (LLVMBuilderRef B, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMBool LLVMGetVolatile (LLVMValueRef MemAccessInst)
void LLVMSetVolatile (LLVMValueRef MemAccessInst, LLVMBool isVolatile)
LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemAccessInst)
void LLVMSetOrdering (LLVMValueRef MemAccessInst, LLVMAtomicOrdering Ordering)
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char *Name)
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildCall (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char *Name)
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char *Name)
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildPtrDiff (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool singleThread)
LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool NewValue)
LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
LLVMModuleProviderRef LLVMCreateModuleProviderForExistingModule (LLVMModuleRef M)
void LLVMDisposeModuleProvider (LLVMModuleProviderRef MP)
LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char *Path, LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char *InputData, size_t InputDataLength, const char *BufferName, LLVMBool RequiresNullTerminator)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char *InputData, size_t InputDataLength, const char *BufferName)
const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
LLVMPassRegistryRef LLVMGetGlobalPassRegistry (void)
LLVMPassManagerRef LLVMCreatePassManager ()
LLVMPassManagerRef LLVMCreateFunctionPassManagerForModule (LLVMModuleRef M)
LLVMPassManagerRef LLVMCreateFunctionPassManager (LLVMModuleProviderRef P)
LLVMBool LLVMRunPassManager (LLVMPassManagerRef PM, LLVMModuleRef M)
LLVMBool LLVMInitializeFunctionPassManager (LLVMPassManagerRef FPM)
LLVMBool LLVMRunFunctionPassManager (LLVMPassManagerRef FPM, LLVMValueRef F)
LLVMBool LLVMFinalizeFunctionPassManager (LLVMPassManagerRef FPM)
void LLVMDisposePassManager (LLVMPassManagerRef PM)
LLVMBool LLVMStartMultithreaded ()
void LLVMStopMultithreaded ()
LLVMBool LLVMIsMultithreaded ()
Variables
static ManagedStatic< LLVMContext > GlobalContext
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ir"
Definition at line 44 of file Core.cpp.
GET_ATTR_KIND_FROM_NAME
#define GET_ATTR_KIND_FROM_NAME
Definition at line 130 of file Core.cpp.
HANDLE_INST [1/2]
#define HANDLE_INST (num, opc, clas) case num: return LLVM##opc;
HANDLE_INST [2/2]
#define HANDLE_INST (num, opc, clas) case LLVM##opc: return num;
HANDLE_VALUE
#define HANDLE_VALUE (Name)
Value:
  case Value::Name##Val: \
    return LLVM##Name##ValueKind;
LLVM_DEFINE_VALUE_CAST
#define LLVM_DEFINE_VALUE_CAST (name)
Value:
  LLVMValueRef LLVMIsA##name(LLVMValueRef Val) {                           \
    return wrap(static_cast<Value*>(dyn_cast_or_null<name>(unwrap(Val)))); \
  }
Definition at line 925 of file Core.cpp.
Typedef Documentation
MetadataEntries
using MetadataEntries = SmallVectorImpl<std::pair<unsigned, MDNode *> >
Definition at line 896 of file Core.cpp.
Function Documentation
extractMDNode()
static MDNode * extractMDNode (MetadataAsValue * MAV) static
Definition at line 874 of file Core.cpp.
References assert(), llvm::MDNode::get(), llvm::Value::getContext(), llvm::MetadataAsValue::getMetadata(), and N.
Referenced by LLVMAddNamedMetadataOperand(), and LLVMSetMetadata().
getMDNodeOperandImpl()
static LLVMValueRef getMDNodeOperandImpl (LLVMContext & Context, const MDNode * N, unsigned Index) static
Definition at line 973 of file Core.cpp.
References llvm::MetadataAsValue::get(), N, and llvm::wrap().
Referenced by LLVMGetMDNodeOperands(), and LLVMGetOperand().
llvm_getMetadata()
static LLVMValueMetadataEntry * llvm_getMetadata (size_t * NumEntries, llvm::function_ref< void(MetadataEntries &)> AccessMD) static
Definition at line 898 of file Core.cpp.
References LLVMOpaqueValueMetadataEntry::Kind, LLVMOpaqueValueMetadataEntry::Metadata, llvm::safe_malloc(), and llvm::wrap().
Referenced by LLVMGlobalCopyAllMetadata(), and LLVMInstructionGetAllMetadataOtherThanDebugLoc().
llvm_map_to_intrinsic_id()
static Intrinsic::ID llvm_map_to_intrinsic_id (unsigned ID) static
Definition at line 2318 of file Core.cpp.
References assert(), and llvm::Intrinsic::num_intrinsics.
Referenced by LLVMGetIntrinsicDeclaration(), LLVMIntrinsicCopyOverloadedName(), LLVMIntrinsicGetName(), LLVMIntrinsicGetType(), and LLVMIntrinsicIsOverloaded().
LLVMAddAlias()
LLVMValueRef LLVMAddAlias (LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char * Name)
Definition at line 2199 of file Core.cpp.
References llvm::GlobalAlias::create(), llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddAttributeAtIndex()
void LLVMAddAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, LLVMAttributeRef A)
Definition at line 2388 of file Core.cpp.
References F, Idx, and llvm::unwrap().
LLVMAddCallSiteAttribute()
void LLVMAddCallSiteAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef A)
Definition at line 2795 of file Core.cpp.
References Idx, and llvm::unwrap().
LLVMAddCase()
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
Definition at line 3192 of file Core.cpp.
References llvm::unwrap().
LLVMAddClause()
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
Definition at line 3209 of file Core.cpp.
References llvm::unwrap().
LLVMAddDestination()
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
Definition at line 3197 of file Core.cpp.
References llvm::unwrap().
LLVMAddFunction()
LLVMValueRef LLVMAddFunction (LLVMModuleRef M, const char * Name, LLVMTypeRef FunctionTy)
Definition at line 2254 of file Core.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddGlobal()
LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name)
Definition at line 2068 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddGlobalIFunc()
LLVMValueRef LLVMAddGlobalIFunc (LLVMModuleRef M, const char * Name, size_t NameLen, LLVMTypeRef Ty, unsigned AddrSpace, LLVMValueRef Resolver)
Definition at line 2497 of file Core.cpp.
References llvm::GlobalIFunc::create(), llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddGlobalInAddressSpace()
LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name, unsigned AddressSpace)
Definition at line 2073 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddHandler()
void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
Definition at line 3222 of file Core.cpp.
References llvm::unwrap().
LLVMAddIncoming()
void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef * IncomingValues, LLVMBasicBlockRef * IncomingBlocks, unsigned Count)
Definition at line 2936 of file Core.cpp.
References llvm::PHINode::addIncoming(), I, and llvm::unwrap().
LLVMAddModuleFlag()
void LLVMAddModuleFlag (LLVMModuleRef M, LLVMModuleFlagBehavior Behavior, const char * Key, size_t KeyLen, LLVMMetadataRef Val)
Definition at line 381 of file Core.cpp.
References map_to_llvmModFlagBehavior(), and llvm::unwrap().
LLVMAddNamedMetadataOperand()
void LLVMAddNamedMetadataOperand (LLVMModuleRef M, const char * Name, LLVMValueRef Val)
Definition at line 1208 of file Core.cpp.
References extractMDNode(), N, and llvm::unwrap().
LLVMAddTargetDependentFunctionAttr()
void LLVMAddTargetDependentFunctionAttr (LLVMValueRef Fn, const char * A, const char * V)
Definition at line 2428 of file Core.cpp.
References llvm::Function::addAttribute(), llvm::AttributeList::FunctionIndex, llvm::DITypeRefArray::get(), and llvm::Function::getContext().
LLVMAliasGetAliasee()
LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
Definition at line 2244 of file Core.cpp.
References llvm::wrap().
LLVMAliasSetAliasee()
void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
Definition at line 2248 of file Core.cpp.
LLVMAlignOf()
LLVMValueRef LLVMAlignOf (LLVMTypeRef Ty)
Definition at line 1459 of file Core.cpp.
References llvm::ConstantExpr::getAlignOf(), llvm::unwrap(), and llvm::wrap().
LLVMAppendBasicBlock()
LLVMBasicBlockRef LLVMAppendBasicBlock (LLVMValueRef FnRef, const char * Name)
Definition at line 2657 of file Core.cpp.
References LLVMAppendBasicBlockInContext(), and LLVMGetGlobalContext().
LLVMAppendBasicBlockInContext()
LLVMBasicBlockRef LLVMAppendBasicBlockInContext (LLVMContextRef C, LLVMValueRef FnRef, const char * Name)
Definition at line 2651 of file Core.cpp.
References llvm::BasicBlock::Create(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMAppendBasicBlock().
LLVMAppendExistingBasicBlock()
void LLVMAppendExistingBasicBlock (LLVMValueRef Fn, LLVMBasicBlockRef BB)
Definition at line 2646 of file Core.cpp.
References llvm::unwrap().
LLVMAppendModuleInlineAsm()
void LLVMAppendModuleInlineAsm (LLVMModuleRef M, const char * Asm, size_t Len)
Definition at line 436 of file Core.cpp.
References llvm::unwrap().
LLVMArrayType()
LLVMTypeRef LLVMArrayType (LLVMTypeRef ElementType, unsigned ElementCount)
Definition at line 743 of file Core.cpp.
References llvm::ArrayType::get(), llvm::unwrap(), and llvm::wrap().
LLVMBasicBlockAsValue()
LLVMValueRef LLVMBasicBlockAsValue (LLVMBasicBlockRef BB)
Definition at line 2562 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBlockAddress()
LLVMValueRef LLVMBlockAddress (LLVMValueRef F, LLVMBasicBlockRef BB)
Definition at line 1814 of file Core.cpp.
References F, llvm::BlockAddress::get(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAdd()
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3258 of file Core.cpp.
References CreateAdd(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAddrSpaceCast()
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3696 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildAggregateRet()
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef * RetVals, unsigned N)
Definition at line 3083 of file Core.cpp.
References N, llvm::unwrap(), and llvm::wrap().
LLVMBuildAlloca()
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3465 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildAnd()
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3373 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayAlloca()
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3470 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayMalloc()
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3430 of file Core.cpp.
References llvm::CallInst::CreateMalloc(), llvm::IRBuilderBase::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAShr()
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3368 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicCmpXchg()
LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool singleThread)
Definition at line 3871 of file Core.cpp.
References mapFromLLVMOrdering(), llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicRMW()
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
Definition at line 3848 of file Core.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, mapFromLLVMOrdering(), llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::SyncScope::SingleThread, llvm::AtomicRMWInst::Sub, llvm::SyncScope::System, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::unwrap(), llvm::wrap(), llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
LLVMBuildBinOp()
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3388 of file Core.cpp.
References map_from_llvmopcode(), llvm::unwrap(), and llvm::wrap().
LLVMBuildBitCast()
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3691 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildBr()
LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
Definition at line 3088 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCall()
LLVMValueRef LLVMBuildCall (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3770 of file Core.cpp.
References llvm::Value::getType(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCall2()
LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3781 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCast()
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3719 of file Core.cpp.
References map_from_llvmopcode(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchPad()
LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3141 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchRet()
LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3176 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchSwitch()
LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char * Name)
Definition at line 3165 of file Core.cpp.
References llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupPad()
LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3149 of file Core.cpp.
References llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupRet()
LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3182 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCondBr()
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
Definition at line 3092 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuilderGetDefaultFPMathTag()
LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
Definition at line 3069 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuilderSetDefaultFPMathTag()
void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
Definition at line 3061 of file Core.cpp.
References llvm::unwrap().
LLVMBuildExactSDiv()
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3333 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildExactUDiv()
LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3323 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractElement()
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char * Name)
Definition at line 3801 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractValue()
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char * Name)
Definition at line 3821 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFAdd()
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3273 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFCmp()
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3757 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFDiv()
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3338 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFence()
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering Ordering, LLVMBool isSingleThread, const char * Name)
Definition at line 3532 of file Core.cpp.
References mapFromLLVMOrdering(), llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildFMul()
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3313 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFNeg()
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3409 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFPCast()
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3743 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFPExt()
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3676 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToSI()
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3656 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToUI()
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3651 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFPTrunc()
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3671 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFree()
LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
Definition at line 3475 of file Core.cpp.
References llvm::CallInst::CreateFree(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFRem()
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3353 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildFSub()
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3293 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildGEP()
LLVMValueRef LLVMBuildGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3541 of file Core.cpp.
References llvm::Type::getScalarType(), llvm::Value::getType(), llvm::unwrap(), and llvm::wrap().
LLVMBuildGEP2()
LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3551 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalString()
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 3591 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalStringPtr()
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 3596 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildICmp()
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3750 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildInBoundsGEP()
LLVMValueRef LLVMBuildInBoundsGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3558 of file Core.cpp.
References llvm::Type::getScalarType(), llvm::Value::getType(), llvm::unwrap(), and llvm::wrap().
LLVMBuildInBoundsGEP2()
LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3568 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIndirectBr()
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
Definition at line 3102 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertElement()
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char * Name)
Definition at line 3807 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertValue()
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char * Name)
Definition at line 3826 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast()
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3737 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast2()
LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char * Name)
Definition at line 3730 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIntToPtr()
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3686 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildInvoke()
LLVMValueRef LLVMBuildInvoke (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char * Name)
Definition at line 3107 of file Core.cpp.
References llvm::Value::getType(), llvm::unwrap(), and llvm::wrap().
LLVMBuildInvoke2()
LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char * Name)
Definition at line 3120 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNotNull()
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 3838 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNull()
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 3833 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildLandingPad()
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char * Name)
Definition at line 3129 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildLoad()
LLVMValueRef LLVMBuildLoad (LLVMBuilderRef B, LLVMValueRef PointerVal, const char * Name)
Definition at line 3480 of file Core.cpp.
References llvm::PointerType::getElementType(), llvm::Value::getType(), llvm::unwrap(), and llvm::wrap().
LLVMBuildLoad2()
LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char * Name)
Definition at line 3488 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildLShr()
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3363 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildMalloc()
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3419 of file Core.cpp.
References llvm::CallInst::CreateMalloc(), llvm::IRBuilderBase::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMBuildMemCpy()
LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Definition at line 3447 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildMemMove()
LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Definition at line 3456 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildMemSet()
LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
Definition at line 3441 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildMul()
LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3298 of file Core.cpp.
References CreateMul(), llvm::unwrap(), and llvm::wrap().
LLVMBuildNeg()
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3395 of file Core.cpp.
References CreateNeg(), llvm::unwrap(), and llvm::wrap().
LLVMBuildNot()
LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3413 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWAdd()
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3263 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWMul()
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3303 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWNeg()
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3399 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWSub()
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3283 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWAdd()
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3268 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWMul()
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3308 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWNeg()
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3404 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWSub()
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3288 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildOr()
LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3378 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildPhi()
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3766 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildPointerCast()
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3725 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrDiff()
LLVMValueRef LLVMBuildPtrDiff (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3843 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrToInt()
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3681 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildResume()
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
Definition at line 3161 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildRet()
LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
Definition at line 3079 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildRetVoid()
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
Definition at line 3075 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSDiv()
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3328 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSelect()
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char * Name)
Definition at line 3789 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSExt()
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3646 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSExtOrBitCast()
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3707 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildShl()
LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3358 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildShuffleVector()
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char * Name)
Definition at line 3814 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSIToFP()
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3666 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSRem()
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3348 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildStore()
LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef PointerVal)
Definition at line 3493 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildStructGEP()
LLVMValueRef LLVMBuildStructGEP (LLVMBuilderRef B, LLVMValueRef Pointer, unsigned Idx, const char * Name)
Definition at line 3576 of file Core.cpp.
References llvm::Type::getScalarType(), llvm::Value::getType(), Idx, llvm::unwrap(), and llvm::wrap().
LLVMBuildStructGEP2()
LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char * Name)
Definition at line 3584 of file Core.cpp.
References Idx, llvm::unwrap(), and llvm::wrap().
LLVMBuildSub()
LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3278 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSwitch()
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
Definition at line 3097 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildTrunc()
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3636 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildTruncOrBitCast()
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3713 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildUDiv()
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3318 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildUIToFP()
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3661 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildUnreachable()
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
Definition at line 3188 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildURem()
LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3343 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildVAArg()
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char * Name)
Definition at line 3796 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildXor()
LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3383 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildZExt()
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3641 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildZExtOrBitCast()
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3701 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMClearInsertionPosition()
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
Definition at line 3015 of file Core.cpp.
References llvm::unwrap().
LLVMConstAdd()
LLVMValueRef LLVMConstAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1488 of file Core.cpp.
References llvm::ConstantExpr::getAdd(), and llvm::wrap().
LLVMConstAddrSpaceCast()
LLVMValueRef LLVMConstAddrSpaceCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1721 of file Core.cpp.
References llvm::ConstantExpr::getAddrSpaceCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstAllOnes()
LLVMValueRef LLVMConstAllOnes (LLVMTypeRef Ty)
Definition at line 1020 of file Core.cpp.
References llvm::Constant::getAllOnesValue(), llvm::unwrap(), and llvm::wrap().
LLVMConstAnd()
LLVMValueRef LLVMConstAnd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1596 of file Core.cpp.
References llvm::ConstantExpr::getAnd(), and llvm::wrap().
LLVMConstArray()
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef * ConstantVals, unsigned Length)
Definition at line 1397 of file Core.cpp.
References llvm::ConstantArray::get(), llvm::ArrayType::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstAShr()
LLVMValueRef LLVMConstAShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1635 of file Core.cpp.
References llvm::ConstantExpr::getAShr(), and llvm::wrap().
LLVMConstBitCast()
LLVMValueRef LLVMConstBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1716 of file Core.cpp.
References llvm::ConstantExpr::getBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstExactSDiv()
LLVMValueRef LLVMConstExactSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1570 of file Core.cpp.
References llvm::ConstantExpr::getExactSDiv(), and llvm::wrap().
LLVMConstExactUDiv()
LLVMValueRef LLVMConstExactUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1559 of file Core.cpp.
References llvm::ConstantExpr::getExactUDiv(), and llvm::wrap().
LLVMConstExtractElement()
LLVMValueRef LLVMConstExtractElement (LLVMValueRef VectorConstant, LLVMValueRef IndexConstant)
Definition at line 1770 of file Core.cpp.
References llvm::ConstantExpr::getExtractElement(), and llvm::wrap().
LLVMConstExtractValue()
LLVMValueRef LLVMConstExtractValue (LLVMValueRef AggConstant, unsigned * IdxList, unsigned NumIdx)
Definition at line 1792 of file Core.cpp.
References llvm::ConstantExpr::getExtractValue(), and llvm::wrap().
LLVMConstFAdd()
LLVMValueRef LLVMConstFAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1505 of file Core.cpp.
References llvm::ConstantExpr::getFAdd(), and llvm::wrap().
LLVMConstFCmp()
LLVMValueRef LLVMConstFCmp (LLVMRealPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1618 of file Core.cpp.
References llvm::ConstantExpr::getFCmp(), and llvm::wrap().
LLVMConstFDiv()
LLVMValueRef LLVMConstFDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1576 of file Core.cpp.
References llvm::ConstantExpr::getFDiv(), and llvm::wrap().
LLVMConstFMul()
LLVMValueRef LLVMConstFMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1549 of file Core.cpp.
References llvm::ConstantExpr::getFMul(), and llvm::wrap().
LLVMConstFNeg()
LLVMValueRef LLVMConstFNeg (LLVMValueRef ConstantVal)
Definition at line 1480 of file Core.cpp.
References llvm::ConstantExpr::getFNeg(), and llvm::wrap().
LLVMConstFPCast()
LLVMValueRef LLVMConstFPCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1757 of file Core.cpp.
References llvm::ConstantExpr::getFPCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPExt()
LLVMValueRef LLVMConstFPExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1681 of file Core.cpp.
References llvm::ConstantExpr::getFPExtend(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPToSI()
LLVMValueRef LLVMConstFPToSI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1701 of file Core.cpp.
References llvm::ConstantExpr::getFPToSI(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPToUI()
LLVMValueRef LLVMConstFPToUI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1696 of file Core.cpp.
References llvm::ConstantExpr::getFPToUI(), llvm::unwrap(), and llvm::wrap().
LLVMConstFPTrunc()
LLVMValueRef LLVMConstFPTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1676 of file Core.cpp.
References llvm::ConstantExpr::getFPTrunc(), llvm::unwrap(), and llvm::wrap().
LLVMConstFRem()
LLVMValueRef LLVMConstFRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1591 of file Core.cpp.
References llvm::ConstantExpr::getFRem(), and llvm::wrap().
LLVMConstFSub()
LLVMValueRef LLVMConstFSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1527 of file Core.cpp.
References llvm::ConstantExpr::getFSub(), and llvm::wrap().
LLVMConstGEP()
LLVMValueRef LLVMConstGEP (LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
Definition at line 1640 of file Core.cpp.
References llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::wrap().
LLVMConstICmp()
LLVMValueRef LLVMConstICmp (LLVMIntPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1611 of file Core.cpp.
References llvm::ConstantExpr::getICmp(), and llvm::wrap().
LLVMConstInBoundsGEP()
LLVMValueRef LLVMConstInBoundsGEP (LLVMValueRef ConstantVal, LLVMValueRef * ConstantIndices, unsigned NumIndices)
Definition at line 1650 of file Core.cpp.
References llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::wrap().
LLVMConstInlineAsm()
LLVMValueRef LLVMConstInlineAsm (LLVMTypeRef Ty, const char * AsmString, const char * Constraints, LLVMBool HasSideEffects, LLVMBool IsAlignStack)
Definition at line 1806 of file Core.cpp.
References llvm::InlineAsm::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstInsertElement()
LLVMValueRef LLVMConstInsertElement (LLVMValueRef VectorConstant, LLVMValueRef ElementValueConstant, LLVMValueRef IndexConstant)
Definition at line 1776 of file Core.cpp.
References llvm::ConstantExpr::getInsertElement(), and llvm::wrap().
LLVMConstInsertValue()
LLVMValueRef LLVMConstInsertValue (LLVMValueRef AggConstant, LLVMValueRef ElementValueConstant, unsigned * IdxList, unsigned NumIdx)
Definition at line 1798 of file Core.cpp.
References llvm::ConstantExpr::getInsertValue(), and llvm::wrap().
LLVMConstInt()
LLVMValueRef LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)
Definition at line 1298 of file Core.cpp.
References llvm::ConstantInt::get(), N, and llvm::wrap().
LLVMConstIntCast()
LLVMValueRef LLVMConstIntCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType, LLVMBool isSigned)
Definition at line 1751 of file Core.cpp.
References llvm::ConstantExpr::getIntegerCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstIntGetSExtValue()
long long LLVMConstIntGetSExtValue (LLVMValueRef ConstantVal)
Definition at line 1341 of file Core.cpp.
LLVMConstIntGetZExtValue()
unsigned long long LLVMConstIntGetZExtValue (LLVMValueRef ConstantVal)
Definition at line 1337 of file Core.cpp.
LLVMConstIntOfArbitraryPrecision()
LLVMValueRef LLVMConstIntOfArbitraryPrecision (LLVMTypeRef IntTy, unsigned NumWords, const uint64_t Words[])
Definition at line 1303 of file Core.cpp.
References llvm::ConstantInt::get(), llvm::IntegerType::getBitWidth(), llvm::Type::getContext(), and llvm::wrap().
LLVMConstIntOfString()
LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char Str[], uint8_t Radix)
Definition at line 1312 of file Core.cpp.
References llvm::ConstantInt::get(), and llvm::wrap().
LLVMConstIntOfStringAndSize()
LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char Str[], unsigned SLen, uint8_t Radix)
Definition at line 1318 of file Core.cpp.
References llvm::ConstantInt::get(), and llvm::wrap().
LLVMConstIntToPtr()
LLVMValueRef LLVMConstIntToPtr (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1711 of file Core.cpp.
References llvm::ConstantExpr::getIntToPtr(), llvm::unwrap(), and llvm::wrap().
LLVMConstLShr()
LLVMValueRef LLVMConstLShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1630 of file Core.cpp.
References llvm::ConstantExpr::getLShr(), and llvm::wrap().
LLVMConstMul()
LLVMValueRef LLVMConstMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1532 of file Core.cpp.
References llvm::ConstantExpr::getMul(), and llvm::wrap().
LLVMConstNamedStruct()
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef * ConstantVals, unsigned Count)
Definition at line 1417 of file Core.cpp.
References llvm::ConstantStruct::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstNeg()
LLVMValueRef LLVMConstNeg (LLVMValueRef ConstantVal)
Definition at line 1467 of file Core.cpp.
References llvm::ConstantExpr::getNeg(), and llvm::wrap().
LLVMConstNot()
LLVMValueRef LLVMConstNot (LLVMValueRef ConstantVal)
Definition at line 1484 of file Core.cpp.
References llvm::ConstantExpr::getNot(), and llvm::wrap().
LLVMConstNSWAdd()
LLVMValueRef LLVMConstNSWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1493 of file Core.cpp.
References llvm::ConstantExpr::getNSWAdd(), and llvm::wrap().
LLVMConstNSWMul()
LLVMValueRef LLVMConstNSWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1537 of file Core.cpp.
References llvm::ConstantExpr::getNSWMul(), and llvm::wrap().
LLVMConstNSWNeg()
LLVMValueRef LLVMConstNSWNeg (LLVMValueRef ConstantVal)
Definition at line 1471 of file Core.cpp.
References llvm::ConstantExpr::getNSWNeg(), and llvm::wrap().
LLVMConstNSWSub()
LLVMValueRef LLVMConstNSWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1515 of file Core.cpp.
References llvm::ConstantExpr::getNSWSub(), and llvm::wrap().
LLVMConstNull()
LLVMValueRef LLVMConstNull (LLVMTypeRef Ty)
Definition at line 1016 of file Core.cpp.
References llvm::Constant::getNullValue(), llvm::unwrap(), and llvm::wrap().
LLVMConstNUWAdd()
LLVMValueRef LLVMConstNUWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1499 of file Core.cpp.
References llvm::ConstantExpr::getNUWAdd(), and llvm::wrap().
LLVMConstNUWMul()
LLVMValueRef LLVMConstNUWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1543 of file Core.cpp.
References llvm::ConstantExpr::getNUWMul(), and llvm::wrap().
LLVMConstNUWNeg()
LLVMValueRef LLVMConstNUWNeg (LLVMValueRef ConstantVal)
Definition at line 1475 of file Core.cpp.
References llvm::ConstantExpr::getNUWNeg(), and llvm::wrap().
LLVMConstNUWSub()
LLVMValueRef LLVMConstNUWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1521 of file Core.cpp.
References llvm::ConstantExpr::getNUWSub(), and llvm::wrap().
LLVMConstOr()
LLVMValueRef LLVMConstOr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1601 of file Core.cpp.
References llvm::ConstantExpr::getOr(), and llvm::wrap().
LLVMConstPointerCast()
LLVMValueRef LLVMConstPointerCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1745 of file Core.cpp.
References llvm::ConstantExpr::getPointerCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstPointerNull()
LLVMValueRef LLVMConstPointerNull (LLVMTypeRef Ty)
Definition at line 1042 of file Core.cpp.
References llvm::ConstantPointerNull::get(), and llvm::wrap().
LLVMConstPtrToInt()
LLVMValueRef LLVMConstPtrToInt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1706 of file Core.cpp.
References llvm::ConstantExpr::getPtrToInt(), llvm::unwrap(), and llvm::wrap().
LLVMConstReal()
LLVMValueRef LLVMConstReal (LLVMTypeRef RealTy, double N)
Definition at line 1324 of file Core.cpp.
References llvm::ConstantFP::get(), N, llvm::unwrap(), and llvm::wrap().
LLVMConstRealGetDouble()
double LLVMConstRealGetDouble (LLVMValueRef ConstantVal, LLVMBool * LosesInfo)
Definition at line 1345 of file Core.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getValueAPF(), llvm::Type::isDoubleTy(), and llvm::Type::isFloatTy().
LLVMConstRealOfString()
LLVMValueRef LLVMConstRealOfString (LLVMTypeRef RealTy, const char * Text)
Definition at line 1328 of file Core.cpp.
References llvm::ConstantFP::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstRealOfStringAndSize()
LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char Str[], unsigned SLen)
Definition at line 1332 of file Core.cpp.
References llvm::ConstantFP::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstSDiv()
LLVMValueRef LLVMConstSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1565 of file Core.cpp.
References llvm::ConstantExpr::getSDiv(), and llvm::wrap().
LLVMConstSelect()
LLVMValueRef LLVMConstSelect (LLVMValueRef ConstantCondition, LLVMValueRef ConstantIfTrue, LLVMValueRef ConstantIfFalse)
Definition at line 1762 of file Core.cpp.
References llvm::ConstantExpr::getSelect(), and llvm::wrap().
LLVMConstSExt()
LLVMValueRef LLVMConstSExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1666 of file Core.cpp.
References llvm::ConstantExpr::getSExt(), llvm::unwrap(), and llvm::wrap().
LLVMConstSExtOrBitCast()
LLVMValueRef LLVMConstSExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1733 of file Core.cpp.
References llvm::ConstantExpr::getSExtOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstShl()
LLVMValueRef LLVMConstShl (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1625 of file Core.cpp.
References llvm::ConstantExpr::getShl(), and llvm::wrap().
LLVMConstShuffleVector()
LLVMValueRef LLVMConstShuffleVector (LLVMValueRef VectorAConstant, LLVMValueRef VectorBConstant, LLVMValueRef MaskConstant)
Definition at line 1784 of file Core.cpp.
References llvm::ConstantExpr::getShuffleVector(), and llvm::wrap().
LLVMConstSIToFP()
LLVMValueRef LLVMConstSIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1691 of file Core.cpp.
References llvm::ConstantExpr::getSIToFP(), llvm::unwrap(), and llvm::wrap().
LLVMConstSRem()
LLVMValueRef LLVMConstSRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1586 of file Core.cpp.
References llvm::ConstantExpr::getSRem(), and llvm::wrap().
LLVMConstString()
LLVMValueRef LLVMConstString (const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Definition at line 1377 of file Core.cpp.
References LLVMConstStringInContext(), and LLVMGetGlobalContext().
LLVMConstStringInContext()
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Definition at line 1368 of file Core.cpp.
References llvm::ConstantDataArray::getString(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstString().
LLVMConstStruct()
LLVMValueRef LLVMConstStruct (LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Definition at line 1411 of file Core.cpp.
References LLVMConstStructInContext(), and LLVMGetGlobalContext().
LLVMConstStructInContext()
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Definition at line 1403 of file Core.cpp.
References llvm::ConstantStruct::getAnon(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstStruct().
LLVMConstSub()
LLVMValueRef LLVMConstSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1510 of file Core.cpp.
References llvm::ConstantExpr::getSub(), and llvm::wrap().
LLVMConstTrunc()
LLVMValueRef LLVMConstTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1661 of file Core.cpp.
References llvm::ConstantExpr::getTrunc(), llvm::unwrap(), and llvm::wrap().
LLVMConstTruncOrBitCast()
LLVMValueRef LLVMConstTruncOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1739 of file Core.cpp.
References llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMConstUDiv()
LLVMValueRef LLVMConstUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1554 of file Core.cpp.
References llvm::ConstantExpr::getUDiv(), and llvm::wrap().
LLVMConstUIToFP()
LLVMValueRef LLVMConstUIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1686 of file Core.cpp.
References llvm::ConstantExpr::getUIToFP(), llvm::unwrap(), and llvm::wrap().
LLVMConstURem()
LLVMValueRef LLVMConstURem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1581 of file Core.cpp.
References llvm::ConstantExpr::getURem(), and llvm::wrap().
LLVMConstVector()
LLVMValueRef LLVMConstVector (LLVMValueRef * ScalarConstantVals, unsigned Size)
Definition at line 1426 of file Core.cpp.
References llvm::ConstantVector::get(), and llvm::wrap().
LLVMConstXor()
LLVMValueRef LLVMConstXor (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
Definition at line 1606 of file Core.cpp.
References llvm::ConstantExpr::getXor(), and llvm::wrap().
LLVMConstZExt()
LLVMValueRef LLVMConstZExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1671 of file Core.cpp.
References llvm::ConstantExpr::getZExt(), llvm::unwrap(), and llvm::wrap().
LLVMConstZExtOrBitCast()
LLVMValueRef LLVMConstZExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
Definition at line 1727 of file Core.cpp.
References llvm::ConstantExpr::getZExtOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMContextCreate()
LLVMContextRef LLVMContextCreate ()
Definition at line 78 of file Core.cpp.
References llvm::wrap().
LLVMContextDispose()
void LLVMContextDispose (LLVMContextRef C)
Definition at line 117 of file Core.cpp.
References llvm::unwrap().
LLVMContextGetDiagnosticContext()
void * LLVMContextGetDiagnosticContext (LLVMContextRef C)
Definition at line 98 of file Core.cpp.
References llvm::unwrap().
LLVMContextGetDiagnosticHandler()
LLVMDiagnosticHandler LLVMContextGetDiagnosticHandler (LLVMContextRef C)
Definition at line 93 of file Core.cpp.
References LLVM_EXTENSION, and llvm::unwrap().
LLVMContextSetDiagnosticHandler()
void LLVMContextSetDiagnosticHandler (LLVMContextRef C, LLVMDiagnosticHandler Handler, void * DiagnosticContext)
Definition at line 84 of file Core.cpp.
References LLVM_EXTENSION, and llvm::unwrap().
LLVMContextSetDiscardValueNames()
void LLVMContextSetDiscardValueNames (LLVMContextRef C, LLVMBool Discard)
Definition at line 113 of file Core.cpp.
References llvm::unwrap().
LLVMContextSetYieldCallback()
void LLVMContextSetYieldCallback (LLVMContextRef C, LLVMYieldCallback Callback, void * OpaqueHandle)
Definition at line 102 of file Core.cpp.
References LLVM_EXTENSION, and llvm::unwrap().
LLVMContextShouldDiscardValueNames()
LLVMBool LLVMContextShouldDiscardValueNames (LLVMContextRef C)
Definition at line 109 of file Core.cpp.
References llvm::unwrap().
LLVMCopyModuleFlagsMetadata()
LLVMModuleFlagEntry * LLVMCopyModuleFlagsMetadata (LLVMModuleRef M, size_t * Len)
Definition at line 332 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Behavior, LLVMOpaqueModuleFlagEntry::Key, LLVMOpaqueModuleFlagEntry::KeyLen, map_from_llvmModFlagBehavior(), LLVMOpaqueModuleFlagEntry::Metadata, llvm::safe_malloc(), llvm::unwrap(), and llvm::wrap().
LLVMCountBasicBlocks()
unsigned LLVMCountBasicBlocks (LLVMValueRef FnRef)
Definition at line 2586 of file Core.cpp.
LLVMCountIncoming()
unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
Definition at line 2943 of file Core.cpp.
LLVMCountParams()
unsigned LLVMCountParams (LLVMValueRef FnRef)
Definition at line 2437 of file Core.cpp.
LLVMCountParamTypes()
unsigned LLVMCountParamTypes (LLVMTypeRef FunctionTy)
Definition at line 657 of file Core.cpp.
LLVMCountStructElementTypes()
unsigned LLVMCountStructElementTypes (LLVMTypeRef StructTy)
Definition at line 701 of file Core.cpp.
LLVMCreateBasicBlockInContext()
LLVMBasicBlockRef LLVMCreateBasicBlockInContext (LLVMContextRef C, const char * Name)
Definition at line 2632 of file Core.cpp.
References llvm::BasicBlock::Create(), llvm::unwrap(), and llvm::wrap().
LLVMCreateBuilder()
LLVMBuilderRef LLVMCreateBuilder (void)
Definition at line 2990 of file Core.cpp.
References LLVMCreateBuilderInContext(), and LLVMGetGlobalContext().
LLVMCreateBuilderInContext()
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
Definition at line 2986 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateBuilder().
LLVMCreateEnumAttribute()
LLVMAttributeRef LLVMCreateEnumAttribute (LLVMContextRef C, unsigned KindID, uint64_t Val)
Definition at line 141 of file Core.cpp.
References llvm::DITypeRefArray::get(), llvm::Attribute::getWithByValType(), llvm::unwrap(), and llvm::wrap().
LLVMCreateFunctionPassManager()
LLVMPassManagerRef LLVMCreateFunctionPassManager (LLVMModuleProviderRef P)
Definition at line 4016 of file Core.cpp.
References LLVMCreateFunctionPassManagerForModule(), and P.
LLVMCreateFunctionPassManagerForModule()
LLVMPassManagerRef LLVMCreateFunctionPassManagerForModule (LLVMModuleRef M)
Definition at line 4012 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateFunctionPassManager().
LLVMCreateMemoryBufferWithContentsOfFile()
LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char * Path, LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 3942 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRange()
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char * InputData, size_t InputDataLength, const char * BufferName, LLVMBool RequiresNullTerminator)
Definition at line 3967 of file Core.cpp.
References llvm::MemoryBuffer::getMemBuffer(), llvm::release, and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRangeCopy()
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char * InputData, size_t InputDataLength, const char * BufferName)
Definition at line 3978 of file Core.cpp.
References llvm::MemoryBuffer::getMemBufferCopy(), llvm::release, and llvm::wrap().
LLVMCreateMemoryBufferWithSTDIN()
LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 3956 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getSTDIN(), and llvm::wrap().
LLVMCreateMessage()
char * LLVMCreateMessage (const char * Message)
Definition at line 65 of file Core.cpp.
Referenced by LLVMGetDiagInfoDescription().
LLVMCreateModuleProviderForExistingModule()
LLVMModuleProviderRef LLVMCreateModuleProviderForExistingModule (LLVMModuleRef M)
Definition at line 3931 of file Core.cpp.
LLVMCreatePassManager()
LLVMPassManagerRef LLVMCreatePassManager ()
Definition at line 4008 of file Core.cpp.
References llvm::wrap().
LLVMCreateStringAttribute()
LLVMAttributeRef LLVMCreateStringAttribute (LLVMContextRef C, const char * K, unsigned KLength, const char * V, unsigned VLength)
Definition at line 166 of file Core.cpp.
References llvm::DITypeRefArray::get(), llvm::unwrap(), and llvm::wrap().
LLVMDeleteBasicBlock()
void LLVMDeleteBasicBlock (LLVMBasicBlockRef BBRef)
Definition at line 2673 of file Core.cpp.
References llvm::unwrap().
LLVMDeleteFunction()
void LLVMDeleteFunction (LLVMValueRef Fn)
Definition at line 2296 of file Core.cpp.
LLVMDeleteGlobal()
void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
Definition at line 2118 of file Core.cpp.
LLVMDisposeBuilder()
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
Definition at line 3028 of file Core.cpp.
References llvm::unwrap().
LLVMDisposeMemoryBuffer()
void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
Definition at line 3996 of file Core.cpp.
References llvm::unwrap().
LLVMDisposeMessage()
void LLVMDisposeMessage (char * Message)
Definition at line 69 of file Core.cpp.
LLVMDisposeModule()
void LLVMDisposeModule (LLVMModuleRef M)
Definition at line 239 of file Core.cpp.
References llvm::unwrap().
LLVMDisposeModuleFlagsMetadata()
void LLVMDisposeModuleFlagsMetadata (LLVMModuleFlagEntry * Entries)
Definition at line 349 of file Core.cpp.
LLVMDisposeModuleProvider()
void LLVMDisposeModuleProvider (LLVMModuleProviderRef MP)
Definition at line 3935 of file Core.cpp.
References llvm::unwrap().
LLVMDisposePassManager()
void LLVMDisposePassManager (LLVMPassManagerRef PM)
Definition at line 4037 of file Core.cpp.
References llvm::unwrap().
LLVMDisposeValueMetadataEntries()
void LLVMDisposeValueMetadataEntries (LLVMValueMetadataEntry * Entries)
Definition at line 2049 of file Core.cpp.
LLVMDoubleType()
LLVMTypeRef LLVMDoubleType (void)
Definition at line 624 of file Core.cpp.
References LLVMDoubleTypeInContext(), and LLVMGetGlobalContext().
LLVMDoubleTypeInContext()
LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
Definition at line 602 of file Core.cpp.
References llvm::IRBuilderBase::getDoubleTy(), and llvm::unwrap().
Referenced by LLVMDoubleType().
LLVMDumpModule()
void LLVMDumpModule (LLVMModuleRef M)
Definition at line 390 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMDumpType()
void LLVMDumpType (LLVMTypeRef Ty)
Definition at line 526 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMDumpValue()
void LLVMDumpValue (LLVMValueRef Val)
Definition at line 837 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMEraseGlobalIFunc()
void LLVMEraseGlobalIFunc (LLVMValueRef IFunc)
Definition at line 2552 of file Core.cpp.
LLVMFinalizeFunctionPassManager()
LLVMBool LLVMFinalizeFunctionPassManager (LLVMPassManagerRef FPM)
Definition at line 4033 of file Core.cpp.
LLVMFloatType()
LLVMTypeRef LLVMFloatType (void)
Definition at line 621 of file Core.cpp.
References LLVMFloatTypeInContext(), and LLVMGetGlobalContext().
LLVMFloatTypeInContext()
LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
Definition at line 599 of file Core.cpp.
References llvm::IRBuilderBase::getFloatTy(), and llvm::unwrap().
Referenced by LLVMFloatType().
LLVMFP128Type()
LLVMTypeRef LLVMFP128Type (void)
Definition at line 630 of file Core.cpp.
References LLVMFP128TypeInContext(), and LLVMGetGlobalContext().
LLVMFP128TypeInContext()
LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
Definition at line 608 of file Core.cpp.
References llvm::Type::getFP128Ty(), and llvm::unwrap().
Referenced by LLVMFP128Type().
LLVMFunctionType()
LLVMTypeRef LLVMFunctionType (LLVMTypeRef ReturnType, LLVMTypeRef * ParamTypes, unsigned ParamCount, LLVMBool IsVarArg)
Definition at line 642 of file Core.cpp.
References llvm::FunctionType::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetAlignment()
unsigned LLVMGetAlignment (LLVMValueRef V)
Definition at line 1993 of file Core.cpp.
References llvm_unreachable, and P.
LLVMGetAllocatedType()
LLVMTypeRef LLVMGetAllocatedType (LLVMValueRef Alloca)
Definition at line 2920 of file Core.cpp.
References llvm::wrap().
LLVMGetArgOperand()
LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
Definition at line 3248 of file Core.cpp.
References llvm::wrap().
LLVMGetArrayLength()
unsigned LLVMGetArrayLength (LLVMTypeRef ArrayTy)
Definition at line 766 of file Core.cpp.
LLVMGetAsString()
const char * LLVMGetAsString (LLVMValueRef C, size_t * Length)
Definition at line 1391 of file Core.cpp.
LLVMGetAttributeCountAtIndex()
unsigned LLVMGetAttributeCountAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx)
Definition at line 2393 of file Core.cpp.
References F, and Idx.
LLVMGetAttributesAtIndex()
void LLVMGetAttributesAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, LLVMAttributeRef * Attrs)
Definition at line 2398 of file Core.cpp.
References F, Idx, and llvm::wrap().
LLVMGetBasicBlockName()
const char * LLVMGetBasicBlockName (LLVMBasicBlockRef BB)
Definition at line 2574 of file Core.cpp.
References llvm::unwrap().
LLVMGetBasicBlockParent()
LLVMValueRef LLVMGetBasicBlockParent (LLVMBasicBlockRef BB)
Definition at line 2578 of file Core.cpp.
References getParent(), llvm::unwrap(), and llvm::wrap().
LLVMGetBasicBlocks()
void LLVMGetBasicBlocks (LLVMValueRef FnRef, LLVMBasicBlockRef * BasicBlocksRefs)
Definition at line 2590 of file Core.cpp.
References llvm::wrap().
LLVMGetBasicBlockTerminator()
LLVMValueRef LLVMGetBasicBlockTerminator (LLVMBasicBlockRef BB)
Definition at line 2582 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetBufferSize()
size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
Definition at line 3992 of file Core.cpp.
References llvm::unwrap().
LLVMGetBufferStart()
const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
Definition at line 3988 of file Core.cpp.
References llvm::unwrap().
LLVMGetCalledFunctionType()
LLVMTypeRef LLVMGetCalledFunctionType (LLVMValueRef Instr)
Definition at line 2842 of file Core.cpp.
References llvm::wrap().
LLVMGetCalledValue()
LLVMValueRef LLVMGetCalledValue (LLVMValueRef Instr)
Definition at line 2838 of file Core.cpp.
References llvm::wrap().
LLVMGetCallSiteAttributeCount()
unsigned LLVMGetCallSiteAttributeCount (LLVMValueRef C, LLVMAttributeIndex Idx)
Definition at line 2800 of file Core.cpp.
References Idx.
LLVMGetCallSiteAttributes()
void LLVMGetCallSiteAttributes (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef * Attrs)
Definition at line 2807 of file Core.cpp.
References Idx, and llvm::wrap().
LLVMGetCallSiteEnumAttribute()
LLVMAttributeRef LLVMGetCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2815 of file Core.cpp.
References Idx, and llvm::wrap().
LLVMGetCallSiteStringAttribute()
LLVMAttributeRef LLVMGetCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2822 of file Core.cpp.
References Idx, and llvm::wrap().
LLVMGetClause()
LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
Definition at line 3205 of file Core.cpp.
References Idx, and llvm::wrap().
LLVMGetCmpXchgFailureOrdering()
LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
Definition at line 3915 of file Core.cpp.
References mapToLLVMOrdering(), and P.
LLVMGetCmpXchgSuccessOrdering()
LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
Definition at line 3902 of file Core.cpp.
References mapToLLVMOrdering(), and P.
LLVMGetCondition()
LLVMValueRef LLVMGetCondition (LLVMValueRef Branch)
Definition at line 2904 of file Core.cpp.
References llvm::wrap().
LLVMGetConstOpcode()
LLVMOpcode LLVMGetConstOpcode (LLVMValueRef ConstantVal)
Definition at line 1455 of file Core.cpp.
References getOpcode(), and map_to_llvmopcode().
LLVMGetCurrentDebugLocation()
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Definition at line 3051 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetCurrentDebugLocation2()
LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
Definition at line 3034 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetDataLayout()
const char * LLVMGetDataLayout (LLVMModuleRef M)
Definition at line 268 of file Core.cpp.
References LLVMGetDataLayoutStr().
LLVMGetDataLayoutStr()
const char * LLVMGetDataLayoutStr (LLVMModuleRef M)
Definition at line 264 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetDataLayout().
LLVMGetDebugLocColumn()
unsigned LLVMGetDebugLocColumn (LLVMValueRef Val)
Definition at line 1288 of file Core.cpp.
References I, and llvm::unwrap().
LLVMGetDebugLocDirectory()
const char * LLVMGetDebugLocDirectory (LLVMValueRef Val, unsigned * Length)
Definition at line 1218 of file Core.cpp.
References assert(), F, I, and llvm::unwrap().
LLVMGetDebugLocFilename()
const char * LLVMGetDebugLocFilename (LLVMValueRef Val, unsigned * Length)
Definition at line 1242 of file Core.cpp.
References assert(), F, I, and llvm::unwrap().
LLVMGetDebugLocLine()
unsigned LLVMGetDebugLocLine (LLVMValueRef Val)
Definition at line 1266 of file Core.cpp.
References assert(), F, I, and llvm::unwrap().
LLVMGetDiagInfoDescription()
char * LLVMGetDiagInfoDescription (LLVMDiagnosticInfoRef DI)
Definition at line 196 of file Core.cpp.
References llvm::raw_ostream::flush(), LLVMCreateMessage(), and llvm::unwrap().
LLVMGetDiagInfoSeverity()
LLVMDiagnosticSeverity LLVMGetDiagInfoSeverity (LLVMDiagnosticInfoRef DI)
Definition at line 207 of file Core.cpp.
References llvm::DS_Note, llvm::DS_Remark, llvm::DS_Warning, and llvm::unwrap().
LLVMGetDLLStorageClass()
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
Definition at line 1942 of file Core.cpp.
LLVMGetElementAsConstant()
LLVMValueRef LLVMGetElementAsConstant (LLVMValueRef C, unsigned idx)
Definition at line 1383 of file Core.cpp.
References llvm::wrap().
LLVMGetElementType()
LLVMTypeRef LLVMGetElementType (LLVMTypeRef WrappedTy)
Definition at line 755 of file Core.cpp.
References llvm::wrap().
LLVMGetEntryBasicBlock()
LLVMBasicBlockRef LLVMGetEntryBasicBlock (LLVMValueRef Fn)
Definition at line 2596 of file Core.cpp.
References llvm::wrap().
LLVMGetEnumAttributeAtIndex()
LLVMAttributeRef LLVMGetEnumAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2405 of file Core.cpp.
References F, Idx, and llvm::wrap().
LLVMGetEnumAttributeKind()
unsigned LLVMGetEnumAttributeKind (LLVMAttributeRef A)
Definition at line 155 of file Core.cpp.
References llvm::Attribute::getKindAsEnum(), and llvm::unwrap().
LLVMGetEnumAttributeKindForName()
unsigned LLVMGetEnumAttributeKindForName (const char * Name, size_t SLen)
Definition at line 133 of file Core.cpp.
LLVMGetEnumAttributeValue()
uint64_t LLVMGetEnumAttributeValue (LLVMAttributeRef A)
Definition at line 159 of file Core.cpp.
References llvm::unwrap().
LLVMGetFCmpPredicate()
LLVMRealPredicate LLVMGetFCmpPredicate (LLVMValueRef Inst)
Definition at line 2744 of file Core.cpp.
References I, and llvm::unwrap().
LLVMGetFirstBasicBlock()
LLVMBasicBlockRef LLVMGetFirstBasicBlock (LLVMValueRef Fn)
Definition at line 2600 of file Core.cpp.
References llvm::Function::begin(), llvm::Function::end(), I, and llvm::wrap().
LLVMGetFirstFunction()
LLVMValueRef LLVMGetFirstFunction (LLVMModuleRef M)
Definition at line 2264 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstGlobal()
LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
Definition at line 2086 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstGlobalAlias()
LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
Definition at line 2212 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstGlobalIFunc()
LLVMValueRef LLVMGetFirstGlobalIFunc (LLVMModuleRef M)
Definition at line 2512 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstInstruction()
LLVMValueRef LLVMGetFirstInstruction (LLVMBasicBlockRef BB)
Definition at line 2695 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstNamedMetadata()
LLVMNamedMDNodeRef LLVMGetFirstNamedMetadata (LLVMModuleRef M)
Definition at line 1130 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetFirstParam()
LLVMValueRef LLVMGetFirstParam (LLVMValueRef Fn)
Definition at line 2459 of file Core.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), I, and llvm::wrap().
LLVMGetFirstUse()
LLVMUseRef LLVMGetFirstUse (LLVMValueRef Val)
Definition at line 948 of file Core.cpp.
References I, llvm::unwrap(), llvm::Value::use_begin(), llvm::Value::use_end(), and llvm::wrap().
LLVMGetFunctionCallConv()
unsigned LLVMGetFunctionCallConv (LLVMValueRef Fn)
Definition at line 2366 of file Core.cpp.
LLVMGetGC()
const char * LLVMGetGC (LLVMValueRef Fn)
Definition at line 2375 of file Core.cpp.
References F.
LLVMGetGlobalContext()
LLVMContextRef LLVMGetGlobalContext ()
Definition at line 82 of file Core.cpp.
References GlobalContext, and llvm::wrap().
Referenced by LLVMAppendBasicBlock(), LLVMConstString(), LLVMConstStruct(), LLVMCreateBuilder(), LLVMDoubleType(), LLVMFloatType(), LLVMFP128Type(), LLVMGetMDKindID(), LLVMHalfType(), LLVMInsertBasicBlock(), LLVMInt128Type(), LLVMInt16Type(), LLVMInt1Type(), LLVMInt32Type(), LLVMInt64Type(), LLVMInt8Type(), LLVMIntType(), LLVMLabelType(), LLVMMDNode(), LLVMMDString(), LLVMPPCFP128Type(), LLVMStructType(), LLVMVoidType(), LLVMX86FP80Type(), and LLVMX86MMXType().
LLVMGetGlobalIFuncResolver()
LLVMValueRef LLVMGetGlobalIFuncResolver (LLVMValueRef IFunc)
Definition at line 2544 of file Core.cpp.
References llvm::wrap().
LLVMGetGlobalParent()
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
Definition at line 1820 of file Core.cpp.
References getParent(), and llvm::wrap().
LLVMGetGlobalPassRegistry()
LLVMPassRegistryRef LLVMGetGlobalPassRegistry (void)
Definition at line 4002 of file Core.cpp.
References llvm::wrap().
LLVMGetHandlers()
void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef * Handlers)
Definition at line 3230 of file Core.cpp.
References llvm::CatchSwitchInst::handler_begin(), llvm::CatchSwitchInst::handler_end(), I, and llvm::wrap().
LLVMGetICmpPredicate()
LLVMIntPredicate LLVMGetICmpPredicate (LLVMValueRef Inst)
Definition at line 2735 of file Core.cpp.
References I, and llvm::unwrap().
LLVMGetIncomingBlock()
LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
Definition at line 2951 of file Core.cpp.
References llvm::wrap().
LLVMGetIncomingValue()
LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
Definition at line 2947 of file Core.cpp.
References llvm::wrap().
LLVMGetIndices()
const unsigned * LLVMGetIndices (LLVMValueRef Inst)
Definition at line 2971 of file Core.cpp.
References I, llvm_unreachable, and llvm::unwrap().
LLVMGetInitializer()
LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
Definition at line 2122 of file Core.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasInitializer(), and llvm::wrap().
LLVMGetInlineAsm()
LLVMValueRef LLVMGetInlineAsm (LLVMTypeRef Ty, char * AsmString, size_t AsmStringSize, char * Constraints, size_t ConstraintsSize, LLVMBool HasSideEffects, LLVMBool IsAlignStack, LLVMInlineAsmDialect Dialect)
Definition at line 446 of file Core.cpp.
References llvm::InlineAsm::AD_ATT, llvm::InlineAsm::AD_Intel, llvm::InlineAsm::get(), and llvm::wrap().
LLVMGetInsertBlock()
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
Definition at line 3011 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetInstructionCallConv()
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
Definition at line 2779 of file Core.cpp.
LLVMGetInstructionOpcode()
LLVMOpcode LLVMGetInstructionOpcode (LLVMValueRef Inst)
Definition at line 2753 of file Core.cpp.
References map_to_llvmopcode(), and llvm::unwrap().
LLVMGetInstructionParent()
LLVMBasicBlockRef LLVMGetInstructionParent (LLVMValueRef Inst)
Definition at line 2691 of file Core.cpp.
References getParent(), and llvm::wrap().
LLVMGetIntrinsicDeclaration()
LLVMValueRef LLVMGetIntrinsicDeclaration (LLVMModuleRef Mod, unsigned ID, LLVMTypeRef * ParamTypes, size_t ParamCount)
Definition at line 2323 of file Core.cpp.
References llvm::Intrinsic::getDeclaration(), llvm_map_to_intrinsic_id(), llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetIntrinsicID()
unsigned LLVMGetIntrinsicID (LLVMValueRef Fn)
Definition at line 2312 of file Core.cpp.
References F, and llvm::unwrap().
LLVMGetIntTypeWidth()
unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
Definition at line 590 of file Core.cpp.
LLVMGetLastBasicBlock()
LLVMBasicBlockRef LLVMGetLastBasicBlock (LLVMValueRef Fn)
Definition at line 2608 of file Core.cpp.
References llvm::Function::begin(), llvm::Function::end(), I, and llvm::wrap().
LLVMGetLastEnumAttributeKind()
unsigned LLVMGetLastEnumAttributeKind (void)
Definition at line 137 of file Core.cpp.
LLVMGetLastFunction()
LLVMValueRef LLVMGetLastFunction (LLVMModuleRef M)
Definition at line 2272 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobal()
LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
Definition at line 2094 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobalAlias()
LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
Definition at line 2220 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobalIFunc()
LLVMValueRef LLVMGetLastGlobalIFunc (LLVMModuleRef M)
Definition at line 2520 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastInstruction()
LLVMValueRef LLVMGetLastInstruction (LLVMBasicBlockRef BB)
Definition at line 2703 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMGetLastNamedMetadata()
LLVMNamedMDNodeRef LLVMGetLastNamedMetadata (LLVMModuleRef M)
Definition at line 1138 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastParam()
LLVMValueRef LLVMGetLastParam (LLVMValueRef Fn)
Definition at line 2467 of file Core.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), I, and llvm::wrap().
LLVMGetLinkage()
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
Definition at line 1828 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMGetMDKindID()
unsigned LLVMGetMDKindID (const char * Name, unsigned SLen)
Definition at line 126 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMGetMDKindIDInContext().
LLVMGetMDKindIDInContext()
unsigned LLVMGetMDKindIDInContext (LLVMContextRef C, const char * Name, unsigned SLen)
Definition at line 121 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetMDKindID().
LLVMGetMDNodeNumOperands()
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Definition at line 1123 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetNumOperands().
LLVMGetMDNodeOperands()
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef * Dest)
Definition at line 1178 of file Core.cpp.
References getMDNodeOperandImpl(), N, llvm::unwrap(), and llvm::wrap().
LLVMGetMDString()
const char * LLVMGetMDString (LLVMValueRef V, unsigned * Length)
Definition at line 1113 of file Core.cpp.
References llvm::unwrap().
LLVMGetMetadata()
LLVMValueRef LLVMGetMetadata (LLVMValueRef Inst, unsigned KindID)
Definition at line 863 of file Core.cpp.
References assert(), llvm::MetadataAsValue::get(), I, and llvm::wrap().
LLVMGetModuleContext()
LLVMContextRef LLVMGetModuleContext (LLVMModuleRef M)
Definition at line 468 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetModuleFlag()
LLVMMetadataRef LLVMGetModuleFlag (LLVMModuleRef M, const char * Key, size_t KeyLen)
Definition at line 376 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetModuleIdentifier()
const char * LLVMGetModuleIdentifier (LLVMModuleRef M, size_t * Len)
Definition at line 243 of file Core.cpp.
References llvm::unwrap().
LLVMGetModuleInlineAsm()
const char * LLVMGetModuleInlineAsm (LLVMModuleRef M, size_t * Len)
Definition at line 440 of file Core.cpp.
References llvm::unwrap().
LLVMGetNamedFunction()
LLVMValueRef LLVMGetNamedFunction (LLVMModuleRef M, const char * Name)
Definition at line 2260 of file Core.cpp.
References getFunction(), llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobal()
LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char * Name)
Definition at line 2082 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobalAlias()
LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char * Name, size_t NameLen)
Definition at line 2207 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobalIFunc()
LLVMValueRef LLVMGetNamedGlobalIFunc (LLVMModuleRef M, const char * Name, size_t NameLen)
Definition at line 2507 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedMetadata()
LLVMNamedMDNodeRef LLVMGetNamedMetadata (LLVMModuleRef M, const char * Name, size_t NameLen)
Definition at line 1162 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedMetadataName()
const char * LLVMGetNamedMetadataName (LLVMNamedMDNodeRef NMD, size_t * NameLen)
Definition at line 1172 of file Core.cpp.
References llvm::NamedMDNode::getName().
LLVMGetNamedMetadataNumOperands()
unsigned LLVMGetNamedMetadataNumOperands (LLVMModuleRef M, const char * Name)
Definition at line 1191 of file Core.cpp.
References N, and llvm::unwrap().
LLVMGetNamedMetadataOperands()
void LLVMGetNamedMetadataOperands (LLVMModuleRef M, const char * Name, LLVMValueRef * Dest)
Definition at line 1198 of file Core.cpp.
References llvm::MetadataAsValue::get(), N, llvm::unwrap(), and llvm::wrap().
LLVMGetNextBasicBlock()
LLVMBasicBlockRef LLVMGetNextBasicBlock (LLVMBasicBlockRef BB)
Definition at line 2616 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMGetNextFunction()
LLVMValueRef LLVMGetNextFunction (LLVMValueRef Fn)
Definition at line 2280 of file Core.cpp.
References llvm::Module::end(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetNextGlobal()
LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
Definition at line 2102 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_end(), I, and llvm::wrap().
LLVMGetNextGlobalAlias()
LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
Definition at line 2228 of file Core.cpp.
References llvm::Module::alias_end(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetNextGlobalIFunc()
LLVMValueRef LLVMGetNextGlobalIFunc (LLVMValueRef IFunc)
Definition at line 2528 of file Core.cpp.
References llvm::GlobalValue::getParent(), I, llvm::Module::ifunc_end(), and llvm::wrap().
LLVMGetNextInstruction()
LLVMValueRef LLVMGetNextInstruction (LLVMValueRef Inst)
Definition at line 2711 of file Core.cpp.
References llvm::BasicBlock::end(), llvm::Instruction::getParent(), I, and llvm::wrap().
LLVMGetNextNamedMetadata()
LLVMNamedMDNodeRef LLVMGetNextNamedMetadata (LLVMNamedMDNodeRef NMD)
Definition at line 1146 of file Core.cpp.
References llvm::NamedMDNode::getParent(), I, llvm::Module::named_metadata_end(), and llvm::wrap().
LLVMGetNextParam()
LLVMValueRef LLVMGetNextParam (LLVMValueRef Arg)
Definition at line 2475 of file Core.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_size(), and llvm::wrap().
LLVMGetNextUse()
LLVMUseRef LLVMGetNextUse (LLVMUseRef U)
Definition at line 956 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNormalDest()
LLVMBasicBlockRef LLVMGetNormalDest (LLVMValueRef Invoke)
Definition at line 2858 of file Core.cpp.
References llvm::wrap().
LLVMGetNumArgOperands()
unsigned LLVMGetNumArgOperands (LLVMValueRef Instr)
Definition at line 2770 of file Core.cpp.
References llvm::unwrap().
LLVMGetNumClauses()
unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
Definition at line 3201 of file Core.cpp.
LLVMGetNumContainedTypes()
unsigned LLVMGetNumContainedTypes (LLVMTypeRef Tp)
Definition at line 762 of file Core.cpp.
References llvm::unwrap().
LLVMGetNumHandlers()
unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
Definition at line 3226 of file Core.cpp.
LLVMGetNumIndices()
unsigned LLVMGetNumIndices (LLVMValueRef Inst)
Definition at line 2957 of file Core.cpp.
References I, llvm_unreachable, and llvm::unwrap().
LLVMGetNumOperands()
int LLVMGetNumOperands (LLVMValueRef Val)
Definition at line 1006 of file Core.cpp.
References LLVMGetMDNodeNumOperands(), and llvm::unwrap().
LLVMGetNumSuccessors()
unsigned LLVMGetNumSuccessors (LLVMValueRef Term)
Definition at line 2886 of file Core.cpp.
LLVMGetOperand()
LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
Definition at line 983 of file Core.cpp.
References assert(), llvm::Value::getContext(), getMDNodeOperandImpl(), llvm::unwrap(), and llvm::wrap().
LLVMGetOperandUse()
LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
Definition at line 997 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetOrdering()
LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemAccessInst)
Definition at line 3615 of file Core.cpp.
References mapToLLVMOrdering(), and P.
LLVMGetOrInsertNamedMetadata()
LLVMNamedMDNodeRef LLVMGetOrInsertNamedMetadata (LLVMModuleRef M, const char * Name, size_t NameLen)
Definition at line 1167 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetParam()
LLVMValueRef LLVMGetParam (LLVMValueRef FnRef, unsigned index)
Definition at line 2450 of file Core.cpp.
References llvm::Function::arg_begin(), and llvm::wrap().
LLVMGetParamParent()
LLVMValueRef LLVMGetParamParent (LLVMValueRef V)
Definition at line 2455 of file Core.cpp.
References getParent(), and llvm::wrap().
LLVMGetParams()
void LLVMGetParams (LLVMValueRef FnRef, LLVMValueRef * ParamRefs)
Definition at line 2443 of file Core.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), I, and llvm::wrap().
LLVMGetParamTypes()
void LLVMGetParamTypes (LLVMTypeRef FunctionTy, LLVMTypeRef * Dest)
Definition at line 661 of file Core.cpp.
References I, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), and llvm::wrap().
LLVMGetParentCatchSwitch()
LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
Definition at line 3237 of file Core.cpp.
References llvm::wrap().
LLVMGetPersonalityFn()
LLVMValueRef LLVMGetPersonalityFn (LLVMValueRef Fn)
Definition at line 2304 of file Core.cpp.
References llvm::wrap().
LLVMGetPointerAddressSpace()
unsigned LLVMGetPointerAddressSpace (LLVMTypeRef PointerTy)
Definition at line 770 of file Core.cpp.
LLVMGetPreviousBasicBlock()
LLVMBasicBlockRef LLVMGetPreviousBasicBlock (LLVMBasicBlockRef BB)
Definition at line 2624 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMGetPreviousFunction()
LLVMValueRef LLVMGetPreviousFunction (LLVMValueRef Fn)
Definition at line 2288 of file Core.cpp.
References llvm::Module::begin(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetPreviousGlobal()
LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
Definition at line 2110 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_begin(), I, and llvm::wrap().
LLVMGetPreviousGlobalAlias()
LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
Definition at line 2236 of file Core.cpp.
References llvm::Module::alias_begin(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetPreviousGlobalIFunc()
LLVMValueRef LLVMGetPreviousGlobalIFunc (LLVMValueRef IFunc)
Definition at line 2536 of file Core.cpp.
References llvm::GlobalValue::getParent(), I, llvm::Module::ifunc_begin(), and llvm::wrap().
LLVMGetPreviousInstruction()
LLVMValueRef LLVMGetPreviousInstruction (LLVMValueRef Inst)
Definition at line 2719 of file Core.cpp.
References llvm::BasicBlock::begin(), llvm::Instruction::getParent(), I, and llvm::wrap().
LLVMGetPreviousNamedMetadata()
LLVMNamedMDNodeRef LLVMGetPreviousNamedMetadata (LLVMNamedMDNodeRef NMD)
Definition at line 1154 of file Core.cpp.
References llvm::NamedMDNode::getParent(), I, llvm::Module::named_metadata_begin(), and llvm::wrap().
LLVMGetPreviousParam()
LLVMValueRef LLVMGetPreviousParam (LLVMValueRef Arg)
Definition at line 2483 of file Core.cpp.
References llvm::wrap().
LLVMGetReturnType()
LLVMTypeRef LLVMGetReturnType (LLVMTypeRef FunctionTy)
Definition at line 653 of file Core.cpp.
References llvm::wrap().
LLVMGetSection()
const char * LLVMGetSection (LLVMValueRef Global)
Definition at line 1922 of file Core.cpp.
LLVMGetSourceFileName()
const char * LLVMGetSourceFileName (LLVMModuleRef M, size_t * Len)
Definition at line 253 of file Core.cpp.
References llvm::unwrap().
LLVMGetStringAttributeAtIndex()
LLVMAttributeRef LLVMGetStringAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2412 of file Core.cpp.
References F, Idx, and llvm::wrap().
LLVMGetStringAttributeKind()
const char * LLVMGetStringAttributeKind (LLVMAttributeRef A, unsigned * Length)
Definition at line 173 of file Core.cpp.
References llvm::Attribute::getKindAsString(), and llvm::unwrap().
LLVMGetStringAttributeValue()
const char * LLVMGetStringAttributeValue (LLVMAttributeRef A, unsigned * Length)
Definition at line 180 of file Core.cpp.
References llvm::Attribute::getValueAsString(), and llvm::unwrap().
LLVMGetStructElementTypes()
void LLVMGetStructElementTypes (LLVMTypeRef StructTy, LLVMTypeRef * Dest)
Definition at line 705 of file Core.cpp.
References llvm::StructType::element_begin(), llvm::StructType::element_end(), I, and llvm::wrap().
LLVMGetStructName()
const char * LLVMGetStructName (LLVMTypeRef Ty)
Definition at line 687 of file Core.cpp.
LLVMGetSubtypes()
void LLVMGetSubtypes (LLVMTypeRef Tp, LLVMTypeRef * Arr)
Definition at line 735 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetSuccessor()
LLVMBasicBlockRef LLVMGetSuccessor (LLVMValueRef Term, unsigned i)
Definition at line 2890 of file Core.cpp.
References llvm::wrap().
LLVMGetSwitchDefaultDest()
LLVMBasicBlockRef LLVMGetSwitchDefaultDest (LLVMValueRef Switch)
Definition at line 2914 of file Core.cpp.
References llvm::wrap().
LLVMGetTarget()
const char * LLVMGetTarget (LLVMModuleRef M)
Definition at line 277 of file Core.cpp.
References llvm::unwrap().
LLVMGetThreadLocalMode()
LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
Definition at line 2150 of file Core.cpp.
References llvm_unreachable.
LLVMGetTypeByName()
LLVMTypeRef LLVMGetTypeByName (LLVMModuleRef M, const char * Name)
Definition at line 729 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetTypeContext()
LLVMContextRef LLVMGetTypeContext (LLVMTypeRef Ty)
Definition at line 522 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetTypeKind()
LLVMTypeKind LLVMGetTypeKind (LLVMTypeRef Ty)
Definition at line 477 of file Core.cpp.
References llvm::Type::ArrayTyID, llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::Type::FunctionTyID, llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm::Type::LabelTyID, llvm_unreachable, llvm::Type::MetadataTyID, llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, llvm::Type::StructTyID, llvm::Type::TokenTyID, llvm::unwrap(), llvm::Type::VectorTyID, llvm::Type::VoidTyID, llvm::Type::X86_FP80TyID, and llvm::Type::X86_MMXTyID.
LLVMGetUndef()
LLVMValueRef LLVMGetUndef (LLVMTypeRef Ty)
Definition at line 1024 of file Core.cpp.
References llvm::UndefValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetUnnamedAddress()
LLVMUnnamedAddr LLVMGetUnnamedAddress (LLVMValueRef Global)
Definition at line 1952 of file Core.cpp.
References llvm_unreachable.
LLVMGetUnwindDest()
LLVMBasicBlockRef LLVMGetUnwindDest (LLVMValueRef Invoke)
Definition at line 2862 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetUsedValue()
LLVMValueRef LLVMGetUsedValue (LLVMUseRef U)
Definition at line 967 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetUser()
LLVMValueRef LLVMGetUser (LLVMUseRef U)
Definition at line 963 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetValueKind()
LLVMValueKind LLVMGetValueKind (LLVMValueRef Val)
Definition at line 808 of file Core.cpp.
References llvm::unwrap().
LLVMGetValueName()
const char * LLVMGetValueName (LLVMValueRef Val)
Definition at line 829 of file Core.cpp.
References llvm::unwrap().
LLVMGetValueName2()
const char * LLVMGetValueName2 (LLVMValueRef Val, size_t * Length)
Definition at line 819 of file Core.cpp.
References llvm::unwrap().
LLVMGetVectorSize()
unsigned LLVMGetVectorSize (LLVMTypeRef VectorTy)
Definition at line 774 of file Core.cpp.
LLVMGetVisibility()
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
Definition at line 1932 of file Core.cpp.
LLVMGetVolatile()
LLVMBool LLVMGetVolatile (LLVMValueRef MemAccessInst)
Definition at line 3601 of file Core.cpp.
References P.
LLVMGlobalClearMetadata()
void LLVMGlobalClearMetadata (LLVMValueRef Global)
Definition at line 2062 of file Core.cpp.
LLVMGlobalCopyAllMetadata()
LLVMValueMetadataEntry * LLVMGlobalCopyAllMetadata (LLVMValueRef Value, size_t * NumEntries)
Definition at line 2023 of file Core.cpp.
References llvm_getMetadata(), and llvm::unwrap().
LLVMGlobalEraseMetadata()
void LLVMGlobalEraseMetadata (LLVMValueRef Global, unsigned Kind)
Definition at line 2058 of file Core.cpp.
LLVMGlobalGetValueType()
LLVMTypeRef LLVMGlobalGetValueType (LLVMValueRef Global)
Definition at line 1987 of file Core.cpp.
References llvm::wrap().
LLVMGlobalSetMetadata()
void LLVMGlobalSetMetadata (LLVMValueRef Global, unsigned Kind, LLVMMetadataRef MD)
Definition at line 2053 of file Core.cpp.
LLVMHalfType()
LLVMTypeRef LLVMHalfType (void)
Definition at line 618 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMHalfTypeInContext().
LLVMHalfTypeInContext()
LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
Definition at line 596 of file Core.cpp.
References llvm::IRBuilderBase::getHalfTy(), and llvm::unwrap().
Referenced by LLVMHalfType().
LLVMHasMetadata()
int LLVMHasMetadata (LLVMValueRef Inst)
Definition at line 859 of file Core.cpp.
LLVMHasPersonalityFn()
LLVMBool LLVMHasPersonalityFn (LLVMValueRef Fn)
Definition at line 2300 of file Core.cpp.
LLVMHasUnnamedAddr()
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
Definition at line 1977 of file Core.cpp.
LLVMInitializeCore()
void LLVMInitializeCore (LLVMPassRegistryRef R)
Definition at line 55 of file Core.cpp.
References llvm::unwrap().
LLVMInitializeFunctionPassManager()
LLVMBool LLVMInitializeFunctionPassManager (LLVMPassManagerRef FPM)
Definition at line 4025 of file Core.cpp.
LLVMInsertBasicBlock()
LLVMBasicBlockRef LLVMInsertBasicBlock (LLVMBasicBlockRef BBRef, const char * Name)
Definition at line 2668 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInsertBasicBlockInContext().
LLVMInsertBasicBlockInContext()
LLVMBasicBlockRef LLVMInsertBasicBlockInContext (LLVMContextRef C, LLVMBasicBlockRef BBRef, const char * Name)
Definition at line 2661 of file Core.cpp.
References llvm::BasicBlock::Create(), llvm::BasicBlock::getParent(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMInsertBasicBlock().
LLVMInsertExistingBasicBlockAfterInsertBlock()
void LLVMInsertExistingBasicBlockAfterInsertBlock (LLVMBuilderRef Builder, LLVMBasicBlockRef BB)
Definition at line 2637 of file Core.cpp.
References assert(), llvm::Function::getBasicBlockList(), llvm::BasicBlock::getParent(), and llvm::unwrap().
LLVMInsertIntoBuilder()
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 3019 of file Core.cpp.
References llvm::unwrap().
LLVMInsertIntoBuilderWithName()
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char * Name)
Definition at line 3023 of file Core.cpp.
References llvm::unwrap().
LLVMInstructionClone()
LLVMValueRef LLVMInstructionClone (LLVMValueRef Inst)
Definition at line 2759 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMInstructionEraseFromParent()
void LLVMInstructionEraseFromParent (LLVMValueRef Inst)
Definition at line 2731 of file Core.cpp.
LLVMInstructionGetAllMetadataOtherThanDebugLoc()
LLVMValueMetadataEntry * LLVMInstructionGetAllMetadataOtherThanDebugLoc (LLVMValueRef Value, size_t * NumEntries)
Definition at line 916 of file Core.cpp.
References llvm_getMetadata().
LLVMInstructionRemoveFromParent()
void LLVMInstructionRemoveFromParent (LLVMValueRef Inst)
Definition at line 2727 of file Core.cpp.
LLVMInt128Type()
LLVMTypeRef LLVMInt128Type (void)
Definition at line 583 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt128TypeInContext().
LLVMInt128TypeInContext()
LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
Definition at line 561 of file Core.cpp.
References llvm::IRBuilderBase::getInt128Ty(), and llvm::unwrap().
Referenced by LLVMInt128Type().
LLVMInt16Type()
LLVMTypeRef LLVMInt16Type (void)
Definition at line 574 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt16TypeInContext().
LLVMInt16TypeInContext()
LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
Definition at line 552 of file Core.cpp.
References llvm::IRBuilderBase::getInt16Ty(), and llvm::unwrap().
Referenced by LLVMInt16Type().
LLVMInt1Type()
LLVMTypeRef LLVMInt1Type (void)
Definition at line 568 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt1TypeInContext().
LLVMInt1TypeInContext()
LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
Definition at line 546 of file Core.cpp.
References llvm::IRBuilderBase::getInt1Ty(), and llvm::unwrap().
Referenced by LLVMInt1Type().
LLVMInt32Type()
LLVMTypeRef LLVMInt32Type (void)
Definition at line 577 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt32TypeInContext().
LLVMInt32TypeInContext()
LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
Definition at line 555 of file Core.cpp.
References llvm::IRBuilderBase::getInt32Ty(), and llvm::unwrap().
Referenced by LLVMInt32Type().
LLVMInt64Type()
LLVMTypeRef LLVMInt64Type (void)
Definition at line 580 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt64TypeInContext().
LLVMInt64TypeInContext()
LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
Definition at line 558 of file Core.cpp.
References llvm::IRBuilderBase::getInt64Ty(), and llvm::unwrap().
Referenced by LLVMInt64Type().
LLVMInt8Type()
LLVMTypeRef LLVMInt8Type (void)
Definition at line 571 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMInt8TypeInContext().
LLVMInt8TypeInContext()
LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
Definition at line 549 of file Core.cpp.
References llvm::IRBuilderBase::getInt8Ty(), and llvm::unwrap().
Referenced by LLVMInt8Type().
LLVMIntrinsicCopyOverloadedName()
const char * LLVMIntrinsicCopyOverloadedName (unsigned ID, LLVMTypeRef * ParamTypes, size_t ParamCount, size_t * NameLength)
Definition at line 2346 of file Core.cpp.
References llvm::Intrinsic::getName(), llvm_map_to_intrinsic_id(), and llvm::unwrap().
LLVMIntrinsicGetName()
const char * LLVMIntrinsicGetName (unsigned ID, size_t * NameLength)
Definition at line 2332 of file Core.cpp.
References llvm::Intrinsic::getName(), and llvm_map_to_intrinsic_id().
LLVMIntrinsicGetType()
LLVMTypeRef LLVMIntrinsicGetType (LLVMContextRef Ctx, unsigned ID, LLVMTypeRef * ParamTypes, size_t ParamCount)
Definition at line 2339 of file Core.cpp.
References llvm::Intrinsic::getType(), llvm_map_to_intrinsic_id(), llvm::unwrap(), and llvm::wrap().
LLVMIntrinsicIsOverloaded()
LLVMBool LLVMIntrinsicIsOverloaded (unsigned ID)
Definition at line 2361 of file Core.cpp.
References llvm::Intrinsic::isOverloaded(), and llvm_map_to_intrinsic_id().
LLVMIntType()
LLVMTypeRef LLVMIntType (unsigned NumBits)
Definition at line 586 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMIntTypeInContext().
LLVMIntTypeInContext()
LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
Definition at line 564 of file Core.cpp.
References llvm::IntegerType::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMIntType().
LLVMIsAMDNode()
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
Definition at line 932 of file Core.cpp.
References llvm::unwrap().
LLVMIsAMDString()
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
Definition at line 940 of file Core.cpp.
References llvm::unwrap().
LLVMIsATerminatorInst()
LLVMValueRef LLVMIsATerminatorInst (LLVMValueRef Inst)
Definition at line 2765 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMIsAtomicSingleThread()
LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
Definition at line 3884 of file Core.cpp.
References I, P, and llvm::SyncScope::SingleThread.
LLVMIsCleanup()
LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
Definition at line 3214 of file Core.cpp.
LLVMIsConditional()
LLVMBool LLVMIsConditional (LLVMValueRef Branch)
Definition at line 2900 of file Core.cpp.
LLVMIsConstant()
LLVMBool LLVMIsConstant (LLVMValueRef Ty)
Definition at line 1028 of file Core.cpp.
References llvm::unwrap().
LLVMIsConstantString()
LLVMBool LLVMIsConstantString (LLVMValueRef C)
Definition at line 1387 of file Core.cpp.
LLVMIsDeclaration()
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
Definition at line 1824 of file Core.cpp.
LLVMIsEnumAttribute()
LLVMBool LLVMIsEnumAttribute (LLVMAttributeRef A)
Definition at line 187 of file Core.cpp.
References llvm::unwrap().
LLVMIsExternallyInitialized()
LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
Definition at line 2189 of file Core.cpp.
LLVMIsFunctionVarArg()
LLVMBool LLVMIsFunctionVarArg (LLVMTypeRef FunctionTy)
Definition at line 649 of file Core.cpp.
LLVMIsGlobalConstant()
LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
Definition at line 2142 of file Core.cpp.
LLVMIsInBounds()
LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
Definition at line 2926 of file Core.cpp.
LLVMIsLiteralStruct()
LLVMBool LLVMIsLiteralStruct (LLVMTypeRef StructTy)
Definition at line 725 of file Core.cpp.
LLVMIsMultithreaded()
LLVMBool LLVMIsMultithreaded ()
Definition at line 4050 of file Core.cpp.
References llvm::llvm_is_multithreaded().
Referenced by LLVMStartMultithreaded().
LLVMIsNull()
LLVMBool LLVMIsNull (LLVMValueRef Val)
Definition at line 1032 of file Core.cpp.
References llvm::unwrap().
LLVMIsOpaqueStruct()
LLVMBool LLVMIsOpaqueStruct (LLVMTypeRef StructTy)
Definition at line 721 of file Core.cpp.
LLVMIsPackedStruct()
LLVMBool LLVMIsPackedStruct (LLVMTypeRef StructTy)
Definition at line 717 of file Core.cpp.
LLVMIsStringAttribute()
LLVMBool LLVMIsStringAttribute (LLVMAttributeRef A)
Definition at line 192 of file Core.cpp.
References llvm::Attribute::isStringAttribute(), and llvm::unwrap().
LLVMIsTailCall()
LLVMBool LLVMIsTailCall (LLVMValueRef Call)
Definition at line 2848 of file Core.cpp.
LLVMIsThreadLocal()
LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
Definition at line 2134 of file Core.cpp.
LLVMIsUndef()
LLVMBool LLVMIsUndef (LLVMValueRef Val)
Definition at line 1038 of file Core.cpp.
References llvm::unwrap().
LLVMLabelType()
LLVMTypeRef LLVMLabelType (void)
Definition at line 796 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMLabelTypeInContext().
LLVMLabelTypeInContext()
LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
Definition at line 783 of file Core.cpp.
References llvm::Type::getLabelTy(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMLabelType().
LLVMLookupIntrinsicID()
unsigned LLVMLookupIntrinsicID (const char * Name, size_t NameLen)
Definition at line 2357 of file Core.cpp.
References llvm::Function::lookupIntrinsicID().
LLVMMDNode()
LLVMValueRef LLVMMDNode (LLVMValueRef * Vals, unsigned Count)
Definition at line 1096 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDNodeInContext().
LLVMMDNodeInContext()
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef * Vals, unsigned Count)
Definition at line 1069 of file Core.cpp.
References assert(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MetadataAsValue::get(), llvm::LocalAsMetadata::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDNode().
LLVMMDNodeInContext2()
LLVMMetadataRef LLVMMDNodeInContext2 (LLVMContextRef C, LLVMMetadataRef * MDs, size_t Count)
Definition at line 1053 of file Core.cpp.
References llvm::MDNode::get(), llvm::unwrap(), and llvm::wrap().
LLVMMDString()
LLVMValueRef LLVMMDString (const char * Str, unsigned SLen)
Definition at line 1065 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDStringInContext().
LLVMMDStringInContext()
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char * Str, unsigned SLen)
Definition at line 1058 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::MDString::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDString().
LLVMMDStringInContext2()
LLVMMetadataRef LLVMMDStringInContext2 (LLVMContextRef C, const char * Str, size_t SLen)
Definition at line 1048 of file Core.cpp.
References llvm::MDString::get(), llvm::unwrap(), and llvm::wrap().
LLVMMetadataAsValue()
LLVMValueRef LLVMMetadataAsValue (LLVMContextRef C, LLVMMetadataRef MD)
Definition at line 1100 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMMetadataTypeInContext()
LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
Definition at line 789 of file Core.cpp.
References llvm::Type::getMetadataTy(), llvm::unwrap(), and llvm::wrap().
LLVMModuleCreateWithName()
LLVMModuleRef LLVMModuleCreateWithName (const char * ModuleID)
Definition at line 230 of file Core.cpp.
References GlobalContext, and llvm::wrap().
LLVMModuleCreateWithNameInContext()
LLVMModuleRef LLVMModuleCreateWithNameInContext (const char * ModuleID, LLVMContextRef C)
Definition at line 234 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMModuleFlagEntriesGetFlagBehavior()
LLVMModuleFlagBehavior LLVMModuleFlagEntriesGetFlagBehavior (LLVMModuleFlagEntry * Entries, unsigned Index)
Definition at line 354 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Behavior.
LLVMModuleFlagEntriesGetKey()
const char * LLVMModuleFlagEntriesGetKey (LLVMModuleFlagEntry * Entries, unsigned Index, size_t * Len)
Definition at line 361 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Key, and LLVMOpaqueModuleFlagEntry::KeyLen.
LLVMModuleFlagEntriesGetMetadata()
LLVMMetadataRef LLVMModuleFlagEntriesGetMetadata (LLVMModuleFlagEntry * Entries, unsigned Index)
Definition at line 369 of file Core.cpp.
References LLVMOpaqueModuleFlagEntry::Metadata.
LLVMMoveBasicBlockAfter()
void LLVMMoveBasicBlockAfter (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
Definition at line 2685 of file Core.cpp.
References llvm::unwrap().
LLVMMoveBasicBlockBefore()
void LLVMMoveBasicBlockBefore (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
Definition at line 2681 of file Core.cpp.
References llvm::unwrap().
LLVMPointerType()
LLVMTypeRef LLVMPointerType (LLVMTypeRef ElementType, unsigned AddressSpace)
Definition at line 747 of file Core.cpp.
References llvm::PointerType::get(), llvm::unwrap(), and llvm::wrap().
LLVMPositionBuilder()
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
Definition at line 2994 of file Core.cpp.
References llvm::BasicBlock::end(), I, and llvm::unwrap().
LLVMPositionBuilderAtEnd()
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
Definition at line 3006 of file Core.cpp.
References llvm::unwrap().
LLVMPositionBuilderBefore()
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 3001 of file Core.cpp.
References I, and llvm::unwrap().
LLVMPPCFP128Type()
LLVMTypeRef LLVMPPCFP128Type (void)
Definition at line 633 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMPPCFP128TypeInContext().
LLVMPPCFP128TypeInContext()
LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
Definition at line 611 of file Core.cpp.
References llvm::Type::getPPC_FP128Ty(), and llvm::unwrap().
Referenced by LLVMPPCFP128Type().
LLVMPrintModuleToFile()
LLVMBool LLVMPrintModuleToFile (LLVMModuleRef M, const char * Filename, char ** ErrorMessage)
Definition at line 395 of file Core.cpp.
References llvm::raw_fd_ostream::close(), llvm::raw_fd_ostream::error(), llvm::sys::fs::F_Text, llvm::raw_fd_ostream::has_error(), and llvm::unwrap().
LLVMPrintModuleToString()
char * LLVMPrintModuleToString (LLVMModuleRef M)
Definition at line 417 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMPrintTypeToString()
char * LLVMPrintTypeToString (LLVMTypeRef Ty)
Definition at line 530 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMPrintValueToString()
char * LLVMPrintValueToString (LLVMValueRef Val)
Definition at line 841 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMRemoveBasicBlockFromParent()
void LLVMRemoveBasicBlockFromParent (LLVMBasicBlockRef BBRef)
Definition at line 2677 of file Core.cpp.
References llvm::unwrap().
LLVMRemoveCallSiteEnumAttribute()
void LLVMRemoveCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2828 of file Core.cpp.
References Idx.
LLVMRemoveCallSiteStringAttribute()
void LLVMRemoveCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2833 of file Core.cpp.
References Idx.
LLVMRemoveEnumAttributeAtIndex()
void LLVMRemoveEnumAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2418 of file Core.cpp.
References F, and Idx.
LLVMRemoveGlobalIFunc()
void LLVMRemoveGlobalIFunc (LLVMValueRef IFunc)
Definition at line 2556 of file Core.cpp.
LLVMRemoveStringAttributeAtIndex()
void LLVMRemoveStringAttributeAtIndex (LLVMValueRef F, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2423 of file Core.cpp.
References F, and Idx.
LLVMReplaceAllUsesWith()
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
Definition at line 855 of file Core.cpp.
References llvm::unwrap().
LLVMRunFunctionPassManager()
LLVMBool LLVMRunFunctionPassManager (LLVMPassManagerRef FPM, LLVMValueRef F)
Definition at line 4029 of file Core.cpp.
References F.
LLVMRunPassManager()
LLVMBool LLVMRunPassManager (LLVMPassManagerRef PM, LLVMModuleRef M)
Definition at line 4021 of file Core.cpp.
References llvm::unwrap().
LLVMSetAlignment()
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
Definition at line 2008 of file Core.cpp.
References llvm_unreachable, and P.
LLVMSetArgOperand()
void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
Definition at line 3252 of file Core.cpp.
References llvm::unwrap(), and value.
LLVMSetAtomicSingleThread()
void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool NewValue)
Definition at line 3893 of file Core.cpp.
References I, P, llvm::SyncScope::SingleThread, and llvm::SyncScope::System.
LLVMSetCleanup()
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
Definition at line 3218 of file Core.cpp.
LLVMSetCmpXchgFailureOrdering()
void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 3920 of file Core.cpp.
References mapFromLLVMOrdering(), and P.
LLVMSetCmpXchgSuccessOrdering()
void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 3907 of file Core.cpp.
References mapFromLLVMOrdering(), and P.
LLVMSetCondition()
void LLVMSetCondition (LLVMValueRef Branch, LLVMValueRef Cond)
Definition at line 2908 of file Core.cpp.
References llvm::unwrap().
LLVMSetCurrentDebugLocation()
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Definition at line 3045 of file Core.cpp.
References llvm::unwrap().
LLVMSetCurrentDebugLocation2()
void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
Definition at line 3038 of file Core.cpp.
References llvm::unwrap().
LLVMSetDataLayout()
void LLVMSetDataLayout (LLVMModuleRef M, const char * DataLayoutStr)
Definition at line 272 of file Core.cpp.
References llvm::unwrap().
LLVMSetDLLStorageClass()
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
Definition at line 1947 of file Core.cpp.
LLVMSetExternallyInitialized()
void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
Definition at line 2193 of file Core.cpp.
LLVMSetFunctionCallConv()
void LLVMSetFunctionCallConv (LLVMValueRef Fn, unsigned CC)
Definition at line 2370 of file Core.cpp.
LLVMSetGC()
void LLVMSetGC (LLVMValueRef Fn, const char * GC)
Definition at line 2380 of file Core.cpp.
References F.
LLVMSetGlobalConstant()
void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
Definition at line 2146 of file Core.cpp.
LLVMSetGlobalIFuncResolver()
void LLVMSetGlobalIFuncResolver (LLVMValueRef IFunc, LLVMValueRef Resolver)
Definition at line 2548 of file Core.cpp.
LLVMSetInitializer()
void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
Definition at line 2129 of file Core.cpp.
LLVMSetInstDebugLocation()
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Definition at line 3057 of file Core.cpp.
References llvm::unwrap().
LLVMSetInstrParamAlignment()
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned align)
Definition at line 2788 of file Core.cpp.
References llvm::Attribute::getWithAlignment().
LLVMSetInstructionCallConv()
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
Definition at line 2783 of file Core.cpp.
LLVMSetIsInBounds()
void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
Definition at line 2930 of file Core.cpp.
LLVMSetLinkage()
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
Definition at line 1857 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::errs(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, LLVM_DEBUG, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::setLinkage(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMSetMetadata()
void LLVMSetMetadata (LLVMValueRef Inst, unsigned KindID, LLVMValueRef Val)
Definition at line 885 of file Core.cpp.
References extractMDNode(), and N.
LLVMSetModuleIdentifier()
void LLVMSetModuleIdentifier (LLVMModuleRef M, const char * Ident, size_t Len)
Definition at line 249 of file Core.cpp.
References llvm::unwrap().
LLVMSetModuleInlineAsm()
void LLVMSetModuleInlineAsm (LLVMModuleRef M, const char * Asm)
Definition at line 432 of file Core.cpp.
References llvm::unwrap().
LLVMSetModuleInlineAsm2()
void LLVMSetModuleInlineAsm2 (LLVMModuleRef M, const char * Asm, size_t Len)
Definition at line 428 of file Core.cpp.
References llvm::unwrap().
LLVMSetNormalDest()
void LLVMSetNormalDest (LLVMValueRef Invoke, LLVMBasicBlockRef B)
Definition at line 2871 of file Core.cpp.
References llvm::unwrap().
LLVMSetOperand()
void LLVMSetOperand (LLVMValueRef Val, unsigned Index, LLVMValueRef Op)
Definition at line 1002 of file Core.cpp.
References llvm::unwrap().
LLVMSetOrdering()
void LLVMSetOrdering (LLVMValueRef MemAccessInst, LLVMAtomicOrdering Ordering)
Definition at line 3625 of file Core.cpp.
References mapFromLLVMOrdering(), and P.
LLVMSetParamAlignment()
void LLVMSetParamAlignment (LLVMValueRef Arg, unsigned align)
Definition at line 2490 of file Core.cpp.
References llvm::Attribute::getWithAlignment().
LLVMSetParentCatchSwitch()
void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
Definition at line 3241 of file Core.cpp.
LLVMSetPersonalityFn()
void LLVMSetPersonalityFn (LLVMValueRef Fn, LLVMValueRef PersonalityFn)
Definition at line 2308 of file Core.cpp.
LLVMSetSection()
void LLVMSetSection (LLVMValueRef Global, const char * Section)
Definition at line 1928 of file Core.cpp.
LLVMSetSourceFileName()
void LLVMSetSourceFileName (LLVMModuleRef M, const char * Name, size_t Len)
Definition at line 259 of file Core.cpp.
References llvm::unwrap().
LLVMSetSuccessor()
void LLVMSetSuccessor (LLVMValueRef Term, unsigned i, LLVMBasicBlockRef block)
Definition at line 2894 of file Core.cpp.
References llvm::unwrap().
LLVMSetTailCall()
void LLVMSetTailCall (LLVMValueRef Call, LLVMBool isTailCall)
Definition at line 2852 of file Core.cpp.
LLVMSetTarget()
void LLVMSetTarget (LLVMModuleRef M, const char * Triple)
Definition at line 281 of file Core.cpp.
References llvm::unwrap().
LLVMSetThreadLocal()
void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
Definition at line 2138 of file Core.cpp.
LLVMSetThreadLocalMode()
void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
Definition at line 2167 of file Core.cpp.
References llvm::GlobalValue::setThreadLocalMode().
LLVMSetUnnamedAddr()
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
Definition at line 1981 of file Core.cpp.
LLVMSetUnnamedAddress()
void LLVMSetUnnamedAddress (LLVMValueRef Global, LLVMUnnamedAddr UnnamedAddr)
Definition at line 1964 of file Core.cpp.
References llvm::GlobalValue::setUnnamedAddr().
LLVMSetUnwindDest()
void LLVMSetUnwindDest (LLVMValueRef Invoke, LLVMBasicBlockRef B)
Definition at line 2875 of file Core.cpp.
References llvm::unwrap().
LLVMSetValueName()
void LLVMSetValueName (LLVMValueRef Val, const char * Name)
Definition at line 833 of file Core.cpp.
References llvm::unwrap().
LLVMSetValueName2()
void LLVMSetValueName2 (LLVMValueRef Val, const char * Name, size_t NameLen)
Definition at line 825 of file Core.cpp.
References llvm::unwrap().
LLVMSetVisibility()
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
Definition at line 1937 of file Core.cpp.
LLVMSetVolatile()
void LLVMSetVolatile (LLVMValueRef MemAccessInst, LLVMBool isVolatile)
Definition at line 3608 of file Core.cpp.
References isVolatile(), and P.
LLVMShutdown()
void LLVMShutdown ()
Definition at line 59 of file Core.cpp.
References llvm::llvm_shutdown().
LLVMSizeOf()
LLVMValueRef LLVMSizeOf (LLVMTypeRef Ty)
Definition at line 1463 of file Core.cpp.
References llvm::ConstantExpr::getSizeOf(), llvm::unwrap(), and llvm::wrap().
LLVMStartMultithreaded()
LLVMBool LLVMStartMultithreaded ()
Definition at line 4043 of file Core.cpp.
References LLVMIsMultithreaded().
LLVMStopMultithreaded()
void LLVMStopMultithreaded ()
Definition at line 4047 of file Core.cpp.
LLVMStructCreateNamed()
LLVMTypeRef LLVMStructCreateNamed (LLVMContextRef C, const char * Name)
Definition at line 682 of file Core.cpp.
References llvm::StructType::create(), llvm::unwrap(), and llvm::wrap().
LLVMStructGetTypeAtIndex()
LLVMTypeRef LLVMStructGetTypeAtIndex (LLVMTypeRef StructTy, unsigned i)
Definition at line 712 of file Core.cpp.
References llvm::CompositeType::getTypeAtIndex(), and llvm::wrap().
LLVMStructSetBody()
void LLVMStructSetBody (LLVMTypeRef StructTy, LLVMTypeRef * ElementTypes, unsigned ElementCount, LLVMBool Packed)
Definition at line 695 of file Core.cpp.
References llvm::unwrap().
LLVMStructType()
LLVMTypeRef LLVMStructType (LLVMTypeRef * ElementTypes, unsigned ElementCount, LLVMBool Packed)
Definition at line 676 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMStructTypeInContext().
LLVMStructTypeInContext()
LLVMTypeRef LLVMStructTypeInContext (LLVMContextRef C, LLVMTypeRef * ElementTypes, unsigned ElementCount, LLVMBool Packed)
Definition at line 670 of file Core.cpp.
References llvm::StructType::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMStructType().
LLVMTokenTypeInContext()
LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
Definition at line 786 of file Core.cpp.
References llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMTypeIsSized()
LLVMBool LLVMTypeIsSized (LLVMTypeRef Ty)
Definition at line 517 of file Core.cpp.
References llvm::unwrap().
LLVMTypeOf()
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
Definition at line 804 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMValueAsBasicBlock()
LLVMBasicBlockRef LLVMValueAsBasicBlock (LLVMValueRef Val)
Definition at line 2570 of file Core.cpp.
References llvm::wrap().
LLVMValueAsMetadata()
LLVMMetadataRef LLVMValueAsMetadata (LLVMValueRef Val)
Definition at line 1104 of file Core.cpp.
References llvm::ConstantAsMetadata::get(), llvm::ValueAsMetadata::get(), llvm::unwrap(), and llvm::wrap().
LLVMValueIsBasicBlock()
LLVMBool LLVMValueIsBasicBlock (LLVMValueRef Val)
Definition at line 2566 of file Core.cpp.
References llvm::unwrap().
LLVMValueMetadataEntriesGetKind()
unsigned LLVMValueMetadataEntriesGetKind (LLVMValueMetadataEntry * Entries, unsigned Index)
Definition at line 2034 of file Core.cpp.
References LLVMOpaqueValueMetadataEntry::Kind.
LLVMValueMetadataEntriesGetMetadata()
LLVMMetadataRef LLVMValueMetadataEntriesGetMetadata (LLVMValueMetadataEntry * Entries, unsigned Index)
Definition at line 2042 of file Core.cpp.
References LLVMOpaqueValueMetadataEntry::Metadata.
LLVMVectorType()
LLVMTypeRef LLVMVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
Definition at line 751 of file Core.cpp.
References llvm::VectorType::get(), llvm::unwrap(), and llvm::wrap().
LLVMVoidType()
LLVMTypeRef LLVMVoidType (void)
Definition at line 793 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMVoidTypeInContext().
LLVMVoidTypeInContext()
LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
Definition at line 780 of file Core.cpp.
References llvm::IRBuilderBase::getVoidTy(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMVoidType().
LLVMX86FP80Type()
LLVMTypeRef LLVMX86FP80Type (void)
Definition at line 627 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMX86FP80TypeInContext().
LLVMX86FP80TypeInContext()
LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
Definition at line 605 of file Core.cpp.
References llvm::Type::getX86_FP80Ty(), and llvm::unwrap().
Referenced by LLVMX86FP80Type().
LLVMX86MMXType()
LLVMTypeRef LLVMX86MMXType (void)
Definition at line 636 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMX86MMXTypeInContext().
LLVMX86MMXTypeInContext()
LLVMTypeRef LLVMX86MMXTypeInContext (LLVMContextRef C)
Definition at line 614 of file Core.cpp.
References llvm::Type::getX86_MMXTy(), and llvm::unwrap().
Referenced by LLVMX86MMXType().
map_from_llvmModFlagBehavior()
static LLVMModuleFlagBehavior map_from_llvmModFlagBehavior (Module::ModFlagBehavior Behavior) static
Definition at line 313 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMCopyModuleFlagsMetadata().
map_from_llvmopcode()
static int map_from_llvmopcode (LLVMOpcode code) static
Definition at line 1443 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMBuildBinOp(), and LLVMBuildCast().
map_to_llvmModFlagBehavior()
static Module::ModFlagBehavior map_to_llvmModFlagBehavior (LLVMModuleFlagBehavior Behavior) static
Definition at line 294 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMAddModuleFlag().
map_to_llvmopcode()
static LLVMOpcode map_to_llvmopcode (int opcode) static
Definition at line 1433 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMGetConstOpcode(), and LLVMGetInstructionOpcode().
mapFromLLVMOrdering()
static AtomicOrdering mapFromLLVMOrdering (LLVMAtomicOrdering Ordering) static
Definition at line 3498 of file Core.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm_unreachable, llvm::Monotonic, llvm::NotAtomic, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by LLVMBuildAtomicCmpXchg(), LLVMBuildAtomicRMW(), LLVMBuildFence(), LLVMSetCmpXchgFailureOrdering(), LLVMSetCmpXchgSuccessOrdering(), and LLVMSetOrdering().
mapToLLVMOrdering()
static LLVMAtomicOrdering mapToLLVMOrdering (AtomicOrdering Ordering) static
Definition at line 3514 of file Core.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm_unreachable, llvm::Monotonic, llvm::NotAtomic, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by LLVMGetCmpXchgFailureOrdering(), LLVMGetCmpXchgSuccessOrdering(), and LLVMGetOrdering().
Variable Documentation
GlobalContext
ManagedStatic<LLVMContext> GlobalContext static
Definition at line 76 of file Core.cpp.
Referenced by LLVMGetGlobalContext(), and LLVMModuleCreateWithName().