LLVM: lib/Transforms/Coroutines/Coroutines.cpp File Reference
Coroutines.cpp File Reference
#include "llvm/Transforms/Coroutines.h"
#include "llvm-c/Transforms/Coroutines.h"
#include "CoroInstr.h"
#include "CoroInternal.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include <cassert>
#include <cstddef>
#include <utility>
Functions
static void addCoroutineOpt0Passes (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addCoroutineEarlyPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addCoroutineScalarOptimizerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addCoroutineSCCPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addCoroutineOptimizerLastPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static bool isCoroutineIntrinsicName (StringRef Name)
static void buildCGN (CallGraph &CG, CallGraphNode *Node)
static void clear (coro::Shape &Shape)
static CoroSaveInst * createCoroSave (CoroBeginInst *CoroBegin, CoroSuspendInst *SuspendInst)
void LLVMAddCoroEarlyPass (LLVMPassManagerRef PM)
void LLVMAddCoroSplitPass (LLVMPassManagerRef PM)
void LLVMAddCoroElidePass (LLVMPassManagerRef PM)
void LLVMAddCoroCleanupPass (LLVMPassManagerRef PM)
Function Documentation
addCoroutineEarlyPasses()
static void addCoroutineEarlyPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 60 of file Coroutines.cpp.
References llvm::legacy::PassManagerBase::add(), and llvm::createCoroEarlyPass().
Referenced by llvm::addCoroutinePassesToExtensionPoints().
addCoroutineOpt0Passes()
static void addCoroutineOpt0Passes (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 51 of file Coroutines.cpp.
References llvm::legacy::PassManagerBase::add(), llvm::createBarrierNoopPass(), llvm::createCoroCleanupPass(), llvm::createCoroElidePass(), and llvm::createCoroSplitPass().
Referenced by llvm::addCoroutinePassesToExtensionPoints().
addCoroutineOptimizerLastPasses()
static void addCoroutineOptimizerLastPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 75 of file Coroutines.cpp.
References llvm::legacy::PassManagerBase::add(), and llvm::createCoroCleanupPass().
Referenced by llvm::addCoroutinePassesToExtensionPoints().
addCoroutineScalarOptimizerPasses()
static void addCoroutineScalarOptimizerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 65 of file Coroutines.cpp.
References llvm::legacy::PassManagerBase::add(), and llvm::createCoroElidePass().
Referenced by llvm::addCoroutinePassesToExtensionPoints().
addCoroutineSCCPasses()
static void addCoroutineSCCPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 70 of file Coroutines.cpp.
References llvm::legacy::PassManagerBase::add(), and llvm::createCoroSplitPass().
Referenced by llvm::addCoroutinePassesToExtensionPoints().
buildCGN()
static void buildCGN (CallGraph & CG, CallGraphNode * Node) static
Definition at line 174 of file Coroutines.cpp.
References F, llvm::CallGraph::getCallsExternalNode(), llvm::CallGraph::getOrInsertFunction(), I, instructions, and llvm::Intrinsic::isLeaf().
Referenced by llvm::coro::updateCallGraph().
clear()
static void clear (coro::Shape & Shape) static
Definition at line 211 of file Coroutines.cpp.
References llvm::coro::Shape::AllocaSpillBlock, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSizes, llvm::coro::Shape::CoroSuspends, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::coro::Shape::HasFinalSuspend, llvm::coro::Shape::PromiseAlloca, and llvm::coro::Shape::ResumeSwitch.
Referenced by llvm::coro::Shape::buildFrom(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DWARFDebugLine::LineTable::LineTable(), llvm::DWARFDebugLine::Prologue::parse(), and llvm::DWARFDebugLine::Prologue::Prologue().
createCoroSave()
static CoroSaveInst * createCoroSave (CoroBeginInst * CoroBegin, CoroSuspendInst * SuspendInst) static
Definition at line 225 of file Coroutines.cpp.
References assert(), llvm::CallInst::Create(), llvm::CoroSuspendInst::getCoroSave(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), and llvm::CallBase::setArgOperand().
Referenced by llvm::coro::Shape::buildFrom().
isCoroutineIntrinsicName()
static bool isCoroutineIntrinsicName (StringRef Name) static
Definition at line 123 of file Coroutines.cpp.
References llvm::Intrinsic::lookupLLVMIntrinsicByName().
Referenced by llvm::coro::declaresIntrinsics().
LLVMAddCoroCleanupPass()
void LLVMAddCoroCleanupPass (LLVMPassManagerRef PM)
Definition at line 360 of file Coroutines.cpp.
References llvm::createCoroCleanupPass(), and llvm::unwrap().
LLVMAddCoroEarlyPass()
void LLVMAddCoroEarlyPass (LLVMPassManagerRef PM)
Definition at line 348 of file Coroutines.cpp.
References llvm::createCoroEarlyPass(), and llvm::unwrap().
LLVMAddCoroElidePass()
void LLVMAddCoroElidePass (LLVMPassManagerRef PM)
Definition at line 356 of file Coroutines.cpp.
References llvm::createCoroElidePass(), and llvm::unwrap().
LLVMAddCoroSplitPass()
void LLVMAddCoroSplitPass (LLVMPassManagerRef PM)
Definition at line 352 of file Coroutines.cpp.
References llvm::createCoroSplitPass(), and llvm::unwrap().