LLVM: lib/Transforms/IPO/DeadArgumentElimination.cpp File Reference
DeadArgumentElimination.cpp File Reference
#include "llvm/Transforms/IPO/DeadArgumentElimination.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <cassert>
#include <cstdint>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "deadargelim"
Functions
STATISTIC (NumArgumentsEliminated, "Number of unread args removed")
STATISTIC (NumRetValsEliminated, "Number of unused return values removed")
STATISTIC (NumArgumentsReplacedWithUndef, "Number of unread args replaced with undef")
INITIALIZE_PASS (DAH, "deadarghaX0r", "Dead Argument Hacking (BUGPOINT USE ONLY; DO NOT USE)", false, false) ModulePass *llvm
createDeadArgEliminationPass - This pass removes arguments from functions which are not used by the body of the function.
Convenience function that returns the number of return values It returns for void functions and for functions not returning a struct It returns the number of struct elements for functions returning a struct static unsigned NumRetVals (const Function *F)
Returns the sub type a function will return at a given Idx Should correspond to the result type of an ExtractValue instruction executed with just that one Idx (i.e. only top-level structure is considered). static Type *getRetComponentType(const Function *F
assert (!RetTy->isVoidTy() &&"void type has no subtype")
if (StructType *STy=dyn_cast< StructType >(RetTy)) return STy -> getElementType(Idx)
else if (ArrayType *ATy=dyn_cast< ArrayType >(RetTy)) return ATy -> getElementType()
SurveyUses This looks at all the uses of the given value Returns the Liveness deduced from the uses of this value Adds all uses that cause the result to be MaybeLive to MaybeLiveRetUses If the result is MaybeLiveUses might be modified but its content should be ignored (since it might not be complete). DeadArgumentEliminationPass
MarkLive Mark the given Function as meaning that it cannot be changed in any way mark any values that are used as this function s parameters or by its return values (according to Uses) live as well. void DeadArgumentEliminationPass
MarkLive Mark the given return value or argument as live mark any values that are used by this value (according to Uses) live as well. void DeadArgumentEliminationPass
PropagateLiveness Given that RA is a live propagate it s liveness to any other values it uses (according to Uses). void DeadArgumentEliminationPass
Variables
Returns the sub type a function will return at a given Idx Should correspond to the result type of an ExtractValue instruction executed with just that one unsigned Idx
else return RetTy
MarkIfNotLive This checks Use for liveness in LiveValues If Use is not live
SurveyUse This looks at a single use of an argument or return value and determines if it should be alive or not Adds this use to MaybeLiveUses if it causes the used value to become MaybeLive RetValNum is the return value number to use when this use is used in a return instruction This is used in the recursion
SurveyUses This looks at all the uses of the given value Returns the Liveness deduced from the uses of this value Adds all uses that cause the result to be MaybeLive to MaybeLiveRetUses If the result is Live
MarkValue This function marks the liveness of RA depending on L If L is MaybeLive
MarkValue This function marks the liveness of RA depending on L If L is it also takes all uses in MaybeLiveUses and records them in Uses
MarkLive Mark the given Function as alive
MarkLive Mark the given Function as meaning that it cannot be changed in any way Additionally
PropagateLiveness Given that RA is a live value
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "deadargelim"
Definition at line 53 of file DeadArgumentElimination.cpp.
Function Documentation
assert()
assert (!RetTy->isVoidTy() &&"void type has no subtype")
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::GEPOperator::accumulateConstantOffset(), llvm::sys::MutexImpl::acquire(), llvm::AliasSetTracker::add(), llvm::SCEVUnionPredicate::add(), llvm::PMDataManager::add(), llvm::lto::LTO::add(), llvm::cflaa::StratifiedSetsBuilder< T >::addAbove(), llvm::AttrBuilder::addAlignmentAttr(), llvm::AliasSetTracker::addAllInstructionsInLoopUsingMSSA(), llvm::AttrBuilder::addAllocSizeAttrFromRawRepr(), llvm::cflaa::CFLGraph::addAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttributeList::addAttributes(), llvm::SSAUpdater::AddAvailableValue(), llvm::SSAUpdaterBulk::AddAvailableValue(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::addBasicBlock(), llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::cflaa::StratifiedSetsBuilder< T >::addBelow(), llvm::LoopBase< BlockT, LoopT >::addBlockEntry(), llvm::CallGraphNode::addCalledFunction(), llvm::SwitchInst::addCase(), llvm::SwitchInstProfUpdateWrapper::addCase(), llvm::cl::Option::addCategory(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LPMUpdater::addChildLoops(), llvm::LandingPadInst::addClause(), llvm::addClonedBlockToLoopInfo(), addConditions(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::IndirectBrInst::addDestination(), llvm::cflaa::CFLGraph::addEdge(), llvm::vfs::YAMLVFSWriter::addFileMapping(), llvm::CatchSwitchInst::addHandler(), llvm::PMTopLevelManager::addImmutablePass(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::cl::parser< DataType >::addLiteralOption(), llvm::LTOCodeGenerator::addModule(), llvm::Module::addModuleFlag(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), llvm::cflaa::CFLGraph::addNode(), llvm::SymbolTableListTraits< ValueSubClass >::addNodeToList(), addNonConstUser(), llvm::IRMover::IdentifiedStructTypeSet::addNonOpaque(), addNoRecurseAttrsTopDown(), llvm::IRMover::IdentifiedStructTypeSet::addOpaque(), llvm::CallBase::addParamAttr(), llvm::AttributeList::addParamAttribute(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::LoopAccessInfo::addRuntimeChecks(), llvm::LPMUpdater::addSiblingLoops(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), addToAccessGroupList(), llvm::BlockFrequencyInfoImplBase::addToDist(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::addToFrontier(), llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop(), llvm::SSAUpdaterBulk::AddUse(), llvm::cl::list_storage< DataType, StorageClass >::addValue(), llvm::cl::bits_storage< DataType, StorageClass >::addValue(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::VPlan::addVPValue(), llvm::cflaa::StratifiedSetsBuilder< T >::addWith(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), adjustToPointerSize(), llvm::BasicAAResult::alias(), llvm::AliasSet::aliasesPointer(), llvm::AliasSet::aliasesUnknownInst(), aliasSameBasePointerGEPs(), llvm::alignAddr(), llvm::alignDown(), llvm::alignTo(), allCallersPassValidPointerForArgument(), llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), llvm::AllocaInst::AllocaInst(), llvm::sroa::AllocaSliceRewriter::AllocaSliceRewriter(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::GVNExpression::AggregateValueExpression::allocateIntOperands(), llvm::GVNExpression::BasicExpression::allocateOperands(), llvm::User::allocHungoffUses(), allocset(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::ForwardDominanceFrontierBase< BlockT >::analyze(), analyzeGlobalAux(), llvm::BlockFrequencyInfoImplBase::analyzeIrreducible(), llvm::VNCoercion::analyzeLoadFromClobberingLoad(), analyzeLoopUnrollCost(), llvm::DIExpression::append(), appendDigit(), appendLoopsToWorklist(), llvm::internal::appendLoopsToWorklist(), llvm::DIExpression::appendToStack(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::MemoryDepChecker::areDepsSafe(), areStridedAccessesIndependent(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::arg_begin(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::arg_end(), llvm::json::OStream::arrayEnd(), assertBranchOrSelectConditionHoisted(), assertCHRRegionsHaveBiasedBranchOrSelect(), llvm::Value::assertModuleIsMaterializedImpl(), AssertSorted(), llvm::CallGraphSCCPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::cflaa::CFLGraph::attrFor(), llvm::DWARFDie::attribute_iterator::attribute_iterator(), llvm::json::OStream::attributeBegin(), llvm::json::OStream::attributeEnd(), llvm::AttributeListImpl::AttributeListImpl(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), BatchCommitValueTo(), llvm::LoopBlocksTraversal::begin(), llvm::PooledStringPtr::begin(), llvm::yaml::begin(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::LoopBlocksDFS::beginPostorder(), llvm::LoopBlocksDFS::beginRPO(), llvm::ConstantRange::binaryOp(), llvm::BitCastInst::BitCastInst(), llvm::LoopAccessInfo::blockNeedsPredication(), llvm::LoopBase< BlockT, LoopT >::blocks(), bothcases(), llvm::BranchProbability::BranchProbability(), BrPHIToSelect(), buildClonedLoopBlocks(), buildClonedLoops(), buildExtractionBlockSet(), buildFixItLine(), llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::VPlanSlp::buildGraph(), llvm::PassBuilder::buildLTOPreLinkDefaultPipeline(), llvm::buildModuleSummaryIndex(), buildNew(), llvm::DICompositeType::buildODRType(), llvm::PassBuilder::buildPerModuleDefaultPipeline(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), llvm::LazyCallGraph::buildRefSCCs(), llvm::InnerLoopVectorizer::buildScalarSteps(), BuildSubAggregate(), llvm::PassBuilder::buildThinLTOPreLinkDefaultPipeline(), llvm::slpvectorizer::BoUpSLP::buildTree(), llvm::ARM::WinEH::RuntimeFunction::C(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::BranchProbabilityInfo::calculate(), llvm::MDNodeOpsKey::calculateHash(), calculateIterationsToInvariance(), llvm::codeview::DebugInlineeLinesSubsection::calculateSerializedSize(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::CallSiteBase(), callsiteIsHot(), canConvertValue(), canCreateAliasFor(), canEvaluateSExtd(), canEvaluateShiftedShift(), canEvaluateTruncated(), llvm::canImportGlobalVar(), llvm::AAResults::canInstructionRangeModRef(), canNotEvaluateInType(), canonicalizeCmpWithConstant(), canonicalizeConstantArg0ToArg1(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), canPaddingBeAccessed(), canProfitablyUnrollMultiExitLoop(), CanPropagatePredecessorsForPHIs(), CanProveNotTakenFirstIteration(), canSinkInstructions(), llvm::canSinkOrHoistInst(), canTransformAccumulatorRecursion(), canTrapImpl(), llvm::LoopVectorizationLegality::canVectorize(), CasesAreContiguous(), llvm::cast(), llvm::cast_or_null(), chainToBasePointerCost(), llvm::LLT::changeElementSize(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::LoopInfoBase< BlockT, LoopT >::changeTopLevelLoop(), llvm::FileCheckString::Check(), checkBasicSSA(), checkBiasedBranch(), checkClobberSanity(), llvm::FileCheckString::CheckDag(), checkDependencies(), llvm::checkGEPType(), checkGlobalVariableScope(), checkHoistValue(), checkMDProf(), llvm::FileCheckString::CheckNot(), checkType(), llvm::IDFCalculatorDetail::ChildrenGetterTy< BasicBlock, IsPostDom >::ChildrenGetterTy(), chopOneUTF32(), llvm::FPPassManager::cleanup(), clearAssumptionsOfUsers(), llvm::SCEVWrapPredicate::clearFlags(), llvm::CoroIdInst::clearPromise(), CloneAliasScopeMetadata(), llvm::CloneAndPruneIntoFromInst(), cloneConstantExprWithNewAddressSpace(), llvm::CloneFunctionInto(), CloneInstructionInExitBlock(), cloneInstructionWithNewAddressSpace(), CloneLoopBlocks(), cloneLoopNest(), llvm::cloneLoopWithPreheader(), llvm::raw_fd_ostream::close(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpTypes(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), llvm::CodeMetrics::collectEphemeralValues(), collectHomogenousInstGraphLoopInvariants(), collectInsertionElements(), collectMultiplyFactors(), collectShuffleElements(), collectSingleShuffleElements(), collectTransitivePredecessors(), combineLoadToNewType(), combineLoadToOperationType(), combineStoreToNewValue(), combineWeight(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::codeview::DebugLinesSubsection::commit(), llvm::codeview::DebugStringTableSubsection::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::pdb::PDBFileBuilder::commit(), commitFpm(), CommitValueTo(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::ShuffleVectorInst::commuteShuffleMask(), llvm::FunctionComparator::compare(), llvm::ScaledNumbers::compareImpl(), llvm::compareLoops(), llvm::MDNodeOpsKey::compareOps(), CompareSCEVComplexity(), llvm::FunctionComparator::compareSignature(), completeEphemeralValues(), computeAddrMap(), computeAliasSummary(), llvm::ComputeASanStackFrameLayout(), computeBucketCount(), llvm::computeConstantRange(), llvm::ComputeCrossModuleImportForModuleFromIndex(), llvm::computeDeadSymbols(), computeDomSubtreeCost(), computeForAddCarry(), llvm::KnownBits::computeForAddCarry(), computeFunctionSummary(), computeImportForFunction(), ComputeImportForModule(), llvm::DivergencePropagator::computeJoinPoints(), computeKnownBits(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsMul(), computeLiveInValues(), computeLiveOutSeed(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), llvm::ICFLoopSafetyInfo::computeLoopSafetyInfo(), llvm::ComputeMultiple(), ComputeNumSignBits(), ComputeNumSignBitsImpl(), llvm::computePeelCount(), computeSignedMinMaxValuesFromKnownBits(), ComputeSpeculationCost(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::computeUnrollCount(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), computeVTableFuncs(), concatenateTwoVectors(), llvm::concatenateVectors(), llvm::VPBlockUtils::connectBlocks(), ConnectEpilog(), ConnectProlog(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldTerminator(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), constantFoldUser(), llvm::ConstantRange::ConstantRange(), ConstructSSAForLoadSet(), llvm::AttrBuilder::contains(), llvm::LoopBase< BlockT, LoopT >::contains(), containsUnconditionalCallSafepoint(), llvm::ContextAndReplaceableUses::ContextAndReplaceableUses(), llvm::ConvertDebugDeclareToDebugValue(), llvm::InlineAsm::convertMemFlagWordToMatchingFlagWord(), ConvertTwoCaseSwitch(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), convertValue(), llvm::Instruction::copyFastMathFlags(), copyMustTailReturn(), llvm::AliasSetTracker::copyValue(), countToEliminateCompares(), llvm::BinaryOperator::Create(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::OnDiskChainedHashTable< Info >::Create(), llvm::OnDiskIterableChainedHashTable< Info >::Create(), llvm::CastInst::Create(), llvm::vfs::RedirectingFileSystem::create(), llvm::StructType::create(), llvm::GetElementPtrInst::Create(), llvm::InlineAsmKeyType::create(), llvm::CatchReturnInst::Create(), llvm::CleanupReturnInst::Create(), llvm::ScalarEvolution::createAddRecFromPHIWithCasts(), llvm::IRBuilder< T, Inserter >::CreateAlignmentAssumption(), llvm::IRBuilder< T, Inserter >::CreateAnd(), CreateAssert(), CreateAssertNot(), llvm::IRBuilderBase::CreateAssumption(), llvm::DIBuilder::createBasicType(), llvm::createBitMaskForGaps(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::MDBuilder::createBranchWeights(), createCallInst(), createCast(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), createCoroSave(), llvm::MemorySSA::createDefinedAccess(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::DIBuilder::createEnumerator(), llvm::IRBuilder< T, Inserter >::CreateExtractInteger(), llvm::CastInst::CreateFPCast(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), createFree(), llvm::CallInst::CreateFree(), llvm::DIBuilder::createFriend(), CreateGCRelocates(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::createHWAddressSanitizerLegacyPassPass(), createImportedModule(), llvm::msf::MappedBlockStream::createIndexedStream(), llvm::msf::WritableMappedBlockStream::createIndexedStream(), llvm::DIBuilder::createInheritance(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::DIBuilder::createLabel(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::FileCheckPatternContext::createLineVariable(), createLocalVariable(), llvm::DIBuilder::createMacro(), createMalloc(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::Target::createMCObjectStreamer(), llvm::IRBuilderBase::CreateMemCpy(), llvm::createMemCpyLoopKnownSize(), llvm::createMemCpyLoopUnknownSize(), llvm::IRBuilderBase::CreateMemMove(), llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), llvm::DIBuilder::createMethod(), createMinMax(), llvm::IRBuilder< T, Inserter >::CreateNAryOp(), llvm::IRBuilder< T, Inserter >::CreateOr(), llvm::DIBuilder::createParameterVariable(), createPHIsForSplitLoopExit(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilder< T, Inserter >::CreatePreserveArrayAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveStructAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePreserveUnionAccessIndex(), llvm::IRBuilder< T, Inserter >::CreatePtrDiff(), llvm::MDBuilder::createRange(), createRdxShuffleMask(), llvm::DIBuilder::createReferenceType(), llvm::VPRecipeBuilder::createReplicateRegion(), llvm::createSanitizerCtorAndInitFunctions(), llvm::IRBuilder< T, Inserter >::CreateSExtOrTrunc(), llvm::createSimpleTargetReduction(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::sys::fs::createTemporaryFile(), llvm::DIBuilder::createUnspecifiedType(), llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::data_operands_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::data_operands_end(), llvm::CallBase::dataOperandHasImpliedAttr(), DEBUG_COUNTER(), llvm::declareSanitizerInitFunction(), llvm::coro::declaresIntrinsics(), DecodeFixedType(), llvm::codeview::decodeFramePtrReg(), llvm::def_chain(), llvm::FileCheckPatternContext::defineCmdlineVariables(), DeleteBasicBlock(), llvm::DeleteDeadBlocks(), llvm::deleteDeadLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DominatorTreeBase< NodeT, IsPostDom >::deleteEdge(), deleteLoopIfDead(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::MDNode::deleteTemporary(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::deopt_begin(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::deopt_end(), llvm::DependenceInfo::depends(), llvm::ManagedStaticBase::destroy(), llvm::SpecificBumpPtrAllocator< T >::DestroyAll(), llvm::Constant::destroyConstant(), llvm::DetatchDeadBlocks(), determinePointerReadAttrs(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::DIMacroNode::DIMacroNode(), llvm::DINode::DINode(), llvm::vfs::directory_iterator::directory_iterator(), llvm::VPBlockUtils::disconnectBlocks(), llvm::ModuleSummaryIndex::discoverNodes(), llvm::IntervalMapImpl::distribute(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::ScaledNumbers::divide32(), llvm::ScaledNumbers::divide64(), DivRemPairWorklistEntry::DivRemPairWorklistEntry(), doemit(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), dofwd(), llvm::FunctionImportGlobalProcessing::doImportAsDefinition(), doinsert(), llvm::isa_impl_cl< To, From * >::doit(), llvm::isa_impl_cl< To, From *const >::doit(), llvm::isa_impl_cl< To, const From * >::doit(), llvm::isa_impl_cl< To, const From *const >::doit(), llvm::isa_impl_cl< To, const std::unique_ptr< From > >::doit(), llvm::Trace::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::OrderedBasicBlock::dominates(), llvm::InstCombiner::dominatesAllUses(), doPromotion(), llvm::DomTreeUpdater::dump(), llvm::ImportedFunctionsInliningStatistics::dump(), llvm::RangeListEntry::dump(), llvm::DWARFDebugNames::Entry::dump(), dumpApplePropertyAttribute(), llvm::PMTopLevelManager::dumpArguments(), llvm::vfs::RedirectingFileSystem::dumpEntry(), dupl(), llvm::JumpThreadingPass::DuplicateCondBranchOnPHIIntoPred(), llvm::DuplicateInstructionsInSplitBetween(), llvm::DWARFExpression::DWARFExpression(), EatNumber(), eliminateDeadStores(), eliminateDeadSwitchCases(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::emitBinaryFloatFnCall(), llvm::LLVMContext::emitError(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::InnerLoopVectorizer::emitTransformedIndex(), emitUnaryFloatFnCallHelper(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::empty(), llvm::BlotMapVector< KeyT, ValueT >::empty(), llvm::TimeTraceProfiler::end(), llvm::PooledStringPtr::end(), llvm::codeview::CodeViewRecordIO::endRecord(), enforceKnownAlignment(), llvm::CFLSteensAAResult::ensureCached(), ensureValueAvailableInSuccessor(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes(), llvm::vfs::Status::equivalent(), llvm::LoopInfo::erase(), llvm::InstCombiner::eraseInstFromFunction(), llvm::objcarc::EraseInstruction(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), error(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::eval(), EvaluateConstantChrecAtConstant(), evaluateFCmpRelation(), evaluateICmpRelation(), evaluateInDifferentElementOrder(), EvaluateStoreInto(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA(), llvm::ARM::WinEH::RuntimeFunction::ExceptionInformationRVA(), llvm::VPlan::execute(), llvm::VPBasicBlock::execute(), llvm::VPRegionBlock::execute(), llvm::VPInstruction::execute(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::VPBlendRecipe::execute(), llvm::VPInterleaveRecipe::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::sys::ExecuteAndWait(), llvm::sys::ExecuteNoWait(), llvm::LoopVectorizationPlanner::executePlan(), llvm::SCEVExpander::expandCodeFor(), llvm::SCEVExpander::expandCodeForPredicate(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::cl::ExpandResponseFiles(), llvm::Expected< T >::Expected(), llvm::ModuleSummaryIndex::exportToDot(), llvm::DWARFExpression::Operation::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFUnitHeader::extract(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::RangeListEntry::extract(), llvm::CodeExtractor::extractCodeRegion(), ExtractConstantBytes(), extractInteger(), extractMDNode(), llvm::Instruction::extractProfMetadata(), llvm::Instruction::extractProfTotalWeight(), llvm::DWARFUnit::extractRangeList(), extractVector(), llvm::ARM::WinEH::ExceptionDataRecord::F(), factorizeFAddFSub(), llvm::filterDeadComdatFunctions(), llvm::DIBuilder::finalize(), llvm::pdb::HashTable< ValueT >::find_as(), llvm::CodeExtractor::findAllocas(), llvm::PMTopLevelManager::findAnalysisPassInfo(), llvm::PMTopLevelManager::findAnalysisUsage(), findBaseDefiningValue(), findBaseDefiningValueCached(), findBaseDefiningValueOfVector(), findBasePointer(), findBasePointers(), findBestInsertionSet(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), FindFirstMatchingPrefix(), findFuncPointers(), llvm::sys::Process::FindInEnvPath(), llvm::FindInsertedValue(), findInsertPointAfter(), findIrreducibleHeaders(), findLiveSetAtInst(), FindLIVLoopCondition(), findLocationForEntrySafepoint(), FindLoopCounter(), llvm::findMaximalSubpartOfIllFormedUTF8Sequence(), FindMostPopularDest(), findmust(), llvm::opt::OptTable::findNearest(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::findOptionMDForLoopID(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), FindPHIForConditionForwarding(), findProfitablePHIs(), llvm::pdb::GlobalsStream::findRecordsByName(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::findScalarElement(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), findTargetSubtable(), llvm::LoopBlocksTraversal::finishPostorder(), firstch(), llvm::FixedStreamArray< T >::FixedStreamArray(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), fmed3AMDGCN(), foldAndToXor(), FoldBitCast(), llvm::FoldBranchToCommonDest(), foldConstantCastPair(), foldConstantInsEltIntoShuffle(), foldCtpop(), foldCttzCtlz(), foldFabsWithFcmpZero(), foldGuardedRotateToFunnelShift(), foldICmpWithLowBitMaskedVal(), foldICmpWithTruncSignExtendedVal(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldOperationIntoSelectOperand(), foldOrToXor(), foldReturnAndProcessPred(), foldSelectICmpAnd(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftedShift(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), foldXorToXor(), forceIndeterminateEdge(), forceRenaming(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), llvm::format_provider< T, typename std::enable_if< detail::use_integral_formatter< T >::value >::type >::format(), llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format(), llvm::codeview::detail::GuidAdapter::format(), llvm::format_hex(), llvm::format_hex_no_prefix(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::detail::frexp(), llvm::ConstantRange::fromKnownBits(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::fromSuccessorIndex(), llvm::FunctionCallee::FunctionCallee(), llvm::cflaa::FunctionHandle< AAResult >::FunctionHandle(), llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo(), llvm::ARM::WinEH::RuntimeFunction::FunctionLength(), LoopFuser::fuseLoops(), llvm::gatherImportedSummariesForModule(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::gc_transition_args_begin(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::gc_transition_args_end(), llvm::RuntimePointerChecking::generateChecks(), llvm::SCEVExpander::generateOverflowCheck(), generatePoisonChecksForBinOp(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), genLoopLimit(), llvm::OptionRegistry::get(), llvm::LayoutAlignElem::get(), llvm::objcarc::ARCRuntimeEntryPoints::get(), llvm::BlockAddress::get(), llvm::pdb::HashTable< ValueT >::get(), llvm::InlineCost::get(), llvm::AttributeList::get(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get(), llvm::ConstantStruct::get(), llvm::VectorType::get(), llvm::ArrayType::get(), llvm::PointerType::get(), llvm::StructType::get(), llvm::ConstantAggregateZero::get(), llvm::ConstantFP::get(), llvm::PointerAlignElem::get(), llvm::ConstantExpr::get(), llvm::ValueAsMetadata::get(), llvm::Attributor::getAAFor(), llvm::DWARFDie::getAbbreviationDeclarationPtr(), llvm::ValueInfo::getAccessSpecifier(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::TargetTransformInfo::getAddressComputationCost(), llvm::LLT::getAddressSpace(), llvm::ConstantExpr::getAddrSpaceCast(), getAdjustedPtr(), llvm::Constant::getAggregateElement(), getAISize(), llvm::opt::Option::getAlias(), llvm::opt::Option::getAliasArgs(), llvm::AliasSummary::getAliasee(), llvm::AliasSummary::getAliaseeGUID(), llvm::AliasSummary::getAliaseeVI(), llvm::AliasSetTracker::getAliasSetFor(), llvm::Attribute::getAlignment(), getAllocaSizeInBytes(), llvm::Attribute::getAllocSizeArgs(), llvm::ScalarEvolution::getAnyExtendExpr(), GetAnyNonZeroConstInt(), llvm::Argument::getArgNo(), llvm::CallBase::getArgOperand(), llvm::CallBase::getArgOperandUse(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgument(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::getArgument(), llvm::getArgumentAliasingToReturnedPointer(), llvm::Intrinsic::IITDescriptor::getArgumentKind(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgumentNo(), llvm::Intrinsic::IITDescriptor::getArgumentNumber(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::TargetTransformInfo::getArithmeticReductionCost(), llvm::Type::getArrayElementType(), llvm::ConstantDataSequential::getAsCString(), llvm::ConstantExpr::getAsInstruction(), llvm::ConstantDataSequential::getAsString(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::FunctionPointerLikeTypeTraits< Alignment, FunctionPointerT >::getAsVoidPointer(), llvm::DWARFAbbreviationDeclaration::getAttrByIndex(), llvm::CFGMST< Edge, BBInfo >::getBBInfo(), llvm::RegionBase< Tr >::getBBNode(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), llvm::ConstantExpr::getBitCast(), llvm::SMTSort::getBitvectorSortSize(), llvm::KnownBits::getBitWidth(), llvm::bfi_detail::getBlockName(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getBlocksSet(), llvm::LoopBase< BlockT, LoopT >::getBlocksVector(), getBranchInsertPoint(), llvm::BranchProbability::getBranchProbability(), GetBranchWeights(), llvm::DWARFDebugNames::NameIndex::getBucketArrayEntry(), GetBucketPtr(), llvm::SourceMgr::getBufferInfo(), llvm::CallBase::getBundleOperandsEndIndex(), llvm::CallBase::getBundleOperandsStartIndex(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::LazyBlockFrequencyInfo< FunctionT, BranchProbabilityInfoPassT, LoopInfoT, BlockFrequencyInfoT >::getCalculated(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::getCall(), llvm::AbstractCallSite::getCallArgOperandNoForCallee(), llvm::TargetTransformInfoImplCRTPBase< T >::getCallCost(), llvm::TargetTransformInfoImplBase::getCallCost(), llvm::TargetTransformInfo::getCallCost(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), llvm::TargetTransformInfo::getCallInstrCost(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseSuccessor(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseValue(), llvm::ConstantExpr::getCast(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getCastsForInductionPHI(), llvm::TargetTransformInfo::getCFInstrCost(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::MemDepResult::getClobber(), llvm::MemorySSAWalker::getClobberingMemoryAccess(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm::pdb::DIAInjectedSource::getCode(), llvm::gvn::AvailableValue::getCoercedLoadValue(), llvm::DebugLoc::getCol(), llvm::ConstantExpr::getCompare(), llvm::BranchInst::getCondition(), llvm::ValueLatticeElement::getConstant(), llvm::KnownBits::getConstant(), llvm::getConstantDataArrayInfo(), llvm::ValueLatticeElement::getConstantInt(), llvm::ValueLatticeElement::getConstantRange(), llvm::LazyValueInfo::getConstantRange(), llvm::getConstantRangeFromMetadata(), llvm::LazyValueInfo::getConstantRangeOnEdge(), llvm::legacy::FunctionPassManagerImpl::getContainedManager(), llvm::legacy::PassManagerImpl::getContainedManager(), llvm::LPPassManager::getContainedPass(), llvm::RGPassManager::getContainedPass(), llvm::FPPassManager::getContainedPass(), llvm::Type::getContainedType(), llvm::CoroSuspendInst::getCoroSave(), llvm::InlineCost::getCost(), llvm::DebugCounter::getCounterValue(), llvm::DWARFDebugNames::NameIndex::getCUOffset(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getDataOperandNo(), llvm::CallBase::getDataOperandNo(), getDbgIntrinsicValueImpl(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::MemDepResult::getDef(), GetDeoptBundleOperands(), getDeoptLowering(), llvm::Argument::getDereferenceableBytes(), llvm::Attribute::getDereferenceableBytes(), llvm::Argument::getDereferenceableOrNullBytes(), llvm::Attribute::getDereferenceableOrNullBytes(), llvm::User::getDescriptor(), llvm::DWARFUnit::getDIEAtIndex(), llvm::DWARFUnit::getDIEForOffset(), llvm::FullDependence::getDirection(), llvm::FullDependence::getDistance(), llvm::DomTreeUpdater::getDomTree(), llvm::VectorType::getDoubleElementsVectorType(), llvm::DWARFUnit::getDwarfStringOffsetsByteSize(), llvm::getDWARFUnitIndex(), getEdgeValueLocal(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::DIExpression::getElement(), llvm::ConstantDataSequential::getElementAsAPInt(), llvm::ConstantDataSequential::getElementAsDouble(), llvm::ConstantDataSequential::getElementAsFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::StructLayout::getElementContainingOffset(), llvm::VectorType::getElementCount(), llvm::StructLayout::getElementOffset(), llvm::LLT::getElementType(), llvm::StructType::getElementType(), llvm::VPBlockBase::getEnclosingBlockWithPredecessors(), llvm::VPBlockBase::getEnclosingBlockWithSuccessors(), getEncodedIntegerLength(), llvm::BlockFrequencyInfoImplBase::getEntryFreq(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), llvm::ScalarEvolution::getEqualPredicate(), llvm::ConstantRange::getEquivalentICmp(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::ConstantExpr::getExtractElement(), getExtractIndex(), llvm::ConstantExpr::getExtractValue(), llvm::TargetTransformInfo::getExtractWithExtendCost(), llvm::ConstantInt::getFalse(), llvm::Instruction::getFastMathFlags(), llvm::ConstantExpr::getFCmp(), getFCmpCode(), getFCmpValue(), getFD(), llvm::DWARFDebugLine::Prologue::getFileNameEntry(), getFirstFunctionBlock(), llvm::InstructionPrecedenceTracking::getFirstSpecialInstruction(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForMem(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::SMTSort::getFloatSortSize(), llvm::ConstantExpr::getFNeg(), getFoldedCast(), llvm::MemoryLocation::getForArgument(), llvm::DWARFDebugNames::NameIndex::getForeignTUSignature(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::Type::getFPMantissaWidth(), llvm::TargetTransformInfo::getFPOpCost(), getFPSequenceIfElementsMatch(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::DIInliningInfo::getFrame(), llvm::LazyCallGraph::Edge::getFunction(), llvm::TargetTransformInfo::getGatherScatterOpCost(), llvm::Function::getGC(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), llvm::ConstantExpr::getGetElementPtr(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), llvm::opt::Option::getGroup(), llvm::VectorType::getHalfElementsVectorType(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), getHashValueImpl(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), getHexDigit(), llvm::ConstantExpr::getICmp(), llvm::MemoryAccess::getID(), llvm::opt::Option::getID(), llvm::codeview::DebugStringTableSubsection::getIdForString(), llvm::GetIfCondition(), llvm::ValueAsMetadata::getIfExists(), llvm::ConstantDataSequential::getImpl(), getImpl(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::getImplicitConstValue(), llvm::Loop::getIncomingAndBackEdge(), llvm::MemoryPhi::getIncomingBlock(), llvm::PHINode::getIncomingBlock(), llvm::MemoryPhi::getIncomingValueForBlock(), llvm::PHINode::getIncomingValueForBlock(), llvm::CoroSubFnInst::getIndex(), llvm::DataLayout::getIndexedOffsetInType(), llvm::DataLayout::getIndexSize(), llvm::coro::Shape::getIndexType(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::CallBrInst::getIndirectDestLabel(), llvm::CallBrInst::getIndirectDestLabelUse(), llvm::Loop::getInductionVariable(), llvm::CoroIdInst::getInfo(), llvm::GlobalVariable::getInitializer(), llvm::DebugLoc::getInlinedAt(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::ConstantExpr::getInsertElement(), getInsertPointForUses(), llvm::ConstantExpr::getInsertValue(), llvm::VectorType::getInteger(), llvm::ConstantExpr::getIntegerCast(), llvm::TargetTransformInfo::getInterleavedMemoryOpCost(), llvm::TargetTransformInfo::getIntImmCodeSizeCost(), llvm::TargetTransformInfo::getIntImmCost(), llvm::DataLayout::getIntPtrType(), llvm::TargetTransformInfo::getIntrinsicCost(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), getIntSequenceIfElementsMatch(), llvm::ConstantExpr::getIntToPtr(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getJumpThreadDuplicationCost(), llvm::LazyCallGraph::Edge::getKind(), llvm::opt::Option::getKind(), llvm::Attribute::getKindAsEnum(), llvm::AttributeImpl::getKindAsEnum(), llvm::Attribute::getKindAsString(), llvm::AttributeImpl::getKindAsString(), llvm::DWARFUnit::getLastChild(), llvm::pdb::NativeTypePointer::getLength(), llvm::ScaledNumbers::getLgImpl(), llvm::DebugLoc::getLine(), llvm::SourceMgr::getLineAndColumn(), llvm::pdb::PDBContext::getLineInfoForAddress(), llvm::cflaa::StratifiedSets< T >::getLink(), llvm::getLoadStoreAddressSpace(), llvm::getLoadStoreAlignment(), llvm::VNCoercion::getLoadValueForLoad(), getLocalFunctionMetadata(), llvm::SlotTracker::getLocalSlot(), llvm::DWARFDebugNames::NameIndex::getLocalTUOffset(), getLocForRead(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::getLoopEstimatedTripCount(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::BlockFrequencyInfoImplBase::getLoopPackage(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::SourceMgr::getMainFileID(), llvm::getMallocArraySize(), llvm::getMallocType(), llvm::TargetTransformInfo::getMaskedMemoryOpCost(), llvm::ShuffleVectorInst::getMaskValue(), llvm::TargetTransformInfo::getMemcpyCost(), getMemInstValueType(), llvm::gvn::AvailableValue::getMemIntrinValue(), llvm::SourceMgr::getMemoryBuffer(), llvm::InlineAsm::getMemoryConstraintID(), llvm::TargetTransformInfo::getMemoryOpCost(), llvm::SourceMgr::GetMessage(), llvm::PredicateInfoClasses::ValueDFS_Compare::getMiddleDef(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::TargetTransformInfo::getMinMaxReductionCost(), llvm::ScalarEvolution::GetMinTrailingZeros(), llvm::codeview::getModifiedType(), llvm::BasicAAResult::getModRefInfo(), llvm::ModuleSummaryIndex::getModule(), llvm::pdb::DbiModuleList::getModuleDescriptor(), llvm::ModuleSummaryIndex::getModuleHash(), llvm::ScalarEvolution::getMulExpr(), llvm::DIInliningInfo::getMutableFrame(), llvm::DIScope::getName(), llvm::StructType::getName(), llvm::opt::Option::getName(), llvm::Intrinsic::getName(), llvm::TargetLibraryInfo::getName(), llvm::DWARFDebugNames::NameIndex::getNameTableEntry(), getNameWithPrefixImpl(), llvm::ConstantExpr::getNeg(), getNegativeIsTrueBoolVec(), llvm::codeview::TypeTableCollection::getNext(), llvm::LazyCallGraph::Edge::getNode(), llvm::RegionBase< Tr >::getNode(), llvm::RegionNodeBase< Tr >::getNodeAs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock(), llvm::cflaa::CFLGraph::ValueInfo::getNodeInfoAtLevel(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ConstantExpr::getNot(), llvm::ValueLatticeElement::getNotConstant(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::LLT::getNumElements(), llvm::msf::getNumFpmIntervals(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::getNumPatchBytes(), llvm::CallBase::getNumSubclassExtraOperandsDynamic(), llvm::CallBase::getNumTotalBundleOperands(), llvm::DICompositeType::getODRTypeIfExists(), llvm::DWARFDie::getOffset(), llvm::codeview::LazyRandomTypeCollection::getOffsetOfType(), llvm::MemoryBuffer::getOpenFileSlice(), llvm::SCEVNAryExpr::getOperand(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::User::getOperand(), llvm::GVNExpression::BasicExpression::getOperand(), llvm::VPUser::getOperand(), llvm::CallBase::getOperandBundle(), llvm::CallBase::getOperandBundleAt(), llvm::LLVMContextImpl::getOperandBundleTagID(), llvm::User::getOperandUse(), llvm::TargetTransformInfoImplBase::getOperationCost(), llvm::TargetTransformInfo::getOperationCost(), llvm::opt::OptTable::getOption(), llvm::ConstantUniqueMap< ConstantClass >::getOrCreate(), llvm::GetOrCreateFunctionComdat(), llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::getOrCreateInitFunction(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::getOrderedReduction(), llvm::OptimizationRemarkEmitterWrapperPass::getORE(), llvm::getOrEnforceKnownAlignment(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::CallGraph::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), llvm::LLVMContextImpl::getOrInsertSyncScopeID(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), llvm::Intrinsic::IITDescriptor::getOverloadArgNumber(), llvm::Argument::getParamAlignment(), llvm::CallBase::getParamAttr(), llvm::Argument::getParamByValType(), llvm::SourceMgr::getParentIncludeLoc(), llvm::PMDataManager::getPassManagerType(), llvm::Function::getPersonalityFn(), llvm::memoryaccess_def_iterator_base< T >::getPhiArgBlock(), llvm::PluginLoader::getPlugin(), llvm::DataLayout::getPointerABIAlignment(), llvm::Value::getPointerAlignment(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), llvm::Value::getPointerDereferenceableBytes(), llvm::Type::getPointerElementType(), llvm::DataLayout::getPointerPrefAlignment(), llvm::DataLayout::getPointerSize(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::cl::list< DataType, StorageClass, ParserClass >::getPosition(), llvm::cl::bits< DataType, Storage, ParserClass >::getPosition(), llvm::DomTreeUpdater::getPostDomTree(), llvm::SCEVAddRecExpr::getPostIncExpr(), llvm::LoopBlocksDFS::getPostorder(), getPow(), llvm::DataLayout::getPreferredTypeAlignmentShift(), llvm::Function::getPrefixData(), llvm::ProfileSummaryInfo::getProfileCount(), llvm::Function::getPrologueData(), llvm::getPtrStride(), llvm::ConstantExpr::getPtrToInt(), GetQuadraticEquation(), llvm::InlineCost::getReason(), getReducedType(), llvm::Intrinsic::IITDescriptor::getRefArgNumber(), llvm::cl::getRegisteredOptions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::GetElementPtrInst::getResultElementType(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::getRoot(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRoot(), llvm::getSafeVectorConstantForBinop(), llvm::LLT::getScalarSizeInBits(), llvm::VectorizerValueMap::getScalarValue(), getScalingFactorCost(), llvm::TargetTransformInfo::getScalingFactorCost(), llvm::ScalarEvolution::getSCEV(), llvm::DIScope::getScope(), llvm::DebugLoc::getScope(), llvm::codeview::getScopeEndOffset(), llvm::codeview::getScopeParentOffset(), llvm::Function::getSectionPrefix(), llvm::ConstantExpr::getSelect(), llvm::Type::getSequentialElementType(), llvm::generic_gep_type_iterator< ItTy >::getSequentialNumElements(), llvm::ConstantExpr::getSExt(), llvm::GetShadowBytes(), llvm::GetShadowBytesAfterScope(), llvm::TargetTransformInfo::getShuffleCost(), llvm::getShuffleReduction(), llvm::ConstantExpr::getShuffleVector(), llvm::CmpInst::getSignedPredicate(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::codeview::TypeIndex::getSimpleKind(), llvm::codeview::TypeIndex::getSimpleMode(), llvm::gvn::AvailableValue::getSimpleValue(), llvm::lto::InputFile::getSingleBitcodeModule(), llvm::ConstantExpr::getSIToFP(), llvm::DataExtractor::getSLEB128(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::SuccIterator< InstructionT, BlockT >::getSource(), llvm::ConstantDataVector::getSplat(), llvm::Constant::getSplatValue(), llvm::DependenceInfo::getSplitIteration(), llvm::Attribute::getStackAlignment(), llvm::GCProjectionInst::getStatepoint(), llvm::InnerLoopVectorizer::getStepVector(), getStoredPointerOperand(), llvm::MDString::getString(), llvm::pdb::NamedStreamMap::getString(), llvm::codeview::DebugStringTableSubsection::getStringForId(), llvm::DWARFUnit::getStringOffsetsBase(), llvm::pdb::PDBFile::getStringTable(), llvm::getStructTM(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), llvm::LoopBase< BlockT, LoopT >::getSubLoopsVector(), getSubprogram(), llvm::BranchInst::getSuccessor(), llvm::InvokeInst::getSuccessor(), llvm::CallBrInst::getSuccessor(), llvm::SwitchInst::getSuccessor(), llvm::CatchSwitchInst::getSuccessor(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getSuccessorIndex(), llvm::GetSuccessorNumber(), llvm::ScaledNumbers::getSum(), llvm::pdb::SymbolCache::getSymbolById(), getSymTab(), llvm::InlineCost::getThreshold(), llvm::ConstantInt::getTrue(), llvm::ConstantExpr::getTrunc(), llvm::VectorType::getTruncatedElementVectorType(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), getTwoPredecessors(), llvm::pdb::TpiStream::getType(), llvm::codeview::LazyRandomTypeCollection::getType(), llvm::codeview::TypeTableCollection::getType(), llvm::CompositeType::getTypeAtIndex(), llvm::ConstantStruct::getTypeForElements(), llvm::getTypeName(), getTypePartition(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::ScalarEvolution::getUDivExpr(), llvm::ConstantExpr::getUIToFP(), llvm::DataExtractor::getULEB128(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::getUnaryFloatFn(), llvm::GetUnderlyingObject(), getUnderlyingObjectFromInt(), llvm::getUniqueExitBlocksHelper(), llvm::AliasSet::getUniqueInstruction(), llvm::Constant::getUniqueInteger(), llvm::LoopBase< BlockT, LoopT >::getUniqueNonLatchExitBlocks(), llvm::ScalarEvolution::getUnknown(), getUnrollAndJammedLoopSize(), getUnrolledLoopSize(), llvm::GetUnrollMetadata(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::ScalarEvolution::getURemExpr(), llvm::TargetTransformInfo::getUserCost(), llvm::Evaluator::getVal(), llvm::TrackingVH< ValueTy >::getValPtr(), llvm::LocationSize::getValue(), llvm::ValueInfo::getValue(), llvm::cl::OptionValueCopy< DataType >::getValue(), llvm::pdb::NativeSymbolEnumerator::getValue(), llvm::Attribute::getValueAsInt(), llvm::AttributeImpl::getValueAsInt(), llvm::Attribute::getValueAsString(), llvm::AttributeImpl::getValueAsString(), llvm::Attribute::getValueAsType(), llvm::AttributeImpl::getValueAsType(), getValueFromCondition(), llvm::Value::getValueName(), llvm::PhiValues::getValuesForPhi(), llvm::DbgVariableIntrinsic::getVariableLocation(), llvm::Type::getVectorElementType(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::VectorizerValueMap::getVectorValue(), getVFSEntries(), llvm::slpvectorizer::BoUpSLP::VLOperands::getVL(), llvm::VPlan::getVPValue(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithAllocSizeArgs(), llvm::Attribute::getWithDereferenceableBytes(), llvm::Attribute::getWithDereferenceableOrNullBytes(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::Attribute::getWithStackAlignment(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ConstantExpr::getZExt(), llvm::codeview::GloballyHashedType::GloballyHashedType(), llvm::GlobalsAAResult::GlobalsAAResult(), llvm::GlobalsMetadata::GlobalsMetadata(), llvm::GlobalValueSummary::GlobalValueSummary(), llvm::GlobalVariable::GlobalVariable(), llvm::User::growHungoffUses(), llvm::ARM::WinEH::RuntimeFunction::H(), HandleCallsInBlockInlinedThroughInvoke(), llvm::CrashRecoveryContext::HandleCrash(), llvm::ValueAsMetadata::handleDeletion(), handleFinalSuspend(), HandleInlinedEHPad(), handleMemIntrinsicPtrUse(), llvm::Constant::handleOperandChange(), llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), HandlePrefixedOrGroupedOption(), llvm::ValueAsMetadata::handleRAUW(), llvm::VPRecipeBuilder::handleReplication(), llvm::mdconst::hasa(), llvm::AliasSummary::hasAliasee(), llvm::Instruction::hasAllowContract(), llvm::Instruction::hasAllowReassoc(), llvm::Instruction::hasAllowReciprocal(), HasAnyUnrollPragma(), llvm::Instruction::hasApproxFunc(), llvm::Instruction::hasAtomicLoad(), llvm::Instruction::hasAtomicStore(), llvm::AttrBuilder::hasAttributes(), llvm::DWARFDie::hasChildren(), llvm::DWARFDebugLine::Prologue::hasFileAtIndex(), llvm::CallBase::hasFnAttr(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), llvm::pdb::hashTagRecord(), hasMoreThanOneUseOtherThanLLVMUsed(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::Instruction::hasNoSignedZeros(), llvm::pdb::PDBFile::hasPDBInjectedSourceStream(), llvm::pdb::PDBFile::hasPDBStringTable(), llvm::VectorizerValueMap::hasScalarValue(), hasUseOtherThanLLVMUsed(), llvm::VectorizerValueMap::hasVectorValue(), llvm::haveNoCommonBitsSet(), haveSameOperands(), haveSameSpecialState(), hoistLoopToNewParent(), llvm::hoistRegion(), HoistThenElseCodeToIf(), hoistValue(), llvm::HUerrBound(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::identifyKnownAlignedObject(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::identifyKnownObject(), llvm::IDFCalculator< IsPostDom >::IDFCalculator(), llvm::FunctionImporter::importFunctions(), incorporateNewSCCRange(), IncorporateWeight(), llvm::vfs::directory_iterator::increment(), llvm::vfs::recursive_directory_iterator::increment(), llvm::MemoryBuffer::init(), llvm::Timer::init(), llvm::codeview::DebugInlineeLinesSubsectionRef::initialize(), initialize(), INITIALIZE_PASS(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::pdb::UDTLayoutBase::initializeChildren(), initializeWorkList(), llvm::InlineFunction(), InlineHistoryIncludes(), inlineLoopID(), llvm::RuntimePointerChecking::insert(), llvm::VPBasicBlock::insert(), llvm::VPBlockUtils::insertBlockAfter(), llvm::insertDebugValuesForPHIs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), llvm::LazyCallGraph::insertEdge(), llvm::DominatorTreeBase< NodeT, IsPostDom >::insertEdge(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), insertInteger(), llvm::LazyCallGraph::RefSCC::insertInternalRefEdge(), llvm::BasicBlock::insertInto(), insertLifetimeMarkersSurroundingCall(), llvm::InterleaveGroup< InstTy >::insertMember(), llvm::InstCombiner::InsertNewInstBefore(), llvm::LazyCallGraph::RefSCC::insertOutgoingEdge(), insertParsePoints(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::codeview::AppendingTypeTableBuilder::insertRecord(), llvm::codeview::GlobalTypeTableBuilder::insertRecord(), llvm::codeview::MergingTypeTableBuilder::insertRecord(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), insertRelocationStores(), insertRematerializationStores(), InsertSafepointPoll(), insertSinCosCall(), insertSpills(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), llvm::VPBlockUtils::insertTwoBlocksAfter(), insertUniqueBackedgeBlock(), insertVector(), llvm::install_bad_alloc_error_handler(), llvm::install_fatal_error_handler(), llvm::install_out_of_memory_new_handler(), llvm::Instruction::Instruction(), instructionClobbersQuery(), instrumentOneFunc(), inSubLoop(), llvm::GVNExpression::AggregateValueExpression::int_op_push_back(), llvm::IntAttributeImpl::IntAttributeImpl(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::InterleaveGroup< InstTy >::InterleaveGroup(), llvm::interpretDecimal(), llvm::intersectAccessGroups(), llvm::DWARFAddressRange::intersects(), IntersectSignedRange(), IntersectUnsignedRange(), llvm::ConstantRange::intersectWith(), llvm::IntervalPartition::IntervalPartition(), llvm::IntToPtrInst::IntToPtrInst(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), invokeFunctionPass(), IsAcceptableTarget(), isAligned(), llvm::KnownBits::isAllOnes(), isAMCompletelyFolded(), llvm::Loop::isAnnotatedParallel(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isArgOperand(), llvm::CallBase::isArgOperand(), llvm::VPBlockUtils::isBackEdge(), llvm::DWARFDebugRangeList::RangeListEntry::isBaseAddressSelectionEntry(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isBundleOperand(), llvm::CallBase::isBundleOperand(), llvm::isBytewiseValue(), llvm::LazyCallGraph::Edge::isCall(), llvm::AbstractCallSite::isCallee(), isCondRelevantToAnyCallArgument(), llvm::KnownBits::isConstant(), isConstantFalse(), IsConstantOne(), llvm::isCriticalEdge(), llvm::CallBase::isDataOperand(), llvm::LazyCallGraph::Node::isDead(), llvm::GlobalValue::isDeclaration(), llvm::CastInst::isEliminableCastPair(), isEpilogProfitable(), llvm::DenseMapInfo< ValueInfo >::isEqual(), isEqualImpl(), isExplicitVecOuterLoop(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::Instruction::isFast(), llvm::InductionDescriptor::isFPInductionPHI(), isGEPKnownNonNull(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::isImpliedByDomCondition(), isImpliedCondAndOr(), llvm::isImpliedCondition(), llvm::InductionDescriptor::isInductionPHI(), llvm::BlockFrequencyInfo::isIrrLoopHeader(), llvm::isKnownNegation(), llvm::isKnownNeverNaN(), isKnownNonNullFromDominatingCondition(), isKnownToBeAPowerOfTwo(), llvm::ScalarEvolution::isKnownViaInduction(), llvm::BasicBlock::isLegalToHoistInto(), llvm::isLegalToPromote(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopCounter(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), isLoopNeverExecuted(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), isMinMaxWithLoads(), llvm::ScalarEvolution::isMonotonicPredicate(), isMultiple(), isObjectDereferencedInBlock(), isOnlyCopiedFromConstantGlobal(), isOnlyReachableViaThisEdge(), llvm::isOverflowIntrinsicNoWrap(), isOverwrite(), llvm::FullDependence::isPeelFirst(), llvm::FullDependence::isPeelLast(), isPointerValueDeadOnEntryToFunction(), llvm::isPotentiallyReachable(), isPredicatedOnPHI(), isProfitableChain(), isProfitableToFoldUnconditional(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::ValueInfo::isReadOnly(), isReturnNonNull(), llvm::ShuffleVectorInst::isReverseMask(), isSafeAndProfitableToSpeculateAroundPHI(), isSafeDecreasingBound(), isSafeIncreasingBound(), llvm::isSafeToLoadUnconditionally(), isSafeToPromoteArgument(), isSafeToSpeculatePHIUsers(), isSafeToTruncateWideIVType(), llvm::FullDependence::isScalar(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), isSCCHeader(), llvm::ShuffleVectorInst::isSelectMask(), isSignedMinMaxClamp(), llvm::BasicBlockEdge::isSingleEdge(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleSourceMaskImpl(), llvm::ConstantRange::isSizeLargerThan(), llvm::ConstantRange::isSizeStrictlySmallerThan(), llvm::ImplicitControlFlowTracking::isSpecialInstruction(), llvm::isSplatValue(), llvm::FullDependence::isSplitable(), llvm::ShuffleVectorInst::isTransposeMask(), llvm::slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), isTruePredicate(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::isUniformLoop(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), AANoSyncFunction::isVolatile(), llvm::ValueInfo::isWriteOnly(), llvm::KnownBits::isZero(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::SyncDependenceAnalysis::join_blocks(), llvm::sys::fs::TempFile::keep(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front(), KnuthDiv(), llvm::ARM::WinEH::RuntimeFunction::L(), llvm::cfg::LegalizeUpdates(), llvm::vfs::recursive_directory_iterator::level(), llvm::codeview::limitSymbolArrayToScope(), llvm::line_iterator::line_iterator(), LinearizeExprTree(), llvm::lintFunction(), llvm::LLT::LLT(), llvm_map_to_intrinsic_id(), llvm_regerror(), llvm_regexec(), llvm::LLVMContext::LLVMContext(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetMetadata(), LLVMGetOperand(), LLVMInsertExistingBasicBlockAfterInsertBlock(), LLVMMDNodeInContext(), llvm::LoadInst::LoadInst(), llvm::MemorySSA::locallyDominates(), llvm::sys::SmartMutex< mt_only >::lock(), llvm::sys::SmartRWMutex< mt_only >::lock(), llvm::unique_lock< MutexT >::lock(), llvm::FileError::log(), llvm::BlockAddress::lookup(), llvm::sys::DynamicLibrary::HandleSet::Lookup(), llvm::DWARFDebugNames::Entry::lookup(), llvm::AppleAcceleratorTable::Entry::lookup(), llvm::GVN::ValueTable::lookup(), llvm::vfs::lookupInMemoryNode(), llvm::Function::lookupIntrinsicID(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), llvm::LoopVersioning::LoopVersioning(), lowBitMask(), LowerNegateToMultiply(), llvm::lowerObjectSizeCall(), llvm::msf::MSFLayout::mainFpmBlock(), makeAllConstantUsesInstructions(), llvm::ConstantRange::makeExactICmpRegion(), llvm::makeFollowupLoopID(), llvm::ConstantRange::makeGuaranteedNoWrapRegion(), llvm::opt::InputArgList::MakeIndex(), makeMergeable(), llvm::ContextAndReplaceableUses::makeReplaceable(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::coro::LowererBase::makeSubFnCall(), makeVisible(), llvm::AbstractAttribute::manifest(), AAReturnedValuesImpl::manifest(), llvm::json::ObjectMapper::map(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), llvm::DivergenceAnalysis::markDivergent(), llvm::LPPassManager::markLoopAsDeleted(), llvm::LPMUpdater::markLoopAsDeleted(), llvm::SCEVWrapPredicate::maskFlags(), llvm::maskTrailingOnes(), llvm::PatternMatch::cst_pred_ty< Predicate >::match(), llvm::PatternMatch::cstfp_pred_ty< Predicate >::match(), llvm::FileCheckPattern::match(), llvm::Regex::match(), matchAccessTags(), matchDeMorgansLaws(), matchIntrinsicType(), matchMinMaxOfMinMax(), matchPairwiseReductionAtLevel(), llvm::ScaledNumbers::matchScales(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), llvm::maxIntN(), llvm::maxUIntN(), llvm::CFLAndersAAResult::FunctionInfo::mayAlias(), mayBeAccessToSubobjectOf(), mayDivideByZero(), mccase(), mcinvert(), meetBDVState(), meetBDVStateImpl(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), memoryIsNotModifiedBetween(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::ValueLatticeElement::mergeIn(), llvm::AliasSet::mergeSetIn(), llvm::minIntN(), llvm::ConstantDataArraySlice::move(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), llvm::MemorySSAUpdater::moveAllAfterSpliceBlocks(), llvm::Instruction::moveBefore(), moveLCSSAPhis(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::MemorySSA::moveTo(), llvm::LoopBase< BlockT, LoopT >::moveToHeader(), llvm::DIType::mutate(), llvm::sys::MutexImpl::MutexImpl(), llvm::sys::path::native(), llvm::pdb::NativeTypePointer::NativeTypePointer(), needsLFTR(), negateICmpIfUsedByBranchOrSelectOnly(), nonnewline(), llvm::BlockFrequencyInfoImplBase::Distribution::normalize(), normalizeForInvokeSafepoint(), llvm::cflaa::StratifiedSetsBuilder< T >::noteAttributes(), llvm::json::OStream::objectEnd(), llvm::json::ObjectKey::ObjectKey(), llvm::OnDiskChainedHashTable< Info >::OnDiskChainedHashTable(), llvm::GVNExpression::BasicExpression::op_push_back(), llvm::GlobalVariable::operator delete(), llvm::User::operator delete(), operator new(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator ValueT *(), llvm::operator!=(), FusionCandidateCompare::operator()(), llvm::AliasSet::iterator::operator*(), llvm::memoryaccess_def_iterator_base< T >::operator*(), llvm::upward_defs_iterator::operator*(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator*(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator*(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator*(), llvm::pdb::HashTableIterator< ValueT >::operator*(), llvm::PredIterator< Ptr, USE_iterator >::operator*(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator*(), llvm::TargetRegistry::iterator::operator*(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator*(), llvm::BranchProbability::operator*=(), llvm::AliasSet::iterator::operator++(), llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++(), llvm::LazyCallGraph::postorder_ref_scc_iterator::operator++(), llvm::memoryaccess_def_iterator_base< T >::operator++(), llvm::upward_defs_iterator::operator++(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::BasicBlock::phi_iterator_impl< PHINodeT, BBIteratorT >::operator++(), llvm::PredIterator< Ptr, USE_iterator >::operator++(), llvm::sys::path::const_iterator::operator++(), llvm::TargetRegistry::iterator::operator++(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator++(), llvm::yaml::document_iterator::operator++(), llvm::BranchProbability::operator+=(), llvm::SuccIterator< InstructionT, BlockT >::operator+=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator+=(), llvm::pdb::DbiModuleSourceFilesIterator::operator+=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator-(), llvm::pdb::DbiModuleSourceFilesIterator::operator-(), llvm::FixedStreamArrayIterator< T >::operator-(), llvm::SuccIterator< InstructionT, BlockT >::operator-(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator--(), llvm::BranchProbability::operator-=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator-=(), llvm::pdb::DbiModuleSourceFilesIterator::operator-=(), llvm::FixedStreamArrayIterator< T >::operator-=(), llvm::codeview::TypeIndex::operator-=(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator->(), llvm::BranchProbability::operator/=(), llvm::BranchProbability::operator<(), llvm::AttributeImpl::operator<(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator<(), llvm::pdb::DbiModuleSourceFilesIterator::operator<(), llvm::FixedStreamArrayIterator< T >::operator<(), llvm::opt::operator<(), llvm::SuccIterator< InstructionT, BlockT >::operator<(), llvm::ValID::operator<(), llvm::operator<(), llvm::raw_ostream::operator<<(), llvm::sys::operator<<(), llvm::BranchProbability::operator<=(), llvm::Timer::operator=(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator==(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::operator==(), llvm::pdb::DbiModuleSourceFilesIterator::operator==(), llvm::FixedStreamArrayIterator< T >::operator==(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator==(), AllocaSlices::partition_iterator::operator==(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator==(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator==(), llvm::operator==(), llvm::BranchProbability::operator>(), llvm::BranchProbability::operator>=(), llvm::BlockFrequency::operator>>=(), llvm::CallGraph::operator[](), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::gsym::AddressRanges::operator[](), llvm::FixedStreamArray< T >::operator[](), llvm::CallGraphNode::operator[](), llvm::cl::applicator< MiscFlags >::opt(), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfLoads(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::opt::Option::Option(), llvm::opt::OptTable::OptTable(), othercase(), llvm::RegionBase< Tr >::outermostLoopInRegion(), llvm::outs(), p_bracket(), p_ere(), p_ere_exp(), p_simp_re(), packAllocSizeArgs(), llvm::ARM::WinEH::RuntimeFunction::PackedUnwindData(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), llvm::CallBase::paramHasAttr(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DWARFDebugLine::LineTable::parse(), llvm::LocationMetadata::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::opt::OptTable::ParseArgs(), llvm::cl::ParseEnvironmentOptions(), parseInt(), llvm::LLParser::ParseMDField(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::detail::HelperFunctions::parseNumericPrecision(), llvm::formatv_object_base::parseReplacementItem(), llvm::pdb::PDBFile::parseStreamData(), parseV5DirFileTables(), llvm::partAsHex(), llvm::BinaryStreamReader::peek(), llvm::yaml::Scanner::peekNext(), llvm::peelLoop(), PerformHeapAllocSRoA(), llvm::PGOOptions::PGOOptions(), PhiHasDebugValue(), llvm::PHITransAddr::PHITranslateValue(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LLT::pointer(), llvm::PointerMayBeCaptured(), llvm::PointerMayBeCapturedBefore(), llvm::BasicAAResult::pointsToConstantMemory(), llvm::sys::fs::recursive_directory_iterator::pop(), llvm::CallBase::populateBundleOperandInfos(), populateDependencyMatrix(), llvm::LazyCallGraph::postorder_ref_scc_begin(), llvm::LazyCallGraph::postorder_ref_scc_end(), llvm::powerOf5(), predictValueUseListOrder(), predictValueUseListOrderImpl(), prepareForSplit(), llvm::PrepareToSplitEntryBlock(), llvm::DIExpression::prependOpcodes(), llvm::format_object_base::print(), llvm::BranchProbabilityInfo::print(), llvm::LLT::print(), llvm::DWARFExpression::Operation::print(), llvm::cl::Option::printHelpStr(), llvm::SourceMgr::PrintIncludeStack(), llvm::printLLVMNameWithoutPrefix(), llvm::SourceMgr::PrintMessage(), PrintNoMatch(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::JumpThreadingPass::ProcessBlock(), llvm::JumpThreadingPass::ProcessBranchOnXOR(), processCallSite(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), llvm::JumpThreadingPass::ProcessThreadableEdges(), processUDivOrURem(), processUMulZExtIdiom(), processWorkListItem(), llvm::promoteCall(), llvm::promoteLoopAccessesToScalars(), propagateAttributesToRefs(), PropagateConstantsIntoArguments(), ProvideOption(), llvm::PtrToIntInst::PtrToIntInst(), llvm::PMStack::push(), llvm::raw_pwrite_stream::pwrite(), llvm::CFLAndersAAResult::query(), llvm::CFLSteensAAResult::query(), llvm::ARM::WinEH::RuntimeFunction::R(), rangeMetadataExcludesValue(), llvm::BinaryStreamReader::readArray(), llvm::support::endian::readAtBitAlignment(), llvm::FileCheck::ReadCheckFile(), llvm::BinaryStreamReader::readCString(), llvm::sys::RWMutexImpl::reader_acquire(), llvm::sys::RWMutexImpl::reader_release(), llvm::readExponent(), llvm::OnDiskChainedHashTable< Info >::readNumBucketsAndEntries(), llvm::pdb::ModuleDebugStreamRef::readSymbolAtOffset(), reassociateFCmps(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), rebuildLoopAfterUnswitch(), recomputeLiveInValues(), recomputeLoopBlockSet(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::ImportedFunctionsInliningStatistics::recordInline(), llvm::InnerLoopVectorizer::recordVectorLoopValueForInductionCast(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), redirectValuesFromPredecessorsToPhi(), ReduceSwitchRange(), llvm::ARM::WinEH::RuntimeFunction::Reg(), llvm::AssumptionCache::registerAssumption(), llvm::ManagedStaticBase::RegisterManagedStatic(), llvm::TargetRegistry::RegisterTarget(), llvm::sys::MutexImpl::release(), llvm::pdb::PDBStringTable::reload(), llvm::pdb::InjectedSourceStream::reload(), relocationViaAlloca(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::RemarkStreamer::RemarkStreamer(), rematerializeLiveValues(), llvm::ConstantUniqueMap< ConstantClass >::remove(), llvm::AttrBuilder::removeAttribute(), llvm::AttributeList::removeAttribute(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::removeBlock(), llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop(), removeBlockFromLoops(), llvm::MemorySSAUpdater::removeBlocks(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::SwitchInst::removeCase(), llvm::SwitchInstProfUpdateWrapper::removeCase(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), RemoveDeadConstant(), llvm::LazyCallGraph::removeDeadFunction(), llvm::IndirectBrInst::removeDestination(), llvm::LazyCallGraph::removeEdge(), removeEmptyCleanup(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::removeFromFrontier(), llvm::MemorySSA::removeFromLookups(), RemoveFromReverseMap(), llvm::ValueHandleBase::RemoveFromUseList(), llvm::CallGraph::removeFunctionFromModule(), llvm::PHINode::removeIncomingValue(), RemoveInstInputs(), llvm::MemoryDependenceResults::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::cl::parser< DataType >::removeLiteralOption(), llvm::LoopInfoBase< BlockT, LoopT >::removeLoop(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::CallGraphNode::removeOneAbstractEdgeTo(), llvm::LazyCallGraph::RefSCC::removeOutgoingEdge(), llvm::CallBase::removeParamAttr(), removePartiallyOverlappedStores(), llvm::BasicBlock::removePredecessor(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), removeTriviallyEmptyRange(), llvm::removeUnreachableBlocks(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), repeat(), replace(), llvm::replaceAllDbgUsesWith(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::MDNode::replaceAllUsesWith(), llvm::replaceAndRecursivelySimplify(), llvm::CallGraphNode::replaceCallEdge(), llvm::LoopBase< BasicBlock, Loop >::replaceChildLoopWith(), llvm::replaceDbgDeclare(), replaceDevirtTrigger(), replaceDominatedUsesWith(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::DIMacroFile::replaceElements(), llvm::DICompositeType::replaceElements(), llvm::RegionBase< Tr >::replaceExit(), ReplaceFoldableUses(), llvm::PHINode::replaceIncomingBlockWith(), llvm::ReplaceInstWithInst(), replaceLoopInvariantUses(), llvm::CallGraphSCC::ReplaceNode(), llvm::LazyCallGraph::RefSCC::replaceNodeFunction(), llvm::replaceNonLocalUsesWith(), replaceOneDbgValueForAlloca(), llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace(), llvm::User::replaceUsesOfWith(), llvm::Value::replaceUsesOutsideBlock(), llvm::DistinctMDOperandPlaceholder::replaceUseWith(), replaceWithConstant(), llvm::report_fatal_error(), llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), llvm::LoopBase< BlockT, LoopT >::reserveBlocks(), llvm::VectorizerValueMap::resetScalarValue(), llvm::VectorizerValueMap::resetVectorValue(), llvm::MDNode::resolve(), llvm::MDNode::resolveCycles(), resolveFwdRef(), llvm::ARM::WinEH::RuntimeFunction::Ret(), llvm::DIBuilder::retainType(), llvm::MetadataTracking::retrack(), reuseTableCompare(), llvm::LoopBase< BlockT, LoopT >::reverseBlock(), llvm::InnerLoopVectorizer::reverseVector(), llvm::SSAUpdaterBulk::RewriteAllUses(), RewriteHeapSROALoadUser(), rewriteMaterializableInstructions(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHINodesForUnswitchedExitBlock(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::RNSuccIterator(), llvm::ThinLTOCodeGenerator::run(), llvm::LoadAndStorePromoter::run(), llvm::ReassociatePass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::FunctionToLoopPassAdaptor< LoopPassT >::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::ArgumentPromotionPass::run(), llvm::InlinerPass::run(), llvm::DevirtSCCRepeatedPass< PassT >::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run(), llvm::SyntheticCountsPropagation::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), runImpl(), llvm::JumpThreadingPass::runImpl(), llvm::runIPSCCP(), llvm::IntervalPartition::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::CrashRecoveryContext::RunSafely(), llvm::sys::RWMutexImpl::RWMutexImpl(), llvm::LLT::scalar(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::detail::scalbn(), scale(), llvm::scaleBranchCount(), llvm::CFLSteensAAResult::scan(), scanOneBB(), llvm::SCEVEqualPredicate::SCEVEqualPredicate(), llvm::SCEVMinMaxExpr::SCEVMinMaxExpr(), llvm::PMTopLevelManager::schedulePass(), llvm::raw_fd_ostream::seek(), selectIncomingValueForBlock(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), separateNestedLoop(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes(), llvm::GlobalAlias::setAliasee(), llvm::GlobalObject::setAlignment(), llvm::AllocaInst::setAlignment(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallBase::setArgOperand(), llvm::cl::Option::setArgStr(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setArgument(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), llvm::wholeprogramdevirt::AccumBitVector::setBE(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes(), llvm::LoopVectorizationPlanner::setBestPlan(), llvm::wholeprogramdevirt::AccumBitVector::setBit(), llvm::BlockFrequencyInfo::setBlockFreq(), llvm::BlockFrequencyInfoImplBase::setBlockFreq(), llvm::BlockFrequencyInfo::setBlockFreqAndScale(), llvm::StructType::setBody(), setBranchWeights(), llvm::CallBase::setCalledFunction(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::setCalledFunction(), llvm::Function::setCallingConv(), llvm::CallBase::setCallingConv(), llvm::CatchReturnInst::setCatchPad(), llvm::CatchPadInst::setCatchSwitch(), llvm::CleanupReturnInst::setCleanupPad(), llvm::BranchInst::setCondition(), setCoroInfo(), llvm::CoroIdInst::setCoroutineSelf(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::Check::FileCheckType::setCount(), llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory(), llvm::MemIntrinsicBase< Derived >::setDest(), llvm::DWARFUnitHeader::setDWOId(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), llvm::VPRegionBlock::setEntry(), llvm::Function::setEntryCount(), llvm::VPRegionBlock::setExit(), llvm::AtomicCmpXchgInst::setFailureOrdering(), llvm::Instruction::setFast(), llvm::Instruction::setFastMathFlags(), llvm::SCEVWrapPredicate::setFlags(), llvm::GlobalObject::setGlobalObjectSubClassData(), llvm::GlobalValue::setGlobalValueSubClassData(), llvm::User::setGlobalVariableNumOperands(), llvm::Instruction::setHasAllowReassoc(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasApproxFunc(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::DomTreeNodeBase< NodeT >::setIDom(), llvm::MemoryPhi::setIncomingBlock(), llvm::PHINode::setIncomingBlock(), llvm::MemoryPhi::setIncomingValue(), llvm::PHINode::setIncomingValue(), llvm::PHINode::setIncomingValueForBlock(), llvm::GlobalVariable::setInitializer(), setInsertionPoint(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SCEVExpander::setInsertPoint(), llvm::VPBuilder::setInsertPoint(), llvm::Instruction::setInstructionSubclassData(), llvm::SCEVExpander::setIVIncInsertPos(), llvm::PMTopLevelManager::setLastUser(), llvm::wholeprogramdevirt::AccumBitVector::setLE(), llvm::MemIntrinsicBase< Derived >::setLength(), setLimitsForBinOp(), llvm::Loop::setLoopID(), llvm::Module::setMaterializer(), setMemoryPhiValueForBlock(), llvm::Instruction::setMetadata(), llvm::LTOCodeGenerator::setModule(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), llvm::User::setNumHungOffUseOperands(), llvm::VPBlockBase::setOneSuccessor(), llvm::NamedMDNode::setOperand(), llvm::MDNode::setOperand(), llvm::User::setOperand(), llvm::GVNExpression::BasicExpression::setOperand(), llvm::AtomicRMWInst::setOrdering(), llvm::LoopBase< BlockT, LoopT >::setParentLoop(), llvm::FuncletPadInst::setParentPad(), llvm::SCEVExpander::setPostInc(), llvm::VPBlockBase::setPredecessors(), llvm::setProfMetadata(), llvm::Instruction::setProfWeight(), llvm::ValueInfo::setReadOnly(), setRetNonNull(), llvm::VectorizerValueMap::setScalarValue(), llvm::MemTransferBase< BaseCL >::setSource(), llvm::Type::setSubclassData(), llvm::CatchReturnInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::CallBrInst::setSuccessor(), llvm::BranchInst::setSuccessor(), llvm::SwitchInst::setSuccessor(), llvm::CatchSwitchInst::setSuccessor(), llvm::AtomicCmpXchgInst::setSuccessOrdering(), llvm::GlobalValue::setThreadLocalMode(), llvm::VPBlockBase::setTwoSuccessors(), llvm::VPValue::setUnderlyingValue(), llvm::CleanupReturnInst::setUnwindDest(), llvm::CatchSwitchInst::setUnwindDest(), llvm::SwitchInst::CaseHandle::setValue(), llvm::FileCheckNumericVariable::setValue(), llvm::MemSetBase< BaseCL >::setValue(), llvm::Value::setValueName(), llvm::VectorizerValueMap::setVectorValue(), llvm::GlobalValue::setVisibility(), llvm::GlobalVarSummary::setVTableFuncs(), llvm::LoopVectorizationCostModel::setWideningDecision(), llvm::ValueInfo::setWriteOnly(), llvm::SExtInst::SExtInst(), shiftRightAndRound(), shouldApply(), llvm::shouldOptimizeForSize(), llvm::OptBisect::shouldRunPass(), shouldSplit(), shouldSplitOnPredicatedArgument(), shouldUseMmap(), ShrinkDemandedConstant(), shrinkInsertElt(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ConstantRange::signExtend(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::codeview::TypeIndex::simpleTypeName(), SimplifyAssociativeBinOp(), SimplifyBSwap(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), SimplifyFCmpInst(), SimplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoop(), simplifyLoopInst(), simplifyOneLoop(), llvm::JumpThreadingPass::SimplifyPartiallyRedundantLoad(), SimplifyShuffleVectorInst(), simplifyX86addcarry(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), sink(), sinkInstruction(), sinkLastInstruction(), sinkLoopInvariantInstructions(), llvm::sinkRegion(), sinkThroughTriviallyReplaceablePHI(), llvm::SIToFPInst::SIToFPInst(), llvm::PooledStringPtr::size(), llvm::sroa::Partition::size(), llvm::yaml::skip(), llvm::DWARFDebugLine::SectionParser::skip(), llvm::skipLeadingZeroesAndAnyDot(), llvm::codeview::CodeViewRecordIO::skipPadding(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), slotForIndex(), llvm::SMFixIt::SMFixIt(), llvm::SMRange::SMRange(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecRange(), llvm::sortPtrAccesses(), llvm::Value::sortUseList(), speculatePHIs(), speculateSelectInstLoads(), SpeculativelyExecuteBB(), split(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), llvm::BinaryStreamWriter::split(), llvm::BinaryStreamReader::split(), llvm::BasicBlock::splitBasicBlock(), llvm::SplitBlockPredecessors(), splitCallSite(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), llvm::SplitIndirectBrCriticalEdges(), llvm::ScalarEvolution::SplitIntoInitAndPostInc(), llvm::SplitLandingPadPredecessors(), llvm::formatv_object_base::splitLiteralAndReplacement(), splitPredecessorsOfLoopExit(), SRAGlobal(), llvm::ARM::WinEH::RuntimeFunction::StackAdjust(), StackMallocSizeClass(), llvm::Timer::startTimer(), llvm::Function::stealArgumentListFrom(), llvm::CallGraphNode::stealCalledFunctionsFrom(), llvm::Timer::stopTimer(), llvm::MDNode::storeDistinctInContext(), StrengthenNoWrapFlags(), llvm::Value::stripAndAccumulateConstantOffsets(), stripAndComputeConstantOffsets(), stripDebugLocFromLoopID(), stripNonValidData(), stripTrailingZeros(), llvm::VarStreamArray< ValueType, Extractor >::substream(), llvm::ConstantRange::subtract(), llvm::BranchInst::swapSuccessors(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToRef(), SwitchToLookupTable(), llvm::IRMover::IdentifiedStructTypeSet::switchToNonOpaque(), switchToSelect(), llvm::LazyCallGraph::RefSCC::switchTrivialInternalEdgeToRef(), llvm::Value::takeName(), llvm::ContextAndReplaceableUses::takeReplaceableUses(), llvm::lto::thinBackend(), llvm::thinLTOInternalizeModule(), llvm::thinLTOResolvePrevailingInModule(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), ThreadCmpOverPHI(), ThreadCmpOverSelect(), llvm::JumpThreadingPass::ThreadGuard(), llvm::Timer::Timer(), llvm::TimerGroup::TimerGroup(), llvm::timeTraceProfilerInitialize(), llvm::timeTraceProfilerWrite(), llvm::codeview::TypeIndex::toArrayIndex(), llvm::ScaledNumber< DigitsT >::toInt(), toStringAPFloat(), llvm::totalExponent(), toUTF8(), llvm::trailingHexadecimalFraction(), llvm::ConstantRange::truncate(), llvm::TruncInst::TruncInst(), llvm::sys::MutexImpl::tryacquire(), llvm::codeview::LazyRandomTypeCollection::tryGetType(), llvm::VPRecipeBuilder::tryToBlend(), llvm::VPRecipeBuilder::tryToInterleaveMemory(), TryToMergeLandingPad(), tryToMoveFreeBeforeNullTest(), tryToReplaceWithConstant(), tryToShortenBegin(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSinkInstruction(), llvm::VPRecipeBuilder::tryToWiden(), llvm::VPRecipeBuilder::tryToWidenMemory(), TurnSwitchRangeIntoICmp(), turnToExplicitForm(), llvm::codeview::TypeServer2Record::TypeServer2Record(), TypeSizeToSizeIndex(), TypeToFloatSemantics(), llvm::UIToFPInst::UIToFPInst(), llvm::ulpsFromBoundary(), llvm::sys::UnicodeCharSet::UnicodeCharSet(), llvm::ConstantRange::unionWith(), llvm::sys::SmartMutex< mt_only >::unlock(), llvm::sys::SmartRWMutex< mt_only >::unlock(), llvm::unique_lock< MutexT >::unlock(), llvm::sys::SmartRWMutex< mt_only >::unlock_shared(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), unpackLoadToAggregate(), UnrollAndJamCountPragmaValue(), llvm::UnrollAndJamLoop(), UnrollCountPragmaValue(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::MetadataTracking::untrack(), llvm::InnerLoopVectorizer::updateAnalysis(), UpdateAnalysisInformation(), llvm::updateCGAndAnalysisManagerForFunctionPass(), llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), llvm::MemorySSAUpdater::updateForClonedLoop(), AAReturnedValuesImpl::updateImpl(), AANonNullArgument::updateImpl(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), updatePhiNodes(), updatePostorderSequenceForEdgeInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), updateSuccessor(), llvm::UpgradeCallsToIntrinsic(), llvm::UpgradeIntrinsicCall(), llvm::UpgradeIntrinsicFunction(), UpgradeIntrinsicFunction1(), upgradeLoopTag(), UpgradeX86ALIGNIntrinsics(), llvm::User::User(), llvm::ValID::ValID(), llvm::json::Value::Value(), llvm::Value::Value(), llvm::ValueAsMetadata::ValueAsMetadata(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::LLT::vector(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::StatepointBase< FunTy, InstructionTy, ValueTy, CallBaseTy >::verify(), FusionCandidate::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::PostDominatorTreeWrapperPass::verifyAnalysis(), llvm::DominatorTreeWrapperPass::verifyAnalysis(), verifyBlocksInRegion(), llvm::MemorySSA::verifyDefUses(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::MemorySSA::verifyDomination(), llvm::MemorySSA::verifyDominationNumbers(), llvm::VPlanVerifier::verifyHierarchicalCFG(), llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::MemorySSA::verifyOrdering(), verifyRegion(), llvm::GVN::ValueTable::verifyRemoved(), llvm::LoopVersioning::versionLoop(), viewRegionInfo(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::SCEVRewriteVisitor< SC >::visit(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAtomicRMWInst(), llvm::InstCombiner::visitCallInst(), llvm::InstVisitor< SubClass, RetTy >::visitCallSite(), visitDomSubTree(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), visitPHIUsersAndDepsInPostOrder(), llvm::PtrUseVisitor< DerivedT >::visitPtr(), llvm::pdb::DbiStream::visitSectionContributions(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitSwitchInst(), llvm::codeview::SymbolDeserializer::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolDeserializer::visitSymbolEnd(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::InstCombiner::visitTrunc(), llvm::codeview::TypeDeserializer::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeDeserializer::visitTypeEnd(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), llvm::InstCombiner::visitZExt(), llvm::VPBlendRecipe::VPBlendRecipe(), llvm::VPRegionBlock::VPRegionBlock(), wasEscaped(), llvm::WholeProgramDevirtPass::WholeProgramDevirtPass(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::InnerLoopVectorizer::widenIntOrFpInduction(), llvm::InnerLoopVectorizer::widenPHIInstruction(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::raw_ostream::write(), llvm::TimeTraceProfiler::Write(), WriteAsOperandInternal(), llvm::support::endian::writeAtBitAlignment(), WriteConstantInternal(), llvm::codeview::ContinuationRecordBuilder::writeMemberType(), llvm::sys::RWMutexImpl::writer_acquire(), llvm::sys::RWMutexImpl::writer_release(), writeToResolutionFile(), writeWithCommas(), llvm::reassociate::XorOpnd::XorOpnd(), llvm::InstCombineWorklist::Zap(), llvm::ConstantRange::zeroExtend(), llvm::ZExtInst::ZExtInst(), llvm::ArrayRecycler< T, Align >::~ArrayRecycler(), llvm::BasicBlock::~BasicBlock(), llvm::CallGraphNode::~CallGraphNode(), llvm::TrailingObjects< BaseTy, TrailingTys >::FixedSizeStorageOwner::~FixedSizeStorageOwner(), llvm::InlinerPass::~InlinerPass(), llvm::Instruction::~Instruction(), llvm::LazyValueInfoWrapperPass::~LazyValueInfoWrapperPass(), llvm::LLVMContextImpl::~LLVMContextImpl(), llvm::sys::MutexImpl::~MutexImpl(), llvm::json::OStream::~OStream(), llvm::PredicateInfo::~PredicateInfo(), llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry(), llvm::PrintIRInstrumentation::~PrintIRInstrumentation(), llvm::raw_ostream::~raw_ostream(), llvm::Recycler< T, Size, Align >::~Recycler(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), llvm::sys::RWMutexImpl::~RWMutexImpl(), llvm::ScalarEvolution::~ScalarEvolution(), llvm::SCEVExpander::~SCEVExpander(), llvm::StringPool::~StringPool(), llvm::TaskQueue::~TaskQueue(), llvm::sys::fs::TempFile::~TempFile(), llvm::Value::~Value(), and llvm::ValueSymbolTable::~ValueSymbolTable().
Idx()
Returns the sub type a function will return at a given Idx Should correspond to the result type of an ExtractValue instruction executed with just that one Idx (i.e. only top-level structure is considered) const
if() [1/2]
else if (ArrayType * ATy = dyn_cast< ArrayType >(RetTy)) -> getElementType()
if() [2/2]
if (StructType * STy = dyn_cast< StructType >(RetTy)) -> getElementType(Idx)
Referenced by allocset(), llvm::canTrackGlobalVariableInterprocedurally(), llvm::pdb::DbiStreamBuilder::commit(), computePointerICmp(), llvm::RangeListEntry::dump(), llvm::isSafeToUnrollAndJam(), llvm::DWARFDebugLine::LineTable::parse(), predictValueUseListOrderImpl(), llvm::CallGraph::print(), and selectCallee().
ignored()
SurveyUses This looks at all the uses of the given value Returns the Liveness deduced from the uses of this value Adds all uses that cause the result to be MaybeLive to MaybeLiveRetUses If the result is MaybeLiveUses might be modified but its content should be ignored (since it might not be complete)
Definition at line 464 of file DeadArgumentElimination.cpp.
References llvm::DeadArgumentEliminationPass::Live, llvm::DeadArgumentEliminationPass::MaybeLive, and llvm::Value::uses().
Referenced by llvm::ConstantFoldCastInstruction(), llvm::ConstantFP::get(), llvm::ConstantFP::isExactlyValue(), and WriteConstantInternal().
INITIALIZE_PASS()
INITIALIZE_PASS (DAH , "deadarghaX0r" , "Dead Argument Hacking (BUGPOINT USE ONLY; DO NOT USE)" , false , false)
createDeadArgEliminationPass - This pass removes arguments from functions which are not used by the body of the function.
Definition at line 110 of file DeadArgumentElimination.cpp.
NumRetVals()
Convenience function that returns the number of return values It returns for void functions and for functions not returning a struct It returns the number of struct elements for functions returning a struct static unsigned NumRetVals (const Function * F)
Definition at line 327 of file DeadArgumentElimination.cpp.
References F, and RetTy.
Referenced by values().
STATISTIC() [1/3]
STATISTIC (NumArgumentsEliminated , "Number of unread args removed")
STATISTIC() [2/3]
STATISTIC (NumArgumentsReplacedWithUndef , "Number of unread args replaced with undef")
STATISTIC() [3/3]
STATISTIC (NumRetValsEliminated , "Number of unused return values removed")
uses()
PropagateLiveness Given that RA is a live propagate it s liveness to any other values it uses (according to Uses)
Definition at line 709 of file DeadArgumentElimination.cpp.
References I, and llvm::DeadArgumentEliminationPass::Uses.
value()
MarkLive Mark the given return value or argument as live mark any values that are used by this value (according to Uses)
Definition at line 694 of file DeadArgumentElimination.cpp.
References llvm::dbgs(), llvm::DeadArgumentEliminationPass::LiveFunctions, llvm::DeadArgumentEliminationPass::LiveValues, and LLVM_DEBUG.
values()
MarkLive Mark the given Function as meaning that it cannot be changed in any way mark any values that are used as this function s parameters or by its return values (according to Uses)
Definition at line 679 of file DeadArgumentElimination.cpp.
References llvm::DeadArgumentEliminationPass::CreateArg(), llvm::DeadArgumentEliminationPass::CreateRet(), llvm::dbgs(), F, llvm::DeadArgumentEliminationPass::LiveFunctions, LLVM_DEBUG, and NumRetVals().
Variable Documentation
Additionally
MarkLive Mark the given return value or argument as live Additionally
Definition at line 677 of file DeadArgumentElimination.cpp.
alive
MarkLive Mark the given Function as alive
Definition at line 676 of file DeadArgumentElimination.cpp.
Idx
Returns the sub type a function will return at a given Idx Should correspond to the result type of an ExtractValue instruction executed with just that one unsigned Idx
Initial value:
{
  Type *RetTy = F->getReturnType()
Definition at line 342 of file DeadArgumentElimination.cpp.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::consthoist::ConstantCandidate::addUser(), analyzeLoopUnrollCost(), buildNew(), llvm::BuryPointer(), canReplaceGEPIdxWithZero(), llvm::CloneAndPruneIntoFromInst(), collectMultiplyFactors(), llvm::ShuffleVectorInst::commuteShuffleMask(), CompareValueComplexity(), computeAddrMap(), computeKnownBitsFromOperator(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::DeadArgumentEliminationPass::CreateArg(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstGEP1_64(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_64(), llvm::TargetFolder::CreateExtractElement(), llvm::ConstantFolder::CreateExtractElement(), llvm::NoFolder::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateGEP(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), llvm::IRBuilder< T, Inserter >::CreateInBoundsGEP(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), llvm::TargetFolder::CreateInsertElement(), llvm::ConstantFolder::CreateInsertElement(), llvm::NoFolder::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), createPHIsForSplitLoopExit(), llvm::DeadArgumentEliminationPass::CreateRet(), llvm::pdb::DbiStreamBuilder::createSectionMap(), llvm::IRBuilder< T, Inserter >::CreateStructGEP(), llvm::Module::debug_compile_units_iterator::debug_compile_units_iterator(), doPromotion(), EvaluateStoreInto(), llvm::VPlan::execute(), llvm::pdb::GSIStreamBuilder::finalizeMsfLayout(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), findBestInsertionSet(), FindPHIForConditionForwarding(), fixPhis(), fixupPHINodeForNormalDest(), fixupPHINodeForUnwindDest(), foldInsSequenceIntoSplat(), generatePoisonChecks(), llvm::ScalarEvolution::getAddExpr(), GetCaseResults(), llvm::LandingPadInst::getClause(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::StructLayout::getElementOffset(), llvm::StructLayout::getElementOffsetInBits(), llvm::ConstantAggregateZero::getElementValue(), llvm::UndefValue::getElementValue(), llvm::ConstantExpr::getExtractElement(), llvm::TargetTransformInfoImplBase::getGEPCost(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::MemoryPhi::getIncomingValueForBlock(), llvm::PHINode::getIncomingValueForBlock(), llvm::DataLayout::getIndexedOffsetInType(), llvm::ConstantExpr::getInsertElement(), llvm::MemoryDepChecker::getInstructionsForAccess(), llvm::TargetTransformInfo::getIntImmCodeSizeCost(), llvm::TargetTransformInfo::getIntImmCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), GetOffsetFromIndex(), llvm::DWARFExpression::Operation::getOperandEndOffset(), llvm::DWARFExpression::Operation::getRawOperand(), llvm::CatchSwitchInst::getSuccessor(), llvm::SuccIterator< InstructionT, BlockT >::getSuccessorIndex(), llvm::CompositeType::getTypeAtIndex(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::identifyObject(), llvm::CompositeType::indexValid(), instrumentMaskedLoadOrStore(), llvm::msf::MSFBuilder::isBlockFree(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isBundleOperand(), llvm::CallBase::isBundleOperand(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isFilter(), IsPointerOffset(), isSafeAndProfitableToSpeculateAroundPHI(), isSafePHIToSpeculate(), isShuffle(), llvm::InlineAsm::isUseOperandTiedToDef(), LLVMAddAttributeAtIndex(), LLVMAddCallSiteAttribute(), LLVMBuildStructGEP(), LLVMBuildStructGEP2(), LLVMGetAttributeCountAtIndex(), LLVMGetAttributesAtIndex(), LLVMGetCallSiteAttributeCount(), LLVMGetCallSiteAttributes(), LLVMGetCallSiteEnumAttribute(), LLVMGetCallSiteStringAttribute(), LLVMGetClause(), LLVMGetEnumAttributeAtIndex(), LLVMGetStringAttributeAtIndex(), LLVMRemoveCallSiteEnumAttribute(), LLVMRemoveCallSiteStringAttribute(), LLVMRemoveEnumAttributeAtIndex(), LLVMRemoveStringAttributeAtIndex(), llvm::Function::lookupIntrinsicID(), llvm::PatternMatch::m_ExtractElement(), llvm::PatternMatch::m_InsertElement(), matchPairwiseReduction(), matchVectorSplittingReduction(), needsLFTR(), llvm::OperandBundleUse::operandHasAttr(), llvm::Module::debug_compile_units_iterator::operator!=(), llvm::SuccIterator< InstructionT, BlockT >::operator*(), llvm::Module::debug_compile_units_iterator::operator++(), llvm::SuccIterator< InstructionT, BlockT >::operator+=(), llvm::SuccIterator< InstructionT, BlockT >::operator-(), llvm::Module::debug_compile_units_iterator::operator->(), llvm::SuccIterator< InstructionT, BlockT >::operator<(), llvm::Module::debug_compile_units_iterator::operator==(), llvm::SuccIterator< InstructionT, BlockT >::operator==(), llvm::LazyCallGraph::RefSCC::operator[](), llvm::TypeFinder::operator[](), llvm::User::OpFrom(), llvm::PointerMayBeCaptured(), llvm::pdb::readSparseBitVector(), removeEmptyCleanup(), llvm::PHINode::removeIncomingValue(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), replaceAndRecursivelySimplifyImpl(), replaceGEPIdxWithZero(), llvm::Instruction::replaceSuccessorWith(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::msf::MSFBuilder::setStreamSize(), llvm::CatchSwitchInst::setSuccessor(), simplifyAllocaArraySize(), SimplifyExtractElementInst(), llvm::SimplifyExtractElementInst(), SimplifyGEPInst(), llvm::SimplifyInsertElementInst(), llvm::simplifyLoop(), simplifyX86varShift(), SinkCommonCodeFromPredecessors(), slotForIndex(), speculatePHINodeLoads(), llvm::SuccIterator< InstructionT, BlockT >::SuccIterator(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), SwitchToLookupTable(), llvm::JumpThreadingPass::UnfoldSelectInstr(), updateOperand(), UpgradeX86ALIGNIntrinsics(), UpgradeX86IntrinsicFunction(), UpgradeX86PSLLDQIntrinsics(), UpgradeX86PSRLDQIntrinsics(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InnerLoopVectorizer::widenPHIInstruction(), llvm::raw_ostream::write_uuid(), and llvm::pdb::writeSparseBitVector().
live
MarkIfNotLive This checks Use for liveness in LiveValues If Use is not live
Definition at line 355 of file DeadArgumentElimination.cpp.
Referenced by findBasePointers().
Live
SurveyUses This looks at all the uses of the given value Returns the Liveness deduced from the uses of this value Adds all uses that cause the result to be MaybeLive to MaybeLiveRetUses If the result is Live
Definition at line 463 of file DeadArgumentElimination.cpp.
Referenced by checkBasicSSA(), insertParsePoints(), relocationViaAlloca(), and llvm::GlobalValueSummary::setLive().
MaybeLive
MarkValue This function marks the liveness of RA depending on L If L is MaybeLive
Definition at line 658 of file DeadArgumentElimination.cpp.
recursion
SurveyUse This looks at a single use of an argument or return value and determines if it should be alive or not Adds this use to MaybeLiveUses if it causes the used value to become MaybeLive RetValNum is the return value number to use when this use is used in a return instruction This is used in the recursion
Definition at line 375 of file DeadArgumentElimination.cpp.
RetTy
else return RetTy
Definition at line 351 of file DeadArgumentElimination.cpp.
Referenced by llvm::LandingPadInst::Create(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createReplaceableCompositeType(), createRetBitCast(), doPromotion(), llvm::TargetTransformInfo::getCallInstrCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost(), llvm::TargetTransformInfo::getIntrinsicCost(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), llvm::Module::getOrInsertFunction(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::FunctionType::isValidReturnType(), NumRetVals(), SimplifyFCmpInst(), llvm::SimplifyShuffleVectorInst(), SimplifyShuffleVectorInst(), simplifyX86addcarry(), and llvm::InnerLoopVectorizer::widenInstruction().
Uses
MarkValue This function marks the liveness of RA depending on L If L is it also takes all uses in MaybeLiveUses and records them in Uses
Definition at line 658 of file DeadArgumentElimination.cpp.
Referenced by addArgumentAttrs(), relocationViaAlloca(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), and llvm::ReplaceableMetadataImpl::resolveAllUses().
value
PropagateLiveness Given that RA is a live value
Definition at line 708 of file DeadArgumentElimination.cpp.
Referenced by llvm::support::endian::byte_swap(), dofwd(), llvm::pdb::DIARawSymbol::dump(), llvm::yaml::ScalarEnumerationTraits< TypeTestResolution::Kind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< WholeProgramDevirtResolution::ByArg::Kind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< WholeProgramDevirtResolution::Kind >::enumeration(), llvm::formatv_object< Tuple >::formatv_object(), llvm::cl::list_storage< DataType, bool >::insert(), llvm::sys::path::is_separator(), LLVMSetArgOperand(), p_b_symbol(), parseInt(), partLSB(), partMSB(), llvm::cl::list_storage< DataType, bool >::push_back(), llvm::readExponent(), llvm::sys::SwapByteOrder_16(), llvm::sys::SwapByteOrder_32(), llvm::sys::SwapByteOrder_64(), llvm::totalExponent(), llvm::json::OStream::value(), llvm::support::endian::write(), llvm::support::endian::write< double >(), llvm::support::endian::write< float >(), llvm::support::endian::writeAtBitAlignment(), and llvm::writeSignedDecimal().