LLVM: lib/ToolDrivers/llvm-dlltool/DlltoolDriver.cpp File Reference
DlltoolDriver.cpp File Reference
#include "llvm/ToolDrivers/llvm-dlltool/DlltoolDriver.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/COFFImportFile.h"
#include "llvm/Object/COFFModuleDefinition.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/Path.h"
#include <vector>
#include "Options.inc"
Macros
#define OPTION(_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12) OPT_##ID,
#define PREFIX(NAME, VALUE) const char *const NAME[] = VALUE;
#define OPTION(X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Functions
static std::unique_ptr< MemoryBuffer > openFile (const Twine &Path)
static MachineTypes getEmulation (StringRef S)
static std::string getImplibPath (StringRef Path)
Macro Definition Documentation
OPTION [1/2]
#define OPTION (_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12) OPT_##ID,
Definition at line 32 of file DlltoolDriver.cpp.
OPTION [2/2]
#define OPTION (X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Value:
  {X1, X2, X10,         X11,         OPT_##ID, llvm::opt::Option::KIND##Class, \
   X9, X8, OPT_##GROUP, OPT_##ALIAS, X7,       X12},
Definition at line 32 of file DlltoolDriver.cpp.
PREFIX
#define PREFIX (NAME, VALUE) const char *const NAME[] = VALUE;
Definition at line 37 of file DlltoolDriver.cpp.
Function Documentation
getEmulation()
static MachineTypes getEmulation (StringRef S) static
Definition at line 68 of file DlltoolDriver.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, and llvm::COFF::IMAGE_FILE_MACHINE_UNKNOWN.
Referenced by llvm::dlltoolDriverMain().
getImplibPath()
static std::string getImplibPath (StringRef Path) static
Definition at line 77 of file DlltoolDriver.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::sys::path::replace_extension(), and llvm::SmallString< InternalLen >::str().
Referenced by llvm::dlltoolDriverMain().
openFile()
static std::unique_ptr< MemoryBuffer > openFile (const Twine & Path) static
Definition at line 57 of file DlltoolDriver.cpp.
References llvm::errs(), llvm::ErrorOr< T >::getError(), and llvm::MemoryBuffer::getFile().
Referenced by llvm::dlltoolDriverMain().