LLVM: lib/DebugInfo/DWARF/DWARFDebugLine.cpp File Reference
DWARFDebugLine.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFRelocMap.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <utility>
Typedefs
using FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Functions
static void parseV2DirFileTables (const DWARFDataExtractor &DebugLineData, uint32_t *OffsetPtr, uint64_t EndPrologueOffset, DWARFDebugLine::ContentTypeTracker &ContentTypes, std::vector< DWARFFormValue > &IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > &FileNames)
static ContentDescriptors parseV5EntryFormat (const DWARFDataExtractor &DebugLineData, uint32_t *OffsetPtr, uint64_t EndPrologueOffset, DWARFDebugLine::ContentTypeTracker *ContentTypes)
static bool parseV5DirFileTables (const DWARFDataExtractor &DebugLineData, uint32_t *OffsetPtr, uint64_t EndPrologueOffset, const dwarf::FormParams &FormParams, const DWARFContext &Ctx, const DWARFUnit *U, DWARFDebugLine::ContentTypeTracker &ContentTypes, std::vector< DWARFFormValue > &IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > &FileNames)
static bool isPathAbsoluteOnWindowsOrPosix (const Twine &Path)
static DWARFDebugLine::SectionParser::LineToUnitMap buildLineToUnitMap (DWARFDebugLine::SectionParser::cu_range CUs, DWARFDebugLine::SectionParser::tu_range TUs)
Typedef Documentation
FileLineInfoKind
using FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Definition at line 32 of file DWARFDebugLine.cpp.
Function Documentation
buildLineToUnitMap()
static DWARFDebugLine::SectionParser::LineToUnitMap buildLineToUnitMap (DWARFDebugLine::SectionParser::cu_range CUs, DWARFDebugLine::SectionParser::tu_range TUs) static
Definition at line 1071 of file DWARFDebugLine.cpp.
References llvm::dwarf::toSectionOffset().
Referenced by llvm::DWARFDebugLine::SectionParser::SectionParser().
isPathAbsoluteOnWindowsOrPosix()
static bool isPathAbsoluteOnWindowsOrPosix (const Twine & Path) static
Definition at line 1002 of file DWARFDebugLine.cpp.
References llvm::sys::path::is_absolute(), llvm::sys::path::posix, and llvm::sys::path::windows.
Referenced by llvm::DWARFDebugLine::Prologue::getFileNameByIndex().
parseV2DirFileTables()
static void parseV2DirFileTables (const DWARFDataExtractor & DebugLineData, uint32_t * OffsetPtr, uint64_t EndPrologueOffset, DWARFDebugLine::ContentTypeTracker & ContentTypes, std::vector< DWARFFormValue > & IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > & FileNames) static
Definition at line 158 of file DWARFDebugLine.cpp.
References llvm::DWARFFormValue::createFromPValue(), llvm::StringRef::data(), llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::StringRef::empty(), llvm::DataExtractor::getCStrRef(), llvm::DataExtractor::getULEB128(), llvm::DWARFDebugLine::ContentTypeTracker::HasLength, llvm::DWARFDebugLine::ContentTypeTracker::HasModTime, llvm::DWARFDebugLine::FileNameEntry::Length, llvm::DWARFDebugLine::FileNameEntry::ModTime, llvm::DWARFDebugLine::FileNameEntry::Name, and Name.
Referenced by llvm::DWARFDebugLine::Prologue::parse().
parseV5DirFileTables()
static bool parseV5DirFileTables (const DWARFDataExtractor & DebugLineData, uint32_t * OffsetPtr, uint64_t EndPrologueOffset, const dwarf::FormParams & FormParams, const DWARFContext & Ctx, const DWARFUnit * U, DWARFDebugLine::ContentTypeTracker & ContentTypes, std::vector< DWARFFormValue > & IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > & FileNames) static
Definition at line 216 of file DWARFDebugLine.cpp.
References assert(), llvm::MD5::MD5Result::Bytes, llvm::DWARFDebugLine::FileNameEntry::Checksum, llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::DataExtractor::getU8(), I, llvm::DWARFDebugLine::FileNameEntry::Length, llvm::DWARFDebugLine::FileNameEntry::ModTime, llvm::DWARFDebugLine::FileNameEntry::Name, parseV5EntryFormat(), and llvm::DWARFDebugLine::FileNameEntry::Source.
Referenced by llvm::DWARFDebugLine::Prologue::parse().
parseV5EntryFormat()
static ContentDescriptors parseV5EntryFormat (const DWARFDataExtractor & DebugLineData, uint32_t * OffsetPtr, uint64_t EndPrologueOffset, DWARFDebugLine::ContentTypeTracker * ContentTypes) static
Definition at line 193 of file DWARFDebugLine.cpp.
References llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), I, and llvm::DWARFDebugLine::ContentTypeTracker::trackContentType().
Referenced by parseV5DirFileTables().