LLVM: lib/Support/Error.cpp File Reference
Error.cpp File Reference
#include "llvm/Support/Error.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include <system_error>
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
void llvm::logAllUnhandledErrors (Error E, raw_ostream &OS, Twine ErrorBanner={})
Log all errors (if any) in E to OS.
std::error_code llvm::inconvertibleErrorCode ()
The value returned by this function can be returned from convertToErrorCode for Error values where no sensible translation to std::error_code exists.
Error llvm::errorCodeToError (std::error_code EC)
Helper for converting an std::error_code to a Error.
std::error_code llvm::errorToErrorCode (Error Err)
Helper for converting an ECError to a std::error_code.
Error llvm::createStringError (std::error_code EC, char const *Msg)
LLVM_ATTRIBUTE_NORETURN void llvm::report_fatal_error (Error Err, bool gen_crash_diag=true)
Report a serious error, calling any installed error handler.
LLVMErrorTypeId LLVMGetErrorTypeId (LLVMErrorRef Err)
void LLVMConsumeError (LLVMErrorRef Err)
char * LLVMGetErrorMessage (LLVMErrorRef Err)
void LLVMDisposeErrorMessage (char *ErrMsg)
LLVMErrorTypeId LLVMGetStringErrorTypeId ()
Variables
static ManagedStatic< ErrorErrorCategory > ErrorErrorCat
int llvm::DisableABIBreakingChecks
Function Documentation
LLVMConsumeError()
void LLVMConsumeError (LLVMErrorRef Err)
Definition at line 155 of file Error.cpp.
References llvm::consumeError(), and llvm::unwrap().
LLVMDisposeErrorMessage()
void LLVMDisposeErrorMessage (char * ErrMsg)
Definition at line 165 of file Error.cpp.
LLVMGetErrorMessage()
char * LLVMGetErrorMessage (LLVMErrorRef Err)
Definition at line 157 of file Error.cpp.
References llvm::toString(), and llvm::unwrap().
LLVMGetErrorTypeId()
LLVMErrorTypeId LLVMGetErrorTypeId (LLVMErrorRef Err)
Definition at line 151 of file Error.cpp.
LLVMGetStringErrorTypeId()
LLVMErrorTypeId LLVMGetStringErrorTypeId ()
Definition at line 167 of file Error.cpp.
References llvm::StringError::ID.
Variable Documentation
ErrorErrorCat
ManagedStatic<ErrorErrorCategory> ErrorErrorCat static
Definition at line 49 of file Error.cpp.
Referenced by llvm::ErrorList::convertToErrorCode(), llvm::FileError::convertToErrorCode(), and llvm::inconvertibleErrorCode().