LLVM: Call Sites and Invocations
Call Sites and Invocations
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group apply to instructions that refer to call sites and invocations.
Functions
unsigned LLVMGetNumArgOperands (LLVMValueRef Instr)
Obtain the argument count for a call instruction.
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
Set the calling convention for a call instruction.
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
Obtain the calling convention for a call instruction.
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned Align)
void LLVMAddCallSiteAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef A)
unsigned LLVMGetCallSiteAttributeCount (LLVMValueRef C, LLVMAttributeIndex Idx)
void LLVMGetCallSiteAttributes (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef *Attrs)
LLVMAttributeRef LLVMGetCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
LLVMAttributeRef LLVMGetCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
void LLVMRemoveCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
void LLVMRemoveCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char *K, unsigned KLen)
LLVMTypeRef LLVMGetCalledFunctionType (LLVMValueRef C)
Obtain the function type called by this instruction.
LLVMValueRef LLVMGetCalledValue (LLVMValueRef Instr)
Obtain the pointer to the function invoked by this instruction.
LLVMBool LLVMIsTailCall (LLVMValueRef CallInst)
Obtain whether a call instruction is a tail call.
void LLVMSetTailCall (LLVMValueRef CallInst, LLVMBool IsTailCall)
Set whether a call instruction is a tail call.
LLVMBasicBlockRef LLVMGetNormalDest (LLVMValueRef InvokeInst)
Return the normal destination basic block.
LLVMBasicBlockRef LLVMGetUnwindDest (LLVMValueRef InvokeInst)
Return the unwind destination basic block.
void LLVMSetNormalDest (LLVMValueRef InvokeInst, LLVMBasicBlockRef B)
Set the normal destination basic block.
void LLVMSetUnwindDest (LLVMValueRef InvokeInst, LLVMBasicBlockRef B)
Set the unwind destination basic block.
Detailed Description
Functions in this group apply to instructions that refer to call sites and invocations.
These correspond to C++ types in the llvm::CallInst class tree.
Function Documentation
LLVMAddCallSiteAttribute()
void LLVMAddCallSiteAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef A)
Definition at line 2795 of file Core.cpp.
References A, C, Idx, and llvm::unwrap().
LLVMGetCalledFunctionType()
LLVMTypeRef LLVMGetCalledFunctionType (LLVMValueRef C)
Obtain the function type called by this instruction.
See also
llvm::CallBase::getFunctionType()
Definition at line 2842 of file Core.cpp.
References llvm::wrap().
LLVMGetCalledValue()
LLVMValueRef LLVMGetCalledValue (LLVMValueRef Instr)
Obtain the pointer to the function invoked by this instruction.
This expects an LLVMValueRef that corresponds to a llvm::CallInst or llvm::InvokeInst.
See also
llvm::CallInst::getCalledValue()
llvm::InvokeInst::getCalledValue()
Definition at line 2838 of file Core.cpp.
References llvm::wrap().
LLVMGetCallSiteAttributeCount()
unsigned LLVMGetCallSiteAttributeCount (LLVMValueRef C, LLVMAttributeIndex Idx)
Definition at line 2800 of file Core.cpp.
References C, and Idx.
LLVMGetCallSiteAttributes()
void LLVMGetCallSiteAttributes (LLVMValueRef C, LLVMAttributeIndex Idx, LLVMAttributeRef * Attrs)
Definition at line 2807 of file Core.cpp.
References A, C, Idx, and llvm::wrap().
LLVMGetCallSiteEnumAttribute()
LLVMAttributeRef LLVMGetCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2815 of file Core.cpp.
References C, getAttribute(), Idx, and llvm::wrap().
LLVMGetCallSiteStringAttribute()
LLVMAttributeRef LLVMGetCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2822 of file Core.cpp.
References C, getAttribute(), Idx, and llvm::wrap().
LLVMGetInstructionCallConv()
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
Obtain the calling convention for a call instruction.
This is the opposite of LLVMSetInstructionCallConv(). Reads its usage.
See also
LLVMSetInstructionCallConv()
Definition at line 2779 of file Core.cpp.
LLVMGetNormalDest()
LLVMBasicBlockRef LLVMGetNormalDest (LLVMValueRef InvokeInst)
Return the normal destination basic block.
This only works on llvm::InvokeInst instructions.
See also
llvm::InvokeInst::getNormalDest()
Definition at line 2858 of file Core.cpp.
References llvm::wrap().
LLVMGetNumArgOperands()
unsigned LLVMGetNumArgOperands (LLVMValueRef Instr)
Obtain the argument count for a call instruction.
This expects an LLVMValueRef that corresponds to a llvm::CallInst, llvm::InvokeInst, or llvm:FuncletPadInst.
See also
llvm::CallInst::getNumArgOperands()
llvm::InvokeInst::getNumArgOperands()
llvm::FuncletPadInst::getNumArgOperands()
Definition at line 2770 of file Core.cpp.
References llvm::unwrap().
LLVMGetUnwindDest()
LLVMBasicBlockRef LLVMGetUnwindDest (LLVMValueRef InvokeInst)
Return the unwind destination basic block.
Works on llvm::InvokeInst, llvm::CleanupReturnInst, and llvm::CatchSwitchInst instructions.
See also
llvm::InvokeInst::getUnwindDest()
llvm::CleanupReturnInst::getUnwindDest()
llvm::CatchSwitchInst::getUnwindDest()
Definition at line 2862 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMIsTailCall()
LLVMBool LLVMIsTailCall (LLVMValueRef CallInst)
Obtain whether a call instruction is a tail call.
This only works on llvm::CallInst instructions.
See also
llvm::CallInst::isTailCall()
Definition at line 2848 of file Core.cpp.
LLVMRemoveCallSiteEnumAttribute()
void LLVMRemoveCallSiteEnumAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, unsigned KindID)
Definition at line 2828 of file Core.cpp.
References C, and Idx.
LLVMRemoveCallSiteStringAttribute()
void LLVMRemoveCallSiteStringAttribute (LLVMValueRef C, LLVMAttributeIndex Idx, const char * K, unsigned KLen)
Definition at line 2833 of file Core.cpp.
References C, and Idx.
LLVMSetInstrParamAlignment()
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned Align)
Definition at line 2788 of file Core.cpp.
References llvm::Attribute::getWithAlignment().
LLVMSetInstructionCallConv()
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
Set the calling convention for a call instruction.
This expects an LLVMValueRef that corresponds to a llvm::CallInst or llvm::InvokeInst.
See also
llvm::CallInst::setCallingConv()
llvm::InvokeInst::setCallingConv()
Definition at line 2783 of file Core.cpp.
LLVMSetNormalDest()
void LLVMSetNormalDest (LLVMValueRef InvokeInst, LLVMBasicBlockRef B)
Set the normal destination basic block.
This only works on llvm::InvokeInst instructions.
See also
llvm::InvokeInst::setNormalDest()
Definition at line 2871 of file Core.cpp.
References B, and llvm::unwrap().
LLVMSetTailCall()
void LLVMSetTailCall (LLVMValueRef CallInst, LLVMBool IsTailCall)
Set whether a call instruction is a tail call.
This only works on llvm::CallInst instructions.
See also
llvm::CallInst::setTailCall()
Definition at line 2852 of file Core.cpp.
LLVMSetUnwindDest()
void LLVMSetUnwindDest (LLVMValueRef InvokeInst, LLVMBasicBlockRef B)
Set the unwind destination basic block.
Works on llvm::InvokeInst, llvm::CleanupReturnInst, and llvm::CatchSwitchInst instructions.
See also
llvm::InvokeInst::setUnwindDest()
llvm::CleanupReturnInst::setUnwindDest()
llvm::CatchSwitchInst::setUnwindDest()
Definition at line 2875 of file Core.cpp.
References B, and llvm::unwrap().