LLVM: Memory Buffers
Memory Buffers
LLVM-C: C interface to LLVM
Functions
LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char *Path, LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char *InputData, size_t InputDataLength, const char *BufferName, LLVMBool RequiresNullTerminator)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char *InputData, size_t InputDataLength, const char *BufferName)
const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
Detailed Description
Function Documentation
LLVMCreateMemoryBufferWithContentsOfFile()
LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char * Path, LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 3942 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRange()
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char * InputData, size_t InputDataLength, const char * BufferName, LLVMBool RequiresNullTerminator)
Definition at line 3967 of file Core.cpp.
References llvm::MemoryBuffer::getMemBuffer(), llvm::release, and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRangeCopy()
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char * InputData, size_t InputDataLength, const char * BufferName)
Definition at line 3978 of file Core.cpp.
References llvm::MemoryBuffer::getMemBufferCopy(), llvm::release, and llvm::wrap().
Referenced by LLVMTargetMachineEmitToMemoryBuffer().
LLVMCreateMemoryBufferWithSTDIN()
LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 3956 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getSTDIN(), and llvm::wrap().
LLVMDisposeMemoryBuffer()
void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
Definition at line 3996 of file Core.cpp.
References llvm::unwrap().
LLVMGetBufferSize()
size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
Definition at line 3992 of file Core.cpp.
References llvm::unwrap().
LLVMGetBufferStart()
const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
Definition at line 3988 of file Core.cpp.
References llvm::unwrap().