LLVM: lib/Transforms/Scalar/GVN.cpp File Reference
GVN.cpp File Reference
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/PHITransAddr.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include "llvm/Transforms/Utils/VNCoercion.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <utility>
#include <vector>
Classes
struct llvm::GVN::Expression
struct llvm::DenseMapInfo< GVN::Expression >
struct llvm::gvn::AvailableValue
Represents a particular available value that we know how to materialize.
struct llvm::gvn::AvailableValueInBlock
Represents an AvailableValue which can be rematerialized at the end of the associated BasicBlock.
class llvm::gvn::GVNLegacyPass
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "gvn"
Functions
STATISTIC (NumGVNInstr, "Number of instructions deleted")
STATISTIC (NumGVNLoad, "Number of loads deleted")
STATISTIC (NumGVNPRE, "Number of instructions PRE'd")
STATISTIC (NumGVNBlocks, "Number of blocks merged")
STATISTIC (NumGVNSimpl, "Number of instructions simplified")
STATISTIC (NumGVNEqProp, "Number of equalities propagated")
STATISTIC (NumPRELoad, "Number of loads PRE'd")
static bool IsValueFullyAvailableInBlock (BasicBlock *BB, DenseMap< BasicBlock *, char > &FullyAvailableBlocks, uint32_t RecurseDepth)
Return true if we can prove that the value we're analyzing is fully available in the specified block.
static Value * ConstructSSAForLoadSet (LoadInst *LI, SmallVectorImpl< AvailableValueInBlock > &ValuesPerBlock, GVN &gvn)
Given a set of loads specified by ValuesPerBlock, construct SSA form, allowing us to eliminate LI.
static bool isLifetimeStart (const Instruction *Inst)
static void reportMayClobberedLoad (LoadInst *LI, MemDepResult DepInfo, DominatorTree *DT, OptimizationRemarkEmitter *ORE)
Try to locate the three instruction involved in a missed load-elimination case that is due to an intervening store.
static void reportLoadElim (LoadInst *LI, Value *AvailableValue, OptimizationRemarkEmitter *ORE)
static void patchAndReplaceAllUsesWith (Instruction *I, Value *Repl)
static bool isOnlyReachableViaThisEdge (const BasicBlockEdge &E, DominatorTree *DT)
There is an edge from 'Src' to 'Dst'.
Variables
static cl::opt< bool > EnablePRE ("enable-pre", cl::init(true), cl::Hidden)
static cl::opt< bool > EnableLoadPRE ("enable-load-pre", cl::init(true))
static cl::opt< bool > EnableMemDep ("enable-gvn-memdep", cl::init(true))
static cl::opt< uint32_t > MaxRecurseDepth ("gvn-max-recurse-depth", cl::Hidden, cl::init(1000), cl::ZeroOrMore, cl::desc("Max recurse depth in GVN (default = 1000)"))
static cl::opt< uint32_t > MaxNumDeps ("gvn-max-num-deps", cl::Hidden, cl::init(100), cl::ZeroOrMore, cl::desc("Max number of dependences to attempt Load PRE (default = 100)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gvn"
Definition at line 88 of file GVN.cpp.
Function Documentation
ConstructSSAForLoadSet()
static Value * ConstructSSAForLoadSet (LoadInst * LI, SmallVectorImpl< AvailableValueInBlock > & ValuesPerBlock, GVN & gvn) static
Given a set of loads specified by ValuesPerBlock, construct SSA form, allowing us to eliminate LI.
This returns the value that should be used at LI's definition site.
Definition at line 727 of file GVN.cpp.
References llvm::SSAUpdater::AddAvailableValue(), assert(), llvm::GVN::getDominatorTree(), llvm::Value::getName(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SSAUpdater::HasValueForBlock(), llvm::SSAUpdater::Initialize(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates().
isLifetimeStart()
static bool isLifetimeStart (const Instruction * Inst) static
Definition at line 816 of file GVN.cpp.
isOnlyReachableViaThisEdge()
static bool isOnlyReachableViaThisEdge (const BasicBlockEdge & E, DominatorTree * DT) static
There is an edge from 'Src' to 'Dst'.
Return true if every path from the entry block to 'Dst' passes via this edge. In particular 'Dst' must not be reachable via another edge from 'Src'.
Definition at line 1656 of file GVN.cpp.
References assert().
IsValueFullyAvailableInBlock()
static bool IsValueFullyAvailableInBlock (BasicBlock * BB, DenseMap< BasicBlock *, char > & FullyAvailableBlocks, uint32_t RecurseDepth) static
Return true if we can prove that the value we're analyzing is fully available in the specified block.
As we go, keep track of which blocks we know are fully alive in FullyAvailableBlocks. This map is actually a tri-state map with the following values: 0) we know the block is not fully available. 1) we know the block is fully available. 2) we do not know whether the block is fully available or not, but we are currently speculating that it will be. 3) we are speculating for this block and have used that to speculate for other blocks.
Definition at line 654 of file GVN.cpp.
References IsValueFullyAvailableInBlock(), MaxRecurseDepth, llvm::pred_begin(), llvm::pred_end(), llvm::succ_begin(), and llvm::succ_end().
Referenced by IsValueFullyAvailableInBlock().
patchAndReplaceAllUsesWith()
static void patchAndReplaceAllUsesWith (Instruction * I, Value * Repl) static
Definition at line 1431 of file GVN.cpp.
References I, and llvm::patchReplacementInstruction().
reportLoadElim()
static void reportLoadElim (LoadInst * LI, Value * AvailableValue, OptimizationRemarkEmitter * ORE) static
Definition at line 1272 of file GVN.cpp.
References DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), and llvm::Value::getType().
reportMayClobberedLoad()
static void reportMayClobberedLoad (LoadInst * LI, MemDepResult DepInfo, DominatorTree * DT, OptimizationRemarkEmitter * ORE) static
Try to locate the three instruction involved in a missed load-elimination case that is due to an intervening store.
Definition at line 824 of file GVN.cpp.
References DEBUG_TYPE, llvm::DominatorTree::dominates(), llvm::OptimizationRemarkEmitter::emit(), llvm::MemDepResult::getInst(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), and llvm::Value::users().
STATISTIC() [1/7]
STATISTIC (NumGVNBlocks , "Number of blocks merged")
STATISTIC() [2/7]
STATISTIC (NumGVNEqProp , "Number of equalities propagated")
STATISTIC() [3/7]
STATISTIC (NumGVNInstr , "Number of instructions deleted")
STATISTIC() [4/7]
STATISTIC (NumGVNLoad , "Number of loads deleted")
STATISTIC() [5/7]
STATISTIC (NumGVNPRE , "Number of instructions PRE'd")
STATISTIC() [6/7]
STATISTIC (NumGVNSimpl , "Number of instructions simplified")
STATISTIC() [7/7]
STATISTIC (NumPRELoad , "Number of loads PRE'd")
Variable Documentation
EnableLoadPRE
cl::opt< bool > EnableLoadPRE("enable-load-pre", cl::init(true)) ("enable-load-pre" , cl::init(true)) static
EnableMemDep
cl::opt< bool > EnableMemDep("enable-gvn-memdep", cl::init(true)) ("enable-gvn-memdep" , cl::init(true)) static
EnablePRE
cl::opt< bool > EnablePRE("enable-pre", cl::init(true), cl::Hidden) ("enable-pre" , cl::init(true) , cl::Hidden) static
MaxNumDeps
cl::opt< uint32_t > MaxNumDeps("gvn-max-num-deps", cl::Hidden, cl::init(100), cl::ZeroOrMore, cl::desc("Max number of dependences to attempt Load PRE (default = 100)")) ("gvn-max-num-deps" , cl::Hidden , cl::init(100) , cl::ZeroOrMore , cl::desc("Max number of dependences to attempt Load PRE (default = 100)")) static
MaxRecurseDepth
cl::opt< uint32_t > MaxRecurseDepth("gvn-max-recurse-depth", cl::Hidden, cl::init(1000), cl::ZeroOrMore, cl::desc("Max recurse depth in GVN (default = 1000)")) ("gvn-max-recurse-depth" , cl::Hidden , cl::init(1000) , cl::ZeroOrMore , cl::desc("Max recurse depth in GVN (default = 1000)")) static
Referenced by IsValueFullyAvailableInBlock().