LLVM: lib/Transforms/Hello/Hello.cpp File Reference
Hello.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Function.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "hello"
Functions
STATISTIC (HelloCounter, "Counts number of functions greeted")
static RegisterPass< Hello > X ("hello", "Hello World Pass")
static RegisterPass< Hello2 > Y ("hello2", "Hello World Pass (with getAnalysisUsage implemented)")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hello"
Definition at line 20 of file Hello.cpp.
Function Documentation
STATISTIC()
STATISTIC (HelloCounter , "Counts number of functions greeted")
X()
static RegisterPass< Hello > X ("hello" , "Hello World Pass") static
Referenced by llvm::AbsoluteDifference(), llvm::ConstantRange::add(), llvm::cl::parser< DataType >::addLiteralOption(), canAlwaysEvaluateInType(), canonicalizeInsertSplat(), canonicalizeSaturatedAdd(), llvm::cast(), checkForNegativeOperand(), llvm::InstCombiner::commonIDivTransforms(), llvm::ScaledNumber< DigitsT >::compare(), CompareSCEVComplexity(), llvm::FoldingSetTrait< SCEV >::ComputeHash(), llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::codeview::consume(), llvm::Trace::contains(), llvm::decomposeBitTestICmp(), decomposeBitTestICmp(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::FoldingSetTrait< SCEV >::Equals(), llvm::FoldingSetTrait< SCEVPredicate >::Equals(), factorizeFAddFSub(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), findGCD(), FindInOperandList(), foldAndOrOfEqualityCmpsWithConstants(), foldBitCastBitwiseLogic(), foldBitcastExtElt(), foldBitCastSelect(), foldCtpop(), foldCttzCtlz(), foldFabsWithFcmpZero(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldFNegIntoConstant(), foldGuardedRotateToFunnelShift(), foldICmpBitCast(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), foldICmpWithTruncSignExtendedVal(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsEltIntoSplat(), foldIsPowerOf2(), foldLogicCastConstant(), foldNoWrapAdd(), foldSelectBinOpIdentity(), foldSelectICmpAndAnd(), foldSelectICmpLshrAshr(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), foldSelectWithBinaryOp(), llvm::InstCombiner::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), llvm::format_provider< T, typename std::enable_if< detail::use_char_formatter< T >::value >::type >::format(), llvm::FmtAlign::format(), llvm::PMDataManager::freePass(), llvm::get_hashable_data(), llvm::Trace::getBlockIndex(), getHashValueImpl(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::ScalarEvolution::getZeroExtendExpr(), hoistInsEltConst(), llvm::isa(), llvm::isConsecutiveAccess(), isDivZero(), isEqualImpl(), llvm::isKnownNegation(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), isSimpleCastedPHI(), llvm::isSplatValue(), isTruePredicate(), llvm::isUInt(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FNegNSZ(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapVectorN(), MatchBinaryOp(), matchRotate(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), MinOptional(), narrowUDivURem(), narrowVectorSelect(), llvm::bfi_detail::BlockMass::operator!=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator!=(), llvm::DIFile::ChecksumInfo< T >::operator!=(), llvm::DIExpression::expr_op_iterator::operator!=(), llvm::DITypeRefArray::iterator::operator!=(), llvm::OnDiskChainedHashTable< Info >::iterator::operator!=(), llvm::ScaledNumber< DigitsT >::operator!=(), llvm::TrackingMDRef::operator!=(), llvm::TypedMDOperandIterator< T >::operator!=(), llvm::TypedTrackingMDRef< T >::operator!=(), llvm::ScaledNumber< DigitsT >::operator*=(), llvm::bfi_detail::BlockMass::operator+=(), llvm::ScaledNumber< DigitsT >::operator+=(), llvm::bfi_detail::BlockMass::operator-=(), llvm::ScaledNumber< DigitsT >::operator-=(), llvm::ScaledNumber< DigitsT >::operator/=(), llvm::bfi_detail::BlockMass::operator<(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<(), llvm::ScaledNumber< DigitsT >::operator<(), llvm::bfi_detail::operator<<(), llvm::operator<<(), llvm::bfi_detail::BlockMass::operator<=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<=(), llvm::ScaledNumber< DigitsT >::operator<=(), llvm::TrackingMDRef::operator=(), llvm::TypedTrackingMDRef< T >::operator=(), llvm::bfi_detail::BlockMass::operator==(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator==(), llvm::DIFile::ChecksumInfo< T >::operator==(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::DIExpression::expr_op_iterator::operator==(), llvm::InlineAsmKeyType::operator==(), llvm::DITypeRefArray::iterator::operator==(), llvm::OnDiskChainedHashTable< Info >::iterator::operator==(), llvm::ScaledNumber< DigitsT >::operator==(), llvm::TrackingMDRef::operator==(), llvm::TypedMDOperandIterator< T >::operator==(), llvm::TypedTrackingMDRef< T >::operator==(), llvm::bfi_detail::BlockMass::operator>(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>(), llvm::ScaledNumber< DigitsT >::operator>(), llvm::bfi_detail::BlockMass::operator>=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>=(), llvm::ScaledNumber< DigitsT >::operator>=(), OptimizeAndOrXor(), optimizeDivRem(), optimizeTrigReflections(), llvm::FoldingSetTrait< SCEV >::Profile(), llvm::FoldingSetTrait< SCEVPredicate >::Profile(), reassociateFCmps(), reassociateShiftAmtsOfTwoSameDirectionShifts(), rotl64(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), llvm::detail::scalbn(), llvm::SignExtend32(), llvm::SignExtend64(), SimplifyAndInst(), simplifyAndOfICmps(), simplifyAndOrOfICmpsWithZero(), SimplifyAShrInst(), simplifyDiv(), simplifyDivRem(), SimplifyFAddInst(), SimplifyFDivInst(), SimplifyFMulInst(), simplifyFNegInst(), SimplifyFSubInst(), simplifyICmpWithConstant(), SimplifyLShrInst(), SimplifyMulInst(), simplifyOrOfICmps(), simplifySelectBitTest(), simplifySelectWithFakeICmpEq(), simplifySelectWithICmpCond(), SimplifyShift(), SimplifyShlInst(), SimplifySRemInst(), SimplifySubInst(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), sinkNotIntoXor(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::opt::StrCmpOptionNameIgnoreCase(), strongerOrdering(), llvm::ConstantRange::sub(), llvm::TrackingMDRef::TrackingMDRef(), TruncIfPossible(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFNeg(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitFRem(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitLShr(), visitMaskedMerge(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), llvm::InstCombiner::visitURem(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
Y()
static RegisterPass< Hello2 > Y ("hello2" , "Hello World Pass (with getAnalysisUsage implemented)") static
Referenced by llvm::AbsoluteDifference(), canonicalizeSaturatedAdd(), llvm::cast(), checkForNegativeOperand(), llvm::InstCombiner::commonIDivTransforms(), computeKnownBitsFromOperator(), llvm::codeview::consume(), decomposeBitTestICmp(), llvm::InnerLoopVectorizer::emitTransformedIndex(), factorizeFAddFSub(), findGCD(), foldCttzCtlz(), foldGuardedRotateToFunnelShift(), foldICmpShlOne(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldSelectBinOpIdentity(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), foldSelectShuffle(), foldSelectWithBinaryOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldToUnsignedSaturatedAdd(), getHashValueImpl(), hoistInsEltConst(), llvm::isa(), isDivZero(), isEqualImpl(), llvm::isKnownNegation(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), llvm::isSplatValue(), MinOptional(), narrowUDivURem(), narrowVectorSelect(), optimizeDivRem(), reassociateFCmps(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), SimplifyAddInst(), SimplifyAndInst(), simplifyAndOrOfICmpsWithZero(), simplifyICmpWithBinOp(), SimplifyLShrInst(), simplifySelectBitTest(), simplifySelectWithICmpCond(), SimplifySubInst(), simplifyUnsignedRangeCheck(), sinkNotIntoXor(), llvm::opt::StrCmpOptionNameIgnoreCase(), strongerOrdering(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFNeg(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().