LLVM: lib/Target/Hexagon/HexagonAsmPrinter.cpp File Reference
HexagonAsmPrinter.cpp File Reference
#include "HexagonAsmPrinter.h"
#include "Hexagon.h"
#include "HexagonInstrInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "MCTargetDesc/HexagonInstPrinter.h"
#include "MCTargetDesc/HexagonMCExpr.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "TargetInfo/HexagonTargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <string>
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "asm-printer"
Functions
void llvm::HexagonLowerToMC (const MCInstrInfo &MCII, const MachineInstr *MI, MCInst &MCB, HexagonAsmPrinter &AP)
static unsigned getHexagonRegisterPair (unsigned Reg, const MCRegisterInfo *RI)
static MCSymbol * smallData (AsmPrinter &AP, const MachineInstr &MI, MCStreamer &OutStreamer, const MCOperand &Imm, int AlignSize)
static MCInst ScaleVectorOffset (MCInst &Inst, unsigned OpNo, unsigned VectorSize, MCContext &Ctx)
void LLVMInitializeHexagonAsmPrinter ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 63 of file HexagonAsmPrinter.cpp.
Function Documentation
getHexagonRegisterPair()
static unsigned getHexagonRegisterPair (unsigned Reg, const MCRegisterInfo * RI) inline static
Definition at line 66 of file HexagonAsmPrinter.cpp.
References assert(), and contains().
Referenced by llvm::HexagonAsmPrinter::HexagonProcessInstruction().
LLVMInitializeHexagonAsmPrinter()
void LLVMInitializeHexagonAsmPrinter ()
Definition at line 774 of file HexagonAsmPrinter.cpp.
References llvm::getTheHexagonTarget(), and X.
ScaleVectorOffset()
static MCInst ScaleVectorOffset (MCInst & Inst, unsigned OpNo, unsigned VectorSize, MCContext & Ctx) static
Definition at line 246 of file HexagonAsmPrinter.cpp.
References llvm::LiveRangeEdit::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::getExpr(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), and llvm::MCInst::getOperand().
Referenced by llvm::HexagonAsmPrinter::HexagonProcessInstruction().
smallData()
static MCSymbol * smallData (AsmPrinter & AP, const MachineInstr & MI, MCStreamer & OutStreamer, const MCOperand & Imm, int AlignSize) static
Definition at line 180 of file HexagonAsmPrinter.cpp.
References assert(), llvm::MCStreamer::EmitCodeAlignment(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::getContext(), llvm::AsmPrinter::GetCPISymbol(), llvm::MCContext::getELFSection(), llvm::MCOperand::getExpr(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MCSymbol::getName(), llvm::MCContext::getOrCreateSymbol(), llvm::AsmPrinter::getSymbol(), llvm::MachineOperand::isCPI(), llvm::MCOperand::isExpr(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isJTI(), llvm::MCSymbol::isUndefined(), llvm_unreachable, llvm::MCSA_Global, llvm::MCSA_Local, MI, Name, llvm::AsmPrinter::OutContext, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, llvm::StringRef::str(), llvm::MCStreamer::SwitchSection(), and llvm::utohexstr().
Referenced by llvm::HexagonAsmPrinter::HexagonProcessInstruction().