LLVM: lib/DebugInfo/GSYM/InlineInfo.cpp File Reference
InlineInfo.cpp File Reference
#include "llvm/DebugInfo/GSYM/FileEntry.h"
#include "llvm/DebugInfo/GSYM/InlineInfo.h"
#include <algorithm>
#include <inttypes.h>
Functions
static bool getInlineStackHelper (const InlineInfo &II, uint64_t Addr, std::vector< const InlineInfo * > &InlineStack)
Function Documentation
getInlineStackHelper()
static bool getInlineStackHelper (const InlineInfo & II, uint64_t Addr, std::vector< const InlineInfo * > & InlineStack) static
Definition at line 37 of file InlineInfo.cpp.
References llvm::gsym::InlineInfo::Children, llvm::gsym::AddressRanges::contains(), getInlineStackHelper(), llvm::gsym::InlineInfo::Name, and llvm::gsym::InlineInfo::Ranges.
Referenced by llvm::gsym::InlineInfo::getInlineStack(), and getInlineStackHelper().