LLVM: lib/IR/Instructions.cpp File Reference
Instructions.cpp File Reference
#include "llvm/IR/Instructions.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>
Functions
static bool IsConstantOne (Value *val)
IsConstantOne - Return true only if val is constant int 1.
static Instruction * createMalloc (Instruction *InsertBefore, BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize, ArrayRef< OperandBundleDef > OpB, Function *MallocF, const Twine &Name)
static Instruction * createFree (Value *Source, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertBefore, BasicBlock *InsertAtEnd)
static Value * getAISize (LLVMContext &Context, Value *Amt)
template<typename IndexTy >
static Type * getIndexedTypeInternal (Type *Agg, ArrayRef< IndexTy > IdxList)
getIndexedType - Returns the type of the element that would be accessed with a gep instruction with the specified parameters.
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts)
Variables
static cl::opt< bool > SwitchInstProfUpdateWrapperStrict ("switch-inst-prof-update-wrapper-strict", cl::Hidden, cl::desc("Assert that prof branch_weights metadata is valid when creating " "an instance of SwitchInstProfUpdateWrapper"), cl::init(false))
Function Documentation
createFree()
static Instruction * createFree (Value * Source, ArrayRef< OperandBundleDef > Bundles, Instruction * InsertBefore, BasicBlock * InsertAtEnd) static
Definition at line 657 of file Instructions.cpp.
References assert(), llvm::CallInst::Create(), F, llvm::FunctionCallee::getCallee(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), and llvm::IRBuilderBase::getVoidTy().
Referenced by llvm::CallInst::CreateFree().
createMalloc()
static Instruction * createMalloc (Instruction * InsertBefore, BasicBlock * InsertAtEnd, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize, ArrayRef< OperandBundleDef > OpB, Function * MallocF, const Twine & Name) static
Definition at line 527 of file Instructions.cpp.
References assert(), llvm::CallInst::Create(), llvm::CastInst::CreateIntegerCast(), llvm::TargetFolder::CreateMul(), F, llvm::IntervalMapImpl::NodeRef::get(), llvm::FunctionCallee::getCallee(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getInstList(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getIntegerCast(), llvm::ConstantExpr::getMul(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::PointerType::getUnqual(), IsConstantOne(), llvm::Type::isVoidTy(), Name, llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::CallBase::setCallingConv(), and llvm::CallInst::setTailCall().
Referenced by llvm::CallInst::CreateMalloc().
getAISize()
static Value * getAISize (LLVMContext & Context, Value * Amt) static
Definition at line 1203 of file Instructions.cpp.
References assert(), Context, llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getInt32Ty(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
getIndexedTypeInternal()
template<typename IndexTy > static Type * getIndexedTypeInternal (Type * Agg, ArrayRef< IndexTy > IdxList) static
getIndexedType - Returns the type of the element that would be accessed with a gep instruction with the specified parameters.
The Idxs pointer should point to a continuous piece of memory containing the indices, either as Value* or uint64_t.
A null type is returned if the indices are invalid for the specified pointer type.
Definition at line 1626 of file Instructions.cpp.
References llvm::ArrayRef< T >::empty(), llvm::CompositeType::getTypeAtIndex(), llvm::CompositeType::indexValid(), llvm::Type::isPointerTy(), llvm::Type::isSized(), and llvm::ArrayRef< T >::size().
Referenced by llvm::GetElementPtrInst::getIndexedType().
IsConstantOne()
static bool IsConstantOne (Value * val) static
IsConstantOne - Return true only if val is constant int 1.
Definition at line 521 of file Instructions.cpp.
References assert(), and llvm::ConstantInt::isOne().
Referenced by createMalloc().
isIdentityMaskImpl()
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 1939 of file Instructions.cpp.
References isSingleSourceMaskImpl().
Referenced by llvm::ShuffleVectorInst::isConcat(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::ShuffleVectorInst::isIdentityWithExtract(), and llvm::ShuffleVectorInst::isIdentityWithPadding().
isSingleSourceMaskImpl()
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 1915 of file Instructions.cpp.
References assert().
Referenced by llvm::ShuffleVectorInst::isExtractSubvectorMask(), isIdentityMaskImpl(), and llvm::ShuffleVectorInst::isSingleSourceMask().
Variable Documentation
SwitchInstProfUpdateWrapperStrict
cl::opt< bool > SwitchInstProfUpdateWrapperStrict("switch-inst-prof-update-wrapper-strict", cl::Hidden, cl::desc("Assert that prof branch_weights metadata is valid when creating " "an instance of SwitchInstProfUpdateWrapper"), cl::init(false)) ("switch-inst-prof-update-wrapper-strict" , cl::Hidden , cl::desc("Assert that prof branch_weights metadata is valid when creating " "an instance of SwitchInstProfUpdateWrapper") , cl::init(false)) static
Referenced by llvm::SwitchInstProfUpdateWrapper::init().