LLVM: lib/Transforms/InstCombine/InstructionCombining.cpp File Reference
InstructionCombining.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm-c/Initialization.h"
#include "llvm-c/Transforms/InstCombine.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LazyBlockFrequencyInfo.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/TargetFolder.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/CBindingWrapping.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
#include "llvm/Transforms/InstCombine/InstCombineWorklist.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "instcombine"
Functions
STATISTIC (NumCombined, "Number of insts combined")
STATISTIC (NumConstProp, "Number of constant folds")
STATISTIC (NumDeadInst, "Number of dead inst eliminated")
STATISTIC (NumSunkInst, "Number of instructions sunk")
STATISTIC (NumExpand, "Number of expansions")
STATISTIC (NumFactor, "Number of factorizations")
STATISTIC (NumReassoc, "Number of reassociations")
DEBUG_COUNTER (VisitCounter, "instcombine-visit", "Controls which instructions are visited")
static bool MaintainNoSignedWrap (BinaryOperator &I, Value *B, Value *C)
static bool hasNoUnsignedWrap (BinaryOperator &I)
static void ClearSubclassDataAfterReassociation (BinaryOperator &I)
Conservatively clears subclassOptionalData after a reassociation or commutation.
static bool simplifyAssocCastAssoc (BinaryOperator *BinOp1)
Combine constant operands of associative operations either before or after a cast to eliminate one of the associative operations: (op (cast (op X, C2)), C1) --> (cast (op X, op (C1, C2))) (op (cast (op X, C2)), C1) --> (op (cast X), op (C1, C2))
static bool leftDistributesOverRight (Instruction::BinaryOps LOp, Instruction::BinaryOps ROp)
Return whether "X LOp (Y ROp Z)" is always equal to "(X LOp Y) ROp (X LOp Z)".
static bool rightDistributesOverLeft (Instruction::BinaryOps LOp, Instruction::BinaryOps ROp)
Return whether "(X LOp Y) ROp Z" is always equal to "(X ROp Z) LOp (Y ROp Z)".
static Value * getIdentityValue (Instruction::BinaryOps Opcode, Value *V)
This function returns identity value for given opcode, which can be used to factor patterns like (X * 2) + X ==> (X * 2) + (X * 1) ==> X * (2 + 1).
static Instruction::BinaryOps getBinOpsForFactorization (Instruction::BinaryOps TopOpcode, BinaryOperator *Op, Value *&LHS, Value *&RHS)
This function predicates factorization using distributive laws.
static Value * foldOperationIntoSelectOperand (Instruction &I, Value *SO, InstCombiner::BuilderTy &Builder)
static Value * foldOperationIntoPhiValue (BinaryOperator *I, Value *InV, InstCombiner::BuilderTy &Builder)
static bool shouldMergeGEPs (GEPOperator &GEP, GEPOperator &Src)
static bool isNeverEqualToUnescapedAlloc (Value *V, const TargetLibraryInfo *TLI, Instruction *AI)
static bool isAllocSiteRemovable (Instruction *AI, SmallVectorImpl< WeakTrackingVH > &Users, const TargetLibraryInfo *TLI)
static Instruction * tryToMoveFreeBeforeNullTest (CallInst &FI, const DataLayout &DL)
Move the call to free before a NULL test.
static bool isCatchAll (EHPersonality Personality, Constant *TypeInfo)
Return 'true' if the given typeinfo will match anything.
static bool shorter_filter (const Value *LHS, const Value *RHS)
static bool TryToSinkInstruction (Instruction *I, BasicBlock *DestBlock)
Try to move the specified instruction from its current block into the beginning of DestBlock, which can only happen if it's safe to move the instruction past all of the instructions between it and the end of its block.
static bool AddReachableCodeToWorklist (BasicBlock *BB, const DataLayout &DL, SmallPtrSetImpl< BasicBlock * > &Visited, InstCombineWorklist &ICWorklist, const TargetLibraryInfo *TLI)
Walk the function in depth-first order, adding all reachable code to the worklist.
static bool prepareICWorklistFromFunction (Function &F, const DataLayout &DL, TargetLibraryInfo *TLI, InstCombineWorklist &ICWorklist)
Populate the IC worklist from a function, and prune any dead basic blocks discovered in the process.
static bool combineInstructionsOverFunction (Function &F, InstCombineWorklist &Worklist, AliasAnalysis *AA, AssumptionCache &AC, TargetLibraryInfo &TLI, DominatorTree &DT, OptimizationRemarkEmitter &ORE, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, bool ExpensiveCombines=true, LoopInfo *LI=nullptr)
INITIALIZE_PASS_BEGIN (InstructionCombiningPass, "instcombine", "Combine redundant instructions", false, false) INITIALIZE_PASS_END(InstructionCombiningPass
void LLVMInitializeInstCombine (LLVMPassRegistryRef R)
void LLVMAddInstructionCombiningPass (LLVMPassManagerRef PM)
See llvm::createInstructionCombiningPass function.
Variables
static cl::opt< bool > EnableCodeSinking ("instcombine-code-sinking", cl::desc("Enable code sinking"), cl::init(true))
static cl::opt< bool > EnableExpensiveCombines ("expensive-combines", cl::desc("Enable expensive instruction combines"))
static cl::opt< unsigned > MaxArraySize ("instcombine-maxarray-size", cl::init(1024), cl::desc("Maximum array size considered when doing a combine"))
static cl::opt< unsigned > ShouldLowerDbgDeclare ("instcombine-lower-dbg-declare", cl::Hidden, cl::init(true))
instcombine
Combine redundant instructions
Combine redundant false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 112 of file InstructionCombining.cpp.
Function Documentation
AddReachableCodeToWorklist()
static bool AddReachableCodeToWorklist (BasicBlock * BB, const DataLayout & DL, SmallPtrSetImpl< BasicBlock * > & Visited, InstCombineWorklist & ICWorklist, const TargetLibraryInfo * TLI) static
Walk the function in depth-first order, adding all reachable code to the worklist.
This has a couple of tricks to make the code faster and more powerful. In particular, we constant fold and DCE instructions as we go, to avoid adding them to the worklist (this significantly speeds up instcombine on code where many instructions are dead or constant). Additionally, if we find a branch whose condition is a known constant, we only visit the reachable successors.
Definition at line 3349 of file InstructionCombining.cpp.
References llvm::InstCombineWorklist::AddInitialGroup(), llvm::BasicBlock::begin(), C, llvm::ConstantFoldConstant(), llvm::ConstantFoldInstruction(), llvm::dbgs(), E, llvm::SmallVectorBase::empty(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::BranchInst::getCondition(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::BranchInst::isConditional(), llvm::isInstructionTriviallyDead(), LLVM_DEBUG, llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::replaceDbgUsesWithUndef(), llvm::salvageDebugInfo(), SI, llvm::successors(), and llvm::Value::use_empty().
Referenced by prepareICWorklistFromFunction().
ClearSubclassDataAfterReassociation()
static void ClearSubclassDataAfterReassociation (BinaryOperator & I) static
Conservatively clears subclassOptionalData after a reassociation or commutation.
We preserve fast-math flags when applicable as they can be preserved.
Definition at line 234 of file InstructionCombining.cpp.
References I.
combineInstructionsOverFunction()
static bool combineInstructionsOverFunction (Function & F, InstCombineWorklist & Worklist, AliasAnalysis * AA, AssumptionCache & AC, TargetLibraryInfo & TLI, DominatorTree & DT, OptimizationRemarkEmitter & ORE, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, bool ExpensiveCombines = true, LoopInfo * LI = nullptr) static
Builder - This is an IRBuilder that automatically inserts new instructions into the worklist when they are created.
Definition at line 3485 of file InstructionCombining.cpp.
References llvm::InstCombineWorklist::Add(), llvm::dbgs(), EnableExpensiveCombines, F, I, LLVM_DEBUG, llvm::LowerDbgDeclare(), llvm::PatternMatch::match(), MaxArraySize, llvm::InstCombiner::MaxArraySizeForCombine, prepareICWorklistFromFunction(), llvm::AssumptionCache::registerAssumption(), llvm::InstCombiner::run(), and ShouldLowerDbgDeclare.
Referenced by llvm::InstCombinePass::run(), and llvm::InstructionCombiningPass::runOnFunction().
DEBUG_COUNTER()
DEBUG_COUNTER (VisitCounter , "instcombine-visit" , "Controls which instructions are visited")
foldOperationIntoPhiValue()
static Value * foldOperationIntoPhiValue (BinaryOperator * I, Value * InV, InstCombiner::BuilderTy & Builder) static
Definition at line 899 of file InstructionCombining.cpp.
References C, llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IntervalMapImpl::NodeRef::get(), I, and std::swap().
foldOperationIntoSelectOperand()
static Value * foldOperationIntoSelectOperand (Instruction & I, Value * SO, InstCombiner::BuilderTy & Builder) static
Definition at line 819 of file InstructionCombining.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateBinOp(), llvm::IRBuilder< T, Inserter >::CreateCast(), llvm::IntervalMapImpl::NodeRef::get(), llvm::Value::getName(), I, and std::swap().
getBinOpsForFactorization()
static Instruction::BinaryOps getBinOpsForFactorization (Instruction::BinaryOps TopOpcode, BinaryOperator * Op, Value *& LHS, Value *& RHS) static
This function predicates factorization using distributive laws.
By default, it just returns the 'Op' inputs. But for special-cases like 'add(shl(X, 5), ...)', this function will have TopOpcode == Instruction::Add and Op = shl(X, 5). The 'shl' is treated as the more general 'mul X, 32' to allow more factorization opportunities.
Definition at line 518 of file InstructionCombining.cpp.
References assert(), C, llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getShl(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::MCBinaryExpr::Mul, and llvm::AtomicRMWInst::Sub.
getIdentityValue()
static Value * getIdentityValue (Instruction::BinaryOps Opcode, Value * V) static
This function returns identity value for given opcode, which can be used to factor patterns like (X * 2) + X ==> (X * 2) + (X * 1) ==> X * (2 + 1).
Definition at line 505 of file InstructionCombining.cpp.
References llvm::ConstantExpr::getBinOpIdentity(), and llvm::Value::getType().
hasNoUnsignedWrap()
static bool hasNoUnsignedWrap (BinaryOperator & I) static
Definition at line 226 of file InstructionCombining.cpp.
References llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), and I.
Referenced by llvm::SDNode::print_details(), and llvm::InstCombiner::visitLShr().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (InstructionCombiningPass , "instcombine" , "Combine redundant instructions" , false , false)
isAllocSiteRemovable()
static bool isAllocSiteRemovable (Instruction * AI, SmallVectorImpl< WeakTrackingVH > & Users, const TargetLibraryInfo * TLI) static
Definition at line 2264 of file InstructionCombining.cpp.
References llvm::LazyCallGraph::Edge::Call, llvm::SmallVectorBase::empty(), llvm::User::getOperand(), I, llvm::ICmpInst::isEquality(), llvm::isFreeCall(), isNeverEqualToUnescapedAlloc(), LLVM_FALLTHROUGH, llvm_unreachable, MI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), SI, llvm::Value::users(), and Users.
Referenced by llvm::InstCombiner::visitAllocSite().
isCatchAll()
static bool isCatchAll (EHPersonality Personality, Constant * TypeInfo) static
Return 'true' if the given typeinfo will match anything.
Definition at line 2765 of file InstructionCombining.cpp.
References llvm::CoreCLR, llvm::GNU_Ada, llvm::GNU_C, llvm::GNU_C_SjLj, llvm::GNU_CXX, llvm::GNU_CXX_SjLj, llvm::GNU_ObjC, llvm::Constant::isNullValue(), llvm_unreachable, llvm::MSVC_CXX, llvm::MSVC_Win64SEH, llvm::MSVC_X86SEH, llvm::Rust, llvm::Unknown, and llvm::Wasm_CXX.
Referenced by llvm::InstCombiner::visitLandingPadInst().
isNeverEqualToUnescapedAlloc()
static bool isNeverEqualToUnescapedAlloc (Value * V, const TargetLibraryInfo * TLI, Instruction * AI) static
Definition at line 2250 of file InstructionCombining.cpp.
References llvm::isAllocLikeFn().
Referenced by isAllocSiteRemovable().
leftDistributesOverRight()
static bool leftDistributesOverRight (Instruction::BinaryOps LOp, Instruction::BinaryOps ROp) static
Return whether "X LOp (Y ROp Z)" is always equal to "(X LOp Y) ROp (X LOp Z)".
Definition at line 469 of file InstructionCombining.cpp.
References llvm::MCBinaryExpr::Mul, llvm::AtomicRMWInst::Sub, and llvm::AtomicRMWInst::Xor.
Referenced by rightDistributesOverLeft().
MaintainNoSignedWrap()
static bool MaintainNoSignedWrap (BinaryOperator & I, Value * B, Value * C) static
Definition at line 203 of file InstructionCombining.cpp.
References B, C, llvm::OverflowingBinaryOperator::hasNoSignedWrap(), I, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::sadd_ov(), llvm::APInt::ssub_ov(), and llvm::AtomicRMWInst::Sub.
prepareICWorklistFromFunction()
static bool prepareICWorklistFromFunction (Function & F, const DataLayout & DL, TargetLibraryInfo * TLI, InstCombineWorklist & ICWorklist) static
Populate the IC worklist from a function, and prune any dead basic blocks discovered in the process.
This also does basic constant propagation and other forward fixing to make the combiner itself run much faster.
Definition at line 3458 of file InstructionCombining.cpp.
References AddReachableCodeToWorklist(), llvm::SmallPtrSetImpl< PtrType >::count(), F, and llvm::removeAllNonTerminatorAndEHPadInstructions().
Referenced by combineInstructionsOverFunction().
rightDistributesOverLeft()
static bool rightDistributesOverLeft (Instruction::BinaryOps LOp, Instruction::BinaryOps ROp) static
Return whether "(X LOp Y) ROp Z" is always equal to "(X ROp Z) LOp (Y ROp Z)".
Definition at line 490 of file InstructionCombining.cpp.
References llvm::Instruction::isBitwiseLogicOp(), llvm::Instruction::isCommutative(), llvm::Instruction::isShift(), and leftDistributesOverRight().
shorter_filter()
static bool shorter_filter (const Value * LHS, const Value * RHS) static
Definition at line 2792 of file InstructionCombining.cpp.
References llvm::Value::getType().
Referenced by llvm::InstCombiner::visitLandingPadInst().
shouldMergeGEPs()
static bool shouldMergeGEPs (GEPOperator & GEP, GEPOperator & Src) static
Definition at line 1142 of file InstructionCombining.cpp.
References GEP, llvm::GEPOperator::hasAllZeroIndices(), and llvm::Value::hasOneUse().
Referenced by llvm::InstCombiner::visitGetElementPtrInst().
simplifyAssocCastAssoc()
static bool simplifyAssocCastAssoc (BinaryOperator * BinOp1) static
Combine constant operands of associative operations either before or after a cast to eliminate one of the associative operations: (op (cast (op X, C2)), C1) --> (cast (op X, op (C1, C2))) (op (cast (op X, C2)), C1) --> (op (cast X), op (C1, C2))
Definition at line 250 of file InstructionCombining.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::ConstantExpr::getCast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Instruction::isBitwiseLogicOp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::match(), llvm::User::setOperand(), and llvm::CCValAssign::ZExt.
STATISTIC() [1/7]
STATISTIC (NumCombined , "Number of insts combined")
STATISTIC() [2/7]
STATISTIC (NumConstProp , "Number of constant folds")
STATISTIC() [3/7]
STATISTIC (NumDeadInst , "Number of dead inst eliminated")
STATISTIC() [4/7]
STATISTIC (NumExpand , "Number of expansions")
STATISTIC() [5/7]
STATISTIC (NumFactor , "Number of factorizations")
STATISTIC() [6/7]
STATISTIC (NumReassoc , "Number of reassociations")
STATISTIC() [7/7]
STATISTIC (NumSunkInst , "Number of instructions sunk")
tryToMoveFreeBeforeNullTest()
static Instruction * tryToMoveFreeBeforeNullTest (CallInst & FI, const DataLayout & DL) static
Move the call to free before a NULL test.
Check if this free is accessed after its argument has been test against NULL (property 0). If yes, it is legal to move this call in its predecessor block.
The move is performed only if the block containing the call to free will be removed, i.e.:
it has only one predecessor P, and P has two successors
it contains the call, noops, and an unconditional branch
its successor is the same as its predecessor's successor
The profitability is out-of concern here and this function should be called only if the caller knows this transformation would be profitable (e.g., for code size).
Definition at line 2437 of file InstructionCombining.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::BasicBlock::end(), llvm::CallBase::getArgOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getTerminator(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_UnconditionalBr(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::Instruction::moveBefore(), and llvm::BasicBlock::size().
Referenced by llvm::InstCombiner::visitFree().
TryToSinkInstruction()
static bool TryToSinkInstruction (Instruction * I, BasicBlock * DestBlock) static
Try to move the specified instruction from its current block into the beginning of DestBlock, which can only happen if it's safe to move the instruction past all of the instructions between it and the end of its block.
Definition at line 3112 of file InstructionCombining.cpp.
References assert(), llvm::dbgs(), E, llvm::findDbgUsers(), llvm::IntervalMapImpl::NodeRef::get(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getTerminator(), I, LLVM_DEBUG, llvm::reverse(), and llvm::salvageDebugInfoForDbgValues().
Referenced by llvm::InstCombiner::run().
Variable Documentation
EnableCodeSinking
cl::opt< bool > EnableCodeSinking("instcombine-code-sinking", cl::desc("Enable code sinking"), cl::init(true)) ("instcombine-code-sinking" , cl::desc("Enable code sinking") , cl::init(true)) static
Referenced by llvm::InstCombiner::run().
EnableExpensiveCombines
cl::opt< bool > EnableExpensiveCombines("expensive-combines", cl::desc("Enable expensive instruction combines")) ("expensive-combines" , cl::desc("Enable expensive instruction combines")) static
Referenced by combineInstructionsOverFunction().
false
Combine redundant false
Definition at line 3614 of file InstructionCombining.cpp.
instcombine
instcombine
Definition at line 3613 of file InstructionCombining.cpp.
instructions
Combine redundant instructions
Definition at line 3614 of file InstructionCombining.cpp.
MaxArraySize
cl::opt< unsigned > MaxArraySize("instcombine-maxarray-size", cl::init(1024), cl::desc("Maximum array size considered when doing a combine")) ("instcombine-maxarray-size" , cl::init(1024) , cl::desc("Maximum array size considered when doing a combine")) static
Referenced by combineInstructionsOverFunction().
ShouldLowerDbgDeclare
cl::opt< unsigned > ShouldLowerDbgDeclare("instcombine-lower-dbg-declare", cl::Hidden, cl::init(true)) ("instcombine-lower-dbg-declare" , cl::Hidden , cl::init(true)) static
Referenced by combineInstructionsOverFunction().