LLVM: lib/IR/Instruction.cpp File Reference
Instruction.cpp File Reference
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Instruction.def"
Macros
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_INST(num, opc, clas)
Functions
static bool haveSameSpecialState (const Instruction *I1, const Instruction *I2, bool IgnoreAlignment=false)
Return true if both instructions have the same special state.
Macro Definition Documentation
HANDLE_INST
#define HANDLE_INST (num, opc, clas)
Value:
  case Instruction::opc:                                                       \
    New = cast<clas>(this)->cloneImpl();                                       \
    break;
HANDLE_TERM_INST [1/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<const CLASS *>(this)->getNumSuccessors();
HANDLE_TERM_INST [2/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<const CLASS *>(this)->getSuccessor(idx);
HANDLE_TERM_INST [3/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<CLASS *>(this)->setSuccessor(idx, B);
Function Documentation
haveSameSpecialState()
static bool haveSameSpecialState (const Instruction * I1, const Instruction * I2, bool IgnoreAlignment = false) static
Return true if both instructions have the same special state.
This must be kept in sync with FunctionComparator::cmpOperations in lib/Transforms/IPO/MergeFunctions.cpp.
Definition at line 379 of file Instruction.cpp.
References assert(), and llvm::Instruction::getOpcode().
Referenced by llvm::Instruction::isIdenticalToWhenDefined(), and llvm::Instruction::isSameOperationAs().