LLVM: lib/Transforms/InstCombine/InstCombineCalls.cpp File Reference
InstCombineCalls.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/InstCombine/InstCombineWorklist.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SimplifyLibCalls.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "instcombine"
Functions
STATISTIC (NumSimplified, "Number of library calls simplified")
static Type * getPromotedType (Type *Ty)
Return the specified type promoted as it would be to pass though a va_arg area.
static Constant * getNegativeIsTrueBoolVec (ConstantDataVector *V)
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
static Value * simplifyX86immShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86varShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86pack (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsSigned)
static Value * simplifyX86movmsk (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86addcarry (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86insertps (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86extrq (IntrinsicInst &II, Value *Op0, ConstantInt *CILength, ConstantInt *CIIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86insertq (IntrinsicInst &II, Value *Op0, Value *Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86pshufb (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert pshufb* to shufflevector if the mask is constant.
static Value * simplifyX86vpermilvar (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
static Value * simplifyX86vpermv (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
static Instruction * simplifyInvariantGroupIntrinsic (IntrinsicInst &II, InstCombiner &IC)
This function transforms launder.invariant.group and strip.invariant.group like: launder(launder(x)) -> launder(x) (the result is not the argument) launder(strip(x)) -> launder(x) strip(strip(x)) -> strip(x) (the result is not the argument) strip(launder(x)) -> strip(x) This is legal because it preserves the most recent information about the presence or absence of invariant.group.
static Instruction * foldCttzCtlz (IntrinsicInst &II, InstCombiner &IC)
static Instruction * foldCtpop (IntrinsicInst &II, InstCombiner &IC)
static Instruction * simplifyX86MaskedLoad (IntrinsicInst &II, InstCombiner &IC)
static bool simplifyX86MaskedStore (IntrinsicInst &II, InstCombiner &IC)
static APFloat fmed3AMDGCN (const APFloat &Src0, const APFloat &Src1, const APFloat &Src2)
static Value * simplifyNeonTbl1 (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Convert a table lookup to shufflevector if the mask is constant.
static Value * simplifyNeonVld1 (const IntrinsicInst &II, unsigned MemAlign, InstCombiner::BuilderTy &Builder)
Convert a vector load intrinsic into a simple llvm load instruction.
static bool haveSameOperands (const IntrinsicInst &I, const IntrinsicInst &E, unsigned NumOperands)
static bool removeTriviallyEmptyRange (IntrinsicInst &I, unsigned StartID, unsigned EndID, InstCombiner &IC)
static Instruction * SimplifyNVVMIntrinsic (IntrinsicInst *II, InstCombiner &IC)
static Instruction * canonicalizeConstantArg0ToArg1 (CallInst &Call)
static bool isSafeToEliminateVarargsCast (const CallBase &Call, const DataLayout &DL, const CastInst *const CI, const int ix)
If this cast does not affect the value passed through the varargs area, we can eliminate the use of the cast.
static IntrinsicInst * findInitTrampolineFromAlloca (Value *TrampMem)
static IntrinsicInst * findInitTrampolineFromBB (IntrinsicInst *AdjustTramp, Value *TrampMem)
static IntrinsicInst * findInitTrampoline (Value *Callee)
Variables
static cl::opt< unsigned > GuardWideningWindow ("instcombine-guard-widening-window", cl::init(3), cl::desc("How wide an instruction window to bypass looking for " "another guard"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 73 of file InstCombineCalls.cpp.
Function Documentation
canonicalizeConstantArg0ToArg1()
static Instruction * canonicalizeConstantArg0ToArg1 (CallInst & Call) static
Definition at line 1758 of file InstCombineCalls.cpp.
References assert().
Referenced by llvm::InstCombiner::visitCallInst().
findInitTrampoline()
static IntrinsicInst * findInitTrampoline (Value * Callee) static
Definition at line 4164 of file InstCombineCalls.cpp.
References findInitTrampolineFromAlloca(), findInitTrampolineFromBB(), llvm::IntrinsicInst::getIntrinsicID(), and llvm::User::getOperand().
findInitTrampolineFromAlloca()
static IntrinsicInst * findInitTrampolineFromAlloca (Value * TrampMem) static
Definition at line 4104 of file InstCombineCalls.cpp.
References llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Value::hasOneUse(), llvm::Value::stripPointerCasts(), llvm::Value::user_back(), and llvm::Value::users().
Referenced by findInitTrampoline().
findInitTrampolineFromBB()
static IntrinsicInst * findInitTrampolineFromBB (IntrinsicInst * AdjustTramp, Value * TrampMem) static
Definition at line 4143 of file InstCombineCalls.cpp.
References llvm::BasicBlock::begin(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Instruction::getParent(), I, and llvm::Instruction::mayWriteToMemory().
Referenced by findInitTrampoline().
fmed3AMDGCN()
static APFloat fmed3AMDGCN (const APFloat & Src0, const APFloat & Src1, const APFloat & Src2) static
Definition at line 1379 of file InstCombineCalls.cpp.
References assert().
Referenced by llvm::InstCombiner::visitCallInst().
foldCtpop()
static Instruction * foldCtpop (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 1258 of file InstCombineCalls.cpp.
References assert(), llvm::InstCombiner::computeKnownBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMinPopulation(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getMetadata(), llvm::Value::getType(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::LLVMContext::MD_range, llvm::Instruction::setMetadata(), llvm::User::setOperand(), and X().
Referenced by llvm::InstCombiner::visitCallInst().
foldCttzCtlz()
static Instruction * foldCttzCtlz (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 1182 of file InstCombineCalls.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::InstCombiner::computeKnownBits(), llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxTrailingZeros(), llvm::KnownBits::countMinLeadingZeros(), llvm::KnownBits::countMinTrailingZeros(), llvm::CallInst::Create(), F, llvm::SelectPatternResult::Flavor, llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::InstCombiner::getAssumptionCache(), llvm::Value::getContext(), llvm::InstCombiner::getDataLayout(), llvm::Intrinsic::getDeclaration(), llvm::InstCombiner::getDominatorTree(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getMetadata(), llvm::Instruction::getModule(), llvm::IRBuilderBase::getTrue(), llvm::Value::getType(), llvm::isKnownNonZero(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), llvm::LLVMContext::MD_range, llvm::KnownBits::One, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setMetadata(), llvm::User::setOperand(), llvm::SPF_ABS, llvm::SPF_NABS, X(), and Y().
Referenced by llvm::InstCombiner::visitCallInst().
getNegativeIsTrueBoolVec()
static Constant * getNegativeIsTrueBoolVec (ConstantDataVector * V) static
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
Definition at line 95 of file InstCombineCalls.cpp.
References assert(), llvm::ConstantVector::get(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantDataSequential::getElementType(), llvm::IRBuilderBase::getInt1Ty(), llvm::ConstantDataSequential::getNumElements(), I, and llvm::Type::isIntegerTy().
Referenced by simplifyX86MaskedLoad(), simplifyX86MaskedStore(), and llvm::InstCombiner::visitCallInst().
getPromotedType()
static Type * getPromotedType (Type * Ty) static
Return the specified type promoted as it would be to pass though a va_arg area.
Definition at line 85 of file InstCombineCalls.cpp.
References llvm::Type::getContext(), and llvm::IRBuilderBase::getInt32Ty().
haveSameOperands()
static bool haveSameOperands (const IntrinsicInst & I, const IntrinsicInst & E, unsigned NumOperands) static
Definition at line 1460 of file InstCombineCalls.cpp.
References assert(), and I.
Referenced by removeTriviallyEmptyRange().
isSafeToEliminateVarargsCast()
static bool isSafeToEliminateVarargsCast (const CallBase & Call, const DataLayout & DL, const CastInst *const CI, const int ix) static
If this cast does not affect the value passed through the varargs area, we can eliminate the use of the cast.
Definition at line 4052 of file InstCombineCalls.cpp.
References llvm::User::getOperand(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::isGCRelocate(), llvm::isGCResult(), llvm::CastInst::isLosslessCast(), llvm::Type::isSized(), and llvm::isStatepoint().
removeTriviallyEmptyRange()
static bool removeTriviallyEmptyRange (IntrinsicInst & I, unsigned StartID, unsigned EndID, InstCombiner & IC) static
Definition at line 1479 of file InstCombineCalls.cpp.
References assert(), llvm::InstCombiner::eraseInstFromFunction(), haveSameOperands(), and I.
Referenced by llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitVACopyInst(), and llvm::InstCombiner::visitVAStartInst().
simplifyInvariantGroupIntrinsic()
static Instruction * simplifyInvariantGroupIntrinsic (IntrinsicInst & II, InstCombiner & IC) static
This function transforms launder.invariant.group and strip.invariant.group like: launder(launder(x)) -> launder(x) (the result is not the argument) launder(strip(x)) -> launder(x) strip(strip(x)) -> strip(x) (the result is not the argument) strip(launder(x)) -> strip(x) This is legal because it preserves the most recent information about the presence or absence of invariant.group.
Definition at line 1156 of file InstCombineCalls.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilder< T, Inserter >::CreateAddrSpaceCast(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateLaunderInvariantGroup(), llvm::IRBuilder< T, Inserter >::CreateStripInvariantGroup(), llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm_unreachable, llvm::Value::stripPointerCasts(), and llvm::Value::stripPointerCastsAndInvariantGroups().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyNeonTbl1()
static Value * simplifyNeonTbl1 (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Convert a table lookup to shufflevector if the mask is constant.
This could benefit tbl1 if the mask is { 7,6,5,4,3,2,1,0 }, in which case we could lower the shufflevector with rev64 instructions as it's actually a byte reverse.
Definition at line 1400 of file InstCombineCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Constant::getNullValue(), llvm::Value::getType(), and I.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyNeonVld1()
static Value * simplifyNeonVld1 (const IntrinsicInst & II, unsigned MemAlign, InstCombiner::BuilderTy & Builder) static
Convert a vector load intrinsic into a simple llvm load instruction.
This is beneficial when the underlying object being addressed comes from a constant, since we get constant-folding for free.
Definition at line 1439 of file InstCombineCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), and llvm::isPowerOf2_32().
Referenced by llvm::InstCombiner::visitCallInst().
SimplifyNVVMIntrinsic()
static Instruction * SimplifyNVVMIntrinsic (IntrinsicInst * II, InstCombiner & IC) static
Definition at line 1502 of file InstCombineCalls.cpp.
References llvm::CallBase::arg_operands(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::AtomicRMWInst::FAdd, llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFnAttribute(), llvm::Instruction::getFunction(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Value::getType(), llvm::Attribute::getValueAsString(), and llvm_unreachable.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86addcarry()
static Value * simplifyX86addcarry (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 641 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilder< T, Inserter >::CreateZExt(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::IRBuilderBase::getInt8Ty(), llvm::Value::getType(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), and RetTy.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86extrq()
static Value * simplifyX86extrq (IntrinsicInst & II, Value * Op0, ConstantInt * CILength, ConstantInt * CIIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 727 of file InstCombineCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), F, llvm::DITypeRefArray::get(), llvm::Constant::getAggregateElement(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getIntegerValue(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::ConstantInt::getValue(), and llvm::ConstantInt::isZero().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86immShift()
static Value * simplifyX86immShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 287 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::IRBuilder< T, Inserter >::CreateVectorSplat(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), and llvm_unreachable.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86insertps()
static Value * simplifyX86insertps (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 668 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::SequentialType::getNumElements(), and llvm::Value::getType().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86insertq()
static Value * simplifyX86insertq (IntrinsicInst & II, Value * Op0, Value * Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 821 of file InstCombineCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), F, llvm::DITypeRefArray::get(), llvm::Constant::getAggregateElement(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilderBase::getInt8Ty(), llvm::Constant::getIntegerValue(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getType(), and llvm::ConstantInt::getValue().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86MaskedLoad()
static Instruction * simplifyX86MaskedLoad (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 1298 of file InstCombineCalls.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::DITypeRefArray::get(), getNegativeIsTrueBoolVec(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86MaskedStore()
static bool simplifyX86MaskedStore (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 1334 of file InstCombineCalls.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::InstCombiner::eraseInstFromFunction(), llvm::DITypeRefArray::get(), llvm::IntrinsicInst::getIntrinsicID(), getNegativeIsTrueBoolVec(), llvm::User::getOperand(), and llvm::Value::getType().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86movmsk()
static Value * simplifyX86movmsk (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 611 of file InstCombineCalls.cpp.
References llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::IRBuilder< T, Inserter >::CreateZExtOrTrunc(), llvm::CallBase::getArgOperand(), llvm::VectorType::getInteger(), llvm::IRBuilderBase::getIntNTy(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and llvm::Type::isVectorTy().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86pack()
static Value * simplifyX86pack (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsSigned) static
Definition at line 545 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateICmpSGT(), llvm::IRBuilder< T, Inserter >::CreateICmpSLT(), llvm::IRBuilder< T, Inserter >::CreateSelect(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::IRBuilder< T, Inserter >::CreateTrunc(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::Constant::getIntegerValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::Type::getVectorNumElements().
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86pshufb()
static Value * simplifyX86pshufb (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert pshufb* to shufflevector if the mask is constant.
Definition at line 916 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IRBuilderBase::getInt32Ty(), llvm::Constant::getNullValue(), llvm::Value::getType(), and I.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86varShift()
static Value * simplifyX86varShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 421 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateAShr(), llvm::IRBuilder< T, Inserter >::CreateLShr(), llvm::IRBuilder< T, Inserter >::CreateShl(), llvm::DITypeRefArray::get(), llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Constant::getNullValue(), llvm::Value::getType(), I, Idx, and llvm_unreachable.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86vpermilvar()
static Value * simplifyX86vpermilvar (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
Definition at line 963 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IRBuilderBase::getInt32Ty(), llvm::Value::getType(), and I.
Referenced by llvm::InstCombiner::visitCallInst().
simplifyX86vpermv()
static Value * simplifyX86vpermv (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Definition at line 1013 of file InstCombineCalls.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DITypeRefArray::get(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IRBuilderBase::getInt32Ty(), llvm::Value::getType(), and I.
Referenced by llvm::InstCombiner::visitCallInst().
STATISTIC()
STATISTIC (NumSimplified , "Number of library calls simplified")
Variable Documentation
GuardWideningWindow
cl::opt< unsigned > GuardWideningWindow("instcombine-guard-widening-window", cl::init(3), cl::desc("How wide an instruction window to bypass looking for " "another guard")) ("instcombine-guard-widening-window" , cl::init(3) , cl::desc("How wide an instruction window to bypass looking for " "another guard")) static
Referenced by llvm::InstCombiner::visitCallInst().