LLVM: lib/Transforms/IPO/IPO.cpp File Reference
IPO.cpp File Reference
#include "llvm-c/Transforms/IPO.h"
#include "llvm-c/Initialization.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/AlwaysInliner.h"
#include "llvm/Transforms/IPO/FunctionAttrs.h"
Functions
void LLVMInitializeIPO (LLVMPassRegistryRef R)
void LLVMAddArgumentPromotionPass (LLVMPassManagerRef PM)
void LLVMAddCalledValuePropagationPass (LLVMPassManagerRef PM)
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
void LLVMAddFunctionInliningPass (LLVMPassManagerRef PM)
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
void LLVMAddGlobalOptimizerPass (LLVMPassManagerRef PM)
void LLVMAddIPConstantPropagationPass (LLVMPassManagerRef PM)
void LLVMAddPruneEHPass (LLVMPassManagerRef PM)
void LLVMAddIPSCCPPass (LLVMPassManagerRef PM)
void LLVMAddInternalizePass (LLVMPassManagerRef PM, unsigned AllButMain)
void LLVMAddStripDeadPrototypesPass (LLVMPassManagerRef PM)
void LLVMAddStripSymbolsPass (LLVMPassManagerRef PM)
Function Documentation
LLVMAddAlwaysInlinerPass()
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
Definition at line 93 of file IPO.cpp.
References llvm::createAlwaysInlinerLegacyPass(), and llvm::unwrap().
LLVMAddArgumentPromotionPass()
void LLVMAddArgumentPromotionPass (LLVMPassManagerRef PM)
Definition at line 69 of file IPO.cpp.
References llvm::createArgumentPromotionPass(), and llvm::unwrap().
LLVMAddCalledValuePropagationPass()
void LLVMAddCalledValuePropagationPass (LLVMPassManagerRef PM)
Definition at line 73 of file IPO.cpp.
References llvm::createCalledValuePropagationPass(), and llvm::unwrap().
LLVMAddConstantMergePass()
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
Definition at line 77 of file IPO.cpp.
References llvm::createConstantMergePass(), and llvm::unwrap().
LLVMAddDeadArgEliminationPass()
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
Definition at line 81 of file IPO.cpp.
References llvm::createDeadArgEliminationPass(), and llvm::unwrap().
LLVMAddFunctionAttrsPass()
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
Definition at line 85 of file IPO.cpp.
References llvm::createPostOrderFunctionAttrsLegacyPass(), and llvm::unwrap().
LLVMAddFunctionInliningPass()
void LLVMAddFunctionInliningPass (LLVMPassManagerRef PM)
Definition at line 89 of file IPO.cpp.
References llvm::createFunctionInliningPass(), and llvm::unwrap().
LLVMAddGlobalDCEPass()
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
Definition at line 97 of file IPO.cpp.
References llvm::createGlobalDCEPass(), and llvm::unwrap().
LLVMAddGlobalOptimizerPass()
void LLVMAddGlobalOptimizerPass (LLVMPassManagerRef PM)
Definition at line 101 of file IPO.cpp.
References llvm::createGlobalOptimizerPass(), and llvm::unwrap().
LLVMAddInternalizePass()
void LLVMAddInternalizePass (LLVMPassManagerRef PM, unsigned AllButMain)
Definition at line 117 of file IPO.cpp.
References llvm::createInternalizePass(), and llvm::unwrap().
LLVMAddIPConstantPropagationPass()
void LLVMAddIPConstantPropagationPass (LLVMPassManagerRef PM)
Definition at line 105 of file IPO.cpp.
References llvm::createIPConstantPropagationPass(), and llvm::unwrap().
LLVMAddIPSCCPPass()
void LLVMAddIPSCCPPass (LLVMPassManagerRef PM)
Definition at line 113 of file IPO.cpp.
References llvm::createIPSCCPPass(), and llvm::unwrap().
LLVMAddPruneEHPass()
void LLVMAddPruneEHPass (LLVMPassManagerRef PM)
Definition at line 109 of file IPO.cpp.
References llvm::createPruneEHPass(), and llvm::unwrap().
LLVMAddStripDeadPrototypesPass()
void LLVMAddStripDeadPrototypesPass (LLVMPassManagerRef PM)
Definition at line 124 of file IPO.cpp.
References llvm::createStripDeadPrototypesPass(), and llvm::unwrap().
LLVMAddStripSymbolsPass()
void LLVMAddStripSymbolsPass (LLVMPassManagerRef PM)
Definition at line 128 of file IPO.cpp.
References llvm::createStripSymbolsPass(), and llvm::unwrap().
LLVMInitializeIPO()
void LLVMInitializeIPO (LLVMPassRegistryRef R)
Definition at line 65 of file IPO.cpp.
References llvm::unwrap().