LLVM: lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp File Reference
LegalizeIntegerTypes.cpp File Reference
#include "LegalizeTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "legalize-types"
Functions
static EVT getShiftAmountTyForConstant (unsigned Val, EVT VT, const TargetLowering &TLI, SelectionDAG &DAG)
static std::pair< ISD::CondCode, ISD::NodeType > getExpandedMinMaxOps (int Op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalize-types"
Definition at line 27 of file LegalizeIntegerTypes.cpp.
Function Documentation
getExpandedMinMaxOps()
static std::pair< ISD::CondCode, ISD::NodeType > getExpandedMinMaxOps (int Op) static
Definition at line 2001 of file LegalizeIntegerTypes.cpp.
References llvm_unreachable, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, and llvm::ISD::UMIN.
getShiftAmountTyForConstant()
static EVT getShiftAmountTyForConstant (unsigned Val, EVT VT, const TargetLowering & TLI, SelectionDAG & DAG) static
Definition at line 363 of file LegalizeIntegerTypes.cpp.
References llvm::SelectionDAG::getDataLayout(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::MVT::i32, and llvm::Log2_32().