LLVM: lib/IR/LegacyPassManager.cpp File Reference
LegacyPassManager.cpp File Reference
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManagers.h"
#include "llvm/IR/LegacyPassNameParser.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassTimingInfo.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <unordered_set>
Classes
class llvm::legacy::FunctionPassManagerImpl
FunctionPassManagerImpl manages FPPassManagers.
class llvm::legacy::PassManagerImpl
PassManagerImpl manages MPPassManagers.
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::legacy
Functions
static PassOptionList PrintBefore ("print-before", llvm::cl::desc("Print IR before specified passes"), cl::Hidden)
static PassOptionList PrintAfter ("print-after", llvm::cl::desc("Print IR after specified passes"), cl::Hidden)
static bool ShouldPrintBeforeOrAfterPass (StringRef PassID, PassOptionList &PassesToPrint)
Variables
static cl::opt< enum PassDebugLevel > PassDebugging ("debug-pass", cl::Hidden, cl::desc("Print PassManager debugging information"), cl::values(clEnumVal(Disabled, "disable debug output"), clEnumVal(Arguments, "print pass arguments to pass to 'opt'"), clEnumVal(Structure, "print pass structure before run()"), clEnumVal(Executions, "print pass name before it is executed"), clEnumVal(Details, "print pass details when it is executed")))
static cl::opt< bool > PrintBeforeAll ("print-before-all", llvm::cl::desc("Print IR before each pass"), cl::init(false), cl::Hidden)
static cl::opt< bool > PrintAfterAll ("print-after-all", llvm::cl::desc("Print IR after each pass"), cl::init(false), cl::Hidden)
static cl::opt< bool > PrintModuleScope ("print-module-scope", cl::desc("When printing IR for print-[before|after]{-all} " "always print a module IR"), cl::init(false), cl::Hidden)
static cl::list< std::string > PrintFuncsList ("filter-print-funcs", cl::value_desc("function names"), cl::desc("Only print IR for functions whose name " "match this for all print-[before|after][-all] " "options"), cl::CommaSeparated, cl::Hidden)
Function Documentation
PrintAfter()
static PassOptionList PrintAfter ("print-after" , llvm::cl::desc("Print IR after specified passes") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::insertPass(), and llvm::shouldPrintAfterPass().
PrintBefore()
static PassOptionList PrintBefore ("print-before" , llvm::cl::desc("Print IR before specified passes") , cl::Hidden) static
Referenced by llvm::shouldPrintBeforePass().
ShouldPrintBeforeOrAfterPass()
static bool ShouldPrintBeforeOrAfterPass (StringRef PassID, PassOptionList & PassesToPrint) static
Definition at line 111 of file LegacyPassManager.cpp.
Referenced by llvm::shouldPrintAfterPass(), and llvm::shouldPrintBeforePass().
Variable Documentation
PassDebugging
cl::opt< enum PassDebugLevel > PassDebugging("debug-pass", cl::Hidden, cl::desc("Print PassManager debugging information"), cl::values(clEnumVal(Disabled, "disable debug output"), clEnumVal(Arguments, "print pass arguments to pass to 'opt'"), clEnumVal(Structure, "print pass structure before run()"), clEnumVal(Executions, "print pass name before it is executed"), clEnumVal(Details, "print pass details when it is executed"))) ("debug-pass" , cl::Hidden , cl::desc("Print PassManager debugging information") , cl::values(clEnumVal(Disabled, "disable debug output"), clEnumVal(Arguments, "print pass arguments to pass to 'opt'"), clEnumVal(Structure, "print pass structure before run()"), clEnumVal(Executions, "print pass name before it is executed"), clEnumVal(Details, "print pass details when it is executed"))) static
Referenced by llvm::PMTopLevelManager::dumpArguments(), llvm::PMTopLevelManager::dumpPasses(), llvm::PMDataManager::dumpPassInfo(), llvm::PMDataManager::dumpPreservedSet(), llvm::PMDataManager::dumpRequiredSet(), llvm::PMDataManager::dumpUsedSet(), llvm::PMDataManager::isPassDebuggingExecutionsOrMore(), llvm::PMDataManager::removeDeadPasses(), and llvm::PMDataManager::removeNotPreservedAnalysis().
PrintAfterAll
cl::opt< bool > PrintAfterAll("print-after-all", llvm::cl::desc("Print IR after each pass"), cl::init(false), cl::Hidden) ("print-after-all" , llvm::cl::desc("Print IR after each pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::shouldPrintAfterPass().
PrintBeforeAll
cl::opt< bool > PrintBeforeAll("print-before-all", llvm::cl::desc("Print IR before each pass"), cl::init(false), cl::Hidden) ("print-before-all" , llvm::cl::desc("Print IR before each pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::shouldPrintBeforePass().
PrintFuncsList
cl::list< std::string > PrintFuncsList("filter-print-funcs", cl::value_desc("function names"), cl::desc("Only print IR for functions whose name " "match this for all print-[before|after][-all] " "options"), cl::CommaSeparated, cl::Hidden) ("filter-print-funcs" , cl::value_desc("function names") , cl::desc("Only print IR for functions whose name " "match this for all print-[before|after][-all] " "options") , cl::CommaSeparated , cl::Hidden) static
Referenced by llvm::isFunctionInPrintList().
PrintModuleScope
cl::opt< bool > PrintModuleScope("print-module-scope", cl::desc("When printing IR for print-[before|after]{-all} " "always print a module IR"), cl::init(false), cl::Hidden) ("print-module-scope" , cl::desc("When printing IR for print-[before|after]{-all} " "always print a module IR") , cl::init(false) , cl::Hidden) static
Referenced by llvm::forcePrintModuleIR().