LLVM: lib/CodeGen/GlobalISel/LegalizerHelper.cpp File Reference
LegalizerHelper.cpp File Reference
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "legalizer"
Functions
static std::pair< int, int > getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT &LeftoverTy)
Try to break down OrigTy into NarrowTy sized pieces.
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size)
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, unsigned Size, Type *OpType)
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type *ToType, Type *FromType)
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, Type *ToType, Type *FromType)
static CmpInst::Predicate minMaxToCompare (unsigned Opc)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalizer"
Definition at line 27 of file LegalizerHelper.cpp.
Function Documentation
conversionLibcall()
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, Type * ToType, Type * FromType) static
Definition at line 343 of file LegalizerHelper.cpp.
References llvm::createLibcall(), getConvRTLibDesc(), getReg(), llvm::LegalizeActions::Libcall, and MI.
Referenced by llvm::LegalizerHelper::libcall().
getConvRTLibDesc()
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type * ToType, Type * FromType) static
Definition at line 320 of file LegalizerHelper.cpp.
References llvm::RTLIB::getFPEXT(), llvm::RTLIB::getFPROUND(), llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::RTLIB::getSINTTOFP(), llvm::RTLIB::getUINTTOFP(), llvm::VTSDNode::getVT(), and llvm_unreachable.
Referenced by conversionLibcall().
getNarrowTypeBreakDown()
static std::pair< int, int > getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT & LeftoverTy) static
Try to break down OrigTy into NarrowTy sized pieces.
Returns the number of NarrowTy elements needed to reconstruct OrigTy, with any leftover piece as type LeftoverTy
Returns -1 in the first element of the pair if the breakdown is not satisfiable.
Definition at line 40 of file LegalizerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::LLT::scalar(), llvm::LLT::scalarOrVector(), and Size.
Referenced by llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), and llvm::LegalizerHelper::reduceLoadStoreWidth().
getRTLibDesc()
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size) static
Definition at line 219 of file LegalizerHelper.cpp.
References assert(), llvm_unreachable, and Size.
Referenced by simpleLibcall().
minMaxToCompare()
static CmpInst::Predicate minMaxToCompare (unsigned Opc) static
Definition at line 3313 of file LegalizerHelper.cpp.
References llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by llvm::LegalizerHelper::lowerMinMax().
simpleLibcall()
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, unsigned Size, Type * OpType) static
Definition at line 309 of file LegalizerHelper.cpp.
References llvm::createLibcall(), getReg(), getRTLibDesc(), llvm::LegalizeActions::Libcall, MI, and Size.
Referenced by llvm::LegalizerHelper::libcall().