LLVM: lib/CodeGen/LLVMTargetMachine.cpp File Reference
LLVMTargetMachine.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
Functions
static TargetPassConfig * addPassesToGenerateCode (LLVMTargetMachine &TM, PassManagerBase &PM, bool DisableVerify, MachineModuleInfo &MMI)
addPassesToX helper drives creation and initialization of TargetPassConfig.
Variables
static cl::opt< bool > EnableTrapUnreachable ("trap-unreachable", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Enable generating trap for unreachable"))
Function Documentation
addPassesToGenerateCode()
static TargetPassConfig * addPassesToGenerateCode (LLVMTargetMachine & TM, PassManagerBase & PM, bool DisableVerify, MachineModuleInfo & MMI) static
addPassesToX helper drives creation and initialization of TargetPassConfig.
Definition at line 98 of file LLVMTargetMachine.cpp.
References llvm::legacy::PassManagerBase::add(), llvm::TargetPassConfig::addISelPasses(), llvm::TargetPassConfig::addMachinePasses(), llvm::TargetPassConfig::setDisableVerify(), and llvm::TargetPassConfig::setInitialized().
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
Variable Documentation
EnableTrapUnreachable
cl::opt< bool > EnableTrapUnreachable("trap-unreachable", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Enable generating trap for unreachable")) ("trap-unreachable" , cl::Hidden , cl::ZeroOrMore , cl::init(false) , cl::desc("Enable generating trap for unreachable")) static
Referenced by llvm::LLVMTargetMachine::LLVMTargetMachine().