LLVM: lib/Analysis/Loads.cpp File Reference
Loads.cpp File Reference
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
Functions
static bool isAligned (const Value *Base, const APInt &Offset, unsigned Align, const DataLayout &DL)
static bool isAligned (const Value *Base, unsigned Align, const DataLayout &DL)
static bool isDereferenceableAndAlignedPointer (const Value *V, unsigned Align, const APInt &Size, const DataLayout &DL, const Instruction *CtxI, const DominatorTree *DT, SmallPtrSetImpl< const Value * > &Visited)
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
static bool AreEquivalentAddressValues (const Value *A, const Value *B)
Test if A and B will obviously have the same value.
Function Documentation
AreEquivalentAddressValues()
static bool AreEquivalentAddressValues (const Value * A, const Value * B) static
Test if A and B will obviously have the same value.
This includes recognizing that t0 and t1 will have the same value in code like this:
%t0 = getelementptr \@a, 0, 3
store i32 0, i32* %t0
%t1 = getelementptr \@a, 0, 3
%t2 = load i32* %t1
Definition at line 170 of file Loads.cpp.
References A, and B.
Referenced by llvm::FindAvailablePtrLoadStore(), and llvm::isSafeToLoadUnconditionally().
isAligned() [1/2]
static bool isAligned (const Value * Base, const APInt & Offset, unsigned Align, const DataLayout & DL) static
Definition at line 27 of file Loads.cpp.
References assert(), llvm::DataLayout::getABITypeAlignment(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerElementType(), llvm::Value::getType(), llvm::APInt::isPowerOf2(), llvm::Type::isSized(), and llvm::APInt::uge().
Referenced by isAligned(), isDereferenceableAndAlignedPointer(), llvm::X86InstrInfo::loadRegFromAddr(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::storeRegToAddr(), llvm::X86InstrInfo::storeRegToStackSlot(), and llvm::X86InstrInfo::unfoldMemoryOperand().
isAligned() [2/2]
static bool isAligned (const Value * Base, unsigned Align, const DataLayout & DL) static
Definition at line 44 of file Loads.cpp.
References assert(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSizeInBits(), isAligned(), and llvm::Type::isSized().
isDereferenceableAndAlignedPointer()
static bool isDereferenceableAndAlignedPointer (const Value * V, unsigned Align, const APInt & Size, const DataLayout & DL, const Instruction * CtxI, const DominatorTree * DT, SmallPtrSetImpl< const Value * > & Visited) static
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
Definition at line 53 of file Loads.cpp.
References GEP, llvm::getArgumentAliasingToReturnedPointer(), llvm::APInt::getBoolValue(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::Value::getPointerDereferenceableBytes(), llvm::SmallPtrSetImpl< PtrType >::insert(), isAligned(), isDereferenceableAndAlignedPointer(), llvm::isKnownNonZero(), Size, and llvm::APInt::uge().
Referenced by isDereferenceableAndAlignedPointer(), llvm::isDereferenceablePointer(), and llvm::isSafeToLoadUnconditionally().