LLVM: lib/Transforms/Scalar/LoopStrengthReduce.cpp File Reference
LoopStrengthReduce.cpp File Reference
#include "llvm/Transforms/Scalar/LoopStrengthReduce.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/IVUsers.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ScalarEvolutionNormalization.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/OperandTraits.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <numeric>
#include <map>
#include <utility>
Macros
#define DEBUG_TYPE "loop-reduce"
Functions
static void DoInitialMatch (const SCEV *S, Loop *L, SmallVectorImpl< const SCEV * > &Good, SmallVectorImpl< const SCEV * > &Bad, ScalarEvolution &SE)
Recursion helper for initialMatch.
static bool isAddRecSExtable (const SCEVAddRecExpr *AR, ScalarEvolution &SE)
Return true if the given addrec can be sign-extended without changing its value.
static bool isAddSExtable (const SCEVAddExpr *A, ScalarEvolution &SE)
Return true if the given add can be sign-extended without changing its value.
static bool isMulSExtable (const SCEVMulExpr *M, ScalarEvolution &SE)
Return true if the given mul can be sign-extended without changing its value.
static const SCEV * getExactSDiv (const SCEV *LHS, const SCEV *RHS, ScalarEvolution &SE, bool IgnoreSignificantBits=false)
Return an expression for LHS /s RHS, if it can be determined and if the remainder is known to be zero, or null otherwise.
static int64_t ExtractImmediate (const SCEV *&S, ScalarEvolution &SE)
If S involves the addition of a constant integer value, return that integer value, and mutate S to point to a new SCEV with that value excluded.
static GlobalValue * ExtractSymbol (const SCEV *&S, ScalarEvolution &SE)
If S involves the addition of a GlobalValue address, return that symbol, and mutate S to point to a new SCEV with that value excluded.
static bool isAddressUse (const TargetTransformInfo &TTI, Instruction *Inst, Value *OperandVal)
Returns true if the specified instruction is using the specified value as an address.
static MemAccessTy getAccessType (const TargetTransformInfo &TTI, Instruction *Inst, Value *OperandVal)
Return the type of the memory being accessed.
static bool isExistingPhi (const SCEVAddRecExpr *AR, ScalarEvolution &SE)
Return true if this AddRec is already a phi in its loop.
static bool isHighCostExpansion (const SCEV *S, SmallPtrSetImpl< const SCEV * > &Processed, ScalarEvolution &SE)
Check if expanding this expression is likely to incur significant cost.
static bool DeleteTriviallyDeadInstructions (SmallVectorImpl< WeakTrackingVH > &DeadInsts)
If any of the instructions in the specified set are trivially dead, delete them and see if this makes any of their operands subsequently dead.
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, const LSRUse &LU, const Formula &F)
Check if the addressing mode defined by F is completely folded in LU at isel time.
static unsigned getScalingFactorCost (const TargetTransformInfo &TTI, const LSRUse &LU, const Formula &F, const Loop &L)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, Instruction *Fixup=nullptr)
static unsigned getSetupCost (const SCEV *Reg, unsigned Depth)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale)
static bool isAMCompletelyFolded (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula &F, const Loop &L)
static bool isLegalUse (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale)
Test whether we know how to expand the current formula.
static bool isLegalUse (const TargetTransformInfo &TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula &F)
static bool isAlwaysFoldable (const TargetTransformInfo &TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg)
static bool isAlwaysFoldable (const TargetTransformInfo &TTI, ScalarEvolution &SE, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const SCEV *S, bool HasBaseReg)
static User::op_iterator findIVOperand (User::op_iterator OI, User::op_iterator OE, Loop *L, ScalarEvolution &SE)
Helper for CollectChains that finds an IV operand (computed by an AddRec in this loop) within [OI,OE) or returns OE.
static Value * getWideOperand (Value *Oper)
IVChain logic must consistently peek base TruncInst operands, so wrap it in a convenient helper.
static bool isCompatibleIVType (Value *LVal, Value *RVal)
Return true if we allow an IV chain to include both types.
static const SCEV * getExprBase (const SCEV *S)
Return an approximation of this SCEV expression's "base", or NULL for any constant.
static bool isProfitableChain (IVChain &Chain, SmallPtrSetImpl< Instruction * > &Users, ScalarEvolution &SE)
Return true if the number of registers needed for the chain is estimated to be less than the number required for the individual IV users.
static bool canFoldIVIncExpr (const SCEV *IncExpr, Instruction *UserInst, Value *Operand, const TargetTransformInfo &TTI)
Return true if the IVInc can be folded into an addressing mode.
static const SCEV * CollectSubexprs (const SCEV *S, const SCEVConstant *C, SmallVectorImpl< const SCEV * > &Ops, const Loop *L, ScalarEvolution &SE, unsigned Depth=0)
Split S into subexpressions which can be pulled out into separate registers.
static bool mayUsePostIncMode (const TargetTransformInfo &TTI, LSRUse &LU, const SCEV *S, const Loop *L, ScalarEvolution &SE)
Return true if the SCEV represents a value that may end up as a post-increment operation.
static bool ReduceLoopStrength (Loop *L, IVUsers &IU, ScalarEvolution &SE, DominatorTree &DT, LoopInfo &LI, const TargetTransformInfo &TTI, AssumptionCache &AC, TargetLibraryInfo &LibInfo)
INITIALIZE_PASS_BEGIN (LoopStrengthReduce, "loop-reduce", "Loop Strength Reduction", false, false) INITIALIZE_PASS_END(LoopStrengthReduce
Variables
static const unsigned MaxIVUsers = 200
MaxIVUsers is an arbitrary threshold that provides an early opportunity for bail out.
static cl::opt< bool > EnablePhiElim ("enable-lsr-phielim", cl::Hidden, cl::init(true), cl::desc("Enable LSR phi elimination"))
static cl::opt< bool > InsnsCost ("lsr-insns-cost", cl::Hidden, cl::init(true), cl::desc("Add instruction count to a LSR cost model"))
static cl::opt< bool > LSRExpNarrow ("lsr-exp-narrow", cl::Hidden, cl::init(false), cl::desc("Narrow LSR complex solution using" " expectation of registers number"))
static cl::opt< bool > FilterSameScaledReg ("lsr-filter-same-scaled-reg", cl::Hidden, cl::init(true), cl::desc("Narrow LSR search space by filtering non-optimal formulae" " with the same ScaledReg and Scale"))
static cl::opt< bool > EnableBackedgeIndexing ("lsr-backedge-indexing", cl::Hidden, cl::init(true), cl::desc("Enable the generation of cross iteration indexed memops"))
static cl::opt< unsigned > ComplexityLimit ("lsr-complexity-limit", cl::Hidden, cl::init(std::numeric_limits< uint16_t >::max()), cl::desc("LSR search space complexity limit"))
static cl::opt< unsigned > SetupCostDepthLimit ("lsr-setupcost-depth-limit", cl::Hidden, cl::init(7), cl::desc("The limit on recursion depth for LSRs setup cost"))
static cl::opt< bool > StressIVChain ("stress-ivchain", cl::Hidden, cl::init(false), cl::desc("Stress test LSR IV chains"))
loop reduce
loop Loop Strength Reduction
loop Loop Strength false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-reduce"
Definition at line 124 of file LoopStrengthReduce.cpp.
Function Documentation
canFoldIVIncExpr()
static bool canFoldIVIncExpr (const SCEV * IncExpr, Instruction * UserInst, Value * Operand, const TargetTransformInfo & TTI) static
Return true if the IVInc can be folded into an addressing mode.
Definition at line 3116 of file LoopStrengthReduce.cpp.
References getAccessType(), llvm::SCEVConstant::getAPInt(), llvm::APInt::getMinSignedBits(), llvm::ConstantInt::getSExtValue(), llvm::SCEVConstant::getValue(), isAddressUse(), and isAlwaysFoldable().
CollectSubexprs()
static const SCEV * CollectSubexprs (const SCEV * S, const SCEVConstant * C, SmallVectorImpl< const SCEV * > & Ops, const Loop * L, ScalarEvolution & SE, unsigned Depth = 0) static
Split S into subexpressions which can be pulled out into separate registers.
If C is non-null, multiply each subexpression by C.
Return remainder expression after factoring the subexpressions captured by Ops. If Ops is complete, return NULL.
Definition at line 3481 of file LoopStrengthReduce.cpp.
References C, CollectSubexprs(), llvm::Depth, llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVNAryExpr::getType(), llvm::SCEVAddRecExpr::isAffine(), llvm::SCEV::isZero(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by CollectSubexprs().
DeleteTriviallyDeadInstructions()
static bool DeleteTriviallyDeadInstructions (SmallVectorImpl< WeakTrackingVH > & DeadInsts) static
If any of the instructions in the specified set are trivially dead, delete them and see if this makes any of their operands subsequently dead.
Definition at line 967 of file LoopStrengthReduce.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), I, llvm::isInstructionTriviallyDead(), and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by ReduceLoopStrength().
DoInitialMatch()
static void DoInitialMatch (const SCEV * S, Loop * L, SmallVectorImpl< const SCEV * > & Good, SmallVectorImpl< const SCEV * > & Bad, ScalarEvolution & SE) static
Recursion helper for initialMatch.
Definition at line 389 of file LoopStrengthReduce.cpp.
References DoInitialMatch(), llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getType(), llvm::ScalarEvolution::properlyDominates(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by DoInitialMatch().
ExtractImmediate()
static int64_t ExtractImmediate (const SCEV *& S, ScalarEvolution & SE) static
If S involves the addition of a constant integer value, return that integer value, and mutate S to point to a new SCEV with that value excluded.
Definition at line 745 of file LoopStrengthReduce.cpp.
References C, ExtractImmediate(), llvm::SCEV::FlagAnyWrap, llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), and llvm::ScalarEvolution::getConstant().
Referenced by ExtractImmediate(), and isAlwaysFoldable().
ExtractSymbol()
static GlobalValue * ExtractSymbol (const SCEV *& S, ScalarEvolution & SE) static
If S involves the addition of a GlobalValue address, return that symbol, and mutate S to point to a new SCEV with that value excluded.
Definition at line 771 of file LoopStrengthReduce.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), ExtractSymbol(), llvm::SCEV::FlagAnyWrap, llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), and llvm::ScalarEvolution::getConstant().
Referenced by ExtractSymbol(), and isAlwaysFoldable().
findIVOperand()
static User::op_iterator findIVOperand (User::op_iterator OI, User::op_iterator OE, Loop * L, ScalarEvolution & SE) static
Helper for CollectChains that finds an IV operand (computed by an AddRec in this loop) within [OI,OE) or returns OE.
If IVUsers mapped Instructions to IVStrideUses, we could partially skip this.
Definition at line 2716 of file LoopStrengthReduce.cpp.
References llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getSCEV(), and llvm::ScalarEvolution::isSCEVable().
getAccessType()
static MemAccessTy getAccessType (const TargetTransformInfo & TTI, Instruction * Inst, Value * OperandVal) static
Return the type of the memory being accessed.
Definition at line 837 of file LoopStrengthReduce.cpp.
References llvm::IntervalMapImpl::NodeRef::get(), llvm::IntegerType::get(), llvm::Type::getPointerAddressSpace(), llvm::TargetTransformInfo::getTgtMemIntrinsic(), llvm::Value::getType(), llvm::MemIntrinsicInfo::PtrVal, and SI.
Referenced by canFoldIVIncExpr().
getExactSDiv()
static const SCEV * getExactSDiv (const SCEV * LHS, const SCEV * RHS, ScalarEvolution & SE, bool IgnoreSignificantBits = false) static
Return an expression for LHS /s RHS, if it can be determined and if the remainder is known to be zero, or null otherwise.
If IgnoreSignificantBits is true, expressions like (X * Y) /s Y are simplified to Y, ignoring that the multiplication may overflow, which is useful when the result will be used in a context where the most significant bits are ignored.
Definition at line 658 of file LoopStrengthReduce.cpp.
References C, llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::SCEVConstant::getAPInt(), llvm::ScalarEvolution::getConstant(), getExactSDiv(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEV::getType(), isAddRecSExtable(), isAddSExtable(), isMulSExtable(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::APInt::sdiv(), and llvm::APInt::srem().
Referenced by getExactSDiv().
getExprBase()
static const SCEV * getExprBase (const SCEV * S) static
Return an approximation of this SCEV expression's "base", or NULL for any constant.
Returning the expression itself is conservative. Returning a deeper subexpression is more precise and valid as long as it isn't less complex than another subexpression. For expressions involving multiple unscaled values, we need to return the pointer-type SCEVUnknown. This avoids forming chains across objects, such as: PrevOper==a[i], IVOper==b[i], IVInc==b-a.
Since SCEVUnknown is the rightmost type, and pointers are the rightmost SCEVUnknown, we simply return the rightmost SCEV operand.
Definition at line 2763 of file LoopStrengthReduce.cpp.
References E, getExprBase(), llvm::SCEV::getSCEVType(), I, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scMulExpr, llvm::scSignExtend, llvm::scTruncate, and llvm::scZeroExtend.
Referenced by getExprBase().
getScalingFactorCost()
static unsigned getScalingFactorCost (const TargetTransformInfo & TTI, const LSRUse & LU, const Formula & F, const Loop & L) static
Definition at line 1756 of file LoopStrengthReduce.cpp.
References assert(), F, llvm::TargetTransformInfo::getScalingFactorCost(), isAMCompletelyFolded(), and llvm_unreachable.
getSetupCost()
static unsigned getSetupCost (const SCEV * Reg, unsigned Depth) static
Definition at line 1215 of file LoopStrengthReduce.cpp.
References llvm::Depth, and getSetupCost().
Referenced by getSetupCost().
getWideOperand()
static Value * getWideOperand (Value * Oper) static
IVChain logic must consistently peek base TruncInst operands, so wrap it in a convenient helper.
Definition at line 2735 of file LoopStrengthReduce.cpp.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopStrengthReduce , "loop-reduce" , "Loop Strength Reduction" , false , false)
isAddRecSExtable()
static bool isAddRecSExtable (const SCEVAddRecExpr * AR, ScalarEvolution & SE) static
Return true if the given addrec can be sign-extended without changing its value.
Definition at line 630 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVNAryExpr::getType(), and llvm::ScalarEvolution::getTypeSizeInBits().
Referenced by getExactSDiv().
isAddressUse()
static bool isAddressUse (const TargetTransformInfo & TTI, Instruction * Inst, Value * OperandVal) static
Returns true if the specified instruction is using the specified value as an address.
Definition at line 797 of file LoopStrengthReduce.cpp.
References llvm::TargetTransformInfo::getTgtMemIntrinsic(), llvm::MemIntrinsicInfo::PtrVal, and SI.
Referenced by canFoldIVIncExpr().
isAddSExtable()
static bool isAddSExtable (const SCEVAddExpr * A, ScalarEvolution & SE) static
Return true if the given add can be sign-extended without changing its value.
Definition at line 638 of file LoopStrengthReduce.cpp.
References A, llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), and llvm::ScalarEvolution::getTypeSizeInBits().
Referenced by getExactSDiv().
isAlwaysFoldable() [1/2]
static bool isAlwaysFoldable (const TargetTransformInfo & TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg) static
Definition at line 1793 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
Referenced by canFoldIVIncExpr().
isAlwaysFoldable() [2/2]
static bool isAlwaysFoldable (const TargetTransformInfo & TTI, ScalarEvolution & SE, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const SCEV * S, bool HasBaseReg) static
Definition at line 1815 of file LoopStrengthReduce.cpp.
References ExtractImmediate(), ExtractSymbol(), isAMCompletelyFolded(), and llvm::SCEV::isZero().
isAMCompletelyFolded() [1/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, const LSRUse & LU, const Formula & F) static
Check if the addressing mode defined by F is completely folded in LU at isel time.
This includes address-mode folding and special icmp tricks. This function returns true if LU can accommodate what F defines and up to 1 base + 1 scaled + offset. In other words, if F has several base registers, this function may still return true. Therefore, users still need to account for additional base registers and/or unfolded offsets to derive an accurate cost model.
Definition at line 1739 of file LoopStrengthReduce.cpp.
References F, Fixup, isAMCompletelyFolded(), and llvm::TargetTransformInfo::LSRWithInstrQueries().
Referenced by getScalingFactorCost(), isAlwaysFoldable(), isAMCompletelyFolded(), and isLegalUse().
isAMCompletelyFolded() [2/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula & F, const Loop & L) static
Definition at line 1701 of file LoopStrengthReduce.cpp.
References assert(), F, and isAMCompletelyFolded().
isAMCompletelyFolded() [3/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale) static
Definition at line 1680 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
isAMCompletelyFolded() [4/4]
static bool isAMCompletelyFolded (const TargetTransformInfo & TTI, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, Instruction * Fixup = nullptr) static
Definition at line 1626 of file LoopStrengthReduce.cpp.
References Fixup, llvm::TargetTransformInfo::isLegalAddressingMode(), llvm::TargetTransformInfo::isLegalICmpImmediate(), and llvm_unreachable.
isCompatibleIVType()
static bool isCompatibleIVType (Value * LVal, Value * RVal) static
Return true if we allow an IV chain to include both types.
Definition at line 2742 of file LoopStrengthReduce.cpp.
References llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPointerTy().
isExistingPhi()
static bool isExistingPhi (const SCEVAddRecExpr * AR, ScalarEvolution & SE) static
Return true if this AddRec is already a phi in its loop.
Definition at line 883 of file LoopStrengthReduce.cpp.
References llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getSCEV(), llvm::SCEVNAryExpr::getType(), llvm::ScalarEvolution::isSCEVable(), and llvm::BasicBlock::phis().
Referenced by isHighCostExpansion().
isHighCostExpansion()
static bool isHighCostExpansion (const SCEV * S, SmallPtrSetImpl< const SCEV * > & Processed, ScalarEvolution & SE) static
Check if expanding this expression is likely to incur significant cost.
This is tricky because SCEV doesn't track which expressions are actually computed by the current IR.
We currently allow expansion of IV increments that involve adds, multiplication by constants, and AddRecs from existing phis.
TODO: Allow UDivExpr if we can find an existing IV increment that is an obvious multiple of the UDivExpr.
Definition at line 903 of file LoopStrengthReduce.cpp.
References llvm::Instruction::getOpcode(), llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getSCEVType(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), isExistingPhi(), isHighCostExpansion(), llvm::ScalarEvolution::isSCEVable(), llvm::scConstant, llvm::scSignExtend, llvm::scTruncate, llvm::scUnknown, llvm::scZeroExtend, and llvm::Value::users().
Referenced by isHighCostExpansion().
isLegalUse() [1/2]
static bool isLegalUse (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, const Formula & F) static
Definition at line 1732 of file LoopStrengthReduce.cpp.
References F, and isLegalUse().
isLegalUse() [2/2]
static bool isLegalUse (const TargetTransformInfo & TTI, int64_t MinOffset, int64_t MaxOffset, LSRUse::KindType Kind, MemAccessTy AccessTy, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale) static
Test whether we know how to expand the current formula.
Definition at line 1718 of file LoopStrengthReduce.cpp.
References isAMCompletelyFolded().
Referenced by isLegalUse().
isMulSExtable()
static bool isMulSExtable (const SCEVMulExpr * M, ScalarEvolution & SE) static
Return true if the given mul can be sign-extended without changing its value.
Definition at line 646 of file LoopStrengthReduce.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), and llvm::ScalarEvolution::getTypeSizeInBits().
Referenced by getExactSDiv().
isProfitableChain()
static bool isProfitableChain (IVChain & Chain, SmallPtrSetImpl< Instruction * > & Users, ScalarEvolution & SE) static
Return true if the number of registers needed for the chain is estimated to be less than the number required for the individual IV users.
First prohibit any IV users that keep the IV live across increments (the Users set should be empty). Next count the number and type of increments in the chain.
Chaining IVs can lead to considerable code bloat if ISEL doesn't effectively use postinc addressing modes. Only consider it profitable it the increments can be computed in fewer registers when chained.
TODO: Consider IVInc free if it's already used in another chains.
Definition at line 2831 of file LoopStrengthReduce.cpp.
References assert(), llvm::dbgs(), for(), llvm::ScalarEvolution::getSCEV(), LLVM_DEBUG, StressIVChain, and Users.
mayUsePostIncMode()
static bool mayUsePostIncMode (const TargetTransformInfo & TTI, LSRUse & LU, const SCEV * S, const Loop * L, ScalarEvolution & SE) static
Return true if the SCEV represents a value that may end up as a post-increment operation.
Definition at line 3539 of file LoopStrengthReduce.cpp.
References llvm::Type::getScalarSizeInBits(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEV::getType(), llvm::SCEVNAryExpr::getType(), llvm::TargetTransformInfo::isIndexedLoadLegal(), llvm::TargetTransformInfo::isIndexedStoreLegal(), llvm::ScalarEvolution::isLoopInvariant(), and llvm::TargetTransformInfo::MIM_PostInc.
ReduceLoopStrength()
static bool ReduceLoopStrength (Loop * L, IVUsers & IU, ScalarEvolution & SE, DominatorTree & DT, LoopInfo & LI, const TargetTransformInfo & TTI, AssumptionCache & AC, TargetLibraryInfo & LibInfo) static
Definition at line 5701 of file LoopStrengthReduce.cpp.
References DEBUG_TYPE, llvm::DeleteDeadPHIs(), DeleteTriviallyDeadInstructions(), EnablePhiElim, llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getModule(), llvm::Loop::isLoopSimplifyForm(), and Rewriter.
Referenced by llvm::LoopStrengthReducePass::run().
Variable Documentation
ComplexityLimit
cl::opt< unsigned > ComplexityLimit("lsr-complexity-limit", cl::Hidden, cl::init(std::numeric_limits< uint16_t >::max()), cl::desc("LSR search space complexity limit")) ("lsr-complexity-limit" , cl::Hidden , cl::init(std::numeric_limits< uint16_t >::max()) , cl::desc("LSR search space complexity limit")) static
EnableBackedgeIndexing
cl::opt< bool > EnableBackedgeIndexing("lsr-backedge-indexing", cl::Hidden, cl::init(true), cl::desc("Enable the generation of cross iteration indexed memops")) ("lsr-backedge-indexing" , cl::Hidden , cl::init(true) , cl::desc("Enable the generation of cross iteration indexed memops")) static
EnablePhiElim
cl::opt< bool > EnablePhiElim("enable-lsr-phielim", cl::Hidden, cl::init(true), cl::desc("Enable LSR phi elimination")) ("enable-lsr-phielim" , cl::Hidden , cl::init(true) , cl::desc("Enable LSR phi elimination")) static
Referenced by ReduceLoopStrength().
false
loop Loop Strength false
Definition at line 5768 of file LoopStrengthReduce.cpp.
FilterSameScaledReg
cl::opt< bool > FilterSameScaledReg("lsr-filter-same-scaled-reg", cl::Hidden, cl::init(true), cl::desc("Narrow LSR search space by filtering non-optimal formulae" " with the same ScaledReg and Scale")) ("lsr-filter-same-scaled-reg" , cl::Hidden , cl::init(true) , cl::desc("Narrow LSR search space by filtering non-optimal formulae" " with the same ScaledReg and Scale")) static
InsnsCost
cl::opt< bool > InsnsCost("lsr-insns-cost", cl::Hidden, cl::init(true), cl::desc("Add instruction count to a LSR cost model")) ("lsr-insns-cost" , cl::Hidden , cl::init(true) , cl::desc("Add instruction count to a LSR cost model")) static
LSRExpNarrow
cl::opt< bool > LSRExpNarrow("lsr-exp-narrow", cl::Hidden, cl::init(false), cl::desc("Narrow LSR complex solution using" " expectation of registers number")) ("lsr-exp-narrow" , cl::Hidden , cl::init(false) , cl::desc("Narrow LSR complex solution using" " expectation of registers number")) static
MaxIVUsers
const unsigned MaxIVUsers = 200 static
MaxIVUsers is an arbitrary threshold that provides an early opportunity for bail out.
This threshold is far beyond the number of users that LSR can conceivably solve, so it should not affect generated code, but catches the worst cases before LSR burns too much compile time and stack space.
Definition at line 130 of file LoopStrengthReduce.cpp.
reduce
loop reduce
Definition at line 5767 of file LoopStrengthReduce.cpp.
Reduction
loop Loop Strength Reduction
Definition at line 5768 of file LoopStrengthReduce.cpp.
Referenced by llvm::LoopVectorizationCostModel::collectValuesToIgnore().
SetupCostDepthLimit
cl::opt< unsigned > SetupCostDepthLimit("lsr-setupcost-depth-limit", cl::Hidden, cl::init(7), cl::desc("The limit on recursion depth for LSRs setup cost")) ("lsr-setupcost-depth-limit" , cl::Hidden , cl::init(7) , cl::desc("The limit on recursion depth for LSRs setup cost")) static
StressIVChain
cl::opt< bool > StressIVChain("stress-ivchain", cl::Hidden, cl::init(false), cl::desc("Stress test LSR IV chains")) ("stress-ivchain" , cl::Hidden , cl::init(false) , cl::desc("Stress test LSR IV chains")) static
Referenced by isProfitableChain().