LLVM: lib/Transforms/Scalar/LoopFuse.cpp File Reference
LoopFuse.cpp File Reference
This file implements the loop fusion pass.
#include "llvm/Transforms/Scalar/LoopFuse.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/DependenceAnalysis.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Classes
struct FusionCandidate
This class is used to represent a candidate for loop fusion.
struct FusionCandidateCompare
struct LoopDepthTree
Collect all loops in function at the same nest level, starting at the outermost level.
struct LoopFuser
struct LoopFuseLegacy
Macros
#define DEBUG_TYPE "loop-fusion"
Enumerations
enum FusionDependenceAnalysisChoice { FUSION_DEPENDENCE_ANALYSIS_SCEV , FUSION_DEPENDENCE_ANALYSIS_DA , FUSION_DEPENDENCE_ANALYSIS_ALL }
Functions
STATISTIC (FuseCounter, "Count number of loop fusions performed")
STATISTIC (NumFusionCandidates, "Number of candidates for loop fusion")
STATISTIC (InvalidPreheader, "Loop has invalid preheader")
STATISTIC (InvalidHeader, "Loop has invalid header")
STATISTIC (InvalidExitingBlock, "Loop has invalid exiting blocks")
STATISTIC (InvalidExitBlock, "Loop has invalid exit block")
STATISTIC (InvalidLatch, "Loop has invalid latch")
STATISTIC (InvalidLoop, "Loop is invalid")
STATISTIC (AddressTakenBB, "Basic block has address taken")
STATISTIC (MayThrowException, "Loop may throw an exception")
STATISTIC (ContainsVolatileAccess, "Loop contains a volatile access")
STATISTIC (NotSimplifiedForm, "Loop is not in simplified form")
STATISTIC (InvalidDependencies, "Dependencies prevent fusion")
STATISTIC (InvalidTripCount, "Loop does not have invariant backedge taken count")
STATISTIC (UncomputableTripCount, "SCEV cannot compute trip count of loop")
STATISTIC (NonEqualTripCount, "Candidate trip counts are not the same")
STATISTIC (NonAdjacent, "Candidates are not adjacent")
STATISTIC (NonEmptyPreheader, "Candidate has a non-empty preheader")
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const FusionCandidate &FC)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const FusionCandidateSet &CandSet)
static void printFusionCandidates (const FusionCandidateCollection &FusionCandidates)
static void printLoopVector (const LoopVector &LV)
static void reportLoopFusion (const FusionCandidate &FC0, const FusionCandidate &FC1, OptimizationRemarkEmitter &ORE)
INITIALIZE_PASS_BEGIN (LoopFuseLegacy, "loop-fusion", "Loop Fusion", false, false) FunctionPass *llvm
Variables
static cl::opt< FusionDependenceAnalysisChoice > FusionDependenceAnalysis ("loop-fusion-dependence-analysis", cl::desc("Which dependence analysis should loop fusion use?"), cl::values(clEnumValN(FUSION_DEPENDENCE_ANALYSIS_SCEV, "scev", "Use the scalar evolution interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_DA, "da", "Use the dependence analysis interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_ALL, "all", "Use all available analyses")), cl::Hidden, cl::init(FUSION_DEPENDENCE_ANALYSIS_ALL), cl::ZeroOrMore)
static cl::opt< bool > VerboseFusionDebugging ("loop-fusion-verbose-debug", cl::desc("Enable verbose debugging for Loop Fusion"), cl::Hidden, cl::init(false), cl::ZeroOrMore)
Detailed Description
This file implements the loop fusion pass.
The implementation is largely based on the following document:
  Code Transformations to Augment the Scope of Loop Fusion in a
    Production Compiler
  Christopher Mark Barton
  MSc Thesis
  https://webdocs.cs.ualberta.ca/~amaral/thesis/ChristopherBartonMSc.pdf
The general approach taken is to collect sets of control flow equivalent loops and test whether they can be fused. The necessary conditions for fusion are:
The loops must be adjacent (there cannot be any statements between the two loops).
The loops must be conforming (they must execute the same number of iterations).
The loops must be control flow equivalent (if one loop executes, the other is guaranteed to execute).
There cannot be any negative distance dependencies between the loops. If all of these conditions are satisfied, it is safe to fuse the loops.
This implementation creates FusionCandidates that represent the loop and the necessary information needed by fusion. It then operates on the fusion candidates, first confirming that the candidate is eligible for fusion. The candidates are then collected into control flow equivalent sets, sorted in dominance order. Each set of control flow equivalent candidates is then traversed, attempting to fuse pairs of candidates in the set. If all requirements for fusion are met, the two candidates are fused, creating a new (fused) candidate which is then added back into the set to consider for additional fusion.
This implementation currently does not make any modifications to remove conditions for fusion. Code transformations to make loops conform to each of the conditions for fusion are discussed in more detail in the document above. These can be added to the current implementation in the future.
Definition in file LoopFuse.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-fusion"
Definition at line 67 of file LoopFuse.cpp.
Enumeration Type Documentation
FusionDependenceAnalysisChoice
enum FusionDependenceAnalysisChoice
Enumerator
FUSION_DEPENDENCE_ANALYSIS_SCEV
FUSION_DEPENDENCE_ANALYSIS_DA
FUSION_DEPENDENCE_ANALYSIS_ALL
Definition at line 89 of file LoopFuse.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopFuseLegacy , "loop-fusion" , "Loop Fusion" , false , false)
Definition at line 1205 of file LoopFuse.cpp.
operator<<() [1/2]
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const FusionCandidate & FC) inline
Definition at line 244 of file LoopFuse.cpp.
operator<<() [2/2]
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const FusionCandidateSet & CandSet) inline
Definition at line 306 of file LoopFuse.cpp.
References IT.
printFusionCandidates()
static void printFusionCandidates (const FusionCandidateCollection & FusionCandidates) static
Definition at line 316 of file LoopFuse.cpp.
References llvm::dbgs().
printLoopVector()
static void printLoopVector (const LoopVector & LV) static
Definition at line 386 of file LoopFuse.cpp.
References llvm::dbgs(), and llvm::printLoop().
Referenced by LoopFuser::fuseLoops().
reportLoopFusion()
static void reportLoopFusion (const FusionCandidate & FC0, const FusionCandidate & FC1, OptimizationRemarkEmitter & ORE) static
Definition at line 394 of file LoopFuse.cpp.
References DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), llvm::Value::getName(), llvm::BasicBlock::getParent(), and FusionCandidate::Preheader.
STATISTIC() [1/18]
STATISTIC (AddressTakenBB , "Basic block has address taken")
STATISTIC() [2/18]
STATISTIC (ContainsVolatileAccess , "Loop contains a volatile access")
STATISTIC() [3/18]
STATISTIC (FuseCounter , "Count number of loop fusions performed")
STATISTIC() [4/18]
STATISTIC (InvalidDependencies , "Dependencies prevent fusion")
STATISTIC() [5/18]
STATISTIC (InvalidExitBlock , "Loop has invalid exit block")
STATISTIC() [6/18]
STATISTIC (InvalidExitingBlock , "Loop has invalid exiting blocks")
STATISTIC() [7/18]
STATISTIC (InvalidHeader , "Loop has invalid header")
STATISTIC() [8/18]
STATISTIC (InvalidLatch , "Loop has invalid latch")
STATISTIC() [9/18]
STATISTIC (InvalidLoop , "Loop is invalid")
STATISTIC() [10/18]
STATISTIC (InvalidPreheader , "Loop has invalid preheader")
STATISTIC() [11/18]
STATISTIC (InvalidTripCount , "Loop does not have invariant backedge taken count")
STATISTIC() [12/18]
STATISTIC (MayThrowException , "Loop may throw an exception")
STATISTIC() [13/18]
STATISTIC (NonAdjacent , "Candidates are not adjacent")
STATISTIC() [14/18]
STATISTIC (NonEmptyPreheader , "Candidate has a non-empty preheader")
STATISTIC() [15/18]
STATISTIC (NonEqualTripCount , "Candidate trip counts are not the same")
STATISTIC() [16/18]
STATISTIC (NotSimplifiedForm , "Loop is not in simplified form")
STATISTIC() [17/18]
STATISTIC (NumFusionCandidates , "Number of candidates for loop fusion")
STATISTIC() [18/18]
STATISTIC (UncomputableTripCount , "SCEV cannot compute trip count of loop")
Variable Documentation
FusionDependenceAnalysis
cl::opt< FusionDependenceAnalysisChoice > FusionDependenceAnalysis("loop-fusion-dependence-analysis", cl::desc("Which dependence analysis should loop fusion use?"), cl::values(clEnumValN(FUSION_DEPENDENCE_ANALYSIS_SCEV, "scev", "Use the scalar evolution interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_DA, "da", "Use the dependence analysis interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_ALL, "all", "Use all available analyses")), cl::Hidden, cl::init(FUSION_DEPENDENCE_ANALYSIS_ALL), cl::ZeroOrMore) ("loop-fusion-dependence-analysis" , cl::desc("Which dependence analysis should loop fusion use?") , cl::values(clEnumValN(FUSION_DEPENDENCE_ANALYSIS_SCEV, "scev", "Use the scalar evolution interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_DA, "da", "Use the dependence analysis interface"), clEnumValN(FUSION_DEPENDENCE_ANALYSIS_ALL, "all", "Use all available analyses")) , cl::Hidden , cl::init(FUSION_DEPENDENCE_ANALYSIS_ALL) , cl::ZeroOrMore) static
VerboseFusionDebugging
cl::opt< bool > VerboseFusionDebugging("loop-fusion-verbose-debug", cl::desc("Enable verbose debugging for Loop Fusion"), cl::Hidden, cl::init(false), cl::ZeroOrMore) ("loop-fusion-verbose-debug" , cl::desc("Enable verbose debugging for Loop Fusion") , cl::Hidden , cl::init(false) , cl::ZeroOrMore) static
Referenced by LoopFuser::fuseLoops().