LLVM: lib/CodeGen/MachineOperand.cpp File Reference
MachineOperand.cpp File Reference
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/CodeGen/MIRPrinter.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetMachine.h"
Functions
static const MachineFunction * getMFIfAvailable (const MachineOperand &MO)
static MachineFunction * getMFIfAvailable (MachineOperand &MO)
static void tryToGetTargetInfo (const MachineOperand &MO, const TargetRegisterInfo *&TRI, const TargetIntrinsicInfo *&IntrinsicInfo)
static const char * getTargetIndexName (const MachineFunction &MF, int Index)
static const char * getTargetFlagName (const TargetInstrInfo *TII, unsigned TF)
static void printCFIRegister (unsigned DwarfReg, raw_ostream &OS, const TargetRegisterInfo *TRI)
static void printIRBlockReference (raw_ostream &OS, const BasicBlock &BB, ModuleSlotTracker &MST)
static void printIRValueReference (raw_ostream &OS, const Value &V, ModuleSlotTracker &MST)
static void printSyncScope (raw_ostream &OS, const LLVMContext &Context, SyncScope::ID SSID, SmallVectorImpl< StringRef > &SSNs)
static const char * getTargetMMOFlagName (const TargetInstrInfo &TII, unsigned TMMOFlag)
static void printFrameIndex (raw_ostream &OS, int FrameIndex, bool IsFixed, const MachineFrameInfo *MFI)
static void printCFI (raw_ostream &OS, const MCCFIInstruction &CFI, const TargetRegisterInfo *TRI)
Variables
static cl::opt< int > PrintRegMaskNumRegs ("print-regmask-num-regs", cl::desc("Number of registers to limit to when " "printing regmask operands in IR dumps. " "unlimited = -1"), cl::init(32), cl::Hidden)
Function Documentation
getMFIfAvailable() [1/2]
static const MachineFunction * getMFIfAvailable (const MachineOperand & MO) static
Definition at line 40 of file MachineOperand.cpp.
References llvm::MachineOperand::getParent(), and MI.
Referenced by getMFIfAvailable().
getMFIfAvailable() [2/2]
static MachineFunction * getMFIfAvailable (MachineOperand & MO) static
Definition at line 47 of file MachineOperand.cpp.
References getMFIfAvailable().
getTargetFlagName()
static const char * getTargetFlagName (const TargetInstrInfo * TII, unsigned TF) static
Definition at line 411 of file MachineOperand.cpp.
References llvm::HexagonInstrInfo::getSerializableDirectMachineOperandTargetFlags(), I, and TII.
Referenced by llvm::MachineOperand::printTargetFlags().
getTargetIndexName()
static const char * getTargetIndexName (const MachineFunction & MF, int Index) static
Definition at line 399 of file MachineOperand.cpp.
References assert(), llvm::find_if(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), I, and TII.
Referenced by llvm::MachineOperand::print().
getTargetMMOFlagName()
static const char * getTargetMMOFlagName (const TargetInstrInfo & TII, unsigned TMMOFlag) static
Definition at line 498 of file MachineOperand.cpp.
References I, and TII.
Referenced by llvm::MachineMemOperand::print().
printCFI()
static void printCFI (raw_ostream & OS, const MCCFIInstruction & CFI, const TargetRegisterInfo * TRI) static
Definition at line 618 of file MachineOperand.cpp.
References llvm::StringRef::empty(), llvm::format(), llvm::MCCFIInstruction::getLabel(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm::MCCFIInstruction::getValues(), llvm::MCCFIInstruction::OpAdjustCfaOffset, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpEscape, llvm::MCCFIInstruction::OpNegateRAState, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpRelOffset, llvm::MCCFIInstruction::OpRememberState, llvm::MCCFIInstruction::OpRestore, llvm::MCCFIInstruction::OpRestoreState, llvm::MCCFIInstruction::OpSameValue, llvm::MCCFIInstruction::OpUndefined, llvm::MCCFIInstruction::OpWindowSave, printCFIRegister(), llvm::MachineOperand::printSymbol(), llvm::StringRef::size(), and TRI.
Referenced by llvm::MachineOperand::print().
printCFIRegister()
static void printCFIRegister (unsigned DwarfReg, raw_ostream & OS, const TargetRegisterInfo * TRI) static
Definition at line 421 of file MachineOperand.cpp.
References llvm::printReg(), and TRI.
Referenced by printCFI().
printFrameIndex()
static void printFrameIndex (raw_ostream & OS, int FrameIndex, bool IsFixed, const MachineFrameInfo * MFI) static
Definition at line 509 of file MachineOperand.cpp.
References llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::isFixedObjectIndex(), Name, and llvm::MachineOperand::printStackObjectReference().
Referenced by llvm::MachineOperand::print(), and llvm::MachineMemOperand::print().
printIRBlockReference()
static void printIRBlockReference (raw_ostream & OS, const BasicBlock & BB, ModuleSlotTracker & MST) static
Definition at line 436 of file MachineOperand.cpp.
References F, llvm::ModuleSlotTracker::getCurrentFunction(), llvm::ModuleSlotTracker::getLocalSlot(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::Value::hasName(), llvm::ModuleSlotTracker::incorporateFunction(), llvm::MachineOperand::printIRSlotNumber(), and llvm::printLLVMNameWithoutPrefix().
Referenced by llvm::MachineOperand::print().
printIRValueReference()
static void printIRValueReference (raw_ostream & OS, const Value & V, ModuleSlotTracker & MST) static
Definition at line 459 of file MachineOperand.cpp.
References llvm::ModuleSlotTracker::getCurrentFunction(), llvm::ModuleSlotTracker::getLocalSlot(), llvm::Value::getName(), llvm::Value::hasName(), llvm::Value::printAsOperand(), llvm::MachineOperand::printIRSlotNumber(), and llvm::printLLVMNameWithoutPrefix().
Referenced by llvm::MachineMemOperand::print().
printSyncScope()
static void printSyncScope (raw_ostream & OS, const LLVMContext & Context, SyncScope::ID SSID, SmallVectorImpl< StringRef > & SSNs) static
Definition at line 481 of file MachineOperand.cpp.
References Context, llvm::SmallVectorBase::empty(), llvm::LLVMContext::getSyncScopeNames(), llvm::printEscapedString(), and llvm::SyncScope::System.
Referenced by llvm::MachineMemOperand::print().
tryToGetTargetInfo()
static void tryToGetTargetInfo (const MachineOperand & MO, const TargetRegisterInfo *& TRI, const TargetIntrinsicInfo *& IntrinsicInfo) static
Definition at line 390 of file MachineOperand.cpp.
References getMFIfAvailable(), and TRI.
Variable Documentation
PrintRegMaskNumRegs
cl::opt< int > PrintRegMaskNumRegs("print-regmask-num-regs", cl::desc("Number of registers to limit to when " "printing regmask operands in IR dumps. " "unlimited = -1"), cl::init(32), cl::Hidden) ("print-regmask-num-regs" , cl::desc("Number of registers to limit to when " "printing regmask operands in IR dumps. " "unlimited = -1") , cl::init(32) , cl::Hidden) static
Referenced by llvm::MachineOperand::print().