LLVM: lib/TableGen/Main.cpp File Reference
Main.cpp File Reference
#include "llvm/TableGen/Main.h"
#include "TGParser.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include <algorithm>
#include <cstdio>
#include <system_error>
Functions
static int reportError (const char *ProgName, Twine Msg)
static int createDependencyFile (const TGParser &Parser, const char *argv0)
Create a dependency file for -d option.
Variables
static cl::opt< std::string > OutputFilename ("o", cl::desc("Output filename"), cl::value_desc("filename"), cl::init("-"))
static cl::opt< std::string > DependFilename ("d", cl::desc("Dependency filename"), cl::value_desc("filename"), cl::init(""))
static cl::opt< std::string > InputFilename (cl::Positional, cl::desc("<input file>"), cl::init("-"))
static cl::list< std::string > IncludeDirs ("I", cl::desc("Directory of include files"), cl::value_desc("directory"), cl::Prefix)
static cl::list< std::string > MacroNames ("D", cl::desc("Name of the macro to be defined"), cl::value_desc("macro name"), cl::Prefix)
Function Documentation
createDependencyFile()
static int createDependencyFile (const TGParser & Parser, const char * argv0) static
Create a dependency file for -d option.
This functionality is really only for the benefit of the build system. It is similar to GCC's -M* family of options.
Definition at line 62 of file Main.cpp.
References DependFilename, llvm::sys::fs::F_Text, llvm::TGParser::getDependencies(), llvm::ToolOutputFile::keep(), llvm::ToolOutputFile::os(), OutputFilename, and reportError().
Referenced by llvm::TableGenMain().
reportError()
static int reportError (const char * ProgName, Twine Msg) static
Definition at line 52 of file Main.cpp.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by createDependencyFile(), and llvm::TableGenMain().
Variable Documentation
DependFilename
cl::opt< std::string > DependFilename("d", cl::desc("Dependency filename"), cl::value_desc("filename"), cl::init("")) ("d" , cl::desc("Dependency filename") , cl::value_desc("filename") , cl::init("")) static
Referenced by createDependencyFile(), and llvm::TableGenMain().
IncludeDirs
cl::list< std::string > IncludeDirs("I", cl::desc("Directory of include files"), cl::value_desc("directory"), cl::Prefix) ("I" , cl::desc("Directory of include files") , cl::value_desc("directory") , cl::Prefix) static
Referenced by llvm::TableGenMain().
InputFilename
cl::opt< std::string > InputFilename(cl::Positional, cl::desc("<input file>"), cl::init("-")) (cl::Positional , cl::desc("<input file>") , cl::init("-")) static
Referenced by llvm::TableGenMain().
MacroNames
cl::list< std::string > MacroNames("D", cl::desc("Name of the macro to be defined"), cl::value_desc("macro name"), cl::Prefix) ("D" , cl::desc("Name of the macro to be defined") , cl::value_desc("macro name") , cl::Prefix) static
Referenced by llvm::TableGenMain().
OutputFilename
cl::opt< std::string > OutputFilename("o", cl::desc("Output filename"), cl::value_desc("filename"), cl::init("-")) ("o" , cl::desc("Output filename") , cl::value_desc("filename") , cl::init("-")) static
Referenced by createDependencyFile(), llvm::CreateInfoOutputFile(), llvm::DisplayGraph(), llvm::EmitImportsFiles(), and llvm::TableGenMain().