LLVM: lib/Support/ManagedStatic.cpp File Reference
ManagedStatic.cpp File Reference
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/MutexGuard.h"
#include "llvm/Support/Threading.h"
#include <cassert>
Functions
static void initializeMutex ()
static sys::Mutex * getManagedStaticMutex ()
Variables
static const ManagedStaticBase * StaticList = nullptr
static sys::Mutex * ManagedStaticMutex = nullptr
static llvm::once_flag mutex_init_flag
Function Documentation
getManagedStaticMutex()
static sys::Mutex * getManagedStaticMutex () static
Definition at line 29 of file ManagedStatic.cpp.
References llvm::call_once(), initializeMutex(), ManagedStaticMutex, and mutex_init_flag.
Referenced by llvm::llvm_shutdown(), and llvm::ManagedStaticBase::RegisterManagedStatic().
initializeMutex()
static void initializeMutex () static
Definition at line 25 of file ManagedStatic.cpp.
References ManagedStaticMutex.
Referenced by getManagedStaticMutex().
Variable Documentation
ManagedStaticMutex
sys::Mutex* ManagedStaticMutex = nullptr static
Definition at line 22 of file ManagedStatic.cpp.
Referenced by getManagedStaticMutex(), and initializeMutex().
mutex_init_flag
llvm::once_flag mutex_init_flag static
Definition at line 23 of file ManagedStatic.cpp.
Referenced by getManagedStaticMutex().
StaticList
const ManagedStaticBase* StaticList = nullptr static
Definition at line 21 of file ManagedStatic.cpp.
Referenced by llvm::ManagedStaticBase::destroy(), llvm::llvm_shutdown(), and llvm::ManagedStaticBase::RegisterManagedStatic().