LLVM: lib/Transforms/Utils/Mem2Reg.cpp File Reference
Mem2Reg.cpp File Reference
#include "llvm/Transforms/Utils/Mem2Reg.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/PromoteMemToReg.h"
#include <vector>
Macros
#define DEBUG_TYPE "mem2reg"
Functions
STATISTIC (NumPromoted, "Number of alloca's promoted")
static bool promoteMemoryToRegister (Function &F, DominatorTree &DT, AssumptionCache &AC)
INITIALIZE_PASS_BEGIN (PromoteLegacyPass, "mem2reg", "Promote Memory to " "Register", false, false) INITIALIZE_PASS_END(PromoteLegacyPass
Variables
mem2reg
Promote Memory to Register
Promote Memory to false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mem2reg"
Definition at line 30 of file Mem2Reg.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PromoteLegacyPass , "mem2reg" , "Promote Memory to " "Register" , false , false)
promoteMemoryToRegister()
static bool promoteMemoryToRegister (Function & F, DominatorTree & DT, AssumptionCache & AC) static
Definition at line 34 of file Mem2Reg.cpp.
References llvm::BasicBlock::begin(), E, llvm::BasicBlock::end(), F, I, llvm::isAllocaPromotable(), and llvm::PromoteMemToReg().
Referenced by llvm::PromotePass::run().
STATISTIC()
STATISTIC (NumPromoted , "Number of alloca's promoted")
Variable Documentation
false
Promote Memory to false
Definition at line 110 of file Mem2Reg.cpp.
mem2reg
mem2reg
Definition at line 109 of file Mem2Reg.cpp.
Register
Promote Memory to Register
Definition at line 109 of file Mem2Reg.cpp.