LLVM: lib/Target/Mips/MipsSubtarget.cpp File Reference
MipsSubtarget.cpp File Reference
#include "MipsSubtarget.h"
#include "Mips.h"
#include "MipsMachineFunction.h"
#include "MipsRegisterInfo.h"
#include "MipsTargetMachine.h"
#include "MipsCallLowering.h"
#include "MipsLegalizerInfo.h"
#include "MipsRegisterBankInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "MipsGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "mips-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Variables
static cl::opt< bool > Mixed16_32 ("mips-mixed-16-32", cl::init(false), cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single output file"), cl::Hidden)
static cl::opt< bool > Mips_Os16 ("mips-os16", cl::init(false), cl::desc("Compile all functions that don't use " "floating point as Mips 16"), cl::Hidden)
static cl::opt< bool > Mips16HardFloat ("mips16-hard-float", cl::NotHidden, cl::desc("Enable mips16 hard float."), cl::init(false))
static cl::opt< bool > Mips16ConstantIslands ("mips16-constant-islands", cl::NotHidden, cl::desc("Enable mips16 constant islands."), cl::init(true))
static cl::opt< bool > GPOpt ("mgpopt", cl::Hidden, cl::desc("Enable gp-relative addressing of mips small data items"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-subtarget"
Definition at line 30 of file MipsSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 33 of file MipsSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 32 of file MipsSubtarget.cpp.
Variable Documentation
GPOpt
cl::opt< bool > GPOpt("mgpopt", cl::Hidden, cl::desc("Enable gp-relative addressing of mips small data items")) ("mgpopt" , cl::Hidden , cl::desc("Enable gp-relative addressing of mips small data items")) static
Referenced by llvm::MipsSubtarget::MipsSubtarget().
Mips16ConstantIslands
cl::opt< bool > Mips16ConstantIslands("mips16-constant-islands", cl::NotHidden, cl::desc("Enable mips16 constant islands."), cl::init(true)) ("mips16-constant-islands" , cl::NotHidden , cl::desc("Enable mips16 constant islands.") , cl::init(true)) static
Referenced by llvm::MipsSubtarget::useConstantIslands().
Mips16HardFloat
cl::opt< bool > Mips16HardFloat("mips16-hard-float", cl::NotHidden, cl::desc("Enable mips16 hard float."), cl::init(false)) ("mips16-hard-float" , cl::NotHidden , cl::desc("Enable mips16 hard float.") , cl::init(false)) static
Referenced by llvm::MipsSubtarget::MipsSubtarget().
Mips_Os16
cl::opt< bool > Mips_Os16("mips-os16", cl::init(false), cl::desc("Compile all functions that don't use " "floating point as Mips 16"), cl::Hidden) ("mips-os16" , cl::init(false) , cl::desc("Compile all functions that don't use " "floating point as Mips 16") , cl::Hidden) static
Mixed16_32
cl::opt< bool > Mixed16_32("mips-mixed-16-32", cl::init(false), cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single output file"), cl::Hidden) ("mips-mixed-16-32" , cl::init(false) , cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single output file") , cl::Hidden) static