LLVM: lib/CodeGen/MIRCanonicalizerPass.cpp File Reference
MIRCanonicalizerPass.cpp File Reference
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/raw_ostream.h"
#include <queue>
Classes
class TypedVReg
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "mir-canonicalizer"
Enumerations
enum VRType { RSE_Reg = 0 , RSE_FrameIndex , RSE_NewCandidate }
Functions
INITIALIZE_PASS_BEGIN (MIRCanonicalizer, "mir-canonicalizer", "Rename Register Operands Canonically", false, false) INITIALIZE_PASS_END(MIRCanonicalizer
mir Rename Register Operands static false std::vector< MachineBasicBlock * > GetRPOList (MachineFunction &MF)
static bool rescheduleLexographically (std::vector< MachineInstr * > instructions, MachineBasicBlock *MBB, std::function< MachineBasicBlock::iterator()> getPos)
static bool rescheduleCanonically (unsigned &PseudoIdempotentInstCount, MachineBasicBlock *MBB)
static bool propagateLocalCopies (MachineBasicBlock *MBB)
static std::vector< MachineInstr * > populateCandidates (MachineBasicBlock *MBB)
Here we find our candidates.
static void doCandidateWalk (std::vector< TypedVReg > &VRegs, std::queue< TypedVReg > &RegQueue, std::vector< MachineInstr * > &VisitedMIs, const MachineBasicBlock *MBB)
static std::map< unsigned, unsigned > GetVRegRenameMap (const std::vector< TypedVReg > &VRegs, const std::vector< unsigned > &renamedInOtherBB, MachineRegisterInfo &MRI, NamedVRegCursor &NVC)
static bool doVRegRenaming (std::vector< unsigned > &RenamedInOtherBB, const std::map< unsigned, unsigned > &VRegRenameMap, MachineRegisterInfo &MRI)
static bool doDefKillClear (MachineBasicBlock *MBB)
static bool runOnBasicBlock (MachineBasicBlock *MBB, std::vector< StringRef > &bbNames, std::vector< unsigned > &renamedInOtherBB, unsigned &basicBlockNum, unsigned &VRegGapIndex, NamedVRegCursor &NVC)
Variables
char & llvm::MIRCanonicalizerID = MIRCanonicalizer::ID
static cl::opt< unsigned > CanonicalizeFunctionNumber ("canon-nth-function", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("Function number to canonicalize."))
static cl::opt< unsigned > CanonicalizeBasicBlockNumber ("canon-nth-basicblock", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("BasicBlock number to canonicalize."))
mir canonicalizer
mir Rename Register Operands Canonically
mir Rename Register Operands false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mir-canonicalizer"
Definition at line 42 of file MIRCanonicalizerPass.cpp.
Enumeration Type Documentation
VRType
enum VRType
Enumerator
RSE_Reg
RSE_FrameIndex
RSE_NewCandidate
Definition at line 74 of file MIRCanonicalizerPass.cpp.
Function Documentation
doCandidateWalk()
static void doCandidateWalk (std::vector< TypedVReg > & VRegs, std::queue< TypedVReg > & RegQueue, std::vector< MachineInstr * > & VisitedMIs, const MachineBasicBlock * MBB) static
Definition at line 409 of file MIRCanonicalizerPass.cpp.
References llvm::any_of(), assert(), llvm::dbgs(), E, llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), TypedVReg::getReg(), llvm::MachineFunction::getRegInfo(), I, llvm::MachineOperand::isFI(), llvm::MachineOperand::isReg(), TypedVReg::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MRI, and RSE_FrameIndex.
Referenced by runOnBasicBlock().
doDefKillClear()
static bool doDefKillClear (MachineBasicBlock * MBB) static
Definition at line 625 of file MIRCanonicalizerPass.cpp.
References MI.
Referenced by runOnBasicBlock().
doVRegRenaming()
static bool doVRegRenaming (std::vector< unsigned > & RenamedInOtherBB, const std::map< unsigned, unsigned > & VRegRenameMap, MachineRegisterInfo & MRI) static
Definition at line 597 of file MIRCanonicalizerPass.cpp.
References E, I, and MRI.
Referenced by runOnBasicBlock().
GetRPOList()
mir Rename Register Operands static false std::vector< MachineBasicBlock * > GetRPOList (MachineFunction & MF) static
Definition at line 106 of file MIRCanonicalizerPass.cpp.
GetVRegRenameMap()
static std::map< unsigned, unsigned > GetVRegRenameMap (const std::vector< TypedVReg > & VRegs, const std::vector< unsigned > & renamedInOtherBB, MachineRegisterInfo & MRI, NamedVRegCursor & NVC) static
Definition at line 529 of file MIRCanonicalizerPass.cpp.
References llvm::dbgs(), llvm::find(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, and MRI.
Referenced by runOnBasicBlock().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (MIRCanonicalizer , "mir-canonicalizer" , "Rename Register Operands Canonically" , false , false)
populateCandidates()
static std::vector< MachineInstr * > populateCandidates (MachineBasicBlock * MBB) static
Here we find our candidates.
What makes an interesting candidate? An candidate for a canonicalization tree root is normally any kind of instruction that causes side effects such as a store to memory or a copy to a physical register or a return instruction. We use these as an expression tree root that we walk inorder to build a canonical walk which should result in canoncal vreg renaming.
Definition at line 379 of file MIRCanonicalizerPass.cpp.
References llvm::MachineBasicBlock::begin(), llvm::dbgs(), llvm::Pass::dump(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MI, and MRI.
Referenced by runOnBasicBlock().
propagateLocalCopies()
static bool propagateLocalCopies (MachineBasicBlock * MBB) static
Definition at line 326 of file MIRCanonicalizerPass.cpp.
References Copies, llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineBasicBlock::instrs(), llvm::TargetRegisterInfo::isVirtualRegister(), MI, MRI, and Uses.
Referenced by runOnBasicBlock().
rescheduleCanonically()
static bool rescheduleCanonically (unsigned & PseudoIdempotentInstCount, MachineBasicBlock * MBB) static
Definition at line 159 of file MIRCanonicalizerPass.cpp.
References llvm::MachineBasicBlock::begin(), llvm::dbgs(), llvm::MachineOperand::dump(), E, llvm::find(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MI, MRI, rescheduleLexographically(), and llvm::MachineBasicBlock::splice().
Referenced by runOnBasicBlock().
rescheduleLexographically()
static bool rescheduleLexographically (std::vector< MachineInstr * > instructions, MachineBasicBlock * MBB, std::function< MachineBasicBlock::iterator()> getPos) static
Definition at line 119 of file MIRCanonicalizerPass.cpp.
References llvm::dbgs(), llvm::raw_ostream::flush(), instructions, LLVM_DEBUG, llvm::sort(), and llvm::MachineBasicBlock::splice().
Referenced by rescheduleCanonically().
runOnBasicBlock()
static bool runOnBasicBlock (MachineBasicBlock * MBB, std::vector< StringRef > & bbNames, std::vector< unsigned > & renamedInOtherBB, unsigned & basicBlockNum, unsigned & VRegGapIndex, NamedVRegCursor & NVC) static
Definition at line 647 of file MIRCanonicalizerPass.cpp.
References llvm::MachineBasicBlock::begin(), CanonicalizeBasicBlockNumber, llvm::copy(), llvm::dbgs(), doCandidateWalk(), doDefKillClear(), doVRegRenaming(), llvm::MachineBasicBlock::dump(), llvm::MachineOperand::dump(), llvm::MachineBasicBlock::end(), llvm::find(), llvm::MachineBasicBlock::getName(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), GetVRegRenameMap(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DEBUG, MI, MRI, populateCandidates(), propagateLocalCopies(), rescheduleCanonically(), RSE_FrameIndex, and RSE_NewCandidate.
Referenced by INITIALIZE_PASS().
Variable Documentation
CanonicalizeBasicBlockNumber
cl::opt< unsigned > CanonicalizeBasicBlockNumber("canon-nth-basicblock", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("BasicBlock number to canonicalize.")) ("canon-nth-basicblock" , cl::Hidden , cl::init(~0u) , cl::value_desc("N") , cl::desc("BasicBlock number to canonicalize.")) static
Referenced by runOnBasicBlock().
CanonicalizeFunctionNumber
cl::opt< unsigned > CanonicalizeFunctionNumber("canon-nth-function", cl::Hidden, cl::init(~0u), cl::value_desc("N"), cl::desc("Function number to canonicalize.")) ("canon-nth-function" , cl::Hidden , cl::init(~0u) , cl::value_desc("N") , cl::desc("Function number to canonicalize.")) static
canonicalizer
mir canonicalizer
Definition at line 103 of file MIRCanonicalizerPass.cpp.
Canonically
mir Rename Register Operands Canonically
Definition at line 104 of file MIRCanonicalizerPass.cpp.
false
mir Rename Register Operands false
Definition at line 104 of file MIRCanonicalizerPass.cpp.