LLVM: lib/CodeGen/MIRParser/MIRParser.cpp File Reference
MIRParser.cpp File Reference
#include "llvm/CodeGen/MIRParser/MIRParser.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/AsmParser/SlotMapping.h"
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
#include "llvm/CodeGen/GlobalISel/RegisterBankInfo.h"
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "llvm/CodeGen/MIRYamlMapping.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Target/TargetMachine.h"
#include <memory>
Classes
class llvm::MIRParserImpl
This class implements the parsing of LLVM IR that's embedded inside a MIR file.
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static void handleYAMLDiag (const SMDiagnostic &Diag, void *Context)
static Function * createDummyFunction (StringRef Name, Module &M)
Create an empty function with the given name.
static bool isSSA (const MachineFunction &MF)
template<typename T >
static bool typecheckMDNode (T *&Result, MDNode *Node, const yaml::StringValue &Source, StringRef TypeString, MIRParserImpl &Parser)
Verify that given node is of a certain type. Return true on error.
Function Documentation
createDummyFunction()
static Function * createDummyFunction (StringRef Name, Module & M) static
Create an empty function with the given name.
Definition at line 260 of file MIRParser.cpp.
References Context, llvm::Function::Create(), llvm::BasicBlock::Create(), llvm::GlobalValue::ExternalLinkage, F, llvm::IntervalMapImpl::NodeRef::get(), llvm::IRBuilderBase::getVoidTy(), and Name.
Referenced by llvm::MIRParserImpl::parseMachineFunction().
handleYAMLDiag()
static void handleYAMLDiag (const SMDiagnostic & Diag, void * Context) static
Definition at line 161 of file MIRParser.cpp.
References Context.
isSSA()
static bool isSSA (const MachineFunction & MF) static
Definition at line 306 of file MIRParser.cpp.
References E, llvm::MachineFunction::getRegInfo(), I, llvm::TargetRegisterInfo::index2VirtReg(), and MRI.
typecheckMDNode()
template<typename T > static bool typecheckMDNode (T *& Result, MDNode * Node, const yaml::StringValue & Source, StringRef TypeString, MIRParserImpl & Parser) static
Verify that given node is of a certain type. Return true on error.
Definition at line 763 of file MIRParser.cpp.
References llvm::MIRParserImpl::error().
Referenced by llvm::MIRParserImpl::parseStackObjectsDebugInfo().