LLVM: lib/Object/ModuleSymbolTable.cpp File Reference
ModuleSymbolTable.cpp File Reference
#include "llvm/Object/ModuleSymbolTable.h"
#include "RecordStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
Functions
static void initializeRecordStreamer (const Module &M, function_ref< void(RecordStreamer &)> Init)
Function Documentation
initializeRecordStreamer()
static void initializeRecordStreamer (const Module & M, function_ref< void(RecordStreamer &)> Init) static
Definition at line 71 of file ModuleSymbolTable.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), assert(), llvm::createMCAsmParser(), llvm::MemoryBuffer::getMemBuffer(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::TargetRegistry::lookupTarget(), MRI, llvm::MCObjectFileInfo::setSDKVersion(), llvm::SrcMgr, and TT.
Referenced by llvm::ModuleSymbolTable::CollectAsmSymbols(), and llvm::ModuleSymbolTable::CollectAsmSymvers().