LLVM: llvm::lto Namespace Reference
llvm::lto Namespace Reference
Classes
struct Config
LTO configuration.
class InputFile
An input file.
class LTO
This class implements a resolution-based interface to LLVM's LTO functionality.
struct LTOLLVMContext
A derived class of LLVMContext that initializes itself according to a given Config object.
struct LTOLLVMDiagnosticHandler
class NativeObjectStream
This class wraps an output stream for a native object.
struct SymbolResolution
The resolution for a symbol.
class ThinBackendProc
This class defines the interface to the ThinLTO backend.
Typedefs
using AddBufferFn = std::function< void(unsigned Task, std::unique_ptr< MemoryBuffer > MB)>
This type defines the callback to add a pre-existing native object file (e.g.
using AddStreamFn = std::function< std::unique_ptr< NativeObjectStream >(unsigned Task)>
This type defines the callback to add a native object that is generated on the fly.
using NativeObjectCache = std::function< AddStreamFn(unsigned Task, StringRef Key)>
This is the type of a native object cache.
using ThinBackend = std::function< std::unique_ptr< ThinBackendProc >(Config &C, ModuleSummaryIndex &CombinedIndex, StringMap< GVSummaryMapTy > &ModuleToDefinedGVSummaries, AddStreamFn AddStream, NativeObjectCache Cache)>
A ThinBackend defines what happens after the thin-link phase during ThinLTO.
using IndexWriteCallback = std::function< void(const std::string &)>
This ThinBackend writes individual module indexes to files, instead of running the individual backend jobs.
Functions
Expected< NativeObjectCache > localCache (StringRef CacheDirectoryPath, AddBufferFn AddBuffer)
Create a local file system cache which uses the given cache directory and file callback.
std::string getThinLTOOutputFile (const std::string &Path, const std::string &OldPrefix, const std::string &NewPrefix)
Given the original Path to an output file, replace any path prefix matching OldPrefix with NewPrefix.
Expected< std::unique_ptr< ToolOutputFile > > setupOptimizationRemarks (LLVMContext &Context, StringRef RemarksFilename, StringRef RemarksPasses, StringRef RemarksFormat, bool RemarksWithHotness, int Count=-1)
Setup optimization remarks.
Expected< std::unique_ptr< ToolOutputFile > > setupStatsFile (StringRef StatsFilename)
Setups the output file for saving statistics.
ThinBackend createInProcessThinBackend (unsigned ParallelismLevel)
This ThinBackend runs the individual backend jobs in-process.
ThinBackend createWriteIndexesThinBackend (std::string OldPrefix, std::string NewPrefix, bool ShouldEmitImportsFiles, raw_fd_ostream *LinkedObjectsFile, IndexWriteCallback OnWrite)
Error backend (Config &C, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, std::unique_ptr< Module > M, ModuleSummaryIndex &CombinedIndex)
Runs a regular LTO backend.
Error thinBackend (Config &C, unsigned Task, AddStreamFn AddStream, Module &M, const ModuleSummaryIndex &CombinedIndex, const FunctionImporter::ImportMapTy &ImportList, const GVSummaryMapTy &DefinedGlobals, MapVector< StringRef, BitcodeModule > &ModuleMap)
Runs a ThinLTO backend.
Typedef Documentation
AddBufferFn
using llvm::lto::AddBufferFn = typedef std::function<void(unsigned Task, std::unique_ptr<MemoryBuffer> MB)>
This type defines the callback to add a pre-existing native object file (e.g.
in a cache).
Buffer callbacks must be thread safe.
Definition at line 27 of file Caching.h.
AddStreamFn
using llvm::lto::AddStreamFn = typedef std::function<std::unique_ptr<NativeObjectStream>(unsigned Task)>
This type defines the callback to add a native object that is generated on the fly.
Stream callbacks must be thread safe.
Definition at line 201 of file LTO.h.
IndexWriteCallback
using llvm::lto::IndexWriteCallback = typedef std::function<void(const std::string &)>
This ThinBackend writes individual module indexes to files, instead of running the individual backend jobs.
This backend is for distributed builds where separate processes will invoke the real backends.
To find the path to write the index to, the backend checks if the path has a prefix of OldPrefix; if so, it replaces that prefix with NewPrefix. It then appends ".thinlto.bc" and writes the index to that path. If ShouldEmitImportsFiles is true it also writes a list of imported files to a similar path with ".imports" appended instead. LinkedObjectsFile is an output stream to write the list of object files for the final ThinLTO linking. Can be nullptr. OnWrite is callback which receives module identifier and notifies LTO user that index file for the module (and optionally imports file) was created.
Definition at line 243 of file LTO.h.
NativeObjectCache
using llvm::lto::NativeObjectCache = typedef std::function<AddStreamFn(unsigned Task, StringRef Key)>
This is the type of a native object cache.
To request an item from the cache, pass a unique string as the Key. For hits, the cached file will be added to the link and this function will return AddStreamFn(). For misses, the cache will return a stream callback which must be called at most once to produce content for the stream. The native object stream produced by the stream callback will add the file to the link after the stream is written to.
Clients generally look like this:
if (AddStreamFn AddStream = Cache(Task, Key)) ProduceContent(AddStream);
Definition at line 216 of file LTO.h.
ThinBackend
using llvm::lto::ThinBackend = typedef std::function<std::unique_ptr<ThinBackendProc>(Config &C, ModuleSummaryIndex &CombinedIndex, StringMap<GVSummaryMapTy> &ModuleToDefinedGVSummaries, AddStreamFn AddStream, NativeObjectCache Cache)>
A ThinBackend defines what happens after the thin-link phase during ThinLTO.
The details of this type definition aren't important; clients can only create a ThinBackend using one of the create*ThinBackend() functions below.
Definition at line 222 of file LTO.h.
Function Documentation
backend()
Error llvm::lto::backend (Config & C, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, std::unique_ptr< Module > M, ModuleSummaryIndex & CombinedIndex)
Runs a regular LTO backend.
The regular LTO backend can also act as the regular LTO phase of ThinLTO, which may need to access the combined index.
Definition at line 423 of file LTOBackend.cpp.
References C, codegen(), finalizeOptimizationRemarks(), llvm::Mod, opt, setupOptimizationRemarks(), llvm::splitCodeGen(), and llvm::Expected< T >::takeError().
createInProcessThinBackend()
ThinBackend llvm::lto::createInProcessThinBackend (unsigned ParallelismLevel)
This ThinBackend runs the individual backend jobs in-process.
Definition at line 1140 of file LTO.cpp.
createWriteIndexesThinBackend()
ThinBackend llvm::lto::createWriteIndexesThinBackend (std::string OldPrefix, std::string NewPrefix, bool ShouldEmitImportsFiles, raw_fd_ostream * LinkedObjectsFile, IndexWriteCallback OnWrite)
Definition at line 1228 of file LTO.cpp.
getThinLTOOutputFile()
std::string llvm::lto::getThinLTOOutputFile (const std::string & Path, const std::string & OldPrefix, const std::string & NewPrefix)
Given the original Path to an output file, replace any path prefix matching OldPrefix with NewPrefix.
Also, create the resulting directory if it does not yet exist.
Definition at line 1153 of file LTO.cpp.
References llvm::sys::fs::create_directories(), llvm::StringRef::empty(), llvm::errs(), llvm::sys::path::parent_path(), llvm::sys::path::replace_path_prefix(), and llvm::SmallString< InternalLen >::str().
localCache()
Expected< NativeObjectCache > llvm::lto::localCache (StringRef CacheDirectoryPath, AddBufferFn AddBuffer)
Create a local file system cache which uses the given cache directory and file callback.
This function also creates the cache directory if it does not already exist.
Definition at line 30 of file Caching.cpp.
References llvm::sys::path::append(), llvm::sys::fs::closeFile(), llvm::consumeError(), llvm::sys::fs::convertFDToNativeFile(), llvm::sys::fs::TempFile::create(), llvm::sys::fs::create_directories(), llvm::sys::fs::TempFile::discard(), E, llvm::errorCodeToError(), llvm::errorToErrorCode(), llvm::errs(), llvm::sys::fs::TempFile::FD, llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::MemoryBuffer::getOpenFile(), llvm::handleErrors(), llvm::sys::fs::TempFile::keep(), llvm::sys::fs::OF_UpdateAtime, llvm::sys::fs::openNativeFileForRead(), llvm::sys::fs::owner_read, llvm::sys::fs::owner_write, llvm::report_fatal_error(), llvm::SmallString< InternalLen >::str(), llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::sys::fs::TempFile::TmpName, and llvm::toString().
setupOptimizationRemarks()
Expected< std::unique_ptr< ToolOutputFile > > llvm::lto::setupOptimizationRemarks (LLVMContext & Context, StringRef RemarksFilename, StringRef RemarksPasses, StringRef RemarksFormat, bool RemarksWithHotness, int Count = -1)
Setup optimization remarks.
Definition at line 1344 of file LTO.cpp.
References Context, E, llvm::RemarksFilename, llvm::RemarksFormat, llvm::RemarksPasses, llvm::RemarksWithHotness, llvm::setupOptimizationRemarks(), and llvm::utostr().
Referenced by backend(), llvm::LTOCodeGenerator::optimize(), llvm::ThinLTOCodeGenerator::run(), and thinBackend().
setupStatsFile()
Expected< std::unique_ptr< ToolOutputFile > > llvm::lto::setupStatsFile (StringRef StatsFilename)
Setups the output file for saving statistics.
Definition at line 1363 of file LTO.cpp.
References llvm::StringRef::empty(), llvm::EnableStatistics(), llvm::errorCodeToError(), and llvm::sys::fs::F_None.
Referenced by llvm::LTOCodeGenerator::optimize(), and llvm::lto::LTO::run().
thinBackend()
Error llvm::lto::thinBackend (Config & C, unsigned Task, AddStreamFn AddStream, Module & M, const ModuleSummaryIndex & CombinedIndex, const FunctionImporter::ImportMapTy & ImportList, const GVSummaryMapTy & DefinedGlobals, MapVector< StringRef, BitcodeModule > & ModuleMap)
Runs a ThinLTO backend.
Definition at line 477 of file LTOBackend.cpp.
References assert(), codegen(), llvm::lto::Config::CodeGenOnly, dropDeadSymbols(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), finalizeOptimizationRemarks(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), I, llvm::FunctionImporter::importFunctions(), llvm::Mod, opt, llvm::lto::Config::PostImportModuleHook, llvm::lto::Config::PostInternalizeModuleHook, llvm::lto::Config::PostPromoteModuleHook, llvm::lto::Config::PreOptModuleHook, llvm::lto::Config::RemarksFilename, llvm::lto::Config::RemarksFormat, llvm::lto::Config::RemarksPasses, llvm::lto::Config::RemarksWithHotness, llvm::renameModuleForThinLTO(), setupOptimizationRemarks(), llvm::Expected< T >::takeError(), llvm::thinLTOInternalizeModule(), and llvm::thinLTOResolvePrevailingInModule().