LLVM: llvm::gsym Namespace Reference
llvm::gsym Namespace Reference
Classes
struct AddressRange
A class that represents an address range.
class AddressRanges
The AddressRanges class helps normalize address range collections.
struct FileEntry
Files in GSYM are contained in FileEntry structs where we split the directory and basename into two different strings in the string table.
struct FunctionInfo
Function information in GSYM files encodes information for one contiguous address range.
struct InlineInfo
Inline information stores the name of the inline function along with an array of address ranges.
struct LineEntry
Line entries are used to encode the line tables in FunctionInfo objects.
struct StringTable
String tables in GSYM files are required to start with an empty string at offset zero.
Functions
bool operator== (const FunctionInfo &LHS, const FunctionInfo &RHS)
bool operator!= (const FunctionInfo &LHS, const FunctionInfo &RHS)
bool operator< (const FunctionInfo &LHS, const FunctionInfo &RHS)
This sorting will order things consistently by address range first, but then followed by inlining being valid and line tables.
raw_ostream & operator<< (raw_ostream &OS, const FunctionInfo &R)
bool operator== (const InlineInfo &LHS, const InlineInfo &RHS)
raw_ostream & operator<< (raw_ostream &OS, const InlineInfo &FI)
raw_ostream & operator<< (raw_ostream &OS, const LineEntry &LE)
bool operator== (const LineEntry &LHS, const LineEntry &RHS)
bool operator!= (const LineEntry &LHS, const LineEntry &RHS)
bool operator< (const LineEntry &LHS, const LineEntry &RHS)
raw_ostream & operator<< (raw_ostream &OS, const AddressRange &R)
raw_ostream & operator<< (raw_ostream &OS, const AddressRanges &AR)
raw_ostream & operator<< (raw_ostream &OS, const StringTable &S)
Function Documentation
operator!=() [1/2]
bool llvm::gsym::operator!= (const FunctionInfo & LHS, const FunctionInfo & RHS) inline
Definition at line 78 of file FunctionInfo.h.
operator!=() [2/2]
bool llvm::gsym::operator!= (const LineEntry & LHS, const LineEntry & RHS) inline
Definition at line 40 of file LineEntry.h.
operator<() [1/2]
bool llvm::gsym::operator< (const FunctionInfo & LHS, const FunctionInfo & RHS) inline
This sorting will order things consistently by address range first, but then followed by inlining being valid and line tables.
We might end up with a FunctionInfo from debug info that will have the same range as one from the symbol table, but we want to quickly be able to sort and use the best version when creating the final GSYM file.
Definition at line 86 of file FunctionInfo.h.
References llvm::gsym::FunctionInfo::Inline, llvm::gsym::InlineInfo::isValid(), llvm::gsym::FunctionInfo::Lines, and llvm::gsym::FunctionInfo::Range.
operator<() [2/2]
bool llvm::gsym::operator< (const LineEntry & LHS, const LineEntry & RHS) inline
Definition at line 43 of file LineEntry.h.
References llvm::gsym::LineEntry::Addr.
operator<<() [1/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const AddressRange & R)
Definition at line 43 of file Range.cpp.
References HEX64.
operator<<() [2/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const AddressRanges & AR)
Definition at line 47 of file Range.cpp.
References I, and llvm::gsym::AddressRanges::size().
operator<<() [3/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const FunctionInfo & R)
Definition at line 15 of file FunctionInfo.cpp.
References llvm::gsym::AddressRange::End, HEX32, HEX64, llvm::gsym::FunctionInfo::Inline, llvm::gsym::FunctionInfo::Lines, llvm::gsym::FunctionInfo::Name, llvm::gsym::FunctionInfo::Range, and llvm::gsym::AddressRange::Start.
operator<<() [4/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const InlineInfo & FI)
Definition at line 19 of file InlineInfo.cpp.
References llvm::gsym::InlineInfo::CallFile, llvm::gsym::InlineInfo::Children, HEX32, llvm::gsym::InlineInfo::isValid(), llvm::gsym::InlineInfo::Name, and llvm::gsym::InlineInfo::Ranges.
operator<<() [5/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const LineEntry & LE) inline
Definition at line 32 of file LineEntry.h.
References llvm::gsym::LineEntry::Addr, llvm::gsym::LineEntry::File, llvm::format(), HEX64, and llvm::gsym::LineEntry::Line.
operator<<() [6/6]
raw_ostream & llvm::gsym::operator<< (raw_ostream & OS, const StringTable & S) inline
Definition at line 40 of file StringTable.h.
References llvm::gsym::StringTable::Data, llvm::gsym::StringTable::getString(), and HEX32.
operator==() [1/3]
bool llvm::gsym::operator== (const FunctionInfo & LHS, const FunctionInfo & RHS) inline
Definition at line 74 of file FunctionInfo.h.
References llvm::gsym::FunctionInfo::Inline, llvm::gsym::FunctionInfo::Lines, llvm::gsym::FunctionInfo::Name, and llvm::gsym::FunctionInfo::Range.
operator==() [2/3]
bool llvm::gsym::operator== (const InlineInfo & LHS, const InlineInfo & RHS) inline
Definition at line 67 of file InlineInfo.h.
References llvm::gsym::InlineInfo::CallFile, llvm::gsym::InlineInfo::CallLine, llvm::gsym::InlineInfo::Children, llvm::gsym::InlineInfo::Name, and llvm::gsym::InlineInfo::Ranges.
operator==() [3/3]
bool llvm::gsym::operator== (const LineEntry & LHS, const LineEntry & RHS) inline
Definition at line 37 of file LineEntry.h.
References llvm::gsym::LineEntry::Addr, llvm::gsym::LineEntry::File, and llvm::gsym::LineEntry::Line.