LLVM: llvm::remarks Namespace Reference
llvm::remarks Namespace Reference
Classes
struct Argument
A key-value pair with a debug location that is used to display the remarks at the right place in the source.
class EndOfFileError
struct ParsedStringTable
In-memory representation of the string table parsed from a buffer (e.g.
struct Parser
Parser used to parse a raw buffer to remarks::Remark objects.
struct Remark
A remark type used for both emission and parsing.
struct RemarkLocation
The debug location used to track a remark back to the source file.
struct Serializer
This is the base class for a remark serializer.
struct StringTable
The string table used for serializing remarks.
class YAMLParseError
struct YAMLRemarkParser
Regular YAML to Remark parser.
struct YAMLSerializer
Serialize the remarks to YAML.
Enumerations
enum class Type {
Unknown , Passed , Missed , Analysis ,
AnalysisFPCommute , AnalysisAliasing , Failure , LastTypeValue = Failure
}
The type of the remark.
enum class Format { Unknown , YAML }
The format used for serializing/deserializing remarks.
enum class UseStringTable { No , Yes }
Wether the serializer should use a string table while emitting.
Functions
constexpr StringRef Magic ("REMARKS", 7)
Expected< Format > parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
Expected< std::unique_ptr< Parser > > createRemarkParser (Format ParserFormat, StringRef Buf, Optional< const ParsedStringTable * > StrTab=None)
Variables
constexpr uint64_t Version = 0
Enumeration Type Documentation
Format
enum class llvm::remarks::Format strong
The format used for serializing/deserializing remarks.
Enumerator
Unknown
YAML
Definition at line 25 of file RemarkFormat.h.
Type
enum class llvm::remarks::Type strong
The type of the remark.
Enumerator
Unknown
Passed
Missed
Analysis
AnalysisFPCommute
AnalysisAliasing
Failure
LastTypeValue
Definition at line 53 of file Remark.h.
UseStringTable
enum class llvm::remarks::UseStringTable strong
Wether the serializer should use a string table while emitting.
Enumerator
No
Yes
Definition at line 41 of file RemarkSerializer.h.
Function Documentation
createRemarkParser()
Expected< std::unique_ptr< Parser > > llvm::remarks::createRemarkParser (Format ParserFormat, StringRef Buf, Optional< const ParsedStringTable * > StrTab = None)
Definition at line 51 of file RemarkParser.cpp.
References llvm::createStringError(), llvm_unreachable, Unknown, and YAML.
Magic()
constexpr StringRef llvm::remarks::Magic ("REMARKS" , 7) constexpr
Referenced by llvm::AsmPrinter::emitRemarksSection().
parseFormat()
Expected< Format > llvm::remarks::parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
Definition at line 19 of file RemarkFormat.cpp.
References llvm::StringSwitch< T, R >::Cases(), llvm::createStringError(), llvm::StringRef::data(), llvm::StringSwitch< T, R >::Default(), llvm::LazyValueInfo::Unknown, and YAML.
Referenced by llvm::setupOptimizationRemarks().
Variable Documentation
Version
constexpr uint64_t llvm::remarks::Version = 0 constexpr
Definition at line 26 of file Remark.h.
Referenced by llvm::AsmPrinter::emitRemarksSection().