LLVM: llvm::sys::unicode Namespace Reference
llvm::sys::unicode Namespace Reference
Functions
bool isPrintable (int UCS)
static int charWidth (int UCS)
Gets the number of positions a character is likely to occupy when output on a terminal ("character width").
int columnWidthUTF8 (StringRef Text)
Function Documentation
charWidth()
static int llvm::sys::unicode::charWidth (int UCS) inline static
Gets the number of positions a character is likely to occupy when output on a terminal ("character width").
This depends on the implementation of the terminal, and there's no standard definition of character width. The implementation defines it in a way that is expected to be compatible with a generic Unicode-capable terminal.
Returns
Character width:
ErrorNonPrintableCharacter (-1) for non-printable characters (as identified by isPrintable);
0 for non-spacing and enclosing combining marks;
2 for CJK characters excluding halfwidth forms;
1 for all remaining characters.
Definition at line 226 of file Unicode.cpp.
References isPrintable().
Referenced by columnWidthUTF8().
columnWidthUTF8()
int llvm::sys::unicode::columnWidthUTF8 (StringRef Text)
Definition at line 342 of file Unicode.cpp.
References charWidth(), llvm::ConvertUTF8toUTF32(), and llvm::getNumBytesForUTF8().
Referenced by llvm::sys::locale::columnWidth().
isPrintable()
bool llvm::sys::unicode::isPrintable (int UCS)
Definition at line 22 of file Unicode.cpp.
Referenced by charWidth(), and llvm::sys::locale::isPrint().