LLVM: llvm::opt Namespace Reference
llvm::opt Namespace Reference
Functions
static int StrCmpOptionNameIgnoreCase (const char *A, const char *B)
static int StrCmpOptionName (const char *A, const char *B)
static bool operator< (const OptTable::Info &A, const OptTable::Info &B)
static bool operator< (const OptTable::Info &I, const char *Name)
Function Documentation
operator<() [1/2]
static bool llvm::opt::operator< (const OptTable::Info & A, const OptTable::Info & B) inline static
Definition at line 65 of file OptTable.cpp.
References assert(), N, and StrCmpOptionName().
operator<() [2/2]
static bool llvm::opt::operator< (const OptTable::Info & I, const char * Name) inline static
Definition at line 88 of file OptTable.cpp.
References I, and StrCmpOptionNameIgnoreCase().
StrCmpOptionName()
static int llvm::opt::StrCmpOptionName (const char * A, const char * B) static
Definition at line 59 of file OptTable.cpp.
References N, and StrCmpOptionNameIgnoreCase().
Referenced by operator<().
StrCmpOptionNameIgnoreCase()
static int llvm::opt::StrCmpOptionNameIgnoreCase (const char * A, const char * B) static
Definition at line 38 of file OptTable.cpp.
References X(), and Y().
Referenced by operator<(), and StrCmpOptionName().