LLVM: llvm::objcarc Namespace Reference
llvm::objcarc Namespace Reference
Classes
class ARCRuntimeEntryPoints
Declarations for ObjC runtime functions and constants.
struct BottomUpPtrState
class ProvenanceAnalysis
This is similar to BasicAliasAnalysis, and it uses many of the same techniques, except it uses special ObjC-specific reasoning about pointer relationships.
class PtrState
This class summarizes several per-pointer runtime properties which are propagated through the flow graph.
struct RRInfo
Unidirectional information about either a retain-decrement-use-release sequence or release-use-decrement-retain reverse sequence.
struct TopDownPtrState
Enumerations
enum class ARCRuntimeEntryPointKind {
AutoreleaseRV , Release , Retain , RetainBlock ,
Autorelease , StoreStrong , RetainRV , RetainAutorelease ,
RetainAutoreleaseRV
}
enum DependenceKind {
NeedsPositiveRetainCount , AutoreleasePoolBoundary , CanChangeRetainCount , RetainAutoreleaseDep ,
RetainAutoreleaseRVDep , RetainRVDep
}
Defines different dependence kinds among various ARC constructs.
enum Sequence {
S_None , S_Retain , S_CanRelease , S_Use ,
S_Stop , S_Release , S_MovableRelease
}
A sequence of states that a pointer may go through in which an objc_retain and objc_release are actually needed.
Functions
void FindDependencies (DependenceKind Flavor, const Value *Arg, BasicBlock *StartBB, Instruction *StartInst, SmallPtrSetImpl< Instruction * > &DependingInstructions, SmallPtrSetImpl< const BasicBlock * > &Visited, ProvenanceAnalysis &PA)
Walk up the CFG from StartPos (which is in StartBB) and find local and non-local dependencies on Arg.
bool Depends (DependenceKind Flavor, Instruction *Inst, const Value *Arg, ProvenanceAnalysis &PA)
Test if there can be dependencies on Inst through Arg.
bool CanUse (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Test whether the given instruction can "use" the given pointer's object in a way that requires the reference count to be positive.
bool CanAlterRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Test whether the given instruction can result in a reference count modification (positive or negative) for the pointer's object.
bool CanDecrementRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Returns true if we can not conservatively prove that Inst can not decrement the reference count of Ptr.
static bool CanDecrementRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA)
static void EraseInstruction (Instruction *CI)
Erase the given instruction.
static const Instruction * getreturnRVOperand (const Instruction &Inst, ARCInstKind Class)
If Inst is a ReturnRV and its operand is a call or invoke, return the operand.
template<class PHINodeTy , class VectorTy >
void getEquivalentPHIs (PHINodeTy &PN, VectorTy &PHIList)
Return the list of PHI nodes that are equivalent to PN.
raw_ostream & operator<< (raw_ostream &OS, const Sequence S) LLVM_ATTRIBUTE_UNUSED
Enumeration Type Documentation
ARCRuntimeEntryPointKind
enum class llvm::objcarc::ARCRuntimeEntryPointKind strong
Enumerator
AutoreleaseRV
Release
Retain
RetainBlock
Autorelease
StoreStrong
RetainRV
RetainAutorelease
RetainAutoreleaseRV
Definition at line 41 of file ARCRuntimeEntryPoints.h.
DependenceKind
enum llvm::objcarc::DependenceKind
Defines different dependence kinds among various ARC constructs.
There are several kinds of dependence-like concepts in use here.
Enumerator
NeedsPositiveRetainCount
AutoreleasePoolBoundary
CanChangeRetainCount
RetainAutoreleaseDep
Blocks objc_retainAutorelease.
RetainAutoreleaseRVDep
Blocks objc_retainAutoreleaseReturnValue.
RetainRVDep
Blocks objc_retainAutoreleasedReturnValue.
Definition at line 44 of file DependencyAnalysis.h.
Sequence
enum llvm::objcarc::Sequence
A sequence of states that a pointer may go through in which an objc_retain and objc_release are actually needed.
Enumerator
S_None
S_Retain
objc_retain(x).
S_CanRelease
foo(x) – x could possibly see a ref count decrement.
S_Use
any use of x.
S_Stop
like S_Release, but code motion is stopped.
S_Release
objc_release(x).
S_MovableRelease
objc_release(x), !clang.imprecise_release.
Definition at line 40 of file PtrState.h.
Function Documentation
CanAlterRefCount()
bool llvm::objcarc::CanAlterRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Test whether the given instruction can result in a reference count modification (positive or negative) for the pointer's object.
Definition at line 34 of file DependencyAnalysis.cpp.
References llvm::objcarc::ProvenanceAnalysis::getAA(), and llvm::objcarc::ProvenanceAnalysis::related().
Referenced by CanDecrementRefCount(), Depends(), llvm::objcarc::BottomUpPtrState::HandlePotentialAlterRefCount(), and llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount().
CanDecrementRefCount() [1/2]
static bool llvm::objcarc::CanDecrementRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA) inline static
Definition at line 79 of file DependencyAnalysis.h.
References CanDecrementRefCount().
CanDecrementRefCount() [2/2]
bool llvm::objcarc::CanDecrementRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Returns true if we can not conservatively prove that Inst can not decrement the reference count of Ptr.
Returns false if we can.
Definition at line 67 of file DependencyAnalysis.cpp.
References CanAlterRefCount(), and CanDecrementRefCount().
Referenced by CanDecrementRefCount(), and findRetainForStoreStrongContraction().
CanUse()
bool llvm::objcarc::CanUse (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Test whether the given instruction can "use" the given pointer's object in a way that requires the reference count to be positive.
Definition at line 81 of file DependencyAnalysis.cpp.
References llvm::objcarc::ProvenanceAnalysis::getAA(), and llvm::objcarc::ProvenanceAnalysis::related().
Referenced by Depends(), findSafeStoreForStoreStrongContraction(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), and llvm::objcarc::TopDownPtrState::HandlePotentialUse().
Depends()
bool llvm::objcarc::Depends (DependenceKind Flavor, Instruction * Inst, const Value * Arg, ProvenanceAnalysis & PA)
Test if there can be dependencies on Inst through Arg.
This function only tests dependencies relevant for removing pairs of calls.
Definition at line 131 of file DependencyAnalysis.cpp.
References AutoreleasePoolBoundary, CanAlterRefCount(), CanChangeRetainCount, CanUse(), NeedsPositiveRetainCount, RetainAutoreleaseDep, RetainAutoreleaseRVDep, and RetainRVDep.
Referenced by FindDependencies().
EraseInstruction()
static void llvm::objcarc::EraseInstruction (Instruction * CI) inline static
Erase the given instruction.
Many ObjC calls return their argument verbatim, so if it's such a call and the return value has users, replace them with the argument value.
Definition at line 51 of file ObjCARC.h.
References assert().
FindDependencies()
void llvm::objcarc::FindDependencies (DependenceKind Flavor, const Value * Arg, BasicBlock * StartBB, Instruction * StartInst, SmallPtrSetImpl< Instruction * > & DependingInsts, SmallPtrSetImpl< const BasicBlock * > & Visited, ProvenanceAnalysis & PA)
Walk up the CFG from StartPos (which is in StartBB) and find local and non-local dependencies on Arg.
TODO: Cache results?
Definition at line 219 of file DependencyAnalysis.cpp.
References Depends().
Referenced by FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), and HasSafePathToPredecessorCall().
getEquivalentPHIs()
template<class PHINodeTy , class VectorTy > void llvm::objcarc::getEquivalentPHIs (PHINodeTy & PN, VectorTy & PHIList)
Return the list of PHI nodes that are equivalent to PN.
Definition at line 86 of file ObjCARC.h.
References I, and P.
getreturnRVOperand()
static const Instruction * llvm::objcarc::getreturnRVOperand (const Instruction & Inst, ARCInstKind Class) inline static
If Inst is a ReturnRV and its operand is a call or invoke, return the operand.
Otherwise return null.
Definition at line 73 of file ObjCARC.h.
Referenced by llvm::objcarc::BottomUpPtrState::HandlePotentialUse().
operator<<()
raw_ostream & llvm::objcarc::operator<< (raw_ostream & OS, const Sequence S)
Definition at line 36 of file PtrState.cpp.
References S_CanRelease, S_MovableRelease, S_None, S_Release, S_Retain, S_Stop, and S_Use.