LLVM: llvm::MinidumpYAML Namespace Reference
llvm::MinidumpYAML Namespace Reference
Namespaces
namespace detail
Classes
struct Object
The top level structure representing a minidump object, consisting of a minidump header, and zero or more streams.
struct RawContentStream
A minidump stream represented as a sequence of hex bytes.
struct Stream
The base class for all minidump streams.
struct SystemInfoStream
SystemInfo minidump stream.
struct TextContentStream
A StringRef, which is printed using YAML block notation.
Typedefs
using ModuleListStream = detail::ListStream< detail::ParsedModule >
using ThreadListStream = detail::ListStream< detail::ParsedThread >
using MemoryListStream = detail::ListStream< detail::ParsedMemoryDescriptor >
Functions
void writeAsBinary (Object &Obj, raw_ostream &OS)
Serialize the minidump file represented by Obj to OS in binary form.
Error writeAsBinary (StringRef Yaml, raw_ostream &OS)
Serialize the yaml string as a minidump file to OS in binary form.
Typedef Documentation
MemoryListStream
using llvm::MinidumpYAML::MemoryListStream = typedef detail::ListStream<detail::ParsedMemoryDescriptor>
Definition at line 103 of file MinidumpYAML.h.
ModuleListStream
using llvm::MinidumpYAML::ModuleListStream = typedef detail::ListStream<detail::ParsedModule>
Definition at line 101 of file MinidumpYAML.h.
ThreadListStream
using llvm::MinidumpYAML::ThreadListStream = typedef detail::ListStream<detail::ParsedThread>
Definition at line 102 of file MinidumpYAML.h.
Function Documentation
writeAsBinary() [1/2]
void llvm::MinidumpYAML::writeAsBinary (Object & Obj, raw_ostream & OS)
Serialize the minidump file represented by Obj to OS in binary form.
Definition at line 564 of file MinidumpYAML.cpp.
References llvm::enumerate(), llvm::MinidumpYAML::Object::Header, layout(), llvm::makeArrayRef(), llvm::minidump::Header::NumberOfStreams, llvm::minidump::Header::StreamDirectoryRVA, and llvm::MinidumpYAML::Object::Streams.
Referenced by writeAsBinary().
writeAsBinary() [2/2]
Error llvm::MinidumpYAML::writeAsBinary (StringRef Yaml, raw_ostream & OS)
Serialize the yaml string as a minidump file to OS in binary form.
Definition at line 579 of file MinidumpYAML.cpp.
References llvm::errorCodeToError(), llvm::Error::success(), and writeAsBinary().