LLVM: llvm::X86_MC Namespace Reference
llvm::X86_MC Namespace Reference
Classes
class X86MCInstrAnalysis
Functions
static std::vector< std::pair< uint64_t, uint64_t > > findX86PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents, uint64_t GotPltSectionVA)
static std::vector< std::pair< uint64_t, uint64_t > > findX86_64PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents)
std::string ParseX86Triple (const Triple &TT)
unsigned getDwarfRegFlavour (const Triple &TT, bool isEH)
void initLLVMToSEHAndCVRegMapping (MCRegisterInfo *MRI)
MCSubtargetInfo * createX86MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
Function Documentation
createX86MCSubtargetInfo()
MCSubtargetInfo * llvm::X86_MC::createX86MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 286 of file X86MCTargetDesc.cpp.
References llvm::StringRef::empty(), ParseX86Triple(), and TT.
Referenced by LLVMInitializeX86TargetMC().
findX86_64PltEntries()
static std::vector< std::pair< uint64_t, uint64_t > > llvm::X86_MC::findX86_64PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents) static
Definition at line 486 of file X86MCTargetDesc.cpp.
References llvm::ArrayRef< T >::data(), llvm::support::endian::read32le(), and llvm::ArrayRef< T >::size().
Referenced by llvm::X86_MC::X86MCInstrAnalysis::findPltEntries().
findX86PltEntries()
static std::vector< std::pair< uint64_t, uint64_t > > llvm::X86_MC::findX86PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents, uint64_t GotPltSectionVA) static
Definition at line 460 of file X86MCTargetDesc.cpp.
References llvm::ArrayRef< T >::data(), llvm::support::endian::read32le(), and llvm::ArrayRef< T >::size().
Referenced by llvm::X86_MC::X86MCInstrAnalysis::findPltEntries().
getDwarfRegFlavour()
unsigned llvm::X86_MC::getDwarfRegFlavour (const Triple & TT, bool isEH)
Definition at line 61 of file X86MCTargetDesc.cpp.
References TT, llvm::DWARFFlavour::X86_32_DarwinEH, llvm::DWARFFlavour::X86_32_Generic, llvm::Triple::x86_64, and llvm::DWARFFlavour::X86_64.
Referenced by createX86MCRegisterInfo().
initLLVMToSEHAndCVRegMapping()
void llvm::X86_MC::initLLVMToSEHAndCVRegMapping (MCRegisterInfo * MRI)
Definition at line 73 of file X86MCTargetDesc.cpp.
References llvm::array_lengthof(), I, and MRI.
Referenced by createX86MCRegisterInfo(), and llvm::X86RegisterInfo::X86RegisterInfo().
ParseX86Triple()
std::string llvm::X86_MC::ParseX86Triple (const Triple & TT)
Definition at line 49 of file X86MCTargetDesc.cpp.
References llvm::Triple::CODE16, TT, and llvm::Triple::x86_64.
Referenced by createX86MCSubtargetInfo().