LLVM: llvm::DOT Namespace Reference
llvm::DOT Namespace Reference
Functions
std::string EscapeString (const std::string &Label)
StringRef getColorString (unsigned NodeNumber)
Get a color string for this node number.
Function Documentation
EscapeString()
std::string llvm::DOT::EscapeString (const std::string & Label)
Definition at line 35 of file GraphWriter.cpp.
References LLVM_FALLTHROUGH.
Referenced by llvm::GraphWriter< GraphType >::emitSimpleNode(), printNodeDOT(), llvm::LazyCallGraphDOTPrinterPass::run(), llvm::GraphWriter< GraphType >::writeHeader(), and llvm::GraphWriter< GraphType >::writeNode().
getColorString()
StringRef llvm::DOT::getColorString (unsigned ColorNumber)
Get a color string for this node number.
Simply round-robin selects from a reasonable number of colors.
Definition at line 70 of file GraphWriter.cpp.
Referenced by llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes().