LLVM: llvm::orc::rpc Namespace Reference
llvm::orc::rpc Namespace Reference
Namespaces
namespace detail
Classes
class APICalls
Convenience class for grouping RPC Functions into APIs that can be negotiated as a block.
class APICalls< APICalls< InnerFuncs... >, Funcs... >
class APICalls< Func, Funcs... >
class BadFunctionCall
BadFunctionCall is returned from handleOne when the remote makes a call with an unrecognized function id.
class ConnectionClosed
RPCConnectionClosed is returned from RPC operations if the RPC connection has already been closed due to either an error or graceful disconnection.
class CouldNotNegotiate
This error is returned if the remote does not have a handler installed for the given RPC function.
class Function
class Function< DerivedFunc, RetT(ArgTs...)>
class InvalidSequenceNumberForResponse
InvalidSequenceNumberForResponse is returned from handleOne when a response call arrives with a sequence number that doesn't correspond to any in-flight function call.
class MultiThreadedRPCEndpoint
class ParallelCallGroup
Allows a set of asynchrounous calls to be dispatched, and then waited on as a group.
class RawByteChannel
Interface for byte-streams to be used with RPC.
class ResponseAbandoned
This non-fatal error will be passed to asynchronous result handlers in place of a result if the connection goes down before a result returns, or if the function to be called cannot be negotiated with the remote.
class RPCAsyncDispatch
Asynchronous dispatch for a function on an RPC endpoint.
class RPCFatalError
Base class of all fatal RPC errors (those that necessarily result in the termination of the RPC session).
class RPCFunctionIdAllocator
Allocates RPC function ids during autonegotiation.
class RPCFunctionIdAllocator< T, typename std::enable_if< std::is_integral< T >::value >::type >
This specialization of RPCFunctionIdAllocator provides a default implementation for integral types.
class RPCTypeName
class RPCTypeName< bool >
class RPCTypeName< Error >
class RPCTypeName< Expected< T > >
class RPCTypeName< int16_t >
class RPCTypeName< int32_t >
class RPCTypeName< int64_t >
class RPCTypeName< int8_t >
class RPCTypeName< JITSymbolFlags >
class RPCTypeName< remote::DirectBufferWriter >
class RPCTypeName< std::map< K, V > >
class RPCTypeName< std::pair< T1, T2 > >
class RPCTypeName< std::set< T > >
class RPCTypeName< std::string >
class RPCTypeName< std::tuple< ArgTs... > >
class RPCTypeName< std::vector< T > >
class RPCTypeName< uint16_t >
class RPCTypeName< uint32_t >
class RPCTypeName< uint64_t >
class RPCTypeName< uint8_t >
class RPCTypeName< void >
class RPCTypeNameSequence
TypeNameSequence is a utility for rendering sequences of types to a string by rendering each type, separated by ", ".
class SequenceSerialization
Utility class for serializing sequences of values of varying types.
class SequenceSerialization< ChannelT >
class SequenceSerialization< ChannelT, ArgT >
class SequenceSerialization< ChannelT, ArgT, ArgTs... >
class SequenceTraits
class SerializationTraits
The SerializationTraits<ChannelT, T> class describes how to serialize and deserialize an instance of type T to/from an abstract channel of type ChannelT.
class SerializationTraits< ChannelT, bool, bool, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
class SerializationTraits< ChannelT, Error >
class SerializationTraits< ChannelT, Expected< T >, Error >
SerializationTraits for Expected<T1> from an Error.
class SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >
SerializationTraits for Expected<T1> from an Expected<T2>.
class SerializationTraits< ChannelT, Expected< T1 >, T2 >
SerializationTraits for Expected<T1> from a T2.
class SerializationTraits< ChannelT, JITSymbolFlags >
class SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
class SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >
class SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >
SerializationTraits default specialization for std::pair.
class SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >
class SerializationTraits< ChannelT, std::string, std::string, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
class SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >
class SerializationTraits< ChannelT, std::string, T, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, const char * >::value||std::is_same< T, char * >::value)>::type >
class SerializationTraits< ChannelT, std::tuple< ArgTs... > >
SerializationTraits default specialization for std::tuple.
class SerializationTraits< ChannelT, std::vector< T > >
SerializationTraits default specialization for std::vector.
class SerializationTraits< ChannelT, T, T, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, uint8_t >::value||std::is_same< T, int8_t >::value||std::is_same< T, uint16_t >::value||std::is_same< T, int16_t >::value||std::is_same< T, uint32_t >::value||std::is_same< T, int32_t >::value||std::is_same< T, uint64_t >::value||std::is_same< T, int64_t >::value||std::is_same< T, char >::value)>::type >
class SingleThreadedRPCEndpoint
Functions
template<typename OStream >
OStream & operator<< (OStream &OS, const RPCTypeNameSequence<> &V)
Render an empty TypeNameSequence to an ostream.
template<typename OStream , typename ArgT >
OStream & operator<< (OStream &OS, const RPCTypeNameSequence< ArgT > &V)
Render a TypeNameSequence of a single type to an ostream.
template<typename OStream , typename ArgT1 , typename ArgT2 , typename... ArgTs>
OStream & operator<< (OStream &OS, const RPCTypeNameSequence< ArgT1, ArgT2, ArgTs... > &V)
Render a TypeNameSequence of more than one type to an ostream.
template<typename ChannelT , typename... ArgTs>
Error serializeSeq (ChannelT &C, ArgTs &&... Args)
template<typename ChannelT , typename... ArgTs>
Error deserializeSeq (ChannelT &C, ArgTs &... Args)
template<typename ChannelT , typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor >
void registerErrorSerialization (std::string Name, SerializeFtor &&Serialize, DeserializeFtor &&Deserialize)
Registers a serializer and deserializer for the given error type on the given channel type.
template<typename ChannelT >
void registerStringError ()
Registers serialization/deserialization for StringError.
template<typename Func , typename RPCEndpointT >
RPCAsyncDispatch< RPCEndpointT, Func > rpcAsyncDispatch (RPCEndpointT &Endpoint)
Construct an asynchronous dispatcher from an RPC endpoint and a Func.
Function Documentation
deserializeSeq()
template<typename ChannelT , typename... ArgTs> Error llvm::orc::rpc::deserializeSeq (ChannelT & C, ArgTs &... Args)
Definition at line 324 of file RPCSerialization.h.
References C, and llvm::codeview::serialize_conditional_impl< T, U >::deserialize().
Referenced by llvm::orc::rpc::SerializationTraits< ChannelT, Error >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::vector< T > >::deserialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::string, std::string, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::deserialize(), registerStringError(), and llvm::orc::rpc::RawByteChannel::startReceiveMessage().
operator<<() [1/3]
template<typename OStream , typename ArgT > OStream & llvm::orc::rpc::operator<< (OStream & OS, const RPCTypeNameSequence< ArgT > & V)
Render a TypeNameSequence of a single type to an ostream.
Definition at line 40 of file RPCSerialization.h.
operator<<() [2/3]
template<typename OStream , typename ArgT1 , typename ArgT2 , typename... ArgTs> OStream & llvm::orc::rpc::operator<< (OStream & OS, const RPCTypeNameSequence< ArgT1, ArgT2, ArgTs... > & V)
Render a TypeNameSequence of more than one type to an ostream.
Definition at line 47 of file RPCSerialization.h.
operator<<() [3/3]
template<typename OStream > OStream & llvm::orc::rpc::operator<< (OStream & OS, const RPCTypeNameSequence<> & V)
Render an empty TypeNameSequence to an ostream.
Definition at line 34 of file RPCSerialization.h.
registerErrorSerialization()
template<typename ChannelT , typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor > void llvm::orc::rpc::registerErrorSerialization (std::string Name, SerializeFtor && Serialize, DeserializeFtor && Deserialize)
Registers a serializer and deserializer for the given error type on the given channel type.
Definition at line 445 of file RPCSerialization.h.
References Name.
registerStringError()
template<typename ChannelT > void llvm::orc::rpc::registerStringError ()
Registers serialization/deserialization for StringError.
Definition at line 455 of file RPCSerialization.h.
References C, deserializeSeq(), llvm::StringError::getMessage(), llvm::orc::orcError(), serializeSeq(), llvm::Error::success(), and llvm::orc::UnknownErrorCodeFromRemote.
rpcAsyncDispatch()
template<typename Func , typename RPCEndpointT > RPCAsyncDispatch< RPCEndpointT, Func > llvm::orc::rpc::rpcAsyncDispatch (RPCEndpointT & Endpoint)
Construct an asynchronous dispatcher from an RPC endpoint and a Func.
Definition at line 1555 of file RPCUtils.h.
serializeSeq()
template<typename ChannelT , typename... ArgTs> Error llvm::orc::rpc::serializeSeq (ChannelT & C, ArgTs &&... Args)
Definition at line 318 of file RPCSerialization.h.
References C.
Referenced by llvm::orc::rpc::SerializationTraits< ChannelT, Error >::registerErrorType(), registerStringError(), llvm::orc::rpc::detail::RespondHelper< true >::sendResult(), llvm::orc::rpc::SerializationTraits< ChannelT, JITSymbolFlags >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::vector< T > >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Error >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T >, Error >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, Expected< T1 >, T2 >::serialize(), llvm::orc::rpc::SerializationTraits< ChannelT, std::string, StringRef, typename std::enable_if< std::is_base_of< RawByteChannel, ChannelT >::value >::type >::serialize(), and llvm::orc::rpc::RawByteChannel::startSendMessage().