LLVM: lib/Object/Object.cpp File Reference
Object.cpp File Reference
#include "llvm-c/Object.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/MachOUniversal.h"
Functions
OwningBinary< ObjectFile > * unwrap (LLVMObjectFileRef OF)
LLVMObjectFileRef wrap (const OwningBinary< ObjectFile > *OF)
section_iterator * unwrap (LLVMSectionIteratorRef SI)
LLVMSectionIteratorRef wrap (const section_iterator *SI)
symbol_iterator * unwrap (LLVMSymbolIteratorRef SI)
LLVMSymbolIteratorRef wrap (const symbol_iterator *SI)
relocation_iterator * unwrap (LLVMRelocationIteratorRef SI)
LLVMRelocationIteratorRef wrap (const relocation_iterator *SI)
LLVMBinaryRef LLVMCreateBinary (LLVMMemoryBufferRef MemBuf, LLVMContextRef Context, char **ErrorMessage)
Create a binary file from the given memory buffer.
LLVMMemoryBufferRef LLVMBinaryCopyMemoryBuffer (LLVMBinaryRef BR)
Retrieves a copy of the memory buffer associated with this object file.
void LLVMDisposeBinary (LLVMBinaryRef BR)
Dispose of a binary file.
LLVMBinaryType LLVMBinaryGetType (LLVMBinaryRef BR)
Retrieve the specific type of a binary.
LLVMBinaryRef LLVMMachOUniversalBinaryCopyObjectForArch (LLVMBinaryRef BR, const char *Arch, size_t ArchLen, char **ErrorMessage)
LLVMSectionIteratorRef LLVMObjectFileCopySectionIterator (LLVMBinaryRef BR)
Retrieve a copy of the section iterator for this object file.
LLVMBool LLVMObjectFileIsSectionIteratorAtEnd (LLVMBinaryRef BR, LLVMSectionIteratorRef SI)
Returns whether the given section iterator is at the end.
LLVMSymbolIteratorRef LLVMObjectFileCopySymbolIterator (LLVMBinaryRef BR)
Retrieve a copy of the symbol iterator for this object file.
LLVMBool LLVMObjectFileIsSymbolIteratorAtEnd (LLVMBinaryRef BR, LLVMSymbolIteratorRef SI)
Returns whether the given symbol iterator is at the end.
LLVMObjectFileRef LLVMCreateObjectFile (LLVMMemoryBufferRef MemBuf)
Deprecated: Use LLVMCreateBinary instead.
void LLVMDisposeObjectFile (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMDisposeBinary instead.
LLVMSectionIteratorRef LLVMGetSections (LLVMObjectFileRef OF)
Deprecated: Use LLVMObjectFileCopySectionIterator instead.
void LLVMDisposeSectionIterator (LLVMSectionIteratorRef SI)
LLVMBool LLVMIsSectionIteratorAtEnd (LLVMObjectFileRef OF, LLVMSectionIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSectionIteratorAtEnd instead.
void LLVMMoveToNextSection (LLVMSectionIteratorRef SI)
void LLVMMoveToContainingSection (LLVMSectionIteratorRef Sect, LLVMSymbolIteratorRef Sym)
LLVMSymbolIteratorRef LLVMGetSymbols (LLVMObjectFileRef OF)
Deprecated: Use LLVMObjectFileCopySymbolIterator instead.
void LLVMDisposeSymbolIterator (LLVMSymbolIteratorRef SI)
LLVMBool LLVMIsSymbolIteratorAtEnd (LLVMObjectFileRef OF, LLVMSymbolIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSymbolIteratorAtEnd instead.
void LLVMMoveToNextSymbol (LLVMSymbolIteratorRef SI)
const char * LLVMGetSectionName (LLVMSectionIteratorRef SI)
uint64_t LLVMGetSectionSize (LLVMSectionIteratorRef SI)
const char * LLVMGetSectionContents (LLVMSectionIteratorRef SI)
uint64_t LLVMGetSectionAddress (LLVMSectionIteratorRef SI)
LLVMBool LLVMGetSectionContainsSymbol (LLVMSectionIteratorRef SI, LLVMSymbolIteratorRef Sym)
LLVMRelocationIteratorRef LLVMGetRelocations (LLVMSectionIteratorRef Section)
void LLVMDisposeRelocationIterator (LLVMRelocationIteratorRef SI)
LLVMBool LLVMIsRelocationIteratorAtEnd (LLVMSectionIteratorRef Section, LLVMRelocationIteratorRef SI)
void LLVMMoveToNextRelocation (LLVMRelocationIteratorRef SI)
const char * LLVMGetSymbolName (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetSymbolAddress (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetSymbolSize (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetRelocationOffset (LLVMRelocationIteratorRef RI)
LLVMSymbolIteratorRef LLVMGetRelocationSymbol (LLVMRelocationIteratorRef RI)
uint64_t LLVMGetRelocationType (LLVMRelocationIteratorRef RI)
const char * LLVMGetRelocationTypeName (LLVMRelocationIteratorRef RI)
const char * LLVMGetRelocationValueString (LLVMRelocationIteratorRef RI)
Function Documentation
unwrap() [1/4]
OwningBinary< ObjectFile > * unwrap (LLVMObjectFileRef OF) inline
Definition at line 23 of file Object.cpp.
Referenced by LLVMBinaryCopyMemoryBuffer(), LLVMBinaryGetType(), LLVMCreateBinary(), LLVMCreateObjectFile(), LLVMDisposeBinary(), LLVMDisposeObjectFile(), LLVMDisposeRelocationIterator(), LLVMDisposeSectionIterator(), LLVMDisposeSymbolIterator(), LLVMGetRelocationOffset(), LLVMGetRelocations(), LLVMGetRelocationSymbol(), LLVMGetRelocationType(), LLVMGetRelocationTypeName(), LLVMGetSectionAddress(), LLVMGetSectionContainsSymbol(), LLVMGetSectionContents(), LLVMGetSectionName(), LLVMGetSections(), LLVMGetSectionSize(), LLVMGetSymbolAddress(), LLVMGetSymbolName(), LLVMGetSymbols(), LLVMGetSymbolSize(), LLVMIsRelocationIteratorAtEnd(), LLVMIsSectionIteratorAtEnd(), LLVMIsSymbolIteratorAtEnd(), LLVMMachOUniversalBinaryCopyObjectForArch(), LLVMMoveToContainingSection(), LLVMMoveToNextRelocation(), LLVMMoveToNextSection(), LLVMMoveToNextSymbol(), LLVMObjectFileCopySectionIterator(), LLVMObjectFileCopySymbolIterator(), LLVMObjectFileIsSectionIteratorAtEnd(), and LLVMObjectFileIsSymbolIteratorAtEnd().
unwrap() [2/4]
relocation_iterator * unwrap (LLVMRelocationIteratorRef SI) inline
Definition at line 52 of file Object.cpp.
References SI.
unwrap() [3/4]
section_iterator * unwrap (LLVMSectionIteratorRef SI) inline
Definition at line 32 of file Object.cpp.
References SI.
unwrap() [4/4]
symbol_iterator * unwrap (LLVMSymbolIteratorRef SI) inline
Definition at line 42 of file Object.cpp.
References SI.
wrap() [1/4]
LLVMObjectFileRef wrap (const OwningBinary< ObjectFile > * OF) inline
Definition at line 27 of file Object.cpp.
Referenced by LLVMBinaryCopyMemoryBuffer(), LLVMCreateBinary(), LLVMCreateObjectFile(), LLVMGetRelocations(), LLVMGetRelocationSymbol(), LLVMGetSections(), LLVMGetSymbols(), LLVMMachOUniversalBinaryCopyObjectForArch(), LLVMObjectFileCopySectionIterator(), and LLVMObjectFileCopySymbolIterator().
wrap() [2/4]
LLVMRelocationIteratorRef wrap (const relocation_iterator * SI) inline
Definition at line 57 of file Object.cpp.
References SI.
wrap() [3/4]
LLVMSectionIteratorRef wrap (const section_iterator * SI) inline
Definition at line 37 of file Object.cpp.
References SI.
wrap() [4/4]
LLVMSymbolIteratorRef wrap (const symbol_iterator * SI) inline
Definition at line 47 of file Object.cpp.
References SI.