LLVM: lib/CodeGen/ParallelCG.cpp File Reference
ParallelCG.cpp File Reference
#include "llvm/CodeGen/ParallelCG.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/SplitModule.h"
Functions
static void codegen (Module *M, llvm::raw_pwrite_stream &OS, function_ref< std::unique_ptr< TargetMachine >()> TMFactory, TargetMachine::CodeGenFileType FileType)
Function Documentation
codegen()
static void codegen (Module * M, llvm::raw_pwrite_stream & OS, function_ref< std::unique_ptr< TargetMachine >()> TMFactory, TargetMachine::CodeGenFileType FileType) static
Definition at line 27 of file ParallelCG.cpp.
References llvm::report_fatal_error(), and llvm::legacy::PassManager::run().
Referenced by llvm::lto::backend(), LLVMTargetMachineEmit(), LLVMTargetMachineEmitToFile(), LLVMTargetMachineEmitToMemoryBuffer(), llvm::splitCodeGen(), and llvm::lto::thinBackend().