LLVM: lib/AsmParser/Parser.cpp File Reference
Parser.cpp File Reference
#include "llvm/AsmParser/Parser.h"
#include "LLParser.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include <cstring>
#include <system_error>
Functions
static bool parseSummaryIndexAssemblyInto (MemoryBufferRef F, ModuleSummaryIndex &Index, SMDiagnostic &Err)
Function Documentation
parseSummaryIndexAssemblyInto()
static bool parseSummaryIndexAssemblyInto (MemoryBufferRef F, ModuleSummaryIndex & Index, SMDiagnostic & Err) static
Definition at line 110 of file Parser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), F, llvm::MemoryBuffer::getMemBuffer(), and llvm::LLParser::Run().
Referenced by llvm::parseSummaryIndexAssembly().