LLVM: lib/Transforms/Instrumentation/PGOInstrumentation.cpp File Reference
PGOInstrumentation.cpp File Reference
#include "CFGMST.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/IndirectCallVisitor.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/JamCRC.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Instrumentation/PGOInstrumentation.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <numeric>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "llvm/ProfileData/InstrProfData.inc"
Classes
struct llvm::GraphTraits< PGOUseFunc * >
struct llvm::DOTGraphTraits< PGOUseFunc * >
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "pgo-instrumentation"
#define VALUE_PROF_KIND(Enumerator, Value, Descr) Descr,
Typedefs
using ProfileCount = Function::ProfileCount
Functions
STATISTIC (NumOfPGOInstrument, "Number of edges instrumented.")
STATISTIC (NumOfPGOSelectInsts, "Number of select instruction instrumented.")
STATISTIC (NumOfPGOMemIntrinsics, "Number of mem intrinsics instrumented.")
STATISTIC (NumOfPGOEdge, "Number of edges.")
STATISTIC (NumOfPGOBB, "Number of basic-blocks.")
STATISTIC (NumOfPGOSplit, "Number of critical edge splits.")
STATISTIC (NumOfPGOFunc, "Number of functions having valid profile counts.")
STATISTIC (NumOfPGOMismatch, "Number of functions having mismatch profile.")
STATISTIC (NumOfPGOMissing, "Number of functions without profile.")
STATISTIC (NumOfPGOICall, "Number of indirect call value instrumentations.")
STATISTIC (NumOfCSPGOInstrument, "Number of edges instrumented in CSPGO.")
STATISTIC (NumOfCSPGOSelectInsts, "Number of select instruction instrumented in CSPGO.")
STATISTIC (NumOfCSPGOMemIntrinsics, "Number of mem intrinsics instrumented in CSPGO.")
STATISTIC (NumOfCSPGOEdge, "Number of edges in CSPGO.")
STATISTIC (NumOfCSPGOBB, "Number of basic-blocks in CSPGO.")
STATISTIC (NumOfCSPGOSplit, "Number of critical edge splits in CSPGO.")
STATISTIC (NumOfCSPGOFunc, "Number of functions having valid profile counts in CSPGO.")
STATISTIC (NumOfCSPGOMismatch, "Number of functions having mismatch profile in CSPGO.")
STATISTIC (NumOfCSPGOMissing, "Number of functions without profile in CSPGO.")
static std::string getBranchCondString (Instruction *TI)
INITIALIZE_PASS_BEGIN (PGOInstrumentationGenLegacyPass, "pgo-instr-gen", "PGO instrumentation.", false, false) INITIALIZE_PASS_END(PGOInstrumentationGenLegacyPass
INITIALIZE_PASS_BEGIN (PGOInstrumentationUseLegacyPass, "pgo-instr-use", "Read PGO instrumentation profile.", false, false) INITIALIZE_PASS_END(PGOInstrumentationUseLegacyPass
INITIALIZE_PASS (PGOInstrumentationGenCreateVarLegacyPass, "pgo-instr-gen-create-var", "Create PGO instrumentation version variable for CSPGO.", false, false) ModulePass *llvm
static bool canRenameComdat (Function &F, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers)
static void instrumentOneFunc (Function &F, Module *M, BranchProbabilityInfo *BPI, BlockFrequencyInfo *BFI, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers, bool IsCS)
static uint64_t sumEdgeCount (const ArrayRef< PGOUseEdge * > Edges)
static bool isIndirectBrTarget (BasicBlock *BB)
static void collectComdatMembers (Module &M, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers)
static bool InstrumentAllFunctions (Module &M, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS)
static bool annotateAllFunctions (Module &M, StringRef ProfileFileName, StringRef ProfileRemappingFileName, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS)
static std::string getSimpleNodeName (const BasicBlock *Node)
void llvm::setIrrLoopHeaderMetadata (Module *M, Instruction *TI, uint64_t Count)
Variables
static cl::opt< std::string > PGOTestProfileFile ("pgo-test-profile-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile data file. This is" "mainly for test purpose."))
static cl::opt< std::string > PGOTestProfileRemappingFile ("pgo-test-profile-remapping-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile remapping file. This is mainly for " "test purpose."))
static cl::opt< bool > DisableValueProfiling ("disable-vp", cl::init(false), cl::Hidden, cl::desc("Disable Value Profiling"))
static cl::opt< unsigned > MaxNumAnnotations ("icp-max-annotations", cl::init(3), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of annotations for a single indirect " "call callsite"))
static cl::opt< unsigned > MaxNumMemOPAnnotations ("memop-max-annotations", cl::init(4), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of preicise value annotations for a single memop" "intrinsic"))
static cl::opt< bool > DoComdatRenaming ("do-comdat-renaming", cl::init(false), cl::Hidden, cl::desc("Append function hash to the name of COMDAT function to avoid " "function hash mismatch due to the preinliner"))
static cl::opt< bool > PGOWarnMissing ("pgo-warn-missing-function", cl::init(false), cl::Hidden, cl::desc("Use this option to turn on/off " "warnings about missing profile data for " "functions."))
static cl::opt< bool > NoPGOWarnMismatch ("no-pgo-warn-mismatch", cl::init(false), cl::Hidden, cl::desc("Use this option to turn off/on " "warnings about profile cfg mismatch."))
static cl::opt< bool > NoPGOWarnMismatchComdat ("no-pgo-warn-mismatch-comdat", cl::init(true), cl::Hidden, cl::desc("The option is used to turn on/off " "warnings about hash mismatch for comdat " "functions."))
static cl::opt< bool > PGOInstrSelect ("pgo-instr-select", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off SELECT " "instruction instrumentation. "))
static cl::opt< PGOViewCountsType > PGOViewRawCounts ("pgo-view-raw-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text " "with raw profile counts from " "profile data. See also option " "-pgo-view-counts. To limit graph " "display to only one function, use " "filtering option -view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text.")))
static cl::opt< bool > PGOInstrMemOP ("pgo-instr-memop", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off " "memory intrinsic size profiling."))
static cl::opt< bool > EmitBranchProbability ("pgo-emit-branch-prob", cl::init(false), cl::Hidden, cl::desc("When this option is on, the annotated " "branch probability will be emitted as " "optimization remarks: -{Rpass|" "pass-remarks}=pgo-instrumentation"))
cl::opt< PGOViewCountsType > PGOViewCounts
cl::opt< std::string > ViewBlockFreqFuncName
pgo instr gen
pgo instr PGO instrumentation
pgo instr PGO false
pgo instr use
pgo instr Read PGO instrumentation profile
static const char * ValueProfKindDescr []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pgo-instrumentation"
Definition at line 124 of file PGOInstrumentation.cpp.
VALUE_PROF_KIND
#define VALUE_PROF_KIND (Enumerator, Value, Descr) Descr,
Typedef Documentation
ProfileCount
using ProfileCount = Function::ProfileCount
Definition at line 122 of file PGOInstrumentation.cpp.
Function Documentation
annotateAllFunctions()
static bool annotateAllFunctions (Module & M, StringRef ProfileFileName, StringRef ProfileRemappingFileName, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS) static
Definition at line 1595 of file PGOInstrumentation.cpp.
References llvm::CallingConv::Cold, collectComdatMembers(), llvm::dbgs(), F, llvm::handleAllErrors(), LLVM_DEBUG, llvm::ErrorInfoBase::message(), llvm::Function::PCT_Real, llvm::PGOVCT_Graph, llvm::PGOVCT_None, llvm::PGOVCT_Text, PGOViewCounts, PGOViewRawCounts, llvm::ProfileSummary::PSK_CSInstr, llvm::ProfileSummary::PSK_Instr, llvm::SplitIndirectBrCriticalEdges(), ViewBlockFreqFuncName, ViewGraph(), and llvm::WriteGraph().
Referenced by llvm::PGOInstrumentationUse::run().
canRenameComdat()
static bool canRenameComdat (Function & F, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers) static
Definition at line 685 of file PGOInstrumentation.cpp.
References DoComdatRenaming, and F.
collectComdatMembers()
static void collectComdatMembers (Module & M, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers) static
Definition at line 1522 of file PGOInstrumentation.cpp.
References DoComdatRenaming, and F.
Referenced by annotateAllFunctions(), and InstrumentAllFunctions().
getBranchCondString()
static std::string getBranchCondString (Instruction * TI) static
Definition at line 258 of file PGOInstrumentation.cpp.
References llvm::raw_ostream::flush(), llvm::BranchInst::getCondition(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getPredicateName(), llvm::Value::getType(), llvm::BranchInst::isConditional(), llvm::ConstantInt::isMinusOne(), llvm::ConstantInt::isOne(), llvm::ConstantInt::isZero(), and llvm::Type::print().
Referenced by llvm::setProfMetadata().
getSimpleNodeName()
static std::string getSimpleNodeName (const BasicBlock * Node) static
Definition at line 1755 of file PGOInstrumentation.cpp.
References llvm::raw_string_ostream::str().
Referenced by llvm::DOTGraphTraits< PGOUseFunc * >::getNodeLabel().
INITIALIZE_PASS()
INITIALIZE_PASS (PGOInstrumentationGenCreateVarLegacyPass , "pgo-instr-gen-create-var" , "Create PGO instrumentation version variable for CSPGO." , false , false)
Definition at line 499 of file PGOInstrumentation.cpp.
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (PGOInstrumentationGenLegacyPass , "pgo-instr-gen" , "PGO instrumentation." , false , false)
INITIALIZE_PASS_BEGIN() [2/2]
INITIALIZE_PASS_BEGIN (PGOInstrumentationUseLegacyPass , "pgo-instr-use" , "Read PGO instrumentation profile." , false , false)
InstrumentAllFunctions()
static bool InstrumentAllFunctions (Module & M, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS) static
Definition at line 1538 of file PGOInstrumentation.cpp.
References collectComdatMembers(), F, and instrumentOneFunc().
Referenced by llvm::PGOInstrumentationGen::run().
instrumentOneFunc()
static void instrumentOneFunc (Function & F, Module * M, BranchProbabilityInfo * BPI, BlockFrequencyInfo * BFI, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers, bool IsCS) static
Definition at line 841 of file PGOInstrumentation.cpp.
References assert(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreatePtrToInt(), llvm::dbgs(), DisableValueProfiling, llvm::BasicBlock::end(), F, llvm::ConstantExpr::getBitCast(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getFirstInsertionPt(), llvm::IRBuilderBase::GetInsertPoint(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilderBase::getInt8PtrTy(), I, LLVM_DEBUG, and llvm::SplitIndirectBrCriticalEdges().
Referenced by InstrumentAllFunctions().
isIndirectBrTarget()
static bool isIndirectBrTarget (BasicBlock * BB) static
Definition at line 1359 of file PGOInstrumentation.cpp.
References llvm::pred_begin(), and llvm::pred_end().
STATISTIC() [1/19]
STATISTIC (NumOfCSPGOBB , "Number of basic-blocks in CSPGO.")
STATISTIC() [2/19]
STATISTIC (NumOfCSPGOEdge , "Number of edges in CSPGO.")
STATISTIC() [3/19]
STATISTIC (NumOfCSPGOFunc , "Number of functions having valid profile counts in CSPGO.")
STATISTIC() [4/19]
STATISTIC (NumOfCSPGOInstrument , "Number of edges instrumented in CSPGO.")
STATISTIC() [5/19]
STATISTIC (NumOfCSPGOMemIntrinsics , "Number of mem intrinsics instrumented in CSPGO.")
STATISTIC() [6/19]
STATISTIC (NumOfCSPGOMismatch , "Number of functions having mismatch profile in CSPGO.")
STATISTIC() [7/19]
STATISTIC (NumOfCSPGOMissing , "Number of functions without profile in CSPGO.")
STATISTIC() [8/19]
STATISTIC (NumOfCSPGOSelectInsts , "Number of select instruction instrumented in CSPGO.")
STATISTIC() [9/19]
STATISTIC (NumOfCSPGOSplit , "Number of critical edge splits in CSPGO.")
STATISTIC() [10/19]
STATISTIC (NumOfPGOBB , "Number of basic-blocks.")
STATISTIC() [11/19]
STATISTIC (NumOfPGOEdge , "Number of edges.")
STATISTIC() [12/19]
STATISTIC (NumOfPGOFunc , "Number of functions having valid profile counts.")
STATISTIC() [13/19]
STATISTIC (NumOfPGOICall , "Number of indirect call value instrumentations.")
STATISTIC() [14/19]
STATISTIC (NumOfPGOInstrument , "Number of edges instrumented.")
STATISTIC() [15/19]
STATISTIC (NumOfPGOMemIntrinsics , "Number of mem intrinsics instrumented.")
STATISTIC() [16/19]
STATISTIC (NumOfPGOMismatch , "Number of functions having mismatch profile.")
STATISTIC() [17/19]
STATISTIC (NumOfPGOMissing , "Number of functions without profile.")
STATISTIC() [18/19]
STATISTIC (NumOfPGOSelectInsts , "Number of select instruction instrumented.")
STATISTIC() [19/19]
STATISTIC (NumOfPGOSplit , "Number of critical edge splits.")
sumEdgeCount()
static uint64_t sumEdgeCount (const ArrayRef< PGOUseEdge * > Edges) static
Definition at line 971 of file PGOInstrumentation.cpp.
Variable Documentation
DisableValueProfiling
cl::opt< bool > DisableValueProfiling("disable-vp", cl::init(false), cl::Hidden, cl::desc("Disable Value Profiling")) ("disable-vp" , cl::init(false) , cl::Hidden , cl::desc("Disable Value Profiling")) static
Referenced by instrumentOneFunc().
DoComdatRenaming
cl::opt< bool > DoComdatRenaming("do-comdat-renaming", cl::init(false), cl::Hidden, cl::desc("Append function hash to the name of COMDAT function to avoid " "function hash mismatch due to the preinliner")) ("do-comdat-renaming" , cl::init(false) , cl::Hidden , cl::desc("Append function hash to the name of COMDAT function to avoid " "function hash mismatch due to the preinliner")) static
Referenced by canRenameComdat(), and collectComdatMembers().
EmitBranchProbability
cl::opt< bool > EmitBranchProbability("pgo-emit-branch-prob", cl::init(false), cl::Hidden, cl::desc("When this option is on, the annotated " "branch probability will be emitted as " "optimization remarks: -{Rpass|" "pass-remarks}=pgo-instrumentation")) ("pgo-emit-branch-prob" , cl::init(false) , cl::Hidden , cl::desc("When this option is on, the annotated " "branch probability will be emitted as " "optimization remarks: -{Rpass|" "pass-remarks}=pgo-instrumentation")) static
Referenced by llvm::setProfMetadata().
false
pgo instr Read PGO instrumentation false
Definition at line 476 of file PGOInstrumentation.cpp.
gen
pgo instr gen
Definition at line 475 of file PGOInstrumentation.cpp.
instrumentation
pgo instr PGO instrumentation
Definition at line 476 of file PGOInstrumentation.cpp.
MaxNumAnnotations
cl::opt< unsigned > MaxNumAnnotations("icp-max-annotations", cl::init(3), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of annotations for a single indirect " "call callsite")) ("icp-max-annotations" , cl::init(3) , cl::Hidden , cl::ZeroOrMore , cl::desc("Max number of annotations for a single indirect " "call callsite")) static
MaxNumMemOPAnnotations
cl::opt< unsigned > MaxNumMemOPAnnotations("memop-max-annotations", cl::init(4), cl::Hidden, cl::ZeroOrMore, cl::desc("Max number of preicise value annotations for a single memop" "intrinsic")) ("memop-max-annotations" , cl::init(4) , cl::Hidden , cl::ZeroOrMore , cl::desc("Max number of preicise value annotations for a single memop" "intrinsic")) static
NoPGOWarnMismatch
cl::opt< bool > NoPGOWarnMismatch("no-pgo-warn-mismatch", cl::init(false), cl::Hidden, cl::desc("Use this option to turn off/on " "warnings about profile cfg mismatch.")) ("no-pgo-warn-mismatch" , cl::init(false) , cl::Hidden , cl::desc("Use this option to turn off/on " "warnings about profile cfg mismatch.")) static
NoPGOWarnMismatchComdat
cl::opt< bool > NoPGOWarnMismatchComdat("no-pgo-warn-mismatch-comdat", cl::init(true), cl::Hidden, cl::desc("The option is used to turn on/off " "warnings about hash mismatch for comdat " "functions.")) ("no-pgo-warn-mismatch-comdat" , cl::init(true) , cl::Hidden , cl::desc("The option is used to turn on/off " "warnings about hash mismatch for comdat " "functions.")) static
PGOInstrMemOP
cl::opt< bool > PGOInstrMemOP("pgo-instr-memop", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off " "memory intrinsic size profiling.")) ("pgo-instr-memop" , cl::init(true) , cl::Hidden , cl::desc("Use this option to turn on/off " "memory intrinsic size profiling.")) static
PGOInstrSelect
cl::opt< bool > PGOInstrSelect("pgo-instr-select", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off SELECT " "instruction instrumentation. ")) ("pgo-instr-select" , cl::init(true) , cl::Hidden , cl::desc("Use this option to turn on/off SELECT " "instruction instrumentation. ")) static
Referenced by llvm::DOTGraphTraits< PGOUseFunc * >::getNodeLabel().
PGOTestProfileFile
cl::opt< std::string > PGOTestProfileFile("pgo-test-profile-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile data file. This is" "mainly for test purpose.")) ("pgo-test-profile-file" , cl::init("") , cl::Hidden , cl::value_desc("filename") , cl::desc("Specify the path of profile data file. This is" "mainly for test purpose.")) static
Referenced by llvm::PGOInstrumentationUse::PGOInstrumentationUse().
PGOTestProfileRemappingFile
cl::opt< std::string > PGOTestProfileRemappingFile("pgo-test-profile-remapping-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile remapping file. This is mainly for " "test purpose.")) ("pgo-test-profile-remapping-file" , cl::init("") , cl::Hidden , cl::value_desc("filename") , cl::desc("Specify the path of profile remapping file. This is mainly for " "test purpose.")) static
Referenced by llvm::PGOInstrumentationUse::PGOInstrumentationUse().
PGOViewCounts
cl::opt<PGOViewCountsType> PGOViewCounts extern
PGOViewRawCounts
cl::opt< PGOViewCountsType > PGOViewRawCounts("pgo-view-raw-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text " "with raw profile counts from " "profile data. See also option " "-pgo-view-counts. To limit graph " "display to only one function, use " "filtering option -view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text."))) ("pgo-view-raw-counts" , cl::Hidden , cl::desc("A boolean option to show CFG dag or text " "with raw profile counts from " "profile data. See also option " "-pgo-view-counts. To limit graph " "display to only one function, use " "filtering option -view-bfi-func-name.") , cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text."))) static
Referenced by annotateAllFunctions().
PGOWarnMissing
cl::opt< bool > PGOWarnMissing("pgo-warn-missing-function", cl::init(false), cl::Hidden, cl::desc("Use this option to turn on/off " "warnings about missing profile data for " "functions.")) ("pgo-warn-missing-function" , cl::init(false) , cl::Hidden , cl::desc("Use this option to turn on/off " "warnings about missing profile data for " "functions.")) static
profile
pgo instr Read PGO instrumentation profile
Definition at line 490 of file PGOInstrumentation.cpp.
use
pgo instr use
Definition at line 489 of file PGOInstrumentation.cpp.
Referenced by llvm::GEPOperator::countNonConstantIndices().
ValueProfKindDescr
const char* ValueProfKindDescr[] static
Initial value:
= {
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
}
Definition at line 1485 of file PGOInstrumentation.cpp.
ViewBlockFreqFuncName
cl::opt<std::string> ViewBlockFreqFuncName extern