LLVM: lib/Target/PowerPC/PPCMCInstLower.cpp File Reference
PPCMCInstLower.cpp File Reference
#include "MCTargetDesc/PPCMCExpr.h"
#include "PPC.h"
#include "PPCSubtarget.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static MachineModuleInfoMachO & getMachOMMI (AsmPrinter &AP)
static MCSymbol * GetSymbolFromOperand (const MachineOperand &MO, AsmPrinter &AP)
static MCOperand GetSymbolRef (const MachineOperand &MO, const MCSymbol *Symbol, AsmPrinter &Printer, bool isDarwin)
Function Documentation
getMachOMMI()
static MachineModuleInfoMachO & getMachOMMI (AsmPrinter & AP) static
Definition at line 32 of file PPCMCInstLower.cpp.
References llvm::MachineModuleInfo::getObjFileInfo(), and llvm::AsmPrinter::MMI.
Referenced by GetSymbolFromOperand().
GetSymbolFromOperand()
static MCSymbol * GetSymbolFromOperand (const MachineOperand & MO, AsmPrinter & AP) static
Definition at line 36 of file PPCMCInstLower.cpp.
References assert(), llvm::StringRef::empty(), llvm::AsmPrinter::getDataLayout(), llvm::MachineOperand::getGlobal(), llvm::MachineModuleInfoMachO::getGVStubEntry(), getMachOMMI(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::getOrCreateSymbol(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::AsmPrinter::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::GlobalValue::hasInternalLinkage(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isSymbol(), llvm::PPCII::MO_NLP_FLAG, Name, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::TM.
Referenced by llvm::LowerPPCMachineOperandToMCOperand().
GetSymbolRef()
static MCOperand GetSymbolRef (const MachineOperand & MO, const MCSymbol * Symbol, AsmPrinter & Printer, bool isDarwin) static
Definition at line 81 of file PPCMCInstLower.cpp.
References llvm::PICLevel::BigPIC, llvm::MCSymbolRefExpr::create(), llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::PPCMCExpr::createHa(), llvm::PPCMCExpr::createLo(), llvm::MCBinaryExpr::createSub(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getParent(), llvm::GlobalValue::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getPICBaseSymbol(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getTargetFlags(), isDarwin(), llvm::MachineOperand::isJTI(), llvm::PPCSubtarget::isSecurePlt(), llvm::PPCII::MO_ACCESS_MASK, llvm::PPCII::MO_DTPREL_LO, llvm::PPCII::MO_HA, llvm::PPCII::MO_LO, llvm::PPCII::MO_PIC_FLAG, llvm::PPCII::MO_PLT, llvm::PPCII::MO_TLS, llvm::PPCII::MO_TLSLD_LO, llvm::PPCII::MO_TOC_LO, llvm::PPCII::MO_TPREL_HA, llvm::PPCII::MO_TPREL_LO, Printer, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_LO, llvm::MCSymbolRefExpr::VK_PPC_TLS, llvm::MCSymbolRefExpr::VK_PPC_TOC_LO, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HA, and llvm::MCSymbolRefExpr::VK_PPC_TPREL_LO.
Referenced by llvm::LowerPPCMachineOperandToMCOperand().