LLVM: lib/Analysis/ProfileSummaryInfo.cpp File Reference
ProfileSummaryInfo.cpp File Reference
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ProfileSummary.h"
Functions
static const ProfileSummaryEntry & getEntryForPercentile (SummaryEntryVector &DS, uint64_t Percentile)
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass, "profile-summary-info", "Profile summary info", false, true) ProfileSummaryInfoWrapperPass
Variables
static cl::opt< int > ProfileSummaryCutoffHot ("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts."))
static cl::opt< int > ProfileSummaryCutoffCold ("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts."))
static cl::opt< unsigned > ProfileSummaryHugeWorkingSetSizeThreshold ("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
static cl::opt< int > ProfileSummaryHotCount ("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot"))
static cl::opt< int > ProfileSummaryColdCount ("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold"))
Function Documentation
getEntryForPercentile()
static const ProfileSummaryEntry & getEntryForPercentile (SummaryEntryVector & DS, uint64_t Percentile) static
Definition at line 61 of file ProfileSummaryInfo.cpp.
References llvm::partition_point(), and llvm::report_fatal_error().
INITIALIZE_PASS()
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass , "profile-summary-info" , "Profile summary info" , false , true)
Definition at line 285 of file ProfileSummaryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeProfileSummaryInfoWrapperPassPass().
Variable Documentation
ProfileSummaryColdCount
cl::opt< int > ProfileSummaryColdCount("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold")) ("profile-summary-cold-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold")) static
ProfileSummaryCutoffCold
cl::opt< int > ProfileSummaryCutoffCold("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts.")) ("profile-summary-cutoff-cold" , cl::Hidden , cl::init(999999) , cl::ZeroOrMore , cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts.")) static
ProfileSummaryCutoffHot
cl::opt< int > ProfileSummaryCutoffHot("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts.")) ("profile-summary-cutoff-hot" , cl::Hidden , cl::init(990000) , cl::ZeroOrMore , cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts.")) static
ProfileSummaryHotCount
cl::opt< int > ProfileSummaryHotCount("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot")) ("profile-summary-hot-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot")) static
ProfileSummaryHugeWorkingSetSizeThreshold
cl::opt< unsigned > ProfileSummaryHugeWorkingSetSizeThreshold("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) ("profile-summary-huge-working-set-size-threshold" , cl::Hidden , cl::init(15000) , cl::ZeroOrMore , cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) static