LLVM: lib/IR/ProfileSummary.cpp File Reference
ProfileSummary.cpp File Reference
#include "llvm/IR/ProfileSummary.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
Functions
static Metadata * getKeyValMD (LLVMContext &Context, const char *Key, uint64_t Val)
static Metadata * getKeyValMD (LLVMContext &Context, const char *Key, const char *Val)
static bool getVal (MDTuple *MD, const char *Key, uint64_t &Val)
static bool isKeyValuePair (MDTuple *MD, const char *Key, const char *Val)
static bool getSummaryFromMD (MDTuple *MD, SummaryEntryVector &Summary)
Function Documentation
getKeyValMD() [1/2]
static Metadata * getKeyValMD (LLVMContext & Context, const char * Key, const char * Val) static
Definition at line 36 of file ProfileSummary.cpp.
References llvm::MDTuple::get(), and llvm::MDString::get().
getKeyValMD() [2/2]
static Metadata * getKeyValMD (LLVMContext & Context, const char * Key, uint64_t Val) static
Definition at line 26 of file ProfileSummary.cpp.
References llvm::ConstantAsMetadata::get(), llvm::MDTuple::get(), llvm::MDString::get(), llvm::ConstantInt::get(), and llvm::IRBuilderBase::getInt64Ty().
Referenced by llvm::ProfileSummary::getMD().
getSummaryFromMD()
static bool getSummaryFromMD (MDTuple * MD, SummaryEntryVector & Summary) static
Definition at line 113 of file ProfileSummary.cpp.
References llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::ConstantAsMetadata::getValue(), and llvm::MDNode::operands().
Referenced by llvm::ProfileSummary::getFromMD().
getVal()
static bool getVal (MDTuple * MD, const char * Key, uint64_t & Val) static
Definition at line 84 of file ProfileSummary.cpp.
References llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), and llvm::ConstantAsMetadata::getValue().
Referenced by llvm::ProfileSummary::getFromMD().
isKeyValuePair()
static bool isKeyValuePair (MDTuple * MD, const char * Key, const char * Val) static
Definition at line 100 of file ProfileSummary.cpp.
References llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::MDString::getString().
Referenced by llvm::ProfileSummary::getFromMD().