LLVM: lib/Support/regerror.c File Reference
regerror.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
#include "regex_impl.h"
#include "regutils.h"
Classes
struct rerr
Functions
static const char * regatoi (const llvm_regex_t *, char *, int)
size_t llvm_regerror (int errcode, const llvm_regex_t *preg, char *errbuf, size_t errbuf_size)
Variables
static struct rerr rerrs []
Function Documentation
llvm_regerror()
size_t llvm_regerror (int errcode, const llvm_regex_t * preg, char * errbuf, size_t errbuf_size)
Definition at line 84 of file regerror.c.
References assert(), rerr::code, rerr::explain, llvm_strlcpy(), rerr::name, REG_ATOI, REG_ITOA, regatoi(), and rerrs.
Referenced by llvm::Regex::isValid().
regatoi()
static const char * regatoi (const llvm_regex_t * preg, char * localbuf, int localbufsize) static
Definition at line 123 of file regerror.c.
References rerr::code, rerr::name, llvm_regex::re_endp, and rerrs.
Referenced by llvm_regerror().
Variable Documentation
rerrs
struct rerr rerrs[] static
Initial value:
= {
  { REG_NOMATCH,  "REG_NOMATCH",  "llvm_regexec() failed to match" },
  { REG_BADPAT, "REG_BADPAT", "invalid regular expression" },
  { REG_ECOLLATE, "REG_ECOLLATE", "invalid collating element" },
  { REG_ECTYPE, "REG_ECTYPE", "invalid character class" },
  { REG_EESCAPE,  "REG_EESCAPE",  "trailing backslash (\\)" },
  { REG_ESUBREG,  "REG_ESUBREG",  "invalid backreference number" },
  { REG_EBRACK, "REG_EBRACK", "brackets ([ ]) not balanced" },
  { REG_EPAREN, "REG_EPAREN", "parentheses not balanced" },
  { REG_EBRACE, "REG_EBRACE", "braces not balanced" },
  { REG_BADBR,  "REG_BADBR",  "invalid repetition count(s)" },
  { REG_ERANGE, "REG_ERANGE", "invalid character range" },
  { REG_ESPACE, "REG_ESPACE", "out of memory" },
  { REG_BADRPT, "REG_BADRPT", "repetition-operator operand invalid" },
  { REG_EMPTY,  "REG_EMPTY",  "empty (sub)expression" },
  { REG_ASSERT, "REG_ASSERT", "\"can't happen\" -- you found a bug" },
  { REG_INVARG, "REG_INVARG", "invalid argument to regex routine" },
  { 0,    "",   "*** unknown regexp error code ***" }
}
Referenced by llvm_regerror(), and regatoi().