LLVM: lib/IR/RemarkStreamer.cpp File Reference
RemarkStreamer.cpp File Reference
#include "llvm/IR/RemarkStreamer.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Remarks/RemarkFormat.h"
Functions
static remarks::Type toRemarkType (enum DiagnosticKind Kind)
DiagnosticKind -> remarks::Type.
static Optional< remarks::RemarkLocation > toRemarkLocation (const DiagnosticLocation &DL)
DiagnosticLocation -> remarks::RemarkLocation.
static std::unique_ptr< remarks::Serializer > formatToSerializer (remarks::Format RemarksFormat, raw_ostream &OS)
Function Documentation
formatToSerializer()
static std::unique_ptr< remarks::Serializer > formatToSerializer (remarks::Format RemarksFormat, raw_ostream & OS) static
Definition at line 110 of file RemarkStreamer.cpp.
References llvm_unreachable, llvm::RemarksFormat, and llvm::remarks::YAML.
Referenced by llvm::setupOptimizationRemarks().
toRemarkLocation()
static Optional< remarks::RemarkLocation > toRemarkLocation (const DiagnosticLocation & DL) static
DiagnosticLocation -> remarks::RemarkLocation.
Definition at line 63 of file RemarkStreamer.cpp.
References llvm::DiagnosticLocation::getColumn(), llvm::DiagnosticLocation::getLine(), llvm::DiagnosticLocation::getRelativePath(), llvm::DiagnosticLocation::isValid(), and llvm::None.
toRemarkType()
static remarks::Type toRemarkType (enum DiagnosticKind Kind) static
DiagnosticKind -> remarks::Type.
Definition at line 39 of file RemarkStreamer.cpp.
References llvm::remarks::Analysis, llvm::remarks::AnalysisAliasing, llvm::remarks::AnalysisFPCommute, llvm::DK_MachineOptimizationRemark, llvm::DK_MachineOptimizationRemarkAnalysis, llvm::DK_MachineOptimizationRemarkMissed, llvm::DK_OptimizationFailure, llvm::DK_OptimizationRemark, llvm::DK_OptimizationRemarkAnalysis, llvm::DK_OptimizationRemarkAnalysisAliasing, llvm::DK_OptimizationRemarkAnalysisFPCommute, llvm::DK_OptimizationRemarkMissed, llvm::remarks::Failure, llvm::remarks::Missed, llvm::remarks::Passed, and llvm::remarks::Unknown.