LLVM: lib/Transforms/Scalar/Scalar.cpp File Reference
Scalar.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm-c/Initialization.h"
#include "llvm-c/Transforms/Scalar.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/Scalarizer.h"
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
Functions
void LLVMAddLoopSimplifyCFGPass (LLVMPassManagerRef PM)
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
void LLVMAddAggressiveDCEPass (LLVMPassManagerRef PM)
void LLVMAddBitTrackingDCEPass (LLVMPassManagerRef PM)
void LLVMAddAlignmentFromAssumptionsPass (LLVMPassManagerRef PM)
void LLVMAddCFGSimplificationPass (LLVMPassManagerRef PM)
void LLVMAddDeadStoreEliminationPass (LLVMPassManagerRef PM)
void LLVMAddScalarizerPass (LLVMPassManagerRef PM)
void LLVMAddGVNPass (LLVMPassManagerRef PM)
void LLVMAddNewGVNPass (LLVMPassManagerRef PM)
void LLVMAddMergedLoadStoreMotionPass (LLVMPassManagerRef PM)
void LLVMAddIndVarSimplifyPass (LLVMPassManagerRef PM)
void LLVMAddJumpThreadingPass (LLVMPassManagerRef PM)
void LLVMAddLoopSinkPass (LLVMPassManagerRef PM)
void LLVMAddLICMPass (LLVMPassManagerRef PM)
void LLVMAddLoopDeletionPass (LLVMPassManagerRef PM)
void LLVMAddLoopIdiomPass (LLVMPassManagerRef PM)
void LLVMAddLoopRotatePass (LLVMPassManagerRef PM)
void LLVMAddLoopRerollPass (LLVMPassManagerRef PM)
void LLVMAddLoopUnrollPass (LLVMPassManagerRef PM)
void LLVMAddLoopUnrollAndJamPass (LLVMPassManagerRef PM)
void LLVMAddLoopUnswitchPass (LLVMPassManagerRef PM)
void LLVMAddLowerAtomicPass (LLVMPassManagerRef PM)
void LLVMAddMemCpyOptPass (LLVMPassManagerRef PM)
void LLVMAddPartiallyInlineLibCallsPass (LLVMPassManagerRef PM)
void LLVMAddReassociatePass (LLVMPassManagerRef PM)
void LLVMAddSCCPPass (LLVMPassManagerRef PM)
void LLVMAddScalarReplAggregatesPass (LLVMPassManagerRef PM)
void LLVMAddScalarReplAggregatesPassSSA (LLVMPassManagerRef PM)
void LLVMAddScalarReplAggregatesPassWithThreshold (LLVMPassManagerRef PM, int Threshold)
void LLVMAddSimplifyLibCallsPass (LLVMPassManagerRef PM)
void LLVMAddTailCallEliminationPass (LLVMPassManagerRef PM)
void LLVMAddConstantPropagationPass (LLVMPassManagerRef PM)
void LLVMAddDemoteMemoryToRegisterPass (LLVMPassManagerRef PM)
void LLVMAddVerifierPass (LLVMPassManagerRef PM)
void LLVMAddCorrelatedValuePropagationPass (LLVMPassManagerRef PM)
void LLVMAddEarlyCSEPass (LLVMPassManagerRef PM)
void LLVMAddEarlyCSEMemSSAPass (LLVMPassManagerRef PM)
void LLVMAddGVNHoistLegacyPass (LLVMPassManagerRef PM)
void LLVMAddTypeBasedAliasAnalysisPass (LLVMPassManagerRef PM)
void LLVMAddScopedNoAliasAAPass (LLVMPassManagerRef PM)
void LLVMAddBasicAliasAnalysisPass (LLVMPassManagerRef PM)
void LLVMAddLowerExpectIntrinsicPass (LLVMPassManagerRef PM)
void LLVMAddUnifyFunctionExitNodesPass (LLVMPassManagerRef PM)
Function Documentation
LLVMAddAggressiveDCEPass()
void LLVMAddAggressiveDCEPass (LLVMPassManagerRef PM)
Definition at line 122 of file Scalar.cpp.
References llvm::createAggressiveDCEPass(), and llvm::unwrap().
LLVMAddAlignmentFromAssumptionsPass()
void LLVMAddAlignmentFromAssumptionsPass (LLVMPassManagerRef PM)
Definition at line 130 of file Scalar.cpp.
References llvm::createAlignmentFromAssumptionsPass(), and llvm::unwrap().
LLVMAddBasicAliasAnalysisPass()
void LLVMAddBasicAliasAnalysisPass (LLVMPassManagerRef PM)
Definition at line 279 of file Scalar.cpp.
References llvm::createBasicAAWrapperPass(), and llvm::unwrap().
LLVMAddBitTrackingDCEPass()
void LLVMAddBitTrackingDCEPass (LLVMPassManagerRef PM)
Definition at line 126 of file Scalar.cpp.
References llvm::createBitTrackingDCEPass(), and llvm::unwrap().
LLVMAddCFGSimplificationPass()
void LLVMAddCFGSimplificationPass (LLVMPassManagerRef PM)
Definition at line 134 of file Scalar.cpp.
References llvm::createCFGSimplificationPass(), and llvm::unwrap().
LLVMAddConstantPropagationPass()
void LLVMAddConstantPropagationPass (LLVMPassManagerRef PM)
Definition at line 243 of file Scalar.cpp.
References llvm::createConstantPropagationPass(), and llvm::unwrap().
LLVMAddCorrelatedValuePropagationPass()
void LLVMAddCorrelatedValuePropagationPass (LLVMPassManagerRef PM)
Definition at line 255 of file Scalar.cpp.
References llvm::createCorrelatedValuePropagationPass(), and llvm::unwrap().
LLVMAddDeadStoreEliminationPass()
void LLVMAddDeadStoreEliminationPass (LLVMPassManagerRef PM)
Definition at line 138 of file Scalar.cpp.
References llvm::createDeadStoreEliminationPass(), and llvm::unwrap().
LLVMAddDemoteMemoryToRegisterPass()
void LLVMAddDemoteMemoryToRegisterPass (LLVMPassManagerRef PM)
Definition at line 247 of file Scalar.cpp.
References llvm::createDemoteRegisterToMemoryPass(), and llvm::unwrap().
LLVMAddEarlyCSEMemSSAPass()
void LLVMAddEarlyCSEMemSSAPass (LLVMPassManagerRef PM)
Definition at line 263 of file Scalar.cpp.
References llvm::createEarlyCSEPass(), and llvm::unwrap().
LLVMAddEarlyCSEPass()
void LLVMAddEarlyCSEPass (LLVMPassManagerRef PM)
Definition at line 259 of file Scalar.cpp.
References llvm::createEarlyCSEPass(), and llvm::unwrap().
LLVMAddGVNHoistLegacyPass()
void LLVMAddGVNHoistLegacyPass (LLVMPassManagerRef PM)
Definition at line 267 of file Scalar.cpp.
References llvm::createGVNHoistPass(), and llvm::unwrap().
LLVMAddGVNPass()
void LLVMAddGVNPass (LLVMPassManagerRef PM)
Definition at line 146 of file Scalar.cpp.
References llvm::createGVNPass(), and llvm::unwrap().
LLVMAddIndVarSimplifyPass()
void LLVMAddIndVarSimplifyPass (LLVMPassManagerRef PM)
Definition at line 158 of file Scalar.cpp.
References llvm::createIndVarSimplifyPass(), and llvm::unwrap().
LLVMAddJumpThreadingPass()
void LLVMAddJumpThreadingPass (LLVMPassManagerRef PM)
Definition at line 162 of file Scalar.cpp.
References llvm::createJumpThreadingPass(), and llvm::unwrap().
LLVMAddLICMPass()
void LLVMAddLICMPass (LLVMPassManagerRef PM)
Definition at line 170 of file Scalar.cpp.
References llvm::createLICMPass(), and llvm::unwrap().
LLVMAddLoopDeletionPass()
void LLVMAddLoopDeletionPass (LLVMPassManagerRef PM)
Definition at line 174 of file Scalar.cpp.
References llvm::createLoopDeletionPass(), and llvm::unwrap().
LLVMAddLoopIdiomPass()
void LLVMAddLoopIdiomPass (LLVMPassManagerRef PM)
Definition at line 178 of file Scalar.cpp.
References llvm::createLoopIdiomPass(), and llvm::unwrap().
LLVMAddLoopRerollPass()
void LLVMAddLoopRerollPass (LLVMPassManagerRef PM)
Definition at line 186 of file Scalar.cpp.
References llvm::createLoopRerollPass(), and llvm::unwrap().
LLVMAddLoopRotatePass()
void LLVMAddLoopRotatePass (LLVMPassManagerRef PM)
Definition at line 182 of file Scalar.cpp.
References llvm::createLoopRotatePass(), and llvm::unwrap().
LLVMAddLoopSimplifyCFGPass()
void LLVMAddLoopSimplifyCFGPass (LLVMPassManagerRef PM)
Definition at line 114 of file Scalar.cpp.
References llvm::createLoopSimplifyCFGPass(), and llvm::unwrap().
LLVMAddLoopSinkPass()
void LLVMAddLoopSinkPass (LLVMPassManagerRef PM)
Definition at line 166 of file Scalar.cpp.
References llvm::createLoopSinkPass(), and llvm::unwrap().
LLVMAddLoopUnrollAndJamPass()
void LLVMAddLoopUnrollAndJamPass (LLVMPassManagerRef PM)
Definition at line 194 of file Scalar.cpp.
References llvm::createLoopUnrollAndJamPass(), and llvm::unwrap().
LLVMAddLoopUnrollPass()
void LLVMAddLoopUnrollPass (LLVMPassManagerRef PM)
Definition at line 190 of file Scalar.cpp.
References llvm::createLoopUnrollPass(), and llvm::unwrap().
LLVMAddLoopUnswitchPass()
void LLVMAddLoopUnswitchPass (LLVMPassManagerRef PM)
Definition at line 198 of file Scalar.cpp.
References llvm::createLoopUnswitchPass(), and llvm::unwrap().
LLVMAddLowerAtomicPass()
void LLVMAddLowerAtomicPass (LLVMPassManagerRef PM)
Definition at line 202 of file Scalar.cpp.
References llvm::createLowerAtomicPass(), and llvm::unwrap().
LLVMAddLowerExpectIntrinsicPass()
void LLVMAddLowerExpectIntrinsicPass (LLVMPassManagerRef PM)
Definition at line 283 of file Scalar.cpp.
References llvm::createLowerExpectIntrinsicPass(), and llvm::unwrap().
LLVMAddMemCpyOptPass()
void LLVMAddMemCpyOptPass (LLVMPassManagerRef PM)
Definition at line 206 of file Scalar.cpp.
References llvm::createMemCpyOptPass(), and llvm::unwrap().
LLVMAddMergedLoadStoreMotionPass()
void LLVMAddMergedLoadStoreMotionPass (LLVMPassManagerRef PM)
Definition at line 154 of file Scalar.cpp.
References llvm::createMergedLoadStoreMotionPass(), and llvm::unwrap().
LLVMAddNewGVNPass()
void LLVMAddNewGVNPass (LLVMPassManagerRef PM)
Definition at line 150 of file Scalar.cpp.
References llvm::createNewGVNPass(), and llvm::unwrap().
LLVMAddPartiallyInlineLibCallsPass()
void LLVMAddPartiallyInlineLibCallsPass (LLVMPassManagerRef PM)
Definition at line 210 of file Scalar.cpp.
References llvm::createPartiallyInlineLibCallsPass(), and llvm::unwrap().
LLVMAddReassociatePass()
void LLVMAddReassociatePass (LLVMPassManagerRef PM)
Definition at line 214 of file Scalar.cpp.
References llvm::createReassociatePass(), and llvm::unwrap().
LLVMAddScalarizerPass()
void LLVMAddScalarizerPass (LLVMPassManagerRef PM)
Definition at line 142 of file Scalar.cpp.
References llvm::createScalarizerPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPass()
void LLVMAddScalarReplAggregatesPass (LLVMPassManagerRef PM)
Definition at line 222 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPassSSA()
void LLVMAddScalarReplAggregatesPassSSA (LLVMPassManagerRef PM)
Definition at line 226 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddScalarReplAggregatesPassWithThreshold()
void LLVMAddScalarReplAggregatesPassWithThreshold (LLVMPassManagerRef PM, int Threshold)
Definition at line 230 of file Scalar.cpp.
References llvm::createSROAPass(), and llvm::unwrap().
LLVMAddSCCPPass()
void LLVMAddSCCPPass (LLVMPassManagerRef PM)
Definition at line 218 of file Scalar.cpp.
References llvm::createSCCPPass(), and llvm::unwrap().
LLVMAddScopedNoAliasAAPass()
void LLVMAddScopedNoAliasAAPass (LLVMPassManagerRef PM)
Definition at line 275 of file Scalar.cpp.
References llvm::createScopedNoAliasAAWrapperPass(), and llvm::unwrap().
LLVMAddSimplifyLibCallsPass()
void LLVMAddSimplifyLibCallsPass (LLVMPassManagerRef PM)
Definition at line 235 of file Scalar.cpp.
LLVMAddTailCallEliminationPass()
void LLVMAddTailCallEliminationPass (LLVMPassManagerRef PM)
Definition at line 239 of file Scalar.cpp.
References llvm::createTailCallEliminationPass(), and llvm::unwrap().
LLVMAddTypeBasedAliasAnalysisPass()
void LLVMAddTypeBasedAliasAnalysisPass (LLVMPassManagerRef PM)
Definition at line 271 of file Scalar.cpp.
References llvm::createTypeBasedAAWrapperPass(), and llvm::unwrap().
LLVMAddUnifyFunctionExitNodesPass()
void LLVMAddUnifyFunctionExitNodesPass (LLVMPassManagerRef PM)
Definition at line 287 of file Scalar.cpp.
References llvm::createUnifyFunctionExitNodesPass(), and llvm::unwrap().
LLVMAddVerifierPass()
void LLVMAddVerifierPass (LLVMPassManagerRef PM)
Definition at line 251 of file Scalar.cpp.
References llvm::createVerifierPass(), and llvm::unwrap().
LLVMInitializeScalarOpts()
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
Definition at line 118 of file Scalar.cpp.
References llvm::unwrap().