LLVM: lib/CodeGen/ScalarizeMaskedMemIntrin.cpp File Reference
ScalarizeMaskedMemIntrin.cpp File Reference
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <cassert>
Macros
#define DEBUG_TYPE "scalarize-masked-mem-intrin"
Functions
INITIALIZE_PASS (ScalarizeMaskedMemIntrin, DEBUG_TYPE, "Scalarize unsupported masked memory intrinsics", false, false) FunctionPass *llvm
static bool isConstantIntVector (Value *Mask)
static void scalarizeMaskedLoad (CallInst *CI, bool &ModifiedDT)
static void scalarizeMaskedStore (CallInst *CI, bool &ModifiedDT)
static void scalarizeMaskedGather (CallInst *CI, bool &ModifiedDT)
static void scalarizeMaskedScatter (CallInst *CI, bool &ModifiedDT)
static void scalarizeMaskedExpandLoad (CallInst *CI, bool &ModifiedDT)
static void scalarizeMaskedCompressStore (CallInst *CI, bool &ModifiedDT)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "scalarize-masked-mem-intrin"
Definition at line 39 of file ScalarizeMaskedMemIntrin.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ScalarizeMaskedMemIntrin , DEBUG_TYPE , "Scalarize unsupported masked memory intrinsics" , false , false)
Definition at line 72 of file ScalarizeMaskedMemIntrin.cpp.
isConstantIntVector()
static bool isConstantIntVector (Value * Mask) static
Definition at line 79 of file ScalarizeMaskedMemIntrin.cpp.
References C.
Referenced by scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), and scalarizeMaskedStore().
scalarizeMaskedCompressStore()
static void scalarizeMaskedCompressStore (CallInst * CI, bool & ModifiedDT) static
Definition at line 618 of file ScalarizeMaskedMemIntrin.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Idx, llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
scalarizeMaskedExpandLoad()
static void scalarizeMaskedExpandLoad (CallInst * CI, bool & ModifiedDT) static
Definition at line 537 of file ScalarizeMaskedMemIntrin.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Idx, llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
scalarizeMaskedGather()
static void scalarizeMaskedGather (CallInst * CI, bool & ModifiedDT) static
Definition at line 358 of file ScalarizeMaskedMemIntrin.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Idx, isConstantIntVector(), llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
scalarizeMaskedLoad()
static void scalarizeMaskedLoad (CallInst * CI, bool & ModifiedDT) static
Definition at line 126 of file ScalarizeMaskedMemIntrin.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::IRBuilder< T, Inserter >::CreateInsertElement(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Idx, isConstantIntVector(), llvm::MinAlign(), llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
scalarizeMaskedScatter()
static void scalarizeMaskedScatter (CallInst * CI, bool & ModifiedDT) static
Definition at line 467 of file ScalarizeMaskedMemIntrin.cpp.
References assert(), llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), Idx, isConstantIntVector(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
scalarizeMaskedStore()
static void scalarizeMaskedStore (CallInst * CI, bool & ModifiedDT) static
Definition at line 249 of file ScalarizeMaskedMemIntrin.cpp.
References llvm::BranchInst::Create(), llvm::IRBuilder< T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< T, Inserter >::CreateBitCast(), llvm::IRBuilder< T, Inserter >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< T, Inserter >::CreateExtractElement(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Idx, isConstantIntVector(), llvm::MinAlign(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().