LLVM: lib/Target/AMDGPU/SIPeepholeSDWA.cpp File Reference
SIPeepholeSDWA.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <unordered_map>
Macros
#define DEBUG_TYPE "si-peephole-sdwa"
Functions
STATISTIC (NumSDWAPatternsFound, "Number of SDWA patterns found.")
STATISTIC (NumSDWAInstructionsPeepholed, "Number of instruction converted to SDWA.")
static raw_ostream & operator<< (raw_ostream &OS, SdwaSel Sel)
static raw_ostream & operator<< (raw_ostream &OS, const DstUnused &Un)
static raw_ostream & operator<< (raw_ostream &OS, const SDWAOperand &Operand)
static void copyRegOperand (MachineOperand &To, const MachineOperand &From)
static bool isSameReg (const MachineOperand &LHS, const MachineOperand &RHS)
static MachineOperand * findSingleRegUse (const MachineOperand *Reg, const MachineRegisterInfo *MRI)
static MachineOperand * findSingleRegDef (const MachineOperand *Reg, const MachineRegisterInfo *MRI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-peephole-sdwa"
Definition at line 56 of file SIPeepholeSDWA.cpp.
Function Documentation
copyRegOperand()
static void copyRegOperand (MachineOperand & To, const MachineOperand & From) static
Definition at line 275 of file SIPeepholeSDWA.cpp.
References assert(), From, llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), and llvm::MachineOperand::setSubReg().
findSingleRegDef()
static MachineOperand * findSingleRegDef (const MachineOperand * Reg, const MachineRegisterInfo * MRI) static
Definition at line 316 of file SIPeepholeSDWA.cpp.
References llvm::MachineInstr::defs(), and MRI.
findSingleRegUse()
static MachineOperand * findSingleRegUse (const MachineOperand * Reg, const MachineRegisterInfo * MRI) static
Definition at line 294 of file SIPeepholeSDWA.cpp.
References llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), isSameReg(), and MRI.
isSameReg()
static bool isSameReg (const MachineOperand & LHS, const MachineOperand & RHS) static
Definition at line 287 of file SIPeepholeSDWA.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), and llvm::MachineOperand::isReg().
Referenced by findSingleRegUse().
operator<<() [1/3]
static raw_ostream & operator<< (raw_ostream & OS, const DstUnused & Un) static
Definition at line 237 of file SIPeepholeSDWA.cpp.
References llvm::AMDGPU::SDWA::UNUSED_PAD, llvm::AMDGPU::SDWA::UNUSED_PRESERVE, and llvm::AMDGPU::SDWA::UNUSED_SEXT.
operator<<() [2/3]
static raw_ostream & operator<< (raw_ostream & OS, const SDWAOperand & Operand) static
Definition at line 246 of file SIPeepholeSDWA.cpp.
operator<<() [3/3]
static raw_ostream & operator<< (raw_ostream & OS, SdwaSel Sel) static
Definition at line 224 of file SIPeepholeSDWA.cpp.
References llvm::AMDGPU::SDWA::BYTE_0, llvm::AMDGPU::SDWA::BYTE_1, llvm::AMDGPU::SDWA::BYTE_2, llvm::AMDGPU::SDWA::BYTE_3, llvm::AMDGPU::SDWA::DWORD, llvm::AMDGPU::SDWA::WORD_0, and llvm::AMDGPU::SDWA::WORD_1.
STATISTIC() [1/2]
STATISTIC (NumSDWAInstructionsPeepholed , "Number of instruction converted to SDWA.")
STATISTIC() [2/2]
STATISTIC (NumSDWAPatternsFound , "Number of SDWA patterns found.")