LLVM: lib/Target/AMDGPU/SIRegisterInfo.cpp File Reference
SIRegisterInfo.cpp File Reference
SI implementation of the TargetRegisterInfo class.
#include "SIRegisterInfo.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPUSubtarget.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "MCTargetDesc/AMDGPUInstPrinter.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
Functions
static bool hasPressureSet (const int *PSets, unsigned PSetID)
static unsigned findPrivateSegmentWaveByteOffsetRegIndex (unsigned RegCount)
static unsigned getNumSubRegsForSpillOp (unsigned Op)
static int getOffsetMUBUFStore (unsigned Opc)
static int getOffsetMUBUFLoad (unsigned Opc)
static MachineInstrBuilder spillVGPRtoAGPR (MachineBasicBlock::iterator MI, int Index, unsigned Lane, unsigned ValueReg, bool IsKill)
static bool buildMUBUFOffsetLoadStore (const SIInstrInfo *TII, MachineFrameInfo &MFI, MachineBasicBlock::iterator MI, int Index, int64_t Offset)
static std::pair< unsigned, unsigned > getSpillEltSize (unsigned SuperRegSize, bool Store)
Variables
static cl::opt< bool > EnableSpillSGPRToSMEM ("amdgpu-spill-sgpr-to-smem", cl::desc("Use scalar stores to spill SGPRs if supported by subtarget"), cl::init(false))
static cl::opt< bool > EnableSpillSGPRToVGPR ("amdgpu-spill-sgpr-to-vgpr", cl::desc("Enable spilling VGPRs to SGPRs"), cl::ReallyHidden, cl::init(true))
Detailed Description
SI implementation of the TargetRegisterInfo class.
Definition in file SIRegisterInfo.cpp.
Function Documentation
buildMUBUFOffsetLoadStore()
static bool buildMUBUFOffsetLoadStore (const SIInstrInfo * TII, MachineFrameInfo & MFI, MachineBasicBlock::iterator MI, int Index, int64_t Offset) static
Definition at line 598 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::MachineInstrBuilder::getInstr(), getOffsetMUBUFLoad(), getOffsetMUBUFStore(), MI, spillVGPRtoAGPR(), and TII.
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex().
findPrivateSegmentWaveByteOffsetRegIndex()
static unsigned findPrivateSegmentWaveByteOffsetRegIndex (unsigned RegCount) static
Definition at line 128 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::reservedPrivateSegmentWaveByteOffsetReg().
getNumSubRegsForSpillOp()
static unsigned getNumSubRegsForSpillOp (unsigned Op) static
Definition at line 456 of file SIRegisterInfo.cpp.
References llvm_unreachable.
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex().
getOffsetMUBUFLoad()
static int getOffsetMUBUFLoad (unsigned Opc) static
Definition at line 534 of file SIRegisterInfo.cpp.
Referenced by buildMUBUFOffsetLoadStore().
getOffsetMUBUFStore()
static int getOffsetMUBUFStore (unsigned Opc) static
Definition at line 513 of file SIRegisterInfo.cpp.
Referenced by buildMUBUFOffsetLoadStore().
getSpillEltSize()
static std::pair< unsigned, unsigned > getSpillEltSize (unsigned SuperRegSize, bool Store) static
Definition at line 766 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), and llvm::SIRegisterInfo::spillSGPR().
hasPressureSet()
static bool hasPressureSet (const int * PSets, unsigned PSetID) static
Definition at line 32 of file SIRegisterInfo.cpp.
spillVGPRtoAGPR()
static MachineInstrBuilder spillVGPRtoAGPR (MachineBasicBlock::iterator MI, int Index, unsigned Lane, unsigned ValueReg, bool IsKill) static
Definition at line 567 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill(), MI, MRI, TII, and TRI.
Referenced by buildMUBUFOffsetLoadStore().
Variable Documentation
EnableSpillSGPRToSMEM
cl::opt< bool > EnableSpillSGPRToSMEM("amdgpu-spill-sgpr-to-smem", cl::desc("Use scalar stores to spill SGPRs if supported by subtarget"), cl::init(false)) ("amdgpu-spill-sgpr-to-smem" , cl::desc("Use scalar stores to spill SGPRs if supported by subtarget") , cl::init(false)) static
Referenced by llvm::SIRegisterInfo::SIRegisterInfo().
EnableSpillSGPRToVGPR
cl::opt< bool > EnableSpillSGPRToVGPR("amdgpu-spill-sgpr-to-vgpr", cl::desc("Enable spilling VGPRs to SGPRs"), cl::ReallyHidden, cl::init(true)) ("amdgpu-spill-sgpr-to-vgpr" , cl::desc("Enable spilling VGPRs to SGPRs") , cl::ReallyHidden , cl::init(true)) static
Referenced by llvm::SIRegisterInfo::SIRegisterInfo().