LLVM: lib/Support/Statistic.cpp File Reference
Statistic.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstring>
Variables
static cl::opt< bool > Stats ("stats", cl::desc("Enable statistics output from program (available with Asserts)"), cl::Hidden)
-stats - Command line option to cause transformations to emit stats about what they did.
static cl::opt< bool > StatsAsJSON ("stats-json", cl::desc("Display statistics as json data"), cl::Hidden)
static bool Enabled
static bool PrintOnExit
static ManagedStatic< StatisticInfo > StatInfo
static ManagedStatic< sys::SmartMutex< true > > StatLock
Variable Documentation
Enabled
bool Enabled static
Definition at line 50 of file Statistic.cpp.
Referenced by llvm::LTOCodeGenerator::setFreestanding(), and llvm::ThinLTOCodeGenerator::setFreestanding().
PrintOnExit
bool PrintOnExit static
Definition at line 51 of file Statistic.cpp.
StatInfo
ManagedStatic<StatisticInfo> StatInfo static
Definition at line 88 of file Statistic.cpp.
StatLock
ManagedStatic<sys::SmartMutex<true> > StatLock static
Definition at line 89 of file Statistic.cpp.
Stats
cl::opt< bool > Stats("stats", cl::desc("Enable statistics output from program (available with Asserts)"), cl::Hidden) ("stats" , cl::desc("Enable statistics output from program (available with Asserts)") , cl::Hidden) static
-stats - Command line option to cause transformations to emit stats about what they did.
Referenced by llvm::pdb::PDBSymbol::dumpChildStats(), dumpIR(), llvm::pdb::PDBSymbol::getChildStats(), operator<<(), and llvm::pdb::operator<<().
StatsAsJSON
cl::opt< bool > StatsAsJSON("stats-json", cl::desc("Display statistics as json data"), cl::Hidden) ("stats-json" , cl::desc("Display statistics as json data") , cl::Hidden) static