LLVM: llvm::CFGViewSuccessors< InverseGraph > Struct Template Reference
llvm::CFGViewSuccessors< InverseGraph > Struct Template Reference
#include "llvm/IR/CFGDiff.h"
Classes
struct DeletedEdgesFilter
Public Types
using DataRef = const GraphDiff< BasicBlock *, InverseGraph > *
using NodeRef = std::pair< DataRef, BasicBlock * >
using ExistingChildIterator = WrappedPairNodeDataIterator< succ_iterator, NodeRef, DataRef >
using FilterExistingChildrenIterator = filter_iterator< ExistingChildIterator, DeletedEdgesFilter >
using vec_iterator = SmallVectorImpl< BasicBlock * >::const_iterator
using AddNewChildrenIterator = WrappedPairNodeDataIterator< vec_iterator, NodeRef, DataRef >
using ChildIteratorType = concat_iterator< NodeRef, FilterExistingChildrenIterator, AddNewChildrenIterator >
Static Public Member Functions
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<bool InverseGraph = false>
struct llvm::CFGViewSuccessors< InverseGraph >
Definition at line 158 of file CFGDiff.h.
Member Typedef Documentation
AddNewChildrenIterator
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::AddNewChildrenIterator = WrappedPairNodeDataIterator<vec_iterator, NodeRef, DataRef>
Definition at line 175 of file CFGDiff.h.
ChildIteratorType
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::ChildIteratorType = concat_iterator<NodeRef, FilterExistingChildrenIterator, AddNewChildrenIterator>
Definition at line 177 of file CFGDiff.h.
DataRef
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::DataRef = const GraphDiff<BasicBlock *, InverseGraph> *
Definition at line 159 of file CFGDiff.h.
ExistingChildIterator
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::ExistingChildIterator = WrappedPairNodeDataIterator<succ_iterator, NodeRef, DataRef>
Definition at line 162 of file CFGDiff.h.
FilterExistingChildrenIterator
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::FilterExistingChildrenIterator = filter_iterator<ExistingChildIterator, DeletedEdgesFilter>
Definition at line 171 of file CFGDiff.h.
NodeRef
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::NodeRef = std::pair<DataRef, BasicBlock *>
Definition at line 160 of file CFGDiff.h.
vec_iterator
template<bool InverseGraph = false> using llvm::CFGViewSuccessors< InverseGraph >::vec_iterator = SmallVectorImpl<BasicBlock *>::const_iterator
Definition at line 174 of file CFGDiff.h.
Member Function Documentation
child_begin()
template<bool InverseGraph = false> static ChildIteratorType llvm::CFGViewSuccessors< InverseGraph >::child_begin (NodeRef N) inline static
Definition at line 181 of file CFGDiff.h.
References N, llvm::succ_begin(), and llvm::succ_end().
child_end()
template<bool InverseGraph = false> static ChildIteratorType llvm::CFGViewSuccessors< InverseGraph >::child_end (NodeRef N) inline static
Definition at line 196 of file CFGDiff.h.
References N, and llvm::succ_end().
The documentation for this struct was generated from the following file:
include/llvm/IR/CFGDiff.h