LLVM: llvm::MemorySSAAnalysis::Result Struct Reference
llvm::MemorySSAAnalysis::Result Struct Reference
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
Result (std::unique_ptr< MemorySSA > &&MSSA)
MemorySSA & getMSSA ()
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Public Attributes
std::unique_ptr< MemorySSA > MSSA
Detailed Description
Definition at line 933 of file MemorySSA.h.
Constructor & Destructor Documentation
Result()
llvm::MemorySSAAnalysis::Result::Result (std::unique_ptr< MemorySSA > && MSSA) inline
Definition at line 934 of file MemorySSA.h.
Member Function Documentation
getMSSA()
MemorySSA & llvm::MemorySSAAnalysis::Result::getMSSA () inline
Definition at line 936 of file MemorySSA.h.
References MSSA.
invalidate()
bool MemorySSAAnalysis::Result::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Definition at line 29 of file LoopAnalysisManager.cpp.
References llvm::PreservedAnalyses::allAnalysesInSetPreserved(), llvm::EnableMSSALoopDependency, F, llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
Member Data Documentation
MSSA
std::unique_ptr<MemorySSA> llvm::MemorySSAAnalysis::Result::MSSA
Definition at line 938 of file MemorySSA.h.
Referenced by getMSSA().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/LoopAnalysisManager.cpp
lib/Analysis/MemorySSA.cpp