LLVM: llvm::DenseMapInfo< BasicBlockEdge > Struct Reference
llvm::DenseMapInfo< BasicBlockEdge > Struct Reference
#include "llvm/IR/Dominators.h"
Public Types
using BBInfo = DenseMapInfo< const BasicBlock * >
Static Public Member Functions
static unsigned getHashValue (const BasicBlockEdge *V)
static BasicBlockEdge getEmptyKey ()
static BasicBlockEdge getTombstoneKey ()
static unsigned getHashValue (const BasicBlockEdge &Edge)
static bool isEqual (const BasicBlockEdge &LHS, const BasicBlockEdge &RHS)
Detailed Description
Definition at line 102 of file Dominators.h.
Member Typedef Documentation
BBInfo
using llvm::DenseMapInfo< BasicBlockEdge >::BBInfo = DenseMapInfo<const BasicBlock *>
Definition at line 103 of file Dominators.h.
Member Function Documentation
getEmptyKey()
static BasicBlockEdge llvm::DenseMapInfo< BasicBlockEdge >::getEmptyKey () inline static
Definition at line 107 of file Dominators.h.
References llvm::DenseMapInfo< LocationSize >::getEmptyKey().
getHashValue() [1/2]
static unsigned llvm::DenseMapInfo< BasicBlockEdge >::getHashValue (const BasicBlockEdge & Edge) inline static
Definition at line 115 of file Dominators.h.
References llvm::BasicBlockEdge::getEnd(), llvm::GVNExpression::Expression::getHashValue(), and llvm::BasicBlockEdge::getStart().
getHashValue() [2/2]
static unsigned llvm::DenseMapInfo< BasicBlockEdge >::getHashValue (const BasicBlockEdge * V) static
getTombstoneKey()
static BasicBlockEdge llvm::DenseMapInfo< BasicBlockEdge >::getTombstoneKey () inline static
Definition at line 111 of file Dominators.h.
References llvm::DenseMapInfo< LocationSize >::getTombstoneKey().
isEqual()
static bool llvm::DenseMapInfo< BasicBlockEdge >::isEqual (const BasicBlockEdge & LHS, const BasicBlockEdge & RHS) inline static
Definition at line 120 of file Dominators.h.
References llvm::BasicBlockEdge::getEnd(), llvm::BasicBlockEdge::getStart(), and llvm::DenseMapInfo< LocationSize >::isEqual().
The documentation for this struct was generated from the following file:
include/llvm/IR/Dominators.h