LLVM: llvm::mca::RetireControlUnit Struct Reference
llvm::mca::RetireControlUnit Struct Reference
This class tracks which instructions are in-flight (i.e., dispatched but not retired) in the OoO backend.
#include "llvm/MCA/HardwareUnits/RetireControlUnit.h"
Classes
struct RUToken
Public Member Functions
RetireControlUnit (const MCSchedModel &SM)
bool isEmpty () const
bool isAvailable (unsigned Quantity=1) const
unsigned getMaxRetirePerCycle () const
unsigned reserveSlot (const InstRef &IS, unsigned NumMicroOps)
const RUToken & peekCurrentToken () const
void consumeCurrentToken ()
void onInstructionExecuted (unsigned TokenID)
void dump () const
Public Member Functions inherited from llvm::mca::HardwareUnit
HardwareUnit ()=default
virtual ~HardwareUnit ()
Detailed Description
This class tracks which instructions are in-flight (i.e., dispatched but not retired) in the OoO backend.
This class checks on every cycle if/which instructions can be retired. Instructions are retired in program order. In the event of an instruction being retired, the pipeline that owns this RetireControlUnit (RCU) gets notified.
On instruction retired, register updates are all architecturally committed, and any physicall registers previously allocated for the retired instruction are freed.
Definition at line 36 of file RetireControlUnit.h.
Constructor & Destructor Documentation
RetireControlUnit()
llvm::mca::RetireControlUnit::RetireControlUnit (const MCSchedModel & SM)
Definition at line 22 of file RetireControlUnit.cpp.
References assert(), llvm::MCSchedModel::getExtraProcessorInfo(), llvm::MCSchedModel::hasExtraProcessorInfo(), llvm::MCExtraProcessorInfo::MaxRetirePerCycle, and llvm::MCExtraProcessorInfo::ReorderBufferSize.
Member Function Documentation
consumeCurrentToken()
void llvm::mca::RetireControlUnit::consumeCurrentToken ()
Definition at line 61 of file RetireControlUnit.cpp.
References assert(), llvm::mca::InstRef::getInstruction(), llvm::mca::RetireControlUnit::RUToken::IR, and llvm::mca::RetireControlUnit::RUToken::NumSlots.
Referenced by llvm::mca::RetireStage::cycleStart().
dump()
void llvm::mca::RetireControlUnit::dump () const
Definition at line 80 of file RetireControlUnit.cpp.
References llvm::dbgs().
Referenced by llvm::mca::DispatchStage::dump().
getMaxRetirePerCycle()
unsigned llvm::mca::RetireControlUnit::getMaxRetirePerCycle () const inline
Definition at line 81 of file RetireControlUnit.h.
Referenced by llvm::mca::RetireStage::cycleStart().
isAvailable()
bool llvm::mca::RetireControlUnit::isAvailable (unsigned Quantity = 1) const inline
Definition at line 68 of file RetireControlUnit.h.
Referenced by reserveSlot().
isEmpty()
bool llvm::mca::RetireControlUnit::isEmpty () const inline
Definition at line 67 of file RetireControlUnit.h.
Referenced by llvm::mca::RetireStage::cycleStart().
onInstructionExecuted()
void llvm::mca::RetireControlUnit::onInstructionExecuted (unsigned TokenID)
Definition at line 73 of file RetireControlUnit.cpp.
References assert(), and IR.
Referenced by llvm::mca::RetireStage::execute().
peekCurrentToken()
const RetireControlUnit::RUToken & llvm::mca::RetireControlUnit::peekCurrentToken () const
Definition at line 57 of file RetireControlUnit.cpp.
Referenced by llvm::mca::RetireStage::cycleStart().
reserveSlot()
unsigned llvm::mca::RetireControlUnit::reserveSlot (const InstRef & IS, unsigned NumMicroOps)
Definition at line 40 of file RetireControlUnit.cpp.
References assert(), IR, and isAvailable().
The documentation for this struct was generated from the following files:
include/llvm/MCA/HardwareUnits/RetireControlUnit.h
lib/MCA/HardwareUnits/RetireControlUnit.cpp