LLVM: llvm::MDNodeKeyImpl< MDTuple > Struct Reference
llvm::MDNodeKeyImpl< MDTuple > Struct Reference
DenseMapInfo for MDTuple.
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (ArrayRef< Metadata * > Ops)
MDNodeKeyImpl (const MDTuple *N)
bool isKeyOf (const MDTuple *RHS) const
unsigned getHashValue () const
Public Member Functions inherited from llvm::MDNodeOpsKey
unsigned getHash () const
Static Public Member Functions
static unsigned calculateHash (MDTuple *N)
Additional Inherited Members
Protected Member Functions inherited from llvm::MDNodeOpsKey
MDNodeOpsKey (ArrayRef< Metadata * > Ops)
template<class NodeTy >
MDNodeOpsKey (const NodeTy *N, unsigned Offset=0)
template<class NodeTy >
bool compareOps (const NodeTy *RHS, unsigned Offset=0) const
Static Protected Member Functions inherited from llvm::MDNodeOpsKey
static unsigned calculateHash (MDNode *N, unsigned Offset=0)
Detailed Description
DenseMapInfo for MDTuple.
Note that we don't need the is-function-local bit, since that's implicit in the operands.
Definition at line 264 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< MDTuple >::MDNodeKeyImpl (ArrayRef< Metadata * > Ops) inline
Definition at line 265 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< MDTuple >::MDNodeKeyImpl (const MDTuple * N) inline
Definition at line 266 of file LLVMContextImpl.h.
Member Function Documentation
calculateHash()
static unsigned llvm::MDNodeKeyImpl< MDTuple >::calculateHash (MDTuple * N) inline static
Definition at line 272 of file LLVMContextImpl.h.
References llvm::MDNodeOpsKey::calculateHash(), and N.
getHashValue()
unsigned llvm::MDNodeKeyImpl< MDTuple >::getHashValue () const inline
Definition at line 270 of file LLVMContextImpl.h.
Referenced by llvm::DenseMapInfo< LoweredPHIRecord >::getHashValue(), llvm::DenseMapInfo< MemoryLocOrCall >::getHashValue(), llvm::DenseMapInfo< VTableSlot >::getHashValue(), llvm::ConstantUniqueMap< ConstantClass >::getOrCreate(), and llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace().
isKeyOf()
bool llvm::MDNodeKeyImpl< MDTuple >::isKeyOf (const MDTuple * RHS) const inline
Definition at line 268 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h