LLVM: llvm::ConstantAggrKeyType< ConstantClass > Struct Template Reference
llvm::ConstantAggrKeyType< ConstantClass > Struct Template Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = typename ConstantInfo< ConstantClass >::TypeClass
Public Member Functions
ConstantAggrKeyType (ArrayRef< Constant * > Operands)
ConstantAggrKeyType (ArrayRef< Constant * > Operands, const ConstantClass *)
ConstantAggrKeyType (const ConstantClass *C, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantAggrKeyType &X) const
bool operator== (const ConstantClass *C) const
unsigned getHash () const
ConstantClass * create (TypeClass *Ty) const
Public Attributes
ArrayRef< Constant * > Operands
Detailed Description
template<class ConstantClass>
struct llvm::ConstantAggrKeyType< ConstantClass >
Definition at line 372 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
template<class ConstantClass > using llvm::ConstantAggrKeyType< ConstantClass >::TypeClass = typename ConstantInfo<ConstantClass>::TypeClass
Definition at line 405 of file ConstantsContext.h.
Constructor & Destructor Documentation
ConstantAggrKeyType() [1/3]
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (ArrayRef< Constant * > Operands) inline
Definition at line 375 of file ConstantsContext.h.
ConstantAggrKeyType() [2/3]
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (ArrayRef< Constant * > Operands, const ConstantClass *) inline
Definition at line 377 of file ConstantsContext.h.
ConstantAggrKeyType() [3/3]
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (const ConstantClass * C, SmallVectorImpl< Constant * > & Storage) inline
Definition at line 380 of file ConstantsContext.h.
References assert(), C, E, llvm::SmallVectorBase::empty(), I, llvm::ConstantAggrKeyType< ConstantClass >::Operands, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
create()
template<class ConstantClass > ConstantClass * llvm::ConstantAggrKeyType< ConstantClass >::create (TypeClass * Ty) const inline
Definition at line 407 of file ConstantsContext.h.
References llvm::ConstantAggrKeyType< ConstantClass >::Operands.
getHash()
template<class ConstantClass > unsigned llvm::ConstantAggrKeyType< ConstantClass >::getHash () const inline
Definition at line 401 of file ConstantsContext.h.
References llvm::hash_combine_range(), and llvm::ConstantAggrKeyType< ConstantClass >::Operands.
operator==() [1/2]
template<class ConstantClass > bool llvm::ConstantAggrKeyType< ConstantClass >::operator== (const ConstantAggrKeyType< ConstantClass > & X) const inline
Definition at line 388 of file ConstantsContext.h.
References llvm::ConstantAggrKeyType< ConstantClass >::Operands, and X.
operator==() [2/2]
template<class ConstantClass > bool llvm::ConstantAggrKeyType< ConstantClass >::operator== (const ConstantClass * C) const inline
Definition at line 392 of file ConstantsContext.h.
References C, E, I, and llvm::ConstantAggrKeyType< ConstantClass >::Operands.
Member Data Documentation
Operands
template<class ConstantClass > ArrayRef<Constant *> llvm::ConstantAggrKeyType< ConstantClass >::Operands
Definition at line 373 of file ConstantsContext.h.
Referenced by llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantAggrKeyType< ConstantClass >::create(), llvm::ConstantAggrKeyType< ConstantClass >::getHash(), and llvm::ConstantAggrKeyType< ConstantClass >::operator==().
The documentation for this struct was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/ConstantsContext.h