LLVM: llvm::GraphTraits< CallGraph * > Struct Reference
llvm::GraphTraits< CallGraph * > Struct Reference
#include "llvm/Analysis/CallGraph.h"
Public Types
using PairTy = std::pair< const Function *const, std::unique_ptr< CallGraphNode > >
using nodes_iterator = mapped_iterator< CallGraph::iterator, decltype(&CGGetValuePtr)>
Public Types inherited from llvm::GraphTraits< CallGraphNode * >
using NodeRef = CallGraphNode *
using CGNPairTy = CallGraphNode::CallRecord
using ChildIteratorType = mapped_iterator< CallGraphNode::iterator, decltype(&CGNGetValue)>
Static Public Member Functions
static NodeRef getEntryNode (CallGraph *CGN)
static CallGraphNode * CGGetValuePtr (const PairTy &P)
static nodes_iterator nodes_begin (CallGraph *CG)
static nodes_iterator nodes_end (CallGraph *CG)
Static Public Member Functions inherited from llvm::GraphTraits< CallGraphNode * >
static NodeRef getEntryNode (CallGraphNode *CGN)
static CallGraphNode * CGNGetValue (CGNPairTy P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 455 of file CallGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< CallGraph * >::nodes_iterator = mapped_iterator<CallGraph::iterator, decltype(&CGGetValuePtr)>
Definition at line 468 of file CallGraph.h.
PairTy
using llvm::GraphTraits< CallGraph * >::PairTy = std::pair<const Function *const, std::unique_ptr<CallGraphNode> >
Definition at line 456 of file CallGraph.h.
Member Function Documentation
CGGetValuePtr()
static CallGraphNode * llvm::GraphTraits< CallGraph * >::CGGetValuePtr (const PairTy & P) inline static
Definition at line 463 of file CallGraph.h.
References P.
getEntryNode()
static NodeRef llvm::GraphTraits< CallGraph * >::getEntryNode (CallGraph * CGN) inline static
Definition at line 459 of file CallGraph.h.
References llvm::CallGraph::getExternalCallingNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< CallGraph * >::nodes_begin (CallGraph * CG) inline static
Definition at line 471 of file CallGraph.h.
References llvm::CallGraph::begin().
Referenced by llvm::RegionBase< Tr >::element_begin(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), llvm::GraphTraits< MachineRegionInfoPass * >::nodes_begin(), and llvm::GraphTraits< RegionInfoPass * >::nodes_begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< CallGraph * >::nodes_end (CallGraph * CG) inline static
Definition at line 475 of file CallGraph.h.
References llvm::CallGraph::end().
Referenced by llvm::RegionBase< Tr >::element_end(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), llvm::GraphTraits< MachineRegionInfoPass * >::nodes_end(), and llvm::GraphTraits< RegionInfoPass * >::nodes_end().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CallGraph.h