LLVM: llvm::format_provider< Enum, typename std::enable_if< dwarf::EnumTraits< Enum >::value >::type > Struct Template Reference
llvm::format_provider< Enum, typename std::enable_if< dwarf::EnumTraits< Enum >::value >::type > Struct Template Reference
Dwarf constants format_provider.
#include "llvm/BinaryFormat/Dwarf.h"
Static Public Member Functions
static void format (const Enum &E, raw_ostream &OS, StringRef Style)
Detailed Description
template<typename Enum>
struct llvm::format_provider< Enum, typename std::enable_if< dwarf::EnumTraits< Enum >::value >::type >
Dwarf constants format_provider.
Specialization of the format_provider template for dwarf enums. Unlike the dumping functions above, these format unknown enumerator values as DW_TYPE_unknown_1234 (e.g. DW_TAG_unknown_ffff).
Definition at line 616 of file Dwarf.h.
Member Function Documentation
format()
template<typename Enum > static void llvm::format_provider< Enum, typename std::enable_if< dwarf::EnumTraits< Enum >::value >::type >::format (const Enum & E, raw_ostream & OS, StringRef Style) inline static
Definition at line 618 of file Dwarf.h.
References E, llvm::StringRef::empty(), llvm::format(), and llvm::dwarf::EnumTraits< Attribute >::StringFn.
Referenced by llvm::format_provider< T, typename std::enable_if< detail::use_char_formatter< T >::value >::type >::format(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), and llvm::format_provider< Twine >::format().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/Dwarf.h