LLVM: llvm::FoldingSetTrait< SCEVPredicate > Struct Reference
llvm::FoldingSetTrait< SCEVPredicate > Struct Reference
#include "llvm/Analysis/ScalarEvolution.h"
Static Public Member Functions
static void Profile (const SCEVPredicate &X, FoldingSetNodeID &ID)
static bool Equals (const SCEVPredicate &X, const FoldingSetNodeID &ID, unsigned IDHash, FoldingSetNodeID &TempID)
static unsigned ComputeHash (const SCEVPredicate &X, FoldingSetNodeID &TempID)
Detailed Description
Definition at line 247 of file ScalarEvolution.h.
Member Function Documentation
ComputeHash()
static unsigned llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash (const SCEVPredicate & X, FoldingSetNodeID & TempID) inline static
Definition at line 257 of file ScalarEvolution.h.
References X().
Equals()
static bool llvm::FoldingSetTrait< SCEVPredicate >::Equals (const SCEVPredicate & X, const FoldingSetNodeID & ID, unsigned IDHash, FoldingSetNodeID & TempID) inline static
Definition at line 252 of file ScalarEvolution.h.
References X().
Profile()
static void llvm::FoldingSetTrait< SCEVPredicate >::Profile (const SCEVPredicate & X, FoldingSetNodeID & ID) inline static
Definition at line 248 of file ScalarEvolution.h.
References X().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/ScalarEvolution.h