LLVM: llvm::DWARFDebugLine::Prologue Struct Reference
llvm::DWARFDebugLine::Prologue Struct Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
Public Member Functions
Prologue ()
const dwarf::FormParams getFormParams () const
uint16_t getVersion () const
uint8_t getAddressSize () const
bool isDWARF64 () const
uint32_t sizeofTotalLength () const
uint32_t sizeofPrologueLength () const
bool totalLengthIsValid () const
uint32_t getLength () const
Length of the prologue in bytes.
uint32_t getStatementTableLength () const
Length of the line table data in bytes (not including the prologue).
int32_t getMaxLineIncrementForSpecialOpcode () const
const llvm::DWARFDebugLine::FileNameEntry & getFileNameEntry (uint64_t Index) const
Get DWARF-version aware access to the file name entry at the provided index.
bool hasFileAtIndex (uint64_t FileIndex) const
bool getFileNameByIndex (uint64_t FileIndex, StringRef CompDir, DILineInfoSpecifier::FileLineInfoKind Kind, std::string &Result) const
void clear ()
void dump (raw_ostream &OS, DIDumpOptions DumpOptions) const
Error parse (const DWARFDataExtractor &DebugLineData, uint32_t *OffsetPtr, const DWARFContext &Ctx, const DWARFUnit *U=nullptr)
Public Attributes
uint64_t TotalLength
The size in bytes of the statement information for this compilation unit (not including the total_length field itself).
dwarf::FormParams FormParams
Version, address size (starting in v5), and DWARF32/64 format; these parameters affect interpretation of forms (used in the directory and file tables starting with v5).
uint64_t PrologueLength
The number of bytes following the prologue_length field to the beginning of the first byte of the statement program itself.
uint8_t SegSelectorSize
In v5, size in bytes of a segment selector.
uint8_t MinInstLength
The size in bytes of the smallest target machine instruction.
uint8_t MaxOpsPerInst
The maximum number of individual operations that may be encoded in an instruction.
uint8_t DefaultIsStmt
The initial value of theis_stmtregister.
int8_t LineBase
This parameter affects the meaning of the special opcodes. See below.
uint8_t LineRange
This parameter affects the meaning of the special opcodes. See below.
uint8_t OpcodeBase
The number assigned to the first special opcode.
ContentTypeTracker ContentTypes
This tracks which optional file format content types are present.
std::vector< uint8_t > StandardOpcodeLengths
std::vector< DWARFFormValue > IncludeDirectories
std::vector< FileNameEntry > FileNames
Detailed Description
Definition at line 62 of file DWARFDebugLine.h.
Constructor & Destructor Documentation
Prologue()
DWARFDebugLine::Prologue::Prologue ()
Definition at line 67 of file DWARFDebugLine.cpp.
References clear().
Member Function Documentation
clear()
void DWARFDebugLine::Prologue::clear ()
Definition at line 89 of file DWARFDebugLine.cpp.
References llvm::dwarf::DWARF32.
Referenced by llvm::DWARFDebugLine::LineTable::clear().
dump()
void DWARFDebugLine::Prologue::dump (raw_ostream & OS, DIDumpOptions DumpOptions) const
Definition at line 101 of file DWARFDebugLine.cpp.
References llvm::DWARFDebugLine::FileNameEntry::Checksum, llvm::MD5::MD5Result::digest(), llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::DWARFFormValue::dump(), llvm::format(), I, llvm::DWARFDebugLine::FileNameEntry::Length, llvm::dwarf::LNStandardString(), llvm::DWARFDebugLine::FileNameEntry::ModTime, llvm::DWARFDebugLine::FileNameEntry::Name, and llvm::DWARFDebugLine::FileNameEntry::Source.
Referenced by llvm::DWARFDebugLine::LineTable::dump(), and llvm::DWARFDebugLine::LineTable::parse().
getAddressSize()
uint8_t llvm::DWARFDebugLine::Prologue::getAddressSize () const inline
Definition at line 100 of file DWARFDebugLine.h.
References llvm::dwarf::FormParams::AddrSize, and FormParams.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
getFileNameByIndex()
bool DWARFDebugLine::Prologue::getFileNameByIndex (uint64_t FileIndex, StringRef CompDir, DILineInfoSpecifier::FileLineInfoKind Kind, std::string & Result) const
Definition at line 1010 of file DWARFDebugLine.cpp.
References llvm::sys::path::append(), llvm::StringRef::empty(), isPathAbsoluteOnWindowsOrPosix(), llvm::Entry::Name, and llvm::SmallString< InternalLen >::str().
Referenced by llvm::DWARFDebugLine::LineTable::getFileNameByIndex().
getFileNameEntry()
const llvm::DWARFDebugLine::FileNameEntry & DWARFDebugLine::Prologue::getFileNameEntry (uint64_t Index) const
Get DWARF-version aware access to the file name entry at the provided index.
Definition at line 79 of file DWARFDebugLine.cpp.
References assert().
getFormParams()
const dwarf::FormParams llvm::DWARFDebugLine::Prologue::getFormParams () const inline
Definition at line 98 of file DWARFDebugLine.h.
References FormParams.
getLength()
uint32_t llvm::DWARFDebugLine::Prologue::getLength () const inline
Length of the prologue in bytes.
Definition at line 110 of file DWARFDebugLine.h.
References getVersion(), PrologueLength, sizeofPrologueLength(), and sizeofTotalLength().
Referenced by getStatementTableLength().
getMaxLineIncrementForSpecialOpcode()
int32_t llvm::DWARFDebugLine::Prologue::getMaxLineIncrementForSpecialOpcode () const inline
Definition at line 120 of file DWARFDebugLine.h.
References LineBase, and LineRange.
getStatementTableLength()
uint32_t llvm::DWARFDebugLine::Prologue::getStatementTableLength () const inline
Length of the line table data in bytes (not including the prologue).
Definition at line 116 of file DWARFDebugLine.h.
References getLength(), sizeofTotalLength(), and TotalLength.
getVersion()
uint16_t llvm::DWARFDebugLine::Prologue::getVersion () const inline
Definition at line 99 of file DWARFDebugLine.h.
References FormParams, and llvm::dwarf::FormParams::Version.
Referenced by getLength().
hasFileAtIndex()
bool DWARFDebugLine::Prologue::hasFileAtIndex (uint64_t FileIndex) const
Definition at line 69 of file DWARFDebugLine.cpp.
References assert().
Referenced by llvm::DWARFDebugLine::LineTable::hasFileAtIndex().
isDWARF64()
bool llvm::DWARFDebugLine::Prologue::isDWARF64 () const inline
Definition at line 101 of file DWARFDebugLine.h.
References llvm::dwarf::DWARF64, llvm::dwarf::FormParams::Format, and FormParams.
Referenced by sizeofPrologueLength(), and sizeofTotalLength().
parse()
Error DWARFDebugLine::Prologue::parse (const DWARFDataExtractor & DebugLineData, uint32_t * OffsetPtr, const DWARFContext & Ctx, const DWARFUnit * U = nullptr)
Definition at line 296 of file DWARFDebugLine.cpp.
References llvm::dwarf::FormParams::AddrSize, assert(), clear(), llvm::createStringError(), llvm::dwarf::DWARF64, llvm::dwarf::FormParams::Format, llvm::DataExtractor::getAddressSize(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), I, llvm::invalid_argument, llvm::not_supported, parseV2DirFileTables(), parseV5DirFileTables(), llvm::Error::success(), and llvm::dwarf::FormParams::Version.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
sizeofPrologueLength()
uint32_t llvm::DWARFDebugLine::Prologue::sizeofPrologueLength () const inline
Definition at line 105 of file DWARFDebugLine.h.
References isDWARF64().
Referenced by getLength().
sizeofTotalLength()
uint32_t llvm::DWARFDebugLine::Prologue::sizeofTotalLength () const inline
Definition at line 103 of file DWARFDebugLine.h.
References isDWARF64().
Referenced by getLength(), getStatementTableLength(), and llvm::DWARFDebugLine::LineTable::parse().
totalLengthIsValid()
bool DWARFDebugLine::Prologue::totalLengthIsValid () const
Definition at line 1094 of file DWARFDebugLine.cpp.
Member Data Documentation
ContentTypes
ContentTypeTracker llvm::DWARFDebugLine::Prologue::ContentTypes
This tracks which optional file format content types are present.
Definition at line 93 of file DWARFDebugLine.h.
DefaultIsStmt
uint8_t llvm::DWARFDebugLine::Prologue::DefaultIsStmt
The initial value of theis_stmtregister.
Definition at line 85 of file DWARFDebugLine.h.
FileNames
std::vector<FileNameEntry> llvm::DWARFDebugLine::Prologue::FileNames
Definition at line 96 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
FormParams
dwarf::FormParams llvm::DWARFDebugLine::Prologue::FormParams
Version, address size (starting in v5), and DWARF32/64 format; these parameters affect interpretation of forms (used in the directory and file tables starting with v5).
Definition at line 71 of file DWARFDebugLine.h.
Referenced by getAddressSize(), getFormParams(), getVersion(), and isDWARF64().
IncludeDirectories
std::vector<DWARFFormValue> llvm::DWARFDebugLine::Prologue::IncludeDirectories
Definition at line 95 of file DWARFDebugLine.h.
LineBase
int8_t llvm::DWARFDebugLine::Prologue::LineBase
This parameter affects the meaning of the special opcodes. See below.
Definition at line 87 of file DWARFDebugLine.h.
Referenced by getMaxLineIncrementForSpecialOpcode(), and llvm::DWARFDebugLine::LineTable::parse().
LineRange
uint8_t llvm::DWARFDebugLine::Prologue::LineRange
This parameter affects the meaning of the special opcodes. See below.
Definition at line 89 of file DWARFDebugLine.h.
Referenced by getMaxLineIncrementForSpecialOpcode(), and llvm::DWARFDebugLine::LineTable::parse().
MaxOpsPerInst
uint8_t llvm::DWARFDebugLine::Prologue::MaxOpsPerInst
The maximum number of individual operations that may be encoded in an instruction.
Definition at line 83 of file DWARFDebugLine.h.
MinInstLength
uint8_t llvm::DWARFDebugLine::Prologue::MinInstLength
The size in bytes of the smallest target machine instruction.
Statement program opcodes that alter the address register first multiply their operands by this value.
Definition at line 80 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
OpcodeBase
uint8_t llvm::DWARFDebugLine::Prologue::OpcodeBase
The number assigned to the first special opcode.
Definition at line 91 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
PrologueLength
uint64_t llvm::DWARFDebugLine::Prologue::PrologueLength
The number of bytes following the prologue_length field to the beginning of the first byte of the statement program itself.
Definition at line 74 of file DWARFDebugLine.h.
Referenced by getLength().
SegSelectorSize
uint8_t llvm::DWARFDebugLine::Prologue::SegSelectorSize
In v5, size in bytes of a segment selector.
Definition at line 76 of file DWARFDebugLine.h.
StandardOpcodeLengths
std::vector<uint8_t> llvm::DWARFDebugLine::Prologue::StandardOpcodeLengths
Definition at line 94 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
TotalLength
uint64_t llvm::DWARFDebugLine::Prologue::TotalLength
The size in bytes of the statement information for this compilation unit (not including the total_length field itself).
Definition at line 67 of file DWARFDebugLine.h.
Referenced by getStatementTableLength(), and llvm::DWARFDebugLine::LineTable::parse().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLine.h
lib/DebugInfo/DWARF/DWARFDebugLine.cpp