LLVM: llvm::Attributor Struct Reference
llvm::Attributor Struct Reference
}
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
~Attributor ()
ChangeStatus run ()
Run the analyses until a fixpoint is reached or enforced (timeout).
template<typename AAType >
const AAType * getAAFor (AbstractAttribute &QueryingAA, const Value &V, int ArgNo=-1)
Lookup an abstract attribute of type AAType anchored at value V and argument number ArgNo.
template<typename AAType >
AAType & registerAA (AAType &AA, int ArgNo=-1)
Introduce a new abstract attribute into the fixpoint analysis.
void identifyDefaultAbstractAttributes (Function &F, InformationCache &InfoCache, DenseSet< unsigned > *Whitelist=nullptr)
Determine opportunities to derive 'default' attributes in F and create abstract attribute objects for them.
bool checkForAllCallSites (Function &F, std::function< bool(CallSite)> &Pred, bool RequireAllCallSites)
Check Pred on all function call sites.
Detailed Description
}
The fixpoint analysis framework that orchestrates the attribute deduction.
The Attributor provides a general abstract analysis framework (guided fixpoint iteration) as well as helper functions for the deduction of (LLVM-IR) attributes. However, also other code properties can be deduced, propagated, and ultimately manifested through the Attributor framework. This is particularly useful if these properties interact with attributes and a co-scheduled deduction allows to improve the solution. Even if not, thus if attributes/properties are completely isolated, they should use the Attributor framework to reduce the number of fixpoint iteration frameworks in the code base. Note that the Attributor design makes sure that isolated attributes are not impacted, in any way, by others derived at the same time if there is no cross-reasoning performed.
The public facing interface of the Attributor is kept simple and basically allows abstract attributes to one thing, query abstract attributes in-flight. There are two reasons to do this: a) The optimistic state of one abstract attribute can justify an optimistic state of another, allowing to framework to end up with an optimistic (=best possible) fixpoint instead of one based solely on information in the IR. b) This avoids reimplementing various kinds of lookups, e.g., to check for existing IR attributes, in favor of a single lookups interface provided by an abstract attribute subclass.
NOTE: The mechanics of adding a new "concrete" abstract attribute are described in the file comment.
Definition at line 150 of file Attributor.h.
Constructor & Destructor Documentation
~Attributor()
llvm::Attributor::~Attributor () inline
Definition at line 151 of file Attributor.h.
Member Function Documentation
checkForAllCallSites()
bool Attributor::checkForAllCallSites (Function & F, std::function< bool(CallSite)> & Pred, bool RequireAllCallSites)
Check Pred on all function call sites.
This method will evaluate Pred on call sites and return true if Pred holds in every call sites. However, this is only possible all call sites are known, hence the function has internal linkage.
Attributor
Definition at line 1318 of file Attributor.cpp.
References llvm::dbgs(), F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCaller(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::GlobalValue::hasExactDefinition(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isCallee(), and LLVM_DEBUG.
getAAFor()
template<typename AAType > const AAType * llvm::Attributor::getAAFor (AbstractAttribute & QueryingAA, const Value & V, int ArgNo = -1) inline
Lookup an abstract attribute of type AAType anchored at value V and argument number ArgNo.
If no attribute is found and V is a call base instruction, the called function is tried as a value next. Thus, the returned abstract attribute might be anchored at the callee of V.
This method is the only (supported) way an abstract attribute can retrieve information from another abstract attribute. As an example, take an abstract attribute that determines the memory access behavior for a argument (readnone, readonly, ...). It should use getAAFor to get the most optimistic information for other abstract attributes in-flight, e.g. the one reasoning about the "captured" state for the argument or the one reasoning on the memory access behavior of the function as a whole.
Definition at line 174 of file Attributor.h.
References assert(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledValue(), and llvm::Attribute::None.
identifyDefaultAbstractAttributes()
void Attributor::identifyDefaultAbstractAttributes (Function & F, InformationCache & InfoCache, DenseSet< unsigned > * Whitelist = nullptr)
Determine opportunities to derive 'default' attributes in F and create abstract attribute objects for them.
Parameters
F The function that is checked for attribute opportunities.
InfoCache A cache for information queryable by the new attributes.
Whitelist If not null, a set limiting the attribute opportunities.
Note that abstract attribute instances are generally created even if the IR already contains the information they would deduce. The most important reason for this is the single interface, the one of the abstract attribute instance, which can be queried without the need to look at the IR in various places.
Definition at line 1489 of file Attributor.cpp.
References llvm::Function::arg_size(), assert(), llvm::LazyCallGraph::Edge::Call, F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCalledFunction(), llvm::Value::getType(), I, instructions, llvm::Type::isPointerTy(), registerAA(), and llvm::ARM::WinEH::RuntimeFunction::Ret().
registerAA()
template<typename AAType > AAType & llvm::Attributor::registerAA (AAType & AA, int ArgNo = -1) inline
Introduce a new abstract attribute into the fixpoint analysis.
Note that ownership of the attribute is given to the Attributor. It will invoke delete for the Attributor on destruction of the Attributor.
Attributes are identified by (1) their anchored value (see AA.getAnchoredValue()), (2) their argument number (ArgNo, or Argument::getArgNo()), and (3) their default attribute kind (see AAType::ID).
Definition at line 229 of file Attributor.h.
Referenced by identifyDefaultAbstractAttributes().
run()
ChangeStatus Attributor::run ()
Run the analyses until a fixpoint is reached or enforced (timeout).
The attributes registered with this Attributor can be used after as long as the Attributor is not destroyed (it owns the attributes now).
\Returns CHANGED if the IR was changed, otherwise UNCHANGED.
Definition at line 1355 of file Attributor.cpp.
References llvm::CHANGED, llvm::dbgs(), llvm::AbstractAttribute::getState(), llvm::AbstractState::indicateOptimisticFixpoint(), llvm::AbstractState::indicatePessimisticFixpoint(), llvm::AbstractState::isAtFixpoint(), llvm::AbstractState::isValidState(), LLVM_DEBUG, llvm_unreachable, MaxFixpointIterations, run(), llvm::UNCHANGED, and VerifyAttributor.
Referenced by run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp