LLVM: AANoSyncFunction Struct Reference
AANoSyncFunction Struct Reference
---------------------— NoSync Function Attribute ----------------------—
Public Member Functions
AANoSyncFunction (Function &F, InformationCache &InfoCache)
AbstractState & getState () override
See AbstractAttribute::getState() {.
const AbstractState & getState () const override
Return the internal abstract state for inspection.
ManifestPosition getManifestPosition () const override
}
const std::string getAsStr () const override
This function should return the "summarized" assumed state as string.
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
bool isAssumedNoSync () const override
See AANoSync::isAssumedNoSync()
bool isKnownNoSync () const override
See AANoSync::isKnownNoSync()
Public Member Functions inherited from llvm::AANoSync
AANoSync (Value &V, InformationCache &InfoCache)
An abstract interface for all nosync attributes.
Attribute::AttrKind getAttrKind () const override
See AbstractAttribute::getAttrKind().
virtual bool isAssumedNoSync () const =0
Returns true if "nosync" is assumed.
virtual bool isKnownNoSync () const =0
Returns true if "nosync" is known.
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (Value *AssociatedVal, Value &AnchoredVal, InformationCache &InfoCache)
An abstract attribute associated with AssociatedVal and anchored at AnchoredVal.
AbstractAttribute (Value &V, InformationCache &InfoCache)
An abstract attribute associated with and anchored at V.
virtual ~AbstractAttribute ()
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual const AbstractState & getState () const =0
Return the internal abstract state for inspection.
Value & getAnchoredValue ()
Return the value this abstract attribute is anchored with.
const Value & getAnchoredValue () const
Function & getAnchorScope ()
}
const Function & getAnchorScope () const
virtual Value * getAssociatedValue ()
}
virtual const Value * getAssociatedValue () const
virtual ManifestPosition getManifestPosition () const =0
}
virtual Attribute::AttrKind getAttrKind () const =0
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
virtual void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void dump () const
virtual const std::string getAsStr () const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::BooleanState
BooleanState ()
Public Member Functions inherited from llvm::IntegerState
IntegerState (base_t BestState=~0)
Initialize the (best) state.
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
void indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
void indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool isKnown (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "assumed bits".
IntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
IntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
IntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual void indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual void indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Static Public Member Functions
static bool isNonRelaxedAtomic (Instruction *I)
Helper function used to determine whether an instruction is non-relaxed atomic.
static bool isVolatile (Instruction *I)
Helper function used to determine whether an instruction is volatile.
static bool isNoSyncIntrinsic (Instruction *I)
Helper function uset to check if intrinsic is volatile (memcpy, memmove, memset).
Static Public Member Functions inherited from llvm::IntegerState
static constexpr base_t getWorstState ()
Return the worst possible representable state.
Additional Inherited Members
Public Types inherited from llvm::AbstractAttribute
enum ManifestPosition { MP_ARGUMENT , MP_CALL_SITE_ARGUMENT , MP_FUNCTION , MP_RETURNED }
The positions attributes can be manifested in.
Public Types inherited from llvm::IntegerState
using base_t = uint32_t
Underlying integer type, we assume 32 bits to be enough.
Static Public Attributes inherited from llvm::AANoSync
static constexpr Attribute::AttrKind ID
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual AbstractState & getState ()=0
Return the internal abstract state for careful modification.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Attributes inherited from llvm::AbstractAttribute
Value * AssociatedVal
The value this abstract attribute is associated with.
Value & AnchoredVal
The value this abstract attribute is anchored at.
InformationCache & InfoCache
The information cache accessible to this abstract attribute.
Detailed Description
---------------------— NoSync Function Attribute ----------------------—
Definition at line 755 of file Attributor.cpp.
Constructor & Destructor Documentation
AANoSyncFunction()
AANoSyncFunction::AANoSyncFunction (Function & F, InformationCache & InfoCache) inline
Definition at line 757 of file Attributor.cpp.
Member Function Documentation
getAsStr()
const std::string AANoSyncFunction::getAsStr () const inline override virtual
This function should return the "summarized" assumed state as string.
Implements llvm::AbstractAttribute.
Definition at line 769 of file Attributor.cpp.
getManifestPosition()
ManifestPosition AANoSyncFunction::getManifestPosition () const inline override virtual
}
See AbstractAttribute::getManifestPosition().
Implements llvm::AbstractAttribute.
Definition at line 767 of file Attributor.cpp.
getState() [1/2]
const AbstractState & AANoSyncFunction::getState () const inline override virtual
Return the internal abstract state for inspection.
Implements llvm::AbstractAttribute.
Definition at line 763 of file Attributor.cpp.
getState() [2/2]
AbstractState & AANoSyncFunction::getState () inline override virtual
See AbstractAttribute::getState() {.
Implements llvm::AbstractAttribute.
Definition at line 762 of file Attributor.cpp.
isAssumedNoSync()
bool AANoSyncFunction::isAssumedNoSync () const inline override virtual
See AANoSync::isAssumedNoSync()
Implements llvm::AANoSync.
Definition at line 777 of file Attributor.cpp.
isKnownNoSync()
bool AANoSyncFunction::isKnownNoSync () const inline override virtual
See AANoSync::isKnownNoSync()
Implements llvm::AANoSync.
Definition at line 780 of file Attributor.cpp.
isNonRelaxedAtomic()
bool AANoSyncFunction::isNonRelaxedAtomic (Instruction * I) static
Helper function used to determine whether an instruction is non-relaxed atomic.
In other words, if an atomic instruction does not have unordered or monotonic ordering
Definition at line 795 of file Attributor.cpp.
References I, llvm_unreachable, llvm::Monotonic, llvm::SyncScope::SingleThread, and llvm::Unordered.
isNoSyncIntrinsic()
bool AANoSyncFunction::isNoSyncIntrinsic (Instruction * I) static
Helper function uset to check if intrinsic is volatile (memcpy, memmove, memset).
Checks if an intrinsic is nosync.
Currently only checks mem* intrinsics. FIXME: We should ipmrove the handling of intrinsics.
Element wise atomic memory intrinsics are can only be unordered, therefore nosync.
Definition at line 844 of file Attributor.cpp.
References I, and isVolatile().
isVolatile()
bool AANoSyncFunction::isVolatile (Instruction * I) static
Helper function used to determine whether an instruction is volatile.
Definition at line 866 of file Attributor.cpp.
References assert(), and I.
updateImpl()
ChangeStatus AANoSyncFunction::updateImpl (Attributor & A) override virtual
See AbstractAttribute::updateImpl(...).
We are looking for volatile instructions or Non-Relaxed atomics. FIXME: We should ipmrove the handling of intrinsics.
Implements llvm::AbstractAttribute.
Definition at line 884 of file Attributor.cpp.
References llvm::LazyCallGraph::Edge::Call, llvm::CHANGED, F, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::hasFnAttr(), I, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isConvergent(), isVolatile(), and llvm::UNCHANGED.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/Attributor.cpp