LLVM: FusionCandidate Struct Reference
FusionCandidate Struct Reference
This class is used to represent a candidate for loop fusion.
Public Member Functions
FusionCandidate (Loop *L, const DominatorTree *DT, const PostDominatorTree *PDT)
bool isValid () const
Check if all members of the class are valid.
void verify () const
Verify that all members are in sync with the Loop object.
LLVM_DUMP_METHOD void dump () const
Public Attributes
BasicBlock * Preheader
Cache of parts of the loop used throughout loop fusion.
BasicBlock * Header
Header of the loop this candidate represents.
BasicBlock * ExitingBlock
Blocks in the loop that exit the loop.
BasicBlock * ExitBlock
The successor block of this loop (where the exiting blocks go to)
BasicBlock * Latch
Latch of the loop.
Loop * L
The loop that this fusion candidate represents.
SmallVector< Instruction *, 16 > MemReads
Vector of instructions in this loop that read from memory.
SmallVector< Instruction *, 16 > MemWrites
Vector of instructions in this loop that write to memory.
bool Valid
Are all of the members of this fusion candidate still valid.
const DominatorTree * DT
Dominator and PostDominator trees are needed for the FusionCandidateCompare function, required by FusionCandidateSet to determine where the FusionCandidate should be inserted into the set.
const PostDominatorTree * PDT
Detailed Description
This class is used to represent a candidate for loop fusion.
When it is constructed, it checks the conditions for loop fusion to ensure that it represents a valid candidate. It caches several parts of a loop that are used throughout loop fusion (e.g., loop preheader, loop header, etc) instead of continually querying the underlying Loop to retrieve these values. It is assumed these will not change throughout loop fusion.
The invalidate method should be used to indicate that the FusionCandidate is no longer a valid candidate for fusion. Similarly, the isValid() method can be used to ensure that the FusionCandidate is still valid for fusion.
Definition at line 123 of file LoopFuse.cpp.
Constructor & Destructor Documentation
FusionCandidate()
FusionCandidate::FusionCandidate (Loop * L, const DominatorTree * DT, const PostDominatorTree * PDT) inline
Definition at line 154 of file LoopFuse.cpp.
References llvm::LoopBase< BlockT, LoopT >::blocks(), I, L, MemReads, and MemWrites.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void FusionCandidate::dump () const inline
Definition at line 218 of file LoopFuse.cpp.
References llvm::dbgs(), ExitBlock, ExitingBlock, llvm::Value::getName(), Header, Latch, and Preheader.
isValid()
bool FusionCandidate::isValid () const inline
Check if all members of the class are valid.
Definition at line 200 of file LoopFuse.cpp.
References ExitBlock, ExitingBlock, Header, llvm::LoopBase< BlockT, LoopT >::isInvalid(), L, Latch, Preheader, and Valid.
Referenced by operator<<(), and verify().
verify()
void FusionCandidate::verify () const inline
Verify that all members are in sync with the Loop object.
Definition at line 206 of file LoopFuse.cpp.
References assert(), ExitBlock, ExitingBlock, llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), Header, llvm::LoopBase< BlockT, LoopT >::isInvalid(), isValid(), L, Latch, and Preheader.
Member Data Documentation
DT
const DominatorTree* FusionCandidate::DT
Dominator and PostDominator trees are needed for the FusionCandidateCompare function, required by FusionCandidateSet to determine where the FusionCandidate should be inserted into the set.
These are used to establish ordering of the FusionCandidates based on dominance.
Definition at line 151 of file LoopFuse.cpp.
Referenced by FusionCandidateCompare::operator()().
ExitBlock
BasicBlock* FusionCandidate::ExitBlock
The successor block of this loop (where the exiting blocks go to)
Definition at line 135 of file LoopFuse.cpp.
Referenced by dump(), isValid(), and verify().
ExitingBlock
BasicBlock* FusionCandidate::ExitingBlock
Blocks in the loop that exit the loop.
Definition at line 133 of file LoopFuse.cpp.
Referenced by dump(), isValid(), and verify().
Header
BasicBlock* FusionCandidate::Header
Header of the loop this candidate represents.
Definition at line 131 of file LoopFuse.cpp.
Referenced by dump(), isValid(), and verify().
L
Loop* FusionCandidate::L
The loop that this fusion candidate represents.
Definition at line 139 of file LoopFuse.cpp.
Referenced by FusionCandidate(), isValid(), and verify().
Latch
BasicBlock* FusionCandidate::Latch
Latch of the loop.
Definition at line 137 of file LoopFuse.cpp.
Referenced by dump(), isValid(), and verify().
MemReads
SmallVector<Instruction *, 16> FusionCandidate::MemReads
Vector of instructions in this loop that read from memory.
Definition at line 141 of file LoopFuse.cpp.
Referenced by FusionCandidate().
MemWrites
SmallVector<Instruction *, 16> FusionCandidate::MemWrites
Vector of instructions in this loop that write to memory.
Definition at line 143 of file LoopFuse.cpp.
Referenced by FusionCandidate().
PDT
const PostDominatorTree* FusionCandidate::PDT
Definition at line 152 of file LoopFuse.cpp.
Referenced by FusionCandidateCompare::operator()().
Preheader
BasicBlock* FusionCandidate::Preheader
Cache of parts of the loop used throughout loop fusion.
These should not need to change throughout the analysis and transformation. These parts are cached to avoid repeatedly looking up in the Loop class. Preheader of the loop this candidate represents
Definition at line 129 of file LoopFuse.cpp.
Referenced by dump(), isValid(), FusionCandidateCompare::operator()(), operator<<(), reportLoopFusion(), and verify().
Valid
bool FusionCandidate::Valid
Are all of the members of this fusion candidate still valid.
Definition at line 145 of file LoopFuse.cpp.
Referenced by isValid().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopFuse.cpp