LLVM: llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > Struct Template Reference
llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
UAddWithOverflow_match (const LHS_t &L, const RHS_t &R, const Sum_t &S)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
LHS_t L
RHS_t R
Sum_t S
Detailed Description
template<typename LHS_t, typename RHS_t, typename Sum_t>
struct llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >
Definition at line 1487 of file PatternMatch.h.
Constructor & Destructor Documentation
UAddWithOverflow_match()
template<typename LHS_t , typename RHS_t , typename Sum_t > llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::UAddWithOverflow_match (const LHS_t & L, const RHS_t & R, const Sum_t & S) inline
Definition at line 1492 of file PatternMatch.h.
Member Function Documentation
match()
template<typename LHS_t , typename RHS_t , typename Sum_t > template<typename OpTy > bool llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match (OpTy * V) inline
Definition at line 1495 of file PatternMatch.h.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::L, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::R, and llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::S.
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
Member Data Documentation
L
template<typename LHS_t , typename RHS_t , typename Sum_t > LHS_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::L
Definition at line 1488 of file PatternMatch.h.
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
R
template<typename LHS_t , typename RHS_t , typename Sum_t > RHS_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::R
Definition at line 1489 of file PatternMatch.h.
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
S
template<typename LHS_t , typename RHS_t , typename Sum_t > Sum_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::S
Definition at line 1490 of file PatternMatch.h.
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h