LLVM: llvm::objcarc::BottomUpPtrState Struct Reference
llvm::objcarc::BottomUpPtrState Struct Reference
#include "Transforms/ObjCARC/PtrState.h"
Public Member Functions
BottomUpPtrState ()=default
bool InitBottomUp (ARCMDKindCache &Cache, Instruction *I)
(Re-)Initialize this bottom up pointer returning true if we detected a pointer with nested releases.
bool MatchWithRetain ()
Return true if this set of releases can be paired with a release.
void HandlePotentialUse (BasicBlock *BB, Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
bool HandlePotentialAlterRefCount (Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Public Member Functions inherited from llvm::objcarc::PtrState
bool IsKnownSafe () const
void SetKnownSafe (const bool NewValue)
bool IsTailCallRelease () const
void SetTailCallRelease (const bool NewValue)
bool IsTrackingImpreciseReleases () const
const MDNode * GetReleaseMetadata () const
void SetReleaseMetadata (MDNode *NewValue)
bool IsCFGHazardAfflicted () const
void SetCFGHazardAfflicted (const bool NewValue)
void SetKnownPositiveRefCount ()
void ClearKnownPositiveRefCount ()
bool HasKnownPositiveRefCount () const
void SetSeq (Sequence NewSeq)
Sequence GetSeq () const
void ClearSequenceProgress ()
void ResetSequenceProgress (Sequence NewSeq)
void Merge (const PtrState &Other, bool TopDown)
void InsertCall (Instruction *I)
void InsertReverseInsertPt (Instruction *I)
void ClearReverseInsertPts ()
bool HasReverseInsertPts () const
const RRInfo & GetRRInfo () const
Additional Inherited Members
Protected Member Functions inherited from llvm::objcarc::PtrState
PtrState ()
Protected Attributes inherited from llvm::objcarc::PtrState
bool KnownPositiveRefCount = false
True if the reference count is known to be incremented.
bool Partial = false
True if we've seen an opportunity for partial RR elimination, such as pushing calls into a CFG triangle or into one side of a CFG diamond.
unsigned char Seq: 8
The current position in the sequence.
RRInfo RRI
Unidirectional information about the current sequence.
Detailed Description
Definition at line 168 of file PtrState.h.
Constructor & Destructor Documentation
BottomUpPtrState()
llvm::objcarc::BottomUpPtrState::BottomUpPtrState () default
Member Function Documentation
HandlePotentialAlterRefCount()
bool BottomUpPtrState::HandlePotentialAlterRefCount (Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Definition at line 228 of file PtrState.cpp.
References llvm::objcarc::CanAlterRefCount(), llvm::dbgs(), llvm::objcarc::PtrState::GetSeq(), LLVM_DEBUG, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, llvm::objcarc::S_Use, and llvm::objcarc::PtrState::SetSeq().
HandlePotentialUse()
void BottomUpPtrState::HandlePotentialUse (BasicBlock * BB, Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Definition at line 256 of file PtrState.cpp.
References assert(), llvm::objcarc::Call, llvm::objcarc::CanUse(), llvm::dbgs(), llvm::BasicBlock::end(), llvm::objcarc::GetBasicARCInstKind(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::objcarc::getreturnRVOperand(), llvm::objcarc::PtrState::GetSeq(), llvm::objcarc::PtrState::HasReverseInsertPts(), llvm::objcarc::PtrState::InsertReverseInsertPt(), llvm::objcarc::IsUser(), LLVM_DEBUG, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, llvm::objcarc::S_Use, llvm::objcarc::PtrState::Seq, llvm::objcarc::PtrState::SetCFGHazardAfflicted(), and llvm::objcarc::PtrState::SetSeq().
InitBottomUp()
bool BottomUpPtrState::InitBottomUp (ARCMDKindCache & Cache, Instruction * I)
(Re-)Initialize this bottom up pointer returning true if we detected a pointer with nested releases.
Definition at line 177 of file PtrState.cpp.
References llvm::dbgs(), llvm::objcarc::ARCMDKindCache::get(), llvm::objcarc::PtrState::GetSeq(), llvm::objcarc::PtrState::HasKnownPositiveRefCount(), I, llvm::objcarc::ImpreciseRelease, llvm::objcarc::PtrState::InsertCall(), LLVM_DEBUG, llvm::objcarc::PtrState::ResetSequenceProgress(), llvm::objcarc::S_MovableRelease, llvm::objcarc::S_Release, llvm::objcarc::PtrState::SetKnownPositiveRefCount(), llvm::objcarc::PtrState::SetKnownSafe(), llvm::objcarc::PtrState::SetReleaseMetadata(), and llvm::objcarc::PtrState::SetTailCallRelease().
MatchWithRetain()
bool BottomUpPtrState::MatchWithRetain ()
Return true if this set of releases can be paired with a release.
Modifies state appropriately to reflect that the matching occurred if it is successful.
It is assumed that one has already checked that the RCIdentity of the retain and the RCIdentity of this ptr state are the same.
Definition at line 204 of file PtrState.cpp.
References llvm::objcarc::PtrState::ClearReverseInsertPts(), llvm::objcarc::PtrState::GetSeq(), llvm::objcarc::PtrState::IsTrackingImpreciseReleases(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, llvm::objcarc::S_Use, and llvm::objcarc::PtrState::SetKnownPositiveRefCount().
The documentation for this struct was generated from the following files:
lib/Transforms/ObjCARC/PtrState.h
lib/Transforms/ObjCARC/PtrState.cpp