LLVM: llvm::DenseMapInfo< VTableSlot > Struct Reference
llvm::DenseMapInfo< VTableSlot > Struct Reference
Static Public Member Functions
static VTableSlot getEmptyKey ()
static VTableSlot getTombstoneKey ()
static unsigned getHashValue (const VTableSlot &I)
static bool isEqual (const VTableSlot &LHS, const VTableSlot &RHS)
Detailed Description
Definition at line 249 of file WholeProgramDevirt.cpp.
Member Function Documentation
getEmptyKey()
static VTableSlot llvm::DenseMapInfo< VTableSlot >::getEmptyKey () inline static
Definition at line 250 of file WholeProgramDevirt.cpp.
References llvm::DenseMapInfo< cflaa::InstantiatedValue >::getEmptyKey().
getHashValue()
static unsigned llvm::DenseMapInfo< VTableSlot >::getHashValue (const VTableSlot & I) inline static
Definition at line 258 of file WholeProgramDevirt.cpp.
References llvm::MDNodeKeyImpl< MDTuple >::getHashValue(), and I.
getTombstoneKey()
static VTableSlot llvm::DenseMapInfo< VTableSlot >::getTombstoneKey () inline static
Definition at line 254 of file WholeProgramDevirt.cpp.
References llvm::DenseMapInfo< cflaa::InstantiatedValue >::getTombstoneKey().
isEqual()
static bool llvm::DenseMapInfo< VTableSlot >::isEqual (const VTableSlot & LHS, const VTableSlot & RHS) inline static
Definition at line 262 of file WholeProgramDevirt.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/WholeProgramDevirt.cpp