LLVM: llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT Struct Reference
llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT Struct Reference
#include "llvm/ADT/FunctionExtras.h"
Public Attributes
void * StoragePtr
size_t Size
size_t Alignment
Detailed Description
template<typename ReturnT, typename... ParamTs>
struct llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT
Definition at line 104 of file FunctionExtras.h.
Member Data Documentation
Alignment
template<typename ReturnT , typename... ParamTs> size_t llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::Alignment
Definition at line 107 of file FunctionExtras.h.
Referenced by llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), addRawAttributeValue(), llvm::AttributeSetNode::get(), llvm::Attribute::getAlignment(), llvm::AttributeSetNode::getAlignment(), llvm::Attribute::getAsString(), getAttrFromCode(), getAttrKindEncoding(), getParameterABIAttributes(), getRawAttributeMask(), llvm::IntAttributeImpl::IntAttributeImpl(), llvm::AttrBuilder::removeAttribute(), llvm::MemIntrinsicBase< Derived >::setDestAlignment(), and llvm::MemTransferBase< BaseCL >::setSourceAlignment().
Size
template<typename ReturnT , typename... ParamTs> size_t llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::Size
Definition at line 106 of file FunctionExtras.h.
StoragePtr
template<typename ReturnT , typename... ParamTs> void* llvm::unique_function< ReturnT(ParamTs...)>::StorageUnionT::OutOfLineStorageT::StoragePtr
Definition at line 105 of file FunctionExtras.h.
The documentation for this struct was generated from the following file:
include/llvm/ADT/FunctionExtras.h