LLVM: llvm::GraphTraits< RegionInfoPass * > Struct Reference
llvm::GraphTraits< RegionInfoPass * > Struct Reference
#include "llvm/Analysis/RegionIterator.h"
Public Types
using nodes_iterator = df_iterator< NodeRef, df_iterator_default_set< NodeRef >, false, GraphTraits< FlatIt< NodeRef > > >
Public Types inherited from llvm::GraphTraits< RegionInfo * >
using nodes_iterator = df_iterator< NodeRef, df_iterator_default_set< NodeRef >, false, GraphTraits< FlatIt< NodeRef > > >
Static Public Member Functions
static NodeRef getEntryNode (RegionInfoPass *RI)
static nodes_iterator nodes_begin (RegionInfoPass *RI)
static nodes_iterator nodes_end (RegionInfoPass *RI)
Static Public Member Functions inherited from llvm::GraphTraits< RegionInfo * >
static NodeRef getEntryNode (RegionInfo *RI)
static nodes_iterator nodes_begin (RegionInfo *RI)
static nodes_iterator nodes_end (RegionInfo *RI)
Detailed Description
Definition at line 338 of file RegionIterator.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< RegionInfoPass * >::nodes_iterator = df_iterator<NodeRef, df_iterator_default_set<NodeRef>, false, GraphTraits<FlatIt<NodeRef> >>
Definition at line 340 of file RegionIterator.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< RegionInfoPass * >::getEntryNode (RegionInfoPass * RI) inline static
Definition at line 344 of file RegionIterator.h.
References llvm::GraphTraits< CallGraphNode * >::getEntryNode(), and llvm::RegionInfoPass::getRegionInfo().
nodes_begin()
static nodes_iterator llvm::GraphTraits< RegionInfoPass * >::nodes_begin (RegionInfoPass * RI) inline static
Definition at line 348 of file RegionIterator.h.
References llvm::RegionInfoPass::getRegionInfo(), and llvm::GraphTraits< CallGraph * >::nodes_begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< RegionInfoPass * >::nodes_end (RegionInfoPass * RI) inline static
Definition at line 352 of file RegionIterator.h.
References llvm::RegionInfoPass::getRegionInfo(), and llvm::GraphTraits< CallGraph * >::nodes_end().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/RegionIterator.h