LLVM: llvm::DenseMapInfo< OffsetInstantiatedValue > Struct Reference
llvm::DenseMapInfo< OffsetInstantiatedValue > Struct Reference
Static Public Member Functions
static OffsetInstantiatedValue getEmptyKey ()
static OffsetInstantiatedValue getTombstoneKey ()
static unsigned getHashValue (const OffsetInstantiatedValue &OVal)
static bool isEqual (const OffsetInstantiatedValue &LHS, const OffsetInstantiatedValue &RHS)
Detailed Description
Definition at line 294 of file CFLAndersAliasAnalysis.cpp.
Member Function Documentation
getEmptyKey()
static OffsetInstantiatedValue llvm::DenseMapInfo< OffsetInstantiatedValue >::getEmptyKey () inline static
Definition at line 295 of file CFLAndersAliasAnalysis.cpp.
References llvm::DenseMapInfo< LocationSize >::getEmptyKey().
getHashValue()
static unsigned llvm::DenseMapInfo< OffsetInstantiatedValue >::getHashValue (const OffsetInstantiatedValue & OVal) inline static
Definition at line 307 of file CFLAndersAliasAnalysis.cpp.
getTombstoneKey()
static OffsetInstantiatedValue llvm::DenseMapInfo< OffsetInstantiatedValue >::getTombstoneKey () inline static
Definition at line 301 of file CFLAndersAliasAnalysis.cpp.
References llvm::DenseMapInfo< LocationSize >::getEmptyKey(), and llvm::DenseMapInfo< LocationSize >::getTombstoneKey().
isEqual()
static bool llvm::DenseMapInfo< OffsetInstantiatedValue >::isEqual (const OffsetInstantiatedValue & LHS, const OffsetInstantiatedValue & RHS) inline static
Definition at line 312 of file CFLAndersAliasAnalysis.cpp.
The documentation for this struct was generated from the following file:
lib/Analysis/CFLAndersAliasAnalysis.cpp