LLVM: llvm::TimeTraceProfiler Struct Reference
llvm::TimeTraceProfiler Struct Reference
Public Member Functions
TimeTraceProfiler ()
void begin (std::string Name, llvm::function_ref< std::string()> Detail)
void end ()
void Write (raw_pwrite_stream &OS)
Public Attributes
SmallVector< Entry, 16 > Stack
SmallVector< Entry, 128 > Entries
StringMap< CountAndDurationType > CountAndTotalPerName
time_point< steady_clock > StartTime
Detailed Description
Definition at line 52 of file TimeProfiler.cpp.
Constructor & Destructor Documentation
TimeTraceProfiler()
llvm::TimeTraceProfiler::TimeTraceProfiler () inline
Definition at line 53 of file TimeProfiler.cpp.
References StartTime.
Member Function Documentation
begin()
void llvm::TimeTraceProfiler::begin (std::string Name, llvm::function_ref< std::string()> Detail) inline
Definition at line 57 of file TimeProfiler.cpp.
References Stack.
Referenced by llvm::timeTraceProfilerBegin().
end()
void llvm::TimeTraceProfiler::end () inline
Definition at line 62 of file TimeProfiler.cpp.
References assert(), CountAndTotalPerName, Entries, Stack, and llvm::TimeTraceGranularity().
Referenced by llvm::timeTraceProfilerEnd().
Write()
void llvm::TimeTraceProfiler::Write (raw_pwrite_stream & OS) inline
Definition at line 87 of file TimeProfiler.cpp.
References assert(), CountAndTotalPerName, Entries, Stack, and StartTime.
Referenced by llvm::timeTraceProfilerWrite().
Member Data Documentation
CountAndTotalPerName
StringMap<CountAndDurationType> llvm::TimeTraceProfiler::CountAndTotalPerName
Definition at line 162 of file TimeProfiler.cpp.
Referenced by end(), and Write().
Entries
SmallVector<Entry, 128> llvm::TimeTraceProfiler::Entries
Definition at line 161 of file TimeProfiler.cpp.
Referenced by end(), and Write().
Stack
SmallVector<Entry, 16> llvm::TimeTraceProfiler::Stack
Definition at line 160 of file TimeProfiler.cpp.
Referenced by begin(), end(), and Write().
StartTime
time_point<steady_clock> llvm::TimeTraceProfiler::StartTime
Definition at line 163 of file TimeProfiler.cpp.
Referenced by TimeTraceProfiler(), and Write().
The documentation for this struct was generated from the following file:
lib/Support/TimeProfiler.cpp