LLVM: llvm::AnonStructTypeKeyInfo Struct Reference
llvm::AnonStructTypeKeyInfo Struct Reference
#include "IR/LLVMContextImpl.h"
Classes
struct KeyTy
Static Public Member Functions
static StructType * getEmptyKey ()
static StructType * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const StructType *ST)
static bool isEqual (const KeyTy &LHS, const StructType *RHS)
static bool isEqual (const StructType *LHS, const StructType *RHS)
Detailed Description
Definition at line 97 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
static StructType * llvm::AnonStructTypeKeyInfo::getEmptyKey () inline static
Definition at line 120 of file LLVMContextImpl.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getEmptyKey().
Referenced by isEqual().
getHashValue() [1/2]
static unsigned llvm::AnonStructTypeKeyInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 128 of file LLVMContextImpl.h.
References llvm::hash_combine(), and llvm::hash_combine_range().
Referenced by getHashValue().
getHashValue() [2/2]
static unsigned llvm::AnonStructTypeKeyInfo::getHashValue (const StructType * ST) inline static
Definition at line 134 of file LLVMContextImpl.h.
References getHashValue().
getTombstoneKey()
static StructType * llvm::AnonStructTypeKeyInfo::getTombstoneKey () inline static
Definition at line 124 of file LLVMContextImpl.h.
References llvm::DenseMapInfo< CachedHashStringRef >::getTombstoneKey().
Referenced by isEqual().
isEqual() [1/2]
static bool llvm::AnonStructTypeKeyInfo::isEqual (const KeyTy & LHS, const StructType * RHS) inline static
Definition at line 138 of file LLVMContextImpl.h.
References getEmptyKey(), and getTombstoneKey().
isEqual() [2/2]
static bool llvm::AnonStructTypeKeyInfo::isEqual (const StructType * LHS, const StructType * RHS) inline static
Definition at line 144 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h