LLVM: llvm::DenseMapInfo< CachedHashStringRef > Struct Reference
llvm::DenseMapInfo< CachedHashStringRef > Struct Reference
#include "llvm/ADT/CachedHashString.h"
Static Public Member Functions
static CachedHashStringRef getEmptyKey ()
static CachedHashStringRef getTombstoneKey ()
static unsigned getHashValue (const CachedHashStringRef &S)
static bool isEqual (const CachedHashStringRef &LHS, const CachedHashStringRef &RHS)
Detailed Description
Definition at line 50 of file CachedHashString.h.
Member Function Documentation
getEmptyKey()
static CachedHashStringRef llvm::DenseMapInfo< CachedHashStringRef >::getEmptyKey () inline static
Definition at line 51 of file CachedHashString.h.
Referenced by llvm::EliminateDuplicatePHINodes(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::getEmptyKey(), llvm::DenseMapInfo< codeview::TypeIndex >::getEmptyKey(), llvm::DenseMapInfo< gsym::FileEntry >::getEmptyKey(), llvm::DenseMapInfo< BasicBlockEdge >::getEmptyKey(), llvm::DenseMapInfo< cflaa::InstantiatedValue >::getEmptyKey(), llvm::DenseMapInfo< OffsetValue >::getEmptyKey(), llvm::DenseMapInfo< OffsetInstantiatedValue >::getEmptyKey(), llvm::AnonStructTypeKeyInfo::getEmptyKey(), llvm::FunctionTypeKeyInfo::getEmptyKey(), llvm::MDNodeInfo< NodeTy >::getEmptyKey(), llvm::DenseMapInfo< CIEKey >::getEmptyKey(), llvm::DenseMapInfo< VTableSlot >::getEmptyKey(), llvm::DenseMapInfo< SimpleValue >::getEmptyKey(), llvm::DenseMapInfo< CallValue >::getEmptyKey(), llvm::DenseMapInfo< OffsetValue >::getTombstoneKey(), llvm::DenseMapInfo< OffsetInstantiatedValue >::getTombstoneKey(), llvm::ValueHandleBase::isValid(), and markAliveBlocks().
getHashValue()
static unsigned llvm::DenseMapInfo< CachedHashStringRef >::getHashValue (const CachedHashStringRef & S) inline static
Definition at line 57 of file CachedHashString.h.
References assert(), llvm::CachedHashStringRef::hash(), and llvm::isEqual().
getTombstoneKey()
static CachedHashStringRef llvm::DenseMapInfo< CachedHashStringRef >::getTombstoneKey () inline static
Definition at line 54 of file CachedHashString.h.
Referenced by llvm::EliminateDuplicatePHINodes(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::getTombstoneKey(), llvm::DenseMapInfo< codeview::TypeIndex >::getTombstoneKey(), llvm::DenseMapInfo< gsym::FileEntry >::getTombstoneKey(), llvm::DenseMapInfo< BasicBlockEdge >::getTombstoneKey(), llvm::DenseMapInfo< cflaa::InstantiatedValue >::getTombstoneKey(), llvm::DenseMapInfo< OffsetValue >::getTombstoneKey(), llvm::DenseMapInfo< OffsetInstantiatedValue >::getTombstoneKey(), llvm::AnonStructTypeKeyInfo::getTombstoneKey(), llvm::FunctionTypeKeyInfo::getTombstoneKey(), llvm::MDNodeInfo< NodeTy >::getTombstoneKey(), llvm::DenseMapInfo< CIEKey >::getTombstoneKey(), llvm::DenseMapInfo< VTableSlot >::getTombstoneKey(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::ValueHandleBase::isValid(), and markAliveBlocks().
isEqual()
static bool llvm::DenseMapInfo< CachedHashStringRef >::isEqual (const CachedHashStringRef & LHS, const CachedHashStringRef & RHS) inline static
Definition at line 62 of file CachedHashString.h.
Referenced by llvm::DenseMapInfo< AssertingVH< T > >::isEqual(), llvm::DenseMapInfo< BasicBlockEdge >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::isEqual(), and llvm::DenseMapInfo< FunctionSummary::ConstVCall >::isEqual().
The documentation for this struct was generated from the following file:
include/llvm/ADT/CachedHashString.h