LLVM: llvm::CFGViewPredecessors< InverseGraph > Struct Template Reference
llvm::CFGViewPredecessors< InverseGraph > Struct Template Reference
#include "llvm/IR/CFGDiff.h"
Classes
struct DeletedEdgesFilter
Public Types
using DataRef = const GraphDiff< BasicBlock *, InverseGraph > *
using NodeRef = std::pair< DataRef, BasicBlock * >
using ExistingChildIterator = WrappedPairNodeDataIterator< pred_iterator, NodeRef, DataRef >
using FilterExistingChildrenIterator = filter_iterator< ExistingChildIterator, DeletedEdgesFilter >
using vec_iterator = SmallVectorImpl< BasicBlock * >::const_iterator
using AddNewChildrenIterator = WrappedPairNodeDataIterator< vec_iterator, NodeRef, DataRef >
using ChildIteratorType = concat_iterator< NodeRef, FilterExistingChildrenIterator, AddNewChildrenIterator >
Static Public Member Functions
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<bool InverseGraph = false>
struct llvm::CFGViewPredecessors< InverseGraph >
Definition at line 212 of file CFGDiff.h.
Member Typedef Documentation
AddNewChildrenIterator
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::AddNewChildrenIterator = WrappedPairNodeDataIterator<vec_iterator, NodeRef, DataRef>
Definition at line 229 of file CFGDiff.h.
ChildIteratorType
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::ChildIteratorType = concat_iterator<NodeRef, FilterExistingChildrenIterator, AddNewChildrenIterator>
Definition at line 231 of file CFGDiff.h.
DataRef
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::DataRef = const GraphDiff<BasicBlock *, InverseGraph> *
Definition at line 213 of file CFGDiff.h.
ExistingChildIterator
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::ExistingChildIterator = WrappedPairNodeDataIterator<pred_iterator, NodeRef, DataRef>
Definition at line 216 of file CFGDiff.h.
FilterExistingChildrenIterator
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::FilterExistingChildrenIterator = filter_iterator<ExistingChildIterator, DeletedEdgesFilter>
Definition at line 225 of file CFGDiff.h.
NodeRef
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::NodeRef = std::pair<DataRef, BasicBlock *>
Definition at line 214 of file CFGDiff.h.
vec_iterator
template<bool InverseGraph = false> using llvm::CFGViewPredecessors< InverseGraph >::vec_iterator = SmallVectorImpl<BasicBlock *>::const_iterator
Definition at line 228 of file CFGDiff.h.
Member Function Documentation
child_begin()
template<bool InverseGraph = false> static ChildIteratorType llvm::CFGViewPredecessors< InverseGraph >::child_begin (NodeRef N) inline static
Definition at line 235 of file CFGDiff.h.
References N, llvm::pred_begin(), and llvm::pred_end().
child_end()
template<bool InverseGraph = false> static ChildIteratorType llvm::CFGViewPredecessors< InverseGraph >::child_end (NodeRef N) inline static
Definition at line 250 of file CFGDiff.h.
References N, and llvm::pred_end().
The documentation for this struct was generated from the following file:
include/llvm/IR/CFGDiff.h