LLVM: llvm::MDNodeKeyImpl< DIImportedEntity > Struct Reference
llvm::MDNodeKeyImpl< DIImportedEntity > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, Metadata *Scope, Metadata *Entity, Metadata *File, unsigned Line, MDString *Name)
MDNodeKeyImpl (const DIImportedEntity *N)
bool isKeyOf (const DIImportedEntity *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
Metadata * Scope
Metadata * Entity
Metadata * File
unsigned Line
MDString * Name
Detailed Description
Definition at line 1065 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIImportedEntity >::MDNodeKeyImpl (unsigned Tag, Metadata * Scope, Metadata * Entity, Metadata * File, unsigned Line, MDString * Name) inline
Definition at line 1073 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIImportedEntity >::MDNodeKeyImpl (const DIImportedEntity * N) inline
Definition at line 1077 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::getHashValue () const inline
Definition at line 1087 of file LLVMContextImpl.h.
References llvm::Tag.
isKeyOf()
bool llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf (const DIImportedEntity * RHS) const inline
Definition at line 1081 of file LLVMContextImpl.h.
References llvm::DIImportedEntity::getFile(), llvm::DIImportedEntity::getLine(), llvm::DIImportedEntity::getRawEntity(), llvm::DIImportedEntity::getRawName(), llvm::DIImportedEntity::getRawScope(), llvm::DINode::getTag(), and llvm::Tag.
Member Data Documentation
Entity
Metadata* llvm::MDNodeKeyImpl< DIImportedEntity >::Entity
Definition at line 1068 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIImportedEntity >::File
Definition at line 1069 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::Line
Definition at line 1070 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIImportedEntity >::Name
Definition at line 1071 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DIImportedEntity >::Scope
Definition at line 1067 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::Tag
Definition at line 1066 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h