LLVM: LoopDepthTree Struct Reference
LoopDepthTree Struct Reference
Collect all loops in function at the same nest level, starting at the outermost level.
Public Types
using LoopsOnLevelTy = SmallVector< LoopVector, 4 >
using iterator = LoopsOnLevelTy::iterator
using const_iterator = LoopsOnLevelTy::const_iterator
Public Member Functions
LoopDepthTree (LoopInfo &LI)
bool isRemovedLoop (const Loop *L) const
Test whether a given loop has been removed from the function, and thus is no longer valid.
void removeLoop (const Loop *L)
Record that a given loop has been removed from the function and is no longer valid.
void descend ()
Descend the tree to the next (inner) nesting level.
bool empty () const
size_t size () const
unsigned getDepth () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Detailed Description
Collect all loops in function at the same nest level, starting at the outermost level.
This data structure collects all loops at the same nest level for a given function (specified by the LoopInfo object). It starts at the outermost level.
Definition at line 332 of file LoopFuse.cpp.
Member Typedef Documentation
const_iterator
using LoopDepthTree::const_iterator = LoopsOnLevelTy::const_iterator
Definition at line 335 of file LoopFuse.cpp.
iterator
using LoopDepthTree::iterator = LoopsOnLevelTy::iterator
Definition at line 334 of file LoopFuse.cpp.
LoopsOnLevelTy
using LoopDepthTree::LoopsOnLevelTy = SmallVector<LoopVector, 4>
Definition at line 333 of file LoopFuse.cpp.
Constructor & Destructor Documentation
LoopDepthTree()
LoopDepthTree::LoopDepthTree (LoopInfo & LI) inline
Definition at line 337 of file LoopFuse.cpp.
Member Function Documentation
begin() [1/2]
iterator LoopDepthTree::begin () inline
Definition at line 368 of file LoopFuse.cpp.
begin() [2/2]
const_iterator LoopDepthTree::begin () const inline
Definition at line 370 of file LoopFuse.cpp.
descend()
void LoopDepthTree::descend () inline
Descend the tree to the next (inner) nesting level.
Definition at line 351 of file LoopFuse.cpp.
References isRemovedLoop().
empty()
bool LoopDepthTree::empty () const inline
Definition at line 364 of file LoopFuse.cpp.
References size().
Referenced by LoopFuser::fuseLoops().
end() [1/2]
iterator LoopDepthTree::end () inline
Definition at line 369 of file LoopFuse.cpp.
end() [2/2]
const_iterator LoopDepthTree::end () const inline
Definition at line 371 of file LoopFuse.cpp.
getDepth()
unsigned LoopDepthTree::getDepth () const inline
Definition at line 366 of file LoopFuse.cpp.
Referenced by LoopFuser::fuseLoops().
isRemovedLoop()
bool LoopDepthTree::isRemovedLoop (const Loop * L) const inline
Test whether a given loop has been removed from the function, and thus is no longer valid.
Definition at line 344 of file LoopFuse.cpp.
Referenced by descend().
removeLoop()
void LoopDepthTree::removeLoop (const Loop * L) inline
Record that a given loop has been removed from the function and is no longer valid.
Definition at line 348 of file LoopFuse.cpp.
size()
size_t LoopDepthTree::size () const inline
Definition at line 365 of file LoopFuse.cpp.
Referenced by empty(), and LoopFuser::fuseLoops().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopFuse.cpp