LLVM: llvm::DOTGraphTraits< BlockFrequencyInfo * > Struct Reference
llvm::DOTGraphTraits< BlockFrequencyInfo * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const BasicBlock *Node, const BlockFrequencyInfo *Graph)
std::string getNodeAttributes (const BasicBlock *Node, const BlockFrequencyInfo *Graph)
std::string getEdgeAttributes (const BasicBlock *Node, EdgeIter EI, const BlockFrequencyInfo *BFI)
Detailed Description
Definition at line 126 of file BlockFrequencyInfo.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< BlockFrequencyInfo * >::DOTGraphTraits (bool isSimple = false) inline explicit
Definition at line 127 of file BlockFrequencyInfo.cpp.
Member Function Documentation
getEdgeAttributes()
std::string llvm::DOTGraphTraits< BlockFrequencyInfo * >::getEdgeAttributes (const BasicBlock * Node, EdgeIter EI, const BlockFrequencyInfo * BFI) inline
Definition at line 142 of file BlockFrequencyInfo.cpp.
References ViewHotFreqPercent().
getNodeAttributes()
std::string llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeAttributes (const BasicBlock * Node, const BlockFrequencyInfo * Graph) inline
Definition at line 136 of file BlockFrequencyInfo.cpp.
References ViewHotFreqPercent().
getNodeLabel()
std::string llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeLabel (const BasicBlock * Node, const BlockFrequencyInfo * Graph) inline
Definition at line 130 of file BlockFrequencyInfo.cpp.
References llvm::getGVDT().
The documentation for this struct was generated from the following file:
lib/Analysis/BlockFrequencyInfo.cpp