LLVM: llvm::OperandTraits< MemoryUseOrDef > Struct Reference
llvm::OperandTraits< MemoryUseOrDef > Struct Reference
#include "llvm/Analysis/MemorySSA.h"
Static Public Member Functions
static Use * op_begin (MemoryUseOrDef *MUD)
static Use * op_end (MemoryUseOrDef *MUD)
static unsigned operands (const MemoryUseOrDef *MUD)
Detailed Description
Definition at line 428 of file MemorySSA.h.
Member Function Documentation
op_begin()
static Use * llvm::OperandTraits< MemoryUseOrDef >::op_begin (MemoryUseOrDef * MUD) inline static
Definition at line 429 of file MemorySSA.h.
References llvm::SCEVNAryExpr::op_begin().
op_end()
static Use * llvm::OperandTraits< MemoryUseOrDef >::op_end (MemoryUseOrDef * MUD) inline static
Definition at line 435 of file MemorySSA.h.
References llvm::SCEVNAryExpr::op_end().
operands()
static unsigned llvm::OperandTraits< MemoryUseOrDef >::operands (const MemoryUseOrDef * MUD) inline static
Definition at line 441 of file MemorySSA.h.
References llvm::SCEVNAryExpr::operands().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/MemorySSA.h