LLVM: llvm::AMDGPUPerfHintAnalysis Struct Reference
llvm::AMDGPUPerfHintAnalysis Struct Reference
#include "Target/AMDGPU/AMDGPUPerfHintAnalysis.h"
Classes
struct FuncInfo
Public Types
typedef ValueMap< const Function *, FuncInfo > FuncInfoMap
Public Member Functions
AMDGPUPerfHintAnalysis ()
bool runOnSCC (CallGraphSCC &SCC) override
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - For this class, we declare that we require and preserve the call graph.
bool isMemoryBound (const Function *F) const
bool needsWaveLimiter (const Function *F) const
Public Member Functions inherited from llvm::CallGraphSCCPass
CallGraphSCCPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a pass that prints the Module corresponding to a CallGraph.
virtual bool doInitialization (CallGraph &CG)
doInitialization - This method is called before the SCC's of the program has been processed, allowing the pass to do initialization as necessary.
virtual bool runOnSCC (CallGraphSCC &SCC)=0
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC.
virtual bool doFinalization (CallGraph &CG)
doFinalization - This method is called after the SCC's of the program has been processed, allowing the pass to do final cleanup as necessary.
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manager this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
void getAnalysisUsage (AnalysisUsage &Info) const override
getAnalysisUsage - For this class, we declare that we require and preserve the call graph.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::CallGraphSCCPass
bool skipSCC (CallGraphSCC &SCC) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 24 of file AMDGPUPerfHintAnalysis.h.
Member Typedef Documentation
FuncInfoMap
typedef ValueMap<const Function*, FuncInfo> llvm::AMDGPUPerfHintAnalysis::FuncInfoMap
Definition at line 49 of file AMDGPUPerfHintAnalysis.h.
Constructor & Destructor Documentation
AMDGPUPerfHintAnalysis()
llvm::AMDGPUPerfHintAnalysis::AMDGPUPerfHintAnalysis () inline
Definition at line 28 of file AMDGPUPerfHintAnalysis.h.
Member Function Documentation
getAnalysisUsage()
void llvm::AMDGPUPerfHintAnalysis::getAnalysisUsage (AnalysisUsage & AU) const inline override virtual
getAnalysisUsage - For this class, we declare that we require and preserve the call graph.
For this class, we declare that we require and preserve the call graph.
If the derived class implements this method, it should always explicitly call the implementation here.
Reimplemented from llvm::CallGraphSCCPass.
Definition at line 32 of file AMDGPUPerfHintAnalysis.h.
References llvm::AnalysisUsage::setPreservesAll().
isMemoryBound()
bool AMDGPUPerfHintAnalysis::isMemoryBound (const Function * F) const
Definition at line 390 of file AMDGPUPerfHintAnalysis.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::end(), F, and llvm::ValueMap< KeyT, ValueT, Config >::find().
needsWaveLimiter()
bool AMDGPUPerfHintAnalysis::needsWaveLimiter (const Function * F) const
Definition at line 398 of file AMDGPUPerfHintAnalysis.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::end(), F, and llvm::ValueMap< KeyT, ValueT, Config >::find().
runOnSCC()
bool AMDGPUPerfHintAnalysis::runOnSCC (CallGraphSCC & SCC) override virtual
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC.
Note that non-recursive (or only self-recursive) functions will have an SCC size of 1, where recursive portions of the call graph will have SCC size > 1.
SCC passes that add or delete functions to the SCC are required to update the SCC list, otherwise stale pointers may be dereferenced.
Implements llvm::CallGraphSCCPass.
Definition at line 367 of file AMDGPUPerfHintAnalysis.cpp.
References F, and I.
Member Data Documentation
ID
char llvm::AMDGPUPerfHintAnalysis::ID = 0 static
Definition at line 25 of file AMDGPUPerfHintAnalysis.h.
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPUPerfHintAnalysis.h
lib/Target/AMDGPU/AMDGPUPerfHintAnalysis.cpp