LLVM: llvm::DenseMapInfo< ArrayRef< T > > Struct Template Reference
llvm::DenseMapInfo< ArrayRef< T > > Struct Template Reference
#include "llvm/ADT/DenseMapInfo.h"
Static Public Member Functions
static ArrayRef< T > getEmptyKey ()
static ArrayRef< T > getTombstoneKey ()
static unsigned getHashValue (ArrayRef< T > Val)
static bool isEqual (ArrayRef< T > LHS, ArrayRef< T > RHS)
Detailed Description
template<typename T>
struct llvm::DenseMapInfo< ArrayRef< T > >
Definition at line 238 of file DenseMapInfo.h.
Member Function Documentation
getEmptyKey()
template<typename T > static ArrayRef< T > llvm::DenseMapInfo< ArrayRef< T > >::getEmptyKey () inline static
Definition at line 239 of file DenseMapInfo.h.
getHashValue()
template<typename T > static unsigned llvm::DenseMapInfo< ArrayRef< T > >::getHashValue (ArrayRef< T > Val) inline static
Definition at line 249 of file DenseMapInfo.h.
References assert(), llvm::ArrayRef< T >::data(), and llvm::hash_value().
getTombstoneKey()
template<typename T > static ArrayRef< T > llvm::DenseMapInfo< ArrayRef< T > >::getTombstoneKey () inline static
Definition at line 244 of file DenseMapInfo.h.
isEqual()
template<typename T > static bool llvm::DenseMapInfo< ArrayRef< T > >::isEqual (ArrayRef< T > LHS, ArrayRef< T > RHS) inline static
Definition at line 256 of file DenseMapInfo.h.
References llvm::ArrayRef< T >::data().
The documentation for this struct was generated from the following file:
include/llvm/ADT/DenseMapInfo.h