LLVM: llvm::HungoffOperandTraits< MINARITY > Struct Template Reference
llvm::HungoffOperandTraits< MINARITY > Struct Template Reference
HungoffOperandTraits - determine the allocation regime of the Use array when it is not a prefix to the User object, but allocated at an unrelated heap address.
#include "llvm/IR/OperandTraits.h"
Static Public Member Functions
static Use * op_begin (User *U)
static Use * op_end (User *U)
static unsigned operands (const User *U)
Detailed Description
template<unsigned MINARITY = 1>
struct llvm::HungoffOperandTraits< MINARITY >
HungoffOperandTraits - determine the allocation regime of the Use array when it is not a prefix to the User object, but allocated at an unrelated heap address.
This is the traits class that is needed when the Use array must be resizable.
Definition at line 95 of file OperandTraits.h.
Member Function Documentation
op_begin()
template<unsigned MINARITY = 1> static Use * llvm::HungoffOperandTraits< MINARITY >::op_begin (User * U) inline static
Definition at line 96 of file OperandTraits.h.
References llvm::User::getOperandList().
op_end()
template<unsigned MINARITY = 1> static Use * llvm::HungoffOperandTraits< MINARITY >::op_end (User * U) inline static
Definition at line 99 of file OperandTraits.h.
References llvm::User::getNumOperands(), and llvm::User::getOperandList().
operands()
template<unsigned MINARITY = 1> static unsigned llvm::HungoffOperandTraits< MINARITY >::operands (const User * U) inline static
Definition at line 102 of file OperandTraits.h.
References llvm::User::getNumOperands().
The documentation for this struct was generated from the following file:
include/llvm/IR/OperandTraits.h