LLVM: llvm::IntelExpr Struct Reference
llvm::IntelExpr Struct Reference
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
Public Member Functions
IntelExpr (bool needBracs=false)
IntelExpr (int64_t imm, bool needBracs)
IntelExpr (StringRef reg, int64_t imm=0, unsigned scale=0, bool needBracs=true)
IntelExpr (StringRef baseReg, StringRef indexReg, unsigned scale=0, int64_t imm=0, bool needBracs=true)
bool hasBaseReg () const
bool hasIndexReg () const
bool hasRegs () const
bool isValid () const
Public Attributes
bool NeedBracs
int64_t Imm
StringRef BaseReg
StringRef IndexReg
unsigned Scale
Detailed Description
Definition at line 62 of file MCTargetAsmParser.h.
Constructor & Destructor Documentation
IntelExpr() [1/4]
llvm::IntelExpr::IntelExpr (bool needBracs = false) inline
Definition at line 69 of file MCTargetAsmParser.h.
IntelExpr() [2/4]
llvm::IntelExpr::IntelExpr (int64_t imm, bool needBracs) inline
Definition at line 73 of file MCTargetAsmParser.h.
References Imm.
IntelExpr() [3/4]
llvm::IntelExpr::IntelExpr (StringRef reg, int64_t imm = 0, unsigned scale = 0, bool needBracs = true) inline
Definition at line 78 of file MCTargetAsmParser.h.
References IndexReg, Scale, and scale().
IntelExpr() [4/4]
llvm::IntelExpr::IntelExpr (StringRef baseReg, StringRef indexReg, unsigned scale = 0, int64_t imm = 0, bool needBracs = true) inline
Definition at line 86 of file MCTargetAsmParser.h.
References BaseReg.
Member Function Documentation
hasBaseReg()
bool llvm::IntelExpr::hasBaseReg () const inline
Definition at line 91 of file MCTargetAsmParser.h.
References BaseReg, and llvm::StringRef::size().
Referenced by hasRegs().
hasIndexReg()
bool llvm::IntelExpr::hasIndexReg () const inline
Definition at line 94 of file MCTargetAsmParser.h.
References IndexReg, and llvm::StringRef::size().
Referenced by hasRegs(), and isValid().
hasRegs()
bool llvm::IntelExpr::hasRegs () const inline
Definition at line 97 of file MCTargetAsmParser.h.
References hasBaseReg(), and hasIndexReg().
isValid()
bool llvm::IntelExpr::isValid () const inline
Definition at line 100 of file MCTargetAsmParser.h.
References hasIndexReg(), and Scale.
Member Data Documentation
BaseReg
StringRef llvm::IntelExpr::BaseReg
Definition at line 65 of file MCTargetAsmParser.h.
Referenced by hasBaseReg(), and IntelExpr().
Imm
int64_t llvm::IntelExpr::Imm
Definition at line 64 of file MCTargetAsmParser.h.
Referenced by IntelExpr().
IndexReg
StringRef llvm::IntelExpr::IndexReg
Definition at line 66 of file MCTargetAsmParser.h.
Referenced by hasIndexReg(), and IntelExpr().
NeedBracs
bool llvm::IntelExpr::NeedBracs
Definition at line 63 of file MCTargetAsmParser.h.
Scale
unsigned llvm::IntelExpr::Scale
Definition at line 67 of file MCTargetAsmParser.h.
Referenced by IntelExpr(), and isValid().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCParser/MCTargetAsmParser.h