LLVM: llvm::DWARFDebugLoc::LocationList Struct Reference
llvm::DWARFDebugLoc::LocationList Struct Reference
A list of locations that contain one variable.
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
Public Member Functions
void dump (raw_ostream &OS, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo *MRI, DWARFUnit *U, uint64_t BaseAddress, unsigned Indent) const
Dump this list on OS.
Public Attributes
unsigned Offset
The beginning offset where this location list is stored in the debug_loc section.
SmallVector< Entry, 2 > Entries
All the locations in which the variable is stored.
Detailed Description
A list of locations that contain one variable.
Definition at line 36 of file DWARFDebugLoc.h.
Member Function Documentation
dump()
void DWARFDebugLoc::LocationList::dump (raw_ostream & OS, bool IsLittleEndian, unsigned AddressSize, const MCRegisterInfo * MRI, DWARFUnit * U, uint64_t BaseAddress, unsigned Indent) const
Dump this list on OS.
Definition at line 39 of file DWARFDebugLoc.cpp.
References dumpExpression(), Entries, llvm::format(), and llvm::raw_ostream::indent().
Member Data Documentation
Entries
SmallVector<Entry, 2> llvm::DWARFDebugLoc::LocationList::Entries
All the locations in which the variable is stored.
Definition at line 41 of file DWARFDebugLoc.h.
Referenced by dump(), and llvm::DWARFDebugLoc::parseOneLocationList().
Offset
unsigned llvm::DWARFDebugLoc::LocationList::Offset
The beginning offset where this location list is stored in the debug_loc section.
Definition at line 39 of file DWARFDebugLoc.h.
Referenced by llvm::DWARFDebugLoc::getLocationListAtOffset(), and llvm::DWARFDebugLoc::parseOneLocationList().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
lib/DebugInfo/DWARF/DWARFDebugLoc.cpp