LLVM: AANonNullImpl Struct Reference
AANonNullImpl Struct Reference
---------------------— NonNull Argument Attribute ---------------------—
Public Member Functions
AANonNullImpl (Value &V, InformationCache &InfoCache)
AANonNullImpl (Value *AssociatedVal, Value &AnchoredValue, InformationCache &InfoCache)
AbstractState & getState () override
See AbstractAttribute::getState() {.
const AbstractState & getState () const override
const std::string getAsStr () const override
}
bool isAssumedNonNull () const override
See AANonNull::isAssumedNonNull().
bool isKnownNonNull () const override
See AANonNull::isKnownNonNull().
std::function< bool(Value &)> generatePredicate (Attributor &)
Generate a predicate that checks if a given value is assumed nonnull.
Detailed Description
---------------------— NonNull Argument Attribute ---------------------—
Definition at line 1000 of file Attributor.cpp.
Constructor & Destructor Documentation
AANonNullImpl() [1/2]
AANonNullImpl::AANonNullImpl (Value & V, InformationCache & InfoCache) inline
Definition at line 1002 of file Attributor.cpp.
AANonNullImpl() [2/2]
AANonNullImpl::AANonNullImpl (Value * AssociatedVal, Value & AnchoredValue, InformationCache & InfoCache) inline
Definition at line 1005 of file Attributor.cpp.
Member Function Documentation
generatePredicate()
std::function< bool(Value &)> AANonNullImpl::generatePredicate (Attributor & A)
Generate a predicate that checks if a given value is assumed nonnull.
The generated function returns true if a value satisfies any of following conditions. (i) A value is known nonZero(=nonnull). (ii) A value is associated with AANonNull and its isAssumedNonNull() is true.
Definition at line 1035 of file Attributor.cpp.
References getParent(), and isKnownNonZero().
Referenced by AANonNullReturned::updateImpl().
getAsStr()
const std::string AANonNullImpl::getAsStr () const inline override
}
See AbstractAttribute::getAsStr().
Definition at line 1016 of file Attributor.cpp.
getState() [1/2]
const AbstractState & AANonNullImpl::getState () const inline override
Definition at line 1012 of file Attributor.cpp.
getState() [2/2]
AbstractState & AANonNullImpl::getState () inline override
See AbstractAttribute::getState() {.
Definition at line 1011 of file Attributor.cpp.
isAssumedNonNull()
bool AANonNullImpl::isAssumedNonNull () const inline override
See AANonNull::isAssumedNonNull().
Definition at line 1021 of file Attributor.cpp.
isKnownNonNull()
bool AANonNullImpl::isKnownNonNull () const inline override
See AANonNull::isKnownNonNull().
Definition at line 1024 of file Attributor.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/Attributor.cpp