LLVM: llvm::MachineInstrExpressionTrait Struct Reference
llvm::MachineInstrExpressionTrait Struct Reference
Special DenseMapInfo traits to compare MachineInstr* by value of the instruction rather than by pointer value.
#include "llvm/CodeGen/MachineInstr.h"
Static Public Member Functions
static MachineInstr * getEmptyKey ()
static MachineInstr * getTombstoneKey ()
static unsigned getHashValue (const MachineInstr *const &MI)
static bool isEqual (const MachineInstr *const &LHS, const MachineInstr *const &RHS)
Detailed Description
Special DenseMapInfo traits to compare MachineInstr* by value of the instruction rather than by pointer value.
The hashing and equality testing functions ignore definitions so this is useful for CSE, etc.
Definition at line 1679 of file MachineInstr.h.
Member Function Documentation
getEmptyKey()
static MachineInstr * llvm::MachineInstrExpressionTrait::getEmptyKey () inline static
Definition at line 1680 of file MachineInstr.h.
Referenced by isEqual().
getHashValue()
unsigned MachineInstrExpressionTrait::getHashValue (const MachineInstr *const & MI) static
Definition at line 1974 of file MachineInstr.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineOperand::getReg(), llvm::hash_combine_range(), llvm::hash_value(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
getTombstoneKey()
static MachineInstr * llvm::MachineInstrExpressionTrait::getTombstoneKey () inline static
Definition at line 1684 of file MachineInstr.h.
Referenced by isEqual().
isEqual()
static bool llvm::MachineInstrExpressionTrait::isEqual (const MachineInstr *const & LHS, const MachineInstr *const & RHS) inline static
Definition at line 1690 of file MachineInstr.h.
References getEmptyKey(), getTombstoneKey(), llvm::MachineInstr::IgnoreVRegDefs, and llvm::MachineInstr::isIdenticalTo().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineInstr.h
lib/CodeGen/MachineInstr.cpp