LLVM: llvm::pdb::GSIHashStreamBuilder Struct Reference
llvm::pdb::GSIHashStreamBuilder Struct Reference
Classes
struct SymbolDenseMapInfo
Public Member Functions
uint32_t calculateSerializedLength () const
uint32_t calculateRecordByteSize () const
Error commit (BinaryStreamWriter &Writer)
void finalizeBuckets (uint32_t RecordZeroOffset)
template<typename T >
void addSymbol (const T &Symbol, MSFBuilder &Msf)
void addSymbol (const CVSymbol &Symbol)
Public Attributes
std::vector< CVSymbol > Records
uint32_t StreamIndex
llvm::DenseSet< CVSymbol, SymbolDenseMapInfo > SymbolHashes
std::vector< PSHashRecord > HashRecords
std::array< support::ulittle32_t,(IPHR_HASH+32)/32 > HashBitmap
std::vector< support::ulittle32_t > HashBuckets
Detailed Description
Definition at line 32 of file GSIStreamBuilder.cpp.
Member Function Documentation
addSymbol() [1/2]
void llvm::pdb::GSIHashStreamBuilder::addSymbol (const CVSymbol & Symbol) inline
Definition at line 68 of file GSIStreamBuilder.cpp.
References Records, and SymbolHashes.
addSymbol() [2/2]
template<typename T > void llvm::pdb::GSIHashStreamBuilder::addSymbol (const T & Symbol, MSFBuilder & Msf) inline
Definition at line 63 of file GSIStreamBuilder.cpp.
References addSymbol(), llvm::codeview::Copy, llvm::msf::MSFBuilder::getAllocator(), and llvm::codeview::SymbolSerializer::writeOneSymbol().
Referenced by addSymbol().
calculateRecordByteSize()
uint32_t GSIHashStreamBuilder::calculateRecordByteSize () const
Definition at line 87 of file GSIStreamBuilder.cpp.
References Records.
calculateSerializedLength()
uint32_t GSIHashStreamBuilder::calculateSerializedLength () const
Definition at line 79 of file GSIStreamBuilder.cpp.
References HashBitmap, HashBuckets, and HashRecords.
commit()
Error GSIHashStreamBuilder::commit (BinaryStreamWriter & Writer)
Definition at line 94 of file GSIStreamBuilder.cpp.
References llvm::codeview::EC, HashBitmap, HashBuckets, HashRecords, llvm::pdb::GSIHashHeader::HdrSignature, llvm::pdb::GSIHashHeader::HdrVersion, llvm::pdb::GSIHashHeader::HrSize, llvm::pdb::GSIHashHeader::NumBuckets, llvm::Error::success(), llvm::pdb::GSIHashHeader::VerHdr, llvm::pdb::GSIHashHeader::VerSignature, llvm::BinaryStreamWriter::writeArray(), and llvm::BinaryStreamWriter::writeObject().
finalizeBuckets()
void GSIHashStreamBuilder::finalizeBuckets (uint32_t RecordZeroOffset)
Definition at line 133 of file GSIStreamBuilder.cpp.
References llvm::pdb::PSHashRecord::CRef, llvm::codeview::getSymbolName(), gsiRecordLess(), HashBitmap, HashBuckets, HashRecords, llvm::pdb::hashStringV1(), llvm::pdb::IPHR_HASH, llvm::Left, llvm::pdb::PSHashRecord::Off, Records, and llvm::Right.
Member Data Documentation
HashBitmap
std::array<support::ulittle32_t, (IPHR_HASH + 32) / 32> llvm::pdb::GSIHashStreamBuilder::HashBitmap
Definition at line 55 of file GSIStreamBuilder.cpp.
Referenced by calculateSerializedLength(), commit(), and finalizeBuckets().
HashBuckets
std::vector<support::ulittle32_t> llvm::pdb::GSIHashStreamBuilder::HashBuckets
Definition at line 56 of file GSIStreamBuilder.cpp.
Referenced by calculateSerializedLength(), commit(), and finalizeBuckets().
HashRecords
std::vector<PSHashRecord> llvm::pdb::GSIHashStreamBuilder::HashRecords
Definition at line 54 of file GSIStreamBuilder.cpp.
Referenced by calculateSerializedLength(), commit(), and finalizeBuckets().
Records
std::vector<CVSymbol> llvm::pdb::GSIHashStreamBuilder::Records
Definition at line 51 of file GSIStreamBuilder.cpp.
Referenced by addSymbol(), calculateRecordByteSize(), and finalizeBuckets().
StreamIndex
uint32_t llvm::pdb::GSIHashStreamBuilder::StreamIndex
Definition at line 52 of file GSIStreamBuilder.cpp.
SymbolHashes
llvm::DenseSet<CVSymbol, SymbolDenseMapInfo> llvm::pdb::GSIHashStreamBuilder::SymbolHashes
Definition at line 53 of file GSIStreamBuilder.cpp.
Referenced by addSymbol().
The documentation for this struct was generated from the following file:
lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp