LLVM: llvm::RemarkSetupErrorInfo< ThisError > Struct Template Reference
llvm::RemarkSetupErrorInfo< ThisError > Struct Template Reference
#include "llvm/IR/RemarkStreamer.h"
Public Member Functions
RemarkSetupErrorInfo (Error E)
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfo< ThisError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Public Attributes
std::string Msg
std::error_code EC
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< ThisError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
template<typename ThisError>
struct llvm::RemarkSetupErrorInfo< ThisError >
Definition at line 57 of file RemarkStreamer.h.
Constructor & Destructor Documentation
RemarkSetupErrorInfo()
template<typename ThisError > llvm::RemarkSetupErrorInfo< ThisError >::RemarkSetupErrorInfo (Error E) inline
Definition at line 61 of file RemarkStreamer.h.
References llvm::ErrorInfoBase::convertToErrorCode(), llvm::RemarkSetupErrorInfo< ThisError >::EC, llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), and llvm::RemarkSetupErrorInfo< ThisError >::Msg.
Member Function Documentation
convertToErrorCode()
template<typename ThisError > std::error_code llvm::RemarkSetupErrorInfo< ThisError >::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 69 of file RemarkStreamer.h.
References llvm::RemarkSetupErrorInfo< ThisError >::EC.
log()
template<typename ThisError > void llvm::RemarkSetupErrorInfo< ThisError >::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 68 of file RemarkStreamer.h.
References llvm::RemarkSetupErrorInfo< ThisError >::Msg.
Member Data Documentation
EC
template<typename ThisError > std::error_code llvm::RemarkSetupErrorInfo< ThisError >::EC
Definition at line 59 of file RemarkStreamer.h.
Referenced by llvm::RemarkSetupErrorInfo< ThisError >::convertToErrorCode(), and llvm::RemarkSetupErrorInfo< ThisError >::RemarkSetupErrorInfo().
Msg
template<typename ThisError > std::string llvm::RemarkSetupErrorInfo< ThisError >::Msg
Definition at line 58 of file RemarkStreamer.h.
Referenced by llvm::RemarkSetupErrorInfo< ThisError >::log(), and llvm::RemarkSetupErrorInfo< ThisError >::RemarkSetupErrorInfo().
The documentation for this struct was generated from the following file:
include/llvm/IR/RemarkStreamer.h