LLVM: llvm::DivergencePropagator Struct Reference
llvm::DivergencePropagator Struct Reference
Public Types
using DefiningBlockMap = std::map< const BasicBlock *, const BasicBlock * >
Public Member Functions
DivergencePropagator (const FunctionRPOT &FuncRPOT, const DominatorTree &DT, const PostDominatorTree &PDT, const LoopInfo &LI)
void addPending (const BasicBlock &Block, const BasicBlock &DefBlock)
void printDefs (raw_ostream &Out)
void visitSuccessor (const BasicBlock &SuccBlock, const Loop *ParentLoop, const BasicBlock &DefBlock)
template<typename SuccessorIterable >
std::unique_ptr< ConstBlockSet > computeJoinPoints (const BasicBlock &RootBlock, SuccessorIterable NodeSuccessors, const Loop *ParentLoop, const BasicBlock *PdBoundBlock)
Public Attributes
const FunctionRPOT & FuncRPOT
const DominatorTree & DT
const PostDominatorTree & PDT
const LoopInfo & LI
std::unique_ptr< ConstBlockSet > JoinBlocks
SmallPtrSet< const BasicBlock *, 4 > ReachedLoopExits
DefiningBlockMap DefMap
std::unordered_set< const BasicBlock * > PendingUpdates
Detailed Description
Definition at line 130 of file SyncDependenceAnalysis.cpp.
Member Typedef Documentation
DefiningBlockMap
using llvm::DivergencePropagator::DefiningBlockMap = std::map<const BasicBlock *, const BasicBlock *>
Definition at line 146 of file SyncDependenceAnalysis.cpp.
Constructor & Destructor Documentation
DivergencePropagator()
llvm::DivergencePropagator::DivergencePropagator (const FunctionRPOT & FuncRPOT, const DominatorTree & DT, const PostDominatorTree & PDT, const LoopInfo & LI) inline
Definition at line 152 of file SyncDependenceAnalysis.cpp.
Member Function Documentation
addPending()
void llvm::DivergencePropagator::addPending (const BasicBlock & Block, const BasicBlock & DefBlock) inline
Definition at line 158 of file SyncDependenceAnalysis.cpp.
References DefMap, and PendingUpdates.
Referenced by visitSuccessor().
computeJoinPoints()
template<typename SuccessorIterable > std::unique_ptr< ConstBlockSet > llvm::DivergencePropagator::computeJoinPoints (const BasicBlock & RootBlock, SuccessorIterable NodeSuccessors, const Loop * ParentLoop, const BasicBlock * PdBoundBlock) inline
Definition at line 220 of file SyncDependenceAnalysis.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), DefMap, FuncRPOT, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), JoinBlocks, LI, LLVM_DEBUG, PendingUpdates, printDefs(), ReachedLoopExits, llvm::successors(), and visitSuccessor().
printDefs()
void llvm::DivergencePropagator::printDefs (raw_ostream & Out) inline
Definition at line 164 of file SyncDependenceAnalysis.cpp.
References DefMap, and FuncRPOT.
Referenced by computeJoinPoints().
visitSuccessor()
void llvm::DivergencePropagator::visitSuccessor (const BasicBlock & SuccBlock, const Loop * ParentLoop, const BasicBlock & DefBlock) inline
Definition at line 181 of file SyncDependenceAnalysis.cpp.
References addPending(), llvm::LoopBase< BlockT, LoopT >::contains(), DefMap, JoinBlocks, and ReachedLoopExits.
Referenced by computeJoinPoints().
Member Data Documentation
DefMap
DefiningBlockMap llvm::DivergencePropagator::DefMap
Definition at line 147 of file SyncDependenceAnalysis.cpp.
Referenced by addPending(), computeJoinPoints(), printDefs(), and visitSuccessor().
DT
const DominatorTree& llvm::DivergencePropagator::DT
Definition at line 132 of file SyncDependenceAnalysis.cpp.
FuncRPOT
const FunctionRPOT& llvm::DivergencePropagator::FuncRPOT
Definition at line 131 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints(), and printDefs().
JoinBlocks
std::unique_ptr<ConstBlockSet> llvm::DivergencePropagator::JoinBlocks
Definition at line 137 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints(), and visitSuccessor().
LI
const LoopInfo& llvm::DivergencePropagator::LI
Definition at line 134 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints().
PDT
const PostDominatorTree& llvm::DivergencePropagator::PDT
Definition at line 133 of file SyncDependenceAnalysis.cpp.
PendingUpdates
std::unordered_set<const BasicBlock *> llvm::DivergencePropagator::PendingUpdates
Definition at line 150 of file SyncDependenceAnalysis.cpp.
Referenced by addPending(), and computeJoinPoints().
ReachedLoopExits
SmallPtrSet<const BasicBlock *, 4> llvm::DivergencePropagator::ReachedLoopExits
Definition at line 140 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints(), and visitSuccessor().
The documentation for this struct was generated from the following file:
lib/Analysis/SyncDependenceAnalysis.cpp