LLVM: llvm::ms_demangle::FunctionSymbolNode Struct Reference
llvm::ms_demangle::FunctionSymbolNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
FunctionSymbolNode ()
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::SymbolNode
SymbolNode (NodeKind K)
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputStream &OS, OutputFlags Flags) const =0
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
FunctionSignatureNode * Signature = nullptr
Public Attributes inherited from llvm::ms_demangle::SymbolNode
QualifiedNameNode * Name = nullptr
Detailed Description
Definition at line 617 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
FunctionSymbolNode()
llvm::ms_demangle::FunctionSymbolNode::FunctionSymbolNode () inline
Definition at line 618 of file MicrosoftDemangleNodes.h.
Member Function Documentation
output()
void FunctionSymbolNode::output (OutputStream & OS, OutputFlags Flags) const override virtual
Reimplemented from llvm::ms_demangle::SymbolNode.
Definition at line 577 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::SymbolNode::Name, llvm::ms_demangle::QualifiedNameNode::output(), llvm::ms_demangle::FunctionSignatureNode::outputPost(), llvm::ms_demangle::FunctionSignatureNode::outputPre(), outputSpaceIfNecessary(), and Signature.
Member Data Documentation
Signature
FunctionSignatureNode* llvm::ms_demangle::FunctionSymbolNode::Signature = nullptr
Definition at line 622 of file MicrosoftDemangleNodes.h.
Referenced by output().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp