LLVM: llvm::GuardWideningPass Struct Reference
llvm::GuardWideningPass Struct Reference
#include "llvm/Transforms/Scalar/GuardWidening.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GuardWideningPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 27 of file GuardWidening.h.
Member Function Documentation
run() [1/2]
PreservedAnalyses GuardWideningPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 803 of file GuardWidening.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::PreservedAnalyses::preserveSet(), run(), and WidenFrequentBranches.
Referenced by run().
run() [2/2]
PreservedAnalyses GuardWideningPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 820 of file GuardWidening.cpp.
References llvm::PreservedAnalyses::all(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopStandardAnalysisResults::DT, F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::BasicBlock::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::LoopStandardAnalysisResults::LI, run(), and WidenFrequentBranches.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/GuardWidening.h
lib/Transforms/Scalar/GuardWidening.cpp