LLVM: lib/Transforms/IPO/SyntheticCountsPropagation.cpp File Reference
SyntheticCountsPropagation.cpp File Reference
#include "llvm/Transforms/IPO/SyntheticCountsPropagation.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/SyntheticCountsUtils.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "synthetic-counts-propagation"
Typedefs
using Scaled64 = ScaledNumber< uint64_t >
using ProfileCount = Function::ProfileCount
Functions
static void initializeCounts (Module &M, function_ref< void(Function *, uint64_t)> SetCount)
Variables
cl::opt< int > InitialSyntheticCount ("initial-synthetic-count", cl::Hidden, cl::init(10), cl::ZeroOrMore, cl::desc("Initial value of synthetic entry count."))
Initial synthetic count assigned to functions.
static cl::opt< int > InlineSyntheticCount ("inline-synthetic-count", cl::Hidden, cl::init(15), cl::ZeroOrMore, cl::desc("Initial synthetic entry count for inline functions."))
Initial synthetic count assigned to inline functions.
static cl::opt< int > ColdSyntheticCount ("cold-synthetic-count", cl::Hidden, cl::init(5), cl::ZeroOrMore, cl::desc("Initial synthetic entry count for cold functions."))
Initial synthetic count assigned to cold functions.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "synthetic-counts-propagation"
Definition at line 46 of file SyntheticCountsPropagation.cpp.
Typedef Documentation
ProfileCount
using ProfileCount = Function::ProfileCount
Definition at line 44 of file SyntheticCountsPropagation.cpp.
Scaled64
using Scaled64 = ScaledNumber<uint64_t>
Definition at line 43 of file SyntheticCountsPropagation.cpp.
Function Documentation
initializeCounts()
static void initializeCounts (Module & M, function_ref< void(Function *, uint64_t)> SetCount) static
Definition at line 66 of file SyntheticCountsPropagation.cpp.
References llvm::CallingConv::Cold, ColdSyntheticCount, F, InitialSyntheticCount, InlineSyntheticCount, and llvm::FunctionSummary::FFlags::NoInline.
Variable Documentation
ColdSyntheticCount
cl::opt< int > ColdSyntheticCount("cold-synthetic-count", cl::Hidden, cl::init(5), cl::ZeroOrMore, cl::desc("Initial synthetic entry count for cold functions.")) ("cold-synthetic-count" , cl::Hidden , cl::init(5) , cl::ZeroOrMore , cl::desc("Initial synthetic entry count for cold functions.")) static
Initial synthetic count assigned to cold functions.
Referenced by initializeCounts().
InitialSyntheticCount
cl::opt< int > InitialSyntheticCount("initial-synthetic-count", cl::Hidden, cl::init(10), cl::ZeroOrMore, cl::desc("Initial value of synthetic entry count.")) ("initial-synthetic-count" , cl::Hidden , cl::init(10) , cl::ZeroOrMore , cl::desc("Initial value of synthetic entry count."))
Initial synthetic count assigned to functions.
Referenced by initializeCounts().
InlineSyntheticCount
cl::opt< int > InlineSyntheticCount("inline-synthetic-count", cl::Hidden, cl::init(15), cl::ZeroOrMore, cl::desc("Initial synthetic entry count for inline functions.")) ("inline-synthetic-count" , cl::Hidden , cl::init(15) , cl::ZeroOrMore , cl::desc("Initial synthetic entry count for inline functions.")) static
Initial synthetic count assigned to inline functions.
Referenced by initializeCounts().