LLVM: lib/Target/SystemZ/SystemZTargetMachine.cpp File Reference
SystemZTargetMachine.cpp File Reference
#include "SystemZTargetMachine.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "SystemZ.h"
#include "SystemZMachineScheduler.h"
#include "SystemZTargetTransformInfo.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Transforms/Scalar.h"
#include <string>
Functions
void LLVMInitializeSystemZTarget ()
static bool UsesVectorABI (StringRef CPU, StringRef FS)
static std::string computeDataLayout (const Triple &TT, StringRef CPU, StringRef FS)
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveSystemZCodeModel (Optional< CodeModel::Model > CM, Reloc::Model RM, bool JIT)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 59 of file SystemZTargetMachine.cpp.
References llvm::DataLayout::getManglingComponent(), TT, and UsesVectorABI().
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 94 of file SystemZTargetMachine.cpp.
References llvm::Reloc::DynamicNoPIC, and llvm::Reloc::Static.
getEffectiveSystemZCodeModel()
static CodeModel::Model getEffectiveSystemZCodeModel (Optional< CodeModel::Model > CM, Reloc::Model RM, bool JIT) static
Definition at line 132 of file SystemZTargetMachine.cpp.
References llvm::CodeModel::Kernel, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
LLVMInitializeSystemZTarget()
void LLVMInitializeSystemZTarget ()
Definition at line 32 of file SystemZTargetMachine.cpp.
References llvm::getTheSystemZTarget(), and X.
UsesVectorABI()
static bool UsesVectorABI (StringRef CPU, StringRef FS) static
Definition at line 38 of file SystemZTargetMachine.cpp.
References llvm::StringRef::empty(), and llvm::StringRef::split().
Referenced by computeDataLayout().