LLVM: lib/CodeGen/TargetPassConfig.cpp File Reference
TargetPassConfig.cpp File Reference
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CFLAndersAliasAnalysis.h"
#include "llvm/Analysis/CFLSteensAliasAnalysis.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/CodeGen/CSEConfigBase.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachinePassRegistry.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Pass.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/SymbolRewriter.h"
#include <cassert>
#include <string>
Classes
struct INITIALIZE_PASS::InsertedPass
class llvm::PassConfigImpl
Namespaces
namespace INITIALIZE_PASS
TargetPassConfig.
namespace llvm
This class represents lattice values for constants.
Enumerations
enum RunOutliner { AlwaysOutline , NeverOutline , TargetDefault }
enum class CFLAAType {
None , Steensgaard , Andersen , Both ,
None , Steensgaard , Andersen , Both
}
Functions
static IdentifyingPassPtr applyDisable (IdentifyingPassPtr PassID, bool Override)
Allow standard passes to be disabled by command line options.
static IdentifyingPassPtr overridePass (AnalysisID StandardID, IdentifyingPassPtr TargetID)
Allow standard passes to be disabled by the command line, regardless of who is adding the pass.
static const PassInfo * getPassInfo (StringRef PassName)
static AnalysisID getPassIDFromName (StringRef PassName)
static std::pair< StringRef, unsigned > getPassNameAndInstanceNum (StringRef PassName)
static FunctionPass * useDefaultRegisterAllocator ()
-regalloc=... command line option.
static void initializeDefaultRegisterAllocatorOnce ()
Variables
cl::opt< bool > EnableIPRA ("enable-ipra", cl::init(false), cl::Hidden, cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls."))
static cl::opt< bool > DisablePostRASched ("disable-post-ra", cl::Hidden, cl::desc("Disable Post Regalloc Scheduler"))
static cl::opt< bool > DisableBranchFold ("disable-branch-fold", cl::Hidden, cl::desc("Disable branch folding"))
static cl::opt< bool > DisableTailDuplicate ("disable-tail-duplicate", cl::Hidden, cl::desc("Disable tail duplication"))
static cl::opt< bool > DisableEarlyTailDup ("disable-early-taildup", cl::Hidden, cl::desc("Disable pre-register allocation tail duplication"))
static cl::opt< bool > DisableBlockPlacement ("disable-block-placement", cl::Hidden, cl::desc("Disable probability-driven block placement"))
static cl::opt< bool > EnableBlockPlacementStats ("enable-block-placement-stats", cl::Hidden, cl::desc("Collect probability-driven block placement stats"))
static cl::opt< bool > DisableSSC ("disable-ssc", cl::Hidden, cl::desc("Disable Stack Slot Coloring"))
static cl::opt< bool > DisableMachineDCE ("disable-machine-dce", cl::Hidden, cl::desc("Disable Machine Dead Code Elimination"))
static cl::opt< bool > DisableEarlyIfConversion ("disable-early-ifcvt", cl::Hidden, cl::desc("Disable Early If-conversion"))
static cl::opt< bool > DisableMachineLICM ("disable-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM"))
static cl::opt< bool > DisableMachineCSE ("disable-machine-cse", cl::Hidden, cl::desc("Disable Machine Common Subexpression Elimination"))
static cl::opt< cl::boolOrDefault > OptimizeRegAlloc ("optimize-regalloc", cl::Hidden, cl::desc("Enable optimized register allocation compilation path."))
static cl::opt< bool > DisablePostRAMachineLICM ("disable-postra-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM"))
static cl::opt< bool > DisableMachineSink ("disable-machine-sink", cl::Hidden, cl::desc("Disable Machine Sinking"))
static cl::opt< bool > DisablePostRAMachineSink ("disable-postra-machine-sink", cl::Hidden, cl::desc("Disable PostRA Machine Sinking"))
static cl::opt< bool > DisableLSR ("disable-lsr", cl::Hidden, cl::desc("Disable Loop Strength Reduction Pass"))
static cl::opt< bool > DisableConstantHoisting ("disable-constant-hoisting", cl::Hidden, cl::desc("Disable ConstantHoisting"))
static cl::opt< bool > DisableCGP ("disable-cgp", cl::Hidden, cl::desc("Disable Codegen Prepare"))
static cl::opt< bool > DisableCopyProp ("disable-copyprop", cl::Hidden, cl::desc("Disable Copy Propagation pass"))
static cl::opt< bool > DisablePartialLibcallInlining ("disable-partial-libcall-inlining", cl::Hidden, cl::desc("Disable Partial Libcall Inlining"))
static cl::opt< bool > EnableImplicitNullChecks ("enable-implicit-null-checks", cl::desc("Fold null checks into faulting memory operations"), cl::init(false), cl::Hidden)
static cl::opt< bool > DisableMergeICmps ("disable-mergeicmps", cl::desc("Disable MergeICmps Pass"), cl::init(false), cl::Hidden)
static cl::opt< bool > PrintLSR ("print-lsr-output", cl::Hidden, cl::desc("Print LLVM IR produced by the loop-reduce pass"))
static cl::opt< bool > PrintISelInput ("print-isel-input", cl::Hidden, cl::desc("Print LLVM IR input to isel pass"))
static cl::opt< bool > PrintGCInfo ("print-gc", cl::Hidden, cl::desc("Dump garbage collector data"))
static cl::opt< cl::boolOrDefault > VerifyMachineCode ("verify-machineinstrs", cl::Hidden, cl::desc("Verify generated machine code"), cl::ZeroOrMore)
static cl::opt< RunOutliner > EnableMachineOutliner ("enable-machine-outliner", cl::desc("Enable the machine outliner"), cl::Hidden, cl::ValueOptional, cl::init(TargetDefault), cl::values(clEnumValN(AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(NeverOutline, "never", "Disable all outlining"), clEnumValN(AlwaysOutline, "", "")))
static cl::opt< cl::boolOrDefault > EnableFastISelOption ("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector"))
static cl::opt< cl::boolOrDefault > EnableGlobalISelOption ("global-isel", cl::Hidden, cl::desc("Enable the \"global\" instruction selector"))
static cl::opt< std::string > PrintMachineInstrs ("print-machineinstrs", cl::ValueOptional, cl::desc("Print machine instrs"), cl::value_desc("pass-name"), cl::init("option-unspecified"), cl::Hidden)
static cl::opt< GlobalISelAbortMode > EnableGlobalISelAbort ("global-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction"), cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure")))
cl::opt< bool > MISchedPostRA ("misched-postra", cl::Hidden, cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)"))
static cl::opt< bool > EarlyLiveIntervals ("early-live-intervals", cl::Hidden, cl::desc("Run live interval analysis earlier in the pipeline"))
static cl::opt< CFLAAType > UseCFLAA ("use-cfl-aa-in-codegen", cl::init(CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis in CodeGen"), cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA")))
const char * StartAfterOptName = "start-after"
Option names for limiting the codegen pipeline.
const char * StartBeforeOptName = "start-before"
const char * StopAfterOptName = "stop-after"
const char * StopBeforeOptName = "stop-before"
static cl::opt< std::string > StartAfterOpt (StringRef(StartAfterOptName), cl::desc("Resume compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StartBeforeOpt (StringRef(StartBeforeOptName), cl::desc("Resume compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StopAfterOpt (StringRef(StopAfterOptName), cl::desc("Stop compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StopBeforeOpt (StringRef(StopBeforeOptName), cl::desc("Stop compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< RegisterRegAlloc::FunctionPassCtor, false, RegisterPassParser< RegisterRegAlloc > > RegAlloc ("regalloc", cl::Hidden, cl::init(&useDefaultRegisterAllocator), cl::desc("Register allocator to use"))
static llvm::once_flag InitializeDefaultRegisterAllocatorFlag
A dummy default pass factory indicates whether the register allocator is overridden on the command line.
static RegisterRegAlloc defaultRegAlloc ("default", "pick register allocator based on -O option", useDefaultRegisterAllocator)
Enumeration Type Documentation
CFLAAType
enum class CFLAAType strong
Enumerator
None
Steensgaard
Andersen
Both
None
Steensgaard
Andersen
Both
Definition at line 163 of file TargetPassConfig.cpp.
RunOutliner
enum RunOutliner
Enumerator
AlwaysOutline
NeverOutline
TargetDefault
Definition at line 115 of file TargetPassConfig.cpp.
Function Documentation
applyDisable()
static IdentifyingPassPtr applyDisable (IdentifyingPassPtr PassID, bool Override) static
Allow standard passes to be disabled by command line options.
This supports simple binary flags that either suppress the pass or do nothing. i.e. -disable-mypass=false has no effect. These should be converted to boolOrDefault in order to use applyOverride.
Definition at line 207 of file TargetPassConfig.cpp.
Referenced by overridePass().
getPassIDFromName()
static AnalysisID getPassIDFromName (StringRef PassName) static
Definition at line 343 of file TargetPassConfig.cpp.
References getPassInfo(), and llvm::PassInfo::getTypeInfo().
getPassInfo()
static const PassInfo * getPassInfo (StringRef PassName) static
Definition at line 331 of file TargetPassConfig.cpp.
References llvm::StringRef::empty(), llvm::PassRegistry::getPassInfo(), llvm::PassRegistry::getPassRegistry(), and llvm::report_fatal_error().
Referenced by llvm::TargetPassConfig::addMachinePasses(), llvm::PMTopLevelManager::findAnalysisPassInfo(), and getPassIDFromName().
getPassNameAndInstanceNum()
static std::pair< StringRef, unsigned > getPassNameAndInstanceNum (StringRef PassName) static
Definition at line 349 of file TargetPassConfig.cpp.
References llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), Name, llvm::report_fatal_error(), and llvm::StringRef::split().
initializeDefaultRegisterAllocatorOnce()
static void initializeDefaultRegisterAllocatorOnce () static
Definition at line 1048 of file TargetPassConfig.cpp.
References llvm::MachinePassRegistry< PassCtorTy >::getDefault(), RegAlloc, and llvm::cl::Option::setDefault().
Referenced by llvm::TargetPassConfig::createRegAllocPass().
overridePass()
static IdentifyingPassPtr overridePass (AnalysisID StandardID, IdentifyingPassPtr TargetID) static
Allow standard passes to be disabled by the command line, regardless of who is adding the pass.
StandardID is the pass identified in the standard pass pipeline and provided to addPass(). It may be a target-specific ID in the case that the target directly adds its own pass, but in that case we harmlessly fall through.
TargetID is the pass that the target has configured to override StandardID.
StandardID may be a pseudo ID. In that case TargetID is the name of the real pass to run. This allows multiple options to control a single pass depending on where in the pipeline that pass is added.
Definition at line 226 of file TargetPassConfig.cpp.
References applyDisable(), llvm::BranchFolderPassID, llvm::DeadMachineInstructionElimID, DisableBlockPlacement, DisableBranchFold, DisableCopyProp, DisableEarlyIfConversion, DisableEarlyTailDup, DisableMachineCSE, DisableMachineDCE, DisableMachineLICM, DisableMachineSink, DisablePostRAMachineLICM, DisablePostRAMachineSink, DisablePostRASched, DisableSSC, DisableTailDuplicate, llvm::EarlyIfConverterID, llvm::EarlyMachineLICMID, llvm::EarlyTailDuplicateID, llvm::MachineBlockPlacementID, llvm::MachineCopyPropagationID, llvm::MachineCSEID, llvm::MachineLICMID, llvm::MachineSinkingID, llvm::PostRAMachineSinkingID, llvm::PostRASchedulerID, llvm::StackSlotColoringID, and llvm::TailDuplicateID.
Referenced by llvm::TargetPassConfig::addPass(), and llvm::TargetPassConfig::isPassSubstitutedOrOverridden().
useDefaultRegisterAllocator()
static FunctionPass * useDefaultRegisterAllocator () static
-regalloc=... command line option.
Definition at line 843 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::addRegAssignmentFast(), and llvm::TargetPassConfig::createRegAllocPass().
Variable Documentation
defaultRegAlloc
RegisterRegAlloc defaultRegAlloc("default", "pick register allocator based on -O option", useDefaultRegisterAllocator) ("default" , "pick register allocator based on -O option" , useDefaultRegisterAllocator) static
DisableBlockPlacement
cl::opt< bool > DisableBlockPlacement("disable-block-placement", cl::Hidden, cl::desc("Disable probability-driven block placement")) ("disable-block-placement" , cl::Hidden , cl::desc("Disable probability-driven block placement")) static
Referenced by overridePass().
DisableBranchFold
cl::opt< bool > DisableBranchFold("disable-branch-fold", cl::Hidden, cl::desc("Disable branch folding")) ("disable-branch-fold" , cl::Hidden , cl::desc("Disable branch folding")) static
Referenced by overridePass().
DisableCGP
cl::opt< bool > DisableCGP("disable-cgp", cl::Hidden, cl::desc("Disable Codegen Prepare")) ("disable-cgp" , cl::Hidden , cl::desc("Disable Codegen Prepare")) static
Referenced by llvm::TargetPassConfig::addCodeGenPrepare().
DisableConstantHoisting
cl::opt< bool > DisableConstantHoisting("disable-constant-hoisting", cl::Hidden, cl::desc("Disable ConstantHoisting")) ("disable-constant-hoisting" , cl::Hidden , cl::desc("Disable ConstantHoisting")) static
Referenced by llvm::TargetPassConfig::addIRPasses().
DisableCopyProp
cl::opt< bool > DisableCopyProp("disable-copyprop", cl::Hidden, cl::desc("Disable Copy Propagation pass")) ("disable-copyprop" , cl::Hidden , cl::desc("Disable Copy Propagation pass")) static
Referenced by overridePass().
DisableEarlyIfConversion
cl::opt< bool > DisableEarlyIfConversion("disable-early-ifcvt", cl::Hidden, cl::desc("Disable Early If-conversion")) ("disable-early-ifcvt" , cl::Hidden , cl::desc("Disable Early If-conversion")) static
Referenced by overridePass().
DisableEarlyTailDup
cl::opt< bool > DisableEarlyTailDup("disable-early-taildup", cl::Hidden, cl::desc("Disable pre-register allocation tail duplication")) ("disable-early-taildup" , cl::Hidden , cl::desc("Disable pre-register allocation tail duplication")) static
Referenced by overridePass().
DisableLSR
cl::opt< bool > DisableLSR("disable-lsr", cl::Hidden, cl::desc("Disable Loop Strength Reduction Pass")) ("disable-lsr" , cl::Hidden , cl::desc("Disable Loop Strength Reduction Pass")) static
Referenced by llvm::TargetPassConfig::addIRPasses().
DisableMachineCSE
cl::opt< bool > DisableMachineCSE("disable-machine-cse", cl::Hidden, cl::desc("Disable Machine Common Subexpression Elimination")) ("disable-machine-cse" , cl::Hidden , cl::desc("Disable Machine Common Subexpression Elimination")) static
Referenced by overridePass().
DisableMachineDCE
cl::opt< bool > DisableMachineDCE("disable-machine-dce", cl::Hidden, cl::desc("Disable Machine Dead Code Elimination")) ("disable-machine-dce" , cl::Hidden , cl::desc("Disable Machine Dead Code Elimination")) static
Referenced by overridePass().
DisableMachineLICM
cl::opt< bool > DisableMachineLICM("disable-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM")) ("disable-machine-licm" , cl::Hidden , cl::desc("Disable Machine LICM")) static
Referenced by overridePass().
DisableMachineSink
cl::opt< bool > DisableMachineSink("disable-machine-sink", cl::Hidden, cl::desc("Disable Machine Sinking")) ("disable-machine-sink" , cl::Hidden , cl::desc("Disable Machine Sinking")) static
Referenced by overridePass().
DisableMergeICmps
cl::opt< bool > DisableMergeICmps("disable-mergeicmps", cl::desc("Disable MergeICmps Pass"), cl::init(false), cl::Hidden) ("disable-mergeicmps" , cl::desc("Disable MergeICmps Pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetPassConfig::addIRPasses().
DisablePartialLibcallInlining
cl::opt< bool > DisablePartialLibcallInlining("disable-partial-libcall-inlining", cl::Hidden, cl::desc("Disable Partial Libcall Inlining")) ("disable-partial-libcall-inlining" , cl::Hidden , cl::desc("Disable Partial Libcall Inlining")) static
Referenced by llvm::TargetPassConfig::addIRPasses().
DisablePostRAMachineLICM
cl::opt< bool > DisablePostRAMachineLICM("disable-postra-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM")) ("disable-postra-machine-licm" , cl::Hidden , cl::desc("Disable Machine LICM")) static
Referenced by overridePass().
DisablePostRAMachineSink
cl::opt< bool > DisablePostRAMachineSink("disable-postra-machine-sink", cl::Hidden, cl::desc("Disable PostRA Machine Sinking")) ("disable-postra-machine-sink" , cl::Hidden , cl::desc("Disable PostRA Machine Sinking")) static
Referenced by overridePass().
DisablePostRASched
cl::opt< bool > DisablePostRASched("disable-post-ra", cl::Hidden, cl::desc("Disable Post Regalloc Scheduler")) ("disable-post-ra" , cl::Hidden , cl::desc("Disable Post Regalloc Scheduler")) static
Referenced by overridePass().
DisableSSC
cl::opt< bool > DisableSSC("disable-ssc", cl::Hidden, cl::desc("Disable Stack Slot Coloring")) ("disable-ssc" , cl::Hidden , cl::desc("Disable Stack Slot Coloring")) static
Referenced by overridePass().
DisableTailDuplicate
cl::opt< bool > DisableTailDuplicate("disable-tail-duplicate", cl::Hidden, cl::desc("Disable tail duplication")) ("disable-tail-duplicate" , cl::Hidden , cl::desc("Disable tail duplication")) static
Referenced by overridePass().
EarlyLiveIntervals
cl::opt< bool > EarlyLiveIntervals("early-live-intervals", cl::Hidden, cl::desc("Run live interval analysis earlier in the pipeline")) ("early-live-intervals" , cl::Hidden , cl::desc("Run live interval analysis earlier in the pipeline")) static
Referenced by llvm::TargetPassConfig::addOptimizedRegAlloc().
EnableBlockPlacementStats
cl::opt< bool > EnableBlockPlacementStats("enable-block-placement-stats", cl::Hidden, cl::desc("Collect probability-driven block placement stats")) ("enable-block-placement-stats" , cl::Hidden , cl::desc("Collect probability-driven block placement stats")) static
Referenced by llvm::TargetPassConfig::addBlockPlacement().
EnableFastISelOption
cl::opt< cl::boolOrDefault > EnableFastISelOption("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector")) ("fast-isel" , cl::Hidden , cl::desc("Enable the \"fast\" instruction selector")) static
Referenced by llvm::TargetPassConfig::addCoreISelPasses().
EnableGlobalISelAbort
cl::opt< GlobalISelAbortMode > EnableGlobalISelAbort("global-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction"), cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure"))) ("global-isel-abort" , cl::Hidden , cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction") , cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure"))) static
Referenced by llvm::TargetPassConfig::TargetPassConfig().
EnableGlobalISelOption
cl::opt< cl::boolOrDefault > EnableGlobalISelOption("global-isel", cl::Hidden, cl::desc("Enable the \"global\" instruction selector")) ("global-isel" , cl::Hidden , cl::desc("Enable the \"global\" instruction selector")) static
Referenced by llvm::TargetPassConfig::addCoreISelPasses().
EnableImplicitNullChecks
cl::opt< bool > EnableImplicitNullChecks("enable-implicit-null-checks", cl::desc("Fold null checks into faulting memory operations"), cl::init(false), cl::Hidden) ("enable-implicit-null-checks" , cl::desc("Fold null checks into faulting memory operations") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
EnableIPRA
cl::opt< bool > EnableIPRA("enable-ipra", cl::init(false), cl::Hidden, cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls.")) ("enable-ipra" , cl::init(false) , cl::Hidden , cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls."))
Referenced by llvm::TargetPassConfig::TargetPassConfig().
EnableMachineOutliner
cl::opt< RunOutliner > EnableMachineOutliner("enable-machine-outliner", cl::desc("Enable the machine outliner"), cl::Hidden, cl::ValueOptional, cl::init(TargetDefault), cl::values(clEnumValN(AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(NeverOutline, "never", "Disable all outlining"), clEnumValN(AlwaysOutline, "", ""))) ("enable-machine-outliner" , cl::desc("Enable the machine outliner") , cl::Hidden , cl::ValueOptional , cl::init(TargetDefault) , cl::values(clEnumValN(AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(NeverOutline, "never", "Disable all outlining"), clEnumValN(AlwaysOutline, "", ""))) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
InitializeDefaultRegisterAllocatorFlag
llvm::once_flag InitializeDefaultRegisterAllocatorFlag static
A dummy default pass factory indicates whether the register allocator is overridden on the command line.
Definition at line 1041 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::createRegAllocPass().
MISchedPostRA
cl::opt< bool > MISchedPostRA("misched-postra", cl::Hidden, cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)")) ("misched-postra" , cl::Hidden , cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)"))
Referenced by llvm::TargetPassConfig::addMachinePasses().
OptimizeRegAlloc
cl::opt< cl::boolOrDefault > OptimizeRegAlloc("optimize-regalloc", cl::Hidden, cl::desc("Enable optimized register allocation compilation path.")) ("optimize-regalloc" , cl::Hidden , cl::desc("Enable optimized register allocation compilation path.")) static
Referenced by llvm::TargetPassConfig::getOptimizeRegAlloc().
PrintGCInfo
cl::opt< bool > PrintGCInfo("print-gc", cl::Hidden, cl::desc("Dump garbage collector data")) ("print-gc" , cl::Hidden , cl::desc("Dump garbage collector data")) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
PrintISelInput
cl::opt< bool > PrintISelInput("print-isel-input", cl::Hidden, cl::desc("Print LLVM IR input to isel pass")) ("print-isel-input" , cl::Hidden , cl::desc("Print LLVM IR input to isel pass")) static
Referenced by llvm::TargetPassConfig::addISelPrepare().
PrintLSR
cl::opt< bool > PrintLSR("print-lsr-output", cl::Hidden, cl::desc("Print LLVM IR produced by the loop-reduce pass")) ("print-lsr-output" , cl::Hidden , cl::desc("Print LLVM IR produced by the loop-reduce pass")) static
Referenced by llvm::TargetPassConfig::addIRPasses().
PrintMachineInstrs
cl::opt< std::string > PrintMachineInstrs("print-machineinstrs", cl::ValueOptional, cl::desc("Print machine instrs"), cl::value_desc("pass-name"), cl::init("option-unspecified"), cl::Hidden) ("print-machineinstrs" , cl::ValueOptional , cl::desc("Print machine instrs") , cl::value_desc("pass-name") , cl::init("option-unspecified") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::TargetPassConfig::TargetPassConfig().
RegAlloc
cl::opt< RegisterRegAlloc::FunctionPassCtor, false, RegisterPassParser< RegisterRegAlloc > > RegAlloc("regalloc", cl::Hidden, cl::init(&useDefaultRegisterAllocator), cl::desc("Register allocator to use")) ("regalloc" , cl::Hidden , cl::init & useDefaultRegisterAllocator, cl::desc("Register allocator to use")) static
Referenced by llvm::TargetPassConfig::addRegAssignmentFast(), initializeDefaultRegisterAllocatorOnce(), and llvm::TargetPassConfig::usingDefaultRegAlloc().
StartAfterOpt
cl::opt< std::string > StartAfterOpt(StringRef(StartAfterOptName), cl::desc("Resume compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StartAfterOptName) , cl::desc("Resume compilation after a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and llvm::TargetPassConfig::hasLimitedCodeGenPipeline().
StartAfterOptName
const char* StartAfterOptName = "start-after"
Option names for limiting the codegen pipeline.
Those are used in error reporting and we didn't want to duplicate their names all over the place.
Definition at line 178 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason().
StartBeforeOpt
cl::opt< std::string > StartBeforeOpt(StringRef(StartBeforeOptName), cl::desc("Resume compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StartBeforeOptName) , cl::desc("Resume compilation before a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and llvm::TargetPassConfig::hasLimitedCodeGenPipeline().
StartBeforeOptName
const char* StartBeforeOptName = "start-before"
Definition at line 179 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason().
StopAfterOpt
cl::opt< std::string > StopAfterOpt(StringRef(StopAfterOptName), cl::desc("Stop compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StopAfterOptName) , cl::desc("Stop compilation after a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and llvm::TargetPassConfig::willCompleteCodeGenPipeline().
StopAfterOptName
const char* StopAfterOptName = "stop-after"
Definition at line 180 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason().
StopBeforeOpt
cl::opt< std::string > StopBeforeOpt(StringRef(StopBeforeOptName), cl::desc("Stop compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StopBeforeOptName) , cl::desc("Stop compilation before a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and llvm::TargetPassConfig::willCompleteCodeGenPipeline().
StopBeforeOptName
const char* StopBeforeOptName = "stop-before"
Definition at line 181 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason().
UseCFLAA
cl::opt< CFLAAType > UseCFLAA("use-cfl-aa-in-codegen", cl::init(CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis in CodeGen"), cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) ("use-cfl-aa-in-codegen" , cl::init(CFLAAType::None) , cl::Hidden , cl::desc("Enable the new, experimental CFL alias analysis in CodeGen") , cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) static
Referenced by llvm::TargetPassConfig::addIRPasses().
VerifyMachineCode
cl::opt< cl::boolOrDefault > VerifyMachineCode("verify-machineinstrs", cl::Hidden, cl::desc("Verify generated machine code"), cl::ZeroOrMore) ("verify-machineinstrs" , cl::Hidden , cl::desc("Verify generated machine code") , cl::ZeroOrMore) static
Referenced by llvm::TargetPassConfig::addVerifyPass().