LLVM: lib/Analysis/TargetTransformInfo.cpp File Reference
TargetTransformInfo.cpp File Reference
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/TargetTransformInfoImpl.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopIterator.h"
#include <utility>
Macros
#define DEBUG_TYPE "tti"
Functions
static bool matchPairwiseShuffleMask (ShuffleVectorInst *SI, bool IsLeft, unsigned Level)
static Optional< ReductionData > getReductionData (Instruction *I)
static ReductionKind matchPairwiseReductionAtLevel (Instruction *I, unsigned Level, unsigned NumLevels)
static ReductionKind matchPairwiseReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
static std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (Value *L, Value *R)
static ReductionKind matchVectorSplittingReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
Variables
static cl::opt< bool > EnableReduxCost ("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tti"
Definition at line 28 of file TargetTransformInfo.cpp.
Function Documentation
getReductionData()
static Optional< ReductionData > getReductionData (Instruction * I) static
Definition at line 888 of file TargetTransformInfo.cpp.
References I, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::None.
Referenced by matchPairwiseReduction(), matchPairwiseReductionAtLevel(), and matchVectorSplittingReduction().
getShuffleAndOtherOprd()
static std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (Value * L, Value * R) static
Definition at line 1048 of file TargetTransformInfo.cpp.
Referenced by matchVectorSplittingReduction().
matchPairwiseReduction()
static ReductionKind matchPairwiseReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 994 of file TargetTransformInfo.cpp.
References EnableReduxCost, llvm::User::getOperand(), getReductionData(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), Idx, llvm::isPowerOf2_32(), llvm::Log2_32(), and matchPairwiseReductionAtLevel().
matchPairwiseReductionAtLevel()
static ReductionKind matchPairwiseReductionAtLevel (Instruction * I, unsigned Level, unsigned NumLevels) static
Definition at line 911 of file TargetTransformInfo.cpp.
References assert(), llvm::User::getOperand(), getReductionData(), I, matchPairwiseReductionAtLevel(), and matchPairwiseShuffleMask().
Referenced by matchPairwiseReduction(), and matchPairwiseReductionAtLevel().
matchPairwiseShuffleMask()
static bool matchPairwiseShuffleMask (ShuffleVectorInst * SI, bool IsLeft, unsigned Level) static
Definition at line 843 of file TargetTransformInfo.cpp.
References llvm::ShuffleVectorInst::getShuffleMask(), llvm::ShuffleVectorInst::getType(), and llvm::Type::getVectorNumElements().
Referenced by matchPairwiseReductionAtLevel().
matchVectorSplittingReduction()
static ReductionKind matchVectorSplittingReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 1059 of file TargetTransformInfo.cpp.
References EnableReduxCost, llvm::User::getOperand(), getReductionData(), getShuffleAndOtherOprd(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), Idx, and llvm::isPowerOf2_32().
Variable Documentation
EnableReduxCost
cl::opt< bool > EnableReduxCost("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns.")) ("costmodel-reduxcost" , cl::init(false) , cl::Hidden , cl::desc("Recognize reduction patterns.")) static
Referenced by matchPairwiseReduction(), and matchVectorSplittingReduction().