LLVM: lib/Transforms/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "llvm/Transforms/Utils.h"
#include "llvm-c/Initialization.h"
#include "llvm-c/Transforms/Utils.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/PassRegistry.h"
Functions
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
void LLVMAddLowerSwitchPass (LLVMPassManagerRef PM)
void LLVMAddPromoteMemoryToRegisterPass (LLVMPassManagerRef PM)
void LLVMAddAddDiscriminatorsPass (LLVMPassManagerRef PM)
Function Documentation
LLVMAddAddDiscriminatorsPass()
void LLVMAddAddDiscriminatorsPass (LLVMPassManagerRef PM)
Definition at line 57 of file Utils.cpp.
References unwrap().
LLVMAddLowerSwitchPass()
void LLVMAddLowerSwitchPass (LLVMPassManagerRef PM)
Definition at line 49 of file Utils.cpp.
References unwrap().
LLVMAddPromoteMemoryToRegisterPass()
void LLVMAddPromoteMemoryToRegisterPass (LLVMPassManagerRef PM)
Definition at line 53 of file Utils.cpp.
References unwrap().
LLVMInitializeTransformUtils()
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
Definition at line 45 of file Utils.cpp.
References unwrap().