LLVM: lib/Transforms/Vectorize/Vectorize.cpp File Reference
Vectorize.cpp File Reference
#include "llvm/Transforms/Vectorize.h"
#include "llvm-c/Initialization.h"
#include "llvm-c/Transforms/Vectorize.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/InitializePasses.h"
Functions
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
void LLVMAddLoopVectorizePass (LLVMPassManagerRef PM)
void LLVMAddSLPVectorizePass (LLVMPassManagerRef PM)
Function Documentation
LLVMAddLoopVectorizePass()
void LLVMAddLoopVectorizePass (LLVMPassManagerRef PM)
Definition at line 36 of file Vectorize.cpp.
References llvm::createLoopVectorizePass(), and unwrap().
LLVMAddSLPVectorizePass()
void LLVMAddSLPVectorizePass (LLVMPassManagerRef PM)
Definition at line 40 of file Vectorize.cpp.
References unwrap().
LLVMInitializeVectorization()
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
Definition at line 32 of file Vectorize.cpp.
References unwrap().