LLVM: lib/Target/X86/X86MacroFusion.cpp File Reference
X86MacroFusion.cpp File Reference
#include "X86MacroFusion.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MacroFusion.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static FirstInstrKind classifyFirst (const MachineInstr &MI)
static JumpKind classifySecond (const MachineInstr &MI)
static bool shouldScheduleAdjacent (const TargetInstrInfo &TII, const TargetSubtargetInfo &TSI, const MachineInstr *FirstMI, const MachineInstr &SecondMI)
Check if the instr pair, FirstMI and SecondMI, should be fused together.
std::unique_ptr< ScheduleDAGMutation > llvm::createX86MacroFusionDAGMutation ()
Note that you have to add: DAG.addMutation(createX86MacroFusionDAGMutation()); to X86PassConfig::createMachineScheduler() to have an effect.
Function Documentation
classifyFirst()
static FirstInstrKind classifyFirst (const MachineInstr & MI) static
Definition at line 40 of file X86MacroFusion.cpp.
References MI.
Referenced by shouldScheduleAdjacent().
classifySecond()
static JumpKind classifySecond (const MachineInstr & MI) static
Definition at line 147 of file X86MacroFusion.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_INVALID, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, llvm::X86::COND_NO, llvm::X86::COND_NP, llvm::X86::COND_NS, llvm::X86::COND_O, llvm::X86::COND_P, llvm::X86::COND_S, llvm::X86::getCondFromBranch(), and MI.
Referenced by shouldScheduleAdjacent().
shouldScheduleAdjacent()
static bool shouldScheduleAdjacent (const TargetInstrInfo & TII, const TargetSubtargetInfo & TSI, const MachineInstr * FirstMI, const MachineInstr & SecondMI) static
Check if the instr pair, FirstMI and SecondMI, should be fused together.
Given SecondMI, when FirstMI is unspecified, then check if SecondMI may be part of a fused pair at all.
Definition at line 180 of file X86MacroFusion.cpp.
References classifyFirst(), classifySecond(), and llvm_unreachable.