LLVM: lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp File Reference
X86MCCodeEmitter.cpp File Reference
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86FixupKinds.h"
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <cstdlib>
Macros
#define DEBUG_TYPE "mccodeemitter"
Enumerations
enum GlobalOffsetTableExprKind { GOT_None , GOT_Normal , GOT_SymDiff }
StartsWithGlobalOffsetTable - Check if this expression starts with GLOBAL_OFFSET_TABLE and if it is of the form GLOBAL_OFFSET_TABLE-symbol.
Functions
static bool isDisp8 (int Value)
isDisp8 - Return true if this signed displacement fits in a 8-bit sign-extended field.
static bool isCDisp8 (uint64_t TSFlags, int Value, int &CValue)
isCDisp8 - Return true if this signed displacement fits in a 8-bit compressed dispacement field.
static MCFixupKind getImmFixupKind (uint64_t TSFlags)
getImmFixupKind - Return the appropriate fixup kind to use for an immediate in an instruction with the specified TSFlags.
static bool Is32BitMemOperand (const MCInst &MI, unsigned Op)
Is32BitMemOperand - Return true if the specified instruction has a 32-bit memory operand.
static bool Is64BitMemOperand (const MCInst &MI, unsigned Op)
Is64BitMemOperand - Return true if the specified instruction has a 64-bit memory operand.
static GlobalOffsetTableExprKind StartsWithGlobalOffsetTable (const MCExpr *Expr)
static bool HasSecRelSymbolRef (const MCExpr *Expr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mccodeemitter"
Definition at line 35 of file X86MCCodeEmitter.cpp.
Enumeration Type Documentation
GlobalOffsetTableExprKind
enum GlobalOffsetTableExprKind
StartsWithGlobalOffsetTable - Check if this expression starts with GLOBAL_OFFSET_TABLE and if it is of the form GLOBAL_OFFSET_TABLE-symbol.
This is needed to support PIC on ELF i386 as GLOBAL_OFFSET_TABLE is magical. We check only simple case that are know to be used: GLOBAL_OFFSET_TABLE by itself or at the start of a binary expression.
Enumerator
GOT_None
GOT_Normal
GOT_SymDiff
Definition at line 248 of file X86MCCodeEmitter.cpp.
Function Documentation
getImmFixupKind()
static MCFixupKind getImmFixupKind (uint64_t TSFlags) static
getImmFixupKind - Return the appropriate fixup kind to use for an immediate in an instruction with the specified TSFlags.
Definition at line 193 of file X86MCCodeEmitter.cpp.
References llvm::MCFixup::getKindForSize(), llvm::X86II::getSizeOfImm(), llvm::X86II::isImmPCRel(), llvm::X86II::isImmSigned(), isPCRel(), llvm_unreachable, llvm::X86::reloc_signed_4byte, and Size.
HasSecRelSymbolRef()
static bool HasSecRelSymbolRef (const MCExpr * Expr) static
Definition at line 274 of file X86MCCodeEmitter.cpp.
References llvm::MCExpr::getKind(), llvm::Ref, and llvm::MCSymbolRefExpr::VK_SECREL.
Is32BitMemOperand()
static bool Is32BitMemOperand (const MCInst & MI, unsigned Op) static
Is32BitMemOperand - Return true if the specified instruction has a 32-bit memory operand.
Op specifies the operand # of the memoperand.
Definition at line 208 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, assert(), llvm::MCOperand::getReg(), and MI.
Is64BitMemOperand()
static bool Is64BitMemOperand (const MCInst & MI, unsigned Op) static
Is64BitMemOperand - Return true if the specified instruction has a 64-bit memory operand.
Op specifies the operand # of the memoperand.
Definition at line 229 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MCOperand::getReg(), and MI.
isCDisp8()
static bool isCDisp8 (uint64_t TSFlags, int Value, int & CValue) static
isCDisp8 - Return true if this signed displacement fits in a 8-bit compressed dispacement field.
Definition at line 168 of file X86MCCodeEmitter.cpp.
References assert(), llvm::X86II::CD8_Scale_Mask, llvm::X86II::CD8_Scale_Shift, llvm::X86II::EncodingMask, llvm::X86II::EVEX, and isDisp8().
isDisp8()
static bool isDisp8 (int Value) static
isDisp8 - Return true if this signed displacement fits in a 8-bit sign-extended field.
Definition at line 162 of file X86MCCodeEmitter.cpp.
Referenced by isCDisp8().
StartsWithGlobalOffsetTable()
static GlobalOffsetTableExprKind StartsWithGlobalOffsetTable (const MCExpr * Expr) static
Definition at line 254 of file X86MCCodeEmitter.cpp.
References llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getRHS(), GOT_None, GOT_Normal, GOT_SymDiff, llvm::Ref, and llvm::MCExpr::SymbolRef.